### ISSUE TITLE
Project not shown in dashboard

### ISSUE THREAD

**Issue by alejoar** [getsentry/sentry#10000]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.0.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I created a project the normal way:
Add new -> project -> Django -> [input project name] -> Create project

The project is not displayed anywhere in the main page. I have several other projects displaying just fine.

If I force the url, I can find it (my-domain:9000/my-organization/project-name/), and it seem to work mostly fine, but for example it doesn't appear in the "select a project" dropdown on the top left corner of the screen:

![image](https://user-images.githubusercontent.com/6714697/46415273-36171580-c725-11e8-9f71-4065180319f1.png)

If I add it to favorties though, it does appear in the main dashboard under "bookmarked projects".

I recently migrated to another DB (postgres to postgres, I just went from a docker one to an RDS instance) so not sure if this might be the issue.

## Steps to Reproduce

1. Create new project
2. See project doesn't appear in dashboard page

### What you expected to happen

The project should be visible in the main view

**Comment by markstory** [comment]
Does your project have a team assigned to it that you belong to? You can check that by going to Project > Settings > Teams.

**Comment by alejoar** [comment]
@marksteve that was it. Sweet jesus.. 🤦🏻‍♂️
