### ISSUE TITLE
Digest for workflow emails (e.g. assign)

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#10002]
My coworker @mnoble assigned my team 10 issues all at once, and I got hit with this in my inbox:

![image](https://user-images.githubusercontent.com/2153/46429499-6d70cc80-c6fb-11e8-8c82-7c56643688ee.png)

Each email is an "Assigned" workflow email:

> You are receiving this email because you have been assigned to this issue.

More accurately it was my team that was assigned:

![image](https://user-images.githubusercontent.com/2153/46429700-f25be600-c6fb-11e8-8fcd-263d1fc95bd7.png)

---

It would be great if we could digest these like we do alerts.

**Comment by benvinegar** [comment]
I also think this is a hard requirement before implementing #3119 (bulk assign).

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
