### ISSUE TITLE
Issue Owners Page Loads Incorrect Settings when Switching Projects

### ISSUE THREAD

**Issue by mnoble** [getsentry/sentry#10003]
## Important Details

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

When you first visit the Issue Owners page, everything loads fine. Then when you switch Projects using the dropdown in the nav breadcrumbs, it does not actually load that project's config. It stays on the one initially loaded on page load.

Then, when you switch to a project again, it loads the previously selected project's config. It's basically always one project behind.

## Steps to Reproduce

GIF of it happening:

![issue-owners-load-problem](https://user-images.githubusercontent.com/36059/46431687-4c12df00-c701-11e8-880f-af15d9ee1589.gif)

1. Page loads on the `front-end` project's Issue Owners. All is good.
2. I switch Projects to the `api` project.
3. The Issue Owners config does not change and is still the `front-end` project's.
4. I switch Projects to the `front-end` project.
5. The Issue Owners config does change, but now it's displaying the `api` project's.

It's as if the config is always one project behind, as I switch projects using the dropdown.

### What you expected to happen

When you switch projects, it should load that projects Issue Owners config.

### Possible Solution

Not sure. I'm guessing it's `state` weirdness in the component?

@getsentry/app-frontend

**Comment by Chrissy** [comment]
I have noticed this on other pages too. For example if I'm looking at a chart in `data-filters` and switch projects using the dropdown, I will need to refresh the page to get the correct chart.

**Comment by billyvg** [comment]
Ah, I think an easy solution would be to define a `key` on the main view with the project slug.

**Comment by markstory** [comment]
I'll take a swing at fixing this.

**Comment by benvinegar** [comment]
Damn, what a killer bug report.
