### ISSUE TITLE
Search by event ID should point you to the exact event

### ISSUE THREAD

**Issue by hkdobrev** [getsentry/sentry#1001]
If you have multiple events in a group and you have an event ID for a specific event when you search for the ID it should redirect you to the exact event (post data, headers and browser could matter).

Right now it is redirecting you to the group page and you must find the exact event yourself.

**Comment by teeberg** [comment]
Sentry does not actually keep track of all event data for all events. Only the event IDs of all events are stored. If the general event data alone is not enough to troubleshoot, I'd recommend including whatever you need to debug it in the fingerprint.

**Comment by dcramer** [comment]
We can close this out since its somewhat configurable at this point.
