### ISSUE TITLE
duplicate react error

### ISSUE THREAD

**Issue by nightnei** [getsentry/sentry#10021]
I use `componentDidCatch` to send error, like in the new documentation. But I receive 2 errors: one is from `componentDidCatch` and another is sent from somewhere another place. Can I disable autosend errors?

```
componentDidCatch(error, errorInfo) {
      this.setState({ error });
      Sentry.configureScope(scope => {
        Object.keys(errorInfo).forEach(key => {
          scope.setExtra(key, errorInfo[key]);
        });
      });
      Sentry.captureException(error);
}
```
<img width="478" alt="screenshot 2018-10-04 18 45 57" src="https://user-images.githubusercontent.com/5598437/46486180-e2302d80-c805-11e8-9abc-e2736858fda9.png">

**Comment by kamilogorek** [comment]
@nightnei do you use development mode by any chance?

https://docs.sentry.io/clients/javascript/integrations/react/

> One important thing to note about the behavior of error boundaries in development mode is that React will rethrow errors they catch. This will result in errors being reported twice to Sentry with the above setup, but this won’t occur in your production build.

**Comment by markstory** [comment]
This issue was moved to getsentry/sentry-javascript#1617

**Comment by nightnei** [comment]
@kamilogorek you are right, thx
