### ISSUE TITLE
On-Premise: Azure DevOps Integration

### ISSUE THREAD

**Issue by iboware** [getsentry/sentry#10054]
Is it possible to add Azure DevOps integration to on-premise installations? There is a legacy vsts integration addon, but it does not work.

**Comment by markstory** [comment]
Are you looking to use the newly announced Azure DevOps integration in your on-premise install, or connect sentry with an on-premise Azure DevOps/Team Foundation Sever?

**Comment by iboware** [comment]
I'm looking for the new Azure DevOps integration. We already have  an Azure DevOps account (visualstudio.com), I tried to connect it with legacy vsts integration (9.0 latest docker image) but it seems to be non-functional. That's why I wondered, if there is a possibility to use the new DevOps integration, which is already available on SaaS version.

**Comment by markstory** [comment]
>  That's why I wondered, if there is a possibility to use the new DevOps integration, which is already available on SaaS version.

The new Azure DevOps integration will be part of the next on-premise release.

**Comment by iboware** [comment]
> > That's why I wondered, if there is a possibility to use the new DevOps integration, which is already available on SaaS version.
> 
> The new Azure DevOps integration will be part of the next on-premise release.

Thank you for the good news. :+1

**Comment by cindoum** [comment]
Is there any ETA for the next release of the on-premise version?

**Comment by markstory** [comment]
@cindoum Not right now. You're free to use the provided docker images as a starting point and upgrade sentry in-place though.
