### ISSUE TITLE
Add possibility to not send an alert if issue is marked as resolved

### ISSUE THREAD

**Issue by zozoens31** [getsentry/sentry#10081]
## Summary

When creating an alert rule, one should be able to ask only for unresolved issues to trigger an alert.

## Motivation

Once an issue is marked as resolved, say in the next release, we know other events might occur before that release, but we don't want to have these to bother us, since the fix has already been implemented.

With a condition such as 'An event is seen in an unresolved issue', or adding the resolution state in the condition 'An event {attribute} value {match} {value}', this could be avoided.

**Comment by adhiraj** [comment]
@scefali this is fixed, right?

**Comment by BYK** [comment]
Closing assuming fixed.
