### ISSUE TITLE
Resolved events are treated as unresolved with auto-resolve on (6.2.2)

### ISSUE THREAD

**Issue by rowandh** [getsentry/sentry#1010]
In Settings -> Event settings -> resolve age set to 1 hour. 

In stream view:

- Set "Status" filter to "Unresolved"
- Apply a filter for a particular tag (eg. for tag "Logger", select "javascript")
- The stream will update but will  include automatically resolved events
- Events that are manually marked as "Resolved" will not appear in the stream.

With auto-resolve disabled and by resolving events manually, I could not replicate this behaviour.

**Comment by dcramer** [comment]
Closing as wontfix for now as its overly complex
