### ISSUE TITLE
Friendlier plain-text emails

### ISSUE THREAD

**Issue by mgedmin** [getsentry/sentry#1017]
Sentry 6.3.0 thoughtfully sends multipart/alternative emails.  Unfortunately the text/plain part has some issues that make it somewhat less useful than it could be:

- the traceback is formatted as HTML
- the request table is also formatted as HTML
- the exception class and value are not displayed at all (this is actually also true of the text/html part)

I'll try to see if I can find the time to send a pull request improving the situation.  Helpful pointers to the bits of Sentry code (and tests) for formatting the notification emails would be, um, helpful.

**Comment by dcramer** [comment]
I believe all of the referenced items here have since been fixed at one point or another.
