### ISSUE TITLE
Customize or translate the user feedback form title

### ISSUE THREAD

**Issue by nuggets** [getsentry/sentry#10181]
I'd like to have the possibility to edit the title of the user feedback form (subtitle and inputs labels are in french but the title in english).

![capture_d_ecran_2018-10-18_a_14 09 51](https://user-images.githubusercontent.com/2040445/47156794-292f2000-d2e8-11e8-9026-6a1c65e79f89.png)

The sentence to update or localize : `It looks like we're having some internal issues.`

This request is linked to the closed issue #8166

**Comment by CharlieEtienne** [comment]
I have the same problem. Changing title in `Raven.showReportDialog` according to [the documentation](https://docs.sentry.io/enriching-error-data/user-feedback/?platform=laravel#customizing-the-widget) isn't working.

```
Raven.showReportDialog({
            eventId: '{{ Sentry::getLastEventID() }}',
            // use the public DSN (dont include your secret!)
            dsn: 'https://1234@sentry.io/1234',
            title: 'Il semblerait qu\'un problème soit survenu',
            user: {
                'name': 'Jean Martin',
                'email': 'jean@exemple.com',
            },
        });
```

**Comment by dcramer** [comment]
Closing this as I'm told the newer ``@sentry/browser`` correctly supports this now.

**Comment by benkindt** [comment]
I have the same problem... the title and the branding is in English, while the rest of the text is localized (German in my case).

Adjusting the titles or labels like proposed in the documentation is not working.
Setting the input of the name & email field with the user object is working though.

    Sentry.init({
        dsn: '<my_dsn>',
        beforeSend(event) {
            if (event.exception) {
                  Sentry.showReportDialog(
                        {
                             user: {
                                       name: 'Testname',
                                       email: 'test@sentry.test'
                                     },
                             title: 'Awesome Title',
                             subtitle: 'Awesome subtitle',
                             labelName: 'Awesome labelName'
                         }
                   );
               }
               return event;
         }
    });

I'm using Sentry version 9.0.0 (self-hosted).

**Comment by dcramer** [comment]
9.0 does not support custom localization of the dialog.

**Comment by NickKaramoff** [comment]
> 9.0 does not support custom localization of the dialog.

@dcramer was it removed or rather never implemented? If removed, why? If not implemented, when will it be?

**Comment by dcramer** [comment]
Did you look at the 9.1 release?

**Comment by NickKaramoff** [comment]
> Did you look at the 9.1 release?

Being honest, I had no idea it was released. Like, the website [literally says "Unreleased"](https://docs.sentry.io/server/changelog/#version-9-1-unreleased) in the Changelog. Thanks for the heads up, I'll look into it
