### ISSUE TITLE
Define a JSON schema

### ISSUE THREAD

**Issue by asbjornu** [getsentry/sentry#1018]
As the JSON serializer used in [SharpRaven](/getsentry/raven-csharp) &mdash; [Json.NET](http://james.newtonking.com/json) &mdash; [supports](http://james.newtonking.com/json/help/index.html?topic=html/JsonSchema.htm) [JSON Schema](http://json-schema.org/), it would be very valuable if Sentry could define a JSON schema for the packets it permits.

Such a schema would easen testing and validation in other clients. If such a schema already exist, then sorry; I've been unable to find it. If it doesn't, please consider creating one.

**Comment by asbjornu** [comment]
@dcramer @mattrobenolt Any progress on this?

**Comment by mindplay-dk** [comment]
Crawling through the documentation trying to write a client is error-prone and messy - it involves a lot of "let's just send it to Sentry and see what comes up on the screen", which isn't a very reliable way to build anything, and maintaining a client to keep up with changes going forward, well, don't get me started.

JSON schema is now [very close to being an official, formal spec](https://json-schema.org/).

Cloudflare offers a [suite of tools](https://github.com/cloudflare/json-schema-tools), including a validator and documentation generator, so you don't have to maintain hand-written documentation pages for the schema.

It's time.

**Comment by BYK** [comment]
I'm hoping this comes close to what is requested here: https://github.com/getsentry/sentry-data-schemas/

Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
