### ISSUE TITLE
Issue in regression email differs from actual issue when following link

### ISSUE THREAD

**Issue by adamreisnz** [getsentry/sentry#10195]
## Important Details

How are you running Sentry?
* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I received an email today regarding a regression:

![image](https://user-images.githubusercontent.com/490562/47193818-58f62a80-d3b1-11e8-8ea7-d8d5e414de0d.png)

However, when I click on the link to that issue, it opens up an issue with a completely different error message:

![image](https://user-images.githubusercontent.com/490562/47193832-68757380-d3b1-11e8-966b-ebe6e1571b33.png)

## Steps to Reproduce

1. Receive a regression email
2. Click on the issue
3. Observe that the issue from the followed link doesn't match the description in the email

### What you expected to happen

To see the same error message/description online as in the email

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by BYK** [comment]
>No one ever replied to it in the 2 years that I posted this lol.

That's why we closed the issue as I don't think this is something that will be looked into soon (if ever). I also don't know if this is still an issue. Is it? :)
