### ISSUE TITLE
API: can't create a webhook ('error_type': 'unavailable_feature')

### ISSUE THREAD

**Issue by oTree-org** [getsentry/sentry#10190]
## Important Details

How are you running Sentry?

* [x ] On-Premise docker [Version 9.0.0]

## Description

I want to use the API to automate adding a webhook to all my projects. it works fine when I do it manually here:

![image](https://user-images.githubusercontent.com/5423929/47180162-d93d7100-d35a-11e8-9ab4-4b1211a202ba.png)

But when I do it through the API using `POST /api/0/projects/{organization_slug}/{project_slug}/hooks/` as described [here](https://docs.sentry.io/api/projects/post-project-service-hooks/), the hook does not appear, and the API call has this response:

```
{'detail': ['You do not have that feature enabled'],
 'error_type': 'unavailable_feature'}
```

Other API calls work fine, such as creating a new team or project.

Even the example in the [docs](https://docs.sentry.io/api/projects/post-project-service-hooks/) shows an error response:

![image](https://user-images.githubusercontent.com/5423929/47180436-8ca66580-d35b-11e8-91be-f0460f4f8f59.png)

This example for using `GET` shows the same error I have (though I get it with POST):

![image](https://user-images.githubusercontent.com/5423929/47180490-ab0c6100-d35b-11e8-91f6-3dd73e9249d1.png)

**Comment by markstory** [comment]
You need to enable the project service hooks feature in [src/sentry/conf/server.py](https://github.com/getsentry/sentry/blob/2a37a647281fd6ad2d5003b59573ecf15187cfb1/src/sentry/conf/server.py#L848). The location in your file may be a different than master as there has been some refactoring around feature flags lately.

I'll get the documentation fixed up.

**Comment by markstory** [comment]
I did some more looking and the webhook UI you're using is part of the legacy integrations which does not use the referenced API behind the scenes.

**Comment by oTree-org** [comment]
OK Thank you! I made the change in sentry.conf.py and it works now :)

**Comment by markstory** [comment]
Great to hear. I am going to close this as I have pull requests open to fix the docs and the tooling that generates th API docs.
