### ISSUE TITLE
selery.worker.job ERROR when upgrading from 8.3 to 9.0

### ISSUE THREAD

**Issue by irados** [getsentry/sentry#10196]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 17.09.0-ce]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Upgraded sentry to 9.0. 
"sentry upgrade" done without the problems.
Now worker logs explode with constantly errors:

{"log":"06:56:32 [ERROR] celery.worker.job: Task sentry.tasks.post_process.post_process_group[aa0fcdb7-e55f-4315-9c58-23d106a4d419] raised unexpected: ProgrammingError('ProgrammingError(\\'column sentry_rule.environment_id does not exist\\\\nLINE 1: ...T \"sentry_rule\".\"id\", \"sentry_rule\".\"project_id\", \"sentry_ru...\\\\n                                                             ^\\\\n\\',)\\nSQL: SELECT \"sentry_rule\".\"id\", \"sentry_rule\".\"project_id\", \"sentry_rule\".\"environment_id\", \"sentry_rule\".\"label\", \"sentry_rule\".\"data\", \"sentry_rule\".\"status\", \"sentry_rule\".\"date_added\" FROM \"sentry_rule\" WHERE (\"sentry_rule\".\"project_id\" = %s  AND \"sentry_rule\".\"status\" = %s )',) (data={u'hostname': 'celery@ca6441821615', u'name': 'sentry.tasks.post_process.post_process_group', u'args': '[]', u'internal': False, u'kwargs': \"{'group': \u003cGroup at 0x7f4ef0ef4050: id=15205L, project_id=1L\u003e, 'is_new_group_environment': False, 'is_new': False, 'event': \u003cEvent at 0x7f4ef0eded90: id=None, project_id=1L, group_id=15205L\u003e, 'is_regression': None, 'is_sample': True, 'primary_hash': '47b1ad29aafb34362693e841c9f659f7'}\", u'id': 'aa0fcdb7-e55f-4315-9c58-23d106a4d419'})\n","stream":"stdout","time":"2018-10-19T06:56:32.848114008Z"}

Have tried "sentry upgrade" again, but no changes.

**Comment by markstory** [comment]
> ProgrammingError(\'column sentry_rule.environment_id does not exist

Does the column in the error message exist in your database?

**Comment by irados** [comment]
Hi Mark, no idea where I should look for it (which database / table). I have a postgresql backend.

**Comment by markstory** [comment]
I don't know the database name as that is something you could have customized, but often its called `sentry`. The table is `sentry_rule`.

**Comment by irados** [comment]
no. sentry_rule doesn't have column environment_id.

**Comment by irados** [comment]
hi mark, thanks for your help. It helped me to understand that I can redo upgrade by deleting entries in the south_migrationhistory. 
After that, a new "sentry upgrade" solved the problem. thx.

**Comment by irados** [comment]
hi mark, thanks for your help. It helped me to understand that I can redo upgrade by deleting entries in the south_migrationhistory. 
After that, a new "sentry upgrade" solved the problem. thx.
