### ISSUE TITLE
Release Timeframe?

### ISSUE THREAD

**Issue by BoLaMN** [getsentry/sentry#10207]
Hey Guys, 

is there a new release dropping anytime soon, noticed theres been 2144 commits since v9.0.0 where usually there was a version increment every ~200 - 300 previously.

Cheers

**Comment by Sija** [comment]
Hi, any news regarding new release?

**Comment by dcramer** [comment]
We have no timeline on when a version will be tagged. I recommend simply pinning to git shas and building from source instead.

**Comment by nlohmann** [comment]
I would also be interested in when a 9.x release is coming, because we are neither allowed to deploy .0.0 releases nor can we pin git shas. So basically as soon as you would release a 9.1.0, we could finally use the 9.x features :-)

**Comment by agis** [comment]
@dcramer Are there any *rough estimates* on when new release might come out? We, like @nlohmann, prefer to use a (somewhat) stable release instead of pinning to a commit that might contain soon-to-be-fixed, knnown issues.

Happy new year!

**Comment by dcramer** [comment]
It's possible we'll do a 9.1 release before we switch some hard requirements over, but its something we have to talk about internally yet before doing the 10.0 release.

We're also talking about changing off a semver release cycle and just doing monthly tags.

The major thing is we're going to be making two hugely breaking infrastructural changes:

1. You'll be required to run our new "Snuba" search and indexing services (this will be detailed later)
2. We'll no longer support any database other than Postgres -- we say that in the docs today, but have tried to maintain a degree of compatibility

**Comment by agis** [comment]
> The major thing is we're going to be making two hugely breaking infrastructural changes

@dcramer is there going some sort of upgrade guide for those running Sentry on-premises?

**Comment by dcramer** [comment]
There certainly will be, but it's going to contain the same caveats as we've always had: "you need to know how to run this software or you're SOL". Unfortunately those caveats will get a lot more bold with the new services.

This also currently exists, and we've documented major requirements in the past: https://docs.sentry.io/server/upgrading/

**Comment by nschlemm** [comment]
(unfortunately) https://forum.sentry.io/t/is-sentry-v10-coming-soon/5093/2 states
> “Sentry 10” is coming soon, whether we call it that or not, but open source users probably won’t be as excited as it’ll require running our new Snuba service (which is an API layer on top of Clickhouse). We’ll talk more about this in the future, but the tl;dr is its going to unfortunately be a lot harder to run yourselves because of the nature of the datastore changes.

and while https://hub.docker.com/r/getsentry/snuba links to https://github.com/getsentry/snuba it is not accessible (yet)

@dcramer can you share details what timeframe we all can expect here? And big THX for this awesome Open Source product!!!

**Comment by Sija** [comment]
@dcramer Couldn't analytics support be optional?

**Comment by Sija** [comment]
@dcramer oh, my bad. I thought you use snuba/clickhouse for analytics.

**Comment by dcramer** [comment]
Closing this out and going to keep it to the forums. 

I've also taken a bit of time this morning to try to write up a more cohesive explanation of what's going on:

https://forum.sentry.io/t/when-will-a-new-version-be-tagged-for-sentry-open-source/5622
