### ISSUE TITLE
Sentry trying to get sourcemaps from other domain

### ISSUE THREAD

**Issue by jpic** [getsentry/sentry#10210]
Hello,

Thanks for making the most beautiful software, one of my favorites ever !

Is it normal that exception on www.mrs.beta.gouv.fr show a failure trying to get the sourcemaps from another environment, here, staging.mrs... ?

![2018-10-22-130105_946x899_scrot](https://user-images.githubusercontent.com/94636/47289416-e4aec780-d5fa-11e8-9208-a5a0e5771cbd.png)

Thanks !

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
