### ISSUE TITLE
Issue activity item for updating linked statuses

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#10259]
Not 100% sure this is a great idea, but when Sentry marks an external issue (e.g. Jira) as resolved, it would be nice to see that an activity item to understand it took place.

Here's an example of what it might look like:

![image](https://user-images.githubusercontent.com/2153/47463158-4ce7df80-d79a-11e8-9685-973b9aa9ca3b.png)

Some other thoughts:
* It should probably just be statuses (created/linked, opened, resolved, etc.)
* It should _not_ be comment syncing (seeing "Sentry posted a comment on Jira" after every comment would be irritating)
* Should probably include an icon of the external tracker (e.g. Jira icon, GitHub icon), since its possible to have multiple external trackers per project

**Comment by lauryndbrown** [comment]
I agree. I honestly think we should have something that says what's going on with syncing. 
I.e. `Sentry attempted to sync with external issue, but failed.` Currently there's no user visibility into issue sync at all.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
