### ISSUE TITLE
Slack Integration: I connected it but setting page said it still not installed

### ISSUE THREAD

**Issue by TylorShin** [getsentry/sentry#10268]
I've got a message at the slack 
```
Sentry APP [3:01 PM]
was added to this conversation by tylor_shin.
```

However my setting page still show me
```
Slack
Not Installed
Learn More
```

I need help to solve this problem.

**Comment by markstory** [comment]
Where/how are you running sentry?

**Comment by TylorShin** [comment]
@markstory 
> Where/how are you running sentry?

I'm using sentry as their own server(sentry.io)
and our project uniqueId is 'pluto-network'

**Comment by TylorShin** [comment]
And I tried to install slack again, the popup window said,
`Sentry is already installed on Pluto.`
However, it still shows me not-installed status.

**Comment by TylorShin** [comment]
NVM. it works fine now.
I'll close this issue. thanks.
