### ISSUE TITLE
Add user comment to User Feedback notification e-mail

### ISSUE THREAD

**Issue by prajmus** [getsentry/sentry#10284]
## Summary

Currently the e-mail alert about User Feedback only contains: "User feedback from: email@server.com and Tags. It'd be much more helpful to get the user comment here as well. The comment is the equivalent of the Stack Trace that appears in e-mails about exceptions, but yet it is not included into the e-mail.

## Motivation

Some user feedback are bug related and may contain additional information that will help resolve other issues. It seems it'd be helpful to include it in the mail.

**Comment by dcramer** [comment]
It looks like comments are included as per master, but its possible this wasn't in 9.0.
