### ISSUE TITLE
'You don't have access to any organizations within Sentry. Talk to a Sentry " "administrator about getting access.‘

### ISSUE THREAD

**Issue by icrisman** [getsentry/sentry#10285]
## Important Details
I cannot register a new user, it will display：'You don't have access to any organizations within Sentry. Talk to a Sentry " "administrator about getting access.‘

## Description

I cannot register a new user, it will display：'You don't have access to any organizations within Sentry. Talk to a Sentry " "administrator about getting access.‘

**Comment by untitaker** [comment]
When you create the database it will ask you whether you want to create a superuser. This is the administrator.

**Comment by icrisman** [comment]
> When you create the database it will ask you whether you want to create a superuser. This is the administrator.

I know that，and I have created an administrator, but when I go to register another account, it always show the above prompt, and I have authorized it with the administrator, but the new account is still displaying the prompt "You don' t have access to any organizations within Sentry. Talk to a Sentry administrator about getting access."

**Comment by Sector95** [comment]
If you haven't already, after creating a user, you need to add them to the project under Organization Settings -> Members.

**Comment by TONYHOKAN** [comment]
hi, i login as admin and go to http://localhost:9000/settings/sentry/members/new/, i cannot search exiting created account user to add to organization, is that only allow add user by invitation email?

**Comment by yzhang226** [comment]
yes, after using version 9, i run into this issue.
how can i do with this?

**Comment by halimb** [comment]
I'm having the same issue here after registering a user.
PS: I made sure the user is indeed added to the organization and even a project and team.
Any ideas on how to solve this?

**Comment by hAh0L13** [comment]
Same problem with Sentry 9.1.2 deployed in K8s with helm/stable

Checked the “Allow registration” setting to True in http://{sentry-root}/manage/settings / and tried to add SENTRY_FEATURES [“auth: register”] = True to sentry.conf.py

Registered user see "No Organization Access" and cannot be added to organization/team by admin

**Comment by port22** [comment]
this problem still exists with v10 - any progress here?

**Comment by izenk** [comment]
+1
Issue exists in v10
User is not attached to any org and Superuser can't add

**Comment by wynemo** [comment]
after the user registered, you need to add him by this way:
http://localhost:9000/settings/sentry/members/

![image](https://user-images.githubusercontent.com/1314428/84660064-e5703c00-af4a-11ea-98a1-4f742af040a9.png)

then get the invitition link

![image](https://user-images.githubusercontent.com/1314428/84660273-2cf6c800-af4b-11ea-8b94-cfbc7533065d.png)

let the use click this link, then he can login in.

somewhat complicated..

**Comment by BYK** [comment]
I _think_ this is fixed so closing. Please comment here if you are still experiencing this with a recent version of Sentry.
