### ISSUE TITLE
Order Suggested Assignees by Issue Owners rule match order

### ISSUE THREAD

**Issue by jeremymailen** [getsentry/sentry#10315]
## Summary

When there are multiple suggested assignees the UI and API appear to return them in alphabetic order.
It would be more useful if it returned them in the order the rules matched. For example a rule higher up the list would cause the assignee to appear earlier in the list.

## Motivation

This would allow rules to be written specific to general, for example:

```
path: src/email/sender/* emailexpert@dev.org
path: * serviceowner@dev.org
```
The UI would then help guide the user to click on the higher ranked owner.
We are automating assignment via the API and this would allow the automation script to choose the first, highest ranked suggested owner as the assignee.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
