### ISSUE TITLE
Audit log overflow with IPv6 IPs

### ISSUE THREAD

**Issue by nepeat** [getsentry/sentry#10316]
## Important Details

How are you running Sentry?

* [X] On-Premise docker [Version 9.1.0.dev0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

When opening the Audit Log for an organization and changes are made with an IPv6 IP, the IP overflows out of the table.

## Steps to Reproduce

1. Make auditable changes with an IPv6 IP
2. Open the Audit Log

![image](https://user-images.githubusercontent.com/6914822/47679808-569a8a00-db82-11e8-8646-ffb848fb9f57.png)

### What you expected to happen

It should not be overflowing :O

**Comment by markstory** [comment]
Closing as there is a pull request open to fix this.

**Comment by nepeat** [comment]
Reopening, seems to be happening again.

Docker On Premise v10 digest 008d39fed70c6b80c23dd6f1a5d332903259a77e9c5149fe1c6213c1c6452ede
