### ISSUE TITLE
Doesn't work tag removing 

### ISSUE THREAD

**Issue by iKBAHT** [getsentry/sentry#10327]
## Important Details

How are you running Sentry?

* [ ] Saas (sentry.io)

## Steps to Reproduce

1. go to https://sentry.io/settings/topsteam/maat/tags/
2. remove tag "url"
3. see 
<img width="931" alt="2018-10-30 17 02 53" src="https://user-images.githubusercontent.com/922404/47723499-b28a0f00-dc65-11e8-936e-c0b769ec7c7b.png">

### What you expected to happen

Tag will be remove

**Comment by markstory** [comment]
Do you only have this issue with the `url` tag? or can you not remove any tags?

**Comment by larsmars** [comment]
I have the same.

Project - Settings - Tags - Hit recycle bin - Confirm

```
Oops! Something went wrong
It looks like you've hit an issue in our client application. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

If you're daring, you may want to try the following:

Give it a few seconds and reload the page.
If all else fails, create an issue with more details.

```

Reload, same error
Resolved errors with tag to delete, same error
Sign out/in, same error

Tag was added like this and worked perfect.

```
    Sentry.withScope(scope => {
      scope.setTag('myTagName', 'myTagValue')
      Sentry.captureException(error)
    })
```

"@sentry/browser": "^4.5.3",
Chrome: 71.0.3578.98 (Offisiell delversjon) (64-bit)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
