### ISSUE TITLE
Error in migration: sentry:0345_add_citext

### ISSUE THREAD

**Issue by atlas1119** [getsentry/sentry#10328]
Error in migration: sentry:0345_add_citext

The error was: OperationalError('\xe9\x94\x99\xe8\xaf\xaf:  \xe6\x97\xa0\xe6\xb3\x95\xe6\x89\x93\xe5\xbc\x80\xe6\x89\xa9\xe5\xb1\x95\xe6\x8e\xa7\xe5\x88\xb6\xe6\x96\x87\xe4\xbb\xb6 "/usr/pgsql-9.6/share/extension/citext.control": \xe6\xb2\xa1\xe6\x9c\x89\xe9\x82\xa3\xe4\xb8\xaa\xe6\x96\x87\xe4\xbb\xb6\xe6\x88\x96\xe7\x9b\xae\xe5\xbd\x95\n',)

CREATE EXTENSION IF NOT EXISTS citext

**Comment by mattrobenolt** [comment]
Sounds like there’s something weird or wrong with your Postgres.

What happens when you run that directly from psql?
