### ISSUE TITLE
Jira Integration: Install/Configuration Loop

### ISSUE THREAD

**Issue by epicserve** [getsentry/sentry#10329]
I'm trying to install and setup the JIRA integration but I'm in a loop that I can't seem to get out of. I'm doing the following:

* Go to Organizational Settings > Integrations
* I see the following 
<img width="449" alt="oeie 2018-10-30 09-36-32" src="https://user-images.githubusercontent.com/191620/47725862-57d1c280-dc27-11e8-862b-e15b963fec3d.png">
* Click on Install and then click on the "Jira Marketplace" button.
* Click on Get it Now (The first time, it asked me for permission and I accepted everything)
* Click on Manage
<img width="517" alt="atlassian marketplace for jira - jira 2018-10-30 09-39-40" src="https://user-images.githubusercontent.com/191620/47726084-c31b9480-dc27-11e8-9526-7fc7e8039fff.png">
* Click on Configure
<img width="515" alt="manage add-ons - jira 2018-10-30 09-40-31" src="https://user-images.githubusercontent.com/191620/47726135-e1819000-dc27-11e8-9079-10396c3f03b2.png">
* Click Sign In to Sentry
<img width="392" alt="configure sentry add-on - jira 2018-10-30 09-41-31" src="https://user-images.githubusercontent.com/191620/47726228-0a098a00-dc28-11e8-9895-7fdb3c6d56c3.png">
* It then takes me back to the sentry dashboard and then if I go to Organizational Settings > Integrations, it doesn't show that Jira is installed and so I would have to repeat all the steps again with the same results.

**Comment by markstory** [comment]
How are you running Sentry? Is it an on-premise install or via sentry.io|

**Comment by epicserve** [comment]
@markstory, it's via sentry.io.

**Comment by EvanPurkhiser** [comment]
@epicserve After ensuring that you're logged into sentry, if you go back to the Jira settings page for Sentry, does it still ask you to login? You should be presented with a list of your sentry organizations to enable the integration on.

**Comment by epicserve** [comment]
@EvanPurkhiser, if I refresh the page/url (https://<our-org-slug>.atlassian.net/plugins/servlet/ac/sentry.io.jira/configure-sentry), it still asks me to sign in to Sentry, even though I'm signed in.

As a side note and data point, I'm using the latest Chrome (70.0.3538.77).

**Comment by epicserve** [comment]
@EvanPurkhiser, I just tried in Firefox and got it to work. Maybe it was one of my plugins in Chrome or something.

**Comment by georges** [comment]
I'm experiencing the same problem with Safari
