### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by pacolotero** [getsentry/sentry#1037]
How I can use Sentry with LDAP?

**Comment by ChadKillingsworth** [comment]
I created an LDAP extension specifically for Sentry. It extends the functionality of the standard `django-auth-ldap` plugin with some Sentry specific actions.

The main features are it marks LDAP created accounts as managed so users can't change their password (or other managed fields). You can also auto-add them to an Organization with specific access.

It wouldn't take a lot to auto-add them to teams based on LDAP groups, but I don't have a use case myself for that. However if someone wants to add it and issue a PR, I'll be happy to merge it.

**Comment by ChadKillingsworth** [comment]
Since the documentation probably won't be published for a bit, here's the plugin link: https://github.com/Banno/getsentry-ldap-auth

**Comment by dcramer** [comment]
Going to go ahead and close this ticket out. the getsentry-ldap-auth is a good enough solution for a lot of people, and we'll provide a full on SSO package for others.
