### ISSUE TITLE
Robot eye animation on a new project (no issues logged) eats cpu

### ISSUE THREAD

**Issue by femaref** [getsentry/sentry#10381]
## Important Details

How are you running Sentry?

on-premise w/o docker 9.0.0

## Description
Chrome 70.0.3538.77

When on a project issue page with no issues present, the blinking red eye eats my cpu alive (late 2011 macbook pro). Deactivating the animation reduces the cpu to 0% for that tab.

## Steps to Reproduce

1. open a project with no issues tracked

### What you expected to happen

not eat my cpu alive

**Comment by markstory** [comment]
Any suggestions on how that animation could be done in a non-CPU intensive way? It is using CSS animations already.

**Comment by lynnagara** [comment]
According to https://stackoverflow.com/questions/13176746/css-keyframe-animation-cpu-usage-is-high-should-it-be-this-way simply adding `transform: translateZ(0);` to that element will reduce cpu usage
