### ISSUE TITLE
Jira Integration: 

### ISSUE THREAD

**Issue by KorashHernandez** [getsentry/sentry#10386]
I have enabled the add-on in JIRA via the "install" button in the sentry settings section, then selecting it i9n the Atlassian marketplace. I then integrated it to JIRA and pointed it at my organization in sentry ("Tangle Inc." - this is the legacy name) but in Sentry under integrations it still says: "Not Installed"

What am I doing wrong?
![image](https://user-images.githubusercontent.com/19277211/47870536-25b79080-dde0-11e8-89c6-c07015557377.png)

![image](https://user-images.githubusercontent.com/19277211/47870548-31a35280-dde0-11e8-89a9-64aba11e285a.png)

**Comment by markstory** [comment]
Closing as this issue has gone stale. Please reply back if you're still having issues.
