### ISSUE TITLE
Filter notifications by TaggedEventCondition

### ISSUE THREAD

**Issue by mabrahamde** [getsentry/sentry#1041]
You can filter notification within a project based on tags.

However it would be great if you could perform this filtering based on TaggedEventCondition. Using TaggedEventConditions (see commit b631520cef923ae6d0b6eadcea2ec0966c7b4135) it would be easily possible to e.g. exclude certain urls from the notification.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
