### ISSUE TITLE
Jira Integration: should we use the org integration or the project integration?

### ISSUE THREAD

**Issue by koreno** [getsentry/sentry#10414]
It seems that the organization integration for Jira is "Enabled", but unless we turn on the legacy Jira integration at the project level, we don't get the ability to link/open tickets into jira.

**Comment by markstory** [comment]
If you are using sentry.io you should use the organization level integration. The project integration will be dropped in the future.

If you are not seeing link issue buttons in the right sidebar you should disconnect and then reconnect the integration.

**Comment by lauryndbrown** [comment]
@koreno I'm sorry you're having trouble. If you have the Jira app installed then, most likely you have not configured your Jira Integration and are still relying on the old version. Our docs aren't adequate in this area. I'll see if I can't fix that in the coming days. In the meantime:

<img width="1362" alt="screen shot 2018-11-08 at 11 13 29 am" src="https://user-images.githubusercontent.com/12959365/48221602-5ef38180-e347-11e8-892d-2157e5eb947e.png">

Click the configure button. It'll take you to this page, where you can select the organizaitons you want to enable it for.

<img width="1540" alt="screen shot 2018-11-08 at 11 15 41 am" src="https://user-images.githubusercontent.com/12959365/48221760-c5789f80-e347-11e8-8a7f-4e3b3186e14f.png">

**Comment by markstory** [comment]
Closing as this issue has gone stale. If you're still having issues please reply back.
