### ISSUE TITLE
On-Premise Python installation doc missing PostgreSQL `citext` extension

### ISSUE THREAD

**Issue by lastmikoi** [getsentry/sentry#10418]
## Important Details
How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [x] Other [briefly describe your environment]

On-Premise *traditional*
CentOS7 virtual machine (Vagrant + VirtualBox)
Configuration via SaltStack 2017.7.8
PostgreSQL 10.5 (from [upstream repositories](https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7.5-x86_64/))
Redis-server 3.2.12 (from EPEL7)
Git snapshot (5b7216edf0d2c4e11330223e36b800fdc7140c07)

## Description

Upon following the `sentry upgrade` step of https://docs.sentry.io/server/installation/python/#running-migrations, the migration fails at `sentry:0345_add_citext`:
```
FATAL ERROR - The following SQL query failed: CREATE EXTENSION IF NOT EXISTS citext
The error was: ProgrammingError('permission denied to create extension "citext"\nHINT:  Must be superuser to create this extension.\n',)
```

My sentry database user being unprivileged, it is indeed unable to create the extension.
Afterwards, and even with creating the extension from a privileged user, one is forced to re-start the installation from scratch in order to avoid further errors such as the ones mentioned in #9642 

### What you expected to happen

I expected the documentation not to assume that the database user was privileged.

### Possible Solution

Documenting the extension creation process before starting `sentry upgrade` should do the trick, for me it was as follows:
```
[root@allinone-test vagrant]# su - postgres
Last login: lun. nov.  5 16:43:23 UTC 2018 on pts/0
-bash-4.2$ psql
psql (10.5)
Type "help" for help.

postgres=# \c sentry
You are now connected to database "sentry" as user "postgres".
sentry=# CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION
```

Thanks and stay awesome.

**Comment by markstory** [comment]
We don't support CentOS, and recommend that you use an Ubuntu based distribution or docker.

**Comment by harmv** [comment]
NB: This problem is not  related to the distribution. It is not CentOS specific, this happens on ubuntu too.

This problem appears if you want to install sentry as a non root user.  (which is sensible thing to do).

So updating the documentation might be helpful.   (https://docs.sentry.io/server/installation/python/)
