### ISSUE TITLE
Java Source Maps

### ISSUE THREAD

**Issue by fprochazka** [getsentry/sentry#10435]
## Summary

I would like to be able to see sources in stacktraces of java exceptions, the same way they're visible for javascript.

## Motivation

This would improve my ability to see the problem in the context of my application.

## Additional Context

Sentry java client, should be able to access `classpath` of the running application and build process should be able to provide versions of installed libraries and built artefacts. Combining these two informations, Sentry should be able to render source code of Java. This would allow you to render on at least *some* frames of the stacktrace (there will always be generated/proxy frames, that will have no "visible" source code available).

By uploading correct artifact (with sources) to a release, I should be able fill in the main part - source code of my own application.

And it would be ideal, if fetching "public" maven jars with sources could be a native part of Sentry, since these libraries take up a massive amount of disk storage, and if they would duplicate on each release, this would be unfeasible. Having a shared cache between releases would be ideal.

**Comment by untitaker** [comment]
Please file this against https://github.com/getsentry/sentry-java

**Comment by fprochazka** [comment]
@untitaker I can do that, but I don't see how sentry-java library can solve this, since this requires direct support of the "core". Or do you just track this kind of issues there knowing this has to be solved in the core?

**Comment by untitaker** [comment]
I think it's better to keep lang-specific issues in sdk trackers even if they have to be fixed in sentry itself

**Comment by fprochazka** [comment]
@untitaker ok, good to know!  :)
