### ISSUE TITLE
Custom fingerprints are overwritten by captureException or captureMessage

### ISSUE THREAD

**Issue by BlitZz96** [getsentry/sentry#10467]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Custom fingerprints are overwritten on submition with either `captureException` / `captureMessage`.
## Steps to Reproduce

1. Sit fingerprints:
```Javascript
Sentry.configureScope(scope => {
  scope.setFingerprint([
    String(exampleVar),
    exampleVar2,
    "OhNoes"
  ])
});
```
2. Capture an exeption / message:
```Javascript
Sentry.captureMessage("This is an error msg");
```
3. Inspect network call and see fingerprints overwritten to the captureMessage ~ `["This is an error msg"]`

[Reproduced JsBin Example](https://jsbin.com/lumiqusulu/1/edit?js)

### What you expected to happen

The user provided fingerprints to be sent back to sentry. Not overwritten.

### Possible Solution
No idea so far.

**Comment by markstory** [comment]
This issue was moved to getsentry/sentry-javascript#1721
