### ISSUE TITLE
Autocomplete gets in the way of issue search results

### ISSUE THREAD

**Issue by lauryndbrown** [getsentry/sentry#10485]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I'm using Chrome. It's pretty irritating if I need to click the first one, as the search results can disappear if I click away to remove the autocomplete. 

![image](https://user-images.githubusercontent.com/12959365/48220396-0373c480-e344-11e8-9b7a-2e86e4fb593a.png)

## Steps to Reproduce

1. Type something into the Link issue box.

**Comment by markstory** [comment]
I'm not sure this is going to be fixable as there are a bunch of layers between our code and the input element. Notably `react-select` doesn't allow us to turn off browser autocompletion.
