### ISSUE TITLE
Name of Linked Issues can Wrap New Line

### ISSUE THREAD

**Issue by lauryndbrown** [getsentry/sentry#10484]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description
Not even totally sure if this is a bug. But letting you know this happens.

![image](https://user-images.githubusercontent.com/12959365/48220226-9d873d00-e343-11e8-9285-db802b950411.png)

## Steps to Reproduce

1. Link an issue with a long project and organization name.

**Comment by markstory** [comment]
Closing as a pull request is open now.
