### ISSUE TITLE
Linked Issue Hover card doesn't change without page refresh

### ISSUE THREAD

**Issue by lauryndbrown** [getsentry/sentry#10488]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description
Issue Hover card looks like this:

<img width="438" alt="screen shot 2018-11-08 at 11 02 59 am" src="https://user-images.githubusercontent.com/12959365/48221075-e809b900-e345-11e8-95a4-3cb792d67ff5.png">

Until you refresh the page. Then it looks like this:

<img width="451" alt="screen shot 2018-11-08 at 11 00 57 am" src="https://user-images.githubusercontent.com/12959365/48221031-c577a000-e345-11e8-8158-6c737d71af7e.png">

## Steps to Reproduce

1. Link an issue. 
2. Hover over it
3. Refresh the page
4. Hover over the issue again.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
