### ISSUE TITLE
Exception message/description not showing

### ISSUE THREAD

**Issue by garvankeeley** [getsentry/sentry#10507]
_Platform:_
- [x ]  iOS
_Swift:_
- [x ]  Yes -> If yes, which version? Version 4
_sentry-cocoa installed with:_
- [x ] Carthage
Version of sentry-cocoa: "4.0.1"

I have following issue:

Most exception crashes are not showing the exception message, just the type
Most crashes are reported like (showing the top-level title from the Sentry report):
`NSInternalInconsistencyException<redacted>`
not
`Could not find index of tab to remove`

**Steps to reproduce:**
- Look at crashes on https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-release-13/

**Actual result:**
- Most crashes show the exception type not the message

**Expected result:**
- Messages shown for the exception.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
