### ISSUE TITLE
Want to see errors happening on a specific date

### ISSUE THREAD

**Issue by gomobileas** [getsentry/sentry#10509]
Hi.

I know that I can use
- event.timestamp:2018-10-27 
or event.timestamp:<2018-10-27 
or event.timestamp:>2018-10-27 

to filter and find events that happened on a given date or on date intervals.

But when I filter like this:  event.timestamp:2018-10-27 the events happening this day are shown, but the latest version of this event is shown.
I want to see the version of these events happening on the given date.
Is this possible ?

**Comment by markstory** [comment]
>  I want to see the version of these events happening on the given date. Is this possible ?

No this is not currently possible because sentry groups events together into 'issues' which is what you see in the UI.
