### ISSUE TITLE
Logger name in issue titles are pushed to a new line

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#10532]
## Description

The title was changed into a block level element so that long titles wouldn't overflow (#10290) - this now causes the logger name to be pushed onto a newline:

![image](https://user-images.githubusercontent.com/79684/48366223-06332a00-e662-11e8-9b16-790ec1cd0b45.png)

**Comment by harishkrao** [comment]
Is this still available? If yes, can I take this?

**Comment by billyvg** [comment]
@harishkrao Yes it's still available, please make sure that we have ellipsis when description content overflows. Thanks!

**Comment by harishkrao** [comment]
I have started working on this, sorry for the delay. Is there a way I can get access to Sentry? I tried signing up with GitHub, but the Google authentication is failing.

**Comment by billyvg** [comment]
@harishkrao You can run sentry locally and use `bin/load-mocks` to get fake data into your instance.

**Comment by ezzy1337** [comment]
Looks like this has been dead about a year. I'll take a look to score one of those tasty Hacktoberfest points.

**Comment by billyvg** [comment]
Bad me, I forgot to link back to this issue, but it was closed in https://github.com/getsentry/sentry/pull/13998

cc @ezzy1337 

I will try to find some other Hacktoberfest issues though
