### ISSUE TITLE
Switching between organizations with different installations installed can cause a crash

### ISSUE THREAD

**Issue by lauryndbrown** [getsentry/sentry#10564]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Gif of behavior: https://cl.ly/147141fb1f0b

## Steps to Reproduce

1. Have one organization with Integration A and another organization that does not have integration A 
2. Navigate to Integration A configure page.
3. Using the drop down for organizations, switch to an org that does not have Integration A
4. See the crash page

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
