### ISSUE TITLE
Jira Installation docs

### ISSUE THREAD

**Issue by lauryndbrown** [getsentry/sentry#10566]
## Summary

Jira needs to be configured post install from the market place. Currently we have a small yellow box saying something. But nice pictures or in app docs would be very useful for Jira considering **every step of the installation process** happens outside of Sentry.io. Something similar to my response here: https://github.com/getsentry/sentry/issues/10414

<img width="624" alt="screen shot 2018-11-13 at 11 22 44 am" src="https://user-images.githubusercontent.com/12959365/48437560-7dd28900-e736-11e8-851e-6a6feff044e4.png">

## Motivation

Ease of use. I noticed a couple people asking in the issues here about how to configure jira: 
https://github.com/getsentry/sentry/issues/10414
https://github.com/getsentry/sentry/issues/10386

**Comment by BYK** [comment]
We now have this: https://docs.sentry.io/product/integrations/jira/
