### ISSUE TITLE
Rewrite OriginsField to use a custom validator

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#1057]
This will allow us to wrap up all of the logic in one place instead of treating it like a URLField.

This will let us solve some of the issues around weird urls that happen from raven.js, like `chrome-extension://`.

See: https://github.com/getsentry/raven-js/issues/157

**Comment by mattrobenolt** [comment]
Need to look at this again to see if it's still a problem.

**Comment by mack7121** [comment]
If this is still an issue, I want to help.

**Comment by dcramer** [comment]
Doesn't look like this is still a problem, as we have simple custom URL parsing here.
