### ISSUE TITLE
[Feature request] sentry.interfaces.Command

### ISSUE THREAD

**Issue by ezzatron** [getsentry/sentry#1058]
A useful addition to Sentry's [interfaces](http://sentry.readthedocs.org/en/latest/developer/interfaces/) would be an interface for logging console command information. This would be similar to what `sentry.interfaces.Http` does for HTTP request related events.

This interface could be used to display the executable path, arguments and options, environment variable values, hostname and more. All of these are useful when tracking down events that occur inside command-line scripts (especially when triggered by a scheduler).

**Comment by dcramer** [comment]
GH-1092 will resolve this
