### ISSUE TITLE
Data cleaning solution

### ISSUE THREAD

**Issue by liuqu11** [getsentry/sentry#10620]
## Summary

Our current production environment has a log volume of 100g. Is there any time to clear the script and only keep a log for one month?

## Motivation

The log growth per month is 100g, but we only pay attention to the log for this month. The previous log does not need to be retained.

Can I have any plans now?

**Comment by mattrobenolt** [comment]
`$ sentry cleanup`

https://docs.sentry.io/server/cli/cleanup/
