### ISSUE TITLE
No referring url on error page

### ISSUE THREAD

**Issue by warmwhisky** [getsentry/sentry#10650]
I cannot for the life of me see the referring url of the error in my account. I have searched google and the sentry docs but I am still not able to see it.

Does it exist in the Sentry?

**Comment by markstory** [comment]
Which SDK are you using? How do you have it setup?

**Comment by warmwhisky** [comment]
I'm currently using Sentry with Laravel 5.3
`"sentry/sentry-laravel": "^0.10.1"`

I usually have a little difficulty setting it up because I also use the name conflicting package `"rydurham/sentinel": "^2.5"`

![2018-11-19_1639](https://user-images.githubusercontent.com/579186/48713766-d663c380-ec19-11e8-8a6d-253f9b61890f.png)
I would have thought to see referrer url in the above tags list, but I cannot see it anywhere on the page. I have sentry setup on a few apps, but have never been able to find the referrer url.

**Comment by markstory** [comment]
What makes you believe you should be seeing the referrer URL? is it in the documentation?

**Comment by warmwhisky** [comment]
I assumed there would be a referring url for errors that have a referring url.
I did mention that I could not find it in the docs. Which is why I wondered if it existed in Sentry.

**Comment by markstory** [comment]
I took a look at the documentation as well, and if you want the referring URL you can add it via tags via [custom context](https://github.com/getsentry/sentry-laravel#adding-context).

Going to close this issue as you can add the tags you're looking for.
