### ISSUE TITLE
Custom search filter on server_name is returning non-matching results

### ISSUE THREAD

**Issue by lampholder** [getsentry/sentry#10705]
In a single project ('badbot-2') errors are being reported from two servers ('matrix-badbot' and 'matrix-sadbot').

![image](https://user-images.githubusercontent.com/1922197/48810085-46a83d00-ed1f-11e8-94a5-f25336d7da29.png)

Filtering the results using a custom search on server_name of either 'matrix-badbot' or 'matrix-sadbot' returns results for both matrix-badbot _and_ matrix-sadbot. 

Filtering on a made-up server_name (e.g. 'matrix-radbot') returns nothing.

Sorry if this is more of a support request than an issue - it certainly _feels_ like something's not behaving as I'd expect, but I'm only just starting to use sentry. Thanks!

**Comment by markstory** [comment]
I'm assuming that `server_name` is a custom tag you've added to your events?

**Comment by lampholder** [comment]
I don't think so - I'm only making a very basic use of sentry - importing the sentry_sdk into a python project and initalising it as per the copy+pasta instructions. Could it be something the python sdk is doing automagically?

Actually, I think I've answered the question - I think I was just confused by the UX 😄.

Searching by `server_name` returns all of the issues containing events with the matching `server_name` tag, but one issue can obviously have many events, and **not all of those events will match the original `server_name` search term**. So if the most recent event happens to come from a server with a different server name, when you click through on an issue from your `server_name:matrix-badbot` filter, the first event you see might actually be tagged `server_name:matrix-sadbot`.

Thanks for your time!

**Comment by markstory** [comment]
I'm going to close this as it sounds like you've figured out how sentry is aggregating events into issues.
