### ISSUE TITLE
Event navigation busted if two events have same timestamp

### ISSUE THREAD

**Issue by dosena** [getsentry/sentry#1071]
If some of the events in a group have identical values for 'datetime' (down to the second), the "newer event"/"older event" buttons end up navigating in an endless loop for such events.

(version 6.2.3)

Here are some fix possibilities:
1. increase the granularity of the DB column to timestamp-plus-sub-second. But it looks like that's not possible in Django (https://code.djangoproject.com/ticket/19716)
2. use something like an IntegerField instead of a DateTimeField, representing milliseconds-since-1970 and piping this thru something like time.ctime()
3. if you can guarantee that  event.PK values are higher for later events, sort via "ORDER BY datetime, id" instead of just "ORDER BY datetime", e.g. in web.frontend.groups.render_with_group_context():

    <<                next_event = base_qs.filter(datetime__gte=event.datetime).order_by('datetime')[0:1].get()
    --------
    >>                next_event = base_qs.filter(datetime__gte=event.datetime,id__gt=event.id).order_by('datetime')[0:1].get()

**Comment by dcramer** [comment]
Reopening this as the fix had to be reverted.

**Comment by dcramer** [comment]
Should be fixed in:

445981742506c17e0c40b99d2fe75a84ed0e8c2f
4766a3bc92c1834d07dbba71a67b66a0a24ab9c2
