### ISSUE TITLE
Creation of user for running sentry

### ISSUE THREAD

**Issue by droidzone** [getsentry/sentry#10754]
At https://docs.sentry.io/server/installation/python/, I did not find any step which mentions creation of a user for running sentry worker. Is it assumed that we need to create a user `sentry` for running the worker as?

**Comment by markstory** [comment]
> Is it assumed that we need to create a user sentry for running the worker as?

Yes. You can run the worker as any unprivileged user. The example systemd configuration files reflect how we setup sentry in the docker based install.
