### ISSUE TITLE
Organization avatar not updating

### ISSUE THREAD

**Issue by lucaspar** [getsentry/sentry#10760]
### Summary
Unable to change organization's avatar.
The org has an old avatar which I would like to update, but it appears Sentry keeps referencing the old uploaded image.

### Steps
1. Navigate to Settings > MyOrg > General and scroll to Avatar.
2. Upload an Image is already selected (I have a custom image), so I click Change Photo and select a new one.
3. The new avatar shows up for cropping, and after adjusting it I click Save Avatar.
4. The message "Successfully saved avatar preferences" pops up, but the old avatar remains.
5. After reloading this General page, the new image I selected remains in the cropping area, so the upload is probably working, but everywhere (breadcrumbs and in settings), the old image is used instead.

### Additional info
- Browser: Chrome 70.0.3538.110 (Official Build) (64-bit)
- I have cleared all my local cache and any persistent data with no success
- I have checked the console, there are no JS errors or warnings from the client side after uploading or saving

**Comment by markstory** [comment]
Are you having this issue with sentry.io or your own on-premise install?

**Comment by lucaspar** [comment]
> Are you having this issue with sentry.io or your own on-premise install?

It's with sentry.io.

**Comment by lucaspar** [comment]
Ok, now I've checked again and the image was finally updated.
Apparently it takes a few minutes for this change to have an effect in other pages, regardless of local cache. Is it expected?

**Comment by markstory** [comment]
> Is it expected?

Yes, we have some internal caches for cloud storage files that take time to purge.

**Comment by lucaspar** [comment]
The organization avatar updates, it just takes longer than expected. Closing issue.

**Comment by richardwellerson** [comment]
Great. I was worried about that.

Tks, @lucaspar and @markstory .
