### ISSUE TITLE
Environment variable SENTRY_EMAIL_HOST doesn't seem to work

### ISSUE THREAD

**Issue by KidkArolis** [getsentry/sentry#10765]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.0.0]

## Description

I've put the following in my .env

```
SENTRY_EMAIL_HOST=smtp.postmarkapp.com
SENTRY_EMAIL_USER=xxx
SENTRY_EMAIL_PASSWORD=xxx
SENTRY_EMAIL_PORT=587
SENTRY_EMAIL_USE_TLS=true
```

Then I open https://my-sentry.com/manage/status/mail/

It shows what looks like incorrect host value:

<img width="398" alt="image" src="https://user-images.githubusercontent.com/324440/49035289-3fb07d00-f1ac-11e8-8d24-41444ef3a0d3.png">

And sending test email doesn't work.

### What you expected to happen

I expected to see `smtp.postmarkapp.com:587` as the host in the UI.
I expected the email to send.

**Comment by KidkArolis** [comment]
Furthermore, if I tweak my .env file and change values such as `SENTRY_EMAIL_USER` or `SENTRY_EMAIL_PORT`, those get reflected in `mysentry.com/manage/status/environment/`, but after changing `SENTRY_EMAIL_HOST`, I always see:

<img width="201" alt="image" src="https://user-images.githubusercontent.com/324440/49047027-143e8a00-f1ce-11e8-9bea-0d8e24f47d70.png">

**Comment by KidkArolis** [comment]
Ok, I just did `docker exec -ti 3e11d92a2ab8 /bin/bash` to enter the container and check the env values there, all of them are correct, but for some reason `SENTRY_EMAIL_HOST` is `smtp`. Hmm

**Comment by KidkArolis** [comment]
If I create a test variable, it correctly preserves the value, e.g.:

```
# .env
SENTRY_EMAIL_HOST=smtp.postmarkapp.com
SENTRY_EMAIL_HOST_TEST=smtp.postmarkapp.com

```

Inside the running docker container:

```
root@58e54ced4990:/usr/src/sentry# echo $SENTRY_EMAIL_HOST
smtp
root@58e54ced4990:/usr/src/sentry# echo $SENTRY_EMAIL_HOST_TEST
smtp.postmarkapp.com
```

It's as if Sentry somehow overwrites the ENV variable?

**Comment by KidkArolis** [comment]
OK, found the issue, it's this: https://github.com/getsentry/onpremise/blob/master/docker-compose.yml#L24

Phew..

**Comment by itay-grudev** [comment]
@KidkArolis Maybe a an year later, but what did you mean by:

> it's this: https://github.com/getsentry/onpremise/blob/master/docker-compose.yml#L24

**Comment by itay-grudev** [comment]
@KidkArolis I found out what you meant. You were linking to the master branch isntead of what the file looked like when you posted the solution. The correct link is:

https://github.com/getsentry/onpremise/blob/9.1.2/docker-compose.yml#L24
