### ISSUE TITLE
Issues resolved for release but not appearing in UI

### ISSUE THREAD

**Issue by willyyang** [getsentry/sentry#10827]
![screen shot 2018-11-29 at 10 28 42 am](https://user-images.githubusercontent.com/6396257/49232350-c1c5bf00-f3c1-11e8-9ff5-f77a4e86ebe8.png)

![screen shot 2018-11-29 at 10 28 21 am](https://user-images.githubusercontent.com/6396257/49232360-c5594600-f3c1-11e8-8987-a4597a855056.png)

I've resolved an issue for this release (Invalid username or password), Should I see that the issue has been resolved in the Overview page?

**Comment by willyyang** [comment]
Is there some sort of lag between the different pages..?

There's a new issue..
![screen shot 2018-11-29 at 10 37 19 am](https://user-images.githubusercontent.com/6396257/49232904-d9517780-f3c2-11e8-95ff-00816b7e17bc.png)

Notice new issues = 0 
![screen shot 2018-11-29 at 10 37 12 am](https://user-images.githubusercontent.com/6396257/49232920-e2dadf80-f3c2-11e8-89f7-dd48cba15181.png)

**Comment by willyyang** [comment]
Is there any update on this? @lauryndbrown ?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
