### ISSUE TITLE
Payload validation

### ISSUE THREAD

**Issue by ogonkov** [getsentry/sentry#10824]
## Summary

Add validation for a payload fields

## Motivation

In our project some cool-hackers trying to pwn us by sending payloads to our sentry server with `release` string containing some html, like `<script>` and other.

It's would be fine to have option to reject such payloads (custom regexp's in Options maybe?).

**Comment by BYK** [comment]
We have [inbound filters](https://docs.sentry.io/product/accounts/quotas/#inbound-data-filters) but not sure it solves this exact problem. In any case, closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
