### ISSUE TITLE
Saved searches do not save environment

### ISSUE THREAD

**Issue by mhauens** [getsentry/sentry#10828]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.0.0]

## Description

If you save a search with an environment parameter and set this as default search-filter, it does not remember the environment variable.

`is:unresolved age:-24h environment:prod`

looses environment:prod

## Steps to Reproduce

1. Configure a search
2. save the search
3. set is as default
4. click in an other tab
5. go back to the search tab

### What you expected to happen

The filter should be 
`is:unresolved age:-24h environment:prod`
instead of
`is:unresolved age:-24h`

**Comment by ndebarnot** [comment]
Hello,
I have the same issue with Version 9.0.0 on-premise. The environment filter gets lost when you load Sentry and it's the default search or if you change tabs
Re-selecting the saved search it will put it back though.

**Comment by Shmakov** [comment]
I believe this issue could be closed. I've experienced the same bug using version 9.0.0, but after upgrading to 9.1.2 the saved searches work as expected.

Thanks.
