### ISSUE TITLE
redis-py-cluster is not matched to setup.py using docker image

### ISSUE THREAD

**Issue by odg0318** [getsentry/sentry#10860]
## Important Details

How are you running Sentry?

* [ V ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

[What happened]
`redis-py-cluster` is not matched to the version described in `setup.py` using `library/sentry:9` docker image.

### setup.py
```
redis-py-cluster==1.3.4
redis>=2.10.3,<2.10.6
```
### pip list on sentry container
```
$ docker run --rm sentry:9 pip list | grep redis-py-cluster
redis-py-cluster         1.3.6
```
And it makes package version conflicted each other.

## Steps to Reproduce

1. docker pull sentry:9
2. docker run --rm sentry:9 pip list | grep redis-py-cluster
3. You can see `redis-py-cluster` version.

### What you expected to happen
1.3.4 `redis-py-cluster` is installed on docker image.

### Possible Solution
What do you think of changing `redis` and `redis-py-cluster` version?
I suggest redis==2.10.6 and redis-py-cluster==1.3.6.

**Comment by adaiLinux** [comment]
`pip install redis-py-cluster==1.3.4` is ok

**Comment by odg0318** [comment]
@adaiLinux I surely know the command. To install other package such as django-ldap-auth, package dependancies should be matched.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
