### ISSUE TITLE
Issue Owners: Assign to the owners instead of only suggesting

### ISSUE THREAD

**Issue by tscolari** [getsentry/sentry#10908]
## Summary

Right now, when you define a rule for the new issue owners feature, the "owner" team only gets suggested to the issue, and not actually assigned to it.
It would be great to have an option to automatically assign to the teams/ppl that match the rule

## Motivation

There isn't a way to filter out issues by "suggested", so having issues suggested to teams does not make the teams dashboard any more cleaver than it was before.
It would also be a good flow if teams could own the issues from day-0 if they are responsible for them.

Alternatively having a way to filter issues by "suggested" would be a good step up in the UX

**Comment by wqtty** [comment]
+1

**Comment by hloehrmann** [comment]
+1

**Comment by hloehrmann** [comment]
+1

**Comment by markstory** [comment]
A feature matching this description has recently shipped. Under a projects 'Issue Owners' settings you will find the following

![Screen Shot 2019-05-28 at 9 54 18 AM](https://user-images.githubusercontent.com/24086/58483639-a815f200-812e-11e9-8ad0-29f5afbafe77.png)

When enabled issue owners will be assigned as new events are processed. If an issue already has an owner no owner will be assigned. If multiple rules match an event the rule with the longest path/url rule will take precedence.

**Comment by hloehrmann** [comment]
@markstory can you provide more information in which version this feature has been shipped? We're running `9.0.0` and it seems to be missing... or what is _recently_?

**Comment by markstory** [comment]
More recent than 9.0.0. You would have to go to 9.1.0 or 9.1.1

**Comment by agis** [comment]
@markstory We're on 9.1.1 and I don't see any such option.

**Comment by markstory** [comment]
@agis I guess you'll have to wait until 10.0 comes out then.
