### ISSUE TITLE
sentry:9.0  /auth/login/    Oops! Something went wrong

### ISSUE THREAD

**Issue by vannesspeng** [getsentry/sentry#10902]
![image](https://user-images.githubusercontent.com/11361345/49413629-82c1b000-f7ab-11e8-9aae-9e8953ee474a.png)

I want to know，where is the log of the error file

**Comment by markstory** [comment]
How have you installed sentry?

**Comment by vannesspeng** [comment]
1、yum install -y yum-utils   device-mapper-persistent-data   lvm2    ----install docker dependent package
2、yum-config-manager     --add-repo     https://download.docker.com/linux/centos/docker-ce.repo    ----add docker yum source
3、yum -y install docker-ce   ----install docker
4、systemctl start docker      ----start docker
5、yum install epel-release
6、yum  install -y python-pip
7、pip  install docker-compose
8、yum install git
9、git clone https://github.com/getsentry/onpremise
10、cd onpremise
11、docker volume create --name=sentry-data && docker volume create --name=sentry-postgres
12、cp -n .env.example .env
13、docker-compose build 
14、docker-compose run --rm web config generate-secret-key - Generate a secret key. 
15、vim docker-compose.yml  ----add SENTRY_SECRET_LEY
16、docker-compose run --rm web upgrade   ----This step programe not notify me input username and password，Is it correct?
17、docker-compose up -d - Lift all services (detached/background mode).
18、Access your instance at localhost:9000!

**Comment by markstory** [comment]
The logs should be available via `docker logs` You can also modify the logging configuration to write logs to files or syslog if you prefer.

**Comment by zsc8917zsc** [comment]
You don't seem to have created  username password
please use docker command in postgres
`docker exec -it onpremise_postgres_1 bash`
```
from sentry.models import Project
from sentry.receivers.core import create_default_projects
create_default_projects([Project])
```

exit or ctrl+d

you can create you useraccont

`docker-compose run --rm web createuser`
