### ISSUE TITLE
Discord Global Integration or Slack Webhook Global Integration

### ISSUE THREAD

**Issue by nepeat** [getsentry/sentry#10925]
## Summary

With the new Global Integrations feature in Sentry, I've tried to adapt my existing setup that uses Discord's Slack compatible webhooks and found that the new Global Integrations feature uses Slack's oAuth API instead of webhook API. I am thinking that either the integration can be expanded to support Slack webhooks or have a separate integration for Discord.

## Motivation

This would improve support for Discord, organizations that do not want to use slack apps and other chat apps that have Slack compatible webhook APIs, depending on the implementation.

## Additional Context

* Discord slack webhook docs - https://discordapp.com/developers/docs/resources/webhook#execute-slackcompatible-webhook

**Comment by EvanPurkhiser** [comment]
We've moved away from using Slack webhooks as they lacked a lot of flexibility which the (unfortunately now deprecated) workspace tokens provided us.

We don't currently have any plans to provide the webhook Slack interface through any integrations.

**Comment by elderlabs** [comment]
I believe there's been a bit of miscommunication/confusion here. The request is to add **Discord** webhook integration, which is identical to the now deprecated legacy Slack webhook. This is not asking to use anything related to Slack whatsoever. More here: [getsentry/sentry-plugins/#249](https://github.com/getsentry/sentry-plugins/issues/249)

**Comment by nepeat** [comment]
Correct. At the time I did not realize that the legacy Slack webhook settings were hidden behind the search menu and I made a issue that is definitely unclear now. As the issue's original text stands, I should have split it down to two separate issues.

1. Adding an integration for native Discord webhooks.
2. Re adding Slack webhooks to the Slack integration to support workgroups that do not wish to use Slack apps or have similar chat services that support Slack webhooks.

I am more interested in the first, like the majority of users but I recognize that the second case is also a thing that would be nice with the potential for future services that implement the Slack hooks API.

**Comment by ovived** [comment]
I too want this integration to my Discord. I saw a prior thread mentioned using the Slack (Legacy) integration and modifying the URL's for discord as a work around, but i know longer see that in the integrations search results

Thanks

**Comment by jacc** [comment]
+1 on this, if possible it would be appreciated.

**Comment by StoneSet** [comment]
+1, good idea !

**Comment by vitormm** [comment]
+1, it would be great!

**Comment by danielxfr** [comment]
+1, we need it.

**Comment by arjunbazinga** [comment]
+1 Would love this

**Comment by Russia9** [comment]
+1, good!

**Comment by SebastianGiro** [comment]
+1

**Comment by elderlabs** [comment]
I should have dropped a note here a few days ago. Sorry folks 😅

You _can_ still use the old Slack Legacy Webhook Integration, but it's hidden. You can find it by navigating to your team/project's settings page and appending `/plugins/slack/` to the URL.

Example: `https://sentry.io/settings/###my-team-name-or-whatever###/plugins/slack/`

From there, you configure the Webhook URL provided from your desired Discord Channel with `/slack` appended to the end of the URL.

Example: `https://canary.discord.com/api/webhooks/###channel-id-here###/###elaborate-webhook-key-here###/slack`

I personally have a Bot Name and Tags configured/enabled, but otherwise you should be able to leave the rest of the settings blank.

Enjoy!

**Comment by SebastianGiro** [comment]
> I should have dropped a note here a few days ago. Sorry folks 😅
> 
> You _can_ still use the old Slack Legacy Webhook Integration, but it's hidden. You can find it by navigating to your team/project's settings page and appending `/plugins/slack/` to the URL.
> 
> Example: `https://sentry.io/settings/###my-team-name-or-whatever###/plugins/slack/`
> 
> From there, you configure the Webhook URL provided from your desired Discord Channel with `/slack` appended to the end of the URL.
> 
> Example: `https://canary.discord.com/api/webhooks/###channel-id-here###/###elaborate-webhook-key-here###/slack`
> 
> I personally have a Bot Name and Tags configured/enabled, but otherwise you should be able to leave the rest of the settings blank.
> 
> **Don't forget to enable the plugin!** Afterwards, it will appear in your integrations as 'Slack (Legacy).'
> 
> Enjoy!

Amazing, please leave a // NOTE to never fully remove it so we can keep using it for discord. Thanks! Working great

**Comment by EvanPurkhiser** [comment]
> +1 We need this integration, the webhook plugin is not working correctly with discord and the slack legacy plugin (that we can use for discord) is not in the list anymore.
> Can you recheck this issue please? @EvanPurkhiser

I can't speak towards any roadmap on adding Discord, but I do know someone who may be able to!

/cc @jonesphillip to get this on your radar :)

(also I think my comment above may have been my most downvoted comment on github haha)

**Comment by dkotama** [comment]
> > I should have dropped a note here a few days ago. Sorry folks 😅
> > You _can_ still use the old Slack Legacy Webhook Integration, but it's hidden. You can find it by navigating to your team/project's settings page and appending `/plugins/slack/` to the URL.
> > Example: `https://sentry.io/settings/###my-team-name-or-whatever###/plugins/slack/`
> > From there, you configure the Webhook URL provided from your desired Discord Channel with `/slack` appended to the end of the URL.
> > Example: `https://canary.discord.com/api/webhooks/###channel-id-here###/###elaborate-webhook-key-here###/slack`
> > I personally have a Bot Name and Tags configured/enabled, but otherwise you should be able to leave the rest of the settings blank.
> > **Don't forget to enable the plugin!** Afterwards, it will appear in your integrations as 'Slack (Legacy).'
> > Enjoy!
> 
> Amazing, please leave a `// NOTE` to never fully remove it, so we can keep using it for discord. Thanks! Working great

Thank you, I just want to add that you should enable the rules for legacy notification for each event happened at project 
via : https://sentry.io/settings/YOUR_TEAM_NAME/projects/YOUR_PROJECTS/alerts/

<img width="728" alt="Screen Shot 2020-06-02 at 14 51 38" src="https://user-images.githubusercontent.com/5332757/83489186-9e149500-a4e0-11ea-9254-09af744f4604.png">

**Comment by victornpb** [comment]
1. Visit this hidden page
  `https://sentry.io/settings/PROJECT_NAME/plugins/slack/`
1. Enable the plugin
  ![image](https://user-images.githubusercontent.com/3372598/86059373-ffc11400-ba38-11ea-8f50-1c2c758355ad.png)
1. Add to project
  ![Add to project](https://user-images.githubusercontent.com/3372598/86059619-71995d80-ba39-11ea-8d20-002c025a9a94.png)

1. Configure webhook
  ![Configuring webhook](https://user-images.githubusercontent.com/3372598/86060047-58dd7780-ba3a-11ea-829a-6e1ed46d85ac.png)
1. Click Test
  ![](https://user-images.githubusercontent.com/3372598/86060380-ff297d00-ba3a-11ea-8dfd-9fd62a80bf35.png)
  ![](https://user-images.githubusercontent.com/3372598/86060407-05b7f480-ba3b-11ea-90fe-cb6ba886d4b4.png)

**Comment by noisyblue** [comment]
I couldn't access webhook configuration page using `https://sentry.io/settings/PROJECT_NAME/plugins/slack/`
Instead `https://sentry.io/settings/ORG_ID/projects/PROJECT_NAME/plugins/slack/` worked.

**Comment by elderlabs** [comment]
> I couldn't access webhook configuration page using `https://sentry.io/settings/PROJECT_NAME/plugins/slack/`
> Instead `https://sentry.io/settings/ORG_ID/projects/PROJECT_NAME/plugins/slack/` worked.

@noisyblue updated my post to reflect your correction. Thank you.

**Comment by NMW03** [comment]
+1

**Comment by TurtDev** [comment]
Discord Webhook Integration would be awesome; +1

**Comment by elderlabs** [comment]
> Is this still working? When I click Test Plugin I receive:
> 
> > "There was an internal error with the Plugin, {"message": "Cannot send an empty message", "code": 50006}"

Depends on your config, likely there's something misconfigured. This still works.

**Comment by ooo27** [comment]
> > Is this still working? When I click Test Plugin I receive:
> > > "There was an internal error with the Plugin, {"message": "Cannot send an empty message", "code": 50006}"
> 
> Depends on your config, likely there's something misconfigured. This still works.

Indeed it was a configuration error. I neglected to change the endpoint from discord.com to canary.discord.com.  Thanks!

**Comment by IanMitchell** [comment]
I wrote a service to forward Sentry Webhooks to Discord - it adds more information than the Slack compatible one does. I'm still testing its reliability, but if anyone is interested in richer embeds check out https://sentrydiscord.dev.

**Comment by jonesphillip** [comment]
@IanMitchell This is great! Would love to discuss how we could get involved, I'll reach out.

**Comment by landsman** [comment]
Yes please!

**Comment by igl** [comment]
We will enter 2022 without discord integration? What the!

**Comment by FeMaffezzolli** [comment]
Any update?

**Comment by elderlabs** [comment]
> Any update?
> 
> I've been using this service as a workaround -> https://sentrydiscord.dev/.

There are multiple posts here detailing how to natively configure Sentry to work with Discord using the legacy Slack integration. As for something labeled "Discord" in Sentry, no dice as of yet.

**Comment by guntiss** [comment]
Please Sentry, this is a must have feature. It's shame that we need to use some workarounds or hacks to receive notifications on a mainstream platform...

**Comment by Benoss** [comment]
With the new Free tier slack model and the increase of the paid plan on Slack. I am exploring moving to Discord instead of Slack as our company communication app. Sentry Slack integration is really good, would love to have the same on Discord!

**Comment by raphahardt** [comment]
+1

**Comment by boosteffect** [comment]
+1 DIscord integration would be awesome

**Comment by Lutacon** [comment]
+1 Discord integration

**Comment by braincomb** [comment]
> We will enter 2022 without discord integration? What the!

We are entering 2023 without Discord integration still.

**Comment by Mentioum** [comment]
This is quite bad. 

My old webhooks to discord are working fine but our new project can't be configured with the same output in Discord.

Sentry, I'm not moving from discord, it's tied to too much. 

If we break up, it'll be you, not discord.

**Comment by therealarkin** [comment]
Hi Folks! Welcome to 2023 :-)

I would love to learn more about Discord so that we can properly think about it -

1. Why do you need discord integration?
2. What type of projects/company are you part of?
3. If you used Slack+Sentry, what do you like about it? What did you dislike?
4. If you used https://sentrydiscord.dev/, what did you like about it? What did you dislike?
5. Are there any Discord-specific patterns/capabilities that we should consider?

**Comment by chris-erickson** [comment]
Thanks for the questions!

1. We use Slack now, and are likely to move to Discord for it's better positioning as a community hub.
2. All our internal app, maybe 10-20 from web frontend, backends and all kinds of other behind the scenes apps.
3. We like that it works, and notifies us of things. Not really much to dislike, it's just far better than email alerts which don't scale well for an open-ish development process. We have many people who one would consider developers, but they aren't added to most systems for quite a long time, for security reasons. This also is how we immediately discuss an issue, or reference it in conversations around Slack.
4. That third-party thing seems to make really nicely formatted messages in Discord. A lot more detail than Slack has, it seems. Not sure that would always be desired but it's nice looking.
5. We aren't super expert users of Discord so no use cases immediately come to mind. Maybe @ mentioning Roles?

**Comment by cognitus** [comment]
1. Discord is our main method of communicating in our (small) team
2. We develop Internal apps and web application for business in our country
3.  -
4. Pretty easy for use inside discord, details of context (it would be nice if was editable). About dislike... the lack configure propriety alerts, sometimes doesn't work with multiples proyects
5. Alert to roles (mentioning). The use of threads, https://support.discord.com/hc/en-us/articles/4403205878423-Threads-FAQ

**Comment by IanMitchell** [comment]
Happy to chat about both the limitations of sentrydiscord and what Sentry could do with the Discord API if you'd like! I had a plan for how to convert the service into a bot, but unfortunately time just hasn't allowed it 😅

**Comment by SteffanDonal** [comment]
Responding to the list, too!

1. In my case, Discord is the primary place our team communicates, and it acts as our shared inbox. I want to improve the visibility of incoming issues and provide a "single dashboard" for the team to pay attention to.
2. Distributed, muti-timezone collaboration for desktop applications.
3. Been many years since I used it!
4. I think simply having notifications with links to the web is just the "minimum effort" kind of integration. Discord bots can have many interactive features that could significantly smooth our workflow! New issues could come in with buttons that allow quick muting/assignment/triage without having to leave the Discord app. 
5. Role mentions, as the others have said, but taking full advantage of Discord embeds, commands and interactions. Discord can show select boxes, text inputs, buttons, and modals.

I'd like to see "regular workflow" parts of Sentry implemented within Discord in ways that encourage developers to engage more with it!

**Comment by nepeat** [comment]
> Hi Folks! Welcome to 2023 :-)
> 
> I would love to learn more about Discord so that we can properly think about it -
> 
> 1. Why do you need discord integration?
> 2. What type of projects/company are you part of?
> 3. If you used Slack+Sentry, what do you like about it? What did you dislike?
> 4. If you used https://sentrydiscord.dev/, what did you like about it? What did you dislike?
> 5. Are there any Discord-specific patterns/capabilities that we should consider?

Hello again, it's been 5 years! Hoping that more traction for a native integration with Discord is coming this year~

1. Discord is the only communications platform of my hackerspace and other groups that I know. We have used the Slack integration which sorta works but given the lesser priority Slack webhooks have been given, it is a lesser experience than going native with the notifications.
2. Hackerspace with a few bots and backend facing services.
3. N/A, never used it with Slack.
4. N/A, never used that service.
5. Embed colors, embed fields, arbitrary user names and icons based on projects, more customizability that integrated with the Discord ecosystem, and adding interactiveness (Ack/Mute/etc) to responses to the alerts.

**Comment by krokovicsmate** [comment]
Hi all!

1. Our company just moved to discord from slack, and we love the slack integration and we are really missing the features of it.
2. PHP projects, mostly CMS, CRM and Webshop systems.
3. The most missing part of it the mention system, we configured the integration to mention a person who is leading the project.
4. Missing options, only the default layout of messages available.
5. The mention sytem :)

**Comment by irfanfadilah** [comment]
Whoa, it's been more than 4 years and still no native integration for Discord.

**Comment by joaofraga** [comment]
**Why do you need discord integration?**
It's the main communication channel of my company.

**What type of projects/company are you part of?**
Payments

**If you used Slack+Sentry, what do you like about it? What did you dislike?**
TBH I haven't used Slack integration before.

**If you used https://sentrydiscord.dev/, what did you like about it? What did you dislike?**
It did not work for me, it asks me to add a discord webhook even though I add the correct url.

**Are there any Discord-specific patterns/capabilities that we should consider?**
Simple alerts are enough to me.

**Comment by igl** [comment]
**Why do you need discord integration?**
It's the main communication channel of my company.

**What type of projects/company are you part of?**
Development

**If you used Slack+Sentry, what do you like about it? What did you dislike?**
The Slack client has very bad performance (not Sentrys fault)

**If you used https://sentrydiscord.dev/, what did you like about it? What did you dislike?**
It did not work for me.

**Are there any Discord-specific patterns/capabilities that we should consider?**
We need High visibility about new errors appearing after a release.
Possiblity to get daily or weekly summaries.

**Comment by ryantam626** [comment]
Just for more visbility - https://github.com/getsentry/sentry/pull/50623#issuecomment-1583985056 indicates that Discord integration work has already been started :tada: 

I have [a branch in my fork](https://github.com/ryantam626/sentry/tree/rt.discord-plugin) that added a stopgap solution that still uses webhook (but the native one) which allows mentioning, just in case this is of interests for folks that self hosts (like me).

**Comment by crabsinger** [comment]
+1 would like this

**Comment by spalmurray** [comment]
Hey Everyone,

We’re excited to announce that the eagerly awaited Discord integration for Sentry is coming soon! 🎉

This integration will allow users to receive and act on notifications about critical issues as they are surfaced by Sentry, directly in Discord.

Issue alerts support will come first with plans to support metric alerts and personal notifications in the future.

You can [sign up here](https://sentry.io/integrations/discord/) to gain early access to the latest functionality and give us input as we build.

If you have any questions or feedback, please get in touch with us on our [Discord server](https://discord.gg/ndsfqnwn) in the [#discord-integration](https://discord.com/channels/621778831602221064/1138592944190930964) channel.

Thank you all for advocating for this feature and sharing your use cases with us!

Spencer from Sentry

**Comment by spalmurray** [comment]
The Discord integration is now available to orgs that have [signed up for early access](https://sentry.io/integrations/discord/). If you haven’t signed up yet, you can do that now and we’ll add you to our early access program next week.

**Comment by 17hogeju** [comment]
🎉 **The Discord integration is officially out!!!** 🎉
Issue and Metric alerts can now be sent to Discord! Check out the changelog [here](https://changelog.getsentry.com/announcements/discord-sentry-integration)

Check out the setup instructions on our new [Discord Sentry Doc](https://docs.sentry.io/product/integrations/notification-incidents/discord/)

If you have any questions or feedback, please get in touch with us on our [Discord server](https://discord.gg/ndsfqnwn) in the [#discord-integration](https://discord.com/channels/621778831602221064/1138592944190930964) channel. 


Thank you for bringing this integration into life! ❤️

Julia from Sentry
