### ISSUE TITLE
Improve filter for api-counts

### ISSUE THREAD

**Issue by DrDth** [getsentry/sentry#10948]
## Summary

It is only possible in the moment, to get the total counts of events for a specific project in the last 24h (or 14d..). It would be great to have the possibility
to filter/group by tags, so that you can get the counts for a specific tag in a specific project for every hour in the last 24h

at the moment:
/api/0/projects/the-interstellar-jurisdiction/pump-station/stats/
---
```
[
    1541455200.0, 
    1184
  ], 
  [
    1541458800.0, 
    1410
  ]
]
```
---

with the feature:
/api/0/projects/the-interstellar-jurisdiction/pump-station/stats/?filter_by=environment&filter_data=testing&filter_data=staging...
---
```
[
    1541455200.0, 
    [
        testing
        200
    ],
    [
       staging
       102
    ]
  ], 
  [
    1541458800.0, 
     [
        testing
        10
    ],
    [
       staging
       0
    ]
  ]
]
```
---
## Motivation

In Case of better usability of the api. (In my case it´s an external dashboard displaying the count of the events with different colors for the different environments)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
