### ISSUE TITLE
Sentry import/export doesn't set auto_increment value

### ISSUE THREAD

**Issue by wyhysj** [getsentry/sentry#10946]
Use sentry export to dump a json backup

Restore the json to a new instance

The table id auto_increment value is not updated

This will result some integrity issue, like create new project fails, etc.

We use sentry:9.0.0 on docker

**Comment by dannietjoh** [comment]
same here, exporting and importing allows creating an object like user, team, project but after deleting its impossible to create anything new.

**Comment by dannietjoh** [comment]
see https://github.com/getsentry/sentry/issues/3840#issuecomment-236292059 for a fix

**Comment by BYK** [comment]
Duplicate of #3840
