### ISSUE TITLE
Release API doesn't seem to do anything

### ISSUE THREAD

**Issue by mnpenner** [getsentry/sentry#10981]
I'm trying to notify Sentry when I do a release. Here's my code:

```
const res = await httpsPost({
    hostname: 'sentry.io',
    path: `/api/0/organizations/mycompany/releases/`,
    headers: {
        'Authorization': `Bearer ${process.env.SENTRY_AUTH_TOKEN}`,
        'Content-Type': 'application/json',
    },
    body: JSON.stringify({
        environment: isLive ? 'production' : 'demo',
        version: changesetId,
        projects: ['bookings'],
    })
})
```

The response I get back is:

```
{ dateReleased: null,
  commitCount: 0,
  url: null,
  data: {},
  lastDeploy: null,
  deployCount: 0,
  dateCreated: '2018-12-09T20:39:52.669Z',
  lastEvent: null,
  version: '0ec69f25b158a75185547fdbb8a22f2e2c71a110',
  firstEvent: null,
  lastCommit: null,
  shortVersion: '0ec69f2',
  authors: [],
  owner: null,
  newGroups: 0,
  ref: null,
  projects: [ { slug: 'bookings', name: 'Bookings' } ] }
```

Which looks mostly successful, except for all the blanks.

But when I go to https://sentry.io/mycompany/bookings/releases/?environment=production, I don't see my release.

This feature doesn't seem to do anything at all. No emails go out. Nothing.

**Comment by markstory** [comment]
You'll also need to add release tag to your SDK integrations so that events can be attached to the release. Only releases that contain issues will show up in the UI. You might also want to add commits to your releases to enable suspect commits.

**Comment by markstory** [comment]
Closing as this the APIs are 'working', but it sounds like you've not completed all the steps to enable releases to show up and behave as you're expecting.
