### ISSUE TITLE
Can't find Jira issue when linking from ID

### ISSUE THREAD

**Issue by jviolas** [getsentry/sentry#11003]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

When I try to link a Jira issue and search an existing issue by its ID, I have no result from Jira.
It used to work fine before. Now, when I start typing my ID, it doesn't seem to search by issue key, only title, and as soon as I type '-' that separate the project key and the issue number, the combobox comes empty.

## Steps to Reproduce

1. Search for a Jira issue (in my case something starting by IP- )
2. Some result show at first, but if the project key appears in the title of some issue
3. then nothing found as soon as I type the entire ID

### What you expected to happen

Having the associated Jira issue in the search result.

**Comment by markstory** [comment]
This should be resolved by #10996 which will go out later today.
