### ISSUE TITLE
Using Sentry with a custom scheme

### ISSUE THREAD

**Issue by Tsury** [getsentry/sentry#11019]
I'm currently developing an Overwolf application, and integrating Sentry into my app.
I'm having issues with the scheme of Overwolf app being `overwolf-extension://`.
Is there a way to register a new scheme to make it supported?

[Overwolf](https://www.overwolf.com/) is a platform based on Chromium which enables devs to create essentially web apps and inject them into games.

**Comment by markstory** [comment]
What kinds of problems are you having?

**Comment by Tsury** [comment]
@markstory Issues with sourcemaps. They seem to not work well.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
