### ISSUE TITLE
Sentry Slack Integration uses deprecated Slack API

### ISSUE THREAD

**Issue by SPARTAN563** [getsentry/sentry#11021]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [x] Other - On-Premise docker built from source at 78e2c3cebfbb035bf191ba7aa58f1792509006a6

## Description

The set of OAuth scopes requested by your Sentry integration for Slack includes `chat:write` which (according to the Slack [documentation](https://api.slack.com/scopes/chat:write)) is not available to non-workspace apps. Since the workspace apps preview has closed and there is no longer the ability to create new workspace apps, this prevents an on-premise installation of Sentry from leveraging the new Slack integration functionality.

## Steps to Reproduce

1. Install an on-premise version of Sentry with the latest stable code
2. Create a new Slack application
3. Configure your on-premise Sentry instance to use your Slack application's tokens
4. Attempt to install the Slack integration into your workspace
5. Receive the following error:

> **Invalid permissions requested**
> User tokens do not support scope: `chat:write`

### What you expected to happen

I expect the Slack integration to make use of only supported, publicly available, API methods and OAuth permissions within the Slack API so that on-premise installations can leverage its functionality.

### Possible Solution

It should be possible to replace the `chat:write` permission [here](https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/slack/integration.py#L75) with `chat:write:bot` without impacting the functionality of the integration.

:warning: If you haven't already requested this permission from workspaces which have installed your integration this may require them to approve the new permissions, that may be a disruptive update so it may make more sense to have a feature flag for Slack Workspace App OAuth scopes to prevent this impacting your SaaS deployment's customers.

**Comment by markstory** [comment]
This issue is covered in #9004. This [comment](https://github.com/getsentry/sentry/issues/9004#issuecomment-438104734) and the surrounding comments are likely relevant to you.

Closing as a duplicate.
