### ISSUE TITLE
Slack Integration: Can not install after remove

### ISSUE THREAD

**Issue by Simonot** [getsentry/sentry#11034]
Hello there,

I think that I have an issue with new slack integration.
I have first installed it successfuly but only giving access to public channels.
Then I wanted to give access to private channels too. Because I did not find the setting in the setting option I removed slack integration and now I want to install it back.
Nevertheless, when I try to add my workspace, the new windows that appears shows me an error (I guess 500)
I do not understand how to activate back slack integration.
(I also did click the "Cancel button" when the windows told me that the integration was already active)

I am missing something ?

Do you need more information ?

<img width="931" alt="not_installed" src="https://user-images.githubusercontent.com/11572602/49939773-097a3980-fede-11e8-98ec-9132da15e472.png">
<img width="664" alt="click_add_workspace" src="https://user-images.githubusercontent.com/11572602/49939780-0d0dc080-fede-11e8-87dd-98896b85e10f.png">
<img width="664" alt="sentry_error" src="https://user-images.githubusercontent.com/11572602/49939957-93c29d80-fede-11e8-8b84-cb564b2372cf.png">

(also it seems that something is strange with the marging. I can only see half of the page when using firefox on MAC OS)

**Comment by lauryndbrown** [comment]
@EvanPurkhiser Is this the correct flow for the slack integration? I assumed it didn't have an installation flow like this.

**Comment by EvanPurkhiser** [comment]
@Simonot can you check if the Slack App is still installed in your slack settings

Check here

    https://<your-slack-workspace>.slack.com/apps/manage

**Comment by EvanPurkhiser** [comment]
> add Sentry user to the private channel.

Yep, that is how this works!
