### ISSUE TITLE
Add optional beacon service to monitor integrations

### ISSUE THREAD

**Issue by Addvilz** [getsentry/sentry#11077]
## Summary

I propose the capability of Sentry integrations to "beacon" request Sentry with fixed interval, with "last ping" available under a separate screen in project. The feature should probably be opt-in.

I am thinking about separate screen in the same level as "user feedback" and "releases" in project view. MVP could be very simple list of "hostname" + DSN ID + "last seen" or some other ability to identify an integration.

## Motivation

Monitoring large deployments with many different integrations is a tricky job. Is Sentry integration set up correctly? Is it connecting? Is the integration down or are there really no issues?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by Addvilz** [comment]
I do think this should be somewhere on the roadmap. 👍🏻

**Comment by BYK** [comment]
Reading this again, I think what you mean by an "integration" is simply a project using the SDK. I think our new performance monitoring covers this as it regularly collects data from healthy clients: https://docs.sentry.io/product/performance/

Combined with [release health](https://docs.sentry.io/platforms/native/release-health/)(soon coming to more platforms) this should be even better than what you proposed initially.

**Comment by Addvilz** [comment]
Missed those, and makes sense! Let's keep it closed then. Cheers!
