### ISSUE TITLE
ORGANIZATION Integrations ui: 

### ISSUE THREAD

**Issue by janceChun** [getsentry/sentry#11076]
how to open ORGANIZATION  Integrations ui
![image](https://user-images.githubusercontent.com/4457572/50147445-20ab9380-02f1-11e9-845e-2fa5339da530.png)

**Comment by markstory** [comment]
That looks pretty open. What are you hoping to see?

**Comment by janceChun** [comment]
sentry 9.0.0
i can‘t find the organization Integrations ui
![image](https://user-images.githubusercontent.com/4457572/50196803-93fbe680-037f-11e9-81d5-b51382592bf4.png)

**Comment by markstory** [comment]
Yes. It wasn't part of the 9.0 release.  You would have to use master or wait for the next release.

**Comment by MartinLoeper** [comment]
Good to know, I was surprised too!
