### ISSUE TITLE
Setup flow appears to be broken after upgrade to @sentry/Brower^4.0

### ISSUE THREAD

**Issue by Chrissy** [getsentry/sentry#11105]
## Important Details

This is in development in OSX Mojave

## Description

I regularly reset the database to load in new mocks. As of last night moving into today, I cannot proceed with the typical Sentry startup flow because of this js error:

![image](https://user-images.githubusercontent.com/435981/50248825-25278900-0391-11e9-9112-2bef51c5f92a.png)

I can move forward with the setup flow if I revert to the commit on `package.json` that immediately precedes this commit: https://github.com/getsentry/sentry/commit/5f0f87daf05cb3721a536153813a7322368324af#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

Once I am through the setup flow, I can return to latest master and everything runs fine.

This could be because of that specific commit, or it could be an unrelated benefit of returning to an old state in the repo. Either way, my only real hunch is that this bug involves the upgrade to `@sentry/browser^4` and probably @HazAT should be aware of this report.

UPDATE: I got a little less lazy and can now verify with 90% certainty that the above commit is the right one. I was able to reproduce the bug on that commit, and then successfully complete the initialization process on the commit that immediately precedes it in `master` history. I had to run `yarn cache clean` at one point when going backwards I think.

## Steps to Reproduce

1. Update to latest master and run `yarn`
2. Run `make reset-db`
3. Boot up server and try to set up Sentry

### What you expected to happen

I progress through the typical Sentry admin initialization flow (password, root url, email, etc.)

### Possible Solution

🤷‍♀️

**Comment by ckj** [comment]
This is because `SENTRY_PROJECT` is unset in sentry.conf.py. I think the difference is that in the past it would fail silently.

**Comment by HazAT** [comment]
Yeah, I am pretty sure this commit is responsible for it but;
I tested it locally without `SENTRY_PROJECT` set which then results in 
```
window.__SENTRY__OPTIONS = {
  dsn: '',
  release: '824c03089907ad22a9282303a5eaca33989ce481',
  whitelistUrls: ""
};
```
And this works if `dsn` is an empty string.
Also If I complety remove `window.__SENTRY__OPTIONS` it works.

When this error pops up can you please open the page source and search for `window.__SENTRY__OPTIONS` and tell me what's in there @Chrissy, I don't want to reset my local db right now 😅

**Comment by nttdocomo** [comment]
SENTRY_PROJECT is default to 1, sentry use this to query in the database to get the project Dsn. But today I update to the latest code. The dsn is not valid in dsn.js

**Comment by nttdocomo** [comment]
SENTRY_PROJECT is default to 1, sentry use this to query in the database to get the project Dsn. But today I update to the latest code. The dsn is not valid in dsn.js

**Comment by HazAT** [comment]
@Chrissy Can you check matt's suggestions?https://github.com/getsentry/sentry/issues/11337#issuecomment-451092664

**Comment by Chrissy** [comment]
@HazAT hey sorry for the holiday drop-off here. Thanks for looking into this! Next time I reset the db (which should be soon) I'll make a note of how it goes.

**Comment by HazAT** [comment]
@Chrissy https://github.com/getsentry/sentry/pull/11355 should have fixed it. Works now!
