### ISSUE TITLE
Get URL of event by ID

### ISSUE THREAD

**Issue by jsok** [getsentry/sentry#1110]
Previously `raven test <uri>` would print a URL which linked directly to the just captured event, e.g.

`The test message can be viewed at the following URL:
  http://localhost:9000/1/search/?q=c988bf5cb7db4653825c92f6864e7206$b8a6fbd29cc9113a149ad62cf7e0ddd5`

This functionality no longer seems to be possible in the new API without also knowing the team slug and project name.
The client only knows the Project ID from the DSN and the event ID.

Is there some other way to get a URL to your event?

**Comment by ducu** [comment]
Indeed I subscribe to this issue.

I have installed Sentry server locally and it seems it's working, client test says success but I can't find the events on the dashboard. They only appear in the organisation/stats *chart* view (I see just the number of accepted events), but not in the platform view and I can't find any details about these events.

It all gives the impression of a nice and clean system, but I can't find basic information such as what's the story with accepting/rejecting events? Can anyone please explain? Thanks

**Comment by khinze** [comment]
I'm having same problem. Not to sure what i'm doing wrong. 

I have a python app, running flask and im trying to log events. I can only see them in the organisation stats.

**Comment by ducu** [comment]
Hey make sure you also start celery, that was my problem



—

**Comment by dcramer** [comment]
Just to close this out, there's no way to build the full URL currently with just the DSN and event ID.

**Comment by khinze** [comment]
Thanks. I did eventually figure it out :)

**Comment by ruimarinho** [comment]
@dcramer, is there any way to build the full URL at all?

**Comment by dcramer** [comment]
@ruimarinho not currently (due to project ID), but we're planning to change that in the near future

**Comment by ruimarinho** [comment]
Alright, but if we know the project ID before hand, would it possible? I'd like to be able to generate a logging message with a direct link to the generated client side id, even if some of the variables have to be fed in.

**Comment by dcramer** [comment]
@ruimarinho as long as you know the project slug you could:

/org-slug/project-slug/?query=EVENTID

**Comment by ruimarinho** [comment]
Got it, but that takes me to the aggregated event and not the exact event id, which is eventually mapped to `org-slug/project-slug/group/<groupid>/events/<eventid>/`.

**Comment by dcramer** [comment]
@ruimarinho there's no guarantee the event is stored as Sentry may sample it. Because of that we dont implement a solid way to jump directly to the event at this time.

**Comment by ruimarinho** [comment]
Ok, fair enough. Thanks for your time!

**Comment by eladmoshe** [comment]
@dcramer Any update how to implement a reliable direct url to a ticket programmatically?

**Comment by dcramer** [comment]
You could dump the event ID into the cross project search and it'll bubble up any matches, but otherwise there's no way to infer it from just the event ID.

**Comment by mariogintili** [comment]
Just came across this thread, people seem to have  been asking for this for years now. What's preventing an implementation?

**Comment by dcramer** [comment]
It’s already doable via what I said above. Event IDs are not globally unique so you need the project.

**Comment by mariogintili** [comment]
@dcramer can you provide an example? I tried:

```
https://sentry.io/organizations/org-name/project-name/?query=ID
```

And got a page not found. Then I tried:

```
https://sentry.io/org-name/project-name/?query=da09b681aad14ec1adbc09db0a70eb81
```

Redirects me to the project's issue search URL which looks like `/organizations/org-name/issues/?project=PROJECT-ID`

Neither works, We're on `sentry-raven` `2.12.2` in Ruby

**Comment by dcramer** [comment]
Are you sure the event made it into the system? If I drop a valid event ID into search it will auto redirect if there's only one match.

**Comment by mariogintili** [comment]
@dcramer I am reporting an event and said action yields no failures, so the event *should* be in the system right?

**Comment by dcramer** [comment]
@mariogintili really depends - we apply filters and rate limits upstream. You can't search for an event that doesn't exist in the system, so if search isn't returning it that'd be the reason why. I would look at the statistics for the project and see if you're dropping events.
