### ISSUE TITLE
the "organazation > Repositories > add Repository" is not clickable

### ISSUE THREAD

**Issue by laobaox** [getsentry/sentry#11118]
## Important Details

How are you running Sentry?

* [1 ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

[What happened]
the "organazation > Repositories > add Repository" is not clickable

**Comment by markstory** [comment]
You need to have a repository integration or plugin configured to add repositories.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
