### ISSUE TITLE
I'm not receiving forgot password email

### ISSUE THREAD

**Issue by kinnrot** [getsentry/sentry#11134]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [X ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

[What happened]

## Steps to Reproduce

1. I'm clicking forgot password
2. entering my email click continue
3. get to a confirmation screen that email will be sent
4. not getting any email

### What you expected to happen

getting an email

### Possible Solution

maybe I turned of notifications, and this is the reason I'm not getting ?

**Comment by EvanPurkhiser** [comment]
Hi @kinnrot !

A better place to ask this question would be over on our support forum. https://forum.sentry.io/

Be sure to check your spam inbox :)
