### ISSUE TITLE
sentry.errors.events: preprocess.failed.empty

### ISSUE THREAD

**Issue by ccjetweat** [getsentry/sentry#11156]
my logs:
Dec 27 22:53:20 sc-prod-sentry-02 sentry[28805]: 14:53:20 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:cb0a769026fa44b28281d28bbe85be94:178')
Dec 27 22:53:20 sc-prod-sentry-02 sentry[28805]: 14:53:20 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:68cabffafb114ee882c9c6e60dde2b30:178')
Dec 27 22:53:23 sc-prod-sentry-02 sentry[28805]: 14:53:23 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:618b89942513495ab26350753205fd8b:178')
Dec 27 22:53:35 sc-prod-sentry-02 sentry[28805]: 14:53:35 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:014b4cc0a18441c899f0792777a5b8f5:178')
Dec 27 22:53:49 sc-prod-sentry-02 sentry[28805]: 14:53:49 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:e6af51ffa3174f5f95a7e3d026253c89:178')
Dec 27 22:54:01 sc-prod-sentry-02 sentry[28805]: 14:54:01 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:e77596ba0c4a47928327b7f161b09c7b:178')
Dec 27 22:54:11 sc-prod-sentry-02 sentry[28805]: 14:54:11 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:5ca358b895324609a4cc08263d9d2b0a:275')
Dec 27 22:54:13 sc-prod-sentry-02 sentry[28805]: 14:54:13 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:6017fd57e4a34afe9a3822d2357e21b3:178')
Dec 27 22:54:13 sc-prod-sentry-02 sentry[28805]: 14:54:13 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:b0ad705d32784983a09fb39b6f243af1:275')
Dec 27 22:54:14 sc-prod-sentry-02 sentry[28805]: 14:54:14 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key=u'e:0cb6887b5b824ffc9f9fbeae5a556669:178')
what??

**Comment by Tennen** [comment]
facing this problem in k8s too, any idea how to solve it?

**Comment by angelicaortega-natgeo** [comment]
I'm facing same issue and so far just found this, but I'm still looking for it
https://forum.sentry.io/t/worker-failing-with-sentry-errors-events-preprocess-failed-empty/726

**Comment by mayt017** [comment]
Facing this same issue. Anyone make any progress towards a solution? I will update this issue if I find anything.

**Comment by angelicaortega-natgeo** [comment]
Hi @mayt017  What I did was configure more workers, due to I was experiencing this error because I had a big amount of request, so I was tuning the configuration and it worked,  you can take a look at this article , it might help you
https://docs.sentry.io/server/performance/

**Comment by LL89757** [comment]
Encountered the same problem, does anyone find a solution

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues. This looks more like a configuration issue so closing this thread here. Happy to discuss more at the forums.
