### ISSUE TITLE
Sentry curl_method exec fails on Windows (wamp)

### ISSUE THREAD

**Issue by archon810** [getsentry/sentry#11150]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

We tried switching sentry to curl_method exec and while it did wonders on Linux, on Windows, the command fails badly with hundreds of these in the log:

> The system cannot find the path specified.

I traced the command, and this is what completely fails on Windows: 

`curl -X POST -H "User-Agent: sentry-php/1.10.0" -H "X-Sentry-Auth: Sentry sentry_timestamp=XXXXXXXXXXX, sentry_client=sentry-php/1.10.0, sentry_version=6, sentry_key=XXXXXXXXXXX, sentry_secret=XXXXXXXXXXXXXX" -H "Content-Type: application/octet-stream" -d "XXXXXXXXXXXXX." "https://sentry.io/api/XXXXXXXXXX/store/" -m 5 > /dev/null 2>&1 &`

The reason seems to be the redirect to /dev/null. Without it, the command works. 

Another thing is the & seems to have no effect and the command still executes synchronously and not in the bg, but it's not as bad as it failing entirely.

### What you expected to happen

Sentry works on Windows with exec enabled.

### Possible Solution

https://stackoverflow.com/questions/313111/is-there-a-dev-null-on-windows has the fix to the issue. We should be `> NUL`, not `/dev/null`.

As for starting in the background, perhaps we need `START /B`? https://serverfault.com/questions/31608/can-i-run-a-gui-program-in-the-background-on-the-windows-command-line

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
