### ISSUE TITLE
"Add note" is slow / lack of UI feedback

### ISSUE THREAD

**Issue by dentarg** [getsentry/sentry#1120]
It's takes several seconds for me to add a note to an event. The time isn't so much the problem as the lack of feedback from the UI that the systems is handling my request of adding a note. 

The only indication that something is happening is from the web browser. If you don't notice that, you think that Sentry didn't register your click, and you click the "Add note" button again, and again, and again...

I'm using https://app.getsentry.com. Let me know if you want to investigate my specific projects.

**Comment by dcramer** [comment]
Resolved in redesign
