### ISSUE TITLE
streamline "Create GitHub Issue" workflow

### ISSUE THREAD

**Issue by whit537** [getsentry/sentry#1126]
[Per Twitter](https://twitter.com/whit537/status/436740735908741120).

Here's my current workflow:

A. Click "Create GitHub Issue" in the sidebar. Here's what I see:

![screen shot 2014-02-21 at 1 13 21 am](https://f.cloud.github.com/assets/134455/2227363/534d0462-9abf-11e3-9e53-50f20aae5f05.png)

B. Remember that I have to copy/paste the actual traceback from elsewhere.

C. ⌘-click my browser's "Back" button to open the previous page in a new tab so I don't lose my current state.

D. Switch over to that new tab.

E. Scroll around until I see the "Raw" button and click it.

F. Copy the Stacktrace ("Stacktrace?" :disappointed:) from the popup.

G. Close the popup.

H. Close the second tab.

I. Paste the traceback:

![screen shot 2014-02-21 at 1 17 58 am](https://f.cloud.github.com/assets/134455/2227378/fa063d64-9abf-11e3-8ece-110fa3cf54b6.png)

J. Edit the traceback to look like a Python traceback:

![screen shot 2014-02-21 at 1 19 22 am](https://f.cloud.github.com/assets/134455/2227388/2502dd56-9ac0-11e3-8469-47c242861080.png)

K. Now I'm ready to begin. I can write a descriptive title, and fill out the description with more info.

It'd be nice to cut out B through J (inclusive). :-)

**Comment by MaxBittker** [comment]
the github plugin accomplishes this now, right?
