### ISSUE TITLE
Broker_URL does not support Redis SSL

### ISSUE THREAD

**Issue by sgorshkov85** [getsentry/sentry#11309]
## Important Details

How are you running Sentry?

 https://docs.sentry.io/server/installation/python/
 Installation with Python. 
 Sentry, version 9.0.0.
 ElastiCache Redis with enabled encryption.  

## Description

  The latest Sentry version configured with old Kombu( version 3.0.35). With this package it is not possible to use SSL w/celery using via url string.

## Steps to Reproduce

  Trying to use **rediss**: 
 ```
BROKER_URL = 'rediss://some_password@redis_node:redis_port'
``` 
 At the moment such URL will cause errors:
```
KeyError: 'No such transport: rediss.  Did you mean redis?'
[ERROR] sentry: 'No such transport: rediss.  Did you mean redis?''
```    

### What you expected to happen

 Support 'new' version of Kambu(4.1.0 or higher)

### Possible Solution

 Using 'new' version of Kambu(4.1.0 or higher).

**Comment by szechyjs** [comment]
We are trying to deploy on AWS, however we have `TransitEncryptionEnabled` set in ElastiCache, so `rediss://` is a requirement. It would be nice to be able to set this in the config, in addition to updating kombu.

**Comment by jaysoffian** [comment]
As a work-around you can use stunnel in client mode. This is what I've done till I can backport TLS support to the older versions of celery/kombu that Sentry uses.

**Comment by BYK** [comment]
Looks like the most glaring breaking change is Redis priorities being reversed: https://kombu.readthedocs.io/en/stable/changelog.html#version-4-0

There are a bunch more changes and removals so someone from the team should investigate what is needed to bump the Kombu version.

>It would be nice to be able to set this in the config (env vars for docker), in addition to updating kombu.

We are trying to limit the number of env variables we support for the Docker images so this is unlikely to happen. You can still achieve the same thing by using a custom configuration file which is encouraged.

**Comment by BYK** [comment]
We're on kombu 4.6 so I guess we can close this out. Thanks a lot @wedamija for doing the hard work 🙂
