### ISSUE TITLE
Invalid Dsn in the browser console

### ISSUE THREAD

**Issue by nttdocomo** [getsentry/sentry#11337]
After I update to the latest 9.10dev today。i got an "Invalid Dsn" erro in my browser console. And I found the dsn in the page is "://6f75457663974cac83a90f672e78bde2@/1", it is no valid to the regexp test. so I try to drop the database and create new to run migrate. but the error is still appear. and after i  login. the page is loading, I can't see anything.

**Comment by mattrobenolt** [comment]
You need to configure system.url-prefix in your config.yml file. This also should be set during the setup wizard after you first install.

**Comment by nttdocomo** [comment]
No. I have never seen any notice about to set the system.url-prefix in the setup. I was follow [this docs](https://docs.sentry.io/development/contribute/environment/) to setup my dev.

**Comment by nttdocomo** [comment]
> You need to configure system.url-prefix in your config.yml file. This also should be set during the setup wizard after you first install.

No. I have never seen any notice about to set the system.url-prefix in the setup. I was follow [this docs](https://docs.sentry.io/development/contribute/environment/) to setup my dev.

**Comment by string-areeb** [comment]
Same issue, there are several failures and nothing in docs on how to deal with them

**Comment by string-areeb** [comment]
Also, there was no setup wizard on install because the site just simply fails to load. IMO, this should be re-opened so that at least this is documented
