### ISSUE TITLE
Not able to access sentry.io

### ISSUE THREAD

**Issue by vsag96** [getsentry/sentry#11415]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

When trying to go to the website, I get the following prompt on both chrome and firefox and site loading stops

Please wait while we load an obnoxious amount of JavaScript.
You may need to disable adblocking extensions to load Sentry.

## Steps to Reproduce

1. Just go to sentry.io/user-name/

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration when relevant

### What you expected to happen

I should have been taken to my projects, where crash reports are shown

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by markstory** [comment]
Closing as we had a temporary problem with an internal system that has been resolved.
