### ISSUE TITLE
Let user subscribe/unsubscribe to note emails per-project

### ISSUE THREAD

**Issue by gthb** [getsentry/sentry#1143]
Right now users can only subscribe or not subscribe, to note notifications overall; the user option always has a NULL `project_id`:

```
id         | 8
user_id    | 8
project_id | <<NULL>>
key        | subscribe_notes
value      | gAJYAQAAADEu
```

and is accordingly looked up irrespective of project [in activity.py](https://github.com/getsentry/sentry/blob/8b1b872267/src/sentry/models/activity.py#L109-L113),

```
        disabled = set(UserOption.objects.filter(
            user__in=user_id_list,
            key='subscribe_notes',
            value='0',
        ).values_list('user', flat=True))
```

Instead, this should be controllable per-project (like the `mail:email` user option), so that a user can have _access_ to a project P1 but turn off all email from it, while still getting all notifications (including notes) for project P2.

(This was the reason behind #1141 — a user had set a bogus email address for some projects, as a workaround for this.)

**Comment by stig** [comment]
:+1: As a person with more operational focus I am not so interested in receiving notifications from DEV projects, but would still like access to view it to aid in debugging occasionally.

**Comment by benvinegar** [comment]
We've made a number of significant improvements to notifications since the last comment on this ticket, including fine-grained controls over which projects you want to receive / don't want to receive notifications from.

I'm closing this issue, but if you feel the new capabilities don't solve your issue, please re-open.
