### ISSUE TITLE
Make it possible to assign events to people

### ISSUE THREAD

**Issue by asbjornu** [getsentry/sentry#1144]
It would be awesome if it was possible to assign events and event groups to people in the team as a way to notify them about the problem and to place ownership (and blame) for a problem. It would almost work like any ordinary task management system, but it does not need to be heavyweight or complicated. Just an "Assign to" link with a drop down list of users in the team would do. When someone is assigned, they should get an e-mail informing them about this, and then notes can be used as a way to discuss between different team members.

**Comment by nferrari** [comment]
+1

**Comment by pratik60** [comment]
+1

**Comment by dcramer** [comment]
I'm going to close this out as it exists on the backend (via the API, in production) and in our redesign branch:

![screenshot 2015-04-07 15 13 41](https://cloud.githubusercontent.com/assets/23610/7034895/ba8bed2a-dd38-11e4-9da8-4636d3bf91c7.png)

**Comment by asbjornu** [comment]
When will the redesign branch be integrated into master and published to getsentry.com?

**Comment by georgexsh** [comment]
+1

**Comment by scottweisman** [comment]
+1

**Comment by john-kelly** [comment]
+1

**Comment by dcramer** [comment]
Closing this as its done in the API and will be visible when the new frontend is landed
