### ISSUE TITLE
c# project example error

### ISSUE THREAD

**Issue by chancelyg** [getsentry/sentry#11455]
Installing the Sentry by my server success
my install method is pip
```
pip install sentry
```
In new create c# project , example is this:
```
var ravenClient = new RavenClient("http://76e85db534174984bfb995a97061d892@xxx.chancel.cn//4");
……
```
But this url is error,right url is this:
```
var ravenClient = new RavenClient("http://76e85db534174984bfb995a97061d892@xxx.chancel.cn/4");
……
```
Is '/' and not is '//'
'//' will trigger csrf verification failed
![tim 20190110115958](https://user-images.githubusercontent.com/38032874/50945358-4599bd80-14cf-11e9-80f5-6b86adfc51a3.jpg)

**Comment by bruno-garcia** [comment]
Raven has been deprecated.
Please use our new [Sentry SDK](https://github.com/getsentry/sentry-dotnet) for .NET
