### ISSUE TITLE
Add ability to not send alert if assignee is present

### ISSUE THREAD

**Issue by meelispr** [getsentry/sentry#11457]
## Summary

Would be nice to be able to add check if any of these rules match but assignee is present then don't send the alert. Alternatively there can be an option in the error itself to make it not trigger alerts.

## Motivation

Some alerts might be noisy and you don't want to just ignore them because new data points might come in but at the same time if someone is already assigned to deal with the issue then it shouldn't be sent to slack for everyone to see.

**Comment by adhiraj** [comment]
1. Would you want the alert to continue alerting the person who's assigned? 
2. Would you want this to be a project-level setting (i.e. applies to all alert rules in the project), or per alert rule?

**Comment by meelispr** [comment]
1. IMHO it's not that relevant. Nice to have the option, but not relevant.
2. In our case it would be nice if this was a project level setting.

**Comment by adhiraj** [comment]
Added in https://github.com/getsentry/sentry/pull/20364
