### ISSUE TITLE
Failed building wheel for hiredis

### ISSUE THREAD

**Issue by whybangbang** [getsentry/sentry#11479]
ailed to build mmh3 setproctitle uwsgi hiredis
redis-py-cluster 1.3.6 has requirement redis==2.10.6, but you'll have redis 2.10.5 which is incompatible.
Installing collected packages: strict-rfc3339, mmh3, django-picklefield, python-memcached, django-jsonfield, percy, python-dateutil, jmespath, docutils, botocore, olefile, Pillow, BeautifulSoup, python-u2flib-server, email-reply-parser, exam, redis-py-cluster, qrcode, setproctitle, django-crispy-forms, Django, futures, selenium, pytest-html, symbolic, contextlib2, raven, s3transfer, boto3, statsd, djangorestframework, uwsgi, hiredis, jsonschema, pytest-django, structlog, sentry
  Running setup.py install for mmh3 ... error
    Complete output from command /www/sentry/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-bRlHnu/mmh3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1oStQ3/install-record.txt --single-version-externally-managed --compile --install-headers /www/sentry/include/site/python2.7/mmh3:
    running install
    running build
    running build_ext
    building 'mmh3' extension
    creating build
    creating build/temp.linux-x86_64-2.7
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.7 -c mmh3module.cpp -o build/temp.linux-x86_64-2.7/mmh3module.o
    mmh3module.cpp:9:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/www/sentry/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-bRlHnu/mmh3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-1oStQ3/install-record.txt --single-version-externally-managed --compile --install-headers /www/sentry/include/site/python2.7/mmh3" failed with error code 1 in /tmp/pip-install-bRlHnu/mmh3/

**Comment by mattrobenolt** [comment]
You need python-dev package to compile.

**Comment by whybangbang** [comment]
@mattrobenolt  thank you very much

**Comment by heidarymr** [comment]
> You need python-dev package to compile.

root@sentry:~# sudo apt-get install -y python-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-dev is already the newest version (2.7.12-1~16.04).
0 upgraded, 0 newly installed, 0 to remove and 33 not upgraded.


but i got this error:
Building wheels for collected packages: mmh3
  Building wheel for mmh3 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/sentry/sentry_app/bin/python2 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-FxU8YM/mmh3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-FxU8YM/mmh3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yTnEAY --python-tag cp27
       cwd: /tmp/pip-install-FxU8YM/mmh3/
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'mmh3' extension
  creating build
  creating build/temp.linux-x86_64-2.7
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c mmh3module.cpp -o build/temp.linux-x86_64-2.7/mmh3module.o
  x86_64-linux-gnu-gcc: error trying to exec 'cc1plus': execvp: No such file or directory
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for mmh3

**Comment by heidarymr** [comment]
solution:
sudo apt-get update
sudo apt-get install --reinstall build-essential
