### ISSUE TITLE
Attach environment name when creating release via API

### ISSUE THREAD

**Issue by MikeElghali** [getsentry/sentry#11561]
Hi,

Is there any way to add environment name (local, staging, prod,...) to the release when i created it via your API?

Currently, all releases are attached to "All environments" with this template:

```bash
# Create a new release
curl https://sentry.io/api/0/organizations/:ORG/releases/ \
  -X POST \
  -H 'Authorization: Bearer :TOKEN' \
  -H 'Content-Type: application/json' \
  -d '
{
    "version": ":COMMIT_REF",
    "refs": [
        {
            "repository": ":REPOSITORY_NAME",
            "commit": ":COMMIT_REF"
        }
    ],
    "projects": [
        ":PROJECT_NAME"
    ]
}
'
```

Thanks,
Regards.

**Comment by markstory** [comment]
Environments are set when you create a 'deploy' of a release to an environment. The [create deploy docs](https://docs.sentry.io/api/releases/post-release-deploys/) cover how to use that API.
