### ISSUE TITLE
Search for Asana task by URL

### ISSUE THREAD

**Issue by danpalmer** [getsentry/sentry#11607]
## Summary

To link an issue to an Asana task you can create a new task or search for an existing one. This is inefficient if you have the direct link to the Asana task. The search box should recognise Asana task URLs and return the linked task as the only search result.

## Motivation

We use Asana to track all tasks within our product and engineering teams, so it's a critical part of our workflow, and having a tight and efficient integration with Sentry is key to the success of our migration to Sentry. We often pass around Asana URLs, have tooling built around them, and use them in code comments, pull requests, Slack chats, etc.

Currently the process for linking an Asana URL to a Sentry issue is:

1. Open the Asana URL (Asana isn't the fastest, so this can take a while)
2. Copy the title of the task
3. Paste it into Sentry's link-to-Asana search
4. Find the correct task (could be tricky if similarly named tasks)
5. Save

This could be:

1. Paste URL into Sentry's link-to-Asana search
2. Exact match on search means only 1 result
3. Save

Happy to answer any questions about our usage, to clarify our setup, etc.

**Comment by lauryndbrown** [comment]
Hi, @danpalmer, I agree that this is a nice feature, but right now Asana isn't being actively worked on as it's one of our legacy plugins.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
