### ISSUE TITLE
Small issue with localization

### ISSUE THREAD

**Issue by rasky** [getsentry/sentry#1163]
When Sentry is translated to Italian, I see this box:

![screenshot 2014-04-07 17 07 59](https://cloud.githubusercontent.com/assets/1014109/2632679/a127e7a4-be66-11e3-9bda-2ecd40d24129.png)

The rows of the table are not aligned correctly. For instance "3 ore fa" (3 hours ago) should be vertically aligned with "Ultima occorrenza" ("Last occurrence").

**Comment by mattrobenolt** [comment]
This is for an older unsupported version of Sentry now.
