### ISSUE TITLE
DSN Auth for the API doesnt seem to work

### ISSUE THREAD

**Issue by XzenTorXz** [getsentry/sentry#11642]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.0.0] installed via helm

## Description

When Trying to access "DSN friendly" API resources I always get the message "Authentication credentials were not provided." when using the header Authorization-Header with "DSN X".

I'm trying to create a Custom Dialog for User Feedback, but I cant get the API to work. If I setup an API key and use the "Bearer"-Auth it works, but it doesnt with DSN-Auth. It should be possible since the [docs](https://docs.sentry.io/api/projects/post-project-user-reports/) state it should be possible with DSN.
So I thought it might be a problem with the user feedback, but i couldnt get the [basic dsn auth example ](https://docs.sentry.io/api/auth/) to work. I also tested this one on sentry.io-api.

## Steps to Reproduce

1. create project
2. curl -H 'Authorization: DSN {DSN}' https://sentry.io/api/0/projects/

results in `Authentication credentials were not provided.`

Example-Post and Answer for Userfeedback:
```
POST /api/0/projects/myOrg/myProj/user-feedback/
Content-Type: application/json
Authorization: DSN 1c34634cee034xxxxxxxxxxxxxxxxxxx
cache-control: no-cache
Accept: */*
Host: sentry.somedomain.com
accept-encoding: gzip, deflate
content-length: 144
{ 
 "comments": "It broke!", 
 "email": "jane@example.com", 
 "event_id": "80d12f21c6dd4f33a38be8728e332d68", 
 "name": "Jane Smith"
 }
HTTP/1.1 401
status: 401
Server: nginx/1.13.12
Date: Tue, 22 Jan 2019 15:19:40 GMT
Content-Type: application/json
Content-Length: 59
Connection: keep-alive
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Language: en
Vary: Accept-Language, Cookie
Allow: GET, POST, HEAD, OPTIONS
X-Frame-Options: deny
WWW-Authenticate: xBasic realm="api"
Strict-Transport-Security: max-age=15724800; includeSubDomains
{"detail": "Authentication credentials were not provided."}
```

### Possible Workaround

I checked how the feedback widget is doing it, but it uses a diffrent endpoint `api/embed/error-page/?dsn=https://{DSN}@sentry.io/....` that one works, so you could use this for a temp. workaround.

**Comment by ricardoglez** [comment]
Im having a similar issue, with both auth methods ( DSN and Bearer ):

i am using this object to config the options in axios:

```

  const instanceSentry = axios.create( );
  const url = `https://sentry.io/api/embed/error-page/?dsn={dsn}`;

  const authOptions = {
      method: 'POST',
      url: url,
      data: reportData,
      headers: {
          'Authorization': 'DSN {dsn}',
          'Content-Type':'application/json'
      }

```
but i keep getting the Options auth error ( 400 ):
```
OPTIONS https://sentry.io/api/{...} 400 (BAD REQUEST)

Access to XMLHttpRequest at ... has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```

Ive tried the Bearer Auth instead but i get the same error,

But when i use this command it didn't complain at all:

```
curl -H 'Authorization: Bearer {token}' https://sentry.io/api/0/projects/{myProject}/user-feedback

```
ive also tried the workaround posted by @XzenTorXz , but it didnt work for me

**Comment by Batistleman** [comment]
Any updates on this? It's not working for us either...

**Comment by XzenTorXz** [comment]
@ricardoglez it is a bit tricky since you have to douple post the data via post and get, here is how our jquery post looks like:

```
.ajax({
    method: "post",
    url:
      "https://" + sentryHOST +
      "/api/embed/error-page/?dsn=" +
      sentryURL +
      "&name=" + userName +
      "&email=" + email +
      "&title=BugReport&subtitle=&subtitle2=&successMessage=&eventId=" +
      eventId,
    data: {
      comments: msg,
      email: email,
      event_id: eventId,
      name: userName
    }
  });
}
```
where sentryHOST is just the host like `sentry.example.com` and sentryURL the whole host `https://DSN@sentry.example.com/PROJECTID`

**Comment by raymundoxmartinez** [comment]
getting the following error "authentication credentials were not provided"
it works fine in postman but having trouble making it work in webapp.

request({
      method: 'post',
      headers: {
        Host: 'sentry.aitmed.com',
        Authorization:
          'Bearer TOKEN',
        'Content-Type': 'application/json',
      },
      data: {
        comments: 'It broke!',
        email: 'jane@example.com',
        event_id: '14bad9a2e3774046977a21440ddb39b2',
        name: 'Jane Smith',
      },
      url: urls.sentry.createUserFeedback,
    })

**Comment by ricardoglez** [comment]
@XzenTorXz What do you mean by 'double post the data via post and get'?

First i updated my request as your workaround ive just added the Bearer case i was keeping the Auth Credentials stuff:

```
   const reportData = { 
    name: 'Ricardo',
    email:'ricardomail@mail.com',
    event_id: 1223,
    comments:'Help!'
}
    const errorUrl = `https://sentry.io/api/embed/error-page/?dsn=https://{MyDSN}@sentry.io/{MyID}&name=${reportData.name}&email=${reportData.email}&title=BugReportID&subtitle=&subtitle2=&successMessage=&comments=${reportData.comments}&eventId=${reportData.event_id}`;

    const authOptions = {
      method    : 'POST',
      url       : errorUrl,
      headers   : {
            'Authorization': 'Bearer {MyToken}',
            'Content-Type':'application/json'
        },
    };

```

I think that i am close , cause im not getting the Auth error anymore, but i've got an error from the response that it need required fields in the post data, but as you can see my data is complete:

The error is the following  :
```
POST https://sentry.io/api/embed/error-page/?dsn=https://{MyDSN}@sentry.io/{MyID}&name=Ricardo&email=ricardomail@mail.com&title=BugReportID&subtitle=&subtitle2=&successMessage=&comments=Help!&eventId=1223 400 (BAD REQUEST)


errors: {name: ["This field is required."], comments: ["This field is required."],…}
comments: ["This field is required."]
email: ["This field is required."]
name: ["This field is required."]
```

In the payload i can see that my data is there so im a little lost here.
```

{"name":"Ricardo","email":"ricardomail@mail.com","comments":"asdasdasd","event_id":"1223"}
```

What i'm missing?

**Comment by XzenTorXz** [comment]
@ricardoglez i just ment that you also need to use the Query-Part of your PostUrl `?dsn=...`, but you allready did that.
I think you also need to use real eventIds that actually occured and it needs to be within 30min after the orrurence (https://docs.sentry.io/api/projects/post-project-user-reports/)

**Comment by ricardoglez** [comment]
> I think you also need to use real eventIds that actually occured and it needs to be within 30min after the orrurence (https://docs.sentry.io/api/projects/post-project-user-reports/)

Thanks @XzenTorXz i was using real event_ids, but for a weird reason it wasn't working with axios, and with native fetch in js.


I've finally made it work using jquery ajax, using your workaround.  :+1: 
 
> ```
> .ajax({
>     method: "post",
>     url:
>       "https://" + sentryHOST +
>       "/api/embed/error-page/?dsn=" +
>       sentryURL +
>       "&name=" + userName +
>       "&email=" + email +
>       "&title=BugReport&subtitle=&subtitle2=&successMessage=&eventId=" +
>       eventId,
>     data: {
>       comments: msg,
>       email: email,
>       event_id: eventId,
>       name: userName
>     }
>   });
> }
> ```

Just a last question :question:  , are you guys getting some response using this method? im just getting an empty object as the response. but with a status 200 :worried: .

**Comment by JonathanCa97** [comment]
I also have this issue. Anybody already looked into this? @dashed  ?

**Comment by nfrasser** [comment]
I'm able to get it working if I use the full DSN URL in the Authorization header. Both of these worked for me

With curl
```sh
curl \
    -d '{"event_id":"1234","name":"Nick","email":"nick@example.com","comments":"Hello World"}' \
    -H 'Content-Type: application/json' \
    -H 'Authorization: DSN https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@sentry.io/#######' \
    -X POST https://sentry.io/api/0/projects/org-name/project-name/user-feedback/
```

With axios

```js
const params = {
    event_id: "1234",
    name: "Nick",
    email: "nick@example.com",
    comments: "Hello World"
}

const config = { 
    headers: { 
        Authorization: 'DSN https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx@sentry.io/#######' 
    } 
}

await axios.post(endpoint, params, config)
```

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
