### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by se-bastiaan** [getsentry/sentry#11668]
It's been some time since the latest release of Sentry. Over 6 months and I don't know how many commits.
I noticed that https://github.com/getsentry/sentry/commit/31a48d597d027c2a21083f122da5a992e493c742 must be running on sentry.io since the settings page matches that commit.

If your software is open source, you maintain it in a completely open repository then why is there no release once functionality is done or bugs are fixed? I understand that releasing probably isn't a priority and that you don't have any obligation to release. However, why wouldn't you if you deem your code stable enough to run your own platform?

**Comment by mattrobenolt** [comment]
https://forum.sentry.io/t/when-will-a-new-version-be-tagged-for-sentry-open-source/5622

This should answer any questions you may have regarding this.

**Comment by se-bastiaan** [comment]
Well that explains that I couldn't find anything when searching for 'releases'. At least it's documented here on GitHub now so that other's don't have to do the search work.
