### ISSUE TITLE
Slack Integration: cannot reactivate after removing

### ISSUE THREAD

**Issue by itimgit** [getsentry/sentry#11662]
Listed as not installed, when trying to install: "already installed"
![image](https://user-images.githubusercontent.com/7840684/51603942-8cde7000-1f0b-11e9-808c-91230523348d.png)

**Comment by lauryndbrown** [comment]
cc @EvanPurkhiser

**Comment by EvanPurkhiser** [comment]
Can you try removing the app in your slack workspace settings and then installing from Sentry's side?
