### ISSUE TITLE
How to create a superuser to manage some data through API？

### ISSUE THREAD

**Issue by FeSeason** [getsentry/sentry#11661]
## Summary

In this front-end address【${HOST}/manage/projects/】, all project information can be obtained through the interface【/api/0/internal/stats/】, but this API 【https://docs.sentry.io/api/projects/get-project-index/】can only get the projects related to you, not all of them.authorization.

## Motivation

We want to authorize access to relevant data through services，

## Additional Context

![](https://ws2.sinaimg.cn/large/006tNc79gy1fzgk75oxrgj31du0p2wi3.jpg)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
