### ISSUE TITLE
Add a Microsoft Teams Integration

### ISSUE THREAD

**Issue by nie7321** [getsentry/sentry#11690]
## Summary
I'd really like a [Microsoft Teams](https://products.office.com/en-us/microsoft-teams/group-chat-software) integration that has parity with the Slack one.

## Motivation
My org recently moved from Slack to Teams and it seems the best I can get are some really anemic webhook notifications -- there is barely any info presented in chat:

![screen shot 2019-01-24 at 10 27 01 am](https://user-images.githubusercontent.com/27235866/51692474-9d9ded00-1fc2-11e9-917a-a1cfa697ff5d.png)

This really hurts after having all the details presented in Slack along with action buttons.

**Comment by peterfarrell** [comment]
What can I do to help developing an integration.

**Comment by josh-degraw** [comment]
Has there been any progress on this one? It would also be nice for this to work on the org level rather than project by project via the legacy integration.

**Comment by josh-degraw** [comment]
For anyone it may help, [sentry-msteams](https://github.com/Neko-Design/sentry-msteams) is a pretty great alternative. It's still project-by-project, but it's got a lot more information in it than the standard integration.

**Comment by toancaro** [comment]
@josh-degraw how to use/install that plugin? Their documentation is not much. I'm using [https://sentry.io/](https://sentry.io). Thank you.

**Comment by josh-degraw** [comment]
@toancaro I'm using it in an on-premise sentry server, I'm not actually sure if it works with the hosted version now that I think about it...

**Comment by nie7321** [comment]
FWIW, BugSnag has OK Teams support.

**Comment by simformsolutions** [comment]
Any updates on this issue for full error or issue details instead of just level:error. We need full error details in microsoft teams.

**Comment by it-painchek** [comment]
My organisation is considering using Microsoft Teams in place of Slack and would also like to see the Teams integration work as well as it did for under Slack.

Are there any plans to do this?  I'm using https://sentry.io/. Thank you.

**Comment by drewzh** [comment]
I seem to have issues getting the sentry-msteams to register on the Integration tab in Sentry on premise version 10. Anyone having similar issues or know how to resolve? I'll also raise a ticket on the relevant repository of course.

**Comment by lucbas** [comment]
Same for us, org is probably switching to Teams

**Comment by jezmck** [comment]
We've been forced to switch to Teams, so here's another vote.
(apologies for the spam)

**Comment by vincent-paing** [comment]
Last updated time is 2018. We really need a upgrade on Teams integration!

**Comment by grv231** [comment]
In the same boat as others. We recently started using **on-prem sentry** and were happy with slack integration but slack would be going away soon for MS teams. Any work/update on it would be highly appreciated

**Comment by jezmck** [comment]
https://twitter.com/eurica/status/1255900857888997376?s=19

> In this case Microsoft controls the Teams-Sentry integration but we’ve definitely noticed a lot more Microsoft Teams usage over the last year and are looking at ways to make that experience better.

😕

**Comment by jonesphillip** [comment]
As @jezmck referenced, the existing Teams integration is developed and maintained by Microsoft. We hear the feedback about providing more details in notifications, and are planning to address it!

Will keep this thread up to date on the status.

**Comment by jezmck** [comment]
Might it be better to create a new integration which uses their APIs, but isn't controlled by them?

**Comment by vincent-paing** [comment]
Would love to help in anyways I can if you want to make a new plugin

**Comment by scefali** [comment]
FYI, we are working on a new Microsoft Teams integration. It will be available sometime in August.

**Comment by exosyphon-meritize** [comment]
@scefali Is this still being released in August?

**Comment by eliorivero** [comment]
Last few hours of August!!
Seriously, a Teams integration would be great. Just tried the legacy WebHooks and it outputs nothing.

**Comment by jezmck** [comment]
Just an update would be appreciated 🙂

**Comment by jonesphillip** [comment]
Our Sentry Microsoft Teams app is currently being reviewed by Microsoft. Depending on how long the review process takes, it may be another week or so. But we'll keep this issue updated!

**Comment by scefali** [comment]
And it's live! Check it out in the Teams app store: https://teams.microsoft.com/l/app/5adee720-30de-4006-a342-d454317db1d4?source=store-copy-link

**Comment by jezmck** [comment]
I can't open that link on mobile?
It wants me to get the app, which I already have.

**Comment by jonesphillip** [comment]
@jezmck  For more information on installation I'd recommend checking out our docs: https://docs.sentry.io/product/integrations/msteams/

Let us know if you have any other questions/feedback throughout the process

**Comment by geekmush** [comment]
Does this work for standalone Sentry installs or only for the hosted
version?

We can't use the hosted version and the stand alone doesn't speak Teams
properly ... We were able to make an old plugin work in our old cluster,
but it no longer works on our new Sentry installation...

**Comment by cpressland** [comment]
We're unable to use the hosted version of Sentry for compliance reasons - it doesn't look like the new Teams Bot supports self-hosted versions. Is this expected @jonesphillip?

**Comment by scefali** [comment]
@geekmush Yea, it will work with on-prem Sentry. We just need to add the docs for it. Since this issue is closed, could you make a new Github issue for on-prem Sentrih with Microsoft Teams?

**Comment by jezmck** [comment]
@jonesphillip Thanks for your work on this.
I was letting you know of a UX problem, rather than asking for help.

**Comment by laurenz-glueck** [comment]
@scefali First of all, thanks a lot for making the new Teams integration possible! Great job 👍 
I have a small feedback to share:

![sentry-notifications-cut-off](https://user-images.githubusercontent.com/2734232/95964610-4b8da280-0e09-11eb-8c30-0eb6651b9c51.png)

Would it be possible to prevent Teams from cutting off the description (as you can see on the screenshot) and maybe just break it to the next line? The current behavior is kind of annoying as you don't see the whole message...

In comparison to Slack (here you see the whole message):
![sentry-slack-notification](https://user-images.githubusercontent.com/2734232/95965032-c2c33680-0e09-11eb-82fe-297ec53f567a.png)

**Comment by discover59** [comment]
@jonesphillip Sentry message is wrong in teams.

In teams, it says `No data for client 30`.
When I clicked link to sentry error page, actual error message is `No data for client 50`.
