### ISSUE TITLE
SaltStack-powered automated install on Centos 6

### ISSUE THREAD

**Issue by unicolet** [getsentry/sentry#1170]
I have written a set of [SaltStack](http://saltstack.org) states to automate installing Sentry on Centos 6. If an issue is not the right way to announce them, please advise and accept my apologies.

The states might need a few improvements like a one-liner bootstrap script, a Celery init script, and likely Ubuntu support, but are otherwise working fine.

The states are at: https://github.com/unicolet/salt-sentry

**Comment by mattrobenolt** [comment]
Closing since there's nothing we can do here, and this is 2 years old, so way out of date for sentry 8 anyways.
