### ISSUE TITLE
`date_from` should be configurable

### ISSUE THREAD

**Issue by WoLpH** [getsentry/sentry#1172]
For some projects it is useful to just see the new errors, but for some others (like less active hobby projects) it is not useful to filter all issues older than 5 days. For some projects I look at the issues once every month and in that case it's just an annoyance that issues automatically become hidden after 5 days.

So my request would be to make the `date_from` parameter configurable instead of hardcoded as it is now:
https://github.com/getsentry/sentry/blob/master/src/sentry/web/frontend/groups.py#L90

The code seems silly (and possibly broken) anyhow, just because `date_from` is passed as a `GET` parameter doesn't mean the `date_to` should be parsed as well.

I would propose something like this instead:

``` python

# date format is Y-m-d
if date_from is not None or time_from is not None:
    date_from = parse_date(date_from, time_from)
elif settings.DATE_FROM_DAYS:
    date_from = today - datetime.timedelta(days=settings.DATE_FROM_DAYS)
else:
    date_from = None

# date format is Y-m-d
if date_to is not None or time_to is not None:
    date_to = parse_date(date_to, time_to)
elif settings.DATE_FROM_DAYS:
    date_to = today - datetime.timedelta(days=settings.DATE_TO_DAYS)
else:
    date_to = None
```

**Comment by MaxBittker** [comment]
this is configurable in search now, no?
