### ISSUE TITLE
Allow personal profiles in GitLab integration

### ISSUE THREAD

**Issue by flaksp** [getsentry/sentry#11735]
## Summary

Add ability to integrate Sentry with personal GitLab profile.

## Motivation

Currently it's possible to integrate Sentry with any group inside GitLab. But a lot of users own repositories located in their personal profiles/accounts. For example, GitHub integration allows using Sentry for repositories located inside your personal GitHub account.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by AndreyKravchina** [comment]
I still need that fix.

**Comment by BYK** [comment]
@AndreyKravchina I don't think we'll be able to work on this any time soon given the lack of interest (both external and from Sentry team) for over a year now. If you want to take a stab at submitting a PR to address it, nobody would stop you though! (on the contrary, we'd help you till the finish line)
