### ISSUE TITLE
Auto unresolving and deployed vs released projects

### ISSUE THREAD

**Issue by jaysoffian** [getsentry/sentry#1175]
Sentry un-resolves (marks as a regression) an error (event group) upon receiving that same error again after it has been marked resolved. This makes sense for deployed projects where you can control the upgrade cycle.

However, for released projects, say a mobile app, this behavior doesn't make sense. Rather, you'd only want to consider an error as a regression if that same error shows up from a newer version of the project.

I'd like to enhance Senty's support for this scenario, and I'm looking for guidance on how best to do so. The simplest change would be a configuration setting to disable auto-unresolving site-wide, slightly more complicated would be to make it a per-project setting. This later capability is similar to how Squash handles things - https://github.com/SquareSquash/web#deploys-and-releases

Ideally I'd like to teach Sentry some notion of a software version associated with errors. Thus if an error is marked resolved in 1.0, it only becomes unresolved if that same error shows up in > 1.0. Comparing versions can be tricky, so the version should adhere to a standard format such as a simple integer or semantic versioning.

Do you have any suggestions on how to go about this? Possibly base it on the rules work being done in 7.0?

**Comment by dcramer** [comment]
I'm going to close this out as the beginnings of releases exist and this ticket is no long reflective of the state of the world
