### ISSUE TITLE
GET call project environments Sentry API

### ISSUE THREAD

**Issue by DerkSchooltink** [getsentry/sentry#11762]
## Summary

Currently there is no suitable way to get the environments listed in a Sentry project. As I am categorizing found events under an environment, it would be incredibly helpful to expose a RESTful API endpoint in the Sentry API, similar to the current implementation of listing a project's debug files: `/api/0/projects/{organization_slug}/{project_slug}/files/dsyms/`

## Motivation

Currently I am executing a call for recent events in a project, from which I gather unique environments (they are listed in events as fields in the JSON result). This requires a heavy call on the API for events, and also requires the end-user to break down the events into unique environments.

This takes increasingly longer to execute if you have multiple projects for which this call have to be executed.

## Additional Context

I would implement the endpoint on the endpoint similar to the project's debug files endpoint: `/api/0/projects/{organization_slug}/{project_slug}/environments`

An expected result (in JSON) would be roughly:

```
{
  "project": "project_slug",
  "organization": "organization_slug",
  "environments": {
    "hidden": [
      "some_env_1",
      "some_env_2"
    ],
    "public": [
      "some_env_3",
      "some_env_4"
    ]
  }
}
```

There is no additional information to environments except for whether they are hidden or not, so this seems like a relatively easy structure to provide and to construct.

Also a pre-emptive apology if this is not the place to request a feature for the API, I could not find a GitHub project for the API.

**Comment by markstory** [comment]
Does the existing project environments API endpoint not do what you want? It has the URL pattern of `^projects/(?P<organization_slug>[^\/]+)/(?P<project_slug>[^\/]+)/environments/$` and returns the environments attached to a project indicating their id, name and hidden flags.

**Comment by DerkSchooltink** [comment]
> Does the existing project environments API endpoint not do what you want? It has the URL pattern of `^projects/(?P<organization_slug>[^\/]+)/(?P<project_slug>[^\/]+)/environments/$` and returns the environments attached to a project indicating their id, name and hidden flags.
> 
> https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/project_environments.py is the related endpoint code.

Correct me if I'm wrong but this is the Python API, and I am looking for the web API as documented here: https://docs.sentry.io/api/

Ultimately, the feature you quote is exactly what I want, but since I work in Kotlin adopting the Python API is not really suitable (albeit possible).

**Comment by markstory** [comment]
@DerkSchooltink I did link to the python code, but that python code is wired up to the the REST API via the URL pattern (eg. `/api/0/projects/org-name/project-name/environments/`). The endpoint has no documentation which is why it doesn't show up in docs.sentry.io

**Comment by DerkSchooltink** [comment]
> environments

Ah, right, my apologies! Thank you so much for the quick response!

I will close the issue then as it is solved. A small side-note though: perhaps it's a good idea to document this feature on the API docs so people like me won't pollute the issue pages of your GitHub. :)
