### ISSUE TITLE
Use to much memory while delete issue

### ISSUE THREAD

**Issue by dIoMeDs** [getsentry/sentry#11797]
Hi!
Sentry version: 8.22.0
OOM'ed when delete issue with 3.9 million events. We have an old issue with large count of enents for 1 year. When running delete or cleanup (otherwise) it "eat" all 8Gb memory and go far away in swap up to 20Gb swap.
Is it ok?

**Comment by markstory** [comment]
>  Is it o

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
