### ISSUE TITLE
Jira Server Integration: not working

### ISSUE THREAD

**Issue by wilk** [getsentry/sentry#11849]
after following the guidelines both for jira and sentry, nothing happens and the integration remains the same (not installed).
what can I do?

**Comment by markstory** [comment]
Hey @wilk There is an omission in the documentation regarding the configuration for the OAuth application in Jira.

In Jira, you have to add an 'OAuth Consumer Callback' to the Incoming Link. To do that you can:

1. Go to the application links
2. Edit the link details.
3. In the 'Incoming Authentication' tab, delete the credential set (as jira doesn't allow editing)
4. Re-enter the consumer key, name, public key, and set the 'oauth consumer callback url' to `https://sentry.io/extensions/jira_server/setup/ `

I hope to have the setup documentation updated soon.

**Comment by eliang** [comment]
I'm running into the following issue after allowing the application access:

```Could not create issue webhook in Jira. You do not have permission to create WebHook 'Sentry Issue Sync'.```

**Comment by wilk** [comment]
@markstory sorry, I didn't reply. It worked, thanks a lot.
