### ISSUE TITLE
Adjust required permissions for Oauth login with GitHub

### ISSUE THREAD

**Issue by Wessie** [getsentry/sentry#1186]
The current Oauth login with GitHub asks for the following permissions:

```
This application will be able to read and write all public and private repo data.
This includes the following:

- Code
- Issues
- Pull requests
- Wikis
- Settings
- Webhooks and services
- Deploy keys
```

With the changes to the GitHub permissions I believe sentry can ask for less permissions than it currently does.

**Comment by hvdklauw** [comment]
Why is this not fixed yet? I'm really now allowing sentry to request access to all that..

The only thing it needs afaics is issue creation.

**Comment by dcramer** [comment]
@hvdklauw are you suggesting a scope that we can use that allows access to private repos and issue creation? 

https://developer.github.com/v3/oauth/

I dont see any here that suggest its possible.

**Comment by hvdklauw** [comment]
Contacted github, hope they fix it.. this is just idiotic.

**Comment by blackjid** [comment]
Hey would it be possible to ask the repo:wirte permissions only when you enable

**Comment by dcramer** [comment]
The integration permission definitely seems useful.

There is complexity in trying to upgrade the account on demand as right now SSO and integrations know nothing about each other in sentry

**Comment by blackjid** [comment]
> There is complexity in trying to upgrade the account on demand as right now SSO and integrations know nothing about each other in sentry

Maybe I'm being naive, but.. wouldn't github just ask for the extra permission when you try to reauthorize with an extra scope??

**Comment by dcramer** [comment]
It *might* be, but I haven't confirmed. I think likely what would have to happen is it'd have to re-request the existing scopes + what it needs. There's also the concern about what do you do to downgrade scopes?

**Comment by blackjid** [comment]
mm, yes... you might just go to github and revoke the access. After that you could resign and the access will be requested again...

**Comment by brandonbloom** [comment]
This prevents me from using Sentry: I can't grant access to my private repositories just to authenticate.

**Comment by dcramer** [comment]
@brandonbloom then use Google SSO, or don't use SSO. At some point we plan to change this, but quite frankly GitHub isn't a great solution for single sign-on. This feature is *not* required to use Sentry.

**Comment by brandonbloom** [comment]
Apologies for my brevity before. My goal was to cast a vote for resolving this issue, but in my hurry, I totally failed to politely provide adequate justification for that vote.

I'm doing some contract work for a client who uses GitHub SSO for a Sentry install. I asked them to switch to Google SSO, but I don't want to dictate such an inconvenience to them. It doesn't seem like it will be a problem for this client, but it's a problem more generally.

**Comment by julianrutten** [comment]
Any update on this issue? Obviously we cannot allow 3rd party access to propriety code bases when all I need to do is have the issues sent to github. Now we would have to write this ourselves using the webhook feature, not really ideal.

**Comment by dcramer** [comment]
@julianrutten if you’re using saas you should consider just going through a security review of Sentry. We don’t actually pull in your repos unless you tell us too (and GitHub alerts you when keys are added). I get the concern, but we’re on top of our shit when it comes to security. Additionally this would still be more doable if GitHub made it so, so you might want to push them as we don’t control their APIs. 

(It’s likely well release integrations api support next year but it doesn’t completely eliminate these concerns)

**Comment by benvinegar** [comment]
We've [reworked our Sentry's GitHub integration](https://blog.sentry.io/2018/09/12/sentry-github-integration-update) which now allows fine-grained permissions.

**Comment by stephgosling** [comment]
@benvinegar do the fine-grained permissions require the GitHub Marketplace App (i.e. the commercial offering) as I can see no way of getting at that for the self-hosted/on-prem version?

**Comment by dcramer** [comment]
@stephgosling they require configuring a GitHub app, unrelated to the marketplace though.

**Comment by benvinegar** [comment]
> I can see no way of getting at that for the self-hosted/on-prem version?

We haven't cut a release with those changes yet. They'll go out in the next open source release – _I think_.
