### ISSUE TITLE
Slack Integration: doesn't work if removed and installed again

### ISSUE THREAD

**Issue by Aarbel** [getsentry/sentry#11882]
![image](https://user-images.githubusercontent.com/25119847/52236006-f2e0d500-28c5-11e9-84c5-cbec2fccda55.png)

Slack integration doesn't appear "installed" if we try to install it again after removing it

**Comment by EvanPurkhiser** [comment]
Can you provide more detail as to symptoms? Does it make it all the way through the install process?

**Comment by EvanPurkhiser** [comment]
Duplicate of #11662
