### ISSUE TITLE
Add usercreate to api

### ISSUE THREAD

**Issue by bbkgh** [getsentry/sentry#11902]
## Summary
Add an api for user creation by admin like createuser command.

**Comment by max-wittig** [comment]
It would be nice, if this would also allow to move and manage members via API.

**Comment by Venus713** [comment]
Hi @markstory 
By I reviewing this issue, I really think the API is unnecessary as you said, so this issue should be closed soon.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
