### ISSUE TITLE
Flot charts on landing page are barely visible

### ISSUE THREAD

**Issue by timlinux** [getsentry/sentry#1192]
On the landing page, the charts associated with each project are barely visible (running 6.4.4 here). Could you give them a bot more or a robust colour. Or even nicer, make the chart colour configurable in the project settings? See screenshot below for example:

![selection_001](https://cloud.githubusercontent.com/assets/178003/3115844/28eacea6-e70f-11e3-95d2-eda758cbfdf9.png)

**Comment by mattrobenolt** [comment]
This doesn't even exist anymore. Closing.
