### ISSUE TITLE
Global integrations

### ISSUE THREAD

**Issue by dgaussin** [getsentry/sentry#11959]
Hi,

Is it possible to use gloal integration with Sentry onpremise 9.0.

In **Organization Settings > Integrations**, we don't have the link "Integrations". On your sentry saas, I can see the link.

Thanks

**Comment by markstory** [comment]
@dgaussin The sentry 9.0 tag was created well before the global integrations are complete. You would have to update to `master` or wait for the next tagged release to get global integrations in an on-premise setup.
