### ISSUE TITLE
Inconsistent language/framework tiles while creating a new project

### ISSUE THREAD

**Issue by pgrzesik** [getsentry/sentry#12012]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Hello, I was creating a new project in Sentry, while I noticed a bit of inconsistency when it comes to suggested languages/frameworks. For example, aiohttp is not listed under the `Server` tab, it also does not have the tile with Python logo.

## Steps to Reproduce

1. Log into sentry.io account
2. Try to create new project (https://sentry.io/organizations/org-name/projects/new/)
3. Check available language/frameworks

### What you expected to happen

I would expect aiohttp (as well as AWS Lambda because it seems it's AWS Lambda Python integration) to be listed under `Server` and have tiles with Python logo.

### Possible Solution

Adjustments in `src/sentry/static/sentry/app/views/onboarding` - I actually took a look around the codebase, but on current master I didn't found any mention of aiohttp. If someone could point me in the right direction, I would love to contribute. 

Regards,
Piotr

**Comment by billyvg** [comment]
@pgrzesik Hey Piotr, you can add a platform here: https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/app/data/platformCategories.jsx#L36

The icon is handled in a different repo iirc: https://github.com/getsentry/platformicons/tree/master/svg

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
