### ISSUE TITLE
Feature request: Auto-assign to issue owner

### ISSUE THREAD

**Issue by d-luk** [getsentry/sentry#12047]
We have set up ownership rules in our project, but we still need to manually assign every issue to that person. 

Fortunately, there is now a "Suggested Assignees" section on the issue page where you can do this with only one click, but we still need to go through all issues to assign that person. It would be great if this could be done automatically.

I understand that this is not possible if there are multiple suggested assignees, but if there is only one, then I don't see any problems.

I would suggest a new setting on the "Issue Owners" page called something like "**Auto-assign to owner**". If this setting is enabled, then the issue is automatically assigned to the issue owner if there is one.

**Comment by agis** [comment]
Dup of #10908.

**Comment by d-luk** [comment]
@agis You're right. I'll close this one.
