### ISSUE TITLE
Be able to configure what is shown as the name for each event

### ISSUE THREAD

**Issue by rasmusbergpalm** [getsentry/sentry#1206]
In java the location of the logged error is not always very useful as sometimes you have lot's of different exceptions being caught and logged in the same place, e.g. all uncaught exceptions might be caught, logged and converted into an error 500 on a public API, etc.

I have different ideas about what might be useful, e.g. the exception type, the message etc. but I think it'd be best if it was configurable in sentry what was displayed

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
