### ISSUE TITLE
Time on activity graph for groups 

### ISSUE THREAD

**Issue by BlueMoebius** [getsentry/sentry#1208]
Hello,

I have a minor issue with time time on group activity graph. The event was sent at 10:06 AM local time. But activity graph  displays it as sent at 9 AM or between 9 and 10. (screenshot)

I have TIME_ZONE set to CET (My local time), and time zone in  Account settings to GMT +2 (Ljubljana).

![sentry_cet](https://cloud.githubusercontent.com/assets/4996003/3440536/83241d2a-00f8-11e4-9858-a169935ef759.png)

**Comment by mattrobenolt** [comment]
This has likely 100% changed in the past 2 years.
