### ISSUE TITLE
Chrome throws a net::ERR_INCOMPLETE_CHUNKED_ENCODING when loading static assets in Sentry web

### ISSUE THREAD

**Issue by c4urself** [getsentry/sentry#1209]
When following the guide to setup [Nginx as a reverse proxy](http://sentry.readthedocs.org/en/latest/quickstart/nginx.html) Sentry fails to load from Nginx (port 80) while still working on Gunicorn (port 9000) when using Chrome.

Adding the following setting to Nginx solves the problem:

`proxy_buffering: off;`

**Comment by mattrobenolt** [comment]
Unlikely this is a problem with Sentry itself.
