### ISSUE TITLE
Inbound Filter for all versions of IE

### ISSUE THREAD

**Issue by justincy** [getsentry/sentry#12178]
## Summary

Add an inbound filter for all versions of IE. Currently we have options for IE 10 and below, but it'd be great to include IE 11.

## Motivation

[Microsoft is discouraging use of IE](https://www.theverge.com/2019/2/8/18216767/microsoft-internet-explorer-warning-compatibility-solution). Many orgs don't support IE. It'd be nice to have the option to ignore all versions of IE, including 11.

## Additional Context

It would look a lot like this PR: https://github.com/getsentry/sentry/pull/4858

**Comment by MikeElghali** [comment]
Hi,

Any news about this issue?

Regards.

**Comment by markstory** [comment]
Not at this time.

**Comment by MikeElghali** [comment]
Thanks for your answer. I added a logic in beforeSend function to only send errors if the current browser is supported by our app. It did the trick.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by spaceemotion** [comment]
We're doing the switch from IE11 to Edge only, would love to see a toggle just as one is available for IE9. Since we use sentry with quite a lot of services, it would be rather tedious to add the exceptions on a per-project basis.

**Comment by BYK** [comment]
Eh, given that even the old Edge is on its way out, I think there's more work for us here. Thanks for the kind responses.

**Comment by BYK** [comment]
Just checked this and it exists:

![image](https://user-images.githubusercontent.com/126780/97117922-e9da0c00-1717-11eb-88b3-eda305ed5186.png)
