### ISSUE TITLE
Cross-Organization Dashboard

### ISSUE THREAD

**Issue by JanMalte** [getsentry/sentry#12176]
## Summary

A simple cross-organization dashboard, showing the most recent issues or activity

## Motivation

This would help users which are a member of multiple organization to get a quick overview of the current situation. Currently they have to switch through all organizations to view the organization dashboard.

**Comment by BYK** [comment]
We now have cross-project view and I hope this gets close enough. Cross-org is very unlikely.

**Comment by JanMalte** [comment]
As a global DevOp it would still be helpful to have a cross-org Dashboard/Overview.

**Comment by BYK** [comment]
@JanMalte noted. It just doesn't seem likely that we'll look into this or something similar any time soon.
