### ISSUE TITLE
Team drop-down overlaps with footer logo in "Add Project" pagee

### ISSUE THREAD

**Issue by peterbe** [getsentry/sentry#12194]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [x] Other [briefly describe your environment]

Self-hosted by Mozilla version 9.0.0.

## Description

Click thee "Add new... Project" drop-down in the upper right-hand corner. 
On the form there's a "Give your project a name" and a "Team:" choice. The Team drop-down overlaps thee footer logo. 

<img width="1294" alt="screen shot 2019-02-25 at 3 27 14 pm" src="https://user-images.githubusercontent.com/26739/53366751-559c1e00-3912-11e9-97c4-1c35b2a0791d.png">

## Steps to Reproduce

See Description above. 

### What you expected to happen

More vertical margin underneath.

**Comment by markstory** [comment]
Thanks for reporting this. It was fixed in #10058
