### ISSUE TITLE
Unable to create GitLab integration

### ISSUE THREAD

**Issue by enyo** [getsentry/sentry#12273]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

When I try to link my project, everything works until the last step where I get:

> The requested GitLab group could not be found.

<img width="616" alt="image" src="https://user-images.githubusercontent.com/133277/53725415-40704380-3e6c-11e9-970b-214149c37b5a.png">

The link to my GitLab instance worked fine, and I'm 100% certain that I entered the right `group/subgroup` combination (as in https://gitlab.com/group/subgroup)

(The repository I'm linking is private, but since I'm creating an Application API access specifically for it, I don't see this being the problem)

## Steps to Reproduce

Follow the steps to link a GitLab project.

**Comment by enyo** [comment]
FYI: I have tried other repositories as well (public ones) and they all failed with the same error message.

I can see the sentry client in my `Applications` settings on GitLab:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/133277/53726481-5121b900-3e6e-11e9-97d2-8d7b8278a676.png">

**Comment by markstory** [comment]
Are you putting the repository path into the group path input? That field is for putting the group or subgroup path that contains a your repositories.

Have you made sure that the user completing the oauth connection has access to the group you are trying to connect to?

**Comment by enyo** [comment]
Ugh.. yes. Spot on. Sorry for that!
