### ISSUE TITLE
OpenID auth request contains an unregistered domain

### ISSUE THREAD

**Issue by npotier** [getsentry/sentry#1228]
Hi,

we use google apps in our company to manage SSO on the tools we use (Gitlab, Redmine). We woul like to to the same for sentry.

We have followed the instructions given in the documentation, but when we try to connect using google oauth the following error occured:
``` 
400. That’s an error.
OpenID auth request contains an unregistered domain: http://sentry.acseo-conseil.fr/
``` 
I've googled this error and it seems to indicate that google doesn't support OpenID anymore.

Thanks for your help.

**Comment by davewongillies** [comment]
@mirath you add those options to your `sentry.conf.py`. Mine's got:
```
AUTHENTICATION_BACKENDS = ( 'social_auth.backends.google.GoogleOAuth2Backend', 'sentry.utils.auth.EmailAuthBackend',)
AUTH_PROVIDERS = { 'google-oauth2': ('GOOGLE_OAUTH2_CLIENT_ID', 'GOOGLE_OAUTH2_CLIENT_SECRET'), }
```

**Comment by dcramer** [comment]
Closing this out as 7.5.0 no longer includes Google Auth

**Comment by stanislav-markus** [comment]
@dcramer will Google Auth be added in ver. 8?

**Comment by dcramer** [comment]
@stanislav-markus its already supported via SSO packages

https://github.com/getsentry/sentry-auth-google

**Comment by stanislav-markus** [comment]
Thank you! 
But I still have a problem, after I did all steps in https://github.com/getsentry/sentry-auth-google I haven't found any change in http://sentry.example.com/auth/login/ page. What could I miss?

**Comment by dcramer** [comment]
@stanislav-markus its not fully supported until the 8.0 release (which you can install from source today but isnt tagged)
