### ISSUE TITLE
Support using nginx to proxy to both application and sentry: example.com/sentry

### ISSUE THREAD

**Issue by zephyrweb** [getsentry/sentry#1230]
It should be possible to do something like this (see https://gist.github.com/j4mie/1778918) without too much effort.

We have a reliable nginx reverse-proxy and we'd like to use one domain and SSL cert for both the application and sentry.

**Comment by mattrobenolt** [comment]
Unfortunately, we don't support this method, and it's unlikely that we will in the near future.
