### ISSUE TITLE
VSTS Integration: 

### ISSUE THREAD

**Issue by dubahu** [getsentry/sentry#12324]
Hi, 
When trying to enable this integration, I get the error below, even though I am logging in to Azure DevOps as the account owner.

Azure DevOps Configuration
No accounts found. Please check that you are an account owner.

**Comment by GuAndrei** [comment]
@dubahu did you find the solution? I got the same error :(

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by dubahu** [comment]
> @dubahu did you find the solution? I got the same error :(

The new integration for Azure DevOps doesn't seem to have this issue.  So technically never got a resolution I guess, but the new version worked. 🤷‍♂️
