### ISSUE TITLE
Automatically tag spiders (bots)

### ISSUE THREAD

**Issue by nidico** [getsentry/sentry#1232]
Automatic tagging of bots based on user agent would be a great addition.

Of course that can be done manually on the client's side, but I think this would be useful as a core feature on the server side.

I just had a look on how this would be implemented, unfortunately spider detection seems to have been removed in the currently used user-agent detection library (see tobie/ua-parser#420).

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
