### ISSUE TITLE
Feature Request: Add basic authentication fields to Replay Request

### ISSUE THREAD

**Issue by zephyrweb** [getsentry/sentry#1233]
When replaying the request, I always get a 401 or 302 because that request doesn't have any credential headers in it. I suppose it might be possible to capture that info, but I'd rather not impersonate whatever user triggered the original error. Putting in test account credentials and just using basic auth would be ideal.

**Comment by tkaemming** [comment]
(We removed this feature, so this is no longer applicable.)

**Comment by asfaltboy** [comment]
How come "replay request" was removed? It was actually very convenient for us in some scenarios.

**Comment by dcramer** [comment]
@asfaltboy it poses too many security issues. You can simply use the curl command, which is far more stable and eliminates all of those issues.
