### ISSUE TITLE
Google Pubsub push messages mis-identified as crawler

### ISSUE THREAD

**Issue by daaain** [getsentry/sentry#12339]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

We get the Sentry API error `Sentry responded with an API error: APIError(Event dropped due to filter: web-crawlers)` when there's an exception in a [Google Pubsub push](https://cloud.google.com/pubsub/docs/push) handler.

Apparently the user agent is `APIs-Google`.

## Steps to Reproduce

1. Set up a Google Pubsub push HTTP event handler
2. Have an exception in the message handler code
3. Not get report in Sentry

### What you expected to happen

`APIs-Google` isn't identified as a web crawler.

### Possible Solution

Improve the regex? 😸

**Comment by daaain** [comment]
Ah great, this user agent is actually properly documented by Google, so it's safe to exclude: https://support.google.com/webmasters/answer/7426684?hl=en

**Comment by ShanTulshi** [comment]
Can I get this one?

**Comment by markstory** [comment]
@ShanTulshi sure! Ping me in the pull request.
