### ISSUE TITLE
Broken 'Getting Started' bar in sidebar

### ISSUE THREAD

**Issue by dpedu** [getsentry/sentry#12346]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [✅] Other - installed via Pip, running directly on a CentOS machine. Recently upgraded from 8.19.0 to 9.0.0

## Description

When I visit `/manage/` via a link from another page, everything is fine.

If I open a new browser window and navigate directly to the `/manage/` page (or if I refresh while already on `/manage/`), There's a greyish bar shown at the bottom of the sidebar. Hovering over it reveals the text "Getting started with Sentry: 0/7 tasks completed". If I click it, I see an error screen stating `There was an error loading a component.` and the following JS error is logged in the browser console:

```

e.(anonymous function) @ console.js:35
St @ react-dom.production.min.js:151
commitErrorLogging @ react-dom.production.min.js:160
A @ react-dom.production.min.js:185
y @ react-dom.production.min.js:182
g @ react-dom.production.min.js:181
m @ react-dom.production.min.js:181
interactiveUpdates @ react-dom.production.min.js:188
je @ react-dom.production.min.js:84
r @ raven.js:374
console.js:35 TypeError: Cannot read property 'onboardingTasks' of undefined
    at todos.jsx:152
    at Array.map (<anonymous>)
    at Object.componentWillMount (todos.jsx:151)
    at Object.componentWillMount (factory.js:615)
    at mountClassInstance (react-dom.production.min.js:112)
    at beginWork (react-dom.production.min.js:138)
    at i (react-dom.production.min.js:176)
    at a (react-dom.production.min.js:176)
    at y (react-dom.production.min.js:182)
    at g (react-dom.production.min.js:181)
    at m (react-dom.production.min.js:181)
    at interactiveUpdates (react-dom.production.min.js:188)
    at je (react-dom.production.min.js:84)
    at HTMLDocument.r (raven.js:374)
```

## Steps to Reproduce

1. Browse to `/manage/`
2. Refresh the page
3. Click the getting started bar

### What you expected to happen

The bar should not be shown as this Sentry instance has been in use for some time. Or, clicking the bar should show me some task to complete.

### Possible Solution

See expected section.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
