### ISSUE TITLE
can I deploy the report api alone without the web system

### ISSUE THREAD

**Issue by qbright** [getsentry/sentry#12374]
can I deploy the report api alone without the web system , because i want to do same access that the web system only can be visit in the company intranet and the report api  can by use anywhere

**Comment by markstory** [comment]
Yes, you can create [deploys/releases via the API directly](https://docs.sentry.io/api/releases/). We recommend the use of [sentry-cli](https://docs.sentry.io/cli/installation/) as it is often simpler to operate from shell scripts over API requests.

**Comment by markstory** [comment]
My mistake, I misread your question. No, you cannot deploy the report APIs without the rest of the API application.

**Comment by mattrobenolt** [comment]
In theory, you could just easily only expose the store API through your front end reverse proxy. And don’t let anything else be exposed.

**Comment by caseyduquettesc** [comment]
@qbright We are using that architecture now, with an external endpoint that's open and going to nginx and then dedicated sentry web instances. The filtering is done at the nginx level, as pointed out by @mattrobenolt. Internally behind a corporate SSO proxy, we have another set of sentry web servers that are not filtered and distinct from the externally facing ones. Here is the nginx configuration we use for our external reverse proxy, note how we do url whitelisting.

```
upstream target_service {
  server sentry-web-external-0;
}

server {
  server_name _;
  listen 80;

  # this might cause problems with ravenJS. we might need to set this to 0
  # which could cause problems with GCE LB instead 
  # https://cloud.google.com/compute/docs/load-balancing/http/
  keepalive_timeout 650;
  keepalive_requests 10000;
  
  location / {
      deny all;
  }

  location ~ ^/nginx-health/$ {
      access_log off;
      return 200 "OK\n";
  }

  if ($http_x_forwarded_proto = "http") { 
    return 301 https://$host$request_uri; 
  } 

  location ~ ^/api/[0-9]+/store/$ {
      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP 0.0.0.0;
      proxy_set_header        X-Forwarded-For 0.0.0.0;
      proxy_set_header        X-Forwarded-Proto $scheme;
      proxy_pass http://target_service;
      proxy_read_timeout  90;
  }

  location ~ ^/api/embed/error-page/$ {
      proxy_set_header        Host $host;
      proxy_set_header        X-Real-IP 0.0.0.0;
      proxy_set_header        X-Forwarded-For 0.0.0.0;
      proxy_set_header        X-Forwarded-Proto $scheme;
      proxy_pass http://target_service;
      proxy_read_timeout  90;
  }
}
```

**Comment by qbright** [comment]
@caseyduquettesc thanks~ , and i have another question , how to setup the dsn for the sdk ,because the root url is difference

**Comment by caseyduquettesc** [comment]
I've found that the host in the DSN doesn't matter as long as you send the request to the right location. When we create projects and Sentry gives us a new DSN and example URL using it, I just make sure that whomever I am giving the DSN to knows to swap out the domain it shows with the actual external domain.

**Comment by qbright** [comment]
thanks~

**Comment by markstory** [comment]
Sounds like there are solutions to this that don't require changes to the code.
