### ISSUE TITLE
How can I setting sentry service log message timezone to UTC +8 ？The default log is displayed in UTC，I want to change it to UTC +8.

### ISSUE THREAD

**Issue by zhangheng1442** [getsentry/sentry#12386]
My server's timezone is UTC +8

**Comment by zhangheng1442** [comment]
My server's timezone is UTC +8

**Comment by zsc8917zsc** [comment]
User Setting -> Timezone  (UTC+0800) Asia/Shanghai

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
