### ISSUE TITLE
[Design Review] Search Flow

### ISSUE THREAD

**Issue by ckj** [getsentry/sentry#1240]
As an experiment, we're opening up our design process with the community with the goal of making Search a core aspect of Sentry 7 and a great experience from the get go.

**Contributing is simple:** If you have a moment, please look over the proposed flow below and reply with how we can make it better.

### Idle:

![search-idle](https://cloud.githubusercontent.com/assets/30713/3901025/6591e89e-229c-11e4-9090-e2586211fe06.png)

### Focus

After clicking into the input you'll be greeted with a non-functioning helper dropdown. This will be a place to reference existing search functionality and see new options as they become available.

![search-focus](https://cloud.githubusercontent.com/assets/30713/3901030/82a4226c-229c-11e4-8f90-7661a2e08857.png)

### Key

![search-tag](https://cloud.githubusercontent.com/assets/30713/3901043/be326316-229c-11e4-96f8-606f3af1523f.png)

### Value

![search-value](https://cloud.githubusercontent.com/assets/30713/3901045/c91ed61a-229c-11e4-8b7a-99139b245460.png)

### Next token

![search-next-token](https://cloud.githubusercontent.com/assets/30713/3901046/d301d088-229c-11e4-8eab-1f27b432cf1d.png)

### Notes

- We're purposefully punting on saved searches for the moment.
- We're not super into the idea of styling the tokenized items unless there is a reason we're not considering right now
- Everything else is fair game. Rip this shit apart. 

### Brief Token Specs

Tokens will be space separated (or encapsulated in quotes if the value contains a space). Several reserved tokens will exist, otherwise they will default to looking for a tag key. Non-tokens will be treated as a simple string search (currently searches the message, but in the future will be expanded), and invalid tokens will be dropped.

The following are example tokens that we have in mind:

- tag:value
- is:[resolved,unresolved,muted] (status: will also be available)
- assigned:[me|user@example.com]
- bookmarked:[me|user@example.com]

**Comment by dcramer** [comment]
List all tag keys for a project:
/api/0/:org/:project/tags/

Typeahead endpoint for a specific key:
/api/0/:org/:project/tags/:key/?query=:query

Reserved keywords (builtins which should autocomplete):

- is:[resolved,unresolved,muted]
- assigned:[me,email address]
- first-release:[version]
- release:[version]
- user:[version]

Notes:

- release/user are actually just tags (sentry:release, sentry:user) which we remap throughout various displays
- first-release typeahead would simply query the tag value endpoint for 'release'
- assigned typeahead should use the project member list (which already should be in memory)

**Comment by dcramer** [comment]
This is fully functional so going to close out this master ticket
