### ISSUE TITLE
Add prefix for RedisCache keys?

### ISSUE THREAD

**Issue by jaysoffian** [getsentry/sentry#1241]
The other uses of Redis use a prefix:

```
  RedisBuffer -> b: and l: (why doesn't _make_lock_key use b:l:?)
  RedisQuota -> quota:
  RedisRateLimiter -> rl:
  RedisTSDB -> ts:
```

Should `RedisCache` use a prefix of `c:` or `cache:` to prevent accidental collisions?

Aside, is `RedisCappedPool` used for anything? It doesn't appear so. In fact, it doesn't even pylint cleanly.

**Comment by ducu** [comment]
Should also have a general prefix for all keys, something like `sentry:b:` and so on

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this as I am not sure what was done about this. I just know this is an issue that never came up recently.
