### ISSUE TITLE
Can i capture exeption in JSR-223

### ISSUE THREAD

**Issue by kolesoffac** [getsentry/sentry#12450]
I have [script of ComundaBPM](https://docs.camunda.org/manual/7.7/user-guide/process-engine/scripting/) on javascript(JSR-223). 

Can i capture event from Comunda to Sentry?

Thanks

**Comment by BYK** [comment]
Hi @kolesoffac, if it supports JavaScript properly, you should be able to use our [JavaScript SDK](https://github.com/getsentry/sentry-javascript) to catch and log errors. If not you can always manually report issues using the API or [using `sentry-cli`](https://docs.sentry.io/product/cli/send-event/).
