### ISSUE TITLE
TypeError: this.setState is not a function on Queue Overview page

### ISSUE THREAD

**Issue by xiangweilee** [getsentry/sentry#12467]
![Screenshot 2019-03-20 at 9 21 30 AM](https://user-images.githubusercontent.com/12265088/54652394-b7a30a00-4af1-11e9-9f3f-186dcd65bd4c.png)

![Screenshot 2019-03-20 at 9 16 10 AM](https://user-images.githubusercontent.com/12265088/54652414-c2f63580-4af1-11e9-928a-0f67a51fe185.png)

![Screenshot 2019-03-20 at 9 16 16 AM](https://user-images.githubusercontent.com/12265088/54652417-c7225300-4af1-11e9-8028-78811163ef2d.png)

**Comment by markstory** [comment]
Fixed in #9152
