### ISSUE TITLE
Project stats are inconsistent

### ISSUE THREAD

**Issue by tino** [getsentry/sentry#12513]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 8.22.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I am trying to read out the stats per project in order to put them into prometheus, as there currently is no prometheus metrics backend. The [Retrieve Event Counts for a Project](https://docs.sentry.io/api/projects/get-project-stats/) endpoint seems the way to go.

However, when I read out that endpoint every ten seconds, the values aren't consistent, see these three consequitive readings:
```python
[('1553429235',
  [(1553429230.0, 2),
   (1553429240.0, 4),
   (1553429250.0, 0),
   (1553429260.0, 0),
   (1553429270.0, 0),
   (1553429280.0, 0),
   (1553429290.0, 0),
   (1553429300.0, 20)]),
 ('1553429245',
  [(1553429240.0, 4),
   (1553429250.0, 0),
   (1553429260.0, 0),
   (1553429270.0, 0),
   (1553429280.0, 0),
   (1553429290.0, 0),
   (1553429300.0, 27),
   (1553429310.0, 0)]),
 ('1553429255',
  [(1553429250.0, 0),
   (1553429260.0, 0),
   (1553429270.0, 0),
   (1553429280.0, 0),
   (1553429290.0, 0),
   (1553429300.0, 27),
   (1553429310.0, 0),
   (1553429320.0, 0)])]
```

The value at `1553429300.0` is first 20, and then later updated to 27. I've seen this jump also happen in the second to last returned value (so jumping up more after becoming 27), but that was in the browser on manual refresh so wasn't able to capture it correctly.

Another run (produced with code below), scroll to the right:
```python
1553432568 : [[1553432570.0, 0], [1553432580.0, 0], [1553432590.0, 0], [1553432600.0, 0], [1553432610.0, 0], [1553432620.0, 0], [1553432630.0, 0], [1553432640.0, 0], [1553432650.0, 0], [1553432660.0, 0], [1553432670.0, 0], [1553432680.0, 0], [1553432690.0, 0]]
1553432578 : [[1553432580.0, 0], [1553432590.0, 0], [1553432600.0, 0], [1553432610.0, 0], [1553432620.0, 0], [1553432630.0, 0], [1553432640.0, 0], [1553432650.0, 0], [1553432660.0, 0], [1553432670.0, 0], [1553432680.0, 0], [1553432690.0, 5], [1553432700.0, 1]]
1553432588 : [[1553432590.0, 0], [1553432600.0, 0], [1553432610.0, 0], [1553432620.0, 0], [1553432630.0, 0], [1553432640.0, 0], [1553432650.0, 0], [1553432660.0, 0], [1553432670.0, 0], [1553432680.0, 0], [1553432690.0, 5], [1553432700.0, 2], [1553432710.0, 0]]
```

This makes it very hard to pull out these stats. When can I assume these to be stable?

## Steps to Reproduce

Run:
```python
import time

import requests

ORG = "somo"
PROJ = "backend"
DOMAIN = "sentry.example.com"
URL = f"http://{DOMAIN}/api/0/projects/{ORG}/{PROJ}/stats/?resolution=10s&since="
HEADERS = {"Authorization": "Bearer XXXXXXXXX"}


while True:
    since = str(round(time.time() - 60))
    response = requests.get(URL + since, headers=HEADERS)
    print(since, ":", response.json())
    time.sleep(10)
```

### What you expected to happen

That stats given for a certain time bucket are consistent. If they completely processed yet they should not be output as they are useless to the consumer.

### Possible Solution

Delay the stats for a time period that is not completely processed, or document what can be expected.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
