### ISSUE TITLE
Incorrect user tracking

### ISSUE THREAD

**Issue by voltcode** [getsentry/sentry#12538]
## Important Details

How are you running Sentry?

* [x ] On-Premise docker [Version 9.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I sent 3 events to sentry (same error, different user data):
1) Id = "A/1", Username = "Abc"
2) Id = "A/2", Username = "Abc" 
3) Id = "A/3", Email= "email"

user parsing on sentry side did not produce expected results:

* last event's user data was not processed because email was invalid. IMHO sentry should not be responsible for validating whether e-mails are correctly formed. Malformed e-mail may be by itself a result of an error.
* user statistics for the error show 1 user, because of the previous point AND because grouping is done per Username and not by Id. This is incorrect behaviour, because an application connected to sentry can have multiple installations. In such case, one would expect that Ids are unique globally (for example prepended with installation name), but usernames don't have to be. Prepending installation name to username is not a good idea, because then, the "avatar" functionality takes first character from the prepended part.

### What you expected to happen

User Statistics should group by user id, not by username
Incorrect emails should be accepted, but in sentry web app, they should be flagged as malformed.

**Comment by untitaker** [comment]
Please check if this is still happening in master. See also https://forum.sentry.io/t/when-will-a-new-version-be-tagged-for-sentry-open-source/5622

**Comment by voltcode** [comment]
Can I do that without upgrading my own installation, for example on your own demo account? If so, how can I access such instance?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
