### ISSUE TITLE
Releases can be duplicated by hook

### ISSUE THREAD

**Issue by gsmetal** [getsentry/sentry#12555]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.0.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

If POST same version to release hook twice — it will duplicate release in project and then that versions will stop working (and all issues in them) due to error 
```
MultipleObjectsReturned: get() returned more than one Release -- it returned 2!
```

## Steps to Reproduce

1. POST version to releases webhook.
2. POST same version to releases webhook again.
3. Try to open details of that version

### What you expected to happen

Before update to 9.0 there wasn't problem with this, multiple posting to releases webhook didn't cause releases duplication and errors.

**Comment by markstory** [comment]
Which endpoint/URL do you mean when you refer to 'releases webhook'?

**Comment by gsmetal** [comment]
I mean URL given in "Releases" page of project settings in "Webhook" section, which looks like `https://DOMAIN/api/hooks/release/builtin/XX/YYYY/`

**Comment by gsmetal** [comment]
I am moving to manage releases through `sentry-cli` and problem also exists in such case (running `sentry-cli releases new VERSION` several times creating several releases with one version). 

Moreover, if I run `new` and `set-commits` consistently:
```bash
sentry-cli releases -p $SENTRY_PROJECT --log-level=DEBUG new --finalize $GIT_REV
sentry-cli releases -p $SENTRY_PROJECT --log-level=DEBUG set-commits $GIT_REV --commit "myrepo@$GIT_REV"
sentry-cli releases -p $SENTRY_PROJECT --log-level=DEBUG deploys $GIT_REV new -e $SENTRY_CURRENT_ENV
```
This creates **two** releases with same version (`$GIT_REV`) and last `deploy` command fails with 
`Object({"detail": String("Internal Error"), "errorId": String("566fcbbb515c4f2f90f75ee1f228025f")})` which is the `MultipleObjectsReturned` error from first post.

P.S. my current sentry version is `9.1.2` and sentry-cli version is `1.49.0`.

**Comment by gsmetal** [comment]
One of the parts of the problem is that I have two projects which have same releases version (`proj` and `proj-test` to separate production and other environments).  As I saw in code releases loading does not support this and loads releases only for `<organization, version>` which returns 2 and `MultipleObjectsReturned` is raised. Trying to move to one sentry-project per my project.

**Comment by gsmetal** [comment]
Oh, found #6649 which somehow explains behavior. Didn't see this in docs.

**Comment by BYK** [comment]
@gsmetal is this still an issue for you (asking based on your last comment)

**Comment by gsmetal** [comment]
Yes, it is. With one project I now don't get errors because of workaround I've made:
```bash
# prevent releases duplication as it's not handled on server
sentry-cli releases -p $SENTRY_PROJECT --log-level=DEBUG info $GIT_REV
if [ $? -ne 0 ]
then
  echo "CREATING RELEASE! $?"
  # sentry-cli releases -p $SENTRY_PROJECT --log-level=DEBUG new --finalize $GIT_REV
  sentry-cli releases -p $SENTRY_PROJECT --log-level=DEBUG set-commits $GIT_REV --commit "project@$GIT_REV" || exit 1
fi

sentry-cli releases -p $SENTRY_PROJECT --log-level=DEBUG deploys $GIT_REV new -e $SENTRY_CURRENT_ENV || exit 1
```
So, I can't run `releases new` and then `releases set-commits` and I can't run one of this method twice so I need to check release existance first.

**Comment by nodomain** [comment]
Same here in 21.1.0

**Comment by nodomain** [comment]
In my case it was due to a broken DB with missing constraints. Reinstall fixed it.
