### ISSUE TITLE
Disabling console log (error, warn, etc) in browser

### ISSUE THREAD

**Issue by rrjanbiah** [getsentry/sentry#12618]
(Since, this is of type question and feature request, posting here. Apologies)

When it comes to JavaScript, as Sentry is logging all console messages in its dashboard, is there anyway to hide those error / warn messages in browser? If not, kindly some config. 

Idea is to avoid displaying errors in browser console for end users.. as we already captured those errors through Sentry. TIA

**Comment by sultan99** [comment]
any solution?

**Comment by BYK** [comment]
I think you're looking for this: https://docs.sentry.io/enriching-error-data/breadcrumbs/?platform=browsernpm#breadcrumb-customization

@kamilogorek - is there any other way for doing this?

**Comment by sultan99** [comment]
this helped me:
```js
Sentry.init({
  . . .
  debug: false, // before it was true
})
```

**Comment by upschmidtcreek** [comment]
To add some more detail to this.  Even if you add "debug: false" to Sentry.init(), Sentry will still log events to the console.

Example on first page load:
Sentry Logger [Log]: Integration installed: InboundFilters
Sentry Logger [Log]: Integration installed: FunctionToString
Sentry Logger [Log]: Integration installed: TryCatch
Sentry Logger [Log]: Integration installed: Breadcrumbs
Sentry Logger [Log]: Global Handler attached: onerror
Sentry Logger [Log]: Global Handler attached: onunhandledrejection
Sentry Logger [Log]: Integration installed: GlobalHandlers
Sentry Logger [Log]: Integration installed: LinkedErrors
Sentry Logger [Log]: Integration installed: UserAgent

If I disable debugging in the Sentry init config, I would expect no console output from Sentry.

**Comment by kamilogorek** [comment]
@upschmidtcreek can you provide a repro for this? The log you pasted comes exactly from the debug logger, which is controlled by `debug` config in `init` call.

**Comment by kamilogorek** [comment]
Regarding OPs question, no, there's no way to do this, as we don't overwrite the default handelrs.
