### ISSUE TITLE
Questions about Docker deploying Sentry

### ISSUE THREAD

**Issue by LimeZky** [getsentry/sentry#12658]
Hello, I have some problems when I try to deploy Sentry on my server according to the official website documentation.
Run the command as follows:
> docker run --detach --name sentry-redis redis:3.2-alpine
> docker run --detach --name sentry-postgres --env POSTGRES_PASSWORD=secret --env POSTGRES_USER=sentry postgres:9.5
> docker run --detach --name sentry-smtp tianon/exim4
> docker run --detach --link sentry-redis:redis --link sentry-postgres:postgres --link sentry-smtp:smtp --env SENTRY_SECRET_KEY="MYKEY" sentry-onpremise
> docker run --detach --link sentry-redis:redis --link sentry-postgres:postgres --link sentry-smtp:smtp --name sentry-web-01 --env SENTRY_SECRET_KEY="MY KEY" --publish 9001:9000 sentry-onpremise  run web
> docker run --detach --link sentry-redis:redis --link sentry-postgres:postgres --link sentry-smtp:smtp --name sentry-worker-01 --env SENTRY_SECRET_KEY="MY KEY" sentry-onpremise run worker
> docker run --detach --link sentry-redis:redis --link sentry-postgres:postgres --link sentry-smtp:smtp --name sentry-cron --env SENTRY_SECRET_KEY="KEY" sentry-onpremise run cron

Then I visit http://MY SERVER IP:9001, which prompts: ERR_EMPTY_RESPONSE
I have already checked my firewall setting,but I can't find anything mistasks.
After I check the log, the information is as follows:

> Original exception was:
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/site-packages/raven/middleware.py", line 100, in __call__
>     iterable = self.application(environ, start_response)
>   File "/usr/local/lib/python2.7/contextlib.py", line 35, in __exit__
>     self.gen.throw(type, value, traceback)
>   File "/usr/local/lib/python2.7/site-packages/raven/middleware.py", line 27, in common_exception_handling
>     client.handle_exception(environ)
>   File "/usr/local/lib/python2.7/site-packages/raven/middleware.py", line 115, in handle_exception
>     return self.client.captureException()
>   File "/usr/local/lib/python2.7/site-packages/raven/base.py", line 814, in captureException
>     'raven.events.Exception', exc_info=exc_info, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 46, in capture
>     return super(SentryInternalClient, self).capture(*args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 297, in capture
>     result = super(DjangoClient, self).capture(event_type, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/raven/base.py", line 641, in capture
>     self.send(**data)
>   File "/usr/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 75, in send
>     key = ProjectKey.get_default(settings.SENTRY_PROJECT)
>   File "/usr/local/lib/python2.7/site-packages/sentry/models/projectkey.py", line 121, in get_default
>     )[0]
>   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
>     return list(qs)[0]
>   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 96, in __iter__
>     self._fetch_all()
>   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
>     self._result_cache = list(self.iterator())
>   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
>     for row in compiler.results_iter():
>   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
>     for rows in self.execute_sql(MULTI):
>   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
>     cursor.execute(sql, params)
>   File "/usr/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 123, in execute
>     return real_execute(self, sql, params)
>   File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/usr/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
>     return self.cursor.execute(sql, params)
>   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 80, in inner
>     raise_the_exception(self.db, e)
>   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 78, in inner
>     return func(self, *args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 22, in inner
>     return func(self, *args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 101, in inner
>     six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
>   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 94, in inner
>     return func(self, sql, *args, **kwargs)
>   File "/usr/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 47, in execute
>     return self.cursor.execute(sql, params)
> 
> django.db.utils.ProgrammingError: ProgrammingError('relation "sentry_projectkey" does not exist\nLINE 1: ...te_limit_window", "sentry_projectkey"."data" FROM "sentry_pr...\n                                                             ^\n',)
> 
> SQL: SELECT "sentry_projectkey"."id", "sentry_projectkey"."project_id", "sentry_projectkey"."label", "sentry_projectkey"."public_key", "sentry_projectkey"."secret_key", "sentry_projectkey"."roles", "sentry_projectkey"."status", "sentry_projectkey"."date_added", "sentry_projectkey"."rate_limit_count", "sentry_projectkey"."rate_limit_window", "sentry_projectkey"."data" FROM "sentry_projectkey" WHERE ("sentry_projectkey"."project_id" = %s  AND "sentry_projectkey"."status" = %s  AND "sentry_projectkey"."roles" =  ("sentry_projectkey"."roles" | 1)) LIMIT 1
> 
> MY IP - - [05/Apr/2019:05:14:17 +0000] "GET /auth/login/ HTTP/1.1" 500 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"

The above is the log of sentry-web-01.
After I have reviewed a lot of information, I still don't know how to solve this problem. Please help me, thank you very much.

**Comment by nelsonroliveira** [comment]
User this https://github.com/getsentry/onpremise the instructions are simple and work fine

**Comment by wupeng1351** [comment]
I have the same problem. How can you solve it?

**Comment by LimeZky** [comment]
I have not solved this problem now.

**Comment by wupeng1351** [comment]
ok,thank you!
  

 

 ------------------ 原始邮件 ------------------
  发件人: "LimeZky"<notifications@github.com>;
 发送时间: 2019年5月3日(星期五) 晚上8:44
 收件人: "getsentry/sentry"<sentry@noreply.github.com>;
 抄送: "金豆豆"<726451064@qq.com>; "Comment"<comment@noreply.github.com>; 
 主题: Re: [getsentry/sentry] Questions about Docker deploying Sentry(#12658)

 

 
I have not solved this problem now.

**Comment by AudriusButkevicius** [comment]
I've had this and this is essentially database migrations failing due to not enough RAM.
 I had to enable swap and give around 3GB of ram for the migrations to finish.

**Comment by LimeZky** [comment]
Ok,thanks
