### ISSUE TITLE
[9.1.0] Errors with tags / SnubaError: HTTPConnectionPool(host='localhost', port=1218)

### ISSUE THREAD

**Issue by the-glu** [getsentry/sentry#12661]
## Important Details

How are you running Sentry?

* [X] On Premise, python mode, version 9.1.0

## Description

Recently upgraded from 9.0.X to 9.1.0 and tags are not working anymore.

Stack trace:

```
SnubaError: HTTPConnectionPool(host='localhost', port=1218): Max retries exceeded with url: /query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a2f643810>: Failed to establish a new connection: [Errno 111] Connection refused',))
  File "sentry/api/base.py", line 90, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "sentry/api/base.py", line 190, in dispatch
    response = handler(request, *args, **kwargs)
  File "sentry/api/endpoints/organization_tagkey_values.py", line 34, in get
    query=request.GET.get('query'),
  File "sentry/tagstore/snuba/backend.py", line 609, in get_tag_value_paginator_for_projects
    referrer='tagstore.get_tag_value_paginator_for_projects',
  File "sentry/utils/snuba.py", line 517, in query
    **kwargs
  File "sentry/utils/snuba.py", line 477, in raw_query
    raise SnubaError(err)
```

I understand with a quick search this is probably because sentry need Snuba, but doc say it's not required yet:

> Our new search infrastructure (codenamed Snuba) will become required (we'll provide a migration path)

And there is no documentation about how to migrate / install it.

How should we fix this ? Is there a setting to disable it - a way to install snuba - should this be fixed on your side ?

Thanks a lot  and have nice day!

**Comment by markstory** [comment]
That looks like something we need to fix on our side.

**Comment by dcramer** [comment]
Is there a specific URL you're hitting this from?

**Comment by dcramer** [comment]
Looks to be from fetchOrganizationTags -- search is expecting org-wide data when its not needed which is a problem.

**Comment by dcramer** [comment]
It also looks like these methods are not implemented on legacy tagstore, so ideally we just stop querying this endpoint when Snuba isn't available. There's no reason it should be needed in the Sentry 9 UI without cross project.
