### ISSUE TITLE
[9.1.0] SAML2 not available

### ISSUE THREAD

**Issue by lunim** [getsentry/sentry#12663]
## Important Details

How are you running Sentry?

* On-Premise docker 9.1.0

## Description

I enabled the following options in my sentry.conf.py before running the 9.1 onbuild docker file:
```
SENTRY_FEATURES['organizations:sso-saml2'] = True
SENTRY_FEATURES['organizations:sso-rippling'] = True
```

I also attempted to install the getsentry/sentry-auth-saml2 plugin, but PIP failed due to the following: "Failed to build xmlsec"

I don't see the SAML options anywhere in the sentry UI, including under Org -> Auth.

**Comment by c4tz** [comment]
Could you please describe what you did to fix the problem for others who have the same one? :)

**Comment by lunim** [comment]
I resolved by installing the following packages:
`apt-get update && apt-get install -y pkg-config xmlsec1 libxmlsec1-dev`

I was then able to install the getsentry/sentry-auth-saml2 plugin and upon restarting Sentry with the saml2/rippling features turned on the SSO options were available.

**Comment by c4tz** [comment]
Thank you for sharing this! 

Unfortunately, I am able to install the plugin, but still don't see the options in the UI. But I'm going to open my own issue for this (if neccessary).
