### ISSUE TITLE
Add "official" support for PostgreSQL version 11

### ISSUE THREAD

**Issue by msva** [getsentry/sentry#12673]
## Summary

It would be nice to add "official" support for postgresql-11.

## Motivation

pgsql-11 have many useful features, added since 9.x releases, and most useful ones:
- logical replication
- many (really) performance improvements (improved parallelism, JIT, ...)

(maybe, users also interested in that, will also provide their argumentation)

**Comment by mattrobenolt** [comment]
Is there something that doesn’t work on Postgres 11? I don’t see why Sentry wouldn’t work. We obviously don’t run pg11 in production, but I think I’ve tested against pg10 before and it was just fine.

**Comment by J0WI** [comment]
The docs do explicitly use 9.5:

- https://github.com/getsentry/sentry-docs/blob/master/src/collections/_documentation/server/installation/docker/index.md#postgresql
- https://github.com/getsentry/sentry-docs/blob/master/src/collections/_documentation/server/installation/index.md#services

**Comment by mattrobenolt** [comment]
We can update the docs to say 9.6. But since we don’t run pg10 or 11 ourselves, it’s hard for us to truly recommend it since we don’t really know if there are any gotchas. I’d expect it to be fine, but we don’t have operational expertise. 

cc @BYK

**Comment by Spellchaser** [comment]
The docs tag 9.5 but they don't explicitly state 9.5 and 9.6 are the only versions officially tested. :)

My bad for assuming that it was just out of date docs, but I went ahead and tried to use 10.7 and had trouble

**Comment by mattrobenolt** [comment]
What issues did you have with 10.7? Just curious. I feel like there shouldn't be any.

**Comment by Spellchaser** [comment]
With the south migration initialization in https://github.com/getsentry/sentry/issues/14338 ;)

**Comment by mattrobenolt** [comment]
Oh, I don't think that's truly related to Postgres 10 though. Does it do that from a new database? Or was this after upgrading from like, 9.x -> 10?

**Comment by Spellchaser** [comment]
It was initializing a new postgres database with sentry. Complete fresh
install running `sentry upgrade` to init the db. I'll provide more details
in the other issue.

**Comment by mattrobenolt** [comment]
Interesting. Yeah, I wonder if South then just fundamentally is broken with some behaviors in Postgres 10. I'd have to investigate and don't really have the time since we don't run this ourselves.

But good to know.

**Comment by Sydgren** [comment]
I've been running Sentry with Postgres 11.5 at work for a few weeks now, no problems this far.

**Comment by Bessonov** [comment]
Well, what's about Postgres 12? :)

**Comment by timfeirg** [comment]
I've been running Sentry with Postgres 12 at work for a half a year now, no problems this far.

**Comment by nilroy** [comment]
@timfeirg which version of sentry you are running?

**Comment by jackkittisakthamrong** [comment]
@Tom-Burton If I may ask, I'm in the same situation as you are since AWS plan to automatically upgrade RDS for PostgreSQL 9.6 databases to 12 starting January 18, 2022, did you manage to upgrade PostgreSQL? If yes, to which version? Do you have any problem after upgrade PostgreSQL?

**Comment by gpurrenhage** [comment]
Is it really still the case that Sentry's only recommended database is EOL?  What's the official position on what a hosted-sentry user should do w/ Postgres at this point?

**Comment by Tom-Burton** [comment]
> @Tom-Burton If I may ask, I'm in the same situation as you are since AWS plan to automatically upgrade RDS for PostgreSQL 9.6 databases to 12 starting January 18, 2022, did you manage to upgrade PostgreSQL? If yes, to which version? Do you have any problem after upgrade PostgreSQL?

Sorry for the late response, was on holiday.  I did upgrade postgres to 13.3 and apart from needing to install the citext extension there have been no problems so far that I have linked to a database issue (had some others, but mostly related to trying to get the big blob of single-server docker-compose installation to translate into something scalable on the cloud)

**Comment by jackkittisakthamrong** [comment]
> > @Tom-Burton If I may ask, I'm in the same situation as you are since AWS plan to automatically upgrade RDS for PostgreSQL 9.6 databases to 12 starting January 18, 2022, did you manage to upgrade PostgreSQL? If yes, to which version? Do you have any problem after upgrade PostgreSQL?
> 
> @jackkittisakthamrong Sorry for the late response, was on holiday. I did upgrade postgres to 13.3 and apart from needing to install the citext extension there have been no problems so far that I have linked to a database issue. (had some others, but mostly related to trying to get the big blob of single-server docker-compose installation to translate into something scalable on the cloud)

@Tom-Burton no worries, thank you so much for your answer.

**Comment by chadwhitacre** [comment]
We have a thread about this in `self-hosted` as well (lolsob that it took this long to connect the dots). I'm closing this in favor of https://github.com/getsentry/self-hosted/issues/1097.

> Is it really still the case that Sentry's only recommended database is EOL?

Yes.

> What's the official position on what a hosted-sentry user should do w/ Postgres at this point?

Check the description [over there](https://github.com/getsentry/self-hosted/issues/1097) for our official position.

Thanks for weighing in everyone, and especially for the reports of success on 11 (@sydgren) and 12 (@timfeirg). 👍
