### ISSUE TITLE
Project list dropdown doesn't show active project

### ISSUE THREAD

**Issue by OliverJAsh** [getsentry/sentry#12693]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

When multiple projects have the same name prefix, it's not obvious which one is currently "active".

In our case, we have two projects:

- unsplash-web-production-client
- unsplash-web-production-server

Looking at the UI, it's impossible for me to tell which one is active (and it's not the top one).

<img width="400" src="https://user-images.githubusercontent.com/921609/55804160-ae470500-5ad3-11e9-9aff-f856995f1758.png" />

### What you expected to happen

- It should be obvious which item in the list is currently "active" (the current project).
- Perhaps (in addition) the active list item should be bumped to the top.

**Comment by lynnagara** [comment]
Users with the "multi project selection" feature turned on see something like this with a checked box next to the selected projects:

<img width="408" alt="Screen Shot 2019-05-02 at 3 01 40 pm" src="https://user-images.githubusercontent.com/1779792/57109857-7191b680-6ceb-11e9-936e-e273a4913fd4.png">

I would propose adding something similar to that purple tick for all users.
