### ISSUE TITLE
Do migration without superuser create

### ISSUE THREAD

**Issue by blodone** [getsentry/sentry#12709]
I'm implementing the docker installation over a puppet based automation.
The step where `docker run --rm -it sentry-onpremise upgrade` is being executed without a tty seems not really a good idea, perhaps you can invent another migrate / setup routine without having to ask for a user being created.

Right now i'm doing the workaround for the problem like this:

1. execute docker run with upgrade and expect return code 0 or 1 (no tty -> aborted)
2. execute docker run with upgrade and expect return code 0
3. create superuser manually

**Comment by blodone** [comment]
now... i investigated here and tried some options... --no-input is not working

also if i try to create the superuser manually it returns like this:
```
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
```

**Comment by BYK** [comment]
This is now done automatically in the install script when `CI` env variable is set to `1`. TTY detection is a bit tricky but feel free to submit a PR over at [getsentry/onpremise](https://github.com/getsentry/onpremise) if you think you want to give it a try.
