### ISSUE TITLE
Commit Logs

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1271]
By capturing commit logs (and their affected files) we can provide a number of features, beginning with:
- Associating commits with releases
- Associating authors with files (not per-line like blame)
- Associating authors with errors indirectly based on first seen notation and culprit file(s)

This would likely consist of the following:
- Commit table (individual commit)
- SourceFile (individual file)
- SourceAuthor (a user described in a commit, with an optional link to a user)
- CommitFile (mapping of commit to source file + metadata, i.e. lines_changed)
- Pulling in sentry_github into core
- Adding a github webhook endpoint
- Adding a github history importer (careful of API limit concerns)

**Comment by dcramer** [comment]
Branch is commit-logs

**Comment by MaxBittker** [comment]
good idea ;)
