### ISSUE TITLE
add unselect to select options in stream sidebar

### ISSUE THREAD

**Issue by dotconnor** [getsentry/sentry#12730]
## Summary

When using the Issue Filter Builder thing, on all of the select options, there is no way to unselect an option without leaving the builder, editing the query yourself and then returning.

![Kapture 2019-04-11 at 6 06 15](https://user-images.githubusercontent.com/14323370/55949191-0e4ac200-5c20-11e9-936e-b971f4ce117e.gif)

**Comment by BYK** [comment]
There is now a small `x` icon next to the dropdown arrow to clear the selection:

![image](https://user-images.githubusercontent.com/126780/96896542-4af2ad00-1496-11eb-85a4-60a4e15c98c3.png)

Sorry for the very late update on this!
