### ISSUE TITLE
Link to browserstack ?

### ISSUE THREAD

**Issue by fruitl00p** [getsentry/sentry#12732]
## Summary

Open the URL as reported directly in the browser as reported (if known ofcourse) thru Browserstack

## Motivation

This would ease the reproducibility and offer a easy single click debug experience (or at least starting point)

## Additional Context

I have no clue as to whether BS would support this, but this seemed like a cool feature to have :)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by fruitl00p** [comment]
I do think you could still work on this, but i fully understand that this is only a small addition and will only work if Browserstack supports this too ;) Lets leave it at this...
