### ISSUE TITLE
when i loging senttry  it appear the page  Welcome to Sentry

### ISSUE THREAD

**Issue by chenbaicheng** [getsentry/sentry#12748]
when i enter the userName  ,it redirect this page http://localhost:9000/settings/account/details/  
this page have some problem  enter the 'continue' button , will appear error 
like this : 
http://localhost:9000/api/0/internal/options/?query=is:required   this address respond 500

HTTP/1.1 500 INTERNAL SERVER ERROR
Content-Length: 75
X-XSS-Protection: 1; mode=block
Content-Language: zh-cn
X-Content-Type-Options: nosniff
Vary: Accept-Language, Cookie
Allow: GET, PUT, HEAD, OPTIONS
X-Frame-Options: deny
Content-Type: application/json; charset=utf-8
Set-Cookie: su="gv471oJs2Pbg:1hEpXR:mGXV4lyxiXAi9CWAWBbplAXsbSc"; httponly; Path=/

**Comment by chenbaicheng** [comment]
Exception(most recent call first)

AssertionError: u'mail.port' cannot be changed at runtime because it is configured on disk
  File "sentry/api/base.py", line 90, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "sentry/api/base.py", line 190, in dispatch
    response = handler(request, *args, **kwargs)
  File "sentry/api/endpoints/system_options.py", line 79, in put
    options.set(k, v)
  File "sentry/options/manager.py", line 90, in set
    ), '%r cannot be changed at runtime because it is configured on disk' % key

**Comment by 23233** [comment]
+1 me too 
you have solve?

**Comment by chenbaicheng** [comment]
@23233  not resolve。maybe can use firefox browser   sometime can entry

**Comment by markstory** [comment]
Duplicate of #12722
