### ISSUE TITLE
Allow SAML logins

### ISSUE THREAD

**Issue by tarkatronic** [getsentry/sentry#1274]
I would like to be able to provision users in our Sentry application via SAML, rather than having to go in and manually create users. I'm currently doing this, for example, with AWS. Everybody uses the same link to go to our AWS console, is automatically logged in, and is given permissions depending on group membership defined in our SAML provider (in this case, LastPass.)

**Comment by dcramer** [comment]
Closing in favor of GH-1372 which is now actively being worked on
