### ISSUE TITLE
Implement sentry on .net 4.6.2

### ISSUE THREAD

**Issue by mouaxiong** [getsentry/sentry#12741]
I'm trying to get sentry.serilog set up on a c# project that I have which is on .net framework 4.6.2.  Based on documentation, it should work with this version of the framework but when I go to run it, nothing is outputted to the sentry issues/event dashboard.

I can run it without any issues and it doesn't throw any exceptions.  However, nothing shows up.  I don't want to use the raven client if I don't have to.  Please let me know.

**Comment by mouaxiong** [comment]
I have an integration project in the solution which is pulling in the libraries.  I had to reference:
- Sentry.Serilog.1.1.2
- Serilog.2.7.1

However in order to get the sample code to allow me to use Dsn, I had to also bring in Sentry.Protocol.1.0.3.

**Comment by bruno-garcia** [comment]
@mouaxiong `Sentry.Serilog` is indeed compatible with .NET Framework 4.6.2.

With the information you provided it's a bit tricky to reproduce your error.
Could you please share a small repro of the issue?

**Comment by mouaxiong** [comment]
Hi Bruno -


We have other libraries that has a dependency on newtonsoft.  Below is the message I get in nuget package manager when I try to install sentry using the console by running:

Install-Package Sentry -Version 1.1.2


[cid:ed0cc5dd-76e9-4ddf-b525-2487955309d2]


Any thoughts around how I can get past this?


Moua Xiong
mxiong@acumium.com<mailto:mxiong@acumium.com>
608.807.1839


Acumium LLC
717 John Nolen Drive
Madison, WI 53713

________________________________

**Comment by bruno-garcia** [comment]
@mouaxiong The error message is missing. copy paste issue maybe?

**Comment by bruno-garcia** [comment]
Closing the issue as stale.
If this is still a problem please try our latest SDK.

Feel free to raise an issue on the SDK repo to get fast feedback:https://github.com/getsentry/sentry-dotnet
