### ISSUE TITLE
[9.1.0] Creating a team without selecting a tchnology redirect to a 404

### ISSUE THREAD

**Issue by the-glu** [getsentry/sentry#12750]
## Important Details

How are you running Sentry?

* [X] On-Premise pip [Version 9.1.0]

## Description

Creating a team with selecting any technology redirect to /XXX/YYY/getting-started/other/, but the page doesn't exists.

## Steps to Reproduce

Create a team without selecting any technology (C# to Ruby buttons).

**Comment by EvanPurkhiser** [comment]
I assume you mean creating a project.

Unfortunately this bug snuck in just before we cut 9.1. [A fix has already landed on master](https://github.com/getsentry/sentry/pull/12723). We will have a 9.1.1 release soon with these bug fixes.

If you wish, you can always point pip at the releases/9.1.x branch.

**Comment by markstory** [comment]
Closing as 9.1.1 has been released.
