### ISSUE TITLE
Make it possible to use messaging as a communication protocol between clients and server

### ISSUE THREAD

**Issue by yevtsy** [getsentry/sentry#12754]
## Summary

This feature allows using messaging (Kafka) as a communication protocol between server and clients (as well as HTTP which can be default one)

## Motivation

The motivation of this enhancement is to improve reliability under high load when Sentry server needs to process tons of requests simultaneously

**Comment by untitaker** [comment]
Would you expect this to be available for SaaS as well, or is this for your own installation? I would recommend looking into [relay](https://github.com/getsentry/semaphore/blob/master/docs/quickstart.md), which is essentially a http proxy that is able to buffer events. This might solve the problems you have.

**Comment by yevtsy** [comment]
Yes, I expect it to be as part of SaaS. The main idea of this feature request is the ability to use an alternative protocol to HTTP

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

As @untitaker suggested, I think we're gonna be sticking with Relay and HTTP for a while now due to its ubiquity.
