### ISSUE TITLE
Clicking "All Events"/"Only Bookmarks" should reset filters

### ISSUE THREAD

**Issue by tarkatronic** [getsentry/sentry#1276]
I've run into two cases today where I ended up with a "No events to show" screen when clicking on "Only Bookmarks". The first was because I was on the second page of issues when I clicked over, so the link was attempting to retrieve page 2 of bookmarks, which did not exist. The second was when I had previously done a search, then clicked on "Only Bookmarks", the search criteria was maintained, again producing "No events to show" as the search didn't match any of my bookmarks.

In contrast, if I am in the "Only Bookmarks" view and type in a search, it takes me back to "All Events".

In both cases where I got "No items to show", the biggest point of confusion was that there was no indicator that the results were being filtered beyond "Only Bookmarks". The only way I figured out what was going on was by looking at the query string (p=2 and q=undefined). In both cases, I had to either click back to the stream and then only "Only Bookmarks" again or manually edit the query string to get the desired view.

**Comment by dcramer** [comment]
/cc @ckj 

I'm not sure my opinion on this, but the behavior still effectively is identical in the React branch

**Comment by benvinegar** [comment]
I've verified that, if you're on the 2nd page of a search, if you click a saved search filter the cursor is reset. We've changed search so many times since this issue was opened, I think it's safe to consider it closed.
