### ISSUE TITLE
PUT api/0/internal/options/?query=is:required 500error

### ISSUE THREAD

**Issue by 23233** [getsentry/sentry#12776]
#### Runtime env 
* ubuntu 16.04 LTS 64
* 4GRAM 
* use tengxun cloud 
* Docker version 18.09.2, build 6247962
* docker-compose version 1.24.0, build 0aa5906

#### Install detail
* apt install docker,pip
* install docker-compose
* git clone https://github.com/getsentry/onpremise
* Up and Running onpremise 

#### error
* open brower ${ip}:9000 
* type root url and admin email   click continue
![image](https://user-images.githubusercontent.com/12870070/56088015-36e5ec80-5eaa-11e9-9939-5b30c28b1217.png)

* request detail
![image](https://user-images.githubusercontent.com/12870070/56088000-c3dc7600-5ea9-11e9-945a-7c4247b8b1ab.png)

![image](https://user-images.githubusercontent.com/12870070/56088001-cfc83800-5ea9-11e9-93cf-d615e2003dc3.png)

* response detail
![image](https://user-images.githubusercontent.com/12870070/56088028-862c1d00-5eaa-11e9-89c9-b01ef4edeb96.png)

* docker logs
![image](https://user-images.githubusercontent.com/12870070/56088066-677a5600-5eab-11e9-8603-371ad54b0cdb.png)

* docker detail

![image](https://user-images.githubusercontent.com/12870070/56088020-54b35180-5eaa-11e9-8e5a-0bcf16696881.png)

i how do you do , this server can be success running ? 

thank you very muck~!

**Comment by dotconnor** [comment]
Same as https://github.com/getsentry/sentry/issues/12722
