### ISSUE TITLE
Project has no traces after upgrade from 9.0 to 9.1

### ISSUE THREAD

**Issue by ekbfh** [getsentry/sentry#12795]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [x] Other [compose with image: sentry, raven 6.1.0 for python project]

## Description
I have 3 installations,
On one after upgrade from 9.0 to 9.1 with running migrations there was no more traces coming.
On other two all was normal.

I haven't found any strange logs.
curl is working and raven's except is reaching of sentry (tcpdump shows.)

**Comment by dcramer** [comment]
If you're not receiving events after an upgrade you need to check that all services are running and processing data. Otherwise there's not enough information in this ticket to surface any issues.

**Comment by ekbfh** [comment]
Hello!
i have checked that all services is up:
```
docker-compose ps
      Name                     Command               State            Ports           
-------------------------------------------------------------------------------------
sentry_cron_1       /entrypoint.sh sentry run cron   Up      9000/tcp                 
sentry_postgres_1   docker-entrypoint.sh postgres    Up      5432/tcp                 
sentry_redis_1      docker-entrypoint.sh redis ...   Up      6379/tcp                 
sentry_sentry_1     /entrypoint.sh sentry run  ...   Up      127.0.0.1:9000->9000/tcp 
sentry_worker_1     /entrypoint.sh sentry run  ...   Up      9000/tcp     
```
Also there are a records when i curl sentry's address with new and deprecated urls from DSN.

**Comment by dcramer** [comment]
I’d events are received by the ingestion endpoint (a 200 is returned) then you have an issue elsewhere in the pipeline. You’re going to have to debug this yourself as that’s the cost of running the service. It goes from web to your broker to the workers, so your best bet is looking at broker and worker logs.
