### ISSUE TITLE
Issues page changing project with selected environment problem

### ISSUE THREAD

**Issue by SeverVladMuresan** [getsentry/sentry#12800]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

I have 2 projects set up. One is Laravel and the other is Javascript. The Laravel project has 2 environments: local and staging. The JavaScript project has no environments.

## Description

Issues were not displayed for the JavaScript project.

## Steps to Reproduce

1. Go to "Issues" page
2. Select Laravel project
3. Select any environment - local/staging in my case
4. Select JavaScript project

### What you expected to happen

Since there are no environments set up for the JavaScript project, I expected to see all the issues of said project. 

### Possible Solution

After the last step, it appears as if "All Environments" is a selected environment - it has an "X" button next to it. After that button is pressed, the issues for JavaScript are being shown.

OR

After the last step, the url query string looks like this:
?environment=local&project=1234...

If I delete the "environment=local&" text from it and hit Enter, all the issues will be show.

**Comment by markstory** [comment]
In step 4 when you select the Javascript project do you add it to the project selection or replace the laravel project with javascript as the only selected project?

**Comment by SeverVladMuresan** [comment]
I replace the laravel project with javascript as the only selected project. I didn't know you could add a project to a selection in the Issues page.

**Comment by markstory** [comment]
Thanks for the additional information. You can select multiple projects in some paid plans.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
