### ISSUE TITLE
Failed to save configuration in "Welcome to Sentry"

### ISSUE THREAD

**Issue by I-Guitar** [getsentry/sentry#12811]
![](http://ww1.sinaimg.cn/large/006V3Yvrgy1g25mxnvc5dj30yi0pzqht.jpg)
When I log in to the sentry, saving the Root Url and Admian Email always fails. Please help me.
build with docker on Centos7

**Comment by docker-man** [comment]
me too

**Comment by I-Guitar** [comment]
> me too
老铁，解决了拜托分享一下哈

**Comment by bushiquanquan** [comment]
me too

**Comment by cesguerra** [comment]
Its also happening on Ubuntu Server 18.04.2 LTS

**Comment by Trick93** [comment]
you can find the solution in #12722
i edit the config.yml and set the sentry version
then wait a few hours
it skip the setup pages

**Comment by bushiquanquan** [comment]
fixed

**Comment by I-Guitar** [comment]
> fixed

how did you fixed, can you help me?

**Comment by I-Guitar** [comment]
> you can find the solution in #12722
> i edit the config.yml and set the sentry version
> then wait a few hours
> it skip the setup pages

thank you! i solved

**Comment by dcramer** [comment]
This is resolved in sentry master and will be fixed in 9.1.1 which we're hoping to get out later today.

**Comment by I-Guitar** [comment]
> This is resolved in sentry master and will be fixed in 9.1.1 which we're hoping to get out later today.

thanks

**Comment by fabiopedrosa** [comment]
@dcramer The fix was sent to master? Any commit I can look at? I'm using the latest version and still getting that.
