### ISSUE TITLE
DSN is empty

### ISSUE THREAD

**Issue by webofrxy** [getsentry/sentry#12813]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker 
* [ ] sentry version 9.1.0 - onbuild
* [ ] docker-compose 

## Description

![image](https://user-images.githubusercontent.com/23710927/56299051-db478780-6165-11e9-9ea1-3c9105781caa.png)

**Comment by markstory** [comment]
How can someone reproduce this issue?

**Comment by untitaker** [comment]
I encountered this as well. It happens when you do not specify a URL prefix during setup. Go to `sentry shell` and run this:

```
>>> from sentry import options
>>> options.set("system.url-prefix", "http://localhost:8000")
```

**Comment by kolesoffac** [comment]
I had this issue, when use db of postgres from old version of sentry.
Fix: renew(remove/create) project

**Comment by thinkocapo** [comment]
these commands from sentry shell fixed it for me. The DSN key field in a project's settings was blank. Ran this command and now its there.

**Comment by navono** [comment]
@untitaker How to run this scripts when I use Docker with onpremise?

**Comment by navono** [comment]
It's the root URL in first login settings.

**Comment by kitho-pwc** [comment]
I meet the same problem, can you show me how to fix it too? How can i run the sentry shell , or change the IP?

**Comment by navono** [comment]
@kitho-pwc  As I said, you can set the root URL in first login settings.

**Comment by dmugtasimov** [comment]
> I encountered this as well. It happens when you do not specify a URL prefix during setup. Go to `sentry shell` and run this:
> 
> ```
> >>> from sentry import options
> >>> options.set("system.url-prefix", "http://localhost:8000")
> ```

if you are using https://github.com/getsentry/onpremise you may just include following to `config.yml`:
```
system.url-prefix: https://your.url.prefix.com
```

**Comment by dmugtasimov** [comment]
Does it happen if you do not choose any of option of sending usage statistics?

**Comment by coderhs** [comment]
It has happened for me as well both in docker and self-install, is this a bug or something we missed during install?

**Comment by xhywxtt** [comment]
Thanks to @navono , changing to IP fixed the problem

**Comment by kuailezhish** [comment]
I builded Sentry with [docker-sentry](https://github.com/getsentry/docker-sentry), I also encountered DSN is empty problem. 
Here is the [issue](https://github.com/getsentry/docker-sentry/issues/169) I posted, I really wanted to know how we can solve this problem elegantly.

**Comment by bwesen** [comment]
Same problem here, setup Sentry 9.1.1 using the official Docker container. Everything seems to work but the DSN fields are empty in my project and if I click on "Generate DSN keys" and then reload the page, I get back to the setup wizard's first screen - clicking on Continue there gets me back to the Project page, and the DSN is still empty. Superbuggy...

**Comment by bwesen** [comment]
Update 2: it didn't seem to be an issue with host vs IP in the Root URL, it also worked when I swapped out https to a more standard http + port 9000 combo. Maybe the parser assumes a port specification, which I didn't have (or need) for the https case as I then had Sentry behind an SSL nginx front listening to the standard https port.

Then when I switched back the Root URL to https and no port spec, the already generated DSNs are shown correctly in the Project DSN fields, so it also seems it involves the generation of them and not the displaying.

**Comment by navono** [comment]
@bwesen hostname has also been used successfully in my private project, and the generated DSN also contains the hostname not IP. After I reinstall Sentry with Docker again. The hostname solution not work anymore.

I didn't spend much time on it, so don't know why.

**Comment by Jaspaul** [comment]
I've been trying to setup sentry onpremise (9.1.1) locally and ran into this issue as well. 

After a bit of experimentation I noticed that the initial setup screen only sends through text fields that you intentionally modify. As a result on the installation screen by default the following is sent as a PUT request from this page:

<img width="1394" alt="Screen Shot 2019-06-06 at 4 11 46 PM" src="https://user-images.githubusercontent.com/2836589/59063347-e40b2e80-8875-11e9-93f5-a462ba3c8c7c.png">

```
https://some.cool.url/api/0/internal/options/?query=is:required
PUT
{"mail.use-tls":false,"auth.allow-registration":false}
```

When this occurs the DSN is empty for me, however the `/manage/settings/` page shows the correct url, in this case `https://some.cool.url`. If you modify and save the url on the `/manage/settings/` page it persists as you'd expect and everything begins to work.

If, on the other hand, you modify the root url during the initial setup it sends through the following (note this happens even if you re-type the same url into the text field that's already there, in this case `https://some.cool.url`):

```
https://some.cool.url/api/0/internal/options/?query=is:required
PUT
{"mail.use-tls":false,"auth.allow-registration":false,"system.url-prefix":"https://some.cool.url","system.admin-email":"admin@some.cool.url"}
```

After manually configuring this url on the setup screen the DSN values appear.

**Comment by crystianwendel** [comment]
> When this occurs the DSN is empty for me, however the `/manage/settings/` page shows the correct url, in this case `https://some.cool.url`. If you modify and save the url on the `/manage/settings/` page it persists as you'd expect and everything begins to work.

This part saved me. Thank you!

**Comment by BYK** [comment]
I'll take a look at this. @Jaspaul - huge thanks for that last comment explaining many things!

**Comment by railsfactory-robin** [comment]
Sentry.init({
dsn: 'http://public key@localhost:9000/projectid',
maxBreadcrumbs: 50,
debug: true,
})
// project id can be find in settings-> projects-> client keys->configure keys

**Comment by j-gooding** [comment]
The DSN is blank if the root URL is set to:
http://localhost:9000

However works fine if set to:
http://127.0.0.1:9000

**Comment by BYK** [comment]
@j-gooding the fix is not released yet. You can still use `http://localhost:9000`, you just need to change the input value a bit first due to a bug. See attached PR which resolved this or the comment above that explains why this happens: https://github.com/getsentry/sentry/issues/12813#issuecomment-499651458

**Comment by sarathn2013** [comment]
Continuing on @dmug's comment.
If you are running sentry on docker containers. 
You can add the following to ENV_CONFIG_MAPPING section of sentry.conf.py and build the image.
`'SENTRY_URL_PREFIX': 'system.url-prefix'` 
By doing the above you should be able to pass `SENTRY_URL_PREFIX` as an environment variable during `docker run` that will fix the DSN value.

**Comment by okainov** [comment]
The issue is still present, why is this closed?

**Comment by BYK** [comment]
@okainov: https://github.com/getsentry/sentry/issues/12813#issuecomment-506687911

**Comment by fabriziosalmi** [comment]
Fix this please. Users are not all aware about default web location. (onpremise)

**Comment by tombh** [comment]
I've just done the second installation in 2 months and surprised to see this exact issue again.

As before the comment above helped me: https://github.com/getsentry/sentry/issues/12813#issuecomment-499651458

**Comment by BYK** [comment]
@tombh @Vaelor - Let's move this discussion over to the forums as this issue as its known state is definitely fixed and verified multiple times. I'd love to hear more about your experiences and setup to see if there's anything else we are missing but keeping the discussion under this issue notifies many other people and also makes is hard to trace things back in the future.

I kindly request you to creating a new topic at https://forum.sentry.io/c/on-premise with your full installation story, all the steps you have followed, and the versions of all the things, including Sentry.

Hoping to resolve the issue once and for all with all your help, thanks in advance!
