### ISSUE TITLE
sentry.utils.geo: GeoIP module not available

### ISSUE THREAD

**Issue by rifukyv** [getsentry/sentry#12829]
docker-compose run --rm web upgrade
![微信图片_20190418114236](https://user-images.githubusercontent.com/33053371/56335494-5002dc00-61cf-11e9-974e-da3af51a9a01.png)
![微信图片_20190418114622](https://user-images.githubusercontent.com/33053371/56335573-a243fd00-61cf-11e9-8471-bcfc0a94cb9b.png)

**Comment by mattrobenolt** [comment]
It’s an optional dependency that isn’t installed by default. https://github.com/getsentry/sentry/blob/master/requirements-optional.txt#L3

Feel free to install this in your own. We can look towards making it not optional in the future since it’s a pretty common one.

**Comment by rifukyv** [comment]
How are GeoIP dependencies installed?

**Comment by carlosen14** [comment]
How are the optional requirements installed? Just copying these `optional-requirement` files on the root src?
