### ISSUE TITLE
500 INTERNAL SERVER ERROR

### ISSUE THREAD

**Issue by bushiquanquan** [getsentry/sentry#12831]
![image](https://user-images.githubusercontent.com/13992586/56348195-83a62c00-61f8-11e9-9cd6-ecb87ad449f5.png)

 as shown in the image

**Comment by gamefundas** [comment]
Found any solution for this? I am getting the same error after upgrade to 9.1.0

**Comment by markstory** [comment]
@gamefundas Have you tried upgrading to 9.1.1?

**Comment by gamefundas** [comment]
Will give it a shot today. Thanks.

**Comment by bushiquanquan** [comment]
> Found any solution for this? I am getting the same error after upgrade to 9.1.0

 9.1.1 or later version is fixed
