### ISSUE TITLE
PyPi 9.1.0 packages do not have templates for debug_toolbar

### ISSUE THREAD

**Issue by danielatdattrixdotcom** [getsentry/sentry#12856]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [X] Other [Vanilla Gentoo, Sentry via pip]

## Description

Following docs to the letter, after login I get:

TemplateDoesNotExist at /sentry/
debug_toolbar/base.html

Further inspection reveals that the debug_toolbar src does not have the templates directory.

## Steps to Reproduce

1. Install Sentry via pip
2. Make sure DEBUG=True in conf
3. Create user
4. Login as user
5. See exception

**Comment by mattrobenolt** [comment]
Did we ever include them? If we did, I can try to figure out how we lost them, but I don’t think any of us consider these to intentionally be a part of a production artifact.

**Comment by danielatdattrixdotcom** [comment]
They are included in this repo ( src/debug_toolbar/templates/debug_toolbar ) and referenced in the python source itself. I did a scratch install, except for setting DEBUG=True.

**Comment by mattrobenolt** [comment]
I understand that they are in the repo. But I wasn’t sure if we bundled these missing files in previous releases since they’re not needed in a production installation of Sentry. You should never run with DEBUG = True.

**Comment by danielatdattrixdotcom** [comment]
Fair point. As you wish on this being an issue then. Thanks.

**Comment by mattrobenolt** [comment]
I’m not insisting this is an issue. I keep asking multiple times now if this is change in behavior from previous releases. If we used to bundle them in previous releases, I’ll fix. If we haven’t, then this isn’t anything new.

**Comment by danielatdattrixdotcom** [comment]
I do not know the answer to that, I was deferring to you on the matter since you responded on the issue. I have a very old install that I am updating, and it was before inclusion of this module.

**Comment by msva** [comment]
@mattrobenolt even if that files was never included in releases, and even despite of "You should never run with DEBUG=True", there are still situations where `DEBUG=True` can be useful (say, if there are some heizenbug issues in the release (like it was in 9.0, where projects failed to create), or when user tries to catch an error on fresh installation, where even users can't be created because of, say, https://github.com/getsentry/sentry/issues/9642.
So, I guess, having it even on "production" release can be useful anyway :-/

**Comment by mattrobenolt** [comment]
Yeah, that’s fine. I’m not opposed to it. It wasn’t a conscious decision to remove them and I’m not sure why they aren’t being included or what broke it. So if someone wants to figure it out and submit a PR, wed most likely accept it assuming it doesn’t break something else.

cc @BYK

**Comment by BYK** [comment]
@danielatdattrixdotcom  - can you specify the exact version such as 9.1.0 or 9.1.2 etc?

AFAIK we should have these in 9.1.2 packages.

**Comment by BYK** [comment]
This is resolved in the recent versions.
