### ISSUE TITLE
Support for Jira premise version

### ISSUE THREAD

**Issue by prakash-p** [getsentry/sentry#12868]
Would your Sentry App on the Jira Marketplace integrate with a on premise version of Jira?  If so, what are the compatible versions?  

https://marketplace.atlassian.com/apps/1219432/sentry-for-jira?hosting=cloud&tab=support

Thanks.

**Comment by markstory** [comment]
No our Jira marketplace app cannot be installed into on-premise jira. Instead you can use [jira-server integration](https://docs.sentry.io/workflow/integrations/global-integrations/jira-server/)
