### ISSUE TITLE
Allow specifying version/shortVersion when creating a release

### ISSUE THREAD

**Issue by trondhindenes** [getsentry/sentry#12862]
### Background
The way deploys are scoped to org instead of project is extremely counter-intuitive. 
There are discussions about this here:
https://github.com/getsentry/sentry/issues/6649
and here https://forum.sentry.io/t/why-are-different-project-release-versions-linked/2493/3

### Proposal
Since a release version containing a dot and a hypen (`project.name-1.0.0`) is parsed and a `shortVersion` attribute containing the likely semver of the version string is created, it is semi-possible to get around this counter-intuitiveness, but this functionality is semi-convoluted and seems to be created primarily with front-end apps in mind.

My proposal is to expose the `shortVersion` flag directly, so that it would be possible to create a release like this:
`sentry-cli releases new -p myproject --version myproject--2.0.9 --shortversion 2.0.9 --finalize`
This would require exposing the `shortVersoin` attribute in the release apis, and falling back to current functionality only if `shortVersion` isn't specified.

Side note: These things are kind of hard to figure out partly because the documentation is fairly thin on the subject. It would be good to have a clean "this is how it works, these are the limitations, and this is how to use it" section in the documentation.

**Comment by Wirone** [comment]
As much as I love Sentry, I hate approach for handling releases and deploys. After long time of usage I still can't understand what is the added value of this dotted prefixing and not binding release to the project. Can anybody explain WHY it was done this way?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
