### ISSUE TITLE
docker sentry --> project -->Client Keys Dns is empty

### ISSUE THREAD

**Issue by jimmycheng888** [getsentry/sentry#12901]
**How are you running Sentry?**
docker run sentry..

*** [ ] On Premise docker [Version xyz]**
```
[root@localhost ~]# docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:47:25 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```
**## Steps to Reproduce**
1. [First Step]
`docker run -d --name sentry-redis redis `
2. [Second Step]
`docker run -d --name sentry-postgres -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=sentry postgres `
3.[Third step]
```
[root@localhost ~]# docker run --rm sentry config generate-secret-key
(tr+y!fj0*h@qpsvm51op0&71urx6@hg%=#ruue--=c9n!5-mj
```
(The previous line gets the secret-key, then copy the key to the single quotes in the next four lines)
4.[Fourth step]
`docker run -it --rm -e SENTRY_SECRET_KEY='(tr+y!fj0*h@qpsvm51op0&71urx6@hg%=#ruue--=c9n!5-mj' --link sentry-postgres:postgres --link sentry-redis:redis sentry upgrade`
5.[Fifth step]
`docker run -d -p 9000:9000 --name my-sentry -e SENTRY_SECRET_KEY='(tr+y!fj0*h@qpsvm51op0&71urx6@hg%=#ruue--=c9n!5-mj' --link sentry-redis:redis --link sentry-postgres:postgres sentry `
6.[Sixth step]
`docker run -d --name sentry-cron -e SENTRY_SECRET_KEY='(tr+y!fj0*h@qpsvm51op0&71urx6@hg%=#ruue--=c9n!5-mj' --link sentry-postgres:postgres --link sentry-redis:redis sentry run cron `
7.[Seventh step]
`docker run -d --name sentry-worker-1 -e SENTRY_SECRET_KEY='(tr+y!fj0*h@qpsvm51op0&71urx6@hg%=#ruue--=c9n!5-mj'--link sentry-postgres:postgres --link sentry-redis:redis sentry run worker`
8.[Eighth step]
Enter the following address in the browser address input 127.0.0.1:9000 Enter, which means perfect installation
9.[Ninth step]
After logging in, select -->add new project-->java project
![image](https://user-images.githubusercontent.com/43160174/56631382-a36da200-6687-11e9-9865-550235227650.png)
Because the DNS is empty, I can't use it in the project. Which big god can help solve it, thank you.

**Comment by zsc8917zsc** [comment]
click Configure you can look public key

**Comment by jimmycheng888** [comment]
> click Configure you can look public key

Thank you, God, has succeeded.

**Comment by wupeng1351** [comment]
安装完成后，最后一步浏览器无法访问此页面

**Comment by wupeng1351** [comment]
When the installation is complete, the browser cannot access this page

**Comment by wupeng1351** [comment]
When the installation is complete, the browser cannot access this page

**Comment by railsfactory-robin** [comment]
Sentry.init({
dsn: 'http://public key@localhost:9000/projectid',
maxBreadcrumbs: 50,
debug: true,
})
// project id can be find in settings-> projects-> client keys->configure keys
