### ISSUE TITLE
Jira Integration: You must have Owner or Manager permissions in Sentry to complete setup.

### ISSUE THREAD

**Issue by marcelopaesrech** [getsentry/sentry#12942]
When I try to integrate Sentry into Jira, I get "You must have Owner or Manager permissions in Sentry to complete setup.", but my role is "Manager" and it still showing up this message making it impossible to get through the integration.

**Comment by markstory** [comment]
You might want to ensure that your browser isn't blocking 3rd party cookies. The jira setup runs in an iframe and folks using privacy extensions or adblockers have had similar issues.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
