### ISSUE TITLE
Python language not shown in bugs list

### ISSUE THREAD

**Issue by sblondon** [getsentry/sentry#12996]
## Important Details

How are you running Sentry?

Sentry server runs on Sentry On-Premise 9.1.0 (Docker file).
Test done with sentry client with sentry_sdk-0.7.14 on python 3.6 (Debian testing).

## Description

The list view shows several informations in the last line like project name, delay since first occurence, delay since last occurence. As you can see in the screenshot:
 - 'javascript' language is shown in the second bug 
 - 'python' language is not shown in the second one:

![screenshot_sentry](https://user-images.githubusercontent.com/1708780/56974785-cf998f00-6b6f-11e9-8f79-43628f07289b.png)

I'm unsure the problem is in the server. However, in the details of the bug report, in the 'sdk' section, 'Name' is 'sentry.python' so I guess the sentry-sdk library sent enough data for the server.

The python bug has been generated by:

```
In [3]: import sentry_sdk


In [4]: sentry_sdk.init(settings.SENTRY_CONF["dsn"])
Out[4]: <sentry_sdk.hub._InitGuard at 0x7fbac14a26a0>


In [5]: try:
   ...:     raise Exception("test sentry-sdk")
   ...: except Exception as e:
   ...:     sentry_sdk.capture_exception(e)

```

### What you expected to happen

It would be nice to show it.

**Comment by untitaker** [comment]
This is because the old SDK used to send a logger name of Python. You can restore old behavior with:

```python
def before_send(event, hint):
    event.setdefault('logger', 'python')
    return event

init(before_send=before_send)
```

IMO `logger` was never supposed to be sent like that. We're currently discussing whether we want to show `platform` as fallback in the UI

**Comment by sblondon** [comment]
Thanks! It works if the DSN string is added as first parameter:

```
sentry_sdk.init(dsn, before_send=before_send)
```

I'm surprised you define `sentry_sdk` library as 'the old SDK' because it replaces [deprecated](https://docs.sentry.io/clients/python/) `Raven` library. Will a new library be released?

**Comment by untitaker** [comment]
I was talking about Raven when I said "old sdk".

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
