### ISSUE TITLE
Bulk resolve max 25 issues

### ISSUE THREAD

**Issue by mariansedivy** [getsentry/sentry#13008]
Hi,

we are running sentry On-Premise docker version 9.1.0. and we can't bulk resolve or merge more than 25 events.

How to reproduce
1. tick checkbox to select all issues on page
2. click on the message saying "25 issues on this page selected.Select the first 1,000 issues that match this search query."
3. click "Resolve"
4. This shows "Unable to update events. Please try again." error.

Am I missing something in configuration? Our installation is running with default settings from docker.

Thank you!

**Comment by mariansedivy** [comment]
Hi,

nobody can help? In Sentry 8.22.0 this was working fine.

**Comment by string-areeb** [comment]
It seems all bulk operations are delegated to snuba. And since it is not installed, it gives an error

I don't suppose it'll be fixed anytime soon since Sentry people are pushing Snuba and Kafka and whatnot.

**Comment by string-areeb** [comment]
And unfortunately, there is no documentation about how to migrate to Snuba and Clickhouse. So you have to figure it out pretty much yourself

**Comment by iliyaZelenko** [comment]
Has anyone been able to figure this out?

**Comment by BYK** [comment]
We now have Snuba, Kafka, and Clickhouse integrated deploys over at [getsentry/onpremise](https://github.com/getsentry/onpremise). Please try with those and let us know if this is still an issue.
