### ISSUE TITLE
sentry start error

### ISSUE THREAD

**Issue by zeayes** [getsentry/sentry#1300]
when i run sentry start, there occurs the error:
```
Running migrations for djcelery:
 - Migrating forwards to 0004_v30_changes.
 > djcelery:0001_initial
TransactionManagementError: Transaction managed block ended with pending COMMIT/ROLLBACK
```
i don't familiar with django. how can I solved it?

**Comment by dcramer** [comment]
If you're still seeing this error can you:

sentry upgrade --traceback

Otherwise I'm going to assume this is resolved or was specific to your installation.
