### ISSUE TITLE
Make `{{ default }}` group by "App Only"

### ISSUE THREAD

**Issue by agis** [getsentry/sentry#13036]
## Summary

Provide the option to make `{{ default }}` group by "App Only" (as opposed to "Full") backtraces.

## Motivation

In our Rails app, we use NewRelic's instrumentation gem (rpm). However, it's not added to all hosts since (a) we don't need it in all hosts and (b) NewRelic pricing is per-host (ie. there is a limited number of seats). This gem appears in almost all error backtraces since it instruments the most core paths of our code (controller actions, database queries, views etc.)

This means that the same class of exceptions reported might have identical "App Only" backtraces but different "Full" backtraces, depending on which host the exception occurred. This causes events with the _same underlying cause_ that use `{{ default }}` as the fingerprint (which is quite handy), to end up in _different_ groups.

Ideally, we'd like events in such cases to be grouped together. We would be able to control through the UI which backtrace `{{ default }}` would correspond to ("Full" or "App Only").

## Additional Context

This could also be solved by setting the fingerprint from the app with an edited version of the backtrace. However this is not future-proof, is error-prone and clunky, since every user would have to remember to do this before reporting the errors. In our case, we have 5-6 different reporter instances with different settings. Plus it would make `{{ default }}` useless, which otherwise could be quite handy.

To keep backwards compatibility, this feature be an opt-in setting.

**Comment by mitsuhiko** [comment]
Is this on sentry.io or on a self hosted installation? We recently did some changes to grouping that will let you opt into new grouping algorithms and to customize the grouping which is already live on sentry.io but did not make it into a stable release yet. If you are willing to do some experiments on sentry.io let me know and I unlock you the feature.

Generally we group by both in-app and all and both hashes are associated. This means that the "weaker" of the two hashes is going to group the event. So if you have frames that are in-app they *will* be already what we group by. However there is a catch and you are likely to run into that: the existing grouping algorithm under some circumstances discards all in-app frames for grouping. The new algorithm no longer does that but is not enabled by default yet.

**Comment by agis** [comment]
We're on a self-hosted installation.

Are there any estimates on when these new algorithms will make it in the open source version? From your description. From your description, I'd say we don't have to test on sentry.io - we'll just wait for a release with this feature.

**Comment by agis** [comment]
@mitsuhiko any updates on this one?

**Comment by mitsuhiko** [comment]
I don't have an update on when a new release is cut for sentry at the moment. We're changing around so much that we need to be careful with doing a release here without regressing.

**Comment by agis** [comment]
Understood. However, do you know if the new release (whenever it's out) is going to have the changes you mentioned?

**Comment by fgabolde** [comment]
I'm confused. I thought Sentry already grouped by in-app frames?

The doc [here](https://docs.sentry.io/data-management/event-grouping/) says pretty clearly:

> The first and most important part is that Sentry only groups by stack trace frames reported to be from your application.

We are running Sentry 9.1.1, and I'm seeing a lot of duplicated errors. In a specific case I grabbed the JSON for events from two such errors and ran some jq on them:

    jq -S '.exception.values[0].stacktrace.frames[] | select(.in_app == true)' event1.json > event1-inapp.json

diff reports that both files are identical. Looking at the full stack traces, some frames are indeed different (because of some Jetty magic that I don't fully understand):

```
                  {
                     "function" : "run",
                     "module" : "org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread",
                     "lineno" : 366,
                     "filename" : "ReservedThreadExecutor.java",
                     "abs_path" : "ReservedThreadExecutor.java",
                     "in_app" : false
                  },
                  {
                     "module" : "org.eclipse.jetty.util.thread.strategy.EatWhatYouKill",
                     "function" : "run",
                     "filename" : "EatWhatYouKill.java",
                     "abs_path" : "EatWhatYouKill.java",
                     "in_app" : false,
                     "lineno" : 126
                  },
                  # three more frames from this class
```

but they are clearly marked as not being in-app.

We just got done upgrading the Sentry SDK to take advantage of https://github.com/getsentry/sentry-java/issues/698, but we're not seeing any fewer duplicates.

If the documentation is wrong and the in-app frames are not the only ones being considered, what can I do to fix my grouping?

**Comment by mitsuhiko** [comment]
The legacy grouping algorithm which is what is also in 9.1.1 has some corner cases where the in app frames might not be considered. This has since been improved and should be part of the next open source release.

**Comment by fgabolde** [comment]
Alright @mitsuhiko, I am impatiently waiting for the 9.1.2 release then, and I will be sure to pester my Sentry admin to upgrade!

**Comment by agis** [comment]
By looking at the patches that went into [9.1.2](https://github.com/getsentry/sentry/compare/9.1.1...9.1.2), I assume that the grouping algorithm haven't really changed.

@fgabolde Have you maybe tried 9.1.2? If so, can you confirm my assumption?

**Comment by BYK** [comment]
I think @mitsuhiko was referring to the upcoming v10 release.

**Comment by mitsuhiko** [comment]
Sorry yes, the 9.1.2 release has the new grouping system but it lacks the new algorithms.
