### ISSUE TITLE
inconsistent javascript source in error view

### ISSUE THREAD

**Issue by sunkencity** [getsentry/sentry#1303]
Sentry 6.4.4
Raven-js: 1.1.16 (probably)
Looking at js exception from rails on sentry it gives inconsistent info on which sourcefile an exception happened in. Rails generates a new hash for each deploy so it's the same file, but different versions.
header refers to : /assets/application-277edf0025aefdb2209d643f78f0a8fc.js
while exceptions refers to: /assets/application-92b8ec05b98762b2a77fe628d95b17e7.js

Also the error column & row information in the backtrace seem to be off target sometimes. Is sentry confused about which source file was active at the time?

**Comment by mattrobenolt** [comment]
Closing since this has likely been fixed/made irrelevant/changed/noidea.
