### ISSUE TITLE
Enabling text message MFA doesn’t work as expected

### ISSUE THREAD

**Issue by j-f1** [getsentry/sentry#13052]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] SaaS (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I got a strange error when trying to enable SMS 2FA

## Steps to Reproduce

1. Go to your Security settings
2. Select the button to enable text message 2FA
3. Type in your phone number

Then, either:

* Press enter. Note that an error occurs

or:

* Click the button to send the 2FA code
* Type in the code
* Press enter. Note that an error occurs

It seems like pressing enter submits some other form that causes the whole process to fail. It’s unclear that you have to actually click the submit button for the process to work.

### What you expected to happen

Pressing enter behaves the same as clicking the buttons.

### Possible Solution

You could add a handler for the form’s `submit` action that stops it and does the request to send the text instead.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
