### ISSUE TITLE
Inconsistent S3 credentials between app and worker containers

### ISSUE THREAD

**Issue by acdha** [getsentry/sentry#13064]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.0.0]

## Description

Sentry is configured to use S3 as the storage backend:

```python
SENTRY_OPTIONS["filestore.backend"] = "s3"
SENTRY_OPTIONS["filestore.options"] = {
    "bucket_name": env("SENTRY_FILESTORE_S3_BUCKET"),
    "default_acl": "private",
}
```

Everything is running in ECS as a single FarGate task using IAM role credentials to grant access to the bucket in question.

## Steps to Reproduce

1. Upload files, which works
2. Manage files through the web UI – download, delete, etc. — which works
3. Notice that the `sentry.tasks.assemble.assemble_dif` task is failing

![image](https://user-images.githubusercontent.com/46565/57233612-fa129e80-6fec-11e9-8812-42c01c399d39.png)

The stack redaction means I can't tell whether it's using the same discovery which the rest of the app does or somehow either ignoring it. I'm setting up CloudTrail logging to get the principal ID to try to narrow that down.

**Comment by AienTech** [comment]
any news on this issue?

**Comment by acdha** [comment]
I did eventually get it working but I'd have to dig to find out exactly what it involved. If you're encountering the same issue, I'd start with using CloudTrail to see what specific request is failing.

**Comment by AienTech** [comment]
@acdha thanks, I actually did the cloudtrail first. it doesn't seems to catch anything! so I did a trail log from the docker it self and it shows me the followoing:
`NoSuchKey: An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.`

these are my configs, maybe I'm doing something wrong?
```
filestore.options:
  access_key: "..."
  secret_key: "..."
  bucket_name: "swwwan-sentry"
  region_name: "us-east-1"
  signature_version: "s3v4"
```

the `access_key` and `secret_key` are all generated within an IAM user, which only has API (programmatic) access to the bucket.

**Comment by AienTech** [comment]
found the problem. I had setup the organization before to use the filesystem. New organizations are now using the S3. Which somehow shows that I didn't correctly setup the sentry.
A fresh install of sentry (with removing all docker images and volumes) did the job

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
