### ISSUE TITLE
Environment Tags Do not Work - Snuba is missing.

### ISSUE THREAD

**Issue by laplace777** [getsentry/sentry#13060]
Hi,

When I click the environment tags, it gives internal Snuba error: When can we get this Snuba upgrade ? 

I tried it installing seperate but this time it gives schema validation error and I could not fix it.

Would you mind helping me with the Snuba configuration in config file ?

Best Regards

huseyin

**Comment by markstory** [comment]
Snuba wasn't  supposed to be part if the 9.0 releas. You should upgrade to 9.1.1 to fix this issue.

**Comment by laplace777** [comment]
I did actually and right now I am running v10.dev but the error is present. When I activate and run snuba api from command line it runs, due to the configs sentry connects to snuba but it gives schema validation error while trying to search. So now I disabled snuba but this time environment tags are not working.

**Comment by markstory** [comment]
v10.dev is going to require snuba, I would stick to 9.1.1 for the time being as snuba also requires additional infrastructure like kafka and zookeeper to operate at any reasonable scale and we don't have the tooling ready for on-premise just yet.

**Comment by chengjianhua** [comment]
@markstory @laplace777 	I upgrade to `v10.dev` headfirst and with the same issue...

How to downgrade to `9.1.1`. Whether running a server with `sentry:9.1` docker image directly can solve this?
