### ISSUE TITLE
Server replied HTTP 500 when breadcrumb contains non-ASCII characters

### ISSUE THREAD

**Issue by karoyqiu** [getsentry/sentry#13076]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

[What happened]
I'm trying the [sentrypad](https://github.com/getsentry/sentrypad) project. The original example works fine. But when I change the breadcrumb message to a string containing non-ASCII characters, the server replies HTTP 500 error. I don't think it's a bug of sentrypad, so I submit it here.

It seems about the last 100 breadcrumbs. If the last 100 breadcrumbs don't contain any non-ASCII characters, the server replis HTTP 200.

## Steps to Reproduce

1. Clone [sentrypad](https://github.com/getsentry/sentrypad).
2. Change [line 43 of example.c](https://github.com/getsentry/sentrypad/blob/master/example.c#L43) to something like `sprintf(buffer, u8"测试 %zu", i);`.
3. Compile and run the example.
4. The server  replies  HTTP 500.

### What you expected to happen
The server should reply HTTP 200.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
