### ISSUE TITLE
OperationTimedOut with Cassandra Nodestore backend

### ISSUE THREAD

**Issue by rtnpro** [getsentry/sentry#1309]
Hi,

I am trying to switch from Django Nodestore backend to Cassandra Nodestore backend. I've followed the docs for Cassandra Nodestore at https://sentry.readthedocs.org/en/latest/nodestore/index.html as it is. However, when I run the celery workers, I start getting ``OperationTimedOut`` from the cassandra backend: https://gist.github.com/rtnpro/cc7ccb958cd0432fa022.

I tried to directly use ``casscache`` client from my sentry box to ``get``, ``set`` keys on the Cassandra cluster, and it works fine.

Am I doing something wrong? Please help to resolve this issue.

**Comment by kuzmik** [comment]
Has anyone solved this yet? We are also experiencing this in our setup. We have 3 sentry nodes talking to a remote Cassandra cluster (currently 1 node in staging). Works fine from the shell, but raises the timeout exception via celery.

**Comment by dcramer** [comment]
@kuzmik good chance it doesnt work at all. We never actually tested it in a production environment (as far as I know Disqus doesn't use it).

That said, our connections should already be thread locals so I'm not sure if the previous SO post is relevant (assuming you're running on a current version of Sentry).

It might be that we need to expand our available APIs to correctly support something like this. Though more likely it's fair to consider this a bug in casscache.

**Comment by kuzmik** [comment]
That is unfortunate. One of the big draws was that Cassandra "just worked" out of the box as a nodestore.

Guess we'll poke around and see what we can fix.

**Comment by dcramer** [comment]
@kuzmik while a timeout error is kind of a terrible way to react to this, it'd probably be easy enough to try/catch

It'd also be pretty simple to do something like suggested in the SO post, though I'm not sure I'm comfortable doing that by default.

i.e.

```
def cassandra_init():
  app.nodestore.conn.shutdown()
worker_process_init.connect(cassandra_init)
beat_init.connect(cassandra_init)
```

**Comment by kuzmik** [comment]
For what it's worth I rewrote the cassandra/backend.py to not use casscahe and just use the Cassndra driver. The same behavior is exhibited. Will look into doing the shutdown stuff later today; if it works I'll submit a PR.

**Comment by dcramer** [comment]
@kuzmik kind of curious how anyone uses the cassandra stuff in production if this is a problem in Sentry's simplistic code. Seems silly that the library isnt handle reconnects for you and you have to explicitly pull the connection each time.

Gonna see if I can get anyone else to chime in here.

**Comment by kuzmik** [comment]
That'd be fantastic, I would appreciate it a lot. Spent most of the morning trying to figure this out with no luck (doesn't help that I am not technically a Python developer).

**Comment by dcramer** [comment]
The theory is this might be related to forking.

Would you mind giving this a shot? It makes the connection lazy so in theory that'd resolve the prefork issue:

https://github.com/getsentry/sentry/blob/e5807c4335e209faeb58ac82d57ba982cc67012d/src/sentry/nodestore/cassandra/backend.py

**Comment by kuzmik** [comment]
Of course! Give me a bit and I'll get back to you.

**Comment by kuzmik** [comment]
That did the trick. Let me deploy the change to the 3 hosts in staging and give it a bit more testing, but initial tests are working!

**Comment by dcramer** [comment]
Closing this out since its likely resolved (turns out we did this same thing to the Riak backend ages ago)
