### ISSUE TITLE
How to change timezone in email 

### ISSUE THREAD

**Issue by Python8023** [getsentry/sentry#13148]
I had add
SENTRY_DEFAULT_TIME_ZONE = 'Asia/Shanghai'
and
set my account timezone UTC+8
but
email May 9, 2019, 7:51:41 a.m. UTC

**Comment by Dukecz** [comment]
You cant: https://github.com/getsentry/sentry/issues/2486

**Comment by markstory** [comment]
Closing as a duplicate.

**Comment by zhangzhaorui** [comment]
Hi，Boss
Is there any solution to modify timezone in e-mails?  I've applied SENTRY_DEFAULT_TIME_ZONE = 'Asia/Shanghai' , but unfortunately it affects only web UI, not sent e-mails.  I would appreciate your help very much
