### ISSUE TITLE
Support Capacitor & Ionic 4

### ISSUE THREAD

**Issue by mrahmadt** [getsentry/sentry#13169]
Hello

Is there any plan to support Ionic 4 with Capacitor? I know cordova is supported, but I need to use Capacitor?

http://capacitor.ionicframework.com/

I searched online couldn't find anything, if I missed something please share it with me. 

Thanks

**Comment by Nodonisko** [comment]
+1

**Comment by josh-m-sharpe** [comment]
@mrahmadt - have you made any progress here?

**Comment by mrahmadt** [comment]
Unfortunately no

**Comment by BYK** [comment]
Please follow the following issues instead:

 - https://github.com/getsentry/sentry-cordova/issues/154
 - https://github.com/getsentry/sentry-cordova/issues/162

TLDR; we are not investing into Cordova at the moment but are open to PRs if you are interested.
