### ISSUE TITLE
Events are not grouped

### ISSUE THREAD

**Issue by TheDutchCoder** [getsentry/sentry#13176]
## Important Details

How are you running Sentry?

* Saas (sentry.io)

## Description

Some events get grouped like expected, however some of them keep opening new issue entries and it's not only incredibly annoying, it makes Sentry unusable as I'm spending the vast majority of my time cleaning up the list.

## Screenshot
![image](https://user-images.githubusercontent.com/1668207/57623485-da83f480-755d-11e9-9d78-148f8d780958.png)

**Comment by markstory** [comment]
Depending on how your application is setup and how you're using the sentry sdks, you should be able to [customize fingerprints](https://docs.sentry.io/data-management/rollups/?platform=javascript#custom-grouping) to achieve the grouping you want.

**Comment by mitsuhiko** [comment]
@TheDutchCoder if you are on sentry.io you can get in contact with customer support to request being opted into the new grouping configuration system as a beta tester. Going to close this issue here as it's not directly actionable without data to work with.
