### ISSUE TITLE
Show :line after filename in stacktrace

### ISSUE THREAD

**Issue by connor4312** [getsentry/sentry#1317]
Small thing: it'd be nice if the line number was shown (when available) prefixed by a colon after the filename in stacktraces. For example, `/home/app.js:123` instead of `/home/app.js`. A bit better UX - most editors such as sublime let you quickly navigate to a certain line in a certain file with that format, and it'd make doing so simply a matter of copy/paste.

**Comment by benvinegar** [comment]
We do this now both in the raw and rich views:

![image](https://user-images.githubusercontent.com/2153/46265385-daf1e280-c4da-11e8-962b-2a146b527b72.png)

```
at componentWillMount(./app/views/routeError.jsx:33:15)
```
