### ISSUE TITLE
Add a tooltip to the resolve button

### ISSUE THREAD

**Issue by rightfold** [getsentry/sentry#1318]
In the stream the bookmark button has a tooltip but the resolve button doesn't. At first this confused me about what the resolve button did.

**Comment by alexcroox** [comment]
Agreed, it was my first big confusion/hesitation with the UI, what on earth does this tick do.

**Comment by mattrobenolt** [comment]
This isn't relevant anymore. Stream view has a tooltip, and elsewhere it literally says "Resolve".
