### ISSUE TITLE
Jira Integration: Wrong Icon

### ISSUE THREAD

**Issue by nepGit** [getsentry/sentry#13235]
It's pulling an Icon from an unrelated Jira Project.  How can I change that?

**Comment by markstory** [comment]
Where are you seeing the incorrect icon?

**Comment by nepGit** [comment]
Under the Settings:
https://sentry.io/settings/nep-services/integrations/
[image: image.png]

https://sentry.io/settings/nep-services/integrations/jira/26377/
[image: image.png]

<https://www.nepservices.com/>

Jim Curran
SYSTEMS OPERATIONS DIRECTOR
p 949-270-6525 <9492706525> | c 949-365-6555 <9493656555>
www.nepservices.com <http://nepservices.com/>
<http://bit.ly/NEP_Facebook>  <http://bit.ly/NEP_Instagram>
<http://bit.ly/NEP_Twitter>  <http://bit.ly/NEP_LinkedIn>

CONFIDENTIALITY NOTICE: This communication with its contents is covered by
the Electronics Privacy Act, 18 U.S.C., sections 2510-2521, and is legally
privileged. This email may contain confidential and privileged material for
the sole use of the intended recipient(s). Any review, use, distribution,
or disclosure by others is strictly prohibited. If you are not the intended
recipient, please contact the sender by reply email and delete all copies.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
