### ISSUE TITLE
[Feature request] Provide predefined public, private key pair

### ISSUE THREAD

**Issue by jaseemabid** [getsentry/sentry#1324]
I have numerous applications using some sentry key pair and its not practical to
go update all of them. I'd like to use another sentry instance on the same fqdn,
but with old keys.

Is there a way I can force sentry to use an existing key pair rather than create
a new one per installation?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
