### ISSUE TITLE
sentry resets SOUTH_DATABASE_ADAPTERS

### ISSUE THREAD

**Issue by overquota** [getsentry/sentry#13242]
## Important Details

How are you running Sentry?
* Building own docker with latest sentry from pip

## Description
Sentry resets SOUTH_DATABASE_ADAPTERS from settings, making impossible to redefine it
After reset sentry does not fill SOUTH_DATABASE_ADAPTERS['default'] key (which is mandatory in south module) if engine is not `sentry.db.postgres` 

## Steps to Reproduce

1. Set SOUTH_DATABASE_ADAPTERS variable in settings (e.g. SOUTH_DATABASE_ADAPTERS = {'test': 1})

### What you expected to happen
While sentry starts, there must be exception from south module (if installed) about this variable
There are no exception now, cause this option resets before south module in https://github.com/getsentry/sentry/blob/master/src/sentry/runner/initializer.py#L383

### Possible Solution
Solved it here:
https://github.com/getsentry/sentry/pull/13241
(initialize SOUTH_DATABASE_ADAPTERS only if it is not already initialized in settings)

**Comment by joshuarli** [comment]
Closing; see https://github.com/getsentry/sentry/pull/13241#issuecomment-632423440.
