### ISSUE TITLE
Updated to latest Sentry, translation stopped working

### ISSUE THREAD

**Issue by OZZlE** [getsentry/sentry#13243]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description
![image](https://user-images.githubusercontent.com/893783/57852099-8dfd1b00-77e2-11e9-9005-73219ed38f5b.png)
I changed to use the latest version of Sentry.io javascript and after that js bugs started coming in untranslated.

## Steps to Reproduce
**Changed from:**

    <script src="https://cdn.ravenjs.com/3.26.4/raven.min.js" crossorigin="anonymous"</script>
    <script type="text/javascript">Raven.config('...').install();</script>

**to:**

    <script src="https://browser.sentry-cdn.com/5.2.1/bundle.min.js" crossorigin="anonymous"></script>
    <script>
    Sentry.init({ 
    dsn: '...',
    release: "javascript@" + window.DEPLOYED_BUILD
    });
    </script>

### What you expected to happen
https://blog.sentry.io/2018/02/28/internet-explorer-translations
According to this the errors should be fixed to English automatically and we haven't had any issues with it before..

### Possible Solution

Regression bug, plz fix :)

**Comment by mitsuhiko** [comment]
Sounds like we need to update the translations. This is a new string I have not seen in our translation files yet.

**Comment by BYK** [comment]
@kamilogorek should we move this issue to https://github.com/getsentry/sentry-javascript ?

**Comment by kamilogorek** [comment]
@BYK no, translations are done here, in this repo :)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
