### ISSUE TITLE
Sentry.io Web UI: Sorting doesn't count properly

### ISSUE THREAD

**Issue by OZZlE** [getsentry/sentry#13240]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

![Skärmklipp 2019-05-16 11 56 58](https://user-images.githubusercontent.com/893783/57845324-12936d80-77d2-11e9-9048-833385884a2f.png)

We're using sentry.io for tracking javascript errors.

Your sorting seems to be off '338' is a lot less than '2.5K'

## Steps to Reproduce

1. Sort by Frequency and unresolved issues

### What you expected to happen

The list should be sorted properly from the highest number of errors to lowest

### Possible Solution

Fix bug :-)

**Comment by markstory** [comment]
Of those 2.5k events how many still exist? Some of the events may have been removed due to age.

**Comment by OZZlE** [comment]
@markstory how can I know? :)

**Comment by markstory** [comment]
You would have to page through all the events :cry: Another factor into sorting is the date range conditions. Events in an issue are constrained by the date filters and then sorted based on the events that fit into the current window. However counts for an issue are a grand total that may include events outside of the currently selected time window.

**Comment by OZZlE** [comment]
@markstory so the 'Events' what time period is it related to? We have 'Auto resolve: 30 days' does it mean that it's the Events from 30 days back then? When changing at the top here:
![Skärmklipp 2019-07-10 11 05 47](https://user-images.githubusercontent.com/893783/60956247-b3019c00-a302-11e9-88cb-4c1dc81444d2.png)
or here:
![Skärmklipp 2019-07-10 11 05 52](https://user-images.githubusercontent.com/893783/60956255-ba28aa00-a302-11e9-8c6b-972193f17002.png)
The numbers on seems to change veeery slightly..

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

PS- We have released some updates to the event counts too which may help with this a bit more.
