### ISSUE TITLE
make pagination powerful!?

### ISSUE THREAD

**Issue by chensongni** [getsentry/sentry#13263]
![image](https://user-images.githubusercontent.com/18071921/57907147-0fba7a80-78af-11e9-9376-22037e3fa40e.png)
Why pagination can not be like this:
![image](https://user-images.githubusercontent.com/18071921/57907174-2c56b280-78af-11e9-94ed-7b4229f8e817.png)

**Comment by markstory** [comment]
We can't really generate the number of pages as doing so requires us to have a count of all rows. Based on how we store data getting that count is almost as expensive as reading all the rows.

Going to close this issue as we won't and can't move to numbered pages.
