### ISSUE TITLE
Secondary development, but deploy failure!

### ISSUE THREAD

**Issue by PerceiverDo** [getsentry/sentry#13285]
Hi, all.Sentry is a very nice work!!!
I will do some chart to show the crash rate ,so i need to do some secondary development.
I have config the development successful,and i can show the page by "localhost:8000".
But when i change some code about "src/sentry/static/sentry/app/components/projectHeader/index.jsx" to note some tab ,like "User Feedback",the server have webpack log and the sentry online do not show the correct page.
![image](https://user-images.githubusercontent.com/6870548/58017939-10177780-7b34-11e9-9f70-2b010cb1b51b.png)

So ,i mean, how to deploy my code when the code have changed.
Do there have some doc?

**Comment by qbright** [comment]
hi~i am start to secondary development , can you tell me how to run the program with the code and how to debug，thanks~

**Comment by BYK** [comment]
Are you talking about a local Sentry instance that you want to modify or do you want to contribute to Sentry the open-source project?
