### ISSUE TITLE
Clearly explain the effects of setting the Platform, and consequences of using a single project for multiple platforms

### ISSUE THREAD

**Issue by carljm** [getsentry/sentry#1329]
It would be nice if the answer to #1286 (or something less vague) were included in the Platform UI in some way. We just spent a while trying to work out what the Platform tag actually does, and what the consequences of reporting JS and Python errors to the same project vs different projects would be, and I don't think we're the only ones confused by it: http://stackoverflow.com/questions/26009389/what-does-the-platform-option-in-sentry-do

**Comment by asbjornu** [comment]
We had all sorts of problems related to event grouping and findability until we started separating each component of the system, for each environment (development, staging, production) it is running in, into its own project. To group related projects together, we create teams. So for a given web project called "Acme" involving a web frontend, web backend and backend API, it might look something like this:

* **Acme** (Team)
 * **Web Frontend Development** (Project [JavaScript])
 * **Web Frontend Staging** (Project [JavaScript])
 * **Web Frontend Production**  (Project [JavaScript])
 * **Web Backend Development** (Project [Python])
 * **Web Backend Staging** (Project [Python])
 * **Web Backend Production** (Project [Python])
 * **API Backend Development** (Project [Java])
 * **API Backend Staging** (Project [Java])
 * **API Backend Production** (Project [Java])

I wish this wasn't necessary, but until a single project can be used across environments (and languages), we've concluded that this is the only viable solution.
