### ISSUE TITLE
[9.1.1] Failed download files after upload

### ISSUE THREAD

**Issue by kolesoffac** [getsentry/sentry#13299]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [x] Self-hosted

## Description

I upload files(js, map) after create release. And some files failed download.
![image](https://user-images.githubusercontent.com/11459507/58076400-cde14b00-7bb2-11e9-801c-5e70a80da359.png)

![image](https://user-images.githubusercontent.com/11459507/58076416-d89be000-7bb2-11e9-9e2f-8dade082aa9d.png)

![image](https://user-images.githubusercontent.com/11459507/58076447-ee110a00-7bb2-11e9-8af9-b1522bf3509a.png)

![image](https://user-images.githubusercontent.com/11459507/58155714-1a915880-7c7d-11e9-8698-1ac9a6f824d4.png)

This file missing in folder.

Why is there meta info, but no file physicaly.

No error in command:
`sentry-cli releases files $VERSION upload-sourcemaps target/scripts`

**Comment by BYK** [comment]
It's probably because the `/tmp/sentry-files` directory is not persisted? I recommend setting a different directory for the file store and ensure it persists.

I'll be closing this issue as it is stale and seems like a configuration issue.
