### ISSUE TITLE
Need help with source maps

### ISSUE THREAD

**Issue by rohanBagchi** [getsentry/sentry#13326]
I have sentry setup with the following:

App is served from `https://app.com`

Resources are like `https://app.com/main.hash.js`

I am not serving source maps from `https://app.com`
I have directly uploaded them as artifacts to sentry

In sentry's `/releases/<release_number>/artifacts/`, I am able to see the following:
`~/main.hash.js`
`~/main.hash.js.map`

Now, my `main.hash.js` has the following `sourceMappingURL` comment:
`//# sourceMappingURL=main.hash.js.map`

Sentry shows my source map is available at `https://app.com/main.hash.js.map`

I have followed this doc `https://docs.sentry.io/platforms/javascript/sourcemaps/#verify-artifact-names-match-sourcemappingurl-value` and I understand that `~` is only a replacement for `https://app.com`

So, `~/main.hash.js.map` should resolve to `https://app.com/main.hash.js.map`

This is not happening and I continue to see the minified file.
To verify if my source map is generated correctly, I tried deploying the source maps to my sandbox and sentry started mapping minified files to the source using source maps.

It all goes for a toss when i don't deploy my source files to `https://app.com`

Please let me know if I am messing something up.

Thanks in advance :)

**Comment by dte** [comment]
Related issue: https://github.com/getsentry/sentry-webpack-plugin/issues/128

**Comment by BYK** [comment]
I think I had a similar issue when I was testing stuff earlier. The core issue was our path matching algorithm discarding "too shallow" paths when they were not exact matches. Can you try moving the source maps to a deeper directory?

I'll also try to find the related code piece and see what we can do about it.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
