### ISSUE TITLE
break-all causing dumb-looking button text

### ISSUE THREAD

**Issue by simonista** [getsentry/sentry#1333]
e349b06d5e4948ca0de060c7b0bde0c6a2377c88 caused https://www.dropbox.com/s/e2eik2y6j0km2kj/Screenshot%202014-12-13%2010.54.22.png?dl=0 to happen for the remove button on the team members page.  Need to find a way to maintain the fix for the problem explained in that commit without making the remove button text look dumb (Chrome 39 on OS X, btw)

**Comment by ckj** [comment]
Appreciate you digging up the culprit. For now this specific issue is fixed in a different way via #1357. The root cause of this issue will be addressed (read: nuked) in an upcoming release.
