### ISSUE TITLE
Inconsistent handling of culprit and stacktrace

### ISSUE THREAD

**Issue by tgr** [getsentry/sentry#1334]
See this report: http://sentry-beta.wmflabs.org/jserrors/jserrors/group/13/

Due to how wrapping works in raven.js, a fake line gets added to the stack trace (getsentry/raven-js#300) and raven.js identifies itself as the culprit because of that. Sentry hides that line from the stacktrace, but does not recalculate the culprit, so it ends up with a cuplrit which is not present in the stack trace.

**Comment by jaseemabid** [comment]
@tgr The issue is not public?

**Comment by tgr** [comment]
It's the test server and the data was not kept for long. I can probably reproduce if needed.

**Comment by mattrobenolt** [comment]
plz reopen if this is still an issue. Lots of stuff has changed around this since the ticket was opened.
