### ISSUE TITLE
Unable to create GitLab integration, identity.token-exchange-error

### ISSUE THREAD

**Issue by issaTan** [getsentry/sentry#13357]
Thanks for your great work!

## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.1]
OS: CentOS 7.6.1810
Docker Server Engine: 18.09.5
Docker Server API: 1.39
Docker Client: 18.09.5
Docker Client API: 1.39

## Description
I want to link my sentry with my gitlab, and follow the guide step by step, but I got an error `identity.token-exchange-error`at last.

## Steps to Reproduce
Configured by this manual page: https://docs.sentry.io/workflow/integrations/global-integrations/#gitlab

1. In Sentry, navigate to Organization Settings > Integrations.
2. Within Integrations, find the GitLab icon and click Install.
3. In the resulting modal, click Add Installation.
4. In the pop-up window, complete the instructions to create a Sentry app within GitLab. Once you’re finished, click Next.
5. Fill out the resulting GitLab Configuration form with the following information:
The GitLab URL is the base URL for your GitLab instance. If using gitlab.com, enter https://gitlab.com/.
Find the GitLab Group Path in your group’s GitLab page.
Find the GitLab Application ID and Secret in the Sentry app within GitLab.
Use this information to fill out the GitLab Configuration and click Submit.
6. In the resulting panel, click Authorize.
And I got the result `An error occurred while validating your request`
![sentry error](https://user-images.githubusercontent.com/7577317/58250251-8e258980-7d93-11e9-9d17-318a86166d61.png)
![sentry res](https://user-images.githubusercontent.com/7577317/58250262-9251a700-7d93-11e9-95cf-2b1354f51629.png)

I got this logs from `onpremise_web_1` container
```
2019-05-23T09:12:36.649073005Z 183.62.22.58 - - [23/May/2019:09:12:36 +0000] "POST /extensions/gitlab/setup/?completed_installation_guide HTTP/1.1" 200 7740 "http://sentry.xxx.com:9000/extensions/gitlab/setup/?completed_installation_guide" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
2019-05-23T09:12:05.493024682Z 183.62.22.58 - - [23/May/2019:09:12:05 +0000] "GET /api/0/organizations/youthmba/ HTTP/1.1" 200 5940 "http://sentry.xxx.com:9000/youthmba/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
/ -bash: 2019-05-23T09:12:05.493024682Z: command not found
2019-05-23T09:12:05.848552337Z 183.62.22.58 - - [23/May/2019:09:12:05 +0000] "GET /api/0/broadcasts/ HTTP/1.1" 200 1012 "http://sentry.xxx.com:9000/youthmba/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
-bash: 2019-05-23T09:12:05.848552337Z: command not found
2019-05-23T09:12:05.902226608Z 183.62.22.58 - - [23/May/2019:09:12:05 +0000] "GET /api/0/teams/youthmba/internal-system/members/ HTTP/1.1" 200 3352 "http://sentry.xxx.com:9000/youthmba/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
-bash: 2019-05-23T09:12:05.902226608Z: command not found
2019-05-23T09:12:05.915668816Z 183.62.22.58 - - [23/May/2019:09:12:05 +0000] "GET /api/0/teams/youthmba/sentry/members/ HTTP/1.1" 200 1752 "http://sentry.xxx.com:9000/youthmba/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
-bash: 2019-05-23T09:12:05.915668816Z: command not found
2019-05-23T09:12:06.045218633Z 183.62.22.58 - - [23/May/2019:09:12:05 +0000] "GET /api/0/organizations/youthmba/projects/?statsPeriod=24h&query=id%3A3+id%3A4+id%3A5+id%3A1 HTTP/1.1" 200 5345 "http://sentry.xxx.com:9000/youthmba/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
-bash: 2019-05-23T09:12:06.045218633Z: command not found
2019-05-23T09:12:08.982779268Z 183.62.22.58 - - [23/May/2019:09:12:08 +0000] "GET /api/0/organizations/youthmba/ HTTP/1.1" 200 5940 "http://sentry.xxx.com:9000/settings/youthmba/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
-bash: 2019-05-23T09:12:08.982779268Z: command not found
2019-05-23T09:12:10.024775809Z 183.62.22.58 - - [23/May/2019:09:12:09 +0000] "GET /api/0/organizations/youthmba/config/integrations/ HTTP/1.1" 200 13824 "http://sentry.xxx.com:9000/settings/youthmba/integrations/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
-bash: 2019-05-23T09:12:10.024775809Z: command not found
2019-05-23T09:12:10.035042120Z 183.62.22.58 - - [23/May/2019:09:12:09 +0000] "GET /api/0/organizations/youthmba/integrations/ HTTP/1.1" 200 1062 "http://sentry.xxx.com:9000/settings/youthmba/integrations/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
-bash: 2019-05-23T09:12:10.035042120Z: command not found
2019-05-23T09:12:10.043068792Z 183.62.22.58 - - [23/May/2019:09:12:09 +0000] "GET /api/0/organizations/youthmba/plugins/?plugins=vsts&plugins=github&plugins=bitbucket HTTP/1.1" 200 768 "http://sentry.xxx.com:9000/settings/youthmba/integrations/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
-bash: 2019-05-23T09:12:10.043068792Z: command not found
2019-05-23T09:12:10.143633778Z 183.62.22.58 - - [23/May/2019:09:12:10 +0000] "GET /api/0/organizations/youthmba/repos/?status=unmigratable HTTP/1.1" 200 774 "http://sentry.xxx.com:9000/settings/youthmba/integrations/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
-bash: 2019-05-23T09:12:10.143633778Z: command not found
2019-05-23T09:12:13.748033844Z 183.62.22.58 - - [23/May/2019:09:12:13 +0000] "GET /organizations/youthmba/integrations/gitlab/setup/? HTTP/1.1" 200 7925 "http://sentry.xxx.com:9000/settings/youthmba/integrations/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
-bash: 2019-05-23T09:12:13.748033844Z: command not found
2019-05-23T09:12:16.881899881Z 183.62.22.58 - - [23/May/2019:09:12:16 +0000] "GET /extensions/gitlab/setup/?completed_installation_guide HTTP/1.1" 200 10878 "http://sentry.xxx.com:9000/organizations/youthmba/integrations/gitlab/setup/?" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
-bash: 2019-05-23T09:12:16.881899881Z: command not found
2019-05-23T09:12:36.622980434Z 09:12:36 [INFO] sentry.integration.gitlab: gitlab.setup.installation-config-view.success (base_url=u'http://git.xxx.com' verify_ssl=False client_id=u'9ba1b4017f5faf45e13ddd40ba5da379b2af839f43bb8e32332537ab556a6648')
-bash: syntax error near unexpected token `('
2019-05-23T09:12:36.624762745Z 09:12:36 [INFO] sentry.identity: identity.token-exchange-error (pipeline_state=u'1b5d0ee0acfa43e68ac215cd2e79882f' error=u'invalid_state')
-bash: syntax error near unexpected token `('
2019-05-23T09:12:36.649073005Z 183.62.22.58 - - [23/May/2019:09:12:36 +0000] "POST /extensions/gitlab/setup/?completed_installation_guide HTTP/1.1" 200 7740 "http://sentry.xxx.com:9000/extensions/gitlab/setup/?completed_installation_guide" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"^C
```
It seems I got an error `invalid_state` at last?

And I check the gitlab logs, it seems anything is ok?
```
Started GET "/oauth/authorize?scope=api&state=b699867b4f4e4e3d9ed7daf2eab92d5e&redirect_uri=http%3A%2F%2Fsentry.xxx.com%3A9000%2Fextensions%2Fgitlab%2Fsetup%2F&response_type=code&client_id=9ba1b4017f5faf45e13ddd40ba5da379b2af839f43bb8e32332537ab556a6648" for 183.62.22.58 at 2019-05-23 09:51:11 +0000

Processing by Oauth::AuthorizationsController#new as HTML

Parameters: {"scope"=>"api", "state"=>"b699867b4f4e4e3d9ed7daf2eab92d5e", "redirect_uri"=>"http://sentry.xxx.com:9000/extensions/gitlab/setup/", "response_type"=>"code", "client_id"=>"9ba1b4017f5faf45e13ddd40ba5da379b2af839f43bb8e32332537ab556a6648"}

Completed 200 OK in 37ms (Views: 29.0ms | ActiveRecord: 3.5ms)

Started POST "/oauth/authorize" for 183.62.22.58 at 2019-05-23 09:51:14 +0000

Processing by Oauth::AuthorizationsController#create as HTML

Parameters: {"utf8"=>"✓", "authenticity_token"=>"/6KDlKcX5T0qD73sX9t5cWdaBGlKwgfF4DLVs1ovgL1hnjaquC0Yg/V+DK/r4/CZCBbzpcfd97U8hctxIFhekg==", "client_id"=>"9ba1b4017f5faf45e13ddd40ba5da379b2af839f43bb8e32332537ab556a6648", "redirect_uri"=>"http://sentry.xxx.com:9000/extensions/gitlab/setup/", "state"=>"b699867b4f4e4e3d9ed7daf2eab92d5e", "response_type"=>"code", "scope"=>"api"}

Redirected to http://sentry.xxx.com:9000/extensions/gitlab/setup/?code=f8b017151e0f07e0e23b1f6ab104e2375e107d55be540e498bdf5ea11316f509&state=b699867b4f4e4e3d9ed7daf2eab92d5e
```

### What you expected to happen
Connect my sentry with my gitlab success.

### Possible Solution
I create it with verify ssl false, should I need to be verify ssl?

**Comment by markstory** [comment]
You should only set verify ssl to true if both gitlab and sentry have certificates that the other system can validate. In your logs the two systems have differing `state` values which is mentioned in the error message, and is likely the cause.

**Comment by issaTan** [comment]
@markstory Thanks for your suggestion! 
I'm sorry to feedback that my gitlab and sentry have no certificates that they can validate, so that I set verify ssl to `false`.
Is any idea I can link my sentry to my gitlab without verify ssl?
From the log, It seems I got the `state=b699867b4f4e4e3d9ed7daf2eab92d5e` from my gitlab, and change to `pipeline_state=u'1b5d0ee0acfa43e68ac215cd2e79882f'` at sentry? It's a ssl cause?

**Comment by bussnet** [comment]
Exact same problem here, with and without validating SSL (both have letsencrypt certificates).
Sentry 9.1.1
Gitlab 8.12.1-ee.0

**Comment by BYK** [comment]
@bussnet are the clocks on those machines in sycn and set correctly?

**Comment by bussnet** [comment]
Exact the same time - but a different timezone - CEST vs UTC. Do you think this could be the problem?

**Comment by BYK** [comment]
@bussnet - that means their clocks are actually different by hours which would make all signing operations fail as they won't tolerate more than a few minutes AFAIK. Try setting them to the same time at the same timezone and see if it works :)

**Comment by bussnet** [comment]
@BYK but if it then works this should be a bug. Excact for this purpose there is not only a time but a timezone, so communication between machines from different timezones is working. Also @mattrobenolt from sentry said there is no need (and no option?) to change the timezone in sentry docker container: https://github.com/getsentry/docker-sentry/issues/84

**Comment by BYK** [comment]
@bussnet this is not about the timezone, it was just to make it easier for you. If you see `00:23:34` as the time for example on both machines with different time zones, that means at least one of the machines have an incorrect clock as they would have different "normalized" clocks (epoh/UTC etc.). So you need to set both machines' clocks correctly, the time zone doesn't matter.

**Comment by bussnet** [comment]
@BYK than the timezone settings would be useless and the internet would break ;)
You **NEVER** have `00:23:34` without a timezone information, if so, than the environment timezone meant (from system, defined in spec etc.).

"normalized" means calculate the "real" time, so "02:23:34" in Europe/Berlin is "02:23:34 +2000" and "normalized" "00:23:34 UTC", so the same time.

I repeat, If the plugin does not consider the timezone information, this is a Bug. Not everybody could change the timezone of both servers to get a plugin working.

**Comment by BYK** [comment]
@bussnet I think we are talking past each other. The plugin does not care about timezone information, at least that's not what I meant. What I understood from your very first message

>Exact the same time - but a different timezone - CEST vs UTC. Do you think this could be the problem?

was this: both machines _display_ the same time although they are on different time zones, hence their _real_ clock is hours apart. Now, from your latest message, I see that you already know quite well how these work so I'm guessing my understanding/assumption was incorrect. :)

Unfortunate reality is, now we are back to square one: we don't know what the issue is but we have eliminated that it is not related to machine clocks.

Maybe one of the machines (I'd check Sentry instance first) is lacking the root cert for Let's Encrypt?

**Comment by bokysan** [comment]
Exact same issue. For GitLab and Slack integration.

Could it have to do something with the fact that we're using Google SSO for login (Sentry, GitLab)?

**Comment by BenWoodford** [comment]
I too am getting an SSL error with Gitlab:

`Ensure that [REDACTED] has a valid SSL certificate`

It certainly is valid, but perhaps it doesn't like LetsEncrypt certs? How can we disable that SSL verification?

**Comment by markstory** [comment]
@BenWoodford If this is an on-premise setup you are in control of which CAs are trusted :smile:

**Comment by BenWoodford** [comment]
@markstory it is but bit of a pain not to have the Docker image not trust one of the major CAs...

**Comment by BYK** [comment]
Ah, now this makes a lot of sense @BenWoodford and sorry for the trouble! @markstory @mattrobenolt I think installing the [ca-certificates](https://packages.debian.org/stretch/ca-certificates) package in our base Docker image makes sense and can be considered safe, right?

**Comment by mattrobenolt** [comment]
Without looking, I’d be really surprised if it wasn’t already there.

**Comment by BYK** [comment]
@mattrobenolt you were right, indeed. @BenWoodford could you be running into this issue: https://community.letsencrypt.org/t/curl-does-not-trust-le-certs-on-plain-debian/54091/4 - Which means your GitLab server does not provide the intermediary CAs for Sentry server to verify them?

**Comment by BenWoodford** [comment]
@BYK Gitlab On-Prem handles its own LetsEncrypt Cert I believe?

**Comment by BYK** [comment]
>So I guess Gitlab isn’t serving intermediary certs?

@BenWoodford, I'd certainly check that and ensure that's not the case before digging more.

**Comment by BYK** [comment]
@BenWoodford were you able to determine whether the missing intermediary certs were the issue or not?

**Comment by BenWoodford** [comment]
Haven’t had a chance yet sorry! How would I check?

**Comment by BYK** [comment]
@BenWoodford have you tried to run the `openssl s_client -connect ...` command mentioned in the Let's Encrypt forum link I provided above?

**Comment by BenWoodford** [comment]
I've run it and it didn't show any errors, though I'm not entirely sure what I'm specifically looking for. Anything I should redact other than my hostname before posting the output?

**Comment by BYK** [comment]
@BenWoodford sorry this fell of my radar. Were you able to solve the issue?

**Comment by tlrh314** [comment]
I've encountered the this issue 4 times until setting up the integration magically worked the 5th time. I tired to set the integration up for a group/subgroup with `verify_ssl=True`. After 2 failures I also tried with `verify_ssl=False` just to see if that'd make a difference, but it did not. 

- Sentry runs on-premise /w Docker image `sentry:9.1.2-onbuild` (image id `a7a01fc9c574`, so the latest 9.1.2 afaik). No fancy/special configuration for the onbuild, just added 4 lines to `config.yml` (copied below, just for completeness)
  - `system.admin-email: 'my@email.com`
  - `system.url-prefix: 'https://sentry.mydomain.tld'`
  - `auth.allow-registration: false`
  - `beacon.anonymous: true`
- GitLab runs on-premise /w GitLab Omnibus CE version `13.5.1 (8ee0746f54c)`

Sentry log
```
11:35:52 [INFO] sentry.integration.gitlab: gitlab.setup.installation-config-view.success (base_url=u'https://git.mydomain.tld' verify_ssl=True client_id=u'wow-such-secret')
11:35:52 [INFO] sentry.identity: identity.token-exchange-error (pipeline_state=u'some-hash' error=u'invalid_state')
...
the above 3 times more
...
11:40:54 [INFO] sentry.integration.gitlab: gitlab.setup.installation-config-view.success (base_url=u'https://git.mydomain.tld' verify_ssl=True client_id=u'wow-such-secret')
172.27.0.7 - - [01/Nov/2020:11:40:54 +0000] "POST /extensions/gitlab/setup/?completed_installation_guide HTTP/1.0" 302 1028 "https://sentry.mydomain.tld/extensions/gitlab/setup/?completed_installation_guide" "wow-such-useragent-string"
```

GitLab log
```
```




One remark, not sure if relevant: there was one previous Webhook in place for one of the repositories in the subgroup for which I tried to set up the integration. I did remove all previous webhooks prior to starting, but it could have taken GitLab some to execute the scheduled removal of the webhook during which this old webhook was lingering around and possibly interfering with setting the Sentry integration up. If so, that would explain why the first 4 attempts failed while the 5th attempt suddenly succeeded. Note, however, that there are no Webhooks at the project level after setting up the integration though. A project webhook was added after I added that repository to `https://sentry.mydomain.tld/settings/group/integrations/` using the `Configure` button.

**Comment by tlrh314** [comment]
Okay, I'm going to claim with 75% certainty that this issue arised for my setup as the result of a delayed removal of a previous webhook in one of the projects in the group/subgroup. I'm not entirely certain of it, but I think that the old webhook was no longer visible on the relevant GitLab settings page. I am certain that 3 of the 4 failed attempts occurred prior to actual removal of the webhook, so a lingering previously existing webhook would still not explain the failed 4th attempt though. The issue was already resolved for me after my 5th attempt though, but I figured providing the logfiles could be useful in light of the last comment in this issue.

**Comment by tlrh314** [comment]
@BYK if there's any further information that I could provide that may be useful to you, please let me know. If you'd like I could also send the relevant parts of the unscrubbed log files, but I'd rather not post those public-facing.

**Comment by BYK** [comment]
@tlrh314 thanks a lot for all the info you provided and sorry for the late response. Since `9.1.2` is quite in the past, I don't think we can do much to improve the experience there.

I think the most important outcome from here is to mention all Sentry services should be run on UTC timezone to avoid any issues as the newer Snuba and Clickhouse services expect that too.

What do you think?

**Comment by tlrh314** [comment]
@BYK many thanks for your reply! So you can confirm that this bug has been resolved in newer releases of Sentry? It has been on my wish list to bump to a newer release for quite a while now, but as `9.1.2` has been running super smoothly I have been too lazy to poke the bear, so to say. Let me just get going on that and pull in all the latest features of Sentry on-premise that I've so far been missing out on 🤩 .

I think the take-home message of my reply is that one way of running into this issue could be a lingering webhook that's scheduled for removal and has already disappeared in the front-end, but has not actually been removed just yet. And indeed, earlier replies suggest it's advisable to run Sentry on UTC timezone.

**Comment by BYK** [comment]
>So you can confirm that this bug has been resolved in newer releases of Sentry?

Cannot really confirm as I don't have access to a local GitLab instance to verify this. It just seems like this is very likely due to the timezone differences (signatures need synchronized clocks within a small tolerance).

You _can_ test this with a fresh install of the newest Sentry self-hosted and only upgarde if it works. Also make sure to back up all your data before the upgrade as there are no guarantees that the upgrade will go smoothly or you'll like the new version (feature-wise I guarantee you'll like it, it just has higher maintenance and hw needs).

Will be keeping the issue open until we can confirm this is no longer an issue.
