### ISSUE TITLE
Jira Integration

### ISSUE THREAD

**Issue by hkrawczyk** [getsentry/sentry#13366]
Is not working on my cloud version.

Got "Please login to your Sentry account to access the Sentry Add-on configuration" when configuring the add-on (nothing more beside that line and button to log in to Sentry) and when I log in and enable Jira integration, the instruction redirects me to Jira marketplace, creating the loop.

**Comment by markstory** [comment]
Could you try disabling your ad-blocker and enable 3rd party cookies?

**Comment by ulgens** [comment]
This is not working for a while. https://marketplace.atlassian.com/apps/1219432/sentry-for-jira?hosting=cloud&tab=reviews There are lots of other users suffering from same issue.
