### ISSUE TITLE
Slack Integration: 

### ISSUE THREAD

**Issue by nguyenpk** [getsentry/sentry#13364]
When I attempt to add the slack integration, the popup window is cut off and I can only see half of the webpage regardless of any zoom settings and window resizing. Using latest Firefox build 
![Screen Shot 2019-05-23 at 11 43 21 AM](https://user-images.githubusercontent.com/11155232/58274382-fe122080-7d4f-11e9-9a6e-2fd1071a0897.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
