### ISSUE TITLE
GitHub Integration: GitHub account is linked to a different user.

### ISSUE THREAD

**Issue by rickmzp** [getsentry/sentry#13370]
I keep getting this error without any information on how to resolve. Can someone help us out with resolving our account state?

<img width="1315" alt="Screen Shot 2019-05-23 at 4 12 49 PM" src="https://user-images.githubusercontent.com/1114/58283194-b2726d80-7d75-11e9-8138-45519e8cbb8a.png">

Thanks!

**Comment by markstory** [comment]
If you're using sentry.io, you might be better served by contacting support. If you're using on-premise you can delete records from `sentry_identity` to break links between github accounts and sentry users.

**Comment by rickmzp** [comment]
Got it. That wasn't clear from before. Thanks!
