### ISSUE TITLE
get all organizations by auth token

### ISSUE THREAD

**Issue by sadmajor** [getsentry/sentry#13407]
## Important Details

How are you running Sentry?

On-Premise docker

## Description

As an admin, I can see all organizations from sentry admin panel from manage/organizations. I checked the query which represents all organizations data and it is same as "List your Organizations" api with an extra parameter "show=all". When I try similar request by using an auth token which is generated with my admin account with all permissions(all scopes are selected), it returns just all organizations that are assigned to my user not all organizations.
curl -H "Authorization: Bearer <auth_token>" 'https://example.com/api/0/organizations/?show=all

## Steps to Reproduce

1. create auth token by admin account
2. request to `/api/0/organizations/?show=all` by auth token

### What you expected to happen

I want to see all organizations (regardless assigned to me or not).

**Comment by sadmajor** [comment]
As an admin, I can see all organizations from sentry admin panel from `manage/organizations`. I checked the query which represents all organizations data and it is same as "List your Organizations" api with an extra parameter "show=all". When I try similar request by using an auth token which is generated with my admin account with all permissions(all scopes are selected), it returns just all organizations that are assigned to my user not all organizations.
`curl -H "Authorization: Bearer <auth_token>" 'https://example.com/api/0/organizations/?show=all`

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
