### ISSUE TITLE
Error still upload even if do not invoke captureException

### ISSUE THREAD

**Issue by Symous** [getsentry/sentry#13409]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description
I can not confirm whether it is a bug that if we once used captureException to report error to sentry and after that even if we remove the captureException code, the error is still uploaded to sentry. what happened?
## Steps to Reproduce

1. [First Step]
use captureException to report an error.
2. [Second Step]
remove or comment the above captureException code.
3. and so on.
Still can see the  new uploaded error.
Good items to include here include:

### What you expected to happen
The error is not supposed to uploaded to Sentry Issues since we have remove the captureException

### Version
Sentry: @sentry/browser 5.3.0
React: 16.8.6

**Comment by markstory** [comment]
Have you made sure that the global `onerror` handlers are also not attached?

**Comment by Symous** [comment]
@markstory thanks for your reply, I do not set a window.onerror handler or any onerror options to sentry initialization. But I have read from the document that:
> Automatically Capturing Errors 
By including and configuring the Sentry Browser SDK, Sentry will automatically attach global handlers to capture uncaught exceptions and unhandled rejections.

Is that means the error will upload automatically even I do not use captureException ? and I also have tested `captureUnhandledRejections :true`, but it seems like that not working as excepted.

**Comment by markstory** [comment]
> Is that means the error will upload automatically even I do not use captureException ?

Yes, that behavior comes from one of the default integrations. You can [disable the default integrations](https://docs.sentry.io/error-reporting/configuration/?platform=browser#default-integrations) if you want.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
