### ISSUE TITLE
Feature request: Display username more prominently

### ISSUE THREAD

**Issue by RudeySH** [getsentry/sentry#13408]
Currently, Sentry displays user data for each issue like this:

![image](https://user-images.githubusercontent.com/3918757/58374052-89013f80-7f37-11e9-83b9-8e72bd00b18d.png)

It tells me the user's name starts with an "R", but I have to scroll down to actually see it.

I'd like to see the full name displayed on top.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
