### ISSUE TITLE
Sentry SAMPLE has big problem 

### ISSUE THREAD

**Issue by junechen86** [getsentry/sentry#1341]
From my test, the Sentry Sample logic has big problem.
From my oppion, if this below method return True, Sentry will not store the event.
the below method has two big problem:
#1. as the group.times_seen increasing, the chance of returning False will increasing, the chance of store the event will increasing.
#2. if you read the context of should_sample method, you will find event.datetime is equal to group.last_seen. so  silence_timedelta will be Zero. time_limit(silence)==SENTRY_MAX_SAMPLE_TIME, so should_sample will almost return False.
```python
def should_sample(group, event):
        silence_timedelta = event.datetime - group.last_seen
        silence = silence_timedelta.days * 86400 + silence_timedelta.seconds
        if group.times_seen % count_limit(group.times_seen):
            return False
        if group.times_seen % time_limit(silence):
            return False
        return True 
```

**Comment by dcramer** [comment]
This should all be fixed now (I'm not sure how we clearly missed this ticket).
