### ISSUE TITLE
Filter by tag not working

### ISSUE THREAD

**Issue by belegnar** [getsentry/sentry#13427]
## Important Details

How are you running Sentry?

* [x ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Events are stored in sentry with tags, i see them, but can't filter on them

## Steps to Reproduce

Post events to sentry with tag
Open issue page
Click on the tag
Click on any item in the list

https://aws1.discourse-cdn.com/standard10/uploads/sentry/optimized/2X/0/03dc2f24e363e0285c74bc9ded7c4824450f1555_2_690x429.png

Good items to include here include:
config on pastebin
https://pastebin.com/ki65EMRL

### What you expected to happen

When filter by tag is active, only events with the tag should be shown

### Possible Solution

Sorry =(

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
