### ISSUE TITLE
how to build the whl and whl.asc from the sentry source

### ISSUE THREAD

**Issue by qbright** [getsentry/sentry#13451]
how to build the whl and whl.asc file from the sentry source, i want to build my own docker image,  i find the docker image is base on the 'https://github.com/getsentry/sentry/releases/download/${SENTRY_VERSION}/sentry-${SENTRY_VERSION}-py27-none-any.whl' , 'https://github.com/getsentry/sentry/releases/download/${SENTRY_VERSION}/sentry-${SENTRY_VERSION}-py27-none-any.whl.asc' , 'https://github.com/getsentry/sentry/releases/download/${SENTRY_VERSION}/sentry_plugins-${SENTRY_VERSION}-py2.py3-none-any.whl', 'https://github.com/getsentry/sentry/releases/download/${SENTRY_VERSION}/sentry_plugins-${SENTRY_VERSION}-py2.py3-none-any.whl.asc'

so , how to build these files

**Comment by mattrobenolt** [comment]
A whl is a Python wheel package. And the asc is the artifact after GPG signing our packages. 

You can find more information here https://github.com/getsentry/sentry-release/blob/master/Dockerfile.sdist, but you shouldn’t ever really need to do this. Just follow this if you’re trying to build something from source or modify to suit your needs https://github.com/getsentry/docker-sentry/tree/master/git.
