### ISSUE TITLE
VSTS Integration: Unable to link account

### ISSUE THREAD

**Issue by paaland** [getsentry/sentry#13497]
When I try to authenticate with Azure Devops I don't get to choose project.
I've got two accounts tied to the same email account, one personal and one work/school. But the Sentry integration wizard will not let me choose which one to authenticate with. This results in my DevOps project not being shown.

Even when I'm already logged in to Azure DevOps it claims to not find my project.

**Comment by chrisevans9629** [comment]
I am glad you referenced my issue.  I never really found a fix for it.  It's kind of a deal breaker if there's no fix for it.

**Comment by Perfect-Web** [comment]
same here

**Comment by BYK** [comment]
Anyone here tried [contacting our support](https://sentry.io/contact/support/) for this?

**Comment by manuzope** [comment]
Closing this in favor of https://github.com/getsentry/sentry/issues/14357.
