### ISSUE TITLE
SnubaError: HTTPConnectionPool(host='localhost', port=1218): Max retries exceeded with url: /query

### ISSUE THREAD

**Issue by bushiquanquan** [getsentry/sentry#13492]
![image](https://user-images.githubusercontent.com/13992586/58782441-313a9680-8611-11e9-80ba-ea0fa8235344.png)
when response  url  http://xxxx:9000/organizations/sentry/issues/?project=2， error occurs

**Comment by markstory** [comment]
What version of sentry are you using?

**Comment by markstory** [comment]
Duplicate of #13494
