### ISSUE TITLE
Gitlab integration requires maintainer privileges to add webhook

### ISSUE THREAD

**Issue by Jimbolino** [getsentry/sentry#13529]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

After connecting the gitlab integration i kept receiving 403 errors. Could not find the logs, so no clue what was wrong. Apparently the integration requires "maintainer" privileges to add a webhook. Developer privileges are not enough. Would be nice if documentation could mention this. 

## Steps to Reproduce

1. Configure gitlab integration
2. Add repository
3. Got 403 error

### Possible Solution

Update documentation on integration/setup screen

**Comment by markstory** [comment]
The [documentation already](https://docs.sentry.io/workflow/integrations/global-integrations/#gitlab) makes note of the required permissions for GitLab. I agree that this could also be mentioned in the setup modal though.

**Comment by carlosen14** [comment]
@markstory have you tried [this](https://gitlab.com/help/user/project/operations/error_tracking)? is the viseversa way. link Sentry from Gitlab

**Comment by markstory** [comment]
No. I work for sentry and maintain the GitLab integration.

**Comment by markstory** [comment]
Closing as the connection modal now includes which GitLab role is required.
