### ISSUE TITLE
How to custom INVALID_EMAIL_ADDRESS_PATTERN?

### ISSUE THREAD

**Issue by shiny** [getsentry/sentry#13541]
![image](https://user-images.githubusercontent.com/117487/58958823-50365580-87d6-11e9-941e-da748ba536fa.png)

I've noticed that qq.com was block by the following code so I can't Invite that mail address.

```python
# block domains which are generally used by spammers -- keep this configurable in case an onpremise
# install wants to allow it
INVALID_EMAIL_ADDRESS_PATTERN = re.compile(r'\@qq\.com$', re.I)
```
Related to #10152

But it's the most popular email service in China for personal usage.
Is it possible to disable this settings?

**Comment by markstory** [comment]
If you're running sentry on-premise you can modify the code and restart the web process.

**Comment by shiny** [comment]
> If you're running sentry on-premise you can modify the code and restart the web process.

Thanks, I'm running sentry in the Docker container, modification can solves my problem.

Another point that the strategy is unfair for hundred million qq mail users, there are large amount developers, not all of them are spammer, please consider.

**Comment by markstory** [comment]
While there are lots of legitimate users using qq.com, we've received significant volumes of abusive traffic in the past from those addresses as well, which is what resulted in the domain ban in the first place.

**Comment by xiaotian45123** [comment]
> ![图片](https://user-images.githubusercontent.com/117487/58958823-50365580-87d6-11e9-941e-da748ba536fa.png)
> 
> 我注意到qq.com被以下代码阻止，所以我不能邀请那个邮件地址。
> 
> ```python
> ＃中通常使用垃圾邮件发送者嵌段域-保持这种配置的情况下，一个onpremise 
> ＃安装要允许它
> INVALID_EMAIL_ADDRESS_PATTERN  = re.compile（ [R “ \ @ QQ 。\ COM $ ”，如re.I）
> ```
> 
> 与[＃10152](https://github.com/getsentry/sentry/pull/10152)相关[](https://github.com/getsentry/sentry/pull/10152)
> 
> 但它是中国最受欢迎的个人使用电子邮件服务。
> 是否可以禁用此设置？

你处理好这个问题没有  ？
