### ISSUE TITLE
[Feature Request] Re-Order of Teams

### ISSUE THREAD

**Issue by ashwin31** [getsentry/sentry#1355]
Re-Order of Teams in homepage. This is for display order only.

**Comment by ashwin31** [comment]
@dcramer I want to re-order the display order of the teams in "My Teams section".

I do have 20 teams there and I want to arrange those in an order I feel important.

The problem is that new projects are getting added to bottom of the list and I need to scroll down the age every time.

**Comment by dcramer** [comment]
This might make sense, though I am not sure yet. We're trying to figure out what teams look like in the long run as we're shifting them to more ACL focused.

**Comment by ashwin31** [comment]
Thats a good idea, I found it difficult to manage users in the past versions but now its much better. Hope to see much more control with the new ACL. When can i see it? in which version?

**Comment by dcramer** [comment]
@ashwin31 this is in our redesign/react branch. Right now all we've really done is remove the team dashboard.

**Comment by ashwin31** [comment]
@dcramer then, Its better to close this issue if you see its fixed or developed to be integrated.

**Comment by ashwin31** [comment]
We are django developers, let me know if we can help in any way in our free time. I am glad to contribute as we are already using self hosted version.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
