### ISSUE TITLE
Dashboard: remove resolved issues from list instead of doing a strike-through

### ISSUE THREAD

**Issue by adamreisnz** [getsentry/sentry#13561]
## Summary
When marking issues as resolved, can they please simply be removed from the list instead of being formatted with a strike-through.

## Motivation
When I mark issues as resolved, I am expecting them to be removed from the list.
This gives me peace of mind and a clear overview of what issues are still left to work on.

Currently, the issues are not removed, and it's hard to visually distinguish them from issues that are not resolved.

Moreover, the filter is set to **Unresolved issues**, so keeping the resolved issues displayed in the overview doesn't make sense from a functional point of view either.

## Additional Context

![image](https://user-images.githubusercontent.com/490562/59002230-d352bc80-8865-11e9-9180-7723adb9c2b2.png)

It's just really not clear at a glance which issues need to be worked on and which have been done. The strike through does not add enough differentiation.

If you are worried this will impact others who may want to keep the resolved issues in the list, then can we please get a setting to control this behaviour. Thank you.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
