### ISSUE TITLE
`Raw` button breaks on multiple presses

### ISSUE THREAD

**Issue by djds23** [getsentry/sentry#1359]
![screen shot 2014-12-31 at 9 14 28 am](https://cloud.githubusercontent.com/assets/5833968/5588100/816788ae-90cd-11e4-98dd-4e2c6a6365b7.png)

Clicking this button more than once breaks the window which displays the raw exception. It turns the window into a blank box, rather than the expected behavior of bringing the window back into focus.

**Comment by dcramer** [comment]
No longer valid
