### ISSUE TITLE
Can't add Github integration on a sentry SaaS installation (sentry.io) 

### ISSUE THREAD

**Issue by mesilov** [getsentry/sentry#13603]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description
 I create an account in sentry.io with email and password, after I try to  add Github integration with Sentry app in Github Marketplace and sentry try to create a new account but I already logged in my Account
https://sentry.io/remote/github/marketplace/purchase/?marketplace_listing_plan_id=47 

![image](https://user-images.githubusercontent.com/1843965/59143766-db7e3980-89d6-11e9-9b15-61a2caa8c413.png)

## Steps to Reproduce

1. Create a new account in sentry (saas) with email and password
2. Try to connect Sentry in Github https://github.com/marketplace/sentry
3. https://sentry.io/remote/github/marketplace/purchase/?marketplace_listing_plan_id=47 
4. See add new sentry account UI 

### What you expected to happen

A connect to me exists Sentry Account

**Comment by BYK** [comment]
I think the best place to report this is our support channel: https://sentry.io/contact/support/

So closing the issue here.
