### ISSUE TITLE
Slack Integration: OAuth Error: Please specify `client_id`

### ISSUE THREAD

**Issue by wakandan** [getsentry/sentry#13629]

**Comment by TejaBeta** [comment]
@wakandan: Add these to your config.yml

slack.client-id: <'client id'>
slack.client-secret: <client secret>
slack.verification-token: <verification token>

Please refer [Slack Configuration](https://forum.sentry.io/t/how-to-configure-slack-in-your-on-prem-sentry/3463). Hope this helps.

**Comment by i5okie** [comment]
Is that expected to work in oss as well?

**Comment by BYK** [comment]
Closing due to lack of any proper details. @wakandan I'd recommend searching the forums (https://forum.sentry.io/) and existing issues before posting a new issue here and then adding as many details as possible for a quicker resolution and response.

**Comment by dmugtasimov** [comment]
I have the same issue.
"OAuth Error: Please specify `client_id`"

It happens when I click "Add Workspace" at "Slack Integration" page.

**Comment by xuqingfeng** [comment]
For anyone who had the same issue, I managed to make it work by(apart from following [this tutorial](https://forum.sentry.io/t/how-to-configure-slack-in-your-on-prem-sentry/3463)):

1. update config file: `sentry/config.yml`
2. rebuild docker images: `docker-compose build`
3. restart containers with updated images: `docker-compose up -d`

**Comment by TimoDJatomika** [comment]
Would be nice if I could configure thous parameters via ENV. 
We use the official Sentry Docker image.

**Comment by TimoDJatomika** [comment]
I've managed to solve the Problem (also on premise sentry installation with the official sentry docker image).

Like @xuqingfeng I also followed this tutorial: [How to configure Slack in your on-prem Sentry](https://forum.sentry.io/t/how-to-configure-slack-in-your-on-prem-sentry/3463)

Unlike @xuqingfeng I didn't build a new Docker image. I just set the following ENV's:
- env('SLACK_CLIENT_ID')
- env('SLACK_CLIENT_SECRET')
- env('SLACK_VERIFICATION_TOKEN')

After that I followed the next steps described in the tutorial.

**Comment by popakatepepel** [comment]
where i can find all this variables ?

> slack.client-id: <'client id'>
> slack.client-secret: <'client secret'>
> slack.verification-token: <'verification token'>

**Comment by popakatepepel** [comment]
perhaps this HowTo is not relevant anymore? I can't see any **Basic Information**
<img width="809" alt="Screenshot 2020-04-13 at 00 41 09" src="https://user-images.githubusercontent.com/62313557/79080675-a7bf1f00-7d1f-11ea-8314-9f2c1de8abc7.png">
