### ISSUE TITLE
@sentry/browser error in Andriod 5

### ISSUE THREAD

**Issue by hxqbeyond** [getsentry/sentry#13631]
This step:
import * as Sentry from '@sentry/browser';// "@sentry/browser": "5.1.1"

Sentry.init({ dsn: 'https://***@yunke-sentry.myscrm.cn/10' })

In android 5:
Object.assign is not a function

**Comment by BYK** [comment]
Looks like you need to add some polyfills in your build. This is not related to Sentry itself so closing.

Also, next time please open issues regarding the SDK in their own repos. https://github.com/getsentry/sentry-javascript would be the one for this issue.
