### ISSUE TITLE
[Monolog] Make it possible to send stackTrace for non-exception events

### ISSUE THREAD

**Issue by JanMikes** [getsentry/sentry#13653]
## Summary

I did not find any way to add stacktrace to sentry monolog handler when logging messages without exceptions.

## Motivation

It would be awesome to have stracktrace while logging with monolog like this: `$logger->critical($message)`, right now it is very hard (nearly impossible) to find out where in the application was this message logged from.

## Additional Context

It is because of `Sentry\Monolog\Handler::write()` uses `HubInterface::captureEvent()`, it would have to use `HubInterface::captureMessage()` or `HubInterface::captureException()`.

I can imagine there would be conditional call of hub's method, depending on `$record['context']['exception']` presence.

Right now i am using this workaround, but i consider it kind of stupid, but working 😄 
```php
$logger->error($message [
    'exception' => new \Exception($message),
]);
```

**Comment by JanMikes** [comment]
I am sorry, wrong repo, moved to https://github.com/getsentry/sentry-php/issues/835

**Comment by untitaker** [comment]
@JanMikes thanks, often sdk issues go here to die :)
