### ISSUE TITLE
Django signal for marking issue resolved not working

### ISSUE THREAD

**Issue by agronick** [getsentry/sentry#13664]
## Important Details

How are you running Sentry?

* [x] On-Premise docker 9.1,1

## Description

I am marking commits as resolved through a GitLab integration. Releases and commits show up correctly but issues are not being marked are resolved. Simply resaving the commit model causes the Django signal to run and everything is processed correctly. 

The commit is not associated until I run this in the Python shell
` Commit.objects.filter(message__contains='Fixes SUPPORTLINK-FRONTEND-21')[0].save()`

I can see that all the regular expressions are working correctly. And everything does become associated. For some reason it is not triggering on the initial save. All releases, commits, and deploys are processes fine. For some reason they just aren't associated when they contain a resolved message.

## Steps to Reproduce

Commit to gitlab with the message.
```
Fixes SUPPORTLINK-FRONTEND-21

Spelling error
```
Notify Sentry through rest API. Everything is saved but for some reason the Django signal is not associating correctly until it the signal run again through a manual model save.

### What you expected to happen
The resolved commit should be associated without manual intervention.

### Possible Solution
The issue seems to be that issues are not marked as resolved until they are deployed to the environment where the issue happened. Deploying isn't what I would expect to mark an issue as resolved though - I would expect pushing the fix to my repository to make the issue resolved.

Another thing is that when I resaved the model manually I got a button with a link to the Gitlab revision on the error. Normally I just see the message that says the issue was resolved in xyz release with no information about Gitlab.

If I had to guess I would think something is happening out of order and when the commit is originally saved it doesn't have the Gitlab information and resaving it after the Gitlab information has been fetched causes everything to work normally.

**Comment by BYK** [comment]
The only possible place that may cause an issue the first time may be here: https://github.com/getsentry/sentry/blob/a66edbe45cd0d1387dbf16912b8eadd8be39041b/src/sentry/receivers/releases.py#L55-L57

That said, even then you should be seeing some internal errors regarding this in Sentry. Do you see them?
