### ISSUE TITLE
Incorrect padding in worker logs

### ISSUE THREAD

**Issue by adepue** [getsentry/sentry#1366]
After upgrading to Sentry 7.0.1 (from 6.4.4), we are getting tons of the following stack trace in celery worker logs.

[ERROR] Incorrect padding
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sentry/db/models/fields/gzippeddict.py", line 35, in to_python
    value = pickle.loads(decompress(value))
  File "/usr/local/lib/python2.7/dist-packages/sentry/utils/strings.py", line 37, in decompress
    return zlib.decompress(base64.b64decode(value))
  File "/usr/lib/python2.7/base64.py", line 76, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

Working on tracking down where it is happening, but figured there may be a simple solution?

**Comment by dcramer** [comment]
We had someone else report this as well. Going to dig into it but we don't see this on production so I'm a bit confused what would be out of sync that this is happening.

**Comment by dcramer** [comment]
Actually it sounds like this is linked to GH-1365

**Comment by dcramer** [comment]
In fact closing in favor of GH-1365

**Comment by adepue** [comment]
Thanks!
