### ISSUE TITLE
Event.culprit calls get on a list of tags, which fails

### ISSUE THREAD

**Issue by adepue** [getsentry/sentry#1367]
The transitional properties that were deprecated in Sentry 7 ({logger,site,logger,level,culprit}) all call self.tags.get('PROPNAME')

```python
    @property
    def logger(self):
        warnings.warn('Event.logger is deprecated. Use Event.tags instead.',
                      DeprecationWarning)
        return self.tags.get('logger')
```

The issue is that self.tags returns a list of tuples, so calling get on that doesn't go so well.

Is the correct approach to just iterate through all tags to look for the one you want?  Happy to update the transitional properties in a PR, just wanted to confirm the approach.

**Comment by dcramer** [comment]
I swear I had fixed this, but yeah. I'll go ahead and push something up. We'll probably be throwing out a 7.0.2 sometime later today.
