### ISSUE TITLE
transfer project is not working

### ISSUE THREAD

**Issue by Artem-Ostankov** [getsentry/sentry#13685]
I try to transfer 
`elbe-frontend-prod` and `elbe-frontend-dev-qa` in `mhb-dev` organisation to gazanfer.ercan@googlemail.com
but it doesn't work and I get an error : `error transfering elbe-frontend-prod` 
Generally I would like to transfer the whole organisation, but since it's not possible, I need a way to transfer the projects at least.

**Comment by BYK** [comment]
Can you please provide more information? Are you using the cloud version or self-hosted?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
