### ISSUE TITLE
Ancient boto3 & botocore versions

### ISSUE THREAD

**Issue by mikeroll** [getsentry/sentry#13705]
Any particular reason these are pinned? This gets in the a way a bit as I am developing an AWS plugin and the old boto3 api is lacking in some places. 
Thanks!

**Comment by markstory** [comment]
We pin dependencies so that they don't slide into versions that contain breaking changes.

**Comment by mikeroll** [comment]
Yeah I'm not suggesting you unpin them completely, but perhaps it's possible to bump the pinned versions?

**Comment by markstory** [comment]
@mikeroll That's doable. Would you be willing to send a pukk request that bumps up to the version you need?

**Comment by max-rocket-internet** [comment]
Any update on this? Can we jump to a very recent version of boto so that newer IAM authentication mechanisms are supported?

**Comment by BYK** [comment]
@joshuarli @mattrobenolt any reason to not merge the attached PR?

**Comment by mattrobenolt** [comment]
My comment here still applies. https://github.com/getsentry/sentry/pull/13777#issuecomment-504564032

**Comment by BYK** [comment]
@mattrobenolt that's fine, we'll check for backwards compatibility. I'm guessing you have no other concerns then?

**Comment by mattrobenolt** [comment]
Nope, that's all.

**Comment by joshuarli** [comment]
@mattrobenolt Should we drop s3 support for filestore while we're at it? Not used in production + would take time to test and possibly port to newer boto3.

**Comment by mattrobenolt** [comment]
I think that'd be a bad idea. S3 is _very_ common. Nobody uses Google Storage except us, and we don't even use the backend here because of filestore.

**Comment by max-rocket-internet** [comment]
> Should we drop s3 support 

😅

**Comment by BYK** [comment]
Fixed via #22543.
