### ISSUE TITLE
Additional Index on Message Filter Table

### ISSUE THREAD

**Issue by gardinerd** [getsentry/sentry#1370]
I run a fairly large MySQL DB instance for Sentry 6.4.4 and noticed a significant performance improvement on the dashboard by simply adding the two following indexes on the message filter table. 

Page load times dropped from 40-60 seconds to 1-2 seconds.

filter index:
ADD INDEX `filter_index` (`project_id` ASC, `group_id` ASC, `key` ASC, `times_seen` ASC)

value_key index:
ADD INDEX `value_key` (`value` ASC, `key` ASC)

**Comment by dcramer** [comment]
Add this to the list of "we really need to fix migrations so they provide sane default indexes".

We have a number of these (probably a dozen) on getsentry.com that aren't in the migration schemas, mostly due to legacy reasons.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

Also, I think we have "fixed" migrations by switching to Django migrations, but who knows. 🤷🏻
