### ISSUE TITLE
 Oops! Something went wrong

### ISSUE THREAD

**Issue by HeiShanLaoYao889** [getsentry/sentry#13724]
> ![image](https://user-images.githubusercontent.com/24189898/59660744-ef4a4c80-91db-11e9-8f17-dba09e93b521.png)
> Docker version 18.09.6, build 481bc77156
> docker-compose version 1.22.0, build f46880fe
> ![image](https://user-images.githubusercontent.com/24189898/59660944-5d8f0f00-91dc-11e9-92f1-c22910770bdb.png)

```
07:32:58 [ERROR] django.request: Internal Server Error: /auth/login/ (status_code=500 request=<WSGIRequest: GET u'/auth/login/'>)
222.90.194.144 - - [18/Jun/2019:07:32:58 +0000] "GET /auth/login/ HTTP/1.1" 500 5659 "http://134.175.170.69:9000/auth/login/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36"
[root@VM_29_101_centos onpremise]#  docker logs --since 2m e47e4aaff85b
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 225, in dispatch
    return self.handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 193, in handle
    return super(AuthLoginView, self).handle(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 238, in handle
    return super(BaseView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_login.py", line 211, in get
    org = Organization.get_default()
  File "/usr/local/lib/python2.7/site-packages/sentry/models/organization.py", line 164, in get_default
    )[0]
  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
```

**Comment by SiriusRed** [comment]
Please, provide your sentry version.
Which auth provider do you use?

**Comment by BYK** [comment]
Have you run `docker-compose run --rm web upgrade` before trying to run the service? Seems like your instance doesn't have any organizations at it should have at least one.

**Comment by HeiShanLaoYao889** [comment]
$ cd onpremise

 $ docker volume create --name=sentry-data && docker volume create --name=sentry-postgres

 $ cp -n .env.example .env

 $ docker-compose build

 $ docker-compose run --rm web config generate-secret-key

 $ vim .env

 $ docker-compose run --rm web upgrade

 $ docker-compose up -d

 $ docker-compose ps

I did it in this order, but I still made a mistake

**Comment by BYK** [comment]
I think your `docker-compose run --rm web upgrade` run didn't finish properly. Can you try again from scratch please?

**Comment by HeiShanLaoYao889** [comment]
No, I've tried it many times, using different versions

**Comment by BYK** [comment]
@HeiShanLaoYao889 can you share the logs for your installation, especially the output from running `docker-compose run --rm web upgrade`?

Also please ensure you have at least 3GB of memory available to your containers, during this command as they tend to get killed by Docker in the middle if your device runs out of memory.

**Comment by rquinlivan** [comment]
I'm seeing the same issue adapting to from [the setup instructions for Docker](https://docs.sentry.io/server/installation/docker/#running-migrations). I think that the `createuser` command should also create an organization, but it doesn't appear to do that.

**Comment by rquinlivan** [comment]
My very horrible workaround for this issue was to manually insert a `sentry_organization` row  and a `sentry_organizationmember` row with the ID for the admin user that the setup command created. I really hope there is a better way of doing this.

**Comment by markkimsal** [comment]
@HeiShanLaoYao889  add more swap space, clear out pgsl or remove the container and create again if using docker.  Try to have about 6 GB of ram and/or swap available.  see #13975

**Comment by BYK** [comment]
I'm going to close this issue as this seems to be around unfinished migrations. We are already aware that these require some amount of RAM and added a check to the onpremise install script for this. We are also going to look into ways for reducing the footprint of migrations.
