### ISSUE TITLE
Oops! Something went wrong

### ISSUE THREAD

**Issue by HeiShanLaoYao889** [getsentry/sentry#13723]
![image](https://user-images.githubusercontent.com/24189898/59660744-ef4a4c80-91db-11e9-8f17-dba09e93b521.png)
Docker version 18.09.6, build 481bc77156
docker-compose version 1.22.0, build f46880fe
![image](https://user-images.githubusercontent.com/24189898/59660944-5d8f0f00-91dc-11e9-92f1-c22910770bdb.png)

**Comment by mattrobenolt** [comment]
There is literally 0 actionable information here without logs or something to at least begin to help us help you.
