### ISSUE TITLE
Should sentry email user 1 on every error?

### ISSUE THREAD

**Issue by dbenamy** [getsentry/sentry#1374]
That seems to be happening, although it's possible it's a plugin doing something weird.

Also, user 1 had a default email address of sentry@localhost so all those mails were bouncing until I fixed that.

This is on f66b0f8.

Thanks very much!

**Comment by dcramer** [comment]
It depends on how your rules are setup.

Check project settings => rules and confirm that theres not something that says "Every event" (there isnt by default).

Going to close this as I'm 99% certain this isn't an issue or we would have found it in prod by this point. If you have more information that you think its still an issue feel free to update this ticket.

**Comment by dbenamy** [comment]
Thanks for the super quick reply, as usual!

I'm definitely using the default rules.

I added some debug logging and it looks like https://github.com/getsentry/sentry/blob/f66b0f8/src/sentry/plugins/bases/notify.py#L55 is returning `[1]`. From reading the code, it looks like https://github.com/getsentry/sentry/blob/f66b0f8/src/sentry/plugins/bases/notify.py#L76 adds the default User 1 and since I don't have any UserOptions, it doesn't get disabled.
