### ISSUE TITLE
Blacklist of user IPs

### ISSUE THREAD

**Issue by BrodaNoel** [getsentry/sentry#13771]
## Summary
Blacklist of user IPs

## Motivation
I'm tracking errors in a mobile App. Google has a bot that does some kind of tests in the apps that are uploaded to the Google Play Store. That bot seems to have some limitations about internet connection (ironically), thus, it is reporting a lot of "Network request failed" errors. All of them from the same IP range:

<img width="1131" alt="Screen Shot 2019-06-21 at 13 38 24" src="https://user-images.githubusercontent.com/1837969/59937907-00889880-942a-11e9-99c0-4f82909c253c.png">

Ignoring errors from some IP ranges (`66.249.69.*`, ie) will be really helpful to get a cleaner "dataset".

_Have a good day.
Best,
Raymond Reddington_

**Comment by BYK** [comment]
Inbound filters should allow this now: https://docs.sentry.io/product/error-monitoring/filtering/
