### ISSUE TITLE
OnPremise - 9.1.1 : Installation of Gitlab leads to a Page NotFound because of organisation's name in uri

### ISSUE THREAD

**Issue by Rebolon** [getsentry/sentry#13788]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.1]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I upgrade Sentry 9 to the latest Sentry 9.1
I failed to keep my data but it's not a problem and a had to configure again the projects, teams...
When i'm trying to configure integrations with my own instance of Gitlab i cann't finish the process because it fails before the ends with the message Page Not Found in the integrations page.

## Steps to Reproduce

1.  from the page https://myServersettings/mySentryOrg/integrations/ 
2.  i click on button install on the Gitlab row and a modal appear
3.  i click on **add installation** which open a window
4.  i click on **next** which open this uri: https://myServersettings/mySentryOrg/extensions/gitlab/setup/?completed_installation_guide with the message Page Not Found

### What you expected to happen

The page should display the form to add Gitlab server information

### Possible Solution
if i copy the uri (step 4) and remove the mySentryOrg part like this `https://myServersettings/extensions/gitlab/setup/?completed_installation_guide` then i can access to the step 2 of the form

But then when i validate this form i go to the gitlab uri and when i click on the validate button the callback uri also have the mySentryOrg part in the path so it fails and the plugin still can not be installed

So i also tried to change the callbackuri in gitlab config but when it goes back to sentry, it displays this error ***Whoops! Looks like something went wrong! Give that another try.

The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.***

**Comment by BYK** [comment]
This should be resolved in 9.1.2, please ping back if it is not.

**Comment by Rebolon** [comment]
I've just updated our server and it doesn't seem to be fixed.
Here is how i did the update:
 * git fetch --prune
 * git pull origin master
 * add `SENTRY_IMAGE=sentry:9.1.2` to my .env file
```
docker-compose build --pull # Build the services again after updating, and make sure we're up to date on patch version
docker-compose run --rm web upgrade # Run new migrations
docker-compose up -d # Recreate the services
```
Then i log into the app and try to add giltab integration, but there is the same problem.

**Comment by BYK** [comment]
Can you share some logs with us?

**Comment by Rebolon** [comment]
I think it's possible (this is the minimum i can do to improve Sentry !)
Which logs do you need ?

Benjamin RICHARD
E-mail : benjamin-richard@orange.fr <benjamin-richard@orange.fr>
about.me/benjamin.richard/


Le lun. 14 oct. 2019 à 20:54, Burak Yigit Kaya <notifications@github.com> a
écrit :

**Comment by BYK** [comment]
@Rebolon  - seeing which URL GitLab tries to hit would be a big help. Also sharing your configuration would help.

**Comment by Rebolon** [comment]
The organization is `sentry-studiosystems` and it has been set up on sentry installation from UI.

When i click on Integrations > Gitlab Install it open a modal on that uri : https://log.tom-health.fr/organizations/sentry-studiosystems/integrations/gitlab/setup/
Then i can click on next and it goes on this uri: https://log.tom-health.fr/sentry-studiosystems/extensions/gitlab/setup/?completed_installation_guide 
But the content of the modal is `Page Not Found`

On the server the .env file contains EMAIL related env, and this one:
`SENTRY_IMAGE=sentry:9.1.2`

What else could i give you ?

**Comment by BYK** [comment]
@Rebolon this is VERY useful. The final piece I need is the output of `sentry config get options.system.url-prefix`

**Comment by Rebolon** [comment]
Here are our containers:
sentry@vps560644:~/onpremise$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                    NAMES
0266cafbcc30        onpremise_worker       "/entrypoint.sh ru..."   3 weeks ago         Up 3 weeks          9000/tcp                 onpremise_worker_1
59a86974d33a        onpremise_cron         "/entrypoint.sh ru..."   3 weeks ago         Up 3 weeks          9000/tcp                 onpremise_cron_1
d69c10e0cc3e        onpremise_web          "/entrypoint.sh ru..."   3 weeks ago         Up 3 weeks          0.0.0.0:9000->9000/tcp   onpremise_web_1
4a6714d2990b        postgres:9.5           "docker-entrypoint..."   3 months ago        Up 3 months         5432/tcp                 onpremise_postgres_1
2144996ea862        tianon/exim4           "docker-entrypoint..."   3 months ago        Up 3 months         25/tcp                   onpremise_smtp_1
da66994240be        memcached:1.5-alpine   "docker-entrypoint..."   3 months ago        Up 3 months         11211/tcp                onpremise_memcached_1
beca614441f4        redis:3.2-alpine       "docker-entrypoint..."   3 months ago        Up 3 months         6379/tcp                 onpremise_redis_1

I've run the command on those container but it always return : unknown option
sentry@vps560644:~/onpremise$ docker exec -it onpremise_worker_1 bash
root@0266cafbcc30:/usr/src/sentry# sentry config get options.system.url-prefix
12:27:09 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
12:27:34 [INFO] sentry.plugins.github: apps-not-configured
Error: unknown option: options.system.url-prefix

sentry@vps560644:~/onpremise$ docker exec -it onpremise_web_1 bash
root@d69c10e0cc3e:/usr/src/sentry# sentry config get options.system.url-prefix
12:28:08 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
12:28:22 [INFO] sentry.plugins.github: apps-not-configured
Error: unknown option: options.system.url-prefix

sentry@vps560644:~/onpremise$ docker exec -it onpremise_cron_1 bash
root@59a86974d33a:/usr/src/sentry# sentry config get options.system.url-prefix
12:29:27 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
12:30:20 [INFO] sentry.plugins.github: apps-not-configured
Error: unknown option: options.system.url-prefix

**Comment by BYK** [comment]
@Rebolon - sorry the command should have been `sentry config get system.url-prefix` ☹️

**Comment by BYK** [comment]
Also you can just do `docker-compose run --rm web config get system.url-prefix` instead of what you are doing.

**Comment by Rebolon** [comment]
thanks for the tips @BYK 
Here is the output:

```
# docker-compose run --rm web config get system.url-prefix
Starting onpremise_postgres_1 ... done
Starting onpremise_smtp_1     ... done
Starting onpremise_redis_1    ... done
Starting onpremise_memcached_1 ... done
11:13:04 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
11:13:10 [INFO] sentry.plugins.github: apps-not-configured
        type: STRING
 from config: <not set>
     current: https://MY_HOST/sentry-studiosystems/
```

i just replaced the real hostname with MY_HOST

**Comment by BYK** [comment]
@Rebolon - okay, I think the reason is `url-prefix` having a subpath on it. Sentry only runs on a dedicated domain or subdomain, it cannot work with under paths other than `/`: https://github.com/getsentry/sentry/pull/5174

**Comment by Rebolon** [comment]
ok,this is strange because this subpaths has been created during installation when it asked me the organization (if i remember well).
I've read the issue 5174 and the file changed but i don't really see how to fix this on my installation

**Comment by BYK** [comment]
@Rebolon - if you changed the config file running the following should update your image:
```
docker-compose down
docker-compose build
docker-compose up
```

Since the file is picked up during the image build stage.

**Comment by Rebolon** [comment]
@BYK thanks, i've finished the configuration and this time it seems better.
But... 
If i can access to the form, and fill everything, when i click on Submit button i'm redirected to my Gitlab instance, but on a page with this message : The redirect URI included is not valid.

If i inspect the uri in the header here is wht i get:
http://MY_GITLAB_HOST/oauth/authorize?scope=api&state=AN_ID&redirect_uri=%2Fextensions%2Fgitlab%2Fsetup%2F&response_type=code&client_id=THE_CLIENT_ID

does the redirect_uri parameter should not be the full uri to sentry ?
When we configure the Gitlab application (like it's said on the first step of the modal, point3: 
```
Name: Sentry
Redirect URI: /extensions/gitlab/setup/
Scopes: api
```
)
we cannot jst set the path for the redirect URI because Gitlab ask for a full uri with hostname. So i have to fill https://My_SENTRY_HOST/extensions/gitlab/setup/

But because in the GET header we only have the path of the uri, then Gitlab may not match ht information. Am i wrong ?

**Comment by Rebolon** [comment]
I also tried to change manually the redirect_uri to what i expect to be the right one.
Then Gitlab show me an authorization form.
If i valid the form (give the access), then i go back to sentry, but with this error:

```
Whoops! Looks like something went wrong! Give that another try.

The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client.
```
