### ISSUE TITLE
Adding GitLab repository fails due to ActiveRecord::NotNullViolation

### ISSUE THREAD

**Issue by gopeter** [getsentry/sentry#13782]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I've connected my self-hosted GitLab to Sentry and now want to add a repository to track releases. But everytime I try this, Sentry throws an error 500. Looking in GitLab's logs, I get this:

```
ActiveRecord::NotNullViolation (PG::NotNullViolation: ERROR: null value in column "issues_events" violates not-null constraint

DETAIL: Failing row contains (72, 154, 2019-06-22 11:47:37.118579+00, 2019-06-22 11:47:37.118579+00, ProjectHook, null, t, null, t, null, f, t, f, f, f, f, f, null, null, SOME_SECRET_KEY?

Ih5..., SOME_SECRET_KEY?

, SOME_SECRET_KEY?

FlP..., SOME_SECRET_KEY?

).

: INSERT INTO "web_hooks" ("project_id", "created_at", "updated_at", "push_events", "merge_requests_events", "encrypted_token", "encrypted_token_iv", "encrypted_url", "encrypted_url_iv") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"):

/home/git/gitlab/config/initializers/peek.rb:18:in `async_exec_params'
/home/git/gitlab/config/initializers/peek.rb:18:in `exec_params'
...
```

## Steps to Reproduce

1. Go to Organization Settings
2. Choose connected GitLab instance
3. Choose "Add respository" and choose a repository of your GitLab account
4. After a second, Sentry says that there is a server error 500

I'm using GitLab 11.11.3.

### What you expected to happen

That this doesn't happen :-)

### Possible Solution

Unfortunately not.

**Comment by markstory** [comment]
Did gitlab recently make issues_events a required field?

**Comment by gopeter** [comment]
No, `null: false` was always given (since it was introduced 5 years ago 😄): https://gitlab.com/gitlab-org/gitlab-ce/commit/169b4ce0ca2ef04d37deb6bdb054cb8124a9db61

**Comment by markstory** [comment]
Ok. I have the sentry integration working against both a self-hosted GitLab and gitlab.com.

**Comment by gopeter** [comment]
Hmmmm, my instance is running on Postgres 10. And I'm using this Docker image: https://github.com/sameersbn/docker-gitlab

**Comment by gopeter** [comment]
Oh, found this one: https://gitlab.com/gitlab-org/gitlab-ce/issues/36531#note_37651729 👍
