### ISSUE TITLE
Async loader requests two domains with the related connection overhead

### ISSUE THREAD

**Issue by dalyr95** [getsentry/sentry#13783]
## Summary

Async loader calls two CDN sub domains and the related connection overhead of DNS lookup, connection and SSL handshake. In this example take from webpagetest, this added a half a second delay to the main bundle being downloaded.

```
DNS Lookup: 289 ms
Initial Connection: 141 ms
SSL Negotiation: 67 ms
```

![Screenshot 2019-06-22 at 16 45 18](https://user-images.githubusercontent.com/548526/59966048-6cdcc800-950e-11e9-9e57-7b73bda0e287.png)

Serving the async loader and main bundle from the same subdomain can save up to half a second in connection setup and allow the main bundle TTFB alot quicker.

## Motivation

Considering the error reports are degraded before the main bundle is downloaded and a major point of failure in JS apps is the app erroring onload and then breaking everything removing any bottlenecks to downloading the main bundle should be removed.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
