### ISSUE TITLE
Cleanup environment

### ISSUE THREAD

**Issue by guilhermearaujo** [getsentry/sentry#13803]
## Summary

Add the possibility to cleanup events of a specific environment (even for multiple projects)

## Motivation

Sentry is able to handle multiple environments per project, for instance *Production*, *Staging* and *Development*.

Users might want to periodically clean up their events to a certain retention window. However, different environments may have different needs. For instance, I'd like to keep *production* events for 180 days, but *staging* events can be discarded after 30 days and *development* events can be scrapped as soon as 7 days.

## Example
As a suggestion:
```shell
sentry cleanup --env staging --env stg --days 30
```

The `--env` parameter could receive multiple values in case distinct projects have different names for environments with the same "purpose".

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
