### ISSUE TITLE
OnPremise - 9.1.1 : on captureException or captureMessage i get 'HTTP Error 403: OK'

### ISSUE THREAD

**Issue by Rebolon** [getsentry/sentry#13805]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.1]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I have installed a fresh version of sentry onpremise (because the upgrade i tried yesterday completly fail).
When i setup project it gives me an DSN Key that i use in PHP or JS code.
But when a do a captureException or captureMessage, i have this response `HTTP 403: OK`
And in the Sentry Dashboard, nothing is captured.

## Steps to Reproduce

1. Install Sentry OnPremise
2. Create a Project
3. Use the DSN Key in a javascript project and do a captureMessage
4. Look at the XHR log in chrome devTools (or any other devTools)

### What you expected to happen

I expect the captureException/Message to be logged into Sentry

### Possible Solution

In fact the DSN Key displayed by Sentry is not good.
Here is what it displays: `https://aSimpleHash:MyHost/{ORGANISATION_NAME}//{PROJECT_ID}`
Whereas it should be `https://aSimpleHash:MyHost/{PROJECT_ID}`

When i use the 2nd DSN Key (removing organisation's name and 2 slashs) then it works well, so the problem is in the display of the DSN Key in the project setting page.

**Comment by BYK** [comment]
This should be resolved in 9.1.2, please ping back if it is not.
