### ISSUE TITLE
OnPremise - 9.1.1 : Invitation link sent to user is invalid because or organisation's name in uri

### ISSUE THREAD

**Issue by Rebolon** [getsentry/sentry#13807]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.1]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

When i create members, a mail is sent to them with an invitation link. The problem is that this link leads to the authentification page instead of the account creation.

1. If they click on 'I forgot my password', no email is sent
2. More over, when i manually correct the link (see Solution section below) then can create the account but they are not linked to any organisation.

Seems to be related to #13788 and #13805 

## Steps to Reproduce

1. install sentry onpremise
2. create member with a valid email
3. open the email and click on the link (or open the member page in sentry and copy/paste the displayed invitation link)
4. you land on authentification page

### What you expected to happen

The link should leads you to account creation page.
You shoud be in an organization.
And if you click on 'I forgot my password' i should receive a valid email.

### Possible Solution

Change the invitation link from `https://YourSentryHost/organisationName/accept/{projectId/simpleHash/` to `https://YourSentryHost/accept/{projectId/simpleHash/`

But i have no clue for the 2 others problems: 'I forgot my password' link and the missing organisation relation of the account (i went to /admin page to add created users to organisation 1)

**Comment by BYK** [comment]
This should be resolved in 9.1.2, please ping back if it is not.
