### ISSUE TITLE
OnPremise - 9.1.1: on error page (whoops) the javascript inside the page doesn't have the good DSN because of organisation's name

### ISSUE THREAD

**Issue by Rebolon** [getsentry/sentry#13806]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.1]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Sometimes i land on sentry error page with the message **Whoops ...**
On this page, if i inspect the source page i can see something like this :
```
<script>
  window.__SENTRY__OPTIONS = {
    dsn: 'https://SimpleHash@myHost/myOrganisationName//ProjectId',
    release: '9.1.1',
    whitelistUrls: ["*"]
  };
  window.__SENTRY__USER = {"ip_address":"AnIp","email":"myEmail","id":1} || undefined;
</script>
```

The problem with those info is that the DSN key is wrong because it should be : `https://SimpleHash@myHost/ProjectId`

## Steps to Reproduce

This issue is related to #13805 and certainly #13788 

### What you expected to happen

There should be the right DSN key, so it could send log to project 'Internal'

### Possible Solution

No Idea

**Comment by BYK** [comment]
This should be resolved in 9.1.2, please ping back if it is not.
