### ISSUE TITLE
CORS reports from JS

### ISSUE THREAD

**Issue by terinjokes** [getsentry/sentry#1383]
If a JS reporter wants to POST a report using CORS (for example, to avoid GET parameter length issues), the current implementation in api.py will require `secret_key` to be included in the `X-Sentry-Auth` header

The current implementation only requires an Origin check on GET requests, instead of verifying with `secret_key`. POSTs from JavaScript (with an Origin header) was previously allowed, but removed with af8e9aaaaf3e3eac009681af261a7dd98c8e97f6.

**Comment by terinjokes** [comment]
@mattrobenolt Have any recommendations on how to resolve this? I don't want to re-introduce any previous security issues you closed with the changes in this area.

**Comment by terinjokes** [comment]
@mattrobenolt any update on this?

**Comment by mattrobenolt** [comment]
We've added the ability to swap in your own transport, but I have no cut a release of this yet.

I planned on doing that later this week, but here's the pull request that added the docs: https://github.com/getsentry/raven-js/pull/390/files

/cc @benvinegar

**Comment by terinjokes** [comment]
This ticket is to track that fact that the server stopped accepting reports over CORS, not to change the transport in raven-js.

(As you might remember, we have our own reporter)

**Comment by mattrobenolt** [comment]
Ohh, I misread. I forgot your use case.

No, we haven't done anything about this. I'm going to bump this up now that I have more time and take a look.

We're going to be needing to support this use case ourselves too, POSTing with an Origin/Referer check.

Sorry about that.
