### ISSUE TITLE
Slack Integration: invalid permission scope 'chat:write' is requested

### ISSUE THREAD

**Issue by gnkoshelev** [getsentry/sentry#13839]
I've got error from Slack when I try to configure Slack Workspace in my Sentry installation:
> Invalid permissions requested
> User tokens do not support scope: chat:write

Sentry app requests invalid permission scope `chat: write`. But Slack supports `chat:write:bot` and `chat:write:user` scopes instead (see screenshot from permission scopes page of bot app at api.slack.com).

<img width="615" alt="image" src="https://user-images.githubusercontent.com/14298612/60237061-1e3f7d00-98c4-11e9-8a7d-1916921c308d.png">

**Comment by RishabhTayal** [comment]
I am getting this error when installing Slack in my project.

<img width="571" alt="Screenshot 2019-06-28 10 38 32" src="https://user-images.githubusercontent.com/2100166/60354079-100b6280-9991-11e9-87c1-a33c55feb23e.png">

**Comment by EvanPurkhiser** [comment]
What version of sentry are you using?

**Comment by gnkoshelev** [comment]
9.0.x, 9.1.x.

**Comment by EvanPurkhiser** [comment]
Are you on 9.1.2?

There is a fix for slack to correctly use bot tokens: https://github.com/getsentry/sentry/pull/13184

**Comment by sem1993** [comment]
I've changed `SLACK_INTEGRATION_USE_WST` to `True` in `.../lib/python2.7/site-packages/sentry/conf/server.py`, restarted sentry services and still got an error about `Failed to retrieve token from the upstream service.`
Sentry 9.1.2 BTW

**Comment by scefali** [comment]
Closing this because it has been fixed long ago. Granted, you might need a new Slack bot app for this to work with recent versions of Sentry. The `chat:write:bot` and `chat:write:user` scopes have been deprecated for new apps: https://api.slack.com/scopes/chat:write

Typical Slack ¯\\(ツ)/¯
