### ISSUE TITLE
Arrow button in issue detail goes to wrong project when coming from email link

### ISSUE THREAD

**Issue by Christilut** [getsentry/sentry#13864]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Pressing the arrow button next to a project name when inside an issue detail page returns me to the wrong parent project

Seems to happen when coming from an email

## Steps to Reproduce

1. Get email from sentry that there is a new issue
2. Click the "View in Sentry" button in the email

I now see the details of an issue and in the top left corner there is an arrow that should return me to the parent project. 

3. Click the arrow
4. I'm now in the wrong parent project. It seems that it returns me to the first project I have and not the correct one

### What you expected to happen

I'm in an issue for Project A. When pressing the arrow button, I expect to go to the overview of Project A and not a different project.

**Comment by BYK** [comment]
Guessing this is fixed. Let us know if it is still an issue for you.
