### ISSUE TITLE
ACTION REQUIRED: Remind me later not working

### ISSUE THREAD

**Issue by adamreisnz** [getsentry/sentry#13862]
![image](https://user-images.githubusercontent.com/490562/60425541-d8c5db80-9c46-11e9-8fab-6a84708dffaa.png)

This modal keeps popping up on EVERY page navigation, even when I try to change our plan. Clicking on Remind me later has no effect.

Can you please fix this, it is really obnoxious and distracting, and even preventing us from upgrading to a paid plan.

**Comment by BYK** [comment]
Have you reported this to support who can help you faster? Also is this still happening?

**Comment by BYK** [comment]
Closing due to lack of response from the author.

**Comment by adamreisnz** [comment]
What does this have to do with support? This is clearly a bug in your app, the modal keeps popping up even though I select REMIND ME LATER.

**Comment by BYK** [comment]
@adamreisnz if you are a paid customer the fastest and best way to get these prioritized and fixed is through support. Creating an issue here wouldn't help anyone as this part is on the SaaS codebase any way.

**Comment by adamreisnz** [comment]
I am not a paid customer yet, so I can't get that kind of support afaik. Our quote was exhausted due to a temporary spike in errors. If you don't want to look into it that's fine, but you are part of the Sentry team and even if you are working on a different codebase, I would imagine that you'd be able to pass this issue on to the relevant team for them to look at.

I won't be the only one experiencing it, and it's a really bad experience for anyone, paid customer or not, to have such a notification shoved in their face on every single page navigation.

The rule we follow with our app: if one customer/user reports it, there are at least 99 others who can't be bothered reporting it who are suffering the same problem.

**Comment by BYK** [comment]
@adamchainz we are already on this, the reason for closing the issue was due to lack of response from your end as I mentioned earlier. We are certainly not sweeping things under the rug as Sentry itself is for higher quality software :)

**Comment by adamchainz** [comment]
I think you @‘d the wrong Adam :)

**Comment by billyvg** [comment]
Fixed in https://github.com/getsentry/getsentry/pull/3139
