### ISSUE TITLE
Cannot find function entries in object function Object

### ISSUE THREAD

**Issue by OZZlE** [getsentry/sentry#13877]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

In Firefox v.64.0 there seems to be a javascript error that is actually caused by Sentry JS. We have gotten 1.5K events.

We use React and babel, jQuery, GTM.

We are running Sentry version 5.2.1

## Steps to Reproduce

Firefox Version: 64.0
Chrome version 71

The strange thing is that I have not been able to reproduce this issue in those browsers, but I keep seeing it reported in Sentry anyway.. 

    TypeError: Cannot find function entries in object function Object() {
        [native code]
    }.
      at ? (/5.2.1/bundle.min.js|_|/html/body/script[4]:2)

### What you expected to happen

No js errors caused by sentry js.

### Possible Solution
–

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
