### ISSUE TITLE
Documentation url can conflict with organization url

### ISSUE THREAD

**Issue by pzinovkin** [getsentry/sentry#1387]
Documentation lives at `http://host/docs/`
I've created an org with same name (slug) and instead of viewing it's dashboard I'm getting documentation.

It would be good to deny creation of orgs with conflicting slugs (docs, manage, account). Or move org dashboard to `/organizations/bla`

**Comment by dcramer** [comment]
We actually deny newly created orgs but we dont migrate previous orgs.

If this is on self-hosted, you can open up /admin/ and change the slug of the organization.
