### ISSUE TITLE
More configurable statsPeriod in the issues route

### ISSUE THREAD

**Issue by cedricyaal** [getsentry/sentry#13878]
## Summary

Hi,
In the route /api/0/projects/{organization_slug}/{project_slug}/issues/ there is a parameter statsPeriod. However I can not configure it other than  24h or  14d.
It would be much appriéciated if I could use 2d or 12h for example.

https://docs.sentry.io/api/events/get-project-group-index/

## Motivation

We have a important number of issues and a fine tune of this request would certainly help its performance

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
