### ISSUE TITLE
how to use sourcemap in android H5 app ?

### ISSUE THREAD

**Issue by webliving** [getsentry/sentry#13900]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]

## Description
Source code was not found 
how to use sourcemap in android H5 app ? file:///xxx/xxx/xxx.js

## Steps to Reproduce
![image](https://user-images.githubusercontent.com/3808577/60698418-d18e1e80-9f21-11e9-84a0-0d8d4fb5b380.png)

![image](https://user-images.githubusercontent.com/3808577/60698406-c0dda880-9f21-11e9-826b-a29a934de9bf.png)

### What you expected to happen

sourcemap is ok

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
