### ISSUE TITLE
7.1.2 not documented

### ISSUE THREAD

**Issue by frewsxcv** [getsentry/sentry#1391]
7.1.2 has been pushed to PyPi, yet there is no git tag for it, nor documented changes

**Comment by dcramer** [comment]
Looks like we forgot to push the tag. 
Generally we haven't been listing minor releases in the changelog but I could be convinced to change that. 






On Tue, Jan 20, 2015 at 2:34 PM -0800, "Corey Farwell" <notifications@github.com> wrote:












7.1.2 has been pushed to PyPi, yet there is no git tag for it, nor documented changes

**Comment by dcramer** [comment]
I lied about not noting minor versions (i thought we had decided to skip it). Going to add it now, but it's just a couple of migration fixes.
