### ISSUE TITLE
Filter by Lastseen is a profet?

### ISSUE THREAD

**Issue by OZZlE** [getsentry/sentry#13929]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description
![Skärmklipp 2019-07-09 15 50 29](https://user-images.githubusercontent.com/893783/60893671-a11bec80-a261-11e9-9114-add0c4295256.png)
So if I assume -1h is from last hour and -1w is for the last week, what the heck is +1d? Can Sentry predict the future and see what will happen the coming day? :D

### Possible Solution
Should is say -1d? I guess all should be either negative or positive, doesn't really make sense to me at least :P

**Comment by tkaemming** [comment]
This follows the same pattern as [`find(1)`](https://www.freebsd.org/cgi/man.cgi?find(1)):

>      All primaries which take a	numeric	argument allow the number to be	pre-
>      ceded by a	plus sign (``+'') or a minus sign (``-'').  A preceding	plus
>      sign means	``more than n'', a preceding minus sign	means ``less than n''
>      and neither means ``exactly n''.

So `+1d` means "more than 1 day ago", `-1d` means "less than one day ago."

**Comment by OZZlE** [comment]
OK :D Would it be possible to add so you can pick '-1d' also then? 

(Also I am not sure all users know the exact specs of find :P we only use Sentry to track js errors, e.g. fe-devs use it)

What about a info box explaining this also? Or it could say 'Last hour', '>=1 day ago', 'Last week'
