### ISSUE TITLE
Support webpack versioning

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1394]
"Webpack by default versions with the first 20 characters of a hash"

You can change the setting, but maybe we should update the JS version logic to support this as well since webpack is one of the three popular toolkits (and the one we're officially adopting).

**Comment by joshma** [comment]
Just FYI, the default is here: https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L39

**Comment by mattrobenolt** [comment]
We've been versioning static assets now since 8.0.
