### ISSUE TITLE
sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured

### ISSUE THREAD

**Issue by machenchn** [getsentry/sentry#13967]
## Important Details
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 28535)
spawned uWSGI worker 1 (pid: 28541, cores: 4)
spawned uWSGI worker 2 (pid: 28542, cores: 4)
spawned uWSGI worker 3 (pid: 28543, cores: 4)
02:24:23 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
02:24:23 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
02:24:23 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
WSGI app 0 (mountpoint='') ready in 37 seconds on interpreter 0x55b25602f0a0 pid: 28542 (default app)
WSGI app 0 (mountpoint='') ready in 37 seconds on interpreter 0x55b25602f0a0 pid: 28541 (default app)
WSGI app 0 (mountpoint='') ready in 37 seconds on interpreter 0x55b25602f0a0 pid: 28543 (default app)
How are you running Sentry?
python 
SENTRY_CONF=/etc/sentry sentry upgrade
or 
SENTRY_CONF=/etc/sentry sentry run web
* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description
worker can't get events
[What happened]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. and so on.

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration when relevant

### What you expected to happen

[What you think should be happening]

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by machenchn** [comment]
(sentry) root@misentry:/home/work/data/www# SENTRY_CONF=/etc/sentry sentry run worker
02:28:21 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.

**Comment by BYK** [comment]
Closing due to incomplete issue report. In the future I encourage you to try [the forums](http://forum.sentry.io/) first and open the issue on getsentry/onpremise if you are sure there is an issue with Sentry and not your configuration (or you think we can improve the defaults/docs).

**Comment by GWillmann** [comment]
If anyone stumbles upon this warning, you have to download a geoip database and tell Sentry where it is stored in the `sentry.conf.py` file for example:

```
GEOIP_PATH_MMDB = './GeoLite2-City_20191001/GeoLite2-City.mmdb'
```

If running Sentry with Docker, don't forget to rebuild the containers...

**Comment by OKNoah** [comment]
For Kubernetes users, we must create our own Docker image and host privately then?
