### ISSUE TITLE
Sentry.constants.RESERVED_ORGANIZATION_SLUGS needs updating

### ISSUE THREAD

**Issue by entrepreneurj** [getsentry/sentry#1397]
I recently discovered I was able to create an organisation called "docs" :)

Would it be better to manually update the RESERVED_ORGANIZATION_SLUGS constant whenever new url stubs (i.e. /docs, /api ) are created, or would it be better to implement something like the script below, i.e. a function that finds a set of the possible slugs where clashes could occur?

https://gist.github.com/entrepreneurj/2325edc4999828e939e6

**Comment by dcramer** [comment]
In all fairness I think automating the constant would be good but we don't change top level urls too often.
