### ISSUE TITLE
Assigning tags in python

### ISSUE THREAD

**Issue by gbreeze** [getsentry/sentry#13973]
HEy, i do this:

``` python
import sentry_sdk
import logging

logger = logging.getLogger('test')
sentry_sdk.init("...")
```

``` python
from sentry_sdk import configure_scope

# 1
with configure_scope() as scope:
    scope.set_tag('task', 'x2')
    logger.exception(Exception('test exception x2'))

# 2
logger.exception(Exception('test exception x1'), extra={'tags': {'task':'x1'}})

# 3
logger.exception(Exception('test exception x0'))
```

\# 1:
 - Assignment is fine, i have the tag 'x2' in the Sentry UI.

\# 2:
 - Wrong assignment, should be 'x1' (is x2)
 - No assignment if I execute this single line only.

\# 3:
 - Wrong assignment, should be NONE (is x2)

hm...

**Comment by untitaker** [comment]
We don't set tags through loggers anymore (all that stuff lands in additional data at the bottom now). If you want a tag, set it through `configure_scope`. If you want a tag for a single line, wrap that line like this:

```python
with push_scope() as scope:
    scope.set_tag("task", "x2")
    logger.exception(...)
```

`push_scope()` resets the tag after getting out of the with-statement.

You can find the rationale for this difference to raven here: https://github.com/getsentry/sentry-php/pull/844#issuecomment-510120197

Hope that clears things up. If you have any follow-up questions please use StackOverflow or open a ticket at https://github.com/getsentry/sentry-python
