### ISSUE TITLE
Cannot add repository for large org

### ISSUE THREAD

**Issue by IndicatorFluid** [getsentry/sentry#13993]
Sentry 9.1.1 on premise.

It seems it's impossible to add a repository via github integration if the organization in question has over 100 repositories, and the repo you are trying to add lexically sorts after the 100th element.

The problem comes from https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/github/client.py#L53.

The UI has a search feature, but it's all client side (verified there is no ajax requests from the browser as the search term changes), so you can only search within the first 100 repos.

Sorry this does not adhere to the template, it seems something in the template was triggering the corporate browsing filter.

There are 2 workarounds:
1. Instead of allowing sentry access to all repos, limit to the repos you want it to be able to access to
2. Use curl to add them:
```
curl -H 'Authorization: Bearer XXX' 'https://sentry.company.net/api/0/organizations/org_name/repos/' -H 'content-type: application/json' --data-binary '{"installation":"XXX","identifier":"XXX","provider":"integrations:github_enterprise"}'
```

There are two ways to fix this:
1. Fetch all repos instead of a 100
2. Wire the search to work with the backend

**Comment by IndicatorFluid** [comment]
Replacing get_repositories with this seems to fix it:
```
    def get_repositories(self):
        page = 1
        repositories = []
        while True:
            repos = self.get(
                '/installation/repositories',
                params={'per_page': 100, 'page': page},
            )['repositories']
            repositories.extend(repos)
            if len(repos) < 100:
                break
            else:
                page += 1
        return repositories
```

**Comment by manuzope** [comment]
This should be fixed on the latest Sentry. The frontend search has been wired to send an AJAX request to the backend. Closing this issue, but feel free to re-open if it doesn't work for you.
