### ISSUE TITLE
Error when using pip install -U sentry[postgres]

### ISSUE THREAD

**Issue by jeanfrancis** [getsentry/sentry#1399]
I have the below error when using pip install -U sentry[postgres]

Error: pg_config executable not found.

    Please add the directory containing pg_config to the PATH

    or specify the full executable path with the option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-hq8W1d/psycopg2

**Comment by entrepreneurj** [comment]
Out of interest, what kind of operating system do you have and is Postgres already installed? Also, if you have installed Postgres, was it from the source, or from a pre-existing package/executable?

**Comment by jeanfrancis** [comment]
Ubuntu Utopic (14.10) yes postgres is already installed from sources

**Comment by entrepreneurj** [comment]
And have you installed "libpq-dev"?

**Comment by dcramer** [comment]
As mentioned above you'll need libpq-dev for the psycopg2 package.
