### ISSUE TITLE
Add Frequency to Rules

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1400]
Right now rules can be a bit too aggressive and fairly annoying in a couple of cases.

For example, if you say "I want to be notified when an event happens more than 50 times per minute". How often do you want notified? We implemented a hard limit of every 30m, but that's not ideal.

There's several frequency variables I think we can provide by default:

- Every X minutes/hours
- Every time the rule matches -- this might be able to replace the "every event" condition)
- When the state of the rule changes -- this might need a better description, but really this is the behavior we want for frequency rules. Ideally the frequency rule would do this either way by default.

Frequency conditions would likely be a third category after actions and would cause the rule to happen on *any* of the frequency terms.

Right now there is a "last_active" column on GroupRuleStatus which will allow us to handle basic frequency. To handle the "state of the rule has changed" we need to expand the API. The problem with the event frequency rule is that the state changes whenever the rule's ``passes`` call changes. That call checks "rule_is_active" so it changes immediately which causes the rule to re-fire. What we really want is a "can rule execute" and "does rule pass". The "can rule execute" would check frequency, or in this case "has the rate limit gone below what it needs to be, or is the rule's state inactive".

**Comment by ashwin31** [comment]
+1

**Comment by mcuelenaere** [comment]
One useful feature to have, would be to say to trigger a rule based on eg. if "an event is seen by more than {x} distinct {user.id} instances in {y} minutes".

We are seeing some JS events that trigger an "if event is seen more than 100 times in 1 minute" rule quite often, even though this is a single user inadvertently sending the same exception/warning over and over.
