### ISSUE TITLE
how to login Sentry

### ISSUE THREAD

**Issue by lixiaoabc** [getsentry/sentry#14005]
when I  install sentry,I don't creat a user
Would you like to create a user account now? [Y/n]: n

then how to login sentry,Only login without registration

**Comment by CBEPX** [comment]
sentry createuser --email={{ sentry_admin_user }} --password={{ sentry_admin_password }} --superuser

**Comment by lixiaoabc** [comment]
> sentry createuser --email={{ sentry_admin_user }} --password={{ sentry_admin_password }} --superuser
I want to create a default username password that does not interact with the virtual machine.
Where does the username password exist?Can I create a username password through a configuration file?

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
