### ISSUE TITLE
Sentry U2F authentication fails with YubiKey (mismatched Challenge), but ok with Off-brand u2f stick

### ISSUE THREAD

**Issue by mastacheata** [getsentry/sentry#14018]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Sentry won't let me login using my Yubikey U2F Key, but registering works just fine.
Also logging in with another "off-brand" U2F-Key by Feitian works just fine.

## Steps to Reproduce

1. Set up YubiKey from the Github/YubiCo Partnership a few years back as 2FA Key
2. Sign out of sentry
3. Sign in again and wait for the U2F challenge
4. Tap YubiKey when asked to
5. Get a wrong challenge error (sentry/models/authenticator.py in validate_response at line 578)

Trying the same procedure with my Feitian Key works just fine.

This is the full error message:
```
Wrong challenge! Was: 'p\xf3~\xb0\xbe\xad\x1cA0\x04\x02\xf2\xffOb\xc08\x92\x93\xc6\xaa!6H\xb7\xff\x87n\xa6!%\x99', expecting: '\x928\x93\x96s\x0c\xcb\xd7\xeb\x05o\x11\xe0S|\xd5\x05\xcf\x15\xa2)\x81l\xf7\xbb\xeef\x0b)\xb7/='
```

Or in human readable format:
Challenge received was `u'cPN-sL6tHEEwBALy_09iwDiSk8aqITZIt_-HbqYhJZk'`
Challenge expected was (impossible to copy that without butchering it): `'8sË×ëoàS|ÕÏ¢)l÷»îf)·/='`

See the screenshot below:
![sentry-error-u2f pnfg](https://user-images.githubusercontent.com/716261/61252825-2f5f0980-a75f-11e9-8b7e-e8bfa53ccfda.png)

Is it normal, that the expected challenge seems to be a "normal" string and the received challenge is a unicode string?

### What you expected to happen

The U2F Key should be accepted and let me pass through the sign in. (I just signed it up a minute ago)

### Possible Solution

Sorry, no ideas on how this could've happened or what might cause this.

**Comment by BYK** [comment]
This may be due to your server clock not being correct. Have you checked this?

**Comment by mastacheata** [comment]
```
# date
Wed Jul 24 13:20:58 UTC 2019
```
^^ Looks correct to me.

**Comment by malexmave** [comment]
Do you have two Yubikeys in your account and is the GitHub-branded one the second? I think this may be an instance of #14656, and not the other way around. See [my debugging steps described  in the other issue](https://github.com/getsentry/sentry/issues/14656#issuecomment-562105868).

**Comment by mastacheata** [comment]
Oooh, interesting find.
No matter which U2F keys I use, I can only ever use the first one added to log in.
Sentry sends the correct challenges/keyIds for all registered keys as Windows knows if a key plugged in is registered or not. The problem seems to be matching the correct challenge and response together.

I guess we can close this issue and continue the bug hunt in that other issue as that's a more correct description of what is happening.
