### ISSUE TITLE
Slack integration: create alert rules based on issue owner

### ISSUE THREAD

**Issue by aommm** [getsentry/sentry#14028]
## Summary

Should be able to send configure slack alert rules based on who is the issue owner.

## Motivation

Our setup:
We use the "issue owner" concept in sentry to automatically assign issues to different Sentry teams.
Each team has their own channel in Slack.

Our wish:
If a new bug comes in that belongs to team XYZ (according to the alert rules we have set up), then a slack message should be sent only to the slack channel #team-xyz-bugs.

## Additional Context
In the "issue owners" docs [here](https://docs.sentry.io/workflow/issue-owners/), it is mentioned that
> Note that at this time the Issue Owners feature is only available for email notifications.

So this seems like a known limitation. We'd love to know if this will be addressed sometime in the near future, or if we ought to change some other part of our workflow.

Cheers!

**Comment by caleb15** [comment]
This would be useful for us too. As I mentioned in https://github.com/getsentry/sentry/issues/8654#issuecomment-541982002 this could be done if issue owner was a tag. Although that assumes alert rules run *after* issue owner rules :thinking:

**Comment by shcallaway** [comment]
This would be incredibly useful for my team.

**Comment by aommm** [comment]
This might be fixed now? When editing an Alert Rule, it is now possible to filter on issue assignee:
![image](https://user-images.githubusercontent.com/1434425/97275683-872b6200-1836-11eb-976b-95eacde2f0ac.png)

**Comment by BYK** [comment]
@aommm - thanks for the follow up! Closing the issue then. Feel free to come back and add a comment if you decide this is not finished yet.

**Comment by caleb15** [comment]
@BYK do you know if alert rules run after issue owner rules?

**Comment by BYK** [comment]
@caleb15 sorry, not my area of expertise. Maybe @adhiraj or @scefali knows?

**Comment by adhiraj** [comment]
Yep, alert rules run after owner rules.

**Comment by AlexanderRydberg** [comment]
@BYK Is this available on prem also ?

**Comment by BYK** [comment]
@AlexanderRydberg it should be via Metric Alerts.

**Comment by AlexanderRydberg** [comment]
I cant seem to find it in Metric Alerts nor Issue Alert. The latter tho looks like it should contain If condition option by judging from the screenshot. But not here :/

**Comment by BYK** [comment]
@AlexanderRydberg what's the version you are using?

**Comment by AlexanderRydberg** [comment]
Test env: 20.11.1 4468076
Prod env: 20.11.0 eb42277

**Comment by BYK** [comment]
Do you have this change applied to your local config: https://github.com/getsentry/onpremise/pull/735/files#diff-f4bf6cddc34b3c80a2bb2497a46d5e7315424593993d0ce41ab7c48064ba165c

**Comment by AlexanderRydberg** [comment]
Yes. Did that misstake once, not merging config-example with my config.
In this case it is the same as the examples.
Just as another note, I also did a post on the forum https://forum.sentry.io/t/alert-based-on-issue-owner/11902 but I grew impatient. :D

**Comment by AlexanderRydberg** [comment]
https://docs.sentry.io/product/alerts-notifications/issue-alerts/ doc says that Issue Alert should have If condition. Mine doesnt

**Comment by BYK** [comment]
@AlexanderRydberg sorry we missed your forum post. Let's continue there.
