### ISSUE TITLE
Manage quicklinks empty

### ISSUE THREAD

**Issue by uhlhosting** [getsentry/sentry#14043]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/6324047/61329275-364c5180-a81d-11e9-931c-6f99af7f3d9c.png">

like is seen in the image the only available menu is /manage the quicklinks are blank. wonder what there should be, or what can cause this.

**Comment by BYK** [comment]
Can you try this with 9.1.2 as there were some fixes related to this?

**Comment by uhlhosting** [comment]
Just upgraded to 9.1.2 yet havent looked indeed will give it a try. Thank you!

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
