### ISSUE TITLE
Resolving or Ignoring issue returns 400

### ISSUE THREAD

**Issue by nbarbettini** [getsentry/sentry#14054]
## Important Details

How are you running Sentry?
* Saas (sentry.io)

## Description
I have two projects in my Developer Plan organization, for backend and frontend apps separately. I set up logging on the backend project and streamed a few issues in. When I try to resolve or ignore them, I can't.

When clicking either button:

![image](https://user-images.githubusercontent.com/7525482/61381898-9b756680-a860-11e9-91ce-e9c91f63a0b0.png)

![image](https://user-images.githubusercontent.com/7525482/61381853-88629680-a860-11e9-8311-39c71b5448f0.png)

I've tried refreshing, signing out and back in, etc.

## Steps to Reproduce

1. Create a second project
2. Try to Resolve or Ignore an issue

**Comment by nie7321** [comment]
Support just told me it's fixed, and indeed it is working again for me!

Looks like this PR fixed it: https://github.com/getsentry/sentry/pull/14058

**Comment by dashed** [comment]
@nbarbettini can you confirm if this is working again?

**Comment by nbarbettini** [comment]
Confirmed, thanks for the ultra quick fix! If it occurs again I'll reopen.
