### ISSUE TITLE
operating system in sentry issue is the server OS not browser OS

### ISSUE THREAD

**Issue by runawaycoin** [getsentry/sentry#14053]
Hi, 

In version 2.1.0, the reported OS details to sentry is for the server. Previously wasn't this the client (browser) and parsed from the user-agent?

Its confusing in sentry dashboard as the browser name and version are shown alongside the server OS - where the browser OS would be more useful.

![image](https://user-images.githubusercontent.com/26024569/58908510-aa68e500-8708-11e9-95d4-d677714a6bd4.png)

**Comment by untitaker** [comment]
I actually think this might be fixed now. There was a lengthy thread in the PHP SDK that I can't find anymore, but the TL;DR is that we now write the User-Agent into `client_os` key if `os` is already set, and the UI adapts accordingly.
