### ISSUE TITLE
Is there an example of collect incomming emails?

### ISSUE THREAD

**Issue by whilgeek** [getsentry/sentry#1407]
The sample configuration [here](http://sentry.readthedocs.org/en/latest/quickstart/nginx.html#proxying-incoming-email) is a little too simple. I wonder is there a best practice of using incomming emails as the input? Such as which address the receiver is?

Thanks.

**Comment by dcramer** [comment]
Let me push our mailgun code into Sentry's public repo real quick. It's a lot easier to deal w/ than Nginx/etc.

**Comment by mattrobenolt** [comment]
@whilgeek fwiw, you can just bind the smtp server to port 25 as well if you just wanted to run it. We don't have this documented well since we don't use it and is more complicated in our setup anyways. If you have Sentry running ona  single web server, you don't need nginx in front.

**Comment by mattrobenolt** [comment]
So you should be able to just configure http://sentry.readthedocs.org/en/latest/config/index.html#smtp-server, and then `sentry start smtp`. If you bind to 25, which you'll need to to get email from the public, then you'll obviously need sudo.

**Comment by whilgeek** [comment]
@mattrobenolt @dcramer  Thanks for the prompt replies, I just did not know who is the mail receiver until reading the source code. It seems like the address should be like teamname@sentryservername.

**Comment by mattrobenolt** [comment]
@whilgeek Well, you'd need an MX record for whatever domain you want to send mail to. And this is really intended only for email replies, and the `Reply-To` header gets filled in properly automatically. So you don't need to worry about the address to send messages to on your own.

Does that make sense?

**Comment by whilgeek** [comment]
Thanks and I have set the MX record, but when I telnet localhost 1025, I found it not open.
So how to start the sentry smtp server?

**Comment by dcramer** [comment]
@whilgeek ``sentry start smtp``

**Comment by dcramer** [comment]
@whilgeek I think you're misunderstanding what email is for. The inbound mail processor is purely so people can reply to notifications and we coordinate those replies into activity events.

**Comment by dcramer** [comment]
Ref 2aeb0df8bad2f0265e16870919c83ab0fa986478

**Comment by dcramer** [comment]
http://sentry.readthedocs.org/en/latest/inbound-mail/index.html

**Comment by whilgeek** [comment]
@dcramer Aha? I think it is like the imap [plugin in Logstash](http://logstash.net/docs/1.4.2/inputs/imap) so that the sentry can collect error log via email. The advantage of this is that when server is down or the network is down, the error log will stuck in the task queue and can be sent later.

Thanks all the same.
