### ISSUE TITLE
Sentry 9.1.1 is not send email 

### ISSUE THREAD

**Issue by lixiaoabc** [getsentry/sentry#14071]
this is my config.yml

```
mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
 mail.host: 'smtp.mxhichina.com'
 mail.port: 25
 mail.username: 'fenghaichun@deepexi.com'
 mail.password: 'Feng0502@'
 mail.use-tls: true
# The email address to send on behalf of
 mail.from: 'fenghaichun@deepexi.com'
```

when i send email the log is 

Temporary failure in name resolutionf

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.

Please also provide as many details as you can. This particular issue seems like a problem with your DNS.
