### ISSUE TITLE
GitHub Integration: 

### ISSUE THREAD

**Issue by benoror** [getsentry/sentry#14072]
Zendesk Request: 22687

On June 26th I created a new Sentry account and transferred the project from Heroku to have all the environments together in a single paid plan.

I'm getting this error message when trying to add Github integration:

![5ab506f4-b00f-4cb3-aa77-bbc764fdcf17](https://user-images.githubusercontent.com/119117/61481212-e2448880-a954-11e9-934f-24756429b7f1.png)

Full details in Zendesk request: 22687

**Comment by sebasjm** [comment]
I'm having the same issue

**Comment by benoror** [comment]
Update: Got contacted by support. Seems to be a mismatch between the Github user and a legacy user related to the Heroku account...

**Comment by sebasjm** [comment]
Thanks! No contact from support here but I have tried again and it worked. Silent fix detected :smile:

**Comment by benoror** [comment]
Worked on my side as well!
