### ISSUE TITLE
Sentry mail without username and password (reset mail settings)

### ISSUE THREAD

**Issue by keros** [getsentry/sentry#14086]
## Important Details

How are you running Sentry?

Ubuntu 18.04
Installed from pip
Started with systemd

## Description
1.) Set mail configuration via gui (smtp, mailserver, username, password, ...).
2.) We need to change to a local Mailserver without authentication (exim4)
3.) Set in `/etc/sentry/config.yml` the following:
```
mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'localhost'
mail.port: 25
mail.username: ''
mail.password: ''
mail.use-tls: false
system.admin-email: 'admin@mydomain.com'
```
4.) Sent test E-mail -> `SMTP AUTH extension not supported by server`

The Problem ist that I can not overwrite the username and the passwort that was set previous in the gui with nothing.
If I go to `Admin -> Mail` I see the old values in `username` and `password`, but there should be `not set`.

I tried to find the "old" values in the database, but can't find anything there.
I also greped in the "/www" folder for this values and find nothing.
Where are this values stored?
How can I reset them to "nothing"?

**Comment by BYK** [comment]
I think this was an issue with the initial setup wizard in Sentry 9.1.1 which is fixed in 9.1.2 released yesterday. Are you able to try with that?

**Comment by keros** [comment]
Thanks for the help

Just updated to 9.1.2 with the same result.
The Webinterface shows me still the old values for username and password.
If I try a test mail the same error comes up (`SMTP AUTH extension not supported by server`)

**Comment by BYK** [comment]
Oh wait, my bad for misunderstanding the issue. As far as I know, when you enter a value from the UI, they are persisted in the DB. I'm guessing the UI doesn't allow empty values?

**Comment by keros** [comment]
Hmm I made a DB dump and searched for the values so I can delete them, but I could not find anything.
Does the system maybe store this data not in plaintext?

I have a second sentry installation where I never added username/password for the mailserver config in the web ui. On this system (9.1.1) everything runs fine with the local exim4 noatuh config.
So empty values should be ok, but If you fill them one times I can not find out how to get them empty again.

**Comment by yydzxz** [comment]
> If you fill them one times I can not find out how to get them empty again.  
me too. 😢

**Comment by BYK** [comment]
I'll try to get to this but if anyone wants to give it a try, it should not be too complicated and I'm happy to assist them in the process.

**Comment by BYK** [comment]
@keros - although this is fixed on master now, I'm not sure if we're gonna do a 9.1.3 release with this patch in soon. :(

**Comment by keros** [comment]
@BYK Thanks for the patch.
I solved the problem with an workaround. So I don't need a fast solution for it.
But its nice that we can overwrite the GUI data now with the config file, even with nothing.
