### ISSUE TITLE
Jira Server Integration: Does it work with on-premise sentry ?

### ISSUE THREAD

**Issue by HIMANSHU-ELIGIBLE** [getsentry/sentry#14100]
I tried the installation instruction at https://docs.sentry.io/workflow/integrations/global-integrations/#jira-server but the step after OAuth setup redirects the page to sentry.io and nothing happens. 

Traditionally, we have been using project level integration but was suggested to use org wide plugins after the auth stopped working suddenly -  https://github.com/getsentry/sentry-plugins/issues/491

**Comment by markstory** [comment]
The Jira Server integration should work with on-premise sentry. You will need to substitute `sentry.io` with your sentry hostname in the OAuth setup steps though.

**Comment by AudriusButkevicius** [comment]
We have it setup on prem with an on prem jira server, so I am sure it works  in 9.1.1 atleast.

**Comment by BYK** [comment]
Please use [our forums](http://forum.sentry.io/) for questions like these in the future as the issue board is only for the core Sentry code-related issues. Integrations category seems like the right fit for this one.
