### ISSUE TITLE
Oops! Something went wrong in Docker Toolbox

### ISSUE THREAD

**Issue by vonlyyou** [getsentry/sentry#14113]
![image](https://user-images.githubusercontent.com/20806458/61685839-74cb9a00-ad50-11e9-8ec2-cbccddc2f26e.png)

use docker toolbox installed sentry

1. git clone https://github.com/getsentry/onpremise.git
2. cd onpremise
3. docker volume create --name=sentry-data && docker volume create --name=sentry-postgres
4. cp -n .env.example .env
5. docker-compose build
6. docker-compose run --rm web config generate-secret-key
7. vim .env and SENTRY_SECRET_KEY = generate-secret-key
8. docker-compose run --rm web upgrade
9. docker-compose up -d
10. docker-compose ps

run http://192.168.99.100:9000/auth/login/

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
