### ISSUE TITLE
Search event.timestamp throws internal error on tags

### ISSUE THREAD

**Issue by blodone** [getsentry/sentry#14114]
On-Premise docker [Version 9.1.1]

When filtering with a query like this:
is:unresolved event.timestamp:>=2016-01-02T01:00:00 event.timestamp:<2016-01-02T02:00:00 
an internal error is thrown at

sentry/tagstore/legacy/backend.py in get_event_tag_qs at line 759

```
NotImplementedError: null
  File "sentry/api/base.py", line 90, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "sentry/api/base.py", line 190, in dispatch
    response = handler(request, *args, **kwargs)
  File "sentry/api/endpoints/project_group_index.py", line 185, in get
    cursor_result, query_kwargs = self._search(request, project, {'count_hits': True})
  File "sentry/api/endpoints/project_group_index.py", line 88, in _search
    result = search.query(**query_kwargs)
  File "sentry/utils/services.py", line 91, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "sentry/search/django/backend.py", line 404, in query
    paginator_options, search_filters, **parameters)
  File "sentry/search/django/backend.py", line 436, in _query
    value=environment.name,
  File "sentry/utils/services.py", line 91, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "sentry/tagstore/legacy/backend.py", line 759, in get_event_tag_qs
    raise NotImplementedError  # there is no index that can appopriate satisfy this query
```

**Comment by BYK** [comment]
Can you try 9.1.2 which was released yesterday and see if it fixes your issue?

**Comment by blodone** [comment]
Hi, with 9.1.2 the error is still there

**Comment by BYK** [comment]
@blodone ack. will give this a looks soon

**Comment by mirzap** [comment]
I also can confirm this happening on 9.1.2. I get the same err when filtering, eg: `event.timestamp:>=2019-07-23T19:27:00`

**Comment by Padamja** [comment]
I will like to take this up. @BYK

**Comment by BYK** [comment]
@Padamja sounds good to me! Not sure if this happens on master but feel free to use the [on-premise repository](https://github.com/getsentry/onpremise) to get started. Also, @blodone's [comment](https://github.com/getsentry/sentry/issues/14114#issuecomment-515942510) suggests that this may have something to do with the Java SDK but the backend should still recover from this (at least by rejecting broken events).

**Comment by PaarthB** [comment]
@BYK I am also getting the same issue on NodeJS and JavaScript projects for 9.1.2

**Comment by JiDW** [comment]
Same issue for PHP projects.
