### ISSUE TITLE
Unable to reach Sentry log server

### ISSUE THREAD

**Issue by robpal** [getsentry/sentry#1412]
Raven can't access sentry log server, what could be wrong ?

This error message : 
```
Client configuration:
  servers        : ['http://sentry.bbet.info/api/store/']
  project        : 3
  public_key     : exx3xxaxx3xx4xxfxxfxx5xxdxxcxx2x
  secret_key     : 6xxbxx5xxfxx4xxdxxcxx6xxfxxcxx8x

Sending a test message...
Unable to reach Sentry log server: HTTP Error 500: INTERNAL SERVER ERROR (url: http://sentry.bbet.info/api/store/, body: )
```

I'm runing server with ``sentry --config=sentry.conf.py start`` and in settings I've ``SENTRY_WEB_HOST = '0.0.0.0'`` ``SENTRY_WEB_PORT = 80``

**Comment by dcramer** [comment]
It's returning a 500, which means the Sentry server itself is erroring. You'll need to check the logs of the server.
