### ISSUE TITLE
`culprit` field is not overriden

### ISSUE THREAD

**Issue by jaseemabid** [getsentry/sentry#1414]
A web app served with Python gunicorn and gevent will have almost all of the
culprit fields set to `gevent.greenlet in run`, making it pretty useless. I
tried to override one of those exceptions with an additional fields and looks
like it didn't get overridden correctly.

    log.exception("Testing exceptions", extra={'culprit': 'my.killer.view.test'})

The raw JSON shows the data correctly in the extras section. 

     extra: {
        function: "'ping_view'",
        culprit: "'my.killer.view.test'",

How should I proceed? 

Versions in use: Python raven 4.2.0, Sentry 7.1.4

**Comment by jaseemabid** [comment]
By the way, the example is from raven-python docs.

```js
logger.error('There was some crazy error', exc_info=True, extra={
    # Optionally you can pass additional arguments to specify request info
    'culprit': 'my.view.name',

    'data': {
        # You may specify any values here and Sentry will log and output them
        'username': request.user.username,
    }
  })

**Comment by dcramer** [comment]
Confirmed this is not broken in current release of raven-python
