### ISSUE TITLE
slow cleanup task because of sorting by non-indexed field

### ISSUE THREAD

**Issue by will-** [getsentry/sentry#14146]
Hi, I was running `cleanup` task and found it very slow to cleanup `sentry_eventmapping` .
Actually, `date_added` wasn't indexed.

https://github.com/getsentry/sentry/blob/525c9c71de21b890d90bea8e39cbee6423686568/src/sentry/runner/commands/cleanup.py#L179
Is `order by "date_added" desc` necessary?
related issue: #5882

**Comment by BYK** [comment]
Closing this issue due to staleness. This model doesn't exist anymore.
