### ISSUE TITLE
Slack Integration: 

### ISSUE THREAD

**Issue by JSekhon321** [getsentry/sentry#14170]
not able to install slack app due to auth error. I have 2 browser windows open, one where i am logged into our sentry site and other i am logged into our slack organization as admin.

**Comment by EvanPurkhiser** [comment]
Have you followed the instructions here? https://forum.sentry.io/t/how-to-configure-slack-in-your-on-prem-sentry/3463

**Comment by BYK** [comment]
Closing this issue in favor of the forum thread. Please continue there if you still have issues.
