### ISSUE TITLE
Feature: Email Icon displayed based on status of Event

### ISSUE THREAD

**Issue by dlamotte** [getsentry/sentry#1419]
Just had an idea that I thought I'd share.  After cleaning up some old Sentry errors in my inbox, I realized I had to _go_ to Sentry to figure out if the error was resolved by someone else on the team.  If I was out for a while, it'd be nice to get some kind of status in the email so I could just remove already resolved incidents.

So I was thinking that the email could embed some image that would be served up differently based on the status of the event (resolved or not).

ie: event/<id>/status.png

Hopefully this is clear.

**Comment by mattrobenolt** [comment]
Clever idea, but pretty sure this won't work since most email providers will proxy and cache the image so it won't update dynamically. Is there a service that already does something similar to see what they do, or was this purely an idea?

**Comment by dlamotte** [comment]
Purely an idea as I was cleaning up my inbox after not checking it for a while.  No big deal.

Makes sense that email providers would do that.  Kind of wonder if Cache-Control headers would help prevent that?  (pray that they're compliant http clients instead of just caching them permanently regardless)

You sound like you have the most experience in this area though, so feel free to close this if you don't think it'll work.  Just seemed like a pretty convenient/useful/easy feature if it were to work.

**Comment by dcramer** [comment]
Going to close as wontfix due to caching behavior making this unreliable
