### ISSUE TITLE
[Feature]Error reporting switches should be added to each release on the client side.

### ISSUE THREAD

**Issue by Leowuqunqun** [getsentry/sentry#14200]
## Summary

Error reporting switches should be added to each release on the client side.  
Mainly used in Ios and Android

## Motivation

We don't want to collect all the time. When we receive the problem, we will immediately fix it in the new version and close the report of the old version after a period of time, which can reduce the flow of the client and provide a good user experience.

## Additional Context

nothing

**Comment by markstory** [comment]
How would sentry help with providing feature switches in your applications?

**Comment by Leowuqunqun** [comment]
> How would sentry help with providing feature switches in your applications?

Can you show the release switch in the web interface?

**Comment by markstory** [comment]
Wouldn't switches in sentry require your applications to make additional requests to sentry to check whether or not they submit errors? This also sounds like scenario you could handle in your applications.

**Comment by Leowuqunqun** [comment]
> Wouldn't switches in sentry require your applications to make additional requests to sentry to check whether or not they submit errors? This also sounds like scenario you could handle in your applications.

Of course, it can be controlled in the program, and what I want to do better is to make these switches in the web, so as to facilitate management. My current strategy is to write a json file to record the version of the switch, and ask the APP to call the interface when starting to determine whether the version needs to turn on the switch to report errors

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
