### ISSUE TITLE
How to write notification plugin with v2 interface?

### ISSUE THREAD

**Issue by eagletmt** [getsentry/sentry#1421]
I started to use v2 plugin interface to integrate with notification rules.
But I got `type object 'HipchatNotifier' has no attribute 'slug'` .

Are there any examples or documentation for writing a Notifier?
My source code is here https://github.com/eagletmt/sentry-notify-hipchat/blob/c78292b39719834aabf84ab3abebac0d6952b532/sentry_notify_hipchat/plugin.py .

**Comment by dcramer** [comment]
This is now technically possible via get_notifiers, but I dont believe we're actually using it anywhere yet.

Effectively it requires you to extend get_notifiers to return a subclass of Notifier.
