### ISSUE TITLE
Asterisk in sentry search on webapp doesn't work

### ISSUE THREAD

**Issue by linapb** [getsentry/sentry#14224]
Example:
level:warning  - works fine
but
level:warn*  or level:"warn*"  - don't work.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by Bessonov** [comment]
@BYK still interested in this feature.

**Comment by BYK** [comment]
@Bessonov just got word that this is something we support now. Have you tried this on sentry.io?
