### ISSUE TITLE
Clearing incoming error "queue" for MySQL

### ISSUE THREAD

**Issue by vbjordan** [getsentry/sentry#1423]
Hi,

I am using MySQL for storage with memcached turned on (buffers are not turned on, yet) and it looks like the workers are trying to write a load of messages that occurred over the last several days. MySQL is deadlocking in response and the load on the server is quite high.

I'm wondering how I can purge the incoming queue of errors for this. Doesn't seem to be anything from the command line, also tried to delete-all from memcached using nc. Sentry and MySQL both restarted but the load comes right back up when the services are restarted.

Any help would be greatly appreciated...

**Comment by dcramer** [comment]
It depends on what queue you're using. If this is old Sentry you need to flush the djkombu tables (or something along those lines), if it's newer, you're likely using Redis or RabbitMQ.

That said, please use the mailing list or IRC for questions, as the issue tracker generally isn't a good place for this.

**Comment by vbjordan** [comment]
Thanks for the response, I'll check IRC and mailing list next time
