### ISSUE TITLE
Change error and fatal error level colors in the list of events

### ISSUE THREAD

**Issue by ninniuz** [getsentry/sentry#14248]
## Summary

`error` and `fatal` error level colors are very similar.

## Motivation

Those two colors are very similar to each other, making it difficult for the dashboard user to quickly distinguish between those two error levels.

## Additional Context

This is a screenshot from Sentry 9.1.1.

The first one is an event with `error` level and the second one has `fatal` level. It is very difficult to distinguish them at first glance.

<img width="52" alt="Schermata 2019-08-01 alle 17 45 35" src="https://user-images.githubusercontent.com/3646303/62310199-4739cb80-b489-11e9-88f1-cc74f5896fc5.png">

**Comment by BYK** [comment]
I think @priscilawebdev addressed this recently so closing. Please reply back if you think this still needs work.
