### ISSUE TITLE
Using cache busting makes the "same" errors appear as separate entries

### ISSUE THREAD

**Issue by joacim-boive** [getsentry/sentry#14247]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [X] Other [briefly describe your environment]

Using self hosted Sentry 9.1.1 on AWS:
https://aws.amazon.com/marketplace/pp/B07JJDVVNJ

## Description

We use cache busting for our JS files and the approach is to add a timestamp to the filename: /js/bundle.app.4185d9aade26cd3a6285.js

This means that on each deploy we have a new unique name for bundle.app.

This means that the same error at different times appears multiple times in the list, when it should only be listed once:
![Screenshot 2019-08-01 at 14 27 08](https://user-images.githubusercontent.com/270235/62293321-a509eb80-b468-11e9-8ce3-66b6b8292dc9.png)

## Steps to Reproduce

Use a common approach for cachebusting your files. :)

### What you expected to happen

I expect it to keep the same errors grouped regardless of the time stamp in the filename.

### Possible Solution

Maybe a setting to ignore part of a filename using a regex.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

This may help you: https://docs.sentry.io/platforms/javascript/data-management/event-grouping/grouping-enhancements/
