### ISSUE TITLE
UnicodeDecodeError Notification

### ISSUE THREAD

**Issue by kikimor** [getsentry/sentry#1424]
Notifications that contain Cyrillic is not sent:

```python
[ERROR] Error processing 'rule_notify' on 'MailPlugin': 'ascii' codec can't decode byte 0xd0 in position 71: ordinal not in range(128)
Traceback (most recent call last):
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/plugins/bases/notify.py", line 59, in rule_notify
    self.notify(notification)
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/plugins/sentry_mail/models.py", line 187, in notify
    context=context,
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/plugins/sentry_mail/models.py", line 46, in _send_mail
    subject='%s%s' % (subject_prefix, subject),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 71: ordinal not in range(128)
```

I fix it as follows:
```python
subject='%s%s' % (subject_prefix, unicode(subject, 'utf-8')),
```

**Comment by mitsuhiko** [comment]
That sounds odd.  What's your subject prefix set to?

**Comment by mitsuhiko** [comment]
Just for the record: the string is supposed to be in unicode, but for some reason your subject prefix is not.  Maybe you set this to a string containing cyrillic letters in your config?  If that's the case you need to add a leading `u` prefix.

**Comment by kikimor** [comment]
Notification prefix: '[Sentry]'

sentry.conf.py:
```python
# -*- coding: utf-8 -*-
...
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": u'CN=ОЭУС,OU=OEUS,OU=IT,DC=ad,DC=is74,DC=ru',
}
...
```

On default config i have a similar problem.

**Comment by mitsuhiko** [comment]
I'm confused now.  Is the prefix `'[Sentry]'`?  Can you verify that this issue occurs with the given prefix?  (Also which version of Django are you using).

**Comment by mitsuhiko** [comment]
In the line of code quoted in your traceback an unicode coercion happens between a unicode string (the right one, which should be unicode) and the left one (which also should be unicode but is not).  I did not trace the code right now, but the left one should come from the config.

**Comment by kikimor** [comment]
In our case Sentry try to send mail with the following subject containing Cyrillic chars:
```
[Sentry] [dev project1] ERROR: CDbCommand не удалось исполнить SQL-запрос: SQLSTATE[HY000]: General error: 1008 OCIStmtExecute: ...
```
So, I get UnicodeDecodeError with the traceback I'we posted above.

**Comment by mitsuhiko** [comment]
If you can reproduce this, maybe you could print the local variables in "sentry/plugins/sentry_mail/models.py", line 46, in _send_mail"?

Eg: add this right before the call to the message builder:

```python
import pprint
pprint.pprint(locals())
```

**Comment by kikimor** [comment]
```python
...
'subject':"[dev project1] ERROR: exception 'CDbException' with message 'CDbCommand \xd0\xbd\xd0\xb5 \xd1\x83\xd0\xb4\xd0\xb0\xd0\xbb\xd0\xbe\xd1\x81\xd1\x8c \xd0\xb8\xd1\x81\xd0\xbf\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xb8\xd1\x82\xd1\x8c SQL-\xd0\xb7\xd0\xb0\xd0\xbf\xd1\x80\xd0\xbe\xd1\x81: SQLSTATE[HY000...",
'subject_prefix':u'[Sentry] '
...
```

**Comment by mitsuhiko** [comment]
I hope this fixes it :)

**Comment by kikimor** [comment]
Unfortunately, the problem is not fixed.

pprint.pprint(locals()), subject value:
```python
[dev project1] ERROR: exception 'CDbException' with message 'CDbCommand \xd0\xbd\xd0\xb5 \xd1\x83\xd0\xb4\xd0\xb0\xd0\xbb\xd0\xbe\xd1\x81\xd1\x8c \xd0\xb8\xd1\x81\xd0\xbf\xd0\xbe\xd0\xbb\xd0\xbd\xd0\xb8\xd1\x82\xd1\x8c SQL-\xd0\xb7\xd0\xb0\xd0\xbf\xd1\x80\xd0\xbe\xd1\x81: SQLSTATE[HY000...
```

exception:
```python
[ERROR] Error processing 'rule_notify' on 'MailPlugin': 'ascii' codec can't decode byte 0xd0 in position 71: ordinal not in range(128)
Traceback (most recent call last):
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/plugins/bases/notify.py", line 59, in rule_notify
    self.notify(notification)
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/plugins/sentry_mail/models.py", line 190, in notify
    context=context,
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/plugins/sentry_mail/models.py", line 49, in _send_mail
    subject='%s%s' % (subject_prefix, subject),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 71: ordinal not in range(128)
```

**Comment by kikimor** [comment]
bump! :-)

**Comment by jpatel3** [comment]
Any recommended fix for this issue. I am also running into it.

**Comment by mattrobenolt** [comment]
@jpadilla What version of Sentry are you running?

**Comment by jpadilla** [comment]
@mattrobenolt not sure if you meant to mention me, but fwiw I'm using 7.7.0 :smile:

**Comment by mattrobenolt** [comment]
Oh. Oops. I meant to mention @jpatel3.

> What version of Sentry are you running?

**Comment by jpatel3** [comment]
using 7.7.4

**Comment by jpatel3** [comment]
It seems like my error is not unicode related. But I have one member with sentry@localhost and MailPlugin throws error {u'sentry@localhost': (504, '5.5.2 <sentry@localhost>: Recipient address rejected: need fully-qualified address')}

**Comment by jpatel3** [comment]
Ignore my error, its resolved. I was debugging on wrong trail :(
