### ISSUE TITLE
Make javascript source fetching optional

### ISSUE THREAD

**Issue by sseypt** [getsentry/sentry#1428]
In 7.2.0 the SourceProcessor (/src/sentry/lang/javascript/processor.py) tries to fetch files it found in the stacktrace (conditions below).

- lineno >= 0
- colno >= 0
- abs_path is the HTTP URI to the source
- context_line is empty

However this causes unwanted actions on application side in case you are using inline javascript and the actions aren't resticted to POST requests. I'm also not sure why these request are necessary when post_context is set with {fetchContext: true} (raven-js).

Furthermore someone could manipulate the stacktrace on client side to let sentry send requests to restricted resources (e.g. localhost or by bypassing firewalls using the ip of the sentry server).

I would like to have an option to deactivate javascript source fetching and/or to setup filters like "*/getJS/*" to controll which resources are good to fetch.

**Comment by dcramer** [comment]
@sseypt Sentry does not allow local resource requests by default so that's not a concern. If you're talking about self-hosted sentry, there's an option to disable source fetching. If you're talking on a per-project level, that's something we'd need to give more thought but seems extremely special cased.

**Comment by sseypt** [comment]
@dcramer Thanks for the quick response. I'm talking about a self-hosted sentry. Per-project level is not the case. Where I can find this option?

**Comment by dcramer** [comment]
@sseypt SENTRY_SCRAPE_JAVASCRIPT_CONTEXT, though keep in mind you'll lose sourcemap support
