### ISSUE TITLE
beforeSend doesn't get triggered when DSN is empty

### ISSUE THREAD

**Issue by Christilut** [getsentry/sentry#14283]
I migrated from `raven` to `@sentry/node v5.5.0`

In raven the beforeSend was triggered even if no DSN was provided. This was helpful because I added my logging into the beforeSend. 
With the new version, beforeSend doesn't seem to get triggered when the DSN is empty. In development my DSN is empty but I still want my Sentry errors to get logged through my logger.

I also tried adding this:
```ts
Sentry.configureScope(scope => {
  scope.addEventProcessor(async event => {
    logger.info(event)

    return event
  })
})
```

But it also doesn't seem to happen when no DSN is provided.

I think both of those should still happen. Everything should happen except the actual sending to Sentry when the DSN is empty.

**Comment by mitsuhiko** [comment]
This is intended behavior. You can alternatively provide a transport function for such cases which will be called regardless I believe on all SDKs. This issue however was filed against the wrong repository. If the transport function does not work for you please re-open against the sentry-javascript repository.
