### ISSUE TITLE
Slack Integration: 

### ISSUE THREAD

**Issue by ehoffman73** [getsentry/sentry#14284]
self hosted, latest, docker containers, get this error when I click on slack install button: OAuth Error: Please specify `client_id`

**Comment by silvez-dh** [comment]
maybe related to https://github.com/getsentry/sentry/issues/14179

**Comment by BYK** [comment]
Hi there! This looks like a configuration issue with your instance so please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
