### ISSUE TITLE
Error message does not match

### ISSUE THREAD

**Issue by robert196** [getsentry/sentry#14294]
The sentry error info is 【lllll is not defined】
but the source code is  【console.log(vvvvcccc)】

**Comment by markstory** [comment]
How can someone reproduce what you're seeing?

**Comment by robert196** [comment]
I just want to know , How does the cache work?
Just restart all services, that was resolved.

**Comment by robert196** [comment]
When I update an existed Releases, that happend.
i supposed update an existed Releases. Am i wrong?
```bash
postgres_1_987675c62435 | ERROR:  duplicate key value violates unique constraint "sentry_release_organization_id_f0a7ec9ba96de76"
postgres_1_987675c62435 | DETAIL:  Key (organization_id, version)=(1, demo@1.0.6) already exists.
postgres_1_987675c62435 | STATEMENT:  INSERT INTO "sentry_release" ("organization_id", "project_id", "version", "ref", "url", "date_added", "date_started", "date_released", "data", "new_groups", "owner_id", "commit_count", "last_commit_id", "authors", "total_deploys", "last_deploy_id") VALUES (1, NULL, 'demo@1.0.6', NULL, NULL, '2019-08-07 01:59:00.053814+00:00', NULL, NULL, '{}', 0, NULL, 0, NULL, '{}', 0, NULL) RETURNING "sentry_release"."id"
postgres_1_987675c62435 | ERROR:  duplicate key value violates unique constraint "sentry_release_project_project_id_35add08b8e678ec7_uniq"
postgres_1_987675c62435 | DETAIL:  Key (project_id, release_id)=(2, 1) already exists.
postgres_1_987675c62435 | STATEMENT:  INSERT INTO "sentry_release_project" ("project_id", "release_id", "new_groups") VALUES (2, 1, 0) RETURNING "sentry_release_project"."id"
web_1_7c51c31dc0e8 | 172.23.0.1 - - [07/Aug/2019:01:59:00 +0000] "POST /api/0/projects/sentry/vue/releases/ HTTP/1.1" 208 692 "-" "sentry-cli/1.47.1"
postgres_1_987675c62435 | ERROR:  duplicate key value violates unique constraint "sentry_release_organization_id_f0a7ec9ba96de76"
postgres_1_987675c62435 | DETAIL:  Key (organization_id, version)=(1, demo@1.0.6) already exists.
postgres_1_987675c62435 | STATEMENT:  INSERT INTO "sentry_release" ("organization_id", "project_id", "version", "ref", "url", "date_added", "date_started", "date_released", "data", "new_groups", "owner_id", "commit_count", "last_commit_id", "authors", "total_deploys", "last_deploy_id") VALUES (1, NULL, 'demo@1.0.6', NULL, NULL, '2019-08-07 01:59:00.230353+00:00', NULL, NULL, '{}', 0, NULL, 0, NULL, '{}', 0, NULL) RETURNING "sentry_release"."id"
postgres_1_987675c62435 | ERROR:  duplicate key value violates unique constraint "sentry_release_project_project_id_35add08b8e678ec7_uniq"
postgres_1_987675c62435 | DETAIL:  Key (project_id, release_id)=(2, 1) already exists.
postgres_1_987675c62435 | STATEMENT:  INSERT INTO "sentry_release_project" ("project_id", "release_id", "new_groups") VALUES (2, 1, 0) RETURNING "sentry_release_project"."id"

```

**Comment by markstory** [comment]
You can use [PUT on a release](https://docs.sentry.io/api/releases/put-organization-release-details/) to update it.

**Comment by robert196** [comment]
thanks for quickly response

**Comment by robert196** [comment]
Actually, i wander to know how did happen.  The error log was correct 【ReferenceError
moopop is not defined】 but the source code was wrong, it seems cached.
![image](https://user-images.githubusercontent.com/23290402/62592548-18e34280-b906-11e9-934a-5c0adde62f85.png)

**Comment by markstory** [comment]
Yes source code is cached. If you want more accurate source code mappings you need to use release APIs to upload source maps.

**Comment by robert196** [comment]
I have uploaded the latest source maps, then I download the source map form artifacts, compare with my local development source map. I am sure they are all the same.
Finally, I restart the memcached service and that problem was resolved.
So I repeated this thing, build and upload source map, trigger an error, restart memcached service ...
would I change the cache time. The cache time will last for 40 minutes, or longer, mabey an hour.
PS: I upload source via sentry-webpack-plugin.what is the different between release APIs

**Comment by BYK** [comment]
Hi there! Sorry for being late to the party but please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues. You can still ping @markstory there: https://forum.sentry.io/u/markstory/summary
