### ISSUE TITLE
Suggestion: Webhooks shouldn't be a legacy integration

### ISSUE THREAD

**Issue by kaspergrubbe** [getsentry/sentry#14295]
## Summary

It seems like right now the webhooks is a legacy integration (that might go away tomorrow).

## Motivation

It's nice that Sentry has built-in integrations for stuff like Github and Jira and what-have-you, but webhooks are an essential feature to glue things together.

It would therefore be nice if webhooks could be supported on the same level as regular integrations, and not hidden away under legacy integrations.

**Comment by BYK** [comment]
They are now a 1st-class integration: https://docs.sentry.io/product/integrations/integration-platform/webhooks/ 🎉

**Comment by kaspergrubbe** [comment]
Fantastic, thanks!
