### ISSUE TITLE
sentry cache 

### ISSUE THREAD

**Issue by robert196** [getsentry/sentry#14306]
sentry cache time up to 40 minutes ，
it's too long for me ，dose it has a easy way to change it？

**Comment by mattrobenolt** [comment]
Which cache? We have lots of caches, but I’m not sure any of them are 40 minutes. That’s an odd time for us to pick.

**Comment by robert196** [comment]
maybe  longer，60min？I counted via alarm.

**Comment by robert196** [comment]
The details of the problem are #14294

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
