### ISSUE TITLE
Stacktrace: double click on captured data doesn't select the whole data

### ISSUE THREAD

**Issue by mfn** [getsentry/sentry#1430]
When trying to quickly copy out data from the trace by double clicking on it, it unexpectedly breaks because of the invisible `<span>`s. Quite unexpected.

![snip20150220_75](https://cloud.githubusercontent.com/assets/87493/6283560/842a22ea-b8e6-11e4-9de8-c6b08c2a42b4.png)

**Comment by mattrobenolt** [comment]
I assume this isn't relevant anymore, but plz reopen if that's not true.
