### ISSUE TITLE
don't know where url-prefix is being set

### ISSUE THREAD

**Issue by belm0** [getsentry/sentry#14314]
We found that url-prefix should not have a trailing slash (#8049), and would like to correct our configuration.  However it's unknown how url-prefix is being set.

```
$ sentry config discover
/etc/sentry/sentry.conf.py
/etc/sentry/config.yml
```
Confirmed that url-prefix is not set by these config files.

`config get` does not indicate the source of this setting:
```
$ sentry config get system.url-prefix
05:24:51 [INFO] sentry.plugins.github: apps-not-configured
        type: STRING
 from config: <not set>
     current: https://[...]/
```

I have looked at the documentation for sentry configuration, it only mentions config.yaml and conf.py for setting these parameters.  Is there some documentation missing?

**Comment by mattrobenolt** [comment]
If it's not in your config files, which it's not as indicated by `<not set>` it means it's stored in the database, which most likely came from the initial setup wizard.

You can just fix this by doing `sentry config set system.url-prefix ...` or setting it in your config file to override the database value.
