### ISSUE TITLE
API for creating/modifying/deleting organisation/teams/projects

### ISSUE THREAD

**Issue by arthurlogilab** [getsentry/sentry#1431]
Am looking into the API for sentry in /docs/api/, I can't find anything about adding a team or a project, does it not exist or is just not documented ? 

If it doesn't exist, it would be useful to have it.

**Comment by dcramer** [comment]
@arthurlogilab it's not publicly available yet. Right now it requires you to have an API key (which cannot be generated from the UI) or use session auth, and we also dont document most of these endpoints.

That said this will be changing in the coming weeks.
