### ISSUE TITLE
how can I config sentry ? I want to change the datetime format

### ISSUE THREAD

**Issue by aFlappyPig** [getsentry/sentry#14317]
![image](https://user-images.githubusercontent.com/18723676/62679569-7a2f1280-b9e7-11e9-922a-3e3e872ecef1.png)
![image](https://user-images.githubusercontent.com/18723676/62679673-c9754300-b9e7-11e9-84e3-f831c829febc.png)

I find this page, but I don't know how to change the default config. And I get nothing from sentry.io. 
I try to change the sentry.conf.py , it don't work.
I run sentry in docker in ubuntu1804.

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
