### ISSUE TITLE
No authentication for CORS preflight request

### ISSUE THREAD

**Issue by whme** [getsentry/sentry#14318]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.0.0]

## Description

For private projects that require an[ authentication token to access the API](https://docs.sentry.io/api/auth/), tools that use[ cross-origin](https://developer.mozilla.org/en-US/docs/Glossary/CORS) requests cannot be used.
This is because Sentry also wants Authentication for the [cors preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request). However, this preflight request is an OPTIONS request and [never includes credentials](https://fetch.spec.whatwg.org/#cors-protocol-and-credentials).

### What you expected to happen

Allow any OPTIONS request even without authentication.

**Comment by scefali** [comment]
@UnicornDeluxe Thanks for bringing this up! I am happy to share with you that some recent changes (this PR https://github.com/getsentry/sentry/pull/14651) probably will help you solve your issue. This change will be released in v10.0.0. I am not sure what kind of auth token you are using (I presume a user based auth token), but the best way of doing this in the future is with the auth token from an internal integration (see [docs](https://docs.sentry.io/workflow/integrations/integration-platform/). What you'll need to do is add the origins you want to whitelist in "Authorised JavasScript Origins" as you see below: 
![Screen Shot 2019-10-14 at 11 40 16 AM](https://user-images.githubusercontent.com/8533851/66778323-2bd33f80-ee80-11e9-8e1a-1666d24346ca.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Please try this with a more recent version of Sentry and if it is still a problem, file a new issue.
