### ISSUE TITLE
Double slash in link to a Jira task ends with broken page

### ISSUE THREAD

**Issue by hinok** [getsentry/sentry#14319]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Created Jira issue through sentry has double slash like

```
https://mycompany.atlassian.net//browse/BL-1994
```

notice double slash after `.net`

```
//browse/BL-1994
```

This link doesn't redirect to "valid" page on Jira. There is an internal redirect on Jira that is trying to transition into `borwse/BL-1994` which ends like on screen below

![Zrzut ekranu 2019-08-8 o 18 01 55](https://user-images.githubusercontent.com/1313605/62718746-bcb41780-ba06-11e9-9467-61a94cc098ea.png)

## Steps to Reproduce

1. Find an issue
2. Create a Jira task through sentry.io panel

![Zrzut ekranu 2019-08-8 o 18 04 05](https://user-images.githubusercontent.com/1313605/62718866-fb49d200-ba06-11e9-8848-c46a9d128e31.png)

![Zrzut ekranu 2019-08-8 o 18 05 27](https://user-images.githubusercontent.com/1313605/62718976-35b36f00-ba07-11e9-9165-81d83d35f0ec.png)

3. Open created link

![Zrzut ekranu 2019-08-8 o 18 04 52](https://user-images.githubusercontent.com/1313605/62719000-4237c780-ba07-11e9-968f-da4c9e8991fb.png)

### What you expected to happen

Should open Jira task

### Possible Solution

Remove `//` from the link

**Comment by markstory** [comment]
Are you using the organization integration for jira or the project level legacy plugin?

**Comment by hinok** [comment]
@markstory legacy integration

![Zrzut ekranu 2019-08-8 o 20 59 58](https://user-images.githubusercontent.com/1313605/62730079-90f15b80-ba1f-11e9-8db0-487197bc71ff.png)

**Comment by markstory** [comment]
That plugin is no longer supported. Would you be able to migrate to the organization integration?

**Comment by hinok** [comment]
It seems that I don't have any other option ;)
