### ISSUE TITLE
Additional email addresses and validation

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1432]
We want to introduce a subsystem which will allow an account to attach additional email addresses to it. These would primarily be used for notifications, and would not be used for authentication.

Doing this would allow us to open up email addresses in a number of ways, such as:
- Verifying that the email address you're spamming has agreed to notifications.
- Allow email rules to be created that go to any arbitrary mailing address that is verified.
- Change how per-project notification addresses work so it's less arbitrary and a simple select box.

One thing to note here is we'd want to be aware of gmail-isms, to where foobar[+alias] is not a separate email, and does not need validated as such.

**Comment by mattrobenolt** [comment]
To add to this, we also need to cover being able to unsubscribe yourself from unwanted emails even if you don't have an account.

The case being, you were previously a part of a project, you were added as an "alert email", then no longer on the project, but you're getting emails still and they're now unwanted.

See: https://sentry.zendesk.com/agent/tickets/642 for the user complaint about exactly this.

**Comment by benvinegar** [comment]
In a minor version of Sentry 8 we introduced secondary emails with verification.
