### ISSUE TITLE
webhooks not being sent

### ISSUE THREAD

**Issue by trevorah** [getsentry/sentry#1433]
Steps to reproduce:

1. enable the webhooks plugin
2. add a [request bin](http://requestb.in) url to the list of Callback URLs
3. click Save
4. click Test Configuration or trigger some error in your personal app
5. no post data is seen in the request bin inspector :sob:

**Comment by dcramer** [comment]
Fixed in 54ea7f8d6a47c2a0f457ac7976d0ed3eb23e49ab

Basic test in 6ce6a307a5fb3f89fb0bf307eda3024b3e0e32c6

**Comment by trevorah** [comment]
Webhooks are coming through now. Thanks @dcramer!
