### ISSUE TITLE
Suggestion: Allow for sending multiple requests in one request.

### ISSUE THREAD

**Issue by tomgie** [getsentry/sentry#14366]
## Summary

Allow any SDK to implement sending multiple requests via one request to the sentry API. Implementing a new attribute on when the request was received by the SDK that goes along with the timestamp of when the error happened. Allowing the latency feature within Sentry to work.

## Motivation

Currently, I am creating an SDK for the game engine/platform Roblox. As developers we are limited on how many HTTP requests we can make in a set amount of time. By allowing multiple requests in one request this would allow me to cut down on how many requests my SDK will make.

**Comment by BYK** [comment]
I think [Envelopes](https://develop.sentry.dev/sdk/envelopes/) solve this issue now.
