### ISSUE TITLE
Cleanup task consumes too much memory

### ISSUE THREAD

**Issue by eagletmt** [getsentry/sentry#1436]
While running `cleanup` task, Sentry consumes about 1-2 GB of memory.

It seems Sentry consumes much memory during "Removing old Node values" step.
The deleted `nodestore_node` record is about 3000+ rows.
Due to this issue, we have to run cleanup task often to reduce the deleted rows during one execution.

Sentry version: 7.3.2

**Comment by dcramer** [comment]
I'll need to look into this but there's a *very* good chance it's the result of Django loading the rows into memory. We can optimize this by using the bulk row deletion strategy thats used in the other deletion tasks.

**Comment by eagletmt** [comment]
I confirmed `Node.objects.filter(timestamp__lte=cutoff_timestamp).delete()` is the memory eater.
https://github.com/getsentry/sentry/blob/7.3.2/src/sentry/nodestore/django/backend.py#L46
When I delete over 10,000 records, the task would be killed by OOM Killer.

I don't know why it loads records into memory...

**Comment by dcramer** [comment]
@eagletmt I think the above commit will resolve this. It'll make it in the 7.4.0 release.

**Comment by eagletmt** [comment]
Thank you!
I'm looking forward to the next release.

**Comment by dIoMeDs** [comment]
Hi!
Sentry version: 8.22.0
OOM'ed when delete issue with 3.9 million events. We have an old issue with large count of enents for 1 year. When running delete or cleanup (otherwise) it "eat" all 8Gb memory and go far away in swap up to 20Gb swap. 
Is it ok?

**Comment by dcramer** [comment]
You don’t have DEBUG enabled by accident do you?
