### ISSUE TITLE
VSTS Integration: Internal Server Error

### ISSUE THREAD

**Issue by garystubbings** [getsentry/sentry#14390]
We are currently trialing sentry with a hope to get it connected to our Azure DevOps project(s). However, we are seeing the following when our Organisation Owner attempts to install the integration. 13th August '19 16:35 **Add Installation** while logged into https://sodalabs.visualstudio.com failed with the following. The system status was fine.

![Screenshot 2019-08-14 at 18 46 33](https://user-images.githubusercontent.com/5552649/63043309-def4dc00-bec3-11e9-8fcc-b9086f0b083f.png)

The owner details do appear to return correctly when we check against the API. 
https://app.vssps.visualstudio.com/_apis/accounts?ownerId=<owner_id>&api-version=4.1 

```
{"count":1,"value":[{"accountId":"<account_id>","accountUri":"https://sodalabs.vssps.visualstudio.com:443/","accountName":"sodalabs","properties":{}}]}
```

**Comment by markstory** [comment]
Internally we got a non-200 response code for that API call which is why the connection failed. I'll fix the fatal error, but I don't know why Azure if giving us a status code other than 200.

**Comment by markstory** [comment]
You'll also want to make sure that the account completing the integration can create webhook subscriptions. I found another error related to that matching sodalabs.
