### ISSUE TITLE
why in stats have many Events by Project,but in event dashboard  nothing??

### ISSUE THREAD

**Issue by vTNT** [getsentry/sentry#1442]
sentry version:7.1.4 
in stats, show 14 Accepted Events by Project, but at event dashboard  show nothing ??

**Comment by dcramer** [comment]
@vTNT we'll be improving other pages soon, but I'm not sure if we'll ever show it per-event, as that's quite a bit more costly than showing it at the organization/team/project level.

**Comment by vTNT** [comment]
i upgrade sentry to 7.3.2  
i run this command: raven test xxx     it can success send a test message. in stat, can find the event +1 ,but event dashboard show nothing                       so i  how to slove it ?

**Comment by dcramer** [comment]
Read what I said above, go over the documentation again, check logs. Something is error or not running.
