### ISSUE TITLE
Find related events

### ISSUE THREAD

**Issue by asbjornu** [getsentry/sentry#1443]
With the limited amount of fields it's possible to search for in Sentry today, I find it hard to discover related events. The information that relates them is often something we call a `ChainID`, that is basically just a GUID we use through a whole "vertical" of systems communicating with each other, all the way from the user's browser, down through various APIs and into the database and back up again.

Other information that relates events together are user names, e-mail addresses, etc. It's often necessary to collect all of these events together in chronological order to understand why something failed and caused all of the events to be sent to Sentry.

Is it possible to do manual grouping of events like these today, or search for metadata that relates them so each individual event related to a `ChainID` or `User` is listed in chronological order? If not, please consider this a highly needed (to us, at least) feature request. :smile:

**Comment by dcramer** [comment]
As part of our upcoming infrastructure overhaul we plan to expand search/streams to *all* events. Today this isn't yet possible.

Additionally down the road (the next API version likely) we'll introduce a "transaction ID" concept which will be the beginnings of distributed tracing, at least from the storage POV.
