### ISSUE TITLE
Sentry does not report errors when caught by custom error renderer

### ISSUE THREAD

**Issue by descl** [getsentry/sentry#1444]
Hello,
since i'm catching basics errors with rescue_from I'm not receiving errors on sentry anymore.

The code I added is:
```
    rescue_from Exception, with: :render_500
  def render_500(exception)
      render :template => "/errors/500error.html", :layout => "empty", :status => 500 and return
  end
  ...
```

I founded this issue for honeybadger https://github.com/honeybadger-io/honeybadger-ruby/issues/29 which is nearly the same but nothing for sentry.
Thanks, Chris

**Comment by descl** [comment]
Hi,
did somebody find a solution for this issue?
Thanks, Chris

**Comment by mattrobenolt** [comment]
Hey @descl, you might have better luck over on the https://github.com/getsentry/raven-ruby repository. :) This repository is for the Sentry server, and this is a ruby client specific bug.

**Comment by descl** [comment]
arg thanks!
