### ISSUE TITLE
Celery integration throws exception

### ISSUE THREAD

**Issue by chrisspen** [getsentry/sentry#14456]
Attempting to import the Celery Integration via:

    from sentry_sdk.integrations.celery import CeleryIntegration

throws the exception:

      File "settings/settings.py", line 14, in <module>
        from sentry_sdk.integrations.celery import CeleryIntegration
      File ".env/lib/python3.7/site-packages/sentry_sdk/integrations/celery.py", line 6, in <module>
        from celery.exceptions import (  # type: ignore
    ModuleNotFoundError: No module named 'celery.exceptions'; 'celery' is not a package

Yet I have celery==4.3.0 installed in my virtualenv.

    $ pip freeze | grep celery
    celery==4.3.0

**Comment by baby5** [comment]
maybe the py file you created named `celery.py`

**Comment by chrisspen** [comment]
No, I named my local Celery initialization file `celery_init.py`.

**Comment by baby5** [comment]
show the tree of your project and content of `celery_init.py`

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
