### ISSUE TITLE
[7.3.2] --config flag is not recognized by "start" command.

### ISSUE THREAD

**Issue by jhgg** [getsentry/sentry#1445]
Running command: 

`/webapps/sentry/bin/sentry --config=/webapps/sentry/sentry.conf.py start`

Workers fail to startup because of error:
```
Traceback (most recent call last):
  File "/webapps/sentry/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/webapps/sentry/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/webapps/sentry/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/webapps/sentry/local/lib/python2.7/site-packages/sentry/services/http.py", line 34, in load
    import sentry.wsgi
  File "/webapps/sentry/local/lib/python2.7/site-packages/sentry/wsgi.py", line 20, in <module>
    configure()
  File "/webapps/sentry/local/lib/python2.7/site-packages/sentry/utils/runner.py", line 399, in configure
    initializer=initialize_app,
  File "/webapps/sentry/local/lib/python2.7/site-packages/logan/runner.py", line 89, in configure_app
    raise ValueError("Configuration file does not exist at %r" % (config_path,))
ValueError: Configuration file does not exist at '/home/jh/.sentry/sentry.conf.py'
```

I've traced it back to this commit: 68d548d792492b104c25ab9df71db73d102b4064

In `services/http.py` changing the `SentryHttpServer.run()` function to the following:

```python
    def run(self):
        #SentryGunicornCommand(self.options).run()
        from django.core.management import call_command
        call_command('run_gunicorn', **self.options)
```

Causes the bug not to happen anymore. This leads me to believe it has to do with the "--config" parameter not getting passed to Logan properly.

Digging into Logan, I decided to dump `sys.argv` on line 85 (except below)

```python
    config_path = os.path.expanduser(config_path)
    print('config_path', config_path, 'argv', sys.argv)
    if not os.path.exists(config_path):
```

When running with `SentryGunicornCommand`, I noticed it would print out:
```('config_path', '/home/jh/.sentry/sentry.conf.py', 'argv', ['/webapps/sentry/bin/sentry'])```

However, when running with `run_gunicorn` command, it would print out:

```('config_path', '/webapps/sentry/sentry.conf.py', 'argv', ['/webapps/sentry/bin/sentry', '--config=/webapps/sentry/sentry.conf.py', 'start'])```

Which leads me to believe that `SentryGunicornCommand` forks off new processes before calling `.load()`, which does not have the config argv that logan checks for. 

I've worked around this by passing in the CONFIG file parameter via os.environ by using the following supervisord config:

```
[program:sentry-web]
directory=/webapps/sentry
command=/webapps/sentry/bin/sentry start
user=sentry
environment=SENTRY_CONF="/webapps/sentry/sentry.conf.py"
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/webapps/sentry/logs/supervisor-sentry-web.log
```

Or by calling the start command as: `SENRY_CONF=/webapps/sentry/sentry.conf.py  /webapps/sentry/bin/sentry start`

**Comment by dcramer** [comment]
This is fixed in master. I'm going to get 7.4.0 out today so people don't continue to have this issue.

**Comment by jhgg** [comment]
Thanks for the quick reply. And I just saw #1438 too! Didn't search closed issue when I was looking to see if anyone else had the issue ;(
