### ISSUE TITLE
uploaded source maps ignored

### ISSUE THREAD

**Issue by seanzhou1996** [getsentry/sentry#14461]
## Environment

* `@sentry/browser`: 5.6.2
* `ionic`: 5.2.5

## Problem Description

* I'm using Sentry on `sentry.io` for my Ionic 4 demo project.
* I created a release and uploaded source maps along with build files. In my project, those files are in the same folder named `www`.
* I wanted to test my implementation so I threw a mock error in the code.
* In the error detail page, the stack trace only showed minified lines.
* There was an error message on the page, saying it couldn't find my source maps.

**Stack trace**

![Screen Shot 2019-08-21 at 11 57 04 AM](https://user-images.githubusercontent.com/22345231/63413666-bffaca80-c42c-11e9-8813-74dea4b78cbb.png)

**Error message**

<img width="855" alt="Screen Shot 2019-08-21 at 12 02 46 PM" src="https://user-images.githubusercontent.com/22345231/63413705-d143d700-c42c-11e9-8abd-52e1d2c77d89.png">

**Artifacts**

<img width="1175" alt="Screen Shot 2019-08-21 at 12 04 47 PM" src="https://user-images.githubusercontent.com/22345231/63413729-e456a700-c42c-11e9-8efa-87715affd21c.png">

<img width="1176" alt="Screen Shot 2019-08-21 at 12 05 26 PM" src="https://user-images.githubusercontent.com/22345231/63413745-e9b3f180-c42c-11e9-9c08-6bced84c7a60.png">

<img width="1174" alt="Screen Shot 2019-08-21 at 12 05 49 PM" src="https://user-images.githubusercontent.com/22345231/63413751-ee78a580-c42c-11e9-81f2-d5e0c9bceeec.png">

In each `<file-name>.js`, `sourceMappingURL` looks like this:

<img width="967" alt="Screen Shot 2019-08-21 at 2 42 33 PM" src="https://user-images.githubusercontent.com/22345231/63413794-03edcf80-c42d-11e9-8665-92add05dd023.png">

## Steps to reproduce

1. Get Ionic 4 and create a new project using `tabs` template:

   ```bash
   npm install ionic -g
   ```

   ```bash
   ionic start ionic-4-demo tabs
   ```

2. Open `src/app/tab3/tab3.page.ts` and insert the following:

   ```typescript
   // tab3.page.ts
   
   export class Tab3Page {
     // ...
     throwError() {
       throw Error('Throwing an custom error...');
     }
   }
   ```

3. Open the corresponding template and add this button:

   ```html
   <!-- tab3.page.html -->
   
   <ion-content>
     <ion-button (click)="throwError()">Throw Error</ion-button>
   </ion-content>
   ```

4. In `src/app`, create an error handler using `sentry/browser`:

   ```typescript
   // src/app/error-handler.ts
   
   import { ErrorHandler } from '@angular/core';
   import * as Sentry from '@sentry/browser';
   
   Sentry.init({
       dsn: '<proj-dsn>',
       release: '<proj-id>@<version>'
   });
   
   export class SentryErrorHandler extends ErrorHandler {
       handleError(err) {
           super.handleError(err);
           const eventId = Sentry.captureException(err.originalError || err);
           Sentry.showReportDialog({ eventId });
       }
   }
   ```

5. In `app.module.ts`, register the error handler:

   ```typescript
   // src/app/app.module.ts
   
   import { ErrorHandler } from '@angular/core';
   import { SentryErrorHandler } from './error-handler';
   
   @NgModule({
     // ...
     providers: [
       // ...
       { provide: ErrorHandler, useClass: SentryErrorHandler }
     ]
   })
   ```

6. Run this build command:

   ```bash
   ionic cordova prepare ios --prod --source-map
   ```

7. Create a new release.

8. Upload artifacts:

   ```bash
   sentry-cli releases files <release-id> upload-sourcemaps www
   ```

9. Finalize the release.

10. Open Xcode, run the app on a device. Navigate to Tab Three and tap "Throw Error" button.

### Expected behavior

Sentry should be able to locate the uploaded source maps; Stack trace should reveal original source file name and error location. Refer to the Safari console output below:

![Screen Shot 2019-08-21 at 3 55 59 PM](https://user-images.githubusercontent.com/22345231/63413868-3f889980-c42d-11e9-8f4c-80343b335b64.png)

**Comment by eriktoyra** [comment]
@SeanZhouSiyuan I'm having a similar issue for my React (CRA) project. Also using `@sentry/browser: 5.6.2`. The source maps are uploaded correct, with correct paths, but they are not resolved. Instead I'm served the minified version of the file from my (localhost) server instead of using the uploaded source maps.

**Comment by youssseeef** [comment]
@eriktoyra I faced this issue recently, could you post a screenshot of your artifacts screen inside the release section?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
