### ISSUE TITLE
SENTRY_BEACON should be False by default.

### ISSUE THREAD

**Issue by ldrumm** [getsentry/sentry#1449]
`SENTRY_BEACON` is sending private information to [getsentry.com](getsentry.com) without my _expressed_ permission.  Updating my installation with `pip install -U sentry` should not end up silently publishing my information to an untrusted 3rd party.

I say untrusted because `getsentry.com` is a black box from the end-user's perspective. The documentation at http://sentry.readthedocs.org/en/latest/beacon.html states that this will be in line with getsentry's privacy policy, which was never agreed to.  The code for sentry is available for all to see which gives transparency on what happers on my server, but not on the behaviour of getsentry.com. This is intrusive behaviour without any prior agreement with getsentry.com, and as such should be opt-in behaviour. 

Please set `SENTRY_BEACON = False`

**Comment by dcramer** [comment]
This won't be changing, but we're happy to accept improvements around the wording.

**Comment by dcramer** [comment]
Also to shed some light on this, we had three fundamental goals here:

1. Provide a more controlled way to do version checks.
2. Provide an opt-in way (that is, non-anonymous) for us to contact admins of self-hosted installs on security release.
3. Collect general usage statistics around self-hosted Sentry installs.

While Sentry is open source, it's fundamentally been built by myself, and is managed by getsentry.com (the company I founded). We consider this a small cost for what is a fairly complex and featureful platform that will continue to be made available for free, and built in the open. 

If it makes people feel better, we're happy to put a giant "YOU ARE AGREEING TO THIS PRIVACY POLICY" whenever Sentry starts up (assuming the beacon is enabled). With that said, consider that you didn't explicitly agree to PyPi's privacy policy, you also didn't explicitly agree to the license of the software. 

Additionally you're trusting that the 70,000+ lines of code that you're installing are trusted and won't cause harm to your systems, which seems a bit more scary than the usage data we're sending.
