### ISSUE TITLE
Creating a new Asana issue returns 400: workspace: not a valid GID type

### ISSUE THREAD

**Issue by itsmemohamed** [getsentry/sentry#14520]
<img width="605" alt="Screen Shot 2019-08-27 at 1 21 30 PM" src="https://user-images.githubusercontent.com/41019781/63805234-d4781080-c8cd-11e9-8d9f-697e1e9cab4e.png">

### Important Details

How are you running Sentry? On-Premise docker

### Description/Repro

Creating a new Asana issue for any errors returns a `Error Communicating with Asana (HTTP 400): workspace: Not a valid GID type: number`

### Possible Solution

Looking at the request sent to the backend,
`GET /api/0/issues/1383/plugins/asana/create/`
`Params: {"workspace":752142915825,"title": ....`
It looks like the workspace GID is sent as a number but the Asana API takes GID as a string, so I'm not sure if this value is forwarded to Asana as-is or is being cast properly.

Edit:
Asana API changes that triggered this issue 
https://forum.asana.com/t/asana-is-moving-to-string-ids-updated-with-revised-timeline/29340
https://asana.com/developers/news/a-reminder-about-integer-id-deprecation

**Comment by berlix** [comment]
Related issue on the `sentry-plugins` repo: https://github.com/getsentry/sentry-plugins/issues/510

**Comment by markstory** [comment]
Closing as there is an issue in sentry-plugins for this which is where the code for the asana plugin lives.
