### ISSUE TITLE
Jira Integration: unable to automatically make tickets

### ISSUE THREAD

**Issue by ekimia** [getsentry/sentry#14526]
hey all, this is a pretty big detriment. Totally get some people may not want issues automatically created, but the main point is to have 1 central repository for all sorts of issues - sentry and nonsentry alike.

**Comment by valentijnscholten** [comment]
So what exactly do you want to see in sentry, every issue in sentry automatically results in a issue being created in JIRA?

**Comment by ekimia** [comment]
@valentijnscholten yes, ideally with rules so only fatal errors get logged.

**Comment by ekimia** [comment]
for most eng orgs there are multiple sources of bugs and feedback. Having to manually create the ticket (despite it being just a button now) is a lot of friction

**Comment by marbon87** [comment]
We are also interested in this feature. Are there any plans to implement this?

**Comment by ceorourke** [comment]
Hey @ekimia we're close to launching this! Keep an eye out - I can't promise a specific date but I'll give you a "soon" (probably this month).

**Comment by ekimia** [comment]
@ceorourke you're a hero!

**Comment by ceorourke** [comment]
This feature is now live to organizations that include transactions in their Business plans. That means if you've recently signed up or migrated from the "old" Business plan you'll have access. See it in the docs: https://docs.sentry.io/product/integrations/jira/#issue-management

It's also available for Azure DevOps!

It will be in on-prem versions with the next release (we release on the 15th of each month).
