### ISSUE TITLE
'Add Note' button clashes with text on "create github issue" text 

### ISSUE THREAD

**Issue by djds23** [getsentry/sentry#1452]
![screen shot 2015-03-10 at 11 21 02 am](https://cloud.githubusercontent.com/assets/5833968/6577939/9c9030e2-c717-11e4-92e4-83a58fc8a225.png)

Steps to reproduce:
1. view a group of events
2. click "create github issue" for that group
3. if the title is too long, it will be hidden beneath the 'Add Note' button

**Comment by mattrobenolt** [comment]
This isn't relevant anymore since the design has completely changed.
