### ISSUE TITLE
Can not disable user registration

### ISSUE THREAD

**Issue by christophlehmann** [getsentry/sentry#1453]
As described in http://sentry.readthedocs.org/en/latest/quickstart/index.html#enabling-third-party-auth
i configured the following in sentry.conf.py
```
from sentry.conf.server import *

...

SENTRY_FEATURES = {
    'auth:register': False,
    'social-auth:register': False,
}
```
restarted sentry and the registration possibility on login page doesn't go away. I'm currently using 7.3.0.

Did i missed something?

**Comment by dcramer** [comment]
Those docs actually aim at the 7.4.x version (where features were introduced). In 7.3 you can set SENTRY_ALLOW_REGISTRATION = False.

**Comment by christophlehmann** [comment]
Thank you!!
