### ISSUE TITLE
Unable to create team or project as an admin

### ISSUE THREAD

**Issue by dtao** [getsentry/sentry#1454]
First: apologies if this is the wrong place to be posting this issue. If it, just point me in the right direction and close it!

My team has a Sentry instance (looks like we're running 6.4.4), of which I am an admin:

![See? I'm an admin!](https://cloud.githubusercontent.com/assets/409328/6606146/7bace36a-c803-11e4-8a33-9f40a725b26d.png)

However, I can't create a team:

![Can't create a team](https://cloud.githubusercontent.com/assets/409328/6606158/9582c188-c803-11e4-9e3c-0d5d6ac1021d.png)

Another admin created the team for me; but then I found I also couldn't create a project *within* that team:

![Also can't create a project](https://cloud.githubusercontent.com/assets/409328/6606171/ac28a272-c803-11e4-952a-33482ca7a72d.png)

Is there something we're missing? Was there a known issue w/ permissions in 6.4.4, and we should just upgrade Sentry?

**Comment by dcramer** [comment]
6.4.x is pretty old so I'd have a tough time saying, but there are definitely system settings that control if you can actually do this by default.

I would take a stab at upgrading if you can, as we generally simplify things as time goes on. Alternatively you should *always* be able to do this if you're a superuser in the system.
