### ISSUE TITLE
Weird UI behaviour.

### ISSUE THREAD

**Issue by jaseemabid** [getsentry/sentry#1456]
The datetime fields don't seem to be rendered correctly. The page loads with correct data (14 minutes ago) and in a few seconds it re renders to "in 8 hours" automatically. 

Its really weird, and hence attaching a video along. 

https://www.youtube.com/watch?v=AXrmE6GAtB0

**Comment by dcramer** [comment]
This is a mix of the frontend and backend using different timezone points. The backend uses your configuration (personal settings) usually and the frontend uses detection.

**Comment by jaseemabid** [comment]
This is a bug. Why close it?

**Comment by dcramer** [comment]
@jaseemabid we've rewritten pretty much all of this already on a branch and i'm trying to clean up the bug tracker to more appropriately reflect whats going on.

**Comment by jaseemabid** [comment]
You could close the bug once its fixed on the mainline with a one liner description or a link to a release notes. The next time someone hit the bug and get here, he will be as clueless as me.
