### ISSUE TITLE
Runtime .NET Framework not showing the version

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#14591]
![image](https://user-images.githubusercontent.com/1633368/64366391-67bfed00-d016-11e9-9eba-1550640826ce.png)

Code in semaphore expects build to be reported:

https://github.com/getsentry/semaphore/blob/63150b06ef85195fdab9f7227b19263e173b5583/general/src/store/normalize/contexts.rs#L40

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by bruno-garcia** [comment]
I fixed it months ago, forgot about this issue
