### ISSUE TITLE
Discover: clearing a condition input causes the page to crash

### ISSUE THREAD

**Issue by stephen** [getsentry/sentry#14597]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description
When editing a query in discover, clearing the condition field crashes the page

![failure](https://user-images.githubusercontent.com/2320890/64389437-806cda80-cff7-11e9-90cd-b3ff703a407d.gif)

[What happened]

## Steps to Reproduce

1. run an query with a condition
2. clear the contents of the condition
3. page crashes

Good items to include here include:

### What you expected to happen
field cleared. no crash.

### Possible Solution

The code here: https://github.com/getsentry/sentry/blob/b2b001334b60995c0dc83dce96d7817fedee2d35/src/sentry/static/sentry/app/views/discover/conditions/condition.tsx#L143-L154 should not be using `evt` inside the `setState`, since that callback is executed async. 

You can call `evt.persist()` to get around this. See: https://reactjs.org/docs/events.html#event-pooling

I tried this locally and it partially solves the problem - the crash doesn't happen, but also there's some wonky defaulting happening. I stopped investigating at that point.

**Comment by dashed** [comment]
Thanks! Would you be willing to open a PR?
