### ISSUE TITLE
JIRA(server) Integration: Only show jira project keys that sentry has access to

### ISSUE THREAD

**Issue by valentijnscholten** [getsentry/sentry#14614]
## Summary

Currently when creating a new JIRA issue, the dropdown with project keys contains *all* projects in JIRA it seems.  
As a user I want to see only projects that sentry has access to to create issues in.

## Motivation
1) Sentry only has access to a handful of projects, so most project keys result in an error because the sentry jira user has no permission to access these projects.
2) The list is very long.

**Comment by markstory** [comment]
How would sentry know which projects it has access to? We use the [get projects API](https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-rest-api-3-project-get) to get the available projects from Jira. Is there a more appropriate endpoint to use?

**Comment by valentijnscholten** [comment]
When I look at the for get Projects on the JIRA Server edition it says it will (should) only return projects visible to the user. And it will return the list of all projects if performed anonymously. This could indicate that maybe sentry is performing the get Projects call anonymously? Not sure how it works with OAuth tokens in the background.
It could also mean that it works slightly different for the JIRA Cloud edition.

Alternatively the get Permissions API might be helpful, but it feels weird to be using that. I would expect some API call to be available to retrieve projects for the current / logged in user.
https://docs.atlassian.com/software/jira/docs/api/REST/8.3.3/#api/2-getAllPermissions

**Comment by valentijnscholten** [comment]
Did some googling on the atlassian forums and some posts seem to indicate there's no single API call that does this: https://community.atlassian.com/t5/Jira-questions/How-to-list-all-projects-a-user-has-access-to-using-Jira-s-REST/qaq-p/423593

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by valentijnscholten** [comment]
This is now possible in JIRA Server 8.14:
![image](https://user-images.githubusercontent.com/4426050/102065090-6627cc00-3df8-11eb-897c-de9166cd6146.png)
