### ISSUE TITLE
Sentry web UI shows internal server error after upgrade.

### ISSUE THREAD

**Issue by pkd809** [getsentry/sentry#14612]
https://github.com/getsentry/sentry-docs/issues/1196#issuecomment-529280197

Follow the above link.
Also on upgrade it did't ask for username or password.

**Comment by hanguihe** [comment]
mark

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.

Also, you need to provide quite a bit more details instead of just saying "it doesn't work" for someone to be able to help you.
