### ISSUE TITLE
unstructred data value is [Filtered]

### ISSUE THREAD

**Issue by crobinson42** [getsentry/sentry#14617]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I am using `setExtra` to add data for debugging but the dashboard shows the value of the key i set as `[Filtered]`: 
![image](https://user-images.githubusercontent.com/5973579/64546096-dafb8480-d2de-11e9-8c2a-06aa7422724c.png)

```
Sentry.configureScope(scope => {
    scope.setExtra('__debug', JSON.stringify(debug(true)))
  })
```

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by BYK** [comment]
It is probably due to this btw: https://docs.sentry.io/platforms/javascript/data-management/sensitive-data/#server-side-scrubbing
