### ISSUE TITLE
redirect loop when login without organization

### ISSUE THREAD

**Issue by favadi** [getsentry/sentry#1463]
In a fresh sentry 7.4.1 instance, after create an user with:

```
sentry --config=/etc/sentry.conf.py createuser
```

and login, sentry redirect to `https://sentry.local/organizations/new/` and cause a: `This webpage has a redirect loop` error in browser.

If I manually create a record in table `sentry_organizationmember` to set organization for this user, I can log in successfully. 

uwsgi log when redirect loop happens:

```
Mar 18 08:28:52 integration-general-local nginx: https://alerts.local:443/organizations/new/- 192.168.11.4:- "GET /organizations/new/ HTTP/1.1" 0.011 760:302 302 "https://alerts.local/auth/login/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36" "-"
Mar 18 08:28:52 integration-general-local uwsgi-sentry: [pid: 18628|app: 0|req: 12/12] 192.168.11.4 () {44 vars in 1070 bytes} [Wed Mar 18 08:28:52 2015] GET /organizations/new/ => generated 0 bytes in 10 msecs (HTTP/1.1 302) 4 headers in 148 bytes (1 switches on core 0)
Mar 18 08:28:52 integration-general-local nginx: https://alerts.local:443/- 192.168.11.4:- "GET / HTTP/1.1" 0.022 742:320 302 "https://alerts.local/auth/login/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36" "-"
Mar 18 08:28:52 integration-general-local uwsgi-sentry: [pid: 18628|app: 0|req: 13/13] 192.168.11.4 () {44 vars in 1034 bytes} [Wed Mar 18 08:28:52 2015] GET / => generated 0 bytes in 21 msecs (HTTP/1.1 302) 4 headers in 166 bytes (1 switches on core 0)
Mar 18 08:28:52 integration-general-local nginx: https://alerts.local:443/organizations/new/- 192.168.11.4:- "GET /organizations/new/ HTTP/1.1" 0.012 760:302 302 "https://alerts.local/auth/login/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.89 Safari/537.36" "-"
```

**Comment by bclermont** [comment]
:+1:

**Comment by lepilepi** [comment]
:+1:

**Comment by mvaled** [comment]
I'm seeing this in 7.5.0.dev0 (self produced `.tar.gz` at commit 02c840121aae14e9f50fec94a501805fee54429a).  

Strangely in my own development machine this does not happen.

**Comment by mvaled** [comment]
Hi @dcramer,

Could you help us with this?

**Comment by mvaled** [comment]
What I did to keep going was:

    $ pip install ipython
    $ sentry --config=etc/sentry.conf.py shell
    
    >>> from sentry.models import User, Organization
    >>> me = User.objects.get(email='my-email@my-server.com')   # fake email
    >>> org = Organization.objects.create(name='My Org', slug='org', owner=me)
    >>> org.save()

Now I could enter and do the rest of the configuration by the web.

**Comment by favadi** [comment]
On 04/20/2015 11:20 PM, Manuel Vázquez Acosta wrote:
> Now I could enter and do the rest of the configuration by the web.
Or you could use the /admin page to create the organization. :P

**Comment by mvaled** [comment]
Ah! My first though was the web page was broken... I didn't think about
going to /admin directly.

**Comment by dcramer** [comment]
45171045df8e30bb5153405adb34857e78275b13 introduces behavior which ensures members are added to the default org in single org mode
