### ISSUE TITLE
[7.4.1] No events

### ISSUE THREAD

**Issue by 1it** [getsentry/sentry#1464]
raven test http://xxxx@sentry.myhost.com/3
Using DSN configuration:
  http://xxxx@sentry.myhost..com/3

Client configuration:
  servers        : ['http://sentry.myhost..com/api/3/store/']
  project        : 3
  public_key     : xxxx
  secret_key     : xxxx
Sending a test message... success!
Event ID was 'xxxx'

Events by Project
Project 	Accepted 	Rejected 	Total
dev / Backend	101  0 	        101

But: 
No events to show.

We'll notify you if that changes. In the meantime why not take a moment to become more familiar with Sentry.

Any ideas?

My conf vars:
/etc/sentry.conf.py
ABSOLUTE_URL_OVERRIDES 	

{}

ADMINS 	

()

ADMIN_FOR 	

()

ALLOWED_HOSTS 	

('sentry.myhost.com',)

ALLOWED_INCLUDE_ROOTS 	

()

APPEND_SLASH 	

True

AUTHENTICATION_BACKENDS 	

('social_auth.backends.twitter.TwitterBackend', 'social_auth.backends.facebook.FacebookBackend', 'social_auth.backends.google.GoogleBackend', 'social_auth.backends.contrib.github.GithubBackend', 'social_auth.backends.contrib.bitbucket.BitbucketBackend', 'social_auth.backends.contrib.trello.TrelloBackend', 'sentry.utils.auth.EmailAuthBackend')

AUTH_PROVIDERS 	

****************

AUTH_USER_MODEL 	

'sentry.User'

BITBUCKET_CONSUMER_KEY 	

****************

BITBUCKET_CONSUMER_SECRET 	

****************

BROKER_URL 	

'redis://localhost:6379'

CACHES 	

{'default': {'LOCATION': ['127.0.0.1:11211'], 'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache'}}

CACHE_MIDDLEWARE_ALIAS 	

'default'

CACHE_MIDDLEWARE_KEY_PREFIX 	

****************

CACHE_MIDDLEWARE_SECONDS 	

600

CELERYBEAT_SCHEDULE 	

{'sync-options': {'task': 'sentry.tasks.options.sync_options', 'options': {'queue': 'options', 'expires': 10}, 'schedule': datetime.timedelta(0, 10)}, 'check-auth': {'task': 'sentry.tasks.check_auth', 'options': {'queue': 'auth', 'expires': 60}, 'schedule': datetime.timedelta(0, 60)}, 'send-beacon': {'task': 'sentry.tasks.send_beacon', 'options': {'expires': 3600}, 'schedule': datetime.timedelta(0, 3600)}, 'check-alerts': {'task': 'sentry.tasks.check_alerts', 'options': {'queue': 'alerts', 'expires': 60}, 'schedule': datetime.timedelta(0, 60)}, 'flush-buffers': {'task': 'sentry.tasks.process_buffer.process_pending', 'options': {'queue': 'counters-0', 'expires': 10}, 'schedule': datetime.timedelta(0, 10)}}

CELERY_ALWAYS_EAGER 	

False

CELERY_CREATE_MISSING_QUEUES 	

True

CELERY_DEFAULT_EXCHANGE 	

'default'

CELERY_DEFAULT_EXCHANGE_TYPE 	

'direct'

CELERY_DEFAULT_QUEUE 	

'default'

CELERY_DEFAULT_ROUTING_KEY 	

****************

CELERY_DISABLE_RATE_LIMITS 	

True

CELERY_IGNORE_RESULT 	

True

CELERY_IMPORTS 	

('sentry.tasks.beacon', 'sentry.tasks.check_alerts', 'sentry.tasks.check_auth', 'sentry.tasks.cleanup', 'sentry.tasks.deletion', 'sentry.tasks.email', 'sentry.tasks.index', 'sentry.tasks.merge', 'sentry.tasks.store', 'sentry.tasks.options', 'sentry.tasks.post_process', 'sentry.tasks.process_buffer')

CELERY_QUEUES 	

[<unbound Queue 'default' -> Exchange ''(direct) -> 'default'>, <unbound Queue 'alerts' -> Exchange ''(direct) -> 'alerts'>, <unbound Queue 'auth' -> Exchange ''(direct) -> 'auth'>, <unbound Queue 'cleanup' -> Exchange ''(direct) -> 'cleanup'>, <unbound Queue 'sourcemaps' -> Exchange ''(direct) -> 'sourcemaps'>, <unbound Queue 'search' -> Exchange ''(direct) -> 'search'>, <unbound Queue 'events' -> Exchange ''(direct) -> 'events'>, <unbound Queue 'update' -> Exchange ''(direct) -> 'update'>, <unbound Queue 'email' -> Exchange ''(direct) -> 'email'>, <unbound Queue 'options' -> Exchange ''(direct) -> 'options'>, <unbound Queue 'counters-0' -> Exchange counters(direct) -> ''>, <unbound Queue 'triggers-0' -> Exchange triggers(direct) -> ''>]

CELERY_RESULT_BACKEND 	

None

CELERY_ROUTES 	

('sentry.queue.routers.SplitQueueRouter',)

CELERY_SEND_EVENTS 	

False

CELERY_TASK_RESULT_EXPIRES 	

1

COMMENTS_ALLOW_PROFANITIES 	

False

CONF_ROOT 	

'/etc'

CSRF_COOKIE_DOMAIN 	

None

CSRF_COOKIE_HTTPONLY 	

False

CSRF_COOKIE_NAME 	

'csrftoken'

CSRF_COOKIE_PATH 	

'/'

CSRF_COOKIE_SECURE 	

False

CSRF_FAILURE_VIEW 	

'sentry.web.frontend.csrf_failure.view'

DATABASES 	

****************

DATABASE_ROUTERS 	

[]

DATETIME_FORMAT 	

'N j, Y, P'

DATETIME_INPUT_FORMATS 	

('%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%Y-%m-%d', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%Y', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M', '%m/%d/%y')

DATE_FORMAT 	

'N j, Y'

DATE_INPUT_FORMATS 	

('%Y-%m-%d', '%m/%d/%Y', '%m/%d/%y', '%b %d %Y', '%b %d, %Y', '%d %b %Y', '%d %b, %Y', '%B %d %Y', '%B %d, %Y', '%d %B %Y', '%d %B, %Y')

DEBUG 	

True

DEBUG_PROPAGATE_EXCEPTIONS 	

False

DECIMAL_SEPARATOR 	

'.'

DEFAULT_CHARSET 	

'utf-8'

DEFAULT_CONTENT_TYPE 	

'text/html'

DEFAULT_EXCEPTION_REPORTER_FILTER 	

'django.views.debug.SafeExceptionReporterFilter'

DEFAULT_FILE_STORAGE 	

'django.core.files.storage.FileSystemStorage'

DEFAULT_FROM_EMAIL 	

'webmaster@localhost'

DEFAULT_INDEX_TABLESPACE 	

''

DEFAULT_TABLESPACE 	

''

DISALLOWED_USER_AGENTS 	

()

EMAIL_BACKEND 	

'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST 	

'localhost'

EMAIL_HOST_PASSWORD 	

****************

EMAIL_HOST_USER 	

''

EMAIL_PORT 	

25

EMAIL_SUBJECT_PREFIX 	

'[Sentry] '

EMAIL_USE_TLS 	

False

FACEBOOK_API_SECRET 	

****************

FACEBOOK_APP_ID 	

''

FACEBOOK_EXTENDED_PERMISSIONS 	

['email']

FILE_CHARSET 	

'utf-8'

FILE_UPLOAD_HANDLERS 	

('django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler')

FILE_UPLOAD_MAX_MEMORY_SIZE 	

2621440

FILE_UPLOAD_PERMISSIONS 	

None

FILE_UPLOAD_TEMP_DIR 	

None

FIRST_DAY_OF_WEEK 	

0

FIXTURE_DIRS 	

()

FORCE_SCRIPT_NAME 	

None

FORMAT_MODULE_PATH 	

None

GITHUB_API_SECRET 	

****************

GITHUB_APP_ID 	

''

GOOGLE_OAUTH2_CLIENT_ID 	

''

GOOGLE_OAUTH2_CLIENT_SECRET 	

****************

IGNORABLE_404_URLS 	

()

INITIAL_CUSTOM_USER_MIGRATION 	

'0108_fix_user'

INSTALLED_APPS 	

('django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.messages', 'django.contrib.sessions', 'django.contrib.sites', 'django.contrib.staticfiles', 'captcha', 'crispy_forms', 'djcelery', 'gunicorn', 'kombu.transport.django', 'raven.contrib.django.raven_compat', 'rest_framework', 'sentry', 'sentry.nodestore', 'sentry.search', 'sentry.lang.javascript', 'sentry.plugins.sentry_interface_types', 'sentry.plugins.sentry_mail', 'sentry.plugins.sentry_urls', 'sentry.plugins.sentry_useragents', 'sentry.plugins.sentry_webhooks', 'social_auth', 'south', 'sudo', 'sentry_youtrack')

INTERNAL_IPS 	

('127.0.0.1',)

LANGUAGES 	

(('af', 'Afrikaans'), ('ar', 'Arabic'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('el', 'Greek'), ('en', 'English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('ga', 'Irish'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hu', 'Hungarian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmal'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sv-se', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-cn', 'Simplified Chinese'), ('zh-cn', 'Traditional Chinese'))

LANGUAGES_BIDI 	

('he', 'ar', 'fa', 'ur')

LANGUAGE_CODE 	

'en-us'

LANGUAGE_COOKIE_NAME 	

'django_language'

LOCALE_PATHS 	

('/var/www/sentry/local/lib/python2.7/site-packages/sentry/locale',)

LOGGING 	

{'loggers': {'static_compiler': {'level': 'INFO'}, 'sentry': {'level': 'ERROR'}, 'sentry.coreapi': {'formatter': 'client_info'}, 'toronado.cssutils': {'propagate': False, 'level': 'ERROR'}, 'sentry.rules': {'propagate': False, 'handlers': ['console']}, 'sentry.errors': {'propagate': False, 'handlers': ['console']}, 'django.request': {'handlers': ['console'], 'propagate': False, 'level': 'ERROR'}}, 'disable_existing_loggers': True, 'handlers': {'sentry': {'class': 'raven.contrib.django.handlers.SentryHandler', 'filters': ['sentry:internal'], 'level': 'ERROR'}, 'console': {'formatter': 'simple', 'class': 'logging.StreamHandler', 'level': 'WARNING'}}, 'formatters': {'simple': {'format': '[%(levelname)s] %(message)s'}, 'client_info': {'format': '[%(levelname)s] %(project_slug)s/%(team_slug)s %(message)s'}}, 'version': 1, 'filters': {'sentry:internal': {'()': 'sentry.utils.raven.SentryInternalFilter'}}, 'root': {'handlers': ['console', 'sentry']}}

LOGGING_CONFIG 	

'django.utils.log.dictConfig'

LOGIN_REDIRECT_URL 	

<django.utils.functional.__proxy__ object at 0x1f325d0>

LOGIN_URL 	

<django.utils.functional.__proxy__ object at 0x1f32710>

LOGOUT_URL 	

'/accounts/logout/'

MAILGUN_API_KEY 	

****************

MAINTENANCE 	

False

MANAGERS 	

()

MEDIA_ROOT 	

'/tmp/sentry-media'

MEDIA_URL 	

''

MESSAGE_STORAGE 	

'django.contrib.messages.storage.fallback.FallbackStorage'

MIDDLEWARE_CLASSES 	

('sentry.middleware.maintenance.ServicesUnavailableMiddleware', 'sentry.middleware.proxy.SetRemoteAddrFromForwardedFor', 'sentry.middleware.debug.NoIfModifiedSinceMiddleware', 'django.middleware.common.CommonMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'sentry.middleware.sudo.SudoMiddleware', 'sentry.middleware.locale.SentryLocaleMiddleware', 'sentry.middleware.social_auth.SentrySocialAuthExceptionMiddleware', 'django.middleware.locale.LocaleMiddleware', 'django.contrib.messages.middleware.MessageMiddleware')

MONTH_DAY_FORMAT 	

'F j'

NUMBER_GROUPING 	

0

PASSWORD_HASHERS 	

****************

PASSWORD_RESET_TIMEOUT_DAYS 	

****************

PREPEND_WWW 	

False

PROFANITIES_LIST 	

()

PROJECT_ROOT 	

'/var/www/sentry/local/lib/python2.7/site-packages/sentry'

RECAPTCHA_PRIVATE_KEY 	

****************

RECAPTCHA_PUBLIC_KEY 	

****************

REST_FRAMEWORK 	

{'TEST_REQUEST_DEFAULT_FORMAT': 'json', 'DEFAULT_PERMISSION_CLASSES': ('sentry.api.permissions.NoPermission',)}

ROOT_URLCONF 	

'sentry.conf.urls'

SECRET_KEY 	

****************

SECURE_PROXY_SSL_HEADER 	

None

SEND_BROKEN_LINK_EMAILS 	

False

SENTRY_ADMIN_EMAIL 	

'tuzhilkin@myhost.com'

SENTRY_ALLOW_ORIGIN 	

None

SENTRY_ALLOW_PUBLIC_PROJECTS 	

True

SENTRY_ALLOW_REGISTRATION 	

True

SENTRY_BEACON 	

True

SENTRY_BUFFER 	

'sentry.buffer.redis.RedisBuffer'

SENTRY_BUFFER_OPTIONS 	

{}

SENTRY_CACHE 	

'sentry.cache.redis.RedisCache'

SENTRY_CACHE_BACKEND 	

'default'

SENTRY_CACHE_OPTIONS 	

{}

SENTRY_CLIENT 	

'sentry.utils.raven.SentryInternalClient'

SENTRY_DEBUG 	

True

SENTRY_DEFAULT_MAX_EVENTS_PER_MINUTE 	

'90%'

SENTRY_DISALLOWED_IPS 	

''

SENTRY_ENABLE_EMAIL_REPLIES 	

False

SENTRY_ENABLE_EXPLORE_CODE 	

False

SENTRY_ENABLE_EXPLORE_USERS 	

True

SENTRY_ENABLE_INVITES 	

True

SENTRY_ENDPOINT 	

None

SENTRY_FEATURES 	

{'social-auth:register': True, 'auth:register': True, 'teams:create': True, 'organizations:sso': False, 'organizations:create': True}

SENTRY_FILESTORE 	

'django.core.files.storage.FileSystemStorage'

SENTRY_FILESTORE_OPTIONS 	

{'location': '/var/www/sentry/tmp'}

SENTRY_FILTERS 	

('sentry.filters.StatusFilter',)

SENTRY_FRONTEND_PROJECT 	

None

SENTRY_GRAVATAR_BASE_URL 	

'https://secure.gravatar.com'

SENTRY_IGNORE_EXCEPTIONS 	

('OperationalError',)

SENTRY_INTERFACES 	

{'stacktrace': 'sentry.interfaces.stacktrace.Stacktrace', 'sentry.interfaces.User': 'sentry.interfaces.user.User', 'sentry.interfaces.Exception': 'sentry.interfaces.exception.Exception', 'logentry': 'sentry.interfaces.message.Message', 'sentry.interfaces.Message': 'sentry.interfaces.message.Message', 'user': 'sentry.interfaces.user.User', 'query': 'sentry.interfaces.query.Query', 'sentry.interfaces.Query': 'sentry.interfaces.query.Query', 'exception': 'sentry.interfaces.exception.Exception', 'request': 'sentry.interfaces.http.Http', 'sentry.interfaces.Http': 'sentry.interfaces.http.Http', 'sentry.interfaces.Template': 'sentry.interfaces.template.Template', 'template': 'sentry.interfaces.template.Template', 'sentry.interfaces.Stacktrace': 'sentry.interfaces.stacktrace.Stacktrace'}

SENTRY_LOGIN_URL 	

None

SENTRY_LOG_DIR 	

'/var/log/sentry'

SENTRY_MANAGED_USER_FIELDS 	

('email',)

SENTRY_MAX_DICTIONARY_ITEMS 	

50

SENTRY_MAX_EXCEPTIONS 	

25

SENTRY_MAX_EXTRA_VARIABLE_SIZE 	

4096

SENTRY_MAX_HTTP_BODY_SIZE 	

2048

SENTRY_MAX_MESSAGE_LENGTH 	

8192

SENTRY_MAX_SAMPLE_RATE 	

10000

SENTRY_MAX_SAMPLE_TIME 	

10000

SENTRY_MAX_STACKTRACE_FRAMES 	

25

SENTRY_MAX_VARIABLE_SIZE 	

512

SENTRY_METRICS_PREFIX 	

''

SENTRY_NODESTORE 	

'sentry.nodestore.django.DjangoNodeStorage'

SENTRY_NODESTORE_OPTIONS 	

{}

SENTRY_OPTIONS 	

{}

SENTRY_PROJECT 	

1

SENTRY_PUBLIC 	

False

SENTRY_PUBLIC_ENDPOINT 	

None

SENTRY_QUOTAS 	

'sentry.quotas.redis.RedisQuota'

SENTRY_QUOTA_OPTIONS 	

{}

SENTRY_RATELIMITER 	

'sentry.ratelimits.redis.RedisRateLimiter'

SENTRY_RATELIMITER_OPTIONS 	

{}

SENTRY_RAVEN_JS_URL 	

'cdn.ravenjs.com/1.1.15/jquery,native/raven.min.js'

SENTRY_REDIS_OPTIONS 	

****************

SENTRY_SAMPLE_DATA 	

True

SENTRY_SAMPLE_RATES 	

((50, 1), (1000, 2), (10000, 10), (100000, 50), (1000000, 300), (10000000, 2000))

SENTRY_SAMPLE_TIMES 	

((3600, 1), (360, 10), (60, 60))

SENTRY_SCRAPE_JAVASCRIPT_CONTEXT 	

True

SENTRY_SEARCH 	

'sentry.search.django.DjangoSearchBackend'

SENTRY_SEARCH_OPTIONS 	

{}

SENTRY_SMTP_HOST 	

'localhost'

SENTRY_SMTP_HOSTNAME 	

'localhost'

SENTRY_SMTP_PORT 	

1025

SENTRY_SOURCE_FETCH_TIMEOUT 	

5

SENTRY_SYSTEM_MAX_EVENTS_PER_MINUTE 	

0

SENTRY_TSDB 	

'sentry.tsdb.redis.RedisTSDB'

SENTRY_TSDB_OPTIONS 	

{}

SENTRY_TSDB_ROLLUPS 	

((10, 30), (3600, 168))

SENTRY_UDP_HOST 	

'localhost'

SENTRY_UDP_PORT 	

9001

SENTRY_URL_PREFIX 	

'http://sentry.myhost.com'

SENTRY_USE_BIG_INTS 	

True

SENTRY_USE_IPV6_UDP 	

False

SENTRY_WEB_HOST 	

'0.0.0.0'

SENTRY_WEB_OPTIONS 	

{'workers': 3, 'secure_scheme_headers': {'X-FORWARDED-PROTO': 'http'}}

SENTRY_WEB_PORT 	

9000

SERVER_EMAIL 	

'sentry@myhost.com'

SESSION_CACHE_ALIAS 	

'default'

SESSION_COOKIE_AGE 	

1209600

SESSION_COOKIE_DOMAIN 	

None

SESSION_COOKIE_HTTPONLY 	

True

SESSION_COOKIE_NAME 	

'sentrysid'

SESSION_COOKIE_PATH 	

'/'

SESSION_COOKIE_SECURE 	

False

SESSION_ENGINE 	

'django.contrib.sessions.backends.signed_cookies'

SESSION_EXPIRE_AT_BROWSER_CLOSE 	

False

SESSION_FILE_PATH 	

None

SESSION_SAVE_EVERY_REQUEST 	

False

SESSION_SERIALIZER 	

'django.contrib.sessions.serializers.PickleSerializer'

SETTINGS_MODULE 	

'sentry_config'

SHORT_DATETIME_FORMAT 	

'm/d/Y P'

SHORT_DATE_FORMAT 	

'm/d/Y'

SIGNING_BACKEND 	

'django.core.signing.TimestampSigner'

SITE_ID 	

1

SOCIAL_AUTH_DEFAULT_USERNAME 	

<function <lambda> at 0x1f3a6e0>

SOCIAL_AUTH_PIPELINE 	

('social_auth.backends.pipeline.user.get_username', 'social_auth.backends.pipeline.social.social_auth_user', 'social_auth.backends.pipeline.associate.associate_by_email', 'social_auth.backends.pipeline.misc.save_status_to_session', 'sentry.utils.social_auth.create_user_if_enabled', 'social_auth.backends.pipeline.social.associate_user', 'social_auth.backends.pipeline.social.load_extra_data', 'social_auth.backends.pipeline.user.update_user_details', 'social_auth.backends.pipeline.misc.save_status_to_session')

SOCIAL_AUTH_PROTECTED_USER_FIELDS 	

['email']

SOCIAL_AUTH_USER_MODEL 	

'sentry.User'

STATICFILES_DIRS 	

()

STATICFILES_FINDERS 	

('django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder')

STATICFILES_STORAGE 	

'django.contrib.staticfiles.storage.StaticFilesStorage'

STATIC_ROOT 	

'/var/www/sentry/lib/python2.7/site-packages/sentry/static'

STATIC_URL 	

'/_static/'

STATSD_CLIENT 	

'django_statsd.clients.null'

TEMPLATE_CONTEXT_PROCESSORS 	

('django.contrib.auth.context_processors.auth', 'django.contrib.messages.context_processors.messages', 'django.core.context_processors.csrf', 'social_auth.context_processors.social_auth_by_name_backends', 'social_auth.context_processors.social_auth_backends', 'social_auth.context_processors.social_auth_by_type_backends', 'social_auth.context_processors.social_auth_login_redirect')

TEMPLATE_DEBUG 	

True

TEMPLATE_DIRS 	

('/var/www/sentry/local/lib/python2.7/site-packages/sentry/templates',)

TEMPLATE_LOADERS 	

('django.template.loaders.filesystem.Loader', 'django.template.loaders.app_directories.Loader')

TEMPLATE_STRING_IF_INVALID 	

''

TEST_RUNNER 	

'django.test.runner.DiscoverRunner'

THOUSAND_SEPARATOR 	

','

TIME_FORMAT 	

'P'

TIME_INPUT_FORMATS 	

('%H:%M:%S', '%H:%M:%S.%f', '%H:%M')

TIME_ZONE 	

'UTC'

TRANSACTIONS_MANAGED 	

False

TRELLO_API_KEY 	

****************

TRELLO_API_SECRET 	

****************

TWITTER_CONSUMER_KEY 	

****************

TWITTER_CONSUMER_SECRET 	

****************

USE_ETAGS 	

False

USE_I18N 	

True

USE_L10N 	

True

USE_THOUSAND_SEPARATOR 	

False

USE_TZ 	

True

USE_X_FORWARDED_HOST 	

False

WSGI_APPLICATION 	

None

X_FRAME_OPTIONS 	

'SAMEORIGIN'

YEAR_MONTH_FORMAT 	

'F Y'

**Comment by dcramer** [comment]
You need to look into the worker logs. Something is not processing things correctly which generally signals a misconfiguration (i.e. the cache is wrong, the broker is wrong, the workers aren't even running,e tc).

**Comment by serggl** [comment]
having the same issue.
Turns out that changing CELERY_ALWAYS_EAGER to True is fixing the issue.
My redis server settings seems to be ok, so Im not sure if this is a configuration issue
