### ISSUE TITLE
Asking for feedback without an exception

### ISSUE THREAD

**Issue by Avamander** [getsentry/sentry#14645]
It would be really nice if I could somehow launch the feedback dialogue without providing an event ID. Sometimes one might just want to capture user's problems they encountered.

In addition to that, if Sentry decides to return 403 it would be really nice if it said what the issue was in the console. I provided the DSN and event ID generated by as required it and it just errors out.

**Comment by untitaker** [comment]
Hi, I moved this to Sentry itself because it has nothing to do with the SDK.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by Avamander** [comment]
I have an alternative implementation for now, but this could just be an official feature indeed.
