### ISSUE TITLE
Error Using second U2F Key

### ISSUE THREAD

**Issue by TeamTeaTime** [getsentry/sentry#14656]
## Important Details

How are you running Sentry?

* [X] On-Premise docker [Version 9.1.2-onbuild]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

U2F security key works correctly if there is only one bound to account, but if I register a second one then only the one that was registered first will work. Attempting to use the second registered key throws:
 ```
ValueError
Wrong challenge! Was: "o'hy&\xcc\x90\xeeb\xa3\xd7\x7fq\xe2\x8eo\x97\xa9\xf9\xc2\x880(\xb3\xe8Pn\xbe\xc0\xbc\xab\xbe", expecting: "\\\x14\xfd.x\xb5\xa3\xff'\x01\xe5\xe4y\xfc\xf7IO\x03\x0f\x88p:\tb2&;\x83\x9en2\x89"
```
Devices in use here are Yubikey 5 NFC (first enrolled) and Yubikey 5 Nano. I was able to get both devices working when they were the only one registered or the first one registered so it doesn't seem to be device specific. 

## Steps to Reproduce

1. Sign in
2. Navigate to User Settings -> Security -> U2F 
3. Follow steps to register first U2F Device
4. Sign out and sign back in using first U2F key as second factor (this works)
5. Navigate to User Settings -> Security -> U2F 
6. Follow steps to register second U2F Device 
7. Sign out and sign back in using second U2F device (this fails and throws the exception and error page)
8. Insert first U2F key and try to sign in again (this succeeds)

Good items to include here include:

```
ValueError: Wrong challenge! Was: "o'hy&\xcc\x90\xeeb\xa3\xd7\x7fq\xe2\x8eo\x97\xa9\xf9\xc2\x880(\xb3\xe8Pn\xbe\xc0\xbc\xab\xbe", expecting: "\\\x14\xfd.x\xb5\xa3\xff'\x01\xe5\xe4y\xfc\xf7IO\x03\x0f\x88p:\tb2&;\x83\x9en2\x89"
  File "django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "sentry/web/frontend/base.py", line 225, in dispatch
    return self.handle(request, *args, **kwargs)
  File "sentry/web/frontend/twofactor.py", line 151, in handle
    if interface.validate_response(request, challenge, response):
  File "sentry/models/authenticator.py", line 578, in validate_response
    self.get_u2f_devices(), challenge, response, self.u2f_facets
  File "u2flib_server/u2f.py", line 86, in verify_authenticate
    valid_facets
  File "u2flib_server/u2f_v2.py", line 240, in verify_authenticate
    "navigator.id.getAssertion", valid_facets)
  File "u2flib_server/u2f_v2.py", line 180, in _validate_client_data
    client_data.challenge, challenge))
```

### What you expected to happen
Login should succeed with either registered U2F keys.

### Possible Solution

Looking at the stack trace and the latest code in the sentry github repo it looks like there is updated U2F handling that is not in the 9.1.2-onbuild Docker image in sentry/models/authenticator.py. 

https://github.com/getsentry/sentry/commit/844de0cf930da241fbe870485c97d579b7069c35
```
    def validate_response(self, request, challenge, response):
        try:
            counter, touch = u2f.verify_authenticate(
                self.get_u2f_devices(), challenge, response, self.u2f_facets
            )
        except (InvalidSignature, InvalidKey, StopIteration):
            return False
        return True
```
vs
```
def validate_response(self, request, challenge, response):
        try:
            u2f.complete_authentication(challenge, response, self.u2f_facets)
        except (InvalidSignature, InvalidKey, StopIteration):
            return False
        return True
```

I haven't tried to test building directly from the git repo yet though.

**Comment by brycied00d** [comment]
I think this may be a duplicate of #14018

**Comment by malexmave** [comment]
I did some testing on my own Sentry instance, as I am in the same situation. Sentry 9.1.2 on-premise with Docker.

Situation: 2 Yubikeys (1 GitHub-branded, one Yubikey 5 NFC). Steps:

1. Set up Yubikey 5
2. Set up GitHub Yubikey
3. Sign out, sign back in with Yubikey 5 (works)
4. Sign out, sign back in with GitHub Yubikey (error as described above)
5. Sign in with Yubikey 5. Remove Yubikey 5 from account. Sign out.
6. Sign in with GitHub Yubikey. Works.
7. Add Yubikey 5 to account. Sign out.
8. Sign back in with Yubikey 5. Error as described above.
9. Sign back in with GitHub Yubikey. Still works.

This seems to indicate that it is not a problem with the GitHub Yubikey (as suspected in #14018), but with the number and order of Yubikeys that are added to the account.

Let me know if I can perform any additional testing to help debug this.

**Comment by mastacheata** [comment]
> I think this may be a duplicate of #14018

Actually, the other way around. My issue was there first, but I had mistaken this to be about the brand/model of the security key.

Tried what @malexmave @TeamTeaTime were suspecting and I can confirm this is about the number of keys registered.

In U2F the "relying party" (here: Sentry) sends a list of key identifiers and corresponding challenges and then requests the user to sign one of the challenges with their corresponding key and send the signature back to the "relying party".

Apparently the problem lies in Sentry not picking the right challenge to verify, but always using the first one instead. That should make this problem a lot easier to find and fix.

**Comment by BYK** [comment]
I think this may be fixed by https://github.com/getsentry/sentry/pull/15896 now. @EvanPurkhiser @wedamija - thoughts?

**Comment by mastacheata** [comment]
Nope, this can't be the solution.

If you view the full stack trace inside sentry for the exception, you can see that the client sends the challenge of the first key and not the one associated with the keyId.

Not sure if this is actually a problem in Sentry or in **ALL** browsers I tried.
The browser u2f implementation seems to expect the challenge to be equal across all keys, but the implementation by YubiCo allows to have individual challenges per key and that is how Sentry implemented it as well.

I have 2 keys registered in my sentry instance and get the correct authenticationRequests for both of them with individual challenges:

```
{
  authenticateRequests: [
    {
      appId: [Filtered],
      challenge: u'65ps...',
      keyHandle: u'dn0v...',
      version: u'U2F_V2'
    }, 
    {
      appId: [Filtered],
      challenge: u'aPi8...',
      keyHandle: u'_RYTh...',
      version: u'U2F_V2'
    }
  ]
}
```

The response contains the keyHandle corresponding to the second key `u'_RYTh...'`

Digging deeper: `u2flib_server/u2f.py$verify_authenticate` identifies the correct device from the devices list.

Digging 2 steps deeper again, we can finally see the decoded clientData and ohh, what do we see there: The client says it is the right key, but identifies the wrong challenge from the first key:

```
client_data 

{
  challenge: u'65ps...',
  origin: u'https://sentry.ymoq.de',
  typ: u'navigator.id.getAssertion'
}
```

The `65ps...` challenge matches the `dn0v...` key, but the challenge for the key I inserted (`_RYTh...`) was supposed to be `aPi8...`

**Comment by mastacheata** [comment]
According to the FIDO U2F JavaScript API specification there should be only one challenge across all keys.

See the U2fSignRequest specification:
https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-javascript-api-v1.2-ps-20170411.html#idl-def-U2fSignRequest

The misinterpretation supposedly stems from the first version of the U2F protocol.
Back then there was no dedicated object for describing a key, instead you would send a list of SignRequests, one for each key known to the relying party. In that format you can indeed send a separate challenge for each keyHandle.

See here: https://fidoalliance.org/specs/fido-u2f-v1.0-ps-20141009/fido-u2f-javascript-api-ps-20141009.html#idl-def-SignRequest

**Comment by mastacheata** [comment]
This should be solved already since in the current master code of Sentry you are using version 5 of the yubico python-u2flib-server which will also follow along with the current gen FIDO-U2F message format from 2017.

See:
https://github.com/getsentry/sentry/blob/03071245943f3d66389710fd71a95ac594127751/src/sentry/models/authenticator.py#L563

**Comment by BYK** [comment]
Closing due to lack of response and @mastacheata's latest claim. Will reopen if this is still broken.

**Comment by TeamTeaTime** [comment]
Sorry for the delay. I have upgraded my Sentry instances to 10.1.0.dev0 (d7283cc) and 10.1.0.dev0 (1d4ac51) respectively and it seems to be fixed when I tested on both of them. Thank you!
