### ISSUE TITLE
Feature Request: Add Rules in User Level 

### ISSUE THREAD

**Issue by abhijo89** [getsentry/sentry#1466]
Currently sentry allows notifications on a global manner. I.e sentry notification rules apply to all the users irrespective of user level. So all the users associated to a project will get the same kind of notification irrespective of whether he is an admin, or a developer, or a tester.  I am requesting you to provide me  a way where each user will be able to set his own sentry rules (custom) so that each user gets notifications that he is interested in.

**Comment by dcramer** [comment]
This feature request has come up before, but it's scary complex to solve this from a UI point of view. I'm confident in saying until there's clear way to do that, that we won't make any effort here.

**Comment by BYK** [comment]
Glad to report that we now have a much better alerts and notifications system with finer-grained controls. Thanks for your input!
