### ISSUE TITLE
Support trusted-types reports delivered as CSP violations

### ISSUE THREAD

**Issue by shekyan** [getsentry/sentry#14698]
## Summary
[Trusted Types API](https://wicg.github.io/trusted-types/dist/spec/) uses CSP reporting to deliver violations. Sentry refuses to accept those because `Invalid security report: u'trusted-types' is not one of ['base-uri', 'child-src', 'connect-src', 'default-src', 'font-src', 'form-action', 'frame-ancestors', 'frame-src', 'img-src', 'manifest-src', 'media-src', 'object-src', 'plugin-types', 'prefetch-src', 'referrer', 'script-src', 'script-src-attr', 'script-src-elem', 'style-src', 'style-src-elem', 'style-src-attr', 'upgrade-insecure-requests', 'worker-src']`

## Motivation

Trusted Types is a promising API that helps eliminate DOM XSS in the document. 

## Additional Context

[Changes](https://wicg.github.io/trusted-types/dist/spec/#csp-violation-object-hdr) to violation object

**Comment by artursvonda** [comment]
Bump

**Comment by markstory** [comment]
My concern with trusted-types is that it is still in the draft stage, and that it is only implemented in a single browser.

**Comment by oioki** [comment]
For the reference, Trusted Types (and some other missing CSP directives) are supported since https://github.com/getsentry/relay/pull/876
