### ISSUE TITLE
Allow disabling missing source code error for node_modules

### ISSUE THREAD

**Issue by laurentgoudet** [getsentry/sentry#14700]
By default, Sentry shows an error in the UI when the source code for some `node_modules` was not uploaded as part of the release.

<img width="805" alt="Screen Shot 2019-09-13 at 10 27 02" src="https://user-images.githubusercontent.com/2169585/64848273-1cf33600-d611-11e9-80ad-0e1c9db6191e.png">

However, most Node.js projects do not upload their `node_modules` sourcemaps to Sentry, even Sentry's own [Webpack plugin](https://github.com/getsentry/sentry-webpack-plugin) defaults to ignoring `node_modules`. Reason are:
- `node_modules` is huge. The Sentry CLI finds 57000 files in mine. With the recent parallel upload fixes in the CLI, it only takes a couple of minutes to upload the 150MB of compressed files, but then Sentry takes ages to process them on the backend (`--wait` flag)
- server-side code isn't minified, so source maps are much less useful than for client-side JS projects. They are still nice for your own code, but I don't really care about them for my app dependencies (as most people probably). In addition, seeing the original file paths of the `node_modules` source code is more confusing than anything, as it's not immediately obvious which module these files are coming from, when sourcemaps for `node_modules` dependencies are uploaded

<img width="750" alt="Screen Shot 2019-09-13 at 10 43 33" src="https://user-images.githubusercontent.com/2169585/64849742-524d5300-d614-11e9-84b8-a479515cac50.png">
 
- Lastly, `node_modules` sourcemaps aren't always properly generated for all modules (the Sentry CLI shows thousands of "could not determine a source map reference" errors), and making all the modules fix their sourcemaps upstream isn't really an option.

Allowing users to disable that missing source code error in the UI on a per-project basis would make Node.js users Sentry experience nicer. Or maybe for server-side JS errors it could default to only being shown for `in_app` frames, although a global toggle would allow people to not use sourcemaps at all if they which.

**Comment by lobsterkatie** [comment]
Should be fixed by #17538, which will get deployed in a few hours. Please let me know if not.
