### ISSUE TITLE
Source maps do not work - they work in all browsers

### ISSUE THREAD

**Issue by iongion** [getsentry/sentry#14705]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [x] Other

Running on S3, served by CloudFront, but I do not understand the question, I don't actually run Sentry, I use Sentry for javascript in a React app.

## Description

The webpack 4.x **dev-tool** I use is **source-map**.
The source maps work in all browsers.

[What happened]

Sentry shows traces of compressed / minified / mangled code, not using the source map at all, like this:

![image](https://user-images.githubusercontent.com/867609/64863952-45415b80-d636-11e9-9a67-25427c8d7e23.png)

Which is quite useless

## Steps to Reproduce

**I start by mentioning that I cannot upload source maps to Sentry due to deployment legal implications**

1. Read everything from here and did all as instructed https://docs.sentry.io/platforms/javascript/sourcemaps/

2. Enabled this toggle

![image](https://user-images.githubusercontent.com/867609/64863811-04494700-d636-11e9-911a-3fdf7d2f2853.png)

2. Follow documentation of using webpack devtool to generated sourcemap 

This is the source map specifier generated by the **devtool**

![image](https://user-images.githubusercontent.com/867609/64863536-576eca00-d635-11e9-91a5-1a593e62221c.png)

And this is the url that sentry loads

![image](https://user-images.githubusercontent.com/867609/64863564-6f464e00-d635-11e9-8401-be2c1e1c4136.png)

They are both running side by side on the webserver (s3 with cloudfront)

3. Read this and do all as instructed https://blog.sentry.io/2018/10/18/4-reasons-why-your-source-maps-are-broken

### What you expected to happen

I expect source maps to work and have real useful stack traces, like browsers do when they fetch the source maps accordingly.

### Possible Solution

None, for sure in my case I cannot upload the source maps to Sentry directly and that option is not possible.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
