### ISSUE TITLE
Single organization mode for on-premise installations

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1471]
Sentry has a "public" mode which over the years has become a "I'm running this on-premise and all these features are annoying and in my way". We want to remove this feature and switch it out with something that more appropriately describes goals: single organization (also commonly called a single user mode).

Here's what I imagine for the feature list:

- Single organization mode is enabled with ``SENTRY_SINGLE_ORGANIZATION = True``
- The default settings enable single org mode
- The 'default' organization that is created is now used for everything
- The login page is always the organization login page (thus forcing SSO functionality)
- User registration becomes implicitly based on the organization's auth settings
- Organization creation functions are disabled, as is the ability to remove an organization
- ``SENTRY_PUBLIC`` is deprecated (and forces ``SENTRY_SINGLE_ORGANIZATION = True``)
- As an organization setting (and the default for new orgs), we allow members to join/leave teams themselves

Future features might also include:

- URLs are simplified (or changed) as the organization slug isnt useful

**Comment by georgexsh** [comment]
+1

**Comment by abhijo89** [comment]
+1

**Comment by davewongillies** [comment]
:+1: I was just going through the issues hoping to find something like this

**Comment by codekitchen** [comment]
+1, especially allowing members to join/leave teams themselves would make a lot of things so much easier

**Comment by simonista** [comment]
+1

**Comment by mcwqy9** [comment]
+:100:

**Comment by BlueMoebius** [comment]
+1

**Comment by dcramer** [comment]
This is done.

**Comment by tlvenn** [comment]
Sorry for bumping this old topic but has anyting been done to simplify URL as mentioned above as future features ?

Right now, when installed (8.11), I end up with `sentry.mydomain.com/sentry/` while ideally i would like to see `sentry.mydomain.com/`.

Thanks

**Comment by dcramer** [comment]
@tlvenn you're doing something odd in your configuration if you have a subpath set. By default we don't do this, and its something we recommend against in your configuration.

For more help, please see our support options:

https://sentry.io/support/

**Comment by mattrobenolt** [comment]
> you're doing something odd in your configuration if you have a subpath set

I think he means literally that the single organization's slug is "sentry", so he wants that at the root since there won't be multiple.

If this is the case, we're definitely not going to be doing that work. You can always rename the organization and rename it's slug to be something other than `sentry`.

**Comment by tlvenn** [comment]
Yes you are correct @mattrobenolt, since there is a single org only which happens to be named `sentry` by default, the url could be simplified to omit it. I understand your position Matt, no worry, I just wanted to make sure I was not missing something. Thanks.
