### ISSUE TITLE
Is there a setting to decrease data retention in sentry from 90 days to less. 

### ISSUE THREAD

**Issue by chowmean** [getsentry/sentry#14729]
We need to reduce the retention time in Postgres. Is there any setting available and if not is there any plan for the same?

**Comment by md-mg** [comment]
you mean something like
`sentry cleanup --help`

**Comment by chowmean** [comment]
@md-mg I need this to happen on a regular basis. As in I don't want to keep the events data in RDS for more than 15 days. Any solution for this in configs?

**Comment by Nemesarial** [comment]
Yes we need this too. Also, since we're running dev and staging environments on the same sentry instance, we need to set different rules for different environments. For dev, we don't want retention for more than a day or two.

**Comment by BYK** [comment]
This is now added for Sentry v10 over at the on-premise repo: https://github.com/getsentry/onpremise#event-retention

Closing in favor of that.
