### ISSUE TITLE
Add setting for default time zone (end-user)

### ISSUE THREAD

**Issue by btidor** [getsentry/sentry#1472]
To reproduce:
  1. In `sentry.config.py`, set `TIME_ZONE` to `America/New_York`.
  2. Create a new organization, team and project under a user account with no display time zone set.
  3. From another server, record an event using the Python client's `captureMessage()` method.
  4. In the web interface, go to the project's stream and click on the error.

Result: the displayed timestamp will be one hour in the future. In the stream and on the group page, a relative time of "in one hour" will be shown.

It is currently DST, and the times on my server and client are synchronized. The raw timestamp sent by the client is `u'2015-03-28T00:55:34Z'`, which is correct, but I think that `process_data_timestamp()` in `coreapi.py` is introducing an error.

**Comment by dcramer** [comment]
I would say, at the very least, that changing TIME_ZONE is not a supported flow.

What's the main goal you have of changing it?

**Comment by btidor** [comment]
Ah. I'd really like to change the default time zone for users. When the option isn't set, it seems to default to TIME_ZONE.

**Comment by dcramer** [comment]
I see no reason why we couldn't provide some kind of SENTRY_DEFAULT_TIME_ZONE (or similar) setting. We'll want to keep TIME_ZONE to UTC simply because it makes everything else way more difficult to maintain if the database is in some other timezone.

Going to update this ticket to reflect that.

**Comment by dansajner** [comment]
@dcramer I switched TIME_ZONE to 'America/New_York' months ago per my user's requests for local timezone and realized this same issue when DST kicked in.  I attempted `TIME_ZONE = None` as suggested here https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py#L88 but that led to 500 errors when trying to view errors in the UI. (Stack trace here: https://gist.github.com/dansajner/00a40e192006ae930970)

It sounds like you do not recommend setting TIME_ZONE to anything other than 'UTC' at this time.  Is that correct?

**Comment by dcramer** [comment]
@dansajner yeah. We try to use timezone support correctly, but it's almost certainly not the case. I've updated the comment to more appropriately affect things.

**Comment by btidor** [comment]
That works great -- thank you!

**Comment by yijingping** [comment]
this dose work for me. thanks!

**Comment by JerryKaKa** [comment]
能不能提供可以自己设置时区的地方
