### ISSUE TITLE
VictorOps as a global integration

### ISSUE THREAD

**Issue by gboor** [getsentry/sentry#14728]
## Summary

VictorOps integration for Sentry currently comes in the form of a plugin, forcing you to configure the connection per project using settings that are very unlikely to change from project to project.

## Motivation

Right now, I have to configure each project in Sentry with exactly the same connection data. This is not super efficient and should not happen in light of global integrations.

I envision a global integration with victorops and perhaps per-project overrides (turn on/off, extra tags, w/e).

**Comment by BYK** [comment]
I think this is now an integration: https://docs.sentry.io/product/integrations/#notification--incidents

Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
