### ISSUE TITLE
Add backgound-color: #fff; to email layout

### ISSUE THREAD

**Issue by sc0rp10** [getsentry/sentry#1473]
Now emails looks bad on non-white web interfaces: http://i.imgur.com/Oo66Qr7.png
Same email with white background: http://i.imgur.com/5wMwEpI.png

**Comment by rakanalh** [comment]
Links don't work :)

**Comment by sc0rp10** [comment]
Oh, sorry, i updated issue.

**Comment by dcramer** [comment]
@ckj i assume this is a quick fix?

**Comment by mattrobenolt** [comment]
Emails are completely different now.
