### ISSUE TITLE
Linking issues to Azure DevOps running the 'Basic' process does not work

### ISSUE THREAD

**Issue by mkskytt** [getsentry/sentry#14749]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Linking any issue in Sentry to Azure DevOps using the [Basic process](https://docs.microsoft.com/da-dk/azure/devops/boards/get-started/plan-track-work?toc=%2Fazure%2Fdevops%2Fboards%2Ftoc.json&bc=%2Fazure%2Fdevops%2Fboards%2Fbreadcrumb%2Ftoc.json&view=azure-devops&tabs=basic-process) does not work.

It seems to fail because it is looking for a work item type of 'Bug', which the 'Basic' process does not include. Instead, the 'Basic' process uses 'Issues' for this.

## Steps to Reproduce

1. Configure Azure DevOps integration
2. Go to any issue in Sentry
3. Press the button 'Link Azure DevOps Issue' under 'Linked Issues'
4. Press the button 'Create Issue' under the tab 'Create'

Error message received:
`Error Communicating with Azure DevOps (HTTP 404): VS402323: Work item type Bug does not exist in project xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx or you do not have permission to access it.`

### What you expected to happen

I expected to successfully create an Azure DevOps 'Issue' from the Sentry issue.

### Possible Solution

A possible solution would be to check for the configured project process instead of using the type 'Bug' in all instances.

If I should guess the fix should be implemented in this [file](https://github.com/getsentry/sentry-vsts/blob/master/sentry_vsts/client.py#L108)

**Comment by markstory** [comment]
Are you using the organization level integration or the project level plugin for Azure DevOps?

**Comment by mkskytt** [comment]
I was unaware of a project level plugin.
Let me know where to configure that if you need me to test it.

I am using the organization level plugin.

**Comment by markstory** [comment]
@mkskytt Thanks, I asked as you mentioned that you were using sentry.io but also linked to a file in the deprecated plugin. When reading the Azure DevOps documentation I noticed that the 'Basic' process is a new trial process that isn't available to everyone yet. How does one enter into the beta/trial group for this new process?

**Comment by mkskytt** [comment]
As I understand the process is in public preview and should be available to anyone, but it is only the default process for new projects created in the Central US region based on what I read [here](https://docs.microsoft.com/en-us/azure/devops/release-notes/2019/sprint-146-update#simplify-the-organization-of-your-work-using-the-basic-process).

When you create a new project press 'Advanced' and select 'Basic' in the 'Work item process' dropdown.

**Comment by ErikEJ** [comment]
Please fix this, we need it in production!

**Comment by wwimmo-mf** [comment]
We also use the basic process template. I think the only relevant change in this case is renaming the type from "bug" to "issue". So it should not be complicated to support the basic process.
Please add this support.

**Comment by manuzope** [comment]
Hey there, this should be fixed. Would someone here mind confirming?

**Comment by mickyf** [comment]
It works for me. I can select all available types now.

**Comment by manuzope** [comment]
Awesome, thanks @mickyf. Closing out this issue.
