### ISSUE TITLE
Lots of entries in djkombu_message

### ISSUE THREAD

**Issue by blueyed** [getsentry/sentry#1474]
I've noticed that the `djkombu_message` table in Sentry's database is large (more than 620000 rows).

The entries are:

    select q.name, count(queue_id)
    from djkombu_message join djkombu_queue q on queue_id = q.id
    group by q.name;

    "name";"count"
    "alerts";48378
    "options";286139
    "update";806
    "default";33
    "counters-0";286139

I think Sentry is meant to maintain this data?

I've seen that there is a management command for kombu, but it would only
remove non-visible entries.

Only two entries for `options` and `counters-0` are non-visible.

I am using Sentry 7.4.1.

**Comment by dcramer** [comment]
If I had to guess, I'd say you're not running the worker processes

**Comment by blueyed** [comment]
I am running the worker processes.

I've noticed that the entries are older already:

"name";"visible";"min";"max";"count"
"alerts";t;"2015-01-30 11:19:09.783507+01";"2015-03-05 01:45:12.056084+01";48378
"counters-0";t;"2015-01-30 11:18:41.863572+01";"2015-03-05 01:45:57.371333+01";286137
"counters-0";f;"2015-01-30 11:18:21.427838+01";"2015-01-30 11:18:31.79442+01";2
"default";t;"2015-01-31 05:00:00.055156+01";"2015-03-04 05:00:00.01455+01";33
"options";f;"2015-01-30 11:18:21.088281+01";"2015-01-30 11:18:31.745147+01";2
"options";t;"2015-01-30 11:18:41.816011+01";"2015-03-05 01:45:57.321404+01";286137
"update";t;"2015-01-30 12:16:09.761071+01";"2015-03-05 01:16:15.107176+01";806

While I guess it's safe to remove them, I think Sentry should take care of this
itself.

I assume that they should also get pruned if no worker was available during
this period?!

**Comment by dcramer** [comment]
I'm not sure. We don't recommend running the database broker in production, and I don't know how the internals of it work.

**Comment by blueyed** [comment]
> We don't recommend running the database broker in production

What do you mean?  I've set it up according to the docs.

**Comment by dcramer** [comment]
The default configuration these days points to a Redis broker (the SQL tables aren't used in this case).

While the docs aren't up to date on the language, the recommendation has always been this:

http://sentry.readthedocs.org/en/latest/queue/index.html#enable-the-queue

**Comment by blueyed** [comment]
I see, and I've actually have:

    CELERY_ALWAYS_EAGER = False                                                   
    BROKER_URL = 'redis://localhost:6379'

Therefore the DB entries are really obsolete.

Sorry for the noise and thanks for your help!
