### ISSUE TITLE
API Questions

### ISSUE THREAD

**Issue by lazerscience** [getsentry/sentry#1475]
Trying to interact with Sentry's API I came up with some questions:

1. I was trying to retrieve the latest event groups using the newer "versioned api" through `/projects/<organization_slug>/<project_slug>/groups/` which generally works, but should there also be a possibility to include get the level names for the groups, as it is possible with the url for polling (without doing additonal requests)?

1. I think the `ApiKey` is still work in progress, do you plan to add a possibilty to obtain a key via the API? (eg. in a similar way django-rest-framework does with the [Token Authentication](http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication))

**Comment by dcramer** [comment]
Not sure how I missed this one, but:

> I was trying to retrieve the latest event groups using the newer "versioned api" through /projects/<organization_slug>/<project_slug>/groups/ which generally works, but should there also be a possibility to include get the level names for the groups, as it is possible with the url for polling (without doing additonal requests)?

Levels are just tags in the current system. They should be available as such.

> I think the ApiKey is still work in progress, do you plan to add a possibilty to obtain a key via the API? (eg. in a similar way django-rest-framework does with the Token Authentication)

In the future we'll likely offer an OAuth server, but we havent done any work / plans for it currently. The ApiKey stuff will be public soon, and works pretty much the same as Tokens (from a high level), but you cant generate them from the API yet.

**Comment by lazerscience** [comment]
> Levels are just tags in the current system. They should be available as such.

Yes already found out that they are tags, but guess there's no possibility to retrieve the tags in __one__ request with the __new__ API?

**Comment by dcramer** [comment]
Ah, I was confused about what I actually wrote in the code :)

We'll be adding this back. Originally we were aiming to remove the level concept, but have since backtracked.
