### ISSUE TITLE
Sentry github integration 404

### ISSUE THREAD

**Issue by MatteoGioioso** [getsentry/sentry#14773]
## Important Details

How are you running Sentry?

* [ X ] Saas (sentry.io)

## Description

I am trying to configure GitHub integration , but once I click to configure I receive 404 from GitHub.

![image](https://user-images.githubusercontent.com/43592430/65224499-7c5bb500-daed-11e9-8a66-71120081fca9.png)

This is the url: `https://github.com/apps/sentry-io/installations/198***`

Thanks

**Comment by MatteoGioioso** [comment]
Any update on this?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
