### ISSUE TITLE
Error with node when installing from source

### ISSUE THREAD

**Issue by odedfos** [getsentry/sentry#1478]
sentry$ python setup.py develop
running develop
running build_static
running [npm install --quiet]
npm WARN package.json uglify-js@2.2.4 'repositories' (plural) Not supported.
npm WARN package.json Please pick one as the 'repository' field
sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 127
npm ERR! not ok code 0
Traceback (most recent call last):
  File "setup.py", line 187, in <module>
    'Topic :: Software Development'
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
...

To solve this:
sudo apt-get install nodejs-legacy
http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu

**Comment by mattrobenolt** [comment]
Not sure how this is a problem with Sentry itself, but you def need a `node` binary on your $PATH.
