### ISSUE TITLE
Only first environment that was released to is shown in Releases tab

### ISSUE THREAD

**Issue by fgblomqvist** [getsentry/sentry#14794]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

In the Releases tab, only the first environment that release X was released to is shown for each release.

This is what it looks like in the Projects list (this is good UX):
![Screenshot from 2019-09-20 10-36-29](https://user-images.githubusercontent.com/649260/65335722-f2febe00-db92-11e9-808c-4106d48bc464.png)

This is what it looks like in the Releases tab (bad, both production and staging are running this release but it only says staging):
![Screenshot from 2019-09-20 10-37-03](https://user-images.githubusercontent.com/649260/65335728-f4c88180-db92-11e9-87e4-6988dd8fdfe6.png)

## Steps to Reproduce

1. Create a release named X for environment Y
2. Create a release named X for environment Z
3. Go to Releases tab, it will only say that it was released to Y

### What you expected to happen

It should either do what the Projects list does and show each environment separately, or it should combine them and show for each release which environment it is/was on.

I think the best UX here is probably to list them separately. E.g. one row in Releases per release and per environment. That way you can keep track of which release was to pushed to where and when.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

/cc @mitsuhiko
