### ISSUE TITLE
issue with incorrect generated URLs when installed in subdirectory

### ISSUE THREAD

**Issue by nneul** [getsentry/sentry#1479]
Using apache in front of sentry, installed as "/sentry". Everything looks fine and works, EXCEPT that the links to individual events on the main screen have /sentry/sentry instead of a single:

http://x.my.com/sentry/sentry/ABC/DEF/group/26/

all of the other relative links are generating without issue. 

Suggestions?

**Comment by dcramer** [comment]
This behavior is not currently supported. You need to use a subdomain with no path prefix.
