### ISSUE TITLE
Move application docs out of Sentry repo

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1480]
This is an ongoing dilemma for a number of reasons. There's various issues with the help pages being in the sentry repo, primarily because theres overlap between the getsentry.com service and sentry itself.

There are pros and cons of each, but let's first focus on the needs:
- Help pages which can plug in your DSN from app.getsentry.com
- A hub for all "how do i use sentry" docs. These things generally aren't version specific but some of the lingo is.
- A potential hub for client docs
- In general, our docs are awful. We need to seriously step up the game.
- Highly readable. Right now our www. docs are much better than our docs in app. just from a visual/legibility point of view.

Here's what I propose:
- Move docs into sentry-docs.
- Use Sphinx. Completely break it apart from the Sentry backend (thus static generating).
- Simple JS widget (using CORs) to enable a project DSN selector on www.
- Host docs at "docs.getsentry.com", clearly illustrate that they represent the current version of Sentry.
- API docs remain as part of the app, but it'll just be /api/ and only focus on the API.

The Pros:
- We can clearly label the docs as "these are for getsentry.com", with each case illustrating "on-premise" vs "hosted" configurations.
- More approachable for individual contributors, as the current docs basically require you to understand the complex project layout.
- Inter-sphinx might be an option if we can standard clients on using Sphinx (it may or may not make sense).
- Client summary docs are no longer out of date if you're using an old version of Sentry.

The Cons:
- This will always represent the "current" version of Sentry. This isn't a huge issue as this is how docs used to work.
- CORs stuff is a bit complicated, but not too much of a concern.

**Comment by dcramer** [comment]
Also if Sphinx can somehow do templates or similar that would be awesome for the Client stuff. We were going to do that with React to where it was super easy to specify "this is how to achieve this feature in this client", but never got too far into it.

**Comment by dcramer** [comment]
@ckj also I think as part of this we might want to consider if the chrome on the docs is still our best choice (since we'll no longer be bound to Sentry CSS). We could do something very simple like the current www. design (maybe we just tweak the header so it uses less space).

**Comment by BYK** [comment]
I think we can consider this as done with https://docs.sentry.io, https://develop.sentry.dev/, and https://develop.sentry.dev/self-hosted/
