### ISSUE TITLE
post-Google SSO auth redirects to organization homepage instead of inbound link

### ISSUE THREAD

**Issue by ckolderup** [getsentry/sentry#1481]
Hi,

We just enabled Google SSO on our organization on the hosted Sentry app at my workplace this week. One thing I've noticed is that when I follow inbound link to Sentry alerts, if it's been more than a little time, I get redirected to this page:

![](https://dl.dropboxusercontent.com/spa/iipw8wgu3n0h7pe/-_7efrdu.png)

Which is fine, but if I go through the Google auth, it then redirects me to https://app.getsentry.com/our-org-name instead of the original link I was trying to view. I have to close the tab, go back to wherever I was coming from in the first place, and click the link again (at which point it works fine).

It's mostly an inconvenience but it seems like it should be possible to retain the URL and forward me to my alert, or maybe just not time me out so quickly? I'm using Google Chrome on OS X Yosemite if it matters—this happens when clicking links from other tabs or from email apps or chat programs.

**Comment by thenonsequitur** [comment]
+1 Same issue here.

**Comment by banderson623** [comment]
:+1: me too

**Comment by dcramer** [comment]
Thanks guys! Should be fixed in prod in ~10m.

**Comment by ckolderup** [comment]
Thank you so much! :sparkling_heart:
