### ISSUE TITLE
Legit errors from Slack commands were filtered out

### ISSUE THREAD

**Issue by chengyin** [getsentry/sentry#14814]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [X] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

We accept Slack unfurling and interactive commands. Those requests from Slack server may lead to errors we do want to know and track. However, Sentry server broadly rejects those errors due to Slack's user agent (done in #5284). There is no option to only whitelist slack bots and we would like to avoid turning off the crawler filtering as a whole.

Note Slack now has [muiltiple bot agent](https://api.slack.com/robots) so one possibility is only to block the crawler ones.

### Possible Solution

- Remove slack filter
- Only filter slack crawler agents but allow slackbot
- Allow us to turn off only the slack rule

**Comment by BYK** [comment]
I guess we can allow `Slackbot 1.0(+https://api.slack.com/robots)` but keep the other two at bay?

/cc @mattrobenolt

**Comment by mattrobenolt** [comment]
Makes sense to me.

**Comment by BYK** [comment]
Turns out this was moved to getsentry/relay so added @getsentry/owners-ingest 

Will try to get it fixed before Monday.
