### ISSUE TITLE
Separation between private and public web endpoints

### ISSUE THREAD

**Issue by Overbryd** [getsentry/sentry#14813]
## Summary

Allow administrators to configure a hostname for public endpoints, that expose much less of the API than the usual public installation of Sentry.

## Motivation

I am running Sentry in closed networks, with great success, and people are really happy to monitor their errors with such a high quality application like Sentry.

Those networks clearly separate between public and private APIs, and thus it is possible for me to run a private application, only exposing certain endpoints to the public.

That does successfully shield away the overall access from the public. However, certain integrations require public endpoints. Like JavaScript and Browser error tracking.
Or the webhooks that integrate with services like Github or Gitlab.

For those, I can imagine routing those requests specifically under a different public hostname.

## Additional Context

So far I found little information on making the best of Sentry in closed environments.
I would be more than happy to do my part in helping you write, or document the changes that I proposed above.

It could be quite simple, as in having a designated subpath `/api/public` or an additional configurable domain name (e.g. `sentry.internal` vs `sentry-public.somecompany.com`).

At the very least, this issue could trigger some API documentation effors, that would bundle the descriptions of all endpoints that require public access (webhooks, integrations) so that an external reverse proxy could map those to Sentry, and still benefit from having less of Sentry exposed, than running a public installation.

**Comment by BYK** [comment]
I think our new project Relay can help here now: https://docs.sentry.io/product/relay/#enterprise-domain-management

Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
