### ISSUE TITLE
Bitbucket Integration: This app is misconfigured error.

### ISSUE THREAD

**Issue by spearox** [getsentry/sentry#14823]
I'll get this error on bitbucket integration install.
I cannot find any info on docs: https://docs.sentry.io/workflow/integrations/global-integrations/#bitbucket

This app is misconfigured. Contact the vendor for assistance.

descriptor_uri: The add-on server wasn't able to authorize your request. Try again, or contact the add-on vendor for help.

redirect_uri: Could not resolve descriptor so cannot check redirect_uri against baseUrl

**Comment by melorbany** [comment]
+1

**Comment by manuzope** [comment]
@spearox @melorbany are ya'll on-prem or the SaaS offering?

**Comment by ba7op** [comment]
on-prem here

**Comment by spearox** [comment]
> @spearox @melorbany are ya'll using on-prem or the SaaS offering?

on-prem

**Comment by manuzope** [comment]
Got it. Which version of on prem are you running? And would you be able to provide a screenshot of the error? It'll help me to figure out where the error is happening.

**Comment by spearox** [comment]
> Got it. Which version of on prem are you running? And would you be able to provide a screenshot of the error? It'll help me to figure out where the error is happening.

Sentry 9.1.2

Here fail on Step 4.
https://docs.sentry.io/workflow/integrations/global-integrations/#bitbucket

img1: https://pasteboard.co/ILWpwyP.png
img2: https://pasteboard.co/ILWpMeE.png
img3 (the error): https://pasteboard.co/ILWpUCp.png
This is the URL on img3: `https://bitbucket.org/site/addons/authorize?descriptor_uri=http://sentry.XY.hu:9400/extensions/bitbucket/descriptor/`

**Comment by BYK** [comment]
@spearox we just released Sentry 10, are you able to test with that?

**Comment by ba7op** [comment]
I'll try it next week.

**Comment by andreyelpaev** [comment]
+1 on-premise problem

**Comment by BYK** [comment]
@andreyelpaev - which version of on-premise? If not 10, can you try upgrading to 10?

**Comment by andreyelpaev** [comment]
> @andreyelpaev - which version of on-premise? If not 10, can you try upgrading to 10?

installed version 9.1.2, can I migrate from 9.1.2 to 10 without delete my events?

**Comment by BYK** [comment]
>@BYK installed version 9.1.2, can I migrate from 9.1.2 to 10 without delete my events?

Yes. The default retention period is 90 days tho, keep that in mind (this can be adjusted if you need more).

**Comment by andreyelpaev** [comment]
> > @BYK installed version 9.1.2, can I migrate from 9.1.2 to 10 without delete my events?
> 
> Yes. The default retention period is 90 days tho, keep that in mind (this can be adjusted if you need more).
> 
> I'd also still back up my data, just in case something goes wrong.

Thx, I will try it today. And I will give feedback.

**Comment by andreyelpaev** [comment]
@BYK I installed Sentry 10.1.0.dev0 (46ff944fefc133ebb8c20c85d46abb8bc9751d09), this version have same problem. 

```
This app is misconfigured. Contact the vendor for assistance.

descriptor_uri: The add-on server could not be reached. Try again or contact support for help.
redirect_uri: Could not resolve descriptor so cannot check redirect_uri against baseUrl
```

**Comment by lsaint** [comment]
+1  @  Sentry 10.1.0.dev0f38ae0a

This app is misconfigured. Contact the vendor for assistance.

descriptor_uri: The add-on server wasn't able to authorize your request. Try again, or contact the add-on vendor for help.

redirect_uri: Could not resolve descriptor so cannot check redirect_uri against baseUrl

**Comment by scefali** [comment]
So, unfortunately, we don't have any docs of how to set up Bitbucket cloud for on-prem users. We are working on adding those missing docs, however.

**Comment by manuzope** [comment]
Hey there, we have docs on how to set up Bitbucket from an on-prem instance. Does this solve your problem? https://develop.sentry.dev/integrations/bitbucket/
