### ISSUE TITLE
Sentry requires you have CITEXT (not documented)

### ISSUE THREAD

**Issue by arianf** [getsentry/sentry#14821]
## Important Details

How are you running Sentry?

* [x] On-Premise python install
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Our Postgres doesn't have the CITEXT extension and we aren't allowed to install extensions on them. I want to setup a Sentry on-premise and I don't see that in the requirements list for using Sentry. Is this required? I'm getting errors when I try to run the migrations.

Why not have sentry just have `lower()` before inserting, rather than using a custom extension?

```sql
SELECT * FROM users WHERE lower(username) = lower('jOhN');
```

```sql
CREATE UNIQUE INDEX unique_username_on_users ON users (lower(username));
```

**Comment by mattrobenolt** [comment]
It's not a custom extension, it ships with Postgres as a standard extension. You're right that we could `lower()` everywhere, but that is error prone. And also requires every index to be functional over `lower()` etc. Or everything kinda falls apart. `citext` is a much better solution and is bundled with Postgres.
