### ISSUE TITLE
ImproperlyConfigured: You must configure ``SENTRY_CACHE``.

### ISSUE THREAD

**Issue by dAnjou** [getsentry/sentry#1482]
Running `sentry upgrade` presented me with above error.

Setting `SENTRY_CACHE = 'sentry.cache.redis.RedisCache'` fixed it. (Thanks, @dcramer.)

But it should be mentioned in the docs.

**Comment by mitsuhiko** [comment]
Upgrade docs are indeed a bit terrible currently.  Note that if you upgrade you better regenerate your config and copy stuff over, you will discover other things breaking too (like counting).

**Comment by dAnjou** [comment]
Thanks. I think I'll stick to v7.4.3 for now then :stuck_out_tongue:

**Comment by dcramer** [comment]
Closing this out, but we'll be actively improving docs in the future.

**Comment by jhnferraris** [comment]
I have the same problem.  How exactly did you set `SENTRY_CACHE`?

**Comment by jhnferraris** [comment]
Nevermind. It's going to be set in the `sentry.conf.py`.
