### ISSUE TITLE
Column sentry_eventattachment.group_id does not exist

### ISSUE THREAD

**Issue by lz1irq** [getsentry/sentry#14835]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.2]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

An exception is raised while using the app:

```
ProgrammingError: ProgrammingError('column sentry_eventattachment.group_id does not exist\nLINE 1: ...ent"."id", "sentry_eventattachment"."project_id", "sentry_ev...\n                                                             ^\n',) SQL: SELECT "sentry_eventattachment"."id", "sentry_eventattachment"."project_id", "sentry_eventattachment"."group_id", "sentry_eventattachment"."event_id", "sentry_eventattachment"."file_id", "sentry_eventattachment"."name", "sentry_eventattachment"."date_added", "sentry_file"."id", "sentry_...
```

## Steps to Reproduce
 
Occurs while browsing issues in the web interface, cannot find exact steps.

Also occurred with the Sentry worker while executing a task:
```
{args: [], kwargs: {action: created, instance_id: 35, sender: Group}, task_name: sentry.tasks.process_resource_change_bound}
```

### Additional information

In the `south_migrationhistory` table in the database, I noticed the following migration:
```
id  | app_name |                                  migration                                  |            applied            
-----+----------+-----------------------------------------------------------------------------+-------------------------------
532 | sentry   | 0495_auto__del_field_eventattachment_group_id                               | 2019-09-25 13:29:30.224537+00
```
However, I don't see this migration in the `src/sentry/south_migrations` folder  when I've checked out tag `9.1.2` from git.

**Comment by mattrobenolt** [comment]
You’re right, that migration doesn’t exist for 9.1.2. I’m not sure how you’d have applied that. Did you at one point run master branch?

**Comment by lz1irq** [comment]
I did run the master branch, but in a separate docker-compose environment, with a different DB volume and so on, not sure how that would be possible. Is there any way to reverse this migration, or do I add in the field manually?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
