### ISSUE TITLE
Sentry sending mails to https://brvmmdwp.localtunnel.me

### ISSUE THREAD

**Issue by RaviTezu** [getsentry/sentry#1484]
Hi, I use a Mailgun API for sending mails from sentry. I see some mails from sentry are being sent to https://brvmmdwp.localtunnel.me and these are being dropped by mailgun. Mailgun was trying to send mails to that localtunnel domain.

Here's the error I see on Mailgun logs:
localtunnel error: no active client for 'brvmmdwp'

Can someone help me how to avoid sending these mails? 

Note: Sentry is able to send the event mails.

**Comment by mitsuhiko** [comment]
Sentry is not using localtunnel.  This seems to be a misconfiguration on your side.

(Closing, this is a bugtracker and not a support forum :))

**Comment by RaviTezu** [comment]
Thanks. Sorry for raising the issue here!
