### ISSUE TITLE
Slack Integration: invalid client_id

### ISSUE THREAD

**Issue by jussirantala** [getsentry/sentry#14850]
I'm trying to install Slack integration, but I get error "missing or invalid client_id".

I've done all steps of this tutorial and also allowed some extra scopes for the app, because it seems to need more than what's said in the tutorial. https://forum.sentry.io/t/how-to-configure-slack-in-your-on-prem-sentry/3463/7

The client_id is correct in URL parameters of the "Authorization Error" window, how is it possible that it's invalid? I use sentry 9.1.2 (on-premise).

**Comment by sumit4613** [comment]
I'm facing the same issue. 
Done everything as said in tutorial but didn't got any success.

**Comment by jussirantala** [comment]
> I'm facing the same issue.
> Done everything as said in tutorial but didn't got any success.

Do you also see the right client_id if you check URL parameters of the URL in the "Authorization Error" window?

**Comment by sumit4613** [comment]
> > I'm facing the same issue.
> > Done everything as said in tutorial but didn't got any success.
> 
> Do you also see the right client_id if you check URL parameters of the URL in the "Authorization Error" window?

No, the client_id always remain empty in the URL parameters.
I don't know why.

**Comment by jussirantala** [comment]
> > > I'm facing the same issue.
> > > Done everything as said in tutorial but didn't got any success.
> > 
> > 
> > Do you also see the right client_id if you check URL parameters of the URL in the "Authorization Error" window?
> 
> No, the client_id always remain empty in the URL parameters.
> I don't know why.

Then your problem is that you didn't get it configured right. Not related to this issue.

**Comment by sumit4613** [comment]
> Then your problem is that you didn't get it configured right. Not related to this issue. Have you checked this yet? [#9004 (comment)](https://github.com/getsentry/sentry/issues/9004#issuecomment-405396652)

my slack config are like this:
slack.client-id: '12.12'
slack.client-secret: xxx
slack.verification-token: xxx

Am i putting these correctly?

**Comment by jussirantala** [comment]
> > Then your problem is that you didn't get it configured right. Not related to this issue. Have you checked this yet? [#9004 (comment)](https://github.com/getsentry/sentry/issues/9004#issuecomment-405396652)
> 
> my slack config are like this:
> slack.client-id: '12.12'
> slack.client-secret: xxx
> slack.verification-token: xxx
> 
> Am i putting these correctly?

Please go to https://github.com/getsentry/sentry/issues/9004 for help as your issue is not related to this issue. Your config looks fine, but for some reason it's not loaded in.

**Comment by BYK** [comment]
Our docs should help you now: https://develop.sentry.dev/integrations/slack/
