### ISSUE TITLE
Filter events by tags, but get all count about one issue.

### ISSUE THREAD

**Issue by PerceiverDo** [getsentry/sentry#14861]
As we seen, one issue may contains some events.But when i filter with some tags, why the issue count is not correct for these filter tags.

![image](https://user-images.githubusercontent.com/6870548/65828216-03b5df00-e2cb-11e9-8b93-ae3228023043.png)

**Comment by harshita** [comment]
> As we seen, one issue may contains some events.But when i filter with some tags, why the issue count is not correct for these filter tags.
> 
> ![image](https://user-images.githubusercontent.com/6870548/65828216-03b5df00-e2cb-11e9-8b93-ae3228023043.png)

I am experiencing a similar problem with filtering by tags and not being able to see the actual count for search criteria of interest.

**Comment by BYK** [comment]
We have very recently released dynamic counts for these: https://github.com/getsentry/sentry/issues/15189#issuecomment-714260243

Closing the ticket as this looks like a duplicate.
