### ISSUE TITLE
Make additional data links clicable

### ISSUE THREAD

**Issue by arthurlogilab** [getsentry/sentry#1486]
![screenshot from 2015-04-10 11 17 58](https://cloud.githubusercontent.com/assets/445200/7085095/5d3a62c2-df73-11e4-9cf9-0039cf42007f.png)

It would be nice for URLs to be clicable in the "Additional data" section.

**Comment by msjaiswal** [comment]
Yes. Also the the link in the message should be clickable. 
<img width="931" alt="screen shot 2016-03-28 at 9 57 41 pm" src="https://cloud.githubusercontent.com/assets/1758886/14082880/20ff9a10-f530-11e5-9b67-2cfded438f23.png">

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
