### ISSUE TITLE
Statsd API incompatibilities

### ISSUE THREAD

**Issue by mvaled** [getsentry/sentry#1488]
I'm just installed Sentry 7.4.3.  When trying to run the workers I get the following error repeatedly until I kill celery:

    $ sentry --config=/home/manu/tmp/sentry/etc/settings.py celery worker -B

     -------------- celery@pavla v3.0.24 (Chiastic Slide)
    ---- **** ----- 
    --- * ***  * -- Linux-3.13.0-48-generic-x86_64-with-Ubuntu-14.04-trusty
    -- * - **** --- 
    - ** ---------- [config]
    - ** ---------- .> broker:      redis://localhost:6379/1
    - ** ---------- .> app:         default:0x7f2f0774d710 (djcelery.loaders.DjangoLoader)
    - ** ---------- .> concurrency: 4 (processes)
    - *** --- * --- .> events:      OFF (enable -E to monitor this worker)
    -- ******* ---- 
    --- ***** ----- [queues]
     -------------- .> alerts:      exchange:default(direct) binding:alerts
		    .> auth:        exchange:default(direct) binding:auth
		    .> cleanup:     exchange:default(direct) binding:cleanup
		    .> counters-0:  exchange:counters(direct) binding:
		    .> default:     exchange:default(direct) binding:default
		    .> email:       exchange:default(direct) binding:email
		    .> events:      exchange:default(direct) binding:events
		    .> options:     exchange:default(direct) binding:options
		    .> search:      exchange:default(direct) binding:search
		    .> sourcemaps:  exchange:default(direct) binding:sourcemaps
		    .> triggers-0:  exchange:triggers(direct) binding:
		    .> update:      exchange:default(direct) binding:update

    [2015-04-12 01:40:03,789: WARNING/MainProcess] celery@pavla ready.
    [2015-04-12 01:40:03,826: ERROR/PoolWorker-2] Data not available in preprocess_event (cache_key=e:14562ccb88d04ef8a0e237a075625a67:1)
    [2015-04-12 01:40:03,826: ERROR/PoolWorker-3] Data not available in preprocess_event (cache_key=e:976600be4fcb4d509f04eeb8d5f5adb1:1)
    [2015-04-12 01:40:03,828: ERROR/PoolWorker-5] Data not available in preprocess_event (cache_key=e:6206a4b45c5e40acb95c867f2812db09:1)
    [2015-04-12 01:40:04,343: ERROR/MainProcess] Task sentry.tasks.store.preprocess_event[421fc5e6-1fb8-4ea2-99f2-8481cbb8a7d9] raised exception: TypeError('_send() takes exactly 4 arguments (2 given)',)
    Traceback (most recent call last):
      File "/home/manu/tmp/sentry/local/lib/python2.7/site-packages/celery/task/trace.py", line 233, in trace_task
	R = retval = fun(*args, **kwargs)
      File "/home/manu/tmp/sentry/local/lib/python2.7/site-packages/celery/task/trace.py", line 420, in __protected_call__
	return self.run(*args, **kwargs)
      File "/home/manu/tmp/sentry/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 24, in _wrapped
	result = func(*args, **kwargs)
      File "/home/manu/tmp/sentry/local/lib/python2.7/site-packages/statsd/client.py", line 41, in __exit__
	self.stop()
      File "/home/manu/tmp/sentry/local/lib/python2.7/site-packages/statsd/client.py", line 55, in stop
	self.send()
      File "/home/manu/tmp/sentry/local/lib/python2.7/site-packages/statsd/client.py", line 64, in send
	self.client.timing(self.stat, self.ms, self.rate)
      File "/home/manu/tmp/sentry/local/lib/python2.7/site-packages/statsd/client.py", line 85, in timing
	self._send_stat(stat, '%d|ms' % delta, rate)
      File "/home/manu/tmp/sentry/local/lib/python2.7/site-packages/statsd/client.py", line 113, in _send_stat
	self._after(self._prepare(stat, value, rate))
      File "/home/manu/tmp/sentry/local/lib/python2.7/site-packages/statsd/client.py", line 128, in _after
	self._send(data)
    TypeError: _send() takes exactly 4 arguments (2 given)

The current virtualenv is as follows:

    amqp==1.0.13
    anyjson==0.3.3
    BeautifulSoup==3.2.1
    billiard==2.7.3.34
    celery==3.0.24
    cffi==0.8.6
    cryptography==0.5.4
    cssselect==0.9.1
    cssutils==0.9.9
    Django==1.6.8
    django-bitfield==1.7.1
    django-celery==3.0.23
    django-crispy-forms==1.4.0
    django-jsonfield==0.9.13
    django-paging==0.2.5
    django-picklefield==0.3.1
    django-recaptcha==1.0.3
    django-social-auth==0.7.28
    django-statsd-mozilla==0.3.8
    django-sudo==1.1.3
    django-templatetag-sugar==1.0
    djangorestframework==2.3.14
    email-reply-parser==0.2.0
    enum34==0.9.18
    exam==0.10.5
    gunicorn==19.3.0
    httplib2==0.9
    ipaddr==2.1.11
    kombu==2.5.16
    logan==0.5.8.2
    lxml==3.4.1
    Markdown==2.4.1
    mock==1.0.1
    ndg-httpsclient==0.3.3
    nydus==0.10.8
    oauth2==1.5.211
    progressbar==2.3
    psycopg2==2.5.4
    py==1.4.26
    pyasn1==0.1.7
    pycparser==2.10
    Pygments==1.6
    pyOpenSSL==0.14
    pytest==2.6.4
    pytest-django==2.7.0
    python-dateutil==1.5
    python-memcached==1.54
    python-openid==2.2.5
    pytz==2014.10
    raven==5.2.0
    redis==2.10.3
    requests==2.5.1
    sentry==7.4.3
    setproctitle==1.1.8
    simplejson==3.3.3
    six==1.8.0
    South==1.0.1
    statsd==3.1
    toronado==0.0.6
    ua-parser==0.3.6
    urllib3==1.7.1

The settings files is as follows:

    from sentry.conf.server import *

    import os.path

    CONF_ROOT = os.path.dirname(__file__)

    DATABASES = {
	'default': {
	    'ENGINE': 'django.db.backends.postgresql_psycopg2',

	    'NAME': 'sentrydb',
	    'USER': '',
	    'PASSWORD': '',
	    'HOST': '',
	    'PORT': '',
	}
    }

    SENTRY_USE_BIG_INTS = True
    SENTRY_ADMIN_EMAIL = 'manu@localhost'

    SENTRY_REDIS_OPTIONS = {
	'hosts': {
	    0: {
		'host': '127.0.0.1',
		'port': 6379,
	    }
	}
    }

    SENTRY_CACHE = 'sentry.cache.redis.RedisCache'

    CELERY_ALWAYS_EAGER = False
    BROKER_URL = 'redis://localhost:6379/1'
    SENTRY_RATELIMITER = 'sentry.ratelimits.redis.RedisRateLimiter'

    SENTRY_BUFFER = 'sentry.buffer.redis.RedisBuffer'

    SENTRY_QUOTAS = 'sentry.quotas.redis.RedisQuota'

    SENTRY_TSDB = 'sentry.tsdb.redis.RedisTSDB'

    SENTRY_FILESTORE = 'django.core.files.storage.FileSystemStorage'
    SENTRY_FILESTORE_OPTIONS = {
	'location': '/tmp/sentry-files',
    }

    SENTRY_URL_PREFIX = 'http://localhost:9000'  # No trailing slash!

    SENTRY_WEB_HOST = '0.0.0.0'
    SENTRY_WEB_PORT = 9000
    SENTRY_WEB_OPTIONS = {
	'workers': 3,  # the number of gunicorn workers
	'secure_scheme_headers': {'X-FORWARDED-PROTO': 'https'},
    }

    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

    EMAIL_HOST = 'localhost'
    EMAIL_HOST_PASSWORD = ''
    EMAIL_HOST_USER = ''
    EMAIL_PORT = 25
    EMAIL_USE_TLS = False

    # The email address to send on behalf of
    SERVER_EMAIL = 'root@localhost'

**Comment by mvaled** [comment]
Upgrading to celery 3.0.25 does not solve this issue.  

From the traceback, this is actually a bug in statsd, but I wonder why nobody seems to have reported this.  Is the statsd version requirement ok?

**Comment by dcramer** [comment]
pip install statsd==1.0.0

I'll see what we need to do to fix this in the package

**Comment by dcramer** [comment]
It actually looks like a newer version of django-statsd-mozilla might resolve this to. We'll try upgrading things (as well as locking in statsd).

https://github.com/andymckay/django-statsd/issues/78

**Comment by dcramer** [comment]
471494cdb64f714c758d13dcdb8ed8426faffc8f will go into next release assuming no issues in getsentry.com prod

**Comment by mvaled** [comment]
I will test this in master and report if I find anything problem

**Comment by mvaled** [comment]
Ok passing in master.
