### ISSUE TITLE
Debounce / bundle emails to prevent stampede

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1489]
Our goal is to create a system which will allow us to bundle (for emails) or suppress (i.e. slack) notifications when they get too bursty, but at the same time ensure minimum delay in receiving initial emails.

This is a fairly rough outline, but here's one concept:

Send max of one email per X minutes:

- exponentially increase X up to a maximum of one email per 15m?
- create digests with multiple pending emails
- user-based (and possibility project based in addition)

The pipeline might look something like this:

- event comes in
- rule says notification should happen
- message goes into pending queue. note first add date ('redis add') and last add date ('redis set')
- task is created with debounce ETA
- when task fires, check pending queue and rates
- debounce message with up to MAX delay between emails (minutes)

**Comment by dcramer** [comment]
Gibberish of notes I wrote down earlier. Aiming for a more solid plan before implementation as theres a bunch of branches that need handled here.

```
Every notification created incr counter (per service)

Store count per minute up to max rate limits

When notification exceeds threshold add to pending queue with estimated time to send

Cron job runs every few seconds to remove pending notifications and fire jobs

Need to set a flag saying user is buffered to handle race between queued notifications and not

Maintain buffer until rate drops

Denounce all notifications for short period and if it hits rate limit notify the user that x have happened and things are now limited 


rule_notify() =>
    # store notification attributes
    key = 'n:g:<group.id>'
    hincrby(key, 'count')
    hsetnx(key, 'first:time', '<time>')
    hset(key, 'last:time', '<time>')
    hset(key, 'first:event', '<event.id>')

    # incr counter for notifications during this minute
    incr('n:u:{user.id}:{minute}', 1)
    expire('n:u:{user.id}:{minute}', '<max_debounce_window>')

    # check rate limits for periods incr'd
    if sum() > x:

    # ensure notification is added to pending queue
    zadd('pending:notifications', key, '<time>')


process_pending_notifications():
    # see buffer.process_pending, but effectively fanout anything that's within
    # the debounce period, and keep track of overall
    for key in zrange('pending:notifications', ...):


- send max of 3 emails in 60 seconds
  - flush pending queue every 60 seconds
- send max of 10 emails in 15 minutes
  - flush pending queue every 5 minutes
- increase rate counter everytime notification *is sent*
  (increase it and then decrease it if we dont send)
```

**Comment by tkaemming** [comment]
This is all basically done, more specific details can be found [in the Digests milestone.](https://github.com/getsentry/sentry/milestones/Digests)

It's also worth noting for posterity that the implementation is not user-centric as noted in the description, but project-centric.

**Comment by troy** [comment]
This turned out fantastic, everyone. As a customer, I love the digest emails.

**Comment by dcramer** [comment]
:ship:
