### ISSUE TITLE
Allow relative URLs for release files

### ISSUE THREAD

**Issue by realityking** [getsentry/sentry#1490]
I've started looking into the new release API, to eventually be able to use sourcemaps. One major for issue for us is, that Sentry exepects the full URI. We make the same application avaiable trough multiple domains (using a slightly different design with some Nginx magic). 

It would be great if we could just specify `/scripts/vendor.js`.

**Comment by dcramer** [comment]
Eliminating the domain would help one case, but there's another case we still have to support as well:

foo.com/{DYNAMIC}/foo/bar.js

I think we should aim for a solution which covers both of these, and the only reasonable thing I've come up with is an "ends with" pattern using a depth-first search.

**Comment by dcramer** [comment]
I think for now we're not going to do this as its fairly complex.

The easier solution is to have client's rewrite the stacktrace to something uniform. We're going to add some helpers in raven.js for this: https://github.com/getsentry/raven-js/issues/352
