### ISSUE TITLE
Grouping Settings

### ISSUE THREAD

**Issue by prankov** [getsentry/sentry#14922]
Hey, guys I need to setup rules for grouping issues
In manual I see this
![sentryman](https://user-images.githubusercontent.com/8806604/66105541-6ad1dd00-e5c4-11e9-8d12-adb91479cd7e.png)
And in settings i can't find this
![sentrysettings](https://user-images.githubusercontent.com/8806604/66105570-78876280-e5c4-11e9-9f59-48c0abd2b50f.png)

**Comment by markstory** [comment]
That feature hasn't been part of an on-premise release yet.

**Comment by prankov** [comment]
And how I can group issues by message and type?

**Comment by markstory** [comment]
You'd have to wait for group configurations to ship in on-premise.

**Comment by c4tz** [comment]
Are there any plans to integrate this yet? Or do we have to create a separate issue in https://github.com/getsentry/onpremise?

**Comment by reynico** [comment]
Hi, any news on this?

**Comment by BYK** [comment]
You all can try the v10 BETA if you are interested in this: https://forum.sentry.io/t/sentry-v10-beta-now-available/8097/6
