### ISSUE TITLE
Bad Request (400) if domain name contains underscore (_)

### ISSUE THREAD

**Issue by phiresky** [getsentry/sentry#14958]
How are you running Sentry?

* [x] On-Premise docker [Version 4fade2fb1f08eae008c435e4c0c5ef03acc9d9a7]

## Description

Accessing the server (behind nginx reverse proxy) just throws a 400 Bad Request error, and even with debug logging active there is no error message.

The domain name was like pp1_sentry.domain.com. Accessing it directly via the IP works.

It was really hard to find that the __domain name__ was the reason. Changing the domain to pp1sentry.domain.com makes it work.

**Comment by zetaab** [comment]
Maybe better to start reading this answer https://stackoverflow.com/a/2183140 it is not quite valid to use underscores in domain name.

**Comment by phiresky** [comment]
Well, sentry is the only component that wasn't able to handle it. DNS, cloudflare, nginx, Chrome all worked fine. The main problem is that the error message is absolutely unhelpful in finding out what is happening. In any case, just having this issue here should reduce the amount of time someone else might waste if they encounter the same problem by a lot. So feel free to close this if you think it's won'tfix.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
