### ISSUE TITLE
Display breadcrumb millisecond when possible

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#14959]
## Summary

Provide the ability to visualize breadcrumbs milliseconds when available. 

## Motivation

Often SDKs provide breadcrumb with millisecond precision. Would be useful in this cases to see it. Even if on a tool tip when hovering it. 

## Additional Context

https://github.com/getsentry/sentry-java/issues/776

**Comment by mrmitew** [comment]
Thank you for picking this up, @bruno-garcia ! Do you have a roadmap or an idea when this could be live?

**Comment by bruno-garcia** [comment]
@mrmitew Not sure. This will be picked up by _product_ and prioritized. Could take a bit since there's a lot in the backlog generally.

The tags indicate this could be a easy first contribution tough, if you'd like to give it a try :)

**Comment by pastDexter** [comment]
I can pick it up later today :)
