### ISSUE TITLE
Upgrading sentry-comments 0.2.0 to 0.3.0 fails

### ISSUE THREAD

**Issue by mgedmin** [getsentry/sentry#1496]
I've got a few old Sentries running 6.3.2 with sentry-comments 0.2.0.  I'm looking to upgrade them to latest Sentry.  It seems that I must first upgrade to Sentry 6.4, run the [migratecomments script](https://gist.github.com/andialbrecht/8644979), then remove sentry_comments and upgrade to latest.

I get stuck on the 1st upgrade: `sentry start` fails with
```
Running migrations for sentry_comments:
 - Migrating forwards to 0001_initial.
 > sentry_comments:0001_initial
FATAL ERROR - The following SQL query failed: CREATE TABLE "sentry_comments_groupcomments" ("id" serial NOT NULL PRIMARY KEY, "group_id" integer NOT NULL, "author_id" integer NOT NULL, "message" text NOT NULL, "created" timestamp with time zone NOT NULL)
The error was: relation "sentry_comments_groupcomments" already exists

Error in migration: sentry_comments:0001_initial
DatabaseError: relation "sentry_comments_groupcomments" already exists
```

Would you mind documenting what the user is supposed to do when upgrading from sentry-comments 0.2.0?

**Comment by dcramer** [comment]
sentry-comments was a third-party plugin and isn't supported by us

That said, the above error is probably mitigated with sentry migrate sentry_comments 0001 --fake

**Comment by mgedmin** [comment]
I'm sorry, I hit the 'New issue' button in the wrong GitHub browser tab again!

:brownpaperbag:
