### ISSUE TITLE
Session cookie being set on static resources

### ISSUE THREAD

**Issue by shivramk** [getsentry/sentry#1498]
If I update my preferences in the appearance settings, sentry starts adding a session cookie to each request. This cookie is set even for static resources (JavaScript, CSS etc) and breaks browser caching. I tracked this down to ```src/sentry/middleware/locale.py``` which seems to be setting the session cookie if a language is set.

Is this behavior intentional? Can we limit this to only non static urls?

**Comment by mattrobenolt** [comment]
Any production server shouldn't be serving static assets through Django. If you use nginx or Apache, this won't be an issue. So closing as invalid for any production use which is where caching would matter anyways.
