### ISSUE TITLE
Group same exceptions different page

### ISSUE THREAD

**Issue by SLv99** [getsentry/sentry#1499]
I installed Sentry on my own VPS. I use it in combination with a Wordpress Error catcher. The problem is that the same exception thrown from a different page is not grouped correctly. With a live website this results in that I get spammed, because every page throws the same error. Is there a possibility to force group exceptions or something?

Thanks!

**Comment by dcramer** [comment]
Sentry primarily groups on the stacktrace. If the stacktrace is effectively the same and this is happening please provide an example and we'll see if we can improve the branches.

Otherwise closing this as it works as expected.
