### ISSUE TITLE
Request access to existing organizations

### ISSUE THREAD

**Issue by jankoprowski** [getsentry/sentry#1500]
Hi,

  Right now user not belonging to any group is asked to create new organization.
  There should be option to redirect it to site with information/instruction/contact page informing how to request membership. It might be page with existing organizations allowing to request membership.

**Comment by dcramer** [comment]
This seems reasonable, but can you explain the use case? Also is this on getsentry.com or on-premise?

**Comment by jankoprowski** [comment]
I'm talking about our internal company instance.

We are using Ansible to setup infrastructure. Sentry role runs bootstrap script creating basic organization. Except admin account Sentry is empty. It is ok for new users to create new organizations except situation when organization they are interested in already exists. They should be able to check it somehow and create new organization or request access to existing one.

**Comment by dcramer** [comment]
Alright. I ask because the organizations feature is primarily aimed at getsentry.com. Generally internally people should be using teams (for a number of reasons) and we're actually already working on a feature to allow users to join/leave teams openly as well as request to join.

**Comment by jankoprowski** [comment]
It might be a good idea to connect that with LDAP group<->team/organization/project mapping.
User 'meeting' some query e.g. (&(sAMAccountName=%s)(memberOf=abc)) = 'some-team' etc...
Some mapping possibility will really useful!

**Comment by dcramer** [comment]
@jankoprowski we'll be offering very tight integration with standard SSO providers in the near future as part of our Enterprise offering. That said, we're still going to push to single organization for on-premise installs.
