### ISSUE TITLE
celery settings do not take effect

### ISSUE THREAD

**Issue by lwcolton** [getsentry/sentry#1502]
Setting BROKER_URL in my settings.conf.py did not actually take effect in celery.  It looks like there is a bug with django 1.6 and celery 3.0 where celery isn't reading the settings from the django settings object.  Recommend upgrading to celery 3.1 ASAP.

**Comment by dcramer** [comment]
It's highly unlikely that there is a bug and it's probably that you're not passing in the confit. This works for everyone else and they all run the same versions. We've also already moved to celery 3.1 in master.
