### ISSUE TITLE
Sourcemap support for self hosted versions

### ISSUE THREAD

**Issue by TheSavior** [getsentry/sentry#1503]
I haven't been able to find any discussion about how Sentry handles sourcemap support when it is being self hosted. The documentation here https://www.getsentry.com/docs/sourcemaps/ state that sourcemaps and unminified files need to be publicly accessible. 

Is there any way to upload sourcemaps? Or perhaps the only way is to guarantee a specific outbound ip address for the service and specifically whitelist that IP to have access to the sourcemap and unminified files.

Thoughts?

**Comment by dcramer** [comment]
https://gist.github.com/dcramer/619d53dabfbc2ed008a1

We'll be pushing out more public guides/etc soon, similar to the above. :)

**Comment by TheSavior** [comment]
Wow, awesome.
