### ISSUE TITLE
Can't access "Events" tab

### ISSUE THREAD

**Issue by AkdM** [getsentry/sentry#15109]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.2]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I've set up Sentry Onpremise locally to try, added the the event feature in `sentry.conf.py` file, then rebuilded. Accessing the **Events** tab results into a `Oops! Something went wrong` error (see screenshot).

## Steps to Reproduce

1. Clone the on premise Sentry version;
2. Add features into `sentry.conf.py` (I wasn't really sure where to add them so I put the features under the "# Docker" comment:
```
SENTRY_FEATURES["organizations:global-views"] = True
SENTRY_FEATURES["organizations:events"] = True
SENTRY_FEATURES["organizations:events-v2"] = True
SENTRY_FEATURES["organizations:event-attachments"] = True
SENTRY_FEATURES["organizations:grouping-info"] = True
```
3. Run `docker-compose build`, `docker-compose run --rm web upgrade` then `docker-compose up` 
4. Access `localhost:9000` and it results into the following error: `Oops! Something went wrong`

<img width="1392" alt="Screen Shot 2019-10-16 at 16 30 34" src="https://user-images.githubusercontent.com/4175461/66929750-dd66a200-f033-11e9-90ec-8d57e68f87a9.png">

### What you expected to happen

It should display the events.

**Comment by markstory** [comment]
The events tab requires snuba which is not currently part of the on-premise setup yet.

**Comment by markstory** [comment]
No ETA yet. But when a release is made it will be announced on the forums.

**Comment by billyvg** [comment]
@AkdM There is a beta available right now: https://forum.sentry.io/t/sentry-v10-beta-now-available/8097 - Events will not be available on v9.
