### ISSUE TITLE
Graph shows no events

### ISSUE THREAD

**Issue by DataGreed** [getsentry/sentry#1510]
So, we have updated to the latest version of sentry, everything works fine except graphs, it's easier to show than describe:

![2015-04-24 14 19 25](https://cloud.githubusercontent.com/assets/2033163/7317781/160287e8-ea8d-11e4-90d8-32366f95cdcb.png)

**Comment by dcramer** [comment]
Have you configured the TSDB correctly?

**Comment by DataGreed** [comment]
I am not quite sure what should I check exactly :-[

sent from a small handheld device with autocorrection
24 апр. 2015 г. 8:35 PM пользователь "David Cramer" <
notifications@github.com> написал:

**Comment by dcramer** [comment]
Mostly SENTRY_TSDB

http://sentry.readthedocs.org/en/latest/tsdb/index.html

**Comment by dcramer** [comment]
Feel free to reopen if its more than a misconfiguration

**Comment by DataGreed** [comment]
thanks, will try that
