### ISSUE TITLE
Sentry to JIRA Server integration - not possible to add.

### ISSUE THREAD

**Issue by pajacz** [getsentry/sentry#15111]
After successful integration adding, (jira-server answered with

```
Access Approved
You have successfully authorized 'Sentry'. Please close this browser window and click continue in the client.
```
) integration still unavailable in Sentry. 

We have installation On Premise, own domain. Sentry 9.1.2 and JIRA Server v8.4.2.

I can see there was already same ticket #11822 open, but closed as "continue in emails".. but for us having the same issue, not helping at all. Any suggestion appreciated. 

Pavel

**Comment by markstory** [comment]
Jira should be redirecting your browser back to Sentry. If that doesn't happen Sentry can't finish the connection process.

**Comment by pajacz** [comment]
Well.. a did all the steps ad described, i can click on the link in JIRA and will get to Sentry page, JIRA successfully authorised the auth request, but after all will end at the screen saying ..
```
Access Approved
You have successfully authorized 'Sentry'. Please close this browser window and click continue in the client.
```

I can't see any more I can do. I've successfully integrated Sentry to e.g. GitLab, and JIRA to e.g. Slack.. but not able to connect Sentry to JIRA at all... any hints? Is someone having more luck or same issue? 

Thanks in advance!

**Comment by pajacz** [comment]
Anyone? Please. :(

**Comment by BYK** [comment]
@pajacz maybe this is an issue with the Jira Server you are using? There seems to be a new version out (8.5) which may have fixed this?

**Comment by forzagreen** [comment]
I am having the same issue with v9.1.2

**Comment by jessedobbelaere** [comment]
I'm setting up the integration for JIRA server v8.5.1 with Sentry.io and I'm getting the same message _"Please close this browser window and click continue in the client."_ without redirect to Sentry. Anyone got any luck so far?

**Comment by maxammann** [comment]
Same problem here, Jira Software 8.4.1 and Sentry 9.1.1.

When installing the integration from the sentry side, the website just loads for half a minute and does nothing.

**Comment by zdelagrange** [comment]
same issue with Sentry 10.1.0.dev079b31fc

**Comment by jessedobbelaere** [comment]
FYI my issue got resolved by filling in the correct callback url in Jira. My Jira admin left the callback url field blank during my first attempt to set up Sentry's Jira integration. 
After filling in the callback url, it worked fine and redirected back to Sentry...

**Comment by yxxhero** [comment]
@jessedobbelaere what is the callback url like? please help me?

**Comment by BYK** [comment]
Closing as this seems like a user configuration error.

**Comment by maxammann** [comment]
Works in latest Sentry :+1:
