### ISSUE TITLE
Where to look up error of sentry itself?

### ISSUE THREAD

**Issue by MichaelLogutov** [getsentry/sentry#1512]
We've set up sentry on our server and sometimes we've got errors while working with sentry web interface. It looks like this:

```
There was an internal server error while processing your request.

You may reference this error as 0f77c43f3ced487085e225207f11beef.
```

Since the error code is always changing I assume it's pointing to some kind of error ID in some storage. But I can't find it.

**Comment by wilful** [comment]
I also wonder how to enable debugging. I can not set up with a bunch of REDMINE without debugging errors.

The current configuration is identical to the "quickstart". Logs are not written in sislog and not to stdout

**Comment by dcramer** [comment]
We're going to improve the logging practices, but Supervisor controls those.

Regarding the internal Sentry project, its at /sentry/ by default

**Comment by dcramer** [comment]
GH-1514
