### ISSUE TITLE
how to change the output log format about sentry this program?

### ISSUE THREAD

**Issue by maggiezhangfan** [getsentry/sentry#15146]
We use helm install sentry on k8s, there are cron, web,worker,pg and redis above six pods.
But we meet a question, sometimes  the web and worker pods restart, even if we want to observe the logs of them. unfortunately, when pods finished restart , the logs will be the newest and don't have the passed logs. so we want to put the logs into elk. And this need us to change the log format of sentry this application. I want to ask if there is somebody try to change log format and the steps.
Thanks!

**Comment by mattrobenolt** [comment]
Most commands take a `--logformat=machine` flag that you can pass.

So for example: `sentry run web --logformat=machine` will give you JSON.

**Comment by mattrobenolt** [comment]
I guess also in your case, it's probably easier to pass the environment variable `SENTRY_LOG_FORMAT=machine` instead of shoving in the command line flags everywhere.

**Comment by maggiezhangfan** [comment]
“SENTRY_LOG_FORMAT=machine”
this is useful.

> I guess also in your case, it's probably easier to pass the environment variable `SENTRY_LOG_FORMAT=machine` instead of shoving in the command line flags everywhere.
