### ISSUE TITLE
Improve accessibility of internal project

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1514]
The internal project is a bit odd, and generally people don't see it by default.

We should:
1. Try to guarantee its part of the same org in SINGLE ORG mode. This should generally be true on new installs, but is odd if you want to convert an existing install.
2. Ensure superusers have a clear selector for "this is the org where the internal sentry projects live".

There's a few complexities around this, but we can always change some things to make this more reasonable.

Currently things get created in a 'sentry' org, with the project slugs being 'backend' and 'frontend', assuming the projects dont exist.

**Comment by BYK** [comment]
I think we now use the name `internal` as a catch-all or something? Closing as I don't see us working on this soon.
