### ISSUE TITLE
{"subjectPrefix":["This field may not be blank."]}

### ISSUE THREAD

**Issue by Jimbolino** [getsentry/sentry#15151]
## Important Details

How are you running Sentry?

* [X] Saas (sentry.io)

## Description

I have a couple of different projects. One with a subjectPrefix, the others without.
When i try to empty the field (and press enter to submit) it says: "This field may not be blank."

## Steps to Reproduce

1. Add project
2. Anter "Subject Prefix"
3. Remove "Subject Prefix"

### What you expected to happen

It should not complain and do what it's told ;)

**Comment by BYK** [comment]
This seems to be fixed now, closing.
