### ISSUE TITLE
Unable to reach Sentry log server: HTTP Error 500

### ISSUE THREAD

**Issue by ernestoarbitrio** [getsentry/sentry#1516]
I deploy sentry on Centos 7. Sentry starts with supervisord and for few minutes it's ok. If i try to launch a <code>python manage.py raven test</code> all is ok. After 2/3 minutes if i retry a raven test i receive:
<code>Sending a test message... success!
</code>
<code>
Event ID was 'bf07ef95b21341b4a409e9703aec7fd3'
Unable to reach Sentry log server: HTTP Error 500: INTERNAL SERVER ERROR</code>

**Comment by dcramer** [comment]
You'll need to look into the logs (which are determined by supervisor config).

It's likely you have something misconfigured, but the logs should give a fairly clear reason.
