### ISSUE TITLE
sourecmap error

### ISSUE THREAD

**Issue by maggiezhangfan** [getsentry/sentry#15172]
we user helm install sentry on k8s, but the sourcemap report some error likes:
"name":"sentry.lang.javascript.processor","event":"sourcemap.compress_read_failed"
in this page "https://docs.sentry.io/platforms/javascript/sourcemaps/"
i find it mentions webpack-plugin, does it mean we should bulid this plugin in our image?
thanks so much!

**Comment by maxeber** [comment]
I am facing the same issue. Got 1.1m events reported on the internal sentry projects.

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.

Also keep in mind that we do not maintain the k8s Helm Charts ourselves so you'd have better luck reporting issues in that repo.
