### ISSUE TITLE
Mute whole projects in case of maintenance downtime

### ISSUE THREAD

**Issue by christophlehmann** [getsentry/sentry#1517]
When i do server updates there is the point services stop and sentry get notified about this 'problem'.

I like to see an option to mute whole projects or projects by tags.

**Comment by dcramer** [comment]
Just to not let this linger, I'm generally in favor of this feature. I'm not sure how it should function from a UI/UX point of view, but it seems generally useful.

**Comment by chriscannon** [comment]
I think this would also be useful for AWS services where you must specify a maintenance window. An even better version of this request would include monitoring SNS alerts to only mute the project if maintenance is actually happening.

**Comment by cheddarwhizzy** [comment]
I'm also in favor of this. I'm guessing Sentry wants the implementation of exception logging to be handled with maintenance in mind. I'm thinking of creating a sentry proxy service to handle this type of logic. My use case is to have sentry not log an exception if the environment is in maintenance mode, but I need to query http endpoints to get maintenance status. 

If there's already a thing to do this, I'd love to learn about it.

**Comment by BYK** [comment]
I think rate limiting is a good enough solution for this: https://docs.sentry.io/product/accounts/quotas/manage-event-stream-guide/#6-rate-limiting

Closing due to staleness.
