### ISSUE TITLE
Data scrubber is too agressive

### ISSUE THREAD

**Issue by realityking** [getsentry/sentry#1518]
The data scrubber is a great idea, unfortunately it's too agressive. In our system we use IDs that look like this `"150428427078522"` (string is correct), which are scrubbed making debugging quite a bit harder.

No genius idea how to solve it, exxept by looking at the keys instead of the values, but maybe someone else has one.

**Comment by mattrobenolt** [comment]
Yeah, so for context, that's being scrubbed because it looks like a credit card number. Not entirely sure the work around at the moment though.

**Comment by dcramer** [comment]
I dont have a great answer here, and I'd rather it be too aggressive vs too lenient. I think in this case the best we can say is "disable it if it doesnt work for you"

**Comment by realityking** [comment]
That's fair enough. It would be great if thiswould be a more fine grained configuration, i.e. I would only need to disable the credit card part (especially since we don't currently deal with CC numbers in our syste)
