### ISSUE TITLE
Demangling not working c++ app (Possibly hit buffer limit ?)

### ISSUE THREAD

**Issue by conradjones** [getsentry/sentry#15206]
I'm seeing the names for this class not being demangled (native SDK / minidump / crashdump ) example : 
_ZN2ui5debug12CrashHandlerINS_3app3mix8DesignerI9EditorAppINS_6config17ConfigDialogMixinINS3_13PlugInChainerINS3_19PlugInWindowManagerIN6engine3app9templates21PlugInEnumeratorMixinINSC_12StereoOutAppINS_11ApplicationEEEJN5audio6plugin3vst19VstPlugInEnum...

this c++ class looks something like this CrashHandler<Designer<EditorApp<ConfigDialogMixin<PlugInChainer<PlugInWindowManager<engine::app::templates::PlugInEnumeratorMixin<StereoOutApp<Application< BASE > >>>>>>>>

**Comment by conradjones** [comment]
The same class name is correctly demangled on a windows build of the same program, the non working example above was MacOS

correct demangle:

ui::debug::CrashHandler<ui::app::mix::Designer<EditorApp<ui::config::ConfigDialogMixin<ui::app::mix::PlugInChainer<ui::app::mix::PlugInWindowManager<engine::app::templates::PlugInEnumeratorMixin<engine::app::templates::StereoOutApp<ui::Application>,audi.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

/cc @jan-auer
