### ISSUE TITLE
Problem with sending data with exceptions on Sentry

### ISSUE THREAD

**Issue by kurama-cube** [getsentry/sentry#15215]
Hi there.
I have a problem with python Sentry SDK
When I want to capture an exception with the capture_exception method,  I set a context with set_context and pass all the extra data to it as a dict and in the sentry web panel, I can't find fields which have None values or in some exceptions, some fields are missing, Sentry will remove these fields. how can I send a JSON object with an exception?

**Comment by untitaker** [comment]
@kurama-cube The github bugtrackers are not for support requests. Please use the forums. Is this your post? https://forum.sentry.io/t/capture-exception-not-showing-on-sentry-issues-tab/7908
