### ISSUE TITLE
Removal of djcelery causes connection has gone away issues

### ISSUE THREAD

**Issue by rogerhu** [getsentry/sentry#1521]
Is there a reason it was removed?

https://github.com/getsentry/sentry/commit/8f8eede4fd9a522aa8f64d471e02c2f9236bba5c

One of the things djcelery does is close the database and cache connections between Celery task runs.   It either has to be re-implemented in the code (see  https://github.com/celery/django-celery/blob/master/djcelery/loaders.py#L122-132) or just added back into requirements.

See this discussion for more context:

https://groups.google.com/forum/#!topic/django-users/eCAIY9DAfG0

**Comment by dcramer** [comment]
Hrmph, wonder how this hasn't bitten us in prod. Could be related to the fact that we run a custom backend to ensure connectivity to the db. Will get this patched up.

**Comment by dcramer** [comment]
I'm going to pull in a lot of the loader code into the new Celery app (slightly infuriated that Celery suggests djcelery is no longer needed).

I will also pull getsentry.db.postgres into Sentry core which solves any number of issues like this.

**Comment by rogerhu** [comment]
Thanks!  For the record we're still on MySQL so feeling the pain there.. :)

**Comment by jaysoffian** [comment]
More than suggests, it explicitly says it isn't needed: "Previous versions of Celery required a separate library to work with Django, but since 3.1 this is no longer the case."

http://celery.readthedocs.org/en/latest/django/first-steps-with-django.html

:-(

**Comment by rogerhu** [comment]
Celery 3.1.18 got released and I realized a lot of this code got moved into Celery directly: https://github.com/celery/celery/commit/5e6245146aa082be6762ad30123943e5971ab03b

**Comment by rogerhu** [comment]
Checking to see if this fix in Celery 3.1.18 resolves the problem:

https://github.com/celery/celery/issues/2453

**Comment by rogerhu** [comment]
Also noticed that I'd been running Celery v3.0 on our Sentry server...so upgrading to Celery 3.1 too.

**Comment by dcramer** [comment]
@rogerhu old celery should have been fine assuming its not new sentry (tbh it should have yelled at you)

**Comment by rogerhu** [comment]
Yeah we're on Sentry 7.4.3  still.... and installs Celery 3.0.25.

https://github.com/getsentry/sentry/blob/2f0f366c9ca2c965f7776194854a9b8efef68988/setup.py

**Comment by dcramer** [comment]
@rogerhu def should still be requiring django-celery pre 7.5. Maybe the issue is something else there?

**Comment by rogerhu** [comment]
Yeah this just might be Amazon ElasticCache DB just going away on us...I think we can close for now.  Will reopen if I find the issue.  Thanks for the fast response!

**Comment by jaysoffian** [comment]
Well that was fun!. :-)
