### ISSUE TITLE
Active tab on nav bar has cursor: default instead of cursor: pointer

### ISSUE THREAD

**Issue by Bartzy** [getsentry/sentry#1522]
Hi,

At least in getsentry.com hosted version, the active tab in the nav bar ("Stream", for example) has ```cursor: default``` and not ```cursor: pointer```.

Small thing but it is pretty annoying to my eyes :)

I found it only in the CSS: https://github.com/getsentry/sentry/blob/190ac812de6541b6a3f9df456f01dcbe5a5ae5b3/src/sentry/static/sentry/styles/sentry.css#L3449

But not in any LESS file, so I didn't open a PR.

Anyone can point me to the corresponding LESS line?

Thanks!

**Comment by ckj** [comment]
@Bartzy This is most likely a Bootstrap 2.0 thing and will be resolved in a future update. I'd for sure merge any PR's in the meantime, though.
