### ISSUE TITLE
"Invite new members" pop up bug

### ISSUE THREAD

**Issue by pbc** [getsentry/sentry#15220]
## Important Details

How are you running Sentry?

* Saas (sentry.io)

## Description

When you try to add a new member to a team using the "Invite new members" pop up menu, and you fill in the "EMAIL ADDRESSES" field, it gets reset after clicking away from the input.

The only way this field doesn't get reset is if you press "tab" instead of clicking away.

## Steps to Reproduce

1. Go to Settings -> Organization -> Members section
2. Click "Invite Members" button
3. Fill in the "EMAIL ADDRESSES" field by pasting a full email address
4. Click on the "join your organization." text so the input field loses focus

### What you expected to happen

The "EMAIL ADDRESSES" should not be reset.

### Possible Solution

Remove the code which converts the email into a visual tag or debug this code.

**Comment by BYK** [comment]
This seems to be working right now. Feel free to ping back here if you are still experiencing the issue.
