### ISSUE TITLE
Combine GitLab URL and path to simplify integration installation

### ISSUE THREAD

**Issue by kinghuang** [getsentry/sentry#15222]
## Summary

The GitLab integration's installation form currently requires that the *GitLab URL* (https://gitlab.com) and *GitLab Group Path* (my-group/my-subgroup) be filled in separately. I think it would be easier for users if they could just fill in the entire URL without splitting (https://gitlab.com/my-group/my-subgroup).

## Motivation

I have MRs in flight to add subgroup (#15178) and whole-instance (#15188) support. There's still an outstanding issue about supporting user namespaces (#11735).

The `Group Path` field is confusing for instance and user level integrations. And, the instructions on the installation form about splitting the url and path add complexity.

Combining the two fields into one field that takes the full URL to a GitLab instance, group, or user would simplify the installation process and provide a clearer path to user namespace support. The URL can be split out into the base and path parts in the code.

## Additional Context

This is what the installation screen looks like with the upcoming instance-level support.

![Screen Shot 2019-10-22 at 9 12 29 AM](https://user-images.githubusercontent.com/27340/67301090-2d1df100-f4ac-11e9-951f-2faeeecc6678.png)

Here's a mockup with the separate path field removed.

![Screen Shot 2019-10-22 at 9 14 57 AM](https://user-images.githubusercontent.com/27340/67301380-8be36a80-f4ac-11e9-8367-fd686e8135c5.png)

**Comment by markstory** [comment]
If the group path and host were merged how would you handle gitlab instances that run in a path? For example `http://internal.example.org/gitlab`?

**Comment by kinghuang** [comment]
Hmm, is it even possible to run GitLab at a subpath? I’ll look into that.

**Comment by kinghuang** [comment]
You're right, GitLab can be configured with a relative URL that is not the root of a domain.

https://docs.gitlab.com/omnibus/settings/configuration.html#enable-relative-url-in-gitlab

Combining the two fields won't work, then.

**Comment by kinghuang** [comment]
Closing this request, as it isn't possible to distinguish between the base GitLab URL and group path  in a single field when GitLab is not at the root of the domain.
