### ISSUE TITLE
`STATIC_URL` not working

### ISSUE THREAD

**Issue by humiaozuzu** [getsentry/sentry#1523]
![bb919e09-6310-45ad-bd36-dd56cc0d3d30](https://cloud.githubusercontent.com/assets/300016/7557655/1d2dfa1e-f7c8-11e4-90f0-6abb1d2ffb22.png)
The configuration is OK but requests in browser is not started with my CDN url.

**Comment by dcramer** [comment]
Sentry doesn't actually support STATIC_URL at this time.

**Comment by humiaozuzu** [comment]
@dcramer Any workaround？

**Comment by dcramer** [comment]
There's not. We don't support hosting media externally from Sentry at this time.
