### ISSUE TITLE
Unattended Sentry upgrade

### ISSUE THREAD

**Issue by gamefundas** [getsentry/sentry#15257]
I know this was discussed and partially addressed in ##3855 but why cant this be implemented in a way that the first/admin user name, credentials, email etc are accepted as another set of parameters, and used only if the user hasn't been setup yet.

This will make Sentry a completely scripted installation process. Currently we have to manually perform this step in the AWS cloudformation lifecycle and then login to the hosts to bring up the server.

**Comment by BYK** [comment]
Please see this: https://github.com/getsentry/onpremise/blob/fc24bd4b82807d845342d7a494414674b587108e/install.sh#L73-L84

(and you can create an issue over at the on-premise repo if this doesn't solve your problem ;))
