### ISSUE TITLE
Why have you removed the Social Auth in 7.5?

### ISSUE THREAD

**Issue by tarjei** [getsentry/sentry#1526]
Are you planning to support is as a plugin instead?

**Comment by dcramer** [comment]
We are not. Sentry has it's own auth system that truly works traditional SSO mechanisms, which was the primary intent login/register via social auth.

**Comment by tarjei** [comment]
Ah, ok. Thanks for the clarification. Maybe you should consider adding a
clarification to the releasenotes of 7.5 :P

2015-05-12 9:33 GMT+02:00 David Cramer <notifications@github.com>:

> Closed #1526 <https://github.com/getsentry/sentry/issues/1526>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getsentry/sentry/issues/1526#event-302518309>.
>



-- 
__________________
Tarjei Huse
Mobil: 920 63 413
