### ISSUE TITLE
Location header is missing when a project is renamed and 302 is returned

### ISSUE THREAD

**Issue by agaudreault-jive** [getsentry/sentry#15278]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Sentry 9.0.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I tried to rename a project an get the project with the old name using the golang http client. When the project is renamed, the response to the GET request is a 302, but an error is returned from the client since the location header is not set on the response

## Steps to Reproduce

1. Rename a project slug
2. curl on the old project url (I used golang http client)
3. result is `Get https://sentry.example.com/api/0/projects/org/oldName/: 302 response missing Location header`

Good items to include here include:

- Include a stacktrace or other logs when relevant
The response body of the 302 is `{"detail": {"slug": "newName"}}`

The headers are
allow: GET, PUT, DELETE, HEAD, OPTIONS
content-language: en
content-length: 39
content-type: application/json; charset=utf-8
date: Fri, 25 Oct 2019 16:41:42 GMT
server: nginx/1.13.12
status: 302
vary: Accept-Language, Cookie
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block

### What you expected to happen

Location header is used by http clients to get the project with the new name on a 302 response.

### Possible Solution

Set location header to `https://sentry.example.com/api/0/projects/org/newName/` so the different HTTP client can handle this scenario. Keep the body for backward compatibility.

**Comment by agaudreault-jive** [comment]
seems fixed by https://github.com/getsentry/sentry/pull/8799 in 9.1.0.

**Comment by BYK** [comment]
Closing as this is fixed in a recent and published version.
