### ISSUE TITLE
Filter stopped work

### ISSUE THREAD

**Issue by SHELA** [getsentry/sentry#15270]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.2]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Filter stopped work.
"Sorry, no events match your filters."
by tags
logs in docker normal

## Steps to Reproduce

1. open even
2. click tag
3. no results in search

**Comment by xamix** [comment]
I confirm this issue also in `Sentry 10.1.0.dev0f66fabd`.

I have a tag named `device_name`, when I click on this tag in an issue, it display `Sorry, no issues match your filters`

I works in the search tab if I use the following syntax `tags[device_name]:xxxxxx`

Possible duplicated issue of [#13427](https://github.com/getsentry/sentry/issues/13427)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
