### ISSUE TITLE
Random values for integrations status on repeated browser refresh

### ISSUE THREAD

**Issue by alexandrul** [getsentry/sentry#1527]
After modifying the integrations and getting the successful save message, I get random values on repeated browser refresh. I will try to attach a recording where you should notice the flickering of the top-left icon on each refresh.

The installation was performed on a clean dedicated Debian 8 VirtualBox VM, using initially sqlite and then postgres (with the same behavior).

Server Version	7.4.3
Python Version	2.7.9 (default, May 12 2015, 07:17:56) [GCC 4.9.2]

**Comment by dcramer** [comment]
Sounds like your cache (or similar) is misconfigured. If you're running in a production environment you need to configure the cache backends per the settings annotations.

**Comment by dcramer** [comment]
Feel free to re-open if you determine that's not the case.

**Comment by alexandrul** [comment]
Thank you for the quick answer, it's my first try at sentry :smile:

For the record, this is the recording: http://www.fastswf.com/saFuQfk

**Comment by dcramer** [comment]
Yeah. What you're likely seeing is thread A using an in-memory cache, and thread B using a different in-memory cache. Thus on reload you see different results.

**Comment by alexandrul** [comment]
Could you please point me to some documentation for this? I'm just following the quickstart tutorial, and I didn't touched the caching section, so I'm using the default:

SENTRY_CACHE = 'sentry.cache.redis.RedisCache'

**Comment by dcramer** [comment]
Actually it looks like we don't force this atm and the default isn't great.

Basically right now you need memcached, and

```python
# If you wish to use memcached, install the dependencies and adjust the config
# as shown:
#
#   pip install python-memcached
#
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#         'LOCATION': ['127.0.0.1:11211'],
#     }
# }
```

**Comment by alexandrul** [comment]
Thank you very much, the issue is not reproducible anymore with memcached.
