### ISSUE TITLE
sentry_messagefiltervalue table always empty

### ISSUE THREAD

**Issue by SHELA** [getsentry/sentry#15287]
in logs many records that filter tried select records from table sentry_messagefiltervalue

 SELECT "sentry_messagefiltervalue"."id", "sentry_messagefiltervalue"."project_id", "sentry_messagefiltervalue"."group_id", "sentry_messagefiltervalue"."times_seen", "sentry_messagefiltervalue"."key", "sentry_messagefiltervalue"."value", "sentry_messagefiltervalue"."last_seen", "sentry_messagefiltervalue"."first_seen" FROM "sentry_messagefiltervalue" WHERE ("sentry_messagefiltervalue"."project_id" = 2  AND "sentry_messagefiltervalue"."group_id" = 2816  AND "sentry_messagefiltervalue"."key" IN ('sentry:release', 'release')) ORDER BY "sentry_messagefiltervalue"."first_seen" ASC LIMIT 1
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

[What happened]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. and so on.

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration when relevant

### What you expected to happen

[What you think should be happening]

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by mattrobenolt** [comment]
What's the question? Depending on what version of Sentry you're running, this table potentially isn't used anymore.

So unclear if there's an actual issue or not.

For context, this is just related to event tags. I know, the name of the table doesn't represent this, but it's hard to rename tables.

**Comment by SHELA** [comment]
Questions why script making select to empty table.
And because of this Filter not work.
Sentry 9.1.2
