### ISSUE TITLE
Why are there no releases?

### ISSUE THREAD

**Issue by Amf1k** [getsentry/sentry#15288]
## Summary

Release stable releases in github releases

## Motivation

Some companies have a self-hosted software deployment policy that says that stable open source releases are needed (the master branch is not a stable version). 
The current release 9.1.2 does not work with PDB files and minidumps from crashpad (sentry-native-sdk) are not sent. But everything works well with the master.

**Comment by BYK** [comment]
Hi @Amf1k - We are actively working on this (https://github.com/getsentry/onpremise/pull/220). There are significant and breaking infrastructure changes with Sentry 10 (what's on master branch) so we are trying to get everything in place properly and a smooth upgrade path from 9.1.2.

We are also working on getting continuous releases from master so feel free to try that branch over at the on-premise repo or using our nightly Docker images directly at https://hub.docker.com/r/getsentry/sentry
