### ISSUE TITLE
Raven test work but sentry doesn't save any event

### ISSUE THREAD

**Issue by viewlview** [getsentry/sentry#1533]
I installed latest Sentry. I installed Redis too. Sentry web panel works fine. Also by running 'python manage.py raven test' I can see successful sending:
'''
Client configuration:
  servers        : ['http://mydomain.com:9000/api/2/store/']
  project        : 2
  public_key     : xxx
  secret_key     : xxx

Sending a test message... success!
Event ID was 'a12d4ce48c5646b8aa2be95554b751c1'
'''
But nothing saved and shown in Sentry.

Also I see this message in Sentry logs:
'''
OperationalError: (2006, 'MySQL server has gone away')
[ERROR] Error processing 'get_rules' on 'JavascriptPlugin': (2006, 'MySQL server has gone away')
'''

By the way I run Sentry in my development with same configs. On my local machine, event saved and counted in Sentry stream. I see same MySql error. And when I click on an event I can't see detail and I faced with a page by this content:
Page Not Found
The page you are looking for was not found.

**Comment by dcramer** [comment]
#1441
