### ISSUE TITLE
Unable to skip the 'add project' step when creating teams

### ISSUE THREAD

**Issue by twelvelabs** [getsentry/sentry#1535]
I setup a ton of projects under a single team and am now attempting to create additional teams to move some of them into. When I click on the 'Create a new Team' button from the teams listing page, I'm shown a two step workflow: name the team, and name the first project. When I click on the 'Skip this step' button, it looks like the form submits but it just ends up reloading the same 'add a project' form.

In order to progress, I have to create a dummy project and then go delete it afterwords.

**Comment by dcramer** [comment]
I wasn't able to reproduce. What version of Sentry?

**Comment by twelvelabs** [comment]
Hosted version. I just checked again and was able to repro [here](https://app.getsentry.com/organizations/vox-product/teams/new/). Possible browser specific JS bug?

OS: 10.9.5
Browser: Safari 7.1.6

**Comment by benvinegar** [comment]
Team creation no longer requires creating a team in Sentry 9.
