### ISSUE TITLE
mail alert service not available in all projects

### ISSUE THREAD

**Issue by alexandervlpl** [getsentry/sentry#15353]
I have two projects belonging to the same team. When I configure alerts for project A, the "Mail" service is available:
![image](https://user-images.githubusercontent.com/8945883/67892367-a4ffb180-fb65-11e9-8bf3-b53fb4cd06f3.png)
**I get email alerts from this project as expected.**

For project B, no Mail service appears and emails are not sent:
![image](https://user-images.githubusercontent.com/8945883/67892422-bf398f80-fb65-11e9-80c9-7f54c0f06ac1.png)
I only get Slack notifications for this project.

Any ideas?

This is Sentry 8.15.0 manual install (not Docker).

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.

**Comment by alexandervlpl** [comment]
Thanks for the quick response. **Seems like a bug to me though**, I can find no configuration problems or any difference between these projects whatsoever.

**Comment by BYK** [comment]
@alexandervlpl even if it is a bug you are talking about Sentry 8.15.0 which is very old so we won't be investigating that. If this is still a bug in the most recent version of Sentry we'd give that a look.
