### ISSUE TITLE
Unable to specify directory for s3 storage in filesystem

### ISSUE THREAD

**Issue by PaarthB** [getsentry/sentry#15363]
When we specify s3 bucket as the filestorage system not the default one on the disk, it doesn't give any option to specify the directory / path inside the bucket where we would like to put the related content (sourcemaps, release artifacts etc.). But when looking into the code, there seems like a variable takes care of that: `self.location` https://github.com/getsentry/sentry/blob/master/src/sentry/filestore/s3.py,. Is this the variable which contains the path inside the s3 bucket? How can this be specified in config file? Can you make a feature which allows users to specify path (key) of bucket along with bucket name?

Do you have any idea of this @mattrobenolt @EvanPurkhiser ?

**Comment by jimbocoder** [comment]
@PaarthB it really does look like you could simply add a value for `location` to the filestore config. Did you end up trying this? Would be interested to hear any results or workarounds you found.

**Comment by mattrobenolt** [comment]
Yeah, just pass `location` to options. We don't use the S3 backend ourselves, so you'll have to experiment, but all settings get elevated into the instance: https://github.com/getsentry/sentry/blob/master/src/sentry/filestore/s3.py#L298-L300 so any of those are able to be set.
