### ISSUE TITLE
Organization button to add/invite should say "Add Member" when invites are disabled

### ISSUE THREAD

**Issue by jathanism** [getsentry/sentry#1536]
I disabled organization invites my `settings.py`:

``` python
SENTRY_ENABLE_INVITES=False
```

However, in index my organization the button that links to `/organizations/:organization/members/new/` is still labeled as "Invite Member". (Source: https://github.com/getsentry/sentry/blob/master/src/sentry/templates/sentry/bases/organization.html#L18)

I feel it would be better UX to have this button say "Add Member" when `SENTRY_ENABLE_INVITES=False`. Another alternative might be to have it say "Add/Invite Member" at all times?

Thanks for listening!

**Comment by MaxBittker** [comment]
this is fixed now
