### ISSUE TITLE
Sentry package depends on insecure versions of Django

### ISSUE THREAD

**Issue by alimony** [getsentry/sentry#1537]
The setup file mandates `Django>=1.6.0,<1.7` meaning depending on Django 1.6.x:

https://github.com/getsentry/sentry/blob/master/setup.py#L70

However, Django 1.6 is not at all supported since April 1 this year:

https://www.djangoproject.com/download/

Is there a plan for updating the dependency to a more recent version of Django?

**Comment by dcramer** [comment]
There is not. We update Django when we see a need and if there's a relevant security release (that they don't backport) then we will patch it.
