### ISSUE TITLE
user agent being overriden

### ISSUE THREAD

**Issue by TerribleDev** [getsentry/sentry#15387]
- [ ] Review the documentation: https://docs.sentry.io/
- [ ] Search for existing issues: https://github.com/getsentry/sentry-javascript/issues
- [ ] Use the latest release: https://github.com/getsentry/sentry-javascript/releases
- [ ] Provide a link to the affected event from your Sentry account

## Package + Version

- [x] `@sentry/browser`
- [ ] `@sentry/node`
- [ ] `raven-js`
- [ ] `raven-node` _(raven for node)_
- [ ] other:

### Version:

```
5.6.3
```

## Description

Hi, we have some third party scripts on our site that log information. One of our vendors has mentioned to us recently that some of our requests have the user agent header of `sentry/10.0.0.dev0 (https://sentry.io)` instead of the actual user agent of our customers. We do not set or change the user agents ourselves. We do not server side render our javascript, and this is only from `XMLHttpRequest`'s being made from the browser.

We don't have a ton of data, but there is no correlation that its coming from a particular browser. We can tie these sessions back to our own access logs.

**Comment by kamilogorek** [comment]
I believe this issue belongs to this repo. I can see related code here - https://github.com/getsentry/sentry/blob/ff7fd4bd455d0fd049bdeb306aba72543e28b3a4/src/sentry/net/http.py#L144-L164

**Comment by TerribleDev** [comment]
We don't use python

**Comment by untitaker** [comment]
@TerribleDev assuming you are on sentry.io, could you link such an issue right here?

**Comment by untitaker** [comment]
@TerribleDev could you clarify what a vendor and what a customer is in your setup? Right now it seems like you have some integration/plugin on Sentry configured to send data to another server, but that's really all I got from your post. Furthermore it's unclear whether you're on SaaS (sentry.io) or a self-hosted installation of Sentry, and whether those wrong user agents surface as part of a Sentry issue or in some completely different tool.

**Comment by TerribleDev** [comment]
@untitaker  we're on sentry.io (SaaS), cargurus organization. I'm willing to be more candid with you in private, but not on public github.

The wrong user agents do not appear in sentry.io, but in the ajax calls we make to a seperate domain from the browser

**Comment by mitsuhiko** [comment]
To clarify what is going on here: if you are not uploading source maps and you have fetching enabled, the sentry server will reach out and try to download the minified javascript files and the source maps they reference from the location in the stack trace.

You can prevent this by disabling fetching and uploading source maps.
