### ISSUE TITLE
Send email

### ISSUE THREAD

**Issue by silverpark** [getsentry/sentry#1539]
Hi Sentry Team,

I've a probleme when I receive an error from sentry with the same message by email with specific différents parameters for analyse an error.

I don't receive all error by email, probably considered like a spam, how to receive all error by email with no exceptions ?

Regards

**Comment by dcramer** [comment]
Click Rules under project settings

**Comment by silverpark** [comment]
Great. Thank you !

**Comment by silverpark** [comment]
Configuration don't save about "Rate limits" : "100%" and "Notifications".

**Comment by dcramer** [comment]
I cannot reproduce any issues with saving rate limits, nor notifications.

**Comment by silverpark** [comment]
My version of sentry is : 6.4.2.1, I keep this version beacause I don't know if my other issue is fixed about a particular url with proxy reverse.

**Comment by dcramer** [comment]
Unfortunately we only provide support for the current release series.
