### ISSUE TITLE
Request resend

### ISSUE THREAD

**Issue by yeleleo** [getsentry/sentry#15409]
## Summary

Sometimes you can see the issue in the code triggered by POST request. Sentry includes all details of the request, headers and body even in curl format, and to re-send it you need to copy-paste it to the console. 

So it would be very cool to be able to resend the data in a single click

## Motivation

Test and re-send data

![2019-11-02_12-07-44 2](https://user-images.githubusercontent.com/1327411/68075786-ef26a400-fdac-11e9-94de-9cd3e73e7e42.png)

**Comment by billyvg** [comment]
I would probably not want a button that sends the request, but I could see adding something similar to `curl` where you get a `fetch()` command you could paste into your console at your own leisure.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
