### ISSUE TITLE
Javascript grouping of errors is all over the place

### ISSUE THREAD

**Issue by pratik60** [getsentry/sentry#1540]
I think it places more emphasis on which page the error occured from, rather than the actual error itself.

So for me, that count of https://xyz.com/summary, is increasing, but they are actually different errors being mapped to the same.

Has anyone else faced similar issues?

**Comment by dcramer** [comment]
We prioritize the stacktrace above all else.

**Comment by pratik60** [comment]
I think we get an error alert for every valid new error, but the grouping on the homepage (dashboard feed) is definitely not based on stack trace.

**Comment by dcramer** [comment]
Do you have an example?

The stacktrace is absolutely what it hashes on, assuming it exists (i.e. isnt a single frame with no information). If you dont use sourcemaps/etc though it gets a lot less useful.

**Comment by mattrobenolt** [comment]
Closing this due to lack of information/we may have improved this.
