### ISSUE TITLE
Sentry slows down client while sending errors

### ISSUE THREAD

**Issue by keithslater** [getsentry/sentry#1541]
Hello, I am running into an issue with sentry and I hope some one can help. When a user gets errors they are sent to sentry and the web client completely stops until the events are completely done sending. Sometimes this can take a long time if it is a major issue. During the time, the browser becomes unresponsive until it's done. Anyone know what is causing this and how I can fix it?

**Comment by dcramer** [comment]
1. your client is synchronous (whereas good clients are async)
2. if you're using self-hosted sentry, your server is probably not configured well
3. and finally, its an error, you should accept consequences

**Comment by keithslater** [comment]
Got it. I'm using raven-php so I switched it to use async.. Hopefully that will help.
