### ISSUE TITLE
Navigating to a project from the Stats page takes me to Settings for the project

### ISSUE THREAD

**Issue by kgraves** [getsentry/sentry#15431]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ √ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I'm using the Stats page (https://sentry.io/organizations/[ORG]/stats/) to determine which projects have the highest rate of issues/events. When I click on a project name I expect that I'll be brought to the project's page with issues listed. (https://sentry.io/organizations/[ORG]/issues/?project=[PROJ_NUM]) Instead I'm brought to the settings for the project, which is a little confusing.

## Steps to Reproduce

1. navigate to https://sentry.io/organizations/[ORG]/stats/
2. find a project, and click on the name (you can also view the link's href)
3. you'll arrive at the project's settings page https://sentry.io/settings/[ORG]/projects/[PROJ]/

### What you expected to happen

Based on the context of what's shown on the Stats page, I expect that I'll be brought to the project's page, listing issues for that project.

### Possible Solution

I'm sure you all have this under control, but I'm going to guess using an incorrect url util function in a template somewhere? 😃 🤷‍♂

**Comment by BYK** [comment]
@EvanPurkhiser any idea whether this is intentional or not? I also expected to be taken to the issue stream instead of the settings page here.

**Comment by EvanPurkhiser** [comment]
Seems reasonable to me.
