### ISSUE TITLE
Can not create sample event

### ISSUE THREAD

**Issue by maggiezhangfan** [getsentry/sentry#15440]
A strange problem, the local admin user can create sample event , his role is owner.
a another user which is member can not create sample event , return 403, i change his role to admin, manager and owner. But none of them can create sample event and all return 403. Anyone know the reason of this situation? thanks.

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
