### ISSUE TITLE
No events after upgrade to 7.5

### ISSUE THREAD

**Issue by pveyes** [getsentry/sentry#1547]
Somehow events are not displayed in project dashboard after upgrading from 6 to 7.5, but I can see them in global stats menu

Manually triggering events increase the stats count, but event lists are still not displayed in project dashboard

Any help would be greatly apreciated

Sentry version: 7.5.3
Sentry client: Raven 1.1.18
Redis server: 3.0.1

**Comment by dcramer** [comment]
Did you go through the upgrade instructions and the change log?

7.x is a huge change and the required configuration greatly differs.

Feel free to re-open if you have more information, but it's mostly certainly an issue with something not running or not being configured.

i.e. celery with -B, redis TSDB, etc
