### ISSUE TITLE
Sentry not receiving any crash reports

### ISSUE THREAD

**Issue by imkarthikk** [getsentry/sentry#1548]
I've self-hosted Sentry (7.5.4) and weirdly, none of the crash reports are being recorded or displayed. 

The crash reports are being sent correctly from my Rails app, and also, the nginx log reports that there are no errors. It used to work perfectly fine earlier. Am I doing something wrong here?

**Comment by dcramer** [comment]
It sounds like your workers aren't running.

Feel free to reopen if you find nothing in worker logs indicating problems.

**Comment by imkarthikk** [comment]
My bad. Looks like the worker was not starting up, after reboot. Right now, I'm doing this cheap trick of running the worker manually and closing the session. For some reason, `supervisor` is not able to run the worker. Here's my configuration: 

```
[program:sentry-worker]
directory=/usr/local/bin/
command=sudo sentry --config=/home/sentry/.sentry/sentry.conf.py celery worker -B
autostart=true
autorestart=true
redirect_stderr=true
killasgroup=true
```

**Comment by dcramer** [comment]
@imkarthikk could be permissions (supervisor user) or missing deps/etc

either way you should be able to find a log for supervisor (might need to configure it)
