### ISSUE TITLE
Clicking "cancel" on "Prevent Storing of IP Addresses" modal still enables (when disabled)

### ISSUE THREAD

**Issue by CameronHall** [getsentry/sentry#15494]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.2]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I was fiddling with the "General Settings" >> "Security & Privacy" >> "Prevent Storing of IP Addresses". It was in a disabled state, when I checked it to enabled a confirmation modal appears. Clicking "cancel" on the modal will still enable the setting. 

## Steps to Reproduce

1. Ensure "Prevent Storing of IP Addresses" is disabled.
2. Toggle the option and click "Cancel" on the modal
3. Observe "Prevent Storing of IP Addresses" still enable.

### What you expected to happen

It doesn't enable.

**Comment by billyvg** [comment]
@CameronHall Do you mean the opposite in your repro steps? It should pop up only when you are disabling (it warns about privacy implications when disabling). This is not a bug in `master`, unfortunately you'll have to wait for our [v10 release](https://forum.sentry.io/t/sentry-v10-beta-now-available/8097)

Thanks for reporting!
