### ISSUE TITLE
Javascript sources are not fetched if source map contains sourcesContent for some files

### ISSUE THREAD

**Issue by liwo** [getsentry/sentry#1551]
In our setup we include several angular components. Some of these contain sourcesContent in their source maps, some don't. If we merge these together with e.g. grunt-contrib-concat, the resulting source map contains a sourcesContent element with value null for those files that didn't have this and contains the source for others. As far as I understood the [source map spec](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?usp=sharing), this is perfectly fine.

When we report an error using raven-js to our sentry, the sources for these files are not fetched. The error message is not very descriptive, just "Source was not found: http://example.com/scripts/angular.js". If the source map does not contain sourcesContent at all, everything is fine.

A minimal project showing the problem is at https://gist.github.com/liwo/f3e4d46a61f73bd74cd0.

I've never done python before, but I had a look at the source and I think I found the problem: 
In https://github.com/getsentry/sentry/blob/master/src/sentry/lang/javascript/sourcemaps.py in line 126 to 135 (at time of writing, revision 3cdc5c00db), in case of existence of sourcesContent in the source map, this is used as the only source for file content. Instead, in case the source for a file is null, the file should probably be fetched normally.

**Comment by dcramer** [comment]
We dont have any tests for this path of code (for whatever reasons), but the above commit should resolve it

**Comment by liwo** [comment]
Thanks for the fast response! Really appreciate it! I will test the next release version and report back. Trying to run a development snapshot version on a test system did not work (sentry init failed) and I currently can't invest much more time into it. But looking at your release cycle the next release is probably not too far away anyway, so I should be able to test soon.
