### ISSUE TITLE
Filter based on Asana linked issues

### ISSUE THREAD

**Issue by bhedavivek** [getsentry/sentry#15525]
## Summary

Filter issues based on whether they have a task assigned in Asana or any other 3rd party integration

## Motivation

The main motivation is to be able to focus on tracking issues that are not known/new/untracked by an existing engineering task managed through an external integration.

**Comment by BYK** [comment]
Related #8338

**Comment by BYK** [comment]
Turns out #21593 was not enough to cover project-level integrations (plugins) and this issue was incorrectly closed. That said there's a new issue with more context around this so if you are interested in Asana part, you can follow #23372 instead.
