### ISSUE TITLE
sourceMap file seem does not work

### ISSUE THREAD

**Issue by cindyliu-tec** [getsentry/sentry#15548]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [x] Other [briefly describe your environment]

vue project, use @sentry/webpack-plugin to upload files

## Description

on sentry's trial website I had upload source code and map file correctly but sentry dont show zhe original position of an Error, what can i do ? I have tried multiple urlPrefix to upload but still dont work

the event id is 395d53b029af4fce96cab212637da311
eventURL：https://sentry.io/organizations/huo-la-la/issues/1328542948/events/395d53b029af4fce96cab212637da311/?project=1816441

![image](https://user-images.githubusercontent.com/56294517/68648207-c8a9fb00-055a-11ea-9ddf-a6aed565d090.png)

![image](https://user-images.githubusercontent.com/56294517/68642754-1ff39f80-054a-11ea-81dd-2718de9c0707.png)

## Steps to Reproduce

1. build project to upload source code and sourcemap，with urlPrefix option
2. visit project page trigger an error
3. visit sentry event detail page

### What you expected to happen
see error position in source code

**Comment by brobertsUPS** [comment]
@cindyliu-tec I had a similar problem with my source maps and files. I was able to get mine working by only uploading the equivalent of your `dist` folder. After that, my files looked something like this when uploaded:

```
~/page/demo.js
~/page/demo.js.map
```

I would try doing:

`sentry-cli releases files VERSION upload-sourcemaps /public/dist`

After that, Sentry was able to match the error I had in the equivalent `page/demo.js` with the uploaded source map. Hope that helps!

**Comment by BYK** [comment]
@cindyliu-tec did @brobertsUPS's answer help you? Also, in the future please use [the forums](https://forum.sentry.io/) for setup issues like this as the issue board is only intended for Sentry core code-related issues.
