### ISSUE TITLE
Infinite Redirection Loop when installing 7.5.0-4

### ISSUE THREAD

**Issue by jbcurtin** [getsentry/sentry#1555]
# Reproduction Steps
Install vanilla Sentry.
Create a superuser [ I tested via: sentry createsuperuser --username=user --email=... ]
Start Sentry normally via: sentry start http [ or omit http ]

In a browser, attempt to login with the newly created user. 
Experience bug.

# Current Work-Around
Downgrade to 7.4.3: pip install sentry==7.4.3 --upgrade
Create the superuser, runserver, login-to server and create Organization/Team/etc...
Logout/KillServer
Upgrade back to 7.5.x: pip install sentry --upgrade
Bootup server again.
Login. 
Enjoy.

**Comment by dcramer** [comment]
Was this a brand new install (i.e. new database)?

It's supposed to create a user and auto add that user to the team.

Also I thought we killed off createsuperuser, but you'll want to switch to createuser as it has some extra behavior.
