### ISSUE TITLE
Is there a way to add specific timestamp to an event in client side?

### ISSUE THREAD

**Issue by foreversmart** [getsentry/sentry#1556]
these days ive read the docs about the sentry client. i found i can add a specific timestamp to a message(packet). but sad found it not work for event, it seem event timestamp decided by the server side when message was received.  i found database table(sentry_eventmapping) store the info of event(sql is postgres). 
![image](http://7sbl1n.com1.z0.glb.clouddn.com/sentry_2.jpeg)
  in my scenario, i'll read the large history log file and pass these message log to the sever side for better manage. so the log timestamp is very different from the server side received timestamp. more seriously,  the whole history log message will aggregate in a short time, thus the events graph is meaningless.

**Comment by dcramer** [comment]
It's possible that we don't correctly support this in the TSDB

**Comment by foreversmart** [comment]
Thanks anyway, I think sentry with this feature will be more powerful for managing and analysing history log. this also make  sentry more flexible and extensible.

**Comment by dcramer** [comment]
@foreversmart thats true, but it's likely we may not support this in the future, at least not in-depth. It's very complicated to allow mutable history, and Sentry isn't aimed (at least not now) to be something that you can just load a bunch of historical data in to analyze. That said, the tsdb should be accepting the correct timestamps so I'd definitely consider this a bug today.

**Comment by foreversmart** [comment]
Thank you anyway
