### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by fossilet** [getsentry/sentry#1560]
When installing Sentry (7.5.4) using `pip`, the error `ImportError: No module named setuptools` occurs.

After this even `pip` cannot run. I have to install `setuptools` using the method [here](http://stackoverflow.com/a/10538412/547578).

Should we add `setuptools` to requirements or is this some kind of bug?

**Comment by dcramer** [comment]
We've seen some various issues with setuptools needing updated. Its more of a system requirement and less so of a Sentry req, and tbh it really depends on how your stuff is setup. I'm not sure if there's a way we could automate things to guarantee its always in a stable state.

Generally apt-get install python-setuptools is enough to bootstrap pip and continue from there.

**Comment by fossilet** [comment]
Thanks for the response.
