### ISSUE TITLE
HELP: Need Assistant with Azure DevOps with On premise sentry

### ISSUE THREAD

**Issue by as-gotethics** [getsentry/sentry#15623]
Hi..

Someone that can help me with this?

I've installed the Ubuntu World Cup on our Azure portal which runs a Sentry on premise.

Everything is running as it should, but we are currently integrating Azure DevOps with Sentry.

What I have done so far is:

created an app here: "https://app.vsaex.visualstudio.com/app/register"
on our organization and put the callback url to: https://sentryURL/extensions/vsts/setup/
and so I got "App ID" as well as "Client Secret"
which I have inserted into sentry.conf.py as it is here:

[https://gyazo.com/4f8cc281dae32c60d3cf837fcea018ca](url)

SENTRY_VSTS_CLIENT_ID = 'AppID'
SENTRY_VSTS_CLIENT_SECRET = 'Client Secret'

In addition, I have tried it inside config.yml like this:
SENTRY_VSTS_CLIENT_ID: 'AppID'
SENTRY_VSTS_CLIENT_SECRET: 'Client Secret'

But the only thing I get when trying to install devops inside intergrations: InvalidScope

[https://i.gyazo.com/04b67e8d57833c3e13eab2bcd9d5c7e1.png](url)

it has to be said that I have restarted the VM machines every time I made a change to be sure it has taken effect

can someone help me, maby someone can make somekind or tutorial

I don't think it should be difficult as there are not so many parameters, but I have tried most now with no luck.

Please help me.

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
