### ISSUE TITLE
Problem connecting GitLab and Sentry

### ISSUE THREAD

**Issue by itml-eu** [getsentry/sentry#15624]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [X] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Sentry cannot be connected to GitLab (gitlab.com)

## Steps to Reproduce

1. Click on integration
2. Add installation
3. Fill all data created by GitLab Applciation (secret + application ID)
4. Click Submit.

Good items to include here include:

Error popping out:

"An error has occurred
Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."

### What you expected to happen

GitLab is integrated with Sentry

**Comment by manuzope** [comment]
Hey @itml-eu, I'm unable to reproduce this.

Would you be able to file a ticket with our support reps (you can do this by logging into your account and then in the left nav clicking `Help -> Contact Support`)? And if you could provide a video of yourself running into the issue, that would greatly help us debug the issue.

Thanks!

**Comment by sbouaked** [comment]
Hi ! I have exactly the same issue.

**Comment by manuzope** [comment]
@sbouaked Could you file a ticket too? That's the best way to get issues resolved for sentry.io.
