### ISSUE TITLE
[Feature Request] Save "sort by" choice on web ui

### ISSUE THREAD

**Issue by jaumard** [getsentry/sentry#15622]
## Summary

By default issue are sort by "last seen", that's great by not really what I want to see on a day to day basis when I monitor my apps. Frequency is for me the right choice here as it will prioritize issues I should work on.  

## Motivation

So it would be nice to have a way to either: 

- choose the default mode on project settings (like this any one can choose the best one for his needs)
- when a new one is selected the choice is saved and restore 

## Additional Context

I didn't find any issue about this with a quick search, I'm using sentry 9.0.0.

**Comment by BYK** [comment]
You can now use the "pin this search" feature to achieve the same end result.
