### ISSUE TITLE
Bitbucket Integration: invalid descriptor_uri and redirect_uri

### ISSUE THREAD

**Issue by grabekm90** [getsentry/sentry#15637]
Hello,
Today I started Sentry On-Premise setup (10.0.0.dev0 version). Trying to install Bitbucket Integration I got an error:

```
This app is misconfigured. Contact the vendor for assistance.

descriptor_uri: The add-on server wasn't able to authorize your request. Try again, or contact the add-on vendor for help.

redirect_uri: Could not resolve descriptor so cannot check redirect_uri against baseUrl
```

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
