### ISSUE TITLE
Multiple use of Github Student Pack

### ISSUE THREAD

**Issue by chrislow** [getsentry/sentry#15639]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I already used the Github Student Package on another organization and another (old) primary email address. Anyway, i managed to activate it again with another organization, just by changing my primary email on github.

## Steps to Reproduce

1. Link Sentry with your current primary email on github
2. Successfully activate the student pack on an organization on sentry.io
3. Change your Github Primary email address
4. Link your github account (with the new email) to another organization
5. Get the package for free

### What you expected to happen

It should not be usable again.

![Bildschirmfoto 2019-11-18 um 19 28 32](https://user-images.githubusercontent.com/5181596/69079154-a96b0c00-0a39-11ea-91f2-8c437dfed7c2.png)

**Comment by dashed** [comment]
@chrislow Thanks for reporting this issue 👏 . My colleague @nathan-heskia has kindly addressed this issue and will be on the next deployment for SaaS. 

Going to close this out.
