### ISSUE TITLE
Why do you include .vscode/ in the repository?

### ISSUE THREAD

**Issue by yoshi1125hisa** [getsentry/sentry#15635]
## Summary

Why do you include .vscode / in the repository?

## Motivation
In other repositories I have never seen the file included

## Additional Context

I'm sorry if it added for any reason.

**Comment by BYK** [comment]
This is to provide some basic settings to get people started when using VSCode. It also helps keep people using the same settings while developing, reducing repeated configuration or confusion.

This may not be ideal when you need to use your local overrides but this feature is requested over at VSCode repo: https://github.com/microsoft/vscode/issues/40233
