### ISSUE TITLE
How do I deploy Sentry on AWS Beanstalk?

### ISSUE THREAD

**Issue by joetpaxton** [getsentry/sentry#1564]
Hi,

I have an Amazon Beanstalk Python app and I am trying to install Sentry on it so we can self-host it.

I've tried creating a requirements.txt that includes `sentry==7.5.4` as well as all of Sentry's requirements. However I get the following error when I deploy:

```
[Fri Jun 19 05:28:02.402590 2015] [:error] [pid 494] [client 127.0.0.1:44636] Target WSGI script not found or unable to stat: /opt/python/current/app/src
```

Has anyone been able to get Sentry working on AWS? If so, any pointers would be super helpful.

Thanks

**Comment by dcramer** [comment]
You should ask on the mailing list (or other places) as the issue tracker isn't the place for general discussion.
