### ISSUE TITLE
Add ability to manually merge aggregated groups

### ISSUE THREAD

**Issue by jpadvo** [getsentry/sentry#1566]
Sometimes the same error shows up aggregated into two different groups. I know about sending checksums, enabling source mapping, etc. But without that stuff in place, and maybe even with it, It would be really great to be able to manually merge errors that are obviously the same thing, but showing up in different places.

Cheers!

**Comment by dcramer** [comment]
This exists in the API is will be available when we release the new frontend

**Comment by seanlinsley** [comment]
That's great to hear @dcramer 🎉
