### ISSUE TITLE
Not able to logout if sentry running on https

### ISSUE THREAD

**Issue by sunil-jhamnani** [getsentry/sentry#15669]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I am trying to logout from sentry UI using the Root URL https://sentry.abcinfo.com/ but in the network tab it always throwing 501
Request data
```
Request URL: https://sentry.abcinfo.com/api/0/auth/
Request Method: DELETE
Status Code: 501 
Remote Address: 104.89.113.127:443
Referrer Policy: no-referrer-when-downgrade

```
Response data
```
Unsupported Request
DELETE to http://sentry.abcinfo.com/api/0/auth/ not supported.
Reference #8.3c01c045.1574177316.d1a763d
```
I don't understand why in response the url is on http not https

If I perform the same task on a domain name which is not secured, it works.

### More information: 

- env variable is set SENTRY_USE_SSL=1
- nginx.conf
```
set_real_ip_from 127.0.0.1;
set_real_ip_from 10.0.0.0/24;
real_ip_header X-Forwarded-For;
real_ip_recursive on;

server {
  listen 80 default_server;
  listen 443;
  server_name sentry.abcinfo.com;

  proxy_set_header   Host                 $http_host;
  proxy_set_header   X-Forwarded-Proto    $scheme;
  proxy_set_header   X-Forwarded-For      $remote_addr;
  proxy_redirect     off;

# keepalive + raven.js is a disaster
  keepalive_timeout 0;

# use very aggressive timeouts
  # proxy_read_timeout 15s;
  # proxy_send_timeout 15s;
  # send_timeout 15s;
  # resolver_timeout 15s;
  # client_body_timeout 15s;

# buffer larger messages
  client_max_body_size 5m;
  client_body_buffer_size 100k;

  location / {
    proxy_pass        http://localhost:9000;
    proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    break;

    # add_header Strict-Transport-Security "max-age=31536000";
  }
}

```

I am not understanding where did I went wrong

**Comment by BYK** [comment]
I think you need to fix your `system.url-prefix` setting to be `https` instead of `http`.

**Comment by sunil-jhamnani** [comment]
@BYK 
I changed the url-prefix and still the issue is there. One more things I can see it I am not getting any entry in the docker logs for sentry web when I logout.

**Comment by BYK** [comment]
@sunil-jhamnani let's keep the conversation over at [the forums](https://forum.sentry.io/c/on-premise) as the issue board is for Sentry core code-related issues. This one looks like a config issue on your end. Since you don't see the logout request on Sentry logs, it means this issue happens at Nginx level. This might be your issue: https://stackoverflow.com/a/47489932/90297
