### ISSUE TITLE
IndexError: list index out of range when parsing source map.

### ISSUE THREAD

**Issue by wfortin** [getsentry/sentry#1569]
I'm trying to enable source maps in sentry but we are experiencing an issue on the sentry server when parsing the source map. Source map is pretty big (512 KB)

The server log:
```
IndexError: list index out of range
(1 additional frame(s) were not displayed)
...
  File "sentry/lang/javascript/plugin.py", line 15, in preprocess_event
    return processor.process(data)
  File "sentry/lang/javascript/processor.py", line 422, in process
    self.populate_source_cache(project, frames, release)
  File "sentry/lang/javascript/processor.py", line 578, in populate_source_cache
    release=release,
  File "sentry/lang/javascript/processor.py", line 315, in fetch_sourcemap
    return sourcemap_to_index(body)
  File "sentry/lang/javascript/sourcemaps.py", line 132, in sourcemap_to_index
    if smap['sourcesContent'][idx]:
```

We are using a docker sentry v7.5.4  https://registry.hub.docker.com/u/slafs/sentry/

Our source map can be viewed here:
https://gist.github.com/wfortin/b9d68ab27bc36d8dadc0
The related javascript file:
https://gist.github.com/wfortin/a3379af90821f9aa8221

Thank you for your help

**Comment by mattrobenolt** [comment]
Looks like your sourcemap is bad. Can you run it through sourcemaps.io?

Also to be clear, we don't support running Sentry in docker or that image.

**Comment by dcramer** [comment]
Going to close this but if your sourcemap works on sourcemaps.io (or the validator is wrong) feel free to reopen.

**Comment by wfortin** [comment]
Turns out the sourceMap was invalid because of the `sourceContent: []` attribute.

Passing `includeContent: false` to gulp-sourcemaps fixed the problem. 

Might want to add a check for an empty sourceContent and add a clear message to this exception. Thanks for the great product !
