### ISSUE TITLE
Slack Global integration Rate limit

### ISSUE THREAD

**Issue by snoopckuu** [getsentry/sentry#15696]
## Important Details

How are you running Sentry?

* [X] On-Premise docker [Version getsentry/sentry:latest as of 20-11-2019]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

During alert rule setup for Slack global integration plugin using private or public channel error occures with the following message: The slack resource "#channel-name" does not exist or has not been granted access in the xxxx Slack workspace.

Here is the error that we can see in the logs: 

sentry.integrations.slack: rule.slack.channels_list_failed (error=u'ratelimited')

This happens every time we save alert rules settings even if we wait for a day after previous error rate limit to eliminate any rate limit possibility.

## Steps to Reproduce

Integration broke after upgrade from 9.1.2 to latest and migrating from WST integration to bot integration. New slack application has been create according to guidelines.

**Comment by BYK** [comment]
On Slack's API docs it says the rate limit is around 20/min: https://api.slack.com/docs/rate-limits#tier_t2

Can you share more logs to see why we'd be hitting this limit?

**Comment by BYK** [comment]
Also, would it be the case that you have _a lot_ of Slack channels? Like more than a few thousands?

**Comment by snoopckuu** [comment]
@BYK we have about 100 channels. That's all I can see in the logs. 

How I can enable additional debug log?

**Comment by BYK** [comment]
@snoopckuu - that's interesting. I think the API counts all channels ever created so the actual number may be higher. You may wanna hit that API endpoint yourself and see what it returns here: https://api.slack.com/methods/channels.list/test

For additional logging, https://docs.sentry.io/server/config/#logging may help you.

**Comment by snoopckuu** [comment]
```
15:57:13 [DEBUG] sentry: Using legacy key: sentry:latest_version
11/21/2019 6:57:15 PM Traceback (most recent call last):
11/21/2019 6:57:15 PM File "/usr/local/lib/python2.7/site-packages/sentry/options/manager.py", line 95, in lookup_key
11/21/2019 6:57:15 PM return self.registry[key]
11/21/2019 6:57:15 PM KeyError: 'sentry:latest_version'
11/21/2019 6:57:15 PM 15:57:15 [DEBUG] sentry: Using legacy key: sentry:latest_version
11/21/2019 6:57:15 PM Traceback (most recent call last):
11/21/2019 6:57:15 PM File "/usr/local/lib/python2.7/site-packages/sentry/options/manager.py", line 95, in lookup_key
11/21/2019 6:57:15 PM return self.registry[key]
11/21/2019 6:57:15 PM KeyError: 'sentry:latest_version'
11/21/2019 6:57:15 PM 15:57:15 [DEBUG] sentry: Using legacy key: sentry:latest_version
11/21/2019 6:57:21 PM 15:57:21 [INFO] sentry.integrations.slack: rule.slack.channels_list_failed (error=u'ratelimited')
```

This is the full log. we have about 160 channels including archived. 

Integration worked with WST on 9.1.2

**Comment by snoopckuu** [comment]
@BYK Is there anything else I can do to help with the resolution?

**Comment by snoopckuu** [comment]
@BYK just found that rate limit happens only for private channels despite adding Slack App to the channel. Works with public channels.

**Comment by otsuka-kentaro** [comment]
Facing same issue on me.

**Comment by snoopckuu** [comment]
@BYK just to give you an update that this is no longer relevant and fixed in master branch.

**Comment by BYK** [comment]
@snoopckuu we've been working on improving our Slack integration. Thanks a lot for the feedback! /cc @scefali @manuzope
