### ISSUE TITLE
Add avatar to user by sending them with user_context

### ISSUE THREAD

**Issue by descl** [getsentry/sentry#1570]
Hi,
when i throw a raven error i'm sending informations in the user_context object (email,login,id...)

I have also the url of the user avatar. How to send this to sentry AND to show the avatar?
I saw that yet it's based on gravatar, but i would love to send directly my avatar urls.
any idea? Thanks for this awesome tool!

**Comment by dcramer** [comment]
I think this could make sense (maybe something like avatarUrl?)

**Comment by mattrobenolt** [comment]
If we did this, we wouldn't want to embed the image directly sentry page. We'd need to have an image proxy built into Sentry to wrap the user content, since embedding random images like that could be a security issue. Violating CSP, tracking users, cookies, etc. We'd want to mask all of that, and there aren't any plans of adding anything like that into Sentry yet, but I don't see it out of the question, since it could be leveraged elsewhere, like, in comments.

**Comment by romanonthego** [comment]
maybe - at a very least - gravatar support as default?

**Comment by carlosen14** [comment]
any new? i was going to open a new issue.. i was thinking on something to search the user id on ours users DB using a service.. to get the user avatar URL..

**Comment by NuckChorris** [comment]
Sentry should probably either remove the avatar circle or let us pass something in (you can use Github's Camo server to proxy!)

**Comment by dob9601** [comment]
+1

**Comment by fzyzcjy** [comment]
Hi is there any updates here...?

**Comment by eerison** [comment]
any news?

**Comment by hubertdeng123** [comment]
i don't think there's been any progress on this, but I'll see if issues team has more say on this.

**Comment by braindigitalis** [comment]
would it be possible for the api to allow upload of an image as base64 image blob? This way you dont need a proxy, would just need to store them de-duplicated on the filesystem.
For my use case, i'd want to optionally put discord avatars there (if the user opts in). These would be provided either via url or via direct upload, API permitting.

**Comment by mrduncan** [comment]
Closing this for now as it's not something on our near-term roadmap. We'll keep it in mind in future iterations however.
