### ISSUE TITLE
Suggestion: allow searching for linked Asana task by url

### ISSUE THREAD

**Issue by PeterJCLaw** [getsentry/sentry#15715]
When linking a Sentry issue to an existing Asana task it would be great if it was possible to search for that task by pasting the url into the search box. This is mostly because Asana makes it easy to copy the url to a task, though also because I'd typically search for the task in Asana in order to find what it was called anyway, so being able to either copy/paste the url from the address bar or click the button in Asana to copy the tasks' url to my clipboard and past that would be easier than copy/pasting the title.

**Comment by BYK** [comment]
This is pretty hard to implement with our current search system and it is unlikely to be attended to any time soon so closing the issue.
