### ISSUE TITLE
Datadog Integration

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#15711]
### Metrics

- org-wide stats: {rejected, filtered, accepted, received} events
- project stats: servers, browsers, operating systems, releases, environments, transactions
- everything contains a project tag
- tag-based events are just "events"

### Events

- replace webhook with an explicit "Datadog Webhook" configuration value
  - alternatively switch to using API to avoid multiple configuration endpoints

**Comment by BYK** [comment]
This is now a thing: https://docs.sentry.io/product/integrations/#notification--incidents
