### ISSUE TITLE
[JIRA] Feature Request: Filtering issues before creating JIRA ticket

### ISSUE THREAD

**Issue by YashishDua** [getsentry/sentry#15712]
Exceptions from different environments like beta, stage or production are sent to Sentry. If automatic JIRA ticket creation is enabled in the JIRA integration, all issues from all environments are raised to tickets which makes unnecessary noisy JIRA ticket dashboard.

This is a feature request to incorporate some sort of filtering of issues before sending them to JIRA when automatic ticket creation is enabled.

**Comment by BYK** [comment]
I think these can all be done via [metric alerts](https://docs.sentry.io/product/sentry-basics/guides/alert-notifications/metric-alerts/) and [webhooks](https://docs.sentry.io/product/integrations/integration-platform/webhooks/) so closing as I don't think this will ever be attended to by the Sentry team.

If the combination of the above two does not cut it for you and you are willing to roll up your sleeves, we are open to PRs.
