### ISSUE TITLE
feature request: fullstory plugin

### ISSUE THREAD

**Issue by mkj28** [getsentry/sentry#15723]
It would be _amazing_ to have a Sentry plugin that queries [fullstory API](https://help.fullstory.com/develop-rest/137382-rest-api-retrieving-a-list-of-sessions-for-a-given-user-after-the-fact) and adds a link in the Sentry UI that takes you directly to the fullstory session that triggered the Sentry - maybe couple seconds before the event fired

**Comment by grv231** [comment]
Just confirming if fullstory plugin is a possibility in the near future :)

**Comment by buremba** [comment]
We use the following snippet and it just works:
```
Sentry.configureScope(scope => {
        scope.addEventProcessor(async (event) => {
          if(event.extra == null) {
            event.extra = {}
          }
          event.extra.sessionURL = FS.getCurrentSessionURL(true)
          return event
        })
      })
```

**Comment by scefali** [comment]
@mkj28 @bcmcq  @devdazed @grv231 @buremba 

Hey guys, in fact, there is a Sentry-Fullstory integration as of a few weeks ago! Check it out here: https://www.npmjs.com/package/@sentry/fullstory

At the core of it, it works pretty much how @buremba's code snippet works. But there is actually additional functionality of linking to the Sentry error from FullStory. Please don't hesitate to reach out if you have any questions (preferably here: https://github.com/getsentry/sentry-fullstory/issues)

**Comment by mkj28** [comment]
WOOOT!!! WOOOT!!!

**Comment by grv231** [comment]
Nice, will check it out today itself. Forgot about this that I had asked a question here :)

**Comment by bcmcq** [comment]
Awesome, thanks!
