### ISSUE TITLE
Only supports a single deploy environment in Heroku plugin

### ISSUE THREAD

**Issue by cancan101** [getsentry/sentry#15722]
Reposting from https://github.com/getsentry/sentry-heroku/issues/1:
>We use Heroku for both a staging and production environment. I am trying to enable release tracking for the staging environment, but it looks like the Heroku integration only supports a single "Deploy Environment". Is that correct? Or is there a different way to configure deploy tracking for our staging environment?

**Comment by ORBAT** [comment]
Are there any plans to fix this?

**Comment by TaylorFCM** [comment]
Following this as my organization has development, staging, and production apps all within one pipeline.

**Comment by jnelken** [comment]
I believe a good workaround is to have separate projects for each environment, and then setup a deployhook / Heroku integration for each project (you cannot set up Heroku integrations at the organization level regardless). I hope that helps. Unfortunately for me, I can't seem to get one deployhook setup correctly. I get this error after every deploy, and see nothing in my heroku logs either.
```
Last notification error: error posting to https://sentry.io/api/hooks/release/heroku/.../..., please check settings.
```

**Comment by sampsonbryce** [comment]
Heres a workaround im using https://gist.github.com/sampsonbryce/da5587e2464defb64bbddb063e2f2322

It uses the heroku release phase scripts to do the sentry release manually so we can still take advantage of releases with multiple environments.

**Comment by iamrajjoshi** [comment]
This seems to be a stale issue, so closing for now.
Sentry is deprecating plugins so unfortunately we don't have the bandwidth to address the request, but there seems to be a workaround posted above.
