### ISSUE TITLE
[JIRA] Allow to filter by the ones without jira ticket assigned

### ISSUE THREAD

**Issue by MaicolBen** [getsentry/sentry#15725]
It'd be great to filter by sentry issues which don't have a ticket in jira linked, so it's easy to triage them.

**Comment by feyyazesat** [comment]
Would love to see such feature.

**Comment by josimar-silva** [comment]
This would be very helpfull.

**Comment by rhaussmann** [comment]
Thanks for all the work on this integration. It is saving me a ton of time. I wanted to voice a request for this feature as well. I just noticed the JIRA tag in gray under the title this morning. That's been helpful!

**Comment by scottapow** [comment]
I see the tag too but am not sure how to build a search to target issues with(out) linked JIRA tickets.

**Comment by hackel** [comment]
Dupe of #8338.  This is a critical issue for those of us who do not assign issues within Sentry.  I would really like to see this included in the "Needs Triage" filter.  A filter like this has got to be trivial to implement, right?

**Comment by saifelse** [comment]
I put up a PR for this: #21593. It was pretty easy to pattern match off of the assigned filter!

**Comment by BYK** [comment]
Duplicate of #8338
