### ISSUE TITLE
[GitLab] Show repo scope on linked issues creation

### ISSUE THREAD

**Issue by carlosen14** [getsentry/sentry#15726]
When showing the Linked Issues list, it would be better to see the scope to differentiate (and at least know) what repo scope we are aiming.

I Had to add 3 integrations with Gitlab, 1 for root repos, other 2 because they are in a subgroup.

## Here is showing a list with the same name. 

![image](https://user-images.githubusercontent.com/9368632/60676317-3a06ce00-9e44-11e9-9bc2-a7077683463c.png)

## But the scope group name and subgroup is showing the info i would like to see

![Untitled](https://user-images.githubusercontent.com/9368632/60677871-4ee56080-9e48-11e9-8549-c344b6df35e0.png)

## Expected

I would like to see the **groupname/subgroup** instead of **Link Gitlab Issue**

**Comment by manuzope** [comment]
Hey @carlosen14, we've implemented a solution to this problem. Now, you should only see one Gitlab Issue link and then be able to select your specific subgroup! Closing this issue out.

**Comment by carlosen14** [comment]
thanks for the advise @manuzope , on which version is this released? I am working with comunity edition on premise.

**Comment by manuzope** [comment]
Hey @carlosen14, it's available in version 20.11.0 and all versions after that.
