### ISSUE TITLE
Redirect Loop when registering a new account with SENTRY_SINGLE_ORGANIZATION = True

### ISSUE THREAD

**Issue by alfonsolzrg** [getsentry/sentry#1572]
When a new user tries to register on /register, if SENTRY_SINGLE_ORGANIZATION = True, a redirect loops occurs.

After seeing similar reports using createuser command, I found that the code in /web/frontend/accounts does not assign the newly created user to an organization. So after copying this code from management/commands/createuser.py I managed to get it working. Of course, this assumes that there is an organization (which should be there after syncing the database).

```python
if settings.SENTRY_SINGLE_ORGANIZATION:
            org = Organization.objects.all()[0]
            OrganizationMember.objects.create(
                organization=org,
                user=user,
                type=OrganizationMemberType.OWNER,
                has_global_access=user.is_superuser,
            )
```

**Comment by dcramer** [comment]
I'm hoping to tackle this sometime this week as it's a pretty complex/shitty experience for users.

There's a few things we need to resolve:

1. The redirect loop which sends you to "create a new organization" when its disabled
2. A more obvious way to "add new users to an organization" -- right now people do this via a middleware when they generally are using an internal auth mechanism
3. A way to "request access to organization" -- this is farther out
