### ISSUE TITLE
[Jira Server] Automatic Ticket Creation

### ISSUE THREAD

**Issue by philiplb** [getsentry/sentry#15721]
Hi,

in the legacy Jira integration, there was the option to automatically create Jira tickets for new Sentry issues. Would it be possible to bring back this feature?
It should be again configurable by Sentry project (so for example the tickets are created for the correct Jira project).
And maybe this feature could get a bit extended with some kind of threshold: Don't create a Jira ticket on the first event but maybe if that issue happened more than an configurable amount of times.

**Comment by Amy-Lynn** [comment]
Any follow up here?

**Comment by saifelse** [comment]
Relevant forum topic https://forum.sentry.io/t/automatically-create-jira-tickets/5472/6 :

> the best approach is to build an integration that does this. We will never automatically create a Jira ticket out of a Sentry issue (the issues I described are still issues). We’ve talked about making it possible to build via a rules engine - so that you could decide when to create a ticket (vs all the time), but thats not high on our priority list at the moment.
