### ISSUE TITLE
Idea: Label issues with plugin?

### ISSUE THREAD

**Issue by miketheman** [getsentry/sentry#15730]
In order to better sort/slice the open issues in this repo, having a set of labels that can be applied would help filter out the ones I'm particularly interested in - like `clubhouse` vs `asana`

**Comment by miketheman** [comment]
Thanks! This repo appears to have labels applied - specifically "Component: Integrations" - would it make sense to be able to further filter based on the type of integration? There are currently 33 open issues with this label.

**Comment by manuzope** [comment]
Hmmm, when I use the label in search, I usually also add the integration name to the search, if I'm looking for issues on a specific integration (like [this](https://github.com/getsentry/sentry/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22Component%3A+Integrations%22+clubhouse)). It does lead to some false positives but the volume is low enough for that to not be a huge issue. What's your use case?

I think this probably made sense for sentry-plugins but feeling it might be too granular for sentry.

**Comment by BYK** [comment]
Closing as I think @manuzope's answer was conclusive and it did not get any response back.
