### ISSUE TITLE
XMPP plugin

### ISSUE THREAD

**Issue by alexanderadam** [getsentry/sentry#15739]
## Summary

Add a working XMPP plugin.

## Motivation

There was once a working third party plugin ([`chroto/sentry-xmpp`](https://github.com/chroto/sentry-xmpp/issues/1)) but it is non-functional anymore. It probably make sense to have something working. :wink:

**Comment by BYK** [comment]
I think one can write an integration for this now: https://sentry.io/integration-platform/

Closing as I don't think Sentry team will invest in this and we probably won't add new plugins, favoring the new integration platform. //cc @manuzope
