### ISSUE TITLE
New techstack: Minimal installation possibilities

### ISSUE THREAD

**Issue by benzkji** [getsentry/sentry#15747]
I was reading the blog about the future of sentry (v10+) - introducing quite some new and heavy dependencies, for example Kafka, and other, not yet specified.

I was using sentry for monitoring our agency's django sites - with a goal of having a very low level of events reported. So, the question: Are there any plans that would allow running sentry on a Django/Postgres setup only, without a broker (or using a db broker), without Snuba. So, abstracting all the new stuff away? Already now, setting up redis is a pain ;-)

I know, this is kind of an edge case, but many people will have some similar thoughts, I guess?

**Comment by mattrobenolt** [comment]
That's likely not going to be a thing we invest into. The tech stack is fundamental to a lot of our feature sets moving forward, and trying to build less than good alternatives that we don't use ourselves is a maintenance nightmare. And a lot of the stuff we need doesn't even have a reasonable alternative, so we'd be just disabling large swaths of core functionality.

Instead, we're just investing heavily into our Docker setup so you shouldn't have to think about these things and just run the thing that gives you Sentry.
