### ISSUE TITLE
Phabricator plugin: "One or more PHIDs were invalid for ownerPHID"

### ISSUE THREAD

**Issue by agis** [getsentry/sentry#15742]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [x] On-Premise pip (9.1.2)

## Description

_Note: This is a transfer of https://github.com/getsentry/sentry-plugins/issues/466_
 
We're on 9.2.0 (happened on 9.1.0 too) and we've noticed that if an assignee is not set, then the task creation throws an error with the following message.

## Steps to Reproduce

1. Click on "Link Phabricator Issue" in an issue page
2. Fill everything in the form except of the assignee, click "Create Issue"

![image](https://user-images.githubusercontent.com/827224/69316450-89a63480-0c41-11ea-81dd-5fd2fff80e4f.png)

### What you expected to happen

I'd expect the task to be successfully created without an assignee, since Phabricator allows this.

### Possible Solution

N/A

**Comment by BYK** [comment]
@agis looks like we need to omit `ownerPHID` here when `form_data.get('assignee')` returns `None`: https://github.com/getsentry/sentry/blob/15bf21da38a5ee117f6b9406205368844bc116b9/src/sentry_plugins/phabricator/plugin.py#L204

Would you like to take a stab at this?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
