### ISSUE TITLE
sentry server don't generate dsn

### ISSUE THREAD

**Issue by violetmoon027** [getsentry/sentry#15745]
I built my own Sentry server and didn't generate the project's DSN after creating the project.
![issue](https://user-images.githubusercontent.com/21093745/69326384-ad3f9e00-0c86-11ea-8e45-f39972423945.png)

**Comment by violetmoon027** [comment]
docker shell:
`
docker run -d --name redis redis


docker run -d --name postgres -e POSTGRES_PASSWORD=secret -e POSTGRES_USER=sentry postgres


docker run --rm sentry config generate-secret-key
# secret key

docker run -it --rm -e SENTRY_SECRET_KEY="secret key' --link postgres:postgres --link redis:redis sentry upgrade


docker run -d --name my-sentry -p 9000:9000 -e SENTRY_SECRET_KEY="secret key" --link redis:redis --link postgres:postgres sentry
`

**Comment by violetmoon027** [comment]
Operating environment:
 docekr 18.09.2
 sentry: 9.1.0

**Comment by mattrobenolt** [comment]
Looks like you don't have `system.url-prefix` set.
