### ISSUE TITLE
Slack plugin: "Select Assignee..." only lists teams, not users

### ISSUE THREAD

**Issue by agis** [getsentry/sentry#15743]
_Note: this is a transfer of https://github.com/getsentry/sentry-plugins/issues/463#event-2817079839_

# Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [x] On-Premise pip (9.2.0)

## Description

After upgrading our on-premise instance to 9.1.0 from 9.0.0 (and now to 9.2.0) we noticed that on the "Select Assignee.." select box in Slack, only the teams are listed - the users are missing.

From Sentry's web UI, we can normally assign issues to individual users.

## Steps to Reproduce

N/A

### What you expected to happen

I'd expect for the assignee list on Slack to also include users, not just teams.

### Possible Solution

N/A

**Comment by BYK** [comment]
Heya! There's this note here that @wedamija found: https://github.com/getsentry/sentry/blob/d6a26d9bccd77bb09f8d7ccf6a83a159ebc60760/src/sentry/integrations/slack/utils.py#L156

Could it be due to that?

/cc @manuzope

**Comment by agis** [comment]
I don't think so, we're way too far until we hit 100 choices.

**Comment by BYK** [comment]
Closing as the ground for Slack integration has shifted quite a bit. We should not be having these kinds of issues with the new integration available in the recent versions of Sentry.

Please file a new issue if you are having this with Sentry 20.9.0+.
