### ISSUE TITLE
'Lost Password' option not throwing an error for unregistered accounts

### ISSUE THREAD

**Issue by aravind08** [getsentry/sentry#15741]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.2]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

'Lost Password' option not throwing an error for unregistered accounts.

## Steps to Reproduce

1. On the login screen, click on the "Lost Password" option.
2. Enter a random Email address.
3. Shows 'Recover Account' instruction and nothing happens.

Good items to include here include:

https://drive.google.com/file/d/1f9HlBu7pBtu8SqKgwhCMOT_L8Q2DRN3j/view?usp=sharing

### What you expected to happen

Throw an error that the account doesn't exist.

### Possible Solution

Have a check if the account exists.

**Comment by untitaker** [comment]
All password resets I have worked with work that way due to security reasons, to prevent figuring out which accounts exist

**Comment by mattrobenolt** [comment]
Yeah, this is working as intended. Otherwise it leaks information which enables people to more easily brute force accounts. Most services behave this way.
