### ISSUE TITLE
Old bugs from sentry-plugins are closed, not migrated

### ISSUE THREAD

**Issue by rvanlaar** [getsentry/sentry#15746]
### What happened

All bugs in the plugin repository: https://github.com/getsentry/sentry-plugins/
were closed when the repository was archived.

### What you expected to happen

Plugin bugs report should be triaged and imported in this repo.

**Comment by BYK** [comment]
@rvanlaar I've closed the ones that were not active before March 2019 and then read all the rest and chose to migrate the ones that looked like we may act on. If there are any other ones you'd like us to pursue, please link them here and I'll transfer.

**Comment by BYK** [comment]
Closing as we did reopen the ones people chimed in on.
