### ISSUE TITLE
Where is the migration wizard

### ISSUE THREAD

**Issue by humiaozuzu** [getsentry/sentry#1577]
I have upgraded to previous version of 7.6.0 (now at 7.5.4), but didnot find where is the migration wizard

**Comment by dcramer** [comment]
If you're talking about the access group migration, it was removed entirely as of 7.6.0.

**Comment by humiaozuzu** [comment]
@dcramer 
the upgrade guide said `This releases entirely removes Access Groups. If you’re upgrading from an installation that had yet to migrate away from this system you should first upgrade to a previous version, run the migration wizard, and then continue the upgrade.`

After upgrading I also meet with a lot of 401 error. And cannot mark event as resolved

```
[26/Jun/2015 01:55:30] "GET /api/0/organizations/a9f1d0b8ea33/stats/?since=1434678929.848&stat=rejected&group=project HTTP/1.0" 401 59
[26/Jun/2015 01:56:05] "POST /api/a9f1d0b8ea33/lws-prod/group/557/set/resolved/ HTTP/1.0" 302 0
```

**Comment by dcramer** [comment]
The migration wizard would have shown up on the organization home (only if you needed to do it) in previous versions.

Regarding the 401s, take a look at the response body. Seemingly you're not authenticated or somethings misconfigured.

**Comment by humiaozuzu** [comment]
I'm now at 7.5.4 and also the owner of orgs. But didn't see the migration wizard.
![4610ba99-b854-4113-8a95-2d35a6bf1e10](https://cloud.githubusercontent.com/assets/300016/8369315/1c98e8d4-1bea-11e5-80d0-15bdc3177c09.png)

**Comment by dcramer** [comment]
@humiaozuzu that just means you werent using Access Groups. You don't have to worry about anything.

(Alternatively if you upgraded the tables were probably removed so it wouldnt show up anyways)

**Comment by humiaozuzu** [comment]
@dcramer But how can I solve the permission problem? I'm sure I'm logged in and I'm the owner of group.

```
https://sentry.liwushuo.com/api/0/organizations/insysu/stats/?since=1434679699.604&resolution=1h&stat=received
`401 UNAUTHORIZED`
```

**Comment by dcramer** [comment]
Does that project show up in your team list? Try logging out and back in again as well in case it's an issue with cookies.
