### ISSUE TITLE
Is sentry any good for a ResT API ?

### ISSUE THREAD

**Issue by Seluj78** [getsentry/sentry#15785]
First of all, I use sentry for my backoffice and front end (both using python flask) and it's amazing and I love it ! ❤️ 🎉 

I had a question. I have a API that both of those apps connect to and I was wondering if it was usefull to have sentry on my API too ? (python flask too)

Cheers, and thanks for the amazing work !

**Comment by BYK** [comment]
Hi there! Thanks for the nice words and we're glad you are enjoying Sentry 😃 

That said, please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.

**Comment by Seluj78** [comment]
Alright, thanks for the reply ! Have a great day !
