### ISSUE TITLE
Jira Integration: Would love to see linked Sentry issues in Jira sidebar

### ISSUE THREAD

**Issue by feyyazesat** [getsentry/sentry#15837]
There are sometimes slightly different instances of errors pops up or anyhow some sentry logs(more than one) are related to one ticket.

an example view which ZenDesk integration has. The one on the sidebar shows linked tickets.

![image](https://user-images.githubusercontent.com/1338800/69666026-d77ccb80-108b-11ea-8006-92b4d50770dd.png)

**Comment by aceatienza** [comment]
Any word on this? We would love to see this as well.

**Comment by manuzope** [comment]
Hey there, we've implemented an MVP. If you already have the JIRA integration installed, you'll have to go to JIRA and update it:
![Screen Shot 2021-01-06 at 2 16 40 PM](https://user-images.githubusercontent.com/1417849/104048820-bf391480-5198-11eb-9c04-0d2bf61930e3.png). Our main purpose behind doing this was to allow users to triage issues faster based on the recency and magnitude of the error.

Currently, it supports showing details on a single issue. We have adding support for multiple issues linked to a JIRA ticket on our roadmap (if you're so inclined, we'd accept PRs too).

**Comment by manuzope** [comment]
Closing this out given that it has been implemented.
