### ISSUE TITLE
global events aka deploy marker

### ISSUE THREAD

**Issue by phoet** [getsentry/sentry#1583]
i was trying to give my exceptions more context by having some kind of deploy-marker like it's available in newrelic or errbit. is there anything comparable in sentry?

**Comment by dcramer** [comment]
We'll be announcing release tracking soon, which effectively adds global activity items to Sentry. That said, we don't yet render these. Realistically we're aiming for a different solution than what errbit likely provides, as we feel there's better ways to solve the problem.

**Comment by phoet** [comment]
looking forward to this! :shipit:
