### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by ckj** [getsentry/sentry#1586]
### Typeahead/Tokenized search
- [ ] Search should autocomplete as outlined in issue #1240 

### Saved searches
- [x] **[Design Needed]** User should be able to see a list of save searches
- [x] **[Design Needed]** User should be able to save the current search
- [ ] Handle saving current search
      ```
      POST /api/0/:orgId/:projectId/searches/
      query=...&name=...
      ````
- [ ] Render list of save searches
      ```
      GET /api/0/:orgId/:projectId/searches/
      ```
- [ ] Handle deletion of a saved search
      ```
      DELETE /api/0/:orgId/:projectId/searches/:id/
      ```

### Clear Functionality
- [x] Clear icon should clear search filters
- [x] Clear icon should only appear when search box is dirty

### Other

- [x] **Design** Add option to “jump to event by ID" in dropdown helper

**Comment by ckj** [comment]
Added a **Saved Searches** tab to the search dropdown.
![screen shot 2015-07-01 at 12 54 46 pm](https://cloud.githubusercontent.com/assets/30713/8460292/874a49a6-1ff1-11e5-82b1-3fbb974ecb45.png)

**Comment by dcramer** [comment]
One thing to consider is right now we have a name for saved searches. That name is required to be unique.

I think what we might want to do is have the saved searches still allow a name and have the results be like:

[Bold][Name][/Bold]
[small][Query][/small]

Behavior around saving I would imagine be:

- Enter search query
- Click save
- Modal comes up, shows query to confirm, and asks you for a name

When activating a saved search I imagine the save becoming "edit", similar to the above. Alternatively you cant update a saved search and can only remove it. That kind of sucks from the point of view that they should be permalinks.
