### ISSUE TITLE
After upgrading sentry, it's broken, how do i fix it?

### ISSUE THREAD

**Issue by brunis** [getsentry/sentry#15865]
So i run:
docker run -it --rm --link sentry-postgres:postgres --link sentry-redis:redis -e SENTRY_SECRET_KEY='none-of-yo-biashara' sentry upgrade
I restart my containers, sentry is now broken. I try bash'ing into the web container to look for logs, but i can't find anything. What do i do now?
Was running 8.22, no idea what it upgraded to, but it ran a lot of migrations.

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.

Also, we'd need a lot more details around your upgrade operation to provide any useful help or tips.
