### ISSUE TITLE
Crash Report is not showing 

### ISSUE THREAD

**Issue by nagaraju85** [getsentry/sentry#15863]
I was added the crash anylitic tool my sample application. then I was crashing the application.
by the time application is crashing but I'm  not getting any crash report to Sentry Dashbaord. I fallowed https://docs.sentry.io/clients/cocoa/ to install,  
when I was sent event message with this code 

>         let event = Event(level: .debug)
>         event.message = "Test Message"
>         Client.shared?.send(event: event) { (error) in
>             // Optional callback after event has been sent
>         }

 it was showing like this 
![Screen Shot 2019-11-28 at 10 38 32 AM](https://user-images.githubusercontent.com/25569254/69778750-8247d380-11cb-11ea-823a-ee91ce1ba024.png), when I try to crash the Application 
with this code
>  let foo: String? = nil
>  print("\(foo!)") // app crash

After application crash i'm not getting any crash report to my Dashboard. Dashbaord showing empty.How can get crash results in Dash board.

**Comment by BYK** [comment]
Can you please follow the issue template and share which version of Sentry are you using: sentry.io or on-premise? If it is on-premise then which version is it (9.1? 10? something else?) and how did you install and configure it?

**Comment by nagaraju85** [comment]
Hi Thanks your for reply am using trail version of sentry , I need to take the product if every thing works properly. I fallowed this link to install https://docs.sentry.io/clients/cocoa/

**Comment by BYK** [comment]
I've opened a support ticket on behalf of you (ticket 27213) since you are using sentry.io.

Closing this GitHub issue in favor of the support ticket.
