### ISSUE TITLE
Enhance SAML2: support HTTP-POST binding for idp SingleSignOnService

### ISSUE THREAD

**Issue by ywmail** [getsentry/sentry#15876]
## Summary

Our idp only take POST request for SAML Request, but python3-saml used by Sentry only support HTTP-POST for SSO Service. see:
https://github.com/onelogin/python-saml/issues/146

## Motivation

Why should this be worked on? What problems or use cases does it solve or
improve?

## Additional Context

Any other context or screenshots or API request payload/responses that you
pertain to the feature.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
