### ISSUE TITLE
Can not get data from API

### ISSUE THREAD

**Issue by kevinyan** [getsentry/sentry#15881]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [x] Other [briefly describe your environment]
    * I installed sentry 9.1.2 through [K8S's helm](https://github.com/helm/charts/tree/master/stable/sentry)

## Description

I can't get data I expected from API

## Steps to Reproduce

1. I installed sentry 9.1.2 through K8S's helm
2. I want to get the error information I collected through the API , like : `/api/0/projects/feed/topicpage/issues/`
3. bug I got a 404 response  with message : `{"detail": "The requested resource does not exist"}`

![image](https://user-images.githubusercontent.com/2274844/69937692-63707680-1516-11ea-9a61-b7b6e25b62a0.png)

### What you expected to happen
I want to get  issues of My project . Here is an example using the official API

![image](https://user-images.githubusercontent.com/2274844/69938475-69675700-1518-11ea-929d-6476fd7cc0a3.png)

**Comment by BYK** [comment]
Are you sure your organization name and project slug are correct?

**Comment by kevinyan** [comment]
> Are you sure your organization name and project slug are correct?


Absolutely sure ， I visited the official website sentry.io the same way


![image](https://user-images.githubusercontent.com/2274844/70120845-68fdc600-16a8-11ea-96fc-0849a6439250.png)

**Comment by BYK** [comment]
>I visited the official website sentry.io the same way

That's the thing, is your org name and project slug exactly the same across sentry.io and your local installation??

**Comment by kevinyan** [comment]
> > I visited the official website sentry.io the same way
> 
> That's the thing, is your org name and project slug exactly the same across sentry.io and your local installation??

Thank you very much for your reminding. The problem has been solved.
I compared the two systems again.  As shown in the figure  , instead of using 'feed' (project id), I should use 'sentry' (Organization ID) in the upper left corner
