### ISSUE TITLE
New issues after a release tagged as resolved when they are not

### ISSUE THREAD

**Issue by isiuiki** [getsentry/sentry#15883]
Hi,

We are using Sentry with the releases, but we are experiencing a strange behavior with the resolved in next release feature. After deployment, if the issues that marked as next release repeat, they tagged as resolved when they are not.

For example: 
![image](https://user-images.githubusercontent.com/10518763/69964079-af291d00-1522-11ea-9cbc-3fe5b3f6237c.png)

This issue marked as resolved in the next release and deployed to the production 2 days ago. The error triggered again an hour ago, but instead of creating a new issue it tagged as resolved and the number of the events count increased.

Is this an expected behavior or something's wrong in our end?

Also, found someone else having the same problem: https://forum.sentry.io/t/resolved-issue-event-count-keeps-going-up-instead-of-new-issue-getting-created/8083

**Comment by BYK** [comment]
The first thing comes to my mind is creating and setting the releases properly. Can you share your SDK integration code for investigation? I'm assuming you've already followed this guide for releases: https://docs.sentry.io/workflow/releases/?platform=browser#configure-sdk

**Comment by isiuiki** [comment]
**Package + Version**
raven.js 3.20.0

```
<script src="https://cdn.ravenjs.com/3.20.0/raven.min.js" crossorigin="anonymous"></script>
  Raven.config("{{ config('env.SENTRY_DSN_PUBLIC') }}").install();
```

config file:
```
<?php
return array(
    'dsn' => env('SENTRY_DSN'),

    // capture release as git sha
    'release' => trim(exec('git log --pretty="%h" -n1 HEAD')),

    // Capture bindings on SQL queries
    'breadcrumbs.sql_bindings' => false,
);

```

**Comment by BYK** [comment]
@isiuiki - seems like you are not passing release information to the SDK which would explain the issue you are seeing. Can you follow the guide I linked in my previous comment and see if this fixes the issue?

**Comment by isiuiki** [comment]
The issue is resolved after adding the release information, thanks.
