### ISSUE TITLE
Extra single quotes in Python dictionaries

### ISSUE THREAD

**Issue by anoadragon453** [getsentry/sentry#15912]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.1]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Sentry seems to insert single-quotes inside of python dict strings in expand-blocks:

![image](https://user-images.githubusercontent.com/1342360/70066340-73568c00-15e4-11ea-8f22-e7b34244364b.png)

This *looks* like the code is accidentally double-quoting strings, but actually if we look at another variable (which is the result of `signatures = json_object["signatures"]`), the actual data is perfectly fine:

![image](https://user-images.githubusercontent.com/1342360/70066363-80737b00-15e4-11ea-9eac-215bb0eb8c82.png)

This seems to only happen in expandable blocks (those I have to click `[+]` to open). Another example:

![image](https://user-images.githubusercontent.com/1342360/70066291-5752ea80-15e4-11ea-96f4-5f2b15fa4dc0.png)

I'm also seeing this in Sentry's JSON output:

![image](https://user-images.githubusercontent.com/1342360/70066695-04c5fe00-15e5-11ea-8110-3a59a8fb2ccf.png)

so many quotes.

## Steps to Reproduce

1. Have a nested dict with `str` values in python that sentry pulls out and displays for some reason
2. See that the `str` objects are double-quoted when the strings themselves aren't.

### What you expected to happen

Strings should not be displayed double-quoted.

This caused me to go on a wild goose-chase for two hours through the codebase looking for posible places where there might be strings getting quoted twice :')

**Comment by untitaker** [comment]
Hi, do you see this in additional data or local frame variables?

**Comment by michaelkaye** [comment]
> Hi, do you see this in additional data or local frame variables?

They're in the local frame variables as part of the "Exception" section, not in the "Additional Data" section.

**Comment by untitaker** [comment]
Could you try this on sentry.io? I think this has been fixed quite a while ago in master. We're working on a release :)

**Comment by anoadragon453** [comment]
Mm, I don't really see an easy way to test with sentry.io. Probably a separate bug but:

```
>>> import sentry_sdk
>>> sentry_sdk.init("https://da70c134669c41838a9d4859ff0c55f3@sentry.io/1844711")
<sentry_sdk.hub._InitGuard object at 0x7f04bf71cc90>
>>> division_by_zero = 1 / 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
>>>
```

doesn't get picked up by the onboarding page. I'll wait for a release to test (unless someone else can test more easily).

**Comment by untitaker** [comment]
Try that code in a python file. The exception is not picked up if it
happens in a repl

**Comment by BYK** [comment]
@anoadragon453 you can try the nightly releases from latest master via https://github.com/getsentry/onpremise

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
