### ISSUE TITLE
Custom Login Form (Message/Logo)

### ISSUE THREAD

**Issue by mwcz** [getsentry/sentry#1591]
I'm rolling out Sentry inside my company and I'd like to add some brief instructions to the login page.

For a temp fix, I edited `sentry/templates/sentry/login.html` inside my virtualenv, but that'll quickly become a nightmare going forward.  Is there a built-in way to add such a message?

Thanks!

**Comment by mitsuhiko** [comment]
Not currently possible but something definitely on the radar.

**Comment by mwcz** [comment]
Cool!  Perhaps a `TEMPLATE_OVERRIDES_DIR` param in sentry.conf.py could point to a directory where custom templates could be placed to override Sentry's stock templates.  That would allow for maximum flexibility (not always a good thing).  Or, much simpler, `SENTRY_LOGIN_MESSAGE`.  Just thinking out loud.

**Comment by mitsuhiko** [comment]
Given that the redesign branch no longer uses templates (or we hope at one point that's the case) we probably might just embed a custom HTML message somewhere.

**Comment by dcramer** [comment]
What kind of instructions are these?

In generally it's very unlikely we'll support overriding anything on the general login page. SSO backends can specify their own views and that is about as far as we're going to allow customization at this time.

**Comment by mwcz** [comment]
I'm not sure what instructions you're referring to.

SSO backends can specify their own views, sure, but in larger companies, the person/team deploying Sentry likely doesn't have control of the SSO view.  I'm just looking to add a short "What is this service and who owns it?" message.

I can make do with my own hacky solution though.  No problem.

**Comment by dcramer** [comment]
We could add box that amounts to support (i.e. contact this email if you have problems with Sentry).

You wont be able to override templates in the new version though as it's all React components.

**Comment by mwcz** [comment]
Awesome!  All sounds excellent to me.  Sorry I misunderstood your question about the instructions.  My bad. :)
