### ISSUE TITLE
Android Integration error

### ISSUE THREAD

**Issue by SG-K** [getsentry/sentry#15927]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Ambiguous method overloading for method java.io.File#<init>.
  Cannot resolve which method to invoke for [null, class java.lang.String] due to overlapping prototypes between:
  	[class java.lang.String, class java.lang.String]
  	[class java.io.File, class java.lang.String]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 2s
Ambiguous method overloading for method java.io.File#<init>.
Cannot resolve which method to invoke for [null, class java.lang.String] due to overlapping prototypes between:
	[class java.lang.String, class java.lang.String]
	[class java.io.File, class java.lang.String]

**Comment by xkun1** [comment]
你好这个问题怎么解决？

**Comment by marandaneto** [comment]
hey @SG-K have you tried the `sentry-android` v2? give it a try.

https://github.com/getsentry/sentry-android/releases

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
