### ISSUE TITLE
Notes disappear after a maximum of 7

### ISSUE THREAD

**Issue by remarkablyrestrained** [getsentry/sentry#1598]
After an apparent limit of 7 notes is reached, the first note is no longer shown. I'm not sure if it's really being deleted from the database, or actually gone.

This has lead to many headaches, as the notes are often a place where part of the debugging over longer time-periods takes place. An to head-scratching and self-doubt as well ("didn't I document this previously?!")

I cannot find any documentation on it either, so I'm classifying it as a bug. Feel free to point me to the relevant configuration-setting if I've missed that.

Observed on Sentry 6.4.4

**Comment by dcramer** [comment]
Of note this will be addressed/fixed in the upcoming redesign, though we likely still need to implement pagination.

I'm going to close this due to the above.
