### ISSUE TITLE
jQuery not defined

### ISSUE THREAD

**Issue by edusperoni** [getsentry/sentry#1599]
Hi!

I upgraded from sentry 7.5.5 to 7.6.1 and it's now giving errors about jquery not being defined. Eveyrthing else seems to be working (it's still collecting data).

Chrome log:
```
vendor-jquery.min.js:1 Uncaught ReferenceError: jQuery is not defined
vendor-bootstrap.min.js:1 Uncaught TypeError: t is not a function
vendor-misc.min.js:2 Uncaught TypeError: Cannot read property 'extend' of undefined
app.min.js:1 Uncaught ReferenceError: jQuery is not defined
app-legacy.min.js:1 Uncaught ReferenceError: jQuery is not defined
vendor-misc.min.js:1 Deprecation warning: moment.lang is deprecated. Use moment.locale instead.
```

Nothing on the worker and web logs show any indication of an error.

Any clues?

**Comment by edusperoni** [comment]
Also, if I manually add a jquery include, I get

```
app.min.js:1 Uncaught TypeError: s.cookie is not a function
```

**Comment by edusperoni** [comment]
More debugging. Copying the old lib/python2.7/site-packages/sentry/static/sentry to the new installation fixes it (probably missing some stuff), but it seems the problem lies in one of those scripts

**Comment by dcramer** [comment]
Looking into this. It's possible something is wrong w/ the sdist code. I'm pulling in some changes we have in a branch that should refine this. I will test to ensure a new package is generated correctly, and push out an updated release.

**Comment by dcramer** [comment]
I've pushed up 7.6.2 which includes the new static code. It's still not clear to me why the old stuff broke, but give it a shot now.
