### ISSUE TITLE
Email verification fails with 400 Bad Request

### ISSUE THREAD

**Issue by gamefundas** [getsentry/sentry#16015]
How are you running Sentry?
On-Premise docker with LDAP [Version 9.1.2]

Problem:
After a fairly new setup of Sentry on-premise with LDAP I got most things working except few things. Opening separate issues for these as it can be easy to track

1. Verification email breaks with 400 Bad request on the frontend

`/api/0/users/me/emails/confirm/:1 Failed to load resource: the server responded with a status of 400 (BAD REQUEST)`

- (anonymous) | @ | index.js:4654
- -- | -- | --
-   | send | @ | jquery.js:8630
-   | ajax | @ | jquery.js:8166
-   | value | @ | api.jsx:201
-   | (anonymous) | @ | api.jsx:255
-   | value | @ | api.jsx:254
-   | (anonymous) | @ | accountEmails.jsx:117
-   | pr | @ | react-dom.production.min.js:125
-   | rr | @ | react-dom.production.min.js:125
-   | ui | @ | react-dom.production.min.js:214
-   | ai | @ | react-dom.production.min.js:205
-   | zi | @ | react-dom.production.min.js:204
-   | fi | @ | react-dom.production.min.js:216
-   | Bn | @ | react-dom.production.min.js:85
-   | o | @ | index.js:3917
- 

Originally I thought this might be an issue with my mail host configuration, but noticed that other forms of notifications (test email, weekly email etc) are going through so this is something else. Then I noticed these JS errors in the webpage.

Adding more details

Request Payload:
{"email":"ANemailid@xyz.com"}

Response Payload:
{"detail": "Invalid email", "email": "Invalid email"}

The email address (Mixed case) seems right, exactly what was setup as part of the LDAP email and it appears correct in the database (organization_member) but the response says "Invalid email".

**Comment by BYK** [comment]
It may be a case sensitivity issue on the back end. Will try to look but not sure when we'd have the time. Would you be interested in diving in? https://github.com/getsentry/sentry/blob/95767d455b8004ec4b4c5026d84b64b6348e6d37/src/sentry/api/endpoints/user_emails_confirm.py#L68 would be a good starting point.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
