### ISSUE TITLE
Decode(?) Sentry release name

### ISSUE THREAD

**Issue by maieonbrix** [getsentry/sentry#16012]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I created a release named 2019-11-04/1, when I try to visit the releases url on sentry.io (sentry.io/organizations/perfectstay/releases/2019-11-04%F4/?project=182xxxx) the following error message is displayed : "This release may not be in your selected project: React"

When I inspect the devtools network panel the GET request returned à 404 not found.

I then decided to replace the / with a "@" and now it is working fine.

## Steps to Reproduce

1. Create a release via init with its name  containing a forward slash (/)
2. try to access this ressource via sentry.io

### What you expected to happen
Access the page

### Possible Solution

Maybe check the decoding part server side ? Or just forbid forward slashes for releases names.

By the way, thank you a lot for your time and for this amazing tool. Love you all. I hope i'll be able to contribute some code this year (:

UPDATE : https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/organization_release_details.py

I think it's in this file, never did some python but I'll try to look at it this week

**Comment by leeandher** [comment]
I suspect this a result of creating a release prior to us enforcing some restrictions that were not communicated on the API. If this is still an issue for users I'll be happy to reopen/address it, but for now I've put together a PR to communicate those restrictions [here](https://github.com/getsentry/sentry/pull/81963). We do restrict slashes, and that is not set to change at the moment.
