### ISSUE TITLE
Search in events' breadcrumbs data

### ISSUE THREAD

**Issue by mrmitew** [getsentry/sentry#16017]
## Summary

I would like to be able to find events that contain breadcrumb(s), based on search keywords.

## Motivation

Me and teammates of mine happened to need to search for specific 'events', recorded as breadcrumbs, however, currently that is not possible. Manually searching can be tedious, especially if we are looking into an issue that has thousands of events.

**Comment by BYK** [comment]
Hi @mrmitew - I definitely see how this could be useful but right now it is not possible nor easy to add this feature. Closing as we do not plan to work on this any time soon but if/when we do, you'll definitely hear about it on our blog or newsletter.

Thanks for your suggestion.
