### ISSUE TITLE
GitHub Integration: Possible bug: can't add same repo to two Sentry organizations (via web)

### ISSUE THREAD

**Issue by avargas** [getsentry/sentry#16029]
I somehow setup "my org" and "my org staging" 

(I know, I'll change it to use staging environments and one single project, but this is an old project).

I mapped our repository to our main "my org" and when I tried to add the integration into the new one, the Github Authorization prompts, but because I've already authorized, it sends me to the Github 

![Screenshot](https://user-images.githubusercontent.com/169653/70528169-8ce36080-1b1b-11ea-9fba-b8509e2609b2.png)

![Screenshot](https://user-images.githubusercontent.com/169653/70528176-91a81480-1b1b-11ea-855e-8b3a9bd4fe2a.png)

And so, on this second screen, since I've already authorized Sentry, I can't just hit "continue". 

**So I can't add the same repo to two organization under my account**

PS: Pardon me if there's a different way / or template, to report bugs, I am reporting it this way because it takes me 5 minutes at the most and I'm dealing with prod issues.

**Comment by BYK** [comment]
@avargas please reach out to our [dedicated support](https://sentry.io/contact/support/) for issues with sentry.io. As you can see GitHub issues are not the best place for swift resolutions 🙂
