### ISSUE TITLE
"raven test http://39419cd8d9544ac087714326b0cc90e9:535537e988d644449a793ec112641277@127.0.0.1/2 " is error

### ISSUE THREAD

**Issue by wanghe4096** [getsentry/sentry#1605]
i can not test for python, it is nginx 404 error.

**Comment by mattrobenolt** [comment]
Can you paste the nginx config + the nginx error log?

**Comment by dcramer** [comment]
This is an internal configuration error certainly. You'll need to ensure your proxy is configured per the documentation.
