### ISSUE TITLE
sentry-error-embed dialog z-index issue

### ISSUE THREAD

**Issue by pmstss** [getsentry/sentry#16083]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [X] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

With default z-index values Sentry feedback dialog is below standard Angular Material dialog.

<details>
<summary>Demo</summary>

![image](https://user-images.githubusercontent.com/12969334/70723301-bbbf2980-1d09-11ea-86ec-e73625ab0ef9.png)
</details>

## Steps to Reproduce

1. Follow https://docs.sentry.io/platforms/javascript/angular/ steps
2. Use standard Angular Material dialog component: https://material.angular.io/components/dialog/overview
3. fire any error that will trigger `showReportDialog()`

### What you expected to happen

Sentry dialog should be on top.

### Possible Solution

`.sentry-error-embed-wrapper` z-index is `999`: https://github.com/getsentry/sentry/blob/b907276fe8b0f62aa862f115424c7f8b9b843913/src/sentry/templates/sentry/error-page-embed.html#L9

Angular Material `.cdk-overlay-container` z-index is `1000`: 
https://github.com/angular/components/blob/45d34ad4ff85d36096df5ccef1b1f5658364372d/src/cdk/overlay/_overlay.scss#L4

Solution could be changing `.sentry-error-embed-wrapper` z-index to `1001`.

**Comment by matejminar** [comment]
Hey, we could change it to something like `1000`, but then the other library in the future could need us to set it to `1001` and so on… I wonder, why don’t you just set 
```css
.sentry-error-embed-wrapper {
    z-index: 1000 !important;
}
```
in your global angular stylesheet to fit your usecase?
