### ISSUE TITLE
How i can change the model for sentry? 

### ISSUE THREAD

**Issue by wanghe4096** [getsentry/sentry#1609]
I have added a new field in models/organization, and excute 'sentry upgrade' , but it is not changed

**Comment by dcramer** [comment]
You need to generate a migration via South

**Comment by wanghe4096** [comment]
3q

**Comment by dcramer** [comment]
Please use a more appropriate place for questions such as IRC or the mailing list. Sentry is Built on Django, so your best bet is to start reading there.
