### ISSUE TITLE
Timestamp parsing fails when the microseconds part is longer than 6 digits

### ISSUE THREAD

**Issue by cmlenz** [getsentry/sentry#1610]
I have run into an issue with sentry server 7.6.2 and raven-csharp.

The latter is sending events with a timestamp that looks like this:

    2015-07-15T11:39:37.0341297Z

This is rejected by the server, which logs the following error:

    Discarded invalid value for timestamp: u'2015-07-15T11:39:37.0341297Z'
    Traceback (most recent call last):
      File "/home/sentry/virtualenv/lib/python2.7/site-packages/sentry/../sentry/coreapi.py", line 261, in validate_data
        process_data_timestamp(data)
      File "/home/sentry/virtualenv/lib/python2.7/site-packages/sentry/../sentry/coreapi.py", line 220, in process_data_timestamp
        raise InvalidTimestamp('Invalid value for timestamp: %r' % data['timestamp'])
    InvalidTimestamp: Invalid value for timestamp: u'2015-07-15T11:39:37.0341297Z'

The cause is that the Python `strptime` implementation only supports up to 6 digits for the fraction part:

> %f is an extension to the set of format characters in the C standard (but implemented separately in datetime objects, and therefore always available). When used with the strptime() method, the %f directive accepts from one to six digits and zero pads on the right.
[8.1.7. strftime() and strptime() Behavior](https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior)

I'm not sure whether this is a problem with raven-csharp or the sentry server, but it seems like the server should be more forgiving here.

BTW: Are the events that cause this error message discarded completely, or is Sentry only ignoring the client-supplied timestamp?

**Comment by dcramer** [comment]
They're only discarding the timestamp
