### ISSUE TITLE
Default project in the issues screen

### ISSUE THREAD

**Issue by cehenriques** [getsentry/sentry#16128]
## Summary

It would like to set the default project to be shown on the issues screen or keep my last used settings.

## Motivation

Every time I go to the issues screen I need to manually switch to the project I use the most. I also tried marking this project as a favorite but Sentry still ignores it and list as projects alphabetically.

## Additional Context

n/a

**Comment by joelstein** [comment]
Same.

**Comment by cedrouck** [comment]
Same too

**Comment by BYK** [comment]
This seems to be fixed for me so closing.
