### ISSUE TITLE
Track Message-Id's from sent email

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#1612]
### Problem
We're sending messages with duplicate `Message-Id` headers which is causing some email clients to behave poorly. To be fair, this is completely wrong on our part.

### Solution
Implement a `ParentId` table to track a unique reference of `(reference, email)` so each mail being sent can generate the correct `In-Reply-To/Reference` headers.

**Comment by dcramer** [comment]
More discussion here: https://github.com/getsentry/sentry/commit/3e653b77153f832b2ab8e14f0588e8895addf928#commitcomment-12239891
