### ISSUE TITLE
CSP: treat block-all-mixed-content as a valid directive

### ISSUE THREAD

**Issue by jeremy** [getsentry/sentry#16146]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Submitting a CSP report with the [block-all-mixed-content](https://w3c.github.io/webappsec-mixed-content/#block-all-mixed-content) directive is rejected as invalid with a 400 Bad Request response: `{ "error": "Invalid security report: u'block-all-mixed-content' is not one of […long list…]" }`

## Steps to Reproduce

1. Use a CSP header that blocks mixed content, like `Content-Security-Policy: block-all-mixed-content; report-uri https://sentry.io/api/xxx/security/?sentry_key=xxx`
2. Embed an image with an http src, triggering the mixed content policy.
3. Browser reports to Sentry which rejects the report as invalid:
> "error": "Invalid security report: u'block-all-mixed-content' is not one of ['base-uri', 'child-src', 'connect-src', 'default-src', 'font-src', 'form-action', 'frame-ancestors', 'frame-src', 'img-src', 'manifest-src', 'media-src', 'object-src', 'plugin-types', 'prefetch-src', 'referrer', 'script-src', 'script-src-attr', 'script-src-elem', 'style-src', 'style-src-elem', 'style-src-attr', 'upgrade-insecure-requests', 'worker-src']"

Example of a CSP report that triggers this (sent from Safari, in this case):
```json
{
    "csp-report": {
        "document-uri": "https://example.com/",
        "referrer": "",
        "violated-directive": "block-all-mixed-content",
        "effective-directive": "block-all-mixed-content",
        "original-policy": block-all-mixed-content; report-uri https://sentry.io/api/xxx/security/?sentry_key=xxx",
        "blocked-uri": "http://example.com",
        "status-code": 0
    }
}
```

To reproduce with cURL:
```bash
curl 'https://sentry.io/api/xxx/security/?sentry_key=xxx' \
-XPOST \
-H 'Accept: */*' \
-H 'Content-Type: application/csp-report' \
-H 'Origin: null' \
-H 'Referer: https://example.com/' \
-H 'Cache-Control: max-age=0' \
-H 'Content-Length: 555' \
-H 'Host: sentry.io' \
-H 'Accept-Language: en-us' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1 Safari/605.1.15' \
-H 'Accept-Encoding: gzip, deflate, br' \
-H 'Connection: keep-alive' \
--data-binary $'{"csp-report":{"document-uri":"https://example.com/","referrer":"","violated-directive":"block-all-mixed-content","effective-directive":"block-all-mixed-content","original-policy":"block-all-mixed-content; report-uri https://sentry.io/api/xxx/security/?sentry_key=xxx","blocked-uri":"http://example.com","status-code":0}}'
```
Response:
```json
{"error":"Invalid security report: u'block-all-mixed-content' is not one of ['base-uri', 'child-src', 'connect-src', 'default-src', 'font-src', 'form-action', 'frame-ancestors', 'frame-src', 'img-src', 'manifest-src', 'media-src', 'object-src', 'plugin-types', 'prefetch-src', 'referrer', 'script-src', 'script-src-attr', 'script-src-elem', 'style-src', 'style-src-elem', 'style-src-attr', 'upgrade-insecure-requests', 'worker-src']"}
```

### What you expected to happen

Expect Sentry to treat block-all-mixed-content as a valid directive.

### Possible Solution

1. Treat the `block-all-mixed-content` directive as valid.
2. Accept future unknown directives rather than rejecting as invalid.

**Comment by BYK** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content
>This feature is obsolete. Although it may still work in some browsers, its use is discouraged since it could be removed at any time. Try to avoid using it.
