### ISSUE TITLE
Which port is used to send captured error to Sentry Cloud

### ISSUE THREAD

**Issue by ashah-kaira** [getsentry/sentry#16157]
I have hosted our system on Amazon Lightsail.

Currently, I am not able to get an error email notification nor can I see on sentry.io. Please inform what to do to get both.

Since Amazon has blocked all ports for security reasons, I may need to enable the port. But not sure which port to keep open. Please inform.

**Comment by mattrobenolt** [comment]
It’s just https, so port 443.

**Comment by ashah-kaira** [comment]
Thanks @mattrobenolt for the quick reply.
Actually 443 port is open as we have hosted site (on which we have set up error logging using Sentry) on https. 
But I am not able to get errors on cloud, is there anything I can see on server? Error logs or something to track why it's not able to send errors to the cloud or send an email.

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
