### ISSUE TITLE
404 on Event Link List

### ISSUE THREAD

**Issue by jesusbotella** [getsentry/sentry#1616]
Hi!

I installed sentry on my own server and I have experienced a few issues I resolved, but there's one that I have not been able to solve yet.

When I'm on the event stream page and click the event title, which supposedly would take me to event details, it gives me a 404 error.

The thing is that the url has duplicated parameters. The URL that is linked to the title is: https://testing/sentry/sentry/savelist/updater/group/1/. But it should be https://testing/sentry/savelist/updater/group/1/

That is my 'URL configuration' right now:

    SENTRY_URL_PREFIX = 'https://testing/sentry'  # No trailing slash!
    STATIC_URL = '/sentry/_static/'
    FORCE_SCRIPT_NAME = '/sentry/'

I've looking for how you were getting that link and I found that: 

    permalink = absolute_uri(reverse('sentry-group', args=[
                obj.organization.slug, obj.project.slug, obj.id]))

But I don't know how it could be mistaken, because the reverse gets the url from sentry-group which doesn't have any 'sentry' in there. And then, joins it to the SENTRY_URL_PREFIX without the trailing slash and there's only a 'sentry' slug in there.

Any clue to solve this problem?

**Comment by dcramer** [comment]
You'll need to host sentry on a subdomain as we dont support subpaths currently.
