### ISSUE TITLE
Support Arbitrary Email Addresses

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1617]
A common request that comes up is the ability to create a rule which will notify an arbitrary email address. This address could be an existing user, though it's more likely that it's a mailing list.

To resolve this we need to build a few things:
- Organization-wide email addresses
- Verification of all addresses
- Organizational and personal ownership of addresses (note ownership does not imply singular, it just implies that you have the authorization for that address)

Some flows that seem relevant:
- Organization-wide email lists. This may be accessible via other pages and less directly as it's not a major component. Possibly also a sub-item under settings.
- Secondary email addresses for user (accessible via account settings)
- A rule condition for the mail backend to notify an arbitrary (verified) address

Ideally we'd also build out some simple unsubscribe models for these, though that's a bit more complex beyond a "unverify" step.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
