### ISSUE TITLE
Event frequency rule condition has unmentioned hard-coded rate limit

### ISSUE THREAD

**Issue by AllenJB** [getsentry/sentry#1618]
The event frequency condition has a [hard coded restriction](https://github.com/getsentry/sentry/blob/master/src/sentry/rules/conditions/event_frequency.py#L64) that prevents it from running more frequently than every 30 minutes.

This restriction is not mentioned on the user interface, and so the rule does not trigger as expected.

Documentation should be added to the user interface to mention the restriction.

Ideally the rate limit restriction should be configurable from the user interface.

**Comment by dcramer** [comment]
Refs GH-1400

**Comment by dcramer** [comment]
I'm going to simply close this in favor of #1400 as there's not a great way to document this, and the current behavior isn't ideal
