### ISSUE TITLE
why breakpoint does not work when debug?

### ISSUE THREAD

**Issue by leveryd** [getsentry/sentry#16188]
My ide is Pycharm,debug config is below.

![image](https://user-images.githubusercontent.com/1846319/71190612-e25c0200-22bf-11ea-912d-59bc9e58b79e.png)

i insert a breakpoint,it reaches this breakpoint,but can not stop.
![image](https://user-images.githubusercontent.com/1846319/71190517-b2146380-22bf-11ea-9812-47561c3bdee3.png)

visit http://localhost:8000/api/0/organizations/sentry/recent-searches/?query=&type=0&limit=3
![image](https://user-images.githubusercontent.com/1846319/71190566-c9535100-22bf-11ea-8352-07d6a298132f.png)

**Comment by BYK** [comment]
This is an obscure option and will disable live-reload but you may try `sentry run web --no-uwsgi` as this is due to UWSGI and forked processes. This option is defined here: https://github.com/getsentry/sentry/blob/master/src/sentry/runner/commands/run.py#L84-L92

**Comment by leveryd** [comment]
> This is an obscure option and will disable live-reload but you may try `sentry run web --no-uwsgi` as this is due to UWSGI and forked processes. This option is defined here:
> 
> https://github.com/getsentry/sentry/blob/9774d33134368cbd87445837a6087f1ba5c689aa/src/sentry/runner/commands/run.py#L87-L92

![image](https://user-images.githubusercontent.com/1846319/71368722-a4265180-25e3-11ea-896e-79552ae844fd.png)

what this means?Need i modify code to debug?
![image](https://user-images.githubusercontent.com/1846319/71368851-02ebcb00-25e4-11ea-9bab-96a085031e16.png)

**Comment by BYK** [comment]
Ooops, forgot to mention that you need to set `SENTRY_ENVIRONMENT=development` (the environment variable) when using this command. Sorry.

**Comment by leveryd** [comment]
![image](https://user-images.githubusercontent.com/1846319/71390751-78838580-263c-11ea-8238-0e7e9c6cb73c.png)
the same as above.

Any tutorial help to debug server source code?no findings on "https://docs.sentry.io/development/contribute/environment/"

**Comment by BYK** [comment]
You are right we should have better docs around this. If you update the command to be `run web -b localhost:8000 --no-uwsgi` you should be good.

Thanks for bringing this up!

**Comment by BYK** [comment]
This should help you now: https://develop.sentry.dev/environment/pycharm/#debugging-with-pycharm
