### ISSUE TITLE
Event frequency rule fails to trigger for different events

### ISSUE THREAD

**Issue by AllenJB** [getsentry/sentry#1620]
The event frequency rule fails to trigger multiple times if multiple events come in of different groups.

If I set up the rule to trigger on "More than 1 event in 1 minute", and 2 events of group A and 2 events of group B all occur within 1 minute (within the same project), then I would expect to receive 2 notifications - 1 for each group.

Through some testing I believe this is caused by the following check: https://github.com/getsentry/sentry/blob/master/src/sentry/rules/conditions/event_frequency.py#L50

**Comment by dcramer** [comment]
I believe this behavior works as you expected. At the very least, our tests show it do and I can't see how it wouldn't. The state here is bound to an individual group (from GroupRuleStatus)
