### ISSUE TITLE
How do i receive webhook data？

### ISSUE THREAD

**Issue by wujinbiao94** [getsentry/sentry#16217]
Plugin Information
Name
    WebHooks
Author
    Sentry Team
URL
    github.com/getsentry/sentry
Version
    9.1.2

Callback URLs
http://ip:port/sentry
When I configure a URL, I can receive a request, but i can not receive any data.
Request Args   : [{}]

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
