### ISSUE TITLE
Support GitHub autolink references

### ISSUE THREAD

**Issue by danielcompton** [getsentry/sentry#16221]
<details>
<summary>Details</summary>

</details>

## Summary

GitHub recently announced [custom autolinked references](https://help.github.com/en/github/administering-a-repository/configuring-autolinks-to-reference-external-resources). This lets you configure your GitHub repository to recognise `MYAPP-317` as a reference to a Sentry issue. Once you do that, GitHub will automatically add hyperlinks to commits, PRs, and issues that use the `MYAPP-*` pattern.

## Motivation

Sentry supports [resolving Sentry issues in commits/pull requests](https://docs.sentry.io/workflow/integrations/global-integrations/#resolving-in-commitpull-request). If you include “Fixes MYAPP-317”, Sentry will automatically resolve the issue in the next release that includes that commit.

If clicking MYAPP-317 from GitHub could take me to the Sentry page for that issue.

## Additional Context

To enable custom autolinked references, you need to provide a URL pattern for GitHub to use, e.g.:

![](https://help.github.com/assets/images/help/repository/add-target-url-field.png)

Sentry doesn't currently support a straightforward URL pattern like that, e.g. `MYAPP-317` would refer to `https://sentry.io/organizations/my-co/issues/1324130571/`. There is an [API](https://docs.sentry.io/api/organizations/get-short-id-lookup/) to lookup the short ID, but this would need to be implemented as a redirect. I could imagine something like:

```
https://sentry.io/organizations/my-co/shortids/MYAPP-317/
```

would redirect to

```
https://sentry.io/organizations/my-co/issues/1324130571/
```

The other thing I noticed is that I think **GitHub only supports numerical IDs**, Sentry's hexadecimal IDs that have characters in them may not get picked up by GitHub.

> Under "Target URL", type the link to the external system you want to link to. Make sure to keep <num> as a variable for the reference number.

**Comment by danielcompton** [comment]
After doing a bit more digging I realised that I could use https://sentry.io/organizations/my-co/issues/?query=MYAPP-123 to resolve to https://sentry.io/organizations/my-co/issues/1324130571/. This works pretty well, as long as your Sentry IDs only have numbers in them.

**Comment by BYK** [comment]
Closing this issue due to staleness and for the discovered (and thankfully shared) workaround. Feel free to comment here if you think we should still work on this.
