### ISSUE TITLE
500 when saving a Slack notification task on Alerts

### ISSUE THREAD

**Issue by rbarbaresco** [getsentry/sentry#16236]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I'm trying to edit an existing alert, adding a new task to send a slack notification, but I'm getting a 500 from browser with the response:
```json
{"detail":"Internal Error","errorId":"a5f350a7fa5045aa8a57203c4ab9c477"}
```

## Steps to Reproduce

1. Go to Project Settings
2. Choose Alerts menu
3. Click on Edit Rule
4. on **Take these actions:** section, try to add a new notification for slack.
5. Hit save.

### What you expected to happen

Either a better feedback error explaining the problem or the alert being correctly saved.

**Comment by manuzope** [comment]
Hey @rbarbaresco, thanks for bringing this up. We're looking into it.

**Comment by MeredithAnya** [comment]
> Either a better feedback error explaining the problem or the alert being correctly saved.

@rbarbaresco, the fix is live so this should be the case now!
