### ISSUE TITLE
Raven-JS and Sentry, do they speak the same language ?

### ISSUE THREAD

**Issue by vperron** [getsentry/sentry#1624]
Hello, 

I have big trouble trying to get stack traces, deminification, etc from my raven-JS (1.1.19) client into Sentry (7.4.3).

I think I know already a little about it since I've already pushed a fix for something related last year.

So I had a look at the internals and I'm confused... My raven-js client sends something like: (taken directly from Chrome request inspector)

```json
{
    "culprit": "http://localhost:3336/js/app.js",
    "event_id": "476e4b5ddd8443569250fe5cc8e843a6",
    "exception": {
        "type": "TypeError",
        "value": "Cannot read property 'dada' of undefined"
    },
    "extra": {
        "session:duration": 281
    },
    "logger": "javascript",
    "message": "Cannot read property 'dada' of undefined",
    "platform": "javascript",
    "project": "2",
    "request": {
        "headers": {
            "User-Agent": "Mozilla/5.0 (X11; Linux x86_64)"
        },
        "url": "http://localhost:3336/#/"
    },
    "stacktrace": {
        "frames": [
            {
                "colno": 30,
                "filename": "http://localhost:3336/js/vendor.js",
                "function": "jQuery.Callbacks.fire",
                "in_app": true,
                "lineno": 71784
            },
            {
                "colno": 5,
                "filename": "http://localhost:3336/js/vendor.js",
                "function": "HTMLDocument.<anonymous>",
                "in_app": true,
                "lineno": 30290
            }
        ]
    }
}
```

... so the format for the interfaces is the "simple" one, like it should be https://github.com/getsentry/raven-js/commit/2fe58470e9e964f01c39d28c21f1ee06d7bef974 .

Still, since sentry doesn't decode this probably I took a look and found out that all tests and such are done with this format:

```python
 data = {
            'message': 'hello',
            'platform': 'javascript',
            'sentry.interfaces.Exception': {
                'values': [{
                    'type': 'Error',
                    'stacktrace': {
                        'frames': [
                            {
                                'abs_path': 'http://example.com/foo.js',
                                'filename': 'foo.js',
                                'lineno': 4,
                                'colno': 0,
                            },
                            {
                                'abs_path': 'http://example.com/foo.js',
                                'filename': 'foo.js',
                                'lineno': 1,
                                'colno': 0,
                            },
                        ],
                    },
                }],
            }
        }
```

(cf tests/sentry/lang/javascript/test_plugin.py) 

I tried modifying src/sentry/lang/javascript/processor.py to match the format but now, my py.test -k javascript tests do not pass anymore because of various exotic reasons (frame contexts, etc...)

Can we (together) do something about that ?

**Comment by dcramer** [comment]
At a glance it does look like we're not support generic stacktrace interface expansion.

That said, when theres an exception the normalization code pushes it into the stacktrace there.

**Comment by vperron** [comment]
thanks @dcramer  !!! now THAT was fast.

**Comment by vperron** [comment]
hum when reading your fix, I think there's still a little something that I don't get :) The "data" that you test the processor against, is that  the same data that is sent by raven JS or something that has already been preprocessed ? 

Is there a reference of the Sentry JSON protocol just so I can fix my ideas ? (I didn't find something very clear yet...)

**Comment by dcramer** [comment]
That fix wasn't quite enough.

This is all the internal JSON spec and is not identical to the data you are sending from the client.

The protocol itself is documented here: https://docs.getsentry.com/hosted/clientdev/quickstart/#building-the-json-packet

**Comment by vperron** [comment]
Yeah, that's what I thought. Can I do something to fix it without getting stuck too deeply into weird frame.pre_context issues ? :)

Should this issue stay closed ?

Here's a fix I was trying to implement: https://github.com/vperron/sentry/commit/4ea0c8cb120a3165f0e0b185c64213b69ab621ea
