### ISSUE TITLE
Stats graph after 7.6.2 upgrade is missing data

### ISSUE THREAD

**Issue by mwcz** [getsentry/sentry#1625]
Before upgrading to 7.6.2, I was on 7.5.4.  The stats graph was, let's say, well-populated with 5k-15k errors per hour.  After the upgrade, it looks like this:

![screenshot from 2015-07-23 09 52 09](https://cloud.githubusercontent.com/assets/364615/8852012/cad648ec-3120-11e5-9c70-c1afaa3af07d.png)

The totals below are also incorrect.  Before the upgade, the total was around 1.3 million, and now is listed as 290k.

![screenshot from 2015-07-23 09 56 47](https://cloud.githubusercontent.com/assets/364615/8852077/29e305be-3121-11e5-8757-bdec14c531db.png)

It looks as if noon Friday through 9AM Wednesday aren't being counted any longer on the Stats page.  No data seems to have been lost; "confirmed" by looking at the stream and seeing well over 290k events.

Not a big deal, just wanted to mention it!

**Comment by dcramer** [comment]
Stats get calculated at process time and stored in a separate datastore, so even if you lost stats somehow the stream wouldn't change (as that data barring the graph on it, aren't stored in TSDB)

I can't really say why this would happen unless something stopped working correctly. Very unlikely upgrading is related here, as there werent any changes to the TSDB between those versions. If you see this come up again please re-open but I dont think there's anything else to be done w/o more information.

**Comment by mwcz** [comment]
No worries, sounds good to me.  Is there a quick and dirty way to regenerate the TSDB?  I suspect not, as the original queue is already processed.  Asking just in case. :)

**Comment by dcramer** [comment]
Yeah no way to regenerate it really today (especially if you have sampling enabled, with nearly everyone does)
