### ISSUE TITLE
Upload an iOS crash log manually to create an issue

### ISSUE THREAD

**Issue by mschickervxob** [getsentry/sentry#16405]
Ist it possible with sentry to upload an iOS/macOS crash log manually to create an issue in sentry and get it symbolicated?

**Comment by BYK** [comment]
Yes it is as this is how we test it works 🙂 

```shell
curl -X POST https://sentry.io/api/$PROJECT_ID/store/?sentry_key=$SENTRY_KEY -d @cocoa.json -v
```
