### ISSUE TITLE
Crystal language icon

### ISSUE THREAD

**Issue by Sija** [getsentry/sentry#16443]
## Summary

Would you mind adding [Crystal](https://crystal-lang.org) icon within the section below?

![image](https://user-images.githubusercontent.com/988/72368835-1b409880-36ff-11ea-919f-fd82d19912e7.png)

SVG icon is available at https://crystal-lang.org/assets/media/crystal_icon.svg

I can post a PR if needed, just wanted to know beforehand would you be willing to accept it.

## Motivation

Would be a nice touch for Crystal-based users.

**Comment by dashed** [comment]
Yes please send a PR
