### ISSUE TITLE
App/system frames need to appear visually different

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1644]

**Comment by ckj** [comment]
@dcramer you mind expanding on this one a bit?

**Comment by dcramer** [comment]
In the stack trace we have frames that have inApp = true. We should ensure that those visually look different from the others when they're together (in the full stack view)

**Comment by ckj** [comment]
@dcramer Do you mind to add some mock app frames? I don't have any of these locally.

**Comment by dcramer** [comment]
as of df559a9fc8067010021391f67b4ebdc5c0d10aaa the JS sample event should have one system frame
