### ISSUE TITLE
Annotations are not rendered on details page (i.e. GH-1)

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1645]

**Comment by dcramer** [comment]
Just realized these are actually implemented on the stream already, but not elsewhere.

**Comment by dcramer** [comment]
Mock data available by doing a pip install on the sentry-github repo and then enabling the integration for the project

**Comment by dcramer** [comment]
Just needs design

https://www.dropbox.com/s/65937hard88zsbs/Screenshot%202015-08-05%2018.18.25.png?dl=0

**Comment by ckj** [comment]
Styled up
