### ISSUE TITLE
Notification e-mail subject $projectID not always respecting the project name setting

### ISSUE THREAD

**Issue by jklaiho** [getsentry/sentry#16485]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [ ] Saas (sentry.io)
* [X] Other [briefly describe your environment]

Version 9.1.2 self-hosted on a Ubuntu Server VPS, running under a non-privileged dedicated user account. Installed through `pip install sentry` into a virtualenv, followed by manual edits of sentry.conf.py and config.yml. Processes running under Supervisor. Postgres and Redis installed via apt. (This is an old installation, gradually upgraded to modern versions.)

## Description

With a Subject Template setting of `[$projectID] $title` and the project name setting set to a pretty string (like `project-name`), notification e-mails for that project sometimes arrive with the pretty name (subject line example: `[Sentry] [project-name] Error Description`, but sometimes with the default uppercase ugly name (e.g. `[Sentry] [PROJECT-NAME-7V] Error Description`). This appears random, we have not been able to reproduce this consistently.

## Steps to Reproduce

1. Configure the subject template with `$projectID`
2. Wait for some notification e-mails to appear
3. Some of them will seemingly randomly have the `$projectID` you configured, others will have the weird uppercase default.

### What you expected to happen

`$projectID` in the subject template would always produce the manually set project name setting.

Unfortunately, I have no idea how to make sense of this due to its apparently (though almost certainly not actually) random nature.

This problem appeared while upgrading from an old version (6 or 7?) step-by-step to version 9. The old version used to work correctly.

**Comment by BYK** [comment]
Hi, this may be fixed in the latest version of Sentry, 10.0.0. As we don't support the 9.x series anymore, I'd kindly request you to try this with 10.0.0 and report back here if its still an issue.
