### ISSUE TITLE
Redis Sentinel Support

### ISSUE THREAD

**Issue by Mokto** [getsentry/sentry#16484]
## Summary

It would be amazing to support Redis Sentinel.

## Motivation

Support high availability redis workloads.

## Additional Context

```
    from redis.sentinel import Sentinel
    sentinel = Sentinel([
                        ('redis-ha-announce-0', 26379),
                        ('redis-ha-announce-1', 26379),
                        ('redis-ha-announce-2', 26379),
                        ], socket_timeout=15)
    redis_host = sentinel.discover_master('master')
```

Using something like this could help (it would need a re-connect mechanism though).

Thanks!

**Comment by BYK** [comment]
Hi! Thanks for the suggestion. We don't have any plans (or incentive) to support Sentinel so I'll be closing this issue to prevent clutter or any false hopes. We do support Redis Cluster though, if that helps.
