### ISSUE TITLE
Task Monitoring

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1649]
We want build some basic monitoring which will:

- Give you total throughput
- Give you per-queue throughput
- Give you a list of all registered tasks

Per Task
- Give throughput
- Give duration (average and 90th at minimum)

**Comment by dcramer** [comment]
This page will likely suck until React changes land.

We also need to implement duration in tsdb to move much further with it.

**Comment by dcramer** [comment]
Closing for now. Will use this as a ref later.

**Comment by jmreicha** [comment]
Is this working in 7.7?

I am seeing "There was an error loading statistics" on the overview and queue pages.

**Comment by dcramer** [comment]
@jmreicha yes -- if its not its likely because theres a server misconfiguration (you should look at the console error and see what it says)

**Comment by jmreicha** [comment]
@dcramer Sorry, I've been super busy.  Seeing this error in the web console:

```
Mixed Content: The page at 'https://<sentry.example.com>/manage/queue/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://<sentry.example.com>/api/0/internal/stats/?since=1450888865.215&resolution=10s&key=jobs.all.started'. This content should also be served over HTTPS.```

I'll dig around and see if I can find a setting I'm missing.

**Comment by dcramer** [comment]
If you're using https then you need to set SENTRY_URL_PREFIX also to be https, that should resolve this.

**Comment by jmreicha** [comment]
Derp, should have caught that.  Working now, thank you!
