### ISSUE TITLE
Cannot search by tags or any other property - On-premise

### ISSUE THREAD

**Issue by bhargav-vasist** [getsentry/sentry#16513]
## How are you running Sentry?

* [x] On-Premise docker [Version 9.1.1]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## What happened ?

We cannot seem to search or filter issues by tags (release, last-seen, environment etc)

## Steps to Reproduce

1. Record an issue with tags.
2. Click on the tag on the issue page
3. Search results are empty.

This issue has surfaced 
and a direct cause might be attributed to switching to 9.1.1
Events captured on our earlier releases seem to work when searching or filtering.
Any issues that are caught recently are not showing up.

This might be due to the issues not being indexed perhaps, because the API call to search results returns an empty array.

[Update] - Another issue that might be a symptom of the root cause -
Even though`setUser` is called with valid data and is setting user properties, the issue's usercount remains 0 (The main issue page where the count of both events and users are shown)

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues. We are not going to make any new releases on the 9.1.x branch so you can try upgrading to 10.0.0 or seek help in the forums.
