### ISSUE TITLE
Status checks visual issues

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1651]
https://www.dropbox.com/s/0ql54yjxbtztbrk/Screenshot%202015-07-27%2016.05.18.png?dl=0

**Comment by ckj** [comment]
These should be good to go:
<img width="1313" alt="screen shot 2015-07-28 at 3 22 38 pm" src="https://cloud.githubusercontent.com/assets/30713/8941291/b2c5e0da-353c-11e5-9a05-6008a1bafb0d.png">
