### ISSUE TITLE
Add settings link (gear icon) to issue list page

### ISSUE THREAD

**Issue by tonyo** [getsentry/sentry#16536]
## Summary

Would be useful to have the link to settings (the gear icon) here:

![image](https://user-images.githubusercontent.com/1120468/72718357-16a03800-3b76-11ea-9133-3874acd48a92.png)
 

## Motivation

It's a bit painful to open project settings from the issue list page: you either have to go via settings, or via the dropdown (where the project might be not visible right away), or open issue details page, where we have the icon:

![image](https://user-images.githubusercontent.com/1120468/72718494-59faa680-3b76-11ea-9654-09562c25a689.png)

## Additional Context

I understand that this doesn't work together with the multi-project select feature, but when there's only one project selected -- why not, it would make things a bit more consistent with the issue details page.

**Comment by markstory** [comment]
The inconsistent experience with multiple projects selected would be one reason not to make this change.

Before folks plan out too many incremental changes to the global selection header, we should find out what the longer term plans for it are. I know there are a few folks in design/product womho would like to see the global header removed entirely.

**Comment by matejminar** [comment]
OK, let's wait for the bigger picture decision from design/product before making any changes.

@tonyo I've played with it a bit and probably the fastest way to navigate to project settings is via the command palette.

When I hit CMD+K and start typing project name, it consistently gives me given project's settings as a first result (maybe except for sentry) so after a few characters hitting Enter will usually do it.

![chrome-capture (1)](https://user-images.githubusercontent.com/9060071/72788013-4eb88100-3c31-11ea-84bb-82c642c04e7e.gif)

I know it's not a solution, just maybe something to consider in a meantime.
