### ISSUE TITLE
Navigate to Project Issues from Issue Detail view

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry#16538]
## Summary

Enable users to consistently navigate from issue detail view to list of issues in the same project.
Possible implementation is to make the project name in the header be a hyperlink to the list of project issues.

## Motivation

> Why should this be worked on? What problems or use cases does it solve or
improve?

Consider this flow:
1. Go to https://sentry.io/issues/
2. Click an issue belonging to "project A"
3. Clicking the <- arrow navigates back to all issues, no way to navigate to all issues of "project A" except for using the browser's Back button

![image](https://user-images.githubusercontent.com/88819/72731402-f5e6db00-3b93-11ea-8f36-b4452bd493ae.png)

## Additional Context

Related issue: #13864.
I noticed that the behavior of the Back button is hard to predict and is influenced by actions you do in the issue view. Going "back" can be ambiguous -- back to where I came from? Back to all issues? Back to project issues? Therefore what I propose is to click on the project name to navigate to project issues, or an equivalent solution.

**Comment by matejminar** [comment]
Hey @markstory, do you think I can make the project name in a global selection header (on issue detail page) link to its issue stream?

I've looked into the code and it is pretty straight forward change. 
The two things to consider here are:
1) small inconsistency - if you click on a project name in global selection header on issue detail page it takes you to its stream (we can put a tooltip there), but on issue stream page clicking on it will open the project selector dropdown
2) the thing you mentioned here: https://github.com/getsentry/sentry/issues/16536#issuecomment-576302996 that we should add incremental changes to global selection header carefully, as we do not know its future

**Comment by markstory** [comment]
Having the project name link back to that project's issue stream seems relatively safe. The dropdown behavior is disabled in single project mode.
