### ISSUE TITLE
Slim Framework + Sentry.io integration not working

### ISSUE THREAD

**Issue by s2925534** [getsentry/sentry#16549]
I have been trying to make this work but with no luck.

In a regular method within a class I have placed:
```

            $options = ['dsn' => getenv('SENTRY_PUBLIC_DSN')];
            \Sentry\init($options);

            try {
                thisFunctionThrows(); // -> throw new \Exception('foo bar');

            } catch (\Exception $exception) {
                \Sentry\captureException($exception);
            }
```

Nothing is happening.

What do I do?

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
