### ISSUE TITLE
Deleting default sentry user deletes all related data

### ISSUE THREAD

**Issue by sul4bh** [getsentry/sentry#1656]
Deleting default 'sentry' user deletes all related data including projects, organizations etc. I guess it is because of default ON DELETE CASCADE in django (https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.ForeignKey.on_delete).

This behaviour should be documented or mentioned on the delete page (https://github.com/getsentry/sentry/blob/master/src/sentry/templates/sentry/admin/users/remove.html). Listing all the items that will be deleted permanently would improve user experience and prevent data lost.

**Comment by dcramer** [comment]
Probably should just prevent removing this user

**Comment by dcramer** [comment]
Deletion should mostly be prevented in b63ea3c17735cd50aa3aeed7b64a8342c333d513
