### ISSUE TITLE
Link Github Issue appears twice

### ISSUE THREAD

**Issue by aroltsch** [getsentry/sentry#16598]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.1.2]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

"Link Github Issue" appears twice in the UI (see screenshot below please).  

## Steps to Reproduce

1. Integrate Github with Sentry following these steps: https://docs.sentry.io/server/integrations/github/
2. The first link works as expected and I am able to create an issue.

![image](https://user-images.githubusercontent.com/3811786/73009946-62a1e580-3ddf-11ea-943d-99f61ff537da.png)

### What you expected to happen

"Link Github Issue" appears only once

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by markstory** [comment]
Do you have the integration setup multiple times?

**Comment by aroltsch** [comment]
If I look at the `sentry_integration` table, it shows only one integration - Github. Is it even possible to setup the same integration twice?

**Comment by markstory** [comment]
Yes it is possible to setup the integration more than once if you have multiple github organizations. Did you ever use the github plugin?

**Comment by aroltsch** [comment]
This is our first time setting it up. I believe we have only one github organization. 

### Plugin Issues
I've noticed that the code also looks at the `pluginIssues` [here](https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/app/components/group/externalIssuesList.tsx#L230). If I look at the network tab:

URL: https://sentry.ds.va.gov/api/0/issues/7759/
Response: 
![image](https://user-images.githubusercontent.com/3811786/73069223-2e7c0280-3e7b-11ea-9fc4-958828eeb846.png)


### Integration Issues

The code checks for `integrationIssues` as well, that I believe is  based on `externalIssues`. If I look at the network tab, I can see externalIssues are coming back correctly. 
URL: https://sentry.ds.va.gov/api/0/groups/7759/integrations/
Response: 
![image](https://user-images.githubusercontent.com/3811786/73069384-97fc1100-3e7b-11ea-89b8-e3a585325fb4.png)

I believe `pluginIssues` should be coming back as an empty array in our case but they are not. Where do I look next? 

Thank you for you help on this!

**Comment by markstory** [comment]
That pluginIssues payload implies that the project level plugin for github has been setup in addition to the organization level integration. You can find project plugins in the project settings.

**Comment by aroltsch** [comment]
@markstory THANK YOU! I uninstalled the project level plugin and it removed the second link.
