### ISSUE TITLE
"Create project" in the sentry GUI truncates long project names

### ISSUE THREAD

**Issue by Kalmalyzer** [getsentry/sentry#16616]
If I create a new project with the name "abcdefghi-abcdefghi-abcdefghi-abcdefghi-abcdefghi-" then its name becomes truncated to 30 characters ("abcdefghi-abcdefghi-abcdefghi-"). I am allowed to enter a long project name in the project creation wizard and I am not informed anywhere that the truncation will occur.

Once the project has been created I can successfully rename it to something longer than 30 characters via the project's Project Settings page.

**Comment by infinityxxx** [comment]
Can someone check https://github.com/getsentry/sentry/pull/21586 ?
