### ISSUE TITLE
AssertionError - Discarded invalid value for interface: sentry.interfaces.Exception - How to Debug?

### ISSUE THREAD

**Issue by eitchugo** [getsentry/sentry#1661]
My sentry installation is working fine with its features (pgsql database, job queues on redis) and accepting events from many clients.

But the web log file shows *many* error entries like this (many per second):

```
AssertionError
Discarded invalid value for interface: sentry.interfaces.Exception
Traceback (most recent call last):
  File "/movile/sentry/env/lib/python2.7/site-packages/sentry/coreapi.py", line 355, in validate_data
    inst = interface.to_python(value)
  File "/movile/sentry/env/lib/python2.7/site-packages/sentry/interfaces/exception.py", line 176, in to_python
    for v in data['values']
  File "/movile/sentry/env/lib/python2.7/site-packages/sentry/interfaces/exception.py", line 47, in to_python
    stacktrace = Stacktrace.to_python(data['stacktrace'])
  File "/movile/sentry/env/lib/python2.7/site-packages/sentry/interfaces/stacktrace.py", line 447, in to_python
    assert data.get('frames')
```

I understand that this error can mean that some client hit an implementation bug or is sending invalid data, but since my server has too many requests from numerous clients, keys and projects, how can I debug the error to know what request is generating the error?

Requests to the API are always returning HTTP 200.
Version used is 7.6.2
There's no errors on the worker log

**Comment by dcramer** [comment]
@eitchugo in the current version of Sentry this is kind of half-assed and you cant really do it

That said, this is enough for me to finally get around to fixing it, so expect a patch shortly.

**Comment by dcramer** [comment]
Closing this out as master (which will be 7.8.0) actually logs this entirely into Sentry's internal project as well as greatly improved console logs.
