### ISSUE TITLE
Some notifications not delivered to Slack

### ISSUE THREAD

**Issue by diogobaeder** [getsentry/sentry#16620]
Hi guys,

In the company I work for we enabled the integration between Sentry and Slack. For a bunch of errors it's notifying fine, but for others it's not. I could get two examples of "unresolved" alerts in the Sentry UI, but for some reason one of them wasn't notified on Slack.

Is there some sort of sampling of alerts that is automatically configured? If so, how can I disable it, so that I can get all the alerts in Slack?

Thanks,
Diogo

**Comment by untitaker** [comment]
I have transferred your issue to the correct repository, but I would consider writing into support with this question.

**Comment by diogobaeder** [comment]
Sorry, I've just found out that I was not getting alerted because I was reaching my quota. So I'll close this ticket, as it's not a Sentry issue.

Thanks!
