### ISSUE TITLE
Breadcrumbs boolean values are ignored in the UI

### ISSUE THREAD

**Issue by JackCA** [getsentry/sentry#16637]
- [x] Review the documentation: https://docs.sentry.io/
- [x] Search for existing issues: https://github.com/getsentry/sentry-javascript/issues
- [x] Use the latest release: https://github.com/getsentry/sentry-javascript/releases
- [x] Provide a link to the affected event from your Sentry account: https://sentry.io/organizations/astral-digital/issues/1354472883/?project=1524574&query=is%3Aunresolved

## Package + Version

- [x] `@sentry/browser`
- [ ] `@sentry/node`
- [ ] `raven-js`
- [ ] `raven-node` _(raven for node)_
- [ ] other:

### Version:

```
5.10.2
```

## Description

It appears that creating a breadcrumb with a boolean value e.g.`{ foo: false}`, will result in a breadcrumb in the UI where there is no visible value for `foo` i.e. it ignores the boolean.

[The docs](https://docs.sentry.io/enriching-error-data/breadcrumbs/?platform=javascript) say that it should be str --> str, so it's understandable that things wouldn't work as expected; however, the [typescript definition](https://github.com/getsentry/sentry-javascript/blob/645ff532941d9a23bb6531c6305e99544b356502/packages/browser/src/integrations/breadcrumbs.ts#L74) has `any` as the value. If boolean's aren't acceptable, then I think perhaps the type definition shouldn't be `any`?

**Comment by priscilawebdev** [comment]
@JackCA  sorry for the delay. I am checking it 😉
