### ISSUE TITLE
How to know if sentry is running and successfully reporting errors?

### ISSUE THREAD

**Issue by islamhamdi** [getsentry/sentry#16631]
Hi all,

Our system integration with Sentry is through various codebases (Elixir, Ruby, React, ...).
Sometimes Sentry doesn't work properly due to an issue with our configuration initialization, e.g:

Our config might look like:

```
if (sentry_enabled == True) { set included_environments: current_env } ; otherwise {set included_environments: [] }
```

Sometimes an issue with our configurations doesn't populate `sentry_enabled` properly and hence it's disabled, how can we alert in such case? Is there a native integration to sentry that alerts us in case: SENTRY DIDN'T SEND ANY ERRORS FOR THE PAST DAY?

Or there's a better suggestion with heartbeat integration with Sentry to make sure things are working properly? Integrating Sentry doesn't mean that it's actually working and reporting errors successfully, a prior incident was an issue with our HTTP library that prevented sending HTTP requests to 3rd parties.

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
