### ISSUE TITLE
GitHub integration is broken

### ISSUE THREAD

**Issue by syabro** [getsentry/sentry#16635]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [X] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

GitHub integration broken. I see "Set up Issue Tracking" in  "Linked Issues" instead of create github issue button. But github integration is installed
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/29029/73151073-31395a80-40fc-11ea-8057-e49a90c8c7d4.png">

### What you expected to happen
See GH issues controls button

**Comment by scefali** [comment]
@syabro I just tested this on the Sentry organization and it looks OK. Can you post a screenshot of what it looks like on the issue where it says "Set up Issue Tracking"? If you can provide the slug of your organization that will also help me debug the problem.

**Comment by syabro** [comment]
@scefali looks like problem was solved
<img width="360" alt="image" src="https://user-images.githubusercontent.com/29029/73228807-5e444680-41aa-11ea-8083-1363fbf8c5d3.png">
