### ISSUE TITLE
Celery error after upgrade to 7.7.0

### ISSUE THREAD

**Issue by 1it** [getsentry/sentry#1665]
-------------- celery@sentry v3.1.18 (Cipater)
---- **** ----- 
--- * ***  * -- Linux-3.16.0-4-amd64-x86_64-with-debian-7.8
-- * - **** --- 
- ** ---------- [config]
- ** ---------- .> app:         sentry:0x2fce150
- ** ---------- .> transport:   redis://127.0.0.1:6379//
- ** ---------- .> results:     disabled
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- 
--- ***** ----- [queues]
 -------------- .> alerts           exchange=default(direct) key=alerts
                .> auth             exchange=default(direct) key=auth
                .> cleanup          exchange=default(direct) key=cleanup
                .> counters-0       exchange=counters(direct) key=
                .> default          exchange=default(direct) key=default
                .> email            exchange=default(direct) key=email
                .> events           exchange=default(direct) key=events
                .> options          exchange=default(direct) key=options
                .> search           exchange=default(direct) key=search
                .> sourcemaps       exchange=default(direct) key=sourcemaps
                .> triggers-0       exchange=triggers(direct) key=
                .> update           exchange=default(direct) key=update

[2015-07-31 09:48:04,740: WARNING/MainProcess] celery@sentry ready.
[2015-07-31 09:48:14,653: ERROR/MainProcess] Received unregistered task of type 'sentry.tasks.check_alerts'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

The full contents of the message body was:
{'utc': True, 'chord': None, 'args': [], 'retries': 0, 'expires': '2015-07-31T09:49:14.651268', 'task': 'sentry.tasks.check_alerts', 'callbacks': None, 'errbacks': None, 'taskset': None, 'kwargs': {}, 'eta': None, 'id': '095adc2d-8a4b-4d6a-9c35-95114f7774f0'} (234b)
Traceback (most recent call last):
  File "/var/www/sentry/local/lib/python2.7/site-packages/celery/worker/consumer.py", line 455, in on_task_received
    strategies[name](message, body,
KeyError: 'sentry.tasks.check_alerts'

**Comment by dcramer** [comment]
You can safely ignore this (that task no longer exists)
