### ISSUE TITLE
Projects by organization does not work without authenticated user

### ISSUE THREAD

**Issue by mi-schi** [getsentry/sentry#1666]
Hello,

I try to get all projects from the sentry api. I use PHP and Guzzle as client.

````
$client = new GuzzleClient();
$projects = $client->get($url, ['verify' => false, 'curl' => [
    CURLOPT_USERPWD => 'c990913e51f01025f489ff27f5c874a3:'
]]);
```

When I call ```https://sentry.domain.com/api/0/``` or ```https://sentry.domain.com/api/0/projects/1/groups/``` I get a response. When I call ```https://sentry.domain.com/api/0/organizations/orga/projects/``` the response is empty.

All scopes are activated for the api key. What I have missed?

**Comment by dcramer** [comment]
@mi-schi it's possible you're using an older version of Sentry?

We have effectively moved away from using project IDs in URLs and nearly everything is keyed by org slug + project slug in latest.

**Comment by mi-schi** [comment]
Hi,

we use Sentry in the penultimate version (7.6.2).

**Comment by dcramer** [comment]
Looks like this endpoint isnt functional in current releases of Sentry (it requires an authenticated user).

**Comment by mi-schi** [comment]
Hi,

I try it with a basic command:

```
curl --insecure -u c990913e51f01025f489ff27f5c874a3: https://sentry.domain.com/api/0/organizations/orga/projects/
```

The response is empty too. When I'm logged in with the browser via frontend and I call this url, I get a response.

**Comment by dcramer** [comment]
@mi-schi as I mentioned it's not working correctly currently. It requires session auth and wasn't updated to support API keys. We'll fix this at some point in the future.

**Comment by mi-schi** [comment]
Is it possible that you create a new version with this changes? Since 28 July, the last version 7.7 is available. Or should we pull dev-master?

**Comment by dcramer** [comment]
@mi-schi we're not pushing out any releases until 8.0 which will probably be another month or so
