### ISSUE TITLE
Bind releases to project instead of organization

### ISSUE THREAD

**Issue by vitalets** [getsentry/sentry#16664]
## Summary

According to [sentry docs](https://docs.sentry.io/workflow/releases/?platform=javascript#setting-up-releases):

> Releases are global per organization, so make sure to prefix them with something project-specific. 

I'd like to bind releases to project scope, not to organization.

## Motivation

* having all releases in organization namespace requires to prefix every release with project name. Instead of just releasing `v1.0` in `projectX` and `projectY` I need to release `projectX-v1.0` and `projectY-1.0` that's redundant.

* using sentry-cli I've configured `.sentryclirc` with `defaults.project=projectX`. Then I've run `sentry-cli releases files v1.0 upload ...` and surprisingly found that files in release `v1.0` of another project (`projectY`) were overwritten! And we got broken source-maps on production release 1.0 of projectY. So, field `defaults.project` in `.sentryclirc` is confusing because it does not restrict scope of sentry-cli commands to specified project.

**Comment by BYK** [comment]
Ping @mitsuhiko

**Comment by mitsuhiko** [comment]
We investigated it again if we can make releases project specific and unfortunately that breaks a lot of usecases that customers currently have. I would leave this issue open as a meta issue since we're aware of the shortcomings and are investigating what options we have that do not break existing workflows.

**Comment by BYK** [comment]
Merged into #6649.
