### ISSUE TITLE
Sentry 10.x Gitlab integration. Strange integration overview

### ISSUE THREAD

**Issue by trondhindenes** [getsentry/sentry#16663]
## Important Details

How are you running Sentry?
* [x] On-Premise docker [10.1.0.dev0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description
After configuring the gitlab integration everything works, but the integration itself lists a single project like this:
![Screenshot from 2020-01-28 12-20-37](https://user-images.githubusercontent.com/1747120/73259877-049f4480-41c9-11ea-876b-837e6ae83e92.png)

While the "repositories" overview lists a lot of configured repos, including the one shown in the "integrations" view. Our developers are confused by this.

For info, we used to have multiple gitlab integrations configured, since we use subgroups in gitlab. Now that the gitlab integration supports subgroups, we've reconfigured sentry so we only have a single gitlab integration configured.

### Possible Solution
The "integrations" view should be more understandable. Either don't show any repos, or show unconfigured ones, but dont show a single random repo like now.

**Comment by trondhindenes** [comment]
I got some more info now:
That single repo listed in the integration is likely the first repo added after we switched to the new version of the gitlab integration. Our "Repositories" list contains a bunch:

![Screenshot from 2020-01-28 12-30-05](https://user-images.githubusercontent.com/1747120/73260349-03bae280-41ca-11ea-82a9-6cbda7ea7e23.png)

Its still confusing. How can we "upgrade" the repos added under the previous version of the integration, so that they're shown?

**Comment by markstory** [comment]
Those other repositories are from the other integration instances so they won't show up in the current integration's repository listing.

There isn't a good way to update those repositories via the API. However, you can update the repository rows in the database as you're running on premise.

**Comment by trondhindenes** [comment]
thanks! We decided to try just re-adding them and that worked.

**Comment by markstory** [comment]
Great to hear that you got it sorted out.
