### ISSUE TITLE
Unsetting per-project email notification preferences removes the link

### ISSUE THREAD

**Issue by kuzmik** [getsentry/sentry#1667]
I set a custom email address for a specific project. I changed my mind about it, deleted it in the popup box and now it is blank. 

![notification_settings___settings___sentry](https://cloud.githubusercontent.com/assets/4432296/9014844/d1e03828-3779-11e5-841c-800fa774a15f.png)

**Comment by dcramer** [comment]
@kuzmik does this fix itself on reload?

Of note need to confirm this isnt broken in the redesign branch, as I dont think we have really checked over the account settings code.

**Comment by kuzmik** [comment]
Yeah it did. Sorry about the superfluous bug report!
