### ISSUE TITLE
Sentry using Server IP address instead of Client IP Address

### ISSUE THREAD

**Issue by Nikita279** [getsentry/sentry#16687]
Hi,

I am using Sentry.io and it is using server ip as user ip to show user count.
We are also setting userid and deviceid in headers. 

How do I configure Sentry to show correct count of users?

Below are screenshot showing the same -
![NullPointerException](https://user-images.githubusercontent.com/40610477/73339207-39310000-429e-11ea-8156-c83190a9a213.png)

![NullPointerException (1)](https://user-images.githubusercontent.com/40610477/73339218-4221d180-429e-11ea-82d0-1ea9830a14f0.png)

**Comment by VentyCZ** [comment]
I also have the same issue lately, also using a proxy like NginX @Nikita279 ?

**Comment by saifelse** [comment]
This is the responsibility of the server when reporting the error. As an example, if your backend is in Python and you're using WSGI, the WSGI Integration properly extracts the IP from the X-Forwarded-For and subsequently sets it on the scope's user:

https://github.com/getsentry/sentry-python/blob/52830558bb535d7ff8e09b27703c99425262067f/sentry_sdk/integrations/wsgi.py#L195-L212

```py
def get_client_ip(environ):
    # type: (Dict[str, str]) -> Optional[Any]
    """
    Infer the user IP address from various headers. This cannot be used in
    security sensitive situations since the value may be forged from a client,
    but it's good enough for the event payload.
    """
    try:
        return environ["HTTP_X_FORWARDED_FOR"].split(",")[0].strip()
    except (KeyError, IndexError):
        pass

    try:
        return environ["HTTP_X_REAL_IP"]
    except KeyError:
        pass

    return environ.get("REMOTE_ADDR")
```

**Comment by BYK** [comment]
Thanks @saifelse for the helpful answer here.

@Nikita279, please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
