### ISSUE TITLE
Offer generating code that can be used in GTM

### ISSUE THREAD

**Issue by Misiu** [getsentry/sentry#16694]
## Summary

While creating project offer generating code that can be directly inserted into GTM

## Motivation

I need to debug two sites that I don't have FTP access to. I was asked to do that using GTM.
I was able to create code on my own, but I this it would be useful to have this auto-generated for your project

## Additional Context

This is the code I'm using right now. It might be not optimal or ideal but it works.

```
<script>(function(d){var h=d.getElementsByTagName('head')[0],c=d.createElement('script');
    c.type='text/javascript';c.src='https://browser.sentry-cdn.com/5.11.1/bundle.min.js';
    c.integrity='sha384-r7/ZcDRYpWjCNXLUKk3iuyyyEcDJ+o+3M5CqXP5GUGODYbolXewNHAZLYSJ3ZHcV';
    c.crossOrigin='anonymous';c.onload=function(){Sentry.init({dsn:'https://f8f44fbdbd3e4bece43395cb84476748@sentry.io/XXXXXXX'});};
    h.appendChild(c);})(document);</script>
```

**Comment by BYK** [comment]
I don't know what you mean by GTM but we already generate code that can be directly copy/pasted into your project: https://sentry.io/<your_org>/<your_project>/getting-started/javascript/
