### ISSUE TITLE
Missing 'org_results' data in production but has some in staging

### ISSUE THREAD

**Issue by kuzmik** [getsentry/sentry#1673]
In file 'web/frontend/help_platform_base.py', method 'group_project_list' the org_results appears to be blank in our production environment.

This manifests when we try to load the 'setup & installation' page
<img width="734" alt="prod" src="https://cloud.githubusercontent.com/assets/4432296/9042832/2c773b94-39c6-11e5-9cc8-fa49f0a6f3ef.png">

However, the same setup is in staging and appears to work, for certain random projects:
<img width="737" alt="staging" src="https://cloud.githubusercontent.com/assets/4432296/9042839/37822d32-39c6-11e5-8c65-ddf6d700de75.png">

In staging I ran 'update sentry_organizationmember_teams set is_active = 1;' and the projects all showed up in the dropdown. 

We *did* add a custom SSO implementation, so perhaps we missed a step on account creation?

Since there is a "client keys" page, this isn't a show stopper but I'm worried that whatever is wrong could manifest in other ways that we haven't found yet.

**Comment by dcramer** [comment]
@kuzmik by custom SSO do you mean an actual SSO Provider (an implementation of sentry.auth.Provider) or simply a middleware/something similar that creates accounts?

If the latter it's possible you need to set some flags or create some specific objects.

Will dig into this as it's possible there's an issue on our side, but we may just ignore this and ensure it's addressed in the v8 redesign branch (which we're close to landing).

**Comment by kuzmik** [comment]
We wrote this implementation:

```
import urllib, json
from django.conf import settings
from django.contrib.auth.backends import RemoteUserBackend
from sentry.models import (
    Organization, OrganizationMember, OrganizationMemberType,
    UserOption
)

class DoormanAuth(RemoteUserBackend):
    def configure_user(self, user):
        user.email = user.username + "@squareup.com"
        user.is_managed = True
        user.save()

        # Fetch full name
        response = urllib.urlopen("userlookupservice/%s" % user.username, proxies={})
        if response.getcode() is 200:
            data = json.loads(response.read())
            user.first_name = data["name"]
            user.save()

        # Disable notfications by default
        UserOption.objects.set_value(
            user=user,
            project=None,
            key="subscribe_by_default",
            value="0",
        )

        # Disable notes by default
        UserOption.objects.set_value(
            user=user,
            project=None,
            key='subscribe_notes',
            value="0",
        )

        if settings.SENTRY_SINGLE_ORGANIZATION:
            org = Organization.get_default()
            OrganizationMember.objects.create(
                organization=org,
                user=user,
                type=OrganizationMemberType.OWNER,
                has_global_access=True,
            )

        return user
```

Ignoring for now is fine, like I said we can get the client keys from that page. Was just something I wanted to make sure wouldn't manifest elsewhere.

**Comment by dcramer** [comment]
At a glance the implementation looks correct. Assuming its an internal issue. Will try to repro just to ensure it's not broken in v8.

**Comment by drcapulet** [comment]
Found the source of the issue - if any set of members have collectively left all teams (aka at least one person has left each team) this bug presents, otherwise it just shows a different set of data - I've got a patch that I'm still working on to make sure it doesn't make the query perform poorly.
