### ISSUE TITLE
Support for colorized logs

### ISSUE THREAD

**Issue by matuscongrady** [getsentry/sentry#16744]
Hi,

**Our use case:**
We print colorized logs to the terminal (from a node.js application).
These logs use special ANSI escape characters to add color to the terminal. For example `\u001B`

![image](https://user-images.githubusercontent.com/20205489/73530331-8f29b300-4418-11ea-8f88-41cf964e98db.png)

Unfortunately, sentry does not recognize these characters and our logs look are hard to read because of that.

It would be nice if you could convert these characters into actual colors, or remove them completely from the string.

It would make our debugging experience way more enjoyable.

Thank you!

**Comment by mitsuhiko** [comment]
@untitaker wonder if we would want to discard this on normalization or deal with it in the UI.

**Comment by untitaker** [comment]
It would be sick to render those colors in the UI ;)

**Comment by untitaker** [comment]
So to be clear I don't think much of normalizing them away. If we don't want this in the schema I think we should figure out why the instrumentation captures logs after formatting

**Comment by MhdSyrwan** [comment]
any updates on this?

@untitaker as far as i know, there is no way to capture that before formatting. since usually people generate these logs using `chalk` nodejs lib or a similar thing. it's already printed with these ansi colors annotations.

in order to make this work, we need to remove these ansi annotations if having a clolored log is not an option.

**Comment by untitaker** [comment]
Right, we didn't really start working on this yet but we're discussing internally what to do about it.

**Comment by windware-ono** [comment]
Any news?
I'd like the support for this too.

It looks semi garbage with the ansi escape sequences all over.

![log-ansi-color](https://user-images.githubusercontent.com/4352236/94708061-20be3b80-037f-11eb-967b-64992ed1edc7.png)

**Comment by ImUrX** [comment]
Any place I should look in the code to start adding support for this, or at least for now normalize it?

**Comment by MichaelSun48** [comment]
Closing this out in favor of [this issue](https://github.com/getsentry/sentry/issues/49804), which is more recent and appears to be the same issue. Feel free to reopen if I'm incorrect.
