### ISSUE TITLE
Slack integration: do not request permission to use channels.info because it exposes too much confidential information to Sentry

### ISSUE THREAD

**Issue by Nowaker** [getsentry/sentry#16755]
## Summary

Do not use the deprecated `channels.info` endpoint. Use `conversations.info` for better security.

## Motivation

Sentry-Slack integration doesn't pass our security review because it requests permission to call `channels.info` presented in Slack UI as:

> View channel names, member lists, topics, purposes, and latest message.

While it's okay for Sentry to see channel names and such, it has absolutely no business in reading the latest message on each channel Sentry app is present on!

In case ever Sentry.io gets compromised, and Slack integration secret for our organization (and other organization) is leaked, conversations on every channel could be disclosed to unrelated parties.

While Sentry source code doesn't appear to be using this endpoint, the fact it has a permission to call that endpoint is a problem.

The whole fix is likely about changing a list of requested permissions to some lesser ones, where Sentry does not get to read any channel messages. (Except for unfurling - but that is a separate permission) 

## Additional Context

My conversation with Slack:

> I've installed a Slack app (Sentry - https://slack.com/apps/A99FD3DJ5-sentry) that has a permission that sounds really scary to me:

>> View channel names, member lists, topics, purposes, and latest message

> "latest message" is the scary part. The app joined all our channels, and I don't know if it's now passing all our new messages to its servers.

> I went to https://api.slack.com/scopes to find which scope exactly the app requests. I can't see it. There is no single scope that would be about viewing latest message. I typed in "View channel names, member lists, topics, purposes, and latest message" into Google - only Sentry app shows up with a direct match: https://slack.com/apps/A99FD3DJ5-sentry. Nothing about that specific scope.

> The question is: what scope EXACTLY is "View channel names, member lists, topics, purposes, and latest message" that Sentry app requests? Is it channels:read? https://api.slack.com/scopes/channels:read It does not have anything related to reading latest message, as you can see under the link. So what is it?

> This question is also a request to update your documentation at https://api.slack.com/scopes to match descriptions visible at https://slack.com/apps/A99FD3DJ5-sentry.

Slack:

> Thanks for writing in, our apologies for the confusion here.

> This is a bit of a complex question because it's tied to some legacy features.

> First, I can confirm that you're correct and that the Sentry app can access the latest message in all the channels it's been added.
> This is because Slack's API provide an "overview" of the channel's info, and includes the channel's latest message.

> This is something that we've removed from newer methods, but that Sentry is still using for legacy reasons.

> You should, however, be able to only add the app to specific channels if needed. You can modify its channel access at: https://my.slack.com/apps/A99FD3DJ5-sentry?settings=1

> Our apologies again for the confusion.

Me:

> By saing "Sentry app can access the latest message in all the channels it's been added" which one do you mean:

> 1. Sentry can make an API call to Slack to get the latest message in all our channels, or
> 2. Sentry receives a webhook from Slack every time a new message is posted to all our channels?

> I guess that's (1) but I wanna double check. :)

Slack:

> It's indeed (1). Slack isn't proactively sending any data, but Sentry could get the latest message information by calling the channels.info endpoint: https://api.slack.com/methods/channels.info

**Comment by mattrobenolt** [comment]
Hi there @Nowaker, thank you for this very detailed report. I'm going to make sure this gets escalated.

**Comment by Nowaker** [comment]
Thanks @mattrobenolt!

Note: I don't see Sentry source code using this endpoint. The fact it has a permission to call that endpoint is the problem. The whole fix is likely about changing a list of requested permissions to some lesser ones.

**Comment by mattrobenolt** [comment]
Yup, I'm assuming that is correct as well. I haven't worked on this integration, so I'm not sure what the reasoning is.

**Comment by mattrobenolt** [comment]
I think this is more context: https://github.com/getsentry/sentry/pull/14848

**Comment by Nowaker** [comment]
@mattrobenolt Yep, it looks like it **was** a solution to the problem. However, between then and now, there appears to be no use of said channels.info endpoint, but access to that endpoint is still requested.

**Comment by MeredithAnya** [comment]
Hi @Nowaker 

> but access to that endpoint is still requested

The scope we require is the `channels:read` scope (which you mentioned above). We need it because we are using the `channels.list` endpoint. The `channels.list` endpoint is being deprecated later this year in favor of the `conversations.list` endpoint, which we will ultimately need to use. 

However, from what I can tell, we will still need to request the `channels:read` scope in order to use the [conversations endpoint](https://api.slack.com/methods/conversations.list). 

cc @EvanPurkhiser

**Comment by Nowaker** [comment]
@MeredithAnya Thanks for clarifying. Looks like you're 100% right, and the guidance Slack provided was incorrect. Switching from `channels.list` to `conversations.list` will achieve absolutely nothing given they're part of the same scope `channels:read`. I've just contacted Slack again and asked them to review the mess they have in there.

**Comment by BYK** [comment]
Closing as this issues is not actionable on our end until Slack makes -yet another set of changes- to their APIs.
