### ISSUE TITLE
GitHub Integration: GitHub thinks the integration is configured, but it doesn't appear in Sentry

### ISSUE THREAD

**Issue by angusholder** [getsentry/sentry#16767]
In Organization Settings > Integrations:
![image](https://user-images.githubusercontent.com/7407345/73650605-73254c00-467a-11ea-895e-55d5459b032f.png)

And when I click Install:
![image](https://user-images.githubusercontent.com/7407345/73650620-791b2d00-467a-11ea-94bf-c015ff0cb190.png)

Yet "Add Installation" leads to a GitHub page that says "Manage your installation settings" (as if it's already installed), and if I click Configure, this is what is shown:
![image](https://user-images.githubusercontent.com/7407345/73650733-be3f5f00-467a-11ea-9ed4-6c3d7fc58d8d.png)

**Comment by benhutton** [comment]
same here!

**Comment by scefali** [comment]
Hi there! Github only allows you to install the Sentry organization at a time. So you will need to uninstall Sentry from your Github account then re-install it on the organization you want. Here is the link to manage your apps, from which you can uninstall Sentry: https://github.com/settings/installations

**Comment by chances** [comment]
@scefali Are you saying that when we install the Sentry integration on GitHub, we need to allow access to _all_ repositories in an organization? In other words, is the problem that I and this issue's author are using "Only select repositories" under "Repository access"?

**Comment by scefali** [comment]
@chances You can either pick "all repositories" or just the ones you want to give access to.
