### ISSUE TITLE
"Back to issues stream" goes to different project

### ISSUE THREAD

**Issue by Christilut** [getsentry/sentry#16776]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I get an email from Sentry about a new issue. I click the "View on Sentry" button in the email to go to the issue. Then I press the "Back to issues stream" arrow button and I'm taken to the issue stream of a different project.

The thing that I know that's different is that the second project has this checkbox:
![image](https://user-images.githubusercontent.com/3471363/73684579-c3290080-46c4-11ea-8ac9-2b55e5be49e9.png)
I'm not even sure what that checkbox means, but maybe it has some kind of influence on this bug.

## Steps to Reproduce

1. Open Sentry through email link
2. Click back arrow button
3. Notice you are in a different project

**Comment by doudejans** [comment]
I've found out how to reproduce this on my machine and will try to look into this.
Also, the recently posted issue #17560 seems to be about the same problem.
