### ISSUE TITLE
CaptureException getting fired by default

### ISSUE THREAD

**Issue by GauravJainOnline** [getsentry/sentry#16792]
Hi,

I have commented captureException at all places in my application and still I am getting exceptions logged in sentry. How do I turn it off by default.

**Comment by untitaker** [comment]
Can you tell us which SDK you are using?

**Comment by GauravJainOnline** [comment]
We are using it for Javascript SDK.

**Comment by untitaker** [comment]
I think this should answer your question: https://docs.sentry.io/platforms/javascript/#sdk-integrations
