### ISSUE TITLE
I get event ID as a response but no message is saved

### ISSUE THREAD

**Issue by karmux** [getsentry/sentry#1682]
If I send message from plain python script or Django then I get event ID as a response like message was successfully saved. When I go to dashboard then there is nothing and also database table is empty.

```
python3 /project/manage.py raven test
Client configuration:
  base_url       : http://sentry:9000
  project        : 2
  public_key     : 7244b94230b84c00bc62576f7c1d9a89
  secret_key     : 81718f3347064b2baad0fd720420d8c1

Sending a test message... Event ID was '6bed73258af0488aa21a13429a12b7cb
```

```
>>> from raven import Client
>>> client = Client('http://7244b94230b84c00bc62576f7c1d9a89:81718f3347064b2baad0fd720420d8c1@sentry:9000/2')
>>> client.captureMessage('Hello')
'fe71980d6dea45bc95f08ce4cceea334'
>>>
```
I looked into gunicorn and Django debug logs but saw nothing suspicious there. What could be the problem?

**Comment by dcramer** [comment]
If this is self hosted you likely have something misconfigured.

What version of Sentry?

**Comment by karmux** [comment]
@dcramer, yes, it's self hosted. Sentry is 7.7.0 from pip.

**Comment by dcramer** [comment]
It would be something with workers then. When it reports 200 OK it says "i have validated the message and put it into the queue". You should check worker logs and confirm nothing is misconfigured there.
