### ISSUE TITLE
Asana legacy integration crash on open

### ISSUE THREAD

**Issue by aliasbody** [getsentry/sentry#16838]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [X] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

When trying to access the asana legacy page we have the following error:
![imagem](https://user-images.githubusercontent.com/9455122/73926265-4619a900-48c7-11ea-8575-5b998669cc53.png)

And this is the XHR feedback:
```json
{
  "detail":"Internal Error",
  "errorId":"aeaf1fcbd11345018faf06211fc3dac5"
}
```

## Steps to Reproduce

1. Go to a project settings
2. Click on the Asana legacy integration on the bottom left bar

### What you expected to happen

Should be able to configure and use the asana integration

**Comment by webmozart** [comment]
I'm having the same problem. Is there any suggested solution?

**Comment by Sayorus** [comment]
Also interested in the solution

**Comment by webmozart** [comment]
This works for me since the upgrade to Sentry 10.

**Comment by Sebasch** [comment]
I have the same issue with on-premise Docker Version 10.1.0.dev0

**Comment by aliasbody** [comment]
The SaaS version still has the issue, don't know about the server version.

**Comment by BYK** [comment]
Have you tried [contacting our support](https://sentry.io/contact/support/) for this?
