### ISSUE TITLE
TV Dashboard

### ISSUE THREAD

**Issue by sul4bh** [getsentry/sentry#1689]
I found a TV Dashboard view hidden in the urls.py file. Are you guys planning to add a url to it anywhere in the UI?

**Comment by dcramer** [comment]
@sul4bh its something we had worked on and will definitely bring back, but I'm afraid that it's going to be completely broken soon. Likely when we bring it back it will be project specific or organization-wide.

**Comment by ArondeParon** [comment]
Any updates on this feature?
