### ISSUE TITLE
24 hour format not everywhere respected

### ISSUE THREAD

**Issue by vonox7** [getsentry/sentry#16897]
In https://sentry.io/settings/account/details/ i have enabled the "Use a 24-hour clock" setting.
But when highlighting in an issue-graph the first-seen or last-seen element, i get the 12-hour format:

![image](https://user-images.githubusercontent.com/621501/74087656-cb02ef00-4a8e-11ea-8070-d8d581e28b7a.png)

Note that each bar has the correct 24-hour format, which makes it much more confusing:

![image](https://user-images.githubusercontent.com/621501/74087670-dc4bfb80-4a8e-11ea-890b-703fedd09f6e.png)

## Expected behaviour
Respect the 24-hour setting everywhere. Apparently https://github.com/getsentry/sentry/pull/4530 hasn't fixed the whole issue.

**Comment by nbelzer** [comment]
I am able to reproduce this locally, will look in to this.
