### ISSUE TITLE
Add Configurable Date Format

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#1690]
The request has been brought up that the date format should be configurable and also show the timezone to clarify confusion between distributed teams, especially upon forwarding mail.

**Comment by dcramer** [comment]
I care less about a configurable date format than I do showing the timezone.

i.e. if the format is always like:

Jan 1 2015, 8:15pm PDT

I dont think anyone would really complain about that.

(this is what we do now on the new one, minus the timezone, as I couldnt figure out how to show that)

**Comment by mitsuhiko** [comment]
Not everybody is a fan of AM/PM I guess :)

**Comment by dcramer** [comment]
Yeah I agree. I think this is a reasonable thing to add, but won't consider it a blocker.

**Comment by matlac** [comment]
Is there any option to change date format from AM/PM to 24h?

**Comment by tkaemming** [comment]
@matlac - Yes, it's in your account settings under the "appearance" tab.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
