### ISSUE TITLE
Create *-foss repositories to track free software components

### ISSUE THREAD

**Issue by oxr463** [getsentry/sentry#16903]
## Summary

Create *-foss repositories and setup CI/CD to automatically push to these.

## Motivation

Per the [FAQ](https://forum.sentry.io/t/re-licensing-sentry-faq-discussion),

> The affected repositories are as follows:
>    https://github.com/getsentry/sentry 40
>    https://github.com/getsentry/sentry-plugins 11
>    https://github.com/getsentry/sentry-docs 1
>    https://github.com/getsentry/snuba/ 15
>    https://github.com/getsentry/semaphore 14
>    https://github.com/getsentry/onpremise 12
>    https://github.com/getsentry/docker-sentry 8
>    All Docker images produced by the repositories above

None of these repositories are free software any longer.

It would be nice to have official upstream versions instead of forks.

## Additional Context

- N/A

**Comment by BYK** [comment]
Sorry, this is not going to happen.
