### ISSUE TITLE
Slack Integration: Installation

### ISSUE THREAD

**Issue by okinospice** [getsentry/sentry#16902]
When i click in Install Slack, new windows pops up and there's error - https://prnt.sc/r04abb 

Logging in Slack doesn't help.

**Comment by okinospice** [comment]
Sentry in installed on a server

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.

Also check out our Slack installation guide before that please: https://develop.sentry.dev/integrations/slack/
