### ISSUE TITLE
Sentry Truck Factor

### ISSUE THREAD

**Issue by gavelino** [getsentry/sentry#1692]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Sentry** and obtained a value of **1**.

The developer responsible for this TF is:

David Cramer - author of 99% of the files 

To validate our results, we would like to ask **Sentry** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Sentry**?

(b) Do you agree that **Sentry** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **Sentry** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by dcramer** [comment]
The project would absolutely burn to the ground if I got hit by a bus. Fortunately there's no worries about me winning the lottery :)
