### ISSUE TITLE
Bundle gets successfully uploaded with "Internal Error"

### ISSUE THREAD

**Issue by minderov** [getsentry/sentry#17005]
**TL;DR:** Source map uploads with no errors, but the content is replaced by `{"detail": "Internal Error", "errorId": "..."}`

I am using Sentry on premise.

Command I run:
```
sentry-cli releases files XXXXX upload-sourcemaps path/to/folder
```

Output:
```
> Analyzing 2 sources
> Adding source map references
> Uploading source maps for release XXXXX

Source Map Upload Report
  Minified Scripts
    ~/index.android.bundle (sourcemap at index.android.bundle.packager.map)
  Source Maps
    ~/index.android.bundle.packager.map
* Closing connection 0
* Closing connection 0
```

The bundle shows up with 0 bytes size:
![image](https://user-images.githubusercontent.com/15854038/74372039-cdb35c00-4d8e-11ea-984f-4e3d347c1ce5.png)

The bundle's content, after uploading is (before uploading it looks normal):
```
{"detail": "Internal Error", "errorId": "7c97cbff08a14cd39e9fb8d09be9cdfd"}
```

Seems like some error has occurred somewhere, but I can't find any errors anywhere.

**Comment by kamilogorek** [comment]
I believe this is processing pipeline, not cli issue, so I transferred it here.

**Comment by agorf** [comment]
Hello. We're experiencing the same issue. We're running our own Sentry instance. Not sure if this has anything to do with it though.

**Comment by minderov** [comment]
> We're running our own Sentry instance. Not sure if this has anything to do with it though.

Agreed. The same problem appears when hosted on https://sentry.io

**Comment by agorf** [comment]
Not sure if it helps, but we've found that both artifacts are correctly uploaded for iOS through Xcode. So I'm not sure this is a sentry instance issue.

**Comment by HazAT** [comment]
So I just tried it on sentry.io and it works fine.
> Having a 0B file uploaded is expected when you use Hermes bundles.
> What's not expected that the code stays minified.

**Comment by Swatinem** [comment]
>     ~/index.android.bundle.packager.map

The `packager` suffix means that you probably have the wrong sourcemap. We are currently working on making this a bit more bullet-proof, by *this*, I mean the interaction between the gradle scripts of `react-native` and `sentry-react-native`. Finding the correct sourcemap to upload is apparently not as easy as expected :-(

Which versions of `react-native` and `sentry-react-native` do you have?

**Comment by minderov** [comment]
> Which versions of react-native and sentry-react-native do you have?

```json
"react-native": "0.61.5",
"@sentry/react-native": "^1.3.0"
```

**Comment by HazAT** [comment]
@minderov Are you running your own Sentry instance?

**Comment by minderov** [comment]
> @minderov Are you running your own Sentry instance?

Yes

I have tried it on [sentry.io](https://sentry.io) and the bundle gets uploaded as 0 bytes as well. Although, judging by your earlier quote, that is actually an expected behaviour for Hermes?

**Comment by HazAT** [comment]
Yes this is expected, make sure your instance is running latest master otherwise we do not support Hermes yet.

**Comment by HazAT** [comment]
I think there is nothing to do here anymore, if I am wrong, feel free to post again.
