### ISSUE TITLE
GitHub authentication: OAuth credentials in query parameters have been deprecated

### ISSUE THREAD

**Issue by IvanAnishchuk** [getsentry/sentry#17023]
## Important Details

How are you running Sentry?

* [X] On-Premise docker [Version 10.1.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description
We've been receiving notifications like this for a while:
 ```Hello there!
On February 11th, 2020 at 17:32 (UTC) your application (Sentry) used its `client_id` and `client_secret` (with the User-Agent sentry/10.1.0.dev0 (https://sentry.io)) as part of a set of query parameters to access an endpoint through the GitHub API:
https://api.github.com/user/[redacted]
Please use Basic Authentication instead as using OAuth credentials in query parameters has been deprecated and will be removed July 1st, 2020.
Depending on your API usage, we'll be sending you this email reminder at most once every 3 days.
Visit https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters for more information.
Thanks,
The GitHub Team 
```

Unless I'm mistaken it has to do with this [github plugin code](https://github.com/getsentry/sentry/blob/f96d1fc138155ec51b2f35a0be0355cf908a83fd/src/sentry_plugins/github/client.py#L47-L51): 

Apart from the [deprecation link above](https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters) GitHub team also published [this instruction](
https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/) (which also mentions brownouts scheduled for May 15 and June 12)

## Steps to Reproduce

1. Use sentry with GitHub SSO authentication
2. Check email every three days
3. Wait for it to stop working on Canada Day

### What you expected to happen

We originally noticed it on 9.x and I naturally assumed everyone knows about it and the fix is already released however for some reason I couldn't find a single mention anywhere around sentry. Hence this issue.

### Possible Solution
Replacing the method in question with something like this should be enough according to the instruction

```python
    def request_no_auth(self, method, path, data=None, params=None):
        from requests.auth import HTTPBasicAuth
        if params is None:
            params = {}

        auth = HTTPBasicAuth(
            settings.GITHUB_APP_ID,
            settings.GITHUB_API_SECRET,
        )
        return self._request(method, path, auth=auth, data=data, params=params)
```

(the helper from requests is not the only option but it's at least well-known and doesn't require adding any py2/py3 compatibility code, can always be replaced with some simple encode/base64/decode chain)

**Comment by IvanAnishchuk** [comment]
Ok, I went ahead a created a PR. Please review.

**Comment by dashed** [comment]
Ref: https://github.com/getsentry/sentry/pull/17091

**Comment by rrati** [comment]
Has this issue been fixed?  The linked PR seems to spider out to numerous other PRs which don't seem to have merged, so it's a little unclear if this issue has been fixed.

**Comment by BYK** [comment]
This was fixed in the following PRs:

- #17255
- #17284
- #17216
- #17178
