### ISSUE TITLE
How to filter issues that are events more than 1 occurance

### ISSUE THREAD

**Issue by cullsin** [getsentry/sentry#17052]
Hello,

In the dashboard, I can see all the issues and most of them are occurred once. I want to skip those issues. Is there any way to filter based on number of events. Is it possible to send only those events to Jira so that we can fix it.

Thanks.

**Comment by BYK** [comment]
You can add `timesSeen:>1` to your search query. You can also use the query builder to set this:
![image](https://user-images.githubusercontent.com/126780/97079285-4e537900-15fb-11eb-8841-b7ba05918f46.png)
