### ISSUE TITLE
Alerts are not rendered correctly

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1708]
- status checks seem to not render all at once (i.e. if theres two, one renders, I close it, and then another renders)
- https://www.dropbox.com/s/255497sv2yrm6ym/Screenshot%202015-08-09%2022.06.18.png?dl=0

**Comment by dcramer** [comment]
part of this is still on you @ckj (the checkmarks)

@benvinegar the status checks problem seems to be a JS bug

**Comment by ckj** [comment]
checkmarks are gone
