### ISSUE TITLE
Nextjs TypeScript source maps not being associated correctly.

### ISSUE THREAD

**Issue by NiluK** [getsentry/sentry#17096]
Hi Sentry team and community, we're in the process of evaluating Sentry and have run into an issue where our NextJs source maps do not seem be associating correctly with the code. Any direction or help would be appreciated. 

### The problem 

We have a piece of code that throws an error: 

```
const throwError = () => {
  throw new Error('An Error has been thrown');
};
```

A button onClick calls this function. Sentry catches the error fine and we have logs generating on the Sentry dashboard(👏) . 

The issue seems to be that the Typescript source maps are not being rendered properly on the sentry dashboard:

What we're expecting to get:

![Sentry Expected Result 1](https://puu.sh/FbObE/219b557d76.png)

![Sentry Expected Result 2](https://puu.sh/FbOcH/c66342150a.png)

What we're getting:
![Sentry actual result](https://puu.sh/FbO90/91af17f32b.png)

### Artefacts

The current artefacts looks like this:

![Artefacts Current](https://puu.sh/FbOgj/845f6fa5fa.png)

However the previous Artefacts looked like this

![Previous Artefacts](https://puu.sh/FbOi2/b7ebf445e0.png)

So I am fairly sure one of those would have given the correct result if the path was the issue. 

## What I've tried so far

I have tried 

- Uploading viia HTTP
- Uploading via the Sentry CLI
- Uploading via the Sentry Webpack Plugin

and have no results.

I'm happy to provide more info if needed. 

Thanks
Nilu

**Comment by toltarisa** [comment]
@NiluK did you come up with a solution ?

**Comment by NiluK** [comment]
Unfortunately no and we've decided to move away from our Sentry trial for the time being.

**Comment by BYK** [comment]
Pinging both @scefali and @kamilogorek as I don't know where would be the culprit reside.

**Comment by kamilogorek** [comment]
Artifacts have to be uploaded `~/` prefix so they can match on any host (including relative url that you have here - `/`). Once changed, it'll work out of the box.

**Comment by BYK** [comment]
@kamilogorek - thanks a lot! Do we document this somewhere?

**Comment by kamilogorek** [comment]
https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/#using-the-
https://docs.sentry.io/product/cli/releases/#managing-release-artifacts
https://docs.sentry.io/platforms/javascript/sourcemaps/multiple-origins/

**Comment by BYK** [comment]
Then closing :)
