### ISSUE TITLE
Investigate deploying getsentry + sentry via Platter

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1710]
I believe Sentry fully works, but the getsentry codebase provides some additional complexity.

This may or may not be needed as we move to Docker infra, so assume this ticket is more about exploring if it's worthwhile to invest the time.

Primary concern right now is our slow release times (~15m due to pip slowness + parallel packaging)

/cc @mitsuhiko @mattrobenolt @tkaemming

**Comment by mattrobenolt** [comment]
First pass is making pip a bit faster with https://github.com/pypa/pip/pull/3066

**Comment by dcramer** [comment]
Going to close this out as I dont think we need this anymore (and the pip stuff will get us a long ways until Docker is in place).
