### ISSUE TITLE
The configured event stream backend does not need a forwarder process to enqueue post-process tasks. Exiting

### ISSUE THREAD

**Issue by jiankunking** [getsentry/sentry#17157]
When I deployed the post-process-forwarder to the kubernetes cluster, the post-process-forwarder always exit.The specific log information is as follows

`01:50:53 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.

01:51:02 [INFO] sentry.plugins.github: apps-not-configured
01:51:02 [DEBUG] sentry.digests: Validating Redis version…
01:51:02 [DEBUG] sentry.tsdb.redis: Validating Redis version…
The configured event stream backend does not need a forwarder process to enqueue post-process tasks. Exiting…`

Environment variable information:
`SNUBA=http://snuba-api:1218 

SENTRY_REDIS_HOST=10.138.0.65 
SENTRY_REDIS_PORT=6379 
SENTRY_MEMCACHED_HOST=10.138.0.65 
SENTRY_MEMCACHED_PORT=11211 
SENTRY_EMAIL_HOST=10.138.0.65 
SENTRY_SECRET_KEY=tLC8fz7W2NF%^M%sPA]5+yXR6I-vb9 
SENTRY_DB_NAME=postgres 
SENTRY_DB_USER=sentry 
SENTRY_DB_PASSWORD=mysecretpassword 
SENTRY_POSTGRES_HOST=10.138.0.65 
SENTRY_POSTGRES_PORT=5432 
DEFAULT_BROKERS=10.138.0.65:9092 
C_FORCE_ROOT=true`

**I also modified the config.yml, sentr.conf.py files**

Start the command:

`sentry run post-process-forwarder --loglevel debug --commit-batch-size 1`

What did I configure wrong?

**Comment by hisabimbola** [comment]
I am also having this issue. Were you able to fix it @jiankunking ?

**Comment by jiankunking** [comment]
> I am also having this issue. Were you able to fix it @jiankunking ?

I haven't solved it yet。

I also went to the forum to ask questions. You can refer to it。
[The configured event stream backend does not need a forwarder process to enqueue post-process tasks. Exiting
](https://forum.sentry.io/t/the-configured-event-stream-backend-does-not-need-a-forwarder-process-to-enqueue-post-process-tasks-exiting/8930/3)

**Comment by jiankunking** [comment]
> I am also having this issue. Were you able to fix it @jiankunking ?

I know how to solve this problem。
copy sentry.conf.py to /etc/sentry

**Comment by hisabimbola** [comment]
I just checked. For me the file is present. I would assume it's not picking it up

**Comment by hisabimbola** [comment]
Oh yeah, that fixed it. Thanks
