### ISSUE TITLE
Unclear instructions for GitLab integration setup

### ISSUE THREAD

**Issue by Nowaker** [getsentry/sentry#17202]
> Step 1: Create a Sentry App in GitLab

> To configure GitLab with Sentry, you will need to create a Sentry app in your GitLab instance.

> You'll also need to be a maintainer or owner in GitLab. Projects owned by users are not supported.

> Navigate to the **User Settings** section of your GitLab instance.

> In the sidebar, select 'Applications'.

Did the author mean `https://gitlaburl/admin`? If so, this is called `Admin Area`:

![image](https://user-images.githubusercontent.com/611746/75067118-f71c6800-54b1-11ea-8c30-4d24449abe9b.png)

Also, providing a direct URL won't hurt. Why not something like this:

> Navigate to the Admin Area of your GitLab instance, then select "Applications" in the sidebar. (Or navigate directly to /admin/applications/new)

**Comment by markstory** [comment]
> Did the author mean https://gitlaburl/admin? If so, this is called Admin Area:

No I meant the settings for your user account, like those found in https://gitlab.com/profile/applications
