### ISSUE TITLE
Debugger patch context needs corrected

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1722]
- It should only patch once, likely at runtime
- A thread-localized collector needs installed to record calls for the current executing context

**Comment by dcramer** [comment]
Totally forgot we use a worker pool. Going to be really tough to link up Redis requests with parent request.

**Comment by dcramer** [comment]
I think we'll need to make Nydus have some kind of local refs. Realistically connections should probably be thread safe, so we can just add native instrumentation support.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
