### ISSUE TITLE
Sentry Azure DevOps integration ends in infinite login loop

### ISSUE THREAD

**Issue by kgrimsby** [getsentry/sentry#17233]
I'm trying to add Sentry integration for Azure DevOps. When adding, I get prompted by login screen (MS SSO). After logging in I get redirected back to the same login over and over.

Does anyone know why this happens? Is this permissions in Azure DevOps?

/Kristian

**Comment by Perfect-Web** [comment]
i have the same issue

**Comment by BYK** [comment]
Have you tried [contacting our support](https://sentry.io/contact/support/) for this?
