### ISSUE TITLE
SSL 

### ISSUE THREAD

**Issue by chaffeqa** [getsentry/sentry#17235]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Originally logged in https://github.com/getsentry/sentry-cli/issues/666

Getting SSL error on Githhub action sourcemap upload for webpack plugin.

When I try locally, it works fine, also seems to work fine on jenkins, but on github actions seems to fail.

## Steps to Reproduce

1. Webpack compile on github actions

```Error: Command failed: /app/node_modules/@sentry/cli/sentry-cli releases new 6b46fb182dfe2cb986b62eed878e4088d00603a1
error: API request failed
  caused by: [60] SSL peer certificate or SSH remote key was not OK

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:311:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: '/app/node_modules/@sentry/cli/sentry-cli releases new 6b46fb182dfe2cb986b62eed878e4088d00603a1'
}
```

### What you expected to happen

Should successfully upload similar to other standard CI / workstation environments

### Possible Solution

Already tried a few debuggin approaches to SSL on github actions:

```
        git config --global http.sslverify false
        openssl  verify  -verbose  /etc/ssl/certs/ca-certificates.crt
        > /etc/ssl/certs/ca-certificates.crt: OK
        touch $HOME/.curlrc
        echo "insecure" >> $HOME/.curlrc
````

**Comment by BYK** [comment]
I don't know why this issue was filed here but it seems to be fixed over at getsentry/sentry-cli#666.

If you can provide more details around what you need us to do, happy to reopen and look into it.
