### ISSUE TITLE
[feature request] per-environment rate limiting

### ISSUE THREAD

**Issue by caleb15** [getsentry/sentry#17318]
## Summary

There is per-project rate limiting but no per-env rate limiting. Per-environment rate limiting would a nice addition.

## Motivation

Per-env rate limiting would be nice because in a lower environment you might get a very low amount of incidents on average with occasional giant spikes when something goes wrong and spams sentry. In this case you would want to rate limit the lower environment so that it doesn't eat up the quota of the higher environment. 

## Additional Context

Currently we use seperate projects for each environment. Ideally we would have one project with seperate environments, but we have been having problems with issue spam in our lower environments. If we moved to seperate environments we wouldn't be able to rate-limit specifically our lower environments anymore.

Of course we could also fix the issues that are generating the sentry spam, but eventually there will be another issue that comes along and causes sentry spam again.

**Comment by BYK** [comment]
I think you can achieve the same thing by generating multiple keys per project and rate limiting per key (DSN): https://docs.sentry.io/product/accounts/quotas/manage-event-stream-guide/#6-rate-limiting

LMK if this works well enough for you as I don't think we would be adding new rate limiting options soon.
