### ISSUE TITLE
Handling issues from JavaScript files that are GZIPED

### ISSUE THREAD

**Issue by shiroganee** [getsentry/sentry#17320]
Greetings,

I've quite an issue with how Sentry is handling files and reporting issues in them when they are gzipped. As of now instead of seeing sourcemaped source, i'm seeing gibberish content that means absolutely nothing (not even regular JS file).
I assume it is due to fact that JS file that has issue is served through S3 AWS which is prezipped with GZIP. Is there a way to tell Sentry "hey mate, this is gzip, firstly decode it"?

Best regards

**Comment by BYK** [comment]
Is this on sentry.io or self-hosted Sentry? If it is the latter, which version?

**Comment by BYK** [comment]
I think you can just use HTTP transport compression instead. Right now I don't think we will support this scenario.
