### ISSUE TITLE
error: project not found

### ISSUE THREAD

**Issue by leoyb** [getsentry/sentry#17342]
When I execute the command：
`sentry-cli releases -o sentry -p niumei-admin files dev@0.1.0 upload-sourcemaps dist/js --url-prefix ~/js`

 I get the error:
`error: project not found`

**run 'sentry-cli info' show the info:**
```
Sentry Server: ***
Default Organization: sentry
Default Project: niumei-admin

Authentication Info:
  Method: Auth Token
  User: ***
  Scopes:
    - event:admin
    - event:read
    - member:read
    - org:read
    - project:read
    - project:releases
    - team:read
    - project:write
```

**run 'sentry-cli projects list' show the info**
```
+----+--------------+--------+--------------+
| ID | Slug         | Team   | Name         |
+----+--------------+--------+--------------+
| 1  | internal     | Sentry | Internal     |
| 4  | niumei-admin | Sentry | niumei-admin |
+----+--------------+--------+--------------+
```

**sentry version:**
```
sentry-cli: 1.51.1
@sentry/browser: 5.12.4
@sentry/integrations: 5.12.4
```

**Comment by hitris** [comment]
Did project 'niumei-admin' has been created in UI? Seems that project is not exist.

**Comment by leoyb** [comment]
@hitris 'niumei-admin' project has been created

![image](https://user-images.githubusercontent.com/10185166/75422588-e66b6680-5977-11ea-93de-51886c6bd9f5.png)

**Comment by hitris** [comment]
> @hitris 'niumei-admin' project has been created
> 
> ![image](https://user-images.githubusercontent.com/10185166/75422588-e66b6680-5977-11ea-93de-51886c6bd9f5.png)

I created a new release, then imitate your command with my own Organization and Project , it works well ! 
So it could be an out-of-command error

**Comment by leoyb** [comment]
@hitris Thank you for your reply. The problem has been fixed. It was found that the URL was filled incorrectly because I configured HTTPS

**Comment by mattrobenolt** [comment]
Good teamwork. 👏 👏
