### ISSUE TITLE
v8 redesign says "Unable to update events. Please try again" and 401 on the console

### ISSUE THREAD

**Issue by mdaniel** [getsentry/sentry#1737]
1. Navigate to an event on `app.getsentry.com`
1. Change the URL from `app.getsentry.com` to `beta.getsentry.com`
1. Observe that the page loads successfully
1. Observe that after a few seconds, a red bar "Unable to update events. Please try again." appears

The console contains the following text:
![screen shot 2015-08-10 at 5 52 05 pm](https://cloud.githubusercontent.com/assets/22526/9187737/b2126fd6-3f88-11e5-9f7b-8a470add4d7f.png)

**Comment by dcramer** [comment]
Refs GH-1675
