### ISSUE TITLE
Phabricator integration: search by task ID does not work

### ISSUE THREAD

**Issue by tiguchi** [getsentry/sentry#17373]
## Important Details

* [x] Saas (sentry.io)

## Description

I linked my projects with a self-hosted Phabricator instance. When I want to link a Sentry event with an existing Phabricator task, search by Phabricator task ID (e.g. `T1234`) does not work. The search result is empty.

## Steps to Reproduce

1. Activate Phabricator integration
2. Link Sentry event with Phabricator task
3. Switch to "Link" tab
3. Enter Phabricator task ID in "Task" search field

### What you expected to happen

Searching by Phabricator task ID should give me non-empty, correct results

### Workaround

The only way to get the correct task result at the moment is by entering keywords from the Phabricator task title.

This may be also a Phabricator API bug, and search by Phabricator task ID needs to be done through a different request parameter or endpoint?

**Comment by rhcarvalho** [comment]
@getsentry/sns FYI

**Comment by dashed** [comment]
@rhcarvalho The @getsentry/ecosystem team owns this.

**Comment by Christinarlong** [comment]
Hi, unfortunately we don't support plugins (including Redmine) anymore so we won't get to this issue, but we’re always open to community contributions.
