### ISSUE TITLE
PHP Integration

### ISSUE THREAD

**Issue by oktaykalfa** [getsentry/sentry#17391]
Hello, i have installed sentry/sdk via:

composer require sentry/sdk:2.1.0

then i have added this line to my project

\Sentry\init([‘dsn’ => ‘https://mycode@sentry.io/myprojectnumber’]);

Lastly, i added this line to test sentry

throw new Exception(“TEST sentry.”);

But nothing is happened. PHP side is not working but Javascript side is working well. This is just ruined all of my day and still working on it.

This is how i’m installed & my code block :

https://aws1.discourse-cdn.com/standard10/uploads/sentry/original/2X/8/8fa306b719242dd05eafee01abbe64ca9923a6a3.png

Thanks for helping.
Regards.

**Comment by pierredup** [comment]
The PHP SDK doesn't register an exception listener to automatically send exceptions, you need to manually catch the exception and send it to Sentry

```php
try {
    throw new Exception("TEST sentry.");
} catch (Exception $exception) {
    \Sentry\captureException($exception);
}
```

**Comment by oktaykalfa** [comment]
> 
> 
> The PHP SDK doesn't register an exception listener to automatically send exceptions, you need to manually catch the exception and send it to Sentry
> 
> ```
> try {
>     throw new Exception("TEST sentry.");
> } catch (Exception $exception) {
>     \Sentry\captureException($exception);
> }
> ```

@pierredup thanks, i found the problem. it was related with the cacert.pem certification file.
