### ISSUE TITLE
bitbucket-server commit-history not working (while bitbucket-saas works well)

### ISSUE THREAD

**Issue by scuben** [getsentry/sentry#17398]
## Important Details

How are you running Sentry?
* Saas (sentry.io)

## Description

I looked forward to using the new bitbucket-server integration. As this is now available I tested it out and found the following problem:

Using the `sentry-cli` (or api) to create/finalize releases, add deployments and commits there is a difference in bitbucket (saas) and bitbucket-server. The releases/deploys with bitbucket (saas) do catch the commit history but bitbucket-server does not.

## Steps to Reproduce

1. set up two identical projects - one with bitbucket (saas) and one with bitbucket-server
2. `sentry-cli releases new -p project-slug release-slug`
3. `sentry-cli releases finalize release-slug`
4. `sentry-cli releases set-commits release-slug --commit 'repo-slug@sha1'`
5. `sentry-cli releases deploys release-slug new --env prod`

### What you expected to happen

I expected the bitbucket-server integration to work like bitbucket (saas) and catch the repo history with its integration.

**Comment by BYK** [comment]
@scuben is this still an issue or resolved with #17403?

**Comment by scuben** [comment]
@BYK I honestly did not check that since. But I assume its okay now so we'll close that for now.

**Comment by BYK** [comment]
@scuben feel free to submit a new issue if this persists.
