### ISSUE TITLE
Event migration 9.1.2 -> 10

### ISSUE THREAD

**Issue by buffcode** [getsentry/sentry#17422]
## Important Details

How are you running Sentry?

* [X] On-Premise docker [Version 9.1.2]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

I followed the migration guide, alongside all fixes and workaround and managed to get to the actual migration routine. Sentry tries to process all existing postgres events but fails to (for every event):

```
An error occured while trying to instert the following event: <sentry.eventstore.models.Event object at 0x7f2f08e552d0>
.----
insert() takes at least 8 arguments (8 given)
[...]
Event migration done. Migrated 0 of 197988 events.
```

## Steps to Reproduce

1. Have a 9.1.2 onpremise setup and have event data
2. Upgrade to 10 (dev-master), run `install.sh` etc.

### What you expected to happen

Migration scripts succeeds and I have all event data in the new version.

### Possible Solution

Error message suggests a syntax error?

**Comment by BYK** [comment]
This is the culprit: #17021 //cc @tkaemming 

Working on a fix.

**Comment by buffcode** [comment]
Nice! How would I re-apply the specific migration which backfills the eventstream?

I tried `django migrate sentry 0024_auto_20191230_2052`, but this will fail due to foreign key constraints / missing tables when rolling back to this migration.

**Comment by BYK** [comment]
@buffcode I think you can try `django migrate sentry 0024_auto_20191230_2052 --fake`?

**Comment by BYK** [comment]
@buffcode I fear I have bad news for you if you don't have a back up of your old DB. There is a way to reapply this migration but since `0027` drops the table that events are stored, even if you go back, you cannot get the event data back :(

**Comment by buffcode** [comment]
I can confirm that with these fixes I was able to import existing data from 9.1.2 / Postgres 9.5 into Sentry 10.

Thanks alot!

**Comment by BYK** [comment]
Thank _you_ for the report @buffcode and sorry for the disruption we caused. We've added a light protection into the migration and I'm planning to add auto-backup to the install script over at getsentry/onpremise :)

**Comment by cb109** [comment]
Are these fixes already part of the onpremise update script/docker image? I am currently trying to upgrade from 9.1.2 to 10.x and my Events are still lost.

**Comment by BYK** [comment]
@cb109 yeah, these are merged to master so you should not have any issues if you are using the latest master of this repo (and not using a specific `SENTRY_IMAGE` override)
