### ISSUE TITLE
Sentry beta breakpoint between mobile and desktop renders awkwardly.

### ISSUE THREAD

**Issue by kitsunde** [getsentry/sentry#1743]
Basically all the stuff that's supposed to into the right column ends up not rendering properly. I'm on chrome 44.

<img width="833" alt="screenshot 2015-08-12 01 35 40" src="https://cloud.githubusercontent.com/assets/48965/9205098/ca37ec3e-4092-11e5-837c-805214dc7777.png">
<img width="851" alt="screenshot 2015-08-12 01 36 06" src="https://cloud.githubusercontent.com/assets/48965/9205099/ca8f05e6-4092-11e5-91b1-12cbadcccd7b.png">

**Comment by ckj** [comment]
Fixed in latest release.
