### ISSUE TITLE
Allowed Domains doesn't seem to work Immediately - It takes very long possibly hours and difficult to identify

### ISSUE THREAD

**Issue by modernwarfareuplink** [getsentry/sentry#17454]
Context:
Tried setting the allowed domains to other random domain and raised exception from my domain, but the events are still coming to my dashboard. Any idea why?

Sentry server ->  Saas (sentry.io)

## Description

Events which should be blocked from other domains not listed in allowed domains of that project is still showing up in the dashboard

## Steps to Reproduce

1. Set the allowed domains of your project to some random domain, say xyz.com
2. Then trigger exceptions from your domain
3. Expected behaviour is to drop the event from your domain as it does not match the allowed domain

Good items to include here include:
No errors or logs, the behaviour is strange.
1. Checked if the project DSN and the place where I have added the allowed domains is same.

## Expected
Events should have been filtered out, if Referrer or Origin does not match the ones in allowed domain of that project.

## Possible Solution
Fix error at the event filtering part of the sentry server (sentry.io)

**Comment by BYK** [comment]
@modernwarfareuplink are you still experiencing this?

**Comment by modernwarfareuplink** [comment]
Nope, didn't try post that, have already done the required changes. Not sure if this still exists. Thanks for checking this out. Hope you are safe.
