### ISSUE TITLE
Inconsistent handling of release version in frontend

### ISSUE THREAD

**Issue by simonihmig** [getsentry/sentry#17474]
## Important Details

How are you running Sentry?

* [ ] On-Premise docker [Version xyz]
* [x] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Due to some other issue related to `sentry-symfony` (https://github.com/getsentry/sentry-symfony/issues/323), the release tag is sent as something like `1.13.0@`. While this is not ideal for sure, it should still be handled gracefully and consistently.

## Steps to Reproduce

When viewing the event list of an issue in the sentry frontend, the release tag is displayed correctly:

![image](https://user-images.githubusercontent.com/1325249/75974087-85431600-5ed6-11ea-957d-1a21abea5710.png)

But when clicking an that particular event, the release information is not shown:

![image](https://user-images.githubusercontent.com/1325249/75975506-ebc93380-5ed8-11ea-9bdc-dfa548fe3cc9.png)

### What you expected to happen

I would expect `1.13.0@` to show up.

### Possible Solution

Handle this consistently in the frontend, and show the release information as it is sent.

**Comment by matejminar** [comment]
Thank you
