### ISSUE TITLE
Support for explicit tag syntax in search bar

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry#17505]
When filtering issues by tag using the [explicit tag syntax](https://docs.sentry.io/workflow/search/?platform=node#explicit-tag-syntax) `tag[name]:value`, the search autocomplete box reports the tag as being invalid:

![image](https://user-images.githubusercontent.com/88819/76099915-23fd6e80-5fcc-11ea-9030-19b69f0de501.png)

Expected the component to behave the same as with the implicit tag syntax:

![image](https://user-images.githubusercontent.com/88819/76100469-fc5ad600-5fcc-11ea-8288-1a279c62f26b.png)

---

 Run into this when investigating #17502.

**Comment by rhcarvalho** [comment]
@priscilawebdev @matejminar do you think you could help me with this?

**Comment by priscilawebdev** [comment]
@rhcarvalho yes sure! let's talk about it when you have time 😉

**Comment by priscilawebdev** [comment]
@rhcarvalho  Please see: https://github.com/getsentry/sentry/pull/17507#issuecomment-597021286

I believe it's related to this issue

**Comment by rhcarvalho** [comment]
This is still reproducible.

Example:
`tags[browser]:"Firefox 84.0"` => Invalid tag
`browser:"Firefox 84.0"` => ok (lists known tag values)

![image](https://user-images.githubusercontent.com/88819/104170168-fe699e80-5400-11eb-8d9c-c8b88b144710.png)

**Comment by priscilawebdev** [comment]
just added this issue to our backlog. We will look into this soon 😉

**Comment by shellmayr** [comment]
Closing - this functionality works in the current version of the UI.
