### ISSUE TITLE
Jira Server Integration: 'invalid request' message but no additional information

### ISSUE THREAD

**Issue by corporalaris** [getsentry/sentry#17512]
When trying to follow the docs to integrate our on-premise jira with on-premise sentry, I just get a 'invalid request' message after approving the OAUTH token within Jira. How am I supposed to troubleshoot this? There's no information given about what the issue is or how to reconcile it.

**Comment by markstory** [comment]
You should check the logs for both Jira and sentry. There should be a log entry in sentry giving you a bit more detail but not much as Jira is pretty terse in why oauth fails.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
