### ISSUE TITLE
Faraday::SSLError - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by th3m4ri0** [getsentry/sentry#1752]
Hi everyone,
I recently noticed I stopped getting errors from a production application. Which is good, eh ?
...yeah. So I check the log, and notice that events are struggling to make it to our sentry server.
Here's what running the test task returns.
```
$ heroku run rake raven:test -r production
Running `rake raven:test` attached to terminal... up, run.8933
Digest::Digest is deprecated; use Digest
Starting up a new ElasticSearch client with https://*******:**********@*********-********.us-east-1.bonsai.io
Digest::Digest is deprecated; use Digest
** [Raven] Raven 0.14.0 ready to catch errors
Sending a test event:

-> ** [Raven] Unable to record event with remote Sentry server (Faraday::SSLError - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed)
-> ** [Raven] /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:920:in `connect'
-> ** [Raven] /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:920:in `block in connect'
-> ** [Raven] /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
-> ** [Raven] /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:101:in `call'
-> ** [Raven] /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
-> ** [Raven] /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:920:in `connect'
-> ** [Raven] /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
-> ** [Raven] /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:852:in `start'
-> ** [Raven] /app/vendor/ruby-2.1.5/lib/ruby/2.1.0/net/http.rb:1369:in `request'
-> ** [Raven] /app/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:80:in `perform_request'
-> ** [Raven] /app/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.0/lib/faraday/adapter/net_http.rb:39:in `call'
-> ** [Raven] Failed to submit event: ZeroDivisionError: divided by 0
-> event ID: 4defd0863e45aa6180c***********

Done!
```

Here's the Gemfile if it can be of any help :
```ruby 
source 'https://rubygems.org'
ruby '2.1.5'

gem 'rails', '4.1.4'
gem 'puma'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Activeadmin (/admin)
gem 'activeadmin', github: 'gregbell/active_admin'
gem 'devise'
gem 'jquery-ui-rails',      '~> 4.2.1'
gem 'active_admin_editor'
gem 'activeadmin-extra', github: 'stefanoverna/activeadmin-extra'
gem 'active_skin'
gem 'chosen-rails'


# Assets upload
gem "fog", "~> 1.3.1"
gem 'carrierwave'
gem 'mini_magick'

# LESS files compilation
# gem 'therubyracer'
# gem 'less-rails'
gem 'sass-rails'
gem 'bootstrap-sass', '~> 3.3.5'

gem 'rails-i18n', '~> 4.0.0'

gem 'elasticsearch-model'
# Searchkick for Elasticsearch API
gem 'searchkick'
gem 'friendly_id', '~> 5.0.0'

# Faker for seeds
gem 'faker', github: 'stympy/faker'

group :production do
    # Postgres
    gem 'pg'
    # Sentry bug reports
    gem "sentry-raven", github: 'getsentry/raven-ruby'
    # Bonsai support
    gem 'bonsai-elasticsearch-rails'
    # Heroku support
    gem 'rails_12factor'
end

group :development do
    gem 'sqlite3'
    gem 'spring'
    gem 'pry'
end
```

Any idea ?

**Comment by dcramer** [comment]
@th3m4ri0 what OS?

**Comment by th3m4ri0** [comment]
Running on Heroku's cedar-14 stack so Ubuntu 14.04 ([says the documentation](https://devcenter.heroku.com/articles/cedar#base-technology))

**Comment by dcramer** [comment]
Also just to confirm, this is getsentry.com?

**Comment by th3m4ri0** [comment]
Yes, self-hosted on our own server.

**Comment by dcramer** [comment]
@th3m4ri0 by self-hosted you mean *not* getsentry.com then? If it's self hosted its possible you need to add your certificate to the local store. We removed our shipped certs (though at least in many situations they werent used). You could also try downgrading raven-ruby to a pinned release to see if that helps.

**Comment by dcramer** [comment]
Closing this but feel free to re-open if you believe it to be an issue on our side (though alternatively this is raven-ruby related)

**Comment by xiaosongmu** [comment]
I"m having the same problem, and the setup is also self-hosted with ruby client. I'm really confused:

I can visit Sentry via the browser (https://sentry.domain.com) and it works, with chrome showing the correct certificate chain. The root is AddTrust. 

But the ruby client, after running rake raven:test says:
`-> ** [Raven] Unable to record event with remote Sentry server (Faraday::SSLError - SSL_connect returned=1 errno=0 state=error: certificate verify failed)
-> ** [Raven] /Users/xiaosongmu/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
-> ** [Raven] /Users/xiaosongmu/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:933:in `connect'
-> ** [Raven] /Users/xiaosongmu/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
-> ** [Raven] /Users/xiaosongmu/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:852:in `start'
-> ** [Raven] /Users/xiaosongmu/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/net/http.rb:1398:in `request'
-> ** [Raven] /Users/xiaosongmu/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
-> ** [Raven] /Users/xiaosongmu/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
-> ** [Raven] /Users/xiaosongmu/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
-> ** [Raven] /Users/xiaosongmu/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
-> ** [Raven] /Users/xiaosongmu/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
-> ** [Raven] /Users/xiaosongmu/.rvm/gems/ruby-2.3.1/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
-> ** [Raven] Failed to submit event: ZeroDivisionError: divided by 0`

Any idea why?

**Comment by dcramer** [comment]
You can pass ssl_ca_file to configuration if need be. Minor personal note, DigiCert has worked extremely well for us at Sentry.
