### ISSUE TITLE
Ways to block errors that bypass Sentry JS configuration

### ISSUE THREAD

**Issue by dryoma** [getsentry/sentry#17521]
## Summary

We'd like to have features similar to `ignoreErrors` and `dedupe()` in the UI on sentry.io, possibly with the ability to fine-tune.

## Motivation

There are cases when errors bypass a project's Sentry initialization code. This might happen either due to [possible bugs in Sentry code](https://github.com/getsentry/sentry-javascript/issues/2377), or for some other reason, like when a user agent decides it doesn't want to load the script with that initialization code or to run it for some reason. In any case, features like `ignoreErrors`, `beforeSend()`, and `dedupe()` become useless against such errors, and in some cases errors like that generate a lot of events which hurts a client's quota and floods their email/chats with notifications. 

Aside from the Known Crawlers/Legacy Browsers settings, the only way to fight that is the IP filter in the UI. Which might not be enough (the error may not be limited to certain IPs/ranges) and might hurt in a long run. So it would be really nice to have the idea to somehow extend the filtering in the UI on sentry.io to make it more effective and flexible.

## Additional Context

The most recent example: some time ago we had a lot of events under the "Illegal Invocation" error. After looking into it we, [as well as other devs](https://github.com/aFarkas/lazysizes/issues/520), came to the conclusion that the error is coming from Facebook's crawler that in order to create a preview parses a page in some kind of limited environment, which causes the error. So we ended up adding the code in our `beforeSend()` that, when it meets the error like that, checks if the IP address is one of Facebook's addresses and if it is, doesn't let the error to get sent.

The problem is, recently the rate for that error skyrocketed to the values much higher than ever before. The crawler now appears to not load our Sentry init JS that defines that `beforeSend()` hook, or it loads it, but doesn't run it. In any case, the events bypass our configuration, where they would be filtered out, and affect our quota in the most unpleasant way. Here is the link to the issue: https://sentry.io/organizations/policeone/issues/978597516/ We can see that [the IP is still Facebook's](https://www.whois.com/whois/173.252.95.9), which should be the signal for our JS code to filter the error out, but the error is still there, and none of the tags/Extras that our code sets is present in the event data.

**Comment by BYK** [comment]
We offer filter by error message and filter by issue on the Business tier: https://docs.sentry.io/product/accounts/quotas/#filter-by-error-message
