### ISSUE TITLE
Non-obvious how to add comments

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1753]
We have the activity tab, but people seem to struggle to find commenting there.

We could easily add an "Add Comment" action, but ideally you'd also know when there are comments, not just how to add more.

**Comment by dcramer** [comment]
Plan is to change Activity to Comments, have the count only show # of comments, and still maintain activity there (though we could move it to the side?)

**Comment by ckj** [comment]
That's not a bad idea

**Comment by ckj** [comment]
Let's just leave it in the same column for now. These will still primarily be activity and it wouldn't look great if there's no comments in the main column and activity stacked on the side.

@dcramer I updated the label, reassigning to you so you can update the count to reflect only the comment count.

**Comment by fabriciorissetto** [comment]
Thanks @dcramer! I just googled about it and found this issue. It's REALLY difficult to find that tab as the users usually will look for something like "comment" and the UI itself has more than 30 options in the same screen
