### ISSUE TITLE
Add project name to page titles

### ISSUE THREAD

**Issue by daninfpj** [getsentry/sentry#17559]
## Summary

Add project name to page titles.

## Motivation

The page title or URL have no clear indication of what the name of the project is. So if you look at the autocomplete options in the browser URL bar, or a bookmark or history, you can’t know what project a URL refers to.

**Comment by priscilawebdev** [comment]
just added this issue to our backlog. We will work on this soon 😉

**Comment by priscilawebdev** [comment]
Please, is there a specific page that you would like the project name to be displayed in the page title?

**Comment by priscilawebdev** [comment]
I added the name of the project on several pages of our application via these PRs: 

https://github.com/getsentry/sentry/pull/24366
https://github.com/getsentry/sentry/pull/24388

I tried to add it to as many pages as possible, but please, if you notice any pages that do not yet have the name of a project and that you think would be important to have, please let us know 😉

**Comment by daninfpj** [comment]
Hi @priscilawebdev! Sorry for the late response and thanks for the PRs!

I think I specifically meant the Issues page, for example: https://sentry.io/organizations/{org}/issues/?project={id}

The title for that page is right now just: “Issues - {org} - Sentry”, but there’s no project name.

I looked at the PRs you submitted and can’t see that page, or am I missing something?

**Comment by priscilawebdev** [comment]
@daninfpj I just checked and everything seems to be fine.

![Kapture 2021-03-15 at 14 09 26](https://user-images.githubusercontent.com/29228205/111158274-21970280-8598-11eb-8615-cc9a6563e422.gif)

**Comment by daninfpj** [comment]
Oh, right, got it! I didn’t know you could do that (not on the business plan 😄).

**Comment by priscilawebdev** [comment]
@daninfpj Please what is the name of your org? Could you please paste a link to the issues page in Sentry so we can take a look?
