### ISSUE TITLE
Sentry failing to send alerts after "ignore for" ends

### ISSUE THREAD

**Issue by jrubinator** [getsentry/sentry#17655]
We're seeing behavior where Sentry isn't sending alerts correctly after an issue becomes un-ignored.

We have an alert rule that acts once every five minutes. If I ignore an issue until it happens one more time, then the next event does not send an alert (which is reasonable). However, if another event comes in on the same issue in those five minutes, that event does not send an alert either.

Here's a sample rule: ![Screen Shot 2020-03-13 at 12 50 10 PM](https://user-images.githubusercontent.com/5924526/76642432-966cd200-6529-11ea-9264-345061ab766e.png)

Note there's nothing specific about the 5 minute throttling that causes this - I saw the same behavior with a 30 minute setting.

**Comment by BYK** [comment]
@scefali @adhiraj I think this is up your alley?

**Comment by adhiraj** [comment]
We'll look into this.
