### ISSUE TITLE
Feedback on V8

### ISSUE THREAD

**Issue by gytisgreitai** [getsentry/sentry#1770]
1) The stream font size/layout is too big. On current view i can see ~11 events. On new one - only 6-7. It makes it hard to quickly overview what has happened and which events should be investigated asap, and which should be left for later
2) No browser information, no ip address (only 
3) Cannot navigate directly to the url with the query string. I see url, i see query string, but how do i open it?
4) Json highlighter is much better.
5) User agent information is stuffed into one line and you have to scroll it to see the full string - inconvenient if I'm quickly looking for patterns in it.

Overall thought the new design is nice, i think those huge margins and font sizes sacrifice usability.

**Comment by dcramer** [comment]
@gytisgreitai thanks!

We're going to be refining the visuals over the coming weeks. There's definitely spots where things are too larger, or the margins are too much. We are aiming for a more flexible design (highly responsive) this time around so it's made things a lot more challenging.

**Comment by dcramer** [comment]
@ckj i think we should see if we can change the Stream back to two lines high as that would greatly improve information flow.

Regarding the user agent, I think we can enable soft wrap by default. I know in some places it was annoying, but I dont recall which ones.

@gytisgreitai what do you mean by no IP/browser info?

**Comment by lpil** [comment]
I agree that the font is far too large. I also find the low contrast a little hard to read.

**Comment by dcramer** [comment]
I have a few thoughts on the stream, but here's some ideas:

- We should stop using bootstrap's default grid widths here as things like assignee selector can be much smaller
- If this were using tables (or that style of CSS) we could simply set all columns to fixed width, expand the main column and move the culprit to the same line as the title (but truncate it?)

Here's a few simple visuals:

https://www.dropbox.com/s/o9wt5u2q9a1sanu/Screenshot%202015-08-14%2001.48.29.png?dl=0

https://www.dropbox.com/s/7tbxk4xrpjdoak9/Screenshot%202015-08-14%2001.50.46.png?dl=0

Context is slightly annoying as the size is widely varying. There's a few other various things we should probably do here:

- Links in the event-extra look identical to non-links.
- Date first seen may not be overly useful so we could remove it if we need more space.
- Add tooltips to action bar buttons as icons may not be obvious to users.

**Comment by mitsuhiko** [comment]
I think we should syart to investigate doing something mire intelligent with the user agent for displaying. It's such an important piece of jnfl but takes ages to decipher as a human.

**Comment by gytisgreitai** [comment]
@dcramer regarding the IP address, currently you have something like this:
https://www.dropbox.com/s/51zuuhkyv8l8nk8/Screenshot%202015-08-14%2015.14.22.png?dl=0

And in the new desing its probably hidden under Tags:
https://www.dropbox.com/s/fr26gf4r9p8mkn9/Screenshot%202015-08-14%2015.15.23.png?dl=0

When i was evluating which error logger to use, i chose sentry because it had all data on one screen (not like for ex. Raygun where you had to switch between tabs to get all the information about the event.). Because it makes viewing event and making decissions faster.

And it's even more slow because each tab is loaded on demand (additional delay) and not cached (go Overview -> Tags -> Overview ->Tags, you'll see a spinner every time).

On current interface i can just quickly scroll up down. I don't need to do any clicks to get a full overview of the event.

**Comment by dcramer** [comment]
@gytisgreitai we plan to cache overview, but the decision to not include tags the way they are currently was intentional. We want to separate the idea of the rollup and the individual event. It confuses far too many people who aren't familiar with crash reporting, as they expect the rollup to be something more magical. You should be able to get an overview of the tags via the sidebar, is that not useful enough?

**Comment by bgSosh** [comment]
I'd like to see more use of colour to differentiate information, and make it easier to asses things at a glance.

**Comment by smazurov** [comment]
Are exceptions being reverse of what they are currently intentional? I personally much prefer the old way of presenting those.

**Comment by dcramer** [comment]
@smazurov for which language? it's not intended that anything is flipped

**Comment by smazurov** [comment]
PHP

**Comment by dcramer** [comment]
All items should now be addressed
