### ISSUE TITLE
Quick filtering issues by projects in a team

### ISSUE THREAD

**Issue by charlesverdad** [getsentry/sentry#17717]
## Summary

In the Issues and Discovery v2 page, there is a dropdown that lets you filter projects. There is a "View all projects" button. It would be great if we can also filter issues by teams. (i.e. if I select the backend team then all backend projects will get selected)

## Motivation

I imagine most organizations having 3 main teams in Sentry: frontend, backend, mobile. Each of these teams can have 10 or more projects (i.e. 1 for each microservice in the backend, etc.)

SREs would normally belong to all three teams in case they need to investigate a bug. But in case they just want to look at backend issues, they would have to manually tick all the backend projects in the dropdown filter. 

It would be really helpful if there is an option to quickly tick all the projects in a specific team.

**Comment by BYK** [comment]
@charlesverdad, thanks for the suggestion! We think this is a very interesting idea and we'd like to give it a shot. There's some work that needs to be done before we can move forward though, so no promises on the timeline.

/cc @silent1mezzo

**Comment by BYK** [comment]
Ping @getsentry/visibility and @silent1mezzo for triage

**Comment by silent1mezzo** [comment]
@charlesverdad Apologies for the missed ping months ago. This is a great idea and one we've discussed before because of how useful it would be. Currently it's not feasible because of how teams are stored. There's an ongoing project that should be wrapping up next quarter that will allow us to efficiently search for events based off the team's they're associated with.

I've created a ticket internally to track this and will update this card when we're able to get started on this.

**Comment by PickledChris** [comment]
@silent1mezzo Did the project that changed how teams were stored get completed? 

This would be very useful for us as users can be members of multiple teams. It would be very helpful to view the review queue by team, without each person having to lock every project individually and save a bookmark, as that can be brittle.

**Comment by silent1mezzo** [comment]
@PickledChris Unfortunately we haven't picked this up at this point in time. I'm going to close this ticket for now but if there's movement we'll open it back up.

**Comment by mmerickel** [comment]
Came across this really hoping to see the feature in sentry. When reviewing issues it happens frequently that folks can see more projects than they are responsible for and would like to quickly trim that list down when finding new things to triage. Being able to do something in the "My Projects" dropdown to "select all projects for team X" versus "select all projects for team Y" would be really really handy.
