### ISSUE TITLE
Server Error on /manage/projects/

### ISSUE THREAD

**Issue by drcapulet** [getsentry/sentry#1772]
When you click to sort by events the server crashes - I looked at the code but didn't know the best way to solve it since the event count fetch is pulled down into the view.

**Comment by mattrobenolt** [comment]
Hey @drcapulet can you provide any other information? Ideally a stack trace so we can see what the issue was?

**Comment by drcapulet** [comment]
Derp, guess I missed out posting the info here from IRC.

Here are the offending lines: https://github.com/getsentry/sentry/blob/d43d625d7a236f111d66a33c1a694e01ca7d11da/src/sentry/web/frontend/admin.py#L67-L76

If the sort parameter is `event` then `order_by` is undefined.

You can trigger this if you go to `/manage/projects/` and click on "Events" to sort by that column. I can dig up a stack trace tomorrow if that'd help.

**Comment by mattrobenolt** [comment]
Awesome, that was easy to replicate. :) https://beta.getsentry.com/share/group/312e3739313531353732/

Will fix.

**Comment by drcapulet** [comment]
Thanks! Looks like that link doesn't work though, JS error or `Uncaught TypeError: Cannot read property 'options' of null`

**Comment by dcramer** [comment]
Welp. Lets go see what I broke :)

**Comment by mattrobenolt** [comment]
@drcapulet I "fixed" this by just removing the link to try and sort by # of events. Sentry has no way to expose any sensible way of doing this right now, unfortunately. So removing the link should avoid the confusion. :confused:

**Comment by drcapulet** [comment]
@mattrobenolt awesome, that works!
