### ISSUE TITLE
The dsyms files was upload successful, but the website's debug information files was empty

### ISSUE THREAD

**Issue by momoAI** [getsentry/sentry#17761]
I'm trying to upload dsym files to our self-hosted sentry. 

Tried with upload-dsym and upload-dif and getting same result.

We are using sentry v9.1.2 and sentry-cli 1.51.1

Command I'm using is 
`export SENTRY_URL=http://sentry.MY_DOMAIN.com
sentry-cli --auth-token API_TOKEN  upload-dif --org sentry --project ios DSYM_PATH`

And getting result:

[13:25:56]: Starting sentry-cli...
[13:26:04]: > Found 2 debug information files
[13:26:04]: > Prepared debug information files for upload
[13:26:17]: > File upload complete:
[13:26:17]: 
[13:26:17]: PENDING 414c2927-5836-3b82-963b-28156a649f39 (MY_APP.app.dSYM/Contents/Resources/DWARF/MY_APP; armv7 debug companion)
[13:26:17]: PENDING f736c1e9-39df-336b-bbaa-b4789abd1520 (MY_APP.app.dSYM/Contents/Resources/DWARF/MY_APP; arm64 debug companion)
[13:26:17]: > No new debug symbols to associate.
[13:26:17]: Successfully uploaded dSYMs!

After two hours,the website's debug information files is still empty.

![img](https://user-images.githubusercontent.com/20637150/76497763-9eb80500-6476-11ea-92cd-64616b1745ea.png)

Then I added arguments "--wait" to the command ，like this:
`export SENTRY_URL=http://sentry.MY_DOMAIN.com
sentry-cli --auth-token API_TOKEN  upload-dif --org sentry --project ios --wait DSYM_PATH
`
The terminal is loading all the time.

![屏幕快照 2020-03-17 上午10 03 34](https://user-images.githubusercontent.com/20637150/76814850-e6ec7400-6836-11ea-9e45-b339e0b71ba3.png)

**Comment by kamilogorek** [comment]
Transferred the issue here, as it's processing issue. CLI is doing its job correctly in this case.
In order for the DSYM processing to work, you need to have correctly configured caching on your on-prem instance - https://docs.sentry.io/server/config/#redis
As well as all workers running https://docs.sentry.io/server/queue/
I'd also try running an instance with higher logging setting and observe what's going on with DSYM files processing - https://docs.sentry.io/server/config/#logging

**Comment by kamilogorek** [comment]
@momoAI also see:
https://github.com/getsentry/sentry-cli/issues/376#issuecomment-454579917 https://github.com/getsentry/sentry-cli/issues/345#issuecomment-408115097

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
