### ISSUE TITLE
"upload dsym file missingchunks" , project not found

### ISSUE THREAD

**Issue by CrazyRoy** [getsentry/sentry#17800]
DEBUG   2020-03-20 12:43:02.034155 +08:00 request GET https://xxxxxx/api/0/organizations/sentry/chunk-upload/
  DEBUG   2020-03-20 12:43:02.034888 +08:00 using token authentication
  DEBUG   2020-03-20 12:43:02.035076 +08:00 retry number 0, max retries: 0
  DEBUG   2020-03-20 12:43:02.252237 +08:00 > GET /api/0/organizations/sentry/chunk-upload/ HTTP/1.1
  DEBUG   2020-03-20 12:43:02.252378 +08:00 > Host: xxxx
  DEBUG   2020-03-20 12:43:02.252461 +08:00 > Accept: */*
  DEBUG   2020-03-20 12:43:02.252538 +08:00 > Connection: TE
  DEBUG   2020-03-20 12:43:02.252614 +08:00 > TE: gzip
  DEBUG   2020-03-20 12:43:02.252690 +08:00 > User-Agent: sentry-cli/1.51.1
  DEBUG   2020-03-20 12:43:02.253135 +08:00 > Authorization: Bearer d947a8b9***
  DEBUG   2020-03-20 12:43:02.308533 +08:00 < HTTP/1.1 200 OK
  DEBUG   2020-03-20 12:43:02.308668 +08:00 < Server: nginx/1.17.9
  DEBUG   2020-03-20 12:43:02.308752 +08:00 < Date: Fri, 20 Mar 2020 04:43:02 GMT
  DEBUG   2020-03-20 12:43:02.308875 +08:00 < Content-Type: application/json
  DEBUG   2020-03-20 12:43:02.309004 +08:00 < Content-Length: 291
  DEBUG   2020-03-20 12:43:02.309093 +08:00 < Connection: keep-alive
  DEBUG   2020-03-20 12:43:02.309294 +08:00 < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization
  DEBUG   2020-03-20 12:43:02.309413 +08:00 < X-Content-Type-Options: nosniff
  DEBUG   2020-03-20 12:43:02.309495 +08:00 < Content-Language: en
  DEBUG   2020-03-20 12:43:02.309599 +08:00 < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
  DEBUG   2020-03-20 12:43:02.309735 +08:00 < Vary: Accept-Language, Cookie
  DEBUG   2020-03-20 12:43:02.309835 +08:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2020-03-20 12:43:02.309913 +08:00 < Allow: GET, POST, HEAD, OPTIONS
  DEBUG   2020-03-20 12:43:02.310051 +08:00 < Access-Control-Allow-Origin: *
  DEBUG   2020-03-20 12:43:02.310149 +08:00 < Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS
  DEBUG   2020-03-20 12:43:02.310227 +08:00 < X-Frame-Options: deny
  DEBUG   2020-03-20 12:43:02.310349 +08:00 response status: 200
  DEBUG   2020-03-20 12:43:02.310467 +08:00 body: {"maxFileSize":2147483648,"hashAlgorithm":"sha1","concurrency":8,"chunkSize":8388608,"maxRequestSize":33554432,"url":"http://xxxx/api/0/organizations/sentry/chunk-upload/","chunksPerRequest":64,"accept":["debug_files","release_files","pdbs","sources"],"compression":["gzip"]}
> Found 2 debug information files
> Prepared debug information files for upload
  DEBUG   2020-03-20 12:43:02.448075 +08:00 request POST https://xxxx/api/0/projects/sentry/ios-app/files/difs/assemble/
  DEBUG   2020-03-20 12:43:02.448204 +08:00 using token authentication
  DEBUG   2020-03-20 12:43:02.448300 +08:00 json body: {"571ce02294f6ae035620b51731617122817375d9":{"name":"dddd","chunks":["1b0718f22a6b7d4d6d7ac6d56280e1d8063637fb","56d4043b11457cc0f5ec0a5ba39b87a4ee7d4fdb"]},"eb416dfd32c8afe7e445a509a7e7769b4fab6b94":{"name":"dddd","chunks":["eec7373508ab3306af21bb5adc9372feacf9aeb9","72420b4cff57b8fc8e5fd1bc6223a9bba0868555"]}}
  DEBUG   2020-03-20 12:43:02.448386 +08:00 retry number 0, max retries: 5
  DEBUG   2020-03-20 12:43:02.448570 +08:00 > POST /api/0/projects/sentry/ios-app/files/difs/assemble/ HTTP/1.1
  DEBUG   2020-03-20 12:43:02.448655 +08:00 > Host: xxxx
  DEBUG   2020-03-20 12:43:02.448732 +08:00 > Accept: */*
  DEBUG   2020-03-20 12:43:02.448808 +08:00 > Connection: TE
  DEBUG   2020-03-20 12:43:02.448884 +08:00 > TE: gzip
  DEBUG   2020-03-20 12:43:02.449006 +08:00 > User-Agent: sentry-cli/1.51.1
  DEBUG   2020-03-20 12:43:02.449125 +08:00 > Authorization: Bearer d947a8b9***
  DEBUG   2020-03-20 12:43:02.449202 +08:00 > Content-Type: application/json
  DEBUG   2020-03-20 12:43:02.449278 +08:00 > Content-Length: 341
  DEBUG   2020-03-20 12:43:02.692014 +08:00 < HTTP/1.1 200 OK
  DEBUG   2020-03-20 12:43:02.692220 +08:00 < Server: nginx/1.17.9
  DEBUG   2020-03-20 12:43:02.692597 +08:00 < Date: Fri, 20 Mar 2020 04:43:02 GMT
  DEBUG   2020-03-20 12:43:02.692862 +08:00 < Content-Type: application/json
  DEBUG   2020-03-20 12:43:02.692986 +08:00 < Content-Length: 339
  DEBUG   2020-03-20 12:43:02.693074 +08:00 < Connection: keep-alive
  DEBUG   2020-03-20 12:43:02.693166 +08:00 < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization
  DEBUG   2020-03-20 12:43:02.693252 +08:00 < X-Content-Type-Options: nosniff
  DEBUG   2020-03-20 12:43:02.693337 +08:00 < Content-Language: en
  DEBUG   2020-03-20 12:43:02.693421 +08:00 < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
  DEBUG   2020-03-20 12:43:02.693505 +08:00 < Vary: Accept-Language, Cookie
  DEBUG   2020-03-20 12:43:02.693589 +08:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2020-03-20 12:43:02.693672 +08:00 < Allow: POST, OPTIONS
  DEBUG   2020-03-20 12:43:02.693756 +08:00 < Access-Control-Allow-Origin: *
  DEBUG   2020-03-20 12:43:02.693840 +08:00 < Access-Control-Allow-Methods: POST, OPTIONS
  DEBUG   2020-03-20 12:43:02.693924 +08:00 < X-Frame-Options: deny
  DEBUG   2020-03-20 12:43:02.694021 +08:00 response status: 200
  DEBUG   2020-03-20 12:43:02.694108 +08:00 body: {"571ce02294f6ae035620b51731617122817375d9":{"state":"not_found","missingChunks":["56d4043b11457cc0f5ec0a5ba39b87a4ee7d4fdb","1b0718f22a6b7d4d6d7ac6d56280e1d8063637fb"]},"eb416dfd32c8afe7e445a509a7e7769b4fab6b94":{"state":"not_found","missingChunks":["72420b4cff57b8fc8e5fd1bc6223a9bba0868555","eec7373508ab3306af21bb5adc9372feacf9aeb9"]}}
error: project not found

**Comment by latenitefilms** [comment]
FWIW - I also just ran into the same issue - I'm seeing the same `{"state":"not_found","missingChunks":` errors.

Leaving it to do it's thing for 10mins or so seemed to fix it.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
