### ISSUE TITLE
Empty list for event context

### ISSUE THREAD

**Issue by codegain** [getsentry/sentry#17812]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

I'm using the sentry-php sdk which allows me to send custom events. Using `$scope->setContext('context', [])` causes an error to show up on the dashboard (as described in https://github.com/getsentry/sentry-php/issues/993). Unfortunately this can't be fixed in the php sdk and so I wanted to ask if it is possible to fix this on the server-side.

## Steps to Reproduce

1. Use `$scope->setContext('context', [])` in the PHP code with the sentry-php sdk.
2. Send an event
3. Log into the dashboard
4. Open the event
5. A processing error is shown.

### What you expected to happen

No processing error is shown.

### Possible Solution

The problem is that PHP converts an empty array `[]` into the JSON equivalent of `[]` and not `{}`. But `{}` is expected by the API, so the event shows a processing error in the dashboard. Is it possible to also accept the `[]`  so the processing error does not show up?

**Comment by untitaker** [comment]
I'm sorry but given the additional context in the issue you linked there is no way we could figure out what you meant to send in Sentry.

**Comment by codegain** [comment]
@untitaker The sentry php-sdk sends `{"contexts": {"context": []}}` if the method `setContext` is called like this: `->setContext('context', [])`. It should (IMO) instead send this: `{"contexts": {"context": {}}}`. This is due to how PHP handles empty arrays in its JSON conversion. An empty PHP array will always result in `[]` instead of `{}` in JSON.

This could be fixed in the php-sdk (see the sdk issue) or by simply allowing `{"contexts": {"context": []}}` in the sentry API which it then interprets as `{"contexts": {"context": {}}}`.

Sorry if I didn't made that clear.
