### ISSUE TITLE
De-emphasize error type in issue view

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry#17837]
## Summary

_Maybe this is only for Go projects, maybe other languages too._

I would like the issue view to put less emphasis on the **error type**, because often times it is not the best information to help discern what happened.

## Motivation

> Why should this be worked on? What problems or use cases does it solve or
improve?

This would improve the experience for Go and Sentry users using the Sentry web application.

In Go, a lot of error values share the same type. Consider this code snippet:

```go
var ErrBadInput = errors.New("bad input")

func foo() error {
	return fmt.Errorf("an error happened")
}

func bar() error {
	return fmt.Errorf("error caused by: %w", ErrBadInput)
}
```
https://play.golang.org/p/PAnRW-8dZZE

The three error values above have types: `*errors.errorString`, `*errors.errorString`, and `*fmt.wrapError`.

There are simply many errors that have the same concrete type and are completely unrelated values.

Instead of:

![image](https://user-images.githubusercontent.com/88819/77349936-11a96180-6d3c-11ea-8406-ef3022586cfc.png)

It would be better to see:

![image](https://user-images.githubusercontent.com/88819/77355569-f2fb9880-6d44-11ea-9b4b-006463ea719f.png)

## Additional Context

> Any other context or screenshots or API request payload/responses that you
pertain to the feature.

Similarly, the error type is over emphasized in the issues list:

![image](https://user-images.githubusercontent.com/88819/77355788-656c7880-6d45-11ea-91fd-e4614940576c.png)

**Comment by lobsterkatie** [comment]
FWIW, this has come up WRT events sent by the Java and JavaScript SDKs as well.

**Comment by rhcarvalho** [comment]
Alternative to CSS changes, the title could be customizable from the SDKs, instead of being computed in Sentry server-side.

**Comment by snigdhas** [comment]
We've made numerous changes to the issue stream and issue details UI over the past year - please feel free to reopen the issue if you find this is still an area for improvement.

**Comment by leonid-shevtsov** [comment]
Hah, I only followed this issue a couple days ago and indeed the problem persists.

For Go, the error type is rarely a useful bit of information, most errors are essentially tagged strings. 

(Of course in some cases the type _is_ useful. And some "tagged string" errors wrap those meaningful error types, like `io.EOF`.)
