### ISSUE TITLE
Long exception values are not displayed in Beta

### ISSUE THREAD

**Issue by benorama** [getsentry/sentry#1784]
Hi,

We are using Sentry with Raven-java client.
On beta version, we don't have any info on the exception (no stack trace).
Is there some setting to change to enable it?

![capture d ecran 2015-08-18 a 14 54 27](https://cloud.githubusercontent.com/assets/394356/9330441/b2eaeadc-45b9-11e5-8c94-a7db28fc12c0.png)
![capture d ecran 2015-08-18 a 14 54 50](https://cloud.githubusercontent.com/assets/394356/9330444/b4a1bf9a-45b9-11e5-97b2-2a850b564b33.png)

**Comment by mitsuhiko** [comment]
It seems like you have no exception stacktrace in either.  However on the new beta the text is now the headline and thus abbreviated so it becomes hard to read.

We probably need to provide rendering for this information somewhere.

**Comment by dcramer** [comment]
This is sort of a blocker. I think what I'd prefer to do is we hard truncate titles and make a [...] clickable which would just expand + wrap. We'd then guarantee a minimum width for title space (i.e. 80 characters or something).

Thoughts @ckj?

**Comment by benvinegar** [comment]
I think we should just break it into two titles, like we do on the current sentry.
