### ISSUE TITLE
Organization selector broken when no org access

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1786]
You can see this in prod by logging in as the 'sentry' user which has global access but no direct access

https://www.dropbox.com/s/7rma7nq54h851ht/Screenshot%202015-08-18%2011.55.57.png?dl=0

**Comment by ckj** [comment]
@dcramer what should be shown there instead?

**Comment by dcramer** [comment]
nothing -- problem is its like an empty gap
