### ISSUE TITLE
Logo should go to organization home

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1788]
Right now it goes to the urlPrefix which is fine, except it causes a reload of the React app. We want this to go to org home when you're on an org page, and go to root when not.

**Comment by benvinegar** [comment]
>  We want this to go to org home when you're on an org page, and go to root when not.

Not sure it's awesome to have the same button have two different destinations.

What about adding a second breadcrumb next to the logo with the org name? Or making "Org Name / Project Name" clickable?
