### ISSUE TITLE
Tags display needs improved

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1790]
- [ ] Padding/margin issues
- [x] Need to link to stream searches
- [ ] Hide sentry: prefixed tags (internal tags)

**Comment by benvinegar** [comment]
Re: "Hide sentry: prefixed tags (internal tags"), I notice that the API doesn't return any "internal" tags for the groups/tags endpoint (e.g. /api/0/groups/75155990/tags/).

Should this be done at the API level?

**Comment by dcramer** [comment]
I think doing it on the server is probably better.

We already expose the user tag as the user data, and the release tag as the release attribute, so it makes more sense that if we're special casing them in that way we should just completely special case them in the backend.

**Comment by dcramer** [comment]
Reassigning to @ckj to make it look more presentable. The tag prefix thing we'll defer til later.
