### ISSUE TITLE
Registration not visible

### ISSUE THREAD

**Issue by sgohl** [getsentry/sentry#17992]
## Important Details

On-Premise w/ Docker, version  10.1.0.dev0978b2df

## Description

I want to enable Registration for any user without the need to approve.

## Steps to Reproduce

1. set `SENTRY_FEATURES['auth:register'] = True` in sentry.conf.py as documented
2. docker-compose build web and restart the stack
3. find on login page that REGISTER is still not available

Good items to include here include:

![image](https://user-images.githubusercontent.com/8873017/78033562-dbd13200-7366-11ea-875f-0968d30e0a9a.png)

**Comment by BYK** [comment]
This should be enabled in the initial setup wizard or via the `auth.allow-registration` setting in the `config.yml` file: https://develop.sentry.dev/config/#authentication
