### ISSUE TITLE
Team cant be deleted

### ISSUE THREAD

**Issue by myyorick** [getsentry/sentry#1800]
Sentry 7.7.0
I tried to delete some team from sentry, I received "team ... scheduled bla-bla-bla, will be deleted", but nothing happens... Team is on site(
Is it a bug?

**Comment by dcramer** [comment]
This fires a job into the queue and the workers are responsible for deleting it. It's possible its slow or somehow failed. You'd need to check worker logs to confirm though. If there's not much data it should happen very fast.
