### ISSUE TITLE
Friendly date shows "a month old", on the first day of the next month.

### ISSUE THREAD

**Issue by burhan** [getsentry/sentry#18015]
## Description

An issue raised on March 31, shows "a month old" when viewed on April 1 (as viewed on sentry.io)

## Steps to Reproduce

1. Create an issue on the last day of the month
2. Login next day
3. In summary view, you'll see `a month old` when the issue was raised yesterday.

<img width="590" alt="Screen Shot 2020-04-01 at 8 30 39 AM" src="https://user-images.githubusercontent.com/603112/78102995-6449e400-73f4-11ea-9784-453b4d26d891.png">

This issue was actually raised yesterday (31 March) `18 hours ago`

<img width="656" alt="Screen Shot 2020-04-01 at 8 30 57 AM" src="https://user-images.githubusercontent.com/603112/78103030-79bf0e00-73f4-11ea-9e5a-aaf8ff0f82e3.png">

**Comment by markstory** [comment]
How many events are in this issue? The second time is the time of the first event in the issue. Our date formatting logic wouldn't create this result unless the time was a month ago.

**Comment by markstory** [comment]
:+1: ok.
