### ISSUE TITLE
[v8] some remarks - API

### ISSUE THREAD

**Issue by xcambar** [getsentry/sentry#1802]
Hey,
first of all, thank you for the redesign, it makes a much better experience!

This issue is not really about the redesign though, but the accompanying API. I've played with it recently to leverage your data (see https://github.com/xcambar/sentry_api_sandbox for 2 examples) and noticed what follows:

* I don't understand how a group can show 220k events in the interface while when I query the API, I hardly reach 2k events. (Summing entries in the payloads doesn't help). Can I retrieve all the events related to a group?
* Stack traces are a long string containing `\n` and other markers. Wouldn't it make more sense to deliver it as an array?
* The `Link` header is amazing, but why would you always include next/previous when there's no data in the next page. It forces clients to check the `results` property, cast it to JSON then do a check. Not much work but I think it would be more natural with "no next URL? I'm on the last page".

That's it for now, I'm really having fun digging the data you collect from my apps, which, I assume, is the best that could happen!

**Comment by dcramer** [comment]
> I don't understand how a group can show 220k events in the interface while when I query the API, I hardly reach 2k events. (Summing entries in the payloads doesn't help). Can I retrieve all the events related to a group?

Sentry samples data: https://docs.getsentry.com/hosted/rollups/#sampling

> Stack traces are a long string containing \n and other markers. Wouldn't it make more sense to deliver it as an array?

This would imply your integration is sending a raw stacktrace and not Sentry's structured data format. Which integration?

> The Link header is amazing, but why would you always include next/previous when there's no data in the next page. It forces clients to check the results property, cast it to JSON then do a check. Not much work but I think it would be more natural with "no next URL? I'm on the last page".

This is because pagination can be used for polling as well (i.e. a previous page doesnt yet exist).

Hopefully that helps explain some things better.

**Comment by xcambar** [comment]
> Which integration?

raven.js

Thanks for the answer, makes sense.

**Comment by dcramer** [comment]
@xcambar stacktrace definitely shouldn't be a raw string in JS

Could you email me (david@getsentry.com) with the more details on the stacktrace?

i.e. the raw JSON, screencaps, whatever might help me understand what the data looks like
