### ISSUE TITLE
Redirect to Organization dashboard after login

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry#18037]
## Important Details

> How are you running Sentry?

Saas (sentry.io)

## Description

After logging in, browser lands back at the login page, without a clue that login actually succeeded.

## Steps to Reproduce

1. Start logged in. Click on your org logo on the top left, then "Sign out".
2. Logging via single sign on or Google account.
3. You're back at the login page (`/auth/login/`).

Browser: Safari version 13.0.5 (15608.5.11)

### What you expected to happen

If you go to the login page and you're already logged in, I'd expect it to redirect to the main application screen until you logout.

### Possible Solution

Update the auth Django view to include a redirect in case the user is logged in.

**Comment by BYK** [comment]
This seems to be the case for me now so closing.
