### ISSUE TITLE
Unable to downlod dSYM (debug symbol file) without Admin role

### ISSUE THREAD

**Issue by guarani** [getsentry/sentry#18041]
## Important Details

Users of Sentry with a Member role should be able to download debug symbol files. It appears that only users with an Admin role can do this at the moment.

How are you running Sentry?
Saas (sentry.io)

## Description

I was looking for the dSYM file for a particular iOS build of our app and located it on Sentry. Upon clicking to download the dSYM, a _JSON_ file is downloaded – which is incorrect. A dSYM file should be downloaded.

We noticed that after changing my role to Admin, I was able to download the dSYM without any issues. It implausible that users need to be an Admin to download a dSYM, so what could be the problem here?

## Steps to Reproduce

1. Login to Sentry with a regular Member account (not Admin)
2. Go to the dSYMs page (debug symbols page), something like at: https://sentry.io/settings/<team_name>/projects/<project_name>/debug-symbols
3. Try to download the dSYM (any browser, Chrome, Firefox, Safari, etc)
4. Notice that a small JSON file is downloaded instead of a dSYM file
5. Change account to Admin and try again, observe that now you can download the dSYM without a hitch

### What you expected to happen

Even non-admins should be able to download debug symbol files from Sentry.

### Possible Solution

Allow non-admins to download debug symbol files from Sentry.

**Comment by BYK** [comment]
@jan-auer @mitsuhiko is this intentional? If so what's the motivation behind it? In either case, is it okay to change the behavior as @guarani suggested?

**Comment by jan-auer** [comment]
This is being addressed in https://github.com/getsentry/sentry/pull/21300.
