### ISSUE TITLE
When removing a user via admin->users it shows the logged in user not user to be deleted in the confirmation screen

### ISSUE THREAD

**Issue by zpgjon** [getsentry/sentry#18071]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 9.1.2

## Description

When removing a user as admin, it shows the admins name as the one to be deleted on the confirmation screen.

eg.
https://sentry.myinstall.com/manage/users/6/ shows "User details MrUser@example.com"
click remove and go to
https://sentry.myinstall.com/manage/users/6/remove/ "Remove User MsAdmin@example.com"

## Steps to Reproduce

1. Go to /manage/users/
2. Select a user to delete
3. See incorrect name in confirmation screen

### What you expected to happen

It should show the users name

### Possible Solution

Use correct var?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
