### ISSUE TITLE
The Sentry JIRA application currently isn't loading within JIRA

### ISSUE THREAD

**Issue by markgarethgabb** [getsentry/sentry#18070]
## Important Details

How are you running Sentry?

Cloud

## Description

When I go to Configure the Sentry application in JIRA it doesn't respond.
I get the following error message: App is not responding. Wait or cancel?

## Steps to Reproduce

1. Configure Sentry within JIRA.

Good items to include here include:

### What you expected to happen

The Sentry app should be loading

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by Dezeter** [comment]
> 
> 
> @markgarethgabb Thanks for writing in. Can you post a screenshot of the issue you see in Jira?

https://i.imgur.com/TEXZcMB.png

**Comment by tmak** [comment]
I'm having the same issue.

We're using an on-premise Sentry installation (9.1.1) with GitHub Authentication SSO enabled + JIRA Cloud.

I was able to get to the same step as Dezeter by following these instructions: https://forum.sentry.io/t/how-to-configure-jira-cloud-in-your-on-premise-sentry/6720

When I click on the `Sign In to Sentry` button it opens our Sentry dashboard in a new browser tab successfully.
But that's it, nothing happens and JIRA is displaying `App is not responding. Wait or cancel?`.

**Comment by joshInsta** [comment]
Exact same issue. Our business has paid subscriptions for both sentry and jira and we can't get past 
App is not Responding

**Comment by tbach** [comment]
Exact same issue for me. I tried disabling all sorts of cookie restrictions since it mentions cross-site cookies, but no luck. This is a really unfortunate blocker since we're paying for both services and would really like to link them.

**Comment by Dezeter** [comment]
@scefali Is it possible to fix it?

**Comment by DethAriel** [comment]
The problem is [this line of code](https://github.com/getsentry/sentry/blob/fda7167f29021cbbf5d4722e242ec7182b0af303/src/sentry_plugins/jira_ac/views.py#L43) (or at least this is one of the first problems):

```py
        res["X-Frame-Options"] = "ALLOW-FROM %s" % self.request.GET["xdm_e"]
```

According to [MDN here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options),

> This is an obsolete directive that no longer works in modern browsers. Don't use it. [...] The [`Content-Security-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) HTTP header has a [`frame-ancestors`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) directive which you can use instead.

So I think the referenced line of code should instead be smth like this:

```
        res["Content-Security-Policy"] = "frame-ancestors %s" % self.request.GET["xdm_e"]
```

**Comment by BYK** [comment]
@DethAriel would you be willing to submit a PR since you seem to have identified some relevant code?
