### ISSUE TITLE
CSP violation about style src violation cannot be reported (403 response)

### ISSUE THREAD

**Issue by tzimmermann** [getsentry/sentry#18098]
## Important Details

How are you running Sentry?

On-Premise, version 8.22.0

## Description

I set up CSP's on our NodeJS server and set the reporting-uri to `https://[our-sentry-domain]/api/2/csp-report/?sentry_key=[our-sentry-key]`

For some violations (like the one mentioned below), I see that they return 403 errors, although I don't see anything wrong with the report itself.

## Steps to Reproduce

 Chrome `Version 80.0.3987.149 (Official Build) (64-bit)` sends this CSP violation to our sentry:

This is the payload of the CSP violation that gets rejected (some information redacted in []):
```json
{
  "csp-report": {
    "document-uri": "https://[our-URL]",
    "referrer": "[our-URL]",
    "violated-directive": "style-src-attr",
    "effective-directive": "style-src-attr",
    "original-policy": "default-src 'self'; img-src 'self' [our-URL] data:; script-src 'self' 'nonce-[someNonce]'; style-src 'self' 'sha256-[someHash]' 'sha256-[someHash]' 'nonce-[someNonce]'; font-src 'self' data: https://cdnjs.cloudflare.com; connect-src 'self' [someURL]; report-uri [our-reportingURL]",
    "disposition": "report",
    "blocked-uri": "inline",
    "line-number": 1,
    "column-number": 829761,
    "source-file": "[some-URL]",
    "status-code": 0,
    "script-sample": ""
  }
}
```

### What you expected to happen

 I would like to see it in sentry since it provides valuable information.

### Possible Solution

Either something's wrong with the CSP report/policy, then I would like to know about it.
Or sentry is too restrictive in accepting CSP reports, then this should be fixed.

**Comment by migg24** [comment]
I had the same issue and for us it turned out that sentry rejects reports coming from localhost (in document-uri, referrer, source-file) even when `allow *` is configured in sentry project settings. 

In our case sentry returned a 403 together with `x-sentry-error: | Event dropped due to filter: invalid-csp` header whenever testing it from localhost. Maybe it helps somebody in the future.

Would be interesting if `[our-URL]` in your case was localhost too.

**Comment by BYK** [comment]
Will close this as the original report seems quite old. Please file a new issue if you are still having problems.
