### ISSUE TITLE
To enable GitLab Integration for projects owned by Users

### ISSUE THREAD

**Issue by mtazzari** [getsentry/sentry#18093]
## Summary

Currently the GitLab Integration only supports Projects owned by groups or sub-groups and it doesn't support Projects owned by users. Supporting Projects owned by users would be extremely useful, and similar to what is already done with the GitHub integration.

## Motivation

There is a huge number of developers (e.g., in the open-source/academic research/higher-education fields) that own the repositories to which they contribute and don't have groups/sub-groups. If the GitLab Integration worked also for Projects owned by users it would enable all these developers to use the latest features of Sentry.

**Comment by Daniel-Mendes** [comment]
I managed to get Sentry activated on a project owned by user.

Steps for the configuration:
- Create a Auth Token from Sentry [link](https://sentry.io/settings/account/api/auth-tokens/).
  - Scopes: Leave the default scopes
- Go to project settings -> Operations -> Error Traking
  - Sentry API URL : https://sentry.io/
  - Auth Token: Copy the token generated from step one
- Click on connect button
- Select project from dropdown menu

You can now acces error traking from the Operation -> Error traking panel

[Official Gitlab documentation for enable error_tracking](https://gitlab.com/help/user/project/operations/error_tracking)

**Comment by BYK** [comment]
Closing as this seems possible. Comment here if you think we need to improve our docs or code.
