### ISSUE TITLE
Bitbucket Integration: 

### ISSUE THREAD

**Issue by letnab** [getsentry/sentry#18123]
please do integration with Bitbucket self-hosted.

**Comment by jonesphillip** [comment]
@letnab we recently shipped a Bitbucket Server integration. Find it in:
Settings > Integrations > Bitbucket Server

**Comment by letnab** [comment]
<img width="974" alt="image" src="https://user-images.githubusercontent.com/13086266/79576694-5cfd2880-80cc-11ea-8aab-68438c653a5d.png">
