### ISSUE TITLE
Adjust rules to maintain current and previous states

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1812]
Rule API needs adjusted to be something like:

```
def passes(self, current_data, previous_data, state):
```

Effectively we need to be able to build rules that say "act on this event when it changes from X to Y" which is fairly tricky when you cant guarantee the change. A prime example of this is to "notify me after the 1,000th occurrence."

**Comment by bentierny** [comment]
That would be amazing David !

**Comment by dcramer** [comment]
This comes up enough that I think I'm just going to add it. It's backwards incompat, but I can squeeze it in real quick before the 8.0 release.

**Comment by dcramer** [comment]
As a simple solution it might be that when a rule becomes active, you can store state with it (in GroupRuleStatus).

i.e. you could say "# of times seen was 700"

Then the next time the rules checked, that state can get passed into it, and you can be like "well last time we did this, the count was 700, now its 1000, so lets notify for the 1000th occurrence".

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
