### ISSUE TITLE
showReportDialog doesn't work

### ISSUE THREAD

**Issue by chpatrick** [getsentry/sentry#18135]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

In my code, I do the following:
```
Sentry.showReportDialog({
    title: "Something wrong?",
    subtitle: "Please describe the problem."
  });
```
this creates the following tag in head:
`<script async="" src="https://o374366.ingest.sentry.io/api/embed/error-page/?dsn=<my DSN>&amp;title=Something%20wrong%3F&amp;subtitle=Please%20describe%20the%20problem."></script>`

Downloading this script produces a 404 Not Found in the Network tab.

**Comment by BYK** [comment]
Seems like this is fixed now. Please comment if you are still experiencing the same issue and we'll reopen and investigate.
