### ISSUE TITLE
Text should not wrap on tooltips

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1815]
https://www.dropbox.com/s/pquz1oao9bd4i8u/Screenshot%202015-08-20%2018.22.36.png?dl=0

**Comment by benvinegar** [comment]
What if we made this text shorter?

e.g. do we need the year if we know it's the past 2 weeks or 24 hours?

**Comment by benvinegar** [comment]
![image](https://cloud.githubusercontent.com/assets/2153/9482905/6c5b5698-4b4e-11e5-8dcc-e13615281b61.png)

**Comment by dcramer** [comment]
Thats probably a good compromise. As long as we ensure important things arent wrapping and we dont make the UX worse I'm happy.

I think in this situation we could still probably force it to a single line, but idk.

**Comment by benvinegar** [comment]
A user points out that this is still an issue because of translations:

![](http://imgur.com/LchfwIo.jpg)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
