### ISSUE TITLE
Missing vendor directory

### ISSUE THREAD

**Issue by petrprikryl** [getsentry/sentry#18183]
## Important Details

How are you running Sentry?

On-Premise Docker, version Sentry 10.1.0.dev0e621146

## Description

Hi, my Sentry instance is missing vendor directory in static:
```
root@ed1b2ff2679f:/# ls -l /usr/local/lib/python2.7/site-packages/sentry/static/sentry/
total 84
drwxr-xr-x 15 root root  4096 Apr  4 01:18 app
drwxr-xr-x 16 root root 65536 Apr  4 01:18 dist
drwxr-xr-x  2 root root  4096 Apr  4 01:18 fonts
drwxr-xr-x  9 root root  4096 Apr  4 01:18 images
drwxr-xr-x  2 root root  4096 Apr  4 01:18 js
drwxr-xr-x  4 root root  4096 Apr  4 01:18 less
```
And it leads to error 404 while getting `/_static/1586442005/sentry/vendor/select2.min.js` on "Create Redmine Task" integration page with this URL `/group/project/issues/796501/actions/redmine/`.

## Steps to Reproduce

1. Go to some issue detail page
2. Click on "Create Redmine Task"
3. There are 404 errors for all vendor/*.min.js files on redirected page

**Comment by EvanPurkhiser** [comment]
Are you still running into this in the latest sentry image?

**Comment by petrprikryl** [comment]
No. I have upgraded to Sentry 20.7.2 46de988 and `vendor` directory with `select2.min.js` is present.

**Comment by BYK** [comment]
Closing as this is now fixed.
