### ISSUE TITLE
Feedback on issues integration in V8

### ISSUE THREAD

**Issue by noplay** [getsentry/sentry#1820]
I would love a better integrations of issue tracker. Actually I need to go to comment section of an error to see if an issue is opened or not.

Possible improvements: 
* A mention of the issue in the overview of the error like in previous release or just an issue icon (in v7 I need one less click to check if an issue is opened or not).
* In error list add an icon in order to know if an issue is opened on the issue tracker

Thanks a lot for your great work

**Comment by dcramer** [comment]
@noplay  Thanks for the feedback!

> A mention of the issue in the overview of the error like in previous release or just an issue icon (in v7 I need one less click to check if an issue is opened or not).

It actually shows up next to the logger name, towards the top of the page: https://www.dropbox.com/s/e3bwx2rwyz93a5l/Screenshot%202015-08-24%2014.50.06.png?dl=0

> In error list add an icon in order to know if an issue is opened on the issue tracker

Same thing as above, next to logger name.
