### ISSUE TITLE
Use monotonic clock to compute durations

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry#18206]
Searching for `time.time()` in the code base reveals many cases where we use it to compute durations, when it would be more robust to use a monotonic clock.

On Python 3.3+ this would be `time.monotonic()` or `time.perf_counter()` (or even `time.process_time()`), as appropriate.

On Python 2.x and <3.3 there is https://pypi.org/project/monotonic/.

See also https://www.python.org/dev/peps/pep-0418/.

**Comment by joshuarli** [comment]
Yeah, I've seen @beezz use monotonic clock in some ops code and it's good. This would maybe require a bit of care auditing all the time usage, as I'm not sure if we rely on the assumption on some deltas being >= 0, for example.

**Comment by BYK** [comment]
@bc-sentry are you sure this should be closed?
