### ISSUE TITLE
"Commits by author" count wrong

### ISSUE THREAD

**Issue by kkmuffme** [getsentry/sentry#18216]
I just created a release with more than 600 commits (& 6 authors)

It shows the commit count correctly here https://sentry.io/organizations/blabla/releases/?project=123456

When I open the release page https://sentry.io/organizations/blabla/releases/2.0.0/?project=123456 the "COMMITS BY AUTHOR" section is completely wrong. It seems it's limited to 100 commits (as the total shown there is 100)?

**Comment by kkmuffme** [comment]
Still a bug.
Should I email support about it to get it fixed more quickly?

**Comment by manuzope** [comment]
Hi @kkmuffme, yea would you mind filing a [support ticket](https://sentry.io/support)? That way, we'll be able to look at the specifics of the release to debug what's going wrong.
