### ISSUE TITLE
dateReleased doesnt have any effect

### ISSUE THREAD

**Issue by kkmuffme** [getsentry/sentry#18219]
on sentry.io when I create a release with a timestamp like:
`"dateReleased": "2019-08-24T14:03:47+00:00"`

Sentry still shows "1 minute ago" (or whatever many minutes ago I created the release via API call) instead of showing the correct date
(here: https://sentry.io/organizations/blabla/releases/?project=123456)

**Comment by BYK** [comment]
Have you tried [contacting our support](https://sentry.io/contact/support/) for this?

**Comment by kkmuffme** [comment]
The issue was fixed, probably with the change to the new view/display of releases
