### ISSUE TITLE
Large sourcemap leads to 502?

### ISSUE THREAD

**Issue by 18569505972** [getsentry/sentry#18221]
## Version
raven-js:  "^3.17.0"
@sentry/webpack-plugin: "^1.10.0",

## Description
![image](https://user-images.githubusercontent.com/26136387/79110950-22368000-7dae-11ea-8c7e-fd86bfd910c3.png)
![image](https://user-images.githubusercontent.com/26136387/79111084-72154700-7dae-11ea-981d-100124e42e7e.png)

[What happened]
App.js.map upload to Sentry fail!
![image](https://user-images.githubusercontent.com/26136387/79111133-86594400-7dae-11ea-814b-77a59febc208.png)

Large sourcemap leads to 502 ? Upload fail?

**Comment by Oikio** [comment]
Any updates on this one? Looks like I have similar problem.

**Comment by BYK** [comment]
Have you tried [contacting our support](https://sentry.io/contact/support/) for this? (assuming this is on sentry.io?)
