### ISSUE TITLE
413 Request Entity Too Large for release

### ISSUE THREAD

**Issue by kkmuffme** [getsentry/sentry#18220]
I want to submit a release with ~4000 commits (incl. patch sets) to sentry.io (via API) but always get "413 Request Entity Too Large" error

Any way to partially upload the release or any other way around this problem?

EDIT: the payload of the release is <3MB when I put it in a .log file to check it

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
