### ISSUE TITLE
GitHub Integration: 

### ISSUE THREAD

**Issue by willgdjones** [getsentry/sentry#18306]
I click "Add installation" for GitHub, complete the steps on GitHub.com, but Sentry indicates that it is not installed.

**Comment by 50l3r** [comment]
I have the same problem:

When i try to finish the integration. I recieve this error:

![](https://i.gyazo.com/b6eaa3daece6b2c45fc7b96a288962b5.png)

Same with Github Login

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
