### ISSUE TITLE
Older Sample gets caught in a loop when samples have the same timestamp

### ISSUE THREAD

**Issue by ragesoss** [getsentry/sentry#1830]
I caught a flurry of Sentry messages at the same time, and there are two that get caught in an endless loop via 'Older Sample'. The only way to get to the actual order messages that I can find is to guess at lower ids via the url. The 'Older Sample' button just cycles back and forth between the same two samples.

**Comment by dcramer** [comment]
@ragesoss is this getsentry.com? If not which version (or git SHA)?

**Comment by ragesoss** [comment]
This is self-hosted, version 7.7.0.

**Comment by dcramer** [comment]
@ragesoss are you able to inspect any of the events (you could use the events tab to list them) to get an idea of the timestamps? I'm wondering if this is an edge case where a large amount of samples have almost identical timestamps.

**Comment by ragesoss** [comment]
@dcramer they have the same datetime: 2015-08-25T17:23:46.000000Z

It looks like all the events have datetimes that only go down to second-level resolution.

**Comment by dcramer** [comment]
That sounds about right. Do you have a rough idea how many events it is? We try to work around ~5 identical events w/ datetimes.

**Comment by ragesoss** [comment]
It appears to be only two events with the same datetime. (There are at least 3 pairs of these in my database... which are errors that get reported when my app gets rate-limited by the Wikipedia API and user edits start failing.)

**Comment by dcramer** [comment]
At least in one case we've got an issue where prev and next event are identical
