### ISSUE TITLE
PagerDuty Integration: "App not found" error

### ISSUE THREAD

**Issue by martinraison** [getsentry/sentry#18311]
I tried using the new PagerDuty integration with Sentry 10. When I click the "Add Installation" button and log into my PagerDuty account, I get an "App not found" error:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/2560662/79476513-5bb6f780-8009-11ea-8b2d-db331b9b9847.png">

Using Chrome's dev tools I see that the request to `/api/v2/apps/install_by_vendor` is returning a 400.

My Sentry version is Sentry 10.1.0.dev0 6e6ed91.

Any idea of what the problem could be ?

**Comment by martinraison** [comment]
Ok I think I found a solution, so I'm documenting it here in case it can help other on-premise users:

To use the new PagerDuty integration, you need to create a "PagerDuty app" (from the main PagerDuty page, "Configuration" -> "API Access" -> "Create an app"). In the app configuration, you should enable "Events Integration" and add the following Redirect URL:

```
https://<YOUR_SENTRY_DOMAIN>/extensions/pagerduty/setup/
```

When you save you will get an "App ID". This should be the value of `pagerduty.app-id` in your Sentry config.

You do not need to publish the app.

Maybe I'm mistaken, but I don't think this process is explained anywhere in the Sentry docs. It would be a worthwhile addition in my opinion.

I hope this is helpful !

**Comment by amitseth7** [comment]
After the instructions you provided above , which I think should be added to the Sentry documentation. 
I am now getting a "You do not have authorization to install this app".
I am an owner in Sentry
