### ISSUE TITLE
Support setting issue owners based on CODEOWNERS files.

### ISSUE THREAD

**Issue by kevincox** [getsentry/sentry#18312]
## Summary

Right now issue owners can be manually specified in the project settings dashboard. However many teams already define owner individuals and teams for their code paths using CODEOWNERS files as supported by Gitlab and Github. It would be great if sentry could use these files as well.

## Motivation

This ensures that there is a single source of truth for which teams are responsible for a given codepath and reduces effort to keep them in sync.

**Comment by mufid** [comment]
This is very interesting and would also help my team in categorizing issue.

**Comment by burkestar** [comment]
My team could also take advantage of this feature.

Either:
- configuring the Github integration and it would auto-detect CODEOWNERS files in the repo and use that
- provide an API to get/set ownership rules for a project (I wasn't able to find this functionality in the API docs).

Thanks!

**Comment by BYK** [comment]
I think @jonesphillip was working on something similar or related to this.

**Comment by jonesphillip** [comment]
@kevincox @burkestar @mufid We're working on making this happen!

If you're interested in learning more or trying it out check out: https://github.com/getsentry/sentry/issues/25794

We'd love to get your feedback on this.
