### ISSUE TITLE
Resurrect a color scheme for group or events.

### ISSUE THREAD

**Issue by mvaled** [getsentry/sentry#1831]
In Sentry 7 red meant an error-level group, in Sentry 8 all groups are not "colored".  Would it make sense to have an "initial" color scheme based on the level of the events in the group.

This interacts with merging, since we can actually merge groups containing warnings with other containing errors.  

But it's nice to have a quick way to notice where priority should be placed when fixing some things.

**Comment by dcramer** [comment]
@mvaled do you not see the red sidebar highlight? We're still toying with improvements to this, but that's the intention of the border color.

**Comment by mvaled** [comment]
Ah! I missed it, it's rather unnoticeable, though.  Probably you should provide a more visible way of displaying it.

**Comment by mvaled** [comment]
I see you have made this more visible by putting labels.  Nice! +10
