### ISSUE TITLE
Jira Integration: 

### ISSUE THREAD

**Issue by patrick-tresp** [getsentry/sentry#18375]
Hi,

just wanted to integrate sentry in our jira installation and i can see in debugger that there is a 404

`Invalid 'X-Frame-Options' header encountered when loading 'https://sentry.io/extensions/jira/configure/?xdm_e=https%3A%2F%2Fxxxxxxxxxx.atlassian.net&xdm_c=channel-sentry.io.jira__post-install-sentry&cp=&xdm_deprecated_addon_key_do_not_use=sentry.io.jira&lic=none&cv=1001.0.0-SNAPSHOT&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZTc5ZTlhZjUxNDY5NjBjMzNlMzU1NWEiLCJxc2giOiIxNDQ5NWQzY2I0YjJiMDNhZjdiMzk4YzU4NzEyMTI2ZjdkZjZlNGIzYTI2MjIwZTQwMmE3OWRhMGU4MGQ4ODNhIiwiaXNzIjoiMGEyMGFjNTQtM2ZhMi0zZTYzLTljZmUtMDMxMTg2ZTRmZWU4IiwiY29udGV4dCI6e30sImV4cCI6MTU4NzQ2MTcwMywiaWF0IjoxNTg3NDYwODAzfQ.6dyVtsX8ndrqHAXR-No9fxqmaao1VSf1svMyXoQVyV0': 'ALLOW-FROM https://xxxxxxxx.atlassian.net' is not a recognized directive. The header will be ignored.

what needs to be done do get a "recognized directive" ?

**Comment by BYK** [comment]
As you can see from [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#Syntax), `ALLOW-FROM` is deprecated and does not work on modern systems. The valid values you can use are `SAMEORIGIN` and `DENY`.
