### ISSUE TITLE
No refresh in Queue Overview

### ISSUE THREAD

**Issue by ChibangLW** [getsentry/sentry#18379]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 10.0.0

## Description
If you want to check the task details on the queue overview only the first choice will be fetched. Every selection following the initial selection won't trigger an api-call. Furthermore it looks like the resolution doesn't have an impact on the made api-call because it is always `1h`. Also tested on fresh on-premise install with `Sentry 10.1.0.dev 018ca08e`

## Steps to Reproduce

1. Go to Admin-Panel
2. Select queue
3. Select any task to show details
4. Select a different task to show details

### What you expected to happen

It should trigger an api-call on any selection of task  and not only the first.

### Possible Solution

As a workaround first hit the `X` in dropdown menu and then select the new task.

**Comment by chadwhitacre** [comment]
Ancient ticket, closing. Ping if we need to reopen, thanks.
