### ISSUE TITLE
Webhook not working sentry.io

### ISSUE THREAD

**Issue by rishbz** [getsentry/sentry#18404]
I am using sentry on our organisation portal.

Steps to reproduce:
1) Go to organisation setting -> Go to Projects -> Choose any project 
2) Go to All integerations page. Enable Webhook and configure with callback URL. My callback URL is for MS teams. Looks like this: https://outlook.office.com/webhook/{guid}/IncomingWebhook/{guid}

3)Go to Alerts -> Under Rules, create rule for when event is first seen. Action-> Send notification(all legacy integertions)

![image](https://user-images.githubusercontent.com/61784117/79974816-93191e80-84b7-11ea-8920-6d2d59e4c085.png)

## Important Details

How are you running Sentry?

On-Premise w/ Docker, version x.y.z

Saas (sentry.io)

Other, version x.y.z, [briefly describe your environment]

## Description

[What happened]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. and so on.

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant

### What you expected to happen

[What you think should be happening]

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by fiammaPantano** [comment]
I have the same issue, any workaround?

**Comment by BYK** [comment]
Please follow the issue template and provide as much information as possible, especially logs and configuration.

Closing this issue as it is not actionable in this state.
