### ISSUE TITLE
Webhook not working (Using sentry portal)

### ISSUE THREAD

**Issue by rishbz** [getsentry/sentry#18405]
I am using sentry on our organisation portal.

Steps to reproduce:
1) Go to organisation setting -> Go to Projects -> Choose any project 
2) Go to All integerations page. Enable Webhook and configure with callback URL. My callback URL is for MS teams. Looks like this: https://outlook.office.com/webhook/{guid}/IncomingWebhook/{guid}

3)Go to Alerts -> Under Rules, create rule for when event is first seen. Action-> Send notification(all legacy integertions)

![image](https://user-images.githubusercontent.com/61784117/79974816-93191e80-84b7-11ea-8920-6d2d59e4c085.png)

The image shows success, but I did not receive notification in my teams channel for which webhook is configured.

@BYK @scefali

**Comment by BYK** [comment]
>I am using sentry on our organisation portal.

I'm guessing this means on-premise. Can you provide more details around which version you are using?

**Comment by rishbz** [comment]
@BYK  we are using 9.0.0

**Comment by BYK** [comment]
Slack API has changed many times since 9.0.0 so you may want to upgrade to at least 9.1.2 to see if it helps as it includes some fixes and updates. You can find an up-to-date guide over at the forums: https://forum.sentry.io/t/how-to-configure-slack-in-your-on-prem-sentry/3463?u=byk

If your question is specifically about a webhook not getting triggered, we'd need more details from your logs (worker logs) too see what's happening.

**Comment by rishbz** [comment]
It's not about slack. It is about webhook not getting triggered as u rightly mentioned in the end. Which logs you require and from where can I fetch them because we do not log anything as sentry and webhook are external systems,right?

**Comment by BYK** [comment]
>It's not about slack. It is about webhook not getting triggered as u rightly mentioned in the end. We are trying to integrate Microsoft teams and Sentry through webhook as sentry does not have plugin for Teams yet.

Yeah, sorry when you just said "teams" it wasn't clear to me that this was MS Teams and not some other Slack thing.

>1 - Which logs you require and from where can I fetch them because we do not log anything as sentry and webhook are external systems,right?

The hooks are triggered by the worker processes as far as I know so getting the logs from those would show whether something fails during the trigger or they don't trigger the hooks at all. If they don't even try, this may be an alert configuration issue on your projects in Sentry.

>2 - Do u have any documentation to update Sentry version which I can refer to do update and check?

 - https://docs.sentry.io/server/upgrading/
 - https://github.com/getsentry/onpremise
 - https://blog.sentry.io/2020/01/07/self-hosted-sentry-10-is-ready-to-serve-get-it-while-its-hot?utm_content=111472566&utm_medium=social&utm_source=twitter&hss_channel=tw-464217126

**Comment by rishbz** [comment]
@BYK So our organisation uses helm upgrade in build script to upgrade helm using command :

+ helm upgrade -i sentry . -f {yaml address} -f {helm yaml} --set{var.}tag=latest --namespace sentry
Release "sentry" has been upgraded. Happy Helming!

It says upgraded but still it runs the older version i.e. 9.0.0

Any idea why is that?

**Comment by rishbz** [comment]
@BYK  So we updated version to 9.1.2 but still webhooks still doesnt work

**Comment by rishbz** [comment]
Team , any response on this? @BYK @scefali

**Comment by BYK** [comment]
@rishbz without the logs we cannot really help with this. Also, please note that we are not actively supporting 9.1.2

**Comment by rishbz** [comment]
@BYK  We are running 9.1.2 - onbuild version . I upgraded to 9.1.2 since official docker site tell 9.1.2 -on build version to be latest . Check https://hub.docker.com/_/sentry/

**Comment by BYK** [comment]
@rishbz - the docker site is maintained by Docker and that version is behind. You can check our (Sentry) documentation and the [on-premise](https://github.com/getsentry/onpremise) to see how to upgrade to the latest version.

**Comment by BYK** [comment]
@rishbz also, we'd still need those logs (you can share logs from 9.1 and we'd still try to help)

**Comment by rishbz** [comment]
@BYK  So i did checked all worker logs - Here's what I did

1. I hit on Test trigger on webhook plugin. On UI it says successfully sent but nothing got generated at worker logs.

2. Then I tried to put random wrong url at webhook plugin in sentry and then hit on Test Trigger - It also says success and with no error log being captured at worker log.

So it looks like @Sentry just doesnot support webhook integration. Please confirm that so i can close this.

**Comment by rishbz** [comment]
@BYK Any response why this is happening?

**Comment by BYK** [comment]
@rishbz - so I tried the same with a local `9.1.2` installation and I definitely got a ping to my test server when using a valid URL. With an invalid URL, the UI still said "test successful" but I saw the following failure on `web` logs:
```
web_1        | ConnectionError: SafeHTTPSConnectionPool(host='i-know-you-dont-exist.com.tr', port=443)
: Max retries exceeded with url: / (Caused by NewConnectionError('<sentry.net.http.SafeHTTPSConnection
 object at 0x7fb9898e9790>: Failed to establish a new connection: [Errno -2] Name or service not known
',))
web_1        | 15:42:33 [ERROR] sentry.safe.webhooksplugin: send_webhook.process_error
```

So it definitely works, there's just a UI bug. Is your webhook domain resolving to an internal IP? That might be the issue as it may trigger some security protections inside Sentry. If that's the case, there's a workaround through the config though.

**Comment by rishbz** [comment]
@BYK  So I re check logs closely from our side and I found out that we do get logs and response when I hit on Test plugin button.

Response looks like this :
`
[sentry-sentry-web-{id}-{id}] 08:48:36 [INFO] sentry.superuser: superuser.request (user_id=235 request_id=u'{guid}' url=u'https://exceptions.{MyOrganization}.com/api/0/projects/sentry/{my-project}/plugins/webhooks/' ip_address=u'223.xxx.xxx.xx' method=u'POST') `

(where ip_address is my ip address here. I hope that is not the issue here? )
`
[sentry-sentry-web-{id}-{id}] 100.117.xxx.xx - - [07/May/2020:08:53:59 +0000] "POST /api/0/projects/sentry/{org_project_name_here}/plugins/webhooks/ HTTP/1.1" 200 967 "https://exceptions.{MyOrganization}.com/settings/sentry/projects/{my project}/plugins/webhooks/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" `

Now, I hit test button with wrong as well as with correct callback URL and the response stays the same in both cases as shown above.

**Comment by rishbz** [comment]
@BYK  Please response by today so I can look at it ASAP as I need to close the case. Tx in advance

**Comment by BYK** [comment]
>Question 1 - (ip_address is my internet ip address in above response. I hope that is not the issue here? )

No, I don't think this would be the issue.

>Question 2:- In webhook, callback URL for Microsoft Team Webhook connector looks like this: https://outlook.office.com/webhook/{guid}@{guid}/IncomingWebhook/{teamGuid}/{ChannelGuid}
>Now, when u say our webhook domain resolving to internal ip, what do u mean by that?

This should be a public API so my comment does not apply to this URL.

>Question 3:- Whats the workaround you are offering ?
>Question 4:- Did u get any idea from our logs, why it is happening?

From what I can tell, the webhook functionality works as expected with the exception of that UI quirk. I won't be able to tell you what is wrong from these limited logs so you'd need to work that out yourself or whoever is maintaining your company's Sentry instance.

>@BYK Please response by today so I can look at it ASAP as I need to close the case. Tx in advance

@rishbz this is not a help service so we cannot guarantee response times or any response at all. Please realize that this is for reporting and solving issues with the open-source project.

Closing as there's nothing we can do on our end to fix this issue, it seems like a configuration or networking problem on your side.
