### ISSUE TITLE
Very minor ugliness when the notification box show on the login for getsentry.com.

### ISSUE THREAD

**Issue by kitsunde** [getsentry/sentry#1844]
On: https://app.getsentry.com/auth/login/media-pop-1/

Put some margin under the box, or not have the top rounded borders. It looks ugly.

<img width="551" alt="screenshot 2015-08-26 13 59 24" src="https://cloud.githubusercontent.com/assets/48965/9486502/9ca2b54c-4bfa-11e5-9391-7ea734c889f2.png">

**Comment by dcramer** [comment]
Just going to wontfix this since v8 will happen very soon and we're focusing all efforts there
