### ISSUE TITLE
When clicking "view on sentry" and needing to log in. Can you direct me to the item I intended to view after login?

### ISSUE THREAD

**Issue by kitsunde** [getsentry/sentry#1845]
In the emails there's a view on sentry:

<img width="687" alt="screenshot 2015-08-26 16 16 08" src="https://cloud.githubusercontent.com/assets/48965/9488590/aaa13be2-4c0d-11e5-8c08-56b89f6b4409.png">

If I'm not logged in, it asks me to login:

<img width="659" alt="screenshot 2015-08-26 16 18 26" src="https://cloud.githubusercontent.com/assets/48965/9488641/ee256c08-4c0d-11e5-89f2-e869aa14ac8f.png">

But it won't remember where I intended to go. So I'm presented with the project view, instead of the issue. I end up tabbing back into my email, clicking the link again to get to where I wanted to go.

**Comment by kitsunde** [comment]
On the same view. Shouldn't it be **Lost your password?** Isn't "**Lose your password?**" ambiguously asking if you want to get rid of your password.

**Comment by dcramer** [comment]
We need to confirm if this is still broken in 8.0.

**Comment by kitsunde** [comment]
This works perfectly on `beta.getsentry.com` which is where my emails are pointing me to, so I'm assuming it's fixed. Cool beans.
