### ISSUE TITLE
Trello - remember board & allow setting labels/user

### ISSUE THREAD

**Issue by kkmuffme** [getsentry/sentry#18476]
## Summary

Improve the trello integration to speed up the workflow:
1) remember the board (& maybe also the list) from last time
2) allow directly adding a label(s) for the trello card
3) allow directly setting a member(s) for the trello card

## Motivation

Currently the Trello integration is mostly useless, since I need to always open the trello card in trello to assign labels (& sometimes members).
This means **currently it's much faster to just directly create the card in trello than to use the integration**

## Additional Context
2 fields for labels & members could easily be added to the existing interface:
![image](https://user-images.githubusercontent.com/11071985/80309989-99213f00-87d8-11ea-8e45-439d476d3265.png)

The trello API calls would be easy to implement, as they are essentially the same as for the "List"

There was a similar request with upvotes which was closed when the trello integration was moved from plugin to the main repo: https://github.com/getsentry/sentry-plugins/issues/283

**Comment by kkmuffme** [comment]
Still annoying af.
Should I contact support by email to get this fixed more quickly?

**Comment by sentaur-athena** [comment]
I'm going to close this issue because plugins are deprecated and we don't support them anymore. To create new integrations please feel free to use integration platform and we're always open to publish community contributions: https://docs.sentry.io/organization/integrations/integration-platform/
