### ISSUE TITLE
test mail work but invite mails not work

### ISSUE THREAD

**Issue by alireza107** [getsentry/sentry#18477]
hi im new to sentry
i install it self host in my server
with docker
my test mail works fine but it doesnt mail for invites

and sorry for my bad english its not my first language

**Comment by BYK** [comment]
This seems like a configuration issue with your workers but it is impossible to help with this little information so closing the issue.

Also, please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
