### ISSUE TITLE
OSError: write error

### ISSUE THREAD

**Issue by jmagnusson** [getsentry/sentry#1850]
I've started seeing empty `OSError: write error` exceptions in Sentry ever since I upgraded raven-python to `5.5.0`? The corresponding log message from uWSGI is:

```
SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /some/path/ (ip 123.123.123.123) !!!
```

Might [this commit](https://github.com/getsentry/raven-python/commit/0ab984b8da5076712d6dce7cfe788b54b039cbf8) be the cause?

**Comment by dcramer** [comment]
@jmagnusson you could try disabling it and see if you still get it, but its not clear to me how it'd be related. Usually that error is safe to ignore, and simply suggests that the client terminated the connection before the backend finished doing whatever
