### ISSUE TITLE
v8 doesn't show discarded data from errors

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#1851]
From v7:

![image](https://cloud.githubusercontent.com/assets/2153/9527381/a9b3632c-4ca3-11e5-9b2a-cbfeb52ebae4.png)

Currently:

![image](https://cloud.githubusercontent.com/assets/2153/9527394/bd943128-4ca3-11e5-9b09-7b907e700bd4.png)

**Comment by dcramer** [comment]
Ideally this would add a 'details' or similar link after each error, and expanding that would give the raw JSON payload (or similar).
