### ISSUE TITLE
The front-end data and database data are inconsistent？

### ISSUE THREAD

**Issue by lpcdma** [getsentry/sentry#18517]
sentry 9.1.2
I try to use sentry to collect user information
During the test, the user reports sentry_message data plus one, which seems to be different in the actual environment
Database query results
```
sentry=# select count(*) from sentry_eventtag;
 count
-------
 98838
(1 row)

sentry=# select count(*) from sentry_eventuser;
 count
-------
 27630
(1 row)

sentry=# select count(*) from sentry_message;
 count
-------
  8822
(1 row)
```

Front-end display
![企业微信截图_15881363112557](https://user-images.githubusercontent.com/2943003/80562079-2b178a80-8a19-11ea-8962-5acad6c31b93.png)

The number of sentry_message should theoretically be greater than sentry_eventuser?

**Comment by untitaker** [comment]
we delete events after 90 days. the other 20k events are likely older than that.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
