### ISSUE TITLE
Separate issue if different domain despite identical stack trace

### ISSUE THREAD

**Issue by kkmuffme** [getsentry/sentry#18524]
## Important Details

How are you running Sentry?
sentry.io

## Description
Sentry separates issues using the stacktrace.
I have example.com, example.fr and example.de all served from the same directory - they are translations of each other.

If an issue occurs on example.com and on example.fr sentry will create 2 separate issues, despite both having the same stack trace.
This leads to loads of duplicate issues.
Especially since I not only have 3 domains/translations but 16 - so we end up with 16 times the same issue.

## Steps to Reproduce
create an error on 3 domains that are translations of each other & served from the same path

### What you expected to happen
Ignore the domain & only compare the stack trace when deciding whether an issue is new/separate or an occurrence of an existing issue.

### Possible Solution

see What you expected to happen

**Comment by BYK** [comment]
Have you [contacted support](https://sentry.io/contact/support/) regarding this?

**Comment by kkmuffme** [comment]
Just did now.

**Comment by BYK** [comment]
Closing then as support should be able to follow up from here. Thanks for the report!
