### ISSUE TITLE
Multiple issues for the same problem

### ISSUE THREAD

**Issue by kkmuffme** [getsentry/sentry#18528]
## Important Details

How are you running Sentry?
sentry.io

## Description
I have 3 identical (same user, same stack trace, same everything, except the timestamp is different) ErrorException issues - why did sentry create 3 issues and not 1 with 3 occurences?
bc like that I have to always manually merge things.

### What you expected to happen

there should be only 1 issue
instead of 3 (D3, D4, D5)

**Comment by BYK** [comment]
Seems like a duplicate of #18524 without enough information so closing.
