### ISSUE TITLE
releases: Identities not synced automatically

### ISSUE THREAD

**Issue by eaigner** [getsentry/sentry#18543]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

I setup GitHub integration and then proceeded to create a new release using `sentry-cli` like this

~~~
$ sentry-cli releases new -p proj1 -p proj2 <VERSION>
$ sentry-cli releases set-commits --auto <VERSION>
$ sentry-cli releases finalize <VERSION>
~~~

After a short bit I got an email saying "Unable to Fetch Commits". I couldn't tell whats wrong, I set up GitHub again just to be sure, still same error.

What did fix it for me is manually and repeatedly visiting https://sentry.io/settings/account/identities/

This seems to force a sync. Sentry just wouldn't sync identities automatically, which is definitely a bug in my book.

**Comment by jonesphillip** [comment]
@eaigner as you noted looks like your GitHub identity in Sentry wasn't synced up for some reason. This typically requires a manual disconnect and reconnect of your identity which you figured out (see help article below). Closing this out for now.

https://help.sentry.io/hc/en-us/articles/360019866834-Why-am-I-receiving-the-email-Unable-to-Fetch-Commits-

**Comment by eaigner** [comment]
Yeah. And this should obviously not happen, and people should not have to look up a blogpost to know why its not working. Why cant this be synced on connect? Or at least display "account not synced" or some notification that tells me to manually sync.

Just not displaying any error at all or anything is a bit weird.

**Comment by jonesphillip** [comment]
Fair point, will get a task together to investigate try and include more information there at least.
