### ISSUE TITLE
Setup Sentry remaining tasks, Create a Project never goes away.

### ISSUE THREAD

**Issue by tlf30** [getsentry/sentry#18561]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

In the Setup Sentry remaining tasks, Create a Project never went away.

![image](https://user-images.githubusercontent.com/10089434/80821488-4b645800-8b85-11ea-853e-2ce56e91b8a2.png)

## Steps to Reproduce

1. Create new account
2. Create Project

### What you expected to happen

The task should be checked off.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by tlf30** [comment]
@BYK this is still an issue on my account.

**Comment by BYK** [comment]
@tlf30 have you tried contacting support for this?

**Comment by tlf30** [comment]
No I have not. This looked to be more like a glitch in the code considering that my self hosted instance did not have this issue.

**Comment by BYK** [comment]
@tlf30 even if it is a bug in the code, going through support lets us investigate your account in a safe way so please go over that channel first.

**Comment by BYK** [comment]
Closing the issue in favor of support. Please let us know if you cannot use that route or get a resolution through support and we'll reopen and investigate.
