### ISSUE TITLE
Template file for Teamwork plugin does not get inside docker image

### ISSUE THREAD

**Issue by ffauvel** [getsentry/sentry#18612]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version Sentry 10.1.0.dev06e9f429

## Description

Teamwork integration is missing the create_issue.html template file.

sentry_plugins/teamwork/templates/sentry_teamwork/create_issue.html is missing.

You can look inside the web docker image in /usr/local/lib/python2.7/site-packages/sentry_plugins/teamwork/ and the templates folder is missing.

## Steps to Reproduce

1. Enable integration with Teamwork
2. Try to create a new Teamwork task from a Sentry issue
3. Getting an error page

![image](https://user-images.githubusercontent.com/1152273/81035873-c91cb200-8e6a-11ea-89a1-ff09d2c3089d.png)

Log is showing this error: TemplateDoesNotExist: sentry_teamwork/create_issue.html (9 additional frame(s) were not displayed) ... File "sentry/web/frontend/group_plugin_action.py", line 25, in handle

### What you expected to happen

Manually copying the missing templates folder into the docker container fix the problem.
I'm getting the Create Teamwork Task page.

![image](https://user-images.githubusercontent.com/1152273/81036008-60820500-8e6b-11ea-9321-fb5ecbaba1e1.png)

### Possible Solution

I don't know much about python packaging, something is excluding that packages/sentry_plugins/teamwork/templates/ folder when packaging the .whl file.

**Comment by ffauvel** [comment]
/usr/local/lib/python2.7/site-packages/sentry/static/sentry/vendor/ folder is also missing in the docker container

**Comment by BYK** [comment]
Oops, sorry about this. Will fix very soon.
