### ISSUE TITLE
[Javascript] Function name is not retrieved from sourcemap

### ISSUE THREAD

**Issue by moroine** [getsentry/sentry#18614]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 9.1.2

## Description

Sentry error name location is not using sourcemap for function name.

![image](https://user-images.githubusercontent.com/4658821/81037664-df932f80-8ea3-11ea-9a72-26e116836097.png)

![image](https://user-images.githubusercontent.com/4658821/81037712-02bddf00-8ea4-11ea-9532-48de63c4bde3.png)

But sourcemap is valid 
![image](https://user-images.githubusercontent.com/4658821/81038099-34837580-8ea5-11ea-9e65-19f202f722ad.png)

### What you expected to happen

The function name should be extracted from the source map

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
