### ISSUE TITLE
BufferError: Local: Queue full

### ISSUE THREAD

**Issue by stayallive** [getsentry/sentry#18624]
I am receiving this error once every 2-4 days and I need to restart Sentry to fix it. This started after moving to the Docker version of Sentry.

I never noticed this being an issue on 9.1.2 also with Clickhouse and Snuba running, but without Kafka.

> https://observ.app/share/issue/4e4f208a500d48cc898770930706959a/

I am not sure where to look / poke / monitor to see this queue that is being spoken of and how I can flush it / enlarge it if needed.

`sentry queues list` showed all 0's so it's not looking like there is a massive backlog of events.

Any help is appreciated!

**Comment by BYK** [comment]
@ibm5155 it seems like this is indeed a missing `poll(0)` call as @petrprikryl suggested above. I'll verify and submit a patch.

**Comment by mattrobenolt** [comment]
Why don’t we have an issue with this ourselves in production? I’d be skeptical of slapping down a patch without understanding that. 

cc @getsentry/sns

**Comment by tkaemming** [comment]
We do see this in Snuba from time to time, but only with a producer that follows a similar usage pattern as the one in Sentry. We haven't seen this in any producers that explicitly call `flush` (the main consumer calls flush immediately after producing batches of replacements, subscriptions continually calls poll in a separate thread.)

**Comment by BYK** [comment]
>Why don’t we have an issue with this ourselves in production?

We simply may have more resources at hand. Also, AFAIK relay would mitigate most of the issue for outcomes. /cc @jan-auer 

>I’d be skeptical of slapping down a patch without understanding that.

There are [multiple](https://github.com/confluentinc/confluent-kafka-python/issues/137#issuecomment-282427382) [issues](https://github.com/confluentinc/confluent-kafka-python/issues/16#issuecomment-231224794) on Kafka repo itself, strongly recommending the use of a `poll(0)` before or after a publish.

**Comment by jan-auer** [comment]
FWIW, the Kafka library we use in Relay also [calls `poll` in regular intervals from a background thread](https://docs.rs/rdkafka/0.23.1/rdkafka/producer/base_producer/struct.ThreadedProducer.html). 

> AFAIK relay would mitigate most of the issue for outcomes.

Tiny clarification and disclaimer: I do not know what the root cause of this is, that is, why sending the message is rejected. With the introduction of Relay to onpremise we've also added an outcomes _consumer_. So if the problem is that Kafka no longer accepts because it fills up or the offset gets too large, then that added consumer will help.

**Comment by BYK** [comment]
>So if the problem is that Kafka no longer accepts because it fills up or the offset gets too large, then that added consumer will help.

I think this is happening even with that consumer.
