### ISSUE TITLE
Broken account: Too many redirects when logging in

### ISSUE THREAD

**Issue by fmalina** [getsentry/sentry#18642]
I have an account with sentry that is unusable because it triggers too many redirects on login.

To help you replicate the bug: Broken account is at fmalina@pm.me, maybe I tried to delete this account in the past as it accumulated too many pointless log events really fast due to a warning coming from GeoDjango on every request I didn't know how to overcome.

**Comment by BYK** [comment]
Have you tried [contacting our support](https://sentry.io/contact/support/) for this?
