### ISSUE TITLE
Configure Sentry in a repo that uses Mikro-ORM #551

### ISSUE THREAD

**Issue by Loown** [getsentry/sentry#18658]
I tried to configure Sentry in my NestJS API that uses Mikro-ORM, but when I installed Sentry I got this error :

> node_modules/mikro-orm/dist/utils/RequestContext.d.ts:7:11 - error TS2451: Cannot redeclare block-scoped variable 'active'.
> 
> 7     const active: ORMDomain;
>             ~~~~~~
> 
>   node_modules/@sentry/hub/dist/hub.d.ts:5:9
>     5     let active: Domain;
>               ~~~~~~
>     'active' was also declared here.

**Comment by BYK** [comment]
Sorry, this is not enough information for us to understand what's going on so closing this issue. Moreover, please file SDK-related issues in the relevant repos. For this one, it would be [getsentry/sentry-javascript](https://github.com/getsentry/sentry-javascript).
