### ISSUE TITLE
Feature request: Resolve Sentry events from GitHub pull requests

### ISSUE THREAD

**Issue by hkdobrev** [getsentry/sentry#1868]
Similar to how you can close/fix/resolve GitHub issues from commits and pull requests in GitHub I'd like Sentry to have a bot which listens to commits on the master branch and close Sentry events as fixes get pushed/merged.

We are using such system at Clippings.com which works with the GitHub and Trello APIs to move Trello cards to a done list. We just add "Fixes https://trello.com/c/....` with the corresponding Trello URL in the PR description and the bot which lives on our Trello board is moving the card automatically when the fix is on master.

**Comment by ashwin31** [comment]
consider gitlab too, we are using gitlab

**Comment by dcramer** [comment]
I think it's a nice to have, but realistically an event is only resolved in Sentry when it stops happening. Due to this we're pushing in the direction of simply being release-aware and giving you better context of "whats happening in the current version of my application".

**Comment by ashwin31** [comment]
@dcramer okay, I am eager to try 8.0. Lets see it.

**Comment by hkdobrev** [comment]
@dcramer When you have a bug logged in Sentry and you fix the bug you would normally mark it as resolved. If it emerges later for whatever reason, it's counted as a regression, you get notified again and it will be unresolved again. I think this workflow would continue to work with or without releases. So I don't think the 0.8 version (which is otherwise great!) or the improvements to release tracking would change it much.

However I realize it's a nice-to-have and it's for the future. It's just that for our team it is be a really-nice-to-have.

Cheers!

**Comment by dcramer** [comment]
@hkdobrev the main complexity is "what happens if its seen again after you mark it as resolved, but havent deployed the fix?"

**Comment by ajwhite** [comment]
+1

**Comment by hkdobrev** [comment]
@dcramer 
> the main complexity is "what happens if its seen again after you mark it as resolved, but havent deployed the fix?"

I see two scenarios:

1. When people merge to master, but deploy only when a deploy/release process is scheduled.
1. When people are using a CI and deploy immediately what's on master, but the Sentry event happens again before the deploy has finished.

In both cases a system could be used which resolves Sentry events when the deploy has finished rather on commit. E.g. a Travis CI `after_deploy` hook or any other CI hooks.

Also the 2nd case is less probable as most deployments would finish in a few minutes and something which close the Sentry event when merged would work for many organizations (personal opinion).

**Comment by hkdobrev** [comment]
@dcramer I see you have resolved your concerns beautifully with http://blog.getsentry.com/2015/11/25/resolve-in-next-release.html. :clap:

**Comment by benvinegar** [comment]
We made this happen in 2017: https://blog.sentry.io/2017/05/01/release-commits.html

**Comment by hkdobrev** [comment]
🙌 🎉 🚀

**Comment by benvinegar** [comment]
> I personally don't see why not closing with "Fixes <Sentry URL>"

I suppose we could explore adding that.

**Comment by urbanit** [comment]
Status?

**Comment by BlitZz96** [comment]
I am not sure if I have a wrong setup, but adding `fixes  <SHORT-ID>` in pull-requests does not work for me. However, adding the same in a commit-message does.

My question is: Is it possible to close sentry issues by adding `fixes  <SHORT-ID>` in PR description/comments?

**Comment by dcramer** [comment]
it should, but you need github integration wired up fully

**Comment by BlitZz96** [comment]
Okey, then probably I am missing adding commits manually since I am using the webpack plugin.
Maybe https://github.com/getsentry/sentry-webpack-plugin/pull/139 would fix it for me 🤷‍♂ 
Thanks for the reply @dcramer
