### ISSUE TITLE
Sentry not reporting CPU brand for Unreal crash reports

### ISSUE THREAD

**Issue by regner** [getsentry/sentry#18714]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

Crash reports from Unreal don't indicate the CPU brand even though it is in the crash context.

## Steps to Reproduce

1. Point Unreal crash reporter at Sentry
2. Cause crash
3. See events in Sentry

### What you expected to happen

I expect both CPU and GPU models to show up in the event details.

### Possible Solution

Looking at the symbolic Rust code I can see the CPU brand being pulled from the XML: https://github.com/getsentry/symbolic/blob/de12af604bca33e8c72bc785d348273bf08d79ab/unreal/src/context.rs#L225

I would think this just requires adding:

```python
    cpu_brand = runtime_prop.pop("misc_cpu_brand", None)
    if cpu_brand is not None:
        set_path(event, "contexts", "cpu", "name", value=cpu_brand )
```
 
To the unreal endpoint, somewhere around here: https://github.com/getsentry/sentry/blob/a41121b3c8a159919a96986013636a7262e1aeac/src/sentry/lang/native/unreal.py#L98

**Comment by BYK** [comment]
@jan-auer sent this your way but feel free to pass it over.

**Comment by jan-auer** [comment]
@regner Thanks for reporting this.

> Crash reports from Unreal don't indicate the CPU brand even though it is in the crash context.

While it's not ideal, you should be able to see the CPU listed as `misc_cpu_brand` and `misc_cpu_vendor` in the Unreal context on the issue details page. 

> I would think this just requires adding: [...]

This is a great suggestion. At the moment, we do not have a standardized context for CPU information. The only contexts we specify are listed [on this page](https://develop.sentry.dev/sdk/event-payloads/contexts/). I'll look into adding this.

**Comment by regner** [comment]
As the CPU information is now shown in the Unreal section I think this can be closed.
