### ISSUE TITLE
sdist fails cause webpack.config.js is not being found.

### ISSUE THREAD

**Issue by mvaled** [getsentry/sentry#1871]
Trying to create a source distribution fails with:

      File "setup.py", line 181, in run
	cwd=work_path)
      File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
	raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['node_modules/.bin/webpack', '-p']' returned non-zero exit status 255

I noticed the actual sdist is being done inside a `sentry-8.0.0dev0` directory, where `webpack.config.js` is not being copied.   I copy it by hand and it works.  Also placing it in the MANIFEST.in works.

**Comment by dcramer** [comment]
Thanks @mvaled! We hadn't tested the new v8 packaging fully yet.

**Comment by mvaled** [comment]
Well, I must say it seems well enough for my environment.  I created the source distribution and upgraded my on-the-premises server a few moments ago, and now I can happily (?!) assign events to people.. ;)
