### ISSUE TITLE
Bitbucket Server Integration throws errors on PR merges

### ISSUE THREAD

**Issue by tm1000** [getsentry/sentry#18729]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 10.1.0.dev087a67ca

## Description

We have the bitbucket server plugin running. But we experience errors from Sentry when merging pull requests.

## Steps to Reproduce

1. Link a repository to sentry through bitbucket server plugin
2. Create a pull request
3. Merge the pull request

```
ApiError: {"errors":[{"context":null,"message":"Commit '0000000000000000000000000000000000000000' does not exist in repository '<repository>'.","exceptionName":"com.atlassian.bitbucket.commit.NoSuchCommitException"}]}
  File "django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "sentry/integrations/bitbucket_server/webhook.py", line 117, in dispatch
    return super(BitbucketServerWebhookEndpoint, self).dispatch(request, *args, **kwargs)
  File "django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "sentry/integrations/bitbucket_server/webhook.py", line 158, in post
    handler()(organization, integration_id, event)
  File "sentry/integrations/bitbucket_server/webhook.py", line 69, in __call__
    project_name, repo_name, from_hash, change.get("toHash")
  File "sentry/integrations/bitbucket_server/client.py", line 146, in get_commits
    params={"since": fromHash, "until": toHash, "merges": "exclude"},
  File "sentry/shared_integrations/client.py", line 272, in get
    return self.request("GET", *args, **kwargs)
  File "sentry/shared_integrations/client.py", line 254, in request
    return self._request(*args, **kwargs)
  File "sentry/shared_integrations/client.py", line 243, in _request
    raise ApiError.from_response(resp, url=full_url)
```

### What you expected to happen

I believe it should ignore any commits with a sha of 0000000000000000000000000000000000000000

tagging @pierredup since he's the original contributor of said plugin

**Comment by tm1000** [comment]
Searching google you can see commit '0000000000000000000000000000000000000000 ' is a pretty common occurrence on bitbucket

https://www.google.com/search?q=bitbucket+commit+0000000000000000000000000000000000000000&oq=bitbucket+commit+0000000000000000000000000000000000000000&aqs=chrome..69i57j0l5j69i61l2.2021j0j7&sourceid=chrome&ie=UTF-8

**Comment by pierredup** [comment]
@tm1000 Empty commits are already excluded

https://github.com/getsentry/sentry/blob/b08b83468cc95d7b69d6d3973689fc8c19c127e2/src/sentry/integrations/bitbucket_server/webhook.py#L67

I'll investigate a bit and see if I can replicate the issue.

**Comment by tm1000** [comment]
@pierredup the errors aren't blocking. It's just sent to sentry and we get emails about there being an issue FYI

**Comment by tm1000** [comment]
I just upgraded to 20.9.0 and still get these errors.

**Comment by BYK** [comment]
@philipphofmann ping for triage

**Comment by BYK** [comment]
Sorry, meant @getsentry/ecosystem and @jonesphillip for triage.

**Comment by tm1000** [comment]
@BYK something to consider about this is that technically Atlassian is sunsetting Bitbucket Server in favor of their cloud only solution (except for datacenter). While it'd be nice to get this fixed my company is probably moving to github enterprise.

**Comment by BYK** [comment]
@tm1000 thanks for the heads up! That said "the future is the cloud" 😁

**Comment by manuzope** [comment]
Looks like this is happening because the `changes.[].toHash` is 0*40. Here's what a sample webhook payload looks like in these cases:
```
{
  ...
  "changes":[
    {
      "fromHash":"d8c234547421793bb8ac9cfd1741ae5e439c8c17",
      "ref":{
        "displayId": "STUFF-123", 
        "id": "refs/heads/STUFF-123", 
        "type": "BRANCH"
      },
      "refId":"refs/heads/STUFF-123",
      "toHash":"0000000000000000000000000000000000000000",
      "type":"DELETE"
    }
  ],
  ...
}
```
The `type`, from the samples I've seen, is always `DELETE`. I don't know what that means and the [Bitbucket documentation](https://confluence.atlassian.com/bitbucketserver/event-payload-938025882.html) doesn't say much. If anyone else knows about why the `toHash` is the way it is, would appreciate the help.

We'll add it to our backlog to see what we can do about it but given Atlassian is sunsetting Bitbucket Server, it likely won't be high on our priority.
