### ISSUE TITLE
Link the Unreal build_version to Sentry release version

### ISSUE THREAD

**Issue by regner** [getsentry/sentry#18733]
## Summary

Issues from the Unreal integration don't have a release set. I would like to propose using the build_version that is included in the Unreal crashes and already parsed by the symbolic code.

## Motivation

Not having the ability to mark things as fixed until next release and just use the release features in general very much hurts our ability to use Sentry to the full extent.

The recommendation within the Unreal development community is to put your version in the build_version attribute. There is another engine_version which is meant to be the version of the base Unreal source that you're using.

So yeah, build_version -> release please!

**Comment by regner** [comment]
As with my other feature request, I am happy to do the development on this just looking for a go ahead that you guys agree this is the appropriate solution.

**Comment by jan-auer** [comment]
For setting releases, we recommend doing this manually during setup. There are mainly two reasons:

- Releases in Sentry are global to the entire organization. This means if you have a build version of `4711` in two of your games, then they would be associated with the same release. To counter this, we recommend to name a release in the format: `game-name@1.2.3+4711`. 
- The characters you can use for a valid release name in Sentry are constrained. We've observed that the `build_version` can also contain arbitrary names and is not guaranteed to match our constraints.

We have documented [here](https://docs.sentry.io/platforms/native/guides/ue4/advanced-config/) how to set a custom `release` during crash reporter initialization. You can read the build version programmatically and then set it into the crash reporter like this:

```c++
#include "GenericPlatform/GenericPlatformCrashContext.h"
#include "Dom/Json.h"

void ConfigureCrashReporter()
{
    TSharedPtr<FJsonObject> config = MakeShareable(new FJsonObject);

    config->SetStringField("release", BUILD_VERISION_GOES_HERE);
    config->SetStringField("environment", "production");

    FString jsonConfig;
    TSharedRef<TJsonWriter<>> jsonWriter = TJsonWriterFactory<>::Create(&jsonConfig);
    FJsonSerializer::Serialize(config, jsonWriter);

    FGenericCrashContext::SetGameData(TEXT("__sentry"), jsonConfig);
}
```

**Comment by regner** [comment]
Thank you very much for the response. I have passed this on to the Engine team here and will leave it with them for now.

Again, thanks for the help on this.
