### ISSUE TITLE
Bitbucket Server Integration: incorrect docs link

### ISSUE THREAD

**Issue by carwynmoore** [getsentry/sentry#18735]
Docs page link 404

On this page:
https://sentry.io/organizations/modica/integrations/bitbucket_server/setup/?

![image](https://user-images.githubusercontent.com/17467757/81603262-29d75c00-9422-11ea-9780-d002c1d6a34c.png)

There is a 'required steps' link to https://docs.sentry.io/workflow/integrations/global-integrations/bitbucket-server/ which gives a 404 Not Found.

It looks like it should be this instead (close!)
https://docs.sentry.io/workflow/integrations/global-integrations/#bitbucket-server

**Comment by jonesphillip** [comment]
@carwynmoore thanks for pointing this out. Will get that fixed!
