### ISSUE TITLE
how to realize feature "delete and discard the future events"  on k8s?

### ISSUE THREAD

**Issue by maggiezhangfan** [getsentry/sentry#18753]
We use helm install sentry on k8s,when we want to delete and discard the future events,it remind us enable this feature need to change the sentry.conf.py and add the following configuration "SENTRY_FEATURES['projects:discard-groups'] = True", i want to know, on k8s, can we add this configuration to configmap to realize this feature.

**Comment by maggiezhangfan** [comment]
i have been solved it by adding config in configmap and restart web node.

**Comment by samatcd** [comment]
@maggiezhangfan, how did you add this config?
