### ISSUE TITLE
Sentry v10 onPrem Upgrade failing due to database upgrade error

### ISSUE THREAD

**Issue by maxp1256** [getsentry/sentry#18755]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 10.1.0.dev 0f07352b

## Description

I'm trying to upgrade to the latest v10 onprem build using install.sh and getting an error:
clickhouse_driver.errors.ServerException: Code 62.
DB::Exception: Syntaxerror: failed at position 2152 (line 7, col 13): TTL timestamp + toIntervalDay(retention_days)
SETTINGS index_granularity=8192;. Expected one of the following ...

**Comment by nicolasbadia** [comment]
Same problem here

**Comment by BYK** [comment]
You may have better luck trying now as we have made a bunch of improvements and fixes. If not, please file a new issue over at [getsentry/onpremise](https://github.com/getsentry/onpremise) as that's the relevant repo.
