### ISSUE TITLE
Need logs like firebase to know activities user navigated before crashing

### ISSUE THREAD

**Issue by junaid-umar** [getsentry/sentry#18754]
It is very difficult sometimes to debug as modern day app uses alot of third party libraries and sometime a simple crash report is not enough to debug.To make it easier log feature helps a lot to create the event like user device.

## Motivation

app is being used on multiple device with different specs on android. it is not easy to sometime debug by simple report and it consumes a lot of time.To make it easy logs feature should be implemented like firebase.

**Comment by marandaneto** [comment]
hey @junaid-umar have you tried the `sentry-android` v2? we do collect automatic breadcrumbs.

https://github.com/getsentry/sentry-android/releases

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
