### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled

### ISSUE THREAD

**Issue by MrJiangZhiGuo** [getsentry/sentry#18782]
When I reported in the local project execution, I encountered this problem that does not allow cross-domain requests. How to solve it, I am waiting for it online!
![image](https://user-images.githubusercontent.com/26242617/81765251-e524f100-9505-11ea-88ab-8130cfffef40.png)
![Uploading image.png…]()

**Comment by susananddaicy** [comment]
how to solve it ？ thank you

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
