### ISSUE TITLE
Can't create environments with some special characters

### ISSUE THREAD

**Issue by JoelAzevedo** [getsentry/sentry#18796]
## Important Details

How are you running Sentry?
Other, version 5.15.5, [Angular 8.2]

## Description

I have several angular 8 applications with sentry and I want to create environments based on the hostname and app name. something like: _example.com/backoffice_ Unfortunately, I can't have the "/" character, no matter what I do.

I had to create a resulting environment like _example.com_backoffice_ just because when I used "/" the environment was not detected on Sentry's dashboard.

## Steps to Reproduce

In my Typescript, when I initialize the environment, If I write this:

```
Sentry.init({
  dsn: environment.sentryDsn,
  environment: environment.hostname + '/backoffice'
});
```
the environment is not set.

If I write this:
```
Sentry.init({
  dsn: environment.sentryDsn,
  environment: environment.hostname + '_backoffice'
});
```
it is defined and appears.

Anyone with the same issue?

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2154) by [Unito](https://www.unito.io)

**Comment by vnenkpet** [comment]
True. I had a similar issue with this and couldn't find the reason for this. This should at least be documented, currently the docs say the only non-allowed characters are newline and whitespace and that it cannot be the string "None"

**Comment by PeloWriter** [comment]
We have added to the content regarding naming environments. I suggest we can close this issue.

> Sentry automatically creates environments when it receives an event with the environment tag. Environments are case sensitive. The environment name can't contain newlines, spaces or forward slashes, can't be the string "None", or exceed 64 characters. You can't delete environments, but you can hide them.

**Comment by chadwhitacre** [comment]
> I suggest we can close this issue.

No objection here. :)

**Comment by markstory** [comment]
Closing as we currently use environment name as a URL path parameter which is why `/` is not allowed.
