### ISSUE TITLE
Get a single users error

### ISSUE THREAD

**Issue by tarjei** [getsentry/sentry#18790]
## Summary
I want to see a concrete users error for a given type of errors

## Motivation

If I get a bug report from a single user and search for that user in Sentry I might get an issue that 1000 users has had (HTTP request failed f.x.) but I'm interested only in the errors that that user had. When I click on the issue I get the latest error that has occured. I want a way to say "I only want to see and inspect the _concrete_ errors that have been tagged by this user.

Why should this be worked on? What problems or use cases does it solve or
improve?

This makes it a lot easier to debug bugreports from users that are incomplete or where it is hard to know what has happened. 

Today the only way to do this is to click through the history of the issue one by one and hope you find the users event.

**Comment by saifelse** [comment]
You should check out [Discover](https://docs.sentry.io/product/discover-queries/), and filter by `user`. You can click into an issue to the specific event for the given user.

![image](https://user-images.githubusercontent.com/549473/97145548-98d01500-1723-11eb-9f30-9a027aaa473d.png)

**Comment by tarjei** [comment]
:+1: Will do! Thanks for the tip!
