### ISSUE TITLE
I cannot access sentry over ELB

### ISSUE THREAD

**Issue by ahmedTouati** [getsentry/sentry#18810]
## Important Details

How are you running Sentry?

On AWS EKS cluster

## Description

i tried exposing sentry on loadbalancer by changing service type to load balancer and adding this annotation **service.beta.kubernetes.io/aws-load-balancer-internal: "true"** so i can access it from within my vpc but the url is still loading indefinitely i tried that with nginx and it worked but with elb it doesn't.

### What you expected to happen

i can access sentry through the generated loadbalancer url.

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
