### ISSUE TITLE
GitLab integration - possible api pagination problem: Link issue dialog shows only 20 projects

### ISSUE THREAD

**Issue by DirkLachowski** [getsentry/sentry#18850]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

- We have a  working integration to our on prem gitlab (latest version). 
- The linked group contains about 60 projects on the first group level and about 10 subgroups, bringing to project count to about 150
- When we try to create or link a sentry issue to gitlab, only 20 projects are shown - a random list of projects in the parent group and in subgroups
- Most of the time the one project we want to link to is missing because of the truncated list 

## Steps to Reproduce

1. Integrate with a gitlab group with more than 20 projects
2. Try to create an issue in gitlab
3. Compare the project count in gitlab and in the sentry dialog

### What you expected to happen

All projects should be shown, not only a truncated list

### Possible Solution

This seems to be a pagination problem, 20 items shown corresponds to the default api pagesize in gitlab. See https://docs.gitlab.com/ee/api/#offset-based-pagination

**Comment by markstory** [comment]
The project dropdown allows you to autocomplete the name of the project you want by typing. We don't load all the projects from gitlab as it is an unbounded set and preparing the form could timeout.
