### ISSUE TITLE
Page contents below sidebar when switching from Admin

### ISSUE THREAD

**Issue by VentyCZ** [getsentry/sentry#18866]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 10.1.0.dev (09dc4ddf - latest on-premise)

## Description

When switching from Admin page (/manage/) to Projects or other pages, the page contents are partially obstructed by sidebar.
Screenshot of clean install: https://gyazo.com/081e59d0a994aff19b86c8688117ec9e

## Steps to Reproduce

1. Open Admin from submenu or navigate to /manage/
2. Click "Projects" on sidebar to switch to Projects page
3. Projects page contents are obstructed by sidebar

### What you expected to happen

Contents should not be obstructed.

### Possible Solution

There seems to be a missing class on <body> - "body-sidebar" - which adds padding to the body.

**Comment by EvanPurkhiser** [comment]
Thanks, I see this too. brewing up a fix here https://github.com/getsentry/sentry/pull/18924
