### ISSUE TITLE
8.0 client router doesn't support url prefixes

### ISSUE THREAD

**Issue by beeftornado** [getsentry/sentry#1887]
The router it seems assumes that the project will be hosted at root (/), but it is possible for an on-premise install to be running off a subpath (/sentry), which breaks most views in the new UI. This doesn't look like an easy fix unfortunately.

**Comment by dcramer** [comment]
We could make the routes more dynamic if we had to, so i dont think its too hard.

i.e.

```
<Route name="app" path={urlPrefix + "/"} handler={App}>
```

**Comment by beeftornado** [comment]
Just some exploratory findings...To get the new UI to work under a subpath I had to set the parent route path and make all subsequent route paths relative. I also had to update the api.jsx baseUrl. I was making static changes just to find the places that needed updating.

**Comment by dcramer** [comment]
We're going to have to change how the API works. Client currently gets built at runtime which won't work. We could probably make it so we can do setBaseUrl or similar on it.

**Comment by mattrobenolt** [comment]
@dcramer Do we have plans to support this in the future?

**Comment by dcramer** [comment]
IMO this is stll a TODO

I strongly believe "just use a subdomain" is a fine solution, but I know sometimes it causes complexities. This isn't that hard to support, we just need to sit down and do it.

**Comment by zhujunsan** [comment]
Any update on this issue?

**Comment by dcramer** [comment]
@zhujunsan this is not high priority for us as we've never officially supported prefixes (and there's no good reason for us to, either). Unlikely to be addressed anytime soon without a community PR.

**Comment by arthurlogilab** [comment]
Hi, I would be interested in this too. 

A colleague that does a bit of react tells me that react-router 4.0 has a mechanism for this with a "SwitchRoute" that has to be added to all the routes. Which versions of react-router are on the roadmap ?

**Comment by dcramer** [comment]
I'm just going to close this out as we have no desire to add additional complexity to Sentry with subpaths. There's no real reason to do it when you can simply setup a subdomain (which has other benefits), and theres are a lot of complexity in Django, React, and surely anything else we'd ever do here. I think if people put forward the effort (including tests, to ensure stability) to support it, then we wouldn't be opposed to patches, but I'd rather avoid "we might do this" if we're literally never going to do it ourselves.

https://github.com/getsentry/sentry/pull/5173
