### ISSUE TITLE
Percy: every PR produces new transaction event ID

### ISSUE THREAD

**Issue by rhcarvalho** [getsentry/sentry#18898]
Recent PRs that don't make any UI changes are producing diffs in Percy:

https://github.com/getsentry/sentry/pull/18896 - https://percy.io/getsentry/sentry/builds/5313235

https://github.com/getsentry/sentry/pull/18897 - https://percy.io/getsentry/sentry/builds/5313291

The only difference is the ID of a transaction event.

![image](https://user-images.githubusercontent.com/88819/82316867-b9a27a80-99cd-11ea-87e5-f610a3bb2873.png)

I guess it needs to be a fixed ID to avoid the noise in Percy.

**Comment by matejminar** [comment]
Thanks for bringing this up, should be fine now.
