### ISSUE TITLE
GitHub Integration: 

### ISSUE THREAD

**Issue by zachheine** [getsentry/sentry#18907]
I integrated on the Github side but Sentry doesn't appear to pick up the changes.

**Comment by EvanPurkhiser** [comment]
Could you provide more information? What changes?

**Comment by dchaur** [comment]
We are having the same issue, Sentry appears installed on GitHub but not on Sentry 
![image](https://user-images.githubusercontent.com/28889792/83849709-1b721c80-a710-11ea-8a56-38166faf3b25.png)

**Comment by CADbloke** [comment]
Same here. the "Github (Legacy)" integration seems to work but the "Github" integration is broken, says "Set up Issue Tracking" near Linked Issue. Turning the legacy integration off just breaks things. 

I am assuming you want us to get off the legacy integration?

**Comment by calebfaruki** [comment]
Same issue. My account lists my repos under the configurations tab. But it still says "Add Installation". That, along with the fact that the commit blaming part of Sentry errors suggests that the integration is broken.

I tried to delete the Github integrations after deleting the Sentry integration on the Github side. But I am not able to delete it from the Sentry side.

**Comment by BYK** [comment]
Is this on sentry.io or are you using self-hosted? If self-hosted which version and have you followed this guide: https://develop.sentry.dev/integrations/github/ o
