### ISSUE TITLE
Explore an organization-wide dashboard

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1891]
This gets a bit complex in some organizations, but the idea is to restore some level of functionality from a team dashboard.

it could also be we let you create "views" (which is just an arbitrary dashboard where you can choose which projects you care about). One obvious area is having a dashboard which shows things like "Assigned to Me" on the organization dashboard.

I'd want this to be more than our previous team dash, which had limited use.

**Comment by jsocol** [comment]
Losing the team dashboard really broke Sentry for my multi-service architecture, leaving a few bad options (send everything into the same project, take time to build a dashboard on my own, run an old version of sentry myself, transition everything to something like ELK).

The key functionality that I'm missing is an overall, cross-project view of new and trending events. A more composable, Kibana-style dashboard sounds great, but in the meantime this was an important way to visualize data, far more valuable than a rough visualization of how many messages each project produces.

**Comment by billyvg** [comment]
Closing this as we have several features that address this
