### ISSUE TITLE
Bitbucket Integration: Only shows me my personal repos

### ISSUE THREAD

**Issue by parsley72** [getsentry/sentry#18929]
When I log into my work Bitbucket account I can only select my personal repos - the company ones don't appear in the list. Do I need an additional permission?

**Comment by parsley72** [comment]
Sentry.io support said:
> You need to be an Owner or Manager in Sentry (your role is Admin right now) and have Admin permissions in the Bitbucket repo to configure the integration:
> https://docs.sentry.io/workflow/integrations/global-integrations/#bitbucket

But I'm having the same problem. I'm not sure why Sentry.io allows me to attempt the connection if I don't have Owner or Manager rights? There should at least be a warning.

**Comment by jonesphillip** [comment]
@parsley72 Were you able to confirm you have correct permissions? Was it working then?

**Comment by vstanyshevskyy** [comment]
I'm having the same problem. I'm the owner of Sentry org and I'm the admin of company bitbucket repo, but it doesn't appear in repos list in Sentry

**Comment by chadwhitacre** [comment]
@parsley72 @vstanyshevskyy Is this still a problem for you? If so we'll ask @getsentry/ecosystem to (re-)triage.
