### ISSUE TITLE
Jira Server Integration no longer working

### ISSUE THREAD

**Issue by mcastets** [getsentry/sentry#18935]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

We can no longer link an issue with Jira Server nor we can access to the Settings > Org > Integrations page.

We think it may be related to Jira Server because we're still able to use "Link Bitbucket issue".

There's always an error page:

<img width="624" alt="Capture d’écran 2020-05-20 à 14 56 53" src="https://user-images.githubusercontent.com/4427447/82448627-44f13e00-9aaa-11ea-8edf-0516716c704d.png">

## Steps to Reproduce

1. Open any issue
2. Click on "Link Jira Server Issue"
3. Error

## Expected

Linking an issue with Jira server should be possible as it used to be.
If this problem is caused by Jira Server then the settings > org > integrations page should be working and report a configuration issue.

**Comment by scefali** [comment]
@Mathieu-Castets I can debug if I have more information. Could you email me the organization slug? My email is scefali@sentry.io.

**Comment by mcastets** [comment]
I see some thumbs up on my original post, maybe we're no longer the single organization to experience this? Any progress?

**Comment by manuzope** [comment]
Hi @mcastets, this is a strange error. Could you try uninstalling and reinstalling the integration to see if the problem still persists?

**Comment by mcastets** [comment]
> Hi @mcastets, this is a strange error. Could you try uninstalling and reinstalling the integration to see if the problem still persists?

Awesome :) Reinstalling the integration was the solution! 

I'm closing the issue. Thanks for the support.
