### ISSUE TITLE
Improve Java issue groupings by ignoring generated stack traces

### ISSUE THREAD

**Issue by krconv** [getsentry/sentry#18959]
## Summary
In https://github.com/getsentry/sentry/issues/13304, Sentry started ignoring stack traces that came from the `jdk.internal.reflect.GeneratedMethodAccessorXX` class because it was causing errors in Sentry to create a new Issue ever time it was thrown (the culprit or transaction would have a random number in it, and would change each time). This request is to also ignore the `GeneratedConstructorAccessor` class (i.e. `jdk.internal.reflect.GeneratedConstructorAccessorXX`) from stack traces.

### Why should this be worked on? What problems or use cases does it solve or improve?

This helps engineers stay organized in situations where the third-party packages they are using are generating exceptions using reflection. The package we use is the [Java SOAP API client for Salesforce](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_quickstart_intro.htm), which ends up filling our Sentry homepage with issues and producing noisy alerts.

### Any other context or screenshots or API request payload/responses that you pertain to the feature.

Here is what our dashboards and Slack alerts look like.

![image](https://user-images.githubusercontent.com/1918630/82559016-df9a5d00-9b3c-11ea-9712-59e0ce6e23b0.png)
![image](https://user-images.githubusercontent.com/1918630/82559103-03f63980-9b3d-11ea-9b7c-fa2c21e31745.png)

**Comment by BYK** [comment]
@bruno-garcia - what do you think as our resident Java expert? 🙂

**Comment by bruno-garcia** [comment]
The PR adding that is here: https://github.com/getsentry/sentry/pull/13305/files

@mitsuhiko is this still the approach we take in this case? Could one replicate that PR and add these new types?

**Comment by mitsuhiko** [comment]
@bruno-garcia on this case clear cut: change the existing file. The grouping code is obviously crap in this case. If it were more debatable we might require a new revision with explicit upgrade.

**Comment by krconv** [comment]
Also wanted to mention that I believe my org has some custom utilities built on top of the Java client to help with grouping; if you think that might be part of the problem here, I'm glad to take a look. It seems that the problem is that generated class name, but I'm not that familiar with what is done client-side.

**Comment by danrods** [comment]
Having the same issue here. Any update or workaround for this?

**Comment by bruno-garcia** [comment]
@adinauer perhaps this was addressed too?

**Comment by adinauer** [comment]
@bruno-garcia sadly no.

**Comment by armenzg** [comment]
The grouping system has improved a lot since this issue was filed.
Last week, we enabled AI grouping for all Java projects.

@krconv If there are any custom stack trace rules in place I suggest removing them and letting us know of any issues.

I'm closing for now.
