### ISSUE TITLE
Auto resolve / last seen works incorrectly

### ISSUE THREAD

**Issue by terion-name** [getsentry/sentry#18980]
## Important Details

How are you running Sentry?

Docker in Kubernetes. v9.1

## Description

Auto resolve works incorrectly. I've set auto resovle for 30 days. Here is a screenshot where it is clearly seen, that issue was seen recently, but it was marked as resolved automatically

<img width="1519" alt="Скриншот 2020-05-22 13 42 05" src="https://user-images.githubusercontent.com/1060205/82659913-1a31f180-9c32-11ea-9880-52755b329dd0.png">

**Comment by BYK** [comment]
Hi @terion-name - v9.1 is quite old. Are you able to try this in a more recent version and see if it is still happening?
