### ISSUE TITLE
Sentry Slack bot is offline

### ISSUE THREAD

**Issue by BadMask121** [getsentry/sentry#18993]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version x.y.z

Saas (sentry.io)

Other, version x.y.z, [briefly describe your environment]

## Description

[What happened]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. and so on.

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant

### What you expected to happen

[What you think should be happening]

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by untitaker** [comment]
Since this issue is entirely empty and the title is not clear at all I'll close this. Feel free to follow up with the information asked of you by the issue template and I'll reopen.
