### ISSUE TITLE
Syntax error: strftime('%s') instead of strftime('%S')

### ISSUE THREAD

**Issue by projekt01** [getsentry/sentry#1902]
The RedisTSDB based on the BaseTSDB uses %s instead of %S in strftime. This makes the sentry server fail to upgrade if configured with TSDB.

see:
https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior

There are other places in sentry where strftime('%s') get used.

sentry Version 7.7.0

**Comment by dcramer** [comment]
%S is not the the same thing. %s is the unix time stamp and is absolutely valid

**Comment by dcramer** [comment]
If you're on windows (which I recall having this behavior) you should know we only support Unix systems.

**Comment by projekt01** [comment]
Yes, I'm on windows for development and nix for production. That's the only part which makes sentry not working for adhoc testing. I guess I can disable TSDB for testing.
