### ISSUE TITLE
Wrong  python package classifiers in setup.py

### ISSUE THREAD

**Issue by projekt01** [getsentry/sentry#1903]
Sentry is not OS Independent as defined in the setup.py python package classifier:
'Operating System :: OS Independent',
It's not supported/working on windows.

Can someone adjust the classifiers? It's sometimes hard to find such information but more bad to find the wrong information. Thanks

**Comment by mattrobenolt** [comment]
@projekt01 Do you mind submitting a PR? Mostly because I'm not sure exactly what it should be. :)

**Comment by projekt01** [comment]
@mattrobenolt I don't know the target OS.

I guess it should be:
Operating System :: POSIX

The available classifiers can get found at:
https://pypi.python.org/pypi?%3Aaction=list_classifiers

Currently the classifier defined in the sentry/setup.py file is.:
Operating System :: OS Independent

The available classifiers are:

Operating System :: Android
Operating System :: BeOS
Operating System :: iOS
Operating System :: MacOS
Operating System :: MacOS :: MacOS 9
Operating System :: MacOS :: MacOS X
Operating System :: Microsoft
Operating System :: Microsoft :: MS-DOS
Operating System :: Microsoft :: Windows
Operating System :: Microsoft :: Windows :: Windows 3.1 or Earlier
Operating System :: Microsoft :: Windows :: Windows 7
Operating System :: Microsoft :: Windows :: Windows 95/98/2000
Operating System :: Microsoft :: Windows :: Windows CE
Operating System :: Microsoft :: Windows :: Windows NT/2000
Operating System :: Microsoft :: Windows :: Windows Server 2003
Operating System :: Microsoft :: Windows :: Windows Server 2008
Operating System :: Microsoft :: Windows :: Windows Vista
Operating System :: Microsoft :: Windows :: Windows XP
Operating System :: OS/2
Operating System :: OS Independent
Operating System :: Other OS
Operating System :: PalmOS
Operating System :: PDA Systems
Operating System :: POSIX
Operating System :: POSIX :: AIX
Operating System :: POSIX :: BSD
Operating System :: POSIX :: BSD :: BSD/OS
Operating System :: POSIX :: BSD :: FreeBSD
Operating System :: POSIX :: BSD :: NetBSD
Operating System :: POSIX :: BSD :: OpenBSD
Operating System :: POSIX :: GNU Hurd
Operating System :: POSIX :: HP-UX
Operating System :: POSIX :: IRIX
Operating System :: POSIX :: Linux
Operating System :: POSIX :: Other
Operating System :: POSIX :: SCO
Operating System :: POSIX :: SunOS/Solaris
Operating System :: Unix

**Comment by mattrobenolt** [comment]
Thanks @projekt01, I just went with `POSIX :: Linux` for now since that's what we officially support. Not sure if we support all of `POSIX` since we never test against others. In theory, they should be fine, but we don't know. :)
