### ISSUE TITLE
empty statsPeriod chokes UI

### ISSUE THREAD

**Issue by whit537** [getsentry/sentry#1905]
I'm trying to find a URL to replace [this one](https://beta.getsentry.com/gratipay/gratipay-com/?sort=freq&df=&tt=&tf=&dt=&date_type=last_seen&cursor=0:110:0) that we [used to use](https://github.com/gratipay/inside.gratipay.com/issues/326#issuecomment-136349645) to get a count of unresolved errors/events. The first thing I tried is [fiddling the `statsPeriod` knob](https://beta.getsentry.com/gratipay/gratipay-com/?sort=freq&statsPeriod=), since that's what seems to limit the events by time. Doing so gives me an infinite spinner in the UI and an `Uncaught TypeError: Cannot read property '' of undefined` in the console, pointing to [groupChart.jsx](https://github.com/getsentry/sentry/blob/7c6182f9d8d435af1c490df3d1c9cd72ef6f7390/src/sentry/static/sentry/app/components/stream/groupChart.jsx#L20). The docstring and code for [`project_group_index.get`](
https://github.com/getsentry/sentry/blob/0e7771608d602f7a954a141d04914327b903fedc/src/sentry/api/endpoints/project_group_index.py#L88-L132) seem to indicate that '' should be considered a valid value.

Whether this is the best way to find the count of unresolved events is another question.

**Comment by dcramer** [comment]
You haven't actually (realistically) been able to get a count of unresolved events, at least not the total number. Everything else should effectively be the same.

Can you clarify what the data you're looking for is?

**Comment by whit537** [comment]
@dcramer Ideally I'd like the total number of unresolved events, as well as the total number of resolved events. Sentry is one of about a dozen queues we monitor weekly with this type of data ([e.g.](https://github.com/gratipay/inside.gratipay.com/issues/332#issuecomment-138281949)), and it's the only one we've had a hard time determining these counts for.

> You haven't actually (realistically) been able to get a count of unresolved events, at least not the total number.

Right. We were hacking it with cursor paging over an "all time" query. A more straightforward solution would be welcome. :-)
