### ISSUE TITLE
Organization Internal Auth Token can't list projects

### ISSUE THREAD

**Issue by MrGreenTea** [getsentry/sentry#19061]
## Important Details

How are you running Sentry?
Saas (sentry.io) and [onpremise](https://github.com/getsentry/onpremise)

## Description

When using an organization auth token generated by creating an Internal Integrations that token can't be used to get all projects with `GET "https://sentry.io/api/0/projects/`.
I've tested it with all permissions set to Admin and that does not change anything.
With a personal token it works though.

## Steps to Reproduce

1. Create internal integration
2. `curl "https://sentry.io/api/0/projects/" -H Authorization:"Bearer <internal token>"`
3. get an empty list `[]`

Good items to include here include:

### What you expected to happen

Get the same list as I would get with `curl "https://sentry.io/api/0/projects/" -H Authorization:"<personal token>"`

**Comment by MrGreenTea** [comment]
I've stumbled upon this on our on premise set up but go the same behaviour on sentry.io

**Comment by scefali** [comment]
@MrGreenTea You need to use the organization project endpoint: https://docs.sentry.io/api/organizations/get-organization-projects/
