### ISSUE TITLE
Can not create user

### ISSUE THREAD

**Issue by urasin** [getsentry/sentry#1906]
I am running sentry server.

```
sentry --config=~/.sentry/sentry.conf.py createsuperuser
sentry --config=~/.sentry/sentry.conf.py start &
sentry --config=~/.sentry/sentry.conf.py celery worker -B &
```
login and create user from web gui.

I have this error and can not create user.

```
  File "/home/vagrant/.pyenv/versions/2.7.9/lib/python2.7/site-packages/django/db/models/fields/related.py", line 326, in __get__
    "%s has no %s." % (self.field.model.__name__, self.field.name))
DoesNotExist: Project has no organization.
```

I can not make team and project.

Please tell me how to start sentry.

**Comment by dcramer** [comment]
Generally you should be using 'createuser' not 'createsuperuser'. By default we create a single organization which that user would then get access to.

Can you try it with createuser and see if that resolves things? Otherwise you need to fix the DB (or use /admin/) to give yourself access.

**Comment by urasin** [comment]
Thank you for it.

I am trying it.
