### ISSUE TITLE
Code preview with Gitlab/github

### ISSUE THREAD

**Issue by SrMouraSilva** [getsentry/sentry#19112]
## Summary

I wish there was a code preview just like with Javascript, however it would support other programming languages. For that, I suggest using code versioning tools, such as GitLab and GitHub

## Motivation

This tool would add to the quick identification of the error, adding more information about the status of the code in the error that occurred. I didn't find your roadmap, so I couldn't relate to the company's goals.

### Ideias

If:

- An error occurs;
- and the error contains the related release information;
- and the release has a set of linked commits;
- and the sentry administrator has enabled Gitlab, GitHub or similar;

Then sentry will preview the associated code. Possibly it will get the raw code (https://raw.githubusercontent.com/getsentry/sentry/master/.eslintrc.js) and show some lines that around the source code.

One thing I couldn't think of was how to associate the stacktrace with the code file. I imagine that interpreted languages inform which file the error occurred (such as python, ruby). However, java, for example, does not have this information.

### Examples

Javascript [example](https://docs.sentry.io/platforms/javascript/#automatically-capture-errors):
![image](https://user-images.githubusercontent.com/5341804/83443902-e8364180-a420-11ea-85c6-52304e06ebf4.png)

Discourse [example](https://discourse.zynthian.org/t/question-about-security-in-webconf/1717?u=srmourasilva) (they use [onebox](https://github.com/discourse/onebox)):
![image](https://user-images.githubusercontent.com/5341804/83444026-22074800-a421-11ea-95d4-f05e581619a0.png)

**Comment by SrMouraSilva** [comment]
Congratulations on the work, I wish the company much success!

**Comment by BYK** [comment]
@MeredithAnya this sounds very much like what you started working on so assigning to you. Feel free to change things if I'm mistaken.

**Comment by MeredithAnya** [comment]
@SrMouraSilva Just to clarify, are you talking about the source code context being displayed in Sentry itself? Or are you talking about a way to link from the stack trace to where in the source code that file/line number lives? For the latter, we do have a feature enabled for Early Adopters that lets you do this for both our GitHub and GitLab integration.

**Comment by SrMouraSilva** [comment]
> @SrMouraSilva Just to clarify, are you talking about the source code context being displayed in Sentry itself? 

Yes, I would like the issue screen (the screen that show the stacktrace) to show the code corresponding to this exception, similarly when it occurs with Javascript.

> Or are you talking about a way to link from the stack trace to where in the source code that file/line number lives? For the latter, we do have a feature enabled for Early Adopters that lets you do this for both our GitHub and GitLab integration.

Okay, that works too! But I still think it would be interesting to already show the context in the sentry itself.
