### ISSUE TITLE
Sentry suggesting bug report

### ISSUE THREAD

**Issue by jonalxh** [getsentry/sentry#19111]
## Important Details

How are you running Sentry?

I'm running Sentry under vue with your plugin.

## Description

[What happened]

I'm actually using Sentry in my Vue project and it is showing me the following error suggesting me to do a bug report.

`
/*! svg.draggable.js - v2.2.2 - 2019-01-08
https://github.com/svgdotjs/svg.draggable.js
Copyright (c) 2019 Wout Fierens; Licensed MIT 
*/

{snip} please open a bug report.")}function ze(e){var t;try{throw new Error("Sentry syntheticException")}catch(e){t=e}return Le("captureException", {snip}
`

## Steps to Reproduce

Just running my project it shows me the message on sentry dashboard, not sure if it is properly from Sentry or My project.

### What you expected to happen

No message being shown constantly.

### Possible Solution

Updating the library, because I think it is a dependency.

**Comment by EvanPurkhiser** [comment]
svg draggable isn't a library we use, sounds like this might be a bug in a different library.
