### ISSUE TITLE
Breadcrumbs messages are overridden by custom event message intermittently

### ISSUE THREAD

**Issue by narenkmanoharan** [getsentry/sentry#19128]
_Platform:_
- [x]  Android -> If yes, which Device API - 29 - compileSdkVersion - 29 - targetSdkVersion - 29
- [ ]  Java -> If yes, which Java (and sourceCompatibility/targetCompatibility) version?
- [ ]  Kotlin -> If yes, which Kotlin (and jvmTarget) version?
- [ ]  NDK -> If yes, which NDK/CMake version?
- [ ]  React-Native -> If yes, which version?

_IDE:_
- [x]  Android Studio -> If yes, which version? Android Studio 3.5.3 (Build #AI-191.8026.42.35.6010548)
- [ ]  IntelliJ -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Build system:_
- [x]  Gradle -> If yes, which version? 6.4.1
- [ ]  Buck -> If yes, which version?
- [ ]  Bazel -> If yes, which version?
- [ ]  Other -> If yes, which one?

_Android Gradle Plugin:_
- [x]  Yes -> If yes, which version? 3.5.3
- [ ]  No

_Sentry Android Gradle Plugin:_
- [ ]  Yes -> If yes, which version?
- [x]  No

_Proguard/R8:_
- [ ]  Enabled
- [x]  Disabled

_sentry-android installed with:_
- [ ] JCenter
- [ ] Bintray
- [x] Maven Central
- [ ] Manually

The version of sentry-android:
**2.1.2**

---
I have the following issue:

We append custom messages to our error events to get some additional context on crashes and errors. However, the message in our breadcrumbs are overridden by our custom message for the event. For example, 

This is our custom message for the crash:

![image](https://user-images.githubusercontent.com/9508432/82478834-5aed0780-9a86-11ea-9664-3a9cdd7de050.png)

The same message seems to be repeated in all our custom breadcrumbs in some crashes.

![image](https://user-images.githubusercontent.com/9508432/82478900-72c48b80-9a86-11ea-89bb-61e02f1da00a.png)

But in others, it actually shows the breadcrumbs that are intended. There doesn't not seem to be any pattern to this. At least from our point of view.

![image](https://user-images.githubusercontent.com/9508432/82480166-40b42900-9a88-11ea-902a-f78d8764d2f7.png)

Checked to make sure that we only attach the info in the event message and we don't mutate the breadcrumbs anywhere. Pretty confident about that. Also, we attach the additional info in the message property of events in the `beforeSend` callback.

![image](https://user-images.githubusercontent.com/9508432/82480502-c041f800-9a88-11ea-921d-90beb520a1ef.png)

Not sure why this might be flaky. Could you please look into this issue? Also let me know if you need any info. Thanks.

**Comment by untitaker** [comment]
Seems to work now

**Comment by narenkmanoharan** [comment]
Thanks for fixing this! :)
