### ISSUE TITLE
Current status of alternative search backends

### ISSUE THREAD

**Issue by imankulov** [getsentry/sentry#1913]
Hey there,

First of all, big thanks to Sentry team for getting incredibly close to the 8.0 milestone!

I have  a question regarding Sentry search backends. From what I can see, the only viable option for third-party users is the `DjangoSearchBackend`, which is sort of suboptimal (`message__icontains=query`, etc).

The second option, `ElasticSearchBackend` still raises `NotImplementedError` in a couple of critical cases. My question is, do you plan to keep working on ElasticSearch backend? Do you have any ETA? I would love to help, but I'm not a big ElasticSearch expert, and besides even if I start I don't want my work to interfere with yours. 

Thanks!

**Comment by dcramer** [comment]
Its not fully implemented, and honestly probably never will be. We're rebuilding the infrastructure, and when thats done we'll effectively have real search, but it will be a new abstraction.
