### ISSUE TITLE
Password Recovery email without recovery link

### ISSUE THREAD

**Issue by 4n70w4** [getsentry/sentry#19159]
## Important Details

How are you running Sentry?
Docker version 18.09.3, build 774a1f4
Image sentry:9.1-onbuild

## Description

Get email without link to restore

![image](https://user-images.githubusercontent.com/38257723/83627937-64a35e80-a5a0-11ea-9501-2673c93bdbe6.png)

## Steps to Reproduce

1
![image](https://user-images.githubusercontent.com/38257723/83628431-1d699d80-a5a1-11ea-862b-74178c5949c3.png)

2
![image](https://user-images.githubusercontent.com/38257723/83628157-bcda6080-a5a0-11ea-823c-0a8e6ed58707.png)

3

![image](https://user-images.githubusercontent.com/38257723/83628300-edba9580-a5a0-11ea-94b6-a8ec6c2ca91f.png)

**Comment by 4n70w4** [comment]
Alert email also without links:
![image](https://user-images.githubusercontent.com/38257723/83629869-8baf5f80-a5a3-11ea-8d51-53c335661d0a.png)

**Comment by BYK** [comment]
Quite sure this is due to your `system.url-prefix` setting missing. Can you set that and try again?

**Comment by 4n70w4** [comment]
@BYK I do not see such an option `system.url-prefix` in the `config.yml` or `sentry.conf.py` files.

But in notifications via `WebHooks` or `sentry-telegram` plugin correct links are generated.

![image](https://user-images.githubusercontent.com/38257723/83771663-2fc00600-a68b-11ea-90a1-b2341bb08bc1.png)

![image](https://user-images.githubusercontent.com/38257723/83771768-4e260180-a68b-11ea-8a47-67aa6ef74d81.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
