### ISSUE TITLE
Source Maps deleted

### ISSUE THREAD

**Issue by christianto88** [getsentry/sentry#19204]
I have a react apps. After build process and upload sourcemaps to sentry and finalizing a release, i can see the sourcemaps under 'Artifacts' tab. But when i delete my sourcemaps file (*.js.map) in the server and then there is an error issue triggered, and i check 'Artifacts' tab, my sourcemap files is deleted. Is this the expected behavior?

For security reasons, i am not going to let my sourcemaps publicly available. Is there any way to save sourcemaps in Sentry?

**Comment by BYK** [comment]
>Is there any way to save sourcemaps in Sentry?

https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/
