### ISSUE TITLE
electron+sentry+sourceMap+electron-builder+asar

### ISSUE THREAD

**Issue by Jom-my** [getsentry/sentry#19269]
file:///Users/{user}/{path}/{name.app}/Contents/Resources/app.asar/renderer.js"

![image](https://user-images.githubusercontent.com/53500080/84218137-6325e900-ab00-11ea-92d9-fa76e9da9f03.png)

**Comment by Jom-my** [comment]
use electron-bulider after packing

**Comment by Jom-my** [comment]
After packing with electronic Bullier

**Comment by BYK** [comment]
Please follow the issue template as this is not an issue report that we can understand and work on.
