### ISSUE TITLE
Members registered after being invited receive default level of permissions, not one they were invited with

### ISSUE THREAD

**Issue by Onekone** [getsentry/sentry#19270]
## Important Details

Running On-Premise w/ Docker, version 10.1.0.dev0

## Description

After deploying sentry/onpremise and inviting members of organization to take part of setting their projects on it, I had one person complain that they do not have rights to manage teams and projects. 

After checking members list, I noticed that their permission level had downgraded back to member (default permission level) from admin (level that invitation was issued with). After asking another pending sentry member to join as invited admin, been able to reproduce the issue

## Steps to Reproduce

1. Issue an invite through members screen with permission level that isn't set as default for new accounts
2. Have invited user register on Sentry instance
3. Check their permission levels

### What you expected to happen

New member gets permissions according to their invitation, not default level

**Comment by BYK** [comment]
I think this should be fixed by #19874 so closing. Will reopen if this is still an issue.

/cc @EvanPurkhiser
