### ISSUE TITLE
Non-Error exception captured with keys: details, error

### ISSUE THREAD

**Issue by vivekkupadhyay** [getsentry/sentry#19272]
## Sentry Config

```
Raven.config('...@sentry.io...', {
            environment: '...',
            ignoreUrls: ...
        }).install();
```

## Sentry Details 

- name: raven-js
- version: 3.27.2

#### Platform

- Chrome, Firefox, Edge (web+mobile)

#### Error (https://cdn.jsdelivr.net/npm/raven-js@3/dist/raven.min.js)
`Non-Error exception captured with keys: details, error` 

> There was 1 error encountered while processing this event 
> **trimHeadFrames**: Discarded unknown attribute

```
Error: Non-Error exception captured with keys: details, error
  at captureException(raven.js:567:12)
  at wrapped(raven.js:447:14)
``` 
```
        //       means Raven caught an error invoking your application code. This is
        //       expected behavior and NOT indicative of a bug with Raven.js.
        return func.apply(this, args);
      } catch (e) {
        self._ignoreNextOnError();
        self.captureException(e, options);
        throw e;
      }
    }
    // copy over properties of the old function
```

```
} else if (isPlainObject(ex)) {
      // If it is plain Object, serialize it manually and extract options
      // This will allow us to group events based on top-level keys
      // which is much better than creating new group when any key/value change
      options = this._getCaptureExceptionOptionsFromPlainObject(options, ex);
      ex = new Error(options.message);
    } else {
      // If none of previous checks were valid, then it means that
      // it's not a DOMError/DOMException
      // it's not a plain Object
      // it's not a valid ErrorEvent (one with an error property)
```

**Comment by BYK** [comment]
This sounds like when someone has an error-like class but it doesn't have a stacktrace and other relevant error information.

Closing as this sounds like a user error and raven-js is deprecated a while ago. If you are still having similar issues with a newer version of the SDK and are sure your app code is not at fault here, please file an issue over at [getsentry/sentry-javascript](https://github.com/getsentry/sentry-javascript)
