### ISSUE TITLE
When "Require Two-Factor Authentication" is enabled, adding new users results in duplicate records, workarounds required to complete new user registration

### ISSUE THREAD

**Issue by davidjmemmett** [getsentry/sentry#19307]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 10.1.0.dev0

## Description

Using either self-registration or by inviting new users results in the user ending up in either an endless redirect loop with the message "Oops something went wrong" on screen, or on another page with the message "This user is already in the organisation". After a user accepts the email invitation, a duplicate account is created, and as an administrator I then have to remove one of the duplicate records (specifically the record lower down the list, leaving the invite at the top of the list) in order to allow the user to complete the registration process.

## Steps to Reproduce

1. Navigate to Settings > Members
2. Click "Invite Members"
3. Enter an email address, leave "Role" as "Member", select a team for the user, click "Send invite" and click Close
4. Refresh the members page and observe that the record appears as an "Invited Member"
5. In a separate session, open the email titled "Join [organisation] in using Sentry" and click the "Join your team" link. Observe that the page displays the message "Accept organization invite" "To continue, you must either login to an existing Sentry account, or create a new account." and gives two options: "Create a new account" and "Login using an existing account".
6. As the user hasn't created an account yet, click "Create a new account". This takes the user to the authentication form, asking the user to "Login".
7. As the user cannot authenticate (they don't yet have a password), click "Register". Observe that the email address field (labelled "Email" - also a separate issue, as an email is a document, not an email address) is populated with the email address specified in the invitation.
8. Enter a name and a password, then click "Register".
9. The user is redirected back to the "Accept organization invite" page with the message "Your account ([email address]) is already a member of this organization. Switch accounts?". The only option presented to the user is a link for "Switch accounts?". Following this link takes the user back to the authentication form. Attempting to authenticate takes the user back to the "Accept organization invite" page with the same option.
10. As an administrator, note that there are now two members displaying in the members table with the same email address, an "Invited Member" and a "Member". The steps diverge here, and I will describe each of them below.

**Deleting the Invited Member**

Following on from step 10:

11. Delete the "Invited Member"
12. If the user reloads the "Accept organization invite" page, they are given the message "This organization invite link is no longer valid".
13. If the user then navigates to the root of the Sentry deployment, they enter into an endless redirect loop between the authentication form and the message "Oops! Something went wrong."
14. The user has to delete the cookie in order to exit the loop, in which case they are back at the authentication form with the message "Your session has expired."

**Deleting the Member**

Following on from step 10:

11. Delete the "Member", leaving the "Invited Member".
12. If the user reloads the "Accept organization invite" page, they are given the message "To continue, [organisation] requires all members to configture two-factor authentication."
13. The user registration process is complete

The sentry configuration is out-of-the-box, except for requiring 2FA.

**Comment by davidjmemmett** [comment]
I've just tested this with "Require Two-Factor Authentication" disabled and the process completes as expected, no duplicate user accounts are created.

**Comment by johnnymijnhout** [comment]
Exact same issue here, running Sentry in Kubernetes with the charts provided by you.

**Comment by BYK** [comment]
>with the charts provided by you.

We do not provide any Kubernetes charts.

I think this should be resolved by #19874 as it sounds very similar to #19820, hence closing. Please comment back if this is still an issue with a more recent version of Sentry.
