### ISSUE TITLE
Pushover plugin doesn't seem to be working

### ISSUE THREAD

**Issue by gbhrdt** [getsentry/sentry#1930]
My user and API key is 100% correct, but Sentry doesn't send any notification.

**Comment by dcramer** [comment]
@gbhrdt is this on getsentry.com? Its possible it was related to our event processing issues in the last hour.

**Comment by carelvwyk** [comment]
Also having this issue on getsentry.com, what information can I provide to help test?

**Comment by gbhrdt** [comment]
@carelvwyk +1
I totally forgot this issue. It's still not working for me on getsentry.com, too.
