### ISSUE TITLE
Device is tagging incorrect values (Other)

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1932]

**Comment by dcramer** [comment]
https://beta.getsentry.com/sentry/javascript/group/79366933/

**Comment by dcramer** [comment]
@mattrobenolt I recall you looking into this, did we figure anything out?

**Comment by mattrobenolt** [comment]
Uhhh, not that I recall. I don't remember the context here either, and the bug you linked to.. doesn't seem related.

**Comment by dcramer** [comment]
Not entirely sure what Device shoudl be at this point. Closing this out until we look into it more.
