### ISSUE TITLE
404 errors - every time

### ISSUE THREAD

**Issue by Daemach** [getsentry/sentry#19331]
Running in the cloud.

With the following DSN, I get a 404 on every error.  I've tried generating a new key and get the same results.

I get the same 404 when launching this URL directly in a browser.

https://4048184f1a244ffd9a5b094a39513ef9@o282532.ingest.sentry.io/5266295

**Comment by BYK** [comment]
Please [contact our support](https://sentry.io/contact/support/) for this.
