### ISSUE TITLE
Slack Integration: Sentry (new) could not be installed. Invalid permissions requested.

### ISSUE THREAD

**Issue by thallada** [getsentry/sentry#19353]
Tried adding the Slack integration to workspace per: https://docs.sentry.io/workflow/integrations/global-integrations/#configure-slack

But, it just shows this page:

![Screen Shot 2020-06-12 at 5 11 15 PM](https://user-images.githubusercontent.com/1505923/84546779-0ed16380-acd0-11ea-8f15-23c5ee08da78.png)

**Comment by saniales** [comment]
+1

**Comment by saniales** [comment]
now it works for me

**Comment by jonesphillip** [comment]
@thallada is this still a problem for you?

**Comment by thallada** [comment]
This is fixed for me.
