### ISSUE TITLE
Add "Close Account" Feature

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1938]
We need an automated way for people to remove their accounts.

Here's what I'm thinking:

- Close Account navigation in Account Settings
- Show a list of organizations that the user is an owner on, with a checkbox next to each. Ticking the box allows the user to remove the organization. Organizations which have no other owners are default ticked and read-only.
- Happens async just like everything else

**Comment by mattrobenolt** [comment]
> Show a list of organizations that the user is an owner on, with a checkbox next to each. Ticking the box allows the user to remove the organization. Organizations which have no other owners are default ticked and read-only.

We should probably provide an option to transfer ownership here with a big warning that all data will be deleted. I'd rather be very explicit here.

**Comment by dcramer** [comment]
@mattrobenolt if you're the only owner on an organization it seems unlikely you'd be transferring ownership. For the others, theres no need since there are already other owners and theres no single master.

As part of this we need to remove Organization.owner from schema. It's mostly unused but not entirely.

**Comment by dcramer** [comment]
Organization.owner is no longer a thing.

**Comment by dcramer** [comment]
https://www.dropbox.com/s/h09rkpguk0pkj83/Screenshot%202015-09-14%2014.07.43.png?dl=0
