### ISSUE TITLE
Add edit/delete to comments

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1939]
- [x] API endpoint for edit
- [x] API endpoint for delete
- [ ] UI behavior for edit
- [ ] UI behavior for delete

**Comment by dcramer** [comment]
@mattrobenolt or @mitsuhiko do you wanna do the API stuff here? Theres a notes details endpoint already so should be fairly easy.

**Comment by mattrobenolt** [comment]
dibs

**Comment by mattrobenolt** [comment]
I have a branch now with the UI changes, but they require some @ckj love since it looks awful.

https://github.com/getsentry/sentry/compare/notes...notes-ui

**Comment by mattrobenolt** [comment]
test
