### ISSUE TITLE
Slack Integration: 

### ISSUE THREAD

**Issue by medrawi** [getsentry/sentry#19439]
Hello, 

We have the self hosted version of sentry, and I was trying to connect it with Slack, but we are getting the error below: 
![image](https://user-images.githubusercontent.com/77969/85008403-3ce5f600-b15d-11ea-96cc-be74f0d67109.png)

What should we do?

**Comment by scefali** [comment]
@medrawi See: https://github.com/getsentry/sentry/issues/19439#issue-641085934

**Comment by kristian2x** [comment]
+1

**Comment by saifelse** [comment]
@medrawi , @kristian2x : You should folllow https://develop.sentry.dev/integrations/slack/ . You'll need to create a Slack App yourself and then update your config.yml to include your Slack App's Client ID keyed under`slack.client-id`
