### ISSUE TITLE
Ability to upload source maps from sentry UI

### ISSUE THREAD

**Issue by gaurav5430** [getsentry/sentry#19443]
## Summary
Ability to upload source maps directly through the Sentry UI, instead of relying on the cli or webpack plugin.

## Motivation

We have a self hosted sentry setup.
Currently we upload source map using sentry webpack plugin during deployment. Sometimes, the source map upload fails due to connectivity issues to our self hosted sentry. In such cases, we have to use the sentry cli locally or the plugin locally to upload source maps to Sentry. It would be much more convenient to be able to upload source maps from the Sentry UI, by going to releases and uploading a folder from local computer.
This feature is purely a UI enhancement, since the api is already available. 

## Additional Context
N/A

**Comment by BYK** [comment]
Thanks for the suggestion @gaurav5430. Closing as we don't plan to work on this any time soon. This is a nice to have but the cost of implementing it would outweigh any potential benefits.
