### ISSUE TITLE
Ops breakdown double-counts child spans

### ISSUE THREAD

**Issue by glentakahashi** [getsentry/sentry#19476]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

Unless I'm misunderstanding how spans work, it looks like the ops breaking is double-counting child spans. In this case, the GetHexesForHexList takes 2.4 seconds, and its child spans take up 2.3 of those seconds, but the Ops breakdown shows that the time spent is about 50:50.

## Steps to Reproduce

<img width="1795" alt="Screenshot 2020-06-19 00 01 00" src="https://user-images.githubusercontent.com/1022767/85105975-43598980-b1c0-11ea-9efd-519e7876e425.png">

### What you expected to happen

I expect that authorization takes up the majority of the time, and the delta (0.1s) is whats counted for GetHexesForHexList

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by BYK** [comment]
Please [contact our support](https://sentry.io/contact/support/) for this.
