### ISSUE TITLE
Slack integration: Cannot create alert rule

### ISSUE THREAD

**Issue by moreinhardt** [getsentry/sentry#19482]
## How are you running Sentry?

On-Premise w/ Docker, latest

## Description

After following the guide at https://forum.sentry.io/t/how-to-configure-slack-in-your-on-prem-sentry/3463 I cannot create an alert rule as I get the error message

> The slack resource "sentry" does not exist or has not been granted access in the xxx Slack workspace.

However, I did invite the user to the `#sentry` channel. I also saw some issues regarding the change of a public channel to private, but the problem appears on a channel that was always private as well as on public (!) channels.

I really don't know what else I can do, as most issue reports are related to the, as I understand, now-legacy version of the integration (e.g. https://github.com/getsentry/sentry/issues/18279).

Would be great if someone could help me.

**Comment by tolegen-t** [comment]
Same problem, I have installed Sentry on-prem in my Kubernetes Cluster, latest helm chart Sentry 3.0.0 from [here](https://github.com/sentry-kubernetes/charts/tree/develop/sentry)

**Comment by tolegen-t** [comment]
This was fixed 2 days ago in [this commit](https://github.com/getsentry/sentry/commit/cc9f7d12f4dd7fc6dc3723876d46052655153143)
I can confirm that setting **"slack.legacy-app"** to **false** resolves this issue.

**Comment by moreinhardt** [comment]
Thanks for the tip. It does resolve the issue. Maybe this should be documented? Why is the default `true`?

**Comment by tolegen-t** [comment]
> Thanks for the tip. It does resolve the issue. Maybe this should be documented? Why is the default `true`?

Maybe for backward compatibility? Yes I think they will document it in nearest future)

**Comment by phyzical** [comment]
i ran in this earlier today,

https://github.com/getsentry/onpremise/pull/563

and

https://github.com/getsentry/develop/pull/73

hopefully address those issues :)

**Comment by bahaagalal** [comment]
I am running in the same issue. I am using V 9.1.2 On-Premise & even after adding `slack.legacy-app: false` in the `config.yml` it still doesn't work.

**Comment by BYK** [comment]
@bahaagalal - if you check the [fixed commit](https://github.com/getsentry/sentry/commit/cc9f7d12f4dd7fc6dc3723876d46052655153143) above, you'd see that the fix is only available after version `20.7.0`.

Closing as this is resolved now.
