### ISSUE TITLE
"New Note" emails should link to "activity" page

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#1951]
Right now, they blindly link to the group overview, but would be nice if we kicked it over to the `/activity/` pane, and ideally, deeplink to the exact comment through a url fragment.

**Comment by mattrobenolt** [comment]
This needs to happen after we release 8.0 to 100% since old version isn't able to deep link.

**Comment by dcramer** [comment]
We can already commit this in the v8 branch, it just wont do anything yet

**Comment by mattrobenolt** [comment]
Yeah, just noting that it's not important to get done yet.
