### ISSUE TITLE
Failed in creating a pull request

### ISSUE THREAD

**Issue by Venus713** [getsentry/sentry#19560]
I tried to create a pull request, but it failed due to lake of authorization for Vercel.
So I need to be added to the related Vercel team and authorize the deployment.
Please review my pull request in https://github.com/getsentry/sentry/pull/19550 and give me some suggestion for that.

**Comment by markstory** [comment]
Vercel is disabled for external contributors because it is a security risk. I'll close this issue as there is nothing to be done with Vercel.
