### ISSUE TITLE
Azure Devops (VSTS) Integration error 

### ISSUE THREAD

**Issue by ivlukyanov** [getsentry/sentry#19589]
When pressing "Add installation" we are facing with error 400 Bad request (see screenshots)
![image](https://user-images.githubusercontent.com/6625276/85945543-e340b100-b93e-11ea-8a31-668b58383378.png)
![image](https://user-images.githubusercontent.com/6625276/85945592-387cc280-b93f-11ea-93e3-bb2b8c0e40d1.png)

**Comment by georghendrik** [comment]
If you're using your own Sentry onpremise installation, you need to configure a few things before you can connect Sentry to Azure DevOps. [These instructions](https://github.com/getsentry/sentry/issues/13094#issuecomment-665525348) from issue #13094 worked for me.

**Comment by Perfect-Web** [comment]
it doesnt work, keeps going in loops

**Comment by BYK** [comment]
@Perfect-Web please use the issue template and share your logs and configuration to get help around this.

Closing this issue as it is not actionable in this state.
