### ISSUE TITLE
Support Two-Factor Authentication with Duo

### ISSUE THREAD

**Issue by tlvenn** [getsentry/sentry#1960]
Given that Sentry operates the web admin on the same port as the capturing of logs, by nature the admin interface is exposed publicly.

It would be great to support 2 factor authentification to make that public interface more secure.

**Comment by dcramer** [comment]
Agreed that its a worthwhile feature. Ive never implemented it myself so am not sure of the costs, impact to running it on-premise, etc.

**Comment by Tlvenn** [comment]
Pricing for Duo is pretty friendly, it's free up to 10 users.
> https://www.duosecurity.com/pricing

And they have a python lib to easily and quickly secure a web login
> https://github.com/duosecurity/duo_python

**Comment by Tlvenn** [comment]
Documentation: https://www.duosecurity.com/docs/duoweb

**Comment by gregwjacobs** [comment]
I've used HAProxy rules to limit traffic from 'outside' to only exercise certain API paths, functions verses internal trusted user LAN segments using the entire Sentry stack. HAProxy let us enforce all this easily. 

```
backend limited_reporting_to_sentry
    mode http
    balance roundrobin
    server your-servername-here 1.2.3.4:80 check
    option http-server-close
    option forwardfor
    option httpchk GET / HTTP/1.1\r\nHost:\ sentry.yourdomainnamehere.com
    acl valid_raven_api path_reg ^/api/\d+/store/$
    http-request deny unless valid_raven_api
    http-request deny unless METH_POST
    http-request deny unless REQ_CONTENT
    http-request deny unless HTTP_1.1
```

You can further restrict payloads as you feel, but with the above we only accept /api/<number>/store/  transactions from a wide inbound path. You have to compose your own routes that will send traffic to this example restrictive backend, verses a more accepting internal one etc.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
