### ISSUE TITLE
Cannot delete project

### ISSUE THREAD

**Issue by davidjmemmett** [getsentry/sentry#19601]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version Sentry 10.1.0.dev0

## Description

Cannot delete project, from a user perspective nothing happens other than the "Confirm Password" button gets disabled. In Chrome's network tab, Sentry returns a 401 for the DELETE request. The user in question is a superuser, and as such I managed to delete the project from the Django administration panel instead.

## Steps to Reproduce

1. Navigate to settings page for a project
2. Select "Remove Project"
3. On the confirmation modal, select "Remove project"
4. On the "Confirm Password to Continue" modal, enter your password and select "Confirm Password".

### What you expected to happen

Project is deleted

**Comment by BYK** [comment]
Could this be the same issue with #2480?

**Comment by BYK** [comment]
Can you provide some logs around this? Also, are you able to try with a more recent version of Sentry?

**Comment by codemers** [comment]
Hi @BYK,

I got the same issue. I try to delete a sentry project through the web interface and then, it ask me to confirm my password.

After entering my password the "confirm" button is disabled and then nothing happen. 

In the network tab I got this:

![2020-11-11 at 3 51 PM](https://user-images.githubusercontent.com/1634975/98863074-d4fab980-2435-11eb-90b4-0776a77f8373.png)

My account seems to be verified, what can I do? 

Thanks!

**Comment by BYK** [comment]
Could this be related to #10380 and resolved with #11499?

**Comment by codemers** [comment]
@BYK I loggout from Sentry then connect back using Github SSO and now I can delete project!

**Comment by BYK** [comment]
@codemers then I'm closing this in favor of the others I referred to above. I think they might be related. Thanks for the fast response!
