### ISSUE TITLE
Handle routing errors

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1961]
Right now if you transition to a page which somehow throws an error during render it completely bricks the app (and you must reload the window).

**Comment by dcramer** [comment]
https://github.com/rackt/react-router/issues/538

**Comment by dcramer** [comment]
https://github.com/gaearon/react-transform-catch-errors/blob/master/src/index.js

**Comment by dcramer** [comment]
https://www.reddit.com/r/reactjs/comments/3g3xj8/question_best_practice_for_handling_error_with/

**Comment by dcramer** [comment]
#2466

**Comment by benvinegar** [comment]
We've since added a 404 component that still renders the sidebar:

![image](https://user-images.githubusercontent.com/2153/46265505-e691d900-c4db-11e8-88d0-4fa00d2fe8e0.png)
