### ISSUE TITLE
Invalid origin: http://localhost:8001

### ISSUE THREAD

**Issue by caffeinatedHuman** [getsentry/sentry#19632]
## Important Details

How are you running Sentry?

[ ] On-Premise w/ Docker, version x.y.z

[ ] Saas (sentry.io)

[x] Other: Web API via Javascript

## Description

Following the [Sentry API docs](https://docs.sentry.io/api/), I'm trying to fetch stats for a particular team as described [here](https://docs.sentry.io/api/teams/get-team-stats/)

On hitting the endpoint, I'm getting `400 BAD REQUEST`, with the response as: `Invalid origin: http://localhost:8001`
## Steps to Reproduce

Attaching a sample code to execute on the client browser:

```
$.ajax({
        url: sentryApiEndpoint+'teams/sample-org/sample-team/stats/',
        method: 'GET',
        crossDomain: true,
        headers: {
            'Authorization': 'Bearer <my-key>'
        },
        contentType: 'application/json'
    }).done(function(response){
        console.log('Request was successful');
        console.log(response);
    })
```

### What you expected to happen

A response was expected as shown in the [docs](https://docs.sentry.io/api/teams/get-team-stats/):
```
[
  [
    1541455200.0, 
    3302
  ], 
  [
    1541458800.0, 
    3832
  ], 
  [
    1541462400.0, 
    3669
  ], 
  [
    1541466000.0, 
    3533
  ], 
]
```

**Comment by hnzycfc** [comment]
Please let us know whether it is a bug or not .
I am using 10.0.0 and I have set SENTRY_ALLOW_ORIGIN

**Comment by BYK** [comment]
@hnzycfc are you able to test this with a more recent version of Sentry?
