### ISSUE TITLE
sentry 7.7.0 raven setup for celery worker logger

### ISSUE THREAD

**Issue by dexter-xiong** [getsentry/sentry#1964]
7.7.0 sentry will send celery worker log to Sentry(internal) project. So if I start celery worker with log level INFO(I upgraded from 6.4.4 and the worker log level was INFO), sentry will be unusable because event process will produce more events and these event need to be processed. I should see that the broker queue became bigger and bigger and it will crash when there is no more memory. 
Similar situation should happen when there were something error on event processing, so I think it should be a critical problem.

**Comment by dcramer** [comment]
Resolved in raven-python 5.7.0
