### ISSUE TITLE
Bitbucket Integration: 

### ISSUE THREAD

**Issue by rastogiachyut** [getsentry/sentry#19660]
I get an 'HTTP ERROR 405' when I click on grant access on the next screen, I have the required permissions to do the integration, i.e. admin access in bitbucket repo and manager access in sentry:
![image](https://user-images.githubusercontent.com/7073017/86215756-9a853400-bb9a-11ea-80ed-9ca4096a7454.png)

**Comment by BYK** [comment]
Can you share your logs for this?
