### ISSUE TITLE
Not able to add a Slack channel with specific name to Alerts

### ISSUE THREAD

**Issue by hayzem** [getsentry/sentry#19664]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

Added sentry to two private channels `#api` and `#api-log`. 
On Alerts section of the project added new alert for `#api` which worked fine.
Then I wanted to switch channel to `#api-log` but it complained that:
`The slack resource "api-log" does not exist or has not been granted access in the {workspace name} Slack workspace.`
But this message is not correct since @sentry added to both channels and working well on the other channel(#api).
 
While I was writing this on I wanted to give another shot with different names and they worked fine. 
`#the-team` worked (so it is not just a dash issue)
`#api-p-log-stage` also worked.

## Steps to Reproduce

1. Add @sentry app to channels one has dash(-) or underscore(_) or `log` in the name, the other just letters.
2. Add an Alert on Sentry
3. The channel named `#api-log` will not be added.

Good items to include here include:
`The slack resource "api-log" does not exist or has not been granted access in the {workspace name} Slack workspace.`

### What you expected to happen

Being able to add channel to Alerts.

### Possible Solution

Unfortunately, no suggestion.
I'm wondering if this is related to any specific settings for that channel. I will research and update here.

**Comment by pratheekhegde** [comment]
This has been bugging me from last two days, seems like the steps described in `https://forum.sentry.io/t/how-to-configure-slack-in-your-on-prem-sentry/3463` doesn't work anymore.

**Comment by harshulj** [comment]
I am facing the same issue. Any workaround for this ?

**Comment by phyzical** [comment]
https://github.com/getsentry/onpremise/pull/563

for the fix :)

**Comment by pratheekhegde** [comment]
Issue fixed after adding `slack.legacy-app: false` to ` config.yml` and restarting the server by `sudo docker-compose restart web cron`.

Thank you @phyzical

**Comment by jonesphillip** [comment]
@hayzem were you able to get this working? Can you try removing `@sentry` from `#api-log` and then re-adding it. I have a feeling you may have multiple sentry bots and the wrong one was invited to the channel.

**Comment by hayzem** [comment]
@jonesphillip just tried what you suggested. sentry alerts giving me the same error. here is what I did:

there is only one `@sentry` bot in the workspace. I removed it via `View N apps in api-log` in channels settings. Re-added `@sentry` again via `Add apps` from channel settings. then I tried to add a new alert on sentry's project settings. it is still giving me the same error.

btw, I have not try the standalone solution suggestions, since our account is `Saas`. just let me know if I can apply those suggestions somehow.

**Comment by ericjeker** [comment]
Not sure it's related but I am having a lot of difficulties with that as well. There are now 3 different Sentry apps in Slack:
![image](https://user-images.githubusercontent.com/979397/87653295-eb468080-c787-11ea-8be4-6e6a35d7c908.png)

On the most recent one (I guess, with the pink icon), they mention a @sentry2 but I have no idea where that is as I only have a @sentry:
![image](https://user-images.githubusercontent.com/979397/87653197-c94cfe00-c787-11ea-8f95-83e1056453e5.png)

I've added the bot in the private channel I want to notify:
![image](https://user-images.githubusercontent.com/979397/87653446-192bc500-c788-11ea-914c-07b701695b27.png)

But I still get an error when I am adding a notification:
![image](https://user-images.githubusercontent.com/979397/87653574-4bd5bd80-c788-11ea-80b4-a1daa5461544.png)

We use Slack SaaS. I've not idea how to fix that.

**Comment by hbish** [comment]
We are having the exact same issue with the SaaS Sentry, could not set up notifications to Slack. Our legacy integration worked but we can't rollback anymore as it's no longer available in the Slack marketplace.

**Comment by MeredithAnya** [comment]
@hayzem @ericjeker @hbish  Is it possible that the channels you are trying to add were previously public channels? 

You can check this by opening Slack in your browser, going to the channel and checking the url, if the last part (e.g. `CSG031XMH/details/` has a 'C' but is a private channel that would mean it was initially public.

We recently had [a change](https://github.com/getsentry/sentry/pull/19446/files) from using the `channels.list` endpoint (which is [deprecated](https://api.slack.com/methods/channels.list)) to the `conversations.list` endpoint. And I just tested out locally that in the response back from Slack - if my channel was public -> private, it's not included in my list of channels.

**Comment by hayzem** [comment]
@MeredithAnya I can't recall it being public but yes the channel url's last part starts with `C`, except the `/details`, that part is missing.

**Comment by ericjeker** [comment]
@MeredithAnya, seems that that particular channel's ID starts with a C. So then, how can we solve that? It seems that it's a problem on Slack's side.

**Comment by MeredithAnya** [comment]
> @MeredithAnya, seems that that particular channel's ID starts with a C. So then, how can we solve that? It seems that it's a problem on Slack's side.

@ericjeker Indeed it does. We are reaching out to them about this, so we'll post an update when we hear back with more information.

**Comment by MeredithAnya** [comment]
> > @MeredithAnya, seems that that particular channel's ID starts with a C. So then, how can we solve that? It seems that it's a problem on Slack's side.
> 
> @ericjeker Indeed it does. We are reaching out to them about this, so we'll post an update when we hear back with more information.

I actually misspoke here, when testing locally I wasn't testing with the setting `slack.legacy: False` (added [in this PR](https://github.com/getsentry/sentry/pull/19446)). 

We have to continue supporting workspace Slack apps while people are still migrating over to the new bot app and workspace apps are not compatible with the `conversations.list` api. This is why for Sentry SaaS, the setting must default to `True`. 

All this is to say, it wasn't on Slack since we weren't actually using the `conversations.list` endpoint for the new bot apps. Instead we're still using the deprecated `channels.list` endpoint. We'll update y'all when the fix is live for non-workspace apps.

**Comment by MeredithAnya** [comment]
Late to update this issue but should've been fixed in https://github.com/getsentry/sentry/pull/20047, so going to close this out.

**Comment by hbish** [comment]
Thanks for the update @MeredithAnya this is finally working!
