### ISSUE TITLE
Create Project Endpoint returns "Internal Error"

### ISSUE THREAD

**Issue by imanodaysoffdotcom** [getsentry/sentry#19663]
When trying to create a new project via the Sentry API i get this errr 
{"detail":"Internal Error","errorId":"random_error_id"} not sure whats going on... All other reqyest seem to work but not this one.

{"detail":"Internal Error","errorId":"1e453a3ca1004aafa2e00440e0f1cb9d"}

curl -X POST \
-H "Authorization: Bearer blahblahblabhblah" \
-H "Content-Type:application/json" \
-d '{"name":"testprojname"}' \
https://sentry.io/api/0/teams/{organization_slug}/{team_slug}/projects/

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
