### ISSUE TITLE
JIRA integration - Mark issue resolved in next release on when task "Done"

### ISSUE THREAD

**Issue by Aidan-Chey** [getsentry/sentry#19673]
## Summary

Ability to specify to have a JIRA linked issue marked as "resolved in next release" when the JIRA task is "Done".

## Motivation

This feature should be added as it is inconvenient / an annoyance to have JIRA issues marked as simply "Resolved". Personally, I'm finding I am having to go back to the issue, un-resolve it and use the drop down to mark as resolved in the next release. The reason I'm having to do this is because I don't want to get regression notifications on these issues that have already been addressed but haven't been released yet.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2044) by [Unito](https://www.unito.io)

**Comment by olivernybroe** [comment]
We are having a kinda similar problem. 

So we have a status called `awaiting release` and `released`, so basically when we put in `awaiting release` we want to mark it as `resolved in next version`.

Right now our settings are set to `When Resolved => Released`, this means if we mark a sentry issue with `resolved in next version` it moves our jira issue to `Resolved`.

It seems like I am missing a status to depend this on, so I actually can make a working setup.

**Comment by andrevalentin** [comment]
Just piling on here, if we were to get a new status field in the Jira integration for specifying when a issue is in "resolved in next version", then that would be perfect, could obviously just be an optional field as I guess a lot of projects maybe don't utilize a status for this.

**Comment by fmod-mathew** [comment]
We use Jira for all Sentry tasks that are sent to the dev team for investigation. Having to bounce back and forth to ensure issues are resolved for next version not just resolved for all versions is extra work. It would be great to have a default setting for always resolve in next version.

**Comment by dall2812** [comment]
I support this request. It would be great to set a Sentry issue linked with a Jira ticket to "resolved in the next version" on marking the Jira ticket as done.

**Comment by MaximeLaurenty** [comment]
I wholeheartedly agree with the above, we have a setup similar to what [olivernybroe described](https://github.com/getsentry/sentry/issues/19673#issuecomment-709316411).
Having a third status mapping in addition to "resolved" and "unresolved" would do the job.

An alternative would be to allow teams to choose what kind of "resolved" they want to use as default.
In our case, in both the mapper and the default issue view we are primarily interested by "resolved in next release", hence we would use it as default.
Having the choice in defaults (resolved & ignored) would spare us a few recurring misclicks when managing issues!

**Comment by Memfisrain** [comment]
Hi, do you have any updates on this?

We have a similar situation on frontend: we mark JIRA ticket as done and after that issue is marked as resolved in Sentry. However some users still use old version of the code and could encounter the issue again. That leads Sentry to change issue's status to regression.

For us, it would be helpful to specify the release version with a fix in JIRA ticket. Alternatively "resolved in next release" option would be helpful as well.

**Comment by hubertdeng123** [comment]
Don't think this has had any movement. Will route this to issues for now

**Comment by Dhrumil-Sentry** [comment]
This is a valid ask. We don't have plans to do this in Q4 But will revisit this in Q1 and update this ticket as we have more details

**Comment by Dhrumil-Sentry** [comment]
This has been shipped. Please see this changelog for more details: https://sentry.io/changelog/resolve-sentry-issues-in-current-or-next-release-when-you-close-the-linked-jira-ticket-as-done/
