### ISSUE TITLE
Jira integration - Mark issue resolved in next release on "Done"

### ISSUE THREAD

**Issue by Aidan-Chey** [getsentry/sentry#19672]
## Summary

One paragraph description of the feature.

## Motivation

Why should this be worked on? What problems or use cases does it solve or
improve?

## Additional Context

Any other context or screenshots or API request payload/responses that you
pertain to the feature.

**Comment by jonesphillip** [comment]
Closing, duplicate of https://github.com/getsentry/sentry/issues/19673
