### ISSUE TITLE
Creating a new artifact with an incorrect release value doesn't return an error

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#1969]
If you submit a bad release value as part of your HTTP API POST, you get the following response:

``` json
{"detail": ""}
```

The reality is that the upload failed, but there's no feedback to explain what happened.

**Comment by dcramer** [comment]
I'm not entirely sure why this is returning empty detail off hand.

It seems like this should be hit:

```
        if 'file' not in request.FILES:
            return Response({'detail': 'Missing uploaded file'}, status=400)
```

**Comment by benvinegar** [comment]
I said "if you submit a bad release value". This error above is if the file is missing.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
