### ISSUE TITLE
Settings menu + mobile UI issue

### ISSUE THREAD

**Issue by phyzical** [getsentry/sentry#19695]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, master 20.XX

## Description

I was at the coffee shop and a dev needed access so i whipped out my phone and was served with this

![image](https://user-images.githubusercontent.com/5182053/86478046-3752f780-bd7c-11ea-8fb5-2f6a3b404403.png)

took me about 2 minutes to remember you can flip a phone portrait 😄   

not a huge deal but a QOL thing

## Steps to Reproduce

1. resize to smallest screen size
2. try to press save

### Possible Solution

maybe we make the sidebar menu shrink similar to the top menu in mobile responsiveness

or at the very least allow the user to scroll horizontally?

**Comment by markstory** [comment]
#15946 is related to this issue.

**Comment by tlf30** [comment]
I wok on the go, and this would be really great to have fixed.

**Comment by markstory** [comment]
Going to close this as we've shipped an update to settings that moves the sidebar into a menu button and fixes many of the overflow issues that settings had in the past.
