### ISSUE TITLE
Accepting Invite doesnt save position

### ISSUE THREAD

**Issue by phyzical** [getsentry/sentry#19736]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 20.7.0.dev08d2f1cb

## Description
Invite a user as admin, upon accepting they hit register and are served with register page, but once accepted they revert back to a member user.

![image](https://user-images.githubusercontent.com/5182053/86698794-33f09200-c042-11ea-8917-8844d3e6bc74.png)

![Jul-07-2020 11-07-15](https://user-images.githubusercontent.com/5182053/86698656-14596980-c042-11ea-8e69-0f224118d235.gif)

![image](https://user-images.githubusercontent.com/5182053/86698551-fd1a7c00-c041-11ea-8d22-5ec2f9f700e0.png)

## Steps to Reproduce

1. invite user as admin
2. click invite link
3. enter details
4. view user in admin panel, they should be back to member level

### What you expected to happen

they should be the user level selected

**Comment by phyzical** [comment]
just noticed this in the settings could this be overriding the selected position? (ill give it a test if i get a chance)
![image](https://user-images.githubusercontent.com/5182053/87030502-47ebed80-c214-11ea-866b-82b9ecd6fa20.png)

**Comment by EvanPurkhiser** [comment]
I think I've fixed this in https://github.com/getsentry/sentry/pull/19874

**Comment by BYK** [comment]
Should be fixed in #19874 so closing. Feel free to reopen if not @phyzical
