### ISSUE TITLE
Render data about crash report on event details

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1974]
We currently only show this data on the prototype report list page. It's not available via the event details endpoint (b67ff0cbe3240b2940b32153f4565ec688550d65) so let's find a way to stuff it into the details page.

Ideally this would be attached to the 'user' interface, but that interface _may not_ be available by default if they didnt send it ahead of time. It's unclear to me what we should do about that, but it's already a special case so we can just do like `evt.user || evt.userReport` and go from there.

/cc @benvinegar @ckj

**Comment by dcramer** [comment]
This needs a lot of product thought -- probably can sync up next week about overall goals here, but I think just mocking up something for event details is a step in the right direction.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
