### ISSUE TITLE
Jira Integration: configuration screen giving error for self hosted Sentry

### ISSUE THREAD

**Issue by WLauret** [getsentry/sentry#19743]
I am self-hosting Sentry (version 10.0.0) and trying to set up Jira integration, following these instructions: https://forum.sentry.io/t/how-to-configure-jira-cloud-in-your-on-premise-sentry/6720

However, when I get to step 4 and click 'Configure' (taking me to https://<domain>.atlassian.net/plugins/servlet/ac/<sentry_url>/configure-sentry ) the page remains blanc, and after a few seconds I get below error

![image](https://user-images.githubusercontent.com/29373231/86773141-89826a00-c055-11ea-9ecb-4dc2fd138c85.png)

Not sure if this is a Jira or Sentry issue, but since I have successfully set up an integration in the past with above instructions, on an older version of Sentry, my guess is on Sentry side.

Any help would be much appreciated.

**Comment by scefali** [comment]
@WLauret Do you mind posting the URL you are using for the descriptor?

**Comment by WLauret** [comment]
Hi @scefali , The descriptor URL I use is the one from the documentation:
https://[my-sentry-domain]/extensions/jira/descriptor/

**Comment by scefali** [comment]
@WLauret Strange, that's the right URL. I'm not quite sure what the issue is; I've never seen that error before

**Comment by WLauret** [comment]
Issue was due to our sentry setting x-frame-options to block iframing, and apparently Jira loads certain pages through iframe to configure. Resolved it by going directly going to the page that jira was trying to load in iframe.
Thanks for the help @scefali
