### ISSUE TITLE
Add JS API for Crash Reports

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#1975]
Right now crash reports only provide a way to render on page error. That is, we look at some window config and say "ok heres the stuff, lets show the dialog". We need an API for creating, showing, and dismissing these.

We then need to instrument our React code with said API (and likely need to do it with raven.js to some degree, for uncaught errors?).

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
