### ISSUE TITLE
Javascript original location information seems to be gone/invisible in the 8.0 beta

### ISSUE THREAD

**Issue by dequis** [getsentry/sentry#1978]
Sometimes I get javascript error reports that seem to come from ad-injecting malware in the users' browsers. In 7.8 there was a link to the original source, but in 8.0 i have no way to tell that it's not a file in my webserver, other than, well, the oddly obfuscated javascript that i'm not hosting.

I see this in the html, in the same place as the old "share" icon.

`<a href="http://cdn.staticwebd*m.com/js/a.js?[snip]" class="icon-share" data-reactid=".0.2.2.1.0.0.1.0.0.2.4:$entry-0.1.0.$0.2.0.$6.0.$share"></a>`

But it has no contents and width 0. I guess icon-share broke?

Screenshots follow.

# 7.8

![](http://dump.dequis.org/NXjPO.png)

And:

![](http://dump.dequis.org/6_t2m.png)

(I actually didn't know about the `?` before I started writing this bug report)

------

# 8.0 beta

![](http://dump.dequis.org/hvWcZ.png)

The `?` popup seems to be gone, but it's probably redundant to the link.

**Comment by mattrobenolt** [comment]
oops, I think this was an oversight on our part. Will get this added back in. :frowning: 

/cc @ckj @benvinegar

**Comment by ckj** [comment]
We're working on getting this back in, @dequis. https://github.com/getsentry/sentry/commit/c1836972f4a40fe0baae65bab08e8a1aeef675d1 brings back the share icon (which is now using our open icon) and should be live shortly.

**Comment by dequis** [comment]
:heart:
