### ISSUE TITLE
Duplicated app name github while upgrading

### ISSUE THREAD

**Issue by darrist** [getsentry/sentry#19805]
## Important Details

On-Premise w/ Docker, version 20.6.0 (AWS EC2 Image)

## Description

An error describing duplicate of Django app "github". I am not sure if this belongs here or @getsentry/onpremise, pardon me.

## Steps to Reproduce

1. At my version, running `pip upgrade -u sentry`
2. Run `sentry upgrade`

Good items to include here include:

```
Traceback (most recent call last):
  File "/usr/sentry/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 166, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/usr/sentry/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/sentry/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/sentry/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/sentry/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/sentry/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/sentry/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/sentry/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 29, in inner
    configure()
  File "/usr/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 129, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/usr/sentry/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 158, in configure
    skip_service_validation=skip_service_validation,
  File "/usr/sentry/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 310, in initialize_app
    django.setup()
  File "/usr/sentry/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/sentry/local/lib/python2.7/site-packages/django/apps/registry.py", line 89, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: github
```

### What you expected to happen

It should upgrade without error.

### Possible Solution

- GitHub apps (assuming is Django apps) are being duplicated, I've tried to search for the code but have no luck.
- edit: Could it be legacy version of sentry-plugin still intact? I am aware that sentry have merged plugins into main repo.
- edit: Attached some grep log below of where I think I could find 'github' related to sentry.

**grep -rnw '../site-packages/sentry' -e 'github'**
https://termbin.com/ywrf

**grep -rnw '../site-packages/sentry-plugins' -e 'github'**
https://termbin.com/fxev

**Comment by scefali** [comment]
@darrist You probably have ` sentry-plugin ` as a dependency. Could you post the output of `pip freeze`?

**Comment by rancorlol** [comment]
> @darrist You probably have ` sentry-plugins` as a dependency. Could you post the output of `pip freeze`?

I have issue like this. Virtualenv, sentry 20.7.0
my output pip freeze
amqp==1.4.9
anyjson==0.3.3
appdirs==1.4.4
attrs==19.3.0
backports.functools-lru-cache==1.6.1
BeautifulSoup==3.2.2
beautifulsoup4==4.7.1
billiard==3.3.0.23
boto3==1.4.5
botocore==1.5.70
cached-property==1.5.1
cachetools==3.1.1
celery==3.1.18
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
click==6.7
configparser==4.0.2
confluent-kafka==0.11.5
contextlib2==0.6.0.post1
croniter==0.3.34
cryptography==2.9.2
cssselect==1.0.3
cssutils==1.0.2
datadog==0.30.0
decorator==4.4.2
defusedxml==0.5.0
distlib==0.3.1
Django==1.11.29
django-auth-ldap==1.2.17
django-crispy-forms==1.7.2
django-jsonfield==0.9.13
django-picklefield==0.3.2
django-sudo==3.1.0
django-templatetag-sugar==1.0
djangorestframework==3.6.4
docutils==0.16
email-reply-parser==0.2.0
enum34==1.1.10
Events==0.3
exam==0.10.6
filelock==3.0.12
funcsigs==1.0.2
functools32==3.2.3.post2
futures==3.3.0
google-api-core==1.14.3
google-auth==1.6.3
google-cloud-bigtable==0.32.2
google-cloud-core==0.29.1
google-cloud-pubsub==0.35.4
google-cloud-storage==1.13.3
google-resumable-media==0.4.1
googleapis-common-protos==1.6.0
grpc-google-iam-v1==0.11.4
grpcio==1.30.0
hiredis==0.1.6
honcho==1.0.1
httplib2==0.18.1
idna==2.7
importlib-metadata==1.7.0
importlib-resources==3.0.0
ipaddress==1.0.23
isodate==0.6.0
jmespath==0.10.0
jsonschema==2.6.0
kombu==3.0.35
loremipsum==1.0.5
lxml==4.3.5
maxminddb==1.4.1
milksnake==0.1.5
mistune==0.8.4
mmh3==2.3.1
mock==3.0.5
more-itertools==5.0.0
msgpack==0.6.2
natsort==6.2.1
oauth2==1.9.0.post1
oauthlib==3.1.0
olefile==0.46
parsimonious==0.8.0
pathlib2==2.3.5
pbr==5.4.5
percy==2.0.2
petname==2.6
phabricator==0.7.0
phonenumberslite==8.11.5
Pillow==6.2.2
pkgconfig==1.5.1
pluggy==0.6.0
progressbar2==3.32.1
protobuf==3.12.2
psycopg2-binary==2.7.7
py==1.9.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
PyJWT==1.5.3
pyOpenSSL==19.1.0
pyrsistent==0.16.0
pytest==3.5.1
pytest-django==2.9.1
pytest-html==1.9.0
python-dateutil==2.8.1
python-ldap==3.3.1
python-memcached==1.59
python-openid==2.2.5
python-u2flib-server==5.0.0
python-utils==2.4.0
python3-saml==1.4.1
pytz==2020.1
PyYAML==5.3.1
qrcode==6.1
querystring-parser==1.2.4
raven==6.10.0
rb==1.7
redis==2.10.5
redis-py-cluster==1.3.4
requests==2.20.1
requests-oauthlib==1.2.0
rfc3339-validator==0.1.2
rfc3986-validator==0.1.1
rsa==4.5
s3transfer==0.1.13
scandir==1.10.0
selenium==3.141.0
semaphore==0.4.65
sentry==20.6.0
sentry-ldap-auth==2.8.1
sentry-plugins==9.0.0
sentry-relay==0.5.11
sentry-sdk==0.16.1
setproctitle==1.1.10
simplejson==3.8.2
singledispatch==3.4.0.3
six==1.11.0
soupsieve==1.9.6
sqlparse==0.2.4
statsd==3.1
stevedore==1.32.0
strict-rfc3339==0.7
structlog==16.1.0
symbolic==7.4.0
toronado==0.0.11
typing==3.7.4.3
ua-parser==0.10.0
unidiff==0.6.0
urllib3==1.24.2
uWSGI==2.0.19.1
virtualenv==20.0.27
virtualenv-clone==0.5.4
virtualenvwrapper==4.8.4
xmlsec==1.3.8
zipp==1.2.0

**Comment by darrist** [comment]
@scefali I am aware that sentry-plugins got deprecated, is there a migration guide available anywhere? I am using AWS EC2 image deployment, it uses Python 2.7 by default (not sure if its related).
