### ISSUE TITLE
Cannot Enable Legacy Integration Alerting on "Frequency of events in entire project"

### ISSUE THREAD

**Issue by chavlin** [getsentry/sentry#19814]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

"Send a Notification to All Legacy Integrations" does not appear as an "Alert Action" when setting an alert configured to "Frequency of events or users affected increasing" and "Frequency of events in entire project".

The only option that appears is "Send to email"

All other configurations of the initial two radio buttons in the Alert setup do list "Send a Notification to All Legacy Integrations".

The only Legacy Integration configured for this project is OpsGenie (v20.7.0.dev0)

Is this a known issue, or is there any additional configuration that must be done behind the scenes to allow Legacy Integration routing?  I would like to configure alerting such that an alert triggers when a project hits its rate limit.

## Steps to Reproduce

1. Settings -> Projects -> <Specific Project>
2. Alerts -> New Alert Rule
3. Select "Frequency of events or users affected increasing" and "Frequency of events in entire project" radio buttons
4. Metric: count(); Time Window: 24 hours
5. "Add an Action" dropdown only shows "E-mail"

### What you expected to happen
The "Add an Action" dropdown ought to include "Send a Notification to All Legacy Integrations" and "Send a Notification Via an Integration" as it does when configuring other alerts.

**Comment by adhiraj** [comment]
"Frequency of events in entire project" (metric alert) is a new type of alert which currently only supports email and the global (org-level) slack integration. We plan to add support for more integrations in the near future (likely pagerduty, opsgenie, and webhooks to start with). opsgenie doesn't exist as a global integration, so we'll first write one, then make metric alerts support it.

**Comment by janithl** [comment]
+1 for OpsGenie integration for Metric Alerts!

**Comment by BYK** [comment]
Closing as we won't ever be supporting legacy integrations for metric alerts. We'll have new integrations which you can follow from our announcements on blogs and newsletters.
