### ISSUE TITLE
[GitHub API] Deprecation notice for Installation Access Token creation API

### ISSUE THREAD

**Issue by dionrhys** [getsentry/sentry#19853]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 9.1.2

## Description

We have Sentry 9.1.2 set up as a GitHub app on our org, using the built-in integration. This has been running well since we set it up last year.

This morning, we had an e-mail from GitHub notifying us of a deprecated endpoint being used by the app:

> **[GitHub API] Deprecation notice for Installation Access Token creation API**
> 
> Hi {org} Admin,
> 
> On July 14th, 2020 at 01:13 (PDT) the application "{org} Sentry" owned by your organization issued a request using the deprecated endpoint for creating access tokens. GitHub has deprecated this undocumented endpoint, its replacement which accepts the same arguments is available now.
> 
> This endpoint will be removed on October 1st, 2020.
> 
> Please visit https://developer.github.com/changes/2020-04-15-replacing-create-installation-access-token-endpoint for more information about suggested changes, brownouts, and removal dates.
> 
> Thanks,
> The GitHub Team

## Steps to Reproduce

1. Create a GitHub org app for Sentry following the instructions here: https://develop.sentry.dev/integrations/github/
2. Install the app on some repos
3. After some time passes, you should receive an e-mail from GitHub warning about the deprecated `/installations/{org}/access_tokens` endpoint

### What you expected to happen

Not receiving a deprecation notice from GitHub.

### Possible Solution

I looked over the Sentry source code to see if it _is_ using this now-deprecated endpoint, and it does seem to be used in many places. (e.g. `src/sentry/integrations/github/client.py`, `src/sentry/integrations/github_enterprise/client.py`, `src/sentry_plugins/github/client.py`)

I checked both on **releases/9.1.x** that we're using, and **master** - same deal in both. I would appreciate if a fix for this could be backported to 9.1.x (as otherwise the GH integration will stop working in Oct 2020), but understand if it cannot.

Based on [the link](https://developer.github.com/changes/2020-04-15-replacing-create-installation-access-token-endpoint/) given by GitHub, the Sentry GitHub integration should amend the endpoint it uses to create access tokens to be `/app/installations/{org}/access_tokens` instead (i.e. include `/app` in front of the current endpoint). _(I'm not sure if the same applies to GH Enterprise)_

The GH documentation also suggests the `Accept: application/vnd.github.machine-man-preview+json` header that's present in the current code is still required.

I wasn't sure exactly which of the files are still used and need to be changed, otherwise I would've opened a PR instead. The endpoints are mentioned a bit in the tests as well.

**Comment by EvanPurkhiser** [comment]
I believe we have fixed this here https://github.com/getsentry/sentry/commit/76ccffdafa48d008487da4d12aac12b078a2433d

@ceorourke can you verify we've fixed this?

**Comment by ceorourke** [comment]
Hello @dionrhys, yes we have addressed the deprecation notice via the PR @EvanPurkhiser linked. The OSS release `20.7.0`  should be going out today.
