### ISSUE TITLE
Tests failing out of the box

### ISSUE THREAD

**Issue by kevinlondon** [getsentry/sentry#1985]
I'm trying to run the tests and having a bit of a tough time with it.

```
sentry kevin$ py.test tests
Traceback (most recent call last):
  File "/Users/kevin/.virtualenvs/hacking/bin/py.test", line 9, in <module>
    load_entry_point('pytest==2.8.0', 'console_scripts', 'py.test')()
. . .
  File "/Users/kevin/.virtualenvs/hacking/lib/python2.7/site-packages/django/conf/__init__.py", line 47, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting pytest_impl, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

What should I set the settings_module setting to be? Is there something else I should be running?

PS - I found it a bit tough to find how to run the tests and checked the tox.ini file. Could we add instructions to the docs? `python setup.py test` yields the following:

```
kevin$ python setup.py test
running test
kevin$
```

**Comment by dcramer** [comment]
I think this is an issue with a new version of pytest (or pytest-django which we use).

Can you try:

```
pip install pytest==2.6.4
```

And see if that resolves it?

**Comment by kevinlondon** [comment]
It does look like that progresses me past the point. Then I'm on to an error message about Redis, which is covered in the installation section. Thanks for the fast reply!

**Comment by pelme** [comment]
Here is the pytest-django issue that deals with this problem:
https://github.com/pytest-dev/pytest-django/issues/272
