### ISSUE TITLE
not able to remove inbound filter after moved the feature to business plan

### ISSUE THREAD

**Issue by m-nathani** [getsentry/sentry#19886]
i am using free version and  set an inboud filter for Custom Release and Error Message filtering.for my project, 
but later they changed its availability  to Business plans and above.

however now i am not able to remove those filter as its disabled.

please help me remove those filter so that i can track my errors

here is the link to debug:

https://sentry.io/settings/umai/projects/umai-fe/filters/data-filters/

**Comment by BYK** [comment]
Please [contact our support](https://sentry.io/contact/support/) for this.
