### ISSUE TITLE
Slack Integration: after upgrade the integreation become configured for the wrong workspace

### ISSUE THREAD

**Issue by theambient** [getsentry/sentry#19888]
subj. followed upgrade procedure using the link from email.

**Comment by jonesphillip** [comment]
@theambient this looks like the wrong Slack workspace was selected when you upgraded. Can you uninstall the Slack integration and re-install with the correct workspace? 

You should see a selector in the top right:
![Screen Shot 2020-07-21 at 12 24 12 PM](https://user-images.githubusercontent.com/7978631/88097610-43490280-cb4d-11ea-888b-5e7f1c971dd7.png)

If that doesn't work or you have any other questions, you can write into: partners@sentry.io
