### ISSUE TITLE
request.body erronously getting truncated to 512 bytes instead of 16KB

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#1990]
Re: https://sentry.zendesk.com/agent/tickets/437

**Comment by radicalbiscuit** [comment]
Any idea on when this will be merged into a release?

**Comment by mattrobenolt** [comment]
This should have been in 8.0 a while back.

**Comment by radicalbiscuit** [comment]
It doesn't seem to match up with 8.1.2 or master. In fact, the blame for [this line](https://github.com/getsentry/sentry/blame/8.1.2/src/sentry/interfaces/http.py#L170) indicates that it hasn't been touched since before this issue was opened.

**Comment by mattrobenolt** [comment]
Wait, did I never merge this into master? It looks like 7e7b02d was only applied to the 7.x-legacy branch.

**Comment by mattrobenolt** [comment]
Lemme try and cherry-pick this into master.

**Comment by mattrobenolt** [comment]
Oh, I see why, because on master this behavior changed. It was never a problem on master, but only existed for 7.x. The original problem is that `body` was a `dict`, and wasn't being trimmed properly in that case, but now it's coerced into a string always and truncation takes place on the string.

**Comment by radicalbiscuit** [comment]
Thanks for checking into that. We'll check our configuration to make sure we aren't truncating sooner than we want.
