### ISSUE TITLE
Discord webhook integration

### ISSUE THREAD

**Issue by victornpb** [getsentry/sentry#19931]
_This issue is more like a PSA for future reference than anything else._

As the time of writting, there's no official support to discord webhooks, but discord supports a slack compatible format. Which could be used with the Slack integration, but it was deprecated in favor of the slack integration with oauth. The old integration (now called Slack Legacy) still work to this day, but it is somewhat hidden.

# How to add discord webhook to sentry

1. Visit this hidden page
  `https://sentry.io/settings/PROJECT_NAME/plugins/slack/`
1. Enable the plugin
  ![image](https://user-images.githubusercontent.com/3372598/86059373-ffc11400-ba38-11ea-8f50-1c2c758355ad.png)
1. Add to project
  ![Add to project](https://user-images.githubusercontent.com/3372598/86059619-71995d80-ba39-11ea-8d20-002c025a9a94.png)

1. Configure webhook
  ![Configuring webhook](https://user-images.githubusercontent.com/3372598/86060047-58dd7780-ba3a-11ea-829a-6e1ed46d85ac.png)
1. Click Test
  ![](https://user-images.githubusercontent.com/3372598/86060380-ff297d00-ba3a-11ea-8dfd-9fd62a80bf35.png)
  ![](https://user-images.githubusercontent.com/3372598/86060407-05b7f480-ba3b-11ea-90fe-cb6ba886d4b4.png)

1. Now enable an Alert rule to your project
  Navigate to https://sentry.io/settings/ORG/projects/PROJECT/alerts/
  ![](https://user-images.githubusercontent.com/5332757/83489186-9e149500-a4e0-11ea-9254-09af744f4604.png)

**Comment by Renato66** [comment]
step 6 was updated:

![image](https://user-images.githubusercontent.com/9284273/93518310-0443ed00-f903-11ea-9602-6d10bf6cfb0c.png)

blue: select your project
green: click on alert tab
orange: create new alert rule

![image](https://user-images.githubusercontent.com/9284273/93518662-82a08f00-f903-11ea-9e9d-456b2282e8c7.png)
red: choose a name for the rule; `ex: Discord (legacy)`
green: select an event that fits to you (you can select multiples)
blue: select `Send a notification (for all legacy integrations)`

**Comment by noisyblue** [comment]
At now, correct url for step 1 is:
https://sentry.io/settings/ORG_ID/projects/PROJECT_NAME/plugins/slack/

**Comment by BYK** [comment]
Thanks for sharing this @victornpb. Since we try to track open issues, I'll be closing this one. I think either our developer documentation at https://develop.sentry.dev/ or [community forum](https://forum.sentry.io) would be a better home for this information.

What do you think?

/cc @jonesphillip

**Comment by followbl** [comment]
@BYK I would've never found this if it was in the community forum. @victornpb thanks for sharing - works great.

**Comment by BYK** [comment]
@followbl I also suggested our developer docs at https://develop.sentry.dev/ 😉

**Comment by victornpb** [comment]
> Thanks for sharing this @victornpb. Since we try to track open issues, I'll be closing this one. I think either our developer documentation at https://develop.sentry.dev/ or [community forum](https://forum.sentry.io) would be a better home for this information.
> 
> 
> 
> What do you think?
> 
> 
> 
> /cc @jonesphillip 

TBH I would like to see a real discord integration, Discord APIs makes things VERY straightforward on their side. 

I see a large number of open source projects moving away from slack to discord as community servers makes it a great communication hub, and it make sense to have notifications there. There's no point in monitoring if no one sees it.

Unless there's is some kind of deal with the current integrations there. This shouldn't require much work on Sentry's side, right?!

**Comment by BYK** [comment]
>Unless there's is some kind of deal with the current integrations there. This shouldn't require much work on Sentry's side, right?!

My standard response to this is: pull requests accepted! Especially if you think it is straightforward to implement 🙂
