### ISSUE TITLE
Automatically disable erroring plugins

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#1997]
- [x] Add "version" to plugins, which is just a hash derived from configuration (GH-1999)
- [ ] If a plugin errors on a specific version over a period of time, disable
- [ ] Message project admin that the plugin was disabled
- [ ] Send email notification to admins?

**Comment by dcramer** [comment]
From my point of view we should do this:

- Set an error threshold -- if a plugin errors multiple times in X period, disable it for a period of time
- As plugins error, we continue to keep it disabled, and every so often we try again (after an expiration window)
- When a plugin is in an error state, we can show messages to admins to let them know its not working correctly

**Comment by mattrobenolt** [comment]
Yup, and I was going to use the version to track a plugin's rate limit, so if the config changes, we can treat them separately and know that a specific version is bad, not just the plugin as a whole.

**Comment by dcramer** [comment]
Oh so the version is of the "ive changed the plugins options". That wasn't clear in the PR

**Comment by mattrobenolt** [comment]
Yeah, it's specifically a version to indicate the state of all the config options. So if a user changes one option, the plugin now has a new version.

**Comment by mattrobenolt** [comment]
As a first pass, I think we're just going to detect consecutive failures on the same plugin version. So just something like:

```
on plugin call:
  check failures counter:
    if > 10:
        ignore entirely
  on success:
    delete failures counter
  on failure:
    increment failures counter
```

@dcramer, we'd want to record the errors so we can message it and they know how to fix it. How should we do this?

**Comment by mattrobenolt** [comment]
Nevermind, we need to do this time based since consecutive failures from an upstream provider would trigger this.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
