### ISSUE TITLE
GitHub Integration: 'Add Installation' button only takes you to the GitHub Marketplace

### ISSUE THREAD

**Issue by tomgie** [getsentry/sentry#19988]
I am currently using the on-premise version of Sentry and whenever I click on 'Add Installation' on the Github integration, it takes me to the GitHub Marketplace. I was not sure if that was intended or if the link was supposed to bring you to an OAuth link.

**Comment by joejordanbrown** [comment]
Same issue here with Sentry v20.7.24 6de988.

**Comment by scefali** [comment]
@tomgie It's supposed to bring open up a modal that shows your integration in the Github Marketplace so you can install it there.

**Comment by tomgie** [comment]
@scefali So, I have to create a GitHub app to work with Sentry?

**Comment by uhlhosting** [comment]
Yes this needs update on docs.

**Comment by scefali** [comment]
@tomgie @uhlhosting Are the docs [here](https://develop.sentry.dev/integrations/github/) not enough?

**Comment by bachden** [comment]
Assume you guys are using sentry onpremise (20+?), you must create github app then fill up fields in sentry/config.yaml then rebuild docker compose.
`docker-compose down ; docker-compose build ; docker-compose up -d`
![image](https://user-images.githubusercontent.com/1224571/97838186-450c8f80-1d12-11eb-8b98-71664826dbd4.png)
