### ISSUE TITLE
Affected users count is not filtered by the environment

### ISSUE THREAD

**Issue by KKAries** [getsentry/sentry#20006]
## Important Details

How are you running Sentry?

Saas (AWS AMI) version 9.1.2

## Description

In the Issue detail page, when filter by the environment drop list on right top, the events number changes but the users number doesn't.

## Steps to Reproduce

1. Go to an issue detail page.
2. Filter the environment by the filter at top right.
3. See the affected users number does not change when the environment changed.

### What you expected to happen

The affected users count is changed to users affected on specific environment.

**Comment by roggenkemper** [comment]
closing because this is fixed
