### ISSUE TITLE
jira integration: create form resets issue type but shows Epic fields

### ISSUE THREAD

**Issue by saifelse** [getsentry/sentry#20016]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description
As of today, when using the JIRA integration, the "Epic Name" field is now required, despite that not being the case in JIRA. Specifying a value here shows a cryptic error:
![image](https://user-images.githubusercontent.com/549473/88332345-39590800-cce3-11ea-93de-6ce5aae1e75a.png)

## Steps to Reproduce

1. Configure a JIRA issue type with epic.
2. Enable JIRA integration.
3. From the issue page, select "Link Jira Issue"
4. Select the create tab, then issue type from (1).
5. Notice that "Epic Name" is a required field.
6. Not filling it out errors. Typing something in errors.

### What you expected to happen
- "Epic Name" should not be showing up.
- I should be able to create JIRA tickets from Sentry.

### Possible Solution

I'm speculating that this was originally addressed in #9421 by special-casing "Epic Link", but maybe JIRA is now surfacing this as "Epic Name" as seen in this screenshot?

**Comment by saifelse** [comment]
Just kidding, it looks like the "Issue Type" now resets to "--" but renders the fields for "Epic" Issue Type... which make the "Epic Name" field show up as required... which isn't possible to fill out.

![image](https://user-images.githubusercontent.com/549473/88333697-863dde00-cce5-11ea-9152-31379210aa6c.png)

So it's largely a usability issue, as the workaround is to remember to select the correct Issue Type before creating the ticket.

I think I can summarize there being 3 surprising behaviors:

1. After using the "Link" feature (intstead of create), all of the default values get reset. So if we typically create tickets in Project XYZ with Issue Type "Bug", the second we use the link feature, the Project / Issue Type fields get reset... and it's annoying to have to reselect these values.. esp. since we almost **always** use XYZ + Bug.

2. Issue Type resets to `--` but is interpreted as Epic. It shouldn't have rendered any fields until the issue type was selected, it should be considered a required field. Hitting "create issue" never works, i.e. does not create an Epic, so there's definitely some weird state at play here.

**Comment by saifelse** [comment]
Here's showing that there is some default id being used that doesn't actually correspond to any of the issue type ids:
![image](https://user-images.githubusercontent.com/549473/88334610-e1bc9b80-cce6-11ea-8fca-8d7d90a76bf0.png)

**Comment by BYK** [comment]
@saifelse is this also resolved via #21580?

**Comment by saifelse** [comment]
@BYK : I think 

> I think I can summarize there being 2 issues:
>
> After using the "Link" feature (intstead of create), all of the default values get reset for "Create". So if we typically create tickets in Project XYZ with Issue Type "Bug", the second we use the link feature, the Project / Issue Type fields get reset... and it's annoying to have to reselect these values.. esp. since we almost always use XYZ + Bug.

This is resolved by #21580?

> Issue Type resets to -- but is interpreted as Epic. It shouldn't have rendered any fields until the issue type was selected, it should be considered a required field. Hitting "create issue" never works, i.e. does not create an Epic, so there's definitely some weird state at play here.

This I think is still an issue. I think there might be a weird bug where if the issue type that was previously the default gets deleted in Jira that the modal gets confused in someway. I can confirm this in the next day or two.

**Comment by BYK** [comment]
Alright @saifelse, keeping this open until you verify then. Thanks a _ton_ for all your contributions!

**Comment by saifelse** [comment]
Our typical project is BNCH (10021), which does not have a "Task" issue type (10002), yet that was the one that is selected in the above screenshots. This sounds a lot like #21751 ... though BNCH is not a next-gen project but a classic software project.

If I first select a project that has this issue type, select Task, and then switch to BNCH, I'm able to recreate the above screenshot... where I think some (/all?) of our custom fields across all issue types for the project are being surfaced. And if I directly visit: https://sentry.io/api/0/groups/1967144109/integrations/12212/?action=create&project=10021&issuetype=10002 I see all of those fields being surfaced... same if I put in a nonsense issuetype: https://sentry.io/api/0/groups/1967144109/integrations/12212/?action=create&project=10021&issuetype=9999999

IMO, if an issue type is selected that doesn't exist for the project either:
a. all fields should be hidden until a valid issue type is selected
b. the first issue type that is valid for the project should be selected.

@scefali : While the proposal of making issue type a required field might help, I think if a user runs into this scenario, it'll be pretty overwhelming to see all of these fields / errors and be confused.
