### ISSUE TITLE
WEBHOOKS Integration Callback URLs validation error

### ISSUE THREAD

**Issue by am-kra4un** [getsentry/sentry#20044]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

When I trying to save webhook configuration with callback URL ex. **https://fb0e7c33c1d6.ngrok.io/sentry** or **https://webhook.site/afd3cc94-d436-4293-8c19-4a91c0d6d0f4** validation error occurs - **Not a valid URL**.

## Steps to Reproduce

1. Go to project config -> Legacy Integrations
2. Choose WebHooks configuration
3. Insert `https://fb0e7c33c1d6.ngrok.io/sentry` to Callback URLs textarea
4. Click Save Changes button

Good items to include here include:

![Screen](https://user-images.githubusercontent.com/2011319/88529597-e34cd300-d008-11ea-980c-1f311ab47aca.png)

### What you expected to happen

No errors 

### Possible Solution

Fix validation for callback URL

**Comment by MoskitoHero** [comment]
I have the exact same issue with another URL:

`https://app.datadoghq.com/intake/webhook/sentry?api_key=MY_DATADOG_API_KEY`

**Comment by murdho** [comment]
I experienced the same issue with Datadog EU URL:
`https://app.datadoghq.eu/intake/webhook/sentry?api_key=MY_DATADOG_API_KEY`

`https://sentry.io/api/0/projects/ORGANIZATION/PROJECT/plugins/webhooks/` responds with 400 Bad Request.

**Comment by jonesphillip** [comment]
We're aware of this issue and working on a fix, sorry for the inconvenience!

**Comment by SophisticaSean** [comment]
Same issue. :(

**Comment by vaibhavawachat** [comment]
Same issue 😞

**Comment by manuzope** [comment]
Hey there, this should be solved now for Sentry SaaS. Please let me know if that's not the case.

**Comment by am-kra4un** [comment]
everything ok

**Comment by manuzope** [comment]
Great, thanks for confirming (and reporting the problem)! Closing the issue.
