### ISSUE TITLE
Vercel Integration: returns Internal Server Error

### ISSUE THREAD

**Issue by jlcarvalho** [getsentry/sentry#20116]
Whenever I try to connect Sentry to Vercel I get the following error:

![Screen Shot 2020-08-02 at 16 11 03](https://user-images.githubusercontent.com/1238663/89130376-de8d9080-d4da-11ea-9ebf-9ce508fe11ac.png)

**Comment by scefali** [comment]
@jlcarvalho That's definitely not the right screen! I presume you are using SaaS Sentry, yes (sentry.io)? If so, could you email me the name of your organization at scefali@sentry.io so I can debug the issue?

**Comment by scefali** [comment]
It should be fixed now
