### ISSUE TITLE
Highlighted row in autocomplete is not obvious

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2011]
![image](https://cloud.githubusercontent.com/assets/375744/10057671/54c2c872-61f6-11e5-8bde-5c74418a36dd.png)

To me, this difference is way too subtle.

I'm referring specifically to the row that's slightly darker grey, not the bright yellow text highlight.

This is problematic when using up/down arrows to switch through results.

Thoughts @ckj ?

**Comment by ckj** [comment]
Looks like it affects the project list on org home as well. I made the bgColor variable lighter without realizing we were using it for highlighting. Will fix.
