### ISSUE TITLE
Not receiving "install" webhook when installing a Public integration

### ISSUE THREAD

**Issue by mieky** [getsentry/sentry#20125]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

When installing an (yet unpublished) integration, I do not get an "install" webhook sent to my configured webhook URL. However, when I uninstall the same integration, the "uninstall" webhook arrives as expected.

## Steps to Reproduce

1. Create a "Public" integration that has a webhook URL defined (but don't publish it yet)
2. Click "Accept & Install" on the integration page

### What you expected to happen

I would have expected to receive a webhook to my configured webhook URL, as described in https://docs.sentry.io/workflow/integrations/integration-platform/webhooks/#uninstallation. However, I would only receive a webhook when I remove the app.

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by scefali** [comment]
@mieky this is now fixed with: https://github.com/getsentry/sentry/pull/21083
