### ISSUE TITLE
Auto-Assign is not working when Suggested Assignees is determined by commit

### ISSUE THREAD

**Issue by marbon87** [getsentry/sentry#20136]
## Important Details

On-Premise with Docker, version 20.7.2

## Description

Auto-Assign is activated for the project.
When a new event comes in, the Suggested Assignee is correctly determined based on a commit (from bitbucket server integration) and i can manually assign it to the user of the commit, but i expect sentry to do that automatically

## Steps to Reproduce

1. Set-commits for a release 
2. Trigger an event with the release, that has commits
3. View event and see that the assignee is not automatically assigned

### What you expected to happen

Suggested Assignee should be automatically assigned to the event.

**Comment by markstory** [comment]
Suggested owners via commit aren't part of the 'issue ownership' rule system that feeds into suggested assigees and automatic assignment right now. Adding that seems potentially doable, however commit based ownership is expensive to compute so we'd likely run into performance problems 🤔

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by marbon87** [comment]
I still think, that this would be helpful

**Comment by BYK** [comment]
Hi @marbon87 - reached out to our product team and turns out this is something we'd like to consider. We canont provide any timeline for now though.

Thanks for taking the time to report this and following up.

**Comment by 5ay3h** [comment]
@BYK so this issue shouldn't be closed, right?

And also `feature_requests += 100`, as my team, along with me, are requesting it 🙏 😉

**Comment by BYK** [comment]
@5ay3h oh, right sorry forgot to reopen in my last comment. Thanks for the heads up!

**Comment by adhiraj** [comment]
I think one of the reasons to not do this automatically is that suspect commits are not high confidence estimates yet. If we made this a setting, would you want it to be for the entire org, per team, per project, or some other granularity?

**Comment by marbon87** [comment]
It would be helpful if it could be configured on a project level.
On big repositories, monoliths apps with a couple of teams working on it, the last committer should be a good first choice for the assignee.

**Comment by snigdhas** [comment]
We've added support for this in https://github.com/getsentry/sentry/pull/40066
