### ISSUE TITLE
Can't Remove Deleted Project From Webhook

### ISSUE THREAD

**Issue by ozanonurtek** [getsentry/sentry#20132]
## Important Details

How are you running Sentry?
-> Saas (sentry.io)

## Description
Integration Bug after deleting a project

## What happened
When I first delete project from settings, I can not delete it from Webhook Integration. It deletes the project but doesn't delete the project from webhook installed table I guess.

## Steps to Reproduce

1. Create an webhook integration for project and use that integration in any alarm
2. Go to settings and delete the project
3. Go to settings > integrations > webhook > try to remove or uninstall deleted project.

UI Response:
![Screen Shot 2020-08-06 at 01 49 13](https://user-images.githubusercontent.com/14114739/89472056-3d2b6680-d788-11ea-93fc-a78eaece021d.png)
Network Response:
"The requested resource does not exist", 404

### What you expected to happen
Automatically remove the project from all integrations.

### Possible Solution
Just for fun, here is my possible solution in pseudo python/sqlalchemy way 😅 :  
```
def delete_project(project_id):
    ....
    Integrarations.query.filter(Integration.fk_project_id == project_id).delete()
    db.session.commit()  
```

**Comment by scefali** [comment]
@ozanonurtek This is definitely a bug. The actual solution here would be to just hide the project that's pending deletion from the UI. If I get some free cycles, I'll see if I can pick it up since it's a 1 line fix.
