### ISSUE TITLE
Gitlab integration does not work

### ISSUE THREAD

**Issue by bartek1234321** [getsentry/sentry#20154]
## Important Details

On-Promise w/ Docker, version 9.1.2

## Description

Can not install GitLab Integration, in step 2 after filling GitLab App credentials data click submit then "Authorize" button, I wait some time and i see this info:

Oops! Something went wrong
It looks like you've hit an issue in our server API. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

## Steps to Reproduce

1. in step 2 after filling GitLab App credentials data click submit
2. in the next page click "Authorize" button
3. on the next page I see: Oops! Something went wrong
It looks like you've hit an issue in our server API. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

### What you expected to happen

Plugin should be installed and access should be granted.

**Comment by markstory** [comment]
If you look into the internal sentry project or the logs do you see any errors? Troubleshooting this is going to be really hard for us, as you're using on premise. I'm not able to reproduce the problem you're having when using sentry.io and gitlab.com.

**Comment by bartek1234321** [comment]
![image](https://user-images.githubusercontent.com/7874149/90615563-9aa1c780-e20c-11ea-8d72-6f75f2f84625.png)
![image](https://user-images.githubusercontent.com/7874149/90615600-a68d8980-e20c-11ea-8860-9a2ec81985c3.png)
![image](https://user-images.githubusercontent.com/7874149/90615611-a8574d00-e20c-11ea-9123-2c8200f19774.png)

**Comment by tardyp** [comment]
I got this today, and it was due to https_proxy variable not configured.

**Comment by bartek1234321** [comment]
works great now, thank you very much!
