### ISSUE TITLE
How can I filter sensitive data from navigation?

### ISSUE THREAD

**Issue by yoyoys** [getsentry/sentry#20151]
I'd tried to use ADVANCED DATA SCRUBBING with regex `%22accessToken%22%3A%22.*?%22` to filter `%7B%22accessToken%22%3A%22access%20Token%20token%22%2C%22refreshToken%22%3A%22refresh%20token%20token%22%7D`, but I don't see any effect at my breadcrumbs.

Is there any wrong? thanks!

**Comment by untitaker** [comment]
Can you post the full rule you tried to configure?

**Comment by yoyoys** [comment]
@untitaker is this okay?

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/22124891/89893709-6ece8280-dc0b-11ea-9af5-13c25ff4cd03.png">

**Comment by untitaker** [comment]
I would try pasting a specific event ID into the form, that gives you better completion on Source. I thikn you might need `$breadcrumb.message` but it's hard to tell.

**Comment by yoyoys** [comment]
and this is what I want to mask
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/22124891/89893885-c0770d00-dc0b-11ea-81b5-21881c2a5d41.png">

**Comment by untitaker** [comment]
Okay, that's probably `$breadcrumb.data.from || $breadcrumb.data.to` or something like that then. Have you verified this with regex101.com?

**Comment by yoyoys** [comment]
So Data Scrubbing is not for this scenario right?

I've just verified this from chrome devtools console.

**Comment by untitaker** [comment]
You mean you verified your regex in javascript? Unfortunately our regex engine is not close to JS at all. I would try it with regex101.com and select the Golang option.

**Comment by yoyoys** [comment]
Okay thanks.
So I can use Data Scrubbing for this requirement?😄

**Comment by untitaker** [comment]
Yes generally this should work but I think doing it with `**` will not work. You will have to paste the event ID as shown in https://blog.sentry.io/2020/07/02/sentry-data-wash-now-offering-advanced-scrubbing/ to figure out the correct value for Source, or at least I think that's the safest way.

And I can't verify if your regex is correct but there's some potential for errors there as well.

**Comment by yoyoys** [comment]
Okay I will change my regex for golang.
By the way, this sensitive data will come with any event, so maybe I will not set the event id. Thanks😄

**Comment by untitaker** [comment]
@yoyoys the event ID is only used as a point of reference to enable better autocompletion while creating the rule, it is not saved as part of settings

**Comment by yoyoys** [comment]
https://regex101.com/r/D8dRUw/1

I've just test with this regex, it works, but not works on breadcrumbs. :(

**Comment by untitaker** [comment]
Can you screenshot your config and link to teh event? This is hard to debug from here
