### ISSUE TITLE
Wrong display of log tag and "age" of event

### ISSUE THREAD

**Issue by DanEEStar** [getsentry/sentry#2018]
I am using the hosted "beta.getsentry.com". This is probably version 8?

I use the following code to display some messages:

```
        client.captureMessage(
            u'Start of "link_and_unlick_customer_subscriptions_with_api_application"',
            tags={'api': 'subscription_application', 'level': 'warning'},
        )
```

So I expect to have a "warning" label next to my message. But in the list display it shows always the "error" tag.

![screenshot_317](https://cloud.githubusercontent.com/assets/1432939/10069796/ca7f2c3c-62ae-11e5-9823-f24927855902.png)

Although the log level seems to get added correctly as seen in the detail view:

![screenshot_318](https://cloud.githubusercontent.com/assets/1432939/10069856/2a05c86e-62af-11e5-8f7c-c71024a123ca.png)

The same problem is there with the "info" log level.

In the list view it also shows "17 hours old" although the event got only captured a few minutes ago...

**Comment by mattrobenolt** [comment]
Can you send a link over to support and I'll take a look?

**Comment by mattrobenolt** [comment]
Oh, I see what you're doing wrong, `level` isn't a tag. It's a top-level `kwarg`.

So something like:
```python
        client.captureMessage(
            u'Start of "link_and_unlick_customer_subscriptions_with_api_application"',
            tags={'api': 'subscription_application'},
            level='warning',
        )
```

should work.

**Comment by DanEEStar** [comment]
It worked as keyword argument. Thanks.
