### ISSUE TITLE
Indicate order of magnitude on error "sparklines"

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2021]
Right now, our bar char lines are only scaled relative within a project. When looking at an overview of all projects, it's hard to get a sense of scale between them.

I think we could indicate this simply with some color shading for orders of magnitude, or some banding that makes sense to us.

For example, 1-10 green, 10-100 orange, 100-1000 red, or some other visual.

Or we can just display the "max" value of the graph. Something along these lines.

Re: https://sentry.zendesk.com/agent/tickets/502

/cc @dcramer

**Comment by aaronfay** [comment]
As an example, even showing the chart max would be tremendously helpful in showing the scale: 

![max](https://i.gyazo.com/5cfc97c8f47bb2f947aa9e64f7a1f553.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
