### ISSUE TITLE
Slack Integration: Error: 'no client id' when adding slack to a workspace

### ISSUE THREAD

**Issue by AchoArnold** [getsentry/sentry#20215]
Hello, 

When I click the add workspace button, I get an error saying the client_id is missing.

<img width="582" alt="Schermafbeelding 2020-08-13 om 17 30 43" src="https://user-images.githubusercontent.com/4196457/90154830-e545be80-dd8a-11ea-9dc7-3a72a4c07497.png">
<img width="1229" alt="Schermafbeelding 2020-08-13 om 17 30 49" src="https://user-images.githubusercontent.com/4196457/90154842-e676eb80-dd8a-11ea-9ac1-1cea295bc8ef.png">

**Comment by joeldhenry** [comment]
Same issue for me....i can see in https://develop.sentry.dev/integrations/slack/ it shows you how to manually integrate, but it would be much nicer to be able to add without having access to the server

**Comment by joeldhenry** [comment]
related to? https://github.com/getsentry/sentry/issues/9004 ????

**Comment by AchoArnold** [comment]
Duplicate of https://github.com/getsentry/sentry/issues/14850
