### ISSUE TITLE
Surface a better Security Violation error when fetching source

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2022]
We should display a better message to the user about this, and point them to documentation for uploading sources or something actionable. As-is, many users see this and don't know how to fix/respond to it.

**Comment by regou** [comment]
I have this problem, and source code can not display. Anyone know how to fix it?
![8aa832d9-5525-4923-b784-baae2a429c27](https://cloud.githubusercontent.com/assets/1773856/11141900/632b4c58-8a24-11e5-8277-3d539a2513f4.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
