### ISSUE TITLE
Add Blacklist for REMOTE_ADDR to block abuse requests

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2023]
- [x] Add backend filter (GH-2025)
- [x] Expose configuration in UI (GH-2026)
- [x] Expose metrics to user in UI (GH-2034)

**Comment by jchen123** [comment]
+1

**Comment by dcramer** [comment]
Is this done?

**Comment by mattrobenolt** [comment]
Oh. Yeah.

**Comment by jchen123** [comment]
lol sup guys

- jzc
