### ISSUE TITLE
Search widget does not allow values outside of typeahead

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2024]
If you attempt to enter a value that is not part of the typeahead results it fails (or worst case, selects something you didn't want).

**Comment by dcramer** [comment]
A good way to reproduce this annoying behavior:

1. Copy/paste a random URL
2. Click the search bar
3. Put "helloworldabc" in to paste buffer
4. Type server: and then hit cmd+v
5. Hit enter and flip tables when it does random shit

The two outcomes are:

- ``server:server:``
- ``server:[some random unrelated entry]``

**Comment by benvinegar** [comment]
Addressed by two changes:

12f317ab232ae5e0b01fe1f3ea52e70d57eeb2e2
737000c95131f451c72c418677c5305af07b7e1c
