### ISSUE TITLE
ReadableStreamCreateReadResult is not defined

### ISSUE THREAD

**Issue by libt-web** [getsentry/sentry#20267]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 20.8.0.dev0

## Description
sentry report error in endless loope.
sdk version: sentry/browser 5.20.1

tagert os:Mac OS X 10.15.5
target browser:Chrome 69.0.3497
mechanism:onunhandledrejection

it looks like sentry sdk throw some error in onunhandledrejection and send report.

**Comment by hexh250786313** [comment]
I've got the same problem. But I thought it might be a browser problem. I upgraded Chrome to the latest version and the problem was resolved.

**Comment by BYK** [comment]
Please follow the issue template and provide as much information as possible such as logs and stacktraces. Closing the issue as it is not actionable with this information.
