### ISSUE TITLE
Sentry's Web Interface Leads to Dead-Ends Configuring Slack's Newest Integration

### ISSUE THREAD

**Issue by willAtSwiftly** [getsentry/sentry#20299]
## Description

Sentry's web interface leads to dead-ends when trying to adjust existing alert rules for Slack's newest integration.

## Steps to Reproduce

1. Log into Sentry.io
2. Click Settings > Integrations > Slack
3. Click Configurations > Configure
4. From the list of Sentry projects, click any "Add Alert Rule" on the righthand side for any project.
5. The resulting page says "Page Not Found"

### What you expected to happen

To be able to configure the Slack alerting rules for a Sentry project.

### Possible Solution

By testing different URLs I found that `https://sentry.io/organizations/${ ORGANIZATION }/alerts/rules/` does exist and works if I manually navigate there. It's the `/rules/new` route – where all the "Add Alert Rule" buttons attempt to navigate – that appears broken.

**Comment by davidenwang** [comment]
Hey sorry about the broken routes, we recently committed some changes that move alert features that were buried in settings into a sidebar page. 

You are correct in that `/alerts/rules/` is where you can view all alert rules. Creating an alert rule should reside at `/alerts/{project.slug}/new/`. 

Hopefully manual navigation won't be needed though as recent changes were pushed out to fix un-migrated links. Let us know if you're still having issues, thanks!
