### ISSUE TITLE
Supporting Google Appengine

### ISSUE THREAD

**Issue by zemanel** [getsentry/sentry#203]
I started today setting up a project to try and run a django-sentry server on Google Appengine:

https://bitbucket.org/zemanel/django-sentry-appengine/src

but hit a roadblock as the "socket" module is blacklisted in the Python sandbox and it's used to get the environment hostname, at least in :

https://github.com/dcramer/django-sentry/blob/master/sentry/conf/defaults.py

Would it be possible for django-sentry to be appengine friendly?

**Comment by thedrow** [comment]
Yes please.
Ping @dcramer

**Comment by dcramer** [comment]
Yep. Definitely no plans to support app engine for the server.

**Comment by poiuytrez** [comment]
What are currently the issues that makes Sentry not to work on AppEngine? App Engine now supports MySQL (Google Cloud SQL).

**Comment by dcramer** [comment]
@poiuytrez primarily we simply dont want to support yet-another-limited-and-annoying platform. MySQL is already a headache for us and adding on GAE will just add more complexity.

Basically the more we support, the less useful Sentry becomes (as its harder to work around database and hosting case).
