### ISSUE TITLE
Send notification email to account owner for going over quota

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2030]

**Comment by asbjornu** [comment]
:+1:

**Comment by mattrobenolt** [comment]
This was implemented for getsentry.com, but not sure if we plan to port it into sentry itself or not, of it it's valuable outside of our paid service.

**Comment by asbjornu** [comment]
@mattrobenolt I really appreciate the implementation in getsentry.com and don't really care whether it's implemented in Sentry itself.

**Comment by mattrobenolt** [comment]
Cool, then I'm going to close this since we don't have immediate plans for bringing this into on-premise.

/cc @tkaemming
