### ISSUE TITLE
Double encoding querystrings when replaying request

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2031]
> I've noticed a problem with the way Sentry encodes the query string when replaying requests.
> 
> So we had this in our query string: "500%7C999.00", which is correct, we had it encoded. But when replaying a request through a form or using the curl option, Sentry would encode it again and it will become "500%257C999.99" and the request would be different.
> 
> Certainly Sentry should not double encode the query string.

Refs: https://sentry.zendesk.com/agent/tickets/498

**Comment by hkdobrev** [comment]
Just to note I've experienced this on Sentry 8 beta, I haven't tested it on the previous stable version.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
