### ISSUE TITLE
Automatic creation of Trello cards

### ISSUE THREAD

**Issue by mblhaunted** [getsentry/sentry#20321]
## Summary

The Trello integration as it stands could be much more useful. Who wants to manually push a ticket from the UI? Please allow the automatic creation of cards for every issue. Please allow the user to configure what board these cards are pushed to. 

## Motivation

This would make it far easier to create an active queue of work for engineers responding to Sentry errors. Having to pick and choose what errors are sent over should be an option, but not the only way the plugin works.

## Additional Context

N/A

**Comment by BYK** [comment]
I _think_ you can achieve this via our generic webhooks integration: https://docs.sentry.io/product/integrations/integration-platform/webhooks/
