### ISSUE TITLE
Crash Report & Focus Lock

### ISSUE THREAD

**Issue by jonathan-wondereur** [getsentry/sentry#20336]
When I have elements on my page using a Focus Lock and the crash report dialogue come up I can not focus on the crash report input fields (as the focus is locked by the focus lock).

I am using Vue Focus Lock: https://github.com/theKashey/vue-focus-lock

**Comment by BYK** [comment]
@jonathan-wondereur it is unlikely that we'll be able to look into this soon but if you have any ideas, we'd gladly accept a PR to fix this.

**Comment by BYK** [comment]
Here's the code for the report dialog: https://github.com/getsentry/sentry-javascript/blob/d44a1d95e8ddd329cee10b6362a1b93d6d653aed/packages/browser/src/client.ts#L26-L47

**Comment by BYK** [comment]
Ping @priscilawebdev and @getsentry/app-frontend

**Comment by priscilawebdev** [comment]
I added this issue to our UI Backlog so we can check it soon 😉

**Comment by markstory** [comment]
@jonathan-wondereur Are you hoping that sentry's user feedback dialog will undo/break the focus lock your application has put in place?

**Comment by jonathan-wondereur** [comment]
Yes, I was hoping that sentry's user feedback dialogue would undo/break the current focus lock so a user can provide feedback.

Ideally, when the feedback was submitted the focus lock from my application would take over again.

**Comment by markstory** [comment]
@jonathan-wondereur I recognize that behavior being useful, but I don't know if that is feasible for us to do. Focus locks can be implemented in a variety of ways and unbinding the event handlers used to create focus locks requires access to the functions that were attached, and the elements focus was trapped to. Those elements could be at any depth in the DOM, and the listener functions are not generally accessible.

We recently shipped a change to the user feedback dialog that uses a simple focus trap that might help, but I can't be confident that it will work in your specific setup.

**Comment by jonathan-wondereur** [comment]
I wonder if there could be an option to open the user feedback in a popup, new tab/window to get around this?

**Comment by chadwhitacre** [comment]
Adding to the backlog on the strength of https://github.com/getsentry/sentry/issues/20336#issuecomment-791460354. Sound right @priscilawebdev?

**Comment by BYK** [comment]
@jonathan-wondereur - as @markstory mentioned earlier, we have shipped a potential fix for this. Is this still an issue for you? If it is we may explore your suggestion for a new tab/popup. Thanks a lot for reporting!

**Comment by markstory** [comment]
I'm not confident that a popup window is a robust approach. Most browsers block popup windows that aren't directly created by a user action. The feedback window would fall into this bucket and likely be blocked requiring the user to also approve the popup.

**Comment by jonathan-wondereur** [comment]
Ya, you are 100% right @markstory

**Comment by priscilawebdev** [comment]
I think we can now close this issue :)

**Comment by jonathan-wondereur** [comment]
That is unfortunate as it means the crash report can not work with focus lock, meaning I can not use it for my site. I would assume others would have this issue if they have models on their site ...

**Comment by BYK** [comment]
@jonathan-wondereur you can always use the API directly: https://docs.sentry.io/api/projects/submit-user-feedback/
