### ISSUE TITLE
Reports are received without a stacktrace, sentry.io shows "There was 1 error encountered while processing this event"

### ISSUE THREAD

**Issue by AlCalzone** [getsentry/sentry#20359]
## Important Details

How are you running Sentry?

Saas (sentry.io), Node.js SDK 5.21.1

## Description
I regularly receive error reports that do not contain a stack trace. When this happens, the sentry.io UI shows that there was an error while processing the event. It feels like reports like these are happening more frequently recently.

An example of such a report can be seen here:
https://sentry.io/share/issue/294b1404774d4a6cabcaf0fb9a680aab/

I'm not sure what can happen in a Node.js environment that causes an error to have no stacktrace.

## Steps to Reproduce

1. ???

### What you expected to happen

The report should contain a stack trace

### Possible Solution

???

**Comment by BYK** [comment]
Have you tried [contacting our support](https://sentry.io/contact/support/) for this?

**Comment by AlCalzone** [comment]
Not yet. Since I haven't seen this error in a while, I'm going to close this until it happens again.
