### ISSUE TITLE
PerformanceObserver.takeRecords Not available on some devices

### ISSUE THREAD

**Issue by woshiwanglizhi** [getsentry/sentry#20355]
## Important Details

On-Premise w/ Docker, version 5.20.1

I find **PerformanceObserver.takeRecords** On **Mac OS X 11.0** and **IOS 14**, **r.takerecords is not a function. (in 'r.takerecords()','r.takerecords' is undefined)** error will be reported, which will cause page stuck
![image](https://user-images.githubusercontent.com/46189766/90997153-5854fd80-e5f3-11ea-9d14-eec3733fd333.png)

**Comment by dashed** [comment]
@woshiwanglizhi this will be addressed by https://github.com/getsentry/sentry/pull/20341

/cc @AbhiPrasad

**Comment by woshiwanglizhi** [comment]
> @woshiwanglizhi这将通过[＃20341解决](https://github.com/getsentry/sentry/pull/20341)
> 
> / cc @AbhiPrasad

Thanks
