### ISSUE TITLE
Sentry Sending envelopes return event rejected due to rate limit

### ISSUE THREAD

**Issue by myonlylonely** [getsentry/sentry#20362]
Sending any envelope will return 429。Should I configure something?

```json
{"detail":"event rejected due to rate limit"}
```

**Comment by souradeepmajumdar05** [comment]
Can i take up this issue?

**Comment by BYK** [comment]
You may want to read on this: https://docs.sentry.io/product/accounts/quotas/#what-counts-toward-my-quota-an-overview

If you still need help, please [contact our support](https://sentry.io/contact/support).
