### ISSUE TITLE
Sentry invitation email

### ISSUE THREAD

**Issue by nilroy** [getsentry/sentry#2042]
When we invite a user from sentry it sends an email with a URL http://sentry:9000/xxxxx
In my deployment I am not exposing 9000 port in the firewall but using nginx to reverse proxy. Is there a way to change the URL in the invitation email?

**Comment by dcramer** [comment]
You need to configure SENTRY_URL_PREFIX to be the correct URL. If you are doing that, please look at the related documentation to ensure your proxy is setup correctly.

**Comment by nilroy** [comment]
Thanks..That works...
