### ISSUE TITLE
Transactions not showing up in the Performance tab

### ISSUE THREAD

**Issue by abhishek-ram** [getsentry/sentry#20435]
## Important Details

How are you running Sentry?

On-Premise w/ Kubernetes, version 20.7.2

## Description

I am able to see transactions being recorded in the Events tab but when I open the Performance tab it says "No Results Found"

## Steps to Reproduce

1. Open the Events tab to see the transactions
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/7054720/91383638-41f4af00-e84a-11ea-9171-246064f7117f.png">

2. Open the Performance tab and it shows no results
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/7054720/91383688-65b7f500-e84a-11ea-87aa-397b3ebe8502.png">

### What you expected to happen

Transactions should show up in the Performance tab

**Comment by abhishek-ram** [comment]
I was digging into this further and I guess this API is being called `https://sentry.dev.spotdraft.com/api/0/organizations/sentry/eventsv2/` for the transactions page. Now the thing is if the API is called with any of these p50(), p95(), failure_rate(), apdex(300), user_misery(300) in the field param then it returns no result, but if I exclude them then I get results. 

I am not sure what this implies.

**Comment by silent1mezzo** [comment]
@abhishek-ram I'm not able to reproduce locally so just trying to get more information. Is the Performance page empty when you first go to it? What's the full set of query params for `/api/0/organizations/sentry/eventsv2/`?

**Comment by abhishek-ram** [comment]
The performance page is empty whenever I go to it and not just the first time. 

The full url being called is https://sentry.dev.spotdraft.com/api/0/organizations/sentry/eventsv2/?statsPeriod=24h&project=2&environment=DEV&field=transaction&field=project&field=epm()&field=p50()&field=p95()&field=failure_rate()&field=apdex(300)&field=count_unique(user)&field=user_misery(300)&sort=-epm&per_page=50&query=event.type%3Atransaction

I installed sentry using this chart https://github.com/sentry-kubernetes/charts BTW.

One more thing I noticed is that in the clickhouse database the tables sentry_local and sentry_dist have data but the tables transactions_local and transactions_dist do not have any data.

**Comment by dashed** [comment]
See https://github.com/sentry-kubernetes/charts/issues/162#issuecomment-682331201 and https://github.com/sentry-kubernetes/charts/pull/142

**Comment by abhishek-ram** [comment]
thanks
