### ISSUE TITLE
hard to distinguish stack frames

### ISSUE THREAD

**Issue by phemmer** [getsentry/sentry#2043]
With the new stacktrace design, it is rather hard to distinguish between stack frames. You can do it, but just glancing at it, it appears to be just one big wall of text. It gets even worse if the lines wrap, or if you have frames without source code available.

![image](https://cloud.githubusercontent.com/assets/1826947/10168687/e3598112-669b-11e5-9445-e884f5ed2ea0.png)

One minor tweak of just reducing the line spacing makes a significant improvement:
![image](https://cloud.githubusercontent.com/assets/1826947/10168773/445cfa02-669c-11e5-8f53-692ba6443ac7.png)

And the a border makes it even better (though it would be better if the border were more subtle):
![image](https://cloud.githubusercontent.com/assets/1826947/10168819/8136b418-669c-11e5-8028-a2a7070f7fa4.png)

Another option might be to number the frames. Add a column to the left side, with the number aligned to the top of the new stack frame.

**Comment by mattrobenolt** [comment]
@phemmer would you say that the old styles were better, just for comparison? Or have we regressed for you?

/cc @ckj

**Comment by phemmer** [comment]
They were better yes. I think mainly due to 2 things, they had less line spacing, and the frame header was bolded.
I think even the old style had room for improvements, but it was still much easier than it is now to skim through the stack trace.

**Comment by ckj** [comment]
Thanks for the suggestions here, @phemmer. I agree that making the frame header bold + reducing the line-height makes this a bit more skimmable.
 <img width="906" alt="screen shot 2015-09-30 at 3 30 01 pm" src="https://cloud.githubusercontent.com/assets/30713/10208434/3c4df0b8-6788-11e5-9d9a-c3304c82a098.png">
