### ISSUE TITLE
Background workers haven't checked in recently. It seems that you have a backlog of 10664 tasks. Either your workers aren't running or you need more capacity.

### ISSUE THREAD

**Issue by NxGreen** [getsentry/sentry#20476]
## Important Details
![image](https://user-images.githubusercontent.com/5018004/91531982-3be0fa00-e940-11ea-8925-dfdea002d641.png)

`
vue.config.js
const SentryCliPlugin = require(’@sentry/webpack-plugin’);
new SentryCliPlugin({
include: './center_web',
ignoreFile: '.sentrycliignore',
ignore: ['node_modules', 'webpack.config.js'],
configFile: 'sentry.properties',
release: 'center@test01',
})

main.js
import * as Sentry from "@sentry/browser";
import { Vue as VueIntegration } from “@sentry/integrations”;
Sentry.init({
release: ‘center@test01’,
dsn: “http://4103a9a5212e4aaea7e7a7a751a165b5@192.168.3.182:9000/3”,
integrations: [new VueIntegration({ Vue, attachProps: true })],
});
Sentry.captureException(new Error(‘release’))

.sentryclirc
[defaults]
url = http://192.168.3.182:9000/
org = sentry
project = center

[auth]
token = 0285941f3dac46b69cd7e8ff4be832c79a191c490522413da07bfaaab85d0c0b
`

![image](https://user-images.githubusercontent.com/5018004/91532701-3df78880-e941-11ea-87aa-36523a65bc37.png)

How are you running Sentry?
i have installed the Sentry server myself，How to cancel this。
And I used webpack cli to release the center test1 version, and I did not receive a problem prompt

`Client:
 Debug Mode: false

Server:
 Containers: 24
  Running: 24
  Paused: 0
  Stopped: 0
 Images: 25
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-693.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.51GiB
 Name: localhost.localdomain
 ID: I3TM:4HYJ:OOL3:KQGM:JYY4:QEUM:WPOX:NWMO:6WAQ:BK5V:SJ6Y:OJZ5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
`
`
CONTAINER ID        IMAGE                                                             COMMAND                  CREATED             STATUS              PORTS                          NAMES
6deb0143d748        nginx:1.16                                                        "nginx -g 'daemon of…"   4 days ago          Up 4 days           0.0.0.0:9000->80/tcp           sentry_onpremise_nginx_1
bc479c0529ed        sentry-cleanup-onpremise-local                                    "/entrypoint.sh '0 0…"   4 days ago          Up 4 days           9000/tcp                       sentry_onpremise_sentry-cleanup_1
d5fa9adc0017        sentry-onpremise-local                                            "/bin/sh -c 'exec /d…"   4 days ago          Up 4 days           9000/tcp                       sentry_onpremise_cron_1
abdd9a64b433        sentry-onpremise-local                                            "/bin/sh -c 'exec /d…"   4 days ago          Up 4 days           9000/tcp                       sentry_onpremise_ingest-consumer_1
56ac0eba00d3        sentry-onpremise-local                                            "/bin/sh -c 'exec /d…"   4 days ago          Up 4 days           9000/tcp                       sentry_onpremise_worker_1
20410f0fd17d        sentry-onpremise-local                                            "/bin/sh -c 'exec /d…"   4 days ago          Up 4 days           9000/tcp                       sentry_onpremise_post-process-forwarder_1
c21338d9774e        sentry-onpremise-local                                            "/bin/sh -c 'exec /d…"   4 days ago          Up 4 days           9000/tcp                       sentry_onpremise_web_1
381d373a7c5b        getsentry/relay:latest                                            "/bin/bash /docker-e…"   4 days ago          Up 4 days           3000/tcp                       sentry_onpremise_relay_1
8ce7e98a0f41        snuba-cleanup-onpremise-local                                     "/entrypoint.sh '*/5…"   4 days ago          Up 4 days           1218/tcp                       sentry_onpremise_snuba-cleanup_1
a0492a69db8d        symbolicator-cleanup-onpremise-local                              "/entrypoint.sh '55 …"   4 days ago          Up 4 days           3021/tcp                       sentry_onpremise_symbolicator-cleanup_1
10898673bbbf        getsentry/snuba:latest                                            "./docker_entrypoint…"   4 days ago          Up 4 days           1218/tcp                       sentry_onpremise_snuba-consumer_1
fb5746a289e0        getsentry/snuba:latest                                            "./docker_entrypoint…"   4 days ago          Up 4 days           1218/tcp                       sentry_onpremise_snuba-replacer_1
4fdfcb1c9a1b        getsentry/snuba:latest                                            "./docker_entrypoint…"   4 days ago          Up 4 days           1218/tcp                       sentry_onpremise_snuba-api_1
8e770a1420ec        getsentry/snuba:latest                                            "./docker_entrypoint…"   4 days ago          Up 4 days           1218/tcp                       sentry_onpremise_snuba-sessions-consumer_1
311194c70a13        getsentry/snuba:latest                                            "./docker_entrypoint…"   4 days ago          Up 4 days           1218/tcp                       sentry_onpremise_snuba-transactions-consumer_1
cb0513bcd7f7        getsentry/snuba:latest                                            "./docker_entrypoint…"   4 days ago          Up 4 days           1218/tcp                       sentry_onpremise_snuba-outcomes-consumer_1
271ca40c0d25        memcached:1.5-alpine                                              "docker-entrypoint.s…"   4 days ago          Up 4 days           11211/tcp                      sentry_onpremise_memcached_1
a1cfde74ae6b        postgres:9.6                                                      "docker-entrypoint.s…"   4 days ago          Up 4 days           5432/tcp                       sentry_onpremise_postgres_1
d66976399744        tianon/exim4                                                      "docker-entrypoint.s…"   4 days ago          Up 4 days           25/tcp                         sentry_onpremise_smtp_1
84604259a148        getsentry/symbolicator:eac35a6058c7749bdf20ed219a377e49e02d0b76   "/bin/bash /docker-e…"   4 days ago          Up 4 days           3021/tcp                       sentry_onpremise_symbolicator_1
88dabf34e852        confluentinc/cp-kafka:5.5.0                                       "/etc/confluent/dock…"   4 days ago          Up 4 days           9092/tcp                       sentry_onpremise_kafka_1
87fad6512bd7        confluentinc/cp-zookeeper:5.5.0                                   "/etc/confluent/dock…"   4 days ago          Up 4 days           2181/tcp, 2888/tcp, 3888/tcp   sentry_onpremise_zookeeper_1
44fccb3fd1aa        redis:5.0-alpine                                                  "docker-entrypoint.s…"   4 days ago          Up 4 days           6379/tcp                       sentry_onpremise_redis_1
2ffbcb7b5fea        yandex/clickhouse-server:19.17                                    "/entrypoint.sh"         4 days ago          Up 4 days           8123/tcp, 9000/tcp, 9009/tcp   sentry_onpremise_clickhouse_1

`

## Description

[What happened]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. and so on.

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant

### What you expected to happen

[What you think should be happening]

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by keviiin38** [comment]
Same error happening on the On-Premise install with version `Sentry 20.9.0.dev 07126989`

Restarting the docker container `worker` seems to reduce the number of tasks in the backlog...

**Comment by keviiin38** [comment]
May be same problem as https://github.com/getsentry/sentry/issues/20315

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
