### ISSUE TITLE
Handle cases where AdBlock/uBlock are blocking XHR requests

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2049]
Since we use slugs for API calls, it's possible that a slug can trigger content blockers. In this case, we just error grossly with everything broken.

We should attempt to detect this and message to user.

**Comment by dcramer** [comment]
I think a good first pass here is to run a simple timeout on the loader.

If it takes i.e. 15 seconds we show a message saying it's taking a long time to load with some basic help tips (i.e. maybe your adblocker is causing problems)

**Comment by dcramer** [comment]
ae2a00096aaa063fe84766232adc9fb71246a56b adds some basic detection that can be used elsewhere

**Comment by mattrobenolt** [comment]
I don't think there's anything else we can do here. Detection is in.
