### ISSUE TITLE
Slack Integration: Cannot add workspace

### ISSUE THREAD

**Issue by michaelkrasa** [getsentry/sentry#20523]
When I click on "Add workspace" I'm greeted with this message.

![Screenshot from 2020-09-01 16-16-45](https://user-images.githubusercontent.com/6185094/91862819-b8404980-ec6e-11ea-938d-db9e25fc3e60.png)

I tried doing the same in incognito mode without any logins / cookies and the same problem occurred.

**Comment by dlibby-verys** [comment]
You'll have to set a few fields in your sentry's `config.yml`. This issue thread helped me out a lot: https://github.com/getsentry/sentry/issues/9004
