### ISSUE TITLE
Stream needs to show installation helper messages

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2054]
When a project has no "firstEvent" we need to show the helper message. This is a bit tricky as we dont update the project's state when events come in, so we might need to set the flag manually in the store.

**Comment by ckj** [comment]
@dcramer Is this flag implemented? Unsure of where to stick this

**Comment by mattrobenolt** [comment]
I assume we're talking about this:

![image](https://cloud.githubusercontent.com/assets/375744/13002444/6b90744a-d123-11e5-812b-f1674d3efabb.png)
