### ISSUE TITLE
"Sign In to Sentry" button not working

### ISSUE THREAD

**Issue by eyscode** [getsentry/sentry#20597]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

I'm trying to complete installation of Sentry+Jira integration ( I'm admin on JIRA and owner on Sentry), I already installed the app and when I go to JIRA -> Gear Icon -> Apps -> Manage Apps -> Sentry -> Get Started, I can see this page:

<img width="930" alt="Screen Shot 2020-09-03 at 15 08 42" src="https://user-images.githubusercontent.com/1343303/92162178-5d862980-edf7-11ea-8a46-69adbf08efac.png">
 
Sign In to Sentry button does not work tho, when I click it that redirects me to Sentry, and after sing in, nothing happens. If try again I got redirected again to Sentry and since I'm already signed in, I'm just redirect to my sentry issues. Then I cannot complete the integration. 

## Steps to Reproduce

1. Install JIRA+Sentry on JIRA
2. Manage Apps
3. Click on "Get Started"
4. Log in to sentry and nothing happens.

This is the logs from the web console on that `post-install-sentry` page:
```
Invalid 'X-Frame-Options' header encountered when loading 'https://sentry.io/extensions/jira/configure/?xdm_e=https%3A%2F%2Fhyketeam.atlassian.net&xdm_c=channel-sentry.io.jira__post-install-sentry&cp=&xdm_deprecated_addon_key_do_not_use=sentry.io.jira&lic=none&cv=1001.0.0-SNAPSHOT&jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZWY0MzcyMTE0ZjYwZTBhYzFiZDNkNmMiLCJxc2giOiIyMDliYzlmYjU5MjkxZjY0ZDljYTY2MzA0YzNjMDkxZWZjMTk5OTgyODkzZmNjN2FmNjQyYzViZDEwZGUwZDJjIiwiaXNzIjoiNzE0NWY2NWEtOTRjMi0zZDdkLTg3ZjYtNGEwMTBiOWE2ZGU4IiwiY29udGV4dCI6e30sImV4cCI6MTU5OTE2NDg1NCwiaWF0IjoxNTk5MTYzOTU0fQ.vU0OJYf2tF490qEJJjXTx6_pp4ld4wad6ZYx8SSxL9I': 'ALLOW-FROM https://hyketeam.atlassian.net' is not a recognized directive. The header will be ignored.
aui.min.js:1 DEPRECATED JS - Cookie has been deprecated since 5.8.0 and will be removed in a future release. Use cookie instead.   
     at assign (<anonymous>)
a @ aui.min.js:1
(anonymous) @ aui.min.js:1
get @ aui.min.js:1
n.default @ aui.min.js:1
(anonymous) @ aui.min.js:6
(anonymous) @ aui.min.js:6
4batch.js?jag=true&locale=en-US:3151 WARN: 'triggerPrivacyPolicySafeEvent' has been deprecated
```

### What you expected to happen

I suppose Sentry should show me something to conclude the integration right? otherwise Sentry does not recognize any kind of integration.

### Possible Solution

No idea what happen.

**Comment by manuzope** [comment]
Hey @eyscode, does enabling 3rd party cookies in your browser make it work?

**Comment by mAAdhaTTah** [comment]
I can confirm I'm experiencing this & that I do not have 3rd party cookies disabled.

**Comment by mAAdhaTTah** [comment]
@manuzope I see this in my console, which may explain the issue:

> Invalid 'X-Frame-Options' header encountered when loading 'https://sentry.io/extensions/jira/configure/?<long-query-string>': 'ALLOW-FROM https://ollie.atlassian.net' is not a recognized directive. The header will be ignored.

**Comment by manuzope** [comment]
Hey @mAAdhaTTah / @eyscode -- we were able to replicate this. Thanks for reporting it. We're looking into it. In the meantime, I was able to get it to work on Safari after enabling third party cookies (it's disabled by default). Could you try that to unblock you?

**Comment by mAAdhaTTah** [comment]
@manuzope I don't have 3rd party cookies blocked in Chrome. Is the suggestion to enable them in Safari and try it?

**Comment by manuzope** [comment]
@mAAdhaTTah Yep! That worked for me. Here's what my privacy tab in Safari looks like.

<img width="776" alt="Screen Shot 2020-09-10 at 5 07 24 PM" src="https://user-images.githubusercontent.com/1417849/92828694-3051f200-f388-11ea-9d8e-6900f6ecfe3c.png">

**Comment by mAAdhaTTah** [comment]
@manuzope Yeah, Safari worked correctly for me, so I at least have the integration working.

**Comment by eyscode** [comment]
@manuzope it worked on Safari. Thanks.
