### ISSUE TITLE
GitHub Integration: Cannot remove integration after uninstalling from GitHub

### ISSUE THREAD

**Issue by kfrz** [getsentry/sentry#20599]
- Using Sentry on-premise `10.0.1`, installed with the barebones configuration.

I was able to install the configuration, however, after uninstalling the application on the GitHub side, I am still unable to remove the integration from Sentry. It shows "installed" on `$URL/settings/$ORG/integrations/`.

How do I ensure a GitHub integration is removed?

**Comment by scefali** [comment]
@kfrz Hmm...it sounds like you didn't get the webhook event to delete the integration. You could try reinstalling it on Github than uninstalling it again.

**Comment by kfrz** [comment]
I wasn't able to delete the integration after reinstalling and uninstalling - ended up with two dangling installations :joy_cat: 

Is there a `sentry` CLI option to prune an installation? Maybe manually triggering the webhook? I haven't had time to spelunk the Sentry codebase yet.

**Comment by scefali** [comment]
@kfrz It sounds like you didn't configure your integration correctly so you'd get the webhook for the uninstallation event. I would double-check your app in Github. But if you are just trying to remove it, might not be worth the trouble.

There's no CLI command to delete installations like that. If you really want to delete the app, your best bet is going in the DB and removing the rows from the `sentry_integration` and `sentry_organizationintegration` tables. But really, I'd ask you why you are worried about having extra installations?

**Comment by kfrz** [comment]
It's not so much a worry as a "cleanup" task - we tested using my personal GitHub account but all applications must be owned by our organization, so after testing, we transferred the application and re-install.

**Comment by kfrz** [comment]
Thanks for following up on this - we managed to figure out what needs to happen!

**Comment by scefali** [comment]
@kfrz btw, I recently merged a change that will allow you to uninstall Github from Sentry. It will be in the next on-prem release.
