### ISSUE TITLE
Sentry distributed tracing for Java apps

### ISSUE THREAD

**Issue by gamefundas** [getsentry/sentry#20644]
Is there going to be distributed tracking support for Java apps. I see that only few platforms; Nodejs, Python etc are supported at the moment.

**Comment by gamefundas** [comment]
Any update on this, whether this is in the pipeline?

**Comment by BYK** [comment]
@bruno-garcia @bowencai8 - anything you can share?

**Comment by bowencai8** [comment]
@gamefundas @BYK Java is currently in-progress 👍 . You can follow updates here: https://github.com/getsentry/sentry-java

**Comment by BYK** [comment]
@gamefundas you can follow this PR: https://github.com/getsentry/sentry-java/pull/971

Closing in favor of that 🙂 

Thanks a lot @bowencai8!
