### ISSUE TITLE
Sentry ignores uploaded sourcemap

### ISSUE THREAD

**Issue by llisonly** [getsentry/sentry#20648]
![image](https://user-images.githubusercontent.com/4126495/92364724-0ef1cb80-f126-11ea-9f54-7942d50ceeca.png)
![image](https://user-images.githubusercontent.com/4126495/92364806-32b51180-f126-11ea-91ae-b73f33fc8bdb.png)
![image](https://user-images.githubusercontent.com/4126495/92364915-46607800-f126-11ea-96e7-c756cc360a18.png)

**Comment by llisonly** [comment]
sentry tries to get the sourcemaps from http, resulting in 404, instead of using the release artifacts

**Comment by DomenicoCardillo** [comment]
I had the same problem with a self-hosted istance of sentry, I resolved following this comment https://forum.sentry.io/t/offline-sourcemaps-not-used/548/3 and setting the main sentry and workers containers with the same image and same settings

**Comment by BYK** [comment]
Closing as this sounds more like a configuration issue and doesn't have enough information for us to do anything about it.
