### ISSUE TITLE
pytest assumes running redis on localhost

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2068]
In `sentry.utils.pytest`, we try to `flushdb` with no host or port settings, so this assumes localhost. Should pull from settings.

``` python
client = StrictRedis(db=9)
client.flushdb()
```

**Comment by tkaemming** [comment]
This should be a straightforward fix now after GH-2714, if there is a good way to mount the configuration in the test environment, replacing this section: https://github.com/getsentry/sentry/blob/9cc9c10092b0798e7e848450e0d0b58fd974f0d7/src/sentry/utils/pytest.py#L98-L106

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
