### ISSUE TITLE
New install on 7.7.0 and cannot login on Sentry nor /admin

### ISSUE THREAD

**Issue by decklord** [getsentry/sentry#2069]
Hi, I just configured Sentry on a stand alone machine. Previously I was using 6.X on a shared environment. I'm using postgres as recommended.

My problem is that if I go to login and enter the credentials used when running the command "sentry createuser" the server doesn't says anything and I get redirected back to login again. If I try another user/pass combination, I get an error message. I get the same behaviour when I go to the Django admin.

I read the logs and I don't get anything. Any ideas on how to debug this issue?

I'm using reverse proxy with Apache, here is my conf:

    <VirtualHost *:*>

        ProxyPass / http://0.0.0.0:9000/
        ProxyPassReverse / http://0.0.0.0:9000/
        ProxyPreserveHost On
        RequestHeader set X-Forwarded-Proto "https" env=HTTPS

        CustomLog ${APACHE_LOG_DIR}/access.log combined
        ErrorLog ${APACHE_LOG_DIR}/error.log

        LogLevel warn

    </VirtualHost>
I'm running everything using supervisord, this is my configuration, there are the logs that I'm checking:

    [program:sentry-web]
    directory=/home/user/.virtualenvs/sentry/
    environment=SENTRY_CONF="/home/user/Sentry/sentry.conf.py"
    command=/home/user/.virtualenvs/sentry/bin/sentry start
    autostart=true
    autorestart=true
    redirect_stderr=true
    stdout_logfile=/home/user/Sentry/logs/sentry-web.log
    stderr_logfile=/home/user/Sentry/logs/sentry-web.log

    [program:sentry-worker]
    directory=/home/user/.virtualenvs/sentry/
    environment=SENTRY_CONF="/home/user/Sentry/sentry.conf.py"
    command=/home/user/.virtualenvs/sentry/bin/sentry celery worker -B
    autostart=true
    autorestart=true
    redirect_stderr=true
    stdout_logfile=/home/user/Sentry/logs/sentry-worker.log
    stderr_logfile=/home/user/Sentry/logs/sentry-worker.log

My sentry configuration is as follows (all the sensitive info as domains/user/passwords are changed for dummy data): 

    # This file is just Python, with a touch of Django which means
    # you can inherit and tweak settings to your hearts content.
    from sentry.conf.server import *

    import os.path

    CONF_ROOT = os.path.dirname(__file__)

    DATABASES = {
        'default': {
            'ENGINE': 'sentry.db.postgres',
            'NAME': 'sentry',
            'USER': 'someuser',
            'PASSWORD': 'somepass',
            'HOST': '',
            'PORT': '',
        }
    }

    # You should not change this setting after your database has been created
    # unless you have altered all schemas first
    SENTRY_USE_BIG_INTS = True

    # If you're expecting any kind of real traffic on Sentry, we highly recommend
    # configuring the CACHES and Redis settings

    ###########
    # General #
    ###########

    # The administrative email for this installation.
    # Note: This will be reported back to getsentry.com as the point of contact. See
    # the beacon documentation for more information. This **must** be a string.

    SENTRY_ADMIN_EMAIL = 'my@email.com'
    SENTRY_SINGLE_ORGANIZATION = True

    #########
    # Redis #
    #########

    # Generic Redis configuration used as defaults for various things including:
    # Buffers, Quotas, TSDB

    SENTRY_REDIS_OPTIONS = {
        'hosts': {
            0: {
                'host': '127.0.0.1',
                'port': 6379,
            }
        }
    }

    SENTRY_PUBLIC = True

    #########
    # Cache #
    #########

    # If you wish to use memcached, install the dependencies and adjust the config
    # as shown:
    #
    #   pip install python-memcached
    #
    # CACHES = {
    #     'default': {
    #         'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
    #         'LOCATION': ['127.0.0.1:11211'],
    #     }
    # }
    #
    # SENTRY_CACHE = 'sentry.cache.django.DjangoCache'

    SENTRY_CACHE = 'sentry.cache.redis.RedisCache'

    #########
    # Queue #
    #########

    # See https://docs.getsentry.com/on-premise/server/queue/ for more
    # information on configuring your queue broker and workers. Sentry relies
    # on a Python framework called Celery to manage queues.

    CELERY_ALWAYS_EAGER = False
    BROKER_URL = 'redis://localhost:6379'

    ###############
    # Rate Limits #
    ###############

    # Rate limits apply to notification handlers and are enforced per-project
    # automatically.

    SENTRY_RATELIMITER = 'sentry.ratelimits.redis.RedisRateLimiter'

    ##################
    # Update Buffers #
    ##################

    # Buffers (combined with queueing) act as an intermediate layer between the
    # database and the storage API. They will greatly improve efficiency on large
    # numbers of the same events being sent to the API in a short amount of time.
    # (read: if you send any kind of real data to Sentry, you should enable buffers)

    SENTRY_BUFFER = 'sentry.buffer.redis.RedisBuffer'

    ##########
    # Quotas #
    ##########

    # Quotas allow you to rate limit individual projects or the Sentry install as
    # a whole.

    SENTRY_QUOTAS = 'sentry.quotas.redis.RedisQuota'

    ########
    # TSDB #
    ########

    # The TSDB is used for building charts as well as making things like per-rate
    # alerts possible.

    SENTRY_TSDB = 'sentry.tsdb.redis.RedisTSDB'

    ################
    # File storage #
    ################

    # Any Django storage backend is compatible with Sentry. For more solutions see
    # the django-storages package: https://django-storages.readthedocs.org/en/latest/

    SENTRY_FILESTORE = 'django.core.files.storage.FileSystemStorage'
    SENTRY_FILESTORE_OPTIONS = {
        'location': '/tmp/sentry-files',
    }

    ##############
    # Web Server #
    ##############

    ALLOWED_HOSTS = ("myip","mydomain.com")

    # You MUST configure the absolute URI root for Sentry:
    SENTRY_URL_PREFIX = 'http://mydomain.com'  # No trailing slash!

    # If you're using a reverse proxy, you should enable the X-Forwarded-Proto
    # header and uncomment the following settings
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    USE_X_FORWARDED_HOST = True

    SENTRY_WEB_HOST = '0.0.0.0'
    SENTRY_WEB_PORT = 9000
    SENTRY_WEB_OPTIONS = {
        'workers': 3,  # the number of gunicorn workers
        'limit_request_line': 0,  # required for raven-js
        'secure_scheme_headers': {'X-FORWARDED-PROTO': 'https'},
    }

    ###############
    # Mail Server #
    ###############

    # For more information check Django's documentation:
    #  https://docs.djangoproject.com/en/1.3/topics/email/?from=olddocs#e-mail-backends

    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

    EMAIL_HOST = 'email_host'
    EMAIL_HOST_PASSWORD = 'pass'
    EMAIL_HOST_USER = 'user'
    EMAIL_PORT = 25
    EMAIL_USE_TLS = False

    # The email address to send on behalf of
    SERVER_EMAIL = 'sentry@mydomain.com'

    # If you're using mailgun for inbound mail, set your API key and configure a
    # route to forward to /api/hooks/mailgun/inbound/
    MAILGUN_API_KEY = ''

    ########
    # etc. #
    ########

    # If this file ever becomes compromised, it's important to regenerate your SECRET_KEY
    # Changing this value will result in all current sessions being invalidated
    SECRET_KEY = 'somesecretkey'

**Comment by dcramer** [comment]
You should use 'sentry createuser'

I dont have time to review the full configuration, but if you're getting redirected it sounds like a mismatch of the URLs (look at the URL its redirecting you too). i.e. the proxy isnt sending the correct URL or SENTRY_URL_PREFIX is wrong.

**Comment by decklord** [comment]
I wasn`t using SSL. I removed from apache confg:

    RequestHeader set X-Forwarded-Proto "https" env=HTTPS

And removed from sentry config:

    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    USE_X_FORWARDED_HOST = True

Also commented this:

    SENTRY_WEB_OPTIONS = {
        'workers': 3,  # the number of gunicorn workers
        'limit_request_line': 0,  # required for raven-js
        #'secure_scheme_headers': {'X-FORWARDED-PROTO': 'https'},
    }
