### ISSUE TITLE
Webhook plugin internal error when clicking test configuration in 8.0 beta

### ISSUE THREAD

**Issue by dequis** [getsentry/sentry#2070]
>There was an internal error with the Plugin

That's the whole user-visible error.

Works fine in 7.x.

Tested with a http://requestb.in/ url, the server didn't receive any requests at all. Swiching the domain name from beta to app and doing the same thing worked.

**Comment by mattrobenolt** [comment]
Is this on getsentry.com? Or are you running it yourself?

**Comment by dequis** [comment]
getsentry.com. Sorry, forgot to mention. User dequis, project altovicio.

**Comment by mattrobenolt** [comment]
Alright, investigating. Not sure what the issue is. :( That error message is the fallback for when something really bad happens.

**Comment by mattrobenolt** [comment]
I see what the issue is. We definitely have a bug on our side.

Fixing.

**Comment by dequis** [comment]
Thanks! :heart:
