### ISSUE TITLE
Add next and previous thread buttons

### ISSUE THREAD

**Issue by tsondergaard** [getsentry/sentry#20746]
## Summary

In the issue view the thread combobox can have many items - looking through the stacktraces of threads is a lot of clicks and you have to remember the current thread yourself and find the next one in the thread combobox. This problem could be addressed very simply by adding two buttons - previous thread and next thread. The same type of buttons that are present in the same view for going through the list of events associated with the issue

## Motivation

Dramatically improves thread navigation and it is a small task to implement it.

## Additional Context

In the screenshot, I have borrowed the buttons for navigating events in the issue. The "Older" and "Newer" texts would be replaced with "Previous" and "Next".

![image](https://user-images.githubusercontent.com/2016842/93071609-a0aa8d00-f680-11ea-891a-7ba6673824ba.png)

**Comment by tsondergaard** [comment]
Please don't close this issue. The thread dropdown is a very big frustration. So many other things have been improved, but this remains a significant problem.

**Comment by karol-pilch** [comment]
I'm also interested in this feature. The implementation doesn't really matter for me, as long as there's an easy way to navigate to next / previous threads. I personally was googling for keyboard shortcuts and only found this issue here.

**Comment by markhajnal** [comment]
When you have an issue with 30-40 threads in it, it's really frustrating to use the dropdown list every time. Especially it doesn't remember where it was scrolled before and also the currently viewed thread is not highlighted.
This feature would be so helpful from UX POV.  It would be very much appreciated.

**Comment by Shreypatel13ll** [comment]
Hi there,

I'm interested in helping implement this improvement. Could someone please point me to the specific code file or files where these changes need to be made? Having the file path(s) would be extremely helpful in getting started.

Thanks!

**Comment by hubertdeng123** [comment]
@malwilley Is this something that we would prefer to do ourselves? Or should we help guide @Shreypatel13ll implement this?

**Comment by Shreypatel13ll** [comment]
any updates?

**Comment by rachrwang** [comment]
@tsondergaard, @karol-pilch, @markhajnal, @Shreypatel13ll  - we're actively working to design an updated experience, and would love to get feedback on our upcoming direction. Would any of you be open to chatting with the team to review designs for this? You can schedule directly with us here: https://calendar.app.google/FiLw4JTPxErwr69t6

**Comment by tsondergaard** [comment]
@rachrwang I'm thrilled to hear that sentry is working on this. I won't be able to join any meetings, but I will be happy to answer questions and provide feedback in an asynchronous manner.
