### ISSUE TITLE
API endpoint to query project events from specific environment

### ISSUE THREAD

**Issue by Isakrom-Ver** [getsentry/sentry#20786]
## Summary

Either augmenting the preexisting project event endpoint to allow filtering by environment or a new endpoint.

## Motivation

I'm currently working on a tool for my company to automate data aggregation and among the sources of data is sentry. However I can only query the sentry events for a given project across all environments which means that we can't tell between staging, test, and prod events via api calls.

**Comment by Nowaker** [comment]
+1 for this. Similar to #24043. Overall, the API needs a lot of improvements to be useful for anything of real value.

**Comment by chadwhitacre** [comment]
> Overall, the API needs a lot of improvements to be useful for anything of real value.

Sad but true. 😞

**Comment by chadwhitacre** [comment]
> Sad but true. 😞

... or I guess it could be happy and true. Improving stuff is fun! 😁

**Comment by BYK** [comment]
@getsentry/ecosystem @manuzope can you triage this?

**Comment by manuzope** [comment]
Hi @Isakrom-Ver, to confirm - you're talking about this endpoint: https://docs.sentry.io/api/events/list-a-projects-events/, yes?
