### ISSUE TITLE
Logs showing correctly in email but not dashboard

### ISSUE THREAD

**Issue by rdbreak** [getsentry/sentry#20830]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

[What happened]

I'm getting alerts for projects through email but can't see the same alerts when logging into my dashboard.

## Steps to Reproduce

1. Alert comes in my email
2. Click "View on Sentry"
3. Make sure I'm on the correct project, active issue is the only filter on, and all environments are selected

### What you expected to happen

I expect to see the same alerts in my dashboards as in my email.

### Possible Solution

Maybe auth related? I made sure I was using all the proper variables when using the SDK but I'm not sure where to go from here

**Comment by scttcper** [comment]
@rdbreak can you post the link you got in the email?

**Comment by rdbreak** [comment]
Hi @scttcper, do you mean the button link?

**Comment by scttcper** [comment]
@rdbreak yeah the button link

**Comment by rdbreak** [comment]
It has inexplicably started working normally. I'll close this issue.
