### ISSUE TITLE
Microsoft Teams Integration with On-Prem

### ISSUE THREAD

**Issue by cpressland** [getsentry/sentry#20834]
## Important Details

On-Premise w/ Docker, version 20.10.0.dev0

## Description

The new Microsoft Teams integration does not appear to support On-Prem Sentry Installations

## Steps to Reproduce

1. Within Microsoft Teams select the `...` Button next to a Team and Select "Manage team"
2. Click on the "Apps" tab
3. Click on "More apps"
4. Search for "Sentry", Select "Sentry" and click the 🔽 button and select "Add to a Team"
5. Confirm the correct Team and Channel are selected and click "Set up a bot"
6. On the new post from Sentry on the Teams General channel click the "Complete Setup" button
7. A browser launches and directs you to Sentry.io which asks you to login or setup an account

### What you expected to happen

Either an additional button or command to tell the bot to use a on-prem version of Sentry instead.

### Possible Solution

@scefali on #11690 suggests the bot does support on-prem installs, but currently isn't documented.

**Comment by scefali** [comment]
@cpressland Docs are ready. There are a lot of steps. Let me know if something doesn't work or make sense so I can update the docs. Check it out here: https://develop.sentry.dev/integrations/msteams/

**Comment by kfkawalec** [comment]
Hi, can anyone confirm that this integration works in on premise installation?
I can add bot, I see message "Welcome to Sentry for Microsoft Teams" and I have button "Complete Setup".
This button open me page with "Finish integration installation", but when I click "Install Microsoft Teams" the page is reloading (with 302 status code ) and I still see the sam page.
Integration in visible as "Not Installed".
There in no informatin in logs, only 302 redirect.

**Comment by outsmartin** [comment]
Similar Issue here. Trying to complete the installation it directly redirects to sentry.io instead of letting me choose our self hosted instance.
Should I create a new issue or will this one be reopened?

**Comment by kfkawalec** [comment]
Hi I'm not sure it's the same problem. I was only redirected to sentry.io if I tried to use buildin Teams integration.
But using the documentation for installing onpremise, there is no setnry.io at all:
https://develop.sentry.dev/integrations/msteams/

**Comment by BYK** [comment]
Seems like we need to investigate this a bit more.

**Comment by BYK** [comment]
@scefali @manuzope can you make sure this is verified to work with self-hosted and add relevant docs to https://develop.sentry.dev/?

**Comment by grimurd** [comment]
Can´t make this work either after following the [directions](https://develop.sentry.dev/integrations/msteams/). I can see in the nginx logs that the bot accesses the /extensions/msteams/webhook/ url but nothing happens, no message in the general channel or anything. No errors are reported in the logs nor in the internal sentry project.

Using Sentry  20.11.1

**Comment by vincent-paing** [comment]
Any updates on this issue?

**Comment by manuzope** [comment]
Hey @vincent-paing, not yet, but we'll look into this soon.

**Comment by ceorourke** [comment]
I'm unable to reproduce any issue here having installed it locally recently. Can those having problems email partners@sentry.io with screenshots of the bot config and be sure to include what you have set for the bot endpoint address? Please include any other relevant information, logs, errors, etc. so we can look into this.

**Comment by grimurd** [comment]
For one reason or another it seems to work now. I went through the same steps as I went through several times before with the only difference being that this time it works.

**Comment by ceorourke** [comment]
I'm closing this since I haven't heard back from anyone experiencing issues but if this persists, feel free to reach out.
