### ISSUE TITLE
How to use Amazon ec2 private IP

### ISSUE THREAD

**Issue by wishabhilash** [getsentry/sentry#2085]
I have hosted sentry on my own server but do not want to use the public IP for logging since my required servers are within the same VPC. Using private IP makes more sense.

Is there a way to achieve this???

**Comment by dcramer** [comment]
The public/private address doesn't matter as long as it's reachable.

If you're asking how you can send events to Sentry using the private IP and access it via the public IP then you will need two routes or appropriate DNS to ensure the hostname is still the same.

**Comment by wishabhilash** [comment]
@dcramer  That is exactly my question. How to route it via private ip yet access public ip. The problem am facing with googling it is that, the word "sentry" is extremely common and irrelevant results are coming on top for me. Like "Sentry" from the DC universe and stuff. :D

It would be lot better if this thing can be helped out here itself in detail. Others will surely be looking for it anyway.

**Comment by dcramer** [comment]
You just need to configure your reverse proxy to accept requests and route things with the correct settings. There's nothing Sentry specific here other than Sentry forcing you to use SENTRY_URL_PREFIX when accessing the web interface.
