### ISSUE TITLE
Bitbucket Integration: integrations:bitbucket.webhook.invalid-ip-range

### ISSUE THREAD

**Issue by martinweinmayr** [getsentry/sentry#20876]
As it is mentioned in https://github.com/getsentry/sentry-plugins/issues/333 "it can happen again..."

It happens again...

In sentry i see "integrations:bitbucket.webhook.invalid-ip-range"

Sentry onpremise
Version: Sentry 20.10.0.dev0e327d14

**Comment by scefali** [comment]
@martijnjanssen Are you using on-prem Bitbucket? Because the Bitbucket integration is only for the SaaS product. If you using on-prem bitbucket, you need to use the Bitbucket Server integration. See: https://docs.sentry.io/product/integrations/bitbucket/#bitbucket-server

**Comment by martijnjanssen** [comment]
@scefali I think you mentioned the wrong person 😉

**Comment by martinweinmayr** [comment]
> @martijnjanssen Are you using on-prem Bitbucket? Because the Bitbucket integration is only for the SaaS product. If you using on-prem Bitbucket, you need to use the Bitbucket Server integration. See: https://docs.sentry.io/product/integrations/bitbucket/#bitbucket-server

Using bitbucket cloud.
As i habe seen they've newer ips in their range again

**Comment by scefali** [comment]
@martinweinmayr thanks for the clarification. Yes, this looks like a bug we need to fix.

**Comment by ceorourke** [comment]
I believe this should be resolved by https://github.com/getsentry/sentry/pull/26725
