### ISSUE TITLE
Can't disable data scrubber

### ISSUE THREAD

**Issue by mqklin** [getsentry/sentry#20878]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

https://sentry.io/settings/***/projects/***/#dataScrubber links doesn't work

### What you expected to happen

I'm trying to disable scrubbing (following this article https://help.sentry.io/hc/en-us/articles/115000154594-Why-am-I-seeing-Filtered-in-my-event-data-#:~:text=If%20you%20feel%20Sentry%20is,%E2%86%92%20uncheck%20%22Data%20Scrubber%22.), but I can't find these options
![123](https://user-images.githubusercontent.com/9456433/93746754-17aacd00-fc0f-11ea-8ca1-25ea74dedfc5.gif)

**Comment by untitaker** [comment]
Thanks, this is broken.. check Security & Privacy in the left, white sidebar to find those settings.
