### ISSUE TITLE
Sentry API 400s with "Please enter a valid email address" when commit emails contain TeamCity email addresses

### ISSUE THREAD

**Issue by rspechenkin** [getsentry/sentry#20881]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

We're using versioned settings in TeamCity and some commits have the email address like **username@TeamCity** and **teamcity@ip-xx-xxx-xx-xxx.domain_name** and that breaks the email validation. So it would be nice if you could remove this validation.

## Steps to Reproduce

1. Create a commit that contains an email address like  **username@TeamCity** or **teamcity@ip-xx-xxx-xx-xxx.domain_name** 
2. Run `sentry-cli releases -o $ORGANIZATION set-commits --auto $SHA1`

### What you expected to happen

Sentry's API should have accepted commits 

### Possible Solution

Remove the email validation as suggested [here](https://github.com/getsentry/sentry/pull/20342#issuecomment-688269672) ?

**Comment by silent1mezzo** [comment]
I've removed the email validation in #20342 now so it'll fix this problem once launched.

**Comment by BYK** [comment]
This should now be fixed as #20342 is out.
