### ISSUE TITLE
Ghost projects

### ISSUE THREAD

**Issue by DavidBabel** [getsentry/sentry#20912]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

We tried to create some projects but they are stuck and unmanageable : 
![image](https://user-images.githubusercontent.com/5599375/93898262-5023d700-fcf3-11ea-893c-c81c9fd274dd.png)

**Comment by bruno-garcia** [comment]
As a user of SaaS you can reach the support: https://docs.sentry.io/support/

**Comment by BYK** [comment]
Please [contact our support](https://sentry.io/contact/support/) for this. Closing in favor of that.
