### ISSUE TITLE
Slack Integration: No slack option on report issue

### ISSUE THREAD

**Issue by cmcaboy** [getsentry/sentry#20932]
This used to work just fine until a few months back. I'm not sure what changed, but I am no longer able to add a slack notification in the issue report section and our existing slack notifications stopped working. We have been on a premium pay tier for some time.

![image](https://user-images.githubusercontent.com/1489169/93957007-58930680-fd21-11ea-9d8f-141c3aed149d.png)

Ironically, there is an option to add a slack notification to the metrics alert section.

![image](https://user-images.githubusercontent.com/1489169/93957144-aad42780-fd21-11ea-8de8-1eae50b139f8.png)

Slack is installed and configured appropriately.

![image](https://user-images.githubusercontent.com/1489169/93957189-c0e1e800-fd21-11ea-888d-8d3ef6f36058.png)
![image](https://user-images.githubusercontent.com/1489169/93957216-cb9c7d00-fd21-11ea-8e37-adf0334b03d2.png)
![image](https://user-images.githubusercontent.com/1489169/93957222-d2c38b00-fd21-11ea-93af-4a5d945c5309.png)

**Comment by hodduc** [comment]
In my case, old projects have an option (Send a slack notification) while a new project does not have.
They have slightly different UI, though I'm not sure that is related.

Old Project
![image](https://user-images.githubusercontent.com/1841490/93989986-8893e580-fdc5-11ea-9c4b-c4e0200d12b9.png)


New Project
![image](https://user-images.githubusercontent.com/1841490/93990087-a9f4d180-fdc5-11ea-90ba-2306c8caf8a7.png)

**Comment by cmcaboy** [comment]
Thank you @hodduc. As per their documentation, it should be there so I would consider this a bug as both of us are encountering this issue.

**Comment by jonesphillip** [comment]
@cmcaboy @hodduc thanks for bringing it to our attention. This was fixed earlier this week so please try creating your alert rule again if you haven't already. Sorry about the experience, closing this out. Let us know if you have any other issues/feedback!
