### ISSUE TITLE
Alert rules can not be deleted when project is deleted

### ISSUE THREAD

**Issue by Gh0stWalk3r** [getsentry/sentry#20997]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

Alert rules are not deleted when project is deleted. Alert rules can neither be deleted nor edited when the project does not exist.

## Steps to Reproduce

1. Create project with alert rules.
2. Delete project.
3. Go to Alerts -> Rule with unknown project ID is still there.

![image](https://user-images.githubusercontent.com/10714600/94307848-d0596f00-ff75-11ea-836c-db208ea007c7.png)

### What you expected to happen

When deleting a project then all associated alert rules should also be deleted.

### Possible Solution

Delete Alert rules on deletion of project.

**Comment by BYK** [comment]
Have you tried [contacting our support](https://sentry.io/contact/support/) for this?

**Comment by Gh0stWalk3r** [comment]
So far I haven't as these rules got removed automatically some time later. I cant exactly tell how long it took as I was only checking from time to time.
My expectation was that those alert rules should be removed immediately when the project is deleted. As a first time user this is somewhat unexpected when it is cleaned up later.
IMHO this can be closed when it is an expected behavior.

**Comment by BYK** [comment]
@Gh0stWalk3r will close for now then. If you experience something similar, please contact our support first as they'll have more access to check this specifically on your account first.
