### ISSUE TITLE
On Premise: User is asked to create organization

### ISSUE THREAD

**Issue by categoryshell** [getsentry/sentry#21008]
## Important Details

I'm running Sentry 20.9.0 on premise with Docker

## Description
When i invite a user to another organization, other that the default/first, the user is asked to create a new organization upon account creation

[What happened]

## Steps to Reproduce
- Set SENTRY_SINGLE_ORGANIZATION to false in sentry/sentry.conf.py
- Create a second organization within the admin
- Invite new user within the new organization
- Have the user complete the registration process until he is asked to create a new organization

### What you expected to happen

I expect the user to join the organization i've added him to, without being asked to create a new one.

**Comment by dcramer** [comment]
SENTRY_SINGLE_ORGANIZATION is not intended for self-hosted, you should leave it to `True`.
