### ISSUE TITLE
Comments/Activity being in dedicated tab

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2102]
There have been a number of user complaints about this change, so opening ticket here for discussion.

How do we feel about this? I personally find it a bit weird since we name the tab "Comments", but it's conflated with general "activity" and the url is `/activity/`. So it seems that we don't really have a solid solution here.

On the other hand, the main group details page already has a lot of stuff, and shoving it back into there is probably not the right solution either.

/cc @dcramer @ckj

**Comment by benvinegar** [comment]
I think there are some small improvements we could try before deciding on completely moving things around.

Like making 1 or more comments stand out more ... say, with a purple background instead of grey.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
