### ISSUE TITLE
Redirect original event group urls after merge

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2104]
> Redirects for merged duplicates would be nice. Last we checked, if you merged A into B, A's URL would stop working. We reference events by URL in several places, and those URLs break.

Re: https://sentry.zendesk.com/agent/tickets/608

Off the top of my head, not sure how difficult this would be, but it seems like a reasonable request.

**Comment by dcramer** [comment]
Solution would likely be add a new object (GroupRedirect) which gets checked when a group doesnt exist.

**Comment by mattrobenolt** [comment]
This should be trivial to slam in.

**Comment by tkaemming** [comment]
Not sure how this is going to be affected by short ID changes, need to keep that in mind here.
