### ISSUE TITLE
celery workers are never recovering from a redis connection loss

### ISSUE THREAD

**Issue by drook** [getsentry/sentry#21133]
## Important Details

Instance: On-Premise wo/ Docker (standalone), version 20.8.0

## Description
When a redis connection from celery workers to a redis is somehow interrupted, celery workers aren't reconnecting back.

## Steps to Reproduce

1. Restart redis used by a sentry.
2. Notice the event flow has stopped.
3. Wait a bit.
4. Wait longer.
5. Restart only sentry celery workers.
6. Notice the event flow is restored.

Here's the sentry log around the event of redis restart:
````
Oct  4 20:10:01 jsentry sentry[25342]: ConnectionError: Error 61 connecting to 10.100.33.5:6379. Connection refused.
Oct  4 20:10:01 jsentry sentry[25342]: 17:10:01 [CRITICAL] celery.worker.request: Couldn't ack 'f4d4ddd5-bcf7-4f07-8a88-1291904bb010', reason:ConnectionError(u'Error 61 connecting to 10.100.33.5:6379. Connection refused.',)
Oct  4 20:10:01 jsentry sentry[25342]: Traceback (most recent call last):
Oct  4 20:10:01 jsentry sentry[25342]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/utils/metrics.py", line 98, in worker
Oct  4 20:10:01 jsentry sentry[25342]:     tsdb.incr(tsdb.models.internal, full_key, count=amount)
Oct  4 20:10:01 jsentry sentry[25342]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/utils/services.py", line 105, in <lambda>
Oct  4 20:10:01 jsentry sentry[25342]:     context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
Oct  4 20:10:01 jsentry sentry[25342]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/tsdb/redissnuba.py", line 87, in method
Oct  4 20:10:01 jsentry sentry[25342]:     return getattr(self.backends[backend], key)(*a, **kw)
Oct  4 20:10:01 jsentry sentry[25342]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/tsdb/redis.py", line 204, in incr
Oct  4 20:10:01 jsentry sentry[25342]:     self.incr_multi([(model, key)], timestamp, count, environment_id)
Oct  4 20:10:01 jsentry sentry[25342]:   File "/usr/local/lib/python2.7/site-packages/sentry-20.8.0-py2.7.egg/sentry/tsdb/redis.py", line 265, in incr_multi
Oct  4 20:10:01 jsentry sentry[25342]:     client.expireat(hash_key, key_expiries.pop(hash_key))
Oct  4 20:10:01 jsentry sentry[25342]:   File "/usr/local/lib/python2.7/site-packages/rb-1.7-py2.7.egg/rb/clients.py", line 625, in __exit__
Oct  4 20:10:01 jsentry sentry[25342]:     self.mapping_client.join(timeout=timeout)
Oct  4 20:10:01 jsentry sentry[25342]:   File "/usr/local/lib/python2.7/site-packages/rb-1.7-py2.7.egg/rb/clients.py", line 413, in join
Oct  4 20:10:01 jsentry sentry[25342]:     command_buffer.wait_for_responses(self)
Oct  4 20:10:01 jsentry sentry[25342]:   File "/usr/local/lib/python2.7/site-packages/rb-1.7-py2.7.egg/rb/clients.py", line 226, in wait_for_responses
Oct  4 20:10:01 jsentry sentry[25342]:     self.connection, command_name, **options)
Oct  4 20:10:01 jsentry sentry[25342]:   File "/usr/local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/client.py", line 680, in parse_response
Oct  4 20:10:01 jsentry sentry[25342]:     response = connection.read_response()
Oct  4 20:10:01 jsentry sentry[25342]:   File "/usr/local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/connection.py", line 624, in read_response
Oct  4 20:10:01 jsentry sentry[25342]:     response = self._parser.read_response()
Oct  4 20:10:01 jsentry sentry[25342]:   File "/usr/local/lib/python2.7/site-packages/redis-2.10.6-py2.7.egg/redis/connection.py", line 403, in read_response
Oct  4 20:10:01 jsentry sentry[25342]:     (e.args,))
Oct  4 20:10:01 jsentry sentry[25342]: ConnectionError: Error while reading from socket: ('Connection closed by server.',)
Oct  4 20:10:01 jsentry sentry[25342]: 17:10:01 [ERROR] sentry.errors: Unable to incr internal metric
Oct  4 20:10:01 jsentry sentry[25342]: Traceback (most recent call last):
````

Although the connection interruption isn't normal, it should not be fatal for a running sentry.
For me it happens once in a 3-5 days. Of course, I'm investigating it's original cause, but it would be nice to have a functionality when sentry reconnects to a redis automatically.

**Comment by azhurbilo** [comment]
The same on my side: redis failover triggered -> sentry stopped processing new events (but celery-worker container continue to work and not fail-fast with exception)

**Comment by drook** [comment]
Well, to be honest we added an ugly workaround: a script checking the Sentry REST API for event flow, and if there's no events for a configured timeout, we merely restart sentry workers. :( Ugly but working. But in our case we got massively loaded application, and an error rate (including mostly false-negative errors, like the ones triggered by client connection reset) about 300К/day. So it our case 0 errors in last 1 minute means workers lost the connection. This absolutely won't be working for installations that get only dozens/hundreds of errors per day.

**Comment by azhurbilo** [comment]
@drook not sure but may be celery version upgrade will fix it https://github.com/getsentry/sentry/blob/master/requirements-base.txt#L4

we are waiting next minor sentry version to check it

**Comment by BYK** [comment]
@azhurbilo I think this is the same celery version we've been using for some time now. I guess the fix is to have a health check in docker-compose and restart based on that?

**Comment by drook** [comment]
@BYK sounds more like a workaround, definitely not a fix.

**Comment by BYK** [comment]
@drook what do you think would be a proper fix? I think Celery should do this itself but that doesn't seem like the case and not sure if this is getting much love from Celery folks 🙂

**Comment by drook** [comment]
Well, I totally understand that traces lead into the upstream, but I'm not familiar with celery at all to report it there (unfortunately for me this is simply a component name). May be someone with more profound knowledge will/should do this, especially if redis connectivity is celery native feature. Also after a brief look at celery upstream I got an impression that they switched their development branch to a python 3.x long ago, may be reproducing this bug on a 3.x celery branch could potentially get more love. But yeah, in the context of Sentry this is even asking for more. But python 2.x applications are doomed in the nearest future anyway, so...

**Comment by BYK** [comment]
@drook we do have PY3 builds now, would you be willing to try this there: https://github.com/getsentry/onpremise#setup

(see the disclaimer tho) - You can just add `SENTRY_PYTHON3=1` in front of the `./install.sh` command and you can even use the latest `20.10.1` release if you don't want to go with nightlies. This release has a known and fixed GitHub integration bug so beware if that's something you use.

**Comment by alex88** [comment]
Keepalive

**Comment by BYK** [comment]
@drook @alex is this still an issue?

**Comment by benabineri** [comment]
We still see this (but we're on 20.6.0 still)

**Comment by BYK** [comment]
@benabineri is it possible for you to upgrade to 21.2.0 or 21.3.0 and see if it gets fixed?

**Comment by benabineri** [comment]
Yes, we plan to upgrade soon, I'll let you know whether this is fixed :)

**Comment by overstep123** [comment]
if this problem has been fixed? or I want to known if this problem would increase to data miss. (I think data would not miss if the redis command will retry if it failed).

**Comment by benabineri** [comment]
bump (we haven't upgraded yet but still plan to)

**Comment by BYK** [comment]
@benabineri @overstep123 we haven't heard any new reports on this recently so I am assuming this was fixed with some dependency or Python upgrades.

If you tried yourself and can report back, it would be useful to finally close this issue or pursue further investigation.
