### ISSUE TITLE
Invalid docstring creation in "load_script"

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [getsentry/sentry#21139]
Hello,

While analyzing Sentry on SonarCloud I saw what looks like an error in [`src/sentry/integrations/cloudflare/webhook.py`](https://github.com/getsentry/sentry/blob/46f5f8db111cd65d437761b2ef63df33bd614036/src/sentry/utils/redis.py#L262-L270):

<img width="1608" alt="Screenshot 2020-10-05 at 17 19 38" src="https://user-images.githubusercontent.com/40498978/95098482-042f5400-072f-11eb-8b78-6abafae2c097.png">

You can see [the issue in SonarCloud here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_sentry&issues=AXT5Osrk8YX1Q6Jis_Ak&open=AXT5Osrk8YX1Q6Jis_Ak).

Only literal strings are accepted as docstring when they are put after a class or function signature. A format expression will simply be considered part of the code.

Here is a concrete example using ipython:
```python
In [1]: def correct():
   ...:     """correct docstring"""
   ...: def invalid():
   ...:     """This is {}""".format("invalid")
   ...:

In [2]: print(correct.__doc__)
correct docstring

In [3]: print(invalid.__doc__)
None
```
A simple solution is to set directly `call_script.__doc__` after the function has been defined.

In case you want to scan Sentry on SonarCloud [you can use a configuration similar to this one](https://github.com/nicolas-harraudeau-sonarsource/sentry/commit/4a253740bfc19b25935efc5b23aff2f6a3acfc7f) when you enable automatic analysis. SonarCloud is free for open source projects.

**Comment by joshuarli** [comment]
This was fixed, I didn't do the magical "fixes" comment in the PR that addresses this.
