### ISSUE TITLE
Unreachable return statement in "CloudflareWebhookEndpoint.on_account_change" and "CloudflareWebhookEndpoint.on_organization_change"

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [getsentry/sentry#21137]
Hello,

While analyzing Sentry on SonarCloud I saw what looks like an error in `src/sentry/integrations/cloudflare/webhook.py` [here](https://github.com/getsentry/sentry/blob/76688bf0bd8145769c18e6c9b9460c30f0d7be9b/src/sentry/integrations/cloudflare/webhook.py#L105-L112) and [here](https://github.com/getsentry/sentry/blob/76688bf0bd8145769c18e6c9b9460c30f0d7be9b/src/sentry/integrations/cloudflare/webhook.py#L145-L152):

<img width="1600" alt="Screenshot 2020-10-05 at 17 04 26" src="https://user-images.githubusercontent.com/40498978/95096743-f678cf00-072c-11eb-8592-1938881ad8e5.png">

You can see the two issues in SonarCloud [here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_sentry&issues=AXT5Os8B8YX1Q6Jis_Ek&open=AXT5Os8B8YX1Q6Jis_Ek) and [here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_sentry&issues=AXT5Os8B8YX1Q6Jis_El&open=AXT5Os8B8YX1Q6Jis_El).

In both cases the return statement is unreachable because each path in the previous `if-else` block has a `return`. It might be a bug or just some dead code.

In case you want to scan Sentry on SonarCloud [you can use a configuration similar to this one](https://github.com/nicolas-harraudeau-sonarsource/sentry/commit/4a253740bfc19b25935efc5b23aff2f6a3acfc7f) when you enable automatic analysis. SonarCloud is free for open source projects.

**Comment by joshuarli** [comment]
This was fixed, I didn't do the magical "fixes" comment in the PR that addresses this.
