### ISSUE TITLE
Duplicate "elif" branch in "OrganizationMonitorsEndpoint.get"

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [getsentry/sentry#21161]
Hello,

While analyzing Sentry on SonarCloud I saw what looks like an error in [`src/sentry/api/endpoints/organization_monitors.py`](https://github.com/getsentry/sentry/blob/e0ec4376fd50247fc21e2046d4b81c7fcc7dc095/src/sentry/api/endpoints/organization_monitors.py#L74):

<img width="1901" alt="Screenshot 2020-10-06 at 10 05 59" src="https://user-images.githubusercontent.com/40498978/95175374-af85ea80-07bb-11eb-903f-9667a1152fbc.png">

You can see [the issue in SonarCloud here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_sentry&issues=AXT5OtAC8YX1Q6Jis_Fd&open=AXT5OtAC8YX1Q6Jis_Fd).

There are two `elif key == "id":` in this `if-elif` block. The second occurence will never execute. If the body of the two `elif` branches were identical I would say that this is just a wrong copy paste with no impact, but they are different so this might be a bug.

In case you want to scan Sentry on SonarCloud [you can use a configuration similar to this one](https://github.com/nicolas-harraudeau-sonarsource/sentry/commit/4a253740bfc19b25935efc5b23aff2f6a3acfc7f) when you enable automatic analysis. SonarCloud is free for open source projects.

**Comment by ChillarAnand** [comment]
@nicolas-harraudeau-sonarsource Good catch. 

Since the first `elif` checks for case-insensitive match, the second `elif` can be removed completely.

**Comment by nicolas-harraudeau-sonarsource** [comment]
Thanks @ChillarAnand.
By the way I don't know if you or another Sentry maintainer noticed but [I wrote a post on the forum](https://forum.sentry.io/t/detecting-bugs-in-sentry-after-a-scan-with-sonarcloud/11330).

I reported only part of the bugs detected by SonarCloud as I wanted to analyze other open source projects too. Sentry is one of the projects we, SonarSource, use to validate our static code analyzers. You can find the link to the full list of bugs in the post.

Hope this helps.

**Comment by joshuarli** [comment]
This was fixed, I didn't do the magical "fixes" comment in the PR that addresses this.
