### ISSUE TITLE
Undefined "lookup_key" listed in "sentry.projectoptions.__all__"

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [getsentry/sentry#21162]
Hello,

While analyzing Sentry on SonarCloud I saw what looks like an bug in [`src/sentry/projectoptions/__init__.py`](https://github.com/getsentry/sentry/blob/e0ec4376fd50247fc21e2046d4b81c7fcc7dc095/src/sentry/projectoptions/__init__.py#L5):

<img width="1826" alt="Screenshot 2020-10-06 at 10 51 54" src="https://user-images.githubusercontent.com/40498978/95180273-08f11800-07c2-11eb-9647-4080ebb4a5b9.png">

You can see [the issue in SonarCloud here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_sentry&issues=AXT5Otr98YX1Q6Jis_VV&open=AXT5Otr98YX1Q6Jis_VV).

This variable is not defined. I tested the following in ipython:
```
In [1]: from sentry.projectoptions import *
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-5cd7974f1c1f> in <module>()
----> 1 from sentry.projectoptions import *

AttributeError: 'module' object has no attribute 'lookup_key'
```
In case you want to scan Sentry on SonarCloud [you can use a configuration similar to this one](https://github.com/nicolas-harraudeau-sonarsource/sentry/commit/4a253740bfc19b25935efc5b23aff2f6a3acfc7f) when you enable automatic analysis. SonarCloud is free for open source projects.

**Comment by joshuarli** [comment]
This was fixed, I didn't do the magical "fixes" comment in the PR that addresses this.
