### ISSUE TITLE
Add higher precision to timestamps in UI

### ISSUE THREAD

**Issue by phemmer** [getsentry/sentry#2118]
Currently the web interface for sentry only shows a timestamp precision down to the minute. On busy systems, a lot can happen in a minute, and so if you need to look in logs to see what was going on around the time of the event, it can be difficult.
To help with this, it would be nice if the timestamp precision were at least down to the second.
It would be even better if it were precise down to the millisecond, but it seems the raven logger truncates the timestamp to the second, at least for golang (maybe this should be addressed as well). Perhaps the web UI can show second precision, and then you can mouseover the timestamp to show the raw value in the JSON payload.

**Comment by mitsuhiko** [comment]
I added a second issue for the protocol: #2119

**Comment by dcramer** [comment]
I've noted timestamp microsecond precision in new spec. Closing this out as its not currently actionable.

**Comment by phemmer** [comment]
Why is this not actionable?
The current timestamp precision is at the minute. The JSON payload is at the second. The data is there.

**Comment by dcramer** [comment]
@phemmer we're not intended to change the current implementation of Sentry as microseconds provide minimal value when we are already sampling/normalizing data. We're working on a new data spec and we'll support it as part of that.

(Additionally many Sentry installs can't even support microsecond precision today due to their backend data store)

**Comment by phemmer** [comment]
I'm not not that interested in microsecond precision. I'm talking about the second.

**Comment by dcramer** [comment]
@phemmer I might be confused as to where we're not correctly supporting seconds. Do you simply mean in the UI?

**Comment by phemmer** [comment]
Yes, things like this:
![image](https://cloud.githubusercontent.com/assets/1826947/10377326/9d1a308e-6dd0-11e5-9daf-41876e170379.png)

**Comment by dcramer** [comment]
@phemmer sorry about that. We'll get the UI addressed :)
