### ISSUE TITLE
ValueError: Unpaired low surrogate: line 1 column 12912 (char 12912)

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2121]
https://app.getsentry.com/sentry/sentry/group/86598932/

```
ValueError: Unpaired low surrogate: line 1 column 12912 (char 12912)
(4 additional frame(s) were not displayed)
...
  File "sentry/nodestore/riak/backend.py", line 62, in get_multi
    return {id: self.get(id)}
  File "sentry/nodestore/riak/backend.py", line 55, in get
    return json.loads(rv.data)
  File "json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
```

**Comment by mattrobenolt** [comment]
Not entirely sure what the issue here is, but apparently we're JSON encoding data into Riak.. but then can't JSON decode it coming back out?

The internet says to use `simplejson`, but I'll need to put together a test case and reproduce what's going on here. Sounds like something to do with UTF-16.

**Comment by pvanderlinden** [comment]
To give some context, this is a request with a file upload, which means it will contain some binary data.
