### ISSUE TITLE
Sentry does not distinguish between (old) Edge and the new Microsoft Edge (based on Chromium)

### ISSUE THREAD

**Issue by alexbjorlig** [getsentry/sentry#21247]
- [x] `@sentry/browser`

### Version:

```
5.25.0
```

## Description

When reporting an error, Sentry does not show if the browser was the old or new Edge. The icon is therefore wrong, when reporting an error from the new Edge.

I tried to lookup what the latest version of the old Edge browser is, but I'm not sure. Maybe it's `18.x` - but I'm not sure:

![Screenshot 2020-10-09 at 12 10 07](https://user-images.githubusercontent.com/9967422/95571228-625a8080-0a28-11eb-9cdf-74083a1ba7dd.png)

I.e. this logo is wrong:
![Screenshot 2020-10-09 at 12 11 19](https://user-images.githubusercontent.com/9967422/95571397-a8afdf80-0a28-11eb-9536-efd29b71059d.png)

Should be the new logo:
![download](https://user-images.githubusercontent.com/9967422/95571414-b5343800-0a28-11eb-909f-7fa485b853f6.jpg)

**Comment by markstory** [comment]
We don't generally keep different logos for browsers as they update their branding. We could update the edge logo to be the current one though.

**Comment by BYK** [comment]
@priscilawebdev @getsentry/app-frontend can you triage please?

**Comment by priscilawebdev** [comment]
I will add this improvement to our UI Backlog and I can probably work on it next week 😉

**Comment by priscilawebdev** [comment]
@alexbjorlig After some research, I also concluded that the latest version of the edge legacy is `18.x` .  We updated our code to display the correct Internet Explorer Edge logo. Done in this PR : https://github.com/getsentry/sentry/pull/24663
