### ISSUE TITLE
Slack Integration: Can't set up alert for private channels

### ISSUE THREAD

**Issue by peterjgrainger** [getsentry/sentry#21245]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

Enabled the integration and set up an alert to send to a private channel on slack

![image](https://user-images.githubusercontent.com/1332395/95546813-7470fa80-09f9-11eb-8026-b5406bf2a793.png)

## Steps to Reproduce

1. Create a private channel
2. Set up alert to post to that slack channel
3. Press Save

Good items to include here include:

### What you expected to happen

Be able to send slack notifications to private channels

### Possible Solution

?

**Comment by manuzope** [comment]
Hey @peterjgrainger, from https://docs.sentry.io/product/integrations/slack/:
> To enable Slack notification for private channels, add the Slack app to the channel. One quick method: use @sentry to invite the Sentry bot the Slack channel.

Does that work for you?

**Comment by peterjgrainger** [comment]
Yep, that was it! Thanks, is it in the docs? If the docs are open I don't mind updating if it isn't already in there
