### ISSUE TITLE
Link Clubhouse Issue - Story autocomplete is broken

### ISSUE THREAD

**Issue by holyoaks** [getsentry/sentry#21260]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

I tried to link a story from Clubhouse to my Sentry issue, but the Story autocomplete dropdown didn't display it. Looking at the developer tools, I see the external call return multiple stories, including the one I wanted, but as I typed further characters, the stories returned reduced (as expected), but didn't include my story (not expected). To be specific:

I typed `10` and 5 stories were returned
I then typed `8`, and one story was returned, but that story was `107`!
I then typed `2`, and no stories were returned, even though `1082` was included in the 5 stories returned at first, and is a valid story in my Clubhouse

## Steps to Reproduce

1. Have a linked Clubhouse SAAS instance
2. Have at least 1000 issues?
3. Click the `Link Clubhouse Issue` link
4. Click the Link tab at the top of the modal window
5. Type the story id of the issue you want to link
6. Check the developer tools to see the results of the external call

### What you expected to happen

My issue, in this case, story id 1082, will appear in the drop down

**Comment by holyoaks** [comment]
I can actually get to my issue, just by typing `1`. Then waiting, and the story does appear in the drop down, but I expect the filter to work correctly, as I may have many more stories that begin with `1` than just 5.

**Comment by manuzope** [comment]
Hey @holyoaks, thanks for writing in! This integration is built and maintained by Clubhouse. To get this issue resolved, please open a support ticket with Clubhouse. :)

**Comment by holyoaks** [comment]
Thank you @manuzope  Will do.
