### ISSUE TITLE
Django version upgrade

### ISSUE THREAD

**Issue by ChillarAnand** [getsentry/sentry#21323]
Sentry is using Django<1.12, for which support has ended in April 2020. Are there any plans to upgrade to a supported version of Django soon?

**Comment by markstory** [comment]
There aren't any timelines right now to upgrade Django. We're in the midst of getting off of python2, and only once that is done would we attempt a Django upgrade.

**Comment by BYK** [comment]
What @markstory said :). Also, please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
