### ISSUE TITLE
Investigate feature for importing/exporting JSON configuration

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2132]
Per discussion on HN it'd be extremely handy to be able to have a JSON representation for a project's entire configuration.

This would include at least:
- Settings
- Rules

We could expose this somewhere in the UI as an advanced view and then offer a way to also import via the same via. Similar to how Datadog does chart editing.

**Comment by BYK** [comment]
I think we have this (albeit in a somewhat broken form) with `sentry export` and `sentry import`. Closing due to staleness.
