### ISSUE TITLE
Discover Cards are showing the wrong field in Y-Axis

### ISSUE THREAD

**Issue by ChillarAnand** [getsentry/sentry#21355]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 20.10.0.dev

## Description

Here is a graph of a saved query with P99 Y-Axis.

<img width="978" alt="Screenshot 2020-10-15 at 5 31 11 PM" src="https://user-images.githubusercontent.com/4463796/96143960-47ed3f00-0f21-11eb-8806-75e99284f67e.png">

The same graph is shown in the Discover Cards. Notice that the Y-axis is showing Count instead of P99.

<img width="317" alt="Screenshot 2020-10-15 at 5 32 13 PM" src="https://user-images.githubusercontent.com/4463796/96144057-5f2c2c80-0f21-11eb-9d4b-cad9e3421f3d.png">

## Steps to Reproduce

1. Create any query with P99 on Y-axis.
2. Go back to discover and see the card.

### What you expected to happen

Show the correct Y-axis in the card.

### Possible Solution

I think currently, counts are shown for all the cards irrespective of what axis is saved in the query. I think the graph on the card should consider the correct axis when rendering the graph.

**Comment by markstory** [comment]
Are you sure it is showing a count? Locally and on sentry.io I'm seeing the same chart shape in the card and full result. However, the axis formatting isn't correct. For example the 6k in your screenshot should be 6s.

**Comment by ChillarAnand** [comment]
@markstory You are right. It's just a formatting issue. 

@Zylphrex Thanks for the quick fix.
