### ISSUE TITLE
Support React Native paths when deployed to iOS devices

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2136]
React Native exceptions are triggered from paths that are per-device.

```
/var/mobile/Containers/Bundle/Application/{DEVICE_ID}/HelloWorld.app/main.jsbundle in breakMe at line 1387:7
```

The Sentry server needs to recognize these patterns and group events and paths properly.

**Comment by benvinegar** [comment]
Some other notes:

* The react-native CLI [bundle command](https://facebook.github.io/react-native/docs/running-on-device-ios.html#using-offline-bundle) always generates a file named `main.jsbundle` – I imagine this file name can be changed, but it's not clear to me how
* These bundles have sourceMappingURLs that look like this:

```javascript
//@ sourceMappingURL=/index.ios.map
```

Specifically, the URLs begin at `/` ... index.ios.map is the default filename (for a generated project), but it can be changed by a developer.

**Comment by mattrobenolt** [comment]
What's the path look for Android? Does this work on Windows too? We'd want to cover all of them, obviously.

**Comment by benvinegar** [comment]
> What's the path look for Android? Does this work on Windows too? We'd want to cover all of them, obviously.

That's why the ticket is "when deployed to iOS devices". We'll make another ticket for that when we find out more.

**Comment by benvinegar** [comment]
> Does this work on Windows too?

Not today.

**Comment by mattrobenolt** [comment]
Don't you know that I'm bad at reading by now?

**Comment by benvinegar** [comment]
🍔

**Comment by dcramer** [comment]
@benvinegar do we still need to do anything here

**Comment by benvinegar** [comment]
Nah – we solved this [in the plugin](https://github.com/getsentry/raven-js/pull/397).
