### ISSUE TITLE
[FEATURE] Detailed stacktraces from minified js with sourcemaps 

### ISSUE THREAD

**Issue by michaelBenin** [getsentry/sentry#2137]
Similar: https://rollbar.com/docs/source-maps/

Also conversation here:
https://rollbar.com/blog/post/2013/07/25/debug-production-errors-in-minified-javascript-with-source-maps-and-rollbar

Was this added into sentry? I couldn't find an issue.

**Comment by mattrobenolt** [comment]
Of course we do. :smile: We've had source map support now for a few years.

https://docs.getsentry.com/hosted/clients/javascript/sourcemaps/
