### ISSUE TITLE
Release Sentry 8.0 to PyPI

### ISSUE THREAD

**Issue by noirbizarre** [getsentry/sentry#2139]
Hi !

I've seen the blog post about Sentry 8.0 and I really want to test it and provide some feedback if need.
Right now it has not been released yet on PyPI. Do you plan to release it soon ?

**Comment by mitsuhiko** [comment]
There is an open milestone for the 8.0 release: https://github.com/getsentry/sentry/issues?q=is%3Aopen+is%3Aissue+milestone%3A%228.0+Release%22

But you can already install from master to get the work in progress version that is on getsentry.com

**Comment by noirbizarre** [comment]
Thanks ! for the quick response !
