### ISSUE TITLE
False spike reports triggered on free plan

### ISSUE THREAD

**Issue by rtpHarry** [getsentry/sentry#21436]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

Hello, I thought I would just point this out, I understand what is happening and don't need support.

I have this running on an in-development project under the free plan. 

It managed to use up all its quota last month.

Now this month it is running normally again, but im getting spike alerts.

It seems to me that its comparing the zero alerts level of the end of last month against this month and thinking its spiking, not that it was cut off before.

Feel free to close this issue if its not important, I just thought it might be useful to know the experience from somebody on the free tier. I don't know how you view it but I would guess that these would normally be new users that are trying to understand the reliability of the system so it could be important to give alerts that take this into account.

**Comment by BYK** [comment]
@jusigler, any idea whom to route this issue to? Looks like a `getsentry/getsentry` issue.

**Comment by BYK** [comment]
Pinging @getsentry/revenue for triage

**Comment by markstory** [comment]
Spike protection doesn't use the previous month's data. Instead it uses `maximum(20, 6 x average error events per minute over the last 24 hours)` [docs source](https://docs.sentry.io/product/accounts/quotas/#spike-protection). Is your project hitting these kinds of thresholds where there are sizable lulls and then periods of much higher activity?
