### ISSUE TITLE
Customize the T thresold to get an adaptive Apdex

### ISSUE THREAD

**Issue by jokesterfr** [getsentry/sentry#21468]
## Summary

The Performance Apdex thresold (T) can only be set globaly on the administration panel. I would like to be able to customize this value by project and transaction.

## Motivation

Solves presenting clear "Apdex" and "User Misery" values in the performance report, when:
* transactions measure batch processing (which may take more time than an usual HTTP request to complete).
* when the user is a machine it's all different about what's acceptable

**Comment by jokesterfr** [comment]
@BYK Hi! What do you think about this? Is this a feature that makes sense to you or should we close it?

**Comment by MurzNN** [comment]
This feature is very necessary! For example, for E-commerce site: 

Load time of some product webpage as 300 msec is good.

But for transaction, that submits the new order from cart with many products, 300 msec is too few! This transaction makes a lot of write processes, so Apdex must be about 2000 msec or even more...

So, we need the way to set separate Apdex values for some transaction groups, that differs from default global Apdex value of project, in Sentry web interface!

**Comment by silent1mezzo** [comment]
Hey @jokesterfr and @MurzNN we're currently working on Per Project User Misery. We recently improved how we calculated User Misery and made it sortable in Performance and now we're allowing users to set the threshold on a project by project basis.

**Comment by jokesterfr** [comment]
Thanks a lot! Going to try this out soon.

**Comment by shruthilayaj** [comment]
Users are now be able to customize Apdex and User Misery thresholds per project and per transaction! Link to [docs](https://docs.sentry.io/product/performance/metrics/#custom-thresholds)
