### ISSUE TITLE
In 8.0.0.dev workers die unexpectedly

### ISSUE THREAD

**Issue by primoz** [getsentry/sentry#2149]
After running sentry for few hours it hangs with:

[2015-10-10 12:29:27,152: INFO/MainProcess] Discarding revoked task: sentry.tasks.process_buffer.process_pending[259f85cb-875d-4a49-8b21-1ec1cf4c0106]

After that it can't be restarted as the event happens right again after restart. Clearing rabbitmq solves the problem temporarily. Any suggestions?

**Comment by mitsuhiko** [comment]
How many servers are you using?  Is this running on different servers or just one?

**Comment by primoz** [comment]
One server contains rabbitmq (only one vhost dedicated to sentry), one server contains postgresql and currently one server runs sentry (fronted + workers)

**Comment by mattrobenolt** [comment]
Fix with 53c4ab5dbee76552e43bcaf018ae2a307cb9251b
