### ISSUE TITLE
Sentry On-Prem(Kubernetes) Sentry 20.8.0 S3 Uploading Issue  

### ISSUE THREAD

**Issue by paziljan** [getsentry/sentry#21504]
hello: 

We have deployed Sentry version 20.8.0 on Kubernetes cluster and we are using AWS S3 as file-store. We are not able to upload Avatars as well as uploading source maps to our projects. We have exhausted our troubleshooting options and we are reaching to Sentry community for help. 

**S3 config:** 

`filestore.backend: s3                                                                                                      │
│ filestore.options:                                                                                                         │
│   access_key: <AKAxxxxxxxxxxxxxxx>                                                                                        │
│   secret_key: <xFCYxxxxxxx>                                                                     │
│   bucketName: <our sentry bucket>                                                                                │
│   signature_version: s3v4                                                                                                  │
│   region_name: us-east-1                                                                                                   │
│   default_acl: private`  

**Nginx Ingress Config:**

`kubernetes.io/ingress.class: nginx-public
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT,GET,POST,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"` 

Steps to reproduce the error: 
1. Uploaded the image for Avatar from GUI
2. Used the sentry-cli uploader

**Below is the error log when uploading from GUI:**

`https://sentry.domain.io/settings/account/details/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
10.10.4.9 - - [21/Oct/2020:14:56:13 +0000] "GET /api/0/users/me/ HTTP/1.1" 200 1589 "https://sentry.domain.io/settings/account/details/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
10.10.3.113 - - [21/Oct/2020:14:56:14 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.16+"
10.10.3.113 - - [21/Oct/2020:14:56:17 +0000] "GET /_health/ HTTP/1.1" 200 200 "-" "kube-probe/1.16+"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 134, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/base.py", line 247, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/endpoints/useravatar.py", line 20, in put
    return super(UserAvatarEndpoint, self).put(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/api/bases/avatar.py", line 57, in put
    filename=self.get_avatar_filename(obj),
  File "/usr/local/lib/python2.7/site-packages/sentry/models/avatar.py", line 75, in save_avatar
    photo.putfile(avatar)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 388, in putfile
    blob = FileBlob.from_file(blob_fileobj, logger=logger)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 248, in from_file
    storage.save(blob.path, fileobj)
  File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 54, in save
    return self._save(name, content)
  File "/usr/local/lib/python2.7/site-packages/sentry/filestore/s3.py", line 511, in _save
    obj = self.bucket.Object(encoded_name)
  File "/usr/local/lib/python2.7/site-packages/sentry/filestore/s3.py", line 361, in bucket
    self._bucket = self._get_or_create_bucket(self.bucket_name)
  File "/usr/local/lib/python2.7/site-packages/sentry/filestore/s3.py", line 397, in _get_or_create_bucket
    bucket = self.connection.Bucket(name)
  File "/usr/local/lib/python2.7/site-packages/boto3/resources/factory.py", line 474, in create_resource
    client=self.meta.client)(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/boto3/resources/base.py", line 119, in __init__
    'Required parameter {0} not set'.format(identifier))
ValueError: Required parameter name not set
10.10.4.9 - - [21/Oct/2020:14:56:23 +0000] "PUT /api/0/users/me/avatar/ HTTP/1.1" 500 656 "https://sentry.domain.io/settings/account/details/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36"
14:56:23 [WARNING] django.security.csrf: Forbidden (CSRF cookie not set.): /api/1/store/ (status_code=403 request=<WSGIRequest: POST u'/api/1/store/'>)
10.10.4.9 - - [21/Oct/2020:14:56:23 +0000] "POST /api/1/store/ HTTP/1.1" 403 5178 "-" "sentry.python/0.16.4"
14:56:24 [ERROR] sentry_sdk.errors: Unexpected status code: 403 (body:
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <meta name="robots" content="NONE,NOARCHIVE">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="icon" type="image/png" href="https://sentry.domain.io/_static/1603224804/sentry/images/favicon.png">

  <link rel="apple-touch-icon" href="https://sentry.domain.io/_static/1603224804/sentry/images/logos/apple-touch-icon.png">
  <link rel="apple-touch-icon" sizes="76x76" href="https://sentry.domain.io/_static/1603224804/sentry/images/logos/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="120x120" href="https://sentry.domain.io/_static/1603224804/sentry/images/logos/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="152x152" href="https://sentry.domain.io/_static/1603224804/sentry/images/logos/apple-touch-icon-152x152.png">

  <link rel="mask-icon" sizes="any" href="https://sentry.domain.io/_static/1603224804/sentry/images/logos/logo-sentry.svg" color="#FB4226">

  <link href="/_static/1603224804/sentry/dist/sentry.css" rel="stylesheet"/>

  <title>CSRF Verification Failed | Sentry</title>

  <script>
    window.__initialData = {"languageCode":"en","csrfCookieName":"sc","features":[],"urlPrefix":"https://sentry.domain.io","needsUpgrade":false,"privacyUrl":null,"isOnPremise":true,"gravatarBaseUrl":"https://secure.gravatar.com","dsn":"https://96ce5618792648eabce46a77ddcf9f56@sentry.domain.io/1","version":{"current":"20.8.0","build":"17e488c41c8fd551367fbf353d3916db8a99dfe0","upgradeAvailable":true,"latest":"20.10.1"},"termsUrl":null,"sentryConfig":{"dsn":"https://96ce5618792648eabce46a77ddcf9f56@sentry.domain.io/1","release":"17e488c41c8fd551367fbf353d3916db8a99dfe0","whitelistUrls":[],"environment":"production"},"apmSampling":0.0,"singleOrganization":true,"user":null,"invitesEnabled":true,"dsn_requests":"","lastOrganization":null,"messages":[],"userIdentity":{"ip_address":"10.10.4.97"},"isAuthenticated":false,"statuspage":null,"supportEmail":"support@domain.io","distPrefix":"/_static/1603224804/sentry/dist/"};
  </script>

  <script src="/_static/1603224804/sentry/dist/vendor.js"></script>
  <script src="/_static/1603224804/sentry/dist/app.js" data-entry="true"></script>

  <script>
    // if the ads.js file loads below it will mark this variable as false
    window.adblockSuspected = true;
  </script>
  <script src="/_static/1603224804/sentry/js/ads.js"></script>

</head>

<body class=" narrow">

  <div class="app">

<div id="blk_alerts" class="messages-container"></div>
<script>
$(function(){
  ReactDOM.render(React.createFactory(SentryApp.SystemAlerts)({
     className: "alert-list"
  }), document.getElementById('blk_alerts'));
});
</script>
<div id="blk_indicators"></div>
<script>
$(function(){
  ReactDOM.render(React.createFactory(SentryApp.Indicators)({
     className: "indicators-container"
  }), document.getElementById('blk_indicators'));
});
</script>

    <div class="container">
      <div class="content">

<div class="pattern-bg"></div>
<section class="org-login">
  <div class="box box-modal">
    <div class="box-header">

        <a class="logo-with-action" href="/">

            <span class="icon-sentry-logo-full"></span>

        </a>

    </div>
    <div class="box-content with-padding">

    <section class="body">
        <div class="page-header">
            <h2>CSRF Verification Failed</h2>
        </div>

        <p>A required security token was not found or was invalid.</p>

        <p>If you're continually seeing this issue, try the following:</p>

        <ol>
          <li>Clear cookies (at least for Sentry's domain).</li>
          <li>Reload the page you're trying to submit (don't re-submit data).</li>
          <li>Re-enter the information, and submit the form again.</li>
        </ol>

        <p>Read more about <a href="http://en.wikipedia.org/wiki/Cross-site_request_forgery">CSRF on Wikipedia</a>.</p>
    </section>

    </div>
  </div>
</section>

      </div>
    </div>
    <footer>
      <div class="container">

        <div class="pull-right">
          <a href="https://docs.sentry.io/api/">API</a>
          <a href="https://docs.sentry.io">Docs</a>
          <a href="https://github.com/getsentry/sentry" rel="noreferrer">Contribute</a>
          <a href="/out/">Migrate to SaaS</a>
        </div>
        <div class="version pull-left">Sentry 20.8.0 (17e488c41c8fd551367fbf353d3916db8a99dfe0) <a href="#" title="You're running an old version of Sentry, did you know 20.10.1 is available?" class="tip icon-circle-arrow-up">&nbsp;</a></div>
        <a href="/" class="icon-sentry-logo"></a>

      </div>
    </footer>
  </div>
</body>
</html>`

**Sentry-cli Uploader error message:** 

`sentry git:(master) ✗ sentry-cli upload-dif -o myorganization -p pythonScript ./nice.py --log-level debug
  INFO    2020-10-20 14:47:19.842055 -04:00 Loaded config from /Users/support/.sentryclirc
  DEBUG   2020-10-20 14:47:19.842819 -04:00 sentry-cli version: 1.58.0, platform: "darwin", architecture: "x86_64"
  INFO    2020-10-20 14:47:19.842838 -04:00 sentry-cli was invoked with the following command line: "sentry-cli" "upload-dif" "-o" "myorganization" "-p" "pythonScript" "./nice.py" "--log-level" "debug"
  INFO    2020-10-20 14:47:19.843624 -04:00 Issuing a command for Organization: myorganization Project: pythonScript
  DEBUG   2020-10-20 14:47:19.844737 -04:00 request GET https://sentry.io/api/0/organizations/myorganization/chunk-upload/
  DEBUG   2020-10-20 14:47:19.845006 -04:00 using token authentication
  DEBUG   2020-10-20 14:47:19.845025 -04:00 retry number 0, max retries: 0
  DEBUG   2020-10-20 14:47:21.047170 -04:00 > GET /api/0/organizations/myorganization/chunk-upload/ HTTP/1.1
  DEBUG   2020-10-20 14:47:21.047202 -04:00 > Host: sentry.io
  DEBUG   2020-10-20 14:47:21.047210 -04:00 > Accept: */*
  DEBUG   2020-10-20 14:47:21.047217 -04:00 > Connection: TE
  DEBUG   2020-10-20 14:47:21.047223 -04:00 > TE: gzip
  DEBUG   2020-10-20 14:47:21.047230 -04:00 > User-Agent: sentry-cli/1.58.0
  DEBUG   2020-10-20 14:47:21.047717 -04:00 > Authorization: Bearer 8424f9a8***
  DEBUG   2020-10-20 14:47:21.307747 -04:00 < HTTP/1.1 401 Unauthorized
  DEBUG   2020-10-20 14:47:21.307784 -04:00 < Server: nginx
  DEBUG   2020-10-20 14:47:21.307797 -04:00 < Date: Tue, 20 Oct 2020 18:47:21 GMT
  DEBUG   2020-10-20 14:47:21.307846 -04:00 < Content-Type: application/json
  DEBUG   2020-10-20 14:47:21.307883 -04:00 < Content-Length: 26
  DEBUG   2020-10-20 14:47:21.307896 -04:00 < Connection: keep-alive
  DEBUG   2020-10-20 14:47:21.307913 -04:00 < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
  DEBUG   2020-10-20 14:47:21.307926 -04:00 < X-Content-Type-Options: nosniff
  DEBUG   2020-10-20 14:47:21.307937 -04:00 < Content-Language: en
  DEBUG   2020-10-20 14:47:21.307948 -04:00 < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
  DEBUG   2020-10-20 14:47:21.307958 -04:00 < Vary: Accept-Language, Cookie
  DEBUG   2020-10-20 14:47:21.307968 -04:00 < X-XSS-Protection: 1; mode=block
  DEBUG   2020-10-20 14:47:21.307978 -04:00 < Allow: GET, POST, HEAD, OPTIONS
  DEBUG   2020-10-20 14:47:21.307988 -04:00 < X-Frame-Options: deny
  DEBUG   2020-10-20 14:47:21.307998 -04:00 < Access-Control-Allow-Origin: *
  DEBUG   2020-10-20 14:47:21.308008 -04:00 < Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS
  DEBUG   2020-10-20 14:47:21.308022 -04:00 < WWW-Authenticate: xBasic realm="api"
  DEBUG   2020-10-20 14:47:21.308035 -04:00 < X-Served-By: web-0df6213e
  DEBUG   2020-10-20 14:47:21.308045 -04:00 < Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  DEBUG   2020-10-20 14:47:21.308094 -04:00 response status: 401
  DEBUG   2020-10-20 14:47:21.308108 -04:00 body: {"detail":"Invalid token"}`

We always get the _**invalid token**_ error even though we created a valid token. 

**Content of our .sentryclirc**

`defaults.url=https://sentry.domain.io
defaults.org=myorganization
defaults.project=pythonScript
[auth]
token=88fhfhdxxxhxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`

**Comment by BYK** [comment]
I think your config should be `bucket_name` not `bucketName`: https://develop.sentry.dev/services/filestore/#amazon-s3-backend
