### ISSUE TITLE
installation instructions not working

### ISSUE THREAD

**Issue by jonchoi** [getsentry/sentry#21509]
## Important Details

How are you running Sentry?

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/9872658/96769903-a0df2c00-1394-11eb-96df-8bf992410430.png">

On-Premise w/ Docker, version x.y.z

Saas (sentry.io)

Other, version x.y.z, [briefly describe your environment]

## Description

[What happened]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. and so on.

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant

### What you expected to happen

[What you think should be happening]

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by BYK** [comment]
Please use the template properly and provide the information for us to help you. Also, please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
