### ISSUE TITLE
Width issue on mobile

### ISSUE THREAD

**Issue by kozickikarol** [getsentry/sentry#2150]
Border below the tabs is too wide. It causes that entire page is too wide. I'm attaching screenshot.
![screenshot_2015-10-10-15-11-35](https://cloud.githubusercontent.com/assets/8099900/10411348/00887be8-6f62-11e5-82ac-c089a5869ee3.png)

**Comment by mattrobenolt** [comment]
@ckj Mind looking into this plz?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
