### ISSUE TITLE
Statics giving 404

### ISSUE THREAD

**Issue by explem32** [getsentry/sentry#2151]
On /src/sentry/web/frontend/generic.py line 25:
```python
path = '%s/%s' % (module, path)
```
changed with
```python
path = 'sentry/%s/%s' % (module, path)
```

problem solved.

Thanks for your excellent software :)

**Comment by dcramer** [comment]
We fixed this in 0edaa6bffca66f1a758817cd03145546a562e8b9

(You caught us at a bad time :)
