### ISSUE TITLE
Redirect a 404 on event detail page back to stream?

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2152]
> I reloaded a browser tab that was pointing to the activity page of an event that was merged with another event, and I got this infinite loading spinner, along with a 404 error

Not entirely sure if this is the best thing to do, but if we 404 on loading the event id, we just get a spinner forever. I think we should either show a "404" type message, or redirect back to stream.

Thoughts?

Re: https://sentry.zendesk.com/agent/tickets/680

For this user, this happened after an event was merged, so we nuked the original group, which causes all existing links to 404.

This is also related to #2104, but this is a much simpler solution in the meantime.

**Comment by dcramer** [comment]
Falls in line with how we handle errors too. We need some generic way to render the appropriate components

**Comment by mattrobenolt** [comment]
Yeah, I dunno if you wanna group this with an overarching, "handle router failures" or something, but that's fine with me. Just documenting this specific issue since it was brought up.

**Comment by benvinegar** [comment]
We've since added an error handling view for this scenario:

![image](https://user-images.githubusercontent.com/2153/46265542-5c964000-c4dc-11e8-9014-c0c458f6c2fd.png)
