### ISSUE TITLE
Add "Resolved in Release" Feature

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2155]
This would add a new way to resolve events, effectively saying "Ive committed a fix, but its not live yet". We need to think about how this plays with current resolution, but it can't replace it.

Here's the thoughts I have:

- Resolving in a release would effectively mark it as fixed and would only regress if its seen in a release that is newer (the Release.date_created value is greater than Group.resolved_at).
- This would not be 'muted', it would be 'resolved', which means rate-based rules are still in effect
- When we integrate with VCS this would be the same behavior that some kind of 'Fixes X' provides.
- "which version was it fixed it" would be an optional attribute, that likely wouldn't be used today
- Activity feed would show version fixed in when possible

Concerns:

- The UI needs quick access to this and it needs to not be confusing. Obviously creating a new status makes this easier, but it overcomplicates other things so our goal is to still treat it as Resolved. It could be we end up with two buttons, a checkmark, and a checkmark that has some secondary marker making it look like its fixed in code.
- It can't replace normal resolve as there are still cases where you simply want to clear things off screen (i.e. a db operational error), but those have nothing to do with committing fixes
- Where do we track state to know what kind of resolution we have? Adding another GroupStatus is non trivial and should be avoided if possible (since this is still resolved). We also should consider future uses like "mute this for X hours".
- Phased deploys can cause serious issues here. For example I see the issue in A (which is on prod), fix it in B (and thus mark it as fixed), and a little while later push push A2 to staging. The event happens now in A2, which is a new commit, but doesnt contain B yet. This is only solvable if we have VCS awareness on both sides of the problem.

**Comment by dcramer** [comment]
```
class GroupState
    # state could be muted, resolved, etc
    state = ...
    # when state change took affect
    timestamp = ...
    # when the state change has a relevant version?
    version = ...
    # if we can figure out a generic "expires" we could
    # easily do "mute for 2 hours"
    expires = ...
    # when the state expires, prev_state is restored
    prev_state = ...
```

**Comment by dcramer** [comment]
Starting to consider actually just adding another GroupStatus. It's pretty awful, but after prototyping some of this it would make it a lot easier.

"resolved_at" is still a bit odd so unless that become "last_status_change" we wouldn't be able to support muted.

If we add this to GroupStatus we need to determine what this is actually called. Some options:

- resolvedInCode
- resolutionPending (makes sense, but not directly clear why its pending)
- resolvedInRelease (odd since we cant tell you what release)

I think down the road we'd have to expand things either way to support the flow of "I've fixed this in SHA, SHA isn't on ENV yet (isn't part of RELEASE), so dont unresolve it when its seen again". That's gotta be a different flow since we won't know SHA right now.

**Comment by tkaemming** [comment]
I am not sure it makes sense to call this "resolved" until it is *actually* resolved. This really seems more like an acknowledgement state that causes another state change (to resolved) on the next release.

Implementation-wise, in addition to phased deploys, how does this work with rolling deploys? Is totally this reliant on the release tag being present in the event payload? Does this mean this feature is only enabled for projects that have releases?

**Comment by dcramer** [comment]
@tkaemming thats a good point regarding "it should be resolved when this is pushed"

It would only function on projects with release data.

**Comment by dcramer** [comment]
Was considering just having something like a ``GroupCommitReference`` entity. We'll need this anyways, so it probably makes sense. From there we can extrapolate what's going on either via some new status "Fix Committed" or "Pending Resolution" (or something that makes sense). It's also sane enough to check that in the pipeline.
