### ISSUE TITLE
Support "ignored fields" for Jira organization integration like legacy Jira project plugin does

### ISSUE THREAD

**Issue by saifelse** [getsentry/sentry#21585]
## Summary
Allow an admin to configure the Jira Integration to hide Jira fields in the
issue creation modal, specified by name on the settings page.

## Motivation
The motivation is the same as to why the Jira plugin already supports this
feature: from a bug triage perspective, having all fields of an issue type
present in the modal can be overwhelming noise, esp. since many of those fields
may be intended to be filled out after the issue is in JIRA (e.g. a tech plan
field).

## Additional Context

Existing "legacy integration" feature 🙌 : 
![image](https://user-images.githubusercontent.com/549473/97115019-5c63d100-16b1-11eb-9582-1183665bb79c.png)

Missing from "organization integration" 😭 :
![image](https://user-images.githubusercontent.com/549473/97115045-81584400-16b1-11eb-8c7e-efaeb34df892.png)

Here is an example from my organization's production Sentry that shows the
creation modal being a bad time for developers (note the scrollbar):
![image](https://user-images.githubusercontent.com/549473/97115166-6cc87b80-16b2-11eb-8150-3b418ca01560.png)

The ideal input format is not obvious to me:

- AFAIK, a "comma-separated list" is only found in the legacy plugins,
  so not sure if this was a concerted effort to avoid these.
- Fingerprinting / grouping UIs have a single-line line per rule that allows
  comments, which is fairly nice (esp. since it would be nice to annotate what
  field name what "customfield_10020" refers to).
- A multi-select that actually hits the Jira API to query all fields would be
  interesting, but from a brief investigation `{"type": "select", "multi": True}`
  didn't work so well, and is complicated by the fact that it'd probably
  need to query all fields across all issue types... which could be large /
  unpleasant to navigate unless there was a better way of exploring all the
  fields... which sounds like more work than its worth.

Personally, I've been okay with the legacy integration's approach... it's an
infrequently tweaked list. I've worked around the issue of no comments by
including non-sense values interspliced, e.g.:
```
customfield_100020,<-- this_is_story_points_field,customfield_100021,<-- tech plan field
```
but first-class support for comments would be nice, e.g.:
```
# story points field
customfield_100020

# tech plan field
customfield_100021
```

**Comment by saifelse** [comment]
cc @macqueen . I see you left the original TODO 😇 :
https://github.com/getsentry/sentry/blob/8ee8669c3a4aebe8ed154470a4a5fd9dd963c814/src/sentry/integrations/jira/integration.py#L202-L203

**Comment by scefali** [comment]
Thanks for making this issue and the PR! Greatly appreciated :D
