### ISSUE TITLE
Slack Integration: 

### ISSUE THREAD

**Issue by Isakgicu** [getsentry/sentry#21614]
Hi,

On a fresh installed sentry on-premises, having troubles with slack integration.
Check attached screen.
Any help would be appreciated. Thank You!
![image](https://user-images.githubusercontent.com/35724103/97337697-47419a80-1889-11eb-9901-99a45a5dc0c1.png)

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.

Also please follow our guidance before reporting issues: https://develop.sentry.dev/integrations/slack/

Looks like you forgot some configuration variables.
