### ISSUE TITLE
Assigned filter doesn't seem to be working.

### ISSUE THREAD

**Issue by kitsunde** [getsentry/sentry#2162]
I assigned a couple of events to someone, then I clicked the assigned filter, but it doesn't appear to work.

<img width="1314" alt="screenshot 2015-10-13 00 06 55" src="https://cloud.githubusercontent.com/assets/48965/10441217/4b70e20c-713e-11e5-96a0-0c8b7c9d5285.png">
<img width="1347" alt="screenshot 2015-10-13 00 07 02" src="https://cloud.githubusercontent.com/assets/48965/10441214/4b05ab72-713e-11e5-913d-bb599ea34009.png">

Project: https://app.getsentry.com/media-pop-1/jaguar/
Example assigned: https://app.getsentry.com/media-pop-1/jaguar/group/87587397/

**Comment by dcramer** [comment]
This is a bit confusing but assigned means "Assigned to Me".

We talked about this pre-release but decided for now to not overhaul it. That said I think there's still work to be done here.
