### ISSUE TITLE
EnhancerByGuice proxies are not filtered out in stack trace

### ISSUE THREAD

**Issue by svetlana-nikitina** [getsentry/sentry#21645]
Hi, we are running sentry java sdk on play framework ver. 2.6.5 with Java 1.8

```
      <dependency>
            <groupId>io.sentry</groupId>
            <artifactId>sentry</artifactId>
            <version>3.1.1</version>
        </dependency>
```

and experience an issue that the guice-enhanced proxies are apparently the part of the stack trace fingerprint calculation, so we have a lot of detached events: 
![image](https://user-images.githubusercontent.com/42933021/97479270-56d8e600-1952-11eb-9180-682fc42b522e.png)

is there a way to exclude them so our events are merged out of the box?

**Comment by bruno-garcia** [comment]
As a work around until we find the final solution, I suggest adding an EventProcessor that will go through each stacktrace frame and if the `function` contains `$EnhancerByGuide$` you mark the frame `setInApp(false)`.

Only `inApp=true` events are considered when grouping.

We'll add some server-side rule for this on our end though.

**Comment by svetlana-nikitina** [comment]
i've played with project configuration a bit and added from UI in `Custom Grouping Enhancements` section this rule:
```
stack.module:*EnhancerByGuice* -group
stack.module:*EnhancerByGuice* -app
```
i don't have enough traffic atm to prove it, but I hope that it help

**Comment by bruno-garcia** [comment]
I believe @adinauer did some improvements in this area?

**Comment by adinauer** [comment]
Yes, we made some improvements via https://github.com/getsentry/sentry/pull/45185

**Comment by svetlana-nikitina** [comment]
seems to work! thanks!

**Comment by svetlana-nikitina** [comment]
Works
