### ISSUE TITLE
Microsoft Teams Integration: Unable to get "complete setup" welcome message after reinstall Sentry

### ISSUE THREAD

**Issue by angelfcm** [getsentry/sentry#21661]
After I uninstalled Sentry from MS Teams and tried to install it again through Teams Marketplace, I don't receive the welcome message of Sentry bot to "complete setup" just receive a message about "Docs", and if I go to my Sentry account and check the MS Teams integration it keeps showing as "not installed" so it request to me install Sentry from Teams Marketplace...

<img width="974" alt="Captura de Pantalla 2020-10-28 a la(s) 21 04 34" src="https://user-images.githubusercontent.com/1879366/97520728-7d524d80-1961-11eb-810e-2439e89791d3.png">
<img width="888" alt="Captura de Pantalla 2020-10-28 a la(s) 21 04 59" src="https://user-images.githubusercontent.com/1879366/97520727-7cb9b700-1961-11eb-851f-82250834bb07.png">
<img width="976" alt="Captura de Pantalla 2020-10-28 a la(s) 21 06 09" src="https://user-images.githubusercontent.com/1879366/97520726-7c212080-1961-11eb-8293-739d1bdb34cc.png">
<img width="1021" alt="Captura de Pantalla 2020-10-28 a la(s) 21 06 20" src="https://user-images.githubusercontent.com/1879366/97520721-7a575d00-1961-11eb-837a-968c35ca6fa0.png">
<img width="987" alt="Captura de Pantalla 2020-10-28 a la(s) 21 09 06" src="https://user-images.githubusercontent.com/1879366/97520861-d3bf8c00-1961-11eb-8b2a-9677f315de24.png">

**Comment by scefali** [comment]
@angelfcm Hi Angel, this is a common problem we see. The root cause is likely not uninstalled from Microsoft Teams (uninstalling the integration in Sentry is not enough). You need to go to `Mange Team`, then `Apps`, and remove the Sentry app from as shown below:

![Screen Shot 2020-10-29 at 11 19 28 AM](https://user-images.githubusercontent.com/8533851/97615726-ec1ebd80-19d8-11eb-82b5-8aafc39ec0a8.png)

**Comment by angelfcm** [comment]
> @angelfcm Hi Angel, this is a common problem we see. The root cause is likely not uninstalled from Microsoft Teams (uninstalling the integration in Sentry is not enough). You need to go to `Mange Team`, then `Apps`, and remove the Sentry app from as shown below:
> 
> ![Screen Shot 2020-10-29 at 11 19 28 AM](https://user-images.githubusercontent.com/8533851/97615726-ec1ebd80-19d8-11eb-82b5-8aafc39ec0a8.png)

You are right, it works for me, thank you so much!!!
