### ISSUE TITLE
GitHub Integration: 

### ISSUE THREAD

**Issue by MurrayJack** [getsentry/sentry#21662]
Hi

we have run through the process for adding  githib integration but no matter what we do it is always showing as  Not Installed, and nothing seems to happen

Help!

**Comment by manuzope** [comment]
Hey @MurrayJack, are you using OnPrem or Saas?

**Comment by MurrayJack** [comment]
We are using the sass version

**Comment by manuzope** [comment]
Gotcha, mind opening a support ticket? We will be able to best assist you that way: https://sentry.io/support.

**Comment by MurrayJack** [comment]
Will do thanks 😁
