### ISSUE TITLE
Explore whether we need to include all of react-bootstrap in vendor.js

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2171]
Pointed out by @taion on [an unrelated PR](https://github.com/rackt/react-router/pull/2262) (and project):

> On a complete tangent, because I don't know the meaning of the word off-topic, I noticed that you guys were pulling in all of React-Bootstrap (and other libraries) for your vendor bundle. Is there a benefit to doing things that way? Seems like you end up with a lot of stuff in your vendor bundle that you couldn't possibly be using.

Basically, we only use Modal and Tooltip from react-bootstrap, but it seems we're pulling in _all_ js for every conceivable component. We should investigate further.

**Comment by taion** [comment]
Interesting - if that's your use case, you might be interested in https://github.com/react-bootstrap/react-overlays, then, which just pulls out the core stuff behind the R-B `Tooltip` and `Modal` components and doesn't have all the Bootstrap stuff.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
