### ISSUE TITLE
POST /sentry-apps/ returning 500 error

### ISSUE THREAD

**Issue by jverce** [getsentry/sentry#21721]
## Important Details

How are you running Sentry?

* On-Premise w/ Docker, version 20.10.1
* Saas (sentry.io)
* Other, version 20.10.1:
  * Dev environment as described here: https://develop.sentry.dev/environment/

## Description

When issuing a `POST` request to `/sentry-apps/` to create an internal integration, I get a `500 Internal Server Error` response.

More details here:
https://forum.sentry.io/t/post-sentry-apps-is-responding-with-a-500-status/11659

## Steps to Reproduce

1. Issue the following request to https://sentry.io/api/0/sentry-apps/:
  * Method: `POST`
  * Payload:
```json
{
    "scopes": [
        "project:read",
        "team:read",
        "event:read",
        "org:read",
        "member:read"
    ],
    "isAlertable": true,
    "name": "test123",
    "webhookUrl": "https://ad33a9a4ac54.ngrok.io",
    "events": [
        "issue"
    ]
}
```
2. Receive a `500 Internal Server Error` response, with a payload similar to this one:
```json
{
    "detail": "Internal Error",
    "errorId": "0624bff51cf644c3b23fca61bbd89849"
}
```

### What you expected to happen

The expected behaviour should be to get a `201 Created` response, together with the data corresponding to the newly created Sentry app.

### Possible Solution

The problem arises when the `organization` field is not provided as part of the payload. In such case, the request is interpreted and validated as `GET /sentry-apps/`, but forwarded to the `POST /sentry-apps/` handler.

Additional and proper validation needs to be added to the `/sentry-apps/` endpoint so that appropiate HTTP error codes (and messages) are returned to users.

**Comment by scefali** [comment]
@jverce I saw this error pop up last week, I see that you were the user behind it: https://sentry.io/share/issue/47562bb32e79496f9d508ed100f27ebf/

I think this is the first time I've seen someone use this API without using the UI. Really curious about what you're doing here!

**Comment by jverce** [comment]
Hi there @scefali!

I'm currently working on what's called an "event source" in a new platform called [Pipedream](https://pipedream.com/). An "event source" is basically an HTTP endpoint that is called by a 3rd party webhook (in this case, the webhook would be on the Sentry side), and produces custom events that can then be forwarded to different systems in order to create a wide variety of custom integrations.

The use case would be very simple:
1. When users create this "event source", the platform would create a webhook on Sentry, with the webhook URL pointing to the event source's URL
2. The event source would then receive events from Sentry, do some basic processing and push them downstream to whatever user's define (e.g. Slack, e-mail, some custom API, etc)
3. When the user decides that the event source is no longer needed, the platform would go ahead and delete the webhook in Sentry

In order to accomplish this, we need to manipulate those Sentry webhooks through the REST API rather than the UI.

**Comment by jverce** [comment]
BTW I created a PR to handle this more gracefully:
https://github.com/getsentry/sentry/pull/21720
