### ISSUE TITLE
Sentry issue detail pages consume a steady % of CPU 

### ISSUE THREAD

**Issue by timruffles** [getsentry/sentry#21728]
## Important Details

On-Premise w/ Docker, version 9.0.0

## Description

Using Sentry UI

## Steps to Reproduce

1. Visit an issue page
2. Open devtools (or browser/OS task manager)
3. Check CPU usage

### What you expected to happen

A static page uses no CPU.

### Possible Solution

- Use CSS animations. 
- Ensure invisible elements don't cost CPU time 

![sentry detail CPU usage](https://user-images.githubusercontent.com/249800/97896013-6d08ec80-1d2c-11eb-8e58-18a4c0d13182.gif)

This is the location of the invisible `class=guide-anchor-ping` element containing the element which is changing and costing CPU time:

```html
<h6 class="nav-header">
   <div type="text" class="css-1mnt2ni e130o4350">
      <div class="guide-anchor-ping issue_number css-jchl67 e130o4351">
         <div class="css-ydrun9 e130o4352"></div>
      </div>
   </div>
   <a class="tip help-link" href="https://docs.sentry.io/learn/releases/#resolving-issues-via-commits" title="" data-original-title="This identifier is unique across your organization, and can be used to reference an issue in various places, like commit messages.">Issue #</a>
</h6>
```

**Comment by scttcper** [comment]
Hi @timruffles thanks for bringing this up. This particular animation was removed in v10 https://github.com/getsentry/sentry/pull/12685 and the feature was completely removed sometime after that.
