### ISSUE TITLE
Add missing mobile icons

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2173]
apple-touch-icon.png is one, there might be others

**Comment by sgoblin** [comment]
Where would the place to put this be (head template or something similar)?

**Comment by ckj** [comment]
@sgoblin I went ahead and added support for these. Here are the docs I referenced:

iOS:
https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

Android:
https://developer.chrome.com/multidevice/android/installtohomescreen
