### ISSUE TITLE
Spinner.gif not found

### ISSUE THREAD

**Issue by stgleb** [getsentry/sentry#2175]
Hello, i've installed sentry 7.7.1 version. when i'm tried to create new team and select a platfrom i open dropdown list of platforms and get 404 error and page redirect after that.
I've investigated that problem had been occured  due to spinner.gif file that could not be found. I've tried to fix in an "intelligent" way, but that just ad it to static directory of sentry and it works!!!
    Could you please fix that UI issue or tell how avoid such problems in future.

**Comment by dcramer** [comment]
We don't plan to do any more releases in the 7.x series unless they involve critical fixes or security patches and I don't believe this is a problem in 8.0
