### ISSUE TITLE
Test email fails

### ISSUE THREAD

**Issue by stgleb** [getsentry/sentry#2176]
Hello, i'm trying to send a test email from admin dashboard and get following error message:

(534, '5.7.14 <https://accounts.google.com/ContinueSignIn?sarp=1&scc=1&plt=AKgnsbt_g\n5.7.14 AYMQ8i6UuevAKoXrfkxjjq7zLdQGF2TUhLIQhmRqyd1EFmG9Hk2cY5q8kEbWJOMtHosS_V\n5.7.14 Ct8qibtgltmN2qfyNRXNwzmXUS_Am1SGiTnmbapHzKsHZuNYi5dGt6tsjVCJzqoktcleLW\n5.7.14 YdJ2KIGya8qhh9xba5rhNlv6obRdj3inQB_B-jeeMHRKYSkvciOfqIjvOLDrkfTWU1XMfk\n5.7.14 2ysE8RP1DWLZvAtkcLjzEC-cfAz0> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14 Learn more at\n5.7.14 https://support.google.com/mail/answer/78754 ry1sm9442649wjb.24 - gsmtp')

Email settings are following:

From Address 	root@localhost
Host 	smtp.gmail.com:587
Username 	gleb.stepanov@srost-studio.com
Password 	********
TLS? 	Yes

i wonder why rom address is root@localhost beacuse i've changes SERVER_MAIL to my email in sentry.conf.py file.

**Comment by mattrobenolt** [comment]
This may be a dumb question, but did you read https://support.google.com/mail/answer/78754 ?

This sounds like you have 2FA enabled for that email address, which means you can't use your password. You'd have to generate an application token.

But that's purely a guess.

**Comment by dcramer** [comment]
Closing this out as its not actionable
