### ISSUE TITLE
Allow open membership to be specified per team

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2177]
This will allow you to use the feature throughout the organization, yet restrict teams they may have sensitive data. Those teams can still be joined via the standard "Request Access" flow.

**Comment by dcramer** [comment]
It's likely at this point we wont get this done for 8.0's public release due to time constraints.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
