### ISSUE TITLE
Slack Integration: Failed to retrieve token from the upstream service.

### ISSUE THREAD

**Issue by Jackwumingjie** [getsentry/sentry#21810]
after oauth the slack and return the page:
![image](https://user-images.githubusercontent.com/39093109/98218037-3dedb780-1f86-11eb-8f96-8b1530c16d4f.png)

**Comment by manuzope** [comment]
Hi @Jackwumingjie, are you using on prem or are you using our SaaS product?

**Comment by Jackwumingjie** [comment]
Hi @manuzope The sentry that is installed in ourself server, not your SaaS product.

**Comment by manuzope** [comment]
@Jackwumingjie: in code, here's where you're running into this problem: https://github.com/getsentry/sentry/blob/10afc1230e6c8201675db7f24232dac9c6ac6ae0/src/sentry/identity/oauth2.py#L331

There should be log lines that tell you the error that Sentry is seeing and why it's OAuth is failing. It's hard for me to tell exactly what is going wrong but those log lines should help. 

If it helps, this development documentation should also tell you how to configure Slack for your on-prem instance: https://develop.sentry.dev/integrations/slack/.

Closing this out cause this isn't happening for most other on-prem instances. You can post this in [our forum](https://forum.sentry.io/) for further questions on setting up the slack integration as this issue board is only for the core Sentry code-related issues.
