### ISSUE TITLE
Broken pagination on event stream

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2184]
It seems that for some accounts, pagination doesn't work. I don't have much more info other than I could reproduce on this user's account so far.

> Hello! I seem to be unable to see the next page of results -- when I click the ">" button at the bottom of the page, I am directed to a new URL, but the same notifications are shown. However, my colleagues are able to page to older results just fine. (Also, I seem to only have this issue on Chrome -- works fine on Safari).

Re: https://sentry.zendesk.com/agent/tickets/727

> The pagination on the project feed page is misbehaving, often when you click it loads a page with the same content as the page you were on. This was definitely work last week.

Re: https://sentry.zendesk.com/agent/tickets/736

**Comment by benvinegar** [comment]
Hmm, how'd I miss this ticket.

Well, it appears like pagination is wonky when polling is enabled.

So, "for some users" might simply mean users that have polling enabled.

**Comment by mattrobenolt** [comment]
@benvinegar by "some users", I also reproduced it, without having polling enabled. Lemme see if I can repro again.

**Comment by benvinegar** [comment]
Pretty sure this was addressed by #2326. Can re-open if it re-appears.
