### ISSUE TITLE
Add environment to Pagerduty details

### ISSUE THREAD

**Issue by hkrutzer** [getsentry/sentry#21857]
# Summary

Add environment to Pagerduty details

## Motivation

Adding the environment will allow Pagerduty Event Rules to be created based on the environment, making it possible to e.g. make development environment errors low priority, so that people are not paged during the night for development errors.

## Additional Context

Error from Appsignal, which does have this feature:
![2020-11-07 at 13 23](https://user-images.githubusercontent.com/3464899/98441072-c9895480-20fc-11eb-90e5-a3a16c7aad16.png)

Sentry equivalent:
![2020-11-07 at 13 26](https://user-images.githubusercontent.com/3464899/98441125-e160d880-20fc-11eb-8763-ce1f7e89a051.png)

**Comment by manuzope** [comment]
Hmmm, I see. Are you able to use Sentry's alert rule builder to route events depending on the tag value?

Out of curiosity -- why send non-prod traffic to PagerDuty?

**Comment by hkrutzer** [comment]
>Are you able to use Sentry's alert rule builder to route events depending on the tag value?

Correct. The interface for doing so is quite basic in my opinion. This screenshot might give you an idea:
<img width="1585" alt="image" src="https://user-images.githubusercontent.com/3464899/99830413-f9554500-2b5d-11eb-8df2-17951545e40d.png">

>Out of curiosity -- why send non-prod traffic to PagerDuty?

We have staging environments which are used by customers to test new features; these have an SLA that only requires  issues to be fixed during business hours.

**Comment by manuzope** [comment]
Got it. Does this workflow work for you?
1. Create a support hours only service in PagerDuty where all staging requests can go
1. Use [Sentry alert rules](https://sentry.io/resources/alert-rules/) to route traffic depending on the environment

> (Others might have a different use case for building rules based on data which is currently in the tags array, such as level. 
For them might make sense to move more of the data out of the array than just environment)

Yea, I think you're right here. Tags do make more sense as a key-value pair, rather than in an array. PD's event rules allow you to do a `tags.environment` so we probably just need to do that so that you can use PD's event rules.

**Comment by hkrutzer** [comment]
>Got it. Does this workflow work for you?
>
>    Create a support hours only service in PagerDuty where all staging requests can go
>    Use Sentry alert rules to route traffic depending on the environment

Kind of, it is a workaround. However I think a single service would be the preferable way.

Also, if you want to create a mapping of the `level` field in Sentry to priority/urgency in Pagerduty, that would not be feasible with the current tags.

**Comment by hkrutzer** [comment]
Would still like to see this

**Comment by baelter** [comment]
Adding project name, and custom context fields to the PagerDuty issue would also be useful.
