### ISSUE TITLE
Trello integration doesn't show Create Trello Card button

### ISSUE THREAD

**Issue by ArtemBernatskyy** [getsentry/sentry#21862]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

Trello integration doesn't show `Create Trello Card` button on the errors in project

## Steps to Reproduce

1. Add Trello integration in legacy integrations
2. Set up trello integration [via setup guide](https://github.com/getsentry/sentry/blob/master/src/sentry_plugins/trello/Trello_Instructions.md)
3. Visit sentry error detail page -> there will be no `Create Trello Card` button

**Comment by manuzope** [comment]
Hi @ArtemBernatskyy, mind opening a request with our [support team](https://sentry.io/support)? We'll be able to help you best that way.

I was able to get it to work on my test account so I'm guessing it's a configuration issue.

**Comment by ArtemBernatskyy** [comment]
@manuzope it was fixed somehow, thx!
closing issue
