### ISSUE TITLE
Create comment when linking to existing Jira issue

### ISSUE THREAD

**Issue by earshinov** [getsentry/sentry#21865]
## Summary

It would be nice if when linking to an existing Jira issue Sentry created a comment with a link back to the Sentry issue.

## Motivation

- Sentry already creates a backlink when creating a _new_ Jira issue
- Being able to navigate from Jira issue to the original Sentry issue is just as important and useful as navigating from Sentry to Jira.

## Additional Context

When creating a new Jira issue, there is a backlink:

![image](https://user-images.githubusercontent.com/52021/98541556-ae574a00-22a0-11eb-9711-4c7f1ef3dbc6.png)

![image](https://user-images.githubusercontent.com/52021/98541575-b31bfe00-22a0-11eb-89dc-0c057ee1519b.png)

![image](https://user-images.githubusercontent.com/52021/98541590-b911df00-22a0-11eb-902f-49981ccbf1bb.png)

When linking to an existing Jira issue, there is no comment and no backlink.

We are using on-premises Jira Server.

**Comment by manuzope** [comment]
Yea, makes sense. I think we'll also have to handle the case where someone unlinks and to add a comment then.

I'll add this to our backlog but will likely not get to it very soon. We'd accept PRs though!

**Comment by earshinov** [comment]
Is there any contribution guide? How do I get started?

**Comment by earshinov** [comment]
There you have it: https://github.com/getsentry/sentry/pull/23023
