### ISSUE TITLE
API (JS) doesnt propagate reasonable errors

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2188]
The jqXHR object isnt propagated due to some bad chaining, but either way we should return our own

Ideally its error(ApiErrorObject), and the object gives us things like status code, json body, whatever is relevant

This will let us better handle errors like 404s or unauthorized requests.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
