### ISSUE TITLE
Can't create alert posting to slack channel

### ISSUE THREAD

**Issue by sintell** [getsentry/sentry#21898]
## Important Details

How are you running Sentry?
*On-Premise w/ Docker, version x9.1.2*

## Description

[What happened]
Can't send alerts that'll post messages to slack. Link substitution isn't working. Tested this with both public and private channels.

## Steps to Reproduce
1. Add slack integration from settings page following https://docs.sentry.io/product/integrations/slack/
2. Proceed to "New alert" for any project
3. Attempt to create new alert that will post to slack channel
4. Get an error saying `The slack resource "my-public-or-private-channel" does not exist or has not been granted access in the MyCompany Slack workspace.`
Also in logs for sentry-web I can see the following record:
`10:43:30 [INFO] sentry.rules: rule.slack.channel_list_failed (error=u'method_deprecated')`

### What you expected to happen
I should be able to create alerts that will post to slack using new global slack integration

### What to do ###
I saw a bunch of different issues related to this problem, and as I saw here https://github.com/getsentry/sentry/pull/19446 it was fixed for v10, but as far as I can see the fix was never backported for 9.1.x branch. Is it possible to backport it somehow, or is there any protocols to help me to contribute on that matter.

**Comment by manuzope** [comment]
Looks like someone was able to figure out a backport for 9.1.x: https://github.com/getsentry/sentry/pull/19446#issuecomment-714351836. Maybe try applying that patch to a forked version of your Sentry?

But there is no official backporting process.
