### ISSUE TITLE
Frontend crashes with TypeError (state undefined) when using custom query sidebar

### ISSUE THREAD

**Issue by ragesoss** [getsentry/sentry#21908]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 20.10.1 78833d9

## Description

When I use the the stream sidebar in the issues list to try to create a custom query, sidebar.tsx throws an error. If enter text in the Text field and press enter, nothing happens in the interface and there's a console error (`TypeError: Cannot read property 'state' of undefined`) from `IssueListSidebar#onTextFilterSubmit`. If I use one of the dropdowns to select a value for any  of the other inputs such as Logger, the frontend crashes and brings up the crash report dialog, and the TypeError comes from onSelectTag#onTextFilterSubmit.

Equivalent queries work as expected when constructed without the sidebar (eg, `logger:ruby`).

## Steps to Reproduce

1. From the Issues view, click the 'toggle search builder' button to bring up the search builder sidebar
2. Choose a value from one of the dropdown inputs (eg, Logger)
3. frontend crashes

Stacktrace: 
[sentry.wikiedu.org-1605033570422.log](https://github.com/getsentry/sentry/files/5519501/sentry.wikiedu.org-1605033570422.log)

## Notes

Possibly related, I get this error twice in the console when loading Sentry: `GET https://sentry.wikiedu.org/_static/1604951199/sentry/js/ads.js net::ERR_ABORTED 404 (Not Found)`

I don't believe it's related to ad blocking, as I have replicated it in Firefox and Chrome without ad block extensions enabled, and also replicated it on a phone over a mobile data connection.

**Comment by markstory** [comment]
This should be fixed in 20.11.1

**Comment by ragesoss** [comment]
Confirmed fixed in 20.11.1. Thanks!
