### ISSUE TITLE
Improve Release Artifact Storage

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2194]
We shouldn't duplicate data or even upload data unless we need to.

Firstly, File data gets moved into a new FileBlob table, which is can be referenced by multiple File objects. The file table would contain the mutable metadata such as name and headers, and the blob would contain the file storage and checksum.

The release process would be expanded so that you can submit ReleaseFile's without uploading the file. Upon submission we would return an error if the file is not present and needs uploaded, and thus you'd resubmit the request with the attached file. This would be optional, and you could still do things the same way as today.

Additionally for privacy we attach a link between an Organization and a File. If an organization has never uploaded the given file, even if its stored (and wont be duplicated), we force them to upload it again to associate it with a release.

**Comment by dcramer** [comment]
We can use the link of ReleaseFile to enforce uploads right now.

**Comment by dcramer** [comment]
Deduplication is live on prod. We need to write a data migration for this (we have one that we used for getsentry.com), but otherwise its looking great. We cut down storage to 10% of the previous requirements on dotcom, so good win overall.

**Comment by dcramer** [comment]
I'm closing this out for now. We can still optimize the upload API so people don't need to continuously ship us artifacts that already exist, but thats more of a nice-to-have.

**Comment by hax** [comment]
Is there any plan to improve uploading release? It's too slow for our production usage, each release may cost 10 mins to upload.

**Comment by mattrobenolt** [comment]
@hax how large are the artifacts you're uploading? Is it one big artifact or are you uploading a bunch of small files? Can you parallelize?

Other than that, if the slowness is purely due to network overhead, not sure what we could do to speed it up.

**Comment by hax** [comment]
Each of our release may include 600+ files, most files are not very big, total size is about 100MB. We already use 100 threads to parallelize uploading.

Normally there are only a few files (< 10 files) changed in each release (but we release 20+ times one day), I don't find any way to bypass exist assets for new release, so we just waste 90% bandwidth and time. 😿  

Besides that, current API only allow upload one file, which seems not efficient. I think it's better to allow upload a compressed archive which include all files of a release.

Anyway, thank you for your great work.

**Comment by mattrobenolt** [comment]
@hax thanks for the feedback. :) Not sure exactly what we'll do here, but it seems like something we can/should address.

**Comment by mattrobenolt** [comment]
Also, to be clear, was 10 minutes not an exaggeration? That seems... really bad if the total size is only 100MB. That means transfer rate across all 100 threads is only getting 166KB/s.

**Comment by hax** [comment]
Our deployment server and sentry server are not in the same ISP host, the connection condition may complex and not very stable. We've tried unlimit threads which may increase the speed to about 3 mins, but many uploads will fail.

I'm still trying to improve our connection condition and other aspect of uploading issue. But even we could decrease the time to 3 mins, it's still slow compare to our whole build/deployment process which only 6 mins. As I mentioned, in our case, bypassing the exist assets may be the most effective method to solve the problem.

**Comment by dcramer** [comment]
We were going to add a check in the API where you could hash things locally and the server could tell you which files are missing. It's entirely designed to deal with this case.

**Comment by hax** [comment]
Just an update, after improve connection, we now can reduce the uploading time to 1min. If we can upload only new assets I expect the time will be only 10 seconds 😄
