### ISSUE TITLE
Create secondary bundle for admin

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2197]
We should split all of the /manage/ pages into their own bundle so normal users do not need to load the extra code.

There's a few things here:
- Identify how routes work when handlers arent available immediately. Is this even an option? We could alternatively just load the page via the server again and load a different main entry point (i.e. app/index instead of app)
- Determine how to create a second admin bundle. Effectively the deps should app relies on vendor, admin relies on app (which relies on vendor).

**Comment by dcramer** [comment]
Also going to need to start being more aware on how much code duplication we have and begin refactoring soon:

```
          vendor.js    1.06 MB       0  [emitted]  vendor
             app.js     317 kB       1  [emitted]  app
          sentry.js   90 bytes       2  [emitted]  sentry
         sentry.css     251 kB       2  [emitted]  sentry
```

**Comment by EvanPurkhiser** [comment]
it's code split.
