### ISSUE TITLE
Assign-to-user dropdown exceeds viewport if many users

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2198]
This occurs on both the event stream, and on group details.

![image](https://cloud.githubusercontent.com/assets/2153/10560357/fe857b3c-74d6-11e5-81f9-3d49c0d0a9f7.png)

**Comment by MaxBittker** [comment]
![image](https://user-images.githubusercontent.com/5915546/32809695-aa2f8e98-c94c-11e7-8214-747e76dbdb26.png)
while we're here, "its not case insensitive sorted"
