### ISSUE TITLE
Decode the fragment part of the URL 

### ISSUE THREAD

**Issue by tomyam1** [getsentry/sentry#2205]
I'd love if you code automatically decode the fragment part of the URL, e.g..:

_Before_:
![image](https://cloud.githubusercontent.com/assets/3265649/10580987/0e43e4ce-7689-11e5-9b5b-be4a14ef49e6.png)

_After_:
![image](https://cloud.githubusercontent.com/assets/3265649/10581049/5d41774e-7689-11e5-8d73-65c8c17ea076.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
