### ISSUE TITLE
On creating Auth Tokens in on-premise Sentry

### ISSUE THREAD

**Issue by dmanbu** [getsentry/sentry#22081]
I am using the version: https://github.com/getsentry/onpremise/archive/20.10.0.zip

I created Auth Tokens and the value of the token is "CI_AUTH_TOKEN"
I did not find any errors related to the api service, I need help, thank you!!

**Comment by BYK** [comment]
This release is faulty and the issue was fixed in 20.10.1. 20.11.0 is also out which you can use.
