### ISSUE TITLE
Display dates in localized formats

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2212]
Right now, we're always spitting out "AM/PM" style dates.

This is a bit annoying for users who use 24 hour time, for example. AKA, anyone not in the US. And me personally since I use 24 hour time. :)

I did some quick Googling, but couldn't figure out a reliable way to detect this. For example, on my computer:

```javascript
> (new Date).toLocaleTimeString()
"3:49:17 PM"
```

/cc @mitsuhiko I feel like you might know this or have an opinion.

**Comment by dcramer** [comment]
Just because you're not in the US doesnt mean you use 24 hour time

**Comment by mattrobenolt** [comment]
Yeah, just generalizing to "whatever your locale is". If your locale is 24 hour, we should use 24 hr, and vice-versa.

**Comment by heyman** [comment]
Thanks for the reply Matt! My thought (in the getsentry feedback I posted) was that it could be a setting on the page where you set the timezone.

I believe that most of Europe uses 24 hour time, but I might be wrong about that.

**Comment by mattrobenolt** [comment]
I think we'd rather avoid adding a new setting just for that if it's able to be detected, personally.

**Comment by dcramer** [comment]
IMO a setting is the right approach (I'm pretty sure you cant detect this in any friendly way). We already have a setting to choose locale, so a setting to choose time display seems fine.
