### ISSUE TITLE
Disallow paginating "next" when there is no next page

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2213]
This has at least been observed on on the event stream.

Right now, we show the button and allow to continuously page next, even if there are no results on the page.

Not entirely sure if this was a regression, or never worked. I feel like it was a regression.

Re: https://sentry.zendesk.com/agent/tickets/770

**Comment by benvinegar** [comment]
I've poked around on some stream pages, and it seems to me the "next" button is disabled appropriately. Have a concrete example?

**Comment by benvinegar** [comment]
Oh, in the ticket. Nevermind.

In any case – this is not as common as the ticket indicates.

**Comment by mattrobenolt** [comment]
Yeah, it doesn't happen all the time. I've just noticed it personally a few times in passing. But logged since this _is_ a bug. :)

**Comment by dcramer** [comment]
Needs more info :)

**Comment by benvinegar** [comment]
@mattrobenolt – The problem is the API response. We are returning a Link HTTP header that says there are "next" and "previous" results, even though there aren't any.
