### ISSUE TITLE
Discover Queries new filter: issue status

### ISSUE THREAD

**Issue by kasiagrnwld** [getsentry/sentry#22188]
## Summary

Add the possibility to Discover Queries of filtering by issue status.

## Motivation

It would be very helpful to be able to exclude events belonging to ignored issues from the result set of Discover Queries.

**Comment by markstory** [comment]
I agree this would be a great addition. Having issue level fields available in discover is something we'd like to do but isn't possible right now because of a variety of technical challenges.
