### ISSUE TITLE
Error when activating GitHub Student Developer Pack Offer | Plan/Offer cannot be activated

### ISSUE THREAD

**Issue by EhabJames** [getsentry/sentry#22215]
After signing into Github and linking Github with Sentry, https://sentry.io/for/education/ acknowledges eligibility for the offer, 
![image](https://user-images.githubusercontent.com/46765823/99908958-94136800-2cb3-11eb-9c0b-0756dd400b82.png)
but when the "Activate Plan" button is hit, an error appears. 
![image](https://user-images.githubusercontent.com/46765823/99908964-a7bece80-2cb3-11eb-9920-e4511d571d11.png)

**Comment by lowkeypriority** [comment]
Same problem.

When I try to click button "Activate plan" it returns HTTP 429:

```json
{"detail":"Rate limit exceeded."}
```

**Comment by BYK** [comment]
@EvanPurkhiser could this be related to #22150 too?
