### ISSUE TITLE
Slack Integration: Unable to install even though I upgraded to Team subscription

### ISSUE THREAD

**Issue by amyin** [getsentry/sentry#22220]
I upgraded and paid for the Team plan but when I try to integrate Slack, I see "Requires Team Plan or above." Please help thx.

![image](https://user-images.githubusercontent.com/680479/99944915-8b10ae00-2d28-11eb-91d1-a9bec6b58670.png)

**Comment by BYK** [comment]
Have you tried [contacting our support](https://sentry.io/contact/support/) for this?
