### ISSUE TITLE
Ability to integrate with CRM system to send alerts to customers about resolution of issues.

### ISSUE THREAD

**Issue by vikasgulati** [getsentry/sentry#2224]
There should be a way to integrate with CRM solutions (freshdesk, zendesk etc.) such that every time an issue is resolved on sentry the affected customers can be sent an email via the CRM portals.

**Comment by dcramer** [comment]
We're on the same page :)

There's some work-in-progress stuff we've got going thats in this exact direction. Likely will be making those plans more public in the next few weeks.

**Comment by vikasgulati** [comment]
Wow, that would be awesome. Thanks @dcramer :)

**Comment by BYK** [comment]
I think this is now possible with our webhook support.

Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
