### ISSUE TITLE
Expose more Releases metadata in UI on Release details page

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2225]
We have `version`, `ref`, `url`, `dateStarted`, and `dateReleased` at our disposal, but we only surface `version` so far.

Refs: https://sentry.zendesk.com/agent/tickets/808

**Comment by ctaintor** [comment]
This would make the Release feature very useful for us. It's often the case that people want to tie an issue in Sentry back to a URL with more information that we have internally for the release. If this metadata were exposed, that would be two clicks in Sentry (issue -> release -> internal site). As it is now, it _is_ stored and queryable by the API, but not as easily viewable.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
