### ISSUE TITLE
Better API Key Support

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2228]
We want to ensure the API is accessible to users. This means that non-owners should be able to perform actions, such as uploading sourcemaps to a project, without requiring an owner create them an API key.

**Comment by mitsuhiko** [comment]
We should send out an email to users that have project keys to let them to to migrate.

**Comment by dcramer** [comment]
I'm exploring this again. Here's what I'm thinking right now:

- Add ``user`` to ApiKey
- Treat ApiKey just like a token
- Via settings (account settings? api keys page?) users can create an API key/token
- If its via api keys page, the key is still org bound
- Created key defaults to most privs? maybe read only privs? Can be customized.

**Comment by dcramer** [comment]
With this approach our plan would be as we work towards a v1 API we would begin to deprecate ApiKey as a pure auth mechanism, and ApiKey would shift towards generating an ApiToken (and primarily be used for OAuth flows).

**Comment by dcramer** [comment]
we're in a good enough spot on this right now
