### ISSUE TITLE
django.db.utils.OperationalError: FATAL:  database "sentry" does not exist

### ISSUE THREAD

**Issue by dazhuaoyao** [getsentry/sentry#22316]
I followed [official doc](https://develop.sentry.dev/environment/) step by step to configure  a local development environment for the Sentry server on macOS.

Everything goes well until I run `make bootstrap` command, it show errors:
<img width="1135" alt="图片" src="https://user-images.githubusercontent.com/29044630/100515211-41571600-31b5-11eb-8760-9de99244ad27.png">

The error messages tell that "database "sentry" does not exist", So I decide to check this. I go to the inner of postgres container by `docker exec -it xxxx`, then show all the database:
<img width="726" alt="图片" src="https://user-images.githubusercontent.com/29044630/100515588-33ef5b00-31b8-11eb-8e9d-2174baf062ad.png">

As you can see, the sentry database indeed exist. How can I fix this error, any advice here ? Thanks

**Comment by armenzg** [comment]
Thanks for filing. I will try to look into this tomorrow.

**Comment by armenzg** [comment]
Hi @dazhuaoyao are you still hitting this issue?
Unfortunately my week has been completed engulfed by the Python 3 migration work (We're now fully switched!).

Would you be able to merge `master` and recreate your virtualenv with Python 3? (it's now the default).

**Comment by dazhuaoyao** [comment]
> merge master and recreate your virtualenv with Python 3
this way fixed my issuse, thanks for advice
