### ISSUE TITLE
User Feedback tab is throwing an error 

### ISSUE THREAD

**Issue by georges** [getsentry/sentry#22318]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

Started using user feedback feature to report a couple of sample user reports. Now when I navigate to the User Feedback tab I get

ops! Something went wrong

It looks like you've hit an issue in our client application. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

If you're daring, you may want to try the following:

Give it a few seconds and reload the page.
If all else fails, contact us with more details.

## Steps to Reproduce

1. Crash a Cocoa app (SentrySDK.crash)
2. Send a user report via SentrySDK.captureUserFeedback
3. Navigate to User Feedback tab on sentry dashboard. Notice error.

Note that some of the user feedback may have had an empty string as email address.

### What you expected to happen

The User Feedback tab to render a list of reported user feedback.

### Possible Solution

I suspect that maybe something is going wrong in trying to pull the Gravatar on the user report email address.

**Comment by BYK** [comment]
Have you tried [contacting our support](https://sentry.io/contact/support/) for this?
