### ISSUE TITLE
Expose Raw JS source before mapping to sourcemap

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2232]
Refs: https://sentry.zendesk.com/agent/tickets/845

**Comment by dcramer** [comment]
It's already in the tooltips. 






On Mon, Oct 26, 2015 at 5:31 PM -0700, "Matt Robenolt" <notifications@github.com> wrote:












Refs: https://sentry.zendesk.com/agent/tickets/845

**Comment by dcramer** [comment]
We can revisit this later, but for now I'm closing as wontfix.
