### ISSUE TITLE
Email Improvements

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2238]
- Comments should ideally have some overflow https://www.dropbox.com/s/11r9g0qploe70rn/Screenshot%202015-10-27%2014.09.43.png?dl=0
- We could probably remove level/event count from the issue thing. Alternatively remove just event count and move error to the line w/ the date string
- Change "On this event" to be "On this issue" for uniform naming

**Comment by dcramer** [comment]
@ckj @tkaemming let me know your thoughts on these

**Comment by ckj** [comment]
:+1:

**Comment by tkaemming** [comment]
> We could probably remove level/event count from the issue thing. Alternatively remove just event count and move error to the line w/ the date string

I think keeping the level makes sense (and I also think we should add it to the digests, actually.) Agreed on removing the count, though.

**Comment by ckj** [comment]
I think I addressed all of this directly on master. Here's the result:
<img width="681" alt="screen shot 2015-10-27 at 4 13 58 pm" src="https://cloud.githubusercontent.com/assets/30713/10775463/ce77df56-7cc5-11e5-806f-9cf4d8f48995.png">
