### ISSUE TITLE
GitHub Actions: Avoid using `pull_request_target`

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#22432]
GitHub Actions (GHA) does not expose repo secrets to PRs opened from a fork. This breaks for our custom and required workflows (e.g. Visual Snapshots). To workaround this we opted to use the workflow event: `pull_request_target` which allows forks access to secrets, with some limitations. The major one being that it only runs the workflow defined on the base branch (e.g. master).

This event also, by default, checks out the repo from the base PR branch (master). In our workflow, we need to check out the fork branch to test, but by doing so we expose ourselves to the user’s code which can pull out and reveal our secrets.

Our current “secrets” are pretty harmless at the moment: 1) visual snapshots API key, which only allows you to upload snapshots (but doesn't get passed to usercode), and 2) secret to verify webhook payload for webpack metrics. However, this will end up being overlooked in the future, and we should change this before it gets to that point.

The solution here is to 1) never use `pull_request_target` for workflows that requires you to checkout/run your repository's code and 2) use `workflow_run` instead.

I have a PR incoming that will address this issue, but wanted to create this issue so that it's documented.

**Comment by joshuarli** [comment]
This is well written. Dang, finding the right things to use is kind of a challenge, I don't remember seeing this before, but workflow_run is what we need:

https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows

> The workflow started by the workflow_run event is able to access the secrets and write tokens used by the original workflow.

**Comment by billyvg** [comment]
@joshuarli Yeah, and the reason I dismissed it initially was because in their payload example, it didn't look like we could get the Pull Request context: https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#workflow_run
