### ISSUE TITLE
Jira Integration: On Prem Install

### ISSUE THREAD

**Issue by ehoffman73** [getsentry/sentry#22441]
We cannot seem to point Jira Cloud to our on premise Sentry install, which we have a requirement for due to information generated to Sentry from error logs.   Is there a way to accomplish this by modifying some settings?

**Comment by BYK** [comment]
We have some docs here: https://develop.sentry.dev/integrations/jira/

Also if you can follow the issue template and provide all the information we ask there, it would be much easier to help you.

**Comment by ehoffman73** [comment]
Great info that I did not find.  Apologize for missing post formatting.  Will work with Jira further as the custom settings fail on their cloud.
On Dec 4, 2020, 8:15 AM -0600, Burak Yigit Kaya <notifications@github.com>, wrote:

We have some docs here: https://develop.sentry.dev/integrations/jira/

Also if you can follow the issue template and provide all the information we ask there, it would be much easier to help you.

**Comment by BYK** [comment]
@ehoffman73 would you mind if we close the issue then? We can always reopen if you need to follow up.

**Comment by ehoffman73** [comment]
Please do, I was able to hack away until it worked.  Thank you for the Christmas gift!!

Regards,

Eric Hoffman
President
Datastream Connexion
ehoffman@dscxn.com
651.717.4105

Set Meeting:
https://calendly.com/ehoffman

LinkedIn:
http://www.linkedin.com/in/ehoffman

[cid:032EB354CF47478EB6EB3903F4EAC92F]
[cid:48FFF055BD734541A894D712BEB6EF2A] [cid:DC34695785CD4E30969BECE2064E0765]
On Dec 7, 2020, 11:50 PM -0600, Burak Yigit Kaya <notifications@github.com>, wrote:

@ehoffman73<https://github.com/ehoffman73> would you mind if we close the issue then? We can always reopen if you need to follow up.
