### ISSUE TITLE
API Key scopes not reflected on edit page

### ISSUE THREAD

**Issue by tomdev** [getsentry/sentry#22459]
## Important Details

**How are you running Sentry?**

On-Premise w/ Docker, version 20.10.1

## Description

The scopes enabled for an API Key are not reflected when editing the API Key.

The following API Key has the `project:releases` scope enabled, but this is not shown:
![Edit_API_Key_-_Sentry](https://user-images.githubusercontent.com/338470/101175477-8069e900-3645-11eb-8728-fb3fde994f32.png)

When looking at the raw response of the XHR call (`https://sentry.somedomain.com/api/0/organizations/my-org/api-keys/6/`) retrieving the API Key information, we do see the following:
![Screenshot_12_4_20__3_34_PM](https://user-images.githubusercontent.com/338470/101176057-40efcc80-3646-11eb-92a3-e7c1f9363a04.png)

## Steps to Reproduce

1. Select "New API Key" from https://sentry.somedomain.com/settings/org/api-keys/
2. Name the key, select scopes
3. Save changes
4. Click on the name of API Key you just created
5. The "Edit API Key" page is not showing the scopes selected in step 2

### What you expected to happen

When editing an API Key I expect to see the checkboxes for the scopes enabled for this API Key to be checked.

### Possible Solution

-

**Comment by NisanthanNanthakumar** [comment]
Hi @tomdev, it seems that we had this issue fixed in this PR: https://github.com/getsentry/sentry/pull/22199
That got merged on Nov 20, 2020. So I would recommend upgrading your instance to the latest onprem version: https://github.com/getsentry/onpremise/releases/tag/20.12.1

**Comment by NisanthanNanthakumar** [comment]
Closing as this is fixed on recent releases.
