### ISSUE TITLE
Unable to fetch lock when creating new project

### ISSUE THREAD

**Issue by acsrujan** [getsentry/sentry#2245]
Logged in as owner and created new project.
Sentry Version: Latest master on git
**Request**: 
    POST https://sentry.tinyowl.com/organizations/sentry-internal/projects/new/
**Exception**:
UnableToGetLock: Unable to fetch lock after 2.912s: <Lock: 'slug:project'>
(6 additional frame(s) were not displayed)
...
File "sentry/web/frontend/create_project.py", line 87, in handle
    project = form.save(request.user, request.META['REMOTE_ADDR'])
 File "sentry/web/frontend/create_project.py", line 50, in save
    return super(AddProjectWithTeamForm, self).save(actor, team, ip_address)
 File "sentry/web/forms/add_project.py", line 29, in save
    project.save()
 File "sentry/models/project.py", line 109, in save
    with Lock(lock_key):
 File "sentry/utils/cache.py", line 123, in __enter__
    raise UnableToGetLock('Unable to fetch lock after %.3fs: %r' % (time() - start, self,))

**Comment by dcramer** [comment]
This relies on the CACHES setting. You should confirm it's configured correctly (or disable it):

```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
    }
}
```
