### ISSUE TITLE
Long package names do not render well

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2246]
This creates two issues:

1. They dont line up with the version
2. They're simply not legible

![image](https://cloud.githubusercontent.com/assets/375744/10943371/fb347c08-82c8-11e5-9524-6cdc56ed6118.png)

**Comment by mattrobenolt** [comment]
There's also a `max-height: 5000px` which causes them to overflow out of the box.

**Comment by asbjornu** [comment]
The list of packages shouldn't be a definition list, but a `table`. It is perfectly valid and semantically correct to use a table for that and it is actually semantically wrong to use a definition list. With the `DL`, packages with long names span several lines and the next package won't align vertically with its corresponding version number. Had you used a table with proper table rows, this problem couldn't have happened.

**Comment by ckj** [comment]
Hey @asbjornu, we shipped out a fix for this just now that utilizes tables. Let us know if it makes things better for you.

**Comment by asbjornu** [comment]
@ckj Perfect!
