### ISSUE TITLE
TLS in SMTP is STARTTLS that is less secure than SSL(TLS)

### ISSUE THREAD

**Issue by PMExtra** [getsentry/sentry#22492]
Ref #4252

There is a wrong standpoint:

> Closing this as we are now on Django 1.11 which should support both SSL and TLS (and you really shouldn't be using SSL 🙂 )
_Originally posted by @BYK in https://github.com/getsentry/sentry/issues/4252#issuecomment-687329455_

We really should support SSL! Because the `SSL` of SMTP is include the well-known `TLS`. But in fact, the `TLS` of SMTP is `STARTTLS` instead of the well-known TLS.

According to [RFC3207](https://tools.ietf.org/html/rfc3207#section-11.1) (summary ref https://serverfault.com/a/648282), STARTTLS is less secure than TLS.

In the docs of most popular email service providers such as Tencent QQMail or Google Gmail, they both recommended using SSL (with port 465) rather than using STARTTLS (with port 587).

**Comment by PMExtra** [comment]
https://github.com/django/django/blob/master/django/core/mail/backends/smtp.py#L56-L67
You can check this to ensure TLS is STARTTLS.

**Comment by PMExtra** [comment]
Other references: https://www.fastmail.com/help/technical/ssltlsstarttls.html

> TLS vs STARTTLS naming problem
> One cause of confusion around the names of these different technologies is that some email software incorrectly uses the term TLS when they should have used STARTTLS.
>
> Older versions of Thunderbird in particular used "TLS" to mean that STARTTLS should be used to upgrade the connection, and the connection should fail if STARTTLS is not supported.
> 
> These versions also used the term "TLS, if available". "TLS, if available" meant that the program would try to use STARTTLS to upgrade the connection if the server supported this, but otherwise use an insecure connection.

**Comment by BYK** [comment]
@PMExtra thanks a lot for noticing the mistake here, picking the old issue up and then providing all these references. I definitely didn't think much about SMTP having different definitions of TLS and SSL.

👏🏻
