### ISSUE TITLE
angular8 ERROR TS2304: Cannot find name 'Omit'.

### ISSUE THREAD

**Issue by xtqjh** [getsentry/sentry#22520]
我采用的是在本地Docker上搭建sentry
前端框架使用Angular版本8

### package.json
```
"@sentry/angular": "^5.29.0",
"@sentry/tracing": "^5.29.0",
```
### main.ts
```
import * as Sentry from '@sentry/angular';

Sentry.init({
  dsn: 'http://325b7dd1b1dc44cd81063b51c359e255@172.16.111.21:9000/2'
});
```

### app.module.ts
```
import { createErrorHandler } from '@sentry/angular';

providers: [
...
{provide: ErrorHandler,useValue: createErrorHandler({showDialog: true,}),}
...
```

> 控制台输出错误：

ERROR in node_modules/@sentry/hub/dist/session.d.ts(17,27): error TS2304: Cannot find name 'Omit'.

[
![image](https://user-images.githubusercontent.com/7663676/101450651-d69c9c00-3965-11eb-9b10-3ae7db5cc5e2.png)
](url)

**Comment by harshilsharma63** [comment]
@xtqjh how did you resolve this?
