### ISSUE TITLE
GHA: Enforce stricter requirements for `uses` 

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#22536]
In GHA, you can use an action via the `uses` key. It is defined by `<github org>/<github repo>@<ref>`. However, ref can refer to a branch name or a tag, both which are mutable and is a security concern when using third party actions. We should either use a commit SHA, or, the preferred method: fork the action into the `getsentry` repo.

In we were to add a linter (see #22495) of some sort, we would be able to enforce a list of allowed action orgs (e.g. `actions/*` and `getsentry/*`).

**Comment by BYK** [comment]
Right now we relay on this for Craft as it is under (somewhat) rapid development. This would cause high friction until we settle on the new stable.

**Comment by billyvg** [comment]
@BYK Can you clarify what you're relying on?

**Comment by BYK** [comment]
@billyvg we use `@master` for our `craft` action and another action. Since we control these repos, I'd say the risk is low.

**Comment by billyvg** [comment]
@BYK ahh, I clarified in description, but this refers to third party actions.

**Comment by billyvg** [comment]
This might not be necessary as GH supports this: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#allowing-specific-actions-to-run

**Comment by armenzg** [comment]
Good finding!

**Comment by billyvg** [comment]
We're going to likely enforce at the GH organization level.
