### ISSUE TITLE
Slack Integration - Tags disappear after assigning issue

### ISSUE THREAD

**Issue by samkotlove** [getsentry/sentry#22535]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

The slack integration allows you to add tags from the event to the slack message. They show up perfectly fine but after assigning the issue to a user, the message changes and the tags are removed.

## Steps to Reproduce

1. Create a slack alert with tags in the alert message
2. Trigger an alert
3. Note the alert has the tags
4. Assign the issue to a user
5. Note the tags are gone

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant

### What you expected to happen

[What you think should be happening]

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by manuzope** [comment]
This seems worthwhile. We don't have the bandwidth to implement this right now but would accept PRs!

**Comment by fenilgandhi** [comment]
I would like to work on this. Will post updates as i find out

**Comment by ido-green** [comment]
We are also inconvenient about the tags being removed after an issue get's assigned in Slack. 
Has there been any progress on this? Any ETA that can be shared? 
Thank you.
