### ISSUE TITLE
Slack Integration: encountering a problem when trying to add workspace

### ISSUE THREAD

**Issue by 318h7** [getsentry/sentry#22550]
When adding a workspace from the sentry/settings/integrations, getting an error message from slack [app](https://my.slack.com/apps/A011MFBJEUU-sentry):
`invalid_team_for_non_distributed_app`

I am sure that I am authenticated to the workspace in question.

Tried to contact slack support, they said to contact you guys. Adding:
```
o give you more context, this error indicates that the app you are trying to install does not have distribution enabled.
```

**Comment by BYK** [comment]
Please follow the issue template and provide as much information as possible. Closing as this issue is not actionable in its current state.
