### ISSUE TITLE
Improve CSRF Behavior

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2258]
Users should generally not ever see a CSRF failure, yet it's not uncommon. We need to identify what's causing these, and ensure it's really hard for it to happen in the future.

**Comment by dcramer** [comment]
Untested steps to reproduce:

- Load login window
- Launch a second window with login window
- Create account using second window
- Login via first window

**Comment by mitsuhiko** [comment]
Leaving some thoughts from IRC here for reference:

* use a token that holds for N hours and generate it out of a based timestamp
* regenerate token every time interval but accept N-2 tokens
* share the same token across all urls and forms.

That way token can only be leaked for N+2 time intervals.  Downside is that it now means you can submit a form twice but I think that's okay.

**Comment by spookylukey** [comment]
Quick note: CSRF tokens (or any auth tokens) should not find their way into URLs, because they can leak via Referer headers or other mechanisms.

**Comment by mitsuhiko** [comment]
@spookylukey is that a general note or are you aware of a case where we leak an csrf token into a URL?

**Comment by dcramer** [comment]
Would we need a nonce store to do the multi token approach?

**Comment by mitsuhiko** [comment]
How married are we to nonces for browser requests?

**Comment by dcramer** [comment]
I'm open to alternatives. No strong opinions.

**Comment by spookylukey** [comment]
@mitsuhiko a general note in response to the line above: "share the same token across all urls and forms."

**Comment by mitsuhiko** [comment]
That is meant as in the token not being scoped to the url of the page it's used on.

**Comment by tomchristie** [comment]
We've hit the same in the past too. Some conversation on gist here: https://gist.github.com/j4mie/9055969

I made a suggestion at that time that login could defer the CSRF check and instead only run it at the point that we determine the request is being made by a non-logged-in user.

I haven't had the time to throughly review if that'd have the desired effect, but maybe worth considering?

**Comment by benvinegar** [comment]
@dcramer – is this still an issue?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
