### ISSUE TITLE
Censor database connection URI's

### ISSUE THREAD

**Issue by jmhobbs** [getsentry/sentry#2260]
Sentry does a good job of censoring API keys and passwords, but one I've just seen it miss is a redis connection URI.

![screen shot 2015-11-02 at 11 08 55 am](https://cloud.githubusercontent.com/assets/115059/10888490/2ae74e1c-8152-11e5-8aa3-38ae5e3b36ce.png)

I think this would be an easy one to catch with a regex, something like ``^[a-z]+://.+:.+@.+``

**Comment by mattrobenolt** [comment]
Hmm, I _thought_ I did this. One second.

**Comment by mattrobenolt** [comment]
```
    def test_sanitize_url(self):
        proc = SensitiveDataFilter()
        result = proc.sanitize('foo', 'pg://matt:pass@localhost/1')
        self.assertEquals(result, 'pg://matt:%s@localhost/1' % proc.MASK)
        # Make sure we don't mess up any other url.
        # This url specifically if passed through urlunsplit(urlsplit()),
        # it'll change the value.
        result = proc.sanitize('foo', 'postgres:///path')
        self.assertEquals(result, 'postgres:///path')
```

I wonder if the values you're referring to aren't getting passed through the data scrubber.

Where are they coming from?

**Comment by mattrobenolt** [comment]
And for reference: 061129f519eef0baf927d95feebc872d2942f395 is where this was added.

**Comment by mattrobenolt** [comment]
Hmm, I even added another test case locally, and it still passed.

I wonder what's going on here.

**Comment by mattrobenolt** [comment]
@jmhobbs Did this happen on getsentry.com, or your own hosted version? If it's on getsentry.com, I'd be happy to investigate. If not, you can send me the raw JSON for that event and I'll look. I can't seem to reproduce this locally.

Unless you're running an older version that doesn't include my linked commit. :)

**Comment by jmhobbs** [comment]
@mattrobenolt I figured that it had been thought of, assumed it was a regression.  This was on getsentry.com

I assume it's passing through, the password config value right above it in the listing was cleaned.

Let me know what you need to look it up, the most unique looking identifier I have on the page is `Event 5c1e8273328c425eba7ab2510478ebd4`

I've got a link to the JSON, but unsure if that's ok to paste in the clear.

**Comment by mattrobenolt** [comment]
You can send the link to support@ and I'll take a look. :) It's slightly easier that way. 

--
Matt Robenolt
@mattrobenolt




On Mon, Nov 2, 2015 at 9:43 AM -0800, "John Hobbs" <notifications@github.com> wrote:












@mattrobenolt I figured that it had been thought of, assumed it was a regression.  This was on getsentry.com



I assume it's passing through, the password config value right above it in the listing was cleaned.



Let me know what you need to look it up, the most unique looking identifier I have on the page is Event 5c1e8273328c425eba7ab2510478ebd4



I've got a link to the JSON, but unsure if that's ok to paste in the clear.
