### ISSUE TITLE
Splunk sentry plugin - Support for Additional Details (extras)

### ISSUE THREAD

**Issue by k2snowman69** [getsentry/sentry#22617]
## Summary

Currently through the JS Api if you are able to send `extras` along with your Sentry message
```
    Sentry.withScope((scope) => {
      scope.setExtras(extras);
      Sentry.captureMessage(message, level);
    });
```

However when this is forwarded to splunk, these "extras" are not passed along.

The request is to pass along these extras to Splunk so that we can perform deeper more specific splunk queries. I would personally prefer they came in a separate section than the rest, for example:

```
{
   environment: Production,
   event_id: 9ca...,
   ...
   extras: {
     missingTranslationKey: "hello world"
   }
}
```

However I can also work with if they are merged with the root object.

## Motivation

To allow for deeper more meaningful splunk queries. Knowing the exception_type and exception_value is a good start, however sometimes being able to provide an object you can use to help categorize errors can be incredibly powerful.

## Additional Context

I see tags being handled here and I'm wondering if extras is effectively the same thing:
https://github.com/getsentry/sentry/blob/master/src/sentry_plugins/splunk/plugin.py#L176

Hopefully when I get time I can learn more about this repo (my first time here, hi!) and hopefully contribute. However I'm really hoping someone who knows the system (and python) can jump in.

**Comment by k2snowman69** [comment]
Just curious, if I were to go about trying to implement this, are there unit tests or sample inputs to help make sure I'm on the right track?

**Comment by manuzope** [comment]
Hmmm, @k2snowman69, you can find the tests [here](https://github.com/getsentry/sentry/blob/master/tests/sentry_plugins/splunk/test_plugin.py) but they're unit tests, they don't provide complete sample inputs.

Perhaps you can try hitting webhook.site or another similar webhook logging service while developing? And then use the Splunk free trial to be sure it works.

If you're up for implementing it, go for it (should be pretty straightforward). If we accept it or not will likely depend on how resource intensive the change is (i.e. does it make additional database calls).

**Comment by k2snowman69** [comment]
I'll be honest, I haven't had time to look into this however it's still useful so hopefully I'll find time or find someone who can.

I did have another question... seems that on [Sentry's documentation](https://docs.sentry.io/platforms/javascript/enriching-events/context/#additional-data) additional data is now deprecated? Is this different than the `setExtras` function still available on the scope or is this something different?

**Comment by k2snowman69** [comment]
Seems that the general event structure looks something like what's found on this page:
https://docs.sentry.io/api/events/retrieve-an-event-for-a-project/

However I still can't find where I'm supposed to pull `extras` from...

**Comment by k2snowman69** [comment]
From what I can tell, just by adding:
```
        props["context"] = [[k.format(tagstore.get_standardized_key(k)), v] for k, v in event.context]
```

Might just get the job done... though I have no idea how to easily test this idea and see if it really even works.

**Comment by klindklind** [comment]
We want to gather everything eventually in Splunk and we want to take Sentry into use for our frontends. However since additional data/extras are not forwarded to Splunk building Splunk dashboards out of Sentry events is pretty cumbersome. Having this support would be a game changer for us 🙏

**Comment by klindklind** [comment]
I know this is quite an old issue but has there been any plans on forwarding at least the additional data to Splunk so we could do searches on it? I guess the Sentry discover doesn't allow one to do searches on additional data which we use for narrowing down generic errors into something more specific.

**Comment by k2snowman69** [comment]
@klindklind It definitely wasn't ideal but we figured out a work around that we've made work fairly successfully using the beforeSend event. We bypass sentry's server side capabilities completely, added our own endpoint on the server that we call, and rebuilt everything we actually wanted in Splunk. With that said, the data payload that comes from Sentry isn't exactly what I would call Splunk friendly. For example breadcrumbs can be a bit of a pain to merge together. However if you're interested here's the code, hope it helps:

```typescript
Sentry.init({
    beforeSend: beforeSend,
    dsn: SENTRY_ENDPOINT,
    // You probably want to have environment, normalizeDepth, and others set
    ...otherConfigurations
});

function beforeSend(event: Sentry.Event) {
    // Don't log on localhost because it's noisy
    if (isLocalhost()) {
      return null;
    }

    // Some custom filter you set so you can remove PII information
    const filteredEvent = filterEvent(event);

    // Send the sentry event to our own endpoint. Endpoint effectively has
    // no logic and the server logger logs the content
    sendBeacon('/logs', filteredEvent);

    // Return null so sentry doesn't attempt to send to the sentry server
    return null;
}
```

**Comment by sentaur-athena** [comment]
Closing this issue since we don't provide support for plug-ins any more. Also seems like there's a workaround posted.
