### ISSUE TITLE
CSRF failure when SSO POST back to /auth/sso

### ISSUE THREAD

**Issue by julyclyde** [getsentry/sentry#2266]
Sentry version: 7.7.0 from pypi.

My company's SSO system just changed the way of passing identify of user back to sentry, now they POST the identify information to http://sentry.mydomain.com/auth/sso , so I encounter a CSRF failure "A required security token was not found or was invalid."

I tried to write this in the config file:
middleware_classes = list(MIDDLEWARE_CLASSES)
middleware_classes.remove('django.middleware.csrf.CsrfViewMiddleware')
MIDDLEWARE_CLASSES = tuple(middleware_classes)

but still meet the same failure. I don't know why.

Can I get rid of CsrfViewMiddleware, or set the sso.mydomain.com in a whitelist of CSRF? I see CSRF_TRUSTED_ORIGINS in https://github.com/django/django/commit/ab26b65b2f178597be845e203eb698e193e3502e , but that's a too new version of django to satisfy the requiments.txt of Sentry 7

**Comment by dcramer** [comment]
We could add support for CSRF_TRUSTED_ORIGINS. That said, is the /auth/sso a custom endpoint on your side? If so it would be fine to just mark it as csrf_exempt.

**Comment by julyclyde** [comment]
/auth/sso/ is not my custom endpoint. It is in src/sentry/web/urls.py and
calling AuthProviderLoginView which is based on BaseView. Csrf_protect is
set on BaseView.dispatch() . If I add csrf_exempt on it, I have to maintain
a branch of source code.

Later in yesterday, I hacked into MIDDLEWARE_CLASSES tuple, add a custom
Django middleware before csrfviewmiddleware, and set
'_dont_enforce_csrf_checks' flag for the single URI.

You said you could add support for CSRF_TRUSTED_ORIGINS, do you mean
support the latest Django, or support the option by sentry itself?

**Comment by dcramer** [comment]
We would support the options ourselves. We unfortunately cannot upgrade Django.

**Comment by julyclyde** [comment]
In additional, in my custom Django middleware before csrfvidewmiddleware, I didn't see HTTP_REFERER in request.META of the POSTed request. Maybe CSRF_TRUSTED_ORIGINS cannot be implemented?

**Comment by julyclyde** [comment]
In additional, in my custom Django middleware before csrfvidewmiddleware, I didn't see HTTP_REFERER in request.META of the POSTed request. Maybe CSRF_TRUSTED_ORIGINS cannot be implemented?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
