### ISSUE TITLE
"Similar events" view needs horizontal scrollbar

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2269]
Windows users literally can't scroll left-to-right at the moment without a trackpad.

**Comment by ckj** [comment]
Windows as in IE? Chrome? I don't have a good way to test this at the moment, but the scrollbars should be there: https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/less/shared-components.less#L523

**Comment by benvinegar** [comment]
```css
overflow-y: scroll;
```

We also need scroll in the `x` direction.

**Comment by ckj** [comment]
:blush:
