### ISSUE TITLE
/manage/status/mail/ has wrong highlight of `queue`

### ISSUE THREAD

**Issue by krrg** [getsentry/sentry#2272]
The admin page for managing email at /manage/status/mail/ has the wrong highlight on the sidebar.

Expected:  Should have `Mail` highlighted.

Actual:  Has `Queue` highlighted.

![screenshot from 2015-11-06 23-54-17](https://cloud.githubusercontent.com/assets/8496492/11014008/ba8d5448-84e1-11e5-9e6c-3fb4e3dd1664.png)

**Comment by dcramer** [comment]
What version of Sentry is this? Can't reproduce on the 8.0 RC

**Comment by krrg** [comment]
This was on version 7.7.  If it has since been fixed in the RC, then that's
fine.
