### ISSUE TITLE
Docs mention section "Running Sentry as WSGI application", which does not exist.

### ISSUE THREAD

**Issue by simonft** [getsentry/sentry#2275]
https://docs.getsentry.com/on-premise/server/installation/ says:

```
Sentry provides a built-in webserver (powered by gunicorn and eventlet) to get you off the ground quickly, also you can setup Sentry as WSGI application, in that case skip to section Running Sentry as WSGI application.
```

However that section does not exist.

**Comment by dcramer** [comment]
I guess we dont document it specifically, but the Nginx docs sort of cover it:

https://docs.getsentry.com/on-premise/server/nginx/

**Comment by do3cc** [comment]
The link you provided does not really explain how to run sentry as a wsgi app. Also, the term @simonft is really confusing. I should skip the Running Sentry as a WSGI application, when I want to run it as a WSGI application?

**Comment by mattrobenolt** [comment]
`sentry start` fires up wWSGI now, so not sure it's relevant anymore to need to run it otherwise since we should make sure this works for all scenarios. Dipping into running it as a WSGI application shouldn't provide any extra values and should be hidden imo. Even for getsentry.com now, we use `sentry start`.

**Comment by simonft** [comment]
[Performance Tuning](https://docs.getsentry.com/on-premise/server/performance/) states

> Switching off of the default Sentry worker model and to uWSGI + emperor mode can yield very good results.

Is this no longer the case?

We also use uwsgi because that's how all of our other python applications are run, so it fits into our deployment model.

**Comment by mattrobenolt** [comment]
I'm not sure the question, but `sentry start` runs uWSGI now and is intended to be the most optimized way and will be what we optimize going forward. It's what we run for getsentry.com too.

**Comment by benh57** [comment]
The docs still mention this section, and the section still does not exist. This bug should still be open. If the section is no longer needed then the bug is 'remove that from the website / docs'.

**Comment by benh57** [comment]
https://docs.sentry.io/server/installation/python/  :  

"Sentry provides a built-in webserver (powered by uWSGI) to get you off the ground quickly, also you can setup Sentry as WSGI application, in that case skip to section Running Sentry as WSGI application."

**Comment by mattrobenolt** [comment]
@benh57 https://github.com/getsentry/sentry/pull/4753

**Comment by benh57** [comment]
Awesome, thanks!
