### ISSUE TITLE
Process Context

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2277]
We should enhance the current revision of the API with process metrics. For now these could show up as something similar to the extra context data.

Some basic attributes:
- Machine
- OS
- Memory
- CPU
- IO (if we can safely get it)

We want the system to mostly be aware of all of these metrics. There's also some complications on how we capture them. i.e. do we capture metrics for all cpus? all disks? Some other notes that process data != system data, so we may want multiple stats here (i.e. how much memory is process using vs how much system is).

**Comment by dcramer** [comment]
This came up recently during a demo, and things like Crashlytics generally provide this. Probably makes sense to start by reviewing what the mobile/desktop platforms focus on, and expand from there. The Rust also captures some of these metrics (many as tags), and we could reach out to them as another use case.

**Comment by mattrobenolt** [comment]
Would we want to support this data as an interface? or just as tags/extra data? I think it'd make sense as an interface personally.

**Comment by dcramer** [comment]
@mattrobenolt it would be a defined struct, not arbitrary as we'd want to build graphs/etc out of it

**Comment by mattrobenolt** [comment]
Right, that's why I'm proposing an actual interface for it, rather than freeform tags or something.

**Comment by dcramer** [comment]
We would want to be able to plot these on a distribution chart for this to be extremely useful. Similar to what we provide with tags today, but we'd need proper bucketing.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
