### ISSUE TITLE
Release Endpoints Version Field Encoding

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#2280]
Currently due to a bug we require clients to multi encode incoming data in the version field.  The decoding happens in these places:

* first level decode in the webserver which decodes for the routing
* second decode is directly in the project endpoint

This means a client needs to double encode the data to get to what the code originally expects.

The original unquoting was done as an attempt to get slashes through the system but unfortunatley they cannot be carried in url path components.  A `%2f` gets resolved to `/` early on to support matching on paths and there is little we can do about that.  Some servers support passing through unquoted bytes but only if no high level matching has been performed.  However even in that case the django routing system requires unquoted paths to support matching which again would kill the slash.

Proposals:

* send the data into a query string, there all bytes survive
* figure out which wsgi servers we support and try to see if we can get to raw bytes for all of them, then build a reconciliation system to get to the raw bytes
* do greedy matching where we allow slashes to appear as part of the parameter.  eg: `/foo/<bar>` where `bar` can contain slashes itself.

**Comment by mitsuhiko** [comment]
Thoughts @dcramer?

**Comment by dcramer** [comment]
I'm not super thrilled about our inability to support this. Using a query string would require literally every endpoint to be changed / duplicated.

If it comes down to using a query string or disallowing slashes, I'm going to vote the latter.

**Comment by mitsuhiko** [comment]
I'm good with just disallowing slashes.

**Comment by dcramer** [comment]
That's fine. We may want to query on what already exists in the system and make sure we're not breaking anyones data. We also need to handle this in the Release auto creation code.

**Comment by mitsuhiko** [comment]
I'm going to remove the bad unquotes for the moment. That will at least make the current endpoints work if you are not using slashes and then separately disallow slashes on new versions.

**Comment by mvaled** [comment]
@dcramer Does raven do the double-encoding automatically?  I'm using raven 5.8.1 (latest on pypi) and I see this quote issue.

**Comment by dcramer** [comment]
I'm not entirely sure. I think the client is encoding it correctly, but we haven't researched it very deeply yet.
