### ISSUE TITLE
New ownership rule removes all existing

### ISSUE THREAD

**Issue by Shtannikov** [getsentry/sentry#22823]
## Important Details

How are you running Sentry?

On-Premise Docker, version 20.11.1 3da5001

## Description

![ownership](https://user-images.githubusercontent.com/31800676/102787573-57ba5100-43b2-11eb-8dd3-06444f506edc.gif)

## Steps to Reproduce

1.  Create ownership rules for project
2. Open any project issue
3. Create ownership rule by Path

### What you expected to happen

The new rule is added to the existing ones

**Comment by scttcper** [comment]
This was fixed in #22139 which looks like it was released in `20.12.0`

**Comment by markstory** [comment]
Closing as this is fixed in 20.12.0
