### ISSUE TITLE
Do not close context variables on click

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#2283]
From support:

Feature request: when showing stacktraces, please don't open/close the inspection on click. Many times I need to copy the variable values to the clipboard but when I select the text the inspection closes.

Here's an image of what I'm talking about: http://cl.ly/image/2k242l3p361a

**Comment by nickpresta** [comment]
@mitsuhiko hoping to fix it in https://github.com/getsentry/sentry/pull/2281

**Comment by mattrobenolt** [comment]
Fixed with #2281
