### ISSUE TITLE
Unable to change subscription even after removing plugin from heroku

### ISSUE THREAD

**Issue by Dreamersoul** [getsentry/sentry#22871]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

I removed the Sentry plugin from Heroku and now i cannot detach the organization from the heroku account 

## Steps to Reproduce

1. use heroku to start a sentry organization for your app
2. remove the plugin from heroku
3. try to update the subscription plan of the organization from sentry

### Possible Solution

Add a button to remove the heroku integration from sentry.io organizations page

**Comment by BYK** [comment]
@manuzope ping
