### ISSUE TITLE
Issue sidebar tagFilter onSelect Crash

### ISSUE THREAD

**Issue by envestcc** [getsentry/sentry#22873]
## Important Details

How are you running Sentry?

Other, version 20.10.1, [deploy in virtual machine ]

## Description

In issues page, i toggle sidebar. when i select a tag from any tagfilter, the web crash happened.

## Steps to Reproduce

1. click "Issues" in left menu 
2. click "toggle search builder"
3. select any tag from any tagfilter

Good items to include here include:

- [stacktrace.txt](https://github.com/getsentry/sentry/files/5750296/stacktrace.txt)

### What you expected to happen

should show the filted issues

**Comment by markstory** [comment]
This has been fixed in master and should be fixed in the 20.11 release.
