### ISSUE TITLE
Make dark mode toggleable per user

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/sentry#22887]
## Summary

We have dark mode now—yay! 🎉 😎 

Sadly it is only available to super-users at the moment:

<img width="427" alt="Screen Shot 2021-01-04 at 8 27 46 AM" src="https://user-images.githubusercontent.com/134455/103539841-bf6aa480-4e66-11eb-8f39-8ee19a3fc55c.png">

Let's bring the darkness to all users!

## Motivation

If we're going to offer dark mode it doesn't seem like there's a good product reason to limit it to superusers. Seems kinda goofy and half-baked 🙈 that it's there but not available for everyone.

## Context

👍 from @tomlister [on Twitter](https://twitter.com/tomlist3r/status/1342402967735922688).

**Comment by tomlister** [comment]
This is a pleasant surprise! ☺️
Cheers.

**Comment by chadwhitacre** [comment]
TIL how to dark mode thanks to you. 😁 Is it really only available from the settings search? 🤔

**Comment by tomlister** [comment]
> TIL how to dark mode thanks to you. 😁 Is it really only available from the settings search? 🤔

Yep. It's very well done too.
Also, I thought I'd rather tack the bug onto this issue than create a new one, so guys don't have to jump around issues or epics (if that's what you use).
This gif should explain the issue.
![2021-01-05 00 38 58](https://user-images.githubusercontent.com/6598515/103541089-f1bfe480-4eee-11eb-9936-d77ea5dbff6d.gif)

**Comment by chadwhitacre** [comment]
Thanks, reticketed as https://github.com/getsentry/sentry/issues/22888 since it'll be a separate piece of work to fix.

**Comment by chadwhitacre** [comment]
And thanks for the kind words! Glad you like the implementation so far. :)

**Comment by tomlister** [comment]
No worries. Thanks for opening the issue 👍

**Comment by billyvg** [comment]
Note dark mode is still under development, which is why it is currently only for superusers. We will be rolling this out to our SaaS users when it's a bit more polished and ready. This is now configurable (for superusers) in `User Settings` via https://github.com/getsentry/sentry/pull/22671
