### ISSUE TITLE
Page refresh drops dark mode

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/sentry#22888]
Reticketing from @tomlister at https://github.com/getsentry/sentry/issues/22887#issuecomment-753981795.

### Environment(s)

- self-hosted (20.12.1bade073)
- SaaS (sentry.io)

### Steps to Reproduce

1. Turn on dark mode via settings search.
2. Refresh the page.

### Expected

Still dark.

### Actual

Not dark. 😞 

![2021-01-05 00 38 58](https://user-images.githubusercontent.com/6598515/103541089-f1bfe480-4eee-11eb-9936-d77ea5dbff6d.gif)

**Comment by tomlister** [comment]
By the way, the environment is self hosted not SaaS. Not sure if that affects your ticketing procedures but just wanted to let you know.

**Comment by chadwhitacre** [comment]
What version of self-hosted are you running?

P.S. I was able to repro in SaaS as well.

**Comment by tomlister** [comment]
The version is Sentry 20.12.1bade073

**Comment by chadwhitacre** [comment]
Thanks, noted in the description.

**Comment by billyvg** [comment]
This is closed by https://github.com/getsentry/sentry/pull/22671

**Comment by chadwhitacre** [comment]
Interesting, thanks @billyvg.

P.S. Should the user option show up when searching for "dark mode"? Users may not think to search for "theme." I presume we're matching on the option name/title and not its description, but if so that's a little misleading since we highlight matches in both the name and description.

<img width="427" alt="Screen Shot 2021-01-04 at 1 50 13 PM" src="https://user-images.githubusercontent.com/134455/103568645-ef7c6c80-4e93-11eb-9d10-3709c40e9136.png">

<img width="434" alt="Screen Shot 2021-01-04 at 1 50 22 PM" src="https://user-images.githubusercontent.com/134455/103568651-f0ad9980-4e93-11eb-80ce-f2c6da7d9314.png">

**Comment by chadwhitacre** [comment]
Also, in SaaS, selecting "Theme" doesn't seem to take me to a place where I can modify the theme. 🐭

https://user-images.githubusercontent.com/134455/103569761-e55b6d80-4e95-11eb-872c-39fbe09ff611.mov

In self-hosted I do find the option (so hopefully @tomlister you are all set?):

<img width="774" alt="Screen Shot 2021-01-04 at 1 58 56 PM" src="https://user-images.githubusercontent.com/134455/103569355-20a96c80-4e95-11eb-904e-4bf4bb5df9b0.png">

**Comment by chadwhitacre** [comment]
Found the [answer](https://github.com/getsentry/sentry/issues/22887#issuecomment-754150516):

> Note dark mode is still under development, which is why it is currently only for superusers. We will be rolling this out to our SaaS users when it's a bit more polished and ready. This is now configurable (for superusers) in User Settings via #22671

**Comment by chadwhitacre** [comment]
(Ideally I guess the "Theme" option would not show up for me as a non-superuser.)

**Comment by billyvg** [comment]
Yeah it seems to be a bug, the search should query the description

**Comment by chadwhitacre** [comment]
> Ideally I guess the "Theme" option would not show up in search for me as a non-superuser.

Reticketed as https://github.com/getsentry/sentry/issues/22915.

> Yeah it seems to be a bug, the search should query the description

Reticketed as https://github.com/getsentry/sentry/issues/22917.
