### ISSUE TITLE
Enhanced Rate Limits

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2289]
Right now Sentry provides rate limits in two systems:

1. getsentry.com has a custom implementation of Quotas that are organization bound
2. Sentry itself provides team and project based rate limits (disabled on getsentry.com)

We want to converge these systems so that getsentry.com can provide a usable implementation of project rate limits.

### Approach

- Add organization rate limits to Sentry core
- Organizational quota is only controllable via plugin (by default), inherits from system quota
- Move rate limit controls to organizational level<br />
  (This ensures that only people with access can control rate limits, as it's generally an administrator who would need to mind over this and not a project owner)
- Change all limits to be percentage based (1-100) of the entire organization quota

### Tiered Limits

The current model of rate limits generally does an increment in Redis and then uses that result to test things. This is a problem if we want to say "there was enough room in the organization but not the project", as it would have effectively counted the event in both. We should move this to a LUA script for the Redis implementation so it can happen in a single transaction, and to the appropriate key. To ensure the key isn't partitioned, we'd (likely) do this within a hash.

**Comment by dcramer** [comment]
In an ideal world, we could simply show a "You have no rate limit, nothing to configure here" on the organization limits page. It's unclear if this makes sense. For On-Premise it's a bit odd, but really the rate limits are operational concerns and each installation should likely specify it, so again passing it up the chain.

Given the above, we could rethink this a bit:

We add a **Rate Limits** navigation item on the organization sidebar. If there's no rate limit for the organization this entire page effectively shows "you have no rate limit". Ideally in on-premise this would allow the admin to configure a rate limit. If there is a rate limit however, we simplify this by showing a box that allows you to set the maximum amount of data a single project can send. This value would be percentage based (1 - 100%), and would be ignored if there was only a single project.

**Comment by dcramer** [comment]
Quick mostly functional mockup of what this might look like on dotcom:

https://www.dropbox.com/s/3ewy2hwl7u7yiua/Screenshot%202015-11-16%2015.59.59.png?dl=0

**Comment by bcharp** [comment]
:+1: 
Hi, I just subscribe to getsentry.com. I arrived here by looking for rate limit on project.
I would like to have some control on project quotas on getsentry.com to prevent projects to canibalize each other.
I would prefer a per project base, but you said it was disabled (I'm curious as if it's a product or technical choice ?)

Thanks for this feature !

**Comment by dcramer** [comment]
@bcharp it was a bit of both -- it didn't work as expected on getsentry.com, and we also don't want people sending a flood of data and discarding it. We are reimplementing a more sane version of the feature per this ticket though.

**Comment by dcramer** [comment]
Redis pattern should be (ideally) contained within a LUA script and do the following:

```
over_quota(project_id, project_quota, team_quota, org_quota) => bool

if incr org > org_quota: return True
if incr team > team_quota: return True
if incr project > project_quota: return True
```

**Comment by dcramer** [comment]
``feature/rate-limits``

**Comment by dcramer** [comment]
@tkaemming assigning to you til we sort out Redis side of things

**Comment by tkaemming** [comment]
Anything else to do here at the moment, @dcramer?

**Comment by dcramer** [comment]
nope we good

**Comment by tkaemming** [comment]
:tada:

**Comment by alexef** [comment]
How should the rate limit feature work for on premises installation?

**Comment by dcramer** [comment]
@alexef same as all of our core features -- they're abstracted through a backend, so you have to configure it (QUOTAS). Once done you have the ability to set various rate limits.

**Comment by alexef** [comment]
Thanks @dcramer, I was able to enable it. One question, as it's unclear to me from the docs: i've set in config the system.rate-limit to 500, but I see the limit being 450 on each organisation's page (I have two organisations in my on premise installation).

Is it safe to assume that each organisation will get 90% of the system value, or there's something else going on?

**Comment by dcramer** [comment]
@alexef theres another setting that lets you set it to a % of the global. I dont recall off hand what it is (it might be in the UI, might be in the conf), but thats likely set to 90% right now. That means each one can send up to 450, but the system can only accept 500 total.

**Comment by alexef** [comment]
@dcramer i think it's SENTRY_DEFAULT_MAX_EVENTS_PER_MINUTE https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py#L840 

Thanks for the clarification, it's clear now what the limit is per system and per organisation!
