### ISSUE TITLE
feat: Help self-hosted users see how saturated their installation is

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/sentry#22904]
There's a "System Warnings" page that [seems to be a no-op](https://discord.com/channels/621778831602221064/621783515423440927/795669856426393610) for self-hosted installations:

<img width="1150" alt="Screen_Shot_2021-01-04_at_10 07 06_AM" src="https://user-images.githubusercontent.com/134455/103551060-c8b03d00-4e77-11eb-9163-3b81b892bae1.png">

It'd be swell to show some useful info there to help operators operate Sentry. [Queue visualizations](https://github.com/getsentry/onpremise/issues/788), for starters. Basically we want to help self-hosted folks understand when they're coming up against the performance limits of single-node Sentry and should start considering a migration to SaaS (or the wilds of yer-on-yer-own multi-node self-hosting).

**Comment by BYK** [comment]
Just merged #23285 today which is related. This page shows when you have actual warnings regarding config or deprecated things. The queue section on that page actually shows useful data but none of this is proactive.

**Comment by chadwhitacre** [comment]
Seems like this is low demand, closing.
