### ISSUE TITLE
bug: Settings search doesn't index descriptions in their entirety

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/sentry#22917]
Reticketing from https://github.com/getsentry/sentry/issues/22888#issuecomment-754180183.

## Environment

SaaS

## Steps

1. Be a superuser (or hurry up before either #22915 is fixed or dark mode is rolled out GA).
1. https://sentry.io/settings/
1. Search > "dark"

## Expected

The "Theme" setting shows up in the search results, because it has the word "dark" (case-insensitive) in its description.

## Actual

The "Theme" setting does _not_ show up in the search results. Adding to my confusion, search terms are highlighted in the description, leading me to believe that they _should_ match there as well.

## Demo

https://user-images.githubusercontent.com/134455/103664425-450e5300-4f40-11eb-9391-1144a2d772fe.mov

**Comment by markstory** [comment]
I wonder if it something specific to that form field. I was able to search other form fields by description.

![Screen Shot 2021-01-05 at 5 10 57 PM](https://user-images.githubusercontent.com/24086/103705478-15c80800-4f79-11eb-9c70-9bb6df642a71.png)

**Comment by chadwhitacre** [comment]
Interesting. I thought it might be entangled with #22915, but I tried on a local install where I am superuser and see the same unexpected behavior.

Furthermore, _some_ strings match the description for "Theme," but not others:

<img width="413" alt="Screen Shot 2021-01-05 at 5 16 15 PM" src="https://user-images.githubusercontent.com/134455/103705831-bdddd100-4f79-11eb-9111-10da7ef2ecb7.png">

<img width="419" alt="Screen Shot 2021-01-05 at 5 17 34 PM" src="https://user-images.githubusercontent.com/134455/103705947-efef3300-4f79-11eb-9408-46b507f016ac.png">

<img width="421" alt="Screen Shot 2021-01-05 at 5 17 07 PM" src="https://user-images.githubusercontent.com/134455/103705895-d9e17280-4f79-11eb-8271-79993bc1249a.png">

🤔 

Oooh! The second "theme" is not highlighted! 😲

<img width="423" alt="Screen Shot 2021-01-05 at 5 18 10 PM" src="https://user-images.githubusercontent.com/134455/103705991-06958a00-4f7a-11eb-9527-49339e6b36a1.png">

**Comment by chadwhitacre** [comment]
The search dropdown disappears when I try to inspect it in Chrome dev tools.

**Comment by chadwhitacre** [comment]
Maybe we only index the first n characters?

**Comment by markstory** [comment]
> Maybe we only index the first n characters?

I'm thinking this is the issue as well. This search component does all the 'indexing' client side via FuseJS. I found a tip in the docs that mentions [only the first 60 characters](https://fusejs.io/api/options.html#ignorelocation) are searched. Dark and Light are after that 60 character threshold.

**Comment by chadwhitacre** [comment]
Sounds about right. Probably easy to tune, though I won't stand in the way of someone more qualified than I closing this issue as `wont-fix`. :)

**Comment by chadwhitacre** [comment]
> someone more qualified

E.g. @github-actions. Eminently qualified. :)
