### ISSUE TITLE
SMTPServerDisconnected: Connection unexpectedly closed: timed out

### ISSUE THREAD

**Issue by arthurlogilab** [getsentry/sentry#2297]
I get a bunch of these tracebacks, eventhough sending emails works and the test procedure via the webui works  : 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sentry/utils/safe.py", line 26, in safe_execute
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sentry/plugins/bases/notify.py", line 59, in rule_notify
    self.notify(notification)
  File "/usr/local/lib/python2.7/dist-packages/sentry/plugins/sentry_mail/models.py", line 190, in notify
    context=context,
  File "/usr/local/lib/python2.7/dist-packages/sentry/plugins/sentry_mail/models.py", line 55, in _send_mail
    return msg.send()
  File "/usr/local/lib/python2.7/dist-packages/sentry/utils/email.py", line 189, in send
    self.send_all(messages, fail_silently=fail_silently)
  File "/usr/local/lib/python2.7/dist-packages/sentry/utils/email.py", line 194, in send_all
    return connection.send_messages(messages)
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 94, in send_messages
    sent = self._send(message)
  File "/usr/local/lib/python2.7/dist-packages/django/core/mail/backends/smtp.py", line 110, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes())
  File "/usr/lib/python2.7/smtplib.py", line 736, in sendmail
    (code, resp) = self.data(msg)
  File "/usr/lib/python2.7/smtplib.py", line 504, in data
    (code, msg) = self.getreply()
  File "/usr/lib/python2.7/smtplib.py", line 360, in getreply
    + str(e))
SMTPServerDisconnected: Connection unexpectedly closed: timed out
```

sentry version : Sentry 7.5.4

**Comment by dcramer** [comment]
it sounds like this is something to do with your SMTP server not responding in a time period the backend were to expect. Not sure what we can really do about this, so going to close it out.

**Comment by arthurlogilab** [comment]
I understand that this might be a problem with the STMP server not responding, but I think that this traceback should not appear in the logs, an single line ERROR log should be enough in my opinion.

**Comment by andrefreitas** [comment]
I am having the same issue. The emails are actually sent but sometimes we have timeouts (even with fast responses times). Sentry could allow to configure smtplib timeout: https://docs.python.org/2/library/smtplib.html#smtplib.SMTP

**Comment by davidmir** [comment]
After migrate to Sentry 8.16.0 I have started receiving this error. I'm not receiving any email from Sentry and I've configure the file with the following parameters:
```
mail.backend: smtp
mail.host: mysmtphost
mail.port: 25
mail.from: myfromail
```

I've seen the connection establishid with my SMTP server, but for some reason Sentry closes the connection... Any tips to try solve this issue?

Thanks

**Comment by ffjia** [comment]
@davidmir I found this article might be helpful to you: http://blog.e-shell.org/323. After increasing the timeout, my time out issue disappeared.

**Comment by Renrhaf** [comment]
Thanks @ffjia !
Maybe a configurable value for this timeout would be useful ?

**Comment by wavilov** [comment]
> @davidmir I found this article might be helpful to you: http://blog.e-shell.org/323. After increasing the timeout, my time out issue disappeared.

I tried to fix that error within a hole day. Though about SMTP settings and libs, firewalls and container links and suddenly it was a simple socket timeout..

Thank you, you make my day!

**Comment by DRSchlaubi** [comment]
I have the same error by using Sendgrid as an email provider and I don't think that a paid service like sendgrid always has such timeouts. Anyways I tried to use the test email button inside the admin dashboard and it worked perfectly

**Comment by wangy8961** [comment]
check out this post: http://www.madmalls.com/blog/post/smtphandler-send-error-email/ 
I personally tested it, it’s real and effective.

**Comment by wangy8961** [comment]
@DRSchlaubi  check out this post: http://www.madmalls.com/blog/post/smtphandler-send-error-email/ 
I personally tested it, it’s real and effective.

**Comment by linehammer** [comment]
This exception is raised when the server unexpectedly disconnects, or when an attempt is made to use the [python mail](http://net-informations.com/python/net/email.htm) SMTP instance before connecting it to a server. According to https://support.gmx.com/pop-imap/imap/windowsmailapp.html, clients sending outgoing mail through mail.gmx.com should connect on port 587 and use starttls. So, first try changing your script to connect on port 587 instead of port 465. Also, you'll need to send the ehlo command before the starttls command, then again after the starttls command.
