### ISSUE TITLE
JIRA: Support Personal Access Tokens (passwords will be deprecated)

### ISSUE THREAD

**Issue by valentijnscholten** [getsentry/sentry#22986]
**Is your feature request related to a problem? Please describe.**
In JIRA Server 8.14 and Confluence Server 7.9 atlassian has (finally) added tokens as a way to authenticate to the REST API. Much better then people using their company wide ldap password for this (and storing it in places).

**Describe the solution you'd like**
I think we should support this new authentication method as JIRA Datacenter will also use it and stay beyond 2024. And basic authentication with passwords will be deprecated at some point by atlassian.

**Describe alternatives you've considered**
Add support for https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html

**Additional context**
Please note these personal access tokens are slightly different from the JIRA Cloud api tokens (thank you atlassian).

Cloud: `curl -H "Authorization: Basic <base64(<username>:<yourToken>>)" https://{jiraBaseUrl}/rest/api/`

Server: `curl -H "Authorization: Bearer <yourToken>" https://{jiraBaseUrl}/rest/api/`

**Comment by BYK** [comment]
Related #15718.

**Comment by markstory** [comment]
Are you using the Jira plugin, or the Jira Server organization integration? The Jira Server Organization Integration (which should work with datacenter) uses private key based OAuth.

**Comment by valentijnscholten** [comment]
Yeah didn't realize that when creating the issue.

**Comment by markstory** [comment]
Ok. You do like there isn't anything to do here. The project plugin is deprecated and the organization integration is already using oauth.

**Comment by valentijnscholten** [comment]
Correct, sorry for "raising an issue too soon". The problem with the current way the integration is done is that it requires system admin access to JIRA, but I will post on the forum first to discuss.
