### ISSUE TITLE
[7.7.2] assets missing

### ISSUE THREAD

**Issue by luxifer** [getsentry/sentry#2298]
I just updated my sentry instance to 7.7.2 but had to rollback. I think the static assets were not build for this release because I get this:

<img width="423" alt="capture d ecran 2015-11-12 a 11 33 04" src="https://cloud.githubusercontent.com/assets/419078/11116199/521aafec-8931-11e5-85f4-4fbdad44bd89.png">

**Comment by renefs87** [comment]
Same happened to me. CSS was loaded properly but javascript was not.

**Comment by arifwn** [comment]
Same here. All js assets are returning 404. Had to revert to 7.7.1 for now.

**Comment by mattrobenolt** [comment]
Oh cool. Ughhh. :(
Sorry, this will get fixed first thing in the morning. (It's 5am right now)
--
Matt Robenolt
@mattrobenolt




On Thu, Nov 12, 2015 at 4:29 AM -0800, "Arif Widi Nugroho" <notifications@github.com> wrote:












Same here. All js assets are returning 404. Had to revert to 7.7.1 for now.

**Comment by mattrobenolt** [comment]
Looking into this now. So mad about this.

**Comment by mattrobenolt** [comment]
Ok, in the meantime, I've removed 7.7.2 from pypi while I'm investigating.

**Comment by luxifer** [comment]
Really really quick reply!! No problem, 7.7.1 works for me for now.

**Comment by mattrobenolt** [comment]
Alright, I've pushed a 7.7.3 that has the correct assets compiled in. I confirmed a few of them manually that were 404ing before.

Turns out, our build process isn't flawless and allowed me to compile a bad release. :(

@luxifer Can you double confirm before I mark this as closed?

**Comment by arifwn** [comment]
@mattrobenolt After upgrading to 7.7.3, I'm getting this error on the js console, and event stream doesn't load at all. Might be related to this assets issue?
![screen shot 2015-11-12 at 10 00 33 pm](https://cloud.githubusercontent.com/assets/1146705/11121698/e4fca290-8989-11e5-8bff-3cc5737d6d57.png)

**Comment by mattrobenolt** [comment]
@arifwn Can you try clearing cache?

If it's still broken, then my guess is some dependency in our JavaScript build has upgraded now to something incompatible. Which... is going to make me super sad. :(

**Comment by mattrobenolt** [comment]
welp, I see the issue now. `bower` and `gulp` failed on a dependency when compiling, but didn't error out the command. So it failed to build `jquery.flot` (which is where the error is coming from), and didn't yell loudly.

UGH, going to cut another release and manually inspect.

**Comment by mattrobenolt** [comment]
Ok, so I pulled 7.7.1 (which was in a working state) and have manually verified checksums of all of the files to compare between new build, and things seem to be ok now.

I guess I'll try and cut a 7.7.4 here to try and fix this.

From all of my inspection of the new tarball I have, this appears to be fine.

**Comment by mattrobenolt** [comment]
@arifwn Can you try 7.7.4 now? It's up on pypi.

If this doesn't work, I give up. :anguished: :rage4:

**Comment by dennishenry** [comment]
7.7.4 seems to resolve the issues for our installation - Thank you!

**Comment by arifwn** [comment]
Looks like it's working flawlessly now. Thanks a lot!

**Comment by mattrobenolt** [comment]
:clap: 

Sorry about this. HOPEFULLY something chaotic like this doesn't happen again.

Thanks for hanging in there.

If there's another issue, feel free to reopen, but I feel pretty confident that this is ok.

**Comment by luxifer** [comment]
everything's allright. thanks :+1:
