### ISSUE TITLE
warning after upgrading to 7.7.4

### ISSUE THREAD

**Issue by vytautasgimbutas** [getsentry/sentry#2300]
Celery workers are referencing a different version of Sentry (7.7.4 vs 7.7.3)

**Comment by mattrobenolt** [comment]
Hey @vytautasgimbutas, there has been a little bit of chaos in the releases from 7.7.2 -> 7.7.4.

7.7.2 and 7.7.3 don't exist, and everything should be updated to 7.7.4.

What you're seeing is exactly what it says. The workers are running 7.7.3, when the main UI is running 7.7.4. (Or vice-versa)

I assume just a restart of everything will make it fix itself.
