### ISSUE TITLE
feat: Support Network Error Logging (NEL)

### ISSUE THREAD

**Issue by ingria** [getsentry/sentry#23019]
### Summary

Sentry already supports [CSP reporting](https://docs.sentry.io/product/security-policy-reporting/). It would be nice to have [NEL](https://w3c.github.io/network-error-logging/) support as well.

### Motivation

NEL is a useful feature that allows reporting network errors that are usually difficult to detect. E.g. [DNS](https://w3c.github.io/network-error-logging/#dns-resolution-errors) or [connection](https://w3c.github.io/network-error-logging/#secure-connection-establishment-errors) errors.

### Additional Context

- [Browser support](https://caniuse.com/mdn-http_headers_nel)
- [W3C specs](https://w3c.github.io/network-error-logging/)
- [MDN article](https://developer.mozilla.org/en-US/docs/Web/HTTP/Network_Error_Logging)

**Comment by ericitzhak** [comment]
Is there any plan to implement this?
Not sure why it went stale, this would be very helpful as I now need to implement this on my own

**Comment by BYK** [comment]
@dcramer who makes the ultimate call on this?
