### ISSUE TITLE
SSO with Gitlab

### ISSUE THREAD

**Issue by sandywater** [getsentry/sentry#2302]
This would be great to have.

Great job on Sentry!

**Comment by dcramer** [comment]
Probably would be really easy to do assuming there is:

1. an api that works similar to github orgs
2. oauth

**Comment by SkyLothar** [comment]
i just write a a sso plugin based on @dcramer 's github version.
i believe most gitlab was used by just one org, so i drop the orgs feature.

check it out @sandywater  `https://github.com/SkyLothar/sentry-auth-gitlab`

**Comment by dcramer** [comment]
@SkyLothar wouldn't dropping the orgs feature mean you couldn't use it with gitlab.com since it would let anyone sign into your Sentry organization as long as they had a gitlab account?

**Comment by SkyLothar** [comment]
they can't. this sso plugin is for those private hosted gitlabs.

i can add orgs features back if you guys think it's important

**Comment by dcramer** [comment]
@SkyLothar its fine as a community contribution, but if we ever officially pushed it we'd probably want to ensure it supports all the standard security

**Comment by sandywater** [comment]
@SkyLothar this is awesome. Thank you!! :+1:

**Comment by urbaniak** [comment]
Are there plans integrating gitlab auth into sentry?

**Comment by dcramer** [comment]
@urbaniak no official plans today

**Comment by amartinz** [comment]
any updates on this one?

would like to see it officially supported.

**Comment by dcramer** [comment]
Closing this out as we have no intention to support more providers for SSO. GitHub is already a questionable mistake and we’re noy going to dig ourselves even deeper in the hole. 

You should use something like G Suite or SAML for proper authentication.

**Comment by amartinz** [comment]
Too bad, we are using a self hosted GitLab instance a SSO provider for everything internal development related as "proper authentication" method (whereas i do not see G Suite as a proper authentication method if i do not want to leak any information to the outside or pay for external temporary people to get access).

Thank you really much, @SkyLothar for your effort! :)

**Comment by dcramer** [comment]
@amartinz SSO is more then just authentication. Most major organizations either use G Suite (nearly all modern SV tech companies) or SAML to achieve these compliance concerns. Google doesn't quite provide all of the features, but it **does** provide a high degree of security. I dont feel like writing up an essay on why this is more than an opinion, but even just understanding (googling) how SAML providers work will help you understand why GitHub/GitLab cannot be treated as real identity providers.
