### ISSUE TITLE
Preview attachments before downloading

### ISSUE THREAD

**Issue by andrewlvovsky** [getsentry/sentry#23041]
## Summary

We would love the ability to preview attachments without having to download them. For example, when a user sends in feedback, a screenshot is captured and attached alongside that report. We would like to view the image directly, and even possibly forward it through integration with something like Slack.

## Motivation

This will save time and disk space for developers.

**Comment by borninla** [comment]
bump to avoid staleness

**Comment by sklibanov312** [comment]
Bump to bring this back to life?

**Comment by sklibanov312** [comment]
Looks like this can be closed. I can click the preview button on an attachment tagged with (for example) the image/png mime type and it shows the aforementioned screenshot.
