### ISSUE TITLE
In  GitLab Integrations, I can't see Code Mappings tab

### ISSUE THREAD

**Issue by cjk87927** [getsentry/sentry#23047]
- Sentry version: 21.1.0.dev0c3eba3c
- GitLab version: 12.6.2 

I'm already turn on the 'Early Adopter'
![image](https://user-images.githubusercontent.com/6744728/104427864-ba23fd00-55be-11eb-8af4-18dd960b79b7.png)
![image](https://user-images.githubusercontent.com/6744728/104427957-d1fb8100-55be-11eb-8a52-f1e9c8d9b0ce.png)

**Comment by MeredithAnya** [comment]
hi @cjk87927, since you are using on-prem you can actually just set the following flag:

```python
"organizations:integrations-stacktrace-link": True
```

**Comment by cjk87927** [comment]
Thank you, I have configured it, but where can I see the source code?
![image](https://user-images.githubusercontent.com/6744728/105817395-83071000-5ff0-11eb-8358-b2f0aa2bc48a.png)
![image](https://user-images.githubusercontent.com/6744728/105817528-b053be00-5ff0-11eb-8118-d92870ebce08.png)

**Comment by manuzope** [comment]
Ah, I think this is because the SDK doesn't send the source context. Until then, you won't be able to see the source code. Stacktrace linking allows you to link to Github/Gitlab only if we already have the source context.

I'd follow this issue: https://github.com/getsentry/sentry-java/issues/633.

**Comment by fmiqbal** [comment]
> hi @cjk87927, since you are using on-prem you can actually just set the following flag:
> 
> ```python
> "organizations:integrations-stacktrace-link": True
> ```

why this is behind feature flag anyway ? any docs about each of the feature behind "disabled" feature flag ?

**Comment by hubertdeng123** [comment]
I'd have to ask the @getsentry/issues team for more information on why the feature is behind a feature flag still.

**Comment by malwilley** [comment]
@fmiqbal thanks for bringing this up. I don't think we have a good reason to keep this flag around, it was something that was lost in the shuffle. I've created this issue to track that work: https://github.com/getsentry/sentry/issues/56416

And since this particular issue has been long resolved, I'll close it.
