### ISSUE TITLE
Proxy solution

### ISSUE THREAD

**Issue by hyperknot** [getsentry/sentry#23054]
## Summary

Sentry Javascript is broken as of today for all users with adblockers using EasyList Privacy (I think many of them do). https://github.com/getsentry/sentry-javascript/issues/2916

Adding a way to proxy requests through custom domains is needed to fix this.

Question: can a simply nginx rule be able to fullfill this? Nginx is perfectly capable of doing forward hosting, it's just not advertised.
https://stackoverflow.com/a/46083709
https://stackoverflow.com/questions/41493170/nginx-forward-requests-to-another-proxy
https://github.com/kawanet/nginx-forward-proxy/blob/master/etc/nginx.conf

The problem is that nginx doesn't support (at least as of 2009) SSL proxying:
https://superuser.com/questions/604352/nginx-as-forward-proxy-for-https

**Comment by hyperknot** [comment]
A potentially much simpler solution would be if we could use a subdomain + CNAME records, that way we wouldn't need nginx hacks.

For example mysentry.mydomain.com could have a CNAME of ingest.sentry.io and then the blockers wouldn't work. This would be by far the easiest solution, but I guess you'd probably need to make changes so that the CNAME-ing works correctly.

**Comment by wilerson** [comment]
+1 on adding a subdomain + CNAME record option - considering the [feedback](https://github.com/easylist/easylist/issues/6963#issuecomment-759336749) given, it is unlikely that EasyList changes this.

One hurdle to this option would be that the organization would need to provide Sentry with an SSL certificate.

**Comment by untitaker** [comment]
You can use CNAME, nginx or [relay](docs.sentry.io/product/relay/) for this, the latter will also help with response speed.

**Comment by untitaker** [comment]
@hyperknot ublock has cname uncloacking btw

**Comment by hyperknot** [comment]
@untitaker thanks for the relay link, I didn't know about it. Can you share the most minimal configuration needed for this use case? Do I understand right that the default config with mode: proxy in Docker would be fine? It'd be behind NGINX so no need for TLS handling.

**Comment by untitaker** [comment]
Yeah [proxy mode](https://docs.sentry.io/product/relay/modes/#proxy-mode) is fine.

**Comment by untitaker** [comment]
In terms of what was requested within this issue I think we already have Relay... adblocking and particularly EasyList continue to be an issue.

**Comment by fprochazka** [comment]
I had the same problem and as adviced, I've deployed relay in proxy mode and so far it works great. Thank you for awesome service!
