### ISSUE TITLE
Can only Select Checkboxes on Current Page

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#2306]
From a support request:

> When trying to mark all events as resolved, using the select all checkbox only checks the boxes currently displayed, not the ones on the following pages. There appears to be no way to mark the thousands of past events as resolved.

We should probably add a button to resolve all.

**Comment by dcramer** [comment]
@mitsuhiko select all already implies this behavior via the modal (if you check all items on the page, and click resolve, it asks if you want to resolve all)
