### ISSUE TITLE
Fix padding around "More Details" on group tags view

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2307]
![image](https://cloud.githubusercontent.com/assets/2153/11152082/8ca90a78-89fe-11e5-8032-a75011773de1.png)

**Comment by ckj** [comment]
Oh, this was supposed to be a button. Fix incoming.

![screen shot 2015-11-13 at 11 31 21 am](https://cloud.githubusercontent.com/assets/30713/11155430/486a4eca-89fa-11e5-960b-e69bd4881537.png)
