### ISSUE TITLE
Differentiate 'bad data' vs 'you captured an error' error labels

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry#23112]
This is a transaction with an associated error

<img width="994" alt="Screenshot 2021-01-15 at 11 45 30" src="https://user-images.githubusercontent.com/5731772/104715973-831d2b00-5727-11eb-899f-07f925c53136.png">

This is an event error that had ingestion errors because of bad data.

<img width="1032" alt="Screenshot 2021-01-15 at 11 46 58" src="https://user-images.githubusercontent.com/5731772/104715996-89130c00-5727-11eb-8611-b8fd0ed9028d.png">

My first thought was, I sent a transaction but I messed up something, not sure if it's just me, but I'd prefer a different look & feel for bad data vs you captured an error in your App.

**Comment by jennmueng** [comment]
Ran into this as well with a transaction from RN, confused me for a second.

**Comment by chadwhitacre** [comment]
Triaging as on hold based on @bruno-garcia's emoji. :)

**Comment by leeandher** [comment]
The new UI for processing errors should hopefully clear this up, to access the new UI see [this discussion](https://github.com/getsentry/sentry/discussions/80801)
