### ISSUE TITLE
Resolve All and Filtered Search can Lead to UI Failure

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#2312]
From a support ticket:

> I just accidentally resolved all the issues in my entire app due to what seems like poor UX.
>
> I searched for 2 specific issues I wanted to resolve, checked their boxes and then clicked the check mark to resolve.
>
> When it asked me if I wanted to resolve all incidents, I assumed it meant all 1000+ instances of the 2 incidents I had selected. I would not expect it to operate on any incidents that were not visible in the UI.

This happens because I assume the dialog triggers when you select all visible issues, but the resolve all does not take into account the current query.  That dialog should probably not come up unless the filter is empty or the resolve should take the filter into account.

**Comment by dcramer** [comment]
Going to change this to be more gmail-esque:

- Add a "Resolve entire project" action
- Remove the "apply to all results" action
