### ISSUE TITLE
API: Add "tags" query parameter for filtering org and project event counts

### ISSUE THREAD

**Issue by samgre** [getsentry/sentry#23158]
## Summary

Add the ability to retrieve event counts histogram for project and organisation, filtered by tags.

## Motivation

We would like to track error rates by a component and feature area that are tagged accordingly in our dashboard. This way we can immediately identify which components have elevated error rates in our dashboard and triage resolving the issue to the right persons.

## Additional Context

https://docs.sentry.io/api/organizations/retrieve-event-counts-for-an-organization/
https://docs.sentry.io/api/projects/retrieve-event-counts-for-a-project/

**Comment by BYK** [comment]
@manuzope this is also partly @getsentry/sns, right?
