### ISSUE TITLE
Rate Limits don't have any effect on on-prem Sentry 20.10.1

### ISSUE THREAD

**Issue by roman-stelmakh-emesa** [getsentry/sentry#23161]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 20.10.1

## Description

Rate limits configured on the organisation settings as well as rate limits on DSN keys don't have any effect.
After we set 10.000 event per hour for the entire organisation, the real number of processed events remains still higher than 60.000. The same result for rate limits on DSN keys.

## Steps to Reproduce

1. Settings -> Rate limits -> Account Limit
2. Settings -> Projects -> [some project] -> Client Keys (DSN) -> Configure -> Rate Limit

**Comment by BYK** [comment]
@untitaker @jan-auer is `relay` enforcing these or something else? If it is `relay`, any idea why this might be happening?

**Comment by untitaker** [comment]
rate limits are configured in relay, yes. they are stored in redis, so if redis loses data you will observe effective rate limit resets

**Comment by BYK** [comment]
@roman-stelmakh-emesa does @untitaker's answer help you? Could you be experiencing issues with Relay or Redis?

**Comment by caseyduquettesc** [comment]
I am on 20.12.1 and after yesterday's android webview crashes it became apparent that the project rate limits (which I expected not to work w/ relay) and the system rate limits no longer apply. I had a 5K system rate limit, which I reduced to 1K, but 200/s are still being accepted. I've had to resort to disabling offending project keys in order to restrict the number of events entering ingestion.

**Comment by Antiarchitect** [comment]
Seems same picture for me. Limits for one of my noisy projects do not apply.

**Comment by BYK** [comment]
@Antiarchitect, you mentioned "BTW I do not use built-in Nginx if that matters." which may be the source. We cannot speculate on why something is not working on non-standard setups (seems like you are using the k8s chart).

**Comment by Antiarchitect** [comment]
It would be nice to know where these limits actually applied. I've searched built-in nginx chart and config and didn't find any clue about sentry rate limiting.

**Comment by Antiarchitect** [comment]
Anyway I will check twice by disabling the key (seems I have now couple of hours processing log) when the project will stop receive new events completely and the old once are processed I will enable the key once again and watch if the limits are applied.

**Comment by BYK** [comment]
@Antiarchitect does this help: https://github.com/getsentry/sentry/issues/23161#issuecomment-763126097

**Comment by Antiarchitect** [comment]
> @Antiarchitect does this help: [#23161 (comment)](https://github.com/getsentry/sentry/issues/23161#issuecomment-763126097)

Seems not as I updated limits recently. I Will update on this tomorrow

**Comment by Antiarchitect** [comment]
According to this: https://github.com/getsentry/sentry/blob/4f0048019a6f552935a371060b6759637cacfb9b/src/sentry/ratelimits/redis.py
I should have keys starting with `rl:` but 
```
127.0.0.1:6379> KEYS *rl:*
(empty list or set)
```

**Comment by Antiarchitect** [comment]
Possibly I found the solution for Sentry Helm Chart case. It appears by default relay is working in proxy mode. In order to change that you should just configure the chart properly:

```
relay:
  mode: managed
```
It seems it autoregister itself in a while.

**Comment by jan-auer** [comment]
Thanks, this is definitely the issue. Internal Relays used for event ingestion in a Sentry setup *must* be in managed mode. More importantly, "processing" must be enabled like [here](https://github.com/getsentry/onpremise/blob/662a773e57dbae037ef095af588617f0c23cf4af/relay/config.example.yml#L7-L13):

```yaml
processing:
  enabled: true
  kafka_config:
    - {name: "bootstrap.servers", value: "kafka:9092"}
    - {name: "message.max.bytes", value: 50000000} #50MB or bust
  redis: redis://redis:6379
  geoip_path: "/geoip/GeoLite2-City.mmdb"
```

For the curious, we have a high-level chart of event ingestion architecture in our [developer documentation](https://develop.sentry.dev/architecture/) with links to relevant further information.

---

For future visitors of this issue: We provide an official setup of Sentry over at https://github.com/getsentry/onpremise. This configuration is tested and continuously updated with every required configuration to support all product features. 

Please call out if you are _not_ using the standard setup. It is hard for us to guess when an inofficial setup may be missing required configuration and makes it more complicated to provide you with help.

**Comment by caseyduquettesc** [comment]
Thanks @jan-auer. My issue was the `redis: ` config was not nested under `processing:` 😅
