### ISSUE TITLE
Latest JavaScript Loader is Loading 6.x JS that Returns 403

### ISSUE THREAD

**Issue by rtymchyk** [getsentry/sentry#23168]
## Important Details
JS Loader

## Steps to Reproduce
Use the JS loader script on a page, and in project settings set to use latest version. Trigger an error on the page to cause the full sentry bundle to load. This will cause https://browser.sentry-cdn.com/6.0.0/bundle.min.js to get requested, but that fails with 403 status code.

### What you expected to happen
https://browser.sentry-cdn.com/6.0.0/bundle.min.js should return 200.

**Comment by HazAT** [comment]
@rtymchyk Thanks, we are looking into it right now.

**Comment by HazAT** [comment]
@rtymchyk Should be resolved now, sorry for the inconvenience.
