### ISSUE TITLE
not-set: cross-origin-opener-policy

### ISSUE THREAD

**Issue by sdsBG** [getsentry/sentry#23167]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version Sentry 20.10.178833d9

## Description

Tried to install JIRA Cloud Sentry Add-On. Got block by sentry.io

sentry.io ist gesperrtsentry.io hat die Verbindung abgelehnt.
ERR_BLOCKED_BY_RESPONSE

X-XSS-Protection: 1; mode=block
not-set: cross-origin-opener-policy

This document was blocked from loading in an iframe with a sandbox attribute because this document specified a cross-origin opener policy.

## Steps to Reproduce

1. Install Jira Integration in Sentry
2. Got forwarded by the integration to Atlassian Marketplace
3. Install the app and click on configure in JIRA Cloud
4. forwarded to `https://sentry.io/extensions/jira/configure/?signed_params=<<a_token>>`
5. blocked by sentry.io

### What you expected to happen

Successful configuration of integration

![111](https://user-images.githubusercontent.com/13250850/105066666-521e5c80-5a7f-11eb-809e-5fbef5bb0e2a.png)
![222](https://user-images.githubusercontent.com/13250850/105066672-521e5c80-5a7f-11eb-97ac-6097d0cb594e.png)

**Comment by manuzope** [comment]
Hey @sdsBG, the Sentry <> JIRA integration on the JIRA marketplace is for sentry.io. Given that you're on prem, here's how you can install the JIRA integration: https://develop.sentry.dev/integrations/jira/.

That should not direct you to sentry.io. Mind giving that a try?

**Comment by sdsBG** [comment]
Hey @manuzope,
holy crap! Sorry, yeah you're right.

I made it with the on prem add-on.

Thank you
