### ISSUE TITLE
Twilio Integration doesn't allow sending to non-US numbers

### ISSUE THREAD

**Issue by danielthedifficult** [getsentry/sentry#23183]
Hello team,
![image](https://user-images.githubusercontent.com/1290033/105198950-83119680-5b3e-11eb-9845-324d6e55bfa5.png)

Per this screenshot, it seems you are automatically adding +1 to the "SMS From #*" field when validating the form.

It would be ideal if we could use EITHER a [Twilio Messaging service sid](https://www.twilio.com/docs/messaging/services) OR any valid phone number registered in our Twilio account, including non-US numbers.

**Comment by danielthedifficult** [comment]
Hello team and @manuzope,

Any ideas about this? I glanced through the Twilio integration code myself, as I would have been happy to fix it, but I didn't see exactly where this was happening, and I'm not familiar with the codebase at all.

**Comment by manuzope** [comment]
Hi @danielthedifficult, apologies for the late response. 

Hmmm, pretty sure the plugin does support international numbers ([code](https://github.com/getsentry/sentry/blob/master/src/sentry_plugins/twilio/plugin.py#L28-L44)). I think it should work if you add the country code. Is that not what you're seeing?

**Comment by danielthedifficult** [comment]
Sorry, I mi-labeled the title of the issue.

It doesn't support sending TO international numbers.

I've now found the issue- the phonenumbers library doesn't use the "DEFAULT_REGION" as a suggestion, it uses it as a 'mandate' to return a phone number formatted with that.

Maybe you could check for the presence of a  "+" sign at position 0 in the string, and if so, do not pass the second parameter. In that case, international numbers would not be parsed with US formatting.

Screenshot of the error in question attached.

![image](https://user-images.githubusercontent.com/1290033/110828382-46892e00-8297-11eb-8a9f-3ec91c5d23e9.png)

**Comment by manuzope** [comment]
I see. And what happens if the `SMS To #s` has the country code? (`+33` in your case I believe)?

**Comment by danielthedifficult** [comment]
Good news, I guess: if the FROM number is a US number, the international TO number works.
