### ISSUE TITLE
Class UserFeedback do not exist

### ISSUE THREAD

**Issue by edwinkkh** [getsentry/sentry#23180]
## Important Details

How are you running Sentry?

Android Studio, kotlin version 1.3.72-release-Studio-4.1-5
## Description

I am trying to invoke the captureUserFeedback method but it does not exist.

## Steps to Reproduce

1. Add sentry implementation in build.gradle
2. Update AndroidMainfest xml
3. Call Sentry.captureUserFeedback(“")

Good items to include here include:
![config](https://user-images.githubusercontent.com/14085719/105161254-20bf9280-5b4c-11eb-9eee-1239dc842988.png)
![capture feedback](https://user-images.githubusercontent.com/14085719/105160905-bc9cce80-5b4b-11eb-923e-287002d0d63b.png)

![build](https://user-images.githubusercontent.com/14085719/105160970-d0e0cb80-5b4b-11eb-9b71-6dfd223e2029.png)

### What you expected to happen

Able to call the Sentry.captureUserFeedback successfully 

### Possible Solution
NIL

**Comment by BYK** [comment]
@bruno-garcia looks like this is a Java SDK issue?

**Comment by bruno-garcia** [comment]
@edwinkkh This feature was introduced on [version 3.1.2](https://github.com/getsentry/sentry-java/releases/tag/3.1.2). Please upgrade the SDK, the latest stable is 3.2.1.
