### ISSUE TITLE
Slack Integration: Cannot authenticate app

### ISSUE THREAD

**Issue by nodomain** [getsentry/sentry#23201]
After setting up Sentry with https://github.com/Rungutan/sentry-performance-monitoring  I try to add a Slack integration. However after click on "Add workspace" I end up with this popup:
![image](https://user-images.githubusercontent.com/104389/105246536-b1f62f80-5b73-11eb-8142-617f3ee650c0.png)

Somehow the client_id is missing and also the other url params.

Thanks for an advise.

**Comment by BYK** [comment]
Sounds like you need to follow https://develop.sentry.dev/integrations/slack/?

**Comment by nodomain** [comment]
How embarrassing. Works now. Thanks!
