### ISSUE TITLE
"Search by Trace" disabled but not hint as to why

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#23224]
Loading a transaction on an org that does not have a team plan (assumption) shows a UI element without information as to why is disabled.

## Steps to Reproduce

1. Load Performance tab
2. Select a transaction
3. Select one of the events
4. Select one of the spans
5. Hover over the button "Search by Trace"

**Expected results:** I get some info as to why it is disabled
**Actual results:** I don't get any information
**Possible Solution:** Give some information as to why it's disabled.

@dashed @markstory Alberto, Mark, CCing you since you were both involved in [the original implementation](https://github.com/getsentry/sentry/pull/19078).

![image](https://user-images.githubusercontent.com/44410/105407051-39d34c80-5bfb-11eb-9163-5bdb3f540f9a.png)

**Comment by Reedham20** [comment]
Hey is this still open?

**Comment by armenzg** [comment]
The UI has changed and it seems to be highlighted:

<img width="630" alt="image" src="https://user-images.githubusercontent.com/44410/142653421-0c54111b-f9c0-4cc8-8d5b-bb886e7590cf.png">

Let's close it and if someone can reproduce it we can re-open it.
