### ISSUE TITLE
Feature Request: Set a theme-color via meta-tag or manifest

### ISSUE THREAD

**Issue by frame** [getsentry/sentry#23289]
### Summary

Setting a theme-color via meta-tag or manifest would make the "PWA" version of Sentry to match the color-scheme of Sentry itself.

### Motivation

When users run Sentry as PWA, the theme-color (title bar and background of the favicon) gets automatically defined by the browser, which is red in my MS Edge version (I suspect this might differ depending on the browser). Setting a theme-color `<meta name="theme-color" content="#452650">`, would make the window look much nicer. (see screenshot of the current red situation)

### Additional Context

The actual colour could maybe get populated by the color-scheme itself or accept a setting via `config.yml`. The colour can get set via `theme-color` meta-tag or `manifest.js`

![capture_20210125_131837](https://user-images.githubusercontent.com/339569/105705794-f3d6fb00-5f10-11eb-9d3e-a9ee1098a99a.png)

I'm currently using a workaround to inject the appropriate header tag at my proxy server (but this also disables compression)

```
<location />
    ProxyPass […]
    ProxyPassReverse […]
    RequestHeader unset Accept-Encoding
    AddOutputFilterByType SUBSTITUTE text/html
    Substitute "s|</head>|<meta name=\"theme-color\" content=\"#452650\"></head>|ni"
</location>
```

### References

- https://developer.mozilla.org/en-US/docs/Web/Manifest
- https://developer.mozilla.org/en-US/docs/Web/Manifest/theme_color
- https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps

**Comment by billyvg** [comment]
Thanks @frame!

Closed by https://github.com/getsentry/sentry/pull/23675
