### ISSUE TITLE
Vercel integration - error

### ISSUE THREAD

**Issue by sushilbansal** [getsentry/sentry#23284]
I am trying to integrate sentry.io with Vercel as explained in the docs: https://docs.sentry.io/product/integrations/vercel/

and got the attached error. Removed the integration multiple times and tried to add again. The same error.
![Screenshot 2021-01-24 at 13 42 03](https://user-images.githubusercontent.com/6096693/105632338-7052d680-5e4a-11eb-9036-cb1310c07f88.png)

**Comment by BYK** [comment]
Can you please provide the information we request on the issue template? Otherwise this issue is not actionable.

**Comment by sushilbansal** [comment]
Apologies if something was not clear. I am not using cli; rather using Integration. Steps to replicate:
1) goto the link: https://docs.sentry.io/product/integrations/vercel/
2) from the above link it provides another link for Sentry integration on vercel platform: https://vercel.com/integrations/sentry
3) Click on Add button (which is on right hand side)
4) It will show: Install Sentry popup (as shown in the above image)
5) Select the eitther option: All Projects, Specific Projects
6) Click on Install
You will see the Error in the original post. If you close it and go back to Vercel integrations then you will see the below error:
![Screenshot 2021-01-24 at 18 11 30](https://user-images.githubusercontent.com/6096693/105639354-bb331500-5e6f-11eb-9389-8733613d2795.png)
 
I removed the config and tried adding Sentry integration multiple times but did not succeed.

**Comment by BYK** [comment]
Hi, I'm not talking about the CLI. Is this Sentry.io or self-hosted Sentry? If it is self-hosted, we'd need the version you are using and the logs. If this is sentry.io, you may want to contact support first to let them check your account specifically.

**Comment by sushilbansal** [comment]
It is the Sentry.io integration. Not sure who built it and whether it is self hosted Sentry or not.

**Comment by BYK** [comment]
@sushilbansal then I strongly recommend [contacting our support](https://sentry.io/contact/support/). I'll keep the issue in the meantime and you can refer to this GitHub issue with your report.

**Comment by hydrosquall** [comment]
Hi @BYK, we're running into the same issue for our site nycvaccinelist.com tonight , using Sentry.io. 

https://a.cl.ly/nOulBNdm

Came across this page in official docs ( https://develop.sentry.dev/integrations/vercel/ ), not sure if this was also needed to set up the app, or if we should be able to use the one from the marketplace directly.

**Comment by BYK** [comment]
@hydrosquall - @getsentry/ecosystem can help answer that I think :)

**Comment by MeredithAnya** [comment]
@sushilbansal A fix for this was deployed today, you should be able to install Vercel successfully now via the steps you outlined.

**Comment by hydrosquall** [comment]
@BYK thanks for the response, I think that might be a private link. Let me know if there's anything else I should do.

**Comment by BYK** [comment]
@hydrosquall it just pinged the relevant team and @MeredithAnya answered above :) I think this should be fixed now, can you verify?

**Comment by fabien-h** [comment]
![Screenshot 2021-02-12 at 13 58 54](https://user-images.githubusercontent.com/2682701/107771040-7ac20b00-6d3a-11eb-91e6-3f9700f441ea.png)

I have a `Warning: Failed to fetch` error instead of the network error. Bu I guess they are similar.

Found a way to fix this ?

**Comment by hydrosquall** [comment]
@BYK we were unsuccessful, so we switched to a different error tracker. Support team recommended that we turn off adblocker, and share a picture/URL of the network tab/console (not posting here in case credentials are sensitive). We noticed that `undefined` was appearing in the URL though.

We had the same error screen as @fabien-h, maybe try removing adblock / seeing what messages appear in your network tab/console too.

**Comment by manuzope** [comment]
Hey @fabien-h, just did a quick test and I get the `Failed to fetch` too when I have uBlock Origin installed and things work fine if I disable it. As @hydrosquall said, for now, the workaround is to disable adblock to view that page on Vercel.

You can find more details about it being blocked here: https://github.com/easylist/easylist/issues/6963, if interested.

**Comment by fabien-h** [comment]
@hydrosquall & @manuzope thank you very much for your quick answer. You are right adblock was the culprit.

**Comment by manuzope** [comment]
Hey, going to close this out cause from what I can tell, things seem to be fixed. Please let me know if that's not the case for anyone and I'll reopen.
