### ISSUE TITLE
Jira Integration: Unable to configure on JIRA cloud after installation

### ISSUE THREAD

**Issue by clinejj** [getsentry/sentry#23293]
We recently tried installing the [JIRA Marketplace add-on](https://marketplace.atlassian.com/apps/1219432/sentry-for-jira?hosting=cloud&tab=overview), and after visting the post-install URL (`plugins/servlet/ac/sentry.io.jira/post-install-sentry`) it hangs on loading and nothing else happens. I have tried uninstalling and reinstalling but am unable to get to the configuration for the app.

**Comment by markstory** [comment]
Are you installing the addon to an organization in sentry.io or a self-hosted sentry?

**Comment by clinejj** [comment]
An organization in Sentry.io. I fixed the issue, my adblocker (Ublock Origin) was blocking the Sentry iframe from loading in the marketplace 🤦🏻‍♂️
