### ISSUE TITLE
AttributeError /api/0/organizations/{organization_slug}/sentry-apps/

### ISSUE THREAD

**Issue by nodomain** [getsentry/sentry#23290]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, Sentry 21.1.0486d790, based on https://github.com/Rungutan/sentry-performance-monitoring

## Description

Opening of these sub items in "Organization" settings fails:
* Audit Log
* Integrations
* Developer settings

This seems to be the resulting issue in the "Internal" Sentry project:
```
AttributeError: 'NoneType' object has no attribute 'get_allowed_origins'
  File "sentry/api/base.py", line 124, in handle_exception
    response = super(Endpoint, self).handle_exception(exc)
  File "rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "sentry/api/base.py", line 237, in dispatch
    response = handler(request, *args, **kwargs)
  File "sentry/api/bases/sentryapps.py", line 59, in wrapped
    return func(self, *args, **kwargs)
  File "sentry/api/endpoints/organization_sentry_apps.py", line 19, in get
    on_results=lambda x: serialize(x, request.user, access=request.access),
  File "sentry/api/base.py", line 330, in paginate
    results = on_results(cursor_result.results)
  File "sentry/api/endpoints/organization_sentry_apps.py", line 19, in <lambda>
    on_results=lambda x: serialize(x, request.user, access=request.access),
  File "sentry/api/serializers/base.py", line 45, in serialize
    return [serializer(o, attrs=attrs.get(o, {}), user=user, **kwargs) for o in objects]
  File "sentry/api/serializers/base.py", line 45, in <listcomp>
    return [serializer(o, attrs=attrs.get(o, {}), user=user, **kwargs) for o in objects]
  File "sentry/api/serializers/base.py", line 60, in __call__
    return self.serialize(obj, attrs, user, **kwargs)
  File "sentry/api/serializers/models/sentry_app.py", line 31, in serialize
    "allowedOrigins": obj.application.get_allowed_origins(),
```

Last SQL before exception

```
SELECT "sentry_organization"."id", "sentry_organization"."name", "sentry_organization"."slug", "sentry_organization"."status", "sentry_organization"."date_added", "sentry_organization"."default_role", "sentry_organization"."flags" FROM "sentry_organization" WHERE "sentry_organization"."id" = %s
```

### What you expected to happen
Menus should work.

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by BYK** [comment]
I am unable to reproduce this issue with the latest nightly using getsentry/onpremise repo. You may want to file this issue under https://github.com/Rungutan/sentry-performance-monitoring

**Comment by nodomain** [comment]
Steps to reproduce. I had luck and could reproduce it on my staging environment. 
- create a internal integration e.g for Sentry CLI, just use the default rights needed for CLI access like described in the docs. 
- go to admin - users. 
- delete the cli user from there and check „delete user and all data“
- Go to one of the mentioned menu items and you will get the exception. 

In my case I deleted the cli user because I wanted to create a new one. 
Please fix this, since I am unable to use the menu items mentioned anymore.

**Comment by nodomain** [comment]
Shall I create a new issue or are you opening it again @BYK?

thx.

**Comment by nodomain** [comment]
Needless to say I broke my staging environment now as well 😂

**Comment by BYK** [comment]
Added the needs more info flag so that I don't forget to verify this.

**Comment by nodomain** [comment]
Appreciated 🍻

**Comment by nodomain** [comment]
Sending you some links to the issues on our system, please keep them non-public.

**Comment by BYK** [comment]
@nodomain can you verify that the fix works for you? You can try it by setting your `SENTRY_IMAGE` env var to `us.gcr.io/sentryio/sentry:cdb476bbd714e3eacb1d20aa185c0aa43184e61c`

**Comment by nodomain** [comment]
Looking into it tomorrow morning! Thx for the quick fix.

**Comment by nodomain** [comment]
I verified locally that this fixes my original issue. Fine to merge from my perspective :)

However, I found that the deletion of the user does not show up in the audit log.

**Comment by BYK** [comment]
>However, I found that the deletion of the user does not show up in the audit log.

That's for another day 😀  //cc @armenzg
