### ISSUE TITLE
Enforce python compatibility at install time

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2330]
We only support python 2.7 on anything non-Windows.

https://github.com/getsentry/sentry/commit/c7d1c38a977e0361c26cc0ecfed1ba32673c6954 is a first step in enforcing python 2.7 inside setup.py, but we also support wheels.

We need to compile a python 2.7 specific wheel, and potentially give it a qualifier to only work on non-Windows.

Wheel sorta supports these qualifiers: https://www.python.org/dev/peps/pep-0425/

**Comment by dcramer** [comment]
We don't even support wheels. Not sure if this really matters. People can just read the docs where we clearly say "PYTHON 2.7".

**Comment by mattrobenolt** [comment]
Sure we do: https://pypi.python.org/packages/py2.py3/s/sentry/sentry-7.7.4-py2.py3-none-any.whl

There's no reason not to. They build fine.

**Comment by dcramer** [comment]
I guess I didn't realize we were uploading wheels at all.

Anyways, this is a nice to have, and I dont think its worth spending time on. People rarely have a problem here.
