### ISSUE TITLE
Detect when session has expired

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2331]
In a long running browser session, at some point, a user's session can be expired causing them to be logged out. Whether from the cookie itself expiring, or another window that explicitly logged them out.

We should detect this and say, "Hey, log back in." or something akin to that.

The two best approaches that we quickly thought of were:

* Periodically ping a `/session` endpoint to check the current status of their session. This isn't perfect since there's still a margin of error between pings, depending on our frequency.
* Detect the first 401 response for not being logged in, and prompt at the time of failure. This isn't perfect either since it requires an action to be made before the user knows.

I don't think there's a way we can do this in 100% realtime, so we'll need to pick which works best for us.

**Comment by Stayallive** [comment]
![image](https://cloud.githubusercontent.com/assets/1090754/11497074/cabfffa8-9816-11e5-8aac-555888406a05.png)

I think that for people having Sentry open in a background tab the /session ping would be soon enough, and people that are working (don't time out) are doing actions and causing a 401 maybe. To make it even a bit better you could store a session expire time (which is conveyed to the front-end via header) and ping after that time has passed to, this could make it a bit more reliable.

You could also postpone the ping if the last action was less then the ping time ago maybe even... (to prevent lot's of ping/pong actions)

Just my 2 cents :)
