### ISSUE TITLE
cannot see my project(s) when linking gitlab issue

### ISSUE THREAD

**Issue by tibz7** [getsentry/sentry#23328]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

gitlab integration is well configured and I added few repositories under the given group.
When I click on linking gitlab issue, i see only 1 project, which is not even in the list of my repositories!

## Steps to Reproduce

1. configure gitlab + sentry
2. add repository
3. try to link an issue 

### What you expected to happen
see my repositories/projects when I want to link an issue

**Comment by BYK** [comment]
@getsentry/ecosystem @manuzope ping? :)

**Comment by tibz7** [comment]
figured out that the input for the project allows you to search... so this
is how i fixed it .also something changed, and now i can see the projects.
so you can close this. thank you for your care!

**Comment by BYK** [comment]
@tibz7 glad to hear it was resolved and sorry we couldn't get to this before our holy bot reaped it. Working on our response times and appreciate your kind response :)
