### ISSUE TITLE
Search bar: possible to autocomplete mismatched tag value

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2332]
To reproduce:

* Type out a tag, e.g. level:
* Wait for "all" tag values to load and display in search bar
* Quickly type out the value of the 2nd item without pausing typing and press enter (to submit search)
* Result: search bar will replace your text with value of **1st** autocomplete item, regardless of whether it is a substring match

This is because we only filter autocomplete items after typing has paused for 500ms. Even in cases where the user "beats" the debounce, we shouldn't choose a value that isn't a substring match.

https://sentry.zendesk.com/agent/tickets/1077

**Comment by dcramer** [comment]
GH-2024
