### ISSUE TITLE
Double hostname on redirect_uri query param for SlackIntegrationProvider

### ISSUE THREAD

**Issue by daniel5gh** [getsentry/sentry#23365]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 20.12.1

## Description

We try to add a slack integration.

Followed the guide to create a slack app, configure the credentials (client id, client secret and signing secret).

Then when pressing Add Workspace, we get an error 500 from slack. But we expect a page on slack where we can give the bot permissions followed by completion of the integration on the sentry end.

## Steps to Reproduce

1. Follow https://develop.sentry.dev/integrations/slack/ - there are slight differences with slack UI since this guide had been created, it is still self-explanatory and doesn't look like anything major. It was a little bit unclear if the `links:read` scope needs to be added to bot scope or user scope. We added it to user scope, and added [these 11 other](https://github.com/getsentry/sentry/blob/20.12.1/src/sentry/integrations/slack/integration.py#L92) scopes to the bot user, just to be sure.
2. Browse to https://sentryhostname/settings/org/integrations/slack/ click the configuration tab and click "Add Workspace" button.
3. Observe a popup browser window with an error 500 from slack.

The requests on the popup window (omitting any JS and other static content) are as follows:

 * https://sentryhostname/organizations/org/integrations/slack/setup/? -> 302
 * https://slack.com/oauth/v2/authorize?client_id=XXX&response_type=code&scope=groups%3Aread+im%3Ahistory+chat%3Awrite+chat%3Awrite.customize+links%3Aread+im%3Aread+links%3Awrite+chat%3Awrite.public+channels%3Aread+users%3Aread+team%3Aread&state=XXX&redirect_uri=sentryhostname%2Fsentryhostname%2Fextensions%2Fslack%2Fsetup%2F&user_scope=links%3Aread -> 200 (some tracking and a JS based redirect to next)
 * https://slack.com/oauth/v2/authorize?client_id=XXX&response_type=code&scope=groups%3Aread+im%3Ahistory+chat%3Awrite+chat%3Awrite.customize+links%3Aread+im%3Aread+links%3Awrite+chat%3Awrite.public+channels%3Aread+users%3Aread+team%3Aread&state=XXX&redirect_uri=sentryhostname%2Fsentryhostname%2Fextensions%2Fslack%2Fsetup%2F&user_scope=links%3Aread&tracked=1 -> 302
 * https://teamname.slack.com/oauth?client_id=XXX&scope=groups%3Aread+im%3Ahistory+chat%3Awrite+chat%3Awrite.customize+links%3Aread+im%3Aread+links%3Awrite+chat%3Awrite.public+channels%3Aread+users%3Aread+team%3Aread&user_scope=links%3Aread&redirect_uri=sentryhostname%2Fsentryhostname%2Fextensions%2Fslack%2Fsetup%2F&state=XXX&granular_bot_scope=1&single_channel=0&install_redirect=&tracked=1&response_type=code&team= -> 500

No relevant logs or config on sentry. The `slack.*` options are set in `config.yml` and while creating the app slack verified it was able to connect to the event endpoint.

### What you expected to happen

We expect a page on slack where we can give the bot permissions followed by completion of the integration on the sentry end

### Possible Solution

We noticed the double hostname on the `redirect_uri`:
```
redirect_uri=sentryhostname%2Fsentryhostname%2Fextensions%2Fslack%2Fsetup
```

This did not look good and we thought it might be causing the error 500 issue. We tracked this down to a double `absolute_uri`:

In `OAuthLoginView`
  1. https://github.com/getsentry/sentry/blob/20.12.1/src/sentry/identity/oauth2.py#L242 (this is the initial dispatch used by the first redirect on the setup endpoint mentioned above)
  2. https://github.com/getsentry/sentry/blob/20.12.1/src/sentry/identity/oauth2.py#L276

And the other one on the `SlackIntegrationProvider`: https://github.com/getsentry/sentry/blob/20.12.1/src/sentry/integrations/slack/integration.py#L114

It seems like the `redirect_url` key on the config on the `SlackIntegrationProvider` can be omitted altogether, since the [default](https://github.com/getsentry/sentry/blob/20.12.1/src/sentry/identity/pipeline.py#L38) when none is given is this `associate_url` which is the reverse of `sentry-extension-setup` with the right provider id (`slack`). Using the reverse is better than hardcoding the `"/extensions/slack/setup/"` anyway.

So, we made this change. It solved the double hostname, but alas it did not solve the error 500 on slack. What did solve this error 500 was to remove the `redirect_uri` completely. The slack docs state that it is [optional](https://api.slack.com/legacy/oauth#authenticating-users-with-oauth__redirect-uris) and when not provided, the URL configured on the slack app is used.

What's also interesting, is that it looks like this double `absolute_url` has been here for quite some time, but I could not find any reports of it not working... So if it was double all this time, and it did work that's strange because slack should not allow that redirect URI if people followed the (redirect URI part of) [Slack Setup Guide](https://develop.sentry.dev/integrations/slack/). And if they did not provide a redirect URI there, then the actual redirect would land back on sentry with a 404.

After hacking out the `redirect_uri` completely ([here](https://github.com/getsentry/sentry/blob/20.12.1/src/sentry/identity/oauth2.py#L230) and [here](https://github.com/getsentry/sentry/blob/20.12.1/src/sentry/identity/oauth2.py#L269)) and making sure the URI configured on the Slack App was correct, at this point we had a workspace added to our sentry, but it was not functional because we ran into the same that appears to be reported in https://github.com/getsentry/sentry/issues/23362

**Comment by daniel5gh** [comment]
We've again configured an integration like we did last time (hacking out the double `absolute_url`) and the integration works as expected, mostly. So I do suspect that the other issue I referenced was indeed also standing in our way.

But now that the integration works, it shows messages on slack, the titles are not hyperlinks. Interestingly they are also not hyperlinks in messages posted via the webhook by the legacy intergration.

We did check if we could send a message with a `title_link` manually using the same client secret that sentry uses. It works fine. So now we suspect that sentry is either not sending a `title_link` or that it maybe is malformed and slack is rejecting it. I just wanted to add this on this ticket, since it also involves URIs and perhaps the two issues are related somehow?

I am still surprised that nobody else noticed this double `absolute_url`, but I don't see how our configuration would be any different such that this becomes a problem only for us but nobody else.

If you want I could sketch up a PR to address the double `absolute_url`, but I'd need to know which location would be the one to keep. ie what component is ultimately responsible for making the URI absolute.

**Comment by MeredithAnya** [comment]
Hi @daniel5gh, a couple things: 

1. You are right about the docs being outdated, those were instructions to create what Slack calls their "classic bot" apps (now considered legacy), I've [updated the docs](https://develop.sentry.dev/integrations/slack/) to reflect the current way to set up their new granular bot apps (and this is what kind of app we use in Sentry.io). One thing to note, you can still use the `slack.verification-token` but the `slack.signing-secret` is preferred. I would recommend going through the steps and checking to see if your scopes that you set match the updated docs.

2. Testing out the Slack install flow locally, I'm not getting any double `redirect_uri`, I'm wondering what you have set for your `system.url-prefix` and if that could be the problem there. I'm pretty sure your issue has to do with [`urljoin`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urljoin), mine locally is set to `https://meredith.ngrok.io` and per the docs:

    > If url is an absolute URL (that is, it starts with // or scheme://), the url’s hostname and/or scheme will be present in the result.

3. I think your `system.url-prefix` may be the root of your other problem with `title_link` as well. Happy to look into this further if you are able to confirm that you `system.url-prefix` is not the problem. 

Also, if there are any more questions or concerns re: Slack feel free to ping me :)

**Comment by daniel5gh** [comment]
Hi @MeredithAnya,

Thanks so much for this pointer. The value of `system.url-prefix` was indeed `sentry.example.com` without scheme, and now that after we've changed that to `https://sentry.example.com` at least the links in `title_link` on slack work as expected! I am assuming (because I don't really want to remove and add again the configuration for slack integration) that the `redirect_uri` in the initial oauth conversation is also corrected.

Another interesting point around all this is that a colleague got to the same conclusion about `urljoin`, but in a different way, while investigating why uploading of source maps was also busted for our setup. It turned out a double hostname showed itself there too, `sentry-cli` was trying to POST to `https://sentry.example.com/api/0/sentry.example.com/api/0/organizations/org/chunk-upload/`

This doesn't change the fact that `absolute_url` is called twice on the `redictect_uri`, but when adding a scheme to `system.url-prefix` this doesn't seems to be a problem. I haven't gone into much detail today, but a quick try shows me the following and it looks like previously sentry's double `absolute_uri` ended up doing the middle case, where after I changed `system.url-prefix` sentry is now like the third case:

```python
>>> urljoin('www.example.com', 'www.example.com/path/')
'www.example.com/path/'
>>> urljoin('https://www.example.com', 'www.example.com/path/')
'https://www.example.com/www.example.com/path/'
>>> urljoin('https://www.example.com', 'https://www.example.com/path/')
'https://www.example.com/path/'
```

Lastly, regarding the setup instructions, the previous version we followed was already for the newer bot config and we did configure `signing-secret`. It was just that the docs had a reference to slack's configuration page which was no longer accurate; there was no distinction between user and bot scopes I believe. You've updated that that document nicely, just one thing I am not sure about; are all these bot scores required? I know the first time around I added those same 11 I referenced from the code, but now I have a setup that only has `links:read` for bot scopes, and it *seems* to all work correctly. I don't know what the right answer is here, just wanted to point this out :)

Thanks again for the help, much appreciated!
