### ISSUE TITLE
Slack Integration: Some alerts have stopped sending to Slack

### ISSUE THREAD

**Issue by fabis94** [getsentry/sentry#23362]
Sentry version: Sentry 20.10.1aa4b37c (on premises)

The weird thing is that the integration does work for some alerts/slack channels, but then stopped working for others. The channels def have the Slack App invited in them and it worked fine up until recently.

Only things we were able to find in the logs were this:
```
10:55:55 [INFO] sentry.integrations.client: integration.http_response (status_string=u'200' integration=u'slack' error=u'internal_error')
10:55:55 [INFO] sentry.rules: rule.fail.slack_post (event_id=u'407be4a193ed47cea3fa6b9ef99309a7' channel_name=u'#sentry-js' error=u'internal_error' project_id=6L)
10:55:57 [INFO] sentry.integrations.client: integration.http_response (status_string=u'200' integration=u'slack' error=u'internal_error')
10:55:57 [INFO] sentry.rules: rule.fail.slack_post (event_id=u'13f279eda4a84fbabb59245db1db15ff' channel_name=u'#sentry-js' error=u'internal_error' project_id=6L)
```

And #sentry-js isn't even the channel that stopped working, so there don't seem to be any logs for failures to send to the other channel.

Clearly something failed, but the logs aren't useful enough to tell us what. Any ideas how to debug this further? Re-configuring the Slack integration and restarting Sentry didn't seem to help

**Comment by bogdandm** [comment]
Also when we try to add new workspace (or re-add old one) we get 500 Server Error without any error messages.
![image](https://user-images.githubusercontent.com/11839115/106002629-6a672a80-60c2-11eb-819d-cc092fa6f6e2.png)

**Comment by darcoli** [comment]
We have the same issue but using the cloud version of Sentry. Slack alerts stopped working some hours ago but email alerts work fine.

**Comment by manuzope** [comment]
Hey there folks, this was an error with the Slack API. They have since fixed it so your notifications should be running again.

Apologies for the inconvenience!

https://status.sentry.io/incidents/7mlyyrvfxbvh

@bogdandm: that looks like a separate issue. Mind opening another Github issue with details on your setup?
