### ISSUE TITLE
Translations for JS App

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#2336]
Right now with the switch to the new UI our translations are not implemented there yet which leaves the UI in a weird state since we traditionally selected localization automatically from the user agent.

Short term we should disable them until we have a solution as this causes a bad user experience:

* [ ] message temporary disabling of translations
* [ ] force english on

For fixing the translations properly we need to figure out what we can do for the JS UI.  Do we want to stick with gettext or look at something different for those parts.

**Comment by mitsuhiko** [comment]
Thoughts @dcramer?

**Comment by dcramer** [comment]
https://github.com/zaach/jsxgettext

**Comment by mitsuhiko** [comment]
I think we should merge all data together into one pot file (backend + frontend) and then separately split them up by usage (eg: used in .jsx file) for the UI.  On the server we can load all translations.

**Comment by mitsuhiko** [comment]
Alternative to jed if that does not work is just loading a key/value mapping for javascript and make Python's babel library convert the plural expression into a javascript function.  Then we just need to decide on what parameter format to use for JavaScript (eg: `%s` etc.).

**Comment by dcramer** [comment]
Working on the Jed stuff in ``js-gettext`` branch

**Comment by dcramer** [comment]
I think we're good with this ticket now
