### ISSUE TITLE
Linked/Unlinked filters do not work with Asana

### ISSUE THREAD

**Issue by hatched-aaron** [getsentry/sentry#23372]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

I have issues linked via the Asana plugin -
![image](https://user-images.githubusercontent.com/53797312/106036493-68da3a00-60a3-11eb-9618-74fb46df4743.png)

However - these linked tasks do not respond to the is:linked filters:  

![image](https://user-images.githubusercontent.com/53797312/106036701-a8a12180-60a3-11eb-926a-7bf34b219f5b.png)

These tasks linked via Asana still show up in the is:unlinked filter as well - so it appears Asana linkage is not taken into account with the filters.

## Steps to Reproduce

1.  Link or create an Asana task for an issue
2. Attempt to filter issues by is:linked (no issues are shown)

### What you expected to happen

is:linked or is:unlinked should correctly filter if an Asana task is linked to the ticket.

This would definitely be useful for us in order to filter by issues we've already assigned tasks for within our sprints.

Much appreciated!

**Comment by BYK** [comment]
I think this was implemented for Jira initially. I'll let @wedamija fill in the gaps tho :)

**Comment by ento** [comment]
@BYK @wedamija Does it mean support for filtering issues linked with Asana is not planned..? It'll be useful for us when listing issues that haven't been triaged.

**Comment by BYK** [comment]
@ento sorry for the late response. This should be implemented in #21593 via the `is:linked` and `is:unliked` filters documented here: https://docs.sentry.io/product/sentry-basics/search/#search-properties

The implementation is generic so it should work. I'll mark this is as a potential bug and reopen until we can verify/reproduce and decide what the course of action is.

**Comment by markstory** [comment]
The `is:linked` filters operate on the `GroupLink` and `PlatformExternalIssue` tables, unfortunately Asana is a 'project plugin' that stores its data in the `GroupMeta` table. This table is not connected to the `is:linked` filter unfortunately. Due to the nature of GroupMeta being an arbitrary key/value pair it is much harder to connect to `is:linked` as not all group meta values indicate an issue link and the key structure is plugin specific.

If/when the Asana project plugin is replaced with an organization level plugin we'll be in much better shape.

**Comment by BYK** [comment]
Then I'm forwarding this to @getsentry/ecosystem for triage, thanks a lot @markstory for the context and clearing out the confusion!

**Comment by chadwhitacre** [comment]
@BYK Based on your comment I've added back `Status: Untriaged` since I think this is still awaiting a response from @getsentry/ecosystem (yes?).

**Comment by BYK** [comment]
@chadwhitacre that's my bad. I actually talked to @manuzope off band and learned that moving the Asana plugin to an integration is definitely on the list but not on the near term. Should have shared it here.

Based on this, getting back the "on-hold" status :)

**Comment by matanbanin** [comment]
Any new on this?

**Comment by GabeVillalobos** [comment]
Unfortunately the team is understaffed and we can’t prioritize this fix, but we’re always open to community contributions.
