### ISSUE TITLE
Sentry 7.7.4 doesn't detect Slack plugin

### ISSUE THREAD

**Issue by karmux** [getsentry/sentry#2338]
Sentry 7.7.0 and sentry-slack 0.4.0 works well together.
Sentry 7.7.4 and sentry-slack 0.4.0 doesn't work (Slack submenu is also missing from left side menu under Settings).

Initially I created this issue but they say this issue is not a bug in Slack plugin but in Sentry:
https://github.com/getsentry/sentry-slack/issues/24

**Comment by mattrobenolt** [comment]
By it not detecting the plugin, do you mean it never shows up as an option inside the UI to enable?

If that's the case, there's likely an error when you start up `sentry runserver`.

> (Slack submenu is also missing from left side menu under Settings).

Can you post a screenshot? Are there assets that are 404ing?

**Comment by mattrobenolt** [comment]
Oh, derp, the Slack submenu.

So my guess is that it's erroring when the process starts up. If that's the case, `sentry runserver` should have a stacktrace for why it failed.

**Comment by karmux** [comment]
@mattrobenolt yes in 7.7.4 there is no option to enable this plugin since it's not showing in Sentry web under integrations. If I downgrade Sentry to 7.7.0 then it's there and posts to Slack. I can check for tracebacks tomorrow.

**Comment by mattrobenolt** [comment]
If for some reason, it works in 7.7.0, but not 7.7.4, that's where this seems concerning.

Nothing changed except pinning some dependencies as I mentioned in the other issue.

See: https://github.com/getsentry/sentry/compare/7.7.0...7.7.4

So a stacktrace here will be really useful. :/

**Comment by Onumis** [comment]
I confirm that on 7.7.2 it also does not show up.
I'm upgrading to 7.7.4 but it seems it will be pointless, be back in a few.

**Comment by mattrobenolt** [comment]
@Onumis And to confirm, it was in fact, working with 7.7.0?

Do you have a stacktrace to share with the issue? When we load plugins on process startup, we'll dump a stacktrace for plugins that fail to load.

**Comment by Onumis** [comment]
I upgraded last week from 7.6.something to 7.7.1, so I cannot answer that.
I'll try go get some more info on this.

**Comment by Onumis** [comment]
Logs for Sentry 7.7.1, with sentry-slack 0.4.0

```
$ sudo cat /var/log/supervisor/sentry-worker-stdout---supervisor-XybNxy.log
Failed to load app 'slack':
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sentry/utils/runner.py", line 243, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2369, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2386, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 851, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (kombu 3.0.26 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('kombu<3.1,>=3.0.29'), set(['celery']))

Failed to load plugin 'slack':
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sentry/utils/runner.py", line 255, in install_plugins
    plugin = ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2369, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2386, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 851, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (kombu 3.0.26 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('kombu<3.1,>=3.0.29'), set(['celery']))

[2015-11-18 20:03:16,996: WARNING/MainProcess] celery@ip-172-31-2-116 ready.

```

**Comment by Onumis** [comment]
Upgrade to sentry 7.7.4 finished now and *sentry-slack works*!

**Comment by mattrobenolt** [comment]
Yeah, that's not an issue with slack, that's an issue with Sentry itself. This is exactly why 7.7.4 exists in the first place. :)

So to confirm, @Onumis it does work on 7.7.4 for you?

**Comment by Onumis** [comment]
![image](https://cloud.githubusercontent.com/assets/1113178/11253259/2e46e4b8-8e19-11e5-8e38-16d2663b5ba6.png)

Tested it right now :+1:

**Comment by johnhamelink** [comment]
I am running Sentry 7.4.4 with Sentry-Slack 0.4.0 and the admin panel is not showing up for me unfortunately - I'm getting the exact same stack trace in the logs as @Onumis is.

**Comment by mattrobenolt** [comment]
@johnhamelink Can you upgrade to 7.7.4? This is unfortunately out of our control since an upstream dependency broke compatibility for us. We had to cut releases in the 7.7.x branch purely to pin dependencies to fix this. But unfortunately, that means some older releases will be broken without manual intervention.

We're no longer cutting releases for 7.4.4, and if for some reason, you can't upgrade, I can probably try and get you fixed up manually.

**Comment by johnhamelink** [comment]
Sorry @mattrobenolt that was a typo - I'm on 7.7.4

**Comment by mattrobenolt** [comment]
Then that stack trace doesn't make sense for 7.7.4. Could you confirm it's exactly the same? :confused:

**Comment by johnhamelink** [comment]
Sorry @mattrobenolt I should probably get some sleep :zzz: 

My conflict is with `python-dateutil` not with `kombu`

```
VersionConflict: (python-dateutil 1.5 (/usr/local/lib/python2.7/dist-packages), Requirement.parse('python-dateutil>=2.0.0,<3.0.0'))
```

However the root of this problem seems to lie with my using the `python-pip` package from ubuntu and not `get-pip.py`. 

Reinstalling with that version of pip solves the problem.

**Comment by karmux** [comment]
Got Sentry 7.7.4 working with sentry-slack 0.4.0.

I had basically two issues:
1) I had to upgrade pip from version in Debian Jessy to version in PyPI.
2) I was always installing kombu==3.0.29. After letting Sentry to decide which version of kombu to install, I got rid of the ContextualVersionConflict error.
