### ISSUE TITLE
Wrong timezone and name on Sentry UI, User Settings screen (Settings > Account > Details)

### ISSUE THREAD

**Issue by semuserable** [getsentry/sentry#23406]
- `Kiev` (Russian pronunciation) should be renamed to `Kyiv` (Ukrainian pronunciation)
- `Kyiv` has two timezones, winter (UTC+0200) and summer (UTC+0300)
![timezone_sentry_kyiv](https://user-images.githubusercontent.com/2175097/106107266-66351e80-614f-11eb-9f27-ad0efaab519a.png)

Right now I expect to see UTC+0200, because that's the actual time right now.

I sent an exception into Sentry and I see the correct name and timezone.

![image](https://user-images.githubusercontent.com/2175097/106108027-61249f00-6150-11eb-86b2-a9a7d4bd2de7.png)

It seems the problem is only on `User Settings` page.

**Comment by silent1mezzo** [comment]
Thanks @semuserable I'll update the name to be correct. Our settings right now aren't dynamic so we chose the time is correct for most of the year. From my research Kyiv spends 7 months in UTC+0300 (April to October) and 5 months (Nov to March) in UTC+0200.

**Comment by silent1mezzo** [comment]
Upon further research both of the libraries we use for managing timezones still use Kiev ([pytz](https://github.com/stub42/pytz/blob/76ed1585bd17a981f295336cb88233deea8cafdc/tz/europe#L4084) and [moment.js](https://github.com/moment/moment-timezone/blob/develop/data/meta/latest.json#L4825)). pytz even has a comment on kiev vs kyiv [here](https://github.com/stub42/pytz/blob/76ed1585bd17a981f295336cb88233deea8cafdc/tz/europe#L4069). For now I think it makes sense to keep the label consistent to avoid confusion.

**Comment by semuserable** [comment]
@silent1mezzo thanks for the heads up. That's unfortunate :(
