### ISSUE TITLE
Sentry doesn't create static/dist items

### ISSUE THREAD

**Issue by MrYoda** [getsentry/sentry#2340]
Hi!

I wanted to install the latest version (from GH) instead of a stable from pypi, and after quiet successful installation sentry page was with the message "Please wait while we load an obnoxious amount of JavaScript."

How can I fix it?

requirements.txt:
```
# sentry==7.7.4  # stable pip
git+https://github.com/getsentry/sentry.git  # dev github

bpython
django-celery-email==1.1.3
djrill==1.4.0
djrillcelery==0.1.1
raven==5.8.1
sentry-youtrack==0.2.5
```

pip installation log from ``pip install -vvvv --log=pip-install.log -r requirements.txt````: http://pastebin.com/idD945DJ

**Comment by mattrobenolt** [comment]
Hey @MrYoda, can you try with `-e`? :)

**Comment by mattrobenolt** [comment]
To clarify, do:

`-e git+https://github.com/getsentry/sentry.git#egg=sentry-dev`

instead. This will cause the static files to be compiled.

**Comment by MrYoda** [comment]
The fastest and useful! Many thanks! I'm going to close issue.
