### ISSUE TITLE
Handle auto-resolution in UI

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2341]
> Once I resolve an error, I can't seem to reopen it. For example, https://app.getsentry.com/.../ is resolved, and when I unclick the resolve button it says "Saving changes", but when I reload the page the error is still resolved.

Refs: https://sentry.zendesk.com/agent/tickets/1100

I have reproduce this on the specific event referenced, but not on others.

**Comment by dcramer** [comment]
I assume it's because it was auto resolved in which you can't unresolved it. It's not really a big, but we could improve the UI around it.

**Comment by dcramer** [comment]
I think we should:

- add indicator saying "auto resolved" similar to muted box
- disable the unresolve action and have a tooltip suggesting that you cant unresolve

**Comment by mattrobenolt** [comment]
Ah, I see. That explains it.

Yeah, agreed then to make UI more obvious.
