### ISSUE TITLE
Platform Wizard alphabetical ordering issue

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#23410]
![image](https://user-images.githubusercontent.com/1633368/106139243-311ed100-613b-11eb-8a90-bd29d2950f7a.png)

Wizard orders by the first character of the whole platform id. But platforms that are nested, such as `dotnet.xamarin` ends up wit an odd order.

**Comment by bruno-garcia** [comment]
@EvanPurkhiser assigning to you for triaging, in case this is something we want to address.

**Comment by srknzl** [comment]
Opened a pr for this #23501

**Comment by BYK** [comment]
I think we should consider popularity sorting and a potential tree-view (for nested platforms under languages) for the future.

**Comment by EvanPurkhiser** [comment]
Yes I agree about tree view

**Comment by bruno-garcia** [comment]
I'm fine closing this as won't fix

**Comment by srknzl** [comment]
So you are closing this?
