### ISSUE TITLE
GitHub Integration: moved project to different github repo but can't update sentry integration to use the new one

### ISSUE THREAD

**Issue by dxm007** [getsentry/sentry#23461]
We set up Sentry last year as two separate projects frontend/backend which used to be in two separate repos. But because of tight coupling between the two, our dev team made a choice to combine those into a monorepo. However, now I'm having a hard time getting "link/create issue" actions on the Issues page to recognize the new repo.  In the integration, I added the new repo but the combo box in link/create dialog still only shows the old repo name and when I drop it down it just displays "no options"

This is the problem I have right now with backend project in sentry.

Interestingly enough, I switched frontend last week and had a fun time doing that. I discovered the issues screen "remembered" last repo choice so when I removed the old repos and only added the new one to the configuration, I would just get a generic error when trying to get to GitHub from Issues page. However, once I added back the old repos, last week the combo box worked. But this week, both frontend/backend Sentry projects do not show any other repo in the dropdown.

**Comment by dxm007** [comment]
hmm.. don't see any updates from the great peeps that bring us Sentry but shortly after I opened this ticket I noticed that magically the UI started working so either stars aligned or someone changed something to address it.  I'm fine to close this now.

**Comment by manuzope** [comment]
Hey, sorry for the late response. This one got lost in my email. 

We didn't change anything so that's strange. Let us know if it happens again.
