### ISSUE TITLE
Microsoft Teams Integration: no welcome message received to complete setup

### ISSUE THREAD

**Issue by atistler** [getsentry/sentry#23466]
I followed the directions here: https://docs.sentry.io/product/integrations/msteams/
to add Sentry integration for MS Teams.  I clicked "Add to Team" and choose a channel, however I never get the "welcome message in the "General" channel" that says "Complete Setup"."

**Comment by manuzope** [comment]
Hey @atistler, are you on sentry.io or on hosted sentry?
