### ISSUE TITLE
GitLab Integration error

### ISSUE THREAD

**Issue by samsulmaarif** [getsentry/sentry#23481]
## Important Details

How are you running Sentry?
Saas (sentry.io), paid plan

## Description

When i try to configure GitLab integration, an error appear:

> Oops! Something went wrong
> 
> It looks like you've hit an issue in our client application. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this! 

## Steps to Reproduce

1. In the organization General Settings -> click Integration -> GitLab
2. There are 2 tabs, click Configurations
3. On the installed GitLab repository integration, click Configure

![sentry-2021-02-01_10-42](https://user-images.githubusercontent.com/1231314/106412459-677d8880-647a-11eb-9097-0db7e3c095cd.png)

4. and the error appear

![sentry-2021-02-01_10-45](https://user-images.githubusercontent.com/1231314/106412597-b0cdd800-647a-11eb-98fb-069ce3645c13.png)

5. I've tried to reload so many times, and still got error

### What you expected to happen

The error does not appear, and i can continue to configure the integration.

### Possible Solution

I do not know. I hope sentry team can fix it.

Thanks.

**Comment by BYK** [comment]
Have you tried [contacting our support](https://sentry.io/contact/support/) for this?

**Comment by samsulmaarif** [comment]
> Have you tried [contacting our support](https://sentry.io/contact/support/) for this?

I did.

**Comment by BYK** [comment]
@samsulmaarif alright, will keep this ticket open and will update once this is resolved.

**Comment by BYK** [comment]
Ping @getsentry/ecosystem for triage (and possible closure if closed)

**Comment by manuzope** [comment]
Hey @samsulmaarif, looked into the account and the configure tab should be working now. Could you please confirm? And if so, do you know what, if anything, changed? We haven't made any changes on our end.

**Comment by samsulmaarif** [comment]
Hi @manuzope I think it solved now. I've checked the configure the integration tab, and the issue has been resolved. Thanks sentry team.

**Comment by manuzope** [comment]
Got it. Did anything change on your side by any chance? Cause I don't think we changed anything. Want to know for future debugging.

**Comment by samsulmaarif** [comment]
Ah, sorry. I tried to reinstall the integration with different gitlab account, and the issue is resolved. I'm not sure how this is work (and the issue that apear before), but it works now.
