### ISSUE TITLE
API to make analysing logs much easier

### ISSUE THREAD

**Issue by mlowicki** [getsentry/sentry#2351]
We're using Sentry heavily to log uncaught exceptions and while debugging various things (for Django, Twisted and standalone applications) to get besides traceback also various data passed through `extra` parameter to logger's methods.

Many times we need to analyse gathered data beyond what is provided out of the box like filters based on User-Agent strings but f.ex. data passed in `extra`.

We've implemented separate tool called sentryanal which talks directly to database to extract data and provides mechanics to filter or group data. Unfortunately such integration via database has many obvious drawbacks (basically each change in schema breaks our tool).

My proposal is to expose API which gives an access to gathered data so we can avoid connecting directly to database. Basic support would be to provide an option to get all samples from particular group.

Let me know what do you think. If this makes useful to push upstream we'll try to organise resources on our side to implement it.

**Comment by dcramer** [comment]
There is a web API that would let you crawl all events for a given group. We wouldn't do this on the server as it has unbounded response time, but the web API has basic pagination. This is the same API that's used to render the page these days, which means everything that is available there is available in the API.
