### ISSUE TITLE
`beforeSend` returned `null`, will not send event.

### ISSUE THREAD

**Issue by KaiyangJi** [getsentry/sentry#23527]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version x.y.z

Saas (sentry.io)

Other, version x.y.z, [briefly describe your environment]

## Description

sentry catch errors like `beforeSend` returned `null`, will not send
picture here [https://ibb.co/njZ1fLY](https://ibb.co/njZ1fLY)
This is an error i want to ignore because i return null in my code like this

beforeSend(event, hint) { 
// some if else judge
 return null;}

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. and so on.

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant

### What you expected to happen

this error should not be uploaded to sentry website

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by BYK** [comment]
Sorry about the bot misbehaving. Reopening, that said you _are_ missing critical information for us to help you and this issue should go to sentry-javascript so transferring there.

Ping @kamilogorek
