### ISSUE TITLE
Implement Environments

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2352]
A few goals here:
- Work towards removal of one-project-per-env
- Ensure we can clearly answer:
  - is this happening in prod?
  - whats happening in prod?
  - is this happening on the latest release in prod?

We'll need to tweak some things to make environments actually useful:
- Add environment to current SDK
- A release should technically be bound to an environment. 
- Artifacts are bound to a version, that is they are shared across all environments for the same version.
- Many breakdowns would be more useful if they were broken up by the environment. Possibly breaking them up by the release (assuming release was bound to an env) is good enough.

Assuming the above, implementing environments will likely end up requiring a bunch of changes to release. We already know we need some of these in areas where a release gets staged, and making the stages simply be env bound might be enough. Most likely ew can do the following:
- Add ReleaseEnvironment which would include release, environment, start/finish, and possibly things like the machines deployed. Alternatively the machine-type data, since its not useful in the short term, could just become a completely different object in the future.
- Accept environment in the SDK (capable as of 476433152c353cf496b0c17422be231b3205709c)
- Auto-tag environments

**Comment by dcramer** [comment]
@getsentry/team thoughts?

**Comment by dcramer** [comment]
I want to get at least basic SDK changes in for 8.0. We're probably ok with the changes already present, but should give it some more thought to make sure SDKs and integrations can support the new flow without yet another big version after 8.0.

**Comment by dcramer** [comment]
Bunch of stuff came up here.

**Rate limits**

Right now people use multiple projects to work around rate limits, and in some situations even use multiple orgs. We are ignoring any limitations around how Sentry does billing as that will change in the future.

**Tag Distribution**

A lot of times you really only care about tags (or other data) in association with an environment. For example, you'd want to know that the server its happening on is also associated with production. I think it's unlikely you share things like servers, so that's probably not a great example, but browser might be. This also comes up for releases, so if we bind the release tagging to version+env and eventually do dimensions we can hit two birds with one stone.

**Comment by benvinegar** [comment]
I believe most of what is described here has been implemented / shipped. Closing.
