### ISSUE TITLE
404 Page Not Found on Documentation

### ISSUE THREAD

**Issue by PenguinNexus** [getsentry/sentry#23549]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

Trying to read documentation on https://sentry.io/settings/<org-name>/projects/<project-name>/user-feedback/ results in a 404 Page Not Found

## Steps to Reproduce

1. Go to User Feedback settings of a project
2. Attempt to click the 'Read the Docs' button
3. Error 404 resulting

### What you expected to happen

Link for 'Read Documentation' links to docs.sentry.io

### Possible Solution

No idea for now.

### Logs / Extra

Link to screen recording:
https://user-images.githubusercontent.com/16801642/106670212-a6a7f880-65a4-11eb-9dfc-aa336ff66420.mp4

**Comment by BYK** [comment]
@PenguinNexus thanks for the report. Next time, please follow the issue template (don't remove fields). /cc @chadwhitacre if you think we should relax the issue template a bit.

**Comment by PenguinNexus** [comment]
Hi, please see #23551 using the correct template (re-created immediately after it was closed by the bot)

**Comment by BYK** [comment]
Closing in favor of #23551. Thanks @PenguinNexus and sorry for the hassle! :)

**Comment by srknzl** [comment]
did you forget to close this @BYK :)

**Comment by BYK** [comment]
I did indeed @srknzl, thanks for the heads up! 😁
