### ISSUE TITLE
404 when attempting to 'Read the Docs' in User Feedback

### ISSUE THREAD

**Issue by PenguinNexus** [getsentry/sentry#23551]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

Trying to read documentation on [https://sentry.io/settings/{org-name}/projects/{project-name}/user-feedback/](https://sentry.io/settings/{org-name}/projects/{project-name}/user-feedback/) results in a 404 Page Not Found

## Steps to Reproduce

1. Go to User Feedback settings of a project
2. Attempt to click the 'Read the Docs' button
3. Error 404 resulting

Link to screen recording:
[https://user-images.githubusercontent.com/16801642/106670212-a6a7f880-65a4-11eb-9dfc-aa336ff66420.mp4](https://user-images.githubusercontent.com/16801642/106670212-a6a7f880-65a4-11eb-9dfc-aa336ff66420.mp4)

### What you expected to happen

URL should link to the correct page.

**Comment by Isaiah08-D** [comment]
This happens for me to!

**Comment by BYK** [comment]
@Isaiah08-D @PenguinNexus would you like to try submitting a PR and get your name on the hall of fame 😛

**Comment by BYK** [comment]
Happy to assist you.

**Comment by BYK** [comment]
I take this back, this seems a bit more complicated than expected.

**Comment by BYK** [comment]
I think #23720 fixed this to an extent.
