### ISSUE TITLE
Expand Organization Dashboard

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2355]
Some things we could show that are useful:
- Assigned issues
- Bookmarked issues
- Activity feed (i.e. comments, assignment, etc)
- Issues which require action (i.e. let users know a bug is fixed, from crash reports)

Some things will be more complicated to do organization-wide so we should tread carefully. Its also likely a lot of these could make their way into the project dashboard.

We should focus this on workflow features less so than data dumps.

**Comment by mattrobenolt** [comment]
> We should focus this on workflow features less so than data dumps.

:+1:

What's the incentive for doing this organization-wide vs project-wide? Would it be potentially too much for a whole org?

Will any of this be personalized for an individual? Like, "issues assigned to me" vs "issues assigned to others". I'm thinking of the Phabricator dashboard here.

**Comment by dcramer** [comment]
@mattrobenolt this would be our version of the Phabricator dash. Organization dash makes a lot more sense as if you work on multiple projects its a mess to dig through things.

**Comment by ckj** [comment]
I sketched an initial stab at this:

![screen shot 2015-11-24 at 2 43 40 pm](https://cloud.githubusercontent.com/assets/30713/11385596/4ee900ce-92cf-11e5-913c-dfef84be421d.png)

There's quite a lot going on, but I think I prefer that to the snoozefest that exists currently. My biggest concerns are:

1. Before this was a launch pad for projects. Now projects that live beyond the 'Active projects' list are two clicks away.

2. The sidebars are a bit tall by default. This could look weird when there's not a ton of issues presented in the main column.

Curious to hear everyone's feedback.

**Comment by dcramer** [comment]
Some thoughts and notes from our convo earlier:

- Might be able to do bookmarked/favorited/starred projects if we have no other useful metric here (or jsut recently visited? favorite + recently visited up to #?)

- Might want to put the projects above activity

- We would need a way to clarify what Most Impactful covers. Is it all projects you're a member of? Just ones you are interested in?

- I think barcharts might be more valuable than user/event count for the bookmarks/assigned, but not a strong feeling here.

I think the height isnt an issue, and is actually a fine thing to do here. Lots of useful content.

**Comment by dcramer** [comment]
Some other feedback:

- Knowing who's assigned (outside of the assigned to me box) would be useful (especially unassigned!)

- Numbers are useful but maybe deprioritize

- Suggest Y value on sparklines and/or add an average line (maybe similar to the old dashed line we had?)

**Comment by benvinegar** [comment]
:+1:

**Comment by dcramer** [comment]
More notes:

- Add a "history" feature, which is just events you've seen, sorted by date of view

- Explore the users affected + events combination chart to replace Event/User counts (everywhere)

**Comment by ckj** [comment]
Updated concept to reflect feedback:

![screen shot 2015-11-30 at 12 25 39 pm](https://cloud.githubusercontent.com/assets/30713/11487294/eb972c50-9772-11e5-8ef7-a6a88143b774.png)

**Comment by dcramer** [comment]
Thinking about this, i wonder if we could put assign to under the selector as well? I still wanna have the barchart there, so if we hid *all* CTAs under the same action bar it'd make it much easier to fit the chart in there.

**Comment by dcramer** [comment]
I've got Assigned, Bookmarked, and History (Viewed) done in the branch. We need visuals for the ``<CompactIssue>`` but a lot of the basics are in place. We can probably merge those in before doing the actual dashboard.

**Comment by dcramer** [comment]
Some initial bits, which power "My Issues" (we could rename this to Issues) are merged behind a feature switch. Any getsentry.com users can reach out to us if they want to opt-in.

**Comment by dcramer** [comment]
- [ ] issues need to truncate (https://www.dropbox.com/s/3vx10i4lqlt8k44/Screenshot%202015-12-04%2013.45.43.png?dl=0)
- [ ] resolved/bookmarked/muted status needs to be indicated in the issue row
- [ ] bar chart alignment/size is off

/cc @ckj

**Comment by dcramer** [comment]
hid assignee selector, implemented the other actions, just needs visuals now (i think)

**Comment by dcramer** [comment]
Some basic work is available in ``org-dashboard`` in ``organizationDashboard.jsx``

**Comment by joaumg** [comment]
@ckj did the organization-wide dashboard at https://github.com/getsentry/sentry/issues/2355#issuecomment-160788811 ever became available ?
