### ISSUE TITLE
CLI Repo URL matching fails for DevOps CI

### ISSUE THREAD

**Issue by matthiasotto** [getsentry/sentry#23583]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description
When running the CLI to automatically determine commits, I receive the following error due to two different paths used by DevOps:
```
  DEBUG   2021-02-03 16:22:03.363458259 +00:00   Got reference URL for repo MyClient-Platform: https://mycorp.visualstudio.com/DefaultCollection/MyClient-Platform/_git/MyClient-Platform
  DEBUG   2021-02-03 16:22:03.363469560 +00:00   Looking for reference URL https://mycorp.visualstudio.com/DefaultCollection/MyClient-Platform/_git/MyClient-Platform
  DEBUG   2021-02-03 16:22:03.365129192 +00:00   not a match: https://mycorp.visualstudio.com/MyClient-Platform/_git/MyClient-Platform != https://mycorp.visualstudio.com/DefaultCollection/MyClient-Platform/_git/MyClient-Platform
  INFO    2021-02-03 16:22:03.393044546 +00:00 Resolving HEAD (origin@HEAD)
```

## Steps to Reproduce

1. Add your DevOps repo via `Integrations` to your Sentry Project
2. Add Sentry CLI to your DevOps CI/CD Pipeline (we use YAML)
3. Attempt to run `sentry-cli releases set-commits --auto "$VERSION"`

### What you expected to happen
I was expecting that the Repo URL obtained by adding DevOps as an integration would match the Repo URL that is internally used by DevOps CI Pipeline.

Both of these URLs are valid links to the very same repository.

### Possible Solution
I have seen the Regex rules to account for the different repos' URL scenarios. Perhaps something like this could be added here to ignore the `DefaultCollection` segment of the URL.

**Comment by BYK** [comment]
@manuzope ping

**Comment by manuzope** [comment]
Hi @matthiasotto, thanks for bringing this up! Do you know what the `DefaultCollection` represents in the URL?
