### ISSUE TITLE
Onboarding Flow Team/Project Regression

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#2358]
When you create a new account on app.getsentry.com there is no flow that forces you to create a team and project any more. This only comes up in single org mode.  This also means that the "+ Project" button is broken because you are not in a team.

This "+ Project" button should not appear:

<img width="780" alt="screen shot 2015-11-24 at 12 43 16" src="https://cloud.githubusercontent.com/assets/7396/11365765/05005438-92a9-11e5-9e66-22135e8af9d8.png">

Instead if you come from the sign up via www.getsentry.com it should ask you for creating a team if you are not in one yet.

**Comment by mitsuhiko** [comment]
The twitter thread that uncovered this problem is here: https://twitter.com/prinzhorn/status/669112671929810944

**Comment by Prinzhorn** [comment]
It's also worth noting that there is already a team created automatically but I'm not assigned to it (see the (1) in the screenshot). I don't know why it's already created or why I'm not assigned directly. Not sure how it's supposed to be, but it currently doesn't look reasonable.

**Comment by mitsuhiko** [comment]
Indeed. I think that's part of the puzzle.

**Comment by dcramer** [comment]
@mitsuhiko were you tackling this? I believe OrganizationMemberTeam just needed created. We should also probably work towards removing superuser as default in tests.

**Comment by mitsuhiko** [comment]
@dcramer i changed it so that you are a team member now from the beginning of that team as a quick fix.

Fixing the messaging now that caused the button to not show it's error message. Separately from that I will try to make the error of that button nicer, maybe to guide it through a flow.

**Comment by mitsuhiko** [comment]
This at least restores the error feedback from the "+ Project" button.  We might want to bring up a dialog directly without a redirect though.

**Comment by dcramer** [comment]
We fixed the lack of membership here
