### ISSUE TITLE
Cannot use release tag in issue ownership rules

### ISSUE THREAD

**Issue by Limsanity** [getsentry/sentry#23617]
## Important Details

How are you running Sentry?

sentry.io

## Description

cannot use release tag as part of issue ownership rules

## Steps to Reproduce

1. create ownership rules

<img width="1176" alt="WX20210205-010400@2x" src="https://user-images.githubusercontent.com/31369862/106928385-16a5b280-674e-11eb-8d2a-633590c4b513.png">

2. create an alert rule

<img width="1649" alt="WX20210205-010538@2x" src="https://user-images.githubusercontent.com/31369862/106928599-4e145f00-674e-11eb-851a-a3138d549847.png">

3. trigger an error with release 1

<img width="390" alt="WX20210205-010804@2x" src="https://user-images.githubusercontent.com/31369862/106928856-9f245300-674e-11eb-8e22-77e0df52a841.png">

### What you expected to happen

Sentry should only send email to xxx@qq.com. However, it cannot match the release tag rule, and then send email to every user with accessed to the project.

### Possible Solution

The release tag is one of protected tags, seems it would be transformed to `sentry:release` internally.

**Comment by Limsanity** [comment]
bump to avoid staleness

**Comment by BYK** [comment]
Assigning to @getsentry/workflow for triage. Also CC @getsentry/visibility in case Workflow is not the correct team for this.

**Comment by burisk** [comment]
+1

We are trying to use tag `user` with value `username:someemail@example.com` but we can't force Sentry to match it by any pattern.

For example:
`tags.user:username:someemail@example.com sentryuser@example.com`
`tags.user:"username:someemail@example.com" sentryuser@example.com`
`tags.user:someemail@example.com sentryuser@example.com`
`tags.user:* sentryuser@example.com`
`tags.user.username:* sentryuser@example.com`
`tags.user:username sentryuser@example.com`
`tags.user:*someemail* #sentry`

None of these patterns work. If we are trying to match with simple tag `level` with value `fatal`, it'll match but not this one.

**Comment by NK74** [comment]
+1 too ....

Same issue here 
```
tag.dag_owner:valentin valentin@example.com
user.username:fgasmi valentin@example.com
```
