### ISSUE TITLE
Not sending to the webhook when the issue happens

### ISSUE THREAD

**Issue by IcaroRios** [getsentry/sentry#23660]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

I added the sentry in my application, in the list of issues in / issues I can see that the sentry is catching the all, if I go to WebHooks and click on "test plugin" it normally sends the notification, but I do not receive anything when the errors occur.
## Steps to Reproduce

1. Create project
2. Enable webhook
3. Test URL (working)
4. Force an error in my application to see if i'll receive the notification (not working)

### What you expected to happen
Receive an message on rocket.chat as same as i know that worked in others application

### Possible Solution

I don't know
![Captura de Tela 2021-02-05 às 12 34 32](https://user-images.githubusercontent.com/21972639/107054144-821f6c80-67ae-11eb-8dd1-19a392784cd2.png)
![Captura de Tela 2021-02-05 às 12 34 44](https://user-images.githubusercontent.com/21972639/107054166-88ade400-67ae-11eb-9796-1039787cc64f.png)
![Captura de Tela 2021-02-05 às 12 35 30](https://user-images.githubusercontent.com/21972639/107054267-a67b4900-67ae-11eb-9a5a-dadc4a5afbe6.png)
![Captura de Tela 2021-02-05 às 12 35 06](https://user-images.githubusercontent.com/21972639/107054217-97949680-67ae-11eb-9262-4ae0a88dc632.png)
.
![Captura de Tela 2021-02-05 às 12 37 21](https://user-images.githubusercontent.com/21972639/107054477-ee01d500-67ae-11eb-928e-487f15864fc8.png)

**Comment by manuzope** [comment]
For webhooks to successfully work, you also need to create an alert rule so that Sentry knows when it should fire. 

And in the alert rule, you'd need to have this action: 
![Screen Shot 2021-02-05 at 10 35 24 AM](https://user-images.githubusercontent.com/1417849/107074753-01f10b00-679e-11eb-9a8c-2a05faba4907.png)

Mind giving that a try if you don't have an alert rule already?

**Comment by IcaroRios** [comment]
I'll try
