### ISSUE TITLE
Can not send a test email to my email address, get a error about socket timeout

### ISSUE THREAD

**Issue by DDusky** [getsentry/sentry#23661]
## Important Details

My sentry version is 21.1.0: latest.  (onpremise)

I run sentry by docker-compose

## Description

After `docker-compose up -d`,   I try to send a test email to myself,  but it does not work. And i get an error about socket timeout

## Steps to Reproduce

1. config sentry/config.yml, this is my mail server config:
```
mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
mail.host: 'smtp.163.com'
mail.port: 25
mail.username: 'xxx@163.com'
mail.password: 'xxxx'
mail.use-tls: false
# The email address to send on behalf of
mail.from: 'xxx@163.com'
```
2. `docker-compose up -d` all done
3.  At sentry web admin page,  i send a test email to xxx@163.com,  then pending......, oh, timeout error
4. Try to call sentry.utils.email.send_mail  in sentry shell manually,  and i get a same error:
```
>>> send_mail('test', 'body message', 'xxx@163.com', ['yyy@qq.com'])
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/sentry/utils/email.py", line 457, in send_mail
    return email.send(fail_silently=fail_silently)
  File "/usr/local/lib/python3.6/site-packages/django/core/mail/message.py", line 348, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 104, in send_messages
    new_conn_created = self.open()
  File "/usr/local/lib/python3.6/site-packages/django/core/mail/backends/smtp.py", line 64, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
```

### What you expected to happen
I hope i can send email to myself or other team members

### Possible Solution
I haven't found a solution to the problem.
I guess this sentry latest version have some problem on mail server module ?

Please assist me in solving this problem. Thanks

**Comment by BYK** [comment]
>I guess this sentry latest version have some problem on mail server module ?

What makes you think it is Sentry that is broken and not some network configuration issue on your end? 🙂

**Comment by DDusky** [comment]
@BYK Because i debug in sentry shell,  i find this method  `socket.py`
```
def getaddrinfo(host, port, family=0, type=0, proto=0, flags=0):
    addrlist = []
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
        af, socktype, proto, canonname, sa = res
        addrlist.append((_intenum_converter(af, AddressFamily),
                         _intenum_converter(socktype, SocketKind),
                         proto, canonname, sa))
    return addrlist
```
while debuging, i get the `sa` values `['220.181.12.17', 25]`,  and `sock.connect make a timeout error`

**Comment by DDusky** [comment]
@BYK But now,  i change my mail server config to TLS SMTP,  and use `django_smtp_ssl.SSLEmailBackend` mail.backend,  it's work !!!  
Amazing ~
Thanks
