### ISSUE TITLE
Add Webhook for Release Tracking

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2367]
We could add a simple webhook view which is project specific and simply proxies through the release details POST endpoint. This would let you avoid setting up an API key (less access), and make it far simpler to implement.

**Comment by rakshazi** [comment]
@dcramer hi!
Can you add info about that here https://docs.sentry.io/learn/releases/ please?

**Comment by teebu** [comment]
Is this something that can be connected in the Github Webhooks?

**Comment by dcramer** [comment]
It won’t work with GitHub webhooks as it requires a specific payload for Sentry. It’s the same request that is required from our API but we allow you to do it with a tokenized URL instead of using a standard API mechanism.
