### ISSUE TITLE
Azure DevOps integration can't find my organization

### ISSUE THREAD

**Issue by dg-eparizzi** [getsentry/sentry#23689]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

When I tried to add this integration it can't find my organization.
![mrl2Jv5QR7](https://user-images.githubusercontent.com/72451869/107232483-bea6ce80-6a21-11eb-9363-33c34c3c4fcb.gif)

I'm indeed the owner of the Azure DevOps organization.

Also, is this extension the same as this one? https://marketplace.visualstudio.com/items?itemName=Sentry.sentry
Or are they two different things?

## Steps to Reproduce

1. Settings
2. Integrations
3. Azure DevOps
4. Add Installation

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant

### What you expected to happen

My organization is listed there.

### Possible Solution

No idea...

**Comment by MeredithAnya** [comment]
@dg-eparizzi is it possible that you are signed into Azure DevOps under a different account where you are not an owner of any Azure organizations?

Also to answer: 

> Also, is this extension the same as this one? https://marketplace.visualstudio.com/items?itemName=Sentry.sentry
Or are they two different things?

There are they same integration, it's just a difference of whether you start the installation on our end or on Azure's end.

**Comment by dg-eparizzi** [comment]
> @dg-eparizzi is it possible that you are signed into Azure DevOps under a different account where you are not an owner of any Azure organizations?
> 
> Also to answer:
> 
> > Also, is this extension the same as this one? https://marketplace.visualstudio.com/items?itemName=Sentry.sentry
> > Or are they two different things?
> 
> There are they same integration, it's just a difference of whether you start the installation on our end or on Azure's end.

No, I'm indeed logged in with the right account. But as I mentioned, the directory where the Azure DevOps organization lives is not the default one. I'm 99% sure is because of that. I had similar issues with other 3rd party services several times because of this.

**Comment by dg-eparizzi** [comment]
Uhm, the bot is about to close it... Any updates?

**Comment by BYK** [comment]
Ping @MeredithAnya @manuzope

**Comment by manuzope** [comment]
Hi @dg-eparizzi, that's unfortunate. Looks like someone else found a workaround: https://github.com/getsentry/sentry/issues/14357#issuecomment-538379352. It's a little hacky but want to get you unblocked as soon as I can.

Does that work for you?

**Comment by dg-eparizzi** [comment]
Yes, that seemed to work.
Thanks


_______________________________

Emiliano Parizzi

Lead Software Development Engineer

Performance Analyzer Team

doosangridtech.com<http://www.doosangridtech.com/>

<mailto:emiliano.parizzi@doosan.com>
[cid:ee6aac49-8738-430e-a954-30e0d9fc3672]
________________________________

**Comment by manuzope** [comment]
Great - thanks for confirming! Going to close this in favor of https://github.com/getsentry/sentry/issues/14357 (which is where we're tracking this problem)
