### ISSUE TITLE
Can we have a configuration option that lets us specify which user gets alerts?

### ISSUE THREAD

**Issue by kitsunde** [getsentry/sentry#2373]
Naturally we're using sentry in development, but it's pretty noisy when one person is developing and it goes out to everyone. Could it be possible to specify who's going to receive the email?

```javascript
Raven.config('https://asdf@app.getsentry.com/38561', {
  shouldSendTo: ['example@example.org']
}).install();
```

That way I can configure our projects to pick up the user of whoever is developing. The user would of course have to be in sentry already since you wouldn't want to let us email random email addresses.

**Comment by dcramer** [comment]
We've talked about adding this in some shape or form. I'm not sure we'd want to do it on the client, but what we had talked about in the past is allowing you to scope rules.

I think in the best case this would come down to the following:

- Rules that are per-user (vs global per project)
- The ability to "Notify myself via email" as an action to said rule

This helps a lot of situations, and probably could be bent to help yours (i.e. if you didn't notify by default in the development environment).

I'm not sure if/when any of this will actually happen though. It's still a concept and to be honest, notifications are a big complex monster. We're slowly improving them, and conversations about it come up every other weeks at this point.
