### ISSUE TITLE
Improvements to i18n catalogs

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2376]
I think we need to approach locales with a bit more rigidness since this affects selection in the UI.

A few goals:

1. Once a language is supported, its always supported. This means we cant automatically disable it.
2. Backend and frontend need to support the same language selection.
3. Knowing the % translated for a language is useful, maybe we support all languages but give a partial flag to the ones that aren't of x %?

**Comment by mitsuhiko** [comment]
The auto update will no longer disable the catalogs. Trying to make the backend selection a subset as well now.

**Comment by dcramer** [comment]
The only items left would be to improve UX around language selection / awareness. Closing this out as its not critical.
