### ISSUE TITLE
Release versions are being URL quoted.

### ISSUE THREAD

**Issue by mvaled** [getsentry/sentry#2377]
When showing the release version we see, for instance, "8.0.20151116.224608%2Ba22433e" instead of "8.0.20151116.224608+a22433e".  

We use the local part of the version to show the commit deployed to our server.

**Comment by mvaled** [comment]
Dashes are being printed as %3A

**Comment by dcramer** [comment]
If this is on getsentry.com, do you have a link to an event? Alternatively, can you give the version (sha) of Sentry, and the input value sent to Sentry for the version?

**Comment by mvaled** [comment]
This is on-premises, at commit id 465426ee816c6e1f47448c7c879436b2ee0b2080 which is just 20hrs ago.

**Comment by dcramer** [comment]
Alright

see #2284 and #2280
