### ISSUE TITLE
Java and lambda expressions group events but they should not

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry#23791]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

When using Java and lambda expressions (same module/class), events might be grouped together but they should not, eg:

```
    binding.unsetUser.setOnClickListener(
        view -> {
            Sentry.captureException(new Exception("unset user button"));
        });

    binding.setUser.setOnClickListener(
        view -> {
            Sentry.captureException(new Exception("set user button"));
        });
```

events have a different exception title, different line number, its own click listener and should be not grouped together.

## Steps to Reproduce

Run an Java/Android App with the code snippet above

Good items to include here include:

<img width="1010" alt="Screenshot 2021-02-11 at 10 10 43" src="https://user-images.githubusercontent.com/5731772/107618165-69e99a80-6c51-11eb-83f2-0724ebc3cf12.png">

### What you expected to happen

they should not group together

### Possible Solution

a workaround would be either using a different exception type, but that's obviously not desirable eg:

```
Sentry.captureException(new Exception("unset user button"));
Sentry.captureException(new RuntimeException("set user button"));
```

another one would be using anonymous classes, also too much boilerplate:

```
        binding.unsetUser.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                Sentry.captureException(new Exception("unset user button"));
            }
        });

        binding.setUser.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                Sentry.captureException(new Exception("unset user button"));
            }
        });
```

last one, maybe the best, creating private methods for each lambda:

```
  private void setUser() {
      Sentry.captureException(new Exception("set user."));
  }

  private void unsetUser() {
      Sentry.captureException(new Exception("unset user."));
  }
```

```
    binding.unsetUser.setOnClickListener(
        view -> unsetUser());

    binding.setUser.setOnClickListener(
        view -> setUser());
```

I believe it should consider inlined functions too:

<img width="882" alt="Screenshot 2021-02-11 at 10 20 42" src="https://user-images.githubusercontent.com/5731772/107619079-e761da80-6c52-11eb-9830-bac1313d3caa.png">

**Comment by BYK** [comment]
@marandaneto is this for @getsentry/visibility?

**Comment by marandaneto** [comment]
@BYK it's related to grouping, but I'd rather close it.
@mitsuhiko told us that lambdas are intentionally ignored because it generates a random name and considering it would be a mess
