### ISSUE TITLE
Not sending to the webhook when the issue happens

### ISSUE THREAD

**Issue by sundar1237** [getsentry/sentry#23820]
## Important Details

How are you running Sentry?
On-Premise (Sentry 21.2.0.dev087d5129) 
Docker version 19.03.9, build 9d988398e7
docker-compose version 1.25.4, build 8d51620a
login using username/password

## Description
as per the suggestion in #23660, i have configured an alert for my project (1 java proejct and 1 spring boot project) sentry and expecting webhool will tirgger.

[What happened]
but i am not getting POST JSON request to my webhook application. Portal triggerred one and normal both are not coming.
but my webhook application is listening a POST JSON request. i confirmed it by curl request. i am getting 200 and message printed in logs. but the messages from sentry not triggered.

## Steps to Reproduce

1. install sentry 21.2
2. configure a project with webhook
3. create alert rule for all events needs to be sent to "legacy integrations"
4. trigger some error and expect for POST Json webhook notification

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant

### What you expected to happen
POST json notification should appear 
[What you think should be happening]

### Possible Solution
some configuration change
![image](https://user-images.githubusercontent.com/4094189/107717404-d1482e80-6cd3-11eb-8049-4a2d30338058.png)
![image](https://user-images.githubusercontent.com/4094189/107717448-f0df5700-6cd3-11eb-97ed-6402e91effce.png)
![image](https://user-images.githubusercontent.com/4094189/107717497-0fdde900-6cd4-11eb-9159-60e325e4ce89.png)

[If you have an idea on how this could be solved include that detail here.]
![image](https://user-images.githubusercontent.com/4094189/107717624-5fbcb000-6cd4-11eb-9049-770f12e31a87.png)

**Comment by BYK** [comment]
@scefali I don't think Webhooks are under "legacy integrations", are they?

**Comment by sundar1237** [comment]
hi BYK, what information you need ?

**Comment by sundar1237** [comment]
even i have changed to Send a notification via "Webhooks" but still no message, help us to get the message.
![image](https://user-images.githubusercontent.com/4094189/107774974-05593900-6d40-11eb-958d-2632e3aecbf6.png)
where can i see the error message about ?

**Comment by BYK** [comment]
>where can i see the error message about ?

`docker-compose logs`?

**Comment by sundar1237** [comment]
[C:\Users\tgdnasu3\home\sentry\docker\compose_logs.txt](url)
[C:\Users\tgdnasu3\home\sentry\docker\sentry_install_log-2021-02-12_11-02-03.txt](url)

**Comment by sundar1237** [comment]
i understood that the issue was related to our corp proxy which is registered in docker.
but anyway you can improve webhook plugin that, it can show the response. so the user can get idea about real issue(proxy).
in this case, i am closing the issue

**Comment by BYK** [comment]
@sundar1237 I think your feature request is a valid one so I'm filing a new issue to track it: #23879
