### ISSUE TITLE
SaaS / On-Premise 2FA Conflict

### ISSUE THREAD

**Issue by hasore** [getsentry/sentry#23824]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

- New 2FA instance of On-Premise/SaaS replaces previous 2FA instance of On-Premise/SaaS.
- Only tested it using same email address on SaaS and On-Premise.
- This was tested using Microsoft Authenticator, didn't try on Google Authenticator, Authy or other apps.

## Steps to Reproduce

1. Register an account on either Sentry Cloud or Sentry Self Hosted and set-up 2FA.
2. Register an account (using same email address) on either Sentry Cloud or another instance of Sentry Self Hosted and set-up 2FA using the same app and device used on step 1.
3. Try to log in on account created on first step.

### What you expected to happen

- A new 2FA Sentry Instance should be created on 2FA application.

### Possible Solution

[If you have an idea on how this could be solved include that detail here.]

**Comment by BYK** [comment]
Thanks a lot for reporting, will look into this ASAP/

**Comment by BYK** [comment]
I can also help if you are willing to submit a PR to fix it. Should be fairly trivial.

**Comment by chadwhitacre** [comment]
Closing as stale, reticket if need be. 🙏
