### ISSUE TITLE
Issue tag/user table % is always "Infinity"

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2382]
Users:

![image](https://cloud.githubusercontent.com/assets/2153/11491180/503d396c-9794-11e5-889f-58eccce81cde.png)

Browser tags:

![image](https://cloud.githubusercontent.com/assets/2153/11491163/2de739c6-9794-11e5-9732-0b20e0d0cb9f.png)

(Ignore my crazy browser tag values – that's unrelated.)

**Comment by benvinegar** [comment]
This appears to be caused because the API is returning `totalValues: null` from `/api/0/issues/2/tags/browser/values/`

cc @dcramer

**Comment by mattrobenolt** [comment]
Hmm, `/tags/<tag>/values/` doesn't even return `totalValues`. It returns a list of objects with a `count` key.

I assume you're referring to `/tags/<tag>/` ?

I haven't seen this in production, and can't see how this would happen. So a link to this happening IRL would be awesome.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
