### ISSUE TITLE
Missing IP range

### ISSUE THREAD

**Issue by kepeder** [getsentry/sentry#23837]
From https://support.atlassian.com/organization-administration/docs/ip-addresses-and-domains-for-atlassian-cloud-products/, the following IP-range is missing 18.246.31.224/28.

[json_log.txt](https://github.com/getsentry/sentry/files/5972832/json_log.txt)

https://github.com/getsentry/sentry/blob/888c94fac6eb5d85bd5069de15f431fd28f7cd2f/src/sentry/integrations/bitbucket/webhook.py#L21

**Comment by BYK** [comment]
Hi @kepeder, thanks for the heads up!

We'd appreciate if you use the issue template next time 🙂

**Comment by manuzope** [comment]
Ah nice. Thanks for pointing that out! Seems like we might even have a wrong list. The list we do have comes from https://support.atlassian.com/bitbucket-cloud/docs/what-are-the-bitbucket-cloud-ip-addresses-i-should-use-to-configure-my-corporate-firewall/ but those look like inbound IPv4 addresses, not outbound.

We'll investigate this further and respond when we've patched it.

**Comment by Christinarlong** [comment]
Closing since no response in a few years
