### ISSUE TITLE
Add proxy capabilities to file scraping

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2385]
We want to be able to support a forward proxy for scraping URLs. In a simple use case, this allows us to put something like Nginx in front of the endpoint. In other cases it would let us funnel (at least some) requests through a centralized endpoint.

Potential solution:
- Create a /internal/source/:projectID/(:version/)? endpoint, which accepts a 'path' query param
  - Requires auth credentials of some sorts, IP limiting could be fine
- Internal endpoint becomes the new `fetch_file` (from JS plugin)
- Old `fetch_file` queries internal endpoint somehow
- Old `fetch_file` behavior can be hooked with some kind of SENTRY_SOURCE_PROXY_ENDPOINT

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
