### ISSUE TITLE
Http Requests where the body is Form is incorrectly formatted 

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry#23862]
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) or self-hosted/on-premise (which version?)
Both 

Which SDK and version?
e.g: JavaScript 5.11.1, .NET 1.2.0
Sentry.AspNetCore 3.0.5 (also tested on 2.8.0)

### Steps to Reproduce
Send a Form request
1. What
2. you
3. did.

### Expected Result
A nice looking Key/Value pair
![image](https://user-images.githubusercontent.com/8229322/107814931-6dfce180-6d51-11eb-9391-2eee36f60420.png)
^ simulated picture with a manually formatted form.

What you thought would happen.

### Actual Result
![image](https://user-images.githubusercontent.com/8229322/107815041-8f5dcd80-6d51-11eb-9fab-9619b58ab827.png)

What actually happened. Maybe a screenshot/recording? Maybe some logs?
Attached Sample https://github.com/lucas-zimerman/Net5SentryRequestIssue
you can try it with POST https://localhost:44306/test
and the body form-data 
```
A 1
B 2
Name test
```

**Comment by bruno-garcia** [comment]
@matejminar might have insight into this

**Comment by matejminar** [comment]
Thanks, our team will investigate what's going on here.

**Comment by priscilawebdev** [comment]
@lucas-zimerman 

I analyzed the issue and concluded that we don't parse formData request response in the frontend.  

In order for this data to look better on our User Interface, I would recommend that you send an object with an empty property and the entire form-data body as a value. Please see:

![image](https://user-images.githubusercontent.com/29228205/108728592-08b3a800-752a-11eb-98a7-4550a0a73f8b.png)


Another option would be to send the data already parsed.

**Comment by lucas-zimerman** [comment]
That should be parsed by the backend or the client SDK.

@bruno-garcia would you like me to give it a try to make a PR for the .NET SDK?

**Comment by bruno-garcia** [comment]
I'm not sure doing this in all SDKs is the way to go though. I'm surprised this never came up before, maybe form data isn't so popular?

Or is the SDK adding this incorrectly?

**Comment by lucas-zimerman** [comment]
> I'm not sure doing this in all SDKs is the way to go through. I'm surprised this never came up before, maybe form data isn't so popular?
> 
> Or is the SDK adding this incorrectly?

Would be nice to validate with other SDKs if they're also outputting the same pattern for form data.

**Comment by priscilawebdev** [comment]
I don't think our SDK parses FormData,  maybe @kamilogorek knows about it?

**Comment by kamilogorek** [comment]
We do not do that.

**Comment by priscilawebdev** [comment]
I believe we can close this issue
