### ISSUE TITLE
feat(webhooks): Send sample payload and request/response details

### ISSUE THREAD

**Issue by BYK** [getsentry/sentry#23879]
## Summary

When adding webhooks to Sentry, it is not possible to see the payload that is sent or the response Sentry got unless one looks at the logs (which is impossible on sentry.io for end-users). It would make developing against webhooks a lot easier if we showed the request/response details like GitHub does for their webhooks.

## Motivation

I think webhooks are the ultimate extension points for Sentry without requiring Sentry team to implement everything themselves. Hence, making this experience smoother would reduce the load on the team both for support and new feature requests while allowing the community to create even more integrations.

## Additional Context

See #23820 as a sample case.

**Comment by manuzope** [comment]
Yea, this would be great. 

Through our internal integration, you can see the [requests that were made and the status code for the responses that are received](https://blog.sentry.io/2020/02/06/sentry-integration-platform-get-insights-on-the-integrations-you-build/) but not the content of the request/response. Adding the request/response body seems like a natural extension to that.

**Comment by manuzope** [comment]
Can't :+1: again but just got another customer requesting this.

**Comment by BYK** [comment]
@manuzope I upvoted my own issue for that ;)

**Comment by JEFFCTSAI** [comment]
Any update on this?

**Comment by leedongwei** [comment]
This idea isn't not being prioritized right now.

**Comment by Christinarlong** [comment]
This is technically done. Developers can see the request and response bodies for their custom integration's webhooks under the 'dashboard' pages network requests.
