### ISSUE TITLE
GroupSeenBy.render occasionally throws exception (seenBy is undefined)

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2387]
https://app.getsentry.com/sentry/javascript/issues/88970365/

**Comment by dcramer** [comment]
Some notes here on how I could see this happening

- I'm viewing stream, realtime is enabled, lots of updates are happening
- I click a group, while a realtime poll in in progress
- The group details loads, clears GroupStore, loads the group
- The polling response comes back in (even though it was cancelled?) and updates the group store with the false data?

It's possible that the order of the last two is inverted, but its the only thing that makes sense.

**Comment by mattrobenolt** [comment]
https://app.getsentry.com/sentry/javascript/issues/97215607/

This exception seems to provide a much much better stacktrace that goes all the way from API call through React into group details. One thing to note is that it is going through the streamManager in the same call stack.

This is also an issue for other things, like: https://app.getsentry.com/sentry/javascript/issues/99474012/

Which is the same thing, except for `group.tags`.
