### ISSUE TITLE
Add target to configure direnv fully

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#23887]
Some devs would end up with `direnv` installed but without `eval "$(direnv hook zsh)"` in their start-up scripts, thus, not actually doing anything.

I want to add a make target that would verify that we have that line properly added similar to how we resolved it for `pyenv`:
https://github.com/getsentry/sentry/pull/23628

**Comment by bc-sentry** [comment]
If this is still an issue, please reopen.  Thanks.
