### ISSUE TITLE
Change of behavior for `re.escape` in Python 3.7+ and error translations

### ISSUE THREAD

**Issue by tonyo** [getsentry/sentry#23880]
We have a failing test in `JavascriptIntegrationTest` when running against Python 3.8: https://github.com/getsentry/sentry/runs/1904647403#step:10:137

```
Error: JavascriptIntegrationTest.test_error_message_translations

AssertionError: assert 'ReferenceErr...on extensible' == 'ReferenceErro...ot extensible'
  - ReferenceError: Impossible de définir une propriété « foo » : objet non extensible
  + ReferenceError: Cannot define property 'foo': object is not extensible
__________ JavascriptIntegrationTest.test_error_message_translations ___________
```

The cause of the error seems to be the changed behavior of `re.escape` in Python 3.7+, which is called here: https://github.com/getsentry/sentry/blob/d64c4f79860b8eea983bfef07e79734a12850f6a/src/sentry/lang/javascript/errorlocale.py#L27

Here's what the Python docs (https://docs.python.org/3.8/library/re.html#re.escape) say about the change:

> Changed in version 3.7: Only characters that can have special meaning in a regular expression are escaped. As a result, '!', '"', '%', "'", ',', '/', ':', ';', '<', '=', '>', '@', and "`" are no longer escaped.

### Is this the only issue related to the behavior change? 

All other places where we use `re.escape` seem to be unaffected.

**Comment by joshuarli** [comment]
Did some more digging around in pdb, it's because we fail to replace `\%s` since % indeed isn't escaped to `\\%` in 3.7+. Fix is to remove that single slash.
