### ISSUE TITLE
Sentry.io is not working properly

### ISSUE THREAD

**Issue by ishan-biztech** [getsentry/sentry#23936]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

When I navigate to https://sentry.io/auth/login/ it doesn't load the static assets(css, js, etc.) properly, it was working till yesterday but today it doesn't work in any browser.

Refer the screenshot

![sentry_io_not_working](https://user-images.githubusercontent.com/61005017/108322669-c1f14580-71eb-11eb-8a05-149e6f7afa03.png)

## Steps to Reproduce

1. Navigate to https://sentry.io/auth/login

Good items to include here include:

Please see console errors:

![sentry_io_console_error](https://user-images.githubusercontent.com/61005017/108322911-0aa8fe80-71ec-11eb-9ffa-9502254f8acb.png)

### What you expected to happen

It should work fine.

**Comment by BYK** [comment]
It seems like your browser is blocking these requests. Are you using an ad blocker of some sorts?

**Comment by ishan-biztech** [comment]
No I'm not using any Ad blocker, but looks like it was blocked from our firewall. It is fixed after our server admin unblocked sentry CDN URL.
