### ISSUE TITLE
Long digest culprit lines aren't truncated, and can flow out of container.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#2395]
This also causes the level label width to get messed up.

Using `?seed=12` (http://dev.getsentry.com:8000/debug/mail/digest/?seed=123456) provides a good example.

**Comment by tkaemming** [comment]
@ckj: Let me know if there's a good way to this with CSS, otherwise I will just truncate the culprit to a max length.

**Comment by ckj** [comment]
@tkaemming Unfortunately `text-overflow` and `max-width` aren't widely supported (e.g. Outlook doesn't support either of them), so we'll have to truncate. Look like cutting it at 45 chars would do the trick:

![screen shot 2015-12-04 at 11 20 28 am](https://cloud.githubusercontent.com/assets/30713/11598838/1019386c-9a79-11e5-942d-7c6dcf6e928c.png)
