### ISSUE TITLE
Change select all behavior in stream

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2397]
Let's just mimic GMail so its more obvious.

- Tick "select all" box (or select all items on screen and itemsSelected === pageSIze)
- Show a box to "Selected 25 items. [link]Select all matching items[/link]" and have that box be the indicator if only the on-page selection is active or if, on the backend, it should select all matching the filter

**Comment by dcramer** [comment]
@benvinegar you think this is something we could very quickly? Would be cool to fix this pre-8.0

**Comment by benvinegar** [comment]
Sure. I think I'd need some design help / mockups to have a better idea of what this looks like.

**Comment by dcramer** [comment]
@benvinegar imo we just 100% mimic gmail -- i can help w/ css but i think itll be easy

https://www.dropbox.com/s/rtchj76ogs1llxo/Screenshot%202015-12-03%2016.08.25.png?dl=0

https://www.dropbox.com/s/u82bsgmjsi17n6a/Screenshot%202015-12-03%2016.08.31.png?dl=0

**Comment by benvinegar** [comment]
No problemo boss.

**Comment by benvinegar** [comment]
#2400
