### ISSUE TITLE
U2F - device name set by user is ignored and random one is picked instead.

### ISSUE THREAD

**Issue by gbdlin** [getsentry/sentry#24001]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

When registering new U2F device for 2factor authentication, there is a field for device name, but when providing custom one, it is ignored. Maybe there is some validation that my input is not passing, but it is not being shown?

## Steps to Reproduce

1. Login to your account
2. Go to security settings
3. Set up U2F device in Two-Factor Authentication section. Provide custom name for newly set up device. For example: "Yubi C 22 NFC"
4. After setup, go back to Two-Factor settings and open U2F devices list
5. Observe the result

### What you expected to happen

Device should appear on the list with custom name provided in step 3.

### What actually happens?

Device appears on the list with randomly generated name.

## Things to consider

Consider adding device name edit button, so users affected by this issue in the past will be able to fix their device names without enrolling them again.

**Comment by chadwhitacre** [comment]
Thanks for the report, @gbdlin. Routing to our team that handles auth for triage.

**Comment by leedongwei** [comment]
Hi @gbdlin. Thanks for the bug report! I have replicated the issue. 

While it's an annoying bug, it's not breaking U2F functionality. I'll add it to our backlog and we'll fix it in a future sprint.

**Comment by mologie** [comment]
Regarding things to consider: In addition to an edit name button I would appreciate a "last used on" date, similar to how Google does it, so that we can identify the key we logged in with. I have one primary and a backup key and no indicator to decide which is which now (apart from maybe just deleting them).

**Comment by gbdlin** [comment]
And for that reason, it may actually be a security issue for some, as for now, when you have multiple keys and you loose one of them, it is not trivial to remove only one that was lost. It is also impossible to remove all of them without decreasing security of your account (even temporary).

**Comment by bowencai8** [comment]
Hi @gbdlin we're going to add this to our backlog, but unfortunately won't have capacity to work on this in the near-term.

I'll provide updates on this thread when we pick it up. Thanks!

**Comment by leedongwei** [comment]
Fixed in https://github.com/getsentry/sentry/pull/24438 and https://github.com/getsentry/sentry/pull/25312

**Comment by leedongwei** [comment]
Hi @gbdlin, we'll be merging the fix later today.

Special shoutout to @3ka5-cat for submitting the patch.

Please let me know if it's still broken for y'all and I'll reopen the issue.

**Comment by gbdlin** [comment]
Thanks! I guess there is still no way to identify existing U2F devices after the fact to name them properly without re-enrolling?
