### ISSUE TITLE
API: List a Project's Issues: Expose "Matching Events" in "stats" field - just like in the UI

### ISSUE THREAD

**Issue by Nowaker** [getsentry/sentry#24043]
## Summary

Search query: `user.id:someuser`. In UI:

![image](https://user-images.githubusercontent.com/611746/108887276-a8774180-75cf-11eb-8675-e1dbba0b32f6.png)

In API (example):

```json
    "stats": {
      "14d": [
        [1612915200, 0],
        [1613001600, 13]
      ]
    }
```
`1613001600` is the timestamp, and `13` is `Total Events`.

`Matching Events` is not available. Searches via API are therefore extremely limited. I cannot find issues that a given user was actually affected by in a given time period.

## Motivation

The UI exposes this data because not doing so would be detrimental to the experience.

API should expose this data too.

```json
    "stats": {
      "14d": [
        [1612915200, 0, 0],
        [1613001600, 13, 4]
      ]
    }
```

`1613001600` is the timestamp, and `13` is `Total Events`, `4` is `Matching Events`.

**Comment by Nowaker** [comment]
@chadwhitacre Can you reopen? Thanks.

**Comment by chadwhitacre** [comment]
Sure thing @Nowaker, sorry for the noise and thanks for the ticket. Routing to @getsentry/ecosystem for [triage](https://www.notion.so/sentry/How-to-Process-Issues-PRs-e9657c0fa77d407ebe7c878076f63e35#0b4da6c630c84c26beafc0f9bb3b4844) [internal].

**Comment by manuzope** [comment]
Hmmm, I don't think we'll be able to make this exact change because it'll be a breaking API change. But maybe we can offer another public API or some other attribute within this API to facilitate this. @getsentry/workflow is probably a better team to address that.

**Comment by Nowaker** [comment]
@manuzope For it to be non-breaking, it would be as easy as keeping "stats" the same, and adding "stats_matching" as a new field.

**Comment by scttcper** [comment]
The matching events the ui is using can be found under `$.filtered.stats` where you'll find the same stats array but with the matching counts. Make sure you are not passing the `collapse=stats` query parameter to the search api.

**Comment by Nowaker** [comment]
@scttcper Not sure how to interpret your answer. What is search API and is there a link to the reference? It's not here https://docs.sentry.io/api/

**Comment by scttcper** [comment]
@Nowaker I was referring to the endpoint used on the page you screenshotted `/api/0/organizations/:orgId/issues/?statsPeriod=14d&project=123&limit=25&query=xx`

**Comment by Nowaker** [comment]
@scttcper Oh! An undocumented API endpoint! And it works!
```
curl -H "Authorization: Bearer ${SENTRY_TOKEN}" 'https://sentry.io/api/0/organizations/ORGID/issues/?project=PROJECTID&query=user.id%3Anowaker&statsPeriod=14d' | jq
```

Can you guys review all your available API endpoints and make sure they're all listed at https://docs.sentry.io/api/? Thanks!

**Comment by BYK** [comment]
@Nowaker we are doing that slowly but certain endpoints are still in flux so we don't want to make them public until we know they are stable.

Do you think we can close this issue now?

@chadwhitacre maybe we can have a "tips and tricks" section in docs or something for things like these?

**Comment by chadwhitacre** [comment]
>> Can you guys review all your available API endpoints and make sure they're all listed at https://docs.sentry.io/api/?
>
> we are doing that slowly but certain endpoints are still in flux so we don't want to make them public until we know they are stable.

If this is true then @manuzope @jonesphillip would this be a good candidate for a "Share the Roadmap" long-lived epic/issue to gather input and track progress with the community? Something like "Roll out API v1"? Let's discuss at our next weekly sync.

> maybe we can have a "tips and tricks" section in docs or something for things like these?

Could do as a bandaid, otoh this thread is public so maybe it suffices?

One way or another, I agree let's close here.
