### ISSUE TITLE
Inbound Filters not working in Sentry v.21.1.0 (on-premise)

### ISSUE THREAD

**Issue by lovaiible** [getsentry/sentry#24068]
## Important Details

How are you running Sentry?
On-Premise w/ Docker, version 21.0.0

## Description

We have recently updated our Sentry version to 21.0.0 from a 20.x.x version (I guess it was 20.7.2 but I'm not too sure).
Currently as well as in the previous installed version, we have used inbound filters to sort out all events coming from `localhost`. However after the update, this filter is not working anymore, as you can see in the screenshot below -> there are no localhost events listed in the ERRORS FILTERED IN THE LAST 30 DAYS (BY DAY) diagram

![image](https://user-images.githubusercontent.com/33764166/109028649-506d3780-76c2-11eb-930c-1751a45e5067.png)

## Steps to Reproduce

1. Go to Settings -> Project -> Inbound Filters
2. The filter for filtering out localhost events is activated
3. Cause an error from a localhost URL -> event is not filtered

I don't know where this error originates from. I have also disabled the filter and enabled it again, but the behaviour is still the same. I have included our sentry configuration down below, if that helps you with the analysis. If you need more information, please let me know.

sentry.config
<details>
{
	"config.yml": "system.secret-key: `<secret<`
		postprocess.use-cache-key: 1.0
		
		# This URL will be used to tell Symbolicator where to obtain the Sentry source.
		# See https://getsentry.github.io/symbolicator/api/
		system.internal-url-prefix: 'http://sentry-web:9000'
		symbolicator.enabled: false
		
		##########
		# Github #
		##########
		
		##########
		# Google #
		##########
		
		#########
		# Slack #
		#########
		
		#########
		# Redis #
		#########
		redis.clusters:
		  default:
		    hosts:
		      0:
		        host: \"sentry-sentry-redis-master\"
		        port: 6379
		        password: `<pw<`
		
		################
		# File storage #
		################
		# Uploaded media uses these `filestore` settings. The available
		# backends are either `filesystem` or `s3`.
		filestore.backend: \"filesystem\"
		filestore.options:
		  location: \"/var/lib/sentry/files\"",
	"sentry.conf.py": "from sentry.conf.server import *  # NOQA
		from distutils.util import strtobool
		
		DATABASES = {
		    \"default\": {
		        \"ENGINE\": \"sentry.db.postgres\",
		        \"NAME\": \"sentry\",
		        \"USER\": \"postgres\",
		        \"PASSWORD\": `<pw<`
		        \"HOST\": \"sentry-sentry-postgresql\",
		        \"PORT\": 5432,
		    }
		}
		
		# You should not change this setting after your database has been created
		# unless you have altered all schemas first
		SENTRY_USE_BIG_INTS = True
		
		###########
		# General #
		###########
		
		# Instruct Sentry that this install intends to be run by a single organization
		# and thus various UI optimizations should be enabled.
		SENTRY_SINGLE_ORGANIZATION = True
		
		SENTRY_OPTIONS[\"system.event-retention-days\"] = int(env('SENTRY_EVENT_RETENTION_DAYS') or 90)
		
		#########
		# Queue #
		#########
		
		# See https://docs.getsentry.com/on-premise/server/queue/ for more
		# information on configuring your queue broker and workers. Sentry relies
		# on a Python framework called Celery to manage queues.
		BROKER_URL = `<broker_url>`
		
		#########
		# Cache #
		#########
		
		# Sentry currently utilizes two separate mechanisms. While CACHES is not a
		# requirement, it will optimize several high throughput patterns.
		
		# CACHES = {
		#     \"default\": {
		#         \"BACKEND\": \"django.core.cache.backends.memcached.MemcachedCache\",
		#         \"LOCATION\": [\"memcached:11211\"],
		#         \"TIMEOUT\": 3600,
		#     }
		# }
		
		# A primary cache is required for things such as processing events
		SENTRY_CACHE = \"sentry.cache.redis.RedisCache\"
		
		DEFAULT_KAFKA_OPTIONS = {
		    \"bootstrap.servers\": \"sentry-kafka:9092\",
		    \"message.max.bytes\": 50000000,
		    \"socket.timeout.ms\": 1000,
		}
		
		SENTRY_EVENTSTREAM = \"sentry.eventstream.kafka.KafkaEventStream\"
		SENTRY_EVENTSTREAM_OPTIONS = {\"producer_configuration\": DEFAULT_KAFKA_OPTIONS}
		
		KAFKA_CLUSTERS[\"default\"] = DEFAULT_KAFKA_OPTIONS
		
		###############
		# Rate Limits #
		###############
		
		# Rate limits apply to notification handlers and are enforced per-project
		# automatically.
		
		SENTRY_RATELIMITER = \"sentry.ratelimits.redis.RedisRateLimiter\"
		
		##################
		# Update Buffers #
		##################
		
		# Buffers (combined with queueing) act as an intermediate layer between the
		# database and the storage API. They will greatly improve efficiency on large
		# numbers of the same events being sent to the API in a short amount of time.
		# (read: if you send any kind of real data to Sentry, you should enable buffers)
		
		SENTRY_BUFFER = \"sentry.buffer.redis.RedisBuffer\"
		
		##########
		# Quotas #
		##########
		
		# Quotas allow you to rate limit individual projects or the Sentry install as
		# a whole.
		
		SENTRY_QUOTAS = \"sentry.quotas.redis.RedisQuota\"
		
		########
		# TSDB #
		########
		
		# The TSDB is used for building charts as well as making things like per-rate
		# alerts possible.
		
		SENTRY_TSDB = \"sentry.tsdb.redissnuba.RedisSnubaTSDB\"
		
		#########
		# SNUBA #
		#########
		
		SENTRY_SEARCH = \"sentry.search.snuba.EventsDatasetSnubaSearchBackend\"
		SENTRY_SEARCH_OPTIONS = {}
		SENTRY_TAGSTORE_OPTIONS = {}
		
		###########
		# Digests #
		###########
		
		# The digest backend powers notification summaries.
		
		SENTRY_DIGESTS = \"sentry.digests.backends.redis.RedisBackend\"
		
		##############
		# Web Server #
		##############
		
		SENTRY_WEB_HOST = \"0.0.0.0\"
		SENTRY_WEB_PORT = 9000
		SENTRY_PUBLIC = False
		SENTRY_WEB_OPTIONS = {
		    \"http\": \"%s:%s\" % (SENTRY_WEB_HOST, SENTRY_WEB_PORT),
		    \"protocol\": \"uwsgi\",
		    # This is needed to prevent https://git.io/fj7Lw
		    \"uwsgi-socket\": None,
		    \"http-keepalive\": True,
		    \"memory-report\": False,
		    # 'workers': 3,  # the number of web workers
		}
		
		###########
		# SSL/TLS #
		###########
		
		# If you're using a reverse SSL proxy, you should enable the X-Forwarded-Proto
		# header and enable the settings below
		
		# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
		# SESSION_COOKIE_SECURE = True
		# CSRF_COOKIE_SECURE = True
		# SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
		
		# End of SSL/TLS settings
		
		############
		# Features #
		############
		
		
		SENTRY_FEATURES = {
		  \"auth:register\": True
		}
		SENTRY_FEATURES[\"projects:sample-events\"] = False
		SENTRY_FEATURES.update(
		    {
		        feature: True
		        for feature in (\"organizations:advanced-search\",
		            \"organizations:android-mappings\",
		            \"organizations:api-keys\",
		            \"organizations:boolean-search\",
		            \"organizations:related-events\",
		            \"organizations:alert-filters\",
		            \"organizations:custom-symbol-sources\",
		            \"organizations:data-forwarding\",
		            \"organizations:discover\",
		            \"organizations:discover-basic\",
		            \"organizations:discover-query\",
		            \"organizations:enterprise-perf\",
		            \"organizations:event-attachments\",
		            \"organizations:events\",
		            \"organizations:global-views\",
		            \"organizations:incidents\",
		            \"organizations:metric-alert-builder-aggregate\",
		            \"organizations:metric-alert-gui-filters\",
		            \"organizations:integrations-event-hooks\",
		            \"organizations:integrations-issue-basic\",
		            \"organizations:integrations-issue-sync\",
		            \"organizations:integrations-alert-rule\",
		            \"organizations:integrations-chat-unfurl\",
		            \"organizations:integrations-incident-management\",
		            \"organizations:integrations-ticket-rules\",
		            \"organizations:integrations-vsts-limited-scopes\",
		            \"organizations:integrations-stacktrace-link\",
		            \"organizations:internal-catchall\",
		            \"organizations:invite-members\",
		            \"organizations:large-debug-files\",
		            \"organizations:monitors\",
		            \"organizations:onboarding\",
		            \"organizations:org-saved-searches\",
		            \"organizations:performance-view\",
		            \"organizations:project-detail\",
		            \"organizations:relay\",
		            \"organizations:release-performance-views\",
		            \"organizations:rule-page\",
		            \"organizations:set-grouping-config\",
		            \"organizations:custom-event-title\",
		            \"organizations:slack-migration\",
		            \"organizations:sso-basic\",
		            \"organizations:sso-rippling\",
		            \"organizations:sso-saml2\",
		            \"organizations:sso-migration\",
		            \"organizations:stacktrace-hover-preview\",
		            \"organizations:symbol-sources\",
		            \"organizations:transaction-comparison\",
		            \"organizations:usage-stats-graph\",
		            \"organizations:inbox\",
		            \"organizations:unhandled-issue-flag\",
		            \"organizations:invite-members-rate-limits\",
		            \"organizations:dashboards-v2\",
		
		            \"projects:alert-filters\",
		            \"projects:custom-inbound-filters\",
		            \"projects:data-forwarding\",
		            \"projects:discard-groups\",
		            \"projects:issue-alerts-targeting\",
		            \"projects:minidump\",
		            \"projects:rate-limits\",
		            \"projects:sample-events\",
		            \"projects:servicehooks\",
		            \"projects:similarity-view\",
		            \"projects:similarity-indexing\",
		            \"projects:similarity-view-v2\",
		            \"projects:similarity-indexing-v2\",
		            \"projects:reprocessing-v2\",
		
		            \"projects:plugins\",
		        )
		    }
		)
		
		#######################
		# Email Configuration #
		#######################
		SENTRY_OPTIONS['mail.backend'] = os.getenv(\"SENTRY_EMAIL_BACKEND\", \"dummy\")
		SENTRY_OPTIONS['mail.use-tls'] = bool(strtobool(os.getenv(\"SENTRY_EMAIL_USE_TLS\", \"false\")))
		SENTRY_OPTIONS['mail.username'] = os.getenv(\"SENTRY_EMAIL_USERNAME\", \"\")
		SENTRY_OPTIONS['mail.password'] = os.getenv(\"SENTRY_EMAIL_PASSWORD\", \"\")
		SENTRY_OPTIONS['mail.port'] = int(os.getenv(\"SENTRY_EMAIL_PORT\", \"25\"))
		SENTRY_OPTIONS['mail.host'] = os.getenv(\"SENTRY_EMAIL_HOST\", \"\")
		SENTRY_OPTIONS['mail.from'] = os.getenv(\"SENTRY_EMAIL_FROM\", \"\")
		
		#########################
		# Bitbucket Integration #
		########################
		
		# BITBUCKET_CONSUMER_KEY = 'YOUR_BITBUCKET_CONSUMER_KEY'
		# BITBUCKET_CONSUMER_SECRET = 'YOUR_BITBUCKET_CONSUMER_SECRET'
		
		#########
		# Relay #
		#########
		SENTRY_RELAY_WHITELIST_PK = []
		SENTRY_RELAY_OPEN_REGISTRATION = True
		
		# No Python Extension Config Given"
}
</details>

### What you expected to happen
I would like that the filter works again with the Sentry Version 21.1.0 and sorts out all localhost events.

**Comment by chadwhitacre** [comment]
Thanks @lovaiible, routing to @getsentry/owners-ingest for [triage](https://www.notion.so/sentry/How-to-Process-Issues-PRs-e9657c0fa77d407ebe7c878076f63e35#0b4da6c630c84c26beafc0f9bb3b4844) [internal].

**Comment by jjbayer** [comment]
Hi @lovaiible, could you please share the event payload (issue view -> "JSON") of an example event that should be filtered? Especially the "sdk", "user" and "request" fields would be interesting. Thank you!

**Comment by lovaiible** [comment]
Hi @jjbayer, sorry I somehow missed your message here. I have inserted the payload fields that you have requested down below. Please let me know if you need further information. Thank you!

skd:
`"sdk": {
    "name": "sentry.javascript.browser",
    "version": "5.22.3",
    "integrations": [
      "GlobalHandlers",
      "TryCatch",
      "LinkedErrors",
      "UserAgent",
      "FunctionToString",
      "InboundFilters",
      "Breadcrumbs"
    ],
    "packages": [
      {
        "name": "npm:@sentry/browser",
        "version": "5.22.3"
      }
    ]
},`

user:
`"user": {
  "ip_address": {
    "": {
      "rem": [
        [
          "@anything:remove",
          "x"
        ]
      ]
    }
  }
}`

request:
`"request": {
  "url": "http://localhost:8080/subscriptions/e2e-QC3-AGL",
  "headers": [
    [
      "User-Agent",
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.157 Safari/537.36"
    ]
  ]
},`

**Comment by jjbayer** [comment]
@lovaiible Thank you for the information! Unfortunately, I wasn't able to reproduce the issue after upgrading a fresh install of [onpremise](https://github.com/getsentry/onpremise) version 20.7.2 to 21.1.0, using the config you provided. What version of Relay are you running? Could you maybe also share the contents of `relay/config.yml`?

**Comment by lovaiible** [comment]
@jjbayer actually we don't run any relay configurations except the snippets in the sentry.config. We deploy the helm charts without any major changes or extra configurations.

**Comment by chadwhitacre** [comment]
@lovaiible Since we don't maintain any helm charts we can't help with that specifically. If you're able to reproduce the issue using the stock docker-compose onpremise setup let us know and we can reopen this issue. Thanks! :-)
