### ISSUE TITLE
Abstract async React components

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2406]
We have a common pattern in components of:
- get state parameters from props
- load data (fetchData)
- when finished render component

This is especially common in our views/containers, and many times we also handle a loading/error state of these components in a fairly uniform way.

Ideally we could abstract a lot of this logic into some helper class. Effectively it'd describe a set of promises that need resolved (i.e. could be multiple API endpoints) and handle the loading/error states. It would also handle cancelling promises (i.e. api.clear in this case).

**Comment by benvinegar** [comment]
https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/app/components/asyncComponent.jsx
