### ISSUE TITLE
Add signals for options changing value

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2408]
It'd be nice to register signal receivers for when options change value, to derive values like `settings.ALLOWED_HOSTS` properly.

This would need to be handled on `options.get()` as well as `options.set()`. We need to do this here since if another process mutates the value, we need to know when it has changed according to the next read. So we don't want to rely solely on `set()`.

This also means we'll have to keep track of a last known value all the time which kinda goes against how it's handled now with `grace` and the periodic cleanups.

Might want to hand onto values beyond grace, if there's a signal receiver only?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
