### ISSUE TITLE
Failure to retrieve Slack team information when using the integration

### ISSUE THREAD

**Issue by jonathandey** [getsentry/sentry#24097]
### Version Information

Using onpremise installation;
Version: 21.2.0

### Steps to Reproduce

1. Configure slack as per documentation: https://develop.sentry.dev/integrations/slack/
2. Tried to add a Workspace in the Slack integration: /settings/animo/integrations/slack/ 
3. Got an invalid auth (`invalid_auth`) error from Slack (Could not retrieve Slack team information)

### Expected Result

Sentry would add the Slack workspace without an auth error.

The cause of the error appears to be how the token field is passed in the request. Currently, it is being passed as an argument, but Slack's documentation states that it should be passed as an Auth header (for a GET request) or as a field in a POST request, see here: https://api.slack.com/methods/team.info

### Actual Result

![slack-sentry-error](https://user-images.githubusercontent.com/634009/109172847-1c098200-777b-11eb-9263-95c11560c02f.jpeg)

### Logs

What you saw along the way, e.g.:

```
integration.http_response

status_string: 200

integration: slack
```

```
slack.team-info.response-error
```

**Comment by BYK** [comment]
This looks legit (just a slight deviation from the template) so reopening for routing.

**Comment by BYK** [comment]
Quite sure this was resolved by #24131 so closing. Heads up to @MeredithAnya in case this is not correct.

This fix will be out in the upcoming release (21.3.0) on March 15th. You can also use the nightlies until then if you cannot wait.

**Comment by jonathandey** [comment]
@BYK I recreated the issue here https://github.com/getsentry/sentry/issues/24098 after the bot warned me of the mistake

**Comment by BYK** [comment]
@jonathandey, ah sorry for the noise then. I was just going through my emails after a short OOO :)

**Comment by jonathandey** [comment]
@BYK - no problem, thanks for taking a look!
