### ISSUE TITLE
Automatically discovery CLI commands with pkgutil

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2410]
Something like: https://github.com/pypa/warehouse/blob/master/warehouse/cli/__init__.py#L43-L46

**Comment by dcramer** [comment]
I don't think we really need this complexity. Auto discovery is always a pain in the ass

**Comment by mattrobenolt** [comment]
This would be simply to replace this: 

https://github.com/getsentry/sentry/blob/master/src/sentry/runner/__init__.py#L29-L41

I didn't mean autodiscovery between all apps, just to import all of `sentry.runner.commands.*` to replace these strings.

**Comment by dcramer** [comment]
@mattrobenolt you can just copy paste code from ``models/__init__`` or similar, we do this in a number of places

**Comment by Dannywanxyz** [comment]
@dcramer how do i setup avatar in sentry?it seems that it doesn't work.
![image](https://cloud.githubusercontent.com/assets/13790928/11705104/683b4c98-9f28-11e5-8960-0ac89ae9c2ad.png)

**Comment by mattrobenolt** [comment]
@Dannywanxyz can you please not post off topic things into random issues?

Please open a new issue if there's a problem.

**Comment by Dannywanxyz** [comment]
@mattrobenolt got it.i am a rookie,sorry about that!

**Comment by BYK** [comment]
I think this is done in our Docker images now in a somewhat hacky but working manner.

Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
