### ISSUE TITLE
Prompt install wizard with options filled in instead of nothing

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2411]
For first install, we should show them with their options prefilled, instead of showing a useless screen with nothing to do.

/cc @dcramer

**Comment by mattrobenolt** [comment]
Going to have to spit back a `firstTimeInstall` key for the UI to render fields even if they are populated.

**Comment by dcramer** [comment]
you can just pretend it has no value but the default value is available

**Comment by mattrobenolt** [comment]
Sure, but right now, we conditionally show fields only if they have options that aren't set. So subsequent upgrades don't re-prompt for all the options.

So I need to special case a first time install, to prompt for them anyways.
