### ISSUE TITLE
Add more known Mobile UserAgents

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry#24119]
## Summary

Add more known Mobile UserAgents
https://github.com/getsentry/sentry/blob/c860b0675f46a6f603d22542c2c57e59fb7c358c/src/sentry/static/sentry/app/components/suggestProjectCTA.tsx#L32

## Motivation

We'd like to target broader mobile Apps and show the CTA dialog

**Comment by marandaneto** [comment]
@philipphofmann @bruno-garcia let's work on it together, I know a few more and will collect them.

**Comment by scefali** [comment]
@marandaneto Thanks for making this issue!

**Comment by marandaneto** [comment]
`android-async-http` for Android, starts with `Android Asynchronous`

https://github.com/android-async-http/android-async-http/blob/a443353a6dc2124ad5b05cfe8aa09deb5f2f9467/library/src/main/java/com/loopj/android/http/AsyncHttpClient.java#L634-L642

**Comment by philipphofmann** [comment]
For Cocoa: 

- [AFNetworking](https://github.com/AFNetworking/AFNetworking)
- [RestKit](https://github.com/RestKit/RestKit)
- [ASIHTTPRequest](https://github.com/pokeb/asi-http-request)
- [CocoaAsyncSocket](https://github.com/robbiehanson/CocoaAsyncSocket)
- [Siesta](https://github.com/bustoutsolutions/siesta)
- [Moya](https://github.com/Moya/Moya)
- [APIKit](https://github.com/ishkawa/APIKit)
- [Networking](https://github.com/3lvis/Networking)
- [YTKNetwork](https://github.com/yuantiku/YTKNetwork)

Taken from https://github.com/vsouza/awesome-ios#networking

**Comment by marandaneto** [comment]
@philipphofmann it'd be nice if you help me out in finding the hardcoded userAgents from those libs, if open-source, searching for user-agent would be easy, I did for Android already

**Comment by philipphofmann** [comment]
The SDKs using the `user-agent` put  `iOS`, `tvOS`, `watchOS` or `Mac OS X` into the header with some other info. @marandaneto do you know if we can check if the header contains these?

**Comment by marandaneto** [comment]
This does not exist anymore.
