### ISSUE TITLE
Wizard Error

### ISSUE THREAD

**Issue by aryeh-looker** [getsentry/sentry#2419]
Thanks for all your wonderful work on Sentry. I am running a recently release (`b8a1d52e40e728668dba1b2bc4f16517f081f2f8`)

I have `system.admin-email` set in `config.yml`. I get the following error after I start Sentry:

`We were unable to submit your changes to the Sentry server. Please take a look at the service logs.`

<img width="741" alt="screen shot 2015-12-07 at 6 12 35 pm" src="https://cloud.githubusercontent.com/assets/12849602/11646012/3e44647c-9d0e-11e5-9ac0-c7275611277e.png">

Would be happy to send over log trace — but not clear on the best way to enable logging.

**Comment by mattrobenolt** [comment]
You definitely caught this on the bleeding edge. :)

What happens if you remove `system.admin-email` from your `config.yml`?

This shouldn't be a problem either way, just checking.

**Comment by dcramer** [comment]
@aryeh-looker what you want to look at would be the JS console (what response did it return) in addition to the webserver log

**Comment by dcramer** [comment]
Also we should sort out error handling (proper) and whatever this is before we tag 8.0-RC1

**Comment by dcramer** [comment]
5162f0a87e46c448e445bf7f1e46351706330d0d handles this better

we should basically never blindly catch exceptions in the API as it masks the error (so it would never be reported on the server)

**Comment by aryeh-looker** [comment]
@mattrobenolt same issue when removing the line from the YAML file

**Comment by aryeh-looker** [comment]
JS console indicates a `401 Unauthorized`:

<img width="1315" alt="screen shot 2015-12-07 at 6 51 34 pm" src="https://cloud.githubusercontent.com/assets/12849602/11646512/9ae2eb18-9d13-11e5-9f05-079d2f1fd496.png">

**Comment by mattrobenolt** [comment]
Oh, this indicates that you should be logged in as a super user. Not sure how you're seeing that without already having permission to do so.

Can you GET that url?

**Comment by aryeh-looker** [comment]
@mattrobenolt Definitely was logged in as a super user! I upgraded to `5162f0a87e46c448e445bf7f1e46351706330d0d` and I was able to get into the app. If I do a `GET` on the URL I get a JSON blob back:

<img width="521" alt="get" src="https://cloud.githubusercontent.com/assets/12849602/11646689/4aa69a4e-9d15-11e5-9998-2e977ccc554e.png">

**Comment by aryeh-looker** [comment]
Note that `value` under `system.admin-email` was populated but I scrubbed it for privacy

**Comment by mattrobenolt** [comment]
Oh, so to confirm, after upgrading to that sha, things are fine now? I'm trying to reproduce locally now and was unable to.

**Comment by dcramer** [comment]
I wonder if this is an issue with the domain changing/similar so that the session cookie is invalid?

**Comment by mattrobenolt** [comment]
That would definitely happen if the domain changed. But I can't see how the page would load at one url, then PUT back to a different one to save.

**Comment by mattrobenolt** [comment]
Ok, so I tracked this issue down to a CSRF failure. I'm 90% sure that's what you hit and I can reproduce it now consistently after clearing my cookies.
