### ISSUE TITLE
Confusing error rate histogram

### ISSUE THREAD

**Issue by andreif** [getsentry/sentry#2421]
It's somehow hard to find error rate after a big event due to small rates shown exactly as zero rate, so I have to hover mouse to see where it's 0, and where it's not:

<img src='http://i.imgur.com/DPpvIEd.png'>

Maybe we can show zero as zero level, and anything >= 1 as first bin so it's visually easy to find such rates.

**Comment by dcramer** [comment]
@andreif we definitely agree -- we're redoing charts very soon, though might not make our 8.0 release cutoff date. We have a few things we're aiming for as part of that:

1. We'll show 'zero' entries differently
2. We'll give an idea of chart scale
3. We'll show "no data at all" differently
4. We'll improve visuals/data on the chart
