### ISSUE TITLE
SAML2 Azure AD Authentication error: Failed to map SAML attributes

### ISSUE THREAD

**Issue by KoSoVaR** [getsentry/sentry#24248]
## Important Details

How are you running Sentry? On-Premise w/ Docker, version 20.7.0.dev0

## Description

SAML2 with Azure AD produces an Authentication error

`Authentication error: Failed to map SAML attributes. Assertion returned the following attribute keys: ['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name', 'http://schemas.microsoft.com/identity/claims/identityprovider', 'http://schemas.microsoft.com/identity/claims/tenantid', 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname', 'http://schemas.microsoft.com/identity/claims/displayname', 'http://schemas.microsoft.com/identity/claims/objectidentifier', 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname', 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress', 'http://schemas.microsoft.com/claims/authnmethodsreferences']`

## Steps to Reproduce

1. Visit Settings > Auth and select SAML2 as a provider
2. Use Metadata URL or paste in XML
3. Use the following claims for the `Map Identity Provider Attributes` configuration

`IdP User ID http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier`

`User Email http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress`

`First Name http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname`

`Last Name http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname`

Microsoft is indeed sending the claims that the error is describing.

**Comment by BYK** [comment]
Ping @getsentry/enterprise to triage

**Comment by KoSoVaR** [comment]
I was able to resolve on our end with @buffcode's response back in October. I'm in agreement with what @buffcode has described as the issue.

**Comment by leedongwei** [comment]
Hi @KoSoVaR, thank for the report! 

Our documentation has been updated with the correct mapping values: https://docs.sentry.io/product/accounts/sso/azure-sso/

**Comment by leedongwei** [comment]
Hi @KoSoVaR, thank for the report! 

Our documentation has been updated with the correct mapping values (https://docs.sentry.io/product/accounts/sso/azure-sso) and I'll close this issue out. 

cc @bowencai8 on using a dropdown with mapping values to improve UX for SSO setup.
