### ISSUE TITLE
Add warning for avatar uploads that are too large

### ISSUE THREAD

**Issue by TaylorBriggs** [getsentry/sentry#24249]
## Summary

When trying to upload a user or organization avatar there is no indication if the file size is too large. There is a banner that says the image was uploaded successfully, but on page refresh the image will not be found (this is especially true with S3 filestore).

## Motivation

It appears that there is a file size limit applied in the backend, but it is not explained in the UI. Users should know what dimensions and maximum file size are supported.

## Additional Context

This would prevent quite a bit of confusion.

**Comment by chadwhitacre** [comment]
Did we actually complete this? 🐭 🙈
