### ISSUE TITLE
Timeline Chart Contingent on Tags

### ISSUE THREAD

**Issue by aryeh-looker** [getsentry/sentry#2424]
Supposing I have a tag for `browser`. Sentry allows me to breakdown the occurrence based on that tag; for example: it is reported 25% from Chrome, 25% from Safari, etc. In addition to these breakdowns, is there some way to show a chart of occurrences only for a given tag as opposed to the issue in aggregate?

**Comment by dcramer** [comment]
@aryeh-looker we dont provide any tag-based charts yet. We're looking at doing a few things around this very soon.

We'll likely offer:

- The ability to plot a single tag over a period of time (this might be per project and per group, though tbd)
- Plot an area chart of a single tag key (thus giving you a top list) over a period of time

**Comment by aryeh-looker** [comment]
@dcramer any thoughts on this these days?

**Comment by dcramer** [comment]
@aryeh-looker we did some infrastructure work on this, but at the moment we haven't fully enabled it as the cost is fairly high and we didn't have any UI/features using it

**Comment by aryeh-looker** [comment]
Sounds good. This is really useful if you are in an environment with heterogeneous application versions. For example, if you have a bug Q in Release A.B and then Release A.C with a putative bug fix, ideally you want to be able to see a decline in bug Q over time for all server releases and you don't want to see bug Q for Release A.C at all. But no good way to look at this right now (AFAICT?).

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
