### ISSUE TITLE
Time Since does not Translate Well

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#2425]
Currently we use `fromNow(true)` to get "2 days" but what we should be doing is use `fromNow()` so that we get "2 days ago".  Reason being is casing in other languages.

Eg in German:
- `2 days ago` -> `vor 2 Tagen`
- `2 days old` -> `2 Tage alt`

**Comment by benvinegar** [comment]
@mitsuhiko – do you remember where you saw this? Is it still open?

**Comment by mitsuhiko** [comment]
I think the commit referenced fixed most of it. If you set the UI to German (or any language) though it's currently a huge mess and I think if we want to fix that we probably will automatically see cases like this again. I think we can close this.
