### ISSUE TITLE
Select All shows wrong count

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2427]
See screenshot:

![image](https://cloud.githubusercontent.com/assets/375744/11672692/9546c0da-9dc7-11e5-82d2-b4e473908369.png)

There's only 1 event in the entire system (this is a brand new install).

**Comment by mattrobenolt** [comment]
This is also in production when we don't show 25 on the page.

**Comment by dcramer** [comment]
@benvinegar is this a quick fix?

**Comment by benvinegar** [comment]
https://github.com/getsentry/sentry/commit/f7681d4bd2638d4c35e442c8c6f19d4ca97bc87e
