### ISSUE TITLE
python 2.7.11 compatibility

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2429]
Sentry currently will not work on python 2.7.11 now without forking kombu (which we're not willing to do).

See https://github.com/celery/kombu/issues/545 for the issue we hit with 2.7.11.

We cannot upgrade to latest kombu because kombu has broken compatibility with Django 1.6, so we're stuck on an older kombu.

We should definition mention this in the docs, and we should enforce this version check at runtime, probably in the `sentry/runner/__init__.py` since there's no other way to enforce this through `pip` or at any other level.

**Comment by thoas** [comment]
What's the cost of upgrading Sentry to Django 1.8+?

**Comment by dcramer** [comment]
@thoas more than were willing to spend. It requires dealing with the migrations mess. While it's not impossible there's no benefit in us solving south + django for thabout greater django community when we're moving away from sql anyways

**Comment by thoas** [comment]
@dcramer if you change your mind, I will be glad to help you.

From a user view, I don't think the south+django is a real issue even if yes migrations are still a real mess with the new engine.
You can still force users to use [pure sql migrations](https://pypi.python.org/pypi/yoyo-migrations) since you have removed the mysql support.

I understand completely your wish to move away from sql but removing support for latest python updates is a tough decision in terms of security, etc.

**Comment by dcramer** [comment]
@thoas we don't need Django's updates. If there is ever a system we use that is compromised, we will replace it with our own. We already have ripped out a lot of the guts of Django in Sentry and will continue down that path.

The migration problem is not as easy as you might look to it on the surface. We would effectively have to provide two full sets of migrations, and force people to upgrade to version X, run migrations, and then version Y. This is not ok in our book, and you can blame the authors of Django/South for taking such a direct (inaccessible) path to the transition. it's fine for companies running Django as they can just cutover, but it's not fine for tools like Sentry which have numerous versions in the wild.

**Comment by mattrobenolt** [comment]
@thoas the problem is this:

Say we ship 8.0.0 with Django 1.6.x. The migrations are all in south now.

User installs 8.0.0.

Later, we ship 8.1, 8.2, they all introduce new migrations which are in South.

Then we decide to upgrade to Django 1.8 (or 1.9) and tag 9.0.0. 9.0.0 has all the existing migrations migrated (haha) over to native Django migrations. Remember: other apps that we depend on (kombu) has their own migrations.

How does user upgrade at that point from 8.0.0 to 9.0.0?

This path is a bit tricky and we'd need to make sure we support it correctly.

I agree it's kinda lame that we can't support 2.7.11 now because of a transient dependency, but we're also planning on killing our dependency on kombu+celery relatively soon. Likely before we drop SQL.

**Comment by thoas** [comment]
ok guys I understand.

Looking forward your next commits especially the kombu+celery murder, thank you for your times.

cheers :beers:

**Comment by mattrobenolt** [comment]
Yeah, sorry, It's just the unfortunate spot we're stuck in and there's no super easy answer. Probably the easiest would be monkey patching kombu, but lol, not going down that path. :)

**Comment by kamikaze** [comment]
It's a shame that many packages are not Python 3.x compatible... but it's twice a shame that Sentry is not >2.7.10 compatible.

**Comment by dcramer** [comment]
@kamikaze Sentry works just fine on 2.7.x (including 2.7.11). This ticket is old, thus the reason its closed (as it clearly has the ticket associated with it).

We will never use Python 3, so if this conversation is related to that, please take it elsewhere.
