### ISSUE TITLE
Add 'source' to events

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2433]
We need to give this more thought, but the idea here is we could identify how an event came to be.

For example, source=crash_handler would suggest the error was not handled, whereas source=logging would suggest it came from a simple log handler.

**Comment by benvinegar** [comment]
@mitsuhiko – this basically become `mechanism`, right?

**Comment by mitsuhiko** [comment]
Correct. This is part of the new mechanism system. Closing as done.
