### ISSUE TITLE
The Bitbucket organization and url is not displayed correctly on the integration configuration page

### ISSUE THREAD

**Issue by jonesphillip** [getsentry/sentry#24333]
## Important Details

What versions of Sentry does this impact?

Saas (sentry.io), Self-hosted

## Description

The Bitbucket organization and url are not displayed correctly on the integration configuration page.

![Screen_Shot_2021-02-25_at_6 46 11_PM](https://user-images.githubusercontent.com/7978631/110416504-b655a980-8048-11eb-9298-f8e9ce6718e8.png)

### Expected behavior

Organization and url should be displayed correctly as it does with other source code integrations.

![Screen_Shot_2021-02-25_at_6 45 12_PM](https://user-images.githubusercontent.com/7978631/110416522-beade480-8048-11eb-81a9-d824ad6a45a9.png)

**Comment by immohsin** [comment]
I want to take up this issue. can I work on it as a contributor outside sentry org?

**Comment by BYK** [comment]
@immohsin of course!

I'd start looking into https://github.com/getsentry/sentry/tree/master/src/sentry/integrations/bitbucket

**Comment by immohsin** [comment]
@BYK Thanks.

I trying to looking into the issue. I'm not able to add bitbucket integration to sentry server running locally. Any way I can add to test it out?

Here is the error
![Uploading Screenshot 2021-04-17 at 12.53.00 PM.png…]()

**Comment by immohsin** [comment]
NVM found a way to test

**Comment by ceorourke** [comment]
Fixed in https://github.com/getsentry/sentry/pull/31536
