### ISSUE TITLE
Ensure IP address can easily be overwritten

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2434]
We allow you to set the IP address in the user context, but we need a good way to override the IP in the HTTP context. This is primarily due to frameworks/applications not having a good way to overwrite the default "what is the request's IP address" mechanism, and things like X-Forwarded-For not being respected by default.

Based on some discussion, we'll like just make something akin to `$use_x_forwarded_for = true` in clients, since if you're sending the data yourself you can always override things. We also likely need to use X-Forwarded-Host/Port instead of the X-Forwarded-For header.

**Comment by Mange** [comment]
What about supporting an `ip` tag and have that stick?

The server would basically say: `tags["ip"] = tags["ip"] || read_ip_from_http_headers(headers)`. The clients can then override that tag where appropriate.

The `raven-ruby` adapter, for example, could then use Rails' built-in proxy trust framework in the Rails integration.
I'm sore most other frameworks also have something in place to determine the real user's IP.

**Comment by dcramer** [comment]
@Mange tag's have special meaning that we wouldn't want to overload here. This really would be specific to SDK's so probably something like just binding ip_address context in the same way other context's work. It's also very possible just doing something like "get the IP address from this function/header" could work too.

**Comment by nateberkopec** [comment]
> We also likely need to use X-Forwarded-Host/Port instead of the X-Forwarded-For header.

Why? X-Forwarded-Host is the client hostname, not the IP address.

**Comment by nateberkopec** [comment]
I think if REMOTE_ADDR is a private IP, Sentry should be looking for X-Forwarded-For and plucking out the leftmost valid IP.

**Comment by dcramer** [comment]
All we care about is setting ``user.ip_address``. This can be done by a user, or could be done by our Rack integration.

``tags['ip']`` isnt a thing in Sentry, and wouldn't provide any value other than creating a tag called ip

**Comment by nateberkopec** [comment]
Yeah, not advocating for tagging, I'm just pointing that even if the client isn't sending the correct IP, the server has all the information to put the pieces together (since it has X-Forwarded-For) and set `ip_address` correctly.

**Comment by Inscure** [comment]
What is the state of this issue?

**Comment by untitaker** [comment]
I believe this has to be resolved on a per-SDK basis. The current Python SDK respects X-Forwarded-For, for instance, and there is a hook to modify the event payload arbitrarily (before-send).

The server should never overwrite your data.
