### ISSUE TITLE
User Feedback request is incorrectly returning a 403 error

### ISSUE THREAD

**Issue by alizain** [getsentry/sentry#24357]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

I'm using Sentry's SDK to load the user feedback feature. When I use the `showReportDialog` function, the SDK injects a `<script>` tag that points to `https://sentry.io/api/embed/error-page/?dsn={DSN}&eventId={EVENT_ID}`. This script returns a 403 Forbidden error.

The request headers when Chrome makes this request include both the `Referrer` and the `Origin` headers:

```
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
DNT: 1
Host: sentry.io
Origin: https://ots.localhost
Pragma: no-cache
Referer: https://ots.localhost/
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"
sec-ch-ua-mobile: ?0
Sec-Fetch-Dest: script
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4437.0 Safari/537.36
```

I'm running this on my local environment where I use the domain of `ots.localhost`. This is setup to point to `0.0.0.0` which is what my dev server is listening on.

I also have my Sentry account configured with the following settings:

<img width="1180" alt="Screen Shot 2021-03-09 at 19 55 04" src="https://user-images.githubusercontent.com/2343007/110558956-5d9e1380-8111-11eb-9320-8ac1a2c144ce.png">

## Steps to Reproduce

I don't have a repro project setup.

**However, when I change the settings on Sentry.io and allow all domains with `*` , the request works!**

### What you expected to happen

I expect it to allow the request without having to use `*`

**Comment by markstory** [comment]
Have you tried `ots.localhost` without the * as an allowed domain?
