### ISSUE TITLE
Support Automatic Issue Creation for Jira Server

### ISSUE THREAD

**Issue by jandersen-plaid** [getsentry/sentry#24363]
## Summary

The Jira integration has brought some fantastic improvements to Sentry over the last year or so, most notably: automatic issue creation. As an on-premise user who needs to connect an on-premise version of Jira (Jira Server), it would be fantastic to see those changes brought to that integration as well.

## Motivation

Parity of features between on-premise edition of an integration and the public version of an integration would be helpful for running Sentry in more locked down settings where communication is more sensitive.

## Additional Context

I peered through the integration itself, and it looks like there could be quite a few opportunities for either copy-paste or refactoring to pull the integration business logic into a shared state. I would be happy to work on a PR with some guidance from the team.

**Comment by BYK** [comment]
Pinging @getsentry/ecosystem for triage.

**Comment by manuzope** [comment]
Hi @jandersen-plaid, thanks for bringing up this issue! This would indeed be a good addition. We don't have the bandwidth to take this on right now but would accept PRs. The way we've implemented it should make it fairly easy to add JIRA server. Should involve a few tweaks, _I think_, given that JIRA server inherits from JIRA.

**Comment by nEdAy** [comment]
It is expected that JIRA Server can be modified to have the functions of JIRA, especially "Automatically create JIRA tickets based on Issue Alert conditions."

**Comment by jandersen-plaid** [comment]
👍 great to hear! I can get started on this today then (sorry for the long delay!)

**Comment by nEdAy** [comment]
Any updates?
Still looking forward to this feature.

**Comment by nikolaigauss** [comment]
Any updates?

**Comment by ceorourke** [comment]
This is available https://github.com/getsentry/sentry/pull/58019
