### ISSUE TITLE
about avatar!

### ISSUE THREAD

**Issue by Dannywanxyz** [getsentry/sentry#2438]
how do i setup avatar in sentry?it confuses me a lot.
![image](https://cloud.githubusercontent.com/assets/13790928/11705450/ed81ad14-9f2a-11e5-97cc-311eef58331a.png)

**Comment by dcramer** [comment]
Avatars should come from Gravatar.com. Can you check any of the image URLs and see what the generated URL is? It's possible its being blocked

**Comment by Dannywanxyz** [comment]
@dcramer I just checked.It seems that Gravatar.com is being blocked in China at present.

**Comment by Dannywanxyz** [comment]
@dcramer Is there an easy way to solve that problem?

**Comment by mattrobenolt** [comment]
No, unfortunately, we only support Gravatar.

**Comment by dcramer** [comment]
@Dannywanxyz I think in the future we'll support uploading avatars/etc, but right now its not possible

**Comment by Dannywanxyz** [comment]
@dcramer @mattrobenolt Ok,thank you guys!I am looking forward to that new features :)
