### ISSUE TITLE
CSP: "referrer" should not be used as unique value

### ISSUE THREAD

**Issue by reedloden** [getsentry/sentry#2439]
This may already be the case somehow, but just filing...

Should not treat the "referrer" option as a unique value, as it's possible that the same CSP error can come from multiple referrers.

**Comment by mattrobenolt** [comment]
We don't use the Referer.

We'd group on `(effective-directive, blocked-uri)`.

Was this an issue that you had?

**Comment by reedloden** [comment]
Nope. I'm comparing some other CSP parsing tools and see what they do so as to improve Sentry's version. If that's the case, closing this out.
