### ISSUE TITLE
Jira Integration Problem

### ISSUE THREAD

**Issue by Isszul** [getsentry/sentry#24412]
## Important Details
How are you running Sentry?
Django integration on hosted webapp.

## Description
Attempted to configure the Cloud Jira integration support.

## Steps to Reproduce
1. Clicked Jira Marketplace
![image](https://user-images.githubusercontent.com/2150998/110921203-33697300-8316-11eb-9f83-6d4d7fcb19d5.png)

2. Get it now
![image](https://user-images.githubusercontent.com/2150998/110921292-4aa86080-8316-11eb-82df-010f0b184402.png)

3. Get Started
![image](https://user-images.githubusercontent.com/2150998/110921573-9c50eb00-8316-11eb-8197-744c29c4ed1e.png)

4. Spinner for ~60seconds, then Kaboom
![image](https://user-images.githubusercontent.com/2150998/110921471-7aefff00-8316-11eb-8949-2b8d7ca00729.png)

### What you expected to happen
No error and the app should be available for configuration! 

I wish I had more debug info to give!

**Comment by BYK** [comment]
Routing to @getsentry/ecosystem that said the page says "contact **Atlassian Support**" so this is probably something on their end?

**Comment by manuzope** [comment]
Hi @Isszul, to confirm - are you running on sentry.io or your own sentry instance?

**Comment by Isszul** [comment]
Both Jira and sentry are cloud-hosted.

**Comment by manuzope** [comment]
Got it. And are you using an adblock by any chance? If so, mind disabling that and trying again?

**Comment by Isszul** [comment]
Yup, that was it. Cheers!

**Comment by manuzope** [comment]
👍  I'll update the docs. Thanks for confirming @Isszul.
