### ISSUE TITLE
CSP: Optionally add additional URIs to DISALLOWED_SOURCES

### ISSUE THREAD

**Issue by reedloden** [getsentry/sentry#2442]
Add optional things to DISALLOWED_SOURCES... Unshamefully taken from @ScottHelme.

These additions will remove any reports that the host can't resolve, which are usually triggered by plugins or the internal workings of a browser.

Blocked URI:

```
mxjscall://
webviewprogressproxy://
res://
mx://
safari-resource://
chromenull://
chromeinvoke://
chromeinvokeimmediate://
mbinit://
opera://
localhost
127.0.0.1
```

Source File:

```
chromenull://
resource://
```

**Comment by mattrobenolt** [comment]
Yeah, we've talked about this briefly internally, but we haven't even made CSP reports very publicly accessible. So it'll probably be a while before we surface a configuration for this, since they don't apply to anything else.

**Comment by mattrobenolt** [comment]
fwiw this is also a pretty good resource: https://blogs.dropbox.com/tech/2015/09/on-csp-reporting-and-filtering/

**Comment by reedloden** [comment]
Ah yes, I had forgotten about that blog post. I see stuff from that list in my reports all the time. Would be good to filter it out.

**Comment by mattrobenolt** [comment]
Yup, same here. :)

**Comment by ScottHelme** [comment]
Please feel free to use any of the filters found on https://report-uri.io! You have to create an account to get to the Settings page but the details of everything that I filter are on there. I'm tempted to created a gist with them all in to make it easier for people to access the information. This may just prompt me to do that.

**Comment by reedloden** [comment]
See also the helpful comments on http://engineeringblog.yelp.com/2014/09/csp-reports-at-scale.html

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
