### ISSUE TITLE
[8.0.0rc1] SoftTimeLimitExceeded: SoftTimeLimitExceeded()

### ISSUE THREAD

**Issue by Stayallive** [getsentry/sentry#2443]
> https://sentry.alboweb.nl/share/issue/312e33343237/

I get a bunch of these errors in the Sentry Backend app.

(p.s. is it helpfull for you guys that I share these things?)

**Comment by mitsuhiko** [comment]
Sentry tries to sync it's internal documentation against docs.getsentry.com.  Any chance that this URL is firewalled off or something of that sort?

**Comment by Stayallive** [comment]
Looks like I can do a curl request just fine (and also ping docs.getsentry.com), I have no outgoing firewalls in place.

```bash
$ curl https://docs.getsentry.com
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by mitsuhiko** [comment]
Any chance you could send me some logs with celery running in debug mode?

**Comment by Stayallive** [comment]
Yeah for sure, lemme figure that out tommorow :)

**Comment by Stayallive** [comment]
I can't seem to reproduce it when I want too :angry: 

![image](https://cloud.githubusercontent.com/assets/1090754/11810598/8cedbe26-a32f-11e5-997e-ab3b6bee089f.png)

But it still happens a bit, any pointers on forcing this event to happen? Celery debug logs grow very big (10mb ~30min) so don't want to run it all the time :)

**Comment by mitsuhiko** [comment]
I'm going to change the doc stuff anyways so probably will just go away automatically. I will close the issue when I have the change in that removes those tasks.

**Comment by Stayallive** [comment]
Thanks :)

**Comment by dcramer** [comment]
sync_docs change is in
