### ISSUE TITLE
Expand Device Logos

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#24440]
New logos are being added through #24439. Unfortunately the mobile devices reported are not named in a way that matches the css class/file for which we have a logo. 

To get Samsung and Motorola we'd need some changes since today it must be an exact match with the class name. Samsung for example, would require matching `SM-*` or `ST-*`. Motorola would be `moto*`. Google Pixel could show the Google logo for: `Pixel*`

![image](https://user-images.githubusercontent.com/1633368/111082650-d7eae100-84df-11eb-8c95-4bbe4242743d.png)

![image](https://user-images.githubusercontent.com/1633368/111082600-880c1a00-84df-11eb-886e-84022415d05f.png)

![image](https://user-images.githubusercontent.com/1633368/111082659-ea651a80-84df-11eb-85e5-94cd4cc455b0.png)

With these we'd cover a lot of devices that today show `?`.

For examples, circle through events in this issue: https://sentry.io/organizations/sentry/issues/2224396209/events/d7d2dec6e3ea4a7bb991e94b04f01f32/?project=1886021&query=is%3Aunresolved

/cc @matejminar @priscilawebdev

**Comment by matejminar** [comment]
Thanks, we'll look at what we can do here.

**Comment by priscilawebdev** [comment]
@matejminar will be working on it 😉
