### ISSUE TITLE
Preview jpg attachment is broken

### ISSUE THREAD

**Issue by myonlylonely** [getsentry/sentry#24526]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

JPG attachment preview as a text file, not as an image.

## Steps to Reproduce

1. Upload an event with a jpg attachment
2. Click preview button
3. it displays as a text file, not a jpg image.

Good items to include here include:

![image](https://user-images.githubusercontent.com/8188177/111591237-265eef00-8802-11eb-8285-746021c52d7c.png)

**Comment by chadwhitacre** [comment]
Dumb bot, sorry @myonlylonely.

Routing to @getsentry/workflow for [triage](https://develop.sentry.dev/processing-tickets/#3-triage).

**Comment by BYK** [comment]
This was superseded by #24527
