### ISSUE TITLE
Preview JPG attachment is broken

### ISSUE THREAD

**Issue by myonlylonely** [getsentry/sentry#24527]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

JPG attachment displays as a text file, not an image.

## Steps to Reproduce

1. Upload an event with a jpg attachment.
2. Click the preview button
3. JPG attachment displays as a text file, not an image.

![image](https://user-images.githubusercontent.com/8188177/111591616-a9804500-8802-11eb-9a12-dd5211b25dd6.png)

### What you expected to happen

The JPG attachment should be displayed as a image, not a text file.

**Comment by BYK** [comment]
Pinging both @getsentry/workflow and @getsentry/team-webplatform (@priscilawebdev, @mitsuhiko) for triage as I don't know who owns this part.

**Comment by mitsuhiko** [comment]
Can you show how you uploaded this attachment? The viewer that is picked up is determined based on the mimetype of the attachment or a guess based on the filename if the content type header is missing. It would be very helpful to know which SDK you used and how you called it.

Additionally what would be extra helpful is to show the API call's response for the attachment listing (you should see it in the console. Something like this: `https://server.example/api/0/projects/ORG/PROJECT/events/EVENT_ID/attachments/`

**Comment by myonlylonely** [comment]
> Can you show how you uploaded this attachment? The viewer that is picked up is determined based on the mimetype of the attachment or a guess based on the filename if the content type header is missing. It would be very helpful to know which SDK you used and how you called it.
> 
> Additionally what would be extra helpful is to show the API call's response for the attachment listing (you should see it in the console. Something like this: `https://server.example/api/0/projects/ORG/PROJECT/events/EVENT_ID/attachments/`

You are right. The MIME header is wrong. I am writing my own SDK.
