### ISSUE TITLE
Some admin pages are mistreated as missing organizations.

### ISSUE THREAD

**Issue by mvaled** [getsentry/sentry#2454]
I was stumbling around the admin pages.  I noticed the Enviroment, Packages and Mail pages, but when I click them I get a message that says: "The organization you were looking for was not found."

**Comment by mattrobenolt** [comment]
Which version of Sentry?

**Comment by dcramer** [comment]
Also do you happen to know an example URL that was broken?

**Comment by mvaled** [comment]
Master branch at eafe886038fdcf9cce88279ce14b2e94bda4d5d7. This is an on-premises installation.  The three paths are: http://my.domain.com/manage/environment/, http://my.domain.com/manage/packages/ and http://my.domain.com/manage/mail/.

**Comment by mvaled** [comment]
It seems what is broken is the links to such pages in other pages.  For instance, if I go first to "Users" and then click over "Mail" the URLs contain a '/status' part that is missing in the URLs I reported.

To reproduce (in the commit I said) you must:  

1- Go to Overview in the admin pages.
2- Click over Environment, Mail or Packages. 

If, otherwise, you go to Users and the click any of those pages the URLs are ok.

**Comment by mattrobenolt** [comment]
Oh, I wonder if I missed a few when I fixed these in 3002f3add79cd41bbbb36e988cebf75ff0143c58

I'll double check all of these today.

**Comment by mvaled** [comment]
@mattrobenolt, In fact I noticed that the menus changes.  When I'm in the Overview I see:

![1](https://cloud.githubusercontent.com/assets/270825/11844456/e5ed676c-a3dc-11e5-828f-6d570ee4c496.png)

When I'm in the Users page I gain a Settings option:

![2](https://cloud.githubusercontent.com/assets/270825/11844464/f3dddb86-a3dc-11e5-867a-9eef25c3ad88.png)

But clicking it yields the same "organization" error.
