### ISSUE TITLE
Google auth is currently unusable as google currently does not allow redirect uris with trailing slashes

### ISSUE THREAD

**Issue by PixelBumper** [getsentry/sentry#24543]
## Important Details

How are you running Sentry?

On-Premise with helm sentry version 21.3.0

## Description
We are running sentry On-Premise in kubernetes and are currently trying to setup google authentication.
Unfortunately google does currently not allow to configure redirect uris with trailing slashes, which unfortunately rules out configuring the redirect uri to use sentry's /auth/sso/ endpoint.

## Steps to Reproduce
1. Setup google account according to [sentry docs](https://develop.sentry.dev/self-hosted/sso/#google-auth)
2. try to configure redirect uri with trailing slash

### What you expected to happen

There should be the option in the google sentry plugin to configure the sso uri.
Alternatively it would be good enough to have an 'auth/sso' endpoint that does not require a trailing slash

**Comment by BYK** [comment]
Hi @PixelBumper,

>Unfortunately google does currently not allow to configure redirect uris with trailing slashes,

Is this documented anywhere? I cannot find anything anywhere on Google's docs.

**Comment by PixelBumper** [comment]
Hi @BYK,

unfortunately it seems not to be documented. In fact the only feedback I get is from the dashboard redlining the input form as soon as I append a trailing slash to the redirect uri.

It might well be that this is a bug on google's side that was introduced recently and does not affect existing configurations, as I have not found reports of other people experiencing this.

There is of course still the chance that the error is on our side.

However we added the /auth/sso uri without the trailing slash in the google dashboard and modified the url in the request that is generated by sentry, and that worked out, prompting us with a google authentication form.
So we think that the app setup at google side is correct, except for the redirect_uri of course.

I will provide a screenshot demonstrating the behaviour in the google dashboard tomorrow morning.

**Comment by BYK** [comment]
@PixelBumper sorry you had to go through all those hoops! That said it indeed sounds like a bug on Google's side as I definitely remember going through this setup myself and succeeding without any issues a while ago.

Would you mind raising this issue there as I don't think it is reasonable to reject valid URLs?

**Comment by PixelBumper** [comment]
@BYK We have created a new google account and could successfully add the redirect_uri there. So it localizes the Problem to our existing company account. We are currently analyzing the difference between the two setups.

Once we have found the issue we will inform you and in the case of a bug at googles side, open a bug ticket there.

So at the moment there is probably no pressing need for the google sentry plugin to be updated.

However once we figure out what went wrong we would like to post the possible solutions/workarounds here. So it would be nice if we could keep this open for discussion for now, as we cannot promise to post feedback before the weekend.

**Comment by BYK** [comment]
>However once we figure out what went wrong we would like to post the possible solutions/workarounds here. So it would be nice if we could keep this open for discussion for now, as we cannot promise to post feedback before the weekend.

@PixelBumper thanks so much for following up! Will surely keep the issue open and will update our docs if you can figure out a workaround or a known issue around this. Thanks again for taking the time to report the issue in the first place and your collaboration.

**Comment by PixelBumper** [comment]
@BYK We have managed to make it work in our company account.

We have no idea why, but when we appended the slash in the google dashboard today it worked.

This is very unsatisfying, as we did not find a way to reproduce this issue.

One thing to try out when someone encounters this, would be to try to clear the browser caches and reload the page.
Other than that it seems like one can only play the waiting game or contact the google support.

We managed to find at least [another person](https://stackoverflow.com/questions/55142909/installedappflow-run-local-server-systematically-add-a-slash-to-the-end-of-t#comment97057820_55142909) that seemed to have encounter the issue

**Comment by BYK** [comment]
@PixelBumper thanks a lot for reporting back again! I'm guessing this was a bug on Google's end and then they silently fixed the issue (would explain the need to cache clearing etc).

I think we can now close this issue as I don't see anything actionable at this point, including any doc updates?

**Comment by PixelBumper** [comment]
I guess so. If it occours again we can still reopen/comment
