### ISSUE TITLE
symbol are missing if crash occurs before dSYM has been uploaded

### ISSUE THREAD

**Issue by allright** [getsentry/sentry#24564]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

Do not show symbols on production app version.

## Steps to Reproduce

1. Upload to AppStoreConnect
2. Download by TestFlight
3. Simulate Crash
4. Download dSYM by Organizer from AppStore Connect
5. Upload symbols to sentry.io
6. Look at the crash....
7. Press the search icon at the right (attached picture 1)
8. Look that dSYMS has been uploaded (attached picture 2)
9. Return back on the screen (attached picture 1) and look that symbols are still missing...

![2021-03-19_17-34-12](https://user-images.githubusercontent.com/374572/111796655-6fce3d80-88d9-11eb-8a5c-73fccf623018.png)
![2021-03-19_17-34-27](https://user-images.githubusercontent.com/374572/111796663-72c92e00-88d9-11eb-8f41-dbaab58c9c7e.png)

### What you expected to happen

Show symbols for all unsymbolificated crashes even if dSYMS are uploaded after the crash has occured.

[What you think should be happening]

**Comment by BYK** [comment]
I think you are looking for https://docs.sentry.io/product/error-monitoring/reprocessing/ ?

**Comment by BYK** [comment]
Ping @jan-auer and @getsentry/owners-ingest for triage/closure.

**Comment by jan-auer** [comment]
@BYK Thanks, and you're right. This is an example where reprocessing is required.

@allright Sentry requires you to upload all symbols before sending crashes in. Uploading missing symbols afterwards will only have an effect on events sent after the upload. The behavior you explained in the reproduction steps is therefore expected.

You can, however, _reprocess_ existing issues with missing symbols. Reprocessing is currently in preview and you can have a look at this forum post for more information, and engage there for feedback: https://forum.sentry.io/t/native-stacktrace-reprocessing-for-early-adopters/12872
