### ISSUE TITLE
Self-Hosted Sentry does not show SYSTEM LEVEL Debug symbols of stack trace

### ISSUE THREAD

**Issue by allright** [getsentry/sentry#24561]
## Important Details

How are you running Sentry?

Self-Hosted docker-compose up -d, version 21.2.0

## Description
System level debug symbols in stack trace are missing.

## Steps to Reproduce

1. Run centry
2. Make some crashes
3. ...

Look at the attached picture

Good items to include here include:

### What you expected to happen

Expected to be visible iOS/MacOs System level symbols.
Or please provide the way to upload debug symbols (step by step guide how to do it).
Please look at the attached picture.

[What you think should be happening]
![image](https://user-images.githubusercontent.com/374572/111782098-b0be5600-88c9-11eb-9a74-0df7cc301341.png)
of stack trace

**Comment by BYK** [comment]
Hi! I think this is due to Apple's own limitations and even mentioning a way to get this done may put us in a legal dispute. That said I still directed this to our @getsentry/owners-native team for an ultimate answer. Special ping to @mitsuhiko and @bruno-garcia as I think they know the best in this area.

**Comment by jan-auer** [comment]
Thanks @BYK, that is right. While we have means to collect Apple's system symbols for symbolication on our SaaS platform (sentry.io), we unfortunately cannot redistribute these files for open source installations.

For a large number of iOS releases, symbol files are available online, such as on [this repository](https://github.com/Zuikyo/iOS-System-Symbols/blob/master/collected-symbol-files.md). You can download them and organize them in a [symbol server](https://docs.sentry.io/platforms/native/data-management/debug-files/symbol-servers/). Then, go to _Project Settings > Debug Files_ and add the symbol server, after which the files will be resolved for new crashes.

To help organizing the symbol server, we also have an open source utility called [`symsorter`](https://github.com/getsentry/symbolicator/tree/master/symsorter). In near future, we plan to publish binary releases; for now you'll have to build it from source.

I'm sorry that we cannot provide more assistance with symbols for Apple's system libraries. We'll close this issue, but feel free to respond back with questions for clarification. Of course, you're always welcome to create an organization on sentry.io, and we would be happy to resolve any concerns you might have.

**Comment by allright** [comment]
Thanks a lot for your detailed answers 🙏
