### ISSUE TITLE
New Asynchronous Workers

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2456]
We want to be accountable for our software. A large amount of Sentry runs async through our workers and we currently run it via a third party module (Celery) as a black box. In addition we want to push towards a distributed (Kafka-driven) future.

Some quick notes on what we want to support:
- MVP being a push/pop queue (from the app side)
- Individual tasks need to support TTLs, timeouts, and late acks
- HA support with minimal tooling on the app
- Support evented IO for things like sourcemaps and future-plugin-architecture
- Redis and Kafka support. Nothing else.

**Comment by dcramer** [comment]
Some notes we talked about:

- Can we use Kafka to store late acks vs having a dedicated result store
- Can we have a backend (in Sentry) which acts as a stepping stone to swapping out Celery? It would support both Celery and [new] as backends
- How do we partition workers so some tasks can be evented and some are classical thread-based

**Comment by mitsuhiko** [comment]
What worries me a bit is that we need to come up with some sort of liveliness check for the workers, at least for redis.  I would like to find out how we go about that.  We want to be able to see that a worker fucked up so that someone else picks up the tasks for it since we no longer have real queue semantics like with AMQP.

**Comment by ralph-tice** [comment]
FWIW I don't think it's worth the engineering effort to harden Redis as a backend when you plan on Kafka support.  There is https://github.com/antirez/disque but I would suggest using http://redis.io/commands/rpoplpush for Redis queuing semantics.

I am also curious what is meant by 'real queue semantics' in terms of what guarantees are expected between Redis and Kafka implementations.

Is using kafka-python a gimme or does there need to be an evaluation of it against pykafka?

**Comment by dcramer** [comment]
@ralph-tice we are intending to implement a Kafka-esque implementation on top of Redis, not just a generic queue implementation. Outside of that i cant really comment on things, but maybe someone else can provide more (i.e. @tkaemming who is working on this project)

**Comment by ralph-tice** [comment]
There's https://github.com/softwaremill/kmq/ now, as well as the "Exactly Once" semantics in Kafka 0.11

**Comment by BYK** [comment]
I think this is what we have now already?
