### ISSUE TITLE
GitHub Enterprise Issue pop-up only shows 30 Assignees

### ISSUE THREAD

**Issue by AndrewMoyse** [getsentry/sentry#24685]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 21.2.0.dev0 ca466fb

## Description

I recently tried to click the "Link GitHub Enterprise Issue" on a test Issue and it only shows 30 employees from the Assignee drop-down. It looks to me because it is not processing paginated response bodies from GHE/GitHub so it's truncating the returned list.

## Steps to Reproduce

1. Create a new Issue
2. Click "Link GitHub Enterprise Issue"
3. Click "Assignee" dropdown

Here's the UI I'm referencing:
<img width="598" alt="Screen Shot 2021-03-24 at 11 50 54 AM" src="https://user-images.githubusercontent.com/7955991/112374729-b0460680-8c9f-11eb-9b8d-fd221815caa0.png">

It looks like the GHE/GH integration code uses the regular **get** method:
https://github.com/getsentry/sentry/blob/11fbfdec330994cd70d9bac43c9d5a12f4c27ddb/src/sentry/shared_integrations/client.py#L289

vs the **get_with_pagination** method:
https://github.com/getsentry/sentry/blob/11fbfdec330994cd70d9bac43c9d5a12f4c27ddb/src/sentry/shared_integrations/client.py#L316
### What you expected to happen

I expected to see the full list of users that are in the corresponding GitHub Org in the Assignee drop-down while trying to link the Issue to a GitHub Enterprise Issue.

**Comment by BYK** [comment]
Pinging @getsentry/ecosystem for triage

**Comment by manuzope** [comment]
Thanks for finding this, @AndrewMoyse! Definitely a bug. Ideally, we still load up n (n=30 or whatever) but do some sort of query parameter lookup based on what is typed by hitting GitHub's API. Will add it to our backlog and try to address it in the next few weeks.

**Comment by manuzope** [comment]
Hi @AndrewMoyse, apologies on not getting back to you earlier but it looks like this was solved: https://github.com/getsentry/sentry/pull/25773. LMK if it is still a problem and we can re-open the issue.
