### ISSUE TITLE
About how many Postgres connections does Sentry use?

### ISSUE THREAD

**Issue by mwcz** [getsentry/sentry#2471]
I just started seeing a bunch of `max_connections`-related errors in my Sentry log.  My `max_connections` (in pgsql config) is set to 100, the default.  I have no problem bumping it up, but I wanted to check whether Sentry is in fact expected to use that many connections.

**Comment by dcramer** [comment]
We dont do connection pools in the app (we use pgbouncer), so I would bump it up to like 1,000 or somewhere equiv (but you'll need pgbouncer in place to handle that). I believe we run with 4000 on getsentry.com
