### ISSUE TITLE
Duplicate environments

### ISSUE THREAD

**Issue by nilpntr** [getsentry/sentry#24731]
## Important Details

How are you running Sentry?
I'm running sentry on Kubernetes with the following [helm chart](https://github.com/sentry-kubernetes/charts/tree/develop/sentry)

On-Premise w/ K8S, version 20.11.1

## Description

I got like 120k environments and like 99% is a duplicate of each other:
![Screenshot_2021-03-26_at_08 08 20](https://user-images.githubusercontent.com/53516395/112614450-96343180-8e21-11eb-9bc5-92f2fc9de8dd.png)

## Steps to Reproduce
---

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant

### What you expected to happen

It should only create environments when they are unique

**Comment by BYK** [comment]
Ping @getsentry/visibility (@mitsuhiko Visibility is the right thing for this, right?)

**Comment by dashed** [comment]
@BYK Should be @getsentry/workflow .

**Comment by BYK** [comment]
Ping @getsentry/workflow for triage

**Comment by markstory** [comment]
How can someone reproduce this problem?

**Comment by nilpntr** [comment]
I don't think you can reproduce it 😅

**Comment by BYK** [comment]
@nilpntr can you at least provide more details about how you use Sentry as otherwise this issue is not actionable.

**Comment by nilpntr** [comment]
I'm currently investigating this thing will get back on you with some more information

**Comment by nilpntr** [comment]
It currently looks like it's creating a record in `sentry_environmentproject` for every issue. Currently there are 479523 records in that table.

**Comment by xvilo** [comment]
We're also experiencing this issue. It makes the UI very slow. We're running a bit outdated version (20.11.1), I asked if this can be upgraded. @nilpntr are you on a newer version? 

@BYK what debug details do you want to have exactly? (So I can ask at the right department) I'm just a consumer of our self-hosted instance and from that point of view we 'just' use the SDK and add new events to the sentry instance

**Comment by scttcper** [comment]
@nilpntr you might be missing some unique indexes on your tables. For example here is `sentry_environmentproject` which should be unique on project_id and environment_id. sentry_environment should also have a unique index on organization_id and name.

```sql
CREATE TABLE "public"."sentry_environmentproject" (
    "id" int8 NOT NULL DEFAULT nextval('sentry_environmentproject_id_seq'::regclass),
    "is_hidden" bool,
    "environment_id" int8 NOT NULL,
    "project_id" int8 NOT NULL,
    CONSTRAINT "sentry_environmentpr_project_id_f57a07ae_fk_sentry_pr" FOREIGN KEY ("project_id") REFERENCES "public"."sentry_project"("id"),
    CONSTRAINT "sentry_environmentpr_environment_id_f5d02227_fk_sentry_en" FOREIGN KEY ("environment_id") REFERENCES "public"."sentry_environment"("id"),
    PRIMARY KEY ("id")
);
```

**Comment by nilpntr** [comment]
Thanks will look into this tomorrow :)

**Comment by nilpntr** [comment]
This is my schema @scttcper 
```sql
                                                    Table "public.sentry_environmentproject"
     Column     |  Type   | Collation | Nullable |                        Default                        | Storage | Stats target | Description 
----------------+---------+-----------+----------+-------------------------------------------------------+---------+--------------+-------------
 id             | bigint  |           | not null | nextval('sentry_environmentproject_id_seq'::regclass) | plain   |              | 
 is_hidden      | boolean |           |          |                                                       | plain   |              | 
 environment_id | bigint  |           | not null |                                                       | plain   |              | 
 project_id     | bigint  |           | not null |                                                       | plain   |              | 
Indexes:
    "sentry_environmentproject_environment_id_f5d02227" btree (environment_id)
    "sentry_environmentproject_project_id_f57a07ae" btree (project_id)
Foreign-key constraints:
    "sentry_environmentpr_environment_id_f5d02227_fk_sentry_en" FOREIGN KEY (environment_id) REFERENCES sentry_environment(id) DEFERRABLE INITIALLY DEFERRED
    "sentry_environmentpr_project_id_f57a07ae_fk_sentry_pr" FOREIGN KEY (project_id) REFERENCES sentry_project(id) DEFERRABLE INITIALLY DEFERRED
```

**Comment by BYK** [comment]
@scttcper ping for re-triage :)

**Comment by chadwhitacre** [comment]
> I'm running sentry on Kubernetes with the following [helm chart](https://github.com/sentry-kubernetes/charts/tree/develop/sentry)

@nilpntr You'll have to ask for help over there (that's not our project).

(Yer off the hook @scttcper. 😁)
