### ISSUE TITLE
How to assign user to a project?

### ISSUE THREAD

**Issue by juanmas07** [getsentry/sentry#2474]
I cannto find in the docs how to assing users to teams, organizations or projects...

**Comment by dcramer** [comment]
On your dashboard you click Members, and then you add the member. Once done they can either be added to teams, or join them on their own, gaining access to those projects.

**Comment by juanmas07** [comment]
In which part should I see members? I cannot find it.

Date: Fri, 18 Dec 2015 17:30:47 -0800

**Comment by dcramer** [comment]
It's on the main entrance page to Sentry. This may vary based on the version of Sentry, but on all current versions there is a "Members" link.
