### ISSUE TITLE
Sentry claims my browser does not support security keys

### ISSUE THREAD

**Issue by WhyNotHugo** [getsentry/sentry#24794]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

Attempting to log in on iPad or iOS shows me an error that says:

 > Unfortunately your browser does not support U2F. You need to use a different two-factor method or switch to a browser that supports it (Google Chrome or Microsoft Edge).

However, my key works fine on this browser. I even just used it to log into GitHub. It’s the same yubikey I use for Sentry.

## Steps to Reproduce

1. Set up a Yubikey on your account.
2. Log in via an iOS device.

### What you expected to happen

Should be able to use my key.

**Comment by BYK** [comment]
Ping @getsentry/enterprise and @getsentry/security for triage

**Comment by leedongwei** [comment]
Hi @WhyNotHugo 

Thanks for the report! Apologies for the bug, I'll prioritize this and I will update here as soon as I have a fix.

**Comment by ds-cbo** [comment]
I can also confirm this for Firefox 87.0 on macOS Big Sur 11.2.3 using a YubiKey 5 on a self-hosted Sentry instance. The same instance works fine on Chrome, and other websites work fine with the same key on Firefox.

**Comment by maxiuyuan** [comment]
Hello! this is now fixed by #30612 and the prs listed in its description
