### ISSUE TITLE
Clarify Story on Unicode

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#2482]
Sentry is grown software and internal handling of Unicode grew with the times.  There is no particularly clear policy on how textual data should be handled at different levels.  This has caused confusion repeatedly and we should write down our expected behavior so that we can align code that does not follow these rules.

In particular this also needs to be considered on the protocol where it's not yet considered.  The known area there is the `data` part which currently can only be text which is disappointing.

**Comment by dcramer** [comment]
I'm deferring here as I still cant ever wrap my head around the complexities of unicode in Python

**Comment by mitsuhiko** [comment]
I will mention this problem in the client spec docs for the moment so that it does not confuse people. Now that @mattrobenolt fixes the issue with the handling of bad data it will probably show up to users more visibly. (So far the data was mostly rejected).

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
