### ISSUE TITLE
Reflect datetimes in users's selected timezone for emails

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2486]
Briefly looking at this its going to require some refactoring

**Comment by akarve** [comment]
+1
i use sentry often. i would love this feature. makes it much easier to diagnose issues and trace them back to a specific commit. no timezone translation.

**Comment by mnpenner** [comment]
+1

**Comment by bas2k** [comment]
+1

**Comment by jaguileram** [comment]
+1

**Comment by gregwym** [comment]
Wonder if there is any news on this? We also would like to have a way to set default timezone on organization level.

**Comment by csonuryilmaz** [comment]
Is there any solution to modify timezone in emails?

**Comment by SystemOutPrint** [comment]
+1

**Comment by shulinwz** [comment]
Still no development?

The mental burden of always having to adding a time zone offset to the timestamp in an alert email is annoying...

I thought about changing the django TIME_ZONE setting to my time zone. But there is a big warning about non-UTC time zone in the sentry code...

**Comment by dcramer** [comment]
We never used to do this because we sent batch emails. I think thats untrue today so probably not hard to fix. Not a priority on our side, but maybe when we take a look at alerts in the future we can tackle it.

**Comment by anush0247** [comment]
@dcramer let us know once you implement this feature, we are looking forward for this feature

**Comment by eic-aibee** [comment]
+1

**Comment by grantmcd** [comment]
+1

**Comment by jinchuanchuan** [comment]
+1

**Comment by zhangzhaorui** [comment]
+1

**Comment by sysardex** [comment]
+1

**Comment by joarobles** [comment]
+1 I don't understand why this basic feature isn't applied yet

**Comment by zhangzhaorui** [comment]
I really hope you can solve this problem！Thanks！

**Comment by elyuty** [comment]
It would be much more logical to see the same time both in email and on the web interface, not having to convert it every time in your head while processing email notifications. Voting +1.

**Comment by poppyred** [comment]
+1

**Comment by leemon9527** [comment]
+1

**Comment by wchaowu** [comment]
+1

**Comment by Akahadaka** [comment]
+1

**Comment by druggo** [comment]
+1
