### ISSUE TITLE
Stats API endpoints grouped by project time out when lots of data

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2487]
This is visible for a small number of organizations on the "Organization Stats" page, under "Events by Project" – the loading spinner never stops spinning.

The API endpoints themselves take about 15-30 seconds before returning with HTTP status 502, "Service Unavailable".

**Comment by dcramer** [comment]
A couple solutions that we talked about the other day:

1. Have the frontend do one query per project (oof)
2. Have an endpoint that lets you specify a set of project IDs (i.e. 10) and chunk them up
3. Wait for @tkaemming's sketch stuff, which would let us paginate this.

Obviously 3 is really nice, but I'm not sure how close we are to that yet.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
