### ISSUE TITLE
Expected new feature for JIRA Server: "Automatically create JIRA tickets based on Issue Alert conditions."

### ISSUE THREAD

**Issue by nEdAy** [getsentry/sentry#24895]
## Summary

It is expected that JIRA Server can be modified to have the functions of JIRA, especially "Automatically create JIRA tickets based on Issue Alert conditions."

## Motivation

The company's JIRA is for server, not SaaS, so I can only install JIRA Server plug-in, not JIRA plug-in.

But we expect to use the "Automatically create JIRA tickets based on Issue Alert conditions" feature.

## Additional Context

Is there any way or plan to implement this feature.

**Comment by BYK** [comment]
Duplicate of #24363.

@nEdAy - please refrain from double posting in the future.
