### ISSUE TITLE
Merging issues return "Unable to merge events. Please try again." message

### ISSUE THREAD

**Issue by spidey** [getsentry/sentry#24923]
## Important Details

How are you running Sentry?
On-Premise w/ Docker, version 9.1.2

## Description

Trying to merge 2 issues I get the generic "Unable to merge events. Please try again." popup message on the bottom right of the screen. Even if I try again it never succeeds. I'd like to get more info on what is wrong. Ultimately I noticed that I was merging a Resolved and an Unresolved issue, and after Resolving the second one the merge succeeded. But I think it's a bug that such a generic message was used or that no details are given on how to solve the problem.

## Steps to Reproduce

I'm not certain this is the scenario, I'll list it anyway just because that's what happened to me. Not sure if these steps are sufficient to reproduce.
1. Select two issues to merge, one Resolved and one Unresolved on the list view.
2. Click the "Merge" button.

I'm a user, I don't have access to Sentry logs and other administrative files. I can request that if necessary.

### What you expected to happen

Either the issues get merged correctly, using the most "complete" state (Resolved/Unresolved -> Resolved, unfilled parameters such as release get filled if either has it filled, etc), or at least a more descriptive error message is shown.

**Comment by BYK** [comment]
Thanks for reporting! This seems to be fixed in the latest version of Sentry so closing.
