### ISSUE TITLE
e['events.dropped'][s] is undefined

### ISSUE THREAD

**Issue by saschanos** [getsentry/sentry#24928]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 21.3.0

## Description

Opening Sentry Admin (/manage/) throws an error.

## Steps to Reproduce

1. Open /manage/ after login
2. Error message is shown (-> error is thrown as internal event)

<img width="1354" alt="Bildschirmfoto 2021-04-02 um 18 55 20" src="https://user-images.githubusercontent.com/4348851/113436470-0d9b2f80-93e5-11eb-8bd9-8ef94dd4e615.png">

<img width="993" alt="Bildschirmfoto 2021-04-02 um 18 55 15" src="https://user-images.githubusercontent.com/4348851/113436479-0ffd8980-93e5-11eb-98de-d7e997cd23e5.png">

For me it looks like the api is returning a response not expected.

### What you expected to happen

See some statistics maybe? :)

**Comment by BYK** [comment]
Thanks for reporting, will check this today.

**Comment by GlobalKeeper** [comment]
Confirm on start clear onpremise installation, version 21.4.0

**Comment by BYK** [comment]
Hi, sorry for the late response! I just tried this with the latest nightly and couldn't reproduce it. @GlobalKeeper is this what you mean, it is resolved in `21.4.0`?

**Comment by GlobalKeeper** [comment]
> Hi, sorry for the late response! I just tried this with the latest nightly and couldn't reproduce it. @GlobalKeeper is this what you mean, it is resolved in `21.4.0`?

No, that error I found in 21.4.0 too (some minutes later error disappeared)

**Comment by BYK** [comment]
@GlobalKeeper do you still see the "error while loading the component" error?

**Comment by GlobalKeeper** [comment]
> @GlobalKeeper do you still see the "error while loading the component" error?

No

**Comment by BYK** [comment]
Alright then, closing the issue. We can file a new one if the error comes back again.

**Comment by saschanos** [comment]
@BYK, for me the issue is not solved. It's still existing.

**Comment by BYK** [comment]
@saschanos can you provide more details about how to reproduce this? Also, have you tried this with the latest version?

**Comment by saschanos** [comment]
It directly appears after opening /manage/ url (see above). Will do an update as soon as possible; will maybe take several days because I need to inform all people using it.

**Comment by saschanos** [comment]
After upgrading to 21.4.1 the error is not shown anymore :). Thank you!

**Comment by BYK** [comment]
Thanks for confirming @saschanos! I wish free fixes for everyone! 😝
