### ISSUE TITLE
Gitlab integration not working

### ISSUE THREAD

**Issue by ErMaqui** [getsentry/sentry#24949]
## Important Details

How are you running Sentry?
On-Premise w/ Docker, version 21.1.0.dev0c3eba3c

## Description

Gitlab integration not working

## Steps to Reproduce

I've enabled gitlab integration. but they isn't getting any new releases.

```
Connect your Sentry organization to an organization in your GitLab instance or gitlab.com, enabling the following features:
    Track commits and releases (learn more here)
    Resolve Sentry issues via GitLab commits and merge requests by including Fixes PROJ-ID in the message
    Create GitLab issues from Sentry
    Link Sentry issues to existing GitLab issues
```

On my "releases" page, I only view two releases (the ones with bugs reported). On gitlab, I have many more (and more recents than the configuration of the integration).
I cannot find any option for create issue / link issue.

### What you expected to happen

At least they should detect new commits on gitlab.

**Comment by BYK** [comment]
Pinging @getsentry/ecosystem for triage. That said it feels like we'd need a bit more information around how you set-up this information and whether there are any error messages in logs etc to make any progress on this issue.

**Comment by manuzope** [comment]
Hi @ErMaqui, for the Gitlab integration to work, Sentry needs to be told when a new release happens. Want to confirm - are you using sentry-cli or something similar to tell Sentry when a release happens (usually done as a part of your CD pipeline)? The integration can then go to your Gitlab and fetch the commits.

But either way, you should be able to see the issue link functionality on the [right nav of any issue](https://docs.sentry.io/product/integrations/gitlab/#issue-management). Do you not see it there?
