### ISSUE TITLE
duplicate key value violates unique constraint sentry_eventuser_project_id

### ISSUE THREAD

**Issue by camilonova** [getsentry/sentry#2494]
Hi there, I'm getting this error on a daily basis:

    duplicate key value violates unique constraint "sentry_eventuser_project_id_1a96easd29e55f9a_uniq"

It began after upgrading to latest version, should I delete some tables and run upgrade again?

**Comment by dcramer** [comment]
Are you seeing this in the server logs? What version of Sentry? We gracefully try/catch on the creation of this in 8.0 so this shouldn't show up outside of SQL warning logs.

**Comment by camilonova** [comment]
@dcramer Yes, seen at the postgres logs. Sentry version ```8.0.0rc1```
Let me know what else do you need. How can I fix it so I don't see it in the logs?

**Comment by dcramer** [comment]
Afaik these cant be removed from the logs. There's nothing wrong here it's just Postgres logging the event. It happens within a transaction which gets rolled back.
