### ISSUE TITLE
POSTing to relay gets blocked by content blockers

### ISSUE THREAD

**Issue by etergen** [getsentry/sentry#24947]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

Reporting to sentry.io gets blocked by content blockers. As suggested in #23054, I deployed [relay](https://docs.sentry.io/product/relay/), which doesn't really solve the issue either.

## Steps to Reproduce

1. Deploy relay
2. Use updated DSN in web app
3. Trigger an error in the browser
4. `POST` gets blocked

Safari (with Wipr) throws:
```
[Error] Resource blocked by content blocker
[Error] Fetch API cannot load https://sentry.my.domain/api/<myID>/store/?sentry_key=<my_key>&sentry_version=7 due to access control checks.
```

Brave (with all shields up except script blocking) throws:
```
POST https://sentry.my.domain/api/<myID>/store/?sentry_key=<my_key>&sentry_version=7 net::ERR_BLOCKED_BY_CLIENT
```

### What you expected to happen

Allow the `POST` to reach my server

### Additional information

Relay was deployed to a subdomain named `sentry`

**Comment by BYK** [comment]
Pinging @getsentry/owners-ingest for triage. (special ping to @untitaker and @jan-auer)

**Comment by untitaker** [comment]
EasyPrivacy has a filter that matches any subdomain `sentry.*`. Here: https://easylist.to/easylist/easyprivacy.txt

This is always going to be a cat-and-mouse game but I guess the next step in it would be to choose a different subdomain. I suggest [Santry](https://twitter.com/getsantry)

**Comment by etergen** [comment]
@untitaker thanks for the tip. I've changed the subdomain where I deployed sentry and it works now 👍 

> I suggest [Santry](https://twitter.com/getsantry)

While tempting, I went for something less fancy 😄
