### ISSUE TITLE
Redis Connection Failures in Celery Setup

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#2495]
Something happens that when celery spawns the workers previous redis connections caused problems when used with epoll/poll. In particular BADFD is signalled which should only happen if a side closes the connection.

This affects both the connection in celery itself to redis as well as our rb library.  Celery now catches down BADFD errors to handle this but I rather want to understand why this happening in the first place.  In our case catching BADFD would not solve the issue unless we reconnect.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
