### ISSUE TITLE
Issue with Sentry's Dark Theme

### ISSUE THREAD

**Issue by catcosmicice** [getsentry/sentry#24954]
### Version Information

Version: 21.4.0.dev0

### Steps to Reproduce

1. Switch to Dark Theme in user settings.

### Expected Result

Dark theme to work perfectly.

### Actual Result

It looks like the theme has some issues, for example, in the Admin Settings UI, the navbar's background color is in white, which makes it harder to read. I have noticed this in some other pages as well.

https://user-images.githubusercontent.com/67003720/113502159-80b6ba00-953b-11eb-9eed-72630fe161d4.mp4

Hope there'll be a fix for this.

Thanks,
[cosmicice](https://github.com/catcosmicice)

**Comment by BYK** [comment]
Pinging @getsentry/app-frontend (@billyvg and @priscilawebdev specifically) for triage

**Comment by billyvg** [comment]
These issues are addressed in https://github.com/getsentry/sentry/pull/24595 if someone could take over that PR and get it merged.
