### ISSUE TITLE
Celery workers are referencing a different version of Sentry (8.0.0rc1 vs 7.7.4)

### ISSUE THREAD

**Issue by jie** [getsentry/sentry#2500]
how to update celery workers to 8.0.0rc1

**Comment by mattrobenolt** [comment]
You should be able to just restart them if you've upgraded to 8.0.0rc1. It sounds like you just restarted the web process only.

**Comment by jie** [comment]
@mattrobenolt 
I have restart both workers and web many times, the warning still here.

web: SENTRY_CONF=/etc/sentry sentry start
weokers: SENTRY_CONF=/etc/sentry sentry celery worker -B

I have installed ord version before, and I upgrade it with:
pip install -U sentry==8.0.0rc1

droped database and redis db

**Comment by mattrobenolt** [comment]
Then it should go away after a few minutes, or if your queue is backed up, it'll take longer. But it should be fine.
