### ISSUE TITLE
Artifact filesize appears as "null B"

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2501]
Example:

![image](https://cloud.githubusercontent.com/assets/2153/12083681/af2e3830-b25c-11e5-88a6-535afcb44151.png)

**Comment by mattrobenolt** [comment]
Also missing the checksum too, since these are now removed off the `FileBlob` and rely on querying the `FileBlobIndex`.

From what I can tell though, we've completely lost a checksum now for the entire `File`. Each individual `FileBlob` has it's own checksum, but we not for the overarching `File`.

**Comment by dcramer** [comment]
Restored File.size in 1e8e2613aa32c21c3cf4123d8156d7d6bd20429d and File.checksum in 6012c2ea240af279444c2b04e3a4f239f1aa0648

Will backfill File.size at some point
