### ISSUE TITLE
Add 'resolved/ignored' field in Splunk Data

### ISSUE THREAD

**Issue by Shafayet-LMI** [getsentry/sentry#25025]
## Summary

The Splunk integration currently forwards data or events. However, the information regarding whether the corresponding issue has been marked resolved or ignored is absent.

## Motivation

Filter out resolved or ignored issues in Splunk reports and dashboards.

## Additional Context

Splunk

**Comment by Shafayet-LMI** [comment]
Even better, if ignored and resolved issues are NOT forwarded to Splunk to begin with.

**Comment by chadwhitacre** [comment]
Thanks @Shafayet-LMI, routing to @getsentry/ecosystem for [triage](https://develop.sentry.dev/processing-tickets/#3-triage).

**Comment by Shafayet-LMI** [comment]
hi thanks @chadwhitacre and @manuzope for routing and assigning the issue. Please let me know if I need to provide any more context. Our company uses a cloud instance of Sentry (sentry.io). We use Splunk for some statistical analysis on the Sentry issues we see in production. However the noise from resolved and ignored issues makes it difficult to have a clean report.

Based on looking at the Splunk plugin code very briefly it seems like it could be a simple change (but maybe not).
Thanks.

**Comment by jonesphillip** [comment]
@Shafayet-LMI Thank you for the request. Currently we only forward event level properties, not issue level properties (aside from the issue id). This isn't something we're currently planning on doing. One solution could be to create an [internal integration](https://docs.sentry.io/product/integrations/integration-platform/#internal-integrations) to forward your events. That way you could filter out/send over additional properties on the issue level.

**Comment by BYK** [comment]
Closing as this is not something we are planning to do soon per @jonesphillip's comment.
