### ISSUE TITLE
Uploading Source Maps to Sentry - Curl Request Failure

### ISSUE THREAD

**Issue by samdturner** [getsentry/sentry#2513]
I am following the documentation below to upload our source map file to sentry:

https://docs.getsentry.com/hosted/clients/javascript/sourcemaps/

We were able to successfully create a new api token and release, but we have been unable to upload our source map file.  Below is the curl request:

```
$ curl https://app.getsentry.com/api/0/projects/instawork/production/releases/:version/files/ -u [:api_key]: -X POST -F file=@webpack.js.map -F name="https://www.instawork.com/static/js/webpack.js.map"
```

(obviously substituting in the :version and :api_key with the appropriate values)

I get the following error: $ curl: (26) couldn't open file "webpack.js.map"

My hunch is that webpack.js.map does not have the appropriate file permissions to be read by others.  However, requesting the file in any browser works as expected.

Please advise.  Thank you sentry

**Comment by mattrobenolt** [comment]
This just means that the user executing `curl` doesn't have permission to read `webpack.js.map` on the local file system. Or the file doesn't exist. This has nothing to do with a bad API response or anything.

**Comment by qbig** [comment]
@samdturner  Did you manage to solve it ?
