### ISSUE TITLE
Reflect event details where possible

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2514]
It feels more natural if, when focused on a specific event, the issue details would reflect that event. This is true on the stream, as well as issue details, and notifications.

The primary example here is the issue title and culprit. We have the title available on the Event itself, though no longer do we store the culprit (oops). A simple solution might to be just switch to a last-write-wins on issues, and ensure notifications, and anything similar, reference the event instead of issue.

Additionally this could be a push towards a slightly more usable UI:
- Issue Details => Event Details (i.e. the permalink is the event, not the issue)
- Issue Title => Event Title

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
