### ISSUE TITLE
"field may not be blank" error pointing to wrong field

### ISSUE THREAD

**Issue by lucdewit2001** [getsentry/sentry#25157]
## Important Details

How are you running Sentry?
- Saas (sentry.io)
- firefox
- mac OS

## Description
When you create a new dashboard widget, and try to save it without a title. It will display an error but pointing to the wrong input element:

![image](https://user-images.githubusercontent.com/73638749/114197209-64a78400-9952-11eb-9bd4-58484dea8995.png)

## Steps to Reproduce
1. Go to dashboard
2. click edit dashboard
3. click the + widget to make a new widget
4. fill in whatever info of the widget except for the title
5. click save

Good items to include here include:

## What you think should be happening
I would expect the error to point to the "Widget name" field instead, because that is the one that is empty and the "Visualization display" field is not empty

**Comment by silent1mezzo** [comment]
Thanks for finding this @lucdewit2001 we'll get this fixed.

**Comment by shruthilayaj** [comment]
Fixed in https://github.com/getsentry/sentry/pull/27580
