### ISSUE TITLE
Support U2F authentication on Mobile Safari

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/sentry#25161]
## Summary

We [support U2F](https://blog.sentry.io/2016/06/22/introducing-2fa), but not on all browsers. The ask here is for Mobile Safari.

## Motivation

@robhague reports [via Twitter](https://twitter.com/robhague/status/1380429134032146432) that both Safari and Mobile Safari support U2F tokens just fine (e.g., it's possible to use a Yubikey to log in to GitHub without a hitch).

> [I] tried to quickly check a Sentry alert on my phone to avoid having to go to my laptop. The NFC Yubikeys work great with iPhones, so it's a shame not to support them.

**Comment by chadwhitacre** [comment]
Routing to @getsentry/enterprise for [triage](https://develop.sentry.dev/processing-tickets/#3-triage). Thanks for the report @robhague. :-)

**Comment by BYK** [comment]
Related: #5164

**Comment by leedongwei** [comment]
Yep, we're aware that this is a limitation cause by the library that we are using. It'll be a good idea to revisit this soon-ish.

**Comment by maxiuyuan** [comment]
Hello! this is now fixed by https://github.com/getsentry/sentry/pull/30612 and the prs listed in its description
