### ISSUE TITLE
Support GitHub autolink references

### ISSUE THREAD

**Issue by Lexicality** [getsentry/sentry#25215]
## Summary

This is exactly the same as #16221 however my sentry issues don't only have numbers (eg `MYAPP-8C`)

## Motivation

Sentry supports resolving Sentry issues in commits/pull requests. If you include “Fixes MYAPP-8C”, Sentry will automatically resolve the issue in the next release that includes that commit.

If clicking MYAPP-8C from GitHub could take me to the Sentry page for that issue.

## Additional Context

While using the query feature kinda works I'd prefer a direct URL

**Comment by BYK** [comment]
Pinging @getsentry/workflow for triage. Also ping to @getsentry/ecosystem just in case this falls under their umbrella.

**Comment by adhiraj** [comment]
This seems like an issue on github's side (doesn't support anything other than numbers). It _is_ possible for us to allow you to say "fixes <numeric issue id>" in your commit in addition to "fixes <short-id>", but at that point you may as well copy the URL of the issue and put it in the commit?
