### ISSUE TITLE
No Dashboard on fresh on-premise install

### ISSUE THREAD

**Issue by Codelica** [getsentry/sentry#25223]
## Important Details

How are you running Sentry?

On-Premise w/ Docker

Sentry 21.4.0.dev053c8331
Docker version 20.10.6, build 370c289
Ubuntu 20.04 fully updated

## Description

Fresh install w/ minimal config changes in sentry directory (system.secret-key, and uncomment items for NGINX https reverse proxy).  Everything seems to be functioning fine except the Dashboard is empty.  After a (very) brief spinner stating “Loading data for your organization” the resulting page is empty except the footer info (version, api, doc, etc links) 

Dashboard page has no console errors and all requests made are 200's. 

Nothing stands out to me in the logs, although with 28 containers I could easily be missing something ;)  No warnings in the admin section.

<img width="500" alt="sentry-dash" src="https://user-images.githubusercontent.com/386101/114594953-1264ac80-9c4b-11eb-9adc-7c7f45ca1886.png">

## Steps to Reproduce

1. Cloned Sentry on-premise repo
2. Minimal config changes (system.secret-key, and uncomment items for NGINX https reverse proxy)
3. install.sh
4. docker-compose up -d
5. Complete web based initial config

After initial attempt resulted in no data, I did the following:

1. docker-compose down
2. removed *all* remaining Docker volumes and images
3. re-ran install.sh
4. docker-compose up -d
5. Complete web based initial config

Same results.. which makes me think maybe I'm hitting a bug here...

### What you expected to happen

Would expect the Dashboard page would at least have a placeholder until data is available.  At this point I've added a project with both stats and errors thinking maybe some data or a cron run would clear it up but nothing changed.

Any clues for what to check out would be greatly appreciated!

**Comment by BYK** [comment]
Thanks a lot for reporting, I'll be investigating this soon.

**Comment by michaelmairegger** [comment]
Same issue here. Dasboard worked with v21.3.0, stopped working with >21.3.1

**Comment by BYK** [comment]
I can confirm this is the case. I suspect a few recent changes. Digging now. /cc @billyvg - I see a bunch of requests made to the IP address `34.73.148.112` which is Google Cloud so guessing this is related to recent FE asset split changes.

**Comment by BYK** [comment]
Okay, figured this out. You need to add the following to the enabled features list in `sentry/sentry.conf.py` in onpremise repo:

- `organizations:dashboards-basic`
- `organizations:dashboards-edit`

Directing to @markstory for a permanent solution.

**Comment by BYK** [comment]
@markstory btw the "failure mode" when the feature is not enabled is quite broken: we still see the link on the left side-bar and the page just shows empty with a footer.

I think we need an audit for the features disabled by default under `server.py` as the intention is to make everything enabled by default (for dev and self-hosted) and disable them over at getsentry for billed accounts?

**Comment by markstory** [comment]
> I think we need an audit for the features disabled by default under server.py as the intention is to make everything enabled by default (for dev and self-hosted) and disable them over at getsentry for billed accounts?

Yes that's generally how feature flags are intended to be used. I can flip on these flags and get the visibility team to review.
