### ISSUE TITLE
Search Bar Quirks

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2526]
- [ ] Typing a query into the search bar (not submitting) and clicking the sidebar button clears your query (resets to current search value)
- [x] status filter does not reflect default query (is:unresolved)

**Comment by benvinegar** [comment]
> Typing a query into the search bar (not submitting) and clicking the sidebar button clears your query (resets to current search value)

Should we make it so that clicking the sidebar filters submits the current query?

There's a disconnect because the input box search requires you to hit "enter" or click the search button to actually invoke the search. As opposed to the sidebar filters, which always submits a search every time you toggle a filter.

**Comment by dcramer** [comment]
i dont think it should force submission, but i think the sidebar should reflect the query box and vice versa, rather than reflecting the current document querystring

**Comment by benvinegar** [comment]
The problem is that, if it reflects the search box, but doesn't submit the search, you literally cannot submit the current search from the sidebars (there is no "apply" button). You would need to toggle the dropdown off/on again, or we need to implement an apply button.

**Comment by dcramer** [comment]
Open to ideas, but im not a big fan of auto submit here as it doesnt feel like the intended action.

**Comment by benvinegar** [comment]
> Open to ideas, but im not a big fan of auto submit here as it doesnt feel like the intended action.

There's no harm in having the search begin. It might feel a little odd. But I'd argue it's better than having your search term disappear (which I'm guessing is what happened in your case).

**Comment by EvanPurkhiser** [comment]
we rebuilt search recently.
