### ISSUE TITLE
Asana Integration: Support specifying Asana Project for Alert

### ISSUE THREAD

**Issue by jpl5280** [getsentry/sentry#25276]
## Summary

The Asana Integration (https://asana.com/apps/sentry) allows customers to create Asana tasks *manually* from the Sentry UI.

Example:

![image](https://user-images.githubusercontent.com/77367150/114781631-289b6700-9d36-11eb-8961-a4502336269e.png)

Ideally, customers could also use the Asana Integration in the `Alerts` functionality of Sentry:

![image](https://user-images.githubusercontent.com/77367150/114781419-dd815400-9d35-11eb-8bad-85354eb4aa72.png)

However, the only option is `Send a notification (for all legacy integrations)`, which will not work for Asana, as the Asana Integration only captures the `Workspace`:

![image](https://user-images.githubusercontent.com/77367150/114781498-fbe74f80-9d35-11eb-8650-052a5a65dfb0.png)

In order to file a Task in Asana, you would also need to specify the `Project` it lands in.

As a result, the request is basically supporting the following `action` in an `Alert`:

![image](https://user-images.githubusercontent.com/77367150/114781813-6e582f80-9d36-11eb-8404-8c11dac418fd.png)

## Motivation

> Why should this be worked on? What problems or use cases does it solve or improve?

- Without this, customers of yours that use Asana have to manually cut Tasks from within the Sentry UI for *every* error

## Additional Context

Is it possible for us to write the code for this? (not sure if all of your code is in this open source repository). If so, and we put up a pull request, would your team merge it and it be incorporated into your SaaS offering? (We're a SaaS customer).

**Comment by BYK** [comment]
Pinging @getsentry/workflow for triage. Also ping @getsentry/ecosystem as it may fall under there too.

**Comment by jonesphillip** [comment]
@jpl5280 appreciate for the feedback. We support this workflow for [Jira](https://docs.sentry.io/product/integrations/jira/#automatically) and [Azure DevOps](https://docs.sentry.io/product/integrations/azure-devops/#automatically).

Asana is currently a legacy project-based integration. We've moved to an organization-based integration model (you can see this by looking at our Jira and Azure DevOps integrations for example). With this change and the future of project-based integrations in flux, we're hesitant to accept new changes to them. Once that is addressed, we'd be glad to accept this change.

**Comment by jpl5280** [comment]
No longer needed, thanks!
