### ISSUE TITLE
IntegrityError: update or delete on table "auth_user" violates foreign key constraint "sentry_organizationmember_user_id_fkey" on table "sentry_organizationmember"

### ISSUE THREAD

**Issue by stayallive** [getsentry/sentry#2527]
When deleting a user as an admin I get this error, this is on a self-hosted instance running 8.0.0.

```
IntegrityError: update or delete on table "auth_user" violates foreign key constraint "sentry_organizationmember_user_id_fkey" on table "sentry_organizationmember"
DETAIL:  Key (id)=(10) is still referenced from table "sentry_organizationmember".

SQL: DELETE FROM "auth_user" WHERE "id" IN (%s)
```

**Comment by dcramer** [comment]
@Stayallive is this from /admin/ or elsewhere?

**Comment by Stayallive** [comment]
Yes this is from `https://sentry.host/manage/users/%ID/remove/`

Choosing:
![image](https://cloud.githubusercontent.com/assets/1090754/12290447/263bab92-b9e2-11e5-8fc4-e1cc9699247c.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
