### ISSUE TITLE
Not receiving email notifications

### ISSUE THREAD

**Issue by david17123** [getsentry/sentry#2528]
I've just recently installed Sentry 8.0.0 and managed to get it working just fine. However, I realized that even though I have set up a rule to notify via email every time an event occurs, I still am not getting any email from Sentry. I've made sure that all projects are ticked on `http://[sentry.domain]/account/settings/notifications/` page. Furthermore, I have tried these:

- Use the "Send a test email" button and it does send the test email properly, so I assume I've got the email config right
- Watch the output of `sentry start` and `sentry worker -l INFO` (and also `WARNING`, `CRITICAL`, `FATAL`) but I couldn't see anything weird (e.g. error messages). Tbh, I'm not sure what to look for in the first place

I'm starting to run out of ideas how to find the problem and fix it. Any ideas what could be the cause? How do I tell if it's config issue or a bug in the release?

Many thanks!
David

**Comment by math2k** [comment]
I'm having the same issue on a 8.0.0 rc1 upgraded to rc2 install.

Any pointers appreciated!

**Comment by dcramer** [comment]
Is this a fresh install? The 'triggers-0' queue would be taking care of notifications, and it would check:

- Should this event generate a notification (based on rules?)
- Which users get notified (based on membership/personal settings)

It seems it would have to fail one of those checks if the test email works fine.

**Comment by david17123** [comment]
Yes, it is pretty much a fresh install. I initially installed version 8.0.0rc1 and noticed this issue. But then I realized that version 8.0.0 has just got released so I thought I'd upgrade to see if the problem disappears after upgrade (which isn't; I'm still not getting the emails).

I have, once again, checked the rules and to avoid any doubt here's the screenshot of the rules list:
![screen shot 2016-01-12 at 12 14 51 pm](https://cloud.githubusercontent.com/assets/7081151/12251851/2c021c8a-b926-11e5-876c-b34e48bb633e.png)

And this is the user's notification settings as found on `http://[sentry.domain]/account/settings/notifications/`:
![sanitized](https://cloud.githubusercontent.com/assets/7081151/12252020/8fdb8092-b927-11e5-9d35-57e3810b1560.png)
_(The project in the red box is the targeted sentry project that receives the event)_

As far as I know, with these settings it should be the case that **a notification is to be created** (because an event is seen) and **the user should be notified** (because the user has subscribed to it).

I have tried to inspect the tasks handled by celery worker when the event is created, and I see the following tasks received and completed in order:
- sentry.tasks.store.preprocess_event
- sentry.tasks.store.save_event
- sentry.tasks.post_process.post_process_group
- sentry.tasks.process_buffer.process_pending
- sentry.tasks.process_buffer.process_incr
- sentry.tasks.options.sync_options
- sentry.tasks.process_buffer.process_incr _(this task appears 18 times with different keys in the kwargs each time)_
- sentry.tasks.digests.schedule_digests
- sentry.tasks.process_buffer.process_pending
- sentry.tasks.options.sync_options

I'm not sure if there's any task there that should have handled sending the notifications but by their names I don't think there's any. Can you suggest me what things to look for or watch? I've been trying to inspect the contents of the `triggers-0` queue but I can't (maybe because it's empty).

_PS: sorry for the long post. I'm just trying to be as precise and clear as possible_

**Comment by dcramer** [comment]
@david17123 can you confirm if you've enabled digests or not (via SENTRY_DIGESTS)? 

the post_process_group task is what would fire notifications, but if digests are enabled that works differently

**Comment by dcramer** [comment]
@david17123 actually looks like we enable these for default -- is it possible that the redis backend is not configured correctly? it relies on SENTRY_REDIS_OPTIONS

**Comment by david17123** [comment]
The SENTRY_REDIS_OPTIONS I have is the default one, namely:
```
SENTRY_REDIS_OPTIONS = {
    'hosts': {
        0: {
            'host': '127.0.0.1',
            'port': 6379,
        }
    }
}
```

I thought I got it right because celery worker (and the web service) won't even start when I put the wrong IP and/or port number.

And yes, I think I've got digests enabled (`SENTRY_DIGESTS = sentry.digests.backends.redis.RedisBackend`) but I don't have anything configured for `SENTRY_DIGESTS_OPTIONS`

**Comment by dcramer** [comment]
And one last thing, can you confirm version of Redis?

/cc @tkaemming this might be digests related

**Comment by david17123** [comment]
It's version 3.0.6. More specifically, this is the output of `redis-server --version`:
```
Redis server v=3.0.6 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=51589ec2e9b72863
```

**Comment by MartyRong** [comment]
I got this problem too,and my redis is 3.0.6 and sentry is 8.0.0

**Comment by a-sk** [comment]
Me too:
  redis 3.0.5, sentry 8.0.0
sentry can talk to redis, I used redis `monitor` command to test it.

**Comment by tkaemming** [comment]
I just ran through a clean install and was able to reproduce this, but the underlying issue is actually independent of the notification system.

The superuser that is created as part of the installation process is not added to the default team, so the [`MailPlugin.should_notify` method returns `False`](https://github.com/getsentry/sentry/blob/1153e88ffd39157d8e15f018fd5f660af853d554/src/sentry/plugins/sentry_mail/models.py#L98-L101) since there are no users to deliver mail to when checked as [part of the post-processing pipeline](https://github.com/getsentry/sentry/blob/1153e88ffd39157d8e15f018fd5f660af853d554/src/sentry/rules/actions/notify_event.py#L39). You can check if this is the case (please do, and post back here) in `sentry shell`:

```
from sentry.models import Team
Team.objects.get(slug='sentry').member_set.all()
```

The last statement should return an empty list (`[]`).

If a new team (and project) is created, events sent to that team should receive email digests.

I believe this only should affect new installations (not upgrades) but am not totally certain.

**Comment by dcramer** [comment]
Fundamentally this is an issue with superusers, and if we can resolve https://github.com/getsentry/sentry/issues/2214 it would fix this as well.

**Comment by david17123** [comment]
@tkaemming I've run the code you posted and indeed it returns an empty list, exactly as you said. I just want to clarify my situation though:
- When I fresh-install Sentry I was prompted to create a new user (when running `sentry upgrade`), and I chose to make this new user a superuser.
- I haven't created any new users ever since. This is the only user I used to create new projects and team.
- Sentry created a team called "sentry" with one project in it called "Internal"; I left it untouched. By default, the user I created on `sentry upgrade` is part of this team.
- I created a new team (called "dev") and added several new projects to it. These are the projects that I expect to get the notifications from (which I don't).

Now when I tried this command instead:
```
Team.objects.get(slug='dev').member_set.all()
```
it returns:
```
[<OrganizationMember at 0x7ff6ab3554d0: id=1L, organization_id=1L, user_id=1L, role=u'owner'>]
```
So does it mean that I should get the digest? (but again, weirdly enough, I don't)

**Comment by dcramer** [comment]
@david17123 a good test to this is look at your member settings (members => your name) and see if the tick is selected for the dev team. if so you'll get notifications for any projects under it

**Comment by dcramer** [comment]
Oh also you'll need to ensure ``celerybeat`` is running (or ``celery -B``, though we now suggest using two processes)

**Comment by david17123** [comment]
Hm.. I can see a tick is selected on the dev team, and I'm pretty sure celerybeat is running (I can see it in `ps aux` output). At the moment, I'm running it through `celery -B`. I'm not sure if running it by `celery beat` will make a difference as far as the digest email is concerned.

Just out of curiosity, why is it preferable to run celerybeat **not** from `celery -B`?

**Comment by dcramer** [comment]
@david17123 @mitsuhiko can confirm, but you might quickly test running it without. Either way you should be seeing schedule_digests fire  and then afterwards a deliver_digest would come up

**Comment by david17123** [comment]
According to celery worker's task log `schedule_digests` got fired pretty frequently, and `deliver_digest` at roughly every 5 minutes (which is the minimum delivery frequency for the project notifications settings). Nonetheless, I still got no emails.

This behavior applies whether or not celerybeat is run via `celery -B`

**Comment by MartyRong** [comment]
I create a new user and invite member to the team，I can receive email now。 but I got a new problem. when I create a new team name Qiushi-Platform. and I tried
     Team.objects.get(slug='qiushi-platform').member_set.all()
it throw
 File "/home/bot/services/pyenv27/lib/python2.7/site-packages/django/core/management/commands/shell.py", line 113, in handle_noargs
    code.interact(local=imported_objects)
  File "/usr/local/python/lib/python2.7/code.py", line 306, in interact
    console.interact(banner)
  File "/usr/local/python/lib/python2.7/code.py", line 238, in interact
    line = line.decode(encoding)
  File "/home/bot/services/pyenv27/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 25: invalid continuation byte
my databases Encoding is UTF8,Collate is en_US.UTF-8 and Ctype is en_US.UTF-8

**Comment by dcramer** [comment]
We're pushing out 8.0.1 which addresses the email membership issues

@MartyRong if I had to guess there's UTF-8 characters in the output and your terminal is not handling it

**Comment by david17123** [comment]
@dcramer After pondering on this issue I started to think that my problem is not membership issue because I see that the user is properly a member of the correct team and is already said to subscribe for notifications on projects in the team. Do you think I should open a new ticket?

**Comment by dcramer** [comment]
@david17123 yeah lets open a new ticket ideally with expanded details -- its not clear to me what else it could possible be though
