### ISSUE TITLE
Releases does not seem to work for us on-premise

### ISSUE THREAD

**Issue by Stayallive** [getsentry/sentry#2529]
The releases does not seem to work and never see any new events although there a plenty events that are new less than 5 days ago... so there should be some issues in here... am I missing something?

![screen shot 2016-01-11 at 13 58 04](https://cloud.githubusercontent.com/assets/1090754/12234220/9a516b02-b86b-11e5-961b-b8a732d2730e.png)

**Comment by dcramer** [comment]
Can you confirm those events are brand new and actually show the release?

**Comment by Stayallive** [comment]
The event I'm looking at is sent by the JS client and shows as first seen `January 6 2016 15:24:39 CET`, they do not show a release tag or something, should they or should this be sent by the client?

**Comment by dcramer** [comment]
There client would have to be sending it. I'll close this out if you can confirm that's not the case. 






On Tue, Jan 12, 2016 at 3:28 AM -0800, "Alex Bouma" <notifications@github.com> wrote:












The event I'm looking at is sent by the JS client and shows as first seen January 6 2016 15:24:39 CET, they do not show a release tag or something, should they or should this be sent by the client?

**Comment by Stayallive** [comment]
Ues that is not the case. I expected it to work based on the time events came in and versions were registered, documentation is not very clear IMO. Thanks for explaining.

**Comment by dcramer** [comment]
@Stayallive I def think we need to improve our "getting started" documentation -- the only advantage of the releases API at this stage is to ensure you can link up build artifacts to a particular version. Otherwise we'll automatically register a release when it's seen.

**Comment by Stayallive** [comment]
Thanks will take a better look at that then :+1:
