### ISSUE TITLE
Merging origin/master into my feature branch causes almost all JS tests to run in pre-commit

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry#25291]
Our `sentry.lint.engine`-based hooks for running JS lints + tests are also triggered upon `git fetch && git merge origin/master` in a feature branch. This stands in contrast to our pre-commit ([the framework](https://pre-commit.com/)) -based Python hooks.

@joshuarli insinuated on Slack that moving them over to pre-commit (the framework) solves this problem. Then we could potentially delete `sentry.lint.engine`

**Comment by natemoo-re** [comment]
Closing this as it appears that a solution was merged in https://github.com/getsentry/sentry/pull/72870, but this issue was never closed.
