### ISSUE TITLE
Integration not showing up in metric alerts

### ISSUE THREAD

**Issue by ginokhumz2020** [getsentry/sentry#25299]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, Sentry 21.2.01dedf39

## Description
Pushover Integration not showing up in metric alerts

## Steps to Reproduce

1. Create Pushover integration
2. Create a new metric alert
3. Try add the integration to actions as an alert method

### What you expected to happen
To see the Pushover integration as part of the list

### Screenshots
Intergration is configured and it works
![Screenshot 2021-04-08 at 22 12 10](https://user-images.githubusercontent.com/61448171/114091554-214d0700-98b9-11eb-993c-f0eb9f1f48b6.png)

Pushover is available on Issue alerts
![Screenshot 2021-04-08 at 22 12 56](https://user-images.githubusercontent.com/61448171/114091614-32961380-98b9-11eb-9515-9e26c98e2413.png)

Pushover is not available on metric alerts
![Screenshot 2021-04-08 at 22 13 40](https://user-images.githubusercontent.com/61448171/114091766-5d806780-98b9-11eb-9456-c669763b3091.png)

**Comment by chadwhitacre** [comment]
@ginokhumz2020 Unfortunately we had a [bug](https://github.com/getsentry/sentry/issues/24639) in recent versions related to metric alerts, can you upgrade to 21.3.1 (or 21.4.0 which should be out in a few hours ☺️ ) and try again? Sorry for the trouble. Closing for now, we can reopen if not fixed with an upgrade.

**Comment by manuzope** [comment]
Hi @inokhumz2020, you're right - the Pushover integration does not support metric alerts. We don't have it on our roadmap right now, but will keep the feature request open. cc: @jonesphillip 

In the time being though, you could use the [integration platform](https://docs.sentry.io/product/integrations/integration-platform/#alerts) to build your own integration, which will work with metric alerts!
