### ISSUE TITLE
Issue with Redis while Upgrading or Installing Sentry

### ISSUE THREAD

**Issue by joaoribeirost** [getsentry/sentry#2530]
Hello there, 

While trying to upgrade to the most recent version of sentry , and following the documentation present at 
[this link](https://docs.getsentry.com/on-premise/server/installation/) i get the following error:
```
TypeError: add_host() got an unexpected keyword argument 'timeout'
```

I tracked down the problem to this part of the configuration file
```
SENTRY_REDIS_OPTIONS = {
    'hosts': {
        0: {
            'host': '127.0.0.1',
            'port': 6379,
            'timeout': 3,
            #'password': 'redis auth password'
        }
    }
}
```

What solved it for me was removing the timeout options. If this is the only solution maybe the documentation should be updated.

If anyone knows about another way of solving this share it. :)

I just wanted to share this.

**Comment by mitsuhiko** [comment]
Thanks for the report. Looking into supporting this in rb.

**Comment by mitsuhiko** [comment]
On a second thought: not sure how that made sense before. Pretty sure we never used the blocking connection pool.

@mattrobenolt do you know what the timeout there is supposed to be for? I can only see this used for the blocking pool as waiting time until connection is available and we are not using that (and did not before unless i am missing a change).

**Comment by mattrobenolt** [comment]
@mitsuhiko This was the `socket_timeout` that used to get passed along to `StrictRedis`. See: https://github.com/disqus/nydus/blob/master/nydus/db/backends/redis.py#L67

**Comment by mattrobenolt** [comment]
@mitsuhiko Not sure what needs to be done here, if anything?

**Comment by mitsuhiko** [comment]
@mattrobenolt probably we should document that this is now called `socket_timeout`. I will check that it's supported in rb and we can put it into the docs.  I rather not diverge from redis options going forward.

**Comment by mitsuhiko** [comment]
@mattrobenolt actually kinda shitty. In rb this is configured with the pool options which you currently cannot set from sentry :(

**Comment by mitsuhiko** [comment]
This issue will tackle supporting it under a new key: https://github.com/getsentry/sentry/pull/2671
