### ISSUE TITLE
Adding U2F device results in 429 error

### ISSUE THREAD

**Issue by MasterWayZ** [getsentry/sentry#25303]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

When attempting to add my YubiKey (default config however FIDO2 is disabled, FIDO U2F is enabled though), it infinitely wants to retry, though all POST requests to https://sentry.io/api/0/users/me/authenticators/u2f/enroll/ fail with 429 Too Many Requests.

## Steps to Reproduce

1. Go to https://sentry.io/settings/account/security/mfa/u2f/enroll/
2. Try to add a U2F device. (Not sure if it is specific to that I have a YubiKey and/or that I have FIDO2 disabled while FIDO U2F is enabled).
3. It may error with 429 Too Many Requests. I've been having this issue over the past few hours as of posting this.

### What you expected to happen

That it works with no errors.

**Comment by chadwhitacre** [comment]
Thanks @MasterWayZ, routing to @getsentry/enterprise for [triage](https://develop.sentry.dev/processing-tickets/#3-triage). ☺️

**Comment by leedongwei** [comment]
Hi @MasterWayZ, appreciate the bug report. I'm able to replicate and we'll look into this today.

**Comment by leedongwei** [comment]
@MasterWayZ Fix will be merged today: https://github.com/getsentry/sentry/pull/25312

**Comment by MasterWayZ** [comment]
Okay @leedongwei, not sure how it works when it comes to deploying to the SaaS site, but when would it be life on the SaaS site?

**Comment by EvanPurkhiser** [comment]
It will go out within the next hour or so :)

**Comment by MasterWayZ** [comment]
When trying to add my U2F device with the above settings, I now get 400 Bad Request with the POST to https://sentry.io/api/0/users/me/authenticators/u2f/enroll/
In the request body:
`
{
    "challenge":	[ "Not a valid string." ]
}
`

**Comment by leedongwei** [comment]
@MasterWayZ I was able to remove and setup my Yubikey. Could you try it on incognito? I want to be sure that your browser isn't caching our old build.

**Comment by MasterWayZ** [comment]
It works now, when I tried it the PR didn't get merged yet I just saw.
Thank you for fixing it!

**Comment by leedongwei** [comment]
Awesome! Glad to hear that it's working again!
