### ISSUE TITLE
Make sure git hooks are always up-to-date

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#25349]
Some folks like me don't need to run devservices, thus, I disable `SENTRY_POST_MERGE_AUTO_UPDATE` since apply-migrations would always fail.

Because of that, I will not get `make setup-git` to run every time there's pre-commit changes (since we switched some packages to relying on `requirements-pre-commit.txt` rather than on pre-commit managing them).

Keeping pre-commits hooks up-to-date is important, especially since we don't run them on CI.

Some thoughts:
- Perhaps we can switch back to pre-commit handling the hooks *and* keeping the `requirements-pre-commit.txt`
  - Twice the work; can fall out of date
- We execute `make setup-git` every time we notice changes on `requirements-pre-commit.txt` or `.pre-commit-config.yaml`
- We run pre-commit on files changed on CI

**Comment by armenzg** [comment]
@EvanPurkhiser @joshuarli what are your thoughts?

**Comment by joshuarli** [comment]
I don't see anything wrong with keeping it as it is currently. Also wasn't there this problem? https://github.com/getsentry/sentry/pull/25315

And unsetting SENTRY_POST_MERGE_AUTO_UPDATE, which is by default opt-in, doesn't prevent `config/hooks/post-merge` from saying what it needs to say - I'm confused with this:

> Because of that, I will not get make setup-git to run every time there's pre-commit changes (since we switched some packages to relying on requirements-pre-commit.txt rather than on pre-commit managing them).

**Comment by armenzg** [comment]
I think I'm OK with closing this issue since finding the right set up might take more work than what is worth.

My main concern is that I want all developers to always have their pre-commit checks up-to-date and I'm unclear as a way forward that would work for all. Not everyone calls `make develop` or `make setup-git` when they come to the repo since they don't often do changes for sentry.

> I don't see anything wrong with keeping it as it is currently. Also wasn't there this problem? #25315
> 
That issue is unrelated.

> And unsetting SENTRY_POST_MERGE_AUTO_UPDATE, which is by default opt-in, doesn't prevent `config/hooks/post-merge` from saying what it needs to say - I'm confused with this:
> 
> > Because of that, I will not get make setup-git to run every time there's pre-commit changes (since we switched some packages to relying on requirements-pre-commit.txt rather than on pre-commit managing them).

Ah! That was probably set for me because I used the [bootstrap script](https://github.com/getsentry/bootstrap-sentry/blob/main/bootstrap.sh#L431). We're making new engineers opt-in by default.

This means that users that don't type `make setup-git` (even if post-merge tells them to do so) and will not have pre-commit hooks up-to-date, however, I can see how this is not as big of a problem since `make develop` makes things get up-to-date.

**Comment by armenzg** [comment]
Please re-open if you believe there's still some value on discussing this further.
