### ISSUE TITLE
SAML2: Sometimes users account is duplicated.

### ISSUE THREAD

**Issue by scorsair** [getsentry/sentry#25345]
## Important Details

How are you running Sentry?
On-Premise w/ Docker, version 21.3.1

## Description

Sometimes users account is duplicated. It means new users don't have permissions and don't belong to any teams except default.  Users have similar email, but different GUID.  We have also tried a feature "organizations:sso-migration", but it didn't help. 
Important: We use **only** SAML2 for auth (except default admin account). SAML2 provider is Keycloak.

## Steps to Reproduce

It's very annoying and no way to reproduce it because it happens from time to time. 

### What you expected to happen

Accounts for certain auth providers mustn't duplicate.

**Comment by chadwhitacre** [comment]
Hrm ... 🤔 Any ideas on how to debug this one, @getsentry/enterprise?

**Comment by leedongwei** [comment]
@scorsair Thanks for the report! Apologies for the annoying user experience.

We are aware of this issue and we are improving account matching to fix this issue. I'll update again when a fix goes out.

**Comment by evansano** [comment]
Thanks @scorsair for opening up this ticket, I'm also annoyedly affected by this issue.

@leedongwei , any estimates on when the fix would go out? Trying to gauge whether to wait for fix or downgrade back to a version where this issue isn't yet present. Regardless, thanks for taking this on!

**Comment by leedongwei** [comment]
@evansano My team is making improvements to the authentication flow during May to July. This is one of the key issues that we want to fix, so I'd give late June as a conservative estimate.

This bug comes from the original implementation (which is a few years old) so I would advise against downgrading your on-prem Sentry version.

**Comment by max-wittig** [comment]
The same thing happens with other type of auth systems (e.g. google)

**Comment by kirik** [comment]
Have same issue with on-prem v20.9.0. Is there are any changes with dates of estimated fix (May-Jul)?

**Comment by scorsair** [comment]
@leedongwei Hello! Can you please provide some estimation for this issue if it possible?

**Comment by leedongwei** [comment]
Hey @scorsair

It was deprioritized last quarter but we're picking it back up again, it's definitely near the top of backlog. I'll tag the PR here when we put something up.

**Comment by scorsair** [comment]
Guys! Sorry for kindly reminder but problem so annoying. We get doubled accounts every day and have to clean them all and set all permissions from scratch ;( Could you please prioritize this issue to more higher? 
@leedongwei

**Comment by chadwhitacre** [comment]
Does this occur in SaaS or only in self-hosted (aka onpremise)?

**Comment by JoshFerge** [comment]
Hello all, 

we are close to having a fix implemented, and will let you know when it is ready to test on a self-hosted release. The fix includes a flow for a user to confirm their sentry account email, so they will be able to link new org memberships with their existing accounts in these scenarios. 

https://github.com/getsentry/sentry/pull/30356
