### ISSUE TITLE
Logs are not shown in sentry dashboard

### ISSUE THREAD

**Issue by jayprakashstar** [getsentry/sentry#2536]
I have set up my own sentry server. In stats I can see even count's increase but i can't see any log on dashboard. With response it seems sentry is working but no logs. Can you find out what is going wrong?

I tried same code 
````
from raven import Client

client = Client('http://0579a8eff754467a962977e1cde0ed59:2987933b9b774fa0871bb0e890982801@45.55.68.226:9000/2')

try:
    1 / 0
except ZeroDivisionError:
    client.captureException()
```
and if try to print like this 
`print client.captureException()`
it prints a string which i suppose an object.

**Comment by dcramer** [comment]
If the server responds 200 OK that means it has enqueued the event processing. If the event isnt showing up in the dashboard something is wrong w/ the async worker processes. I would check the logs on those.
