### ISSUE TITLE
Sentry allows to enroll the same U2F device twice

### ISSUE THREAD

**Issue by gbdlin** [getsentry/sentry#25389]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

When enrolling U2F devices for 2 factor authentication, sentry allows to enroll the same device twice.

This can cause some serious mistakes when enrolling multiple devices, as one can enroll one device multiple times instead of enrolling multiple devices, each of them once, which in consequence can lead to a complete account loss when all of the enrolled devices will be lost (one may be convinced that he still has some U2F devices available, which is not true).

U2F enrollment shouldn't allow for the same device to be enrolled twice or should warn user if he tries to do so.

## Steps to Reproduce

1. Prepare your U2F device.
2. Login to your sentry account.
3. Go to `/settings/account/security/`.
4. Enroll your U2F device,
5. After the first successful enroll, try to enroll the device again.

### What you expected to happen

2nd enrollment attempt should fail or user should be warned that he is trying to enroll an already enrolled device, possibly with a confirmation if he really wants to do that.

### What is actually happening

2nd enrollment succeeds and one device is enrolled twice. Additionally, this fact can't be discovered on the device lists as at this stage, Sentry application has no way to identify it.

### Possible solution

This issue can be fixed by providing a list of already enrolled tokens for the user account to the `u2f.register` function in [this line of the code](https://github.com/getsentry/sentry/blob/master/static/app/components/u2f/u2finterface.tsx#L59) as it is specified in the [FIDO U2F docs](https://fidoalliance.org/specs/fido-u2f-v1.0-nfc-bt-amendment-20150514/fido-u2f-javascript-api.html#widl-uf-register-void-DOMString-appId-sequence-RegisterRequest--registerRequests-sequence-RegisteredKey--registeredKeys-function-RegisterResponse-or-Error--callback-unsigned-long-opt_timeoutSeconds). This information will be then passed from the users browser to the U2F device, so it can identify if it possess one of the tokens specified and if such situation occurs, it will refuse to enroll another one.

This issue cannot be fixed in the post-enrollment process, as the Sentry application won't have the ability to identify that 2 different U2F credentials are coming from the same U2F device.

**Comment by BYK** [comment]
Pinging @getsentry/enterprise for triage

**Comment by leedongwei** [comment]
@gbdlin Thanks for writing up a detailed issue report! 

Definitely agree that our U2F flow needs more love and your concerns here are valid. I'll address this as part of our upcoming auth refactor.
