### ISSUE TITLE
Microsoft Edge for iOS is detected as Mobile Safari

### ISSUE THREAD

**Issue by padinko** [getsentry/sentry#25420]
[Micosoft Edge for iOS](https://apps.apple.com/us/app/microsoft-edge-web-browser/id1288723196)
has user agent like:
```
Mozilla/5.0 (iPhone; CPU iPhone OS 14_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 EdgiOS/46.2.0 Mobile/15E148 Safari/605.1.15
```

with `EdgiOS/version` part, but sentry is not detecting this and showing `Mobile Safari` as a browser

**Comment by lobsterkatie** [comment]
@padinko - sorry, forgot our bots wouldn't accept the issue as is. Regardless, it's probably a good idea to create a new issue for the package update once `ua-parser` has done their fix, as this will get auto-closed after a certain amount of time even if I re-open it now.

**Comment by padinko** [comment]
ok, they already have [issue](https://github.com/ua-parser/uap-core/issues/487) I will watch it and create new issue on fix
