### ISSUE TITLE
Captured exceptions interpreted as messages 

### ISSUE THREAD

**Issue by dennisnuhiji** [getsentry/sentry#25449]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

Unhandled JS exceptions that are happening at runtime are being interpreted in the Sentry UI as messages, which makes it hard to find the error since the stack trace is not getting resolved through the source maps.

## Steps to Reproduce

1. Setup NextJS project with Sentry following the [with-sentry](https://github.com/vercel/next.js/tree/canary/examples/with-sentry) example
2. Try and produce an error such as undefined.filter(...
3. Find the captured error in Sentry Issues dashboard

Good items to include here include:

![exceptionAsMessage](https://user-images.githubusercontent.com/18103853/115407829-ac4ecb00-a1f0-11eb-9f7d-bcb107e39115.png)
We can see here that the error with its stack trace is sent as `ADDITIONAL DATA` arguments and further categorized as `Message`
![exceptionAsMessage2](https://user-images.githubusercontent.com/18103853/115407848-af49bb80-a1f0-11eb-9fc1-855cd3e1ba3e.png)

### What you expected to happen
To be exception such as this one, which was produced with `throw new Error('Second Error')`
![exception](https://user-images.githubusercontent.com/18103853/115407908-b96bba00-a1f0-11eb-8895-4a24ab4cf32a.png)

**Comment by chadwhitacre** [comment]
Thanks @dennisnuhiji, routing to @getsentry/team-webplatform for [triage](https://develop.sentry.dev/processing-tickets/#3-triage).

**Comment by kamilogorek** [comment]
We don't have control over https://github.com/vercel/next.js/tree/canary/examples/with-sentry and we just released our own experimental next.js plugin https://docs.sentry.io/platforms/javascript/guides/nextjs/ which we recommend to try, as this is what we are going to iterate over.
