### ISSUE TITLE
Invisible text in new project name field in dark theme

### ISSUE THREAD

**Issue by Simek** [getsentry/sentry#25447]
## Important Details

How are you running Sentry?

- Saas (sentry.io)

## Description

The text in new project name field is invisible in dark theme. 

Win 10, Chrome

## Steps to Reproduce

1. Enable dark theme: https://sentry.io/settings/account/details/
2. Navigate to: https://sentry.io/organizations/{YOUR_ORG_NAME}/projects/new/
3. Start typing the project name

#### Preview
![err](https://user-images.githubusercontent.com/719641/115401328-90e0c180-a1ea-11eb-8383-6830968603fc.gif)

### What you expected to happen

Field should be styled like others input fields in dark theme and text should be visible.

**Comment by EvanPurkhiser** [comment]
Thanks for reporting that!
