### ISSUE TITLE
Wrong encoding when reading config.yml

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2546]
```
sentry.options.manager.UnknownOption: 's\x00y\x00s\x00t\x00e\x00m\x00.\x00s\x00e'
```

This happened when reading the following default config:

```
# While a lot of configuration in Sentry can be changed via the UI, for all
# new-style config (as of 8.0) you can also declare values here in this file
# to enforce defaults or to ensure they cannot be changed via the UI. For more
# information see the Sentry documentation.

# If this file ever becomes compromised, it's important to regenerate your SECRET_KEY
# Changing this value will result in all current sessions being invalidated
system.secret-key: '######################################'
```

From some quick searching, this appears to be related to `utf-32` because of the added null bytes, but I'm not able to reproduce this yet.

@timeseer can you provide more context on your environment? What operating system, version of python, etc.

/cc @mitsuhiko

**Comment by timeseer** [comment]
Python 2.7.11+ (default, Jan 13 2016, 21:14:16)
psql (PostgreSQL) 9.2.14
Linux CentOS-7 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
LANG=ko_KR.UTF-8

Are there any other things you want more?

**Comment by mattrobenolt** [comment]
@timeseer We think #2547 will fix this issue, but it's sort of a guess since I can't reproduce it personally.
