### ISSUE TITLE
build failed from dockerfile

### ISSUE THREAD

**Issue by overstep123** [getsentry/sentry#25479]
## Important Details

How are you running Sentry?

sentry:21.4.0  Docker:19.03.1

## Description

[What happened]

build failed from dockerfile

## Steps to Reproduce

1. git clone git@github.com:getsentry/sentry.git 
2. cd sentry/docker
3. docker build -t sentry .

Good items to include here include:
![image](https://user-images.githubusercontent.com/41141842/115527398-99f19180-a2c3-11eb-8d6d-83faf7d592f7.png)

### What you expected to happen

build successfully

**Comment by BYK** [comment]
This is because it is now how we build our docker images. You can find the full steps here: https://github.com/getsentry/sentry/blob/master/docker/cloudbuild.yaml
