### ISSUE TITLE
Cannot edit team settings without being a member of that team

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2551]
Right now "Team Settings" is only visible from "Projects" -> "Your Teams":

--
![image](https://cloud.githubusercontent.com/assets/2153/12335623/ffbea464-bab4-11e5-8ed6-213a8795bdf9.png)
--

If you subsequently leave a team, you can no longer edit that team's settings – including deleting the team entirely – even if you are an organization owner.

This is confusing for admin owners who are trying to delete teams without necessarily being members of them.

**Comment by dcramer** [comment]
This was resolved
