### ISSUE TITLE
Provide release notes

### ISSUE THREAD

**Issue by max-wittig** [getsentry/sentry#25522]
## Summary

Provide release notes in GitHub releases (or anywhere `CHANGELOG.md`)

## Motivation

We don't know, if this is just a patch update or a security fix that needs to be deployed asap.

<img width="859" alt="image" src="https://user-images.githubusercontent.com/6639323/115668718-bf27e380-a347-11eb-98bf-210e3ef60c91.png">

**Comment by BYK** [comment]
Duplicate of #21594.

**Comment by BYK** [comment]
@max-wittig - If you click on the compare dropdown, you can see what changes were merged between 21.4.0 and 21.4.1: https://github.com/getsentry/sentry/compare/21.4.0...21.4.1

Some notable PRs:

- #25458 (security)
- #25397 (fix)
