### ISSUE TITLE
Twilio integration : Allow Alphanumeric Sender ID

### ISSUE THREAD

**Issue by Gregory-Widmer** [getsentry/sentry#25535]
## Summary

Allow using instead of a phone number an alphanumeric sender ID for Twilio.

## Motivation

It's useful to hide the phone number and prevent replies on a SMS. It's basically a customization feature, but I don't think it requires many changes.

## Additional Context

See [some twilio doc about it](https://support.twilio.com/hc/en-us/articles/223181348-Alphanumeric-Sender-ID-for-Twilio-Programmable-SMS). 

Basically, when making a request, we only need to put an Alphanumeric sender ID instead of the phone number. Setting the "From" value to a sender ID like this would be a nice feature.

Here is a screenshot from my self-hosted Sentry of what it could look like.

![image](https://user-images.githubusercontent.com/81698118/115706488-ff9a5800-a36d-11eb-83df-bfd2c833cfb8.png)

When we provide a sender ID, we get the following error on test.

![image](https://user-images.githubusercontent.com/81698118/115706703-38d2c800-a36e-11eb-8c26-2fff647d4d8a.png)

On the API request, we just need to replace the "From" data value by the Sender ID, like this (Exemple with curl) :

```
curl -XPOST https://api.twilio.com/2010-04-01/Accounts/ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Messages.json \
-d "Body=The body goes here" \
-d "To=<My awesome phone number>" \
-d "From=Sentry" \
 -u 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:auth_token'
```

By replacing phone number validation by Sender ID or phone number validation, we should be able to allow this feature.

Thanks for reading.

**Comment by BYK** [comment]
Pinging @getsentry/workflow for triage. Also ping to @getsentry/ecosystem in case this falls into their court.

**Comment by devtanna** [comment]
I see the Twilio docs support this as correctly mentioned in the description.
https://www.twilio.com/docs/sms/send-messages#use-an-alphanumeric-sender-id

I can try to work on this if this is indeed an intended use case :)

CC: @jonesphillip

**Comment by jonesphillip** [comment]
@devtanna looks like that's right. Another example here:
https://support.twilio.com/hc/en-us/articles/223133967-Change-the-From-number-or-Sender-ID-for-Sending-SMS-Messages

Are you still interested in working on this?

**Comment by devtanna** [comment]
@jonesphillip I have opened a PR for initial review :)
Please let me know if I have missed anything.

**Comment by sentaur-athena** [comment]
Twilio is built on our deprecated platform which we're not supporting anymore so I'm going to close the issue. We're always open to community contributions. You can check out the docs here for how to create an integration using our new platform: https://docs.sentry.io/organization/integrations/integration-platform/
