### ISSUE TITLE
direnv usability improvements

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#25578]
Suggested fixes:

- If there are steps that take short time simply take them.
- Give a list of commands in one shot (instead of requiring multiple direnv invocations) to get into a good state.
- Share code paths between `direnv` and `lib.sh`
- Take advantage of `bootstrap-py3-venv`

**Comment by joshuarli** [comment]
for posterity: <img width="586" alt="image" src="https://user-images.githubusercontent.com/14209781/115909462-19659900-a45b-11eb-8666-c4129dc0895e.png">

**Comment by armenzg** [comment]
> for posterity: <img alt="image" width="586" src="https://user-images.githubusercontent.com/14209781/115909462-19659900-a45b-11eb-8666-c4129dc0895e.png">

I will take some of it in my PR (#25676) but those are bigger changes that I want to hold off until we're sure my PR is not good enough. We may do some other long term investments for the dev env (e.g. remote environment, docker image -- I used this for my previous project).
