### ISSUE TITLE
TypeError: can't subtract offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by Rambomst** [getsentry/sentry#2559]
Getting spammed with this error, just upgraded to version 8.0.1.

>[2016-01-17 21:28:02,191: ERROR/Worker-5] can't subtract offset-naive and offset-aware datetimes
>Traceback (most recent call last):
>  File "/sentry/local/lib/python2.7/site-packages/sentry/utils/logging.py", line 23, in wrapped
>    return func(*args, **kwargs)
>  File "/sentry/local/lib/python2.7/site-packages/sentry/event_manager.py", line 467, in save
>    **group_kwargs
>  File "/sentry/local/lib/python2.7/site-packages/sentry/event_manager.py", line 641, in _save_aggregate
>    can_sample = should_sample(event.datetime, group.last_seen, group.times_seen)
>  File "/sentry/local/lib/python2.7/site-packages/sentry/event_manager.py", line 142, in should_sample
>    silence_timedelta = current_datetime - last_seen
>TypeError: can't subtract offset-naive and offset-aware datetimes

**Comment by Rambomst** [comment]
Found this issue in another place. This can be produced by going to events list of a project and all it says is "There was an error loading data."

>Traceback (most recent call last):
>  File "/sentry/local/lib/python2.7/site-packages/sentry/api/base.py", line 81, in handle_exception
>    return super(Endpoint, self).handle_exception(exc)
>  File "/sentry/local/lib/python2.7/site-packages/sentry/api/base.py", line 143, in dispatch
>    response = handler(request, *args, **kwargs)
>  File "/sentry/local/lib/python2.7/site-packages/sentry/api/endpoints/project_group_index.py", line 234, in get
>    stats_period=stats_period
>  File "/sentry/local/lib/python2.7/site-packages/sentry/api/serializers/base.py", line 33, in serialize
>    return [serializer(o, attrs=attrs.get(o, {}), user=user) for o in objects]
>  File "/sentry/local/lib/python2.7/site-packages/sentry/api/serializers/base.py", line 47, in __call__
>    return self.serialize(obj, attrs, user)
>  File "/sentry/lib/python2.7/site-packages/sentry/api/serializers/models/group.py", line 171, in serialize
>    result = super(StreamGroupSerializer, self).serialize(obj, attrs, user)
>  File "/sentry/lib/python2.7/site-packages/sentry/api/serializers/models/group.py", line 97, in serialize
>    elif status == GroupStatus.UNRESOLVED and obj.is_over_resolve_age():
>  File "/sentry/lib/python2.7/site-packages/sentry/models/group.py", line 171, in is_over_resolve_age
>    return self.last_seen < timezone.now() - timedelta(hours=int(resolve_age))
>TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by dcramer** [comment]
Sentry does not store timestamps without timezones. You should check what's up with your database, because these should not exist. If I had to guess I'd say this is a MySQL install converted to Postgres.

Otherwise please provide more info (like previous version).
