### ISSUE TITLE
Creating new organization and restricting user creation.

### ISSUE THREAD

**Issue by ybv** [getsentry/sentry#2561]
I'm currently setting up on-premise Sentry 8.0 release. After looking around a bit, it wasn't clear how to create a new organization (setup seems to create a 'sentry' organization which I couldn't modify).. 
Also, since we don't have a firewall, we would like to restrict the user registration to certain email domains, is that possible?
-- any help would be greatly appreciated.

**Comment by dcramer** [comment]
Ensure people cannot create organizations (I believe you can't by default in new installs as it's setup to only have one). From there you can enable an SSO plugin (i.e. sentry-auth-google) to limit account creation and login. Alternatively you can disable registration which would then require you to invite new members to the organization.
