### ISSUE TITLE
Support multiple releases

### ISSUE THREAD

**Issue by noirbizarre** [getsentry/sentry#2565]
Most of the time, a product is a composition of subproducts, each one having its own release.
My app will be composed from multiple libraries, maybe pugins...

Most of the time, you won't add sentry support in each subproduct, but only in the one aggregating the others.
So it may be advantageous to support multiple release.
Instead of specifying one release:
```javascript
Raven.config({
  release: '0.1.2.3'
});
```
it would be better to have:
```javascript
Raven.config({
  releases: {
     product1:  '0.1.2',
     product2:  '3.4.5',
  }
});
```

**Comment by dcramer** [comment]
The release describes the version of your application you have shipped, which there is only one of. It's not intended to describe which versions of components you're using, but the version of the final state of the collective application.
