### ISSUE TITLE
Javascript events blacklist error

### ISSUE THREAD

**Issue by MrHalfman** [getsentry/sentry#2566]
Hi,

I have an error when an event is reported from Raven-js. The event is successfully saved but sentry says that one or more errors has been encountered : "Security violation [URL/to/script.js] : [URL/to/script.js] matches the URL blacklist".

Problem is that my blacklist is empty and I don't find why these URLs are filtered.

Sincerely,
Julien DUTRIAUX.

**Comment by dcramer** [comment]
I believe we changed this error, but this means that the URL is an unreachable address such as an internal IP so it didn't try to download the source. If you need to use internal URLs, and tbh even if you don't, you should upload your source as described here: https://docs.getsentry.com/hosted/clients/javascript/sourcemaps/

**Comment by MrHalfman** [comment]
Yep it's a local domain. Thanks for the answer, the error was disturbing me :smile:.
