### ISSUE TITLE
Add a link to the marketing site from the product

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/sentry#25670]
## Summary

We use https://sentry.io/ for both the marketing homepage and the product itself depending on whether the user is authenticated. This can make it difficult for people who are logged into Sentry to access the marketing page (which _is_ actually still available at https://sentry.io/welcome/).

## Motivation

Sometimes you just wanna read some sweet, sweet marketing copy, ya know? Or look at pricing, or ...

## Additional Context

Reported by @chriswiggins [via Twitter](https://twitter.com/chriswigginsnz/status/1386898967204569091).

**Comment by chadwhitacre** [comment]
@EvanPurkhiser Thoughts on what team to route this to? 🤔

**Comment by EvanPurkhiser** [comment]
This is probably a @cameronmcefee thing

**Comment by cameronmcefee** [comment]
This is the @getsentry/design if it's in the product.

**Comment by chadwhitacre** [comment]
Oh wow ... new team label to create. :)

**Comment by ckj** [comment]
I think this is an edge case, but it wouldn't be difficult to link to https://sentry.io/welcome/ from the footer. There's real estate here where we could place a 'Visit Sentry.io' link:

<img width="1067" alt="Screen Shot 2021-04-27 at 10 58 19 AM" src="https://user-images.githubusercontent.com/30713/116291561-93db3500-a749-11eb-9abf-4c7620836f88.png">

For things like pricing, we have the equivalent information on the Manage Subscription page and as an extra measure we direct link to https://sentry.io/pricing/ there contextually (under the 'And more...') link.

**Comment by ckj** [comment]
I think this is an edge case, but it wouldn't be difficult to add a 'Visit Sentry.io' link to https://sentry.io/welcome/ from the footer here:

![Screen Shot 2021-04-27 at 10 58 19 AM](https://user-images.githubusercontent.com/30713/116293427-bb330180-a74b-11eb-87ae-a7b6743b1307.png)

As for things like Pricing, we have the equivalent information available on the Manage Subscription page and as an extra measure, we direct link from that page to https://sentry.io/pricing/ via the 'And more...' link.

**Comment by dcramer** [comment]
If someone wants to change this they can figure it out, but I would not consider this high priority. You can already access it via direct URL, and anything you "need" on the marketing site should be available within the product (pricing) or docs (platforms/etc).

**Comment by imatwawana** [comment]
FWIW, I went in many frustrating circles trying to get back to sentry "home" once I was an authenticated user on sentry.io. And I just told someone internally how to get out of this infernal loop the other day. I wonder if this is as edgy as we think? Maybe, just doesn’t tend to rise to the level of “lemme cry out for help."

**Comment by chriswiggins** [comment]
Thanks for creating the issue @chadwhitacre !

The issue with "Its in the product" is that 9/10 I just want to see your pricing plan options on your marketing screen, because to me this is a much better way of viewing it. Almost all other products we use put the user portal under a different subdomain, which avoids this issue entirely.

Perhaps I'm just an edge-case, but your marketing copy is far better to read over trying to click multiple times around the product portal trying to find information.

My 2c! 👍

**Comment by chadwhitacre** [comment]
> Almost all other products we use put the user portal under a different subdomain, which avoids this issue entirely.

+1 ... norm afaict is https://example.com/ &rarr; https://app.example.com/ or some such, but I assume that ship has sailed for Sentry. Link in the footer is least we can do.

**Comment by dcramer** [comment]
@imatwawana i would not make decisions based on how internal dev works. you can bookmark /welcome/ ultimately, and the use case for internal (as well as the patterns of uses) end up looking wildly diff than external consumers of sentry

im fine w/ the link, i just mean if someone wants to do it, do it, but unlikely this will fall on any specific teams backlog/roadmap

**Comment by chadwhitacre** [comment]
> if someone wants to do it, do it, but unlikely this will fall on any specific teams backlog/roadmap

Copy that, gold leader. 👍
