### ISSUE TITLE
merge/unmerge loses total event counts of issue

### ISSUE THREAD

**Issue by untitaker** [getsentry/sentry#25672]
## Important Details

This affects all Sentry versions regardless of how they are run.

## Description

There are two kinds of event counts within issues:

- The ones calculated off of the still-retained event data ("snuba counts")

    ![Screenshot 2021-04-27 at 19 29 32](https://user-images.githubusercontent.com/837573/116285906-ec80f100-a78e-11eb-9031-a4b00fe448e8.png)

    This type of count is present on issuestream and discover, and has the ability to be sensitive to a configured timerange. It starts *decreasing* once events are deleted after 90d and are not compensated for by new events coming in.

    This count is calculated dynamically by Snuba via `select count() from events`

- the one that is counted up from 0 since the issue started ("postgres counts", total counts, aka **`times_seen`**).

    
    ![Screenshot 2021-04-27 at 19 28 55](https://user-images.githubusercontent.com/837573/116285868-dffc9880-a78e-11eb-933e-8fa96843c29b.png)

	This type of count is shown most prominently on the issue details page, and since it is a single integer in postgres that is constantly being counted up, is insensitive to any configured timeranges and immune to event retention.

When two issues are merged, the two total counts are summed up to become one count. Simple enough. The Snuba counts do not need recalculating.

When those issues are unmerged, the summands of the sum are no longer available. Therefore total counts cannot be recovered. What unmerge does is instead, is to count how many events *currently exist* (not how many *have been seen*), and set that as the total count.

## Steps to Reproduce

1. Merge two issues that are both older than 90d, such that `times_seen` for each issue is larger than the amount of events that are still retained.
2. Observe _in issue details_ that the new issue's `times_seen` is the sum of the previous two.
3. Unmerge the two issues.
4. You end up in a state where the two unmerged issues have a smaller `times_seen` than they started out with.

### What you expected to happen

Sentry should have un-merged the issue into two issues that have the same `times_seen` as originally, from before they were merged together.

This would likely require storing `times_seen` on `GroupHash` rather than `Group`, so unclear whether we're ever going to fix this.

**Comment by mikejihbe** [comment]
While this is a fair criticism, it hasn't been fixed in 3 years and likely wont be prioritized soon. I don't think people mind that unmerge is a mildly destructive operation.  Closing.
