### ISSUE TITLE
events delay one hour in the project events list view

### ISSUE THREAD

**Issue by kevinxuv** [getsentry/sentry#2568]
In the projects list view, it showed some events comes in last one hour, but in the project view, all the events is an hour ago, the recent events did not show, my sentry version is 8.0.0, pls help
project list view:
![image](https://cloud.githubusercontent.com/assets/4512444/12411623/2bb35b96-bebb-11e5-8312-18a084aae03a.png)
project events list view:
![image](https://cloud.githubusercontent.com/assets/4512444/12411575/edb81232-beba-11e5-930a-1df08c9b2643.png)

**Comment by dcramer** [comment]
- check to make sure the queue isnt backlogged
- clear all default filters to make sure its not muted/etc
- check logs to make sure event processing isnt erroring

**Comment by kevinxuv** [comment]
@dcramer thanks !
