### ISSUE TITLE
Organization Slug issue with OKTA integration using terraform

### ISSUE THREAD

**Issue by summersonne** [getsentry/sentry#25716]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

Hello, Sentry
I am trying to create integration with Okta using terraform.
I did't find any descriptions about how to pass "Organization Slug" field
I can pass Base URL but no luck with Organization Slug unfortunately.

Terraform code sample:

`
resource "okta_app_saml" "sentry" {
  label             = "Sentry"
  preconfigured_app = "sentry"

  app_settings_json = jsonencode(

    {
      baseUrl  = "https://sentry.io",
      org_slug = "company_name"
      email    = "$${source.email}"
    }
  )

  user_name_template = "$${source.email}"
  depends_on         = [okta_group.groups]

}
`

## Steps to Reproduce

1. Trying to pass Organization Slug in the terraform code

### What you expected to happen

Organization Slug field filled with data in OKTA

**Comment by BYK** [comment]
Pinging @getsentry/enterprise for triage

**Comment by leedongwei** [comment]
@summersonne Hello

I'm seeing Okta accepted the `organizationSlug` key on a POST request through their web UI. Could you try using this key instead? 

If that doesn't work, you should contact Okta support as this is an Okta API issue.
