### ISSUE TITLE
UI for disabled client keys (DSN) is not obvious

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2572]
I don't think our client keys page does a good enough job of explaining which keys are disabled (if any):

![image](https://cloud.githubusercontent.com/assets/2153/12436574/5b79d5de-becb-11e5-8e35-3d40d504c3e3.png)

Suggestion:

* No "blue" on the "Enable" button
* Literally put "This key is disabled" next to the key name or something

**Comment by mattrobenolt** [comment]
I'll just do both of these suggestions unless @ckj has an objection.

**Comment by ckj** [comment]
No objections. :+1:  on <Key name> (Disabled).
