### ISSUE TITLE
Sentry charts empty

### ISSUE THREAD

**Issue by mo-mughrabi** [getsentry/sentry#2573]
in reference to this issue https://github.com/getsentry/sentry/issues/1411

I have an existing setup of sentry, dockerized setup, have three running dockers one for redis, sentry worker (with -B) and sentry web

It seems though the charts still unpopulated and I don't want to drop db as troubleshooting recommends todo so, is there a different way to troubleshoot this issue?

**Comment by joedborg** [comment]
I had the same issue with Dockerized setup and v7.  Moving to v8 seems to fix the graphs but causes a whole raft of other issues.

**Comment by dcramer** [comment]
Because we do not yet officially recommend using the Docker setup, you're going to need to debug the configuration. It's likely something is not fully configured and thus causing issues. Go through the installation process instructions and confirm things match up to whats expected.

**Comment by mattrobenolt** [comment]
@mo-mughrabi @joedborg for context, were you using https://hub.docker.com/_/sentry/ or your own image?

**Comment by mattrobenolt** [comment]
If you're using that image, feel free to reopen here: https://github.com/getsentry/docker-sentry and I'll investigate. :)

**Comment by joedborg** [comment]
Ah thanks @mattrobenolt, I have a few from "sentry:latest" (8.0.2).

**Comment by mattrobenolt** [comment]
Then let's open issues over on getsentry/docker-sentry and I'd be glad to help there.
