### ISSUE TITLE
Ability to re-order saved searches

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2574]
Right now the only way to do this is to delete and re-create them in the order you want.

**Comment by dcramer** [comment]
Mm order could be good. Though they're supposed to be name sorted today. 






On Wed, Jan 20, 2016 at 10:59 AM -0800, "Ben Vinegar" <notifications@github.com> wrote:












Right now the only way to do this is to delete and re-create them in the order you want.

**Comment by benvinegar** [comment]
Being able to sort them would substitute the need for "default search" ... just the first-ordered search would be the "default search".

But then there's a question of "ordered for me" and "ordered for the team".

**Comment by dcramer** [comment]
I think because of how complex this would make UI interactions, let's wontfix it.
