### ISSUE TITLE
sentry.tasks.options.sync_options raises InterfaceError

### ISSUE THREAD

**Issue by GeoTob** [getsentry/sentry#2575]
My internal sentry log is full with `InterfaceError('cursor already closed',)` errors that seem to be triggered by `sentry.tasks.options.sync_options`. There is no further stacktrace beyond that in both Sentry and my server's logs.

This is a clean install of Sentry8.0.1, celery + gevent on Ubuntu 14.04.

Not sure how to troubleshoot here, any ideas would be appreciated?

**Comment by mattrobenolt** [comment]
Gevent? Does this work without gevent? We should strip all of our gevent stuff since I assume none of it works. :(

**Comment by GeoTob** [comment]
My other instance works fine with gevent, though I can probably run without it :(

**Comment by mattrobenolt** [comment]
We definitely do not document gevent anywhere fwiw. If it works without gevent, I'm just going to assume gevent support is entirely broken.

**Comment by GeoTob** [comment]
I'll close this issue if it works for >12h

**Comment by mattrobenolt** [comment]
@GeoTob Going to assume this is good now. :)
