### ISSUE TITLE
Graphs on the project list don't correctly reflect stream contents.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#2577]
<img width="718" alt="screenshot 2016-01-20 15 15 05" src="https://cloud.githubusercontent.com/assets/65315/12466328/9d0d9d24-bf88-11e5-8145-0a79ecc0b1cc.png">

The graphs on the project list page are based on the [`project_total_received`](https://github.com/getsentry/sentry/blob/ab4ab0d25d3009926fd3d36dc2831ed6b842d948/src/sentry/tsdb/base.py#L33-L34) statistic, which is the number of events received by the server, *including* all events that were rejected due to [blacklists](https://github.com/getsentry/sentry/blob/ab4ab0d25d3009926fd3d36dc2831ed6b842d948/src/sentry/web/api.py#L289-L294) or [rate limits](https://github.com/getsentry/sentry/blob/ab4ab0d25d3009926fd3d36dc2831ed6b842d948/src/sentry/web/api.py#L309-L314).

This is confusing, since this data doesn't actually reflect the data that will be shown when navigating to the project stream view. Instead, this graph should be based on the `project` statistic. This also will cause the graph to be relative to the event timestamp, as it is in the stream view. (The `project_total_*` statistics currently used are relative to the server timestamp when the event was *processed*, which is used to calculate ingestion rates, not the point in time when an event *occurred*, which is what a user is generally concerned with.)

**Comment by mattrobenolt** [comment]
@tkaemming Wanna do this for 8.2? I think this is useful as well and doesn't seem like it'd be a major effort.
