### ISSUE TITLE
Bitbucket Integration: "This app is misconfigured"

### ISSUE THREAD

**Issue by stefanschindler** [getsentry/sentry#25804]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version "Sentry 21.4.1"

## Description

Hi!

I am not able to use the Bitbucket integration for my On-Premise Sentry installation.

I am getting the following error when trying to install the Bitbucket Integration:

**An error has occurred during installation**

descriptor_uri: The add-on server wasn't able to authorize your request. Try again, or contact the add-on vendor for help.

redirect_uri: Could not resolve descriptor so cannot check redirect_uri against baseUrl

Unfotunately, I could not find any info in the docs(https://docs.sentry.io/product/integrations/bitbucket/)

### What you expected to happen

Integration of Bitbucket should work

**Comment by BYK** [comment]
Hi there! You should be checking your `redirect_uri` and `system.url-prefix` configurations.

I'll be closing this issue as it is not something we act on. You may want to seek help from [the forum](https://forum.sentry.io).
