### ISSUE TITLE
vendor-jquery.min.js using non-ssl hostname

### ISSUE THREAD

**Issue by kzw** [getsentry/sentry#2581]
This is causing the following ssl page to not load these non-ssl assets

https://server-hostname/team/project

Other pages do not have this issue.

This is despite the fact that SENTRY_URL_PREFIX configuration variable is 'https://....'

Here is the message from firebug
-------
19
Blocked loading mixed active content "http://sentry.......com/api/xxxxx-engineers/production-api/poll/?&cursor=1453389210:0:1"

...function(n,i){var o,r=e.xhr(),a=++Dt;if(r.open(e.type,e.url,e.async,e.username,e...
 

Up arrow pointed near r.open
------

**Comment by mattrobenolt** [comment]
What version of Sentry is this with? This doesn't look like our latest.

**Comment by dcramer** [comment]
Closing as we dont have a vendor-jquery in Sentry 8
