### ISSUE TITLE
Connection refused from client when running under Cron

### ISSUE THREAD

**Issue by joedborg** [getsentry/sentry#2582]
If I run the following script locally (creds omitted), there is no problem:

```python
import raven
rc = raven.Client(dsn='http://sentry:9999/5')
rc.captureMessage('Hello')
```

But when I run this in a crontab (same user, same host), I get
```
Sentry responded with an error: <urlopen error [Errno 111] Connection refused> (url: http://sentry:9999/api/5/store/)
```

**Comment by mitsuhiko** [comment]
Do you need a proxy to talk to your sentry server? If yes, you might have to export that setting in your cron.

**Comment by joedborg** [comment]
No, I don't.  It's only started happening since upgrading to 8.0.1 from 7.7.4

**Comment by mitsuhiko** [comment]
My hunch is that this has nothing to do with sentry but something else. Could it be that `sentry` does not resolve to `127.0.0.1` under cron?

**Comment by joedborg** [comment]
I can do a test to see but, as mentioned, it worked fine in 7.7.4.

**Comment by dcramer** [comment]
Connection refused is a client error, so its absolutely not related to Sentry. Your server is simply unreachable from the client given the address.
