### ISSUE TITLE
Merge all issues matching query: ALL issues merged!

### ISSUE THREAD

**Issue by JeroenDN** [getsentry/sentry#2585]
I ran a search query which resulted in 30 issues. I checked the checkbox on the top left and the following message was displayed: "25 issues on this page selected. Select all issues matching this search query." I clicked "Select all issues matching this search query" and chose for "Merge Events". The result is that not only the 30 issues that were found, but ALL unresolved issues (15k+) have been merged into one group (all resolved issues remained untouched). It might be a more generic problem that is not only affecting the merge function. This is a serious bug and it should be fixed. But more importantly for me: how can I undo this action? Would it be possible to delete all messages and process the data from nodestore_node again? I'm using Sentry 8.0.2 with PostgreSQL. Thanks in advance.

**Comment by dcramer** [comment]
What version of Sentry? We haven't been able to identify an issue where it was incorrectly merging what the active search query was, but we recently added more UI to confirm the query so there was less confusion.

There is some code in master that will attempt to ungroup a merged issue, but it won't be able to restore 100% of data.

```
from sentry.tasks.merge import rehash_group_events
rehash_group_events(group_id)
```

**Comment by JeroenDN** [comment]
I'm using Sentry 8.0.2 with PostgreSQL.

I'll try the ungroup function, thanks very much.

**Comment by dcramer** [comment]
@JeroenDN FYI it might not be in 8.0.2 (I dont think we merged in that). We're aiming for an 8.1 release around Feb 1, but otherwise you could install from master (its stable).

**Comment by dcramer** [comment]
We fixed some broken behavior here (sorry!) in 8.0.3

**Comment by JeroenDN** [comment]
Wow, you're very fast. Great, thanks!

For future reference: 5ac41cc2a1926e399aa78ebd22b5830be4881ff1

**Comment by aheuermann** [comment]
Seeing this on 8.0.4 as well

**Comment by benvinegar** [comment]
See #2607

**Comment by benvinegar** [comment]
@aheuermann – we are going to publish a new release with the fix soon.

**Comment by aheuermann** [comment]
@benvinegar thanks!

**Comment by dcramer** [comment]
8.0.5 includes this fix. Once again we apologize for the issues his may have caused. We haven't back ported the rehashing code but if anyone's in need of that it's available in master as part of the merge tasks. It will also be available in 8.1 which will ship next week.

**Comment by davemcphee** [comment]
I understand this is fixed, but what is the correct steps for someone in this situation, running sentry 8.0.2? I copied in the 8.1 tasks/merge.py and attempted to run the rehash_group_events() function, but it failed. 
If you could let me know best course of action to undo this, and how to ascertain the group_id required by the function, that would be awesome :)

**Comment by dcramer** [comment]
You need to update Sentry. We don't support patch backports.
