### ISSUE TITLE
Jira "create new issue" and "link issue" broken

### ISSUE THREAD

**Issue by theoribeiro** [getsentry/sentry#25882]
## Important Details

How are you running Sentry?
Saas (sentry.io)

## Description

After installing the Jira integration, we cannot create new issues or link an existing issue. 
When trying to create the issue, the field "Reporters" is empty, not letting us create the issue as it is a required field. Other  fields like "Components", "Project" and "Issue Type" have the correct options, which shows the integration is "sort of working". 

When trying to link an existing issue, the "Issue ID" field is also empty, not letting us link anything.

I'm not sure if this is related but when we added the project in the Jira integration configuration page the following error happened after setting up the issue status for unresolved and resolved states: 

![image](https://user-images.githubusercontent.com/41117224/117161157-b1cf1800-ad8f-11eb-8fe7-9e2d9f93d127.png)

## Steps to Reproduce

1. Install Sentry app on Jira Marketplace
2. Finish set up on sentry.io by adding a project
3. Go to a Sentry issue and try to create a Jira issue from it

### What you expected to happen

The fields should have the correct choices shown allowing us to link or create an issue in Jira.

**Comment by BYK** [comment]
Pinging @getsentry/ecosystem for triage

**Comment by ceorourke** [comment]
@theoribeiro we can look into this more but if you type in "T" (for Theo) for example in the reporter dropdown do you see your name and are you able to create the issue?

**Comment by theoribeiro** [comment]
@ceorourke My bad! It was not clear to me that I could type on that field, I thought it was only a select box. Typing in the name of the reporter works. 

Closing this as it was an error on the user side. You might want to think if there's any way to make it a little clearer that it is not only a select box.

**Comment by ceorourke** [comment]
Hey @theoribeiro - I made this small change I hope helps https://github.com/getsentry/sentry/pull/25946
