### ISSUE TITLE
Webpack sourcemaps not working for minified code

### ISSUE THREAD

**Issue by MikeKasperlik** [getsentry/sentry#25889]
## Important Details

How are you running Sentry?

We run a on premise installation but I duplicated the setup to sentry.io to make sure it is not an issue with out local installation.

## Description

We have a react app build with webpack which reports errors to sentry. Sourcemaps are uploaded as part of the release process. As soon as we turn on webpacks `optimization.minimize` feature stacktaces on sentry are not correctly traced back to the original source or show errors in the UI + a strange error title with a `?` in it.

![Screenshot 2021-05-05 at 20 09 49](https://user-images.githubusercontent.com/1431474/117189046-0600e900-adde-11eb-92e2-e72e62b8da23.png)

Browsers + other tools (such as https://sokra.github.io/source-map-visualization) indicate no error with the sourcemap. 

## Steps to Reproduce

1. Compile app to produce a `bundle.min.js` + `bundle.min.js.map`
2. Upload via WebpackSentryPlugin or Sentry CLI to sentry
3. Crash
4. See errors in sentry web ui:

Stripped project for reproduction:

[Archive.zip](https://github.com/getsentry/sentry/files/6429349/Archive.zip)

package.json
```json
{
  "name": "app",
  "version": "0.0.1",
  "private": true,
  "dependencies": {
    "@sentry/react": "^6.3.5",
    "react": "^17.0.2"
  },
  "devDependencies": {
    "webpack": "^5.36.2",
    "webpack-cli": "^4.6.0",
    "webpack-dev-server": "^3.11.2",
    "html-webpack-plugin": "^5.3.1",
    "ts-loader": "^9.1.1",
    "typescript": "^4.2.4",
    "uglifyjs-webpack-plugin": "^2.2.0",
    "@sentry/webpack-plugin": "^1.15.1"
  },
  "scripts": {
    "build": "webpack --config webpack.conf.app.js",
    "start": "webpack serve --port 8001 --config webpack.conf.app.js"
  },
  "eslintConfig": {
    "extends": "react-app"
  }
}

```

index.tsx
```ts
import * as Sentry from "@sentry/react";

Sentry.init({
  dsn:
    "https://XXX@XXX.ingest.sentry.io/5750538",
  environment: "dev",
  release: "TEST",
});

//@ts-ignore
window.myUndefinedFunction();
```

Webpack conf:
```js
const HtmlWebpackPlugin = require('html-webpack-plugin')
const UglifyJsPlugin = require('uglifyjs-webpack-plugin')
const SentryCliPlugin = require('@sentry/webpack-plugin')

module.exports = env => {
  return {
    entry: {
      app: './src/index.tsx'
    },
    devtool: 'source-map',
    optimization: {
      minimize: true,
      minimizer: [
        new UglifyJsPlugin({
          sourceMap: true,
        }),
      ],
    },
    mode: "production",
    module: {
      rules: [
        {
          test: /\.(js|jsx)$/,
          exclude: /node_modules/,
          use: ['babel-loader']
        },
        {
          test: /\.tsx?$/,
          use: 'ts-loader',
          exclude: /node_modules/,
        },
      ]
    },
    output: {
      filename: 'bundle.min.js',
      sourceMapFilename: "bundle.min.js.map",
    },
    plugins: [
      new HtmlWebpackPlugin({
        template: 'public/index.html'
      }),
      new SentryCliPlugin({
        include: './dist',
        ignoreFile: '.sentrycliignore',
        ignore: ['node_modules', 'webpack.conf.app.js'],
        release: "TEST"
      }),
    ],
    devServer: {
      historyApiFallback: true,
      host: "0.0.0.0",
      writeToDisk: true,
    }
  }
}
```
.sentryclirc
```
[auth]
token=XXXX

[defaults]
org=XXX
project=XXX
```

### What you expected to happen

No error & correct error title/grouping

**Comment by BYK** [comment]
Pinging @kamilogorek and @lobsterkatie for triage

**Comment by chadwhitacre** [comment]
So what's the decision, are we closing as not our problem, or are we accepting this as a bug for us to work around?

**Comment by MikeKasperlik** [comment]
I tried quite a few combinations of options in terser / uglifyJs and was not able to get this working in a proper way. For me as a Sentry user some kind of hint what I can do in my application inside your docs would be great. 

I don't know the numbers, but webpack + minify seems like a pretty popular choice nowadays.

**Comment by kamilogorek** [comment]
@MikeKasperlik the main issue here is that you are throwing an error in the main code execution pipeline. The way webpack works, it that it bundles everything into an IIFE, so any error that will happen inside that initial code execution, will include this IIFE call as well, and there's no way around it.
However, once you go outside of that execution, be it any user interaction, events, clicks, timers, promises etc. it won't include that.

```js
function foo () {
  (window as any).myUndefinedFunction();
}

function bar () {
  foo()
}

setTimeout(() => bar())
```

![image](https://user-images.githubusercontent.com/1523305/118117493-00ae2a80-b3ec-11eb-9b4e-5ffb43f512ef.png)

There's nothing that we can fix it really, so I'll mark this closed. Cheers!
