### ISSUE TITLE
"Link Asana Issue" modal spontaneously closes

### ISSUE THREAD

**Issue by quinnleong** [getsentry/sentry#25892]
## Important Details

How are you running Sentry?
Saas (sentry.io) - in Chrome Version 90.0.4430.93 (Official Build) (x86_64)

## Description

The modal to create or link an Asana issue spontaneously closes in the middle of editing.

## Steps to Reproduce

1. Visit a specific issue in Sentry
2. Click the "+" next to Asana Issue under Linked Issues
3. Start editing and watch the modal disappear mid-edit, losing any changes made

This doesn't happen every single time, but most of the time. It also will happen repeatedly, sometimes three or four times in a row before I can finish editing the issue and submit. It also unfortunately does not save progress, so the changes have to be made repeatedly until they can be completed before the modal closes.

I don't see anything notable in the dev console. I have a GIF I can share if desired (although I'd prefer not to post it publicly here!).

### What you expected to happen

The modal shouldn't close until it's submitted successfully or the user closes it 🙂 

Thank you!

**Comment by BYK** [comment]
Pinging @getsentry/ecosystem for triage

**Comment by quinnleong** [comment]
I just found a little more context 🙂 It seems to happen consistently and only in this case:
- when linking an issue, not creating one
- when editing the "Comment" field _before_ the "Task" field has finished loading (the loading dots animation still going)

Hope this helps a little!

**Comment by manuzope** [comment]
Hi @quinnleong, can you email the gif to me at manu@sentry.io?

Would also be helpful to know your organization slug.

**Comment by manuzope** [comment]
Also, do you see any non-200s in the network tab?

**Comment by manuzope** [comment]
Quinn followed up with me with a gif but I'm unable to replicate it. Going to keep this issue open in case others have the same problem.

**Comment by sentaur-athena** [comment]
Closing since there weren't any recent instances.
