### ISSUE TITLE
No module named sentryext

### ISSUE THREAD

**Issue by weaming** [getsentry/sentry#2593]
```
# Sphinx version: 1.3.3
# Python version: 2.7.10 (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.8
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sphinx/cmdline.py", line 239, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib/python2.7/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/usr/lib/python2.7/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/usr/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "/usr/lib/python2.7/site-packages/six.py", line 672, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 241, in <module>
    import sentryext
ImportError: No module named sentryext
```

**Comment by mattrobenolt** [comment]
What did you do to trigger this? Looks like trying to render docs or something. 

If so, our docs are pretty complicated and I'd start with https://github.com/getsentry/sentry-docs

**Comment by weaming** [comment]
@mattrobenolt I try to `make build` in setry-docs:

```
13:35 weaming@Fedora:~/github/sentry-docs $ make build
--> Update api-docs venv
./bin/extract-docs
New python executable in /home/weaming/github/sentry-docs/.api-docs-venv/bin/python
Installing setuptools, pip, wheel...done.
make[1]: Entering directory '/home/weaming/github/sentry-docs/doc-modules/sentry'
make[1]: *** No rule to make target 'develop-only'。 停止。
make[1]: Leaving directory '/home/weaming/github/sentry-docs/doc-modules/sentry'
Processing /home/weaming/github/sentry-docs/doc-modules/sentry
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-build-k_Zp2l/sentry/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k_Zp2l/sentry
python: can't open file '/home/weaming/github/sentry-docs/bin/../doc-modules/sentry/api-docs/generator.py': [Errno 2] No such file or directory
python: can't open file '/home/weaming/github/sentry-docs/bin/../doc-modules/sentry/bin/dump-command-help': [Errno 2] No such file or directory
Makefile:57: recipe for target 'extract-docs' failed
make: *** [extract-docs] Error 2
```

**Comment by mattrobenolt** [comment]
All of this is @mitsuhiko territory. I can't help. :)

But what are you trying to accomplish? All of our docs are available at docs.getsentry.com.

**Comment by weaming** [comment]
@mattrobenolt I just want to know how to deploy sentry in my local linux OS, but it seems need charge.

**Comment by mattrobenolt** [comment]
Yeah, you shouldn't need to touch this stuff at all.

Just follow the instructions here: https://docs.getsentry.com/on-premise/server/installation/

**Comment by weaming** [comment]
This means it could be deploy absolutely free in local?

**Comment by mattrobenolt** [comment]
Sure. :)

**Comment by weaming** [comment]
Very well. Thank you ! 
But it's not obvious in its official website.
First I read is to register and try it for only 14 days.

**Comment by mattrobenolt** [comment]
We have two offerings. Our website https://getsentry.com/ is for our SaaS, which you can pay us for. Or you can run this software yourself since it's open source. We offer the SaaS because generally people don't want to be bothered running and managing the infrastructure needed themselves and it's easier to just pay us to do it instead.

**Comment by weaming** [comment]
Where is sentry server's setting files?
Could you help me? More will be late.

**Comment by dcramer** [comment]
@weaming you'll need to go through the on-premise docs. We dont provide general support for On-Premise beyond standard things like addressing bugs/issues. If you're not comfortable running Sentry (and its various dependencies), you likely will just want to use the SaaS service.

**Comment by weaming** [comment]
@dcramer Okay.

**Comment by mitsuhiko** [comment]
In case someone hits this in the future: the submodule for the sentry ext is needed to build docs in isolation.

@mattrobenolt should we include this in sdists? Honestly. I rather just ship the built docs with the dist.

**Comment by mattrobenolt** [comment]
We could ship the docs with 8.1 if you want to cram that in. I was under the impression that those wouldn't be needed though since we have docs.getsentry.com.

I think doing it as a part of sdist will be too complex. Maybe we could sync them from S3?

Not sure the value of bundling them though like that.

**Comment by mitsuhiko** [comment]
I remember having the discussion with @dcramer in the past that he wants the docs to be included for on-prem so that the API docs match up.

**Comment by mitsuhiko** [comment]
We could also host tagged tarballs for the docs.

**Comment by Wentil** [comment]
Guys, while following the install procedure you have provided at "https://docs.getsentry.com/on-premise/server/installation/", on a fresh install of the latest version of Ubuntu 14 LTS, I receive the same error, "Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yqYBxK/psycopg2", which fatally interrupts the install. Scrolling up through the list of tasks it's been performing, I see that this error was thrown:
----------------------------------------
  Running setup.py (path:/tmp/pip_build_root/psycopg2/setup.py) egg_info for package psycopg2
    Error: pg_config executable not found.

    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:

        python setup.py build_ext --pg-config /path/to/pg_config build ...

    or with the pg_config option in 'setup.cfg'.
    Complete output from command python setup.py egg_info:
    running egg_info
----------------------------------------

Any advice?

**Comment by mattrobenolt** [comment]
You're missing a dependency. plz re-read the installation docs. This is coming from a missing libpq-dev I believe.

**Comment by Wentil** [comment]
Yes I somehow missed that one, but I got all the others. Thanks, it's
installed now.

On Thursday, February 18, 2016, Matt Robenolt <notifications@github.com>
wrote:

> You're missing a dependency. plz re-read the installation docs. This is
> coming from a missing libpq-dev I believe.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getsentry/sentry/issues/2593#issuecomment-185954242>.
>


-- 
Sent from Gmail Mobile

**Comment by xoco70** [comment]
It happens to me when I do : `sudo -H sentry upgrade`. The first step to update : `sudo -H pip install --upgrade sentry`worked well. I also did `sudo -H pip install --upgrade pip`successfully

**Comment by mattrobenolt** [comment]
My only guess is using `sudo` is wrong. You're probably not in the correct virtualenv.

**Comment by xoco70** [comment]
`sentry upgrade` without sudo give the exact same result

**Comment by dcramer** [comment]
This is not a support forum. Please see https://sentry.io/support/ for options.
