### ISSUE TITLE
Tooltip cutoff at top of screen

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2595]
When scrolled down on the stream view and the toolbar is locked at the top of the page, the tooltip becomes useless and pop up/off the screen.

![image](https://cloud.githubusercontent.com/assets/375744/12559206/955af41e-c348-11e5-87ea-11987a95098d.png)

**Comment by mattrobenolt** [comment]
@benvinegar It'd be nice if we can get this before 8.1 today, if this is easy. I don't have enough context to know if this is easy or hard.

**Comment by benvinegar** [comment]
I'll take a look, but my first instinct is that it is non-trivial (like, a few hours vs an hour).

I also don't think this is a big enough issue to delay the release, etc. If it goes out in 8.2, cool.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
