### ISSUE TITLE
Expose client package name, version in event JSON

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2599]
Right now we just have `platform: javascript` – we don't know which client produced this event. It would be useful to see something like:

```json
{
  "platform": "javascript",
  "client-name": "raven-js",
  "client-version": "2.1.0"
}
```

**Comment by dcramer** [comment]
We have this in the super secret new spec. We could just backport little pieces of it. We're also going to need device info (vs server_name).

**Comment by tkaemming** [comment]
This would also help for situations such as the one that is about to occur with [getsentry/raven-java](https://github.com/getsentry/raven-java). We're going to be moving the package location after getsentry/raven-java#182 (from `net.kencochrane` to `com.getsentry`) and will need to alert users to update their dependencies to point to the new location. We don't have a reliable way to notify users of this change right now other than social channels or broadcasts.

**Comment by dcramer** [comment]
```
  "sdk": {
    "id": "raven-python",
    "version": "1.0"
  },
```

**Comment by dcramer** [comment]
@kstenerud @benvinegar @bretthoerner @mitsuhiko @mattrobenolt  thoughts on adding the sdk (per my latest comment) to clients? We'd keep platform how it is, and platform will reflect "android" even if its raven-java for the sdk.

We can quickly add it to the server, and old versions will just throw it away. So no need for a protocol bump.

**Comment by bretthoerner** [comment]
Seems fine to me. Should version be broken into major and minor (does patch and lower really matter?) for easy sorting on server side to say "Hey, looks like you're using X in your latest release, you should try Y"?

**Comment by dcramer** [comment]
@bretthoerner I'm wondering if it's simply enough to use a standard format. We could also add a "build" for supplemental version info, or we could dissect it into multiple params on the version. Seems like it might be overkill though.

**Comment by dcramer** [comment]
We can likely derive the SDK attribute out of the ``sentry_client`` authentication header when its not present in the JSON payload.

**Comment by dcramer** [comment]
Ended up bundling all the required changes into the PR.
