### ISSUE TITLE
Notifications contain exception message contents when Enhanced Privacy is enabled

### ISSUE THREAD

**Issue by tduzan** [getsentry/sentry#2600]
Currently, when a notification is triggered, the notification contains the contents of the exception message output itself, even though it strips other data such as url params.  In some cases exception messages can contain protected data and should also be stripped so that notifications only provide an exception class and nothing else when Enhanced Privacy is enabled in the settings.  This would limit accessing this information to logged in users who are authorized to see it.

Thanks.

**Comment by dcramer** [comment]
There's still an additional concern here that we show a message subject/title. It gets trimmed, but its possible for it to contain sensitive data.

**Comment by tduzan** [comment]
I'm not sure about other's situations, but at least in ours we're not worried about the message subject/class of exception, it's more the contents of the exception that could be sensitive.  Based on reading through the commit you made, it looks like this would resolve things as we see it.

Thanks.

**Comment by dcramer** [comment]
@tduzan we include a truncated version of the message in the subject. The message  in a lot of cases will be "{type}: {value}".

**Comment by tduzan** [comment]
Ah, yeah, that would still need to be corrected then.  Thanks for the clarification.  I'd suggest changing the subject to be the exception class or, in your format above, just "{type}".

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
