### ISSUE TITLE
Come Up With New Story on HTTP Data

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#2601]
This is the follow up to #2482: we need to come up with a good idea of how to represent HTTP body data that makes sense.  Right now it's a string that can end up being truncated or not and it's always a string which causes problems with unicode.

Maybe we need to have something like this instead:

```
"body": {
  "data": <arbitrary data>,
  "length": <number of bytes it had originally>,
  "type": <the type of data>
}
```

Where "data" can then be a base64 encoded string, a normal string, a rich data structure and "type" indicates what it is for the UI. We need to think about this clearer about how we want to deal with this.

Things to think about:
- why do we have the data?
- we need to understand the data to understand scrubbing at least in parts.
- for the user it needs to be clear when it was truncated so that they understand what to do with the data
- binary data is mostly only useful for msgpack/protobuf

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
