### ISSUE TITLE
When editing comment, "Updating issue" alert doesn't go away

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2603]
The comment is updated successfully, however.

![image](https://cloud.githubusercontent.com/assets/2153/12573166/818f1200-c3aa-11e5-8e63-35492e433896.png)

**Comment by mattrobenolt** [comment]
I'm going to look at this today. We'll see if I can handle it like a bit boy.

**Comment by mattrobenolt** [comment]
I can't seem to reproduce either locally or in production?

**Comment by benvinegar** [comment]
I can still reproduce. I deleted a comment, and this spinner didn't go away:

![image](https://cloud.githubusercontent.com/assets/2153/12763576/0118282c-c9aa-11e5-9be2-5763080690b5.png)

Looking at the network graph, I can see that the deletion XHR was canceled. Probably as a result of the comment being unmounted before the XHR finishes. This is likely a race condition.

![image](https://cloud.githubusercontent.com/assets/2153/12763634/4cbf31f8-c9aa-11e5-9d19-d803b1f06188.png)

Definitely a client-side issue; I'll take it.
