### ISSUE TITLE
Support grouping tracing spans by op and description

### ISSUE THREAD

**Issue by st0012** [getsentry/sentry#26049]
## Summary

Please support grouping tracing spans (especially sql spans) that have identical `op` and `description`.

## Motivation

Some APM services, like scout apm, group similar (sql) spans together. For example:

<img width="70%" alt="grouped_sqls" src="https://user-images.githubusercontent.com/5079556/118262514-95e21980-b4e7-11eb-8ff5-ad4a20785a18.png">

This makes n+1 queries obvious + saves the visual space.

And because Sentry doesn't support this, 10 n+1 queries generates 10 spans in the view. Like:

<img width="70%" alt="ungrouped_sqls" src="https://user-images.githubusercontent.com/5079556/118262551-9f6b8180-b4e7-11eb-96a4-eadec4a20b99.png">

From my experience, in endpoints that have many sql spans (like 200+), the information would become pretty much useless unless they're grouped together in some way. For example, this is a request that generated 700+ queries. And the spans view isn't very helpful to me

<img width="70%" alt="screenshot of 700 queries event" src="https://user-images.githubusercontent.com/5079556/118262794-fe30fb00-b4e7-11eb-8048-15acff5b4e21.png">

This is what scout displays for the same endpoint:

<img width="70%" alt="scout example" src="https://user-images.githubusercontent.com/5079556/118263070-5e27a180-b4e8-11eb-8f78-492bee38dade.png">

So I hope Sentry can have a similar feature to group spans with "exact same op & description".

**Comment by dashed** [comment]
@st0012 Some updates, @0Calories will be working on this 😄 .

**Comment by st0012** [comment]
@dashed thanks for the update!

**Comment by natematykiewicz** [comment]
I'd also love this feature. As a Scout and Sentry user, missing features like this keep me using Scout for performance monitoring.

Ideally I'd use Sentry for everything, but it's just not as robust as Scout yet.

**Comment by 0Calories** [comment]
Hi @natematykiewicz ,

This feature was recently shipped to all Performance users! :)
We'd also love to hear about any other features you'd like to see in Performance.

Going to close this issue.
