### ISSUE TITLE
Docker devservices changes not being tested

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#26052]
CC @billyvg @fpacifici 

Filippo landed a change that succeeded on sentry yet it failed on getsentry.
This is because they failed on the `Setup Getsentry` step with:
```
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/cdc/postgres-entrypoint.sh": stat /cdc/postgres-entrypoint.sh: no such file or directory: unknown")
```

On `getsentry` we run tests within a Docker set up.
We need to make `sentry` tests have a similar set up *but* meanwhile we could see why nothing got dispatched during the PR/master OR add a simple workflow on `sentry` to "start up the devservices"

* Success on `sentry`:
<img width="525" alt="image" src="https://user-images.githubusercontent.com/44410/118279056-ac14b900-b498-11eb-8438-88a8f16d2afa.png">

* Failures on `getsentry`:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/44410/118279081-b5058a80-b498-11eb-9685-4e84229ed48c.png">

* Failing step on `getsentry`:
<img width="186" alt="image" src="https://user-images.githubusercontent.com/44410/118279216-df574800-b498-11eb-9f8c-78d1513a71a2.png">

* Dispatcher not triggering anything:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/44410/118279904-a5d30c80-b499-11eb-8385-9b17c750aedb.png">

**Comment by BYK** [comment]
Another reason to find a way to converge self-hosted-powered e2e tests.

**Comment by bc-sentry** [comment]
CI tests will be using new devservices for service dependency management to solve this issue.
