### ISSUE TITLE
Protocol Additions

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2605]
Tentatively calling this Protocol 8.
## Device

Might be Browser, Phone, or OS (most appropriate context). While Browser has a relevant OS, it can be embedded as part of the device name if it actually matters.

```
{
  "name": "Chrome (Mobile)",
  "version": "46",
  "build": "46.0.1"
}
```

```
{
  "name": "Windows",
  "version": "95",
  "build": "some obscure version"
}
```

Additional arbitrary metadata could be provided similar to `user`.

One primary goal here is to index these in a usable way.

```
device.name:"Chrome (Mobile)"
device.version:"Chrome (Mobile) 46"
```

It's unlikely build matters enough for it to be indexed.
## SDK

Today we have platform, but that's more about "what language does this data represent".

See GH-2599
## Threads

Each thread contains various metadata (platform specific, such as the thread name/address) and an optional stacktrace.
## Language overrides
- Frames from diff platforms (e.g. Python calling into C)
- Language specific context within a frame (e.g. addresses from Swift)

**Comment by dcramer** [comment]
#2691

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
