### ISSUE TITLE
Can't assign issues to users on touch devices

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2606]
> Impossible to select assignee on mobile Chrome (Android 6.0) by touch. The only way that works is typing the name and pressing Enter.

**Comment by fongandrew** [comment]
Also experiencing this issue with desktop Chrome on Windows with a mouse.

**Comment by mattrobenolt** [comment]
@fongandrew Oh? That's much more concerning. :(

**Comment by mattrobenolt** [comment]
I wonder if it's related to this:

![image](https://cloud.githubusercontent.com/assets/375744/12688573/f80ca1fc-c68b-11e5-9ca5-e9c4280b5415.png)

All of the `<li>` containers are `disabled`.

**Comment by fongandrew** [comment]
That's actually not the issue for me. There's a `<div>` with a `dropdown-backdrop` class that's sitting on top of the  the `<li>` containers and intercepting all the clicks. Manually removing the backdrop in Chrome's inspector allows me to assign issues, regardless of backdrop.

**Comment by mattrobenolt** [comment]
Hmm, so this looks like it's coming from `bootstrap-dropdown.js`:

```javascript
        if ('ontouchstart' in document.documentElement) {
          // if mobile we we use a backdrop because click events don't delegate
          $('<div class="dropdown-backdrop"/>').insertBefore($(this)).on('click', clearMenus)
        }
```

But only on mobile. @fongandrew I feel like this shouldn't be happening for you on a desktop, according to this code. Lemme see if bootstrap has updated around here.

**Comment by mattrobenolt** [comment]
This plugin has been completely rewritten in most recent Bootstrap. Not sure if we're just using it wrong, or if there's a bug and we need to update.

**Comment by mattrobenolt** [comment]
@fongandrew Is there some reason why your computer would be thought that it's a touch device? Can you run this in Chrome console:

```javascript
'ontouchstart' in document.documentElement
```

I'm assuming this is `true` for you.

**Comment by fongandrew** [comment]
@mattrobenolt It's a laptop with a touch screen.

**Comment by mattrobenolt** [comment]
Ah, well then. :) I'm inclined to thing this is a bug in Bootstrap at the moment, but I'm going to have trouble debugging this.

/cc @benvinegar

**Comment by mattrobenolt** [comment]
Confirmed. I did not fix this, at least on iPad. Assuming the same for other touch devices. 

Gonna try and figure out how to debug this.
