### ISSUE TITLE
Events per minute / hour / day, etc.

### ISSUE THREAD

**Issue by dkarlovi** [getsentry/sentry#2610]
If you have a few dozen projects with a small number of issues, your "Events per minute" stat is useless because it's always equal to zero. It would be more useful if it would scale to your situation (so, per minute isn't useful, per day might be). Alternative is having a dropdown where you select the scale desired.

Not a big feature, but useful IMO.

**Comment by tkaemming** [comment]
@dkarlovi — is this referring to the number of the project list page (see screenshot) or somewhere else?

![screenshot 2016-03-25 14 56 57](https://cloud.githubusercontent.com/assets/65315/14054842/cc8e685a-f299-11e5-8d37-70293a3d67df.png)

**Comment by dkarlovi** [comment]
@tkaemming yes, sorry, should have made that much more clear.
