### ISSUE TITLE
crossorigin="anonymous" is incompatible with authenticating reverse proxies

### ISSUE THREAD

**Issue by gg7** [getsentry/sentry#2612]
I have Sentry accessible at `https://sentry.example.com/` which is actually an Apache server with custom authenticating logic. Only authenticated requests (those with a valid cookie) get proxied to Sentry. Everything was working perfectly with Sentry 7.7.4.

Sentry 8.0.4's `templates/sentry/layout.html` uses `crossorigin="anonymous"` for the [`vendor.js` and `app.js` `<script>` elements](https://github.com/getsentry/sentry/blob/951e993b56cc6ab768ea0883d73d9faefd065d08/src/sentry/templates/sentry/layout.html#L34-L35). This means that requests for those resources will not include any cookies even though they are on the exact same server (`https://sentry.example.com/`).

From Apache's point of view these requests are not authenticated and should not be proxied to Sentry. Consequently Sentry's front end doesn't load unless I patch `templates/sentry/layout.html`.

I'm aware I can whitelist `https://sentry.example.com/_static/*` requests in Apache and get Sentry working without any patching, but I'm reporting this since I was asked to do so on `#sentry`. Apparently other users have been affected by this as well (see IRC logs).

Setup:
* Sentry:
  * Version: 8.0.4 (pip + virtualenv)
  * OS: Ubuntu 14.04
  * Apache: 2.2.22
  * Python: 2.7.6
* Me:
  * Browser: Chromium 48.0.2564.82

**Comment by dcramer** [comment]
@benvinegar @mattrobenolt why do we use the CORS annotation here?

**Comment by mattrobenolt** [comment]
To avoid "Script error." on JS errors.

Technically, we only need this if STATIC_URL were different domain than the root url.

**Comment by dcramer** [comment]
so ``{{if not same domain}} crossorigin="anonymous"{{/if}}``  ?

**Comment by mattrobenolt** [comment]
Yeah, I could make that happen. I didn't know this would be a problem in any scenario.

Will take care of it.

**Comment by mattrobenolt** [comment]
@gg7 this will be in 8.0.6 and 8.1.0 which will be released Monday. :)

**Comment by gg7** [comment]
@mattrobenolt Thanks for the quick fix! :)
