### ISSUE TITLE
sentry event ip all are private ip address

### ISSUE THREAD

**Issue by Zuckjet** [getsentry/sentry#26152]
## Important Details

How are you running Sentry?

On-Premise , version 20.10.1

Saas (sentry.io)

Other, version x.y.z, [briefly describe your environment]

## Description

All of my sentry events's ip address start with 10, such as `10.42.251.99`, which is a private ip address.
![image](https://user-images.githubusercontent.com/17976139/118952059-32943380-b98e-11eb-988d-d0de28bda1d5.png)

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. and so on.

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant

### What you expected to happen

I want the ip address in my sentry event all are public ip address, how should I do ?

**Comment by BYK** [comment]
Please see the first paragraph of this section: https://develop.sentry.dev/self-hosted/#productionalizing
