### ISSUE TITLE
Add "Resolved in next release" and snooze to stream actions

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2616]
There are a bunch of actions only available from the issue view:
- Resolve in next release
- Snooze

![image](https://cloud.githubusercontent.com/assets/2153/12654383/8e54b4b8-c5a8-11e5-888f-306486549a84.png)

We are getting feedback from users that would like to perform these actions on more than one issue at once / would like these actions visible from the stream view. Currently only the following actions are possible:

![image](https://cloud.githubusercontent.com/assets/2153/12654407/aaed71b4-c5a8-11e5-8e98-b8e773dd2db0.png)

**Comment by dcramer** [comment]
I'd propose we do this:

- Move Mute out of the Snooze dropdown
- Rename Mute to Ignore (renaming this will be a bit of a pain in the ass)
- Add the checkbox to the resolve dropdown on details (☑️ Resolve) so it carries over to the shortened version well
- Consider an icon for snooze, and ignore (same pattern as above)
- Add secondary dropdown to stream for Resolve in Next Release (same as on issues)
  - This requires us to actually support this behavior, which we need to have a conversation about as its complex to do correctly.

**Comment by dcramer** [comment]
If we can come up with an icon (augmented check) that works for "Resolved in Release" we could make it show up in the dropdown and then on the stream have [Resolve | Resolve in Release] as their own button group.

**Comment by benvinegar** [comment]
We did this!
