### ISSUE TITLE
--config option doesn't pass along to uwsgi worker

### ISSUE THREAD

**Issue by mvaled** [getsentry/sentry#2617]
I have a long-running on-premises sentry installation.  I use the master branch.  Today I upgraded up to commit b0969558777d57a42eb0772f46179b2db502195c.

When I try to start the server:

```
sentry --config=etc/sentry.conf.py start
```

uWSGI complains it can't start without the `config.yml`.  So, I get it, there's a new configuration format.  But documentation is lacking.

I ran the `sentry init` command and brand new `config.yml` is now in my `/srv/sentry/etc/config.yml`.    I put in the sentry's user home, since it seems the 'sentry' command does not take the path to the config.yml.

Now I get another error about the 'cache.backend'... 

Where should I look for documentation on how to upgrade to latest master?

**Comment by mattrobenolt** [comment]
In theory, the same config should just work. Can you try with an absolute path in `--config`?

fwiw, `config.yml` isn't required as long as it finds an acceptable `sentry.conf.py`.

**Comment by mvaled** [comment]
Hi @mattrobenolt,

The abspath make no difference:

```
$ rm ~/.sentry/config.yml
$ sentry --config=/srv/sentry8/etc/sentry.conf.py start

...
*** no app loaded. GAME OVER ***
  File "/srv/sentry8/src/sentry/src/sentry/runner/__init__.py", line 106, in configure
    configure(ctx, py, yaml, skip_backend_validation)
  File "/srv/sentry8/src/sentry/src/sentry/runner/settings.py", line 300, in configure
    raise ValueError("Configuration file does not exist at '%s'" % click.format_filename(yaml))
ValueError: Configuration file does not exist at '/home/sentry/.sentry/config.yml'
unable to load app 0 (mountpoint='') (callable not found or import error)
```

**Comment by mattrobenolt** [comment]
Oh, it looks like it's still looking for it at `/home/sentry/.sentry/config.yml`.

For the hell of it, can you try `SENTRY_CONF=/srv/sentry8/etc/sentry.conf.py sentry start` ?

**Comment by mattrobenolt** [comment]
If that works, I know what the issue is. The config isn't getting passed the uwsgi workers.

**Comment by mvaled** [comment]
SENTRY_CONF works! :D

**Comment by mattrobenolt** [comment]
Yeah, then that's the issue. :) Will fix today.

**Comment by mattrobenolt** [comment]
@mvaled Wanna try with 302f3e2f7a28d229e5aa2185322c33dc473b1b66 now? It should fix you up. :)

**Comment by mvaled** [comment]
On it... I'll report in a few minutes.

**Comment by mvaled** [comment]
Worked!

**Comment by mattrobenolt** [comment]
:fire: Thanks for testing!
