### ISSUE TITLE
Uncaught (in promise) error not sending 

### ISSUE THREAD

**Issue by zatorck** [getsentry/sentry#26201]
## Important Details

How are you running Sentry?

Saas (sentry.io)

## Description

Hello I'm wondering why this errors are not pushed, all other errors are sended properly.

![sentry error](https://user-images.githubusercontent.com/11573475/119409333-71581f80-bce7-11eb-8bab-ff3b6741da6a.png)

## Steps to Reproduce

1. Install OneSignal API
2. Configure different domain for OneSignal from that is actually used in site

### What you expected to happen

Sending error to Sentry Sass

Thanks in advance

**Comment by BYK** [comment]
Can you please provide more information about your issue? Not everybody knows what OneSignal is (I don't for instance) and we need to be able to easily reproduce the issue you are having to be able to fix it (or even help you if this is not a bug).

It this a web application? Which Sentry SDK are you using and what version? How are you integrating it with your project?
