### ISSUE TITLE
Queue graphs incomplete

### ISSUE THREAD

**Issue by Stayallive** [getsentry/sentry#2623]
Hey Guys,

It looks like not all graphs are working in our on-premise installation:

![image](https://cloud.githubusercontent.com/assets/1090754/12696999/77ae21be-c778-11e5-840b-44783c7dca12.png)

While scrolling to the buttom I can see stuff happening:

![image](https://cloud.githubusercontent.com/assets/1090754/12697004/8dce3542-c778-11e5-8ea2-8822dc292c67.png)

Also the throughput and any other graphs looks correct:

![image](https://cloud.githubusercontent.com/assets/1090754/12697010/ab085fac-c778-11e5-916d-78a633b430ac.png)

Please let me know if I can provide some data! We use the almost default config from the installation guide using redis as a back-end.

**Comment by mattrobenolt** [comment]
Yeah, this global throughput graph is definitely busted. :(

**Comment by Stayallive** [comment]
Works great now, thanks :+1:
