### ISSUE TITLE
Sentry in docker has no notification email

### ISSUE THREAD

**Issue by cuirongqing** [getsentry/sentry#2629]
I install sentry in docker.  I can see all events but I cannot receive any notification mail.
It's strange that the test mail can notify successfully.  
- Sentry 8.0.5
- Python 2.7.11

I have made sure that

- Mail plugin is enabled and project is enabled in [http:/localhost:8080/account/settings/notifications](url)
![image](https://cloud.githubusercontent.com/assets/17017729/12741282/de9c1928-c9b5-11e5-9c61-4ff9a7d36f17.png)

-  The queue works fine.
![image](https://cloud.githubusercontent.com/assets/17017729/12741299/01ab97f4-c9b6-11e5-97f4-459cca46e68a.png)

-  I did not see any error in log.
`{"log":"[2016-02-02 06:06:02,417: INFO/MainProcess] Scheduler: Sending due task send-ping (sentry.tasks.send_ping)\n","stream":"stderr","time":"2016-02-02T06:06:02.418920036Z"}
{"log":"[2016-02-02 06:06:02,421: INFO/MainProcess] Scheduler: Sending due task check-auth (sentry.tasks.check_auth)\n","stream":"stderr","time":"2016-02-02T06:06:02.421568292Z"}
{"log":"[2016-02-02 06:06:02,619: INFO/MainProcess] Scheduler: Sending due task schedule-digests (sentry.tasks.digests.schedule_digests)\n","stream":"stderr","time":"2016-02-02T06:06:02.620291103Z"}
{"log":"[2016-02-02 06:06:04,723: INFO/MainProcess] Scheduler: Sending due task flush-buffers (sentry.tasks.process_buffer.process_pending)\n","stream":"stderr","time":"2016-02-02T06:06:04.724734059Z"}
{"log":"[2016-02-02 06:06:04,730: INFO/MainProcess] Scheduler: Sending due task sync-options (sentry.tasks.options.sync_options)\n","stream":"stderr","time":"2016-02-02T06:06:04.734650187Z"}
{"log":"[2016-02-02 06:06:14,732: INFO/MainProcess] Scheduler: Sending due task flush-buffers (sentry.tasks.process_buffer.process_pending)\n","stream":"stderr","time":"2016-02-02T06:06:14.732939296Z"}
{"log":"[2016-02-02 06:06:14,757: INFO/MainProcess] Scheduler: Sending due task sync-options (sentry.tasks.options.sync_options)\n","stream":"stderr","time":"2016-02-02T06:06:14.760265938Z"}
{"log":"[2016-02-02 06:06:24,763: INFO/MainProcess] Scheduler: Sending due task flush-buffers (sentry.tasks.process_buffer.process_pending)\n","stream":"stderr","time":"2016-02-02T06:06:24.763518561Z"}
{"log":"[2016-02-02 06:06:24,779: INFO/MainProcess] Scheduler: Sending due task sync-options (sentry.tasks.options.sync_options)\n","stream":"stderr","time":"2016-02-02T06:06:24.779931587Z"}
{"log":"[2016-02-02 06:06:32,634: INFO/MainProcess] Scheduler: Sending due task schedule-digests (sentry.tasks.digests.schedule_digests)\n","stream":"stderr","time":"2016-02-02T06:06:32.635682837Z"}
{"log":"[2016-02-02 06:06:34,780: INFO/MainProcess] Scheduler: Sending due task flush-buffers (sentry.tasks.process_buffer.process_pending)\n","stream":"stderr","time":"2016-02-02T06:06:34.781486883Z"}

Please tell me any idea how to find the problem and fix this issue.

Many thanks.
Rongqing

**Comment by mattrobenolt** [comment]
Hey @cuirongqing Do you mind opening this ticket on https://github.com/getsentry/docker-sentry ? Assuming you're using our image.

**Comment by mattrobenolt** [comment]
But from my understanding, this is mostly confusing for people because emails are sent from workers, and the test email gets sent by the web process. This generally happens when the worker and the web are running different configurations. For example, email being configured correctly in web container, but not updating working container with the same settings.
