### ISSUE TITLE
Req: Allow to make default the current custom search

### ISSUE THREAD

**Issue by mvaled** [getsentry/sentry#2630]
It would be nice to allow making the current custom save the default.

When you define a new custom search you have the option to make it the default for you and/or your team.  However, once it's defined there's no way to make it the default.  I would like to make the "Needs Triage" custom search my default, since it's my duty to ensure all issues are being properly assigned.

**Comment by dcramer** [comment]
@mvaled hit manage searches and you can make the default from there (or go to Settings => Saved Searches).

We plan to expand on the dropdown UI, but we generally take the approach of doing a minimal UI and expanding once things feel comfortable.

(Also currently you cant change your personal default unless you're an admin)
