### ISSUE TITLE
Github Session

### ISSUE THREAD

**Issue by DaveBlooman** [getsentry/sentry#2635]
After upgrading from 1 EC2 instance to 2, I am unable to login, i'm guessing my load balancer is sending traffic back and forth.  Is the session data stored in Postgres/Redis, so when i'm using via an ELB, the user will be able to hold their session?

**Comment by dcramer** [comment]
Sessions are mapped via a secret-key which is stored in the config (and thus needs to be shared). That said user details are stored in the Postgres database (so your auth should still work).

**Comment by DaveBlooman** [comment]
Thanks for the fast response, I was generating the config.yaml on boot, so my keys were random.
