### ISSUE TITLE
Create a docker image for running Sentry's test suite

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#26364]
We should create a docker image for running Sentry's test suites (similar to what we do in `getsentry`). This will allow us to re-use these images on other repos when running Sentry's test suites.

**Comment by BYK** [comment]
Can we not use the Python wheel we already build for self-hosted in GHA?

**Comment by billyvg** [comment]
@BYK Can you point me to what you're referring to?

**Comment by BYK** [comment]
https://github.com/getsentry/sentry/blob/6de06ca91f0c2bc0a62530af3341d70d4e0eb962/docker/cloudbuild.yaml#L91-L94

@joshuarli may know better.

**Comment by joshuarli** [comment]
Those wheels would save about the ~5m needed to build static assets and whatever time would be involved installing yarn deps (thanks to sentryio/sentry-builder), but you'd have to wait until they're uploaded which takes ~13m which includes other things like running some e2e tests (though, I don't see any issue with moving the upload step before).

I can envision a future where sentry has a fast ensure-python-image for most testing, and then an ensure-image for like, acceptance testing, which either installs static assets through those wheels OR uses assets generated from frontend testing - I'm not very clear on the state of things with frontend separation there and I would guess there's opportunity for reuse/deduplication between you two.

**Comment by BYK** [comment]
@billyvg btw. I don't understand the benefits of having a Docker image for testing. Can you share a bit more context around this?

**Comment by billyvg** [comment]
@BYK The end goal here is to run a subset of sentry tests on other repos, e.g. snuba, relay, symbolicator.

**Comment by armenzg** [comment]
Not necessary for https://github.com/orgs/getsentry/projects/15 after all.
