### ISSUE TITLE
error on fetch of javascript source

### ISSUE THREAD

**Issue by lfalcao** [getsentry/sentry#2642]
Hello,

I've been seeing a lot of errors from celery worker on the fetch_file method _(File "/usr/local/lib/python2.7/dist-packages/sentry/lang/javascript/processor.py", line 296, in fetch_file)_, it's usually a timeout (defaults to 30s) or a connection refused. In both cases, i receive the message: Disabling sources to {HOST} for 300s

So, in this case isn't better skip the source download? There's any way to do it besides ignore all source download (SENTRY_SCRAPE_JAVASCRIPT_CONTEXT)? Tks

Version: 8.1.1

**Comment by mattrobenolt** [comment]
@lfalcao What's the concern here? This is normal behavior and isn't really an error, more like a warning.

You could disable source fetching globally, as you pointed or, or disable it on a per-project level from within project settings.
