### ISSUE TITLE
Unable to transfer project

### ISSUE THREAD

**Issue by SamPeng87** [getsentry/sentry#26445]
## Important Details

How are you running Sentry?

k8s, version 21.5.1

## Description

[What happened]

## Steps to Reproduce

1. transfer project to xxx@xxx.xxx@xxx is member of project
2. show me error is: Unable to transfer project

logs is
```
POST /api/0/projects/startimes/stariboss/transfer/ [404]
```

### What you expected to happen

success transfer for project.

**Comment by BYK** [comment]
It is not clear what is happening can you please describe your issue with more details?

**Comment by markstory** [comment]
That 404 error should also have a response body with the reason why the project cannot be transfered. In a future self-hosted release that error message will also display in the UI from #26318
