### ISSUE TITLE
Getting 'Oops!' page after upgrading self-hosted version

### ISSUE THREAD

**Issue by avasa** [getsentry/sentry#2648]
These were the steps I took to upgrade Sentry.

1) pip install --upgrade sentry
2) Then I noticed pip notification, so then I did - pip install --upgrade pip
3) source bin/activate
4) supervisorctl restart sentry-worker
5) supervisorctl restart sentry-web

I'm getting 'sentry, version 8.1.1' on sentry --version

Any help would be appreciated.

Thanks.

**Comment by dcramer** [comment]
Please read the upgrade instructions as you're likely missing a step additionally there is not any information about the actual error here.



    _____________________________

**Comment by avasa** [comment]
Can you please post link to correct upgrade documentation.

Thanks in advance.

**Comment by avasa** [comment]
Found it.

Link is https://github.com/getsentry/sentry/blob/master/docs/upgrading.rst

Thanks for you help.
