### ISSUE TITLE
Arbitrary snooze durations

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2651]
Right now, we have 4 hardcoded options, `30 minutes`, `2 hours`, `24 hours`, or `forever`. There's no option to do for any duration in between.

I was thinking we should add an `Other`, which would trigger a popup to allow entering in a value such as `15m`, `5h`, `10d`, etc.

Thoughts?

**Comment by benvinegar** [comment]
Do we really get much user feedback on this? Seems like the numbers likely cover most use cases.

**Comment by mattrobenolt** [comment]
Not a ton, but I agreed that there is a huge gap from 1 day to forever. The feedback was they wanted to snooze it for one week, and at that point, it's prob not terrible to just allow arbitrary input since the API already handles it.

**Comment by mattrobenolt** [comment]
For example, I could see these being snoozed for sprint cycles, etc.

**Comment by benvinegar** [comment]
I'd sooner just add "1 week" before we add arbitrary.

I see complexity added by adding arbitrary, e.g. now we have to validate those strings in the client and show error messages. For a feature that we're not sure enough people would use. Death by a thousand cuts, etc.

I'm in favor of keeping this ticket open to see if this is really a pain point for users. And/or add "1 week" as an interim step.

**Comment by mattrobenolt** [comment]
Yeah, adding 1 week would be easy, just didn't want to keep chasing whatever people want.

Alternatively, we could also present a slider for "Other", but that's more complex.

**Comment by rockhunters08** [comment]
The gap of 24h to forever is huge, especially for services on longer (e.g. weekly) release cycles.  Would think, at minimum, snooze for 1 week and 1 month should be added in, or some configurable amount.  Even better, read the quantities from a  config file before starting the app.  Most people know the durations their teams need, so I don't think arbitrary is as important as being able to configure the list.

**Comment by benvinegar** [comment]
We ended up adding both "1 week" and a custom dialog.
