### ISSUE TITLE
make develop in sentry and getsentry is not consistent

### ISSUE THREAD

**Issue by dashed** [getsentry/sentry#26535]
Creating this issue ticket at the request of @armenzg .

-----

The behaviour of `make develop` in `sentry` and `getsentry` is not consistent:

- https://github.com/getsentry/getsentry/blob/1fac6fd548bda2d9c42295d18d03906c46a4499c/Makefile#L15-L16
- https://github.com/getsentry/sentry/blob/0f255b6dabf7332025215be22ee5200961a4f98d/scripts/lib.sh#L142-L146

In summary, `make develop` in `sentry` will ***not*** run migrations (i.e. `make apply-migrations`), whereas in `getsentry` they are run (whether or not migrations needs to be applied).

We should keep the behaviour consistent.

-----

As a primary developer on the Sentry product, I prefer the `make develop` behaviour on `getsentry`, since it is only one command I need to run at the beginning of my work day to pull in changes. And I do not have to think too much of how to bring my local getsentry development environment at the latest and stable working state.

**Comment by bc-sentry** [comment]
getsentry is being deprecated
