### ISSUE TITLE
Feature request: Allow import of error reports by uploading json files or archives

### ISSUE THREAD

**Issue by pstuermlinger** [getsentry/sentry#2654]
Hello Sentry,

I hope this is the right place for a feature request.

We'll have some embedded devices which host an Ember app. Since the embedded device and the client devices are on a private network, we want to store the error reports either at the client or the embedded device and import them later into the Sentry server via the sentry webinterface.

Having an import function like this would be a great USP for Sentry.

Kind regards,
haggins

**Comment by dcramer** [comment]
I think more discussion needs to be had around this specific use case (can we do something better?), but we have talked about having a way to import the JSON payload for an event several times, if nothing else then for debugging processing issues.

**Comment by haggins** [comment]
Thanks for your reply, dcramer. If such a feature would not fit into the UI concept, you could also think about a (configurable) directory at the filesystem where someone can store appropriate data. Once the cron runs, Sentry takes notice of these files and imports them.

An interface solution would be the most user friendly one for the customer support. However, if this requires too much work by your UX designers, a quick 'n dirty filesystem watching import feature would do the job as well.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

/cc @jan-auer in case you have some ideas/plans around this.
