### ISSUE TITLE
Upcoming feature: Support Semantic Versioning

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#26562]
## Background ##

On mobile/native, version names are usually not commit sha, but SemVer. Developers on these platforms have usually different release workflows than on the web platforms. On the web, almost every release gets adopted immediately and is usually the only one used at the time. On mobile, adoption time takes longer and developers often need to support/patch multiple major versions at the same time.

Single release filter is in this scenario often just too granular. We are working on filtering results (errors, transactions, sessions, and releases) by a range of releases with wildcards.

We want to provide a way to answer questions like “What's the crash rate of releases > 12.2.4" or "What are new issues on 11.* versions”.

We're in the development of some features to help with this and would love to get your input.

### SemVer Filtering ###
We'll extend the search query syntax to allow SemVer filtering. The syntax could look something like this and will be available out of the box in Project Details, Issues, Performance, Releases, Discover, and Dashboards.
```
release:8.19.1
release:8.*
release:<12 AND release:>8
release.major:8
release.minor:19
release.patch:1
release.revision:2
release.build:123
release.prerelease:dev
release.package:io.something
```
<img width="1439" alt="Screenshot 2021-06-11 at 17 47 37" src="https://user-images.githubusercontent.com/9060071/121713639-5fdf8780-cadd-11eb-9156-f78ec52aea5c.png">

### Sort Releases by SemVer ###
In addition to our usual release sorting options, we'll add two new: Sort by Semantic Version and Sort by Build Number.
<img width="1439" alt="Screenshot 2021-06-11 at 17 44 46" src="https://user-images.githubusercontent.com/9060071/121713806-87365480-cadd-11eb-95fc-a791dd07867a.png">

### Resolved in SemVer ###
We currently support resolve in the next release, current release, and any other existing release.
If we detect SemVer, we'll add 3 more: next major, next minor, next patch.
<img width="1436" alt="Screenshot 2021-06-11 at 17 48 48" src="https://user-images.githubusercontent.com/9060071/121713834-8dc4cc00-cadd-11eb-8f39-b4592d17e87f.png">

### Project Details ###
We'll add the new release filter to our Project Details page, enabling you to see high-level statistics scoped to a major/minor version.
![Untitled](https://user-images.githubusercontent.com/9060071/121713910-a6cd7d00-cadd-11eb-8fe9-066192251123.png)

## Feedback ##
If you have any feedback/feature requests, let us know in the comments. Or if you'd like to be an early adopter, email workflow-feedback@sentry.io.

**Comment by marandaneto** [comment]
@matejminar very nice, thanks.

questions: 

`release:<12 AND release:>8` is filtering by `major` I assume?
`release.build:123` is `build` the last appended number in the release string? `package@version+build`
`release.package`, the `package` naming would work in a few technologies but not all, the question here is, should we find a generic name for "unique app identifier" or is it fine that other platforms would adapt? on Android is `application id` (but has the package format a.b.c...), on iOS is `bundle id`, on Flutter is `name`.

**Comment by matejminar** [comment]
> `release:<12 AND release:>8` is filtering by major I assume?

would you expect this to translate under the hood to `release:<12.* AND release:>8.*`, therefore `8.1` would not match or should it translate to `release:<12.0 AND release:>8.0` so that `8.1` matches?

> `release.build:123` is `build` the last appended number in the release string? `package@version+build`

yes

> `release.package`, the `package` naming would work in a few technologies but not all, the question here is, should we find a generic name for "unique app identifier" or is it fine that other platforms would adapt? on Android is `application id` (but has the package format a.b.c...), on iOS is `bundle id`, on Flutter is `name`.

we are basing this on our documented recommended format of `package@version+build`
we could create an alias so that it's more natural to people, maybe `identifier`?

**Comment by marandaneto** [comment]
> > `release:<12 AND release:>8` is filtering by major I assume?
> 
> would you expect this to translate under the hood to `release:<12.* AND release:>8.*`, therefore `8.1` would not match or should it translate to `release:<12.0 AND release:>8.0` so that `8.1` matches?

I'd expect that `release:<12 AND release:>8` includes every 8.x releases, but none of 12.x releases since its a `<` and not `<=`

> we are basing this on our documented recommended format of `package@version+build`
> we could create an alias so that it's more natural to people, maybe `identifier`?

the docs depend on the platform, see iOS which calls `CFBundleIdentifier` instead of `package`
https://docs.sentry.io/platforms/apple/configuration/releases/

Android calls `packageName`
https://docs.sentry.io/platforms/android/configuration/releases/

so I just wanted to give food for thought, other option would be removing this specific platform doc about the versioning format and instead, linking directly to the common release health page, which explains more in detail, wdyt? so then we can call whatever is documented in the official docs.

**Comment by yordis** [comment]
Kind of related, I have been trying to standardize with https://calver.org/ as for the web rather than having commit SHA, would be amazing to have something similar

**Comment by matejminar** [comment]
@yordis We've taken CalVer into account and these new features will play nicely with it 👍

**Comment by sebathomas** [comment]
A small question about issue resolution: Does this also imply that the order of releases will follow the semantic version? For example, if I resolve an issue for version 2.3, it will not be reported as a regression if it occurs in version 1.7 (independently of the order in which those versions were released)?

**Comment by matejminar** [comment]
@sebathomas that's correct! If your project uses semantic versions and you click resolve in next/current/another version, the regression algorithm will look into semantic value, not the release date.

**Comment by matejminar** [comment]
The feature has been implemented. Closing this issue. Thank you for all your feedback.

Docs here: https://docs.sentry.io/product/releases/usage/sorting-filtering/

**Comment by yordis** [comment]
@matejminar no CalVer support?

**Comment by matejminar** [comment]
@yordis We use CalVer in sentry self-hosted repo (https://github.com/getsentry/self-hosted/releases) and these new semver features were compatible with that and worked well for us. 
If you run into any problems, please feel free to open up a new issue so that we can look into it.
