### ISSUE TITLE
Sentry 8 cannot be run when installed via buildout

### ISSUE THREAD

**Issue by do3cc** [getsentry/sentry#2662]
Hi,

I am investigating what to do about it and will add a PR when finished.
So far the issue seems to be that uwsgi is unaware about the eggs installed via buildout. I just need to find a good way how to make uwsgi aware of those buildout installed eggs.

**Comment by mattrobenolt** [comment]
What happens in this case? I've never used buildout, and we technically don't support it, but if it's a simple fix and we regressed here, it would be worth fixing.

This also sounds like a thing @mitsuhiko would be aware of.

**Comment by mattrobenolt** [comment]
This seems to be the closest I've found. https://www.seantis.ch/blog/getting-pyramid-to-work-with-uwsgi-in-a-buildout-environment

**Comment by do3cc** [comment]
yes, that is the same thing I found. I hope to continue working on this, but I got sidetracked here. No worries, this is going to work ;-)

**Comment by dcramer** [comment]
Closing this as it's not something we'll actively support. PRs accepted to improve support here, but it'll likely break again in the future without some Travis CI integration.

**Comment by do3cc** [comment]
FYI, I got it working like that:
I created a uwsgi.ini:
```
[uwsgi]
pythonpath = /home/sentry/sentry_psql/eggs/*.egg
pythonpath = /home/sentry/sentry_psql/extras
pythonpath = /home/sentry/sentry_psql/src/*
```
The fist path is required for the python eggs,
The second path is required for a simple middleware to handle multiple proxies
The third path is required for the source checkout of the gitlab authentication plugin.

Then I call `sentry start` with an additional env var UWSGI_INI=.../uwsgi.ini
I'd have preferred to set the pythonpath via an env variable, but you can not use it to pass multiple values in there.

These problems are not sentry specific. I am going to write a blog post about it, We Ploners will use WSGI more in the future, then we have to get this working too.
