### ISSUE TITLE
How to disable user register on self hosted server ?

### ISSUE THREAD

**Issue by MiteshShah** [getsentry/sentry#2663]
I'm not able to find disable user registration

Can anyone guide me here.

**Comment by dcramer** [comment]
SENTRY_FEATURES['auth:register'] = False

**Comment by MiteshShah** [comment]
@dcramer Sorry but I'm new to sentry can you tell me which file should i add this

Thanks

**Comment by dcramer** [comment]
@MiteshShah this goes in the config.py file

**Comment by MiteshShah** [comment]
@dcramer Edited ~/lib/python2.7/site-packages/sentry/conf/server.py with your suggested changes and restarted sentry and its works good as expected

```
fuuer -k 9000/tcp; && SENTRY_CONF=~/.sentry sentry start &
```

**Comment by rudyryk** [comment]
When registration is disabled, I can't create an organization on the first login (by superuser created from console):

![screenshot 2016-05-25 15 09 32](https://cloud.githubusercontent.com/assets/4500/15539446/9083d140-2293-11e6-85ff-c61f2564bff5.png)

Not sure thought if it's fixed in the master branch or not, I'm using the latest version from the PyPi.

**Comment by dcramer** [comment]
User registration shouldn't be controlling anything related to organization created. There's a single organization by default in installations, and if you're getting this it means that something went wrong w/ the installation and you weren't granted access. I would try re-creating the database, but otherwise you need to manually add the membership.

**Comment by rudyryk** [comment]
Hi @dcramer! I'll take a deeper look on that as I'll need to perform a fresh install soon.

> There's a single organization by default in installations

Should it be created during a database initialization?

What I did:

1. `sentry upgrade`
2. `sentry createuser --superuser`
3. logged in as superuser to the running Sentry
4. created an organization via the web interface (with enabled 'auth:register' feature)
5. then disabled 'auth:register' feature

**Comment by dcramer** [comment]
``auth:register`` is literally only for "can I create new users", it has nothing to do with organizations

"single organization mode" is enabled on new installs when generating the config which disables creating multiple orgs, and when you create a user (via ``sentry createuser``) they get added to that org

**Comment by VikramTiwari** [comment]
@dcramer How is `SENTRY_FEATURES['auth:register'] = False` passed if I am running sentry on docker container? Couldn't find anything on docker hub.

**Comment by dcramer** [comment]
@VikramTiwari via sentry.conf.py, the same way as any install. Our Docker setup runs no different than our standard install. You should take a look at our installation docs for more information.

**Comment by VikramTiwari** [comment]
Ah! I was using the publicly available sentry image from docker hub. This is even better. Thanks! 👍

**Comment by mackermedia** [comment]
@dcramer : I attempted adding `SENTRY_FEATURES['auth:register'] = False` to the `sentry.conf.py` in my fork, then running `make build`, and restarting the docker containers, however I'm still seeing the ability for users to register.

Am I missing a step? Can you confirm that this works?

**Comment by marcelom56** [comment]
@mackermedia 
We had the same problem here and we solved adding this line to Dockerfile:
`COPY sentry.conf.py sentry.conf.py`

After that, we remove the onpremise_web image (docker rmi onpremise_we) and ran those commands again:
`docker-compose run --rm web upgrade`
`docker-compose up -d`
