### ISSUE TITLE
Support HTTP(S)_PROXY env var

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2665]
For installs that are behind firewalls, they might not be able to access the internet directly, but instead need to be proxied through an outbound proxy.

`requests` already supports this with `HTTP_PROXY` and `HTTPS_PROXY` env vars as documented here: http://docs.python-requests.org/en/master/user/advanced/#proxies

Our problem stems from `sentry.http` which tests everything through our `BlacklistAdapter` first. This `BlacklistAdapter` does a DNS lookup to check against a set of IP addresses. In these scenarios, you also cannot do a DNS lookup directly, and that's expected to be delegated to the proxy. So there's no way that we can enforce a blacklist and we can assume its' the proxy's responsibility to prevent potentially dangerous access on their networks.

There are a few things we can do here:

* Detect the presence of `HTTP_PROXY` or `HTTPS_PROXY` on our side and skip the `BlacklistAdapter` entirely.
* Default the `SENTRY_DISALLOWED_IPS` to an empty list, and on empty list, ~~skip `BlacklistAdapter`. We should do the latter part of this anyways~~ 112dd509a853143da51101ef746d0a44892d76fc.
* Document whatever we come up with on how to run sentry in these environments.

See: https://github.com/getsentry/sentry-slack/issues/37 and #2491 (there have been others that have come up in the past)

/cc @dcramer

**Comment by dcramer** [comment]
This is resolved by changing DISALLOWED_IPS
