### ISSUE TITLE
Be able to run relay integration tests with the test docker setup

### ISSUE THREAD

**Issue by dashed** [getsentry/sentry#26668]
The test docker setup for Sentry development is documented in https://develop.sentry.dev/testing/#getting-setup

Posted here for posterity:

```sh
# Turn off services for local testing.
sentry devservices down

# Turn on services with a test prefix to use separate containers and volumes
sentry devservices up --project test

# Verify that test containers came up correctly
docker ps --format '{{.Names}}'

# Later when you're done running tests and want to run local servers again
sentry devservices down --project test && sentry devservices up
```

This docker setup is incompatible with relay integration tests when running this locally: 

```
pytest -vv tests/relay_integration/tests.py
```

The relay setup assumes there is a `sentry` network, and will attempt to connect to docker containers brought up with `sentry devservices up` (e.g. `sentry_kafka`).

We should expect to be able to run relay integration tests that is agnostic to how docker containers are setup.

**Comment by bc-sentry** [comment]
New devservices will allow this control.
