### ISSUE TITLE
When merging issues, the assignee is (temporarily) removed

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2667]
To reproduce:
- From the issues stream, have two distinct issues
- On a single issue, assign a user
- Merge the two issues
- The resolved, "final" issue will appear to have removed the assigned user

The user is still assigned on the backend. Refreshing the page will restore the UI properly and you will see the user assigned.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
