### ISSUE TITLE
When merging issues, external linked issues can be lost

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2668]
To reproduce:
- From the stream, have two issues
- Create an external linked issue (e.g. GitHub) for the bottom-most issue
- Merge the two issues

Result: Sentry takes the highest ID by default, and so the second issue is removed from the page. The earlier, "parent" issue has no external issue ID. When you refresh, the external issue ID does not return.

Example:

![merged-issues-external](https://cloud.githubusercontent.com/assets/2153/12993345/90b506d2-d0ce-11e5-844a-6363bf038a6a.gif)

Note that if instead, the "parent" issue had a linked external issue ID, it would still be there. Only child external issue IDs are lost.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
