### ISSUE TITLE
app.getsentry.com is hard coded in Login Page

### ISSUE THREAD

**Issue by cnuss** [getsentry/sentry#2669]
https://github.com/getsentry/sentry/blob/c89d63e5b32cdce872ee7f3887e63560f081eb1d/src/sentry/templates/sentry/login.html#L67

For the on-prem install, it should use the configured URL of the service, correct?

Sentry 8.1.2 (but still in Master Branch)

**Comment by dcramer** [comment]
Yep good catch!

**Comment by dcramer** [comment]
Just realized why this has never come up before.

@cnuss you should likely be running SENTRY_SINGLE_ORGANIZATION = True in your config. When thats the case there's only ever one login page, and it bypasses these screens.

**Comment by dcramer** [comment]
We're going to have to change the messaging/UI on this entirely to fix it, as just swapping out the prefix isn't doable.

At some point we'll fix this, but definitely not high priority.

**Comment by cnuss** [comment]
@dcramer thanks for taking a look
- I'm leveraging multiple orgs for our on prem install for each team (Backend, Frontend, Mobile) so that's why I disabled SENTRY_SINGLE_ORGANIZATION
- this is merely a cosmetic issue so no worries on demoting the priority

p.s. there's some funky issues I've come across once disabling SENTRY_SINGLE_ORGANIZATION, I'll let you know about those issues separately

**Comment by mattrobenolt** [comment]
Just realized this was fixed long ago. :) Closing.
