### ISSUE TITLE
Unable to get lock; should I be concerned? (on-premise)

### ISSUE THREAD

**Issue by mwcz** [getsentry/sentry#2682]
I just upgraded from 7.x to 8.1.2 and am seeing many messages like this in my sentry workers error log:

    Skipped process on b:k:sentry.grouptagvalue:bbb052c2f35c2b973fa222124e532974; unable to get lock

I'd estimate 30-40 of these per minute.  Is this a misconfiguration on my part?

**Comment by dcramer** [comment]
Did you setup SENTRY_CACHES

There were lots of changes between 7.x/8.x, so if you didn't you'll want to go through the upgrade guide and the new settings, as well as the CHANGES.

**Comment by mwcz** [comment]
Thanks, I'll check into that.  I didn't see that setting in the upgrade guide (this one: https://docs.getsentry.com/on-premise/server/upgrading/ ) or in the changelog ( https://docs.getsentry.com/on-premise/server/changelog/ ).

**Comment by dcramer** [comment]
Generally a good rule of thumb when doing large upgrades (and we should doc this), is to generate a new config file. We don't patch in new settings in the old file, so your configuration will get out of date over time.

**Comment by mwcz** [comment]
:+1: thanks, you are truly god's gift to programming.

**Comment by dcramer** [comment]
Added some clarity to upgrade notes in e7d31972ee25ec1185aaf6b658ecae732c7a0522

**Comment by benvinegar** [comment]
> :+1: thanks, you are truly god's gift to programming.

what have you done, now we will never hear the end of this

**Comment by mwcz** [comment]
@benvinegar he started it ;) https://twitter.com/zeeg/status/685551732038881280

**Comment by benvinegar** [comment]
Oh wait, he is quoting me ... this has come full circle, and I only have myself to blame :(

**Comment by mwcz** [comment]
The ciiiiiiiiiiiiiircle of zeeg!

I generated a new config file, copied my existing values in, installed memcached and uncommented `CACHES`, which I hoped would enable memcached.  I'm a bit disoriented about the various cache settings, their interdependencies and ideal values.  @dcramer said to use `SENTRY_CACHES`, which I can't find, but I do see `CACHES`, `SENTRY_CACHE`, and `SENTRY_CACHE_OPTIONS` in conf/server.py.

**Comment by dcramer** [comment]
Oh sorry, its ``SENTRY_CACHE``. ``CACHES`` isn't really needed. It saves some DB usage, but its not overly useful in Sentry. We use ``SENTRY_CACHE`` for locks. If you're seeing the lock issue it would imply to me that something is wrong w/ the cache backend, but that might not be true. You'd also want to ensure everything else is setup correctly (``SENTRY_BUFFER``, queue isnt overloaded).

**Comment by mwcz** [comment]
SENTRY_CACHE = 'sentry.cache.redis.RedisCache'
    SENTRY_BUFFER = 'sentry.buffer.redis.RedisBuffer'

I don't know if this is related to the lock issue, but I'm now seeing thousands of `Data not avaialble in preprocess_event (cache_key=e:foo)` when I restart my Sentry services.

**Comment by dcramer** [comment]
@mwcz this can be caused by the workers not being able to keep up w/ the inbound rate of data. The data expires from the processing pipeline cache after 1h.

**Comment by mwcz** [comment]
Still no luck on either count.  Memory and CPU are both <1% utilized, so it doesn't feel like the queue could be overflowing.  I guess Redis could be misconfigured, but it's been working happily up until today.

I'll see if I can find a Redis guru around here who can help with further debugging the "unable to get lock" issue.

**Comment by mwcz** [comment]
This might be a stupid question, but is there any risk of data loss due to the "unable to get lock" issue?  I would guess that it happens when a worker tries to process a task that's already been claimed.  I just want to be sure before I turn the log level down. ;)

**Comment by dcramer** [comment]
This error generally shouldn't happen at all. The only time it would is under a complex race condition on a high throughput system, and only by running at minimum two celerybeat processes.

You can get length of queue via:

```
redis-cli llen default
```

You can turn down logging, but this is definitely an issue you'd want to resolve.

**Comment by mwcz** [comment]
I'm not sure if this is the best solution or not, but I tuned Celery like so:

    -numprocs=8
    +numprocs=1

    -sentry celery worker -c 1 --autoscale=8,1
    +sentry celery worker -c 1

Haven't seen an 'unable to get lock' message since.  Even with 1 process and 1 thread it still seems to be handling our queue without a sweat.  I'm judging that based on seeing many events from "a few seconds ago" in the UI. 

Thanks again for your patience and help.  dcramer++ Sentry++

**Comment by mattrobenolt** [comment]
I wonder if this is related to the autoscaling somehow. I'd literally never touch that if I were you. :)

fwiw, we run using `-P ${numprocs}` instead of `-c`. `-P` uses real processes instead of threads. When doing that, you should be able to crank up how many processes are being used without an issue. I'm guessing there's possibly an issue with using threaded workers?

**Comment by dcramer** [comment]
You shouldn't with a high process count per our docs as celery has locking issues. 4-8 is ideal. 






On Wed, Feb 17, 2016 at 10:05 AM -0800, "Matt Robenolt" <notifications@github.com> wrote:












I wonder if this is related to the autoscaling somehow. I'd literally never touch that if I were you. :)



fwiw, we run using -P ${numprocs} instead of -c. -P uses real processes instead of threads. When doing that, you should be able to crank up how many processes are being used without an issue. I'm guessing there's possibly an issue with using threaded workers?

**Comment by mwcz** [comment]
The error is back today, even with only a single worker (ie `numprocs=1` and `-c 1`).  I'm kinda stumped on where to go from here.

**Comment by dcramer** [comment]
The primary things to confirm at this point:

- Version of Redis
- Length of queues are always low (llen counters-0, llen default, llen events)
- SENTRY_CACHE is setup to the Redis backend
- SENTRY_BUFFERS is setup to the Redis backend
- celery beat is running as a separate process

This warning specifically says "I got a duplicate job in the time i haven't finished processing the last job", which usually would imply the workers can't keep up with the queue. That is, it says "increment this counter in 10s", then, 10s later, it creates a job to increment it. Before it is able to actually execute that new job, the process repeats, and by the time it executes its happening for multiple jobs.

**Comment by mwcz** [comment]
`llen counters-0` is 0 the vast majority of the time, but it does go >0 on occasion.  I watched `counters-0` side by side with the celery worker log, and sure enough, the "unable to get lock" errors *always* corresponded with counters-0 going above 0.  It's not a two-way correspondence though, since counters-0 went over 0 several times with no lock contention.

Heres's [a 2m video](https://zippyy.com/share/sentry-counters-queue.webm) of what I was looking at.  You can see how counters-0 > 0 seems to cause to the lock errors sometimes, but not always.  Sorry for the long stretches of dead time in the vid... counters-0 is empty almost all the time.

counters-0 hit a max of 49 in the fifteen minutes or so that I watched.

Here's the rest of the info which all seems to be in order:

 - Redis server v=2.8.19 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=c0359e7aa3798aa2
 - I printed `llen default` and `llen events` in a loop  for a few minutes and got "(integer) 0" the whole time.  For reference the UI reports about 20 EPM now, but at our peak last year we were getting 150 (we fixed *le bugs*).
 - `SENTRY_CACHE = 'sentry.cache.redis.RedisCache'`
 - `SENTRY_BUFFER = 'sentry.buffer.redis.RedisBuffer'`

I confirmed both settings in the Sentry UI as well as conf file to rule out a wrong conf file mixup.

Here's proof of separate pids for celery beat, celery workers, and uwsgi (as managed by supervisor):

    supervisor> status
    sentry-beat                        RUNNING   pid 6135, uptime 1 day, 5:50:59
    sentry-web                         RUNNING   pid 6136, uptime 1 day, 5:50:59
    sentry-workers:sentry-workers_00   RUNNING   pid 6020, uptime 0:01:13

Just in case it's informative, here's [a screenshot](https://zippyy.com/share/sentry-queue-stats.png) of the queue stat graphs.

**Comment by dcramer** [comment]
Do you have metrics integration enabled? (its possible to get some data out of Sentry internals, but its not as full featured as statsd or datadog)

We capture things like revoked jobs and buffer size in there that might aid in understanding this.

buffer.revoked
buffer.pending-size
jobs.{name}.dispatched

**Comment by mwcz** [comment]
I didn't have metrics enabled but I'm working on it.  Will post back when I have some info.

Yeah, just one beat process.  Here's the full supervisor.d config:

    [program:sentry-web]
    user=root                     ; setuid to this UNIX account to run the program
    command=su -l sentry -c "workon sentry && uwsgi --ini /home/sentry/.sentry/uwsgi.ini"
    autostart=true                ; start at supervisord start (default: true)
    autorestart=true              ; retstart at unexpected quit (default: true)
    stopasgroup=true
    killasgroup=true
    stopsignal=INT
    stdout_logfile=/var/log/sentry/sentry-web.log
    stdout_capture_maxbytes=1MB   ; number of bytes in 'capturemode' (default 0)
    stderr_logfile=/var/log/sentry/sentry-web-error.log
    stderr_capture_maxbytes=1MB   ; number of bytes in 'capturemode' (default 0)

    [program:sentry-beat]
    user=root                     ; setuid to this UNIX account to run the program
    command=su -l sentry -c "/home/sentry/.virtualenvs/sentry/bin/sentry celery beat -l WARNING"
    killasgroup=true
    autostart=true                ; start at supervisord start (default: true)
    autorestart=true              ; retstart at unexpected quit (default: true)
    stdout_logfile=/var/log/sentry/sentry-beat.log
    stdout_capture_maxbytes=1MB   ; number of bytes in 'capturemode' (default 0)
    stderr_logfile=/var/log/sentry/sentry-beat-error.log
    stderr_capture_maxbytes=1MB   ; number of bytes in 'capturemode' (default 0)

    [program:sentry-workers]
    command=su -l sentry -c "/home/sentry/.virtualenvs/sentry/bin/sentry celery -c 1 worker -l WARNING -n worker-%(process_num)02d"
    process_name=%(program_name)s_%(process_num)02d
    numprocs=1
    numprocs_start=0
    startsecs=1
    startretries=3
    stopsignal=TERM
    stopwaitsecs=10
    stopasgroup=false
    killasgroup=true
    environment=SENTRY_CONF="/home/sentry/.sentry/sentry.conf.py"
    autostart=true                ; start at supervisord start (default: true)
    autorestart=true              ; retstart at unexpected quit (default: true)
    stdout_logfile=/var/log/sentry/sentry-workers.log
    stdout_capture_maxbytes=1MB   ; number of bytes in 'capturemode' (default 0)
    stderr_logfile=/var/log/sentry/sentry-workers-error.log
    stderr_capture_maxbytes=1MB   ; number of bytes in 'capturemode' (default 0)

**Comment by Kronuz** [comment]
Getting the same error in the logs after installing fresh new sentry server with SENTRY_CACHE and SENTRY_BUFFERS configured (which was already there in the sentry.conf.py) a single celery beat process, a single celery worker and a single uwsgi and receiving near zero events (new server).

sentry-8.1.2
redis-3.0.5_2
uwsgi-2.0.12
python27-2.7.11_1

**Comment by dcramer** [comment]
ca90532

**Comment by dcramer** [comment]
Should be resolved -- will go out in 8.2

**Comment by djova** [comment]
> Should be resolved -- will go out in 8.2

I'm also seeing a *lot* of this "unable to get lock" issue. We deployed straight off of master yesterday, version `8.2.0.dev0` and we're using redis for SENTRY_CACHE, SENTRY_RATELIMITER, SENTRY_BUFFER, SENTRY_QUOTAS, SENTRY_TSDB. 

When you merge your change we'll try it out.

**Comment by djova** [comment]
> Should be resolved -- will go out in 8.2
> I'm also seeing a lot of this "unable to get lock" issue. We deployed straight off of master yesterday, version 8.2.0.dev0 and we're using redis for SENTRY_CACHE, SENTRY_RATELIMITER, SENTRY_BUFFER, SENTRY_QUOTAS, SENTRY_TSDB.
> 
> When you merge your change we'll try it out.

Seems to be fixed now. Thanks!
