### ISSUE TITLE
Where is sentry loaddata method go?

### ISSUE THREAD

**Issue by nilroy** [getsentry/sentry#2683]
I was using sentry 8.0.1 and now upgraded to sentry 8.1.2. Where is the sentry loaddata command went? Is there another way to invoke that? Its very handy while installing sentry using configuration management tool. The action was idempotent also.

**Comment by dcramer** [comment]
It's under the django sub command. You should use the native import/export behavior instead as this won't be supported forever.

**Comment by nilroy** [comment]
@dcramer thanks for your input. However could you giuide me how to do that? There are multiple settings.py in the sentry virtualenv directory. Which one I shoud use?

**Comment by dcramer** [comment]
@nilroy I am not sure what you mean -- Sentry doesn't use a settings.py (it's very different than a Django app). There is a SENTRY_CONF dir (which used to simply be a sentry.conf.py file).

You can 'sentry django loaddata', but the other commands I was referring to are 'sentry export' and 'sentry import'

**Comment by nilroy** [comment]
@dcramer thanks for the input. I misunderstood you and I was trying to run django-admin.py. Now I am able to run the sentry django loaddata command. One final question. Does this command work in sentry 7?

**Comment by dcramer** [comment]
Yes. django-admin has never been supported. 






On Tue, Feb 16, 2016 at 12:56 AM -0800, "Nilanjan Roy" <notifications@github.com> wrote:












@dcramer thanks for the input. I misunderstood you and I was trying to run django-admin.py. Now I am able to run the sentry django loaddata command. One final question. Does this command work in sentry 7?
