### ISSUE TITLE
How to fix

### ISSUE THREAD

**Issue by nohnaimer** [getsentry/sentry#26865]
## Important Details

How are you running Sentry?

On-Premise w/ Docker, version 21.7.0.dev0

Saas (sentry.io)

Other, version x.y.z, [briefly describe your environment]

## Description

[What happened]

## Steps to Reproduce

1. [First Step]
2. [Second Step]
3. and so on.

Good items to include here include:

- Include a stacktrace or other logs when relevant - screenshot
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant - default config with added only mail block:
mail.host: 'server'
mail.port: 25
mail.from: 'sentry@domain'

### What you expected to happen

After update from 21.4.0dev0 to 21.7.0.dev0 get error:
<img width="2198" alt="Снимок экрана 2021-06-24 в 14 31 47" src="https://user-images.githubusercontent.com/8865830/123256141-4ab12280-d4f9-11eb-92c0-febe24730364.png">
Any ideas how to fix?

**Comment by chadwhitacre** [comment]
Gonna need a way better bug report to be able to help, please fill out the template instead of bypassing it.
