### ISSUE TITLE
Add ability to group projects (not by Team)

### ISSUE THREAD

**Issue by rreynier** [getsentry/sentry#2687]
Currently the only way to put our apps into groups is by leveraging the "teams".  It would be nice to have another level of organization called grouping.  

Essentially imagine having the following:

**Team 1**

Project A Staging Environment _(proposed group)_
- APP 1
- APP 2

Project A QA
- APP 1
- APP 2

Project A Production Environment _(proposed group)_
- APP 1
- APP 2

------

**Team 2**

Project X Staging Environment _(proposed group)_
- APP 5
- APP 6
- APP 7

Project X Production Environment _(proposed group)_
- APP 5
- APP 6
- APP 7

**Comment by dcramer** [comment]
Is the primary reason simply to group up environments?

**Comment by rreynier** [comment]
Essentially yah.  Some of our projects 5-6 environments: Ex: QA1, QA2, Stage1, US, Europe, AU.

**Comment by dcramer** [comment]
I can unquestionably say we won't implement another hierarchy here, but I do understand the concern with environments and we'd like to solve it.

The main issue today is representing multiple environments under a single project, and our inability to answer a few questions like:

- how often is this happening in X env (this is slightly untrue, as we can answer this)
- how often is this happen in X env on Y [other dimension, like version]
- is this primarily happening in production? (or other environment you really care about)
- is this *still* happening in production? (or other environment you really care about)

If theres some other things that click for you it'd be great to hear your feedback. The latest revision of our API spec has environment as a first class citizen, but we don't do anything with it on the server yet other than add a tag.

**Comment by rreynier** [comment]
Yah, adding another hierarchy probably isn't the right solution, but I am glad you are looking to solve this problem. To add to what you have, we need our support teams to really only pay attention to certain environments, so ideally we would have "views" or something like it that could be provided to different groups.  We wouldn't want errors out of QA or Staging causing alarms for example.

**Comment by rreynier** [comment]
I was just thinking about this some more, without keeping different environments in separate projects, how do you handle releases?  You may have release 1.5.2 on stage1 and release 1.6.0 on qa2 and 1.5.0 on production.  When marking a fix in qa2 which is on 1.6.0 they fix may not come till its next release. 

I assume you guys are more building around a model of continuous delivery?

**Comment by dcramer** [comment]
@rreynier we actually have some specs (somewhere) to associate releases with other data (e.g. i released X to env [and to device Y]).

Some of what we've done so far works well for continuous releases, and some of it doesn't work as well. We're definitely taking the slower iterative approach here as its a complex problem with a lot of use cases.

**Comment by rreynier** [comment]
Very cool.  For now we are just creating projects for each app and environment and organizing them through a specific naming scheme.  Do you have any idea how soon in the future these types of features will be released?  Are we talking a couple months or a couple years?

**Comment by dcramer** [comment]
We generally shift plans around a lot, but a lot of work we're doing right now is around making data more actionable. I would say its closer to a couple months vs a couple years, but we still don't have a fully conceptualized solution for the problem yet.

**Comment by rreynier** [comment]
Thanks David.  Look forward to it!
