### ISSUE TITLE
Support marking issues as unread

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2690]
This was brought up via a support ticket. I understand why someone might want to do this, but we don't really think of the seen status as a function, but rather an indicator to your peers. Need to decide if we want to do this as it wouldn't be overly difficult to add.

**Comment by dcramer** [comment]
To be clear, I'm referring to the UI here. We accept this in the API already.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
