### ISSUE TITLE
sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured

### ISSUE THREAD

**Issue by johnsonprabu-a** [getsentry/sentry#26917]
## Important Details

How are you running Sentry?

I am running it on k8s based on helm chart deployment (https://github.com/sentry-kubernetes/charts)

Docker image: getsentry/sentry:21.4.1

Saas (sentry.io)

Other, version x.y.z, [briefly describe your environment]

## Description

[What happened]
Sentry web pod is crashed on "[WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured."
## Steps to Reproduce

1. helm install --namespace getsentry sentry-prod --wait sentry -f sentry/values.yaml
2. kubectl -n getsentry logs -f sentry-prod-web-6688ccff58-dn2b8
07:21:23 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.

Good items to include here include:

- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration (`sentry.conf.py` and `config.yml` files) when relevant

### What you expected to happen

[What you think should be happening]

With reference to the ticket https://github.com/getsentry/sentry/issues/13967, same issue is persists on the current release also. Kindly suggest to fix it

**Comment by BYK** [comment]
We do not support or manage the helm chart so you may need to file the issue there. For your reference, here's our guide to implement geolocation: https://develop.sentry.dev/self-hosted/geolocation/
