### ISSUE TITLE
"Event Type" and "Event Type Health" Information in Group

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#2691]
We need a name for this which is probably not platform but the idea is that the group knows about what type of information is stored within it which could affect the UI and what the internal health of that group is.

In particular for instance we want to know these things:
- platform javascript: if it's an even with a stacktrace the health information is how well configured the sourcemaps are (absent, corrupted, fetched dynamically with error/without error etc.)
- platform native: if there are stacktraces the health is the status of the dsym files etc.
- platform csp: we just track that it's a csp report which can change the ui etc.

Needs more thought but generally the idea is that we can adjust the UI based on what's in the event group and and that we can have screens that will show you in general about all the unhealthy groups and how to fix them. This is particularly important with sourcemaps and dsyms.

**Comment by dcramer** [comment]
A few additional notes here:

- Event types might be Error, CSP Report, Log Message
- Both details and stream UI can change based on event type (e.g. the individual row in the stream)
- Notifications can change based on type

**Comment by dcramer** [comment]
#2673

**Comment by mitsuhiko** [comment]
One thing we might want to consider is taking the idea of downward qualified event types as we had in another proposal a while ago.  Where it's `error`, `error.java`, `error.java.spring` etc.  Then we can start customizing UI trivially that way.

**Comment by dcramer** [comment]
Yeah I def agree with that. Im thinking of this like XML namespaces:

```
{"type": "error"}
```

```
{"type": "error:javascript"}
```

```
{"type": "error:native"}
```

**Comment by dcramer** [comment]
What if, under an interface (which is effectively aliased), we allow platform overrides. That is, we can say "if the platform is javascript, we load the js exception interface here".

One alternative is at the top level we make the type be error:[type] or similar, but then how do we derive interfaces from that? It's possible that we do like:

EventType.get_interfaces() => {'exception': JSException}

I do like the idea of encapsulating this behavior in the event type, rather than per interface (since the language is global to the event, and the interface isn't). One caveat here is how do we deal with Obj-C calling JavaScript and other similar situations. We can't reasonable layout stacktraces in many situations unless they're part of the same datastructure.

**Comment by mitsuhiko** [comment]
So just a quick brain dump. Here are some scenarios I want to explore:

* for frameworks in js/native generated code i would like to be able to augment the stacktraces to clarify what some frames mean (framework routing code, react component reconciling, generated code from call from ios to swift, landing pads etc.)
* different stacktrace rendering altogether. Native in particular looks bad currently and should probably be rendered more like a table.
* different raw stacktrace rendering (currently uses project platform setting)
* certain platforms (like angular in js, react in js) might want to show props/context/scopes somewhere instead/in addition of local variables
* javascript might want to show minimized/unminimized stacktraces
* long term it would be nice to reuse some of that information for the tracing. There we used dotted paths to specifically mention frameworks so we can filter them (eg: give me all the things that django did)
* drive culprits from this on a per type basis

**Comment by mitsuhiko** [comment]
Other ones:

* we probably want to have the type also set on the stack which becomes useful as we have an interface to show different threads active. Particularly useful for iOS and later when we do unity which would have both native and c# threads.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
