### ISSUE TITLE
Notification Hub and Stored Rules

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#2695]
This is a potential follow up for #2673 

We're going over some ideas for how a notification system in Sentry can work, also in particular with future expansion and extensibility in mind. Here are some pillars we would like to work with:
- expand on the rule system but change it to be more "programmer friendly". In particular we like the idea of data dog where you can look at the underlying JSON for a rule and literally copy/paste it around if needed.  So the rule editor would be a UI for a basic JSON rule format.
- rules could be stored in a central rule list (maybe associated with the user that created it?) and users can then enable/disable those rules for their preferred notification services if they want.  Basic matrix might do it.
- the internal notification hub might be something we could design in a way that plugins can easily hook into it to listen to messages. So the slack plugin would just subscribe itself to "deliver short notification" and gets all the data needed preconfigured for short notifications. Likewise email plugins would listen to "deliver long notification" etc.  Essentially we want plugins to stop using internal interfaces and get standardized data.

**Comment by dcramer** [comment]
> rules could be stored in a central rule list (maybe associated with the user that created it?) and users can then enable/disable those rules for their preferred notification services if they want. Basic matrix might do it.

A simple way to think about this is -- if there were no major changes to the UI -- having a "subscribe to this email rule" for each mail condition.

**Comment by dcramer** [comment]
#2673

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
