### ISSUE TITLE
Add Error Event Type

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2696]
Inferred via any event which contains an exception object.

Promoted properties:
- exception.values[0].type
- exception.values[0].value
- culprit

Data changes:
- Remove message when inferred from exception.values[0]
  - Maybe remove it entirely. Is it actually useful? It should only be present in logging.error(exc_info=True) style situations.

Stream:

```
[type]: [value]
[culprit]
```

Details (and email):
- Reflect similar header as stream flow
- De-prioritize message

Subtypes will reflect languages, and might include:
- javascript
- native (native might make sense as a strongly customized type)

Refs GH-2691

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
