### ISSUE TITLE
Any built in backup strategy ?

### ISSUE THREAD

**Issue by Biegal** [getsentry/sentry#2698]
Sorry if that's stupid question, but is there any built in backup command ?
Or is backing up postgresql only enough ?
There are few 'moving pieces' like postgres, redmine, worker processes, main sentry instance, so I'm worried if I won't loose anything crucial getting only data from postgres ?

**Comment by mattrobenolt** [comment]
Most of the data you care about is in Postgres, yes.

We have a builtin tool `$ sentry export <file.json>` that can export, with a subsequent `$ sentry import <file.json>`.

This will dump all of the postgres data into JSON format.

There's other data in redis, but this is basically just driving graphs and is our time-series data. If you lose this data, it's just historical, and not possible to backfill, but new data will be just fine. Generally, this isn't that big of a deal, but if it is, you can keep backups in your redis configurations. You should have AOF and/or rdb snapshotting enabled. Sentry itself doesn't have a way to export data from redis. You could also configure redis replicas for redundancy. See: http://redis.io/topics/persistence and http://redis.io/topics/replication for more information.

**Comment by mattrobenolt** [comment]
Also, to clarify on `$ sentry {export,import}`, it's much better to still use the normal postgres backup tooling periodically, with `$ pg_dump` and friends. `$ sentry export` leaves a bit to be desired yet, and doesn't backup _everything_.

And like redis, you could maintain a postgres replica as well and perform a failover if the master were to go down, etc.

**Comment by Biegal** [comment]
Thanks for that @mattrobenolt!
I got whole picture now! Now just need to sort it out with docer, but should be all fine here:)
Maybe that's a good idea to add this to the docs ?

**Comment by intgr** [comment]
**Beware:** this information is outdated now, backup is a lot more complex now: https://github.com/getsentry/onpremise/issues/364
