### ISSUE TITLE
Revoke membership when SSO invalid

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2699]
We currently have a process that automatically marks an SSO account as invalid after a small window (~1h) if it has been suspended on the upstream provider. However, it leaves the account attached to the organization with the "SSO link missing" flag.

We should improve this process so that it removes the member entirely if the SSO account is still invalid after a longer period of time. The primary concern here is user confusion, and the fact that manual intervention would be needed to remove all records.

There's a gray area here as well, where we don't want to very aggressively remove membership in the situation where the provider (e.g. Google) reports the account as invalid, but only for a brief window of time.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
