### ISSUE TITLE
Cross-browser smoke tests

### ISSUE THREAD

**Issue by BYK** [getsentry/sentry#27009]
### Problem Statement

We want to make sure Sentry UI loads and can perform basic tasks such as logging in across all major browsers:

- Chrome
- Firefox
- Edge
- Safari

### Solution Brainstorm

We can use publicly available tools such as BrowserStack and integrate them to our Vercel preview deploys to get PR-level warnings when things break.

We can also set up per-commit or time-based regular checks for the live product.

**Comment by chadwhitacre** [comment]
Surprised we've gotten this far without this, tbh. Better late than never! :)

**Comment by ryan953** [comment]
We had some cross-browser tests in https://github.com/getsentry/smoke-test-sentry, then we turned them off because they're flakey and not catching enough problems to justify the cost.
