### ISSUE TITLE
Restarting sentry

### ISSUE THREAD

**Issue by fatagun** [getsentry/sentry#2700]
Hello,

How does one stops and restarts sentry?

Thanks.

**Comment by mitsuhiko** [comment]
Hi. This is an issue tracker and not a support forum. Please use stackoverflow for support questions.

**Comment by dcramer** [comment]
Please refer to our documentation. Sentry does not manage processes so it's up to whatever solution you setup.

**Comment by fatagun** [comment]
I am sure Bill the lizard will close the question in 2 minutes on SO. Thanks though.

**Comment by mattrobenolt** [comment]
sentry should be running in the foreground when you `sentry start`, so sending a SIGINT/SIGTERM/SIGKILL should stop it just like normal processes. But this falls in line with what any other process manager would do, like supervisord, upstart, systemd, runit, etc.

**Comment by fatagun** [comment]
Thanks. I did find a solution. Ironically it wasnt a SO question. 

https://github.com/getsentry/sentry/issues/2663

This worked.
