### ISSUE TITLE
Cumulative metrics in Sentry don't seem to be correct.

### ISSUE THREAD

**Issue by DaveLemanowicz** [getsentry/sentry#2701]
We are using Sentry and people had been complaining that errors were occurring that were not getting recorded in Sentry. I created a stand alone program:

    raven = Client('MY-SENTRY-URL')
    try:
        int('Wha!?')
    except Exception as ex:
        print('Exception: {}'.format(ex))
        raven.captureException() 

I ran it several times on feb 10th, then we installed some updates on feb 16th so I tried it again and even though I had just run the error causing program, my error was nowhere near the top of the chronological list.

I searched for the error and this is what the page for the error looked like:

![pic1](https://cloud.githubusercontent.com/assets/2996565/13123933/baf4b66e-d58c-11e5-8b8f-4940a60a9b1d.gif)

The date under the event is the most recent but under "Last seen" it says the error happened 7 days ago. Even if you take that to mean "Last seen before THIS instance" it should have been the same day 10 minutes earlier because I ran this program and caused that exception twice that day.

Also, I caused this exact error 5 times on feb 10th and twice more of feb 16th so why does "Events" say 1?

If you look at "Related Events":

![pic2](https://cloud.githubusercontent.com/assets/2996565/13124100/80e6265a-d58d-11e5-87cc-d9679e0a2b82.gif)

It appears that Sentry did capture all the events but it appears to be presenting the information in a way that is misleading. When I look at an error detail page, it appears that it happened only once and possibly quite some time ago when in actuality it is happening currently and has happened many times.

**Comment by dcramer** [comment]
I assume this is on-premise? If so you might not be running certain required processes. Many counters buffer for a short duration before they flush to the database, if, for example, the celery beat process isn't running then they will never get flushed.

I will reopen this if we provide further information which suggests improvements that need made in Sentry.

**Comment by DaveLemanowicz** [comment]
It is on premises. I will check about the required processes.
