### ISSUE TITLE
Use mkcert for yarn dev-ui

### ISSUE THREAD

**Issue by dashed** [getsentry/sentry#27030]
### Problem Statement

Use a valid certificate for `yarn dev-ui`. https://github.com/FiloSottile/mkcert

Example in action:

<img width="1300" alt="Screen Shot 2021-06-29 at 4 59 52 PM" src="https://user-images.githubusercontent.com/139499/124018784-3916c180-d9b6-11eb-9f0f-5749126d1361.png">

**Comment by BYK** [comment]
Who should we assign this to, @getsentry/productivity?

**Comment by dashed** [comment]
@BYK I think they might be the best candidate.

**Comment by armenzg** [comment]
Is this it? https://github.com/getsentry/sentry/commit/1ad13d81240ed97fe388ee55ea3eb958d63c7fb8

**Comment by billyvg** [comment]
yeah https://github.com/getsentry/sentry/pull/27158
