### ISSUE TITLE
Email issue

### ISSUE THREAD

**Issue by MiteshShah** [getsentry/sentry#2704]
We have self hosted sentry server

If we send test email from http://sentry.example.com/manage/status/mail/ its send email from sentry@example.com

But for project all emails are sent from root@localhost.

Can anyone point me here how to fix this issue.

Thanks

**Comment by mattrobenolt** [comment]
Hey @MiteshShah, it sounds like you need to configure `SERVER_EMAIL` in your `sentry.conf.py` file.

**Comment by MiteshShah** [comment]
@mattrobenolt Already configured that and killed sentry & started again 
after that  http://sentry.example.com/manage/status/mail/  start working but project still used root@localhost.

I think i'll miss something here.

**Comment by dcramer** [comment]
You likely need to configure DEFAULT_FROM_EMAIL

**Comment by vahidm** [comment]
I have the same issue, `SERVER_EMAIL` is set in the environment and when I visit /manage/status/mail/ and /manage/status/environment/ configurations are correct, but emails are still sent from root@localhost. By `SERVER_EMAIL` you mean `SENTRY_SERVER_EMAIL` or it is another setting?
