### ISSUE TITLE
constraint violation using django-auth-ldap

### ISSUE THREAD

**Issue by bibby** [getsentry/sentry#2710]
I'm trying to add ldap authentication to a sentry 8.1 docker container using [Banno/getsentry-ldap-auth](https://github.com/Banno/getsentry-ldap-auth) (ergo, CC @ChadKillingsworth) and I gave an interesting problem.

The first login works fine! The ldap user gets automatically associated with the configured default sentry organization and I'm good to go. BUT!

Subsequent logins will result in a postgres error:

    duplicate key value violates unique constraint "auth_user_username_key"
    DETAIL:  Key (username)=(Andrew Bibby) already exists.
    
    SQL: UPDATE "auth_user" SET "password" = %s, "last_login" = %s, "username" = %s, 
    "first_name" = %s, "email" = %s, "is_staff" = %s, "is_active" = %s, "is_superuser" = %s,
    "is_managed" = %s, "date_joined" = %s WHERE "auth_user"."id" = %s

This doesn't appear to be directly caused by `getsentry-ldap-auth`, but rather `django-auth-ldap` vs `sentry`.

**Comment by mattrobenolt** [comment]
I'm not sure what we can do here since both getsentry-ldap-auth and django-auth-ldap are outside our control. This isn't a problem with Sentry itself. I'd try filing the bug over for getsentry-ldap-auth first unless we can get more information here to point towards Sentry.

**Comment by bibby** [comment]
sure sure.
What is under your control is your departure from the framework, if that's what it ends up being.

**Comment by mattrobenolt** [comment]
> What is under your control is your departure from the framework, if that's what it ends up being.

I'm not sure what you mean by this. Can you clarify?

**Comment by bibby** [comment]
I was speaking of django as a whole. `django-ldap-auth` as a backend works well in version 7 of sentry. If  that backend no longer works, our organization loses sentry as an option.

**Comment by dcramer** [comment]
@bibby if you want to pay us we're happy to make LDAP work for you. Otherwise pull requests accepted. Remember, Sentry is open source, and while we love keeping it that way, we prioritize things for our customers.

**Comment by bibby** [comment]
I'll pay _all_ the monies. :)
That's ok, I have a plan now. I mistakenly thought the [ldap auth backend](https://bitbucket.org/psagers/django-auth-ldap/wiki/Home) was close to the django core, which it is not.
 
I'll likely fork that project and toss it back to Banno as the viable ldap-for-sentry.

Sorry to pester.

**Comment by bibby** [comment]
Final note on this, for future searchers.
A simple [misconfiguration](https://github.com/Banno/getsentry-ldap-auth/issues/8).

Thank you for sentry.
