### ISSUE TITLE
sentry celery worker memory leak with rabbitmq broker

### ISSUE THREAD

**Issue by kevinxuv** [getsentry/sentry#2715]
celery worker memory usage grow up after long time running, running celery worker with
`sentry celery worker -l WARNING -c 24` and 5 processes on 24 core 32g ram server, and the memory usage grow up from 5g to 14g, but it did not stop growing, is that celery worker memory leak?  is there anybody met this problem?

**Comment by dcramer** [comment]
Are you running with DEBUG on by chance?

**Comment by kevinxuv** [comment]
@dcramer No

**Comment by i5nicca** [comment]
+1

**Comment by jiehua233** [comment]
I have the same problem. I follow the [docs](https://docs.getsentry.com/on-premise/server/) and install sentry on my Aliyun ECS server, 1 core with 2G RAM. However after running the service for a while, I found my server almost down.

Server: Linux 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 14.04.2 LTS)
Sentry:  8.2.2
Postgresql: 9.3.1
Redis: 2.8.4

BTW, the redis and postgresql are hosted in another server in the same LAN, but I don't think it does any matter.

the _uptime_ show:
`
Load average: 22.01, 11.10, 5.44
`
and _smem_ show:
`
  PID User     Command                         Swap      USS      PSS      RSS 
19553 ubuntu   [Sentry] uWSGI worker          80856       12       34       84 
19552 ubuntu   [Sentry] uWSGI worker          78832       84      106      156 
19534 ubuntu   [Sentry] uWSGI maste            2528      172      198      264 
19545 ubuntu   [celery beat] celery beat      29724    33208    33741    34984 
19554 ubuntu   [celeryd: celery@localhost:    11012    55660    63630    72352 
19535 ubuntu   [celeryd: celery@localhost:   355436  1259408  1267380  1276120 
`
and _top_:
`
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
ubuntu   19535  3.4 62.1 1794060 1273520 ?     S    Mar11  40:34 [celeryd: celery@localhost:MainProcess] -active- (celery worker)  
`

**Comment by holys** [comment]
http://stackoverflow.com/questions/19925264/django-1-6-and-celery-3-0-memory-leaks

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
