### ISSUE TITLE
Add support for distinct user counts in stream graphs to API.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#2721]
This change seems like it should be reasonably straightforward.

I see two implementation options:
1. **Add a query parameter that allows changing the statistic fetched in the [`StreamGroupSerializer`](https://github.com/getsentry/sentry/blob/48d762408ccfb02d2c74e283dbbd85e4a0c8dc18/src/sentry/api/serializers/models/group.py#L144-L178).** The advantage of this approach is that it's very simple. The disadvantages are that it requires refreshing the stream to change the graph (issues may be ordered differently, making comparison difficult; also higher latency) and that it limits the ability to implement a graph that displays both statistics, which we kicked around doing in the past. (Note that this is also how it works for the time interval switch from 24H to 14D.)
2. **Return both the event and user metric series from the `StreamGroupSerializer`.** The advantages are lower latency and stable ordering when switching graph types, as well as better future proofing. The disadvantages are higher initial latency (especially if we don't show both series, this could be frustrating) and that we'd need to figure out where to include it in the API response — [the `stats` attribute](https://github.com/getsentry/sentry/blob/48d762408ccfb02d2c74e283dbbd85e4a0c8dc18/src/sentry/api/serializers/models/group.py#L174-L176) currently supports only a single key, so we'd have to either add another top-level key for this new statistic (seems a little silly) or change the return type of the `stats` attribute to be a map containing different series, labeled by some identifier (a breaking change.)

**Comment by dcramer** [comment]
@tkaemming the reason we do everything opt-in right now is because its actually fairly time consuming and expensive to request tons of data out of Redis. If we can optimize that I'd love to return them by default.

**Comment by tkaemming** [comment]
Totally get that, and I think the first option is probably the most realistic for now.

**Comment by tkaemming** [comment]
Bumped this out of 8.3 to focus on GH-2912 and GH-2911 since it won't be used in the UI yet.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
