### ISSUE TITLE
Sentry shouldn't toss out requests with invalid HTTP verbs

### ISSUE THREAD

**Issue by nateberkopec** [getsentry/sentry#2727]
Since a client can put anything as their request verb (cheers `curl -X`!), Sentry should Just Deal With It and report what the client requested. 

Current behavior: Sentry tosses out the entire `request` object when it sees an HTTP method it doesn't recognize.

Proposed behavior: Sentry should just report the HTTP method that was used, or at least should keep the rest of the request object, which includes valuable info like the URL.

**Comment by mattrobenolt** [comment]
This is definitely easy to do, but I'm unsure if the reason why were strict about it. There are lots of verbs, and people use non-standard verbs for weird things. I'm not sure it's correct that we reject the entire interface in this case. Maybe we just cap on `len()` for some sanity check?

**Comment by nateberkopec** [comment]
Seems reasonable. Here's the list ActionController accepts in Rails as an example of what legitimate HTTP verbs look like. They're pretty short:

> OPTIONS, GET, HEAD, POST, PUT, DELETE, TRACE, CONNECT, PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK, UNLOCK, VERSION-CONTROL, REPORT, CHECKOUT, CHECKIN, UNCHECKOUT, MKWORKSPACE, UPDATE, LABEL, MERGE, BASELINE-CONTROL, MKACTIVITY, ORDERPATCH, ACL, SEARCH, MKCALENDAR, and PATCH

**Comment by dcramer** [comment]
I think it's fine to make this change. We should def put some caps on what we allow, but as long as it matches what is spec'd it's ok.

**Comment by nateberkopec** [comment]
:+1: The longest valid HTTP verb is 16 characters, so a limit of 16-32 characters on this field seems good.

**Comment by dcramer** [comment]
I cant find a spec for HTTP verb/methods, but yeah I think limiting it to 32 chars, and saying it has to be ``[A-Z\-]`` is probably good. Will sort out who has time to deal w/ this.

**Comment by mattrobenolt** [comment]
Briefly looking at the nginx parser, nginx doesn't even allow a hyphen in the verb, but it does allow underscores.

Not sure it matters in our case, I'm just going to allow hyphens and underscores. It's not like this is a security issue on our end, and we are intended to catch errors. So it's possible that clients send a erronous method, and I'd rather err on the side of capturing it personally.

PR in one minute.
