### ISSUE TITLE
Unable to connect to getsentry.com

### ISSUE THREAD

**Issue by mvaled** [getsentry/sentry#2728]
We can't reach getsentry.com or docs.getsentry.com.  Neither via the browser or curl.

IPs:

```
;; ANSWER SECTION:
getsentry.com.		2946	IN	A	173.193.154.240
getsentry.com.		2946	IN	A	169.53.228.185
getsentry.com.		2946	IN	A	173.193.138.213
```

```
$ traceroute -p 443 169.53.228.185 
traceroute to 169.53.228.185 (169.53.228.185), 64 hops max
  1   192.168.64.251  0,448ms  0,265ms  0,307ms 
  2   190.92.124.129  1,096ms  1,259ms  1,193ms 
  3   *  *  * 
  4   *  *  * 
  5   *  *  * 
  6   *  *  * 
  7   *  *  * 
  8   *  *  * 
  9   *  *  * 
 10   *  *  * 
 11   *  *  * 
 12   *  *  * 
 13   *  *  * 
 14   *  *  * 
 15   *  *  * 
 16   *  *  * 
```

Our gateway can't go reach the IP.

From another server in France, curl works fine.

**Comment by mattrobenolt** [comment]
Yeah, I'm not sure what we can do here, but it's not making it anywhere near us. So it's very unlikely there's anything we can do to influence this. I'd maybe poke your ISP.

**Comment by mattrobenolt** [comment]
Also, the last IP you hopped to, the first one outside the private network, is still in Cuba. It's not even getting into the US.

**Comment by mvaled** [comment]
Nop.  I guess we try to connect directly (at least a the IP level)... Not sure how to test real routers in-between.  Yet I can connect to other sites so I guess is a new restriction somewhere and I did connect on the past.

**Comment by mattrobenolt** [comment]
It seems that SoftLayer does block traffic from Cuba. https://knowledgelayer.softlayer.com/faq/softlayer-network-wide-ip-blocking

**Comment by mvaled** [comment]
I cannot even reach that link... :(

**Comment by mattrobenolt** [comment]
> ## SoftLayer Network-wide IP Blocking

> SoftLayer implements network-wide blocking of IP addresses that originate from countries that are subject to U.S. trade and economic sanctions. Currently, these countries are Cuba, Iran, North Korea, Sudan, and Syria.  (The U.S. trade and economic sanctions for Sudan are limited to the Republic of  Sudan.  The Republic of South Sudan is not subject to these sanctions.)

> Q1: What are U.S. trade and economic sanctions?

> A1: The United States prohibits most commercial transactions and other dealings with a handful of countries for foreign policy and national security reasons.  These prohibitions – formally known as trade and economic sanctions or comprehensive embargoes – currently target Iran, Cuba, North Korea, Sudan, and Syria. 

> Q2: What data and what locations are affected by this policy?

> A2: This policy affects all SoftLayer datacenter locations and environments, and blocks access by IP addresses registered to countries subject to U.S. trade and economic sanctions, including Cuba, Iran, North Korea, Sudan and Syria. 

> Q3:  How does SoftLayer come up with the list of IP addresses to be blocked?

> A3:  To identify IP addresses associated with U.S. embargoed countries, SoftLayer references the Geo IP2 Database maintained by MaxMind (www.maxmind.com).  SoftLayer updates its IP address country mapping on a quarterly basis.

> Q4: Why does SoftLayer impose these U.S.-based export restrictions on non-U.S. customers?

> A4: As a U.S. Company, SoftLayer complies with all United States export regulations across the full scope of its worldwide operations. The company has adopted this best practice as part of its export compliance processes.

> Q5: Does this restriction apply to content that is not prohibited under U.S. sanctions and embargoes?

> A5:  No.  Please contact SoftLayer at exemptions@softlayer.com if you believe your content is not prohibited under U.S. trade and economic sanctions.

**Comment by dcramer** [comment]
Due to trade sanctions still in place between US and Cuba you'll be unable to use getsentry.com. We're going to resolve an issue w/ 'sentry upgrade' that fails if it cannot access getsentry.com, but you'll have to rely on the repository docs (in docs/) Will leave this ticket open until at least that's resolved.

**Comment by mattrobenolt** [comment]
This was done with 72580869b89d7a6874d60f06b9a3ea9abc5f4690
