### ISSUE TITLE
Add 2nd confirmation on remove account

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2729]
Add a second confirmation on the remove account flow to make them confirm yet again that they're going to be removing organizations.

**Comment by dcramer** [comment]
Might be some other possibilities for additional protection here such as notifying owners when an org/project is scheduled for removal, and having a page where they can cancel it.

**Comment by mattrobenolt** [comment]
Maybe don't allow deletion directly through the UI.

I like the idea of emailing when this event happens, but maybe we should:

* Trigger an org deletion from UI, and this just fires off a confirmation email
* Click link in email to confirm deletion. Deletion is deferred for x hours.
* Add a page to be able to abort this deletion before ETA is up.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
