### ISSUE TITLE
Increase deletion window to 24h

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2730]
At the very least on:
- team
- project
- org

**Comment by dcramer** [comment]
ETAs will become an issue here, so its probably worthwhile to:

1. Change status to PENDING_DELETION immediately
2. Add to a queue of sorts (e.g. a table) where we simply schedule jobs. Could just be (task, json payload).

**Comment by mattrobenolt** [comment]
> ETAs will become an issue here

You mean because of the way celery handles ETAs? If we had a lot of queued jobs with a super long ETA, that'd become problematic since celery memory would bloat.

I'd be +1 on throwing deletions into a table though and avoid that behavior.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
