### ISSUE TITLE
Allow long URLs in URL dropdown to wrap

### ISSUE THREAD

**Issue by rreynier** [getsentry/sentry#2731]
Currently when you go to filter by URL, you are presented a select2 dropdown.  Because URL's tend to be longer than the width of the Select 2 dropdown, it makes it impossible to know which one you are selecting.  The solution (I think) is to add `word-wrap: break-word;` to https://github.com/getsentry/sentry/blob/334d8a910fe99c4732fac70e568dda239e4e06c1/src/sentry/static/sentry/less/includes/select2.less#L302

In the meanwhile I am literally resorting to opening developer tools and looking at the full strings through inspection and/or by changing the CSS inline.

**Comment by mattrobenolt** [comment]
Adding @ckj here since he knows what CSS is.

**Comment by rreynier** [comment]
Forgot to attach screenshot:

![image](https://cloud.githubusercontent.com/assets/1953114/13689122/ca7225c8-e6e3-11e5-9a01-2b2f5320868b.png)

**Comment by dcramer** [comment]
This requires insertion of HTML tags to force the ability to wrap, but I agree we should resolve this.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by rreynier** [comment]
This is resolved anyway, since there is now a horizontal scroll bar in this drop down :+1:
