### ISSUE TITLE
Inconsistent ctrl-click/middle click (open in new tab) behaviour on sidebar & alert panels

### ISSUE THREAD

**Issue by tfh-cri** [getsentry/sentry#27360]
### Environment

SaaS (https://sentry.io/)

## sidebar
1. go to `https://sentry.io/settings/$org`
2. ctrl-click (or middle-click) any of the Help/What's New/Try Business entries at the bottom of the sidebar

## info boxes
1. go to https://sentry.io/settings/$org/billing/overview/ for an org with a 'try business' active promotion
2. ctrl-click or middle-click on the 'Learn More' or 'Start Trial' buttons in the info box 

### Expected Result

destination of those pages opens in a new tab

### Actual Result

sidebar opens a new tab but retains original page
infobox trial buttons do nothing

**Comment by markstory** [comment]
Thanks for opening this issue.

I'm not sure we can have a ctrl-click work for the sidebar, info box items. The items you listed don't have 'pages'. For example the 'help' item opens a menu, and 'try business' opens a modal window on top of the current page. We could try to have middle/ctrl-click work like a primary button click though.

**Comment by tfh-cri** [comment]
Hi, thanks for the quick followup!

Would it be practical to have it open a new window to the current view, and open the modal/take whatever action in that new tab instance? That's what I'd immediately assume would happen for non-transitioning actions when told to 'open in new tab'.

**Comment by markstory** [comment]
That is something we could explore doing. It would require including more state in the URL to get the new tab to where it needs to be.
