### ISSUE TITLE
Queue overview error

### ISSUE THREAD

**Issue by Evanion** [getsentry/sentry#2744]
I just setup a fresh install of sentry on ubuntu 14.04, and when I go to the queue overview, i get the following error: https://www.dropbox.com/s/i5fw403whm0nk0a/Screenshot%202016-02-24%2017.35.12.png?dl=0
(The top bar warning about workers not reporting have been fixed by chown /www/sentry to the sentry user)

python: 2.7
postgreSQL: 9.4.6
sentry: 8.1.2
redis: 3.0.7
 

I have installed it using the official guide:
https://docs.getsentry.com/on-premise/server/installation/

**Comment by mattrobenolt** [comment]
Do you get an error on the server? Or JavaScript errors in your console? We definitely need more information here.

**Comment by Evanion** [comment]
It seems to have to do with the requests being made over HTTP instead of HTTPS:

[blocked] The page at https://sentry.wokcraft.com/manage/queue/ was not allowed to display insecure content from http://sentry.wokcraft.com/api/0/internal/stats/?since=1456329005.946&resolution=10s&key=jobs.all.started.

The 'Root URL' is configured for HTTPS.



Sidenote:
Getting the following deprication error as well:
Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead.

**Comment by Evanion** [comment]
Seemed to be a cache issue.

**Comment by mattrobenolt** [comment]
:) Thanks. 

And fwiw, the React warning is just a warning. Unrelated.
