### ISSUE TITLE
DSN Empty after upgrade

### ISSUE THREAD

**Issue by rbudiharso** [getsentry/sentry#27492]
### Environment

self-hosted (`onpremise` deployment)

### Version

21.6.3

### Steps to Reproduce

1. Upgrade self-hosted sentry with docker-compose using `install.sh` to version 21.6.3 results in DSN empty

### Expected Result

DSN field not empty, creating new project should have DSN populated, regenerating new DSN should also have DSN populated.

### Actual Result

DSN is empty, regenerating new DSN or creating new project also result in empty DSN
![Screenshot from 2021-07-16 09-22-23](https://user-images.githubusercontent.com/43447/125882183-76e7a49e-6343-4e6f-a614-72010f2fc3f6.png)

I already set `system.internal-url-prefix: 'https://sentry.mysite.url'` like https://github.com/getsentry/sentry/issues/12813#issuecomment-489363824 suggest, but it doesn't work

**Comment by chadwhitacre** [comment]
Does a fresh install of 21.6.3 have the same problem?

What version are you upgrading from?

**Comment by BYK** [comment]
Are you sure your `system.url-prefix` config is set: https://develop.sentry.dev/config/#general
