### ISSUE TITLE
UI Bug: Rate Limit page menu also highlights Saved Searches menu option

### ISSUE THREAD

**Issue by LordMike** [getsentry/sentry#2751]
Hi,

Awesome tool - looking into it as an on-premises tool. As I was browsing around, I stumbled upon a UI bug in the active menu highlighting on a projects settings page, as shown in the picture below.

It's been tested in both IE and Chrome. The sentry installation is very new (days old) and is version `sentry (8.1.2)` installed via `pip` on Debian.

![image](https://cloud.githubusercontent.com/assets/1027111/13329382/cf5df4d6-dbf3-11e5-81b7-985a7baf428e.png)

**Comment by mattrobenolt** [comment]
doh, this should be an easy fix. :) Thanks.

**Comment by dcramer** [comment]
This is fixed in master/8.2

**Comment by LordMike** [comment]
Well damn. This issue took longer to create than the total time to fix took.

**Comment by dcramer** [comment]
@LordMike it's actually been fixed in master for a while, it probably just didn't make it into the 8.1 release :)
