### ISSUE TITLE
IntegrityError: duplicate key value violates unique constraint "sentry_organizationonboar_organiz...

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2752]
https://app.getsentry.com/sentry/sentry/issues/113622958/

```
IntegrityError: duplicate key value violates unique constraint "sentry_organizationonboar_organization_id_47e98e05cae29cf3_uniq"
DETAIL:  Key (organization_id, task)=(31693, 2) already exists.

SQL: INSERT INTO "sentry_organizationonboardingtask" ("organization_id", "user_id", "task", "status", "date_completed", "project_id", "data") VALUES (%s, %s, %s, %s, %s, %s, %s) RETURNING "sentry_organizationonboardingtask"."id"
(23 additional frame(s) were not displayed)
...
  File "sentry/db/postgres/decorators.py", line 73, in inner
    return func(self, *args, **kwargs)
  File "sentry/db/postgres/decorators.py", line 21, in inner
    return func(self, *args, **kwargs)
  File "sentry/db/postgres/decorators.py", line 95, in inner
    six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
  File "sentry/db/postgres/decorators.py", line 88, in inner
    return func(self, sql, *args, **kwargs)
  File "sentry/db/postgres/base.py", line 44, in execute
    return self.cursor.execute(sql, params)
```

**Comment by mattrobenolt** [comment]
It seems that this is a `get_or_create` call as well which doesn't need to be. Seems like you just need the same `create()` pattern here and catch the `IntegrityError`.

**Comment by quantonganh** [comment]
```
/usr/local/sentry/bin/pip show sentry
---
Name: sentry
Version: 8.4.0
Location: /usr/local/sentry/lib/python2.7/site-packages
Requires: BeautifulSoup, celery, click, cssutils, Django, django-bitfield, django-crispy-forms, django-debug-toolbar, django-paging, django-jsonfield, django-picklefield, django-recaptcha, django-social-auth, django-sudo, django-templatetag-sugar, djangorestframework, email-reply-parser, enum34, exam, hiredis, honcho, ipaddr, kombu, lxml, mock, petname, progressbar, psycopg2, pytest, pytest-django, python-dateutil, python-memcached, PyYAML, raven, redis, requests, simplejson, six, setproctitle, statsd, South, toronado, ua-parser, urllib3, uwsgi, rb
```

and we are being flooded with:

```
postgres[29238]: [3-1] ERROR:  duplicate key value violates unique constraint "sentry_organizationonboar_organization_id_47e98e05cae29cf3_uniq"
postgres[29238]: [3-2] DETAIL:  Key (organization_id, task)=(3, 5) already exists.
postgres[29238]: [3-3] STATEMENT:  INSERT INTO "sentry_organizationonboardingtask" ("organization_id", "user_id", "task", "status", "date_completed", "project_id", "data") VALUES (3, NULL, 5, 1, '2016-05-21 06:24:45.748733+00:00', 5, '{}') RETURNING "sentry_organizationonboardingtask"."id"
```

**Comment by mattrobenolt** [comment]
@quantonganh There's no harm in these logs, and this is expected behavior. We should definitely reduce the volume of them, but it's not a bug and doesn't hurt Postgres or the app. It's just the side effect of doing an `INSERT` that violates the `UNIQUE` constraint, which is faster than doing a `SELECT` + `INSERT` to check if it exists first. We're just doing a fire and forget.

**Comment by quantonganh** [comment]
@mattrobenolt The thing is it occurs on every insertion:

```
postgres[23126]: [3-1] ERROR:  duplicate key value violates unique constraint "sentry_organizationonboar_organization_id_47e98e05cae29cf3_uniq"
postgres[23126]: [3-2] DETAIL:  Key (organization_id, task)=(3, 5) already exists.
postgres[23126]: [3-3] STATEMENT:  INSERT INTO "sentry_organizationonboardingtask" ("organization_id", "user_id", "task", "status", "date_completed", "project_id", "data") VALUES (3, NULL, 5, 1, '2016-05-25 04:55:38.324203+00:00', 5, '{}') RETURNING "sentry_organizationonboardingtask"."id"
```

all the time.

**Comment by mattrobenolt** [comment]
I'm aware. :) It's still not a bug. It's just a side effect of poor logging on Postgres' side.

We're going to likely improve this with some buffers, but it'll never go away. We have other instances of this too. It's just a product of how we are using Postgres, but the application is completely graceful. It's just being logged by Postgres.

**Comment by hasegeli** [comment]
It is not poor logging.  It is very nice of Postgres that it logs errors.  The expected flow of the application shouldn't include getting errors from the database.  Many people are monitoring their logs and get annoyed by this.

Why don't you use `ON CONFLICT DO NOTHING`, or something like `INSERT INTO SELECT WHERE NOT EXISTS ()` if you want to be pre-9.5 compatible?

**Comment by mattrobenolt** [comment]
Please submit a pull request to Django so the ORM can handle these, and please backport it into the version we use.

It may be an error to the database, but it's not an error to the application since we catch this and roll back the transaction in isolation just fine. But the database doesn't know what we're doing. It just sees a failed attempt to insert a row. 

We use this pattern in lots of places within Sentry and it suits our needs well.
