### ISSUE TITLE
Missing Content-Length Header

### ISSUE THREAD

**Issue by andykent** [getsentry/sentry#2755]
I've been trying to use Sentry behind an AWS ELB. (using https://github.com/getsentry/docker-sentry)

Everything works fine when I have the ports configured as TCP listeners but when switching to HTTP listeners (needed to get SSL protocol port header support) the ELB responds with a 502 response for every request. I've spent best part of a day debugging this and found...

- Looking in the Sentry logs I can see that Sentry is responding to the requests with a 200 response as normal.
- According to [the ELB docs](http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/ts-elb-error-message.html#ts-elb-errorcodes-http502) a 502 "Indicates that the load balancer was unable to parse the response sent from a registered instance"
- I found [this document](https://media.readthedocs.org/pdf/uwsgi-docs-additions/latest/uwsgi-docs-additions.pdf) that states "If you use Amazon’s ELB (Elastic Load Balancer) in HTTP mode in front of uWSGI in HTTP mode, a valid Content-Length must be set by the backend.", the AWS docs additionally state "If the response includes a body, then your application must either set the Content-Length header to a value greater than or equal to zero, or specify Transfer- Encoding with a value set to 'chunked'."
- After checking several Sentry responses I've noticed that none of them seem to have a `Content-Length` header set.

I haven't been able to confirm that adding a correct `Content-Length` header will indeed fix the ELB issues but it's currently my best working theory.

I'm not that familiar with Python/Django/uWSGI so I'm not sure if this is a conscious decision on your part or not? I see from the changeset that you did recently switch from gunicorn to uWSGI though so possibly this is regression that crept in as part of that migration?

**Comment by mattrobenolt** [comment]
Yeah, we definitely aren't calculating a Content-Length header on the response, and I can add that in. I've had issues with things like this before. But the typical suggestion for Sentry is to still run `nginx` or something in front of the sentry processes. nginx would correct this since it'd also typically do gzipping which would modify the length anyways.

I'll keep this open though since it's a trivial fix on our side to add it.

**Comment by dcramer** [comment]
-1 on content length to fix this. We say you must run nginx in front of Sentry (or equiv). \

Computing content-length shouldn't be necessary and breaks streaming responses (which if we offer artifact downloads we might want).

**Comment by mattrobenolt** [comment]
> Computing content-length shouldn't be necessary and breaks streaming responses (which if we offer artifact downloads we might want).

That's why there's `Transfer-Encoding` header. :)

Maybe instead of doing `Content-Length`, we just always say `Transfer-Encoding: chunked`?

**Comment by andykent** [comment]
Thanks for the speedy response guys.

yeah, I'd assumed it might be related to streaming responses.

Maybe I should open an issue on [docker-sentry](https://github.com/getsentry/docker-sentry) to ship it with nginx if that is advised setup?

**Comment by mattrobenolt** [comment]
> Maybe I should open an issue on docker-sentry to ship it with nginx if that is advised setup?

This isn't 100% thought out on my end yet, but there's likely going to be a larger story here. I think my plan is we'll be shipping sentry specific containers for each of these components. Like, a `sentry-nginx`, `sentry-postgres`, `sentry-redis`, etc. That way they can be ready to go for our setup, rather than generic containers. But again, not 100% thought out for this plan yet. :)

**Comment by andykent** [comment]
ah, hmm, OK, I was thinking we were talking about running nginx inline in the same container as the sentry web process. If you are already using a top level LB like ELB or HAProxy then you likely don't want another secondary layer of containers for nginx with each proxying to a single app instance.

Also, in our scenario we are relying on AWS services such as Elasticache and RDS for the storage rather than linking to redis/postgres containers. I think this is quite a common pattern as dealing with docker persistence in production can be tricky.

**Comment by andykent** [comment]
Wow, fast work, perfect, thanks!

Really keen to try this out. Is there an easy way to get a docker image built against master? Or is a release likely anytime soon?

**Comment by mattrobenolt** [comment]
> Is there an easy way to get a docker image built against master?

Coming soon™

> Or is a release likely anytime soon?

This will be in 8.2, which will be cut March 1st. :)
