### ISSUE TITLE
cors error

### ISSUE THREAD

**Issue by peymansh71** [getsentry/sentry#27569]
### Environment

SaaS (https://sentry.io/)

### Version

5.27.3

### Steps to Reproduce

hi there 
i'm using sentry with my react projects, and i get cors error when i open console on browser
there are some solutions on troubleshooting , but none of them are for people who use SDK
any idea about problem?!

### Expected Result

not to have any error on console

### Actual Result

<img width="1297" alt="Screen Shot 1400-04-29 at 09 46 33" src="https://user-images.githubusercontent.com/46920977/126265774-7b64ddd4-626f-4d83-b546-962ca2200020.png">

**Comment by chadwhitacre** [comment]
Sorry for the trouble, @peymansh71. This sounds like #27524, so I'm closing this in favor of that one.
