### ISSUE TITLE
Event can't be showed fully and the JSON of the event can't be viewed

### ISSUE THREAD

**Issue by ueman** [getsentry/sentry#27570]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I'm really not sure what to write other than to look at the issue yourself. It's from the SDK development, so I assume that you should be able to view them.
It's this event https://sentry.io/share/issue/1db4db79b6fe40539fc0657f3cb217ec/ (or https://sentry.io/organizations/sentry-sdks/issues/2522072686/?project=5428562&query=is%3Aunresolved)

### Expected Result

No errors on the event page and being able to view the events JSON

### Actual Result

I can't view the events JSON and some errors happen on the issue page.

**Comment by ueman** [comment]
Okay, it somehow fixed itself after some time. I'll leave this open if you still want to investigate.

Otherwise, feel free to just close this issue without further action.

**Comment by chadwhitacre** [comment]
Hrm. 🤔 Let us know if it recurs, eh?
