### ISSUE TITLE
Unable to get lock

### ISSUE THREAD

**Issue by fatagun** [getsentry/sentry#2758]
Hello,

I am recieving the following log for celery workers.

$ sentry celery worker -B

Skipped process on b:k:sentry.tagvalue:7eaf8109003e5b36696cb008fb6fb3ee; unable to get lock
[2016-02-26 10:03:00,116: INFO/Worker-9] Skipped process on b:k:sentry.tagvalue:7eaf8109003e5b36696cb008fb6fb3ee; unable to get lock

I have many messages like above on the console.

Why is this happening? How can i resolve it?

Thanks..

**Comment by dcramer** [comment]
This is resolved in the upcoming 8.2 release
