### ISSUE TITLE
Ignore errors after Javascript has been edited in devtools?

### ISSUE THREAD

**Issue by dmnd** [getsentry/sentry#2763]
I'm not sure if Chrome has an API for this, but it would be nice if Sentry stopped reporting errors as soon as a user edited the Javascript or even mutated the DOM via the devtools. Errors that happen after that are not interesting but can potentially be really spammy.

**Comment by mattrobenolt** [comment]
This is likely impossible to determine.

@benvinegar can you confirm?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
