### ISSUE TITLE
_ref in Webhook payload may break other tools

### ISSUE THREAD

**Issue by mosesschwartz** [getsentry/sentry#2769]
Notification WebHook callbacks include a `_ref` key in the payload that may break other systems using Mongo. When parsed on the other end, the MongoDB libs raise an error because they expect `_ref` to mean something special. 

For example, see: https://github.com/StackStorm/st2/issues/2541

**Comment by dcramer** [comment]
This is an issue upstream. The API input endpoint should be able to handle serialization in whatever form it needs. Whether thats renaming it, or simply ignoring it. For example, if something is directly inserting it into the database, that creates a potential security risk, and you absolutely do not want that.
