### ISSUE TITLE
Cannot call sentry web api by python requests

### ISSUE THREAD

**Issue by kevinxuv** [getsentry/sentry#2774]
here is my code:
`requests.get('http://localhost/api/0/organizations/sentry/teams/',auth=(username, password))`
return 401, pls help!

**Comment by dcramer** [comment]
@kevinxuv if you're seeing a 401 it means the credentials are incorrect. Make sure you're using the correct API key and passing them correctly.

**Comment by kevinxuv** [comment]
Thanks for your reply, you are always very kind.
definitely it is the right username and password, but the same data it worked fine when I user postman.

**Comment by dcramer** [comment]
If you're receiving 401 all i can say is the credentials are wrong:

- username should be the API key
- password should be an empty string

You can confirm here:

https://docs.getsentry.com/hosted/api/auth/

The only alternative is the endpoint you're requesting doesn't expose itself with the credentials you're providing.

**Comment by kevinxuv** [comment]
@dcramer I got it , and it works fine, I did not get the doc mean before, thanks a lot!
