### ISSUE TITLE
Improve "Test Configuration" sample event

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2778]
Right now, clicking on Test Configuration for a notification plugin works by triggering a sample event.

This is faulty for a few reasons:
- If done multiple times, this event will group, causing a notification to likely not get sent anyways.
- It's confusing for the team when someone triggers this. It's not obvious where the event came from.

My proposal is that the event should be unique enough to not get grouped, and we surface information into the fake event that says "Triggered by <so and so>" or something like that, and possibly a description inside the Message saying this was a test, etc.

**Comment by paularmstrong** [comment]
:+1: for *Triggered by*

Would also be good to have a little asterisk next to the *Test Configuration* button that let's the user know that a sample error will be created.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
