### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2781]
An new event [Interface](https://docs.getsentry.com/hosted/clientdev/interfaces/) that provides additional context about application events that occurred before the error was thrown. We are calling these events "breadcrumbs" to distinguish them clearly from higher-level error event itself.

Example "breadcrumb" events:

- HTTP requests with metadata (e.g. response status code, request method)
- navigation events (e.g. changing between menus in a video game UI, or a URL change in a web application)
- log statements
- UI events (e.g. user clicked coordinates X, Y)

**Goals**

- breadcrumb events are platform agnostic – i.e. they *should* be useful by both web applications, mobile applications, games, servers, etc
- dedicated interface in the event UI

**Comment by mitsuhiko** [comment]
There is an old branch for this which imlements this. feature/breadcrumbs i think

**Comment by mitsuhiko** [comment]
https://github.com/getsentry/sentry/commits/feature/breadcrumbs

**Comment by mattrobenolt** [comment]
@benvinegar Can this be closed? Or was there more work left?
