### ISSUE TITLE
Better graphs/sparklines

### ISSUE THREAD

**Issue by ckj** [getsentry/sentry#2782]
Would like to do something like this for the org dashboard:

<img width="298" alt="screen shot 2016-03-01 at 6 47 52 pm" src="https://cloud.githubusercontent.com/assets/30713/13450101/af44e6c2-dfe6-11e5-9493-aeb31c0143f2.png">

@tkaemming gonna assign this to you per our slack convo.

**Comment by tkaemming** [comment]
@benvinegar: FYI, GH-2820 solves an issue with the way project statistics are currently displayed on the project list that will presumably affect sparklines as well unless you've already changed the behavior.

**Comment by benvinegar** [comment]
So – sparklines that more or less look like this pic are in the app. But they're currently all blue.

Do we want to use red, grey, etc depending on the event count? And what's a good way of assessing whether an event count is "bad"?

cc @dcramer
