### ISSUE TITLE
Org Dashboard

### ISSUE THREAD

**Issue by ckj** [getsentry/sentry#2783]
Didn't see an issue for this yet. Here's a slightly outdated screencap:

<img width="626" alt="screen shot 2016-03-01 at 7 56 00 pm" src="https://cloud.githubusercontent.com/assets/30713/13450195/abc8401a-dfe7-11e5-8bb3-f46619e87452.png">

We need to figure out what we want to make available here, as well come up with a new design for activity. 
- [ ] What do we show here for launch?
- [ ] Better activity design
- [ ] Prerequisite?: https://github.com/getsentry/sentry/issues/2782

**Comment by benvinegar** [comment]
I kind of miss this view. Closing though since we launched it, then removed it.
