### ISSUE TITLE
Allow "Enhanced Privacy" configuration to be overridden per-project

### ISSUE THREAD

**Issue by jamesob** [getsentry/sentry#2786]
![img](http://i.imgur.com/mQuJHDp.png)

In our organization, one of the main systems (i.e. projects) has sensitive information, so we've enabled "Enhanced Privacy" org-wide to ensure that we don't leak stacktraces email for that particular system. But the majority of our projects _aren't_ sensitive, and there's high utility in having stacktraces delivered to email for those systems.

"Enhanced Privacy" only seems configurable at the org-level; is there any reason we shouldn't offer the ability to override that configuration per project?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
