### ISSUE TITLE
Cleanup task shows progress bar on stderr

### ISSUE THREAD

**Issue by do3cc** [getsentry/sentry#2794]
This makes silencing the cleanup task for cron consumption dangerous, because I would have to ignore real errors too.
For sentry 7 I posted a similar issue in the past, #1798 so you might have a Déjà vu
I didn't reopen that other issue, because this time it is probably caused by something else.

**Comment by mattrobenolt** [comment]
@do3cc Do you mean when calling `sentry cleanup` or something else?

**Comment by dcramer** [comment]
The referenced code is in cleanup_unused_files in the cleanup task

**Comment by do3cc** [comment]
@mattrobenolt exactly, sentry cleanup

I am analysing and will provide a PR
Intermediate result:
https://github.com/niltonvolpato/python-progressbar/issues/51
