### ISSUE TITLE
User count incorrect after merging events

### ISSUE THREAD

**Issue by dmnd** [getsentry/sentry#2804]
After I manually merge events, the user count doesn't update. For example, these two screenshots are from the same event:

![image](https://cloud.githubusercontent.com/assets/4427/13533723/8c3a7fc8-e1e6-11e5-9065-481ab74d0225.png)

![image](https://cloud.githubusercontent.com/assets/4427/13533714/84d659e6-e1e6-11e5-8da2-f9c5f98b7ece.png)

This is annoying because the user count is a good way to prioritize getting errors fixed.

**Comment by dmnd** [comment]
This bug breaks one of the big attractions of using Sentry's UI — rich error-specific information. Others on my team want to stop using Sentry to manage issues and just have them piped into Jira. Quick access to the users count from the dashboard is a reason to stick with Sentry's UI, but it's hard to make that argument when it's buggy.

**Comment by dmnd** [comment]
It looks like `user_count` is just missing from the merge task: https://github.com/getsentry/sentry/blob/master/src/sentry/tasks/merge.py#L70

**Comment by mattrobenolt** [comment]
@dmnd It's not user_count persay, that value is derived from `GroupTagKey`. `GroupTagKey` is getting reassigned to the right group_id, but it doesn't merge the `values_seen` on it.

Should be a relatively easy fix.

**Comment by dmnd** [comment]
Thanks @mattrobenolt! <3

**Comment by mattrobenolt** [comment]
Turns out, the patch for this was bad and had to be reverted. Gonna try this again.
