### ISSUE TITLE
Sanic automatic performance monitoring supported?

### ISSUE THREAD

**Issue by sharathpuranik** [getsentry/sentry#28065]
### Environment

self-hosted (`onpremise` deployment)

### Version

21.8.0.dev0

### Steps to Reproduce

1) Integrate issue monitoring in Sanic
2) Enable performance monitoring via traces_sample_rate set > 0
    1) Start testing with sample_rate set to 1
    2) Test with different sample_rate to check

### Expected Result

API performance details are expected in the sentry dashboard.
Issues are being tracked successfully.

### Actual Result

The performance page for the project is completely empty.

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/70695456/129445414-949ef387-cee5-4261-a2a2-b6e62dd6b6f7.png">

If Sanic framework is supported with automatic performance monitoring, any suggestions on how we can achieve the same?

**Comment by chadwhitacre** [comment]
@sharathpuranik Can you log events into your self-hosted sentry from _any_ framework? You've described a pretty broad surface area, will need to narrow down to find the root of your problem.
