### ISSUE TITLE
Don't let one bad frame spoil the whole stacktrace

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2808]
Right now, if there's one bad frame inside of full stacktrace, we reject the entire Stacktrace with a bit of a confusing error.

We should either ignore this frame and continue on, or fabricate one with `"module": "<unknown>"` just so the idea that a frame _was_ there isn't lost.

**Comment by mattrobenolt** [comment]
Another possibility would be to introduce a new interface type, `InvalidFrame` that served as a token which we could better represent in the UI.

**Comment by mattrobenolt** [comment]
After attempting this with an InvalidFrame marker, learned this was a bad idea.

Instead, we're going to opt to catch the validation error inside Stacktrace interface, annotate the error with useful information, then rethrow.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
