### ISSUE TITLE
Clarify sourcemapping error messages

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry#28085]
### Steps to Reproduce

1. Be a customer trying to set up sourcemaps.
2. Mess up one of the steps and get an error in your event.
3. Have questions because the error messages aren't always all that clear or specific.

### Expected Result

Error messages ideally should tell customers exactly what went wrong, in a clear and unambiguous way.

### Actual Result

They don't always.

----------

This is a tracking issue for work stemming from my hackweek 2021 project (which was to improve sourcemap error messaging in the UI).

PRs tracked here will fall into three categories:

1) Make the code easier to understand. I've spent many hours, on and off over the course of a number of years now, digging into this code in order to try to debug various customers' sourcemapping problems. As part of this project, I 10x-ed that effort, in order to thoroughly understand the _entire_ process, line by line. In hopes that whoever comes after me can reap the benefit of all of that work, I'm going to push a number of refactoring/clarifying changes before making any behavioral changes. (This should also hopefully make it easier to review said behavioral changes.)

2) Small logic tweaks (not all error-focused) where I noticed things being done in inconsistent and/or redundant ways.

3) Changes to error messaging (and changes to support those changes). In some cases, making the errors better means getting more information (or different information) than we're currently getting, which makes improving error messaging more than just a matter of changing the text.

Because I recognize that this is a critical code path, I want all of the work here to be as easy to review as possible, so I'm going to spread the this out over a number of different PRs, aiming to keep each as small and tightly-focused as I can. (I'm probably going to go overboard on this score. Apologies in advance.)

PRs:
https://github.com/getsentry/sentry/pull/28086

**Comment by mydea** [comment]
**Why was this issue closed?**

This issue hasn't been touched recently and no longer seems relevant. 
Hence, we're closing it to maintain a clean and transparent backlog.

Please feel free to leave a comment if you think this issue should be reopened.
