### ISSUE TITLE
Add internal queue monitoring

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2809]
Specifically we want to capture the size of each queue.

We'll need a gauge type in tsdb to handle this, as well as some service running (either as its own process, or part of an existing) which captures the stats routinely. This service may also be able to replace Celerybeat.
- [x] Display in UI when backlogged GH-2867
- [x] CLI tooling to fetch queue sizes GH-2844
- [x] Update docs GH-2944
- [ ] Internally track and graph size over time

**Comment by mattrobenolt** [comment]
@dcramer Care to elaborate on how something like this could replace celery beat? I was hoping the first pass would be to give it a dedicated queue and just celery beat it every minute. Then we track the results. I think we can expand on this later after this is working. I'm unsure of the immediate value to try and replace that entirely unless I'm missing some other better reason.

**Comment by dcramer** [comment]
We can't rely on the queue to monitor the queue. A distinct queue doesn't guarantee workers won't block for an extended period of time before the tasks are run. Most of our celerybeat usage is fixed window jobs which fire other jobs which is why I said it could potentially replace that.

**Comment by mattrobenolt** [comment]
> We can't rely on the queue to monitor the queue.

Oh, right. :)

**Comment by mattrobenolt** [comment]
@dcramer So Celery beat has this thing `CELERYBEAT_SCHEDULE_FILENAME` which is a file that persists the last runs of tasks. This way when you say "run every 5 minutes", it'll continue to do every 5 minutes through restarts.

I'd rather ditch this and work on clock schedules. I'd rather define jobs crontab style, and we always just leverage the clock time instead of needing to persist to disk.

Do you have an opinion about this?

**Comment by dcramer** [comment]
@mattrobenolt my opinion is it works fine today and theres little value in changing it (also see the PR for ScheduledJob)

**Comment by mattrobenolt** [comment]
Well, my reasoning is that if I'm replacing celery beat with our own cron-like utility, it's more work to have to replace that too. I also don't see the value in it when we can just schedule based on wall clock time instead.

**Comment by mattrobenolt** [comment]
(Linking this here for reference: https://github.com/getsentry/sentry/pull/2743)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
