### ISSUE TITLE
New release hook: error not properly converted to JSON

### ISSUE THREAD

**Issue by NotSqrt** [getsentry/sentry#2814]
Hi,

When using the hook `/api/hooks/release/builtin/` to submit a new release, I get an error 400, with a response containing only the text `"detail"`

The actual exception is `ApiError: status=400 body={'detail': 'Release with version already exists'}`, when executing the code of the view.

Relevant code:
https://github.com/getsentry/sentry/blob/8.2.2/src/sentry/web/frontend/release_webhook.py#L62

Can you fix the body of the response ?

Thanks !

**Comment by mattrobenolt** [comment]
I'll get this fixed up.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
