### ISSUE TITLE
Centralize file storage configuration

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2819]
We should have one global option, something like `system.file-dir`. This directory will act as a parent directory for any other subsystem that needs to store data on the filesystem.

Off the top of my head, the two options we now have are for file uploads, which is `SENTRY_FILESTORE_DIR` and what @mitsuhiko just added for dsyms, `dsym.cache-path`.

We should introduce a new option, and these systems can then just do `path.join(options.get('system.file-dir'), 'dsym-cache'))`, etc.

This way there's only one option a user has to configure, and we can easily add more storages without them needing to configure yet another location.

**Comment by mitsuhiko** [comment]
I just want to leave my opinion on record here that I think it should still be possible to override the paths. Eg. The dsym.cache-path if not set is a subfolder of system.file-dir but if configured, overrides the default.

**Comment by mattrobenolt** [comment]
What's the value in being able to do that? In what scenario would someone want to have storages in entirely different locations without sharing the parent? It's easy to mount drives to a subdirectory.

I can't think of any large system that requires configuring multiple directories like that.

I'm open to this, I'm just not sure there's value in adding that complexity.

**Comment by dcramer** [comment]
Storage needs to be capable of living in diff roots. Join is fine as it allows absolute paths. 






On Tue, Mar 8, 2016 at 3:31 PM -0800, "Matt Robenolt" <notifications@github.com> wrote:












What's the value in being able to do that? In what scenario would someone want to have storages in entirely different locations without sharing the parent? It's easy to mount drives to a subdirectory.



I can't think of any large system that requires configuring multiple directories like that.



I'm open to this, I'm just not sure there's value in adding that complexity.

**Comment by mattrobenolt** [comment]
> Storage needs to be capable of living in diff roots. Join is fine as it allows absolute paths.

This is what I'm asking about. :) What would be the reason someone would want that? This just makes it now N configuration options, as opposed to just 1. One for each different storage system.

**Comment by dcramer** [comment]
Because I might want file store to live in temp or I might already have mounts setup a specific way. 






On Tue, Mar 8, 2016 at 3:34 PM -0800, "Matt Robenolt" <notifications@github.com> wrote:













Storage needs to be capable of living in diff roots. Join is fine as it allows absolute paths.




This is what I'm asking about. :) What would be the reason someone would want that? This just makes it now N configuration options, as opposed to just 1. One for each different storage system.

**Comment by mitsuhiko** [comment]
I know you could have a mount under the path or have symlinks, but i just generally prefer being able to point things to completely different locations.

**Comment by mattrobenolt** [comment]
`¯\_(ツ)_/¯`

Ok. I will agree to disagree. I don't have a strong enough argument, I just personally don't like it and don't think the extra complexity is valuable here.

But we can keep them all individual config options if others have stronger opinions.

**Comment by mandeepbal** [comment]
Could you switch the storage backend to be S3?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by BYK** [comment]
Btw I think this is done now with the `config.yml` file.
