### ISSUE TITLE
Request: Related Events search more fields

### ISSUE THREAD

**Issue by mwcz** [getsentry/sentry#2821]
Currently, the search field under "Related Events" only searches the message field.  I haven't found this particularly useful because the messages in a particular event are usually exactly the same, so using the search field results in either "here is every single error" or "no results".  

It would be extremely useful if the Related Events search could also filter by the following fields which are displayed in the Related Events table along with the message:

 - Browser
 - Device
 - Level
 - Logger
 - OS
 - Project
 - URL
 - User

Thanks for all your amazing work on Sentry.  The new UI is fantastic!

**Comment by dcramer** [comment]
In 8.2 we added "EventTag" on the backend, which gives us enough data to provide the tag-based event search. I don't know when we'll get around to implement the expanded search here, but it's definitely something we're planning to do.

**Comment by mwcz** [comment]
:+1:  I had a feeling you guys were on it already. :)
