### ISSUE TITLE
raven-js reports URL that doesn't match Allowed Domains

### ISSUE THREAD

**Issue by mwcz** [getsentry/sentry#2822]
I'm seeing a weird case where Sentry is accepting events that thought should be rejected.

In my project, Allowed Domains is set to `*.redhat.com`.  And yet, I occasionally see errors where the URL doesn't match that pattern, like so:

![screenshot from 2016-03-09 11-14-16](https://cloud.githubusercontent.com/assets/364615/13641889/431c992e-e5e8-11e5-9cf1-db65554266fe.png)

Have I misunderstood how the Allowed Domains setting works?

**Comment by dcramer** [comment]
He summary is we look at the stacktrace for the whitelist and the URL is pulled from the document location. Does the stacktrace (top frame iirc) map up to the correct domain?

**Comment by mwcz** [comment]
Yeah, the top of the stack trace does match Allowed Domains, so that explains that.  However the text in Sentry just above Allowed Domains says "This will restrict requests based on the Origin and Referer headers." hence my confusion.

**Comment by mwcz** [comment]
The context appears to be that someone saved one of our pages into the podio service, and when they view it, it spews errors back at us because so much environmental stuff is missing.  Kinda like "Save As / Web Page (complete)" and viewing via file:// URL.  I assumed those types of errors wouldn't make it into Sentry because of the Allowed Domains setting, but if it's based on the top stack frame then my assumption was definitely wrong.

Luckily I have a very thin nodejs proxy sitting in front of Sentry, in which I can block bad Origins.

**Comment by dcramer** [comment]
Ah sorry, I mistakenly was thinking you meant the whitelist. If this JavaScript, Allowed Domains will definitely restrict where you can report events from, but it won't affect various other things. I'd have to check, but there's a good chance that file:// don't actually report headers, though I thought we would block it by default.

**Comment by mwcz** [comment]
There is no file:// request at work here, I just used that as a weak comparison.  One of our pages was saved under another domain and errors are getting through, even though the URL doesn't match the string in Allowed Domains.

In the thin proxy I mentioned, that sits in front of Sentry, I wound up reaching into the `sentry_data` URL param and blacklisting any incoming request where `sentry_data.request.url` didn't match *.redhat.com.  That seems to have worked, which may suggest that Allowed Domains is behaving perfectly well, but the Referer and Origin headers actually do, somehow, match *.redhat.com even though they're being served from a different domain.

**Comment by dcramer** [comment]
That's very odd. It's possible its happening via an iframe/frame. Were you able to at least confirm that Referer/Origin actually were set to *.redhat.com in the request?

**Comment by mwcz** [comment]
Origin *did* match *.redhat.com, so you're right, it must be an iframe.  I don't think there's any other way for Origin to be set as such.  But if that's the case, I wonder how raven-js wound up reporting the URL to be `files.podio.com`...

**Comment by dcramer** [comment]
@benvinegar can probably provide inside in how cross channel works, as I'm definitely not an expert there.

You might consider enabling X-Frame-Options on the website if you know it shouldnt ever be served like that:

https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options

**Comment by dcramer** [comment]
Going to close this out since it seems its not really an issue with Sentry (or anything we can address).
