### ISSUE TITLE
Question: Offline clients

### ISSUE THREAD

**Issue by fatagun** [getsentry/sentry#2823]
Hello,

How does sentry works with offline clients? ie: a mobile client with no internet access or limited internet.

Same for smart client apps.
I imagine this is related to raven but wanted to ask. 

Thanks.

**Comment by mitsuhiko** [comment]
You could buffer it up and then submit it.  That said, if the data is too old (going back a few days) then the sampling algorithm might throw away the data.  Can you clarify a bit what sort of usage pattern you have in mind?

**Comment by fatagun** [comment]
Sure. Thanks for quick response. I am managing sentry for a company who sells EHR (Electronic Health Record Systems) to doctors. It is a windows desktop app. Doctors install it and go out of office, so sometimes they don't have internet access but they still use the app. Company have no idea what is going on with their app during this duration. When doctors go online, is there a way to push the events to sentry ?

Thanks.

**Comment by mitsuhiko** [comment]
This very much depends on what type of client you have.  Generally though it should be straightforward to have the client dump out json files onto the file system and then submit that to the submission api when the internet becomes available. However clients currently do not feature this.

This would probably require some more details about what your client environment is. But yeah, what you have in mind is possible with the current protocol.  I will close this issue as a result.  If you have any questions about this or need assistance, feel free to get in contact with me.
