### ISSUE TITLE
Allow users to change avatars

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2829]
We can probably use the File infrastructure here. Should be easy enough to plug into LDAP systems where people already have avatars available.

**Comment by bsergean** [comment]
Here's how to retrieve user pictures with Atlassian products, from Confluence. A REST API can retrieve the url to a picture. Not sure how this could be used, just sharing.

https://answers.atlassian.com/questions/68791/can-i-remotely-access-profile-pictures-for-display-outside-of-confluence

**Comment by mattrobenolt** [comment]
This has been done for a while now.
