### ISSUE TITLE
Error when importing "export" file.

### ISSUE THREAD

**Issue by dts** [getsentry/sentry#2836]
Trying to migrate from one server to another, and I'm having some troubles.  I want to `sentry import` a successfully exported file.  However, doing this with a fresh postgres DB whines about tables not being there, but after `sentry upgrade`, it won't import it because it would overwrite the `sentry` project.  Not sure how to proceed, or if this is even a reasonable place to ask this question...

**Comment by dcramer** [comment]
@dts you could truncate the tables, but we likely need to resolve this by giving the abiliy to overwrite data w/ import

**Comment by dts** [comment]
I'd rather have an option "don't overwrite existing things but keep on truckin'".  Both would be useful.  How do you recommend truncating the tables? Is there some description of what I can do inside `sentry shell` or `sentry django shell`?

**Comment by dcramer** [comment]
@dts you can truncate tables via normal SQL. Its likely you simply only need to remove the project.

**Comment by dts** [comment]
Unfortunately, this strategy did not work.  I was able to get it kinda working by changing the private/public keys using SQL, but now it accepts events but I cannot look at the events' details... it's claiming a 404.  I'm just going to have to redeploy the app with a new DSN.

**Comment by dcramer** [comment]
If you're getting a 404 it sounds like membership or URLs are wrong, or the event does not exist in the new system.

**Comment by sammerry** [comment]
Running into this issue as well, I'm trying to migrate from raw aws instances into kubernetes. I'd like to simply dump users and projects leaving exception history behind, but import is throwing exceptions. I've been able to get it partially working by excluding almost every model except the projects, but i'm not sure if this is going to cause problems later.

```
sentry --config /etc/sentry export  --exclude savedsearch,rule,permission,migrationhistory,contenttype,option,site,userip,useroption,projectoption,counter,organizationmemberteam,organizationmember,team,organizationoption,projectteam,authenticator,organization,projectbookmark
```

It looks like cleaning history and using pg_dump is the best option but there's a lot of cruft I'd like to leave behind.

**Comment by RootLUG** [comment]
Same issue here. I'm migrating sentry from sqlite to postgres. After doing upgrade to init the database structure and then doing import, sentry complains with messages such as:
```
django.db.utils.IntegrityError: IntegrityError('duplicate key value violates unique constraint "django_content_type_app_label_model_key"\nDETAIL:  Key (app_label, model)=(sentry, projectdsymfile) already exists.\n',)
SQL: UPDATE "django_content_type" SET "name" = %s, "app_label" = %s, "model" = %s WHERE "django_content_type"."id" = %s
```
I tried to also truncate table "django_content_type" prior to export but I still receive this same error even after truncating. I only care about migrating users & projects (too costly to onboard it again and change configs on already deployed live projects) and would be fine to start with events from scratch.

**Comment by residentsummer** [comment]
Importing the file to migrate projects and users proved to be very error-prone. Had to manually edit it multiple times to remove irrelevant objects which caused conflicts. But even after "successful" import, there were a lot of problems on saving various settings.  For example, when changing user's role:

```
IntegrityError: IntegrityError('duplicate key value violates unique constraint "sentry_organizationmember_teams_pkey"\nDETAIL:  Key (id)=(1) already exists.\n',)
SQL: INSERT INTO "sentry_organizationmember_teams" ("team_id", "organizationmember_id", "is_active") VALUES (%s, %s, %s), (%s, %s, %s)
```

Similar errors for other changes. To fix the issue in case of postgresql storage, do the following:

1. Generate sql commands to reset sequence numbers:

    ```
    sentry django sqlsequencereset sentry > sentry_pkfix.psql
    ```
2. Execute them via psql:

    ```
    psql -d sentry -U <sentry_user> -f sentry_pkfix.psql
    ```

Maybe it should be included in `sentry repair`...

**Comment by taina0407** [comment]
I'm having this issue too, is there any updates or workaround ?

**Comment by saschanos** [comment]
Same issue here.

**Comment by saschanos** [comment]
@BYK, is there any news?

**Comment by ilya-lesikov** [comment]
This is what worked for me:
```bash
# Export
SENTRY_LOG_LEVEL=CRITICAL sentry export --exclude=contenttype,permission > /backup.json

# Import
sentry import /backup.json
sentry django sqlsequencereset sentry > sentry_pkfix.psql
psql -d sentry -U <sentry_user> -f sentry_pkfix.psql
```

If there are more "duplicate key value violates unique constraint" errors during `sentry import` then you might need to exclude more models, as specified here: https://github.com/getsentry/sentry/issues/2836#issuecomment-361266152

**Comment by BYK** [comment]
We have identified multiple issues with the `export`/`import` flow and are actively working on improving these.

One patch landed a few days ago: #23957 and more on the way for issues like #23843 and getsentry/onpremise#863

**Comment by BYK** [comment]
For everyone following this thread, we've merged 2 important patches yesterday and #24471 is the final piece that should make the backup/restore experience much smoother.

Please try these improved/fixed versions and share any feedback you have about them. You can use the nightly images for testing.

**Comment by BYK** [comment]
Alright, I've just verified locally that I can export, do a fresh install and then import that data properly. I've also tried importing an old, somewhat malformed backup file which also worked.

So I'm closing this issue. Please do report any more potential issues you may encounter and we'll be more than happy to fix them.

**Comment by lucky4ever2** [comment]
I also had problems with the restore. With the Nightly Bulid, the restore runs with exit code 0!
