### ISSUE TITLE
JS eval() Frames cause Processing Errors

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#2837]
Currently if you have `eval()` in use in a javascript app we will show a fetch error on the top.  Instead of doing that I would suggest we detect this case, do not attempt to fetch sourcemaps for it.  We can instead show a hint on the stacktrace that it could be improved by switching away from eval().

This came up a few times with users in support and they are quite surprised by this behavior. It appears this got worse recently due to browser or library changes.

**Comment by benvinegar** [comment]
This is still affecting users – going to prioritize this.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
