### ISSUE TITLE
Early Adopters: Change Alerts 📈

### ISSUE THREAD

**Issue by adhiraj** [getsentry/sentry#28404]
## Problem

Users want to know if there's a sudden spike in an issue or metric. This class of problems is common but Sentry cannot tell you about it today.

## Solution Brainstorm

Allow alerting when the value of a metric is more than X% above/below its previous value(s). We're looking at 2 types of previous values:
1. In the recent past, e.g. comparing to 5-10 mins to detect sudden spikes
2. Further out, e.g. comparing to a week ago to help detect changes in seasonal, predictable metrics like traffic to your app

## Feedback
We're currently developing this feature. If you're interested in early access, please leave a reaction/comment below and/or email workflow-feedback@sentry.io.

**Comment by CyberFlameGO** [comment]
Yeah I'm interested in early access

**Comment by scttcper** [comment]
Change alerts has been launched as a part of our business plan and enabled by default in self-hosted.
