### ISSUE TITLE
Sentry cleanup never finishes

### ISSUE THREAD

**Issue by danp60** [getsentry/sentry#2852]
We're seeing an issue with the `sentry cleanup` command which causes it to never finish during the `Removing expired values for EventMapping` phase. I think the issue is with this line https://github.com/getsentry/sentry/blob/master/src/sentry/db/deletion.py#L56. We have basically have a never ending stream of events coming in, so the rowcount never reaches 0. Each time the delete query completes, `now()` has advanced a little and more rows become eligible for deletion.

I think the fix could be to change the line to something like:

``` python
results = cursor.rowcount == chunk_size
```

so that once we reach the tail end of events we can stop, or to materialize `now()` in the where condition to guarantee there is a fixed number of rows we are going to process in the current run.

**Comment by dcramer** [comment]
That makes sense, and tbh I'm surprised we haven't seen this issue ourselves. We definitely should precompute now in these queries, which isn't an overly hard thing to fix.

**Comment by fisherking** [comment]
I think, this issue is not actual, because since version 8.13.0 **now** in where clause is precomputed

**Comment by hieast** [comment]
maybe it's just too much event.
I have 100m event waiting for delete. and it's quite slow.
I add log in `_continuous_query` and i can see it's working.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
