### ISSUE TITLE
Default to 'identicon' instead of 'mystery man' for gravatar

### ISSUE THREAD

**Issue by josefsabl** [getsentry/sentry#2856]
Our sentry is riddled with issues assigned to mystery men. As sentry usually only shows avatar and not username it is pretty uncomfortable to find out who is who.

http://screenpresso.com/=PqQee

I know that we can all set our avatars. But it feels pretty strange to nag all our users, contractors etc. to "please set your gravatar for your business e-mail address".

Also note that mystery man icon is somewhat similar to "not-assigned" icon that sentry uses. It happened to me more than once that I thought the issue is not assigned and it was assigned to person without gravatar.

I think that defaulting to identicon would solve this issue. Maybe as an option in settings?

Related: https://github.com/getsentry/sentry/pull/2631

**Comment by mattrobenolt** [comment]
@ckj @dcramer thoughts? I'm not opposed to this, but I don't have a strong opinion. I can see a bunch of mystery men being annoying. :)

**Comment by ckj** [comment]
I'd like to get away from the mystery men for sure. I personally like the Dropbox/Asana style initials approach (http://cl.ly/392V2Z1g3s1t) as identicons don't offer much more than variety IMO.
