### ISSUE TITLE
Open Redirect Vulnerability

### ISSUE THREAD

**Issue by TheAschr** [getsentry/sentry#28579]
### Environment

self-hosted (`onpremise` deployment)

### Version

21.8.0

### Steps to Reproduce

1. Deploy on-prem sentry
2. Link a user to the deployed sentry instance at https://HOSTNAME:9000%252F@b.xy/ replacing HOSTNAME as appropriate
3. User gets redirected to http://b.xy/
4. Setup a website on "b.xy" that looks like Sentry with a username/password login
5. User enters their sentry username password into malicious site compromising their account

https://cwe.mitre.org/data/definitions/601.html

### Expected Result

Should not redirect user to malicious site.

### Actual Result

User gets redirected to malicious site.

**Comment by BYK** [comment]
Are you sure this is an open-redirect issue? I tried this in my browser and it simply works for any site (including google.com). Looks like expected browser behavior to me.

**Comment by TheAschr** [comment]
I think you are right. I am waiting to hear back if [acunetix](https://www.acunetix.com/) is giving a false positive:

![bitrix](https://user-images.githubusercontent.com/10580515/133334133-ff06ed56-ffe2-4e84-b79e-2ceccba85b7c.png)

**Comment by BYK** [comment]
I don't think this is valid at all so closing:

```shell
curl -v -L 'https://try.sentry-demo.com%252F@b.xy'
* Rebuilt URL to: https://try.sentry-demo.com%252F@b.xy/
* Could not resolve host: b.xy
* Closing connection 0
curl: (6) Could not resolve host: b.xy
```
