### ISSUE TITLE
Question: UI Changes

### ISSUE THREAD

**Issue by fatagun** [getsentry/sentry#2857]
Hello, Is it possible to make a minor UI change on a running instance? How do I go around modifying a Page Html code?

Thanks.

**Comment by dcramer** [comment]
Sentry is a mix of modern React templates (contained in static/app) as well as some legacy Django templates (in sentry/templates). You'd have to dig into what you want to change, but it's likely in React. I would absolutely recommend proposing the change as an issue first, unless its extremely minor, as we're fairly sensitive on UI/UX changes.
