### ISSUE TITLE
Unable to send alert notification to team

### ISSUE THREAD

**Issue by adamgsg** [getsentry/sentry#28582]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1.  Click Alerts > Create Alert Rule > Issues
2. Under "set Conditions" > "perform actions" click "Add action" > "Send Notification"
3. Choose "Send notification to Team"

### Expected Result

You will see a list of teams

### Actual Result

You will see a list of members, not teams

Both the "Members" and "Teams" options query the "https://sentry.io/api/0/organizations/my-org/members/?query=" endpoint.   The "Teams" option should instead query the "https://sentry.io/api/0/organizations/my-org/teams/?query=" endpoint.

**Comment by davidenwang** [comment]
Hi! Thanks for writing in about this bug, we caught it earlier this morning and a fix is coming out within the day!
