### ISSUE TITLE
RequirementParseError on Startup (Sentry v8.1.1), Complains about `_sqlite3`

### ISSUE THREAD

**Issue by sirosen** [getsentry/sentry#2866]
This caught me somewhat off-guard while digging into a separate issue with my Sentry server.

This is the basic form that the error took, as emailed to me by the server:
```python
RequirementParseError: Invalid requirement, parse error at "'_sqlite3'"
(5 additional frame(s) were not displayed)
...
  File "sentry/debug/utils/packages.py", line 19, in get_package_version
    return pkg_resources.get_distribution(module_name).version
  File "pkg_resources/__init__.py", line 540, in get_distribution
    dist = Requirement.parse(dist)
  File "pkg_resources/__init__.py", line 2806, in parse
    req, = parse_requirements(s)
  File "pkg_resources/__init__.py", line 2754, in parse_requirements
    yield Requirement(line)
  File "pkg_resources/__init__.py", line 2763, in __init__
    raise RequirementParseError(str(e))
```

Nothing in my `sentry.conf.py` refers to SQLite, and we're using Postgres as the DB.
Running on Ubuntu 14.04 with the stock python version (`2.7.6`).

I'm not clear on what this even means.
Could this be a side-effect of having done an in-place upgrade from an older version of Sentry?
Is there possibly lingering config that wasn't cleaned up during the upgrade process?

**Comment by mattrobenolt** [comment]
This was patched with [8.1.3](https://github.com/getsentry/sentry/releases/tag/8.1.3) and [8.2.1](https://github.com/getsentry/sentry/releases/tag/8.2.1).

A newer version of a system dependency was upgraded which broke Sentry. These patch releases were to address it.
