### ISSUE TITLE
Visual indicator in UI when `DEBUG` is `True`

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2868]
We should indicate something in the UI, probably just to superusers, if `DEBUG` is on when running Sentry. Right now, if somebody had this on, it's impossible to know unless looking at the config. We should say something in the UI about it, whether as a warning/banner thing, or something completely different. Maybe a bit less obtrusive since local development will obviously be running with `DEBUG = True` and we don't want that to be overly annoying for us.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
