### ISSUE TITLE
Issue gives "There was an error loading data. Retry button"

### ISSUE THREAD

**Issue by joshzitting** [getsentry/sentry#2870]
I have been testing sentry and it seems like I get it working fine and send some events to it etc but then after awhile I start gettting no event data when I click on an event and I get the warning.. "There was an error loading data." with a retry button.. the botton never loads anything.. 

Also at the same time I start getting the error below on the internal project.. 
`Error running script (call to f_3e3d663746e29efde08272f437568f78f65c387e): @enable_strict_lua:14: user_script:154: Script attempted to access unexisting global variable 'bit' 
`
```
ResponseError: Error running script (call to f_3e3d663746e29efde08272f437568f78f65c387e): @enable_strict_lua:14: user_script:154: Script attempted to access unexisting global variable 'bit' 
  File "sentry/utils/logging.py", line 23, in wrapped
    return func(*args, **kwargs)
  File "sentry/event_manager.py", line 477, in save
    **group_kwargs
  File "sentry/event_manager.py", line 693, in _save_aggregate
    ], timestamp=event.datetime)
  File "sentry/tsdb/redis.py", line 332, in record_frequency_multi
    self.cluster.execute_commands(commands)
  File "rb/cluster.py", line 390, in execute_commands
    results[key].append(targeted.execute_command(*command))
  File "rb/clients.py", line 577, in __exit__
    self.mapping_client.join(timeout=timeout)
  File "rb/clients.py", line 366, in join
    command_buffer.wait_for_responses(self)
  File "rb/clients.py", line 208, in wait_for_responses
    self.connection, command_name)
  File "redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "redis/connection.py", line 582, in read_response
    raise response
```

it says it is coming from here..'/usr/local/lib/python2.7/dist-packages/sentry/utils/logging.py'
this is on sentry 8.2.2

**Comment by tkaemming** [comment]
This was resolved in [8.2.3](https://github.com/getsentry/sentry/releases/tag/8.2.3), or you can upgrade to Redis 2.8.9+.

**Comment by mattrobenolt** [comment]
You mean Redis 2.8.18+. ;)

**Comment by tkaemming** [comment]
Oops, yeah, 2.8.18 — misread the release notes. :)

**Comment by joshzitting** [comment]
ok re-deploying and testing.. Thanks.

**Comment by joshzitting** [comment]
looking better. Thanks
