### ISSUE TITLE
Agressive data scrubber

### ISSUE THREAD

**Issue by sul4bh** [getsentry/sentry#2871]
I added 'cc' to the scrub field (cc for credit card) and Sentry scrubbed 'Accept' header because it has 'cc' in it. Is this how the scrubber is supposed to work? I think this behavior is a bit aggressive.

**Comment by mattrobenolt** [comment]
Yeah, this is a known issue, and we don't have a solution as of yet. This is working as expected, but it's definitely overly aggressive and it's not ideal.

My thoughts are allowing these patterns to be "glob" style.

So you could specify "cc", "cc*", "*cc", or "*cc*" to control how the match happens.

**Comment by sul4bh** [comment]
Glob style matching looks like a good idea.
Thanks for clarifying.

**Comment by tkaemming** [comment]
See also: GH-2840

**Comment by dimaqq** [comment]
Thanks @sul4bh and @mattrobenolt your description and response just saved me from wasting another half a day trying to figure out why my entire breadcrumb was `[Filtered]`. I was logging unrecognised error JSON, which just happened to contain `"message": "Invalid Password"` 😡
