### ISSUE TITLE
Background workers haven't checked in recently

### ISSUE THREAD

**Issue by nuklea** [getsentry/sentry#2873]
I use sentry 8.0.6 with redis 3.0.7 as a celery broker. Celery is running with `-B` flag.

I see warning _Background workers haven't checked in recently. This can mean an issue with your configuration or a serious backlog in tasks._ if the sentry for a long time does not receive an error notification from clients. Immediately after receiving the error, the warning disappears.

Problem appeared after upgrade from sentry 7.7.4.

**Comment by mattrobenolt** [comment]
Try running without `-B` and running a separate `sentry celery worker` and `sentry celery beat`. There's an issue with running `-B` and we no longer recommend doing it that way.

**Comment by nuklea** [comment]
@mattrobenolt thanks! It seems to have helped.

**Comment by adamlc** [comment]
Fantastic, this has fixed the issues for me too :)

**Comment by nuklea** [comment]
Maybe upstream problem?

**Comment by mattrobenolt** [comment]
> Maybe upstream problem?

It's complicated. :)

**Comment by autumn1023** [comment]
When I opened the terminal, I found that the log has been brush, we have encountered this problem

**Comment by Wowgreat** [comment]
I install sentry first time and met the trouble today.
this is may solution:
[senrty installation](https://github.com/Wowgreat/softwares-installation/blob/master/sentry.md)
