### ISSUE TITLE
Possible to sort by User?

### ISSUE THREAD

**Issue by karli2000** [getsentry/sentry#2874]
Hi,

in Sentry i can sort by First Seen, Frequency, etc. but i cannot sort by user. 
I know, detecting unique users can be hard, but the numbers are there already, when i can sort by user it would give me at least some hint how many people are affected. 
A bug that happened for 10k users once is in my view more important than a bug that a happened 10k times for two user :)

PS: keep up the great work, sentry is great!

**Comment by ehfeng** [comment]
Upvoted https://twitter.com/drewml/status/732688410662473728

**Comment by benvinegar** [comment]
What if we just implemented it like this:

![image](https://cloud.githubusercontent.com/assets/2153/15720653/180834a2-27ea-11e6-9902-9eb351379c44.png)

**Comment by mordaha** [comment]
++

And what is the status of?

**Comment by tkaemming** [comment]
The user count that's displayed in the stream view [is derived from the `GroupTagKey`](https://github.com/getsentry/sentry/blob/02472b6fc4d8fba2cd0ab50a2a109adad6b88234/src/sentry/api/serializers/models/group.py#L123-L128) (`sentry_grouptagkey` table) record. As far as I can tell, the biggest blocker here is that there is no index that would satisfy this query. Most (maybe all?) of the other sort clauses are directly off indexed[1] columns on the `sentry_groupedmessage` table.

If we wanted to implement arbitrary threshold filters on the number of distinct times any tag value — not just user — has been seen, we'd probably want to create an index similar to `(project_id, key, values_seen DESC)` on this table. If we only wanted to index the user tag for a sort clause, [we could do that with a partial index](https://www.postgresql.org/docs/9.3/static/indexes-partial.html), at least for PostgreSQL. We'd have to create some additional index on this table in either case which could potentially be expensive.

I do think this is a potentially useful feature, but not sure offhand what the cost of creating this index would be on write operations or on disk utilization.

[1]: or at least *should* be indexed…

**Comment by tow-ableton** [comment]
Interested to hear if there has been any progress with this. Sorting by users still is one prominent wish for us and would greatly improve our work with Sentry.

**Comment by chrismerck** [comment]
Indeed. My organization judges issue severity by number of users impacted, rather than total occurrences.

**Comment by kishorenaib** [comment]
Sorry to re-bump, but this feature is important...
I can't think why the default ordering would be by event count DESC?  it doesn't have much practical meaning. Error count by User (maybe multiplied by user-priority ranking in internal db for advanced usage) ORDER BY DESC is the barometer of error reduction.  Not COUNT of errors.

Are you guys going to add this sort option after all this time?  Without it, I find the UI unusable.  Maybe we need more time with it.  But strong bump for ORDER BY USERS DESC...

**Comment by chocnut** [comment]
I don't really understand why is this complicated? Cleary, when I do an API call to issue the response, does have userCount field. Can you just include this to you Sentry CLI then?

**Comment by chocnut** [comment]
Anyways, I just made a small script for me to use. Let me know if anyone want this happy to share it. I hope the sentry team can add this as their feature.

![Screenshot 2019-12-13 at 16 32 31](https://user-images.githubusercontent.com/291424/70786013-98a67f80-1dc6-11ea-8e37-97ea619582d7.png)

**Comment by rjnienaber** [comment]
Here is the script that I've been using to get the details out that I need, sorted by users affected:

```
curl -H 'Authorization: Bearer $SENTRY_TOKEN' $SENTRY_URL | \
jq -r '[.[] | {id: .id, title: .title, count: .count | tonumber, users: .userCount, firstSeen: .firstSeen, lastSeen: .lastSeen, culprit: .culprit, filename: .metadata.filename, link: .permalink}] | sort_by(-.users)' | \
in2csv -f json > /tmp/errors.csv
```

Relies on [jq](https://stedolan.github.io/jq/) and [csvkit](https://csvkit.readthedocs.io/en/latest/).

**Comment by mpspencer** [comment]
Can't believe this was raised in 2016 and not yet addressed.

When ordered by Frequency there are cases when the error rate per user is higher than some other issues. For example on the screenshot below the 3rd highest had 15k events from 326 users where as the 5th most frequent issue had 19k events from 16k users. I would think that most people would prioritize the 19k events from 16k users issue rather then the 15k events from 326 users issue.

![image](https://user-images.githubusercontent.com/9847041/76304169-dea7ac80-62fd-11ea-8042-0af966551d25.png)

**Comment by chocnut** [comment]
Anyone who still interested in or looking for a tool. Please check my repo [here](https://github.com/chocnut/sentry-monitor)
