### ISSUE TITLE
Captcha on Sign-In Broken on Phones

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#2875]
Users who are shown the captcha on sign-in report issues with it working on mobile view.

**Comment by ckj** [comment]
Here's the problem:

![screen shot 2016-03-21 at 1 51 33 pm](https://cloud.githubusercontent.com/assets/30713/13933906/a01d4b2c-ef6c-11e5-8336-c67ac1057bb2.png)

and

![screen shot 2016-03-21 at 1 51 55 pm](https://cloud.githubusercontent.com/assets/30713/13933912/a5e38ab2-ef6c-11e5-976a-fff92246edbf.png)

From personal experience I get my password wrong more often on mobile and we aggressively require this captcha after 1 mistake. Any chance we can disable it entirely here? If not, I can look into if we have any control over the way this renders.

**Comment by dcramer** [comment]
Can't disable it unfortunately. We should try to resolve visuals or move to diff captcha. Can also make it less aggressive. 






On Mon, Mar 21, 2016 at 2:00 PM -0700, "Chris Jennings" <notifications@github.com> wrote:












Here's the problem:







and







From personal experience I get my password wrong more often on mobile and we aggressively require this captcha after 1 mistake. Any chance we can disable it entirely here? If not, I can look into if we have any control over the way this renders.

**Comment by mitsuhiko** [comment]
@dcramer is the captcha about rate limiting the login? We could explore some alternatives to the captcha there.

**Comment by dcramer** [comment]
It's just to prevent automated brute force, though it realistically doesn't do that if you're slightly clever.






On Mon, Mar 21, 2016 at 2:03 PM -0700, "Armin Ronacher" <notifications@github.com> wrote:












@dcramer is the captcha about rate limiting the login? We could explore some alternatives to the captcha there.

**Comment by mitsuhiko** [comment]
A reasonable way to deal with that is on failure to sign in to increment a failure counter and write a timestamp into db/memcache. Next failure you sleep in the worker until that passes. It's a bit shitty because you can take workers down but on wait times > n seconds you can just make the request fail instantly.
