### ISSUE TITLE
Notifications activity feed

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2878]
Surface an activity feed of either per-project or per-organization notification events.

These would be triggered by rules, I'd assume, and would help with debugging the many issues if people claiming they haven't gotten a notification, or the notification sent and errored.

This feed could show errors triggered by plugins or bounced emails, the list of emails the notification was sent to, etc.

**Comment by mattrobenolt** [comment]
See also possibly some overlap with GH-2695.

**Comment by mattrobenolt** [comment]
First step is to just add some logging around every notification trigger, so we could trace this back at the operations level first, before we try to save every event in database.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
