### ISSUE TITLE
Discarded invalid value for parameter 'user' on "null" email

### ISSUE THREAD

**Issue by bradynpoulsen** [getsentry/sentry#2882]
What are the validity requirements for the user parameter?

My current guess is that the email is being sent across as "null" although its actual value is a literal null on our application.

**Comment by mattrobenolt** [comment]
If you click on "Expand", it should have more details. Mind posting what it says?

**Comment by bradynpoulsen** [comment]
```There was 1 error encountered while processing this event
Discarded invalid value for parameter 'user' Collapse
{
  "name": "user",
  "value": {
    "username": "johndoe",
    "first_name": "John",
    "last_name": "Doe",
    "phone": "null",
    "created_on": 1458239804,
    "email": "null",
    "id": "12",
    "updated_on": 1458512606
  }
}```

**Comment by dcramer** [comment]
@bradynpoulsen I'm guessing its yelling at you because of "null" on email

**Comment by bradynpoulsen** [comment]
That's exactly what I'm thinking. But when I provide the email to sentry, it's provided as a literal null. So that means its stringifying as a literal string

**Comment by bradynpoulsen** [comment]
And I've checked it with all the other exceptions that have this issue. They all show `"email": "null"`

**Comment by dcramer** [comment]
@bradynpoulsen you're certain? is this PHP or JS? definitely is email is "null" as a string it will throw a validity error

**Comment by bradynpoulsen** [comment]
I'm absolutely certain. It is PHP. It's also on getsentry.com

**Comment by bradynpoulsen** [comment]
I clicked on the "JSON" link to view the raw request, but it showed up the same there, too

**Comment by dcramer** [comment]
Somewhere on the PHP end its serializing null as "null". The easiest work around atm would be simply to not set the key until we sort out what else might be going on.

**Comment by bradynpoulsen** [comment]
For now I'm checking if email is null and setting it accordingly

**Comment by dcramer** [comment]
Closing in favor of PHP issue

**Comment by dimaqq** [comment]
Sorry to jump on the old thread, apparently empty string is also invalid:

<img width="512" alt="Screenshot 2019-05-09 at 13 36 32" src="https://user-images.githubusercontent.com/662249/57427603-8c21dd80-725f-11e9-93f3-114516429c61.png">

`"errors":[{"reason":"invalid characters in string","type":"invalid_data","name":"tags.0.1","value":""}]`

Do I understand that right?

I'm also a bit confused over what `tags.0.1` is, is that an index into tags array?

**Comment by jamesgraham** [comment]
Can anyone point to the documentation on what are the valid characters for the params?
