### ISSUE TITLE
Allow guest access per OU or per project

### ISSUE THREAD

**Issue by mitchhentges** [getsentry/sentry#2887]
I'm working on [an open-source project](https://github.com/james-proxy/james), and I'm having issues reported back to Sentry, which I'm hosting myself.

It's pretty awesome, but it's missing one thing: guest access.
I'd like other contributors (who I don't need to manually add to the GitHub OU) to be able to see Sentry reports. Ideally, I can specify individual projects to have "guest access", so anyone can see the project, but can't write to it (resolving issues, etc).

It seems like authentication happens on an OU level, so OU-level guest access would _also_ work, but it might not work for partially-open-source organizations.

Either way, this application is fantastic. Good design, and pretty responsive. :+1:

**Comment by dcramer** [comment]
I think this is an interesting idea, and I'm absolutely in favor of better supporting use cases like this. We would need to figure out some things like:

- What does guest access give access to?
- Does guest access show full details of issues or just the public view?

**Comment by mitchhentges** [comment]
From my perspective, I feel that guest access is the equivalent of giving everyone a read-only full account. So:
* Allow viewing each entry in the `ORGANIZATION` and `ISSUES` group in the side bar
* Show full details when viewing an issue
* Of course, don't allow making changes to anything

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by BYK** [comment]
Also, this should be possible with shareable events/issues now FYI.
