### ISSUE TITLE
Send back Retry-After header for blacklisted IP responses

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#2890]
Right now, if you blacklist an IP address inside of Sentry, the request is rejected and doesn't affect your project's quota, but the client will continue to attempt to send requests, which doesn't help us at all handling the traffic.

On requests that get rate limited, we _do_ send back a `Retry-After` header, which I think only `raven-python` supports (because I added it years ago) and the client will back off and stop even attempting to send requests for X seconds.

We should implement the same thing on a blacklisted response, but a much higher `Retry-After`. Say, `Retry-After: 300`, then clients could 100% disable itself for the next 300 seconds. This would mitigate the issue of stray clients hammering away at the Sentry server when someone blacklists.

Ideally, this would need to get implemented into our major SDKs (python, ruby, java, go, node). We can't do this in raven-js since it can't read the header back (I don't think we could do this? Maybe if we send back this value in the JSON response body as well. @benvinegar)

**Comment by benvinegar** [comment]
Re: Raven.js – pretty sure we can read the header.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
