### ISSUE TITLE
Add tool to migrate deprecated settings to configuration file.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#2893]
@mattrobenolt brought this up the other day — since we already know what settings need to be moved (essentially anything that raises a `DeprecatedSettingWarning`) we should be able to put together a little CLI tool to move automatically these values to the configuration file. The user would still need to manually remove these settings from their legacy settings file, however.
- [ ] Figure out what to do with `sentry.conf.py` (to avoid conflicts with settings declared in multiple places.)
- [ ] Figure out how to migrate to `redis.clusters` — `SENTRY_REDIS_OPTIONS` can represent default, and then iterate through other backends, comparing them to the default cluster and creating new clusters if they are different?

**Comment by chadwhitacre** [comment]
Gonna go ahead and close this one out as stale.
