### ISSUE TITLE
OAuth enabled for one org prompts for password when joining a different org

### ISSUE THREAD

**Issue by cnuss** [getsentry/sentry#2894]
hey

we found an issue regrading multiple orgs and oauth.  we have Google oauth enabled and multiple orgs.

when a new user joins one org, they are successfully oauth'd and allowed into that org.  

when the same user tries to join another org, they're prompted to enter their password.  they obviously don't have one due to oauth.

workaround is to go through the password reset flow and get the password

**Comment by dcramer** [comment]
Open to thoughts on how we should address this. It seems like we could be smart when someone tries to login with an SSO-only account, but I think no matter what they're going to be in a complicated situation.

**Comment by cnuss** [comment]
is there metadata somewhere that tracks that they're SSO?  or does that need to be added?

**Comment by dcramer** [comment]
@cnuss no metadata, but we know "they have no password", so we could use that as a generic indicator for any kind of account

**Comment by cnuss** [comment]
@dcramer What about `auth_user`.`is_managed`?  Seems to be true for any users that have SSO'd in my Sentry instance.  Also the password is empty in the db as well, as you mentioned.  Using these two fields, we could do a domain comparison with the user's domain and the organization's required domain, and bypass the password screen?  Happy to put more thought into it if you think I'm missing something

**Comment by dcramer** [comment]
We wouldn't be able to bypass any of the login screens as each is independent based on the org (they are share nothing). We could however make a simply flow that its more clear how they can convert their account (assign a password), or even push for that as a step once they've created the account initially.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
