### ISSUE TITLE
Downgrade psycopg2-binary on Python 3.8

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#28958]
psycopg 2.9.x is fundamentally incompatible with Django 2.2: https://github.com/psycopg/psycopg2/issues/1293

We'll have to stay on 2.8.x and find a way to get it working with Apple M1 machines.

**Comment by tokdev** [comment]
Got the same issue with it. Try to downgrade it to 2.8.6 but get issues for it. What is the solution for it?

**Comment by armenzg** [comment]
> Got the same issue with it. Try to downgrade it to 2.8.6 but get issues for it. What is the solution for it?

You can either upgrade to Django 3.2 or downgrade to psycopg-binary 2.8.6. See [this issue](https://github.com/psycopg/psycopg2/issues/1293#issuecomment-863430637) for all details.
