### ISSUE TITLE
Remove Callsign

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#2896]
(documenting this so we know what we need to do)

- [x] Empty out the migrations that add the fields (they haven't been in a point release yet)
- [x] Adjust any future migrations to remove references
- [x] Run manual query on getsentry.com to kill the columns

We can document the manual query as part of the commit message so if anyone really did install from git they can do it as well. I think this is the safest/cleanest approach, since it's an expensive migration by default.

**Comment by mitsuhiko** [comment]
This is done now.
