### ISSUE TITLE
How to do Secondary Development ?

### ISSUE THREAD

**Issue by hustcc** [getsentry/sentry#2897]
Hello, all, `sentry` is a very nice work, now I want wo do some `Secondary Development` to use it into my QA daily work. Such as:

1. add some action buttom, eg: push to redmine.
2. openid login with our company user system.
3. simplify the authority management.

Can give me some guide to tell me `HOW TO START`? Such as:
 - How to run it in develop environment?
 - technology which is used to develop?

Thanks very very much.

**Comment by mattrobenolt** [comment]
Hey @hustcc, we actually do not. I've just created a more encompassing issue under GH-2899 to get this done.

But quickly to answer your questions:

To get started in a development environment, you'll need: python, node, postgres, and redis at minimum. If you're familiar with Docker, you're in luck. We provide a [Dockerfile.dev](https://github.com/getsentry/sentry/blob/master/Dockerfile.dev) that is moderately documented.

Without docker, it should just be a matter of cloning the repository and running `make develop` to get everything installed.

Then to run a local dev server of sentry, you'd just do `$ sentry devserver` and this should spin up a local server on port 8000.

Let me know if you have any other questions, and I'll be happy to add these to official docs when I get around to it.

Thanks! :)

**Comment by hustcc** [comment]
many thx.

**Comment by hustcc** [comment]
I have done below steps:
1. `make develop`
2. `sentry init`, edit the config file
3. `sentry devserver`

then, open `http://ip:8000` can not work, `ping 127.0.0.1:8000` on the server, can get server log 400 HTTP code. log below:
![image](https://cloud.githubusercontent.com/assets/7856674/14072268/25821e9e-f4f1-11e5-81dd-ab463290707f.png)

**Comment by mattrobenolt** [comment]
For local dev, you'd likely want to put `DEBUG = True` in your config. That should avoid the 400 error. 

You also didn't run `sentry upgrade` which is still required.

**Comment by hustcc** [comment]
Now, `127.0.0.1:8888` is OK, How can I visit it use `IP:8000` after `sentry devserver` ?

**Comment by mattrobenolt** [comment]
I'm not sure what you mean, by default, `sentry devserver` binds to `127.0.0.1:8000`. You could also do: `sentry devserver 127.0.0.1:8888` to change what it binds to.

**Comment by hustcc** [comment]
It `worked`! very thanks~

**Comment by hustcc** [comment]
Hello, problem came again, in database table `sentry_option`, there have some options, I need update it on my hand, but I do not know how the `value` column was encrypted?

**Comment by dcramer** [comment]
You will need to use the ORM. I highly recommend looking at the Django docs to better understand the paradigm that Sentry is developed in.

That said, the best strategy for early contributions is to suggest a change via an issue. We can always provide guidance (as well as a clear "yes we'll allow this") with this method.

Also keep in mind GitHub is not a place for general questions like this (it notifies more or less every contributor). Please use the Google Group or IRC or something similar for general discussion.
