### ISSUE TITLE
[Feature suggestion] Search by date range

### ISSUE THREAD

**Issue by dkarlovi** [getsentry/sentry#2898]
Let's say I have a **known date range** in which an error happened and would like to find it. It would be great to be able to find a specific sample of an error which was collected in the said date range.

I know about `age`, but I don't think it's a good fit for this use case.

**Comment by dcramer** [comment]
We haven't opened up any search availability on the raw samples that are stored (primarily because they may or may not exist), but you can search using ``event.timestamp:>2016-01-01 event.timestamp:<2016-01-02`` (we havent documented this yet).

**Comment by dkarlovi** [comment]
Excellent, thank you!

**Comment by wting** [comment]
FYI this is now officially documented [here](https://docs.sentry.io/learn/search/).

**Comment by stantonk** [comment]
@dcramer @wting what version is this available in? i'm not seeing it filter the results with:

`event.timestamp:<2017-10-19T10:00:00 server_name:somehost01`
