### ISSUE TITLE
Lack of acknowledgement for translators

### ISSUE THREAD

**Issue by caizixian** [getsentry/sentry#2906]
Maybe add translators from Transifex to https://getsentry.com/thanks/ is a good idea.

**Comment by dcramer** [comment]
I'm on board with this. Not sure what it'll take but I assume Transifex has an API that makes it easy enough.

**Comment by caizixian** [comment]
http://docs.transifex.com/api/languages/

**Comment by caizixian** [comment]
@dcramer http://docs.transifex.com/api/languages/
This API can list contributors by roles in each team.

**Comment by mattrobenolt** [comment]
I'll take care of this. :) Thanks for the suggestion.

**Comment by caizixian** [comment]
@mattrobenolt How's it going? :)

**Comment by dcramer** [comment]
fwiw this isn't a high priority item

**Comment by chadwhitacre** [comment]
Ancient issue but still accepted afaict. Moving to backlog.

**Comment by chadwhitacre** [comment]
Looks like we still use [Transifex](https://explore.transifex.com/getsentry/sentry/):

> **Last activity**
> 3 days ago

I see "873 contributors" but no drilldown in Transifex, that would've been nice.

**Comment by chadwhitacre** [comment]
https://gist.github.com/mikejolley/8862027

**Comment by chadwhitacre** [comment]
https://transifex.github.io/openapi/
