### ISSUE TITLE
"Delete rule" button misbehavior

### ISSUE THREAD

**Issue by etataurov** [getsentry/sentry#2915]
I have "Every time __all__ of these conditions are met:" rule
with two conditions:
1. An event's level is __greater than or equal to__ __Debug__
2. An event's level is __less than or equal to__ __Error__

When I press the delete button for the first rule - it remains on its place, but second one is being deleted.

Another issue:
two conditions:
1. An event is first seen
2. An event's level is __equal__ __Info__

When I press the delete button for the first rule - first rule deletes, but the second changes to
1. An event's level is __greater than or equal to__ __Warning__

In this case `<select>` also loses its style https://www.dropbox.com/s/pewu6hahd9obmw4/Screenshot%202016-03-26%2020.49.31.png?dl=0

I have these issues on both Safari and Chrome.
And on both local setup (@4fe01197f2f04d176c4101607fa40d2d2ccab575) and https://app.getsentry.com/

**Comment by dcramer** [comment]
@benvinegar can you take a look at confirm repro?

**Comment by benvinegar** [comment]
I can reproduce. Investigating a fix now.
