### ISSUE TITLE
Blockquote styles in activity/comments is abnormally large

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#2931]
![image](https://cloud.githubusercontent.com/assets/2153/14100658/eedef148-f543-11e5-9b3b-8d9244f6b98c.png)

cc @ckj

**Comment by ckj** [comment]
Fixed:

<img width="490" alt="screen shot 2016-06-06 at 7 30 19 pm" src="https://cloud.githubusercontent.com/assets/30713/15844224/2e5b0acc-2c1d-11e6-8258-f2040275617c.png">
