### ISSUE TITLE
Redirect a merged issue to merged issue

### ISSUE THREAD

**Issue by msjaiswal** [getsentry/sentry#2936]
Lets say there is an issue A and it is merged with other issues B,C and D to form a merged issue X. 
In this case, 
http://example.com/gludo/crawlers/issues/A 
should be redirected to
http://example.com/gludo/crawlers/issues/X

**Comment by tkaemming** [comment]
This was resolved with GH-2104 and will be available in Sentry 8.3 (and is available on master.)
