### ISSUE TITLE
Alert Rule suggests options that are not fully supported

### ISSUE THREAD

**Issue by peanderson2016** [getsentry/sentry#29409]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Got to Alerts
2. Create Alert
3. Select `Number of Errors`
4. Change `Events` to `event.type.error OR event.type.default`
5. Set `Critical` value
6. Give the Rule a name
7. Save Rule
8. View your new rule 

### Expected Result

I would expect to see a list of related issues on the Alert Rule page

### Actual Result

- When viewing the Rule page you can see that `Related Issues` states `There was an error loading data`
![image](https://user-images.githubusercontent.com/41328548/137913979-216b1d2f-7813-4546-bddd-54313c68dc4a.png)

-  Clicking `Open in Issues shows the error `Error parsing search query: Boolean statements containing "OR" or "AND" are not supported in this search`
![image](https://user-images.githubusercontent.com/41328548/137914274-7636581d-0aeb-4183-88cf-4091fc102ca2.png)

-  Works as expected when opening in `Discover`

**Comment by scttcper** [comment]
we handle `event.type.error OR event.type.default` now and issues will appear. Additional OR queries will still fail.
