### ISSUE TITLE
App Store Connect integration: remove iTunes Credentials requirement

### ISSUE THREAD

**Issue by maxlapides** [getsentry/sentry#29531]
As [the docs](https://docs.sentry.io/platforms/apple/guides/ios/dsym/#bitcode-appstore) currently note, setting up App Store Connect integration with Sentry currently requires two separate credentials: App Store Connect API Key and iTunes Credentials.

As of recently, the App Store Connect API now includes a download dSYMs function that should make the iTunes Credentials requirement unnecessary. You can see the discussion in Fastlane, which has just implemented this update: https://github.com/fastlane/fastlane/discussions/17485#discussioncomment-1517796

Is there any timeline for supporting this within the Sentry App Store Connect integration?

**Comment by jacobhzen** [comment]
Patiently waiting for this to become live! We have an existing API key (but not service account) and are looking to set this up. Are there any known specifics on how often this sync occurs?

**Comment by relaxolotl** [comment]
The changes should now be deployed 🎉 This might be a little rough around the edges as we work through some edge cases, so issues detailing any problems with the new set up and syncing experience are welcome.

@jacobhzen syncing occurs approximately once an hour, so the general estimate we provide is about an hour (at worst) for dSYMs to be downloaded, ignoring any potential issues with the download or the credentials used.

The frequency is also mentioned in our documentation [here](https://docs.sentry.io/platforms/apple/guides/ios/dsym/#bitcode-appstore) but it is a little hidden: you'll want to look for the small block of text after the first screenshot in the section I've linked to.

**Comment by diogot** [comment]
Great thanks!
Just one doubt,  in the `Custom repositories` panel I see `8 builds pending` for the last 3 or 4 days.
I expect that this number goes down in over the days. Do you know why this is happening? Should I open a ticket to this be investigated?

**Comment by relaxolotl** [comment]
@diogot if you could open up a ticket that would be greatly appreciated. We can pick up from there and take a look at what's going on. 

There are a couple of reasons why dSYMs might fail to sync, but normally there should be some hints in the UI, particularly in the same place that tells you how many builds are left to be synced (Project Settings -> Debug Files) that guide you towards fixing those up. What you're seeing sounds quite strange, so we might have to do a bit of spelunking to figure out what's happening in your project.

**Comment by diogot** [comment]
@relaxolotl I opened a support request, thanks!

**Comment by philipphofmann** [comment]
@relaxolotl and @flub, can't we close this issue?

**Comment by flub** [comment]
yep!
