### ISSUE TITLE
Http API Query params lists are converted to strings in sentry.io ui

### ISSUE THREAD

**Issue by mljlynch** [getsentry/sentry#29543]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

If you have access to this issue you can see: https://sentry.io/organizations/fig-food-is-good/performance/fig-api:7b39e232d6dc486aa065587b54f72fbe/?project=5576189&query=transaction.duration%3A%3C15m+event.type%3Atransaction+http.method%3AGET&statsPeriod=24h&transaction=GET+%2Fv0%2Fproduct%2Frandom&unselectedSeries=p100%28%29

The data is:
```json
{
  "baseUrl": "/v0/product",
  "query": {
    "diet": "65eace81b4e6bb63259b5a66d6daeb1fb0275e2f",
    "filteredRatings": [
      "red",
      "yellow"
    ],
    "offset": "",
    "seed": "277"
  },
  "url": "/v0/product/random?diet=65eace81b4e6bb63259b5a66d6daeb1fb0275e2f&filteredRatings=red&filteredRatings=yellow&offset=&seed=277"
}
```

note: `&filteredRatings=red&filteredRatings=yellow`

But in the convert to curl UI it converts it inappropriately to a string: 

In this section: 
![image](https://user-images.githubusercontent.com/13424219/138720902-1cb4c601-93fc-440a-95c2-19052abe13e7.png)

The url is

```sh
"https://api.foodisgood.com/v0/product/random?diet=65eace81b4e6bb63259b5a66d6daeb1fb0275e2f&filteredRatings=%5B%22red%22%2C%22yellow%22%5D&offset=&seed=277"
```

### Expected Result

```sh
"https://api.foodisgood.com/v0/product/random?diet=65eace81b4e6bb63259b5a66d6daeb1fb0275e2f&filteredRatings=red&filteredRatings=yellow&offset=&seed=277"
```

### Actual Result

```sh
"https://api.foodisgood.com/v0/product/random?diet=65eace81b4e6bb63259b5a66d6daeb1fb0275e2f&filteredRatings=%5B%22red%22%2C%22yellow%22%5D&offset=&seed=277"
```

**Comment by chadwhitacre** [comment]
Sorry @mljlynch, our web team is overwhelmed and not keeping up GitHub Issues right now. 😞 I'm putting this to the backlog so it at least stays open.

**Comment by mljlynch** [comment]
Sounds good thanks for the update @chadwhitacre

**Comment by mydea** [comment]
**Why was this issue closed?**

This issue hasn't been touched recently and no longer seems relevant. 
Hence, we're closing it to maintain a clean and transparent backlog.

Please feel free to leave a comment if you think this issue should be reopened.
