### ISSUE TITLE
Small Source Maps Remote file too large for caching

### ISSUE THREAD

**Issue by Scong** [getsentry/sentry#29550]
### Environment

self-hosted (`onpremise` deployment)

### Version

21.9.0

### Steps to Reproduce

1. Run sentry on Prem upgraded kubernetes helm chart 11.9.0.
2. Let source maps (smaller than 10MB) be available publicly or upload them manually via CLI with no errors.

Prior to upgrade our helm / sentry version we did not have any issues with source maps.

I have seen other users have similar issues, but have not found a relating issue in github. 

https://forum.sentry.io/t/config-parameter-to-set-max-cache-size/14811

Some users mention having even smaller source maps with this issue. We had the same issues on earlier charts as well as earlier version of Sentry. If I had to guess, version 9 was working for us, but versions above 20 were not (don't have precise records).

This person had to go down an epic, I think our issue is potentially different though.  Still evaluating.
https://engblog.yext.com/post/sentry-js-source-maps

### Expected Result

Expect source maps to be available for issues / artifacts to be available in Sentry after manual upload or public retrieval.

Expect to receive an error in Sentry-CLI if source map artifacts cannot be created. 

Expected different error message if it is not related to cache size (as it appears not to be as source maps are smaller). 

### Actual Result

![image](https://user-images.githubusercontent.com/4022295/138727719-f8d9c677-6ab9-465c-82b6-12bc972dc4c3.png)

![image](https://user-images.githubusercontent.com/4022295/138728069-76151623-e055-496a-b94a-502cb9e75176.png)

```
 Bundling files for upload... ~/packs/js/stuff.js
> Bundling completed in 3.11s
> Optimizing completed in 0.094s

(Biggest sourcemap)
  DEBUG   2021-10-25 16:18:25.578900803 +00:00 > Content-Length: 9338457
  Uploading completed in 1.332s
  
Processing completed in 0.237s
> File upload complete (processing pending on server)
> Organization: sentry
> Project:$PROJECT_NAME
> Release: $RELEASE_NAME
> Dist: None

Finalized release $RELEASE_NAME
```

**Comment by Scong** [comment]
This ended up being related to our cache being inaccessible by Sentry. An upgrade instruction was missed related to how Redis should be configured (usePassword: true) in the chart. From chart 9 -> 10 for the helm sentry chart.

I'm leaving this open as the error thrown is miss leading.

**Comment by chadwhitacre** [comment]
@Scong Glad you got it sorted! :)

I'm going to go ahead and close this out. We now have something for those who hit the same issue to find via google, and anyway this situation won't really arise except when deploying Sentry using `onpremise`, which is primarily what we support.
