### ISSUE TITLE
Template "absolute_asset_url" ignore HTTPS protocol

### ISSUE THREAD

**Issue by JiffsMaverick** [getsentry/sentry#2981]
I turned on HTTPS in Nginx and [Sentry](https://docs.getsentry.com/on-premise/server/installation/#enabling-ssl), but browsers (Chromium, Firefox etc) show warning:

`Mixed Content: The page at 'https://example.com/sentry/' was loaded over HTTPS, but requested an insecure favicon 'http://example.com/_static/d896d9de2e6c63ebbbede072b88b7883857ccfbc/sentry/images/icons/apple-touch-icon.png'. This content should also be served over HTTPS.`

**Comment by dcramer** [comment]
This is a misconfiguration somewhere:

- url prefix is wrong
- or protocol forwarding not setup per docs

**Comment by JiffsMaverick** [comment]
Oh, yes, my mistake, "system.url-prefix" solved my problem. Thanks!

P.S.: perhaps it's necessary to update the [manual section on the SSL](https://docs.getsentry.com/on-premise/server/installation/#enabling-ssl) and add about system.url-prefix.
