### ISSUE TITLE
Invasive infobar for unsolvable issue

### ISSUE THREAD

**Issue by moimael** [getsentry/sentry#2983]
Hi,

Since 8.3.0 release there is an orange infobar popping to inform about deprecated settings.
This part is fine and a good idea.
What I find truly annoying is, that after I fixed deprecated settings, I still have this infobar because my redis release is too old. (Redis (TSDB) should be upgraded to 3.0.4 on 127.0.0.1:6379.).

While I understand, our Sentry is hosted on a CentOS 7 machine which won't have redis 3 ever. I'm stuck with 2.8. Considering that CentOS/Red Hat OSes are massively used and nowhere near end of life, would it be conceivable to remove this warning ?

Thanks !

**Comment by tkaemming** [comment]
I updated the versions to be more reflective of our roadmap as we understand it today — we won't be requiring 3.X for any reason in the foreseeable future, but we will likely require 2.8.18 for the TSDB backend in an upcoming release.

The alert bar itself should be able to be persistently dismissed for a week as of GH-2945. (If you're particularly adventurous, you can check out the source and it should be fairly obvious how to make it be dismissed effectively indefinitely from your JavaScript console.)

We may also look into providing a hook for adding filter functions to the warnings manager, but that's probably as much control as we'd allow for disabling these notifications system-wide.
