### ISSUE TITLE
gavatar default image is confusingly similar to unassigned icon

### ISSUE THREAD

**Issue by macqueen** [getsentry/sentry#2987]
![screen shot 2016-04-05 at 11 38 33 am](https://cloud.githubusercontent.com/assets/5026776/14293818/1d7a6d22-fb23-11e5-8915-8d49efe934ba.png)
![screen shot 2016-04-05 at 11 40 12 am](https://cloud.githubusercontent.com/assets/5026776/14293840/30f4055c-fb23-11e5-92ba-687fdb483323.png)

**Comment by mattrobenolt** [comment]
See also: https://github.com/getsentry/sentry/issues/2856

**Comment by macqueen** [comment]
closing since this duplicates #2856
