### ISSUE TITLE
NodeUnpopulated: You should populate node data before accessing it.

### ISSUE THREAD

**Issue by balsagoth** [getsentry/sentry#3001]
I'm having the same issue as #2524 with sentry-jira plugin.

Somehow on models/event.py in `get_interfaces()` method, it cannot iterate over `NodeData` object.

    for key, data in self.data.iteritems():

where data is `<NodeData: id=9vcAqDXlQt+ykm+SK50qiQ==>`

I'm on sentry version 8.2.4

**Comment by balsagoth** [comment]
Upgraded to sentry-jira 0.11-dev and Sentry to 8.3.1 and everything works like a charm.

**Comment by Duologic** [comment]
I'm still get this error with the sentry-jira plugin.

        $ pip freeze  | grep sentry
        sentry==8.4.1
        sentry-jira==0.9.0

I've checked the source code a little bit but this goes beyond my knowledge. Not sure where the NodeData is coming from.

**Comment by Duologic** [comment]
sentry-jira==0.10.0 seems to fix it for me.

I'll go and create an issue on sentry-jira to release that on PyPi.
