### ISSUE TITLE
Fix russian spelling

### ISSUE THREAD

**Issue by MikeVL** [getsentry/sentry#3003]
File: src/sentry/locale/ru/LC_MESSAGES/django.po

Change:
```diff
-msgstr "Добро пожаловаьт в Sentry"
+msgstr "Добро пожаловать в Sentry"
```

**Comment by dcramer** [comment]
Hey Mike

We unfortunately dont have a way to accept changes like this on GitHub. If you want to help, you can sign up on Transifex: https://www.transifex.com/getsentry/sentry
