### ISSUE TITLE
Segmentation fault (core dumped) after sentry upgrade

### ISSUE THREAD

**Issue by AlexFinn** [getsentry/sentry#3004]
```
> sentry:0234_auto__add_savedsearchuserdefault__add_unique_savedsearchuserdefault_pr
 > sentry:0235_auto__add_projectbookmark__add_unique_projectbookmark_project_id_user_
 > sentry:0236_auto__add_organizationonboardingtask__add_unique_organizationonboardin
 > sentry:0237_auto__add_eventtag__add_unique_eventtag_event_id_key_id_value_id
 > sentry:0238_fill_org_onboarding_tasks
 > sentry:0239_auto__add_projectdsymfile__add_unique_projectdsymfile_project_uuid__ad
 > sentry:0240_fill_onboarding_option
 > sentry:0241_auto__add_counter__add_unique_counter_project_ident__add_field_group_s
Segmentation fault (core dumped)
```

**Comment by mattrobenolt** [comment]
That's definitely not supposed to happen. I'd suggest just retrying.

**Comment by AlexFinn** [comment]
Ok. To close issues is super!

```
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)

Synced:
 > django.contrib.admin
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.messages
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.staticfiles
 > captcha
 > crispy_forms
 > debug_toolbar
 > raven.contrib.django.raven_compat
 > rest_framework
 > sentry.plugins.sentry_interface_types
 > sentry.plugins.sentry_mail
 > sentry.plugins.sentry_urls
 > sentry.plugins.sentry_useragents
 > sentry.plugins.sentry_webhooks
 > south
 > sudo

Not synced (use migrations):
 - sentry
 - sentry.nodestore
 - sentry.search
 - social_auth
(use ./manage.py migrate to migrate these)
Running migrations for sentry:
 - Migrating forwards to 0245_auto__del_field_project_callsign__del_unique_project_organization_call.
 > sentry:0241_auto__add_counter__add_unique_counter_project_ident__add_field_group_s
 > sentry:0242_auto__add_field_project_forced_color
 > sentry:0243_remove_inactive_members
 > sentry:0244_auto__add_groupredirect
 > sentry:0245_auto__del_field_project_callsign__del_unique_project_organization_call
 - Loading initial data for sentry.
Installed 0 object(s) from 0 fixture(s)
Running migrations for nodestore:
 - Migrating forwards to 0001_initial.
 > nodestore:0001_initial
 - Loading initial data for nodestore.
Installed 0 object(s) from 0 fixture(s)
Running migrations for search:
 - Migrating forwards to 0002_auto__del_searchtoken__del_unique_searchtoken_document_field_token__de.
 > search:0001_initial
 > search:0002_auto__del_searchtoken__del_unique_searchtoken_document_field_token__de
 - Loading initial data for search.
Installed 0 object(s) from 0 fixture(s)
Running migrations for social_auth:
 - Migrating forwards to 0002_auto__add_unique_nonce_timestamp_salt_server_url__add_unique_associati.
 > social_auth:0001_initial
 > social_auth:0002_auto__add_unique_nonce_timestamp_salt_server_url__add_unique_associati
 - Loading initial data for social_auth.
Installed 0 object(s) from 0 fixture(s)
Creating missing DSNs
Correcting Group.num_comments counter
```

and after that I cannot create first user. Issue about it is closed already also

**Comment by mattrobenolt** [comment]
It looks like because of the segfault, the first migration didn't run correctly. I'd wipe the database and try again.

If things work correctly, you should absolutely be prompted to create first user during `sentry upgrade`

**Comment by AlexFinn** [comment]
I was conscious. I tried several times.
I know that I should be prompted to create first user. But...

**Comment by mattrobenolt** [comment]
Does it segfault every time in the same place? That seems suspicious, but I'm assuming something is bad with your environment and/or python. This isn't a problem with Sentry at this point though, unfortunately, and I'm not sure what advice to give other than something in your environment being broken.

**Comment by AlexFinn** [comment]
Ok. I will create new clean instance and will write results. Thanks.

**Comment by AlexFinn** [comment]
@mattrobenolt 
I'm sorry. It was my mistake. All works! Many thanks for your patience :)

**Comment by yourithielen** [comment]
Was Sentry still running when you ran `sentry upgrade`? This was my problem at least.

**Comment by scaryclam** [comment]
I had the same issue. Re-ran three times without restarting with a new database and it looks like it's failing after different number of migrations each time. Since the migrations before the segfault are applied, it starts further along in the migrations each time. I would suggest that this is more an issue with the version of Django itself rather than sentry.

**Comment by mattrobenolt** [comment]
@scaryclam That sounds like the process running out of memory and segfaulting. I've heard similar issues on people trying in real memory constrained environments.

**Comment by scaryclam** [comment]
Agreed. I'm on an environment with 1GB memory and a single core, so not *too* constrained but I also have a process running Java, which is making matters worse.

**Comment by mattrobenolt** [comment]
Oh, then I'm assuming that's your problem. :) This isn't something that Django or Sentry can work around. We need a reasonable amount of memory.
