### ISSUE TITLE
 Couldn't find a suitable DSN, defaulting to a Noop one

### ISSUE THREAD

**Issue by fatagun** [getsentry/sentry#3010]
I have a Java Client which I am following your [example ](https://docs.getsentry.com/hosted/clients/java/modules/raven/)and yet getting the error below even though I have the DSN copied from sentry. 

21 [main] INFO com.getsentry.raven.DefaultRavenFactory - Using an HTTP connection to Sentry.
50 [main] WARN com.getsentry.raven.dsn.Dsn - Couldn't find a suitable DSN, defaulting to a Noop one.
50 [main] INFO com.getsentry.raven.DefaultRavenFactory - Using noop to send events.

Also, I am having problems with log4j, logback and log4j2 clients. None seem to be sending any event to sentry.

I have the network packages checked by sysadmins on firewall, was told packages are going through but unable to view them in sentry. 

What might be the problem? Is there any sample java project I can put in my DSN and test out?

Thanks.

**Comment by tkaemming** [comment]
This is the wrong project for this issue — you want [raven-java](https://github.com/getsentry/raven-java).

This sounds like a configuration error. You'll want to make sure the configuration is specified correctly for whichever integration you are using. Without more details it's difficult to provide any additional help here.

There are sample projects in the [raven-java-examples](https://github.com/getsentry/raven-java-examples) repository that you can use to test your configurations with.

**Comment by pengboyin** [comment]
hi, I run the githup demo(log4j) is success, but the sentry server have no data, who can give me some proposal.
thanks

**Comment by mattrobenolt** [comment]
Would you mind posting this over at https://forum.sentry.io? GitHub Issues isn't really a good place for questions like that.

**Comment by pengboyin** [comment]
thanks for your response. and i have another  question, when i set  "raven.async=false", the sentry server can get error data, otherwise no error data, i do not know why?
