### ISSUE TITLE
Document clearly what data Sentry Cloud collects

### ISSUE THREAD

**Issue by AshStefanOltmann** [getsentry/sentry#30161]
### Problem Statement

I want to use Sentry Cloud for my app, but as a German company we need to make clear privacy statements about what Sentry does collect.

Unfortunately all your documentations like https://sentry.io/security/ does not describe which information from our app users is actually collected so that we can write a clear statement in our terms and conditions.

Even long outdated things like the Privacy Shield are mentioned, but nothing I actually need to know.

Here is another request I found that got no answer to this:
https://forum.sentry.io/t/customers-privacy-policy-section-what-data-is-collected-by-sentry/11702

### Solution Brainstorm

The Firebase Crashlytics documents on https://firebase.google.com/support/privacy describes clearly which information a message sent from the SDK to Googles server will contain:

```
    An RFC-4122 UUID which permits us to deduplicate crashes
    The timestamp of when the crash occurred
    The app's bundle identifier and full version number
    The device's operating system name and version number
    A boolean indicating whether the device was jailbroken/rooted
    The device's model name, CPU architecture, amount of RAM and disk space
    The uint64 instruction pointer of every frame of every currently running thread
    If available in the runtime, the plain-text method or function name containing each instruction pointer.
    If an exception was thrown, the plain-text class name and message value of the exception
    If a fatal signal was raised, its name and integer code
    For each binary image loaded into the application, its name, UUID, byte size, and the uint64 base address at which it was loaded into RAM
    A boolean indicating whether or not the app was in the background at the time it crashed
    An integer value indicating the rotation of the screen at the time of crash
    A boolean indicating whether the device's proximity sensor was triggered
```

It must not so technical and deep, but please write at least a statement what a crash report send to Sentry Cloud will contain on a high level (like UUID installation identifier, stack trace, latest log messages...) in an official document we can refer to.

Right now we may refer to your privacy policy, but the question which data are actually transferred is completely unanswered. At best you can show a sample crash log message.

**Comment by Kobby-Bawuah** [comment]
Hello, the customer configures Sentry SDKs and determines what data is sent to Sentry. We don't request or require any personal data to be sent in order for customers to use our application and performance monitoring solution. Typically the data sent to us is error and performance data about our customer's app. They can choose to use our scrubbers to remove personal data they have inadvertently sent and can also configure the SDKs so they don't send data at all. https://docs.sentry.io/platforms/dotnet/guides/uwp/data-management/sensitive-data/

**Comment by AshStefanOltmann** [comment]
Thanks for the hint for data scrubbing.

What I'm looking for is a list of fields with sample data that will get transfered if I use the Sentry standard configuration.

In the [Sentry forum](https://forum.sentry.io/t/customers-privacy-policy-section-what-data-is-collected-by-sentry/11702) someone listed the things he could see in the interface and asked if that's all that gets transferred:

```
    Error messages that occur while using the app
    Information about the use of the app immediately before the error occurred and when the app was started
    Date and time of the errors
    Device information: operating system and version, app version and device model
    identifier to to identify errors from the same device
    Status of the device: battery charge and temperature, charging state, boot time, memory space and connection type (Wi-Fi/mobile data), (free) storage space, preferred language, device orientation, screen resolution and density, time zone
    IP address of the machine (when the connection is established)
```

My requst is to add a chapter to the privacy policy similar to what Crashlytics did.

I imagina something like 
```
A Sentry error message contains this fields:
-A 
-B
-C
```

**Comment by Kobby-Bawuah** [comment]
Hello @AshStefanOltmann, thanks for the heads up. We are currently not going to rewrite our existing policies at this time. Our policies do describe the information we collect from our customers (registration data). The data we process in the service is dependent on our customer's configuration of the SDK so we can't actually speak to what they are choosing to send us.

**Comment by AshStefanOltmann** [comment]
Hi @Kobby-Bawuah ,

unfortunately I don't know what I'm sending to you.

I set up Sentry the default way:
```
Sentry.init { options ->
  options.dsn = "<thednspath>"
  options.release = AppBuildConfig.APP_VERSION
  options.setDebug(true)
}
```

I log my exceptions this way:
```
fun sendToCrashLogger(
    message: String,
    throwable: Throwable? = null
) {

    Sentry.addBreadcrumb(message)

    throwable?.let {
        Sentry.captureException(it)
    }
}
```

Pretty standard I guess.

So what I actively send you is this:
- My current app version
- A log message that I wrote
- A stack trace

In the UI frontend I see in addition:
- Date and Time
- Platform (for e.g. "java")
- Runtime (for JVM, eg. "AdoptOpenJDK 15.0.2")
- A "server_name"

In the JSON log there is also the used Sentry version.

What else do you log?

Do you promise that the JSON file I can download per issue contains all and everything you log?
Or is there anything else?
What's about the client IP address? How do you handle that?

Because of GDPR it's really important to know and understand what is sent.

**Comment by AshStefanOltmann** [comment]
I also see in fact a huge difference in what is captured by the Java and the Cocoa plugin.

Why does the Cocoa plugin record and store an IP address and the Java plugin does not?

Reading your docs I admire that you have defaults that prevent the capturing of sensitive personal identifiable information.

So I think my suggestion here is just to put up a side that describes which fields are captured in standard configuration.

Of course I could assemble such a list just from what I can see in the UI and assume that this is all data you have...

But wouldn't it be easier if you had such a page per platform describing what the default configuration stores at fields and in my privacy policy I can tell my users what fields I turned off?
