### ISSUE TITLE
Embedded error page endpoint is not derived from the DSN.

### ISSUE THREAD

**Issue by elliotcourant** [getsentry/sentry#30249]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Request the embedded error page from a relay server, eg: `https://relay.monetr.app/api/embed/error-page/?dsn=...`
   The relay will forward this request to sentry.io. Note: The DSN has `relay.monetr.app` as the domain.
2. The resulting script returned will have the following endpoint:
   ```javascript
   var endpoint = /**/"https://sentry.io/api/embed/error-page/?dsn=..."/**/
   ```

This is caused by this code:

https://github.com/getsentry/sentry/blob/c80434508667a10b61c4edba1b962b0c1b3fe0e2/src/sentry/web/frontend/error_page_embed.py#L211

Because `absolute_uri()` derives the base domain/protocol from the configuration for sentry, not from the DSN; the resulting script does not use the relay and instead tries to talk to sentry directly.

My `Content-Security-Policy` has this `connect-src 'self' https://relay.monetr.app` and I'd like to keep it that way if possible. 

### Expected Result

The resulting script from `/api/embed/error-page` should derive the base domain from the DSN provided, rather than always assuming it will be from the config.

### Actual Result

The `/api/embed/error-page` always uses the config to derive the domain, which results in issues when trying to only talk to sentry through the relay.

**Comment by markstory** [comment]
Thanks for the feedback on this. Getting the error page to be delivered from relay is a big change.

**Comment by billyvg** [comment]
Based on what mark said, this is not something we're going to change. As an alternative you can check out our new [User Feedback integration](https://docs.sentry.io/platforms/javascript/user-feedback/) that should work with your relay

**Comment by elliotcourant** [comment]
I'll give that a try, thank you all very much!
