### ISSUE TITLE
Support new `sections: ` spec (index maps) in sourcemaps for javascript

### ISSUE THREAD

**Issue by nikki93** [getsentry/sentry#3025]
Hi!

I'm using sentry for a react-native project. react-native runs babel (a JS transpiler) on each file in your project before combining them into one big bundle. When you transform each file, babel gives you a source map for each one, so that mapping needs to be incorporated into the final mapping that combines all the transformed files. react-native currently achieves this using 'index maps': https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?pref=2&pli=1#heading=h.535es3xeprgt

The current implementation that the source map isn't an index map since it always asks for the `mappings` key in the JSON object before checking for the `sections` key: https://github.com/getsentry/sentry/blob/master/src/sentry/lang/javascript/sourcemaps.py#L63

An example implementation that does support index maps is the mozilla one, which checks for `sections` before choosing between whether to assume index or basic maps: https://github.com/mozilla/source-map/blob/master/lib/source-map-consumer.js#L20

An alternative is to 'flatten' the index source maps as presented here: https://github.com/DavidSouther/flatten-source-map

We are quite interested in using sentry for error reporting on https://exponentjs.com/ apps, and it's been a great experience so far! Let me know if you need more information.

**Comment by nikki93** [comment]
Can confirm that using https://github.com/DavidSouther/flatten-source-map makes it work with sentry, but would be nice to have index source maps directly supported by sentry.

**Comment by ehfeng** [comment]
Looks to be a duplicate of https://github.com/getsentry/sentry/issues/3025

Close?

**Comment by nikki93** [comment]
@ehfeng I'm guessing you mean #3224 but yup, it's a duplicate! I'll close this one.
