### ISSUE TITLE
Sentry is generating huge load then for event with "Remote file too large for caching" error

### ISSUE THREAD

**Issue by xor-ai** [getsentry/sentry#30255]
### Environment

self-hosted (`onpremise` deployment)

### Version

21.8.0

### Steps to Reproduce

It happened one in our production. And cost us a lot of money.

November 25, 12 PM UTC we noticed a huge spike in our CDN traffic.
![image](https://user-images.githubusercontent.com/91734686/143879454-f6b5d1b0-0fc9-4b91-b9cf-0309c77ce731.png)
![image](https://user-images.githubusercontent.com/91734686/143879470-9fc548b0-b154-4330-8871-beb234837d08.png)

Our investigation resulted in the following:
![image](https://user-images.githubusercontent.com/91734686/143882141-8551a4ec-558f-4520-aa86-40c6d89463d1.png)

One of the application JS files was requested enormously. And the requester was sentry:
![image](https://user-images.githubusercontent.com/91734686/143879828-d80ae14f-5cb1-4489-961d-778ac415b192.png)

It was ongoing for 5 hours in a row resulted in 3.5Tb of data transferred. 
![image](https://user-images.githubusercontent.com/91734686/143879970-24222cd6-3c19-4fd7-a6ec-7b2ed402b56f.png)

It started here:
![image](https://user-images.githubusercontent.com/91734686/143880123-b73c1ab0-28f4-4b0c-a057-53cd9cbeec29.png)
From our on-premise sentry IP: *.*.102.173
![image](https://user-images.githubusercontent.com/91734686/143882391-f61fa01b-d1b5-4789-9860-696878d9651b.png)

We have correlation with Events in sentry:
![image](https://user-images.githubusercontent.com/91734686/143880338-7fe8b6c0-572b-410d-bc0e-a7a8c896919e.png)

And here is the event itself:
![image](https://user-images.githubusercontent.com/91734686/143882696-5799f65f-d303-4ec3-ace4-44f797847be8.png)

It looks like Sentry was constantly trying to fetch this resource at an enormous rate  700 000 times.  It really looks like a defect in the Sentry codebase. It did cost us around 600E (with VAT):
![image](https://user-images.githubusercontent.com/91734686/143881020-bd02fe86-e1fa-4721-af06-ef76a006d03b.png)

Is there any way to limit unsuccessful requests (retries) count or something like that? Or better fix this on the Sentry side. 

### Expected Result

Sentry is not sending hundreds of thousands of requests if it fails to load remote files.

### Actual Result

Sentry makes too many retry attempts for a failed remote file fetch.

**Comment by markstory** [comment]
You can generally avoid these requests entirely by uploading source maps to releases.

**Comment by xor-ai** [comment]
Thanks, we already disabled source fetching. While considering an option to upload source maps. 
Yet, this behavior does not look right.
What kind of details do you need? Sentry logs for period?

**Comment by markstory** [comment]
> Yet, this behavior does not look right.

What behavior is not correct?

>  What kind of details do you need? Sentry logs for period?

Sorry I had to edit my comment and left a note of the edit I made.

**Comment by xor-ai** [comment]
> What behavior is not correct?

Yes, generating 700 000 download requests for events and downloading 3.5 Tb of data is not correct behavior.  If we look at the events chart we can see 4000 events of the same kind. Let's suppose each of them had the same "too large for caching" issue.
That means Sentry made 700 000 / 4 000 = 175 retry attempts for each event. Without any timeout. Network traffic is not free at all. For us, it was 3.5 terabytes of data moved from CDN. And 1.6 Gb/s channel overuse. That is definitely not correct.
I do not know what happened internally in the Sentry. But from my expectation, Sentry had to make 3 retry requests at most and stop. I still wonder why it stopped after 5 hours race. It could easily continue retrying, resulting in a much higher loss for us.

**Comment by xor-ai** [comment]
I'm trying to find the reason why it happened, but unsuccessfully. After a quick acquaintance, I did not find retry policies or anything like that. But I'm not an expert neither in Sentry, nor in Python. I can see the fetching code, but no clue how that happened.  It definitely does not happen every time. We had this event (same file) before, we have it later. And everything is ok. But something went wrong this day. And since it happened, it is possible to happen later, maybe not in our environment but for another client/user.

**Comment by markstory** [comment]
> Generating 700 000 download requests for events and downloading 3.5 Tb of data is not correct behavior. If we look at the events chart we can see 4000 events of the same kind. Let's suppose each of them had the same "too large for caching" issue.

I agree that's not great behavior. There is logic that flags a domain as one Sentry should not fetch source code/source maps from, but that relies on cache as well. If your cache is full and evicting keys the application is no longer able to track that it shouldn't make requests to a domain and future events that are processed will attempt to fetch source & source maps. Do you know if the cache your Sentry instance may have gotten full or started to evict keys?

**Comment by xor-ai** [comment]
That is what I do not know, not logging for this. I've checked sentry worker logs. It has tons of records like these:

2021-11-25 11:59:59	
2021-11-25T11:59:59.151038755Z stdout F 11:59:59 [WARNING] sentry.http: source.disabled (type='too_large_for_cache' url='https://******.ai/main-es2015.97045e0595cbd6f25bd6.js')
2021-11-25 11:59:59	
2021-11-25T11:59:59.112783082Z stdout F 11:59:59 [WARNING] sentry.http: source.disabled (type='too_large_for_cache' url='https://******.ai/main-es2015.97045e0595cbd6f25bd6.js')
2021-11-25 11:59:59	
2021-11-25T11:59:59.193602093Z stderr F   InsecureRequestWarning)
2021-11-25 11:59:59	
2021-11-25T11:59:59.193599693Z stderr F /usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-11-25 11:59:59	
2021-11-25T11:59:59.193595592Z stderr F   InsecureRequestWarning)
2021-11-25 11:59:59	
2021-11-25T11:59:59.193593292Z stderr F /usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-11-25 11:59:59	
2021-11-25T11:59:59.193590892Z stderr F   InsecureRequestWarning)

And it all started with "InsecureRequestWarning: Unverified HTTPS request is being made" error.

**Comment by markstory** [comment]
Those logs look like the requests to get source code/source maps. You would need to look at the metrics/logs for your memcache instance or whatever you're using for the default caches.

**Comment by xor-ai** [comment]
I do not see any related logs in the sentry Redis cache for this timeframe. There are logs, but nothing related to the error. Just information.

**Comment by chadwhitacre** [comment]
Closing this as stale. Please open a new issue if need be.
