### ISSUE TITLE
Sentry 8.3.1 Deprecating `SECRET_KEY` in sentry.conf.py make it hard to load it from environment variable

### ISSUE THREAD

**Issue by ye** [getsentry/sentry#3028]
Getting the below warning while installing a brand new Sentry 8.3.1 with MySQL. According to the docs, `SECRET_KEY` along with a handful of other parameters have been deprecated in `sentry.conf.py` and in favor of `config.yml` YAML configuration file. However, it also make it hard to be able to [pass the secret at run time to the sentry docker container as an environment variable](https://github.com/getsentry/docker-sentry/blob/672a98fdbf4e1ccecfbebc9cacb4438e8209f58f/8.3/sentry.conf.py#L250)

Any suggestions of how to pass SECRET_KEY as an environment variable while not triggering this warning?

![screen shot 2016-04-08 at 3 13 33 pm](https://cloud.githubusercontent.com/assets/133924/14394892/88c08ca8-fd9c-11e5-9940-1f11eeb56119.png)

**Comment by mattrobenolt** [comment]
See: https://github.com/getsentry/docker-sentry/blob/master/8.3/sentry.conf.py#L262

All of these can be shoved into a `SENTRY_OPTIONS` dictionary which maps exactly to config.yml. In the case of our docker container, this is what we do. The alternative is to generate the config.yml from a template and compile in your env vars, but `SENTRY_OPTIONS` is sufficient in our case.

**Comment by ye** [comment]
@mattrobenolt thanks for the suggestion. It appears that I might have taken an old template of `sentry.conf.py` somewhere in the sentry repo rather than the docker-sentry repo. 

Can you clarify this following statement?

>  All of these can be shoved into a SENTRY_OPTIONS dictionary which maps exactly to config.yml. In the case of our docker container, this is what we do.

I don't care much about how internally secret key is named, be it `SECRET_KEY` or `SENTRY_OPTIONS['system.secret-key']`, as long as it's still taking environment variable as a way then it's fine. In other words, would this following line goes away in the future?
https://github.com/getsentry/docker-sentry/blob/master/8.3/sentry.conf.py#L250

**Comment by mattrobenolt** [comment]
>  In other words, would this following line goes away in the future?
https://github.com/getsentry/docker-sentry/blob/master/8.3/sentry.conf.py#L250

No. Sentry itself doesn't respond do these environment variables, which is why docker-sentry has this shim to read env vars and put them in their right places. In our container, we look for the `SENTRY_SECRET_KEY` env var (which Sentry knows nothing about)`, and just translates it into `SENTRY_OPTIONS['system.secret-key']`. This is equivalent to using `system.secret-key` in `config.yml`.

**Comment by ye** [comment]
Makes sense. Thanks!
