### ISSUE TITLE
Uploading source code + source map for react-native project

### ISSUE THREAD

**Issue by jlo1** [getsentry/sentry#3034]
When logging an event in a release build, the event title is something like `<errormessage>@file:///var/containers/Bundle/Application/<someid>/<myapp.app>/main.jsbundle`.

And all the messages from the stack trace follow similar patterns. I've uploaded the release artifacts `main.jsbundle` and `index.ios.map` (tried using `/main.jsbundle` and `/var/containers/Bundle/....../main.jsbundle` paths). But I'm still getting an unclear source map. How do I correctly add the source code and source map?

**Comment by benvinegar** [comment]
The Raven.js React Native plugin is supposed to strip/normalize `<someid>` paths: https://github.com/getsentry/raven-js/blob/master/plugins/react-native.js#L18

But I can see you have a different path. What version of iOS / React Native are you using?

Note that, in the mean time, you can supply your own path-stripping regex to plugin by specifying `pathStrip`: 

https://github.com/getsentry/raven-js/blob/master/plugins/react-native.js#L54

**Comment by Kerumen** [comment]
I have the latest React Native version (0.26) and iOS 9.3.2 and I get the same path:
```
/var/containers/Bundle/Application/173B9DA8-E916-4F26-9749-BA7A9283B584/[myAppName].app/main.jsbundle
```

Maybe I can send a PR to update to the last path?

**Comment by EricWithCare** [comment]
I see this problem too, the path isn't being normalized and so I get a 
`Source code was not found for /var/containers/Bundle/Application/1EBE6535-304A-4607-995A-0A2EF15C39FA/XXXXXX.app/main.jsbundle` error when viewing the event. I'm using `React-Native 0.34.1` and `Raven-JS 3.7.0`. 

Any ideas?

**Comment by ajwhite** [comment]
This is causing a problem for us as well. All crashes come in with the full bundle path, `/var/containers...`

Is there something we have to do specifically to normalize this to `/main.jsbundle`?

**Comment by benvinegar** [comment]
Since this issue opened, we launched [a dedicated React Native client library for Sentry](https://github.com/getsentry/react-native-sentry).

Closing this – please open any issues re: React Native on react-native-sentry instead.
