### ISSUE TITLE
Handle a 400 Bad Request better

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3048]
Right now, this behavior is piggy backed from builtin Django, based on `settings.ALLOWED_HOSTS`, but this is super confusing for our users since it provides nothing useful except "it's broken".

We should stop using this builtin behavior and do something better with potentially a better error message to indicate "Check your `system.url-prefix` setting" or something.

Not entirely sure, but there's options here and we frequently help users with this issue.

**Comment by dmclain** [comment]
The path that is rendering the `Bad Request (400)` is `django.views.defaults.bad_request` by setting `handler400` to a different view function the rendering can be easily overriden. The exception is the second argument to the view, so singling out `django.core.exceptions.DisallowedHost` should be simple

see https://docs.djangoproject.com/en/1.9/ref/urls/#handler400

**Comment by mattrobenolt** [comment]
Oh, this is new in Django 1.6. Yeah, it might be easier to just tap into that then. Thanks for the heads up. :) I obviosuly didn't do much research here yet.
