### ISSUE TITLE
Add data scrubbing reasons to event detail display.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#3050]
We've received many questions over the support channels for hosted Sentry about why certain fields were filtered out on ingestion. Since we don't have the data (it's filtered, obviously), we can't provide a conclusive answer about what caused the data to be redacted. In many cases, we can provide reasonable guesses due to context, but it would be helpful to record the reason why the field was redacted at the time the decision is made.

There are a few ways we could display this data:
1. We add a tooltip next to filtered fields that includes information why the field was stripped, e.g. "This data was scrubbed since it included content that looked like a credit card number." or "This data was scrubbed since it included the string "password".", etc. This would probably be the least invasive and most descriptive option, but would require some design decision and potentially API changes.
2. We could show this above the issue, similarly to the [`EventErrors` component](https://github.com/getsentry/sentry/blob/f150beecf5a24cbc2ec8d33cd9a1d054af441994/src/sentry/static/sentry/app/components/events/eventEntries.jsx#L96-L100). This would probably be the easiest implementation, but least useful.
3. We could replace the [`FILTER_MASK` constant](https://github.com/getsentry/sentry/blob/f150beecf5a24cbc2ec8d33cd9a1d054af441994/src/sentry/constants.py#L195) with something that includes the reason for scrubbing, e.g. `[Filtered: Field included "password".]` or `[Filtered: Field included credit card.]`, etc.

**Comment by dcramer** [comment]
I like the idea of having more details, but I personally like how EventError works because its an enum. If we can do a similar thing to make it very compact to store filtering errors im definitely +1.

Also might be worth considering if we can do something similar for trimmed data since its a similar issue.

**Comment by tkaemming** [comment]
> I like the idea of having more details, but I personally like how EventError works because its an enum. 

Yeah, my worry with this approach is that since the notification would be shown away from the data, we'd only be able to say "Some data was filtered because it appeared to have credit card information." which isn't super helpful if you triggered multiple filters. (It'd be better than no information at all, though.)

> Also might be worth considering if we can do something similar for trimmed data since its a similar issue.

This is a good idea, totally agree.

**Comment by tkaemming** [comment]
I spoke with @dcramer a bit about this yesterday, and we kicked around the idea of adding the ability to "annotate" variable values with additional data. Adding annotations would let us implement the first option above (tooltips next to filtered values) as well as some other features we've talked about, such as better messaging about data that was replaced because it was invalid or trimmed. Another related idea is the ability to add type annotations — this would be especially helpful some other runtimes such as the JVM. You could make a reasonable argument about it's usefulness in Python, too, when `repr()` methods can return potentially ambiguous results.

If we wanted to take this approach, I've settled on a couple options that seem reasonable:

1. **Expand the values of the stack frame `vars` mapping to be an object that includes the value representation, as well as slots to include additional annotations, such as warnings or type information.** For example, `u'value'` would become `{"value": "u'value'", "type": "unicode", "warnings": []}` or similar. For filtered data, this could become something along the lines of `{"value": null, "type": "unicode", "warnings": ["This value was removed since it contained the string 'password'."]}`. (These are just for examples of how the types would change — please don't get caught up in implementation details quite yet about how the error messages are structured, or attribute names, etc.) This is probably the most straightforward approach, but has a few drawbacks:
  - It only allows annotating the entire variable. For filtering, we would only be able to annotate the top-level value of any composite data type, and not any of the children, so if multiple child fields are filtered for different reasons, this introduces some ambiguity. If we wanted to use this to provide type annotations (e.g. for JVM languages), we'd only be able to provide them for the "main" data type as well.
  - Any values that are repeated will across stack frames will need to be rendered in their entirety multiple times.
2. **Replace the `vars` mapping's values with reference addresses to values in another mapping that contains their values.** This is a bit hard to explain, so I threw together a simple example of how encoding and decoding would work in [this gist](https://gist.github.com/tkaemming/303f0761723801f350b92345a53a46e2). (It doesn't support circular references, since I'm ignoring type annotations at the moment that the rewriting happens on the server purely to add metadata to values. Implementing circular reference support is reasonably straightforward, and might be a good idea if this is implemented on the client.) The main drawback of this approach is it adds a non-negligible amount of complexity. There are also several advantages, though:
  - We'd be able to notate fields at any level in composite data types. If we want to add type annotations, this seems almost like it'd be a hard requirement.
  - Any values that appear repeatedly in the payload only need to be stored once. This could also be a drawback if values *don't* occur repeatedly, since we'll be adding some additional bytes to the payload to store the value's reference address twice — once in the value mapping, and once in the location that it's actually referenced from. Depending on how these reference addresses are generated, they could get quite large. (If we really wanted to, we could optimize this by counting each time a variable is referenced during encoding, and if it's infrequently referenced, inlining it like in the first option above — sort of a hybrid approach. This obviously adds another layer of complexity.) 
  - Since these values are unique by definition in the value mapping, transforming them — like during scrubbing — only has to process each unique value once, rather than the recursive implementation that we use today.
  - If we wanted to store large values (e.g. POST bodies) separate from the report itself, having this "reference address" abstraction would provide a much simpler starting point for that work. (I think there may have been talk about this in the past, but I might just be making this up because I think it sounds cool.)

This would be a fairly substantial change. Either of these approaches will require:

1. front-end changes (rendering will have to account for this data either way),
2. storage changes (data will have to be upgraded from the old format to the new format on ingestion and on retrieval of old data; we might need to provide a downgrade path as well if we're concerned about maintaining API compatibility),
3. *potential* external ingestion interface changes (if we want to allow clients to provide custom annotations, such as type annotations.)

**Comment by dcramer** [comment]
I think the encoding is confusing as hell, but its the only reasonable solution as far as I can tell.

I think we could focus on the mapping which gives us:

1. dedupe
2. the ability to add filter/truncation annotations

I think type annotations are a future thing we can care about.

**Comment by mattrobenolt** [comment]
A couple things to reiterate what we discussed in person:

* It'd be nice to have filtering applied on a per-interface basis, rather than blanket applied everywhere to every field possible. For example, it's common to get `User-Agent` filtered because someone wanted to filter `user`. Have per-interface rules would allow each interface to define potential fields that are not to be scrubbed, etc. It could also make things more efficient on interfaces that require no scrubbing at all, say the `User` interface or `Csp`.

* Right now, our filter rules aren't very flexible. We always do a "contains" match, which is unintuitive in some cases, and undesirable in others. For example, if you wanted to filter the field "cc", that means you'd also be filtering the HTTP "Accept" header since "cc" is present in it. We should support some primitive glob matching, so you could do `cc`, `*cc*`, `cc*`, `*cc`. I don't think it's worth a full regex since those could be uncontrollably expensive.

* The value of the data being filtered could be a little bit smarter. For example, today, one of the checks we do is for a password that exists within a URL. So we take `http://foo:bar@example.com`, and turn it into `http://foo:[Filtered]@example.com`. It'd be nice to be able to apply rules similar to this on other values. Like, potentially the CC# scrubber goes to "***1234" and retains the last 4 digits. This way we can scrub values so they're still useful, while still removing the dangerous bits. Another example would be an HTTP Authorization header. Maybe we retain the `username` piece of the Basic auth, etc.

Turns out, these are slightly off topic from the original issue, but relevant.

**Comment by tkaemming** [comment]
So, before committing to moving forward with this, I have a few concerns.

With the new format (including type information, as well as an empty annotations list), the compresed size is an ends up increasing the file size by somewhere around 15%.

```
8639	9056	104.83%	2507	2660	106.10%
32167	29046	90.30%	5528	6422	116.17%
22950	27132	118.22%	5448	6414	117.73%
7382	8858	119.99%	2184	2567	117.54%
10673	12101	113.38%	2703	3088	114.24%
14766	18375	124.44%	3890	4708	121.03%
14765	18374	124.44%	3877	4703	121.31%
9503	11488	120.89%	2651	3136	118.29%
```

To avoid requiring us to store more data to make this change, I also tried to split up the payload into two separate chunks — one for the shared data, and the unique data. This seems promising. The below data (for the same sample of events) shows:

- original data size
- shared data size
- % of shared data / original data
- unique data
- % of unique data / original data
- … and then the same sequence repeated after compression.

```
8639	3220	37.27%	6394	74.01% 2507	1085	43.28%	1883	75.11%
32167	14771	45.92%	14729	45.79% 5528	3256	58.90%	3508	63.46%
22950	11700	50.98%	15620	68.06% 5448	2955	54.24%	3786	69.49%
7382	3129	42.39%	5975	80.94% 2184	1072	49.08%	1763	80.72%
10673	5280	49.47%	6803	63.74% 2703	1725	63.82%	1790	66.22%
14766	7657	51.86%	11324	76.69% 3890	2088	53.68%	2869	73.75%
14765	7657	51.86%	11392	77.16% 3877	2088	53.86%	2887	74.46%
9503	5022	52.85%	6856	72.15% 2651	1411	53.23%	1932	72.88%
```

This seems like a generally reasonable approach as far as storage goes, but I am a little worried about the complexity — this means we'll have to stitch the payload back together from two different files, and also maintain a mapping of what fields are shared and what fields are unique for each attribute across all interfaces. (For an example, check out [this part of the gist](https://gist.github.com/tkaemming/303f0761723801f350b92345a53a46e2#file-split-py-L81-L109).)

Due to the way these components are interleaved (only `vars

**Comment by tkaemming** [comment]
So, before committing to moving forward with this, I have a few concerns.

With the new format (including type information, as well as an empty annotations list), the compresed size is an ends up increasing the file size by somewhere around 15%.

```
8639	9056	104.83%	2507	2660	106.10%
32167	29046	90.30%	5528	6422	116.17%
22950	27132	118.22%	5448	6414	117.73%
7382	8858	119.99%	2184	2567	117.54%
10673	12101	113.38%	2703	3088	114.24%
14766	18375	124.44%	3890	4708	121.03%
14765	18374	124.44%	3877	4703	121.31%
9503	11488	120.89%	2651	3136	118.29%
```

To avoid requiring us to store more data to make this change, I also tried to split up the payload into two separate chunks — one for the shared data, and the unique data. This seems promising. The below data (for the same sample of events) shows:

- original data size
- shared data size
- % of shared data / original data
- unique data
- % of unique data / original data
- … and then the same sequence repeated after compression.

```
8639	3220	37.27%	6394	74.01% 2507	1085	43.28%	1883	75.11%
32167	14771	45.92%	14729	45.79% 5528	3256	58.90%	3508	63.46%
22950	11700	50.98%	15620	68.06% 5448	2955	54.24%	3786	69.49%
7382	3129	42.39%	5975	80.94% 2184	1072	49.08%	1763	80.72%
10673	5280	49.47%	6803	63.74% 2703	1725	63.82%	1790	66.22%
14766	7657	51.86%	11324	76.69% 3890	2088	53.68%	2869	73.75%
14765	7657	51.86%	11392	77.16% 3877	2088	53.86%	2887	74.46%
9503	5022	52.85%	6856	72.15% 2651	1411	53.23%	1932	72.88%
```

This seems like a generally reasonable approach as far as storage goes, but I am a little worried about the complexity — this means we'll have to stitch the payload back together from two different files, and also maintain a mapping of what fields are shared and what fields are unique for each attribute across all interfaces. (For an example, check out [this part of the gist](https://gist.github.com/tkaemming/303f0761723801f350b92345a53a46e2#file-split-py-L81-L109).) This seems like it could break easily by accident.

Due to the way these components are interleaved — for example, only the `vars` attributes of the stack frames are extracted into the new types, but the entirety of extra data is — I'm a little also a little worried about keeping the backend and frontend in sync.

I still think both of these ideas are generally good, but I didn't want to start building them without bringing this stuff up first.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
