### ISSUE TITLE
Clarify license conditions when self hosting.

### ISSUE THREAD

**Issue by CrashyBang** [getsentry/sentry#3051]
I noticed on your pricing page: https://getsentry.com/pricing/ that while it indicates sentry is completely open source the On-Premise plan comes with a cost: "On-Premise Starts at $999/mo".

I was just wondering is On-Premise separate from self hosting? Am I allowed to set this up on my own little in house server with the license? Or is there a fee attached? Sorry if this is a stupid question I did read the license in the repo but the pricing page threw me.

Cheers,
Otis.

**Comment by dcramer** [comment]
The license for Sentry is what you think. Our On-Premise pricing is for our commercial support offering.

**Comment by Achillesxu** [comment]
> The license for Sentry is what you think. Our On-Premise pricing is for our commercial support offering.
it means that self-hosted is free?

**Comment by dcramer** [comment]
I'm locking this thread. Please look at the license to understand if you can run it. We no longer sell any on-premise support, and this thread is 4 years old.
