### ISSUE TITLE
[Doc] Weird command to run server

### ISSUE THREAD

**Issue by hongquan** [getsentry/sentry#3067]
This section https://github.com/getsentry/sentry/blob/d046263c55f861c4d3093ab7110f84464023b2b3/docs/performance.rst#web-server

suggests the command to run uWSGI

```
command=newrelic-admin run-program /srv/www/getsentry.com/env/bin/uwsgi
```
I think NewRelic here is not necessary and not everyone understand.

**Comment by mattrobenolt** [comment]
This page is entirely out of date and these are mostly wrong. I'll update. Thanks for bringing it to our attention. :)
