### ISSUE TITLE
Add a `sentry init --dev` command

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3073]
This should spit out a similar, but slightly different config tuned for local development.

Basically, the changes should be:

* set `DEBUG = True` in `sentry.conf.py`.
* set `mail.backend` to something more sensible, probably `console` is a sane default since most people aren't running local SMTP servers in `config.yml`
* set `CELERY_ALWAYS_EAGER = True` on `sentry.conf.py`
* Prefill stuff in `SENTRY_FEATURES`?

Thoughts? @getsentry/team What else do you do in your local config to make things work reasonably.

**Comment by JTCunning** [comment]
Maybe (maybe) a preference to sqlite if it's installed and/or on?

**Comment by dcramer** [comment]
-1 on CELERY_ALWAYS_EAGER, it causes recursion issues and should not be promoted (especially with --workers)

**Comment by mattrobenolt** [comment]
> Maybe (maybe) a preference to sqlite if it's installed and/or on?

I think we're trying to get away from using sqlite at all since our code pretty much depends on Postgres at this point. Generally sqlite is fine, but we don't really want to encourage it since it'll likely cause issues with certain things.

**Comment by dcramer** [comment]
we removed support for all dbs that aren't Postgres (including sqlite) so -1

**Comment by mattrobenolt** [comment]
> 1 on CELERY_ALWAYS_EAGER, it causes recursion issues and should not be promoted
I've never had a single issue. Was this an issue a while back, or is this currently an issue? Or am I just lucky and have never hit an issue?

> (especially with --workers)
Yeah, I agree it's much less of an issue now that it's easier to spawn all the workers. Maybe we also make `--workers` default? and you have to opt out with `--no-workers`?
