### ISSUE TITLE
Organisational switch test has missing comma resulting in the 404 page being tested

### ISSUE THREAD

**Issue by code-review-doctor** [getsentry/sentry#30911]
The organisational switch test does not work as intended because there is implicit string concatenation on line 54
https://github.com/getsentry/sentry/blob/1e4daba640a3929cb49fc749822711cdfed2efb5/tests/acceptance/test_organization_switch.py#L52-L55

There is a comma missing between `"releases"` and `"discover"` resulting in the two being implicitly concatenated together to form  `"releasesdiscover"`.

The impact is the test requesting `"/releasesdiscover"` which does not exist, and so instead of "/releases" and "/discover" being tested, instead the 404 page is tested.

### Expected Result

Add the missing comma i.e., 
`["issues", "releases", "discover", "user-feedback"]`

### Actual Result

NA

I will create a PR to fix this for you :)

**Comment by Kobby-Bawuah** [comment]
@markstory
