### ISSUE TITLE
Interface fragment identifier URLs on GroupDetails don't scroll browser window on load

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3095]
If you just paste a full URL to group details w/ a fragment identifier (e.g. #exception) into your address bar, and hit enter, the page will not scroll to the appropriate section.

Example URL:

```
http://127.0.0.1:8000/sentry/internal/issues/861/#exception
```

We need some code that, after GroupDetails mounts, looks at the fragment and scrolls to that section.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
