### ISSUE TITLE
Race condition causes assignment drop-down to be empty.

### ISSUE THREAD

**Issue by jlafleche** [getsentry/sentry#3097]
I maintain an on-premises deployment of Sentry. About 50% of the time, the assignee drop-down is blank:

<img width="283" alt="screen shot 2016-04-21 at 4 45 37 pm" src="https://cloud.githubusercontent.com/assets/13784646/14727524/a4f0dbc8-07e0-11e6-8067-4613a49f26c2.png">

This seems intermittent, and I find that if I try to step through the code in the Chrome debugger, the issue happens less frequently.  Seems like a race condition - the members API is always returning the right data, so I suspect this is a front-end issue.

We are running version 8.1.2.

**Comment by billyvg** [comment]
Closing in favor of #4434
