### ISSUE TITLE
Grouping by Levenshtein distance

### ISSUE THREAD

**Issue by trueinsider** [getsentry/sentry#3099]
There is times when we don't have control over how events will be sent to Sentry (how messages will be logged). Worst case is there'll be different events for same message with different parameters because of `log.error("user " + user + " did smth wrong")` as opposed to `log.error("user %s did smth wrong", user)` (let's call them wrongly-parametrized). Instead of simply grouping them by that message (which is different almost every time) something more intelligent is possible: for example, calculating Levenshtein distance with all other wrongly-parametrized messages and applying some threshold to match them together or creating new group. Or something more simple: first N words match percentage is over some threshold means same group. Or ability to write your own matcher.

**Comment by dcramer** [comment]
I agree it would be nice to be able to do this kind of thing, but (and hear me out):

Sentry isn't logging.

We work on structured data, specifically errors, and more importantly exceptions. There is absolutely value in capturing non-exception errors, but its often easy to manipulate those into a usable solution in Sentry (especially with our powerful API).

More importantly doing something like a streaming computation against the towards-infinite amounts of data that come into Sentry just isn't practical. Especially when we can solve the common (and our targetted) use case with simply preparsing the data. To put this into a more illustrative example, what do you do if you receive 1,000 errors/second? Do you say "only check the last N"? What if those 1k were the same? What if they were all unique? What if your matching took 1000% more CPU and 10000% more network to compute? 

In the end, Sentry sticks with what it knows, and what it knows are exceptions, and more importantly structured data.
