### ISSUE TITLE
[Question] Sentry version

### ISSUE THREAD

**Issue by fatagun** [getsentry/sentry#3100]
Hello,

Where can i learn the current version of sentry? Currently we are running 8.2.2.

I d like to find out the current release version as well as the changes since a version. 

is this possible?

Thanks.

**Comment by dcramer** [comment]
We release a new version of Sentry once a month. The current version is 8.3 (which is what's listed on pypi.python.org).

https://docs.getsentry.com/on-premise/server/changelog/
