### ISSUE TITLE
Sentry is down?

### ISSUE THREAD

**Issue by mrnonz** [getsentry/sentry#31131]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Just go to https://sentry.io/

and this show message

```
no healthy upstream
```

### Expected Result

Normal web portal.

### Actual Result

Got `no healthy upstream`

<img width="341" alt="Screen Shot 2565-01-14 at 09 54 41" src="https://user-images.githubusercontent.com/9113726/149443989-f6fdc9b5-ab5b-42ea-b441-90106a6dafc7.png">

**Comment by dominickwok** [comment]
+1

**Comment by souredoutlook** [comment]
Back up! Thanks for flagging. 

[Status update if you're curious.](https://status.sentry.io/incidents/55f49f1v81w0)
