### ISSUE TITLE
Improve Content Handling for Copy-as-curl

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#3114]
Currently when data is available but truncated copy as curl is a bit pointless. We should probably improve this were you can copy as curl without payload.

**Comment by mitsuhiko** [comment]
This is related to this discussion: https://github.com/getsentry/sentry/issues/3050

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
