### ISSUE TITLE
Assign issues in bulk from event stream

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3119]
> Add in mass assign. I want to be able to mark all errors and assign them to one user, that'd be awesome.

@getsentry/team Thoughts?

**Comment by tkaemming** [comment]
Similar ticket here: GH-3119

**Comment by dmalan** [comment]
Just wanted to echo an interest in this feature. In cases where one member of our team needs to be assigned several (related) issues that suddenly cropped up, being able to check multiple/all checkboxes and bulk assign would be quite convenient, much like Asana allows for tasks!

**Comment by dmalan** [comment]
Just wanted to echo an interest in this feature. In cases where one member of our team needs to be assigned several (related) issues that suddenly cropped up, being able to check multiple/all checkboxes and bulk assign would be quite convenient, much like Asana allows for tasks!

**Comment by dcramer** [comment]
FWIW the complexity here is just the UI. The endpoint already supports it. I want to get it added at some point, as it absolutely makes sense to offer.

**Comment by archon810** [comment]
Another vote for this.

**Comment by agamrafaeli** [comment]
Would have saved me about two hours of work right now.

**Comment by NathanUrwin** [comment]
Wow it's been almost 3 years since this issue was opened. Any update on this?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by archon810** [comment]
Yes, please still work on this.
