### ISSUE TITLE
App/root path improvements

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#3128]
Let's improve SDKs and how they handle prefixes and app detection.
1. Ensure all SDKs have either include_paths (-1) or project_root, which is used to detect in_app
2. Ensure all SDKs have a list of "prefixes" they can strip. In some cases this can be automatic (Python sys packages, Ruby gems). The project root is automatically included here.

**Comment by dcramer** [comment]
@getsentry/team if anyone has feedback here

- Python has include_paths and auto strips site-packages
- PHP has "base_path" and "app_path"
- Ruby assumes relative path for app root + some magic

**Comment by dcramer** [comment]
Also converting PHP to "prefixes" for stripping.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
