### ISSUE TITLE
Incorrect docstring for sentry.sentry_mail.get_send_to

### ISSUE THREAD

**Issue by kbroekhoven** [getsentry/sentry#3129]
This isn't an issue of functionality, but of documentation. 

The function `get_send_to(self, project=None)` returns a set of user IDs to be notified for a project, using the NotificationPlugin method `get_sendable_users(self, project=None)`. 

On the other hand, the docstring reads:
```
"""
Returns a list of email addresses for the users that should be notified of alerts.

The logic for this is a bit complicated, but it does the following:

The results of this call can be fairly expensive to calculate, so the send_to list gets cached for 60 seconds.
"""
```

This should be edited to read something along the lines of "Returns a list of IDs of the users ...", it's currently very misleading.

**Comment by tkaemming** [comment]
Thanks for pointing this out — I think I've actually been bitten by this one before but it might have gotten fixed on a branch that ended up being abandoned. We've updated the documentation to closer reflect reality.
