### ISSUE TITLE
Add breadcrumb for "trimmed" or condensed breadcrumbs

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3132]
Unfortunately, we cannot store infinite breadcrumbs – we have a limit on the amount of breadcrumb events we can send.

For long-lived sessions (like web pages, desktop apps, etc), we "trim" breadcrumbs and only keep the most recent X breadcrumbs. We need a breadcrumb object that describes how many of these events were trimmed, allowing us to render this in the breadcrumb interface UI.

Some possible names for this breadcrumb type:
- trimmed
- condensed
- summary

cc @mitsuhiko

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
