### ISSUE TITLE
Add optional "start" property to breadcrumb objects

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3133]
This property can be used to indicate that a breadcrumb is the _first_ breadcrumb event in a series. For example, the initial navigation event (loading the page) that starts a web application session. Or an inbound HTTP request that is handled by a web server.

Something like:

``` json
{
  "type": "navigation",
  "timestamp": 1461795857026,
  "start": true,
  "data": {
    "to": "/login"
  }
}
```

Discussion point: the "start" property may not be necessary if #3132 is implemented. The "start" breadcrumb can always be the first in the list, followed by a "trim" breadcrumb if any trimming took place, followed by any subsequent "full" breadcrumbs.

cc @mitsuhiko

**Comment by dcramer** [comment]
not a huge fan but i might be convinced

**Comment by benvinegar** [comment]
What about my comment re: "discussion point"? That might be the best solution. I put both tickets up just in case.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
