### ISSUE TITLE
Merged issues do not merge graph (tsdb) data correctly

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3136]
Other metadata (e.g. "first seen", "last seen") is correct. Just the data powering the right-side graphs (24h, 30d) is affected.

**Comment by tkaemming** [comment]
This ticket is related: https://sentry.zendesk.com/agent/tickets/2226

If we *do* decide to do this — for what it's worth, I think we should — it would be relatively straightforward to backfill using the [`GroupRedirect`](https://github.com/getsentry/sentry/blob/master/src/sentry/models/groupredirect.py) model to grab the historic IDs.
