### ISSUE TITLE
Truncated javascript messages

### ISSUE THREAD

**Issue by prebenlm** [getsentry/sentry#3144]
I'm seeing errors like: 

"undefined: QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage tha…"

However, I'm unable to read the entire message, as it just cuts off before the end of it. It seems to cut it off at 100 chars.

**Comment by benvinegar** [comment]
Hey @prebenlm – this is probably an issue for [getsentry/raven-js](/getsentry/raven-js).

What version of the client are you running?
