### ISSUE TITLE
Credit card regex should include spaces/dash

### ISSUE THREAD

**Issue by ayeowch** [getsentry/sentry#3156]
https://github.com/getsentry/sentry/commit/cf20bb17f598e9a86ac18c3197f00f44097e392b scrubs "4111111111111111" but not "4111 1111 1111 1111". Both used to be scrubbed prior to this commit. Was there a specific reason we no longer want to scrub credit card number with spaces/dash?

**Comment by dcramer** [comment]
I believe we changed this because it was far too lenient before and it was scrubbing a lot of data. I'm not against improving the current approach to try and catch those, but I was really hoping to avoid a full on "does this pass the cc validation tests" for any value

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
