### ISSUE TITLE
KeyError: 'file like object has no read() method'

### ISSUE THREAD

**Issue by ghost** [getsentry/sentry#3157]
Hi guys
I tried run amazing Sentry project by apache2 mod_wsgi that run an installed Sentry in virtual environment, i can do it, but any static files cant load on my browser, after i checked apache log i see description similar below lines:

```
[Sun May 01 16:38:46.106931 2016] [wsgi:error] [pid 19046] [remote 5.39.50.57:27319] Traceback (most recent call last):
[Sun May 01 16:38:46.106960 2016] [wsgi:error] [pid 19046] [remote 5.39.50.57:27319]   File "/var/www/sentry-me/env/lib/python2.7/site-packages/raven/middleware.py", line 48, in __call__
[Sun May 01 16:38:46.107006 2016] [wsgi:error] [pid 19046] [remote 5.39.50.57:27319]     for event in iterable:
[Sun May 01 16:38:46.107043 2016] [wsgi:error] [pid 19046] [remote 5.39.50.57:27319] KeyError: 'file like object has no read() method'
```

I tried to known type of iterable variable and i understand that type of this is FileWrapper that imported from wsgiref.util...
However [i resolved this problem](http://stackoverflow.com/questions/36969244/setup-apache2-mod-wsgi-for-sentry) by replacing application value in wsgi.py file by default django WSGIHandler, but i think better way for resolving this problem is adding read method to FileWrapper class.

**Comment by mattrobenolt** [comment]
Sentry does not support being run via `mod_wsgi` and there shouldn't be any reason to. The built in `sentry start` (now `sentry run web`) is production ready and should be used. 

Is there a reason you're trying to do this in the first place?

**Comment by mattrobenolt** [comment]
Also, to clarify, this is just for static files, right? My guess then is related to the `wsgi.file_wrapper` thing. I guess `HttpResponse.streaming_content` isn't the right type that `mod_wsgi` expects?

**Comment by moshen212** [comment]
Yes, this problem is only related to statics files.
I think is better if Sentry develop independent of special web-server, i can use Sentry with `mod_wsgi` by tiny changes in `wsgi.py` file and by apply tiny changes in main Sentry code can work by mod_wsgi without need to applying custom changes by server admins.

**Comment by markstory** [comment]
Closing as reporter is now a ghost.

**Comment by mattrobenolt** [comment]
👻
