### ISSUE TITLE
Breadcrumbs follow-ups

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3162]
- [ ] revisit relative vs absolute timestamps
- [x] the "..." icon doesn't expand breadcrumbs, only text (#9698)
- [ ] icon for navigation crumbs
- [x] remove "generic" text for errors

**Comment by dcramer** [comment]
- error needs to be structured (type/value) [[1]](https://app.getsentry.com/sentry-test/sentry-ruby-test/issues/126565924/)
- error needs to render as: **Type:** value (one line)
- margins are messed up (top vs bottom on each row)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
