### ISSUE TITLE
DistributionNotFound: No distributions matching the version for honcho<0.8.0,>=0.7.0 (from sentry)

### ISSUE THREAD

**Issue by mwcz** [getsentry/sentry#3168]
I'm attempting to upgrade to Sentry 8.4, but the `pip install -U sentry` is failing with this error:

      [SNIP]
      Could not find a version that satisfies the requirement honcho<0.8.0,>=0.7.0 (from sentry) (from versions: 0.0.4, 0.3.1, 0.4.1, 0.4.0, 0.1.0, 0.2.0, 0.0.3, 0.4.2, 0.5.0, 0.0.1, 0.0.2)

    Cleaning up...

      Removing temporary dir /home/sentry/.virtualenvs/sentry/build...
    No distributions matching the version for honcho<0.8.0,>=0.7.0 (from sentry)

    Exception information:
    Traceback (most recent call last):
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
        status = self.run(options, args)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/pip/commands/install.py", line 236, in run
        requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/pip/req.py", line 1085, in prepare_files
        url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
      File "/home/sentry/.virtualenvs/sentry/lib/python2.7/site-packages/pip/index.py", line 309, in find_requirement
        raise DistributionNotFound('No distributions matching the version for %s' % req)
    DistributionNotFound: No distributions matching the version for honcho<0.8.0,>=0.7.0 (from sentry)

Happy to provide additional information.  Might be a pip problem, not a Sentry one.  It looks like there *is* a [honcho 0.7.0](https://pypi.python.org/simple/honcho/) but pip can't find it for some reason.

**Comment by mwcz** [comment]
Sorry, it was a pip issue.  After upgrading pip the install -U worked.

**Comment by ericcf** [comment]
@mwcz I'm seeing this same problem, using pip 8.1.1. Which version are you running now that works? Thanks.

**Comment by mwcz** [comment]
Great!  Glad it's working. :D

Just for completeness, I'm on pip 8.1.1 as well.

**Comment by DaveBlooman** [comment]
Im having the same issues on centos7

```sh
Downloading/unpacking honcho>=0.7.0,<0.8.0 (from sentry)
  Could not find a version that satisfies the requirement honcho>=0.7.0,<0.8.0 (from sentry) (from versions: 0.0.4, 0.3.1, 0.4.1, 0.4.0, 0.1.0, 0.2.0, 0.0.3, 0.4.2, 0.5.0, 0.0.1, 0.0.2)
Cleaning up...
No distributions matching the version for honcho>=0.7.0,<0.8.0 (from sentry)
Storing complete log in /root/.pip/pip.log
[root@38f2d083de9c /]# pip -V
pip 8.1.1 from /usr/lib/python2.7/site-packages (python 2.7)
```

**Comment by mattrobenolt** [comment]
I'm guessing this is related to https://github.com/nickstenning/honcho/issues/177

But with pip 8.1.1, there definitely shouldn't be an issue. This would affect much older `pip` versions.
