### ISSUE TITLE
Retaining All Samples

### ISSUE THREAD

**Issue by abhillman** [getsentry/sentry#3169]
Is there any way to retain all samples for self-hosted Sentry instances? Is this a Bad Idea?

**Comment by dcramer** [comment]
You can set ``SENTRY_SAMPLE_DATA = False`` in the ``sentry.conf.py`` file. It's not a bad idea, and in fact its what we're moving towards. That said, by default its not a good idea since it generally costs a lot more in storage for minimal value.
