### ISSUE TITLE
Can I use mysql with docker-compose?

### ISSUE THREAD

**Issue by wyman1217** [getsentry/sentry#31753]
### Problem Statement

I want to use mysql as the database with docker-compose.How to change the docker-compose.yml?
Now I using postgres,is it possible to swich to mysql without losing the data?

**Comment by markstory** [comment]
MySQL is not supported and will not work with Sentry. We use a number of postgres specific features.

**Comment by wyman1217** [comment]
Not - https://github.com/fwani/Sentry-Docker-Compose, is  - https://github.com/getsentry/self-hosted.
Yes I want to use client tools of mysql.I am familiar with using mysql client to select data.

**Comment by markstory** [comment]
>  Yes I want to use client tools of mysql.I am familiar with using mysql client to select data.

Understandable, but Sentry doesn't support MySQL. Our migrations and queries rely on postgres specific features. There are also no plans to add support for MySQL.
