### ISSUE TITLE
Add server spec recommendation for self hosted version

### ISSUE THREAD

**Issue by garygreen** [getsentry/sentry#3190]
I was trying to find information on the docs but cannot find any.

What's the recommended server requirements for a self-hosted sentry installation? Can I run it on a raspberry pi or is that stupid?

It would be good to give some indication on the docs about memory recommendation / CPU usage based on X exceptions per minute.

Cheers

**Comment by dcramer** [comment]
Given that Sentry is an infrastructure service it is not intended to run on minimalistic hardware like the Raspberry Pi.

We document hardware guidance here:

https://docs.getsentry.com/on-premise/server/installation/
