### ISSUE TITLE
DSym Launch Issues

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#3194]
Things that come up:

* [x] sometimes the lack of dsym files can cause processing to just skip the stacktrace. Need to investigate why that might be.
* [x] if you have an app made from multiple frameworks/images/etc. the stacktraces hide pretty much everything by default now.
* [x] no insight in processing failures. This needs to land because it's too hard to figure out why something went wrong.

For the clients:

* [x] make sure breadcrumbs match current API

**Comment by dcramer** [comment]
Of note, any open sentry-cli issues we should resolve as well

**Comment by dcramer** [comment]
Do we need to do more work on docs as well?

**Comment by mitsuhiko** [comment]
Done for now. Rest split off into #3352
