### ISSUE TITLE
Device tag (Auto-generated?)

### ISSUE THREAD

**Issue by mastacheata** [getsentry/sentry#3196]
I'm not exactly sure if this is a problem with the sentry server or the php library.

Most of the events logged to my sentry instance come from a web application which in turn is called from rather generic HTTP libraries/plugins to third-party software.
These libraries have very generic User Agents like "Mozilla/3.0" or "http_requester/0.2".
In Sentry my events have a device tag labeled "Generic Feature Phone"

While I can see the full user agent in the data part that's filled from the $_SERVER superglobal, there seems to be a "device" tag that's auto-filled as well. (It's not supplied from the PHP application)
I couldn't find where it gets that from, though. It's not in the php library as far as I could tell, but it's also not in Monolog, so I'm wondering where it gets that from.

Does it do that conversion from the user agent "extra param" to the device tag in the server itself?
If that is the case I'd like to suggest  having the full user agent as the device tag in cases where no other match is found or offer an option to add custom user agent to device tag mappings.

If this is not part of the sentry server, I'd appreciate any hint on where to find that conversion.

Thanks in advance

**Comment by dcramer** [comment]
@mastacheata device and browser are parsed by the Sentry server from the user-agent

If you wanted more, you could always create a tag yourself for the user agent, or whatever specific information you want.
