### ISSUE TITLE
Web frontend show big decimal accuracy issue

### ISSUE THREAD

**Issue by kevinxuv** [getsentry/sentry#3200]
It is a js issue, when a big decimal is longer than 17, this issue will occur, for example: 1006244505781987669, the frontend will show 1006244505781987700, this issue is a minor issue.

**Comment by tkaemming** [comment]
This is technically true, but I'm pretty sure if you're dealing with literally quintillions of events, the fact that the number is 9.93794246e-17% off from the actual total is the least of your worries.
