### ISSUE TITLE
Data scrubber filters entire URL if breadcrumb contains sensitive data

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3202]
From a user:

>  Currently if URL contains `access_token` param, whole URL will be shown as `[Filtered]`, which is not really useful when almost all our URLs have access_token query param due to ability to avoid CORS OPTIONS request for each HTTP request.

It would be nice if the data scrubber only filtered the affected query string component.

**Comment by jazoom** [comment]
Same problem. Is there a plan to address this?

**Comment by adamreisnz** [comment]
+1 for this, as currently the breadcrumb information is pretty useless when certain requests are scrubbed:

![image](https://user-images.githubusercontent.com/490562/35485111-419fd83e-04bf-11e8-9247-9a1ea1c3f537.png)

**Comment by dangreenisrael** [comment]
You can just put `url` in Safe Fields in your project settings 
![Screen Shot 2019-05-09 at 3 02 27 PM](https://user-images.githubusercontent.com/4509692/57479489-86ca9000-726b-11e9-9b43-db741eeb9289.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
