### ISSUE TITLE
Release details doesn't render for some release strings

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3203]
For example, we have a user sending release/version strings that look like this (with spaces):

```
v: 1.1.321 / 01.01.2017-11.22
```

Looks fine in the release list, but when you visit the release itself (releaseDetails.jsx), you get the following:

![image](https://cloud.githubusercontent.com/assets/2153/15157317/ef237ade-169f-11e6-9b32-90b8b466b5e8.png)

**Comment by benvinegar** [comment]
This should have been obvious but I missed it: the forward slash in the version string (`/`) causes the router not to find the correct route.

@dcramer – could we add validation to the route here to prevent users from creating releases w/ slash characters?

**Comment by benvinegar** [comment]
Relevant Django ticket: https://code.djangoproject.com/ticket/15718 (closed as "wontfix")

> Django unquotes urls and not able to distinguish %2F and /

**Comment by joaomilho** [comment]
I think this is being done mainly because one can't see the release details in Sentry's UI, so one piles stuff in the string.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
