### ISSUE TITLE
JS stack trace don't expands to sources

### ISSUE THREAD

**Issue by ColCh** [getsentry/sentry#3207]
Hi! I'm using react-native, javascript.
Uploaded sourcefile and sourcemap. Twice-checked it (before upload) with loading script in `index.html` and looking in chrome dev tools:

This is a message from Chrome:
```
ExceptionsManager.js:76Error: __fbBatchedBridgeConfig is not defined, stack:
ReferenceError: __fbBatchedBridgeConfig is not defined
    at BatchedBridge.js:16
    at requireImpl (require.js:82)
    at _require (require.js:31)
    at NativeModules.js:14
    at requireImpl (require.js:82)
    at _require (require.js:31)
    at JSTimers.js:15
    at requireImpl (require.js:82)
    at _require (require.js:31)
    at setUpTimers (InitializeJavaScriptAppEngine.js:107)
```
(Take a look on this: `at`- they point on approtiate files)

Sourcemap path:
```
//# sourceMappingURL=index.android.bundle.map
```

Command to upload:
```shell
curl /app.getsentry.com/api/0/..../releases/test/files/ \ \
-u ...: \
-X POST \
-F file=@index.android.bundle.map \
-F name="index.android.bundle.map"

# and

curl /app.getsentry.com/api/0/..../releases/test/files/ \
-u .....: \
-X POST \
-F file=@index.android.bundle \
-F name="index.android.bundle"
```

Then, `throw new Error` and `Raven.captureException` it.

Sentry dashboard:
```
Error
Hello world, I'm managed exception from JS side!
index.android.bundle at line 1430:643
index.android.bundle in requireImpl at line 87:17
index.android.bundle in _require at line 36:19
index.android.bundle at line 1330:102
index.android.bundle in requireImpl at line 87:17
index.android.bundle in requireImpl at line 44:30
index.android.bundle in _require at line 36:19
index.android.bundle in global code at line 92038:9
```
So, `index.android.bundle at line 1430:643` points on this line:
```
var RELEASE_ID='test';var Raven=require(442 /* raven-js */);Raven.config('https://..........',{release:RELEASE_ID}).install();require(448 /* raven-js/plugins/react-native */)(Raven);function logException(ex,context){Raven.captureException(ex,{extra:context});window.console&&console.error&&console.error(ex);}try{throw new Error("Hello world, I'm managed exception from JS side!");}catch(e){console.log(e.message);console.log(e.stack);logException(e,"Hello world error");}
```
(It's one line)
And `index.android.bundle at line 1430:643` itself, points on Error constructor
```
throw new Error("Hello world, I'm managed exception from JS side!");
```
(This is fine)

But not very helpful. We don't store our bundled code anywhere - for builds, it get's minified ("uglified")

What I see for minified code:
```
index.android.bundle at line 12:884
```

Not very helpful... This error is in `app.js:51:18`

This is message from Google Chrome web dev console, on minified script, using react-native debugger (just ok):
```
Error: Hello world, I'm managed exception from JS side!
    at app.js:51
    at t (require.js:82)
    at i (require.js:31)
    at index.android.js:2
    at t (require.js:82)
    at t (require.js:39)
    at i (require.js:31)
    at require-0.js:1
    at messageHandlers.executeApplicationScript (debuggerWorker.js:18)
    at DedicatedWorkerGlobalScope.onmessage (debuggerWorker.js:33)
2016-05-11 15:16:06.466 ExceptionsManager.js:76 Error: Hello world, I'm managed exception from JS side!(…)console._errorOriginal.console.error @ ExceptionsManager.js:76n.(anonymous function) @ console.js:26l @ app.js:51(anonymous function) @ app.js:56t @ require.js:82i @ require.js:31(anonymous function) @ index.android.js:2t @ require.js:82t @ require.js:39i @ require.js:31(anonymous function) @ require-0.js:1messageHandlers.executeApplicationScript @ debuggerWorker.js:18onmessage @ debuggerWorker.js:33
```

It seems, that I'm not mistaken on any step, right?

So, any way to get expanded sources, like in Google Chrome Web developer console?

**Comment by ColCh** [comment]
Attached a screenshot, may be it will be helpful

![2016-05-11_15-24-58](https://cloud.githubusercontent.com/assets/599439/15180874/c3cde930-178c-11e6-8a88-93127d009533.png)

**Comment by benvinegar** [comment]
@ColCh – it looks like you're a hosted Sentry user. Can you write to support@getsentry.com and we can help you from there.

**Comment by willtennien** [comment]
Hey Ben can you explain this for those of us watching from home?

**Comment by benvinegar** [comment]
There's a million reasons why this could be happening. If you can share the assets that are generated we could take a look.

Also – we have a new [React Native client library](https://github.com/getsentry/react-native-sentry) that you should be using, with a wizard that helps get Sentry going. I'd use that if you aren't already
