### ISSUE TITLE
going to /auth/login (rather than /auth/login/) causes a loading error after login

### ISSUE THREAD

**Issue by macqueen** [getsentry/sentry#3215]
The react router is likely the culprit.

Steps to reproduce:
1. go to /auth/login (no trailing /)
2. login form will appear normally, login with valid credentials
3. You're not correctly redirected and there's a data loading or organization not found error:
![screenshot 2016-05-11 14 45 24](https://cloud.githubusercontent.com/assets/5026776/15197570/08fe19c2-1787-11e6-8624-8bddd7b0ecad.png)

**Comment by percyhanna** [comment]
The issue title doesn't differentiate between `/auth/login` and `/auth/login/` (the trailing `/` is missing from both references). However, when I accessed it with the trailing `/`, I was able to log in successfully.

**Comment by macqueen** [comment]
thanks, fixed the title! @percyhanna
