### ISSUE TITLE
Option to NOT display application user's photos in error notifications emails

### ISSUE THREAD

**Issue by vladgurovich** [getsentry/sentry#3217]
We have recently transitioned from Sentry 7 to Sentry 8 and discovered that error notification emails nowshow our application's users photos in the notification emails 

Is there an option not to have gravatars in the email? We dont want to expose any more information in those emails about the user than absolutely needed to do our jobs as developers and gravatars are absolutely unessential.

![gravatar](https://cloud.githubusercontent.com/assets/444833/15203072/ef2eb19a-17b4-11e6-94f2-acff190930f8.jpg)
 based on the Gravatar lookup of the email from the error's user context.

**Comment by dcramer** [comment]
If you're concerned about PII we recommend enabling the Enhanced Privacy option which is an org setting. It will slim down the emails to exclude anything that might have PII. If that's not a good enough solution were interested in hearing more feedback.

**Comment by vladgurovich** [comment]
@dcramer Was  the gravatar in the error report by design? Im curious of what is the use case for it? I.E what value does it add to the email

**Comment by dcramer** [comment]
@vladgurovich it makes us happier about life because our emails are less tiresome. I'm pretty sure even in the current release of Sentry we're not using Gravatar there, but didn't confirm.
