### ISSUE TITLE
More detail in breadcrumbs ui.click

### ISSUE THREAD

**Issue by soroushhakami** [getsentry/sentry#3220]
Compared Sentrys breadcrumbs to TrackJS Telemetry Timeline, and I think Sentrys can be improved a little bit. 

Sentry ui-click:
```
div.well.ng-scope > div.ng-scope > div > button.btn.btn-lg.btn-primary
```

TrackJS ui-click:
```
<button class="btn btn-lg btn-primary" ng-click="uploadFile()" />
```

It'd be really nice to be able to see all attributes on the button, such as ng-click. 
If possible, it'd be nice to see the text of the button aswell.

**Comment by mitsuhiko** [comment]
We actually started out with rendering other attributes originally but we did not really consider it useful. The only attributes currently rendered are `name` and indirectly `class` and `id`. Maybe it makes sense to include `ng-*` into the rendering.

**Comment by mitsuhiko** [comment]
I opened up an issue on the javascript client.

**Comment by soroushhakami** [comment]
Nice, thanks.

What do you think of the possibility to add the text of the button aswell? It'd make things easier especially for apps where the classnames don't reveal much.

Something along the lines of :

```
 div > button.btn.btn-lg.btn-primary "Purchase"
```

**Comment by mitsuhiko** [comment]
@soroushhakami ideally we move this discussion to the javascript client. The server does not care about the data being sent from the client for this purpose.

**Comment by soroushhakami** [comment]
My bad, will move to separate issue on the client.

**Comment by mitsuhiko** [comment]
Not sure if you saw, but I opened an issue here: https://github.com/getsentry/raven-js/issues/576

**Comment by soroushhakami** [comment]
Yeah I saw, thanks 👍 
And I created another issue, for the second part of my request (they are independent): https://github.com/getsentry/raven-js/issues/577
