### ISSUE TITLE
Add support for "indexed" (or "alternate format") source maps

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3224]
See: [Source Map Revision 3 Proposal](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k)

Right now Sentry supports the default source map format, documented in the spec under [Proposed Format](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.qz3o9nc69um5).

However, the spec also outlines an alternate [Index mapped](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.535es3xeprgt) format. This format is currently not supported by Sentry, and will be rejected if it is discovered as an artifact when processing an error event's stack trace.

This hasn't been a problem up until now, because AFAIK all popular source-map generating tools produced the default format (e.g. Browserify, Uglify). But it has come to our attention that the **React Native** bundler (as of 0.25.x) will produce this indexed source map format when run with `--dev false`:

```bash
$ react-native bundle --dev false --entry-file index.ios.js --bundle-output main.bundle --sourcemap-output main.bundle.map
```

Produces the index format:

```
{"version":3,"file":"main.bundle.bundle","sections":[{"offset":{"line":0,"column":0}, ....
```

_Note that when run with --dev true (or --dev is altogether omitted), React Native produces the standard format source map and Sentry ingests this properly._

**Comment by benvinegar** [comment]
Here is the [relevant source map building code](https://github.com/facebook/react-native/blob/cccb8db1751572f4ce3800c1d325d15319f573ea/local-cli/bundle/output/unbundle/as-indexed-file.js) (as-indexed.js) from React Native.

**Comment by mattrobenolt** [comment]
So, for this complexity, I'd like to straight up remove it out of Sentry core, for one.

I already have https://github.com/mattrobenolt/python-sourcemap, but it does significantly more, and iirc was heavier in memory usage. Though, I've slimmed it down quite a bit.

But I'd want to support this inside python-sourcemap and then use that instead of shoving more into our core here. I have lots more test cases and unit tests over there.

**Comment by mattrobenolt** [comment]
(We can also move this library under getsentry org if that matters)

**Comment by benvinegar** [comment]
@mattrobenolt – makes sense to me. I mean, we may also be looking at having to build a stack trace normalization/formatting lib in Python too (since there is a long term goal of having @getsentry do that rather than browser js libs).

**Comment by mattrobenolt** [comment]
Yeah, I think that's a separate problem, and would probably be worth doing a lib just for that. Then we can try to convert over all the unit tests from js to python.

**Comment by Kerumen** [comment]
What's the update on this?

**Comment by ide** [comment]
@Kerumen We post-process the source maps by flattening them before uploading them to Sentry.

**Comment by nikki93** [comment]
@Kerumen Here's the change we made, for reference. https://github.com/facebook/react-native/compare/master...exponentjs:flatten-source-map

**Comment by jayshah123** [comment]
@nikki93  how do you build your bundle? I tried 

`sudo curl "http://localhost:8081/index.android.bundle?dev=false&minify=true&flattenSourceMap=true" -o "android/app/src/main/assets/index.android.bundle"`

The last line of index.android.bundle is however 
`//# sourceMappingURL=/index.android.map?dev=false&flattenSourceMap=true&minify=true`

Sentry cannot find file if it finds query params in sourcemapping URL.
Any suggestions?

**Comment by ide** [comment]
@benvinegar could you keep us posted when your commits get deployed to production?

**Comment by benvinegar** [comment]
@ide – this is now live and I've confirmed that it works with output generated from the react-native bundler (with `--dev false`).

**Comment by ide** [comment]
@benvinegar Thank for you for the update and that's awesome!

**Comment by benvinegar** [comment]
@kerumen – quick question, how are you getting that output w/ `/*ascii:*/`? We had a user run into this issue, but I can't seem to generate it using latest RN (0.31.0).

**Comment by Kerumen** [comment]
@benvinegar It was [right there](https://github.com/facebook/react-native/blob/0.28-stable/local-cli/bundle/output/hash.js#L20) in RN 0.28.

It was removed then.

**Comment by benvinegar** [comment]
@Kerumen – Thanks for the followup. We added something to Sentry to handle those comments anyways just in case.
