### ISSUE TITLE
Uploaded sourcemap not recognized

### ISSUE THREAD

**Issue by Ninerian** [getsentry/sentry#3228]
I created a release and uploaded the source files to sentry on my self hosted version. Under the releases tab, the source files are recognized and associated to their URL. 

But when a problem occur, their is are error message `Unable to fetch resource: http://gitlab/diginetmedia/pano-player/raw/3.4.3/app/_/js/base/events.js `

The files are safed internal and not accessible from the internet. But I assumed, that uploading them would be the solution for it, as your documentation states:

> In many cases your application may sit behind firewalls or you simply can’t expose source code to the public. Sentry provides an abstraction called Releases which you can attach source artifacts to.

What did I do wrong?

**Comment by dcramer** [comment]
One of two things:

- the name of the uploaded file is not the same as that full URL (must be exact)
- you're not sending the release attribute with the event that matches up to the same version

Feel free to reopen if you verify and still having issues
