### ISSUE TITLE
Sentry groups different errors under the same report

### ISSUE THREAD

**Issue by vladikoff** [getsentry/sentry#3229]
Hello, I have errors with different `Messages` and error numbers grouped under the same report. 

Example:

Title says `Error: Unexpected error`, message below says `Error: Incorrect password`. If I click on the "Older" button, title stays the same but "Message" changes.

Why are these errors grouped together? Is it because they have the same stack trace report?

![](http://v14d.com/i/5735f94dafe43.png) 

### Another example:

![](http://v14d.com/i/5735f9b6f0984.png)

Once I refresh the example above, the TITLE changed to `Attempt limit exceeded`.

![](http://v14d.com/i/5735f9f277edc.png)

**Comment by vladikoff** [comment]
This happens with Sentry 8.3.2 and Raven 2.3.0

**Comment by vladikoff** [comment]
cc @mattrobenolt @benvinegar

**Comment by mattrobenolt** [comment]
Yes, they are grouped because of the same stacktrace. We have documentation on this: https://docs.sentry.io/hosted/learn/rollups/

**Comment by vladikoff** [comment]
@mattrobenolt thanks!
