### ISSUE TITLE
Improve SourceMaps Visibility

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#3230]
First, the problems:
- Users are confused as to what filename to use when uploading source & maps
- Users are confused when they have uploading sourcemaps and they're not parsed (often the error isn't clear enough, or its only half of the story)
- An expectation exists that uploading a sourcemap will reprocess old data [low priority]

An approach:
- ~~Add a "original" and "debug" view for exceptions. Debug would be debug symbols/sourcemap. For now we just wouldn't keep the original view when we have the debug view. These are only shown when the platform is relevant, and include instructions to trigger them.~~ [implemented in #3316]
- On the little annotation marker next to each frame we could show if there was a sourcemap error (via an icon), and clicking it could give a more helpful modal that describes exactly what the filename should be, and how they might upload it.
- ~We can support relative sourcemaps. This might purely be url.rsplit('/', 1)[-1] == ReleaseFile.name~.

@getsentry/ui @getsentry/javascript

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
