### ISSUE TITLE
"sentry" breadcrumbs do not link to issue

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3245]
Breadcrumbs from raven-js, rather:

![image](https://cloud.githubusercontent.com/assets/2153/15306732/1363ffea-1b82-11e6-99c0-849b89c15744.png)

See also: getsentry/raven-js#580

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
