### ISSUE TITLE
Update Python 3.8 -> 3.10

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry#32463]
### Problem Statement

Sentry is currently using Python 3.8, which is out of full-support status as of 2021-05-03 and now in security-fixes-only stage (until approximately Oct 2024).

### Solution Brainstorm

Should we consider updating to the current release (3.10)?

@markstory

**Comment by markstory** [comment]
It would be great to get to 3.10. I can bring this up to the backend-tsc next session.

**Comment by mattjohnsonpint** [comment]
FYI, I'm sure there are many more impactful benefits, but one that stood out to me is that we could remove the pytz dependency - as 3.9 added built-in time zone support via zoneinfo. 😄

**Comment by ArthurKnaus** [comment]
Closing as we are on 3.12.6 by now.
Last upgrade in https://github.com/getsentry/sentry/pull/77420
