### ISSUE TITLE
Improve searchability with event types

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#3248]
Since the transition to event types its a lot less clear whats searchable on an error. We didn't change that functionality, but we changed whats displayed, and often whats displayed is no longer part of the 'message' attribute (which is what is primarily searchable).

To resolve this, we need to ensure that the core metadata on event type is indexed in a convenient way.

An approach:
- Deprecate Event.message (migrate to the Message interface)
- Use Event.message to index the metadata

See also: GH-1247

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
