### ISSUE TITLE
Switching between comment box preview/input breaks UI w/ Grammarly plugin

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3251]
[Grammarly](https://www.grammarly.com/) is a pretty popular Chrome plugin (~4 million users, 8k reviews), and it causes issues with our issue comment box. When switching between preview/input, it results in something like the following:

![image](https://cloud.githubusercontent.com/assets/2153/15337628/86df17e8-1c31-11e6-9876-524745d07284.png)

IMHO, this is Grammarly's problem ... but it seems to work fine w/ other edit boxes (e.g. GitHub's). It has enough users that we should quickly investigate and see if there's a quick change that can be made.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by masinette** [comment]
A customer has written in recently about this Issue. I've linked this GitHub Issue to the internal ticket.
