### ISSUE TITLE
Project selector in mobile view is unclickable (sometimes)

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3253]
In some mobile views, the project selector dropdown icon is not clickable.

Specifically when you reach this screen width breakpoint:

![image](https://cloud.githubusercontent.com/assets/2153/15340860/88889c54-1c40-11e6-8a73-69e8b3ba63dc.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
