### ISSUE TITLE
Alert for All Projects

### ISSUE THREAD

**Issue by burakatudemy** [getsentry/sentry#32563]
### Problem Statement

Currently, we cannot create an alert for all projects. We have to create an alert for each project we have. For example, I want to create an alert that detects event rate increases. Before creating this alert I have to select a project. But I want that it is valid for all of my projects. 

Most of the monitoring and observability tools allow us to create this kind of alert/monitor. It would be very useful if Sentry also provides this feature.

### Solution Brainstorm

Instead of selecting a single project, multi-project selection must be enabled. The created alert query can be executed in all selected projects.

**Comment by wedamija** [comment]
Thanks for the suggestion @bukurt, I've added this to our backlog
