### ISSUE TITLE
Letsencrypt failes through sentry routing

### ISSUE THREAD

**Issue by Ninerian** [getsentry/sentry#3256]
Hello,

I know this is also an issue for the letsencrypt repo. But I open it here, in the hope, some one of you have a solution for me. 

I use letsencrypt to get a certificate for the sentry subdomain. But know an error occured on the renewal process. The letsencrypt routine checks the address `http://sentry.domain.de/.well-known/acme-challenge/L-95F_7DReyuMJzEFKfE43iG_gR5lHSJCLTB-GUV4FM` for the token. But its returning a page from Sentry, which states a not found route.

I use apache to serve Sentry and configured it after the documentation. I also added a route to the apache config for the path, but it is still not working. 

Does anyone have a clue, how I could solve this?

Thank you in advance.

**Comment by mattrobenolt** [comment]
Hey @Ninerian, I'm not super familiar with how this works in Apache. I haven't used it in a while. But you just would need to set a `<Location />' directive that handles `/.well-known/` and loads files from disk where letsencrypt is dropping them.

If you were using nginx, I could help more. :)
