### ISSUE TITLE
[Flaky CI]: customRepositories.spec.tsx: App Store Connect missing from page

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#32731]
### Flakiness Type

Assertion failure

### Name of Job

acceptance / frontend tests (0)

### Name of Test

tests/js/spec/views/settings/projectDebugFiles/customRepositories.spec.tsx

### Link to Test Run

https://github.com/getsentry/sentry/runs/5585976249?check_suite_focus=true#step:9:448

### Details

The change is a dev env change, thus, FE failures should be unexpected.

Failure snippet:
>      108 |     // Display modal content
>      109 |     // A single instance of App Store Connect is available on free plans
>      110 |     expect(await screen.findByText('App Store Connect credentials')).toBeInTheDocument();
>          |                         ^
>      111 |
>      112 |     // Close Modal
>      113 |     userEvent.click(screen.getByLabelText('Close Modal'));

**Comment by priscilawebdev** [comment]
is this test still flaky? I've merged a PR today that may solve this issue https://github.com/getsentry/sentry/pull/32725. I believe the problem was with the `await mountModal`

**Comment by armenzg** [comment]
@priscilawebdev The execution of the test is on `master` rather than a PR.

It got merged ~3 hours after cf8d5b1c95a57ab705b5f9c047a043b9494b0ccf

**Comment by armenzg** [comment]
[This](https://sentry.io/organizations/sentry/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&query=transaction.op%3A%22jest+test%22+title%3A%22Custom+Repositories+%3E+renders%22++%21transaction.status%3Aok&sort=-timestamp&statsPeriod=30d&yAxis=count%28%29) Discover query shows the last 30 days when this test has failed.

It definitely got worse this week:
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/44410/158869203-4b381f5c-1d81-4e31-be39-f7ffaaf5d5b6.png">

**Comment by mitsuhiko** [comment]
@priscilawebdev can you have another look? this is still flaky.
