### ISSUE TITLE
Issues with Auth Tokens

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#3282]
There are currently some problems with auth tokens:
- [ ] the documentation does not show the tokens and indicates basic auth instead of bearer authorization
- [x] the documentation mentions the wrong header "Authentication"
- [x] quite a few endpoints access the `organization` property of the api key which is unavailable for api tokens (SENTRY-1A9)
- [x] the scope code raises an exception (SENTRY-1A5)

I think for the organization issue it would make sense to have an abstraction around request.access (maybe common baseclass is enough) to return a list of orgs, check access for org etc. instead of accessing attributes. That would also help the global key path tremendously.

**Comment by mitsuhiko** [comment]
Fixed the header in the docs here: https://github.com/getsentry/sentry-docs/commit/df3051d9cc2bc8c101e643fbc3b59a058706baba

**Comment by mitsuhiko** [comment]
Fixed the scope code in #3281

**Comment by sharma-abhishek** [comment]
Hi @mitsuhiko,

I have a on-premise setup of sentry v8.4.1. I cannot find  documentation/links to generate the authentication tokens to use sentry server API. Any help would be much appreciated.

Thanks,
Abhishek

**Comment by dcramer** [comment]
@sharma-abhishek they are not available in 8.4

**Comment by dcramer** [comment]
@mitsuhiko do you mean the generated API examples dont use the new header?

**Comment by mitsuhiko** [comment]
@dcramer yeah. Also they are completely absent anyways from the dropdown for now.

**Comment by timzaak** [comment]
Authorization: Basic {TOKEN}
Authorization: Beared {TOKEN}

what's the difference. and how can I get `Beared` token?

**Comment by dcramer** [comment]
@timzaak please see the docs:

https://docs.getsentry.com/hosted/api/auth/

There is no token used in basic authentication (its for legacy API keys), and ``{TOKEN}`` is simply a placeholder.

**Comment by timzaak** [comment]
@dcramer  thanks.

**Comment by ODemidenko** [comment]
I tried to find where this `{API_KEY} `: is set but failed.
Probably it is referenced in different parts of the config/docs by different names?
Otherwise, I can't find how to specify it

**Comment by dcramer** [comment]
Are you certain the token is correct? That should work just fine.

**Comment by dcramer** [comment]
All I can say is that there are ample tests for this code in Sentry core. It's possible that 8.22 just doesnt behave the same as our docs suggest.

I'd suggest taking this to forum.sentry.io either way.

**Comment by ODemidenko** [comment]
Is it possible to somehow check the set auth.token value, other then trying to query the API?

**Comment by ODemidenko** [comment]
You also mention is different branches that token's could be created at user account settings (https://github.com/getsentry/sentry/issues/2816#issuecomment-224075671). 
But I failed to find this option there. Could you probably give a screenshot on what are you speaking about? Or there is no more such option in the UI?

**Comment by dcramer** [comment]
@ODemidenko 8.22 is going on two years old if I recall correctly. Certainly anything we talk about works drastically different than what's on sentry.io right now. docs.sentry.io is always for the current version of sentry (and that is always whats on sentry.io). You can always try updating to the release candidate:

https://forum.sentry.io/t/sentry-9-release/3850/6

As mentioned though, this should be taken to forum.sentry.io as without a proof of bug its not really relevant to our issue tracker (or ultimately this ticket).

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
