### ISSUE TITLE
Dashborad js error -  Cannot read property 'id' of null

### ISSUE THREAD

**Issue by Alex-Bond** [getsentry/sentry#3291]
Hi!

I just upgraded my sentry from 7 to latest (8.4.1) version and have a bug on dashboard page.
My Recent Activity block doesn't loading (indefinite spinner)  and console showing this error:
raven.js:266 Uncaught TypeError: Cannot read property 'id' of null

Maybe this is my own hands from wrong place, but i cant find out whats wrong.

Thank you!

**Comment by mattrobenolt** [comment]
Hey @Alex-Bond, can you provide more information? At least the full stacktrace would be helpful.

My hunch is the API response is returning some misshaped data since this was a big upgrade you did.

/cc @benvinegar

**Comment by benvinegar** [comment]
I suspect he needs #3259

**Comment by mattrobenolt** [comment]
welp was there anything done on the JS side to guard against it? I could merge something into the 8.4.x release branch to deal with it gracefully. But I don't want to merge in the migration since we don't add migrations for patch releases.

**Comment by benvinegar** [comment]
> welp was there anything done on the JS side to guard against it?

There wasn't.

**Comment by mattrobenolt** [comment]
@Alex-Bond Could you try the following:  Run `sentry shell`, and enter:

```python
from sentry.models import Activity
Activity.objects.filter(group_id__isnull=True, type=1).delete()
```

If this is the problem, this will nuke the old/bad data.

**Comment by Alex-Bond** [comment]
Hi to all. Today problem gone after i mark few issues as resolved.

Thank you all for quick responses!
