### ISSUE TITLE
[Flaky CI]: WidgetBuilder > Widget Library > renders

### ISSUE THREAD

**Issue by JonasBa** [getsentry/sentry#32921]
### Flakiness Type

Jest Snapshot

### Name of Job

Issue opened from dashboard data

### Name of Test

tests/js/spec/views/dashboardsV2/widgetBuilder/widgetBuilder.spec.tsx

### Link to Test Run

n/a

### Details

Reported as flakey in https://sentry.io/organizations/sentry/dashboard/7997/

**Comment by shruthilayaj** [comment]
I'm going to close this one since it doesn't look like a flake but actual
expected test failures on the branch it ran on.
(https://github.com/getsentry/sentry/runs/5664623263?check_suite_focus=true#step:9:78)
