### ISSUE TITLE
[Flaky CI]: WidgetBuilder > can choose a field

### ISSUE THREAD

**Issue by JonasBa** [getsentry/sentry#32928]
### Flakiness Type

Other / Unknown

### Name of Job

Issue opened from dashboard data

### Name of Test

tests/js/spec/views/dashboardsV2/widgetBuilder/widgetBuilder.spec.tsx

### Link to Test Run

n/a

### Details

As reported in https://sentry.io/organizations/sentry/dashboard/7997/

**Comment by shruthilayaj** [comment]
https://github.com/getsentry/sentry/pull/33014
