### ISSUE TITLE
[Flaky CI]: WidgetBuilder > Sort by selectors > sortBy defaults to the first field value when coming from discover

### ISSUE THREAD

**Issue by JonasBa** [getsentry/sentry#32922]
### Flakiness Type

Jest Snapshot

### Name of Job

Issue opened from dashboard data

### Name of Test

tests/js/spec/views/dashboardsV2/widgetBuilder/widgetBuilder.spec.tsx

### Link to Test Run

n/a

### Details

Reported in https://sentry.io/organizations/sentry/dashboard/7997/

**Comment by udameli** [comment]
I'll look into this one

**Comment by udameli** [comment]
thanks to @narsaynorath this might be addressed with https://github.com/getsentry/sentry/pull/33362
I'll monitor if the flakiness is still present

**Comment by udameli** [comment]
haven't seen any flakes since https://github.com/getsentry/sentry/pull/34188 was merged. Will close this issue since it appears to be resolved
