### ISSUE TITLE
GroupActions > reprocessing > open dialog by clicking on the ReprocessAction component

### ISSUE THREAD

**Issue by JonasBa** [getsentry/sentry#32931]
### Flakiness Type

Other / Unknown

### Name of Job

Issue opened from dashboard data

### Name of Test

tests/js/spec/views/organizationGroupDetails/actions.spec.tsx

### Link to Test Run

n/a

### Details

Reported in https://sentry.io/organizations/sentry/dashboard/7997/

**Comment by scttcper** [comment]
This might have been fixed in
https://github.com/getsentry/sentry/pull/32834

Related
https://github.com/getsentry/sentry/pull/32740
