### ISSUE TITLE
Dropped Events — Sentry 8.3.3

### ISSUE THREAD

**Issue by aryeh-looker** [getsentry/sentry#3293]
Thank you kindly for all your hard work and for maintaining such a wonderful project. Our Raven client occasionally appears to be failing to send events to our Sentry instance.

I am working to gather more information about the issue, but in the mean time, I wonder: are there any cases when Sentry would intentionally return a non-200 status code when reporting an event (for example — if the same event, even with a different ID is repeatedly sent within too short a time span)?

It could merely be a gateway timeout issue, but our Sentry instance otherwise seems highly responsive.

Thank you again kindly!

**Comment by dcramer** [comment]
The API will always return an X-Sentry-Error cause for why something is rejected. If its a 429 its rate limiting, if its something else it could be a strong validation or a duplicate event rejection. The ``coreapi.py`` file contains the mixed logic for all of this, but we don't document the various cases.

**Comment by aryeh-looker** [comment]
Thanks a ton @dcramer.

**Comment by aryeh-looker** [comment]
Is it correct to say that by default, there is no rate limit? i.e. https://github.com/getsentry/sentry/blob/76fcb50c6382c674cb9d21be70b9dee5305ca543/src/sentry/options/defaults.py#L24

**Comment by dcramer** [comment]
For on-premise unless its been configured by either the installation or the organization there's no rate limits.
