### ISSUE TITLE
`Source code was not found for main.jsbundle` in a React Native app 

### ISSUE THREAD

**Issue by alvaromb** [getsentry/sentry#3294]
We're trying to integrate Sentry in our React Native apps. We're running our own hosted Sentry. I followed the steps explained [here (React Native integration)](https://docs.getsentry.com/hosted/clients/javascript/integrations/react-native/) and [here (Source Maps)](https://docs.getsentry.com/hosted/clients/javascript/sourcemaps/#uploading-source-maps-to-sentry). We're running Sentry v8.4.0 and `raven-js` 3.0.4.

To recap, I did the following steps:

- Created a new release named `1.0.1-b2`.

- Generated and uploaded the source map:

```
curl http://oursentry.net/api/0/projects/sentry/react-native-app/releases/1.0.1-b2/files/ \
-u <key>: \
-X POST \
-F file=@index.ios.map \
-F name="ios/index.ios.map"
```

- Checked that the `main.jsbundle` has the following line `//# sourceMappingURL=ios/index.ios.map`.

- Generated a crash.

At this point I realised that I needed to upload the `main.jsbundle` file also, because I was getting the following error:

<img width="742" alt="err" src="https://cloud.githubusercontent.com/assets/289640/15464220/30b2d4a8-20ce-11e6-958b-7b2e9591ce38.png">

So I uploaded the files, trying to do that using both the full file path and `main.jsbundle`, `file:///main.jsbundle`:

```
curl http://ourhostedsentry.net/api/0/projects/sentry/react-native-app/releases/1.0.1-b2/files/ \
-u <key>: \
-X POST \
-F file=@main.jsbundle \
-F name="main.jsbundle"
```

My release artifacts now looks like:

<img width="332" alt="artifacts" src="https://cloud.githubusercontent.com/assets/289640/15464301/c8b56932-20ce-11e6-9889-cd9ba37c2eec.png">

Then, I tried to generate more errors forcing a crash in other parts of the app. I realised I needed to tweak a bit the regexp to handle the bundle path, so in the end the new error reports looked like this:

<img width="456" alt="newerr" src="https://cloud.githubusercontent.com/assets/289640/15464403/67dc7906-20cf-11e6-8d59-3afb1270f5c8.png">

But I wasn't getting the stack trace, just the line number in the minified code. In order to debug the issue and trying to find what really happened, I ran this query into the Sentry db (last file is a test with a backslash before `main.jsbundle`):

```sql
sentry=# select * from sentry_releasefile;
 id | project_id | release_id | file_id |    ident     |       name
----+------------+------------+---------+--------------+-------------------
  2 |          7 |          4 |       2 | someidhash01 | ios/index.ios.map
  4 |          7 |          4 |       4 | someidhash02 | main.jsbundle
 11 |          7 |          4 |      11 | someidhash03 | /main.jsbundle
```

And then the releases

```sql
sentry=# select * from sentry_release;
 id | project_id | version  |          date_added           |         date_released         | ref | url | date_started | data | new_groups | owner_id
----+------------+----------+-------------------------------+-------------------------------+-----+-----+--------------+------+------------+----------
  4 |          7 | 1.0.1-b2 | 2016-05-19 14:25:49.910188+00 | 2016-05-19 14:25:49.910011+00 |     |     |              | {}   |          7 |      
  1 |          5 | 0.0.1    | 2016-05-12 13:40:48+00        |                               |     |     |              | {}   |         15 |      
(2 rows)
```

So it seems that the number matches in the database, but somehow Sentry is unable to find the matching artifact event if they exists for that project & release. Just FYI, I checked the actual files in the filesystem and it seems that Sentry doesn't duplicate `main.jsbundle` even if I have two artifacts with the same file but different name (which makes sense). I can `ls` two files separated into 1MB chunks that match both file sizes. I'll try to delete all the `main.jsbundle` files and re-create all, but I don't know if thats the issue we're seeing.

**Edit**

I deleted all the artifact files & events, re-uploaded `main.jsbundle` and source maps and I'm still getting the same error, `Source code was not found for main.jsbundle`.

**Comment by alvaromb** [comment]
Hello @benvinegar, would you like to give us a hand with this? Thanks! 😃

**Comment by benvinegar** [comment]
@alvaromb – sorry, this issue got buried and I should have responded sooner. Any news?

If Sentry says, "Source code not found for /path/to/file.js", you must specify the full `/path/to/file.js` as the artifact name. It's not clear to me that you've tried that?

**Comment by alvaromb** [comment]
Hi Ben! Thanks for jumping in.

This is a React Native project, and the event always asks for the following file URL, after stripping the bundle file URL from the app (`/var/containers/Bundle...`). The stripping is done in the `raven-js` client.

```
{
  "url": "main.jsbundle"
}
```

I have included an artifact with that name. In fact, in the Sentry database there is a file with that _exact_ name, however it's not finding it.

Somehow Sentry doesn't match the `main.jsbundle` with the `main.jsbundle` artifact.

**Comment by timzaak** [comment]
with the latest raven-js  3.2.0, the error change to:
Invalid location in sourcemap: (1402, 41) Collapse
{
  "column": 1402,
  "source": "/main.jsbundle",
  "row": 41
}

my shell to get and upload sourcemap is:
```sh
curl http://127.0.0.1:8081/index.ios.js -o index.ios.js

curl https://app.getsentry.com/api/0/projects/org/project/releases/{releaseId}/files/ \
	  -X POST \
	  -H 'Auth....' \
	  -F file=@index.ios.js \
	  -F name="/main.jsbundle"
```
if `curl http://127.0.0.1:8081/index.ios.js -o index.ios.js` is wrong?
@benvinegar

**Comment by benvinegar** [comment]
@timzaak – Don't upload index.ios.js – that is your source file / entry point. `main.jsbundle` should be your final built application file that is transferred to devices. You can build this yourself with the React Native packager.

@alvaromb – Please contact support and I can take a look at why the lookup is unsuccessful.

I'm going to close this ticket because these aren't Sentry bugs but rather just React Native source code lookup confusion. I'm going to be expanding our RN docs to address this.

**Comment by alvaromb** [comment]
Hi @benvinegar!

This is an in-house Sentry installation, can I contact support anyway?

**Comment by arilitan** [comment]
@benvinegar @timzaak  have you found a work around to this issue?

**Comment by benvinegar** [comment]
> This is an in-house Sentry installation, can I contact support anyway?

@alvaromb – it wouldn't be any good, because my purpose was to look at your sentry.io account to debug further.

> @benvinegar @timzaak have you found a work around to this issue?

The [React Native plugin docs](https://docs.getsentry.com/hosted/clients/javascript/integrations/react-native/) were expanded significantly since this issue was raised. I'd read them in full.

**Comment by arilitan** [comment]
@benvinegar yes i did read them in full, however I am experiencing the exact error as described above: `Source code was not found for /main.jsbundle` and  `main.jsbundle` is uploaded as an asset. your doc's mention to name the file `/main.jbundle` however its not possible to include the character `/` in filenames. My filesystem (OSX) encodes it as a `:`

**Comment by alvaromb** [comment]
Just a quick update @benvinegar, we're running Sentry 8.8.0 in our in-house installation. While testing this with a React Native app running on the simulator, we get the following error, even with the right artifact file and filename uploaded for the release:

<img width="861" alt="screen shot 2016-10-10 at 09 59 30" src="https://cloud.githubusercontent.com/assets/289640/19229793/7ad8bdac-8ed0-11e6-9b4d-2f153ff724de.png">

<img width="628" alt="screen shot 2016-10-10 at 09 59 16" src="https://cloud.githubusercontent.com/assets/289640/19229797/7f4a46b2-8ed0-11e6-9c43-c943d322ca78.png">

I've followed the RN plugin docs (thanks for the update!) but I think we're getting the same error as described before. Although we upload the right artifact and name for the right release, Sentry seems unable to match both names (encoding issue maybe?).

If it helps you debugging, this is the last line of my `main.jsbundle` for a simulator environment:

```
//# sourceMappingURL=/index.ios.map?platform=ios&dev=true
```

**Comment by benvinegar** [comment]
@arilitan

> however its not possible to include the character / in filenames

This is the artifact name you tell Sentry – it can contain any characters.

**Comment by benvinegar** [comment]
@alvaromb

Hmm, that all looks right. Unless some whitespace snuck into your artifact names that I can't see.

Did you trigger the errors *after* the artifacts were uploaded? Just a quick note that they are not retroactive.

**Comment by denstepa** [comment]
Hi! 
We are also having the same issue usgin self-hosted sentry 8.7.0

the error is 

`Source code was not found for /main.jsbundle
{
  "url": "/main.jsbundle"
}`

Here are how the Artefacts look for this release. We tried both with `/` in the beginning and without.
What could be wrong ?
![2016-11-17 12 16 14](https://cloud.githubusercontent.com/assets/3616888/20387312/c2c8a246-acbf-11e6-8f6e-f9f908c964eb.png)
