### ISSUE TITLE
Systemd service files (documentation)

### ISSUE THREAD

**Issue by LordMike** [getsentry/sentry#3301]
Hi,

After having followed your excellent guide (really, kudos on that. It's almost copy-paste and then run) a few times, I've now written the same `systemd` service files two or three times. Do you have systemd documentation or would you like it?

I've created 3 systemd service files in my `Ubuntu 16.04`'s `/etc/systemd/system` directory, as shown below. This allows me to `systemctl enable sentry-web` (and the other two) as well as `service sentry-web status|start|stop`. SystemD keeps track of PID files, stopping services on shutdown (because you elegantly respond to `SIGTERM`).

The files are a start and work in my installation. They may need more in terms of `[Install]` or other options. I haven't handled the virtualenv besides setting `WorkingDirectory`, but it doesn't seem like it's needed.

**sentry-web.service**

    [Unit]
    Description=Sentry Main Service
    After=network.target
    Requires=sentry-beat.service
    Requires=sentry-worker.service
    
    [Service]
    Type=simple
    User=sentry
    Group=sentry
    WorkingDirectory=/www/sentry
    Environment=SENTRY_CONF=/etc/sentry
    ExecStart=/www/sentry/bin/sentry run web

**sentry-beat.service**

    [Unit]
    Description=Sentry Beat Service
    After=network.target
    
    [Service]
    Type=simple
    User=sentry
    Group=sentry
    WorkingDirectory=/www/sentry
    Environment=SENTRY_CONF=/etc/sentry
    ExecStart=/www/sentry/bin/sentry celery beat

**sentry-worker.service**

    [Unit]
    Description=Sentry Background Worker
    After=network.target
    
    [Service]
    Type=simple
    User=sentry
    Group=sentry
    WorkingDirectory=/www/sentry
    Environment=SENTRY_CONF=/etc/sentry
    ExecStart=/www/sentry/bin/sentry celery worker

**Comment by mattrobenolt** [comment]
I'd be open to a pull request. :) We don't use systemd ourselves, so we can't provide this documentation.

**Comment by LordMike** [comment]
Where should I place the files?

**Comment by mattrobenolt** [comment]
The gist of what you'd want can be found at https://github.com/getsentry/sentry/blob/master/docs/installation.rst#running-sentry-as-a-service but there are likely other places that reference supervisord as well.

**Comment by LordMike** [comment]
Gotcha. Heading to bed now - will check up tomorrow (hopefully).
