### ISSUE TITLE
User feedback entries (inside an issue) should link to corresponding event

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3303]
So you can see breadcrumbs and other per-session data corresponding to that feedback item.

**Comment by billyvg** [comment]
There seems to be at least frontend support for linking to events: https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/app/components/events/userFeedback.jsx#L32

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
