### ISSUE TITLE
Click on "Track issue in Jira" triggers error

### ISSUE THREAD

**Issue by x-merlin-x** [getsentry/sentry#33040]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Display an event,
Click on "Track issue in Jira"

### Expected Result

Track isue in Jira

### Actual Result

error page, reload or if this does not work contact support.

**Comment by ceorourke** [comment]
Hi @x-merlin-x this issue has now been fixed - the button was linking to the wrong page.
