### ISSUE TITLE
[Flaky CI]: Issue Details PII Tooltip Snapshot Flake

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry#33089]
### Flakiness Type

Visual Snapshot

### Name of Job

Visual Snapshot / Visual Snapshot

### Name of Test

acceptance-mobile/issue-details-pii-tooltips.png

### Link to Test Run

https://github.com/getsentry/sentry/pull/32592/checks?check_run_id=5745151966

**Comment by JoshFerge** [comment]
wonder if this would fix? https://github.com/getsentry/sentry/pull/29581

**Comment by udameli** [comment]
seeing another (new?) flake for the same test https://github.com/getsentry/sentry/pull/33264/checks?check_run_id=5822176863

**Comment by udameli** [comment]
and another one https://github.com/getsentry/sentry/pull/33747/checks?check_run_id=6098146382
