### ISSUE TITLE
On project notification settings, indicate if current user is opted into notifications for this project

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3310]
We've had users who are confused why they aren't seeing notifications for a project they created – unaware that they are opted out of some projects' notifications on a completely different page (`/account/settings/`).

**Comment by benvinegar** [comment]
May be related to #2878, but not really

**Comment by benvinegar** [comment]
See also #3922

**Comment by castlec** [comment]
@benvinegar is this still causing problems?

**Comment by benvinegar** [comment]
Notifications have been overhauled so significantly since that I don't think this should remain open. Thanks for getting my attention.
