### ISSUE TITLE
Cocoa* Support

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#3312]
# Swift/Obj-C

We have two newer SDKs -- [sentry-swift](https://github.com/getsentry/sentry-swift) and [sentry-objc](https://github.com/getsentry/sentry-objc) -- targeting Apple's platforms. This discusses the reasons both SDKs exist, and the path to completion.

We'll close out this ticket when full support lands, but until this this will be used as a guideline and discussion towards our approach.
## tl;dr
- Swift is our platform of choice for Cocoa*
- Obj-C is only supported for Unity
## sentry-swift
- Cocoa docs on getsentry.com reference only Swift SDK
- Build a shim on top of SDK (if needed) to ensure highly usable API for Objective-C users
- All usage examples in docs should show Swift usage first, and then ObjC usage (using same SDK)
- Note/callout on docs "Need to support iOS 7? Take a look at our legacy Objective-C SDK."
- Supports all Apple platforms (iOS, OS X, tvOS)
- Backed by KSCrash
## sentry-objc
- Future Unity docs reference Objective-C SDK
- Only needs to support iOS 7
- Note on docs "The Objective-C SDK is only used for older versions of iOS. You should migrate to the new Sentry SDK."
- Backed by KSCrash

/cc @mitsuhiko @kstenerud @joshdholtz

**Comment by benvinegar** [comment]
@HazAT – is there anything actionable here / worth keeping alive or can we close this?

**Comment by mitsuhiko** [comment]
sentry-swift and sentry-objc have been entirely deprecated and KSCrash is now shipped with sentry-cocoa which is the new library that handles both.
