### ISSUE TITLE
Styles for "leads-to-app"

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3317]
The feature to show the one frame leading up to the app frame was added because of support for Cocoa. But this has bled into every other language support without any special styling to indicate what this is and just looks incorrect in an "App Only" view.

For Cocoa styling looks like this for App Only: 
![image](https://cloud.githubusercontent.com/assets/375744/15523500/ab4a883a-21cf-11e6-86be-c95ac9d8dc7d.png)

And in Full view:
![image](https://cloud.githubusercontent.com/assets/375744/15523506/bd4fbbe0-21cf-11e6-9025-48d5edaae934.png)

Notice that the "leads-to-app" frames are highlighted in blue, and under Full, the system frames are grey.

I'm not sure if this styling should be applied elsewhere, since to me it seems like we wouldn't want to highlight "leads-to-app" frames in anything else, but unstyled as-is definitely looks wrong. Maybe we just want to dim the frames elsewhere?

@getsentry/ui @joshdholtz @mitsuhiko

**Comment by mitsuhiko** [comment]
Unfortunately I can't find the discussion any more but I was originally thinking of adding a little arrow that indicates that a call to the app happened.

**Comment by mattrobenolt** [comment]
> but I was originally thinking of adding a little arrow that indicates that a call to the app happened

If we go this route, or any permutation of this route, we definitely need to change this button of `App Only` to something else.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
