### ISSUE TITLE
Don't auto-select Password field on sudo with U2F

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3320]
When U2F is enabled, and I get a sudo prompt, the Password field is selected by default, meaning when I tap my key, the characters get dropped into Password field and submits the form, which would be incorrect.

I'm not sure of a correct workflow here, but this seems like if u2f is enabled, default to _only_ that, then have an option to click, "or enter in password", and switch over to that view.

@mitsuhiko

**Comment by mitsuhiko** [comment]
Not sure why the focus matters. U2F requires a yubikey to be in U2F mode. I assume this is an issue if U2F does not initialize and your yubikey falls back to OTP and it starts writing crap into the password field.

In U2F mode the yubikey directly invokes a browser API so the focus really does not matter.

**Comment by mattrobenolt** [comment]
Oh, then that's likely the issue. It was definitely erroring locally for me. I'll confirm in production.

**Comment by mattrobenolt** [comment]
Yeah, just confirmed. So this is invalid, but the error state is still an issue since that's what caused the confusion.
