### ISSUE TITLE
Event importance level for more flexible cleanup policy

### ISSUE THREAD

**Issue by Tab10id** [getsentry/sentry#33202]
### Problem Statement

We use sentry for both error catching and performance monitoring.
But error data is much more important than performance data.
In our case we want to store exceptions events permanently (or at least for much bigger period).

### Solution Brainstorm

As idea I propose to introduce importance level for events.
I understand that mass update of events can cause a performance problem for large databases but for most events we know imortance level even before actual send it to sentry.
That parameter will make retention process trivial and should solve problems with important data loss.

**Comment by Tab10id** [comment]
Yes, I'm on self-hosted sentry.

**Comment by Tab10id** [comment]
I want to attach some related discussion on sentry forum:

https://forum.sentry.io/t/cleanup-retention-by-errorlevel/9040
https://forum.sentry.io/t/automatic-deletion-of-issues/6664/12

A lot of topics about nodestore_node size
https://forum.sentry.io/search?q=nodestore

**Comment by horseBatteryStapler** [comment]
Wanted to post a +1 on this! Events data is much more important than transaction data for us; transaction data is a nice-to-have but the joined nature of the data in the nodestore_node table right now is making it very hard to scalably include transaction data on our self hosted setup.

Maybe a possible workaround would be to configure the `sentry-cleanup` job to specifically clean up only transactions, or clean up transactions & events on separate expiry-periods? That way we won't need any significant schema changes and the data model can stay the same.
