### ISSUE TITLE
Integrations/Plugins page broken when declare SENTRY_FEATURES in sentry.conf.py

### ISSUE THREAD

**Issue by ivnik** [getsentry/sentry#3321]
I upgrade new version 8.4.1

Add line in sentry.conf.py:
SENTRY_FEATURES = { 'auth:register': False } 

(because warning: The SENTRY_ALLOW_REGISTRATION setting is deprecated. Please use SENTRY_FEATURES["auth:register"] instead.)

After restart plugins page (/frontend/settings/plugins/) is empty and plugins settings page become unavailable (sentry-jira).

**Comment by dcramer** [comment]
Changing this setting wouldn't affect anything like you're talking about it.

- At the top of the file you have ``from sentry.conf.server import *``?
- You're restarting the server through the same way it was running before?
- Nothing changed in the virtualenv?

**Comment by naglis** [comment]
Hello @dcramer,

we are experiencing the same issue after upgrading to 8.4.1 and now to 8.5.0 -- the integrations list in a project's `/settings/plugins/` page is empty. Also, the settings page for previously enabled integrations redirects (HTTP 302) to project's settings page. The previously enabled integrations do work, it's just that we can't enable/disable/configure them.

To answer the three questions:

- Yes
- Yes
- No

Maybe there is something else I could do to debug this issue and provide more information?

**Comment by ryanbagwell** [comment]
I'm seeing this too in v8.4. The project's integrations page, i.e. /[org]/[project]/settings/plugins/, looks like this:

![screen shot 2016-06-06 at 11 22 33 am](https://cloud.githubusercontent.com/assets/365105/15827466/48b4df40-2bd9-11e6-9d3a-004f61c4606a.png)

Same answers to the questions as @naglis posted above.

**Comment by ryanbagwell** [comment]
@naglis I just fixed this on our end. See https://github.com/getsentry/sentry-github/issues/29

**Comment by naglis** [comment]
Thanks a lot @ryanbagwell! Indeed, I was reassigning the `SENTRY_FEATURES` dict instead of updating it.
