### ISSUE TITLE
Sentry 8.1.2 error:  TypeError: Object [object Object] has no method 'select2'

### ISSUE THREAD

**Issue by evan-ty** [getsentry/sentry#3326]
I have been getting this error from Sentry Internal.  
What does this mean, is my version of raven out of date?  
Will upgrading Sentry fix this, if not how can I go about resolving this issue?

```
TypeError: Object [object Object] has no method 'select2'
  at ready(~/jquery/dist/jquery.js:3433:0)
  at ready(~/jquery/dist/jquery.js:3417:0)
  at resolveWith(~/jquery/dist/jquery.js:3211:0)
  at fire(~/jquery/dist/jquery.js:3099:0)
  at apply(~/raven-js/src/raven.js:242:0)
  at HTMLDocument.<anonymous>(/auth/login/sentry/:268:17)
```

**Comment by mitsuhiko** [comment]
Your favorite bug.

**Comment by benvinegar** [comment]
@evan-ty – it's a bug in Sentry that we haven't figured out how to resolve yet. Best we can tell, it's occurring when someone visits a Sentry URL (e.g. an issue) via a URL generated by one of Google's link redirect services (google.com/url). Literally every error event we get is referred to by google.com/url. If you have any insight into how this was triggered, we're all ears.

**Comment by evan-ty** [comment]
@benvinegar 

Thanks for the explanation. Sucks to hear that it hasn't been resolved. 
That is strange phenomenon, I don't know how come an URL would be coming from Google in the first place.

If I find anything I will post here.

ps:  do you know if this bug has any effect on the stability of the sentry server which is monitoring production-grade apps?  Or is this something I can turn a blind eye to, for the time being?

**Comment by benvinegar** [comment]
> ps: do you know if this bug has any effect on the stability of the sentry server which is monitoring production-grade apps? Or is this something I can turn a blind eye to, for the time being?

As far as we can tell, it has something to do with a JavaScript library not loading correctly (a library, select2, that converts `<select>` HTML elements to look nicer). We believe the impact is low because nobody has contacted us with a support issue about it.

**Comment by markstory** [comment]
Closing as this issue has gone stale.
