### ISSUE TITLE
Notify commenting participants on issue status changes

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3329]
If I've commented on an issue, that means I'm likely showing interest in what's happening. So it'd be nice to notify me when the issue has gotten marked as resolved.

We could alternatively go a bit deeper and do "subscriptions" and allow a user to just subscribe to an issue to get notified, without actually commenting.

@getsentry/team

**Comment by JTCunning** [comment]
<img width="210" alt="screenshot 2016-05-25 10 26 31" src="https://cloud.githubusercontent.com/assets/1189446/15549810/3daa41be-2263-11e6-8f22-e83b54b9092e.png">

**Comment by gek0** [comment]
@JTCunning he probably meant in sentry itself, not on git.
Agree, it would be a nice feature.

![Comment on issue](https://i.imgur.com/iQ8lHly.png])

**Comment by mattrobenolt** [comment]
This is highly related to GH-3428 and GH-3430. Closing in favor of these since they cover the larger project.
