### ISSUE TITLE
Reduce Github required checks

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#33408]
### Problem Statement

We have too many and every time there's name changes we need to manually update a list via a UI. We also need to update Freight to match such list.

Currently, there's 26 of them:

- Visual Snapshot
- acceptance (3.8.12, 0)
- acceptance (3.8.12, 1)
- acceptance (3.8.12, 2)
- acceptance (3.8.12, 3)
- api docs test (3.8.12)
- backend lint (3.8.12)
- backend test (3.8.12, 0)
- backend test (3.8.12, 1)
- backend test (3.8.12, 2)
- chartcuterie integration (3.8.12, 0)
- check migration (3.8.12)
- cli test (3.8.12)
- frontend tests (0)
- frontend tests (1)
- frontend tests (2)
- frontend tests (3)
- getsentry / js build and lint
- plugins test (3.8.12)
- relay test (3.8.12)
- self-hosted-github-pr-check (sentryio)
- snuba test (3.8.12, 0)
- snuba test (3.8.12, 1)
- symbolicator test (3.8.12)
- typescript and lint
- webpack

### Solution Brainstorm

With careful analysis and some changes we can reduce this quite a bit.

**Comment by armenzg** [comment]
@mitsuhiko @joshuarli @billyvg If you have any objections please let me know. I will start preparing the PRs tomorrow

**Comment by joshuarli** [comment]
> @mitsuhiko @joshuarli @billyvg If you have any objections please let me know. I will start preparing the PRs tomorrow

SGTM. Lemme know when you need the Frieght adjustments, I can do those.

**Comment by armenzg** [comment]
> > @mitsuhiko @joshuarli @billyvg If you have any objections please let me know. I will start preparing the PRs tomorrow
> 
> SGTM. Lemme know when you need the Frieght adjustments, I can do those.

Super! Thanks @joshuarli ! For now, we need to wait until #33454 merges. However, a draft PR can already be worked on. The new checks will be named:

- acceptance / Acceptance
- frontend / Frontend
- backend / Backend

**Comment by billyvg** [comment]
@armenzg btw, Freight *only* checks `getsentry`'s github context.

**Comment by armenzg** [comment]
I believe at the beginning of the week (or the one before) I reduced the required checks on Sentry and we have not had any fall outs. See the screenshot for our current set of required checks [1].

On Monday, I will merge skipping jobs at the job level rather than per step:
https://github.com/getsentry/sentry/pull/34004

I'm now making these changes to the getsentry repo.

[1]
<img width="691" alt="image" src="https://user-images.githubusercontent.com/44410/167137032-dc5f4c25-5cb1-42bd-95d7-7a1ff756343f.png">
