### ISSUE TITLE
Project not visible on issue via mobile screen dimensions

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3343]
In the example below, the organization is "Sentry" and the project is "Earth":

![image](https://cloud.githubusercontent.com/assets/2153/15584127/00acfcae-232e-11e6-8977-db14bb38c8b5.png)

Only the organization is visible.

**Comment by MaxBittker** [comment]
![screenshot 2016-11-03 16 03 07](https://cloud.githubusercontent.com/assets/5915546/19988724/08bc089c-a1df-11e6-8878-9b695ec8c824.png)
![screenshot 2016-11-03 16 03 01](https://cloud.githubusercontent.com/assets/5915546/19988725/08d6e4d2-a1df-11e6-96d1-2dc9efbabec0.png)
 looks like this is fixed on new design. (related events hitting the second row is kind of gross but not nearly as bad)
