### ISSUE TITLE
Filtering events by date

### ISSUE THREAD

**Issue by rreynier** [getsentry/sentry#3347]
It would be extremely useful to somehow filter by date.  

Lets say for example support comes to me and says "we had X problem 3 days ago".  Right now, I have no good tools to navigate to errors that occurred during this timeframe.  Lets say the problem was Exception Y.  The problem is, Exception Y just occurred two minutes ago, but also 5 hours ago, and also 3 days ago (the problem reported by support).  So now if I just go back in time.. Exception Y only shows as having occurred two minutes ago.  Essentially I have to just start perusing through entries in Sentry and looking at occurrences/events for them to find a match to my time frame. 

Is anything in the works to address this kinda thing?

Having a time sorted / searchable list of events would be amazing!  It can also help you understand scope of errors around that same time since maybe some of it correlates.

**Comment by dcramer** [comment]
This already exists in the current versions of sentry. Take a look at the search docs for more details.
