### ISSUE TITLE
[Flaky CI]: `acceptance/dashboards-change-from-area-chart-to-big-number-keeps-height.png`

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/sentry#33479]
### Flakiness Type

Visual Snapshot

### Name of Job

Visual Snapshot

### Name of Test

acceptance/dashboards-change-from-area-chart-to-big-number-keeps-height.png

### Link to Test Run

https://github.com/getsentry/sentry/pull/33460/checks?check_run_id=5888470174

**Comment by udameli** [comment]
saw a flake https://github.com/getsentry/sentry/pull/34454/checks?check_run_id=6391124783

**Comment by markstory** [comment]
While this test was flaky, it no longer exists. ✨
