### ISSUE TITLE
Replay details crash if there is malformed JSON in attachments

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#33504]
It's possible to have corrupt replay data which we will not be able to parse as JSON. e.g. the client disconnects before the upload is completed.

For now, we should display an error message letting them know the replay data was corrupted and attempt to render the rest of the page.

**Comment by billyvg** [comment]
@ryan953 hmm not on hand, but iirc, this should be semi resolved from your change w/ display an error message when there are no events. (The error was popping up in the fetch replay hook).

**Comment by ryan953** [comment]
I couldn't find an example of this exact issue, but I did find another fatal error: `Cannot read properties of undefined (reading 'span_id')`

It's happening to a few of our examples, the important bigs of the stacktrace are:
```
 eval
  app/components/events/interfaces/spans/utils.tsx:320:17
 parseTrace
  app/components/events/interfaces/spans/utils.tsx:319:42
 new SpansInterface
  app/components/events/interfaces/spans/index.tsx:67:71
```

I'll work on handling that, the overall improved error handling should mean corrupt data is handled better too.... if not we'll open another issue later on.
