### ISSUE TITLE
Change Tag Searches to target Related Events

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#3351]
Within an issue we have several locations that link tags to the issues search. This is a proposal to change those links to point to Related Events, thus letting you (attempt to) find relevant events. Within that search we could also have a quick link to "Find similar issues in this project" which can just copy paste the query into the issues tab.

This is at least:
- Links in tag values lists (Tags > [Tag Key])
- Links in tag list on event details

@getsentry/ui

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
