### ISSUE TITLE
Crash Report Take Two

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#3352]
We want to introduce a new crash report format that replaces the apple specific "apple crash report" format. The idea is to keep the apple code around until all the clients are migrated to the new format.

The idea is that we launch all clients on the old format, fix bugs there and then migrate over to the new format over the next few weeks.

What needs to be done:
- [ ] server side supports a platform tag on a per-frame basis
- [ ] add a new "sentry.interfaces.CrashReport" interface
- [ ] later deprecate "sentry.interfaces.AppleCrashReport'

New format for "sentry.interfaces.CrashReport":

```
{
  "debug_images": [
    {
      "type": "apple",
      "cpu_subtype": 9,
      "cpu_type": 12,
      "image_addr": 749568,
      "image_size": 262144,
      "image_vmaddr": 16384,
      "name": "/private/var/mobile/Containers/Bundle/Application/436352A9-1BE2-4934-9C6F-237CC7DFF27B/Crash-Tester.app/Crash-Tester",
      "uuid": "8094558B-3641-36F7-BA80-A1AAABCF72DA"
    }
  ],
  "threads": [
    {
      "crashed": true,
      "current_thread": true,
      "exception": {
        "type": "TheErrorClass",
        "module": "optional.module",
        "value": "The error message",
        "stacktrace": {
          "frames": [
            {
              "type": "apple",
              "instruction_addr": 653426999,
              "object_addr": 652337152,
              "object_name": "CoreFoundation",
              "symbol_addr": 653426872,
              "symbol_name": "<redacted>"
            },
            {
              "type": "sentry",
              "platform": "javascript",
              "filename": "foo.js",
              "function": "foo()"
            }
          ]
        }
      }
    }
  ]
}
```

We can decide if we want to support the `system` key on the new format or if the clients are supposed to report this in the correct sentry interfaces instead.

**Comment by kstenerud** [comment]
We can't put `stacktrace` inside exception because the rest of the threads will have stack traces but no exception.

**Comment by mitsuhiko** [comment]
@kstenerud i think for those cases we could have the stacktrace reported on the same level as `error` but as `stacktrace`.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
