### ISSUE TITLE
Add a line or area chart that graphs the free + used js memory

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#33623]
Note: this data is currently (Apr 14) not collected by the SDK yet, but imagine a dataset similar to: `[timestamp, {used: number, free: number}]`

We have a number of existing charting components that wrap [`echarts`](https://echarts.apache.org/en/index.html) in `app/components/charts`. We would like to chart memory usage over time on the Replays Details page.

**Comment by Danondso** [comment]
@Jesse-Box is there a figma for the details page that I can work off of for this?
