### ISSUE TITLE
Split the front-end gettext code to a NPM package so it can be reused

### ISSUE THREAD

**Issue by mandx** [getsentry/sentry#3363]
It would be really awesome if the [locale.jsx module](https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/app/locale.jsx) is separated into a npm package and published to https://npmjs.com, so it can be reused.

I have been looking around and so far the way you guys handle the translations (specially the React integration) is both the most flexible for developers and the least intrusive for translators.

It would really help in some of my projects (React + Django), both open-source and commercial.

In case this is set as `wontfix`: Is it possible to legally extract some of that code and use it in some of my commercial projects?

Thanks!

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
