### ISSUE TITLE
How to solve Internal project (id=1) does not exist which I delete it from UI click unexpected。

### ISSUE THREAD

**Issue by linsmalldragon** [getsentry/sentry#3370]
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker --- * ***  * -- Linux-3.13.0-85-generic-x86_64-with-Ubuntu-14.04-trusty
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker -- * - **** ---
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker - ** ---------- [config]
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker - ** ---------- .> app:         sentry:0x7efc88787750
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker - ** ---------- .> transport:   redis://localhost:6379//
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker - ** ---------- .> results:     disabled
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker - *** --- * --- .> concurrency: 1 (prefork)
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker -- ******* ----
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker --- ***** ----- [queues]
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker  -------------- .> alerts           exchange=default(direct) key=alerts
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker                 .> auth             exchange=default(direct) key=auth
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker                 .> cleanup          exchange=default(direct) key=cleanup
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker                 .> counters-0       exchange=counters(direct) key=
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker                 .> default          exchange=default(direct) key=default
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker                 .> digests.delivery exchange=default(direct) key=digests.delivery
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker                 .> digests.scheduling exchange=default(direct) key=digests.scheduling
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker                 .> email            exchange=default(direct) key=email
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker                 .> events           exchange=default(direct) key=events
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker                 .> merge            exchange=default(direct) key=merge
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker                 .> options          exchange=default(direct) key=options
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker                 .> search           exchange=default(direct) key=search
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker                 .> triggers-0       exchange=triggers(direct) key=
May 30 22:28:52 iZ284ni6b9yZ supervisord: sentry-worker                 .> update           exchange=default(direct) key=update
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron [2016-05-30 14:28:54,068: INFO/MainProcess] Scheduler: Sending due task flush-buffers (sentry.tasks.process_buffer.process_pending)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron [2016-05-30 14:28:54,076: ERROR/MainProcess] Message Error: Couldn't apply scheduled task flush-buffers: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that m$
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron ['  File "/var/www/sentry/bin/sentry", line 11, in <module>\n    sys.exit(main())\n', '  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 148, in main\n    cli(prog_name=get_pro$
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron Traceback (most recent call last):
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/beat.py", line 204, in maybe_due
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     result = self.apply_async(entry, publisher=publisher)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/beat.py", line 260, in apply_async
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     entry, exc=exc)), sys.exc_info()[2])
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/beat.py", line 252, in apply_async
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     **entry.options)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/celery.py", line 44, in apply_async
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     return OriginalTask.apply_async(self, *args, **kwargs)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/app/task.py", line 559, in apply_async
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     **dict(self._get_exec_options(), **options)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/app/base.py", line 353, in send_task
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     reply_to=reply_to or self.oid, **options
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     **kwargs
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     routing_key, mandatory, immediate, exchange, declare)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/connection.py", line 436, in _ensured
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     return fun(*args, **kwargs)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/messaging.py", line 188, in _publish
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     mandatory=mandatory, immediate=immediate,
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 521, in basic_publish
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     message, exchange, routing_key, **kwargs
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/transport/virtual/exchange.py", line 61, in deliver
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     _put(queue, message, **kwargs)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 688, in _put
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     client.lpush(self._q_for_pri(queue, pri), dumps(message))
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 1227, in lpush
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     return self.execute_command('LPUSH', name, *values)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 573, in execute_command
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     return self.parse_response(connection, command_name, **options)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 585, in parse_response
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     response = connection.read_response()
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/connection.py", line 582, in read_response
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     raise response
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron SchedulingError: Couldn't apply scheduled task flush-buffers: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please$
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron [ERROR] Internal project (id=1) does not exist
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron [2016-05-30 14:28:54,114: INFO/MainProcess] Scheduler: Sending due task sync-options (sentry.tasks.options.sync_options)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron [2016-05-30 14:28:54,120: ERROR/MainProcess] Message Error: Couldn't apply scheduled task sync-options: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that ma$
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron ['  File "/var/www/sentry/bin/sentry", line 11, in <module>\n    sys.exit(main())\n', '  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 148, in main\n    cli(prog_name=get_pro$
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron Traceback (most recent call last):
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/beat.py", line 204, in maybe_due

 File "/var/www/sentry/local/lib/python2.7/site-packages/celery/app/task.py", line 559, in apply_async
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     **dict(self._get_exec_options(), **options)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/app/base.py", line 353, in send_task
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     reply_to=reply_to or self.oid, **options
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     **kwargs
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     routing_key, mandatory, immediate, exchange, declare)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/connection.py", line 436, in _ensured
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     return fun(*args, **kwargs)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/messaging.py", line 188, in _publish
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     mandatory=mandatory, immediate=immediate,
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 521, in basic_publish
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     message, exchange, routing_key, **kwargs
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/transport/virtual/exchange.py", line 61, in deliver
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     _put(queue, message, **kwargs)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 688, in _put
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     client.lpush(self._q_for_pri(queue, pri), dumps(message))
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 1227, in lpush
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     return self.execute_command('LPUSH', name, *values)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 573, in execute_command
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     return self.parse_response(connection, command_name, **options)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 585, in parse_response
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     response = connection.read_response()
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/connection.py", line 582, in read_response
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     raise response
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron SchedulingError: Couldn't apply scheduled task flush-buffers: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please$
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron [ERROR] Internal project (id=1) does not exist
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron [2016-05-30 14:28:54,114: INFO/MainProcess] Scheduler: Sending due task sync-options (sentry.tasks.options.sync_options)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron [2016-05-30 14:28:54,120: ERROR/MainProcess] Message Error: Couldn't apply scheduled task sync-options: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that ma$
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron ['  File "/var/www/sentry/bin/sentry", line 11, in <module>\n    sys.exit(main())\n', '  File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 148, in main\n    cli(prog_name=get_pro$
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron Traceback (most recent call last):
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/beat.py", line 204, in maybe_due
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     result = self.apply_async(entry, publisher=publisher)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/beat.py", line 260, in apply_async
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     entry, exc=exc)), sys.exc_info()[2])
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/beat.py", line 252, in apply_async
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     **entry.options)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/celery.py", line 44, in apply_async
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     return OriginalTask.apply_async(self, *args, **kwargs)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/app/task.py", line 559, in apply_async
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     **dict(self._get_exec_options(), **options)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/app/base.py", line 353, in send_task
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     reply_to=reply_to or self.oid, **options
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/celery/app/amqp.py", line 305, in publish_task
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     **kwargs
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     routing_key, mandatory, immediate, exchange, declare)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/connection.py", line 436, in _ensured
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     return fun(*args, **kwargs)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/messaging.py", line 188, in _publish
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     mandatory=mandatory, immediate=immediate,
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 521, in basic_publish
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     message, exchange, routing_key, **kwargs
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/transport/virtual/exchange.py", line 61, in deliver
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     _put(queue, message, **kwargs)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 688, in _put
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     client.lpush(self._q_for_pri(queue, pri), dumps(message))
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 1227, in lpush
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     return self.execute_command('LPUSH', name, *values)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 573, in execute_command
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     return self.parse_response(connection, command_name, **options)
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/client.py", line 585, in parse_response
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     response = connection.read_response()
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron   File "/var/www/sentry/local/lib/python2.7/site-packages/sentry/../redis/connection.py", line 582, in read_response
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron     raise response
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron SchedulingError: Couldn't apply scheduled task sync-options: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please $
May 30 22:28:54 iZ284ni6b9yZ supervisord: sentry-cron [ERROR] Internal project (id=1) does not exist

**Comment by linsmalldragon** [comment]
And the same time redis log says: Can't allocate memory when persist data.

**Comment by mattrobenolt** [comment]
This is a cascading issue. The main issue is the redis problem. Redis commands are erroring, but Sentry itself tries to log it's own errors to the internal project. But in turn, since you deleted the internal project, it's unable to log it's own errors.
