### ISSUE TITLE
Design: Timeline could visually compress inactive periods

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#33727]
## Problem
As a user I may not care about the periods of time in the timeline where there is zero activity. It would be nice if we could have a view where it compresses down the whitespace so that it's easier to see batches of events. Likewise, we should allow for them to see the timeline fully expanded to get a sense of inactivity scale for the session.

**Comment by ryan953** [comment]
This could represent the behavioral change needed (exact css is tbd): 

![Image](https://user-images.githubusercontent.com/187460/176316732-c9904c71-9f13-4ad1-88bb-350d06a847b7.png)

**Comment by Jesse-Box** [comment]
Hey @billyvg @ryan953, I had some time to look into this problem. Let me know what you think.

[Figma Link](https://www.figma.com/file/dsjzlr0Zh3fwuizEWa0at3/Specs%3A-Compress-Inactive-Times?node-id=0%3A1&t=JgMyS3E3gnAN05yQ-1)

### What we have currently
The "Fidelity" of the event timeline and the player is determined by the session's total replay duration.
![Image](https://user-images.githubusercontent.com/6508377/203973218-1ed6d8cc-ac06-40be-b67f-debe019d22ad.png)

### What I'm proposing
We technically define what inactivity means, and based on our definition, we in effect slice time away from the replay, increasing the overall fidelity of the event timeline.
![Image](https://user-images.githubusercontent.com/6508377/203973229-3f80f5ab-33f2-4f1d-8b0c-262d57f9e61b.png)

### Thinks to note
1. The event timeline shows period of inactivity in relation to the total duration of the session
2. However, the player's "finish time" is calculated by session duration minus inactive period
3. We add the same UI component throughout the various organisms to anchor the user on what happens before and after set inactivity
![Image](https://user-images.githubusercontent.com/6508377/203973239-c8846502-8ffc-442e-bdb3-bb3a88ac431a.png)

**Comment by benvinegar** [comment]
I think we need something between what you're proposing and what Ryan has. Being able to see at a glance the "empty" sections helps communicate the story of the timeline. If we reduce that to a line you can't glance at the timeline and understand that – actually – there were huge periods of inactivity (unless you manually scroll over it).

I think Ryan's treatment makes it more obvious that "something amiss" has occurred during this section. I'm not sure the line communicates enough.

**Comment by benvinegar** [comment]
I do appreciate how the line treatment works in other areas though like the console. I think that is valuable.

**Comment by Jesse-Box** [comment]
Thanks for the @benvinegar I'll go back to the drawing board using the original proposal as guidance.

**Comment by Jesse-Box** [comment]
@billyvg @ryan953 

Last Friday, I showed my sketches for improving our tracing view to the product design team and Vu tangentially raised the same issue as this ticket. When designing charts, “Axis Breaks” or "Broken Axis" are often utilized when the value of a few data is largely deviating from the values of most of the others.


Example 1
![Image](https://github.com/getsentry/sentry/assets/6508377/b8f3d2fa-ec4d-4f7b-8202-a0bb3fe494d2)

Example 2

![Image](https://github.com/getsentry/sentry/assets/6508377/2838fe35-9563-4345-ae80-b8b9593902ac)

Perhaps we can lean on this existing design pattern for increasing the resolution of our event timeline?

**Comment by billyvg** [comment]
@Jesse-Box Isn't this pattern very similar to https://github.com/getsentry/sentry/issues/33727#issuecomment-1169362492?
