### ISSUE TITLE
"Open URL" icon is confusing – users expect it to open new tab/page

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3373]
![image](https://cloud.githubusercontent.com/assets/2153/15720479/7296a9b8-27e9-11e6-828a-cbe1244673cb.png)

Some users have commented that the "open URL" icon (seen above) affixed to some URLs in Sentry is confusing – it looks like it should open a new tab/page, but it does not. If they do not CMD + Click the link, they leave the React app.

Thoughts:
- should it just open a new tab/page?
- or should we consider a different icon? are there alternative icons?

**Comment by sagiavinash** [comment]
thanks @benvinegar for raising an issue. awesome feedback loop

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
