### ISSUE TITLE
Scrubbing in Replays is slow/laggy

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#33730]
e.g. this replay: https://sentry.io/organizations/sentry-emerging-tech/replays/billy-test:20052048ae0c4323922af0b26e086182/

It is not very responsive when you drag the scrubber around. (e.g. press play and drag to middle of the bar).

**Comment by ryan953** [comment]
I went through the video but after the ~3:45 point it's just displaying the 'Failed to compile' message. Dragging the scrobber around earlier than that.. i do see the links in the nav bar flash blue while css is being applied, but nothing major.

Could be a hardware though.
The scrobber is not smooth after tell Chrome to throttle my CPU to be 4x slower. Dragging from the middle of the video towards the end is not the worst, but going backwards in time is really janky. Sliding left to right from the 1/2 way point to 3/4 and back is also janky.

Maybe some throttling on the mouse inputs would help. Also some caching of the `currentTime` or expected-current-time would make the <ReplayBasicTimeline> and <ReplayCurrentTime> components to look more responsive.

**Comment by ryan953** [comment]
Idea is: 
- memoize the expected timestamp, so that the scrobber and currentTime view is always up to date and looks it's snappy
- show loading/buffering overlay on the video
- hide that overlay then the rrweb `currentTime` maatches the memoized/expected `currentTime`
