### ISSUE TITLE
Collapse exception/stack trace if over X frames

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3375]
Some platforms send a ton of frames, and without quick links to HTTP request / package / other interface areas below, it can be really annoying to scroll to the bottom.

**Comment by MaxBittker** [comment]
@benvinegar curious, do you remember what platforms are usual causes of this?

**Comment by benvinegar** [comment]
Rails, JavaScript w/ frameworks ... nobody has commented on this or +1'd it so I don't think it's a priority. Might even close.

**Comment by MaxBittker** [comment]
going for it
