### ISSUE TITLE
Disable the selection filters guides on Replay Index

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#33763]
![image](https://user-images.githubusercontent.com/79684/164114716-ebca78da-8a1c-46ad-bb46-9c392de7d604.png)

This is a new feature, so I don't think it makes sense to show this here.

**Comment by billyvg** [comment]
@davidenwang what do you think w/r/t showing this guide here?

**Comment by evanpurkhiser** [comment]
It won't show after you click it away on any page. do we actually care about this?

**Comment by billyvg** [comment]
@evanpurkhiser yeah just thinking about minimizing the number of popups and if this one makes sense. e.g. this doesn't for new orgs who have never used Sentry before (and kinda likewise here since this is a new view).
