### ISSUE TITLE
Can reveive issue stats, but events cannot show

### ISSUE THREAD

**Issue by llitfkitfk** [getsentry/sentry#3381]
version 8.4.1 sentry in docker

**Comment by mattrobenolt** [comment]
I'm not fully sure what this means. Can you provide more details? Is something erroring? Are you running everything correctly?

**Comment by llitfkitfk** [comment]
![image](https://cloud.githubusercontent.com/assets/2404785/15734787/aa79a312-28c5-11e6-8c3e-d61f25d57fea.png)
selected the first, then 

![image](https://cloud.githubusercontent.com/assets/2404785/15734798/c515b15c-28c5-11e6-95ec-df6fc894ac47.png)

**Comment by mattrobenolt** [comment]
This looks like you're not running the workers. Events are being accepted in the web process, being added to the queue, but nothing is then pulling them off the queue to process.

**Comment by llitfkitfk** [comment]
selected the second
![image](https://cloud.githubusercontent.com/assets/2404785/15734853/2de2d94e-28c6-11e6-9fb2-78cb8d1a7d1a.png)

**Comment by llitfkitfk** [comment]
@mattrobenolt I will try

**Comment by llitfkitfk** [comment]
@mattrobenolt Thx, I try add db environment  for celery work & beat, It's worked
