### ISSUE TITLE
Infinite loop in sqlquerycount (PostgreSQL)

### ISSUE THREAD

**Issue by shwhl** [getsentry/sentry#3382]
I'm having same issue as #3185, but I'm using PostgreSQL and use the latest code, which should already fixed this issue.
The error log is just same as in #3185, except the line number changed, but the error code is same.
@mitsuhiko @dcramer

**Comment by shwhl** [comment]
json error here.
[error.txt](https://github.com/getsentry/sentry/files/295502/error.txt)

**Comment by mattrobenolt** [comment]
Going to mark this as closed and shouldn't exist in 8.5+.
