### ISSUE TITLE
Investigate: Cross Project Search / Filtering

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#3385]
This came up a few times in support already: basically the ability to look across projects. It's mostly not searching but filtering by assignment status / unassigned for the entire team.

**Comment by scottolsen** [comment]
This would be very useful to see something similar to Zendesk's filtering that has an easy way to see my open tickets and tickets not assigned to anyone across all projects.

![entrepreneurial_technologies_-_agent](https://cloud.githubusercontent.com/assets/113754/15749753/2549af32-28a9-11e6-9bb3-2ab4e7a62d65.png)

**Comment by masochist** [comment]
This would be extremely helpful for triaging issues, as well. I have a number of issues I'm working with. We just deployed sentry for our services, and as you can imagine, there are a number of issues coming up to look through. Not being able to see issues that are unassigned, or even sort by who's assigned, means it's a lot harder than it should be to triage.

**Comment by hjanuschka** [comment]
+1 from me, we have one Group with a gazillion of projects, and would love to see a group based, issue list + filter

**Comment by Diggsey** [comment]
Any news on this? The releases API basically forces us to have a different project for each of our microservices if we want to use sentry properly, and yet if we do that we'll have no dashboard to see new/unresolved events!

**Comment by billyvg** [comment]
Good news, [Sentry now supports cross project issues](https://blog.sentry.io/2019/03/06/new-features-greater-visibility#cross-project-issues)
