### ISSUE TITLE
Add "other projects" to Events by Project view on Stats page for transparency 

### ISSUE THREAD

**Issue by fredfalcon** [getsentry/sentry#3387]
We noticed a spike in errors on Sentry recently and were puzzled as to where they were coming from.  It turns out that we were not part of the team in Sentry.  We found this out after emailing Sentry about it and discovering we were unable to see the projects from a direct link to the error.  One of our developers suggested that it will be good to have an "other projects" line on the Stats page so when seeing the spike it will make sense where they are coming from.  Please see the screenshot below:
![image](https://cloud.githubusercontent.com/assets/7475382/15754581/ba5731c2-28c6-11e6-8961-741a97ae6e14.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
