### ISSUE TITLE
Highlight linked error when navigating to Replay Details from an error event (e.g. via Issue Details)

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#33887]
Todo:
Clicking "View Details" should take you to the details page
1. Deeplink to the timestamp when the error happened (maybe 5seconds earlier?)
2. The video timestamp on this page is set to be when the error happened (maybe 5seconds earlier?)
3. Deeplink to the console tab, that's filtered to only show Errors. (depends on [#38881](https://github.com/getsentry/sentry/issues/38861))

<img width="776" alt="189403724-66efbe14-c44f-46d1-bc74-cf81519bc123" src="https://user-images.githubusercontent.com/187460/190506365-5061acf1-96fc-447b-b6de-7cf0b360dbc8.png">

**Comment by ryan953** [comment]
Some updates after discussion related to dex: 
1. We're going to remove the query param that sets the filter to only be errors: remove ` f_c_logLevel: 'error',`
    This is because we're coming from the errors page, so people know what the error is and can find it easily. They're going to want to see all new information when they switch pages, so we should be showing all the console messages.
2. We're going to deep-link into the exact timestamp when the error happened.
    The `5 seconds before` was kind of arbitrary and people can easily navigate to do that on their own. We should take people to the exact spot so they don't get lost looking at something else.
