### ISSUE TITLE
Add "Send test email" button to account notification settings

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3394]
To help users verify mail delivery is working / configured correctly without having to trigger an event.

**Comment by fredvd** [comment]
@benvinegar 

This has been implemented now, but see #3990 for an issue that the testing function doesn't use the normal e-mail path through the worker, but sends the e-mail probably directly from the django web process.

**Comment by BYK** [comment]
This is now working (except #3990, yes)
