### ISSUE TITLE
Share page in some circumstances keeps reloading

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#3395]
In certain circumstances the event share page has been reported to reload constantly.

Example event from sentry's payment backend: https://app.getsentry.com/share/issue/312e313330383536353235/

**Comment by josketres** [comment]
I can reproduce it reliably opening the link in incognito mode (Version 50.0.2661.102 (64-bit))

**Comment by mitsuhiko** [comment]
I think this might be a global handler that detects an authentication failure against /internal/health/
