### ISSUE TITLE
Border and padding polishing

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#33968]
The replays index page looks a bit off in terms of padding and border. There is a border-bottom missing between the header and body here:

![image](https://user-images.githubusercontent.com/79684/165362317-a00c0739-edb2-49a0-b77f-2ad61ff235e2.png)

Compare this to Alerts:

![image](https://user-images.githubusercontent.com/79684/165362372-852eef9e-85e1-4c73-94ed-f31e4d3cd9c4.png)

Also the padding around the body content is a bit smaller than other pages:

![image](https://user-images.githubusercontent.com/79684/165362455-9a81cb7e-f931-4070-90e8-13c3496bbea1.png)

Compare to Alerts:
![image](https://user-images.githubusercontent.com/79684/165362496-e5c56e4f-5491-4225-b51f-e2ac2c6eeec0.png)

Lets make the Replays more consistent with the rest of the application.

**Comment by Danondso** [comment]
I'm also adjusting the search bar being fatter than the dropdown filters.
