### ISSUE TITLE
Audit log crash on IPv6

### ISSUE THREAD

**Issue by rdoursenaud** [getsentry/sentry#3416]
Affected version: 8.5.0

I was just saving some preferences and faced this error:
```
DataError: ERREUR:  syntaxe en entrée invalide pour le type inet : « 2001 »
LINE 1: ...oursenaud@gpcsolutions.fr', 2, NULL, 1, NULL, 11, '2001', 'e...
                                                             ^

SQL: INSERT INTO "sentry_auditlogentry" ("organization_id", "actor_label", "actor_id", "actor_key_id", "target_object", "target_user_id", "event", "ip_address", "data", "datetime") VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING "sentry_auditlogentry"."id"
```

Looks like IPv6 addresses are not handled properly.

Also reproduced by deleting a project.
Oddly this wasn't triggered on project creation and my IPv4 was logged instead of my IPv6.

**Comment by mattrobenolt** [comment]
I think there's something else going on here. The column in the database is typed `inet` which would cover both ipv4 and ipv6. But somehow you're getting the value `2001`.

It seems that we're messing up parsing this in the `SetRemoteAddrFromForwardedFor` middleware.

/cc @JTCunning wanna take a look at this?

**Comment by mattrobenolt** [comment]
Seems we would have regressed here: https://github.com/getsentry/sentry/pull/3239

**Comment by rdoursenaud** [comment]
Yes, looks like it.
2001 is the first part of my IPv6 address ```2001:470:[something]```(I use a Huricane Electric tunnel).

**Comment by JTCunning** [comment]
@rdoursenaud: Thanks for pointing this out. The fix is pretty simple, and I'll whip up some tests to make sure that we aren't blindly separating IPs.

**Comment by rdoursenaud** [comment]
@JTCunning Great!
Thank YOU all @getsentry for the awesome work :)
