### ISSUE TITLE
Rule triggered when it shouldn't

### ISSUE THREAD

**Issue by sigismund** [getsentry/sentry#3418]
I created a webhook rule with following rules:
```
Every time all of these conditions are met:
An event is seen
An event's level is greater than or equal to Error	
An event is seen more than 1  times in one minute
```
But I am still getting 'Warning' logs to my callback script.

I am not using self hosted version so I am not sure if this 'issue' is present in self-hosted version.

**Comment by dcramer** [comment]
Are you certain "all" is selected? Are you certain its not generated via another rule? What version of Sentry?

**Comment by mattrobenolt** [comment]
I wonder if related to https://github.com/getsentry/sentry/pull/3412 ?

**Comment by tkaemming** [comment]
Closing this since there's not much information to work with here. If you're still experiencing this, let us know.
