### ISSUE TITLE
[Question] Sentry Architecture

### ISSUE THREAD

**Issue by fatagun** [getsentry/sentry#3419]
Hello, 

I am curious about sentry architecture, ie: how do you collect events? what happens to event when it hits the API? where does redis fits in? What do you store in redis? how do you aggregate? what do you write to postgres? 

![redis](https://cloud.githubusercontent.com/assets/987005/15824882/09b85e26-2c0a-11e6-8e1d-91aabb27be0c.PNG)

Can you please help me understand these? Do you have an architectural diagram?

Thanks.

**Comment by dcramer** [comment]
We do not have any public material on how the architecture works. You're welcome to read the source code, but it's not a simple product and quite a large number of simple concepts make up sentry.

**Comment by fatagun** [comment]
It is a great product, that is why I was curious. Thanks anyway.

**Comment by dcramer** [comment]
@fatagun you can learn about most pieces that aren't a standard lamp stack by looking at sentry/app.py. Most systems have a common entry point that we try to keep fairly simple and document.

**Comment by huoteng** [comment]
@dcramer I quite agree with @fatagun .

If there is an architecture diagram, will let me more confident to adjust the config of Sentry.
