### ISSUE TITLE
Filter the chapters component so we only show `ui.click`, `error` & `navigation` crumbs

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#34224]
Types other than `ui.click` `fetch` and `navigation` should be ignored by the Chapter component.

**Comment by SDaian** [comment]
This feature was done on #33898

**Comment by ryan953** [comment]
Sorry, i made a typo in the title of this

The title was originally: "only show ui.click, fetch & navigation crumbs"

it should be: "only show ui.click, error & navigation crumbs"

Error should be shown. fetch should not.
