### ISSUE TITLE
Add a button to toggle between relative and absolute timestamps in the chapters component

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#34225]
The existing breadcrumb component has a button at the top of the "time" column to toggle between the two modes:
<img width="174" alt="Screen Shot 2022-05-05 at 12 31 56 AM" src="https://user-images.githubusercontent.com/187460/166728102-f9d250b5-d99a-4a81-9ee2-bf37079f8e93.png">

Since we are showing a time in the Chapter component, it could work in the same way.

**NOTE:**
When we render the relative time, it should be relative to the start of the replay: `event.startTimestamp`.

The time increments from there. You can imagine an example page where the data looks like this:

| ------ | ---- | --- |
| event type | abs. time | rel. time |
| ------ | --- | --- |
| navigate | 3:45:00pm | 0s |
| click | 3:46:30 | 90s |
| click | 3:46:45 | 105s |
| fetch | 3:46:46 | 106s |

The relative time is a positive number, incrementing after the replay start time

**Comment by SDaian** [comment]
hey, @ryan953 think the Event Chapters component doesn't have a columns header, think we need to re-think this.

What do you think @Jesse-Box ?

**Comment by ryan953** [comment]
At minimum we could add a tooltip to the relative time display so people can hover and see the full date/time.

**Comment by Jesse-Box** [comment]
> At minimum we could add a tooltip to the relative time display so people can hover and see the full date/time.

@SDaian @ryan953 I think @ryan953 suggestion is the right way of approaching this task. Below are a few examples of a pattern that we should follow for signifying tooltips over text. I'm pretty sure the styling comes out of the box, so I would investigate this before trying to style this yourself.

Alerts
<img width="810" alt="Screen Shot 2022-05-09 at 09 52 21" src="https://user-images.githubusercontent.com/6508377/167365078-35c2e1aa-4f3d-40ba-a0e1-f393524d560b.png">

Issues
<img width="452" alt="Screen Shot 2022-05-09 at 09 54 08" src="https://user-images.githubusercontent.com/6508377/167365345-14b47a7e-892b-4979-90d5-c7f6d5f4b1ea.png">

**Comment by SDaian** [comment]
Sounds good to me! Thanks.
