### ISSUE TITLE
Clicking on an item in the Chapter component should tell the player to start the video from that timestamp

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#34227]
The Chapter component can become a quick way for people to jump into interesting parts of the replay video.

By clicking on a Chapter item, the video should move to the timestamp when that action happens.

**Comment by SDaian** [comment]
This issue was done on the same commit of #33898

**Comment by ryan953** [comment]
Fixed by https://github.com/getsentry/sentry/pull/34198
