### ISSUE TITLE
Notifications Improvements

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3427]
- [ ] Issue subscribe/unsubscribe (GH-3428)
- [ ] Workflow settings shuffle (GH-3429)
- [ ] New Activity types (GH-3430)
- [ ] Comment mentions (GH-2634)

@getsentry/infrastructure @tkaemming

**Comment by dcramer** [comment]
#3613

**Comment by tkaemming** [comment]
All of this is done except for mentions, and there's a separate ticket for that one, so closing this.
