### ISSUE TITLE
New Notification Types

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3430]
* An issue unassigned
* An issue was unresolved/reopened (either manually, or automatically to a regression)
* An issue received a user report

**Comment by tkaemming** [comment]
This might make GH-3329 redundant?

**Comment by mattrobenolt** [comment]
Yeah, gonna close that in favor of this parent ticket.

**Comment by dcramer** [comment]
#3613 implements everything except user reports (I believe)

**Comment by tkaemming** [comment]
There's a pull request over here for user feedback: GH-3490

Everything else is done here.
