### ISSUE TITLE
The <CompactSelect> component doesn't open a flyout when rendering in the Chrome Mobile Emulator

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#34320]
Repro: 

1. Visit: https://storybook.sentry.dev/?path=/story/components-forms-fields--compact-select-field
   - Notice you can open the select field and see some options
3. In devtools enable mobile emulation
   - <img width="271" alt="Screen Shot 2022-05-06 at 10 17 14 PM" src="https://user-images.githubusercontent.com/187460/167151371-b4e0991a-d800-495c-b050-9d4f88ee33ec.png">
   - Notice the flyout no longer appears when you click the field.

**Comment by Danondso** [comment]
This is the warning emitting when it happens. Added non-passive event listener to a scroll-blocking 'wheel' event.

**Comment by Danondso** [comment]
For posterity, that warning had nothing to do with the problem, for whatever reason the CompactSelect overlay would get blurred immediately after opening.

**Comment by Danondso** [comment]
Details are listed in this [PR](https://github.com/getsentry/sentry/pull/34331). tl;dr the dirty fix is to set shouldCloseOnBlur prop to false which allows mobile screens to open dropdown correctly. Obv that doesn't work since folks can set the prop. 
The prop is passed to a useOverlay hook that comes from react-aria.

Below are my findings from looking more into that library. 
> I did some looking around on react and found https://github.com/adobe/react-spectrum/issues/816 that's > essentially the same behavior, a blur event fires right after opening. There's claims of a fix but there's no direct version > number pointing to it but there's a https://github.com/adobe/react-spectrum/pull/2175. I'm curious if a dependency upgrade > will fix it and I can go down that path if we're okay with bumping the react-aria version up to 3.15.

> For the sake of time I'm going to get a codesandbox link up that duplicates the problem and create an issue. In the > meantime I'll adjust the PR to ignore the prop on mobile. My plan is to check isMobile() since leveraging a media query check > gave me really mixed results, the only problem with that is we'll get inconsistent behavior between the mobile view in the > browser vs a native view since the userAgent doesn't change.

**Comment by vuluongj20** [comment]
Hello! Posted a fix for this problem in https://github.com/getsentry/sentry/pull/34820

**Comment by ArthurKnaus** [comment]
Closing as this seems to have been fixed.
