### ISSUE TITLE
Validate Release.version value

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3440]
This value comes in from two different places, either from the API endpoint to explicitly create a release, and on data ingest from the `release` attribute in the event payload.

Neither of these do any validation over the value and has caused many issues related to sourcemaps, especially with weird characters and url encoding, as well as characters like `\n` and other invisible characters causing another class of issues.

We should just have a pretty liberal whitelist of characters that we allow, and surface invalid data in the UI like we do with other issues. Or if it's an API call, just return an error.

For context, the only validation we do right now is on data ingest and we check the length: https://github.com/getsentry/sentry/blob/781271c317cd490bf235f5a82d090d4a649ca399/src/sentry/coreapi.py#L605-L613

Refs: GH-3203 SENTRY-1D4

@getsentry/infrastructure @benvinegar

**Comment by dcramer** [comment]
:+1:

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
