### ISSUE TITLE
Chapters should hightlight the most recent breadcrumb when hovering over the scrubber

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#34554]
In the Chapters component: only the most recent item _before_ the current timestamp should be hovered when you hover your mouse cursor over the timeline component. 

Currently the implementation highlights the _closest_ item to the current timestamp.

--- 
By using the `currentHoverTime` to control which component is highlighted with a background color, we can remove the `:hover {...}` CSS selector as well. That CSS selector is redundant and not needed.

This fixes an issue where two items can be hovered: the one under the cusor (via `:hover{}` css) and another earlier in the list which shares the same timestamp (like a click that's before a navigate)

![Image](https://user-images.githubusercontent.com/187460/168318391-77134e7b-5739-4ddd-a727-f2930b1b1881.png)

**Comment by SDaian** [comment]
think is not happening anymore @ryan953, I tried to reproduce, and is not happening, let me know.
