### ISSUE TITLE
服务器内部错误

### ISSUE THREAD

**Issue by chspan** [getsentry/sentry#34585]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Oops! Something went wrong
It looks like you've hit an issue in our server API. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

If you're daring, you may want to try the following:

Give it a few seconds and reload the page.
If all else fails, [create an issue](http://github.com/getsentry/sentry/issues) with more details.

### Expected Result

login打不开， Oops! Something went wrong

### Actual Result

![image](https://user-images.githubusercontent.com/19632399/168253803-a689238d-d5df-4a88-bac6-dd99305db45d.png)

**Comment by Kobby-Bawuah** [comment]
Hello @chspan, is your Org self-hosted?
