### ISSUE TITLE
Celery workers are never recovering from a redis connection loss

### ISSUE THREAD

**Issue by YaYaPao** [getsentry/sentry#34582]
I also encountered this problem，and here more details:
- Server version:  21.6.3
- Python Version: 3.6.14

For me it happens once in a 7-10 days. And my redis memory will grow quickly. Is there some ways to config and resolve it ?

Have a great day!

_Originally posted by @BYK in https://github.com/getsentry/sentry/issues/21133#issuecomment-852108648_

**Comment by BYK** [comment]
`21.6.3` is _very_ old so I first recommend upgrading it. I remember a redis-queue related optimization landing but I cannot remember the exact release.

**Comment by YaYaPao** [comment]
> `21.6.3` is _very_ old so I first recommend upgrading it. I remember a redis-queue related optimization landing but I cannot remember the exact release.

I will choose an inelegant workaround: a checking script to watch the event flow, and alert me if there's no events for a time range, and i merely restart the save-worker server. Because i add some customized feature like _app quality score_ at runtime. So upgrading sentry maybe a huge work for me.
