### ISSUE TITLE
Merge official plugins into sentry-plugins

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#3468]
This is a proposal to move all officially supported plugins into a monorepo. We can decide if its one giant python package or individual still, but this will greatly simplify things like testing and /large scale API changes.

**Comment by mattrobenolt** [comment]
Will this ultimately be what we tell people to install? Or would this just become an actual dependency of `sentry` itself and everyone gets it automatically?

I guess to clarify, if a user wants say, `sentry-slack` today, will the new instructions just be, `Install sentry-plugins`? I'm just making sure I understand the outcome of this.

**Comment by dcramer** [comment]
@mattrobenolt i think we'd tell them to install it, but tbqh I dont care either way. Mostly just the maintenance burden right now sucks
