### ISSUE TITLE
Share, forward or email an event

### ISSUE THREAD

**Issue by gamefundas** [getsentry/sentry#3475]
This is more of a question, as I am thinking this feature must be there, just that I am not looking hard enough.

At times I am looking an an error event and I want someone in my project to take a look at it. In such a case having the ability to forward or email the specific event with all the details might be very useful. I did come across the "share this event" link but that simply loads the event in a new page. I could share the link by copy pasting etc but wouldn't it be convenient if I can share it via email.

Please point me to this feature if it exists. Will be really helpful for my team.

**Comment by dcramer** [comment]
If we had mentions in comments would that solve your concerns?

**Comment by gamefundas** [comment]
These are situations where some of the team members, for instance leads who don't login to the tool could be passed the sentry error. Also if the tool provided the ability to key in a email address to forward the error to it will be easier to pass it to a distribution or individual email address who is not setup in the tool. 

I see this as a very handy feature.

**Comment by huannh** [comment]
I think it might also be helpful if we can have a set of plugin for share feature. e.g email/slack/... to share an error

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
