### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by tsabi** [getsentry/sentry#3476]
Hi,
i would like to do hungarian translation of sentry, please open the hungarian language in transifex - as i requested it there.
Thanks!
Csaba

**Comment by dcramer** [comment]
@tsabi did this already get approved? Otherwise I'm not seeing the language request

**Comment by tsabi** [comment]
Hungarian language did not exist before. So i requested to create the language - again:


Recent activity
The user Csaba Tóth requested the language Hungarian (Hungary) for the project sentry.
1 minutes ago

**Comment by dcramer** [comment]
I think I've gotten it approved, though I'm not sure if it added you to the team. If it didn't, send request and I'll make sure you get on there.

**Comment by Grvs7** [comment]
I am in

**Comment by tsabi** [comment]
Ok, hungarian language exists now, you just need to accept my join request :)

**Comment by tsabi** [comment]
I would like to get your attention kindly, that i requested to join to the hungarina team, accept my request please!

**Comment by mattrobenolt** [comment]
@tsabi I've accepted your request. :)
