### ISSUE TITLE
Experiment: Move Memory chart under the Timeline

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#34839]
As an experiment* we should try putting the Memory chart directly underneath the Timeline/Minimap.

It might be a little tall, so we could make it collapsable, ie: using an accordion component to wrap it.

We should take inspiration from chrome devtools, specifically devtools Performance tab. This tab has multiple expand/collapse sections like "Frames" "Main" "GPU" "Compositor". If an accordion or expando component works for Memory, then we may add scale and have more tabs/toggles in the future.

**Experiment**
The goal of this is to learn:
- How easy is it to move the memory chart into a new spot on the page -> A PR will demonstrate that
- What does the page look like with an accordion/expando under the timeline -> Take screen shots

**Comment by Jesse-Box** [comment]
@ryan953 will take on this
