### ISSUE TITLE
Experiment: Remove spacing from inside video URL and Controller components

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#34845]
As an experiment* we should remove inner spacing from the `<ReplayController>` and `<ReplayCurrentUrl>` components.

The spacing adds extra whitespace around the buttons and text. Instead we can have no whitespace between the buttons and the panel borders.

For example:
![Image](https://user-images.githubusercontent.com/187460/169456272-dba66009-c044-43fd-9cce-381d98a32278.png)

**Experiment**
The goal of this is to learn:
1. How does the component look without that inner padding? Do the text elements look too squished -> Screen shots will demonstrate this -> screen shots will show this
2. How much custom CSS does it take to strip the inner padding and make borders & border-radius settings line up -> a PR will demonstrate this
    - tweaks or additions to ButtonBar might help reduce the page-specific css we need to write

**Comment by Jesse-Box** [comment]
Gonna  sunset this ticket considering we're focused on layout changes rather than reducing paddings.
