### ISSUE TITLE
Celery workers are referencing a different version of Sentry (8.5.1 vs 8.6.0.dev0)

### ISSUE THREAD

**Issue by wzlee** [getsentry/sentry#3499]
![image](https://cloud.githubusercontent.com/assets/4182865/16114690/211fe776-33f5-11e6-9f6a-e92e099af701.png)
why this error show?

**Comment by mattrobenolt** [comment]
There are two errors here, and they both say pretty clearly the issue.

* Background workers haven't been running in a while.
* Background workers are a different version of Sentry compared to the web processes.

**Comment by mattrobenolt** [comment]
So to clarify, it sounds like workers _were_ running, then you upgraded, and you didn't start them back up under the new version.

**Comment by xoco70** [comment]
it happens the same thing to me... I understand, but as I am not a python dev, I don't really know how to fix it... 

I installed it once, then deleted it, now reinstalling it and get this exactly 2 messages...

Try to reboot server as many say, but didn't work. How should I do it?

**Comment by jakubczaplicki** [comment]
You may want to restart Sentry supervisor processes :
```
sudo supervisorctl restart sentry-web
sudo supervisorctl restart sentry-cron
sudo supervisorctl restart sentry-worker
```

**Comment by ssilaev** [comment]
Make sure that works the all three services (web, cron and worker). And just check syslog and this configure - https://docs.sentry.io/server/installation/python/#configure-supervisord
