### ISSUE TITLE
Error Sentryspawning

### ISSUE THREAD

**Issue by Sprungente** [getsentry/sentry#3524]
What's wrong? I use the last devbuild from Citizens 2 and Sentry

19.06 13:44:38 [Server] ERROR [Citizens] An exception occurred while the trait sentry was spawning for NPC ID 64.
19.06 13:44:38 [Server] WARN java.lang.NoClassDefFoundError: net/minecraft/server/v1_9_R2/Packet
19.06 13:44:38 [Server] WARN at net.aufdemrand.sentry.SentryTrait.ensureInst(SentryTrait.java:137)
19.06 13:44:38 [Server] WARN at net.aufdemrand.sentry.SentryTrait.onSpawn(SentryTrait.java:119)
19.06 13:44:38 [Server] WARN at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:244)
19.06 13:44:38 [Server] WARN at net.citizensnpcs.npc.skin.Skin.applyAndRespawn(Skin.java:127)
19.06 13:44:38 [Server] WARN at net.citizensnpcs.npc.skin.Skin.setData(Skin.java:224)
19.06 13:44:38 [Server] WARN at net.citizensnpcs.npc.skin.Skin.access$600(Skin.java:32)
19.06 13:44:38 [Server] WARN at net.citizensnpcs.npc.skin.Skin$1.onResult(Skin.java:168)
19.06 13:44:38 [Server] WARN at net.citizensnpcs.npc.profile.ProfileRequest$1.run(ProfileRequest.java:120)
19.06 13:44:38 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
19.06 13:44:38 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
19.06 13:44:38 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741)
19.06 13:44:38 [Server] WARN at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399)
19.06 13:44:38 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672)
19.06 13:44:38 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571)
19.06 13:44:38 [Server] WARN at java.lang.Thread.run(Unknown Source)
19.06 13:44:38 [Server] WARN Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_9_R2.Packet
19.06 13:44:38 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91)
19.06 13:44:38 [Server] WARN at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
19.06 13:44:38 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
19.06 13:44:38 [Server] WARN at java.lang.ClassLoader.loadClass(Unknown Source)
19.06 13:44:38 [Server] WARN ... 15 more

**Comment by mattrobenolt** [comment]
This seems entirely unrelated. This project is for https://getsentry.com. It looks like you're looking for http://wiki.citizensnpcs.co/Sentry.
