### ISSUE TITLE
New Auth Tokens cannot pass sudo check

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#3525]
The new auth token based API access never passes sudo:

```python
def is_considered_sudo(request):
    return request.is_sudo() or \
        isinstance(request.auth, ApiKey)
```

**Comment by mitsuhiko** [comment]
The error from the API:

```
{
  "error": "Account verification required.",
  "sudoRequired": true,
  "username": "foo@bar.com" 
}
```

**Comment by dcramer** [comment]
I suppose if we did it for ApiKey it's likely fine for AuthToken. Was there a specific report of someone wanting to do something that required sudo?

**Comment by Viatrak** [comment]
The API documentation lists support for deleting a sentry project (which we are trying to utilize).

When calling HTTP DELETE on API https://app.getsentry.com/api/0/projects/org-slug/project-slug/ with the 'Authorization: Bearer authtoken' header we receive the following response:

Response code:
{
"error": "Account verification required.",
"sudoRequired": true,
"username": "foo@bar.com"
}

**Comment by dcramer** [comment]
Could you describe the use-case for which you want to remove a project via the API? We're a bit paranoid about opening up endpoints like this as they expose easier attack vectors.

**Comment by Viatrak** [comment]
One of the configurations for our dev environments is to mirror production and develop directly on AWS (we have a series of tools in place to make this seamless). Recently, as part of the auto-provisioning of the AWS dev environment we started provisioning a GetSentry project to associate with the dev environment. When we auto unprovision the dev environment on AWS it would be nice to clean up the Sentry project associated with it at the same time.
