### ISSUE TITLE
Changes to digest schedule intervals are not immediately reflected in schedules.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#3534]
Any settings changes to the schedule don't take effect until a new notification is added to a digest, so schedule changes are not necessarily reflected immediately. So, if you had a digest that already had items in it and was scheduled to be sent in 5 minutes, and then changed the schedule to a 60 minute minimum delay, the digest would remain scheduled to be sent in 5 minutes unless another event is seen.

This isn't a significant issue since it only happens once, but it's something we should probably fix if there's an easy solution. (I haven't thought hard enough about it yet to know if there is an easy fix, though.)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by BYK** [comment]
Hi @tkaemming
