### ISSUE TITLE
[SaaS, Alerts] Not catching messages in alerts

### ISSUE THREAD

**Issue by saippuakauppias** [getsentry/sentry#35357]
### Environment

SaaS (https://sentry.io/)

### Version

SaaS (version not showed in footer)

### Steps to Reproduce

1. Create rule with settings:
- WHEN (Any): The issue is seen more than 1 times in one minute
- IF (Any): The event's "message" value contains "do_request"
- THEN: Send a notification to Member
![image](https://user-images.githubusercontent.com/945306/172071798-23706fa4-7ea5-4eff-b71b-87a9a1d5a2a6.png)

2. Send event from `sentry.php@v2.2.4`:
```php
\Sentry\withScope(function (\Sentry\State\Scope $scope) use ($url, $result) {
    $scope->setExtra('selector', $url);
    $scope->setExtra('result', $result);
    \Sentry\captureMessage('API.do_request');
});
```

3. It comes in `Isues`:
<img width="1589" alt="image" src="https://user-images.githubusercontent.com/945306/172071917-dbf13bab-1b60-4fbe-b854-1bfb207ec532.png">
<img width="1627" alt="image" src="https://user-images.githubusercontent.com/945306/172071997-1b2e2b70-3d5b-4486-9970-3a3937df823d.png">
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/945306/172072012-18d3c11b-5daf-4900-befb-19652cdd0703.png">

4. But the Alert is not sent and is not caught:
![image](https://user-images.githubusercontent.com/945306/172072185-c56bb9f7-d993-41bc-9357-9e1eef1aa66c.png)

### Expected Result

Alert is caught and a notification is sent

### Actual Result

Alert is not sent and is not caught

**Comment by scttcper** [comment]
Can you check your notification settings - https://sentry.io/settings/account/notifications/alerts/

Make sure "Issue Alerts" is enabled and setup to send to email. Also it sounds like its setup to alert when an event is seen more than 1 time in a minute, are you pushing two events? 

![image](https://user-images.githubusercontent.com/1400464/172480175-be4afba0-f2f9-4c41-a435-37ee88544c5c.png)

In the above screenshot I see that it has 2 events in 24 hours, but the events would need to be in the same minute in order to trigger.

**Comment by saippuakauppias** [comment]
Hi,

"Issue Alerts" enabled:
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/945306/172487358-ddf11dd0-7997-4ee6-9fdd-5b8c80781d9f.png">

I send one message at a time, of course :)

Does setting "The issue is seen more than 1 times in 1m" mean that you need strictly more than 1 event per minute? I thought it meant "more or equal".

Changed it to "0" now and I'll let you know if in the next few days the alert finally comes.

PS: When I had exactly errors (not messages), then this alert was triggered and I received emails. But I need to check a specific case that sends a message without stopping the script from working further with an error.

**Comment by scttcper** [comment]
You could remove the "The issue is seen more than 1 times in 1m" completely.

**Comment by saippuakauppias** [comment]
Thank you, you were right!

When I set this to 0 or remove the condition, the alerts start coming:

<img width="1593" alt="image" src="https://user-images.githubusercontent.com/945306/172960410-639f10cd-a008-4e51-82a6-e4b2bd3e373f.png">
