### ISSUE TITLE
i hoped the sentry can obtain the project's members in the redmine  when i created a issue in sentry by sentry-redmine 

### ISSUE THREAD

**Issue by zhangjianpinghik** [getsentry/sentry#3540]
when i created a issue in sentry by sentry-redmine ,the issue'assigned_to is NULL,so i hope that the sentry can obtain the project's members in the redmine, in this way，when i link a issue to redmine  in the sentry ,i can select a member belong to the project as the  issue'assigned_to.

**Comment by mattrobenolt** [comment]
Can you reopen this in https://github.com/getsentry/sentry-redmine please?
