### ISSUE TITLE
AssertionError: Group must belong to Project

### ISSUE THREAD

**Issue by deansheather** [getsentry/sentry#3541]
Whenever I reload the page in a Sentry instance that seems to be working, an event fires into the Internal project with this traceback...

```
AssertionError: Group must belong to Project
  File "celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "sentry/tasks/digests.py", line 65, in deliver_digest
    digest = build_digest(project, records)
  File "sentry/digests/notifications.py", line 200, in build_digest
    state = attach_state(**state)
  File "sentry/digests/notifications.py", line 75, in attach_state
    assert group.project_id == project.id, 'Group must belong to Project'
```

I've tried changing the group for the project I was viewing, but it didn't seem to work. I believe this happens every time a request is made that involves anything to do with issues.

**Comment by tkaemming** [comment]
This is a strange one. There's no valid way to get the database into this state, but here are a few possibilities that I can think of:

* data in the `sentry_groupedmessage` table was updated manually, circumventing the application (we don't provide a way to do move groups between projects via the application for a number of reasons, one of which you're discovering now),
* a Sentry instance was installed that uses a Redis database which already is used by another Sentry instance, or previously was used for another Sentry instance and was not flushed before the new instance was set up.

If you just want to delete the corrupted records from the database, you delete all keys prefixed with "d:" from your Redis cluster that is used for the digest backend, but if any of the above notes are true, your data will still probably be corrupted in some fashion.

**Comment by deansheather** [comment]
Flushing those keys from the Redis cluster seems to have fixed it, thanks!
