### ISSUE TITLE
Can not install from source code on docker ubuntu container

### ISSUE THREAD

**Issue by kingofhawks** [getsentry/sentry#3543]
I want to run sentry on docker's ubuntu container, when i run "python setup.py develop", i got the error:
<pre>
<code>
running develop
running egg_info
creating src/sentry.egg-info
error: could not create 'src/sentry.egg-info': Protocol error
</code>
</pre>
I cannot figure it out by Googling the error message. Could someone help me?

**Comment by kingofhawks** [comment]
I download source code to Windows 10 C:/Users/Workspace/sentry, and start the ubuntu container by mount the host directory:
<pre>
<code>
docker pull python:2.7.11
docker run -idt -v /c/Users/workspace:/opt/workspace --name sentry python:2.7.11
</code>
</pre>

**Comment by mattrobenolt** [comment]
I've never seen this before. Why not use our official [sentry](https://hub.docker.com/_/sentry) image?

**Comment by mattrobenolt** [comment]
Oh, I'm guessing this is most certainly related to Windows. I'm assuming mounting a volume from your Windows host machine into a docker container will cause problems since the file systems aren't compatible.

**Comment by mattrobenolt** [comment]
Also, to provide more assistance: this definitely isn't an issue with Sentry itself. It seems more related to either Docker itself or setuptools not working correctly in this environment.

**Comment by kingofhawks** [comment]
@mattrobenolt  Is it possible to setup development docker image by following this 
https://github.com/getsentry/sentry/blob/master/Dockerfile.dev?

**Comment by mattrobenolt** [comment]
Yeah, but I've never tested against Windows, so I'm not sure what issues will come from there. I've run this in Linux and OSX.

**Comment by kingofhawks** [comment]
@mattrobenolt  Thanks, i will give it a try:)

**Comment by kingofhawks** [comment]
@mattrobenolt  I tried to build development image from your Dockerfile.dev, but it failed. Then I  followed the instruction from your official docker image(https://hub.docker.com/_/sentry/), and successfully started the container from my Windows 10 host. But i wonder is it possible to pull latest code and do some customization based on your official docker image?

**Comment by mattrobenolt** [comment]
> I tried to build development image from your Dockerfile.dev, but it failed.

What was the failure?

> But i wonder is it possible to pull latest code and do some customization based on your official docker image?

No, it's completely different and won't work for development. It's entirely made for running in production.

**Comment by kingofhawks** [comment]
$ docker build --rm -t sentry:dev -f Dockerfile.dev .
Error checking context: 'can't stat '\\?\C:\Users\Simon\AppData\Local\Application Data''.

**Comment by mattrobenolt** [comment]
I already said, this likely doesn't work with Windows. If someone can figure out a solution, I'd happily take a pull request. These errors seem to be because you're mounting the Windows file system into a Linux container. I have no idea if/how that works.

**Comment by mattrobenolt** [comment]
To me, this seems like an issue with Docker itself. I'm not sure.

**Comment by kingofhawks** [comment]
@mattrobenolt  Thanks! I agree with you, maybe this is a docker issue. I will try to go with ubuntu virtual machine,our development environment is based on Windows.
