### ISSUE TITLE
Sentry Angular: 1 error triggering 3 separate issues (Chrome, Safari, Firefox)

### ISSUE THREAD

**Issue by thmclellan** [getsentry/sentry#35447]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which package are you using?

@sentry/angular

### SDK Version

6.19.2

### Framework Version

6.19.2

### Steps to Reproduce

I'm using sentry/capacitor (0.6.1) with the related version of sentry/angular (6.19.2). Everything is working including sourcemaps, but when triggering a test error (calling a non-existent javascript function), then Sentry creates 3 separate issues for each of Chrome, Safari, and Firefox. 

![3-issues-1-error](https://user-images.githubusercontent.com/9682900/171750872-d2b4b3fb-6a70-4cb4-a1b7-dcdd4591c8d8.png)

Here are the issues for troubleshooting: 

Safari: 
https://sentry.io/organizations/jetsign/issues/3321138205/?project=6438629&query=is%3Aunresolved&statsPeriod=14d
Chrome & Firefox:  
https://sentry.io/organizations/jetsign/issues/3321139313/events/latest/?project=6438629&query=is%3Aunresolved&statsPeriod=14d
Firefox only: 
https://sentry.io/organizations/jetsign/issues/3321143625/?project=6438629&query=is%3Aunresolved&statsPeriod=14d

It's strange that the Firefox issue triggered once on its own and another time alongside the Chrome issue. I'm using Angular's differential loading to support legacy es5 but these browsers are all the latest. 

The same problem is happening with a Capacitor webview mobile app build (Ionic/Angular) running on iOS and Android, where we get an issue for iPhone and Android, though it's the same build and sourcemaps: 

https://sentry.io/organizations/jetsign/issues/3321134513/?project=6438639&query=is%3Aunresolved&statsPeriod=14d
https://sentry.io/organizations/jetsign/issues/3321134046/?project=6438639&query=is%3Aunresolved&statsPeriod=14d

I'm using an Angular ErrorHandler that uses the same _defaultExtractor() function as sentry/angular.  Here is a simplified version: 
 

```typescript
import { ErrorHandler, Injectable } from "@angular/core";
import { environment } from "../environments/environment";
import * as SentryBrowser from "@sentry/browser";
import * as Sentry from "@sentry/capacitor";
import * as SentryAngular from "@sentry/angular";
import { runOutsideAngular } from "./sentry-zone";
import { version } from "@src/environments/version";
import { HttpErrorResponse } from "@angular/common/http";
 
const debug = require("debug")("appSentryErrorHandler");

@Injectable()
export class SentryErrorHandler implements ErrorHandler {
  constructor() {
    const release = version.versionCodeBuildNumber.toString();
    // load dsn, environment, etc
    try {
      Sentry.init(
        {
          release,
          dsn,
          dist: release,
          environment,
          debug: false,
          integrations: (integrations) => {
            integrations.push(
              new SentryBrowser.Integrations.TryCatch({
                XMLHttpRequest: false,
              })
            );
            // exclude the 'Breadcrumbs' integration if we're not running in production, otherwise the console will show everything originating from breadcrumbs.js
            return integrations.filter(
              (integration) => !(integration.name === "Breadcrumbs" && !environment.production)
            );
          },
        }, // Forward the init method from @sentry/angular
        SentryAngular.init
      );
      console.log("Sentry initialized:");
    } catch (sentryErr) {
      console.log("Sentry sentryErr:", sentryErr);
    }
  }

  protected _defaultExtractor(errorCandidate: unknown): unknown {
    let error = errorCandidate;

    // Try to unwrap zone.js error.
    // https://github.com/angular/angular/blob/master/packages/core/src/util/errors.ts
    if (error && (error as { ngOriginalError: Error }).ngOriginalError) {
      error = (error as { ngOriginalError: Error }).ngOriginalError;
    }

    // We can handle messages and Error objects directly.
    if (typeof error === "string" || error instanceof Error) {
      return error;
    }

    // If it's http module error, extract as much information from it as we can.
    if (error instanceof HttpErrorResponse) {
      // The `error` property of http exception can be either an `Error` object, which we can use directly...
      if (error.error instanceof Error) {
        return error.error;
      }

      // ... or an`ErrorEvent`, which can provide us with the message but no stack...
      if (error.error instanceof ErrorEvent && error.error.message) {
        return error.error.message;
      }

      // ...or the request body itself, which we can use as a message instead.
      if (typeof error.error === "string") {
        return `Server returned code ${error.status} with body "${error.error}"`;
      }

      // If we don't have any detailed information, fallback to the request message itself.
      return error.message;
    }

    // Nothing was extracted, fallback to default error message.
    return null;
  }

  handleError(error) {
    // If the error has been marked handled, then do nothing, otherwise send it to Sentry
    debug("handleError:", error);
    if (!(error && error.handled)) {
      const extractedError = this._defaultExtractor(error) || "Handled unknown error";

      // Capture handled exception and send it to Sentry.
      if (environment.production) {
        console.warn("Sentry capture error", error);
        // const eventId = Sentry.captureException(extractedError);
        // Capture handled exception and send it to Sentry.
        const eventId = runOutsideAngular(() => Sentry.captureException(extractedError));
      } else {
        console.warn("Sentry not in production, just throw error");
        throw error;
      }
    }
  }
}
```

The `sentry-zone` file is just a clone of sentry/angular `zone.js`: 

```typescript

// That's the `global.Zone` exposed when the `zone.js` package is used.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
declare const Zone: any;

// There're 2 types of Angular applications:
// 1) zone-full (by default)
// 2) zone-less
// The developer can avoid importing the `zone.js` package and tells Angular that
// he is responsible for running the change detection by himself. This is done by
// "nooping" the zone through `CompilerOptions` when bootstrapping the root module.
// eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
const isNgZoneEnabled = typeof Zone !== "undefined" && !!Zone.current;

/**
 * The function that does the same job as `NgZone.runOutsideAngular`.
 */
export function runOutsideAngular<T>(callback: () => T): T {
  // The `Zone.root.run` basically will run the `callback` in the most parent zone.
  // Any asynchronous API used inside the `callback` won't catch Angular's zone
  // since `Zone.current` will reference `Zone.root`.
  // The Angular's zone is forked from the `Zone.root`. In this case, `zone.js` won't
  // trigger change detection, and `ApplicationRef.tick()` will not be run.
  // Caretaker note: we're using `Zone.root` except `NgZone.runOutsideAngular` since this
  // will require injecting the `NgZone` facade. That will create a breaking change for
  // projects already using the `@sentry/angular`.
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
  return isNgZoneEnabled ? Zone.root.run(callback) : callback();
}


```
Package.json highlights: 
```json
{  
    "@angular/common": "12.2.16",
    "@angular/core": "12.2.16",
    "@angular/forms": "12.2.16",
    "@angular/platform-browser": "12.2.16",
    "@angular/platform-browser-dynamic": "12.2.16",
    "@angular/router": "12.2.16",
    "@ionic/angular": "5.9.3",
    "@sentry/angular": "6.19.2",
    "@sentry/capacitor": "0.6.1",
    "@sentry/cli": "2.1.0",
    "@sentry/node": "6.19.2",
    "zone.js": "0.11.4"
}
```

### Expected Result

For Sentry to automatically merge these issues together to avoid extra noise when resolving issues. 

### Actual Result

The same missing function error creates multiple issues for different browsers executing the same build and source maps.

Maybe I'm doing something wrong in my configuration? Appreciate any suggestions or help, let me know if there's any more information I can provide. Thanks

**Comment by Swatinem** [comment]
I’m afraid this is just the nature of how browsers report stack traces.

You can see that we use the stack trace for grouping infromation (you can expand the details on the very bottom of the event).

Something you could try is updating to our grouping breakdown preview: https://docs.sentry.io/product/data-management-settings/event-grouping/grouping-breakdown/

That should probably help in this case, as the top ~5 frames are at least the same across browsers.

**Comment by thmclellan** [comment]
Thanks @Swatinem for responding, I'll try the new grouping breakdown feature. It seems the situation may be worse than usual with Angular because there is a lot of stack trace wrapping by zone.js/dist/zone. This should probably get added as a troubleshooting tip to the sentry-angular docs.
