### ISSUE TITLE
Regression: lost ability to change celery log level

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3546]
This has gotten hardcoded to `WARN`, so now passing `-l info` or friends doesn't give us what we want anymore.

**Comment by JTCunning** [comment]
Two things happening here:
 1. We removed the hijacking of the root logger so any of the logging options passed in will be overridden by django's loggingDict instantiation.
 2. We set the loglevel to `WARN` so we wouldn't flood all of logging with task status.

What needs to happen:
 Essentially #3346, verifying that it extends to both celery applications.
