### ISSUE TITLE
Improvement: Active project should be visible on Replay Details

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#35548]

**Comment by benvinegar** [comment]
As of right now, we do not identify the active project when accessing Replay Details. We need to identify the active project so that users know what data they're looking at, as we do on other pages.

**Comment by ryan953** [comment]
A comment was made that if we show the Platform Icon for the active project that would save space, but also that it would always be Javascript because replays are a web browser thing.

**Comment by ryan953** [comment]
The new header design includes the current project. See #36110

Closing this because it's a duplicate
