### ISSUE TITLE
Installed plugins show up sporadically in sentry 8.5.1

### ISSUE THREAD

**Issue by tomlinford** [getsentry/sentry#3565]
Hello,

We're running self-hosted sentry (v8.5.1) and I've been trying to get the sentry-slack plugin installed. The slack integration only shows up maybe 20% of the time when refreshing the "all integrations" page -- `https://{netloc}/{team}/{project}/settings/plugins/`. When it shows up and I click on the configure button, it will usually 302 and redirect me to the main settings page for the project. The plugin appears to be installed correctly:

```
$ sentry plugins list
sentry-slack 0.5.0
$ python -c "from pkg_resources import iter_entry_points; print list(iter_entry_points('sentry.plugins'))"
[EntryPoint.parse('slack = sentry_slack.plugin:SlackPlugin')]
```

I have of course restarted the web server after installing `sentry-slack`. I also tried other plugins and encountered the same issue.

Any thoughts about what could be going on here?

**Comment by mattrobenolt** [comment]
Do you have more than one server running? If so, this would indicate that it's installed on one server, and not the others, etc.

There's no other reason that'd happen.

**Comment by tomlinford** [comment]
Oh heh, duh, thanks!
