### ISSUE TITLE
Sentry with Azure redis-cache

### ISSUE THREAD

**Issue by RankoR** [getsentry/sentry#3570]
I'm trying to use Sentry with Azure redis. Azure generates long password such as:
qdwdqwdWBDWBDwsomething2/d1hb+Wwwa=

I use the following broker URL:
`BROKER_URL = 'redis://:qdwdqwdWBDWBDwsomething2/d1hb+Wwwa=@some-sentry.redis.cache.windows.net:6379/0'`

But when I run sentry upgrade, I get the following error:

> sentry.exceptions.InvalidConfiguration: NOAUTH Authentication required.

So it seems to process such passwords incorrectly. And I can't change password to a simplier one in Azure.

**Comment by mattrobenolt** [comment]
Can you provide the full stacktrace please?

**Comment by RankoR** [comment]
@mattrobenolt 

> [ERROR] Unable to fetch internal project
> Traceback (most recent call last):
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/utils/raven.py", line 78, in send
>     project = Project.objects.get_from_cache(id=settings.SENTRY_PROJECT)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/db/models/manager.py", line 259, in get_from_cache
>     result = self.get(**kwargs)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/django/db/models/manager.py", line 151, in get
>     return self.get_queryset().get(*args, **kwargs)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 304, in get
>     num = len(clone)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 77, in __len__
>     self._fetch_all()
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 857, in _fetch_all
>     self._result_cache = list(self.iterator())
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/django/db/models/query.py", line 220, in iterator
>     for row in compiler.results_iter():
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 713, in results_iter
>     for rows in self.execute_sql(MULTI):
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
>     cursor.execute(sql, params)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/raven/contrib/django/client.py", line 112, in execute
>     return real_execute(self, sql, params)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
>     return self.cursor.execute(sql, params)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
>     return self.cursor.execute(sql, params)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 75, in inner
>     raise_the_exception(self.db, e)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 73, in inner
>     return func(self, *args, **kwargs)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 21, in inner
>     return func(self, *args, **kwargs)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 95, in inner
>     six.reraise(exc_info[0], exc_info[0](msg), exc_info[2])
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/decorators.py", line 88, in inner
>     return func(self, sql, *args, **kwargs)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/db/postgres/base.py", line 39, in execute
>     return self.cursor.execute(sql, params)
> ProgrammingError: relation "sentry_project" does not exist
> LINE 1: ...ct"."status", "sentry_project"."first_event" FROM "sentry_pr...
> 
> SQL: SELECT "sentry_project"."id", "sentry_project"."slug", "sentry_project"."name", "sentry_project"."forced_color", "sentry_project"."organization_id", "sentry_project"."team_id", "sentry_project"."public", "sentry_project"."date_added", "sentry_project"."status", "sentry_project"."first_event" FROM "sentry_project" WHERE "sentry_project"."id" = %s 
> Traceback (most recent call last):
>   File "/home/sentry/sentry/bin/sentry", line 11, in <module>
>     sys.exit(main())
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 152, in main
>     cli(prog_name=get_prog(), obj={}, max_content_width=100)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
>     return callback(*args, **kwargs)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/runner/decorators.py", line 25, in inner
>     configure()
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/runner/__init__.py", line 115, in configure
>     configure(ctx, py, yaml, skip_backend_validation)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/runner/settings.py", line 159, in configure
>     }, skip_backend_validation=skip_backend_validation)
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 198, in initialize_app
>     validate_backends()
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 221, in validate_backends
>     backend.validate()
>   File "/home/sentry/sentry/local/lib/python2.7/site-packages/sentry/buffer/redis.py", line 37, in validate
>     raise InvalidConfiguration(unicode(e))
> sentry.exceptions.InvalidConfiguration: NOAUTH Authentication required.

**Comment by mattrobenolt** [comment]
Yeah, this isn't related to the `BROKER_URL` setting. This is the `redis.clusters` configuration and you're not declaring the password needed there.
