### ISSUE TITLE
Breadcrumbs list should scroll to ensure that "selected" breadcrumb is viewable

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#35744]
If breadcrumbs list is long, we should scroll the list so that the "selected" breadcrumb is viewable (i.e. either have it scroll so that the selected breadcrumb is at the top or bottom of list).

**Comment by Danondso** [comment]
On the thisdot fork there's this [PR](https://github.com/thisdot/sentry/tree/feat/replays/35744/breadcrumb-scroll). The issue I was facing was the scrollIntoView() call I was making causes the breadcrumb list to scroll to the bottom. Which prompted a discussion around what makes the most sense, [this youtube video](https://www.youtube.com/watch?v=T2kBBqoSFDY) shows how YT manages chapter scrolling. But Jesse wanted to do some exploring there.
