### ISSUE TITLE
Suggested new rule action: auto assign to specific user

### ISSUE THREAD

**Issue by dmnd** [getsentry/sentry#3575]
Right now it seems like the only actions I can take after a rule triggers is to send a notification:

![image](https://cloud.githubusercontent.com/assets/4427/16282964/b9f4c208-387f-11e6-98eb-b75eb1541cdc.png)

I'd love to make a rule that will auto-assign that issue to a specific user. Relatedly, I'd _also_ like to be able to trigger a notification to _only the auto-assigned user_.

Here's the use case behind this suggestion: we sometimes ship new code that isn't perfect yet. We run the code, but intentionally throw away the results. Because the code isn't perfect, we expect it to sometimes raise exceptions, which we catch, then send to Sentry. The idea here is that we can run the code for a while, logging all exceptions, and fixing the causes. Once the feature is no longer generating exceptions, we can turn on the feature for real.

What we've found is that it's harmful to notify the entire team about this kind of exception. It makes the channel noisy, exacerbating problems discussed in #2673. 

Instead, only the developer who set it up should be notified, and hopefully assigned too.

**Comment by JTCunning** [comment]
Hey @dmnd, thanks for the suggestion! I'm going to assign this to @tkaemming since he is taking lead on a related set of changes going on currently. He's currently at Monitorama so hang tight and expect a reply sometime within the week.

**Comment by wearhere** [comment]
"expect a reply sometime within the week"… any thoughts? :)

**Comment by dcramer** [comment]
Likely won't happen with this specific concept. There's a lot of systems that need to be in place to do this correctly, and we generally refuse to do things that we have to rip out and refactor a few months later. I will say that "owners" are coming though.

**Comment by snarfed** [comment]
looks like this shipped a bit ago as the [suggested owners](https://docs.sentry.io/learn/releases/#suggested-owners) feature. cool!

if i understand that feature right, it only shows up on the issue detail page. it's not incorporated into notifications. i'd still love the original request here, ie the ability to only notify the suggested owner, either when the suggestion is above a confidence threshold, or at any confidence. thoughts?

**Comment by dcramer** [comment]
@snarfed thats only the first peek at it. Still a bunch more coming in the next few months. We're just working on some groundwork to get things in place for the larger feature.
