### ISSUE TITLE
Breadcrumbs stringify object

### ISSUE THREAD

**Issue by BlackDante** [getsentry/sentry#3576]
Hi,

Is there any chance to add object serialization to breadcrumbs feature? 
At this moment we only have `[object Object]` message, which is not too helpfull.

![BreadCrumbs](http://serwer1428975.home.pl/breadcrumbs.jpg)

Best, 
Kamil

**Comment by mitsuhiko** [comment]
I opened an issue against the client: https://github.com/getsentry/raven-js/issues/623
