### ISSUE TITLE
Network waterfall should not show all the sentry-replay beacon/post requests

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#35773]
The network waterfall is full of beacon and fetch requests from the sentry-replay sdk.

Example:
![Image](https://user-images.githubusercontent.com/187460/174185417-cbc08d93-5265-4dd1-b5ab-546487786fe6.png)

This is really meta, and not part of the page/product itself. I think we should hide it in the Network waterfall so that customers are not confused by all this traffic that they are not in control of.

A followup ticket would be to add a toggle so that people can optionally see this 'sentry metadata', but by default it's hidden and people only see requests that their own app is generating.

**Comment by billyvg** [comment]
This should probably be handled at the SDK level and not be collected at all

**Comment by ryan953** [comment]
> This should probably be handled at the SDK level and not be collected at all

That makes sense. I've put the task in the SDK repo: https://github.com/getsentry/sentry-replay/issues/95
