### ISSUE TITLE
Cannot link asana account

### ISSUE THREAD

**Issue by jakeonrails** [getsentry/sentry#35963]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Go to settings
Go to integrations
Go to asana
Go to Add project
Click my project
It says "You still need to associate an Asana identity with this account."
Click Associate
I see this error:

```
Oops! Something went wrong
It looks like you've hit an issue in our server API. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

If you're daring, you may want to try the following:

Give it a few seconds and reload the page.
If all else fails, [contact us](https://github.com/getsentry/sentry/issues/new/choose) with more details.
```

### Expected Result

Expected an OAuth flow with Asana, instead got an error screen

### Actual Result

<img width="825" alt="Screen Shot 2022-06-23 at 9 19 15 AM" src="https://user-images.githubusercontent.com/580084/175347037-496b0a88-67af-4bb3-ba9a-86c866544468.png">

**Comment by leeandher** [comment]
Hi there @jakeonrails, I wasn't able to reproduce this error when I attempted to use the Asana plugin. Would you mind sharing the Error ID for the error you experienced? It'll be in the console or network request history and would really help with debugging your exact issue.
