### ISSUE TITLE
Redmine plugin integration doesn't work

### ISSUE THREAD

**Issue by gek0** [getsentry/sentry#3596]
Using this plugin for redmine integration with self-hosted instance of sentry (8.4.1 version) https://github.com/facconi/sentry-redmine

Redmine version is 3.1.2.stable

After filling the form with redmine tracker data and clicking the "Create Redmine task" button, only thing I get is
` Oops! Something went wrong
It looks like you've hit an issue in our server API. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!
If you're daring, you may want to try the following:
Give it a few seconds and reload the page.
If all else fails, create an issue with more details.`

Log file only reports 500 http error on that route, nothing else. Got any solution for this?

**Comment by mattrobenolt** [comment]
You should install our version instead: https://github.com/getsentry/sentry-redmine and see if this solves your issues.

**Comment by gek0** [comment]
Yep, that version works. Thanks.
