### ISSUE TITLE
Get two-factor status through API

### ISSUE THREAD

**Issue by henrikhodne** [getsentry/sentry#3602]
Hi!

We have a tool that automatically checks everyone's two-factor authentication status and sends out a reminder if they don't have it enabled on some services, and I'd like to add Sentry to the list of services supported by that tool. In order to do that, the 2fa status for each member would have to be available through the API. Would this be something you'd consider adding to the API?

**Comment by mattrobenolt** [comment]
@henrikhodne thanks for the suggestion. 🍪

**Comment by henrikhodne** [comment]
Sweet, thank you! :heart:

How long does it usually take for something like this to be deployed?

**Comment by dcramer** [comment]
@henrikhodne should be live

**Comment by henrikhodne** [comment]
@dcramer It is indeed, I just forgot the trailing `/` on the API endpoint. Thank you for the quick turnaround! :sparkles: :heart: :heart: :sparkles:
