### ISSUE TITLE
Timeline should render custom breadcrumbs that the SDK captured

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#36034]
This might already be possible, but we'd need to test it. 

To test i'd get an example app, maybe something with react/redux, something where the SDK creates custom breadcrumb. Just verify that they are saved as part of the replay, and visible in the breadcrumbs!

Also: I don't think that custom breadcrumbs should be appearing in the Timeline. The Timeline doesn't have as much room to show data.

Expected outcomes: 
1. Someone needs to check that custom things appear in the breadcrumbs
2. Take screen shots of how they look currently
3. Recommendations (or a PR) for how to make them look better/unique, if needed.

**Comment by danecando** [comment]
I tested custom breadcrumbs by instrumenting a basic redux app with replay and the sentry redux integration. Redux action breadcrumbs are showing up in the breadcrumb list and not in the timeline. 

![Image](https://user-images.githubusercontent.com/3721977/176206721-9433f557-657b-4ebd-b095-8896de471c62.png)

![Image](https://user-images.githubusercontent.com/3721977/176206719-13eb3a6b-993d-4479-8bfb-2c699b5e554e.png)

One thing that I noticed which I'm attaching a quick clip to show is: Some of the Redux Action breadcrumbs in the list cannot be hovered over / clicked. It just skips over them to the next or previous breadcrumb in the list. Also it would be nice if we were able to show some metadata about the action like the name like how DOM event breadcrumbs show a trail of elements. 

https://user-images.githubusercontent.com/3721977/176208204-f5345dc5-25f6-468d-ab2a-01b71f35955c.mp4
