### ISSUE TITLE
Sentry iOS Papercuts

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#3608]
Email related:
- [ ] email always shows ocurred but that can be wildely in the past/future because it's a user device. Also it might have needed an app restart to get the event. Maybe we can do something clever here where if the date seems unlikely we use the received date and indicate this?

General:
- [x] The raw stackframe rendering is broken for cocoa (lots of question marks)
- [x] Unclear `device.family`
- [ ] Device data from simulator runs is very odd (shows lots of x86_64?).
- [ ] All of the method names are blue and look like links, but you can’t click them. Recolor?
- [x] Remove device name if not used (and some other keys)
- [x] Os label is confusing, should be shown as "Operating System"
- [x] tag for rooted should be yes/no instead of `True`/`False`.
- [ ] app version is not shown

**Comment by mitsuhiko** [comment]
The things marked as fixed are fixed on #3612.

**Comment by mitsuhiko** [comment]
The device data is bad in simulator because we get it bad from KSCrash. We should probably fix this with the new report format.

**Comment by mitsuhiko** [comment]
The new PR that tracks the changes is #3634.

**Comment by JanNash** [comment]
Technically, the Simulator IS x86_64, so I don't understand how this is odd?

**Comment by mitsuhiko** [comment]
@JanNash yeah, that's fine. But that information is also shown in places where it should not be. I don't have the details right now but i think it shows the architecture in three places instead of model name.

**Comment by JanNash** [comment]
Ah ok, thanks for clarification 👍

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
