### ISSUE TITLE
See per-project events dropped per day/week on stats page

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3611]
Right now the stats page only shows a summary involving the last 7 days. Users have commented that it would be helpful to see more granular data, especially when tweaking per-project rate limits.

User feedback:

> I changed per project rate limit of a organization from 100% to 50% and can't wait see the effect a week later since stats page only show us 1 week statistics.

**Comment by hiroshi** [comment]
It'll be great if stats and issues page have time window preferences like New Relic does
<a href="https://gyazo.com/17a8911d2fa21f27bb95efe475065cd3"><img src="https://i.gyazo.com/17a8911d2fa21f27bb95efe475065cd3.png" alt="https://gyazo.com/17a8911d2fa21f27bb95efe475065cd3" width="456"/></a>

**Comment by dcramer** [comment]
:+1: probably not that hard to throw something in and its come up a few times

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
