### ISSUE TITLE
Improvement: Condensed Replay Details Header

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#36110]
### Context
The current page header, used in our replay details view, relies on a lot of vertical space to provide the user context of how they got to this replay. The UX is sound, but the space used is excessive.

### Acceptance Criteria
- The user must be able to understand this specific replay was the one they clicked on from the index view.
- The user must be able to navigate back to the replay index page.
- The user must be able to see high-level meta of the replay, similar to the index page.
- The metadata signifiers used on both, the index and details need to be consistent.
- From the relay index, the user can directly go to issues tab to see which issue is featured in this replay.
- Relative timestamp abbreviation used for index and details is consistent with sentry issues

### Designs
[Figma Mock](https://www.figma.com/file/3irLdrxfSf6GxtKmMOM5dq/Exploration%3A-Details-v2?node-id=128%3A5828)
<img width="734" alt="Screen Shot 2022-07-12 at 10 13 46 AM" src="https://user-images.githubusercontent.com/187460/178552639-d85a5835-00e2-47fa-9802-19d5cc9dcf0c.png">

### Related Issues
https://github.com/getsentry/sentry/issues/35548

**Comment by ryan953** [comment]
Reopened because #36638 has some followups still:

1. call useProjects() hook so we can get the correct data for <ProjectBadge>
2. bring the new styles into the header on /v2/, which means editing https://github.com/getsentry/sentry/blob/master/static/app/views/replays/detail/page.tsx

**Comment by ryan953** [comment]
The new styles will be part of the v2 design when #36705 is merged
