### ISSUE TITLE
Navigating to sentry.io/organizations/:org/events/:event_id/ infinite loops

### ISSUE THREAD

**Issue by cdignam-segment** [getsentry/sentry#36201]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Find a project name and event_id associated with that project. E.g. `segment` and `b5ac6493004f4882a058980bbf690d68`
2. Navigate to `sentry.io/organizations/:org/events/:event_id/`
3. Open the JS console and observe an infinite loop of requests to https://sentry.io/organizations/:org/events/:event

<img width="644" alt="Screen Shot 2022-06-29 at 11 47 17 AM" src="https://user-images.githubusercontent.com/95240033/176479902-2375118c-80b1-429d-a966-d1ed4eb3cf13.png">
 

### Expected Result

Navigating to sentry.io/organizations/:org/events/:event_id/ redirects to the associated issue

### Actual Result

Browser shows a blank screen and continuously makes API requests

<img width="661" alt="Screen Shot 2022-06-29 at 11 48 18 AM" src="https://user-images.githubusercontent.com/95240033/176480135-7c30d3d8-8083-4576-bbf8-b98b90d544ad.png">

**Comment by souredoutlook** [comment]
@cdignam-segment did the URL pattern I provided earlier work for your needs?

Also worth noting, I was able to reproduce the loop and it has been escalated to the relevant team.

**Comment by snigdhas** [comment]
@cdignam-segment Also curious to know how you ended up at this page - were you routed there through something in the Sentry UI?

**Comment by cdignam-segment** [comment]
@souredoutlook Yeah, that URL pattern worked for me
