### ISSUE TITLE
External file link doesn't click through

### ISSUE THREAD

**Issue by cameronmcefee** [getsentry/sentry#3620]
### Expected

Click the external link icon, go to a file somewhere.

### Actual

Contents under the file path collapses

![slack-imgs com](https://cloud.githubusercontent.com/assets/72919/16507851/0c237eee-3ee2-11e6-839d-3b8941417644.png)

The anchor is there and has an href value, so I'm guessing the click event is prematurely being handled and not passed through to the link.

**Comment by ckj** [comment]
cc @getsentry/ui
