### ISSUE TITLE
Webhook not work

### ISSUE THREAD

**Issue by ckrgithub** [getsentry/sentry#36245]
### Environment

Saas (https://sentry.io/)

### Version

No response

### Steps to Reproduce

Internal Integration：
![image](https://user-images.githubusercontent.com/18225851/176665948-31b5194c-96f4-45ee-82e7-449c4af3342d.png)
![image](https://user-images.githubusercontent.com/18225851/176664313-35efd305-bcab-469d-9d80-3e2fb0471675.png)

WebHooks: 
![image](https://user-images.githubusercontent.com/18225851/176664512-067e7004-a9e5-4b40-b02d-8e11bdb72838.png)

Alert Rules:
![image](https://user-images.githubusercontent.com/18225851/176664750-5c452596-7243-401f-8ff5-c73717cd3a77.png)
![image](https://user-images.githubusercontent.com/18225851/176665259-45971eff-abb1-4d8f-8272-f5ff5b59cf37.png)

### Expected Result

The issue alerts can be triggered

### Actual Result

The issue alert cannot be triggered

**Comment by ckrgithub** [comment]
@getsentry-release I don't understand. Now I'm running into webhook not working

**Comment by ceorourke** [comment]
Hi @ckrgithub - it looks like you're using both the webhooks plugin and internal integrations, but have set the internal integration as your alert rule action, so you don't need the webhooks plugin (your 3rd picture). From your images it seems that the alert did trigger from a new issue, but I'm guessing you didn't receive the webhook in your service? 

We have an [example application](https://docs.sentry.io/product/integrations/integration-platform/#example-app) here you can take a look at, and [here](https://docs.sentry.io/product/integrations/integration-platform/webhooks/issue-alerts/) are the issue alert webhook docs. As long as you're able to receive webhooks from us this will work. You may want to do a simple test of using https://webhook.site/ as the destination to verify your internal integration and alert rule are set up properly, and then if that's working but your URL isn't, the problem would be your service.

**Comment by ckrgithub** [comment]
webhook url: https://open.feishu.cn/open-apis/bot/v2/hook/c2691562-26b5-4308-8d8a-bf69bd68eef2

**Comment by ceorourke** [comment]
Hi @ckrgithub how did the webhook.site test go? When the alert fired, did it show up there? You may need to ensure your service is reachable by us too, here are our [IP ranges](https://docs.sentry.io/product/security/ip-ranges/)?

**Comment by ckrgithub** [comment]
@ceorourke The webhook.site is working.My Sevice needs to be developed for third-party platforms. Thanks!
