### ISSUE TITLE
[Page turning function]now only page forward and backward are supported, it is not easy to use when there are a lot of pages

### ISSUE THREAD

**Issue by Chris0121** [getsentry/sentry#36274]
### Problem Statement

now only page forward and backward are supported, it is not easy to use when there are a lot of pages

Actual Reuslt : only upside down and upside down are supported.
Expected Result : support more easy to turn page liking Page number supported. When there are a lot of pages, we can turn to specfic page, first page and last page.

<img width="272" alt="image" src="https://user-images.githubusercontent.com/71202262/176341669-8c2b741d-d7fa-4fad-93b4-5ec60b4376a1.png">

**Comment by Chris0121** [comment]
> Could you please give more context about where these buttons are in the UI? Also, moving to the sentry repo and handing off to the frontend team to look at.

@ethanhs Thank you for response. We can find these button in issues page.
Thank you.
<img width="1698" alt="image" src="https://user-images.githubusercontent.com/71202262/176815450-59382c65-e0be-4172-bf79-37aa2f297215.png">

**Comment by ethanhs** [comment]
@Chris0121 Thank you! That makes it easier to see where you were talking about. I will leave this to the front end team to look at. Keep in mind we are coming back from a long weekend (it was a holiday in the United States yesterday).

**Comment by chadwhitacre** [comment]
Any thoughts on this @getsentry/app-frontend?

**Comment by malwilley** [comment]
It appears that we're using cursor-based pagination, which is better than offset-based pagination in a lot of ways, but it doesn't allow you to jump to an arbitrary place in the result set. So if we _did_ want to add page number, this seems like a blocker to doing so.

However, I'd like to hear a little more about the use case for jumping through so many pages. Perhaps there's a better way for us to improve the experience, like adding additional search queries or fields to sort on. Or maybe a "jump to start/end"?

**Comment by Chris0121** [comment]
> It appears that we're using cursor-based pagination, which is better than offset-based pagination in a lot of ways, but it doesn't allow you to jump to an arbitrary place in the result set. So if we _did_ want to add page number, this seems like a blocker to doing so. (Please correct me if I'm wrong here, I don't yet have a great grasp on the codebase)
> 
> However, I'd like to hear a little more about the use case for jumping through so many pages. Perhaps there's a better way for us to improve the experience, like adding additional search queries or fields to sort on. Or maybe a "jump to start/end"?

Thank you for response. It's ok as long as it's convenient to use. Now if there are more pages, it's too inconvenient to use.
Thank you for your help.

**Comment by Chris0121** [comment]
@malwilley 
Thank you for your help. And do you have any plan about how to easy turn page?
Thank you again.

**Comment by malwilley** [comment]
@Chris0121 this seems like it would be a large effort and isn't on our roadmap currently, so I don't think it will be worked on anytime soon.

**Comment by chadwhitacre** [comment]
Should we go ahead and close this out as wont-do, then?

**Comment by Chris0121** [comment]
@malwilley 
This is understandable. Thank you very much for your support.
