### ISSUE TITLE
(On Premise) Move Team to another Organization

### ISSUE THREAD

**Issue by temp** [getsentry/sentry#3628]
We host our own on-premise installation of sentry, but made some mistakes in the beginning...
We created several organiziations, and want to unify this to one organization now.
#1296 states that there is a possibility to transfer a team to another organizations - but how? Can't find anything related in the UI, or in the REST endpoints.
Any help on this would be appreciated!

**Comment by mattrobenolt** [comment]
You should be able to do this through the Django admin with your install. At `/admin/`. When you change the organization a team is a part of, it'll fix everything else to go with it.

At least it should. This is definitely not a normal operation, so we haven't exposed anything more user friendly.

**Comment by temp** [comment]
Thanks for this, matt! Didn't know about /admin/. Will try.
Just to make sure - I'll create a new organization, move all teams to it, and delete the other organizations afterwards. What about the Sentry organization and project? Guess it was auto-created... Should I move this there, too?

**Comment by temp** [comment]
@mattrobenolt ok, that worked. but i'm still unsure about the sentry organization. should i remove it, and move the sentry team/project to my new orga? or can i leave it like it is for single organization mode?

**Comment by Rylon** [comment]
@temp hi! You asked about removing the "Sentry" organisation last year, I just wondered what the result of this was as I have a similar situation :)

**Comment by temp** [comment]
@Rylon sorry for the late answer - I did watt Matt suggested, I changed the Organization of all Teams and Projects to the main Organization within the Django admin panel at /admin. Worked like a charm.

**Comment by Rylon** [comment]
No worries @temp I gave it a try also and it worked :) Thanks!
