### ISSUE TITLE
Sourcemap example

### ISSUE THREAD

**Issue by shaharmor** [getsentry/sentry#3636]
Hi,

I've tried basically any combination of file/name for both the .js and the .map file, but i couldn't get the sourcemap solution to work.

Is there any working example to follow?

My use case is as follow:
I have a app.js file per customer, where the difference between the customers is in the id query string parameter.

So /app.js?id=123 & /app.js?id=xyz are different files with different source-maps.
I need to be able to get the original source-code in Sentry for each of these files somehow, obviously without exposing the source-maps themselves.

**Comment by benvinegar** [comment]
Hi @shaharmor – I believe I've gotten in touch with you via our support email. I'm going to close this ticket for now.
