### ISSUE TITLE
"Trace details" description with link and some text after space renders incorrect HTML link element

### ISSUE THREAD

**Issue by wojtekweg** [getsentry/sentry#36419]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create an issue with href link and some text after whitespace in description for "Trace details" (for example `https:/url.com/images/logo-01.jpg GET`, see screenshot in "Actual result")
2. Open the issue in sentry.io, head to "Trace details" and click the link from description

### Expected Result

Link is properly parsed and can be opened, text that is present after a whitespace should not be part of link element (`<a target="_blank" rel="noreferrer noopener" href="https:/url.com/images/logo-01.jpg" class="external-icon css-c5vwnq ehytxfi0">`)

### Actual Result

Following HTML object is rendered: `<a target="_blank" rel="noreferrer noopener" href="https:/url.com/images/logo-01.jpg GET" class="external-icon css-c5vwnq ehytxfi0">` that leads to an invalid address, what leads to confusion

<img width="1316" alt="Screenshot 2022-07-07 at 14 55 29" src="https://user-images.githubusercontent.com/49337058/177778501-3d421cfb-1a04-4a37-ba68-df50f6b75a0d.png">

**Comment by taylangocmen** [comment]
To clarify is the expected result, the url in the description should be cleaned up or the anchor should only include the url without the `GET`?

**Comment by taylangocmen** [comment]
Thanks @wojtekweg, we'll add this to our backlog.

**Comment by Dhrumil-Sentry** [comment]
The new trace view has likely fixed this issue. Closing this but please feel free to reopen it
