### ISSUE TITLE
yarn dev-ui does not work

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#36420]
STR:
- Load https://dev.getsentry.net:7999
  - It redirects to https://dev.getsentry.net:7999/auth/login/
- Enter Account and Password values [1]

Expected results:
- Sign-in completes

Actual results:
- Error page [2]

There's nothing in [the docs](https://develop.sentry.dev/environment/#frontend-only) as to how to proceed.

[1]
<img width="267" alt="image" src="https://user-images.githubusercontent.com/44410/177798213-2b9ed857-d7de-4d82-b31f-347c4fe4e7a6.png">

[2]
<img width="407" alt="image" src="https://user-images.githubusercontent.com/44410/177798755-f6362dd8-4322-43df-b413-3c3c1576623e.png">

[2]
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/44410/177798452-b24a79aa-f542-43c6-b5c3-fa4368414921.png">

**Comment by armenzg** [comment]
I'm now constantly hitting this:
<img width="527" alt="image" src="https://user-images.githubusercontent.com/44410/178493800-79fe7dec-761c-4d78-9b79-49b1bc0f6962.png">

**Comment by priscilawebdev** [comment]
closing this issue according to the last comment
