### ISSUE TITLE
FORCE_SCRIPT_NAME fails on api url

### ISSUE THREAD

**Issue by abusquets** [getsentry/sentry#3644]
I'm running sentry 8.6.0 with this configs

FORCE_SCRIPT_NAME = '/apps/sentry'
system.url-prefix: /apps/sentry

But the api url doesn't have the prefix

raven.js:985Uncaught RavenConfigError: Invalid DSN: ://e189c354dcc04033926ec4de38af620e@/apps/sentry/1_parseDSN @ raven.js:985config @ raven.js:123(anonymous function) @ (index):57
jquery.js:8630GET http://localhost:8080/api/0/organizations/?member=1 404 (Not Found)
jquery.js:8630GET http://localhost:8080/api/0/internal/health/ 404 (Not Found)
jquery.js:8630GET http://localhost:8080/api/0/internal/options/?query=is:required 404 (Not Found)

**Comment by dcramer** [comment]
@abusquets unfortunately hosting Sentry at a subpath is very much a "pull requests accepted". We try not to break it, but its never been supported, and is likely even less supported today. You should look into running it at sentry.yourcompany.org
