### ISSUE TITLE
Improve Release support for iOS / Android

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#3652]
On iOS, Android, and some other platforms versions are not as unique. That is, in development you care about version + build, whereas in the app store you only care about version (though it still may be a specific build). We need to adapt releases to this situation.

A few notes:
- Releases today are unique on version. Unless we include the build in the version (which isn't great) there will need to be some changes there.
- We could add many builds per release, though that may have its own problems.
- We want the primary indicator of "release" to still be just the version, but have the ability to break down by version + build (e.g. release.build="1.0.0 adf383ka)

**Comment by dcramer** [comment]
Likely what we'll want to do is change 'release' to accept either a string or a hash, where the hash would map up to an interface (ephemeral?) which gets written as Release.

**Comment by BYK** [comment]
@bruno-garcia should this stay here or be transferred to an SDK repo?

**Comment by bruno-garcia** [comment]
The server today parses a format like:
`io.sentry@1.1.1+123123` so I believe it cover this and could be closed.

The releases page undertands this format (and the mobile SDKs send it already). This way improvements are done on the server now to group multiple releases by name (including multiple builds).

**Comment by BYK** [comment]
Closing based on what @bruno-garcia said.
