### ISSUE TITLE
Muted issues in dashboard

### ISSUE THREAD

**Issue by heytrav** [getsentry/sentry#3662]
Is there any way to prevent or filter _muted_ issues from appearing in the Dashboard? The volume of muted errors we see in the Dashboard makes it pretty hard to notice the dozen or so actual errors occurring in our system.  

![selection_005](https://cloud.githubusercontent.com/assets/64812/16641970/0497d058-445a-11e6-8ca5-d28b55200b75.png)

Each column represents ~1200 events.

**Comment by dcramer** [comment]
This has come up before and it might be worthwhile if we just started storing counters for "unresolved events" and switching up the chart. We definitely need to redo the dashboard, so probably can be done as part of that.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
