### ISSUE TITLE
Integration Docs Do Not Render Newlines

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#36667]
### Environment

SaaS (https://sentry.io/)

### Version

7a3cf289999d017ff602f903667c58df85be8f40

### Steps to Reproduce

As an example the github actions docs ([example from sentry org](https://sentry.io/settings/sentry/document-integrations/github-actions/)) show `\n\n` instead of rendering.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/7396/178942261-04a6be9d-2ef6-4905-b0e6-b7da8f377637.png">

The source of the doc is pulled from here somehow: https://github.com/getsentry/sentry-docs/blob/master/src/docs/product/releases/setup/release-automation/github-actions/index.mdx

### Expected Result

I expect a paragraph rather than `\n\n`

### Actual Result

I see escaped stuff.

**Comment by leeandher** [comment]
Good catch, this has been fixed :+1:
