### ISSUE TITLE
Message formatting incorrect in workflow emails

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3666]
Not sure if this is in other emails, but it's at least in the "resolved in next release" emails:

![image](https://cloud.githubusercontent.com/assets/375744/16650193/bfe77084-43f1-11e6-97d4-a901aa9b5d83.png)

@getsentry/ui @tkaemming

**Comment by tkaemming** [comment]
This is related to GH-3600 also.

**Comment by tkaemming** [comment]
This should be fixed for the HTML body, but still needs to be updated in the [email subject](https://github.com/getsentry/sentry/blob/cd37620897bac5e91d011f0126ce661ae7e41f7a/src/sentry/models/group.py#L411-L416) as well as the plain text body for [generic activity emails](https://github.com/getsentry/sentry/blob/cd37620897bac5e91d011f0126ce661ae7e41f7a/src/sentry/templates/sentry/emails/activity/generic.txt#L10), [note activity emails](https://github.com/getsentry/sentry/blob/cd37620897bac5e91d011f0126ce661ae7e41f7a/src/sentry/templates/sentry/emails/activity/note.txt#L12) and [digest emails](https://github.com/getsentry/sentry/blob/cd37620897bac5e91d011f0126ce661ae7e41f7a/src/sentry/templates/sentry/emails/digests/body.txt#L6) (and possibly other places.)

**Comment by tkaemming** [comment]
We fixed this a while ago.
