### ISSUE TITLE
Self-hosted setup does not populate client_id for Azure DevOps login

### ISSUE THREAD

**Issue by thekoding** [getsentry/sentry#36726]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.6.0

### Steps to Reproduce

1. Go to Settings -> Integrations
2. Select the "Add integration" button next to Azure DevOps
3. Login with my Office 365 account

### Expected Result

To be able to select the Azure DevOps environment

### Actual Result

From what I see the client_id value is not populated.

<img width="1249" alt="Screenshot 2022-07-15 at 16 25 39" src="https://user-images.githubusercontent.com/48824864/179232437-cd487dad-ac08-4d8c-921f-fa3f02e33c29.png">

**Comment by leeandher** [comment]
Hi @thekoding, thanks for the bug report! Could you confirm that your Self-hosted Sentry instance has `vsts.client-id` and `vsts.client-secret` properties configured as per [these docs](https://develop.sentry.dev/integrations/azuredevops/)?
