### ISSUE TITLE
Bug: Options dropdown failing to activate on first click in full screen

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#36735]
### Problem

When you click the options button to activate the dropdown when the player is in full screen mode it does not show up the first time. I've reproduced this bug on both Firefox and Chrome. It appears to be an issue where in full-screen mode a window onScroll event gets fired and the dropdown / select menus have logic that causes a close handler to be called on the dropdown when the page is scrolled. 

### Repro Steps:
_don't click or scroll or anything else_
1. Open a Replay (hard-refresh the page)
2. Click "Fullscreen"
3. Click the "Settings" icon
Notice that the settings flyout doesn't open
4. Click "Settings" again
Now it's working fine.

**Comment by jesus4497** [comment]
@ryan953 I think this was fixed collaterally, I cannot reproduce the bug anymore
