### ISSUE TITLE
Filter for "last seen"

### ISSUE THREAD

**Issue by SteveShaffer** [getsentry/sentry#3678]
It'd be nice to have a filter for "last seen."  I see the `age:` filter to filter for first seen, but it'd be nice to filter for just stuff that HAS been seen in the last hour (or 5 minutes for that matter if we're trying to correlate support tickets).  Maybe it exists and I just don't know the syntax, but I couldn't find it in the UI.

**Comment by tkaemming** [comment]
I think you're looking for `event.timestamp`, as documented here: https://docs.getsentry.com/hosted/learn/search/

It's not last seen exactly (it will match any issue that contains an event which satisfies the filter constraint — not just the last occurrence) but you should be able to use that field to build the type of queries you're asking about.
