### ISSUE TITLE
Angular2 integration doesn't work

### ISSUE THREAD

**Issue by kamikaze** [getsentry/sentry#3682]
When doing everything documentation says for Angular2 integration - I'm getting following error on project build:

`dist/tmp/app/main.ts(13,9): error TS2305: Module '"/home/user/projects/my-project/node_modules/raven-js/typescript/raven"' has no exported member 'Raven'.
[15:43:59] TypeScript: 1 semantic error`

**Comment by benvinegar** [comment]
@kamikaze – You may need to do `import Raven = require('raven-js')`. This depends on the package manager you're using + TypeScript compiler settings.

I've updated the docs about this [here](https://docs.getsentry.com/hosted/clients/javascript/integrations/angular2/).

In the future, tickets like this should be opened on getsentry/raven-js (the browser JavaScript SDK).
