### ISSUE TITLE
Issue with Org Slug Rename

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#3683]
Renaming an organization's slug to an existing one (thus causing a failure) seems to incorrectly trigger a successful action. That is, its redirecting you to the new slug even though the form is showing an error.

**Comment by dcramer** [comment]
Totally wrong ticket ref'd here.

**Comment by benvinegar** [comment]
This is solved today:

![image](https://user-images.githubusercontent.com/2153/46268785-7beb9800-c4f1-11e8-81ee-dedaacc3c35d.png)
