### ISSUE TITLE
Design Nit: Show a banner/message if the current browser is different from the browser that was used when the capture was taken

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#36882]

**Comment by Jesse-Box** [comment]
@ryan953 do we know specifically which browser the session was recorded on? or do we just know if the browser doesn't equal the browser you're using to watch the session?

**Comment by ryan953** [comment]
We do know which browser the session was recorded on. 

We'll have nice values like:
![Image](https://user-images.githubusercontent.com/187460/201777373-d8da6f94-039c-4699-a6fe-df2219af5c5f.png)


For the current browser (the one used to view the Details page) we'll have to parse the user agent manually.

**Comment by Jesse-Box** [comment]
I think with the recent work I'm doing for #42784 will resolve this ticket. The solution is different, however the information is more front and center.

**Comment by ryan953** [comment]
@Jesse-Box agree. Closing this
