### ISSUE TITLE
Investigate URL sourced transaction in Sentry

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#36906]
### Problem Statement

JS SDK team has been discussing transaction names from the JS sdk and related to some data on TXN and what [source](https://develop.sentry.dev/sdk/event-payloads/transaction/#transaction-annotations) they have, we want to try and analyze why Sentry produces so many raw URL TXNs, and if there is some learning we can have  to:
determine if there are better ways we can capture parameterized TXNs from our SDK determine if there are ways we can guide customers how to better set up their own website to produce parameterized TXN names

- we want to prevent the JS SDK from producing so many unique transaction names

### Solution Brainstorm

- as a start, we’re going to see why [Sentry.io](http://sentry.io/) produces so many unique transactions
- we’ll look at transactions with low TPM first, because they tend to be unique
- we’ll try to investigate why they aren’t parametrized correctly

**Comment by gggritso** [comment]
# Potential Issue 1: Mixed Routing

The React Router V3 instrumentation automatically starts a transaction on page load. It uses the `routes` object to resolve the current URL path to a route. If there is no matching route, it creates a transaction using the full current path as the name. Not all front-end routes are declared with React Router, though! If the application bundle that includes the React Router instrumentation is loaded on a page _not_ declared with React Router, it will automatically start a transaction, but fail to parametrize the transaction name.

An example of this is `/auth/login/x` transactions (e.g., `/auth/login/sentry`) of which there are many. That route is not declared using React Router, so there's a transaction for every single organization.

**Comment by gggritso** [comment]
## Potential Issue 2: React Router Redirects

Another common symptom is handling React Router's `<Redirect>`s. One example is `/organizations/:orgId/teams/performance/`, which redirects to `/settings/:orgId/teams/performance/members/`. Loading the page directly (as in, not by navigating the app, but by pasting into the URL bar) creates a non-parametrized transaction. e.g., navigating to `/organizations/sentry/teams/performance/` does the redirect, but creates the eponymous transaction. I wasn't able to figure out the exact cause, but another example is `/organizations/:orgId` which creates transactions like `/organizations/sentry` before doing the redirect.
