### ISSUE TITLE
Design Nit: The whole Details page scrolls when there's a page-wide `.messages-container` banner

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#36937]
The yellow banner takes up space, causing the rest of the page to scroll.

![Image](https://user-images.githubusercontent.com/187460/180285239-81cdf96c-610b-445f-9d4b-61b836a054a9.png)

I tried to fix this, the css we need isn't crazy. The issue is that the banner lives outside of our page content, so we need either:
a) global css selectors to touch it, or
b) somehow read the state so the details page knows that this banner exists
c) do fixed position for the page content so it doesn't matter if the banner appears or not. `FullViewport { position: fixed; top: 0; z-index: -1; }`

**Comment by danecando** [comment]
It's also the very small footer at the bottom. IMO I would just add a calc for that height so the footer is included in the 100vh cc @ryan953

**Comment by ryan953** [comment]
I've noticed that the footer only shows up in dev, and the renderer has some kind of bug because it will go away after the page redraws. 

I'm not too worried about the footer things right now.

**Comment by Jesse-Box** [comment]
Is this something design can solve, or is this more frontend challenge that needs to be overcome @ryan953 ?

**Comment by ryan953** [comment]
Not a huge deal. it's just in dev and we've survived with it for long enough already.
