### ISSUE TITLE
Proposal: dedicated artifact upload endpoint for JavaScript assets

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3700]
Artifacts are general purpose and can be used for non-JavaScript stuff like debug symbols (iOS). But because they're generic, we can't do good validation on JavaScript/source map-specific stuff like:
- verifying that  source maps are built correctly
- verify that sources are included in the sourceMap, or uploaded separately
- the minified/transpiled file correctly points to the source map file

Instead we have to do this at event processing time, which means not knowing if your source maps work until you're already knee-deep in errors.
## Proposal

A dedicated artifact upload API endpoint for JavaScript assets, that accepts:
1. a minified/transpiled file (e.g. app.min.js)
2. a source map file (e.g. app.min.map)
3. (optional) additional sources (if not included in the source map via `sourcesContent`)

And performs the validations outlined above, which are possible because there is a defined relationship between the files as part of the API parameters.

Spec below:

---
### Upload JavaScript Assets

```
POST /api/0/projects/{organization_slug}/{project_slug}/releases/{version}/js-assets/
```

Upload JavaScript assets for the given release.

Unlike other API requests, files must be uploaded using the traditional multipart/form-data content-type.
- **Path Parameters**
  - **organization_slug** (string) – the slug of the organization the release belongs to.
  - **project_slug** (string) – the slug of the project to change the release of.
  - **version** (string) – the version identifier of the release.
- **Parameters**
  - **jsUrl** (string) - url of the minified/transpiled file, e.g. "https://example.com/js/app.min.js"
  - **jsFile** (string) - multipart encoded file
  - **sourceMapFile** (string) - multipart encoded file
  - _how to specify additional sources?_
- **Authentication**
  - required
- **Method**
  - POST
- **Path**
  - /api/0/projects/{organization_slug}/{project_slug}/releases/{version}/js-assets/

Note that we don't need `sourceMapUrl` as a param, because we can just derive it from what's in `jsFile`.

cc @dcramer @mitsuhiko @mattrobenolt

**Comment by cudasteve** [comment]
Would the jsFile be optional?  Why would it need to be uploaded if you're already passing the URL for it?

**Comment by mitsuhiko** [comment]
Just some quick notes about this: I really want to do this and then have the upload endpoint associate a header with the files so we know after the fact as well if something is a sourcemap or a source file. This will come in useful if we want to add reprocessing support for JavaScript.

The sentry-cli tool does a lot of hackery already to detect different file types and could supply that information already if we want.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
