### ISSUE TITLE
Console panel should have a sticky header, so the title of the table columns do no scroll away

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#37017]
The network table has a sticky header, so when you scroll the table content the titles are still visible. 
Example:
![Image](https://user-images.githubusercontent.com/187460/181080526-d5ed909f-b818-42bc-b5df-c89d7e2862f8.png)

We should do the same for the Console table

**Comment by Jesse-Box** [comment]
I would argue that since the console log is more of a list than a table, this isn't needed. Fixed headers are great for tables because sometimes it's hard to remember what each column represents and also each column header could contain sorting functionality.

**Comment by ryan953** [comment]
@Jesse-Box that's fair. There's no table headings so what's meant to be sticky? nothing there!

We also have #36033 where we're going to make the filter stuff sticky. That's probably what I should've asked for here. I'll close this and we'll get it when the PR (https://github.com/getsentry/sentry/pull/37902) lands
