### ISSUE TITLE
How does sentry server refuse the event

### ISSUE THREAD

**Issue by jinzhao1994** [getsentry/sentry#3709]
I build a sentry server. It is run in docker. 

When I run the python code below to send 15 exceptions, sentry only receive 3 events(most of time). I printed the return value. Capture method after the third time will get None. If I add "sleep(1)" before the foo return, it will run well. I think this is a feature in sentry, to avoid too many request, but I don't know where is the document about this, and how to close it.

```python
def foo(a, b):
    try:
        return a / b
    except Exception as e:
        print a, b
        print client.captureException()


def main():
    for i in range(15):
        foo(i, 0)
```

The out is like this.

```
0 0
6c549ea6ff244ac0a1e7271b7ce94d52
1 0
3626e62963634c9897e3df2981a28a15
2 0
037d82f7f9784188b218f47fbd6517f2
3 0
None
4 0
None
5 0
None
6 0
None
7 0
None
8 0
None
9 0
None
10 0
None
11 0
None
12 0
None
13 0
None
14 0
None
Sentry is attempting to send 3 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
```

But it seems that this will not happen when I send message by logging.

```python
def bar(x):
    logging.error('wrong_id test %d', x)


def main2():
    for i in range(15):
        bar(i)
```

All the 15 event will send to sentry. Why?

**Comment by jinzhao1994** [comment]
I send 1e5 logging to sentry, it cost about 200 seconds, and sentry receive about 6100 events.

**Comment by dcramer** [comment]
You're probably being rate limited by the server. If Sentry responds with a 429 the Python client backs off until its told it can send data again.

**Comment by jinzhao1994** [comment]
Do you mean the rate limited in project? I have configured it to 100%. Rate limited means the max proportion between projects, doesn't it?

**Comment by dcramer** [comment]
@jinzhao1994 the project rate limits aren't the only guaranteed. If this is getsentry.com the subscription is rate limited. If it's on-premise it varies depending on how the install is configured. Either way, the status code + X-Sentry-Error header will describe whats going on.

**Comment by jinzhao1994** [comment]
It seems that the sentry web only received 3 exception. All of these three exception get a response 2xx. My raven client may drop the other exceptions. Thank you for your help.
