### ISSUE TITLE
Bug about language

### ISSUE THREAD

**Issue by jinzhao1994** [getsentry/sentry#3710]
I have set `SENTRY_DEFAULT_TIME_ZONE = 'Asia/Shanghai'` in sentry.conf.py. New account will set timezone as Asia/Shanghai as default. It runs well.

But when I go to the homepage, the page is written by English. If I click the 'Members', it will jump a Chinese page. If I go back to homepage again, it will jump to English again.

After I go to the account setting, click 'save' in appearance(although I change nothing), it comes right. All the pages become Chinese now.

**Comment by Barbery** [comment]
same question.

**Comment by BYK** [comment]
The timezone setting is different than the language setting so what you see is normal. Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
