### ISSUE TITLE
Feature Request: Better details on Django models in scope

### ISSUE THREAD

**Issue by cmpis** [getsentry/sentry#3712]
When we get an exception in a Django project often times we get the `repr()` version of the class.

Sometimes the data we need to see is what that current django model had so we can track back what happened.

It'd be nice if there were a way to provide a `__method__()` or property that sentry looked at for custom classes that would reveal that extra information we want.

**Comment by dcramer** [comment]
@cmpis we should be showing repr() of classes with the Python SDK unless its a specific type that we handle, which a Model is not.

You can provide ``__sentry__`` to override the repr which is shown.
