### ISSUE TITLE
Network table should *only* show resources & navigation types. Not anything to do with 'paint'

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#37122]
And *maybe* navigation? paint related items should not be shown.

![Image](https://user-images.githubusercontent.com/79684/181288969-80199faf-c520-45b1-b99a-52dcccc165d2.png)

**Comment by ryan953** [comment]
We should make sure those paint events are showing up somewhere though, like console? otherwise they could be lost.

I don't think they should be lost because they're part of that minimal 'what the browser shows' use-case imo.

**Comment by ryan953** [comment]
These are still visible in the breadcrumbs, and https://github.com/getsentry/sentry/issues/37604 will make sure that the value of the LCP (how long it took) is visible in breadcrumbs too. So nothing is lost.
