### ISSUE TITLE
Update sample Javascript events

### ISSUE THREAD

**Issue by ehfeng** [getsentry/sentry#3716]
- [ ] Tag with browser, device
- [x] Fix "2 errors encountered while processing this event"
- [ ] Add breadcrumbs

![image](https://cloud.githubusercontent.com/assets/279398/16821360/b49477fe-490a-11e6-9e22-2da904f52980.png)

File at `src/sentry/data/samples/javascript.json`

**Comment by benvinegar** [comment]
The sample JavaScript event today has breadcrumbs and device information:

![image](https://user-images.githubusercontent.com/2153/46268774-5a8aac00-c4f1-11e8-9f7e-62ffa51d9110.png)
