### ISSUE TITLE
DELETE release using an Auth Token errors

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3722]
It appears that we have an implicit assumption that this endpoint requires a browser session since we're erroring on a CSRF check.

See: SENTRY-HP

**Comment by mitsuhiko** [comment]
Some notes: we go down that path because an origin is set.

**Comment by dcramer** [comment]
Why would an Origin be set? FWIW auth tokens should not be used in browsers as that's a security concern today (since theres no concept of bound keys) nor are there allowed origins for tokens.

**Comment by mattrobenolt** [comment]
The user was using a browser extension which helps making API calls, and it sends along an Origin header with the API request.
