### ISSUE TITLE
Replay player needs a dark-mode specific scrubber nub

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#37241]
the current nub looks great in light mode, but it's too big and white for dark mode:

![Image](https://user-images.githubusercontent.com/187460/181688597-60b620eb-4283-4c00-a7b9-ba9095bb91e2.png)

![Image](https://user-images.githubusercontent.com/187460/181688533-bca5ff25-a072-4654-9951-5f0545b688d1.png)

What i'd suggest to try first is:
- no border
- make the inner part white
2nd try:
- thinner border
- smaller radius

**Comment by Jesse-Box** [comment]
We could take this one step further and iterating on the scrubber itself, to be shown to the user in a more obvious way. 


### Screenshots
#### Layout = Top 
![Image](https://user-images.githubusercontent.com/6508377/200552122-5916b2b2-f94c-41af-964a-e3d0acf4745f.png)
#### Layout = Player Left
![Image](https://user-images.githubusercontent.com/6508377/200552123-35409eac-e664-4de4-a5ec-3ebcad88fe25.png)

### Figma Designs
https://www.figma.com/file/OPFnT04z0uy8BEUms9OU4f/Specs%3A-Details-v3?node-id=634%3A20338
