### ISSUE TITLE
Discuss: Replace "User Blur/Focus" breadcrumbs

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#37354]
These breadcrumbs can be a bit noisy and might not be the best to include in the breadcrumbs list + timeline.

What if instead, we represented them in a different way as to remove some noisy from the above UI components. e.g. we can have a highlighted region in the timeline marked as "inactivity" and/or an overlay over the recording saying that the user is "inactive".

## Potential Solution via @Jesse-Box 
[Figma](https://www.figma.com/file/OPFnT04z0uy8BEUms9OU4f/Specs%3A-Details-v3?node-id=33%3A2991)
- We visually highlight periods of inactivity (User Blur till User Focus)
- We remove these from the breadcrumb list
- We don't use them to measure "Interest"

![Solution Mock](https://user-images.githubusercontent.com/6508377/184899298-8dcdf48b-cdf2-41a9-970e-71c25a6d7270.png)

**Comment by danecando** [comment]
I agree with this not sure what it would look like though. Currently theres a ticket for changing the icon color to split them up: https://github.com/getsentry/sentry/issues/37603 But I think this would make it a lot more clear to the user (an overlay or something) as they might not understand what the event means

**Comment by Jesse-Box** [comment]
@billyvg you created ticket #33727 a few months ago which fleshed out with problem and solution statement.

Hoping we can use that as the point of truth.

**Comment by billyvg** [comment]
As mentioned in Slack, #33727 is a bit different as it refers to visually compressing the timeline due to inactivity (which can result from user afking without a blur/focus). Let's use this ticket to address the noise that comes from the user focus/blur breadcrumbs specifically.

**Comment by ryan953** [comment]
The result is that we're going to remove focus/blur from the ui for now, but keep the data

https://github.com/getsentry/sentry/issues/38593
https://github.com/getsentry/sentry/issues/38591
