### ISSUE TITLE
I'm using sentry@21.6.3, I can't install python 3.6.13 in my m1 pro monterey mac

### ISSUE THREAD

**Issue by shezhangzhang** [getsentry/sentry#37405]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

21.6.3

### Steps to Reproduce

make setup-pyenv:

<img width="760" alt="image" src="https://user-images.githubusercontent.com/26793777/182539919-11433c0b-33c4-4506-a18a-a0425e482a3e.png">

latest mac, latest macos

### Expected Result

RIGHT

### Actual Result

WRONG

**Comment by shezhangzhang** [comment]
What can I do...
I can't upgrade the whole things, I just upgrade the version of python to 3.8.13, It says I'm on my own. I got a lot of other errors.

**Comment by shezhangzhang** [comment]
Finally, I installed 3.8.13, It support m1 monterey. 
But, when `make bootstrap`, I got some error because some pkg version in requirements-base.txt were wrong. e.g. psycopg2-binary version:
<img width="517" alt="image" src="https://user-images.githubusercontent.com/26793777/182569577-558a5780-03c9-4c4d-8303-f85432c74d5c.png">

the requirements-base.txt in my sentry@21.6.3 (the python version is 3.6.13, but I can not use it on my m1 pro mac dev env) is:
```txt
beautifulsoup4==4.7.1
boto3==1.10.49
botocore==1.13.50
celery==4.4.7
click==7.1.2
confluent-kafka==1.5.0; python_version <= '3.8'
confluent-kafka==1.6.0; python_version == '3.9'
croniter==0.3.37
dataclasses==0.8; python_version <= '3.6'
datadog==0.29.3
django-crispy-forms==1.7.2
django-picklefield==1.0.0
Django==1.11.29
djangorestframework==3.11.2
email-reply-parser==0.5.12
google-api-core==1.25.1
google-auth==1.24.0
google-cloud-bigtable==1.6.1
google-cloud-core==1.5.0
googleapis-common-protos==1.52.0
google-cloud-pubsub==2.2.0
google-cloud-storage==1.35.0
jsonschema==3.2.0
lxml==4.6.3
maxminddb==2.0.3
mistune==0.8.4
mmh3==3.0.0
parsimonious==0.8.0
petname==2.6
phonenumberslite==8.12.0
Pillow==8.2.0
progressbar2==3.32.0
# If we bump it to 2.8.4 or greater then Python 3.6 & 3.8 would use the same version
psycopg2-binary==2.7.7; python_version == '3.6'
psycopg2-binary==2.8.6; python_version > '3.6'
PyJWT==2.1.0
python-dateutil==2.8.1
python-memcached==1.59
python-u2flib-server==5.0.0
python3-saml==1.10.1
PyYAML==5.4
rb==1.9.0
redis-py-cluster==2.1.0
redis==3.4.1
requests-oauthlib==1.2.0
requests==2.25.1
# [start] jsonschema format validators
rfc3339-validator==0.1.2
rfc3986-validator==0.1.1
# [end] jsonschema format validators
sentry-relay==0.8.7
sentry-sdk>=1.0.0,<1.2.0
snuba-sdk==0.0.26
simplejson==3.17.2
statsd==3.3
structlog==21.1.0
symbolic==8.1.0
toronado==0.1.0
ua-parser==0.10.0
unidiff==0.6.0
urllib3==1.24.2
uWSGI==2.0.19.1
zstandard==0.14.1

msgpack==1.0.0
# for encrypting stored user credentials
cryptography==3.3.2
# celery
billiard==3.6.3
kombu==4.6.11

# Note, grpcio>1.30.0 requires setting GRPC_POLL_STRATEGY=epoll1
# See https://github.com/grpc/grpc/issues/23796 and
# https://github.com/grpc/grpc/blob/v1.35.x/doc/core/grpc-polling-engines.md#polling-engine-implementations-in-grpc
grpcio==1.35.0

# not directly used, but provides a speedup for redis
hiredis==0.3.1

# not directly used, but pinned for at least semaphore/symbolic
cffi==1.14.5

# not directly used, but pinned for toronado because it doesn't pin these
cssutils==1.0.2
cssselect==1.0.3

# sentry-plugins specific dependencies
phabricator==0.7.0

# test dependencies, but unable to move to requirements-test until
# sentry.utils.pytest and sentry.testutils are moved to tests/
selenium==3.141.0
sqlparse==0.2.4
# We're still using mock in Python 3.6 because it contains a fix to Python issue37972.
# We should be able to fully swap it out for stdlib once we're on 3.8.
mock==4.0.3

oss2==2.15.0

```

Notice #26488, Which versions in the above file should I change ? too messy...
Please😭 @armenzg

**Comment by shezhangzhang** [comment]
Recap: How can I migrate this #26488 m1 support to sentry version 21.6.3 ?

**Comment by shezhangzhang** [comment]
I change sentry-relay to 
```txt
sentry-relay>=0.8.7
```
it installed 0.8.13
ERROR: 
import _cffi_backend
ImportError: dlopen(/Users/xxx/huya/sentry/sentry-em/.venv/lib/python3.8/site-packages/_cffi_backend.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_ffi_prep_closure'
make: *** [bootstrap] Error 1

**Comment by armenzg** [comment]
Hi @shezhangzhang 
It's basically a complete uphill battle.
I have it somewhere on my notes that the first Python version that worked on M1s was Python 3.8.10.

I recommend the following:

- Try a version of Sentry to 21.11.x or greater
- Use a Linux VM on your M1 to run self-hosted on your M1
- Maybe a Docker image _may_ work on your M1 but I don't know if it will work

Other than that there's not much help I can provide.

**Comment by shezhangzhang** [comment]
@armenzg Thanks for your reply😆
