### ISSUE TITLE
Consider fetching artifact files w/o query string

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3744]
Right now if you have a query string as part of your source/sourcemap URL lookup, we need you to name artifacts with a matching query string. This means that if you are doing app.js?user=123, you would need to upload app.js for every conceivable user ID that might use your application.

We currently have a support issue open with such a user, who is asking if it could be possible to drop the query string when looking up source files (e.g. `app.js?user=123` would match on an artifact named `app.js`).

My current feeling is that, were we to do this, we should have another unique identifier that users must specify – similar to how we introduced the `~` prefix for omitting hostname/protocol.

For example, specifying a single question mark `app.js?` could match on all potential query string values.

Open to discussion.

**Comment by shaharmor** [comment]
This should first take into consideration an artifact matching the query string, and only if that fails check the "catch-all" one

**Comment by yongzhi-chen** [comment]
hi is there any update?

**Comment by mattrobenolt** [comment]
This should be resolved with GH-5860
