### ISSUE TITLE
Does sentry support redis cluster for redis 3.0+?

### ISSUE THREAD

**Issue by jinzhao1994** [getsentry/sentry#3745]
There are a config about redis cluster in `sentry.conf.py`. When I tried it with a redis cluster, It failed with the prompt like `MOVED 9842 10.4.36.226:8865`. The version of redis is 3.2, with 3 master nodes and 3 slave nodes, use slot to control routing.

I tried reading the source code about sentry. It seems that we use `rb` to work with redis cluster. In fact, the cluster is independent redis node. There is no network connections between the node of a cluster. Sentry will choose the right node to store the key/value.

Am I right about it? If I am right, how can I scale out with redis?

**Comment by mitsuhiko** [comment]
We do not support redis cluster, we use our own clustering based on `rb`.

> how can I scale out with redis?

You configure more redis hosts in the various RB configs. Though I have to admit I'm not sure how well all of this is documented.

**Comment by jinzhao1994** [comment]
That's what I want to know. I'm looking forward to the support about redis cluster. Thank you for you assistance.  :-)

**Comment by mitsuhiko** [comment]
I don't think we will add support for redis cluster. We're not quite convinced of it's promises and what we have currently works well :)

**Comment by jinzhao1994** [comment]
I think `rb` is a simple but useful library. But I still have some question. If I start sentry with 3 redis nodes, and I want to scale out, what should I do? From the routing algorithm of `rb`, it seems that I can only extend to 6 or 9 nodes, but not 4. There is a more important thing, how can I keep the data when I do this? Or can I just drop some data because sentry only use redis temporal?

**Comment by xjinza** [comment]
I have the same problem,set the config.yml 
```
redis.clusters:
  default:  # cluster name
    hosts:  # connection options, passed to `rb.Cluster`
      0:
        host: 172.31.1.247
        port: 6379
      1:
        host: 172.31.1.254
        port: 6379
```
But have the ResponseError, moved 11916 172.31.0.252:6379.
![_15468284263731](https://user-images.githubusercontent.com/3285701/50762933-5b2d9e00-12a9-11e9-9638-ed9441ce0ab4.png)
How to config the redis.clusters?

**Comment by jaketlarson** [comment]
Hi, I also have similar questions..
1) Do we still not support regular Redis clustering?
2) If we're only supporting rb cluster, does that mean we don't have a great way of supporting the HA-like setup we could get from Redis cluster / Sentinel?
