### ISSUE TITLE
Assign Issue to Self on Dashboard

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#3746]
At the "Unresolved Issues" page, one can select multiple issues and set them to resolved, add them to your bookmarks, etc. But one thing that is missing and would be really helpful is "Assign to me".

This is from a support request.

**Comment by alfonsomga** [comment]
Is this possible? or not yet?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
