### ISSUE TITLE
Better workflow for merging issues

### ISSUE THREAD

**Issue by dmnd** [getsentry/sentry#3751]
Often I open a series of issues in their own tabs to check for duplicates. Once I find duplicates, though, I have to go back to the issues list, careful match up the tabs with the rows in the list (by comparing the ID in the URL), and then merge.

Some suggestions for making this easier:
1. From the issue detail page, paste in a list of IDs/URLs merged to the current issue
2. From the issue detail page, flag an issue as "to merge". Then make it easy to see all flagged issues with a "merge" button.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
