### ISSUE TITLE
DOM Event tab is lagging/slow to load when there are many rows

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#37549]
Everything was laggy while the tab was switching over. After clicking on the "DOM Events" tab button itself, it was slow to see the purple underline switch away from the previous tab and showup under "DOM Events".

I think it has to do with having to render all the html snippets at once. Many of them are hidden though, you have to scroll. We should speedup the render.

A virtual list component might be the way to go here. Don't render every row at the start... virtual list will do it on scroll.

**Comment by danecando** [comment]
It looks like the full page re render triggered on tab change is causing the delay when switching tabs. 
![Screen Shot 2022-08-23 at 10 58 42 AM](https://user-images.githubusercontent.com/3721977/186192383-d62d60f5-5344-47ae-ae22-4ff8f4f53243.png)

The HTMLCode components are a little bit expensive to render so they are compounding the slow re-render work
![Screen Shot 2022-08-22 at 3 51 03 PM](https://user-images.githubusercontent.com/3721977/186192606-480cc748-6392-4dd8-a4c0-8ff4c6824a95.png)
![Screen Shot 2022-08-22 at 3 59 55 PM](https://user-images.githubusercontent.com/3721977/186192671-60c5d529-b638-4533-b5f2-fd87335a6933.png)

**Comment by danecando** [comment]
Lazy loading the HTML Code snippets didn't provide much of an improvement
