### ISSUE TITLE
Search by "last seen"

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3756]
Suggested via support:

> Trying to figure out if I can search by last seen? I can do "age:+30d" but that's based on first seen. I want to find all issues that have not been seen in 30 days. Something like "last_seen:+30d" ...

**Comment by cudasteve** [comment]
`event.timestamp` should do the trick #3678

**Comment by benvinegar** [comment]
> event.timestamp should do the trick #3678

Nah, this is different. This is saying, "find me tickets that have strictly been last seen within a range". Searching on `event.timestamp` returns *any* event that was seen in the provided interval, regardless of whether it was seen more recently.
