### ISSUE TITLE
Generic integration plugins aren't rendering

### ISSUE THREAD

**Issue by holys** [getsentry/sentry#3759]
![image](https://cloud.githubusercontent.com/assets/1198913/16978633/73b712ca-4e8f-11e6-8d92-aae0d22d9dc7.png)

```
Sentry version:  8.6.0
Python: 2.7.11 (default, Jun 29 2016, 12:22:42) 
[GCC 4.4.6 20120305 (Red Hat 4.4.6-4)]

Installed App:

('django.contrib.admin', 'django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.messages', 'django.contrib.sessions', 'django.contrib.sites', 'django.contrib.staticfiles', 'captcha', 'crispy_forms', 'debug_toolbar', 'raven.contrib.django.raven_compat', 'rest_framework', 'sentry', 'sentry.nodestore', 'sentry.search', 'sentry.lang.javascript', 'sentry.lang.native', 'sentry.plugins.sentry_interface_types', 'sentry.plugins.sentry_mail', 'sentry.plugins.sentry_urls', 'sentry.plugins.sentry_useragents', 'sentry.plugins.sentry_webhooks', 'social_auth', 'south', 'sudo', 'sentry_xmail', 'sentry_xsms')
```

When I click the url  `http://shopapi.sentry.b2c.srv/sentry/internal/settings/plugins/xmail/` manually, it redirects  to `http://shopapi.sentry.b2c.srv/sentry/internal/settings/`

**Comment by naglis** [comment]
Hi @holys,

we had a very similar issue (see #3321). Please check if you are not reassigning the `SENTRY_FEATURES` dict in your `sentry.conf.py` configuration file. Instead you should just update it.

**Comment by holys** [comment]
@naglis  I did reassign  `SENTRY_FEATURES` dict in my `sentry.conf.py`, and when I remove it, the plugins page works greatly.  But how can I do something like `SENTRY_ALLOW_REGISTRATION ` ?

**Comment by naglis** [comment]
You can just update the dict. `SENTRY_ALLOW_REGISTRATION` is now [deprecated](https://github.com/getsentry/sentry/blob/d41df76d6ae935d7377f92bce90255d482ddf815/CHANGES#L537) in favor of `SENTRY_FEATURES['auth:register']`, so you can add something like this to your `sentry.conf.py`: 
```python
SENTRY_FEATURES['auth:register'] = False
```

**Comment by holys** [comment]
@naglis  Got it, thanks.
