### ISSUE TITLE
Can't open admin panel after server installation by installation guideline

### ISSUE THREAD

**Issue by hixel** [getsentry/sentry#3760]
Ubuntu - 15.04
Docker - 1.11.2

My steps
1. docker run -d --name sentry-redis redis:3.2-alpine
2. docker run -d --name sentry-postgres --env POSTGRES_PASSWORD=sentry --env POSTGRES_USER=sentry postgres:9.5
3. docker run -d --name sentry-smtp tianon/exim4
4. cd /home/debian/sentry-onpremise <git clone before>
    docker build -t mysentry/sentry .
5. docker run --rm --name sentry-web-01 -p 9000:9000 --link sentry-redis:redis --link sentry-postgres:postgres --link sentry-smtp:smtp --env SENTRY_SECRET_KEY="mcuw=99v*5ex0u-h$n2^g%2#ft(=ac+8=ja5is0vtaj3kg7y(r" mysentry/sentry run web

After 5 step i see
*** Operational MODE: preforking+threaded ***
spawned uWSGI master process (pid: 10)
spawned uWSGI worker 1 (pid: 15, cores: 4)
spawned uWSGI worker 2 (pid: 16, cores: 4)
spawned uWSGI worker 3 (pid: 17, cores: 4)
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x1327490 pid: 16 (default app)
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x1327490 pid: 17 (default app)
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x1327490 pid: 15 (default app)

But when i go to http://[ip]:9000 i get redirect to http://[ip]:9000/auth/login and in console log i see error

... many File errors ... 
django.db.utils.ProgrammingError: relation "sentry_projectkey" does not exist
LINE 1: ..."."status", "sentry_projectkey"."date_added" FROM "sentry_pr...
                                                             ^

SQL: SELECT "sentry_projectkey"."id", "sentry_projectkey"."project_id", "sentry_projectkey"."label", "sentry_projectkey"."public_key", "sentry_projectkey"."secret_key", "sentry_projectkey"."roles", "sentry_projectkey"."status", "sentry_projectkey"."date_added" FROM "sentry_projectkey" WHERE ("sentry_projectkey"."project_id" = %s  AND "sentry_projectkey"."roles" =  ("sentry_projectkey"."roles" | 1)) LIMIT 1

What am I doing wrong?

**Comment by mattrobenolt** [comment]
You definitely missed the `upgrade` step which sets up the database tables.
