### ISSUE TITLE
Breadcrumb icons for LCP & focus & blur events should be purple200 instead of purple300

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#37603]
The mix in too much with important things like click events. Lets soften up the color and make it purple200

Before:

![Image](https://user-images.githubusercontent.com/187460/183703966-3228d8a5-5680-44ae-93ce-47d2980c2928.png)

**Comment by Jesse-Box** [comment]
@ryan953 it's worth discussing this with the team, but my feeling is that by solving #33727 we'll solve this ticket as well. The problem here isn't the colors but the fact these events "pollute" the breadcrumb list.

**Comment by billyvg** [comment]
Closing this ticket since we do not have these breadcrumbs anymore.
