### ISSUE TITLE
[Question] Client side error reporting

### ISSUE THREAD

**Issue by fatagun** [getsentry/sentry#3761]
Hello,

We have a SPA that we get errors, however, errors are not re-producible, hence we can not really capture the error. 

Would JS client help us with this problem?

Can I have a catch all exceptions method to send exceptions to sentry?

**Comment by dcramer** [comment]
@fatagun our JS SDK is entirely designed for browser experiences. Sentry itself is a SPA and uses its own SDK to monitor errors.
