### ISSUE TITLE
Map @sentry/replay feature flag to an internal team on the "sentry" org

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#37623]

**Comment by ryan953** [comment]
I'm looking at where we init the sdk:
https://github.com/getsentry/sentry/blob/3289fcf8cd24f1fecf1fe92d34656a0aa52b9aa6/static/app/bootstrap/initializeSdk.tsx#L85

and we've got this `Config` object, which has a `User` inside it, which has `experiments`: https://github.com/getsentry/sentry/blob/3289fcf8cd24f1fecf1fe92d34656a0aa52b9aa6/static/app/types/user.tsx#L45

So I'm thinking if we can activate that we'll be on the road to success.

**Comment by ryan953** [comment]
Also i noticed that we do a normal import of `import SentryRRWeb from '@sentry/rrweb';`
but then only activate it for staff:
https://github.com/getsentry/sentry/blob/3289fcf8cd24f1fecf1fe92d34656a0aa52b9aa6/static/app/bootstrap/initializeSdk.tsx#L88

So that seems subpar for the rest of the userbase.

**Comment by ryan953** [comment]
cc @billyvg for insights

**Comment by billyvg** [comment]
@ryan953 Ooops missed these comments -- I'm not exactly sure what the `experiments` property is, but the feature flags are generally attached to the org. Feature flag was added here: https://github.com/getsentry/sentry/pull/37761/files#diff-a97d79eb6c3e736e205f4f7e28147494f1592af6f24bb3593e1758d9eca9d7abR28

It's currently added to all sentry staff here: https://flagr.getsentry.net/#/flags/230
