### ISSUE TITLE
Web Vitals look like user activity

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#37864]
## Problem 
Web Vitals give the impression of user inactivity.  

## Solution 
[Figma Designs](https://www.figma.com/file/OPFnT04z0uy8BEUms9OU4f/Specs%3A-Details-v3?node-id=33%3A2991) 
- Visually distinguish and seperate web vitals in the timeline. 
- Remove all web vitals from breadcrumb list.  

### DOM Nodes ![Image](https://user-images.githubusercontent.com/6508377/184913365-01ebb049-6673-42c0-b70e-fbc8516d93cf.png)

**Comment by ryan953** [comment]
Related to #38620
