### ISSUE TITLE
List page search typeahead should be tailored to fields that are available inside replays

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#37968]
Right now when you open the search box on the replay list page there are all kinds of suggestions. Most of these fields are not available on replays. 

![Image](https://user-images.githubusercontent.com/187460/185259500-d64ebcf6-09b6-4e83-b5b9-a52c18c2c520.png)

**Comment by ryan953** [comment]
@cmanallen Can you add/link to the backend info that we'll need in order to do this ticket? There's a new endpoint i heard...

**Comment by cmanallen** [comment]
@ryan953 I'll look into it.  I'm not familiar with this so I'll sync with Josh and let you know what needs to be done.

**Comment by evanpurkhiser** [comment]
What is available to be searched for here?
