### ISSUE TITLE
Bug: Timeline recording status overflows when a recording finishes playing

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#38000]
Example replay: https://sentry.io/organizations/sentry/replays/javascript:f928ac21-d6dc-4300-945e-d0f05863ae8a/

Play the recording and when it finishes, the purple "status" bar in the timeline ends up overflowing.

![Image](https://user-images.githubusercontent.com/79684/185430039-f8cb4915-4473-488b-b063-1c8d72470ee8.png)

**Comment by ryan953** [comment]
I think this is a start/finish timestamp issue

- The replay says: `finishedAt = "2022-08-18T14:54:58+00:00"` (note: 58th second)
- The last segment has a timestamp of: `dateAdded: "2022-08-18T14:54:59.058074Z"` (note: 59th second)

So that segment is appearing 'after' the replay is finished.

**Comment by ryan953** [comment]
Related to https://github.com/getsentry/sentry-replay/issues/148

**Comment by billyvg** [comment]
@ryan953 Here's one where it looks like finishedAt == last segment but it's overflowing: https://sentry.io/organizations/sentry-emerging-tech/replays/billy-test:a059b6139367467aab10579061436c47/

Maybe because we lose precision with the `duration` from the replay record?

**Comment by billyvg** [comment]
This should be fixed by https://github.com/getsentry/sentry-replay/pull/169

**Comment by benvinegar** [comment]
Do we believe the above PR fixed this? Can we close?

**Comment by billyvg** [comment]
Going to see if the cause for duplicate segment ids has also fixed this -- I believe there were still instances where this was overflowing.

**Comment by billyvg** [comment]
https://sentry.io/organizations/sentry/replays/javascript:952bb398d92242afa05a3676afb08443/?referrer=%2Forganizations%2F%3AorgId%2Freplays%2F&t_main=network

**Comment by billyvg** [comment]
https://sentry.io/organizations/sentry/replays/javascript:4f3fdfe947b1497cb0ce98710bcf5e26/?referrer=%2Forganizations%2F%3AorgId%2Freplays%2F

**Comment by billyvg** [comment]
I think @ryan953 is going to change the frontend behavior to not use the timestamps that lack ms precision.

**Comment by ryan953** [comment]
I think this is fixed now by https://github.com/getsentry/sentry/pull/40281 

The improvement is inside of static/app/utils/replays/replayReader.tsx, the `finishedAt` timestamp usually has `ms` precision, and we're using that to re-calculate the `duration`. That sets the right-most bounds of the `<Timeline>` to the correct place so we shouldn't overflow in the way we have before.

**Comment by ryan953** [comment]
There are three examples in the thread above that are still available, they're all working great now:

- Example From Sept 1st (https://github.com/getsentry/sentry/issues/38000#issuecomment-1234378274) 
   <img width="343" alt="Screen Shot 2022-10-21 at 9 02 09 AM" src="https://user-images.githubusercontent.com/187460/197239759-2fd552a2-4d96-41ca-8c53-a67690b8a397.png">

- Example From Sept 19 (https://github.com/getsentry/sentry/issues/38000#issuecomment-1251423672)
    <img width="411" alt="Screen Shot 2022-10-21 at 9 02 13 AM" src="https://user-images.githubusercontent.com/187460/197239893-f46f4377-d516-432e-8b74-f10cf678e9a5.png">

- Example From Sept 23 (https://github.com/getsentry/sentry/issues/38000#issuecomment-1256646515)
   <img width="387" alt="Screen Shot 2022-10-21 at 9 02 18 AM" src="https://user-images.githubusercontent.com/187460/197239958-4fce44cd-d71f-4217-9319-cbba80da3a0b.png">



Looks much better, I will close it out now.
