### ISSUE TITLE
Bug: Errors are not correctly showing up on the Details header and Issues tab

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#38001]
See https://sentry.io/organizations/sentry/replays/javascript:bb62563b-2e9f-474a-b907-f981603057a2/?t_main=console (there should be 3 errors associated with it, Index page displays countErrors correctly).

**Comment by ryan953** [comment]
Issue tab should be fixed with #38002. The issue is dashes inside the `replayId` value, thanks to auto-formatters in snuba.
