### ISSUE TITLE
Bug: Tracing tab is not functional

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#38002]
Seems like we need to update the query after switching to the new backend

**Comment by ryan953** [comment]
The problem seems to be that there are dashes in the `replayId`.

#38014 would fix it, but it's better to just not send around formatted uuid's at all. The better fix is to make the backend remove dashes before sending.

**Comment by JoshFerge** [comment]
btw, all dashes should be able to be removed now.

**Comment by JoshFerge** [comment]
i see traces sometime work now? not sure if this is fixed.

**Comment by ryan953** [comment]
Can confirm that the trace tab does load now:

![Screen Shot 2022-09-08 at 9 55 32 AM](https://user-images.githubusercontent.com/187460/189181216-d8d43d03-5a46-4f0b-835d-b001baca5a99.png)

closing ticket.
