### ISSUE TITLE
Password Verification in Account Settings

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#3802]
We intentionally currently only validate the password for password changes but we might want to do it for mail as well. In any case we should change the messaging on this page as it seems to indicate you always need to reply it.

**Comment by dcramer** [comment]
This already should be happening. There are tests that cover this behavior. 






On Tue, Jul 26, 2016 at 5:15 AM -0700, "Armin Ronacher" <notifications@github.com> wrote:












We intentionally currently only validate the password for password changes but we might want to do it for mail as well. In any case we should change the messaging on this page as it seems to indicate you always need to reply it.

**Comment by benvinegar** [comment]
I've confirmed you are prompted to verify your password before being able to add an email.

![image](https://user-images.githubusercontent.com/2153/46268748-24e5c300-c4f1-11e8-9205-9e6714fd9125.png)

**Comment by mitsuhiko** [comment]
@benvinegar for what it's worth this refers to the case that adding an email brings up the sudo prompt whereas changing the password asks for the actual old password. Originally those were on the same page and the password was only required for the password change.

I think security wise what the dialog does now is acceptable and the confusing messaging is gone.
