### ISSUE TITLE
No Password Length Verification

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3804]
**Link**:		https://hackerone.com/reports/153978
**Date**:		2016-07-26 09:54:54 UTC
**By**:		daniyal_nasir
**Types**:	Authentication, Design Issue

**Details**:
"No Password Length Verification"
(Insecure Password Security Layer)

Hello Team, I have found that,

i am able to create a password with 10000000 characters while sign up on Sentry Web Application while signing up. which fully leads to MySQL or server side Denial Of Service attack.

Anyone can create an account on with 10000000 characters passwords, also when ever you will go for login you have to enter those 10000000 characters...

You need to decrease password length :There are two reasons for limiting the password size.
For one, hashing a large amount of data can cause significant resource consumption on behalf of the server and would be an easy target for MySQL Denial Of Service attack.

Normally all sites have a password minimum to maximum length like 72 words limit or 48 limit to prevent Denial Of Service attack in mySQL....

but in Sentry web application, there are no limitation.

Kindly Set your Password Length to 48 or 72.....

Kindly Fix this ASAP.

Thanks for taking time to read this report!

best regards,
Daniyal Nasir
Security Researcher

**Comment by mdamien** [comment]
This have been fixed in 2013, https://www.djangoproject.com/weblog/2013/sep/15/security/#s-issue-denial-of-service-via-large-passwords

Can't reproduce on my instance for example.

**Comment by mattrobenolt** [comment]
Yeah, I'll see why we don't handle this. It should be super trivial to patch.

**Comment by mattrobenolt** [comment]
Hmm, we don't do anything special here, and we just literally use Django behavior here. We also run against 1.6.11. Going to manually verify, but I don't see how this is applicable to us.

**Comment by mattrobenolt** [comment]
welp, somehow this patch never landed into a tag on 1.6.x branch for Django. Not sure how that happened.

**Comment by mattrobenolt** [comment]
I guess it was reverted and deemed unnecessary:

https://github.com/django/django/commit/50a811a170dfeddd9c27d21aee36801277d21bf3
https://github.com/django/django/commit/50a811a170dfeddd9c27d21aee36801277d21bf3

**Comment by mattrobenolt** [comment]
I'm closing this since it's not applicable after the Django patch. On my computer, before being able to take any reasonable amount of resources, the password would have to be 1GB long, in which, this is now the least of the concern, and we wouldn't allow this volume of data.
