### ISSUE TITLE
Disable autocomplete for phone number in 2FA flow

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3805]
It was brought to our attention through a security report that it's against best practice to store phone number in the field used for 2FA, so should be easy, unless we have an objection by killing this. It doesn't seem overly useful, and I'd personally be ok with removing autocomplete on the field.

Thoughts? @getsentry/ui @getsentry/security

**Comment by benvinegar** [comment]
Do you mean the phone number field when configuring 2FA, or the "secret code" field when you are submitting what was sent to your phone to complete 2FA?

If it's the former (disabling auto-complete on phone number configuration), can you elaborate on how this is a security concern?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
