### ISSUE TITLE
Typo on Sentry's website.

### ISSUE THREAD

**Issue by shiyanshirani** [getsentry/sentry#38105]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

On Sentry's [page](https://sentry.io/for/django/) in **Django Error Monitoring with Complete Stack Traces** block, the description is ended with a blunt word **Django**. 

### Expected Result

The description box should have been - 
See local variables in the stack for prod errors, just like in your dev environment. Introspect more deeply into the runtime and jump into the frame to get additional data for any local variable. Filter and group Django exceptions intuitively to eliminate noise.~~Django~~

### Actual Result

![Screenshot 2022-08-23 at 12 51 40 PM](https://user-images.githubusercontent.com/51873238/186096486-5a406eae-f2bf-4563-b3c2-564128913adf.png)

**Comment by shiyanshirani** [comment]
I was not able to locate the html file in project directory, Kindly point out the file so I can fork and make the changes.

**Comment by dashed** [comment]
@shiyanshirani Thanks for reporting in on this! 🙏  Unfortunately, the source code for our marketing website doesn't reside within this repository. However, I've gone ahead and fixed it. 👍

**Comment by shiyanshirani** [comment]
Thanks. :)
