### ISSUE TITLE
Session Replay internal alpha: user analytics

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#38315]
**Problem**

We will be launching an internal alpha of session replay in September. We want to understand how users are interacting with the product, as well as who are the most active users.

**Solution**

Instrument user analytics on Amplitude:

1. Clicks on the Replay Details page (broken down by user email)
2. How did a user land on Replay Details: from Issues, from Transaction Summary, or from the Replay Index page
3. What changes are made to the layout configuration - clicking "Player Top", "Player Left", "Player Right" or the dragging of the replay video

**Comment by Jesse-Box** [comment]
@jas-kas here is a brain dump

### How are people finding a replay from the index page?
- **Are certain URL's being clicked on more than others?** Meaning is our assumption that users care more about specific URL's correct or not? 
- **What metric are users using to find a specific replay?** Meaning do they sort by duration, timestamp, errors, activity
- **How are people using the search to filter the results?** Might give us insights into how we should improve this page.

### How are people using the details page
- **How are users getting to the details page?** You already mentioned it above, but is it from issue details, performance, replay index?
- **Whats their first, second and third interaction?** I need to understand what people are typically doing on this page to understand how aligned my assumptions are with reality. If it's really off, then we can reach out to people for interviews.
- **What's the average duration spent on a details page?** I'm thinking that if people only spend say _less than 1min_ on each replay, its likely they are a) not debuging, just poking the UI, or b), not finding the _right_ information.
- **How are people navigating a replay?** Are they using the breadcrumb list, event timeline, the video scrubber or perhaps a row from within a given tab
- **Are people changing their layout?** Given there is a default, would be nice to know how much people change it and to what?

Hope that helps!

**Comment by ryan953** [comment]
Clicked play/pause

**Comment by ryan953** [comment]
log which tabs get opened

**Comment by hubertdeng123** [comment]
@ryan953 Just wondering, does self assigning automatically add the `Team: Emerging Technology` tag to the issue or did you add it yourself? I'm not seeing the tag being added in the history of the issue and am wondering if it is an issue with our automation.

**Comment by ryan953** [comment]
> @ryan953 Just wondering, does self assigning automatically add the `Team: Emerging Technology` tag to the issue or did you add it yourself? I'm not seeing the tag being added in the history of the issue and am wondering if it is an issue with our automation.

I've not seen it get auto-added, i add it manually whenever i see that it's missing

**Comment by ryan953** [comment]
closing this one because it's marked done on the project board, and the latest ideas are captured in https://github.com/getsentry/sentry/issues/38581
