### ISSUE TITLE
Filtering individual events in an issue

### ISSUE THREAD

**Issue by cudasteve** [getsentry/sentry#3832]
When searching, it's possible to limit search results to only issues that have occurred in a particular release or environment or other criteria.  But the results show all the information for the issue.  It'd be nice to be able to filter the events that have taken place in an issue and display only the information about those.

For example, "how many times have we gotten error x in the test environment in the last release?"

**Comment by dcramer** [comment]
@cudasteve likely never going to happen as its extremely expensive (as in unrealistic) to compute that on the fly.

We *will* however be adding project-wide environment filtering in the future, and the goal there is that all data reflects that environment (counts and tags).
