### ISSUE TITLE
`architecture` key in contexts.device not behaving as expected

### ISSUE THREAD

**Issue by marcomorain** [getsentry/sentry#3835]
When I send an event with `contexts.device.architecture` set, the data does not seem to parsed correctly. See this screenshot:

<img width="861" alt="screen shot 2016-07-28 at 23 21 08" src="https://cloud.githubusercontent.com/assets/448001/17231476/ffef3ac0-5519-11e6-830c-73fc1379eb8a.png">

## Expected:
A single 'Architecture' row in the UI.

## Actual:
There are 2 architecture rows in the UI, one with a capital `A`, the other with lowercase `a`. The row with the uppercase `A` is incorrect.

I tried sending the event with the key renamed to `contexts.device.Architecture` but it didn't fix the issue.

## Event URL:

https://app.getsentry.com/flipdish/development/issues/146030552/ (not public)

## Event JSON:

```
{
  "id": "775b4f9ac9be482c9cee77400acef66d",
  "project": 75499,
  "release": null,
  "platform": "java",
  "culprit": "",
  "message": "Device Test",
  "datetime": "2016-07-28T22:14:26.000000Z",
  "time_spent": null,
  "tags": [
    [
      "level",
      "info"
    ],
    [
      "device",
      "VF-895N"
    ],
    [
      "device.family",
      "Vodafone"
    ],
    [
      "os",
      "Android 5.0.2"
    ],
    [
      "os.name",
      "Android"
    ]
  ],
  "contexts": {
    "device": {
      "screen_resolution": "1280x720",
      "model_id": "VF-895N",
      "orientation": "portrait",
      "family": "Vodafone",
      "architecture": "armv7l",
      "model": "VF-895N",
      "type": "device"
    },
    "os": {
      "kernel_version": "3.10.49-gfd96891",
      "version": "5.0.2",
      "type": "os",
      "name": "Android",
      "build": "21"
    },
    "package": {
      "type": "default",
      "version_name": "1.0",
      "version_code": "1",
      "name": "com.joshdholtz.sentryapp"
    }
  },
  "errors": [],
  "extra": {},
  "fingerprint": [
    "{{ default }}"
  ],
  "metadata": {
    "title": "Device Test"
  },
  "received": 1469744067,
  "sdk": {
    "version": "0.2.0",
    "name": "sentry-android"
  },
  "sentry.interfaces.Message": {
    "message": "Device Test"
  },
  "type": "default",
  "version": "7"
}
```

**Comment by marcomorain** [comment]
I came across this when adding device and OS contexts to the Android SDK - https://github.com/joshdholtz/Sentry-Android/pull/61.

**Comment by dcramer** [comment]
I believe the key is "arch". Let me know if there's still issues b

**Comment by marcomorain** [comment]
Looks like a docs bug then - https://docs.getsentry.com/hosted/clientdev/interfaces/#context-types says `architecture`?
