### ISSUE TITLE
Bug: CurrentUrl is missing a border now that it's separate

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#38354]
![Image](https://user-images.githubusercontent.com/187460/187770619-25e628dd-39c3-402c-9326-a991fbbe92ef.png)

Seems related to https://github.com/getsentry/sentry/pull/38159

**Comment by ryan953** [comment]
Duplicate of #38012

**Comment by ryan953** [comment]
Duplicate of #38012

**Comment by ryan953** [comment]
Duplicate of https://github.com/getsentry/sentry/issues/38012

**Comment by danecando** [comment]
Fixed in #38363
