### ISSUE TITLE
Verification email not being sent

### ISSUE THREAD

**Issue by Programmix** [getsentry/sentry#3842]
I have set up Sentry with Docker following the guide [here](https://hub.docker.com/_/sentry/) to the best of my ability. I added my e-mail as a superuser and then logged in. However, I discovered that I'm unable to create projects, which led me to assume I needed to verify my e-mail. However, Sentry doesn't seem to actually be sending me the verification e-mail. Sending e-mails from the command line works fine. The only thing I notice in the logs regarding e-mails is this:
`[INFO] sentry.mail: mail.queued message_to=u'[redacted]@gmail.com' message_id='<20160730044311.21.86886@localhost>' message_type='user.confirm_email'`

**Comment by mattrobenolt** [comment]
Did you properly configure email to talk to an SMTP server? It just sounds like that's not setup. Without anything, the default backend is "dummy" which means nothing happens. 

Either that, or you don't have a worker running to consume the jobs from your queue.

**Comment by Programmix** [comment]
Pretty sure I have a worker running. In the config, the backend is set to `smtp`. How would you recommend setting up an SMTP server?

**Comment by mattrobenolt** [comment]
If you have a worker going, there should be logs from the worker to indicate if the mail was sent or not.

**Comment by Programmix** [comment]
The worker seems to be running fine. Puts this in the log.
`[INFO] sentry.mail: mail.sent message_id='<20160730061040.20.66307@localhost>'`
However, I'm not receiving the mail.

**Comment by mattrobenolt** [comment]
Yeah, then I don't know. This is simply a misconfiguration then with your credentials. Make sure the smtp host and whatnot are correct.

**Comment by Programmix** [comment]
Been trying to get this set up properly for a few hours now. xD
What should `mail.host` and `mail.from` optimally be configured to?

**Comment by mattrobenolt** [comment]
Well, you need a mail server first of all. Then use the credentials for that. There isn't a magical answer here.

**Comment by Programmix** [comment]
Tried using gmail's SMTP server, set credentials in `config.yml`. Still won't send an e-mail. :/

**Comment by tkaemming** [comment]
Have you been restarting the worker after these configuration changes?

**Comment by pokemane** [comment]
Really sorry to necro, but:

I'm having a similar issue.  Test email works, verification and invite emails do not.  I have not had the opportunity to test event emails yet.

Celery worker log:
```
19:11:14 [INFO] sentry.mail: mail.sent (size=4757 message_id='<20161208191113.20.10373@domain.com>')
```

**Comment by pokemane** [comment]
Found it.  The `SENTRY_EMAIL_HOST` env var and its companions need to be set for the workers as well as the main sentry container instance.  Apologies again for thread necro.

**Comment by arthurlogilab** [comment]
This this a documentation bug.

**Comment by arthurlogilab** [comment]
Maybe it's not... wouldn't it be better that the test email procedure should run through the worker since most emails sent by sentry are done though the worker (or have both processes send an email).

Or maybe the worker should log an error... this is a silent fail...

**Comment by dcramer** [comment]
I'm closing this as there are no issues in Sentry and this is simply people not understanding (and I don't mean to sound harsh) basic operations. It's our point of view that if you're not familiar with the technologies or do not have the expertise required to run such a complex infrastructure service, you should probably be considering using our cloud offering.
