### ISSUE TITLE
Performance sub-tabs switching automatically

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry#38435]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

In the Sentry UI, create a new project and select .NET as the platform type

After the project is built:
- Go to the Performance tab
- Select "All Transactions"
- Select the project

### Expected Result

The sub-tab should still be on "All Transactions".  If there were any transactions for my project, I would be seeing them as expected.

Filtering to one of the sub-tabs should be the user's choice, and not changed automagically per project.

### Actual Result

The sub-tab switched away from "All Transactions" and is now on "Backend".  I'm only looking at transactions for my project that are categorized as backend transactions.

This is problematic for several reasons:
- Intuitive UX interaction is upper-left to lower-right.  This issue forces you to go backwards.
- For .NET, not all transactions are going to be under "backend".  Indeed, .NET can be used to make console, desktop, and mobile applications as well.  For example, a typical user may try a console or desktop app first, then go to Performance and see nothing because they're on the wrong tab.
- This applies to other languages and tab types as well - it's not unique to .NET
- We can lock the project selection, but we can't lock the tab filter.  Change to "all transactions", leave the performance tab and come back, and you're back on "backend".  It doesn't remember.

**Comment by mattjohnsonpint** [comment]
https://user-images.githubusercontent.com/1396388/188248584-e11ff0a2-ea0d-4748-859a-a3713fba5c8a.mov

**Comment by om-ray** [comment]
@mattjohnsonpint Would storing the tab you were in last in localStorage be a solution to this problem?

**Comment by DominikB2014** [comment]
hey @mattjohnsonpint!
I'm going to close this as we are planning planning to remove the performance item in the sidebar in favour of Insights > Frontend, Backend, Mobile, etc

This issue would not apply anymore as these tabs would no longer exist. Feel free to reopen a new issue if you would like to suggest some improvements to our new domain specific views
