### ISSUE TITLE
Feature request: Jscript handles offline error caching

### ISSUE THREAD

**Issue by matsomahoney** [getsentry/sentry#3843]
We have to handle offline scenarios quite a lot in our web app.  When an error is thrown and caught by sentry AND user is offline  THEN error is lost.  It would be great if it were queued up and sent up to Sentry when comes back online i.e using html5 offline storage or the like .. This would just round-out the product that much more.  Thanks for considering

**Comment by benvinegar** [comment]
Hi there, this ticket should go in getsentry/raven-js, our browser JavaScript SDK. There's already an open issue on this topic: getsentry/raven-js#279.
