### ISSUE TITLE
Design: HMW better surface an individual replay preview on an error event in Issues

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#38463]
### Problem
Today users need to scroll down to the bottom of the event details to discover if there's a replay attached. HMW surface replays on error events more proactively so they are easily discoverable and actionable in Issues?

### Potential ideas
-  highlight replays in the aggregate information in the right sidebar, or in the top-right data
- add an indicator at the top of event details to show there is a replay on this event
- changes to the Replays tab in Issues 

#### Figma
https://www.figma.com/file/f9ywS3TPYGjgOvx4ff4dvY/Specs%3A-Replay-in-Issues?node-id=7%3A2869

#### Screenshots
![Image](https://user-images.githubusercontent.com/6508377/190657762-498c7d9e-837a-4e85-a1d7-1fa94dd51bbd.png)
![Image](https://user-images.githubusercontent.com/6508377/190657778-80cc6342-8bed-4f50-86f8-56da85fe1962.png)
![Image](https://user-images.githubusercontent.com/6508377/190657783-8f47c2eb-1158-446d-908f-24807e2d1d9d.png)

**Comment by ryan953** [comment]
There was idea to integrate with the existing Trace bubbles that are at the top of Issue Details, and then have a link to say a) there is a replay associated with this error instance b) click to jump down to the replay.

**Comment by Jesse-Box** [comment]
@jas-kas @ryan953 Updated Issue Description with my latest concepts

**Comment by jas-kas** [comment]
This design ticket is closed by the implementation ticket [38956](https://github.com/getsentry/sentry/issues/38956)
