### ISSUE TITLE
Fix org memberlist button and avatar alignment

### ISSUE THREAD

**Issue by ckj** [getsentry/sentry#3846]
Minor rendering issue on mobile breakpoint

![screen shot 2016-08-01 at 11 34 24 am](https://cloud.githubusercontent.com/assets/30713/17304777/1f00bb90-57dc-11e6-8b21-b5293481cbbf.png)

cc @getsentry/ui @tkaemming

**Comment by shubhpatel108** [comment]
The buttons overflows in smaller screens.

<img width="421" alt="screen shot 2016-09-28 at 1 34 26 pm" src="https://cloud.githubusercontent.com/assets/4345133/18905345/5328a2bc-8580-11e6-93d3-b3d34aea1f08.png">
