### ISSUE TITLE
Bug: Dom Events tab doesn't show all DOM events although there are user clicks in the breadcrumbs

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#38465]
Example replay: https://sentry.io/organizations/sentry/replays/javascript:35d8228d910043fc82caac2c87e50c20/?t_main=dom

**Comment by ryan953** [comment]
I wonder if this is related to the missing-segment issue, causing dropped frames, so we're unable to read the dom.

**Comment by JoshFerge** [comment]
yeah its missing a few segments
to check, you can just simply remove the “download” query parameter from the endpoint query
https://sentry.io/api/0/projects/sentry/javascript/replays/35d8228d910043fc82caac2c87e50c20/recording-segments/

**Comment by ryan953** [comment]
Ok, since this is missing some segments and that is a known problem I think this can be closed.
Last segment is id=19, it's missing missing 8, 9, 11, 13, 15.

If we see the empty state again then lets re-open the bug.
