### ISSUE TITLE
Bug: "Error while fetching this replay" from a 5d old replay

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#38466]
Example replay: https://sentry.io/organizations/sentry/replays/javascript:a8132a7e7f86455f81476523b3849efe/

**Comment by ryan953** [comment]
cc @billyvg is this the same replay that was crashing because `Sentry.captureException(error);` had an issue and threw?

**Comment by ryan953** [comment]
cc @billyvg is this the same replay that was crashing because `Sentry.captureException(error);` had an issue and threw?

**Comment by ryan953** [comment]
cc @billyvg is this the same replay that was crashing because `Sentry.captureException(error);` had an issue and threw?

**Comment by ryan953** [comment]
This is related to the known problem of fetching too many segments at once, causing timeouts.

**Comment by JoshFerge** [comment]
Actually not related to fetching too many segments, there was a bug in our utf-8 parsing / decompression logic. Fixed by https://github.com/getsentry/sentry/pull/38481
