### ISSUE TITLE
Load initial segment chunk, then async load the remainder so the pageload feels quicker

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#38524]
Related to #38521 

This is the harder version of #38521. In #38521 we've got to render the replay object when it loads. 

In this ticket, we're talking about streaming in the rrweb data, so the timeline could off being empty (no events/icons to display) and then those icons will pop in over time as the rrweb data downloads. Playback while rrweb events are downloading could be truncated

**Comment by billyvg** [comment]
@ryan953 This is done now right?

**Comment by ryan953** [comment]
We merged https://github.com/getsentry/sentry/pull/44561 so I do think this is done now yes.
