### ISSUE TITLE
trying CAS integration with Sentry

### ISSUE THREAD

**Issue by prashant3863** [getsentry/sentry#3854]
Sorry, I don't know if this is the right place to ask this. I am trying to integrate CAS with Sentry. I see there is no inbuilt support for that in Sentry. I would have to write that on my own. After searching I found that `https://github.com/mingchen/django-cas-ng` should help me. But I am a bit confused on the extent of code changes I would have to do. Any guidance would be highly appreciated. 
P.S. I am new to Django.

**Comment by dcramer** [comment]
It's very possible it won't work. Sentry *is* a Django application, but its arguably one of the most complex in existence. We also have our own authentication systems, which means many things simply won't work without modifying Sentry (which we wouldn't support upstream). We leave it as an exercise to the reader to try and make CAS work, but it's not something we'll provide support for and seems fairly complex.
