### ISSUE TITLE
Allow sentry upgrade to run unattended

### ISSUE THREAD

**Issue by jmatsushita** [getsentry/sentry#3855]
When deploying with container orchestration tools (we're using rancher) we want to allow specifying everything in environment variables. Would it be possible to allow this instead of (or in addition to) the interactive first user creation with `sentry upgrade` ?

**Comment by dcramer** [comment]
It won't be possible to configure the default user with environment variable. You can always shell in or access the database to define data.

**Comment by jmatsushita** [comment]
I know I *can* but I don't think I *should* have to given that its best practice to allow unattended installation.

**Comment by mattrobenolt** [comment]
You can run `sentry upgrade --noinput` to avoid being prompted. That will just skip creating the user to allows an unattended install/upgrade to work. You could then additionally create the user with your own script or exec the commands. We won't be adding a method to automatically do this based on environment variables. There are many ways to do this.

**Comment by jmatsushita** [comment]
Awesome. I with `sentry upgrade --noinput` and 
```
# sentry createuser --help
Usage: sentry createuser [OPTIONS]

  Create a new user.

Options:
  --email TEXT
  --password TEXT
  --superuser / --no-superuser
  --no-password
  --no-input
  --help                        Show this message and exit.
```

I'm sorted!

Thanks!
