### ISSUE TITLE
Clean up "referrer" event property for Session Replay user analytics

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#38555]
**Problem:**

The referrer event property for the `Viewed Replay Details` reload event returns many unique URLs. Thus, reducing the legibility of the Amplitude chart and ability to pull key insights quickly. 

![Image](https://user-images.githubusercontent.com/77064737/189134720-33cf181e-747d-418d-a59a-4e9f6e209dbb.png)

**Solution ideas:**

- Use Transaction name
- Alt: Drop query params

Related to [38315](https://github.com/getsentry/sentry/issues/38315) https://github.com/getsentry/sentry/pull/38370

cc @ryan953

**Comment by ryan953** [comment]
I made a fix to how the data in the dashboard is queried and it seems like we're getting what we expect now.

The key insight i found is that there are two `referrer` fields in the data; The Event Property, and the User Property:
<img width="549" alt="Screen Shot 2022-09-16 at 2 04 03 PM" src="https://user-images.githubusercontent.com/187460/190753296-48624980-8c0c-49ac-a722-be8068fdfcb6.png">


Previously the chart is defined to group-by using the User prop:
<img width="963" alt="Screen Shot 2022-09-16 at 2 12 28 PM" src="https://user-images.githubusercontent.com/187460/190755201-f7461b69-0a18-4f89-83a4-32e596f653b2.png">


The dashboard should be grouping by the event prop:
<img width="966" alt="Screen Shot 2022-09-16 at 2 12 49 PM" src="https://user-images.githubusercontent.com/187460/190756402-eb21afcf-3fd2-47ab-8a81-190738fd932f.png">
