### ISSUE TITLE
Replay Search results should render and match what Issues does

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#38575]
I think that the page should behave:
- if there is a real backend error (like a 5xx response) we show the error message inside the table, instead of blowing up the whole page ✅ (see invalid syntax example below)
- if the user input is bad (invalid search term, 4xx response), we show "no-results" inside the table. (see no results example below)
- if the js on the page throws an error then an error message taking over the whole are (like we had before) can still make sense, although this shouldn't be happening i don't care about handling it specifically.

**Dependencies:** One question I have is whether the backend responds with the correct 4xx or 5xx response codes. Making sure that is working as expected is probably a requirement to testing and landing this change.
Related: https://github.com/getsentry/replay-backend/issues/115

Example issues fail search (invalid syntax):
![Screen Shot 2022-09-08 at 10 19 37 AM](https://user-images.githubusercontent.com/187460/189185816-0092bbec-7534-4944-8423-12f82f83fff3.png)

example issues search with no results:
![Screen Shot 2022-09-08 at 10 03 23 AM](https://user-images.githubusercontent.com/187460/189182560-f2fc926a-f44a-4749-bca4-7b3853578219.png)

**Comment by cmanallen** [comment]
Notes on 400 errors from the /replays resource.

- No field is considered invalid.  All fields are filtered.  If no column exists we look for a matching tag.
- Fields have operator restrictions.  Environment can't be filtered with `>` for example.  This will raise a 400 error.
- Fields have value restrictions.  Duration, and other numeric fields, can not equal alpha characters.  E.g. `duration:wow` would 400.
