### ISSUE TITLE
Design: Improve the connection between the Issues tab and the error events that occur in the replay video

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#38578]
**Problem:**

Today you can see all issues that belong to errors found in a replay in the Issues tab on Replay Details. However, there are no timestamps on the issue to bring users to that exact moment in the replay video (unlike the other tabs on Replay Details). What makes this more complicated is an issue may have multiple errors in the same Replay. 

Here's an example where there were 3 different issues, and 8 error events for a given replay. There's no way for a user to easily navigate to the errors belonging to a specific issue in the Issues tab. As a result, users need to dig through the timeline or breadcrumbs to find the relevant error events.

![Screen Shot 2022-09-06 at 4 25 14 PM](https://user-images.githubusercontent.com/77064737/188731378-82e7c67b-2e34-46e2-b823-3742ec5c19bf.png)

HMW improve the connection between the Issues tab and the error events that occur in the replay video?

**Solution**

TBD on Design.

**Comment by Jesse-Box** [comment]
@jas-kas I'm honestly thinking that #38461 solves most of challenges mentioned above.

**Comment by jas-kas** [comment]
@Jesse-Box I think so! But I'll wait until we finalize the design of [#38461](https://github.com/getsentry/sentry/issues/38461) before we close this ticket.

**Comment by jas-kas** [comment]
This design ticket is closed by the implementation ticket [#38861](https://github.com/getsentry/sentry/issues/38861).
