### ISSUE TITLE
Bug: Deduplicate LCP breadcrumbs by picking the last LCP when there are a string of them together

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#38592]
This will eventually be solved on the SDK side (https://github.com/getsentry/sentry-replay/issues/100), but until then we should just display one LCP when there are a few in a row.

![Image](https://user-images.githubusercontent.com/187460/189455185-0e1eecfb-b7e0-4e15-9a75-cb1633fb82e3.png)

**Comment by billyvg** [comment]
Fixed by https://github.com/getsentry/sentry-replay/pull/209
