### ISSUE TITLE
Username filtering in UI

### ISSUE THREAD

**Issue by MrChrisW** [getsentry/sentry#3859]
We have the following configuration for setting up the `user_context`. 
```
       Raven.user_context(
          id: current_user.id,
          email: current_user.email,
          username: current_user.username,
        )
```

According to the [docs](https://docs.getsentry.com/hosted/learn/context/)

>Each of these is optional, but one must be present in order for the user to be captured.

When using the "filtering" options in the Sentry WebUI, only the `id` can be filtered. 

![image](https://cloud.githubusercontent.com/assets/5282264/17357548/db9caa16-598f-11e6-892a-11962dce8eec.png)

___________

I've tested removing the `id` from the `user_context` and can then search by username.

![image](https://cloud.githubusercontent.com/assets/5282264/17357576/0c793d70-5990-11e6-9372-db5627a563a7.png)

_________

Can we have both the `username` and `id` values in the `user_context` but still search for `username` in the UI ? What dictates that the `id` is the only field searchable if included?

**Comment by dcramer** [comment]
You can user 'user.username:foo' as a search term. Take a look at our docs under Search for more examples.

**Comment by MrChrisW** [comment]
@dcramer I'm aware of the ability to use `user.username:foo` as a search term. 

However shouldn't I be able to search by `username` or `id` in the `USER` UI field?

**Comment by dcramer** [comment]
@MrChrisW we'd plan to add it there at some point, its just not available at this time

**Comment by MrChrisW** [comment]
@dcramer Thanks for your quick responses 👍 . Is there a feature proposal somewhere or something to track the progress? Or just wait and see 😃

**Comment by dcramer** [comment]
@MrChrisW we sometimes track features on GitHub, but to be quite honest, theres far too much volume and far too many things for it to be reliable. At this point we don't have a timeline when we'll add typeahead support for user.

**Comment by MrChrisW** [comment]
No problem mate, we had a quick discussion about this on a [GitLab](https://gitlab.com/gitlab-com/support-kb/merge_requests/7#note_13220864) MR and decided to lodge an issue. Cheers 👋
