### ISSUE TITLE
`device.family` tag recorded inconsistently, gives deceptive insights

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3862]
We don't capture `device.family` for all browsers, which leads to situations like below, where "100% of events" are shown as having `device.family` value "Spider".

![image](https://cloud.githubusercontent.com/assets/2153/17384944/4b25794a-5994-11e6-9bcc-03530f262f2c.png)

In reality, these tags represent data from 10s of thousands of events, and only **4** recorded "Spider" for `device.family`. For all other events, this tag was never provided.

**Comment by m-vdb** [comment]
any progress here? :)

**Comment by dcramer** [comment]
fwiw this is the same for a few things I believe

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
