### ISSUE TITLE
Each tab looks quite different

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#38620]
### Problem
- Depending on which tab you have active, the UI style vary quite a bit, which in turn, makes it hard to iterate on the experience.

### Acceptance Criteria
- As a user, I expect a consistent look and feel when navigating, Console, DOM Events & Network
- As a user, I can clearly see which element within a given tab is selected, hovered and focused

#### Rewatch
https://sentry.rewatch.com/video/a4oif3v3v0gsbbjc-rewatch-replay-details-highlighting-ui-feedback-round-1
#### Screenshots
![Console](https://user-images.githubusercontent.com/6508377/189325874-98a55468-a5e8-4ada-8842-0274a6d4a510.png)
![DOM Events](https://user-images.githubusercontent.com/6508377/189325897-d1c80ad2-14ce-4d96-aa27-ee8c0d702d32.png)
![Network](https://user-images.githubusercontent.com/6508377/189325909-56275089-dd99-4fd3-b910-cbeded28f75d.png)
#### Figma
- Breadcrumb Component https://www.figma.com/file/OPFnT04z0uy8BEUms9OU4f/Specs%3A-Details-v3?node-id=142%3A8712
- Console Component https://www.figma.com/file/OPFnT04z0uy8BEUms9OU4f/Specs%3A-Details-v3?node-id=104%3A8686
- DOM event component https://www.figma.com/file/OPFnT04z0uy8BEUms9OU4f/Specs%3A-Details-v3?node-id=104%3A8713
- Network component https://www.figma.com/file/OPFnT04z0uy8BEUms9OU4f/Specs%3A-Details-v3?node-id=104%3A8770

#### Tips 
Each component has props which you can see here
![Breadrcrumbs](https://user-images.githubusercontent.com/6508377/189328518-cf06a0f3-9157-48c0-8a0d-74899b94e5f2.png)
![Console](https://user-images.githubusercontent.com/6508377/189328539-f30b63b6-5b45-48ae-97bb-ec78dff3b4d9.png)
![DOM events](https://user-images.githubusercontent.com/6508377/189328615-0d7e76e1-1c55-4db6-8b36-02cb59e99066.png)
![Network](https://user-images.githubusercontent.com/6508377/189328647-4548078a-a707-45ec-952d-1d032ed9ddc5.png)

**Comment by ryan953** [comment]
We're going to merge these new designs, but it's going to be a few tickets. cc @jas-kas to work together on a checklist of the changes.

**Comment by Jesse-Box** [comment]
Nice, thanks for the update @ryan953. I'll update the linked Figma file to improve 400 cases in the network case

**Comment by Jesse-Box** [comment]
@ryan953 updated figma doc, basically it functions the exact same as the console minus the flame icon.

![Image](https://user-images.githubusercontent.com/6508377/189849964-cbff6dea-f8f4-4eac-a32f-8615b85f9fba.png)

**Comment by ryan953** [comment]
I see tickets here to break out:
- New Icons
- Row background + padding + hover states for each tab
- Network tab 4xx colors
- There's a question: `console.error` messages will appear the same as Sentry Errors in the console table, is that ok?
- I think missing the purple line to distinguish between rows that are 'in the past' vs 'coming up next'. I think that's a really important usability feature.

Deeplinking into Errors from the header is covered in another ticket
Play button next to timestamps is covered in another ticket

**Comment by Jesse-Box** [comment]
@ryan953 @billyvg I've updated the designs to include the stroke for selected/current time as well as which rows are elapsed or not.

See screenshots in issue description or go to `components` page in figma to see each component state definition
https://www.figma.com/file/OPFnT04z0uy8BEUms9OU4f/Specs%3A-Details-v3?node-id=142%3A7844

**Comment by billyvg** [comment]
@ryan953 Synced up with Jesse, here are some updates:

* Ignore breadcrumbs for now
* Console: Add new filter level that shows *only* Sentry issue messages
* Console: "View Details" should be "sticky" to the right hand side
* Network: Similar treatment of console tab irt current player time. Rows that have not occurred yet should be in a lighter/gray font (see mocks). The current player time border should be red if row is red.

The below are probably not needed for ext alpha:
* DOM Events: Code font-size is a bit large, let's decrease to 12px
* Play icon appears when hovering on the row. It (icon) and timestamp should be a button whose focused state should have the purple border.

**Comment by Jesse-Box** [comment]
@billyvg @ryan953 I've revised the breadcrumbs (again) so that we can utilise the same UI pattern for showing elapsed, selected events.

See here https://www.figma.com/file/OPFnT04z0uy8BEUms9OU4f/Specs%3A-Details-v3?node-id=142%3A8712

This should cover all the interactive components in same UI

**Comment by ryan953** [comment]
@Jesse-Box is that red/purple line under the breadcrumb the currentTime indicator? I like it if 'yes'.

**Comment by Jesse-Box** [comment]
Yes

**Comment by jas-kas** [comment]
This design ticket is closed by implementation tickets [#38945](https://github.com/getsentry/sentry/issues/38945), [38946](https://github.com/getsentry/sentry/issues/38946), [38947](https://github.com/getsentry/sentry/issues/38947, [38948](https://github.com/getsentry/sentry/issues/38948) and [38949](https://github.com/getsentry/sentry/issues/38949).
