### ISSUE TITLE
Investigate if discover queries need to use the proper time ranges

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#38633]
For any Replay views that rely on Discover queries -- they may need to have the proper date range supplied, otherwise it will default to window.location (e.g. the date range selector). In the default case this will be 14 days.

This means that replays older than 14 days may cause some issues as the discover queries are looking for events only up to 14 days ago. 

If this happens, we will need to use the replay record's start/end timestamps when making the discover query.

**Comment by ryan953** [comment]
Is the problem that retention could be different between events & replays?

**Comment by ryan953** [comment]
This is 'solved' by removing the date-picked on the relevant pages.
