### ISSUE TITLE
buffer pending to be processed is too large

### ISSUE THREAD

**Issue by julyclyde** [getsentry/sentry#3870]
I don't know why I have over 100K elements in the b:p (means buffer:pending) key in each redis of a two redis nydus cluster. The process_pending scheduled task cannot process so many tasks, and this slows the overall performance of my Sentry installation.

How can I tune to improve it?

And, there might be a race condition: the TTL of lock key l: b :p is 60 seconds, if the process_pending main loop cost over 60 seconds, the lock key would varnish away, and the next process_pending task would start to execute before the former one finishes.

Sentry 7.7.4 from pip
Python 2.7.5 from CentOS SCL

**Comment by dcramer** [comment]
Get bigger servers. It sounds like you'd be better off using hosted sentry. Otherwise you're going to have to sort these problems out on your own as we don't provide free support for this kind of issue.
