### ISSUE TITLE
Emails on invites and verification are not sending

### ISSUE THREAD

**Issue by terion-name** [getsentry/sentry#3873]
Sentry 8.6.0, installed via Docker

SMTP configured to Gmail

* test email is sending ok
* when creating a new user - he gets an email with random password
* BUT email verification emails are not sending
* BUT organization invites are not sending (nor for existing, nor for non-existing user)

So I just can't add any accounts to organization/project.

I don't know where to look for detailed debug info, point please, I will attach it

**Comment by dcramer** [comment]
If I had to guess I'd say workers weren't running or configured correctly.
