### ISSUE TITLE
[jest] Test render of each individual focus area (Console / Dom / Network / Memory)

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#38850]
We need to have an [acceptance/integration](https://develop.sentry.dev/testing/#acceptance-tests) test which asserts that we can activate each of the main tabs within the Replay Details page.

Something like:
1. Load a replay
2. For each tab in the list (console, network, dom, ,errors, etc, etc, etc)
3. Click the tab
4. Assert the tab button is active
5. Assert that the content has changed

We probably don't need to worry about making sure there is data inside each tab. For example we don't need mock Console logs. It'll be enough to assert that the Console tab is active, and that we can see the message "No console rows found" on the screen.

**Comment by michellewzhang** [comment]
Relates to https://www.notion.so/sentry/INC-403-Session-Replay-UI-Broken-d9d0a00b653d45b0aede9fcbe8170ab3
