### ISSUE TITLE
[jest] unit test ReplayReader

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#38853]
- [ ] check that data is marshaled correctly
- [ ] use multiple sets of mocked input data
- [ ] look for edge cases

**Comment by ryan953** [comment]
We have a good set of tests for ReplayReader now:

https://github.com/getsentry/sentry/blob/41fc679bf0515f9f7c779e2b2d50bde8f3c3c746/static/app/utils/replays/replayReader.spec.tsx#L7
