### ISSUE TITLE
Design: Move replay video to above breadcrumbs in the Issue Details page + "Replays (Alpha)" pill

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#38923]
### Problem
As a user interested in knowing the users path to a error, I need to read a lot

### Acceptance Criteria
- User can watch the part of a replay which shows the same error found in a sentry issue 
- User can click directly to the replay details 
- User can see additional exceptions the replay captured after the error event.

#### Figma
https://www.figma.com/file/f9ywS3TPYGjgOvx4ff4dvY/Specs%3A-Replay-in-Issues?node-id=1%3A4650

#### Screenshot
![Image](https://user-images.githubusercontent.com/6508377/190655918-3893359e-1c08-46ad-8fd8-4910570bbd49.png)
![Image](https://user-images.githubusercontent.com/6508377/190655919-f30fc9e7-1943-4ae4-8fa5-bc8a08e2ec6e.png)
![Image](https://user-images.githubusercontent.com/6508377/190657139-25537a0a-78e2-40aa-8bd0-d364c89ff441.png)
![Image](https://user-images.githubusercontent.com/6508377/190657138-43a9535b-5d4e-4ae3-9da2-c692d9954d59.png)

**Comment by Jesse-Box** [comment]
@jas-kas I've updated the Issue Description to show my latest designs

**Comment by jas-kas** [comment]
Thanks @Jesse-Box ! Going to break this up into multiple smaller-sized implementation tix.

**Comment by jas-kas** [comment]
This design ticket is closed by the following implementation tickets: [#39026](https://github.com/getsentry/sentry/issues/39026) and [#39027](https://github.com/getsentry/sentry/issues/39027)
