### ISSUE TITLE
Replay Details: behaviour around console.error messages and Sentry Errors in the console table, right now they appear the same

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#38949]
**Problem:**

In ticket [38861](https://github.com/getsentry/sentry/issues/38861) we want to leverage the `Log level: Error` filter to show all Sentry errors that occurred in a replay video when a user clicks the error counter in the header.

However, there will be other console.error messages that are not Sentry errors here. So the counter that someone sees in the header may not line up with the number of errors/rows they see in the console.

**Solution:**

- Add another filter option `Log Level: Sentry Error` to deep link to only Sentry errors in Console

See design decision [here](https://github.com/getsentry/sentry/issues/38620#issuecomment-1249407450).

**Comment by jas-kas** [comment]
Hey @Jesse-Box - would love your input here on the best solution in your opinion!

**Comment by ryan953** [comment]
As part of this i'll also make sure to render the stack-trace for any errors captured by sentry.

**Comment by Jesse-Box** [comment]
> As part of this i'll also make sure to render the stack-trace for any errors captured by sentry.

How would this work in practise? I'm guessing it will be the raw stack trace right?

**Comment by ryan953** [comment]
> > As part of this i'll also make sure to render the stack-trace for any errors captured by sentry.
> 
> How would this work in practise? I'm guessing it will be the raw stack trace right?

Talked about the stacktrace offline, it's not happening as part of this, probably not at all.
