### ISSUE TITLE
Replay Details: add play button icons to Console, DOM Events, and Network on hover of row to show that the timestamp is clickable.

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#38945]
See a play button icon next to the timestamp in Console, DOM Events, and Network on hover **of row** to indicate that the timestamp is clickable. The icon and timestamp should be a button whose focused state should have the purple border.

Here's an example for the Console tab:

![Image](https://user-images.githubusercontent.com/77064737/190642460-5f79da7c-18c4-4bee-b207-cac317560ee0.png)

See more in the [Figma](https://www.figma.com/file/OPFnT04z0uy8BEUms9OU4f/Specs%3A-Details-v3?node-id=142%3A7844).

[Rewatch video.](https://sentry.rewatch.com/video/a4oif3v3v0gsbbjc-rewatch-replay-details-highlighting-ui-feedback-round-1)

This is an implementation ticket from the design ticket [#38620](https://github.com/getsentry/sentry/issues/38620#issuecomment-1248593395).

**Comment by Jesse-Box** [comment]
@jas-kas I'm closing this ticket as I've consolidated the requirements here into [#38945](https://github.com/getsentry/sentry/issues/38945)
