### ISSUE TITLE
Consistent hover states and row background for Network, Console, DOM Events tabs and Breadcrumbs

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#38948]
### Acceptance Criteria
- Breadcrumb, console, DOM and network items consistently visualise when they've elapsed, current, or pending
- Breadcrumb, console, DOM and network items consistently visualise onHover behaviour. However, breadcrumb items don't show a play icon next to their timestamp.
- Breadcrumb, console and network items consistently visualise when its an error. However, breadcrumb errors only have a background colour onHover.
- Console items have new styles to better differentiate the types of console logs.

### Designs
https://www.figma.com/file/OPFnT04z0uy8BEUms9OU4f/Specs%3A-Details-v3?node-id=604%3A17755

### Screenshots
![Image](https://user-images.githubusercontent.com/6508377/200331998-42adc007-bc99-4861-a6f1-4d4084dfa1ea.png)
![Image](https://user-images.githubusercontent.com/6508377/200331996-6120b713-9f35-4110-81db-9cbd9cd25a23.png)
![Image](https://user-images.githubusercontent.com/6508377/200331997-14348f03-921e-4eea-bb05-3c86e02dc8f1.png)

**Comment by ryan953** [comment]
FYI The replay 'Play' icon button treatment is merged and deployed: https://github.com/getsentry/sentry/pull/42216

Other design elements are getting put in, step by step though.

**Comment by ryan953** [comment]
Closed, but i'm still missing my blue icons :(
