### ISSUE TITLE
Replay Details: Network tab 400 & 500 status code has color

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#38946]
See for [Figma](https://www.figma.com/file/OPFnT04z0uy8BEUms9OU4f/Specs%3A-Details-v3?node-id=104%3A8770) for the Network component.

![Image](https://user-images.githubusercontent.com/77064737/190514803-c2f7c749-b012-498e-9d93-62367e3da1d0.png)

[Rewatch video.](https://sentry.rewatch.com/video/a4oif3v3v0gsbbjc-rewatch-replay-details-highlighting-ui-feedback-round-1)

This is an implementation ticket from the design ticket [#38620](https://github.com/getsentry/sentry/issues/38620#issuecomment-1248593395)

**Comment by ryan953** [comment]
This ticket is just to do the red background and red status column. We need those css styles merged this week.

The remaining css changes that are in the figma are covered by other tickets, and not as urgent.
