### ISSUE TITLE
Issues: Links to issues should link to the error event instead of the latest event of the issue.

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#38951]

**Comment by ryan953** [comment]
On the console tab we have the "View Details" button that does link directly to the correct instance of the error.

On the Issues tab however, the link goes to the Issue itself, not a specific error. So that is a challenge.

**Comment by billyvg** [comment]
Also reminder that we could have multiple errors that belong to the same issue.

**Comment by jas-kas** [comment]
> Also reminder that we could have multiple errors that belong to the same issue.

How should we handle this case? Do we pick the most recent error from that issue that belongs to the Replay?

**Comment by ryan953** [comment]
Landed in https://github.com/getsentry/sentry/pull/50701
