### ISSUE TITLE
Scope mismatch for creating projects

### ISSUE THREAD

**Issue by danrjohnson** [getsentry/sentry#3901]
The front end checks for `project:write` when displaying the button as active:
https://github.com/getsentry/sentry/blob/481b4b9d2365749c7b8fcf55d5aa66ee5210ab93/src/sentry/static/sentry/app/components/organizations/homeContainer.jsx#L28

The view requires the scope for `team:write`:
https://github.com/getsentry/sentry/blob/481b4b9d2365749c7b8fcf55d5aa66ee5210ab93/src/sentry/web/frontend/create_project.py#L56

It's unclear to me which of the two is actually correct, but just granting `project:write` doesn't allow a member to create new projects.

**Comment by dcramer** [comment]
Left some comments in the PR on why I think it should be project:write
