### ISSUE TITLE
Clarify user's project subscription status inside project settings

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#3922]
## The Problem

At the moment, email settings for the logged in user are managed via `/account/settings/notifications/`. Here they see a giant matrix of active subscription settings per-project:

![image](https://cloud.githubusercontent.com/assets/2153/17608945/1712a9d2-5fe5-11e6-8a14-4e15f6253c17.png)

But many users expect to be able to see and edit their current subscription settings from the _Project Notification_ settings page (`/<org>/<project>/settings/notifications`):

![image](https://cloud.githubusercontent.com/assets/2153/17608976/511213f2-5fe5-11e6-8ae7-2b791893c271.png)
## The Goal

Fundamentally, make it crystal clear what emails a user will expect to receive on the Project Notification settings (vs having it buried in their account settings).
- [ ] Show the user's current subscription (alerts + workflow) for this project on the _Project Notifications_ page
- [ ] Show the user if their email is not currently verified
- [ ] Show a handy link to the user's account notification settings
- [ ] _Nice to have:_ allow the user to edit their subscription settings (either as part of clicking "Save" for the project settings, or via AJAX or something else) – _either way, it is recommended to do this as a follow-up PR_

**Comment by dcramer** [comment]
+1 I think allow the user to edit them via the project settings is also a "nice to have"

**Comment by benvinegar** [comment]
> I think allow the user to edit them via the project settings is also a "nice to have"

Right. As a first pass it's probably fine to just show them the current status, then link them to the Account Notification settings if they want to change it.

**Comment by benvinegar** [comment]
cc @macqueen

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
