### ISSUE TITLE
Bug: Clicking into the Replays index from the sidebar does not respect the "locked" project

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#39252]
If you have a project that is "locked" in the project selector, and you click into the Replays page from the main nav bar, it will show replays for *all* projects instead of the locked project that will be selected in the project selector.

![Image](https://user-images.githubusercontent.com/79684/192033846-df92e015-2a05-4ca0-8fb5-e52fb15a3b8d.png)

**Comment by ryan953** [comment]
Repro Steps:
1. Visit the Replay Index page
2. Open the Project filter
    a. Click the checkbox to select a single project
    b. Click the button at the top to 'lock' the selection
    c. Click the button at the bottom to "Apply Filter"

Notice how the list is filtered now to only show one project. This is expected.
Notice how `?project=123` has been added to the url

3. Remove the `?project=123` from the url and click 'enter' to load that page

Notice how two requests to the `/api/0/organizations/${orgSlug}/replays/` endpoint appear in the network tab. The second request includes `project:123` and the first request does not.

Often the 2nd request (for data from a single project) returns quicker, and the 1st request is slower. The data from the 1st request is what gets rendered

![Image](https://user-images.githubusercontent.com/187460/197304914-eee4bc7c-f702-48ad-bcd2-b0bd4adfc3b5.png)
