### ISSUE TITLE
Replay Details: missing error message in Breadcrumbs and Console

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#39339]
**Problem:**

There is no error message for the second error triggered [in this replay](https://sentry.io/organizations/sentry/replays/javascript:292bb2507c99449e9722a7be633af940/?f_c_logLevel=error&referrer=%2Forganizations%2F%3AorgId%2Freplays%2F&t_main=console). However, if you click the "View Details" link in the Console for this error, you see it does exist and is named "Project ID was not set." In addition, the breadcrumb where there's an empty error message is not clickable.

Replay ID: `292bb2507c99449e9722a7be633af940`

**Solution:**

Display error message for all errors.

**Comment by ryan953** [comment]
For this one I can see that the breadcrumb object has an empty `message` field:
![Screen Shot 2022-09-29 at 2 25 41 PM](https://user-images.githubusercontent.com/187460/193145023-0e8ff89c-d9f2-429d-a398-809a44c799b4.png)

Compare that to another error that does show some text as expected (from the same replay):
![Screen Shot 2022-09-29 at 2 26 28 PM](https://user-images.githubusercontent.com/187460/193145236-76f9b9f6-231c-47b7-9bfc-572d505f1894.png)

**Comment by ryan953** [comment]
Happily the error does have a working "View Details" button, which takes us to the error. It is "Project ID was not set" and we can see in the code that it's actually coming from right here: https://github.com/getsentry/sentry/blob/67c2aa84bb4e1f88a07780c5bbeefddaafb5ef8a/static/app/views/organizationGroupDetails/groupEventDetails/groupEventDetails.tsx#L131

So we're going to have to make sure these types of `captureMessage` calls get rendered properly. When we do the fetch for the `groupId` we should be able to get the error message and merge it in here.
