### ISSUE TITLE
Replay Details: clicks happening in the Breadcrumbs list + replay video that are not captured in DOM Events list

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#39343]
**Problem:**

User clicks are missing from the DOM Events list [in this replay](https://sentry.io/organizations/sentry/replays/javascript:afd992fb239643aabc3993d456bfc765/?referrer=%2Forganizations%2F%3AorgId%2Freplays%2F&t_main=dom). Specifically, there are clicks happening in the breadcrumbs list that are not in the DOM Events list.

Replay ID: `afd992fb239643aabc3993d456bfc765`

**Solution:**

All user clicks should be seen in the DOM Events list.

**Comment by ryan953** [comment]
Confirmed: there is a click event in breadcrumbs at time=1:26 in the replay, and it's not in the DOM tab.

**Comment by ryan953** [comment]
This replay has a missing segment early in the list, it's missing the 3rd segment :(
![Screen Shot 2022-09-29 at 2 58 48 PM](https://user-images.githubusercontent.com/187460/193149625-be77e79d-a9fb-452c-bbbc-6dd1785f7ea3.png)

That's going to prevent it from having a complete list in the DOM tab, we can't playback the replay past that missing data.
