### ISSUE TITLE
sentry with rabbitmq

### ISSUE THREAD

**Issue by jinzhao1994** [getsentry/sentry#3939]
It seems that there is something wrong with `pip install librabbitmq`

I use the docker image, version 8.6, when I run python in the container, I can't import librabbitmq.

**Comment by jinzhao1994** [comment]
I've done some test.

`pip install librabbitmq==1.6.1` can run well in `python:2.7.12`.

`pip install librabbitmq==1.6.1` will not report any error in `python:2.7.12-slim`, but after pip install, I still can't `import librabbitmq`

**Comment by jinzhao1994** [comment]
I've found the reason.

I start a bash from `python:2.7.12-slim`, run `apt-get install git gcc make`, then `pip install librabbitmq==1.6.1` can run well.

In sentry:8.6 docker image, `git` and `gcc` have been installed. If you add `apt-get install make` before `pip install librabbitmq==1.6.1`, I think it will be right.

**Comment by mattrobenolt** [comment]
This is really odd. I'm impressed that the install doesn't fail without `make` and just continues along.

I'll get this patched up.

**Comment by mattrobenolt** [comment]
lol turns out `librabbitmq` just doesn't care. If `make` is missing, it just doesn't install anything: https://github.com/celery/librabbitmq/blob/master/setup.py#L176-L202

**Comment by mattrobenolt** [comment]
This should be released when this gets merged: https://github.com/docker-library/official-images/pull/2056

In the meantime, it's pretty easy to workaround if you can't wait. Just `pip uninstall librabbitmq`, then correctly install over it.

**Comment by mitsuhiko** [comment]
Great stuff.

**Comment by jinzhao1994** [comment]
Thx. You work efficiently. 👍
