### ISSUE TITLE
Improvements to weekly reports.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#3945]
- [x] Move feedback link to forum.
- [x] Don't send reports when there is no data. — GH-4122
- [x] Fix personalized impact circle outline rendering. — GH-4120, GH-4136
- [x] Include groups that were reopened during the week, but are now closed. [Right now, the query only accounts for groups that are still unresolved.](https://github.com/getsentry/sentry/blob/dc908e6fa554d3809191229f633d42d8d7daa703/src/sentry/tasks/reports.py#L200) — GH-3948
- [x] Add distribution chart for events in new, reopened, and existing issues over the week. — GH-4027
- [x] Add day of the week below bar chart column. — GH-4031
- [x] Improve mobile stylesheet.
- [ ] Improve empty state messaging.
- [ ] Add one-click unsubscribe link.
- [ ] Add frequency chart for top N releases by number of events. — GH-3974, GH-3984
- [ ] Investigate other frequency charts based on experience type.

**Comment by tkaemming** [comment]
After some feedback, the current thinking is to split these into two types different reports that are more focused in their purpose:

1. __organization reports__, which are focused on high-level aggregate metrics (time series event graph, issue breakdown into new/existing/reopened, etc — mostly what exists today, without the issue list which is more specific than necessary for this level of granularity.)
2. __project reports__, which are focused on more detailed metrics for a specific project (time series event graph, issue type breakdown, issue list, top release list, other tag top lists.)

Users can opt-out from organization reports for each organization they belong to (but not select what set of projects are used to generate the organization report) and opt-out of project reports on a per-project basis (again, these don't affect the composition of the organization report.)

In the future, it's possible we'll allow tuning the delivery frequency of these reports (e.g. daily project reports for specific projects, rather than weekly.) Most of the current implementation accounts for this, but should be kept in mind going forward.

**Comment by ckj** [comment]
> project reports, which are focused on more detailed metrics for a specific project (time series event graph, issue type breakdown, issue list, top release list, other tag top lists.)

Would be good to eventually get top releases, top tags, etc on the project dash

**Comment by tkaemming** [comment]
This is pretty much done as it pertains to organization reports, the remainder of the work here is only really relevant to project reports.
