### ISSUE TITLE
sentry with uwsgi

### ISSUE THREAD

**Issue by jinzhao1994** [getsentry/sentry#3951]
My sentry web server will print a error like this when it start. Started from docker, sentry:8.6, use `uwsgi` web option. 

```
!!! no internal routing support, rebuild with pcre support !!!
```

In fact, my sentry runs well, there are no other errors. I can successfully visit my sentry through nginx, and can't visit it directly.

There are some solutions in [stackoverflow](http://stackoverflow.com/questions/21669354/rebuild-uwsgi-with-pcre-support). It said that we should run `apt-get install libpcre3 libpcre3-dev` before `pip install uwsgi`.

I don't know what what is wrong, and what will happen. Can I just ignore this `!!! no internal routing support, rebuild with pcre support !!!` sentence?

**Comment by mattrobenolt** [comment]
Yeah, this is fine to ignore. We don't use any of those features.

**Comment by jinzhao1994** [comment]
Thanks~
