### ISSUE TITLE
Design: HMW demonstrate to users the relationship between replays and other events in the existing trace concept in Issue Details?

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#39618]
**Problem:**

Our interim solution on the Issue/Event Details page is to display a ["Replay" button](https://github.com/getsentry/sentry/pull/39512) to bring you to the Replay preview on this page. However, we want to integrate replays/sessions in the existing trace concept (e.g., trace navigator diagram).

**Solution:**

TBD on Design.

**Comment by Jesse-Box** [comment]
@jas-kas based on the specs and our conversations, I think this ticket can be close

https://www.figma.com/file/HLnI6oylSX6UTH4SHdIUQb/Specs%3A-Replays-in-Performance?node-id=92%3A3062
