### ISSUE TITLE
Design: HMW make it known immediately when a replay is available on a transaction event on the Transaction Event Details page?

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#39621]
**Problem:**

Today, replay videos do not appear on Transaction Event Details pages.

**Solution:**

We want the replay video preview to be available on this page.

We want to also extend the trace navigator to include replays.

It should be clear/obvious when a replay existed on a transaction event without scrolling.

**Comment by ryan953** [comment]
>Today, replay videos do not appear on Transaction Event Details pages.

Update: they do now!
This url pattern does show a replay preview: `/organizations/:org/performance/:projectSlug:id/`

--- 

> Solution:
1. We want the replay video preview to be available on this page.
2. We want to also extend the trace navigator to include replays.
3. It should be clear/obvious when a replay existed on a transaction event without scrolling.

Of these three solutions, 1 is done, for 2 see #39708,  for 3 see #39709
