### ISSUE TITLE
Design: On the Replay Index, introduce mini-lists/cards/previews/widgets for Most Erroneous Replays and Slowest Replays (for example)

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#39620]
**Problem:**

Today, the Replay Index page is a list of session replays sorted by most recent. This may not always be the most useful or valuable replays for our users.

**Solution:**

We want to highlight the most actionable session replays on the Replay Index. For example, most erroneous and slowest. 

Bring elements of the replay video to this. Thumbnails/previews on the video, for example. (At a glance, what page the user is on.)

More ideas:
https://github.com/getsentry/sentry/issues/36228

**Comment by jas-kas** [comment]
Alternative idea: look for "Slowest Transaction" (from the Transaction Summary > Replays tab)

**Comment by jas-kas** [comment]
- Bruno: Can we dynamically hide table for "Slowest Replays"? 
- Jesse: Create a design for state where a customer has Errors only. 
- How can we define "Most Erroneous"?
- Ryan: errors per page view? 
- Jesse: How can we harness existing touchpoint flows we have for Session Replay for this?
- Jasmin: "Most Erroneous" could be a user that encountered the most errors in aggregate and show their replays
-Ryan: What makes a good visual element/replay preview for this page?

**Comment by ryan953** [comment]
In progress figma:
https://www.figma.com/file/9KcBRp3IniYCtCuAwuu3e2/Specs%3A-Index-Widget?node-id=0%3A1&t=usm4uQUOUSY0cOS0-0

**Comment by bruno-garcia** [comment]
I created an epic to track this deliverable: #45701

> In progress figma:
https://www.figma.com/file/9KcBRp3IniYCtCuAwuu3e2/Specs%3A-Index-Widget?node-id=0%3A1&t=usm4uQUOUSY0cOS0-0

Are we good with the design? If so can we close this issue?

**Comment by Jesse-Box** [comment]
@bruno-garcia 

Designs are done
Can be found [here](https://www.figma.com/file/9KcBRp3IniYCtCuAwuu3e2/Specs%3A-Index-Widget?node-id=79%3A3907&t=8GYedopkwuV1r2QB-1) (Page: Specs)
