### ISSUE TITLE
Design/Discussion: For performance views - HMW make it easy for users to find replays with slow transactions?

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#39622]
**Potential Solutions:**

- Add a replay column in Discover that links to the specific Replay Details
- Add a replay column in the Events tab in Issue Details (by default)
- Add a replay column in the All Events page under Transaction Summary

- Add filter option on Transaction Summary homepage "Filter: Transactions with Replays" (sorted by slowest)
- Deep link from Transaction Event Details (Web Vital cards on the right-side) to Replay Details timestamp

**Comment by ryan953** [comment]
> Add a replay column in Discover that links to the specific Replay Details

See #39713

> Add a replay column in the Events tab in Issue Details (by default)

See #???

> Add a replay column in the All Events page under Transaction Summary

See #???

> Add filter option on Transaction Summary homepage "Filter: Transactions with Replays" (sorted by slowest)

See #???

> Deep link from Transaction Event Details (Web Vital cards on the right-side) to Replay Details timestamp

See #???

**Comment by ryan953** [comment]
All the ideas in this are transferred into separate tickets, closing.
