### ISSUE TITLE
How to disable organization creation by regular user?

### ISSUE THREAD

**Issue by DenisBY** [getsentry/sentry#3966]
I have the following in my config:
```
SENTRY_FEATURES['organizations:sso'] = False
SENTRY_FEATURES['auth:register'] = False
SENTRY_SINGLE_ORGANIZATION = False

AUTHENTICATION_BACKENDS = (
    'sentry.utils.auth.EmailAuthBackend',
    'sentry_ldap_auth.backend.SentryLdapBackend',
)

AUTH_LDAP_SENTRY_ORGANIZATION_ROLE_TYPE = 'member'
AUTH_LDAP_SENTRY_ORGANIZATION_GLOBAL_ACCESS = False
AUTH_LDAP_DEFAULT_SENTRY_ORGANIZATION = u'Sentry'
```

And all new users logged in via LDAP are able to create a new organization in addition to 'Sentry'
How to disable this behaviour? How to limit organization creation only by admins?
I can globally disable this feature by `SENTRY_FEATURES['organizations:create'] = False` but I need to switch it each time I need to create a new organization.

**Comment by dcramer** [comment]
You cannot -- multi-organizations are not intended to be used for on-premise installs, and entirely exist to serve getsentry.com. The 'organizations:create' feature is a legacy feature, and its unlikely we're going to expand on it.
