### ISSUE TITLE
OS details in "context interfaces" don't show up in UI correctly

### ISSUE THREAD

**Issue by jakubzitny** [getsentry/sentry#3968]
Hi, latest update to Sentry UI brought nice feature for showing Operating System or Browser data.

![screen shot 2016-08-17 at 18 44 59](https://cloud.githubusercontent.com/assets/3315662/17745565/9259c26c-64ac-11e6-8767-3858c34b811a.png)

However, when I am trying to send all the data we want to track for Operating System it doesn't show up in the new UI. For Linux systems I want to have the distro version (e.g. Ubuntu 14.04) and the kernel version (4.4.0) instead of Unknown. I've tried to add these into `contexts` as `os.version` and `os.kernel_version` as documented in [Interfaces docs](https://docs.getsentry.com/on-premise/clientdev/interfaces/#context-types). I've tried to add that via [Raven.context](https://docs.getsentry.com/hosted/clients/javascript/usage/#raven-js-additional-context) as `os` as well.

The UI seems to be aware of that as it is showing the info in right sidebar `tags` as `os.version` and `os.kernel_version`. If I add it incorrectly inside `contexts` or directly as `os` (without `contexts`) it shows error `Discarded invalid parameter 'os'`:

![screen shot 2016-08-17 at 19 03 07](https://cloud.githubusercontent.com/assets/3315662/17745728/4774f388-64ad-11e6-88eb-9eb2f321e7c1.png)

However, in the header there is still "Linux version Unknown" and in Operating System section it is `undefined` and `n/a`:

![screen shot 2016-08-17 at 19 04 08](https://cloud.githubusercontent.com/assets/3315662/17745774/7503eb74-64ad-11e6-9898-deb875ad79b2.png)

I wonder if this is problem on my side or you have a bug in Sentry.

We're using On-Premise Sentry and newest `raven-js 3.5.0`.

Thanks and sorry for "shortcuts-mistyped" #3967.

**Comment by dcramer** [comment]
Can you show the value you're passing for the OS context?

**Comment by jakubzitny** [comment]
@dcramer something like this:
```js
Raven.captureException(error, {
  'tags': tags,
  'extra': extra,
  'contexts': {
    'os': {
      'version': linuxDistro.os + " " + linuxDistro.release, // becomes "Ubuntu 14.04"
      'kernel_version': os.release() // "4.4.0-31-generic"
    }
  }
})
```

**Comment by dcramer** [comment]
so you would need the os 'version' to just be the release, and the os name to be the distro

its also possible we'll throw this away right now if you send it via the JS client, but thats a separate issue (and im not sure its true)

let me know if that works, and if so we'll close this out

**Comment by jakubzitny** [comment]
@dcramer I tried it but it's still the same:

![screen shot 2016-08-17 at 23 27 02](https://cloud.githubusercontent.com/assets/3315662/17753880/28dd2362-64d2-11e6-95e1-91af97d6b5de.png)


If you're doing some kind of filtering or pattern matching or number checking in os version or/and name there might be a problem with Linux. You have `os.name` (automatically detected by Raven) set to "Linux", which is true - it is Linux. It's just not the distribution name. I'd be happy to put it into the version (together with release number) because it is showing in the header and it's pretty important info. It would be cool to let us (devs) do it from Raven. We're tracking the Linux distro names and versions and also kernel versions anyway so why not use it in this cool new UI?

Besides, the `undefined` and `n/a` is pretty useless over there and if there is no way to set it correctly..

I would say this is exactly the issue that you're throwing it away so I'd leave this open until it's sorted out. What do you think?

**Comment by dcramer** [comment]
I also forget what our "desired format" is for things like OS name. It's definitely something we need to document, but right now this feature is sort of hidden and in the early stages.

Will look into the possibility that we're overwriting things on the server.

**Comment by jakubzitny** [comment]
It might be the problem only in the "Operating System" section. The values are showing up in the right panel:

![screen shot 2016-08-17 at 23 34 59](https://cloud.githubusercontent.com/assets/3315662/17754138/72e816aa-64d3-11e6-8359-a65c1bc12fb3.png)

I can have a look at the code if you direct me to wherever the ui template / component for the issue page is.

**Comment by dcramer** [comment]
The root of it its contexts.jsx (in our interface components), and on the backend its contexts.py.

**Comment by jakubzitny** [comment]
Hey guys, I didn't really have time to check this. Has there been any progress on your side regarding this issue?

**Comment by dcramer** [comment]
@jakubzitny no updates on our end yet -- we haven't prioritized this since its not yet really documented.

**Comment by priscilawebdev** [comment]
@jakubzitny thanks for reporting this.

So I just checked the UI and I can confirm that:

in the context summary (header) we display `Unknown` if `version` or `kernel_version` are `undefined`.

in the Operating System section we no longer display `Version` and `Kernel Version` if case of  `undefined`.

You mentioned that the right sidebar displays the information as expected, but I noticed that the information displayed in the right sidebar comes from the request `/issues/${groupId}/ ` (groupDetails.jsx) and the information displayed in the issue content comes from a different one 'issues/${groupIdv}/events/latest/' (groupEventDetails.tsx)

I don't know the reason behind this, but I believe that this problem can be fixed on the backend. @rhcarvalho, could you please take a look at this?

**Comment by rhcarvalho** [comment]
@jakubzitny do you have any recent event to demonstrate how to reproduce this? In the meantime, did you migrate to a newer version of the JavaScript SDK?

Cheers!

**Comment by jakubzitny** [comment]
Hi there, we're using `raven-js": "^3.22.1` and now it seems that the "Operating System" section works. The header icon, however, is showing only "Unknown OS".

<img width="481" alt="Screenshot 2020-04-14 at 17 28 15" src="https://user-images.githubusercontent.com/3315662/79243053-6b9dd280-7e75-11ea-9882-e069df241a32.png">
<img width="785" alt="Screenshot 2020-04-14 at 17 28 46" src="https://user-images.githubusercontent.com/3315662/79243057-6cceff80-7e75-11ea-95ad-009d7eb657b5.png">


Let me try to upgrade the client to see how things work in latest version. I'll try to get back to you next week 😉

**Comment by rhcarvalho** [comment]
@jakubzitny cool. Are you using Sentry.io or on-prem?

**Comment by jakubzitny** [comment]
On-prem, v9.1.2 right now.
