### ISSUE TITLE
Extend the Trace navigator widget to include Replays

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#39708]
## Task
We want to design some version of the Trace Navigator widget that lets us show Replays as being a super-set of the existing traces. 

## Acceptance Criteria
- Replays must show in the trace navigator when their associated with a error or transaction event 
- Replays must appear in both the Issue details and Event details (See Touchpoints).
- Replays must adhere to the cases outlined in "Test Cases"
- The Replay button in issue details, next to the event pagination is removed

## Touchpoints
| Page | Screenshot |
| --- | --- |
| Issue Details | ![Screen Shot 2022-10-05 at 3 03 36 PM](https://user-images.githubusercontent.com/187460/194172501-da679518-2828-46bc-9e42-4ade4952af38.png) |
| Transaction Summary > Event Details | ![Screen Shot 2022-10-05 at 3 03 26 PM](https://user-images.githubusercontent.com/187460/194172504-f46aebde-ea50-4162-9243-3933e7abbdf9.png) |

## Test cases
Whilst we're **not changing any existing behaviour** of the trace navigator, I've documented below how this component behaves under different situations. I've highlighted certain performance cases(!!!) which Replay depend on being true to render

### Performance
- (!!!) `IF` the SDK Version is sufficient for distributed tracing
	- `IF` distributed tracing is setup on all relevant projects
		- `IF` there's a full trace associated with this event
			- `THEN` [display](https://www.figma.com/file/HLnI6oylSX6UTH4SHdIUQb/Specs%3A-Replays-in-Performance?node-id=144%3A5176)
			- <img width="833" alt="Screen Shot 2022-10-28 at 10 18 38 AM" src="https://user-images.githubusercontent.com/187460/198695416-0acc0693-abe9-4702-9338-570d8d42b23e.png">
		- `ELSE IF` the trace was dropped due to sampling, rate limiting etc.
			- `THEN` [display](https://www.figma.com/file/HLnI6oylSX6UTH4SHdIUQb/Specs%3A-Replays-in-Performance?node-id=144%3A5015)
			- <img width="828" alt="Screen Shot 2022-10-28 at 10 19 05 AM" src="https://user-images.githubusercontent.com/187460/198695506-edc67052-374b-4979-ae9e-17feff0a1348.png">
		- `ELSE IF` the corresponding transaction for this event was dropped due to sampling, rate limiting
			- `THEN` [display](https://www.figma.com/file/HLnI6oylSX6UTH4SHdIUQb/Specs%3A-Replays-in-Performance?node-id=144%3A5046)
			- <img width="838" alt="Screen Shot 2022-10-28 at 10 19 28 AM" src="https://user-images.githubusercontent.com/187460/198695575-9fad5032-8546-4351-bc46-8148da9eb728.png">
	- `ELSE IF` distributed tracing is setup on this project only
		- `THEN` [display](https://www.figma.com/file/HLnI6oylSX6UTH4SHdIUQb/Specs%3A-Replays-in-Performance?node-id=144%3A5224)
		- <img width="834" alt="Screen Shot 2022-10-28 at 10 19 51 AM" src="https://user-images.githubusercontent.com/187460/198695642-115b20bd-b93b-4f4b-a57d-a7ca4b669e2a.png">
	- `ELSE` [display](https://www.figma.com/file/HLnI6oylSX6UTH4SHdIUQb/Specs%3A-Replays-in-Performance?node-id=144%3A4966)
	- <img width="825" alt="Screen Shot 2022-10-28 at 10 20 12 AM" src="https://user-images.githubusercontent.com/187460/198695720-87689296-1928-437b-94f1-8248a1be1d19.png">
- `ELSE` [display](https://www.figma.com/file/HLnI6oylSX6UTH4SHdIUQb/Specs%3A-Replays-in-Performance?node-id=144%3A4361)
- <img width="829" alt="Screen Shot 2022-10-28 at 10 20 36 AM" src="https://user-images.githubusercontent.com/187460/198695775-237228ef-8a66-48b8-96d8-74da008e6250.png">

### Replay
- `IF` replay is setup on selected project
	- `IF` there's a Replay associated with this event 
		- `THEN` [display](https://www.figma.com/file/HLnI6oylSX6UTH4SHdIUQb/Specs%3A-Replays-in-Performance?node-id=144%3A4585)
		- <img width="848" alt="Screen Shot 2022-10-28 at 10 21 44 AM" src="https://user-images.githubusercontent.com/187460/198695965-144aa8a1-fd86-4243-805b-69d520ede628.png">
	- `ELSE` [display](https://www.figma.com/file/HLnI6oylSX6UTH4SHdIUQb/Specs%3A-Replays-in-Performance?node-id=144%3A4682)
	- <img width="787" alt="Screen Shot 2022-10-28 at 10 22 09 AM" src="https://user-images.githubusercontent.com/187460/198696043-f4abe588-549d-4fe4-b43c-0e3bc3c49596.png">
- `ELSE` [display](https://www.figma.com/file/HLnI6oylSX6UTH4SHdIUQb/Specs%3A-Replays-in-Performance?node-id=166%3A3634)
- <img width="832" alt="Screen Shot 2022-10-28 at 10 22 50 AM" src="https://user-images.githubusercontent.com/187460/198696153-b624eae0-5651-40ee-88fe-391eb63fcb2c.png">

**Comment by Jesse-Box** [comment]
@ryan953 @jas-kas I've updated this ticket so its ready for development

**Comment by ryan953** [comment]
Should we have a 'configure session replay [read docs] [snooze] [dismiss]' box that appears (only if the feature is enabled)?

Also, I'll assume now that session replay has the same SDK Version requirements as tracing, so that condition guards everything

**Comment by Jesse-Box** [comment]
> Should we have a 'configure session replay [read docs] [snooze] [dismiss]' box that appears (only if the feature is enabled)?

We can do it, but I dont think we need it for this round of work.

The issue details has this problem where its almost become a space for advertising auxiliary sentry services, and I want the design team to figure out a more robust solution to this.
