### ISSUE TITLE
Issue Details > All Events should link to Replay Details

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#39734]
Currently the Issue Details > All Events page displays a (weird looking, side scrolling) table of events that are included in this isuse.

The `replayId` column should link to the Replay Details page following the same rules as #39713

- [ ] can be a truncated replayId
     - instead of showing the full `0ffabc111f064effb92d33ee3b6ab250` we just need `0ffabc11`. 
     - This aligns with existing examples throughout the app.
- [ ] link to the replay details page
    - link includes `?referrer`
- [ ] It should have the 'replay play icon' as a prefix, (see inspiration screen shot below)
- [ ] If possible & performant: deep link into the timestamp when the transaction happened. 
    - If it's not possible or performant, then make a followup ticket and link it here

Existing page/table:
![Screen Shot 2022-10-05 at 4 52 28 PM](https://user-images.githubusercontent.com/187460/194184426-5db97e94-e2d1-4d83-9f0d-07129e418e55.png)

**Comment by Jesse-Box** [comment]
@ryan953 @danecando just want to point out that there's a new version of this table which i think hasn't rolled out to the public, but is visible for all sentry org members.
