### ISSUE TITLE
Bug: Performance > Transaction Summary header should not wrap when many tabs are visible

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#39735]
This shouldn't wrap the "Replays" tab to a 2nd row:

![Image](https://user-images.githubusercontent.com/187460/194184631-adc1d1d7-d9d2-4bba-80d2-f710b55f47c2.png)

**Comment by jesus4497** [comment]
> I think this has been resolved recently @ryan953

Yup! This was fixed by #38886 
![image](https://user-images.githubusercontent.com/39612839/200897590-e92a75d2-5ce6-4b19-a1a0-a6e9f4da59b2.png)

**Comment by ryan953** [comment]
Can we improve it though? your screen shot cuts off the rigth side of the header... looking at the entire header it's a little weird to me that the "show more" button is in the middle of the screen:

<img width="1004" alt="Screen Shot 2022-11-09 at 1 30 52 PM" src="https://user-images.githubusercontent.com/187460/200945994-8a1ad977-ab2a-4d44-8edc-d3eea9f4b647.png">
