### ISSUE TITLE
Issues List page should suggest searches for 'Issues With Replays'

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#39733]
On the Issues List page there is a "Saved Searches" dropdown which has a list of suggested searches.

Existing Suggestions:
<img width="347" alt="Screen Shot 2022-10-26 at 1 33 48 PM" src="https://user-images.githubusercontent.com/187460/198132331-74b72193-98dd-4077-96fd-179684580cff.png">

When the replay ui feature is enabled we should add a suggestion for "Issues With Replays". I think a search query that includes `!replayId:""` would work but potentially `has:replayId` would also work. We'd need to check on that.

**Comment by Jesse-Box** [comment]
I think we'll get a lot of push back on this because these suggestions heavily relate to a specific workflow which we want users to adopt in the end.

**Comment by ryan953** [comment]
cc @jas-kas & @Dhrumil-Sentry for your input

**Comment by ryan953** [comment]
Closing this. Feedback is that it's not discoverable, no one will find and click this thing. It's good enough that we have auto-complete in the search box to guide people.
