### ISSUE TITLE
False blocked URL report

### ISSUE THREAD

**Issue by mrtronje** [getsentry/sentry#39743]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

We receive CSP reports in sentry that are false. We get the message that 	
script-src-elem https://cdn.cookielaw.org is blocked although the report (see screenshot) shows that this is allowed. Is this a bug?
![image](https://user-images.githubusercontent.com/15194959/194055845-ba83d7af-ed00-4efa-a2aa-2b22599d14f4.png)

### Expected Result

No CSP report for script-src-elem https://cdn.cookielaw.org

### Actual Result

CSP report for script-src-elem https://cdn.cookielaw.org

**Comment by iker-barriocanal** [comment]
Hi @mrtronje, what version of self-hosted and relay are you running? It'd also be helpful if you could clarify the following:

> We get the message that script-src-elem https://cdn.cookielaw.org/ is blocked

What message do you get confirming that? Is the message here the CSP report?
Could you post a screenshot of how you're blocking that source for CSP reports? 

> We receive CSP reports in sentry that are false.

What does this mean specifically? Is this issue only about getting CSP reports from blocked/unblocked sources, or also about getting CSP reports that you didn't expect to receive?

**Comment by mrtronje** [comment]
Hi @iker-barriocanal 

Oh I see it wasn't precious enough. 

> what version of self-hosted and relay are you running?

Sentry 22.9.0, e40aded; Relay: 22.8

> What message do you get confirming that? Is the message here the CSP report?
Could you post a screenshot of how you're blocking that source for CSP reports?

The "message" is the CSP Report that I see in sentry. In the browser console and network tab I don't get an CSP error.  We don't block that resource (cookielaw) it's the opposite, we enable that resource (see "original policy" in the screenshot of the intial post where cookielaw is "enabled" ). 

> What does this mean specifically? Is this issue only about getting CSP reports from blocked/unblocked sources, or also about getting CSP reports that you didn't expect to receive?

It means that we see this entry in sentry: 
![image](https://user-images.githubusercontent.com/15194959/194552008-9847115a-b694-4c89-a28c-5e643afe6f1f.png)
although we enable this resource in our CSP Headers. So we shouldn't see this entry in sentry because the resource isnt't actually blocked.

**Comment by iker-barriocanal** [comment]
I'm not sure I understand your issue correctly, so I'll rephrase your issue with my words and you correct me if I'm wrong. You see on Sentry a CSP report claiming a script from `cookielaw` was blocked, but you don't see any errors on the browser console and network tab and you expect that CSP report to not be on Sentry. Is this correct?

If the above is correct, could you copy-paste the `original_policy` field (or the `Content-Security-Policy-Report-Only` header) for better readability? And, have you verified the syntax of the header's value is correct (see [Content-Security-Policy-Report-Only docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only))?
