### ISSUE TITLE
[React Native] Source code was not found for

### ISSUE THREAD

**Issue by Kerumen** [getsentry/sentry#3976]
I have a bunch of errors like this on Sentry with RN 0.31:

```
Source code was not found for /Users/<user>/<path>/node_modules/react/lib/ReactNativeEventEmitter.js
``` 

With a lot of files.
It's because in the sourcemaps there is this part:

```
"sources":["/Users/<user>/<path>/node_modules/react/lib/ReactNativeEventEmitter.js"]
```

Should I have to upload all the source code as artifacts? It means all my code and all the node_modules sources. That's the wrong way to solve I think.

**Comment by dcramer** [comment]
If the source is in the uploaded sourcemap you don't need to do anything. If it's not, then you need to upload the source as well. RN keeps changing, but last I knew there was a bundle.js and a sourcemap for that bundle, and thus you'd need to upload both.

**Comment by Kerumen** [comment]
I uploaded both the jsbundle and the sourcemaps. 
Is it viable to upload all my source code and my node_modules source code?

**Comment by dcramer** [comment]
If it's not part of the jsbundle (I thought it was) then ya the only solution is to upload the remainder.

**Comment by Kerumen** [comment]
I'll check.
But maybe it's in the bundle but not well parsed because it's the indexed sourcemaps format and sentry handled them recently (https://github.com/getsentry/sentry/issues/3224).

**Comment by ajwhite** [comment]
@Kerumen did you end up figuring this out? Is there any guidance for this issue @dcramer?

> then ya the only solution is to upload the remainder.

Unclear what this is proposing; I noticed `raven-js` has a React Native plugin; does Sentry not support the crash logs that it reports?

**Comment by Kerumen** [comment]
@ajwhite No, so I ended up by switching to Bugsnag which works very well. I didn't have to configure something, everything was good out of the box.

**Comment by ajwhite** [comment]
Thanks @Kerumen, I'll check that out if I can't get this working. 

Hoping @dcramer might have some advice before looking at alternatives

**Comment by dcramer** [comment]
We have some plugins and similar that will work with this but we're going to be launching some cross language support for react native here pretty soon.
