### ISSUE TITLE
Test email doesn't use workers to send

### ISSUE THREAD

**Issue by thorerik** [getsentry/sentry#3990]
When working on an issue on our self-hosted sentry instance, we had only configured the core instance with email, workers didn't get this configuration.

When testing email sending from the admin panel, all seems good, email gets delivered just fine, but when trying to verify email or send invites to users no email gets sent, but workers log as if email was sent:

```
05:37:04 [INFO] sentry.mail: mail.sent (message_id='<20160822053703.19.51343@ourdomain.com>')
```

though on our mail host, no send attempt was logged, as a stab in the dark I set up a third worker with email configured, lo and behold that worked.

I think the test email button in the admin panel should use the workers to send, that way it's a little more clear if there is an issue with the setup.

**Comment by fredvd** [comment]
I just bumped into this as well. I'm trying to debug a situation where the worker suddenly is no longer able to send e-mail (will create a separate issue for that if there's not a report already), but found the 'test' e-mail settings button in the user interface. 

I was surprised that nothing got logged on the sentryworker stdout but the e-mail still arrived.  I have restarted the sentryworker and e-mail works again, but it would be helpful if the testing e-mail tests the 'normal' route of e-mail sending.

**Comment by pokemane** [comment]
#3842 

Seems to be the opinion of the team that it's operator error and isn't worth mentioning in the documentation, and that if you can't grasp "simple operations" you should pay them money instead.

**Comment by dcramer** [comment]
We have an internal policy to not say "PRs accepted", but Sentry is entirely built by the company at this point, and our focus is on our SaaS service. Opening tickets, while sometimes helpful, isn't going to really push these things in the right direction. If people want to help improve docs we'll absolutely accept pull requests there, but that's the right kind of solution (vs a variety of scattered tickets that email blast everyone participating in the project).

**Comment by chadwhitacre** [comment]
Ancient ticket, closing.
