### ISSUE TITLE
Rules: An event changes state from resolved to unresolved

### ISSUE THREAD

**Issue by hustcc** [getsentry/sentry#3991]
I add a rule, when `An event changes state from resolved to unresolved`, then to `webhook`.

![image](https://cloud.githubusercontent.com/assets/7856674/17854393/d6fbfd44-68a4-11e6-99a2-d1d27fd8ebc2.png)

But I `can not receive any HTTP request` in the webhook url, after reading the code, I found below:

```py
class RegressionEventCondition(EventCondition):
    label = 'An event changes state from resolved to unresolved'

    def passes(self, event, state):
        return state.is_regression
```

What is the meaning of `state.is_regression` ?

**Comment by mattrobenolt** [comment]
`is_regression` means literally that. An event was once resolved, but it has flipped state back to unresolved.
