### ISSUE TITLE
Uncaught SyntaxError: Unexpected token } when trying to remove a tag.

### ISSUE THREAD

**Issue by viciu** [getsentry/sentry#3992]
version of sentry: 8.7.0

![scrn565](https://cloud.githubusercontent.com/assets/56233/17855288/3fb63d18-6878-11e6-8687-2d67e789eee0.png)

**Comment by mattrobenolt** [comment]
This has been fixed on master a while ago. Lemme dig up the commit.

**Comment by mattrobenolt** [comment]
https://github.com/getsentry/sentry/pull/3908
