### ISSUE TITLE
Group merging fails sometimes

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#3997]
See https://sentry.zendesk.com/agent/tickets/4300 for more context.

```
error(1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`sentry`.`sentry_grouprulestatus`, CONSTRAINT `group_id_refs_id_66981850` FOREIGN KEY (`group_id`) REFERENCES `sentry_groupedmessage` (`id`))')
```

In theory, should be relatively easy to reproduce and put together a test case.

**Comment by mattrobenolt** [comment]
Turns out, this is happening for ourselves as well, and can be seen here: https://app.getsentry.com/sentry/sentry/issues/115299711/

**Comment by bsergean** [comment]
Hallo, we are still running into this bug, and sometimes our tags don't show up for some crash group. I wonder if the 2 are correlated.

We run sentry 8.14 at this point, but we've seen this happen with all release since ... 8.something ?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
