### ISSUE TITLE
GitHub Enterprise Integration Problem - can only configure one App

### ISSUE THREAD

**Issue by AndrewMoyse** [getsentry/sentry#39980]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

21.8.0

### Steps to Reproduce

1. Create GitHub App at the Org level
2. Enter github-app config details for the App in config.yaml
3. Create another GitHub app for another GitHub Org
4. Adding App details to config.yaml means replacing the previous apps details..

### Expected Result

I expect to be able to wire up multiple GitHub Apps that are installed in multiple Orgs. How do I do that?

### Actual Result

One GitHub app is added, but we need multiple.

**Comment by armenzg** [comment]
@AndrewMoyse You only set-up one Github App but you get to install it in more than one Github org.

Does that help?
