### ISSUE TITLE
getCurlCommand assumes json data

### ISSUE THREAD

**Issue by davidszotten** [getsentry/sentry#4000]
or at least seems to do the wrong thing with form encoded data

**Comment by MaxBittker** [comment]
hi @davidszotten  - would you mind pasting the offending curl command? trying to recreate this

**Comment by davidszotten** [comment]
iirc it was from a mailgun webhook. only have the version that shows up in the ui, but will try to re-create

**Comment by davidszotten** [comment]
ok, so i think i completely misdiagnosed this. still not found an exact example but i think the issue is  the quote escaping, in particular if the string contains already escaped quotes

**Comment by MaxBittker** [comment]
thank you, I agree that this problem sounds more likely

**Comment by MaxBittker** [comment]
@davidszotten does the version that shoes up in the UI contain double-escaped strings like 
`\\\\" `
?

**Comment by davidszotten** [comment]
yes, or well, shows up like two, not 4:

`...   [\\"X-Mailgun-Sid\\", \\"foo=\\"], ...`

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
