### ISSUE TITLE
Feature Request: Columns/Extra in "Related Events"

### ISSUE THREAD

**Issue by mneuhaus** [getsentry/sentry#4007]
Hey!

i was wandering if it was possible to add the possibility to add extra columns in the "related events" tab.
Usecase: I'm watching a Sync on a remote Server. i'm capturing when/how many files are synced.
the Message of the log is always the same, but i'm sending the count in extra. i know i can open
every single event and look at that, but what would be cool is, if you could add columns in the
list view. i'd be willing to provide a Patch if you'd be interested to accept a pull-request for that.
what do you think?

Cheers
Marc

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
