### ISSUE TITLE
Members list for non-admin users is misaligned

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#4030]
Logged in as "Billing"-level user:

![image](https://cloud.githubusercontent.com/assets/2153/18071082/a336d688-6e07-11e6-95fc-a6ff60e3aae2.png)

Logged in as admin:

![image](https://cloud.githubusercontent.com/assets/2153/18071136/f3de6a4c-6e07-11e6-9e8a-4884a18d26c2.png)

Note this is not a browser width/reflow issue: the alignment issues persist at pretty much every breakpoint.

cc @getsentry/ui

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
