### ISSUE TITLE
Provide onboarding instructions/flow in the empty state of the Replay Index page

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#40329]
**Problem:**

Today our empty state on Replay Details before a customer has started sending replays for a given project does not communicate how to get started with Session Replay/onboarding flow. 

**Solution:**

We want to demonstrate to any user in an organization how to start sending replays and see their data reflect in the Replay Index view in the in-app experience.

_TBD._

**Comment by ryan953** [comment]
I think this is covered by the designs in https://www.figma.com/file/MnKsgpxDrfEphCKLKuOetG/Specs%3A-Onboarding-v1?node-id=330%3A3539

Implementation ticket is: https://github.com/getsentry/sentry/issues/40787
