### ISSUE TITLE
Sort transactions by 'hasReplay' then by timestamp on the Transaction Summary page

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#40339]
This is a replacement for #39722

The idea is to sort all of these event tables by two parameters; has replay and by whatever else is selected (timestamp by default).

The result should be that all the most recent events with replays will float to the top of table. 

Example:
 
<img width="921" alt="197018892-50963b52-3caa-4295-8060-71d68169aae1" src="https://user-images.githubusercontent.com/187460/197021481-aa602318-418c-475c-88a2-3fd44c68cdaa.png">

We **do not** have to make the column headers sortable in this ticket. Really, people should just be clicking on the "View All Events" button to get features like that.

**Comment by ryan953** [comment]
We've identified some issues with this ticket, mainly:

1. If we only sort on the front-end then it's kind of useless. a) there might not be a transaction with a replayId at all, because there are only 5 rows shown. b) only 5 rows, users can pick out the row with a 'View Replay' button easily.

2. If we edit the queries then things breakdown
For example, right now we’ve got "Filter: Recent transactions":
```
WHERE tnx_name = '/issues'
SORT BY timestamp
LIMIT 5;
```
and "Filter: Slowest transactions"
```
WHERE tnx_name = '/issues'
SORT BY duration
LIMIT 5;
```
if we mix in the replay columns:
```
WHERE tnx_name = '/issues'
SORT BY hasReplay, timestamp
LIMIT 5
```
then you’ll get everything that has a replay first, and of those we’ll sort by timestamp so you could see dates like:
```
Oct 25 | View Replay
Oct 1. | View Replay
Oct 25 | -
Oct 25 | -
Oct 25 | -
```

if we added a checkbox "[x] Only txns with replays" then the query would be like:
```
WHERE tnx_name = '/issues' AND hasReplay
SORT BY timestamp
LIMIT 5
```
and results could be:
```
Oct 25 | View Replay
Oct 1. | View Replay
Sept 28 | View Replay
```
But a checkbox is a bad UI pattern and we're not going to do that.

We could add a new filter option (as in #39722) "Filter: With Replays". But the transactions found might not be actionable. One benefit of this approach is that users clicking on the "View All Events" button would get a pre-filled searchbox to further sort/filter. meh.

**Comment by Jesse-Box** [comment]
Having some time to think about this, I don't see an obvious way of solving this issue.

I don't want to clutter this specific organism with a `has:replay` checkbox because this pattern doesn't scale to more services which want to make the same connection to transactions — think profiling.

Maybe its enough for now, that people see there's new replay column, which they can act on by going to the All events tab?

**Comment by ryan953** [comment]
> I don't want to clutter this specific organism with a has:replay checkbox
> Maybe its enough for now, that people see there's new replay column, which they can act on by going to the All events tab?

I agree with all of that. Lets close this issue for now as it's been well explored and we've got other touchpoints to rely on. We don't need to force this.
