### ISSUE TITLE
Project dropdown should indicate when no projects available

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#4033]
If you've just joined an organization and are not assigned to any teams, you see the following:

![image](https://cloud.githubusercontent.com/assets/2153/18072534/f37c35c8-6e13-11e6-8a98-b0e5b876fa9d.png)

---

This should probably repeat the message from the team page when you are in this state:

> You are not a member of any teams. Join an existing team or create a new one.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
