### ISSUE TITLE
embedding image in html email

### ISSUE THREAD

**Issue by AyumuKasuga** [getsentry/sentry#4038]
Hello!
In current implementation images are not attached to email, img tag points to [sentry server ](https://github.com/getsentry/sentry/blob/master/src/sentry/templates/sentry/emails/base.html#L20) (and [background image](https://github.com/getsentry/sentry/blob/master/src/sentry/templates/sentry/emails/email-styles.html#L5))

But in situations when sentry installed in corporate network (not accessible without VPN) our emails looks like this:

![image](https://cloud.githubusercontent.com/assets/700142/18087415/d0b3f77e-6ebd-11e6-8591-216f87b6f1c7.png)

Is it possible to attach images to email or at least add option to load images from CDN?

**Comment by mattrobenolt** [comment]
Ideally, I think we'd just base64 encode and inline the media. I've personally had this concern, it's just been low priority to address. Not sure if there's an easy way we can just automatically do this.

@tkaemming

**Comment by mattrobenolt** [comment]
Now that I'm looking at it, it should be pretty trivial to write a template tag that just takes the media path and spits back a data uri.
