### ISSUE TITLE
Replay Details: add informative empty state message for Memory tab when browser =/= Chrome

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#40407]
**Problem:**

Today the memory stats tab is only supported for Chrome browsers. We should communicate to users why it is empty when they are viewing a replay not from Chrome.

![Image](https://user-images.githubusercontent.com/77064737/197262272-26367ce1-971f-4c7b-8941-5a5b10a19a60.png)

**Solution:**

Change copy in message. "No memory metrics found" --> "No memory metrics found. Memory metrics are only applicable to Chrome browser sessions."

**Comment by ryan953** [comment]
What about "Memory metrics are only captured within Chromium based browser sessions."

**Comment by jas-kas** [comment]
@ryan953 sounds good to me!
