### ISSUE TITLE
Replay Index: Read the new 'activity' column provided by the backend instead of calculating it on the frontend.

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#40419]
We want to sort by "Activity" on the Replay Index page upon clicking the column header. This is so users can see the replays with the most activity at the top of the list. It should also sort by the parameter "Start time" to sort replays that have the same activity level.

Depends on https://github.com/getsentry/replay-backend/issues/176

**Comment by ryan953** [comment]
cc @joshuarli @cmanallen

**Comment by JoshFerge** [comment]
how is activity calculated now?

**Comment by ryan953** [comment]
@JoshFerge It's calculated on the front end, the function is: https://github.com/getsentry/sentry/blob/master/static/app/components/replays/replayHighlight.tsx#L15-L27

It's still the alpha algorithm, so we can port it faithfully or replace if if we've got something better. The win would be to get a new numeric field on the server that we can search/sort by.

**Comment by ryan953** [comment]
Depends on https://github.com/getsentry/sentry/pull/40688/files

**Comment by jesus4497** [comment]
Depends on https://github.com/getsentry/sentry/pull/41388
