### ISSUE TITLE
Update last_login periodically

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#4046]
We want last_login to signal something more along the lines of "last active". We dont need to do this on every request, but we should do something like "if last_login is > one hour ago, update it to now" upon an active session's request (API or server views).

**Comment by travijuu** [comment]
Hello @dcramer, I created PR [#5151](https://github.com/getsentry/sentry/pull/5151) for this. Can you evaluate?
Thank you.

**Comment by mattrobenolt** [comment]
I'm comfortable saying this was closed with https://github.com/getsentry/sentry/pull/5630 and we track last_active instead.
