### ISSUE TITLE
Unable to bulk merge/resolve more than 1000 issues at a time

### ISSUE THREAD

**Issue by francoishill** [getsentry/sentry#4050]
Do a search that would produce more than 1000 issues. If you use the "select all" checkbox and then click the message `25 issues on this page selected.Select all issues matching this search query.` it only ends up merging/resolving 1000 of the issues.

The relevant line/todo in the source code seems to be in file [project_group_index.py line 329](https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/project_group_index.py#L329) where there is a todo comment reading: 

```
# bulk mutations are limited to 1000 items
# TODO(dcramer): it'd be nice to support more than this, but its
# a bit too complicated right now
```

**Comment by Meh-Lindi** [comment]
Its not even doing that.

I would say from having spent hours doing this - I'd say it is only merging only say 100 or 200 records per "merge all"

Could the "Merge all" link and message at least just say how many it is doing until its actually resolved, so that you know its not doing "all"?

**Comment by dcramer** [comment]
It definitely caps at 1k items (this is implemented in the software, its very explicit). We can't tell you how many are actually going to be merged/etc. The best we could do is say "there are more than 1k results". In the ideal world this would just merge them all, but there's complexity in that doing this synchronously creates very long running processes, and doing it async creates UI feedback issues.

**Comment by ajgrover** [comment]
That feedback alone would be helpful, right now the copy sets the expectation that all issues will actually be merged/resolved which was very confusing for us

**Comment by jarekwg** [comment]
Bulk deletion seems to only do 25 at a time (same amount that's displayed)..

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
