### ISSUE TITLE
NOT Origin check in error_page_embed.py causes 403 User Feedback page on mobile devices for non-referrer requests

### ISSUE THREAD

**Issue by codewise-nicolas** [getsentry/sentry#4060]
When using the raven-js library in phonegap (or other mobile js framework or any other direct way to get to the /api/embed/error-page url) if the User Feedback functionality is triggered, it leads to a 403 error.
The browser/url attempted to be loaded is /api/embed/error-page

Even with SENTRY_ALLOW_ORIGIN = "*" there is a 403.

Due to the code at line 82 of the error_page_embed.py https://github.com/getsentry/sentry/blob/e9f671ad701a7a6074cc0df42c8a03ebfb3cc437/src/sentry/web/frontend/error_page_embed.py if there is no origin or referer set, then the _get_origin function returns none, and thus the check at line 82 fails and you get a 403 error.

When this url is being access from a mobile app such as made by phonegap, the referer will not be set (or even be valid) sometimes. 

Possible solutions:
a) if allow_origin = \* then dont even do that check
b) have some extra setting to allow bypassing this check
c) ignore this problem

I dont have the know how (or time) to provide a proper fix based on A, I have simply commented out that line 82 check on my version. Hope this helps other people.

**Comment by adamreisnz** [comment]
I think I'm running into a similar issue with the standard javascript client library.
Our server is getting hit by GET /embed/error-page/ requests, which of course lead to a bad request error as that URL is not mapped to a valid route.

Googling about who or what might be calling this URL yielded several issues from Sentry, so I assume Sentry might be trying to call this URL incorrectly without a proper domain.

Note that we do not have user feedback enabled for our projects.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by BYK** [comment]
Also I believe this was fixed via #14628.
