### ISSUE TITLE
Rules containing `EventFrequencyCondition` can have unexpected behavior.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#4065]
If a rule is defined that contains an `EventFrequencyCondition` and requires matching all conditions (or any conditions, if it is the sole condition), the `EventFrequencyCondition` will return `False` when evaluated against _any_ event subsequent to an event that caused the rule's action to be triggered, (regardless of whether the condition is actually satisfied.) In a pathological case, this can result in an action being taken only half of the times that the condition is actually met. This is due to [this conditional](https://github.com/getsentry/sentry/blob/45b83c448b6691c3c73908c31e420cf37f393138/src/sentry/rules/conditions/event_frequency.py#L48-L52)[1], which can trigger a false negative when a rule *should* match.

When a rule is implicitly created, the `state.rule_is_active` value is `False` (since it's created with the default `GroupRuleStatus.INACTIVE`.) This results in the condition body being evaluated since it passes the aforementioned conditional. If the condition passes, [the rule status is set to `GroupRuleStatus.INACTIVE` as part of the rule processor.](https://github.com/getsentry/sentry/blob/45b83c448b6691c3c73908c31e420cf37f393138/src/sentry/rules/processor.py#L114-L124) The next time the condition is evaluated, it will always return `false` — even if the rule should pass — due to the conditional at the beginning of the condition body. [This causes it to be flipped back to `GroupRuleStatus.INACTIVE` again in the rule processor](https://github.com/getsentry/sentry/blob/45b83c448b6691c3c73908c31e420cf37f393138/src/sentry/rules/processor.py#L125-L131), and the next condition check will return the correct value (at the point in time that it is actually checked — at which point the state may no longer exist that should have resulted in the action being triggered earlier.)

1: This comment isn't accurate, either — when a rule _is_ active, the action has already occurred.

**Comment by dcramer** [comment]
Going to resolve this by implementing GH-1400 and removing the one-off freq logic for these conditions.
