### ISSUE TITLE
Design treatment for the Replay preview CTA on Issue Details

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#40719]
### Problem
Today, the replay preview/thumbnail with the large purple play icon makes it seem like the video will play immediately within the issue context, instead it takes you to the dedicated replay UI.

There are also two CTAs in this section, purple play icon, as well as "View Full Replay" which both take you to the same place.

We want to better set user expectations here.

![Image](https://user-images.githubusercontent.com/77064737/198671815-d861836d-a77d-4d88-ae79-410d266a6f00.png)

### Acceptance Criteria
- Users still have to go to the replay details page to view the replay
- Users see updated UI to better align with their expectations
- Users see alert if replay can't found for various reasons

#### Figma
https://www.figma.com/file/wv3xGa0kw5Oj1jxE5EkYGA/Specs%3A-Replays-in-Issues-v3?node-id=1%3A4649

#### Screenshot

If there's a replay associated with this error event
![Image](https://user-images.githubusercontent.com/6508377/200567705-6e041374-cb64-4c1a-a895-8ae6786e668d.png)

If there's a replay associated with this error event, but for whatever reason can't be shown (Sampling for example)
![Image](https://user-images.githubusercontent.com/6508377/200569527-98bf7c8d-8a78-4edd-8096-ec2da35533a0.png)

**Comment by Jesse-Box** [comment]
Hey @jas-kas heres my design proposal for this.

I'm suggesting to increase the scope a little to include less than idea cases, much like what the trace navigator does.

If Replay is associated with error event
![Image](https://user-images.githubusercontent.com/6508377/199512086-7de0d101-d33d-45cb-bc27-961820c8b847.png)
If there was a problem with associated Replay
![Image](https://user-images.githubusercontent.com/6508377/199512112-1a9cae37-ec1d-4daf-aab0-4c7dc67ad127.png)
If they havent setup Replay but can
![Image](https://user-images.githubusercontent.com/6508377/199512141-a4cb135f-0328-4822-a74d-7a14630e0954.png)

**Comment by jas-kas** [comment]
Hey @Jesse-Box - I like that you explore the various states the replay could be in for the Issue Details page!

For state 1 - I ran this by Will (since it was his feedback originally) and he suggested "Open Replay" rather than "See Replay" since it is a bit more clear that you'll be taken to a new page as a user

For state 3 - I would check with Dora on this one. I think in general we might be reducing CTAs similar to this kind in the product. (See [slack thread](https://sentry.slack.com/archives/C041U8UMAVC/p1667234878082869))
Also note that if we had this, it should conditionally show up only if you're viewing an error from a JS or related proj. :)

**Comment by Jesse-Box** [comment]
@jas-kas I've updated the ticket description with updated designs.
