### ISSUE TITLE
Bug: Count of replays in the "Issue > Replay (N)" tab is incorrect

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#40730]
Depends on: https://github.com/getsentry/replay-backend/issues/190

1. Need to update the count on the Issues List page:
<img width="542" alt="Screen Shot 2022-11-04 at 8 41 36 AM" src="https://user-images.githubusercontent.com/187460/200032653-e5f315d1-67a8-429e-8814-cb0129748679.png">

2. Also the count on the "Issue>Replays" tab 
3. Also the count on the "Performance>Replays" tab

Related: https://github.com/getsentry/sentry/issues/40731

**Comment by jesus4497** [comment]
Please see this [comment](https://github.com/getsentry/sentry/pull/40798#issuecomment-1298885969) for more details for the solution
