### ISSUE TITLE
Upgrade Select2 to 4.0.3

### ISSUE THREAD

**Issue by michaelhelmick** [getsentry/sentry#4074]
I was looking to update a plugin and when attempting to allow the user to input multiple items from the autocomplete, I ran into an error like this:

`Option ajax is not allowed for Select2 when attached to a <select> element`

Googled around and found that versions of Select2 3.5.x and lower causes this error. Tried upgrading to 4.0.3 (current as typing) and got:

`Error: No select2/compat/initSelection`

I tried figuring out where it was coming from but I'm not too familiar with React.

tagFilter.jsx, ruleNode.jsx were both using `initSelection` I commented it out but got more compat issues.

Would be great if this could be updated. 🍪

**Comment by mattrobenolt** [comment]
@macqueen says she plans on updating this anyways.

**Comment by MaxBittker** [comment]
hey @michaelhelmick, I looked into this, and there were reasonable fixes for the JS api changes, but unfortunately https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/less/includes/select2.less
relies on a bunch of selectors that 4.0 breaks badly. with that in mind, pushing this off again for a bit - hope you were able to find a workaround

**Comment by michaelhelmick** [comment]
Ah, I wasn't. I kind of just left my changes to the sentry plugin laying around until this is handled. No worries, nothing pressing.

**Comment by benvinegar** [comment]
We've since removed select2.
