### ISSUE TITLE
Release + environment breakdown graph on group detail page uses incorrect bounds, causing it to display incorrect results.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#4076]
Example of this phenomenon on an issue that has *only* occurred in the "prod" environment:

![screenshot 2016-09-02 18 03 12](https://cloud.githubusercontent.com/assets/65315/18221694/e1411164-7136-11e6-8d1b-9254c9bd7db1.png)

The XHR request that provided the data for the above screenshot was made using these query parameters:

```
since:1472774400
until:1472860801
```

These bounds represent a 24 hour window:

```
In [2]: to_datetime(1472774400)                             
Out[2]: datetime.datetime(2016, 9, 2, 0, 0, tzinfo=<UTC>)   
                                                            
In [3]: to_datetime(1472860801)                             
Out[3]: datetime.datetime(2016, 9, 3, 0, 0, 1, tzinfo=<UTC>)
```

These values were [computed in this method](https://github.com/getsentry/sentry/blame/c3baa7d7ac93dfeadd283a40aa6148d6900d719b/src/sentry/static/sentry/app/components/group/releaseStats.jsx#L103-L132), passed through the [`GroupEnvironmentDetails` endpoint](https://github.com/getsentry/sentry/blame/c3baa7d7ac93dfeadd283a40aa6148d6900d719b/src/sentry/api/endpoints/group_environment_details.py#L59-L63) to the [`GroupEnvironmentWithStats` serializer](https://github.com/getsentry/sentry/blame/c3baa7d7ac93dfeadd283a40aa6148d6900d719b/src/sentry/api/serializers/models/environment.py#L50-L56), resulting in a response that included statistics for all 24 hours, but only 2 days of the 30 day period where the provided bounds overlapped the TSDB rollup intervals.

The rest of the statistics (used to render the gray bars) come from `GroupDetailsEndpoint`, which [doesn't actually accept bounding parameters for statistics](https://github.com/getsentry/sentry/blame/c3baa7d7ac93dfeadd283a40aa6148d6900d719b/src/sentry/api/endpoints/group_details.py#L190-L202), so those are correct values but attributed to incorrect releases and environments.

**Comment by mitsuhiko** [comment]
How did this ever work then?

**Comment by tkaemming** [comment]
> How did this ever work then?

I'm not really sure. Either it never actually did and we never noticed because we thought it was a backfill quirk, or something behavior changed [upstream of this method](https://github.com/getsentry/sentry/blame/c3baa7d7ac93dfeadd283a40aa6148d6900d719b/src/sentry/static/sentry/app/components/group/releaseStats.jsx#L103-L132) that caused the value of `this.props.group.stats` to be different.
