### ISSUE TITLE
need 1s when reporting error to sentry

### ISSUE THREAD

**Issue by zhaohehe** [getsentry/sentry#4077]
it's too slow when i report error to sentry, use php..codeigniter   .normal?

**Comment by mattrobenolt** [comment]
Hey @zhaohehe, I'm not entirely sure what you're asking, but this seems to be a better fit for https://forum.sentry.io. 

This issue tracker is strictly for issues relating to the server component.

**Comment by zhaohehe** [comment]
thanks for your reply,the problem has been solved:
I did not config curl_method,so the curl function take a long time.

like this:
$client = new Raven_Client($dsn, array(
    'curl_method' => 'exec',
));
