### ISSUE TITLE
User Feedback Detail Page Stopped Working

### ISSUE THREAD

**Issue by PhucNgo1711** [getsentry/sentry#40789]
### Environment

SaaS (https://sentry.io/)

### Version

Sentry 22.9.0

### Steps to Reproduce

1. Go to User Feedback 
2. Try to open one reported issue

### Expected Result

It should open up a detail page for the issue

### Actual Result

I got a 
```
Not found
Could not find an issue for the provided event id
```
This used to work fine about 2 weeks ago

**Comment by brianthi** [comment]
Hi @PhucNgo1711, this sounds like a problem specific to your Sentry organization.  Could you create [a support ticket](https://help.sentry.io/), and provide more specifics, such as your organization slug or organization ID, and which reported issue via user feedback you're trying to open?  Thanks!
