### ISSUE TITLE
Please truncate/trim stack traces with a large number of repeating calls

### ISSUE THREAD

**Issue by adambuczynski** [getsentry/sentry#4078]
E.g.:

![image](https://cloud.githubusercontent.com/assets/490562/18223820/38dc2efa-7217-11e6-99a0-0936e8366aa9.png)

I have literally pages and pages full of this because there was a RangeError with the max call stack exceeding. This large number of lines in the stack trace slows down the app a lot.

Is it possible to have Sentry detect these kind of repeating stack traces and truncate them with a message saying something like "Truncated (2300 more)"?

**Comment by mitsuhiko** [comment]
We could at the very least detect them in the UI. I would still like to capture them because in some languages we capture locals so they are not entirely the same and there is value in having them.

**Comment by adambuczynski** [comment]
Ok sounds good.

**Comment by MaxBittker** [comment]
![screenshot 2016-09-21 19 10 51](https://cloud.githubusercontent.com/assets/5915546/18735024/2e78dfb4-802f-11e6-9b25-6c6243ca4f4f.png)
 a rough draft

**Comment by adambuczynski** [comment]
Looks good. Just to confirm, is this done purely on the client side or is the JSON sent back from the server also truncated to avoid the duplicate lines? This because I'd still not like to have to download 20k+ lines of repeating code through my mobile subscription when I'm viewing an issue on my phone.

**Comment by MaxBittker** [comment]
I *think* they'd be gzipped, and if not that would probably be the best solution
