### ISSUE TITLE
Are source maps cached?

### ISSUE THREAD

**Issue by adambuczynski** [getsentry/sentry#4079]
I have encountered some errors in Sentry in which the source maps weren't parsed and I could only see the minified source code. I think this is because our source maps (and minified code bundles) are hashed, so for each deployment they get a unique file name.

If someone still has a browser window open with the old code base, Sentry doesn't seem to be able to find the missing source map file.

Is that to be expected or is there some way Sentry could cache the source maps so we would always have access to non minified code via the dashboard?

**Comment by mattrobenolt** [comment]
I think what you're looking for us our releases. This should give you more information about that: https://docs.sentry.io/hosted/clients/javascript/sourcemaps/#making-source-maps-available-to-sentry

**Comment by adambuczynski** [comment]
Ah thanks, I didn't know I can upload sourcemaps manually. Cheers.

**Comment by adambuczynski** [comment]
Sorry, can I not just upload a source map via the dashboard? Is via the CLI the only way?

**Comment by dcramer** [comment]
Its not really a process that caters to manual effort. You need to upload a sourcemap with each change of the sourcecode (usually each release) so we focus on features that make the process of pushing those easier.

**Comment by adambuczynski** [comment]
Fair enough, I guess I was just looking to quickly upload it so I could test it, but it makes more sense to integrate it after the deploy step.

**Comment by adambuczynski** [comment]
@dcramer follow up question: how would I upload source maps for different environments? I see in the documentation that I have to specify a URL prefix, but my app runs on a variety of different (sub) domains, hosted on different Firebase servers, for each environment (e.g. demo, staging, production). 

How do I consolidate this and properly set up source map support for all domains?

**Comment by dcramer** [comment]
@adambuczynski you'd use unique filenames (e.g. put a version in the URL). You can either re-use them on the same domain, or simply upload one per domain (we do that at Sentry, e.g. for staging vs production).
