### ISSUE TITLE
Replays column on Perf Views is populated but leads to unavailable replays

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#40896]
**Problem:**

For customers with `captureOnlyOnError:true`, there are replays populated in Performance views such as the "All Events" tab. When the play icon is clicked on, it sometimes leads to a Replay Details state where there is a "Page Not Found" error.

<img width="773" alt="Screen Shot 2022-11-02 at 12 31 09 PM" src="https://user-images.githubusercontent.com/77064737/199546955-fce4c889-ebce-428b-ba38-ed8276c6699a.png">

**Root cause brainstorm:**

- could be that we're associating transactions with not-yet-saved replay sessions because the session is waiting for an error
- capture on error means we don't know if the replay will exist or not, so transactions get proactively get tagged. and if an error never occurs, there is no replay

**Solution:**

Use new endpoint to do the count before showing link

**Comment by ryan953** [comment]
Related comment: https://github.com/getsentry/sentry/pull/40798#issuecomment-1298885969

> [we can] attempt to tag replays with the name of the associated transaction, and do this search on the replays dataset instead.

**Comment by ryan953** [comment]
> it’s missing `replay_start_timestamp`
- Josh

Should be fixed with https://github.com/getsentry/sentry-replay/pull/271

**Comment by ryan953** [comment]
Related to #40278

**Comment by ryan953** [comment]
The plan is that we're going to call the new `/replay-count/` endpoint (once it supports replayId as a param) and get a count of whichReplayIds actually have active replays available. Using that we can render links in all the places, or not.

**Comment by JoshFerge** [comment]
https://github.com/getsentry/sentry/pull/43188
