### ISSUE TITLE
Add additional playback speeds to Replay Details: 8x and 16x

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#40913]
We want to add more playback speeds (e.g., 8x and 16x) so users can skip ahead quickly in long replays.

![Image](https://user-images.githubusercontent.com/77064737/199589973-704f7f26-d536-4fb7-94f7-0ceb979bfe5e.png)

Updating ticket to add another request for this feature:

> Speedx options 1x, 2x,4x,8x

**Comment by pyeinblick** [comment]
Could avoid dropdown bloat with just 0.5/1/2 + free entry w/ max or min restrictions

**Comment by ryan953** [comment]
We could also do like a segmented number line, and have an input box beside it. It would still live behind the dropdown though.

This is low-pri right now, we're limiting replays to 30mins (if the user continues browsing a new replay will start capturing.. this will make it easier for us to manage the data, and also segment long sessions) so powering through long periods of boring  user activity shouldn't be so common.
