### ISSUE TITLE
Bad error message when linking stack trace to repo that's not part of project

### ISSUE THREAD

**Issue by mlissner** [getsentry/sentry#40918]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Great a crash that spans two repos and have it be captured by Sentry
2. In the stacktrace, there's a link that says, "Link to your code" or similar. Click it.
3. Paste in a link from a repo that's not part of the project.
4. You'll get an error that says, "Something went wrong: Could not find repo"

### Expected Result

I'd expect a better error message that tells me to add that repo to the project. I only figured this out after having a back-and-forth with the support folks, adding the repo to the project, and then trying again.

Even better would be if it just *added* the project automatically, maybe with a warning or something first, if there's a reason to do that.

### Actual Result

You get the error message, which doesn't make much sense. It's particularly confusing because it sort of seems like you're trying to find the repo *on the Internet.* So when the error says, "Could not find repo", you think the repo is private or something. Nope! It's just misconfigured.

**Comment by brianthi** [comment]
Hi @mlissner, thanks for the feedback.  We're actively looking to improve this and I will link this issue with our internal ticket to make sure you get updated.

**Comment by scttcper** [comment]
hey @mlissner we've updated the modal to be more clear and fixed a few bugs as well.

For your particular issue, we've added a banner that clarifies that we do not have access to that repo
![image](https://user-images.githubusercontent.com/1400464/204600574-8b4a1159-6ff2-43d5-9ea6-f0dbf697fcac.png)

**Comment by mlissner** [comment]
I love sentry. Thank you.
