### ISSUE TITLE
Ability export issue events to csv

### ISSUE THREAD

**Issue by dopesong** [getsentry/sentry#4094]
Hey guys,

It would be great for devs to be able export events of issue. In that case if something goes wrong - we can reproduce events with same data. :)

**Comment by dcramer** [comment]
I'd like to move this over to the forum as we're increasing visibility of product discussions there.

That said, adding more context would help. Do you want a continuous export (e.g. a data pipeline)? Just a simple "export the events in this issue"? A way to export a list of issues?

**Comment by dopesong** [comment]
@dcramer strange decision to move away from github, but ok. :)

**Comment by dcramer** [comment]
@dopesong mostly so we can focus on actual code bugs here (we get a TON of noise, like questions/feature requests). It's also where we direct community support, and its a bet more approachable than GitHub for that, so knowledge share there is helpful for us.

**Comment by dopesong** [comment]
@dcramer you see thing is that github is like core of whole open source world. There are lots of strange decisions and so on. Things like mailing groups and so on...

You see, when someone finds this issue they are able to provide pull request for it. Its easer to participate :)

**Comment by dcramer** [comment]
@dopesong that's the trick: no one provides pull requests. Sentry is fundamentally only build by the Sentry team, and big features like this are really unapproachable for most users. We also may or may not even want that PR (since we control Sentry, and want to ensure the product direction).

**Comment by dopesong** [comment]
Even I would try to help with some thing which can be easily done when I find them on github. I never read forums to provide some code - I'm checking for issues same like mine and then if there is need - I try to help :)

@dcramer - so sentry is open source product which not accepts anything but only provides product code? You should reconsider this and take a look how gitlab goes (they have community edition and enterprise edition) :)

**Comment by dcramer** [comment]
@dopesong guess who builds gitlab? :) the GitLab team, not the open source community

**Comment by dopesong** [comment]
Yeah but people provides code for features that really upvoted and so on. :)

**Comment by dopesong** [comment]
You see @dcramer - I don't try to find some shitty points to judge or something like that. I really like sentry, it goes to right direction, but don't build wall from community, because people like me are thankful and would like to provide some help etc... :)

**Comment by emanuelis** [comment]
@dopesong spent half a day today modifying sentry code to export data. And wanted to create a pull request.
At least 1/3 of programmers in our company want to contribute to github. Being more open you would benefit a lot.

**Comment by dcramer** [comment]
@emanuelis @dopesong like I said we're not against it. We'd just prefer discussing features before PRs get opened, as we don't want people to waste time if:

- we're already building something
- have alternatively plans
- genuinely don't think a feature is a good idea

**Comment by raymondjplante** [comment]
-1 for forum requiring additional login outside of your sentry login
