### ISSUE TITLE
Bug: Project slug in replay link on table view column undefined in certain cases

### ISSUE THREAD

**Issue by danecando** [getsentry/sentry#40981]
**Step to Repro:**

1. Go to discover
2. Set the columns to be `replayId` and `count()`
    <img width="882" alt="Screen Shot 2022-11-03 at 5 30 35 PM" src="https://user-images.githubusercontent.com/187460/199859936-5e7f8400-3486-4598-9cb7-b70b834ab704.png">

3. Make sure the timeframe is long enough to get some results in the table

Notice that the replay button links to an invalid url. The project slug is `undefined`

<img width="830" alt="Screen Shot 2022-11-03 at 5 31 40 PM" src="https://user-images.githubusercontent.com/187460/199860210-c3af4da1-8e2c-4bc8-8e79-4004aa362220.png">

The problem is that the code is making an assumption that `dataRow['project.name']` exists

https://github.com/getsentry/sentry/blob/f7ec37579b0c30c9497dac7614b443f4dc4401d2/static/app/views/eventsV2/table/tableView.tsx#L310-L313

Depends on https://github.com/getsentry/replay-backend/issues/213

See: https://github.com/getsentry/sentry/pull/40961#pullrequestreview-1167108327

**Comment by ryan953** [comment]
We could solve this by showing the `replayId` instead of the button, whenver we don't have the `project.name` in there. But we don't show `replayId` anywhere in the app right now, so I wouldn't want this to be the first spot.

**Comment by ryan953** [comment]
This'll be done as part of https://github.com/getsentry/sentry/issues/44345

closing because we'd don't need to track both things.
