### ISSUE TITLE
Bug: missing replay from manually triggered error

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#40984]
**Problem:**

Customer has manually triggered an error and recorded the user session of that error via the Replay SDK. The error can be seen in Sentry and there is a "1 replay" count shown on the Issues stream. However, you click into the replays list for that Issue, no replays are found.

Customer details are in [this Jira ticket](https://getsentry.atlassian.net/browse/FEEDBACK-1649). 

**Solution:** 

TBD.

**Comment by ryan953** [comment]
i think the issue is that the replay in question is too short.

**Comment by ryan953** [comment]
@JoshFerge can you look up replay `bde1cecf61c14c81b82114b4622b7000` inside org # 1112303 and see if it has a short duration?

**Comment by JoshFerge** [comment]
it's missing its `replay_start_timestamp` which means we can't compute duration,and therefore we don't return anything. we have a fix up at https://github.com/getsentry/sentry-replay/pull/271
