### ISSUE TITLE
"associate an identity" is not obviously a link

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#4108]
![image](https://cloud.githubusercontent.com/assets/375744/18396009/407f96f2-7676-11e6-9754-1b99434d2694.png)

This straight up just looks like bolded/emphasized text.

@getsentry/ui @macqueen 

I was thinking either to just simply give it an underline or something, or to move it out into an explicit "connect identity" button below. I'm leaning towards a button personally.

**Comment by ckj** [comment]
+1 for button. might be a good use for a bootstrap panel.
