### ISSUE TITLE
Invalid value for culprit

### ISSUE THREAD

**Issue by lukepolo** [getsentry/sentry#4110]
Trying to implement javascript error handling and getting this :

ERROR 403 : `{error: "Invalid value for culprit"}`

any ideas ? is this even related to sentry ?

**Comment by lukepolo** [comment]
Found out what it really means, is the error being sent is bad.

**Comment by mnpenner** [comment]
@lukepolo How did you fix it? Why is raven-js sending bad requests?

**Comment by lukepolo** [comment]
I think i had the wrong sentry id , cant remember tbh.

**Comment by rafis** [comment]
`culprit` is a field in JSON sent to Sentry server. Maybe this error happens because of culprit too large or contains something that Sentry don't like?
