### ISSUE TITLE
Change Default Layout to Top

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#41175]
### Problem
Sentaurs have mentioned that the replay video is too small, but based on amplitude data, very few people change the layout. I'm making an assumption here is that our default is wrong choice for most users needs which is, to watch the video first.

### Acceptance Criteria
- `top` is the default layout for the details page
- Maintain logic to change layout based on viewport size

**Comment by ryan953** [comment]
This is related to the other idea to change the dimensions to be 50% wide: https://github.com/getsentry/sentry/issues/41184
