### ISSUE TITLE
Detect MN+1 DB queries as a Performance Issue

### ISSUE THREAD

**Issue by mjq-sentry** [getsentry/sentry#41219]
For an example, see this span tree from #41202:

![200946222-4793e8de-a1dc-47e3-bc9f-d21542d0048a](https://user-images.githubusercontent.com/110054669/201142526-7f10068a-3e4c-41da-ae51-62cb8fb05546.png)

This is an N+1 DB query that isn't being caught by our N+1 detector because it's interspersed with another repeating span (`event.django`, in this case): an MN+1 DB query.

Either extend the existing N+1 detector or create a new detector that catches this shape: a repeating set of spans, at least one of which is a repeating database span.

## Open Questions

- Same issue type as N+1 DB Query, or a different one?
- Do the non-DB repeating spans also need to have equal hashes, or only the DB queries?

**Comment by gggritso** [comment]
Yes! IMO, can still be called "N+1", and the non-db spans don't need equal hashes. Also, if there is a set of _multiple_ database spans that are repeating, is that two N+1 issues, or one double issue? IMO two issues!
