### ISSUE TITLE
FlexibleForeignKey fields broken in admin

### ISSUE THREAD

**Issue by vsvasya** [getsentry/sentry#4124]
Just installed fresh sentry 8.8.0

In sentry admin all FlexibleForeignKey fields (such as team, organization, project) in all forms are just plain inputs instead of normal select fields or select2 js widgets.

**Comment by dcramer** [comment]
@vsvasya they're not really intended to work. The admin is more or less a convenience power user tool that's been deprecated internally, and will slowly be replaced by our own tooling.
