### ISSUE TITLE
NoReverseMatch

### ISSUE THREAD

**Issue by NotSqrt** [getsentry/sentry#4125]
Hi,

Got an exception when editing a user with sentry==8.8.0:

sentry/web/frontend/admin.py in edit_user at line 118:
```python
    if form.is_valid():
        user = form.save()
        return HttpResponseRedirect(reverse('sentry-admin-users'))
```
raises:
``NoReverseMatch: Reverse for 'sentry-admin-users' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []``

Regards,

**Comment by omniton** [comment]
Hi @dcramer ,
I'm getting same error on user account deleting:

Reverse for 'sentry-admin-users' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
sentry/web/frontend/admin.py in remove_user at line 154
```python
        if form.cleaned_data['removal_type'] == '2':
            user.delete()
        else:
            User.objects.filter(pk=user.pk).update(is_active=False)
        return HttpResponseRedirect(reverse('sentry-admin-users'))
    context = csrf(request)
    context.update({
        'form': form,
        'the_user': user,
```
python 2.7.12
sentry 8.9.0
