### ISSUE TITLE
Add pre-save rules

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#4148]
Right now all rules are used for alerts, but it would be useful if we could generate rules that happen at an earlier stage.

Three such sub categories would be useful:
- discarding events
  - same as our inbound data filters
- scrubbing certain data
  - "remove the HTTP post body"
- grouping events
  - defining a fingerprint most likely
  - .. or by saying "group them together" and having the system create a fingerprint automatically

These two actions happen at different stages of the lifecycle: filters and scrubbing are immediate, and grouping rules can take place later. That said, we could potentially do them all pre-queue to simplify things.

A simple course of action to implement this would be to take all the existing rules/conditions and re-type them as "post-save". Then create a new "pre-save" type, which has a different struct (just the normalized JSON payload) to bind new rules to. We'd then tweak various endpoints to be "alert rules" etc.

**Comment by dcramer** [comment]
I'm creating this on GH for now as it's something we plan to commit to doing, though I'm open to moving this discussion to the forum since that's been our target for most things.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
