### ISSUE TITLE
Design Nit: Issues List cuts off metadata at narrow widths

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#41548]
See the Issues tab on the Replay Details page:

**Wide enough:**

![Image](https://user-images.githubusercontent.com/187460/202588076-f61fc199-35ea-4edb-bde0-17f89e849805.png)

**Too Narrow:**

![Image](https://user-images.githubusercontent.com/187460/202588126-2f959c77-eb35-49a2-b64b-d68a8e2dbb6d.png)

**Comment by ryan953** [comment]
cc @Jesse-Box

**Comment by Jesse-Box** [comment]
@ryan953 is the graph column really needed? In the transaction summary page for example, they dont have it. Maybe that gives us more for our indicator here.

**Comment by Jesse-Box** [comment]
Bump @ryan953
