### ISSUE TITLE
Filtering on "environment" not working correctly

### ISSUE THREAD

**Issue by heytrav** [getsentry/sentry#4155]
We're using version 8.6.0 _in house_ 

We've integrated the *environment* flag across our project. I notice quite often that the events appear on the *Issues* page when I filter for *production* even though they are not in the production environment.

Issues page:
<img width="1209" alt="screen shot 2016-09-17 at 6 42 14 am" src="https://cloud.githubusercontent.com/assets/64812/18597540/a1ead618-7ca2-11e6-9141-83d0fb9f0e53.png">

When I click on any of the events appearing here:
<img width="636" alt="screen shot 2016-09-17 at 6 42 38 am" src="https://cloud.githubusercontent.com/assets/64812/18597570/b6fc3c86-7ca2-11e6-9e32-f046d6264db3.png">

**Comment by dcramer** [comment]
Sentry operates on aggregates, and the issue you're clicking has happened at least once in the environment you searched against. We don't attempt to forward to an individual sample (found in Related Events) that matches your search query today as it may not exist, and there's a bit of complexity around that.

**Comment by heytrav** [comment]
Thanks for the explanation. 

Personally, I still find it a bit misleading. I've been using the *Issues* page as the main *overview* of what is happening in our system. I would have expected that items appearing on this page, or any page that allows filtering, to match the mask I've specified. 

So if I understand correctly, the only way for me to know for certain that events appearing on this page (when I've selected *environment:production*) aren't still happening in *production*, is to go into each event and look for when it was last seen?

**Comment by dcramer** [comment]
@heytrav we want to make environment a first class citizen, but the challenges around what you're wanting is real-time aggregation. There's no reasonable way to on-demand update the page based on the search query (at any reasonable scale and performance).

With making environment first-class however, we can at least say "this very specific thing gets special cased". Our plan with that is to add a native environment selector (vs using an arbitrary tag query) and have all counts, last seen, etc represent specifically that environment.
