### ISSUE TITLE
GitHub Code Mapping link does not show if there is no inline source displayed

### ISSUE THREAD

**Issue by eric** [getsentry/sentry#41588]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open a Sentry Issue that has a stack trace with frames containing `abs_path` values that are in the source code repo
2. Look for a way to link to GitHub

### Expected Result

I expect to see a link to GitHub

### Actual Result

There is no link.

<img width="863" alt="CleanShot 2022-11-18 at 18 29 04@2x" src="https://user-images.githubusercontent.com/470/202830156-7c5c99f4-91b3-4635-b3b5-a3c80c274f04.png">

**Comment by armenzg** [comment]
Hi @eric 
Would you be able to share a link to that issue so I can look closely?
I'm also happy to look around until I find your org if you would rather not paste a link that would show your org slug.

Would you expect main.m to be a link to Github? (assuming that is a file that is part of one of your repos)

**Comment by eric** [comment]
@armenzg I would expect each line that has source file with underscores to link to github. Yes, main.m is one of them. 

Here is an example of an issue that has this problem: https://sentry.io/organizations/fancy-bits-llc/issues/3408717119/?project=1441550

**Comment by eric** [comment]
I'm still interested in this.

**Comment by hubertdeng123** [comment]
I'll see if the team responsible for this has an update for you.

**Comment by lobsterkatie** [comment]
@Armen, did you get a chance to dig into this at all when you were looking at it earlier this year?
