### ISSUE TITLE
Navigating to a project page while having a project locked throws "project filter has been overwritten" notice erroneously

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#41672]
The following message appears on the top of the project page when a project is locked in the project selector:

![Image](https://user-images.githubusercontent.com/1308394/203413111-63e78ddd-27a1-4f95-a4e3-7e1e28c80c09.png)

> "**The project filter has been overwritten.** This can happen when you open sentry.io links with filter parameters that are different from your current filter values."

However, the projects filter doesn't exist on the "Projects" page (only a team's filter), so this notice might be confusing to customers since there isn't a project filter on the project page.

Steps to reproduce:

1. Go to "Issues" open the projects selector and lock a project.
2. Go to "Projects" and select a project.
3. The notice above will be shown even though there is no project filter on the project page.

**Comment by gaprl** [comment]
IMHO we should remove the project filter notice from this page, but keep any other notices (for the environment or date period, for example).

**Comment by om-ray** [comment]
@gaprl I wasn't able to reproduce this issue
