### ISSUE TITLE
Add option to allow users to receive notifications for their own activity.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#4167]
This makes it easier to follow a comment/activity thread without logging into the application (e.g. from an email client.)

Here's how GitHub provides these options: 

![screenshot 2016-09-19 10 57 50](https://cloud.githubusercontent.com/assets/65315/18642862/3af82f76-7e57-11e6-9da8-3f45a2592a50.png)

This should probably be disabled by default (opt-in.)

**Comment by skoryky** [comment]
Wow, thanks for the fast turnaround time! 💐
