### ISSUE TITLE
Users are running into Internal Server error on the Issues page

### ISSUE THREAD

**Issue by rbisol** [getsentry/sentry#41692]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Open the issues page, this does not affect all projects in an organisation.

One possible workaround at the moment is to search for events using Discover.

### Expected Result

list of Issues to be presented

### Actual Result

Internal error message, and an event sent to Sentry. The resulting issue is: https://sentry.io/organizations/sentry/issues/3759086300/?project=1

NotImplementedError
Unknown Owner
https://github.com/getsentry/sentry/blob/cf97cdd53fa09ca3787be33af2cf1872ffbfa7b2/src/sentry/models/groupowner.py#L93

**Comment by rbisol** [comment]
quick update: The issue has been identified and mitigation is being implemented.

**Comment by rbisol** [comment]
The issue should be fixed now. Please report here if you are still seeing it.

**Comment by iainad** [comment]
Confirm it's fixed. Thanks.

**Comment by dmudro** [comment]
thanks all!
