### ISSUE TITLE
Share at timestamp

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#41731]
### Problem
Interesting moments in a replay can last a few seconds but our replays can be much longer. Meaning if an engineer wanted to share that interesting moment with their colleagues, they would have to give them precise times to skim to. That sucks

### Acceptance Critertia
- User can share a Replay's URL which starts from the beginning
- User can share a Replay's URL which starts at a specific point in time
- If the user has already played a replay up to a specific point in time, that time is prefilled in the "Start at" field

### Designs
[Figma Designs](https://www.figma.com/file/VTwvF65Dvg710T7k2Jvghl/Specs%3A-Share-Modal?node-id=0%3A1&t=VThObqaDgowc3uZL-1)

![Image](https://user-images.githubusercontent.com/6508377/203759701-2ac1b19e-f844-4491-b1e8-06eb95a4b919.png)
![Image](https://user-images.githubusercontent.com/6508377/203759718-fa802875-a421-45c9-98f0-eaa7f3bcd51d.png)
![Image](https://user-images.githubusercontent.com/6508377/203759766-5d1961e7-5bcf-4644-bdf7-1ee22df37c27.png)

**Comment by Jesse-Box** [comment]
@jas-kas @ryan953 designs attached

**Comment by billyvg** [comment]
Will this be confusing with the concept of shared issues which make the issue public?

Im curious to see how often this will be used. In the future, I would like to see it tucked away in a contextual (right click) menu on player and timeline -- if it's not used often.
