### ISSUE TITLE
Unable to create a new alert from www/settings/alerts/rules/

### ISSUE THREAD

**Issue by jessicalc** [getsentry/sentry#4175]
**Steps to repro**

1. From https://sentry.io/[my-project]/www/settings/alerts/rules/, click on `New Alert Rule`

**Expected**
I should be able to create a new rule

**Actual**
I get a **Page Not Found**
![image](https://cloud.githubusercontent.com/assets/729524/18651745/14f4ab94-7e82-11e6-9fae-0350a1554f93.png)

This is also happening to my colleague on his own account. Thank you!

**Comment by dcramer** [comment]
Sorry about that!

We'll get this deployed in a moment, and its fixed in 6e4c5887565b898ef2f32afce49c124b32746684

**Comment by jessicalc** [comment]
No worries! Thanks a lot 💯
