### ISSUE TITLE
Filter by tag not working

### ISSUE THREAD

**Issue by ashalaenko** [getsentry/sentry#4181]
I send to sentry.
sentry_client.capture('raven.events.Message', message="foo_test_error", data={"logger":"javascript"}, tags={"app": "015", "captureError": "custom", "authId": "1", "username": "user"})

So in sentry i see the event with tags. But when i try to use filter like "has:app" I got an empty result.
So, when I check sentry issue by http://my_sentry_server.com/api/0/issues/2902/
 I got my issue with empty "tags" field
```json
seenBy": [],
"lastSeen": "2016-09-19T16:11:14Z",
"userReportCount": 0,
"numComments": 0,
"userCount": 0,
"stats": {},
"culprit": "/usr/bin/ipython",
"title": "foo_test_error",
"id": "2902",
"assignedTo": null,
"logger": "javascript",
"type": "default",
"annotations": [],
"metadata": {
"title": "foo_test_error"
},
"status": "unresolved",
"pluginActions": [],
"tags": [],
"isPublic": false,
"hasSeen": true,
...
"shareId": "342e32393032",
"firstSeen": "2016-09-19T15:20:14Z",
"count": "1",
"permalink": "link_to_issue",
"level": "error",
"isBookmarked": false,
"project": {...}
...
````

But when I check events by http://my_sentry_server.com/api/0/issues/2902/events/ I got all my tags
```json
{
"eventID": "696dd6a8bfa14a25bc7d0ac93fcaa1a2",
"tags": [
{
"value": "015",
"key": "app"
},
{
"value": "1",
"key": "authId"
},
{
"value": "custom",
"key": "captureError"
},
{
"value": "error",
"key": "level"
},
{
"value": "javascript",
"key": "logger"
},
{
"value": "user",
"key": "username"
}
],
"dateCreated": "2016-09-19T16:11:14Z",
"dateReceived": "2016-09-19T16:11:14Z",
....
```

So the question: why I can't filter my issues by tag using "has:[tag_name] [tag_name]:[tag_value]" in query?

Example:
api/0/projects/sentry/my_project/issues/?query=app:015

got 

```json
[]
```

**Comment by dcramer** [comment]
Tags are indexed via the buffer processes. It sounds like they're not running, or not running correctly.

**Comment by belegnar** [comment]
How to debug this process to provide more debug info?

**Comment by dcramer** [comment]
Please open a new ticket with relevant details if you're having issues, but if its simply operational questions those belong on our forums as the ticket tracker is reserved for known issues.
