### ISSUE TITLE
SENTRY_PUBLIC=True makes all users be redirected to /sentry by default.

### ISSUE THREAD

**Issue by mgedmin** [getsentry/sentry#4182]
Fresh install of on-premises Sentry 8.8.0.  `SENTRY_PUBLIC` is `True`.  There are two organizations: the builtin 'sentry' and one other.  There are a number of users that belong to the other organization.

Whenever any of those users first logs in, they're redirected to `/sentry` and get a message saying there was an error loading data.

AFAICT this happens because `OrganizationMixin.redirect_to_org()` calls `self.get_active_organization()` which calls `Organization.objects.get_for_user()`, which checks `SENTRY_PUBLIC` and returns all the organizations, and not just the ones that have `user` as a member.

Turning off `SENTRY_PUBLIC` fixes things: the users get redirected to the right organization.

I don't know if `SENTRY_PUBLIC` is supposed to grant the users access to the internal sentry org/project, but if it doesn't, it would be nice if `redirect_to_org()` wouldn't default to it.

**Comment by dcramer** [comment]
This feature should be removed. It's from an era of sentry that is much different than today, and while it still works in some situations the meaning of the flag has changed over the years.
