### ISSUE TITLE
Permissions Error on issues replays tab

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry#41836]
- when loading the replays tab, we hit the endpoint `https://sentry.io/api/0/organizations/{org_slug}/events`. if the org isn't on a business plan, the endpoint returns a 400 `{"detail":"You cannot view events from multiple projects."}`.

for whatever reason, if you refresh the page, the query then works.

**Comment by ryan953** [comment]
This depends on #41720 at least. Might be easy to slip in a fix to that change
