### ISSUE TITLE
Be able to attach an exception to a payload, but treat the payload as a message

### ISSUE THREAD

**Issue by lyrixx** [getsentry/sentry#4183]
Hello.

I'm going to talk about PHP but I think the same logic applies to all languages.

So in PHP, with [monolog](https://github.com/Seldaek/monolog) you can write this kind of code:

``` php
try {
    $this->userRepository->find($id);
} catch (Exception $e) {
    $this->logger->error('Impossible to send an email to user because it does not exist.', [
        'exception' => $e,
        'id' => $id,
    ]);

    return;
}
// ...

```

Because I added the `exception` in the payload, the exception will be used as the "main message". Example of an exception:
![screenshot2](https://cloud.githubusercontent.com/assets/408368/18672378/3bb77768-7f48-11e6-89af-14bdd2fb92c4.png)

It's nice because Sentry add automatically the stacktrace and it is well displayed into the UI.

But actually I don't like it, because it displays the title of the exception and not **my** title (`Impossible to send an email to user because it does not exist.`).

More over, the `userRepository::find` always throw the same exception, so if I have the same block of code in different place of my application, all theses messages will be grouped together.

Obviously, I can use captureMessage and not captureException of the PHP SDK but the exception will not be rendered in the UI as beautiful as it is.

---

I tried to play a bit the SDK and I was not able to do what I want:
```php

$client = new Raven_Client('XXXX');

$client->captureMessage('First capture');
$exception = new \Exception('this is a new exception');
$options['message'] = 'Second capture ?';
$client->captureException($exception, $options);

```

---

So could you please add a flag or something to use the initial/raw message when an exception is attached in the payload?

Thanks.

**Comment by lyrixx** [comment]
hello here.

Do you have any feedback on this issue?

Thanks.

**Comment by dcramer** [comment]
It's very unlikely anything will change here, as the server controls this. It's important to remember that Sentry is for capturing exceptions (and not simple messages), so at the end of the day we care about prioritizing that information. If you're just wanting a stacktrace that's a different concern, and I believe you can already pass an argument to captureMessage in order to pull in the current stack.
