### ISSUE TITLE
settings/notifications/ digests: maximum & minimum seem mixed up

### ISSUE THREAD

**Issue by oTree-org** [getsentry/sentry#4200]
I think the words "minimum" and "maximum" should be reversed...because a lower interval is a higher frequency

![image](https://cloud.githubusercontent.com/assets/5423929/18745015/dbc07a1a-80c0-11e6-8cf3-844ca81fc9fb.png)
 
Using v8.8.0 on-premise

**Comment by MaxBittker** [comment]
good catch 😄  hopefully you approve of my fix.
