### ISSUE TITLE
"Test Configuration" for WebHooks always returns "No errors returned"

### ISSUE THREAD

**Issue by aryeh-looker** [getsentry/sentry#4201]
While "Test Configuration" does indeed send a test request, Sentry always reports that the request was successful:

<img width="724" alt="screen shot 2016-09-22 at 11 08 18 am" src="https://cloud.githubusercontent.com/assets/12849602/18760191/e338d712-80b4-11e6-9f54-105ca81ad2a8.png">

... even if a server is not available at the specified URI.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
