### ISSUE TITLE
embed page endpoint is fixed to https

### ISSUE THREAD

**Issue by minhur** [getsentry/sentry#4203]
I'm dumbfounded by this problem:

The User Feedback Page first makes request to render an html. 
https://sentry.xxx.net/api/embed/error-page/....

but the response from it is always set to https
```
var endpoint = /**/"http://sentry.xxx.net/api/embed/error-page/?eventId=41d2cc0fc54643fcb7715e9dbf8b...";/**/'';
```

which causes an issue with User Feedback Pages, as it tries to submit the user feedback form to `http` instead of `https`

What I need is for that var endpoint to return from backend

```
var endpoint = /**/"https://sentry.xxx.net/api/embed/error-page/?eventId=41d2cc0fc54643fcb7715e9dbf8b...";/**/'';
```

It looks like the endpoint is decided at:
https://github.com/getsentry/sentry/blob/8a376f8078fc4417d027a96363ea2573bd27e0c9/src/sentry/web/frontend/error_page_embed.py#L160

I'm not sure what it keeps returning as `http` there though.

Initially I thought it's a configuration problem, but my system.url-prefix is set correctly
```
config get system.url-prefix
        type: STRING
 from config: https://sentry.xxx.net
     current: https://sentry.xxx.net
```

The only noticeable thing might be that i'm going through a load balancer, which takes in req by 443 and then send to my nginx running on 80, which reverse proxies to 9000.

any thoughts?

**Comment by mattrobenolt** [comment]
You're missing the proper SSL config in your sentry.conf.py.

You need to make sure you have this stuff:

```python
##############
# Web Server #
##############

# If you're using a reverse SSL proxy, you should enable the X-Forwarded-Proto
# header and uncomment the following settings
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
```

**Comment by minhur** [comment]
Thanks @mattrobenolt .

i've updated to have the response header have:
```
X-Forwarded-Proto:https
```

and updated sentry.conf.py to have
```
##############
# Web Server #
##############

# If you're using a reverse SSL proxy, you should enable the X-Forwarded-Proto
# header and set `SENTRY_USE_SSL=1`

SENTRY_USE_SSL=1
if Bool(env('SENTRY_USE_SSL', False)):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
```

however i'm still getting insecure error where endpoint is set to http instead of https.
is there something else i'm missing? do I not need to use SENTRY_USE_SSL=1 and just set the settings under it as true by default?

**Comment by mattrobenolt** [comment]
Yeah, for sure. Also, you didn't mention this was docker. For that, you can just set `SENTRY_USE_SSL=1` as an env var on the container.

**Comment by minhur** [comment]
it's still not working for me unfortunately,  
to rule out any issues, i'm trying to force in the headers for now:

nginx.conf
```
    location / {
        proxy_pass         http://localhost:9000;
        proxy_redirect     off;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        add_header   X-Forwarded-Proto https;
    }
```

sentry.conf.py 
```
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
```

start.sh
```
docker run \
  --detach \
  --link sentry-redis:redis \
  --link sentry-postgres:postgres \
  --link sentry-smtp:smtp \
  --env SENTRY_SECRET_KEY=xxxxxx \
  --env SENTRY_USE_SSL=1 \
  --name sentry-web-01 \
  -p 9000:9000 \
  sentry-onpremise \
  run web
```

at this point everything runs fine under HTTPS.  
but whenever I use the User Feedback Modal, it resorts to http on form submit instead of https

![image](https://cloud.githubusercontent.com/assets/456497/18853108/8edc6c14-8411-11e6-86cc-7256ede40a5f.png)

![image](https://cloud.githubusercontent.com/assets/456497/18853160/c833dc72-8411-11e6-8fa1-b3c31c388952.png)

What I'm failing to do is to get this response from https call to return an endpoint set to *https* instead of *https*

![image](https://cloud.githubusercontent.com/assets/456497/18853248/1ed2ead2-8412-11e6-8431-381307ac7f89.png)

**Comment by mattrobenolt** [comment]
You're nginxing wrong. `add_header` is wrong, it should be `proxy_set_header`.

**Comment by minhur** [comment]
I do have proxy add header, add header was added as well just to test. 

i do see the header in my first request to embed (screenshot above)

The second form post req fails since client is on https but form tries to submit to http

Is there a way to force the endpoint to https from error_page_embed.py?

**Comment by minhur** [comment]
nevermind, you were right. I was touching the wrong file when setting this up.

turns out I was touching the wrong nginx.conf (i have two setup for it and the other was missing it)
setting this on nginx
```
        proxy_set_header   X-Forwarded-Proto https;
```

and using on docker start command helped
```
  --env SENTRY_USE_SSL=1 \
```

thanks so much for the help @mattrobenolt
