### ISSUE TITLE
Show the reason a field was rejected in the UI

### ISSUE THREAD

**Issue by marcomorain** [getsentry/sentry#4204]
I have an event sent using the Sentry-Android SDK that has an invalid timestamp field. 

> There was 1 error encountered while processing this event
> Discarded invalid value for parameter 'timestamp'

```
{
  "name": "timestamp",
  "value": "2016-09-22T19:08:10"
}
```

The event is here for those with access:

https://sentry.io/flipdish/android/issues/142638597/

I believe the problem is that the timestamp is 8 minutes in the future (according to the time Sentey says the event was received – September 22 2016 19:00:50 UTC

It would be awesome if Sentry could give the reason for why a field has been rejected.

In this case I didn't know if there was an error parsing the field (the string format could have been invalid) or if the field was passed correctly but the value was invalid (as appears to be the case).

**Comment by tkaemming** [comment]
There's a similar issue with data scrubbing, noted here: GH-3050

**Comment by bruno-garcia** [comment]
The reason is displayed on the UI currently.
