### ISSUE TITLE
Add IP address to Alert Rule edits

### ISSUE THREAD

**Issue by rjo100** [getsentry/sentry#42083]
Rodolfo submitted feedback. No IP address is logged in the audit log for alert_rule.edit (and possibly more).

**Comment by rjo100** [comment]
Root cause on this is the `AlertRuleSerializer` is used in a variety of contexts, chiefly for creating/editing alert rules. Since it's generally generic, we don't pass the `ip_address` into the context like we should from the request. By the time we actually fire the signal to the audit log, we've stripped the `ip_address` from the serializer.

**Comment by jangjodi** [comment]
The IP address is logged for edited rules: 
<img width="1184" alt="Screenshot 2024-04-30 at 3 16 24 PM" src="https://github.com/getsentry/sentry/assets/116035587/504b35af-d761-4dbe-a763-a9e85c202862">
