### ISSUE TITLE
Render `reason` code in HTTP breadcrumbs?

### ISSUE THREAD

**Issue by marcomorain** [getsentry/sentry#4208]
I've been adding breadcrumb support to [Sentry-Android](https://github.com/joshdholtz/Sentry-Android) today and I'm wondering what to do with the `reason` string from HTTP breadcrumbs. It doesn't seem to be rendered in the UI:

<img width="927" alt="screen shot 2016-09-25 at 14 25 00" src="https://cloud.githubusercontent.com/assets/448001/18815508/de8fe2f4-832b-11e6-93ed-270e25d76c1b.png">

My breadcrumb is setting the `reason` to `OK`:

```
{
  "category": "http.post",
  "timestamp": 1474809665.0,
  "message":"",
  "type":"http",
  "data":{
    "url": "https://example.com/form/",
    "status_code": "200" ,
    "reason": "OK" ,
    "method": "POST"
  }
},
```

Should I just send the `reason` code regardless?

**Comment by billyvg** [comment]
Currently we only render the method, url, and status code:

https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/app/components/events/interfaces/breadcrumbs/httpRenderer.jsx#L23
