### ISSUE TITLE
sentry wont run

### ISSUE THREAD

**Issue by rstalbow** [getsentry/sentry#4211]
I get the following output when I run `SENTRY_CONF=/etc/sentry sentry run web`:

`*** Starting uWSGI 2.0.13.1 (64bit) on [Mon Sep 26 13:36:04 2016] ***`
`compiled with version: 4.8.4 on 26 September 2016 09:34:05`
`os: Linux-3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016`
`nodename: ip-10-0-2-238`
`machine: x86_64`
`clock source: unix`
`detected number of CPU cores: 1`
`current working directory: /srv/sentry/lib/python2.7/site-packages/sentry`
`detected binary path: /srv/sentry/bin/uwsgi`
`!!! no internal routing support, rebuild with pcre support !!!`
`uWSGI running as root, you can use --uid/--gid/--chroot options`
`*** WARNING: you are running uWSGI as root !!! (use the --uid flag) ***`
`your processes number limit is 15926`
`your memory page size is 4096 bytes`
`detected max file descriptor number: 1024`
`lock engine: pthread robust mutexes`
`thunder lock: enabled`
`Python version: 2.7.6 (default, Jun 22 2015, 18:01:27)  [GCC 4.8.2]`
`Set PythonHome to /srv/sentry`
`Python main interpreter initialized at 0xb78e70`
`python threads support enabled`
`The -s/--socket option is missing and stdin is not a socket.`

When I run Sentry as a Service using Supervisor I get the same error in the Supervisor error log.

Any ideas how to get it running? The worker and cron run without issue using Supervisor.

**Comment by mattrobenolt** [comment]
What's in your config? It looks like you have some bad options in `SENTRY_WEB_OPTIONS`.

**Comment by rstalbow** [comment]
Thanks......that's what was wrong.

**Comment by rstalbow** [comment]
now all i get it a 502 bad gateway. this is my nginx config:

upstream sentry {
    server 0.0.0.0:9000;
}

server {

    listen 80;
    server_name sentry-new-vpn.*;

    access_log /var/log/nginx/sentry_access.log;
    error_log /var/log/nginx/sentry_error.log notice;


    # pass through all API calls w/o nginx authentication
    location /api/store {
       proxy_set_header HOST $http_host;
       proxy_pass http://sentry;
       proxy_buffering off;  # no need as services are local
    }

    location / {

       proxy_redirect     off;
       proxy_set_header HOST $http_host;
       proxy_pass http://sentry;
       proxy_buffering off;  # no need as services are local
    }
}

any ideas what could be wrong?

**Comment by dcramer** [comment]
Please use our forums for questions. We don't provide general support here.
