### ISSUE TITLE
CSP error: Event dropped due to filter

### ISSUE THREAD

**Issue by yannickcr** [getsentry/sentry#4212]
According to https://github.com/getsentry/sentry/issues/729#issuecomment-231825330 CSP Reports are available for testing.

However, I cannot send CSP Reports to sentry, my requests keeps being rejected by sentry.io with the error `"Event dropped due to filter"` (https://github.com/getsentry/sentry/blob/master/src/sentry/web/api.py#L324):

CSP Header:
```
content-security-policy-report-only: default-src 'self'; report-uri https://sentry.io/api/68268/csp-report/?sentry_key=XXX
```

Request Headers:
```
Host: sentry.io
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:48.0) Gecko/20100101 Firefox/48.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
DNT: 1
Content-Length: 367
Content-Type: application/csp-report
Connection: keep-alive
```

Request Body:
```json
{
  "csp-report": {
    "blocked-uri": "http://local-files.deezerdev.com",
    "document-uri":"http://local-www.deezerdev.com/album/11471884",
    "original-policy": "default-src http://local-www.deezerdev.com; report-uri https://sentry.io/api/68268/csp-report/?sentry_key=XXX",
    "referrer": "",
    "violated-directive": "default-src http://local-www.deezerdev.com"
  }
}
```

Sentry Response Headers:
```
Cache-Control: max-age=0
Content-Encoding: gzip
Content-Language: en
Content-Type: application/json
Date: Mon, 26 Sep 2016 14:00:09 GMT
Expires: Mon, 26 Sep 2016 14:00:09 GMT
Last-Modified: Mon, 26 Sep 2016 14:00:09 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Vary: Accept-Encoding, Accept-Language, Cookie
X-Content-Type-Options: nosniff
X-Firefox-Spdy: h2
X-Served-By: web-13
X-XSS-Protection: 1; mode=block
x-frame-options: deny
x-sentry-error: Event dropped due to filter
```

Sentry Response Body:
```json
{
  "error": "Event dropped due to filter"
}
```
I tried to remove "Default ignored Sources" and all "Inbound Data Filters", without success. And afaik my project is not over quota.

Did I miss something? 

(Let me know if you need more information about my project configuration)

**Comment by mattrobenolt** [comment]
This report is flat out not giving us enough information to do anything useful with it.

It seems like it's being dropped right here: https://github.com/getsentry/sentry/blob/master/src/sentry/utils/csp.py#L81-L82 because there is no `effective-directive` block.

This is due to FireFox not implementing this yet, as seen by this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1192684

We're choosing to drop these because Chrome handles it just fine, and CSP doesn't have varying behavior between browsers like JavaScript. So if this error came from a Chrome browser, it'd be logged and you'd see what's going on.

**Comment by yannickcr** [comment]
Thanks for these information. It was not very clear why my event was dropped by Sentry here.

**Comment by dlebedynskyi** [comment]
we have same problem with [effective_directive](https://github.com/getsentry/sentry/blob/master/src/sentry/utils/csp.py#L98). 
Chrome by default send it and report gets rejected. 
Bumper to use sentry for CSP 😢
