### ISSUE TITLE
Sentry problem on cleanup

### ISSUE THREAD

**Issue by hheexx** [getsentry/sentry#42137]
### Self-Hosted Version

22.11.0

### CPU Architecture

x86_64

### Docker Version

20.10.21

### Docker Compose Version

1.29.2

### Steps to Reproduce

sudo docker-compose run -T web cleanup --days 90 -m nodestore -l debug

### Expected Result

no error

### Actual Result

```
Cleaning up unused FileBlob references
>> Skipping FileBlob
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
```

**Comment by hheexx** [comment]
If it is a warning than it's no priority.

btw. way to clean up artifacts is highly needed, my sentry installation is growing rapidly passing 1tb size.

**Comment by cclauss** [comment]
Is this fixed?  Can it be closed?
https://github.com/linsomniac/python-memcached/blob/5c5cb1bc965c941f93b166d7ab2c055e3d8261e0/memcache.py#L1309

**Comment by hubertdeng123** [comment]
Yeah, looks like this can be closed.
