### ISSUE TITLE
sentry celery worker memory leak with redis broker

### ISSUE THREAD

**Issue by adilnaimi** [getsentry/sentry#4213]
I'm facing an issue, after running sentry for a while, sentry service down.

Is there a recommended setup to avoid memory leak.

I'm running on promise sentry: 
Instance type: EC2 m4.xlarge, 4CPUs, 16Gb RAM
The same instance is running the following containers:
`redis`

`sentry web, using start`

`celery worker`

`celery beat`

I'm running sentry version 8.0.4

**Comment by bsergean** [comment]
It's unclear whether this will fix it, but 8.0.4 is pretty old, I would give a try to the latest 8.8.0.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
