### ISSUE TITLE
/api/0/internal/health/ returns 403 forbidden

### ISSUE THREAD

**Issue by fastest963** [getsentry/sentry#4218]
I noticed that the Dashboard tries to load `/api/0/internal/health/` which returns:
```{"detail": "You do not have permission to perform this action."}``` and a status of `403 Forbidden`. My role is `Owner` and I'm logged in. It doesn't seem to work for other users either. We use SSO with Google to login and we're running Sentry 8.8.0 behind Nginx over SSL. Let me know if there's any more detail I can provide.

**Comment by dcramer** [comment]
@fastest963 this is only for Sentry admins. It's a bit of noise, but we check it 100% of the time whether you're logged in or not, since the UI may not be able to load upon health failures.
