### ISSUE TITLE
Embed display issue with subheading

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#4221]
![screenshot 2016-09-27 11 56 37](https://cloud.githubusercontent.com/assets/23610/18887580/7c4ccea2-84a9-11e6-87c3-03af48700948.png)

**Comment by dcramer** [comment]
Actually seems to happen elsewhere. Looks like we just need to explicitly define fonts.

![screenshot 2016-09-27 12 56 47](https://cloud.githubusercontent.com/assets/23610/18889443/e35cb1e0-84b1-11e6-9e30-c40be02d8748.png)

**Comment by MaxBittker** [comment]
@dcramer to be clear, the problem here is the low contrast right?

**Comment by dcramer** [comment]
@MaxBittker mostly that its using a different font than what we are specifying, which is fine, but it shouldn't override implicitly like this (users should have to explicitly target our css selectors if they want this)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
