### ISSUE TITLE
Refreshing issue list page doesn't work with replay count

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry#42239]
the issue-replay-count endpoint can take in a maximum of 25 replay ids. When the "realtime updates" feature is enabled on the replay list page, we will add more replays to the page. we'll attempt to load in all 26+ issue ids into our endpoint, which can only take a maximum of 25 replay ids. We either need to cache the previous issue replay counts, or perhaps do multiple requests.

**Comment by ryan953** [comment]
See also : https://github.com/getsentry/sentry/blob/master/static/app/views/issueList/overview.tsx#L83
