### ISSUE TITLE
Make sure we allow searching Replays list by error_id, transaction_id, url(s) and tags

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#42273]
Depends on https://github.com/getsentry/replay-backend/issues/242

**Comment by mattleonowicz** [comment]
Looks like you're good with URLs already, but searching by custom tags like in Issues would be awesome 🚀 
<img width="546" alt="Screenshot 2023-01-20 at 16 19 37" src="https://user-images.githubusercontent.com/9438872/213734362-328b8bed-2987-4f32-aea2-7b80a5cf7068.png">

**Comment by bruno-garcia** [comment]
@mattleonowicz the search by custom tags is available. But there's no auto complete for that yet.
