### ISSUE TITLE
Uncheck a plugin integration does not remove the configuration from db

### ISSUE THREAD

**Issue by swdream** [getsentry/sentry#4228]
I am using some sentry plugins such as sentry-youtrack, sentry-slack. When I disable these plugins for a project, their configurations were not  removed from DB.
There is any reason for that? I think it is a bug, isn't it? 

sentry version: 8.4.0
sentry-youtrack plugin version: 0.3.3
sentry-slack plugin version: 0.4.0

Thanks & best regards.

**Comment by dcramer** [comment]
@swdream this is not a feature that exists. Unchecking (and saving) simply disables it.

**Comment by swdream** [comment]
@dcramer will this feature be developed in the future?

**Comment by dcramer** [comment]
@swdream i dont know but if you're suggesting that unchecking a plugin should uninstall the module its very unlikely that will ever happen

**Comment by swdream** [comment]
@dcramer No, I mean when disabling a plugin for a sentry project, it will call to DB and remove the plugin's configuration of that project, no need to uninstall that module/plugin.
Then, when we re-enable that plugin, we can re-configure it, no use the old configuration which was configured before disabling.

**Comment by dcramer** [comment]
@swdream its not unreasonable (and not hard to do). Pretty easy task for someone looking to contribute, I dont see it being a huge priority internally.

**Comment by swdream** [comment]
@dcramer ok, thanks for your help :D
