### ISSUE TITLE
Record Issue ownership rules change in the audit logs

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#42285]
### Problem Statement

Currently, changes applied to Project Settings -> Issue owners are not recorded in audit logs (Organisation settings -> Audit log).

This makes hard to know when/who applied changes to settings. it 

### Solution Brainstorm

Implement logging for the issue ownership feature.

**Comment by JoshFerge** [comment]
I can confirm this has been added at some point in the past:<img width="1148" alt="Image" src="https://github.com/user-attachments/assets/347aee2c-1ae7-44ed-be6d-a868a56e7b81" />
