### ISSUE TITLE
Bug: Replays Index Page making duplicate requests

### ISSUE THREAD

**Issue by cmanallen** [getsentry/sentry#42299]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Visit /replays browse screen.

### Expected Result

A single request to the /replays API browse endpoint.

### Actual Result

Two requests are made.  Both are nearly identical.  The second request includes a duration filter.

<img width="840" alt="Screen Shot 2022-12-13 at 12 56 27 PM" src="https://user-images.githubusercontent.com/6018782/207421157-0057fc6f-7a77-4f08-88cf-e90c3df564d9.png">

**Comment by ryan953** [comment]
@cmanallen is this still an issue?

**Comment by ryan953** [comment]
This is fixed now as part of https://github.com/getsentry/sentry/pull/43998

If you type in `/organizations/MY_ORG/replays/` into the url bar you'll still see two requests made, but the first is cancelled by the browser, replaced with the request that includes `duration:>=5`.
