### ISSUE TITLE
Perf: When issue-list page is polling only request replay count for issues that do not yet have a count fetched (or the count is zero)

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#42310]
Re: performance/efficiency of the `useReplaysCount()` hook.

See idea and conversation: https://github.com/getsentry/sentry/pull/42242#issuecomment-1349711561

**Comment by realkosty** [comment]
Could this bug be related? 
1. Generated error that created brand new issue
2. Click on the new issue from Issues page
3. This is what I see immediately. ACTUAL: Replays (0) EXPECTED: Replays (1)
4. Replay clearly available below the fold
5. Navigate away, come back, refresh page - get Replays (1) as expected
<img width="309" alt="Screenshot 2022-12-22 at 2 29 54 PM" src="https://user-images.githubusercontent.com/490201/209238129-eff65415-a1ac-44bd-8644-c7b65a29c4f8.png">

**Comment by ryan953** [comment]
@realkosty i don't think what you're describing is the same thing -> that sounds like a bug (or caching).

**Comment by ryan953** [comment]
The performance is acceptable for this `useReplayCount()` react hook. Per-pageload, it will only fetch the count for id's that are new, once a count has been fetched we won't re-request it until the page is reloaded.
