### ISSUE TITLE
Replay: Free tier fails to load Trace tab

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#42439]
### Environment

SaaS (https://sentry.io/)

### Link

https://sentry.io/organizations/nugettrends/replays/spa:81e576a2b7f44f27aad788a7a495d2d6/?referrer=%2Forganizations%2F%3AorgId%2Freplays%2F&t_main=trace

### Steps to Reproduce

On a Free or Sponsored tier, loading Trace renders an error.

### Expected Result

Display the full trace.

Reasoning: When clicking on a See Trace in a transaction, the whole trace shows up even on a free tier.

Example on the same Sponsored org: https://sentry.io/organizations/nugettrends/performance/trace/bbcb3a9db5ec422ba6379a01ae6019b8/?pageEnd=2022-12-19T10%3A11%3A05.067&pageStart=2022-12-18T10%3A10%3A41.118

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/1633368/208461872-f1e5771f-1e5e-4948-85c3-171f98d28652.png">

### Actual Result

<img width="851" alt="image" src="https://user-images.githubusercontent.com/1633368/208461222-6d141b9f-68ac-4a81-b98f-bf3ba13cddf5.png">

API result: 400, ` "You cannot view events from multiple projects."`

Related to: https://github.com/getsentry/sentry/issues/35367

**Comment by ryan953** [comment]
See also https://github.com/getsentry/sentry/issues/40127
