### ISSUE TITLE
Bug: Do not display Replays CTA in Issue Details if Replays is already installed on a project

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#42448]
**Problem:**

Today, we display the Session Replay CTA under "Breadcrumbs" in Issue Details even when SR is already installed. 
We should not show this CTA when it's not actionable, like when we already have Replays on the project, or the platform isn't supported.

![Image](https://user-images.githubusercontent.com/77064737/208500738-318eb7e6-985e-4bfe-8508-27b79460df85.png)

**Solution:**

Only show Replays CTA for applicable projects **where replays are not installed.**

**Comment by ryan953** [comment]
> We should not show this CTA when it's not actionable, like when we already have Replays on the project, or the platform isn't supported.
> Only show Replays CTA for applicable projects where replays are not installed.

The existing code purports to support this ideal state:
https://github.com/getsentry/sentry/blob/3d02977307166aa68d3e772ad6e014af34281413/static/app/components/events/eventReplay/index.tsx#L29-L45

1. If the project does not support replay we show nothing: 
 - https://github.com/getsentry/sentry/blob/3d02977307166aa68d3e772ad6e014af34281413/static/app/components/events/eventReplay/index.tsx#L29-L31

2. If the project has never received a replay (and therefore, this event will not have a replay), show the onboarding:
 - https://github.com/getsentry/sentry/blob/3d02977307166aa68d3e772ad6e014af34281413/static/app/components/events/eventReplay/index.tsx#L33-L39

3. If the project has received a replay, but this event hasn't, then show nothing (things are setup, data is sampled here):
 - https://github.com/getsentry/sentry/blob/3d02977307166aa68d3e772ad6e014af34281413/static/app/components/events/eventReplay/index.tsx#L41-L43

4. If we've got a replayId then try to render that, it might not work though:
 - https://github.com/getsentry/sentry/blob/3d02977307166aa68d3e772ad6e014af34281413/static/app/components/events/eventReplay/index.tsx#L45-L54

**Comment by jas-kas** [comment]
Cannot repro this issue with where this was [first observed](https://sentry.io/organizations/nugettrends/issues/2104638359/?project=1266321). CTA may have only appeared due to caching.

Going to close this ticket and will re-open if another incidence of this is reported.
