### ISSUE TITLE
Update post process forwarder to  work with generic issues

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#42529]
We're currently sending generic events to snuba via eventstream. We also want to be able to schedule `post_process_group` via the [post process forwarder](https://github.com/getsentry/sentry/blob/5d006832f3fa640a6927bcbf38b41bbbcf3388fa/src/sentry/eventstream/kafka/postprocessworker.py#L94-L122).

This might just work as is - we will already grab the `group_id` and `is_new`, etc parameters from eventstream. If this does just work, then we need to just add an additional celery worker to process the `post_process_group_generic` queue.

Note that we don't want to use the list of `GroupState` objects here. That's specific to performance issues, and we'll probably phase it out after we move them over to the issue platform.

**Comment by rjo100** [comment]
Seems like adding the celery worker might have some thorns. Will check in tmrw about strategy with this.

**Comment by rjo100** [comment]
Will need to talk to ops still. Did we want the queue to be named `post_process_group_generic` or `post_process_issue_platform`? Or am I confusing celery and kafka queues?

**Comment by rjo100** [comment]
Well the event is `generic` and the issue is `error/profiling/performance/etc.` from the `platform` (and then there's the `occurrence` separately). So I would say `post_process_issue_platform`.

**Comment by rjo100** [comment]
https://getsentry.atlassian.net/browse/OPS-2798
