### ISSUE TITLE
Add a way to process generic events in `post_process_group`

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#42530]
We need to be able to handle platform issues in `post_process_group`. I think that all platform issues will be processed in the same way, so there's no need to add a new entry for every new `GroupCategory`.

There are two issues here:
 - We need be able to build the `PostProcessJob` for a generic event. Platform issues will only have one `group_id`, same as errors.
 - We need to add a pipeline that will handle all future `GroupCategory` types. Probably we should just have the generic pipeline be a fallback if an explicit pipeline isn't in place. That way we don't need to constantly add new entries into `GROUP_CATEGORY_POST_PROCESS_PIPELINE`, we can just do it if customization is needed for a given category.

**Comment by rjo100** [comment]
What methods exactly do we want in here

**Comment by wedamija** [comment]
> What methods exactly do we want in here

Let's make it the same as perf issues for now

**Comment by rjo100** [comment]
Nice, way ahead of you
