### ISSUE TITLE
Improve tests around event ingestion

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#42557]
When we create an event via ingesting an issue occurrence we don't validate that the fields in the event are what we expect. We should add in some tests here to improve that.

**Comment by rjo100** [comment]
https://github.com/getsentry/sentry/blob/c9af751306578054d93a8e52eae705c35e449040/src/sentry/snuba/json_schemas.py#L1-L63

**Comment by rjo100** [comment]
mainly for fields passed to event manager
