### ISSUE TITLE
Support merges/deletions for issue platform issues

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#42568]
When deleting issues in Sentry, we wrap them in these start/end deletion calls to eventstream.

https://github.com/getsentry/sentry/blob/c9af751306578054d93a8e52eae705c35e449040/src/sentry/eventstream/snuba.py#L197-L222

Same thing for merges and unmerges:
https://github.com/getsentry/sentry/blob/c9af751306578054d93a8e52eae705c35e449040/src/sentry/eventstream/snuba.py#L224-L273

We need to be able to support doing this for issues that use our generic dataset in Snuba. This might be as simple as just making sure these messages go to a different replacements topic. Maybe we just end up passing an event type or something along those lines to these function for use in deciding the topic?

**Comment by barkbarkimashark** [comment]
After discussing this with SNS team, we're de-prioritizing this for now.
