### ISSUE TITLE
Set up more Amplitude events around user behaviour on the Replay Index page

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#42563]
**Suggestions from Josh:**

ideas for events:

- paginate through list
- added search field
- did column sort
- time on page
- add this source to our Replay Details Views by Referrer chart

**From Ryan:**

> For the Replay Details Views by Referrer chart, the list page referrer is in there, but it looks filtered out on the dashboard. idk why (it’s the biggest source)
i could do these three easily enough:
> -paginate through list
> -added search field
> -did column sort
> 
> for the search box field/tag name would be the max i’d save anyway, because it could be too high cardinality otherwise.

**Comment by ryan953** [comment]
Events:
- [ ] Paginate next/prev -> will implement "Paginated Replay List"
- [ ] Do search
  - Already implemented as `"Search: Performed search"`, filter with `search_source=replay_index`
- [ ] Column sort -> will implement "Sorted Replay List"

**Comment by ryan953** [comment]
Added charts for list page:
1. time spent
2. conversions: sorting
3. conversions: paginating
4. conversions: searching
