### ISSUE TITLE
Issue details "All events" list is unusable on smaller screens

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#42570]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Go to the all events tab and expand a column. 

### Expected Result

- data to be readable without expanding a column
- pagination is always accessible 
- scroll horizontally works 

### Actual Result

- data is not readable without expanding a column
- pagination is inaccessible 
- unable to scroll horizontally

Additionally: would it be possible to select which columns are shown?

**Comment by philipp-tailor** [comment]
[Screen recording](https://app.birdeatsbug.com/sessions/ITY7BiCD4xrta3tCmRWgzXQNzNgmLkPU-jEHL1ooyXO-?devToolsHidden=true) demonstrating the issue.

**Comment by hubertdeng123** [comment]
Cleaning up Core UI labels since the team does not exist anymore, let me know if this is the right team to route to
