### ISSUE TITLE
Allow tagstore to query issue platform issues

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#42589]
Currently tagstore works with errors and performance issues. We want to allow it to query any issue platform related issues as well.

This might be the only place we need to touch:
https://github.com/getsentry/sentry/blob/c28d9b7abe002f1f18765dba36e4c273fd691276/src/sentry/tagstore/snuba/backend.py#L527-L536

Probably just need to change the dataset to be the issue platform one if not error/performance.

Should also make sure that we write tests that query the issue platform. There should be examples related to performance issues.

**Comment by ceorourke** [comment]
Blocked by https://github.com/getsentry/snuba/pull/3571 - someone else can pick this up if they want.
