### ISSUE TITLE
Enable issue platform deletions and merges in the UI and apis

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#42585]
Currently merges/deletions are only available for errors, and we've prevented users from using this functionality in the UI and APIs. Once we are able to support this functionality (https://github.com/getsentry/sentry/issues/42567, https://github.com/getsentry/sentry/issues/42568) we need to allow it in the API and show in the UI.

**Comment by barkbarkimashark** [comment]
De-prioritizing for now.
