### ISSUE TITLE
Ignore for periods of time should work with issue platform

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#42627]
Some ignores query snuba to get counts of events/distinct users. 

https://github.com/getsentry/sentry/blob/c28d9b7abe002f1f18765dba36e4c273fd691276/src/sentry/models/groupsnooze.py#L96-L101
https://github.com/getsentry/sentry/blob/c28d9b7abe002f1f18765dba36e4c273fd691276/src/sentry/models/groupsnooze.py#L117

This should hopefully just work after https://github.com/getsentry/sentry/issues/42626, but we should write tests to validate here.

**Comment by logicalbomb** [comment]
The work is complete, this issue wasn't closed at that time.
