### ISSUE TITLE
Chrome for windows is detected as Chrome for Android

### ISSUE THREAD

**Issue by websus** [getsentry/sentry#4263]
Hello there! I'm using Chrome version Version 53.0.2785.116 m (64-bit) on Windows 10 and in the issues section of my app it says that the errors come from a Nexus Phone LG using Chrome version 46.0.2490.
Can't be quite possible since I'm working local from my laptop.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
