### ISSUE TITLE
Bug: Unpredictable behaviour on Replay Details page for short replays (1s or less)

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#42632]
**Problem:**

For short replays, a customer has exhibited unusual behaviour on the Replay Details page once they hit play:

- Time bar purple highlight spills over
- No play indicator on timeline
- Time infinitely increases on video player

See customer details, screenshots and example replay [here](https://getsentry.atlassian.net/browse/FEEDBACK-1699).

**Solution Brainstorm:**

TBD.

**Comment by ryan953** [comment]
I'm thinking about reverting https://github.com/getsentry/sentry/commit/4fdbd4bccb3babb68bbdbeb42de7d05f7009a99b to help resolve this quicker

**Comment by billyvg** [comment]
Seems like a good short-term solution. But with the example replay, neither are "correct", but the frontend calculated duration is less broken.
