### ISSUE TITLE
The Projects page refers to a number of "Errors", but issues could be warnings or other types

### ISSUE THREAD

**Issue by glen-84** [getsentry/sentry#42659]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

View the Projects page.

![image](https://user-images.githubusercontent.com/261509/209559607-cb5a5b03-61a1-4f9f-a472-9a91fe253839.png)

### Expected Result

`Errors:` should likely be `Issues:`.

### Actual Result

The page refers to a number of "Errors", but issues could be warnings or other types as well.

**Comment by evanpurkhiser** [comment]
> The page refers to a number of "Errors", but issues could be warnings or other types as well

These actually are "error events", which may have a log level which could be of type `info`, or `warning` as you noted. But in Sentry terminology, it is actually correct to refer to all of those as Errors.

It's important to note, these are _not_ "Issues". An issue is a grouping of events that have the same fingerprint (this is what makes sentry so much more powerful than just logging).

A better word probably __would__ be `Events`, but a Transaction is also an Event, so we separate them into Errors and Transactions.

Another important note, in the future we likely will have more types of events than just errors and transactions
