### ISSUE TITLE
Can't find issues

### ISSUE THREAD

**Issue by YaYaPao** [getsentry/sentry#42654]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

21.6.3

### Steps to Reproduce

1. we bundle a Application with React Native, and init the Sentry SDK **sentry.javascript.browser@5.27.4**
2. Cannot collect some issues, but other SDK can do it correctly.

So these confusing me:
- should i upgrade the SDK version?
-  should i use broswer SDK in RN app?
- client env version(ios system etc.) will cause some events missed?

Have a great day, bro!

### Expected Result

Have all events reported correctly

### Actual Result

Some events/issues missed

**Comment by Kobby-Bawuah** [comment]
Hello @YaYaPao, could you try using the debug option seen [here](https://docs.sentry.io/platforms/react-native/configuration/options/#debug)? Let us know what the output of that was. Please also send a snippet from the SDK init code block.

**Comment by YaYaPao** [comment]
> 

Thanks for your kind advice, and this is the code snippet.

```js

const release = CustomizedOptions.uuid + '@' + CustomizedOptions.version
Sentry.init({
  dsn,
  release: release,
  dist: 'release',
  environment: CustomizedOptions.environment,
  integrations: [
    new RewriteFrames({
      iteratee: (frame) => {
        if (frame.filename) {
          frame.filename = frame.filename
            .replace(/^file:\/\//, '')
            .replace(/^address at /, '')
            .replace(/^.*\/[^.]+(\.app|CodePush|.*(?=\/))/, '')
          if (
            frame.filename !== '[native code]' &&
            frame.filename !== 'native'
          ) {
            if (
              CustomizedOptions.baseMoudleName &&
              CustomizedOptions.baseProxyURL &&
              frame.filename.indexOf(CustomizedOptions.baseMoudleName) != -1
            ) {
              frame.filename = CustomizedOptions.baseProxyURL
            } else if (CustomizedOptions.busiProxyURL) {
              frame.filename = CustomizedOptions.busiProxyURL
            }
          }
        }
        return frame
      },
    }),
  ],
  beforeSend(event, hint) {
    const { originalException } = hint || {}
    const { message } = originalException || {}
    sentryLog.addLog(CustomizedOptions, { msg: message })
    return event
  },
})
Sentry.setTag('platform', Platform.OS)


```

**Comment by Kobby-Bawuah** [comment]
Hello @YaYaPao, I am still waiting on the debug output to have an idea of what might be going on.

**Comment by YaYaPao** [comment]
> 

The issue does not reappear, and debug message indicates everything is fine. So i think this is a random accident, and i will close the issue.

Thanks bro.
