### ISSUE TITLE
[real-time] Resolving issues doesn't remove them from the issue list

### ISSUE THREAD

**Issue by glen-84** [getsentry/sentry#42657]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Enable real-time updates.
2. Resolve an issue.

### Expected Result

The issue is removed from the list, since the `is:unresolved` filter is active.

### Actual Result

The issue remains in the list.

**Comment by hubertdeng123** [comment]
Core UI team no longer exists, routing to Workflow. Let me know if this needs to be rerouted.

**Comment by MichaelSun48** [comment]
This no longer appears to be an issue based on my testing - feel free to reopen if anyone can reproduce this again
