### ISSUE TITLE
The returned data has a default value, but is for display(issue link)

### ISSUE THREAD

**Issue by coderfong-hub** [getsentry/sentry#42665]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/73768118/209693838-543c54a7-fe73-434b-8664-674131248ea0.png)
![image](https://user-images.githubusercontent.com/73768118/209693899-aba54b9b-18e4-497c-99ff-07c7065f8b3f.png)

### Expected Result

It should be presented as expected

### Actual Result

The returned data has a default value, but is for display

**Comment by kerenkhatiwada** [comment]
Can you please confirm, you are expecting to see the default project value populated in the drop down?

**Comment by evanpurkhiser** [comment]
Re-routing to @getsentry/ecosystem since this will be their area of expertise.

**Comment by coderfong-hub** [comment]
Is the problem solved?

**Comment by brianthi** [comment]
Hi @coderfong-hub, I'm not able to reproduce this issue. I think the best course of action here is for you to create a support ticket, https://help.sentry.io/, and our team there will be better equipped to help resolve your issue.
