### ISSUE TITLE
"There was an error loading a component." on "Release Details" page

### ISSUE THREAD

**Issue by maksimkurb** [getsentry/sentry#42664]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.11.0

### Link

(I'm using self-hosted Sentry)

Stacktrace of this issue: https://sentry.dev.onecell.ru/share/issue/dfeeeb307e8047b7a1eab41a8cb9466c/
JSON export of this issue from Sentry dashboard: https://gist.github.com/maksimkurb/6339e8136a7e6341e185a6c87b8ba2c0

### Steps to Reproduce

This is a duplicate of closed issue #39667, this problem is reproduced on the latest Sentry Hosted version.

1. Open the Releases tab on the sidebar
2. Open release
3. See loading spinners like this: 
![image](https://user-images.githubusercontent.com/1351924/209674205-b2c9ed38-c521-4e4e-81cb-fa67ef901a42.png)
4. Then I see an error on the whole page:
![image](https://user-images.githubusercontent.com/1351924/209674247-39da7c19-7f37-45b3-a896-bb1efd2e7d99.png)

P.S. A can upload Sentry Frontend 22.12.0 sourcemaps to our Sentry instance to improve this stacktrace readability, but I can't find them in the release distribution. Local builds give me another filenames of chunks. Can you send me Sentry Hosted 22.12.0 sourcemaps if it is possible?

P.S.S. I can provide more debug info if needed, please send me details on how I can improve this issue description.

### Expected Result

I can see specific release issues, can see graphs

### Actual Result

The whole page is broken with this error.

**Comment by scttcper** [comment]
Thanks for reporting, this was fixed in #42580
