### ISSUE TITLE
Search not returning results for e.g. "Resuqe::DirtyExit"

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#4269]
Given we have an exception with the following details:

```
Resque::DirtyExit
pid 39284 SIGKILL (signal 9)
```

Searching for "Resque::DirtyExit" brings up nothing. Searching for both Resque and DirtyExit work fine.

**Comment by tkaemming** [comment]
We fixed the quoted term behavior here (GH-4270, mentioned above.)

Otherwise, this tokenizes now to:

```
>>> from sentry.search.utils import tokenize_query
>>> tokenize_query("Resque::DirtyExit")
{'Resque': [':DirtyExit']}
```

It seems like we might want to warn (but not error) when a tag is specified that doesn't match anything in the database, but that seems like a separate task/issue than this one.
