### ISSUE TITLE
Performance landing page search not working as expected

### ISSUE THREAD

**Issue by rbisol** [getsentry/sentry#42692]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Issue1: 
1. Go to The performance page
2. A list of transactions will be shown based on the default criteria
3. In the search box, do not type anything and press enter.

Issue2:
1. One existing transaction (said `transaction1` is not listed on the page.
2. Searching for `transaction1` without changing filters finds the transaction.
3. Removing all search criteria (without pressing enter) results in all transactions shown on the page, including `transaction1`

The transaction is not "hidden" on another page because the list has only 6 transactions. 

### Expected Result

It is expected that all transactions matching the filters are listed on the page when you land on it. 

Pressing "enter" on an empty search box should not change the results listed on the page.

### Actual Result

I could not reproduce both issues on my account (i did not find any transaction that is not listed on the landing Performance page to reproduce Issue2).

Due to PII being involved on the repro video, I cannot add it to this ticket. Here is a [link to the internal ticket ](https://sentry.zendesk.com/agent/tickets/77108)where the video can be found.

**Comment by DominikB2014** [comment]
I put up a merged in a PR for issue 1, empty search should now reset the search! Reach out if there is anything unexpected still!

 I'll check with the team regrading issue 2

**Comment by DominikB2014** [comment]
@rbisol I just merged the PR to fix issue 2! It will be deployed later today, please reach out if there are any more issues!

**Comment by rbisol** [comment]
Just confirmed both issues are no longer reproducible.

**Comment by buckett** [comment]
Just confirming that on our account the issue appears fixed as well. Thanks.
