### ISSUE TITLE
Sentry UI Alerts do not show all alerts

### ISSUE THREAD

**Issue by martinkwan** [getsentry/sentry#42702]
### Environment

SaaS (https://sentry.io/)

### Version

On the Sentry UI website

### Steps to Reproduce

1. Navigate to Alerts tab of Sentry.io
2. Navigate through each page
3. Notice not all alert rules show up by the time the last page is reached.

### Expected Result

All alert rules should show up if I reach to the end of pagination

### Actual Result

Some alert rules are missing. This makes it hard to know which alert rule I may have missed if I am trying to go through each alert rule to edit each of them.

**Comment by souredoutlook** [comment]
Hey @martinkwan thanks for writing in!

Can you share a link the relevant view or your organization slug? If you'd like to share your organization ID anonymously you can simply provide a DSN from any projects of which you are a member.

Let me know so I can investigate this further

**Comment by scttcper** [comment]
Thanks for reporting this, we've added it to our backlog

**Comment by ceorourke** [comment]
I rewrote the alert paginator a few months ago, feel free to reopen if this is still occurring but it should be fixed.
