### ISSUE TITLE
Failed to execute 'matches' on 'Element': 'body *:not(style,script)' is not a valid selector.

### ISSUE THREAD

**Issue by iscekic** [getsentry/sentry#42700]
### Environment

SaaS (https://sentry.io/)

### Link

https://sentry.io/organizations/firesidechat/issues/3843166139/?project=6122809

### DSN

https://00cd68d0276b4de3a6f342955581ac69@o430938.ingest.sentry.io/6122809

### Steps to Reproduce

No specific steps to reproduce - looks like an error in `@sentry/replay`

### Expected Result

No error from sentry modules

### Actual Result

```
SyntaxError
Failed to execute 'matches' on 'Element': 'body *:not(style,script)' is not a valid selector.
```

**Comment by bruno-garcia** [comment]
This issue is a duplicate to: https://github.com/getsentry/sentry-javascript/issues/6618

It was fixed through: https://github.com/getsentry/sentry-javascript/pull/6637

Released on: https://github.com/getsentry/sentry-javascript/blob/master/CHANGELOG.md#7290
