### ISSUE TITLE
This is an Api question.

### ISSUE THREAD

**Issue by myeongseop-sofit** [getsentry/sentry#42710]
### Problem Statement

I wonder if there is an Api that receives log information such as transactions from the Performance tab.

**Comment by Fwang36** [comment]
Hey there,

[This](https://docs.sentry.io/api/discover/query-discover-events-in-table-format/) might be what you're looking for.  For example a query of `query=event.type:transaction` would pull all your transactions.

**Comment by Fwang36** [comment]
For another option if the above does not work for you,  we also have an undocumented discover api that you could try.  If you take a look at your network tab while browsing the discover tab, you can learn more about the syntax.

**Comment by shellmayr** [comment]
Closing - this issue is not actionable, just a question and no clear indication that something needs to be implemented.
