### ISSUE TITLE
Replay Feature: Expose window size/dimensions somewhere

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#42774]
We should include ~window size/resolution~ ~device type~ somewhere in the replay details ~(tags)~. This will likely need some work in the SDK/backend as well.

Closes FEEDBACK-55

https://sentry.io/organizations/sentry/issues/3849892876/?project=6356259&query=is%3Aunresolved+assigned%3A%23emerging-technology&referrer=issue-stream&statsPeriod=14d

[FEEDBACK-55]: https://getsentry.atlassian.net/browse/FEEDBACK-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Jesse-Box** [comment]
@billyvg @bruno-garcia 
To move this conversation along

I actually don't think people care in seeing the specific resolution of a replay, rather the specific device type.

When I say device type, it could be
* Viewport widths and orientations which correspond to arbitrary device classes, i.e. mobile, tablet, or desktop 
* Naming the specific device used during a replay, i.e. iPhone7, Samsung Galaxy Tab, Surface Pro

The extra benefit of knowing the device (or any proxy value for a device) can tell the user what input type they're using (touch or click).

**Comment by bruno-garcia** [comment]
> Naming the specific device used during a replay, i.e. iPhone7, Samsung Galaxy Tab, Surface Pro

I believe we send what's available already
On errors for example: 
![image](https://user-images.githubusercontent.com/1633368/218803900-35d2ca01-b187-425f-a9fd-b9172a15960f.png)

On Replay tags:
![image](https://user-images.githubusercontent.com/1633368/218804221-ccb4b522-a5fc-4889-8c8c-a7da121ac3f5.png)

> Viewport widths and orientations which correspond to arbitrary device classes, i.e. mobile, tablet, or desktop

The suggestion is to just say "mobile, desktop or tablet"? without the actual values

**Comment by Jesse-Box** [comment]
> The suggestion is to just say "mobile, desktop or tablet"? without the actual values
@bruno-garcia exactly.

We can expose the resolution perhaps on hover, but it's not the "primary" info we initially surface to the user

**Comment by billyvg** [comment]
Idea: have the icons in this bar: browser, device type (and resolution on hover for device type):

![image](https://user-images.githubusercontent.com/79684/219079671-3d11b736-a1ab-4330-ad06-26a39ef24bc7.png)

**Comment by billyvg** [comment]
We currently have the window size from rrweb breadcrumbs ("meta" event, `type: 4`), which gets used when setting the iframe dimensions. We could add this to hover of the browser icon, but this has not be a sought out feature, so I'm going to close it out.
