### ISSUE TITLE
Feature: Hovering over UI events timeline does not highlight DOM element in replay

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#42773]
For example, hovering over a click event in the mini timeline will not highlight the DOM el that was clicked in the replay. This behavior is present in our breadcrumbs.

Closes FEEDBACK-56

(https://sentry.io/organizations/sentry/issues/3849895693/?project=6356259&query=is%3Aunresolved+assigned%3A%23emerging-technology&referrer=issue-stream&statsPeriod=14d)

[FEEDBACK-56]: https://getsentry.atlassian.net/browse/FEEDBACK-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ryan953** [comment]
This is fixed now.

See screen shot where i'm hovering in the Timeline (tooltip is active) and the related DOM node is highlighted in the player.

![Image](https://github.com/getsentry/sentry/assets/187460/76e273bb-91e5-4495-9463-5da21e08028a)
