### ISSUE TITLE
[Cron Monitoring] Status doesn't update

### ISSUE THREAD

**Issue by d0niek** [getsentry/sentry#42771]
### Environment

SaaS (https://sentry.io/)

### Link

https://docs.sentry.io/product/crons/getting-started/

### Steps to Reproduce

Start cron monior with command

```bash
call_sentry() {
    if [[ "$SENTRY_DSN" == "" ]]; then
        echo "Sentry skip. SENTRY_DSN not set"

        return
    fi

    local monitorId="$1"

    if [[ "$monitorId" == "" ]]; then
        echo "\$monitorId is required"

        return
    fi

    local status="$2"

    if [[ "$status" != "in_progress"
        && "$status" != "error"
        && "$status" != "ok"
    ]]; then
        echo "Allowed values for \$status are: in_progress, ok, error"

        return
    fi

    local method='POST'
    local checkInId="$3"

    if [[ "$status" != "in_progress" ]]; then
        if [[ "$checkInId" == '' ]]; then
            echo "checked_in_id is required"

            return
        fi

        method='PUT'
    fi

    response="$(curl -Ls \
        -X "$method" \
        "https://sentry.io/api/0/monitors/$monitorId/checkins/$checkInId" \
        --header "Authorization: DSN $SENTRY_DSN" \
        --header 'Content-Type: application/json' \
        --data-raw "{\"status\": \"$status\"}")"

    echo "$(echo "$response" | awk -F'"' '{print $4}')"
}

checkInId="$(call_sentry "$monitor_id" 'in_progress')"

# job

call_sentry "$monitor_id" 'ok' "$checkInId"
```

starts monitoring 
![obraz](https://user-images.githubusercontent.com/9316891/210615604-15bd3be4-194f-4403-8866-201f2f197bf6.png)

but after second call, after job complete with `$checkInId` or even raw `curl` call doesn't update monitor status.

The same issue is described for [cli-sentry](https://docs.sentry.io/product/crons/troubleshooting/#cli-is-only-creating-in-progress-check-ins) but there is a problem with token permissions. For DSN we can't setup `project:write` permission.

### Expected Result

Update monitor job status to `ok` or 'error`.

### Actual Result

Doesn't update monitor job status.

**Comment by d0niek** [comment]
Yes, I did. But even when I call `curl` directly from cli:

```bash
curl -X POST \
    'https://sentry.io/api/0/monitors/$monitor_id/checkins/' \
    --header 'Authorization: DSN $dsn' \
    --header 'Content-Type: application/json' \
    --data-raw '{"status": "in_progress"}'
```

wait some time, copy `$check_in_id` from response and run `curl` from cli

```bash
curl -X PUT \
    'https://sentry.io/api/0/monitors/$monitor_id/checkins/$check_in_id' \
    --header 'Authorization: DSN $dsn' \
    --header 'Content-Type: application/json' \
    --data-raw '{"status": "ok"}'
```

status won't update.

**Comment by davidenwang** [comment]
Sorry for the late reply on this, try adding a `/` to the end of the URL in your second curl/http request 'https://sentry.io/api/0/monitors/$monitor_id/checkins/$check_in_id**/**'

**Comment by d0niek** [comment]
Works...

Thank you @davidenwang !
