### ISSUE TITLE
Auto create GitHub issues 

### ISSUE THREAD

**Issue by ghost** [getsentry/sentry#42803]
### Problem Statement

I would like the ability to create issues automatically from Sentry errors. Similarly to how do you have it set up with Jira. Also when the GitHub issue is closed it automatically resolves the Sentry issue.

**Comment by scttcper** [comment]
Thanks, I've added this to our team backlog

**Comment by Dhrumil-Sentry** [comment]
@lcsvcn This is available already, please see this changelog for more details: https://sentry.io/changelog/2023-11-6-automatically-create-issues-for-jira-server-and-github/

Similar to Jira, this feature is available for Business plan customers only

**Comment by cathteng** [comment]
Closed as it is already available
