### ISSUE TITLE
Replay: Don't hard-code '14d' inside useReplaysCount.tsx, it should be set depending on the context of the page or url that's being linked to

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#42818]

**Comment by ryan953** [comment]
Fixing the duration isn't so hard, but the header of the page isn't super intuitive:
<img width="1172" alt="SCR-20230105-n6y" src="https://user-images.githubusercontent.com/187460/210906666-433576d5-5d81-4834-b67e-dfb3a824c163.png">

1. the search box applies to the transactions, not the replays
2. searching does not (and should not, because of the info hierarchy on the page, search box is inside the tab) update the count

If we make the tab show a count of 1day, or 90days it'll be a different scale from what we show in the issues list (it's 14days there, and there's no time-range picker):
<img width="1181" alt="SCR-20230105-n8z" src="https://user-images.githubusercontent.com/187460/210906897-f7740038-efdf-4b75-89fa-ff5ca8d4f2d6.png">

My feeling is that this count should be the count of all replays that exist related to this transaction (same for error), so we should be doing a 90d time-range here. Then the searching and filtering applies to that list of records.

**Comment by ryan953** [comment]
Maybe what we should do is remove the filter/search buttons from this Txn > Replays tab. then the count will be a hard-coded 14d and that's it, the count will match the table.

Then on the Txn>All Events we should add a Replay column. For filtering/searching _transactions that have replays_ you could go to All Events and should have everything.
(this is what we've got setup in Issues>All Events and Issues>Replays)

**Comment by bruno-garcia** [comment]
> My feeling is that this count should be the count of all replays that exist related to this transaction (same for error), so we should be doing a 90d time-range here. Then the searching and filtering applies to that list of records.

I agree here, their replay is stored and available and related, so why not show the total count. Filtering happens to what's below and doesn't update the counter above (that's always 'total' count)

**Comment by ryan953** [comment]
The problem is that getting the 90d count every time is prohibitively expensive

**Comment by JoshFerge** [comment]
I would just remove the count. its not that important. if we really need 90d search and deem this is important, we can look at adding an index for replay_id

**Comment by ryan953** [comment]
cc @Jesse-Box

**Comment by billyvg** [comment]
> If we make the tab show a count of 1day, or 90days it'll be a different scale from what we show in the issues list (it's 14days there, and there's no time-range picker)

I think this is OK as long as the replays query is consistent with the page contents. In transactions summary, it's respective of the time selector. In issue details it's a bit iffier... in the tabs we have "Activity" and "user Feedback" which have counts for all time. The events/user count in the header I believe is all time. In the "Details" tab, we have charts for last 24 hrs and 30 days. I'd expect the Replays tab in Issue details to show all replays (90d).
