### ISSUE TITLE
Search by event id is broken 

### ISSUE THREAD

**Issue by maroux** [getsentry/sentry#4283]
Searching by event id no longer shows you the event details. Instead it opens the error group with the latest event showing. This is problematic because there's no other way to get info about the exact event.

**Comment by dcramer** [comment]
I wouldn't consider this broken, but its a nice feature to have. It is very possible this used to once forward to an event and doesn't anymore, but if so its been >1yr since that change was made. It's also important to know that we can't always forward to an event.
