### ISSUE TITLE
When an issue is resolved on Squadcast, it should automatically be resolved on Sentry

### ISSUE THREAD

**Issue by pelincetin** [getsentry/sentry#43019]
### Problem Statement

Hi, we use Sentry for monitoring and Squadcast for alerting. Currently, when I resolve an issue on Squadcast, it doesn't automatically resolve on Sentry. It would be nice if I didn't have to manually go and resolve in two separate places

**Comment by Dhrumil-Sentry** [comment]
Hi @pelincetin We don't maintain a Sentry Squadcast integration, I believe its built by the Squadcast team using Sentry webhooks. Please reach out to the squadcast for this- Sentry has APIs that can be used to resolve an issue once something is changed in a 3rd party tool
