### ISSUE TITLE
can`t get the right sourcemap data

### ISSUE THREAD

**Issue by Chengshihao1018** [getsentry/sentry#43014]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.10.0

### Steps to Reproduce

i have deployed sentry from sentry-helm(sentry version 22.10.0).and i have turned sourcemap flag to true
![image](https://user-images.githubusercontent.com/31720199/211452514-98827a30-25bc-4ca7-b851-4db36fd32b7f.png)

and in memcache value i use standalone architecture
![image](https://user-images.githubusercontent.com/31720199/211452636-0dc71caf-a761-45f8-8194-af73c8d358bd.png)

my service works fine
![Uploading image.png…]()

### Expected Result

it should get the sourcemap data like below
![image](https://user-images.githubusercontent.com/31720199/211452953-120c821d-5b59-4b81-81bc-754da312b9c5.png)

### Actual Result

i get this sourcemap data in my enviroment
![image](https://user-images.githubusercontent.com/31720199/211453074-ab8ce154-48b6-4973-a240-acde41b630b9.png)

**Comment by ethanhs** [comment]
Hi, unfortunately we don't support Sentry deployed via Kubernetes, only from the official docker-compose setup. If you experience a similar issue, or are able to debug the issue and believe it is not related to the kubernetes deployment, please let me know.

**Comment by Chengshihao1018** [comment]
> Hi, unfortunately we don't support Sentry deployed via Kubernetes, only from the official docker-compose setup. If you experience a similar issue, or are able to debug the issue and believe it is not related to the kubernetes deployment, please let me know.

OK,thank you.i think that maybe the upgrade cause this. i used to run sentry on version 20.9.0. in that version, helm delpoyment dosen`t have sourcemaps flag,and it can collect sourcemap defaultly.when upgrade to 22.10.0,it should turn this on and use memcache to collect this.sourcemap present mapping relation.the new data can work fine.but the old data which was collected at 20.9.0 may can`t find the right mapping relation,so that it shows uncorrect data.
