### ISSUE TITLE
[design] Replay onboarding illustration on Issue Details doesn't look good in dark mode

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#43049]
![Image](https://user-images.githubusercontent.com/187460/211665732-1edecab9-daaa-47eb-84a2-52248cee6042.png)

**Comment by Jesse-Box** [comment]
@ryan953 heres the updated file

![Image](https://user-images.githubusercontent.com/6508377/218424181-3fd6b6b2-aeb6-4eeb-bbf0-77bab48e0b32.svg)
