### ISSUE TITLE
"Don't store IP address" checkbox not consistently followed

### ISSUE THREAD

**Issue by abought** [getsentry/sentry#4313]
# Description

Sentry only partially respects the “Don’t store IP address” checkbox in the project settings page (`https://sentry.io/<orgname>/<project>/settings/`).
- The IP address is correctly removed from the `user` section of the error report page.
- However, the IP address is still being captured as part of the `sdk.clientIP` field of the record describing a specific event
- Although this field isn’t displayed in the UI, this field is displayed in the API response describing an event, so the information is shipped out to the client in a manner accessible from the front-end

Possibly related change:
https://github.com/getsentry/sentry/pull/3950/files#diff-5df200932e60fd9eaecc457a360ac726R350
# Steps to reproduce
1. Select "Don't store IP address" from the settings page for a sentry project. 
2. Send an error event
3. Inspect the UI ("user" and "sdk" sections), and see IP address is not present
4. Inspect the API response for the record (from network tab of browser dev tools on that page), and see IP address is part of the record

![screen shot 2016-10-10 at 12 38 52 pm](https://cloud.githubusercontent.com/assets/2957073/19246786/1146144a-8ef6-11e6-9c5c-39b2dcd24fbc.png)
# Expected result
- Selecting “Don’t store IP address” causes the IP address to be omitted consistently across all fields in the record
- Specifically, it would be omitted from the `sdk.clientIP` field.
# Actual result
- Despite turning on data scrubbing, the IP address is accessible to anyone who can see this record, because it is stored in more than one place
- UI omits IP address, but the information is still available to the front end via endpoints used to render the page.
  <img width="1032" alt="screen shot 2016-10-10 at 1 35 58 pm" src="https://cloud.githubusercontent.com/assets/2957073/19246804/2a74ddd4-8ef6-11e6-9253-edc9c9675906.png">
  <img width="1030" alt="screen shot 2016-10-10 at 1 36 49 pm" src="https://cloud.githubusercontent.com/assets/2957073/19246807/2d5cc32c-8ef6-11e6-9ba3-0e02d963f095.png">

Sample payload for `https://sentry.io/api/0/issues/<id>/events/latest/`

```
…
{     "user": {"id": "abought"},
    … 
    "sdk": { 
        "clientIP": “an.ip.address”,
         "version": "3.5.1",
         "name": "raven-js",
         "upstream": {"url": "https://docs.sentry.io/hosted/clients/javascript/", "isNewer": false, "name": "raven-js"} 
}
…

```
# Notes

I recognize that IP addresses are always captured at some level, and that some splitting of hairs is involved. Our use case for this feature is a client that will be conducting experiments via the web. They would like human-friendly error reports that do not unambiguously connect user + IP.  

This request is for a slightly improved version of sensitive data scrubbing, to more consistently follow the existing UI settings. We've found Sentry to be very helpful, and this would help to make it a reality for this project.
# Versions affected
- First seen on locally hosted Sentry 8.8.0, with the Raven.js sentry client 3.5.1
- Confirmed same issue in managed sentry.io, 8.10.0-dev0

**Comment by dcramer** [comment]
Hrm yeah we need to give this some thought. We capture clientIPs to aid in reporting, but I'm not sure how that affects privacy compliance policies in certain countries. I will say that the only way we will scrub this from the ``sdk`` attribute is if we need to for compliance purposes.

**Comment by abought** [comment]
Thanks.

As a middle ground: Sentry already offers a "Don't store IP address" setting, so having it stored (and visible) in another field is somewhat surprising.

Also possibly relevant- we were not able to remove the field via either the checkbox setting, or any of the other Security and privacy settings (eg sensitive fields) that we tried.

**Comment by dcramer** [comment]
@abought it does, but we still store IPs in logs, so that setting will never affect this. That setting is intended for "dont store PII", and this might qualify as that so we may need to consider extending it. The difference is this is an inbound IP hitting our server, and as far as I know that's safe to track, at least for a period of time. It's different than "this is an explicit user IP, not specifically the client sending the data".

To be clear, it's not expected that the current option should scrub this field, as nothing in this interface should be scrubbed today. We *dont* want people removing the data unless we have to for compliance reasons, as its stored explicitly to ensure we and our customers can track abuse or other similar concerns.

**Comment by fbrandel** [comment]
Would an "anonymized" IP make sense here? Something like 192.168.1.x where the last octet is not visible in the UI.

Personally I also was surprised seeing the IP in the UI even after checking the PII checkbox. And reading that the IP address is stored for some time may also be risky for some countries/companies.

Best or safest solution would be to have an option where the IP is anonymized right after hitting the server. Just like Google does it for Analytics: (https://support.google.com/analytics/answer/2763052?hl=en).

**Comment by dcramer** [comment]
More discussion here:

https://forum.sentry.io/t/client-ip-is-seen-even-with-prevent-storing-of-ip-addresses/576

The simple point here is that this is not purely intended to identify the user, but its intended to identify the SDK and thus we're absolutely not going to anonymize it. At the very most we'll likely hide it from the UI so only installation owners can see it.

**Comment by dcramer** [comment]
https://github.com/getsentry/sentry/pull/4674

**Comment by JohannesRudolph** [comment]
I'm wondering whether it might be sensible to just hash the IP on the client-side or server-side? The critical issue is the persistence of the IP, not its temporal use for rate limiting etc. From an operational perspective, you wouldn't loose the ability to enforce rate limits (at least on the application layer).

**Comment by ruud** [comment]
Any more news on this subject?
We cannot use Sentry in production if the client IP is stored ...

**Comment by dcramer** [comment]
I’m pretty sure we don’t return the IP to end users at this point so I’m closing this out. 

Yes we could hash IPs, but we’re likely not going to. We need the data for various reasons and our cloud service continues to expand on privacy law compliance.

**Comment by majoer** [comment]
I think this problem is highly relevant for all applications with users in the EU. The GDPR classifies an IP-address as digital personal data. This means that we MUST mask IP-addresses if we want to use them with analysis tools such as Sentry.

Otherwise, I believe we have to ask for user consent and provide means that abide by the "Right to be Forgotten", "Right to Access", etc..

Correct me if I'm wrong

Sources
https://eugdprcompliant.com/personal-data/
https://www.eugdpr.org/key-changes.html
https://www.datatilsynet.no/rettigheter-og-plikter/internett-og-apper/webanalyse/ (norwegian)

**Comment by dcramer** [comment]
@majoer yes you need to declare Sentry as a sub processor if your sending and storing PII.

Sentry stores IP addresses of clients (that isn’t changing) but doesn’t make them available to users. It’s for administrative purposes and is required under the business cases if GDPR.
