### ISSUE TITLE
python sentry uses wrong version of pyuwsgi

### ISSUE THREAD

**Issue by ObsidianDestroyer** [getsentry/sentry#43171]
### Environment

SaaS (https://sentry.io/)

### Version

22.9.0, 22.10.0, 22.11.0, 22.12.0

### Steps to Reproduce

1. `pip install poetry && poetry shell`
2. `poetry add "sentry==22.12.0"`

### Expected Result

Expected a success installation of **sentry**:
```
Using version 22.12.0 for sentry

Updating dependencies
Resolving dependencies... (1.3s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing sentry (22.12.0)
```

### Actual Result

But getting this output:
```
Updating dependencies
Resolving dependencies... (3.6s)

Because sentry (22.12.0) depends on pyuwsgi (2.0.20.0) which doesn't match any versions, sentry is forbidden.
So, because ton-aml-api depends on sentry (22.12.0), version solving failed.
```
The actual version of [pyuwsgi](https://pypi.org/project/pyuwsgi/#history) is 2.0.21 and version required for sentry is not listed in **pyuwsgi** repository (check the link).

**UPD:**
Tried to install version of sentry 22.7.0 and is successfully installed.

**Comment by asottile-sentry** [comment]
@ObsidianDestroyer are you meaning to install `sentry` (the self hosted sentry server) or are you actually looking for `sentry-sdk`?

`pyuwsgi` 2.0.20 *does exist* -- I suspect `poetry` is misleading you?

**Comment by JLuse** [comment]
Removing untriaged label, waiting for customer follow up as in progress

**Comment by ObsidianDestroyer** [comment]
> @ObsidianDestroyer are you meaning to install `sentry` (the self hosted sentry server) or are you actually looking for `sentry-sdk`?
> 
> `pyuwsgi` 2.0.20 _does exist_ -- I suspect `poetry` is misleading you?

Yea, right was my mistake, tried to install self hosted sentry. But any away, there is was a trailing zero in dependencies which fails installation.
