### ISSUE TITLE
Sentry bot account avatar has low contrast in GitHub dark mode

### ISSUE THREAD

**Issue by Turbo87** [getsentry/sentry#43180]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

enable dark mode theme on GitHub, then visit https://github.com/rust-lang/crates.io/issues/5646, which shows something like this:

<img width="287" alt="Bildschirmfoto 2023-01-12 um 18 33 08" src="https://user-images.githubusercontent.com/141300/212138803-8d4ad12d-6fe0-477c-b54d-0cae074d3887.png">

### Expected Result

The Sentry bot avatar should have better contrast, probably by adding a white background or a white stroke around the logo.

### Actual Result

see above :)

**Comment by chadwhitacre** [comment]
Phew, @getsantry is not affected. :-)

<img width="382" alt="Screen Shot 2023-01-13 at 2 19 54 PM" src="https://user-images.githubusercontent.com/134455/212401241-ea728fbf-503b-4e34-8047-3395c55acf6f.png">

**Comment by chadwhitacre** [comment]
Update with a non-transparent background. Thanks for the report @Turbo87! :-)

<img width="372" alt="Screen Shot 2023-01-13 at 2 26 10 PM" src="https://user-images.githubusercontent.com/134455/212402336-ac25398d-9e6f-4970-8e0d-e7a3c98a0c38.png">

<img width="371" alt="Screen Shot 2023-01-13 at 2 26 25 PM" src="https://user-images.githubusercontent.com/134455/212402334-46cfe850-8331-4e73-bd70-5177522dc73e.png">

**Comment by Turbo87** [comment]
Sweet, thanks! :)
