### ISSUE TITLE
Add a refresh button, or hide resolved issues

### ISSUE THREAD

**Issue by adamreisnz** [getsentry/sentry#4323]
When I mark issues as resolved they get a strike through. This is fine, but at times I want to refresh the issues list and hide everything I have resolved.

This is not currently possible, as even clicking on Issues again doesn't do anything.

So the only solution I have at the moment is to hard refresh the page, which is far from optimal.

**Comment by adambuczynski** [comment]
This is also a minor annoyance when I am looking at an issue, and mark it as resolved, and then want to go back to the overview. The "issues" button doesn't have a mouse over hover effect, so you can't really tell it's a link (even though it does work). It's these minor UI hiccups that make navigation in Sentry a bit cumbersome at times.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
