### ISSUE TITLE
Definitive guide to Sourcemaps and more with Sveltekit 🎉

### ISSUE THREAD

**Issue by alexbjorlig** [getsentry/sentry#43301]
### Problem Statement

[SvelteKit](https://kit.svelte.dev/) is awesome - and it's now version 1  (fresh out of beta)!

One of the great things about SvelteKit is the ability to abstract away the hosting provider. You write the same code, and then you can use an [adapter](https://kit.svelte.dev/docs/adapters) to deploy where you want. It could be

- Node.js platforms like Heroku
- Cloudflare edge functions
- Vercel
- Netlify

The good question now is: **How do we get source maps to Sentry**?
And follow-ups like:

- Should you setup both @sentry/browser @sentry/node?
- Is it wise to use both server/client error hooks?
- Where do you hook into the Sveltekit life-cycle to enrich the sentry scope on the server?
- What breadcrumbs do you recommend removing from the default setup?

It would be such a cool thing to solve ❤️ (Sveltekit actually mentions Sentry already in certain places in the [docs](https://kit.svelte.dev/docs/hooks#shared-hooks-handleerror)).

 

### Solution Brainstorm

I guess the first path to a more robust solution, would be documentation about how sourcemaps can be synced for the different adapters (if there is any change at all???)

Ultimately an integration with the Sentry CLI would be 🥷

Let me know what you think? - How do you sync source maps from a Sveltekit project?

Our team has not done it yet 🫣

**Comment by AbhiPrasad** [comment]
Hey @alexbjorlig great to see you excited around this! We're working on improving our support here by building a first class SDK for just SvelteKit (where everything should just work out of the box!): https://github.com/getsentry/sentry-javascript/issues/6692

See some of our experimental work here: https://github.com/getsentry/sentry-javascript/discussions/5838#discussioncomment-4591389

I know @Lms24 has been looking at sourcemaps, perhaps we can give some more insight here?

**Comment by alexbjorlig** [comment]
Hi @AbhiPrasad - that could be a possible solution.

But how do I know what the folder should be here?
```
// Specify the directory containing build artifacts
include: "./dist",
```

**Comment by AbhiPrasad** [comment]
From the SvelteKit docs, it seems to default to `.svelte-kit`? https://kit.svelte.dev/docs/configuration#outdir

**Comment by Lms24** [comment]
Hi @alexbjorlig thanks for opening this issue. As already mentioned by @AbhiPrasad, I took a look at source maps. There's probably room for improvement but I added a small section to our GH discussion with some preliminary instructions: https://github.com/getsentry/sentry-javascript/discussions/5838#discussioncomment-4696985

**Comment by AbhiPrasad** [comment]
Hey @alexbjorlig we decided we're going to use https://github.com/getsentry/sentry-javascript/issues/6692 to track our work, so closing this issue as a result. Please open issues in the JavaScript SDK repo if you have any more questions/concerns! Thanks again for reaching out.
