### ISSUE TITLE
Get rid of unnecessary "landing page" for Azure AD logins

### ISSUE THREAD

**Issue by cthwallis** [getsentry/sentry#43348]
### Problem Statement

With Okta, when I click on my tile within the Okta dashboard, im taken directly to the Sentry control panel.

When I configure Saml for Azure AD, using the Azure AD app and following the tutorial, I'm first taken to a landing page that asks me to click the "Login with Azure Active Directory"  button.  This should not be necessary if Okta can get around it.

### Solution Brainstorm

Modify your SAML integration with Azure AD to not require users to have to click this extra button.  My users expect when they click the Sentry tile in their myapps.microsoft.com dashboard that they will be taken directly into the Sentry control panel.

**Comment by leedongwei** [comment]
Thanks for the report! We have plans to update our authentication service to improve the UX. I'll keep this in mind when we are working on Azure AD.
