### ISSUE TITLE
Partially mute issues by tag

### ISSUE THREAD

**Issue by lucillebenoit** [getsentry/sentry#43366]
### Problem Statement

It would be very helpful to be able to partially mute an issue by tag.
 
For example: A merchant integrating with our SDK has a known bug which triggers a Sentry alert. We want to be able to mute the issue for this specific `merchant_id` but still be alerted if the issue occurs with another merchant. Other helpful cases could include muting issues by geography, language, device type, operating system, etc. It would be ideal to be able to achieve this without needing to change the fingerprint rules across all issues.

This [previously reported issue](https://github.com/getsentry/sentry/issues/5314) had a similar request.

**Comment by lucillebenoit** [comment]
Here is an example of our issue grouping settings:
```
error.type:* -> {{ default }}, {{ tags.environment }}
message:* -> {{ default }}, {{ tags.environment }}
error.type:example-issue tags.merchant_id:"example-merchant" -> example_issue_occurring_only_on_example_merchant
```

Ideally we would want to be able to mute `example-issue` only when the error is tagged with `example-merchant` but still be alerted if another merchant experiences that same issue.

**Comment by lucillebenoit** [comment]
If you tap **Ignore** on an issue, you are currently presented with three options: 

- For (period of time)
- Until this occurs again (number of times)
- Until this affects an additional (number of users)

I'm essentially suggesting that there be a fourth option where you can mute until a given tag on the issue is different than the current one (for example if `tags.merchant_id` != the tagged `merchant_id` in the current issue).

**Comment by lucillebenoit** [comment]
I'm still interested in this feature. Let me know if you need more information from me.

**Comment by scefali** [comment]
@lucillebenoit Can't you use issue alert filters to filter out as shown below?

<img width="838" alt="Screen Shot 2023-08-10 at 9 04 58 AM" src="https://github.com/getsentry/sentry/assets/8533851/35e30032-978f-4a41-96d6-0ecd6c0f1df6">

I'd think this would solve your use case.

**Comment by MichaelSun48** [comment]
Closing this out due to inactivity - feel free to reopen if anyone has the same request and @scefali's suggestion doesn't work.
