### ISSUE TITLE
Feature Request: Don't show animations if `prefers-reduced-motion` is turned on

### ISSUE THREAD

**Issue by todofixthis** [getsentry/sentry#43368]
### Problem Statement

Kia ora.   I note that when I go to Sentry's Issues view (https://sentry.io/organizations/\<my-org\>/issues/) and there are no issues, it plays an animation in the centre of the view (see attached screencap below).

I have my OS's 'prefer reduced motion' setting turned on, so I would prefer if Sentry displayed a static image for me instead of an animation.

More info:

* https://web.dev/prefers-reduced-motion/
* https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

Let me know if you have any questions and/or if there is any further information I can provide.

https://user-images.githubusercontent.com/202040/213050633-a18e8a68-fe06-4ec1-972e-22893d07db1c.mov

**Comment by Dhrumil-Sentry** [comment]
Hi @todofixthis This is something we're actively considering, Will update here once we have more information

**Comment by evanpurkhiser** [comment]
This is a pretty easy fix, @getsentry/core-ui can take this :)
