### ISSUE TITLE
Sanitizing path params in breadcrumbs ends up as "[Filtered]"

### ISSUE THREAD

**Issue by ri0ter** [getsentry/sentry#43374]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Sanitizing path params in breadcrumbs `to` and `from` params, causes breadcrumb values to appear as `"[Filtered]"`
I'm performing this parameter sanitization on the JS side. 
I do it by replacing path segments with `:<param>`. 
For e.g.: `/foo/bar/123-645-123` ends up as: `/foo/bar/:baz`. 
This approach works correctly when applying for the `request.URL` in the event (in `beforeSend` function).

### Expected Result

```
{
    from: /foo/bar/:some-param, 
    to: /baz/qux/:other-param
}
```

### Actual Result

```
{
    from: [Filtered], 
    to: [Filtered]
}
```

**Comment by olksdr** [comment]
@ri0ter , could you, please, provide the link to the event in Sentry? It will be easier for us to debug.
