### ISSUE TITLE
I got many "UnableToAcquireLock" issues in the Internal project.

### ISSUE THREAD

**Issue by lyd600lty** [getsentry/sentry#4337]
I deploy two servers use the same database and redis, following is the detail.

![image](https://cloud.githubusercontent.com/assets/2917899/19302948/2f90835a-9099-11e6-979d-8aef2b138fa2.png)

**Comment by tkaemming** [comment]
This happens when two digest scheduler jobs overlap. If this happens very infrequently, you can ignore it. If this happens often, you'll need to add capacity to your cluster. It can also happen if you are running multiple beat processes. Here is a similar issue: GH-3349.
