### ISSUE TITLE
Unmerging issues not working as expected after using the bulk mutate endpoint for merging

### ISSUE THREAD

**Issue by stellaatsentry** [getsentry/sentry#43378]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

The customer tried to use the [Bulk Mutate a List of Issues](https://docs.sentry.io/api/events/bulk-mutate-a-list-of-issues/) endpoint to merge two issues. Here's a snippet of their actual code in TypeScript, where this.request is done through axios.

```
async mergeIssues(sentry_issue_ids: string[]): Promise<string | null> {
const url = `/projects/${SENTRY_ORG_NAME}/${SENTRY_PROJECT_SLUG}/issues/`;
const data = { merge: true };
const params = { id: sentry_issue_ids };
const response = await this.request({ method: "put", params, data, url });
const parentId = response.data?.merge?.parent;
return parentId || null;
}
```
This returned a new parent issue ID `X` into which all existing issues of that project were merged.
Customer then tried to unmerge the issues by opening issue `X`, going to the Merged Issues tab, selecting the listed hashes and clicking Unmerge.

### Expected Result

1. The API endpoint call should have merged only the two issues from the two provided issues IDs
2. Unmerging the merged issues should separate them into their own issues

### Actual Result

1. The api call ended up merging all the issues in the project together into the new issue with ID `X`.

2. When trying to unmerge, some issues cannot be unmerged.
In another example regarding this problem, event `A` had hash `123` inside the Merged issues tab of issue `X`. After unmerging this hash, it disappeared from the merged issues tab of issue `X`. However, when accessing event `A`, it now has two hashes, `456` and `789`, neither of which appear in the merged issues tab of issue `X`, yet, event `A`'s URL has the issue ID of `X`.

Further details are described in the internal ticket due to PII.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1714) by [Unito](https://www.unito.io)

**Comment by armenzg** [comment]
@stellaatsentry could we follow up in Slack?
Could you please provide the link to the ticket on #discuss-workflow?

The docs say:
> It is optional only if a status is mutated in which case an implicit update all is assumed.

Since no `status` is defined in their code, it assumes all issues need to be updated.

For "When trying to unmerge,..." I will need links to check what you mean.
