### ISSUE TITLE
Sentry 8.9.0: Sentry.routes is not a function

### ISSUE THREAD

**Issue by Leroygirl** [getsentry/sentry#4338]
Hello!
I'm using Sentry 8.9.0 and everything seems to be ok except the javascript in Sentry web interface.
After successful login I got this sentence on the screen "Please wait while we load an obnoxious amount of JavaScript.You may need to disable adblocking extensions to load Sentry." and nothing else.
In my web console I see this:
vendor.js:67Uncaught TypeError: Sentry.routes is not a function(anonymous function) @ (index):92r @ vendor.js:67l @ vendor.js:24fireWith @ vendor.js:24ready @ vendor.js:24a @ vendor.js:14
Failed to parse SourceMap: http://sentry.supl.biz/static/sentry/dist/locale/ru.js.map

Please, tell me what I did wrong? With previous Sentry versions everything was ok :(
Thanks!

**Comment by dcramer** [comment]
It sounds like static assets are missing. I can't explain why this would be, and we should try to compile them if they're not present. I would take a look at our install guide and make sure you're following the directions and using the latest version of pip.

**Comment by yedpodtrzitko** [comment]
@Leroygirl you have to run `sentry django collectstatic` just after running `sentry upgrade`

**Comment by cash2910** [comment]
@yedpodtrzitko won't work ...
