### ISSUE TITLE
Assertion Error: Group must belong to Project

### ISSUE THREAD

**Issue by allo-** [getsentry/sentry#4341]
I got this "Internal Error" from my sentry installation. I do not know what triggers this. It were already 97 events in one hour, then it stopped (according to the sentry report).

```
AssertionError: Group must belong to Project
  File "celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "sentry/tasks/base.py", line 54, in _wrapped
    result = func(*args, **kwargs)
  File "sentry/tasks/digests.py", line 65, in deliver_digest
    digest = build_digest(project, records)
  File "sentry/digests/notifications.py", line 205, in build_digest
    state = attach_state(**state)
  File "sentry/digests/notifications.py", line 78, in attach_state
    assert group.project_id == project.id, 'Group must belong to Project'
```

python 2.7.9
sentry 8.8.0

**Comment by tkaemming** [comment]
There's no way for this to possibly happen under normal operation, which is why it is causing an error.

Are you running two different Sentry installations sharing a Redis cluster, or have you tried to reinstall Sentry and configured it with a Redis server that previously ran it? Did you manually update rows in the `sentry_groupedmessage` and change the `project_id` field?

This will eventually "resolve" itself by virtue of the invalid data expiring, but it's symptomatic of a different issue that may or may not have led to further data corruption.

**Comment by allo-** [comment]
Nothing of this. Default installation following the docs, no fancy settings, no custom modules or similar. No reinstallation, etc.

The only experimental bit is the activated support for CSP-Reports.

I reported this as bug here, because i guess an assert line should be a "this should never happens" condition, which indicates a missing check with proper error message.

Additional possible useful data:

    args = ['mail:p:2', 1476278596.126981]

**Comment by tkaemming** [comment]
This issue should also have been logged to the Sentry Internal project in your installation. Were the values of `project` and `group` in the last frame logged?

**Comment by allo-** [comment]
I got it from the internal project.

No project or group logged, just a ``task_id`` and the cmdline
``['/home/django/sentry/bin/sentry', 'run', 'worker']``

**Comment by allo-** [comment]
Ah wait, i see i can unfold more on the stacktrace. (Why isn't there a "raw" option which contains everything?)

It actually belongs to the Project where i collect the CSP violations:

    'groups': {
    57: <Group at 0x7f36fd627a50: id=57L, project_id=2L>,
    58: <Group at 0x7f36fd627ad0: id=58L, project_id=None>,
    60: <Group at 0x7f36fd627b50: id=60L, project_id=2L>},
    'project': <Project at 0x7f36fd66fe90: id=2L, team_id=1L, name=u'CSP violations', slug=u'csp-violations'>, 

I guess the group 58 is the problem, because it has ``project_id=None``?

**Comment by tkaemming** [comment]
> I guess the group 58 is the problem, because it has `project_id=None`?

Yep, that'd cause this. I don't think this is an issue with digest notifications (the conclusion I jumped to earlier, sorry), but it seems like some other part of the system recorded bad data. If you run this in `sentry shell`, do you still get "None"?

```python
from sentry.models import Group              
repr(Group.objects.get(id=58L).project_id)
```

**Comment by allo-** [comment]
Yes, it is 'None'.

What can be possible causes? It seems it happened only for one hour yesterday 97 times, then it stopped.

When i try to open Issue 58 by url, i get another issue:

    AttributeError: 'NoneType' object has no attribute 'organization'

Seems like there is more broken on this record.

**Comment by tkaemming** [comment]
> What can be possible causes?

Not sure, honestly — something went wrong when the record was created that prevented the `project` field from being filled in correctly. This is what led to the failing assertion when trying to send digest notifications, as well as the issue when viewing the URL. Was anything else logged in the Internal project around the time the issue was created?

**Comment by allo-** [comment]
Only the assertion error and when i try to access the issue by building the url with the id

    AttributeError: 'NoneType' object has no attribute 'organization'
      File "sentry/api/base.py", line 86, in handle_exception
        return super(Endpoint, self).handle_exception(exc)
      File "sentry/api/base.py", line 161, in dispatch
        (args, kwargs) = self.convert_args(request, *args, **kwargs)
      File "sentry/api/bases/group.py", line 48, in convert_args
        self.check_object_permissions(request, group)
      File "rest_framework/views.py", line 284, in check_object_permissions
        if not permission.has_object_permission(request, self, obj):
      File "sentry/api/bases/group.py", line 23, in has_object_permission
        request, view, group.project)
      File "sentry/api/bases/project.py", line 31, in has_object_permission
        request.access = access.from_request(request, project.organization)

which has ``project is None``

It is possible, that i deleted it (via the web ui). And i am not so sure about the project it should belong to. I definitely did not mess with anything not reachable via the web ui.

**Comment by DenisBY** [comment]
I have same problem. @allo- did you fix it?

**Comment by artemkaint** [comment]
Have the same exception sentry 8.12

http://clip2net.com/s/3GniFgv

**Comment by mattrobenolt** [comment]
We have absolutely no real idea how this has happened, but at this point, since the Groups don't have Projects attached to them, you should be able to just delete them to get rid of the error by opening up `sentry shell` and doing this:

```python
from sentry.models import Group
for g in Group.objects.filter(project_id__isnull=True):
  g.delete()
```

We have not seen this issue on sentry.io so it's unclear how it's possible to have gotten into this state. :(

**Comment by mattrobenolt** [comment]
Rather, this is probably a bit safer all around:

```python
from sentry.models import Group
from sentry.tasks.deletion import delete_group
for g in Group.objects.filter(project_id__isnull=True):
  delete_group(g.id)
```

**Comment by allo-** [comment]
@DenisBY I have no idea what's the problem.
@mattrobenolt The only thing i can say is, that my installation has only a few projects, a few issues and no advanced configuration. It happend when i was merely testing without doing anything fancy.

**Comment by allo-** [comment]
Happened another time when catching a CSP violation. The logged violation has an error attached:

    There was 1 error encountered while processing this event
    
        Discarded invalid value for parameter 'tags' Collapse
    
        {
          "name": "tags",
          "value": [
            "blocked-uri",
            "https://camo.githubusercontent.com/e7bbb0521b397edbd5fe43e7f760759336b5e05f/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677265656e5f3030373230302e706e67"
          ]
        }

**Comment by alexandrul** [comment]
Encountered on a clean install of Sentry 8.14.1, the invalid group was:
`(model='GroupRelease' group_id=1033L)`

**Comment by mbudde** [comment]
I have gotten this error after having merged a bunch of groups (5636 and 5637 were merged into 5591):
```
event_counts:   { 5591: 81, 5636: 2, 5637: 2 }
id:             5636
group:          <Group at 0x7fb45a2907d0: id=5636L, project_id=None>
groups:         {
                    5591: <Group at 0x7fb45a2908d0: id=5591L, project_id=3L>,
                    5636: <Group at 0x7fb45a2907d0: id=5636L, project_id=None>,
                    5637: <Group at 0x7fb45a290850: id=5637L, project_id=None>
                }
project:        <Project at 0x7fb459ea5f10: id=3L, team_id=1L, name=u'Backend', slug=u'backend'>
```
Sentry 8.14.1

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
