### ISSUE TITLE
transaction.status:ok returns nothing and transaction.status:unknown includes events with status ok

### ISSUE THREAD

**Issue by stellaatsentry** [getsentry/sentry#43428]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. In the performance tab, pick a transaction and open its summary
2. Search for `transaction.status:ok`
3. Search for `transaction.status:unknown`
4. Open one event
5. Open the event's JSON

### Expected Result

Each search filter should return the transactions with the corresponding status.

### Actual Result

Searching by `transaction.status:ok` returns nothing. 

When searching for `transaction.status:unknown` and opening an event, the status briefly appears as `unknown` in the web UI before turning into `ok`. When opening that event's JSON, the status is registered as `unknown`.

https://user-images.githubusercontent.com/81985895/213460443-07ebcd56-7364-4989-8758-f53047a306eb.mov

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1718) by [Unito](https://www.unito.io)

**Comment by wmak** [comment]
With the video posted, the org doesn't have any transactions with the `ok` status (eg. see this discover result https://sentry.io/organizations/dragonfruit-dev/discover/results/?field=transaction.status&field=count%28%29&name=%2F&project=4504179109068800&query=transaction.op%3Apageload+event.type%3Atransaction+transaction%3A%2F&sort=-transaction.status&statsPeriod=30d&yAxis=count%28%29)

There is an issue here where the Event details is showing the incorrect status, the transaction you're opening has the status unknown but we're showing `ok` when its actually unknown.

**Comment by stellaatsentry** [comment]
@wmak, thank you for looking into this, yes the primary concern is that transactions with status unknown are showing with status ok.

**Comment by gggritso** [comment]
This is alive!
