### ISSUE TITLE
[Alert Rule Editor] Missing Text for "show tags" in Slack Alert

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry#43442]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Edit an existing alert rule
2. Observe that the prompt is missing a description for the 4th field (which should prompt the user to input which tags they wish to show in the alert).

![slack rule](https://user-images.githubusercontent.com/76002357/213526193-c23798fb-22b8-4866-8755-fa5385b817dd.png)

### Expected Result

Prompt users to input tags to be shown in Slack Alert

### Actual Result

See attached screenshot.

**Comment by scttcper** [comment]
this was resolved in #43490 and #43495
