### ISSUE TITLE
Code Mappings tab is missing in Gitlab integration

### ISSUE THREAD

**Issue by Zaratusa** [getsentry/sentry#43452]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.1.0

### Steps to Reproduce

1. Go to Gitlab integration
2. Click the `configurations` tab
3. Press `configure`
4. Note the missing `Code Mappings` tab

### Expected Result

Following this [stack trace linking tutorial](https://docs.sentry.io/product/integrations/source-code-mgmt/gitlab/#stack-trace-linking) the `Code Mappings` tab should exist.

### Actual Result

The `Code Mappings` tab is missing.

**Comment by scttcper** [comment]
Try enabling the `organizations:integrations-stacktrace-link` flag in your feature flags

**Comment by Zaratusa** [comment]
I've added it to the `sentry.conf.py` and restarted it with `docker-compose`, but it's still not visible. In the environment config on the website the `SENTRY_FEATURES` are just shown as `****************`. Is there any way to verify the config change had an effect?

**Comment by Zaratusa** [comment]
After waiting a few minutes, the tab appeared. Thanks!
