### ISSUE TITLE
Additional sensitive fields not respected

### ISSUE THREAD

**Issue by alexmic** [getsentry/sentry#4345]
I have a POST request with a JSON body `{"fields": [list of sensitive fields]}`. I have added `fields` in the "Additional sensitive fields" box but I can still see their values when a new event is received. Am I doing something wrong or is this a bug?

**Comment by dcramer** [comment]
@alexmic it's possible that we're not parsing it correctly, or it was added after the event was stored. Is this on-premise? If so you could you get us a redacted example payload and we'll confirm via the test suite. If it's on sentry.io, can you toss me a link (either here, or to support@).

**Comment by alexmic** [comment]
Hey @dcramer, it's on sentry.io. I added the fields after I saw (and deleted) the first event. All subsequent events after that were not filtered. Here's an example json body:
```
{
  institution: ***, 
  login_fields: [
    {
       name: ***, 
       value: ***
    }, 
    {
       name: ***, 
       value: ***
    }, 
    {
       name: ***, 
       value: ***
    }
  ]
}
```

I want the `login_fields` key to be scrubbed from the body and any other place it pops up as a variable in the stack trace. Is that possible or do I have to scrub them on my side?

**Comment by dcramer** [comment]
@alexmic I need to see the sample event to confirm that its actually JSON and not a raw string. We have a lot of test cases around this and I cant find any way that added "login_fields" to the list of scrubbed fields would possibly not scrub it. We both look at the key name and the value (using a CONTAINS match).

**Comment by alexmic** [comment]
@dcramer emailed

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
