### ISSUE TITLE
Easily understand a project's platform throughout the Sentry UI

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry#43456]
### Problem Statement

Organizations using Sentry often use many different SDKs. If one is not familiar with the icon representing a particular language/framework, it is difficult to tell which SDK a project uses.

Although it is possible to navigate to a project's Settings page to see the platform, this takes a number of clicks and requires leaving the current page. However, if a user has never encountered a particular icon before, and they aren't aware that the project settings page shows the platform type, there is no straightforward way for them to figure out the platform.

**So: on any given page that displays project icons (Stats, Issues, Projects, etc.), the request is to have a clear way, beyond just the existing icon, to identify a project's platform.**

Some other notes:

- React and React Native have the same icon, so it can be difficult to tell whether a project is React or RN without navigating to the project's settings page.
- [Minidumps, Unity, and Serverless SDKs](https://sentry.io/platforms/) all seem to have the same icon, leading to the same kind of confusion.

The confusion of duplicate icons increases the value of showing the platform type in text.

### Solution Brainstorm

Having a tooltip that appears with the name of the platform when you hover over its icon could be a simple solution to this problem.

<img width="1469" alt="identify-platform" src="https://user-images.githubusercontent.com/12092849/213556335-45fc2ae2-edae-4487-a183-d3069101e8b6.png">

**Comment by quickstark** [comment]
+ 1
