### ISSUE TITLE
Truncated module name in stack trace view hides information

### ISSUE THREAD

**Issue by sklibanov312** [getsentry/sentry#43465]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.12.0

### Steps to Reproduce

1. Install self-hosted sentry using the normal docker-compose instructions
2. Create a 'native' project
3. Submit an event with an exception and a stack trace. The stack trace frames part of the exception must have data similar to the following, consistent with a minimal implementation of https://develop.sentry.dev/sdk/event-payloads/stacktrace/ :

```
{"package": "UnrealEditor", "function": "FEngineLoop::Tick()"}, 
{"package": "UnrealEditor_ApplicationCore", "function": "FWindowsPlatformApplicationMisc::PumpMessages()"}
```

So, just a package and a function and nothing else. In spite of Unreal in the text, Sentry's stock Unreal integration is not involved here, this is custom code implementing a Sentry event upload.

### Expected Result

In the web browser, looking at the successfully reported event in Sentry, expect to see the full package name, like this:

| UnrealEditor | FEngineLoop::Tick() |
| UnrealEditor_ApplicationCore | FWindowsPlatformApplicationMisc::PumpMessages() |

### Actual Result

Actually see a truncated package name, hiding the informative part of the name.

| UnrealEditor | FEngineLoop::Tick() |
| UnrealEditor_... | FWindowsPlatformApplicationMisc::PumpMessages() |

Unreal has many dozens of DLLs, the names of which are important to be able to ascertain at a glance from the callstack view.

Here's a picture:
![image](https://user-images.githubusercontent.com/111643872/213576446-75d85473-1aa1-42a0-b030-7644d97671dd.png)

Is there a way to control the number of characters or pixel width of the package column? The full name is available via tooltip, but that's not user friendly.

**Comment by sklibanov312** [comment]
Making the window wider unfortunately doesn't help at all. It's just a truncated package, then function, then a lot of empty space, then the right margin...

**Comment by RaduW** [comment]
Thanks for bringing this to our attention, we are looking at it right now and we'll try to figure out a way to
display the stacktrace labels in a more usable way.

**Comment by sklibanov312** [comment]
Just in case, here's the longest several modules that (our copy of) Unreal has:

```
UnrealEditor-MeshModelingToolsEditorOnlyExp
UnrealEditor-AbilitySystemGameFeatureActions
UnrealEditor-AppleImageUtilsBlueprintSupport
UnrealEditor-EditorInteractiveToolsFramework
UnrealEditor-LocalizationCommandletExecution
UnrealEditor-MovieRenderPipelineRenderPasses
UnrealEditor-PIEPreviewDeviceProfileSelector
UnrealEditor-AnimationLocomotionLibraryEditor
UnrealEditor-GeometryFlowMeshProcessingEditor
UnrealEditor-VisualStudioCodeSourceCodeAccess
UnrealEditor-AnimationLocomotionLibraryRuntime
UnrealEditor-CustomizableSequencerTracksEditor
```

The longest is almost 50 characters.

**Comment by RaduW** [comment]
Thanks, our team is looking into it, we need to find a way to be able to display useful information so the people can identify the modules but at the same time we have constraints on the available space so we need to find something that works for everybody.

**Comment by priscilawebdev** [comment]
@sklibanov312 thanks for bringing this up 🙏 We just rolled out several small improvements to the stack trace of native events and now you shall be able to see the full package name as we are no longer truncating it. Give it a look and let us know what you think 🙂
