### ISSUE TITLE
Customer Control & Choice

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#43489]
Taken from https://www.notion.so/sentry/Issue-Platform-Overview-b5799988da494f11a435479ffb539391#0b44d0338d154d57ba0b05504cff48b4

Provide Sentry customers with a way to disable specific issue types and/or specific categories of issues. Maybe some kind of table like `OrganizationGroupTypeConfig` or whatever, that allows you to disable specific issue types. Could potentially be per project too?

Maybe even allow bulk disabling of a whole category (including new types in that category)

**Comment by rjo100** [comment]
Would this potentially be a UI setting? Or do we want to block it further up the pipeline to avoid event limits etc.

**Comment by wedamija** [comment]
Yeah, I think probably just UI. That way, if they decide to turn it back on then everything is still there. Also gives us the opportunity to allow this setting to be at the user level at some point.
