### ISSUE TITLE
Policy Layer

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#43488]
Taken from https://www.notion.so/sentry/Issue-Platform-Overview-b5799988da494f11a435479ffb539391#cb14300a1a4d4edba34465056bccdfbc

Basic protections against abuse/runaway detectors. Some of these might be customizable by the vertical teams. Things like
    - Rate limiting per project
    - Only creating an issue after an occurrence is seen x times
    - Provide ways for vertical teams to try out experimental new issue types without accidentally spamming customers
    - Release new issue types to specific customers: EA, specific orgs, etc.
    - In the future: Ranking based on real user interactions

One way I could see this working is that as part of the problems that are passed to us we have a policy_config key. It might look like

```
{
    “min_times_seen”: 3, # Only create an issue once this is seen at least this many times
    “ea_only”: True,  # restrict to EA orgs 
    “organizations”: [”sentry”], # Limit to specific orgs
    …
}
```
That kind of config would allow verticals to run stable existing detections alongside new experimental ones.

This config would probably be configured into the `GroupType` table.

**Comment by rjo100** [comment]
I think we need `min_times_seen` and `time_period`.

Should `organizations` be ones we are enabling the detector for or ones we're adding noise reduction for? I feel like noise reduction should be the default.

**Comment by wedamija** [comment]
> I think we need `min_times_seen` and `time_period`.
Right now this is just an absolute value without a time period, but we could change that if we think it's helpful.

> Should `organizations` be ones we are enabling the detector for or ones we're adding noise reduction for? I feel like noise reduction should be the default.

I was thinking that the list of orgs is a list of places to release to. It could make sense to separate the keys more clearly as well, not sure what our actual structure would look like here.

**Comment by rjo100** [comment]
Right now we have various levels of control over new event and issue types.

Ingestion + detectors:
- Event type + category must be pre-registered with monolith codebase
- Detector must be running in SDK

Settings values:
- Org level - Enable the `organizations:` flag in `server.py`, generally used at the issue `category` level
- Project level - `per_project_rate` sample
- Event manager level - noise reduction for issue `type`
    - \# of events per 24 hours rolling window

In conjunction with https://github.com/getsentry/sentry/issues/43484, we'll add more settings that can help reduce noise during rollouts of new detectors and help control customer impact.

At the event manager level, we'll add more settings to support more granular configs:
- Settings per specific org, per EA org, and default all orgs
- Ability to specify # of events over XX amount of time period
- Ability to update values in concert or independently with the event type registry
- Appropriate level of backend database caching so as not to incur significant overhead
- Metrics to ensure data-driven decision making about next steps & rollout

**Comment by rjo100** [comment]
I think from a data level that will look more like

```
"organizations":
   {"sentry.io": NoiseConfig},
"early_access": NoiseConfig,
"default": NoiseConfig
```
```
NoiseConfig:
{
    “min_times_seen”: 3, # Only create an issue once this is seen at least this many times
    "time_span": 86400, # time to keep the key in the cache
    …
}

**Comment by rjo100** [comment]
This will require 2 main pillars of work:
- Setting up the system to interact with `event_manager` + `issue types` database
- Making sure the backend is efficient and ready to handle load
