### ISSUE TITLE
Replay: Include replay setup inside in-product 'new project' wizard

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#43502]
### Problem Statement

Currently if you create a new JavaScript project in Sentry, the onboarding wizard doesn't have any reference of Session Replay.
Once the product is generally available, we can help customers onboard with Session Replay by getting them up and running from the initial Sentry SDK configuration.

### Solution Brainstorm

Add Replay to the onboarding wizard. Be aware that pushing this without being clear about what this means can cause users to be disappointed. That happened a few times with Performance since we add 100% sample rate with a large comment above. Developers can miss that comment and simply copy paste.

Ideally a flow that's very clear what the side effect of the change. There's an initiative going on to change Sentry's onboarding process:
* https://github.com/getsentry/sentry/pull/42550

**Comment by ryan953** [comment]
This is done for supported plans.
