### ISSUE TITLE
No SCM repos displayed in integration config - pagination bug

### ISSUE THREAD

**Issue by realkosty** [getsentry/sentry#43514]
### Environment

SaaS (https://sentry.io/)

### Link

https://sentry.io/settings/testorg-az/integrations/github/13712/

### Steps to Reproduce

1. Go to Settings -> Integrations -> GitHub -> Configurations -> click "Configure" next to "sentry-demos" -> look at "Repositories" tab

This integration has many repositories configured, stack trace linking is working, etc.

### Expected Result

Repositories tab shows all repositories

### Actual Result

Repository tab is **seemingly empty** (placeholder text: _Sentry is better with commit data
Add a repository to begin tracking_)

However: on the bottom-right there is a pagination control [ < ] [ > ], if you click right arrow it will show all the repositories.

<img width="859" alt="Screenshot 2023-01-18 at 3 06 32 PM" src="https://user-images.githubusercontent.com/490201/213798366-15ce3abc-615f-43eb-a50f-3952df886088.png">

**Comment by cathteng** [comment]
I think this is no longer an issue -- just checked the demo org, but feel free to reopen if that's not the case.
