### ISSUE TITLE
Error reporting with Public DSN in standalone binaries

### ISSUE THREAD

**Issue by thomasv314** [getsentry/sentry#4353]
I'd like to track error exceptions that occur in a rubygem binary.

Sentry would work perfect for this use case except for the fact that public-key DSN's only work for the JavaScript clients.

Is there documentation on how I can craft a request that can be used without a private DNS key?

Here's my configuration attempt:

```
Raven::Configuration.class_eval do
  def verify!
    %w(server public_key project_id).each do |key|
      raise(Error, "No #{key} specified") unless public_send key
    end
  end
end

Raven.configure do |cfg|
  cfg.dsn = 'https://mypublicdsn@sentry.io/project'
end

Raven.capture { MyCLI.start(ARGV) }
```

This results in a 403 response, can you advise me on proper documentation/recommendations on how to bend Sentry to do what I want? :D

**Comment by mattrobenolt** [comment]
It's not really possible, and the public DSN is only used by browser JavaScript.

But to be clear, the scope of damage using the secret key is very very limited. It only allows reporting of errors. There's no way to use the key to read data back.

So in this case, I'd generate a new key dedicated just for this with intention to distribute. Then the key can be revoked, etc. There's not inherently anything more secure with the private key vs public key. Public key leverages Referer/Origin for auth, and secret key doesn't is pretty much it.

**Comment by thomasv314** [comment]
Ah! Thanks for speedy response and the clarification. 

I had thought about going that route but the implications of sharing the private key weren't immediately apparent.
