### ISSUE TITLE
PagerDuty Integration Problem

### ISSUE THREAD

**Issue by karlcampbell** [getsentry/sentry#43546]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. press the "add installation" button
2. login to a pager duty account

### Expected Result

To be able to setup the integration.

### Actual Result

I login, but it just drops me into my pager duty account. As if I've logged into it normally.

**Comment by armenzg** [comment]
Hi @karlcampbell thanks for filing; could you please take some screenshots of what you see?

If you could provide an org slug or the DSN for one of your projects it would help me find the errors.

I believe there's two types of PagerDuty integrations, the legacy one (plugins; it may not show up for you) and the current one.

Could you please confirm which one you have? The URLs would be one of these (bar the org slug)
https://sentry.io/settings/sentry/plugins/pagerduty/
https://sentry.io/settings/sentry/integrations/pagerduty/
