### ISSUE TITLE
"There was an error loading a component" on Edit Alert page when the alert's timeWindow is updated using api call

### ISSUE THREAD

**Issue by sepbehroozi** [getsentry/sentry#43548]
### Environment

SaaS (https://sentry.io/)

### Link

https://sentry.io/organizations/{org_slug}/alerts/metric-rules/{project_name}/{alert_id}/

### Steps to Reproduce

1. Create an Alert on Crash Free Session Rate
2. Set any values and save the alert.
3. use the unlisted Sentry API (PUT request to `/projects/{org_slug}/{project_name}/alert-rules/{alert_id}/`) to modify alert's `timeWindow` and set it to any value other than the listed ones which are `60`, `120`, `240`, and `1440` (for example `720`)
4. Navigate to the Alert page on https://sentry.io/organizations/{org_slug}/alerts/rules/
5. Click on the newly created and updated alert.
6. Click on the "Edit Rule" button on the top right corner

### Expected Result

On the Alert overview page, everything works fine. Even the `timeWindow` is correct.
![Screenshot 2023-01-23 at 16 50 16](https://user-images.githubusercontent.com/1960884/214093297-ec9044ed-b839-41e7-9f3f-690caeb54ea7.png)

# Expected:
The alert Edit Page

### Actual Result

There was an error loading a component
![Screenshot 2023-01-23 at 16 58 51](https://user-images.githubusercontent.com/1960884/214093549-1ae01856-f201-4a8a-8075-8c51992f0d98.png)

Checking the browser console, I could see this error:
```
TypeError: undefined is not an object (evaluating 'r.includes')
```
![Screenshot 2023-01-23 at 17 28 11](https://user-images.githubusercontent.com/1960884/214094175-85967f82-741c-4320-a3fa-6276b6a3ca20.png)

**Comment by armenzg** [comment]
Hi @sepbehroozi thanks for filing!
Would the alerting system still work for you with the recommended parameters? (instead of trying to support any values)

**Comment by sepbehroozi** [comment]
> Hi @sepbehroozi thanks for filing!
> Would the alerting system still work for you with the recommended parameters? (instead of trying to support any values)

Hello @armenzg
I haven't noticed any triggers yet but I assume it works as the chart and the time window is showing correctly in the Alert's detail page.
![Screenshot 2023-01-24 at 09 46 22](https://user-images.githubusercontent.com/1960884/214247903-064829d9-84a1-40fa-bf26-f652d98e8e78.png)
I'll let you know once the alert is triggered.

**Comment by scttcper** [comment]
I think the alert will likely work with that value, the details page and editor just aren't setup for custom values. There are intervals that would not work though like really small intervals or really large.

**Comment by sepbehroozi** [comment]
I confirm that the Alert is working properly and I received a notification when it hit the warning threshold in a 720 minutes time window 👍 
CC: @scttcper @armenzg

**Comment by armenzg** [comment]
Thanks for confirming!
