### ISSUE TITLE
I Can't Login - Text Message Always Failed

### ISSUE THREAD

**Issue by sluxzer** [getsentry/sentry#43552]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Hi There, 

I got this error when trying to log in for almost 2 weeks, at first I thought it was some internal problem, but I'm not sure everyone is getting this.

**Step to Produce:**
- I only set my account with 2FA via text message
- My country code is **ID** (stands for Indonesia), and my phone number starts with +62877******
- I try to change devices and also try to change my connection (wifi, mobile data, VPN)

I think it's related to your text message services, I don't know where to ask, there's some related topic on my research on google, but the thread was locked without a solution.

If I'm in the wrong section, please let me know.

Thanks

### Expected Result

I should be getting a text message code to confirm my login

### Actual Result

With this issue, I've no other option to log in, I try to use forgot password but after that, the problem still occurs.

![image](https://user-images.githubusercontent.com/5717315/214111670-df2391e1-cd77-4d8b-9590-d5e1445f4d6b.png)

**Comment by mdtro** [comment]
Hi @sluxzer - Apologies for the trouble here! Could I have you try again and report back? I've made some adjustments to our messaging service's configuration.

**Comment by DulanWirajith** [comment]
I also facing this issue. My phone number starts with +94767******. My country code is SL which stands for Sri Lanka.
Could you please check this @mdtro

**Comment by mdtro** [comment]
@DulanWirajith - Please try again.

@sluxzer & @DulanWirajith -- [Sentry is in the process of deprecating SMS.](https://help.sentry.io/account/security/sms-2fa-deprecation-faq/) We _highly_ recommend you configure an additional 2FA mechanism, either TOTP (ex. Authy, 1Password, Google Authenticator, etc) or a U2F hardware device (ex. Yubikey, Google Titan Security Key, etc).

We also recommend you copy your recovery codes and keep them in a secure place. :)

**Comment by DulanWirajith** [comment]
@mdtro thanks, it's working now. I configure other 2FA mechanism also. thanks for the quick response
