### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by rodrigoalmeida94** [getsentry/sentry#43615]
### Environment

SaaS (https://sentry.io/)

### Link

https://sentry.io/settings/juaai-ag/integrations/github/

### Steps to Reproduce

1. Add Instalation
2. Add authorization on GitHub

### Expected Result

Ability to add repositories to Sentry projects

### Actual Result

nothing happens - i.e. the github configurations page in Sentry remains empty
Any help would be great!

**Comment by armenzg** [comment]
Hi @rodrigoalmeida94 thanks for filing; Could you try one more time?
Are you a Github admin besides a Sentry admin?
And is your Github instance under github.com ? (rather than a GH enterprise deployment) 
If you please provider for screenshots or a HAR file it would be great.
