### ISSUE TITLE
Jira Integration - missing option to create Jira ticket on alert

### ISSUE THREAD

**Issue by mateuszgazdziak** [getsentry/sentry#43637]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Setup a Jira integration
2. Create Alert

### Expected Result

There should be an option for creating Jira tickets on issues in Alerts settings.

### Actual Result

![image](https://user-images.githubusercontent.com/2071939/214389873-6c0bbf68-3c93-4518-a338-655c699e8081.png)

**Comment by brianthi** [comment]
Hi @mateuszgazdziak, there could be something wrong with your Jira integration. Could you share your DSN or create a support ticket https://help.sentry.io/ ? Thanks!

**Comment by mateuszgazdziak** [comment]
@brianthi Here is example DSN: https://ad3c6bcfc6d44c44a8896d08b3c25f02@o1412472.ingest.sentry.io/6766730

I've used suggested plugin made by Sentry. I can create Jira ticket from Sentry issue view.

**Comment by snigdhas** [comment]
Hi @mateuszgazdziak, automatic issue management is available to organizations that include transactions in their Business and Enterprise plans. Could you confirm that this is the case for your organization?

**Comment by mateuszgazdziak** [comment]
No, we a are on Team plan. Thank you!
