### ISSUE TITLE
Crons: Enable attachments to be sent with a check-in

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#43657]
## Problem
When users see an `Failed` check-in on the crons dashboard or get alerted on a `Failed` check-in they are not given any additional context such as an error message to help them debug what happened during cron execution.

## Overview
To help with debugging check-in failures and ensuring the overall health of their system we should allow users to send additional data with the status of the check-in. This could include data such as error messages or metrics like the number of items processed during job execution.

## Proposed Solution
Add a new `File` column into the `monitor.py` model which can hold arbitrary data from the user. We will try to mimic the functionality of [event attachments](https://docs.sentry.io/platforms/javascript/enriching-events/attachments/) where the user can specify a MIME type for the file. Then make changes to the API to support sending/writing this data into the new column. Additionally, we will have to ensure this data follows the user retention policy.

## Integration into CLI
For users who choose to wrap their commands with the CLI instead of calling the API directly we can offer another option onto `sentry-cli monitor run` which will tell us to listen to STDOUT or STDERR when running the user's command and send the output to the API when registering a check-in.

## Related Tasks
```[tasklist]
### Related Tasks
- [ ] https://github.com/getsentry/sentry/issues/44701
```

**Comment by benjaminrussell-americor** [comment]
Thanks for working on this. How can I ensure that the attachment uploaded is understood to be a stack trace or stderr output?

I would expect that when I upload an attachment for a monitor it gets added to the associated issue's entries as a "stacktrace" type object. Also, it would get added to that event's attachments. However, the stack trace preview says there is no stack trace available and the issue's attachments are empty.


![Image](https://user-images.githubusercontent.com/123392899/220418454-88fe6331-e0fa-41f9-9f8d-25e1fda86fea.png)

![Image](https://user-images.githubusercontent.com/123392899/220418915-f681e42e-cb61-4f78-ba43-5a5533b3d204.png)

**Comment by davidenwang** [comment]
Hi @benjaminrussell-americor thanks for using our new attachments feature. Unfortunately we currently don't support linking the uploaded attachment to the issue/error event. This will probably change in the near future as we tighten up how crons integrates with the rest of sentry, so hold tight!
