### ISSUE TITLE
Dashboard Metric: Total number of errors and affected users per day 

### ISSUE THREAD

**Issue by keithhalterman** [getsentry/sentry#4367]
We can write our own SQL query to count the total number of daily errors, but it is difficult to count the number of effected users due to the way events are logged.

These two metrics would be extremely useful to our organization for tracking and reporting the reliability of our application. They would be a great addition to the project dashboard.

**Comment by martinspaeth** [comment]
Related issue: https://github.com/getsentry/sentry/issues/15189

**Comment by BYK** [comment]
@keithhalterman @martinspaeth - I think the pre-built queries in Discover would satisfy this: https://docs.sentry.io/product/discover-queries/#pre-built-queries

What do you think?

**Comment by martinspaeth** [comment]
Thanks @BYK i am looking forward to see the implementation of the ticket I was referencing to. Thank you for sharing the doc regarding pre build queries! My needs are fulfilled so atm! Thank again

**Comment by BYK** [comment]
Closing per @martinspaeth's comment. Feel free to comment your feedback @keithhalterman if you still care about this 🙂
