### ISSUE TITLE
Cant connect self-hosted Gitlab with sentry

### ISSUE THREAD

**Issue by Sorien** [getsentry/sentry#43676]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.1.0

### Steps to Reproduce

after authorizing access to sentry app browser is redirected back to `/extensions/gitlab/setup/?code=bf5b0d3b12f1d1a2d38c8b3944443249b9067b317ffc04d7999ba0e769c2621b&state=dbf677d5dbb24b02b68472a28e377f51`

that ends with `We were not able to parse a JSON response, please try again.`

![image](https://user-images.githubusercontent.com/1270275/214509914-c3ad796e-25aa-4c39-b417-8b07c7f463cb.png)

### Expected Result

successfully finish authorization and connect sentry to gitlab

### Actual Result

Whoops! Looks like something went wrong! Give that another try.

We were not able to parse a JSON response, please try again.

**Comment by Sorien** [comment]
the problem seems to be the wrong DNS configuration self-hosted Gitlab and the sentry can't see each other

**Comment by chadwhitacre** [comment]
@Sorien Glad you were able to sort it out, thanks for following up. :)
