### ISSUE TITLE
Replay: Make sure the Breadcrumbs component displays new 'SDK start' crumb

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#43683]
### Problem Statement

When the SDK is used on a page that posts back to the same URL, we don't capture any breadcrumbs (e.g; navigation).
That information in events is required by the Replay player so we can know what URLs we're at, and properly present them over the player.

### Solution Brainstorm

Once https://github.com/getsentry/sentry-javascript/issues/7259 is completed, look for those new breadcrumbs to feed into today we rely on navigation breadcrumbs.

**Comment by ryan953** [comment]
@bruno-garcia This is missing a link to the mentioned issue

**Comment by billyvg** [comment]
Shouldn't this belong in sentry-javascript?

From Slack:

> I think this is when we start a new session from an existing page (e.g. due to session idle timeout)

**Comment by bruno-garcia** [comment]
I created this at the time: https://github.com/getsentry/sentry-javascript/issues/6928 
But that was closed through https://github.com/getsentry/sentry-javascript/pull/7029 but I'm not sure that'll help achieve what we this issue tracks.

Created now: https://github.com/getsentry/sentry-javascript/issues/7259 (updated description)

**Comment by billyvg** [comment]
Do we have an example replay of this happening? Wondering how you're determining it's a post back that is causing this.

**Comment by bruno-garcia** [comment]
Sadly I don't. This came up from a PHP app.

Maybe @cleptric has experienced this with his dogfooding like gibpotato?  @cleptric problem here is that when the customer loaded a replay it didn't have the right URL on top of the player. IIRC there was no JS playing a role, it was just posting back for any interaction and rendering again on the server.

I just lowered this to p2 since it hasn't come up again since then

**Comment by bruno-garcia** [comment]
A repro: https://sentry.sentry.io/replays/javascript:a40bc81628e94d04b350222270f78b4e
Not necessarily about post back, but the URL at the top of the player is missing the path, which is visible in the first breadcrumb: `Start Recording`

**Comment by ryan953** [comment]
Closing, this seems to have gotten off-topic from the original intent of the ticket.

The most recent example where the url's are inconsistent is represented/replaced by this ticket instead: https://github.com/getsentry/sentry/issues/51404
