### ISSUE TITLE
Crons: Colors of check-in status are hard to tell apart with red-green deficiency

### ISSUE THREAD

**Issue by Radiergummi** [getsentry/sentry#43718]
### Problem Statement

This is probably very much unimportant to you, but easily fixable. Like 8% of the population, I suffer from a red-green vision deficiency. The colors of the check-in status indicators are too similar, such that *in progress* and *ok* are hard to tell apart for me, both looking like some green-brown-ish hue:
<img width="269" alt="Bildschirm­foto 2023-01-26 um 11 06 42" src="https://user-images.githubusercontent.com/6115429/214809348-28234b4a-3906-4d91-9498-5ee5ffb96bd8.png">

### Solution Brainstorm

 A super-quick fix would be to use a color like orange, or blue:
<img width="289" alt="Bildschirm­foto 2023-01-26 um 11 06 19" src="https://user-images.githubusercontent.com/6115429/214809268-ae7fe850-b241-4cf5-b2b6-f6b8973490e7.png">

**Comment by gaprl** [comment]
Hey @Radiergummi, thank you for bringing this to our attention. We're working with our design team to make our Crons' status more accessible, including other improvements to the listing page. I'll keep this issue open for now and will reach back out when we have updates to share.

**Comment by gaprl** [comment]
Hey @Radiergummi, we made a few changes to the list page which hopefully fixes this issue for you, please let us know otherwise. Thanks again for the feedback!
