### ISSUE TITLE
JIRA Server in private network unable to complete Integration Installation

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#43739]
### Environment

SaaS (https://sentry.io/)

### Link

https://sentry.io/settings/coupang/integrations/jira_server/

### Steps to Reproduce

1. Access https://sentry.io/settings/coupang/integrations/jira_server/ and click 'Add Installation'
2. Specify JIRA URL, Consumer Key, and Private Key.
3. Click Submit

### Expected Result

Installation of JIRA Server Integration should succeed.

### Actual Result

Installation fails with the message in the below screenshot. No Integration is established. 

NOTE: The JIRA server is in a private subnet with a .net domain but a public domain (stage-bts.coupang.com) has been exposed to communicate with the private instance through a load balancer.
The .com domain is being specified when they set up the integration but the error lists the .net domain even though it is never referenced once during installation.

Sentry is expecting to auth to a jira server that has the public .com domain, but the self hosted jira server is validating the request using the internal .net domain instead.

<img width="819" alt="image (1)" src="https://user-images.githubusercontent.com/103009467/214913356-b74990a1-f2d9-4f81-946f-be9884f3eb26.png">

**Comment by kpujjigit** [comment]
HAR file of the Installation is attached as .txt due to filetype constraints on GH:

[sentryJiraIntegrationInstall.txt](https://github.com/getsentry/sentry/files/10512155/sentryJiraIntegrationInstall.txt)

**Comment by kpujjigit** [comment]
do not close

**Comment by hubertdeng123** [comment]
Sorry this fell through the cracks, resurfacing this.

**Comment by scefali** [comment]
I'm doing some investigation. Not sure if it's possible to get Jira Server to work when it DNS isn't available to the outside world, doing it through the load balancer like you're doing may not be possible.

**Comment by scefali** [comment]
@kpujjigit The [Jira base URL ](https://confluence.atlassian.com/adminjiraserver/configuring-the-base-url-938847830.html) needs to have a DNS that's available to the outside world in order for oauth to work. I think you might be able to use a [split-horizon DNS ](https://en.wikipedia.org/wiki/Split-horizon_DNS)here without the load balancer.
