### ISSUE TITLE
Square brackets surrounding project title in email subject breaks gmail threading

### ISSUE THREAD

**Issue by cbetti** [getsentry/sentry#4374]
Consider the use case of using Sentry for services, where each service is a separate project, and multiple teams are involved. Sentry delivers an email where Subject is prefixed with `[<Team> <Project>]`.

**Problem**

Gmail and other email clients thread by subject, but the threading mechanism explicitly ignores text within square brackets. Threads are typically based on the 1st message, and other messages are joined into the thread by evaluating relevance of the subject. This causes:
1. Missed or confusing messages (because only the subject of the first message is displayed).
2. Filters to be ineffective (because messages are displayed within a thread even if filtered to a different mailbox / label / tag).

**Cases where this comes up frequently in Sentry**
1. the same exception appears in two different services
2. activity summaries (such as "3 new alerts since DATE")

**The fix**

Follow email convention. Keep important distinguishing detail, like Team and Project, outside of brackets. Use brackets only for non-grouping or tracking data, like system ID or issue status.

**Comment by dcramer** [comment]
FYI we do specify various grouping headers, which I thought at the very least gmail respected.

**Comment by cbetti** [comment]
Assuming you mean the list headers? The list headers work for filtering,
but subject based threading seems to override them. That, and only some of
the sentry notification emails contain the list header.

**Comment by tkaemming** [comment]
I think @dcramer is talking about the `In-Reply-To` and `References` headers which are set here: https://github.com/getsentry/sentry/blob/256ffc9a835e63429d303445e5c8da74f9cae282/src/sentry/utils/email.py#L316-L327

In my own inbox, I've observed Gmail preempting these headers and grouping on subject, though.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
