### ISSUE TITLE
Endpoint api/embed/error-page returns 403 without any error message after following implementation instructions

### ISSUE THREAD

**Issue by cdelacombaz** [getsentry/sentry#43828]
### Environment

SaaS (https://sentry.io/)

### Version

1.14.0

### Link

https://sentry.io/organizations/aodmc/projects/

### DSN

https://8c1ace60d1fb44448a94da05e655f7f0@o4504593398431744.ingest.sentry.io/4504593401118720

### Steps to Reproduce

1. visit https://aodmc.sit.academy/sentry-debug/
2. check network tab 
3. JavaScript SDK loads successfully
4. API call to https://sentry.io/api/embed/error-page/?dsn=https://8c1ace60d1fb44448a94da05e655f7f0@o4504593398431744.ingest.sentry.io/4504593401118720&eventId=47cf1948a6e947f5b584da691b76c58c returns a 403 without any error message

(or visit directly: https://sentry.io/api/embed/error-page/?dsn=https://8c1ace60d1fb44448a94da05e655f7f0@o4504593398431744.ingest.sentry.io/4504593401118720&eventId=47cf1948a6e947f5b584da691b76c58c )

I followed these instructions for the implementation: https://docs.sentry.io/platforms/python/guides/django/enriching-events/user-feedback/

### Expected Result

Feedback widget should show up on my page: https://aodmc.sit.academy/sentry-debug/

### Actual Result

The embed api endpoint returns a 403 => nothing shows up.

**Comment by scttcper** [comment]
You've setup your Allowed Domains in project settings. I think you'll either need to relax this setting or setup Access-Control-Allow-Origin to pass the origin header with the request. I'm not an expert on when browsers send the origin header, the sdk team might know more.

**Comment by cdelacombaz** [comment]
Thanks for the hint. Putting allowed domains back to * results in the form to show up. However, now anyone can see my DSN and send errors to my project, right?

**Comment by scttcper** [comment]
Yeah, but once they have your DSN they can get around the domain block by using a scripting language instead of a browser. Basically you need to set the origin or referrer header to your domain and the requests will be accepted.
