### ISSUE TITLE
Cannot make a user admin or superuser via the admin menu.

### ISSUE THREAD

**Issue by martijnhartlief** [getsentry/sentry#43829]
### Version

22.6.0 (e68da5c)

### Steps to Reproduce

1. Go to the "admin" menu item (/manage/)
2. Select a user
3. Toggle admin or superuser status to on
4. Press "Save changes"

### Expected Result

Admin and superuser status should be persisted

### Actual Result

- The put request is completed successfully 
- Toast pops up with "User account updated"
- After reloading the page, the admin and/or superuser toggles are disabled.

(I inspected network traffic, the put request has isStaff and isSuperuser as true, the response had the isStaff and isSuperuser property as false)

I tested if the user saving is just broken, but changing the username or active works just fine. It just looks like the data is dropped or ignored without reason/error.

- The user email is validated
- Having 2FA on or off made no difference

**Comment by chadwhitacre** [comment]
Let's see if @getsentry/enterprise can help us out with this one.

**Comment by cathyteng17** [comment]
Hello! I'm looking into this

**Comment by cathyteng17** [comment]
I have a fix here #43841. It turns out we weren't correctly parsing snakeCase into camel_case and our tests weren't catching this. Also updating the frontend to display the error detail in #43842

**Comment by chadwhitacre** [comment]
Is anyone running self-hosted nightlies? Can you confirm this fix?
