### ISSUE TITLE
8.9.0 On Premises installation: Constantly logged out with 'Your session has expired.'

### ISSUE THREAD

**Issue by torarnv** [getsentry/sentry#4382]
Following the instructions at https://docs.sentry.io/server/, all with default options, I have all services running, but the web interface keep kicking me out with `Your session has expired.` after only a few seconds browsing around.

**Comment by mattrobenolt** [comment]
This seems entirely related to cookies.

Can you confirm that your `system.url-prefix` setting is correct? if not, this will, I'm pretty sure, cause cookies to get set to the wrong domain causing nothing to stay.

You can confirm by running `sentry config get system.url-prefix` and this should match what you go to in your browser.

**Comment by torarnv** [comment]
```
root@a341b3107989:/usr/src/sentry# sentry config get system.url-prefix
        type: STRING
 from config: <not set>
     current: http://localhost:9000
```

This is the URL i use in the browser as well, which keeps logging me out. 

The following cookies are set (copied from Chrome):
```
altimeActive	false	localhost	/	Session	19			
sc	<redacted>	localhost	/	2017-10-18T10:43:13.516Z	34			
sentrysid	<redacted>	localhost	/	2016-11-02T10:41:54.570Z	231	✓		
sudo	<redacted>	localhost	/	2016-10-19T13:41:54.523Z	53	✓		
```
