### ISSUE TITLE
Automatic Release Configuration for Azure Devops

### ISSUE THREAD

**Issue by klettg** [getsentry/sentry#43835]
### Problem Statement

Similar to the Sentry Github Action (https://docs.sentry.io/product/releases/setup/release-automation/), I'd like an Azure Devops task to assist with Release Tracking.

### Solution Brainstorm

In the meantime, may I ask for assistance to confirm steps to do this manually through azure devops release pipeline - 

Using some combination of an inline bash script to install the sentry CLI like: 

curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION="2.2.0" bash
SENTRY_AUTH_TOKEN=xxxxx
SENTRY_ORG=org_name
SENTRY_PROJECT=node
VERSION=`sentry-cli releases propose-version`
sentry-cli releases new "$VERSION"
sentry-cli releases set-commits "$VERSION" --auto
sentry-cli releases finalize "$VERSION"

Currently I'm having issues installing the cli using the bash script - any advice would be greatly appreciated

![image](https://user-images.githubusercontent.com/32664313/215547541-83516d95-d39e-4445-b85f-625b4c0f4f7a.png)

**Comment by Dhrumil-Sentry** [comment]
Hi @klettg The first request is something we've added to our backlog, we don't have plans to do this in the near term but I will keep this issue updated.

@masinette Can you please help with the other part of the query about help with the CLI
