### ISSUE TITLE
[Feature Request] More functionality to DSNs

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#43846]
### Problem Statement

Currently, using multiple DSNs per project only provides little use.

Instead, this could be used as a very natural way to categorize events from different instances of the same project. If, for example, a project were deployed in multiple markets, or SaaS is provided to multiple customers, DSNs could be used to tag events accordingly.

This, of course, can be implemented in the service directly, but it feels like a very natural property of multiple DSNs to provide some sort of event categorization.

### Solution Brainstorm

See above.

**Comment by iker-barriocanal** [comment]
Hi @jeengbe, I may be missing something but I can't think of any use case using DSNs could solve that code doesn't. Let me know if I misunderstood the description or if you can think of a use case to justify it, and I'll reopen the issue. Thanks for contributing!

**Comment by jeengbe** [comment]
Hey @iker-barriocanal, no you are right, it is equally possible to implement this functionality in code. The ability to automatically tag events based on DSN just seemed like a natural (and easy to implement, I'd guess :)) feature multiple DSNs would provide.
