### ISSUE TITLE
Data Scrubber doesn't work for attachment removal

### ISSUE THREAD

**Issue by Zaratusa** [getsentry/sentry#43862]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.1.0

### Steps to Reproduce

1. Setup Unreal Engine crash reporter
2. Configure the following advanced data scrubbing rule in the server: `[Remove] [Anything] from [$attachments.'CrashReportClient.ini']`

### Expected Result

The `CrashReportClient.ini` should be scrubbed from the attachments.

### Actual Result

The `CrashReportClient.ini` still exists for new events.

**Comment by iker-barriocanal** [comment]
Data scrubbing is meant to scrub data from an attachment, see [attachment scrubbing docs](https://docs.sentry.io/product/data-management-settings/scrubbing/attachment-scrubbing/). If you don't want to have specific files in Sentry, I'd suggest not uploading them. If you're using an official Sentry SDK, there's probably a built-in feature to exclude specific files. ["Uploading attachments" for Unreal Engine docs](https://docs.sentry.io/platforms/unreal/enriching-events/attachments/#uploading-attachments) seem relevant.
