### ISSUE TITLE
Unable to share issue publicly

### ISSUE THREAD

**Issue by stellaatsentry** [getsentry/sentry#43876]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open an issue from your Sentry Issues Page
2. Click on the Share button
3. Copy the link
4. Log out of your account or open an incognito window and paste the link

### Expected Result

The issue should appear in its shared form for a user that doesn't have a Sentry account.

https://user-images.githubusercontent.com/81985895/215792418-8892a045-854f-4726-aeb2-ce03cbe50859.mov

### Actual Result

As a user without a Sentry account, pasting the link in the browser leads to the log in page. This means that the issue cannot be shared publicly.

https://user-images.githubusercontent.com/81985895/215792446-ec494a7b-e715-456c-b1c8-a9f905832a82.mov

**Comment by scttcper** [comment]
Thanks for reporting, i've reproduced this. We're looking into it.
