### ISSUE TITLE
Flutter/Dart source context not shown

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry#43891]
### Environment

SaaS (https://sentry.io/)

### Link

https://sentry.io/organizations/sentry-sdks/issues/3865664603/events/caae327dd2304a1ba9ebd5ed56a267cb/

### Steps to Reproduce

As part of https://github.com/getsentry/sentry-dart/issues/132 - I've tried to do E2E testing of the source context for Dart but it doesn't show up on events in the UI even though the symbolication happens and if you have a look at the linked issue, it actually shows the source context in the stack frame
![image](https://user-images.githubusercontent.com/6349682/215841683-f68b1baf-972e-4ce5-8578-571dcae298aa.png)

### Expected Result

When sources are provided and correctly symbolicated (i.e. what already happens), source context banner should show up on UI.

### Actual Result

No source context at the moment, see https://sentry.io/organizations/sentry-sdks/issues/3865664603/events/caae327dd2304a1ba9ebd5ed56a267cb/

**Comment by hubertdeng123** [comment]
Seems like mobile sdk team knows about this issue, so this is the appropriate team to be routed (correct me if I'm wrong)

**Comment by hubertdeng123** [comment]
Does this item belong on the backlog? Or will it be worked on soon? The Open Source team is tracking this for triage right now so that's helpful to know here 😅

**Comment by lforst** [comment]
@hubertdeng123 Ivan is a contractor helping us out so not sure if this issue is under SLAs. I tagged the mobile team as this a mobile issue.

**Comment by vaind** [comment]
Not sure this belongs with the mobile SDK team. The event is reported to sentry.io and is processed with sources included (as can be seen in the event JSON, I'va pasted in the description). These sources just don't show up on the UI so to me it seems like something is missing in the UI to pick up the source context and print out the expandable component, as it does for other platforms.

**Comment by kahest** [comment]
This is actually the issue to track an issue on the UI (sentry.io). We already track issues related to the SDK in https://github.com/getsentry/sentry-dart/issues/132. I think this is relevant for the Workflow team.

**Comment by lforst** [comment]
We should definitely rename the frontend SDK team as it is totally not what we are at this point.

**Comment by hubertdeng123** [comment]
Thanks for the info and follow up all, it's much appreciated

**Comment by kahest** [comment]
@NisanthanNanthakumar thank you for looking into that! @marandaneto FYI

**Comment by marandaneto** [comment]
@jangjodi should this issue be closed after https://github.com/getsentry/sentry/pull/44327 ?

**Comment by vaind** [comment]
Yes, UI works now:

<img width="1457" alt="image" src="https://user-images.githubusercontent.com/6349682/217781715-22a0ed74-c9c5-4e3e-b970-b6ccc9b39a51.png">
