### ISSUE TITLE
Configure uncompressed assets threshold

### ISSUE THREAD

**Issue by Nickolaus** [getsentry/sentry#43945]
### Problem Statement

Since the feature has been enabled it is bloating our sentry issues.
We have a huge angular application where the files are exceeding the threshold.
This is no easy way to improve this without a lot of work, therefore it would awesome if we could define the threshold values during sentry initialization.
Since those issues are  counting on our quota this is currently kind of unsatisfying because we would need to increase it since we cannot stop this issues from being sent.

### Solution Brainstorm

make threshold values configurable during initialization

**Comment by alexjillard** [comment]
@Nickolaus Thanks for raising this! We're currently refining the thresholds for this detector, and will be releasing an update in the next couple of days. None of the performance issues should be impacting the issue quota, but we'll take a look to confirm no perf issues are being counted.

**Comment by Nickolaus** [comment]
Good to know, nevertheless it would be awesome to  configure this in order to decrease the noice  in our issue reporting.
Thanks in Advanced for handling the issue

**Comment by nanoburd** [comment]
@Nickolaus Hi! product manager here for Performance.

Just to re-confirm, performance issues are grouping transactions, so its not taking up any error quota. We are analyzing transactions you're already sending us for potential problems we think you could fix.

On the topic of noise, is it generating a lot of new issues -> lots of notifications?

I'm trying to understand your situation cause its likely happening to others, so we can improve the detector. This is our 1st version of it! Your your feedback is very valuable. If you have 15 minutes I'd love to chat briefly and find an immediate solution for you while we improve this feature.

**Comment by k-fish** [comment]
Also hey @Nickolaus o/ Following up @nanoburd's comment, I just wanted to ask more about your use case in particular. `Uncompressed Asset` should only be detected if you have huge assets _but they are uncompressed_, which is usually just a setting for your asset domain in your CDN (Fastly, etc.) or your server (nginx, etc.) and nothing to do with file splitting etc. If there is something specific about your scenario it would be great to help us remove those issues removing in the first place, the intent is that these should be relatively straightforward to fix.

**Comment by Nickolaus** [comment]
@nanoburd / @k-fish The first 11 entries in our issues are all referring to uncompressed assets, as far as I can identify these are all `js` files of each module generated during the build
