### ISSUE TITLE
Remove Replay link near Trace navigator on issue details page

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#43942]
## Solution

* Kill the “View Replay” link
* The “|> Replay” Pill behaviour is changed to link the user to the replay details page
* Add amplitude events to just the replay pill

**Comment by ryan953** [comment]
Reverted the change that moved the "Replay" button close into the trace navigator. We don't really need this ticket now until we're ready to dig in and modify trace navigator properly.

**Comment by therealarkin** [comment]
One minor comment - I think it is better that the label will say: "View replay", vs "Replay" especially as the product is new.
