### ISSUE TITLE
Missing known GPU details (max texture size, graphics shader level, support for ...)

### ISSUE THREAD

**Issue by ShawnCZek** [getsentry/sentry#43953]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.1.0

### Steps to Reproduce

1. Create a new exception event
2. Add a GPU context and include one or more of the following keys:
    - `max_texture_size`
    - `graphics_shader_level`
    - `supports_draw_call_instancing`
    - `supports_ray_tracing`
    - `supports_compute_shaders`
    - `supports_geometry_shaders`
3. Send the event to a native project
4. View the event in issues

### Expected Result

Values of the mentioned keys will be appropriately formatted or at least visible as they are described in the documentation:
https://develop.sentry.dev/sdk/event-payloads/contexts/#gpu-context

### Actual Result

This issue is similar to #42969. There are two differences between these two:

- Right now, the GPU values are _somehow_ displayed in the administration
- However, these properties are not described in the types even when they are documented (as shown above):
https://github.com/getsentry/sentry/blob/623a055b4145538718b7af5588a689152ae1b51a/static/app/components/events/contexts/gpu/types.tsx#L1-L11

The context then appears like this:

![Wrongly formatted GPU context](https://user-images.githubusercontent.com/15310717/216097631-08de2090-a776-4047-a23b-9d646275be50.png)

Therefore, I am not entirely sure whether these properties should be added to the administration or whether they should be removed from the documentation as they are/were deemed unofficial.

**Comment by hubertdeng123** [comment]
Thanks for bringing this up, could you comment your problem in the previous issue you've opened?
https://github.com/getsentry/sentry/issues/42969

It seems like a similar enough issue that potentially can be solved at one time and it'd be nice to avoid the switching between issues for context.

**Comment by ShawnCZek** [comment]
@hubertdeng123 Since this has slightly different behavior and affects a different context, I rather opened a different issue. However, if you maintain all contexts together, I can edit the original issue.

**Comment by ShawnCZek** [comment]
Per the request above, I have merged this issue with #42969.
