### ISSUE TITLE
Replay: Trace Navigator loading placeholder on event details page overflows

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#43978]
### Problem Statement

![image](https://user-images.githubusercontent.com/1633368/216135445-8b5a2bd0-439e-4e17-8e46-aed35dc7d642.png)

### Solution Brainstorm

probably set to width=100% or something and doesn’t like being pushed over

**Comment by ryan953** [comment]
Fixed by https://github.com/getsentry/sentry/pull/43995
