### ISSUE TITLE
Migrate Performance Issues to Issue Platform

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#43973]
We want to start serving performance issues via the Issue Platform. We'll need to dual write them for a while, migrate existing data across, and then have a way to switch search to use the issue platform.

```[tasklist]
### Tasks
- [ ] #43983
- [ ] #43975 
- [ ] #43981
- [ ] #43982
- [ ] #44084
```

-----

### [epic in Jira](https://getsentry.atlassian.net/browse/ISP-96)

**Comment by chadwhitacre** [comment]
What's the right `Team: *` [label](https://github.com/getsentry/sentry/labels?q=team) to apply to this issue? I'll assume it's the same for #42044.

**Comment by wedamija** [comment]
> What's the right `Team: *` [label](https://github.com/getsentry/sentry/labels?q=team) to apply to this issue? I'll assume it's the same for #42044.

Do we need to apply these team labels for internal projects? I've added issue platform, but it feels a bit onerous to need to add this label to every issue

**Comment by chadwhitacre** [comment]
PITA, sorry. [Deets](https://github.com/getsentry/team-ospo/issues/105).

**Comment by wedamija** [comment]
@udameli This was closed due to an issue with github -> jira sync. If you start work on this before we get that sync fixed, we can just duplicate this epic to work around the problems

**Comment by logicalbomb** [comment]
Unito is dead, long live Unito.  Sorry for the shenanigans.
