### ISSUE TITLE
Perf Migration: Migrate existing perf data to the issue platform

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#43981]
https://github.com/getsentry/sentry/issues/43975 must be in production before we merge the backfill, otherwise we'll miss data.

We'll need to write a migration that fetches all events for performance issues and writes them to the issue search dataset. I think that the easiest way to do this is to fetch all transactions with a not null `issue_ids` column and write them to the issue search dataset via eventstream.

However, sending things through eventstream also results in them being sent to post process group afterwards. We don't want to do this since it'll result in a large number of duplicate alerts and other things to happen. To avoid this, we can use `skip_consume` when writing to eventstore.

Note that issue platform expects one row per issue, so any rows with > 1 value in `issue_ids` should be duplicated once per id. We might just be able to use an arrayjoin in the query to do this implicitly.

Here's an example of migrating things to snuba from a long time ago: https://github.com/getsentry/sentry/blob/e06263660e6ddf458a3c8c4d2014af5f14552a17/src/sentry/migrations/0024_auto_20191230_2052.py. A lot of this isn't relevant, but this should be a reasonable guideline. Might need to check with ops to see if there will be any problems querying snuba from a migration (shouldn't be, but worth being sure).

**Comment by barkbarkimashark** [comment]
Working on this right now. I wonder if it makes sense to do something like this:
1. Query snuba transaction table for a slim view of the transactions:
```
select arrayJoin("group_ids") as group_id, event_id, project_id from transactions
where group_ids is not null
```
2. For each row returned we:
    a. query the Group in postgres
    b. query GroupHash for the created fingerprint for this event-issue combination 
    c. query nodestore for the event
    d. save an instance of IssueOccurrence from the above objects
3. Pass all these objects to `send_issue_occurrence_to_eventstream` which should gets processed into the search_issues dataset.

My original plan was to query all the columns from the transactions table and try to map the columns back to create an `Event` but this can get hairy if we don't map it properly.

**Comment by wedamija** [comment]
> Working on this right now. I wonder if it makes sense to do something like this:
> 
> 1. Query snuba transaction table for a slim view of the transactions:
> 
> ```
> select arrayJoin("group_ids") as group_id, event_id, project_id from transactions
> where group_ids is not null
> ```
> 
> 2. For each row returned we:
>    a. query the Group in postgres
>    b. query GroupHash for the created fingerprint for this event-issue combination
>    c. query nodestore for the event
>    d. save an instance of IssueOccurrence from the above objects
> 3. Pass all these objects to `send_issue_occurrence_to_eventstream` which should gets processed into the search_issues dataset.
> 
> My original plan was to query all the columns from the transactions table and try to map the columns back to create an `Event` but this can get hairy if we don't map it properly.

This seems like the right way to me. There should only ever be a single group hash for each perf issue. You don't need to query nodestore for the event, since you can just pass the `event_id` instead of `event` and the consumer will handle that.

I just realised that we will need a way to prevent buffer values from being incremented when we send these backfill values through. Otherwise we'll end up double counting for things like `times_seen`. It kind of feels like all we want these backfill events to do is:
 - write an issue occurrence to nodestore
 - write the occurrence + event to eventstream
But we want to skip most of the logic here: https://github.com/getsentry/sentry/blob/73741939df364be90e9cd8ca9cfe795e770fc849/src/sentry/issues/ingest.py#L56-L64

**Comment by barkbarkimashark** [comment]
Yeah, here's a WIP I have that was half-way through implementing the initial approach I thought of. Will need to fix this to query nodestore for the full transaction instead.

https://github.com/getsentry/sentry/pull/44645/files

Hmm, when are these buffer values incremented?

**Comment by barkbarkimashark** [comment]
Lol, I was the one who implemented this ... I thought you were referring to a different consumer downstream. Ok, I think for this migration we'll have to do something similar to what we have in the consumer. I'd imagine the migration would be a cherry-pick of parts of the occurrence consumer.
