### ISSUE TITLE
Internal server error on the Replays page

### ISSUE THREAD

**Issue by rbisol** [getsentry/sentry#44017]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Send replays to a project
2. Go to the Replays page
3. Select an environment to filter results.

### Expected Result

No error and correct list of replay events matching filters.

### Actual Result

Internal server error:

https://user-images.githubusercontent.com/64906376/216316938-e024f72c-6025-4a21-b323-45ed7737677b.mov

[Issue in Sentry](https://sentry.sentry.io/issues/3907931250/events/latest/?project=1&referrer=latest-event&statsPeriod=7d)

**Comment by cmanallen** [comment]
@rbisol This has been fixed.
