### ISSUE TITLE
macOS: `make develop` fails with ld: library not found for -lssl

### ISSUE THREAD

**Issue by torarnv** [getsentry/sentry#4401]
Based on instructions here: https://docs.sentry.io/internal/environment/

OpenSSL installed via `brew install openssl`, but the path doesn't seem to be passed during the build process. Forcing openssl into /usr/local/lib is not an option:

```
(py27) [whopper:~/dev/sentry] $ brew link --force openssl
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
```

**Comment by torarnv** [comment]
cc @mattrobenolt

**Comment by mitsuhiko** [comment]
You need to manually export LDFLAGS for it. We probably won't add a mac workaround for it.

**Comment by torarnv** [comment]
I did:

`pip install --global-option=build_ext --global-option="-L/usr/local/opt/openssl/lib" psycopg2`

But `export LDFLAGS=-L/usr/local/opt/openssl/lib` worked too as you say. Thanks!
