### ISSUE TITLE
Ability to set a default team for new members to be added to

### ISSUE THREAD

**Issue by sentryadam0000345** [getsentry/sentry#44013]
### Problem Statement

Easier way for teams and orgs to onboard new members to Sentry.

### Solution Brainstorm

Having a toggle option or adjustable property to indicate which team should be default team for new members.

**Comment by Dhrumil-Sentry** [comment]
Hi @sentryadam0000345 , Could you tell us why this is a pain today? We want users to be deliberate about adding new members to teams, By having a default team, we see Orgs end up with teams with too many members and that makes it very difficult to use helpful features down the line
