### ISSUE TITLE
Responsive Dashboard

### ISSUE THREAD

**Issue by olafek** [getsentry/sentry#44029]
### Problem Statement

The current grid, regardless of device , for the projects dashboard seems to be maxed at 3x row. If I reduce the width I get maybe 1 or 2 projects , but never more than three.

It would be great to be able to choose the amount of projects in the grid, or at least expand the items per row if displayed on a bigger screen (4k  8k). In our case scenario, we keep one monitor constanly on the dashboard, with some pinned projects on top, but on 4k you get 3x4 (12) stretched monitors, which doesn't really give you an idea of the overall situation of the proejcts.

You can see a 4k display here: https://nimb.ws/Hjd9XR 

Lot of wasted and stretched  space, it would be great to have an option to get say 6 per row for example...

thank you

**Comment by jeremybourque** [comment]
Thanks for the suggestion! We've been thinking about this page a bit lately and some possible ways to improve it. I hadn't really considered that it might be used as a monitoring dashboard. Makes perfect sense now that you say it tho. 😃
Is it just spikes in error volumes that you're looking out for? Or is there more to it?

**Comment by olafek** [comment]
I've been using sentry for a while now (and it's by far our favourite platform, up to the point that I suggest it to clients outside of our monitoring "umbreall" to integrate for pro-active error management) so this would be a great addition.

But yes, we would love some sort of error monitoring dashboard (maybe a different page where we can choosee what to monitor ,without the space occupied by the menu and header, or they can be minimised), with a refresh every 5 minutes or so (not too sure what is the refresh time now) that we can put on a massive screen in the office so whoever is in charge of error monitoring can clearly see that something is wrong and assign it to someone to fix or investigate.

This way is we see a lot of dark bars popping up somewhere we will know straight away that something is wrong and we coudl intervene before the client event notices it...

**Comment by jeremybourque** [comment]
Glad to hear you're enjoying Sentry. 😀 I'll keep your suggestion in mind as we look at improvements to the projects page and I'll see what we can do in the meantime to make it scale better for large displays. You might also want to check out our custom dashboards feature. ([link to docs](https://docs.sentry.io/product/dashboards/)) It doesn't have a live monitor view that hides the navigation menu. But it does let you customize what you put on the dashboard and how it gets visualized.

**Comment by evanpurkhiser** [comment]
I got you

**Comment by jeremybourque** [comment]
great stuff - thanks @evanpurkhiser!
