### ISSUE TITLE
UI bug in the dropdown menu used to select a version when resolving an issue

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#44058]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When attempting to access the version selection option when navigating to "Resolve" > "Another existing release...", it has been observed that users are unable to search for a specific version. The only option available is to select the desired version from the dropdown list. This is causing issues as the list only displays the most recent versions at the top and users are unable to select older versions.

Steps to reproduce:
Navigate to "Resolve" > "Another existing release..."
Attempt to search for a specific version (e.g. 0.1.1)
Observe that the version is not available through search and must be selected from the dropdown list.

### Expected Result

Users should be able to search for and have results returned then select a version, regardless of its position in the dropdown list.

### Actual Result

Users can only select versions appearing at the top of the dropdown list and cannot search for and select older versions.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1730) by [Unito](https://www.unito.io)

**Comment by rbisol** [comment]
Reproducible in Chrome, Safari and Firefox

Adding an example: [issue link](https://sentry.io/organizations/dev-curumas/issues/3757068487/?project=5278835&query=is%3Aunresolved&referrer=issue-stream)

Sentry is sending the correct request and gets the response, but the options are not rendered in the dropdown menu.

GET https://sentry.io/api/0/projects/dev-curumas/react/releases/?query=site

```
[{"id":629350470,"version":"siteProduction","status":"open","shortVersion":"siteProduction","versionInfo":{"package":null,"version":{"raw":"siteProduction"},"description":"siteProduction","buildHash":null},"ref":null,"url":null,"dateReleased":null,"dateCreated":"2023-02-03T07:32:57.686500Z","data":{},"newGroups":0,"owner":null,"commitCount":0,"lastCommit":null,"deployCount":0,"lastDeploy":null,"authors":[],"projects":[{"id":5278835,"slug":"react","name":"ReactProject","newGroups":0,"platform":"javascript-react","platforms":["javascript","python"],"hasHealthData":false}],"firstEvent":"2023-02-03T07:34:00Z","lastEvent":"2023-02-03T07:34:00Z","currentProjectMeta":{},"userAgent":null}]
```

https://user-images.githubusercontent.com/64906376/216548230-bce519c6-9ab0-4b8a-93ea-e5e5e55cc388.mov

**Comment by evanpurkhiser** [comment]
Taking a look at this

**Comment by evanpurkhiser** [comment]
I see what is going on here. Should have a fix for this one soon
