### ISSUE TITLE
{{ release }} in fingerprint doesn't work

### ISSUE THREAD

**Issue by Lingviston** [getsentry/sentry#44094]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.7.0

### Steps to Reproduce

Create grouping rule like this: `error.type:UnknownProductException -> unknown-product-id, {{ level }}, {{ release }}, {{ tags.product_id }}`

### Expected Result

Events from different app versions are grouped into different issues.

### Actual Result

Event do not count in `release` value. Instead the fingerprint of event resolves into the following:
```
[
    unknown-product-id, 
    warning, 
    {{ release }}, 
    some_product_id
]
```

**Comment by scttcper** [comment]
@getsentry/ingest is this an expected feature of ingest/grouping?

**Comment by jjbayer** [comment]
@Lingviston `release` is indeed not a valid variable (see [docs](https://docs.sentry.io/product/data-management-settings/event-grouping/fingerprint-rules/#combining-matchers)). You can always filter by release in the issue search, or use  [Release Health](https://docs.sentry.io/product/releases/health/) to get an overview of errors per release. Feel free to reopen as a feature request if you feel like these product features do not cover your specific use case.
