### ISSUE TITLE
xhr in breadcrumb suddenly shows 'redacted' and does not tell the url endpoint

### ISSUE THREAD

**Issue by studroid** [getsentry/sentry#44101]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

At least until yesterday, I could see the URL in xhr category in breadcrumb, but it is suddenly redacted since a few hours ago.

1. Turn on 'Data Scrubber' for the project and use default scrubbers.
2. Add 'body', 'data' to the additional sensitive fields.
3. Make xhr request in frontend while using app.
4. Produce error and check breadcrumb in the project issue.

### Expected Result

URL is shown in xhr category in breadcrumb.

### Actual Result

<img width="611" alt="CleanShot 2023-02-04 at 00 54 18@2x" src="https://user-images.githubusercontent.com/4001790/216649452-f4a5b329-bc55-4461-b101-deb1174a50f6.png">

<img width="914" alt="CleanShot 2023-02-04 at 00 55 14@2x" src="https://user-images.githubusercontent.com/4001790/216649466-ad56de9c-0974-4c0b-9b44-f57b85d308d4.png">

**Comment by studroid** [comment]
Not sure but I thought there could be some unintentional changes in default scrubbers policy.
It would be much appreciated if you let me know the cause of the change.

**Comment by priscilawebdev** [comment]
Thanks for reporting this issue @studroid 🙏  Can you provide us the link to this event?

**Comment by studroid** [comment]
@priscilawebdev 

[This](https://lemonbase.sentry.io/issues/3735970947/events/be12a955ba0d4357a96dbc163792deae/?project=3699839) is the recent event link. Thanks for quick check!

**Comment by studroid** [comment]
<img width="707" alt="CleanShot 2023-02-05 at 16 59 25@2x" src="https://user-images.githubusercontent.com/4001790/216808073-f01c8ae9-3716-41a8-aaed-1c6adf7e75f0.png">

Still don't know why, and not only xhr but any urls in breadcrumb are redacted.

**Comment by priscilawebdev** [comment]
Thank you for providing the link... will check it soon 😉

**Comment by studroid** [comment]
@priscilawebdev 

Thanks for checking!
It had been, however, shown correctly just before some days ago.

Also as I checked my audit log, I'm sure I didn't change the additional sensitive fields.

We are currently sending sensitive data with `data` field, so if you can handle something for it, it would be a great help for us.

Please let me know if anything had been changed on your part.
Thanks in advance!

**Comment by priscilawebdev** [comment]
> It had been, however, shown correctly just before some days ago.

Data Scrubber takes some time to be applied, but it wouldn't take days cc @untitaker 


> We are currently sending sensitive data with data field, so if you can handle something for it, it would be a great help for us

Since you don't want to redact all the sensitive data coming in the `data` value, have you considered using [Advanced Data Scrubbing](https://docs.sentry.io/product/data-management-settings/scrubbing/advanced-datascrubbing/)? lets you write fields separately and you could, for instance, use regex for it.

**Comment by studroid** [comment]
Yeah, to make it more clear, the URL was correctly shown in the breadcrumb longer than 2 years with the same option. So it didn't have any problem for a long time at least until a week ago.

I thought Advanced Data Scrubbing might be an option for me, but as you told `data` field in "Additional Sensitive Field" is the cause of the issue, I'm not sure if I can handle it with the advanced one.

I still need to redact the data field sent from my frontend app, while the URL is shown correctly.

**Comment by studroid** [comment]
Is there any update? I thought this might be kind of a simple issue, but if not, I will try to find another way to handle this.

**Comment by priscilawebdev** [comment]
hey, sorry for my late reply.

> I thought Advanced Data Scrubbing might be an option for me, but as you said data field in "Additional Sensitive Field" is the cause of the issue, I'm not sure if I can handle it with the advanced one.
> 
> I still need to redact the data field sent from my frontend app, while the URL is shown correctly.

In an advanced data scrubber, you could use, for instance, regex to redact everything else, rather than the URL

<img width="623" alt="image" src="https://user-images.githubusercontent.com/29228205/218064269-8fb019a7-583c-4bc1-9aa3-2ec122de55ee.png">

As for why this only started to properly work now, I don't know... @untitaker do you think you can help us here?

**Comment by priscilawebdev** [comment]
@studroid I have just added a ticket for this issue to our backlog and we will investigate it. As soon as we have more information, we will post it here. Thank you!

**Comment by studroid** [comment]
@priscilawebdev 

Thank you for your kind support!
So what you're saying is that the current situation is originally intended but there was a problem before, right?

I'm not 100% sure about what's happening now, but I will try advanced data scrubbing.

By the way, In the screenshot you uploaded, `**` is used as Source but then isn't it the same with using `data` in Additional Sensitive Field?
(I'll try `extra.**` as well and check it out if it fits for my case.)

![CleanShot 2023-02-10 at 20 40 46](https://user-images.githubusercontent.com/4001790/218084459-35799e84-179c-41dc-bf65-58fd70998035.png)

![CleanShot 2023-02-10 at 20 40 54](https://user-images.githubusercontent.com/4001790/218084495-166faa3c-72a8-46f6-ba78-9eb39db7ffa4.png)

**Comment by studroid** [comment]
Hmm... I don't get it...

I entered `data`, `.*data.*` but both didn't work as expected.
I have to filter out `data` value in the screen shot attached. Let me know if you have any ideas.

![CleanShot 2023-02-10 at 22 07 06@2x](https://user-images.githubusercontent.com/4001790/218101355-b1499f12-1c03-49dc-a849-d7b3ad405dd8.png)

**Comment by priscilawebdev** [comment]
hello! sorry... busy days :)

So in the above image, I can see that you are trying to scrub contexts and not breadcrumbs as previously discussed.

If you want to scrub `baseURL` the following shall work

![Screenshot 2023-02-15 at 12 02 00](https://user-images.githubusercontent.com/29228205/219010754-e75f917c-3594-4410-a127-0bec73a31d44.png)

There is a field called `Use event ID for auto-completion` that helps you see what you can redact in your event... you just have to paste the event ID that you can find at the very top of each event's page.

Please let me know if that works.

**Comment by studroid** [comment]
@priscilawebdev 

Thank you for your help!
As you said, I've succeeded in masking individual elements by using the event id as a hint, but I can't mask all the nested data in the contexts. I entered `contexts`, `contexts.**` but it didn't work as expected.

Do you have any guidance for this kind of situation?

**Comment by studroid** [comment]
![CleanShot 2023-02-16 at 16 52 24](https://user-images.githubusercontent.com/4001790/219302043-ce484327-a00a-410b-8fdc-26eb2994ce1d.png)

After a lot of trying, I managed to make it work. It was pretty hard to find out this option, but I'm back to the expected environment. 

I've solved my problem, so it's up to you to close this issue or not :)

**Comment by studroid** [comment]
@priscilawebdev 

[This documentation](https://docs.sentry.io/product/data-management-settings/scrubbing/advanced-datascrubbing/) helped a little, but not enough in my case.

It was lack of these things for me.
1. The exact meaning of `Data Type` in advanced data scrubbing rule
   - At first, I thought it should be `key` in JSON data, but it actually filters value matching the pattern. It was confusing to me.
2. What's in `contexts` or Where the data I sent goes into.
   - To find what is exactly in `contexts`, I used `onBeforeSend` event in my script and printed the log.
   - There was not enough explanation, so I consumed long time to understand that.
3. How to find exact data key in nested object
   - [This explanation about Wildcards](https://docs.sentry.io/product/data-management-settings/scrubbing/advanced-datascrubbing/#wildcards) exists, but it doesn't mention some more detailed patterns.
   - Someone may get it, but if more patterns and concrete examples could be provided, it should be greatly helpful.
   - In my case, because I was confused what `Data Type` means and tried to use regex - what was wrong, I couldn't easily find the pattern I should apply.
5. The time needed to apply individual adavanced data scrubbing rule
   - I'm still not sure how long it takes, but I definitely went through some weird situation.
   - If I set or changes several rules in sequence, the data were not filtered as I expeceted.
   - I just thought it neeeds some time to be applied and maybe Sentry have some queues for the rules to be applied, but I wasn't sure and confused.


I might have been more confused 'cause English is not my first language, but because of that, I could be better to find the points to be improved.

I'm willing to contribute in small ways, so gonna make some improvement suggestions as pull request soon :)


---

About the breadcrumbs,
Because I finally understood how the Advanced Data Scrubbing Rule is applied, it was relatively easy to handle filtering data in breadcrumbs. I'm pretty sure I can manage data in breadcrumb as I intended.

<img width="904" alt="CleanShot 2023-02-17 at 14 23 56@2x" src="https://user-images.githubusercontent.com/4001790/219556527-b0a12bb8-0441-48e4-8893-8e141dae7360.png">

Thank you again for your kind support.
Hope this report also help you in some way.

**Comment by priscilawebdev** [comment]
@studroid Thank you so much for the great and detailed feedback! 🙏  

I will be sharing this feedback internally so we can discuss it and improve this document soon. 

Very glad to know that Advanced Data Scrubbing is now helping you.  👏 🙂
