### ISSUE TITLE
Dashboard filters being set inconsistently

### ISSUE THREAD

**Issue by narsaynorath** [getsentry/sentry#44161]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Lock a project filter
2. Open a dashboard
3. Go back to manage page
4. Open another dashboard
5. Repeat

### Expected Result

The dashboards should open up with the filters saved on the dashboard and inform the user that the filters have been overridden. Similar to Discover saved queries.

### Actual Result

Occasionally users will see the locked filter, and sometimes they'll see the saved filters. Whichever the user sees more often seems to differ (I've seen it favouring the saved filter, a report showed it favouring the locked filter)

**Comment by brentc** [comment]
Let's try and at least identify root cause in the next sprint

**Comment by ale-cota** [comment]
This behaviour seems no longer reproducible. The dashboard loads with the correctly saved filters every time.
