### ISSUE TITLE
Issue search follow up tasks

### ISSUE THREAD

**Issue by rjo100** [getsentry/sentry#44201]
Document searchable keys + fix UI tooltip
Remove unused `get_filter`

**Comment by rjo100** [comment]
There is a lot of snuba weirdness around `format_search_filter`. I don't think we're actually properly utilizing the project + group id breakout queries. Also, `get_filter` seems to be totally unused.

https://github.com/getsentry/sentry/pull/43851

**Comment by barkbarkimashark** [comment]
`get_filter` can maybe be deprecated since it uses the old format and discover and metrics uses the SnQL format now.

**Comment by barkbarkimashark** [comment]
- Document `project:<project-slug>` as a search filter alias in the UI
- Document `issue:<Issue-short>` as a search filter alias in the UI

**Comment by barkbarkimashark** [comment]
Update docs to reflect new aliases:
https://docs.sentry.io/product/sentry-basics/search/searchable-properties/

**Comment by barkbarkimashark** [comment]
https://docs.sentry.io/product/sentry-basics/search/searchable-properties/

**Comment by ceorourke** [comment]
Closing as it seems done
