### ISSUE TITLE
[Slack Bot] Send Spike Protection alerts to Slack

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#44222]
### Environment

SaaS (https://sentry.io/)

### Version

n/a

### Link

n/a

### DSN

n/a

### Steps to Reproduce

n/a

### Expected Result

n/a

### Actual Result

Sentry [App] should also send spike alerts to Slack (maybe make this configurable). 

This would alert more people of the fact that something is seriously wrong, allowing for a quicker roll back.

**Comment by Dhrumil-Sentry** [comment]
Hi @jeengbe Thanks a lot for raising this issue, We'll also be working on allowing spike protection notifications to be sent to slack channels in the future

I also noticed that your Sentry Org is not in the Closed Beta for Improved Spike Protection https://github.com/getsentry/sentry/discussions/44155

Would you like to have your Org included in the Beta?

**Comment by jeengbe** [comment]
Hello @cathyteng17 Thanks for the link! In that case, there is something wrong with Slack notifications. I received an email today warning me about an error spike, yet neither in a Slack Channel nor in DM did we get any alerts about this issue.

Some further suggestions:
- Link to that page from the integrations page. That's where I looked the such setting.
- How do notifications in Slack relate to my account's own settings? I'd like to trigger an alert in a channel, not receive a DM from Slack.

**Comment by jeengbe** [comment]
Hi @Dhrumil-Sentry That's great to hear, thanks!

I'll discuss joining the closed beta with the team, judging by the linked Discussion, it surely looks promising. :)

Didn't know that was a thing, thanks for suggesting!

**Comment by Dhrumil-Sentry** [comment]
Hi folks, we made improvements to Spike Protection and it's now generally available. We've also added notification controls to allow you to send a project's spike notifications to a Slack channel or Pagerduty. Please see this discussion for more details: https://github.com/getsentry/sentry/discussions/44155
