### ISSUE TITLE
Show new app context for "app was in foreground/background" in event details

### ISSUE THREAD

**Issue by zoesyc** [getsentry/sentry#44251]
Mobile app crashes can happen when the app is in the foreground or in the background. However, we currently do not surface this detail to the developer. 

![Image](https://user-images.githubusercontent.com/38118634/217347956-5a7a87b4-37fc-4194-8d2f-ed081ba0e219.png)

Currently, we surface a stack trace value `was active` to developers (image above) but this can manifest differently depending on the framework:

1. Single Thread frameworks (Flutter, React Native) - will be `true` regardless of the app being in foreground or background
2. Multi-thread frameworks (Android, iOS) - will be at individual thread level and reflects state for that thread

For scenario 1, `was active` is not an accurate proxy for whether the app was in foreground/ background at crash time and this new value `app.in_foreground` aims to address this problem. While for scenario 2, `was active` can be a more accurate proxy. 

Surfacing `app.in_foreground` raises a scoping question: **Do we want to surface this as a tag?** 
It has already be made searchable in the Issue stream and we see value in being able to break metrics down by this value. 

![Image](https://user-images.githubusercontent.com/38118634/217347752-dc78333b-aaff-4b77-a147-abc5830ba7cc.png)

Additional notes:

- Front-end task for exposing the new app context coming in getsentry/team-mobile#36

- Related PR: getsentry/sentry#43964

**Comment by brentc** [comment]
> Currently, we surface a stack trace value was active to developers (image above) but this can manifest differently depending on the framework

From what I understood, I would actually say this value is _independent_ of the state of the app. It's thread-specific and indicates if _the current thread was active_ during the event.

**Comment by snigdhas** [comment]
Looks like the related epic was completed 🥳
