### ISSUE TITLE
Could not set key: u'l:buffer:process_pending'

### ISSUE THREAD

**Issue by DenisBY** [getsentry/sentry#4426]
I see a lot of message like:
```
16:43:33 [WARNING] sentry.tasks.process_buffer: Failed to process pending buffers due to error: Unable to acquire <Lock: 'buffer:process_pending'> due to error: Could not set key: u'l:buffer:process_pending'
```
I have 2 servers running 16 workers with `-c 4` on each server
I what direction should I look? What to check and fix?

**Comment by dcramer** [comment]
tl;dr is your server is not configured correctly. We don't provide help with that outside of resolving actual code bugs here. Please use the forum for support, but even then, you're choosing to host Sentry (which is a fairly large complex infrastructure beast), so you'll have to dig into a lot of the issues yourself.
