### ISSUE TITLE
Option to have event details without values, to be visible in formatted view

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#44276]
### Problem Statement

When event details have missing values the parameter is not displayed in the formatted view, however, they are displayed in the curl view.

For example, in my test organization, query parameters without values display in the curl version:

![Screen Shot 2023-02-07 at 4 08 30 PM](https://user-images.githubusercontent.com/8451987/217395643-b7699c69-9d6c-42c4-aa8d-ae39b3d1c7ef.png)

Example of the missing parameter in formatted version:

![Screen Shot 2023-02-07 at 4 08 41 PM](https://user-images.githubusercontent.com/8451987/217395698-e33c3ac7-8df2-4b32-bae3-92d69ba80cf9.png)

Specific customer feedback:
_IIt would be very useful to have these empty parameters visible somehow. One of the parameters that was not displayed was actually the source of the bug which caused the exception, and not having them there is quite confusing as they are valid (but empty) parameters._

### Solution Brainstorm

Option to enable parameters without values to be displayed in the formatted view. These values could be populated as null/empty-strings

**Comment by therealarkin** [comment]
@JLuse - thanks!

@brianthi is there a way for us to understand how common it is? 
It's fine to show param with no values
What the downside of doing so?

**Comment by brianthi** [comment]
I don't think there's an easy way for us to determine how often this happens. I don't see any downsides to this other than it may clutter the view if there are a lot of empty params, but we could fix that with a small change in the design of that Query String component.

**Comment by therealarkin** [comment]
Re: frequency: get a 10k sample ulrs from curl and count? if you dump me the urls a sheet, i can take a stab and count them w/ some python. It's my night hobby. 

Can we add an "Empty Param" section, and just show all of them? cc: @robinrendle
