### ISSUE TITLE
Integration with internal crash reporter

### ISSUE THREAD

**Issue by rebx** [getsentry/sentry#44282]
### Problem Statement

Hi,

I wanted to check if it's possible to integrate sentry with another application that I use for reporting crashes? Like I would want the application we have to watch for crashes/events but send them to sentry so they can be visualised better? If it is possible, what process do I need to follow? Is there a base class or interface that I need to extend that will allow me to do this? 

If it isn't possible, what would be a good way to start to write a custom integration? 

Many thanks

**Comment by ashwoods** [comment]
Hi @rebx! 
You could leverage the SDK to send an event manually. What platforms does your application support?

**Comment by rebx** [comment]
Thanks for your reply. It will be both c++ and python. Do you have examples or docs on how to do this with the SDK?

**Comment by ashwoods** [comment]
I think we would need a lot more information about what your current crash handler provides, but in essence, the simplest approach is to use the sentry-native SDK with `SENTRY_BACKEND=none` together with `sentry_capture_event`, out of the box these wouldn't be crashes.
