### ISSUE TITLE
Include nuget symbol server by default for dotnet projects

### ISSUE THREAD

**Issue by mattjohnsonpint** [getsentry/sentry#44280]
### Problem Statement

In #43943 we got the Nuget symbol server as a built-in. 👍 

It would be nice if it was on by default for new .NET projects.

### Solution Brainstorm

Defaults for built-in symbol servers are set here:

https://github.com/getsentry/sentry/blob/1abd29e8d049084e4f221cf931cf1bb40263adc0/src/sentry/projectoptions/defaults.py#L53-L56

We'd just need to add `"nuget"` to the list of defaults.  But I don't currently see any way to change the default based on the selected platform, and it probably should only be on by default for `dotnet`.

@Swatinem - thoughts?

**Comment by Swatinem** [comment]
The symbol server has a filetype filter, so it will only be used for portable pdb files. So its good to set it as default.
