### ISSUE TITLE
Can not silence "Sentry is attempting to send 2 pending error messages Waiting up to 2 seconds Press Ctrl-Break to quit"

### ISSUE THREAD

**Issue by glenn-jocher** [getsentry/sentry#44285]
### Environment

SaaS (https://sentry.io/)

### DSN

https://f805855f03bb4363bc1e16cb7d87b654@o4504521589325824.ingest.sentry.io/4504521592406016

### Steps to Reproduce

Our users are seeing the following message on every error event sent to Sentry, which we do not want to show:
```
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit
```

See See https://github.com/ultralytics/ultralytics/issues/862 for one example. Our `sentry.sdk_init()` already sets `debug=False` (see source below) and this message is still appearing every time an error happens.

https://github.com/ultralytics/ultralytics/blob/f5d003d05a6796fb6047dc1dcfa70c0bbdf43526/ultralytics/yolo/utils/__init__.py#L502-L509

### Expected Result

No console output displayed by sentry.

### Actual Result

Console message displayed every time an error is sent to sentry:

```
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit
```

**Comment by Kobby-Bawuah** [comment]
Hello @glenn-jocher, I noticed you also sent this to the sentry support team. I sent a reply via that channel so will be closing this ticket. If you have any other questions follow up on that ticket.
