### ISSUE TITLE
Public API endpoint to set external user mappings

### ISSUE THREAD

**Issue by meichend** [getsentry/sentry#44325]
### Problem Statement

I want to add/remove/edit external user mappings with an endpoint similar to `/api/0/organizations/{organization_slug}/external-users/` to create external user mappings *in bulk* programmatically. If there's a workaround solution I can implement now that would be great, too.

Thank you.

### Solution Brainstorm

Make a public version of said API that has the same access rules as the existing one but accept an array in request body

**Comment by therealarkin** [comment]
Thanks! What is the reason you'd want to do it? Trying to better understand the use case here

**Comment by meichend** [comment]
Sorry for the late response. We're trying to develop a service that would make this process more streamlined and help larger organizations quickly set up their external user mappings when they start using Sentry or when new employees join and/or leave.

**Comment by iamrajjoshi** [comment]
We have docs for this now! https://docs.sentry.io/api/integrations/create-an-external-user/
