### ISSUE TITLE
Source context highlighting

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry#44344]
### Problem Statement

As a follow-up for https://github.com/getsentry/sentry/issues/43891 which fixed showing `dart` sources in issues. I'm wondering what it would take to have formatting on the shown fragments, based on the file extension (i.e. for all languages, not just dart).

I've tried to find an existing feature request but seems like there's none, feel free to close this as a duplicate if it exists.

### Solution Brainstorm

Something like https://prismjs.com would make the code a bit more readable: see the following examples:

## [Current state on sentry.io](https://sentry.io/organizations/sentry-sdks/issues/3865664603/events/caae327dd2304a1ba9ebd5ed56a267cb/)

<img width="850" alt="image" src="https://user-images.githubusercontent.com/6349682/217784080-e6d0ffff-fdca-4af4-82dc-fe799167cf2c.png">

## [Sample formatted with prismjs](https://prismjs.com/test.html#language=dart&text=%7D%0AFuture%3Cvoid%3E%20tryCatch()%20async%20%7B%0A%20%20try%20%7B%0A%20%20%20%20throw%20StateError('try%20catch')%3B%0A%20%20%7D%20catch%20(error%2C%20stackTrace)%20%7B%0A%20%20%20%20await%20Sentry.captureException(error%2C%20stackTrace%3A%20stackTrace)%3B%0A%20%20%7D%0A%7D%0A)
<img width="684" alt="image" src="https://user-images.githubusercontent.com/6349682/217783976-a9708d18-3a69-4356-aa51-cc2c0af289bd.png">

**Comment by malwilley** [comment]
Hi @vaind this is timely feedback! We have this on an ideas backlog for improving the issue experience so will be discussing this soon.
