### ISSUE TITLE
[Feature Request] Slack notification should include project

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#44340]
### Problem Statement

Currently, issue notifications to Slack look like this:
![image](https://user-images.githubusercontent.com/51749023/217752864-ca482b0b-8746-4d5f-a398-7cb573ef8c4a.png)

However, with multiple project using the same names for alerts, it's difficult to tell at a glance from which project the issue came from.
Changing the alert name in Sentry itself to include the project scope is possible, but not the best solution, as that's effectively redundant information.

### Solution Brainstorm

Something very simple like the following would already do. 
![image](https://user-images.githubusercontent.com/51749023/217753376-79ea36b2-ff5f-497d-b03f-f5c913d4cc29.png)

**Comment by Dhrumil-Sentry** [comment]
Hi @jeengbe Thanks a lot for the feedback. We definitely agree this is worth doing and I am adding it to the backlog

Some follow-up questions to understand your workflow a bit better

- Is your team sending slack alerts from multiple projects to the same channel? Is there a reason why you are not using different slack channels? 
- Is there any other improvement you'd like to see in Slack?

**Comment by jeengbe** [comment]
Hey @Dhrumil-Sentry! Thanks a lot!

And yes, that's how we do it. Both frontend and backend alerts go to the same channel, and we've also got some overlapping with another domain team which also gets their alerts in that very same Slack channel. I support that setup, since it's always good to stay in the loop with closely collected upstream dependencies.
So far, I can't think of anything else that I see missing. I can't speak for others in my team, but I am very satisfied with what the Slack integration offers :)

**Comment by ceorourke** [comment]
We've added the project slug to Slack alerts now, please see [this post](https://docs.sentry.io/changelog/more-context-in-slack-alerts/) for all the details of the change.
