### ISSUE TITLE
Hope uploading only sourcemap files(without source code) can work

### ISSUE THREAD

**Issue by a1mersnow** [getsentry/sentry#44343]
### Problem Statement

I only have sourcemap files, and I don't have source code files because they are only hold by  third party.

IMO, there are error line number and column number, and there are sourcemap files, we can get the mapped source code line number and column number. Then, my sourcemap files contain the `sourcesContent` property, so we can display the source code.

Is there something I miss?
Only have sourcemap files, sentry can't work?
I tried:
`sentry-cli sourcemaps explain`
I got:
```
✖ Uploaded artifacts do not include entry
```

**Comment by kamilogorek** [comment]
I'm not sure what's the issue here tbh. Can you explain it further? And provide some example issues that are not resolved?
