### ISSUE TITLE
Assign-to-user dropdown does not populate when loading an issue directly

### ISSUE THREAD

**Issue by compact** [getsentry/sentry#4434]
If I open the url /project/issues/1234/ directly, the "assigned" dropdown is empty:

![image](https://cloud.githubusercontent.com/assets/498501/19702946/d15c5020-9acf-11e6-9cc2-84df4f371f58.png)

If I first open another url such as /project/, and then navigate to /project/issues/1234/, then the dropdown is filled with users.

**Comment by dcramer** [comment]
I've seen this happen too and I think its a race condition (as I dont think 100% of the time this happens).

**Comment by compact** [comment]
Oh that's right, I just reloaded a bunch and the users did load a few times, though they did not load most of the time.

Thanks for the quick response!

**Comment by lalpert** [comment]
This race condition is happening to me as well... The users list only loads about 10% of the times I reload the page.

**Comment by mattrobenolt** [comment]
I assume also the same as https://github.com/getsentry/sentry/issues/5966

**Comment by MaxBittker** [comment]
i was able to reproduce this by turning dev tools network throttling on.

**Comment by MaxBittker** [comment]
hmmm, i guess i didn't fix https://github.com/getsentry/sentry/issues/5966 with https://github.com/getsentry/sentry/pull/5967

:S

**Comment by billyvg** [comment]
I have a fix incoming
