### ISSUE TITLE
Sentry Support for Xtensa architecture

### ISSUE THREAD

**Issue by reshmatitus** [getsentry/sentry#44365]
### Problem Statement

Sentry is currently unable to decode the ESP32 backtrace from the elf file. 

### Solution Brainstorm

Add sentry support for ESP32 microcontroller

**Comment by Swatinem** [comment]
What exactly do you mean by "from the elf file"?

Are you sending an event, or a minidump? Is it failing in symbolication (using the DWARF data), or when processing the minidump (stack walking using CFI data)?

Do you have an example file we can look at?

Depending on the outcome of these open questions, I would however not get the hopes up too high. If there is a simple fix, possibly one in dependencies, it might be easy to fix this.
If it would require more implementation work however, I doubt we will prioritize this anytime soon.

**Comment by reshmatitus** [comment]
This is a crashdump and we are trying to decode the stack from the .elf file. We're using a script from sentry as the basis for our upload. 
From the screenshots that I've provided you can see that symbolication is ok and it is able to find debug, unwind and symtab.(first two images) I'm not sure why it isn't able to decode the backtrace.(last image)
<img width="510" alt="Screen Shot 2023-02-13 at 10 01 11 AM" src="https://user-images.githubusercontent.com/120426876/218574639-4fd7d136-88b8-49f9-99b5-956c25b35565.png">
<img width="839" alt="Screen Shot 2023-02-13 at 10 01 20 AM" src="https://user-images.githubusercontent.com/120426876/218574646-6497ce30-fc7f-4a83-b19b-d0f353f18688.png">
![Screen Shot 2023-02-13 at 10 01 46 AM](https://user-images.githubusercontent.com/120426876/218574687-ead5b29d-acbc-4abb-a7bf-f9049eb07f43.jpeg)

**Comment by Swatinem** [comment]
Okay, looks like the `coredump-uploader` actually sends an event payload to sentry. What is the symbolication status of the stack frames in the event JSON?

Can you link me to a sentry event so I can take a detailed look? It is very hard to figure out whats going on just by looking at screenshots.

**Comment by reshmatitus** [comment]
Here is a link to one of our crash
https://chewielabs.sentry.io/issues/3546472789/events/fad81dcbe1824053b74bf02866ffee67/?project=6622721

**Comment by reshmatitus** [comment]
Hi it would be helpful if I could get an update on this :)

**Comment by reshmatitus** [comment]
Hi I am having trouble uploading the file to sentry. Is there a direct message option through which I can send the elf file to you.

**Comment by Swatinem** [comment]
I am on discord where you can PM me: Swatinem#8483
or alternatively you can send me any link to arpad.borsos@sentry.io

**Comment by Swatinem** [comment]
I was able to take a closer look at this (also answered via email).

It seems like the module load address in the sentry event is wrong.

The debug file reports an internal load address of `0x3f400020`, and with the absolute address `0x400d9c88` (which I can look up via `dwarfdump`) it gives me the file-relative address of `0xcd9c68`.

`dwarfdump` and our own `symcache_debug` agree when looking up these addresses.

However the event on sentry reports a load address of `0x40080000`, which then yields a relative address of `0x59c88`, which does not yield anything.

As this most likely comes from https://github.com/getsentry/coredump-uploader, it might be necessary to investigate the problem there.

**Comment by reshmatitus** [comment]
this worked thanks

**Comment by Swatinem** [comment]
Glad this helped! May I ask what you did to fix this?

**Comment by reshmatitus** [comment]
I modified the start address in the script
