### ISSUE TITLE
📊 Wrong timezone in graphs (in issues and dashboard graphs)

### ISSUE THREAD

**Issue by saippuakauppias** [getsentry/sentry#44372]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.12.0

### Steps to Reproduce

**1. I chose the timezone in my account (`domain.com/settings/account/details/`):**
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/945306/217932898-56e11c8e-c6e3-46ce-adcd-4338e2f8556e.png">

**2. All issues and errors are displayed with the _correct_ timezone (current time is: `23:44 MSK (+03:00)`):**
<img width="339" alt="image" src="https://user-images.githubusercontent.com/945306/217934034-88b95b79-452b-4c9d-8dcd-97de62c05a58.png">
<img width="388" alt="Снимок экрана 2023-02-09 в 23 41 48" src="https://user-images.githubusercontent.com/945306/217934861-c795278f-ce15-4b73-98bb-14056e649d41.png">

**3. But on all charts I see time in UTC (_without_ timezone shift):**
<img width="341" alt="image" src="https://user-images.githubusercontent.com/945306/217935028-25993773-d3b4-418b-a1de-0aa061fbe6d8.png">
<img width="347" alt="image" src="https://user-images.githubusercontent.com/945306/217935084-b9960fc9-fe06-4447-9c4d-a88fcf27fa20.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/945306/217935191-80ef9117-294d-4435-9a52-611b9edee653.png">
(_last - is chart in dashboard_)

### Expected Result

In all graphs you must also take into account the shift in the timezone. 

Perhaps https://github.com/getsentry/sentry/pull/44009 solves this problem, but I'm not sure

### Actual Result

Screenshots above

**Comment by saippuakauppias** [comment]
@evanpurkhiser, maybe you know, your PR fixes just that? I would be grateful for feedback

**Comment by saippuakauppias** [comment]
Same in the charts on the projects (`/organizations/[org]/projects/`) page (**current time is: 15:35 MSK +03:00**):
<img width="946" alt="2023-02-10 в 15 35 48" src="https://user-images.githubusercontent.com/945306/218094162-67946b60-e30d-4714-9cb3-34482443d824.png">

**Comment by mjq-sentry** [comment]
Would you mind taking a quick look @evanpurkhiser? If not kick it back to me and I'll get perf or visibility on it. Thanks!

**Comment by saippuakauppias** [comment]
@evanpurkhiser @mjq-sentry , any info? Our graphs still broken :(

**Comment by adiletkabylbekov** [comment]
fixed with adding config option `TIME_ZONE` to configuration file sentry.conf.py

example:
```
TIME_ZONE = "Asia/Bishkek"
```

**Comment by saippuakauppias** [comment]
Unfortunately, setting `TIME_ZONE` fixes some charts, but breaks others.

I did not have time to take screenshots, already rolled it back.

**Comment by saippuakauppias** [comment]
Any info?

**Comment by saippuakauppias** [comment]
Problems still here (

**Comment by MichaelSun48** [comment]
I believe this has been fixed, though I can't find the exact PR that did so. Going to close for now, but feel free to reopen if it is still happening:


Timezone being respected in dashboards:

![Image](https://github.com/user-attachments/assets/c7b7d710-ebf3-4317-a8b2-aabdc0d3be0e)

Timezone being respected in issues chart:

![Image](https://github.com/user-attachments/assets/9afb883f-10ba-498c-85cf-3920c08c5987)
