### ISSUE TITLE
how can i add a custom plugin ?

### ISSUE THREAD

**Issue by peiquan** [getsentry/sentry#4438]
the setup.py file 
`
from setuptools import setup, find_packages

install_requires = [
    'sentry>=8.0.0',
]

setup(
    name='sentry-yysms',
    version='1.0.0',
    author='zhupeqiaun',
    author_email='zhupeqiaun@yy.com',
    url='',
    description='A plugin for Sentry which sends SMS notifications via yysms',
    long_description=__doc__,
    license='BSD',
    packages=find_packages(exclude=['tests']),
    zip_safe=False,
    install_requires=install_requires,
    include_package_data=True,
    entry_points={
        'sentry.apps': [
            'sentry_yysms = sentry_yysms',
        ],
        'sentry.plugins': [
            'sentry_yysms = sentry_plugins.sentry_yysms.plugin:YysmsPlugin',
        ]
    },
    classifiers=[
        'Framework :: Django',
        'Intended Audience :: Developers',
        'Intended Audience :: System Administrators',
        'Operating System :: OS Independent',
        'Topic :: Software Development'
    ],
)
`
pip install successfully, but i can't find the plugin in the sentry , how could i do ?

**Comment by mattrobenolt** [comment]
This path appears to be wrong: `sentry_plugins.sentry_yysms.plugin:YysmsPlugin`. Seems like the `sentry_plugins` part is extra for you. You probably see this erroring when you start up the processes. We dump plugin inititialization errors to console.
