### ISSUE TITLE
Replace usage of request.build_absolute_uri with absolute_uri

### ISSUE THREAD

**Issue by scefali** [getsentry/sentry#44424]
### Problem Statement

In some cases, the use of `request.build_absolute_uri` is breaking features for self-hosted users who have a proxy in front. For example, we generate an incorrect redirect URI for social auth plugins like Asana (see https://github.com/getsentry/sentry/blob/master/src/social_auth/backends/__init__.py#L361). `absolute_uri` builds with `url-prefix` while `request.build_absolute_uri` builds the URL based on the host of the request which might not be the domain a user accesses their self-hosted instance if they have a proxy.

### Solution Brainstorm

We should go through each instance of `request.build_absolute_uri` and see if we can replace it with `absolute_uri`

**Comment by floels** [comment]
Hi @scefali,

I started working on a solution in [this PR](https://github.com/floels/sentry/pull/1).

Is this what you had in mind? Let me know if you have comments, knowing that this is my very first PR on GitHub 🐣
