### ISSUE TITLE
Raw Stacktrace" functionality buried 

### ISSUE THREAD

**Issue by pcsmchristine** [getsentry/sentry#44478]
### Problem Statement
 Sentry's presentation of the stacktrace has always been a workflow obstacle & pain point for us.  
We nearly always need to click the "Raw" button because:
1- We copy & paste the full raw stacktrace into IntelliJ for debugging & analysis (very important).
2- We prefer to see the stacktrace in a familiar format.

I've requested that the "RAW/Pretty" selection be sticky or a preference to smooth our experience.  Instead the UX has gone the other direction by adding more clicks for us by burying the "Raw Stacktrace" functionality under a new "..." menu.  This would be acceptable if the checkbox was sticky & persisted between issues & sessions, but it doesn't, so it's just extra clicks & harder to find.

**Comment by priscilawebdev** [comment]
cc @Jesse-Box

**Comment by priscilawebdev** [comment]
Thank you for reporting this issue 🙏  I have added a ticket for it to our backlog and we will investigate. As soon as we have more info, we will post it here

**Comment by Jesse-Box** [comment]
Hey @pcsmchristine,

It's very unlikely that we'll work on this right now, given we haven't received any feedback similar to your own. However, we can always act if that changes :)
