### ISSUE TITLE
Long User IDs and Wrapping

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#4447]
They dont display overly well when, for example, the user ID is a UUID (32 character string).

**Comment by bsergean** [comment]
Here are two examples, one where the wrapping works fine, and one where the wrapping fails.

![screen shot 2016-10-28 at 11 44 58 am](https://cloud.githubusercontent.com/assets/11857745/19818805/54689cde-9d06-11e6-8781-7e0a2f7c2034.png)

![screen shot 2016-10-28 at 11 44 52 am](https://cloud.githubusercontent.com/assets/11857745/19818813/5b86259a-9d06-11e6-9f7a-4e7964bec0ac.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
