### ISSUE TITLE
Close Account doesnt load the page

### ISSUE THREAD

**Issue by mkosir** [getsentry/sentry#44497]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Go to User Settings -> Close Account

### Expected Result

Be able to close account.

### Actual Result

![Screenshot 2023-02-13 at 15 20 10](https://user-images.githubusercontent.com/3073826/218484267-2231476e-d7ff-4114-8a5c-4a347ff9c08a.png)
![Screenshot 2023-02-13 at 15 22 16](https://user-images.githubusercontent.com/3073826/218484280-17f893b9-f473-4187-913f-2b5041c54ada.png)

**Comment by souredoutlook** [comment]
Related to [INC-304. ](https://getsentry.atlassian.net/browse/INC-304)

**Comment by cathyteng17** [comment]
This was the problematic PR, reverting now https://github.com/getsentry/sentry/pull/44182
