### ISSUE TITLE
[Slack Notifications] Show Tag Key:Value Pairs On Same Line

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#44491]
### Problem Statement

Without tags, Slack notifications look quite fancy. Including the `market` tag here, the alert is a lot larger than need be.

![image](https://user-images.githubusercontent.com/51749023/218393912-432cf7ac-d4e8-4ac3-8b8c-ce3e29e84645.png)

### Solution Brainstorm

putting key and value inline is quite the improvement already 

![image](https://user-images.githubusercontent.com/51749023/218394337-5208c4a2-0010-4121-a084-9c8ff19860b0.png)

You could also experiment with "Context" slack block, and maybe link to Sentry issues tagged respectively.

**Comment by souredoutlook** [comment]
Hi @jeengbe thanks for requesting this feature - I added the enhancement label and tweaked your title, feel free to change it back if that's your preference.

**Comment by jeengbe** [comment]
Wonderful, thanks a lot!

**Comment by armenzg** [comment]
Thank you @jeengbe !

Backlogged:
https://getsentry.atlassian.net/browse/WOR-2707

**Comment by ceorourke** [comment]
We've changed the format of tags along with a number of other improvements you can read more about [here](https://docs.sentry.io/changelog/more-context-in-slack-alerts/).
