### ISSUE TITLE
Replay crumb data can be any type due to custom breadcrumbs

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#44498]
This is probably typed incorrectly - we don't know what type crumb.data will be due to custom breadcrumbs. We expect it to be an object of sorts, but it can be anything (e.g. breadcrumb). This throws type errors in Replay Details if it is non-object.

**Comment by ryan953** [comment]
@billyvg did i see a fix go out for this?

**Comment by billyvg** [comment]
@ryan953 [Not a fix](https://github.com/getsentry/sentry/pull/44501) that addresses the typing

**Comment by ryan953** [comment]
Fixed with the new `*Frame` type system that the SDK exports
