### ISSUE TITLE
[Integration Platform] Reflect API Scopes in Automatically Generated Integration Description

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry#44527]
### Problem Statement

An API integration can request read-only permissions for various Sentry resources but the description implies that it can read and update resources (if permission is granted).

### Solution Brainstorm

For some integrators and end-users this language may be to vague. Consider having the message reflect the token scopes or changing the language to point to the scopes for details about how the resources are used by the integration.

(follow up from private discussion with @ceorourke)

**Comment by armenzg** [comment]
@ceorourke Hi! Would you be able to add more details to the issue?

**Comment by ceorourke** [comment]
Hi Armen, when we select integration features it automatically generates text from here: https://github.com/getsentry/sentry/blob/master/src/sentry/models/integrations/integration_feature.py#L77-L104 
Maybe we could just change the language here to reference the already listed out scopes?

**Comment by souredoutlook** [comment]
Thanks @ceorourke - just didn't want to lose track of the feedback. It seems low priority for now - so far this is feedback from a single individual
