### ISSUE TITLE
Default Sentry organization can be deleted without warning when SENTRY_SINGLE_ORGANIZATION is not set to True

### ISSUE THREAD

**Issue by bqbn** [getsentry/sentry#4453]
We're running Sentry v8.3.3, and the SENTRY_SINGLE_ORGANIZATION is False by default.

We were able to delete the default Sentry organization without being warned. After the default Sentry organization is deleted, we see the following errors in the log:

```
sentry[2688]: [ERROR] Unable to fetch ProjectKey for internal project
sentry[2688]: Traceback (most recent call last):
sentry[2688]: File "/data/sentry/venv/lib/python2.7/site-packages/sentry/templatetags/sentry_react.py", line 66, in _get_public_dsn
sentry[2688]: )[0]
sentry[2688]: File "/data/sentry/venv/lib/python2.7/site-packages/sentry/../django/db/models/query.py", line 132, in __getitem__
sentry[2688]: return list(qs)[0]
sentry[2688]: IndexError: list index out of range
sentry[2688]: [ERROR] Internal project (id=1) does not exist
```

According to our chat in IRC, @mattrobenolt thinks that 

https://github.com/getsentry/sentry/blob/8.3.3/src/sentry/web/frontend/remove_organization.py#L31-L35

should have warned about the deletion operation but it didn't.

This is to request that the above lines of code be looked at and see if the above described behavior (no warning before deletion of the default Sentry organization) is expected and have it warn properly if not.

**Comment by cristim** [comment]
I also deleted it and I keep getting errors like that now that I switched my on-prem setup to the Docker-based installation method.

I had re-created the Sentry organization with another ID and I used to have a configuration override where I set the new project ID, but that is no longer supported in the Docker image.

**Comment by BYK** [comment]
Why do you need this (if it is still relevant to you). The default org contains the default internal project for Sentry to self-report so I expect this not being so easy to change for any value it adds.

**Comment by cristim** [comment]
I'm no longer running a Sentry installation, and it's been so long ago that I don't remember in detail about this issue.

Hopefully @bqbn can remember more about this.
