### ISSUE TITLE
Searching for `issue:<issue-short>` should work with issue platform dataset

### ISSUE THREAD

**Issue by barkbarkimashark** [getsentry/sentry#44539]
Not totally sure if this is a bug or not but we need to verify search queries like `issue:<issue-short>` properly query the right dataset.

**Comment by ceorourke** [comment]
I looked into this a bit, you can query by directly using the short ID which works fine, but `issue:<short ID>` where the short ID is a performance issue hits a 500 on the `OrganizationGroupIndexStatsEndpoint`. 

Here's an issue I triggered trying to do it:

https://sentry.sentry.io/issues/3939241477/events/2f60c4bca379417886a0e140aa28a8b9/?project=1&referrer=issue-list&statsPeriod=14d

**Comment by barkbarkimashark** [comment]
So I think this error is related to this PR we merged in that adds support for conditions like `issue:<issue-short>`
https://github.com/getsentry/sentry/pull/43851/files#diff-90100cbf11fb4a0d40a6e28d03ccce84855cb027e9c74dc0ce3fbfd0fa8d95cdR907-R914

It looks like the query from `OrganizationGroupIndexStatsEndpoint` isn't removing the extra condition on the issue short ID (this is a special case where instead of querying the tag, we resolve the short through postgres). We might need to Centralize that bit of code that converts the `SearchFilter` -> `Condition` and update the GroupStream to do that extra step.
