### ISSUE TITLE
Can't delete release

### ISSUE THREAD

**Issue by dtlhlbs** [getsentry/sentry#44567]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Ensure the below release has no issues, then:

`C:\bin\sentry-cli-Windows-x86_64.exe releases delete -o <org> -p <project> "app@999.9"`

Note that viewing this release on the dashboard shows "2 new issues", however there are no issues, as I have deleted them. This breaks the non-UI method to delete releases, since there is no delete release function on the UI.

 I'm testing releases, so I am creating test releases. Not having the ability to delete test releases during and after testing is frustrating.

### Expected Result

Release with no issues is deleted

### Actual Result

```
error: API request failed
  caused by: sentry reported an error: This release is referenced by active issues and cannot be removed. (http status: 400)
```

Yes this is a duplicate of #5701.. and #19629 and #23286. Seems like a problem.

**Comment by armenzg** [comment]
Thanks for reporting @dtlhlbs !

As mentioned in the other issue we do not plan to fix this. We're happy to review any fixes for it but this is not high priority to fix.
