### ISSUE TITLE
sourcemap urlprefix setting

### ISSUE THREAD

**Issue by KobeZhou** [getsentry/sentry#44568]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.1.1

### Steps to Reproduce

1. Example：config.plugin("sentryCliPlugin").use(sentryCliPlugin, [
       {
        release: "",
        include: "",
        ignore: [],
        configFile: "sentry.properties",
        urlPrefix: "www.xx.com/1/static/js",
      },
    ]);

2. my static resource is deployed by CDN， so the urlPrefix is dynamic；For example， this url of static resource is ‘http:// www.xx.com/1/static/js’  this time,   and next time, the url of static resource is ‘http:// www.xx.com/2/static/js’ ;
3. how to handle the urlPrefix。

### Expected Result

 I can use sourcemap correctly in sentry。

### Actual Result

 I do not konw how to do。

**Comment by hubertdeng123** [comment]
The first thing I'd ask here is if it is absolutely necessary to have a dynamic url? How often does the url change? I'm not sure how we would be able to support that.
