### ISSUE TITLE
Quota exceeded notification is not sent to Owner

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#44571]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1, the user has Owner role
2, the Owner's email address is not on the bounce list
3, the quota notification emails are enabled for both 100% and 80%
![Screenshot 2023-01-24 at 20 38 08 (1)](https://user-images.githubusercontent.com/25980868/218734737-180f37af-e8f4-44d7-b6c6-8a33324d4217.png)

### Expected Result

the user should receive the quota notification emails for errors and transactions

### Actual Result

the user does not receive the quota notification emails for errors and transactions

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1744) by [Unito](https://www.unito.io)

**Comment by madsnedergaard** [comment]
Hi, I am the one who reported this and it just happened again: An email notification was sent to the Billing Email we have listed, but not to me as an Owner.

<img width="707" alt="Screenshot 2023-03-16 at 11 02 20" src="https://user-images.githubusercontent.com/3296643/225583510-3fe08d10-f22d-48b3-9bec-93c10a407c84.png">
<img width="859" alt="Screenshot 2023-03-16 at 11 02 30" src="https://user-images.githubusercontent.com/3296643/225583516-ed7b8356-571d-43f9-8dd1-8583d5ad8cee.png">

This is quite frustrating as we would like to separate billing and technical ownership, but I never get notified if anything is going wrong with monitoring and suddenly we are charged an excessive amount :(

**Comment by markstory** [comment]
Hey @madsnedergaard I took a look through our logs and found that only the email to the subscription's billing email address was sent. Do you happen to have a member in the organization that shares an email account with the subscription billing e-mail address?

**Comment by madsnedergaard** [comment]
> Hey @madsnedergaard I took a look through our logs and found that only the email to the subscription's billing email address was sent. Do you happen to have a member in the organization that shares an email account with the subscription billing e-mail address?

Thanks for taking a look :)

Yes, we did receive the email on the supplied billing email address and someone forwarded it to me. The issue is that I would like to receive the notifications (as I am the owner on Sentry), as I do not have access to the billing email address.

**Comment by markstory** [comment]
I wanted to give an update on this as it has been a few days. I've been able to reproduce the issue you're having and been able to track down the source. I'm hoping to have a solution ready in the next few days.

**Comment by madsnedergaard** [comment]
Great, thanks for fixing this! :)
