### ISSUE TITLE
Filtering transactions broken on Performance Overview

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#44603]
### Environment

SaaS (https://sentry.io/)

### Version

n/a

### Link

n/a

### DSN

n/a

### Steps to Reproduce

n/a

### Expected Result

On the Performance Page, I should be able to filter for transactions by tag, for example. Pressing on the search bar, however, does nothing, and inputting filters manually, returns No Transactions Found.

![image](https://user-images.githubusercontent.com/51749023/218818711-dcb4afe0-ed7a-4a14-b86f-60be0bf36cd5.png)

### Actual Result

Compare this to the Transaction Summary page, focusing the search bar opens the following dropdown:

![image](https://user-images.githubusercontent.com/51749023/218818827-ffc98ee8-bb3a-4a39-84bc-427da3f89454.png)

**Comment by udameli** [comment]
Hi @jeengbe 👋 The landing page search is meant to help you find particular transactions, so it only supports transaction name search. I'm going to resolve this issue for now.

Could you share the use case for searching by tags on the landing page? We specifically narrowed it down to transactions because that was the most used filter but I'm curious about other use cases.

**Comment by jeengbe** [comment]
Hey @udameli! 

That's most unfortunate to hear.

In my case, we are running multiple deployments in multiple regions with transactions tagged accordingly. In order to better understand how just a single market was performing (generally, not limited to specific transactions), I wanted to filter the overview page to only account for transactions from that very market I was interested in.

The other reason I can think of from the top of my head is when dealing with cross-transaction A/B experiments. In order to compare variants with each other, filtering to only include transactions with, again, a certain tag, would be very helpful.

**Comment by udameli** [comment]
Thanks for sharing your use case @jeengbe! We're collecting feedback for the landing page search changes so this is super helpful! 

Meanwhile, for the use case you described, Discover search should give you the results you're looking for.

**Comment by jeengbe** [comment]
Hi @udameli, great to hear! Feel free to ask further questions, I'd be happy to input my thoughts.

How exactly does the Discover page work for the described case? This page only appears to show errors over time, but I'm specifically interseted in transactions.

**Comment by udameli** [comment]
You should be able to filter by event type like so `event.type:transaction`. Let me know if that worked :)

**Comment by jeengbe** [comment]
I see now, thanks :)

Unfortunately, the Discover page appears not to bear as many nice functions as the Performance overview page does. This graph and a list of spans is all I can see on that page. If we had the Business plan, I could get a breakdown-like view of tags, but that's about it.
![image](https://user-images.githubusercontent.com/51749023/219802321-030e6295-7eb2-494c-807b-9afc8e96de48.png)

No way near the features the performance overview provides.

Correct me if I'm wrong, but doesn't it like a fairly simple thing to add those filters to the overview page as well? :)

**Comment by jeengbe** [comment]
Hi @udameli!

Coming back to this issue, it's a fairly big issue for me that this doesn't work. The performance overview tab gives a wonderful overview of transactions (e.g. web server). Those, however, consist of both SSR routes and other miscellaneous stuff, such as redirects, GraphQL, session handling etc. All transactions are tagged accordingly.
I would now very much like to only filter for `type:route`, for example, to get an understanding of how routes (and only routes) are performing. As far as I'm aware, there is no real way of doing this at the moment.

**Comment by udameli** [comment]
Hi @jeengbe, 

If I understand your setup correctly, you want to filter events in Discover by a specific tag, correct? If so, you should be able to filter by custom tags or by other searchable properties ([docs](https://docs.sentry.io/product/sentry-basics/search/searchable-properties/)). Does that help your use case?

**Comment by jeengbe** [comment]
Hello @udameli,

no, it is not. I want to be able to filter them in the Performance Overview page: 
![image](https://user-images.githubusercontent.com/51749023/221244052-61db1f63-a227-4b85-896b-d3afccf02517.png)

The following edited screenshot shows what I am trying to explain in words:
![image](https://user-images.githubusercontent.com/51749023/221244760-ff7b3e42-5bf6-49ab-bce4-fdb0f9d93355.png)

**Comment by udameli** [comment]
> 

The filters you've used in the screenshot above should work in Discover. Returned events, however, will be displayed in a single table. I see that you want a curated dashboard similar to what we have on the Landing page. You could upgrade to a business plan where you could add custom columns to the Discover table (like `p50(transaction.duration`) and/or re-create those widgets as your custom dashboard (also a business plan feature) and apply any filter you'd like. I'd say creating a custom dashboard is your best bet and we're happy to set up a trial for that. You can request additional help [here](https://help.sentry.io/).
