### ISSUE TITLE
warning line in log during uptick of sentry version

### ISSUE THREAD

**Issue by silpol** [getsentry/sentry#44607]
### Self-Hosted Version

23.1.1

### CPU Architecture

x86_64

### Docker Version

23.0.0

### Docker Compose Version

1.29.2

### Steps to Reproduce

previous Sentry version was 22.2.0

1. unzip new version
2. run ./install.sh
3. get warning line (second one, first one about ca-certs is for context where it happens)

### Expected Result

no warnings

### Actual Result

> Running hooks in /etc/ca-certificates/update.d...
done.
> /usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py:243: DeprecationWarning: `structlog.threadlocal` is deprecated, please use `structlog.contextvars` instead.
  WrappedDictClass = structlog.threadlocal.wrap_dict(dict)

**Comment by hubertdeng123** [comment]
I believe this can be routed to the backend team

**Comment by hubertdeng123** [comment]
going to put this one on the backlog since it's not a priority

**Comment by markstory** [comment]
This deprecation warning was addressed in #44831
