### ISSUE TITLE
Replay Details: update copy on the 'inspecting the DOM tree' message

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#44602]
**Problem:**

We've received a number of internal reports from developers that it is unclear what action to take from the current banner message to inspect the DOM on the replay player.

![Image](https://user-images.githubusercontent.com/77064737/218818102-9e97d65d-b7c0-4cdd-bd70-dd7999e4c783.png)

**Solution:**

Reword the banner copy to say "You can right click and inspect elements inside the player window." for clarity.

**Comment by ryan953** [comment]
Just sticking the text in is the easy part, gotta fix the overflow/wrapping: 

![SCR-20230214-dzj](https://user-images.githubusercontent.com/187460/218820889-aea6cb64-4bf8-419c-bc0c-db9107fa254a.png)


We can revisit this later

**Comment by ryan953** [comment]
Other copy suggestion, it's shorter so there will be fewer css issues:
> right click & inspect your app’s DOM with your browser


Also suggested: put in the shortcuts (per browser) `cmd+shift+c` or whatever

Also: we could change the icon to match the browser

**Comment by ryan953** [comment]
I'll stick `right click & inspect your app’s DOM with your browser` in there and see how we're doing space wise. 

It's a better sentence (hopefully) and we're not going to mess with CSS this time around. So we'll ship that, close the ticket, and if we want to iterate again with css changes then we'll open a new ticket and do it.
