### ISSUE TITLE
Sentry + Linear Integration - Issue not resolved when marked as complete on Linear.

### ISSUE THREAD

**Issue by unreleased** [getsentry/sentry#44609]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Hi there,

I am using the Linear integration, whenever I mark a linked issue as "Complete", Sentry does not mark the issue as resolved. I hope this is the correct place to post about the issue. I am unsure if this is a Linear or Sentry issue.

The issues are correctly linked.

1. Throw an error.
2. Sentry catches the error and creates an issue on Linear
3. I mark that issue on Linear as "Complete"
4. I click the link from that issue to the Sentry page and can see it has not been marked as resolved.

### Expected Result

I expect Sentry to mark the issue as Resolved, as mentioned here: https://linear.app/docs/sentry 

* I did change my email on Linear from my corporate to personal for testing this, but it still did not resolve on Sentry.

### Actual Result

Did not mark the issue as resolved.

**Comment by brianthi** [comment]
Hi @unreleased, to help us triage this issue can you create a support ticket (https://help.sentry.io/) to provide us your org slug, or provide your DSN on this GH issue.

**Comment by rbisol** [comment]
As per https://docs.sentry.io/product/integrations/issue-tracking/linear/
The linear integration is supported by Linear (the integration's creator).

I was not able to reproduce the issue, for some reason, I do not have the option to mark an issue as complete, only as done. Might be a limitation of my Linear account. 

Here is the information on my test org:
Issue link: https://dev-curumas.sentry.io/issues/3882065585/
Status in linear
![Screenshot 2023-02-16 at 08 34 11](https://user-images.githubusercontent.com/64906376/219298179-b25cf03d-fa57-4e43-9365-923d0b53ec7e.png)


@brianthi internal ticket with the customer information: https://sentry.zendesk.com/agent/tickets/80352

**Comment by unreleased** [comment]
Thanks for the reply @rbisol,

When I said to mark the issue as Complete, I meant the Workflow category as I know the word "Done" is customizable. But yes, I do mean mark as done.

The same issue also applies to changing the Assignee, which also does not update on slack.

Do you know how I would contact Linear in regards to this issue if that would be more appropriate and relevant to them

**Comment by rbisol** [comment]
Hi Conor, sorry for the delay.

I checked Linear.app website for means to contact and I found the address `support@linear.app`. And when logged in, you can click on `Help & support` in the bottom left corner, and then `Contact linear Support` in the bottom right. 

When contacting them mention the integration was created by them and Sentry pointed you in their direction. If Linear needs something from our side to work on the issue, they can reach out to us directly and we will be able to help them.
