### ISSUE TITLE
Slack Integration Problem

### ISSUE THREAD

**Issue by mpechner-akasa** [getsentry/sentry#44618]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.11.0

### Steps to Reproduce

Access to slack is SAML login via jumpcloud.  Not sure if that is the issue.
I did login to slack via the browser for this.

settings -> integrations -> slack->add workspace
then. I get
<img width="611" alt="Screenshot 2023-02-14 at 12 04 45 PM" src="https://user-images.githubusercontent.com/114946732/218853109-59dbcb32-416e-49e2-904d-623f6a9390c2.png">

### Expected Result

add my workspace

### Actual Result

<img width="611" alt="Screenshot 2023-02-14 at 12 04 45 PM" src="https://user-images.githubusercontent.com/114946732/218853635-cda6bb2d-2d34-4c12-bc80-13fa173416fd.png">

**Comment by armenzg** [comment]
Since you're using Self-hosted, does it make sense to follow these instructions?
https://develop.sentry.dev/integrations/slack/

**Comment by scefali** [comment]
Make sure you set these in your `sentry.conf.py` file as explained in the instructions Armen posted
```
SENTRY_OPTIONS["slack.client-id"] = "YourId"
SENTRY_OPTIONS["slack.client-secret"] = "YourSecret"
SENTRY_OPTIONS["slack.signing-secret"] = "YourSigningSecret"
```

**Comment by mpechner-akasa** [comment]
Thanks I was finding  different documentation. This will let me get it done.
Google search: sentry slack integration
First link: https://sentry.io/integrations/slack/

Even from: https://docs.sentry.io/
Search for slack
Install slack:  https://docs.sentry.io/product/integrations/notification-incidents/slack/
configure slack: https://docs.sentry.io/product/integrations/notification-incidents/slack/

I would say there is a bug in the documentation.

**Comment by armenzg** [comment]
I'm glad this got figured out. I will pass the note about docs.
