### ISSUE TITLE
HTML-encoded subject

### ISSUE THREAD

**Issue by fribergr** [getsentry/sentry#4462]
When Sentry sends a mail showing that we got multiple notifications in a project, the subject-header of the email seems to be HTML-encoded.

For example:
```[Sentry] [Robin &amp; David Forum] 2 notifications since Nov. 1, 2016, 2:29 p.m. UTC```

**Comment by tkaemming** [comment]
This was fixed with GH-4172 and was already released as part of 8.9.0.
