### ISSUE TITLE
Set Client Key rate limit via API

### ISSUE THREAD

**Issue by vladimir-kozyrev** [getsentry/sentry#44652]
I am following up on Zendesk request N80310. The support team said it is impossible to set the rate limit via API.

### Problem Statement

Client keys without a rate limit can consume the total error limit available to the organization.
This is not ok because it forces us to pay more for the things we do not want.
Setting the limit manually for each key is tedious and we are living in 2023 where such things should be automated if possible.

### Solution Brainstorm

1. Set the limit for the default key at the project creation. As far as I can see, every new project has a default key tied to it.
2. Allow setting and changing the rate limit for each key after they are created.

**Comment by olksdr** [comment]
If I got your correctly, you would like to configure the rate limits via API. That's should definitely be possible:
* see the following docs on how to [update the client keys](https://docs.sentry.io/api/projects/update-a-client-key/)
* send the following payload, e.g. 5 minutes window with 1000 events - `{"rateLimit":{"window":300,"count":1000}}`

Basically it should look like 
```bash
> curl https://sentry.io/api/0/projects/{organization_slug}/{project_slug}/keys/{key_id}/ \
 -H 'Authorization: Bearer <auth_token>' \
 -X PUT \
 -H 'Content-Type: application/json' \
 -d '{"rateLimit":{"window":300,"count":2000}}'

```

Hopefully this will help to get desire results.

**Comment by vladimir-kozyrev** [comment]
Thanks @olksdr! I will try that.

**Comment by jernejstrasner** [comment]
@vladimir-kozyrev have you had a chance to try this yet? Let us know if you're still having problems.

**Comment by olksdr** [comment]
Closing this as non-active. 
Please, re-open if there is more information available or there are more questions about this topic.
