### ISSUE TITLE
Unsubscribing from marketing emails is currently not possible

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#44653]
### Environment

SaaS (https://sentry.io/)

### Link

https://www.sentry.marketing/UnsubscribePage.html

### Steps to Reproduce

1. Go to https://www.sentry.marketing/UnsubscribePage.html
2. Enter any email address 
3. Click on "Unsubscribe"
4. The POST request (https://www.sentry.marketing/index.php/leadCapture/save2) gives a 400 error and the user receives a "Submission failed, please try again later"

### Expected Result

To be able to unsubscribe from marketing emails

### Actual Result

Currently, you cannot unsubscribe from marketing emails

**Comment by scefali** [comment]
We're on this. As a temporary workaround, you can unsubscribe here: https://sentry.io/contact/unsubscribe/

**Comment by DaveRosenthalSentry** [comment]
This has been open for ages. Should the broken version (.marketing) just be taken down? (It seems like maybe there is a new URL that works for this?

**Comment by DaveRosenthalSentry** [comment]
It appears the (outdated) link from the OP issue is working. Closing this issue.
