### ISSUE TITLE
Replay: Visualize Redux State

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#44662]
### Problem Statement

Session Replay has the timeline of events and a visual replay of the web page.
It's not clear how the redux state changes affected the site.

### Solution Brainstorm

Have a tab that displays the Redux state changes similar to:

https://github.com/reduxjs/redux-devtools

Relates to: https://github.com/getsentry/sentry-javascript/issues/6266

**Comment by billyvg** [comment]
Transferred this out of SDK repo as right now we have redux breadcrumbs, and it's more on the UI to display them (outside of breadcrumbs).

**Comment by billyvg** [comment]
I don't think we're going to have library-specific integrations into the Replay UI given the constant change of frontend. We think the breadcrumbs are useful as they are and we won't be pursuing a redux specific visualizer.
