### ISSUE TITLE
Crons: SDK for Python

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#44687]
This issue tracks adding Crons to our Python package.

**Is this issue important to you?**
Please feel free to upvote or provide your feedback, we'd love to hear more about your use cases.

**Comment by gaprl** [comment]
Reposting [Azkae](https://github.com/Azkae) comment from #42767:
> ### Problem Statement
> I would like to setup cronjob using the SDK.
> 
> My use case: I have a celery task in Python that must run everyday and I want to monitor it. Since my task runs in celery, I don't have an entrypoint to use `sentry-cli monitors run [...]`.
> 
> I would like to call a function in the sentry SDK to start monitoring a cronjob.
> 
> I could also call the two HTTP requests directly but I didn't find them in the docs.
> 
> ### Solution Brainstorm
> An usage could be:
> 
> ```
> # This function is called everyday
> def my_task():
>     with sentry_sdk.start_cronjob("<monitor_id>"):
>         ...
> ```

**Comment by TheBlusky** [comment]
What about auto integration / registration with celery scheduled tasks ? Everything might be in code :

- Tasks are already in a python decorator (such as `@app.task`)
- Schedule can be retrieved in the task manager (default in beat_schedule)

Manually  registering a monitor_id might be a pain for developer experience. If the SDK can auto register jobs, it might make developer life easier.
