### ISSUE TITLE
Crons: Fix the subsort

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#44686]
![Image](https://user-images.githubusercontent.com/1900676/218558703-4355109a-1644-4e10-964a-93814df553b8.png)

We need to make sure that there’s two sorts applied here:

1. Status
2. Time of last check-in

In the example above the check-in that happened 9 minutes ago should be at the top and the one from 2 years ago should be at the bottom.

**Comment by evanpurkhiser** [comment]
This is done in #44703
