### ISSUE TITLE
event data is missing in the periodic reporting

### ISSUE THREAD

**Issue by Chengshihao1018** [getsentry/sentry#44730]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.10.0

### Steps to Reproduce

i write a demo with data regularly senting to sentry, the main code shows below
![image](https://user-images.githubusercontent.com/31720199/219292688-70d07df1-3c11-4f8f-af42-5f05ff5a0eaa.png)

but i couldn't get whole event data in sentry,as shown below,the data between 41 to 59 was missing
![image](https://user-images.githubusercontent.com/31720199/219293147-2ec75dea-2569-47ca-8343-92d9bdb84897.png)

here is the specific parameters in 41
![image](https://user-images.githubusercontent.com/31720199/219293457-7a205b1a-4b2e-436d-b72f-08e7ad64aefb.png)

and this is in 59
![image](https://user-images.githubusercontent.com/31720199/219293559-a5ac3e13-3510-48d5-b399-c7cac1fe3e13.png)

and this is the logs generated by the client side, the data was generated regularly
![image](https://user-images.githubusercontent.com/31720199/219293911-ec0a4620-7054-4c01-b89f-f687561bf03a.png)

and the ratelimit in project like below,It doesn't look like being restricted anymore
![image](https://user-images.githubusercontent.com/31720199/219294157-52553670-a1c7-46e4-a5b8-3677a7954681.png)

what could cause this problem?

### Expected Result

sentry should show data regularly

### Actual Result

missing some data in regular time.
![image](https://user-images.githubusercontent.com/31720199/219294511-f7ff7176-911f-470d-ac85-e80430172076.png)

**Comment by hubertdeng123** [comment]
Hi there, maybe it's possible the data has been dropped. Could you check network logs?

**Comment by Chengshihao1018** [comment]
> Hi there, maybe it's possible the data has been dropped. Could you check network logs?

It doesn't look like a network problem.we can observe this phenomenon in every hour.we lose a few minutes data in every hour.

**Comment by hubertdeng123** [comment]
Can you check snuba logs to see if there's anything helpful there?

**Comment by Chengshihao1018** [comment]
> Can you check snuba logs to see if there's anything helpful there?

which module should i see?snuba-consumer or snuba-subscription-consumer-events?

**Comment by Chengshihao1018** [comment]
i find the reason, the kafka partition is too small,and some data was dropped,i have expanded kafka.and it seem to work fine,thx
