### ISSUE TITLE
Sentry Stop the Collecting - 403 dropped envelope: invalid data 

### ISSUE THREAD

**Issue by Natgho** [getsentry/sentry#44732]
### Environment

SaaS (https://sentry.io/)

### Version

23.1.1

### Steps to Reproduce

I am using a self hosted sentry build on docker-compose. Sentry suddenly stopped reading error messages. When I checked the logs, I saw that all packages started returning 403 error messages.
![image](https://user-images.githubusercontent.com/6623948/219309156-50fc80c3-373a-418e-bba9-a5d801e2e488.png)
When I renewed my DSN key, I saw that the error was resolved. However, it has been 3 days since I started using sentry. Renewing the DSN key every 3 days is probably not a normal situation.

### Expected Result

It should work properly :)

### Actual Result

All incoming packets are rejected when data should continue to flow. Error on Django side;
![image](https://user-images.githubusercontent.com/6623948/219309780-3a79161f-6c7d-4f8a-87b0-a9a6e830cdd8.png)

**Comment by hubertdeng123** [comment]
I don't think you need to be rotating DSN keys every 3 days and I'm curious to why it stopped working in the first place. In fact, you shouldn't really need to ever touch that at all so this seems to me like an edge case scenario. Could you keep me updated on whether or not this happens again?

**Comment by Natgho** [comment]
Then let me confuse them thoroughly by giving more interesting information. I went back to the old DSN and it started working again, great bug :D If I encounter the same error again, I will write it with the logs.
