### ISSUE TITLE
Suspect commit not showing for new issue.

### ISSUE THREAD

**Issue by rbisol** [getsentry/sentry#44733]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Enable suspect commits as per doc: https://docs.sentry.io/product/issues/suspect-commits/#enable-suspect-commits
2. Send a test event from one of the changed files listed in the release

### Expected Result

The suspect commit shows in the event.

### Actual Result

No suspect commit.
Example issue: https://dev-curumas.sentry.io/issues/3939157286/events/1ed60d6bd2a64460b5f3f679f530ca7d/?project=5225844

- The integration is set and the Sentry app has access to all repositories in the account:
         - https://dev-curumas.sentry.io/settings/integrations/github/165248/
- Code mapping is set.
- The link from the event points to the correct file and line in GitHub
- The commit is added to the event's release: 
         - https://dev-curumas.sentry.io/releases/nocode/commits/?project=5225844
- The user is member of the organisation, has email verified and is part of project's team
- The commit is present in the sentry_commit table.
         - 2aa45934c1999b809637e6e9bec023bf9e79ebf4 
- GC logs returns:  "reason": "could_not_fetch_commit_context",

**Comment by rbisol** [comment]
Possibly linked to: https://github.com/getsentry/sentry/issues/38492

**Comment by armenzg** [comment]
[Backlogged](https://getsentry.atlassian.net/browse/WOR-2721).

**Comment by armenzg** [comment]
I'm going to close it against #38492 which makes sense.
