### ISSUE TITLE
Time graph in issues overview (and other places) does not respect 24-hour clock setting

### ISSUE THREAD

**Issue by Vilkku** [getsentry/sentry#4473]
<img width="326" alt="image" src="https://cloud.githubusercontent.com/assets/175621/19958577/0321b106-a1a9-11e6-8da3-e172fdf66b6d.png">

I have set my time display to 24-hour clock in my settings, however the graphs (in issues overview and other places, I suspect everywhere but I haven't confirmed) do not seem to take this setting into account. As you can see in the screenshot, it still uses AM/PM.

**Comment by sadlar** [comment]
我在使用sentry_wechat做报警日志的时候，遇到中文就会报错，无法提交信息到微信。
I use sentry_wechat to do the alarm log, when the Chinese will be reported to the wrong, you can not submit information to WeChat.
The error log ：
Warning: Incorrect string value: '\xE4\xB8\xAD\xE6\x96\x87...' for column 'message' at row 1
08:41:07 [ERROR] celery.worker.job: Task sentry.tasks.store.save_event[3d1024c2-768a-4563-960f-b5ec84af09fd] raised unexpected: Warning(u"Incorrect string value: '\\xE4\\xB8\\xAD\\xE6\\x96\\x87...' for column 'message' at row 1",) (data={u'hostname': 'celery@gabriel', u'name': 'sentry.tasks.store.save_event', u'args': '[]', u'internal': False, u'kwargs': "{'start_time': 1478162467.450588, 'cache_key': 'e:f60e58ffb7bd4d55930c041e99599d28:4', 'data': None}", u'id': '3d1024c2-768a-4563-960f-b5ec84af09fd'})

**Comment by MaxBittker** [comment]
@Vilkku thanks for the note, worth fixing

**Comment by Vilkku** [comment]
Thank you!
