### ISSUE TITLE
Consistent UI for primary meta data

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#44759]
## Problem
- With [#44345](https://github.com/getsentry/sentry/issues/44345) replacing all event tables with a hashed replay ID to help users find a specific replay, we need to show this replay ID in the details and index page now
- In the replay details page, we need to relocate the user identifier("[User Scrubbed]", IP address, email, or username) to accommodate the replay ID position in the header
- In the replay index, we have to show "[User Scrubbed]" when IP address are scrubbed from a replay
- In the replay index and details, we have to allocate more space for OS and Browser information

## Related Tickets
- https://github.com/getsentry/sentry/issues/44345 ← ⚠ This has to be completed before starting this ticket
- https://github.com/getsentry/sentry/issues/42784

## Designs
https://www.figma.com/file/fOXcP5EaaTnerWqrydnyCP/Exploration%3A-Index-v3?node-id=190%3A38289&t=Ps3r1Eoz1dHP0zF5-1

### Index
![Image](https://user-images.githubusercontent.com/6508377/220661749-5493c49a-b7ad-49d8-a552-1bcbdf03542f.png)
![Image](https://user-images.githubusercontent.com/6508377/220661748-3fd1e141-8e07-4b27-9d29-aa6f9de62342.png)

**Comment by jas-kas** [comment]
Re-posting my Slack message so tis not lost:

> Is there a way we can keep the user avatar and or the essence of it on the Index page? Right now, this list could be a list of transactions, or errors, or any random event, not immediately clear it a user session 

> I think the design of the tags on the Replay Details top-right with labels is good with me, makes it easy to understand what a user is looking at.
> Can we also see another version of these tags where errors == 0? Will it still be red? Still a fire icon?

**Comment by Jesse-Box** [comment]
Made the changes @jas-kas
