### ISSUE TITLE
Settings page (Early Adopter switch) should contain a link to the docs

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#44773]
### Problem Statement

> Opt-in to new features before they're released to the public

What does that mean? I just stumbled upon [a page in the documentation](https://docs.sentry.io/product/accounts/early-adopter/), but for months, I have been wondering what those "new features" are

### Solution Brainstorm

Link to the docs page from somewhere in that settings page:

![image](https://user-images.githubusercontent.com/51749023/219457938-3b1f605f-dbcb-4436-a375-08b0cbd9ddaa.png)
The link would take you to the docs entry.

This link would conflict with the label also reacting to click events, but that's something I would be happy to get rid of. These settings are very fundamental and shouldn't be changed on accident. But that's a different topic for a different [issue](https://github.com/getsentry/sentry/issues/44772). Literally.

**Comment by evanpurkhiser** [comment]
Good call @jeengbe!
