### ISSUE TITLE
[Thoughts] Working with A/B experiments

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#44779]
This is just a rough idea that needs a lot more input and refinement before proceeding with it. Perhaps, an official discussion about this and what people want/expect is also a good idea.

## Working with experiments
With Sentry already collecting a lot of data (both error- and performance-wise), supporting some way of working with experiments and comparing them only sounds like a natural next step.

### Current State

The only way I have found this to be possible today is by tagging events with the currently activated variant, and, for performance, going to Performance > Tags, and selecting the tag. This, sadly, only yields very little information. Precisely, I can lean no more from this than average duration. Unfortunately, not outstandingly helpful. It would already help a lot if I could choose what to display: 50th, 95th, mean, avg duration etc. 

![image](https://user-images.githubusercontent.com/51749023/219470243-e9540e19-3d80-4b69-b288-fa18182982fb.png)

### Comparing Tags Table
In the above table, it would be nice if you could select which metric to compare. Should be fairly simple. :)

### A/B Testing Page

![image](https://user-images.githubusercontent.com/51749023/219475867-1dfdd9cf-3423-4ed1-9130-3e8910fe6b5e.png) 

This page would feature a more extensive suite of tools useful for what is essentially comparing tags. Alternatively (or optionally), experiments would be created explicitly with defined goals (metric + filter, e.g. p50 on `route.type=react`).
With this would come pretty graphs that compared both variants in a single plot, and many other things I cannot think of right now.

### Integration with external providers

Just a vague thought. I have never worked with external feature switch services, so please, if you have suggestions on what can be done with external services, leave a comment.

**Comment by silent1mezzo** [comment]
Thanks for the request @jeengbe. At this point in time we're not going to be adding any A/B testing tools into Sentry. We personally use https://github.com/openflagr/flagr for flags and Amplitude for analytics while A/B testing.
