### ISSUE TITLE
Weird chars in JS stack trace

### ISSUE THREAD

**Issue by urbany** [getsentry/sentry#4477]
Hi guys, I have been using sentry without a problem but suddenly the errors stacktrace started showing some weird chars instead of my source code. I have tested the sourcemap in https://raygun.com/sourcemaps and its working correctly (used the link found in the current sentry version artifacts).

Here is an example of what I see:
![screen shot 2016-11-03 at 21 58 24](https://cloud.githubusercontent.com/assets/50884/19987609/f4f47472-a213-11e6-9cb2-4e7585eafa8c.png)

My guess is that it might have something to do with the server serving gzipped files.

Has this happened to anyone before? Any idea how I can fix this?

**Comment by MaxBittker** [comment]
how suddenly? this week?

**Comment by mattrobenolt** [comment]
This definitely seems to be because you've uploaded gzipped sources to us. Or if being fetched from the internet, they don't have the `Content-Encoding: gzip` header.

**Comment by urbany** [comment]
Wow, this is what I call fast reply, thanks for that!

@MaxBittker hmm might have been for more then a month but I only noticed now, so nevermind the sudden part.

@mattrobenolt I just reviewed my deploy process and I made a change that is uploading to sentry after the GZIP. So that's the problem.

Thanks guys.
