### ISSUE TITLE
Pressing on input labels in Organization Settings shouldn't toggle the input

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#44772]
### Problem Statement

This is more me voicing my opinion than a real feature request: Most of these settings should not toggle inputs just when clicking on the label. Sure, the bottom right toast gives good feedback on the action, but changing these settings at the core of the organization and security should require explicit toggling. The risk of accidentally doing something while browsing, or highlighting something, or what not are too high – especially in combination with immediate action instead of a submit button.

![image](https://user-images.githubusercontent.com/51749023/219459430-b72eb5c4-24df-46ec-9c29-2d99840fd580.png)

Just my thoughts on this :)

### Solution Brainstorm

Of course, there are confirmation alerts for severe actions like disabling 2FA, but in my opinion, instead of, for _some_ actions, requiring alert modals, make each action a more conscious one by requiring explicitly pressing the input. Where a modal is applicable for an extra warning, there is nothing hindering that.

**Comment by evanpurkhiser** [comment]
Hey @jeengbe,

We discussed internally a bit, I think we're going to keep it as is, since you can quickly undo the changes, and for toggles that are destructive they have confirmation modals.

**Comment by jeengbe** [comment]
Hi @evanpurkhiser,

I'm happy with having it had discussed :)
