### ISSUE TITLE
Creating a dashboard template (via Template → Add Dashboard) should immediately open the created dashboard

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#44783]
### Problem Statement

When you click "Add Dashboard" from a dashboard template it all it does is show a notification in the corner that its been created.

![image](https://user-images.githubusercontent.com/23610/219485356-be9c4149-a72a-49af-9c10-d9b68a16b54d.png)

Note: Creating a new dashboard via the "Create Dashboard" button opens that dashboard after you click "Save and Finish"

### Solution Brainstorm

When creating a dashboard via a dashboard template's "Add Dashboard", the newly created dashboard should be immediately opened.

**Comment by om-ray** [comment]
@dcramer @brentc I think this should be closed, the issue doesn't seem to happen anymore

**Comment by brentc** [comment]
It behaves as expected when starting from a scratch via the "Create Dashboard". But creating a dashboard from one of the templates, (e.g. General Template → + Add Dashboard) brings you back to the dashboards list instead of opening the new dashboard. I'll update the ticket accordingly.

**Comment by om-ray** [comment]
@brentc Hi, I've been working on this issue for the past few days, could you assign this issue to me?

**Comment by om-ray** [comment]
@dcramer @brentc Please review the [PR](https://github.com/getsentry/sentry/pull/48682) I made
