### ISSUE TITLE
External metric sources

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#44780]
### Problem Statement

With Sentry expanding its capabilities into the domain of performance monitoring, the idea of gathering metrics from more sources than what is ingested by SDKs comes to mind. In a way, what Grafana does. 

Right now, I can only think of GKE metrics for CPU/RAM usage, but I am pretty sure there are people with more use cases for this. 

If not, scrap this; it's merely an idea

**Comment by AbhiPrasad** [comment]
@jeengbe - thanks for writing in (and being super active with your feedback/questions).

We currently do have the ability to attach metrics to transactions via [custom performance metrics](https://docs.sentry.io/platforms/node/performance/instrumentation/performance-metrics/), but these have to be through the SDK and be associated to a transaction.

There is currently no plans to open up Sentry to allow sending arbitrary metrics, so I'm going to go ahead and close this issue as a result.

Maybe in a couple months we re-evaluate this though - lets see!

**Comment by jeengbe** [comment]
Hey @AbhiPrasad! 👋🏻 

Sure, thanks for the link, albeit not quite the same thing. 

Consider this issue alongside #44781 and #44779 more of "this would be a cool new feature, let's add it deep into the backlog for refinement once we get to it" kinds of issues than something what would be good to have asap. From what I have seen so far, Sentry is very actively building new features, and these might inspire feature ones 🙂

**Comment by AbhiPrasad** [comment]
I went ahead and closed this issue because it's not going to be worked on any time in the near future - so even adding it in the backlog probably will just let this go stale.

The other items you mentioned though do have the chance to be picked up within the next few months - so I'll leave them for the teams working on those to directly respond to you there (also why I didn't respond to those yet).

**Comment by jeengbe** [comment]
Yes sure, I can imagine the technical challenges this issue bears, didn't expect too much from this to begin with. It's more or a "If it aligns with your plans, nice, you know you've got support. If not, no big deal either" sort of issue, this particular one
