### ISSUE TITLE
External Services breakdown

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#44781]
### Problem Statement

The same way New Relic does (see below), a summary-like overview of which external services take the longest/are requested the most would come in handy.

![image](https://user-images.githubusercontent.com/51749023/219479704-9cd2f251-6b76-42f3-bb40-630fccfb897a.png)

From what I understand, Sentry does not provide a concept of "external services" yet.
Certain spans may be highlighted (Suspect Spans is a pretty nifty feature), but grouping of spans by properties, such as origin for http.client or external database requests.

**Comment by vinayinvicible** [comment]
@chadwhitacre is there any timeline for this feature.
It is really required for monitoring the performance impact by external services.

This is **the** feature that is stopping us from fully adopting sentry as an APM tool

**Comment by chadwhitacre** [comment]
@vinayinvicible Thanks for the bump. I'm putting this back in the queue for the relevant product team to address.

**Comment by ishkebab** [comment]
@vinayinvicible 
Hey, thanks for your comment!  And thanks for resurrecting this thread!  My name is Ash, and I am a product manager on the Sentry Performance team.  

To comment on your request - Yes! We are planning for a external services view which will break down the performance impact for your application based on 3rd party APIs.  This is currently in the development stage, and is intended for launch in Q1 2024.  

I will post some details as well as an intended UX design for feedback soon.  If you would like to be part of an early trial for the feature, we would appreciate the feedback.  

Also, do you have any particular requirements that you would like to see in our external services view?  

Let me know, thanks!

**Comment by Dhrumil-Sentry** [comment]
This feature is generally available in Insights->Backend->Outbound API Requests

![Image](https://github.com/user-attachments/assets/93cd35bd-b85f-4997-86a1-fe1db2931fcf)
