### ISSUE TITLE
Dashboard widget chart overlaps labels

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#44790]
### Environment

SaaS (https://sentry.io/)

### Link

https://sentry.sentry.io/dashboard/38089/?project=1&query=crons&statsPeriod=30d

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/23610/219489660-d1a5a969-5b47-450f-aa13-6e4f60b74229.png)

note 30d time window

### Expected Result

.

### Actual Result

.

**Comment by evanpurkhiser** [comment]
This is a larger issue with our usage of echarts

**Comment by alexjillard** [comment]
This has been fixed with the recent changes to dashboard widgets @gggritso has made.

<img width="514" alt="Image" src="https://github.com/user-attachments/assets/14844367-81ab-4fbf-86fe-4c55bb409648" />
