### ISSUE TITLE
Not obvious how to rename a widget

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#44792]
### Problem Statement

![image](https://user-images.githubusercontent.com/23610/219490715-53461393-6ed1-45d7-92bc-1a81f347f1d3.png)

![image](https://user-images.githubusercontent.com/23610/219490741-83abd687-4a98-4ef1-ac81-dcfa574c5f29.png)

### Solution Brainstorm

Literally could not find it. Had to have someone at Sentry show me. Just make it a form control?

**Comment by evanpurkhiser** [comment]
![image](https://user-images.githubusercontent.com/1421724/219495825-39c83aa6-d31a-4123-9c6e-5502b4d2a670.png)

it's this right? I think we could allow editing on the widget itself too, and then in the dropdown havea `Rename Widget` that triggers the edit right there.

**Comment by doralchan** [comment]
Could change the pencil to blue and add the option to rename widget as @evanpurkhiser suggested

**Comment by silent1mezzo** [comment]
This has been an issue for a while, IMO it'd be better to include as part of the workflow 

<img width="1067" alt="Screenshot 2023-02-16 at 6 53 07 PM" src="https://user-images.githubusercontent.com/155016/219514175-7895bbab-5ab1-46ed-86f7-7106d7b0e8a7.png">

**Comment by om-ray** [comment]
@dcramer @evanpurkhiser Please review the PR I made to fix this issue
