### ISSUE TITLE
Chrome Subdomain Phishing Warnings

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#44820]
Some Chrome users are reporting that their sentry subdomains (when they look like a domain) are causing a warning:

> The site you just tried to visit looks fake. Attackers sometimes mimic sites by making
small, hard-to-see changes to the URL.

For instance if a user owns `example.com` and they sign into `example-com.sentry.io`, Chrome thinks this might be a Phishing attack. There is an automated and manual process to add sentry to the trust system. The process is documented here: https://chromium.googlesource.com/chromium/src/+/master/docs/security/lookalikes/lookalike-domains.md#removing-lookalike-warnings-from-a-site

The automated process does not work for us because it requires that we own both domains (`example.com` and `example-com.sentry.io`). However the manual approach lets Google allowlist all of sentry.io. 

Form for the manual process: https://forms.gle/BxV3JGbCbRjucDxq6

**Comment by mitsuhiko** [comment]
Link to a customer Tweeting about this issue: https://twitter.com/fanahova/status/1626421309545799680?s=46&t=9zZuwpoO5ZPsq1PWAeXLZQ

**Comment by mitsuhiko** [comment]
Ad triaging: I internally referred this forward to Security, but we have no security team tag on github.

**Comment by mdtro** [comment]
I've filed the form for the manual appeal process. 🤞 
I'll report back in about three days on the results or next steps.

**Comment by mdtro** [comment]
I heard back from the Chromium team that this has been fixed and should roll out to most browsers over the next few days. I'll keep this issue open until the end of the week and close it out.
