### ISSUE TITLE
"Jira Server" Integration 500 on issue creation attempt 

### ISSUE THREAD

**Issue by MaxPaw** [getsentry/sentry#44824]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.11.0

### Steps to Reproduce

Jira Server: 8.20.8
1. Create integration with your Jira self-hosted (Server, not Data Center)
2. Use Issue create feature

### Expected Result

1. Creation form closed
2. Issue created

### Actual Result

1. Creation form stays
2. 500 error in console like: {"detail":"Internal Error","errorId":""}
3. Issue is not created

**Comment by MaxPaw** [comment]
Found out that plugin requests something like this https://${JIRA}/rest/api/2/issue/createmeta/${ProjectID}/issuetypes/${IssueTypeId}
So some projects work just fine but others fail - seems like plugin might be telling me something more specific about the problem that occurs, rather than just 500

**Comment by snigdhas** [comment]
Hi @MaxPaw, did you just set up/modify the Jira integration or did this used to work before?

**Comment by MaxPaw** [comment]
Hi! Thanks, @dhirennotani19 I am trying to create issue from Senty to my Jira Server, systems already integrated, but I got an error if I attempt to create issue to specific project (technically the problem occurs with specific field configuration / screen configuration, but it is quite hard to find difference and impossible to identify the root cause)

**Comment by MaxPaw** [comment]
Hi! Thanks, @snigdhas I recreated Jira integration setup in my attempt to quick-fix the problem, but it didn't manage to fix the issue, logs shows:
`{"log":"08:16:49 [INFO] sentry.access.api: api.access (method='POST' view='sentry.integrations.jira_server.webhooks.JiraIssueUpdatedWebhook' response=200 user_id='None' is_app='None' t
oken_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/extensions/jira-server/issue-updated/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImppcmEuc2t5
ZW5nLnRlY2g6QkVHQU4tcGVvcGxlLU9QSU5JT04tZmFjZSJ9.7pjgKmIqgiElAup5wX5IV53SBtWrU006EoP30KGmZdk/' caller_ip='46.182.25.254' user_agent='Atlassian HttpClient 2.2.1 / JIRA-8.20.10 (820010) 
/ Default' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.012018918991088867 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_
time='None' group='None' limit='None' remaining='None')\n","stream":"stderr","time":"2023-03-01T08:16:49.231651101Z"}
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2023-03-01T08:16:51.113633549Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/sentry/api/base.py\", line 150, in handle_exception\n","stream":"stderr","time":"2023-03-01T08:16:51.11364839Z"}
{"log":"    response = super().handle_exception(exc)\n","stream":"stderr","time":"2023-03-01T08:16:51.113650847Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/rest_framework/views.py\", line 469, in handle_exception\n","stream":"stderr","time":"2023-03-01T08:16:51.113652508Z"}
{"log":"    self.raise_uncaught_exception(exc)\n","stream":"stderr","time":"2023-03-01T08:16:51.113654398Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/rest_framework/views.py\", line 480, in raise_uncaught_exception\n","stream":"stderr","time":"2023-03-01T08:16:51.113655997Z"}
{"log":"    raise exc\n","stream":"stderr","time":"2023-03-01T08:16:51.113657806Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/sentry/api/base.py\", line 265, in dispatch\n","stream":"stderr","time":"2023-03-01T08:16:51.11365937Z"}
{"log":"    response = handler(request, *args, **kwargs)\n","stream":"stderr","time":"2023-03-01T08:16:51.113661074Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/sentry/api/endpoints/group_integration_details.py\", line 193, in post\n","stream":"stderr","time":"2023-03-01T08:16:51.11366261
Z"}
{"log":"    data = installation.create_issue(request.data)\n","stream":"stderr","time":"2023-03-01T08:16:51.113664238Z"}
{"log":"  File \"/usr/local/lib/python3.8/site-packages/sentry/integrations/jira_server/integration.py\", line 938, in create_issue\n","stream":"stderr","time":"2023-03-01T08:16:51.113
665748Z"}
{"log":"    if not (isinstance(cleaned_data[\"issuetype\"], dict) and \"id\" in cleaned_data[\"issuetype\"]):\n","stream":"stderr","time":"2023-03-01T08:16:51.113667615Z"}
{"log":"KeyError: 'issuetype'\n","stream":"stderr","time":"2023-03-01T08:16:51.113669451Z"}
{"log":"08:16:51 [INFO] sentry.access.api: api.access (method='POST' view='sentry.api.endpoints.group_integration_details.GroupIntegrationDetailsEndpoint' response=500 user_id='482' is
_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/groups/6590301/integrations/5/' caller_ip='212.50.106.31' user_agent='Mozilla/5
.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0
.03921794891357422 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')\n","stream":"stderr","time":"2
023-03-01T08:16:51.127205496Z"}
{"log":"08:16:51 [ERROR] django.request: Internal Server Error: /api/0/groups/6590301/integrations/5/ (status_code=500 request=\u003cWSGIRequest: POST '/api/0/groups/6590301/integratio
ns/5/'\u003e)\n","stream":"stderr","time":"2023-03-01T08:16:51.128753028Z"}`

**Comment by MaxPaw** [comment]
`"log": "KeyError: 'issuetype'\n"`
Seems to be the case, but same "issuetype" just works with other projects
