### ISSUE TITLE
Repository Config

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#4484]
We need to be able to configure repositories both within an organization, as well as per event.

## Adding Repositories

Integrations should be able to give a mechanism for adding a repository. For example, I want to "Add GitHub repository", which simply takes the existing GitHub permissions and registers a webhook to receive commit events.

## SDK Configuration

Within SDKs we need to configure which repos are present, where the code is located, and how it maps up to the repository structure.

e.g.

```python
SENTRY_CONFIG["repositories"] = {
  # in the Python SDK, we're just referencing a package name, but the wire protocol
  # would be absPath of the package. This could also always be the full absPath.
  "sentry": {
        "repository": "github:getsentry/sentry",
        # how we map up the local path to the path in the repo
        "prefix": "src",
        # revision is optional, and would allow us to link to specific versions a file on e.g. GitHub
        "revision": "...",
    },
}
```

**Comment by mitsuhiko** [comment]
👍

**Comment by dcramer** [comment]
There's actually an issue here. If we do it based on path, we cant correctly support frames that aren't file based. That means we could either:

- Make the key either be a file path or module path, and have the server magically try to figure it out.
- Flip it so the key is the repo name, and allow each repo to specify multiple paths? (ugh this is awful)
  - Alternatively we could just not support multiple on-disk paths for the same repo, but I'm not sure if its worth creating this arbitrary limitation.

**Comment by dcramer** [comment]
Aside, there's still an issue if we dont have absPath in that we need to pretend we can magically map module path -> local file path. Maybe we just wont support that for now.

**Comment by mitsuhiko** [comment]
So we assume dotted name then or how does this work on PHP?

**Comment by dcramer** [comment]
@mitsuhiko gave up on the idea -- we just wont support non-file based stuff as its not really doable

**Comment by mitsuhiko** [comment]
I think it should be possible to get file info on java btw.

**Comment by bretthoerner** [comment]
Yeah, at least Java class names have to match up to filenames, so I feel like it could be found in the repo. It won't be a direct path from root, though.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
