### ISSUE TITLE
Replay Details: When resizing replay video, console messages sometimes overlap and become illegible

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#44859]
**Problem:**

Console messages can overlap depending on viewport size/how large the video is resized to.

<img width="413" alt="image (3)" src="https://user-images.githubusercontent.com/187460/220430906-125bc3b7-d373-46cc-917d-861100e747ba.png">

Example [replay](https://sentry.sentry.io/replays/javascript:394622b3929b45c7b5e35184e24f6391/?query=&referrer=%2Freplays%2F&statsPeriod=14d&yAxis=count%28%29) where this happens.

**Comment by billyvg** [comment]
This also happens when you resize the window manually -- the tab does not re-render
