### ISSUE TITLE
Auto Assignment defaulting to incorrect ownership rule

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#44854]
### Environment

SaaS (https://sentry.io/)

### Link

https://color.sentry.io/issues/3937630512/?project=6191176

### DSN

https://612e1a0e1c4c42bc82ee151c142bd5b0@o22410.ingest.sentry.io/6191176

### Steps to Reproduce

1. Issue is captured by Sentry Org with Github CodeOwners file integrated.
2. Sentry reads the ownership rule `**/*.css #ux-infra` within the CodeOwners file
3. Regardless if there is a .css file in the stack trace or not, Sentry auto-assigns any/all issues to this team based on its rule.
![image](https://user-images.githubusercontent.com/103009467/219795763-c5867a2b-c9f2-41b8-b4b2-e0710cb4b985.png)

### Expected Result

Sentry should properly read the imported CodeOwners file to properly assign the issue automatically. Something about the asterisks might be throwing off the logic.

### Actual Result

Sentry reads the ownership rule **/*.css #ux-infra within the GitHub's CodeOwners file. Regardless if there is a .css file in the stack trace or not, Sentry auto-assigns any/all issues to this team based on this rule.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1779) by [Unito](https://www.unito.io)

**Comment by brianthi** [comment]
This was resolved from this PR: https://github.com/getsentry/relay/pull/1952

**Comment by DavidCain** [comment]
@brianthi -- thanks for noting the work that fixes this issue! Has the linked PR been deployed to production? We've turned auto-assignment back on and it appears to be auto-assigning all issues to the same team based on the rule `/**/*.css`

**Comment by brianthi** [comment]
It has been deployed to production, however if you're still seeing an issue, we must have missed something.  @jangjodi is looking back into this now.

**Comment by DavidCain** [comment]
@jangjodi - any updates?
