### ISSUE TITLE
Design: Replay preview takes up too much space

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#44920]
### Problem
> It's not necessarily that it auto-plays. I don't actually mind going to another page. It's the 400px's of something that I can't actually interact with and doesn't show me any information. If it was half that would I have a problem? Probably not. If it was side-by-side with the breadcrumbs and didn't push anything down, that'd be fine too.

### Solution
TBD

**Comment by ryan953** [comment]
@Jesse-Box can you help pick a new max-height for the replay preview component?

**Comment by Jesse-Box** [comment]
@ryan953 @jas-kas 
I would propose that the problem statement isn't that the replay preview takes up too much space, it's that they can't watch the replay in the issue details.

**Comment by jas-kas** [comment]
@Jesse-Box That could be one angle to look at it. Or if we are going to keep the choice to make users go to the Replay Details to view the replay, then we probably shouldn't take up as much real estate on Issue Details. 🤔

**Comment by ryan953** [comment]
related to https://github.com/getsentry/sentry/issues/55492

**Comment by Jesse-Box** [comment]
Closing this ticket because we're actively working on a solution.

See https://github.com/getsentry/sentry/issues/59280
