### ISSUE TITLE
Instructions on moving data on self-hosted servers?

### ISSUE THREAD

**Issue by ayyazdaniaryan** [getsentry/sentry#4494]
I have the latest version of Sentry running on one of my servers (self-hosted python installation), and now I have to move the entire instance of sentry, with all data to another server. I noticed sentry has an export/import command, but the docs show it is only for meta-data, rather than all data. Are there any instructions/steps for moving the instance with content intact?
 
Thanks!

**Comment by mattrobenolt** [comment]
The simplest way will be to just use your postgres tools to pg_dump and then reload into a new database. sentry export/import doesn't 100% handle all data. There's also data that is stored in redis, which you'd need to take an rdb snapshot to restore that from.

Ideally, these are all just tools that you already should be familiar with and there's nothing sentry specific here.

**Comment by ayyazdaniaryan** [comment]
@mattrobenolt Awesome! Indeed, nothing Sentry related. Just dump the two db's (postgres and redis) and reload in new instance. Do not also do a sentry import/export. Thanks!

**Comment by the-redback** [comment]
Hi @mattrobenolt,
What's about the data that is stored in filestore.backend? for example,

```
filestore.backend: 'filesystem'
filestore.options:
  location: '/var/lib/sentry'
```

Don't I need this data?

**Comment by mattrobenolt** [comment]
Yeah. There’s also data in Redis, etc. if you’re running Sentry 10, there’s now Kafka, Zookeeper, and Clickhouse as well that’s holding data.

**Comment by the-redback** [comment]
@mattrobenolt , I see. So, I need to backup both filestore and redis? my sentry version is 9.1.2.
Is there any documentation about how to do it idiomatically? Thanks.
