### ISSUE TITLE
Long error message not wrapping correctly

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#44993]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

A customer reported when a Sentry issue with a longer error message is applied, the wrapping continues off onto the hand sidebar of the UI.

Zendesk:
https://sentry.zendesk.com/agent/tickets/80767

### Expected Result

The message should wrap or generate a scrollbar, or be broken into multiple lines.

### Actual Result

Screenshot of experience. Customer allowed consent to share.
![sentry-long-error-message-words](https://user-images.githubusercontent.com/8451987/220768711-330e51aa-1db1-4cf5-85a8-c0c2e60cfe7c.png)

**Comment by scttcper** [comment]
fixed in #45002
