### ISSUE TITLE
Handle optional TLS validation for external source fetching

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#4500]
Originally brought up here: https://github.com/getsentry/sentry/pull/4016

We should surface a new setting to require TLS validation when fetching external files. This option would be enabled by default (security first) with an option to disable. We need to make sure we then are able to surface this exact error inside the UI correct so a user can make the decision to disable on their own. To clarify, we shouldn't just blindly say, "Failed to fetch file.", we should strictly say, "Unable to validate TLS certificate when fetching file." or something akin to that.

**Comment by graingert** [comment]
There's no such thing as a TLS certificate. Maybe the following text would be better:

”Unable to connect via TLS (HTTPS), x509 certificate invalid because:”

**Comment by mattrobenolt** [comment]
Sorry, I'm bad with words. 😛

**Comment by graingert** [comment]
It would be nice to have a field for a custom PEM, or support TOFU.

**Comment by graingert** [comment]
To try and minimise the number of users with validation disabled.

**Comment by mattrobenolt** [comment]
I don't think as a product we should go that far. We support users uploading sources into Sentry, and we'd rather encourage doing that.

**Comment by graingert** [comment]
@mattrobenolt here's the first part of it, default to false. requests logs validation errors, so it should be easy enough to debug if anyone enables it.
