### ISSUE TITLE
Ignore selection 3rd level expanding issue

### ISSUE THREAD

**Issue by Rarta** [getsentry/sentry#45029]
### Problem Statement

Hello, I'm using your solution a few times per week. It's a bit annoying how the ignore selection works.
You can see in the attached video that sometimes it does not open the 3rd level menu.
Sometime earlier the menu expanded to the left and it was more smoothly comparing with the current version when 3rd level open on top on the 1 and 2nd level.
https://sentry.zendesk.com/attachments/token/aKpxZzNvxdoQEq5iMhEzTENXJ/?name=select+box.webm

Just sharing my opinion :)

### Solution Brainstorm

I would suggest returning previous logic when 3rd level menu expands to the left
![image](https://user-images.githubusercontent.com/41193096/220841090-bd395250-4bb2-4b8e-9e5e-02c9a34463a9.png)

**Comment by brianthi** [comment]
Thanks @Rarta for filing this bug with us! I'm putting it into our backlog for now, and we'll look to fix it in the future.

**Comment by brianthi** [comment]
We are looking to make significant updates to this component of the page, and will likely replace these 2nd and 3rd level selects.  Will close this issue as we won't fix it.
