### ISSUE TITLE
Splunk Integration with sentry (Splunk - > Sentry)

### ISSUE THREAD

**Issue by sujathanavin** [getsentry/sentry#45036]
### Problem Statement

We are looking to forward events from Splunk to Sentry, and didn't find one available. Seems it is available the other way round. 
Currently all our logging is ingested into Splunk and we are looking to send the events to Sentry without having to make any code changes in legacy applications.  This will allow more projects to switch over to Sentry faster.

### Solution Brainstorm

Forward events from Splunk to Sentry

**Comment by Dhrumil-Sentry** [comment]
Hi @sujathanavin We're unlikely to build this. Sentry is meant to be error monitoring for your application and the app needs to be instrumented with the Sentry SDK initialization.

The alternative that you can consider is to build a middle layer that reads your Splunk data and uses the Sentry SDK to send custom events to Sentry. But this will likely be a subpar experience
