### ISSUE TITLE
[Feature Request] Data Export

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#45048]
### Problem Statement

I would very much like to download my data from the Sentry SaaS.

Mainly for analytical purposes (at a level Sentry currently doesn't offer, see #44779, #44603, #44601), a full export of all stored errors/transactions would be very useful.

### Solution Brainstorm

Bonus points if filters, such as `http.method:GET http.status_code:200 event.type:transaction` can be applied.

**Comment by jeengbe** [comment]
what does `(sfo)` mean

**Comment by souredoutlook** [comment]
> what does `(sfo)` mean

Hey @jeengbe - this is referring to the Sentry "Hub" location where the business day SLA is being measured from. For routing you'll see this get passed back and forth from YYZ (Toronto, Ontario, Canada) to SFO (San Francisco, California, USA) and triage can vary a bit more than that. The codes are referring to the IATA airport codes for airports nearest the hub office for that area. 😄

**Comment by Dhrumil-Sentry** [comment]
Hi @jeengbe The best option for this is to use the [Discover Events](https://docs.sentry.io/api/discover/query-discover-events-in-table-format/) API. Let us know if this answers your question

**Comment by jeengbe** [comment]
Hey @Dhrumil-Sentry!

That page would partly cover what I need. However, _"This endpoint is intended to get a table of results, and is not for doing a full export of data sent to Sentry"_, so, sadly, not quite suited for my need. There's also not pagination, so scraping many values is.. difficult.

I couldn't also fully test this, as the field `url.searchParams.append("field", "tag[myTag]");` (which I assume groups by that tag) yields `{ detail: 'Invalid characters in field tag[myTag]' }`.

**Comment by Dhrumil-Sentry** [comment]
Hi @jeengbe  We don't hear such a use case frequently and we're unlikely to support the export of all event data
