### ISSUE TITLE
[Feature Request] Button To Copy abs_path In stack trace Ui

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#45051]
### Problem Statement

Received a request to be able to directly copy the source abs_path, line and column numbers for faster access to get to their actual code.

<img width="928" alt="Screenshot 2023-02-23 at 1 50 57 PM" src="https://user-images.githubusercontent.com/96670625/221002850-45580ce5-afce-4627-9c4e-5927ef3c7b7e.png">

Customer provided an example + context - 

> They have a copy link function in their codemap ex: automatically copy `/ProjectRoot/File.rb:LINE_NUM` that makes it super easy to jump to the file in your IDE.

### Solution Brainstorm

Maybe a copy button next to the Toggle Context arrow at the end?

**Comment by therealarkin** [comment]
Thanks, we have too many buttons already. So closing for now
