### ISSUE TITLE
Web dashboard real time display new issue question?

### ISSUE THREAD

**Issue by istommao** [getsentry/sentry#4505]
I found the web dashboard can't display new issue automatic, you should manually refresh the page!
I remember if client send an new issue, the web dashboard will display new issue automatic before sentry version 8.x, but now i can't found this feature!

Can anybody tell me how to configure it!

**Comment by mattrobenolt** [comment]
Click this "Play" button.

![image](https://cloud.githubusercontent.com/assets/375744/20165748/da72c332-a6c4-11e6-9b5a-6a453f392bb4.png)

**Comment by istommao** [comment]
Well Forgive me for my stupidity!😄
