### ISSUE TITLE
Issue with  iOS Crash Logs Not Symbolicating Correctly on Sentry Web Platform

### ISSUE THREAD

**Issue by yufanghui** [getsentry/sentry#45077]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.9.0

### Steps to Reproduce

1.use sentry-cli upload dsym 
2.check dsym upload succes
3. wait dysm file handled after many hours
4. produce a crash

### Expected Result

Correctly parsing the stack trace of the crash,loacate do the source code 

### Actual Result

A bunch of symbols that cannot be associated with source code
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/16069335/221170560-e3b49789-2a83-4b38-8901-9fc25479e9e6.png">

### description
The crash logs on the Sentry web platform are not being correctly symbolicated. 

![image](https://user-images.githubusercontent.com/16069335/221453897-a4514db2-7254-4673-9fcc-cd18b64a5a01.png)

I have already uploaded the iOS debug symbol file and verified that the version matches, but the "Images Loaded" section is showing missing debug symbols. 
![image](https://user-images.githubusercontent.com/16069335/221453824-b0b19830-f867-4d15-b221-116f1d635e4b.png)

However, when I click the View button go into the details of the crash, I can see that the debug symbols are present and marked as "unapplied." 

![image](https://user-images.githubusercontent.com/16069335/221454045-2155227a-ed73-4d2d-81a4-fa2800a12fe3.png)

I have waited for over an hour after uploading the symbols and intentionally triggered a crash, but the crash is still not being symbolicated correctly.

Thank you for your assistance with this issue. I appreciate your time and effort in helping me resolve this problem. Your expertise has been invaluable in troubleshooting this issue, and I am grateful for your support. Please let me know if there's anything else I can provide to help further investigate this problem. Thanks again!

**Comment by yufanghui** [comment]
![image](https://user-images.githubusercontent.com/16069335/221453364-861a56cc-2b79-44b8-bc12-a0d629cd8690.png)

**Comment by loewenheim** [comment]
Hi, I would ask you to run the `symbolicli` tool on this event. Unfortunately we don't have a binary release of it at the moment; it's part of the `symbolicator` repository: https://github.com/getsentry/symbolicator

You can run it with `cargo run -p symbolicli --release -- --url <YOUR_SENTRY_URL> --auth-token <TOKEN> -o <ORG> -p <PROJECT> <EVENT_ID>`. It should run the symbolication locally. Also, please turn the logging level up to `trace` by setting the `RUST_LOG` environment variable to `trace`.

**Comment by yufanghui** [comment]
I am an iOS developer and our web team is responsible for deploying the Sentry project on the server. I am experiencing issues with incorrect symbolication of iOS crashes, not just one specific crash but all of them. Therefore, I suspect that there might be a problem with the symbolication service on the server.

**Comment by yufanghui** [comment]
> Hi, I would ask you to run the `symbolicli` tool on this event. Unfortunately we don't have a binary release of it at the moment; it's part of the `symbolicator` repository: https://github.com/getsentry/symbolicator
> 
> You can run it with `cargo run -p symbolicli --release -- --url <YOUR_SENTRY_URL> --auth-token <TOKEN> -o <ORG> -p <PROJECT> <EVENT_ID>`. It should run the symbolication locally. Also, please turn the logging level up to `trace` by setting the `RUST_LOG` environment variable to `trace`.

"I am an iOS developer and our web team is responsible for deploying the Sentry project on the server. I am experiencing issues with incorrect symbolication of iOS crashes, not just one specific crash but all of them. Therefore, I suspect that there might be a problem with the symbolication service on the server."

**Comment by loewenheim** [comment]
`symbolicli` will perform the same symbolication process as `symbolicator` would, including downloading your debug files, on your local machine. The log output from this tool would be the easiest first step for us to find out what is going wrong during symbolication without access to your server.

**Comment by yufanghui** [comment]
ok.when i run symbolicli locally ,and set 'export RUST_LOG=trace' i got this 

![image](https://user-images.githubusercontent.com/16069335/222024125-01d2758c-36ad-4a7b-83d6-f9efbc6dff0c.png)

And keeps printing continuously.


if i do not set 'export RUST_LOG=trace',i got this
![image](https://user-images.githubusercontent.com/16069335/222024534-b227941f-365b-4d17-923d-7edc249bb56d.png)

**Comment by yufanghui** [comment]
i set "export RUST_LOG="symbolicator_service=trace"" and  run "cargo run -p symbolicli --releas ....." again ,i got this [log.txt](https://github.com/getsentry/sentry/files/10866958/log.txt)

**Comment by loewenheim** [comment]
Hm, unfortunately there's nothing jumping out at me in the logs or the output. If you like you can hit me up on the community discord (https://discord.gg/sentry), I'm Loewenheim there as well.
