### ISSUE TITLE
Sentry not associating stacktrace with corresponding uploaded Windows pdb

### ISSUE THREAD

**Issue by GeckoEidechse** [getsentry/sentry#45116]
### Environment

SaaS (https://sentry.io/)

### DSN

`https://f833732deb2240b0b2dc4abce97d0f1d@o1374052.ingest.sentry.io/6692177`

### Steps to Reproduce

1. Create a Rust project according [to the docs](https://docs.sentry.io/platforms/rust/)
2. Create a release build (`cargo release`) and publish it somewhere
3. Upload the pdb to sentry by running `.\sentry-cli upload-dif -o YOUR_ORG_HERE -p YOUR_PROJECT_HERE .\app.pdb`
4. Cause a panic in your Rust application and have the Sentry crash logger upload the stacktrace
5. Check the crash in sentry dashboard

### Expected Result

![image](https://user-images.githubusercontent.com/40122905/221440138-b1824d90-1d9e-4362-8cb9-3fad50bfe376.png)

### Actual Result

![image](https://user-images.githubusercontent.com/40122905/221440100-5c7ae8cc-d3b5-413b-b7d7-562a80433330.png)

**Comment by GeckoEidechse** [comment]
**Additional notes:**

As far as I can tell reading through the docs, Sentry is able to automatically associate a stacktrace with a pdb so to my knowledge I do not need to tell it which pdb to use for a given stacktrace (not that I found an option to do that).

Placing the `app.pdb` next to the Windows `exe`, and running and crashing it I do get the corresponding information from the pdb shown in Sentry so I believe the issue is outside of Rust or Sentry failing to upload any specific information but rather the backend server being unable to associate the uploaded pdb with a stacktrace

**Comment by GeckoEidechse** [comment]
Hilariously I was on `v0.29.2` when running the test, i.e. one dot release too early. I'll retest with a higher version when I get to it later today and try and see if it resolves the issue.

For reference, here's my

- [`Cargo.toml`](https://github.com/R2NorthstarTools/FlightCore/blob/v1.8.2/src-tauri/Cargo.toml#L22)
- [`main.rs` where Sentry is initialised](https://github.com/R2NorthstarTools/FlightCore/blob/v1.8.2/src-tauri/src/main.rs#L47-L56)

**Comment by GeckoEidechse** [comment]
Updated the `sentry` dependency in my Rust project to `0.30.0` and **success** :tada: 

![image](https://user-images.githubusercontent.com/40122905/221908585-5e992ce0-520d-4614-8b3a-66829d4df96f.png)

So yeah it was simply because the `debug_images` feature was not enabled.

Now as to why I didn't already enable it on the older version of the crate, there simply wasn't anything in [the Rust docs](https://docs.sentry.io/platforms/rust/) explaining how to enable it ^^
Not sure if that's something that should be updated in the documentation still or can be neglected now that the feature is enabled by default anyway and for anyone else also running into it, will "solve itself over time" :P

Anyway, I'm happy to mark this as solved from my side ^^

**Comment by Swatinem** [comment]
Improvements to docs are always welcome :-)

I believe this integration was not in the default set for some historic reasons that predate me. Really it should have always been there, as symbolication simply does not work without it.
