### ISSUE TITLE
Where is the webhook?

### ISSUE THREAD

**Issue by istommao** [getsentry/sentry#4511]
![image](https://cloud.githubusercontent.com/assets/5070879/20201838/00110aea-a7f6-11e6-8486-9ced7857b3b8.png)

**Comment by mattrobenolt** [comment]
You're going to have to help me out since this isn't in English. What am I even looking at here? And what are you looking for?

**Comment by istommao** [comment]
![image](https://cloud.githubusercontent.com/assets/5070879/20202088/a7771c56-a7f7-11e6-9289-31f97dcd179b.png)
I want to find webhooks menu!

In sentry 8.x how to configure webhooks?

**Comment by mattrobenolt** [comment]
I'm not sure, but it sounds like you're misconfiguring. `sentry.plugins.sentry_webhooks` must exist in your `INSTALLED_APPS`, but this is a default configuration. So it sounds like you've misconfigured and overwritten this value and clobbered all of the defaults.

**Comment by istommao** [comment]
Well i didn't remove webhooks from settings! and i'm not sure which settings overwritten this value!

**Comment by mattrobenolt** [comment]
This would be in `sentry.conf.py`, the `INSTALLED_APPS` setting.

**Comment by istommao** [comment]
Maybe the sentry version is the answer, My sentry is 8.10.0, and i found sentry version in sentry.io is 8.11

**Comment by mattrobenolt** [comment]
No. I'm telling you what the issue is. You're doing something wrong in your configuration to make this happen. I'd suggest starting over and redoing `$ sentry init` to get a new config file.

**Comment by istommao** [comment]
Ok I'll try it!
