### ISSUE TITLE
Fallback Issue title for unsymbolicated stack frames

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry#45144]
### Problem Statement

We've seen each grouping category has different fallbacks if the function name is unavailable in the stack frames: 

`mobile:2021-02-12`: 
- fallback is the package name if the function name is unavailable. 

`newstyle:2019-10-29`: 
- fallback is the first system frame if the function name is unavailable 

In our use case, it would make more sense for the fallback to be the package name rather than the system name but we also prefer the newstyle grouping strategy vs the mobile grouping strategy. Is it possible to configure the fallback method?

### Solution Brainstorm

Configuring the fallback from the UI

**Comment by ashwoods** [comment]
Hi @dachakra! Thanks for your feedback. We are going to revisit this soon, as we are deprecating grouping breakdown strategy "mobile:2021-02-12", but we will backport some of the improvements to the newstyle strategy.
