### ISSUE TITLE
Support release:latest in Metric Alert Filters

### ISSUE THREAD

**Issue by idosun** [getsentry/sentry#45140]
### Problem Statement

I would like to set a Crash Free Rate metric alert to notify me about declining rates in my latest release. Sentry offers the release:latest filter however it is not supported for metric alerts

![image](https://user-images.githubusercontent.com/6572704/221653590-8f809890-a7ec-4d14-9b11-b6ba3878f7c1.png)

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1760) by [Unito](https://www.unito.io)

**Comment by ceorourke** [comment]
We have an upcoming feature that addresses this and allows the user to monitor a new release or deploy for a set time period by selecting "conditional" (as opposed to the default "continuous") monitor type when creating a metric alert rule. Here's the epic if you want to follow along: https://github.com/getsentry/team-core-product-foundations/issues/176
