### ISSUE TITLE
Direct SSO redirect 

### ISSUE THREAD

**Issue by matsmalmstensc** [getsentry/sentry#45141]
### Problem Statement

At the moment it is not possible to use Sentry SSO with input less tools that would support SSO automatic login because the login page where you need to click login with SSO. One use case is radiator screens that could use e.g. Okta SSO with certificate based authentication to automatically log in to sentry on radiator screens. 

### Solution Brainstorm

Have a way to automatically initiate the SSO redirect with e.g. a customer specific SSO login URL.

**Comment by dashed** [comment]
@matsmalmstensc Hi! May I ask what a "radiator screen" is? Googling the term doesn't bring up any useful search results.
