### ISSUE TITLE
Crons: Support user defined org-unique slug per monitor

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#45166]
To support #42881 we need to allow users to specify a unique slug for their monitor. The same way they can specify a slug for their org or project. This will allow for creation of monitors (via upsert) without the client needing to maintain a mapping of GUIDs.

We will be removing GUIDs from monitors and only using slugs. Existing GUIDs will be migrated to become slugs. This means all monitor lookups will need to have organization context now.

URLs will have two flavors due to Hybrid Cloud

```
https://sentry.io/api/0/organizations/:org_slug/monitor/:monitor_slug/
```

```
https://org_slug.sentry.io/api/0/monitor/:monitor_slug/
```

Checkins however, will still need to support the orgless routes

```
https://sentry.io/api/0/monitors/:monitor_slug/checkin/:checkin_uuid/
```
```
https://org_slug.sentry.io/api/0/monitors/:monitor_slug/checkin/:checkin_uuid/
```

```[tasklist]
- [ ] https://github.com/getsentry/sentry/pull/45227
- [ ] https://github.com/getsentry/sentry/pull/45258
- [ ] https://github.com/getsentry/sentry/pull/45270
- [ ] https://github.com/getsentry/sentry/pull/45276
- [ ] https://github.com/getsentry/sentry/pull/45292
- [ ] https://github.com/getsentry/sentry/pull/45279
- [ ] https://github.com/getsentry/sentry/pull/45294
```

### Open questions about slugs

 - Should we allow monitor slugs to be edited (I assume yes) but we should indicate that it will break any usages they have using that slug at the moment

### Followups

* https://github.com/getsentry/sentry/issues/45328
* https://github.com/getsentry/sentry/issues/45340

**Comment by dcramer** [comment]
If we're going to talk about removing GUIDs lets talk about that as a separate thing. To support slugs we dont need to remove GUIDs, and they may still be needed for a variety of reasons. You can still use the same URLs if you want and just make it so a monitor slug or a GUID is a usable key.

I would allow slugs to be editable - its up to the user if they want to break their system, but if they name a slug incorrectly and want to fix it (e.g. before its even used), why stop them?

**Comment by evanpurkhiser** [comment]
We can keep around GUIDs, but that does add some complexity that is worth being aware of.

We can dual lookup on the slug and GUID, this means we'll try and parse the UUID first, and if that fails we'll query on the slug. In the case of the checkin endpoint which has a orgless route we'll only allow the GUID to be used.

We should decide if we want to expose slugs in the UI at all in this case, we don't need them yet so we can get away with keeping all of that functionality hidden for now.

We can definitely follow up with removing GUIDs after the fact

**Comment by evanpurkhiser** [comment]
> We should decide if we want to expose slugs in the UI at all in this case, we don't need them yet so we can get away with keeping all of that functionality hidden for now.

for now I am leaving slugs out of the UI, but it will be part of the API. For now slugs are just defaulting to whatever the GUID is set to.

**Comment by evanpurkhiser** [comment]
@gaprl Let's spin out the two **[FUTURE WORK]** tasks into a new ticket that we'll track for improving the slugs / names / GUIDs UX in the UI

**Comment by evanpurkhiser** [comment]
This is complete.
