### ISSUE TITLE
Allow SSO plugins to have non-csrf-protected views

### ISSUE THREAD

**Issue by ojii** [getsentry/sentry#4516]
To allow SAML2 SSO, the views in `Provider.get_setup_pipeline` and `Provider.get_auth_pipeline` should have a way to be marked as CSRF exempted, since SAML2 usually uses a POST request for the response. 

In a similar fashion, it would be useful if `AuthHelper` had a method to go to the next step without calling the next step, currently I just do it manually using this:

```python
                helper.request.session['auth']['idx'] += 1
                helper.request.session.modified = True
```

EDIT: By the way, WIP SAML2 plugin: https://github.com/ojii/sentry-auth-saml2

**Comment by dcramer** [comment]
I think what we should do, at least on the CSRF part, is allow the view to say ``csrf_required = False``.

Also regarding the next step bit, whats the case where you can't use next_step (to avoid me digging to understand)?

**Comment by ojii** [comment]
> Also regarding the next step bit, whats the case where you can't use next_step (to avoid me digging to understand)?

https://github.com/ojii/sentry-auth-saml2/blob/cd68dddf91a41a4f6dade2dc1974aacd21f0cf9d/sentry_auth_saml2/views.py#L74-L76

Basically, I need to redirect to an external URL (the SAML Identity Provider) and have sentry resume from the next view.

**Comment by ojii** [comment]
Is there any progress on this or anything I could do to help get SAML support for sentry?

**Comment by dcramer** [comment]
@ojii we'll be getting saml in soon (next 60 days probably)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

PS- We now have SAML support: https://docs.sentry.io/accounts/sso/saml2/
