### ISSUE TITLE
Have human friendly names for issue.type search

### ISSUE THREAD

**Issue by DominikB2014** [getsentry/sentry#45195]
### Problem Statement

On the issue's page, when I search for a specific type, the possible values aren't very human friendly. 

![image](https://user-images.githubusercontent.com/44422760/221944454-32a0e632-5ec1-4fd7-9956-ccd742d8971a.png)

It would be good if more human friendly values were used. For example, instead of `issue.type:performance_slow_db_query`, we could have `issue.type:Slow DB Query`. 

### Solution Brainstorm

A simple solution would be to map the issue.type values to a more human friendly version in the frontend. This can also be done in the backend as well.

**Comment by MichaelSun48** [comment]
Implemented in #65810
