### ISSUE TITLE
Notification specificity

### ISSUE THREAD

**Issue by jplansiri** [getsentry/sentry#45241]
### Problem Statement

Our organization has several roles using Sentry, and the notification settings do not meet our needs. In particular, there is one role that only needs to be notified when new user feedback is added to a project (regardless of issue type). There is not currently a way to allow this through Account Settings.

**Comment by ceorourke** [comment]
@jplansiri we have user feedback as an issue type now, check out the docs for how to configure this type of alert https://docs.sentry.io/product/user-feedback/#getting-user-feedback-alerts
