### ISSUE TITLE
Tag with name 'function' cannot be processed

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry#4524]
**Steps to reproduce:**
- Send an event with `tags` `[[ "function", "function" ]]`

**Actual result:**
- Server cannot process `tags`
![screen shot 2016-11-15 at 10 38 51](https://cloud.githubusercontent.com/assets/363802/20300510/d932ffb4-ab1f-11e6-943d-71a2dcee139f.png)

**Expected result:**
- Should show up as every other event tag

**Comment by mattrobenolt** [comment]
🤔

**Comment by FZambia** [comment]
@HazAT hi, was this resolved in any way so you closed this issue?

**Comment by HazAT** [comment]
@FZambia 
Sorry for just closing it without saying why.
We have some internal reserved tag keys/names and function falls into that:
https://github.com/getsentry/sentry/blob/master/src/sentry/models/tagkey.py#L23-L26

**Comment by FZambia** [comment]
@HazAT thanks! looks like we will do the same way.
