### ISSUE TITLE
Feature: Support interactive object inspection in "Console" tab

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#45256]
Currently, we attempt to stringify objects/arrays in our Console messages. It would be nice if we could instead have these types as interactable a la browser console. You could see a preview of the object and expand/collapse as necessary.

Here's an example library we could use: https://www.npmjs.com/package/react-json-tree (from redux dev tools).

**Comment by billyvg** [comment]
Another potential library: https://www.npmjs.com/package/react-json-view

**Comment by ryan953** [comment]
Could be related to the HTTP/Responses project
