### ISSUE TITLE
Logged in and presented with a "It looks like we're having issue." modal.

### ISSUE THREAD

**Issue by williamatpaper** [getsentry/sentry#45263]
### Environment

SaaS (https://sentry.io/)

### Link

https://gradeslam.sentry.io/issues/

### Steps to Reproduce

1. Log in

### Expected Result

View Projects, and the rest of Sentry. 

### Actual Result

![image](https://user-images.githubusercontent.com/115566901/222256238-3d2eda78-22ce-49d9-9839-d7e528223c95.png)

**Comment by JLuse** [comment]
@williamatpaper there was a brief outage earlier that may have been what you experienced. If you try accessing Sentry now you shouldn't have this issue.
