### ISSUE TITLE
Double verify new password when changing password

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#4527]
Right now, there's only one field for "New Password". If you quickly typed a password wrong, there's no way to really know since we don't require a double verification.

Maybe we should tuck this away under a "Change Password" CTA to avoid the clutter?

/cc @kjlundsgaard @ckj

**Comment by mattrobenolt** [comment]
Literally no idea. @ckj has ideas about how things look.

**Comment by ckj** [comment]
@kjlundsgaard Another option could be to add a change password section under the security tab and have that link point there. That's how Dropbox does it and kind of how GitHub does it:

![screen shot 2016-11-15 at 3 04 44 pm](https://cloud.githubusercontent.com/assets/30713/20328080/357e6400-ab45-11e6-8705-d753a47ef591.png)

**Comment by benvinegar** [comment]
Should look like this:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/2153/33857241-b5dfe880-de7f-11e7-8513-35317946e0d5.png">
