### ISSUE TITLE
Sentry QueryExecutionError / Releases not working

### ISSUE THREAD

**Issue by tosnoah** [getsentry/sentry#45306]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.2.0

### Steps to Reproduce

Hey, 

Sentry deployed on Azure kubernetes service having internal issues due to some problems in Clickhouse. 

Used: Latest helm chart which can be found here [https://github.com/sentry-kubernetes/charts/tree/develop/sentry](url)

Snuba version:23.1.1
Clickhouse version:20.8.19.4

All pods are working just fine.

### Expected Result

Response in the details section, no more internal errors. 

### Actual Result

<img width="1043" alt="Bildschirm­foto 2023-03-02 um 13 35 27" src="https://user-images.githubusercontent.com/121792205/222430603-2a4268a5-55b5-4af1-89bc-a87f1176b863.png">

<img width="1055" alt="Bildschirm­foto 2023-03-02 um 12 56 51" src="https://user-images.githubusercontent.com/121792205/222422155-057a419c-5262-41b8-9337-5e0520cee30a.png">

`Error: DB::Exception: Illegal column for DataTypeNullable.`

<img width="687" alt="Bildschirm­foto 2023-03-02 um 12 59 43" src="https://user-images.githubusercontent.com/121792205/222422753-bb356b0f-7a94-4792-a919-7368680dcadd.png">

Do i need to investigate errors_local table in the clickhouse pod and see if there is a mismatch?

**Comment by tosnoah** [comment]
solved it by using the clickhouse version 21.8. can be closed.

**Comment by chadwhitacre** [comment]
Thanks for circling back @tosnoah, glad you were able to figure something out.
