### ISSUE TITLE
react-hydration-errors inbound filter doesn't catch all errors

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#45363]
### Environment

SaaS (https://sentry.io/)

### Link

https://prisjakt-ab.sentry.io/issues/3933815010/?project=1228836

### Steps to Reproduce

n/a

### Expected Result

With #45188, React hydration errors should be filtered out directly. This is sadly not the case.

### Actual Result

After removing client-side hydration error filtering, this is what happened:

![image](https://user-images.githubusercontent.com/51749023/222711339-8e99de64-1e75-44a5-8d1d-16170599f248.png)

**Comment by priscilawebdev** [comment]
but yes you are right...we are only filtering the most common cases as listed here https://github.com/getsentry/sentry/blob/24137343fea84e14f49fce8dd0de5a699209456b/src/sentry/relay/config/__init__.py#L122-L126

**Comment by jeengbe** [comment]
@priscilawebdev 
> We have shipped a small fix a few hours ago. Do you think you can test again and see if it is filtering out? 🙏

It works now, thanks! 🙏🏻
