### ISSUE TITLE
Update docs.sentry.io/server/warnings with filestore settings

### ISSUE THREAD

**Issue by jakubczaplicki** [getsentry/sentry#4537]
After upgrading Sentry on-premise from 8.8.0 to 8.10.0 I see a warning regarding Deprecated Settings:

> The SENTRY_FILESTORE setting is deprecated. Please use SENTRY_OPTIONS['filestore.backend'] instead.
> The SENTRY_FILESTORE_OPTIONS setting is deprecated. Please use SENTRY_OPTIONS['filestore.options'] instead.

Yet, the https://docs.sentry.io/server/warnings/ doc page doesn't mention `filestore.backend` nor `filestore.options`. It might be worth putting those two settings in the doc page. 

----
To be specific, the .yml  seems to have strings and bools configs only, while SENTRY_FILESTORE_OPTIONS is a dict in `sentry.conf.py`. 

Is this the correct mapping ?

From `sentry.conf.py` :
```
SENTRY_FILESTORE = 'django.core.files.storage.FileSystemStorage'
SENTRY_FILESTORE_OPTIONS = { 'location': '/tmp/sentry-files', }
```

to `config.yml`:
```
filestore.backend: 'django.core.files.storage.FileSystemStorage'
filestore.options: { 'location': '/tmp/sentry-files', }
```

**Comment by mattrobenolt** [comment]
Yup, I definitely forgot to add this to our docs. And yes, what you suggested would work. You can also use the short alias `fs` now as well to replace the longer `django.core.files.storage.FileSystemStorage`.
