### ISSUE TITLE
_normalizeUrl is never called, so sourcemaps aren't connecting (react native)

### ISSUE THREAD

**Issue by sjafri5** [getsentry/sentry#4538]
Hi, so the problem on a macro scale is that the sourcemaps are not matching to the minified code in the stacktraces.

When I upload the artifacts with their full name (i.e. `file:///var/mobile/Containers/Bundle/Application/CF21C92F-695D-47E8-9B63-F5EB40DE0A2F/my-app.app/main.jsbundle`) I get full stack traces. This obviously not scalable since the full url has a specific deviceID.

This seemed to be a problem with an updated pathname that the regex didn't cover (#665) but that has been updated and I can confirm that the new regex captures everything except the tail (`/main.jsbundle`).

So it seems that the issue is that the `reactNativePlugin._normalizeUrl` (which is where the stripping occurs) isn't being called. It seems that the method `_normalizeData` only calls `_normalizeUrl` if either `data.exception` or `data.culprit` exist. When i run this with debugger, they skip over both of these conditionals. However the JSON that shows up in on server shows a data.culprit with the full URL.

Any help would be greatly appreciated.

**Comment by JTCunning** [comment]
Hey @sjafri5, it seems as though you're hinting towards [this function](https://github.com/getsentry/raven-js/blob/3.8.0/plugins/react-native.js#L33), which is specific to the [raven-js repository](https://github.com/getsentry/raven-js).

It also seems as if you're referencing https://github.com/getsentry/raven-js/issues/665, so I'm going to close this and ask you to reopen your current issue on the approriate repository. We do appreciate your report, though.

**Comment by sjafri5** [comment]
Ahh sorry, my fault. will repost in Raven. thanks
