### ISSUE TITLE
Crons: Navigating to an issue from monitor details with environment locked shows error

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#45445]
# Problem
Since Crons doesn't currently support multiple environments, if you have locked a specific environment when navigating through issues shown in the monitor details page, you'll see this message:

![Image](https://user-images.githubusercontent.com/1308394/223243655-256facbb-458f-4867-b7b4-a5555fede9d5.png)

# Steps to reproduce

1. Go to issues
2. Select an environment in the filters
3. Lock that environment 
4. Go to Crons and select a monitor with issues
5. Click on the issue

# Expected behavior
It should disable the lock or simply render the issue details even with an environment lock.

**Comment by rjo100** [comment]
This should be fixed now, right? We send environment with the issue now so it will show as the environment is respected across the different pages

**Comment by gaprl** [comment]
Yes this is fixed.
