### ISSUE TITLE
Mask certain routes captured by Session Replay for PII purposes

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#45456]
### Problem Statement

Currently, only privacy selectors documented [Here](https://docs.sentry.io/platforms/javascript/guides/react/session-replay/privacy/#privacy-configuration) are available to mask PII Data in captured Replays. A simpler or more accessible method has been requested to tweak PII retention outside of the integration itself. 

### Solution Brainstorm

Options via the Org UI to filter particular route information (e.g - /account/* which may contain sensitive account information)

**Comment by kpujjigit** [comment]
JIRA Ticket: https://getsentry.atlassian.net/browse/OPS-2914?atlOrigin=eyJpIjoiZTk4NDhmMmI3ODAzNGUxYTg5ZDE0MjgzNGMxY2FiMGMiLCJwIjoiaiJ9

**Comment by bruno-garcia** [comment]
Thanks for the feature request. We'll discuss this and evaluate the impact.

**Comment by bruno-garcia** [comment]
> JIRA Ticket: https://getsentry.atlassian.net/browse/OPS-2914?atlOrigin=eyJpIjoiZTk4NDhmMmI3ODAzNGUxYTg5ZDE0MjgzNGMxY2FiMGMiLCJwIjoiaiJ9

@kpujjigit Is this the right Jira ticket? It's an ops request, doesn't seem related to Replay

**Comment by billyvg** [comment]
There's a lot of complexity involved with controlling SDK options from inside our Sentry UI (org settings).    Unfortunately we weren't unable to get our remote config project approved, which would have been part of the foundation required to have this feature. Going to close out this issue as it's unlikely we'll be able to do this in the near future.
