### ISSUE TITLE
High severity vulnerability affecting this repo

### ISSUE THREAD

**Issue by benmag1** [getsentry/sentry#4546]
Hi there, 

We noticed that your repo has a high severity vulnerability: 
* [Content & Code Injection (XSS)](https://snyk.io/vuln/npm:marked:20150520?utm_source=gh_issue)
* Affected package: marked<=0.3.5

[Here is the test report for this repo](https://snyk.io/test/github/getsentry/sentry?utm_source=gh_issue). 
If you’d like to fix this vulnerability, Snyk lets you generate a pull request that recommends the best upgrade path - there’s a link to fix this vulnerability on the test report. 

Stay secure :-)

Ben from the Snyk team

**Comment by JTCunning** [comment]
Thanks for the report, @benmag1.

I've assigned this to @benvinegar so that he can prioritize and possibly forward this to another contributor.

**Comment by mattrobenolt** [comment]
Oh, I'm pretty confident this doesn't actually affect us since I patch our way around it. Lemme dig it up.

**Comment by mattrobenolt** [comment]
Yeah, we avoid the security issue here: https://github.com/getsentry/sentry/commit/6ab1e6d847bdeb1c20115ae74170d4f44add06d8

Since we don't even allow `javascript:` urls.
