### ISSUE TITLE
i get event too old error in  sentry-sessions-consumer

### ISSUE THREAD

**Issue by Chengshihao1018** [getsentry/sentry#45468]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.10.0

### Steps to Reproduce

i`ve change the rotation date in clean up job,change 7 day to 2.meanwhile i change the conf in sentry 
![image](https://user-images.githubusercontent.com/31720199/223421833-59f06096-04ab-45ea-b2d4-0053d7fd5373.png)

i try to clean up redis and set kafka topics to latest,and then i restart all module,but i get this error in sentry-sessions-consumer
![image](https://user-images.githubusercontent.com/31720199/223422236-d9d04339-bd20-4535-b537-86494b89da3d.png)

how could i handle this data?

### Expected Result

sentry-sessions-consumer should work without error

### Actual Result

get event too old error

**Comment by hubertdeng123** [comment]
Is this error bothering you? I looked into the snuba codebase and I think that's an error exception raised to enforce retention when processing messages

**Comment by Chengshihao1018** [comment]
> Is this error bothering you? I looked into the snuba codebase and I think that's an error exception raised to enforce retention when processing messages

so it doesn't affect the whole service？

**Comment by hubertdeng123** [comment]
Yep, shouldn't affect the whole service. Are you observing any unexpected behavior?

**Comment by Chengshihao1018** [comment]
> Yep, shouldn't affect the whole service. Are you observing any unexpected behavior?

from now on,data reporting and alarming seems to be normal.thx for your answer,i will keep look on it~~~~

**Comment by hubertdeng123** [comment]
closing this issue then, feel free to reopen in the future :)
