### ISSUE TITLE
Source code was not found for /main.jsbundle

### ISSUE THREAD

**Issue by denstepa** [getsentry/sentry#4547]
Hi there! 
We are having an issue with artefacts using self-hosted sentry 8.7.0
We user raven-js to track error in a react-native app, and have setup everything accourding to the docs and have the following problem:
`
Source code was not found for /main.jsbundle { "url": "/main.jsbundle" }
`
But the artefacts are in place, we tried different namings etc.. nothing worked
Here are how the Artefacts look for this release. We tried both with `/` in the beginning and without.
What could be wrong ?

![c2c8a246-acbf-11e6-8f6e-f9f908c964eb](https://cloud.githubusercontent.com/assets/3616888/20399370/097f03e8-acf1-11e6-8ab0-82853e621ea9.png)

**Comment by dcramer** [comment]
Please use our public forum for community support.

**Comment by zefj** [comment]
@denstepa hey, I'm having the same issue, tried literally every combination possible. Have you been able to resolve this issue?
