### ISSUE TITLE
[Implementation] In-App Onboarding Experience Improvements for Session Replay

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#45474]
## Summary

Frontend implementation ticket of this [design ticket](https://github.com/getsentry/team-replay/issues/22). It communicates to our users how they can get started with Replay, even if they have an in-eligible project selected in Page Filters.

_**The goal is eventually to re-use the same flows and logic for the Profiling in-app onboarding.**_ However, this is not in the scope of this ticket.

### More information

See the Figma [here](https://www.figma.com/file/6e0R6eyjmohixOipp7lkq6/Specs%3A-Onboarding-v2?node-id=826%3A6165&t=GFny5ZFra6iYDeEp-0).
For the flow chart:

- Valid: means in this context that the selected projects are eligible to use/setup Session Replay
- Setup: means in this context that the selected project(s) has Session Replay setup
- Yes & No - happens in the case where where multiple projects are selected in the Page Filters

**Important items to note:**

- Intentional choice here to change the the checkboxes to a numbered list in tray
- There's also a desire for the tray to be wider (See [Figma comment](https://www.figma.com/file/6e0R6eyjmohixOipp7lkq6?node-id=823:2704#386644657))
- We will not be implementing a flow to trigger an email to a user that has project creation permissions
- In the onboarding tray, the project selector is a filtered list based on all eligible projects that have _yet_ to be set up

**Comment by Jesse-Box** [comment]
cc: @jas-kas
---
I just want to highlight that these problems exist for profiling as well. Can we build something where we mash two potatoes with one fork?

**Comment by eliashussary** [comment]
@jas-kas @Jesse-Box 
> In the onboarding tray, the project selector is a filtered list based on all eligible projects that have yet to be set up

I don't think i actually see this in figma; were we looking to do something like we did in profiling, where we group the list by supported/unsupported? In addition to this grouping we can sort it by having elgiible projects not setup at the top

![image](https://user-images.githubusercontent.com/7349258/228638435-41bb0106-ccac-4ea2-8006-4c948a956fe8.png)

**Comment by Jesse-Box** [comment]
> @jas-kas @Jesse-Box
> 
> > In the onboarding tray, the project selector is a filtered list based on all eligible projects that have yet to be set up
> 
> I don't think i actually see this in figma; were we looking to do something like we did in profiling, where we group the list by supported/unsupported? In addition to this grouping we can sort it by having elgiible projects not setup at the top
> 
> ![image](https://user-images.githubusercontent.com/7349258/228638435-41bb0106-ccac-4ea2-8006-4c948a956fe8.png)

Hey @eliashussary, on a high level, the user experience is essentially forcing the user to select a valid project from the index page, but informing the user of a selected project that isn't eligible and why (Scenario C). Showing unsupported projects again in the tray wouldn't necessarily hurt the user experience; however, I'm not convinced it's needed either.

I hope that helps!

**Comment by jas-kas** [comment]
@eliashussary @Jesse-Box 

I should have thought about this sooner but it slipped my mind! Can we only have these new banners be present for AM2 organizations? Only AM2 organizations will be able to set up Replay + send replay events (by April 13th).

In this screenshot, is a Team AM1 account. It doesn't make sense to ask them to switch their project to a FE one, if they can't send replays all together. The "Update Plan" CTA is meant to encourage them to update from AM1 to AM2. :)

![Screenshot 2023-03-30 at 5 53 25 PM](https://user-images.githubusercontent.com/77064737/228972751-aaa9b6bc-203a-4a74-aeae-def1ae70debc.png)

**Comment by eliashussary** [comment]
Closed by:
https://github.com/getsentry/sentry/pull/46504
https://github.com/getsentry/sentry/pull/46791
https://github.com/getsentry/sentry/pull/46812
https://github.com/getsentry/getsentry/pull/10100
