### ISSUE TITLE
Add a threshold to percent change alerts

### ISSUE THREAD

**Issue by danielcompton** [getsentry/sentry#45489]
### Problem Statement

I'm trying to set a threshold alert for errors. I set 300% higher than same time one week ago, grouped over 1 hour interval. This would match the spike on the right. Unfortunately, it would also match very low traffic/low error periods where there was a small blip above the week ago's baseline.

![CleanShot 2023-03-08 at 09 48 53@2x](https://user-images.githubusercontent.com/811954/223549202-5a0b8596-53a1-4347-ab94-98ab63856daf.png)

We don't want those very low periods to trigger an alert.

### Solution Brainstorm

What I'd like to see is the ability to set a percent change threshold + an event baseline, e.g. 300% higher than same time one week ago, AND > 50.

**Comment by brianthi** [comment]
Hi @danielcompton, I would recommend in this case that you either increase the percentage threshold or choose a static value instead of percentage. Allowing to check on multiple conditions isn't something we had planned for, but will keep your feedback in mind.
