### ISSUE TITLE
Dashboard Improvement when using different Scales

### ISSUE THREAD

**Issue by irodrigues-git** [getsentry/sentry#45502]
### Problem Statement

Requesting the ability to create a dashboard with different scales or metrics (eg. minutes and days) that adjust to such scales and metrics. 

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1769) by [Unito](https://www.unito.io)

**Comment by brentc** [comment]
Thanks for the suggestion @irodrigues-git. Can we dig a little further into what not having this functionality is preventing? What is the user trying to accomplish when they want to be able to set different time scales and adjust them. 

We likely won't be working on this in the short-term, but we'll add it to the backlog to be prioritized in the future if we can identify the value having this would provide for our users.

**Comment by Cefold** [comment]
I believe it is called second Y axis, which is a Y axis drawn on the right-hand side of a chart. The most common case would be put two metrics with different scales into one graph.

**Comment by Cefold** [comment]
<img width="204" alt="image" src="https://user-images.githubusercontent.com/25673069/223814677-1566dcc7-68f1-4c8f-8f0b-abcc2d822ffd.png">
Another solution would be show this timestamp (dotted line) for every graph, so users could compare across graphs.

**Comment by brentc** [comment]
Got it. Thanks for the context. It's something we're aware of. We'll be backlogging this request for now and will consider it against other priorities in the future.
