### ISSUE TITLE
[Azure DevOps] Installation failure - Insufficient account access error

### ISSUE THREAD

**Issue by stellaatsentry** [getsentry/sentry#45522]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Follow [Sentry's Documentation](https://docs.sentry.io/product/integrations/source-code-mgmt/azure-devops/) to install the Azure DevOps integration.

### Expected Result

The integration is installed successfully.

### Actual Result

Receiving the error message 

> The installation could not complete due to a provider error. You do not have sufficient account access to create webhooks on the selected Azure DevOps organization. Please check with the owner of this Azure DevOps account.
![image](https://user-images.githubusercontent.com/81985895/223756035-c6cf2ebe-f7cc-4858-a131-85e4fb5a17e2.png)

What has been checked so far:
- The customer is an Azure organization owner and a user in the Project Collections Administrators group, and has set every available permission to "Allow"
- The customer is also listed as an Owner in their Sentry Organization
- They are using the same email both in Sentry and in Azure (log into Sentry through DevOps Login)
- A HAR file of the installation process has been provided

Further details provided in the internal ticket.

[Zendesk ticket](https://sentry.zendesk.com/agent/tickets/79538)

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1768) by [Unito](https://www.unito.io)

**Comment by RobBuijs** [comment]
Same issue here. Please fix.

**Comment by garytube** [comment]
same here.

**Comment by garytube** [comment]
Yep! That fixed it.  I must have missed that in the docs

**Comment by stellaatsentry** [comment]
Glad to learn that! We will be adding it to our documentation for future reference.
