### ISSUE TITLE
Including context causes automatic OS/browser detection via User-Agent to fail

### ISSUE THREAD

**Issue by nateberkopec** [getsentry/sentry#4553]
https://github.com/getsentry/raven-ruby/issues/583

Providing `contexts: :os` or `contexts: :runtime` or even `contexts: :server_os` causes the autodetection plugin to not attempt to do anything. This is not ideal because, for example, on Rails application server we'd like to report the Ruby runtime version and server OS while keeping the auto browser detection.

In the meanwhile, we'll report this under extra context.

**Comment by nateberkopec** [comment]
Ah yeah, this is it: https://github.com/getsentry/sentry/blob/master/src/sentry/plugins/sentry_useragents/models.py#L26

I'm not sure what behavior makes sense, but I really don't want to have to duplicate the User-Agent parsing logic Sentry already does.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by dentarg** [comment]
@BYK has this been solved?

**Comment by BYK** [comment]
@dentarg seems like it was with https://github.com/getsentry/sentry/commit/2b0e63aac71dfb0b7d52454563152b21dbb9b788#diff-d85a98fd4990c11990759887501fefbc

@dcramer do you remember anything about this?

**Comment by dcramer** [comment]
I honestly don't remember
