### ISSUE TITLE
Unable to set 2FA as join new organisation process.

### ISSUE THREAD

**Issue by rbisol** [getsentry/sentry#45577]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Enforce 2FA in an organisation
2. Invite a new member
3. The user creates a new account or login into an existing account (without 2FA)
4. The user gets a prompt informing the organisation requires 2FA
5. The user gets an error when trying to set 2FA in https://sentry.io/settings/account/security/

### Expected Result

The user gets redirected to security settings to set 2FA

### Actual Result

User gets an error page:

Oops! Something went wrong
It looks like you've hit an issue in our client application. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

Sentry issue: https://sentry.sentry.io/issues/3988107425/?project=11276

No workarounds at the moment

**Comment by sumerdeveci** [comment]
@markstory Hi, is there any improvements on this issue?
