### ISSUE TITLE
Source Maps not working for flutter web

### ISSUE THREAD

**Issue by ChetanKhanna767** [getsentry/sentry#45580]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. I already have a release on sentry 
2. I have the sourcemap for the release, generated using 
` flutter build web --release --source-maps -t lib/main_${{github.event.inputs.flavor}}.dart
`
3. I uploaded soucemaps to sentry with this command
`sentry-cli releases -o innotrail -p flutter  files "innotrail@2.5.0+124" upload-sourcemaps main.dart.js.map`
4. They were upload successfully
5. But when I see the issues on sentry, it says

> Source code was not found (see [Troubleshooting for JavaScript](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/))
> 
> Expand
> Source code was not found (see [Troubleshooting for JavaScript](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/))
> 
> Expand
> Invalid location in sourcemap (see [Troubleshooting for JavaScript](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/))
> 
> Expand
> Invalid location in sourcemap (see [Troubleshooting for JavaScript](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/))
> 
> Expand
> Invalid location in sourcemap (see [Troubleshooting for JavaScript](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/))
> 
> Expand

### Expected Result

I should see mapped stacktrace

### Actual Result

![Annotation 2023-03-09 212902](https://user-images.githubusercontent.com/101747174/224082291-85cf3093-e6f1-42d1-8d22-74f60014ef58.png)

**Comment by Fwang36** [comment]
Hey there,

Have you double checked that the path in the stack trace matches the path in your uploaded artifacts?  I don't see any options like --url-prefix being passed to sentry-cli so I'm guessing this might be the case.  You also need to upload both the source file and the source map, not just the map.

Also have you double checked that the release in the Sentry.init is the same as the release set in the sentry-cli?

Take a look at our troubleshooting docs for source maps[ here](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/)

**Comment by ChetanKhanna767** [comment]
Thanks !
It worked with sentry_dart_plugin.
I was not uploading the source files
