### ISSUE TITLE
Provisioning Team Members, membership is not restricted through IDP after accepting Invite

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#45594]
### Environment

SaaS (https://sentry.io/)

[Jira Ticket with customer details and screenshots](https://getsentry.atlassian.net/browse/FEEDBACK-1773) by [Unito](https://www.unito.io)

[Zendesk Ticket](https://sentry.zendesk.com/agent/tickets/81340l)

*Relates to [this Github issue 45588](https://github.com/getsentry/sentry/issues/45588)
### Steps to Reproduce

1. Provision a new team 
2. Go into team on Sentry side, and see that the invites are pending with the remove option greyed out.
3. Users accept invite
4. Go back into team on Sentry side and see that the user is now removable through the UI

### Expected Result

Membership should only be manageable through SCIM

### Actual Result

Membership is manageable through Sentry UI as well.

**Comment by cathteng** [comment]
i believe i have deployed a fix https://github.com/getsentry/sentry/pull/52846
