### ISSUE TITLE
Global 'in progress' status per issue

### ISSUE THREAD

**Issue by nagolml** [getsentry/sentry#456]
For teams using Sentry, it would good to be able to have the ability to set a global status on an issue to indicate that it is being worked on so that other developers won't need to waste their time investigating an issue that is already being worked on by somebody else (but that has not yet been resolved).

**Comment by benvinegar** [comment]
Today we considered this state is captured by "assigned" – somebody is responsible.

Given that it's been 5 years without activity on this issue, I'm going to close.
