### ISSUE TITLE
UI Display Issue: Inbound Filters Error Message List appears oddly when updated

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#45608]
### Problem Statement

During the error message list update, the UI shows both the old and updated lists. However, when the list is large, the display banner of: "Changed error message from " is not displayed well.

Please see here: https://user-images.githubusercontent.com/99350819/224158408-ca06c424-6ac9-4e84-8d7a-fd5bd55d66e0.mov

**Comment by evanpurkhiser** [comment]
@vuluongj20 you plan to take care of this?
