### ISSUE TITLE
Content Security Policy Support Self hosted Sentry

### ISSUE THREAD

**Issue by noobd3v3loper** [getsentry/sentry#45616]
### Problem Statement

Hi,

We've hosted the sentry on our on prem server. And did a vulnerability scan on the sentry app. And there are findings. I would like to know how to resolve this findings.

The findings is Content Security Policy Missing on header. What would be the headers that needed to be added on our reverse proxy.

**Comment by mdtro** [comment]
@noobd3v3loper - I'm looking in to this for you.

**Comment by mdtro** [comment]
@noobd3v3loper 

I'm back from researching this, and I think I can get you started. Setting the CSP headers depends a lot on what your local deployment looks like, so unfortunately we don't have a one-size fits all approach here at the moment. 

Ironically, we're working on refreshing our CSP configurations for the SaaS product at the moment. My hope is that work will better inform us how to set a sane default posture for self-hosted out-of-the-box. We also have a self-hosted install we dogfood I can work with too. That's going to take some time though.

To get you started, my recommendation is to setup [our CSP monitoring first](https://docs.sentry.io/product/security-policy-reporting/#content-security-policy), then move to a locked down policy after triaging and adjusting the policy directives.

Set your `Content-Security-Policy-Report-Only` header to the [suggested starter policy](https://content-security-policy.com/#:~:text=Starter%20Policy,starting%20point%20for%20many%20sites.) on content-security-policy.com with your Sentry instance as your `report-uri` (you should create a project for this).

```
default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self'; base-uri 'self'; form-action 'self'; report-uri https:://<your self-hosted ingest domain>/api/<project id>/security/?sentry_key=<key>
```

You can find the fully qualified report URI in the project configuration at `https://<YOUR DOMAIN>/settings/projects/<PROJECT ID HERE>/security-headers/.

**Comment by chadwhitacre** [comment]
This is great, @mdtro, thank you!

@noobd3v3loper If this is successful for you, let's write this up [in our documentation](https://develop.sentry.dev/self-hosted/).

**Comment by noobd3v3loper** [comment]
Thanks. I will try it out on our sandbox and will let you know.

**Comment by noobd3v3loper** [comment]
Hello @chadwhitacre @mdtro , I tried the above solution but when i check the console log on the browser, it showing error below:

![image](https://user-images.githubusercontent.com/88873001/227926390-ba058aa6-00a8-4705-b8eb-a5971a7a70fb.png)
![image](https://user-images.githubusercontent.com/88873001/227926537-4db17757-9205-4872-a795-e145b950e259.png)
![image](https://user-images.githubusercontent.com/88873001/227926738-8ad4451c-579a-4c12-9537-6fb52945c331.png)


I just block the self hosted url that i have. 

Thanks

**Comment by chadwhitacre** [comment]
Sorry we haven't been able to help, @noobd3v3loper. Have you figured out anything further here?

**Comment by mdtro** [comment]
Hi @noobd3v3loper, I hope things are going well for you!

I do have an update for you on some `font-src` directive blocks. I'm seeing this in our dogfood instance, so I suspect you are too.

I suggest adding this to the CSP configuration:

```
font-src self https://fonts.gstatic.com/ https://use.typekit.net/;
```

I'm looking in to the `script-src` errors you are encountering. Ideally, I'd like to not allow `unsafe-inline`. We'll see if there are better options there. :)
