### ISSUE TITLE
Cannot Configure 2FA

### ISSUE THREAD

**Issue by Ryanmcdermottperth1990** [getsentry/sentry#45629]
### Environment

SaaS (https://sentry.io/)

### Link

https://pentanet.sentry.io/settings/account/security/

### Steps to Reproduce

1. Accept invite to join invitation to organisation 
2. Click on Configure 2FA 

### Expected Result

I am able to configure 2FA so I can access my organisation 

### Actual Result

I am presented with an error message 
Find attached screenshot of the error message 
<img width="1321" alt="Screenshot 2023-03-10 at 3 13 23 pm" src="https://user-images.githubusercontent.com/112834877/224248321-daeb7012-c226-4b9a-a6b7-7dc9b52724f8.png">

**Comment by markstory** [comment]
Seems like a duplicate of #45577

**Comment by leedongwei** [comment]
@Ryanmcdermottperth1990 The fix is merged, can you check if it's working for you?

**Comment by Christinarlong** [comment]
closed as fixed
