### ISSUE TITLE
The setter 'attachViewHierarchy' isn't defined for the type 'SentryFlutterOptions'.

### ISSUE THREAD

**Issue by ChetanKhanna767** [getsentry/sentry#45636]
### Environment

SaaS (https://sentry.io/)

### Version

sentry_flutter-6.22.0

### Steps to Reproduce

I want to view the UI tree, when the exception happens and as per flutter documentation.
I can do this using
```
Future<void> main() async {
  await SentryFlutter.init(
    (options) {
      options.dsn = 'https://examplePublicKey@o0.ingest.sentry.io/0';
      options.attachViewHierarchy = true;
    },
    appRunner: () => runApp(MyApp()),
  );
}
```
[Link of the doc](https://docs.sentry.io/platforms/flutter/enriching-events/viewhierarchy/)

### Expected Result

Should work as per documentation

### Actual Result

The setter 'attachViewHierarchy' isn't defined for the type 'SentryFlutterOptions'.
Try importing the library that defines 'attachViewHierarchy', correcting the name to the name of an existing setter, or defining a setter or field named 'attachViewHierarchy'

**Comment by marandaneto** [comment]
Its in a pre-release stage, so you have to use the latest RC https://github.com/getsentry/sentry-dart/releases/tag/7.0.0-rc.2
