### ISSUE TITLE
[Default scrubbers] Safe fields behaviour

### ISSUE THREAD

**Issue by masinette** [getsentry/sentry#45668]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Adding "user.id" to the project Safe Field, but it is still filtered.

I tested on my account an only got the wanted result when using "user.id" and "user" together.
I tried these values separately and in combination with one another in the Safe Field: user, id and user.id. 

Steps to reproduce:
1. Create a test event by setting the user.id to sensitive string: Sentry.setUser({"id":"5355849125500546"})
2. Set safe field to id.
3. Sent test event
4. Check if [user.id] is filtered or not
5. Repeat for each entry in project Safe Fields

### Expected Result

The user id being filtered with "user.id" in the Safe Field.

### Actual Result

 - Start with empty field: [empty](https://liv-togethr.sentry.io/issues/3987969029/events/ac3c7d3d5c3b490d87594438077877ce/?project=5904047&query=is%3Aunresolved&referrer=previous-event)
- [id](https://liv-togethr.sentry.io/issues/3987969029/events/6dd5b4ac10794a339db56900b2b657a7/?project=5904047&query=is%3Aunresolved&referrer=next-event) - filtered
- [user](https://liv-togethr.sentry.io/issues/3987969029/events/d1734075935c4b95b82b6fee3c5470b5/?project=5904047&query=is%3Aunresolved&referrer=next-event) - filtered
- [user.id](https://liv-togethr.sentry.io/issues/3987969029/events/e395aab1495e4db2b6f96471bce34d87/?project=5904047&query=is%3Aunresolved&referrer=next-event) - filtered
- [user, id](https://liv-togethr.sentry.io/issues/3987969029/events/a85cb0c50812443499d54107809329df/?project=5904047&query=is%3Aunresolved&referrer=next-event) - filtered
- [user, user.id](https://liv-togethr.sentry.io/issues/3987969029/events/f7f281b895f94a23bdb9f6153ad97718/?project=5904047&query=is%3Aunresolved&referrer=next-event) - not filtered
- [id, user.id](https://liv-togethr.sentry.io/issues/3987969029/events/9338c747846c42fab4339d95ffce8fc1/?project=5904047&query=is%3Aunresolved&referrer=next-event) - filtered
- [user, id, user.id](https://liv-togethr.sentry.io/issues/3987969029/events/246c2f07fb31425c9c24ac03bc696fdb/?project=5904047&query=is%3Aunresolved&referrer=next-event) - filtered
 - Start with empty field: [empty](https://liv-togethr.sentry.io/issues/3987969029/events/ac3c7d3d5c3b490d87594438077877ce/?project=5904047&query=is%3Aunresolved&referrer=previous-event)
- [id](https://liv-togethr.sentry.io/issues/3987969029/events/6dd5b4ac10794a339db56900b2b657a7/?project=5904047&query=is%3Aunresolved&referrer=next-event) - filtered
- [user](https://liv-togethr.sentry.io/issues/3987969029/events/d1734075935c4b95b82b6fee3c5470b5/?project=5904047&query=is%3Aunresolved&referrer=next-event) - filtered
- [user.id](https://liv-togethr.sentry.io/issues/3987969029/events/e395aab1495e4db2b6f96471bce34d87/?project=5904047&query=is%3Aunresolved&referrer=next-event) - filtered
- [user, id](https://liv-togethr.sentry.io/issues/3987969029/events/a85cb0c50812443499d54107809329df/?project=5904047&query=is%3Aunresolved&referrer=next-event) - filtered
- [user, user.id](https://liv-togethr.sentry.io/issues/3987969029/events/f7f281b895f94a23bdb9f6153ad97718/?project=5904047&query=is%3Aunresolved&referrer=next-event) - not filtered
- [id, user.id](https://liv-togethr.sentry.io/issues/3987969029/events/9338c747846c42fab4339d95ffce8fc1/?project=5904047&query=is%3Aunresolved&referrer=next-event) - filtered
- [user, id, user.id](https://liv-togethr.sentry.io/issues/3987969029/events/246c2f07fb31425c9c24ac03bc696fdb/?project=5904047&query=is%3Aunresolved&referrer=next-event) - filtered

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1778) by [Unito](https://www.unito.io)

**Comment by iker-barriocanal** [comment]
Same as [ISSUE-1421](https://getsentry.atlassian.net/browse/ISSUE-1421).

**Comment by Dav1dde** [comment]
Only `id` should actually whitelist the `user.id` field, I tried reproducing this and for me only using `id` actually stops the filtering any other combination (without `id`) has no effect.

**Comment by Dav1dde** [comment]
We additionally changed the safe fields syntax in https://github.com/getsentry/relay/issues/2605 to support the advanced config's path expressions, this means `user.id` will work now as well as just `id` (this will match any field named id).
