### ISSUE TITLE
Support upload of GZIPped artifacts through the API

### ISSUE THREAD

**Issue by urbany** [getsentry/sentry#4566]
Hi, would it be possible to upload GZIPped artifacts through the sentry API when the upload is done with the Header `Content-Encoding: gzip`?

Basically if that header is present during upload Sentry would unzip the received artifact after the upload is complete (ex: a sourcemap) and keep the same name.

**Comment by mattrobenolt** [comment]
You can already do this with the header parameter specified here: https://docs.sentry.io/api/releases/post-release-files/

Note that it's a parameter on the request, NOT an actual header on the request, if that makes sense.

**Comment by urbany** [comment]
@mattrobenolt thank you for the quick reply!
I tried this but without luck:
```js
var params = {
  name: urljoin(this.sentrySettings.publicUrl, filePath),
  file: fs.createReadStream(fileName),
  header: 'Content-Encoding:gzip',
};
```

Still seeing this:
![screen shot 2016-11-18 at 15 47 55](https://cloud.githubusercontent.com/assets/50884/20436046/70e7f7a0-ada6-11e6-9827-40ec67883ba6.png)

**Comment by mattrobenolt** [comment]
Is this on sentry.io?

**Comment by urbany** [comment]
yes

**Comment by mattrobenolt** [comment]
Mind emailing into support@ so I can take a look? :)

**Comment by urbany** [comment]
Sure thing mate, will email right now, thanks!

**Comment by kmiyashiro** [comment]
Any updates on this?

**Comment by mattrobenolt** [comment]
@kmiyashiro I have not fixed this yet, but definitely plan on doing so soon. Possibly this week.

**Comment by mattrobenolt** [comment]
Reopening since this was a thing I thought worked, which doesn't. Bad mistake considering I wrote the code too. :(

**Comment by kmiyashiro** [comment]
🎉 🎉 🎉

**Comment by mattrobenolt** [comment]
welp, something here wasn't great. Will need to try again.

**Comment by duizendnegen** [comment]
Could I ping you for an update?

**Comment by urbany** [comment]
Hi @mattrobenolt sorry for bothering you, but do you know if this is still getting fixed?

**Comment by LevelbossMike** [comment]
@mattrobenolt Does this mean it's impossible to upload gzipped files? This is slowing down deployment considerably. Can we help in any way getting this fixed?

**Comment by duizendnegen** [comment]
Any update @mattrobenolt?

**Comment by duizendnegen** [comment]
Could I ask again for an update on this @mattrobenolt?

**Comment by Saravanan90** [comment]
Looking forward for gzip support in Sentry, it will make things simple

**Comment by xcambar** [comment]
To the many people waiting for this issue to move forward: did you find a service (and if so, which?) that you'd recommend for features/support/community?

My email is open if not comfortable to reply here.

**Comment by tylerteem** [comment]
Has anyone found a workaround for this?

**Comment by BYK** [comment]
I'm told that #9238 should have fixed this. Will verify and close if that's the case and investigated more otherwise.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
