### ISSUE TITLE
Source map project settings needs to show bundles with debug ids

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#45686]
## Problem
There is no way for a user to see bundles and it's artefacts which only have debug ID's

### Musts
For this ticket to be closed…

- [x] Within the source map project settings screen, a user can navigate to a table populated with bundles which only have debug ID's
- [x] A user can filter that table of bundles by debug-id

### Nice to have's
Remaining items can be moved to backlog…
```
`*` Indicates when the criteria is applicable for both debug id and release bundles**
```
- [x] A user can see if a `release` or `dist` has been bound to a specific bundle
- [x] A user can see all the artefacts of a “debug ID bundle”
- [x] A user can filter the table of artefacts by `debug-id` or `path`
- [ ] A user can see the file type of artefact `*`
  - minified source
  - source
  - source map
  - indexed ram bundle
- [x] A user can see the debug ID specific to the artefact
- [ ] A user can no longer see the time when a bundle's artefact was created `*`
- [x] A user can no longer delete a specific artefact from a bundle `*`

## Design
[Figma Link](https://www.figma.com/file/uB5BxSAYy4JylKVzyPtSZu/Specs%3A-Source-Map-Project-Settings-v2?node-id=0%3A1122&t=vdb0bebJEH2klKVW-1)

By default, the release bundles are loaded first
![Image](https://user-images.githubusercontent.com/6508377/225581923-f4200a98-f75b-498e-a3f6-24795b55e073.png)

However, the user can navigate to a table specific for bundles with debug ID's
![Image](https://user-images.githubusercontent.com/6508377/225582059-e608bbbc-79fa-42ec-ad26-bd8baba13270.png)

If time and technology permits, it would be nice if a user can see the contents of a bundle
![Image](https://user-images.githubusercontent.com/6508377/225582186-b3895b43-6a11-463c-92e3-573113e64359.png)

**Comment by iambriccardo** [comment]
- Search will be done by bundle_id in the bundles view
- Search will be done by debug_id and file path in the bundle view
- We want to show multiple chips for release, dist in the bundles view and not in the bundle view

**Comment by Jesse-Box** [comment]
@iambriccardo I've updated the AC's accordingly

**Comment by priscilawebdev** [comment]
**Notes:**

- A user can no longer see the time when a bundle's artifact was created *

we decided to not update the release artifacts UI with this new change now, therefore we still display the time in the release artifacts UI

- A user can see the file type of artefact *

we decided to not update the release artifacts UI with this new change now, therefore we don't yet display this info in the release artifacts UI 

- `Invalid` is missing from the list:

>  A user can see the file type of artefact *
> minified source
> source
> source map
> indexed ram bundle


we decided to not update the release artifacts with these new changes now, therefore we don't display the above in

**Comment by priscilawebdev** [comment]
Everything has been implemented and now we are just collecting feedback so I am closing this issue
