### ISSUE TITLE
Please do not use error code like 429 for throttled requests

### ISSUE THREAD

**Issue by Knagis** [getsentry/sentry#45708]
### Problem Statement

I can't count how many users, QAs etc. have submitted to us screenshots saying "webapp crashed, look at this red Sentry 429 line" and completely ignoring that they need to scroll a bit up to see the actual error.

Over time this has accumulated in significant amount of developer time, every time explaining the user what to ignore and where to look. Especially concerning when issues are hard to reproduce and users have missed the opportunity by taking note of the wrong thing.

### Solution Brainstorm

Best option would be to be able to configure sentry to issue requests with some additional `&never429=true` argument that the backend reads and returns the error in the body, not as http status. This can still be shown in browser console as warning or info message, as long as it isn't red in console or in network trace.

**Comment by evanpurkhiser** [comment]
Routing to SDK teams

**Comment by mitsuhiko** [comment]
The ask here is for the backend to issue different status codes. Given how complex our routing system is and how reliant we are on the 429 handling I can exclude that we will be able to change this easily.

You could however configure and run a tunnel for the JavaScript SDK which would hide the status code.

https://docs.sentry.io/platforms/javascript/troubleshooting/
