### ISSUE TITLE
Publicize/Document our UI-based (unofficial) API

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#45707]
### Problem Statement

Currently undocumented, our UI-based API could be leveraged to complete a myriad of tasks not possible with our currently documented API. (Ex. - Material Security is trying to leverage our API to programmatically access their Org’s Audit Log)

### Solution Brainstorm

Document available API parameters to encourage ease of use. (Ex. - Timeframe, Org/projectID, Multiple actions as opposed to the single dropdown filter [or make this a multi-filter?]) 
Encourage the use of multiple parameters at once. For Audit log purposes, this would go beyond what's available in the UI.

**Comment by JoshFerge** [comment]
@kpujjigit mind listing out which APIs you'd like us to make public? we have hundreds of undocumented APIs. is it only audit logs?
