### ISSUE TITLE
Ability to use numerical values for issue alerts

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#45710]
### Problem Statement

Currently, users are unable to use operators on numerical values that are sent as tags in events.

From user: I have events where I send as part of the tags I expose numerical values.
I want to create an alarm over these events and set a threshold on the value of the tag. The problem is, the tag value is always string and I can't use < to > functions on string values.

### Solution Brainstorm

Expose the numerical value of tags for the ability to create alarms over it

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1777) by [Unito](https://www.unito.io)

**Comment by brianthi** [comment]
Backlogging this for now, however it's unlikely we'll pick this up any time soon as it would likely require significant development time.  

@kerenkhatiwada can you provide examples of tags are customers looking to create alerts in this way for?

**Comment by brianthi** [comment]
Heard back from some others and this is not a feature we'd be able to support.  Closing this issue for now, but still curious what tag values they're trying to create alerts for.

**Comment by kerenkhatiwada** [comment]
@brianthi I'll check in with the customer on this and provide info in the linked Jira.
