### ISSUE TITLE
Create monitor deletion task

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#45736]
When we delete a monitor we want to make sure all related checkins and other relations get deleted. If a monitor has minute checkins, there will be potentially 130k rows in the checkins table, so we don't want to rely on Django to delete these since the db query will likely time out.

Instead, we should add an entry for monitors to deletions. This is a decent example: https://github.com/getsentry/sentry/blob/2ec9adaa218e4097caa36e456c160b7cbe906b94/src/sentry/deletions/defaults/commit.py#L4-L12

Also, when deleting a monitor we should use `ScheduledDeletion.schedule` to schedule the deletion to make sure it happens correctly.

**Comment by rjo100** [comment]
Also need to add logic to `transfer_to` if a project changes organizations
https://github.com/getsentry/sentry/blob/f0cfb25daf1c3cc6cef2f28a06d4085dea5c93c3/src/sentry/models/project.py#L293

**Comment by rjo100** [comment]
Looks like we're already using scheduled deletion

**Comment by rjo100** [comment]
https://github.com/getsentry/sentry/pull/46646
