### ISSUE TITLE
Empty response when querying API tokens from a superuser account

### ISSUE THREAD

**Issue by bartscherer** [getsentry/sentry#45758]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.2.0

### Steps to Reproduce

1. Set the is_superuser flag for your user to "true" within Postgres
2. Open the Settings -> Account -> API -> Auth Tokens page
3. If there is no token, create one. Otherwise skip this step

### Expected Result

A list of auth tokens containing the created ones

### Actual Result

An empty list of auth tokens

**Comment by bartscherer** [comment]
Within the file [src/sentry/api/endpoints/api_tokens.py](https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/api_tokens.py#L28) (method `ApiTokensEndpoint.get`) you can see that, if the request is sent by a superuser account, a query parameter named "userId" is required to fetch a list of tokens. The UI doesn't contain e.g. a field to enter the desired user to query API tokens for so the request will always show an empty list because the "userId" parameter will never be filled. 

```python
    @never_cache
    def get(self, request: Request) -> Response:
        user_id = request.user.id
        if is_active_superuser(request):
            user_id = request.GET.get("userId") # this will always be empty when the request is sent via the UI!

        token_list = list(
            ApiToken.objects.filter(application__isnull=True, user_id=user_id).select_related(
                "application"
            )
        )
```

My proposal would be either to 

1. Set the default value for "userId" to the superuser's ID if it's empty
2. Add frontend controls for selecting a user account whose tokens will be queried

Code for 1.:

```python
        if is_active_superuser(request):
            user_id = request.GET.get("userId", user_id) # the default value is now the user's ID
```

**Comment by dashed** [comment]
@bartscherer This should be addressed by https://github.com/getsentry/sentry/pull/46965.
