### ISSUE TITLE
Display number of issues for a query

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/sentry#4577]
I'm looking for the number of issues matching a query on the issue listing and I'm not seeing it, e.g., on:

https://sentry.io/gratipay/gratipay-com/

![screen shot 2016-11-21 at 9 26 09 am](https://cloud.githubusercontent.com/assets/134455/20486123/94f7eb96-afcc-11e6-8b57-94c31b0b20f1.png)

**Comment by mattrobenolt** [comment]
Hey @whit537, unfortunately, we don't really have this information at the time of the query. The only case we'd actually know a count is if the number of results were less than 1 page. But in which case, this might be awkward to show a count sometimes, and not others.

Is this what you're referring to?

**Comment by whit537** [comment]
This is what I'm referring to, yes. A pattern I've seen in other applications such as Gmail is to give estimates where exact counts aren't known. Is that maybe more doable?

![screen shot 2016-11-21 at 11 42 43 am](https://cloud.githubusercontent.com/assets/134455/20491511/a51da3fe-afdf-11e6-86a3-6217da7d44c1.png)
![screen shot 2016-11-21 at 11 42 13 am](https://cloud.githubusercontent.com/assets/134455/20491512/a524f212-afdf-11e6-9c78-331995529896.png)
![screen shot 2016-11-21 at 11 42 24 am](https://cloud.githubusercontent.com/assets/134455/20491513/a5254636-afdf-11e6-9a08-020606d4c620.png)

**Comment by dcramer** [comment]
I tried this a while back and for whatever reason my patch failed out. I dont recall which commit, but it was an attempt to make the cursor/paginator always include count estimates.

**Comment by whit537** [comment]
As a workaround for a single page of results I am searching for ` old` on the page.

**Comment by castlec** [comment]
is this still a perceived problem? @dcramer Do you have suggestions on implementations if so.

**Comment by dcramer** [comment]
We already do this in current Sentry
