### ISSUE TITLE
[Design] Search by DOM elements that were clicked

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#45781]
### Goal:

For the Session Replay feature to search replays by DOM elements that were clicked by end-users, we require designs in order to demonstrate how a user can use this capability.

**Acceptance criteria:** 

- This capability should be presented in the autocomplete when the Replay Index search box is clicked so it is discoverable 
- We should guide the user to completing the query with our autocomplete experience 

It would be good to explore both a selector and purely text approaches in the Search -- to see which can provide the best user experience.

**Comment by ryan953** [comment]
We've settled on a search syntax/field naming convention. it'll look like this:

- `replay_click.tag:div`
- `replay_click.class:btn AND replay_click.class:btn-primary`
- `replay_click.class:btn-*`
- `replay_click.selector:div#id.class[alt=”a good puppy”]`

See also:
- https://github.com/getsentry/sentry/pull/45763/files#diff-0e4d43542249b0417d788646d1263990affac44f3c80c8740d23849db1d8e42c
- https://github.com/getsentry/sentry/pull/45744/files
- https://github.com/getsentry/sentry-docs/pull/6465/files
