### ISSUE TITLE
Improve query performance for the replay details page

### ISSUE THREAD

**Issue by cmanallen** [getsentry/sentry#45846]
### Problem Statement

The query to fetch an individual replay is slower than it needs to be.

### Solution Brainstorm

Currently, the query groups by the "replay_id" alias.  "replay_id" is an alias of the column "replay_id" converted to a string with its dashes stripped.  By renaming this alias to something else we can group on replay_id *column* which will allow us to utilize its bloom filter index.

**Comment by JoshFerge** [comment]
https://github.com/getsentry/sentry/pull/45715/files :D wanted to end friday with a smaller win & looked at this
