### ISSUE TITLE
[Replay] Link to Replay on Issue Detail when no replay is available

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#45841]
When visualizing an issue detail that had a Replay related, we show a Replay button on the top:

![image](https://user-images.githubusercontent.com/1633368/225369849-53dd660f-89d0-4f83-9d62-bc093ff47ed8.png)

Sometimes the Replay is not available, for example, when it's deleted. In that case, the button scrolls to where the replay should be in the page and a message shows:

> The replay associated with this event could not be found.

This leads to poor UX. The Replay Tab already exists showing related replays for that issue so there's enough visibility about Replays on the top part of that page.

![image](https://user-images.githubusercontent.com/1633368/225370449-c954f231-c235-4250-ae52-c7421bc51f4c.png)

We're better off removing the "⏯️  Replay" button and avoid the scrolling if there's no replay for the specific issue.

Raised by a customer: https://github.com/getsentry/team-replay/issues/47

**Comment by ryan953** [comment]
When the replay in question is not available this message is displayed to the user:

<img width="948" alt="SCR-20230319-mnt" src="https://user-images.githubusercontent.com/187460/226216084-e011723f-9ca6-4cb8-ba09-b3ed0f258b79.png">


We have similar messages for when traces are missing too:
<img width="956" alt="SCR-20230319-mni" src="https://user-images.githubusercontent.com/187460/226216121-c29ffabd-c308-425e-a1f8-7ebb50d2e2be.png">


The solution should not be to remove the button and hide the problem, instead what we should do is link from the message into the docs.

**Comment by ryan953** [comment]
See also https://github.com/getsentry/sentry/issues/43965
