### ISSUE TITLE
Performance transaction rate limit

### ISSUE THREAD

**Issue by rychlis** [getsentry/sentry#45856]
### Problem Statement

For performance monitoring, I know we can use [traces_sample_rate](https://docs.sentry.io/platforms/python/configuration/sampling/#setting-a-uniform-sample-rate) and [traces_sampler](https://docs.sentry.io/platforms/python/configuration/sampling/#setting-a-sampling-function) in the application to limit performance transaction sampling, however sometimes a new endpoint is added or a bug is introduced on the app side that triggers thousands of transactions that we don't need in the APM, but uses up our transactions budget for the whole organisation.

### Solution Brainstorm

I'd like to limit number of transaction for each project separately - there should be a way to split the transaction budget between projects, so a single bug/misconfiguration doesn't exhaust our transaction count for the whole organisation for the whole billing period.

As a possible solution, it would be great if I could set similar rate limit to how errors can be limited per DSN, but for transactions: 

![Screenshot 2023-03-15 at 19 29 02](https://user-images.githubusercontent.com/1819747/225407777-e9b8d8f4-a510-43e3-a86e-b7f7eed6a71d.png)

Ideally there should be a default rate limit configured for organisation so all new DSNs have it.

I noticed there is a feature called "Dynamic Sampling" which seems to be related, not sure if it applies to APM as well?

**Comment by rychlis** [comment]
The support agent told me about https://github.com/getsentry/sentry/discussions/44562 which might be a good enough solution for my problem, will try it out :)

**Comment by 0Calories** [comment]
Glad to hear you got it sorted! 😄 

Going to close the issue
