### ISSUE TITLE
Transaction sample rate on Sentry's end

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#45869]
### Problem Statement

On a high level, this is a very simple idea: instead of setting a transaction sample rate on the client (referring to the application that is sending traces), there should exist a sampling solution on Sentry's side. Similar to inbound filters for events, which allow for unwanted events to be discarded before they are counted towards the quota, such a filter for transactions would allow dropping transactions before they are sampled.

### The sampling algorithm 

The naivest approach is simply a "sample n% of transactions" kind of filter. However, since Sentry would have access to all transactions, more complicated algorithms could be implemented that takes into account how many transactions are being sent, and from that dynamically adjusts the sample rate. This idea would also fix the problem of the number of transactions being proportional to the number of users, thus ingesting next to no transactions at night. Now, we could guarantee a steady number of transactions throughout the entire day.

### Exploring even further

Exploring this idea even further, an even more complicated algorithm could also vary that very rate depending on the name of the transaction. For a service with two routes, one of which being visited 50x as often as the other, we currently get next to no transactions for the less visited route. With a limiter that takes this into account, we could weigh less visited routes more, thus making sure both routes are covered equally.

[Dynamic Sampling](https://docs.sentry.io/product/data-management-settings/dynamic-sampling/) does some sort of selection of highest-valued transactions, so the same algorithm could be applied _before_ billing a transaction.

---

There are a few main gains from this:
- **Maintainability** - While most of the proposed ideas can already be implemented with custom transaction sampling logic, that approach would require _a lot_ of work and maintaining to keep numbers up to date. A service gets more traffic, or the relative distribution of route visits changes? Need to change numbers in the code accordingly. All in all, far too much work would go into such a solution on the client. This effort also grows with an increasing number of projects. 

- **Coverage** - Unless you implement a solution like outlined above, routes with much traffic generate many more sampled transactions than ones that receive far less traffic. This can manifest in too few data points for poorly visited routes and with that invalidating any statistics Sentry is able to offer for that route. In our case, we have routes that only receive a transaction every couple of minutes, simply because of the enormous difference in traffic between this route and more visited ones.

- **True TPM** - In order to get the true number of request per minute, you currently need to multiply whatever TPM you see with the fixed transaction rate you have set in the SDK. This approach goes completely nil with dynamic sampling rates described above. Instead, Sentry now has access to the true number of transactions per minute and can display that number accurately. 

- **Dynamic Sampling** - As highlighted in [this article](https://docs.sentry.io/product/data-management-settings/dynamic-sampling/), Sentry doesn't numerically take every single ingested transaction into account. Makes sense, doesn't it? A close enough estimation based on samples is more than good enough. The article recommends sending 100% of transactions to Sentry if possible: rip budget. With this not being a viable option for many customers, the effect of dynamic sampling decreases as less transactions means less transactions to sample from. 

--- 

The key idea in this thread is transaction filtering on Sentry's end before they are counted towards the quota, thus billed. If Sentry selects which transactions are discarded before they are counted towards the quota and further processed, this ultimately opens the door to higher quality metrics in Sentry.

**Comment by silent1mezzo** [comment]
Thanks for the detailed feature request @jeengbe. Everything you've listed here is exactly what we're trying to do, and have done, with Dynamic Sampling. 

The goal of Dynamic Sampling is to be entirely invisible to a developer, you send us your transactions and Sentry figures out which transactions to store and, more importantly, which metrics to extract and aggregate to give you an accurate view of your applications performance. In a perfect world, we'd only ever store the transactions that you need to solve performance problems or see what's happening around an error. Everything else would be derived from the metrics extracted by Dynamic Sampling.

The main reason why we can't run Dynamic Sampling before billing a transaction is that it costs money to run the algorithm and store the metrics (we did decrease the cost of transactions when we implemented this). We feel that the value you get from having these metrics (getting that holistic view of performance) is worth it.

**Comment by jeengbe** [comment]
Hi @silent1mezzo!

It would really go a long way if we could even find some sort of compromise on this topic. Currently, finding a good transaction rate is a real headache: request count varies greatly over the course of a day as well as on a seasonal basis and must be kept up-to-date with actual session count. This adds a lot of uncertainty and very granular number tweaking for finding a good rate.

A dead simple mechanism that takes the desired number of requests per, say, minute, and divides that by the total number of requests in the last minute would solve exactly that problem with little effort. 
The great benefit from this is that this would make it really simple to set a fixed transaction rate and not having to deal with fine numbers in the 0.00x's for very large projects.

This might be worth a discussion on GitHub to see how others think about this and whether actually testing this impact might be worth the effort.
