### ISSUE TITLE
Can we disable or run dashboard on different port?

### ISSUE THREAD

**Issue by vady1** [getsentry/sentry#4586]
Hi,

I have configured Sentry on our server. Great application !! We want to enable front-end logging however we don't want to expose our dashboard publicly. Is it possible to run dashboard on different dashboard and receive the logging on port 80? 

Thank you,
Vady

**Comment by dcramer** [comment]
This simple requires you to configure your load balancers appropriately. 

That said, this isn't a support forum, so I'm closing this ticket out. You can ask on our public forum (forum.sentry.io), but this is a general operational issue and isn't Sentry specific.

**Comment by vady1** [comment]
Thank you for quick response.
