### ISSUE TITLE
Session Replay React-Native support

### ISSUE THREAD

**Issue by gakinson** [getsentry/sentry#45873]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Hello,

I was wondering what your timeline is for supporting react-native for your new session replay feature?

### Expected Result

Support react-native session replay

### Actual Result

Not supported ATM.

**Comment by ryan953** [comment]
Hey @gakinson thanks for your interest in Session Replay and react-native!

We're tracking this feature over here: https://github.com/getsentry/sentry-react-native/issues/2703 so I'm going to close this one out as a duplicate.

But you should give that issue a 👍 to boost it up even more, and subscribe to follow along when updates become available.
