### ISSUE TITLE
message attribute in payload

### ISSUE THREAD

**Issue by WoZ** [getsentry/sentry#4588]
Hi!

I've found that some sentry clients don't send `message` field with exceptions.

raven-node sends it even with string passed to captureException, sentry-php deleted this field in 1.x branches, raven-js doesn't pass `message` started from 3.2.x versions and still pass when string passed to captureException.

First of all, I've checked official [sentry documentation]( https://docs.sentry.io/clientdev/attributes/#required-attributes) and it says that `message` is required.

Is `message` always required? Is documentation is in actual state?

**Comment by dcramer** [comment]
@WoZ its only required when other structured data isnt present. We're moving towards making 'message' auto convert to the 'sentry.interfaces.Message' structure. If you pass an Exception for example, you dont need any kind of message to go along with it.
