### ISSUE TITLE
Release adoption by device/platform

### ISSUE THREAD

**Issue by stx** [getsentry/sentry#45892]
### Problem Statement

We release to many different platforms, including iOS, Android, Apple Watch, Wear OS and the web. It would be useful to see release adoption by device family. According to our investigation of the Sentry dashboard, and Sentry support, you can do this via issues but there is no way to do this with releases.

We were invited by Sentry support to create this issue.

### Solution Brainstorm

Allow filtering releases similar to how you can filter issues. Or, at the least, by device.

**Comment by brianthi** [comment]
Hi @stx, unfortunately there's no way to get this number accurately at the moment. It's not something we have planned for our roadmap, but I will share this feedback with our team.
