### ISSUE TITLE
Issue was marked as regression for a release before a resolved commit

### ISSUE THREAD

**Issue by eric** [getsentry/sentry#45904]
### Environment

SaaS (https://sentry.io/)

### Link

https://fancy-bits-llc.sentry.io/issues/3987482407/

### Steps to Reproduce

1. Resolve an issue with a commit
2. Wait

### Expected Result

Issue stays resolved until it happens again on a release that contains the commit

### Actual Result

The issue is marked as a regression for an older release than the commit.

**Comment by scttcper** [comment]
The releases are being parsed as semantic versions but the release that is unresolving the issue has parsed the version as `2023.0.0-build-version` which is greater than the version its being resolved in `5.x.x`. 

The 2023 release will continue to mark things as unresolved since sentry is comparing the two versions to determine if the release is newer than the version the issue was marked as resovled in - eg "marked this issue as resolved in 5.x.x (build)"

**Comment by eric** [comment]
I see. I expected Sentry to be tracking what commits are in what releases.

Because of idiosyncrasies of the Apple deployment process we do not have our beta build versions matching the release versions. TestFlight builds require a review by Apple for every version change, so we set the version to the current year so that we only have one review per year to allow us to do TestFlight builds as often as we want.

I guess this means that we would need to separate our release vs beta builds into separate projects? Is there any documentation regarding the assumptions (like versions) around projects, environments, etc? It was never clear when we were setting up our project how exactly to model what we were trying to do.

It would be a shame to no longer have exceptions linked between beta and release builds, but it's also not great right now to not have resolving working. The big issue I can think of right now between having beta and release in separate projects is it would require us to resolve an issue twice.

**Comment by Dhrumil-Sentry** [comment]
Hi @eric , At the moment we have the following documentation about [Environments](https://docs.sentry.io/product/sentry-basics/environments/)

This [doc](https://docs.sentry.io/product/releases/#different-ways-to-resolve-issues) explains how Resolve in Current/Next Release works

I've seen customers work around the problem you are describing by creating separate projects for different environments. Yes it can lead to having to resolve issues twice but these customers often fixed issues in staging environments so seeing the same issue in prod environments would be rare.

We've also gotten feedback from customers that they like the fact that events from staging env can mark an issue as a regression to get better monitoring but they likely don't have the tvOS release version challenges you face

**Comment by eric** [comment]
The Environments docs don't talk about how Sentry expects versions to match across environments in a given project.

...and the docs for Resolve don't really talk about how versions interact with environments.

We _would_ like to have one bucket of Issues across our TestFlight and App Store releases, but because we have different version schemes, it doesn't appear that's viable right now in Sentry.
