### ISSUE TITLE
Problem configuring multifactor authentication

### ISSUE THREAD

**Issue by TheOriginalJimGo** [getsentry/sentry#45901]
### Environment

SaaS (https://sentry.io/)

### Link

https://sentry.io/settings/account/security/

### Steps to Reproduce

1. Follow the link to confirm my E-mail address
2. Site says that I need to set up MFA, so I click the button
3. Site say:
![image](https://user-images.githubusercontent.com/112049280/225474928-b5bfb1c9-39cb-4fb1-8af6-d6368bc02e21.png)

Given that it has been several hours and your logs should tell you my UserID (since I'm part way through the registration process), I'm not sure I believe the "we're working on it" part (otherwise, I hope someone would have contacted me by now to at least confirm the "we're working on it"). 

### Expected Result

To be able to set up my MFA

### Actual Result

Unable to set up my MFA
![image](https://user-images.githubusercontent.com/112049280/225475506-bef66b5d-ce1e-4ea0-937d-8110a48a36b9.png)

**Comment by leedongwei** [comment]
@TheOriginalJimGo I'm not able to replicate, let me take a closer look and I'll get back in a bit.

**Comment by leedongwei** [comment]
@TheOriginalJimGo Could you reach out to us at support@sentry.io, using the email address of the affected acount?

No need to write anything, you can just put the link of this Github thread in the email. The support team will forward it to me.
