### ISSUE TITLE
authentication failiure issue with jenkins integration

### ISSUE THREAD

**Issue by gagnish** [getsentry/sentry#45907]
### Problem Statement

Hi,

I am getting the below error while i integrate the jenkins with the sentry. I have added the steps in jenkins file and getting the below API error after running the job-

error: API request failed
  caused by: sentry reported an error: Invalid token (http status: 401)

**Comment by gagnish** [comment]
Hi Team,

Please help on this as soon as possible. as this is urgent issue.

**Comment by brianthi** [comment]
Also, did you create a token as described in our docs? https://docs.sentry.io/product/releases/setup/release-automation/jenkins/

**Comment by gagnish** [comment]
@brianthi @armenzg yes i have followed the same document , i have created the token in sentry and used as a secret text in jenkins. I have added the steps in jenkins file with same token i have created in sentry, but after executing the jenkins job i am getting the below error-

---------------------------------------------
+ command -v sentry-cli
/usr/local/bin/sentry-cli
[Pipeline] sh
+ sentry-cli releases propose-version
+ export SENTRY_RELEASE=05e843f3207de9b22c6f1d4ff94d246b32be9954
+ sentry-cli releases new -p test 05e843f3207de9b22c6f1d4ff94d246b32be9954
error: API request failed
  caused by: sentry reported an error: Invalid token (http status: 401)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

**Comment by armenzg** [comment]
From the response, the token is either not loaded or has permission issues.

You can actually run those steps locally just to test that the token is valid. You will have to export SENTRY_AUTH_TOKEN.

If it doesn't work, check that the permissions of the token match [this](https://docs.sentry.io/static/7db283b3cefe98abc19cc2a421bc17a4/aa440/internal-integration-permissions.png) and try again.

If that works, would you be able to double check that the token is declared properly in Jenkins? (maybe there's a white space when copy-pasting; it's happened to me) 

Or even try --log-level=debug to see if it shows more.

**Comment by gagnish** [comment]
@armenzg , checked the permission was fine and also checked the space in token, but still having the same issue.
can you please share the sample jenkins file with sentry steps, or can we schedule a call if possible.

**Comment by gagnish** [comment]
@armenzg @getsentry-bot , Please help on this to resolve this issue as soon as possible.

**Comment by gagnish** [comment]
@armenzg @getsentry-release @brianthi @getsentry-bot  , please update on this. Need your support urgently.

**Comment by armenzg** [comment]
@gagnish have you tried reproducing locally? Can you please paste the output from trying locally?

Could you also provide a link to your org? I can validate your configuration.

My apologies on the delay I was off.

You can create a new token to prevent pasting the production one by mistake.

**Comment by armenzg** [comment]
Also, is this for self-hosted or SaaS?

**Comment by gagnish** [comment]
@armenzg , we are using this service as a self hosted. I have tried it locally but getting the below error-
Also i have tried after regenerate the token but same error.

OPN-MC-284:~ gagnish.dhiman$ export SENTRY_RELEASE=$(sentry-cli releases propose-version)
error: Could not automatically determine release name
---------------------------------------------------------

And after adding the 'export SENTRY_LOG_LEVEL=[info|debug]' in jenkins file i am getting the below error on jenkins job-

/var/lib/jenkins/workspace/uat-k8s-icp-2/code@tmp/durable-91f44820/script.sh: 3: /var/lib/jenkins/workspace/uat-k8s-icp-2/code@tmp/durable-91f44820/script.sh: debug]: not found

**Comment by armenzg** [comment]
Locally, are you running the command within a Git checkout?

I'm running the following within Sentry's checkout:
```
sentry-cli releases propose-version
0042e02db2775a6eb80c51f121680b4807293ff6
```

If I do it anywhere else I will get this error:
```
sentry-cli releases propose-version
error: Could not automatically determine release name

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

**Comment by gagnish** [comment]
@armenzg , i tried through Sentry CLI, getting the same error-

OPN-MC-284:~ gagnish.dhiman$ sentry-cli releases new -p test 97219bcef89842ed6bd202e678bb548f6815e014
error: API request failed
  caused by: sentry reported an error: Invalid token (http status: 401)

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
OPN-MC-284:~ gagnish.dhiman$

**Comment by armenzg** [comment]
@gagnish this is not a product issue. You need to pay close attention to the output and follow the documentation very closely. I will let the @getsentry/support team follow up with you

**Comment by hubertdeng123** [comment]
Echoing Armen here, seems like your token isn't valid. If you're able to reproduce this issue locally then it's not too surprising that it's happening in Jenkins for you. One last thing, `sentry-cli` defaults to using sentry.io so you need to set the `SENTRY_URL` environment variable to point to your self-hosted instance.
https://docs.sentry.io/product/cli/configuration/

**Comment by souredoutlook** [comment]
Hi @gagnish if you want to open up a ticket with our Support team we can look at this in greater detail but I will echo what @hubertdeng123 and @armenzg have shared - this does not appear to be unexpected behaviour

**Comment by gagnish** [comment]
@hubertdeng123 , that Token API error is now resolved, but now getting the below error-

OPN-MC-284:~ gagnish.dhiman$ sentry-cli releases  new -p $SENTRY_PROJECT $SENTRY_RELEASE --log-level=debug
  INFO    2023-03-30 13:16:09.183447 +05:30 Loaded config from /Users/gagnish.dhiman/.sentryclirc
  DEBUG   2023-03-30 13:16:09.183858 +05:30 sentry-cli version: 2.16.0, platform: "darwin", architecture: "arm64"
  INFO    2023-03-30 13:16:09.183903 +05:30 sentry-cli was invoked with the following command line: "sentry-cli" "releases" "new" "-p" "test" "2383680bb0f5732b6593901cb4a1b1cd3104c64a" "--log-level=debug"
  DEBUG   2023-03-30 13:16:09.185434 +05:30 request POST https://sentry.bankopen.com/api/0/projects/Sentry/test/releases/
  DEBUG   2023-03-30 13:16:09.185470 +05:30 using token authentication
  DEBUG   2023-03-30 13:16:09.185558 +05:30 json body: {"version":"2383680bb0f5732b6593901cb4a1b1cd3104c64a","projects":["test"],"dateStarted":"2023-03-30T07:46:09.185141Z"}
  DEBUG   2023-03-30 13:16:09.185776 +05:30 retry number 0, max retries: 0
  DEBUG   2023-03-30 13:16:09.690270 +05:30 > POST /api/0/projects/Sentry/test/releases/ HTTP/1.1
  DEBUG   2023-03-30 13:16:09.690420 +05:30 > Host: sentry.bankopen.com
  DEBUG   2023-03-30 13:16:09.690449 +05:30 > Accept: */*
  DEBUG   2023-03-30 13:16:09.690476 +05:30 > Connection: TE
  DEBUG   2023-03-30 13:16:09.690507 +05:30 > TE: gzip
  DEBUG   2023-03-30 13:16:09.690534 +05:30 > User-Agent: sentry-cli/2.16.0
  DEBUG   2023-03-30 13:16:09.691137 +05:30 > Authorization: Bearer 57cfa1b0***
  DEBUG   2023-03-30 13:16:09.691195 +05:30 > Content-Type: application/json
  DEBUG   2023-03-30 13:16:09.691221 +05:30 > Content-Length: 118
  DEBUG   2023-03-30 13:16:09.789787 +05:30 < HTTP/1.1 404 Not Found
  DEBUG   2023-03-30 13:16:09.789969 +05:30 < Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding
  DEBUG   2023-03-30 13:16:09.790037 +05:30 < Access-Control-Allow-Methods: GET, POST, HEAD, OPTIONS
  DEBUG   2023-03-30 13:16:09.790089 +05:30 < Access-Control-Allow-Origin: *
  DEBUG   2023-03-30 13:16:09.790138 +05:30 < Access-Control-Expose-Headers: X-Sentry-Error, Retry-After
  DEBUG   2023-03-30 13:16:09.790186 +05:30 < Allow: GET, POST, HEAD, OPTIONS
  DEBUG   2023-03-30 13:16:09.790234 +05:30 < Content-Language: en
  DEBUG   2023-03-30 13:16:09.790282 +05:30 < Content-Type: application/json
  DEBUG   2023-03-30 13:16:09.790329 +05:30 < Date: Thu, 30 Mar 2023 07:46:10 GMT
  DEBUG   2023-03-30 13:16:09.790377 +05:30 < Server: nginx
  DEBUG   2023-03-30 13:16:09.790424 +05:30 < Vary: Accept-Language, Cookie
  DEBUG   2023-03-30 13:16:09.790472 +05:30 < X-Content-Type-Options: nosniff
  DEBUG   2023-03-30 13:16:09.790518 +05:30 < X-XSS-Protection: 1; mode=block
  DEBUG   2023-03-30 13:16:09.790567 +05:30 < Content-Length: 50
  DEBUG   2023-03-30 13:16:09.790615 +05:30 < Connection: keep-alive
  DEBUG   2023-03-30 13:16:09.790701 +05:30 response status: 404
error: project not found

**Comment by souredoutlook** [comment]
It looks like your organization slug is set to "Sentry" is this correct? Likewise, if the project "test" does not actually exist you can't update a resource for it.

We don't actually have the ability to verify these things because the instance is self-hosted.

**Comment by gagnish** [comment]
@souredoutlook yes our organization slug is set to 'Sentry' and i have already create the project called 'test'.
Please find the below screenshot for reference. i have tried this on locally as well as in jenkins file , it acts as same error.



<img width="977" alt="image" src="https://user-images.githubusercontent.com/73713601/228835492-73514fab-db05-417a-b46e-c77eed852d3f.png">
