### ISSUE TITLE
Resolving an issue with a commit keeps being reverted

### ISSUE THREAD

**Issue by eric** [getsentry/sentry#45903]
### Environment

SaaS (https://sentry.io/)

### Link

https://fancy-bits-llc.sentry.io/issues/3987482407

### Steps to Reproduce

1. Hit the "Resolve" dropdown
2. Select "A commit..."
3. Specify `0358352`

### Expected Result

The issue is resolved

### Actual Result

The issue doesn't get resolved.

**Comment by scttcper** [comment]
Once the commit is attached to a release, sentry gets the version from that release and compares the versions with the new event.

I think this a pretty similar problem to #45904 and sentry is having trouble parsing your release version semantically.
