### ISSUE TITLE
Unable to configure two factor auth

### ISSUE THREAD

**Issue by STC-Manas** [getsentry/sentry#45914]
### Environment

SaaS (https://sentry.io/)

### Link

https://the-giving-movement.sentry.io/settings/account/security/

### Steps to Reproduce

1. Click on Configure Two-factor auth 
![image](https://user-images.githubusercontent.com/86705273/225622244-8ceb8d76-f8f7-4abb-b16b-9b47af211ea5.png)

2. Error message appears

### Expected Result

Login to organization after configuring two factor auth

### Actual Result

![image](https://user-images.githubusercontent.com/86705273/225621977-c642ee66-f317-4d7f-98d6-8f0165097090.png)

**Comment by masinette** [comment]
Hi @STC-Manas. Please write in to [Support](https://help.sentry.io/) so we can assist you further. We're happy to look into it for you!
