### ISSUE TITLE
Session replays not sending errors

### ISSUE THREAD

**Issue by Komal1223** [getsentry/sentry#45910]
### Environment

SaaS (https://sentry.io/)

### Version

7.43.0

### Link

https://default.sentry.io/replays

### Steps to Reproduce

1. Configured the set up for enabling session replay using next.js and react sdk version 7.43.0
`Sentry.init({
……
replaysSessionSampleRate: 0.1,
replaysOnErrorSampleRate: 1.0
integrations: [new Sentry.Replay()]`

2. No errors showing with Replay in Sentry

### Expected Result

Errors should show in replay

### Actual Result

No errors shows in replay

**Comment by billyvg** [comment]
@Komal1223 Is your issue that you are not receiving replays at all or that your replays that you have do not have errors in them? Can you link your org?

**Comment by Komal1223** [comment]
> @Komal1223 Is your issue that you are not receiving replays at all or that your replays that you have do not have errors in them? Can you link your org?

I have received 2 or 3 replays but I do not have errors in them.

**Comment by Komal1223** [comment]
@billyvg would `replaysSessionSampleRate: 0` and `replaysOnErrorSampleRate: 1.0` contain errors. Also, I don't have any clue why only 3 replays have been captured since the last 8 hours (8 hours ago I had set session replays config)

**Comment by billyvg** [comment]
Yes that would mean you would only capture replays that contain errors. `0.1` means it's only sampling 10% of the sessions, I don't know your traffic patterns so not sure why you only have 3. Again please link you org, or write in to support@sentry.io

**Comment by Komal1223** [comment]
> Yes that would mean you would only capture replays that contain errors. `0.1` means it's only sampling 10% of the sessions, I don't know your traffic patterns so not sure why you only have 3. Again please link you org, or write in to [support@sentry.io](mailto:support@sentry.io)

I have added in the description above

**Comment by billyvg** [comment]
@Komal1223 Thanks! I've confirmed that the replays there are session based, however there was a bug on our end that allowed these replays to go through. Your billing plan does not support Replay and you'll need to change your plan to one that supports Replay. Please contact support@sentry.io if you need additional assistance/clarification.

**Comment by Komal1223** [comment]
@billyvg aren't 500 replays free at the moment?

**Comment by billyvg** [comment]
@Komal1223 My mistake, it looks like some orgs on the older plan could be enrolled into Replay -- support will be able to straighten things out

**Comment by Komal1223** [comment]
@billyvg Thanks, it’s resolved by the Sentry’s support team
