### ISSUE TITLE
Performance issue not created when it (probably) should have been

### ISSUE THREAD

**Issue by fribergr** [getsentry/sentry#45924]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.2.0

### Steps to Reproduce

Using Laravel 10 on PHP 8.1.
Configured Sentry DSN and performance with SENTRY_TRACES_SAMPLE_RATE=1
Calling database using the QueryBuilder inside a foreach-loop. Resulted in 29 calls taking 206.71ms, but no issue was created regarding n+1 performance. The spans where grouped correctly in the performance view.

Export of that transaction has been attached to this ticket.
[issue.zip](https://github.com/getsentry/sentry/files/10992327/issue.zip)

### Expected Result

I would have expected an issue of category "performance" to be created as described here https://docs.sentry.io/product/issues/issue-details/performance-issues/

### Actual Result

No new issue were created when this occurred.

**Comment by mjq-sentry** [comment]
Hi @fribergr! Thanks for the report, and for attaching an example. I ran that transaction through the N+1 detector and it does indeed detect an N+1 on ``select `date` from `issues` where `system` = ? and DATE(date) <= ? and (`date_done` is null or `date_done` >= ?)``.

An N+1 has to be seen 3 times before it's reported - just to be totally sure, has that transaction been hit 3 or more times? 

The other possibility I can think of is something configuration related on self-hosted, but I'm less familiar with that (cc @udameli - do you have any ideas?)

**Comment by fribergr** [comment]
Any update on this?

**Comment by udameli** [comment]
Hi @fribergr,

Sorry for the late reply! We're currently changing how performance issues are created and saved. This introduced some complications for the self-hosted rollout so we temporary disabled performance issue creation. We're aiming to re-enable performance issues by early May. I'll ping you here once they're released. Apologies for the inconvenience!

**Comment by rzv-me** [comment]
Hi @udameli,

Any ETA on when performance issues will be enabled on self hosted instances? 

Thank you

**Comment by udameli** [comment]
Hi,

Apologies for the delay! Rolling out a new way of creation issues was more complicated than we anticipated. Good new though, Performance Issues are supported in the newest release https://github.com/getsentry/self-hosted/releases/tag/23.8.0. Thanks @hubertdeng123 👏
