### ISSUE TITLE
Global Selection Header locks not Persisting to the Project Details page

### ISSUE THREAD

**Issue by wmak** [getsentry/sentry#45921]
### Environment

SaaS (https://sentry.io/)

### Link

https://sentry.sentry.io/projects/sentry/?project=1

### Steps to Reproduce

1. From any page lock the Global Selection Header for any attribute (eg. time period)
2. Navigate to the projects page
3. Navigate into the Project Details

### Expected Result

The locked selection from step 1 persists even when navigating to the project details

### Actual Result

It does not persist

**Comment by hubertdeng123** [comment]
Ugh, `Team: Front End` is a label that isn't used anymore...going to backlog this until it's clear which team owns this as part of the managing teams changes project going on.

**Comment by ryan953** [comment]
Locking happens automatically now. Closing because this doesn't apply anymore.
