### ISSUE TITLE
🔕 Mute Alerts 🔕

### ISSUE THREAD

**Issue by scefali** [getsentry/sentry#45935]
**Background**

Alerts can be noisy and sometimes you just don't want to receive notifications for an alert someone set up. Today it’s not possible to turn off an alert just for yourself, instead you have to customize your personal notifications which is why a lot of folks turn off notifications entirely. 

**Solution**

V1 will include muting issue alerts forever ~~and for a period of time~~ for everyone or for an individual user. Access will be through the alert rule details page and a link in email footers.

V2 will add support for metric alerts and muting an alert ~~for everyone~~ for a period of time. Add access through Slack and MSTeams buttons.

[Product Spec](https://www.notion.so/sentry/Mute-Alerts-6c1ed3bc2e7946ce908d002f05b32412)
[Tech Spec](https://www.notion.so/sentry/Mute-Alerts-Tech-Spec-53a968fbb82b4312bdd4b48ad1b54353#a72e7a412b534789a9050815c2fd48fd)

```[tasklist]
### V1 Tasks
- [ ] https://github.com/getsentry/sentry/issues/46827
- [ ] https://github.com/getsentry/sentry/issues/46828
- [ ] https://github.com/getsentry/sentry/issues/47045
- [ ] https://github.com/getsentry/sentry/issues/46837
- [ ] https://github.com/getsentry/sentry/issues/47049
- [ ] https://github.com/getsentry/sentry/issues/46830
- [ ] https://github.com/getsentry/sentry/issues/46842
- [ ] https://github.com/getsentry/sentry/issues/46844
- [ ] https://github.com/getsentry/sentry/issues/46833
- [ ] https://github.com/getsentry/sentry/issues/47508
- [ ] #48650 
```

### V2 Tasks
- Check whether or not to send a metric alert based on `RuleSnooze`s
- Add link to metric alert email footer
- Implement UI for muting for a period of time (needs design)
- Add mute button to Slack issue alert notification (needs designs - one for DMs and one for channel msgs)
- Add mute button to MSTeams issue alert notification (needs designs - one for DMs and one for channel msgs)
- Add mute button to Slack metric alert notification (needs designs - does anyone ever get metric alert DMs?)
- Add mute button to MSTeams metric alert notification (needs designs - does anyone ever get metric alert DMs?)

**Comment by ceorourke** [comment]
After the table is created, #46828, #46830, and #46842 can be done in parallel.

**Comment by ceorourke** [comment]
It'd be nice to see on the all alerts page whether an alert is muted or not - needs design.

**Comment by kpujjigit** [comment]
Hi - 2 questions:

1. Is there a timeline on V2 tasks?
2. Why was muting for a period of time not implemented?

**Comment by kpujjigit** [comment]
Heya, any insight on my recent inquiry?

**Comment by rachrwang** [comment]
@kpujjigit - we don't have any timelines for V2 tasks as the team is currently prioritizing a different set of work. The muting for a specific period wasn't implemented since it wasn't high enough on our priority list/ we didn't determine it to be a strong enough use case to prioritize at this time
