### ISSUE TITLE
Not possible to create JIra issue from sentry when tempo account field is used

### ISSUE THREAD

**Issue by izenk** [getsentry/sentry#45931]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.2.0

### Steps to Reproduce

1. Setup Jira-server integration as described here https://docs.sentry.io/product/integrations/issue-tracking/jira/#manually
2. Manually create Jira issue from sentry
3. If Jira issue has required field (tempo account), error will appear when click "Create Issue" button

### Expected Result

Jira issue is created

### Actual Result

Error is displayed in UI
If I enter tempo account id (number), for example 69, then error is:
Error Communicating with Jira Server (HTTP 400): Account id 'null' is invalid

If I enter tempo account key (string), for example AP_DEV, then error is:
Error Communicating with Jira Server (HTTP 400): Account id 'AP_DEV' is invalid

**Comment by hubertdeng123** [comment]
Can you attach some screenshots so I can get more of an idea of what's going on? Seems like it's complaining that your account id is invalid, which makes sense for what you're trying to enter

**Comment by izenk** [comment]
@hubertdeng123 sure

First one is where Jira project string id is used: AP_DEV
<img width="976" alt="Screenshot 2023-03-17 at 13 03 03" src="https://user-images.githubusercontent.com/6417697/225875519-83d010d8-c3ed-422f-82a4-a4b8800cff92.png">

Second one is where numerical id is used: 69
<img width="950" alt="Screenshot 2023-03-17 at 13 06 54" src="https://user-images.githubusercontent.com/6417697/225875654-174e834a-0c24-479a-8921-156907b8a777.png">

Third one is screenshot from Jira, where you can see project string id and numerical id in browser address filed
![Uploading Screenshot 2023-03-17 at 13.12.41.png…]()

**Comment by ceorourke** [comment]
Hello, we don't support custom required fields in Jira, please see the docs: https://docs.sentry.io/product/integrations/issue-tracking/jira/#cant-create-issues-using-a-custom-required-field

**Comment by hubertdeng123** [comment]
Going to close this then. Thanks @ceorourke for chiming in

**Comment by izenk** [comment]
@ceorourke can you please explain a little bit more
I can see, that there is support for exact tempo account field [here](https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/jira_server/integration.py#L257)
