### ISSUE TITLE
Add to Dashboard from Discover has a blank title when a homepage query is saved

### ISSUE THREAD

**Issue by narsaynorath** [getsentry/sentry#45941]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Save a Discover query as your default
2. Refresh the page
3. Click "..."
4. Click "Add to Dashboard"
5. Select a Dashboard and click "Open in Widget Builder"
6. Click "Add Widget"

### Expected Result

The modal and widget builder should have a default title. If there isn't a title the form should have also errored.

### Actual Result

There's no title in the modal or the widget builder, and trying to save from the widget builder provides no feedback to the user that it was unsuccessful.

<img width="618" alt="Screenshot 2023-03-16 at 1 21 17 PM" src="https://user-images.githubusercontent.com/22846452/225701016-a1727488-c54d-47cd-b8c0-c5e7da3c1df2.png">

**Comment by ale-cota** [comment]
@narsaynorath I tried the exact steps and wasn't able to reproduce this. It seems to be working well and saving the widget with the title of the previously saved query.
