### ISSUE TITLE
Access Restriction to Environments

### ISSUE THREAD

**Issue by mikestrach** [getsentry/sentry#45978]
### Problem Statement

Our system is a monlithic system for a very regulated market, and hence a lot of snsitive information is passed back and forth. We can restrict users to only be able to see certain projects, but it'd be great if the same could be extended to environments, to ensure team members that shouldn't see the performance logs for a production environment cannot see them (e.g. a Grad or Junior developer that only needs and only should see local)

**Comment by Dhrumil-Sentry** [comment]
Hi @mikestrach Have you considered creating different projects for different environments?
