### ISSUE TITLE
Docker sunset of free Teams

### ISSUE THREAD

**Issue by DaspawnW** [getsentry/sentry#45979]
### Problem Statement

As you are maybe already aware [Docker will sunset free Teams](https://github.com/docker/hub-feedback/issues/2314). This change will lead to frozen public images if the owner doesn't apply to the OpenSource Program or buys the Team. (That's at least my interpretation, but as it's currently a manner of hours until this changes it's also not put into stones).

Is there any plan how Sentry will handle this? Alternatives could be for example github, google, quay or ecr.

Thank you in advance,
Best regards,
 Björn

**Comment by asottile-sentry** [comment]
re-routing to open source to decide on the self-hosted image.  ghcr is probably the easiest -- I don't own it though I just have an opinion

**Comment by chadwhitacre** [comment]
Their [docs](https://web.docker.com/rs/790-SSB-375/images/privatereposfaq.pdf) say:

> **How can I see if I’m affected?**
> Please consult the [Organizations page](https://hub.docker.com/orgs) of your Docker account; any affected organizations are labeled “Docker Free Team” in the “Subscription” column.

I don't see "Docker Free Team" there, so it looks like we pay for Docker and are in the clear here.

<img width="624" alt="👍" src="https://user-images.githubusercontent.com/134455/225947572-6aa1c77e-5f9c-4527-ace6-455e827ce57c.png">

**Comment by DaspawnW** [comment]
thanks @chadwhitacre  for the feedback :-)

**Comment by chadwhitacre** [comment]
Thanks for asking the question! I appreciate your vigilance, and it's good to have this documented publicly. :)
