### ISSUE TITLE
sentry.interfaces.Exception stacktrace.abs_path was truncated with 256

### ISSUE THREAD

**Issue by midstr** [getsentry/sentry#4598]
In the process.py:
```
  if frame['lineno'] is not None:
                    source = self.get_source(frame['abs_path'], release)
                    if source is None:
                        logger.debug('No source found for %s', frame['abs_path'])
                        continue
```

but the abs_path has been truncated whith 256 in the stacktrace.py:
```
kwargs = {
            'abs_path': trim(abs_path, 256),
            'filename': trim(filename, 256),
```

this causes the `get_source` failed, and my web server handle the request with "500 error".

e.g: 
...
       "abs_path":"http://i.meituan.com/firework/lq-push?need_login=0&activity_id=7324&ys=1&ys_id=363&trace_tag=%7B%22src_page%22%3A%22p_homepage%22%2C%22extra%22%3A%22%7B%5C%22activityid%5C%22%3A%5C%22363%5C%22%7D%22%2C%22tgt_page%22%3A%22p_activity%22%2C%22req_time%22%3..."
     ...

Is any suggestion to avoid the `get_source`

**Comment by mattrobenolt** [comment]
I suppose we should be able to detect that the string was truncated before attempting to resolve it. That should be simple to do.

**Comment by biggu0** [comment]
good job
