### ISSUE TITLE
Let Members Delete Events toggle not working

### ISSUE THREAD

**Issue by stellaatsentry** [getsentry/sentry#46030]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Go to Organization Settings > General Settings > Toggle off the "Let Members Delete Events" option.

### Expected Result

Users with the "Member" role should not be able to delete Issues.

### Actual Result

Users with the "Member" role are still able to delete Issues.

**Comment by cathteng** [comment]
hello! i have a fix for this here https://github.com/getsentry/sentry/pull/46089
