### ISSUE TITLE
Ability to require 2FA

### ISSUE THREAD

**Issue by thorerik** [getsentry/sentry#4603]
We have an on-peremise installation of Sentry, and I'd like to require 2FA on all users.

I can't see that there's an option for this in the web panel and can't say I spotted anything in the documentation either. 

What would be nice would be a similar approach to what Gitlab has, where you can require 2FA and also set a grace period so that when implementing it you can give a short period to allow users to get their 2fa poison of choice (eg. a ubi-key).

**Comment by mattrobenolt** [comment]
Yeah, this is definitely not able to be done yet and is on our radar for sure.

**Comment by akleiber** [comment]
Hello there. We love the ability to use 2FA. Making this a requirement for members of a team would improve security even more.

+1 for this request

**Comment by Skyx1** [comment]
Hi there, the ability to enforce 2FA is a Mandatory Feature for us.

+1 👍

**Comment by dcramer** [comment]
Due to the recent work on how "requires SSO" was resolved (enforcing you login via SSO per-org), this should be a lot easier now.

**Comment by chauffer** [comment]
👍

**Comment by ys** [comment]
@dcramer do you have any idea when that could be shipped?

**Comment by dcramer** [comment]
@ys  It's something that's not **too** hard, but it's also hard to prioritize given a lot of companies use an SSO service that already mandates 2FA (e.g. Google). I'm not sure if/when we'll prioritize it. I imagine at some point someone will just want to fix it with some spare time, but we still see it as a nice-to-have.

**Comment by billyvg** [comment]
@maheskett Is this live for users yet?

**Comment by maheskett** [comment]
Dang, yeah this has been live for a while.
Docs are here: https://docs.sentry.io/accounts/require-2fa/
