### ISSUE TITLE
When inviting a new or existing user to an Organization position isn't saved

### ISSUE THREAD

**Issue by thorerik** [getsentry/sentry#4605]
When you invite a new user to an org you get the option to set their permission level right away, this doesn't seem to work:

![image](https://d3vv6lp55qjaqc.cloudfront.net/items/3a1r0B3U0C1G3s0J0o22/Screen%20Recording%202016-11-27%20at%2010.00%20PM.gif)

**Comment by dcramer** [comment]
@benvinegar you added this feature didn't you? it looks like theres no tests, and its unclear whats wrong code-wise at a glance

**Comment by benvinegar** [comment]
There's at least [a few tests here](https://github.com/getsentry/sentry/blob/master/tests/sentry/web/frontend/test_create_organization_member.py#L119). I'll take a look.

**Comment by phyzical** [comment]
just confirming this as still an issue in the latest nightly of onpremise

**Comment by benvinegar** [comment]
@EvanPurkhiser Can you investigate?

**Comment by EvanPurkhiser** [comment]
@phyzical I can't seem to reproduce this. What exactly are you seeing? The interface has changed quite a bit since this original issue.


![Screen-Recording-2020-07-06-at-1](https://user-images.githubusercontent.com/1421724/86630610-e90f4580-bf81-11ea-8973-287c9d2cda5b.gif)

**Comment by phyzical** [comment]
Ah sorry i have miss interpreted the exact issue. @EvanPurkhiser and @benvinegar 

it is upon the user accepting it defaults back to lowest permission of member.

i will search the issue list again and create a new one if i don't find one 👍
