### ISSUE TITLE
Removing members from an org just throws a generic error

### ISSUE THREAD

**Issue by thorerik** [getsentry/sentry#4606]
When filing #4605 I came across the following issue on our self-hosted sentry instance:

![image](https://d3vv6lp55qjaqc.cloudfront.net/items/0g2O0S0i1G1H470d0o1h/Image%202016-11-27%20at%2010.10.25%20PM.png)
In the console the following is logged:
Blocked loading mixed active content "http://sentry.site.com/api/0/organizations/test-org/members/8/"[Learn More]

We're on Sentry 8.10 using the docker deployment method with the following options:
```
docker run -d --name sentry-site -e SENTRY_SECRET_KEY=<our secret> -e SENTRY_EMAIL_HOST=mail01.site.com -e SENTRY_EMAIL_PASSWORD=<longass password> -e SENTRY_EMAIL_USER=email@site.com -e SENTRY_EMAIL_PORT=587 -e SENTRY_EMAIL_USE_TLS=True -e SENTRY_SERVER_EMAIL=email@site.com -e SENTRY_USE_SSL=True --link sentry-redis:redis --link sentry-postgres:postgres -p 8099:9000 sentry:8.10```

In front we got nginx which terminated SSL

**Comment by dcramer** [comment]
You have something misconfigured. Take a look at the docs on how SSL settings work.

**Comment by thorerik** [comment]
@dcramer I might be blind but I can't see any mention of SSL in the documentation except for the NGINX frontend configuration here: https://docs.sentry.io/server/nginx/

I obviously forgot to add the crucial information of that we're setting the header X-Forwarded-Proto to https, outside of that I can't see what could be causing this behaviour.

Full nginx config:
```
upstream sentry.site.com {
    server 127.0.0.1:8099;
}
server {
  listen 443 ssl http2;
  server_name sentry.site.com;

  ssl_certificate         /etc/letsencrypt/live/sentry.site.com/fullchain.pem;
  ssl_certificate_key     /etc/letsencrypt/live/sentry.site.com/privkey.pem;

  ssl_trusted_certificate /etc/letsencrypt/live/sentry.site.com/chain.pem;
  ssl_session_cache shared:SSL:10m;
  ssl_dhparam /etc/ssl/dhparams.pem;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
  ssl_ecdh_curve secp384r1;
  ssl_session_tickets on;
  ssl_prefer_server_ciphers on;
  ssl_stapling on;
  ssl_stapling_verify on;

  access_log  /var/log/nginx/sentry.site.com.access.log;
  error_log   /var/log/nginx/sentry.site.com.error.log;

  client_max_body_size 10G;
  fastcgi_buffers 64 4K;

  include letsencrypt.conf;

  location / {
    proxy_pass http://sentry.site.com/;
    proxy_set_header Host $Host;
    proxy_set_header   X-Forwarded-Proto    $scheme;
    proxy_redirect off;

  }
}
```

**Comment by dcramer** [comment]
@thorerik its there somewhere, but tbh you're going to have to dig through it yourself. Side effect of free open source ;) Most importantly, we dont allow general Q&A/support on the issue trackers, which is why I aggro closed this: https://sentry.io/support/

**Comment by thorerik** [comment]
@dcramer I'd argue there's a bug here, maybe spesificly to the docker image.
https://docs.sentry.io/server/config/ mentioned:
```
system.url-prefix: 'https://sentry.example.com'
```
Which as far as I can tell is not possible to set without utilizing on-build, but considering that 
```
SENTRY_USE_SSL
```
is exposed, system.url-prefix should also be exposed and set without the use of on-build.

**Comment by dcramer** [comment]
@thorerik Docker should always be setup with a configuration file. It's complex infrastructure, and I have adamant views about the use of environment variables (or zero-knowledge) configuration. Either way, this isn't a bug, at best its poor docs.
