### ISSUE TITLE
Error while installing sentry via python

### ISSUE THREAD

**Issue by badr-badri** [getsentry/sentry#4607]
Hello,
I get an error about at the end the sentry installation while i use python.  The command that i use is "pip install -U sentry" as it's indicated on the official documentation.
The error is:

-----
Running setup.py install for libsourcemap
    Running command /sentry-1/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-GORFB8/libsourcemap/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lcPRsd-record/install-record.txt --single-version-externally-managed --compile --install-headers /sentry-1/include/site/python2.7
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/libsourcemap
    copying libsourcemap/__init__.py -> build/lib.linux-x86_64-2.7/libsourcemap
    copying libsourcemap/_compat.py -> build/lib.linux-x86_64-2.7/libsourcemap
    copying libsourcemap/_sourcemapnative.py -> build/lib.linux-x86_64-2.7/libsourcemap
    copying libsourcemap/exceptions.py -> build/lib.linux-x86_64-2.7/libsourcemap
    copying libsourcemap/highlevel.py -> build/lib.linux-x86_64-2.7/libsourcemap
    error: [Errno 2] No such file or directory
    Complete output from command /sentry-1/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-GORFB8/libsourcemap/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lcPRsd-record/install-record.txt --single-version-externally-managed --compile --install-headers /sentry-1/include/site/python2.7:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/libsourcemap

copying libsourcemap/__init__.py -> build/lib.linux-x86_64-2.7/libsourcemap

copying libsourcemap/_compat.py -> build/lib.linux-x86_64-2.7/libsourcemap

copying libsourcemap/_sourcemapnative.py -> build/lib.linux-x86_64-2.7/libsourcemap

copying libsourcemap/exceptions.py -> build/lib.linux-x86_64-2.7/libsourcemap

copying libsourcemap/highlevel.py -> build/lib.linux-x86_64-2.7/libsourcemap
error: [Errno 2] No such file or directory

----------------------------------------
Cleaning up...
Command /sentry-1/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-GORFB8/libsourcemap/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lcPRsd-record/install-record.txt --single-version-externally-managed --compile --install-headers /sentry-1/include/site/python2.7 failed with error code 1 in /tmp/pip-build-GORFB8/libsourcemap
Exception information:
Traceback (most recent call last):
  File "/sentry-1/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/sentry-1/local/lib/python2.7/site-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/sentry-1/local/lib/python2.7/site-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/sentry-1/local/lib/python2.7/site-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/sentry-1/local/lib/python2.7/site-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /sentry-1/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-GORFB8/libsourcemap/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-lcPRsd-record/install-record.txt --single-version-externally-managed --compile --install-headers /sentry-1/include/site/python2.7 failed with error code 1 in /tmp/pip-build-GORFB8/libsourcemap
-----

OS: Debian jessie 8.6

**Comment by mattrobenolt** [comment]
You need `pip` 8.1 or newer.

**Comment by ngocson2vn** [comment]
I have the same problem and upgrade pip resolved it.
Thank you so much!

**Comment by Abhishek103** [comment]
I am using PIP 9.1 but still getting the same error

**Comment by mattrobenolt** [comment]
Then you must be on some platform that we don't support and we don't compile a wheel for.

**Comment by Abhishek103** [comment]
I am using win10 Pro

**Comment by mattrobenolt** [comment]
As our documentation says, we don't support Windows. https://docs.sentry.io/server/installation/python/#dependencies

**Comment by Abhishek103** [comment]
Sorry for asking such questions, but is there is a way through which I can install sentry server on windows ?

**Comment by mattrobenolt** [comment]
I've locked this thread since the original issue has been answered and this is not a support forum for general advice about running Sentry. We have public documentation which needs to be read.
