### ISSUE TITLE
Users "Page Not Found"

### ISSUE THREAD

**Issue by stevendluke** [getsentry/sentry#4609]
On the sentry.io issue page, when I click on the user number (which should bring me to a page that has a list of users affected by the issue), I get a "Page Not Found" message.

**Comment by mattrobenolt** [comment]
Can you provide a more concrete URL?

**Comment by stevendluke** [comment]
https://sentry.io/copy-hackers/airstory/issues/186211894/users/

**Comment by mattrobenolt** [comment]
doh, you're right. Something is wrong here. Thanks for the heads up!

**Comment by stevendluke** [comment]
Np!

**Comment by mattrobenolt** [comment]
@benvinegar It seems that we're definitely missing a route for this url, but it also seems that we're missing a view to go with it. At least that I can find. I don't remember if this should actually be linking somewhere or if something has gotten lost.

**Comment by mattrobenolt** [comment]
Seems behavior changed here which broke the link: https://github.com/getsentry/sentry/pull/4589

And I don't really have enough context to determine what the behavior is intended to be. but the route should be `/tag/user/`, not `/users/`, but it was changed explicitly, so unclear why to me.

**Comment by dcramer** [comment]
This was a bug that slipped through
