### ISSUE TITLE
[Replays] Add conditions to filter out replays

### ISSUE THREAD

**Issue by ymatusevich** [getsentry/sentry#46115]
### Problem Statement

We have integration with an availability monitoring tool called pingdom that logs in into our website. Sentry captures a lot replays from such health check users.

<img width="1174" alt="Screenshot 2023-03-21 at 15 40 22" src="https://user-images.githubusercontent.com/9289300/226642785-4d6d665b-c906-4edc-9617-fafe26aedbf2.png">

### Solution Brainstorm

I'd appreciate if you implement any of the scenarios bellow:
1. filter out replays from a specific users/usernames/user.emails
2. add web hook `beforeSendReplay` similar to `beforeSendTransaction` so we can apply custom rules
3. filter out replays shorter than N seconds.
4. move delete button from view replay page to index page so it would be easier to bulk delete replays.

**Comment by ryan953** [comment]
@ymatusevich one quick thing you might be able to do to address point 1 is adjust the sampling rate if you see a user/email that you don't want to capture. 

```
const isBlockedUser = (user) => user.name === 'pingdom_test';

const user = { name: 'pingdom_test' };

Sentry.init({
  dsn: "https://examplePublicKey@o0.ingest.sentry.io/0",

  replaysSessionSampleRate: isBlockedUser(user) ? 0.0 : 0.1,
  replaysOnErrorSampleRate: isBlockedUser(user) ? 0.0 : 1.0,

  integrations: [new Sentry.Replay()],
});
Sentry.setUser(user);
```

It's a contrived example, hopefully your `Sentry.init()` & `Sentry.setUser()` calls both have access to the user.

**Comment by ryan953** [comment]
You can also follow https://github.com/getsentry/sentry-javascript/issues/7540 which seems related.
