### ISSUE TITLE
CODEOWNERS rules with double star (`/**/`) match everything, even if there is suffix after it.

### ISSUE THREAD

**Issue by orsinium** [getsentry/sentry#46113]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

We have noticed that some of the issues are auto assigned to the last team in the CODEOWNERS file that has `**` glob in the rule pattern, despite the path not matching the part of the rule after the `/**/` part. I've tracked the issue to a specific function in the Sentry server source code:

```
from sentry.utils.codeowners import *
codeowners_match('project/smth/smth/message.py', '/project/**/no_matter/')
# True
```

### Expected Result

False

### Actual Result

True

**Comment by jangjodi** [comment]
Thanks @orsinium for bringing this to our attention! We are currently working on it [here](https://github.com/getsentry/relay/pull/1952)

**Comment by orsinium** [comment]
https://github.com/getsentry/relay/pull/1952 is merged, and I hope it will help. We'll double-check that it works when it hits the prod. For now, I'll close the issue. Thank you for solving the problem :)
