### ISSUE TITLE
Organization avatar

### ISSUE THREAD

**Issue by stayallive** [getsentry/sentry#4613]
I would like to request the ability to upload a team avatar and/or set a Gravatar e-mail for the team (like Github does).

**Comment by mattrobenolt** [comment]
I swear I thought we had an open ticket for this already. Assuming you mean organization avatar.

I'm pretty confident this was on our radar. /cc @ckj @macqueen

**Comment by stayallive** [comment]
I figured you guys did but could not find anything, and yes I meant a org avatar 👍

**Comment by jessedobbelaere** [comment]
Would like that too! Right now I have a pink sentry org avatar :P

**Comment by lenovouser** [comment]
Yep, this would be nice to have 👍

**Comment by ngubin** [comment]
@lenovouser, there is a table for avatars in the database. Maybe in the work already...

**Comment by Belax8** [comment]
It looks like it's merged in, but I'm not sure where you guys are implementing it. https://github.com/getsentry/sentry/pull/4818

**Comment by dcramer** [comment]
Likely in 9.0

**Comment by khushkaran** [comment]
Any ETA for 9.0?

**Comment by billyvg** [comment]
Added in #8360
