### ISSUE TITLE
Session Replay: Performance Issues and Replays Integration

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#46162]
**Opportunity**

Today, we have [7 performance issues](https://docs.sentry.io/product/issues/issue-details/performance-issues/) as documented in our product docs. There's an opportunity for us to surface Replay in the debugging context for each performance issue, so our customers can assess the user impact and severity level of a perf issue. In the same way that we surface Replay on error issues. 

There may be some performance issues that already meet some of the following ACs listed because of existing logic in place.

**Acceptance Criteria for the Performance Issue Details page**

- See Replay Preview/Thumbnail under the "Breadcrumbs" heading in Issue Details when available
--> When a user clicks the Replay Preview/Thumbnail to go to the Replay Details page, it should bring you to the timestamp of the specific transaction event you were viewing on the Issue Details page
- "Replays" tab in Issue Details showcasing all replays associated with any transaction events belonging to the performance issue
- "Replay" column under "All Events" tab

**Note:** It likely requires significantly more work to integrate Replay with backend performance issues, when compared to frontend.

**Comment by bruno-garcia** [comment]
Relates to: https://github.com/getsentry/sentry/issues/45664

**Comment by Jesse-Box** [comment]
@jas-kas @ryan953 

Designs here for the first acceptance criteria
https://www.figma.com/file/VYQS8oJ7wMh3wrfaa11DpL/Specs%3A-Replays-in-Issues-v4?type=design&node-id=1%3A4649&mode=design&t=Ryw7fj0nAvYhe42l-1
