### ISSUE TITLE
Call code in post processing

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry#46175]
Identify the proper location to call the code of #44342.

### Option 1: Event Manager
The `event_manager` similar to where we call `detect_performance_problems`. 

https://github.com/getsentry/sentry/blob/fc1d72ee868af1103f2751e2fa0f1928d3d2ba4c/src/sentry/event_manager.py#L2491

### Option 2:  Issue platform detectors

The purpose of [detectors](https://github.com/getsentry/sentry/tree/fc1d72ee868af1103f2751e2fa0f1928d3d2ba4c/src/sentry/utils/performance_issues/detectors) is to find problems in the customer's dataset, such as N+1 queries, file I/O on the main thread, slow DB query, etc. As #44342 aims to find problems of the SDKs, detectors don't seem like the correct place.

### Option 3: Post Processing
[post_processing](https://github.com/getsentry/sentry/blob/e39eeadd8b67c4c2c11f02d6ce8f2a2ef99bc018/src/sentry/tasks/post_process.py#L1): does some other non-critical event processing. We could add it to the post processing pipeline: https://github.com/getsentry/sentry/blob/fc1d72ee868af1103f2751e2fa0f1928d3d2ba4c/src/sentry/tasks/post_process.py#L976-L992

**Comment by jjbayer** [comment]
I vote for Option 3, post-processing. This is where we can run non-critical handlers for every event after it was stored. We can wrap it in metrics and `safe_execute` like we do here:

https://github.com/getsentry/sentry/blob/06a66941590c4a810fdb49bb1363a9d7ec636ed6/src/sentry/tasks/post_process.py#L941-L943

We should then monitor how much time the crash monitoring usually takes. If necessary, we can spawn a separate Celery task for it, but I would not start with that as long as it is in the range of milliseconds.
