### ISSUE TITLE
Offline sourcemaps not used

### ISSUE THREAD

**Issue by psychoo118** [getsentry/sentry#4622]
Hello!

I'm running an on-premise sentry server in docker container (Sentry 8.10.0). We have a webapp built in webpack which in the end has a bundle-[hash].min.js and a bundle-[hash].min.js.map file. I created a new release with sentry-cli:

`sentry-cli releases new a3494cd0a6043b80388e4521165b77acd0bdb5e5`

and then uploaded assets:

`sentry-cli releases files a3494cd0a6043b80388e4521165b77acd0bdb5e5 upload-sourcemaps dist/`

It uploads 2 files:
- ~/assets/bundle-05ed754f62e885e7b062.min.js
- ~/assets/bundle-05ed754f62e885e7b062.min.js.map

When deploying the project only the JS file is uploaded since we can not publish the sourcemap. JS file is publicly accessible at https://example.com/assets/bundle-05ed754f62e885e7b062.min.js
On the web-interface the new release appears and artifacts are visible too.

![screen shot 2016-11-29 at 18 24 08](https://cloud.githubusercontent.com/assets/6742328/20720846/11b0458a-b661-11e6-8b96-d85250a6d59a.png)

In the HTML raven is initialized like this:

`Raven.config('https://571be8ea728c416a955775e5bdb90545@sentry.****.hu/2', { release: "a3494cd0a6043b80388e4521165b77acd0bdb5e5", environment: "staging" } ).install()`

After receiving an error Sentry displays stack trace like this:
![screen shot 2016-11-29 at 18 32 36](https://cloud.githubusercontent.com/assets/6742328/20721208/56de876a-b662-11e6-9e35-e2e370b31371.png)

And for some reason it wants to download the sourcemap:
![screen shot 2016-11-29 at 18 33 15](https://cloud.githubusercontent.com/assets/6742328/20721245/77f17a2a-b662-11e6-92c3-4a0a2a3e1932.png)

Sourcemap is referenced in JS code like this:
`//# sourceMappingURL=bundle-05ed754f62e885e7b062.min.js.map`

When source map was uploaded previously(for testing) Sentry was able to show the sourcemapped stack trace.(probably it downloaded it but it means sourcemapping works)

I even tried to upload sourcemaps with url-prefixes like this:
![screen shot 2016-11-29 at 18 42 09](https://cloud.githubusercontent.com/assets/6742328/20721574/96114732-b663-11e6-9e80-5728af26b8aa.png)

Results were same, no sourcemapped stack traces :(
`$ sentry-cli releases list` gives me:
![screen shot 2016-11-29 at 18 43 14](https://cloud.githubusercontent.com/assets/6742328/20721703/148bfa4e-b664-11e6-8fcd-893edc8fe18c.png)

Where I don't know what "[unreleased]" means.. Maybe that's the problem

Could you please help me find out the solution?
Thanks in advance!

**Comment by mattrobenolt** [comment]
Hey @psychoo118, unfortunately this is not a place for us to provide general support.

Do you mind reposting over on our community forums? https://forum.sentry.io/c/on-premise
