### ISSUE TITLE
Add support for secure (SSL/TLS) Redis

### ISSUE THREAD

**Issue by radicaled42** [getsentry/sentry#46228]
### Problem Statement

I have created a secure Redis cluster. If I try to access from a VM there is no problem, I can connect in a secure mode.
But when I try to start sentry web (`sentry run web`) it hungs up without messages.

This is the result I get when I try to run it:
```
# sentry run web
/usr/local/lib/python3.8/site-packages/sentry/runner/initializer.py:243: DeprecationWarning: `structlog.threadlocal` is deprecated, please use `structlog.contextvars` instead.
  WrappedDictClass = structlog.threadlocal.wrap_dict(dict)
22:44:18 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
22:44:21 [INFO] sentry.plugins.github: apps-not-configured
```

I've seen similar issues:
- https://github.com/getsentry/self-hosted/issues/1437
- https://github.com/getsentry/sentry/issues/24238

### Solution Brainstorm

Quoting (https://github.com/getsentry/sentry/issues/24238)

> The way I would do it is by adding ssl as an acceptable option in https://github.com/getsentry/sentry/blob/master/docker/sentry.conf.py#L98

**Comment by hubertdeng123** [comment]
Can someone from @getsentry/ingest chime in? Seems like in the past relay does not support SSL connections, is that still the case?

**Comment by hubertdeng123** [comment]
Seeing this comment from @jan-auer, so Relay 😁
https://github.com/getsentry/sentry/issues/24238#issuecomment-801910836

Also seeing this PR that recently went in to enable TLS for Redis in Relay so maybe this is possible now?
https://github.com/getsentry/relay/pull/1772

**Comment by olksdr** [comment]
Hey @hubertdeng123, 
Relay should support TLS now.  The PR which you mentioned enables it and we do build the docker images with SSL feature enabled as well.  
Let's the ingest team know if there are any problems with configuring it or you see some strange bugs and errors.

**Comment by radicaled42** [comment]
Ok, so as far as I understand with relay release 23.1.1 TLS has been enable (https://github.com/getsentry/relay/releases/tag/23.1.1).

What about sentry?
As far as I understand/look into, the config.yml should be something like this?
```
 redis.clusters:
   default:
     hosts:
       0:
         host: XXXXXX
         port: 6379
         password: XXXXXXX
         ssl: True
```
I tested it with the release 22.12.0 and it works. If I try to use the same as relay, I get a 504 Bad Gateway from relay.

**Comment by hubertdeng123** [comment]
> Ok, so as far as I understand with relay release 23.1.1 TLS has been enable for redis

Yep, it looks like the changes to enable SSL for Relay went in with 23.1.1.
> As far as I understand/look into, the config.yml should be something like this?

You can modify the config however you'd like, yes. 

Are you using [self-hosted Sentry](https://github.com/getsentry/self-hosted) here? Keep us posted on how the setup goes.

**Comment by radicaled42** [comment]
Well, I'm not using exactly the self hosted version. I'm using the docker images and built it around it.
But yes, Relay is working correctly on version 23.1.1 and Sentry works correctly with version 22.12.0 at least. I'm having an upstream error (504 Bad Gateway) if I use the Sentry 23.1.1, but I think its my problem.
I will close this issue.

Although, I have also open an issue with Snuba, because I'm not able to connect to a secure Redis using TLS.
https://github.com/getsentry/snuba/issues/3986

Thanks
