### ISSUE TITLE
Filter which errors cause a Replay to be created

### ISSUE THREAD

**Issue by ianfairbairn** [getsentry/sentry#46236]
### Problem Statement

Although I may want to capture all errors in Sentry I don't want to have every error create a Replay.  I'd like to have control over which errors create or don't create a Replay and currently there is no way to do this.

### Solution Brainstorm

I'd suggest either:

1) having a separate ignoreErrors and ignoreReplayErrors configuration item 
2) having a separate beforeSend() hook for errors and beforeSendReplay() for Replays in which I can decide whether to create the Replay or not

Thank you, I look forward to using this shiny new feature.

**Comment by bruno-garcia** [comment]
Thanks for the feedback. Currently there's no way to control it that way. Other than with a sample rate. We'll consider additional quota control mechanisms in the future

**Comment by billyvg** [comment]
@ianfairbairn We're going to be tracking this feature in https://github.com/getsentry/sentry-javascript/issues/7540 -- please subscribe there for updates, thanks!
