### ISSUE TITLE
SourceMap Uploaded artifacts do not include entry: ~/inject_content.js

### ISSUE THREAD

**Issue by Turbozanik** [getsentry/sentry#46274]
### Environment

SaaS (https://sentry.io/)

### Link

https://expanice.sentry.io/settings/organization/expanice

### Steps to Reproduce

1. sentry-cli releases files "$VERSION" upload-sourcemaps /path/to/sourcemaps
2. sentry-cli sourcemaps explain --org expanice --project ens_price_calculator dd39ba56f79f40a48daaa2aaed360fc0

### Expected Result

I was expecting it to explain the error on base of the sourcemap I have provided.

### Actual Result

✔ Fetched data for event: dd39ba56f79f40a48daaa2aaed360fc0
✔ Event has release name: ens_price_calculator@1.0.0+1
✔ Event has a valid exception present
✔ Event has a valid stacktrace present
✖ Uploaded artifacts do not include entry: ~/inject_content.js

PS: This is a flutter project built for web. I can't find any mentions of `inject_content.js` neither in main.dart.js.map nor in the whole build folder. Such string is just not there(or it is hiding really well).
So it is either me building the map in the wrong way. Or sentry expecting something that I am not aware of.

Can you please help me resolving this?

**Comment by masinette** [comment]
Hi @Turbozanik. Thanks for reaching out. Can you write in to [Support](https://help.sentry.io/) so we can look into this for you?

**Comment by Turbozanik** [comment]
> Hi @Turbozanik. Thanks for reaching out. Can you write in to [Support](https://help.sentry.io/) so we can look into this for you?

Done, thank you.

**Comment by Turbozanik** [comment]
Add a -dist parameter to the source map uploading command
