### ISSUE TITLE
[Profiling] connResertException 

### ISSUE THREAD

**Issue by schankam** [getsentry/sentry#46307]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

The moment we're adding the profiling feature on our Node.JS app, we're starting to get this error on Sentry:

![Screenshot 2023-03-23 at 10 33 51](https://user-images.githubusercontent.com/3543017/227477036-1b661775-4283-4fe8-a24e-bea0d256fe2f.png)

Our configuration:

Node.JS 18, running inside docker on Google Cloud Run.

 "@sentry/node": "^7.44.1"
 "@sentry/profiling-node": "^0.2.2"
 "@sentry/tracing": "^7.44.1"
 "@sentry/types": "^7.44.1"
 
 We did not investigate due to lack of time, but if I disable the sentry profiling integration the error stops.
 
 Our initialization:
 
 ```
   Sentry.init({
    dsn: process.env.SENTRY_DSN,
    environment: process.env.NODE_ENV ? process.env.NODE_ENV : null,
    attachStacktrace: true,
    tracesSampler,
    beforeSend
    // profilesSampleRate: 1.0,
    // integrations: [new ProfilingIntegration()]
  });
```

### Expected Result

No errors to happen

### Actual Result

![Screenshot 2023-03-23 at 10 33 51](https://user-images.githubusercontent.com/3543017/227477470-fa588717-1852-4bd4-95d5-622a9024ac25.png)

**Comment by hubertdeng123** [comment]
did not mean to route ops here, was a misclick

**Comment by JonasBa** [comment]
@schankam I'm moving the issue over to our profiling-node repository - see https://github.com/getsentry/profiling-node/issues/120

@hubertdeng123 thanks for tagging us!
