### ISSUE TITLE
Impossible to create second jira_server integration 

### ISSUE THREAD

**Issue by izenk** [getsentry/sentry#46318]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.2.0 8cfa6b9

### Steps to Reproduce

1. Create multiple orgs
2. Setup jira_server integration for one of them
3. Try to setup jira_server integration for second org

### Expected Result

Jira integration can be set up for all sentry orgs 

### Actual Result
Im not sure, which side problem is.
From sentry docs, during integration setup I should create Application Link in Jira.
We have multiple orgs in our sentry, so I need to create multiple App Links in Jira - and this is impossible, because Sentry has one link https://our_sentry_domain/extensions/jira-server/setup/ for integration. So when I try to create Application Link in Jira, it says:
```
There is already one Application Link with URL 'https://our_sentry_domain/extensions/jira-server/setup'.
```

If I try to use one Application Link in Jira for multiple orgs in Sentry, I get error:
```
IntegrityError
UniqueViolation('duplicate key value violates unique constraint "sentry_identity_idp_id_external_id_a24ac9c1_uniq"\nDETAIL:  Key (idp_id, external_id)=(1, jira.test.com:org2) already exists.\n')
SQL: INSERT INTO "sentry_identity" ("idp_id", "user_id", "external_id", "data", "status", "scopes", "date_verified", "date_added") VALUES (%s, %s, %s, %s, %s, %s, %s, %s) RETURNING "sentry_identity"."id"
```

**Comment by brianthi** [comment]
Hi @izenk, thanks for reporting this issue.  We're aware of the limitation, and currently we only support 1:1 mapping from a Sentry org to a Jira service.  I will link this request to our internal ticket for tracking purposes, but for now will close this issue as it is not work we intend to take on.

**Comment by izenk** [comment]
@brianthi FYI, I found a workaround and now it seems to work fine.
Workaround is done on Jira side. Despite jira require uniq app link when during app creation, you can set any custom link on first step and then change it when configuring "Incoming auth".

On this step
<img width="970" alt="Screenshot 2023-03-28 at 23 01 44" src="https://user-images.githubusercontent.com/6417697/228353720-8b5dd510-004e-4f42-b5e5-6b750435f451.png">
you can enter any link, what allows you to create second/third/etc app in jira and then
<img width="785" alt="Screenshot 2023-03-28 at 23 03 23" src="https://user-images.githubusercontent.com/6417697/228354155-71182afb-559c-452e-a0e2-83e0ac13004d.png">
you can set callback url the same as in other sentry-jira apps.
Now you can have multiple sentry orgs linked to one jira server.
