### ISSUE TITLE
There was an error loading data Error

### ISSUE THREAD

**Issue by badr-badri** [getsentry/sentry#4632]
Hello,

I'm getting this error in Sentry dashbord :
"There was an error loading data"
When i click in the button "retry" I get this logs:

Dec 02 19:34:27 SENTRY sentry[11039]: Traceback (most recent call last):
Dec 02 19:34:27 SENTRY sentry[11039]: File "/var/lib/sentry/local/lib/python2.7/site-packages/sentry/api/base.py", line 86, in handle_exception
Dec 02 19:34:27 SENTRY sentry[11039]: return super(Endpoint, self).handle_exception(exc)
Dec 02 19:34:27 SENTRY sentry[11039]: File "/var/lib/sentry/local/lib/python2.7/site-packages/sentry/api/base.py", line 176, in dispatch
Dec 02 19:34:27 SENTRY sentry[11039]: response = handler(request, *args, **kwargs)
Dec 02 19:34:27 SENTRY sentry[11039]: File "/var/lib/sentry/local/lib/python2.7/site-packages/sentry/api/endpoints/project_stats.py", line 68, in get
Dec 02 19:34:27 SENTRY sentry[11039]: **self._parse_args(request)
Dec 02 19:34:27 SENTRY sentry[11039]: File "/var/lib/sentry/local/lib/python2.7/site-packages/sentry/api/base.py", line 238, in _parse_args
Dec 02 19:34:27 SENTRY sentry[11039]: assert start <= end, 'start must be before or equal to end'
Dec 02 19:34:27 SENTRY sentry[11039]: AssertionError: start must be before or equal to end

OS = Debian Jessie
Sentry version  =  8.10.0
Redis version = 3.2.5
Python installation method

**Comment by dcramer** [comment]
Sounds like something is misvonfigured. Please give the API request that generated this error.

**Comment by badr-badri** [comment]
I just click on the button "retry" on the main page. I do not make any API request

**Comment by dcramer** [comment]
@badr-badri that is making an API request -- I will need that request to help. You can find it in the logs or in the browser's console. Without more information I'll simply have to close this ticket.

**Comment by badr-badri** [comment]
This is the API request that generates the error:
http://10.0.0.12:9000/api/0/organizations/sentry/stats/?since=1480924290.731&stat=generated&group=project
When I open this URL in my browser I get this error:
{"detail": "Internal Error", "errorId": "1bd6dd61d3b84f23a9b80a4cd8d9851e"}
In the logs I get the same messages that the ones that I put when I opened this isse.

**Comment by mattrobenolt** [comment]
I can only guess clock skew. Your browser's clock is skewed ahead of your server's clock by too much. The `since` would be taken from your browser, and the server would be implying "now" for `end`. The error is stating that `start` is actually after `end`. So the only explanation I can think of is clock skew. Either your local clock is too far off, or your server is too far off.

**Comment by badr-badri** [comment]
you guessed well, it was due to Sentry server clock.
Thanks for your support :)

**Comment by TL-KenYu** [comment]
Hi, I am having the same issue. How did you fix this?
