### ISSUE TITLE
Link to URLs from extra context

### ISSUE THREAD

**Issue by beheh** [getsentry/sentry#4636]
My organisation attaches various tracing URLs to exceptions in a Python (Django) application, linking to Cloudwatch logs or corresponding admin pages. We're using hosted Sentry.

We've accidentally been using the user context so far for these, which meant the links appeared in the "User" section on the exception page and had the small, clickable "external link" icon.

I've now moved the attached URLs to the extra context, and while the URLs are now shown in the "Additional Data" section, they no longer feature the clickable icon directly opening that link.
Additionally, the user context has been stripping the python unicode "u" prefix and the surrounding quotes, which the extra context does not.

I assume it's a bug that the extra context is behaving differently here.

**Comment by markstory** [comment]
I took a look into this and this functionality is in sentry.io, and will be in the next on-premise release if it is not already there too.

**Comment by beheh** [comment]
Does that mean this should be fixed as of right now on sentry.io, or only in an upcoming deploy there? I'm still seeing a scrollable text field and no clickable external link icon there:

![link](https://user-images.githubusercontent.com/929769/49896018-66c8a900-fe52-11e8-8ce4-97b3d7e39853.png)

**Comment by markstory** [comment]
Which SDK are you using to record that information? I tried reproducing this problem with the PHP SDK and the following extra context:

```php
$sentry->extra_context([
        'list' => ['fish', 'in', 'a', 'bowl'],
        'nested_url' => ['nope', 'http://example.org/nested'],
        'nowrap' => 'https://example.org/top',
);
```

Results in the following on my issue

<img width="672" alt="screen shot 2018-12-12 at 9 42 06 am" src="https://user-images.githubusercontent.com/24086/49901951-770f6280-fe17-11e8-9c1d-c984e30881b5.png">

which contains working external link icons. I'll see if the presence of a querystring or document fragment breaks our autolinking.

**Comment by markstory** [comment]
Basic query strings and fragments also work for me:

<img width="664" alt="screen shot 2018-12-12 at 2 12 19 pm" src="https://user-images.githubusercontent.com/24086/49902175-0caaf200-fe18-11e8-8aad-7339ff2a3c37.png">

**Comment by markstory** [comment]
It could be how the raven library converts data before sending it to sentry. I will see if I can reproduce missing links from a python script.

**Comment by markstory** [comment]
I was able to reproduce this problem with the old python SDK. That SDK casts string data into their repr value. However, the new sentry_sdk library does not do this and allows autolinks to be created. You should consider upgrading if autolinking in extra_context is important to you.

**Comment by beheh** [comment]
OK, great! We're in the process of updating it. Thanks for the help.
