### ISSUE TITLE
Allow custom project icons, so they're unrelated to the main platform

### ISSUE THREAD

**Issue by igorsantos07** [getsentry/sentry#46364]
### Problem Statement

As you might be aware, many systems are not frontend only or backend-only. Thus, if you have many subsystems on Sentry, the only way to get matching icons is to have two different "projects" for the same subsystem you manage. It's much easier to have both sides (PHP and JS, for instance) reporting on the same project, and I guess this is even useful if you are able to link two issues from back/frontend together (wasn't able yet lol)

Related to what's seen at #46311

### Solution Brainstorm

Allow us to upload custom project icons, or simply set a letter-based icon (ugly, but better than the currently confusing reports where you see a PHP icon under a JS report lol).

**Comment by scttcper** [comment]
@igorsantos07 i'd recommend using two projects if you can, even if the live within the same repo. There's a few things we do based on the project chosen where choosing php and submitting js events or picking js and submitting php events might not give you the best experience.

We're unlikely to let people submit their own icons for the platform, but there is a "other" platform.

**Comment by dakujem** [comment]
It is not practical to divide a single project into multiple projects on Sentry.

- A lead developer needs to be able to view sentry errors (and performance) across the whole project, regardless of the platform.
- It does also happen that someone on the backend team causes a crash on frontend client app by sendind in the wrong data, and so _should_ also track the errors originating in the client apps

It is not possible to monitor multiple Sentry projects on Team plan. This might be the intention, I understand, but then it makes no sense to divide projects at all for smaller teams.

**Comment by igorsantos07** [comment]
I underline @dakujem's comment, specially the part where we cannot check multiple projects' issues on the same screen if you're on the lower plans. While it kinda makes sense, it completely kills the suggestion given.

One other scenario where splitting projects is troublesome: supposedly, it should be possible to link two issue reports through some hidden information (which I was not yet able to figure out how and isn't working automagically as I would expect it to, at least not in `fetch()` calls). Thus, a report coming from the backend would be linked to the related issue which happened in the frontend. Is that supposed to work across projects too?
