### ISSUE TITLE
Devise a way to fetch an estimated time of the session replay.

### ISSUE THREAD

**Issue by jdamon96** [getsentry/sentry#46408]
### Problem Statement

I want to be able to query the session time of sessions captured via Sentry Replay. I reached out to support and they instructed me that "Currently being able to track session time via session replays is not a current functionality of this feature." but I should ask here.

**Comment by JoshFerge** [comment]
@jdamon96 what exactly are you trying to do? search for replays longer than X? or look at a distribution of session times?

**Comment by jdamon96** [comment]
distribution of session times

Ideal behavior would be to be able to query session times recorded w Sentry Replay based on the value of a URL parameter

I’d be able to set this up on my own if the Replays have associated URL data and total session time

**Comment by JoshFerge** [comment]
once we have a materialized view, it may be possible to put replays in our "discover" product. much to think about there! cc @bruno-garcia @jas-kas

**Comment by cmanallen** [comment]
We do not have the capability of expressing this information in a performant way (currently) and its not within our product priorities to add it, at the moment.  Should we re-assess this issue a materialized view will be required.
