### ISSUE TITLE
Django initial setup error: "event submission rejected with_reason: ProjectState"

### ISSUE THREAD

**Issue by mynameistechno** [getsentry/sentry#46405]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.11.0 60999b0

### Steps to Reproduce

1. Follow the django installation instructions that is served by our self-hosted instance at /getting-started/python-django/
2. I created a sample error in the django app, i.e. divide by zero
3. Turned on Debug on client (django app)
4. Visit the /sentry-debug/ page on django app to trigger the unhandled error

### Expected Result

The error is logged and visible in Sentry

### Actual Result

Nothing shows up in Sentry, but there are logs on the instance and in the client (once Debug is enabled):
```
[sentry] ERROR: Unexpected status code: 403 (body: b'{"detail":"event submission rejected with_reason: ProjectState"}')
| Unexpected status code: 403 (body: b'{"detail":"event submission rejected with_reason: ProjectState"}')
```

**Comment by mynameistechno** [comment]
I was able to set up sentry in a different django app and it worked. Any pointers on how to debug the issue in the other django app? Is "ProjectState" part of sentry?

**Comment by doublecompile** [comment]
I'm running self-hosted Sentry on Kubernetes and using the Helm charts. I ran into the above error after deploying the latest chart, and tracked down a related message in the Relay pod. 

```
2023-03-31T12:46:58Z [relay_server::actors::project_upstream] ERROR: error fetching project states: upstream request returned error 401 Unauthorized
  caused by: Unknown relay
```

I killed the Relay pod and allowed it to restart; once I did, everything began working correctly across all affected projects.

**Comment by TBS1996** [comment]
Thanks for updating, we're closing this issue as it seems to be working now. Feel free to re-open if needed.
