### ISSUE TITLE
Perf: Switching to the Network tab has a noticeable delay

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#46428]
Example replay: https://sentry-emerging-tech.sentry.io/replays/billy-test:cb8c41dbd430498896bc155041496de0/?project=6326737&query=&referrer=%2Freplays%2F&statsPeriod=14d&t_main=network&t_side=crumbs&yAxis=count%28%29

**Comment by bruno-garcia** [comment]
Relates: https://github.com/getsentry/sentry/pull/47357

**Comment by eliashussary** [comment]
Also related and shipped: https://github.com/getsentry/sentry/pull/47354

tldr; it caches cell measurer

**Comment by eliashussary** [comment]
Another UI/X enhancement but is a bit of a hack: https://github.com/getsentry/sentry/pull/47357

A better solution would be to look into avoiding cell measuring for every row since every row is basically a fixed height. We should in theory be able to supply it a constant value and avoid all the enumeration over rows and computation of whether or not a row is in view.

**Comment by ryan953** [comment]
Could be better with https://github.com/getsentry/sentry/pull/48231/files#r1183125051

**Comment by ryan953** [comment]
> A better solution would be to look into avoiding cell measuring for every row since every row is basically a fixed height. We should in theory be able to supply it a constant value and avoid all the enumeration over rows and computation of whether or not a row is in view.

I'm looking into this and i think we're already skipping the height of each row.

heres: the code for the measurer: https://github.com/bvaughn/react-virtualized/blob/master/source/CellMeasurer/CellMeasurerCache.js#L65

We're passing in this config: https://github.com/getsentry/sentry/blob/master/static/app/views/replays/detail/network/index.tsx#L32-L46

the rendered height is 28px, so it looks good already imo, but still can be slow.

**Comment by ryan953** [comment]
Update, looks like it's only slow the first time the tab is opened, after that it's more snappy.

**Comment by ryan953** [comment]
This is better given the conversation above, but perf can always be better. If someone gets a fresh example of slow perf then lets open a new ticket.
