### ISSUE TITLE
Crons: Interval monitors sometimes have their next checkin double what it should be

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#46427]

**Comment by evanpurkhiser** [comment]
This was confusing because the margin was set to 59 minutes (for a 1 hr checkin).

@gaprl can you find or create a ticket that describes separating the margin from the next checkin both in the backed and in the UI, and link it here (and close this one)

**Comment by evanpurkhiser** [comment]
Okay, here is the correct ticket that actually describes what should happen so this is not confusing https://github.com/getsentry/sentry/issues/46843
