### ISSUE TITLE
JS Loader settings UI improvements

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry#46436]
### Problem Statement

The current UI to configure the loader has some room for improved clarity:

![image](https://user-images.githubusercontent.com/2411343/228176931-0572b163-2ca0-4dc9-9b6e-7c1f7e28a990.png)

### Solution Brainstorm

Possible improvements in clarity:

* When enabling replay or performance, the SDK version is always 7. We should either disallow setting this to something before 7, or at least show a message that this is the case, I guess?
* When enabling replay, the loader switches from the ES5 build to the ES6 build. This is necessary as replay is ES6-only. We should maybe show a message that this is the case, as it means that the loader will not work e.g. on IE11.
* We should maybe rename "Enable Debug Bundles" to something a bit clearer, e.g. "Enable debug logging" or something like this? IMHO "Debug Bundles" is rather technical/internal. We should also make sure in https://github.com/getsentry/sentry/issues/46368 that `debug: true` is the default in that case.

**Comment by danielkhan** [comment]
Looks good but needs more copy on the different items so that I know what it is.
E.g. what are "debug Bundles"?
