### ISSUE TITLE
Broken dependancy of sentry on selenium=3.0.0b3

### ISSUE THREAD

**Issue by leoleovich** [getsentry/sentry#4645]
sentry 8.10.0
Debian Jessie
No docker

There is a dependency for sentry https://github.com/getsentry/sentry/blob/master/setup.py#L132, which is uninstallable, because of broken package name in pip
```
root@aw-db02:~# pip install selenium=3.0.0b3
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 269, in run
    InstallRequirement.from_line(name, None))
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 173, in from_line
    return cls(req, comes_from, url=url, prereleases=prereleases)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 71, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2793, in parse
    reqs = list(parse_requirements(s))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2721, in parse_requirements
    "version spec")
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2686, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'selenium=3.0.0b3', 'at', '=3.0.0b3')
```
```
root@aw-db02:~# grep version selenium-3.0.0b3/setup.py
    'version': "3.0.0.b3",
```
It is fixable by downloading archive and repacking with the proper version (selenium-3.0.0.b3). But some more people may complain.

**Comment by mattrobenolt** [comment]
Uhh, you're mistyping. There should be two equals signs.

**Comment by mattrobenolt** [comment]
Just to follow up here, why were you trying to install dependencies manually like this? Was there a reason that drove you to need to do this? You should only really need to do `pip install sentry` and it'll take care of all dependencies for you.

**Comment by leoleovich** [comment]
@mattrobenolt - I am building debian packages out of sentry and all components. Installation requires to execute:
1) Download dependency
2) `py2dsc -m 'Oleg <leoleovch@domain.com>' ./${package}.tar.gz`
3) `cd deb_dist/${package} && DEB_BUILD_OPTIONS=nocheck debuild -i -us -uc -b`

This fails for this version
```
Traceback (most recent call last):
  File "setup.py", line 82, in <module>
    setup(**setup_args)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/stdeb/command/sdist_dsc.py", line 74, in run
    assert actual_package_dirname==expected_package_dirname
AssertionError
ERROR running: /usr/bin/python setup.py --command-packages stdeb.command sdist_dsc --dist-dir=/root/sentry/deb_dist --use-premade-distfile=/root/sentry/selenium-3.0.0b3.tar.gz --maintainer=Oleg <leoleovch@domain.com>
```
and works perfectly fine with upstream 3.0.2

**Comment by mattrobenolt** [comment]
Oh, yeah, not sure how much I can help here. It definitely installs just fine with `pip`, so unclear what the issue would be or how to resolve it. I'd be open to suggestions.

**Comment by leoleovich** [comment]
Is there a real reason to use only this beta version in dependency list (==)?
There is an agreement on versions, and I do not think this one fits in: https://www.python.org/dev/peps/pep-0440/#examples-of-compliant-version-schemes

This issue may not be important for pip installation, but we do not use pip on production.

**Comment by mattrobenolt** [comment]
I'm not sure, but this is outside the scope of our product. We officially support installation via `pip` only and this is considered a requirement for us. It's unclear to me if there will be other issues, but I'm not inclined to randomly update dependencies just to satisfy an unofficial installation method.
