### ISSUE TITLE
Allow showReportDialog to be more configurable

### ISSUE THREAD

**Issue by jmatsushita** [getsentry/sentry#4646]
Hi there,

Awesome product so thanks a ton for making it available as Open Source!

I just discovered the User Feedback feature which is really great, but I wish there would be more configuration options. For instance, given the great attention to privacy preserving error reporting elsewhere, it would be great to be able to not make the user name and email address required:

![image](https://cloud.githubusercontent.com/assets/356097/20966405/6691c226-bc7a-11e6-95c7-fb7cb1f5dc6e.png)

Also here are some other potential candidates for additional configuration options:
 - Allow the title and subtitles to be configurable.
 - Allow the thank you message to be configurable
 - Allow the user to see the crash report before sending it.

Keep up with the amazing work!

Cheers,

Jun

**Comment by dcramer** [comment]
@jmatsushita the primary goal here is the user connection, not so much the actual comments they leave (as they're almost never going to be as useful as the information we already collect). Because of that I dont think we want to make user information optional, other than maybe not requiring a real name.

I do agree however on making the messages configurable, as that has come up quite often in many regards. One of the primary being custom translations.

Also of note, the user feedback isn't an opt-in to send a crash report, we've already sent it to the server and that wouldn't change. Because of that, it wouldn't really make much sense to try and show them the crash report.

**Comment by jmatsushita** [comment]
> the primary goal here is the user connection, not so much the actual comments they leave (as they're almost never going to be as useful as the information we already collect). 

Can I then suggest a more straightforward default subtitle instead of `If you'd like to help, tell us what happened below` and maybe `If you'd like to get in touch so we can let you know if we've fixed the problem and to tell us more about what happened`... ?

> I do agree however on making the messages configurable, as that has come up quite often in many regards.

Awesome!

> It wouldn't really make much sense to try and show them the crash report.

It's true that the subtitle already says "Our team has been notified" so its clear that it isn't opt-in already. I gues it would make sense to also allow the user to see the error message for deployments where an increase of transparency would be valued by the user (in particular if they want to check that there was no personally identifiable info that was sent).

**Comment by ThiefMaster** [comment]
I think being able to make the name/email optional would be useful. If a user is willing to spend the time to write a comment what went wrong it's already valuable information.

**Comment by dcramer** [comment]
Going to go back on what I said a year ago, and say we'd be open to making the name and email address optional fields at this point. I do still think they're extremely valuable here (whereas the feedback isn't so much).

**Comment by TuxujPes** [comment]
Hi there,
This one is open, but I can see that some of the requested features were already implemented, such as configurable labels.

I would like to have a bit different functionality though:
Is there a way to pass default values into inputs for `id_name`, `id_email`?

Usually, when the app faills, we already have knowledge of that data about users.
So it would be good to have those values prefilled with data.

**Comment by dcramer** [comment]
You can already do that by passing (iirc) userName and userEmail. 

Also closing this out since we landed these changes on the server months ago.

**Comment by TuxujPes** [comment]
@dcramer could you please elaborate on the way to pass userName and userEmail?

https://docs.sentry.io/learn/user-feedback/?platform=browser does not seem to have information on this

**Comment by dcramer** [comment]
@kamilogorek could we work to get the user feedback stuff fully documented? 

@TuxujPes it actually looks like, at least in raven-js, that its ``{user: {name: ..., email: ...}}``

**Comment by dcramer** [comment]
@kamilogorek oh also should double check -- did we fix showReportDialog to pass any option given to it to the endpoint (e.g. to support the localization params)

**Comment by TuxujPes** [comment]
Thanks, @kamilogorek!
I looked into documentation so I thought it is not available.

I should have checked `interface ReportDialogOptions` first...
