### ISSUE TITLE
Flakey test on events-stats

### ISSUE THREAD

**Issue by edwardgou-sentry** [getsentry/sentry#46461]
https://sentry.sentry.io/issues/4043871495/events/f6dca6eedd62455d80fa0b91b5b6b0bf/?project=2423079&referrer=alert-rule-issue-list

**Comment by DominikB2014** [comment]
Closing as the sentry issue link leads to "The issue you were looking for was not found."
Seems like the issue hasn't occurred in awhile and got deleted, so this issue is either not actionable or not relevant
