### ISSUE TITLE
Incorrect "Last seen" release shown in issue view

### ISSUE THREAD

**Issue by gthb** [getsentry/sentry#46499]
### Environment

SaaS (https://sentry.io/)

### Link

https://grid.sentry.io/issues/3949166297/?environment=production&project=1871088&query=%22Cannot+set+properties+of+undefined+%28setting+%270%27%29%22&referrer=issue-stream&sort=freq&statsPeriod=90d&stream_index=0

### Steps to Reproduce

1. Have a Sentry issue A last seen in an old release R, last month
2. Get a new Sentry issue B that doesn't get automatically grouped with A
3. Realize on manual inspection that B is really a recurrence of A, so manually merge them
4. Open the issue, see that its "Last seen" entry in the right sidebar now reflects the new occurrence ("11 hours")
5. Now notice that this "Last seen" entry claims "in release <R>” (that old release last month) and go “huh, somebody still has that open? 🤔”
6. Now notice that the tags of the latest event in the issue _actually_ show the newest release. So that “Last seen” release was incorrect (presumably from before the issues were merged)

### Expected Result

I expect the “Last seen” information to show a timestamp _and_ release ID from the same event. If one is still stale from before the issue merge (because of some “eventually consistent” fun stuff underneath), then _both_ should be, because that's less misleading.

### Actual Result

![image](https://user-images.githubusercontent.com/153580/228513748-ceb79d42-5561-4a40-bd63-2d8ce8e04447.png)

**Comment by scttcper** [comment]
Thanks for reporting this really clearly, I've added this to the teams backlog. There's a few funky things that happen when merging issues.

**Comment by brianthi** [comment]
Hi @gthb, we're thinking about how to improve our grouping logic so that manual merges become less necessary.  Could you share with us what data in the issue you used which gave you confidence that one issue was a recurrence of another?

**Comment by gthb** [comment]
> Could you share with us what data in the issue you used which gave you confidence that one issue was a recurrence of another?

It was the tip of the stack trace, combined with my knowledge that differences in stack frames further up do not matter in this case, that is, they do not make for separately addressable issues. Kinda doubt that there's a generalizable way to determine that without domain knowledge, but who knows, you are the wizzes with respect to that :)

**Comment by etienne-bondot** [comment]
Hi, I had a similar issue seting up a new sentry integration.
Publishing multiple releases and trigerring the same error (from the example of the documentation).
I can see the error handle by Sentry on each release:

![image](https://github.com/getsentry/sentry/assets/2827929/9b356b47-cbd0-4a7a-bf2a-e29fd40323b3)

But on the issue report, the "Last seen" field is still set to the first occurence (release v0.0.22).

![image](https://github.com/getsentry/sentry/assets/2827929/bb117f60-6984-446a-a2fe-42bbbf6a092f)

Any news on this issue?

I'm using NextJs deploying on Vercel with  `@sentry/nextjs` v7.103.0.

**Comment by leeandher** [comment]
As this hasn't received any changes in some time, and caching delays are expected in some areas of the app, I'll be closing this out. If you're still experiencing this issue, please let me know so I can reopen and investigate fixes!
