### ISSUE TITLE
Link Transaction Names to Transaction Summary in Dashboards

### ISSUE THREAD

**Issue by silent1mezzo** [getsentry/sentry#46519]
### Problem Statement

When I have a widget that shows a group of transactions, there's no easy way to get to that transaction.

![Screenshot 2023-03-29 at 12 34 30 PM](https://user-images.githubusercontent.com/155016/228607618-7ac61aae-45ba-4529-b483-f7bc3ae5ef0e.png)

### Solution Brainstorm

Linking the transaction name to the Transaction Summary would help me find out more information about that transaction.

**Comment by ale-cota** [comment]
hi, @silent1mezzo!
Sorry it took us a while to get back to this issue. We weren't able to reproduce this problem when using the `transaction` field. Can you please confirm that's the one you're using? If the problem still persists, can you share a link to the dashboard where you're facing this issue? Thank you!

**Comment by silent1mezzo** [comment]
@ale-cota unfortunately I no longer work at Sentry and don't have access to this dashboard.

> hi, [@silent1mezzo](https://github.com/silent1mezzo)! Sorry it took us a while to get back to this issue. We weren't able to reproduce this problem when using the `transaction` field. Can you please confirm that's the one you're using? If the problem still persists, can you share a link to the dashboard where you're facing this issue? Thank you!

**Comment by ale-cota** [comment]
Hi Adam,
Thanks for the quick response and sorry for not recognising the username 😅
It works as expected currently, so the issue was fixed in the meantime.

All the best,
Ale
