### ISSUE TITLE
[Integrations] - Github Enterprise - Able to use the same features as Github

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#46521]
### Problem Statement

Currently it is not possible to leverage the same features in Github enterprise vs. Github

Features that are missing inside github enterprise are:
- Link your Sentry stack traces back to your GitHub source code with stack trace linking.
- Import your GitHub [CODEOWNERS file](https://docs.sentry.io/product/integrations/source-code-mgmt/github/#code-owners) and use it alongside your ownership rules to assign Sentry issues.

![Screenshot 2023-03-29 at 18 34 41](https://user-images.githubusercontent.com/25929053/228609656-00b7d455-ac04-4b40-aa74-932ff6a00c7f.png)

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1798) by [Unito](https://www.unito.io)

**Comment by Dhrumil-Sentry** [comment]
I agree this feature is useful for large customers and have added it to the backlog, would request Sentry folks to get their customers to upvote/comment here so we can understand how many large customers are asking for this

**Comment by Angelodaniel** [comment]
🥁 -> I think we can close this ticket 
https://changelog.getsentry.com/announcements/stack-trace-links-codeowners-suspect-commits-for-github-enterprise
