### ISSUE TITLE
[Flaky CI]: static/app/components/events/contexts/user/index.spec.tsx

### ISSUE THREAD

**Issue by mattgauntseo-sentry** [getsentry/sentry#46550]
### Flakiness Type

Assertion failure

### Name of Job

Jest

### Name of Test

static/app/components/events/contexts/user/index.spec.tsx

### Link to Test Run

sentry.sentry.io/issues/3974475742/?project=4857230

### Details

@priscilawebdev @malwilley @shruthilayaj as y'all are in the history of commits for this test file.

Disabled in: https://github.com/getsentry/sentry/pull/46545

**Comment by priscilawebdev** [comment]
will take a look into it! Thanks for reporting @mattgauntseo-sentry

**Comment by priscilawebdev** [comment]
@mattgauntseo-sentry are you sure the flaky test is not the `components/events/contexts/browser/index.spec.tsx `? the linked issue points to the browser test

**Comment by mattgauntseo-sentry** [comment]
There is a chance that the same error is coming from multiple places meaning that sentry it showing a new and different test.

For example, searching `All Events` for `components/events/contexts/user/index.spec.tsx` shows a number of events that are from the file in the original issue: https://sentry.sentry.io/issues/3974475742/events/2f52c9fb5d6d4ea8a9f32323c32a0d45/?project=4857230

Sadly, those events are happening after this skip, so it seems like this might be a common issue in our tests.

**Comment by priscilawebdev** [comment]
I see... thanks @mattgauntseo-sentry. because this is only happening in CI it is very difficult to trace the cause 😔
