### ISSUE TITLE
Source Map field returns 0 even though debug id bundle has weakly associated releases

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#46577]
### Problem
Source Map field returns 0 even though debug id bundle has weakly associated releases
![Image](https://user-images.githubusercontent.com/6508377/228766420-a5a9155e-7704-49f8-9b71-9f6e202a3fca.png)

### Acceptance Criteria
- Show number of artifacts if debug bundle was associated with a release

**Comment by iambriccardo** [comment]
PR: https://github.com/getsentry/sentry/pull/46585
