### ISSUE TITLE
`List a Project's issues` endpoint - Stats field does not respect environment

### ISSUE THREAD

**Issue by BlakeSearlSonocent** [getsentry/sentry#46586]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Set up two environments (e.g. `dev` and `production`)
2. Generate an event that links to the same issue in each environment
3. Use the [List a Project's issues endpoint](https://docs.sentry.io/api/events/list-a-projects-issues/) to list issues, limiting to a singular environment (e.g. https://sentry.io/api/0/projects/{organization_slug}/{project_slug}/issues/?query=environment:production)
4. Look at the stats field, the counts will be the sum of events in `dev` and `production`, rather than just `production`

### Expected Result

The counts within the `stats` field should only be for the specified `environment`.

![Screenshot 2023-03-30 at 10 59 59](https://user-images.githubusercontent.com/74195660/228801250-74a0d1b9-02ef-441a-ad76-cbcb1623434f.png)

### Actual Result

The counts sum across all `environment`s regardless of the `environment` filter.

The regular `count` field does respect the `environment`, so it seems that the counts in the `stats` field should too.

**Comment by scttcper** [comment]
@BlakeSearlSonocent use the `environment=production` query parameter instead of `query=`

**Comment by BlakeSearlSonocent** [comment]
> @BlakeSearlSonocent use the `environment=production` query parameter instead of `query=`

Thanks! This works just fine (I actually thought I had tried this but clearly made a mistake somewhere 🤦)

Should this be added to the documentation, or did I miss something somewhere? I think it applies to other endpoints too, e.g. https://docs.sentry.io/api/events/retrieve-the-latest-event-for-an-issue/
