### ISSUE TITLE
UI & UX polish required for AI suggestion project

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#46584]
### Problem
The current implementation breaks Sentry's UI conventions

### Acceptance Criteria
- The user sees a permanent banner encouraging them to look at the suggestion
- The user is required to scroll below the breadcrumbs to find the AI suggestion Banner. Meaning, remove the header button.
- If the user has given their consent, we show AI-generated text in the format of, Problem, Solution & Joke
- The user can decide to rate their experience by clicking one of three buttons
- The user can collapse the section

### Designs

- [Figma](https://www.figma.com/file/8uOQuURhMQgRC72c81zOF4/Specs%3A-AI-Suggestions?node-id=0%3A1&t=ARHrvJHKoQ1mRVFv-1)
- [Art Assets](https://drive.google.com/file/d/1Fp5YRL4h6ORGcwuuv3W_5eSjUh79d02x/view?usp=sharing)

#### Banner Closed
![Image](https://user-images.githubusercontent.com/6508377/229452615-9217126d-dea5-424a-a669-f9c70da40c0f.png)

#### AI Suggestions Loading
![Image](https://user-images.githubusercontent.com/6508377/229452685-952d2d73-69ca-4086-b8bf-b220f9643b55.png)

#### AI Suggestions Shown
![Image](https://user-images.githubusercontent.com/6508377/229452718-ca94c07f-5186-44b2-be19-cf51ea9ccfa8.png)

**Comment by ale-cota** [comment]
@priscilawebdev, @Jesse-Box for the (?) Tooltip we talked about, I would suggest "This is an experimental feature that uses AI to explain an issue and to propose a solution. [Learn more](https://docs.sentry.io/product/issues/issue-details/suggested-fix/)"
