### ISSUE TITLE
Discrepancy between count_crashed(session) and sum(session) grouped by session.status

### ISSUE THREAD

**Issue by brentc** [getsentry/sentry#46606]
Customer is reporting seeing two different numbers for crashed sessions when they're using `count_crashed(session)` in a Big Number widget, and `sum(session)` grouped by `session.status` in a Table widget.

Reproduced in [my test dashboard](https://sentry.sentry.io/dashboard/8237/)

cc @kerenkhatiwada

**Comment by brentc** [comment]
Other higher priorities have bumped this, but we still intend to look into it. We'll update when we have more information.

**Comment by ale-cota** [comment]
This issue has not been active in a long time and is no longer reproducible. We're therefore closing it to keep our backlog maintainable and transparent. 

Please feel free to leave a comment if you think this issue should be reopened.
