### ISSUE TITLE
[Design] Empty states for HTTP Req/Res + API Headers

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#46603]
**Opportunity**

For the HTTP Request, Response and API Headers features we want to visually communicate the following 3 states:

- When a request body, response body, and API header does not exist for a given network call
- When we reject the entirety of the request body, response body and API header due to it exceeding our size limit
- When we _truncate_ some part of the request body, response body, and API header due to our truncation approach

**Comment by Jesse-Box** [comment]
Given that truncation is still a work in progress, there might be more design input needed here.

However, I would say this is for the most part done.

The Figma file can be found [here](https://www.figma.com/file/SVyNvm8p17xGfIC7r7l2YS/Specs%3A-Details-%2F-Network-Tab?node-id=146%3A33268&t=qpaSrooUA59bW5Eo-1)
