### ISSUE TITLE
[Design] Highlight the DOM element on Replay Details after DOM element search is applied

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#46602]
**Opportunity**

Any time a DOM element search is applied on Replay Index, we want to be able to highlight the first instance of the DOM element on the Replay Index page when a user clicks thru to a replay.

The replay video will already be scrubbed to the point-in-time a DOM element is clicked. However, it may not be obvious what part of the page is the DOM element a user has searched for.

**Solution Brainstorm**

- Visually highlight in the replay video the DOM element that was interacted with.
- Visually highlight the associated UI click breadcrumb.

The stopgap before this comes along is https://github.com/getsentry/sentry/issues/47312

**Comment by ryan953** [comment]
We might also want to highlight in the Replay List how many found dom elements are within each replay result.

This could be a reason to fork the index page, and create a 'dom search' specific tab/view that has a different search interface, and different columns in the result table. Forking the view like that might also make it easier for the backend to optimize the different queries (dom-search vs. generic search)

**Comment by Jesse-Box** [comment]
@jas-kas 

@ryan953 and I talked last night, and we found a simple solution to improve the flow from index to details, highlighting the DOM elements you originally searched for. See Below.

[Figma Link](https://www.figma.com/file/sQEM8sWZKTbkZrFB33I1eY/Specs%3A-DOM-Search?node-id=83%3A8242&t=cTahpk5pO69a1zOR-1)

![Image](https://user-images.githubusercontent.com/6508377/234603563-221486ca-f796-462f-a7a8-1b351e41ab5f.png)

There are two improvements I believe we can make:
1. Bring the smart search component into the DOM tab view, that can only utilize the `click` field. For example; If a user filtered the index page using click search and navigated to the details page of a replay, this smart search would be prefilled with the same query used on the index page. I'm implying here also that the DOM tab would be the first tab shown if they did use Click Search on the index page.
2. Lightly modify the styling of existing DOM highlighting shown on the replay. Specifically, inverting the styling to create a vignette-like effect.

Let me know what you think

**Comment by jas-kas** [comment]
Hey @Jesse-Box,

Both of these improvements look great!

1. Although I think this is neat, I'm not sure if it would be worth the effort to implement. I also think it might be confusing if _some_ search conditions carry over to the Details page, and others don't. (Although all are applied)

2. I think we should definitely pursue this design. I have a few questions thought: How long does the vignette-like effect stay on the replay video once you click into a replay? Will this vignette-like effect replace all of our existing DOM highlighting? Or is only if you come from Click Search?

**Comment by Jesse-Box** [comment]
> How long does the vignette-like effect stay on the replay video once you click into a replay?

Good question. So assuming the video skips to the first instance of that dom element, I would expect the highlighting to persist until:
1. Resumes or scrubs through the replay
2. Hovers over any breadcrumb item or DOM row item  `!===` that very DOM element
3. Clicks on any play icon on any row item

@ryan953 what's your thoughts on this?

> Will this vignette-like effect replace all of our existing DOM highlighting?

Yes it would, I see no reason why distinction would be necessary

**Comment by ryan953** [comment]
What jesse said makes the most sense imo

**Comment by Jesse-Box** [comment]
Marking this design task as done

Figma file [here](https://www.figma.com/file/sQEM8sWZKTbkZrFB33I1eY/Specs%3A-Click-Search?node-id=92%3A28263&t=in1xW57pvd1svzqS-1)
