### ISSUE TITLE
Arrow Down does not work on single completion in the search box

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#4660]
Currently if you use arrow down when there are two choices it completes the first one. However if there is only one available (for instance: `is:mu` for `is:muted`) you need to auto complete with tab instead as the current item is already selected and nothing happens.

**Comment by alsuren** [comment]
Similar to this, currently the only way to insert a completion is to hit tab. A common way to insert a completion in the browser (when you're at the rightmost end of the input and there are completions to be had) is to hit right-arrow. I don't think that right-arrow is used for anything at the moment, so I may contribute a patch that fixes both at the same time (no promises though).

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
