### ISSUE TITLE
[Design] "Organic" Introduction of HTTP Request/Response + API Headers

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#46637]
## **Problem**

We want to introduce the HTTP Request/Response + API Header feature in a subtle contextual way to bring awareness of this feature to our user base. We also want to bring awareness to this feature in the "zero-state" of the Replay Details > Network tab view. Without any additional efforts here, the only indication of this feature in the UI is that the cursor changes to 'clickable' (i.e., pointer) on applicable Network calls.

## **Solution Brainstorm**

- ”Beta”/”New” flag
- Add a note under or above the Network calls list to draw attention to it 
- Indication directly on applicable Network calls (possibly a small icon)
- [Other]

**Comment by Jesse-Box** [comment]
Apart from copy, ill consider this design task done

Figma file can be found [here](https://www.figma.com/file/sQEM8sWZKTbkZrFB33I1eY/Specs%3A-DOM-Search?node-id=37%3A2383&t=monjTMA9La5zLqUz-1)
