### ISSUE TITLE
Not showing exact file name & line number in Sentry with Webpack integration in a Node.js Express Application

### ISSUE THREAD

**Issue by Govind-Sivadasan** [getsentry/sentry#46653]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

@sentry/node - 7.44.2, @sentry/webpack-plugin - 1.20.0

### Steps to Reproduce

1. Added the following Sentry webpack plugin in `webpack.config.js`.
```
const SentryWebpackPlugin = require('@sentry/webpack-plugin');

const config = {
  plugins: [
    new SentryWebpackPlugin({
      include: ['../dist', '.'],
      ignore: ['node_modules', 'webpack.config.js'],
      configFile: 'sentry.properties',
    }),
  ],
};
```

2. Added `devtool: 'source-map'` and `mode: 'production'` in the `webpack.config.js` so that it can help with debugging and tracing errors back to their original source code.
     ##### Note:- Verified the validity of source-map file with [`source-map-support`](https://www.npmjs.com/package/source-map-support) node package and later removed before uploading to sentry and by following [4 Reasons Why Your Source Maps are Broken](https://blog.sentry.io/2018/10/18/4-reasons-why-your-source-maps-are-broken/)

3. Followed the instructions as mentioned in the [sentry documentation](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/webpack/).

**Final Output:-** When a crash occurs in the application, the stack trace points to the minified JavaScript file, which makes it challenging to identify the exact location of the error in the original source code.

### Expected Result

When there is a crash, the Sentry should be able to show the actual file name and line number.

### Actual Result

![Not working - Copy](https://user-images.githubusercontent.com/101784959/229031405-4a39b881-f5cc-4c64-aa28-29a4c1663dd4.jpg)

**Comment by rbisol** [comment]
Pleas check the source map troubleshooting guide: https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/
