### ISSUE TITLE
Replay: Replace Timeline Duration with Timezone

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#46650]
### Problem Statement

For some captured sessions, customers have requested the timeline to reflect the time (in UTC or otherwise) at which the breadcrumbs and user invocations were captured. For our clients' support teams, this could reduce triage and allow developers to compare the session to other metrics such as event statistics. 

### Solution Brainstorm

Perhaps import the current time as the startTime for a session, then import again at the end of the session for the endTime. Then replace the durations on the timeline with values relative to the startTime.

**Comment by bruno-garcia** [comment]
The current times are adjusted to the local (user watching the Relay)'s time. 
The goal is to know then timezone of the user? Usually other apps/tools also show things in local time. If they are shown in UTC then the onus is on the other tool to adjust UTC to the user's local time, making it easier to compare timestamps across tools.

To help me better understand the use case, could you share which tools you are using to match the times against? And a bit more about the workflow? This is: Looking at logs in Kibana and matching timestamps with Sentry breadcrumbs?
