### ISSUE TITLE
Sensitive data is not filtered if it appear in the exception message

### ISSUE THREAD

**Issue by boussouira** [getsentry/sentry#4666]
This is an example:
http://i.imgur.com/qJh4APK.png

However the password is filtered in Breadcrumbs and stack local variables
I'm using sentry.io as the server

**Comment by ganeshkbalaji** [comment]
Work in Progress

**Comment by mattrobenolt** [comment]
Hm, why was this closed?

**Comment by boussouira** [comment]
Closed by mistake! It's still happening and now the sensitive data show up in Breadcrumbs too:
![image](https://user-images.githubusercontent.com/1050218/44948286-83dced00-ae0a-11e8-8069-fca24e480c89.png)

**Comment by boussouira** [comment]
@dcramer Is this an easy task?

**Comment by luozhaoyu** [comment]
I am using `sentry-python` and I also think Sentry's server-side scrubbing works for "additional data", but not for data in "exception"

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by boussouira** [comment]
No need to open it again, after 4 years bugs are fixed automatically

**Comment by BYK** [comment]
@boussouira there was a lot of work around this. If this is still an issue, I'll reopen and bug some people. Is it?

**Comment by boussouira** [comment]
No worries, we did some workaround in our app
