### ISSUE TITLE
Add support for a function that shows the earliest time of the event in Discover

### ISSUE THREAD

**Issue by brentc** [getsentry/sentry#46703]
We have a `last_seen()` function, but the only way to see the _earliest_ equivalent is to use `min(timestamp)`.

Calling it `first_seen()` would link it more logically with `last_seen`, but wouldn't actually be accurate as the actual first seen may have been discarded by data storage time limits. 

Maybe `earliest()`?

**Comment by alexjillard** [comment]
Closing issue since we will only have 90d of data at most, so showing an earliest/first seen results in a misleading UI and likely to be more harmful than helpful in many situations.
