### ISSUE TITLE
Add support for `having` clause in metrics layer

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#46720]
**Description**

As a request from performance team, we would like to extend the metrics layer with support for having clause in the queries.

The current implementation of having with metrics is available in the query builder at https://github.com/getsentry/sentry/blob/69b66cacd33d1f999357e7c5a1a0028b3993f186/src/sentry/search/events/builder/metrics.py#L235-L251

**Acceptance Criteria**

The metrics layer supports having in the MetricsQuery.

**Comment by iambriccardo** [comment]
An example test which is using the `having`: https://github.com/getsentry/sentry/blob/61b5ad886ba4a4f68700a6b5d5fa77eaa05b6be5/tests/snuba/api/endpoints/test_organization_events_mep.py#L253-L253

**Comment by iambriccardo** [comment]
The implementation of the `having` should just expose `snql`, similarly to how the `where` is implemented.
