### ISSUE TITLE
Implement fetching actual_sample rate per project to avoid under/over sampling of projects

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#46724]
AC: It adjusts the base sample rate to get closer to the overall fidelity.

https://sentryio.cloud.looker.com/dashboards/1024?Snapshot%20Date=yesterday&Reserved%20Quantity=%3E5000000&Dynamic%20Sampling%20Rate%2028d=NOT%20NULL&Billing%20Category=transactions&Plan=%25am2%25

**Comment by andriisoldatenko** [comment]
https://github.com/getsentry/getsentry/pull/10094
https://github.com/getsentry/sentry/pull/46773
