### ISSUE TITLE
403 (FORBIDDEN) when using with Ionic 2

### ISSUE THREAD

**Issue by rolandjitsu** [getsentry/sentry#4673]
Sentry: **3.9.1**
Framework: **Angular 2.1.1**

I just setup Sentry with an Ionic 2 app (which uses Angular 2) and whenever an error is thrown, Sentry comes back with a **403 FORBIDDEN**:
```js
{"error":"Event dropped due to filter"}
```

Request:
```
POST https://sentry.io/api/<id>/store/?sentry_version=7&sentry_client=raven-js%2F3.9.1&sentry_key=<key>
```

Response headers:
```
Access-Control-Allow-Headers:X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication
Access-Control-Allow-Methods:GET, POST, HEAD, OPTIONS
Access-Control-Allow-Origin:*
Cache-Control:max-age=0
Connection:close
Content-Language:en
Content-Length:39
Content-Type:application/json
Date:Wed, 14 Dec 2016 16:20:27 GMT
Expires:Wed, 14 Dec 2016 16:20:27 GMT
Last-Modified:Wed, 14 Dec 2016 16:20:27 GMT
Server:nginx
Strict-Transport-Security:max-age=31536000; includeSubDomains; preload
Vary:Accept-Language, Cookie
X-Content-Type-Options:nosniff
X-Frame-Options:deny
X-Sentry-Error:Event dropped due to filter
X-Served-By:web-7
X-XSS-Protection:1; mode=block
```

Request headers:
```
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US
Cache-Control:no-cache
Connection:keep-alive
Content-Length:16142
Content-Type:text/plain;charset=UTF-8
Host:sentry.io
Origin:file://
Pragma:no-cache
User-Agent:Mozilla/5.0 (Linux; Android 7.0; PREVIEW - Google Nexus 5X - 7.0.0 - API 24 - 1080x1920 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.91 Mobile Safari/537.36
X-DevTools-Emulate-Network-Conditions-Client-Id:1B50CF02-F094-462F-8700-04DBD7671A17
X-Requested-With:com.ionicframework.operator117483
```

Query string params:
```
sentry_version:7
sentry_client:raven-js/3.9.1
sentry_key:<key>
```

And there is some payload which I'm not sure how relevant it is (mostly about the error).

**Comment by dcramer** [comment]
In the future please use our support options:

https://sentry.io/support/

This is saying that Sentry's server-side filters are dropping your request. You can change these via [project] -> Settings -> Inbound Data Filters.

**Comment by rolandjitsu** [comment]
@dcramer I already checked that and the only thing that is checked is web crawlers, but this app is not a web crawler. I wouldn't have opened an issue before I checked it.

So, could it be that the sentry server just blocks everything coming from `file://`? In which case, what can we do about it? Since, my guess is, all Ionic apps will have the same origin.

**Comment by toddanglin** [comment]
FWIW, I was having this same problem using Raven in a NativeScript app (getting 403 errors for all POST requests). To "solve" the problem, all I had to do was explicitly set the `Origin` header to a URL and then everything worked.

So, as an example using the `http` library in NativeScript:
```typescript
http.request({
   method: "POST",
   headers: {
      "Content-Type": "application/json",
      "Origin": "http://www.nativescript.org"
   },
   url: url,
   timeout: 2000,
   content: JSON.stringify(options.data)
})
``` 
I assume this would similarly work in a Ionic/hybrid app. Hope it helps someone else.
