### ISSUE TITLE
Subscription breadcrumb has an incorrect link

### ISSUE THREAD

**Issue by liamjones** [getsentry/sentry#46766]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Navigate to Subscription -> Receipts (or anything else under Subscription)
2. Click Subscription in the breadcrumb at the top of the page

### Expected Result

Subscription page is displayed

### Actual Result

Organisation page is displayed

**Comment by brianthi** [comment]
I'm no longer able to reproduce this, closing issue.
