### ISSUE TITLE
Add to the project creation flow

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#46775]
**Problem/Opportunity**: We want to encourage customers to add Replay also in the new project creation flow. This flow has the extra kink that the customer has to be on an AM2 plan for it to make sense, otherwise they can add the code snippet but nothing will happen. 

**Solution**:
Add the same UI with product selection to the new project creation flow as well and guide customers on legacy plans to update to AM2.

**Acceptance Criteria**:
- If the org is on AM2, then the UI with all checkboxes is displayed
- If the org isn't, nothing changes.

**Comment by ale-cota** [comment]
@Jesse-Box, @priscilawebdev I've drafted the ticket, let me know what you think. Thank you!

**Comment by priscilawebdev** [comment]
lgtm @ale-cota
