### ISSUE TITLE
API to add supplementary data to an event

### ISSUE THREAD

**Issue by mikepurvis** [getsentry/sentry#4678]
I inquired about this a few months ago on https://github.com/getsentry/raven-objc/issues/11, just want to open a discussion here in its own issue.

The situation is:

- Our app is composed of a bunch of small C++ binaries, which are mutating all the time.
- We archive debug symbols from the build process which produces these binaries.
- An in-house crash reporter sends core dumps back to Sentry.
- Accessing the symbols and expanding the stack-traces from these dumps has a nontrivial time/compute cost.

We deal with a high enough volume of events that doing the stack trace expansion either in-process (with a [sentry plugin](https://github.com/getsentry/sentry/blob/master/src/sentry/lang/javascript/plugin.py)) or pre-process (via Cyclops) may not be realistic. What I think we want is to be able to do this asynchronously, with some kind of external job queuing system (eg Rundeck or the like) that can be notified "generate the stack trace for this core file" and then can call Sentry back a few minutes later "okay, here it is".

If this kind of functionality were possible in a sufficiently general way, there's actually a bunch of additional metadata which we could produce after the fact from various telemetry that comes from our system, including screenshots, plots, other visuals, etc. Some of this isn't even part of the Sentry report but could be correlated in from other silos and would add considerable value to the core Sentry report.

Understanding from @dcramer that Sentry treats the base event data as immutable once received, I guess I'm curious about possibilities for after-the-fact supplementals, generated either:

- Once an event is known to be fully retained (eg, not discarded via sampling), or
- On-demand by a developer clicking a button to _expand XYZ for this event_.

Are there other possibilities that I'm not seeing for how all this could be managed?

Thanks for any thoughts.

**Comment by rodneyrehm** [comment]
I'd also like to add attachments/links to an issue.

If message has been reported to Sentry (for our WebUI) I'd like to allow the user do one of the following things:

* download a configuration/state snapshot from their backend service and attach that ZIP file to the sentry event (required for debugging a second system that is not itself connected to Sentry)
* trigger their backend service to send a message to their sentry project (same server) and link that to event from the WebUI (possible for debugging a second system that is also connected to Sentry)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
