### ISSUE TITLE
Create members via API endpoint using internal integration with admin permissions

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry#46818]
### Problem Statement

Sharing this on behalf of a customer:

> We want to use this endpoint by an automation script for when people add their projects to sentry – so that if their account doesn’t exist, it will create it automatically and add it to the appropriate teams. Because that unit of automation will be sticking around long-term, we want to use an internal integration API key instead of my user-account API key.
> I tried to use an auth token from an internal integration, with admin-level member-management permissions to invite a member (via `POST https://sentry.io/api/0/organizations/my-org-slug/members/`).  However, I’m getting this error:

```
[2023-03-30 17:28:15,983] my_machine post():87      Posting {'email': 'myuser@myapp.com', 'userName': 'myuser@myapp.com', 'role': 'admin'} to https://sentry.io/api/0/organizations/my-org-slug/members/

[2023-03-30 17:28:17,142] my_machine _post():44     Response code: 400, response text: {"role":["You do not have permission to set that org-level role"],"orgRole":["You do not have permission to set that org-level role"]}
```

> This does not happen when I use my API key instead – I’m guessing because my account has Owner access. However, I would have hoped that Admin would have equivalent privileges. We can use my personal key in the short term, but this is not really ideal, given the potential for user accounts to be cleaned up (and the API key be destroyed).
Do you think this is something that can be looked into and potentially changed to allow me to call that endpoint using the internal integration?

Current permissions of the internal integration are:
![image003 (1)](https://user-images.githubusercontent.com/12092849/229619724-355667ea-add2-49d8-af95-0260dea32336.png)

### Solution Brainstorm

- I'd like to be able to use an internal integration with "admin" permissions to create members via this endpoint

**Comment by zukwung** [comment]
thanks for raising this @cstavitsky, I believe created a ticket for Sentry support.

**Comment by leedongwei** [comment]
That's odd. I'm in that area of the codebase and I can take a closer look later.

**Comment by kpujjigit** [comment]
Hi @leedongwei - any update on this?

**Comment by Dhrumil-Sentry** [comment]
@kpujjigit we don't have any updates yet, Danny is OOO for a few weeks- We will follow up on this later

**Comment by schew2381** [comment]
@zukwung @kpujjigit @cstavitsky
Hi there, sorry for the delay on this fix. I've made it so integration tokens can now successfully invite new members with the member role only.

**Comment by rohitkataria-sentryio** [comment]
Hi @schew2381 
Posting below on behalf of one of our Touch customer for whom we had raised this:

"Our default role is actually Admin rather than Member (to avoid org owners having to get involved every time someone wants to create a new team or project). Is there a reason why [this has only been allowed for Member role only](https://github.com/getsentry/sentry/issues/46818#issuecomment-1858519864)?"
