### ISSUE TITLE
Broken error link in transaction detail page

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#46853]
### Environment

SaaS (https://sentry.io/)

### Link

https://steven-eubank.sentry.io/performance/galloway-farms-nextjs:415374e688ba4834bf5f0b9922b1b9f6/?project=4504882863734784&query=&statsPeriod=14d&transaction=%2F#span-90b030d064358fae

### Steps to Reproduce

1. any transaction which is linked to a trace (at least I saw multiple examples of this)
2. navigate to the transaction detail page, the red banner should appear that says there is a linked error
3. try to click on it, it does nothing

(UX/UI feedback I always find the big red banners to look like something is wrong with my event, as in I did something wrong, and really it is just a link to)

Also I was slightly confused at first since the red banner at the top says `pageload` then when expanding the span with an error below it says network error

### Expected Result

Link works and takes me to the error issue page

### Actual Result

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/47563310/229748910-64d4c45d-a650-4ae3-ab58-5e849d13bfec.png">

**Comment by gggritso** [comment]
@smeubank now that Sentry has an all-new trace view, is this still an issue?
cc @0Calories

**Comment by 0Calories** [comment]
@gggritso We can close this, the new trace view doesn't have this problem
