### ISSUE TITLE
the new suggested fix button being so long is causing overflow at certain resolutions

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#46863]
### Problem
the new suggested fix button being so long is causing overflow at certain resolutions

### Acceptance Criteria
- The suggested fix button is removed
- The suggested panel is relocated below the breadcrumbs section
- The suggested panel title is “AI Solutions (Experimental)”
- The suggested panel section is titled “Resources and Maybe Solutions”
- The Suggested panel section can be collapsed if needed

### Design
![Image](https://user-images.githubusercontent.com/6508377/229786806-c55eabab-b0be-4ba1-9f93-ae84b19eb47a.png)
![Image](https://user-images.githubusercontent.com/6508377/229786739-b33683a5-afce-4fbd-89a9-447d4cdd278b.png)

**Comment by matejminar** [comment]
Closed in favor or https://github.com/getsentry/sentry/issues/46930
