### ISSUE TITLE
Getting 404 when requesting replays

### ISSUE THREAD

**Issue by cre8** [getsentry/sentry#46860]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.4.0.dev0

### Steps to Reproduce

I needed to migrate from a paid plan from SAAS to on premise because of compliance. We added the replay function and it worked fine on SAAS. But on the on premise solution we are getting errors:
```
NotFoundError
GET "/projects/{orgSlug}/{projectSlug}/replays/{replayId}/" 404
```

when it tries to get the following url `GET /api/0/projects/trustcerts/trust-signer-frontend/replays/fe577b6346e644e7967679732be215ee/ [404]`

On the left in the replay section I can see 2 replays that are 2 days old

I added the json export here [file.md](https://github.com/getsentry/sentry/files/11147566/file.md)

### Expected Result

Getting the replays for the errors, but none is generated

### Actual Result

Throwing internal errors :(

**Comment by cre8** [comment]
I got the same error pointing to one of the issues that where thrown with this message:
```
The replay for this event cannot be found. [Read the docs to understand why](https://docs.sentry.io/platforms/javascript/session-replay/#error-linking). This could be due to these reasons:

The replay is still processing
The replay has been deleted by a member in your organization
There is an internal system error
```
Could it be that the replay information were not uploaded to the server correctly but sentry thinks there is a replay for this issue?

**Comment by hubertdeng123** [comment]
It's possible that there was potentially an issue that happened when replays were being uploaded. The replay metadata is stored in Clickhouse and the replay segments are stored in Postgres.

1. Can you check the `replays_local` table in Clickhouse? How many entries do you see there? Is it empty?
2. What is in the postgres table `replays_replayrecordingsegment`? Is there any data there?

**Comment by cre8** [comment]
@hubertdeng123 

The postgres table returns me this information:
![image](https://user-images.githubusercontent.com/4020915/230662746-6daa0406-3086-4dc5-bb4d-7112f32b61a5.png)

And from clickhouse:
![image](https://user-images.githubusercontent.com/4020915/230663769-d601360e-3d81-44aa-a61a-dc2d5d1403b3.png)

So I see some data and I can request some replays from the browser. But for some errors it seems that some data is missing.

Clickhouse shows me 15 entries, but postgres got 50. But I see multiple entries for the replay_id in the postgres DB so the two different values seem to be correct

**Comment by cre8** [comment]
So i can confirm for the error of the 404 there is no entry in the DB according to this replay:

![image](https://user-images.githubusercontent.com/4020915/230664582-b902733e-1394-4dc7-94f3-47992d686185.png)

**Comment by hubertdeng123** [comment]
I believe Clickhouse should have metadata that can map to multiple blobs in postgres. Maybe the replay was dropped?

**Comment by cre8** [comment]
I reinstalled sentry from scratch. In case the error appears again I will reopen this and analyse the error (maybe the upload of the replay was aborted)
