### ISSUE TITLE
Subject substitution issue on email alert for Performance issue 

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#46872]
The email I received 2 days ago showed the subject like:

![image](https://user-images.githubusercontent.com/1633368/229830519-ddfa03f7-9b87-4b71-b834-10088bdb11dc.png)

Docs indicate the environment should be replaced: 

> You’re able to change the subject line for alert emails within your Project’s Email Settings by going to Project Settings > Alerts > Settings. Email subjects can include variables such as $project, $title, and ${tag:key}, such as ${tag:environment} or ${tag:release}.

I confirmed `environment` exists [in the event:](https://testorg-az.sentry.io/issues/4056375822/?referrer=alert_email&alert_type=email&alert_timestamp=1680447601889&alert_rule_id=889972) 

![image](https://user-images.githubusercontent.com/1633368/229830411-1b7c6457-d2b8-4a70-86c2-a10eb1309e07.png)

**Comment by nanoburd** [comment]
@bruno-garcia have you noticed this for other issue alerts for errors or performance?

**Comment by hubertdeng123** [comment]
Should this issue be routed to a specific team? Maybe performance? 🤔
