### ISSUE TITLE
Dashboard should not allow saving environment filter if env doesn't exist

### ISSUE THREAD

**Issue by narsaynorath** [getsentry/sentry#46870]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to a dashboard with an environment filter
2. Edit the environment filter in the URL query params to something that doesn't exist
3. See the dashboard breaks
4. Save the dashboard

### Expected Result

We shouldn't allow users to save the dashboard in this state. Doing so breaks all of the widgets on subsequent openings due to a 404 that happens when using the environment to look up data.

### Actual Result

The dashboard saves and no data will properly load.

**Comment by ale-cota** [comment]
@narsaynorath this doesn't seem to be reproducible anymore. I just tried it and when I load the dashboard with the non-existent environment it just ignores it and loads "All Env".
