### ISSUE TITLE
[feature-request] Ability to change the TOTP 2FA title

### ISSUE THREAD

**Issue by zerkms** [getsentry/sentry#4687]
At the moment (sentry 8) the TOTP 2 factor entry in the application appears as `Sentry (<email>)`.

It is slightly inconvenient when you run multiple sentry services, since each would look the same.

What if sentry provided a configuration option for that (or reused one of the existing options)?

**Comment by mattrobenolt** [comment]
This seams reasonable, but @mitsuhiko is probably the only one who knows how to do this. :)

**Comment by steffjenl** [comment]
Kick?
