### ISSUE TITLE
`HTTP_X_FORWARDED_FOR` is not used for sentry web worker logs

### ISSUE THREAD

**Issue by zerkms** [getsentry/sentry#4688]
As of sentry v8.11 the `sentry web` output log does not use the `SENTRY_USE_X_FORWARDED_FOR` setting and still logs the reverse proxy ip address:

```
127.0.0.1 - - [19/Dec/2016:03:27:55 +0000] "GET /api/0/organizations/?member=1 ...
```

**Comment by mattrobenolt** [comment]
Hmm, I'll have to see how to do this since the logging is happening from uWSGI. But shouldn't be impossible.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
