### ISSUE TITLE
Feature Request: Merged Issues Overview

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#46881]
### Problem Statement

Merging issues feels like a pretty opaque process at the moment. You select issues and decide to merge them. After that, they are added to some queue (would be nice to have some indication for that). I am missing some overview that displays which issues are merged together, be it just to check that there are no issues that have been accidentally merged that don't actually belong. 

### Solution Brainstorm

An overview page that shows which current issue merging rules are active. Rules can then be expanded to show which actual issues are merged into that single issue.

**Comment by scefali** [comment]
@jeengbe How are you selecting issues to merge them? I'd recommend using the similar issues tab and then checking the grouping score before merging:

![Screen Shot 2023-04-04 at 1 26 14 PM](https://user-images.githubusercontent.com/8533851/229912335-46069043-888b-4ea2-be3a-abe6e26ada88.png)

With this workflow, I'm petty sure you can avoid merging issues that shouldn't be grouped together.
