### ISSUE TITLE
Investigate stream polling failures

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#4689]
A user has observed that the stream polling feature (play button on stream) does not reliably return new events 100% of the time. If they click back to "Overview", then return to the stream, the new data they expect appears. The user understands that the polling is every minute, and observed the behavior by inspecting their browser's network graph.

**Comment by probc** [comment]
I noticed something interesting here.  In the network tab when i see the poll request occur it loads this url:

/issues/?sort=date&query=is%3Aunresolved&limit=25&statsPeriod=24h&shortIdLookup=1&cursor=0:0:1

which results in an empty response coming back.  If I remove the 'cursor=' parameter and execute another query manually it seems to work and the response comes back as expected, leading me to believe it would have refreshed the Issue tab properly as well.

/issues/?sort=date&query=is%3Aunresolved&limit=25&statsPeriod=24h&shortIdLookup=1

**Comment by probc** [comment]
Now that works is back to normal again, has there been any progress in resolving this issue?

Also, instead of a timed poll, could this be enhanced with the push via a websocket or something to get real-time updates?  When I code I like to keep the Sentry window open and when an issue happens I can see it right away during the front-end testing instead of having to wait a minute or so, or having to click the tabs to refresh the Sentry screen

**Comment by harveyr** [comment]
FWIW, I'm seeing this same issue, both on my hosted freebie account and an on-prem instance I just set up. The polling responses from the `/issues/` endpoint are empty arrays. When I mess with the `cursor` parameter, setting the timestamp back farther in time, eventually I get data in the response.

**Comment by wridgers** [comment]
I've been experiencing this issue.

I believe it's happens when the most recent issue is resolved - the next new issue will not make it through because there is an `OFFSET 1` in the query that skips it.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
