### ISSUE TITLE
Support sorting table widgets that have `session.status` columns in Dashboards

### ISSUE THREAD

**Issue by brentc** [getsentry/sentry#46891]
### Problem Statement

Currently you can't sort a table widget by column if `session.status` is one of the columns because of limitations to how we query the Session API.

Customers would like to be able to sort by `sum()` or other fields when building a Session Status table widget.

![image](https://user-images.githubusercontent.com/466158/229887186-7f11208b-ae74-4808-9db6-33dc6c2eff47.png)

**Comment by brentc** [comment]
We likely won't be working on this in the short-term, but we'll add it to the backlog to be prioritized in the future if we can identify the value having this would provide for our users.

**Comment by ale-cota** [comment]
We are prioritizing work based on company-wide initiatives, community demand, and activity on issues.
This issue only has no upvotes, has seen little activity, hasn't been touched recently. We're therefore closing it to keep our backlog maintainable and transparent. 

Please feel free to leave a comment if you think this issue should be reopened.
