### ISSUE TITLE
Favourite project not showing at the top

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#46931]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to issues page
2. Open the project selector menu.
3. Mark a project a Favourite/start

I was only able to reproduce it on a free or team plan, issue was not experienced on an organisation with Business plan.

Locking the project has no effect. In the screenshots below, apsnet-core project is part of teamA and the other 3 projects are part of teamB. However, the same behaviour happens when marking any other project as favourite.  

### Expected Result

As per: https://docs.sentry.io/product/projects/

> The projects are displayed in alphabetical order, separated by team. Note: For faster access, star your favorites to ensure they display at the top of the page each time you view.

The starred project is show at the top of the project list.

### Actual Result

Starred project is on the second line.

![Screenshot 2023-04-05 at 11 05 53](https://user-images.githubusercontent.com/64906376/230036712-75966fa0-293f-490f-8491-d27be4fddbdc.png)
![Screenshot 2023-04-05 at 11 05 45](https://user-images.githubusercontent.com/64906376/230036720-dcd05d29-39dd-4af1-8532-dcde13c5d722.png)

**Comment by vuluongj20** [comment]
I'm working on an updated version of the project selector (https://github.com/getsentry/sentry/issues/45074), which doesn't this issue.

**Comment by vuluongj20** [comment]
This has now been fixed following the release of https://github.com/getsentry/sentry/issues/45074
