### ISSUE TITLE
Public Alerts API so that alert rules can be defined and managed in code (IaC)

### ISSUE THREAD

**Issue by jazlalli** [getsentry/sentry#46940]
### Problem Statement

The only way to create or change alerts currently is via the UI. We want to be able to change/tweak rules, and create new ones, across different projects, in a way that is version controlled and captures history. An Alerts API feels like it would be the most viable option (this could then perhaps be incorporated into other tools such as Pulumi, which we already use).

Is an Alerts API on your roadmap, if so, please consider this an upvote.

If there is already some means by which this can be achieved, pls do let me know.

Thanks.

### Solution Brainstorm

Create a public Alerts API

**Comment by Dhrumil-Sentry** [comment]
Hi @jazlalli could you please give us some more details on what you'd like to change in existing alert rules programmatically?

**Comment by jazlalli** [comment]
Sure. 

I'd like to be able to control all aspects of an alert via an API, emulating anything you can do in the UI. Meaning...

- alert creation
- specifying conditions, filters, and actions
- action interval
- name and owner
- etc etc

Using browser devtools, I can see that when I save an alert rule, a request similar to that shown below is sent. I'm basically after a public, documented, supported API that I can use to manage all alerts across all of our projects. If the API had an SDK, that would be even better, but I'm willing to hand roll something if necessary, so long as an API exists and is relatively stable/well-supported.

Example request captured from devtools

```
PUT /api/0/projects/<company>/<project>/rules/13478608/?duplicateRule=false&wizardV3=true HTTP/1.1

{
    "id": "13478608",
    "conditions": [{
        "id": "sentry.rules.conditions.every_event.EveryEventCondition",
        "name": "The event occurs"
    }],
    "filters": [...],
    "actions": [...],
    "actionMatch": "all",
    "filterMatch": "all",
    "frequency": 60,
    "name": "Web Alerts",
    "dateCreated": "2023-01-17T17:38:19.402693Z",
    "owner": "???",
    "createdBy": {
        "id": ???,
        "name": "???",
        "email": "???"
    },
    "environment": "production",
    "projects": ["???"]
}
```

**Comment by Dhrumil-Sentry** [comment]
Thanks a lot for the feedback @jazlalli , I am adding this to our backlog and will update this issue once I have more details

**Comment by realkosty** [comment]
There's a Terraform provider for Sentry that can do it: https://registry.terraform.io/providers/jianyuan/sentry/latest/docs

**Comment by realkosty** [comment]
Duplicate earlier feature request for the same: https://github.com/getsentry/sentry/issues/36968

**Comment by ceorourke** [comment]
Docs for creating alerts are published here: https://docs.sentry.io/api/alerts/
