### ISSUE TITLE
Can't promote member to team admin despite being team admin myself

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/sentry#46950]
### Environment

SaaS (https://sentry.io/)

### Link

https://sentry.sentry.io/settings/teams/opensource/members/

### Steps to Reproduce

1. Be a team admin on [a team](https://sentry.sentry.io/settings/teams/opensource/members/).
2. Try to promote another team member to team admin.

### Expected Result

Can promote.

### Actual Result

Can't promote. Option is in a dropdown but can't select it.

<img width="886" alt="admin admin" src="https://user-images.githubusercontent.com/134455/230154076-fb0897e1-ca36-4f43-aa73-95919741e53a.png">

**Comment by leedongwei** [comment]
Good catch, thanks!

**Comment by chadwhitacre** [comment]
This still isn't working for me. (Afaict #47105 _is_ in prod, yes?)

**Comment by shellmayr** [comment]
Closing - this was fixed in https://github.com/getsentry/sentry/pull/47105 and has been verified to work.
