### ISSUE TITLE
On premise logs location, investigating 403 response from Sentry server.

### ISSUE THREAD

**Issue by tlvenn** [getsentry/sentry#4695]
Hi,

I am trying to investigate errors from sentry such as:

```
[raven-pool-1-thread-3] WARN  c.g.r.connection.AbstractConnection: An exception due to the connection occurred, a lockdown will be initiated.
com.getsentry.raven.connection.ConnectionException: {"error":"Event dropped due to filter"}
        at com.getsentry.raven.connection.HttpConnection.doSend(HttpConnection.java:157) ~[raven-7.8.1.jar:na]
        at com.getsentry.raven.connection.AbstractConnection.send(AbstractConnection.java:86) ~[raven-7.8.1.jar:na]
        at com.getsentry.raven.connection.AsyncConnection$EventSubmitter.run(AsyncConnection.java:164) [raven-7.8.1.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://sentry.mydomain.com/api/3/store/
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[na:1.8.0_111]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[na:1.8.0_111]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[na:1.8.0_111]
        at com.getsentry.raven.connection.HttpConnection.doSend(HttpConnection.java:149) ~[raven-7.8.1.jar:na]
        ... 5 common frames omitted
```

So I would like to understand why the sentry server is responding with a `403` and I was thinking that the sentry logs would have some clue. Issue is, I can't figure out where the logs are and it does not seem to be documented either.

Thanks in advance.

**Comment by mattrobenolt** [comment]
We don't log why the event was filtered, so that won't help. But this is due to a set of Inbound Data Filters. We have a baseline of stuff to filter out noise, but they can be disabled in your project's settings.

**Comment by tlvenn** [comment]
Hi @mattrobenolt , the thing is I dont have any filters but the `Filter out known web crawlers` activated so I am not sure why the server is emitting those 403... And i got a lot of them...

Our of curiosity and for my understanding, what is the location of the sentry logs ?

Thanks !

**Comment by mattrobenolt** [comment]
My guess then is you're hitting that filter. You should try disabling them all and see if you still get filtered.

And logs are just dumped to stderr/stdout. We don't do anything special to write to files.

**Comment by cruftex** [comment]
> But this is due to a set of Inbound Data Filters.

@mattrobenolt : If this is the case, why is the issue closed? The exception and error message

> "An exception due to the connection occurred, a lockdown will be initiated."

Clearly indicates that bad things are going on. Either bad things are going on or the message is misleading, both, IMHO, is a valid issue that needs to get solved.

**Comment by mattrobenolt** [comment]
@bretthoerner I’m not sure if Java is being overly conservative here about backing off on 403s or norm.

**Comment by bretthoerner** [comment]
We backoff for non-2XXs, if 403 is expected and we shouldn't backoff then that can be changed in `sentry-java`. I'd say make an issue there if you think that's the case @cruftex?

**Comment by bretthoerner** [comment]
I'm actually back at my computer, so made the issue that I'll check out soon: https://github.com/getsentry/sentry-java/issues/452

**Comment by cruftex** [comment]
@bretthoerner, @mattrobenolt: Many thanks for looking into this!

According to https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors 403 is defined as:

> 403 Forbidden
> The request was valid, but the server is refusing action. The user might not have the necessary  permissions for a resource, or may need an account of some sort.

Since the 403 could also come from a HTTP gateway it is not a good idea to change the behavior in `sentry-java` and ignore them somehow. I don't see how to differentiate between a bad 403, because of a misconfigured gateway and a "usual" 403 because of a event is filtered.

When the event is filtered, it is actually received and processed properly; at least from the perspective of the sending client. Why return an error?

**Comment by mattrobenolt** [comment]
When we return a 403 in this case, we don’t process it. We reject it before it’s stored, therefore we’re signaling this behavior.

**Comment by cruftex** [comment]
Please use HTTP status the way the standard defines it. The 4xx status codes are intended for responses that indicate that the client sent a wrong request. This causes quite a confusion.

Why return an error? In my line of thinking an error means something is wrong and needs to be corrected.

**Comment by dcramer** [comment]
We know HTTP plenty well, but thank you for your input.
