### ISSUE TITLE
docs.sentry.io is not updated after a new release. 

### ISSUE THREAD

**Issue by fredvd** [getsentry/sentry#4697]
Sentry 8.11 was released 19 days ago according to the github tag, but docs.sentry.io still has documentation from before that.

https://docs.sentry.io/server/changelog/  for example still has version 8.11 (unreleased).

**Comment by dcramer** [comment]
This definitely would be good to add to the release checklist /cc @mattrobenolt 

I'm going to push out the latest version of the docs now.
