### ISSUE TITLE
 The configure sdk screen is empty when creating a project

### ISSUE THREAD

**Issue by onepredict-lbm** [getsentry/sentry#46993]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.4.0.dev0

### Steps to Reproduce

1. “I installed Sentry self-hosted and installed Sentry by running the install.sh script and docker compose up -d”
2. "After installation, I created a project and the configure sdk screen was empty”
3. “I removed everything related to Sentry with docker compose down --volumes and docker volume rm and reinstalled it, but this problem still occurred”

### Expected Result

 “Currently the sdk screen is empty. In another environment installed with the same version, the sdk configure screen appears correctly”
 "Currently the example is ios, but this phenomenon occurs in all languages"

### Actual Result

![image](https://user-images.githubusercontent.com/127291063/230254397-13cc7544-f37c-4b0b-abca-0d9fbab4a977.png)

**Comment by hubertdeng123** [comment]
The appropriate team is aware of this issue. Thanks for bringing this up.

**Comment by hubertdeng123** [comment]
looks like you also created an issue in the self-hosted repo, since this fix will be in `getsentry/sentry`, going to close that one as a duplicate

**Comment by priscilawebdev** [comment]
@onepredict-lbm thanks for reporting this issue. It will be fixed in the PR https://github.com/getsentry/sentry/pull/47078 😉

**Comment by priscilawebdev** [comment]
PR was merged, so the issue shall be fixed now
