### ISSUE TITLE
Metric Alert Fixes

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#47004]
**Problem**: When creating alerts based on Performance metrics, we only support a [limited list of filters](https://docs.sentry.io/product/alerts/create-alerts/metric-alert-config/#tags--properties).

**Solution**: Notify the user when they're trying to use an unsupported tag/property and teach them which ones are.

**Acceptance Criteria**:
- replace the current copy in the helper text with "The field * is not supported for performance alerts. See all searchable properties in the docs."
- update the link to the docs to point [here](https://docs.sentry.io/product/alerts/create-alerts/metric-alert-config/#tags--properties)
- when there is an unsupported parameter in the query, we render an empty chart a warning that reads "Your filter conditions contain an unsupported field - please review."

![Image](https://user-images.githubusercontent.com/26696515/230627726-c070f833-b5bc-4aeb-ab04-2620578b9364.png)

**Comment by matejminar** [comment]
How about we render empty chart with note "unsupported query" (but nicer).
