### ISSUE TITLE
Hide SDK Updates

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#47001]
Based on a lot of internal feedback, the existing SDK Updates in the product need to be hidden. They are noisy, and people just start ignoring them. There needs to be a plan to approach this more holistically. Possibly Issue Experience will be working on it.

Employees only: More context [here.](https://sentry.slack.com/archives/CA2V2LBDL/p1680712410099249)

- [x] remove from What's new sidebar
- [x] remove from project details

**Comment by priscilawebdev** [comment]
remove it from issue details?
