### ISSUE TITLE
Dashboards with indexed metrics warning

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#47006]
**Problem**: Dashboard widgets based on Performance metrics are sometimes based on processed events and sometimes based on indexed events, but the user is not informed. When incompatible filters actually applied, we fall back to the events dataset and only show values based on those and not total events.

**Solution**: Notify the user when that is the case. 

**Acceptance Criteria:**
- Add triangle warning sign and tooltip to widget
![Image](https://user-images.githubusercontent.com/26696515/230352769-aa3418d8-a43b-43f2-be68-6269d9bd4857.png)
- Update copy in the tooltip to say “Based on your search criteria, the sampled events available may be limited and may not be representative of all events.”

Requires https://github.com/getsentry/sentry/issues/48633

**Comment by ale-cota** [comment]
Original Jira ticket from the Perf team: https://getsentry.atlassian.net/browse/PERF-2035

**Comment by matejminar** [comment]
This was already done, but we had to revert it because of https://sentry.slack.com/archives/CTZCE4WBZ/p1681900832617979?thread_ts=1681741202.138949&cid=CTZCE4WBZ

**Comment by ale-cota** [comment]
This issue is blocked for now because we need the Discover API to be adapted to return the event type, so that we can show the warning only in case of queries on Transactions and not in case of queries on Errors.
