### ISSUE TITLE
[EPIC] AI Suggest

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#47014]
### Problem/Opportunity:

We want to enable customers to better understand what the issue is about they are on and what they could do to resolve it.

### Solution:

The opportunity here is to ride the popularity of ChatGPT a bit so this feature is intentionally tongue in cheek. A button is added to the UI which sends an export of the event to openai for analysis.

For customers with a signed DPA or an invoiced account a prompt is added to ask them to sign a DPA addendum ([Subprocessor Acknowledgement](https://docs.google.com/document/d/1_vW8S1vwIyV_lKy7Qd0cet4FQ-TBvKE-LwFUAZlERvE/edit)). For others a popup is presented that asks for confirmation to send data to a third party.

Once clicked the response is generated and shown in an accordion folding down from the top of the event page.

### Acceptance Criteria:

- The user has to click an explicit CTA in order to receive the suggestion (we pay per API call)

- For customers with a signed DPA or an invoiced account a prompt is added to ask them to sign a DPA addendum ([OpenAI Subprocessor Acknowledgement](https://docs.google.com/document/d/1_vW8S1vwIyV_lKy7Qd0cet4FQ-TBvKE-LwFUAZlERvE/edit)). Only Org admins can agree to this.

  - If the user is an org admin

    - This is displayed until one org admin agrees to it and then never again (needs a back-end check probably to know whether this was already signed or not)

    - The user is taken to the Compliance and Privacy Documents page to sign the DPA Addendum.

  - If the user is not an org admin

    - Display a dialogue that tells them to talk to their admin. (Compliance and Privacy Documents)

    - Non-admins can’t see this page if they just navigate to the settings

    - If they are on the pop-up they can be navigated by us there with the notification that they don’t have the right to sign it. 

  - Text is provided by Legal - [OpenAI Subprocessor Acknowledgement](https://docs.google.com/document/d/1_vW8S1vwIyV_lKy7Qd0cet4FQ-TBvKE-LwFUAZlERvE/edit)

- For customers without a signed DPA (higher Priority)

  - we present the user with a dialogue that asks for confirmation to send data to a third party.

  - we need to remember this per user (remember it in local storage)

  - Text will come from Legal

- Once clicked the response is generated and shown in an accordion folding down from the top of the event page.

  - The user should be able to collapse the accordion.

- We keep the response cached for 5 minutes and can use it to display it to any users.

- The element doesn’t disrupt the rest of the issue details page (you can still scroll up and down).

- We need to show that this is experimental/might go away at any time (there’s a new badge in the component library).

**Comment by BiaDd** [comment]
Hi, is this epic still open? If so, I'd be interested in helping out with it

**Comment by matejminar** [comment]
Hi @BiaDd , all done - hope you'll like it :)
https://docs.sentry.io/product/issues/issue-details/ai-suggested-solution/
