### ISSUE TITLE
Unable to change slowDB query threshold

### ISSUE THREAD

**Issue by adort-doc** [getsentry/sentry#47020]
### Problem Statement

I was tasked with increasing our threshold for slow DB queries, as the current 1-second threshold is too strict for our use cases. I created a script to address this since there isn't a global setting. However, I realized that there isn't any way (at least not documented) to determine if an event was marked as a slow DB query. This prevents me from adding a manual filter to stop these events from being sent.

Currently, the most I could do was read the execution times of the SQL breadcrumbs, but this approach risks accidentally filtering out other events that Sentry would mark as something other than a slow DB query.

### Solution Brainstorm

Add a property or flag to events marked as slow DB queries, which will allow users to easily filter them in their application.
This way they can prevent it from getting logged to Sentry when it is not needed / filling too much of the quota

**Comment by DominikB2014** [comment]
Hey @adort-doc! I'm going to close this issue. 
You can now adjust the slow db query threshold, its a project level setting under performance ( ie
`settings/projects/{PROJECT_NAME}/performance/`). If there's some additional behaviour you'd expect, feel free to open a new issue.
