### ISSUE TITLE
Setting up Metric Alerts with multiple metrics 

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry#47052]
### Problem Statement

Our team wants to set up a metric alert that factors in 2 metrics: 
- Transaction Duration 
- Throughput (tpm) 

Scenario is that during night hours, we have small number of users overall, so just few outliers can trigger alerts.

### Solution Brainstorm

Ability to factor in multiple metrics. Transaction Duration && Throughput

**Comment by brianthi** [comment]
Hey @dachakra, unfortunately this would take significant investment in our metric alert infrastructure to be able to support, and it's not an ask that has come up very frequently.  Will share this with Eran for visibility, but closing this as it's very unlikely we'll take something like this on in the future.
