### ISSUE TITLE
Handle OpenAI RateLimit

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry#47063]
For the suggested fix feature that we recently enabled for early adopters customers, we are using the [OpenAI API ](https://github.com/getsentry/sentry/blob/cc5289031912bac290dca7d910910423c2988b62/src/sentry/api/endpoints/event_ai_suggested_fix.py#L250) for the suggestions.

Sentry makes use of a [RateLimit and we have that on the endpoint we are currently using](https://github.com/getsentry/sentry/blob/cc5289031912bac290dca7d910910423c2988b62/src/sentry/api/endpoints/event_ai_suggested_fix.py#L268-L275), but we are not dealing with the [RateLimit that OpenAI also uses](https://platform.openai.com/docs/guides/rate-limits) and this is causing[ Sentry to get some errors regarding this](https://sentry.my.sentry.io/organizations/sentry/issues/394060/?project=2&referrer=slack).

**Acceptance Criteria:**

- Wrap the openAI request with some sort of try...catch or similar and check if it will return the error code `429`, id yes, return the response with this code too

**Comment by r3alst** [comment]
Hello @andriisoldatenko @priscilawebdev ,

Can I contribute to this issue? If it still pending.
