### ISSUE TITLE
Crons: error with the monitor slug in the context does not show up in monitor details page

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#47086]
### Steps to Reproduce

1. Catch an exception with the monitor slug in the context:
```
Sentry.captureException(e, {
  contexts: {
    monitor: {
      slug: 'my-monitor-slug',
    },
  },
});
```
2. Go to the monitor details overview page.
3. The exception will not show up under "related issues".

### Expected Result

The exception to show up in the monitor issues page.

**Comment by evanpurkhiser** [comment]
The issue here is we can't query on both guid (id) and slug, and since we haven't been correctly creating checkins with slugs if we swap it over we'll not see all the old errors.

**Comment by evanpurkhiser** [comment]
We'll need to fix https://github.com/getsentry/sentry/issues/47119 first before we can fix this
