### ISSUE TITLE
issue  with notifications page

### ISSUE THREAD

**Issue by aliva** [getsentry/sentry#4709]
we are using sentry on our servers (self hosted installed with virtualenv/postgres/redis) (Sentry 8.11.0)

issue is on account -> notifications (the page that user can choose if they want to receive email or not)

I have attached an screenshot:

![shot](https://cloud.githubusercontent.com/assets/359286/21471321/87f98bf4-cac3-11e6-83d9-ed97334ca3ce.png)

what is the problem with this page :-|

**Comment by dcramer** [comment]
Either:

1. You're manually injecting something invalid in the DB
2. Somehow JS is partially disabled
3. I have no idea

I'm closing this though as without more information there's nothing we can do, and this is working fine in production for us.
