### ISSUE TITLE
sentry can not group same exception

### ISSUE THREAD

**Issue by mbande** [getsentry/sentry#4710]
i'm using sentry 8.10.0 with raven 5.23.0 in a python 3 project.
somewhere i use python requests to do some post, and when the destination server is down i see many many same exception:
```
HTTPConnectionPool(host='192.168.11.11', port=8080): Max retries exceeded with url: /query (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fc125df5940>: Failed to establish a new connection: [Errno 111] Connection refused',))
```
as all of them happening in the same module with same stack trace, why sentry can not detect that they are same? how could i help sentry to aggregate them

**Comment by dcramer** [comment]
The stacktraces are certainly different or it would group together. If you wish to provide the stacks I can confirm that, but it's absolutely guaranteed that if the stacks are identical, and the exception class is identical, that Sentry will always group them together.

**Comment by mbande** [comment]
@dcramer as far as I can see, the event pages are identical, same message, same logger
what should i provide from event page other than the message that i provided?

**Comment by dcramer** [comment]
The message is not what we group on -- the stacktrace is. I'm 100% confident that the stacktrace is not identical though, as there is no condition per my statement above that would cause them to not group. The question is, why is the stacktrace different?

**Comment by mbande** [comment]
how can i investigate that? is the full stack trace logged in the sentry event? or i should do a custom logging for that?

**Comment by dcramer** [comment]
@mbande is there no stacktrace with it? how are you capturing the exception? if its using ``captureException`` it should include a stacktrace, which is primarily how we group things.

**Comment by mbande** [comment]
@dcramer i use django logging as specified in [docs](https://docs.sentry.io/clients/python/integrations/django/#integration-with-logging)

**Comment by dcramer** [comment]
@mbande so if you're logging things, then you're stuck with wahtever the result is. For example, if you're just doing log.info('foo bar') its going to be pretty shitty. It's important to remember Sentry is diff than logging, and it needs a lot of metadata. If in this case you're logging an exception, make sure you use ``exc_info=True`` or logging.exception to capture it.

**Comment by mbande** [comment]
thank you @dcramer , i will use logging.exception to include stacktrace
