### ISSUE TITLE
Conditionally send View Hierarchies to Sentry with certain events

### ISSUE THREAD

**Issue by michaelchai-sentry** [getsentry/sentry#47108]
### Problem Statement

A user reported that they would only like to send View Hierarchies for events of a certain level (i.e. only fatal events). Right now, it is a opt-in feature that allow only allows you to set it to true/false. The reasoning behind wanting this is to reduce the overhead of data sent, and that they want to cut down the noise and are only interested in View Hierarchies for certain events.

### Solution Brainstorm

Add some conditional logic to this feature, such as the before send callback

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1803) by [Unito](https://www.unito.io)

**Comment by mattjohnsonpint** [comment]
The user should be able to adjust this in `beforeSend`.  Which SDK are they using?

**Comment by marandaneto** [comment]
@michaelchai-sentry which platform does the user have set up?

**Comment by brustolin** [comment]
On Cocoa this problem will be solved with https://github.com/getsentry/sentry-cocoa/issues/3007

**Comment by marandaneto** [comment]
Other platforms already support the filtering of view hierarchies and screenshots via `beforeSend` and `Hints`, only iOS is pending but there's already a ticket open https://github.com/getsentry/sentry-cocoa/issues/3007
Closing this one.
