### ISSUE TITLE
change SENTRY_GRAVATAR_BASE_URL has no effect on some pages

### ISSUE THREAD

**Issue by AyumuKasuga** [getsentry/sentry#4711]
- The version of Sentry you're using
8.11.0
- Whether you're using Docker or another installation method
from pip

Hello! I use custom `SENTRY_GRAVATAR_BASE_URL` option. And on most of pages avatars still download from `secure.gravatar.com` domain. For example on team members page `/organizations/intdev/teams/sentry/members/`. I am not sure, but maybe it because of url hardcoded in [this](https://github.com/getsentry/sentry/blob/839ae421fe8989ee0b209cb29ab66a4602ac0c46/src/sentry/static/sentry/app/components/avatar.jsx#L31) place?

**Comment by AyumuKasuga** [comment]
Guys?

**Comment by mattrobenolt** [comment]
I can look at this today quickly.

**Comment by mattrobenolt** [comment]
Yeah, can confirm. Should be easy patch.

**Comment by AyumuKasuga** [comment]
@mattrobenolt thank you!
