### ISSUE TITLE
Additional customization for native crash report storage

### ISSUE THREAD

**Issue by dgbailey** [getsentry/sentry#47114]
### Problem Statement

Currently the product allows you to [specify a limit per issue for storing native crash reports](https://docs.sentry.io/platforms/native/guides/minidumps/enriching-events/attachments/#enabling-crash-report-storage). 

Customers have feedback around this feature:

> If it is an issue that has sat around for one or two releases, we want to be able to debug this on the current release of the executable. We don’t want to have to roll back code and installed executables to the older version just to unwind the stack. When we saturate the limit of X mini dumps per issue this can result in less efficient workflows.

> Not everyone has the ability to delete crash reports. This results in other inefficiencies where someone has to get permissions to delete dumps just to let some through from the latest release.

> Strategy of keeping the oldest - makes sense not having the sand shift as you are triaging, during development. However what is causing new things to happen & why are we still seeing this issue is also important.

### Solution Brainstorm

1. Let one or two mini dumps cycle through per day. 
2. Default to storing first 5 & latest 5 per issue if the limit is 10. 
3. Configurable levers around the composition of stored crash reports. (e.g. thresholds per version)

**Comment by ashwoods** [comment]
@dgbailey Thanks for feedback! Once a minidump is processed it will already count towards the quota limit, no matter how long it sticks around, so cycling would defeat the purpose, but we will look into more configurable ways of limiting. For events that are not sparse, as a workaround, you can delete all the minidump associated with an issue and newer ones should roll in.
