### ISSUE TITLE
Implement: Adjust intensity of rebalancing 

### ISSUE THREAD

**Issue by RaduW** [getsentry/sentry#47141]
### Problem Statement

Add the algorithm we came up in https://github.com/getsentry/sentry/issues/46768 to adjust both the
transaction and project rebalancing.

We would need two options, one for project and one for transaction that control how aggressive the algorithm is in rebalancing the items. 
**TODO:** Decide if the options are global or per org ( I think global would be the way to go).

**Comment by matejminar** [comment]
@RaduW Here's an example of how to register and use global options:
https://github.com/getsentry/sentry/issues/47988

**Comment by RaduW** [comment]
Implemented in : https://github.com/getsentry/sentry/pull/48336
