### ISSUE TITLE
Slack Integration Problem

### ISSUE THREAD

**Issue by theboyisno-one** [getsentry/sentry#47144]
### Environment

SaaS (https://sentry.io/)

### Version

22.3.0 08d452b (helm)

### Link

N/A

### DSN

N/A

### Steps to Reproduce

1. Goto settings -> integrations -> slack 
2. Try to add another workspace by clicking on Add Workspace button.
3. It will redirect to integration URL for very first workspace only.

### Expected Result

We should be able to integrate multiple slack workspace using UI

### Actual Result

UI not allowing multiple slack workspace integration

**Comment by JLuse** [comment]
Yes, please submit a support ticket where exactly you're running into this in Sentry.

**Comment by theboyisno-one** [comment]
@NisanthanNanthakumar  @JLuse  this is self-hosted sentry. How can I create a support ticket?

**Comment by hubertdeng123** [comment]
If I'm looking at this properly, you're using the helm charts version of self-hosted Sentry, not our officially support docker-compose setup?
