### ISSUE TITLE
8.11.0 source maps are not found in any release

### ISSUE THREAD

**Issue by vojtatranta** [getsentry/sentry#4718]
Hi all,
thank for your work on this great product, however we experience troubles.

Version: `8.11.0`
```
Source code was not found for avocode.min.js Collapse
{
  "url": "avocode.min.js"
}
```

After update to `8.11.0` source maps and source files are not found anymore.

Even when I try older version of our app and create a uncaught exception, Sentry is not able to locate the source files. Even repeated event comes to sentry as a new one without matched source maps.

We are using `raven-js@^3.4.0` but we even tried latest version without any difference...

Any ideas what may caused this? Have we missed some upgrade notes?

**Comment by dcramer** [comment]
@vojtatranta if its saying its not found they're either:

- not available on disk
- not uploaded correctly (pinned to the correct release/named appropriately)

**Comment by mattrobenolt** [comment]
Are you saying it did work correctly on 8.10.0 and is now not working after upgrading?

**Comment by mitsuhiko** [comment]
What was the old version you were using and can you share the filenames you are uploading as?

**Comment by vojtatranta** [comment]
Then you all for your swift reaction! That's a great user experience!

@dcramer thank you for this quick report.

But these are wrong suggestions. As I wrote. Even older release are not working. When I invoke an error in the older release (where source mapping worked) sentry receives a new event (does not pair it with it's older counterpart) and outputs an error which says that it could not locate the source files.

Yes it does not work after an update (I'll try to find out which version we had before but it was the one "before the redesign"). Except sentry version, nothing has changed. 

Of course I tried all the "typical" problems I found around on the internet...

Sure names are correct, not changed across all the sentry versions we've used - is this form enough?:
![snimek obrazovky 2017-01-03 v 19 26 04](https://cloud.githubusercontent.com/assets/4154045/21618309/96fdef04-d1ea-11e6-88c4-0e42b2d90947.png)

**Comment by mitsuhiko** [comment]
@vojtatranta just to make sure: you did not accidentally store the files in a docker container but on a mounted volume? Because if they were in the container and you made a new one, they are lost.

**Comment by vojtatranta** [comment]
@mitsuhiko no, that is not the issue. I even tried to reupload all those files again, to make sure they are present, but no luck...

**Comment by mitsuhiko** [comment]
The correct filenames for uploaded files *should* be `~/filename.min.js` instead of `filename.min.js` for normal apps. I'm surprised this worked before since we always match on full URLs. This should make it work for you but I will investigate if this might have worked by accident before. Is this by any chance from an electron or react native app?

**Comment by vojtatranta** [comment]
To fill the info we upgraded from `8.8`.

@mitsuhiko it is Electron app.

Well, I think the path `filename.min.js` is also a path, isn't it? But give me a sec I try the solution you suggest.

**Comment by vojtatranta** [comment]
I can even send you the payload of the event that is sent to Sentry.

Alright I tried your solution, but no luck so far, this is the settings:
<img width="796" alt="snimek obrazovky 2017-01-03 v 20 37 14" src="https://cloud.githubusercontent.com/assets/4154045/21620419/86bb6450-d1f4-11e6-921a-f416672a6120.png">

<img width="567" alt="snimek obrazovky 2017-01-03 v 20 37 31" src="https://cloud.githubusercontent.com/assets/4154045/21620424/8b9a9b58-d1f4-11e6-9200-438737ebf9cb.png">

**Comment by mitsuhiko** [comment]
Hey, quick question. Are you using a custom dataCallback that changes something? If yes, can you share it?

**Comment by vojtatranta** [comment]
@mitsuhiko sure.

basically the result is `avocode.min.js`. I tried to make it `~/avocode.min.js` but no difference...

```
dataCallback: (data) ->
        if data.exception
          data.exception.values[0]?.stacktrace?.frames?.forEach (frame) ->
            filenameParts = frame.filename.split('/')
            normalizedName = filenameParts[filenameParts.length - 1]
            frame.filename = normalizedName
          data.culprit = data.exception.values[0].stacktrace.frames[0].filename
```

**Comment by dcramer** [comment]
To be clear, are these pre-existing issues or are you re-sending them? We wont reprocess any existing issues when sourcemaps are added -- it only happens if they're present at the time the event is received.

**Comment by vojtatranta** [comment]
@dcramer yeah I am aware of it. Don't worry.

**Comment by mitsuhiko** [comment]
@vojtatranta yeah, was almost expecting this. The way we match paths is by URL where we definitely support these modes:

* full url -> full url (eg: http://example.com/foo.js -> http://example.com/foo.js)
* absolute path -> absolute path (/foo.js -> /foo.js)
* full url -> wildcard url (http://example.com/foo.js ~/foo.js)

Relative paths I'm investigating right now. I was not aware we support(ed?) this and there is at least one unrelated bug with this.

In theory if you change your dataCallback to set the filename to something like `'/' + normalizedName` and then upload the files as `/filename.min.js` and co this *should* work.

**Comment by vojtatranta** [comment]
@mitsuhiko oukej, I'll give it a try - basically if I reference it in the html like this `./dist/avocode.min.js` - this should be also `filename` and the `culprit` should be also the same, right?

**Comment by mitsuhiko** [comment]
@vojtatranta it does not matter what filename you reference it in html with. What matters is the filename that is transmitted to the server. Normally that is a full URL but because electron is not using full URLs you are sending it modified in the `dataCallback`. There however it's split down to something that is not at all a URL any more.

So if you send it with a leading slash there it should at least not cause problems with the behavior on the server which can deal with absolute paths. The culprit you don't actually need to send at all I believe.

So effectively you will then need to upload the file as `/avocode.min.js` which is what that modified data callback will report:

```coffee
      dataCallback: (data) ->
        if data.exception
          data.exception.values[0]?.stacktrace?.frames?.forEach (frame) ->
            filenameParts = frame.filename.split('/')
            normalizedName = filenameParts[filenameParts.length - 1]
            frame.filename = '/' + normalizedName
```

**Comment by vojtatranta** [comment]
@mitsuhiko OK, I'll try it, thanks. I'll be back in a sec.

**Comment by vojtatranta** [comment]
Right, so I tried it with this config:
`culprit: "/avocode.min.js"`
Artifacts:
<img width="382" alt="snimek obrazovky 2017-01-03 v 21 44 30" src="https://cloud.githubusercontent.com/assets/4154045/21622465/dad697e0-d1fd-11e6-82ed-f14f2040608a.png">

And still the same - but I noticed that url param in the error message is without a slash at the beginning:

<img width="558" alt="snimek obrazovky 2017-01-03 v 21 45 05" src="https://cloud.githubusercontent.com/assets/4154045/21622483/ff5f44e0-d1fd-11e6-8ebe-b3446a6be8cc.png">

**Comment by dcramer** [comment]
@vojtatranta culprit doesnt do anything here -- it looks at each frame in the stacktrace and takes frame.abs_path and tries to map it up to a release artifact

**Comment by vojtatranta** [comment]
@dcramer gosh. I see I screwed up. Give me a sec...

**Comment by vojtatranta** [comment]
@dcramer Yes!! Thank you @mitsuhiko

It works now! I had to add `'/' + filename` great!

Resolved!

**Comment by mitsuhiko** [comment]
Going to close this in favor of #4719
