### ISSUE TITLE
So I'm using debug IDs, but Issue Details is telling me to setup Releases

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#47229]
### Problem
When any `in-app` frame within a given stack trace isn't solved, irrespective of SDK version, we tell the user to set up releases. This is an issue because with the introduction of artifact bundles and debug IDs, a user is more likely to resolve their source map issues with debug IDs than releases.

![Screenshot of current experience](https://user-images.githubusercontent.com/6508377/229151835-2654e09a-5698-48f2-bea4-1f1c17bd3e8a.png)

### Acceptance Criteria
If an event has unresolved `in-app` stack frames, we show the below message and direct them to the [uploading source map docs page](https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/uploading/)

```
No artifacts uploaded
Take advantage of our bundler plugins or the sentry-cli tool to easily upload source maps to Sentry.
```

### Design
Userflow can be found [here](https://www.figma.com/file/Mplyw96iZEnsoTWwQZDcwb/Exploration%3A-Issue-Experience-%2F-Artifact-Bundles?node-id=75%3A629&t=2oXmLD1bneegUCjz-1)

![Design](https://user-images.githubusercontent.com/6508377/234527117-1c8c9700-5fbe-4b35-99b2-b334d65057dd.png)

### Ticket blocked by
https://github.com/getsentry/sentry/issues/47968

**Comment by hubertdeng123** [comment]
@Jesse-Box The bot will only allow you to use one label if an issue is untriaged

**Comment by Jesse-Box** [comment]
Thanks for the heads up @hubertdeng123 !

**Comment by lforst** [comment]
Since we removed these alerts we can close this. https://github.com/getsentry/sentry/issues/55662 works on giving users proper feedback on their source maps setups.
