### ISSUE TITLE
Worker failing with `sentry.errors.events: preprocess.failed.empty`

### ISSUE THREAD

**Issue by kayone** [getsentry/sentry#4722]
Sentry 8.12.0, using the official docker container, 

everything seemed to be working fine, but then all of the sudden sentry started reporting the new issues in the dashboard, clients get 200 when reporting and I can see the reports come in, but the worker fails to process them, I'm not sure if it's related or not, but things seemed to have gone wrong once I added custom `fingerprint` to one of our clients. 

![image](https://cloud.githubusercontent.com/assets/412280/21670540/c3c11784-d2c9-11e6-8d71-9e3506ba6c86.png)

you can see the big drop at the end, and it's happening for all projects even some that haven't been updated recently. 

looking at the worker log I see constant, 

```
06:02:07 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key='e:d817b41584824f3ea017a543c2e34bf0:8')
06:02:07 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key='e:69291860bf5649f497d194254a426dd1:8')
06:02:07 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key='e:9ccef557e05f48c0a41c4536fb0c4294:8')
06:02:07 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key='e:6886f587400e4c38802d37445f735b85:8')
06:02:07 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key='e:ef796b8ab129405f8e263fdff87d138d:8')
06:02:08 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key='e:115a5aedb8de4561bdfdd42b7ae0cf27:8')
06:02:08 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key='e:aad17301ad5c41ccb00b722554baca6d:8')
06:02:08 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key='e:781a99a3f2204cf89b4c68efba2b37db:8')
06:02:08 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key='e:9103660875544666bdc84ff80b926c5b:8')
06:02:08 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key='e:5046b33cd0b54d04b639e71e6e6cb4c2:8')
06:02:08 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key='e:51f2a1ef29e6407391461f2a44ce2073:8')
06:02:08 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key='e:5eb78c5498f04a20b9b9ee06772000cb:8')
06:02:08 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key='e:2e563ae0fdd54d878d4e518808d029fe:8')
06:02:09 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key='e:fa8cb44c724e4a518958b677929b10b6:8')
06:02:09 [ERROR] sentry.errors.events: preprocess.failed.empty (cache_key='e:28fd83a610c249c898264bbb0a73725f:8')
```

I would really appreciate any help.

**Comment by dcramer** [comment]
This means that it cannot find the blob in the cache. That can mean a number of things like:

- it expired
- the cache is completely bricked
- some other obscure config issue

That said, issue tracker is reserved for code flaws, so if you still need help I encourage you to look at our support forum.
