### ISSUE TITLE
So I'm using debug IDs, but Sentry CLI is telling me to setup Releases

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#47227]
### Problem
When any `in-app` frame within a given stack trace isn't solved, irrespective of SDK version, the command `sourcemap explain` will tell the user to set up releases. This is an issue because with the introduction of artifact bundles and debug IDs, a user is more likely to resolve their source map issues with debug IDs than releases.

### Acceptance Criteria
If an event `sdk.version` is  `>=` `7.44.0` and has unresolved `in-app` stack frames, we print the following message to the user

```bash
sentry-cli sourcemaps explain XXXXXXXXXXXXXXXXXXXXXXX
Fetched data for event: XXXXXXXXXXXXXXXXXXXXXXX
Event is missing a debug-ids
Inject debug IDs into your applications build artifacts and upload them using sentry-cli or our bundler plugins
https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/uploading/cli/
https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/uploading/
```

### Design
Userflow can be found [here](https://www.figma.com/file/Mplyw96iZEnsoTWwQZDcwb/Exploration%3A-Issue-Experience-%2F-Artifact-Bundles?node-id=0%3A1&t=5lutB8V6edRcryoz-1)

### Ticket Inspiration
https://github.com/getsentry/sentry/issues/47968

**Comment by loewenheim** [comment]
This is blocked by https://github.com/getsentry/sentry-cli/issues/1601.
