### ISSUE TITLE
Stack Frame Reprocessing Support from Multiple Processors

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#4723]
As I'm trying to add reprocessing it becomes more and more obvious that the way we currently process stacktraces is not ideal.

In particular the example I care about is react-native which needs two processors:

* sourcemaps for JS
* symbolication for native frames

Right now if processing fails in a processor it can emit a raw stacktrace. Now however it brings up all kinds of weird issues if both processors run and one fails or the other. Additionally we have so many places now where stacktraces exist that the existing interface internally makes things very messy.

I'm not sure what the solution is yet but I think a general plugin method that returns stackframe processors might be useful which takes a stacktrace and then returns a processed one or indicates an error. Then the code that invokes it can figure out raw stacktraces, chaining and other things.

This will also greatly aid reprocessing however there are more ongoing issues with it.

Related issues:

* #4599 for reprocessing
* #4657 for pro-guard support which is a new backend which adds to the same issue

**Comment by HazAT** [comment]
So what would be the optimal way to solve this ... if we would have no implications ...
My knowledge about the whole system is still limited but as far as I understood it ... 

- Events should always keep the raw data (immutable) which was sent from a client
- An Event can go through one or more mutators/reducers to process it and display it accordingly for the language/framework the Event is about
- An Event can be marked for reprocessing (if processing fails or whatever) which will delete the old event, creates a new one with the same raw data and sends it through all the mutators again

**Comment by mitsuhiko** [comment]
Since keeping the raw data in all cases would be too expensive we currently modify it right away. Ideally we can keep at least parts of that data until processing finishes.

**Comment by mitsuhiko** [comment]
This is done now.
