### ISSUE TITLE
[Linear] Linking Linear issue spins forever

### ISSUE THREAD

**Issue by scnerd** [getsentry/sentry#47254]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Prereqs: Linear integration successfully set up and working.

1. Open issue on Sentry
2. Click on "Linear Issue +" (Often, first click doesn't work and the modal disappears immediately; if so, try again)
3. Click the "Link" tab
4. Start typing a search term for a known ticket

### Expected Result

Ticket shows up, and I can click it to link the ticket to the Sentry issue. Up until a few days ago, this worked perfectly.

### Actual Result

Spinner spins forever, no results populate.

Opening the network panel, I see my typing generate a request to `.../api/0/sentry-app-installations/23b24b9d-3b0b-44c3-bea4-0beca8669beb/external-requests/?projectId=4504046214840320&query=uk&uri=%2Fhooks%2Fsentry%2Fissues%2Fsearch`, which errors with a 400 response that just says `{"error":"Error communicating with Sentry App service"}`.

Tried:
- Refreshing
- Different browsers (firefox+chrome)
- Re-installing Linear integration
- Different Sentry issues and ticket search terms

**Comment by scnerd** [comment]
Additional detail: Creating new tickets works fine, only searching for existing tickets is broken.

**Comment by scttcper** [comment]
I'm seeing a lot of 500's from linear `https://api.linear.app/hooks/sentry/issues/search` endpoint. It looks like something might have changed on their end. If you could escalate this with their support. The installation id you provided might also help `23b24b9d-3b0b-44c3-bea4-0beca8669beb`

**Comment by scnerd** [comment]
Received a notification from the Linear team that they'd fixed this issue on 4/13, and I now see this issue as resolved. Closing this issue. Thanks.
