### ISSUE TITLE
Jira integration issue

### ISSUE THREAD

**Issue by RedShiba** [getsentry/sentry#47276]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

22.12.0

### Steps to Reproduce

As far as I know you don't support anymore jira plugin, but jira server integration. Unfortunately I can't use Jira Server Integration due to security policy of Jira Server in my company. I decided re-write jira plugin and get rid of jira's deprecated method createmeta as you did for jira integration. It works. But I have visual bug with fields "Affects version" and "Fix Version". When I select smth in dropdown list, it doesn't shown as selected, actually nothing happens. But issue will be created with selected item even if it's not displayed on the UI. Also seems multiple choice for these fields doesn't work. The question is do you have the same issue with Jira integration? or know how to fix this issue?
<img width="601" alt="paveikslas" src="https://user-images.githubusercontent.com/96052052/231575666-91bf3376-95c6-43e1-aa9a-e8f98c3747a0.png">

### Expected Result

selected items are displayed correctly on the UI for fields "Affects version" and "Fix Version"

### Actual Result

selected items are displayed as unselected on the UI but actually used when jira issue is being created.

**Comment by RedShiba** [comment]
I use this plugin https://github.com/getsentry/sentry/tree/22.12.0/src/sentry_plugins/jira, but a bit modified this in order to work with jira >9.0. As I mentioned above I have visual issue on the UI, so I just wondering do you have the same issue with these fields in Jira Integration as I have using jira plugin?

**Comment by hubertdeng123** [comment]
I'm seeing this 🤔, maybe this is resolved in a later version of Sentry?

<img width="590" alt="Screenshot 2023-04-14 at 1 34 50 PM" src="https://user-images.githubusercontent.com/25517925/232149627-3e2a14e5-8da0-4a6d-8fa2-08229d2ff0fa.png">

**Comment by RedShiba** [comment]
seems it works :'( 
Is it jira plugin or jira integration?

**Comment by RedShiba** [comment]
it also doesn't work in newer version of sentry :(

**Comment by RedShiba** [comment]
@hubertdeng123 any thoughts? maybe you know someone who is familiar with code that responsible for this web form?

**Comment by RedShiba** [comment]
Could anyone provide info from Response json about what fields inside "fixVersion" in Firefox/Chrome? 
Web Developer Tools --> Network --> press GET api/0/../plugins/jira/create --> Response
Just wanna make sure I didn't miss anything here. Maybe "multiple:true" is not enough for this field
<img width="485" alt="paveikslas" src="https://github.com/getsentry/sentry/assets/96052052/7e1295ef-dd23-46ea-b9a0-6ae4246b3f13">

**Comment by chadwhitacre** [comment]
Sorry we haven't been able to help more with this, @RedShiba. Seems you're really in the weeds. 😞

Here's the JSON I'm seeing for fix version:

```json
        {
            "label": "Fix versions",
            "required": false,
            "multiple": true,
            "choices": [
                [
                    "10128",
                    "Q3/22"
                ],
                [
                    "10153",
                    "Q4/22"
                ],
                [
                    "10171",
                    "Q1/23"
                ],
                [
                    "10173",
                    "EndOfQ1"
                ],
                [
                    "10174",
                    "EA"
                ],
                [
                    "10200",
                    "Q2/23"
                ],
                [
                    "10212",
                    "Q3/23"
                ],
                [
                    "10216",
                    "Q4/23"
                ],
                [
                    "10220",
                    "Q1/24"
                ],
                [
                    "10254",
                    "Q2/24"
                ]
            ],
            "default": "",
            "type": "select",
            "name": "fixVersions"
        },
```

**Comment by RedShiba** [comment]
Hi, @chadwhitacre . Actually you can, if someone could find a bit time and take a look into https://github.com/getsentry/sentry/pull/50163. It's a fix of visual bug.

**Comment by chadwhitacre** [comment]
Ah, nice! Let me see if I can get that on someone's radar ...

**Comment by hubertdeng123** [comment]
Looks like this [PR](https://github.com/getsentry/sentry/pull/50163) hasn't been merged yet, so looks like we need to get that in.

**Comment by ceorourke** [comment]
cc @vuluongj20 seems like you've been working on the PR

**Comment by GabeVillalobos** [comment]
Unfortunately the team is understaffed and we can’t prioritize this fix, but we’re always open to community contributions.
