### ISSUE TITLE
Improve Ruby Grouping for generated ERB template suffix

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry#47289]
### Environment

SaaS (https://sentry.io/)

### Version

sentry.ruby 4.8.1

### Steps to Reproduce

1. An error is occurring in a `jbuilder` function whose name is dynamically generated. 

```
// Issue A - function has two underscores after "..._jbuilder"
/path/to/file/file.json.jbuilder in block in _myfunction_json_jbuilder__1111111111111111_222222222222

// Issue B - function has three underscore after "..._jbuilder"
/path/to/file/file.json.jbuilder in block in _myfunction_json_jbuilder___3333333333333_444444444444
```

2. This results in each of these getting grouped differently, despite having the same stack trace, AND despite being [scrubbed of the generated template suffix here](https://github.com/getsentry/sentry/blob/master/src/sentry/grouping/strategies/newstyle.py#L260-L268)

Grouping details:

![issue_grouping_underscores_redacted](https://user-images.githubusercontent.com/12092849/231602919-112194ff-49cc-4b6f-9ac0-1aa8c2c9d98c.png)

### Expected Result

The expected result is that these issues should be grouped together. I think what may be happening is that the initial underscore or two gets stripped out but the number of underscores is not normalized for grouping when [processed here](https://github.com/getsentry/sentry/blob/master/src/sentry/grouping/strategies/newstyle.py#L260-L268).

### Actual Result

Described and screenshotted in 'steps to reproduce'

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1809) by [Unito](https://www.unito.io)

**Comment by mrduncan** [comment]
Our recent [AI grouping](https://blog.sentry.io/cancel-the-issue-noise/#ai-grouping-smarter-more-effective-issue-creation) changes which are now available for Ruby should have resolved this. @cstavitsky if you have any recent examples where this isn't the case, please reopen.
