### ISSUE TITLE
Update AI Suggestion Mp4 with new illustration

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry#47304]
The Illustration team recently agreed on not having illustrations for dark and light modes but rather an illustration that is suitable for both modes. You can read more about it in [this conversation slack conversation](https://sentry.slack.com/archives/C592MC8TF/p1681320482621349). 

Drew provided a new illustration for the Wheel of Fortune and we will have to update the "loading" video.

**Assets**

![Image](https://user-images.githubusercontent.com/29228205/231677342-be88456e-a883-47e6-8e6b-08e0b98af73b.svg)

![Image](https://user-images.githubusercontent.com/29228205/231677357-7d093b79-92bb-4d98-8e9a-7045d7194643.gif)

We also have a `.ai` extension but this extension is not allowed by GitHub. Please if you need it, just reach out to me.

**Acceptance Criteria:**

- Update the "loading" video with the new illustration
- Update the "Sentaur" with a version that fits both light and dark mode

**Comment by Jesse-Box** [comment]
@priscilawebdev Is this a ticket for me or for you?
