### ISSUE TITLE
Typing `-use-artifact-bundles` tells the user to update sentry cli or use `--release`

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#47309]
### Problem
Users could have simply mistyped the option, and so we should remind users of this fact before recommending more drastic actions

### Acceptance Criteria
If a user specifies an option that the current version of sentry-cli doesn't recognize, we should output the following message

```
error: This version of Sentry does not support the option '-use-artifact-bundles'. Please verify that you've correctly typed the desired option. If that fails, try updating sentry-cli to the latest version by typing 'sentry-cli update'.
```

**Comment by kamilogorek** [comment]
This is somewhat hard to achieve, as `-use-artifact-bundles` *is* a valid option for cli parser and it means means `-u se-artifact-bundles` which is equivalent for `--url-prefix se-artifact-bundles` 👀 
If you type `--use-artifact-bundle` it _will_ warn you about invalid flag and tell you that `--use-artifact-bundles` exists instead.
