### ISSUE TITLE
Ignore old Opera Mini

### ISSUE THREAD

**Issue by pensierinmusica** [getsentry/sentry#4730]
Hi,

In the project settings section I see there's an "Inbound data filters" option that says "Filter out known errors from legacy browsers".

One of the options is "Opera - Version 14 and lower". This unfortunately doesn't seem to include Opera Mini though, which is present on a lot of old Android devices.

Can you please fix it? Thanks!

**Comment by benvinegar** [comment]
> One of the options is "Opera - Version 14 and lower". This unfortunately doesn't seem to include Opera Mini though, which is present on a lot of old Android devices.

We'd consider this a separate, "Opera Mini" filter. We'd classify this as a new feature instead of a bug.

**Comment by dylmye** [comment]
I would like to help out but it seems like we don't want to pursue this any further due to the complexity. Am I correct in that assumption?

**Comment by markstory** [comment]
@dylmye I don't think the issue is complexity. The last pill request had a conflict and we don't have the people power to rebate and clean up conflicted changes. If you have time/interest we can probably get the changes through.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
