### ISSUE TITLE
Can't see linked issue on Jira ticket

### ISSUE THREAD

**Issue by jazzdragon** [getsentry/sentry#47313]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Install the Jira integration
2. Create a Jira ticket from a sentry issue
3. Open the ticket in Jira
4. Can't see the Sentry issue

### Expected Result

I should be able to see Sentry issues linked to a Jira ticket

### Actual Result

<img width="703" alt="CleanShot 2023-04-13 at 12 46 04@2x" src="https://user-images.githubusercontent.com/5546798/231749018-2f6a9ec9-ed96-4cb5-ab27-8d9187176ecf.png">

**Comment by jazzdragon** [comment]
How do I create a support ticket? it's basically any issue we have linked with Jira.

**Comment by brianthi** [comment]
You can create a support ticket here: https://help.sentry.io/.  However I'll reassign this to the support team now so they can help you out.

**Comment by jazzdragon** [comment]
@JLuse sorry even with the link I can't see anywhere I can open a ticket with support. Why did you close this issue? was it fixed?

**Comment by mathieulepoutrebelgium** [comment]
I would like to offer Exalate, a solution for synchronizing data between your Github and Jira instances. Our decentralized solution can help you achieve this seamlessly and efficiently.

**Comment by jazzdragon** [comment]
Are you doing marketing on github issues? bold move.

**Comment by hubertdeng123** [comment]
@jazzdragon are you still experiencing this issue?
