### ISSUE TITLE
AI suggested fix has annoying prompt

### ISSUE THREAD

**Issue by lesderid** [getsentry/sentry#47314]
### Problem Statement

 I stumbled upon the new suggested fix feature in SaaS, implemented in https://github.com/getsentry/sentry/pull/46375.

While this feature sometimes gives useful output, the 'snarky greeting' and 'fun prompt' stuff is jarring, unprofessional, and unpredictable, and is stopping me from using the feature.

### Solution Brainstorm

Please get rid of it (the greeting/fun prompt stuff) before it goes to GA, it serves no purpose.

**Comment by mitsuhiko** [comment]
I'm sorry that the style of the greeting does not sit well with you. I would however be curious if it generated particularly problematic greetings for you. Do you have some examples of what you consider "jarring"?

**Comment by lesderid** [comment]
I only saved one example that I found particularly annoying. I've added some highlights:

![Screenshot](https://files.catbox.moe/zmyouk.png)

**Comment by mitsuhiko** [comment]
Thanks for the feedback. We will discuss this internally.

**Comment by tyocca** [comment]
I agree with this feedback and support the suggested solution. 

The prompts are tacky, distasteful, off-putting, and ignorant.

I similarly will avoid this feature until it is removed.

**Comment by FredrikAugust** [comment]
Hi. I was referred to this issue from speaking with customer support. Personally I find the "fluff" to be nothing more than distracting while attempting to solve a bug. I've added a screenshot of a random reply from the bot and highlighted everything I find to be distracting.

<img width="1840" alt="Screenshot 2024-01-22 at 12 42 38" src="https://github.com/getsentry/sentry/assets/7691547/e83c2f6a-632d-45e0-9137-0dda5d7b7419">

It's a bit annoying having to filter out all the other "stuff" before being able to read the actual analysis and accepting/discarding the factual contents.

**Comment by ale-cota** [comment]
Thanks a lot for the suggestions!
@trillville here's an improvement to consider.
