### ISSUE TITLE
Add Endpoint to Download Apple Compatible Raw Crash Report

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#4736]
As a temporary stop-gap (and for beta releases later) we should add a way to download an apple compatible text file that can be manually symbolicated on the user's computer.

**Comment by mitsuhiko** [comment]
Disregard above commits, they reference the wrong issue.

**Comment by mitsuhiko** [comment]
GITHUB!

**Comment by HazAT** [comment]
We will generate the apple crash report on the fly ... for that we have to keep the `debug_meta` info in order to provide the `Binary Images:` section for the report
