### ISSUE TITLE
Show full transaction names in the performance UI for long truncated names

### ISSUE THREAD

**Issue by osdiab** [getsentry/sentry#47378]
### Problem Statement

We have performance traces with long names since

- we serve a graphQL api
- it supports batched graphQL operations
- we name the traces based on the combination of all the operations in the batch graphQL requests

But it just gets cut off since they're long as a result. I can still view it if I hit the gear icon on a trace, but that was not obvious to find.

Can you add some way to view a full trace name for a trace with a long name? Thanks!

https://www.loom.com/share/435cacfef468433aa03e6eda2a5fcf4d

### Solution Brainstorm

At least show it as a tooltip on hover, ideally provide a ux like a `... Expand` button or something to see it all, or show it in smaller text somewhere else. Maybe scale the font size down if the name is long?

**Comment by silent1mezzo** [comment]
Thanks for this @osdiab. We'll get a fix for this out.

**Comment by narsaynorath** [comment]
Hi @osdiab! We've added a tooltip to the performance headers so if they overflow you should be able to hover on them now. Thanks for the report, let us know if there are any other issues
