### ISSUE TITLE
Dynamic Issue Assignment rules based on event context data

### ISSUE THREAD

**Issue by gid-sentry** [getsentry/sentry#47376]
### Problem Statement

Customer writes:

"Currently when we have a crash during a build in our build pipeline..." "...the crash gets reported to sentry. and we've got it tagging the build user based on some jenkins metadata. for example if i triggered a build, and during the build the app crashed, it would get tagged with build_user: MY_NAME. i was wondering, in the sentry automatic assignment rules, is it possible to auto-assign issues dynamically based on the value of a tag like that? such that an issue would get auto-assigned to the username in the tag?

Our builds are absurdly complex and the true error often ends up buried deep in obscure log files  - 

currently we've got sentry running in the app itself in the build, and also in our c# build automation tool, and i'd like to also trigger it from our jenkins groovy, maybe as part of a jenkins shared pipeline library - https://www.jenkins.io/doc/book/pipeline/shared-libraries/ - which could probably be open sourced for use by anyone"

### Solution Brainstorm

Allow for a dynamic owner setting in issue ownership rules, such that variables can be plugged into it (such as the value of a tag, or other bits of context from the event coming in)

**Comment by snigdhas** [comment]
Hi @gid-sentry, this can be done manually by setting ownership rules such as `tags.build_user:<username> <email>`. More information on that [here](https://docs.sentry.io/product/issues/ownership-rules/#ownership-rules). 

We're unlikely to get to automating this anytime soon.
