### ISSUE TITLE
Edge runtime regions not working when integrating with Sentry

### ISSUE THREAD

**Issue by Cow258** [getsentry/sentry#47404]
### Environment

SaaS (https://sentry.io/)

### DSN

https://756fac6d7d514f5db62c7f0bc5a0f53e@o4504872119566336.ingest.sentry.io/4504872145059840

### Link to the code that reproduces this issue

https://github.com/Cow258/edge-bug-demo

### To Reproduce

1. Deploy to Vercel
2. Goto https://****.vercel/api/hello
3. Open DevTool for the response headers
4. You will find the region is different from 'sin1'

https://edge-bug-demo.vercel.app/api/hello

### Expected Behavior

The region should be as same as the config when integrating with Sentry
![image](https://user-images.githubusercontent.com/14261588/231961907-45d677b8-17f3-436b-9766-09595eb1164f.png)

### Actual Result

I set the regions to ['sin1'], but it still global after deployed to Vercel and integrating with Sentry

```js
export const config = {
  runtime: 'edge',
  regions: ['sin1'],
}
```
![image](https://user-images.githubusercontent.com/14261588/231961648-c66e6591-bc5a-4d8d-94c3-8d35b652f31d.png)

**Comment by AbhiPrasad** [comment]
Hey @Cow258, thanks for writing in! This is a known issue - we are tracking things related to it in this GH issue: https://github.com/getsentry/sentry-javascript/issues/7450, so closing this issue since it's duplicate.

**Comment by AbhiPrasad** [comment]
Until this is fixed, you can use the `excludeServerRoutes` option to stop adding Sentry instrumentation to your edge routes to unblock yourself.
