### ISSUE TITLE
Mexico timezone incorrect, does not observe DST

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#47424]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Mexico no longer observes daylight savings time [here](https://techcommunity.microsoft.com/t5/daylight-saving-time-time-zone/mexico-2023-time-zone-updates-now-available/ba-p/3749684). In Sentry if you have selected Mexico City selected from the account settings, events are time stamped 1 hour ahead of current Mexico time:
<img width="1907" alt="Screenshot 2023-04-14 at 9 17 01 AM" src="https://user-images.githubusercontent.com/8451987/232158953-aecbf90e-e549-4f87-ba07-b4e318e91761.png">

Steps: 
1. Navigate to account settings - https://{slug}.sentry.io/settings/account/details/
2. Change timezone to Mexico City
3. Trigger event -> compare time stamp of event to current Mexico City time

Suggested fix: Set to (-5) [here](https://github.com/getsentry/sentry/blob/6fb9d246de05dd6313d3743bb5ab83841c45c0f6/static/app/data/timezones.tsx#L153)

### Expected Result

Sentry event timestamps to match current Mexico City time zone

### Actual Result

Events are reported 1 hour ahead of current Meixco timezone

**Comment by evanpurkhiser** [comment]
Changing it to `-5` in the proposed fix section actually won't do anything, that's just for visual information. I think we'll need to upgrade `moment-timezone`

Though we can probably also update the `-6` in that list.

**Comment by evanpurkhiser** [comment]
@JLuse once that merges we can check if things are fixed 👌
