### ISSUE TITLE
About updating the translations

### ISSUE THREAD

**Issue by myonlylonely** [getsentry/sentry#47439]
### Problem Statement

How often is the translation updated? 
Is there a way for us to update the tranlations from Transifex in Docker images?

**Comment by Fwang36** [comment]
Hi 

Looks like the last update to the translations page was 2 days ago.  If you would like to contribute, you can request to join [here](https://explore.transifex.com/getsentry/sentry/)

**Comment by myonlylonely** [comment]
Is it under https://github.com/getsentry/sentry/tree/master/src/sentry/locale ? It is 2 years old.
