### ISSUE TITLE
"Last Seen" in issue sidebar does not show issues from the latest release

### ISSUE THREAD

**Issue by alvarlagerlof** [getsentry/sentry#47443]
### Environment

SaaS (https://sentry.io/)

### Link

https://alvar-lagerlof.sentry.io/issues/4095244054/events/latest/?environment=vercel-preview&project=4505020218277888&query=is%3Aunresolved&referrer=latest-event&stream_index=1

### DSN

https://85e3ebd203224c8ba6c6a2832b5ab1f9@o4505020211134464.ingest.sentry.io/4505020218277888

### Steps to Reproduce

1. Find or make an issue tied to one release
2. Make a new release that does not fix the issue
3. Trigger the issue again
4. The "Last Seen" in the sidebar does not mention the latest release, but the first one

The release progression is:
1. [d2b05d10e84d](https://alvar-lagerlof.sentry.io/releases/d2b05d10e84d12a3ca06d5dd8f1a43110d8e87c2/?project=4505020218277888)
2. [2e5591065b0d](https://alvar-lagerlof.sentry.io/releases/2e5591065b0d79394895e2b593d978c41a75fc15/?project=4505020218277888)

Both of them have issue the same issue tied to them.

### Expected Result

Last Seen
5 minutes ago in release [2e5591065b0d](https://alvar-lagerlof.sentry.io/releases/2e5591065b0d79394895e2b593d978c41a75fc15/?project=45050202182778886

### Actual Result

Last Seen
5 minutes ago in release [d2b05d10e84d](https://alvar-lagerlof.sentry.io/releases/d2b05d10e84d12a3ca06d5dd8f1a43110d8e87c2/?project=4505020218277888)

I can see both of these at the same time on the same [page](https://alvar-lagerlof.sentry.io/issues/4095244054/events/e25c09067c6546188ad6a5d8aec78716/?project=4505020218277888).

<img width="317" alt="image" src="https://user-images.githubusercontent.com/14835120/232310006-fd95261c-74d1-423b-a4ae-9aef99cbaac3.png">
<img width="181" alt="image" src="https://user-images.githubusercontent.com/14835120/232310017-3a7cf465-5a02-4ddd-a6ba-2491b87fe70b.png">

**Comment by brianthi** [comment]
Hi @alvarlagerlof, when I look at the issue you've shared, the latest release is shown in the `Last Seen` section.  It's likely that there's some latency when updating this field.  I'll pass this along to the team to see if this is expected or not, however I will close this ticket as it's no longer reproducible.

**Comment by alvarlagerlof** [comment]
> Hi @alvarlagerlof, when I look at the issue you've shared, the latest release is shown in the `Last Seen` section.  It's likely that there's some latency when updating this field.  I'll pass this along to the team to see if this is expected or not, however I will close this ticket as it's no longer reproducible.

Hmm. Then maybe I've seen that in other places as well. It seems that the cache is fresh too long. Several minutes.
