### ISSUE TITLE
AI Bug Bash

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#47454]
- [x] Hide Details -> save in localstore
- [x] Do not close the suggestion after giving feedback
- [x] Responsive issues
- [x] Banner too low on the page
https://minarorg.sentry.io/issues/4090269597/?project=4505012487258112&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
- [x] AI Solution and Experimental badge are misaligned
- [x] Dismiss button should have the same action as hide suggestion
- [x] Add a bit more padding to the consents
- [x] Ask Armin about adding the document to the legal section on the website

**Comment by priscilawebdev** [comment]
regarding the last item, Armin was asked in the slack thread https://sentry.slack.com/archives/C04SUT3KUV8/p1681732238173119

**Comment by priscilawebdev** [comment]
we will rotate the last item to the enterprise team and see if they can improve it
