### ISSUE TITLE
Device model name should be shown instead of model type where possible

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry#47453]
### Problem Statement

Currently, when viewing an error or a transaction, in some places, the model type of the device (e.g. `iPhone15,3`) is shown instead of the more readable model name (`iPhone 14 Pro Max`).

These places are:
- the Tags header section of an error event
<img width="852" alt="Screenshot 2023-04-17 at 10 25 18" src="https://user-images.githubusercontent.com/2005158/232430978-20ee7909-e6e0-43fb-8425-5e3054cdd72b.png">

- the device tags overview for error events
<img width="341" alt="Screenshot 2023-04-17 at 10 31 50" src="https://user-images.githubusercontent.com/2005158/232430988-7d4605bb-2eee-4e14-bd0f-c6e19f2d61ab.png">

- the Tag Details section of a transaction
<img width="357" alt="Screenshot 2023-04-17 at 10 32 38" src="https://user-images.githubusercontent.com/2005158/232430992-c688fe7c-baee-4381-b0df-b28df34836e8.png">

(this may not be a complete list)
However, as depicted, in some instances the mapping seems to work in these places. 

Also, in the device breakdown of the All Tags section of an error event, mapping seems to work in general:
<img width="321" alt="Screenshot 2023-04-17 at 10 29 39" src="https://user-images.githubusercontent.com/2005158/232431234-71190c65-fa40-49bb-8947-320ef234dd3b.png">

Note: The examples here are for mobile events and iOS devices, but may be applicable to other mobile device families and even non-mobile events.

### Solution Brainstorm

- The model name should be displayed instad of the model type - this is mainly important for the Tags header section of error events
- It is still useful to be able to see the exact model type, e.g. via hovering over the model name

**Comment by scttcper** [comment]
hmm looks like the package we're using hasn't been updated in a bit https://github.com/pbakondy/ios-device-list/
