### ISSUE TITLE
The event frequency condition passes regardless of any other filtering conditions passing.

### ISSUE THREAD

**Issue by JTCunning** [getsentry/sentry#4751]
Adding a filtering condition like `tagged_event` or `event_attribute` to `event_frequency` makes it so that a rule will pass if the frequency is met and the filter is met for any one of the events in the frequency window, and not the entire set of events in the frequency window.

This behavior was brought to light by @nabil-money through [zendesk ticket #5445](https://sentry.zendesk.com/agent/tickets/5445).

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by BYK** [comment]
Hi @JTCunning
