### ISSUE TITLE
Replay Index: The sortable headers should have a larger click-target

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#47525]
And maybe the headers need a tooltip?
Also show sort direction on hover?

The real goal of this ticket is to make it easier to know that they are sorted/sortable in the first place

If we're fixing padding in the header of the replays table, we should go around the app and do the same for other tables too.

**Comment by billyvg** [comment]
Currently, the click target does not include the yellow area

![Image](https://github.com/user-attachments/assets/07d42f57-6ea1-451c-8edd-8d23afdf627e)
