### ISSUE TITLE
Multiple Sentry Session Replay instances are not supported

### ISSUE THREAD

**Issue by lehmat** [getsentry/sentry#47532]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.3.1

### Steps to Reproduce

Initialize sentry with following setup to setup replay:

```
      Sentry.init({
        dsn: process.env.SENTRY_DSN,
        Vue: Vue,
        release: process.env.SENTRY_RELEASE,
        replaysSessionSampleRate: 0,
        replaysOnErrorSampleRate: 1.0,
        attachProps: true,
        logErrors: false,
        integrations: [
          new Integrations.BrowserTracing({
            tracingOrigins: [
              'localhost',
            ],
          }),
          new Sentry.Replay({
            maskAllText: true,
            blockAllMedia: true,
            maskAllInputs: true,
          }),
        ],
        tracesSampleRate: process.env.NODE_ENV === 'development' ? 0.5 : 0.1,
      })
```

A lot of errors arrive with Multiple Sentry Session Replay instances are not supported from frontend

### Expected Result

Replay would work and not error out on multiple Replay instances (with one initialized)

### Actual Result

No replays found and erroring

**Comment by AbhiPrasad** [comment]
Hey @lehmat - using Replay with multiple clients/hubs or having a replay integration per micro-frontend is not supported at the moment (same with `BrowserTracing`). See: https://github.com/getsentry/sentry-javascript/discussions/7037#discussioncomment-4852229 for some reasoning around this.

**Comment by lehmat** [comment]
Hi @AbhiPrasad

> At the moment, the Replay integration does not support multiple Sentry instances, you'll have to only use one Sentry instance

I'm only using one Sentry instance or does it mean only one `{ integration: [..] }` in the init is possible?

**Comment by AbhiPrasad** [comment]
If you only have a single `init `call, that config looks fine to me.

Looking at your sample rates:

```
replaysSessionSampleRate: 0,
replaysOnErrorSampleRate: 1.0,
```

This means that you are only sending replays when errors occur. That is intended right?

Maybe then the issue is https://github.com/getsentry/self-hosted/issues/2057 since I notice you are on self-hosted. So replays are not showing up in the Sentry UI at all right?

**Comment by lehmat** [comment]
Sentry UI is totally empty yes. I looked at logs of snuba-replays-consumer and it sitting idle so events are not coming in?

Not sure why it would yield in Multiple Replays error on Vue if the API responds 200 and the event is not just showing up

**Comment by AbhiPrasad** [comment]
If you test with a `sentry.io` DSN, do you still get replays @lehmat?

**Comment by lehmat** [comment]
I will close this for now. I will re-open if issue persists after a resolution to  [#2507](https://github.com/getsentry/self-hosted/issues/2057) has been made and I've made fixes to on-premise installation
