### ISSUE TITLE
[Design] Opt-in state for HTTP Req/Res/API Headers

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#47548]
## **Problem**

The HTTP Req/Res + API Headers feature is only available upon opting-in. In addition, it also requires a new SDK version (7.50.0).

For more details, see this [GitHub issue](https://github.com/getsentry/sentry-javascript/issues/7830). We need to communicate to users the two discreet steps to enable the highly anticipated HTTP Req/Res + API headers feature.

--

In addition, we want to have a more prominent indication that this feature exists for our users.

## Solution Proposal

With maintain the existing icons we have on each Fetch and XHR as seen in [this Figma](https://www.figma.com/file/SVyNvm8p17xGfIC7r7l2YS/Specs%3A-Details-%2F-Network-Tab?node-id=109-6850&t=Al4IVdCzrwa51T9w-0). When a user clicks an applicable network call, we show them two steps:

1. Make sure they're on SDK version X.XX.XX or higher.
2. Copy the following code snippet to opt-in for Network Req/Res + API headers for a given URL. A copy clipboard feature would be nice here.

Ryan/Bruno's suggestion:

> we can even put together a regexp to make it copy+pasteable because we know the url that you want to see

--

For more prominent indication that this feature exists, we could introduce a banner message under the Network tab. We could also add a "New" badge next to "Network" in the tab.

**Comment by ryan953** [comment]
I think this is done.

> For more prominent indication that this feature exists
![SCR-20230426-jatv](https://user-images.githubusercontent.com/187460/234646478-5eb2c3be-776c-4258-a861-d0cfd57daea3.png)


> Copy the following code snippet to opt-in
From [figma](https://www.figma.com/file/SVyNvm8p17xGfIC7r7l2YS/Specs%3A-Details-%2F-Network-Tab?node-id=218-15105&t=7qcBukfYSRapvawh-0)
![SCR-20230426-jefk](https://user-images.githubusercontent.com/187460/234648516-0885c860-5078-4a15-984c-05d53e98d4ee.png)
