### ISSUE TITLE
Custom section layout for event details

### ISSUE THREAD

**Issue by pfdzm** [getsentry/sentry#47552]
### Problem Statement

I would like to be able to re-arrange the layout of some areas/blocks in the issue details page. For example, while we find it useful to provide some additional data for some errors, this data is often hidden in some (seemingly) random place in the UI and not featured in any particular way. It's easy to miss and, especially when using any platform-specific wrapper/integration, is drowned out by similar sections that, honestly, are mostly not that interesting. For example I see a "Culture" section ("contexts" from the JSON?) that specifies `locale` and `timezone` - nice to have, I guess, but why does this appear on top of my additional data?

### Solution Brainstorm

Add a (very basic) UI builder or at least let me specify which contexts/sections should be pinned at the top. So, if I have an "Additional Data" section, I want to see that before anything else. It would be even cooler if I could even place this _above_ the breadcrumbs or stack trace section (I guess tags could be abused for that, but it doesn't feel right).

**Comment by therealarkin** [comment]
Hi!

Thanks for the feedback. You are not the first one suggesting that; we are trying to make things work out of the box for 90% of the people and allow customization to more advanced users. However, we have yet to think through this particular one.

What default improvements (i.e. without the customization) would you feel will be net better for your use case and why?

**Comment by pfdzm** [comment]
Thanks for your reply! Makes sense, I do understand that you need to take all users' perspectives into account.

It's just something that every now and then leads to some frustration, because of how easy it is to oversee a section in the context/extra data section of the page. But if we have an event with this extra data, generally we don't want it to be missed. Maybe slightly more distinct headings would already be a great improvement. 

I think allowing users to pin a particular section to the top, or to affect how things are sorted in that section might help massively. Or give the "Additional Data" section a slightly different background, so it stands out. 

I am not sure if this is the relevant code, but perhaps it could be possible to sort these entries based on user code: https://github.com/getsentry/sentry/blob/af49b367e0a3b1815e7079ac7c29c74202526de2/static/app/components/events/contexts/index.tsx#L56 (but I understand that this may not be desired at all, and it's probably way more complicated than I can see here).

**Comment by snigdhas** [comment]
@pfdzm we've been working on changes to the issue details layout in recent months. The feature is in EA but you can check it out by enabling the early adopter option for your organization. I'm going to close this since the we've taken this feedback into account for the new layout but please reopen or file a new issue with your feedback on the new UI - we'd love to make it work for you!

**Comment by pfdzm** [comment]
great, thank you, will give it a try 🙂
