### ISSUE TITLE
Breakpad-generated minidump errors on Linux get over-eagerly merged into single issues

### ISSUE THREAD

**Issue by endrift** [getsentry/sentry#47611]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.3.1

### Steps to Reproduce

Using minidumps generated by breakpad's post-mortem generator tool core_handler on Linux, submit via the Minidump endpoint for a given DSN. I don't have symbols imported, but given how disparate the backtraces are, I'm unsure this matters.

### Expected Result

Different backtraces and different executables should be properly separated into distinct issues.

### Actual Result

Sentry over-eagerly merges errors generated by distinct backtraces _from distinct executables_ into the same issue. The only thing that seems to differentiate them into separate issues is which signal caused it to crash: SIGABRT and SIGSEGV errors wind up properly separated into distinct issues. I don't have symbols loaded for any of these, but it doesn't seem to matter even if I add them--they still get lumped into the same issue.

I tried enrolling in early access features for the issue grouping breakdown settings to see if I could work around the issue, but that doesn't seem to work on my installation (maybe it's SaaS only?)

Some JSON logs here: [minidumps.zip](https://github.com/getsentry/sentry/files/11267623/minidumps.zip)

**Comment by hubertdeng123** [comment]
If these are early adopter features, you'll need to add this to your `sentry.conf.py`. You can view the features that are for grouping here:
https://github.com/getsentry/sentry/blob/master/src/sentry/features/__init__.py#L81

**Comment by endrift** [comment]
These are not early adopter features. This is a basic, documented feature that things are supposed to be grouped based on stack trace. What's happening here is that they are being grouped _in spite_ of their stack traces. I'm not sure how that isn't clear. I tried doing the early access feature only to see if I could work around the broken feature.

**Comment by endrift** [comment]
Sorry, what more information do you need? I need more information to give you more information.

Also, now that the grouping UI is enabled (I think?) it shows that the issues are grouped because things like this:

![image](https://user-images.githubusercontent.com/605502/234474383-c79c11ae-36f4-4ffc-9d98-edfc5d90fa11.png)

Except the number of traces and details in the section are all completely different. I have no idea what's going on here, but it happens with or without me putting things in the stack trace rules section. Clearly either something extremely basic is broken, or your documentation is severely insufficient for "how do you make it not group everything".

**Comment by hubertdeng123** [comment]
Sorry to hear that you're experiencing frustration here. My comment earlier was addressing early access features since you mentioned it didn't seem to work for you. For self-hosted Sentry, the process for enabling those is different from SaaS. As for the issue grouping issue that you're experiencing, that will have to be addressed by someone else on another team.

**Comment by endrift** [comment]
Setting the grouping strategy to mobile:2021-02-12 seems to potentially resolve this, however I still need to figure out if it differentiates executables with the same name properly still. This isn't a mobile program though, so I'm not sure why that one works better than newstyle:2019-10-29 (the apparently default) or newstyle:2023-01-11 (which I have to manually select to get it to be applied).

Since selecting the grouping strategy is not something that's allowed by default, I still consider this a bug.

**Comment by jjbayer** [comment]
@endrift could you please share the full text (minus sensitive data) of the grouping UI for two events from the same issue that you think should be in different issues? Make sure to press "All values" first:

![image](https://user-images.githubusercontent.com/1565449/235067957-393be77d-86e6-422a-a91d-28a80b6f81e9.png)

Thanks!

**Comment by endrift** [comment]
I only meant to collect 2, but here are 3 because something else crashed in the meantime.
![image](https://user-images.githubusercontent.com/605502/235267627-706c9a15-b858-467d-9cb2-9bf4fe5fbfc9.png)
![image](https://user-images.githubusercontent.com/605502/235267695-35fab02f-52d5-49ac-93d4-ca5904b1567f.png)
![image](https://user-images.githubusercontent.com/605502/235267752-103d708b-6d86-46b5-8c53-59cbe20e0a47.png)
Note that all three of these are from different programs, which is not reflected in the grouping strategy.

Of course, all three have the same actually contributing values
![image](https://user-images.githubusercontent.com/605502/235267856-7e22d586-76a1-4422-8fdd-66bee5d04a2e.png)

**Comment by jjbayer** [comment]
@endrift thank you. I cannot tell you for sure why these events group together, but the short answer is that our grouping algorithm relies on symbolicated stack traces. Could you try if uploading symbols resolves the issue for you?

>  I don't have symbols imported, but given how disparate the backtraces are, I'm unsure this matters.

**Comment by Swatinem** [comment]
We are currently discussing an internal issue that was related to "unapplied" debug files.
In summary, something is marked as "unapplied" if the debug file exists in sentry, but is not being queried/found by symbolicator during symbolication.

This can happen if symbolicator can not correctly call back to sentry to ask for the file. You would in that case see an error reported internally in symbolicator.

**Comment by endrift** [comment]
> @endrift did you follow instructions at https://docs.sentry.io/platforms/native/data-management/debug-files/?

Yes I did.

**Comment by endrift** [comment]
I can confirm that symbolication means it's no longer over-eagerly merged, but this is still a pretty significant oversight for some niche cases.

**Comment by chadwhitacre** [comment]
Am I reading this right that we have a workaround identified? Do we have any further action items on this issue, or can we close it?

**Comment by endrift** [comment]
I don't understand why you're equating a workaround with a fix.

**Comment by chadwhitacre** [comment]
I'm not. I'm asking the team if they are satisfied with the workaround or intend to put this on their backlog to eventually fix.

**Comment by Swatinem** [comment]
I believe there is different things at play here.
- I was focusing on the `Unapplied` label of debug files that were uploaded. This is most likely a mis-configuration issue where symbolicator can not correctly query for debug files on Sentry. You should see this in the logs, and configuring this correctly will fix that part.
- Issue grouping with lack of symbolication. I believe this is your primary ask here. If you have correct symbolication, grouping will work better for sure. With lack of symbols due to whatever reason, you will get bad grouping. As you suggest, one way to solve that would also be to consider the library in the stack trace if there is nothing else. I believe this used to be part of the "grouping breakdown" that was also mentioned, but we have since reverted back from that.

However with these things, I would rather focus on the first one. Since you mention breakpad, unwinding the minidump does need unwind info, for which it needs symbols. If you do not symbols available, you will get a bad experience regardless of any grouping problems.

**Comment by armenzg** [comment]
Out of curiosity, where does `function:* +app` come from? I see it in the screenshots.
Is it a customer stack trace rules? Or does it come from one of the grouping configs?

**Comment by endrift** [comment]
That's a customer stack trace rule that I added in desperation. It does not affect the grouping without symbols.

**Comment by armenzg** [comment]
I've filed #50155 to see if we can improve the experience and backlog it.
Thanks @endrift for filing it!

I will close this issue since it has too many threads for whoever may end up working on it from my team.
