### ISSUE TITLE
Cron monitors: Possible race condition 

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#47613]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a monitor that waits for check-ins every minute (or every 5 minutes, this time is not very important)
2. Do not set missed status wait time.
3. Configure your job to send check ins in sentry. 

### Expected Result

Assuming the job is working correctly, all executions are successful and send a status ok to Sentry. All check in times are marked as "ok" in the Sentry UI.

### Actual Result

In some occasions, we mark the check-in as missed. Because there is no wait window to mark it as missed during some periods of high traffic of the day show the same check in as missed and ok, most likely a race condition:
- The check in is a bit delayed in traffic or processing
- There is no wait window to mark the expected check-in as missed -> the check in is marked as missed
- We receive the ok check-in 

Similar to: https://github.com/getsentry/sentry/issues/44393

**Comment by evanpurkhiser** [comment]
Without setting a wait window we expect the monitor to checkin almost exactly on time (I believe there is a 1 minute window for it to be late, since the task that does this check runs once per minute).

I'm a little confused exactly what situation you're describing though

**Comment by evanpurkhiser** [comment]
This should be significantly improved by https://github.com/getsentry/sentry/pull/48826

Feel free to re-open the issue if you're still seeing strange issues like this
