### ISSUE TITLE
The issue link default value option value is invalid

### ISSUE THREAD

**Issue by coderfong-hub** [getsentry/sentry#47621]
### Environment

SaaS (https://sentry.io/)

### Link

https://c98416e79ee1.sentry.io/issues/3982627284

### DSN

https://d077b91934f14ad088668f2ea48f363f@o1238224.ingest.sentry.io/4504733024583680

### Steps to Reproduce

1.Loading the issue page
2.Click integration application
3.View the return value of the issue link

### Expected Result

The issue link option return value should be displayed on the option if it is the default value, not the status of the blank option

### Actual Result

According to the api documentation, when the interface returns a default value, options are not processed as default options
![image](https://user-images.githubusercontent.com/73768118/233063437-95fb3252-f658-453b-b81e-36e6bd43638e.png)

**Comment by brianthi** [comment]
Hi @coderfong-hub, even though the default value is in the API response, we have chosen not to display this in the UI.  Appreciate you raising this to us as it could have easily been a bug/oversight on our side!

**Comment by coderfong-hub** [comment]
> Hi @coderfong-hub, even though the default value is in the API response, we have chosen not to display this in the UI. Appreciate you raising this to us as it could have easily been a bug/oversight on our side!

Thank you for your response. I look forward to hearing about the fix!
