### ISSUE TITLE
Silently discarded exception inside worker process when reading source map from disk

### ISSUE THREAD

**Issue by adi1133** [getsentry/sentry#4769]
I consider that the crash at [this line](https://github.com/getsentry/sentry/blob/5755e6665965060da3bff46724b96dc1e1c5b230/src/sentry/lang/javascript/processor.py#L269) should be reported on the web interface or at least get logged as an error.

This error is currently silently discarded and the ui shows `Unable to fetch resource: http://www.website.com/main.js`.

The cause of my issue was not sharing the the `/var/lib/sentry/files directory` between the worker and web process thus causing a file read error. This was caused by running each process isolated in a different docker container. 

This may be relevant to #3228 and https://forum.sentry.io/t/offline-sourcemaps-not-used/548

Sentry version 8.12.0

**Comment by mattrobenolt** [comment]
We do log this as an error. It just isn't logged onto the event to be shown in the UI. This type of error is an operation error of the system, and is not relevant to the error itself. There are many reasons why the release file may not exist. Misconfiguration of the system is just one of them.
