### ISSUE TITLE
Build Number for Cocoa Events

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry#4773]
We currently do not send the build number with our events see:
https://github.com/getsentry/sentry-swift/issues/112

I've added an event property `buildNumber`
https://github.com/getsentry/sentry-swift/pull/113

Talked to @mitsuhiko about it because technically the build belongs to a release but I am not sure how it plays with the current release system.
It would be sufficient if we dynamically create an `event.tag` with `Build:${buildNumber}` to show the user the build.

**Comment by dcramer** [comment]
I dont have strong opinions here. Run it by @mattrobenolt and @tkaemming and propose something and I'm happy to weigh in.

**Comment by HazAT** [comment]
Maybe you guys can checkout to PR ... simple straight forward solution.
