### ISSUE TITLE
[Research] User Feedback Alert

### ISSUE THREAD

**Issue by scefali** [getsentry/sentry#47747]
One of our top Github issues has to do with getting alerts when user feedback is submitted: https://github.com/getsentry/sentry/issues/5055

1. Figure out what's the ideal product experience 
2. Spec out the technical work

**Comment by davidenwang** [comment]
This may or may not help but all of crons feedbacks are forwarded to slack, via this alert 
<img width="361" alt="image" src="https://user-images.githubusercontent.com/9372512/235743812-184c0a8e-98e5-471f-be92-f82d78338330.png">
and as far as I can tell we have not missed a feedback message

**Comment by georgiosd** [comment]
@scefali @davidenwang can we help somehow? :)

**Comment by georgiosd** [comment]
@scefali @davidenwang surely the bot is lying? :)
