### ISSUE TITLE
Add ability to configure session duration via web UI

### ISSUE THREAD

**Issue by daniilr** [getsentry/sentry#47751]
### Problem Statement

Currently, it is not possible to configure session duration. We are being logged out of sentry.io after 20 hours. Which ruins our cloud experience a bit comparing to self-hosted where this was longer by default. 

### Solution Brainstorm

It would be great to have a session duration setting under "Security & Privacy" per organization.

**Comment by souredoutlook** [comment]
Hey @daniilr this looks like a duplicate of of https://github.com/getsentry/sentry/issues/43182

Specifically this suggestion: 

> An organization level toggle for configuring session duration

If you want to provide your cloud organization ID I can add you to our internal tracker as well.

Let me know if I've misunderstood your request,

Nick
