### ISSUE TITLE
Transactions per minute

### ISSUE THREAD

**Issue by ashokchitimilla** [getsentry/sentry#47782]
### Problem Statement

Dear Team,

I would like to add widget for creating dashboards related to transactions per minute. Basically, I want a big number display of average transactions per minute for the time frame selected. Kindly let me know in case of any queries.

Thanks,
Ashok.

**Comment by wmak** [comment]
If you would like to do this: 

1. Click dashboards in the sidepanel
2. Either create a dashboard or edit an existing one
3. Click Edit dashboard
4. Click the add Widget icon
<img width="493" alt="image" src="https://user-images.githubusercontent.com/4205004/233732974-29f36c16-a7e7-4529-89a9-07a4e106234a.png">
5. Set the widget to this
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/4205004/233732870-4f773624-09d7-46c3-84df-a0be9ba36542.png">

You can read more [here](https://docs.sentry.io/product/dashboards/widget-builder/), please note that the dashboards feature is only available on either a Business or Trial plan.
