### ISSUE TITLE
Notify Discover only shows indexed

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#47811]
Problem Statement:
People do not realize that discover shows only indexed event and therefore cannot be trusted for trends and decisions based on total events.

Acceptance Criteria
- showing only for AM2 with base sample rate lower than 100%

Design
![image](https://github.com/getsentry/sentry/assets/9060071/16c3dcc3-4813-4f8c-a9c7-7fcdefb80cec)

**Comment by ale-cota** [comment]
This issue is blocked for now because we need the Discover API to be adapted to return the event type, so that we can show the warning only in case of queries on Transactions and not in case of queries on Errors.

@matejminar can you please link the corresponding ticket for the D&D/Perf team once created? Thank you! 🙏

**Comment by matejminar** [comment]
@ale-cota Here you go: https://github.com/getsentry/sentry/issues/48633

**Comment by ale-cota** [comment]
We can still implement the less intelligent version of this, where we display the warning independent of the data source.
- The banner can be dismissed
- The banner is dismissed on a per-user level.

**Comment by ale-cota** [comment]
@priscilawebdev to make this a little bit more accurate, could we not show the warning in the case where the customer specifically types in something like `event.type:error`? Because then we know for sure it's not sampled, since we store all errors. Thank you!
