### ISSUE TITLE
Edited comment does not update unless page is reloaded

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#47818]
### Environment

SaaS (https://sentry.io/)

### Product Area

Issues

### Steps to Reproduce

1. Open an issue
2. Go to the Activity tab
3. Add a comment
4. Edit the comment

### Expected Result

The comment appears with its edited version after clicking on "Save Comment"

### Actual Result

After clicking "Save Comment", the edited comment appears unchanged. The user hat to refresh the page for the comment to update.

https://user-images.githubusercontent.com/81985895/234006743-f6241990-951c-49c5-aabe-7d072e5b8b0c.mov

**Comment by hubertdeng123** [comment]
Looks like this was backlogged, but routing to `Issues` for visibility
