### ISSUE TITLE
Can only select the last 90 days of Issues

### ISSUE THREAD

**Issue by mnietz** [getsentry/sentry#47814]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Version

23.2.0

### Product Area

Issues

### Steps to Reproduce

After upgrading to 23.2.0 we are no longer able to select issues older 90 days from the issues-pages timepicker by choosing 'Absolute date'. Our sentry is configured in a way that it never should delete any issues (retention-period 9000). The logs from the cleanup-containers indicate, that the retention-period is used.

### Expected Result

Beeing able to review/count all issues

### Actual Result

Only the last 90 days of issues can be selected.

**Comment by hubertdeng123** [comment]
What version are you upgrading from? As far as I know, we've limited the retention period in snuba for issues to be 90 days maximum and that is reflected in SaaS.

**Comment by hubertdeng123** [comment]
I'm assuming you were on a pretty old version of self-hosted and unfortunately we don't have a solution for you here

**Comment by mnietz** [comment]
Thanks, we've upgraded from a 21 version. Is this somewehere documented?
