### ISSUE TITLE
Generate weekly reports by environment

### ISSUE THREAD

**Issue by sergiosentry** [getsentry/sentry#47826]
### Product Area

Unknown

### Problem Statement

The weekly summary reports send data from every environment in a project, where some of the data from those environments (like staging) might not be as important for the customer and might not always depict an accurate representation of "live data"

### Solution Brainstorm

To have a setting to define a "default" environment for weekly reports

**Comment by harshal-shah** [comment]
@sergiosentry This is closed without any activity. Can you please reopen and ensure some movement happens on this problem?
