### ISSUE TITLE
Replays showing duplicate requests in network tab

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry#47922]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

navigate to [https://sentry.sentry.io/replays/javascript:fc8751217ea44aafac914156432b0078/?n_detai[…]s_n_by=size&statsPeriod=14d&t_main=network&yAxis=count%28%29](https://sentry.sentry.io/replays/javascript:fc8751217ea44aafac914156432b0078/?n_detail_row=0&n_detail_tab=response&project=11276&query=&referrer=%2Freplays%2F&s_n_asc=false&s_n_by=size&statsPeriod=14d&t_main=network&yAxis=count%28%29)

### Expected Result

i see one request per one made in the replay.

### Actual Result

I see three.

### Product Area

Replays

**Comment by bruno-garcia** [comment]
<img width="635" alt="image" src="https://user-images.githubusercontent.com/1633368/234387456-5cc04389-a20d-487b-b0ba-e11f0d789e2a.png">

Hovering also seems to 'select' 3 at a time

**Comment by ryan953** [comment]
> Hovering also seems to 'select' 3 at a time

Three are selected because they all share the same timestamp.
