### ISSUE TITLE
N+1 Issue in /api/0/organizations/{organization_slug}/users/

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry#47926]
On this transaction for `/api/0/organizations/{organization_slug}/users/
` there are two N+1 issues. Are they related to Hybrid Cloud / Team Roles?

This makes the endpoint extremely slow, and I imagine also hammers our postgres database.

https://sentry.sentry.io/performance/sentry:ca5b62338d51492b9a6b60f46e0fd56e/?project=1&query=&referrer=performance-transaction-summary&showTransactions=slow&statsPeriod=14d&transaction=%2Fapi%2F0%2Forganizations%2F%7Borganization_slug%7D%2Fusers%2F&unselectedSeries=p100%28%29

```
SELECT sentry_useravatar.id, sentry_useravatar.file_id, sentry_useravatar.ident,
       sentry_useravatar.user_id, sentry_useravatar.avatar_type
FROM sentry_useravatar
WHERE sentry_useravatar.user_id = %s
ORDER BY sentry_useravatar.id ASC
LIMIT 1
```

```
SELECT sentry_team.slug, sentry_team.org_role
FROM sentry_team
INNER JOIN sentry_organizationmember_teams ON (sentry_team.id = sentry_organizationmember_teams.team_id)
WHERE (sentry_organizationmember_teams.organizationmember_id = %s
       AND NOT (sentry_team.org_role IS NULL))
```

**Comment by markstory** [comment]
Closing this as I'm pretty sure this is fixed.
