### ISSUE TITLE
Implement field which specifies whether debug id or release has been using for un-minification

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#47968]
For better error handling, we would like to clearly communicate to the frontend what we used for un-minifying a specific stackframe. Currently we have `data.sourcemap` which contains a URL of the sourcemap used for resolution but since the URL can contain anything, we would need an additional field like `resolved_with` which can have values:
- `debug-id`
- `release`
- `release-old`

In the frontend we should use this value to determine what is the resolution state of the frame by also looking at the SDK version, debug ids in the frames and release/dist.

**Comment by iambriccardo** [comment]
Synced with @Swatinem, we might only do this on the symbolicator side.

**Comment by iambriccardo** [comment]
We require also work on the `artifact-lookup` endpoint.
