### ISSUE TITLE
Replay "restart" button does not correctly reset player.

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry#47963]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

watch a replay. then hit "restart replay"

### Expected Result

the replay is taken back to the beginning and starts over

### Actual Result

the replay is frozen on the last screen from the end of the replay, at least it looks like until the next full checkout happens in the replay player

### Product Area

Replays

**Comment by ryan953** [comment]
rrweb 2.0 might help with this.

the code hasn't changed in >10months or something, so i don't think this is a big blocker for people trying to use the product right now.

**Comment by michellewzhang** [comment]
is this bug still happening?
