### ISSUE TITLE
github-app settings require also github-login settings

### ISSUE THREAD

**Issue by jakubgs** [getsentry/sentry#47984]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Deploy `23.4.0` version a self-hosted with multiple-organizations enabled
2. Configure GitHub Application using `github-app.*` settings
3. Attempt to connect the Sentry organization to GitHub organization
4. See `404` error due to empty `client_id` in the redirect URL
5. Add `github-login.client-id` and `github-login.client-secret` with same values as `github-app` counterparts
6. See the `404` error go away

### Expected Result

I'd expect only the `github-app.*` settings to be necessary when using a GitHub App. Instead the `github-login` ones are necessary.

### Actual Result

Just `404` when clicking `Configure` for GitHub in Authentication section of organization settings.

### Product Area

Settings - Auth

### Version

23.4.0

**Comment by hubertdeng123** [comment]
Hey there, just looking at our code and it looks like you would need to set `github-login.*` for multi-organization setups. Setting `github-app.*` options don't do anything

https://github.com/getsentry/sentry/blob/master/src/sentry/runner/initializer.py#L317

**Comment by jakubgs** [comment]
Right, then that might be worth mentioning in the docs, wouldn't it?
https://develop.sentry.dev/self-hosted/sso/#github-auth
The example doesn't mention it. Or even better, add some kind of `assert` that triggers when `github-app` settings are set but not `github-login` in a multi-org setup?

**Comment by hubertdeng123** [comment]
Yep you're right, we can definitely make that clear in the docs. Thanks for bringing this up to us

I've put up a PR: https://github.com/getsentry/develop/pull/925

**Comment by jakubgs** [comment]
Although to be fair, a real solution would be using the `github-app` settings if the `github-login` ones are not set.

**Comment by jakubgs** [comment]
But thanks for updating the docs.

**Comment by chadwhitacre** [comment]
I'm gonna close this with the docs change. Not seeing momentum for the more comprehensive fix.
