### ISSUE TITLE
Perf: In Network details, the fully expanded objects can cause lag when switching between requests

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#47992]

**Comment by bruno-garcia** [comment]
Originally expanded to 1 level. Then we moved to 3. Perhaps go back to 2.

**Comment by ryan953** [comment]
Example where it's still slow to view details: [https://sentry.sentry.io/replays/javascript:48bd242ebe724f4e9fc46ad485860eae/?n_detai[…]s_n_by=size&statsPeriod=14d&t_main=network&yAxis=count%28%29](https://sentry.sentry.io/replays/javascript:48bd242ebe724f4e9fc46ad485860eae/?n_detail_row=1&n_detail_tab=response&project=11276&query=&referrer=%2Freplays%2F&s_n_asc=false&s_n_by=size&statsPeriod=14d&t_main=network&yAxis=count%28%29)

**Comment by ryan953** [comment]
Similar to  https://github.com/getsentry/sentry/issues/46428
