### ISSUE TITLE
Crons: mis-firing failure event?

### ISSUE THREAD

**Issue by Dave13h** [getsentry/sentry#48059]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a monitor with a schedule of `*/2 * * * *`, missed status of `30` and failed status of `60`
2. Run a script every 2 minutes that sends an `inprogress` event followed by an `ok` status.
3. View monitors on sentry.io website and observe it pingponging between OK and Failed even with no Failed event being sent?

![image](https://user-images.githubusercontent.com/13381774/234825485-37036aab-f6e1-4c3a-a33c-29cd815d0271.png)

### Expected Result

Status is consistently `ok`

### Actual Result

The Staging environment is running every 2 minutes, locally is just run adhoc for testing.

![image](https://user-images.githubusercontent.com/13381774/234825789-36ea779c-3a87-40cb-889d-4c1dc01c24d5.png)

Interestingly the `local` environment doesn't seem to ever go into `failed` even though its stale. The `Staging` one seems to flip between `ok` and `failed` every other check-in even though I can't see any failures in the log.

![image](https://user-images.githubusercontent.com/13381774/234826221-1d31204e-ad34-47d7-bb70-88888860a7c7.png)

The failure vs ok ratio is almost identical. Could there be a stale event that is continually stuck as failing perhaps?

### Product Area

Crons

**Comment by Dave13h** [comment]
Further testing, I believe this is related to the environment handling. I've created a new monitor with a different slug and it seems to behave better so far.

Also seems I can't pause the broken monitor.

**Comment by rjo100** [comment]
Hi! Thanks for writing in. We've identified both of the bugs you've identified here and are in the process of rolling out fixes. Let us know if they're still giving you trouble. Apologies for the issues and thanks again for the report.

**Comment by rjo100** [comment]
One more thing. Not sure if you're using this call pattern but be sure to call `PUT` with the guid of the check-in from the first `POST` call like the example here:
https://docs.sentry.io/product/crons/getting-started/http/#check-ins-recommended

Otherwise we currently mark that first check-in as a separate run from the finished check-in and one that never completed running.

**Comment by Dave13h** [comment]
Amazing, thank you so much!

We're using the PHP SDK implementation - https://docs.sentry.io/platforms/php/crons/

**Comment by rjo100** [comment]
Got it. Also make sure you're "closing" your in progress check-ins by including this line like in the docs
`id: $checkIn->getId(),`
https://docs.sentry.io/platforms/php/crons/
