### ISSUE TITLE
migrations for plugins should run before running service

### ISSUE THREAD

**Issue by sazary** [getsentry/sentry#4806]
Hi  
I've installed sentry using docker, and I'm using the latest version, which is 8.11 as of now. I added `sentry-plugins` to requirements and I ran `docker-compose run --rm web upgrade` and then `docker-compose up -d`, and the sentry was running. But when I wanted to add a new project, It returned an error which indicated that `nodestore_node` relation does not exist in postgres (sorry, I can't copy paste the actual error). By chance, I ran `docker-compose run --rm web upgrade` one more time, and this time it ran migrations that created `nodestore_node` relation among other tables which were needed by plugins, and I created project after that without any problem.
I'm not that expert on docker, so I don't know what the solution is. But I hope reporting this issue helps.  
Let me know if I can help any further :blush:

**Comment by mattrobenolt** [comment]
It sounds like it just didn't successfully run the first time. My guess, because this happens to a lot of people, is it ran out of memory while running migrations and was killed. 

Also, you shouldn't have to do anything special with plugins. Our official image has the, bundled in already.

**Comment by sazary** [comment]
I can assure you that it didn't print any errors. It printed a line for each migration it ran, and then exited clean. I did run it on a server with nearly 800mb of free RAM, is it insufficient?  
If adding `sentry-plugins` isn't necessary, may be we should mention it in installation guide.

**Comment by bogdanr** [comment]
I also had this issue with the latest version. Can't say if it ran out of RAM though. With sentry running my machine still has 1G of RAM free.

**Comment by nttdocomo** [comment]
I had the same issue on 8.22

**Comment by jplagostena** [comment]
Hi, today I cloned the onpremise repo and after executing install.sh the plugins' migrations were missing.

After running `docker-compose run --rm web upgrade` after the initial install.sh was all finally set.
