### ISSUE TITLE
Sampling sessions at the user level 

### ISSUE THREAD

**Issue by pyeinblick** [getsentry/sentry#48090]
### Problem Statement

It makes it easier to track customer journeys and see the end-to-end process if I can sample at the user level and not the session level.

### Solution Brainstorm

Hash userid and filter based on that 

### Product Area

Replays

**Comment by bruno-garcia** [comment]
With the [SDK version 7.50.0 (released today)](https://github.com/getsentry/sentry-javascript/releases/tag/7.50.0) you can do that by controlling the recording programatically.

Docs didn't land yet (there's a [PR up though if you want to peek](https://github.com/getsentry/sentry-docs/pull/6735/files)).

**Comment by pyeinblick** [comment]
Amazing, yes, that would work I believe. Thanks @bruno-garcia 

(Unrelated, but heads up that your bot name is getsantry[bot] -- unless that's an ironic allusion to `Sanic`)
![image](https://user-images.githubusercontent.com/111363033/235009538-301d7db8-5b1e-4078-b8ef-eb176ad04184.png)
