### ISSUE TITLE
Slightly confusing alternate email UI

### ISSUE THREAD

**Issue by cameronmcefee** [getsentry/sentry#4809]
The UI for adding an alternative email is a little confusing, for a couple reasons:

- "New email" sounds like "Change my email"

- The "New email" field is a child of of the "Alternative Emails" section, but they have the same hierarchy as though they are individual sections.

Rather than make these form fields look like unique sections, it might be good to simplify the field and nest it under the "Alternative Emails" section. It probably needs a little more thought than my quick mockup, but something like this:

![screen shot 2017-01-23 at 11 02 46 am](https://cloud.githubusercontent.com/assets/72919/22218433/961f1f6a-e15b-11e6-87f6-6d93d20b7d3d.png)

cc @getsentry/ui

**Comment by kjlundsgaard** [comment]
There's an open PR for improvements to this UI if you'd like to leave comments on design [here](https://github.com/getsentry/sentry/pull/4415)

**Comment by cameronmcefee** [comment]
Ah nice, will do.
