### ISSUE TITLE
Possible for a user to choose an empty field for notifications

### ISSUE THREAD

**Issue by kjlundsgaard** [getsentry/sentry#4810]
It's still possible that a user can choose an empty field for email notifications in the notifications tab. Once the empty field has been chosen, the dropdown no longer appears.

![screen shot 2017-01-23 at 11 08 54 am](https://cloud.githubusercontent.com/assets/9269824/22218616/87eed984-e15c-11e6-9f3e-28f976cd8824.png)

**Comment by benvinegar** [comment]
We no longer let you choose a custom email destination per project.
