### ISSUE TITLE
Stats->Issues not displaying the correct stats

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/sentry#48113]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a project
2. Send error to Sentry instance
3. Go to Stats->Issues page
4. Observe that the stats there are all still 0

### Expected Result

stats on Stats->Issues page are not 0

### Actual Result

![Screenshot 2023-04-27 at 2 24 38 PM](https://user-images.githubusercontent.com/25517925/234994618-c83ee469-e3ab-479f-9c9e-8d567eb41d66.png)
![Screenshot 2023-04-27 at 2 24 08 PM](https://user-images.githubusercontent.com/25517925/234994622-2c519919-ec6c-4386-b00e-51e9532b3b09.png)

### Product Area

Stats

### Link

https://hubert-deng.sentry.io/stats/issues/

**Comment by scttcper** [comment]
This page is team based, the issue would have to be assigned to a specific team

**Comment by hubertdeng123** [comment]
ah, it's working as intended then. Thanks for the clarification
