### ISSUE TITLE
[doc-feature-request] Permissions required for API endpoints

### ISSUE THREAD

**Issue by zerkms** [getsentry/sentry#4814]
It would be super helpful if the api endpoints docs (eg https://docs.sentry.io/api/releases/post-release-files/) contained the required permissions. In this particular case: `project:releases`.

**Comment by MythriNagaraju** [comment]
@zerkms @dcramer Is this issue already resolved ? The project releases api endpoints docs seems to have the required permissions: https://docs.sentry.io/api/releases/post-project-release-files/

**Comment by zerkms** [comment]
@MythriNagaraju can you be more specific? I'm not sure I can see it.

**Comment by flamableconcrete** [comment]
Hello out of nowhere (I mean Hacktoberfest)! Clicking around on the various pages off of https://docs.sentry.io/api/releases/, it looks like each page documenting an API endpoint says what Scope it requires. To my untrained eye, it appears that this is what was requested initially - and while maybe it wasn't there 3+ years ago, it is definitely there now. I'm betting this issue could be closed.

**Comment by zerkms** [comment]
I think you're right, @flamableconcrete 

Thanks!

https://docs.sentry.io/api/releases/upload-a-new-project-release-file/
