### ISSUE TITLE
Bitbucket Integration Problem

### ISSUE THREAD

**Issue by cleyan** [getsentry/sentry#48158]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Settings
2. Integrations
3. Bitbucket
4. Add Integration
5. Select Workspace: I select the second workspace in my bitbucket account but the integration is always done using the first workspace listed
  
I tried to make a second integration but the result is always the same, don't make an integration using the second workspace listed

### Expected Result

Make an integration using the selected bitbucket workspace 

### Actual Result

Always the bitbucket integration is made using the first workspace listed on sentry

### Product Area

Settings - Integrations

### Link

https://leytec.sentry.io/settings/integrations/bitbucket/

**Comment by scttcper** [comment]
Can you take a screenshot of where you're selecting between the organizations?
