### ISSUE TITLE
date format not pasteable

### ISSUE THREAD

**Issue by nbrustein** [getsentry/sentry#48171]
### Problem Statement

Hello,

It seems like you recently changed the date format you use on the Issues page to show the time of a particular event.

The new format is prettier to my human eyes, but it can't be pasted into SQL, which is something I do a lot.

Just wanted to let you know about this unintended consequence of the change.

- Nate

### Product Area

Unknown

**Comment by malwilley** [comment]
@nbrustein thanks for the feedback! Understandable that you might want to copy/paste the full datetime in some circumstances.

Take a look at https://github.com/getsentry/sentry/pull/48223 and let us know if that solves your issue. You should be able to copy from the tooltip now 😄
