### ISSUE TITLE
Mistake in koa configuration instructions

### ISSUE THREAD

**Issue by noamnelke** [getsentry/sentry#4821]
In the [koa configuration instructions](https://docs.sentry.io/clients/node/integrations/koa/) there's a mistake on this line:

```
sentry.captureException(err, function (err, eventId) {
```

There's no symbol named `sentry`, it should be `Raven`.

**Comment by dcramer** [comment]
Closing in favor of https://github.com/getsentry/raven-node/issues/260

**Comment by LewisJEllis** [comment]
Fixed in getsentry/raven-node#261
