### ISSUE TITLE
Email unsubscribe link is broken

### ISSUE THREAD

**Issue by zerkms** [getsentry/sentry#4822]
Environment: Self-host Sentry 8.12.0, installed from pip.

The problem: when an email alert is received there is an unsubscribe link in the bottom of the email.

It looks like

    https://hostname.tld/account/notifications/unsubscribe/21/?_=1:xxxx:xxxxxxxxx

When I click it it redirects to the organisation root page with a red warning on the top

    The link you followed is invalid or expired.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
