### ISSUE TITLE
Remove status tag

### ISSUE THREAD

**Issue by NisanthanNanthakumar** [getsentry/sentry#48235]
![Image](https://user-images.githubusercontent.com/10491193/235276877-4e82e1f0-f35e-4043-be57-d12b937c9682.png)

Remove the hover over state

**Comment by RT-1904129** [comment]
Hi Team
Can you please assign me this task?I have relevant experience in this I will contribute and complete this
Thanks & Regards
Rishabh Tripathi

**Comment by scttcper** [comment]
no longer relevant
