### ISSUE TITLE
Update Activity records to display Archived/Escalating states

### ISSUE THREAD

**Issue by NisanthanNanthakumar** [getsentry/sentry#48232]
![Image](https://user-images.githubusercontent.com/10491193/235274465-e4ca256e-5d54-4199-90b0-7429af9f7615.png)

**Comment by therealarkin** [comment]
We need to update it from now on. That's a blocker.

It's nice to have to update it retroactively.

**Comment by brianthi** [comment]
The activity records should also indicate the threshold value, and the current event value which has caused it to escalate
