### ISSUE TITLE
[Implementation] Frontend/UI Changes for Connecting Replay to Backend Errors

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#48249]
The following frontend changes required for Connecting Replay to Backend Errors per our PRD:

~- Issues > Issue Details of Backend Platform that has replays associated > See replay preview/thumbnail if latest error has a replay under “Breadcrumbs”
When clicking preview, it brings you to the point of time of backend error in the replay
Also on Event Details (as found in Discover)~
~- (Must-have/MVP) Issues > Issue Details > All Events tab~
~- (Must-have/MVP) Issues > Issue Details (Backend) > Replays tab~

- [x] #48361
- [x] #48478
- [x] #48362
- [x] Replay Details > Trace tab should reflect backend errors - This already exists.
- [x] #48363

^ Note: The last bullet above is only place where we visually distinguish frontend errors from backend errors. This is what [the mocks](https://www.figma.com/file/VJffxPWvRaaRJ1gywzuUre/Specs%3A-Connecting-Backend-Errors?node-id=340%3A16919&t=F3gzC9N6dJ6f1Plg-1) show.

More info in [this doc](https://www.notion.so/sentry/FY-24-Q1-Connect-to-Backend-Errors-91a70a306d364dc88105cee1071d47d9?pvs=4#9591d15a4b9c418b9856131d4e895c1f) (Internal). 

EH: adding below to epic description so i can convert to tasks and it's front and center :) 
Small follow up UI/X fixes:
- [ ] #48466
- [ ] Replay Details > Filter backend errors out of console (TBD? - open slakck thread)

**Comment by eliashussary** [comment]
Relates to: https://github.com/getsentry/sentry/issues/45529

**Comment by eliashussary** [comment]
Small follow up UI/X fixes:
- [ ] Replay Details > Breadcrumb linking to issue tab
- [ ] Replay Details > Filter backend errors out of console?
