### ISSUE TITLE
UI: Issues date filter dropdown is not fully visible with absolute date enabled

### ISSUE THREAD

**Issue by artem-tarasenko** [getsentry/sentry#48246]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open the issues section
2. Open filtering by date dropdown
3. Pick the "Absolute date" option
4. See the UI

### Expected Result

Probably be able to see both the "absolute date" section and the list of specific time intervals.

### Actual Result

"Specific time intervals" section is not fully visible as it is overlapped by the side menu.

![2023-04-30_19-42-34](https://user-images.githubusercontent.com/71615921/235389628-1c3c4bcd-5b83-4231-be61-4dac90217592.png).

I wonder why any dropdown from filters is aligned to the top-left absolute position, but this particular dropdown (with both intervals and absolute date enabled) is aligned to the top-right (be it top-left as well it won't be under the side menu).

### Product Area

Issues

**Comment by malwilley** [comment]
This will be fixed by https://github.com/getsentry/sentry/issues/45074
