### ISSUE TITLE
Convert svgs -> pngs in emails

### ISSUE THREAD

**Issue by ceorourke** [getsentry/sentry#48255]
According to [this site](https://www.caniemail.com/features/image-svg/) most users won't be able to see svg icons in their emails anymore. I updated one [here](https://github.com/getsentry/sentry/pull/48162) after it was pointed out that it wasn't working, but we should update the rest in that template and others.

**Comment by ceorourke** [comment]
Noo agh idk how this works, just trying to get it on [this board](https://github.com/orgs/getsentry/projects/55/views/5)

**Comment by chadwhitacre** [comment]
@ceorourke Product Area labels are working for routing now, but since your goal was just to get this on a board and it's on the board I cleared the labels. :shrug:

**Comment by chadwhitacre** [comment]
Silly bot. 🙄
