### ISSUE TITLE
Download all events

### ISSUE THREAD

**Issue by Houd1ny** [getsentry/sentry#4835]
Is there some api to download all events of some issue?
For example I need to know how many events between two dates has tag build-version 1.0.0 for example

**Comment by dcramer** [comment]
Please see our docs as the API is outlined and our issue tracker isn't an appropriate place for general questions. 

docs.sentry.io

**Comment by Houd1ny** [comment]
Where should I ask this questions?

**Comment by dcramer** [comment]
Please take a look at our support section:

https://docs.sentry.io/support/
