### ISSUE TITLE
Alerting "Group By"

### ISSUE THREAD

**Issue by gid-sentry** [getsentry/sentry#48380]
### Problem Statement

Being notified if _any one_ endpoint spikes in its failure rate / response time / any other metric.   
At the moment it's possible to either look at the aggregated failure rate of all transactions, or create a separate alert for every endpoint I'm interested in.
It would be nice to be able to do this in a less tedious way

### Product Area

Alerts

**Comment by scttcper** [comment]
Metric alerts can select multiple endpoints and monitor error levels for example `title:/api/0/organizations/*`
