### ISSUE TITLE
[Discussion] Convert Issue State logic into a finite state machine.

### ISSUE THREAD

**Issue by NisanthanNanthakumar** [getsentry/sentry#48381]
## Objective:

The current state diagram of Issue States makes finite state machines an ideal solution to manage its complexity and side effects.

![Image](https://user-images.githubusercontent.com/10491193/235777911-0d7e195c-78d4-409e-8b6b-ac9c65663b84.png)

Right now, we have code all over the place to manage the side effects of state changes using django signals. But this is getting unwieldy. A state machine would let us explicitly define the state changes and all the side effects of each transition in one place.

This would be a large-ish upfront investment to refactor into a state machine, but I think the time saved on future additions and the reduced complexity in maintenance  is worth it.

Does this sound ok @wedamija ? cc: @armenzg @brianthi

**Comment by armenzg** [comment]
@NisanthanNanthakumar I think this is great, however, I would move it to after we get to closed beta OR push the closed beta date by at least a couple of weeks at a minimum (my hand waving estimation).

**Comment by wedamija** [comment]
This sounds like a good plan to me. I've always found it crazy that there's no central place where you mark an issue resolved, and that the code just lives in an api somewhere.

I think I agree with @armenzg to not let this block the closed beta. There's a lot of extra complexity in the resolve workflow when you include things like resolve in release/commit that might complicate this process as well.
