### ISSUE TITLE
Note in settings not displayed correctly

### ISSUE THREAD

**Issue by timothyis** [getsentry/sentry#48421]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to project settings as a non "business" account
2. Click on "inbound filters"

### Expected Result

Should be able to read the note about custom release and error message filtering note

### Actual Result

![image](https://user-images.githubusercontent.com/1695613/235883657-5b01ac58-0160-4cc6-af17-9fe583ae7840.png)

### Product Area

Settings

### Link

https://{org}.sentry.io/settings/projects/{project}/filters/data-filters/

**Comment by cathteng** [comment]
hello, taking a look at this. which browser are you experiencing this in?
