### ISSUE TITLE
Sentry Alert Slack Notification Formatting

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry#48449]
IMO this looks unpolished.

- The latency number should certainly be rounded 
- anything over a couple of hours should be formatted as hours / days, not minutes
![Screenshot 2023-05-03 at 10 44 18 AM](https://user-images.githubusercontent.com/1976777/236001083-80cf44a6-7691-4816-b75c-db3602f2f448.png)

**Comment by ceorourke** [comment]
All fresh now: https://docs.sentry.io/changelog/more-context-in-slack-alerts/
