### ISSUE TITLE
Sentry Alert Display of Fire Timing

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry#48457]
I have an alert with the following criteria:
![Screenshot 2023-05-03 at 11 03 19 AM](https://user-images.githubusercontent.com/1976777/236005011-ccd47e19-0a75-468b-bc5e-50f2cd7386e1.png)

I find it strange that the "Date triggered" and date shown on the chart are different. the date shown on the chart seems to be the date at which the window of the trigger starts, as opposed to the end of the window and the present time. Is this deliberate? 
![Screenshot 2023-05-03 at 11 03 13 AM](https://user-images.githubusercontent.com/1976777/236005238-7f40200e-730d-4fdd-b859-8dc0cdac3c75.png)

**Comment by scttcper** [comment]
We're drawing the red line at the date it was "started" which is the time it was triggered - the interval.

**Comment by JoshFerge** [comment]
@scttcper this is confusing to me as a user, but if its intentional, i guess that's okay.
