### ISSUE TITLE
Display for the count() and count_unique() seems to be reversed in Dicover graph

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#48452]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Select both count() and count_unique() to show in the Y-Axis in Discover 
2. Observe the graph seems to reverse count() and count_unique() 

Link to example discover page: https://org2-w7.sentry.io/discover/homepage/?display=default&end=2023-03-27T23%3A59%3A59&field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&name=All+Events&project=6229212&query=&sort=-timestamp&start=2023-03-26T00%3A00%3A00&utc=true&yAxis=count%28%29&yAxis=count_unique%28user%29

<img width="448" alt="image" src="https://user-images.githubusercontent.com/99350819/235995303-c80884ba-29f1-41f1-a027-e1c97cc32380.png">

### Expected Result

the count() and count_unique() is reflected accurately on the graph

### Actual Result

the count() and count_unique() is not reflected accurately on the graph

### Product Area

Discover

### Link

https://org2-w7.sentry.io/discover/homepage/?display=default&end=2023-03-27T23%3A59%3A59&field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&name=All+Events&project=6229212&query=&sort=-timestamp&start=2023-03-26T00%3A00%3A00&utc=true&yAxis=count%28%29&yAxis=count_unique%28user%29

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1819) by [Unito](https://www.unito.io)

**Comment by silent1mezzo** [comment]
Hey @kerenkhatiwada the graph is showing the values correctly. Stacked area charts always stack the values on top of one another and are exclusive of what's below (e.g. the yellow isn't the blue + yellow, it's just the yellow).
