### ISSUE TITLE
Sentry Alert Pagination Seems Broken

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry#48453]
click this link: https://sentry.sentry.io/alerts/rules/?cursor=-1%3A0%3A1&expand=latestIncident&expand=lastTriggered&name=Endpoint+is+getting+slow%3A&project=1&sort=incident_status&sort=date_triggered&team=myteams&team=unassigned 

It is a link to the alerts page with a search filter. Most of the time, if i click the "next page" arrow, it somehow will not paginate / duplicate items from the previous page. If you can't get it to happen, refresh and try again. I can also link a replay if it is proving hard to debug.

**Comment by brianthi** [comment]
@JoshFerge a replay would help, I wasn't able to reproduce

**Comment by JoshFerge** [comment]
@brianthi: https://sentry.sentry.io/replays/javascript:d6b634ed710446ef9187fd995a273141/?f_n_search=combined-rules&f_n_type=resource.fetch&f_n_type=resource.xhr&n_detail_row=&n_detail_tab=response&project=11276&query=&referrer=%2Freplays%2F&statsPeriod=14d&t_main=network&yAxis=count%28%29

see in the network tab, the responses don't seem to be paginating and include the same data twice. Here is a screenshot below where you can see the same data being included in subsequent requests.

**Comment by JoshFerge** [comment]
@brianthi and looking at the replay that you triggered, it looks like you did replicate the issue: https://sentry.sentry.io/replays/javascript:ca201b92e61441b38ddf05216d965a97/?project=11276&query=user.email%3Abrian.thi%40sentry.io&referrer=%2Freplays%2F&statsPeriod=14d&yAxis=count%28%29

**Comment by JoshFerge** [comment]
@brianthi do you need more information?

**Comment by JoshFerge** [comment]
I believe this is issue still exists in prod.

**Comment by hubertdeng123** [comment]
Looks like this issue is still relevant.

**Comment by ceorourke** [comment]
@JoshFerge I rewrote the pagination not too long ago: https://github.com/getsentry/sentry/pull/51763 is it still an issue?

**Comment by JoshFerge** [comment]
> @JoshFerge I rewrote the pagination not too long ago: #51763 is it still an issue?

yes looks good thank you!
