### ISSUE TITLE
Issue Details UI: Auto-collapse context data with large numbers of items

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#48480]
Context JSON data (in the "additional data" section of issue details) will auto-collapse objects and arrays that are at least one-level down. However, there are sometimes very long lists on the root level of the object which can make the section very long. We should look at the number of keys to decide whether or not to begin collapsed.

**Comment by mwarkentin** [comment]
Here's a good example event if you want to see the issue: https://sentry.sentry.io/issues/4115309411/?project=4505048029986816&query=+is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=14d&stream_index=0
