### ISSUE TITLE
GitHub integration: a repository with that name already exists

### ISSUE THREAD

**Issue by stellaatsentry** [getsentry/sentry#48504]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Uninstall the GitHub integration
2. Install the GitHub integration anew
3. Re-add the repositories that had been added in the previous iteration of the integration

### Expected Result

All repositories are added normally.

### Actual Result

Most repositories are added normally but when trying to add one of them, the error "a repository with that name already exists" appears.

![image](https://user-images.githubusercontent.com/81985895/236134588-220099c3-43dd-4932-83b4-75709e489860.png)

This repository does not exist under the "Repositories" tab so it is unclear why this is happening.

[Zendesk ticket](https://sentry.zendesk.com/agent/tickets/84500).

### Product Area

Settings - Integrations

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1820) by [Unito](https://www.unito.io)

**Comment by scefali** [comment]
It's a weird edge case bug that happened upon renaming, I followed up in Zendesk

**Comment by 0xcaff** [comment]
This is happening for us to. Where do we get help for this?

**Comment by stellaatsentry** [comment]
@0xcaff You can open a support ticket and we will be happy to assist you. Please make sure to include the link to this GH issue in your support ticket.
