### ISSUE TITLE
[Layout Flexibility Improvement] Replay Details To Be Taller Than the Window Height

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#48529]
**Problem:**

For mobile-orientation replay videos, the replay video and the breadcrumb area both have to fit on the screen so they're both smaller than desired for some customers. As a result of the Replay Details page being constrained to the window height.

Customer quote:

> _I would like this whole page to be scrollable and be able to expand both the replay and breadcrumb views as much as I want, which is probably like 3 times taller than they can go right now. In the absence of this flexibility, I go to the full-screen replay view, but then am annoyed that I can't see the breadcrumbs as the replay progresses._

**Solution Proposal:**

Replay Details to be taller than window height.

**Comment by ryan953** [comment]
related to https://github.com/getsentry/team-replay/issues/199
