### ISSUE TITLE
Deleted Replay Still Appearing in List

### ISSUE THREAD

**Issue by masinette** [getsentry/sentry#48553]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1.  Select Replay from main list
2. View details and select 'Delete' icon, and confirm
3. Navigate back to main list
4. Error appears instead of details page: "Page not found"

### Expected Result

Replay is removed from main list

### Actual Result

Replay still appears in main list despite being deleted

### Product Area

Replays

**Comment by JoshFerge** [comment]
running queries. will comment back when we have more data.
