### ISSUE TITLE
Set global timezone for a dashboard

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry#48584]
### Problem Statement

Opening on behalf of a customer:

> We have developers all over the world, so want to make sure that when we’re talking about specific time windows, it is clear that we’re all talking about the same exact window. So, we want the ability for dashboards to show in Pacific Time regardless of where the developer using Sentry is located.

To my understanding, [timezone is an individual setting](https://sentry.zendesk.com/hc/en-us/articles/115006562707-How-can-I-change-the-timezone-in-Sentry-) and cannot currently be globally set for dashboards. 

### Solution Brainstorm

A possible solution here would be to scope timezone settings to individual dashboards, and also make it clear when viewing a given dashboard, that time is being shown in PST or whatever timezone.

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1823) by [Unito](https://www.unito.io)

**Comment by brentc** [comment]
Thanks for the feedback @cstavitsky. It's can be really tricky to provide too much flexibility here because date conversion to/from/between local/utc/arbitrary offset gets complicated quickly. But we'll backlog this request and consider it against future priorities.

**Comment by ale-cota** [comment]
We are prioritizing work based on company-wide initiatives, community demand, and activity on issues. This issue doesn't have any upvotes, has seen little activity and hasn't been touched recently. We're therefore closing it to keep our backlog maintainable and transparent. 

Please feel free to leave a comment if you think this issue should be reopened.
