### ISSUE TITLE
Request to have FullStory button on slack mes

### ISSUE THREAD

**Issue by aumni-sorce** [getsentry/sentry#48609]
### Problem Statement

We would like to know if it's possible to add a button to the issue slack message to go to FullStory. I've attached a screenshot for more info.

Thanks

### Solution Brainstorm

See screenshot:

<img width="460" alt="Screenshot 2023-05-03 at 10 43 44 PM" src="https://user-images.githubusercontent.com/99351177/236377178-b76a0df5-c7ef-4d94-89ba-448051ec1d9c.png">

### Product Area

Settings - Integrations

**Comment by jas-kas** [comment]
Hey @aumni-sorce,

Thanks for reaching out to the team! Unfortunately, there are no plans to include a link to the associated replay from the FullStory integration in our Issue Slack notifications. However, Sentry will be adding a link to a replay associated with a given issue, from [Sentry's Session Replay](https://sentry.io/for/session-replay/) product. 

Please let me know if you have any other questions.
