### ISSUE TITLE
Low Volume Projects bias needs to give 100% to projects without traffic

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#48623]
We have a suspicion that projects that don't get any traffic in the last X hours are not included in the low project volume bias and therefore are not boosted to 100%.

We need to ensure this works correctly and projects without any traffic in the last X hours get boosted to 100%. If you have a website that gets a visitor once a day - you better be ready for them and index everything.

**Comment by iambriccardo** [comment]
Waiting for @beezz opinion on the query's complexity.
