### ISSUE TITLE
[Design] Notify Discover only shows indexed MVP

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#48622]
**Problem**: This ticket aims to address the same problem as [getsentry/sentry#47811](https://github.com/getsentry/sentry/issues/47811) with a short term solution. The target solution requires [work to adapt the discover API ](https://github.com/getsentry/sentry/issues/48633)from the D&D/Starfish/Performance teams and might take time.

**Proposed Solution**: In the meantime, we could display a static/generic message that informs the user that what they're looking at is sampled data.

**Comment by Jesse-Box** [comment]
@ale-cota @Prithvirajkumar see [Figma link](https://www.figma.com/file/LyKAQlCcIrKn7o0lcC79Tq/Specs%3A-Sampled-Data-Banner-v1?type=design&node-id=0%3A1&t=1NNzunqzzp9LnIOW-1)

I don't have a strong preference, but I'd imagine Concept B will be the more successful one.

**Comment by ale-cota** [comment]
@Jesse-Box I like it 😄  left some feedback.

**Comment by priscilawebdev** [comment]
Concept B is also my favorite as the alert is located at the top of the graph which is also affected if the data is metric or sampled data

**Comment by Jesse-Box** [comment]
Closing this ticket

Concept B is preferred

Points worth mentioning for frontend implementation.
* The banner can be dismissed
* The banner is dismissed on a per-user level.
