### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by defrex** [getsentry/sentry#48656]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Sentry > Settings > Integrations > Github
2. Click "Add Installation"
3. Don't have Owner/Manager permissions, so the process fails
4. Get Order/Manager permissions
5. Try again, this time the auth works, and your redirected to the Github Sentry Organization settings
6. Go back to Sentry > Settings > Integrations > Github
7. Will still be listed as "Not Installed" with no way to change it

### Expected Result

There should be a way to tell Sentry that the Github app is installed so that it can connect the Github org to the Sentry org.

### Actual Result

Github is listed as "Not Installed"

### Product Area

Settings - Integrations

### Link

https://optimus-2h.sentry.io/settings/integrations/github/

### DSN

https://7e649ef5aba348a8a947e8e2a262ddd4@o4505132861489152.ingest.sentry.io/4505132865028096

**Comment by Kobby-Bawuah** [comment]
Sometimes if the connection fails for some reason please try the following:

- Remove the Sentry integration from the GitHub application settings - https://github.com/settings/installations
- Go through the installation process again through Sentry -> Try in an incognito browser to ensure you're linking to the correct GitHub instance.

Just a note: 
- Ensure you do not have the GitHub instance installed in a different sentry organization
- A user with [Owner or Manager](https://docs.sentry.io/product/accounts/membership/) permissions needs to install the integration by following the guide [here](https://docs.sentry.io/product/integrations/github/). 
- They also need to have owner permissions on the Github repo.

**Comment by defrex** [comment]
That worked, thanks!

Might be worth adding some kind of help text or documentation for this case, as it was pretty easy to trip into, and there was no obvious way out.
