### ISSUE TITLE
Remove duplicate Express from project selection

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#48687]
### Problem Statement

When I want to create an Express project sentry gives me 2 options with no clear difference

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/47563310/236791459-13ac4112-ee59-4c1c-a759-ee6cdaa49e0f.png">

### Solution Brainstorm

Remove duplicate. There is already a generic Node

### Product Area

Projects

**Comment by smeubank** [comment]
one is actually linked to project platform = `node-serverlesscloud`

so I would just remove that one (circled in screenshot below), the snippets appear to be the same. And serverless is managed by the dedicated ones for Azure, AWS, and GCP respectively

<img width="307" alt="image" src="https://github.com/getsentry/sentry/assets/47563310/05aaef75-e221-4f39-bb5c-39a7f81f26b5">

**Comment by ale-cota** [comment]
@smeubank, should we re-use the icon for the other one actually? I'm just thinking it's maybe good to keep "node" in there as well 🤔

**Comment by smeubank** [comment]
@ale-cota There is a pure node platform with icon to select. IMO the express one should have the express logo with the node smaller logo as it is now

**Comment by priscilawebdev** [comment]
closing this issue as this was fixed 

![Image](https://github.com/getsentry/sentry/assets/29228205/a79141ba-6e48-4526-870e-7c309fc9fb6e)
