### ISSUE TITLE
Auth tokens and API Keys are hard to find

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#48690]
### Problem Statement

When setting up a project I need an auth token to create releases and upload source maps for example

Unless going through some automated flow, it is very hard to understand as a new user what key is being referred to and where to find it in Sentry

Can be found in Project settings > SDK Setup > Releases and then under the webhook section as a param of the URL in the cURL snippet there, but I only know that is what it is by recognition

<img width="949" alt="image" src="https://user-images.githubusercontent.com/47563310/236801199-46dc39d9-c691-4e73-bf4e-93776bbc5ad6.png">

### Solution Brainstorm

1. should be searchable cmd + k
2. should be in a logically easy place to find
3. consider this as part of onboarding 
  - (risk) adds complexity to onboarding 

### Product Area

Projects

**Comment by danielkhan** [comment]
With
> consider this as part of onboarding

you mean that this should be automated during onboarding, correct, @smeubank?

**Comment by ale-cota** [comment]
This is at this point duplicated by https://github.com/getsentry/team-webplatform-meta/issues/67
