### ISSUE TITLE
Prioritize replays for specific errors

### ISSUE THREAD

**Issue by tomukasas** [getsentry/sentry#48698]
### Problem Statement

Let's say I want to get to the bottom of the error X, which happens when users use the app in specific way. At the moment the replays are generated for all errors, which eats up replays quota quickly and there are no replays logged for the error X I'd like to get more details on.

### Solution Brainstorm

This potentially could work in a similar fashion `ignoreErrors` and `denyUrls` works at the moment, where I could supply a list of the errors I'd like to be prioritized. I imagine regex matching would be beneficial too.

### Product Area

Replays

**Comment by bruno-garcia** [comment]
This can be done now through `beforeErrorSampling`. More detail on the docs: https://docs.sentry.io/platforms/javascript/session-replay/configuration/

Please update to the latest version of the SDK to get this API
