### ISSUE TITLE
Gitlab integration installation producing an error

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#48710]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Org Settings > Integrations
2. Gitlab  
3. Add Installation
4. this screen (example from docs):
<img width="759" alt="image" src="https://user-images.githubusercontent.com/8920574/236882589-0984e179-d09e-4fcc-bd1c-07044b50284c.png">

**Error in UI says:**
"Whoops! Looks like something went wrong! Give that another try
An error occurred while validating your request"

**More Context**
see this [FEEDBACK-1828](https://getsentry.atlassian.net/browse/FEEDBACK-1828) for the customer's:
- screenshot of their config, screenshot of their Chrome.network tab
- Gitlab link to the Gitlab org they want to add (and it has a repo shown)
- Sentry repo list
- Sentry gitlab integration

**Brainstorming**
Compare config versus first Gitlab installation that was added successfully, including what that gitlab org looks like in the Gitlab UI., and think about what role this plays in the domain and Gitlab Path URL you have to write in the Sentry UI when configuring.

User says they spent a lot of time re-checking permissions and various things on the Gitlab side on what may be different between their two Gitlab Orgs.

### Expected Result

No errors, it should be successfully added like their other gitlab app/org that got added.

### Actual Result

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/8920574/236881355-636ba20c-3e24-4d1c-9465-713894ff1cc5.png">
could not find anything useful in Chrome.console Chrome.network tabs, see JIRA ticket.

### Product Area

Settings - Integrations

[FEEDBACK-1828]: https://getsentry.atlassian.net/browse/FEEDBACK-1828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by armenzg** [comment]
I looked at the JIRA ticket and it may be something simple to solve.

**Comment by thinkocapo** [comment]
Reopening because I updated mentions of 'repo' to 'org. Problem was with adding an Org Installation and not adding a Repo.

Same screenshots are still applicable, for how they add the org and what is the result outcome.

**Comment by armenzg** [comment]
I believe we should be closing this issue as the customer should not be trying to install the integration for a user account but an org account.

**Comment by miekekepieke** [comment]
I have the same issue.

**Comment by armenzg** [comment]
As per the docs:
> Q: My repositories are hosted under my user account, not a group account. Can I still use this integration?
> A: Unfortunately, not. The GitLab integration only works for repositories that are hosted under group accounts.
