### ISSUE TITLE
Linear issue - Error communicating with Sentry App service

### ISSUE THREAD

**Issue by nonameolsson** [getsentry/sentry#48765]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open an issue
2. Create a Linear issue
3. Fill in form
4. Press "Save changes"

### Expected Result

Linear issue should be successfully created

### Actual Result

Error message: "Error communicating with Sentry App service"

**Request headers**
```
POST /api/0/sentry-app-installations/c2d79393-ed33-47ae-991d-652826e4fa4e/external-issue-actions/ HTTP/1.1
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 3228
.....
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
accept: application/json; charset=utf-8
baggage: ...
content-type: application/json
sec-ch-ua: "Chromium";v="113", "Not-A.Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-gpc: 1
sentry-trace: 87c1aa522ce24b11b344dc39366eb747-bc98e9e9d2bc4898-0
x-csrftoken: ...

```
**Request payload**
```json
{
    "groupId": "3984578391",
    "action": "create",
    "uri": "/hooks/sentry/issues/create",
    "title": "Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may ...",
    "description": "Sentry Issue: [XXX-API-4W](https://XXX-XXX.sentry.io/issues/3984578391/?referrer=Linear)\n\n```\nMicrosoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.\n  ?, in void AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(int commandIndex, int expectedRowsAffected, int rowsAffected)\n  ?, in async Task<int> AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagationAsync(int commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)\n  ?, in async Task AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)\n  ?, in async Task ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken) x 2\n  ?, in async Task<int> BatchExecutor.ExecuteAsync(IEnumerable<ModificationCommandBatch> commandBatches, IRelationalConnection connection, CancellationToken cancellationToken) x 3\n  ?, in async Task<int> StateManager.SaveChangesAsync(IList<IUpdateEntry> entriesToSave, CancellationToken cancellationToken) x 2\n  ?, in async Task<TResult> SqlServerExecutionStrategy.ExecuteAsync<TState, TResult>(TState state, Func<DbContext, TState, CancellationToken, Task<TResult>> operation, Func<DbContext, TState, CancellationToken, Task<ExecutionResult<TResult>>> verifySucceeded, C...\n  ?, in async Task<int> DbContext.SaveChangesAsync(bool acceptAllChangesOnSuccess, CancellationToken cancellationToken) x 2\n  File \"/src/XXX.ZZZ.DataAccessEFCore/Services/AuditService.cs\", line 576, col 9, in async Task AuditService.DeleteFavoriteAudit(int FavoriteAuditId)\n  File \"/src/XXX.ZZZ-API/Controllers/AuditsController.cs\", line 370, col 13, in async Task<IActionResult> AuditsController.DeleteFavoriteAudit(int FavoriteAuditId)\n  ?, in async ValueTask<IActionResult> TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)\n  ?, in async Task ControllerActionInvoker.InvokeActionMethodAsync()+Awaited(?)\n  ?, in async Task ControllerActionInvoker.InvokeNextActionFilterAsync()+Awaited(?)\n  ?, in void ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n  ?, in Task ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)\n  ?, in async Task ControllerActionInvoker.InvokeInnerFilterAsync()+Awaited(?)\n  ?, in async Task ResourceInvoker.InvokeNextExceptionFilterAsync()+Awaited(?)\n```",
    "priority": "",
    "teamId": "25bf3326-8726-47ff-a62a-bbc87db43dce",
    "assigneeId": "",
    "labelId": "f2ac27e9-4f44-49df-9b26-971dcf6a6814",
    "projectId": "",
    "stateId": ""
}
```

**Response**
```json
{"error":"Error communicating with Sentry App service"}
```

### Product Area

Issues

### Link

https://{XXX-ZZZ}.sentry.io/issues/3984578391/?project=6013835

**Comment by armenzg** [comment]
Hi @nonameolsson thank you for filing.

Has this worked for you before? Would you be able to provide a link to one of your issues and I can have a peek?

If you would rather not share a link publicly, you can create a customer support ticket and share the link privately there. Please make a reference to this ticket.

**Comment by nonameolsson** [comment]
> Hi @nonameolsson thank you for filing.
> 
> Has this worked for you before? Would you be able to provide a link to one of your issues and I can have a peek?
> 
> If you would rather not share a link publicly, you can create a customer support ticket and share the link privately there. Please make a reference to this ticket.

Thank you! I have contacted you through customer support, where I included a link to this issue. 👍🏻

**Comment by armenzg** [comment]
Great. I've set a reminder to look at it on Monday. Thanks for your patience!

**Comment by armenzg** [comment]
Hi @nonameolsson 
I noticed the for issue 3984578391 you have a Linear link.

Did this start working for you?

I also tried in issues/2296224124/?project=1314009 and it worked.

**Comment by armenzg** [comment]
You may want to delete the linear Issue I created for that issue and apologize to whoever got surprised by it!

**Comment by armenzg** [comment]
I think it may have been a Linear issue since we have not changed anything.

For anyone coming along later, this is the API that we hit once we hit save:
https://SLUG.sentry.io/api/0/sentry-app-installations/<some_id>/external-issue-actions/

This is the code handling the post event:
https://github.com/getsentry/sentry/blob/c3deb64333005d4baf5083809122be4f00db5003/src/sentry/api/endpoints/integrations/sentry_apps/installation/external_issue/actions.py

**Comment by nonameolsson** [comment]
> Hi @nonameolsson I noticed the for issue 3984578391 you have a Linear link.
> 
> Did this start working for you?
> 
> I also tried in issues/2296224124/?project=1314009 and it worked.

Thanks for looking into this @armenzg!
I still have the issue, and I have done a screen recording of this. What would be a good way to pass it on to you privately?

**Comment by armenzg** [comment]
@nonameolsson Via Zendesk

**Comment by nonameolsson** [comment]
> @nonameolsson Via Zendesk

Perfect, thanks! I did include the video recording on Zendesk now.

**Comment by armenzg** [comment]
For whoever end up working on this.
The Zendesk related issues are [this](https://sentry.zendesk.com/agent/tickets/85802) and [this](https://sentry.zendesk.com/agent/tickets/86711).
