### ISSUE TITLE
Locked environment not persisting on project change

### ISSUE THREAD

**Issue by samuelhwilliams** [getsentry/sentry#48771]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Sentry team plan with a few projects
2. Go to the issues dashboard
3. Pick a project and then lock onto a specific environment (eg production)
4. Change project

### Expected Result

The locked environment is retained for the new project (where possible)

### Actual Result

It falls back to 'all envs'

![2023-05-09 12 44 05](https://github.com/getsentry/sentry/assets/2920760/2751810b-2268-4995-a01a-4b78f9f597c7)

### Product Area

Issues

**Comment by armenzg** [comment]
@samuelhwilliams thank you for filing!

**Comment by scttcper** [comment]
should be fixed
