### ISSUE TITLE
Force users to ignore issues based off "Until X" / "For X" Option

### ISSUE THREAD

**Issue by sentryadam0000345** [getsentry/sentry#48847]
### Problem Statement

Filing feedback on behalf of [Ramp](https://ramp.com/business-cards?utm_campaign_id=17802544987&utm_ad_group_id=137857912686&utm_ad_id=611479329319&utm_term=ramp&utm_campaign=google-search-rlsa-branded&utm_source=google&utm_medium=cpc&hsa_acc=5740001625&hsa_cam=17802544987&hsa_grp=137857912686&hsa_ad=611479329319&hsa_src=g&hsa_tgt=aud-1015283010850:kwd-27557331&hsa_kw=ramp&hsa_mt=e&hsa_net=adwords&hsa_ver=3&gad=1&gclid=CjwKCAjw3ueiBhBmEiwA4BhspEMepJOHtwJfLEuUoW9jtYXX01iizJT3-CCeVOJ-IViF5XFZV56oOxoCIVsQAvD_BwE) 

Basically, they wish to force the above behavior as documented [here](https://docs.sentry.io/product/issues/states-triage/#ignore).  

**The reason being:**

They don't want a dev/individual contributor to have the option, at all, to permanently ignore an issue.  Because there can be ignored issues that may have not been real problems in the past but they now are.  

### Solution Brainstorm

Provide some kind of permission on one of the user members levels [here](https://docs.sentry.io/product/accounts/membership/#membership).

### Product Area

Issues

**Comment by therealarkin** [comment]
We are changing the ignore mechanism in the next 4 weeks (https://github.com/getsentry/sentry/discussions/43039). Let's see if the new behavior addresses the core issue and re-open if not.
