### ISSUE TITLE
How to avoid attacks that consumes a lot of API calls and thus money?

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry#48860]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Hi thanks for the product! I wonder how to avoid attacks that consumes a lot of API calls and thus money? I am not an expert in security, but I know there is CC and DDOS attack. So from my understanding, the attacker can send a ton of "valid" requests to sentry server, pretending he is my app and is reporting an exception. Then, the attacker can easily cost me high price because it is not hard to trigger a ton of requests to Sentry. Since the DSN is public (you know, hardcoded in app), I also cannot hide it. 

### Expected Result

-

### Actual Result

-

### Product Area

Unknown

**Comment by fzyzcjy** [comment]
@kerenkhatiwada Dart/Flutter. However, IMHO this is unrelated to particular SDK, but is indeed related to the server. For example, an attacker can use the server API directly and send HTTP POST requests instead of using any SDK

**Comment by Dhrumil-Sentry** [comment]
@fzyzcjy Can you please have a look at https://github.com/getsentry/sentry/discussions/44155 and ensure you have it on and get notified for spikes?

This gives protects you against any sudden quota-depleting spikes. Business plan customers also have the ability to add DSN level rate limits

**Comment by fzyzcjy** [comment]
@kerenkhatiwada Thanks for that information! However, IMHO if the hacker sends data without using a browser (say, using python or using curl), then those headers can be completely fake and thus this protection does not work.

**Comment by fzyzcjy** [comment]
@Dhrumil-Sentry Thanks! Sure I have opened the spike detection. However, the hackers can still attack. For example, suppose I am during a 8-hour sleep and the hacker slowly increases sending events to sentry. Then after I get up, there is already a lot of money consumed.

**Comment by leedongwei** [comment]
@fzyzcjy I hear your concern. However, this is a feature not a bug. 

In order for Sentry to work with any app (especially consumer apps), we'll need to accept events from everywhere. Similarly to the function of a physical mailbox or email inbox, the address has to be public and it needs to accept mail from any sender. 

We have not seen this as a common vector for abuse. If you experience a illegitimate, abusive volume of events to your Sentry DSN endpoint which does not originate from your code, please reach out to us and we can help you to throttle and rotate the DSN keys, after which we can gift events/credits at no extra cost to you. If it is a persistent attack, I'm confident that we can find resources to develop a spam filter.

As of now, we've only seen our customers DDoS themselves, hence the suggestion for Spike Protection (https://github.com/getsentry/sentry/discussions/44155) as a solution.

**Comment by fzyzcjy** [comment]
> We have not seen this as a common vector for abuse. If you experience a illegitimate, abusive volume of events to your Sentry DSN endpoint which does not originate from your code, please reach out to us and we can help you to throttle and rotate the DSN keys, after which we can gift events/credits at no extra cost to you. If it is a persistent widespread attack, we will develop a spam filter to handle it.

I see, thank you!
