### ISSUE TITLE
Sentry SaaS support IP whitelist of the clients?

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry#48863]
### Problem Statement

Hi thanks for the tool! I wonder whether will Sentry SaaS support IP whitelist of the clients?

Why I need this: I am worried about https://github.com/getsentry/sentry/issues/48860. Thus, a possible solution is that, I create a proxy server (say, nginx) for the Sentry SaaS server in my own server, and let the users send to my proxy instead of sentry. In other words:

```
App ---network request--> My server's nginx ----network request---> Sentry SaaS server
```

By doing so, I can control the network traffic easily. As a naive example, I can just throttle if there are too many requests, or throttle that each user id can only send a handful of exception reports per day, etc.

### Product Area

Unknown

**Comment by kerenkhatiwada** [comment]
@fzyzcjy  What particular SDK are you using? Seeing if this can potentially be transferred to the appropriate SDK repo.

**Comment by Dhrumil-Sentry** [comment]
@fzyzcjy have you explored [allowUrls](https://docs.sentry.io/platforms/javascript/configuration/options/?original_referrer=https%3A%2F%2Fwww.google.com%2F#allow-urls) on the client side for this ?

**Comment by fzyzcjy** [comment]
@mdtro Hi thanks for the information! I have discovered Relay and it seems quite good.

@Dhrumil-Sentry Well, IMHO that does not avoid this attack...
