### ISSUE TITLE
Instrument weekly cron job with Sentry's cron product

### ISSUE THREAD

**Issue by jangjodi** [getsentry/sentry#48877]
### Problem Statement

We want to dogfood our own crons product and give feedback to the crons team. 

### Solution Brainstorm

- Do not use any internal docs/communication/tips to set up crons. Starting point for instrumenting our cron should be public docs: [Crons](https://docs.sentry.io/product/crons/) 
- We should build monitors and analytics as we would normally do for a feature.  For any that overlap which crons supports, check to see if they are reporting similar data.  If not, take note of that to share with the crons team.
- Gather all feedback in a single notion page, and share it with the crons team once completed.
- Document any monitoring you would have normally included while developing a new cron job which our crons product did not support

### Product Area

Issues

**Comment by evanpurkhiser** [comment]
Shall we close this? cc @rjo100

I think this should be completed since we now instrument ALL of our tasks

**Comment by rjo100** [comment]
Yeah auto-instrument covers just about everything (except for the sub-minute stuff that we paused)
