### ISSUE TITLE
react-router in onboarding

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#48872]
### Problem Statement

Can we make it easier for people using react-router to onbaord to the product? While not all react projects use react-router, a significant number do, and it may make sense to elevate that in the onbaording.

[Docs](https://docs.sentry.io/platforms/javascript/guides/react/configuration/integrations/react-router/) 

These docs also need to be sanity checked, and cleaned up to be more concise

Feedback:
>Observation1:
If you’r on [Setup Performance Monitoring](https://docs.sentry.io/platforms/javascript/guides/react/performance/), you may miss it because it’s not in the code example but it is anchor link’d at the very bottom
Observation2
If you’re on [Instrumentation.Automaticinstrumentation](https://docs.sentry.io/platforms/javascript/guides/react/performance/instrumentation/automatic-instrumentation/) it is mentioned up front in text + code much better

![image](https://github.com/getsentry/telemetry-pm/assets/47563310/0d1c58ef-2afd-4a4d-9cc2-dbafe4f114c1)

![image](https://github.com/getsentry/telemetry-pm/assets/47563310/a22b9380-8639-42ea-a5aa-92d358debe92)

> this conversation comes up time and again
it is about half, but the gap is also slowly increasing. [NPM trends](https://npmtrends.com/react-vs-react-ro-vs-react-router) as a "signal"
i think we could still find a way to make it easier for onboarding

![image](https://github.com/getsentry/telemetry-pm/assets/47563310/60778747-bb7d-4e1b-a28b-3f922a4ce770)

### Product Area

Projects React onboarding (react-router)

**Comment by shanamatthews** [comment]
- https://github.com/getsentry/sentry-docs/pull/7138
- https://github.com/getsentry/sentry-docs/pull/7136
- https://github.com/getsentry/sentry-docs/pull/7137
