### ISSUE TITLE
[FE] Issue details banner for archived/ignored isn't substatus aware

### ISSUE THREAD

**Issue by barkbarkimashark** [getsentry/sentry#48893]
Example: [This issue](https://sentry.sentry.io/issues/3935139508/?project=1&query=is%3Auntil_condition_met&referrer=issue-stream&statsPeriod=14d&stream_index=2) says its ignored forever, but the substatus is until_escalating

https://github.com/getsentry/sentry/blob/a9b033d430222acc85080dbc828d84283d6e4b23/static/app/views/issueDetails/groupEventDetails/groupEventDetails.tsx#L142-L164

**Comment by scttcper** [comment]
this should be fixed
