### ISSUE TITLE
Background workers haven't checked in recently. This is likely an issue with your configuration or the workers aren't running.

### ISSUE THREAD

**Issue by vopjie** [getsentry/sentry#4890]
![image](https://cloud.githubusercontent.com/assets/9351855/22776081/4b9dea7a-eee9-11e6-89c5-7146efb01f4b.png)

i have installed the Sentry server myself, then i got this.
what can i do! please!

**Comment by vopjie** [comment]
and here is the log:
*** Starting uWSGI 2.0.14 (64bit) on [Thu Feb  9 04:53:50 2017] ***
compiled with version: 4.9.2 on 01 February 2017 23:58:51
os: Linux-4.9.4-moby #1 SMP Wed Jan 18 17:04:43 UTC 2017
nodename: dd81234ba49e
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address 0.0.0.0:9000 fd 3
Python version: 2.7.12 (default, Dec 14 2016, 18:46:29)  [GCC 4.9.2]
Set PythonHome to /usr/local
Python main interpreter initialized at 0x1d384e0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
setting request body buffering size to 65536 bytes
mapped 1922048 bytes (1877 KB) for 12 cores
*** Operational MODE: preforking+threaded ***
spawned uWSGI master process (pid: 11)
spawned uWSGI worker 1 (pid: 16, cores: 4)
spawned uWSGI worker 2 (pid: 17, cores: 4)
spawned uWSGI worker 3 (pid: 18, cores: 4)
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x1d384e0 pid: 18 (default app)
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x1d384e0 pid: 17 (default app)
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x1d384e0 pid: 16 (default app)
SIGINT/SIGQUIT received...killing workers...
[deadlock-detector] a process holding a robust mutex died. recovering...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.14 (64bit) on [Thu Feb  9 05:20:25 2017] ***
compiled with version: 4.9.2 on 01 February 2017 23:58:51
os: Linux-4.9.4-moby #1 SMP Wed Jan 18 17:04:43 UTC 2017
nodename: dd81234ba49e
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address 0.0.0.0:9000 fd 3
Python version: 2.7.12 (default, Dec 14 2016, 18:46:29)  [GCC 4.9.2]
Set PythonHome to /usr/local
Python main interpreter initialized at 0xc6a4e0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
setting request body buffering size to 65536 bytes
mapped 1922048 bytes (1877 KB) for 12 cores
*** Operational MODE: preforking+threaded ***
spawned uWSGI master process (pid: 11)
spawned uWSGI worker 1 (pid: 16, cores: 4)
spawned uWSGI worker 2 (pid: 17, cores: 4)
spawned uWSGI worker 3 (pid: 18, cores: 4)
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xc6a4e0 pid: 16 (default app)
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0xc6a4e0 pid: 17 (default app)
*** Starting uWSGI 2.0.14 (64bit) on [Thu Feb  9 09:25:42 2017] ***
compiled with version: 4.9.2 on 01 February 2017 23:58:51
os: Linux-4.9.4-moby #1 SMP Wed Jan 18 17:04:43 UTC 2017
nodename: dd81234ba49e
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address 0.0.0.0:9000 fd 3
Python version: 2.7.12 (default, Dec 14 2016, 18:46:29)  [GCC 4.9.2]
Set PythonHome to /usr/local
Python main interpreter initialized at 0x259d4e0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
setting request body buffering size to 65536 bytes
mapped 1922048 bytes (1877 KB) for 12 cores
*** Operational MODE: preforking+threaded ***
spawned uWSGI master process (pid: 11)
spawned uWSGI worker 1 (pid: 16, cores: 4)
spawned uWSGI worker 2 (pid: 17, cores: 4)
spawned uWSGI worker 3 (pid: 18, cores: 4)
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x259d4e0 pid: 16 (default app)
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x259d4e0 pid: 17 (default app)
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x259d4e0 pid: 18 (default app)
IP & PORTS
You can access this container using the following IP address and port:

DOCKER PORT	ACCESS URL
9000/tcp	localhost:<not set>

**Comment by vopjie** [comment]
*** Starting uWSGI 2.0.14 (64bit) on [Thu Feb  9 09:27:22 2017] ***
compiled with version: 4.9.2 on 01 February 2017 23:58:51
os: Linux-4.9.4-moby #1 SMP Wed Jan 18 17:04:43 UTC 2017
nodename: dd81234ba49e
machine: x86_64
clock source: unix
detected number of CPU cores: 2
current working directory: /
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: enabled
uwsgi socket 0 bound to TCP address 0.0.0.0:9000 fd 3
Python version: 2.7.12 (default, Dec 14 2016, 18:46:29)  [GCC 4.9.2]
Set PythonHome to /usr/local
Python main interpreter initialized at 0x26614e0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
setting request body buffering size to 65536 bytes
mapped 1922048 bytes (1877 KB) for 12 cores
*** Operational MODE: preforking+threaded ***
spawned uWSGI master process (pid: 11)
spawned uWSGI worker 1 (pid: 16, cores: 4)
spawned uWSGI worker 2 (pid: 17, cores: 4)
spawned uWSGI worker 3 (pid: 18, cores: 4)
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x26614e0 pid: 16 (default app)
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x26614e0 pid: 17 (default app)
WSGI app 0 (mountpoint='') ready in 5 seconds on interpreter 0x26614e0 pid: 18 (default app)

**Comment by mattrobenolt** [comment]
You also need to run the `cron` process and `worker` processes. Please read documentation.

**Comment by vopjie** [comment]
@mattrobenolt but i have already run cron and worker
![image](https://cloud.githubusercontent.com/assets/9351855/22811415/a42f10c0-ef79-11e6-8dd2-6d4945e870fa.png)

**Comment by mattrobenolt** [comment]
According to these logs, you aren't. Your container just happens to be named that way. Those are logs of the web process. You need to use the entrypoint `sentry run worker` and `sentry run cron`

**Comment by vopjie** [comment]
OK,thanks a lot
