### ISSUE TITLE
Teams filter resets to the default state when other filters applied on the Alert page

### ISSUE THREAD

**Issue by ilyasgaraev** [getsentry/sentry#48918]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open the Alerts page (`/alerts/rules/`);
2. Make sure that the default Teams filter is applied (My teams + Unassigned);
![image](https://github.com/getsentry/sentry/assets/44410/d8236128-3dd7-421e-aca2-1cba2285f460)

3. Open the Teams filter and clear all preselected filters (after this step the URL params should be `expand=latestIncident&expand=lastTriggered&sort=incident_status&sort=date_triggered&team=`, the team parameter is empty);
![image](https://github.com/getsentry/sentry/assets/44410/cfa7d89f-0fcc-4cc2-841f-9d4d6ba355ca)

4. Click on the Search input, add any text and press Enter.

### Expected Result

The team filter should be empty as selected previously.

### Actual Result

The team filter resets to the default state (My teams + Unassigned) after the search. The same behavior if you change the Project filter.

![image](https://github.com/getsentry/sentry/assets/44410/a98d526f-7c0b-4cd1-b660-2a0a491bb1b7)

### Product Area

Alerts

**Comment by armenzg** [comment]
Hi @ilyasgaraev thanks for filing!

This works:
* Make a search
* Uncheck "My teams" and "Unassigned" --> It will search All Teams

The following will not:
* Uncheck "My teams" and "Unassigned" 
* Make a search -> It will only search "My Teams" and "Unassigned" rather than All teams

**Comment by ceorourke** [comment]
I can't reproduce this problem, the teams remain unselected after a search is performed. Feel free to reopen if you're still experiencing the problem though.
