### ISSUE TITLE
Better and easier overview

### ISSUE THREAD

**Issue by iMusicJJ** [getsentry/sentry#48933]
### Problem Statement

Having recently migrated over from NR, we lack a few nice-to-have features, for better glanceability.

1) Have a hover-over graph with detailed spans.
Eg. being able to hover over the graph below and see where the time was spent. To easily see which service exploded after the release on May 2nd.
![image](https://github.com/getsentry/sentry/assets/57725397/211d7c98-107e-47ef-ac46-fdbf0a136ead)

Which leads me to
2) More detailed span-names.
Instead of just `http.route` make it `http.route.{externalHost}`, to see if an external host is experiencing problems.
Same goes for many other spans eg. `db.sql.query` => `db.sql.query.{tablename}`

### Product Area

User Feedback

**Comment by brentc** [comment]
Thanks for the feedback, this is valuable insight. I'll share it with the team and get back to you.

**Comment by nanoburd** [comment]
Just wanted to clarify a few things.

1. "see where the time was spent"
Are you expecting to see a % breakdown by top span ops or what's most useful to you? Maybe elaborate on what services you want to see a breakdown for?

2. Detailed Span Names
We provide the full span name when you look at span details or the waterfall. Do you mean you want more detail when we are grouping the spans by operation and adding the table name will add slightly more specificity?

Happy to chat more!~ Thanks for your feedback.

**Comment by iMusicJJ** [comment]
> Are you expecting to see a % breakdown by top span

Exactly. By showing us that, we can hover over the graph before the increase in response time, and after, and compare the two. Giving us the ability, at a glance, to see if maybe DB time went from 10% to 40% or external services were slower etc.

> We provide the full span name when you look at span details or the waterfall

Yes, the span names still seem too broad. `http.route` is quite ambiguous. It'd be nicer to include the host in the span name. This allows us to easily see if a host is experiencing problems.

Same goes for `db.sql.query`, where it'd be nice to include the tablename in the span name, so we can see if a table is slow and might benefit from a closer look at the indexes etc.

**Comment by Dhrumil-Sentry** [comment]
The Insights->Backend->Queries view helps answer such questions

![Image](https://github.com/user-attachments/assets/56c58593-1163-4790-8f49-35245b21bbb4)
