### ISSUE TITLE
[Replay Details] [Bug] "Learn more" banner for Network Req/Res Covers All Network Calls

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#48941]
In some cases, the "Learn more" blue banner for Network Req/Res takes up the entire Network tab and hides all the network calls. I hit X to close out of the banner and then that revealed all the the actual network calls table/rows. I haven't been able to repro this after Xing out the banner.

![SCR-20230511-iwft](https://github.com/getsentry/sentry/assets/187460/a03477bb-cbbf-4f85-abc0-52819dde53be)

**Comment by ryan953** [comment]
Reverting https://github.com/getsentry/sentry/pull/48874 which caused the issue. A fix would take longer to figure out and test.

**Comment by ryan953** [comment]
fixed: 
![SCR-20230511-jfpz](https://github.com/getsentry/sentry/assets/187460/0dfed061-46ff-48d6-b0ad-555bb803f98f)
