### ISSUE TITLE
Replay: user.email does not show all of the expected results

### ISSUE THREAD

**Issue by stellaatsentry** [getsentry/sentry#48957]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Have an app with Session Replay that sets a user email for events (setUser or initialScope)
2. Go to the Replays tab in the Sentry web UI
3. Search for `user.email:[the user email we set]`

### Expected Result

All replays that include this user email appear.

### Actual Result

In the replays page, we can see that there are 3 replays with the email `john.doe@example.com`. ([link](https://dragonfruit-dev.sentry.io/replays/?project=4504536789024768&statsPeriod=90d))
![Screenshot 2023-05-11 at 15 31 57](https://github.com/getsentry/sentry/assets/81985895/609e11a3-856c-4d86-be2f-409bebbced63)

However, when we query `user.email:john.doe@example.com` in the search bar, only one of the replays appear. ([link](https://dragonfruit-dev.sentry.io/replays/?project=4504536789024768&query=user.email%3Ajohn.doe%40example.com&statsPeriod=90d))
![Screenshot 2023-05-11 at 15 32 50](https://github.com/getsentry/sentry/assets/81985895/849cd63c-09fb-4c96-ab2f-e5262690ac67)

### Product Area

Replays

**Comment by JoshFerge** [comment]
We introduced this in https://github.com/getsentry/sentry/pull/47543 - for a performance optimization. we weren't sure that this was a frequent occurrence, but will absolutely prioritize a solution. thanks for reporting!

**Comment by JoshFerge** [comment]
@stellaatsentry could you try this now? I believe i've implemented a fix for the user fields. thanks!

**Comment by JoshFerge** [comment]
@stellaatsentry can you check on the customers that had trouble querying tags? that should be fixed as well now!

**Comment by stellaatsentry** [comment]
@JoshFerge It's fixed for them too!

**Comment by hubertdeng123** [comment]
Going to close this as it seems to be fixed now then. Thanks everyone!
