### ISSUE TITLE
Increased flexibility in dashboard dropdowns beyond environment, time range, releases

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry#48969]
### Problem Statement

Submitted on behalf of a customer:

I would like the ability to have increased flexibility in dashboard dropdowns. Currently, you can only select across:

- projects
- environments
- time range
- releases

<img width="627" alt="Screenshot 2023-05-11 at 2 31 39 PM" src="https://github.com/getsentry/sentry/assets/12092849/a7c14e60-e869-45a6-b5af-f5f08dd83c70">

Beyond this, I would like the ability to filter a dashboard by other means, for example tags. For instance, if I capture different regions where my app is deployed as tags, I want the ability to view the same dashboard quickly in region A, then switch to region B, and so on, without creating additional dashboards. To do this now, I would need to either edit widgets over and over, or else create multiple, essentially identical dashboards. Neither of these are a good user experience.

### Solution Brainstorm

Allow for a dropdown that lets a user select a tag-value pair (similar to alert rules?)

<img width="839" alt="Screenshot 2023-05-11 at 2 34 43 PM" src="https://github.com/getsentry/sentry/assets/12092849/82c1012b-21f9-45fb-94a5-42d7ffdd6543">

Or, some other way of allowing a dashboard to be updated in real time based on custom tags, via a dropdown.

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1839) by [Unito](https://www.unito.io)

**Comment by nanoburd** [comment]
Similar to this ticket: https://github.com/getsentry/sentry/issues/55036

**Comment by alexjillard** [comment]
https://github.com/getsentry/sentry/issues/55036 Will be the tracking ticket for this feature. Closing in favour of that ticket.
