### ISSUE TITLE
How does Sentry's disk tracking function notify relevant IMs that the C++dump file is too large, resulting in a failed report 413? How to solve it?

### ISSUE THREAD

**Issue by toby20130333** [getsentry/sentry#48983]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Hi support and dev:

How does Sentry's disk tracking function notify relevant IM chat, that the C++dump file is too large, resulting in a failed report 413? How to solve it?

### Expected Result

![image](https://github.com/getsentry/sentry/assets/4186642/fa9c7a13-0a0a-4fdd-9ccc-90aabd4865b4)

### Actual Result

![image](https://github.com/getsentry/sentry/assets/4186642/a3c74f69-2e4d-4cb9-ae01-979349407687)

### Product Area

Alerts

**Comment by scefali** [comment]
@toby20130333 What's going on is whatever service you are using for your integration is returning a 413 status code. Sentry is not generating a 413 status code, it just stores whatever status code your service returns. I'd investigate to see what might be returning a 413 such as an Ngnix proxy in front of your main app service.

**Comment by toby20130333** [comment]
@scefali Thank you.
It's due to our services framework's limit the body size
It's already resolved
