### ISSUE TITLE
Clean up FE API client error handling

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry#48981]
Goals:
- Have the full code path involving the handling of 4xx and 5xx responses included in the stacktrace. See [split description below into separate issue].
- Have a more useful `culprit` value than the name of the error-handling function
- Suppress 401, 403, and 404s
- Simplify where possible
- Fix problems:
  - Error messages equal to`[object Object]`

Currently:
- The full code path for 4xx and 5xx errors consists of three segments: frames before the `fetch` call (A), frames turning the response into an actual error (B), and frames after the promise has rejected with said error (C). Right now, we either collect an error chain with the A frames in the `cause` error and the B frames in the main error or collect just the C frames.

[screenshots to go here]

We'd like to have one event with all three pieces of the stack in one.

Tasks:
- Error handling in `api.tsx`
    - [x] move name lookup stuff to `RequestError` (https://github.com/getsentry/sentry/pull/49452)
    - [x] get rid of `createRequestError` (https://github.com/getsentry/sentry/pull/49452)
    - [ ] create first error inside executor
    - [ ] create second error inside of `error`
    - [x] remove setters (https://github.com/getsentry/sentry/pull/49452)

- `handleXhrErrorResponse` changes
    - [x] make `handleXhrErrorResponse` not return a callback (a whole series of PRs, culminating in https://github.com/getsentry/sentry/pull/49160)
    - [x] clean up `handleXhrErrorResponse` (https://github.com/getsentry/sentry/pull/49359)
    - [x] rename `modalManager` function with same name (https://github.com/getsentry/sentry/pull/49022)
    - [x] add `responseJSON` to `extra` (https://github.com/getsentry/sentry/pull/49359)
    - [x] use incoming error as `source` (https://github.com/getsentry/sentry/pull/49385)
    - [x] fix the `Error: [object Object]` problem (https://github.com/getsentry/sentry/pull/49119)

- Fix `culprit`
    - [ ] add `culprit` handling in `beforeSend`
    - [ ] add `culprit` tag in `handleXhrErrorResponse`

- Async stacktrace re-creation
    - [ ] (maybe) create `RequestStacktraceSegment` class extending `Error` (mostly like `RequestError`, but with `culprit` and `getResponseHeader`)
    - [ ] do smushing in `beforeSend`
    - [ ] add smushing flag in `handleXhrErrorResponse`

- [ ] Suppress 4xx errors

**Comment by evanpurkhiser** [comment]
Would love to read over this!

**Comment by evanpurkhiser** [comment]
Will do so in the morning :)

**Comment by lobsterkatie** [comment]
Am going to call this as done as it's going to be for now. May eventually come back to the async stacktrace thing and the setting of the culprit, but that's not going to happen now, so I'll make new tickets if it comes to that.
