### ISSUE TITLE
Ignoring errors using `ignoreErrors` and `beforeSend` is not working

### ISSUE THREAD

**Issue by dansofter** [getsentry/sentry#48997]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Added these regular expressions to `ignoreErrors` list in the configuration.
```
const filters = [
  /b\.recordDroppedEvent/i,
  /e\.dn is not a function/i,
  /Cannot read properties of undefined (reading 'length')/i,
  /AbortError/i,
  /NotSupportedError/i,
  /invalid address/i,
  /account has not been authorized by the user/i,
  /UnknownError/i,
  /Unexpected error/i,
];
```
2. Added this code snippet to `beforeSend` callback.
```
beforeSend(event) {
    if (event && event.message) {
      if (filters.find((filter) => event.message.match(filter))) return null;
    }
    return event;
  },

```

3. The error starts with `AbortError` is still coming. Attached a screenshot.
<img width="1538" alt="image" src="https://github.com/getsentry/sentry/assets/48925763/ba35bf6d-3218-43dd-9c4c-2a30a76028a8">

### Expected Result

The error starts with `AbortError` shouldn't come.

### Actual Result

<img width="1538" alt="image" src="https://github.com/getsentry/sentry/assets/48925763/ba35bf6d-3218-43dd-9c4c-2a30a76028a8">

### Product Area

Issues

### DSN

https://8ddd54b0f8cb4bcd8ddc3c2c1ab46be4@o4504568918376448.ingest.sentry.io/4504568969363456

**Comment by kerenkhatiwada** [comment]
@dansofter I believe this is occurring because error.message is undefined. Instead, can you please attempt to use  the [ignore errors](https://docs.sentry.io/platforms/javascript/guides/react/configuration/filtering/?original_referrer=https%3A%2F%2Fwww.google.com%2F#using-platformidentifier-nameignore-errors-) option as show in the docs:

`  ignoreErrors: [
    /b\.recordDroppedEvent/i,
    /e\.dn is not a function/i,
    /Cannot read properties of undefined (reading 'length')/i,
    /AbortError/i,
    /NotSupportedError/i,
    /invalid address/i,
    /account has not been authorized by the user/i,
    /UnknownError/i,
    /Unexpected error/i,
  ],`

**Comment by dansofter** [comment]
> @dansofter I believe this is occurring because error.message is undefined. Instead, can you please attempt to use the [ignore errors](https://docs.sentry.io/platforms/javascript/guides/react/configuration/filtering/?original_referrer=https%3A%2F%2Fwww.google.com%2F#using-platformidentifier-nameignore-errors-) option as show in the docs:
> 
> ` ignoreErrors: [ /b\.recordDroppedEvent/i, /e\.dn is not a function/i, /Cannot read properties of undefined (reading 'length')/i, /AbortError/i, /NotSupportedError/i, /invalid address/i, /account has not been authorized by the user/i, /UnknownError/i, /Unexpected error/i, ],`

@kerenkhatiwada 
I already set up `ignoreErrors` like that but it's not working.

```
Sentry.init({
  dsn: SENTRY_DSN,
  // Adjust this value in production, or use tracesSampler for greater control
  tracesSampleRate: 1.0,
  // ...
  // Note: if you want to override the automatic release value, do not set a
  // `release` value here - use the environment variable `SENTRY_RELEASE`, so
  // that it will also get attached to your source maps,
  ignoreErrors: [
    // Random plugins/extensions
    'top.GLOBALS',
    // See: http://blog.errorception.com/2012/03/tale-of-unfindable-js-error.html
    'originalCreateNotification',
    'canvas.contentDocument',
    'MyApp_RemoveAllHighlights',
    'http://tt.epicplay.com',
    "Can't find variable: ZiteReader",
    'jigsaw is not defined',
    'ComboSearch is not defined',
    'http://loading.retry.widdit.com/',
    'atomicFindClose',
    // Facebook borked
    'fb_xd_fragment',
    // ISP "optimizing" proxy - `Cache-Control: no-transform` seems to reduce this. (thanks @acdha)
    // See http://stackoverflow.com/questions/4113268/how-to-stop-javascript-injection-from-vodafone-proxy
    'bmi_SafeAddOnload',
    'EBCallBackMessageReceived',
    // See http://toolbar.conduit.com/Developer/HtmlAndGadget/Methods/JSInjection.aspx
    'conduitPage',
    // Generic error code from errors outside the security sandbox
    // You can delete this if using raven.js > 1.0, which ignores these automatically.
    'Script error.',
    // Errors from the wall
    /b\.recordDroppedEvent/i,
    /e.dn is not a function/i,
    /AbortError: The play() request was interrupted because the media was removed from the document./i,
    /NotSupportedError: The element has no supported sources./i,
    /Cannot read properties of undefined (reading 'length')/i,
    /AbortError: The play() request was interrupted by a call to pause()./i,
    /NotSupportedError: Failed to load because no supported source was found./i,
    /invalid address/i,
    /account has not been authorized by the user./i,
  ],
  ignoreUrls: [
    // Facebook flakiness
    /graph\.facebook\.com/i,
    // Facebook blocked
    /connect\.facebook\.net\/en_US\/all\.js/i,
    // Woopra flakiness
    /eatdifferent\.com\.woopra-ns\.com/i,
    /static\.woopra\.com\/js\/woopra\.js/i,
    // Chrome extensions
    /extensions\//i,
    /^chrome:\/\//i,
    // Other plugins
    /127\.0\.0\.1:4001\/isrunning/i, // Cacaoweb
    /webappstoolbarba\.texthelp\.com\//i,
    /metrics\.itunes\.apple\.com\.edgesuite\.net\//i,
  ],
});

```

**Comment by kerenkhatiwada** [comment]
ignoreErrors will look at the title of an event, is it possible to check the JSON of the event for the title and let me know of the value? Additionally, were you able to further check on the event.message being undefined? In this case, the event's type/value may be helpful. These can be accessed as: event.exception.values[0].type, event.exception.values[0].value .

**Comment by dansofter** [comment]
@kerenkhatiwada This is the title I got from the error json.

`Error: AbortError: The play() request was interrupted because the media was removed from the document.`

So I believe this error shouldn't come as the title includes `AbortError`.
However, how can I check `event.message` on the code?
I tried to log `event` on console, but nothing was logged.

**Comment by dansofter** [comment]
[1.txt](https://github.com/getsentry/sentry/files/11480902/1.txt)
Can you check this txt file?

**Comment by kerenkhatiwada** [comment]
@dansofter With some more testing it seems it's the parenthesis preventing the error from matching. Can you please attempt to use the below: 

  ignoreErrors: [
    /AbortError: The play\(\) request was interrupted because the media was removed from the document./i,
  ],
  
As for the issue of logging the event in the console. Can you please let me know how you are logging it?

**Comment by dansofter** [comment]
@kerenkhatiwada Let me try that out.
For logging, I just tried to log event and hint in `beforeSend` function.

```
beforeSend(event, hint) {
    const error = hint.originalException;
    console.log({ event, hint });
    if (error && error.message) {
      if (filters.find((filter) => error.message.match(filter))) return null;
    }
    return event;
  },
```

**Comment by dansofter** [comment]
Ok. It looks like it's hitting the beforeSend hook very rarely. I added a console log in `beforeSend` but the log works very rarely.
If I use sentry in Next.js project, it's correct to set up this in `sentry.client.config.js`, right?
Let me post the full config file here.

```
// This file configures the initialization of Sentry on the browser.
// The config you add here will be used whenever a page is visited.
// https://docs.sentry.io/platforms/javascript/guides/nextjs/

import * as Sentry from '@sentry/nextjs';

const SENTRY_DSN = process.env.SENTRY_DSN || process.env.NEXT_PUBLIC_SENTRY_DSN;

const filters = [
  /b\.recordDroppedEvent/i,
  /e\.dn is not a function/i,
  /Cannot read properties of undefined/i,
  /AbortError/i,
  /NotSupportedError/i,
  /invalid address/i,
  /account has not been authorized by the user/i,
  /UnknownError/i,
  /Unexpected error/i,
  /DOMException/i,
];

Sentry.init({
  dsn: SENTRY_DSN,
  // Adjust this value in production, or use tracesSampler for greater control
  tracesSampleRate: 1.0,
  // ...
  // Note: if you want to override the automatic release value, do not set a
  // `release` value here - use the environment variable `SENTRY_RELEASE`, so
  // that it will also get attached to your source maps,
  ignoreErrors: [
    // Random plugins/extensions
    'top.GLOBALS',
    // See: http://blog.errorception.com/2012/03/tale-of-unfindable-js-error.html
    'originalCreateNotification',
    'canvas.contentDocument',
    'MyApp_RemoveAllHighlights',
    'http://tt.epicplay.com',
    "Can't find variable: ZiteReader",
    'jigsaw is not defined',
    'ComboSearch is not defined',
    'http://loading.retry.widdit.com/',
    'atomicFindClose',
    // Facebook borked
    'fb_xd_fragment',
    // ISP "optimizing" proxy - `Cache-Control: no-transform` seems to reduce this. (thanks @acdha)
    // See http://stackoverflow.com/questions/4113268/how-to-stop-javascript-injection-from-vodafone-proxy
    'bmi_SafeAddOnload',
    'EBCallBackMessageReceived',
    // See http://toolbar.conduit.com/Developer/HtmlAndGadget/Methods/JSInjection.aspx
    'conduitPage',
    // Generic error code from errors outside the security sandbox
    // You can delete this if using raven.js > 1.0, which ignores these automatically.
    'Script error.',
    // Errors from the wall
    ...filters,
  ],
  ignoreUrls: [
    // Facebook flakiness
    /graph\.facebook\.com/i,
    // Facebook blocked
    /connect\.facebook\.net\/en_US\/all\.js/i,
    // Woopra flakiness
    /eatdifferent\.com\.woopra-ns\.com/i,
    /static\.woopra\.com\/js\/woopra\.js/i,
    // Chrome extensions
    /extensions\//i,
    /^chrome:\/\//i,
    // Other plugins
    /127\.0\.0\.1:4001\/isrunning/i, // Cacaoweb
    /webappstoolbarba\.texthelp\.com\//i,
    /metrics\.itunes\.apple\.com\.edgesuite\.net\//i,
  ],
  beforeSend(event) {
    console.log({ event });
    // if (event.message) {
    //   if (filters.find((filter) => event.message.match(filter))) return null;
    // }
    // if (event.exception.values.length > 0 && event.exception.values[0].value) {
    //   if (
    //     filters.find((filter) => event.exception.values[0].value.match(filter))
    //   )
    //     return null;
    // }
    return null;
  },
  debug: true,
});

```

**Comment by kerenkhatiwada** [comment]
Can you scroll down to the bottom of the sentry issue and ensure the event is coming from the sentry.javascript.nextjs SDK? If beforeSend is not dropping everything, that implies there may be a separate frontend Sentry.init() handling those errors somewhere. Maybe a CDN? Can you write to support@sentry.io mentioning this GitHub issue so we can take a closer look?

**Comment by kerenkhatiwada** [comment]
Thank you! I have followed up there.
