### ISSUE TITLE
[onboarding] Remove duplicate Angular project selection

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#48996]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. create new project
2. go to all
3. search angular
4. 2 appear Angular and AngularJS

### Expected Result

only one project selection for angular, with most up to date setup instructions

### Actual Result

new angular

<img width="959" alt="image" src="https://github.com/getsentry/sentry/assets/47563310/827f2b6e-7d55-4a9c-a93f-fa05c9f99616">

old: angularJS

<img width="752" alt="image" src="https://github.com/getsentry/sentry/assets/47563310/a0aa6d6d-248f-4890-9039-59233b13791e">

### Product Area

Projects

**Comment by smeubank** [comment]
@Lms24 if you don't see any immediate issues with remove the angularjs project type, then I think we toss it

**Comment by smeubank** [comment]
FYI @priscilawebdev & @ale-cota similar to https://github.com/getsentry/sentry/issues/48687

**Comment by Lms24** [comment]
Yeah, I think it's safe to remove AngularJS (= Angular 1.x). It's [EOL since Jan 22](https://docs.angularjs.org/misc/version-support-status)

**Comment by priscilawebdev** [comment]
Thanks for bringing this up @smeubank  and @Lms24 for double-checking it. We will remove Angular 1 soon 😉
