### ISSUE TITLE
[Replay Details] Sentry Errors in the table should show title + message

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#49016]
Sometimes one of the fields is empty, so the error can be not helpful until you click through:

![Image](https://github.com/getsentry/sentry/assets/187460/6c69cef3-8c4f-42d4-8ab5-b1f07bd1da9c)

We should show title and description all the time.

**Comment by billyvg** [comment]
This may be specific to that Sentry Issue as other errors render as expected 
<img width="396" alt="image" src="https://github.com/getsentry/sentry/assets/79684/289465b9-3881-4476-a94d-32b944d571ac">

**Comment by ryan953** [comment]
Not needed anymore. We have the new errors tab, so issues in console is no more.
