### ISSUE TITLE
[Replay Details] Column Headers on the network table are too wide

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#49026]
Possible solution: 
1. smush non-path columns to be the width of its content cells ignoring the header (force headers to be ellipsed)
2. Resizable (width) columns

**Comment by michellewzhang** [comment]
@ryan953 is this still an issue? if so could you add a picture or clarify what you mean by "too wide"

**Comment by billyvg** [comment]
Here's an example:
![Image](https://github.com/user-attachments/assets/8bf1305a-abb7-44d0-9655-4619d279c578)

**Comment by billyvg** [comment]
I added my thoughts to the ticket, but I'm going to close this since it's been around for ~18 months. I think tooltips over the path is a pretty reasonable workaround and even better in situations when the path is extremely long as the tooltip can wrap and span many lines.
