### ISSUE TITLE
Errors in breadcrumbs seem to add unnecessary "Error" prefix/suffix

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#49032]
See below

![Image](https://github.com/getsentry/sentry/assets/79684/18e0b783-98db-4115-92f4-7398c577e54d)

**Comment by ryan953** [comment]
This might be fixed, because i'm not able to find any recent examples anymore. 

If we had an example replay that would be helpful!

**Comment by ryan953** [comment]
Example: https://sentry.sentry.io/replays/javascript:600e43fc6c2d4426938dcfdc39356ec8/?query=&referrer=%2Freplays%2F&statsPeriod=14d&t_main=console&yAxis=count%28%29

**Comment by ryan953** [comment]
seems fixed:

![Image](https://github.com/getsentry/sentry/assets/187460/34da04b4-6f59-483a-94b4-87a21c4fb388)
