### ISSUE TITLE
[Feature] Provide an ability to know the IP Address from which a particular issue was created

### ISSUE THREAD

**Issue by dmitry-fedyuk** [getsentry/sentry#4904]
Sentry has a nice feature «**Filtered IP Addresses**».
![15807b7838726ed223ae6858ffb5392661424af8 1](https://cloud.githubusercontent.com/assets/83204/22851371/2326ac78-f031-11e6-85b8-ac9586f7b1e6.png)
But [as I understand](https://forum.sentry.io/t/how-can-i-know-from-a-sentry-projects-web-interface-from-which-ip-address-was-created-a-particular-issue/910) , Sentry does not provide a way to know the IP Address from which a particular issue was created.  
So there is a problem: **I want to filter a particular issue by its IP Address, but I do not know from which IP Address the issue was created**.

**Comment by dcramer** [comment]
We currently hide it in the UI due to privacy concerns (unless you're a superuser). We could probably move it behind the "enhanced privacy" or "scrub IP addresses" filter.

**Comment by dmitry-fedyuk** [comment]
Who is a superuser? Whether am I a superuser if I am the creator of my account on sentry.io?

**Comment by dcramer** [comment]
@dmitry-fedyuk owner of the sentry install, so the Sentry company if you're using sentry.io

Aside, if this is a web request, you might be able to look at the HTTP headers. Alternatively you might want to record ``user_context('ip_address': '...')`` which could also give you what you need.

**Comment by dmitry-fedyuk** [comment]
Interestingly, the «**Don't store IP Addresses**» option is unchecked for me:
![11](https://cloud.githubusercontent.com/assets/83204/23328985/71825200-fb3f-11e6-8363-e51a19d67f0d.png)

**Comment by dcramer** [comment]
@dmitry-fedyuk we fixed an issue in the python SDK which would cause the request to not always be available

**Comment by dmitry-fedyuk** [comment]
I use the [PHP SDK](https://github.com/getsentry/sentry-php), not the Python one.

**Comment by dcramer** [comment]
@dmitry-fedyuk ah actually it looks like we dont capture the IP address in PHP like we do elsewhere. I'm going to submit a PR that grab it.

**Comment by dmitry-fedyuk** [comment]
[Your code](https://github.com/getsentry/sentry-php/pull/419/commits/d652cdd54e30fdee74bf0edd361007f9eed69b8e) collects the visitor's IP Address.  
I need to know the problem website's IP Address.  
My software is used on multiple websites, and some of them report non-important issues.  
I want to filter them out using the «**Filtered IP Addresses**» feature.

**Comment by dcramer** [comment]
I'm not sure what you're asking anymore. The option is to *remove* IP addresses, and definitely works. There was behavior in the PHP SDK that would never collect them, which is the opposite of that behavior.
