### ISSUE TITLE
[Design] Replay AM1 upgrade path

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#49076]
**Opportunity**: We are currently only proposing Replay in the new project creation flow for AM2 orgs, because it’s not supported on AM1.

**Acceptance Criteria:**
- if an AM1 customer creates a new project on a platform where Replay is supported, they are notified about the existence of Replay and that they need to update their plan
- the user has an easy way to "trigger" the update process (same as existing update flow from Replay tab)

**Comment by Jesse-Box** [comment]
Designs are ready for development

Figma:
https://www.figma.com/file/XQlqqM1lGGA6PcnBjZ83DE/Specs%3A-Replay-Upsell-in-Project-Creation-Flow?type=design&node-id=416%3A1618&t=AGJKIfllzxU8IiKE-1
