### ISSUE TITLE
Enable "AI Suggested Solution" only for specific projects

### ISSUE THREAD

**Issue by rvgansewinkelsendcloud** [getsentry/sentry#49073]
### Problem Statement

Currently, it is only possible to enable/disable the feature at the organizational level. 

![image](https://github.com/getsentry/sentry/assets/133636459/925e8e6b-db1e-4e55-a680-772f17e93321)

In my company, we have multiple projects in Sentry. Some we wouldn't like the content to be shared with AI tools while others are fine by us (mainly frontend projects). It would be nice to get the ability to enable/disable the feature on a project level to facilitate this.

### Solution Brainstorm

Add a similar toggle within https://sendcloud.sentry.io/settings/projects/[project-name]/ as has been done for https://sendcloud.sentry.io/settings/organization/

### Product Area

Settings - Projects

**Comment by leedongwei** [comment]
@rvgansewinkelsendcloud  Thanks for the feedback. This is a feature in its early days and it uses a external data processor, so we went with a org-wide setting to simplify the legal/privacy requirements. We'll add this to our backlog for consideration when we're ready for a wider release.

**Comment by roggenkemper** [comment]
This feature has been deprecated so closing the issue
