### ISSUE TITLE
Offer query parameters for easier setup of Auth Tokens

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry#49084]
### Problem Statement

Currently there seems to be no way to select a specific preset of privileges when creating a new auth token. We could help our users by providing those, depending on where they come from, without making the process more complicated.

### Solution Brainstorm

Initially I wanted to upload source maps. In order to do so, I had to request an auth token. I ended up on this site, but had no idea which privileges should be granted (overlooked the hint in a comment):

<img width="1505" alt="Screenshot 2023-05-15 at 10 59 57" src="https://github.com/getsentry/sentry/assets/7096858/df0a979d-3ac7-4021-8f47-6840c2c37226">

What was actually written in the comment was:
<img width="726" alt="Screenshot 2023-05-15 at 11 00 46" src="https://github.com/getsentry/sentry/assets/7096858/32992b9b-e3e1-45c3-8777-12258e806cdd">

What would be really great is if we would introduce kind of "presets" for auth tokens, without complicating it for our users. We could do so by introducing query parameters for the URL:
https://sentry-tutorial.sentry.io/settings/account/api/auth-tokens/new-token/

Something like
https://sentry-tutorial.sentry.io/settings/account/api/auth-tokens/new-token/?preset=sourcemaps or
https://sentry-tutorial.sentry.io/settings/account/api/auth-tokens/new-token/?setup=sourcemaps 

Which would then pre-fill the privileges like that:

<img width="1512" alt="Screenshot 2023-05-15 at 11 06 07" src="https://github.com/getsentry/sentry/assets/7096858/8ad189da-27f5-4fef-90c6-362b00e064b1">

And we would change it in the SDK comments to:

<img width="946" alt="Screenshot 2023-05-15 at 11 06 59" src="https://github.com/getsentry/sentry/assets/7096858/5f2f1a60-75a1-4337-b98d-e8274d987279">

### Product Area

Settings - Auth

**Comment by Lms24** [comment]
Questions around permissions for the auth token also came up in the docs a couple of times. For example: https://github.com/getsentry/sentry-docs/issues/6573

+1 on solving this via the UI/a query param

**Comment by smeubank** [comment]
Related: https://github.com/getsentry/sentry/issues/48690

**Comment by smeubank** [comment]
it could also be considered that this would be automated in docs where the user is logged in that the token would be autofilled similar to project, org, and DSN

**Comment by Dhrumil-Sentry** [comment]
@stephanie-anderson @smeubank  The requirement is a bit unclear to me- I'd understand if the Auth UX had a way to allow users to specify the token's purpose and then Sentry could auto-select the needed scopes.

But why do you want query parameters in the API? Since Sentry already knows what scopes to use for different use cases you already know what scopes to ask for. Is my understanding correct?

**Comment by scefali** [comment]
I am hesitant about UX to improve user tokens. We want people to use organization tokens so if they leave Sentry, things don't just break.

**Comment by Dhrumil-Sentry** [comment]
> I am hesitant about UX to improve user tokens. We want people to use organization tokens so if they leave Sentry, things don't just break.

I 100% agree, Ideally, I'd like to improve the UX for internal integration tokens- "Internal Integration" is confusing to folks IMO- Either Sentry can automatically create these tokens for users when we know a project needs tokens to upload source maps, etc or We should have a very clear settings entry for Tokens in Orgs Settings- It can use the same logic behind the scenes but the users should not have to create "Internal Integrations" to get tokens

**Comment by stephanie-anderson** [comment]
We're going to build proper org based auth tokens, which we will initially build to serve as CI/CD tokens (https://github.com/getsentry/team-webplatform-meta/issues/75). Will close this issue.
