### ISSUE TITLE
Enable Sentry <-> Azure DevOps integration via Service Hooks

### ISSUE THREAD

**Issue by RichardOberdieck** [getsentry/sentry#49083]
### Problem Statement

Currently, any integration between Sentry and Azure DevOps requires owner, or owner-like privileges for the organization. This is security concern, as these powers (like being able to delete a repo) should not be needed. 

### Solution Brainstorm

Azure [Service Hooks](https://learn.microsoft.com/en-us/azure/devops/service-hooks/overview?view=azure-devops) are made for exactly this: 

> Service hook publishers define a set of events that you can subscribe to. Subscriptions listen for these events and define actions to take based on the event.

There are two main advantages:
- These hooks are administered on the project level (not the organization level), which by itself is much lower risk
- One can configure the permissions of the service hooks, and as such limit the security concerns even more.

### Product Area

Issues

**Comment by Dhrumil-Sentry** [comment]
HI @RichardOberdieck - Is the only concern that too many users need the Admin role to configure the Sentry-Azure devops integration?

The integration only needs to be installed once by the organization owner/manager/admin, Could you please explain why multiple users need to configure this flow?
