### ISSUE TITLE
Got tons of "Authentication credentials were not provided" error  in my Chrome console

### ISSUE THREAD

**Issue by tonghs** [getsentry/sentry#4909]
![](https://ww4.sinaimg.cn/large/006tNc79gy1fcq7e7xjj3j31bo0u4ace.jpg)

My env info:
Server: Ubuntu 14.04.5
Sentry:  8.13.0
Client: macOS + chrome

**Comment by dcramer** [comment]
Your server is misconfigured, and we do not provide support via our issue tracker.

**Comment by tonghuashuai** [comment]
Resovled.
Go to my account (User Icon -> API) and generate a new token.
