### ISSUE TITLE
Add Mark Reviewed Button in slack integration

### ISSUE THREAD

**Issue by andrii-chyzhh** [getsentry/sentry#49091]
### Problem Statement

Reference:
https://docs.sentry.io/product/issues/states-triage
> While you can work to have zero unresolved issues (“Inbox Zero”) by resolving or ignoring all issues, this usually isn’t feasible for any non-trivial production application. However, it is feasible to have zero for-review issues by triaging the issues in the Review List. We recommend triaging these issues once a day to keep your issues manageable.

We use Sentry + Slack integration. With issue view in slack we have only 3 options: 
Resolve button, Ignore button and assignee dropdown.

We can't mark issue as reviewed from slack. 

### Solution Brainstorm

Add Mark Reviewed button in slack issue view:
https://take.ms/Pv6vJ

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
Hi @andrii-chyzhh, The Issues team has different ideas for how triage experience using Sentry should evolve. Please see https://github.com/getsentry/sentry/discussions/43039 for more details.

So we're unlikely to add Mark Reviewed to our Slack alerts
