### ISSUE TITLE
Personal Notifications not working with Slack

### ISSUE THREAD

**Issue by landorg** [getsentry/sentry#49189]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Setup Slack integration following: https://develop.sentry.dev/integrations/slack/
2. do `/sentry link` (works)
3. Click on the Button in the Message from Sentry: `Turn on personal notifications`

### Expected Result

Personal notifications working

### Actual Result

![image](https://github.com/getsentry/sentry/assets/1443267/0502df71-daf8-41b7-aecd-f5e21dce7f3e)

### Product Area

Alerts

### Version

22.11.0
also in
23.3.1

**Comment by brianthi** [comment]
Hi @landorg, can you navigate to /settings/account/notifications/ on your sentry instance, and make sure that the notifications are turned on, and under `Fine tune` for each notification type, you have added Slack in the `Delivery Method`.

**Comment by landorg** [comment]
Hi and thanks for your quick reply.
The slack delivery method wasn't enabled for the alerts but I still get the same message in slack when I try to turn on personal notifications.

**Comment by landorg** [comment]
A small update: 
After setting the personal notification settings I now get some notifications but the error message is still there.
btw: Is there a way to set the slack notifications as a default for all users?

**Comment by scttcper** [comment]
There currently isn't a way to set slack as the default, glad you got it working
