### ISSUE TITLE
Do not show HTML tags in stacktrace

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#49184]
This was discussed in https://github.com/getsentry/sentry-javascript/issues/8102

[This issue](https://sentry.sentry.io/issues/4146750272/?project=11276) shows a stacktrace with HTML elements.

@AbhiPrasad does not consider them being in the stacktrace to be a bug, however, he suggests in https://github.com/getsentry/sentry-javascript/issues/8102#issuecomment-1547445068 that we should hide it from the UI.

The customer can still see the elements in the raw stacktrace if they find any value on inspecting it.

<img width="633" alt="image" src="https://github.com/getsentry/sentry/assets/44410/d7f27b36-6a33-42b7-9017-8c755b2deefc">

**Comment by AbhiPrasad** [comment]
I would only remove HTML elements if they don't have line/col numbers - otherwise they still have value.
