### ISSUE TITLE
Error adding ticket - Sentry and Jira Server integration

### ISSUE THREAD

**Issue by dvyatkov** [getsentry/sentry#49186]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Add jira server integration: https://docs.sentry.io/product/integrations/issue-tracking/jira/
2. Open any sentry issue 
3. Click on "Link Jira Server Issue"

### Expected Result

The ticket creation screen appears without any errors

### Actual Result

After clicking on the button "Link Jira Server Issue", we get an error (see screenshot). At the same time, in the integration settings, we get the current list of our projects - those integration is configured correctly

![Screenshot 2023-05-16 at 18 23 56](https://github.com/getsentry/sentry/assets/110402033/36c007a8-cd25-429b-8eab-ae48794cd10b)

### Product Area

Issues

### Version

21.11.0

**Comment by scttcper** [comment]
have you run through the troubleshooting steps here https://docs.sentry.io/product/integrations/issue-tracking/jira/#trouble-with-self-hosted-sentry-installation

**Comment by scttcper** [comment]
You might also try updating your instance of sentry

**Comment by dvyatkov** [comment]
Hello! 
I checked the points from the documentation and everything is ok. I also noticed that we have the ability to link a ticket, the error occurs only when creating a task.
What version has a solution to this problem? I already saw a ticket with exactly the same problem, but it was still last year and the problem is not solved https://github.com/getsentry/sentry/issues/42245

**Comment by hubertdeng123** [comment]
Looks like PR's went in around Aug 2022 for this. https://github.com/getsentry/sentry/pull/37577

So you'll want to probably try 22.9.0 and up
