### ISSUE TITLE
Saved search for member level role

### ISSUE THREAD

**Issue by sksembhi** [getsentry/sentry#4921]
Customized issue/error search cannot be saved if user only has member level permissions.

**Comment by nimishsinghal** [comment]
Hi @sksembhi,
For this issue the below view should be made visible to logged in user who have member level permissions right?
<img width="541" alt="screen shot 2017-02-19 at 12 43 01 am" src="https://cloud.githubusercontent.com/assets/4672630/23096139/771b7a0a-f63c-11e6-8821-6776f54be0ef.png">

Also who should be given preference the setting which he has selected for himself or the settings which the admin has selected for the whole team?
Thanks

**Comment by sksembhi** [comment]
@nimishsinghal member level should have that view visible to them with the exception of "make this the default view for my team".

Member level should not be able to change the default view for the whole team, but can change the default view for him/herself

**Comment by nimishsinghal** [comment]
Thanks @sksembhi made a PR to resolve above issue

**Comment by nimishsinghal** [comment]
@sksembhi this issue can be closed.
