### ISSUE TITLE
On a refresh pageload, having t=x in the URL bar does not show `00:x` in the scrubber

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#49227]
For example, load this replay: https://sentry.sentry.io/replays/7e38e0da35934f0cb3b03a1550f8adee/?referrer=%2Fissues%2F%3AgroupId%2F&t=5&t_main=dom

Scrubber says `00:00`, if you click "Play", it'll set to `00:05` and play from `00:05` -- the initial rendered value of the scrubber is off.

**Comment by ryan953** [comment]
Fixed!
