### ISSUE TITLE
Save button for custom search at bottom of advanced filter view

### ISSUE THREAD

**Issue by sksembhi** [getsentry/sentry#4923]
UX/UI thoughts: creating a save button at the bottom of the advanced filter view when creating customized searches. 

<img width="358" alt="screen shot 2017-02-15 at 5 30 25 pm" src="https://cloud.githubusercontent.com/assets/22206567/23003285/880b8f2a-f3a4-11e6-8056-6242e3c6ec96.png">

**Comment by Riyuzakii** [comment]
@berkerpeksag I'm a first timer on github and i would like to help fix this bug, could you direct me to the files to be changed and maybe tell a little bit more about the issue.

**Comment by Riyuzakii** [comment]
@dcramer  I'm a first timer on github and i would like to help fix this bug, could you direct me to the files to be changed and maybe tell a little bit more about the issue

**Comment by BYK** [comment]
I think we have this now: https://docs.sentry.io/product/sentry-basics/search/#pinned-searches
