### ISSUE TITLE
Fix stream action bar when advanced search view is open

### ISSUE THREAD

**Issue by sksembhi** [getsentry/sentry#4924]
Issue: when advanced search view is open, and user scrolls down, the events dashboard header/stream action bar obstructs the page view. Example attached.

<img width="1364" alt="screen shot 2017-02-15 at 5 35 06 pm" src="https://cloud.githubusercontent.com/assets/22206567/23003392/6e57ecbc-f3a5-11e6-9f8a-89e71135865d.png">

**Comment by nimishsinghal** [comment]
This has to be made of full width while scrolling right?

**Comment by sksembhi** [comment]
Stream action bar should disappear while scrolling

**Comment by nimishsinghal** [comment]
@sksembhi thank you, I had initially made it of full width. Now I have added a fix up commit and disappeared stream action bar.
