### ISSUE TITLE
Metric alerts with different slack channels for warning and critical send to both

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#49252]
Using 2 different slack channels for warning and critical sends a message to both channels on warning

ACs:

- Only send to the one channel on warning

**Comment by spalmurray** [comment]
Was not able to reproduce the behavior on warning, but did find what appears to be the issue:

Setup:
- Two Slack channels: one for warning and one for critical
- Metric alert configured to send message to the warning channel on warning status and the critical channel on critical status

This leads to the following message behavior (where columns are alert state transitions):

|  | Warning | Critical | Resolved |
| --- | --- | --- | --- |
| Warning channel |W | - | R |
| Critical channel | - | C | W |

|  | Critical | Warning | Resolved |
| --- | --- | --- | --- |
| Warning channel | W | - | R |
| Critical channel | C | W | R |

|  | Critical | Resolved |
| --- | --- | --- |
| Warning channel | W | R |
| Critical channel | C | W |

|  | Warning | Resolved |
| --- | --- | --- |
| Warning channel | W | R |
| Critical channel | - | - |

Only the last scenario behaves as expected. I don't think we ever want to see warnings in the critical channel.

**Comment by spalmurray** [comment]
The expected behavior in each scenario is:

|  | Warning | Critical | Resolved |
| --- | --- | --- | --- |
| Warning channel | W | - | R |
| Critical channel | - | C | R |

|  | Critical | Warning | Resolved |
| --- | --- | --- | --- |
| Warning channel | -? | W? | R |
| Critical channel | C | -? | R |

|  | Critical | Resolved |
| --- | --- | --- |
| Warning channel | -? | -? |
| Critical channel | C | R |

|  | Warning | Resolved |
| --- | --- | --- |
| Warning channel | W | R |
| Critical channel | - | - |

**Comment by spalmurray** [comment]
Eran's suggestion: show critical messages in warning channel also:

|  | Warning | Critical | Resolved |
| --- | --- | --- | --- |
| Warning channel | W | C | R |
| Critical channel | - | C | R |

|  | Critical | Warning | Resolved |
| --- | --- | --- | --- |
| Warning channel | C | W | R |
| Critical channel | C | - | R |

|  | Critical | Resolved |
| --- | --- | --- |
| Warning channel | C | R |
| Critical channel | C | R |

|  | Warning | Resolved |
| --- | --- | --- |
| Warning channel | W | R |
| Critical channel | - | - |

**Comment by spalmurray** [comment]
See this [Notion doc](https://www.notion.so/sentry/Metric-alert-notifications-888ca0b0d1784e80a9f6181514472303?pvs=4) for more info on the problem and the solution we went with.
