### ISSUE TITLE
[Design] Dead Clicks V1

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#49257]
For the following [Q2 initiative](https://github.com/getsentry/sentry/issues/48259), here is the design work required:

1. New Entry on Issues Stream ([Please see 1/ under the "What" section.](https://www.notion.so/sentry/FY-24-Q2-Dead-Clicks-f24bad63dc5b4910b457efd1d91ba83a?pvs=4#7d8d274b63a84fb482d91ed10babccc8))
2. Issue Details ([Please see 2/ and 3/ under the "What" section. Only what is marked as MVP is necessary for first design iteration.](https://www.notion.so/sentry/FY-24-Q2-Dead-Clicks-f24bad63dc5b4910b457efd1d91ba83a?pvs=4#7d8d274b63a84fb482d91ed10babccc8))
3. Replay Details ([Please see 5/ under the "What" section](https://www.notion.so/sentry/FY-24-Q2-Dead-Clicks-f24bad63dc5b4910b457efd1d91ba83a?pvs=4#9cb68767e756454cb4631d1413340638))

Once done, please add mocks directly to the [Dead Clicks PRD](https://www.notion.so/FY-24-Q2-Dead-Clicks-f24bad63dc5b4910b457efd1d91ba83a?d=135f623e1f3f4c7ea0d4b533e6a1d5d8#7d8d274b63a84fb482d91ed10babccc8) in the "What" section.

**Comment by jas-kas** [comment]
@Jesse-Box Feel free to create as separate ticket for "3." above if you prefer to split up the work of Issue Details v. Replay Details for this project. :)

**Comment by jas-kas** [comment]
(Internal) Initial Exploration of Dead Click Issues: https://www.figma.com/file/pi5lcH5oeZBoakfEtCb8T9/Exploration%3A-Dead-Click-Issue?type=design&node-id=5-611&t=SgialfPFLXyIYG6V-0

**Comment by Jesse-Box** [comment]
@jas-kas @ryan953 

I just want to highlight that given, we're not creating issues until we can refine the detection, I'm changing the status to `TODO`

**Comment by Jesse-Box** [comment]
@jas-kas @ryan953 

I'll close this design ticket given this Q2 initiative is also closed
