### ISSUE TITLE
[Design] Replay Details > Issues Tab V2

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#49263]
## Issues (including their Errors) inside Replay Details
Today, there is no dedicated view to see solely **all** issues and their error events that occurred during a Replay. 

We have added FE error events and the associated issue link in our Console tab, but have seen confusion from customers on the difference between a 'console error' v. 'sentry error'. In addition, we want to avoid including BE error events in the Console tab so it can closely mirrors DevTools. More in this [Slack thread](https://sentry.slack.com/archives/C04RDSY3ML1/p1683659099245289).

### Limitations of Replay Details > Issues tab
- The individual error events that occurred in the replay are not reflected
- Cannot easily visit the specific error event Issue Details page from this view
- Can't jump to timestamp of when the specific error in the Replay occurred 

### Minimum Product Requirements for Replay Details > Issues Tab V2
- Covers Backend and Frontend Issues
- Present aggregate insights on the Sentry Issue such as *total* number of events and users impacted
- Includes individual error events that occurred in the Replay and make it clear which Issue they're associated with
- Be able to go from error event in Issues Tab V2 to the specific error event Issue Details page
- Be able to jump to the relevant timestamp of when an error occurred in the Replay

Figma of _Initially_ Proposed Issues/Errors tab: https://www.figma.com/file/VJffxPWvRaaRJ1gywzuUre/Specs%3A-Connecting-Backend-Errors?type=design&node-id=422-25593&t=Xc6WwCPSIpZYhKvx-0

**Comment by jas-kas** [comment]
cc/ @Jesse-Box @ryan953 🙏

**Comment by jas-kas** [comment]
(Internal) Latest design is Feedback 5 on [Figma](https://www.figma.com/file/VJffxPWvRaaRJ1gywzuUre/Specs%3A-Connecting-Backend-Errors?type=design&node-id=422-25592&t=6xpiiD22P9bSuHdN-0).

**Comment by Jesse-Box** [comment]
@jas-kas @ryan953 going to call this ticket done.

Designs
https://www.figma.com/file/VJffxPWvRaaRJ1gywzuUre/Specs%3A-Connecting-Backend-Errors?type=design&node-id=517%3A28073&t=akC3V9GuI4esiGoS-1

Something's that, I think, should be mentioned in the frontend work.
- Console no longer shows sentry errors
- This tab is now the first in order
- The search field filters by: Event ID, Issue ID or Error Title
- The errors table can be filtered by the project it's associated with. This can be achieved either by the project selector or by clicking an error counter specific to a project. If there's only one error counter, then the errors table isn't filtered.
- Hovering over the issue ID presents the same issue hovercard found in discover
- Hovering over the event ID presents the same event hovercard found in discover
- A user can go directly to the error event by clicking the event ID.
