### ISSUE TITLE
GET /api/0/organizations returns `200 OK - []`

### ISSUE THREAD

**Issue by cdelst** [getsentry/sentry#49335]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Get a valid token (I can validate that it is in fact valid, because other endpoints I am hitting (projects, for example) is working correctly.) 
2. Query `GET https://launchdarkly-ecosystem.sentry.io/api/0/organizations/`
3. See 200 OK response with empty array body. 

I have also tried using the non self-hosted URL as well.  

Here's a screenshot of the integration permissions I'm using that generates the token: 

![image](https://github.com/getsentry/sentry/assets/44860108/6f4ed189-eed0-4ca7-862c-a5aa39033b14)

### Expected Result

I expect the organizations endpoint to return the organizations in our account.

### Actual Result

`200 OK - []`

![image](https://github.com/getsentry/sentry/assets/44860108/9f8d3a3d-11b0-4390-8a9d-45d5aa18235c)

Proof that I do in fact have an organization (I don't think you can not have one?)

![image](https://github.com/getsentry/sentry/assets/44860108/ae6c4330-a8b9-49a5-8bd3-069e7398449a)

### Product Area

Other

**Comment by Dhrumil-Sentry** [comment]
@leedongwei can this API be used using Integration tokens or does it need a user's auth token?

**Comment by cdelst** [comment]
Any update on investigation here? cc @Dhrumil-Sentry @leedongwei

**Comment by Dhrumil-Sentry** [comment]
@cdelst I'll let @leedongwei confirm this but I suspect that this particular API endpoint can only be invoked by a user token. The integration token you are using is tied to a specific org and it won't be able to list other organizations your user account has access too.

Is there any particular use case for which you need this list of orgs?

**Comment by cdelst** [comment]
@Dhrumil-Sentry The exact use case we need is to be able to list all environments and projects in a given org, without knowing the org name/key (as that is not provided in the integration handshake as far as I can tell).  

The list organizations endpoint is a roundabout way of getting that, but we did not find another endpoint that could satisfy that requirement.

**Comment by AniketDas-Tekky** [comment]
I'm assuming you're looking for projects and environments in your own organization. In which case the APIs would be:
`/api/0/organizations/launchdarkly-ecosystem/projects/` - all projects
`/api/0/organizations/launchdarkly-ecosystem/environments/` - all environments

The subdomain in the URL (in your case `launchdarkly-ecosystem`) is your organization key.

**Comment by cdelst** [comment]
@AniketDas-Tekky Unfortunately, we need the projects and environments of our integration consumer, to provide them a setup experience on our end mapping our (LaunchDarkly's) environments and projects to the customer's Sentry projects and environments.

**Comment by cdelst** [comment]
Looking at the permissions of the integration, it feels like this should be possible when the `Organization` permission is set to read: 
![image](https://github.com/getsentry/sentry/assets/44860108/e46e265d-e7d1-48f1-a403-91a18393829f)

**Comment by cdelst** [comment]
@AniketDas-Tekky I could be confused here, so sorry in advance, but I thought the point of going through the authentication flow, and getting a token out of it was that that token had access to our integration consumer's information.  It's fine if that token is scoped to a project, but we need some way of getting information about that project with the information that's provided to us through the integration handshake.  

Are there any other approaches you'd recommend here? Or is it simply not possible? Being able to retrieve only the customer's projects using our token would be a bit unfortunate.

**Comment by cdelst** [comment]
Additionally, it might make more sense to not return a `200 - OK` when a token does not have access to any organization information if that is indeed the expected behavior for all integration tokens.

**Comment by cdelst** [comment]
Thanks @Dhrumil-Sentry.  I missed that. Thanks for both of your help.
