### ISSUE TITLE
With disable registration = False we still have link when open from invite email

### ISSUE THREAD

**Issue by lfrodrigues** [getsentry/sentry#4935]
If I send an invitation for someone doesn't matter if I click the "create new account" button or "Login as existing user" I'm taken to a screen that has the "register link"

I'm using version 8.13.0

Screenshot when accessing normally
![screen shot 2017-02-18 at 13 24 53](https://cloud.githubusercontent.com/assets/301004/23093527/170b1dae-f5de-11e6-84b8-2f0e83b6aef9.png)

Screenshot if coming from invite link
![screen shot 2017-02-18 at 13 26 05](https://cloud.githubusercontent.com/assets/301004/23093523/05fc02b2-f5de-11e6-9659-cc2cd3b2ae3f.png)

**Comment by dcramer** [comment]
This is intentional behavior, because otherwise there is no way they can actually setup an account.

**Comment by lfrodrigues** [comment]
Ok, fair point. 

But in my case we're using login with ldap so there is not need for register (and adds confusion to first time users).  Would it make sense to add another configuration option?

**Comment by dcramer** [comment]
@lfrodrigues its not something we'd add, but we might accept a PR. At the end of the day we're focused on building saas, and in our current model LDAP would be an SSO provider instead of an install-wide thing.
