### ISSUE TITLE
Link from shared issue to the detailed one when user is authenticated

### ISSUE THREAD

**Issue by noirbizarre** [getsentry/sentry#4936]
Public shared issues is awesome on opensource projects.

But when I share an issue with someone or in a github issue comment, there is no easy way to get back to the detailed issue for authenticated users.

It would be nice to have a link to the detailed issue when the user is allowed to see it.

**Comment by scotchka** [comment]
working on this

**Comment by scotchka** [comment]
can be closed

**Comment by noirbizarre** [comment]
Thanks for the implementation !
