### ISSUE TITLE
Use Spike Protection to set configurable thresholds and limit event ingestion based on fingerprint

### ISSUE THREAD

**Issue by sergiosentry** [getsentry/sentry#49390]
### Problem Statement

Currently, Spike Protection bases its threshold on the average number of error events over the past 7 days for the whole project.

This request is divided into 2 parts:

- Some customers want to be able to customize the Spike Protection threshold so that events get dropped after the project volume goes over it.

- Some customers want to be able to use Spike Protection as a throttling system for specific issues based on fingerprint. Meaning that if an issue has 3000 occurrences, they just want to send 1000 events of that issue to Sentry and drop the remaining 2000 (We have DSN rate limits but these blindly drop events (no matter the fingerprint) as soon as the limit is reached)

### Solution Brainstorm

The ability to customize thresholds for Spike Protection and use a system to be able to throttle events coming from specific issues based on the fingerprint

### Product Area

Settings - Spike Protection

**Comment by Dhrumil-Sentry** [comment]
Spike protection is meant to protect our customers from sudden quota-depleting spikes. It's not meant to be a quota management tool. We're unlikely to make these enhancements anytime soon
