### ISSUE TITLE
Activity emails don't respect the project subject template

### ISSUE THREAD

**Issue by snopoke** [getsentry/sentry#4939]
None of the activity emails respect the project subject template. I realize that the not all of the activities may have the necessary information to completely fulfill the template (though ideally they should all have a minimal set of required fields).

Specifically we use `tag:environment` in our subject template which allows us to see which environment a notification is from. Without that info it's impossible to filter the notifications appropriately (e.g. staging vs production).

Version: Hosted sentry service at Sentry.io

**Comment by dcramer** [comment]
This is intentional as activity emails are different than alerts. I'm going to close this to avoid anyone getting their hopes up that this will change.

**Comment by pcorliss** [comment]
Howdy, found this issue after running into the same issue. Our threading breaks because we have a custom subject template for errors, but don't have that ability for activity/workflow and the configuration does not appear to be shared.

If the intention is to not use the same template. Perhaps adding a customization field for the workflow would be possible?

**Comment by dcramer** [comment]
They simple cannot match subjects as the context available in each is different. Alerts are based on a single event whereas workflow is an issue.

**Comment by vladgurovich** [comment]
What are Activity emails? When someone resolves or comments on an issue?
Shouldnt you have enough context at the time to satisfy at least some subject template variables, such as project name, environment etc so it doesnt break email threading and filters

**Comment by ruimarinho** [comment]
Ran into this issue for the same reason. I was expecting activity emails to be grouped under a similar context. I thought the custom subjects would also apply to these emails. Keeping the email thread would be very nice.
