### ISSUE TITLE
Issues tracking links to GitLab issues are incorrect

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#49409]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Link a Sentry issue to a Gitlab project 
Select the link and you are redirected to: https://gitlab.com/testintsentry/newtest/issues/2
<img width="1102" alt="image" src="https://github.com/getsentry/sentry/assets/99350819/6f271f27-4f94-47ae-a3ab-eebe11a51a96">

### Expected Result

the correct format/redirect should be: https://gitlab.com/testintsentry/newtest/-/issues/2

<img width="1220" alt="image" src="https://github.com/getsentry/sentry/assets/99350819/fe1f0abe-fe44-40e4-8250-512b22f472a2">

### Actual Result

redirected to a URL that returns a 404: https://gitlab.com/testintsentry/newtest/issues/2

### Product Area

Issues

### Link

https://org2-w7.sentry.io/issues/4167183106/?project=6229212&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1837) by [Unito](https://www.unito.io)

**Comment by amalyshkin** [comment]
This issue is the result of legacy routes removal in GitLab announced in https://docs.gitlab.com/ee/update/removals.html#legacy-routes-removed and released in https://gitlab.com/gitlab-org/gitlab/-/issues/28848#release-notes. The old link format is not valid anymore.

**Comment by beerik94** [comment]
This can be closed imo since gitlab is reverting the change in 16.1 
https://gitlab.com/gitlab-org/gitlab/-/issues/412435
