### ISSUE TITLE
Alert list `combined-alerts` query slow because of issue alerts last triggered date

### ISSUE THREAD

**Issue by scttcper** [getsentry/sentry#49411]
We need to speed up the combined-alerts endpoint that is used on the alerts list. Its slow because of a subquery to fetch the alert's last triggered date. What's slow is alerts that trigger a lot have a lot of results and its doing something like `Max(select date from alerts_triggered)`

ACs:
- Change the last triggered query to only look back so far?
- Start deleting the old history (how many months?) in the cleanup command https://github.com/getsentry/sentry/blob/91f54f860011a5d90c2d573d358f25471dcda8b8/src/sentry/runner/commands/cleanup.py
- update docs to reflect that we do not keep the entire history

perfromance query
https://sentry.sentry.io/performance/summary/?project=1&query=http.method%3AGET&referrer=performance-transaction-summary&statsPeriod=14d&transaction=%2Fapi%2F0%2Forganizations%2F%7Borganization_slug%7D%2Fcombined-rules%2F&unselectedSeries=p100%28%29

**Comment by ceorourke** [comment]
Closing as the performance as shown in the provided link is 1ms today. Feel free to reopen if this regresses.
