### ISSUE TITLE
Support backreferences in Advanced Data Scrubbing regex replacement

### ISSUE THREAD

**Issue by jtg-github** [getsentry/sentry#49467]
### Problem Statement

The Advanced Data Scrubbing currently supports a Regex Match rule with a Custom Placeholder to replace the text matched. Unfortunately, the Custom Placeholder cannot be a backreference: it has to be a literal string. The Custom Placeholder should support backreferences when a Regex Match rule is used and has captured groups.

### Product Area

Settings - Security & Privacy

**Comment by cmanallen** [comment]
Backtracking can have exponential complexity which will have severe run time implications for our systems.  We will likely never support this.
