### ISSUE TITLE
Hide replay UI for desktop & mobile projects

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#49464]
Desktop and mobile projects can never have replay data. Backend project types (python, php, etc) can however.

We should not show any replay related buttons inside the Issues or Transactions pages for projects that are: iOS, Android, Window, etc.

Some places to hide (there are more):

![Image](https://user-images.githubusercontent.com/187460/239579370-925cb234-fbd8-4ee2-9906-f2634111c468.png)

**Comment by jas-kas** [comment]
cc/ @michellewzhang 👀
