### ISSUE TITLE
Request to change the way Slug and Project Name are being used when creating a Project

### ISSUE THREAD

**Issue by Prithvirajkumar** [getsentry/sentry#49488]
### Problem Statement

Currently the way Sentry works is that when adding a Slug as part of project creation, the slug serves as a reference for the project throughout Sentry. It will appear in various parts of the platform such as the Projects page, Stats page, etc. 
The Slug will also be used as part of the URL when referencing the project.

The Project Name added as part of project creation will be used as the internal name of the project and will only be available within the General Settings of the specific project.

This means that if I use the terraform plugin and specify the following:
```
resource "sentry_project" "main" {
  organization = sentry_team.main.organization
  team         = sentry_team.main.id
  name         = "prithvi-001"
  platform     = "python"
  slug         = "001"
}
```

The result would be that the project would be referred to as '001' within Sentry along on the URL (example) - https://testorg-az.sentry.io/settings/projects/001/

'prithvi-001' on the other hand will only be visible within the Project Settings of the selected project. 

Screenshots:
![Screenshot 2023-05-19 at 12 30 09 PM](https://github.com/getsentry/sentry/assets/56081556/459c2e92-14fc-4285-9012-f21b9780167c)
![Screenshot 2023-05-19 at 12 30 48 PM](https://github.com/getsentry/sentry/assets/56081556/50d664e0-7b6d-40c4-b284-e927dfb4d800)
![Screenshot 2023-05-19 at 12 30 18 PM](https://github.com/getsentry/sentry/assets/56081556/e23109e1-170c-4034-bfc2-363a27645765)
![Screenshot 2023-05-19 at 12 30 40 PM](https://github.com/getsentry/sentry/assets/56081556/d345bd99-7d93-432f-8b63-654205ce276f)
![Screenshot 2023-05-19 at 12 30 29 PM](https://github.com/getsentry/sentry/assets/56081556/3a30c8e3-465e-40bb-b150-2314a02ba1fe)

This has some drawbacks, example if I use GitLab and want to configure the following as part of project creation: 
name = "GitLab_Project_Name"
slug = "Gitlab_Project_ID"

In this case, the slug which is now a unique set of numbers (from GitLab) will be used as my project's name throughout Sentry. While the name would only be available within Project Settings.  
The slug will also be used as part of the URL which is expected. 

If I switch this to:
name = "Gitlab_Project_ID" 
slug = "GitLab_Project_Name"

The slug which is now the project name will be used as my project's name throughout Sentry. 
However, the ID will not longer be available in the URL and I can only validate this by going to the Project Settings. 

The goal of passing the Gitlab_Project_ID to Sentry is to have this information accessible, however there are drawbacks to adding it as the Project Slug or the Project Name

The expected behaviour is that when I set the following: 
name = "GitLab_Project_Name"
slug = "Gitlab_Project_ID"
The corresponding URL of the project should be - https://example-org.sentry.io/settings/projects/GitLab_Project_ID/
And the name of the project should be - GitLab_Project_Name (referred across Sentry, not just in project settings).

### Solution Brainstorm

The solution here would be to modify the way Project Slug and Project Name:
- The Project Slug should be used as part of the URL. 
- The Project Name should be used as a reference to the project throughout Sentry. 

### Product Area

Projects

**Comment by Dhrumil-Sentry** [comment]
@Prithvirajkumar We only have a project name field to allow integrators to provide a name for the project that Sentry then "cleans" and creates a slug out of.

Project slug is the only identifier used across our UX and URLs. Using two distinct values for project name and project slug is not a supported use case and we have no plans to support this either
