### ISSUE TITLE
Change default mute to mute for everyone if alert action is Slack

### ISSUE THREAD

**Issue by ceorourke** [getsentry/sentry#49494]
If you just click "mute" on the alert details page, the alert will be muted just for the user, as opposed to muted for everyone (which is in the dropdown). For alerts that have actions that directly go to a Slack channel or Slack user (e.g. "Send a notification to the {workspace} Slack workspace to {channel or user}") the only mute available should be "mute for everyone".

We can potentially change the button and banner language if the alert action is going to a user, since "mute for everyone" sounds a little odd (but on the backend that's how we need to process it) if that's not too much trouble.

If the alert has multiple actions this might get a bit hairy. If the actions go to multiple Slack channels, keep as "mute for everyone". If the actions go to a bunch of different places, maybe just keep the current behavior and let the user figure it out.

Ensure the link in the emails obey this behavior as well.

**Comment by roggenkemper** [comment]
Done in https://github.com/getsentry/sentry/pull/49573
