### ISSUE TITLE
webhooks log

### ISSUE THREAD

**Issue by sul4bh** [getsentry/sentry#4950]
## Feature request

I see that sentry does not log webhooks requests it makes. Logs would useful when trying to integrate sentry with other services. It would help figure out which side of the integration is not functioning as expected.

If there is enough interest in this feature, I can work towards creating a PR.

**Comment by dcramer** [comment]
@mitsuhiko 

We were talking about this internally the other day. There's complexity in the amount of data that would get stored here, which means it would need very heavy/active GC.

**Comment by mattrobenolt** [comment]
Yeah, so this has come up before. I've personally wanted this, but this comes with a challenge that most other webhook services don't deal with: scale and volume of data.

For us, it's possible to generate thousands of webhooks per minute from each project. This would be extremely expensive to log every single one. Ideally, we'd add logs for all notifications.

So I haven't come up with a reasonable solution here myself, and internally we haven't spent a ton of time talking about it.

**Comment by sul4bh** [comment]
The obvious solution I can think of is having `celery` do the cleanup based on a configuration value. But I am sure it is more complicated than that.

**Comment by mattrobenolt** [comment]
It's not so much the cleanup, it's the fact that we'd be writing potentially thousands of events per minute, and in sentry.io's case, likely many hundreds per second, since it's possible that every single event may trigger multiple webhooks or other notifications that we'd wanna log. This is a lot of extra data.

I'd rather we figure out a way to either reliably sample, or only surface errors instead of just success logs, personally.

**Comment by KFoxder** [comment]
+1 would really like to see this especially since I am now trying to figure out if it Sentry or PagerDuty that isn't doing its job. PagerDuty has the logs to prove they aren't but can't get the logs for Sentry to see if the "Sentry Issue" is being sent over to PagerDuty.

**Comment by developer99** [comment]
+1

**Comment by orangle** [comment]
+1

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
