### ISSUE TITLE
Investigate server filter for `file://`

### ISSUE THREAD

**Issue by scttcper** [getsentry/sentry#49519]
If we added a filter for urls starting with `file://` how may issues would be filtered and for how many projects / orgs.

This might be difficult to measure since its in tagstore.

**Comment by scttcper** [comment]
- Add it to the localhost filter

**Comment by scttcper** [comment]
started reaching out to the data team https://sentry.slack.com/archives/C5939A927/p1685487923814459

**Comment by lobsterkatie** [comment]
Filter added in https://github.com/getsentry/relay/pull/2214.
