### ISSUE TITLE
Login Page is not working

### ISSUE THREAD

**Issue by ktambehha** [getsentry/sentry#49527]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

https://sentry.bfortress.com/auth/login/annkissam/
![image](https://github.com/getsentry/sentry/assets/109623564/84bf9c1e-2714-4bd9-a96b-3615418b20a1)

### Expected Result

Login Page 

### Actual Result

![image](https://github.com/getsentry/sentry/assets/109623564/15bfc5a2-4109-4afb-b7be-0110e63a79af)

### Product Area

Sign In

### Link

https://sentry.bfortress.com/auth/login/annkissam/

**Comment by leedongwei** [comment]
Hello @ktambehha, the link that you provided is for a self-hosted version of Sentry. 

It likely to be a configuration issue on your end, please contact your admin for help.

As far as I can tell, it's unrelated to code changes on our end.
