### ISSUE TITLE
Investigate server filter for Dead object firefox garbage

### ISSUE THREAD

**Issue by scttcper** [getsentry/sentry#49520]
We should be able to find how many orgs / projects have these issues since the title is in postgres.

**Comment by scttcper** [comment]
We would add this to `Filter out errors known to be caused by browser extensions`

**Comment by scttcper** [comment]
Title exists in a column that can't be accessed (gzip) but there's another way to count titles - https://redash.getsentry.net/queries/4237/source Its only issues viewed but 27% of issues with that title were ignored, however the count is pretty low.

Maybe the count makes it low risk? But it also makes it seem somewhat uninteresting.

**Comment by scttcper** [comment]
Total number of views https://redash.getsentry.net/queries/4238/source

**Comment by scttcper** [comment]
https://www.notion.so/sentry/Result-from-can-t-access-dead-object-investigation-353bf4b84cc74913a1606c129b3985bd

**Comment by lobsterkatie** [comment]
Filter added in https://github.com/getsentry/relay/pull/2215.
