### ISSUE TITLE
Page not found when linking identities from Teams

### ISSUE THREAD

**Issue by Aralun** [getsentry/sentry#49538]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Click the `Resolve` button in a Sentry card in a Teams channel
2. Follow the Sentry plugin instructions by clicking the `Link Identities` button sent via MP ![Teams screenshot](https://github.com/getsentry/sentry/assets/4149052/3fa48596-b820-4961-8e84-e94753e067b1)
3. Get the crashy page

### Expected Result

Some sort of identification process, I presume.

### Actual Result

"Page not found"

![crashy Sentry page screenshot](https://github.com/getsentry/sentry/assets/4149052/3b6b3745-2ecf-4829-9859-e18e1044b065)

### Product Area

Unknown

### Link

https://sentry.io/extensions/msteams/link-identity/{What I assume is an auth token that I should definitely not share}

**Comment by snigdhas** [comment]
Hi @Aralun, would you be able to share any error messages in the JS console or Network tab from this request?
