### ISSUE TITLE
Create alerts at the org level based on number of events

### ISSUE THREAD

**Issue by serglom21** [getsentry/sentry#49549]
### Problem Statement

Sentry currently sends alerts when an org has depleted 80% and 100% of the overall org quota. But when it comes to creating metric alerts based on configurable thresholds, this is only available on a per-project basis.

It would be great to be able to create quota alerts that takes into consideration the added consumption for the whole organization

### Solution Brainstorm

Be able to create metric alerts for the overall org event consumption

### Product Area

Alerts

**Comment by Dhrumil-Sentry** [comment]
@sergiosentry can you please ask the customer what type of thresholds are these customers looking for?

**Comment by realkosty** [comment]
Related: https://github.com/getsentry/sentry/issues/30059

**Comment by serglom21** [comment]
@Dhrumil-Sentry Based on conversations I have had with some customers, good thresholds would be percentage-based (i.e alert me whenever the overall org consumption goes over 60%)

**Comment by Dhrumil-Sentry** [comment]
CC @sentrypri - Another ticket related to configurable quota notifications

**Comment by brianthi** [comment]
This has been implemented and configuration for it is available on the Subscriptions page on the Notifications tab.
