### ISSUE TITLE
Show Environment in "Failed to Process Events" notification email

### ISSUE THREAD

**Issue by michaelchai-sentry** [getsentry/sentry#49553]
### Problem Statement

A customer org's owners received multiple "Failed to Process Events" notification emails after updating their SDKs to the latest version, with an example email that we send out attached as an image here. This caused some concern for them as debug symbol files were being correctly uploaded and we couldn't find anything listed in the "Processing Issues" tab. Upon digging a little deeper, we realized that it was for staging issues that they don't upload dSYM files for.
![Failed to Process Events email](https://github.com/getsentry/sentry/assets/98921471/d576e102-cbd3-466c-8759-15e41ab0861a)

### Solution Brainstorm

The suggestion from the customer was to show which `Environment` these failed to process issues are from. Having a staging issue failed to process is much less critical than a production issue failing to process, and when all org owners get an email it can raise unintended alarms

### Product Area

Discover

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1835) by [Unito](https://www.unito.io)

**Comment by ceorourke** [comment]
Closing as we no longer have this email
