### ISSUE TITLE
Ability to Ignore Errors in Non-Production Environments until Occurrence in Production

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#49559]
### Problem Statement

Users would like to have the ability to ignore specific errors that predominantly occur in non-production environments until they are encountered again in a production environment. 

### Solution Brainstorm

 Users would like to find that option, with a submenu for all available environments:
 
<img width="294" alt="image" src="https://github.com/getsentry/sentry/assets/99350819/91c5d3e4-2c21-4063-b943-9c20f0e5b768">

### Product Area

Issues

**Comment by brianthi** [comment]
In the future, we're planning to remove those ignore sub options in favor of just having a default behavior available. Something we should look into for non-prod environments more generally is, should we stop those notifications all together by default and allow users to opt in instead?

**Comment by rondanen** [comment]
Agreed, this would be very useful.

**Comment by barkbarkimashark** [comment]
Dupe of https://github.com/getsentry/sentry/issues/12341
