### ISSUE TITLE
Replay: Add Electron to Replay onboarding

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#49595]
When navigating to the Replay index and selecting Electron we show:

<img width="1095" alt="image" src="https://github.com/getsentry/sentry/assets/1633368/f8902b61-225f-436b-9893-4cd771238725">

But Electron is already supported

**Comment by bruno-garcia** [comment]
This is a blocker for: https://github.com/getsentry/sentry/pull/51258

**Comment by jas-kas** [comment]
cc/ @michellewzhang 👁️
