### ISSUE TITLE
sendmail

### ISSUE THREAD

**Issue by vassilevsky** [getsentry/sentry#4959]
Is it possible to set up mail delivery via sendmail?

If so, how?

Thank you for amazing software! 💖

**Comment by mattrobenolt** [comment]
Unfortunately, we only support SMTP.

**Comment by iSWORD** [comment]
is this possible in 2018 almost 2019? :smiley:

**Comment by mattrobenolt** [comment]
Pull requests are welcome. We have no use for this ourselves, and obviously, very low demand so it’s not likely we’d invest our own resources any time soon.
