### ISSUE TITLE
Bug: Highlighting the first instance of DOM element only appears after pressing play

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#49601]
### Reproduction Steps
1. Search `click.tag=button`
2. Select a replay with enough activity and duration
3. Press play on replay

### Expected Behavior
The player already shows/highlights the first instance of the DOM element

### What happens
You have to press play before seeing the first instance of the DOM element

Can share video in slack

**Comment by ryan953** [comment]
I've run the repro steps and this looks fixed now. 

When I do a click-search and open one of the results, i see a dom node is spotlighted (everything is blue except that spot). When i click play the blue spotlight will go away. Also if i hover something in the DOM tab (which is open by default) the blue spotlight will go away.
