### ISSUE TITLE
Disabled dashboard-level filters in the widget creator are confusing

### ISSUE THREAD

**Issue by brentc** [getsentry/sentry#49616]
The dashboard-level filters included in the "Filter your results" section presented as disabled inputs are confusing

The idea is that since dashboard-level filters affect widgets we should show them here so users understand what they're seeing in the preview, but by using disabled input it sends mixed messages to users. Disabled implies "could be enabled" but it's unclear why they're disabled ("Did I do that?", "Is there something I could change to make these enabled?")

We should figure out a better way to present "These filters are being applied because of the dashboard this widget belongs to" 

![image](https://github.com/getsentry/sentry/assets/466158/883e93ba-6f3d-4ba2-88d9-5e58b79ee46b)

**Comment by Abdkhan14** [comment]
1. Added a better description in bolder text and sectioned out the search bar from the disabled filters. 
<img width="875" alt="Screenshot 2023-05-24 at 4 18 37 PM" src="https://github.com/getsentry/sentry/assets/60121741/6367b601-6e28-4de5-9c06-478532f9d073">


3. The issue led us to a bug, the disabled filters were still interactable. Fixed here: https://github.com/getsentry/sentry/pull/49634
