### ISSUE TITLE
Duplicate y-axis values

### ISSUE THREAD

**Issue by silent1mezzo** [getsentry/sentry#49615]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When viewing a widget where the y-axis is duration you'll sometimes get duplicate values due to rounding.

1. Go to dashboards
2. View a widget where y-axis is duration and there's multiple items charted.

### Expected Result

y-axis only shows a single value, the chart is accurate.

### Actual Result

When viewing a widget where the y-axis is duration you'll sometimes get duplicate values due to rounding.

e.g.
![image (4)](https://github.com/getsentry/sentry/assets/155016/c65968c0-a475-46ac-b43f-2b50ba3f4acd)
<img width="816" alt="Screenshot 2023-05-23 at 11 11 14 AM" src="https://github.com/getsentry/sentry/assets/155016/3003b006-c969-496b-a765-66021672e86a">

### Product Area

Dashboards

### Link

https://sentry.sentry.io/dashboard/38857/?project=11276&statsPeriod=24h

**Comment by Abdkhan14** [comment]
Hey @silent1mezzo thank you for pointing this out. The bug has been fixed. Here's the [PR](https://github.com/getsentry/sentry/pull/49855).
