### ISSUE TITLE
Migration 0286 does not work on postgresql 8.4

### ISSUE THREAD

**Issue by spapas** [getsentry/sentry#4961]
I tried upgrading my hosted sentry from 8.12 to 8.13. Unfortunately my sentry it is hosted in a rather old Centos (6.8) and using the postgresql from the repos (8.4.20). This version of postgresql does not support the `ALTER TABLE table DROP CONSTRAINT IF EXISTS` syntax so running the migration 0286_drop_project_fk_release_release_file fails because of the lines:

```
db.execute("ALTER TABLE sentry_release DROP CONSTRAINT IF EXISTS project_id_refs_id_21d237e2")
db.execute("ALTER TABLE sentry_releasefile DROP CONSTRAINT IF EXISTS project_id_refs_id_878696ea")
```

I'm getting an error of the form: `django.db.utils.ProgrammingError: ProgrammingError('syntax error at or near "EXISTS"\nLINE 1: ALTER TABLE sentry_release DROP CONSTRAINT IF EXISTS project...\n                                                      ^\n',)`

As a temporary solution, I just executed the following to drop  the constraints (without using the IF EXISTS) from the database:
```
ALTER TABLE sentry_release DROP CONSTRAINT project_id_refs_id_21d237e2;
ALTER TABLE sentry_releasefile DROP CONSTRAINT project_id_refs_id_878696ea
```

and commented out the corresponding  two lines from the migration. After that all migrations run smoothly and sentry 8.13 is working fine with my Postgresql 8.4.20 installation!

**Comment by mattrobenolt** [comment]
I don't think we explicitly state this anywhere, but we'll likely never attempt to support Postgres that old. I'd say at minimum 9.0.

If you ran that alter, then can then fake the migration by doing `sentry django migrate --fake sentry 0286` to skip past it and continue on.

**Comment by spapas** [comment]
Hello @mattrobenolt yes I understand that my postgresql is too old however please notice that everything else until Sentry 8.13 (*except* that migration) works perfect ! I've already skipped this migration and everything else runs fine.

**Comment by lilydjwg** [comment]
Hi @mattrobenolt [the doc](https://docs.sentry.io/server/installation/) doesn't say which versions of postgresql are support. Maybe you can update that?
