### ISSUE TITLE
Jira and Sentry integration error when trying to create a Jira Issue - Follow up of #42245

### ISSUE THREAD

**Issue by marbon87** [getsentry/sentry#49612]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1.Create an integration between Jira and Sentry according to this documentation: https://docs.sentry.io/product/integrations/issue-tracking/jira/
2.Navigate to Sentry
3.Click on "Issues" and open a specific issue
4.Click on "Link Jira Server Issue"

### Expected Result

When clicking on "Link Jira Server Issue", Jira issue create screen should appear without any errors and allow to create a Jira issue

### Actual Result

![image](https://github.com/getsentry/sentry/assets/2949525/878075fd-43ca-427b-92d1-26cf3afb107f)

### Product Area

Issues

### Version

23.5.0

**Comment by brianthi** [comment]
Hi @marbon87, this usually happens when the user used to authenticate into Jira was revoked access to the project.  The solve for this is to uninstall and reinstall your integration.  I'm keeping this in the backlog to track UX improvements that can be made for this flow.

**Comment by marbon87** [comment]
Hi @brianthi , that's not fully corrected. 
We habe a bigger jira setup with about 200 projects and the problem occurs if the sentry user is not allowed to access the first project in the list. To fix this, jira should not load the first project as default but let the user choose the correct project.

**Comment by GabeVillalobos** [comment]
Unfortunately the team is understaffed and we can’t prioritize this fix, but we’re always open to community contributions.
