### ISSUE TITLE
Feature request: scheduled maintenance window for project

### ISSUE THREAD

**Issue by ktosiek** [getsentry/sentry#4966]
It would be useful to stop Sentry from alerting when the app is in a known problematic state.
Example: doing database maintenance might cause DB errors to show up, which are not important at the moment, but I don't want to ignore them as they are important normally.

**Comment by mattrobenolt** [comment]
Cool, so dropping some initial thoughts:

I imagine you'd envision this happening at project level. But how do environments factor into this? WOuld you want to say "maintenance for project A on production"?

Whould this suppress all notifications? I'm assuming so.

What about time window? I feel like I'd rather say, "maintenance for X hours".

Would you want this to notify team members about going into/out of maintenance?

And lastly, how would you expect the UI to reflect this? I feel like we'd want to make it pretty explicit and bold to say "yo, this is in maintenance."

**Comment by ktosiek** [comment]
I'm currently using separate projects for each environment, but yes - I would use the feature to silence specific environments.

It's hard to tell which issues/regressions are due to ongoing work, so I'd imagine actually suppressing all notifications triggered by issues. I was thinking about resolving all issues that got (re)opened while in maintenance when it ends - that way issues that persist after that period will cause alarms.

Yes, I think declaring the time window upfront is the best way. It's too easy to forget to turn it off.

I'm already notifying the team by hand - having each monitoring system notify about maintenance would generate as much mail as the alarms already do :-)

I'm no designer, but changing the colour of the stream actions bar + a description of why it's changed would help. Maybe even a list of projects in maintenance on the dashboard?

**Comment by jasonhkennedy** [comment]
+1 to this. Using environments as well. I would expect it to suppress notifications. Having a time window up front is nice, but having a way to also turn it off explicitly too. I think we would benefit from a notification of maintenance.

**Comment by sanjioh** [comment]
+1 to this!

An interesting subfeature would be having some sort of recurring scheduled maintenance. The use case would be silencing environments at specific hours of day/night, when events are expected to be safely ignorable (e.g.: routine service restarts).

**Comment by ktosiek** [comment]
BTW it looks like this is a duplicate of #1517

**Comment by dcramer** [comment]
Going to actually just close this in favor of #1517 to ever so slightly help issue tracker volume.
