### ISSUE TITLE
Increase 30s limit for transactions

### ISSUE THREAD

**Issue by SimonRelu** [getsentry/sentry#49667]
### Problem Statement

Currently transactions are limited to 30 seconds. Any information afterwards will be disgarded. Our use case is profiling the performance of Machine Learning operations. These often take longer than 30 seconds therefore we'd like the option to increase this limit.
<img width="1510" alt="Screenshot 2023-05-24 at 09 48 40" src="https://github.com/getsentry/sentry/assets/110388884/1bbdcc42-9632-45c1-bef1-c3497f8a0bbd">

### Solution Brainstorm

Add an option in the `sentry_sdk.init` to increase this limit (f.e. `traces_sample_time_limit`) which defaults to 30 seconds.

### Product Area

Profiling

### Update

Currently I've pached this constant myself like so:

```
from sentry_sdk import profiler

profiler.MAX_PROFILE_DURATION_NS = int(5 * 6e10)  # 5 minutes
```

This seems to work

**Comment by Zylphrex** [comment]
This is something we want to eventually enable but is not currently on the roadmap. For more information please follow #48931

**Comment by realkosty** [comment]
Updated name "for transactions" -> "for profiles" to be more accurate

**Comment by realkosty** [comment]
Another customer (enterprise) requested this, their uses case is similar - long-running ML pipelines

**Comment by realkosty** [comment]
Continous Profiling is now available in beta
https://sentry.io/changelog/continuous-profiling-available-for-early-adopters/
https://docs.sentry.io/platforms/python/profiling/#enable-continuous-profiling
