### ISSUE TITLE
Framework Modal list has top frameworks first

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#49689]
**Background:**

When selecting the vanilla platfroms during project creation for JS, Node, and Python, the user is presented with a modal to select a specific framework. 

**Proposal:**
It would be nice to have the top frameworks for each language at the top of the list. Which might encourage more users to select and not scroll (vs ABC ordering)

**Python:**
1. Django
2. Flask
3. FastAPI
4. AWS Lambda
5. aioHTTP
remainder ABC

**JavaScript:**
1. React
2. NextJS
3. Vue
4. Angular
5. Svelte
6. SvelteKit
7. Remix
Remainder ABC

**Node:**
1. Express
2. AWS Lambda
3. Serverless Cloud
4. GCP Functions
5. Koa
Remainder ABC

![Image](https://user-images.githubusercontent.com/47563310/240650315-76974a46-ed62-40b9-88bf-25aed05e5a3d.png)

**Comment by leedongwei** [comment]
@smeubank Seems like your team is owning this? https://github.com/getsentry/sentry/pull/49305
