### ISSUE TITLE
Delete releases from the UI

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#4969]
Right now this is only possible from Sentry CLI / the API. Artifacts can be deleted via the UI, but not releases.

**Comment by ismay** [comment]
Yeah this would be great 👍

**Comment by adamreisnz** [comment]
This would indeed be nice to have, especially since doing it via CLI seems to be bugged at present, not accepting the `--org` flag but asking for it if it's ommitted:

```
sentry-cli releases delete xxxxxx
error: An organization slug is required (provide with --org)
```

```
sentry-cli releases delete xxxxxx --org yyyy
error: Found argument '--org' which wasn't expected, or isn't valid in this context

USAGE:
    sentry-cli releases delete <VERSION>
```

**Comment by G-Rath** [comment]
This would be fantastic

**Comment by stephan-v** [comment]
10/10 would want.

**Comment by john1jan** [comment]
how to do it with sentry cli ?

**Comment by ucorina** [comment]
@john1jan 
I use `sentry-cli releases delete <VERSION>`.

You can get a list of all the existing releases with `sentry-cli releases list`.

**Comment by rohandzone** [comment]
@ucorina  `sentry-cli releases delete <VERSION>` gives me following error. All the issues in that release has been marked as resolved.

`This release is referenced by active issues and cannot be removed`

**Comment by adamreisnz** [comment]
I get these kind of errors a lot too. I find sentry is rather over protective of deleting things. If users want something *gone*, sentry should imo just nuke it, including any related artefacts, issues, etc. etc.

**Comment by pupeno** [comment]
I would like this too.

**Comment by kumavis** [comment]
+1

**Comment by BlackHole1** [comment]
+1

**Comment by metaa** [comment]
I can't believe this still isn't a thing
