### ISSUE TITLE
Add more escalating analytics to redash dashboard

### ISSUE THREAD

**Issue by jangjodi** [getsentry/sentry#49692]
Add the following to the [redash dashboard](https://redash.getsentry.net/dashboard/issue-escalation-and-unignored-metrics?p_date=d_last_7_days&p_today=d_now):

For each org (daily and a 7 day moving average roll up):
- number of issue viewed
- number of issue archived
- number of issues that archived and escalated
- number of issues that archived escalated and then assigned/resolved/given feedback on
- number of positive feedbacks, number of negative feedbacks on escalated issues

**Comment by therealarkin** [comment]
it will best if we can as many of these as possible in amplitude

**Comment by brianthi** [comment]
for the feedback on issue details page, you can refer to the amplitude event, Issue Details: Escalating Feedback Received
