### ISSUE TITLE
Still can't disable error notifications

### ISSUE THREAD

**Issue by Rambomst** [getsentry/sentry#4971]
Version: 8.13.0 with Docker

I reported this issue awhile ago but it was closed and it is still happening.

I keep receiving email errors yet I believe I have the notification settings turned off correctly. [http://imgur.com/a/kgJgq](Here) is a screenshot of my notification settings.

In the bottom of the emails it says 

> You are receiving this email because you have opted to receive updates for all issues within projects that you are a member of.

However I believe that to be incorrect

**Comment by kylehsu** [comment]
I also have this issue with sentry.io where I get email alerts for a project that I've turned off.

In https://sentry.io/settings/account/notifications/alerts/

I have alerts set to OFF for that project and also have project alerts toggled off on my account https://www.dropbox.com/s/x2fo7xwdr4cro0q/Screenshot%202018-09-17%2011.33.17.png?dl=0

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
