### ISSUE TITLE
ignore > archive in popover

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#49718]
As discussed in today's standup meeting, it would be nice to have the popover be more explicit that Ignore is changing to Archive.

**Comment by robinrendle** [comment]
<img width="1634" alt="CleanShot 2023-05-31 at 11 25 23@2x" src="https://github.com/getsentry/sentry/assets/1900676/b553440a-cb8f-47b4-8ad8-5a84d9f65a5b">
