### ISSUE TITLE
Feature Request: In saved searches, "at least X events" filter for the issues

### ISSUE THREAD

**Issue by arturaz** [getsentry/sentry#4972]
I'd like to request a simple feature request.

In saved searches, could we have a "at least X events" filter for the issues?

The problem is we get a lot of random issues from our clients that only have 10 or 20 events which is mostly noise. Perhaps user has a bad device. Perhaps his package was corrupted. Lots of reasons.

When real errors happen we get thousands of errors. It would be great if we could filter errors in the issues list that had at least X events.

**Comment by tkaemming** [comment]
This is available now as `timesSeen`, e.g. `timesSeen:10`, or `timesSeen:>10`, etc. I'll update the documentation soon.

**Comment by mraxus** [comment]
@tkaemming Can you confirm that this feature is currently broken in the Sentry search UI / as query param? I cannot get this to work and I get no suggestions/autocompletes at all when writing anything in the `timesseen` filter box. All values are cleared onBlur =-(

**Comment by tkaemming** [comment]
It seems to be working for me. If you're having trouble with it on sentry.io, write into support and we'll take a look.

**Comment by mraxus** [comment]
@tkaemming will do.
