### ISSUE TITLE
How many service and cron workers can run (ambigious documentation)

### ISSUE THREAD

**Issue by fredvd** [getsentry/sentry#4973]
In the Sentry documention in queue.rst the asynchronous workers are discussed. Below the cron worker this is stated:

> It’s recommended to only run one of them at the time or you will see unnecessary extra tasks being pushed onto the queues but the system will still behave as intended if multiple beat processes are run. This can be used to achieve high availability.

To what is them referring? The Cron workers, or the service worker just above? them is plurar so it suggests both, but I assume that I should be able to start multiple service workers. Only one cron worker seems more logical to me.

**Comment by dcramer** [comment]
Its referring to the cron, but I agree we could be more clear in the documentation.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by BYK** [comment]
(we'll be revisiting these docs soon anyway)
