### ISSUE TITLE
Unable to get server-side data scrubbing working

### ISSUE THREAD

**Issue by karun012** [getsentry/sentry#49743]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Setup self hosted sentry
2. Enable server-side data scrubbing for the whole organization
3. Create a project
4. Create a simple nodejs app on your machine and throw an error containing a password - `throw new Error('This is a sample exception with a password: password123#')` or a string that looks like a credit card number - 4242 4242 4242 4242

### Expected Result

From what I read in the docs I expected the password and/or the credit card looking string to be scrubbed.

### Actual Result

I see the password in sentry. Am I missing something or misunderstanding the feature? Any help will be really appreciated.

<img width="1103" alt="Screenshot 2023-05-24 at 11 44 49 PM" src="https://github.com/getsentry/sentry/assets/2170863/9de0f304-4f0a-4171-8207-e50a9e2247f7">

### Product Area

Issues

### Version

23.5.0

**Comment by snigdhas** [comment]
Hi @karun012 - the data scrubbing [feature](https://docs.sentry.io/product/data-management-settings/scrubbing/server-side-scrubbing/#known-limitations) doesn't extend to code, so the stacktrace in the screenshot wouldn't be scrubbed. The scrubbing is intended to hide sensitive values of the variables from the stacktrace.
