### ISSUE TITLE
Automated preview/sandbox environments at Pull Request

### ISSUE THREAD

**Issue by dakar91** [getsentry/sentry#49762]
### Problem Statement

**Summary*
Bunnyshell is providing free Kubernetes infrastructure to open source projects.

Would you be interested in having preview environments on future pull requests?

Our team @bunnyshell and @bunnyshellosi are ready to help implement the initial pipeline to get you started!

**Motivation*
We really think some of the issues and PRs can benefit from preview environments, like the more than 63 open issues which are UI related: https://github.com/getsentry/sentry/labels/Scope%3A%20Frontend

### Solution Brainstorm

Example PR-preview workflow - https://github.com/aris-bunnyshell/demo-books-php/tree/main/.github/workflows
Example configuration - https://github.com/aris-bunnyshell/demo-books-php/blob/main/.bunnyshell/templates/docker-compose/bunnyshell.yaml

### Product Area

Other

**Comment by dakar91** [comment]
hey @mattgauntseo-sentry maybe you can have a quick look on this issue since you've been working on the Sentry workflows for dev environments?

**Comment by hubertdeng123** [comment]
We already have automated workflow for preview environments on PR's through Vercel.
