### ISSUE TITLE
Cannot confirm email

### ISSUE THREAD

**Issue by fabrizioanichini** [getsentry/sentry#49773]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. I've created a new account
2. Into the User Settings -> security -> U2F -> "ADD"
3. It ask to confirm the email -> "Resend Verification"
4. From the email click on "Confirm"

### Expected Result

Confirmed Email

### Actual Result

<img width="1213" alt="Screenshot 2023-05-25 at 18 51 32" src="https://github.com/getsentry/sentry/assets/34816005/8059d373-1bcb-43e4-8cc9-32ff10f6e27e">

### Product Area

Settings

**Comment by fabrizioanichini** [comment]
Is there anything else I can provide to investigate further?

**Comment by schew2381** [comment]
I followed the steps to reproduce and was able to land on the correct page

<img width="958" alt="Screenshot 2023-06-23 at 11 24 42 AM" src="https://github.com/getsentry/sentry/assets/67301797/fd086ff6-9aa5-4033-9c46-3b9acacfa2ac">

<img width="1110" alt="Screenshot 2023-06-23 at 11 24 50 AM" src="https://github.com/getsentry/sentry/assets/67301797/69e75ccb-aba3-4caf-b55c-f9ee80bfc2c0">
