### ISSUE TITLE
Log when user enables a plugin

### ISSUE THREAD

**Issue by MeredithAnya** [getsentry/sentry#4977]
Logging for when a user enables a plugin (not sure if we would want both logs for adding a plugin and enabling).

**Comment by DoronCohen** [comment]
Hi, I would like to solve this. As I am new to PRs and Sentry I have some questions:
1. Where do you want the logging to happen? My guess is at the API level in project_plugin_detail.py in the post method. Am I right?
2. What do you mean by log? just use the app logger? Or is there a special admin log something to write to?
3. Is there something else I shoud edit? CHANGES file or something?

Thanks

**Comment by MeredithAnya** [comment]
@JTCunning you think you could add the logging this week?

**Comment by mattrobenolt** [comment]
https://github.com/getsentry/sentry/pull/5102

I need to help carry this through since it's not exactly correct. Or @jtcunning can.

**Comment by dylmye** [comment]
OK to close this issue? Seems to be resolved
