### ISSUE TITLE
Integration OAuth flow not showing install button

### ISSUE THREAD

**Issue by prestonp** [getsentry/sentry#49802]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

* Prepare public integration in Sentry dashboard `sentry.io/settings/developer-settings/`
* OAuth client application links to `/sentry-apps/:sentryAppSlug/external-install/` to initiate the OAuth flow
* Select workspace
* The form is missing the install button

(previous correspondence is in Zendesk ticket 85677)

### Expected Result

The resource `/sentry-apps/:sentryAppSlug/external-install/` should show a button for installing the integration.

### Actual Result

The install button is missing but the cancel button is visible. This used to work a few weeks ago.
![image (3)](https://github.com/getsentry/sentry/assets/1265379/ebd91f72-0fc9-42aa-9dd3-a08b059ccdf1)

### Product Area

Settings - Integrations

### Link

https://jam-yw.sentry.io/sentry-apps/jam-staging/external-install/

**Comment by danigrant** [comment]
That was so fast! Thank you so much @scefali! 🚀

**Comment by danigrant** [comment]
We just saw the fix is already live! That was so fast - thank you so much, we are so excited. 🤯

Let us know if we can send you a Jam t-shirt to say thanks 🙏
