### ISSUE TITLE
Question about use of sessionStorage

### ISSUE THREAD

**Issue by BlessYAHU** [getsentry/sentry#49832]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I just had a question. I didn't have access to post on the discussion, so I used this template.  If there is somewhere more applicable to post this, let me know and I will post it there.  

I was viewing different implementations of sessionStorage hooks and came across your useSessionStorage code.  The following line is using sessionStorage:

https://github.com/getsentry/sentry/blob/7d64ff41c664dbe6c5ea3f2550ad4675d6f258a1/static/app/utils/useSessionStorage.tsx#L8

Question: Is using the sessionStorage instead of the sessionStorageWrapper here by design? 

### Expected Result

Just a question

### Actual Result

Just a question

### Product Area

Unknown

### Link

https://github.com/getsentry/sentry/blob/7d64ff41c664dbe6c5ea3f2550ad4675d6f258a1/static/app/utils/useSessionStorage.tsx#L8

**Comment by chadwhitacre** [comment]
Any insight here @JonasBa? Looks like you wrote this in #37181. :-)

**Comment by JonasBa** [comment]
Sorry for the late reply @chadwhitacre, I was on PTO. @BlessYAHU You have a good 👁️ , we should be using the wrapper in that case.

**Comment by chadwhitacre** [comment]
Nice work, people. 🙏

Just gonna [drop this here](https://sentry.io/careers/5027559/) before closing. 😉
