### ISSUE TITLE
Replay Settings Dropdown Breaks Page Layout:

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry#49833]
when the settings button is clicked under the replay player, it seems to break the layout of the page. 
![image](https://github.com/getsentry/sentry/assets/1976777/e9c14be3-f69c-43f7-aad9-d0cef59af072)

**Comment by JoshFerge** [comment]
Seems related to the `CompositeSelect` component?

**Comment by michellewzhang** [comment]
@JoshFerge is this still happening?
