### ISSUE TITLE
1 minute resolution fot issues statistic

### ISSUE THREAD

**Issue by krozhdestvenski** [getsentry/sentry#49853]
### Problem Statement

I need to get statistic for some issues selected by query.
I'm using method https://docs.sentry.io/api/events/list-a-projects-issues/ which has paremeter statsPeriod. But the parameter can only take the following values:  "24h", "14d", and "". 
In my case i need more detilized statistic (optimal period for me is **1 munute**).

Another method "Retrieve Event Counts for a Project"(https://docs.sentry.io/api/projects/retrieve-event-counts-for-a-project/) has similar functionality and  detalisation, which i need(10s,1h,1d). But this method does not support "query" parameter.

### Solution Brainstorm

1. For method https://docs.sentry.io/api/events/list-a-projects-issues/
Add "1m" value in option  statsPeriod. 
In this case method can return statistic for last hour only.

OR

3. For method https://docs.sentry.io/api/projects/retrieve-event-counts-for-a-project/
Add "query" paremeter for this method

### Product Area

Issues

**Comment by mrduncan** [comment]
I'm going to close this for now as we are unlikely to be able to support it in the near term. [Discover](https://docs.sentry.io/product/explore/discover-queries/) may be a good workaround to achieve this
