### ISSUE TITLE
Enable Stack trace linking for Bitbucket

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#49899]
### Problem Statement

Currently Stack trace linking is only available for Github & Gitlab, to provide the same level we need to have this functionality for Bitbucket as well.

### Solution Brainstorm

https://support.atlassian.com/bitbucket-cloud/docs/hyperlink-to-source-code-in-bitbucket/

<img width="911" alt="Screenshot 2023-05-27 at 09 33 26" src="https://github.com/getsentry/sentry/assets/25929053/16bee04c-4f6a-47e5-a266-9c152a30a1b7">

### Product Area

Settings - Integrations

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1844) by [Unito](https://www.unito.io)

**Comment by Dhrumil-Sentry** [comment]
@Angelodaniel This feature is now supported: please see our [changelog entry](https://changelog.getsentry.com/announcements/link-errors-to-your-source-code-in-bitbucket-azure-devops) to learn more
