### ISSUE TITLE
Handle Issue States for Merged Issues

### ISSUE THREAD

**Issue by NisanthanNanthakumar** [getsentry/sentry#49891]
## Objective: 

Code where we handle merge: https://github.com/getsentry/sentry/blob/master/src/sentry/issues/merge.py#L19

Snuba records which Issues are merged. The primary Issue is the one that has the most events. The other Issues will get merged into the primary Issue. 

We should delete the individual Issues EscalatingForecasts and create a new forecast for the combined Issue. On merge, we should inherit on the GroupStatus, GroupInboxReason and GroupHistory of the primary Issue.

**Comment by jangjodi** [comment]
Querying event counts for the primary group after the unmerge returns the wrong results unless all groups involved in the unmerge are included in the query (see https://github.com/getsentry/sentry/pull/53112). This ticket is blocked until that is fixed
