### ISSUE TITLE
Vercel Integration Problem

### ISSUE THREAD

**Issue by gibtang** [getsentry/sentry#49900]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. In https://vercel.com/integrations/sentry Add the Sentry integration
2. In the Vercel project dashboard, it shows that Sentry integration has been added and there is a 'Configure' button on the top right which will lead to your Sentry account
3. In your sentry account, go to /settings/integrations/vercel and it shows Vercel not installed. So something broke in between the integration between Vercel and SentryS

### Expected Result

In your Sentry account, it should show Vercel installed as the integration was done in step 2

### Actual Result

![image](https://github.com/getsentry/sentry/assets/1892674/07e653c1-7085-4b13-baa2-7083d812a745)

### Product Area

Settings - Integrations

### DSN

https://b874bb9f90e349e9af61cc71e126ce7c@o845955.ingest.sentry.io/4504517160927232

**Comment by scefali** [comment]
@gibtang Are you a member of multiple Sentry organizations? I suspect this is the bug where it installed the integration on the wrong org. If so, I'm already looking into this.
