### ISSUE TITLE
Design: Improve framework selection solution

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#49929]
**Problem**: By using the easy framework selection modal solution we've validated that a large portion of new customers who choose a "vanilla" SDK, are actually using a different framework. >40% of those who initially select a "vanilla framework", proceed to select a more specific framework once prompted to do so in the modal. This was an easy MVP however, so now that we've validated the problem, we could investigate a more complex approach to solving the problem, such as more intelligent search.

**Acceptance Criteria:**
- Provide some context why we're sharing new designs for this particular screen
- What the criteria of success would be from changing this screen
- Provide multiple UI options 
- Relay feedback into a separate ticket

**Comment by Jesse-Box** [comment]
Still a relevant ticket, GitHub!
