### ISSUE TITLE
To the sentry developers

### ISSUE THREAD

**Issue by shenmingdidi** [getsentry/sentry#49939]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the dashboard menu.
2. Click on Ceneral.
3. Enlarge Errors by country.

### Expected Result

Hey friends, Sentry is a very good log monitoring system and it has been very helpful to me. Unfortunately, when I clicked into the dashboard menu today, I found something disappointing. I found that the map of China in the Errors by Country menu is not complete because Taiwan is not included in Chinese territory, but is listed separately as a country. As is well known, Taiwan has always been China's territory. I don't know if you are aware of this issue, nor do you know what caused it to occur. Anyway, I believe that this error should not occur in the project. I hope you can investigate the cause of the problem and correct it in a timely manner. China is a beautiful and open country, welcome to come. Looking forward to your reply, users from China.

### Actual Result

![BCD49B24-9BA5-425a-966B-F6E7B5EB7BEE](https://github.com/getsentry/sentry/assets/95074885/fb7dc253-debf-4f7e-96e5-6a32b4f452ee)
![B7B4AC8B-1761-439a-BDBE-C8467B24FA1A](https://github.com/getsentry/sentry/assets/95074885/a217f47a-55c1-4a5c-b90e-6730165a3cf9)
![CBC97C81-12ED-43f6-B865-FE979CE247A1](https://github.com/getsentry/sentry/assets/95074885/948ef9a5-eba1-42de-b15c-a02b4f422493)

### Product Area

Dashboards

### Version

 23.6.0.dev0

**Comment by chadwhitacre** [comment]
Thanks @shenmingdidi. The map is working as intended.

**Comment by chadwhitacre** [comment]
For the record, we discussed this internally, resulting in https://github.com/getsentry/sentry/issues/49995. 🙇
