### ISSUE TITLE
AM1 organisations can't create a new project with session replay enabled

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#49936]
### Problem
AM1 organisations can't create a new project with session replay instrumented.

#### In all cases 👇
- All AM1 organisations are presented with the new wizard experience where a user can opt in/out of specific products.
- By default, Session Replay will be "unchecked" for AM1 organisations

#### If the user isn't a owner 👇 
- They're prevented from "checking" the Session Replay button.
- They are presented with a banner at the top of the page, prompting them to request an owner to update their organisation plan to AM2
- The banner disappears after making the request, showing a toast as confirmation

#### If the user is an owner 👇 
- When a user from an AM1 organisation "checks" Session Replay, the user is prompted by one of two modals
- If the organisation wouldn't incur additional costs they are presented with modal shown in Figma(D)
- If the organisation would incur additional costs they are presented with modal shown in Figma(E)

### Designs
[Figma](https://www.figma.com/file/XQlqqM1lGGA6PcnBjZ83DE/Specs%3A-Replay-Upsell-in-Project-Creation-Flow?type=design&node-id=416%3A1619&t=MH8xljsHmnhaAofC-1)

### Related Tickets
https://github.com/getsentry/getsentry/pull/10610/files#

**Comment by priscilawebdev** [comment]
It's still missing to add the changes to the project loader and do it in a separate PR
