### ISSUE TITLE
Organization Manager cannot remove team

### ISSUE THREAD

**Issue by stellaatsentry** [getsentry/sentry#49937]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Assign the "Manager" role to a user
2. Through that user, go to Organization Settings > Teams > pick a team > Settings > Remove Team

### Expected Result

The button is accessible to an Organization Manager, as in [the documentation](https://docs.sentry.io/product/accounts/membership/#membership) it is states that Managers "Can add/remove teams".

### Actual Result

The "Remove Team" button appears grayed out and is unclickable.
![image](https://github.com/getsentry/sentry/assets/81985895/1111721b-1ad8-46e1-a163-4be71e959279)
This is the case both for Early Adopters (Team-based Roles) and non Early Adopters, and both for empty and populated teams.

### Product Area

Settings - Teams

### Link

https://dragonfruit-dev.sentry.io/settings/teams/removable-team/settings/

**Comment by leedongwei** [comment]
Fix is merged. @stellaatsentry can you check if it is working as expected?
