### ISSUE TITLE
Remove Archive button while on Archive tab

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#50005]
It doesn't make sense to have the Archive button while on the tab that shows only Archived issues.  The button should be removed. 

![Image](https://user-images.githubusercontent.com/1660873/242098145-d5b43137-5557-4b96-ad2b-1d55c608fc00.png)

**Comment by robinrendle** [comment]
Let's make sure we disable it, not remove it.

**Comment by scttcper** [comment]
What if you wanted to change the archive from forever to until escalating

**Comment by brianthi** [comment]
After a bit more discussion, it made sense to add a new button, "Unarchive".  https://sentry.slack.com/archives/C04GMUU6BFA/p1685649350585589

However, unsure if we care to leave the archive button here also so that users can change how they wanted it to escalate
