### ISSUE TITLE
wall duration vs self time

### ISSUE THREAD

**Issue by klboke** [getsentry/sentry#50039]
### Problem Statement

Hello, we're using Sentry's Performance Transaction Summary and found that Sentry only calculates and analyzes the p95 value of the selftime of spans, but doesn't analyze the duration of spans. In most cases, people are more concerned about the duration of methods, for example, OpenTelemetry only has duration. So, is it possible to include both selftime and duration in the analysis?

### Solution Brainstorm

It is known that the transactions_local table in Snuba's ClickHouse contains a field called spans.exclusive_time_32 to store selfTime. It is possible to add a new field called spans.duration_time_32 to store the duration value.

### Product Area

Performance

**Comment by nanoburd** [comment]
Thanks for the feedback. The team is looking at a few different ways we can potentially serve up this use case. In the meantime, backlogging this feedback and linking it to relevant projects.

**Comment by 0Calories** [comment]
Closing, the product has been moving away from `self_time` and we use span duration in most places now
