### ISSUE TITLE
Design UI for multiple release/dist pairs for an artifact bundle

### ISSUE THREAD

**Issue by iambriccardo** [getsentry/sentry#50041]
With the new de-duplication system in place, we will now offer users the ability to bind multiple release/dist pairs to the same artifact bundle. This new association will require some UI changes to make the UX better.

**Comment by Jesse-Box** [comment]
Closing this issue as the designs have been approved

Designs are here
https://www.figma.com/file/2lbakKLk7gp1CYgmZm4NEK/Specs%3A-Source-Map-Project-Settings-v3?type=design&node-id=76%3A1846&t=TJPmlBDxGq7h4xja-1
