### ISSUE TITLE
Internal error when adding Azure DevOps integration 

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#50044]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Follow the steps on this page to install DevOps integration: https://docs.sentry.io/product/integrations/source-code-mgmt/azure-devops/

I was able to reproduce with 3 different accounts with owner permissions in Sentry and organisation owner in Azure.

### Expected Result

The integration is installed. 

### Actual Result

Internal server error: 
![Screenshot 2023-05-31 at 11 14 05](https://github.com/getsentry/sentry/assets/64906376/a254754c-d5e2-45f3-bf85-e2e1f9f7e0ac)

The sentry issue points to JSON decoding error: 
JSONDecodeError
Expecting value: line 3 column 1 (char 4)

https://sentry.sentry.io/issues/4215021150/

The following error is also raised at the same time, not sure if related or not: https://sentry.sentry.io/issues/4047339827/

### Product Area

Settings - Integrations

**Comment by nhsiehgit** [comment]
Hey @rodolfoBee 

This is unfortunately very confusing and misleading.

Can you try going through the steps [here to set up Azure Active Directory SSO](https://docs.sentry.io/product/accounts/sso/azure-sso/?original_referrer=https%3A%2F%2Fwww.google.com%2F) instead?

The Azure DevOps integration i believe not for SSO and only for app integrations

**Comment by nhsiehgit** [comment]
Ah shoot.

Sorry, NOT the same >_<

SSO is different than the social login link.

one moment. let me continue digging

**Comment by vivamau** [comment]
Sorry here, wondering if you have any updates on this issue. It is blocking us

**Comment by a1i3n37** [comment]
This issue is blocking me as well. =/
Tried to uninstall my Azure DevOps integration because it stopped working recently, and now I am stuck because I cannot install it again.

**Comment by yoyoys** [comment]
I have same issue

**Comment by Dhrumil-Sentry** [comment]
We're currently having certain problems with our Azure Devops Integrations- We've updated our [status](https://status.sentry.io/) page to reflect this too

https://github.com/getsentry/sentry/issues/50221 is a related issue. We're working towards resolving this in the next few days

**Comment by Dhrumil-Sentry** [comment]
We've deployed a fix- Can you please let us know if this is still not working for you 🙏

**Comment by Transheroes** [comment]
I can't still install the integration or extension,

Both ways I have tried from the Sentry side and from Azure Devops side

I get the following message

<img width="588" alt="image" src="https://github.com/getsentry/sentry/assets/133911013/23a7fc03-87a0-44c7-a97c-1ca318b3db59">

I am in Sentry and Azure Devops an organization owner.

**Comment by a1i3n37** [comment]
I was able to integrate my Azure DevOps account into Sentry again, thank you. 
Will keep observing it the next few days, if there are any further issues.

**Comment by rodolfoBee** [comment]
My latest test also worked, was able to add the integration again and create issues from Sentry to Azure.

Marking this as closed, please comment or reach out to support in case you run into any issues and we will take if from there.
