### ISSUE TITLE
Feature Request: Custom Integrations

### ISSUE THREAD

**Issue by JamesMowatt** [getsentry/sentry#5004]
It would be great if you could integrate custom issue trackers just by calling an API with standard formatted data. Letting the person controlling the API customise it to Sentry's call. This could open up more possibilities for cool integrations, if this is possible please give me guidance.

Thanks

**Comment by dcramer** [comment]
it'd be fairly complex to do this but I can envision a world where we allow you to simply specify a maniefest JSON to post to an API service with an expected response and then you can just instrument a middle layer or a simple integration in the issue tracker itself.

**Comment by BYK** [comment]
Now available: https://docs.sentry.io/product/integrations/integration-platform/#internal-integrations
