### ISSUE TITLE
Project Creation Wizard not Loading

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#50054]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. create project
2. select FastAPI
3. next

### Expected Result

Onboarding wizard for FastAPI

### Actual Result

![image](https://github.com/getsentry/sentry/assets/47563310/af052f14-fecd-4028-b569-012355f12e83)

### Product Area

Projects

**Comment by smeubank** [comment]
![image](https://github.com/getsentry/sentry/assets/47563310/531d126d-a1d1-449e-a7fa-96348db9bb9e)

**Comment by ale-cota** [comment]
@smeubank this should be working again now.
