### ISSUE TITLE
Improvements on automatic JIRA issue creation

### ISSUE THREAD

**Issue by sul4bh** [getsentry/sentry#5008]
I would like to discuss an idea regarding improvement of automatic JIRA issue creation.

When Sentry automatically creates an issue in JIRA, I would like to specify additional fields and their values. We already have "Default Priority" and "Default Issue Type". We could have an interface that allows us to select a field from a dropdown and provide a default value for it. The interface would allow us to do this repeatedly(similar to what we have for Alert Rules).

I am ready to help with implementing this feature if you guys think it can be useful. What do you say?

**Comment by dcramer** [comment]
Theres a lot of complexity with this -- we wanted to remove the automatic issue creation just because it doesn't make a lot of sense. The major issues are:

1. What you highlighted above
2. It should be rule driven
2a. The rule system doesn't support crazy configurations like this

**Comment by sul4bh** [comment]
Are you planning to axe automatic issue creation feature? That doesn't sound like a good idea to me. I guess a lot of people use this feature.

We might start with something small initially? Like, ability to add at least one field of our choice?

**Comment by dcramer** [comment]
@sul4bh I think it can be a useful feature, I just think the current implementation isn't a great experience and we haven't really had time to do anything about it (mostly because its actually a lot of work to do what I suggested above)

**Comment by sul4bh** [comment]
I understand.

**Comment by sul4bh** [comment]
I got around this limitation by not using the default JIRA Integration plugin. Instead I used Sentry webhooks to send events to an AWS lambda function that takes care of creating JIRA issues.
