### ISSUE TITLE
Path seems to be duplicated when looking up sourcemaps

### ISSUE THREAD

**Issue by janpaul123** [getsentry/sentry#5010]
Sourcemaps seem to not be working for us — the base path is duplicated: instead of "/client" it becomes "/client/client". Unclear why, the paths all seem to look fine, both in the source file and in the uploaded artefacts. Attached are some screenshots.

Also important to note is that this used to work fine, and seems to have stopped working early January. We didn't change anything in our infrastructure.

We're using hosted Sentry, version currently reports as 8.14.0.dev0.

1. This is the source file, paths all look sane:
<img width="640" alt="screen shot 2017-02-28 at 10 13 55" src="https://cloud.githubusercontent.com/assets/177461/23442370/d26daa52-fddc-11e6-926d-e4de05ea0891.png">

2. This is the error stack trace, path also looks good:
<img width="489" alt="screen shot 2017-02-28 at 10 27 03" src="https://cloud.githubusercontent.com/assets/177461/23442377/e2b6853c-fddc-11e6-9386-acd0c5e57992.png">

3. Here are the uploaded artefacts, also with correct paths:
<img width="1170" alt="screen shot 2017-02-28 at 10 13 24" src="https://cloud.githubusercontent.com/assets/177461/23442398/f90ae2e2-fddc-11e6-9b82-4e5430ed0c8d.png">

4. But then it shows this error at the top, with the "/client/client" thing happening:
<img width="803" alt="screen shot 2017-02-28 at 10 13 32" src="https://cloud.githubusercontent.com/assets/177461/23442464/69c07af6-fddd-11e6-90af-e4f44baff204.png">

Any idea what's happening here? A bug in Sentry?

**Comment by dcramer** [comment]
it sounds like the source is being registered with two prefixes. You can view the raw JSON of the event to verify this. What we show by default in the filename bit is an idealized relative path. If you do find information that suggest its actually Sentry causing the duplicate prefix we can dig into it more, but we haven't heard of this issue before.

**Comment by janpaul123** [comment]
This is the JSON from the request that registers a typical event, is that what you mean?

<img width="793" alt="screen shot 2017-03-01 at 17 07 24" src="https://cloud.githubusercontent.com/assets/177461/23488491/cf949776-fea1-11e6-8562-34bd3d991642.png">

I don't see the double "/client/client" anywhere in that JSON…

**Comment by dcramer** [comment]
@janpaul123 can you confirm that the filename matching the error is correct in the raw JSON (in frames)?

**Comment by janpaul123** [comment]
Yeah, they seem to match:

<img width="605" alt="screen shot 2017-03-01 at 21 32 25" src="https://cloud.githubusercontent.com/assets/177461/23494286/ad755886-fec6-11e6-96ae-4d80d091abc9.png">

<img width="1299" alt="screen shot 2017-03-01 at 21 32 00" src="https://cloud.githubusercontent.com/assets/177461/23494284/a7863396-fec6-11e6-850b-f7dcd800ced0.png">

<img width="526" alt="screen shot 2017-03-01 at 21 34 58" src="https://cloud.githubusercontent.com/assets/177461/23494322/fddbf8fc-fec6-11e6-8055-85c55d3b2c9a.png">

**Comment by janpaul123** [comment]
Oh and in this case the error itself:

<img width="853" alt="screen shot 2017-03-01 at 21 33 30" src="https://cloud.githubusercontent.com/assets/177461/23494394/83a61dfa-fec7-11e6-82e4-a4b5e36da8db.png">

Thanks for investigating!!

**Comment by janpaul123** [comment]
Stack traces seem to be working for us again! Unclear how or why. Anyway, thanks! 😄
