### ISSUE TITLE
Event selection bug

### ISSUE THREAD

**Issue by sul4bh** [getsentry/sentry#5013]
- The version of Sentry you're using: **Hosted on sentry.io Sentry 8.14.0.dev0**

In the events list page, the select all checkbox bring up a message saying "25 issues on this page selected. Select all issues matching this search query." but clicking on "select all issues" does not work as expected. See the attached video.

https://dl.dropboxusercontent.com/u/91772376/select_all.mov

**Comment by webmozart** [comment]
I'm encountering the same problem.

**Comment by MaxBittker** [comment]
i believe this is fixed now
