### ISSUE TITLE
Microsoft Teams Integration Problem

### ISSUE THREAD

**Issue by marensas** [getsentry/sentry#50133]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Teams app:

1. Right click on the team
2. Click Manage team
3. Click Apps tab
4. Select More apps
5. Type in search: Sentry
6. Press Add button
7. Press down arrow and Add to to team button
8. Select custom channel
9. Press Set up Bot

### Expected Result

I expect setup process.

### Actual Result

Will continue reproduce :

10. Getting "Sentry" link in the text input
11. Pressing enter
12. Getting text:

> Sentry for Microsoft Teams does not support any commands in channels, only in direct messages. To unlink your Microsoft Teams identity from your Sentry account message the personal bot.
> Want to learn more about configuring alerts in Sentry? Check out our documentation.

### Product Area

Settings - Integrations

**Comment by marensas** [comment]
Strange thing: I saw a setup process message in the "General" channel which I wasn't selected at all.

**Comment by scttcper** [comment]
make sure you click "add to team" and not add https://docs.sentry.io/product/integrations/notification-incidents/msteams/#install

<img width="836" alt="image" src="https://github.com/getsentry/sentry/assets/1400464/b08acd7b-fdda-4b71-902d-67a86c5a7587">

**Comment by marensas** [comment]
> make sure you click "add to team" and not add https://docs.sentry.io/product/integrations/notification-incidents/msteams/#install
> 
> 
> 
> <img width="836" alt="image" src="https://github.com/getsentry/sentry/assets/1400464/b08acd7b-fdda-4b71-902d-67a86c5a7587">
> 
> 

I was aware of that and didn't clicked it. Also Sentry app was not installed before to the team/channel.
