### ISSUE TITLE
Update alert rule models to better reflect how they are used

### ISSUE THREAD

**Issue by spalmurray** [getsentry/sentry#50131]
**Check out [this doc](https://www.notion.so/sentry/Metric-Alerts-Overview-fdd5f99e18f2418c9b96954e0a74d690) for an overview of Metric Alerts. We will want to update this document to reflect any changes made here.**

Upon looking into #49252, we discovered an inconsistency between how metric alert notifications are implemented and how we intend them to work. There's a summary of the problem and a couple potential solutions in [this Notion doc](https://www.notion.so/sentry/Metric-alert-notifications-888ca0b0d1784e80a9f6181514472303).

We ended up implementing a duct tape fix to have the external behavior match what we expect, but in the code things are a bit hacky still. This ticket is for implementing the 'nicer' solution.

Current data model: 
- [`AlertRuleTriggerAction`](https://github.com/getsentry/sentry/blob/83a905ad29afbc9775402c09f680728d2a3f09b9/src/sentry/incidents/models.py#L532) contains the information for a notification (think Slack channel, email address, etc). Each action has an `AlertRuleTrigger` foreign key.
- [`AlertRuleTrigger`](https://github.com/getsentry/sentry/blob/83a905ad29afbc9775402c09f680728d2a3f09b9/src/sentry/incidents/models.py#L496) describes a 'warning' or 'critical' trigger, has the alert/resolve threshold info, etc. Each trigger has an `AlertRule` foreign key.
- [`AlertRule`](https://github.com/getsentry/sentry/blob/83a905ad29afbc9775402c09f680728d2a3f09b9/src/sentry/incidents/models.py#L361) is pretty self explanatory.

We have updated alert rule notifications to reflect the status of an `AlertRule`, not the status of an `AlertRuleTrigger`. Currently, each `AlertRuleTriggerAction` still belongs to an `AlertRuleTrigger`, so in order to collect all of the actions for a given alert rule, we currently have to dig through all the triggers.

Proposed data model:
- Leave `AlertRule` and `AlertRuleTrigger` as they are.
- Rename `AlertRuleTriggerAction` to `AlertRuleAction`
- Have `AlertRule` as a foreign key in `AlertRuleAction` instead of `AlertRuleTrigger`
- Add field for the 'log level' of this action to `AlertRuleAction` (i.e. is this a warning action or a critical action?)

This change will require some adjustment of the existing logic inside the `src/sentry/incidents` directory, but external behavior shouldn't be impacted. This should just allow us to align the logic with the behavior we're after.

**Comment by ceorourke** [comment]
Addressed by ACI
