### ISSUE TITLE
Update Issue Details troubleshooting logic

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#50138]
**Problem:** In Q1, the Issues team developed an [in-product debugging system for source maps](https://www.notion.so/sentry/In-App-Source-Map-Debugging-63e1f437d45445149abf7920510fed50), with the goal of both raising awareness about the need to configure source maps upload, as well as helping fix broken/incomplete setups. When a particular frame doesn't have source maps, the user sees a CTA that shows a specific error message (e.g. release missing, path mismatch, etc.) and gets a link to the specific troubleshooting step in the docs. This logic is however all based on the previous workflow using releases.

**Solution:** Update the logic to support the new approach with artifact bundles and the new potential troubleshooting steps.
A draft user flow mapping can be found [here](https://www.figma.com/file/Mplyw96iZEnsoTWwQZDcwb/Exploration%3A-Issue-Experience-%2F-Artifact-Bundles?type=whiteboard&node-id=0-1&t=cLpLzUtvj7I0Fg9L-0). It needs to be verified and then the appropriate updates should be made to the Explain endpoint and the Issue details UI.

**Comment by smeubank** [comment]
@scefali is this being tracked somewhere? 

@kamilogorek was there anything done in CLI explain that accounts for the changes by debugId? Guessing some logic around checking for release is no longer relevant

**Comment by kamilogorek** [comment]
> @kamilogorek was there anything done in CLI explain that accounts for the changes by debugId? 

No, not yet. See https://github.com/getsentry/sentry-cli/issues/1601 for tracking this issue. We want to reuse same endpoint as `/sourcemap-debug` does
