### ISSUE TITLE
Alert rule via webhook

### ISSUE THREAD

**Issue by lcorn** [getsentry/sentry#5016]
I want to receive custom alerts (regressions, first event, too many events etc.) via webhook (not only emails). I created regression rule and triggered appropriate alert. I have tested webhooks and json have no sign that alert is regression. Regression's json is the same as json which we get from first event and any other alert rule. Visually they are the same and their structure is similar.
So, you don't send the rule name through the webhook. 
Did i miss something, or this feature is not implemented yet?

**Comment by dcramer** [comment]
@LdmlD its not yet something that we've implemented. I do agree it'd be useful to be able to receive activity-style events via webhooks. You *can* create rules around things like first event and regressions and send webhooks, but you cant do many other things.

**Comment by jdrydn** [comment]
@lcorn What alert rule did you use? I'm trying to setup an alert for when an issue is marked as "regression" yet I can only add alerts for "_first seen_", and "_seen_" (which is too often).

**Comment by nauxliu** [comment]
Any news? I would love to see this.

**Comment by BYK** [comment]
They have arrived: https://docs.sentry.io/product/integrations/integration-platform/webhooks/
