### ISSUE TITLE
Update internal and external docs

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#50228]
Internal docs: https://www.notion.so/sentry/Currently-Supported-Processed-Event-Data-e29f2d6b6d7749eaaaafe412f2b46964
External docs: [here](https://docs.sentry.io/product/alerts/create-alerts/metric-alert-config/#tags--properties), but there may be other places.

**Comment by RaduW** [comment]
Pushed a very small PR (tagged @ale-cota for review).
