### ISSUE TITLE
Unable to login via "Sign in with Azure DevOps"

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#50221]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When trying to login using the "Sign in with Azure DevOps" option users are met with a 403 forbidden error after authenticating in Azure. 

Steps to reproduce:
1. Go to https://sentry.io/auth/login/
2. Try to login with "Sign in with Azure DevOps"

Internal tracker: https://getsentry.atlassian.net/browse/INC-398

The Sentry team is aware of the issue and currently working on it.

### Expected Result

Login with no errors.

### Actual Result

403 Forbidden error

### Product Area

Sign In

**Comment by Dhrumil-Sentry** [comment]
The team is actively investigating this issue

**Comment by rvelasquez** [comment]
Reported this issue to Sentry support yesterday.

**Comment by scefali** [comment]
We have determined the problem but we need to get ahold of Azure DevOps support for assistance. Hoping to get it resolved in the next few days.

**Comment by Dhrumil-Sentry** [comment]
We've deployed a fix- please let us know if this is still not working

**Comment by rodolfoBee** [comment]
The issue is no longer reproducible on my side.

**Comment by rvelasquez** [comment]
Same, all is working.  Thanks!

**Comment by hubertdeng123** [comment]
closing this since it appears to be fixed now
