### ISSUE TITLE
Spring Boot Getting Started guide improvements

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#50226]
### Problem Statement

When creating a Java project (vanilla, kotlin, or frameworks)

- displays Maven and Gradle users need to decide
- displays Kotlin and Java user needs to decide

### Proposed Solution

Design: https://www.figma.com/file/wROselpEmYKvGs38quXLbR/Exploration%3A-Wizard-Settings?type=design&mode=design&t=E0210JsYc4cA2AdO-0
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/56237
- [ ] https://github.com/getsentry/sentry/issues/56238
```

**Comment by ale-cota** [comment]
Final designs ready: https://www.figma.com/file/wROselpEmYKvGs38quXLbR/Exploration%3A-Wizard-Settings?type=design&node-id=56-903&mode=design&t=rGYDbcj1puzWxkkw-0
