### ISSUE TITLE
Java Modal for Project Selection

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#50224]
### Problem Statement

When Creating a Java project users might miss that they should use a framework specific SDK. Today they are sent on a generic flow

### Solution Brainstorm

Add the modal framework selection window same as Node, Python, and JS Browser

### Product Area

Projects

**Comment by bruno-garcia** [comment]
> @smeubank could you please add the list of frameworks in the order we should display them in the modal? Thank you!

![image](https://github.com/getsentry/sentry/assets/1633368/795c4396-8cad-4178-9b2f-5b60c2041b9b)


I propose this order:
SB, Spring, Servlet, logback, log4j2, java.util.logging, regular Java

But we only have these wizards:

![image](https://github.com/getsentry/sentry/assets/1633368/e85f13ca-0c69-4ab6-bf0d-7a59753552e8)

So how about:
SB, Spring, logback, log4j2, regular Java

**Comment by Jesse-Box** [comment]
@matejminar @priscilawebdev 

Below is the SVG art required to complete this modal
![art-java-frameworks](https://github.com/getsentry/sentry/assets/6508377/a75722eb-106c-431d-8613-419d146cd184)
