### ISSUE TITLE
Raven Sentry for Rails `user_id` hangs server

### ISSUE THREAD

**Issue by untoldone** [getsentry/sentry#5025]
Sentry Server Version: 8.12 running in Docker with the plugins:
* sentry-plugins
* https://github.com/getsentry/sentry-auth-github/archive/master.zip

sentry-raven ruby gem -- 2.3.1

In my application controller I have the code:

```
Raven.user_context(user_id: current_user.id, email: current_user.email ) if current_user
```

I should have had `id` instead of `user_id` but this locked up the sentry server causing the all other sentry clients to have errors like:

```
E, [2017-03-02T22:30:49.597704 #140] ERROR -- sentry: ** [Raven] Unable to record event with remote Sentry server (Raven::Error - execution expired):
/usr/local/bundle/gems/sentry-raven-2.3.1/lib/raven/transports/http.rb:35:in `rescue in send_event'
/usr/local/bundle/gems/sentry-raven-2.3.1/lib/raven/transports/http.rb:18:in `send_event'
/usr/local/bundle/gems/sentry-raven-2.3.1/lib/raven/client.rb:40:in `send_event'
/usr/local/bundle/gems/sentry-raven-2.3.1/lib/raven/instance.rb:81:in `send_event'
/usr/local/bundle/gems/sentry-raven-2.3.1/lib/raven/instance.rb:126:in `capture_type'
/usr/local/bundle/gems/sentry-raven-2.3.1/lib/raven/instance.rb:97:in `rescue in capture'
/usr/local/bundle/gems/sentry-raven-2.3.1/lib/raven/instance.rb:92:in `capture'
/usr/local/lib/ruby/2.3.0/forwardable.rb:189:in `capture'
(irb):1:in `irb_binding'
/usr/local/lib/ruby/2.3.0/irb/workspace.rb:87:in `eval'
/usr/local/lib/ruby/2.3.0/irb/workspace.rb:87:in `evaluate'
```

**Comment by dcramer** [comment]
This needs more information, and sounds like a configuration issue.

**Comment by untoldone** [comment]
@dcramer Please reopen -- i posted before finished writing by accident

**Comment by untoldone** [comment]
To add more context, I see nothing that looks abnormal in terms of logging on the sentry docker container's log, but it no longer accepts events until I restart the server. Removing `user_id` from the user context fixes the problem.

**Comment by dcramer** [comment]
Unfortunately, this is still seemingly a misconfiguration issue and we dont provide support here. You should confirm theres no network issues and that all services are up.

**Comment by untoldone** [comment]
@dcramer Thanks for taking a look.

I wish I could use your SaaS offering, but we need HIPAA compliance and might have PHI in our exceptions. I'll continue to investigate on my own and let you know if I find consistent way to reproduce / if I find evidence of something beyond configuration issues.

**Comment by dcramer** [comment]
@untoldone sounds good -- if you do identify something feel free to update us here.

(aside, we're hoping to have HIPAA in place in the next couple of months)
