### ISSUE TITLE
Billing role missing in the Filter under Settings --> Members

### ISSUE THREAD

**Issue by rohitkataria-sentryio** [getsentry/sentry#50264]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Click Settings 
Click Members
Click Filter and we do not see Billing

### Expected Result

Billing is a supported role as per docs and used to be available in that Filter. 

### Actual Result

Billing is a supported role as per docs and used to be available in that Filter. 
<img width="452" alt="Screenshot 2023-06-02 at 11 00 55 AM" src="https://github.com/getsentry/sentry/assets/66752128/4193c54b-a13e-4bc8-b234-add2395f8230">
<img width="529" alt="Screenshot 2023-06-02 at 11 00 27 AM" src="https://github.com/getsentry/sentry/assets/66752128/e1b652a4-8435-479d-92f7-0742fdeeda96">

### Product Area

Settings - Members

**Comment by schew2381** [comment]
I was unable to reproduce this bug in sentry or my test-org
<img width="585" alt="Screenshot 2023-06-23 at 11 14 49 AM" src="https://github.com/getsentry/sentry/assets/67301797/bc7eca59-450e-409c-b19a-3c39de84c63f">

<img width="557" alt="Screenshot 2023-06-23 at 11 16 06 AM" src="https://github.com/getsentry/sentry/assets/67301797/dfb793c0-81a5-4333-9b3a-dc71eb7fd850">

**Comment by rohitkataria-sentryio** [comment]
@schew2381   - did you get a chance to check the same in customers' orgs ?  The screenshot shared while opening this issue were taken from customers' org  and even now, I can still see the same issue in them. Though I agree the problem is not present in the Sentry Org or testorg-az

**Comment by souredoutlook** [comment]
@rohitkataria-sentryio I believe this may stem from viewing an organization as a Super User. If you look at an org where you are a normal member of the org, without a super user session, this option is present.

**Comment by hubertdeng123** [comment]
@schew2381 is this enough to go off of for now? Going to move this back to `Waiting for: Product Owner`

**Comment by sentaur-athena** [comment]
[rohitkataria-sentryio](https://github.com/rohitkataria-sentryio) can customer experience or are you experiencing as super user? Because if you experience as super use that's expected.

**Comment by rohitkataria-sentryio** [comment]
@sentaur-athena - I do not know if a customer has experienced this but I can ask next time on a call. 

If its expected that as a super user then we ideally need a list of all the discrepancies a super user observes because otherwise it distances  Support/Solutions-SalesEngineers/Customer Success from how their customers use the product and can easily cause professional embarrassment and not knowing-what-you-are-talking about situation. 

Also, I am not sure if this was always the case so since its a recent change - for the superuser - it'll be good to know the motivation behind it.

I appreciate the cycles spent on this case so we may close it since both of my asks above are rather broad and I am not sure who the owner there is.
