### ISSUE TITLE
Mute metric alerts

### ISSUE THREAD

**Issue by pmatev** [getsentry/sentry#50276]
### Problem Statement

Currently it is only possible to mute "Issue Alerts" but it is not possible to do the same on "Metric Alerts". This is a key functionality for on-call teams in order to prevent alert spam during an active incident.

### Solution Brainstorm

The basic request is for the ability to manually mute/unmute the alert notifications from the UI. A nice to have addition would be to add the ability to mute alerts only for 1 hour, 4 hours, 24 hours etc.

### Product Area

Alerts

**Comment by rachrwang** [comment]
Hi @pmatev - Sentry now supports the ability to mute metric alerts. Have you had a chance to try it out yet? Let us know if you have any questions or feedback!

**Comment by pmatev** [comment]
Thanks @rachrwang! Haven't had a chance to try it out yet, but will report back.
