### ISSUE TITLE
Resolve signatures for Metric Alerts are broken for JavaScript

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#50272]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Our code for verifying signatures for JavaScript requests doesn’t seem to be working for metric alerts.

Please see this [Jira ticket](https://getsentry.atlassian.net/browse/API-2862) for more details

### Expected Result

Users should be able to verify the Metric alert signature in JS too

### Actual Result

N/A

### Product Area

Settings - Integrations

**Comment by scefali** [comment]
@Dhrumil-Sentry Has the user seen this issue yet? https://github.com/getsentry/sentry/issues/38443

**Comment by mgm-sentry** [comment]
> @Dhrumil-Sentry Has the user seen this issue yet? #38443

This is for the customer Tipalti. I can share this with them.
