### ISSUE TITLE
Azure DevOps Integration Problem

### ISSUE THREAD

**Issue by iteufel** [getsentry/sentry#50291]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Remove Existing DevOps Repo
2. Click Add Installation

### Expected Result

The Repo will be added.

### Actual Result

Internal Server Error.
![Bildschirmfoto 2023-06-05 um 13 20 30](https://github.com/getsentry/sentry/assets/4130931/080f2074-4a50-40ca-aa10-131564f3a7ac)

### Product Area

Settings - Repositories

### Link

https://metacarp-gmbh.sentry.io/settings/integrations/vsts/

**Comment by Dhrumil-Sentry** [comment]
We're currently having certain problems with our Azure Devops Integrations- We've updated our [status](https://status.sentry.io/) page to reflect this too

[#50221](https://github.com/getsentry/sentry/issues/50221) is a related issue. We're working towards resolving this in the next few days

**Comment by Dhrumil-Sentry** [comment]
Hi @iteufel , We've deployed a fix- Can you please let us know if this is working for you now

**Comment by GabeVillalobos** [comment]
Closing this as there hasn't been any activity in over a year.
