### ISSUE TITLE
Jira Server integration issue creation failure

### ISSUE THREAD

**Issue by Sayorus** [getsentry/sentry#50303]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Configure jira server integration
2. Open any issue in sentry
3. Try to create Jira Issue via intagration

### Expected Result

Open issue creation form

### Actual Result

Popup with crash message. 
In internal project found next issue:

**HTTPError: 400 Client Error:  for url: https://myawsomedomain.com/rest/api/2/issue/createmeta/11102/issuetypes**

### Product Area

Issues

### Version

22.12.0

**Comment by ceorourke** [comment]
Hi @Sayorus - Atlassian [removed the createmeta endpoint](https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html) so we updated our code as well. You'll want to update your Jira Server version to 8.4 or higher to continue using the integration.

**Comment by Sayorus** [comment]
@brianthi setup was done correctly and error throwing on every try 

@ceorourke  Our Jira version is v9.6.0
