### ISSUE TITLE
Loading a replay at a specific timestamp isn't working

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#50312]
Tried to load up https://sentry.sentry.io/replays/javascript:74c092d6ac3d4f14af7a778ac6104bc2/?t=31 with `?t=31` and it's starting at 0:00 instead

**Comment by ryan953** [comment]
see also https://github.com/getsentry/sentry/issues/50653

**Comment by bruno-garcia** [comment]
Worth noting that once you start the playback, it jumps to the timestamp specified in the query string.
