### ISSUE TITLE
Merge `replay.render-issues-detail-count` fields event into the issues pageview event

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#50348]
Following up on https://github.com/getsentry/sentry/pull/48797

We should merge this `replay.render-issues-detail-count` event with an existing one. It's basically a pageview thing so we can instead add the `count` field onto something that exists (with a good name obvs).

**Comment by ryan953** [comment]
@jas-kas Do we use this new metric "Render Issues Detail Replay Count" anywhere?

**Comment by jas-kas** [comment]
@ryan953 Yes, in the Q1 Initiative Replay Dashboard (linked in the bookmarks of the #team-replay channel)
