### ISSUE TITLE
Issue titles for issue platform issues aren't searchable

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#50345]
I think this is because we're not including them in `search_message` here:

https://github.com/getsentry/sentry/blob/ccfb37212102945df5f35e8f55fe38891b70036b/src/sentry/eventstore/models.py#L541-L569

We should write a test that searches on the title for a platform issue and figure out how to make it pass

**Comment by cmanallen** [comment]
@wedamija Replays also suffers from this but on more fields than just the title.  For example our events have a tag `replayId` which is not searchable.  See: https://sentry.sentry.io/issues/?project=11276&query=is%3Aunresolved+issue.category%3Areplay+replayId%3A0779b2f063804a3489b8d6836fc5f8c6&referrer=issue-list&statsPeriod=14d&stream_index=0

**Comment by scefali** [comment]
It looks like we don't have the search text column in ClickHouse yet, we need to write to it first

**Comment by wedamija** [comment]
https://github.com/getsentry/snuba/blob/c5f069eae10e256633825c2d56b44501412c67fe/snuba/datasets/configuration/events/entities/events.yaml#L84

Basically we should probably have this column in the search issues dataset in clickhouse so we can do general searches.
