### ISSUE TITLE
Minor change to escalating issues text

### ISSUE THREAD

**Issue by therealarkin** [getsentry/sentry#50351]
![Image](https://github.com/getsentry/sentry/assets/115136522/9624679f-61bb-4c3f-a840-37259195bf9f)

Current: "Was this issue high priority for you?"
New: "Has this issue become more important and worth your attention?"

Current hover: "We're collecting feedback on a new feature - Escalating Issues."
New hover: "Help us improve our issue escalation algorithm by telling us if you agree that this issue should’ve been escalated."

Now I know this hasn't been used much so far, but I want to give this another chance... Hopefully this is very easy

**Comment by scttcper** [comment]
I don't think the tooltip is very helpful at the moment we should put one of those `(i)` hover icons so they know they can hover. I wish the wording mentioned either escalating or archive so they knew we were directly asking for feedback about that feature.

**Comment by therealarkin** [comment]
I don't mind adding an "i" icon.

Re: Wording itself - i don't want to bikeshed too much because I don't know if it will get used. My reasoning was not to use "escalating" or "archive" in the question itself because the essence of what we want to capture is if this issue has become more important to you. If we detect escalation, and it is still not important, maybe our threshold should be different (and I expect that over time we will have different thresholds for different types of issues but need to crawl before we walk)

That being said, I don't feel strongly, so if you have something you feel strongly about, go for it!

**Comment by brianthi** [comment]
I prefer the (i) icon over the hover over as well.
