### ISSUE TITLE
captureMessage shadowing real error

### ISSUE THREAD

**Issue by mblayman** [getsentry/sentry#5037]
Hi,

We use hosted Sentry. Today, I upgraded our JS client to use 3.12.0. When I'm looking at the Sentry errors that are coming in, it appears that `captureMessage` is swallowing the error message that we hope to see and raising its own exception. The report is super weird because there is a catch call immediately surrounding where the error is thrown. I'm not sure why that throw is able to propagate all the way through.

https://sentry.io/storybird/javascript/issues/229801162/ is an example of it in action. Here is the stacktrace reported by Sentry.

```
at e.captureMessage(raven.js:488:22)
at captureMessage(raven.js:435:24)
at captureException(raven.js:387:21)
```

```javascript
  <script src="https://cdn.ravenjs.com/3.12.0/raven.min.js"></script>
  <script>
      Raven.config('<redacted>', {
        shouldSendCallback: function(data) {
          if (!window.hasSentSentryError) {
            window.hasSentSentryError = true;
            return true;
          }
          return false;
        },
        whitelistUrls: [/storybird\.com/],
        ignoreUrls: [
          // Ignores urls containing in "/affs?" a common extension for spyware.
          /\/\/(\w|\.)*\/affs\?/
        ]
      }).install();
  </script>
```

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
