### ISSUE TITLE
Track assignment and resolution rate for escalating vs unignored issues

### ISSUE THREAD

**Issue by snigdhas** [getsentry/sentry#50393]
The algorithm is more useful than manual snoozing

For projects that used “Archive” at least once and Ignore until (user-defined escalation) at least once:

Compare:
Assignment and resolution rates of issues that have escalated due to algorithm vs user defined escalation

**Comment by scttcper** [comment]
Example of group that was escalating from user defined https://sentry.sentry.io/issues/2543393483/activity/?project=1 and then resolved.

Count how many issues went from ignored -> unignored and archived -> escalating and then count how many had an action taken on them

**Comment by scttcper** [comment]
Progress? https://redash.getsentry.net/queries/4274/source
