### ISSUE TITLE
Auto-assign ownership rule by tag value

### ISSUE THREAD

**Issue by ran-mochary-gong** [getsentry/sentry#50397]
### Problem Statement

We auto-assign issues to teams using tags in ownership rules.
However, the team name has to be hard-coded in the ownership rule.
For example: 
tags.g-module:ModuleA #team-a

I would like to use the tag value as the team to assign to.
For example:
tags.g-team:#team-a #team-a
tags.g-team:#team-b #team-b
Your support confirmed these rules should work.

This still requires writing hard-coded team names, duplicating this rule for all teams.
It would be better if I could write a rule that uses the tag value.
Something like:
tags.g-team:$TAG_VALUE $TAG_VALUE

### Product Area

Issues

**Comment by brianthi** [comment]
Hi @ran-mochary-gong, thanks for writing in with the suggestion. Unfortunately this isn't a change we're likely to make in the product. I'll close this issue for now, and if we put more time towards this area of the product, I'll consider your request and see how it may fit in to our roadmap.
