### ISSUE TITLE
Jira Integration Problem

### ISSUE THREAD

**Issue by xavier-ferro** [getsentry/sentry#50405]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I can't configure my Jira instance once the app is installed

### Expected Result

Being able to get my Jira and Sentry instances work together

### Actual Result

![Screenshot 2023-06-06 at 09 45 59](https://github.com/getsentry/sentry/assets/130777037/8754c4e1-db59-4c0a-b1c4-cb7d468411d2)

Error on Jira instance

### Product Area

Other

**Comment by masinette** [comment]
Hi @xavier-ferro. Can you write in to Support to have a look?

**Comment by Dhrumil-Sentry** [comment]
Closing this issue for now- @masinette  Please let us know if we need to reopen it later
