### ISSUE TITLE
Create members via API endpoint using internal integration with admin permissions -> Please reopen #46818

### ISSUE THREAD

**Issue by fmartinou** [getsentry/sentry#50402]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Hi, can you please reopen https://github.com/getsentry/sentry/issues/46818?
Because this issue has not been fixed and it's still failing.

Thank you!

### Expected Result

See https://github.com/getsentry/sentry/issues/46818

### Actual Result

See https://github.com/getsentry/sentry/issues/46818

### Product Area

Settings - Auth

**Comment by Dhrumil-Sentry** [comment]
Please track this issue via the original issue https://github.com/getsentry/sentry/issues/46818
