### ISSUE TITLE
Stack trace platform icon shows `other` instead of TypeScript

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#50435]
When two stack traces show up, only one of them displays the correct platform icon:

![image](https://github.com/getsentry/sentry/assets/1633368/dd22c779-9395-47a3-a8a8-d9f4cdad6820)

Repro: https://sentry.sentry.io/issues/4207594145/events/e1dc6538051d433f971adddcab0f3fac/

Relevant code: 
 https://github.com/getsentry/sentry/blob/7ca0ab21bff692c8282e19c19718b952755efa3e/static/app/utils/fileExtension.tsx#L3

**Comment by malwilley** [comment]
Fixed in https://github.com/getsentry/sentry/pull/61551
