### ISSUE TITLE
Customer feedback: Timestamp display on Sentry Web UI

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#50473]
### Problem Statement

We use Sentry in our project for tracking errors, there is a lot to like here since it makes it easy for us to track the related issues and group them automatically.

One major pain point with the UI is the very poor handling of timestamps. On the event list the timestamps are barely visible as they are hidden into a column narrower than the timestamp. Plus the timestamp display format choice is very poor for troubleshooting. For example a timestamp like "Jun 3, 4:38 AM" is very bad and makes our lives much harder. Would it be possible to use proper ISO timestamp format or make it available for easy copying? In this case I have to manually write "2023-06-03 04:38:00.000Z", manually, every time, because the timestamp on the Sentry UI is so bad that it cannot be used. On the all events page this is even worse, it makes it much harder to troubleshoot and debug problems when we don't know when they happen and it is such a pain to get these timestamps from Sentry.

Timestamp in the event details page:
![image](https://github.com/getsentry/sentry/assets/44410/be79c939-ff7a-4831-b90c-3045ea4e5030)

All Events page Timestamp column:
![image](https://github.com/getsentry/sentry/assets/44410/a69b2214-1e82-49da-abe8-95481a96710f)

Could you please make some improvements on this?

### Solution Brainstorm

I propose two suggestions:

1. On the all events page, make the timestamp column the first and make it use ISO8061 format, and make it available to copy the full timestmap (up to milliseconds in ISO8061 format in UTC timezone) for any event in
the listing.

2. On an even page, allow to copy the ISO8601 UTC timestamp of the event just like you have a button for copying the event ID.

These improvements would really help improve the experience with Sentry. If this is something you don't want to change for all users, it would be great if you added a new preference for users to turn this on who prefers proper timestamps.

Because seeing an even in Sentry is not helpful if you don't troubleshoot and fix it, but for that you need the timestamp to dig into what happened at the time, for which Sentry falls short.

### Product Area

Other

**Comment by stellaatsentry** [comment]
@armenzg Yes, the screenshots are exactly what the customer was talking about!
