### ISSUE TITLE
Alerts - Team selection will be set to default when searching for alerts

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#50487]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to alerts page
2. Clear teams selection
3. Search for any value
4. You see that Teams are set to my teams/ unassigned again

### Expected Result

Team selection would be maintained when searching

### Actual Result

https://github.com/getsentry/sentry/assets/25929053/92ff292c-5e15-4261-9dd3-a6b1048367aa

### Product Area

Alerts

### Link

any SaaS org

**Comment by rachrwang** [comment]
@Angelodaniel - are you able to repro this? It looks fixed from my end - wanted to confirm before closing this issue out. Thanks!

**Comment by Angelodaniel** [comment]
@rachrwang seems to be fixed on my side as well! Thank you for checking 🙌
