### ISSUE TITLE
[Success Metrics] Connect Replay to BE Errors - Project Icons on Replay Details

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#50500]
**Problem**

We want to be able to track how many orgs are using the Replay BE Errors feature. 

The initial approach was to log pageviews of the Replay Details page, and record whether errors in the replay are part of multiple projects or not. This data is not representative because some orgs send all their data to the same DSN, so they have BE and FE errors in the same project. We should iterate and improve the 'has_backend_error' field.

**Comment by ryan953** [comment]
What we can do it look at the list of errors which are part of the 'replay event' (https://github.com/getsentry/sentry/blob/50e45e7f16a90070346e32defab9c16099a8af96/static/app/views/replays/types.tsx#L41) and compare that to the list of errors that are related to the replay. The list of related errors will include BE and Replay Errors (dead clicks). We could filter out replay-errors to arrive at a list of BE only errors.
