### ISSUE TITLE
Inconsistent source mapping with Release Bundles

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#50518]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Users are reporting that their sourcemaps are no longer working with no changes on their part.  Not including the users who do not want to upgrade, debug Ids are not supported by our NextJs sdk or React Native hermes, so many users still have to use Release Bundles as their method of mapping, but source mapping fails through release bundles often now.

Most issues seem related to having trouble linking the source file to the source map.  Issues are much more common in releases that have many artifacts or long file paths.

Here is a working [example event](https://francisorg.sentry.io/issues/3885650639/?project=4504089864830976&query=is%3Aunresolved&referrer=issue-stream&stream_index=0) from a fresh release.  This is mapping properly.  

<img width="915" alt="Screenshot 2023-06-07 at 4 59 16 PM" src="https://github.com/getsentry/sentry/assets/96670625/c3a55b51-822f-4bf8-a202-d7f539776584">

I then do a new build into the same release with a new set of artifacts and [throw the same error ](https://francisorg.sentry.io/issues/4221810173/?query=is%3Aunresolved&referrer=issue-stream&stream_index=0).  Here only the system frames are being mapped and none of the in app frames.

<img width="925" alt="Screenshot 2023-06-07 at 4 54 09 PM" src="https://github.com/getsentry/sentry/assets/96670625/9cd8ec29-c808-4c61-8238-1097139c7e4f">

Based on what has been reported, even more artifacts and longer file paths can cause the issue to not map at all.

### Expected Result

Mapping behavior should not change for something previously working for some.

### Actual Result

Mapping behavior has changed to not accommodate previously working use cases.

### Product Area

Issues

### Link

https://francisorg.sentry.io/issues/3885650639/?environment=production&project=4504089864830976&query=is%3Aunresolved&referrer=issue-stream&stream_index=2

**Comment by rodolfoBee** [comment]
hey @Fwang36, can you send a link to the repro app and a exact list of steps o reproduce with the commands you use, like:
1. deploy a release
2. send test event
3. deploy the same release
4. send same event again... 
...
...

**Comment by Fwang36** [comment]
I have a repro repo set up [here](https://github.com/Fwang36/nextjs-sourcemap-repro).  This is bested in my org because the mapping usually works the first time and can take a day or two to stop working.  The release value I have set already in the repo is already broken

**Comment by kamilogorek** [comment]
Reassigning to @lforst as for now, this is docs issue that he's working on. Quoting Ricardo:

> What we should clarify to users is that they have to use the dist as a discriminant if they want to have multiple bundles with different contents on the same release. We can’t do much about multiple bundles on the same release, since we will need to merge server side the bundles. Searching for a match doesn’t work either since url can’t alone determine the correct file and symbolication can lead to false positives in case we use the wrong sourcemap :(

**Comment by lforst** [comment]
@kamilogorek I am not working on any docs for this.

Is it possible we have a regression? In the past, uploading multiple times with Next.js to the same release worked totally fine. And I think it should continue working, since some of our users probably depend on this behaviour.

**Comment by chadwhitacre** [comment]
Does it work to move this to a different repo? My understanding is that any regression would be in `symbolic` (yes?), while of course `sentry-docs` is where this should go if we're trying this as a docs issue.

The reason I ask is that I'm trying to [make changes to our `labels.yml`](https://github.com/getsentry/sentry/pull/51719) in this repo and the manual addition of the `Product Area: SDKs - Native` label is [blocking my progress](https://github.com/getsentry/sentry/pull/51719#issuecomment-1610008767). 🐭 The intention is to not have `Product Area: SDKs - *` labels exist in this repo, on the theory that any issue routable to SDK product areas should live in a different repo.

**Comment by lforst** [comment]
@chadwhitacre I think this issue has been triaged since we put it into the Processing-Team's backlog.

I am a bit lost in regard to what our triaging process is right now. Feel free to change the labels as you see fit. I think this issue should remain in Sentry since the logic for looking up artifacts lives here.

**Comment by altechzilla** [comment]
Any updates on this? The only alternative is pushing the source maps to production and then erase them via a build command, which seems risky and kinda unstable.

Haven't been able to get Next.js source maps in Sentry regardless of having the Vercel integration / Github integration set up. Using both appDir and pages.

**Comment by kamilogorek** [comment]
We're still working on it, but cannot give you exact timeline. tl;dr is that our system will currently resolve only first 5 uploaded bundles for a given release, which makes it inconsistent in some case. We're updating everything to work with arbitrary number of files and uploads.

**Comment by shubhamkumbhakar** [comment]
<img width="896" alt="Screenshot 2023-07-27 at 12 02 02" src="https://github.com/getsentry/sentry/assets/42243806/22b0b532-cdd2-4521-bebb-e209408a9f92">
Similar issue is being seen for us as well. Our deployment is handled by Vercel but while an error, we can not see the stack trace due to non existence of Source Maps. Please help with a solution for this.

**Comment by shubhamkumbhakar** [comment]
> Any updates on this? The only alternative is pushing the source maps to production and then erase them via a build command, which seems risky and kinda unstable.
> 
> Haven't been able to get Next.js source maps in Sentry regardless of having the Vercel integration / Github integration set up. Using both appDir and pages.

Can we do this as a temporary fix for now?

**Comment by kamilogorek** [comment]
Unfortunately, you cannot simply delete it like that, but as a workaround, you should be able to change the `release` associated with the upload.

**Comment by Fwang36** [comment]
For nextjs users,

A temporary workaround while a fix is being implemented can be to disable the webpack plugins inside the nextjs sdk and use the `sentry-cli` to inject debug ids instead.

First install `sentry-cli` as a dependency - `npm install @sentry/cli`
 
Then disable the sentryWebpackPlugin by adding this to your sentry object in next.config.js -
 ```
disableClientWebpackPlugin: true,
disableServerWebpackPlugin: true,
```
 
Let nextjs itself create the sourcemaps for you with their source maps option by adding `productionBrowserSourceMaps: true,` to your next.config.js module.exports
 
Then go to your build commands in your package.json and edit it to add `sentry-cli`.  With nextjs defaults this can look like - `next build && sentry-cli sourcemaps inject .next && sentry-cli sourcemaps upload .next`.  If you would like to delete the map files after the upload to Sentry you can try also adding `find ./.next -name \"*.map\" -delete"` to the build command as well.
 
The sourcemaps upload command requires the org, project and auth tokens either as ENV variables or as a [.sentryclirc file](https://docs.sentry.io/product/cli/configuration/#configuration-file).  If you are using the Vercel integration, these should be added already for you.
 
The new source mapping method does not require a release set, so the command I provided above will not set one.  If you wish to have a release set you can change the upload command [to this one here](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/cli/#optional-steps).

**Comment by Swatinem** [comment]
Hi! I see that its been a while.

Since then we have migrated from Release Bundles over to Artifact Bundles on the backend transparently.
Using that newer mechanism should lead to more consistent source mapping results.

The only manual step that is needed is to upload fresh sourcemaps, and things should work afterwards.

Can you try again and see if the problem has now been solved?

**Comment by Fwang36** [comment]
With the move over to Artifact Bundles, the issue is no longer reproducible by me, so I'm closing this issue.  If anyone is still having issues with their source maps, it's likely a separate issue than the problem discussed here.
