### ISSUE TITLE
Public API for Ownership Rules

### ISSUE THREAD

**Issue by tbbream** [getsentry/sentry#50550]
### Problem Statement

Document and make the API public for the ownership rules. This would allow for programmatic addition of rules to help ensure that our sentry are mapped to the correct teams.

### Product Area

Settings

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2050) by [Unito](https://www.unito.io)

**Comment by sandstrom** [comment]
Would also be useful for those that don't want to give Sentry full access to source code, but would want to sync owners with Github.

That way, we could use the CLI (or your HTTP API) to push the latest ownership rules everytime we make a new release.

**Comment by MichaelSun48** [comment]
Hey there @tbbream and @sandstrom 👋

It looks like the endpoint to update project ownership rules was made public about 4 months ago in #57429. You can find more information about how to use this endpoint including the url and parameters [here](https://docs.sentry.io/api/projects/update-ownership-configuration-for-a-project/) in the Sentry docs.

**Comment by sandstrom** [comment]
Thanks @MichaelSun48
