### ISSUE TITLE
Redis Client Connections are not closing.

### ISSUE THREAD

**Issue by srikannanb** [getsentry/sentry#5056]
Hi,

I have configured 16 connections per app server for redis client connection in my application and I have properly handled the return of the connection. But frequently i get running out of connections from some app servers.

When I run the command "client list" in redis. I can see connections from that app server having more idle time and keep on alive.

If I restart my application server and it works fine for few hours and again this issue occurrs.

I can set timeout to solve this issue. But i want to know the root cause for this issue. What could be the possible cause for this problem.

Regards
Srikannan B

**Comment by wridgers** [comment]
I'm also experiencing Sentry not closing Redis connection after having upgraded from 8.10 to 8.14.

**Comment by mattrobenolt** [comment]
Nothing on our end has changed here. This is likely because of networking issues where Redis still thinks there are connections alive when they've been terminated. If you're experiencing this, try setting the `timeout` config documented here: https://redis.io/topics/clients

**Comment by wridgers** [comment]
@mattrobenolt, Okay. I've set `timeout = 300` and now I'm seeing `ConnectionError: Error while writing to socket (host 0): [Errno 32] Broken pipe` (and a few other similar errors) in the interal Sentry project.

**Comment by mattrobenolt** [comment]
We used to run with `timeout 3600`. You don't want it prematurely interrupting connections.

**Comment by wridgers** [comment]
Okay great, I'll give that a go. Many thanks.
