### ISSUE TITLE
Add mute button to alert rule details

### ISSUE THREAD

**Issue by roggenkemper** [getsentry/sentry#50578]
Add the dropdown mute button to the alert rule details page. This will be tailored to what the integrations are on the page since depending on the integration, we want to offer a specific option for muting. For example, for a Slack notification to a channel, "mute for me" doesn't really mean much so we would only offer "mute for everyone' 

Similar PR from V1 of Mute Alerts: https://github.com/getsentry/sentry/issues/46844
Similar PR for changing default mute for Integrations: https://github.com/getsentry/sentry/pull/49573

**Comment by ceorourke** [comment]
Done in https://github.com/getsentry/sentry/pull/50967
