### ISSUE TITLE
Add link to metric alerts email

### ISSUE THREAD

**Issue by roggenkemper** [getsentry/sentry#50577]
From V1 we found that the primary place users learn about muting alerts is from the emails. We added a link to mute the alert automatically to the email which we want to do for metric alerts now. When combined with https://github.com/getsentry/sentry/issues/50576, a user can automatically mute the alert that triggered the email with 1 click. 

Similar PR from V1 of Mute Alerts: https://github.com/getsentry/sentry/pull/47650

**Comment by ceorourke** [comment]
Done in https://github.com/getsentry/sentry/pull/51074
