### ISSUE TITLE
Replay: Hide Slow/dead/rage click breadcrumb 

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#50590]
We've collecting breadcrumbs for Slow Clicks as part of:
* https://github.com/getsentry/sentry/issues/48259

Since we're aware of some false positives, for example:
* https://github.com/getsentry/sentry-javascript/issues/8301)

Lets hide the breadcrumbs from the UI until we're comfortable with the detection logic.

For debugging purposes, we'll let them be visible to ourselves (we'll feature flag it)

**Comment by billyvg** [comment]
I disagree we should hide the breadcrumbs in the UI, I think the breadcrumbs are pretty "low stakes" compared to notifications. It's additional context for the user as they are viewing the replay. Showing these breadcrumbs for users will allow to us to start gather real user feedback while we decide how to best use this data.
