### ISSUE TITLE
I am the owner of the sentry account. I don't see an option to update my password

### ISSUE THREAD

**Issue by rakesh-nd** [getsentry/sentry#5062]
## General Support

If you're looking for general support, please utilize our [community forum](https://forum.sentry.io/) rather than GitHub Issues.

## Reporting Bugs

When reporting bugs, include details about your configuration, such as:

- The version of Sentry you're using
- Whether you're using Docker or another installation method
- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration when relevant

**Comment by dcramer** [comment]
As per the prefilled template, this is not a support forum. The password change is in your account settings, which is available via your avatar in the bottom corner.
