### ISSUE TITLE
Link Issue Tracker doesn't seem to work after escalation

### ISSUE THREAD

**Issue by mvgijssel** [getsentry/sentry#5063]
The Link Issue Tracker button on the detail page (shown after escalating an issue) of an issue doesn't work. It redirects to `<<projectname>>/settings/issue-tracking/` even though the issue tracking has been configured (Phabricator). 

![image](https://cloud.githubusercontent.com/assets/6029816/23795280/fc1593a0-0594-11e7-8e8b-c2ce8a1e6e54.png)

Clicking on the link of the external escalation tool in the comment section of the same issue works just fine indicating the external tracker has been configured properly. 

![image](https://cloud.githubusercontent.com/assets/6029816/23795396/b9d8864a-0595-11e7-8c56-8caebdeef47e.png)

## Details
Sentry 8.12.0
Phabricator plugin 0.7.0 
Installation not through Docker

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
