### ISSUE TITLE
Metrics & Dashboards for grouping release confidence

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#50640]
Create metrics to monitor state of grouping both on product and infrastructure to ensure we don’t introduce unexpected behavior. One of the challenges we've had in the past with releasing grouping changes is the whether or not we've introduced undesired grouping behavior outside of the target area to fix. 

We should be able to create very simple metrics to begin with which can help give indications on the expected outcome of a grouping change is occurring or not. Some ideas:
- Counting the number of new issues grouped by platform by day

**Comment by armenzg** [comment]
I've created an initial query [here](https://redash.getsentry.net/queries/4300/source#5419).

```
SELECT
  platform,
  count(*) as count,
  DATETIME_TRUNC(first_seen, DAY) as trunc_date
FROM
  getsentry.sentry_groupedmessage
WHERE first_seen>'2023-01-01 00:00:00' and first_seen<'2023-06-08 00:00:00'
group by
  platform,
  trunc_date;
```

<img width="928" alt="image" src="https://github.com/getsentry/sentry/assets/44410/466e4996-60ca-4397-b8f1-8e3beb411f11">
