### ISSUE TITLE
Replay player does not show correct timestamp on initial load with timestamp query param

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#50653]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to replay
2. Go to a specific part of the replay and click the share button
3. Copy the link with a `t=<timestamp>` parameter and load it in a new tab

You will see that the replay appears to start at the beginning. Once you hit play the player does go to the correct timestamp, but it's a bit confusing that it doesn't start there on initial load.

### Expected Result

Would expect the player to visually begin at the shared timestamp on initial load.

### Actual Result

See this [very meta replay link](https://sentry.sentry.io/replays/javascript:2ef565420e5d420990e9d8279b283e59/?project=11276&query=&referrer=%2Freplays%2F%3AreplaySlug%2F&statsPeriod=30d&t_main=network&yAxis=count%28%29&t=68) (with a timestamp query param) of me loading a replay with a timestamp query param.

### Product Area

Replays

**Comment by ryan953** [comment]
Fixed with https://github.com/getsentry/sentry/pull/50779
