### ISSUE TITLE
Stack trace: Use gray and italicized text for system frames

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#50691]
In order to more easily visually distinguish system vs in-app frames, use gray italicized text for the function names:

![Image](https://user-images.githubusercontent.com/10888943/244813298-05ef31f4-9396-4322-b268-fb0340c1623d.png)

**Comment by 17hogeju** [comment]
With 6 responses to [Feedback on proposed stack trace changes](https://docs.google.com/forms/d/e/1FAIpQLSe2tnnLkIWsxyj4NYtnM3H_LXIrGD6cug4uxQGiN-XVXkz0eg/viewform?usp=sf_link), people seem to be mostly for gray/italicizing and removing the system tag
