### ISSUE TITLE
"Organization is over the membership limit" when opening issue list via url

### ISSUE THREAD

**Issue by beheh** [getsentry/sentry#5070]
My team is using the hosted Sentry 8.15.0.dev0 at https://sentry.io. Our organization has 4 members in the Sentry for Open Source plan and has been using it for quite a few months now (no member has been added recently).

When navigating to a project by clicking on ifrom the Dashboard all works fine, the url changes to the project url (https://sentry.io/[organization]/[project]/) and I see the issue list and can use it as usual. However, refreshing the page from the browser or entering the page directly via a bookmark results in the following message:

![grafik](https://cloud.githubusercontent.com/assets/929769/23836735/605d76f4-077d-11e7-9696-89692f344b52.png)

This seems like a bug since everything still seems to work as usual and the and the managers do not seem to receive any kind of notification - we still seem to be in the same plan we have been for quite some time.

My billing manager is reporting he keeps getting redirected to billing, just to find nothing unusual when opening the page directly via the url.

**Comment by beheh** [comment]
This started happening to us around the 27th of February.

**Comment by dcramer** [comment]
Can you email support@ with the organization name (and reference this PR so they have full context). Thanks!

**Comment by istepaniuk** [comment]
This seems indeed to be a bug. We are on a hosted, paid plan, 3 members, experiencing **exactly** this.

**Comment by dcramer** [comment]
As per the previous note, please contact support if you're seeing this. Often this is due to confusion around which organization is selected.
