### ISSUE TITLE
Embed the span details into the Trace View's transactions

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#50715]
### Problem Statement

Right now if you're on the Trace View, there's no way to see the span details embedded under the transactions. A user asked me, "Do I have to click View Event? Is there some config I am missing to allow this view in the Trace View Page?"

For example, you have to click the 'pageload' VUe.js transaction here and then click 'View Event', in order to get that span details, and then you are no longer viewing the entire trace anymore (as you'd only be viewing the frontend Vue.js transaction).

Q. "Is the ask if spans can be included in trace view basically?"
A. Yes

Q. "Right so they can see a combined span waterfall across all the transactions in the trace?"
A. Yes

![image](https://github.com/getsentry/sentry/assets/8920574/87c1be16-1d79-4701-8fc7-e276ab8a0cdb)
![image](https://github.com/getsentry/sentry/assets/8920574/62ec57a7-a176-46f8-9a4a-8c14d1d819fa)

### Solution Brainstorm

Transaction's Event Detail page has the solution. It says "This span has a direct child. Add transaction to view"

Need to show spans for each transaction in Trace View. Show them all open (uncollapsed into a transaction) by default. Or offer the '+' icons to uncollapse it, and fetch the spans as you click the '+'.

![image](https://github.com/getsentry/sentry/assets/8920574/76c5061f-f980-40fd-aaae-7e5dc0e26569)

### Product Area

Performance

**Comment by brentc** [comment]
This is an interesting idea that's been brought up before. Adding it to our backlog to be prioritized against other initiatives.

**Comment by Dhrumil-Sentry** [comment]
The new trace view addresses a lot of this feedback: https://sentry.io/changelog/the-new-trace-view-is-generally-available/
