### ISSUE TITLE
[SPIKE] Understand why tagging is not working on Sentry project

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#50714]

**Comment by iambriccardo** [comment]
We did some analysis and found a first problem which is unrelated ( #implemen

**Comment by iambriccardo** [comment]
We are still unsure though, what the problem might be. At least we rolled back the PR from Neel which was problematic for our use case.

**Comment by ale-cota** [comment]
We're unable to find anything at this point, will wait for Issues team to start testing and get more feedback.
