### ISSUE TITLE
Event details link to search other issues experienced by a particular user

### ISSUE THREAD

**Issue by LewisJEllis** [getsentry/sentry#5074]
Say I look at an issue and see only a few users are affected; I might wonder "what other issues are these users encountering?". In the event view where we show the user context details (`context-summary.context-item.user`), we could incorporate some sort of link to a search view. If we have a user ID of "lewis" we might link to say https://sentry.io/org/project/?query=is%3Aunresolved+user%3Alewis as a "find other issues this user experienced" sort of thing.

This came up in discussion with @jessla on some user feedback.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
