### ISSUE TITLE
Event aggregation count "blocked" at "1"

### ISSUE THREAD

**Issue by jdeniau** [getsentry/sentry#5075]
I'm sorry I can not use your forum: when I try to activate my account, I got a `['BAD CSRF']` :/

## Bug

Sentry version: 8.14.1

I think an image is more relevant than a description here:

![](https://box.everhelper.me/attachment/811268/1c6cdbff-27bf-4189-aa9a-0759513bf7db/499720-7eMB6W4xSTIAbErg/screen.png)

The "count" of event stay "blocked" at "1", even if the total number of items is > 1 (4 in the screenshot here)

As a matter of fact, I tried triggering 1000 error and the total count stays at "1", but the "charts" size seems related to the real number of events:
![](https://box.everhelper.me/attachment/811279/1c6cdbff-27bf-4189-aa9a-0759513bf7db/499720-PGbWwyPloFJf7d0a/screen.png)

57 in the first row (for 1000 trigger, probably the "rollup" thing), 4 in the second (for 4 triggered). 

Is this a bug or a feature ??

Thanks

**Comment by mattrobenolt** [comment]
Sigh. I think this bug fix didn't make 8.14.x. I'll probably cut a 8.14.2 containing the fix for this. It was introduced late in the 8.14.0.dev0 cycle, and not noticed until after 8.14 was cut.

**Comment by jdeniau** [comment]
Well good news :)

Waiting 8.14.2 then
