### ISSUE TITLE
Allow changing SAML certificate

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#50792]
### Problem Statement

Currently it is not possible to change update SAML certificates without disabling SSO completely in the Sentry organisation.

### Solution Brainstorm

Allow owners to change certificates while SSO is still enabled.

### Product Area

Unknown

**Comment by chadwhitacre** [comment]
Let's use "Sign In" for this one.

**Comment by leedongwei** [comment]
This will be on the roadmap for our work on SAML.

**Comment by nhsiehgit** [comment]
🤔 

Is this still an issue?

I've set up a custom SAML sso integration in okta via the idP certificate
![Mar-27-2024 16-38-41](https://github.com/getsentry/sentry/assets/6186377/e658ccce-9d80-4fc9-8dbb-b0f831a91a73)

Validated creating a new certificate and updating it via the auth form

**Comment by nhsiehgit** [comment]
@rodolfoBee - do you know which SAML SSO set up was used that's not allowing for the certifcate to be udpated?

**Comment by nhsiehgit** [comment]
I'm gonna backlog this again

I'm unable to replicate and I'm also not entirely sure what the use case would be for someone to update their SAML cert either 🤔 

@rodolfoBee if you've got any more information on this, mind updating this ticket or closing this out? 🙏

**Comment by rodolfoBee** [comment]
@nhsiehgit do you see the option to change certificate when you set SSO with Okta, AD, OneLogin, Jumpcloud, Auth0 or Rippling?

**Comment by leedongwei** [comment]
@nhsiehgit E.g. https://devsentry-okta.sentry.io/organizations/devsentry-okta/auth/configure/
