### ISSUE TITLE
OPSGenie integration should support Metric Rules

### ISSUE THREAD

**Issue by mdestagnol** [getsentry/sentry#50860]
### Problem Statement

Currently, it's not possible to fire an on-call alert if a metric rule is getting triggered. It would be beneficial if it did.

### Product Area

Settings - Integrations

**Comment by scttcper** [comment]
duplicate of https://github.com/getsentry/sentry/issues/37347

**Comment by Dhrumil-Sentry** [comment]
@mdestagnol Please have a look at our GH discussion about a new opsgenie integration: https://github.com/getsentry/sentry/discussions/54156
