### ISSUE TITLE
Consolidate AlertRuleDetailsEndpoint's

### ISSUE THREAD

**Issue by roggenkemper** [getsentry/sentry#50899]
Right now we have 2 endpoints for alert rule details : ProjectAlertRuleDetailsEndpoint and OrganizationAlertRuleDetailsEndpoint. The vast majority of requests use the organization version but a few still use the project one, and the project one has some functionality the organization one doesn't. to prevent confusion and clean things up, they should be consolidated into 1 endpoint.

**Comment by ceorourke** [comment]
Done 😄
