### ISSUE TITLE
Doc: (solution included) Angular2 webpack starter - documentation for integration with sentry

### ISSUE THREAD

**Issue by kamil-kielczewski** [getsentry/sentry#5090]
## Information about problem

Hi, I start using sentry but I see lack in documentation about Angular2-webpack-starter (A2WS) integration - so below I put Instruction that I create myself to do it (i spent 2-3hours on this so it is not trivial).

I know that there is [Anuglar CLI documentation](https://docs.sentry.io/clients/javascript/integrations/angular2/) but A2WS is 'environment/framework' used for build more large and complicated systems - this is why documentation for integration it with sentry is important.

## Solution

Below instruction is for Angular2-webpack-starter (A2WS) https://github.com/AngularClass/angular2-webpack-starter  version from commit [55d4325] Mar 8, 2017. This is done in this way that on development mode Sentry if OFF, but in production mode (for normal and AoT build) sentry is ON

1. Go to project directory and in console run:
npm install raven-js --save

2. Create file: ./src/app/app.sentry.ts

```
import * as Raven from 'raven-js'; // http://sentry.io
import { ErrorHandler } from '@angular/core';

if ('production' === ENV) // this is needed to activate sentry ONLY in production mode. (without this 'if' import statement in environment.ts wil execute this code on dev)
{
    Raven // Sentry configuration http://sentry.io
        .config('https://xxxxxxxxxxxxxxxxxxxxxxxxxx@sentry.io/yyyyyy')
        .install();
}

export class RavenErrorHandler implements ErrorHandler {
  public handleError(err: any): void {
    Raven.captureException(err.originalError);
    console.error(err);                         // show captured errors into browser console - for directly see errors on reproducing it in production
  }
}

export const SENTRY_PROVIDER =  { provide: ErrorHandler, useClass: RavenErrorHandler };
```
 
3. Edit file  ./src/app/environment.ts and add 2 lines of code:

```
// Angular 2
import {
  enableDebugTools,
  disableDebugTools
} from '@angular/platform-browser';
import {
  ApplicationRef,
  enableProdMode
} from '@angular/core';

import * as Sentry from './app.sentry';    // !!!-> SENTRY NEW FIRSRT CODE LINE

// Environment Providers
let PROVIDERS: any[] = [
  // common env directives
];

// Angular debug tools in the dev console
// https://github.com/angular/angular/blob/86405345b781a9dc2438c0fbe3e9409245647019/TOOLS_JS.md
let _decorateModuleRef = <T>(value: T): T => { return value; };

if ('production' === ENV) {
  enableProdMode();

  PROVIDERS.push(Sentry.SENTRY_PROVIDER); // !!!-> SENTRY NEW SECOND CODE LINE

  // Production
  _decorateModuleRef = (modRef: any) => {
    disableDebugTools();

    return modRef;
  };

  PROVIDERS = [
    ...PROVIDERS,
    // custom providers in production
  ];

} else {

  _decorateModuleRef = (modRef: any) => {
    const appRef = modRef.injector.get(ApplicationRef);
    const cmpRef = appRef.components[0];

    let _ng = (<any> window).ng;
    enableDebugTools(cmpRef);
    (<any> window).ng.probe = _ng.probe;
    (<any> window).ng.coreTokens = _ng.coreTokens;
    return modRef;
  };

  // Development
  PROVIDERS = [
    ...PROVIDERS,
    // custom providers in development
  ];

}

export const decorateModuleRef = _decorateModuleRef;

export const ENV_PROVIDERS = [
  ...PROVIDERS
];
```

And thats all :) 

Now when you run server in development mode by `npm run server` sentry will bi OFF. But if you build dist by `npm run build:prod` or `npm run build:aot` and run it by `npm run server:prod` sentry will be ON

**Comment by BYK** [comment]
I think this is good now: https://docs.sentry.io/platforms/javascript/guides/angular/
