### ISSUE TITLE
Go Onboarding Missing Frameworks

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#50921]
### Problem Statement

If I am using any specific framework for Go (where Sentry even does have SDK specific support) the Sentry product provides no clear way in onboarding to discover it.

- The platforms do not exist
- once creating a Go vanilla project there's nothing that tells me there may be a better way to set up the SDK for my app

<img width="1166" alt="image" src="https://github.com/getsentry/sentry/assets/47563310/3c08c281-c1c6-482f-9133-2d2e44e2b31e">
- includes Google and other's only because of %go%, ignore those

### Solution Brainstorm

- Add platforms for the framework specific support
  - [Go Vanilla](https://docs.sentry.io/platforms/go/)
  - We can confirm which from these warrant an own platform for project creation
  - all to be named: "go-{frameworkname}"
<img width="179" alt="image" src="https://github.com/getsentry/sentry/assets/47563310/34d0d39f-3ce4-4046-980c-d4fc744b078b">

- Once added consider a modal
  - when selecting Go Vanilla we should prompt users (the modal) if they may want a framework specific setup

- Ideally searching "go" or "golang" will return all go platforms

### Product Area

Projects

**Comment by ale-cota** [comment]
We can do this within the migration to React, Pri can create a first version and ask the SDK folks for review.

**Comment by priscilawebdev** [comment]
We need an image for "go" that will be displayed at the top of the framework selection modal cc @Jesse-Box
