### ISSUE TITLE
Custom decryption log and pdb file

### ISSUE THREAD

**Issue by A-BenMao** [getsentry/sentry#50923]
### Problem Statement

For security reasons, the log text and pdb file generated by our program are encrypted and encrypted on the client side. Therefore, after we upload the event information through sentry SDK, the information we see on the GUI interface cannot be parsed normally.
How does sentry handle this scenario? Can plugins solve it？

### Solution Brainstorm

We tried to solve this problem by means of the plugin integrations, but found that there were no attached parameters

### Product Area

Issues

**Comment by scefali** [comment]
@A-BenMao What's the product ask exactly? I'm not quite sure.

**Comment by A-BenMao** [comment]
Under normal circumstances, the data uploaded by sentry SDK is plain text, and sentry can decode it normally. But our product is very special:The error message (log) and C++ PDB file are encrypted, which makes sentry unable to parse and process according to the normal process.
But we can't decrypt it on the client side, because that is equivalent to encrypting and decrypting on the client side, which is not safe, so we want to handle it on the sentry side.

**Comment by Swatinem** [comment]
You should not ship the C++ PDB file to the client to begin with.
You would upload the unencrypted PDB file to Sentry, or configure a custom symbol server where we can access it. The PDB file never ends up with clients, it is only referenced by a unique ID.

For the log message, we currently have no way to hook into that. You might have some luck using some custom grouping rules, and then fetch events from the API to decrypt them with whatever tool you want to use.
