### ISSUE TITLE
Issues not marked with Regression labels

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry#50937]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Resolve an issue 
2. Send new event 
3. Regression label is missing

### Expected Result

Expecting a regression label to be displayed on the issue and the issue to appear in the Issue Stream using `is:for_review`. 

### Actual Result

None

### Product Area

Issues

**Comment by snigdhas** [comment]
This should be fixed with https://github.com/getsentry/sentry/pull/50872. The changes will be deployed soon.
