### ISSUE TITLE
Https API requests return http response pagination links

### ISSUE THREAD

**Issue by pastchan** [getsentry/sentry#50933]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Run any API request from our documentation here: https://docs.sentry.io/api/
I am using the [List Your Projects](https://docs.sentry.io/api/projects/list-your-projects/) endpoint.

### Expected Result

The response link should start with https.

### Actual Result

The response pagination link starts with http:
```
<http://sentry.io/api/0/projects/?&cursor=1686556948990:0:1>; rel="previous"; results="false"; cursor="1686556948990:0:1", <http://sentry.io/api/0/projects/?&cursor=1588775467235:1:0>; rel="next"; results="false"; cursor="1588775467235:1:0"
```

This can be a problem for some customers if they use client libraries that assume the URL prefix returned in the pagination links matches the URL prefix of the request.

### Product Area

Other

**Comment by hubertdeng123** [comment]
I am able to reproduce this and it seems unexpected here.

**Comment by hubertdeng123** [comment]
Going to investigate this myself, but it seems like the likely culprit is something going wrong with the uri on this line
https://github.com/getsentry/sentry/blob/6609c64773cc7542e19648ed4fc9fff7ff947184/src/sentry/api/base.py#L64

**Comment by miguelslemos** [comment]
> Going to investigate this myself, but it seems like the likely culprit is something going wrong with the uri on this line
> 
> https://github.com/getsentry/sentry/blob/6609c64773cc7542e19648ed4fc9fff7ff947184/src/sentry/api/base.py#L64

Hey @hubertdeng123 any update?

**Comment by rodolfoBee** [comment]
This issue is now solved:

Request: 
`GET https://sentry.io/api/0/issues/<redacted>/events/`

Link header in the response:
`<https://sentry.io/api/0/issues/<redacted>/events/?&cursor=0:0:1>; rel="previous"; results="false"; cursor="0:0:1", `
`<https://sentry.io/api/0/issues/<redacted>/events/?&cursor=0:100:0>; rel="next"; results="true"; cursor="0:100:0"`
