### ISSUE TITLE
Add impacted users / # of events to Slack alert

### ISSUE THREAD

**Issue by ido-green** [getsentry/sentry#50944]
### Problem Statement

With the Sentry Slack integration, we can add specific tags to the Slack message, would be great to have impacted users / # of events. 

### Product Area

Settings - Integrations

**Comment by ceorourke** [comment]
We've added the number of users and events for issue with more than one event - see [this post](https://docs.sentry.io/changelog/more-context-in-slack-alerts/) for more details on the Slack changes.
