### ISSUE TITLE
Issues stream - Sorting on Issue count is mixed when Performance Issues are present

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#50961]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open issue stream with All categories selected 30 days
2. Sort on Event count
3. Shows all events with Performance events mixed
4. Switch to errors only shows the right order as Perfomance issues don't happen that much

### Expected Result

I would expect Performance count would be mixed correctly together with the the error issues based on count.

### Actual Result

Performance issues are sorted but not on the right position within the stream

Example
1. Error Issue -> 100k
2. Error Issue -> 88k 
3. Performance issue -> 102
4. Performance issue -> 86
5. Error Issue -> 66k 

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1855) by [Unito](https://www.unito.io)

**Comment by Angelodaniel** [comment]
Looks like it's been caused by hitting the limits of the amount of tags. Or at least the query fails during the load

**Comment by ceorourke** [comment]
This seems to very specifically be happening with the `is:unassigned` filter and with "All Categories" selected (or at least this is the only way I am able to reproduce it). We show a few error issues, then all of the performance issues, and are leaving out a large number of error issues with higher event counts than the performance issues shown. I can only reproduce it in one organization (the one that prompted this GH ticket). 

For testing / reproduction purposes, it's most evident if you have 3 tabs open with the `:is:unassigned` filter - one with only the "Error" category selected, one with only the "Performance" category selected, and one with "All Categories" selected. I also get slightly different results if I query `is:unassigned issue.category:[error, performance] ` - in this case there are more error issues before the performance issues show up, but there are still some missing.

We'll still try looking into it, but I wanted to record the investigation results.

**Comment by snigdhas** [comment]
I'm no longer able to repro this - @Angelodaniel are you still seeing this behavior?

**Comment by Angelodaniel** [comment]
Seems to be normal again! @snigdhas 👍 I'll close the ticket
