### ISSUE TITLE
When teams have "organizations" in their name, navigation in team settings doesn't work

### ISSUE THREAD

**Issue by ChelseaValentine-at** [getsentry/sentry#51003]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a Sentry team whose name has "organizations" in it, e.g. "cool-organizations".
2. Go to the Sentry team page in settings (e.g. `https://<your subdomain>.sentry.io/settings/teams/cool-organizations/members/`)
3. Try to navigate between any of the tabs, e.g. to any of the "Members", "Projects", "Notifications", or "Settings" tabs.
4. Observe that you go to a page like `https://<your subdomain>.sentry.io/settings/<your subdomain>/teams/cool-/`.

### Expected Result

It loads the Members, Projects, Notifications, or Settings tab for that team at a URL, such as `https://<your subdomain>.sentry.io/settings/teams/cool-organizations/members/`

### Actual Result

It tries to link you to a page like `https://<your subdomain>.sentry.io/settings/<your subdomain>/teams/cool-/`. Once you arrive there, you'll see
```
This team does not exist, or you do not have access to it.
```

### Product Area

Settings - Teams

**Comment by dashed** [comment]
@ChelseaValentine-at Thanks for writing in. I'll investigate and have a fix for this bug.

**Comment by dashed** [comment]
@ChelseaValentine-at Just looping back here, this bug should now be fixed.

**Comment by ChelseaValentine-at** [comment]
that was fast, thanks! :D
