### ISSUE TITLE
[SPIKE] Check for possible `client_sampled` in tagging

### ISSUE THREAD

**Issue by iambriccardo** [getsentry/sentry#51026]
Right now the error tagging doesn't support client side sampling, that is, if a trace is sampled out by the head of the trace, this information is not propagated in the trace header (aka dsc). This means that from the perspective of dynamic sampling, we don't know whether the trace has been sampled out on the client and this could lead to false positives.

We would need to fix this by having the client SDKs add the client sampling decision in the dsc that will be attached to the error. This client sampling decision will work similarly to dynamic sampling, that is, if the head is sampled out all the children are sampled out and vice versa.

**Comment by ale-cota** [comment]
Waiting for SDK work and overall tracking issue.
