### ISSUE TITLE
Add RuleSnooze manager functions + test fixture

### ISSUE THREAD

**Issue by ceorourke** [getsentry/sentry#51055]
Add functions like `RuleSnooze.objects.disabled_for_team(alert_rule)` and `RuleSnooze.objects.disabled_for_user(alert_rule, user)` on the model manager and update code as needed. 

Add a test fixture `mute_rule(rule, user=None)` and/or `mute_alert_rule(alert_rule, user=None)` and update tests as needed 

This is more of a nice to have and isn't necessary before EA/GA.

**Comment by roggenkemper** [comment]
Good suggestion - definitely would help clean up a lot of code around muting alerts
