### ISSUE TITLE
Message is cut off

### ISSUE THREAD

**Issue by jorgsiegel** [getsentry/sentry#51149]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Report a message with many characters. 

We use this message:
`Skip sending email/push for entry with category "${entry_category}" and id "${doc.id}" because entry was created less than 2 minutes ago. Now: "${new Date().toLocaleString()}"; createTime: "${doc.createTime?.toDate()}"; date_creation: "${doc.data() .date_creation.toDate()}".`

### Expected Result

See the whole message.
Why is it cut off so soon!?

### Actual Result

It is cut off after createTime (around the middle of the message)

### Product Area

Unknown

**Comment by jorgsiegel** [comment]
"@sentry/angular": "^7.35.0"

**Comment by Kobby-Bawuah** [comment]
Hey @jorgsiegel, 

Apologies for the delay in getting back to you. It seems that I missed your GitHub issue when you replied. I'm here now to assist you. Are you still experiencing the message truncation problem?

If the issue persists, I recommend trying to set the [maxValueLength](https://docs.sentry.io/platforms/javascript/guides/angular/configuration/options/?original_referrer=https%3A%2F%2Fwww.google.com%2F#max-value-length) option and see if it resolves the truncation. By adjusting this setting, we can increase the allowed length of your messages.

Once you've made the necessary changes, please let me know the outcome of your test

**Comment by hubertdeng123** [comment]
Going to close this as this looks resolved.
