### ISSUE TITLE
Add 301 permanent redirect when changing project slug

### ISSUE THREAD

**Issue by ruimarinho** [getsentry/sentry#5116]
Similarly to GitHub, it would be nice if changing a project slug would add a 301 redirect rule to the new one.

**Comment by mattrobenolt** [comment]
Not sure if we could ever reasonably support an actual 301 redirect since this logic happens purely client side in the React app, but it likely wouldn't be unreasonable to support some client side redirect like we do when merging groups.

**Comment by ruimarinho** [comment]
A client side redirect, while not being ideal, works for me. Thanks for taking this into consideration.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
