### ISSUE TITLE
(API) statsPeriod paramater ignored

### ISSUE THREAD

**Issue by RuyiLi** [getsentry/sentry#51186]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Send a request to list a project's issues (need authorization header): `curl https://sentry.io/api/0/projects/uncountable/unc-f/issues/\?statsPeriod\=24h`

### Expected Result

According to https://docs.sentry.io/api/events/list-a-projects-issues/, the issues should be filtered down according to the stat period.

### Actual Result

I am seeing issues last occurring as early as March, with zero occurrences in the past 24 hours.

<img width="355" alt="image" src="https://github.com/getsentry/sentry/assets/16544254/5e1dc159-6fa9-45bf-be03-c2156ab9c094">

### Product Area

Projects

**Comment by ceorourke** [comment]
@RuyiLi I definitely see why this is confusing! The `statsPeriod` param just changes the results of `stats`, not the returned issues. I can file a feature request to add the behavior you're looking for - may I ask what you're trying to achieve? Maybe there's some other solution.

**Comment by RuyiLi** [comment]
Oh, that clears things up. Thank you! I was trying to filter out any issues that occurred more than 24 hours ago. I was able to run a manual date filter after retrieving all of the issues, however, so it's not too big of a deal
