### ISSUE TITLE
Jira Integration Problem

### ISSUE THREAD

**Issue by metok** [getsentry/sentry#51219]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. .../jira/marketplace/discover/app/sentry.io.jira?installDialogOpen=true&source=mpac click on "Get it now", "Sentry for Jira was added." popup appears
2. Click on "Get started" or "Configure" on the Popup
3. Loading spinner for a long time...
4. "Something failed" Error message, I get it in German: "Irgendetwas ist schiefgelaufen. Unser Team wurde benachrichtigt. Sollte das Problem bestehen bleiben, wenden Sie sich an den Support von Atlassian."

### Expected Result

Sentry App is installed

### Actual Result

Sentry App configuration dialog is not starting

### Product Area

Settings - Integrations

**Comment by scefali** [comment]
@metok did you contact Atlassian support? This error happens in Jira so I don't know what we can do unless Atlassian can figure it out.

**Comment by Dhrumil-Sentry** [comment]
@metok if you are trying to install the Jira integration you can do that from your own Sentry org too by going to Settings->Integrations

**Comment by metok** [comment]
In the org>settings>integrations it's said:
"Visit the Jira Marketplace to install this integration. After installing the Sentry add-on, access the settings panel in your Jira instance to enable the integration for this Organization."

So I cannot install it from Sentry. But I will ask the Atlassian support.

**Comment by metok** [comment]
![image](https://github.com/getsentry/sentry/assets/2174685/c01f9e03-998a-4a5f-84de-a2a3248bf6b0)

Actually Atlassian support for the integration is referencing to this GitHub project for issue tracking.

**Comment by hubertdeng123** [comment]
@metok are you still experiencing this issue?

**Comment by metok** [comment]
I found out, that the Adblocker is breaking the configuration page of the plugin (https://....atlassian.net/plugins/servlet/ac/sentry.io.jira/configure-sentry).

When I disabled the Adblocker, the integration worked.

**Comment by ceorourke** [comment]
I'm just seeing this but FYI we mention this in our docs: https://docs.sentry.io/product/integrations/issue-tracking/jira/#something-went-wrong-message-with-jira-on-saas-sentryio-install I'm not sure if there's anything we can do about being blocked.
