### ISSUE TITLE
Query parser assigns inclusivity inclusivity incorrectly when using 'event.timestamp'

### ISSUE THREAD

**Issue by travisoneill** [getsentry/sentry#5121]
'date_from_inclusive' is set to True when the '>' operator is used and to False when the '<=' operator is used.

example queries:
event.timestamp:>12-12-12
event.timestamp:<=12-12-12

see parse_query at /src/sentry/search/utils.py:297

**Comment by travisoneill** [comment]
Trying to fix this right now

**Comment by mattrobenolt** [comment]
🎉

**Comment by travisoneill** [comment]
I think there is also an issue with the 'firstSeen' tag functionality.  The test suite shows it as having exactly the same behavior as the 'age' tag:

    def test_age_range(self):
        result = self.parse_query('age:-24h age:+12h')
        assert result['age_from'] > timezone.now() - timedelta(hours=25)
        assert result['age_from'] < timezone.now() - timedelta(hours=23)
        assert result['age_to'] > timezone.now() - timedelta(hours=13)
        assert result['age_to'] < timezone.now() - timedelta(hours=11)

    def test_first_seen_range(self):
        result = self.parse_query('firstSeen:-24h firstSeen:+12h')
        print(result)
        assert result['age_from'] > timezone.now() - timedelta(hours=25)
        assert result['age_from'] < timezone.now() - timedelta(hours=23)
        assert result['age_to'] > timezone.now() - timedelta(hours=13)
        assert result['age_to'] < timezone.now() - timedelta(hours=11)


Will also change this in the PR.

**Comment by travisoneill** [comment]
@mattrobenolt What does the inclusivity boolean do in terms of timestamp searches?  If it is only handling whether an item is returned when occurring at the exact millisecond of the search bound that would seem like an extreme edge case not worth worrying about.

**Comment by travisoneill** [comment]
Fixed with PR #5169

**Comment by BYK** [comment]
Closing this issue due to staleness (associated PR was also closed now). All this should be fixed by our new search infrastructure Snuba now.
