### ISSUE TITLE
Design: Source map table view sucks hard

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#51221]
### Problem
- Users associate new releases to old artifact bundles, but the UI provides no means of highlighting this use case. The UI assumes that the most recent bundles are the only relevant bundles. Whilst, this true for most cases, we’ve discovered many cases that fit the original problem statement.
- Our customer support have a difficult time finding artifact bundles which contain a file with a matching debug ID.

### Acceptance Criteria
- Users can easily find which artifact bundles were recently updated with releases
- Users can easily find which artifact bundles contain a file with a specific debug ID

**Comment by Jesse-Box** [comment]
I'm marking this task as done

Figma files can be found [here](https://www.figma.com/file/Ieg9z8tLIHuI8viooNRA7c/Specs%3A-Source-Map-Project-Settings-v4?type=design&node-id=389%3A6751&mode=design&t=dAFkFQpVkqmo1vCc-1)

Foot note:
I don't think these designs should be prioritized for development, until we get more feedback from tech support
