### ISSUE TITLE
More analytics for biases sufficiency

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#51229]
**Problem**: We currently have analytics in place for this assessment [for the Performance page](https://analytics.amplitude.com/sentry/chart/o91aplfn/edit/ts9upoeb). Signal correlation is another success metric for our biases, so we should implement further analytics to track this.

**Solution**: Implement analytics to track the availability of connected traces on the Issues page and the Replay page (Navigate to the Trace tab). We also need the ability in the analytics data to filter out customers who are not using Performance.

**Comment by priscilawebdev** [comment]
The analytics available on the Issue Details page offers data for tracking the availability of a trace. This check is specifically triggered when performance monitoring is enabled and actively utilized by a project. Therefore we will only need to do some work on the Session Replay page.
