### ISSUE TITLE
Implement de-duplication with chunking in the assemble endpoint for artifact bundles

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#51224]
In order to optimize the assemble endpoint for artifact bundles, we would like to implement a de-duplication mechanism that allows users to only upload the chunks that weren't already uploaded before.

This is already one similarly for diff in: https://github.com/getsentry/sentry/blob/6b64e53641b41ae9a2b3b23a02f2b26e3d0faaf2/src/sentry/api/endpoints/debug_files.py#L280-L280.

**Comment by iambriccardo** [comment]
Work by @loewenheim on the CLI side being tracked here -> https://github.com/getsentry/sentry-cli/issues/1649.
