### ISSUE TITLE
Unable to install Clickup integration

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#51228]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the Integrations page - https://yourtestorg.sentry.io/settings/integrations/
2. Search for the Clickup integration
3. Click on "Accept & Install"
4. Log in to Clickup when prompted
5. Head back to your Sentry org, the status of the integration will be pending
6. Click on Uninstall, then "Accept & Install" again
7. The app hangs forever and the integration is not installed

### Expected Result

Users should be able to install the Clickup integration

### Actual Result

A 500 error is returned and the installation stays in a pending state:

<img width="605" alt="Screenshot 2023-06-19 at 10 05 03" src="https://github.com/getsentry/sentry/assets/25980868/336b012e-628b-49c7-9b99-06e4575f8028">

### Product Area

Settings - Integrations

**Comment by yes-wordup** [comment]
hi @scefali, thanks for helping with this issue, but unfortunately, it still happens to us today. We still got `500` error when there is a `POST https://app.clickup.com/v1/teams/null/sentry` api call after trying to install the ClickUp integration, and the response is as below
```
{err: "invalid input syntax for integer: "null"", ECODE: "SHARD_001"}
```

Is there any possible reason that we may have a team `null` in that api call? Like we miss some configurations? 
And If you need more info about our usage for figuring out the issue, please feel free to let me know, thanks~
