### ISSUE TITLE
Incorrect Event Count Discrepancy in Sentry Dashboard

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry#51261]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

It is not easy to reproduce. A user pointed it out and I also see it in my org. 

Navigate to the Sentry dashboard.
Put your mouse on the events field and observe the event count displayed for a specific time range, such as the last 14 days.
Compare the displayed event count with the actual count of events since the issue began.
Take note of any discrepancies between the two counts.
Click into the issue to view the details
Compare the displayed event count on the list with the previously observed counts.
Notice differences or inconsistencies between the two counts.

![Screenshot 2023-06-19 at 7 30 14 PM](https://github.com/getsentry/sentry/assets/89524511/6c176dcf-a06d-474e-a218-6a57854fe5ee)

![Screenshot 2023-06-19 at 7 48 38 PM](https://github.com/getsentry/sentry/assets/89524511/04488a31-65d2-464c-af09-c4b89ac939ba)

When I also click on the event number(18) on the second image, I get 19 events in the stream: 
![Screenshot 2023-06-19 at 7 50 41 PM](https://github.com/getsentry/sentry/assets/89524511/b8b58327-43f6-478e-92b2-2a7d041bbec9)

If we are misinterpreting the data, could this be made clear? 

### Expected Result

Numbers are corrected.

### Actual Result

Incorrect Event Count displayed

### Product Area

Issues

**Comment by jangjodi** [comment]
Thanks for bringing this to our attention @Kobby-Bawuah! We are aware of this issue, and have a ticket for it [here](https://github.com/getsentry/sentry/issues/51081).
