### ISSUE TITLE
What does it mean advanced analytics in Business plan?

### ISSUE THREAD

**Issue by filipatbnp** [getsentry/sentry#51272]
### Problem Statement

In https://sentry.io/pricing/ there is
> Business
Standardized Error and Performance Monitoring with insights powered by Discover.
$80/mo
When billed annually with default pre-paid data
Highlights:
    Advanced analytics

### Product Area

Unknown

**Comment by kerenkhatiwada** [comment]
Hello! "Advanced Analytics" primarily refers to the inclusion of features within [Discover](https://docs.sentry.io/product/discover-queries/?original_referrer=https%3A%2F%2Fsentry.io%2F) and [Dashboards](https://docs.sentry.io/product/dashboards/?original_referrer=https%3A%2F%2Fsentry.io%2F). The documentation will provide more detailed information on the specific features available with the Business Plan. Some examples of these features include Discover's [Query Builder](https://docs.sentry.io/product/discover-queries/query-builder/?original_referrer=https%3A%2F%2Fsentry.io%2F), Dashboards' [Widget Builder](https://docs.sentry.io/product/dashboards/widget-builder/?original_referrer=https%3A%2F%2Fsentry.io%2F) and [Custom Dashboards](https://docs.sentry.io/product/dashboards/custom-dashboards/?original_referrer=https%3A%2F%2Fsentry.io%2F).
