### ISSUE TITLE
Feature request: don't mark regression if last resolved time is newer than issue submit time

### ISSUE THREAD

**Issue by messense** [getsentry/sentry#5131]
In our on-premise Sentry deployment, sometime the Celery workers have a lot of lags. When someone mark a issue as resolved, later the lagged Celery workers would mark the issue as regression which actually is not.

Please consider this feature request, Sentry should not mark a issue as regression if last resolved time is newer than issue submit time.

**Comment by mattrobenolt** [comment]
This is what Releases for and Resolved in Release does. Without releases, it's not safe to make this assumption.

**Comment by messense** [comment]
But we have release.

**Comment by messense** [comment]
So you mean I should use `Resolve in next release` instead of `Resolve` button?

**Comment by mattrobenolt** [comment]
Yup.
