### ISSUE TITLE
[Dashboards] Release filter deselect does not default to all releases

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#51336]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the default Dashboard in the Sentry Web UI
2. Filter by release
3. Deselect all release filters

### Expected Result

Upon deselecting all release filters, the filter should default to "All Releases".

### Actual Result

If we choose many releases to filter by, deselecting them does update the Dashboard as long as there is one selected release left. After deselecting the last release left, though, the Dashboard does not update to the "All Releases" filter, but stays in the same view instead.

If we refresh the page, the last selected release that we had will be applied as a filter again. The only way to go back to all releases is to go to a different page and then back to dashboards.

https://github.com/getsentry/sentry/assets/81985895/fc2e5435-1f29-40dc-91c2-010e37414022

### Product Area

Dashboards

**Comment by narsaynorath** [comment]
Hey @stellaatsentry! Thanks for the bug report. We're going to backlog this for now but we'll update the ticket when we push it along.

**Comment by InterstellarStella** [comment]
@ale-cota No, I am not able to reproduce this behavior anymore!

**Comment by bcoe** [comment]
> No, I am not able to reproduce this behavior anymore!

@InterstellarStella woohoo, please let us know if you bump into any more issue.
