### ISSUE TITLE
Internal error when trying to add Linear Integration 

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#51346]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Organisation Settings -> Integrations -> Linear 
2. Click `Accept and Install`

The issue in Sentry can be found here: https://sentry.sentry.io/issues/4264071128/events/7ada4e55c13f4590a6cc4ddda4969992/

The errors are:

```
ApiGrant.MultipleObjectsReturned
get() returned more than one ApiGrant -- it returned 26!

SentryAppInstallation.DoesNotExist
SentryAppInstallation matching query does not exist.
```

### Expected Result

Integration is installed

### Actual Result

Unable to Install Linear error message appears on the bottom right corner. 

### Product Area

Settings - Integrations

**Comment by dalnoki** [comment]
The same happens when you try to install the clickup integration: https://github.com/getsentry/sentry/issues/51349

**Comment by scefali** [comment]
Fixed
