### ISSUE TITLE
Sentry worker only logs time to stdout with issues

### ISSUE THREAD

**Issue by fredvd** [getsentry/sentry#5137]
Running sentry 8.13 with normal processes managd by supervisord.

The sentry works only logs the time component when a new event occurs, not the date. This is confusing if you want to figure out 'when' something happens.  Found while figuring out #5136.

What is logged is:

15:06:21 [ERROR] celery.worker.job: Task sentry.tasks.email.send_email[08f311a6-a86b-41eb-9b6b-cfd128d69c1c] raised unexpected: gaierror(-5, 'No address associated with hostname') (dat
a={u'hostname': 'celery@zzz-servernamewithoutdomain-zzz', u'name': 'sentry.tasks.email.send_email', u'args': '[]', u'internal': False, u'kwargs': "{'message': <django.core.mail.message.EmailMu

**Comment by franciscomemoli** [comment]
Same problem here! Any workaround?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
