### ISSUE TITLE
Feature request: Searching specific events

### ISSUE THREAD

**Issue by nhumrich** [getsentry/sentry#5138]
My team absolutely loves sentry. It is a game changer, and we tell everyone about it. 

One thing that we really wish we could do is search specific events. Currently, when you seach for a specific field, you get all issues that match the search. When you click on one, you get the issue, but it shows all of the events for the issue, not just the ones that match your search term. One very common example is "environment". Its nice to be able to tag which environment an issue came from. However, sometimes we want to see the specific events that happened on production. It is nice to be able to see all users impacted on production, and a specific event. However, when you search by environment, you just get a list on issues that happened, its impossible to get the specific events that happened on production without going to the issue, and manually clicking through all events until you find one that happened on production.

Along these lines, sometimes we have a customer report an issue outside of sentry reporting. Right now, when we search by "user", we just get the issues, but its not possible to get the specific event for that User, making debugging harder, as not all the details always match up. 

Right now, this is so painful for us, that we actually end up creating separate projects for each environment. We have `foobar-dev`, `foobar-stage`, `foobar-beta`, `foobar-prod`. That way, the only events are the one on that environment. The "tagging environment" ability is useless for us without being able to filter events, not just issues. 

Is there anyway you guys could add the ability to search/filter individual events?

----
Since we are on the topic of searching by events, a nice cherry on top would be if there was an extra field I could send to sentry that would let me search by that, but not be included in the issue filters. For example, we use microservices, so we tag every request with a correlation-id. When a service calls another service, that correlation-id gets passed down the chain. It would be amazing if we could search by correlation-id to get the specific event that failed. But adding the correlation id to the issue filter would be pointless, as there will always be only one and exactly one event with that correlation-id. Doing statistics on that field would be pointless.

**Comment by tuatara** [comment]
This feature would make the user filtering much more useful for us also … currently it's easy to see what issues a user has had, but much more difficult to discover the specific events.

**Comment by kiwiscanfly** [comment]
This feature would be very useful for us as well.

**Comment by nhumrich** [comment]
Would love to see a comment from the sentry team on this.

**Comment by dcramer** [comment]
This will happen "sometime in the future", but probably not until mid next year. There will be various things you see that lead up to this, slowly making events more accessible, but we won't open up a full stream search for a little while.

**Comment by mydea** [comment]
Is there any update on this? Would love to have that feature!

**Comment by nhumrich** [comment]
@mydea not sure, but I talked with some sentry folks at a booth at a trade show, and it sounded like this would be in 9.0. If you look at releases, there is a 9.0 released 4 days ago. I have yet to try it out, but I will include an update here if 9.0 seems to fix this.

**Comment by dcramer** [comment]
You cant fully search individual events in 9, but we're exploring some prototypes internally. This isn't available today as it isn't core to Sentry's original mission (error tracking), but it'll likely be exposed in numerous ways later this year.

**Comment by mydea** [comment]
That's great to hear! Looking forward to more information later this year :)

**Comment by simzen85** [comment]
+1

**Comment by youcandanch** [comment]
@dcramer I'm curious, since we're running into an issue similar to #6519. Getting a list of issues associated with a user is pretty trivial from the API, but actually getting the _specific event_ to see specifics on the actual occurrence seems like it can't be done at the moment. This is a much narrower case than the OP's presenting, but I figured it was close enough to hop on here. Any idea if any of the prototypes y'all are playing around with might hit this case? 

Either way probably gonna clone down and play with https://github.com/getsentry/sentry/blob/c269e6cbb41bf4e22ad4c9fe633d01ea7cb8c549/src/sentry/api/endpoints/project_events.py#L23 tonight, since it'll be good learning regardless. Just figured I'd ask. Thanks as always.

**Comment by dcramer** [comment]
@youcandanch we're fixing this right now (literally). I wouldn't bother with trying to make it more available with the existing code. It's going to be built on top of our newer search infra which can answer these questions much more meaningfully. Likely will be on SaaS by december.

**Comment by youcandanch** [comment]
Freaking love y'all. Thanks, @dcramer!

**Comment by jhurwitz** [comment]
Excited for the new search infra! Any updates on the ETA?

**Comment by dcramer** [comment]
@jhurwitz about to go into prod for sentry.io for all customers (that are on current generation plans) - likely by Monday. Otherwise if you're on current gen plans you can just tick Early Adopters in settings and you'll get it today.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
