### ISSUE TITLE
Sorting is broken on the performance page

### ISSUE THREAD

**Issue by SurenNihalani** [getsentry/sentry#51410]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to performance page and sort by p50

### Expected Result

Sortability by the actual time and not unguessable sort order

### Actual Result

<img width="88" alt="image" src="https://github.com/getsentry/sentry/assets/1093911/e6351ef2-5961-422e-a67a-29e778aa6b47">

### Product Area

Performance

**Comment by silent1mezzo** [comment]
Hey @SurenNihalani, are the first two transactions starred (key transactions). From the screenshot it looks like it is ordered by p50 but the first two transactions are key transactions which are always put before non key transactions. This is definitely a confusing part of the application though when you're expecting something different.
