### ISSUE TITLE
Ability to exceed 100 alert issues per project

### ISSUE THREAD

**Issue by sentryadam0000345** [getsentry/sentry#51422]
### Problem Statement

For multiple teams sharing a project, the total number of alerts per project can easily exceed the 100 alert limit.  

### Solution Brainstorm

Differentiating and having a higher limit for the rules that are not as resource intensive, for example alert rules that query snuba can be expensive

### Product Area

Alerts

**Comment by wedamija** [comment]
The reason we have this limit is to prevent overuse of expensive rules that query snuba. If we want to raise it, then we can split rules into two buckets, one for rules with expensive snuba queries and one without. We can then have separate limits, so we'd allow up to 100 expensive queries, and 200 inexpensive for 300 total.

We already differentiate between cheap/expensive queries here: https://github.com/getsentry/sentry/blob/014c409e6b2eb5e8d9d4b2c0e0ba7051f7300929/src/sentry/rules/processor.py#L190-L194. This is used to prioritise processing the faster conditions more first so we can exit early and skip the more expensive conditions if they're unnecessary. We just need to extract this logic into a separate function and use it to bucket rules here: https://github.com/getsentry/sentry/blob/014c409e6b2eb5e8d9d4b2c0e0ba7051f7300929/src/sentry/api/endpoints/project_rules.py#L64-L71
