### ISSUE TITLE
Additional `HEALTH_CHECK_GLOBS`

### ISSUE THREAD

**Issue by qqii** [getsentry/sentry#51439]
### Problem Statement

Our health check uses `/health-check/` instead of one of the existing globs.

https://github.com/getsentry/sentry/blob/e49a8136373899af7d78014ad9429af7e5795336/src/sentry/dynamic_sampling/rules/biases/ignore_health_checks_bias.py#L14-L22

### Solution Brainstorm

Add additional health check globs (`*health-check*`). Even better would be to allow us to customise this list.

### Product Area

Other

**Comment by brentc** [comment]
Hi @qqii thanks for the report. Work is currently being done on inbound filters for health checks. You can comment/follow along here: #46731. Closing this request as a duplicate.
