### ISSUE TITLE
Don't show escalating popovers for new orgs

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#51431]
The popovers intended to help users understand archive and escalation on the issue stream and issue details should not be displayed for new organizations.  An example of a popover is here:
![Image](https://github.com/getsentry/sentry/assets/1660873/cc12f20e-88eb-47b6-8653-b89ebb2f39c6)

**Comment by scttcper** [comment]
we'll use july 5th our GA date to determine who doesn't see it.
