### ISSUE TITLE
Improve Project Redirect on "Show Issues" 

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#51488]
### Problem Statement

After creating a new project and clicking on "Show Issues," users are redirected to the Issues tab. However, the current behavior is that their default/first project is shown instead of the project they just created. Consequently, users become confused as to why they are not seeing the logs they expect. It is only after checking the menu bar that they notice the wrong project is being selected.

### Solution Brainstorm

Instead of automatically redirecting users to the default/first project, users could be redirected to the project they just created.

### Product Area

Projects

**Comment by MichaelSun48** [comment]
This no longer appears to be an issue from my testing - feel free to reopen if there are new repro steps.
