### ISSUE TITLE
Race condition in apiSource causes auto-complete results to get clobbered

### ISSUE THREAD

**Issue by russellp17** [getsentry/sentry#51532]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. open `/issues/` and choose a tag to search for that has a lot of results, e.g. username
2. type out the first few characters of a query relatively quickly

### Expected Result

The auto-complete results should be populated with results that are filtered to the first few characters typed out. e.g. if you type out "abc", the auto-complete results should all contain the string "abc"

### Actual Result

In reality, there is a race condition where previous queries can clobber later ones. The results of the query _may_ contain non-relevant results. Since this is a race condition it's non-deterministic

I'm fairly sure the bug is in this file: https://github.com/getsentry/sentry/blob/dcc464e15d5c134371a4f140c710834bf8b8f59d/static/app/components/search/sources/apiSource.tsx

`doSearch` is invoked in `UNSAFE_componentWillReceiveProps` and kicks off a new search whenever the query change (with some debouncing in theory). It searches asynchronously and then updates the state after it is completed.

But there is no logic to cancel an in-progress search when a new one begins, so you get situations where:
- search A begins with initial query
- search B begins with updated query
- search B completes and sets state
- search A completes and overwrites the state with results that are no-longer relevant

### Product Area

Issues

**Comment by JLuse** [comment]
Support ticket for reference: https://sentry.zendesk.com/agent/tickets/89069

**Comment by roggenkemper** [comment]
thanks for bringing this up! the auto-complete results should definitely be better.

**Comment by mrduncan** [comment]
Closing this for now as we have made significant improvements to our search experience recently, please reopen if you're able to reproduce.
