### ISSUE TITLE
Newer Chrome Version string is treated as IP address

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#51569]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When  "Prevent Storing of IP Addresses" option is turned on sometimes the Chrome version string as an IP address.

It looks like it only happens for [newer chrome versions](https://developer.chrome.com/blog/user-agent-reduction-android-model-and-version/. ) where the minor version is omitted from the user agent. In Issue Details under Headers -> User-Agent rather than showing for example Chrome 113.0.0.0 what is shown is  Chrome/[ip]. I've provided a screenshot of a version of Chrome IP showing and one not showing when the "Prevent Storing of IP Addresses"  is turned on 
<img width="767" alt="Screenshot 2023-06-23 at 9 35 04 PM" src="https://github.com/getsentry/sentry/assets/100724053/76f948d1-e361-477b-bf56-9b584a7e2fe4">
<img width="774" alt="Screenshot 2023-06-23 at 9 35 15 PM" src="https://github.com/getsentry/sentry/assets/100724053/31f28525-2738-494f-b17e-994948cce4e7">

 

### Expected Result

Show Chrome version for example in Headers -> User Agent  Chrome 113.0.0.0

### Actual Result

Hides Chrome version and instead shows Chrome [ip]

### Product Area

Issues

**Comment by roggenkemper** [comment]
thanks for flagging this! the team is already looking at it and it is being tracked in https://github.com/getsentry/relay/issues/1826

**Comment by mrduncan** [comment]
Closing this as https://github.com/getsentry/relay/issues/1826 has been resolved.
