### ISSUE TITLE
Design: SourceMaps Setup - In-Product Guide

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#51583]
**Problem**: Our overall goal is to increase the % of issues with source maps (and thus readable stack traces), in order to increase the value customers can get from our Issues product. We are currently working on technical enablers to improve the robustness of the system, but this will not improve the ease of setup - customers need more guidance than the docs.

**Solution**: Offer a one liner to set up source maps using the [new source maps wizard](https://github.com/getsentry/sentry-wizard/issues/289) in the new org onboarding and new project creation flows.

Draft user flow: [Figma](https://www.figma.com/file/NZX0hEUtVH9FLcJRm8gvkg/Source-Maps-%2B-New-Auth-Token?type=design&node-id=579-1425&mode=design&t=jU8CKBorgo4V4SPy-4)

**Acceptance criteria:**
- the instructions are in the new customer onboarding & new project creation flows
- the user can choose between the one-line wizard and the manual setup instructions
- the user has an easy way to verify that his source maps setup is correct
- in case of issues the user is directed to some troubleshooting resources

**Comment by Jesse-Box** [comment]
@matejminar 

@ale-cota and I discussed the user flow at length yesterday. To progress with the design ticket, we need to demo the npm/yarn command to learn the edge cases

**Comment by ale-cota** [comment]
Duplicates https://github.com/getsentry/sentry/issues/52068
