### ISSUE TITLE
Internal error when trying to add AWS Integration

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#51594]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Organisation Settings -> Integrations -> AWS Lambda
2. Click Add Installation

The issue in Sentry can be found here: https://sentry.sentry.io/issues/4271176351/events/cf1f1685a186437c93a30613ddd54b5e/?project=1

### Expected Result

Integration is installed

### Actual Result

Internal server error appears in a new window:

<img width="589" alt="Screenshot 2023-06-26 at 14 35 10" src="https://github.com/getsentry/sentry/assets/25980868/76d9134a-2c9f-4a78-9f25-06cd1ca82dfe">

### Product Area

Settings - Integrations

**Comment by hermanlintvelt** [comment]
Thanks for logging this. Its quite important for us to try out this AWS Lambda integration in Sentry.

**Comment by scefali** [comment]
@hermanlintvelt We've identified the error and are working on a fix

**Comment by hermanlintvelt** [comment]
@scefali thanks! Just ping me if you want me to try it out ;-)

**Comment by estahn** [comment]
@hermanlintvelt I reported this issue initially and it appears to be resolved. Now I'm questioning if there is any additional value in using this over the django/python/pip module?

**Comment by scefali** [comment]
@hermanlintvelt I think this is fixed, can you try again?

**Comment by hermanlintvelt** [comment]
@scefali yes, this is fixed, thanks. The value it adds is that I could connect now a number of lambdas that are not yet integrated with the sentry sdk. We'll have to first make code changes to use the other approaches.

**Comment by iamrajjoshi** [comment]
Thanks for the report, seems like the issue was resolved, so closing now! Feel free to reach out if the problem exists.
