### ISSUE TITLE
Searching related events for tags does not seem to work

### ISSUE THREAD

**Issue by lesteenman** [getsentry/sentry#5160]
In the list of related events of an issue, we want to search for a specific tag, such as a browser (or in our case, a custom tag). However, this does not seem to work.

Text entered in the search field only seems to search for contents in the event. Searching for tags (e.g. "Browser:Chrome" or variations thereof) yields no results.

This is especially an issue for us because, when searching for a specific tag in the full list of events, clicking a search result gives the general page of that issue, not the specific event (with the tag) you searched for. Therefore, looking up an event with a specific tag seems impossible at the moment.

We are running Sentry version 8.15.0.dev0.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
