### ISSUE TITLE
Miss some result in search on level

### ISSUE THREAD

**Issue by vahid-amintabar** [getsentry/sentry#5161]
My project in sentry has 6 issues with level of fatal. When i searched for "level:fatal", I received only 2 issues. Is there any problem with sentry search?
All of my issues have level in their tags.
I'm using self hosted sentry 8.11.0

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

I think Sentry v10+ solves search in a pretty satisfactory level with Snuba though.
