### ISSUE TITLE
U2F support in Firefox

### ISSUE THREAD

**Issue by minus7** [getsentry/sentry#5164]
U2F is supported in Firefox using [this addon](https://addons.mozilla.org/en-US/firefox/addon/u2f-support-add-on/). Unfortunately, even with this addon installed I get the message about using a browser lacking U2F support. For reference, Google, Github and Gitlab do support Firefox there and it would be nice to see support in Sentry too.

**Comment by mikecmpbll** [comment]
compatibility test should not check browser version, but instead the presence of u2f libs.

**Comment by chris-morgan** [comment]
Firefox Nightly now has u2f support behind an about:config flag, and it’s currently expected to land in Firefox 58 (scheduled for release around 2018-01-16). It would be good to get this working; then I’d actually _use_ 2FA.

I think Sentry is using `u2f-api` NPM package; I filed https://github.com/grantila/u2f-api/issues/3 on it.

**Comment by chris-morgan** [comment]
u2f-api 0.1.0+ now support the `u2f` global. Upgrade to that and U2F should start working in Firefox Nightly with the appropriate about:config flags set.

**Comment by benvinegar** [comment]
Firefox Quantum [now natively supports U2F](https://www.yubico.com/2017/11/how-to-navigate-fido-u2f-in-firefox-quantum/). We should revisit this.

**Comment by minus7** [comment]
U2F does work for https://sentry.io/auth/login/ in Firefox 57 already. (And thankfully you don't need to enable OTP first to enable U2F 👍; although you can view recovery codes when already being logged in without having to use your second factor, so anyone that finds your logged-in account can grab those codes)

**Comment by salasrod** [comment]
Is this still on the roadmap? Sentry.io does not work for me with Firefox 60.0.2 with U2F enabled.

**Comment by billyvg** [comment]
@salasrod what error are you getting, we're using `u2f-api@0.2.3`, so should have firefox support.

**Comment by salasrod** [comment]
@billyvg, I get an internal server error when I try to log in through the U2F login page.

**Comment by ELLIOTTCABLE** [comment]
Same here; still occurring in FF 62. `)=`

**Comment by salasrod** [comment]
I've been able to log in with an actual Yubikey with no error, the error happens when I use a key that is not Yubikey, specifically this one: https://www.ftsafe.com/products/FIDO/Multi

**Comment by ELLIOTTCABLE** [comment]
Odd; this occurs with a brand-name (USB-C) Yubikey 4, for me

**Comment by acdha** [comment]
U2F support has worked well in Firefox a long time using the `security.webauth.u2f=true` setting. On April 4th they announced that this is tracking to be on by default in Firefox 67, which should ship on May 14th:

https://blog.mozilla.org/security/2019/04/04/shipping-fido-u2f-api-support-in-firefox/

**Comment by BYK** [comment]
Our goal is to switch to WebAuthn which will make this compatible with Firefox and other browsers too.

Thanks a lot for your patience. 🙏🏻

**Comment by chris-morgan** [comment]
> "A weed is but an unloved flower."

I just asked my sister, a gardener. She disagrees.

This isn’t the blunt instrument that is the **stale** bot (which I have never once had a positive experience with), but I still dislike bots like this because in my experience they consistently do more harm than good. I’m guessing here that this is a fairly new experiment. Probably everything that was already assigned to anyone (like this issue) should be labelled “Status: Accepted”.

**Comment by minus7** [comment]
The original issue has long been fixed in u2f-api, so I'll close this.
