### ISSUE TITLE
Replay: Mutation breadcrumb should lead to the docs

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#51656]
When the Sentry SDK detects multiple mutations, it creates a breadcrumb to warn the developer.

![image](https://github.com/getsentry/sentry/assets/1633368/cddc4fc9-4820-4f8d-92eb-059f33ad3115)

That's documented here: https://docs.sentry.io/platforms/javascript/session-replay/configuration/#mutation-limits

Additionally, we documented in our troubleshooting page (https://docs.sentry.io/platforms/javascript/session-replay/troubleshooting/#i-see-the-message-a-large-number-of-mutations-was-detected-n-this-can-slow-down-the-replay-sdk-and-impact-your-customers) this crumb. In the event a confused user looks it up.

This workflows assumes a confused user will look it up (google it or search our docs). We believe this crumb albeit valuable can be confusing to users ("what should I do") hence we should be linking to the docs directly from the breadcrumb.

**Comment by ryan953** [comment]
**Task:** link from that breadcrumb to the `/config` page.
