### ISSUE TITLE
Send workflow notifications (comments) via Slack to individual users

### ISSUE THREAD

**Issue by estahn** [getsentry/sentry#51681]
### Problem Statement

It is hard to distinct between emails reporting issues and comments on issues. Therefore those comment may not get read in time.

### Solution Brainstorm

1. The comments should be sent to alternative channels, in our case to individuals in Slack (our comms tools). The Slack integration would require user mapping similar to the GitHub integration. Possibly there is some auto-mapping magic via email address.

2. Another solution could be threaded responses on the already reported issues in slack. A comment with mention `@xxx` would be added in the thread.

Solution 2 might be preferable as this would expose comments to a wider audience as well as notify the individual. 

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
Hi @estahn - Sending workflow notifications to Slack is already possible. Your team members can update the personal notification settings to direct workflow alerts to them. Please find more details in our [docs](https://docs.sentry.io/product/alerts/notifications/notification-settings/#workflow) here


Your team members can also link their slack identity to Sentry using these [instructions](https://docs.sentry.io/product/integrations/notification-incidents/slack/#linking-your-slack-and-sentry-accounts)
