### ISSUE TITLE
Use the Generics Metrics Backend to create a new dataset

### ISSUE THREAD

**Issue by NisanthanNanthakumar** [getsentry/sentry#51757]
## Objective:
We will have to create a new metric for the Generic Metrics Backend. Use this doc: https://www.notion.so/sentry/Creating-a-New-Use-Case-ID-for-the-Generic-Metric-Pipeline-Locally-d9bdeaac34c14ea88f1ff0f9dbd6e90a

You will need to create a new `UseCaseId`

Example PR for emitting counter metrics: https://github.com/getsentry/sentry/pull/47897/files#diff-4f84287e9286e7eb52a61d789db46acfb6534f829fedd047d150dfcb13631437

**Comment by rachrwang** [comment]
Closing since we aren't working on this anytime soon
