### ISSUE TITLE
Creating issue w/JIRA integration causes description dialog to disappear

### ISSUE THREAD

**Issue by mikellykels** [getsentry/sentry#5177]
When creating a JIRA ticket from Sentry, creating a new line or typing a lot in the description will cause the dialog modal to disappear.

To reproduce the issue:

1) use an ipad. 
2) open a sentry event. 
3) click the JIRA button and create an issue 
4) type lots and lots into the description field (especially new lines)

![img_0001](https://cloud.githubusercontent.com/assets/20312973/24572064/80d72158-162a-11e7-851c-78b4d47d5c98.PNG)

**Comment by benvinegar** [comment]
We've since relaunched our [Jira integration for Sentry](https://blog.sentry.io/2018/09/10/atlassian-jira-bitbucket-update), and I can't reproduce this in the new version. Closing.
