### ISSUE TITLE
Sentry cloud in other regions?

### ISSUE THREAD

**Issue by fzyzcjy** [getsentry/sentry#51859]
### Problem Statement

Hi, I wonder whether Sentry has a plan to host the sentry cloud in regions other than https://help.sentry.io/account/legal/where-are-your-servers-located/? It is because in some countries, if you are sending data to other countries, you need to do much extra paperwork.

If no, I may have to self-host Sentry, or even leave Sentry and use other bug-reporting solutions :( I hope I can use the sentry cloud solution.

### Product Area

Unknown

**Comment by dashed** [comment]
@fzyzcjy Please see: https://github.com/getsentry/sentry/discussions/49564

**Comment by fzyzcjy** [comment]
@dashed That looks great! However, is there a plan to add a data center in China? Since both EU and US are foreign countries for users in China and still require all paperwork.

**Comment by scefali** [comment]
@fzyzcjy Google is not allowed to operate in China and Sentry is on GCP which is blocked there. One thing you might be interested in is our Relay option (https://docs.sentry.io/product/relay/) which you can host yourself which then relays the events to Sentry SaaS.

**Comment by fzyzcjy** [comment]
@scefali Ah I see the google cloud problem :( The relay is not an option, because even if the data is sent to relay in my server firstly, the relay has to send data to sentry cloud later on, so it is still "send privacy data to outside".
