### ISSUE TITLE
Filtering errors by tags return issues with 1000s of errors without the given tag

### ISSUE THREAD

**Issue by marandaneto** [getsentry/sentry#51862]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Search for the tags `task_name:sentry.tasks.app_store_connect.dsym_download` AND `tags[project]:$projectId` on the Issues page.

Discover works just fine, it's just an issue on the Issues page.

### Expected Result

Only issues with the given tags should be returned and it should be possible to find the events with the tag within those issues. The first half of that (finding the correct issues) probably already works, but it's impossible to tell because of the second half (the fact that there's no way to find the relevant events). 

### Actual Result

The result returns issues with 1000s of errors, and not all those errors contain the given tags, maybe one of those errors contains the given tags, but not all (the majority actually), making it impossible to find the desired errors. Not only does this potentially make the search results seem incorrect (even if they're not), it also means said results are not actually particularly useful.

### Product Area

Issues

### Link

sentry.sentry.io

### DSN

Sentry SaaS itself

**Comment by lobsterkatie** [comment]
FYI, @marandaneto, I added onto your descriptions a bit, to make it clearer what the heart of the problem is. Hope that's okay!

**Comment by malwilley** [comment]
FYI for anyone coming across this issue, we _do_ have an existing UI that helps find the specific events matching the search filters. If you hover over the event totals, there is a tooltip that appears with links to discover (in this screenshot, it would be the `328` number):

<img width="300" alt="CleanShot 2023-07-05 at 15 50 42@2x" src="https://github.com/getsentry/sentry/assets/10888943/c4c73cc9-e81d-4318-8f64-e176580b21d1">

But admittedly there could be some work done here to make the UI less confusing or easier to find.

**Comment by marandaneto** [comment]
> that's

Thank you.
