### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by keenahn** [getsentry/sentry#51895]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1.Go here `/settings/integrations/github/` and install the integration
2. Github admin for the repo approves it

### Expected Result

for the integration to work

### Actual Result

![20232329-143859](https://github.com/getsentry/sentry/assets/283603/ce9e4396-9fad-4d8b-9bdb-96fdbf176d3b)
![image](https://github.com/getsentry/sentry/assets/283603/f7e468f5-9924-41ae-94ec-ab39dff7f41a)

### Product Area

Settings - Integrations

**Comment by brianthi** [comment]
Hi @keenahn, this screen is asking to update access instead of add. I suggest removing the Sentry app on the Github side and try again. If your problem persists, then our support team is best equipped to help you out https://help.sentry.io/.
