### ISSUE TITLE
Creating a sample event fails to be stored

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#51904]
This issue may be revealing really worse underlying issues. 

[This project](https://sentry.sentry.io/issues/?groupStatsPeriod=auto&project=4505445599936512&query=is%3Aunresolved+is%3Afor_review+assigned_or_suggested%3A%5Bme%2C+my_teams%2C+none%5D&referrer=issue-list&sort=inbox&statsPeriod=90d) requested sample events three times. The group was created but the events did not make it into Snuba.

You can see the group in the issue stream (stored in PG) [1]. Loading the issue will show "sorry, the events for this issue could not be found" [2]. You can see that we count the events but they're not stored [3].

Action items:
- [ ] Troubleshoot what happened
- [ ] Create metric and alert for this

[1]
<img width="759" alt="image" src="https://github.com/getsentry/sentry/assets/44410/482412d2-e440-4606-b658-93164dc41e14">
[2]
<img width="768" alt="image" src="https://github.com/getsentry/sentry/assets/44410/bcf80db1-f28e-4e99-9a9f-abf33f527fa7">
[3]
<img width="67" alt="image" src="https://github.com/getsentry/sentry/assets/44410/9a639745-8df3-45e9-82f5-98abb6afc5cb">

**Comment by barkbarkimashark** [comment]
Was able to repro this and whats curious is when I click the `create sample event` button and the issue shows up on the issue stream in the for review tab. The issue has an event count of `0/0`. 

It seems like somewhere down the event creation pipeline, the event never makes it to snuba which powers the issue search functionality for tabs that aren't `For Review`. So if we figure out why the event never gets saved, I suspect this issue will also be fixed.

I don't think this issue is specifically related to issue states and whether the feature flag is on/off.

**Comment by armenzg** [comment]
Thanks @barkbarkimashark !
I've removed the issue states milestone relation.
This is likely related to #inc-417 which we're still investigating.

**Comment by snigdhas** [comment]
The sample event creation creates 3-5 events and groups them into a new issue. Looking at the network tab, I see that the issue gets created, but the call to get the latest event (`events/latest`) 404s. It keeps retrying for a while before failing silently. 

If I get the issue ID from the request and visit the URL, I see the `Sorry, the events for this issue could not be found.` error above. 

I'll post this in discuss-ops/sns to see if anyone has insight/can help further.

**Comment by snigdhas** [comment]
We've confirmed that sample events are not making it into Snuba. The path taken to save a sample event is different than that for regular event ingestion, so this shouldn't indicate that we're dropping events elsewhere. The next step is to add logging to understand exactly where in the event save logic this is failing.

**Comment by brianthi** [comment]
https://github.com/getsentry/sentry/pull/54748 fixed this issue
