### ISSUE TITLE
.NET Modal for Project Selection

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#51903]
Similar to Java version:https://github.com/getsentry/sentry/issues/50224

Get .NET onboarding: cc @bitsandfoxes 

Wizards: 
![image](https://github.com/getsentry/sentry/assets/1633368/a5d9e7d7-a8c8-48f2-a3b1-e42e09e15044)

order suggested:

aspnet core
aspnet
maui
wpf
winforms
xamarin
uwp
gcpfunction
awsfunction
standard csharp

**Comment by Jesse-Box** [comment]
@matejminar @priscilawebdev

Below is the SVG art required to complete this modal
![art-dotnet-frameworks](https://github.com/getsentry/sentry/assets/6508377/99b2f314-a559-488d-a162-4a6301be2d2e)

I know it looks strange, having two of the same logos on there, but if you look at all their social profiles, they don't have separate logos for their various tooling

**Comment by priscilawebdev** [comment]
I understand your reasoning behind your decision, but I agree that it does appear unusual. Have you considered aligning the left icon with the Maui styles? We could make it more blueish 

![image](https://github.com/getsentry/sentry/assets/29228205/78cf5592-faa7-4ed5-b32a-5d449d03d565)

**Comment by Jesse-Box** [comment]
I would like to avoid making logos for `aspnet` or any SDK which has no clear brand guidelines
