### ISSUE TITLE
Endpoint API for creating an organization

### ISSUE THREAD

**Issue by marcosalpereira** [getsentry/sentry#51924]
### Problem Statement

I would like to create an organization through the API

**Comment by brianthi** [comment]
Hi @marcosalpereira, we're very unlikely to create or support an API with the ability to create organizations. Could you describe your use case a bit more? Maybe we can help you with another way to solve the problem you're running into.

**Comment by marcosalpereira** [comment]
We are thinking of using the organization as being the divisions of our company, and as we have many divisions, we would like to fulfill requests to create them in sentry through automation. So, we would need this possibility in the Sentry API

**Comment by scefali** [comment]
@marcosalpereira You can try replicating the browser request you see here creating a new organization: https://sentry.io/organizations/new/

It's definitely not documented and not likely to be documented but I have a feeling it will just "work" if you use your user's authentication token on the API call.

**Comment by Dhrumil-Sentry** [comment]
@marcosalpereira we've added [Spend Allocation](https://github.com/getsentry/sentry/discussions/44562) and [Team level roles](https://github.com/getsentry/sentry/discussions/49028) as features to make it easier to manage multiple teams in the same Sentry organization. Would appreciate your feedback on why you don't want to have multiple divisions in the same organization

**Comment by malwilley** [comment]
Closing this issue since we don't plan on adding official support for this feature, but please follow up with additional feedback if you have any!
