### ISSUE TITLE
Activity log incorrect when escalating by user defined value

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#51963]
Any time the user selects Archive until :"For...", "Until this occurs again..." and "Until this affects an additional..." options, we should show those details when it escalates due to those reasons.  This should render the reason as it did when we had the ignore activity.  However, we should ensure if it escalates due to the new algorithm that we have those details in the activity log too.

![Image](https://user-images.githubusercontent.com/1660873/249916810-77ad30af-cdb5-4f32-b737-e60515d1740e.png)

**Comment by scttcper** [comment]
link to example https://sentry.sentry.io/issues/1957376472/activity/?project=1&referrer=escalating_activity-slack

example data passed, we should be able to say the values it exceeded correctly
![image](https://github.com/getsentry/sentry/assets/1400464/e3118e44-1517-4ef1-9723-fd1875f5b88d)

**Comment by brianthi** [comment]
Archive forever is not well described in the activity log: 
![Screenshot 2023-07-10 at 9 51 56 AM](https://github.com/getsentry/sentry/assets/1660873/3020a488-e47e-419e-a683-86e0bdf10cb8)
