### ISSUE TITLE
Subscriptions tab disappears when on Notifications tab 

### ISSUE THREAD

**Issue by mikellykels** [getsentry/sentry#5198]
When you're on the Notifications tab, the Subscriptions tab disappears:

![screen shot 2017-04-04 at 11 47 45 am](https://cloud.githubusercontent.com/assets/20312973/24681492/4fe107a8-194a-11e7-9d07-4ee926240630.png)
![screen shot 2017-04-04 at 11 47 57 am](https://cloud.githubusercontent.com/assets/20312973/24681494/51ececba-194a-11e7-8b69-edd94e846c3f.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
