### ISSUE TITLE
cannot upload error on my local env

### ISSUE THREAD

**Issue by henryzp** [getsentry/sentry#5201]
i use online，it can show error。

but i use local，it tips me：

```
Raven.config('http://9c8f5205384e4a0f957b2dce78af29a6@localhost:9000/2').install()
```

and this cannot recieve error。

compare the request，it also response a correct result。

so what the reason can it be?

how to fix it？

**Comment by dcramer** [comment]
Our issue tracker is not a support forum. Please see https://sentry.io/support/ for options.
