### ISSUE TITLE
Duplicate Event Listeners

### ISSUE THREAD

**Issue by Quantastical** [getsentry/sentry#5203]
I recently added **Sentry 8.15.0.dev0** integration into an enterprise application but had to disable it because I was noticing erratic behavior on one of my input fields, where every keypress resulted in two characters being added to my field. It is kind of a unique scenario, but from I try my best to explain.

We have a maskedTextBox from [Kendo UI](http://www.telerik.com/kendo-ui), which changes a traditional text input field into one that provides real-time masking feedback to the user. For example, a masked phone number will operate like this as the user enters in a number:

```
___-___-____
1__-___-____
12_-___-____
123-___-____
...
```

Kendo attaches an event listener to the input field to capture keypress event and do its thing. Everything works fine initially, but when I auto-populate other fields using another 3rd party tool for auto-completion called [Dashlane](https://www.dashlane.com/), I notice that the input field suddenly has two event listeners. As a result, the keypress event gets fired twice and exhibits behavior like so:

```
___-___-____
11_-___-____
112-2__-____
112-233-____
...
```

Obviously there is a lot of parts here, but when I inspect the masked input field in Chrome and look at the event listeners for that node, I can see the field has two keypress listeners. One of them originated from jQuery (which I assume is from Kendo). The other is from a library called raven.js, which I understand to be a dependency from Sentry.

I would like to use the Sentry tool, but because of this behavior, I must disable it as it is creating unexpected buggy behavior in my application. As soon as I disable Sentry, Dashlane and Kendo work in concert and the duplication of event listeners goes away.

I can provide additional insight, snapshots, etc., but I'm not familiar enough with raven.js to provide much more than what I see.

**Comment by MaxBittker** [comment]
thanks for this issue @Quantastical , this sounds like something we should look into and fix in raven-js. In the meantime, a workaround would be to configure raven to not instrument breadcrumbs automatically, or at least not for input events. Try setting `autoBreadcrumbs:false` or ```autoBreadcrumbs: {
    'xhr': true,      // XMLHttpRequest
    'console': true,  // console logging
    'dom': false,       // DOM interactions, i.e. clicks/typing
    'location': true  // url changes, including pushState/popState
}``` https://docs.sentry.io/clients/javascript/config/

**Comment by MaxBittker** [comment]
closing this in favor of the raven-js issue.

**Comment by LewisJEllis** [comment]
I'm going to close this in favor of getsentry/raven-js#947.

@Quantastical could you comment there with the version of raven-js you're using and what your raven-js initialization/setup code looks like? Also, when you remove raven-js, do you still see two event listeners on the input field, or fewer? We shouldn't be attaching any *additional* event listeners, but it's possible that another *existing* event listener would, due to our instrumentation, start to look like it comes from raven-js.
