### ISSUE TITLE
User feedback is not linked to the event

### ISSUE THREAD

**Issue by iki** [getsentry/sentry#5205]
Sentry 8.14.1

1. From issue user feedback section `/issues/NNN/user-feedback/` the user feedbacks don't link anywhere. 
  But the support needs to be able to get to the event related to the feedback `issues/NNN/events/EEE/`
  Can you link issue user feedbacks to the events related to them?

2. From top-level user feedback `/user-feedback/` the user feedbacks link to the containing issues `/issues/NNN/`, not directly to the events related to them  `issues/NNN/events/EEE/`,
  But the support needs to be able to get to the event related to the feedback. If point 1 is implemented, the support could get to the event by going to the containing issue, then to the issue user feedback section, then lookup given feedback there, and use the link to get to the related event. However, it 's not only impractical, it wouldn't be usable at all for higher number of feedbacks on one issue.
  Can you link the top-level user feedbacks directly to the events related to them?

**Comment by dcramer** [comment]
I believe this ticket is no longer valid and we've resolved the core of it.
