### ISSUE TITLE
[Alert rules] "issue is seen by more than X users in X" has incorrect details and appears inoperative

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#52050]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

**Details:**
When creating an alert rule with the  _"issue is seen by more than X users in X"_ WHEN condition, after saving the details are incorrect and do not reference the number of users.

Steps:
1. Create an alert rule:
<img width="971" alt="Screenshot 2023-06-30 at 1 59 19 PM" src="https://github.com/getsentry/sentry/assets/8451987/390a93c0-b7e9-4d83-a359-3c154bb986e6">

2. View incorrect alert details:
<img width="356" alt="Screenshot 2023-06-30 at 2 00 18 PM" src="https://github.com/getsentry/sentry/assets/8451987/e1a6ffd4-125a-45a2-9cb3-9573c0c0eb96">

3. Send issues that should fulfill the condition

### Expected Result

Alerts to be labeled with the number of users and notifications to be sent when condition is met

### Actual Result

Alerts are mislabeled and appear to not send notifications

### Product Area

Unknown

**Comment by scttcper** [comment]
This was fixed a while back.
