### ISSUE TITLE
Indicate which dashboard widgets are sampled

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#52067]
Display the "sampled" indicator next to the widget title if (all need to apply):
- the widget is using Errors + Transactions dataset
- the API response contains isMetricsData: false
- the query filter does not contain any of the following: https://github.com/getsentry/sentry/blob/bdc9f462faed8b60031d350c17d642624a9d8526/src/sentry/tasks/check_am2_compatibility.py#L142

Implementation will be similar to https://github.com/getsentry/sentry/pull/47383 (was reverted) but with added query filter condition.

Indicator and copy TBD.

Let's put this behind a feature flag a enable for sentry first.

**Comment by ale-cota** [comment]
Since we're reaching the finish line with on-demand metrics by now, it doesn't make sense to add this anymore.
