### ISSUE TITLE
Design: UI Changes to Alerts for on-demand metrics

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#52072]
**Problem**: We're reintroducing the capability for customers to create more granular alerts based on metrics. Because the actual metrics extraction only begins once the alert is saved, there is no historical data to show the customer and this must be explained in the UI.

**The feature is restricted in a first step to Business plans**, so new tags are only visible to these customers. We might want to go with a different approach where we limit the number of custom tags and offer a different number to Team vs. Business... so we don't take that option off the table, but we should offer this only for Business to start. This means we don't need to make an effort to "upsell" at the moment.

**Comment by Jesse-Box** [comment]
Marking this ticket as done, assuming that the copy is the only thing that still needs addressing.

Figma designs here
https://www.figma.com/file/81N3LMNOSSQLxpR4VoBNZn/Specs%3A-Alerts-%26-On-demand-Metrics?type=design&node-id=17%3A5756&mode=design&t=6qrCKJ77YbAB6l6c-1
