### ISSUE TITLE
Issues page - Activity counter only shows manually placed comments

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#52075]
### Problem Statement

As a developer I want to know if there is activity on the issue. But in order for the developer to see that it has to open up the activity tab first.

Problem is, that the activity counter is not being changed if an automation like jira, gh or asana make an update to the activity tab. This only happens when a user manually adds a comment 
![Screenshot 2023-07-03 at 10 38 26](https://github.com/getsentry/sentry/assets/25929053/99d9cf09-d869-4aa6-a9bb-8116a2368efa)

If you look at the screenshot you would expect that the activity counter in the left top would state 2 or 1 at least if we exclude the "first saw issue" comment. 

### Solution Brainstorm

Include all activity to the counter or have another counter with total activity if the counter is only for comments made by other developers. 

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1865) by [Unito](https://www.unito.io)

**Comment by snigdhas** [comment]
the new issue details UI displays the activity in the main issue details page. Closing this issue but please reopen if there's more we can do to improve the experience
