### ISSUE TITLE
Issues - Asana integration modal does not close when creating a new issue out of the sentry ui

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#52090]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Need Asana integration setup
2. Go to issue
3. Create asana issue through the Issue detail ui
4. Modal does not close
5. UI does not update (no X mark next to the asana integration on the linked issue)

### Expected Result

I would expect the modal to close and the UI to refresh so I have the right context.

### Actual Result

 Modal does not close
UI does not update (no X mark next to the asana integration on the linked issue)

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1866) by [Unito](https://www.unito.io)

**Comment by scefali** [comment]
Fixed
