### ISSUE TITLE
Establish deployment checklists

### ISSUE THREAD

**Issue by iambriccardo** [getsentry/sentry#52096]
We had several incidents caused by rushed implementations and deployments. In order to do so, we would like to sit down and establish deployment checklists for different kinds of changes, with the goal of trying to minimize human error.

**Comment by iambriccardo** [comment]
This discussion arose from the postmortem of INC-427 available [here](https://www.notion.so/sentry/INC-427-Source-Maps-missing-chunk-functionality-not-enabled-on-the-server-while-CLI-was-rolled-out-c6d063f4ff674852af7dcb38123d39fc).

**Comment by matejminar** [comment]
https://www.notion.so/sentry/Deployment-Check-List-b7c8e148dd094366afa15889404270e7
