### ISSUE TITLE
Can't possibly create project. The project you were looking for was not found

### ISSUE THREAD

**Issue by myrubapa** [getsentry/sentry#5222]
I can't create project after install sentry return "The project you were looking for was not found." in header "Background workers haven't checked in recently. This is likely an issue with your configuration or the workers aren't running." but is running.  I'm try  install with python and docker same issue 
Sentry 8.15.0
Docker version 17.04.0-ce, build 4845c56
I setup sentry with https://github.com/getsentry/onpremise

![sent3](https://cloud.githubusercontent.com/assets/1535825/24917205/d77c42bc-1ef5-11e7-946a-cbfa9a8be36e.png)

![sent](https://cloud.githubusercontent.com/assets/1535825/24916896/f05c4d82-1ef4-11e7-9ae8-f2a9e34e203f.png)

![sent2](https://cloud.githubusercontent.com/assets/1535825/24917005/3ce82450-1ef5-11e7-9fa5-9c63f0fe9b01.png)

**Comment by dcramer** [comment]
https://sentry.io/support/
