### ISSUE TITLE
Alert emails do not respect group subscription settings.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#5223]
You can't unsubscribe from alert emails for a specific issue. This is because [`NotificationPlugin.get_sendable_users` is only passed the project](https://github.com/getsentry/sentry/blob/c3ff532237118ecfcd915949e2d6d7d193f18abe/src/sentry/plugins/bases/notify.py#L116-L149), and not the group. We should extend this to check the `GroupSubscription` status as well.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
