### ISSUE TITLE
Create an API which will force run auto-assignment

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#52318]
We built a feature which prevents auto-assignment of an issue which was manually assigned.  This is to prevent us from incorrectly auto-assigning an issue when it has been determined that there is a better assignee.  This however can lead to an issue where if issues were accidentally assigned in bulk, that we don't have a way to allow auto-assignment to fix it.  

AC:
- Given a list of group IDs, force auto-assignment to run based on auto-assignment configuration for that project.  
- Limit this API to 100 group IDs per request
- Implement a rate limit of one request per minute per org

**Comment by jangjodi** [comment]
Add API to Issues Owners Triage internal doc once merged in
