### ISSUE TITLE
Replay event timeline on full screen

### ISSUE THREAD

**Issue by bradleytaftsmith** [getsentry/sentry#52323]
### Problem Statement

I want to see the event timeline when in full screen of a replay, so I can see the remaining and past event activity

### Solution Brainstorm

Add event timeline to full screen UI for for replays, so they will be available when scanning many replays on full screen

### Product Area

Replays

**Comment by bruno-garcia** [comment]
Thanks for raising @bradleytaftsmith . We have been discussing a 'theater mode' which would take more space in the screen and include some tools around it. We'll keep your suggestion here to consider when we tackle that.

**Comment by c298lee** [comment]
Done with https://github.com/getsentry/team-replay/issues/199
