### ISSUE TITLE
[Replay] Replay do not visible in UI

### ISSUE THREAD

**Issue by kolesoffac** [getsentry/sentry#52337]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Self-hosted/on-premise

### Which SDK are you using?

@sentry/vue

### SDK Version

7.57.0

### Framework Version

Vue 2.x

### Steps to Reproduce

0) Installed self hosted Sentry 23.3.1 and @nuxtjs/sentry 7.3.1
1) Activate Replays integration in code
2) Set replaysSessionSampleRate=0.5 and replaysOnErrorSampleRate=1
3) After some actions throw error

### Expected Result

Show this replay in Replays section in UI and show Replays tab in event error.

### Actual Result

Don't show this replay in Replays section in UI and don't show Replays tab in event error.

I have log (debug=true):
Sentry Logger [log]: Integration installed: Replay
Sentry Logger [log]: [Replay] Using compression worker

In network tab of devtools i see payload in outgoing requests:
...
{"type":"replay_event"}
...
{"type":"replay_recording","length":331}
...

All events in Sentry have tag relayId.

**Comment by ryan953** [comment]
@kolesoffac make sure you self-hosted py config has both of these flags enabled:
```
  "organizations:session-replay": True,
  "organizations:session-replay-ui": True,
```
Based on the screen shot I can see that the the 2nd flag is already on.
The first flag however controls ingestion. So if your SDK is setup correctly (it seems like it based on the devtools network tab activity) then this will tell the server that it's ok to accept replay data and save it to the database.

If both flags are already set to True, then you should take a look at the server logs and see if all the backend services and workers have started correctly and have no errors. This type of debugging depends more on how you've deployed things, and the community is the best place to get help and tips on that.
