### ISSUE TITLE
how i set source map upload filename if my js file have multiple path（not hostname） ?

### ISSUE THREAD

**Issue by liuqipeng417** [getsentry/sentry#5234]
Hi:

Because my project's js file is in user local env（not in server）, and everyone's local path is different, the `~` char just omit protocal and hostname , but i want to **omit some path**, if there is anthoer config or solutions ?

```
// ths js path maybe like that:

file:///C:/Users/{username}/AppData/html/taskpane/js/manifest.js

```

**Comment by liuqipeng417** [comment]
ok, i find the solution: https://gist.github.com/danharper/a89685cc1028759345b8

for the raven-js v3.13.x

`
  dataCallback(data) {
    var normalize = function(filename) {
      const splitArray = filename.split('/');
      return splitArray[splitArray.length - 1];
    };

    data.exception.values[0].stacktrace.frames.forEach(function(frame) {
      // you can change the filename that you want
      frame.filename = 'www/' + normalize(frame.filename);
    });

    data.culprit = data.exception.values[0].stacktrace.frames[0].filename;

    return data;
  }
`

**Comment by liuqipeng417** [comment]
related issue: [#2708](https://github.com/getsentry/sentry/issues/2708)

**Comment by castlec** [comment]
@liuqipeng417 it appears as though this issue can be closed. Can you confirm?
