### ISSUE TITLE
2FA email Mandatory: Enable Two-Factor Authentication has none URL

### ISSUE THREAD

**Issue by sdzhong** [getsentry/sentry#52369]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Enable 2FA for the Sentry org (this sends invitation emails like `[org name] Mandatory: Enable Two-Factor Authentication`)
2. The email (see attachment) has button `Enable Two-Factor Authentication` with embedded url `none`.
![image](https://github.com/getsentry/sentry/assets/89550162/5ac989f8-6a3d-4225-ac29-6a41cf382868)

### Expected Result

The button should have a proper url to enable 2FA and reinstate access.

### Actual Result

The button `Enable Two-Factor Authentication` has embedded url `none`.
![image](https://github.com/getsentry/sentry/assets/89550162/5ac989f8-6a3d-4225-ac29-6a41cf382868)

Note: This was resolved by resending the invitation.

### Product Area

Settings - Auth

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1873) by [Unito](https://www.unito.io)

**Comment by schew2381** [comment]
Hi, this is a duplicate issue so I'm closing this for now. We have a fix in the works and future updates will be posted to https://github.com/getsentry/sentry/issues/52117
