### ISSUE TITLE
SentryNetworkTracker.m:5:9 'SentryDSN.h' file not found

### ISSUE THREAD

**Issue by wmalloc** [getsentry/sentry#52378]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

In a case sensitive Filesystem file is missing because the file is named `SentryDsn.h`. 

### Expected Result

To be able to import the correct file

### Actual Result

Not able to import the header

### Product Area

Releases

**Comment by lobsterkatie** [comment]
Closing as a duplicate of https://github.com/getsentry/sentry-cocoa/issues/3115.
