### ISSUE TITLE
Use project names instead of slugs in weekly org report

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#5237]
In the Weekly Report (stats about your projects delivered every week), we list projects using their slug and not their proper formatted name.

At least one user has commented this is confusing, because the slug is not commonly referred to in the app or in other emails (where the proper name is used).

![image](https://cloud.githubusercontent.com/assets/2153/25022566/2f42ce02-204b-11e7-93a9-0e5e787abb8f.png)

**Comment by dcramer** [comment]
I'd like to deprecate project names and move towards slugs entirely. It makes a lot of things less confusing, and GitHub has proven its good enough.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
