### ISSUE TITLE
No hash derived for frames with only `function` properties

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#5239]
A user doing custom client development is passing us `Stackfrace` interface frames that only possess `function` and `in_app`, and observing that these events are all being merged together as one issue.

Taking a look at the `get_hash` [implementation](https://github.com/getsentry/sentry/blob/master/src/sentry/interfaces/stacktrace.py#L360), we believe [this branch](https://github.com/getsentry/sentry/blob/master/src/sentry/interfaces/stacktrace.py#L402) is hit which causes `get_hash` to bail before actually adding the `function` value on line 413 below.

Needs more investigation / a test case.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
