### ISSUE TITLE
Use different color for empty buckets in histogram graph

### ISSUE THREAD

**Issue by kerbylane** [getsentry/sentry#5241]
Sometimes when looking at the bar graphs of event counts, if some buckets/bars have a very large number, it can be difficult to distinguish other buckets which have small values, close to 0, from buckets that are at 0. For instance, in the example from the attachment there are 275 events in one bucket. The most recent 2 buckets have 0 and 9 events. But without hovering over them I can't tell that either is at 0. 

It would be helpful if the 0-count buckets were in a different color to help distinguish between these 2 cases.

![screen shot 2017-04-13 at 3 38 01 pm](https://cloud.githubusercontent.com/assets/4228228/25028640/b8ef7e06-206a-11e7-9ccc-7f2ca5908413.png)

**Comment by MaxBittker** [comment]
this is a good point! i'll play with some takes on it.

**Comment by MaxBittker** [comment]
(haven't had time quite yet but still going to get to this)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
