### ISSUE TITLE
SolidJS support

### ISSUE THREAD

**Issue by amirzahavi** [getsentry/sentry#52418]
### Problem Statement

We use [SolidJS](https://www.solidjs.com/) in our projects and would like native SDK support for the Sentry product.
currently, we have to use the vanilla JS SDK.

### Product Area

Unknown

**Comment by AbhiPrasad** [comment]
Hey @amirzahavi thanks for writing in! We are currently supporting SolidJS here: https://github.com/getsentry/sentry-javascript/discussions/5552

Please react and leave comments on that GH issue, that helps us prioritize this work accordingly.
