### ISSUE TITLE
Triggering Configure SDK Button for SDK "React" results in 400

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#52427]
### Screenshots
![Image](https://user-images.githubusercontent.com/6508377/251694715-63039d8a-898c-42d3-ad6f-1c25cb1c57f5.png)

### Console
`POST https://jesse-box-dr.sentry.io/api/0/teams/jesse-box-dr/jesse-box/projects/ 400
Bad Request`

**Comment by priscilawebdev** [comment]
it shall be working again! 😉
