### ISSUE TITLE
Slack integration -- tags first appear in the Slack posts but then disappear

### ISSUE THREAD

**Issue by nyccto** [getsentry/sentry#5242]
Using Sentry 8.16.0.dev0 and using the Slack integration. The service seems to work fine expect that it doesn't include tags all the time. It will include tags the first time I setup the tags to be included in the Sentry web app settings but then will not show in the following Slack posts. I'm not sure if there is a pattern, I tried editing the tag names and updating the settings, it will sometimes include the tags once in the post but then will stop in the following posts right away.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
