### ISSUE TITLE
SAML assertion error

### ISSUE THREAD

**Issue by seanbrowntruera** [getsentry/sentry#52455]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Visit Settings > Auth and select Active Directory
Use Metadata URL
Use the following claims for the Map Identity Provider Attributes configuration
```
IdP User ID http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name

User Email http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress

First Name http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname

Last Name http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname
```
Microsoft is indeed sending the claims that the error is describing.

This is the same issue as this ticket https://github.com/getsentry/sentry/issues/24248 but now I'm seeing the same error using the ```name``` attribute instead of ```nameIdentifier```

### Expected Result

Authenticated User

### Actual Result

```Authentication error: Failed to map SAML attributes. Assertion returned the following attribute keys: 'http://schemas.microsoft.com/claims/authnmethodsreferences', 'http://schemas.microsoft.com/identity/claims/displayname', 'http://schemas.microsoft.com/identity/claims/identityprovider', 'http://schemas.microsoft.com/identity/claims/objectidentifier', 'http://schemas.microsoft.com/identity/claims/tenantid', 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname', 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name', 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname'```

### Product Area

Sign In

### Link

 https://sentry.io/organizations/truera/

### DSN

https://694c67e874f240d29fbeaafcb4cbd65a@o4504204189302784.ingest.sentry.io/4504207280504832

**Comment by schew2381** [comment]
Hi, the error keys are outlining which ones are available. It appears that `User Email http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress` is missing from that list. Can you ensure that you have email set in your [Active Directory Claim](https://learn.microsoft.com/en-us/azure/active-directory/develop/saml-claims-customization)?

**Comment by seanbrowntruera** [comment]
<img width="461" alt="Screen Shot 2023-07-10 at 3 20 06 PM" src="https://github.com/getsentry/sentry/assets/118211263/324c30b0-4e10-430b-85a1-33a3c44bf8ed">


 it is set yes

**Comment by schew2381** [comment]
This appears to be an issue with the AD tenant not sending the email address field. I searched for some answer online and this seems to have appeared before. Could you try some of the solutions outlined here?

https://github.com/MicrosoftDocs/azure-docs/issues/8702
https://stackoverflow.com/questions/50374291/getting-email-and-manager-id-in-saml-attributes-from-azure-ad

**Comment by seanbrowntruera** [comment]
Thanks for the help I've asked in the Issue you sent. It looks like the solution they had was to use a microsoft 365 group. I know it's mentioned in Sentry docs as well but we store our members in security groups. I've add a 365 group to the Sentry app but it's still not sending the email.

**Comment by schew2381** [comment]
Closing for now as this appears to be an AD issue.
