### ISSUE TITLE
Opening an error fails

### ISSUE THREAD

**Issue by Birowsky** [getsentry/sentry#5248]
Simply clicking on an error item, opens the error details view, but the loading spinner goes on forever.

I already tried with the [forum here](https://forum.sentry.io/t/opening-error-goes-on-forever/1267?u=birowsky), no answer.

I also tried closing my account completely, and reopening it. Didn't help.

**Comment by mattrobenolt** [comment]
If you open your browser's error console, there's probably an error there with more information? Most likely probably a 404 from the XHR request to load the event information is my guess.

**Comment by Birowsky** [comment]
Even so, why closing this?
