### ISSUE TITLE
Stats Page - Dropped Events should included Abuse Tier

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#52499]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Stats All Projects it does not add up:
<img width="1528" alt="image" src="https://github.com/getsentry/sentry/assets/8920574/a21c527e-be77-48b1-80d6-40453a76d87b">

For a Single Project selected it does not add up:
<img width="1522" alt="image" src="https://github.com/getsentry/sentry/assets/8920574/5e60f808-07d1-4d55-8dac-305d33411efc">

We noticed in Admin there were lots of Dropped errors due to Abuse. If you do the math on the 2.1m/day peak, it is only 24events/second.
<img width="1558" alt="image" src="https://github.com/getsentry/sentry/assets/8920574/9f5d54be-32d3-48af-b3bd-7a1dd145954a">

However we think this was the reason why the limit on org events/second was being reached:
<img width="973" alt="image" src="https://github.com/getsentry/sentry/assets/8920574/618467b6-2c65-4903-960a-ae1a04f26f38">

### Expected Result

Total Errors == Accepted Errors + Filtered Errors + Dropped Errors

### Actual Result

Total Errors !== Accepted Errors + Filtered Errors + Dropped Errors

^ happened in both the Stats.AllProjects view as well as the Stats.SingleProject view for the project that was sending to many events (sessions).

### Product Area

Stats

**Comment by Dhrumil-Sentry** [comment]
We plan on fixing this by removing abuse outcomes from the stats page- Abuse outcomes don't have any event type and that leads to confusion on these pages. Adding this to our backlog

**Comment by brianthi** [comment]
Looking at the API response that provides the data in stats page, the abuse outcomes have been removed. Closing issue.
