### ISSUE TITLE
Add wizard into the getting started guide

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#52500]
We'd like to mention wizard in the project creation (and org onboarding) snippets.

![Image](https://user-images.githubusercontent.com/9060071/252281253-a5cd37f3-2a9a-47d9-aeec-811ab23b2c8c.png)

It's already implemented in the docs here:
https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/webpack/

![Image](https://user-images.githubusercontent.com/9060071/252281370-dd30b8ad-c2e3-4cb1-ac12-651eaf077838.png)

Relates to: https://github.com/getsentry/sentry/issues/52431

- [x] React
- [x] Vanilla
- [x] Vue
- [x] Svelte
- [x] Angular
- [x] Ember
- [x] Gatsby

**Comment by priscilawebdev** [comment]
Closing this as everything was done in the PRs:

https://github.com/getsentry/sentry/pull/52616 - Gatsby
https://github.com/getsentry/sentry/pull/52614 - Vue
https://github.com/getsentry/sentry/pull/52606 - Angular
https://github.com/getsentry/sentry/pull/52506 - React
https://github.com/getsentry/sentry/pull/52625 - Vanilla
https://github.com/getsentry/sentry/pull/52618 - Svelte
https://github.com/getsentry/sentry/pull/52615 - Ember
