### ISSUE TITLE
[nextjs] Group Invariant: attempted to hard navigate to the same URL errors

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#52534]
Potential outcome: 
- Add this rule: `stack.function:"Error: Invariant: attempted to hard navigate to the same URL*" -app`
- This is caused by the lack of source maps

I was looking at a customers' FE project and I noticed a lot of groups that have the same stacktrace but fail to be same at the very end with `Error: Invariant: attempted to hard navigate to the same URL /some/route/`.

For some reason, [I see that code](https://github.com/search?q=%22Invariant%3A+attempted+to+hard+navigate+to+the+same+URL%22&type=code) quite often in public GitHub repos.
```javascript
throw new Error(`Invariant: attempted to hard navigate to the same URL ${url} ${location.href}`);
```

It seems to be related to Next.js projects. If you need a project that has this error you can look for this id: `5806672`

Perhaps this rule by default would do the trick: `stack.function:"Error: Invariant: attempted to hard navigate to the same URL*" -app`

Note from Markus:
> We should find a way to un-parametrize the log statement within the SDK. Other SDKs like Python send us "attempted to hard navigate to the same URL %s" which is much easier to group by. We can't push all responsibility for good grouping to the grouping algorithm, the input data here is broken and possibly needs some platform-specific solution (serverside as part of sourcemap processing or SDK, I don't know)

![Image](https://user-images.githubusercontent.com/44410/242052260-9eddc641-bb33-4728-ba51-591b3df0fb99.png)

**Comment by lobsterkatie** [comment]
> For some reason, [I see that code](https://github.com/search?q=%22Invariant%3A+attempted+to+hard+navigate+to+the+same+URL%22&type=code) quite often in public GitHub repos.

It's internal nextjs code, and it shows up in other repos only because people are committing their built assets, which include the nextjs framework bundle.

**Comment by lobsterkatie** [comment]
It's weird to me that it's showing up as a function name in the screenshots above. In every event I can find, it's the `value` (which actually makes more sense):

![image](https://github.com/getsentry/sentry/assets/14812505/754bb838-fc4b-4f6e-80c6-84008798582a)

So I think this needs to be a parameterization fix rather than a `-app` rule fix.

**Comment by lobsterkatie** [comment]
UPDATE: I have dug into it further, and chatted with @armenzg, and it seems now the grouping is happening correctly. (The examples I see in different groups actually do have legitimately different stacktraces). Going to close this until there's some evidence it's happening again.
