### ISSUE TITLE
Cannot remove Vercel integration from Sentry

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#52541]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

**Summary:**
A customer is reporting that they cannot remove the Vercel integration from Sentry with the intention to re-install it with their correct projects and source map capabilities. They have removed Sentry from the Vercel side so there is no reference to the Sentry integration from the Vercel platform.

Ticket with customer information: https://sentry.zendesk.com/agent/tickets/90365

Steps to reproduce:
1. Access customer org
2. Navigate to the integrations page -> Vercel integration
3. Attempt to uninstall/delete Vercel integration
4. Open network tab -> Internal Error

### Expected Result

Ability to uninstall/delete Vercel integration from Sentry.

### Actual Result

An internal error occurs and failed to remove integration.

### Product Area

Settings - Integrations

**Comment by ceorourke** [comment]
When we try to uninstall a Vercel integration we first hit Vercel's delete integration endpoint but that's 403'ing since it's already been deleted on the Vercel side. I think we can change it to _attempt_ to delete it on Vercel's side but continue deleting it in Sentry if that fails.

**Comment by ceorourke** [comment]
I just merged #52698 (give it a bit to get deployed) which I'm hoping will unblock this customer.

**Comment by stephanie-anderson** [comment]
@ceorourke @scefali can you please confirm that this works now and close this issue? Thank you!

**Comment by scefali** [comment]
Don't think we can easily replicate the problem but I'm confident that @ceorourke's fix works here
