### ISSUE TITLE
CSRF Verification Failed Page on Login

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry#52572]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When using the Brave Browser, a user is frequently encountering a "CSRF Verification Failed" page during the login process on sentry.io. This issue seems to be related to session refreshing failures within Sentry. As a result, the affected user has to manually clear their cookies and navigate to the sentry.io root URL in order to successfully log in again. It is worth noting that the user can log in using an incognito browser or sometimes even in a normal window, but occasional login or session refresh failures lead to the CSRF fail page.

From the description, the steps to reproduce are:
- Use the latest version of Brave Browser based on Chromium.
- Attempt to log in to the sentry.io project (e.g., "node-app.sentry.io") using a previously visited URL.
- Notice that sometimes Sentry fails to refresh the session, leading to the "CSRF Verification Failed" page.
- Manually clear cookies and navigate to the sentry.io root URL to log in again successfully.

### Expected Result

Users should be able to log in to sentry.io consistently without encountering the "CSRF Verification Failed" page and without the need to manually clear cookies or navigate to the root URL.

### Actual Result

There are intermittent login and session refresh failures, resulting in the display of the "CSRF Verification Failed" page. This forces affected users to manually clear their cookies and manually navigate to the sentry.io root URL to log in again.

### Product Area

Sign In

**Comment by JoshFerge** [comment]
over a year and no movement, will go ahead and close. feel free to re-open if this comes up again.
