### ISSUE TITLE
Sentry for organizational process performance

### ISSUE THREAD

**Issue by BYK** [getsentry/sentry#52609]
### Problem Statement

We have an organizational process that we want to track the performance of. It has technical bits and some less technical bits. What we are after is almost exactly the same as what https://github.com/getsentry/sentry-github-actions-app does for GitHub actions: record metrics about certain transactions and spans and then analyse and visualise them.

The only issue is: these processes can take multiple months, some longer than the default 90-day retention period Sentry has. I was wondering if it would be possible (maybe with some local hacking) to make Sentry work for this use case? Or does it already work as 90-day period only applies to individual events but not aggregate data?

### Solution Brainstorm

No idea, make Sentry a generic process performance tracking tool as it is awesome?

### Product Area

Performance

**Comment by mjq-sentry** [comment]
Hi @BYK! This is an interesting use case, but I'm not sure if it's one we're going to be able to support well. In general, we don't keep data for more than 90 days in Sentry and so single processes longer than that will end up missing data. I don't think this is a constraint we're likely to change in the short term. I'm forwarding this to @nanoburd (product owner for Performance) so he can at least read over the use case though!

**Comment by BYK** [comment]
Hi @mjq-sentry! Sorry for the very delayed response and thank you for yours :)

I do understand the 90-day retention period issue. I just wanted to bring up the fact that there are many other possibilities for use of the tool you folks have created.

That said I'm happy for this issue being closed for clarity if there are no plans to make it a reality any time soon.

**Comment by gggritso** [comment]
@BYK it's been a while since you filed this, and Sentry has a shiny new Trace view. Does that make the situation better for you? It should be more amenable to longer/bigger/stranger traces

**Comment by BYK** [comment]
Hi @gggritso, not necessarily but I'd say this is such an edge case it should be fine to close the issue ☺️

Thanks so much for the care and pointing out a potential solution which indeed looks awesome!
