### ISSUE TITLE
[Bug] Sentry stacktrace snip not taking the right portion of the minified line.

### ISSUE THREAD

**Issue by sagiavinash** [getsentry/sentry#5261]
As you can see in the screenshot below. the variable causing the issue is "e"
but in the stacktrace snip the variable is not found.

http://image.prntscr.com/image/22505d9d8ef6405ebadd49b1898d0670.png

i am currently on raven client `v3.7.0`

**Comment by dcramer** [comment]
I'm not really sure why but really you should just setup sourcemaps here. We can't guarantee column numbers so we can't guarantee correct snipping.
