### ISSUE TITLE
Visual Studio Team Services Issue Tracking

### ISSUE THREAD

**Issue by csmithnic** [getsentry/sentry#5263]
I already made a feature request, but it was suggested that I also create an issue for this.  I see some of the big Task Management softwares listed on the issue tracing integrations list, but I don't see Visual Studio Team Services (aka Team Foundation Server 2017) on the list.  Our company is heavily dependent on TFS and I'd love to see this integration added to your list.

Thanks!

**Comment by dcramer** [comment]
I actually was going to add it a little while back, but its when our new UI code for plugins was still a bit more of a draft. I wouldn't say it's super easy now, but we at least have the things in place where we could more easily get VSTS in now:

https://github.com/getsentry/sentry-plugins/tree/vsts

**Comment by olsh** [comment]
Are there updates on this?

**Comment by dcramer** [comment]
@olsh its on hold as we're overhauling integrations and VSTS is pretty low on the list of users (and thus priority).

**Comment by dcramer** [comment]
#232

**Comment by stajs** [comment]
Can I just check that this is working as expected?

I tried adding this integration to my projects. I've gone through the flow of adding the VSTS identity (redirect to VSTS, click Accept on the permissions request, redirect back to Sentry). The `Identity` of `Visual Studio` shows up under my `Current Identities`:

https://sentry.io/account/settings/identities/

However I get an error when linking:

> An unsupported response type was returned: text/html; charset=utf-8

![image](https://user-images.githubusercontent.com/2253814/30789319-1c362f06-a201-11e7-912d-169eea20a9aa.png)

If I try to create a new issue, I just get:

> There was an error creating the issue.

**Comment by dcramer** [comment]
Saw this on the server side and should have enough detail, so will follow up early this week to figure out whats going on. VSTS has some non-standard API quirks in a few places, and its likely this is another one that we didn't see in QA.

**Comment by stajs** [comment]
Thanks, is it worth re-opening this issue (or create a new one)? Let me know if/when you would like me to re-test this.

**Comment by dcramer** [comment]
https://sentry.io/share/issue/312e333535313939393137/

**Comment by dcramer** [comment]
This actually seems to be something different than what I thought, and I'm a bit confused. The response itself is something about a proxy not relaying the content correctly (I dont have it off hand, but I recall it form development). Whenever I saw this, it suggested the access_token was invalid, and needed refreshed. Unfortunately that doesn't seem to be the case here, as its hitting this error on its refresh attempt.

**Comment by dcramer** [comment]
It unfortunately seems not a lot of information exists around the API, and we're still pretty early in conversations with anyone on MSFT's side. Will update when I'm able to figure out more.

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/13ae6190-8d01-4e2f-8037-9661b88fb7e0/visual-studio-online-rest-api-http-203-nonauthoritative-information-when-accessing-team?forum=TFService

**Comment by dcramer** [comment]
Closing in favor of #6184
