### ISSUE TITLE
Support DSyms in Deletion

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#5265]
The dsym code currently is not handled correctly in `sentry.tasks.deletion`.

**Comment by bretthoerner** [comment]
@mitsuhiko can you elaborate?

Is this issue to add full support for the user deleting DSym info manually?

Because as for `sentry.tasks.deletion`, it seems like the only ways a DSym would be dropped is it the `Project` is deleted, which should be handled fine by the cascade/FKs?

**Comment by mitsuhiko** [comment]
@bretthoerner this is for when a user deletes the org. The issue right now is that this deletion (unlike some others) fully depends on the cascade which means we cannot split those tables. I noticed that other deletions there are based on all models having the org ID so I was originally thinking of attaching the org_id.

**Comment by bretthoerner** [comment]
Oh, are we planning to move the DSym tables? I'm surprised they're that big.

OK, I can look into that now that I understand more.

**Comment by mitsuhiko** [comment]
@bretthoerner we do not plan on moving them right now, no. We can also close this issue down with outlining the limitation so that nobody forgetting about deletions later if ops wants to split things. My biggest worry was that I added some code that unlike other code does not have the org ID so we put outselves in a stupid corner later.

The deletion code currently triggers deletions without depending on cascades for the rest of it as far as I know. So this would bring it in line.

**Comment by bretthoerner** [comment]
But `Project` has a real FK to `Organization`, and all DSym tables have real FKs to `Project` -- so a deletion of either should handle all the DSym data.

**Comment by bretthoerner** [comment]
OK we discussed some in Slack. The issue isn't necessarily rows remaining in Postgres (because we have FKs... for now). The issue is not calling `delete` on all objects, which may leave stuff behind:

https://github.com/getsentry/sentry/blob/2cef08cc7eb97b64e69ec83af6d84bed4c26efbf/src/sentry/models/file.py#L109-L125

See `ReleaseFile` here: https://github.com/getsentry/sentry/blob/master/src/sentry/deletions/defaults/organization.py
