### ISSUE TITLE
Support Absolute Time for Replay Details

### ISSUE THREAD

**Issue by kmix** [getsentry/sentry#52682]
### Problem Statement

Sometimes when troubleshooting it's nice to be able to compare timestamps of the replay session with other logs or bug reports.  FullStory has the ability to toggle the timeline between session time and absolute time:

https://help.fullstory.com/hc/en-us/articles/360020623614-Understanding-session-time-and-how-to-switch-to-absolute-time

### Solution Brainstorm

It would be useful to support the ability to toggle between session time and absolute time.

### Product Area

Replays

**Comment by jas-kas** [comment]
Design from @Jesse-Box https://www.figma.com/design/UbdErmrMeEkthzCUSFjOGM/Specs%3A-Player-Settings?node-id=1-264&t=sWlO4MjgWW76ceex-1
