### ISSUE TITLE
Regression email should use latest error message

### ISSUE THREAD

**Issue by jonmcewen** [getsentry/sentry#5270]
Applies to hosted Sentry.
When a regression email alert is sent, the email contains an error message relating to the issue, but this is not the message from the latest event.

Issues may relate to unhandled data values (e.g. where a mapping is missing from config), and the missing value will be included in the error message.

It would be more helpful, and less misleading, if the email contained the error message from the event that caused the regression.

To recreate the issue, fire an event with an error message that contains the current time.  Mark the issue as resolved, and then fire another event that differs only by the time in the message.  The regression email will not contain the new time.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
