### ISSUE TITLE
Expose On Demand search filter mapping

### ISSUE THREAD

**Issue by obostjancic** [getsentry/sentry#52702]
We currently have two separate definitions of search filters that are on-demand metrics extraction supports.
List for the UI is defined in https://github.com/getsentry/sentry/blob/574748ccee06e9114a5ae50dae78be3c9cdce5fc/static/app/views/alerts/wizard/options.tsx#L238

Sentry backend defines the mapping in https://github.com/getsentry/sentry/blob/2fd2459c274dc81c079fd4c31b2755114602ef7c/src/sentry/snuba/metrics/extraction.py#L42

Use mapping defined in sentry backend as a single source of truth, expose it to the UI and reuse it in the alert edit/creation form

**Comment by jan-auer** [comment]
Frontend TSC recommended to duplicate the mapping and link it with code comments.
