### ISSUE TITLE
[web app] Log user out if browser page is stale

### ISSUE THREAD

**Issue by scottyantipa** [getsentry/sentry#5271]
There are several pages of the sentry website that contain sensitive information, like auth tokens, rendered in plain text.  It would be nice if either:
- These pages either didn't display the sensitive info all the time.  They could instead make you click to display the sensitive info, which would then be hidden automatically after a few minutes.
- and/or the page becomes stale after some minutes of inactivity.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
