### ISSUE TITLE
Team Admins could be able to link/unlink their teams to a Slack channel

### ISSUE THREAD

**Issue by sepbehroozi** [getsentry/sentry#52716]
### Problem Statement

When trying to link a Slack channel to a Sentry team using `/sentry link team` command, via a non-admin/manager user, Sentry shows the below error:

> You must be a Sentry admin, manager, or owner to link or unlink teams

The problem with asking the Admin/Manager to link a team is that they first, need to join the team, then Sentry shows the team in the team selection drop-down, like the figure below:
![Screenshot 2023-07-12 at 15 45 49](https://github.com/getsentry/sentry/assets/1960884/9ea8d98f-a07a-4456-8abc-40bfab0b100e)

### Solution Brainstorm

To make it easier for the teams to link/unlink their Slack channels with their Sentry team, this access can be granted to the users who have Team Admin access.

![Screenshot 2023-07-12 at 15 53 47](https://github.com/getsentry/sentry/assets/1960884/44dbe71d-5890-4851-a5f5-e430be09bc8b)

### Product Area

Settings - Teams

**Comment by Dhrumil-Sentry** [comment]
@sepbehroozi Thanks a lot for this feedback! This is something that team admins should have permission to do. I'll add this to our backlog and update the issue as I have more details

**Comment by sepbehroozi** [comment]
Hello @Dhrumil-Sentry 
The issue still exist and our teams have to reach out to organization admins to link/unlink their slack channel.
I wanted to kindly follow up on it. Is it still in your backlog and hasn't been surfaced yet?

**Comment by Dhrumil-Sentry** [comment]
@sepbehroozi We understand this is important for large customers and we're looking into this. I will keep this issue updated as I have more details. We don't expect this to be fixed before the end of October at the earliest and will likely take longer

**Comment by schew2381** [comment]
@sepbehroozi Hi there, sorry for the delay! I've merged in the change and tested that you can now link slack channels as a team admin. If anything else pops up, feel free to reopen this issue and ping me! 👍
