### ISSUE TITLE
angular invalid location in sourcemap Might be raven issue

### ISSUE THREAD

**Issue by graingert** [getsentry/sentry#5273]
## Reporting Bugs

When reporting bugs, include details about your configuration, such as:

- The version of Sentry you're using: sentry.io

##

Angular Raven plugin likes to set a link to the angular docs for certain errors:
http://errors.angularjs.org/1.6.4/$controller/ctrlreg?p0=SomeCtrl

![angular-sourcemap-fail](https://cloud.githubusercontent.com/assets/413772/25272168/cd092c38-267e-11e7-9132-104c291ac6eb.png)

However it seems that Sentry wants to process this as a sourcemap.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
