### ISSUE TITLE
Improve readability of stack traces by automatically restoring mangled functions/classes names from source maps

### ISSUE THREAD

**Issue by andreyselitsky** [getsentry/sentry#52780]
### Problem Statement

When mangling your source code with UglifyJS, the names of the functions and classes become unreadable. 

Sentry could try to restore real names from the source maps, in case available, and show them in the stack traces. 

### Solution Brainstorm

Chrome somehow restores names for functions and symbols and the debugger shows the right names. Sentry could do something similar. Not much idea how to do it though. 

### Product Area

Issues - Source Maps

**Comment by AbhiPrasad** [comment]
Hey @andreyselitsky, thanks for writing in! We support using sourcemaps to restores names for functions and symbols - please see https://docs.sentry.io/platforms/javascript/sourcemaps/ for more details.
