### ISSUE TITLE
Duration is always 0 for network requests to 1st party domain in Sentry Replays

### ISSUE THREAD

**Issue by damacisaac** [getsentry/sentry#52790]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Capture a replay that has network requests being made to 1st party domain
2. Check network details in Sentry Replay
3. Duration is always 0

### Expected Result

Duration should be tracked

### Actual Result

<img width="755" alt="Screenshot 2023-07-13 at 10 30 50 AM" src="https://github.com/getsentry/sentry/assets/3689921/1170d7a4-c86d-4a56-89be-65b7b33f33bf">

### Product Area

Replays

### Version

7.57.0

**Comment by billyvg** [comment]
@damacisaac Does this only happen on XHR's or other requests as well?

**Comment by damacisaac** [comment]
@billyvg it's also happening with calls to our AWS assets bucket.

**Comment by jahewson** [comment]
I'm seeing this issue too, for XHR requests against our API (which in our case is a CORS request).

<img width="347" alt="Screen Shot 2023-10-13 at 10 55 54 AM" src="https://github.com/getsentry/sentry/assets/467695/924d3828-8533-45eb-868f-bf0d08d5a9d6">


Version: 7.72.0

**Comment by mydea** [comment]
Hey,

we've identified the issue and opened a PR to fix it: https://github.com/getsentry/sentry-javascript/pull/9341 this will go out with the next release of the Sentry SDK!

**Comment by mydea** [comment]
This has been fixed & released in 7.75.0 of the SDK!
