### ISSUE TITLE
Allow filtering an Issue Alert on whether a Github issue (in issue tracking) has been assigned

### ISSUE THREAD

**Issue by DanielNoord** [getsentry/sentry#52793]
### Problem Statement

We'd like to not send Issue Alerts whenever we have already identified the problem and created (and linked) an issue in our bug tracker.
We does this via the Issue Tracking feature in Sentry. It would be good to be able to filter out such events.

### Solution Brainstorm

Just add a filter for this in the current dropdown selection.

### Product Area

Alerts

**Comment by scttcper** [comment]
@DanielNoord thats great feedback. I've added this to our backlog. Would make sense since we allow filtering by `is:linked` in the issues stream

**Comment by DanielNoord** [comment]
If you'd be able to give me some point I'd be happy to help implement this myself. Although I worry this might be a little bit too hard to implement on a codebase I don't know yet.

**Comment by scttcper** [comment]
@DanielNoord thats very nice of you to offer. I think we might be able to get this in scope of a project coming up as well.

The filters look like this https://github.com/getsentry/sentry/blob/master/src/sentry/rules/filters/assigned_to.py#L18-L54 and the others are in the same folder.

**Comment by DanielNoord** [comment]
I had a look but had a bit of difficulty understanding how to determine whether there were any linked issues for an `EventGroup`. I'll be looking forward to the upcoming project.

**Comment by DanielNoord** [comment]
I found this works with `!is:linked`. Thanks!
