### ISSUE TITLE
Add CORS header for CSP reports

### ISSUE THREAD

**Issue by ishitatsuyuki** [getsentry/sentry#5279]
Edge attempts to use XHR internally to POST a CSP violation report.

Test results:
Edge 14: report failure as 403
Edge 15: report sent with CORS error messages in console

The best way is to add Access-Control-Allow-Origin for the CSP endpoint. There's no such specification in CSP reference, but anyway it's up to the vendor's implementation.

**Comment by mattrobenolt** [comment]
Do you mind sharing the actual error being spit back? And if possible, the payload that Edge is trying to send?

**Comment by ishitatsuyuki** [comment]
I failed to get a perfect screenshot, but this is how it occurs in Edge 14:

![screenshot from 2017-04-24 17-52-45](https://cloud.githubusercontent.com/assets/12389383/25334944/ca9777ac-292b-11e7-8b61-a7bdc4ce8c95.png)

Turns out this is rather #3542, which is the behavior of [CSP 1.0](https://www.w3.org/TR/2012/CR-CSP-20121115/#sample-violation-report).

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
