### ISSUE TITLE
Refactor CSP endpoint to support report-to 

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#52794]
### Problem Statement

Sentry current CSP report requires user to set "report-uri" with Sentry endpoint that contains query parameters:
```
Content-Security-Policy: ...; report-uri https://o{org_id}.ingest.sentry.io/api/{project_id}/security/?sentry_key={key_id}
```
However `report-uri` is deprecated and replaces with `report-to`:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri

The issue is that report-to does not support query parameters (?sentry_key={key_id}`) being impossible to use with Sentry's CSP endpoint in it. 

### Solution Brainstorm

Allow accepting CSP reports on a project specific endpoint that does not require a query parameter to it can be used in `report-to`. 

### Product Area

Other

**Comment by jan-auer** [comment]
See also: https://github.com/getsentry/sentry/issues/38940
