### ISSUE TITLE
Filter Slackbot crawler

### ISSUE THREAD

**Issue by rcscott** [getsentry/sentry#5284]
We get issues reported in Sentry whenever we post our internal app links in Slack because the Slackbot web crawler tries to load them and fails. Would it be possible to get Slackbot added to the list of crawlers that are ignored in Sentry?

**Comment by dcramer** [comment]
+1

**Comment by rcscott** [comment]
The three Slack user agents for their crawlers are detailed at https://api.slack.com/robots.

**Comment by mattrobenolt** [comment]
If we're gonna do this, we might as well also get Facebook and Twitter. Unless we already do. (Not looking at code yet)

**Comment by rcscott** [comment]
Facebook is in the list of crawlers at https://github.com/getsentry/sentry/blob/master/src/sentry/filters/web_crawlers.py

**Comment by mattrobenolt** [comment]
Cool, then let's add Slack and Twitter to this. I can do this at some point unless you want to throw up a PR for it. <3

**Comment by rcscott** [comment]
@mattrobenolt it seemed easy so I went ahead and put up a PR - #5285.
