### ISSUE TITLE
Add ability to search by rage and dead clicks

### ISSUE THREAD

**Issue by cmanallen** [getsentry/sentry#52883]
### Problem Statement

Users experience poorly behaving applications which results in rage and dead click breadcrumbs.

### Solution Brainstorm

We will add new columns to the database to track the rage and dead click breadcrumb events.  With these indexed breadcrumbs we can search and sort replays by them.

- [x] Add documentation 
  - [ ] ~https://docs.sentry.io/product/session-replay/replay-page-and-filters/~ will be updated with showing columns in the UI
  - [x] https://docs.sentry.io/product/sentry-basics/search/searchable-properties/session-replay
- Add front-end autocomplete
  - [x] https://github.com/getsentry/sentry/issues/52803
- [x] Add API fields.
    - Done.  Pending processor merge.
- [x] Update replays consumer to submit rage and dead click breadcrumbs on the click events.
- [x] Migrate the ClickHouse schema to include new rage and dead click counts.
- [x] Merge Snuba processor.
    - Pending revert of revert.

### Product Area

Replays

**Comment by bruno-garcia** [comment]
🥳 🥳 🥳
