### ISSUE TITLE
Forgot about perl

### ISSUE THREAD

**Issue by KES777** [getsentry/sentry#5293]
on `/getting-started/` page you forgot to mention about `Perl`

**Comment by mattrobenolt** [comment]
Hey, thanks for the feedback. I'm not sure the word "forgot" is correct here. :) Even out documentation is pretty lightweight: https://docs.sentry.io/clients/perl/

Perl is a community maintained SDK, so none of the core developers of Sentry have real experience with Perl. I'll see if I can hobble together a page for this though.

Or if you have feedback, as a Perl developer, that'd be appreciated as well.
