### ISSUE TITLE
Checking migration state failed(1146)

### ISSUE THREAD

**Issue by Jerry805** [getsentry/sentry#52944]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

python: 3.10.12
mysql8

1. pip install sentry
2. sentry init
3. change database to mysql
4. sentry upgrade
Checking migration state failed with: (1146, "Table 'sentry.django_migrations' doesn't exist")
Error: Could not determine migration state. Aborting

### Expected Result

init database success

### Actual Result

Checking migration state failed with: (1146, "Table 'sentry.django_migrations' doesn't exist")
Error: Could not determine migration state. Aborting

### Product Area

Issues

### Version

23.6.2

**Comment by hubertdeng123** [comment]
closing as duplicate of https://github.com/getsentry/self-hosted/issues/2270
