### ISSUE TITLE
Ignore has:* in metrics query

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#52959]
We have a lot of dashboard widgets that are doing something like:
query: `has:measurements.frames_frozen_rate`, fields: [`transaction`, `p75(measurements.frames_frozen_rate)`].
The `has:` does not have any effect as long as you are also querying it. If that's the case, we should ignore it in the query because we are unnecessarily falling back to indexed because of it.

**Comment by RaduW** [comment]
Tried queries with and without has and it doesn't seem to make any difference.
has: does not appear to trigger indexed data in Dashboards.
Was this fixed ?

Example:
https://sentry.sentry.io/api/0/organizations/sentry/events/?dataset=metricsEnhanced&field=count%28%29&name=&per_page=20&project=1&query=event.type%3Atransaction%20browser.name%3AChrome&statsPeriod=1h&yAxis=count%28%29

A dashboard with 2 widgets (one with and one without has) both return the same value, both return data marked with: isMetricsData = true, dataset = metricsEnhanced

**Comment by RaduW** [comment]
Also tried with transaction field.
Same result ( correctly using metrics data even when adding has: transaction)

https://sentry.sentry.io/api/0/organizations/sentry/events/?dataset=metricsEnhanced&field=count%28%29&name=&per_page=5&project=1&query=has%3Atransaction&referrer=api.dashboards.bignumberwidget&statsPeriod=1h&yAxis=count%28%29

**Comment by RaduW** [comment]
Reproduced after input from Jan:
Table widget with fields: transaction , p75(measurements.frames_frozen_rate) and  HAS measurements.frames_frozen_rate

**Comment by jan-auer** [comment]
@RaduW We'd also need to consider the same in the on-demand metrics check. There's a function that assesses whether an alert needs ondemand metric or OOTB metrics. Please sync with @obostjancic on the details.
