### ISSUE TITLE
Crons: Unexpected `missed_checkin`s on timezoned crontabs with Celery integration when monitoring beats.

### ISSUE THREAD

**Issue by MihailRussu** [getsentry/sentry#52950]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

First of all - the Sentry Crons integration with `CeleryIntegration(monitor_beat_tasks=True)` is awesome, thank you very much for it! 🙏

I believe I may have stumbled upon a bug with timezoned crontabs on celery integration when monitoring beats, where despite the successful on-time check-in, Sentry Crons anyway still expects another check-in at the wrong time.
On my app, I have a crontab with a specific timezone that is expected to run only once a day at 7 am (UTC +2h), e.g.:
<img width="841" alt="Screenshot 2023-07-16 at 15 19 20" src="https://github.com/getsentry/sentry/assets/1810455/b90c1192-2080-41be-a6bb-834e0b66e37e">

But I will always get two reports for that job: a successful one at 7am, and a missed one at 9am.

### Expected Result

Only one, the successful check-in at 7am is reported. No tasks are expected to run at 9am, so the missed check-in warning is erroneous & misleading.

### Actual Result

I'm constantly getting unexpected `missed_checkin` reports that are off by 2 hours, on top of the expected successful ones, e.g.:
<img width="969" alt="Screenshot 2023-07-16 at 15 24 33" src="https://github.com/getsentry/sentry/assets/1810455/ec0375e8-3c24-486f-b828-16e291129350">
(see how Sentry UI indicates the task is expected to run at 7am, shows a successful check-in at 7am 👍, but also indicates a missed check-in at 9am 👎 which shouldn't be there, as the job already succeeded for that day, it is not expected to run again until the next morning)

### Product Area

Crons

**Comment by MihailRussu** [comment]
@evanpurkhiser thanks a lot for looking into this!

The timezone of the machine is UTC:
![timezone](https://github.com/getsentry/sentry/assets/1810455/7a1cf02f-518a-49e1-984e-e560894f81f4)

 The timezone of the Sentry Crons Monitor that is automatically created thanks to `CeleryIntegration(monitor_beat_tasks=True)` - just like you suggested does indeed match & is also UTC:
<img width="342" alt="crons" src="https://github.com/getsentry/sentry/assets/1810455/30b7ab11-278e-4b64-9679-dc393e89bba1">

But for the convenience of the "jobs' operator" and as indicated in the very first screenshot - the jobs may be scheduled to run in different timezones.

While I suppose one can go to the individual Sentry Crons Monitor, and manually adjust the timezone to the desired one - that would be somewhat inconvenient as there may be tens of them. Also, it's not clear whether that manual change wouldn't be reset / overridden once the beat triggers again.

Is there maybe a way to tell Sentry integration to NOT take the machine's timezone, but rather the Celery Crontab's, or is that "syntactic sugar" provided by Celery Beat, that isn't easily available to the Sentry integration?

**Comment by evanpurkhiser** [comment]
Ahh, sounds like there may have been a piece I was missing here. I wasn't familiar enough with Celery to know you could actually configure each schedule with it's own timezone!

@antonpirker would we be able to updated the SDK to prefer reading this timezone from the celery schedule, instead of using the machines timezone? I think that would be the fix for this!

**Comment by antonpirker** [comment]
Hey @MihailRussu !
We use the timezone from the Celery configuration: https://github.com/getsentry/sentry-python/blob/antonpirker/2262-traces-sampler-url-instead-of-generic-asgi-request/sentry_sdk/integrations/celery.py#L440

Can you show me how you set the timezone for your Celery Beat task? Then I can fix this in the SDK. Thanks!
