### ISSUE TITLE
[SPIKE] Dogfood our product to debug DS tasks running out of time

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#52961]
Use our Performance and Profiling products to debug and resolve DS tasks running out of time.

**Comment by RaduW** [comment]
Findings:

### Performance

Backend sampling in sentry is set at  0.02 ( 2%).
For tasks you can override it in `sentry/utils/sdk.py::SAMPLED_TASKS`.
Created a PR to set it to 25%.

### Profiling
In production we set `profiles_sample_rate=1` we do not set a `profiles_sampler`.
This means that all traces are profiled. 
The 'catch' is that we do not enable profiling for on all pods.
`SENTRY_PROFILING_ENABLED = os.environ.get("SENTRY_PROFILING_ENABLED", False)` is overriden in one
pod and set to True ... so only that pod captures profiles.

Currently tnone of the Celery workers (the pods where they run) have profiling enabled.
Talked with Tony Xiao and he said that in the future they would be open to talk about enabling profiling for
particular tasks (nothing it is setup for this at the moment).
