### ISSUE TITLE
Deeply nested objects in extra_context aren't fully encoded as JSON

### ISSUE THREAD

**Issue by JamesHageman** [getsentry/sentry#5303]
Hi, I'm running an on-premise docker deployment of `sentry:8.15-onbuild`. I'm reporting errors to sentry using this version of the Raven gem:
```
gem 'sentry-raven', require: 'sentry-raven-without-integrations', github: 'getsentry/raven-ruby', ref: '9f9116b1ab3c346671bc83c83c40657883074469'
```

When I attach a deeply nested object to `extra_context` (via `raven.extra_context(input: some_hash)`), sentry only JSON encodes the object 3 levels deep, then it switches to some sort of Python string encoding like `{u'cents': u'1234'}`.

Here is a screenshot:

![screen shot 2017-04-27 at 10 35 08 am](https://cloud.githubusercontent.com/assets/2660188/25488513/375070d2-2b35-11e7-8eba-749c106c4945.png)

I expected sentry to encode the entire object all they way down, so I can use the whole object when I query for events with the API. 

Because of this issue, I've had to JSON encode the extra context before sending it to sentry. This isn't ideal because sentry has a string length limit on extra context fields, so big JSON objects don't fit.

**Comment by dentarg** [comment]
```
data = JSON.parse('{ "foo": [ { "bar": { "baz": "åäö" } } ] }')
Raven.extra_context(data: data)

**Comment by EvanPurkhiser** [comment]
Here's the culprit: 

https://github.com/getsentry/sentry/blob/04d8cf5987353b7018e6682077b68a7dc236a003/src/sentry/event_manager.py#L322

**Comment by EvanPurkhiser** [comment]
@dcramer: Looks like the trimming was originally introduced here https://github.com/getsentry/sentry/commit/d0e2278770be3a392d8a9238b802922ecb497ec9#diff-4bf345e0795c0e86cfdb6a13f60bcb64R182, do you know what the intention was for it?

**Comment by dcramer** [comment]
We trim data because otherwise payloads are have no realistic max size.

**Comment by ffxsam** [comment]
Yes, but I had a field go completely missing that I was trying to log. I had a `result.data` that was raw HTML (not massive), and when I logged `result` as an extra field, `data` didn't show up at all.

**Comment by dcramer** [comment]
One quick solution we could possibly do for top level keys, is at least retain the key but truncate the value (and show it as such).

**Comment by ffxsam** [comment]
>One quick solution we could possibly do for top level keys, is at least retain the key but truncate the value (and show it as such).

That could work. The issue I had is that we had an API returning an unexpected result (`result.data` contained an HTML string rather than JSON). And even if we saw some truncated HTML, we would know something was up. Instead, we spent a good few hours trying to figure out what was wrong.

**Comment by dentarg** [comment]
I don't get it, what has trimming the data to do with not rendering it correctly?

**Comment by EvanPurkhiser** [comment]
Haven't had time to dig deeper into this yet still, but just another specific point, this is what's causing the python representation:

https://github.com/getsentry/sentry/blob/20dc1571999a612ef10b65155e286066e6ff9939/src/sentry/utils/safe.py#L67
