### ISSUE TITLE
[Investigation] Alerts fire only considering indexed events

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#53044]
**Problem**
Alert: https://sentry.sentry.io/alerts/rules/details/23528/?alert=85286
It looks like it’s ignoring the non-stored events. Notice that it’s triggering when volume isn’t actually 0. When you open up the chart in Discover, you can see where we just stored metrics for events instead of the actual events which corresponds to the triggered “incidents”.

**Comment by obostjancic** [comment]
### Investigation summary
- The actual configuration stored in the db looks ok, it is set up to query metrics and not indexed data
- When reproduced locally the alert querying behaved as expected, querying the metrics data
- Comparing Metrics vs Indexed data for the last 7 days shows no hard correlation between indexed data dropping under the threshold and the alert triggers. 
    - First trigger (Jul 14) seems to have nothing to do with indexed data. 
    - Jul 16 triggers seem to be somewhat correlated but a related incident that impacted alert triggers was in progress during that timeframe. 
    - Last trigger again shows no correlation with Indexed data. 
    - The drop in indexed data (Jul 18) did not trigger an alert.

![Image](https://github.com/getsentry/sentry/assets/86684834/f00a6b64-fbc6-4e05-8473-39a620b04545)

We will continue to monitor this specific alert, its triggers, as well as the related metrics and indexed data for some time.

**Comment by iambriccardo** [comment]
Followed up with Steve on a thread, will keep the situation monitored since the system seems fine from the outside, over a period of 90 days. Unfortunately we don't have metrics before 90 days since that would ultimately allow us to understand whether we had a real drop in traffic close to the 31st May 2023.

**Comment by iambriccardo** [comment]
There is a possibility of client side sampling being reduced but we are asking Steve about that.

**Comment by iambriccardo** [comment]
Client side sampling seems to be 100%, thus other issues might come at play here.

**Comment by matejminar** [comment]
We did an additional investigation and the root transaction's project is `sentry` (not frontend), so there's definitely a client-side sampling. We can also confidently confirm that this alert is taking metrics into account, not indexed data, as this issue suggests. There's still one question remaining: why is the alert firing when clearly the chart shows that there was at least 1 signup in that time bucket? That is likely related to how alerts, in general, evaluate rolling windows and is outside the scope of this issue.
