### ISSUE TITLE
Design: Org/Project Selection for Wizard

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#53045]
Full details in: https://github.com/getsentry/sentry-wizard/issues/357

**Problem**: The Sentry wizard requires users to setup an Auth token. Our new org-scoped auth tokens, we need the user to specify a certain org and project. The current UX requires users to log in using the browser UI and then returns them to the CLI to select the project by scrolling through a long list
**Solution**: Guide users to login and select a project within the browser UI before returning them to the CLI.

**Comment by Jesse-Box** [comment]
Marking this issue as done/not needed

@ale-cota, @Lms24 and I agreed yesterday that his team will work forward without designs as the solution they suggested is sound and there are existing components in the application they can use to facilitate the required flow.

@Lms24 will inform me when a PR is ready to be reviewed
