### ISSUE TITLE
Typo in Sentry Guided tour

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#53048]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. In Sentry Quick Start, go to Track releases
2. There's a typo in this text: `Click here and select the "react-native" project to see how the release is trending compaed to previous releases.` -> it's compared instead of compared

the typo is in the getGuidesContent.tsx file (sentry/static/app/components/assistant/getGuidesContent.tsx)

### Expected Result

there shouldn't be a typo

### Actual Result

there is a typo

### Product Area

Help

**Comment by chadwhitacre** [comment]
Easier to make a PR than to go through the machine. :P

https://github.com/getsentry/sentry/pull/53101
