### ISSUE TITLE
Front-end streaming support for gpt4

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#53050]
Since GPT-4 is incredibly slow, the only way to experiment with it is to provide some streaming support. The back-end changes have already been merged in https://github.com/getsentry/sentry/pull/50735

On the frontend this would require bigger changes to how the API fetching system currently works.

**Comment by Jesse-Box** [comment]
We need to further investigate how big the changes are to the API fetching system. @mitsuhiko is the main go to person to understand how vast the changes are.

**Comment by matejminar** [comment]
Issues team will likely take this over.

**Comment by roggenkemper** [comment]
closing because ai suggested fix is deprecated
