### ISSUE TITLE
Revise Replay Search with "Popular Filters" UI

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#53085]
![Image](https://user-images.githubusercontent.com/77064737/253381211-f255822f-729f-4d47-af33-e57688891b4c.png)

**Comment by jas-kas** [comment]
@ryan953 This is a good list!

Only thing I might add is "Browser name" since apparently folks are searching for that based on Amplitude metrics.

"With Activity" seems a little vague to be super helpful

**Comment by michellewzhang** [comment]
@aliu39 do you think we can close this ticket now that we have the new search bar out?

**Comment by aliu39** [comment]
Hmm I'm actually not sure if new search bar does this, maybe we can move this back to "Needs triage/details". We have recent searches and popular tags, but not suggested searches like this.

**Comment by ryan953** [comment]
The new search bar replaces the popular filters thing with the categories tabs left to right across the top. 

![Image](https://github.com/user-attachments/assets/003b3c0f-17f2-4ea2-8ce6-f4b5eaa60665)


closing this.
