### ISSUE TITLE
Issues marked as NOT having sourcemaps when there are

### ISSUE THREAD

**Issue by oozliuoo** [getsentry/sentry#53131]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Follow the automatic setup for JS to setup and upload sourcemaps to Sentry
2. Verified that for a given release, all the artifacts (both source files and sourcemaps) are there
3. Send an error to sentry
4. Check the issue in sentry, see that there's an error banner complaining "We've encountered 1 problem un-minifying your applications source code", and the linked Guide points to sourcemap setup. However, looking at the stacktrace, it correctly points to the lines in the typescript files

![image](https://github.com/getsentry/sentry/assets/6527286/7489bab2-3c3e-4264-9c9a-fc3f573dc5aa)

Also, if I ran the `sentry-cli` to explain this particular event I can see it says the "Exception is already source mapped", and its showing me the correct code as well.

![image](https://github.com/getsentry/sentry/assets/6527286/36e93621-68d8-4754-bb46-49bd6b879040)

### Expected Result

1. There's no error banner shown in the Sentry issue, no complain about sourcemaps
2. Since the stacktrace is correctly pointing to the lines in our _TS_ files, should the icon say "TS" instead of "JS"? Showing "JS" here sometimes confuses me that its not correctly mapping the source

![image](https://github.com/getsentry/sentry/assets/6527286/199174ff-73cf-47aa-81b9-e9b178619b4f)

### Actual Result

1. Still seeing the error banner, as shown in the Repro steps
2. Seeing a "JS" icon in the stack trace which points to _TS_ files - maybe thats expected, but thats confusing, so I'd lke to check

### Product Area

Issues - Source Maps

### Link

https://tentaroocom-inc.sentry.io/issues/4264368716/?project=1252641&query=is%3Aunresolved+release%3A9.102609&referrer=issue-stream&statsPeriod=14d&stream_index=1

**Comment by kamilogorek** [comment]
> Still seeing the error banner, as shown in the Repro steps

We are aware of this issue and are working to make the false-positive go away.

> Seeing a "JS" icon in the stack trace which points to TS files - maybe thats expected, but thats confusing, so I'd lke to check

This is indeed a bug, thanks for reporting.
