### ISSUE TITLE
cannot access sentry dashboard when using VPN

### ISSUE THREAD

**Issue by szamanr** [getsentry/sentry#53130]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. connect to VPN
- i'm using proton VPN, some IP addresses are: 178.218.167.211, 194.126.177.56, 185.246.211.194
2. go to https://sentry.io/

### Expected Result

site should load fine

### Actual Result

site doesn't load: server not found
cannot log in, cannot access sentry dashboard

if i start the session with VPN disconnected, and then connect to VPN, sentry will work in that tab for the remainder of the session.

### Product Area

Sign In

### Link

https://sentry.io/

**Comment by schew2381** [comment]
Hello! I was unable to replicate this issue using proton VPN. Are you the adblock feature of Proton at all? This could potentially be causing some issues

**Comment by szamanr** [comment]
yes, i use netshield with the highest setting (blocks ads, trackes and malware)

**Comment by schew2381** [comment]
If you turn off netshield, does sentry work as expected?

**Comment by szamanr** [comment]
yes

**Comment by schew2381** [comment]
Unfortunately we won't be able to solve this on our end as Proton Netshield is blocking Sentry from functioning properly. I tried looking to see if Netshield has a whitelist but it doesn't support that currently. I'm sorry for not being to help with this, but please reach out if you have any other issues!

**Comment by szamanr** [comment]
thanks @schew2381, should i instead reach out to proton team to unblock sentry? any additional details i can provide them with?

**Comment by schew2381** [comment]
Yes that'd be the best course, Proton seems to be using a combination of open-source blocklists and some internal ones, so hopefully they should be able to whitelist Sentry
