### ISSUE TITLE
Mixed platforms stacktraces with multiple file extensions are not handled correctly

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry#53132]
The recognition of the platform works well for Dart where all files have the same file extension.

This doesn't work for RN where JS is mixed `ts/x` and `js/x` and JVM stacktraces can have `java` and `kt`.

### Example (RN on the left, Dart on the right):
Compared to dart/flutter where `event.platform` is `other`, React Native set it to `javascript` or `node`. 

![Screenshot 2023-07-18 at 15 26 15](https://github.com/getsentry/sentry/assets/31292499/2fbdc522-7613-4c71-99fa-edeea1c0601e)

#### iOS mixed stack trace from debug build symbolicated locally 
https://krystofs-org.sentry.io/issues/4367628579/events/fe7a0ee5f60340c28d84dbf5d00a57ad/  

![ios_local](https://github.com/getsentry/sentry/assets/31292499/5330e345-312b-480f-89ac-c599ef8e2a14)

#### iOS mixed stack trace from release build symbolicated on the server 
https://krystofs-org.sentry.io/issues/4367437848/events/2b09f1d5104540dbac8da5fc5f0c3bb6/

![ios_server](https://github.com/getsentry/sentry/assets/31292499/638a1ff3-f699-4855-94e8-2027de43ee44)

#### Android mixed stack trace from debug build symbolicated locally 
https://krystofs-org.sentry.io/issues/4323317574/events/76dd7c47f53e48d884392d69692e8334/

![java_local](https://github.com/getsentry/sentry/assets/31292499/dda77da1-6159-4312-8cad-1b82d2bad68c)

#### Android mixed stack trace from debug build symbolicated on the server
https://krystofs-org.sentry.io/issues/4336558830/events/fb5adc200c4b484a80bb94891a18ae06/

![java_server](https://github.com/getsentry/sentry/assets/31292499/ddddb725-2eaa-482d-a1d4-ed30639896ec)

### Solutions

1: Loosen the file extension logic and take the first file extension. I don't know an example where this would fail, but it would make the fallback platform useless.

2: First check if all frames are from the same platform, if so use that icon, if a platform was missing or not the same fallback to file extensions, if file extensions were mixed fallback to `event.platform`.

#### File extensions mapping:
https://github.com/getsentry/sentry/blob/8a85e901e085e2e3b0d9a04cd858348bdddfeb6a/static/app/utils/fileExtension.tsx#L1
#### Fallback platform:
https://github.com/getsentry/sentry/blob/8a85e901e085e2e3b0d9a04cd858348bdddfeb6a/static/app/components/events/interfaces/exception.tsx#L43-L57

**Comment by krystofwoldrich** [comment]
Is there any timeline for this issue?

**Comment by brianthi** [comment]
Hi @krystofwoldrich, there's no timeline yet, other than the Issues team will help with this in Q4. Will update this ticket once we pick up this task.

**Comment by krystofwoldrich** [comment]
Update links to example errors:

### iOS symbolicated on device
https://sentry-sdks.sentry.io/issues/4589159265/events/711a25b962c346dfbb6c6e9903fc6894/

### iOS symbolicated on server
https://sentry-sdks.sentry.io/issues/4589259304/events/f20e42b610e44a8cbfc10ae04ce197c2/

### Android symbolicated on device


### Android symbolicated on server
