### ISSUE TITLE
Complex Saved Search Renders Ugly Input

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#53135]
### Problem Statement

<img width="1068" alt="image" src="https://github.com/getsentry/sentry/assets/7396/782e629b-4188-4d30-8da0-990f0b3c9646">

### Solution Brainstorm

Unclear. But it looks ugly

### Product Area

Issues

**Comment by roggenkemper** [comment]
closing because we have an updated search bar/issue stream where this shouldn't happen
