### ISSUE TITLE
Partial mute incident by tag[s]

### ISSUE THREAD

**Issue by zeldigas** [getsentry/sentry#5314]
It would be great to be able to filter and mute some incidents partially, by tag.

Use case: distributed application with one "location" having more unstable connection. Due to this it's acceptable to receive timeout exceptions from it so it could be muted. At the same time for other locations it's not good, so notifications should still be generated for quick reaction of support team.

I tried to find something similiar with in-house installation of Sentry (Sentry 8.15.0) but could not find anything similiar.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
