### ISSUE TITLE
Jira integration: make Sentry field configurable

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#53142]
### Problem Statement

As soon as Jira is connected to the Sentry app, every issue site-wide has a new field in the issue detail view.

This has a negative UX impact as this field is irrelevant to 99 % of the projects the customer runs on their Jira instance. Please provide a solution to limit this field's visibility to relevant projects.

### Product Area

Settings - Integrations

**Comment by scefali** [comment]
@dalnoki are you saying Sentry shows every possible option for Jira projects? I'm unclear what you mean by "As soon as Jira is connected to the Sentry app, every issue site-wide has a new field in the issue detail view.".

**Comment by GabeVillalobos** [comment]
Closing this due to age + lack of information. If this is still a concern, please open a new github issue with more detail so that we can triage this appropriately.
