### ISSUE TITLE
Highlight environment in the issues view

### ISSUE THREAD

**Issue by Rezrazi** [getsentry/sentry#53202]
### Problem Statement

It would nice to have the environment shown in a more highlighted way in the UI, currently I have to dig in the event tags to determine which env raised the issue.

Some other competitors make this very clear in their UI and it's very UX friendly.

![CleanShot 2023-07-20 at 00 24 10@2x](https://github.com/getsentry/sentry/assets/2086576/65d3b63e-588c-4cf6-8f1c-76e4d6f4523c)

![CleanShot 2023-07-20 at 00 29 54@2x](https://github.com/getsentry/sentry/assets/2086576/4601753f-6432-4a33-af8c-ff19e790a757)

### Solution Brainstorm

Some kind of UI element that highlights in a clear way the environment from which the issue was encountered

### Product Area

Issues

**Comment by armenzg** [comment]
Thanks @Rezrazi for the suggestion! We like it.
I have backlogged it for our team.

**Comment by Rezrazi** [comment]
One thing that could be really nice to add, some other platform do it already, is an indication to the environments affected in the list view 

i tried with a very rough mockup of what I had in mind
![CleanShot 2023-07-27 at 18 58 54](https://github.com/getsentry/sentry/assets/2086576/e201aa7c-b378-4096-88c4-1e2ee2cc6894)

**Comment by roggenkemper** [comment]
Thanks for the additional suggestion! We will keep track of it as we look into this more.

**Comment by pczartoryski** [comment]
Any update of this? It would be very helpful to affected environment on the issues list.

**Comment by jangjodi** [comment]
Hi [pczartoryski](https://github.com/pczartoryski), this is still in our backlog as we are focusing on other initiatives right now. We'll update this ticket with any updates!

**Comment by mrduncan** [comment]
This is now available in the new streamlined experience, currently available in EA! https://github.com/getsentry/sentry/discussions/80801
