### ISSUE TITLE
React Hydration fail errors are not filtered even using Filter out hydration errors in Replay

### ISSUE THREAD

**Issue by jiwon-mun** [getsentry/sentry#53234]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

**it seems related to this issue**
https://github.com/getsentry/sentry/pull/45188

I toggled Filter out hydration option for Hydration error
<img width="640" alt="image" src="https://github.com/getsentry/sentry/assets/109935474/b2457ec5-8372-49f7-9acb-33b89590ea7d">

### Expected Result

there's no hydration errors in replay.

or there's other way to filter amout of replay.

### Actual Result

I expected that the hydration errors which already filtered are not in replay as well.
but this filter only work at issue session.

### Product Area

Replays

**Comment by bruno-garcia** [comment]
Unfortunately Replays don't get the backend filters were created for errors. Not yet anyway, we're tracking this here: https://github.com/getsentry/sentry/issues/44700

**Comment by bruno-garcia** [comment]
I've edited the description to call out this specifically: https://github.com/getsentry/sentry/issues/44700
Please feel free to add comments and a 👍 to help us push this ahead
