### ISSUE TITLE
0302 Migration error (8.14.1 -> 8.15)

### ISSUE THREAD

**Issue by bsergean** [getsentry/sentry#5323]
```
  File "/home/sentry/venv/lib/python2.7/site-packages/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/home/sentry/venv/lib/python2.7/site-packages/sentry/south_migrations/0302_merge_environments.py", line 13, in forwards
    self._forwards(orm)
  File "/home/sentry/venv/lib/python2.7/site-packages/sentry/south_migrations/0302_merge_environments.py", line 89, in _forwards
    to_renv.update(last_seen=last_seen)
AttributeError: 'ReleaseEnvironment' object has no attribute 'update'
```

I tried to add some exception handling over there, to get more details.

```
(Pdb) l
 88  	            last_seen = max([re.last_seen for re in renvs])
 89  	            try:
 90  	                to_renv.update(last_seen=last_seen)
 91  	            except AttributeError:
 92  	                import pdb; pdb.set_trace()
 93  ->	            orm.ReleaseEnvironment.objects.filter(
 94  	                id__in=[re.id for re in from_renvs],
 95  	            ).delete()
 96  	
 97  	    def backwards(self, orm):
 98  	        "Write your backwards methods here."
(Pdb) to_renv
<ReleaseEnvironment: ReleaseEnvironment object>
(Pdb) to_renv.__dict__
{'release_id': 2281L, '_state': <django.db.models.base.ModelState object at 0x767e590>, 'organization_id': 1L, 'environment_id': 7L, 'first_seen': datetime.datetime(2016, 8, 6, 7, 30, 24, tzinfo=<UTC>), 'project_id': 19L, 'id': 15L, 'last_seen': datetime.datetime(2016, 9, 14, 14, 44, 45, tzinfo=<UTC>)}
```

First stack-overflow hit for Django + "object has no attribute 'update'.
http://stackoverflow.com/questions/15304378/django-error-model-object-has-no-attribute-update

**Comment by mattrobenolt** [comment]
That's... really strange...

**Comment by mattrobenolt** [comment]
Oh, I bet somehow, doing `.update` just doesn't work in South and somehow this has literally never come up before. :/ Since this aren't exactly the same Model instances.

@macqueen

**Comment by mattrobenolt** [comment]
@bsergean if you run this by hand, outside of the migration, you would definitely avoid this issue, while we try and figure out what we should even do here.

**Comment by mattrobenolt** [comment]
```python
from django.db import models, transaction, IntegrityError
from sentry.models import Environment, EnvironmentProject, ReleaseEnvironment

dupe_envs = Environment.objects.values('name', 'organization_id')\
                                           .annotate(ecount=models.Count('id'))\
                                           .filter(ecount__gt=1)

for env in dupe_envs:
    name = env['name']
    organization_id = env['organization_id']

    envs = list(Environment.objects.filter(
        name=name,
        organization_id=organization_id,
    ).order_by('date_added'))
    to_env = envs[0]
    from_envs = envs[1:]

    try:
        with transaction.atomic():
            EnvironmentProject.objects.filter(
                environment__in=from_envs,
            ).update(environment=to_env)
    except IntegrityError:
        for ep in EnvironmentProject.objects.filter(environment__in=from_envs):
            try:
                with transaction.atomic():
                    ep.update(environment=to_env)
            except IntegrityError:
                ep.delete()

    from_env_ids = [e.id for e in from_envs]
    try:
        with transaction.atomic():
            ReleaseEnvironment.objects.filter(
                environment_id__in=from_env_ids,
            ).update(environment_id=to_env.id)
    except IntegrityError:
        for re in ReleaseEnvironment.objects.filter(environment_id__in=from_env_ids):
            try:
                with transaction.atomic():
                    re.update(environment_id=to_env.id)
            except IntegrityError:
                re.delete()

    Environment.objects.filter(id__in=from_env_ids).delete()

dupe_release_envs = ReleaseEnvironment.objects.values(
    'release_id', 'organization_id', 'environment_id'
).annotate(
    recount=models.Count('id')
).filter(recount__gt=1)

for renv in dupe_release_envs:
    release_id = renv['release_id']
    organization_id = renv['organization_id']
    environment_id = renv['environment_id']
    renvs = list(ReleaseEnvironment.objects.filter(
        release_id=release_id,
        organization_id=organization_id,
        environment_id=environment_id,
    ).order_by('first_seen'))
    to_renv = renvs[0]
    from_renvs = renvs[1:]
    last_seen = max([re.last_seen for re in renvs])
    to_renv.update(last_seen=last_seen)
    ReleaseEnvironment.objects.filter(
        id__in=[re.id for re in from_renvs],
    ).delete()
```

This should be enough to just run in `sentry shell`

**Comment by bsergean** [comment]
Can I paste the whole thing straight in the shell, or can the sentry shell command take a file ?

Also, this is for 302, is there any other file I need to run ?

**Comment by mattrobenolt** [comment]
I'd actually save this toa  file and run it with `sentry exec ./file.py` to avoid issues with `sentry shell`.

From a quick glance, it doesn't appear that you'd have any issues beyond 302.

**Comment by bsergean** [comment]
ok cool, I'll try this (probably later tonight) and I'll report how it goes

**Comment by bsergean** [comment]
It worked !! Thanks !

(now I'm upgrading to 8.16)

**Comment by bsergean** [comment]
Upgrade to 8.16 was smooth.

**Comment by cactus** [comment]
I ran into this too. thanks for the workaround @mattrobenolt  👍

**Comment by gregwjacobs** [comment]
I upgraded from 8.11 to 8.16 and also hit the same issue/error as above. 

```
File "/usr/local/lib/python2.7/dist-packages/sentry/south_migrations/0302_merge_environments.py", line 89, in _forwards
    to_renv.update(last_seen=last_seen)
AttributeError: 'ReleaseEnvironment' object has no attribute 'update'
```

 The workaround above also worked for me - thanks so much!

I re-ran the 'migrate' django job so remaining migration completed once the workaround was applied as per above, just in case others new to django are reading this.  So migrate, run the workaround following the above error, and re-run the migration (aka ```sentry upgrade``)

**Comment by Mezzle** [comment]
I went from 8.13 to 8.16 and had the same issue as above - workaround also worked for me.

**Comment by dcramer** [comment]
The issue is that there is no ``update`` method on Django's native Model instances. This is something we have built on top of ours. Migrations need to use ``QuerySet.update()``.

**Comment by mattrobenolt** [comment]
Dang, literally didn't register/forgot that `Model.update` was not a native ORM method. We've added this, which is why the migration would never work. :(

I'm going to tag a release today that includes this patch. Sorry about that everyone.

**Comment by jscn** [comment]
Thanks for the fix, @mattrobenolt!

Any chance of getting a new release tagged with this fix included? I'm trying to upgrade our on-premise installation and the Docker image for 8.16 doesn't include the fix.

**Comment by mattrobenolt** [comment]
@jscn I've tagged and pushed 8.16.1. Waiting on https://github.com/docker-library/official-images/pull/2990 now, then it'll be updated in the official Docker repository.

**Comment by jscn** [comment]
Thanks @mattrobenolt, finally got around to doing the upgrade and everything appears to be working well.
