### ISSUE TITLE
Ask for "list" command on Sentry slack app

### ISSUE THREAD

**Issue by jueonpark-dev** [getsentry/sentry#53244]
### Problem Statement

Is there any plan to support a `list` like command on Sentry slack app, so it can list issues that are assigned to me. I think it will be very useful. Thanks! 🙏 

### Product Area

Other

**Comment by brianthi** [comment]
Hi @jueonpark-dev there's no plan to expand the Slack app at the moment to implement a feature like that. In the app, you are able to quickly search for issues assigned to you using the search term, `assigned:me`. Hope this helps!
