### ISSUE TITLE
Design: UI Changes to Dashboards for on-demand metrics

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#53256]
**Problem**: We're introducing the on-demand metrics extraction also to dashboards.
Because the actual metrics extraction only begins once the dashboard widget is saved, there is no historical data to show the customer and this must be explained in the UI.

**Note**: Dashboards are only available to Business customers to begin with, so no plan considerations needed.

**Comment by jan-auer** [comment]
Design is at: https://www.figma.com/file/81N3LMNOSSQLxpR4VoBNZn/Specs%3A-Alerts-%26-On-demand-Metrics?type=design&node-id=69-11444&mode=design&t=pZrMtRNFEEsuYXTl-0

**Comment by ale-cota** [comment]
Designs are also included here, below Alerts: https://www.figma.com/file/81N3LMNOSSQLxpR4VoBNZn/Specs%3A-Alerts-%26-On-demand-Metrics?type=design&node-id=0-1&mode=design&t=Tm7jJXxgbnQ0GfRP-0
