### ISSUE TITLE
Record replay sessions for a certain group of users

### ISSUE THREAD

**Issue by Lezhag** [getsentry/sentry#53257]
### Problem Statement

In our app we give access to test users and admin users which are heavily using the app, but don't have any product value. So these replays are just a waste of time and resources. We would like to exclude these users from session replays. I couldn't find a way of doing it.

### Product Area

Replays

**Comment by bruno-garcia** [comment]
Are you sampling only on error (`replaysOnErrorSampleRate`) or also just sessions (`replaysSessionSampleRate`).
Do you currently capture errors for all sessions (admin/test users included)?

**Comment by Lezhag** [comment]
I have both:
```
replaysSessionSampleRate: 0.1,
replaysOnErrorSampleRate: 1.0
```
So yes, I am capturing all the sessions

**Comment by bruno-garcia** [comment]
> I have both:
> 
> ```
> replaysSessionSampleRate: 0.1,
> replaysOnErrorSampleRate: 1.0
> ```
> 
> So yes, I am capturing all the sessions

Thanks for sharing. That's right, you're capturing 100% of session that have 1 or more errors, and 10% of random sessions, regardless of having an error.

If you want to conditionally sample based on the user, you can set a different value depending on the user in question.

Another alternative, is to not use these sample rates, and use the `start` and `stop` functions programatically. We document how to programatically start/stop recording, here: https://docs.sentry.io/platforms/javascript/session-replay/understanding-sessions/#manually-starting-replay

We understand these are less convenient than having more options built-in to the SDK to control which sessions to sample. There's already a ticket tracking this request, please comment, 👍 and/or subscribe on that one instead: 

* https://github.com/getsentry/sentry-javascript/issues/8462
