### ISSUE TITLE
GitLab webhooks started to 400

### ISSUE THREAD

**Issue by DougEdey** [getsentry/sentry#53266]
### Environment

saas

### Steps to Reproduce

After raising https://github.com/getsentry/sentry/issues/52972#issuecomment-1638046702 and reinstalling our GitLab integration, our webhooks were working fine.

July 20th 9:33am Eastern -> Last good webhook
July 20th 9:42am Eastern -> 400s only

### Expected Result

Webhooks do not return 400s

### Actual Result

<img width="1207" alt="image" src="https://github.com/getsentry/sentry/assets/1833545/8dd3f86d-5cc5-46c7-94de-b73505cc6e1d">

There's nothing in the event response to indicate any issues, I don't see a request ID either.

### Product Area

Settings - Integrations

### DSN

https://bf7e09f1dd06454b9ebe746c572afb66@o1091613.ingest.sentry.io/6108796

**Comment by AniketDas-Tekky** [comment]
@DougEdey Just wondering, did you reinstall your GitLab integration ~8 hours before the 400s started?
You likely need to refresh your tokens: https://docs.sentry.io/product/integrations/integration-platform/public-integration/#refreshing-tokens

**Comment by DougEdey** [comment]
@AniketDas-Tekky Why doesn't Sentry handle this? It seems a bit odd. I think we'll just remove that webhook, it's a shame since there may have been value but I don't want to maintain a script to do this.

**Comment by AniketDas-Tekky** [comment]
@DougEdey I took another look at this yesterday. When you reinstalled the app, did you uninstall it on both the GitLab and Sentry side? or just Gitlab?
The reason I ask is because I only see your old installation of gitlab in our database, and the errors are a result of the webhook secrets not matching.

**Comment by DougEdey** [comment]
I uninstalled in Gitlab and Sentry, something caused it to be uninstalled in Gitlab (we can't find out who did it) and deletng from sentry took a significant amount of time (multiple hours) before I couldn't see it.

Right now, the integration is working for us to create GitLab issues which is fine enough, we're moving off GitLab soon.
