### ISSUE TITLE
Merge / Delete menus missing on Issues mobile view

### ISSUE THREAD

**Issue by pokrovskyy** [getsentry/sentry#5329]
I can still delete from a single error view but this is not much convinient. Not sure if it's a bug or intended to be so, but I really miss these 2 options somewhere next to Resolve on the mobile view (using iPhone 6S)

**Comment by dcramer** [comment]
Sounds like an oversight. I'll admit we dont often do a great job in evaluating mobile views (or optimizing them).

**Comment by pokrovskyy** [comment]
Well that would be great to have. I use mobile to keep an eye on the heartbeat of my app and having these features to clear / merge errors would be great. Any timeframe to expect these available in the mobile view anytime soon?

**Comment by dcramer** [comment]
I'll be transparent and say it's not going to be a big short term priority for us. It's possible someone will pick it up and solve it but we have so many other projects right now and tackling mobile usability has quite a few things to resolve.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
