### ISSUE TITLE
transaction.status not properly translating when exported via discover

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#53292]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to discover
2. Build query including transaction.status as a column
3. Click Export All
4. Open up the csv file in your email.

**Discover query view before export -**
<img width="1234" alt="Screenshot 2023-07-20 at 2 02 55 PM" src="https://github.com/getsentry/sentry/assets/96670625/48269bcd-3b2c-4cec-a994-b10b7e453083">

**Exported csv with transaction.status as numerical values -** 
<img width="491" alt="Screenshot 2023-07-20 at 2 02 41 PM" src="https://github.com/getsentry/sentry/assets/96670625/813f1198-8d39-4a98-ad96-361d406f417b">

### Expected Result

Exported csv file should be consistent with discover query view

### Actual Result

exported csv file has numerical values of for transaction.status with no way to know what they refer to.

### Product Area

Discover

**Comment by brentc** [comment]
Yep, this is a bug. We'll look into getting it fixed.

**Comment by Abdkhan14** [comment]
This has been fixed. Transaction columns are now names instead of codes in async export.
