### ISSUE TITLE
Spike Protection - Webhook integration for spike protection notifications

### ISSUE THREAD

**Issue by vtoklu** [getsentry/sentry#53332]
### Problem Statement

Currently, Sentry has the following notification actions for the spike protection feature:
- Send a Sentry notification
- Send a Slack/Pagerduty notification

It would be great to add Webhook as another notification action to spike protection settings. This would enable calling a pre-defined endpoint which could be particularly useful for organizations using an internal notification router. 

### Product Area

Settings - Spike Protection

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1885) by [Unito](https://www.unito.io)

**Comment by brianthi** [comment]
Closing as it's unlikely we would implement this.
