### ISSUE TITLE
iOS Symbolication Iteration

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#5335]
There are currently some issues that have not been fixed because they affect grouping. It's however becoming clear we should fix them going forward. Here a list of problems I want to fix before we go live with reprocessing by default:

* [x] strip the leading `_` on system symbols
* [ ] improve `in_app` detection (swift frameworks should not be in app, but non app frameworks should still be in app. Maybe we can improve the logic for known frameworks?)
* [x] strip path prefix from abs_path based on comp_dir dwarf info
* [x] only use basename for grouping for non system frames
* [x] single thread grouping (https://github.com/getsentry/sentry/pull/5246)
* [x] release https://github.com/getsentry/sentry-cli/issues/60
* [x] release and merge https://github.com/getsentry/sentry/pull/5346

There is more to come but this is my currently list.

**Comment by mitsuhiko** [comment]
This is related: https://github.com/getsentry/sentry-cli/issues/60

**Comment by BYK** [comment]
Closing this issue due to staleness. I think this is mostly done anyway.
