### ISSUE TITLE
Incorrect Alert Conditions UI

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#53382]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Configure an alert to fire when the number of events is X% higher in one day compared to one week ago.
<img width="886" alt="image" src="https://github.com/getsentry/sentry/assets/99350819/6d864e1b-3139-4204-95ee-0c803d8d592d">

2. Save the alert 
3. Observe the UI on the alert details page says it will fire when the number of events is X% higher in 1 week compared to day ago.
<img width="353" alt="image" src="https://github.com/getsentry/sentry/assets/99350819/89972965-0b42-44c8-bd31-85321eeb4629">

### Expected Result

alert details should show "Number of events in an issue is X% higher in 1d compared to 1w ago"

### Actual Result

alert details shows "Number of events in an issue is X% higher in 1w compared to 1d ago"

### Product Area

Alerts

### Link

https://org2-w7.sentry.io/alerts/rules/testreact/14559481/details/

**Comment by barkbarkimashark** [comment]
Woops, this looks like we swapped the text in the display text. I've created a PR to fix this issues. Thanks for reporting it!
