### ISSUE TITLE
"Celery workers are referencing a different version of Sentry (8.16.0 vs 8.15.0)"

### ISSUE THREAD

**Issue by salzig** [getsentry/sentry#5342]
I'm unsure how to handle this situation. Cron/Worker/Web use the same image and run on the same host. 

# The version of Sentry you're using
Docker Image: sentry:8.16

# Whether you're using Docker or another installation 
Docker 17.04.0-ce

# Include a stacktrace or other logs when relevant
Web UI shows me "Celery workers are referencing a different version of Sentry (8.16.0 vs 8.15.0)", so far unable to find an error in the logs. 

# Include a redacted version of your configuration when relevant
no special configuration beside `SENTRY_SINGLE_ORGANIZATION: 'false'`

**Comment by dcramer** [comment]
Please use our support forums as this is either a configuration or operational error.

**Comment by salzig** [comment]
Thats an error after upgrading to 8.16. 8.14 and 8.15 didn't show that message. No configuration was changed in that time.
