### ISSUE TITLE
Improve "invited member joining" flow

### ISSUE THREAD

**Issue by ehfeng** [getsentry/sentry#5343]
Users often accidentally create a new organization when signing up via the invite flow.

**Comment by farhaanbukhsh** [comment]
Hey I would like to work on the issue I am new to the project can someone guide me to get started ?

**Comment by ngubin** [comment]
Oh yes, the ability to prohibit users from creating an organization is not enough. Just invite the user to the existing organization and prevent him from creating his own.

**Comment by ehfeng** [comment]
This issue needs a lot more detailed thinking (particularly UX and design) on what the flows might be. Probably not an "easy task" for now, removing.

**Comment by BYK** [comment]
I think @EvanPurkhiser fixed this flow a while ago so this no longer should be an issue. Please file a new issue if you think there's more work to be done here.
