### ISSUE TITLE
Getting error "The organization you were looking for was not found." when trying to access session replays

### ISSUE THREAD

**Issue by xliee** [getsentry/sentry#53431]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

When you access the replays list (in https://example.com/organizations/{organization_slug}/replays) 
and click one of the replays, it redirects you to, `https://example.com/replays/1461d5f133fa4e8d8914b607b314efcb/...`
there appears this error
![image](https://github.com/getsentry/self-hosted/assets/40280035/679c4c8c-1605-4ffc-8afd-1e0f9a3cda0c)

The correct url should indeed be `https://example.com/organizations/sentry/replays/1461d5f133fa4e8d8914b607b314efcb/...`
![image](https://github.com/getsentry/self-hosted/assets/40280035/5ca8808c-191d-4d92-984b-c0c00293fed6)

The `organizations/${organization.slug}/` is missing (https://github.com/getsentry/sentry/pull/52933/files#diff-deb3934bfd12ee1ede62177d72424cfe226a9a3a15d97feb36588b9e3f8ebbba)

The bug was introduced as a solution to #51541 in #52933 PR.
This issue is a duplicate from https://github.com/getsentry/self-hosted/issues/2291

### Expected Result

`https://example.com/replays/1461d5f133fa4e8d8914b607b314efcb/`

### Actual Result

`https://example.com/organizations/sentry/replays/1461d5f133fa4e8d8914b607b314efcb/`

### Product Area

Replays

### Version

Sentry 23.8.0.dev0 97c76f2

**Comment by JoshFerge** [comment]
noticed internally as well: https://github.com/getsentry/team-replay/issues/116. will prioritize a fix here!

**Comment by bruno-garcia** [comment]
@xliee A fix was merged:
* https://github.com/getsentry/sentry/pull/53451

Could you please update to the latest commit and let us know it solved the problem?

**Comment by alkanna** [comment]
@bruno-garcia Updated to latest commit and can confirm it's working great now, thanks !

**Comment by xliee** [comment]
> @xliee A fix was merged:
> 
> * [fix(replay): Normalize urls that link into replay details #53451](https://github.com/getsentry/sentry/pull/53451)
> 
> Could you please update to the latest commit and let us know it solved the problem?

Yes it is fixed. Thanks!

**Comment by bruno-garcia** [comment]
Thanks!
