### ISSUE TITLE
Feature Request: Ability to add error count in the email header

### ISSUE THREAD

**Issue by sauliusgrigaitis** [getsentry/sentry#5348]
We migrated from Errbit to Sentry and we really miss error count in the header. Errbit sends 10th, 100th repeating error and includes the number in the title so it makes very clear how severe is the issue just by looking at the email title. I see two possible implementations for this:

1) Allow to set different email titles, so different rules can use different email titles. Then it would be possible to hardcode error count into email titles.
2) Allow accessing error count variable in the email headline. I prefer it as it's more flexible.

Thanks!

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
