### ISSUE TITLE
Crons monitoring Timeouts on checkin, even though the ok event is successful

### ISSUE THREAD

**Issue by Dave13h** [getsentry/sentry#53503]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

We have a CronJob that runs every 2 minutes, it starts the InProgress event, runs the job then sends the Ok event.

We're using the PHP SDK - https://github.com/getsentry/sentry-php 

It seems to go through phases of successful checkins from 8am (BST) then it deteriorates throughout the day. The Ok event always seems to succeed (which we expect because we can see the result of the job running throughout the day, so we're pretty confident that the job is succeeding).

This is happening on all the monitors we have set up in our account.

### Expected Result

Check-in and Ok events showing as successful in the monitor view.

Also a little odd that this doesn't seem to be raising an Issue, should it? The check-in is technically failing but the Ok event comes in pretty quick, so maybe that's the right behaviour?

### Actual Result

<img width="1056" alt="image" src="https://github.com/getsentry/sentry/assets/13381774/acf6085d-b47c-400e-b46f-ad03f86241c1">

<img width="1079" alt="image" src="https://github.com/getsentry/sentry/assets/13381774/b03bf499-89e1-46d1-9c92-c5437417c013">

### Product Area

Crons

### Link

https://d3r.sentry.io/crons

**Comment by rjo100** [comment]
Hi!

You're correct about the issues, since we have the successful check-in we don't create the issue.

As for the timed out check-ins, are you "closing" the check-in by sending the same `id` with the `OK` check-in?
See the line `id: $checkIn->getId(),` here:
https://docs.sentry.io/platforms/php/crons/#check-ins-recommended

**Comment by Dave13h** [comment]
Hi @rjo100 

Thanks for the quick reply, yes we are using the `getId()` from the checkin event. Is there anything you can see from your side to confirm that the id's match possibly? This was working fine when we launched the change back in May. I'm unsure when it stopped working because we were expecting the issue to track when there were any problems. 

Thankfully the ok event is providing us some good logging.

**Comment by rjo100** [comment]
Unfortunately there's nothing on the backend that's indicating anything in particular. Is it possible it's generating multiple `in_progress` check-ins at  the start? The timed out check-ins indicate that a check-in is being created but we don't receive a closing `ok/error` check-in with the same `id`.

**Comment by Dave13h** [comment]
Hi @rjo100 

I've just done a bit of testing and I can see that the In Progress event has the following ID then it's being sent in the OK event..

```
string(5) "in_progress"
object(Sentry\EventId)#1937 (1) {
  ["value":"Sentry\EventId":private]=>
  string(32) "1ecf36d9532a48729f37a3c79a173b81"
}

string(2) "ok"
object(Sentry\EventId)#1937 (1) {
  ["value":"Sentry\EventId":private]=>
  string(32) "1ecf36d9532a48729f37a3c79a173b81"
}
```

This slug matches too, it shouldn't be possible to run this script multiple times concurrently either as we have a locking mechanism to prevent that. Any else you can think of to aid debugging this?

Thanks!

**Comment by cleptric** [comment]
@Dave13h, mind sharing your code that creates the check-ins? I just want to validate that it is set up correctly on the PHP side.

**Comment by Dave13h** [comment]
Hi @cleptric thanks for looking.. here is basically what we are doing, I've had to anonymise a few little bits because its from a private repo, hope that's ok.

Helper class

```
class Helper 
{
    const SENTRY_OK = 'ok';
    const SENTRY_ERROR = 'error';

    /** @var array Sentry Cron Events */
    protected static $sentrySlugs = [];

    /**
     * Sentry Begin Event.
     */
    public static function sentryBegin(string $slug)
    {
        $slug = self::formatSentrySlug($slug);
        if (array_key_exists($slug, self::$sentrySlugs)) {
            throw new Exception(sprintf('Slug[%s] Event already created!', $slug));
        }

        $event = SentryEvent::createCheckIn();
        $event->setCheckIn(
            new SentryCheckIn(
                $slug,
                SentryCheckInStatus::inProgress(),
                null,
                static::getRelease(),
                static::getConfigName()
            )
        );

        SentrySdk::getCurrentHub()->captureEvent($event);

        self::$sentrySlugs[$slug] = $event;
    }


    /**
     * Sentry End Event.
     */
    public static function sentryEnd(string $slug, string $outcome, ?float $timeTaken = null)
    {
        $slug = self::formatSentrySlug($slug);
        if (!array_key_exists($slug, self::$sentrySlugs)) {
            throw new Exception(sprintf('Slug[%s] Event doesn\'t exist!', $slug));
        }

        $beginEvent = self::$sentrySlugs[$slug];

        // Just incase the script finishes too quickly, pad some
        // extra time before the end event so hopefully sentry
        // has processed the first event before this one.
        sleep(1);

        $event = SentryEvent::createCheckIn();
        $event->setCheckIn(
            new SentryCheckIn(
                $slug,
                $outcome == self::SENTRY_OK ? SentryCheckInStatus::ok() : SentryCheckInStatus::error(),
                (string) $beginEvent->getId(),
                static::getRelease(),
                static::getConfigName(),
                $timeTaken
            )
        );

        SentrySdk::getCurrentHub()->captureEvent($event);
    }

    /** 
        [...] other methods
    */
}
```

In Script -

```
$helper::sentryBegin(SCRIPT_NAME);

// Do the thing

$helper::sentryEnd(SCRIPT_NAME, $helper::SENTRY_OK, DebugTools::stopTimer(SCRIPT_NAME));

```

One thing I was wondering, the `SentrySdk::getCurrentHub()->captureEvent($event);` actually returns the last event id without modifying the original event object, that would be the same event id right?

**Comment by cleptric** [comment]
Your problem is that you don't use the same check-in ID.
See https://docs.sentry.io/platforms/php/crons/#check-ins-recommended

The second check-in with the status `ok`/`error` has to have the same ID as your first `in_progress` check-in.

**Comment by Dave13h** [comment]
@cleptric 
Oh I see, I need the id from the `SentryCheckIn` not the `SentryEvent::createCheckIn` ?

**Comment by cleptric** [comment]
Correct, the event ID is something else and will vary, as these are two different events. The check-in ID is what we use to correlate check-ins together.

**Comment by Dave13h** [comment]
Amazing, thank you so much for your help. I'll get this updated today 🙏

**Comment by Dave13h** [comment]
Confirming this was the issue. Thank you both for the assistance!
