### ISSUE TITLE
Global Fatal Error Handler argument order in docs is wrong

### ISSUE THREAD

**Issue by akleiber** [getsentry/sentry#5350]
This is for **node-raven v1.2.1**

The docs say:
https://docs.sentry.io/clients/node/usage/#global-fatal-error-handler

```javascript
Raven.install(function (err, sendErr, eventId) {
  ...
});
```

The code says:
https://github.com/getsentry/raven-node/blob/v1.2.1/lib/client.js#L531

```
var eventId = client.captureException(reason, function (sendErr) {
  cb && cb(!sendErr, reason);
});
```

So while the docs say the first argument is the error in reality the first argument is the boolean that says if there was an error while calling `captureException` and the second argument is the error from raven.

Furthermore `eventId` is never injected into the callback `cb`. 🙈

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
