### ISSUE TITLE
Sentry UI shows slug as team name instead of the name field 

### ISSUE THREAD

**Issue by vips-sharma** [getsentry/sentry#53593]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Used terraform sentry provider with sentry_team resource to create the team ( passing name and slug arguments )
2. name parameter is not displayed while slug is displayed in place of name and slug fields on the UI.
3. Checked the name parameter is passed properly using the api : https://sentry.io/api/0/organizations/<your-org>/teams/

resource "sentry_team" "tf_api" {
  organization = data.sentry_organization.main.id
  name         = "tf-api"
  slug = "tf-ui"
}

<img width="405" alt="image" src="https://github.com/getsentry/sentry/assets/138785075/0eda817d-7b52-411c-8593-d8793f07e296">

<img width="700" alt="image" src="https://github.com/getsentry/sentry/assets/138785075/4f9c5f85-2d17-468c-9142-1b5e82dff754">

### Expected Result

name parameter to be displayed as team name ( tf-api for above use case )

### Actual Result

<img width="616" alt="image" src="https://github.com/getsentry/sentry/assets/138785075/79172dac-dae2-42a4-bfd6-30c51f22f3a0">

### Product Area

Settings - Teams

**Comment by Dhrumil-Sentry** [comment]
Hi @vips-sharma - The team slug is what is used in our UX- the team name field in our API is mainly used to help sync teams with SCIM etc. We take the name fields from SCIM integrations and slugify them to create team-slug.

I'd suggest passing the desired name into the team-slug itself.
