### ISSUE TITLE
SourceMap Path Match with electron

### ISSUE THREAD

**Issue by meveno** [getsentry/sentry#53609]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Upload source maps
Run electron
Have an error
Check in sentry.io

### Expected Result

The source Maps are correctly mapped

### Actual Result

As in electron the source URL is user-relative to path match does not work properly.

```
We've encountered 1 problem un-minifying your applications source code!
Partial Absolute Path Match

The abs_path of the stack frame is a partial match. The stack frame has the path file:///C:/Users/username/AppData/Local/Programs/altere/resources/app.asar/dist/src/index.d47c85cc.js which is a partial match to ~/src/index.d47c85cc.js. You need to update the value for the URL prefix argument or `includes` in your config options to include
```

I'm aware that we can set an url-prefix but with electron the url prefix depends on the username

### Product Area

Issues - Source Maps

### Link

https://ovalt.sentry.io/issues/4341615511/?project=6474955&query=is%3Aunresolved&referrer=issue-stream&stream_index=1

### Version

7.42.0

**Comment by lforst** [comment]
Hey, if the filenames in the stack traces depend on some dynamic parameter you should use the [`RewriteFrames` integration](https://docs.sentry.io/platforms/javascript/configuration/integrations/plugin/#rewriteframes) to match the paths from the stacktrace with the uploaded artifacts.

Another option for you is to update your SDK to the newest version and use one of our [bundler plugins](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/) or [Sentry CLI to upload sourcemaps](https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/cli/). Here we have a new process that won't require you to match names of artifacts. It's a little more robust and easier to set up.

**Comment by meveno** [comment]
Ok I will try this
