### ISSUE TITLE
"View active issues" links to new issue

### ISSUE THREAD

**Issue by G-Rath** [getsentry/sentry#5362]
Sentry version: Sentry 8.17.0.dev0

On the support page for Sentry, where it says 'Follow development of Sentry as it happens. You can also view active issues or create a new issue.', the links for 'view active issues' and 'create a new issue' are the same. 

```
<p>
    Follow development of Sentry as it happens. You can also <a href="https://github.com/getsentry/sentry/issues/new">view active issues</a> or <a href="https://github.com/getsentry/sentry/issues/new">create a new issue</a>.
</p>
```

(I'm a little unsure if this should be on the community form or not, since it's a pretty small 'bug', so sorry if it's in the wrong place :) )

**Comment by mattrobenolt** [comment]
Thanks. This was fixed, but in our internal repository. 🍦
