### ISSUE TITLE
Update Organization Settings > Early Adopter description url

### ISSUE THREAD

**Issue by sdzhong** [getsentry/sentry#53662]
https://github.com/getsentry/sentry/blob/b9a3f269eb68031d616b200ac0ca3d541efc7635/static/app/data/forms/organizationGeneralSettings.tsx#L41

https://docs.sentry.io/product/accounts/early-adopter/ 404's. I believe the reference should be https://docs.sentry.io/product/accounts/early-adopter-features/

<img width="1135" alt="image" src="https://github.com/getsentry/sentry/assets/89550162/d7a1d66c-4416-4b25-a171-6eb0009695cb">

**Comment by shanamatthews** [comment]
Uh oh, looks like the redirect @lizokm put in in https://github.com/getsentry/sentry-docs/pull/7481 didn't work. Let me take a look at why that redirect isn't redirecting.
