### ISSUE TITLE
libswiftCore needed?

### ISSUE THREAD

**Issue by pvinis** [getsentry/sentry#5367]
Sentry version:  Sentry 8.17.0.dev0
Using on sentry.io
--

When an event is reported, I get an error that an optional symbol was not included and its this
```
{
  "image_arch": "arm64",
  "image_uuid": "900e59d2-1c9f-3a43-9d3a-e552a289103f",
  "message": "None",
  "image_path": "/private/var/containers/Bundle/Application/3A3AE185-4757-4850-8407-F5D635399863/Bla.app/Frameworks/libswiftCore.dylib"
}
```
Why is this even optionally required?
What does this mean?
What would we gain from having this?

PS: the crash is caused by the `Sentry.crash()` method, so its a purposeful crash.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
