### ISSUE TITLE
Add ability to mark a transaction as "DO NOT DROP", so the request is guaranteed to be indexed

### ISSUE THREAD

**Issue by RaduW** [getsentry/sentry#53685]
### Problem Statement

From an internal user:

> I'd give anything for the ability to say "Hey Sentry for this 1 request, sample it no matter what", this is a really big part of my debug workflow where I want to see the specific sample of a request.
> For example
> Somebody comes to me with "Hey X in discover isn't working", I try that query myself to see if it is or isn't working and it broke. I'd like to see that sample
> I got a performance fix into production and I want to see immediately whether or not the fix is doing what I wanted
> The current way I'm working around this is to just take the trace of a sampled event, and modify the request so that it sends the same trace id so I can get samples again.

### Product Area

Unknown

**Comment by matejminar** [comment]
We'll have a proper EPIC for this in Q3: https://github.com/getsentry/sentry/issues/54094

**Comment by matejminar** [comment]
We'll have a proper EPIC for this in Q3: https://github.com/getsentry/sentry/issues/54094
