### ISSUE TITLE
Almost every issue has message "Source code was not found"

### ISSUE THREAD

**Issue by karolina-szlenk** [getsentry/sentry#53716]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Self-hosted/on-premise

### Which SDK are you using?

@sentry/nextjs

### SDK Version

7.57.0

### Framework Version

Next - 12.2.6

### SDK Setup

**sentry config**
```
const config: (browser: boolean) => Parameters<typeof Sentry.init>[0] = (
    browser: boolean,
) => {
    return {
        dsn: SENTRY_DSN,
        tracesSampleRate: 0.3,
        environment: SENTRY_ENVIRONMENT,
        denyUrls: [...],
        integrations: browser
            ? [
                  new Sentry.BrowserTracing({
                      tracingOrigins: [...],
                  }),
              ]
            : [],
        ignoreErrors: [...],
        beforeSend(event, hint) {
            ...
        },
    };
};
```

**sentry.client.config**
```
if (SENTRY_DSN && SENTRY_ENVIRONMENT) {
    Sentry.init(config(true));
} else {
    console.info('Running application without Sentry');
}
```

**sentry.server.config**
```
if (
    SENTRY_DSN &&
    SENTRY_DSN !== '#{sentryDSN}#' &&
    SENTRY_ENVIRONMENT &&
    SENTRY_ENVIRONMENT !== '#{sentryEnvironment}#'
) {
    Sentry.init(config(false));
} else {
    console.info('Running application without Sentry');
}
```

### Steps to Reproduce

1. Go to Sentry issues section
2. Open an issue with issue exception that comes from your code 
3. Look at a messages section
4. Look at an exception section
5. Go to sentry-cli and try to figure it out

### Expected Result

- Sentry sends a message in situation when indeed the source map are missing.
- Sentry does not send a message when we actually see a source of error.
- `sentry-cli` gives more info about the exception.

### Actual Result

I have seen that a message with info `Source code was not found` happens in almost each Sentry issue recently. In some of them, I actually see that pinpointing where the error happened works fine. 
An issue that looks familiar and the exception message comes from my source code
![image](https://github.com/getsentry/sentry-javascript/assets/59310977/3e066c32-54c2-4d2d-8311-ecf726d5c84a)
Messages in this issue show me that the source maps were not found and are invalid
![image](https://github.com/getsentry/sentry-javascript/assets/59310977/b1f3f02e-a56f-48be-a8b2-4636c6cdb086)
Exception section in this issue shows me the exact file and line in my source code, where the error happened
![image](https://github.com/getsentry/sentry-javascript/assets/59310977/e8d27e19-c16d-49ae-86fa-6619f3b1bee5)
It is vague for me and try to verify this exception in sentry-cli, but received that actually the exception is already source mapped but points to empty lines. I
![image](https://github.com/getsentry/sentry-javascript/assets/59310977/22c804de-80bc-4b14-9616-69af6b4dc7bd)

**Comment by roggenkemper** [comment]
Would you mind posting a screenshot of the entire details page for the issue? you can email it to me at richard.roggenkemper@sentry.io if you don't want to post it on github.

**Comment by lforst** [comment]
I believe this is not an issue anymore.
