### ISSUE TITLE
Replay Index: Error message does not align with search condition for `duration`

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#53735]
**Problem**

I used 's' to represent seconds at the end of the value for the key:value pair for duration and the error message tells me to use 'k', 'm', 'b' which is not related to units for duration.

![Image](https://user-images.githubusercontent.com/77064737/256648292-8f600d5a-ccff-4cc0-a0f8-4bf928931c3d.png)

Adding the unit at the end of a duration query is what we do for `transaction.duration`, so I was used to that pattern. 

I'd expect the error message on Replay Index to either tell me that the syntax doesn't require units. Or, we end up supporting 's' for seconds, and 'm' for minutes.

**Proposed Solution**

Remove the incorrect error message that says to use 'k', 'm', and 'b'.

Accept 's' and 'm' units for `duration`. 
This would be matching the behaviour we have in Discover: for `transaction.duration`: https://sentry.sentry.io/discover/homepage/?field=transaction.duration&field=transaction&name=All+Events&project=11276&query=transaction.duration%3A%3E5m&sort=transaction.duration&statsPeriod=14d&yAxis=count%28%29

Currently, we default duration to always be seconds and don't accept units.

**Comment by billyvg** [comment]
Looks like it thinks duration is a file-size type field instead of a duration/time based one.

**Comment by michellewzhang** [comment]
so i'm looking into this and i think the `k, m, b` refer to `"k": 10.0**3, "m": 10.0**6, "b": 10.0**9` second suffixes rather than file sizes. the replay `duration` number is always in seconds so i don't think we can search by a different granularity atm

**Comment by jas-kas** [comment]
@michellewzhang So can we just alter the error message shown? I'd expect the error message on Replay Index to either tell me that the syntax doesn't require units or say that we only support seconds. The current error message is confusing (see screenshot) IMO.

**Comment by michellewzhang** [comment]
<img width="1244" alt="SCR-20240617-jamr" src="https://github.com/getsentry/sentry/assets/56095982/1d228694-d1fd-4afd-92c0-012295d2dd2e">
@jas-kas looks like the search failure returns a different message now

**Comment by michellewzhang** [comment]
it was introduced in this PR: https://github.com/getsentry/sentry/pull/66282

**Comment by jas-kas** [comment]
@michellewzhang Hmm that's not a super specific message, but it is accurate! It's an invalid search param. Closing

**Comment by souredoutlook** [comment]
The Error message was noted here but this cause of the error is new: https://github.com/getsentry/sentry/issues/53735
