### ISSUE TITLE
Would be great to have more compact view of issue extras / breadcrumb datas

### ISSUE THREAD

**Issue by erictheswift** [getsentry/sentry#53758]
### Problem Statement

As we add more `breadcrumb.data` as well as `event.extra`, page expands in height a lot and focus goes away from breadcrumb messages/etc.

E.g. breadcrumb.data must always be an object (has always 1 level wrapper — it's +40px height (significant) and  40px width (less significant but also neater for me without it) loss)

### Solution Brainstorm

By applying -20px margin to `<pre>` wrapper I can see the same data with more information density

![image](https://github.com/getsentry/sentry/assets/2434839/83364da3-c9d1-4c23-bc96-5a6b17dc98b7)

### Product Area

Issues

**Comment by scttcper** [comment]
new breadcrumbs should be a bit more compact https://sentry.io/changelog/improved-breadcrumbs-on-issues/
