### ISSUE TITLE
Alert for same issue is sent multiple times on the same service if two rules match the alert

### ISSUE THREAD

**Issue by marcosalles** [getsentry/sentry#5375]
I have contacted support and they redirected me here, so I'll describe my situation.

I have a few sets of rules for alerts on a project. Two of them are as follows:
```
RULE1 (Spam):
  When all of these conditions are met:
    - An event is seen
    - An event's message value does not contain "some message"
  Take these actions at most once every 5 minutes for an issue:
    - Send a notification via slack

RULE2 (Critical):
  When any of these conditions are met:
    - An event is seen more than 5 times in 1m
    - An event is seen by more than 5 users in 1h
  Take these actions at most once every 60 minutes for an issue:
    - Send a notification (for all enabled services)
```
I would have expected to receive a slack message and an email about the same issue, but the thing is: apparently the rules are not exclusive. So I eventually get the same message for the same issue at the same time on slack because it matches both rules.

It shouldn't happen, the rules should be exclusive between themselves for a single notification service.

I know I can just filter the enabled services on RULE2 but that seems like a bug either way (and a waste of your resources, for sending an alert for the same issue twice).

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by marcosalles** [comment]
Quite stale indeed I'll check if there is still an issue when I get the chance. Ty for  closing!
