### ISSUE TITLE
Failure to upload sentry symbols for C++/native app

### ISSUE THREAD

**Issue by bsergean** [getsentry/sentry#53760]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

See https://github.com/getsentry/sentry-cli/issues/1699

1. sentry-cli upload-dif /path/to/binary --wait
2. An error happens: I don't think it's related to sentry-cli.

### Expected Result

Symbol files can be uploaded.

### Actual Result

```
    ERROR mediationserver_cli
        An unknown error occurred
```

### Product Area

Other

**Comment by amonshiz** [comment]
We appear to be having a similar issue starting today sometime between 2:45pm Eastern and 3:15pm Eastern. Our error is the same. We know of no changes on our end that could have lead to this. The logs from `sentry-cli` are unfortunately not helpful.

```
> Found 12 debug information files
> Prepared debug information files for upload
> Uploaded 2 missing debug information files
> File upload complete:

    ERROR Arc
        An unknown error occurred
    ERROR Arc
        An unknown error occurred
```

**Comment by amonshiz** [comment]
Not to speak too soon, but we just had our uploads begin working again.

**Comment by bsergean** [comment]
Yes it's working for us now too. There was a maintenance mentioned in the status.sentry.io site, maybe that was it.

**Comment by olksdr** [comment]
Hey,
thanks for reporting this.
Looks like everything is fixed now. 
Closing this issue. Please, reopen if there are any issues again. Thanks!
