### ISSUE TITLE
alerts:write scope not respected for metric alert creation

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#53807]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

**Description:**
Users with Member roles cannot create metric alerts with the "Let Members Create and Edit Alerts" org setting active. Users can setup the alert, however upon saving they receive a permissions error. Potentially related to the sentry:alerts_member_write option.

Steps:
1. Activate _"Let Members Create and Edit Alerts"_ in general settings
2. As a member -> attempt to create a metric alert at stepping through to save portion

### Expected Result

Ability for members to create metric alerts

### Actual Result

Members can edit metric alerts but cannot create them.

### Product Area

Settings - General

**Comment by cseas** [comment]
Hi, any update on this bug? Right now do we need to be at least a team admin for creating alerts?

**Comment by roggenkemper** [comment]
the fix was merged in this morning!
