### ISSUE TITLE
Investigate the discrepancies in extrapolated alert charts

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#53842]
https://sentry.sentry.io/alerts/rules/details/162912/

![Image](https://github.com/getsentry/sentry/assets/9060071/4791e06e-8adb-4752-85a6-e9a6441b369d)

![Image](https://github.com/getsentry/sentry/assets/9060071/e3986577-dbd7-48e4-a17b-bf85fd64304a)

**Comment by RaduW** [comment]
Ognjen will implement a different approach ( get the rate by querying a normal metric via indexed and metric and deriving a rate at each point).
