### ISSUE TITLE
[SPIKE] - Check if we can replace the current specific profiling and replay docs with the migrated ones

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry#53861]
In the sentry-docs repository, we have specific onboarding documentation for profiling and replay. As part of our ongoing improvement efforts, it's essential to analyze these docs and determine if we can replace them with the docs that we have now in our sentry main repo.

**Comment by ArthurKnaus** [comment]
Findings and proposal in https://github.com/getsentry/sentry/issues/56387
