### ISSUE TITLE
Team Admin - Debug Symbols cannot be removed from project settings

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#53919]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Log in as a team admin
2. Go to project with debug symbols uploaded
3. Try to remove one of the symbols

### Expected Result

I would expect to delete the debug symbols because of the team admin role my user has like mentioned in the banner on the top of the first screenshot

### Actual Result

<img width="1615" alt="Screenshot 2023-08-01 at 10 11 12" src="https://github.com/getsentry/sentry/assets/25929053/767b7348-dabb-4925-aa07-4fab7e3bba43">
<img width="1557" alt="Screenshot 2023-08-01 at 10 11 28" src="https://github.com/getsentry/sentry/assets/25929053/4342f0e2-e076-4f9d-b58e-93457890122d">
<img width="1590" alt="Screenshot 2023-08-01 at 10 11 34" src="https://github.com/getsentry/sentry/assets/25929053/38a68e09-aabb-4db5-a801-3a7c3940feb3">

### Product Area

Settings

### Link

https://super-mario.sentry.io/settings/projects/chaos-planner/

**Comment by Dhrumil-Sentry** [comment]
Hi @Angelodaniel - Thanks a for raising- Team Admins should be allowed to do this- @leedongwei something for us to fix

**Comment by Dhrumil-Sentry** [comment]
@leedongwei another issue that asks for team admin access to debug files: https://github.com/getsentry/sentry/issues/55975
