### ISSUE TITLE
Sorting by last seen does not honor tag filters

### ISSUE THREAD

**Issue by dmwtf** [getsentry/sentry#53922]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

We have dosen of application deployments which report issues to the same Sentry project (use the same DSN). They all differs by `environment` tag.
Wenn I open default `Issues` view all issues are sorted correctly by "Last Seen" date.
Couple of weeks ago if I would select some specific environment tag I would see Issues sorted by last occurence of issue in my selected environment.
Today I see something "unsorted". I suppose I still see issues sorted by last occurences in ALL evironments showing me last occurence in my selected environment. 

### Expected Result

I would like to see as before issues sorted by last occurence my selected environment. Events happened in other enviroments should not affect sorting.

### Actual Result

![grafik](https://github.com/getsentry/sentry/assets/128166295/106a3bf3-2a44-4f45-af12-3f399a788dda)

### Product Area

Issues

**Comment by malwilley** [comment]
For future reference, [this was the reverted PR](https://github.com/getsentry/sentry/pull/53321). I'm no longer able to reproduce so am closing the issue. Please comment again if you have more troubles with this!
