### ISSUE TITLE
[EPIC] Source SDK versions from release registry

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#53921]
### Problem Statement

Today for platforms Java and Android (that I know of) the SDK versions are hard coded in the copy paste snippets during the Project Onboarding. This requires manual updates everytime there is a new release of the SDKs.

### Solution Brainstorm

The SDK version should be dynamically retrieved from the registry, similar to how it is done in static-sites now. See PR below for reference

https://github.com/getsentry/static-sites/pull/1721

### Product Area

Projects

**Comment by smeubank** [comment]
@priscilawebdev is this something which could be done similar to static-sites in product?

**Comment by priscilawebdev** [comment]
I will verify if this can be done in our sentry product 😉
