### ISSUE TITLE
Sentry error: API request failed   caused by: [60] SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by diegobejardelaguila** [getsentry/sentry#53934]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

How are you running Sentry?

 On-Premise docker [Version xyz]
 Saas (sentry.io)
 Other [briefly describe your environment]
Description
Originally logged in https://github.com/getsentry/sentry-cli/issues/666

Getting SSL error on Githhub action sourcemap upload for webpack plugin.

When I try locally, it works fine, but on jenkins seems to fail

Steps to Reproduce
     
      [0m[91mSentry CLI Plugin: Command failed: /****/node_modules/@sentry/cli/sentry-cli releases new 
      Bb4k9N0eLFX9KHebLkD_9
      error: API request failed
        caused by: [60] SSL peer certificate or SSH remote key was not OK (SSL certificate problem: unable to get local issuer 
      certificate)
      
      Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
      Please attach the full debug log to all bug reports.
      
      [0m[91m
      [0m[91m> Build failed because of webpack errors
      [0m[91merror Command failed with exit code 1.
      [0minfo Visit ****://yarnpkg.com/en/docs/cli/run for documentation about this command.

  
    
      

### Expected Result

What you expected to happen
      Should successfully upload similar to other standard CI / workstation environments

### Actual Result

Actual Result
      Should successfully upload similar to other standard CI / workstation environments
      

      [0m[91mSentry CLI Plugin: Command failed: /****/node_modules/@sentry/cli/sentry-cli releases new 
      Bb4k9N0eLFX9KHebLkD_9
      error: API request failed
        caused by: [60] SSL peer certificate or SSH remote key was not OK (SSL certificate problem: unable to get local issuer 
      certificate)

### Product Area

Issues

**Comment by jredmond-sentry** [comment]
Does this happen every time, or is it intermittent?

We're currently testing a new IP and TLS certificate on sentry.io; this week (31 July-4 August 2023) we're setting `sentry.io` as a round-robin record between old and new IPs, between the hours of 09:00 and 21:00 UTC. Based on the error you provided, I suspect that either a firewall needs updating (to give Jenkins access to the new IP), or Jenkins' CA bundle needs to be updated (the new certificate uses a different root than before), or possibly both.

https://status.sentry.io/incidents/tk9cv26z8xcl has more details about the new IP testing; https://status.sentry.io/incidents/y9rf1x79cz2q has more details about the new TLS certificate. Note that we'll be switching back and forth between new and old IPs for the month of August 2023, but that the new certificate is being installed everywhere on 7 August.
