### ISSUE TITLE
Adjustable Y-Axis or better Outlier filtering

### ISSUE THREAD

**Issue by nanoburd** [getsentry/sentry#53938]
### Problem Statement

<img width="1468" alt="image" src="https://github.com/getsentry/sentry/assets/97483437/40a95509-91e2-434e-a020-116b3c254981">
![dd-fullscreen-log](https://github.com/getsentry/sentry/assets/97483437/0200e16f-3a22-48db-8a8f-5b0f60152420)

When there are outliers, the bulk of the graph is unviewable.

Applied to metric graphs in all areas of the product.

### Product Area

Dashboards

**Comment by nanoburd** [comment]
@brentc @doralchan this is backlogged but we need some thoughts on this too.

**Comment by gggritso** [comment]
I'm going to close this, in favour of https://github.com/getsentry/sentry/issues/75729 which will enable Y-axis scaling in more contexts, and eventually Performance landing will be one of them 👍🏻
