### ISSUE TITLE
Add image hero to the Go "Select Framework" modal

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry#53931]
As soon as an illustration is provided by our designers, this has to be added to the top of the framework modal for Go.

Related to https://github.com/getsentry/sentry/pull/53845

**Comment by Jesse-Box** [comment]
@matejminar @ArthurKnaus 

Marking as Done

![Frameworks-Go](https://github.com/getsentry/sentry/assets/6508377/ce47927c-f315-4574-ae40-1487c68c0f9d)
