### ISSUE TITLE
Stand alone Raven configuration for ReactNative app leads to no stripping of path_to_artifact

### ISSUE THREAD

**Issue by samratshekhar** [getsentry/sentry#5393]
We've setup Raven for JavaScript crash reporting in our ReactNative app, without utilising the Sentry RN plugin, since we were running  into [this](https://github.com/getsentry/react-native-sentry/issues/21) issue. Crash reporting works fine upto the point where we hit a particular issue 'Source code was not found for **file**'. Because of this issue we're only able to view minified version of the crash log.

Here is our setup code:

```
import Raven from 'raven-js';
import RavenNative from 'raven-js/plugins/react-native';
static setupSentry() {
  RavenNative(Raven);
  Raven.config(Constants.ravenDSN(), {
    release: DeviceInfo.getVersion(),
    dataCallback: (data) => {
      const newData = data;
      newData.contexts = newData.contexts || {};
      newData.contexts.device = {
        ...newData.contexts.device,
        name: DeviceInfo.getDeviceName(),
        family: DeviceInfo.getBrand(),
        model: DeviceInfo.getModel(),
      };
      newData.contexts.os = {
        ...newData.contexts.os,
        name: DeviceInfo.getSystemName(),
        version: DeviceInfo.getSystemVersion(),
      };
      return newData;
    },
  }).install();
}
```

Following github issue #3294 we tried uploading the artifacts with various url prefixes, but the scenario in which we were able to pull a fully un-minified version of the crash log was when we hardcoded the exact file path which Sentry was expecting. But the caveat of this method is that it is device specifc :P. We're attaching files which gives a brief idea of our client config, as well as the various url-prefiexes we've tried, apart from absolute path.

![screen shot 2017-05-15 at 5 19 38 pm](https://cloud.githubusercontent.com/assets/25629471/26058362/3d764616-399b-11e7-8444-a01bdd13bb1f.png)

So our question stands, **Is there a way to strip the prefix to the artifact path in crash logs like**
` /var/containers/Bundle/Application/{DEVICE_ID}/HelloWorld.app/main.jsbundle => /main.jsbundle`
when using a setup like ours?

**Comment by mitsuhiko** [comment]
If you want to manually upload the build artifacts you need to do it with `--rewrite` and `--url-prefix` set to `~/` as well as the extensions expanded to include `jsbundle` and `map`. It's important to upload all in one go as otherwise the cross references are not set up correctly.

Eg:

    sentry-cli releases files VERSION upload-sourcemaps -x map -x jsbundle --rewrite /path/to/folder

Inside `folder` you need to have your `jsbundle` and `map` files.

**Comment by samratshekhar** [comment]
Thanks @mitsuhiko for the prompt reply. I tried all the stuff u mentioned. Here are the findings:

Here's my directory structure:
<img width="636" alt="screen shot 2017-05-16 at 11 43 49 am" src="https://cloud.githubusercontent.com/assets/25629471/26092371/4412b69c-3a2e-11e7-824e-440b91c96551.png">

The command used to upload the artifacts:
![screen shot 2017-05-16 at 11 46 29 am](https://cloud.githubusercontent.com/assets/25629471/26092619/8e6f25d0-3a2f-11e7-8684-d74902afeaa7.png)

Resulting to:
![screen shot 2017-05-16 at 11 49 04 am](https://cloud.githubusercontent.com/assets/25629471/26092627/9da99a80-3a2f-11e7-854d-17dc8719aef6.png)
 
Leading to following error in the crash log:
![screen shot 2017-05-16 at 11 49 32 am](https://cloud.githubusercontent.com/assets/25629471/26092640/aa75ce96-3a2f-11e7-873f-42d72b4d50cd.png)

**Comment by samratshekhar** [comment]
But if I provide the exact path which Sentry is expecting and in the absence of which throwing error
`var/containers/Bundle/Application/DCD93D11-D329-4ADB-A988-A6553E747314/qplum.app/main.jsbundle`, then things seem to work as intended.

Updated command used to upload the artifacts:
![screen shot 2017-05-16 at 11 58 15 am](https://cloud.githubusercontent.com/assets/25629471/26092722/288a4d84-3a30-11e7-930a-1ed6c5138b3d.png)

Resulting to:
![screen shot 2017-05-16 at 12 00 59 pm](https://cloud.githubusercontent.com/assets/25629471/26092731/38a061cc-3a30-11e7-83a8-6dc8eaef78b0.png)

Leading to perfect crash log:
![screen shot 2017-05-16 at 12 01 27 pm](https://cloud.githubusercontent.com/assets/25629471/26092748/4aac0772-3a30-11e7-85f6-baaac5277ba2.png)

**Comment by samratshekhar** [comment]
If I'm not mistaken, `--strip-common-prefix` is spear-headed to handle the exact scenario, right? If so, then what could be possibly going wrong?

**Comment by mitsuhiko** [comment]
@samratshekhar that is because you are not using the react native plugin so the paths will be wrong. Even if you cannot use the native module for some reason you can use it unlinked in which case the paths will be normalized before event submission.

Closing this issue here as no repro.

**Comment by mitsuhiko** [comment]
Also a quick heads up: the distirbution field and qualified release names are becoming mandatory for mobile apps. So you will need to upload release as `your.reverse.dsn-VERSION.NUMBER` and `VERSION_CODE` as distribution going forward if you are using the react native integration.

**Comment by samratshekhar** [comment]
Could you please elucidate how to use a RN plugin "unlinked"?

**Comment by mitsuhiko** [comment]
Remove the added xcode projects and the include and init in the `AppDelegate.m`.

**Comment by mitsuhiko** [comment]
This is however not recommended because you will lose functionality
