### ISSUE TITLE
Sentry Issue Filters providing results outside of filters

### ISSUE THREAD

**Issue by isabelpanepento** [getsentry/sentry#53945]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the issues page in sentry
2. Filter a package for a specific environment in the last hour
4. Observe the results filter incorrectly. 
  - Issues with no events in the last hour
  - Issues that have never appeared in the environment specified in the search
  - Issues in the incorrect order of last observed

### Expected Result

Only seeing issues within the constraints of the filter set

### Actual Result

![Screen Shot 2023-08-01 at 1 05 00 PM](https://github.com/getsentry/sentry/assets/93609179/26abba39-0047-4097-b26b-2606c6a2b519)
![Screen Shot 2023-07-31 at 2 43 17 PM](https://github.com/getsentry/sentry/assets/93609179/e5732e1f-3959-4996-8b67-7744a16deeb4)

see the filters and see the results not matching the time constraints

### Product Area

Issues

### DSN

127052

**Comment by malwilley** [comment]
@isabelpanepento we just reverted a change related to how the issue search behaves. Can you confirm that this behavior is still happening for you?

**Comment by isabelpanepento** [comment]
@malwilley Everything looks correct now!! Thank you for the quick response!!

**Comment by malwilley** [comment]
Glad to hear everything is working again! 😄 

For our future reference, [this was the offending change](https://github.com/getsentry/sentry/pull/53321).
