### ISSUE TITLE
Tag CSP as a platform

### ISSUE THREAD

**Issue by ehfeng** [getsentry/sentry#5394]
Tag CSP events as "csp" in `sentry_groupedmessage.platform`

I traced this down to the `insert_data_to_database` in `src/sentry/coreapi.py` file. My hypothesis is we can add "csp" to the `LazyData` object here, but the code is pretty confusing.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
