### ISSUE TITLE
Identify Issue and Metric Alerts APIs to Publish

### ISSUE THREAD

**Issue by jangjodi** [getsentry/sentry#53972]
The following APIs need to be documented so they can be published here: https://docs.sentry.io/api/

- Publish APIs that list Issue and Metric alerts
- Publish APIs that provide CRUD operations for Issue and Metric alerts
- Determine what supporting APIs used when creating alerts. An example can be like gathering Jira issue fields for ticket creation as an action for an alert. We need to understand all supporting APIs to publish these as well.

**Comment by isabellaenriquez** [comment]
APIs identified to be published: https://www.notion.so/sentry/85feada1b20c4066bbc690256c2aa528?v=ad03b10725dd4571bfbeeed245a5e8ec&pvs=4

**Comment by isabellaenriquez** [comment]
Next milestone: https://github.com/getsentry/sentry/issues/55920
