### ISSUE TITLE
API-Calls don't work if not ended with a slash

### ISSUE THREAD

**Issue by thomaseizinger** [getsentry/sentry#5400]
Using the hosted version of sentry (Sentry 8.17.0.dev0).

API calls respond with a 404 if the path does not end with a slash. For example, the following request does not work:
`GET https://sentry.io/api/0/organizations/:slug/releases`
whereas the following works:
`GET https://sentry.io/api/0/organizations/:slug/releases/`

Is this intended?
I know that the paths are documented like that, but it is still not a very nice behaviour IMO. Took me a while to figure out the issue why some requests work and some don't :)

**Comment by joeyparis** [comment]
Thank you for your post, this has been driving me crazy for the last hour and a half. I definitely support the idea of the trailing slash being optional

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by joeyparis** [comment]
@BYK I think this should still be worked on because it seems like a fairly simple change (of course not knowing the deeper workings of the system). Or at the very least maybe including some sort of warning to check for trailing slashes in the event of a 404, just because it's definitely easy to overlook even though it is documented correctly.

**Comment by dcramer** [comment]
It is not possible to have API requests work as singular identity URLs. While it might be possible to redirect a GET verb, any other kind of action will fail, so supporting that isn't on our radar, nor is double mapping all API urls to support slash and non-slash.

**Comment by dcramer** [comment]
Aside, if we did want to follow up, an ideal change would be having the API reject all requests without a trailing slash, and giving an appropriate error message to help people. The fact that GET requests redirect is a bit of a problem and adds to the confusion.

**Comment by joeyparis** [comment]
I think that would be an appropriate solution to this problem!
