### ISSUE TITLE
Ignore or override CODEOWNERS rules

### ISSUE THREAD

**Issue by serglom21** [getsentry/sentry#54012]
### Problem Statement

There are some cases where it would be useful to override or **ignore** ownership rules coming from a CODEOWNERS file:

As an example, lets say I am part of a team that owns a shared library code, and this library wraps a lot of other teams' code. So we have a CODEOWNERS rule to assign to my team if the frame from that library is present (because we would like to review changes in Github). However, we get assigned to issues that contain that shared library code (or wrapper) in Sentry and we don't want that. 

If there are any other frames in the callstack that are called after my wrapper code, I would like those frames to determine ownership

### Solution Brainstorm

I would like to be able to "ignore" a file or rule from the CODEOWNERS file and assign the issue to the next matching rule in the calls tack

### Product Area

Issues

**Comment by DavidCain** [comment]
Hey, team -- any updates on prioritizing this issue? We're particularly interested in finding a way to leverage `CODEOWNERS` despite the bottom of the stacktrace living in core shared utilities.

**Comment by DavidCain** [comment]
@NisanthanNanthakumar -- I was under the (perhaps incorrect?) assumption that a file's position in the stacktrace played a role in what team is assigned? For example, consider this stracktrace:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    bad_ideas.main()
  File "src/bad_ideas.py", line 5, in main
    numbers.divide_by_zero(10)
  File "src/numbers.py", line 2, in divide_by_zero
    num / 0
ZeroDivisionError: division by zero
```

If the `@mathematicians` team owns `numbers.py` and `@engineering` owns `bad_ideas.py`, is the owner of this `ZeroDivisionError` entirely determined by which `CODEOWNERS` rule appears _last_ in `.github/CODEOWNERS`?

--

As a side note, I _did_ move the ownership of the shared library code (`src/util`) to the absolute top of the `CODEOWNERS` file, and new errors (which include `src/util` in their trace) _continue_ to be assigned to the team that owns those utilities.

**Comment by DavidCain** [comment]
Also, @NisanthanNanthakumar -- I'd be happy to reopen, but do not have permissions to do so.

**Comment by malwilley** [comment]
Re-closing due to duplicate opened here: https://github.com/getsentry/sentry/issues/57828

Looks like this is already on the backlog. Thanks for the detailed request and sorry we missed your followup!
