### ISSUE TITLE
Fix feedback banner for Escalating Issues

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#54063]
1. After submitting Yes/No feedback, refreshing the page or navigating back will show the feedback banner again.  A simple cookie drop to track that feedback was submitted for this issue previously should suffice
2. Previously, upon giving feedback there was a modal popup that had a text box to give more detailed feedback.  We should add that back
3. There was an Amplitude flag tracking "is_high_priority" / "isHighPriority".  It would be great if clicks on Yes/No would still capture this so we can see at a glance in Amplitude the distribution between yes/no is.

**Comment by scttcper** [comment]
https://github.com/getsentry/getsentry/pull/11340
