### ISSUE TITLE
Render JSON in breadcrumbs

### ISSUE THREAD

**Issue by G-Rath** [getsentry/sentry#5407]
We often have JSON in our breadcrumbs when using Sentry.

This is very common with XHR related requests, and so it would be nice if we could view the data in breadcrumbs with some basic formatting, instead of just a straight dump.

There are a couple of solutions to this: 
* A 'transform' button, that transforms a single breadcrumb's key (or 'transform on click', similar to how some sites handle code examples)
* Parsing data from breadcrumbs the same way that additional data is. 
* Allowing us to flag a field as having JSON, and so have those fields parsed (rather than trying to parse/test every field, or treating everything like JSON).

**Comment by BYK** [comment]
Closing this issue due to staleness. I think we already do this now btw.
