### ISSUE TITLE
Total Users strange behaviour 

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#54090]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Configure release and users in a project
Go to Project Details
Select the Crash free users graph for a specific release
Change the time range

### Expected Result

-

### Actual Result

Changing the date filter from 14d to 30 make the total user count decrease on a release that was created 1 day ago. I would expect this value to not change, and only decreases if i select a time range after the release was created. 

See links and screenshots:
14d: 21496 total users: https://sentry.sentry.io/projects/javascript/?chart1=crash_free_users&project=11276&query=release%3Afrontend%40e9a29cc719eec29a34c8a9fb9bdba39289823b32&statsPeriod=14d›
![Screenshot 2023-08-03 at 12 16 02](https://github.com/getsentry/sentry/assets/64906376/c38e4547-2cd3-47b0-a0fe-7411c64d37a8)

30d: 17038 total users: https://sentry.sentry.io/projects/javascript/?chart1=crash_free_users&project=11276&query=release%3Afrontend%40e9a29cc719eec29a34c8a9fb9bdba39289823b32&statsPeriod=30d
![Screenshot 2023-08-03 at 12 16 20](https://github.com/getsentry/sentry/assets/64906376/b066aec7-a148-4a01-b66e-f74cd7cd6f9c)

### Product Area

Releases

**Comment by hubertdeng123** [comment]
Ownership of the Projects product area has changed, so I'm going to reset the due date.

**Comment by lobsterkatie** [comment]
@rodolfoBee You're right, that is puzzling. Thanks for reporting it. We'll look into it and keep you posted.
