### ISSUE TITLE
Migration 8.0.6 to 8.6.0

### ISSUE THREAD

**Issue by joaomvfsantos** [getsentry/sentry#5412]
After upgrading from 8.0.6 to 8.6.0 (pip upgrade and sentry upgrade ran without errors) I was getting internal errors when opening sentry in the browser, with the message: 

```
ProgrammingError: column sentry_organizationmember.counter does not exist
LINE 1: ... "sentry_organizationmember"."has_global_access", "sentry_or...
```

Clearly something went wrong with the schema migration although no errors were reported, so I manually added the counter column to the schema of sentry_organizationmember table and this solved the errors, but I had the feeling that something was missed in the migration, so although this is solved for me maybe it's something you may want to check if you deem worth it.

**Comment by mattrobenolt** [comment]
I'm not entirely sure what state you're in, but in 8.8.0, this column is removed entirely: https://github.com/getsentry/sentry/commit/6cc920d29c70566ab919bc0d648461b28afc08d7
