### ISSUE TITLE
Feature Request: Search by External Issue

### ISSUE THREAD

**Issue by dt** [getsentry/sentry#5413]
We're already using Github Issues to to track everything and want to be able to search in Sentry by GitHub issue, both by issue number and, more importantly, for all issues that do, or do not, have an external issue linked (i.e. those awaiting triage).

**Comment by Diggsey** [comment]
We have the same feature request, but for clubhouse tickets.

**Comment by danpalmer** [comment]
> more importantly, for all issues that do, or do not, have an external issue linked (i.e. those awaiting triage)

Huge +1 to this!

**Comment by markstory** [comment]
I've started this in #11049. I'm hoping to get this work finished off once my time frees up in February.

**Comment by Shtannikov** [comment]
@markstory are there any news?

**Comment by markstory** [comment]
@Shtannikov This work is currently blocked due to dependencies on getting more state pushed into clickhouse so that we can stop splitting queries across postgres and clickhouse. Unfortunately that blocking work is not scheduled to be completed for sometime.

**Comment by BYK** [comment]
Related #8338, #15525

**Comment by goodevilgenius** [comment]
#21593 only resolves half of this issue.

It allows one to search for issues that are or are not linked, but doesn't actually allow one to search for issues specifically by a GitHub issue.

**Comment by BYK** [comment]
The original message was focusing on the existence of a linked issue and that's why we think this issue is resolved.

I encourage you to filing a new issue for the feature you request @goodevilgenius and it will be evaluated by our team accordingly.
