### ISSUE TITLE
Clicking a tag's value searches the issue stream

### ISSUE THREAD

**Issue by ceorourke** [getsentry/sentry#54135]
When you click a tag's value on the issue details page, it brings you to the issues stream and adds the tag key and value to the search. I've never wanted that behavior and it always annoys me - I'd expect it to either bring me to the events tab and filter down to events w/ that tag's value, or bring me to the tags page (ideally with an anchor for the tag I'm looking at).

**Comment by roggenkemper** [comment]
Closing because it currently brings you to the events tab
