### ISSUE TITLE
Sentry Docker on Port 80

### ISSUE THREAD

**Issue by be-janshair** [getsentry/sentry#5415]
I'm using Sentry via Docker-Compose. My Docker Compose file has 3 services:
- sentry
- sentry-cron
- sentry-worker-1

Only the `sentry` service exposes port 9000. Now I want to map the container port 9000 to port 80 on my local machine. I do write `80:9000` and application runs with all the components and workers, but when I go to Admin Panel -> Buffer, the application crashes coz it redirects it to port 9000 where no service is listening.
Any solution for this?
Thanks

**Comment by mattrobenolt** [comment]
You want to set `system.url-prefix` configuration option. Please read our documentation.

**Comment by be-janshair** [comment]
I followed [this](https://docs.sentry.io/server/config/) where it says about `system.url-prefix` that it is declared in `config.yml`. I then used [this](https://raw.githubusercontent.com/getsentry/docker-sentry/master/git/config.yml) as a sample config file and I inserted `system.url-prefix: "http://localhost:80"` in the file, rebuild the docker image but I'm still not accessing it. Also 3 containers get exited when I run `docker-compose up -d` with this configuration.

**Comment by be-janshair** [comment]
That's resolved now. Thanks for the tip. :)

**Comment by matiasvns** [comment]
@be-janshair hi, can you explain how to resolved this problem ?

**Comment by be-janshair** [comment]
@matiasvns write a config in the `config.yml` file with your custom domain `system.url-prefix: 'https://sentry.example.com'`, copy this file to your docker and you're good to go.
