### ISSUE TITLE
RFE: Releases API: List a Release’s Issues

### ISSUE THREAD

**Issue by rtyley** [getsentry/sentry#5424]
Currently there's no endpoint in the [Releases API](https://docs.sentry.io/api/releases/) for listing a Release’s Issues (ie like [_List a Project’s Issues_](https://docs.sentry.io/api/events/get-project-group-index/) but for Releases, not Projects) - could that be added?

We have a [bot](https://www.theguardian.com/info/developer-blog/2015/feb/03/prout-is-your-pull-request-out) that monitors the Continuous Deployment of our PRs, and also [pushes Release information to the Sentry API](https://github.com/guardian/prout/issues/47#issuecomment-302468156). In the 30-60 minute period after deployment of a PR, we'd like the bot to be able to ask the Sentry API what new issues have occurred with the release, so our bot can report back in the PR with a comment stating that new issues have occurred, notifying the people responsible for that release - but we would need this new API endpoint in the Sentry API to make this work!

_(I was lucky enough to talk this over with @ehfeng at GitHub Satellite - thanks Eric!)_

**Comment by dcramer** [comment]
We could probably create a dedicated endpoint, but it can be accessed today by hitting the "issue list for a project" with a query of "first-release:[version]".

Aside, you can also do "first-release:latest", as well as "release:latest".

https://docs.sentry.io/learn/search/
