### ISSUE TITLE
Write code to call severity api for an event

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#54249]
We’d call this in a similar way to https://github.com/getsentry/sentry/blob/7f4151250e78cdc4f8204eac6497d5595c6647e1/src/sentry/api/endpoints/organization_events_trendsv2.py#L62. Probably worth making our own connection pool here so that we can switch to a different service at some later point. We’ll have a different specific api to call as well, @trillville  will provide us with this.

The payload will look like
```
{
	"message": "<event message>",
	"stacktrace": "<event pruned/formatted stacktrace>",
	"type": "warning/error/etc",
	"sdk": "python/javascript/etc",
}
```

We’ll format the stack trace using [this code](https://github.com/getsentry/sentry/blob/066a443bc46c05e458f61007932aaa79c0fcb0cc/src/sentry/api/endpoints/event_ai_suggested_fix.py#L133-L243), possibly with some tweaks as needed.

When making the requests, we should have a low timeout so that if there's some problem with the service we don't end up causing an outage. Low could be 1s, 500ms, etc. Ideally the lower the better, but we should leave plenty of headroom for normal response time (will have to get an idea of how long a standard call to the api will take with @trillville)

Making this call should be behind an option, so that we're able to dynamically disable it if we notice any problems. The entire thing should be wrapped in a try/catch so that there's no way it breaks ingestion.

**Comment by wedamija** [comment]
@trillville For `sdk` do you want the `platform` (python/javascript/etc) or the sdk field, which looks more like
```
"sdk": {
"name": "sentry.python.django",
"version": "1.28.1",
"integrations": [
"argv",
"atexit",
"celery",
"dedupe",
"django",
"django_atomic",
"excepthook",
"logging",
"modules",
"redis",
"rust_info",
"stdlib",
"threading"
],
"packages": [
{
"name": "pypi:sentry-sdk",
"version": "1.28.1"
}
]
}
```

**Comment by lobsterkatie** [comment]
Note that for now, we're just using the event's message, rather than all of the data listed above.
