### ISSUE TITLE
Breadcrumb logs text color like in the console/terminal

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry#54269]
### Problem Statement

The breadcrumbs list is rendered not super nicely if there are colors used for log Statements:
e.g:
`API listening on [35mhttp://localhost:8911/[39m`

it should look like this instead:
<img width="400" alt="image" src="https://github.com/getsentry/sentry/assets/363802/0cf180e5-ff6f-4bdb-87c2-f4343b66163c">

Here is a full screenshot:
<img width="1088" alt="image" src="https://github.com/getsentry/sentry/assets/363802/79b02290-163c-43ce-ba51-10f61b0b72a3">

### Solution Brainstorm

Maybe we can also make it if it's `category: error` more red'ish than just the pill on the right

### Product Area

Issues

**Comment by roggenkemper** [comment]
Closing this out in favor of https://github.com/getsentry/sentry/issues/49804, which appears to be the same issue
