### ISSUE TITLE
Trio of events seen in replay timeline

### ISSUE THREAD

**Issue by michellewzhang** [getsentry/sentry#54293]
Check out [this replay:](https://sentry.sentry.io/replays/78519d7dae53419c92fbce1954543f36/?query=&referrer=%2Forganizations%2F%3AorgId%2Freplays%2F&statsPeriod=14d&t_main=dom&yAxis=count%28%29)
we see a strange trio of events in the replay details timeline

![SCR-20230804-nokm](https://github.com/getsentry/sentry/assets/56095982/03b8fc73-b0e1-456d-89a4-1171817e10db)

Another example can be seen in Josh's replay [here](https://sentry.sentry.io/replays/870100c597a04e8daa3db945dc0a210c/?f_d_type=ui.slowClickDetected&query=&referrer=%2Freplays%2F&statsPeriod=14d&t_main=dom&yAxis=count%28%29) at 1:05

**Comment by mydea** [comment]
cc @ryan953 one thing that also is weird for this replay is that some of the breadcrumbs (rage clicks etc.) are shown in the UI Events pane as well, others arent:
<img width="1258" alt="image" src="https://github.com/getsentry/sentry/assets/2411343/9b07af4d-2376-4e16-a41c-1dafbb79f93c">

**Comment by michellewzhang** [comment]
> cc @ryan953 one thing that also is weird for this replay is that some of the breadcrumbs (rage clicks etc.) are shown in the UI Events pane as well, others arent: <img alt="image" width="1258" src="https://user-images.githubusercontent.com/2411343/259141275-9b07af4d-2376-4e16-a41c-1dafbb79f93c.png">

I also mentioned this in this issue here! https://github.com/getsentry/sentry/issues/54291

**Comment by michellewzhang** [comment]
@mydea we are still seeing the trio of events (and missing rage/dead clicks) issue in [this replay](https://sentry.sentry.io/replays/8bc7ae375e39456d89d30d06087192d6/?f_d_type=ui.slowClickDetected&query=&referrer=%2Freplays%2F&statsPeriod=14d&t_main=dom&yAxis=count%28%29) from 4 days ago
<img width="267" alt="SCR-20230814-jdxz" src="https://github.com/getsentry/sentry/assets/56095982/a1a865e3-a54e-4b2f-9335-daa0d2f9fca8">
<img width="326" alt="SCR-20230814-jdgu" src="https://github.com/getsentry/sentry/assets/56095982/b726e648-ef54-4393-843d-7ad24ce5aadd">

**Comment by mydea** [comment]
Hmm, but these seem different - they are on different elements and on different timestamps!
Are you "hiding" the click breadcrumb with the same timestamp as the rage click breadcrumb now? It seems to me so (I don't see any click at this time with the same selector), and then this would be correct to me - we capture at most one click per second, so this is "by design" if you click an element many times over multiple seconds 🤔
