### ISSUE TITLE
Notification email unsubscribe links do not work

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#54306]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open a notification email for an issue from Sentry
2. Click the "Unsubscribe" link at the bottom of the email

### Expected Result

The unsubscribe action should be successful and show in the UI as such.

### Actual Result

An error banner is shown and the unsubscribe action is not successful.

![image](https://github.com/getsentry/sentry/assets/10888943/cad90bb9-44ea-43c1-984f-db14ae24caed)

### Product Area

Other

**Comment by corps** [comment]
Fix is out!

**Comment by ceorourke** [comment]
Closing as the prior comment says it's been fixed, please reopen if you're still seeing this.
