### ISSUE TITLE
Sending tag "user" in event causes an error

### ISSUE THREAD

**Issue by vkapitanova** [getsentry/sentry#5434]
When trying to send event with tag "user" getting an error on the issue page and this tag absent in a list of tags:
 ```
There was 1 error encountered while processing this event
Discarded invalid value for parameter 'tags'
{
  "name": "tags",
  "value": [
    "user",
    "test_user"
  ]
}
```
For other tags working as expected (if replace "user" with "auth_user" for example).
We're using sentry version 8.15 deployed in docker and raven-logback 8.0.3 on an application side.

**Comment by dcramer** [comment]
User is a reserved tag in Sentry as it's used for user context and auto generated.
