### ISSUE TITLE
linkable event stack trace frames

### ISSUE THREAD

**Issue by MaxBittker** [getsentry/sentry#5435]
sometimes you want to point people to a specific frame in a stack trace, it would be nice to have a way to do this.

could be similar to the semantics of github line number anchors
(example:
https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/organization_releases.py#L173 )

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
