### ISSUE TITLE
Table zbdata.DUAL doesn't exist

### ISSUE THREAD

**Issue by wcnmsd1s** [getsentry/sentry#54355]
### Problem Statement

An error occurred after springboot + alibaba druid + dynamic + clickhouse integration

erro：Table zbdata.DUAL doesn't exist. (UNKNOWN_TABLE) (version 23.6.2.18 (official build))

### Product Area

Issues

**Comment by chadwhitacre** [comment]
Not sure. @wcnmsd1s Are you on self-hosted? `23.6.2.18` does not look like one of our version numbers.
