### ISSUE TITLE
Alerts based on both Error and User count

### ISSUE THREAD

**Issue by jhyland-rtr** [getsentry/sentry#54361]
### Problem Statement

At the moment, alerts have a base setting of being based on number of errors or number of affected users. This can result in unwanted alerts when a single user is repeating some strange behaviour - we would not want to alert on this scenario as it does not impact the general user base.

### Solution Brainstorm

Allow alerts to be based on both error and user count.
Example: Above 5 errors, impacting 2 or more users.

### Product Area

Alerts

**Comment by jangjodi** [comment]
Thank you for your feedback @jhyland-rtr! Would something like this fit your use case (Alerts > Create Alert > Issues), or do you specifically want this to be a metric alert functionality? 
<img width="1023" alt="Screenshot 2023-08-08 at 9 56 05 AM" src="https://github.com/getsentry/sentry/assets/116035587/78106172-077f-485d-9297-2733cff6d549">

Please see the [Metric Alerts Docs](https://docs.sentry.io/product/alerts/create-alerts/metric-alert-config/) and the [Issue Alerts Docs](https://docs.sentry.io/product/alerts/create-alerts/issue-alert-config/) if you'd like to see the other types of alerts that are available.

**Comment by jhyland-rtr** [comment]
@jangjodi thanks - that looks promising. One issue I see with this is the events that I'm targeting are coming through as separate issues, so I don't think the "number of events in an issue" will catch them.

I'm sending these events with;
```
Sentry.withScope(function (scope) {
  scope.setTag("customTag", true);
  Sentry.captureException(exception);
});
```

I was using the custom tag on the metrics filter. Is there a way to use withScope and tags to ensure the events get collated under the same issue?

**Comment by jangjodi** [comment]
@jhyland-rtr Thank you for your response. In general, you can use fingerprints via the SDK to merge different issues (see [here](https://docs.sentry.io/platforms/javascript/usage/sdk-fingerprinting/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2Fproduct%2Fdata-management-settings%2Fevent-grouping%2F)). More options for issue grouping can be found [here](https://docs.sentry.io/product/data-management-settings/event-grouping/).

**Comment by jhyland-rtr** [comment]
@jangjodi thanks for steering me towards the custom fingerprints! These are now grouping as expected.

I tried changing to an Issue Alert but really like the Metric Alert alert so we've changed to a metric alert based on the number of users impacted.

**Comment by jhyland-rtr** [comment]
@jangjodi just discovered an issue with the Metric Alert - it doesn't seem to give an Action option for VictorOps? I have integrated and embedded for the project - I do see this an an option for Issue Alert. The only options I see are Email and Slack. Is this expected?

**Comment by jangjodi** [comment]
@jhyland-rtr unfortunately VictorOps is a plugin as opposed to a first party integration, and thus support for VictorOps and metric alerts is not implemented

**Comment by schew2381** [comment]
Closing as the original issue seems to be resolved. Feel free to open another request if you'd support for a new integration!
