### ISSUE TITLE
GCC failing when trying to install cryptography wheel

### ISSUE THREAD

**Issue by koala421** [getsentry/sentry#5437]
## Reporting Bugs

When reporting bugs, include detailsabout your configuration, such as:
- The version of Sentry you're using----- 8.16.0
- Whether you're using Docker or another installation method---Using Python Installation
- Include a stacktrace or other logs when relevant--

    build/temp.linux-x86_64-2.7/_openssl.c:73274:42: error: storage class specified for parameter ‘_cffi_type_context’
     static const struct _cffi_type_context_s _cffi_type_context = {
                                              ^
    build/temp.linux-x86_64-2.7/_openssl.c:73274:21: error: parameter ‘_cffi_type_context’ is initialized
     static const struct _cffi_type_context_s _cffi_type_context = {
                         ^
    build/temp.linux-x86_64-2.7/_openssl.c:73291:11: error: expected declaration specifiers before ‘#pragma’
      pragma GCC visibility push(default)  /* for -fvisibility= */
               ^
    build/temp.linux-x86_64-2.7/_openssl.c:73324:11: error: expected declaration specifiers before ‘#pragma’
       pragma GCC visibility pop
               ^
    build/temp.linux-x86_64-2.7/_openssl.c:682:9: error: old-style parameter declarations in prototyped function definition
     typedef LHASH_OF(CONF_VALUE) Cryptography_LHASH_OF_CONF_VALUE;
             ^
    build/temp.linux-x86_64-2.7/_openssl.c:682:1: error: parameter name omitted
     typedef LHASH_OF(CONF_VALUE) Cryptography_LHASH_OF_CONF_VALUE;
     ^
    build/temp.linux-x86_64-2.7/_openssl.c: At top level:
                 ^
    build/temp.linux-x86_64-2.7/_openssl.c:608:13: warning: ‘ERR_Cryptography_OSRandom_error’ declared ‘static’ but never defined [-Wunused-function]
     static void ERR_Cryptography_OSRandom_error(int function, int reason,
                 ^
    build/temp.linux-x86_64-2.7/_openssl.c: In function ‘LHASH_OF’:
    build/temp.linux-x86_64-2.7/_openssl.c:73324:11: warning: control reaches end of non-void function [-Wreturn-type]
       pragma GCC visibility pop
               ^
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/open/usr/local/develop/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-9x65VS/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-XqauhP-record/install-record.txt --single-version-externally-managed --compile --install-headers /open/usr/local/develop/zk4pmgr/open-py/include/site/python2.7/cryptography" failed with error code 1 in /tmp/pip-build-9x65VS/cryptography/

- Include a redacted version of your configuration when relevant

**Comment by bsergean** [comment]
Hey @koala421 , which version of Linux are you using ?

**Comment by koala421** [comment]
I'm using RHEL7, I tried installing it through a virtualenv but wasn't able to but when I exited the virtualenv I was able to install it without hiccups

**Comment by mattrobenolt** [comment]
fwiw our docs explicitly say that we only support Debian/Ubuntu. I'm pretty sure there are many problems you'll come across with RHEL.

**Comment by mattrobenolt** [comment]
Also, closing since, if anything, this is moreso an issue with `cryptography` than Sentry itself. If we officially supported RHEL, we'd probably figure this out. :)
