### ISSUE TITLE
Crash Free Rate is not show up

### ISSUE THREAD

**Issue by hujingyuki** [getsentry/sentry#54439]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

https://sentry.pt.xiaomi.com/

### Expected Result

show Crash Free Rate

### Actual Result

![image](https://github.com/getsentry/sentry/assets/35281360/835fa730-b9e9-42c5-9d9f-50428a507fd9)

### Product Area

Projects

**Comment by brentc** [comment]
It looks like you're looking for support getting your project to be able to see crash-free rate. For support please consider opening a support ticket at https://help.sentry.io/
