### ISSUE TITLE
Slack Integration no longer navigates to the latest event in an issue

### ISSUE THREAD

**Issue by rayanami** [getsentry/sentry#54431]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1.  Trigger a Sentry event that has a corresponding alert rule to send a notification to Slack
2.  Click on the link from the Slack notification

### Expected Result

Website browser opens a tab and browses to the latest event for an issue.

### Actual Result

Website browser navigates to an older event for an issue (sometimes 5 days old).

We started noticing this incorrect behavior about a month ago.  

When we look at the resultant website link, it does not include "&referrer=latest-event" at the end of the URL.

### Product Area

Alerts

### Link

https://theorycraft-games.sentry.io/issues/4263316912/?alert_rule_id=5441011&alert_type=issue&project=5710262&referrer=slack

### DSN

https://149a7ac2a7914150b87ce714fd4d6444@o566896.ingest.sentry.io/5710262

**Comment by rachrwang** [comment]
Hi @rayanami - thanks for filing this issue! I'm Rachel, PM for the Issues team.

The experience you've reported is part of an upcoming change we're introducing for Issues, which will default to showing details for a "recommended event". As of today, you should be seeing the following experience when you navigate to any issue:
<img width="399" alt="Screenshot 2023-08-09 at 10 18 11 AM" src="https://github.com/getsentry/sentry/assets/82916311/c478e451-fc3d-4b80-9c63-136b9d229b0f">

The "recommended event" is detected by Sentry as having the most context - which could be a replay, trace, no processing errors, etc. You can always switch to the latest event, or navigate between.

A few questions I have for you:

1. What are your thoughts on this new experience/ UI?
2. Given this update, how would you rate the value from a "latest" event vs. "recommended" for the example you shared above? Are there reasons why "latest" would be more helpful for your use case?

If you'd like to chat live about this feature or any other Issue features, you can schedule directly with me here: https://calendly.com/rachel-wang-sentry/30min. Thanks!

**Comment by rayanami** [comment]
Hi Rachel,

Thanks for the quick response.  For our use case, we are getting a similar
amount of context across all issues within a grouping.

Thus, it's most valuable for us to see the latest issue as other
information contained within the event is more recent (for example,
browsing source context in a stack trace).

Most of my team thought it was a bug when the default setting is
'recommended event'.  A big reason for this is that we rely on the Slack <>
Sentry integration, which reports the latest event.  When a user clicks on
that link they expect to be navigated to that exact event and are confused
when the navigation goes to an older bug affecting a different user.

We would usually prefer the 'latest' event as default.  It's nice to have
the option to go to a 'recommended' event, but certainly would not want
that as default for any of our users.

Best,
Tom

**Comment by rachrwang** [comment]
Thank you for sharing that context!

In the near term, you can update your account settings here: https://theorycraft-games.sentry.io/settings/account/details/, to ensure that your default is always the latest event.

Given that this feature is in EA, we'll be iterating on the experience (so thank you for the feedback!). If you or members from your team have feedback on the "Recommended" experience in the coming days/weeks, please don't hesitate to chime in here.

**Comment by rayanami** [comment]
Perfect, I've adjusted that setting.  Thank you Rachel!
