### ISSUE TITLE
In commit tab, show only first line

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#5444]
Like GitHub, show only the first line, use "..." if there's more.

Example of how this is problematic now:

![image](https://cloud.githubusercontent.com/assets/2153/26430637/a5af0114-40a3-11e7-998b-57f69af2cb74.png)

Should look like:

![image](https://cloud.githubusercontent.com/assets/2153/26430647/bdf6d12a-40a3-11e7-8e2e-5ef7b83b5af5.png)

**Comment by kjlundsgaard** [comment]
https://github.com/getsentry/sentry/pull/5446
