### ISSUE TITLE
Span duration longer than sum of child spans

### ISSUE THREAD

**Issue by mimre25** [getsentry/sentry#54443]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Hi, 

I have an app that every now and then produces spans that have a much higher duration than the sum of child spans.

I'm wondering, how could this happen? 
Is there a way to find out what causes these extreme discrepancies?

### Expected Result

The sum of child span duration should be a sum's duration.

### Actual Result

![image](https://github.com/getsentry/sentry/assets/2582811/f3ee72cb-e029-42f8-9ffa-b05788edaed9)

### Product Area

Performance

### Version

23.6.1

**Comment by narsaynorath** [comment]
Hey @mimre25, the gap could be explained by our SDK not being able to auto-instrument the operations there. It looks like you're on [a version of self-hosted](https://github.com/getsentry/self-hosted/releases/tag/23.6.1) which supports profiling, so something we can consider here is enabling profiling, [docs here](https://docs.sentry.io/platforms/python/profiling/) which can give us more insight into that span.

When you select the span, and there's an associated profile, we'll be able to [show you stacktrace insights](https://docs.sentry.io/product/profiling/#zooming-in-from-performance-to-profiling) which should help give you a better idea of what isn't being instrumented there and you can add custom instrumentation.

For the Python SDK, you'll have to ensure you're running at least version `1.18.0`. Let me know if you have any questions
