### ISSUE TITLE
Dashboards - Ability to show releases in Line & Area Charts

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#54460]
### Problem Statement

For dashboard charts there is no possibility to easily see which release influences the metrics.
We capture both metrics and releases but are unable to manually combine them inside 1 chart.
![Screenshot 2023-08-09 at 19 26 11](https://github.com/getsentry/sentry/assets/25929053/9655ee6b-0183-4085-b605-8996a96de82f)

### Solution Brainstorm

We do this on the performance transaction summary page already.
![Screenshot 2023-08-09 at 19 26 36](https://github.com/getsentry/sentry/assets/25929053/0249c57b-5d2c-49e2-a5fc-3065d5df626e)

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1900) by [Unito](https://www.unito.io)

**Comment by brentc** [comment]
Thanks for the suggestion. We've added this to our backlog and will review against other priorities in the future.
