### ISSUE TITLE
Something wrong with fetching local sourceMap

### ISSUE THREAD

**Issue by DeepenLau** [getsentry/sentry#5448]
I post an issue at forum.sentry.io, thanks!
[https://forum.sentry.io/t/something-wrong-with-fetching-local-sourcemap/1575](https://forum.sentry.io/t/something-wrong-with-fetching-local-sourcemap/1575)

**Comment by dcramer** [comment]
I'm going to close this out as its used specifically for bug tracking in the app (and source maps are definitely functional, as it sounds like this is a docs/configuration issue).

Expect a response on the forum.
