### ISSUE TITLE
[Flaky CI]: tests/sentry/api/endpoints/test_project_key_stats.py test_simple

### ISSUE THREAD

**Issue by ceorourke** [getsentry/sentry#54520]
### Flakiness Type

IndexError

### Name of Job

backend

### Name of Test

tests/sentry/api/endpoints/test_project_key_stats.py test_simple

### Link to Test Run

https://github.com/getsentry/sentry/actions/runs/5815274344/job/15767486437?pr=54512

Since this probably won't be active for long, here's the output:
`FAILED tests/sentry/api/endpoints/test_project_key_stats.py::ProjectKeyStatsTest__InRegionMode::test_simple - IndexError: list index out of range`

### Details

Flaking at ~6 PST. Skipping it here: https://github.com/getsentry/sentry/pull/54521

**Comment by lobsterkatie** [comment]
This test always flakes around 6 pm. Something to do with it being tomorrow in GMT time, I think. (Shouldn't matter, all the times are in GMT, but ¯\\_(ツ)_/¯.)

Related: https://github.com/getsentry/sentry/issues/46402

**Comment by ceorourke** [comment]
Assigning @markstory cause of git blame, sorry 😬
