### ISSUE TITLE
Fingerprint on message value using wildcard doesn't appear to impact grouping (on a long string)

### ISSUE THREAD

**Issue by quickstark** [getsentry/sentry#54574]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Need an Issue with a long message (650+ bytes).

1. Add Fingerprint rule: 
`message:"*Failed to establish a new connection: [Errno 111] Connection refused*" -> connection-error`
2. Ingest events
3. Check if grouping is applied

**Additional Context:** 
In the Event Grouping Details, the default grouping is a bit different than the message: `Failed to establish a new connection: [Errno <int>] Connection refused'`

### Expected Result

Should expect all events with the stated string to be grouped.

### Actual Result

Individual issues are still being created after the Fingerprint Rule was added.

### Product Area

Issues

### Link

Being submitted by Dirk N (Sentry EE) on behalf of a customer. Can share Org internally.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1902) by [Unito](https://www.unito.io)

**Comment by lobsterkatie** [comment]
@quickstark - Interesting. Looks like the parameterization is causing the problem.

This isn't a solution-solution, but can you please run your test again, substituting a `*` for the `111` in your fingerprint rule? In the meantime, I'll solicit opinions on potentially carving out a parameterization exception for `Errorno xxx`.

**Comment by lobsterkatie** [comment]
> @quickstark - Interesting. Looks like the parameterization is causing the problem.
> 
> This isn't a solution-solution, but can you please run your test again, substituting a `*` for the `111` in your fingerprint rule? In the meantime, I'll solicit opinions on potentially carving out a parameterization exception for `Errorno xxx`.

Actually, I'm not sure this is the problem. I'd still love to know the results of the above test, but can you also please try using `error.value:"*Failed to establish a new connection: [Errno 111] Connection refused*" -> connection-error` rather than `message:...`?
