### ISSUE TITLE
chrome-extension:// URLs do not resolve source map location properly

### ISSUE THREAD

**Issue by MeredithAnya** [getsentry/sentry#5459]
When evaluating `sourceMappingURL` directives inside JavaScript files, the source map file URL is resolved relative to the JavaScript file.

Meaning in `http://example.com/static/app.js`, if `//# sourceMappingURL=app.js.map` is found, then the source map is expected to be located at `http://example.com/static/app.js.map`.

This works fine for `http://`, `https://`, `file://` and other standard protocols. But fails for `chrome-extension://` and other non-standard protocols.

The source is [six.moves.urllib.parse](https://docs.python.org/2/library/urlparse.html#urlparse.urljoin), which we use in [javascript/processor.py](https://github.com/getsentry/sentry/blob/master/src/sentry/lang/javascript/processor.py#L190):

```python
from six.moves.urllib.parse import urljoin

urljoin('http://example.com/app/app.js', 'app.js.map')
# result => 'http://example.com/app/app.js.map'

urljoin('chrome-extension://hgfakmfpmkaaamdjfolpjgdofepbfhke/static/app.js', 'app.js.map')
# result => 'app.js.map'
```

cc @mitsuhiko @MaxBittker @benvinegar

**Comment by mattrobenolt** [comment]
Oh, we need to register the protocol with urlparse.

**Comment by maxpaj** [comment]
Is this still an issue? Because I can't see any mapped code on issues in Sentry from the background page of my Chrome Extension.

The source mapping is present at the bottom of the file and the .js.map file is present. 

Is there something else I have to do?

**Comment by avalanche1** [comment]
For anyone struggling: you need to add `--url-prefix` when uploading sourcemaps, like this:
```
`sentry-cli releases -o ${org} -p ${project} files ${version} upload-sourcemaps ${distPath} --url-prefix "chrome-extension://ckcfjkiackeclohodgajcpenmphxjkkb/"`
```
(insert *your* extn id)
