### ISSUE TITLE
getting started on existing project not redirecting correctly

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry#54616]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. open this page on your browser
https://sentry-sdks.sentry.io/projects/sentry-react-native/getting-started/
![image](https://github.com/getsentry/sentry/assets/8229322/64e2affe-a5bf-4dc6-ac19-b35f03c81f34)
2. press the "Back to Platform Selection" button
3. page will open "https://sentry-sdks.sentry.io/projects/new/?referrer=getting-started&project=5428561" but there's a blank screen on it
![image](https://github.com/getsentry/sentry/assets/8229322/70455bbb-1823-4eb0-bee3-27f9baebfc10)

(Checked on Edge on Windows and Safari on MacOS)

### Expected Result

Return to the previous page or to the project settings. (Not entirely sure but not a blank page)

### Actual Result

Screenshot attached on the reproduction steps.

### Product Area

Settings

### Link

https://sentry-sdks.sentry.io/

**Comment by lucas-zimerman** [comment]
Also, How am I supposed to reach the getting-started page?  I used to navigate towards the Instrumentation on the project settings to check the getting started steps, now I can only check when creating a new project?

**Comment by hubertdeng123** [comment]
Ownership of the Projects product area has changed, so I'm going to reset the due date.

**Comment by lobsterkatie** [comment]
@lucas-zimerman Thanks for reporting! We've added it to our backlog for investigation.

**Comment by ArthurKnaus** [comment]
@lucas-zimerman can you verify this issue still persists? I am having troubles reproducing it. 🤔 
If it still happens, can you give me more information?
E.g. is there anything suspicious in the network tab or the dev console?
