### ISSUE TITLE
Allow usage of custom S3 storage backends

### ISSUE THREAD

**Issue by zetaab** [getsentry/sentry#5466]
Current S3 solution supports only AWS S3 endpoint. However, we would like to get support to use own hosted S3 backends like [https://www.minio.io/](minio). [https://docs.sentry.io/server/filestore/](Documentation) does not support adding other hostname (and disable ssl). It looks like there is quite much hardcoded variables in S3 integration https://github.com/getsentry/sentry/blob/master/src/sentry/filestore/s3.py#L238-L288 is there way to modify those in settings file? (I tried it without result)

```
SENTRY_OPTIONS['filestore.backend'] = 's3'
SENTRY_OPTIONS['filestore.options'] = {
    'access_key': env('SENTRY_FILE_ACCESS'),
    'secret_key': env('SENTRY_FILE_SECRET'),
    'bucket_name': env('SENTRY_FILE_BUCKET'),
    'custom_domain': env('SENTRY_FILE_HOST'),
    'use_ssl': False,
    'url_protocol': 'http:'

}
```

still this was connecting towards aws.com

**Comment by mattrobenolt** [comment]
You can! We actually do this ourselves. The setting you want is `endpoint_url`.

We simply have `'endpoint_url': 'http://127.0.0.1:10420',` which should cover everything you need.

The settings you adjusted aren't really relevant in Sentry. They're what would be used to reverse a url for an object to render it directly in a browser. `endpoint_url` is what is used for all the S3 API requests.

**Comment by LukeSheard** [comment]
@mattrobenolt Is this in the `config.yml`? The only reference the endpoint_url I can find in the codebase is https://github.com/getsentry/sentry/blob/f6dcca457eff204243769f860130286d0dad1939/src/sentry/filestore/s3.py#L341 which I can't see being set anywhere?

**Comment by ParthKolekar** [comment]
endpoint_url is actually a parameter passed into the boto3 Session() object. It works as expected.

**Comment by paramaggarwal** [comment]
Is there a way to achieve this via `config.yml` instead of changing the underlying Sentry code in `sentry/src/sentry/filestore/s3.py`?
