### ISSUE TITLE
Collapse consecutive crumbs in replays

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#54688]
Collapse consecutive crumbs of the same category/type in replay details.

e.g. if we have many consecutive mutation crumbs, we should show the first one and a message expressing the number of consecutive crumbs and a way to expand/view them.

See https://github.com/getsentry/sentry-javascript/issues/8420 for more information

**Comment by ryan953** [comment]
@billyvg I think we should take this off the board now. Thoughts?
