### ISSUE TITLE
Users creating a BE project without making a FE one, or using the DSN/loader code from the FE project for their BE.

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry#54696]
**Problem:**

Upon reviewing projects involving events from both backend (BE) and frontend (FE) SDKs, such as `sentry.python.django` and `sentry.javascript.browser`, the following observations were made:

- Typically, users tend to create backend projects and not create frontend ones, and vice versa.
- Users often utilize the DSN/loader code from frontend projects in their backend projects.

**Comment by ale-cota** [comment]
Seems like something specific for Replay and frameworks like NextJS. but we don't have enough context. Closing this for now and will create a new issue if necessary.
