### ISSUE TITLE
Add source maps cli step to node js platfoms

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry#54697]
**Problem:**
Right now, the UI only shows the source maps wizard for frontend platforms. However, we've noticed the following:

- Many people use TypeScript with Node.js applications, whether it's with Express, plain Node.js, or other frameworks.
- Additionally, people bundle Node.js apps, like for Serverless functions, which also require source maps.
- Some Node.js frameworks, such as [NestJS](https://docs.nestjs.com/providers), are built to work seamlessly with TypeScript.

**Solution:**

Introduce a UI element that provides guidance, such as: "If you're transpiling or minimizing your code, utilize the source maps wizard for assistance."

**Comment by ale-cota** [comment]
We can add it similarly to other platforms, but updated copy.

<img width="903" alt="Screenshot 2023-09-11 at 15 06 27" src="https://github.com/getsentry/sentry/assets/26696515/dc65c4a9-5270-4e34-8fe0-03a0ddd4abd7">
