### ISSUE TITLE
Error tem name from sentry.io of my project

### ISSUE THREAD

**Issue by lc4t** [getsentry/sentry#5469]
1. First I create a team named `cnss`
2. create a project `Sender`, team name is `cnss`
3. delete project `sender`
4. delete project `cnss`
5. create team name `lc4t`
6. create a project `Sender`, team name is `lc4t`
7. but error as follow:(the URL is right, title name and team name is wrong)

![](http://ac-HSNl7zbI.clouddn.com/gVasNk4yf1rpDzeIa3CcuNjMFQyzumXycFyaMsn8.jpg)

**Comment by dcramer** [comment]
Am I correct that the 'sender-uv' is the old project? That is, are you accessing the old project's URL and its showing the new team as the selection? If so that seems correct, as on the backend we don't currently say "if theres a different team already selected, allow that selection to stay".

**Comment by lc4t** [comment]
Maybe not.

originally, I just want change `sender` project's team name, from `cnss` to `lc4t`

But after I create team `lc4t`(my username is also `lc4t`), in `sender` project  settings, there is only `cnss` team name but no `lc4t` tean name.

So I delete project and team `cnss`, then create new, 

no `cnss` team and no `sender`. only `lc4t` team name there

create `sender` in team `lc4t`, but after create it success, the project `sender` is also belongs to `cnss`..

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
