### ISSUE TITLE
Enable Suspect Commits for Unity

### ISSUE THREAD

**Issue by serglom21** [getsentry/sentry#54702]
### Problem Statement

It would be great to have [suspect commits](https://docs.sentry.io/product/integrations/source-code-mgmt/github/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2F#suspect-commits-and-suggested-assignees) working for Unity.

With the [new suspect commit logic](https://blog.sentry.io/suspect-commits-via-git-blame/), I am not sure if this is something that should work without making changes to the client as long as you have your Source Code Management integration setup on Sentry. I tried testing this out but did not get any suspect commits on my issues

### Solution Brainstorm

Implement suspect commits for Unity as it is for other languages and frameworks 😄 

### Product Area

Issues

**Comment by hubertdeng123** [comment]
Bot is not having a good time due to GitHub outage with webhooks, sorry!
