### ISSUE TITLE
INC-454 Add more monitoring around alerts firing

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#54729]
Ticket for an action from https://www.notion.so/sentry/INC-454-Metric-alerts-misfiring-96cd3b3c49374f159d75f0b7e27e7ed3

This incident caused several alerts to fire incorrectly. We can see this in the graph here: https://app.datadoghq.com/dashboard/xyh-g9w-jqe/sentry-subscriptions?fullscreen_end_ts=1689728211478&fullscreen_paused=true&fullscreen_section=overview&fullscreen_start_ts=1689546239503&fullscreen_widget=2849334327457114&from_ts=1689546239503&to_ts=1689728211478&live=false

It'd be good to have a datadog monitor or sentry alert to capture a large spike like this in the future.

**Comment by snigdhas** [comment]
Added the `Alert rule trigger volume too high` monitor on Datadog - pending review.

**Comment by brianthi** [comment]
Remaining work will be to add a playbook on the monitor to inform what the process would be to resolve the monitor failing

**Comment by snigdhas** [comment]
Added a playbook to the alert pointing out possible causes and tools to use to dig deeper.
