### ISSUE TITLE
Improving Search Capabilities

### ISSUE THREAD

**Issue by MeredithAnya** [getsentry/sentry#5475]
**Problem**
Applying multiple search parameters could lead to no results for parameters that would have > 1000 results. Stems from code [here](https://github.com/getsentry/sentry/blob/master/src/sentry/search/django/backend.py#L62).

**Example**
A search for `release:1.0.0` has more than 1000 results. 
A search for `release:1.0.0 environment:custom` might not match anything because the first 1000 that match `environment:custom` don't have `release:1.0.0` - this depends on the order of the execution for [matching tag values](https://github.com/getsentry/sentry/blob/master/src/sentry/search/django/backend.py#L142).

@tkaemming

**Comment by tkaemming** [comment]
This is also blocking further progress on GH-4702.

**Comment by tkaemming** [comment]
See also: GH-4050

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
