### ISSUE TITLE
 The OpsGenie integration is not available when **creating** issue alert

### ISSUE THREAD

**Issue by sepbehroozi** [getsentry/sentry#54750]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Make sure the OpsGenie integration is configured
2. Go to "Alerts" menu from the sidebar
3. Click on "Create Alert" button
4. Make sure "Issues" is selected, then click on the "Set Conditions" button
5. In the `Then` section, click on the "Add Action" drop-down
6. Select "Send a notification via an integration"

### Expected Result

It's expected that there will be an item named "OpsGenie" alongside other integrations. Like the screenshot below:
![Screenshot 2023-08-15 at 09 29 13](https://github.com/getsentry/sentry/assets/1960884/a22cd72e-da28-4b4f-a471-fb6b6d58e11a)

### Actual Result

The integration drop-down only shows "Webhook".
![Screenshot 2023-08-15 at 09 28 11](https://github.com/getsentry/sentry/assets/1960884/810ff533-7efb-4b43-a86a-8abc474b70bf)

## Workaround
1. Save the alert without adding a "Send a notification via an integration" action
2. On the alert details page, click on the "Edit Rule" button
3. Now the OpsGenie integration is available

### Product Area

Alerts

**Comment by mifu67** [comment]
@sepbehroozi to send an alert via the Opsgenie integration, there should be an option labeled "send an Opsgenie notification" in the dropdown menu. Does this now show up for you?

**Comment by Dhrumil-Sentry** [comment]
@sepbehroozi We have built a new Opsgenie integration https://github.com/getsentry/sentry/discussions/54156 which will be made generally available soon

While we investigate this issue would you like to be part of the Beta for the new integration?

**Comment by sepbehroozi** [comment]
Thanks @Dhrumil-Sentry for your reply.
We're part of the Beta users of the new integration already but I haven't configured it yet.
I'll let you know if the new integration has the similar issue 👍

**Comment by mifu67** [comment]
Closing—this issue seems to be fixed by the new Opsgenie integration. You should migrate from the plugin to the integration if possible.
