### ISSUE TITLE
Create a Sentry Project via web api

### ISSUE THREAD

**Issue by fox-sizemore** [getsentry/sentry#54805]
### Problem Statement

I'm looking for a way to create a new Sentry Project via webhooks or a similar web api so that we can automate the process of creating new projects when we startup a new project. It doesn't seem that there is a way to do this currently after poking around on the docs. Is this something you guys have considered / I might have missed?

Thank you very much for your help!

### Solution Brainstorm

A webhook that can provide info to the Sentry backend such that it can create a new project (name, platform, etc).

### Product Area

Projects

**Comment by Dhrumil-Sentry** [comment]
Hi @fox-sizemore we have APIs for project creation : https://docs.sentry.io/api/projects/create-a-new-project/

We're actively investing in improving our API docs so please let us know if anything is unclear

**Comment by fox-sizemore** [comment]
Thank you @Dhrumil-Sentry! I'll use this and come back if I hit any major blocks :)
