### ISSUE TITLE
Listing members through the organizations API does not return the full list (seems to skip users with no team)

### ISSUE THREAD

**Issue by kot0dama** [getsentry/sentry#54814]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

List all Sentry users through the API on self hosted Sentry 9.1.2.
GET /api/0/organizations/:slug/users/

### Expected Result

Expected result is the full list of all users per https://docs.sentry.io/api/organizations/list-an-organizations-users/

### Actual Result

Actual result is a limited list of users, apparently only those who are members of at least one team.
I confirmed there is no pagination Link headers.
I also confirmed a user set as "Owner" but with no team does not show up in the API results.

See also https://forum.sentry.io/t/api-does-not-returns-the-entire-list-of-organizations-users/14928

### Product Area

Other

### Version

9.1.2

**Comment by Dhrumil-Sentry** [comment]
@kot0dama Thanks for the feedback, we've added this to our backlog and will keep the issue updated

**Comment by schew2381** [comment]
Closing as resolved in https://github.com/getsentry/sentry/issues/66147

**Comment by kot0dama** [comment]
Using the `members` indeed fixes my issue, indeed I did not realize `users` had a different behavior.

Many thanks!
