### ISSUE TITLE
Sentry doesn't seem to respect sourceMappingURL for publicly hosted source maps

### ISSUE THREAD

**Issue by wegry** [getsentry/sentry#54819]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which SDK are you using?

@sentry/browser

### SDK Version

7.64.0

### Link to Sentry event

https://streak.sentry.io/issues/4385391052/?project=4504322969763840&query=error.type%3AWaitForError&referrer=issue-stream&sort=user&statsPeriod=14d&stream_index=0

### SDK Setup

```javascript
Sentry.init({
  dsn: process.env.SENTRY_EXT_DSN,
  environment: info.channelName ?? (!isDev ? 'production' : 'dev'),

  integrations: [
    new Sentry.BrowserTracing({
      startTransactionOnPageLoad: false,
    }),
  ],

  tracesSampleRate: 1,

  // Set sampling of transactions for performance monitoring.
  beforeSendTransaction(transaction) {
    // Transactions add up very quickly. Sample far fewer transactions than Error events.
    // If we ever move to opentelemetry and sample 100% of the time, we should be
    // able to sample more aggressively.
    if (Math.random() <= actualSentrySampleRate * 0.025) {
      return transaction;
    }

    return null;
  },
  beforeSend(event, _hint) {
    if (Math.random() <= actualSentrySampleRate) {
      return event;
    }

    return null;
  },
});
```

### Steps to Reproduce

1. Deploy and monitor publicly hosted js without content hashes in file names, example: https://www.inboxsdk.com/build/platform-implementation.js.
2. Change content of files and keep filename the same. Sentry source maps will continue to be cached and point to old module/method/function names.
1. As part of work on InboxSDK/InboxSDK#950, I've pushed up a change where the sourceMappingURL comment at the bottom of https://inboxsdk.com/build/platform-implementation.js includes a webpack generated contenthash. The content hash is there only in the source map because [that file url](https://inboxsdk.com/build/platform-implementation.js) can't change. Example: https://www.inboxsdk.com/build/platform-implementation.js.dc3408d3b642000acf5b940c12e1f12d.map

### Expected Result

Sentry should ideally scrape the current sourceMapURL, even if the asset path hasn't changed, in this case https://www.inboxsdk.com/build/platform-implementation.js.

### Actual Result

When an error is reported to sentry, source maps look like they're still caching the contenthash-less version of the source map URL (https://www.inboxsdk.com/build/platform-implementation.js.map).
![Screenshot 2023-08-15 at 09 01 22](https://github.com/getsentry/sentry-javascript/assets/5156873/6148a6a6-b3bf-4ab6-b428-007402025655)

This source map is presumably cached from when we started using sentry, many months ago. The source code has drifted away from this map making the file name/method/function mapping incorrect.

I spoke with a support rep and they mentioned

> There is caching for self hosted source maps. They are cached for 1 week everytime the file gets accessed. This translates to essentially forever if the file gets touched once a week.

This blog post https://blog.sentry.io/how-we-made-javascript-stack-traces-awesome/#where-to-go-from-here makes it sound like the source file is considered alongside the sourceMap.

_edit: bumped `@sentry/browser` to 7.64.0 and swapped Expected and Actual Result sections._

**Comment by loewenheim** [comment]
Hi, the problem here is that minified JS files also get cached, and since the minified file URL doesn't contain a hash, the new version with the correct source mapping URL is never re-fetched. We'll have to rethink our caching logic to address cases like this—It was originally created for native debug files, where we may assume files to be immutable.

**Comment by wegry** [comment]
As a fairly convoluted workaround, it seems that manually updating both the source and source map in sentry dislodges the stale cached source map. Here's roughly what I did with `@sentry/cli@1`.  The CLI commands came from https://docs.sentry.io/product/cli/releases/#sentry-cli-sourcemaps and probably(?) work for `@sentry/cli@2` as well.

1. Download platform-implementation.js from https://www.inboxsdk.com/build/platform-implementation.js
2. Find the latest production of our main [sentry project] release in sentry. Copy the version and substitute it for $VERSION in the next command. You'll also need a sentry auth token for your user with release privileges.
3. Upload the platform-implementation.js source to sentry with: `SENTRY_PROJECT=[sentry project] SENTRY_AUTH_TOKEN=[sentry-auth-token] SENTRY_ORG=streak SENTRY_LOG_LEVEL=debug yarn  sentry-cli releases files "$VERSION" upload [localpathto]/platform-implementation.js https://www.inboxsdk.com/build/platform-implementation.js` with your auth token and the latest  sentry release version.
4. Find the source map file corresponding to the sourceMapURL at the bottom of https://www.inboxsdk.com/build/platform-implementation.js. Download and use the file name and content hash to upload the local file to sentry at that path.
5. Upload the corresponding source map file mapped to from with `SENTRY_PROJECT=[sentry project] SENTRY_AUTH_TOKEN=[sentry-auth-token] SENTRY_ORG=streak SENTRY_LOG_LEVEL=debug yarn sentry-cli releases files "$VERSION" upload-sourcemaps --no-sourcemap-reference [localpathto]/platform-implementation.js.[contenthash].map https://www.inboxsdk.com/build/platform-implementation.js.[contenthash].map`

**Comment by Swatinem** [comment]
That looks like a working solution as well.
We eventually solved this in our backend as well, to only cache scraped files for 1h. We may revisit the exact time frame at some point, but the main point is that scraped files will now pick up changes after a while instead of being immutable forever.
