### ISSUE TITLE
Track source map method in Amplitude

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#54834]
**Problem**: We'd like to determine how effective symbolication using the new debugIDs method is compared to the legacy method that uses releases.

**Proposed Solution:** Enrich the existing Amplitude event “Issue Details: Viewed", to track source map method: `release`, `debugID`.

**Comment by smeubank** [comment]
method is good so it is not boolean

on an event there is "resolved_with":"debug-id". The tag on the amplitude event could simply copy over what is there, so in amplitude we could group by: resolve_with same as sentry

**Comment by matejminar** [comment]
@smeubank `resolved_with` is per frame. If there's more than one `resolved_with` per event, we can send an array to amplitude - does that sound good? Alternatively, we could just send one (the one that has majority or something).
