### ISSUE TITLE
Clean up integration-docs-platforms

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#54835]
Once the profiling and replay docs are moved over to the sentry repo, we can do a cleanup of integration-docs-platforms.
That would include:

- Webpack configuration that sets up this integration-docs-platforms alias
- Webpack plugin to download
- Python implementation to download

See https://github.com/getsentry/sentry/pull/54678/files#r1293806721

**Comment by ArthurKnaus** [comment]
I checked the current implementation, there is no webpack plugin anymore. However, there is a different mechanism now.
What remains to do is:
1. Remove [Inline docs](https://github.com/getsentry/sentry/blob/master/static/app/components/events/interfaces/spans/inlineDocs.tsx) that are shown in the trace view for spans that are missing instrumentation.
2. Remove the `build-platform-assets` build step that downloads the docs on backend build (see [_integration_docs.py](https://github.com/getsentry/sentry/blob/master/src/sentry/build/_integration_docs.py))
3. Remove [ProjectDocsPlatformEndpoint](https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/project_docs_platform.py)
