### ISSUE TITLE
Unknown object appears in issues page

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#54864]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

![Screenshot 2023-08-15 112144](https://github.com/getsentry/sentry/assets/99350819/b340df0d-f522-4c9e-82b7-5cb2511bde46)

Report from customer: You should be able to reproduce the issue if your screen height is not too large.

### Expected Result

Despite browser height the object in the image should not appear

### Actual Result

The object appears on issue page

### Product Area

Issues

**Comment by scefali** [comment]
@kerenkhatiwada From what I can see, if you scroll down you can see the full image. Is that not what happens for you?

**Comment by super-chill** [comment]
Hey, I guess I'm probably the customer here.

My original message is:

> It's pretty scary when seeing the screenshot. I thought there's a snail 🐌  on my screen!

**Comment by lobsterkatie** [comment]
@super-chill Thanks for the feedback! We'll pass it along to our design team.
