### ISSUE TITLE
Active releases not showing in Dashboard filter

### ISSUE THREAD

**Issue by ckurt3** [getsentry/sentry#54906]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Have a release, in my case version 4.3.6 that was released outside of dashboard window (for example, if version 4.3.6 was released 48 hours ago but dashboard is set to 24 hours visibility)
2. Attempt to filter the dashboard to this release

### Expected Result

If the version was active in the last 24 hours (in this case, 4.3.6 was the most active release in that time window), then I should be able to filter to it.

### Actual Result

It seems that since the release was released longer than 24hrs ago (?), it does not show in the filter.

<img width="1460" alt="Screenshot 2023-08-16 at 10 56 04 AM" src="https://github.com/getsentry/sentry/assets/7183617/750a26fd-4df6-48ca-9fbd-42524cb49db6">
<img width="337" alt="Screenshot 2023-08-16 at 10 56 14 AM" src="https://github.com/getsentry/sentry/assets/7183617/4fb70eb0-164a-49ca-8964-29eb6d0189cf">

### Product Area

Dashboards

### Link

https://zoox.sentry.io/dashboard/48481/?project=4504601293553664&statsPeriod=7d

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1912) by [Unito](https://www.unito.io)

**Comment by realkosty** [comment]
I'm observing the same and have another customer complaining about this

**Comment by brentc** [comment]
Thanks for reporting this. This is currently a known limitation to how the feature was implemented. This limitation has already been tracked in this backlogged issue: #43781. Closing this one as a duplicate, and will reconsider the existing issue against other priorities soon.
