### ISSUE TITLE
Add option to configure an alert as Low Urgency for PagerDuty

### ISSUE THREAD

**Issue by cseas** [getsentry/sentry#54921]
### Problem Statement

All alerts created from Sentry are reported as High Urgency on PagerDuty. We don't have any option to configure their urgency.

<img width="804" alt="Screenshot_2023-08-17_at_1_08_36_PM" src="https://github.com/getsentry/sentry-javascript/assets/29686866/eec915b6-6da6-480f-bd83-6fd1c12749a1">

### Solution Brainstorm

We need an option in alert configuration to set an alert as "Low Urgency" when its reported to PagerDuty. This is a critical requirement for us because our on-call developers receive phone calls for "High Urgency" alerts and we don't want to spam them for every alert created by Sentry.

**Comment by scefali** [comment]
Seems like a decent idea, adding to our backlog.

**Comment by abhieshekumar** [comment]
➕1, to the issue.

**Comment by cathteng** [comment]
We are able to allow customization for the severity of the alert via the Pagerduty API https://developer.pagerduty.com/api-reference/368ae3d938c9e-send-an-event-to-pager-duty, and are adding support for this.

But whether an alert is high or low urgency is only configurable on the Pagerduty side. https://support.pagerduty.com/docs/configurable-service-settings#step-one-configure-urgencies-on-a-service
![image](https://github.com/getsentry/sentry/assets/70817427/ff6c835a-a0a6-41ca-8229-9880f542312c)

**Comment by Dhrumil-Sentry** [comment]
This has been shipped, please see the changelog: https://sentry.io/changelog/change-the-severity-for-your-pagerduty-and-opsgenie-alerts/
