### ISSUE TITLE
Monitors show multiple times when applying environment filters

### ISSUE THREAD

**Issue by amadeogallardo** [getsentry/sentry#54933]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Navigate to "Crons".
2. Click the environment filters.
3. Filter by more than one environment using the checkboxes.

### Expected Result

- Each monitor shows up once.
- Each monitor shows each environment in its timeline column.

### Actual Result

- Monitors are duplicated.
- Each monitor shows each environment in its timeline column (no changes).

![image](https://github.com/getsentry/sentry/assets/15894109/47227452-5f71-403c-ae99-0cb9106b502a)

Since the timeline column already stacks each environment, it seems unnecessary (or possibly a bug) that each monitor shows more than once.

### Product Area

Crons

### Link

/crons

**Comment by amadeogallardo** [comment]
Note that this works correctly when not filtering by any environment (when it shows "All Envs" on the filter).

**Comment by davidenwang** [comment]
Hi @amadeogallardo thanks for reporting this! This is definitely not expected behavior and we'll remove the duplication in this view.

**Comment by markstory** [comment]
I checked this today and this issue has been resolved.
