### ISSUE TITLE
"Client Keys" should be ordered by something other than `id`

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#54935]
### Problem Statement

In Project Settings -> Client Keys, the list of keys are ordered by `id` which does not make sense from a user perspective. We should change the order of this in the UI to sort by something more logical. (I would avoid changing this in the API as surely there's someone out there that depends on the existing behavior)

### Solution Brainstorm

Some ideas:

* name - I don't love this because names are autogenerated and are actually a bit difficult to change (you have to click Configure)
* date created (asc?) - this would at least make it easier to identify based on age of the key. (e.g. you generate a new key to test and are confident the last key in the list is the newest/test key)

### Product Area

Settings - Projects

**Comment by NeetigyaPod** [comment]
Hi, can I work on this or is this resolved?

**Comment by billyvg** [comment]
@NeetigyaPod Sorry, this looks like it's been resolved! I am seeing the API return results sorted by date created, desc. (Though the source doesn't seem to agree 🤔 https://github.com/getsentry/sentry/blob/db1ac76efbdb61e258d6f7edaca0ff04189864b3/src/sentry/api/endpoints/project_keys.py#L70)

**Comment by billyvg** [comment]
@NeetigyaPod I did notice something else -- when you add a new key (e.g. clicking on "Generate New Key"), it adds a new key to the bottom, but the list is sorted with newest at the top (e.g. on fresh reload, the key you added will be at top of list). You could change to ensure that the list is always sorted.

**Comment by NeetigyaPod** [comment]
Hi sure, I would like to. Can you help guide me a bit ,since I am new to OpenSource?
