### ISSUE TITLE
Check why Sentry does not ingest request errors when using `handleXhrErrorResponse`

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry#54945]
In the [PR](https://github.com/getsentry/sentry/blob/eea3f5131b3a6e42ce838ea146735a6ca5f1dc4b/static/app/components/onboarding/gettingStartedDoc/useSourcePackageRegistries.tsx#L37) we are using `handleXhrErrorResponse` to send an error event to Sentry in case of request failures. The problem is that apparently Sentry is not ingesting errors and it was noticed that with the following structure, everything works:

```
new Error(message, {
            cause: {
              responseText: err.responseText,
              responseJSON: err.responseJSON,
              status: err.status,
              statusText: err.statusText,
              name: err.name,
              stack: err.stack,
            },
          })
```

We have to investigate why this is happening and make sure that errors are being captured.

**Comment by matejminar** [comment]
@ArthurKnaus will bring this up in fronted TSC.
