### ISSUE TITLE
Sample event not created properly for ASP.NET Core projects

### ISSUE THREAD

**Issue by isabellaenriquez** [getsentry/sentry#54965]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a ASP.NET Core Project
2. Go to the Issues page
3. Click the Create a Sample Event button

### Expected Result

The page for the sample error should reflect the data from the ASP.NET Core sample found at `src/sentry/samples/aspnetcore.json`. 

### Actual Result

Instead, it uses the JavaScript sample, which is the default used in the case the samples for the platform nor the language cannot be located, even though a sample does exist in the codebase. Although the message says, "This is an example ASP.NET Core exception," the files referenced, the stack trace, and the breadcrumbs all come from the JavaScript sample.

<img width="1512" alt="image" src="https://github.com/getsentry/sentry/assets/45607721/653b15b0-ba80-496f-82b0-72b3512f316f">

<img width="922" alt="image" src="https://github.com/getsentry/sentry/assets/45607721/1e86da64-8a82-45e5-8834-a132c32cf403">

<img width="910" alt="image" src="https://github.com/getsentry/sentry/assets/45607721/40b7edf7-23f0-4294-a03a-725236bfc244">

### Product Area

Issues

**Comment by JoshFerge** [comment]
we've gotten rid of the "create sample event" flow, which has been replaced with a more interactive onboarding requiring SDK setup.
