### ISSUE TITLE
unable to install GitHub Enterprise

### ISSUE THREAD

**Issue by awentzel** [getsentry/sentry#54999]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Follow these instructions https://docs.sentry.io/product/integrations/source-code-mgmt/github/
2. Fill out the following form
![Screenshot 2023-08-17 at 2 33 56 PM](https://github.com/getsentry/sentry/assets/16669785/840359df-2b19-4b88-8e24-8e04794ed9f0)

## Other details
Using Brave browser, shields on/off results in no difference.
* sentry installation is pre-existing
* added CodeCov plan same day
* `GitHub` Integration already exists
* `GitHub Enterprise` Integration isn't working
* GitHub Org has private/public repositories

### Expected Result

Success

### Actual Result

![Screenshot 2023-08-17 at 2 35 01 PM](https://github.com/getsentry/sentry/assets/16669785/f880a27c-1868-4e3e-a340-c49dfda7352a)

No logs present from attempts

### Product Area

Settings - Integrations

### Link

https://trans-stat.sentry.io/organizations/trans-stat/integrations/github_enterprise/setup/?

**Comment by Dhrumil-Sentry** [comment]
Hi @awentzel Thanks for opening this issue, we're adding this to our backlog and we will update the ticket once we investigate this

**Comment by awentzel** [comment]
> Assigning to @getsentry/support for [routing](https://open.sentry.io/triage/#2-route) ⏲️

How long does the triage / backlog process generally take? Thanks,
