### ISSUE TITLE
Add UI for enabling test for a given alert

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry#54994]
![CleanShot 2023-08-17 at 13 44 41](https://github.com/getsentry/sentry/assets/10888943/6364d3a7-befd-4597-b23f-ea34cfddb641)

**Comment by malwilley** [comment]
Backend code controls what is shown here, so this ticket is no longer necessary (and will be completed along with https://github.com/getsentry/sentry/issues/54252)
