### ISSUE TITLE
Integration with ClickUp doesn't work

### ISSUE THREAD

**Issue by alvar-hoenig** [getsentry/sentry#55006]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I set up the integration between sentry and clickup. When I try to create a clickup task from sentry, it works for me, however not for anyone else. They will get an error - see screenshots. Any idea what can be wrong about our set up? Creating tasks directly from sentry errors is crucial for us to using this integration.

Thanks.
![CU_task_create_request](https://github.com/getsentry/sentry/assets/134983142/40dc1555-6577-4873-8dfb-15e7992094b3)
![CU_task_create_response](https://github.com/getsentry/sentry/assets/134983142/e3128ed9-0503-4be3-bcd7-3c2268b51868)

### Expected Result

Every CU member should be able to create CU task from sentry.

### Actual Result

Getting error
![CU_task_create_request](https://github.com/getsentry/sentry/assets/134983142/9c7e4cd8-38ae-4f9d-a48a-88b064b62caa)
![CU_task_create_response](https://github.com/getsentry/sentry/assets/134983142/2e3de42a-a913-4c90-94c4-1e26f6f789aa)

### Product Area

Other

**Comment by scefali** [comment]
@alvar-hoenig Seems like an issue with ClickUp's service. You'll need to contact their support.

**Comment by alvar-hoenig** [comment]
Hi,
I finally got the response from ClickUp. They say the problem is on your
side. Please I attached a screenshot of the error which ClickUp is getting
from Sentry.

Thanks.
Best Regards,

*Alvar Honig*
Director of Engineering | Momence <https://momence.com>

**Comment by alvar-hoenig** [comment]
Hi,
I definitely attached a screenshot to my email, perhaps it doesn't work with the gh integration?
Trying again directly from GH:

![Image](https://github.com/user-attachments/assets/219b2c95-1083-48f2-ade6-a0af1dcc67ab)

The error says "Error: There is no free venue available for selected time."

Your comment about non 2xx response code doesn't make sense to me. The error I am attaching is error which CU got when called Sentry. Not the other way around. That's what CU told me.

Anyway, you understand that I, as a customer, don't enjoy the position of being a middleman between Sentry and CU. It would be great if you talk directly to CU, if you have any additional questions. That's what I would expect from two service which claim they have been integrated.

Thanks.

Best regards,
Alvar

**Comment by scefali** [comment]
@alvar-hoenig You are a bit confused the error you are showing is the error for the Sentry issue you are trying to make a ClickUp issue for. That's why it's in the payload section. That error came from your application, not Sentry. The error you're looking for would be in the response, not the payload.

> Your comment about non 2xx response code doesn't make sense to me. The error I am attaching is error which CU got when called Sentry. Not the other way around. That's what CU told me.

In fact, as I mentioned before, the error you are showing is actually from your application, not Sentry or ClickUp.

> Anyway, you understand that I, as a customer, don't enjoy the position of being a middleman between Sentry and CU. It would be great if you talk directly to CU,

I understand the frustration of being caught in the middle, but I don't actually work at Sentry full-time anymore so I can't talk to them on behalf of Sentry. Tagging @Dhrumil-Sentry to see if he can help.

**Comment by alvar-hoenig** [comment]
Got it, thanks. The screenshot is from the ClickUp support. In other words, they sent me a useless screenshot to share with the Sentry team. Nice.

**Comment by leedongwei** [comment]
@alvar-hoenig Can you send this public GH thread to the ClickUp folks? We can debug it together here.

**Comment by alvar-hoenig** [comment]
Thanks, Danny. In fact I did. They only complained I shouldn't solve Sentry problems with Stephen who doesn't work in Sentry any more.

**Comment by leedongwei** [comment]
Sentry is contracting work out to @scefali. He's no longer working _at_ Sentry, but he's working _with_ Sentry. 

I'm here to figure out priorities for the team + contractors. I'll let the ClickUp folks chime in here because I need more info.

**Comment by Christinarlong** [comment]
Closing, since issue is stale. Feel free to open a new one, if this problem is still happening.
