### ISSUE TITLE
Create Jira ticket with 'None' value in custom select field

### ISSUE THREAD

**Issue by dounan** [getsentry/sentry#5500]
When using the Sentry UI to create a new Jira issue, the UI doesn't seem to respect the default value of 'None' for a custom select field.

Here is the config in Jira
![image](https://cloud.githubusercontent.com/assets/1095431/26704991/f07dbaa6-46e7-11e7-905b-2b30b1d1f6ac.png)

Here are the options in Sentry
![image](https://cloud.githubusercontent.com/assets/1095431/26705005/150888b0-46e8-11e7-8b4b-401c2e8585a3.png)

Notice how there is no option to select 'None'.

**Comment by dmnd** [comment]
When the jira screen is first loaded, this custom field appears like it has a value:

![image](https://user-images.githubusercontent.com/4427/29979661-4238063e-8efb-11e7-92d3-cb0c4d1c4a23.png)

But looking at the react devtools, the `state.value` is `""`. Once I click an item, `state.value` changes to an id.

I notice there's an `allowEmpty` prop which is set to `false`, but setting it to true doesn't seem to clear the value in the UI — not sure what's up with that.

So if you create an issue without touching the select field, you can create an issue without having to pick an option. This is a decent workaround for this bug.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
