### ISSUE TITLE
Sentry's unavailability should not affect app's performance or make it crash

### ISSUE THREAD

**Issue by pawel989** [getsentry/sentry#55012]
### Problem Statement

In case of Sentry service being down or not available, the sentry log requests stack and go into infinite loop. That causes the original application performance to drop dramatically and eventually crash.

It would be great to run health checks on the Sentry service to avoid the risk of having the original application crash due to sentry availability issues. Possibly limit the Sentry log requests in case of such event.

### Product Area

SDK and maybe APIs

**Comment by armenzg** [comment]
Hi @pawel989 do you have steps to reproduce?

**Comment by armenzg** [comment]
What stack are you using? What SDK version?
