### ISSUE TITLE
Suspect commits not showing up in our Android and iOS errors

### ISSUE THREAD

**Issue by idosun** [getsentry/sentry#55044]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

We're associating commits to our releases and while we see suggested assignees based on commit data for some of the issues in our issue stream,
- None of the issues actually show a suspect commit
- The suggested assignee is not showing up in the Assigned To dropdown 

Steps to reproduce
- Set commits to an Android project release
- Trigger an error related to the files in the associated commits

### Expected Result

Issues showing suggested assignees based on commit data in the issues stream, should present the actual suspect commit when navigating to that issues detail page. 

### Actual Result

No suspect commit appears in the issue detail page 

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1913) by [Unito](https://www.unito.io)

**Comment by malwilley** [comment]
I believe this should be fixed by the changes here: https://github.com/getsentry/sentry/pull/62768

The suspect commit docs have been updated to reflect this: https://docs.sentry.io/product/issues/suspect-commits/
