### ISSUE TITLE
stream view filter reacts incorrectly to keyboard input

### ISSUE THREAD

**Issue by MaxBittker** [getsentry/sentry#5511]
steps to reproduce:

type "is:res" into stream view filter bar
hit down arrow once or twice to select `is:unresolved` or `is:resolved`

hit enter

Expected behavior: search token will be replaced with highlighted value, then search will trigger

behavior: search triggered with "is:res"

**Comment by MaxBittker** [comment]
autocomplete uses tab only and it's better that way

**Comment by benvinegar** [comment]
Some background:

When we first implemented search, we actually DID map "enter" to select the first autocomplete item. But we ran into a bunch of situations where this behavior was problematic, e.g. if you typed _faster_ than autocomplete you could hit race conditions where your answer would be replaced by an autocomplete item.

At the end of the day, we decided NOT to make "Enter" modal (two behaviors depending on state) and made "Tab" the default auto-complete selection key.

See #2332 #2024 #2122
