### ISSUE TITLE
Snooze alerts for a specified period

### ISSUE THREAD

**Issue by cseas** [getsentry/sentry#55127]
### Problem Statement

Often when we get an alert, the team starts working on a fix but meanwhile we don't want the same alert to trigger again as we're already aware of the issue. It causes a lot of noise.

Right now there's a "Mute" option on alerts but there's no way to specify a time period for it so it's auto-enabled sometime later. This leads to scenarios where someone might Mute an alert but forget to enable it again.

<img width="449" alt="Screenshot 2023-08-20 at 11 45 17 AM" src="https://github.com/getsentry/sentry/assets/29686866/3daee69b-d432-430e-b89c-a44ddf067be0">

### Solution Brainstorm

We want a "Snooze" option for alerts similar to PagerDuty. Say, I Snooze an alert for 8 hours, then it should get re-enabled after 8 hours.

### Product Area

Alerts

**Comment by saponifi3d** [comment]
Thanks for submitting this feature request. Unfortunately, I don't think we're planning on implementing this.
