### ISSUE TITLE
Filter errors that are not related to my team

### ISSUE THREAD

**Issue by matany-orca** [getsentry/sentry#55128]
### Problem Statement

Hi,
In dashboards - Id like to be able to create a table based on errors, but be able to filter out errors that are not related (e.g. assigned) to my team. 
I know that "assignment" is ISSUE related, but if ill change the dataset to issues then i wouldnt be able to use the table for its purpose - top X errors, right? Id like to be able to combine both datasets to have TOP 10 ERRORS THAT BELONG TO MY TEAM
tnx

### Product Area

Dashboards

**Comment by brentc** [comment]
Hi @matany-orca.

Are you wanting to sort the table by the Issue's error count, and filter to just those assigned to your teams?

I believe you can achieve that result with the `events` column in the Issues set:

<img width="656" alt="image" src="https://github.com/getsentry/sentry/assets/466158/447ad28d-5b8d-4a36-a201-ab124450b248">

Please let me know if I'm misinterpreting the request though!

**Comment by DominikB2014** [comment]
@matany-orca I'm going to close this as it appears the issue you're reporting is a already a feature of sentry. If this is not the case or you expected this to be more intuitive, feel free to open a new issue stating so!
