### ISSUE TITLE
Rust onboarding not showing SDK version

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#55131]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Project creation
2. Create a new Rust project

### Expected Result

The onboarding flow show the correct snippet to be added to Cargo.tom with current version of the SDK

```
[dependencies]
sentry = "0.31.5"
```

### Actual Result

it shows:

![Screenshot 2023-08-21 at 10 26 35](https://github.com/getsentry/sentry/assets/64906376/10c5616d-5b4a-4ca9-87b6-7b73572d591a)

### Product Area

Unknown

**Comment by Dhrumil-Sentry** [comment]
@ale-cota is this something for your team to look into?

**Comment by schew2381** [comment]
Just double checked this and it seems to be working now
