### ISSUE TITLE
Autofill of empty WHEN condition upon saving alert rule

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#55130]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create an alert rule with empty WHEN and IF conditions so that it detects every new event
2. Save the rule

### Expected Result

The alert rule is saved with the inputed conditions.

### Actual Result

After clicking on save, the WHEN condition is autofilled with the "A new issue is created" rule. A 400 "Invalid input" error is thrown. This has also been tested on an incognito window.

[Here is the replay in Sentry's Sentry](https://sentry.sentry.io/replays/96b19ce4a4fb458dbca5a2096f23570d/?n_detail_row=69&referrer=%2Fdiscover%2F%3AeventSlug%2F&t=155&t_main=network). Adding the HAR file from the customer in the connected internal ticket.

### Product Area

Alerts

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1911) by [Unito](https://www.unito.io)

**Comment by bml1g12** [comment]
In case it's useful for others, in the mean time while this bug is to be resolved, a workaround for this seems to be to set  "WHEN The issue is seen more than BLANK times in ONE minute"

**Comment by brianthi** [comment]
Thanks for reporting this! Looks like a bug, we'll take a look at it soon.

**Comment by brianthi** [comment]
We no longer allow saving an alert without a WHEN or IF condition, unless it has an action. The UI flow should now reflect this and throws an error when this is the case. The goal was to reduce alerts triggering on every event without good reason to. If the customer has a specific use case which they want to have alerts on every event without an action, then please create a ticket for that as our PM team would like to understand those use cases better. Thanks!
