### ISSUE TITLE
Design: Upsell on Dead/Rageclick emphasizes the requirements more than the promise

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#55145]
TBD

**Comment by Jesse-Box** [comment]
@jas-kas @ryan953 

I think instead of showing the dead/rage clicks cards for users with an SDK version below minimum requirements, let's use the banner instead.

The CTA takes them to the changelog for the feature
https://changelog.getsentry.com/announcements/user-frustration-signals-rage-and-dead-clicks-in-session-replay

### Screenshot
![Image](https://github.com/getsentry/sentry/assets/6508377/24d6c4c3-b231-486d-8b4d-0f0a72a564c4)

### Designs
https://www.figma.com/file/yS1d4Q0m8bziJ15esyAUXB/Exploration%3A-Index-v6?type=design&node-id=618%3A1046&mode=design&t=L26jOhlUwXxGDzn8-1

**Comment by jas-kas** [comment]
@Jesse-Box Looks good to me! Would it be OK to insert an SDK update callout in the small subheading text since we _know_ what SDK version they're on and we _know_ that's why they don't see rage and dead clicks today.  VS. having to open the changelog and read the pre-reqs listed

cc/ @ryan953

**Comment by Jesse-Box** [comment]
> @Jesse-Box Looks good to me! Would it be OK to insert an SDK update callout in the small subheading text since we _know_ what SDK version they're on and we _know_ that's why they don't see rage and dead clicks today. VS. having to open the changelog and read the pre-reqs listed
> 
> cc/ @ryan953

Something like this perhaps @jas-kas ?

<img width="581" alt="Screenshot 2023-09-06 at 18 40 23" src="https://github.com/getsentry/sentry/assets/6508377/c7039137-3b07-4418-b4bd-0f6a6d8c6d8d">

**Comment by Jesse-Box** [comment]
Marking this task as done @jas-kas @ryan953 

Figma
https://www.figma.com/file/yS1d4Q0m8bziJ15esyAUXB/Exploration%3A-Index-v6?type=design&node-id=618%3A1046&mode=design&t=L26jOhlUwXxGDzn8-1
