### ISSUE TITLE
Weekly Report sending multiple times for a single org

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#55141]
Weekly report emails have been reported to send multiple emails within the same day.  Sometimes these emails will be spaced out by hours.  

Expected outcome
- A user should only receive a single weekly report email per week per org they belong to.

Actual outcome
- Users have reported multiple weekly report emails for the same org for that week's report.
- Some weekly reports are being sent 3+ times per org to a user.
- Not all users get multiple emails for the same org for that week.

**Comment by damianKokot** [comment]
Hi,
Is there any update in why is this task closed? I have the same issue after upgrading sentry self hosted to version 23.8.0 causing 6+ weekly reports per week...

**Comment by azaslavsky** [comment]
This was fixed in mainline sentry, and will be included in the 23.9.0 release, due out next week.
