### ISSUE TITLE
Crons: Add project icon next to each monitor name

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#55160]
In the Crons timeline view, we should add the project icon next to the monitor name for easier identification like we do in the details page.

Example:

![Image](https://user-images.githubusercontent.com/1308394/262167870-69065844-0125-4623-a0a0-7e68ac614d5d.png)
![Image](https://user-images.githubusercontent.com/1308394/262167774-21d73be4-1a1b-4bba-9d72-975e67122a84.png)

**Comment by evanpurkhiser** [comment]
This was completed here https://github.com/getsentry/sentry/pull/65944
