### ISSUE TITLE
[Audit Log] Surface Project Key Change Details in Audit Log

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry#55187]
### Problem Statement

ProjectKey.change events in the audit log only show which key was changed. This is not very useful.

### Solution Brainstorm

We do surface what the new values are: 
```
rate_limit_count: 220 //number of events per window
rate_limit_window: 60 //window duration in seconds
```
We should show this so that the audit log can be used to infer changes over time.

### Product Area

Unknown

**Comment by scttcper** [comment]
The audit log leaves a lot to be desired when changing values. Adding to our backlog
