### ISSUE TITLE
DSN env variable name is replaced with actual DSN in onboarding flow

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/sentry#55180]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Create a new Symfony project

### Expected Result

- `config/packages/sentry.yaml` does not show the actual DSN
- as I understand it, `.env` should also be replaced with `.env.local` for Symfony projects, see https://symfony.com/doc/current/configuration.html#selecting-the-active-environment

### Actual Result

- the flow suggests to put the DSN in a file called `.env`, which seems to be the template for `.env.local` which is then used in a specific environment
- `config/packages/sentry.yaml` shows the actual DSN, which is later repeated in the .env file as well

![screencapture-sentry-sdks-sentry-io-projects-stats-scraper-getting-started-2023-08-23-10_50_43](https://github.com/getsentry/sentry/assets/7096858/87189ea2-4abb-40d4-9f02-74e9530dbbf6)

### Product Area

Projects - Project Creation

**Comment by ArthurKnaus** [comment]
Closed in https://github.com/getsentry/sentry/pull/55681
