### ISSUE TITLE
INC-477 Document and ticket highest risk typing errors in post process

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#55193]
Many files related to post-process are skipping type checks. Document the specific features/codepaths that are unchecked and high risk. https://github.com/getsentry/sentry/blob/b7810a9dca4b57afd2858903a6a9ec7ab50cdead/pyproject.toml#L732

**Comment by snigdhas** [comment]
Untyped files invoked from post process:
- `sentry.tasks.post_process`: processing snoozes, group owners, owner assignment, 
- `sentry.tasks.groupowner`, `sentry.tasks.commits`: suspect commits
- `sentry.rules.processor`: rule processing, alerts  
- `sentry.api.endpoints.organization_derive_code_mappings`: endpoint to derive code mappings from the UI 
- `sentry.tasks.servicehooks` 
- `sentry.tasks.sentry_apps`
-  post process for plugins

Other seemingly important files related to alerts and notifications areas:
- `sentry.tasks.digests`
- `sentry.mail.adapter`
- `sentry.mail.notifications`
- `sentry.notifications.notifications.rules`
- most of `sentry.rules`
- integration notifications (slack, msteams)
