### ISSUE TITLE
Dashboard showing data for all environments, no matter which one selected

### ISSUE THREAD

**Issue by realkosty** [getsentry/sentry#55191]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to customer dashboard (see linked Jira ticket for URL)
2. Look at "User Builds" widget
3. Note values of CRASH FREE RATE, UNIQUE USERS and TOTAL SESSIONS for release `4.3.7 (2)`
4. Change environment filter from "Production" to "All Environments"
5. Observe exact same values being displayed. <-- **THIS IS INCORRECT**
6. Click on `4.3.7 (2)` release which takes you to /releases page
7. Change time range to match Dashboard time range (14d)
8. Observe that THIS RELEASE column shows the same values as Dashboard does in Step [3] and [5].
9. Change environment filter from "All Environments" to "Production" 
10. Observe different values (what should've been shown in Step [5])

### Expected Result

in [5] we should see same values as in [10]

### Actual Result

instead in [5] we see value based on data from ALL environments, which is same as [3] and is incorrect.

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1915) by [Unito](https://www.unito.io)

**Comment by brentc** [comment]
Yes, this appears to be a bug. Looking into it to diagnose further.

**Comment by thinkocapo** [comment]
fixing this would be wonderful, because it'd allow React Native users to set an environment for each mobile platform type

environment: "production-" + Platform.OS

And then filter Crash Free Rates by Mobile Platform (environment) like they can do in Crashlytics out-of-the-box.

@brentc is there any update? We have a list of customers with this problem in React Native.

**Comment by narsaynorath** [comment]
hey @realkosty, just wanted to let you know this is merged and deployed now. Let me know if you have any issues but the environment filter should work with release health widgets

**Comment by realkosty** [comment]
@narsaynorath thank you Nar! I just tested and it works as expected so bringing the good news to our customer ☺️
Also "Entire Release Period" and vertical bars for Adopted/Created are awesome
