### ISSUE TITLE
Spike Protection Triggered emails link to settings page instead of something useful

### ISSUE THREAD

**Issue by willieowens** [getsentry/sentry#55200]
### Problem Statement

Emails for spike protection triggering have a button named "View More Details" which links to https://sentry.io/settings/audit-log/?utm_source=sentry&utm_campaign=spike_protection which 302's to https://sentry.io/settings/organization/?utm_source=sentry&utm_campaign=spike_protection.

The settings page it 302s to does not refer to Spike Protection in any way. 

### Solution Brainstorm

I believe it should either route to https://sentry.io/settings/spike-protection/ or what would be better than a settings page is the actual Spike information, so something like https://sentry.io/stats.

### Product Area

Settings - Spike Protection

**Comment by willieowens** [comment]
So I think the real issue is that https://sentry.io/settings/audit-log actually redirects you to https://{organizationSlug}.sentry.io/settings/organization, NOT https://{organizationSlug}.sentry.io/settings/audit-log.

However, I still think https://{organizationSlug}.sentry.io/stats (or the specific project's stats page) would be a better destination to link to. https://sentry.io/stats redirects you to https://{organizationSlug}.sentry.io/stats fine FWIW.

**Comment by Dhrumil-Sentry** [comment]
@willieowens Thanks a lot for this feedback, We'll dig more into this and keep the issue updated. cc @cathteng @leedongwei

**Comment by cathteng** [comment]
This PR has a fix for this https://github.com/getsentry/getsentry/pull/11498
