### ISSUE TITLE
Deploy notifications sent though setting is "OFF"

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#55206]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Turn off Deploys and My Own Activity notifications 
<img width="1435" alt="CleanShot 2023-08-24 at 09 54 27@2x" src="https://github.com/getsentry/sentry/assets/99350819/67b5a88f-20da-4eae-a8d1-c2fa4b58699a">
Observe Deploy notifications are still sent to users 

[Zendesk ticket](https://sentry.zendesk.com/agent/tickets/101413)

### Expected Result

No deploy notification sent

### Actual Result

Deploy notification sent

### Product Area

Unknown

### Link

https://sentry.io/settings/account/notifications/

**Comment by taylorthurlow** [comment]
Thanks for the response, feel free to ping me here or in the support email if you have any questions.

**Comment by scefali** [comment]
We are in the process of revamping our notification settings and this bug will go away. We'll have it wrapped up by the end of September.
