### ISSUE TITLE
Downloading raw Apple crash reports is missing critical contexts that appear in the web ui

### ISSUE THREAD

**Issue by idosun** [getsentry/sentry#55219]
### Environment

SaaS (https://sentry.io/)

Our purpose is to align as much as possible with Apple's raw crash report format. 

### Steps to Reproduce
Missing contexts:
- The binary image offsets + load addresses 
- CPU registers for the crashing thread

1. Go to any Apple crash error/issue 
3. Display the crash frames as “Raw stack trace” + “Unsymbolicated”
4. Click download
5. Observe that CPU registers for the crashing thread and image load addresses are missing from the bottom of the file, but present in the web UI

![image](https://github.com/getsentry/sentry/assets/6572704/9a52ad04-b8cd-46a4-ae45-d9111cec492a)

![image](https://github.com/getsentry/sentry-native/assets/6572704/51940f57-3f1c-428c-b489-8401f0386160)

### Expected Result

Downloaded crash report should contain the 
- Binary images load + offset addresses 
-  CPU registers for the crashing thread
At the bottom of the report (see [internal ticket](https://getsentry.atlassian.net/browse/ISSUE-1680) for example) 

### Actual Result

EOF right after the list of thread dumps

### Product Area

Issues

**Comment by malwilley** [comment]
@idosun a fix has just been deployed. Can you confirm that the download works as expected now?

**Comment by idosun** [comment]
Works as expected! Thank you @malwilley

**Comment by malwilley** [comment]
Thanks for the confirmation! 🥳
