### ISSUE TITLE
Gitlab integration, add repository programmatically using sentry API

### ISSUE THREAD

**Issue by fmiqbal** [getsentry/sentry#55231]
### Problem Statement

As per docs, I need to "add repository" in the gitlab integration page in organization settings to add more data about the release itself, so it should looks like this 
![image](https://github.com/getsentry/sentry/assets/8409391/668e08d1-af04-4046-90fa-7d0cbd78277a)

while when i am not adding the repository manually, it look like this
![image](https://github.com/getsentry/sentry/assets/8409391/f4d56b5d-5a83-409e-9d78-d7f206eceb45)

Meanwhile, the "add repository" setting is done manually (as far as i read the docs), this become an ops-overhead for us because we create teams, create project, assign member, and release programmatically using the API and sentry-cli. 

Any way to do this using API ? or maybe 

### Solution Brainstorm

I am thinking of the "add repository" to add "all" repository, instead of just one, or maybe just using prefix ? group ?, as I understand right now, the option on the install gitlab integration page is just for "listing/searching" not for actually adding the repository. the repository itself need to be added manually.

Or maybe just use the API to post to `/repos` with specified 
- `url` : which in ci cd pipeline we already have derived from CI_PROJECT_URL 
- `name` : which we also have derived from CI_PROJECT_PATH
- `provider` : which we can set static
- `integrationId` : which we also can set static

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
Hi @fmiqbal Thanks a lot for this feedback. Ideally when you install the GitLab integration and give Sentry access to your repos we should automatically link your repositories.

Having an API to link repositories also makes sense but the former option might be the cleanest solution.

I am adding this to our backlog and will keep this issue updated

**Comment by fmiqbal** [comment]
I also agree with that, but won't they make a bit of problem? considering when we are adding installation, it use the token provided, which in our case, can be a lot of project because the sentry has only concept of "single integration" for the gitlab (I think), so we are resorting to have single token to access all the project in our self hosted instance.

What are the purpose of having 2 step anyway ? as far as I am observed, it add something to the webhook, anything else? for some hundreds of project, "automatically linking all repositories" will mean all of that will have webhook right ?

how about implementing group webhook ? https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#group-webhooks, although its for premium offering, and we dont have it, so maybe just a brainstorm

**Comment by sentaur-athena** [comment]
I'm going to close this since the request is stale. We're always open to community contributions.
