### ISSUE TITLE
Not Able to Logged In

### ISSUE THREAD

**Issue by ankushqoala** [getsentry/sentry#55236]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Need to just logged in through Google Account

### Expected Result

Should Logged in Normally

### Actual Result

Error - Status Code -503 
Error Message - 
"Too many envelopes (event_buffer_size reached)"

### Product Area

Sign In

### Link

https://sentry.qi.qoala.app/auth/login/qoala/

### DSN

https://sentry.qi.qoala.app/auth/login/qoala/

**Comment by Dhrumil-Sentry** [comment]
@chadwhitacre The URL seems to be self hosted Sentry?

**Comment by Dhrumil-Sentry** [comment]
Asking the support team to create a Jira issue with details pertaining to org slug/member email

**Comment by JoshFerge** [comment]
closing due to no further activity
