### ISSUE TITLE
8.17: MultipleObjectsReturned in sentry.tasks.store.save_event get() returned more than one Environment -- it returned 13!

### ISSUE THREAD

**Issue by JeanFred** [getsentry/sentry#5524]
After upgrading from 8.16 to 8.17, I ran into 
```
MultipleObjectsReturned in sentry.tasks.store.save_event
get() returned more than one Environment -- it returned 13!
```

Sentry itself reports 5.8 millions such occurrences in 21 hours. This also happens on another Sentry instance we are running (319K events).

I cannot provide the stack trace because Sentry displays “There was an error loading data.” when loading the event.

- Sentry 8.17
- Running on-premise Docker-compose 

(This has a similar title as #1377).

**Comment by mattrobenolt** [comment]
It sounds like you failed or didn't run a migration that's needed to de-dupe the objects here. There are 2 migrations of importance, 0302 and 0321. Without these being run, this will definitely be a problem.

**Comment by JeanFred** [comment]
Right, that make sense. When upgrading from 8.16 to 8.17, I had to fake `0321_auto__add_unique` because it was failing with 
```
Running migrations for sentry:
 - Migrating forwards to 0326_auto__add_field_groupsnooze_count__add_field_groupsnooze_window__add_f.
 > sentry:0321_auto__add_unique_environment_organization_id_name
FATAL ERROR - The following SQL query failed: CREATE UNIQUE INDEX CONCURRENTLY sentry_environment_organization_id_6c9098a3d53d6a9a ON sentry_environment (organization_id, name)
```

Thanks for the answer − I’ll try sorting it out. :)

**Comment by mattrobenolt** [comment]
Oh, then you probably hit this issue: https://github.com/getsentry/sentry/issues/5502

There's a script included there to de-dupe. The de-duping happened in 0302, but apparently we failed to prevent all dupes from occurring beyond that, so adding the index fails. I'm not sure what we can do to fix retroactively, but the intent of adding the actual unique constraint is to prevent it from happening moving forward.

**Comment by JeanFred** [comment]
Oh right, I had missed #5502. That solved it − thanks !
