### ISSUE TITLE
CORS problem on sentry.io

### ISSUE THREAD

**Issue by kakulukia** [getsentry/sentry#5525]
XMLHttpRequest cannot load https://reload.getsentry.net/page/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://sentry.io' is therefore not allowed access.

Thats happens when imopening my project on https://sentry.io/org/project/

The second problem is:
raven.js:1060 GET https://sentry.io/api/0/internal/health/ 403 (FORBIDDEN)

**Comment by mattrobenolt** [comment]
Will fix. This shouldn't have any impact though.

**Comment by mattrobenolt** [comment]
Should be good now. :)

**Comment by kakulukia** [comment]
@mattrobenolt the first problem is fixed the second still exists tho

**Comment by mattrobenolt** [comment]
Oh, sorry, I didn't comment on that. That is working as intended and has been the same behavior for at least a year or so by now. It's harmless to you.
