### ISSUE TITLE
Measure how often the frame timestamps do not match replay starting timestamp

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#55277]
We currently inspect all replay frame data to find the oldest frame and use that to calculate the replay duration inside of replay details. Instead, we want to eventually use the starting timestamp on the replay record. As an intermediate step, let's measure how often the replay record's starting timestamp does not equal the oldest frame timestamp (we likely want a buffer, e.g. allow them to differ by up to an hour).

**Comment by ryan953** [comment]
Here are a pair of histograms that show how often the start/end timestamps are unexpectedly different:
https://app.amplitude.com/analytics/sentry/dashboard/zt9vqllj

**Comment by ryan953** [comment]
cc @billyvg lmk if the dashboards are solving the issue

**Comment by billyvg** [comment]
@ryan953 This does, thanks! -- one question, is there ever the case where started at time > db time?

**Comment by ryan953** [comment]
I don't see any. 

To check i filtered out `0` from the results (to skip fencepost problems) and set the range to be +/- one extra segment in the distribution:

<img width="563" alt="SCR-20230925-kzuo" src="https://github.com/getsentry/sentry/assets/187460/84479e4b-15ec-4ee1-83ce-9b516f3c3c96">
<img width="808" alt="SCR-20230925-kzsc" src="https://github.com/getsentry/sentry/assets/187460/86b7018b-d968-4765-bfdf-3f5629c9aceb">
