### ISSUE TITLE
Disable spike protection on enterprise-trial-start, enable spike protection on enterprise-trial-end

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry#55271]
### Problem Statement

Per @Dhrumil-Sentry , Spike Protection does not consider enterprise trials, currently Sentry employees managing the enterprise trial are asked to manually disable Spike Protection. It would be better if this didn't have to be managed manually and was taken care of automatically on trial start/end

### Solution Brainstorm

- Automatically disable spike protection when an enterprise trial starts
- Automatically re-enable spike protection when an enterprise trial ends

### Product Area

Settings - Spike Protection

**Comment by realkosty** [comment]
Looks like it's been addressed. 

> Spike Protection does not apply during trials as category quotas are unlimited for the duration of the trial. For example, new organizations on a trial will not be spike-protected until the trial is over even if projects have Spike Protection enabled.

https://docs.sentry.io/product/accounts/quotas/spike-protection/

Sounds like it will show as enabled in Settings but will not actually activate
