### ISSUE TITLE
User feedback doesn't include email in sentry UI

### ISSUE THREAD

**Issue by delamart** [getsentry/sentry#5531]
I'm using sentry hosted (sentry.io) and implemented the User Feedback system on my web app. It works great.

However I can't find the email provided in the form anywhere in the UI, I only see the Name and the Message.

I understand this feature is a work in progress, but could you just show the email ? That way I can get in touch with the user.

**Comment by dcramer** [comment]
Looks like there's a bug with our API responses. Will get a fix pushed out.
