### ISSUE TITLE
Selector info for dead click is inconsistent between breadcrumbs & DOM tab

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry#55326]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

https://sentry-test.sentry.io/replays/fe2c522954154bad9e6eea520f266234/?f_d_type=ui.slowClickDetected&query=&referrer=%2Freplays%2F&statsPeriod=14d&t_main=dom&yAxis=count%28%29

### Expected Result

Dead click in breadcrumbs list should show the correct selector, but shows a different/incorrect one?

### Actual Result

![image](https://github.com/getsentry/sentry/assets/2411343/3c9897ff-2c13-4e7a-9c3c-6732b5a2bd36)

Selector in breadcrumbs list is different, and seems to be incorrect (??)

### Product Area

Replays

### Link

https://sentry-test.sentry.io/replays/fe2c522954154bad9e6eea520f266234/?f_d_type=ui.slowClickDetected&query=&referrer=%2Freplays%2F&statsPeriod=14d&t_main=dom&yAxis=count%28%29

**Comment by michellewzhang** [comment]
closing as we no longer have the DOM tab
