### ISSUE TITLE
Design: Spring Boot Getting Started improvements

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#55325]

**Comment by Jesse-Box** [comment]
Design is ready for @ArthurKnaus 

`Option A` for now but in the future if we have more than 4 products in a given wizard, then `Option C`

Designs 👇 
https://www.figma.com/file/wROselpEmYKvGs38quXLbR/Exploration%3A-Wizard-Settings?type=design&node-id=56%3A903&mode=design&t=VG0mMI5mJ82TNyzk-1
