### ISSUE TITLE
Would like to extract information from the API when an issue has been merged into another one

### ISSUE THREAD

**Issue by mtoto17** [getsentry/sentry#55331]
### Problem Statement

We use the Sentry API to build our internal dashboards that developers consult on outstanding issues. When an issue gets merged into another one however, there is no way to capture this information and so the issue lives on on the dashboard, even though its not relevant to the team anymore. 

We would like to be able to extract information from the API when an issue is merged into another one, so we can exclude them from our internal dataset.

### Solution Brainstorm

Could be a new issue state I suppose, such as 'merged'. Or maybe a separate endpoint? I am not too sure.

### Product Area

APIs

**Comment by mtoto17** [comment]
@Dhrumil-Sentry yes we are using that endpoint indeed, additionally we also extract data from 
- https://docs.sentry.io/api/organizations/list-an-organizations-projects/,
- https://docs.sentry.io/api/teams/list-an-organizations-teams/,
- https://docs.sentry.io/api/organizations/list-an-organizations-users/,
- https://docs.sentry.io/api/events/list-a-projects-events/

**Comment by Dhrumil-Sentry** [comment]
@mtoto17 Thanks for this feedback, we'll add this to the backlog but we don't have any near-term plans to do this yet.

@brianthi @rachrwang - Worth considering if we can make "Merged" issues available in the issues API endpoint or as an issue webhook event

**Comment by MichaelSun48** [comment]
This seems to be similar to [this ticket](https://github.com/getsentry/sentry/issues/81352), which also asks for merged issues to be tracked in the Activity section. Going to close this out in favor of that one since it's newer and is more likely how we would resolve the root issue of not having enough visibility into Merged issues.
