### ISSUE TITLE
error: http error: generic error (403)

### ISSUE THREAD

**Issue by nenti** [getsentry/sentry#5541]
I'm using react-native-sentry and in the postbuild phase sentry returns.

```
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
error: http error: generic error (403)
:app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.
```

How can I generate more insights into this error?

**Comment by nenti** [comment]
React native link didn't setup my sentry.properies. So I manually added DSN which was missing. This should be added to documentation for android setup on react-native-sentry.

**Comment by juanmanuelarze** [comment]
can you bring more details plz, how you do that exactrly? @nenti

**Comment by petromoldovan** [comment]
@nenti how did you solve it? could you share it with the rest?

**Comment by egormerkushev** [comment]
@nenti please show list of options in your sentry.properies

**Comment by petromoldovan** [comment]
@juanmanuelarze @egormerkushev try this?
https://github.com/getsentry/react-native-sentry/issues/128

**Comment by egormerkushev** [comment]
@petromoldovan thank you! I found that defaults.url in my properties was wrong, I just commented this line and all was working fine!
