### ISSUE TITLE
No ‘Access-Control-Allow-Origin’ header is present on the requested resource

### ISSUE THREAD

**Issue by vopjie** [getsentry/sentry#5545]
- The version of Sentry :8.17
- installation method: python

response headers has no Access-Control-Allow-Origin:*

![image](https://user-images.githubusercontent.com/9351855/26916711-03277f9a-4c5e-11e7-9294-597311b4b1f8.png)

![image](https://user-images.githubusercontent.com/9351855/26916717-073ff440-4c5e-11e7-964d-28d0b09e61f7.png)

![image](https://user-images.githubusercontent.com/9351855/26916721-0b1c1828-4c5e-11e7-9eb4-0e6d4b770389.png)

**Comment by k9k** [comment]
@vopjie 
Hi, I'm struggling with the same issue, how did you finally resolve this?

**Comment by denyo** [comment]
I also saw this one today. Any hints?

**Comment by k9k** [comment]
@denyo 
try to add `USE_X_FORWARDED_HOST = True` to your Sentry config (`sentry.conf.py`)
and also add env variable `SENTRY_USE_SSL: 1` to `docker.compose.yml`

**Comment by denyo** [comment]
How to do this when using the hosted version of sentry?

**Comment by k9k** [comment]
Unfortunately I don't know, in my case we host Sentry on our machine. But you can check variable `USE_X_FORWARDED_HOST ` in settings in `/manage/status/environment/`. In my case it's set to True.

**Comment by dcramer** [comment]
@denyo this is per-project configuration on sentry.io. The settings above refer to our onpremise install and are already properly configured. You need to visit Project -> Settings -> General, and under Allowed Domains you can configure the properties.
