### ISSUE TITLE
[Performance Issue] Issue Details Page Can Freeze when Scrolling Past Replay for ~4s

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#55489]
See specific customer report and example [here](https://github.com/getsentry/team-replay/issues/158) in private repo.

**Comment by ryan953** [comment]
We don't need two tickets, https://github.com/getsentry/team-replay/issues/158 is the one.

**Comment by jas-kas** [comment]
@ryan953 I use two tickets because one is where I have customer info in a private repo, and the other is a public repo ticket that I can share with the customer to track our progress. So we need two tickets for that.
