### ISSUE TITLE
Github Integration not working

### ISSUE THREAD

**Issue by risingwolf21** [getsentry/sentry#55525]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open Sentry Issue
2. Issue Tracking > Track this issue in Jira
3. Setup Github
4. Add private repository to Sentry configuration
5. Go back to issue
6. Still no Create github issue button

### Expected Result

After setting up the github integration, I should be able to create an issue.

### Actual Result

![image](https://github.com/getsentry/sentry/assets/29673745/c431166e-c67a-4f63-be5d-89aeb8d0abb2)
![image](https://github.com/getsentry/sentry/assets/29673745/a8f058fb-6370-4208-8be7-2f2024cc6c87)

![image](https://github.com/getsentry/sentry/assets/29673745/3a41cdbe-f18f-4ae5-8075-e0e59126c77c)

### Product Area

Issues

**Comment by scttcper** [comment]
Did you try refreshing the page? We might need your orgslug or an open issue with support for more details

**Comment by risingwolf21** [comment]
Yeah I refreshed the page, but I did not work. I deleted the Github Installation in Sentry and tried it again, but without any changes.

**Comment by arag00rn** [comment]
Seems I'm having the same issue. Is it a confirmed bug ?

**Comment by Dhrumil-Sentry** [comment]
@scefali is this a known bug?

**Comment by risingwolf21** [comment]
This was not a bug in my case.
I just could not find out, that you need more than the Free Plan to use Integrations.
