### ISSUE TITLE
Dynamic sampling tasks produce a lot of issues in sentry internal project

### ISSUE THREAD

**Issue by ibor1senko** [getsentry/sentry#55544]
### Problem Statement

I found that [dynamic_sampling_task_with_context](https://github.com/getsentry/sentry/blob/2ad7aac21f390c17ff66d97a25815cfba4272f39/src/sentry/dynamic_sampling/tasks/utils.py#L36) decorator capture message each time when task is run successfully.
<img width="1251" alt="image" src="https://github.com/getsentry/sentry/assets/62235361/7050ddf1-8fec-4b8e-a0df-bfe80fc0cadd">

Version: sentry 23.8.0 522613d

### Solution Brainstorm

remove capture_message in else [section](https://github.com/getsentry/sentry/blob/2ad7aac21f390c17ff66d97a25815cfba4272f39/src/sentry/dynamic_sampling/tasks/utils.py#L36).

### Product Area

Crons

**Comment by vechorko** [comment]
Hi @ibor1senko , I've got the same issue as your describe, do you have some temporary solution for this case?

**Comment by ibor1senko** [comment]
Hi @vechorko, unfortunately no

**Comment by vechorko** [comment]
Hope that sentry team help us to find a quick solution to solve it

**Comment by ceorourke** [comment]
@getsentry/telemetry-experience is this in your wheelhouse?

**Comment by neo502721** [comment]
Same here. Any update?

**Comment by hubertdeng123** [comment]
@iambriccardo I see that you added the [line](https://github.com/getsentry/sentry/blob/2ad7aac21f390c17ff66d97a25815cfba4272f39/src/sentry/dynamic_sampling/tasks/utils.py#L36). Do you have more context on this?

**Comment by kamenskiyyyy** [comment]
Same here. Any update?

**Comment by azaslavsky** [comment]
@iambriccardo can you take a look at this?

**Comment by mikaelengstrom** [comment]
Im also experiencing this

**Comment by malwilley** [comment]
@iambriccardo do you know why this is happening when it shouldn't, or if we can just remove that `capture_message` call?

**Comment by iambriccardo** [comment]
Hi all! This is expected behavior since Sentry is using itself to communicate the timings of our background cron jobs powering dynamic sampling. It was added an an extra observability measure to make sure cron jobs do not run out of time.

If you feel like this might be too noisy, I will be more than happy to remove it and emit logs instead.

Let me know!

**Comment by iambriccardo** [comment]
I have opened a PR to remove it: https://github.com/getsentry/sentry/issues/55544

Sorry if this caused any inconvenience and for the late reply!

I will deploy it tomorrow morning after approval.

**Comment by iambriccardo** [comment]
The fix is now deployed for all sentry saas customers and it's going to be available in the next release for self-hosted.
