### ISSUE TITLE
Race condition when creating `TagValue` records can lead to tags being recorded as having 0 unique values.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#5554]
The [`TagValue` buffer flush signal receiver](https://github.com/getsentry/sentry/blob/412c54b25f9a32416df84a248d8df58fc01fccf3/src/sentry/receivers/core.py#L143-L158) is used to update the `TagKey.values_seen` field. (This buffer itself is interacted with as [part of `Group.add_tags`](https://github.com/getsentry/sentry/blob/412c54b25f9a32416df84a248d8df58fc01fccf3/src/sentry/models/group.py#L125-L134).)

However, the `index_event_tags` task also [creates a `TagValue` record if none already exists](https://github.com/getsentry/sentry/blob/412c54b25f9a32416df84a248d8df58fc01fccf3/src/sentry/tasks/post_process.py#L191-L195) as part of it's implementation.

It looks like in many cases, the `index_event_tags` method is executed prior to the buffer flush, and the body of the `record_project_tag_count` buffer flush signal receiver is never executed, so the `values_seen` field is never updated.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

Is this fixed by #5669 @tkaemming?
