### ISSUE TITLE
Clarify documentation: mail.backend defaults to 'dummy'

### ISSUE THREAD

**Issue by chrisblech** [getsentry/sentry#5557]
Just tried several hours to get mail working with my own smtp-host (latest docker version, without smtp-docker-container), finally I realized that it's important to enable "mail.backend='smtp'" in config.yml.

All settings in config.yml are commented out, and listed with their default value - so I was thinking 'smtp' is also default, and didn't see any sense in removing the hash sign.
Even in Sentry-UI, I could see all SMTP-configuration, without any note that it's disabled because of "mail.backend=dummy" setting.

What can you improve:
- change default config.yml to:
`# mail.backend='dummy'  # uncomment and change to 'smtp' to enable external smtp settings`
- add a note to UI: `/manage/status/mail` when mail.backend=dummy is set

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

PS- we've already addressed this issue. Thanks for the report and sorry for the very late response :)
