### ISSUE TITLE
Consolidate project platforms between frontend and backend

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#55626]
These two files should be kept in sync (at least according to comments).
https://github.com/getsentry/sentry/blob/master/src/sentry/models/project.py
and
https://github.com/getsentry/sentry/blob/master/static/app/data/platformCategories.tsx

I've noticed the `go-echo` was missing in one of them.
The goal of this ticket is to find why we need both and consolidate them.

**Comment by ArthurKnaus** [comment]
There are two pairs of files that need to be kept in sync.

[src/sentry/models/project.py](https://github.com/getsentry/sentry/blob/2cba1aba2870ea3d558a6a62b919dd08d3177907/src/sentry/models/project.py) & [static/app/data/platforms.tsx](https://github.com/getsentry/sentry/blob/79e609ed8f59854b80f250718d46e0eb7db1700e/static/app/data/platforms.tsx):
**The FE** file defines all platforms that are available for project creation.
**The BE** definitions are used for validation upon project creation. The project creation fails if a platform is passed, that is not defined in this file.

[src/sentry/utils/platform_categories.py](https://github.com/getsentry/sentry/blob/cd955ea612a79eaeabc59ff2b6180cdeb6eabb89/src/sentry/utils/platform_categories.py) & [static/app/data/platformCategories.tsx](https://github.com/getsentry/sentry/blob/f9e62f5767804f9844f92348cb4b8cb4f22d8195/static/app/data/platformCategories.tsx):
**The FE** file defines the different categories that can be filtered for in the tabs of the project creation. Additionally it has also definitions for the feature support of platforms (e.g. `const profiling: string[] = [...]`). In here the type PlatformKey is defined as the Union of all platform categories:
```ts
export type PlatformKey =
  | (typeof popularPlatformCategories)[number]
  | (typeof frontend)[number]
  | (typeof mobile)[number]
  | (typeof backend)[number]
  | (typeof desktop)[number]
  | (typeof tracing)[number]
  | (typeof serverless)[number]
  | 'other';
```

The BE file does only include some of those definitions and only a few of those are used in `getsentry` for analytics purposes. Unused definitions: `FILTER_ALIAS, RELEASE_HEALTH, WITHOUT_PERFORMANCE_SUPPORT, WITH_PERFORMANCE_ONBOARDING, PERFORMANCE, TRACING, SOURCE_MAPS`. Those were added 13 months ago when the file was created. The PR includes a discussion about the usefulness of mirroring all definitions vs only those that are needed in the BE: https://github.com/getsentry/sentry/pull/37894

Proposed next steps: 
1. Consolidate the content of the files without adding any new unused categories. (in this issue)
2. Renew the discussion about the usefulness of adding unused definitions to the BE code (Who owns the code?). As the current attempt to keep the whole file in sync failed, I would propose to keep only the single definitions in sync with an comment above every affected definition.
3. The type `PlatformKey` should be calculated from the platform definitions in `platforms.tsx`. We already had problems of platforms not being in categories and therefore not being included in the type.
