### ISSUE TITLE
Ability to link to an exact event in an issue

### ISSUE THREAD

**Issue by sentryadam0000345** [getsentry/sentry#55620]
### Problem Statement

Currently, it’s a bit painful to drill down “All Events” section under each issue, sort by environment/look up the timestamp and then access the specific event page triggered the issue.  Having the ability to prevent this would be great.

### Solution Brainstorm

As a potential workaround is - you can specify the alert to be triggered if it has certain tags and etc. This can help because when the issue is specified, it will be triggered when the event occurs which will allow you to access the event a lot quicker.

Having a more direct link would be great.

### Product Area

Alerts

**Comment by ceorourke** [comment]
Hi @sentryadam0000345 what are you trying to do? I don't really understand what the problem is.

**Comment by ceorourke** [comment]
Closing as we haven't heard back in over a year - feel free to reopen if this is still relevant.
