### ISSUE TITLE
Incorrect permissions on bot invite

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [getsentry/sentry#55631]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Invite the bot https://YOURORGNAME.sentry.io/settings/integrations/discord/
2. It doesn't request the `Embed Links` permission which is required

### Expected Result

It should invite the bot with both the `Send Messages` and `Embed Links` permissions.

The reason why the bot needs this permission is because it uses embeds for issues and not regular messages, so it requires the `Embed Links` permission and if not given, the notification will fail to send to your Discord channel.

### Actual Result

It only invites the bot with the `Send Messages` permission.

### Product Area

Settings - Integrations

### Link

https://wdh.sentry.io/settings/integrations/discord/

**Comment by 17hogeju** [comment]
@WilliamDavidHarrison When you go to Server Settings > Integrations > Bots and Apps > Sentry > Manage, I'm curious to know what the bot permissions are listed. Does it look like this? 

![Image](https://github.com/getsentry/sentry/assets/22582037/bba0bc49-9da5-4ae6-982f-104cd06971be)

**Comment by WilliamDavidHarrison** [comment]
I see this:
![image](https://github.com/getsentry/sentry/assets/87287585/37e97692-f082-46b3-b2ad-90a7b380ab19)

But this is because the @\everyone role in my Discord gives most of those permissions. Whereas if you just had a Discord server where the @\everyone role had no permissions at all and just invited the bot, it would only have the Send Messages permission and not the Embed Links permission.
