### ISSUE TITLE
Add per-project option for which end of chained stacktrace is the culprit

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry#5565]
Right now [it's hardcoded to use](https://github.com/getsentry/sentry/blob/7f20e69046f4c52713956b9871068beacd55f3ef/src/sentry/event_manager.py#L177) `stacktraces[-1]` but some projects may prefer `stacktraces[0]` as the culprit. The culprit is often used to construct the message that is used in the UI and so is extra important to users.

`stacktraces[0]`: the original exception, could be the culprit for obvious reasons.
`stacktraces[-1]`: the "last" exception wrapper, often used when exceptions are re-thrown with extra information or a better message, so an equally valid option depending on the project.

This came up here: https://github.com/getsentry/sentry-java/issues/412

**Comment by bretthoerner** [comment]
Worth nothing this was fixed (for that user) for now by setting the oldest frame as the culprit using normal SDK functionality.

**Comment by dcramer** [comment]
This seems like low hanging fruit. I think we should explore it more, and get in a configuration option for it. It might make sense to also change the default in some languages, but we can start by just allowing people to choose the best behavior.

**Comment by jeremyhaile** [comment]
This is affecting almost every exception we're receiving from JRuby.

**Comment by bretthoerner** [comment]
There are two issues here:

1. People for whom grouping is fine, but they want the culprit to be the "inner-most" exception rather than the "outer-most" exception (our default).
2. People who only to ignore all but one exception (the first or last) in a chain of exceptions for grouping.

@jeremyhaile does 2 describe your issue/request correctly? I want to make sure I/we cover all the proper options that are needed in project settings.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
