### ISSUE TITLE
iOS issues with identical stacktraces and different messages are not grouped together

### ISSUE THREAD

**Issue by edenman** [getsentry/sentry#5566]
sentry-cocoa 3.0.1
https://sentry.io/recharge/consumer-ios/issues/294495639/
https://sentry.io/recharge/consumer-ios/issues/294512648/

I thought this was supposed to be fixed by @mitsuhiko's PR #5246 but it's apparently not.

**Comment by mitsuhiko** [comment]
This is because in that case multiple threads are recorded and we do not perform grouping there.

We might use the crashed information on the thread to expand it but I do not really like that the SDK logs *all* threads in that case in the first place.

@HazAT what about we just report the calling thread for log messages? I vastly prefer this. That is a lot of clutter right now in those events.

**Comment by edenman** [comment]
(i would be totally fine with only sending up the current thread's stacktrace on nonfatal events)

**Comment by HazAT** [comment]
@edenman I guess you are using `snapshotStacktrace` right?
Because this is actually set that it should log only the current thread 
`logAllThreads:NO`
will check why this is not working.

**Comment by edenman** [comment]
yup, this is how I'm invoking it:
```
func LogNonFatal(_ message: String) {
	let sentry: Client = Client.shared!
	let isMainThead = Thread.isMainThread
	sentry.snapshotStacktrace {
		let event = Event(level: .error)
		event.message = message
		if event.extra == nil {
			event.extra = [:]
		}
		event.extra!["is-main-thread"] = isMainThead
		sentry.send(event: event)
	}
}
```

**Comment by HazAT** [comment]
I've looked into it now in detail, it's not about the stacktrace they are fine, its because you are logging the user ID in the message. This is the reason why it's not grouped together.

**Comment by mitsuhiko** [comment]
It should purely group on the stacktrace though. That was the chane i made
but it only does that when a single thread is logged.

**Comment by HazAT** [comment]
I've created an issue in `sentry-cocoa` since this isn't a problem with sentry itself https://github.com/getsentry/sentry-cocoa/issues/180

**Comment by HazAT** [comment]
Hey, this has been fixed in the latest release https://github.com/getsentry/sentry-cocoa/releases/tag/3.0.11
