### ISSUE TITLE
is there any way to limit weekly project overview email

### ISSUE THREAD

**Issue by Chengshihao1018** [getsentry/sentry#55678]
### Problem Statement

project member will get project overview email every week, the email looks like below 
![image](https://github.com/getsentry/sentry/assets/31720199/5d48cb73-81c4-46aa-8119-082aeb23f0ba)

we use smtp sever to send email,but it limits the maximum number of times that can be sent per minute.With the increase of access projects it is easily to reach the limit.

### Solution Brainstorm

if it is a way to limit weekly project overview email, not just send in the same time?

### Product Area

Help

**Comment by hubertdeng123** [comment]
Are you self-hosting Sentry? Reason I ask is that this doesn't seem to be an issue for SaaS.

**Comment by Chengshihao1018** [comment]
> Are you self-hosting Sentry? Reason I ask is that this doesn't seem to be an issue for SaaS.

yes,we use self-hosting Sentry

**Comment by Chengshihao1018** [comment]
200 emails per minute.
