### ISSUE TITLE
Add SDK name to first_event_for_project.sent event

### ISSUE THREAD

**Issue by ArthurKnaus** [getsentry/sentry#55684]
Add SDK name to `first_event_for_project.sent` event so we can track which SDK are used by new projects.

This will help us decide which platforms and SDK we should further support / display in out onboarding docs.

**Comment by smeubank** [comment]
we can chat with Ale as well. I'd be interested if there was a way to standardize the events and tags we see in amplitude. In the following 2 for example are we adding the same tags in the same way? Meaning can we reliably track funnels

https://app.amplitude.com/analytics/sentry/dashboard/n4m5set

https://app.amplitude.com/analytics/sentry/dashboard/x2afqrg

**Comment by smeubank** [comment]
more concretely, would like to be able to rely on this dashboard 😅 

https://app.amplitude.com/analytics/sentry/chart/xatpzu54

**Comment by smeubank** [comment]
<img width="683" alt="image" src="https://github.com/getsentry/sentry/assets/47563310/ad633f1b-e7c9-4c32-bb21-c685b50b4a2b">

this event seems to actually be the correct one to be used for analysis around funnels during project creation, however it does not have a platform tag

this one from growth [is being used](https://app.amplitude.com/analytics/sentry/chart/gdr6qgqg?linkingDashboardId=x2afqrg) but it is for the wrong purpose it is from a different entry point not generically creating a new project via the UI

<img width="753" alt="image" src="https://github.com/getsentry/sentry/assets/47563310/84c8bdae-2b56-49e8-9f43-89e3a0bb6641">
