### ISSUE TITLE
Requesting an alert that can handle a conditional rule

### ISSUE THREAD

**Issue by kennethpgreen** [getsentry/sentry#55704]
### Problem Statement

I essentially want to alert if the tag is there and it's true OR in occasions where the tag is just not there. I confirmed with the Sentry team that there's not currently a way to do this.

### Product Area

Alerts

**Comment by ceorourke** [comment]
Hi @kennethpgreen is this not what you're looking for?

<img width="587" alt="Screenshot 2023-09-06 at 12 20 27 PM" src="https://github.com/getsentry/sentry/assets/29959063/3c04a60e-432d-439a-a105-82dd3977968e">
