### ISSUE TITLE
Dynamic sampling tasks produce a lot of issues in sentry internal project 

### ISSUE THREAD

**Issue by ibor1senko** [getsentry/sentry#55718]
### Problem Statement

I found that [dynamic_sampling_task_with_context](https://github.com/getsentry/sentry/blob/2ad7aac21f390c17ff66d97a25815cfba4272f39/src/sentry/dynamic_sampling/tasks/utils.py#L36) decorator capture message each time when task is run successfully.
<img width="1240" alt="image" src="https://github.com/getsentry/self-hosted/assets/62235361/d57f9dcc-3fc8-4966-8f8c-d9620a686909">

### Solution Brainstorm

remove capture_message in else [section](https://github.com/getsentry/sentry/blob/2ad7aac21f390c17ff66d97a25815cfba4272f39/src/sentry/dynamic_sampling/tasks/utils.py#L36).

**Comment by hubertdeng123** [comment]
actually I see https://github.com/getsentry/sentry/issues/55718

Will close as duplicate.
