### ISSUE TITLE
Disabling Deploy Based Notifications Still Results in Slack notifications on the Sentry App on Slack

### ISSUE THREAD

**Issue by Prithvirajkumar** [getsentry/sentry#55722]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Navigate to User Settings--> Notifications 

Select Off on Deploys.

If you have set up the Slack integration, you will continue to receive to Deploy based notifications on the Sentry App within the Slack instance.

The workaround here is to Select On on Deploys and disable Alerts on an organization level.

### Expected Result

Disabling Deploy based notifications should not trigger Deploy based notifications on the Sentry App on Slack.

### Actual Result

Disabling Deploy based notifications will still trigger Deploy based notifications on the Sentry App on Slack.

### Product Area

Settings

### Link

https://sentry.io/settings/account/notifications/

**Comment by lobsterkatie** [comment]
@scefali Is this something which will get fixed by the upcoming changes to notification settings?

**Comment by scefali** [comment]
@lobsterkatie @Prithvirajkumar Yes, the new notification changes will solve this and they are now enabled.

**Comment by ceorourke** [comment]
Closing as there have been no comments in over a year and we expect this to be resolved.
