### ISSUE TITLE
Issue upgrading to newest version of sentry

### ISSUE THREAD

**Issue by keithslater** [getsentry/sentry#5573]
After a successful pip install --upgrade sentry

I'm getting this

sentry --config ~/.sentry/sentry.conf.py upgrade

Traceback (most recent call last):
  File "/var/www/sentry/bin/sentry", line 11, in <module>
    sys.exit(main())
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/runner/__init__.py", line 160, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/var/www/sentry/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/var/www/sentry/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/var/www/sentry/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/www/sentry/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/www/sentry/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/var/www/sentry/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/runner/decorators.py", line 35, in inner
    configure()
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/runner/__init__.py", line 123, in configure
    configure(ctx, py, yaml, skip_service_validation)
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/runner/settings.py", line 153, in configure
    }, skip_service_validation=skip_service_validation)
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/runner/initializer.py", line 248, in initialize_app
    apply_legacy_settings(settings)
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/runner/initializer.py", line 437, in apply_legacy_settings
    url_prefix = options.get('system.url-prefix', silent=True)
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/options/manager.py", line 151, in get
    result = self.store.get(opt, silent=silent)
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/options/store.py", line 77, in get
    result = self.get_store(key, silent=silent)
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/options/store.py", line 169, in get_store
    except self.model.DoesNotExist:
  File "/var/www/sentry/lib/python2.7/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.func.__name__] = self.func(instance)
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/options/store.py", line 63, in model
    from sentry.models.option import Option
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/models/__init__.py", line 14, in <module>
    import_submodules(globals(), __name__, __path__)
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/utils/imports.py", line 51, in import_submodules
    module = __import__(module_name, globals(), locals(), ['__name__'])
  File "/var/www/sentry/lib/python2.7/site-packages/sentry/models/accessgroup.py", line 14, in <module>
    from sentry.constants import MEMBER_TYPES, MEMBER_USER
ImportError: cannot import name MEMBER_TYPES

**Comment by keithslater** [comment]
Output from pip freeze

pip freeze
amqp==1.4.9
anyjson==0.3.3
asn1crypto==0.22.0
BeautifulSoup==3.2.1
billiard==3.3.0.23
boto3==1.4.4
botocore==1.5.68
celery==3.1.18
cffi==1.10.0
click==6.7
contextlib2==0.5.5
cryptography==1.9
cssselect==1.0.1
cssutils==0.9.10
Django==1.6.11
django-bitfield==1.7.1
django-celery==3.1.17
django-crispy-forms==1.4.0
django-debug-toolbar==1.3.2
django-jsonfield==0.9.13
django-paging==0.2.5
django-picklefield==0.3.2
django-recaptcha==1.0.5
django-social-auth==0.7.28
django-statsd-mozilla==0.3.16
django-sudo==2.1.0
django-templatetag-sugar==1.0
djangorestframework==2.4.8
docutils==0.13.1
email-reply-parser==0.2.0
enum34==1.1.6
exam==0.10.6
funcsigs==0.4
futures==3.1.1
gunicorn==19.4.5
hiredis==0.1.6
honcho==0.7.1
httplib2==0.10.3
idna==2.5
ipaddr==2.1.11
ipaddress==1.0.18
jmespath==0.9.3
kombu==3.0.35
libsourcemap==0.5.0
logan==0.7.1
loremipsum==1.0.5
lxml==3.8.0
Markdown==2.6.5
mmh3==2.3.1
mock==1.0.1
ndg-httpsclient==0.4.0
nydus==0.11.0
oauth2==1.9.0.post1
oauthlib==2.0.2
olefile==0.44
pbr==1.8.1
percy==0.4.5
petname==2.0
Pillow==3.2.0
progressbar==2.3
progressbar2==3.10.1
psycopg2==2.6.2
py==1.4.34
pyasn1==0.1.9
pycparser==2.17
Pygments==2.1.3
PyJWT==1.5.0
pyOpenSSL==17.0.0
pytest==2.8.7
pytest-django==2.9.1
pytest-html==1.9.0
python-dateutil==2.6.0
python-memcached==1.58
python-openid==2.2.5
python-u2flib-server==4.0.1
python-utils==2.1.0
pytz==2017.2
PyYAML==3.11
qrcode==5.3
raven==5.33.0
rb==1.6
redis==2.10.5
requests==2.12.5
requests-oauthlib==0.8.0
s3transfer==0.1.10
selenium==3.0.0b3
sentry==8.17.0
sentry-hipchat==0.6.0
setproctitle==1.1.10
simplejson==3.8.2
six==1.10.0
South==1.0.1
sqlparse==0.2.3
statsd==3.1
structlog==16.1.0
symsynd==3.2.0
toronado==0.0.11
ua-parser==0.7.3
urllib3==1.16
uWSGI==2.0.15

**Comment by dcramer** [comment]
You have cached Python files:

```
find -name *.pyc -delete
```

**Comment by keithslater** [comment]
I tried that but I'm getting the same error.

**Comment by dcramer** [comment]
All i can tell you is that file no longer exists

**Comment by keithslater** [comment]
Are you referring to accessgroup.py? Should I just delete it? That and alert.py seems to not have been updated or deleted.

models]# ls -la
total 464
drwxr-xr-x  2 root root  4096 Jun 15 10:53 .
drwxr-xr-x 54 root root  4096 Jun 15 10:52 ..
-rw-r--r--  1 root root  1517 Dec  9  2015 accessgroup.py
-rw-r--r--  1 root root  3661 Jun 15 09:52 activity.py
-rw-r--r--  1 root root  3434 Dec  9  2015 alert.py
-rw-r--r--  1 root root  2829 Jun 15 09:52 apiapplication.py
-rw-r--r--  1 root root  1921 Jun 15 09:52 apiauthorization.py
-rw-r--r--  1 root root  2209 Jun 15 09:52 apigrant.py
-rw-r--r--  1 root root  3105 Jun 15 09:52 apikey.py
-rw-r--r--  1 root root  3290 Jun 15 09:52 apitoken.py
-rw-r--r--  1 root root  9894 Jun 15 09:52 auditlogentry.py
-rw-r--r--  1 root root 20340 Jun 15 09:52 authenticator.py
-rw-r--r--  1 root root  1773 Jun 15 09:52 authidentity.py
-rw-r--r--  1 root root  1607 Jun 15 09:52 authprovider.py
-rw-r--r--  1 root root  2950 Jun 15 09:52 avatar.py
-rw-r--r--  1 root root  1442 Jun 15 09:52 broadcast.py
-rw-r--r--  1 root root   997 Jun 15 09:52 commitauthor.py
-rw-r--r--  1 root root   758 Jun 15 09:52 commitfilechange.py
-rw-r--r--  1 root root  2230 Jun 15 09:52 commit.py
-rw-r--r--  1 root root  3886 Jun 15 09:52 counter.py
-rw-r--r--  1 root root  3316 Jun 15 09:52 deploy.py
-rw-r--r--  1 root root   835 Jun 15 09:52 distribution.py
-rw-r--r--  1 root root 18688 Jun 15 09:52 dsymfile.py
-rw-r--r--  1 root root  2249 Jun 15 09:52 environment.py
-rw-r--r--  1 root root  5144 Jun 15 09:52 eventerror.py
-rw-r--r--  1 root root  1757 Jun 15 09:52 eventmapping.py
-rw-r--r--  1 root root  9852 Jun 15 09:52 event.py
-rw-r--r--  1 root root   994 Jun 15 09:52 eventtag.py
-rw-r--r--  1 root root  4093 Jun 15 09:52 eventuser.py
-rw-r--r--  1 root root  8337 Jun 15 09:52 file.py
-rw-r--r--  1 root root  2870 Jun 15 09:52 groupassignee.py
-rw-r--r--  1 root root  1249 Jun 15 09:52 groupbookmark.py
-rw-r--r--  1 root root   728 Jun 15 09:52 groupcommitresolution.py
-rw-r--r--  1 root root  1244 Jun 15 09:52 groupemailthread.py
-rw-r--r--  1 root root  1805 Jun 15 09:52 grouphash.py
-rw-r--r--  1 root root  3695 Jun 15 09:52 groupmeta.py
-rw-r--r--  1 root root 15368 Jun 15 09:52 group.py
-rw-r--r--  1 root root   562 Jun 15 09:52 groupredirect.py
-rw-r--r--  1 root root  2784 Jun 15 09:52 grouprelease.py
-rw-r--r--  1 root root  1419 Jun 15 09:52 groupresolution.py
-rw-r--r--  1 root root   958 Jun 15 09:52 grouprulestatus.py
-rw-r--r--  1 root root   928 Jun 15 09:52 groupseen.py
-rw-r--r--  1 root root  3235 Jun 15 09:52 groupsnooze.py
-rw-r--r--  1 root root  5236 Jun 15 09:52 groupsubscription.py
-rw-r--r--  1 root root  1040 Jun 15 09:52 grouptagkey.py
-rw-r--r--  1 root root  3618 Jun 15 09:52 grouptagvalue.py
-rw-r--r--  1 root root  1179 Dec  9  2015 helppage.py
-rw-r--r--  1 root root   505 Jun 15 09:52 __init__.py
-rw-r--r--  1 root root  2290 Jun 15 09:52 lostpasswordhash.py
-rw-r--r--  1 root root   972 Jun 15 09:52 option.py
-rw-r--r--  1 root root  3016 Jun 15 09:52 organizationaccessrequest.py
-rw-r--r--  1 root root   822 Jun 15 09:52 organizationavatar.py
-rw-r--r--  1 root root  7034 Jun 15 09:52 organizationmember.py
-rw-r--r--  1 root root  4584 Jun 15 09:52 organizationonboardingtask.py
-rw-r--r--  1 root root  4322 Jun 15 09:52 organizationoption.py
-rw-r--r--  1 root root 10650 Jun 15 09:52 organization.py
-rw-r--r--  1 root root  4314 Jun 15 09:52 processingissue.py
-rw-r--r--  1 root root  1006 Jun 15 09:52 projectbookmark.py
-rw-r--r--  1 root root  5820 Jun 15 09:52 projectkey.py
-rw-r--r--  1 root root  3941 Jun 15 09:52 projectoption.py
-rw-r--r--  1 root root   710 Jun 15 09:52 projectplatform.py
-rw-r--r--  1 root root 10877 Jun 15 09:52 project.py
-rw-r--r--  1 root root   944 Jun 15 09:52 rawevent.py
-rw-r--r--  1 root root   746 Jun 15 09:52 releasecommit.py
-rw-r--r--  1 root root  2540 Jun 15 09:52 releaseenvironment.py
-rw-r--r--  1 root root  2034 Jun 15 09:52 releasefile.py
-rw-r--r--  1 root root   672 Jun 15 09:52 releaseheadcommit.py
-rw-r--r--  1 root root 14655 Jun 15 09:52 release.py
-rw-r--r--  1 root root  1582 Jun 15 09:52 repository.py
-rw-r--r--  1 root root   806 Jun 15 09:52 reprocessingreport.py
-rw-r--r--  1 root root  2318 Jun 15 09:52 rule.py
-rw-r--r--  1 root root  1189 Jun 15 09:52 savedsearch.py
-rw-r--r--  1 root root  1930 Jun 15 09:52 scheduledeletion.py
-rw-r--r--  1 root root  3050 Jun 15 09:52 tagkey.py
-rw-r--r--  1 root root  2754 Jun 15 09:52 tagvalue.py
-rw-r--r--  1 root root  8108 Jun 15 09:52 team.py
-rw-r--r--  1 root root   848 Jun 15 09:52 useravatar.py
-rw-r--r--  1 root root  1650 Jun 15 09:52 useremail.py
-rw-r--r--  1 root root  5544 Jun 15 09:52 useroption.py
-rw-r--r--  1 root root  8942 Jun 15 09:52 user.py
-rw-r--r--  1 root root  1095 Jun 15 09:52 userreport.py

**Comment by keithslater** [comment]
I was able to fix it by manually removing the files. There were also some .py files in api/serializers that had the same problem.
