### ISSUE TITLE
Profiling does not show Application frames 

### ISSUE THREAD

**Issue by mwenko** [getsentry/sentry#55758]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

I'm using NodeJS with the NestJS (which uses Express under the hood) framework. I configured Sentry like:

```
import * as Sentry from "@sentry/node";
import { ProfilingIntegration } from "@sentry/profiling-node";

integrations: [
            // enable HTTP calls tracing
            new Sentry.Integrations.Http({ tracing: true }),
            new Sentry.Integrations.Express({
                app: app.getHttpServer(),
            }),
            new ProfilingIntegration(),
            new Sentry.Integrations.Mongo({
                useMongoose: true,
            }),
        ]
```

### Expected Result

When using the profiling tab and selecting "Application frames", I would expect to see my application methods/frames to show up. Like the calls to the `services` and the calls to the `repositories`. (a call like `getCommuteStatistics()` for the service should show up instead of `emit()`)

### Actual Result

![image](https://github.com/getsentry/sentry/assets/22257587/c6c535a0-93dd-454c-97f4-b24c53c0e7f4)

The profiling tab does not show any application frames that I would expect. It shows methods like `emit()` which are very low level and definitely not part of our own application-code.

The application specific code seems missing here. 

### Product Area

Profiling

### Version

23.6.2

**Comment by samuelhwilliams** [comment]
I have just given profling a shot as well, using the Python package (`sentry-sdk[celery,flask,sqlalchemy]==1.21.1`) and I'm also not seeing any application frames - just system ones 🤔 Not sure if I'm misunderstanding or misreading something

<img width="1504" alt="image" src="https://github.com/getsentry/sentry/assets/2920760/b6fd5e05-77ac-4406-ad52-10af53818036">

**Comment by indragiek** [comment]
@mwenko @samuelhwilliams Thank you for the reports! I've triaged this to the owners of profiling on those SDKs (@JonasBa for Node.js and @Zylphrex for Python). We'll investigate and get back to you soon.

**Comment by samuelhwilliams** [comment]
oh :( ok, thanks for letting me know!

**Comment by Zylphrex** [comment]
You can follow https://github.com/getsentry/sentry-python/issues/1949 for updates when I do find a good solution for this.

**Comment by JonasBa** [comment]
@mwenko can you share a small reproducible example of that post route? There are a few things that could be happening here that might impact this, but it will depend on your usage and what/how your application is performing those calls.

**Comment by mwenko** [comment]
> @mwenko can you share a small reproducible example of that post route? There are a few things that could be happening here that might impact this, but it will depend on your usage and what/how your application is performing those calls.

@JonasBa 

Repository with reproducible example: https://github.com/flodaniel/sentry-test (Thanks to colleague @flodaniel)

When calling the `Get()` endpoint (defined in `app.controller`) of the application, I get the following result in Sentry:
<img width="886" alt="image" src="https://github.com/getsentry/sentry/assets/22257587/7dffbc3b-6c9e-4a8e-9819-1639a5cf41b0">

In the `ApplicationFrames` tab, I would expect to see the method calls in the following hierarchy:
- `appService.getHello()`
   - `appService.loadCode()`
      - `delay()`

But we get none of that as the screenshot proves.

Happy to hear your where/what we can improve here.

**Comment by JonasBa** [comment]
@mwenko first of all, thank you for providing a reproducible case, it helps us a lot and speeds up the time it takes for us to answer your question. 🙌

Unfortunately, what you are seeing is a limitation of the v8 CPU profiler and the implementation of `async` functions in the underlying engine. The issue itself comes from the fact that async functions are heap-allocated, meaning they are not visible by the stack based profiler.

Currently, Sentry's agentless design decision is a limiting factor in how much visibility we get into the process execution as we are limited to the information that we can obtain at runtime. Agent-based profilers that focus on observing your entire process will do a better job than what we currently can. Those profilers will also be able to collect C++ frames which are currently not visible to us. We are actively looking into addressing this in the mid-term future as it has been a common request from our users.

**Comment by mwenko** [comment]
> @mwenko first of all, thank you for providing a reproducible case, it helps us a lot and speeds up the time it takes for us to answer your question. 🙌
> 
> Unfortunately, what you are seeing is a limitation of the v8 CPU profiler and the implementation of `async` functions in the underlying engine. The issue itself comes from the fact that async functions are heap-allocated, meaning they are not visible by the stack based profiler.
> 
> Currently, Sentry's agentless design decision is a limiting factor in how much visibility we get into the process execution as we are limited to the information that we can obtain at runtime. Agent-based profilers that focus on observing your entire process will do a better job than what we currently can. Those profilers will also be able to collect C++ frames which are currently not visible to us. We are actively looking into addressing this in the mid-term future as it has been a common request from our users.

Understood, well explained and helpful!

In a world full of `async` functions, I'm wondering what benefit the profiling has for the users. While I understand that there are couple of use cases, the majority of applications _do_ use `async` functions to a very large extent.

Appreciate all your work on Sentry as a whole, because it's a great tool! ⭐ 

Looking forward to see this feature soon!
