### ISSUE TITLE
List a Project's Issues，GET /api/0/projects/{organization_slug}/{project_slug}/issues/

### ISSUE THREAD

**Issue by yysfwls** [getsentry/sentry#55750]
### Problem Statement

Path Parameters Can be supported time intervals ？
only "24h", "14d", and "" Now

### Product Area

APIs

**Comment by yysfwls** [comment]
Reference document：https://docs.sentry.io/api/events/list-a-projects-issues/

**Comment by Dhrumil-Sentry** [comment]
@schew2381 @sentaur-athena some helpful feedback for our issues endpoint- I believe the time windows are fixed to these values today for several endpoints

**Comment by yysfwls** [comment]
Are there plans to support this feature？like this
xxx?startTime=1693977220000&endTime=1694063620000

**Comment by Dhrumil-Sentry** [comment]
Hi @yysfwls we don't have concrete plans for this as of now, but we'll keep this issue updated if we have any news to share

**Comment by jangjodi** [comment]
I'm closing this issue as it's a duplicate of these two issues: https://github.com/getsentry/sentry/issues/38439 and https://github.com/getsentry/sentry/issues/45815
