### ISSUE TITLE
Wrong string serialization in Rust getting started instructions

### ISSUE THREAD

**Issue by tennox** [getsentry/sentry#55769]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. create rust project
2. confirm to get to "Getting started" page

### Expected Result

e.g. 
```
sentry = "0.25.0"
```

### Actual Result

![image](https://github.com/getsentry/sentry/assets/2084639/b74dff80-60ae-469b-83c6-3b2b844ed2a6)

... happens to the best of us :yum: 

### Product Area

Projects - Project Creation

### Link

https://tennoxlab.sentry.io/projects/rose-sonnen-influx/getting-started/

### DSN

https://88e9077d5e5373d190309ed8fbe596bd@o70999.ingest.sentry.io/4505833846013952

**Comment by matejminar** [comment]
Thank you @tennox for reporting! We are on it.
