### ISSUE TITLE
Symbolication Failures on macOS

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#5579]
Looks like some users are reporting that symbolication is failing for them on macOS. The application frames just show `<unknown>` or `<redacted>`.

Tooltip says "with the tooltip: "Unknown system frame. Usually from beta SDKs". This might be a regression from the `in_app` detection. Unsure if server or client at this point thoug

**Comment by mitsuhiko** [comment]
The issue effectively is most likely that `is_image_from_app_bundle` in the symbolizer now decides hard on if we go through the symbolserver or the user dsyms whereas previously we always fell back to the user dsyms.  This regression was caused by adding support for reprocessing.

We cannot reintroduce the fallback but for non iOS builds we could trivially change the behavior of `is_image_from_app_bundle` to consider anything below a path named something like `\.app/Contents/` to be "in app".

**Comment by mitsuhiko** [comment]
Actually on second thought we might just consider everything app bundled on macOS since the symbolserver does not carry any mac symbols.

**Comment by srubin** [comment]
Thank you!
