### ISSUE TITLE
"New Issues" in Release Overview Page Can't Handle High Issue Volume

### ISSUE THREAD

**Issue by ceorourke** [getsentry/sentry#55801]
The release overview page's "new issues" section is having trouble when there are a very large number of issues to show. [Here](https://sentry.sentry.io/issues/4387026486/events/abe116747f8e4b798061134070bd7cb8/?project=1) is a Sentry event created from it. Clicking the "Open in Issues" page creates a [similar error](https://sentry.sentry.io/issues/4394021961/events/50777fc9afb64fbfa3556331ce06c339/?project=1&referrer=issue-list&statsPeriod=24h) (`firstRelease:abc123` as the query). 

George left some investigation notes in the Slack thread this was surfaced in:
> here are some investigation notes:
this issue is on the rise lately, customers like `redacted` are running into this, despite the issue being Archived
the call doesn’t return results even for a 1h time span, so I don’t know of a workaround right now
it looks like the failure happens when fetching the issue counts. There’s special logic that runs if the customer has an unreasonable volume of data. In those cases, the code estimates the hits instead, using a sample size
in production, the sample size is 100
here’s [an example transaction](https://sentry.sentry.io/performance/sentry:86e1dc15a8ee4640865d9a1a2712e4d0/?breakdown=none&project=1&query=&showTransactions=p100&sort=-transaction.duration&statsPeriod=1h&transaction=%2Fapi%2F0%2Forganizations%2F%7Borganization_slug%7D%2Fissues-count%2F) where the query runs slowly but succeeds
the query times out after 30s

**Comment by armenzg** [comment]
I entered a URL under "Private Data" since it took me a bit to figure out how to find it.

**Comment by armenzg** [comment]
[This event](https://sentry.sentry.io/issues/4386450198/events/8007adbaf541457994065a9857b65036/?project=1) has a stacktrace and some values for the function calls.

I've added the exact API with the exact query parameters to "Private Data".

The sub-optimal query is this one:

```
SELECT sentry_groupedmessage.id
FROM sentry_groupedmessage
WHERE (sentry_groupedmessage.project_id IN (%s)
       AND NOT (sentry_groupedmessage.status IN (%s,
                                                 %s,
                                                 %s))
       AND sentry_groupedmessage.last_seen >= %s
       AND sentry_groupedmessage.id IN
         (SELECT U0.group_id
          FROM sentry_groupenvironment U0
          WHERE U0.environment_id IN (%s) )
       AND sentry_groupedmessage.id IN
         (SELECT U0.group_id
          FROM sentry_groupenvironment U0
          INNER JOIN sentry_release U2 ON (U0.first_release_id = U2.id)
          WHERE (U0.environment_id IN (%s)
                 AND U2.organization_id = %s
                 AND U2.version IN (%s)))
       AND sentry_groupedmessage.status IN (%s))
LIMIT 3001
```

**Comment by armenzg** [comment]
It seems that we were having some bad SQL performance up until Sept. 26th (IIRC).
I also discovered that *not* picking the environment makes the queries a lot faster, thus, reducing the chance of the page not loading for them.

**Comment by armenzg** [comment]
For now, this is working again, however, we need to make the issue less likely to happen by tackling #57594.
