### ISSUE TITLE
WrongBackend: Incorrect authentication service "github"

### ISSUE THREAD

**Issue by sabrehagen** [getsentry/sentry#5583]
When trying to authorise my github identity so that I can link a repository to my project, I get the following error: http://35.167.249.144:9000/share/issue/312e3430/

- Sentry 8.17.0
- Self hosted docker container

**Comment by dcramer** [comment]
Sounds like you didnt install the extension in all containers. Either way this is a support issue with your specific docker installation, not a bug in Sentry. https://sentry.io/support/

**Comment by servomac** [comment]
I just opened a topic explaining the problem:

https://forum.sentry.io/t/wrongbackend-incorrect-authentication-service-github/2191
