### ISSUE TITLE
OKTA config

### ISSUE THREAD

**Issue by jonramming** [getsentry/sentry#55864]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Attempting to set up okta auth. When I enter in the metadata URL, I get "It looks like you've hit an issue in our server API"

### Expected Result

OKTA auth should work

### Actual Result

OKTA auth does not work:
<img width="1257" alt="Screenshot 2023-09-07 at 1 42 16 PM" src="https://github.com/getsentry/sentry/assets/122482072/99803f68-d9f6-4bde-aa64-9a7a978b27af">

### Product Area

Settings - Auth

**Comment by kerenkhatiwada** [comment]
HI @jonramming, can you please write to sentry support with this issue? This will require looking at your organization.

**Comment by JoshFerge** [comment]
hasn't been commented on in over a year, closing out!
