### ISSUE TITLE
overlapping of sidebar menu on the expanded time range selector

### ISSUE THREAD

**Issue by vicainelli** [getsentry/sentry#55899]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Navigate to the issues page `https://ingka.sentry.io/issues/` 
2. Click on the time range selector `data-test-id="page-filter-timerange-selector"` 
3. Select the item "Absolute date" on the bottom

### Expected Result

<img width="1191" alt="Screenshot 2023-09-08 at 07 46 21" src="https://github.com/getsentry/sentry/assets/1155694/f2d8d190-a27d-4537-9cc0-081a95620569">

### Actual Result

<img width="1191" alt="Screenshot 2023-09-08 at 07 43 17" src="https://github.com/getsentry/sentry/assets/1155694/5863477d-3a52-4b6a-9305-3f74096125f0">

https://github.com/getsentry/sentry/assets/1155694/1d5a862a-d08c-4fc8-8c4e-4bd74ef7e553

### Product Area

Issues

**Comment by ceorourke** [comment]
Hey @vicainelli we're working on an improvement for this - it should be out "soon" though I don't have an exact timeline for you.

**Comment by mrduncan** [comment]
This seems to not be possible any more, please reopen if you're able to repro!
