### ISSUE TITLE
Customer fingerprint rule does not work (no stacktrace in issue)

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#55912]
The customer set a correct fingerprint rule and it did not apply. It matched by the message (there's no stacktrace) which contains UUID.

Please see "private data" field with link to Notion with more details.

Note for whoever takes this on, you can probably create an exact test case and investigate if fingerprint matching by message (rather than stacktrace) skips the fingerprint rules from the customer.

**Comment by lobsterkatie** [comment]
Custom fingerprinting applies regardless of the other methods we might use for grouping. Just checked the customer's data (from the link in the notion doc) and everything is now grouping on fingerprint, so I'm going to close this.
