### ISSUE TITLE
Safe cleaning of expired custom rules

### ISSUE THREAD

**Issue by RaduW** [getsentry/sentry#55978]
All custom rules for an organisation are kept in one Redis hash.
(Why ?).  Initially I wanted to keep one rule per key so we can leverage the Redis key expiration.
The problem with this approach is that it becomes a problem to find which keys are available for an organisation.

The current solution is to keep all rules applicable to an organisation ( or a set of projects in an org) under one key in a Redis Hash . This however makes it necessary to manage the expiration time of rules individually (since each rule inside the hash has its own expiration).

Currently there is a rule cleaning functionality implemented in Python, this reads all the rules for an organisation and removes the expired ones. This is done in multiple steps: read organisation hash, remove expired keys.

There is a small chance that another request overrides an existing rule (that was expired) after the hash is read but before the old keys are removed. This would cause the cleanup task to remove newly created rules.

We need what to do about this.

## Do not do anything about it

A valid approach is not to do anything about it, the chance of this happening is extremely small and the worst it can happen is that a new rule is deleted and needs to be re created.

## Implement the rule cleanup atomically

An atomic cleanup implementation can be done with a Lua script executed inside Redis 

**Note:** redis transactions would not work since the first operation is a read, and based on that read we need to see what we can delete. The read will not return anything until the transaction is closed so there is no way to read, decide what to remove, do the removing and then close the transaction.

## Change the way we store rules (one rule per key)

Not sure how to do this, I don't know how to find the keys, we can create a hash that contains rule keys rather than rules and have the rules expire but then we need to clean the hash containing the rule keys which brings us back to the original problem.

**Comment by matejminar** [comment]
We switched to pg.
