### ISSUE TITLE
Update alert dataset and query subscription on plan change

### ISSUE THREAD

**Issue by iambriccardo** [getsentry/sentry#55973]
The prefilling logic for AM1 to AM2 transition is already in place but there is an edge case to cover, since alerts are triggered by query subscriptions that are stored on snuba. Since those subscriptions are not touched by the prefilling, we need to find a way to automatically invalidate all subscriptions of an org that has been moved to AM2.

**Comment by iambriccardo** [comment]
![Image](https://github.com/getsentry/sentry/assets/15819674/5f1d3f17-3209-4dc9-a9e4-a7f36c9c5c35)

**Comment by obostjancic** [comment]
Closing in favor of #58137

**Comment by obostjancic** [comment]
Closing in favor of #58137
