### ISSUE TITLE
API for managing AWS S3 repository secrets

### ISSUE THREAD

**Issue by jonpaul** [getsentry/sentry#55988]
### Problem Statement

I want to ability to programmatically manage the AWS credentials provided to Sentry for custom debug repositories. Many compliance rigors require software companies to periodically rotate access credentials (such as the secret and token used for the AWS cloud) and manually performing these routine modifications is cumbersome.

### Solution Brainstorm

An API provided by Sentry that allows customers to list all their custom repositories and update the credentials used to configure that resource. Managing the other attributes of the custom repository (bucket or region for example) could also prove useful though the only values routinely changed are the key+secret.

### Product Area

Settings - Repositories

**Comment by Dhrumil-Sentry** [comment]
Hi @jonpaul Thanks for this feedback- We're certainly looking into making APIs available for adding and managing debug file repos.

@kahest Another request similar to https://github.com/getsentry/sentry/issues/55923 - APIs for this setup flow would be helpful in several cases

**Comment by jonpaul** [comment]
Thank you @Dhrumil-Sentry I appreciate your consideration. Like the other user, we also prefer APIs over terraform but have expertise in both. Have a wonderful day.

**Comment by loewenheim** [comment]
This can theoretically already be accomplished with an existing API endpoint: https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/project_details.py

A get request to this endpoint will return the project's full details, including a `symbolSources` field containing all configured sources:
```
❯ curl -H 'Authorization: Bearer 0462b1de967f726b2a8a6843edc3c11832636838ad4522f3183d7e430d685fba' localhost:8000/api/0/projects/sentry/1745/ | jq .symbolSources

"[{\"secret_key\":{\"hidden-secret\":true},\"id\":\"d1887865-11b9-40ae-988e-ea8c538c194e\",\"layout\":{\"type\":\"native\",\"casing\":\"default\"},\"region\":\"us-east-1\",\"access_key\":\"abcdefg\",\"bucket\":\"uiaenu\",\"name\":\"aws-test\",\"type\":\"s3\"},{\"id\":\"171f3bf8-712f-4c75-b2c7-8ab638aec4a1\",\"name\":\"http-test\",\"url\":\"example.com\",\"layout\":{\"type\":\"native\",\"casing\":\"default\"},\"type\":\"http\"}]"
```
Unfortunately, as you can see, this field is not a JSON object but the string representation of a JSON object.

Editing symbol sources can similarly be accomplished by sending a PUT request to the same endpoint. You would have to edit the (parts of the) symbol sources you want to change (i.e. the `secret_key` of the `aws_test` source in the above example) and send the rest back unchanged.

Thus, the full procedure to update an AWS source would look like this:
1. GET `/api/0/projects/{org}/{project}/`
2. parse the response's `symbolSources` field into a JSON list
3. edit the `access_key`, `secret_key`, and whatever else you want to change in the right source in the list
4. serialize the list of sources back to a string
5. PUT `/api/0/projects/{org}/{project}/` with the request containing `symbolSources: <the serialized string from 4>`

This is obviously quite cumbersome. If the inconvenience is too high, we can think about introducing a more specialized API.

**Comment by loewenheim** [comment]
We have started working on a more pleasant API: https://github.com/getsentry/sentry/pull/56464

**Comment by jonpaul** [comment]
Thank you for your reply @loewenheim, I agree that's it's definitely possible to do but a more specialized API would be preferable. Thank you for working on the new interface.

**Comment by Dhrumil-Sentry** [comment]
@jonpaul we've published APIs to allow users to add/delete/update symbol sources:

https://docs.sentry.io/api/projects/update-a-projects-symbol-source/
https://docs.sentry.io/api/projects/add-a-symbol-source-to-a-project/
https://docs.sentry.io/api/projects/delete-a-symbol-source-from-a-project/

Can you please take a look and let us know if this unblocks you?
