### ISSUE TITLE
Create team API not working as expected

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#55985]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

According to the documentation [here](https://docs.sentry.io/api/teams/create-a-new-team/), create a team using the endpoint:
https://sentry.io/api/0/organizations/my-org-slug/teams/?name=newteam

### Expected Result

A new team is created.

### Actual Result

We get the following 400 error:
```
{
    "non_field_errors": [
        "Name or slug is required"
    ]
}
```

The workaround to this is to include the following in the body:
```
{ "name":"newteam"}
```

### Product Area

APIs

**Comment by Dhrumil-Sentry** [comment]
@sentaur-athena @schew2381 Can either of you please take a look?

**Comment by schew2381** [comment]
Hi, currently we mislabel many body parameters in our API documentation as query parameters. Our docs page has no way to distinguish between them and we're looking to add this in the future.
