### ISSUE TITLE
crash report is stretched upon opening in IE11 until resize

### ISSUE THREAD

**Issue by vzaidman** [getsentry/sentry#5601]
using
<script src="https://cdn.ravenjs.com/3.12.0/console/raven.min.js" crossorigin="anonymous"></script>

in IE11

I have a bug where upon first opening of the crash report, the window is stretched like in mobile mode.

a minor resize immediately solves it.

![01](https://user-images.githubusercontent.com/5188459/27433123-f88fefd2-575b-11e7-9180-0723f3bcb8ed.png)

**Comment by vzaidman** [comment]
looks like i also found a solution:
https://stackoverflow.com/questions/34736866/css-is-broken-in-ie11-until-developer-tools-are-opened

**Comment by vzaidman** [comment]
Where can i see the list of the supported browsers?

**Comment by benvinegar** [comment]
Oh my bad, this is for the User Feedback dialog. Hmm.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
