### ISSUE TITLE
Spec out an incident tracking service

### ISSUE THREAD

**Issue by udameli** [getsentry/sentry#56048]
Previous docs: https://www.notion.so/sentry/Platform-Support-for-SD-and-Crons-Issues-Spec-46b819dfdb474acea937fba6e02f8582?pvs=4#5a1262df937c495288259636e38fe6ee

Similar work being done by the Crons team: https://github.com/getsentry/sentry/issues/54202

**Comment by JoshFerge** [comment]
covered by other projects at this point. closing
