### ISSUE TITLE
Feature Request: Telegram integration

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#56066]
### Problem Statement

Our customer wants to have a Sentry-supported Telegram integration since they don't use Slack

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
We'll add this to our backlog but we don't have any near term plans to do this

**Comment by Dhrumil-Sentry** [comment]
Marking this as a duplicate of https://github.com/getsentry/sentry/issues/61998
