### ISSUE TITLE
Alerts should be sent to members outside the Sentry org as well

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#56068]
### Problem Statement

Some of our customers work with clients that they don't want to invite to Sentry, but they should still be able to receive some alerts. Currently, only the Sentry org members can receive alerts. Our customer doesn't use Slack so that cannot be set up as a workaround.

### Product Area

Alerts

**Comment by rachrwang** [comment]
@dalnoki - do we know why these customers don't want to invite their clients to Sentry? For legal/ policy reasons - we don't have any plans to send notifications to users that aren't Sentry users. If they are firm on not inviting those clients into Sentry, I'd recommend setting up email forwarding and/or a shared slack channel (or ms teams, if they use that)

**Comment by ceorourke** [comment]
Closing as there's been no follow up in over a year. Feel free to reopen if this is still relevant.
