### ISSUE TITLE
[Github Integration] Code Mapping (Stack trace linking) does not work when abs_path uses backslashes

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#56115]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

 Reported by customer on php sdk, and I tested by using RewriteFrames in Javascript to make my stack trace use backslashes.

**1. Send an error where the abs_path uses backslashes.** 

<img width="419" alt="Screenshot 2023-09-12 at 4 14 29 PM" src="https://github.com/getsentry/sentry/assets/96670625/526b1f6f-7e74-425f-8bce-f9fd717807b0">

**2. Open up the issue and click on the "Tell us where your source code button"**

<img width="559" alt="Screenshot 2023-09-12 at 4 14 52 PM" src="https://github.com/getsentry/sentry/assets/96670625/6c4b0b44-fa70-4563-a9ab-ddc7a6ef6e9d">

**3. Put in the path of the file and click save and receive 400 error with double backslashes for the stackPath in the POST request -**

<img width="1504" alt="Screenshot 2023-09-12 at 4 19 10 PM" src="https://github.com/getsentry/sentry/assets/96670625/9fe16a1e-8699-4f0e-ba79-a39c7ae50205">

### Expected Result

Sentry should detect that the filename is the same regardless of whether there is a front slash or backslash.  

### Actual Result

Sentry believes the filename is incorrect.  If I change the slash in the abs_path to a front slash, it will work.

[Event with backslash and double backslashes in abs_path ](https://francisorg.sentry.io/issues/4458353703/events/2cc7d7b4b20849c4b4b7bd713da06d6a/)

### Product Area

Settings - Integrations

**Comment by bruno-garcia** [comment]
To call out this came up here again:

* https://github.com/getsentry/sentry/issues/64342#issuecomment-1924571624

Windows is still number 1 desktop OS out there so worth addressing this one. 🙏

**Comment by MichaelSun48** [comment]
Fixed in #65474
