### ISSUE TITLE
NextJS Profiling on Server Side

### ISSUE THREAD

**Issue by radekwarisch** [getsentry/sentry#56153]
### Problem Statement

Hey Team, I have a question regarding Profiling feature (https://docs.sentry.io/platforms/node/profiling/). 
We would like to setup NextJS profiling for checking for bottlenecks, but on the server side (I see there is a guide, but it seems to cover only client side: https://docs.sentry.io/platforms/javascript/guides/nextjs/profiling). 
I do not see how to set it up for server side for NextJS?

### Solution Brainstorm

Guide on connecting profiling to NextJS with server side would be great.

### Product Area

Performance

**Comment by JonasBa** [comment]
@radekwarisch we support both nodejs and browser profiling (you actually linked to them in your description). There is no one single package to manage this so you need to follow the setup guide for each platform separately (for nodejs https://docs.sentry.io/platforms/node/profiling/) and for browser js (https://docs.sentry.io/platforms/javascript/guides/nextjs/profiling/). You will need to install @sentry/browser and @sentry/node and @sentry/profiling node to make this work.
