### ISSUE TITLE
Sentry Replay crashes when displaying Google File Picker

### ISSUE THREAD

**Issue by damacisaac** [getsentry/sentry#56160]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Record a replay in which a Google File Picker modal is presented on screen. 
2. Watch the replay in Sentry

### Expected Result

1. The Replay does not break after displaying the Google File Picker

### Actual Result

<img width="1512" alt="Screenshot 2023-09-13 at 10 53 11 AM" src="https://github.com/getsentry/sentry/assets/3689921/49cd4636-d5d7-4a85-a953-8f141e2f6fb4">

### Product Area

Replays

### Link

https://coefficient.sentry.io/replays/4306b9a4bd1e481faacc6f46c0098ca5/

**Comment by billyvg** [comment]
@damacisaac I'm not familiar with Google File Picker, would it be the same one that's used in Google Drive or gmail?

**Comment by damacisaac** [comment]
This one: https://developers.google.com/drive/picker/guides/overview

**Comment by billyvg** [comment]
Ah so I misunderstood the ticket -- I thought the Picker was crashing Replay during recording: I made a repro in a sandbox here: https://codesandbox.io/s/charming-panka-qn6r75?file=/src/App.js and it records fine. The picker does not show up in the replay because it is a cross origin frame, so our player cannot load it.

**Comment by damacisaac** [comment]
For me the Replay video player would crash. It would start showing a blank video.

**Comment by billyvg** [comment]
Just to note, the player is not crashing, it is however, having issues recording the iframe contents - will investigate

**Comment by bruno-garcia** [comment]
Since this issue was created we released a new version of the SDK with improved iframe support. This should be fixed but if not, please feel free to reopen!
