### ISSUE TITLE
Design: Update Replay onboarding view to match the new style that Crons spearheaded

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#56263]
![Image](https://user-images.githubusercontent.com/187460/268049380-72ed0288-51ac-40d8-815d-c2588deb852c.png)

**Comment by jas-kas** [comment]
If we're going to iterate on the empty state of Replay Index, can we include a callout to the Sandbox?

**Comment by Jesse-Box** [comment]
Theres two working docs for this

The userflow, which aims to clarify how the front show/might behave
* [Figma](https://www.figma.com/file/DZOMcbl7iU3WBSrKtREEPB/Exploration%3A-Onboarding-v3?type=whiteboard&node-id=0%3A1&t=zQaqXqfVTKmkYFeC-1)
* [Rewatch](https://sentry.rewatch.com/video/b039vugmoszx1n29-replay-onboarding-v3-exploration-feedback-round-2)

The visual presentation of our page
* [Figma](https://www.figma.com/file/ltrSBJHvlz0TB1b96vlEtn/Specs%3A-Onboarding-v3?type=design&node-id=5%3A8913&mode=design&t=iD77Wyt9IiFXI8Zg-1)
* [Rewatch](https://sentry.rewatch.com/video/iucic9oe5rynnsk0-issue-details-replay-section-exploration-feedback-round-1)

**Comment by michellewzhang** [comment]
Closing as we've moved to the project epic: https://github.com/getsentry/sentry/issues/60793
