### ISSUE TITLE
long error location in regression email breaks formatting

### ISSUE THREAD

**Issue by JannKleen** [getsentry/sentry#5626]
This happens on Sentry 8.17.0 using Apple Mail (Version 10.3 (3273)) . It works fine in the gmail web app.

![screen shot 2017-06-26 at 11 57 48](https://user-images.githubusercontent.com/170582/27535184-02f5e042-5a6a-11e7-8a7e-50f442d353ce.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
