### ISSUE TITLE
Comments section in issues does not work

### ISSUE THREAD

**Issue by MrMorice** [getsentry/sentry#5627]
Sentry 8.16.1, Docker

Sentry throws an error when visiting the comments section of an issue. The following error is logged to sentry internal channel:

TypeError
b.sprintf.parse is not a function

./app/locale.jsx in parse at line 45:10
function formatForReact(formatString, args) {
  let rv = [];
  let cursor = 0;
  // always re-parse, do not cache, because we change the match
  sprintf.parse(formatString).forEach((match, idx) => {
    if (_.isString(match)) {
      rv.push(match);
    } else {
      let arg = null;
      if (match[2]) {
./app/locale.jsx in formatForReact at line 201:11
./app/locale.jsx in format at line 210:9
./app/views/groupActivity/index.jsx in t.formatActivity at line 92:17
./app/views/groupActivity/index.jsx in formatActivity at line 178:20
./app/views/groupActivity/index.jsx in map at line 152:34
./app/utils/errorHandler.jsx in apply at line 8:28

**Comment by mattrobenolt** [comment]
This was fixed in 8.17.

**Comment by MrMorice** [comment]
Thanks! Just upgraded and it works perfectly now! All the best, Moritz
