### ISSUE TITLE
`Unable to load tags` error when opening any page that needs tags to be loaded

### ISSUE THREAD

**Issue by hariprasadiit** [getsentry/sentry#56277]
### Self-Hosted Version

23.8.0

### CPU Architecture

x86_64

### Docker Version

20.10.23

### Docker Compose Version

2.15.1

### Steps to Reproduce

Since upgrade to 23.8.0, we started seeing this issue. not sue if it can be reproduced in a fresh install.

### Expected Result

No error in loading tags

### Actual Result

Everything is working except, it shows error, `Unable to load tags`.  I'm using official docker-compose.
```
[ERROR] django.request: Internal Server Error: /api/0/organizations/vizmo/tags/ (status_code=500 request=<WSGIRequest: GET '/api/0/organizations/vizmo/tags/?statsPeriod=7d&use_cache=1&utc=false'>)
```
This is the error I'm seeing in the `web` logs.

Appreciate help in looking for relevant logs from other dependencies.

**Comment by roggenkemper** [comment]
hi! do you know what version you were on before upgrading to 23.8.0? When the error comes up, can you just dismiss it and access the page still or is it completely erroring on any page where it tries to load tags?

**Comment by hariprasadiit** [comment]
> hi! do you know what version you were on before upgrading to 23.8.0? When the error comes up, can you just dismiss it and access the page still or is it completely erroring on any page where it tries to load tags?

I was using 23.6.1 before the upgrade. I can't dismiss the error, however I can access the page still

**Comment by malwilley** [comment]
@hariprasadiit - do you see any issues related to this in your `internal` project? It should create issues there by default, which could help us debug the problem.

**Comment by hariprasadiit** [comment]
@malwilley for some odd reason, `Internal` project is not picking up these 500 errors. Not sure what went wrong there. I can  see some resolved older errors related `ChunkLoadError`

**Comment by scefali** [comment]
You need to dig into the logs and figure out what's going on for us to be able to help. Or just switch to SaaS and let us deal with it.

**Comment by hariprasadiit** [comment]
it seems it was some issue with Kafka streams. After seeing `"Broker: Offset out of range"` error I've reset all Kafka offsets, which fixed this issue for me.
