### ISSUE TITLE
Discord Integration gone from Integrations list

### ISSUE THREAD

**Issue by perryliao** [getsentry/sentry#56285]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Following the documentation: https://docs.sentry.io/product/accounts/early-adopter-features/discord/
1. Turn on Early Adopter toggle in Organization -> General Settings
2. Go to Integrations
3. Discord is not on the list 

### Expected Result

Discord should be on the list, but is not. (It was there earlier this week and yesterday, but it's gone when I tried to actually use it this morning.)

### Actual Result

<img width="558" alt="Screenshot 2023-09-14 at 1 07 15 PM" src="https://github.com/getsentry/sentry/assets/26581943/fbbc974b-7c71-41d4-95c2-c5d13a56fdf9">
<img width="675" alt="Screenshot 2023-09-14 at 1 07 25 PM" src="https://github.com/getsentry/sentry/assets/26581943/fb1fc03e-73c8-4edd-aa40-7abd4a9977f3">

### Product Area

Settings - Integrations

**Comment by malwilley** [comment]
Thank you for the report!

The discord integration was briefly disabled for early adopter orgs, but has since been restored. If you go back to your integrations page you should see it again. Sorry for the interruption!
