### ISSUE TITLE
Do not prompt user to tell us where the source code map is when there is unminified code

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#56319]
When a stacktrace has minified code, we should not ask the customer to tell us where their source code is. See screenshot.

![Image](https://github.com/getsentry/sentry/assets/44410/28a5ecff-da62-4b32-b696-d6e83c855fed)

PS: In the Private Data field, I have a link to an issue where source maps are missing and we ask for creating code mappings

**Comment by scttcper** [comment]
the new version will hide it
