### ISSUE TITLE
Please clarify "Bulk Remove a List of Issues" API

### ISSUE THREAD

**Issue by chylek-qr** [getsentry/sentry#56315]
### Problem Statement

Hi, the "Bulk Remove a List of Issues" API is missing some important details: https://docs.sentry.io/api/events/bulk-remove-a-list-of-issues/

The example does not show how the list of issue IDs should be provided, and the parameter description is not clear.

<img width="505" alt="image" src="https://github.com/getsentry/sentry/assets/73221701/98b23015-0213-40db-b8db-752ce2cfb3f7">

To me, this means `id[]=1&id[]=2&id[]=3`, because that's how I'm used to passing a "list" or "array" in URLs in web applications, and multiple web frameworks support this.

However, if I try this, then instead of getting an error that the API is not recognizing the format of the query, it appears Sentry just deletes every single issue in the project. This seems insane to me.

### Solution Brainstorm

Please clarify how the API should be used, and perhaps show an error when the URL query is invalid instead of deleting every single issue in a project.

### Product Area

APIs

**Comment by Dhrumil-Sentry** [comment]
@schew2381 Can you please take a look ?

**Comment by varunsaral** [comment]
@Dhrumil-Sentry 
https://github.com/getsentry/sentry/blob/6f09b9ae5224dab3172f96844b68b4d86aeeec1c/src/sentry/api/endpoints/group_details.py#L354C1-L354C1
This function does not seem to handle multiple issues, it accepts only one issue, that too in /issues/issues-id format, maybe we can try /issues/id1,id2,id3 and split them in delete function and delete one by one. I tried to look at code and can be entirely wrong.

**Comment by chylek-qr** [comment]
The format `id=1&id=2&id=3` seems to have worked and deleted the correct issues, however it seems to be a fragile API that can destroy all issues if you use it wrong by accident.

**Comment by malwilley** [comment]
@chylek-qr I agree that this can be documented better. I also agree that this is dangerous API design, but it has existed this way for quite some time so I'm wary of changing the functionality in case some users depend on it working this way. I'll start by adding some clarifying documentation and we'll keep this in mind if we ever need to modify the way bulk actions work.

**Comment by varunsaral** [comment]
Hey @malwilley did I read the correct code block, unfortunately I couldn't see any bulk action and it was working on single issue. 
https://github.com/getsentry/sentry/blob/6f09b9ae5224dab3172f96844b68b4d86aeeec1c/src/sentry/api/endpoints/group_details.py#L354C1-L354C1

**Comment by malwilley** [comment]
@varunsaral the relevant code block is here actually https://github.com/getsentry/sentry/blob/65401f44631fcd751657e9ff099a228aef2f4d8a/src/sentry/api/endpoints/organization_group_index.py#L467

**Comment by varunsaral** [comment]
Thanks for the clarification @malwilley it was little tricky to find it through urls.py.
