### ISSUE TITLE
Allow alerts for "custom performance metrics" 

### ISSUE THREAD

**Issue by dor-tzur-lmnd** [getsentry/sentry#56314]
### Problem Statement

Currently Sentry's "alerts" feature support "custom metrics" but not "custom performance metrics". 

We've setup at Lemonade several custom performance metrics which we would like to get alerted when they abnormally changed. 

### Solution Brainstorm

Merge "custom metrics" in the alerts feature to also include "custom performance metrics". Wanting get alerted for drastic performance changes for custom metrics sounds like would be beneficial to many customers

### Product Area

Alerts

**Comment by malwilley** [comment]
Thanks for the feature request @dor-tzur-lmnd! You're right that this would be valuable. We have some discussion about this in another issue (https://github.com/getsentry/sentry/issues/55159) so please show your support there! I'll close this one for now as a duplicate.
