### ISSUE TITLE
Expand Alerting capability to specific performance transactions/spans

### ISSUE THREAD

**Issue by sethkfman** [getsentry/sentry#56312]
### Problem Statement

I would like to be able to alert on specific performance transactions/spans when they drift out of tolerance similar to what I can do for errors.

For example, I want to know when our login view takes more than 8 seconds to complete the ui.load transaction. If there are 1000 events beyond 8 seconds in a 24 hr period I would like the alert to be signaled. 

### Product Area

Performance

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1943) by [Unito](https://www.unito.io)

**Comment by sethkfman** [comment]
Percentile is sufficient. The desire is to be able to track a performance transactions rather than a specific span inside the an event.

**Comment by nanoburd** [comment]
So you can currently do that with the product today.

https://docs.sentry.io/product/alerts/alert-types/#performance

You can set percentile thresholds if you apply a filter for a specific transaction name.

If there is a span you are interested in, I would potentially advise you to custom instrument that span as a transaction as a mini-hack.
