### ISSUE TITLE
Hang/No response @ ingest.sentry.io/api/

### ISSUE THREAD

**Issue by colinmcdermott** [getsentry/sentry#56347]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Hi,

I am looking at web performance on our site and noticed the follow.

Can I check if something like the below (see screenshot) is normal/to be expect, or fixable?

https://i.imgur.com/uB1s3L8.png

GtMetrix report: https://gtmetrix.com/reports/whop.com/dMFwG5PT/

I believe we are using sentry/nextjs package.

### Expected Result

Ideally would like to not see such a long query/no response

### Actual Result

https://i.imgur.com/uB1s3L8.png

GtMetrix report: https://gtmetrix.com/reports/whop.com/dMFwG5PT/

### Product Area

APIs

### Link

https://whop.com/

**Comment by jjbayer** [comment]
@colinmcdermott thanks for reporting. Does this happen on every request, or only sporadically?

**Comment by jjbayer** [comment]
@colinmcdermott might this be a problem with your local setup / internal network? I can get a fast response from the URL in your screenshot:

```shell
curl --data '{}' 'https://{org}.ingest.sentry.io/api/{project}/envelope/?sentrykey={key}'
```

**Comment by JoshFerge** [comment]
stale issue, gonna go ahead and close. feel free to re-open!
