### ISSUE TITLE
Statistics for frequency of particular Tag values are incorrect

### ISSUE THREAD

**Issue by ryho** [getsentry/sentry#5636]
Using Sentry 8.5.1
Installation etc: Not sure, I work for a large company, but our Sentry seems to be hosted internally.
For a long time now, the "Tags" statistics on the right side of an issue seem to be correct, but when I click a particular Tag to view the full breakdown, the data is conflicting and makes no sense. 
Tags at the right of an issue:
![screen shot 2017-06-27 at 12 20 47 pm](https://user-images.githubusercontent.com/2478057/27598301-11d54ade-5b33-11e7-9b63-ee25fc70747a.png)
Clicking the "Merchant Token" Tag:
![screen shot 2017-06-27 at 11 14 09 am](https://user-images.githubusercontent.com/2478057/27598243-e40fd5b0-5b32-11e7-8a5e-0977717a991e.png)
This is the most extreme example I have come across so far, but this always seems to be the case for my project, and the other devs on my team agree that it has been this way for a while.
I can provide additional info myself or I can try to find the right people at my company for further info if necessary.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
