### ISSUE TITLE
CODEOWNERS file not syncing properly

### ISSUE THREAD

**Issue by serglom21** [getsentry/sentry#56401]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

This ticket is being filed on behalf of a customer. So specific examples and the CODEOWNERS file will be attached in the JIRA ticket

CODEOWNERS file does not sync automatically and manually syncing it returns a "successful" message but the latest changes are not reflected.

We validated by looking at the request Sentry makes to GH and the raw data from the CODEOWNERS file that there are some differences.

### Expected Result

I expect the CODEOWNERS file entries to be synced properly

### Actual Result

CODEOWNERS entries are not synced properly

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1939) by [Unito](https://www.unito.io)

**Comment by lobsterkatie** [comment]
Related ticket with more detail: https://github.com/getsentry/sentry/issues/56624. In that case content changes are apparently syncing, though.

**Comment by snigdhas** [comment]
It looks like the related ticket was fixed. Marking this as closed but please reopen if the issue still exists.
