### ISSUE TITLE
AI Feature Request

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#56428]
### Problem Statement

Customer request the option to adjust the tone and demeanor of the AI, making it less sarcastic and removing the use of emojis

### Product Area

Issues - Suggested Fix

**Comment by matejminar** [comment]
Hi @kerenkhatiwada, I'll discuss this with the team. We don't have enough similar feedback around this so it will likely have lower priority. We welcome PRs though in case you'd like to have this finished sooner.

**Comment by vartec** [comment]
The AI behavior has been tweaked in the past to address off-color jokes, so this should no longer be an issue.
