### ISSUE TITLE
Customisable default for new alert rules

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [getsentry/sentry#56446]
### Problem Statement

I would like an option so you can customise the default alert rule "layout" or setup for when a new alert rule is created for a project, this could be useful for people who commonly have the same conditions and notification methods for each alert rule.

### Product Area

Alerts

**Comment by malwilley** [comment]
Thank you for the feature request! If I'm understanding correctly, you'd like some sort of customizable template for new alert rules?

This seems similar to this feature request, which is something we've considered: https://github.com/getsentry/sentry/issues/30059

I'll close this issue as a duplicate, but please throw your support behind the other issue or let us know if your idea is different enough to warrant a separate issue.

**Comment by WilliamDavidHarrison** [comment]
I didn't realise this was a duplicate, sorry for wasting your time!
