### ISSUE TITLE
Celery issues + Increase number of events accepted

### ISSUE THREAD

**Issue by munai-das** [getsentry/sentry#5645]
## Configuration

- Sentry Version: 8.7.0  --- c4.4xlarge (50% usage maximum)
- Postgres Version 9.3.14  ---- db.m4.4xlarge (50% usage maximum)
- Redis Version  3.2.4 ----- r3.2xlarge(8-10% usage maximum)

## Issues

1.  **Celery events getting queued**

$ sentry --config "/etc/sentry" queues list
alerts 0
auth 0
cleanup 0
counters-0 78
default 0
digests.delivery 0
digests.scheduling 0
email 0
events 129014
merge 0
options 0
search 0
stats 0
triggers-0 0
update 0

2. **Sentry accepts only 540,000 events per day**

How to increase this limit? Is there any tuning to do in the server level?

**Comment by dcramer** [comment]
We do not provide support for your infrastructure via our GitHub tracker.

https://sentry.io/support/
