### ISSUE TITLE
Gauges/counters consumer changes

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#56482]
From Riya:

Hey, the main entry point for metric message processing lives [here](https://github.com/getsentry/sentry/blob/master/src/sentry/sentry_metrics/consumers/indexer/processing.py). This is where the logic for processing/indexing any metrics messages begins. The Consumer Strategy Factory helps create the actual consumer using its configured strategy

**Comment by iambriccardo** [comment]
Trying to figure out with @ayirr7 and @mitsuhiko how to move it forward.

**Comment by iambriccardo** [comment]
We agreed to not continue on this path due to its complexity and the fact that it will be a temporary change.

**Comment by iambriccardo** [comment]
We agreed to not continue on this path due to its complexity and the fact that it will be a temporary change.
