### ISSUE TITLE
Discord Integration link support for in-browser

### ISSUE THREAD

**Issue by 17hogeju** [getsentry/sentry#56481]
### Problem Statement

On Integrations > Configure Discord, the `Open in Discord` button only opens the Discord desktop app. It should also allow users to open Discord in their browser.

### Solution Brainstorm

Changes will be centered around this [line](https://github.com/getsentry/sentry/blob/17d7b08c837ab0ba02a707e7d76a4bebc42ff497/static/app/views/settings/organizationIntegrations/configureIntegration.tsx#L270C76-L270C76)

### Product Area

Settings - Integrations

**Comment by iamrajjoshi** [comment]
Closing b/c not much value added.
