### ISSUE TITLE
Usage of setLevel not working in Java lib

### ISSUE THREAD

**Issue by lcszulpo** [getsentry/sentry#5651]
Version of Sentry - 1.2.0
Language - Java
Manager - Maven

The following code:

```
Sentry.record(
         newBreadcrumbBuilder().
         setMessage(message).
         setLevel(Breadcrumb.Level.ERROR).
         build());
```

Does not generate an issue in the Dashboard with the error level, but a info issue.

**Comment by tkaemming** [comment]
This is the repository and issue tracker for the Sentry server. You're looking for [getsentry/sentry-java](https://github.com/getsentry/sentry-java).

As far as your problem goes: the level that is shown on the dashboard is the issue level (which is derived from the latest event seen in an issue.) `Sentry.record` is recording breadcrumbs, which are part of an event, and not issues, so the breadcrumb level has no effect on the dashboard display. You'd use `Sentry.capture` to record an event, and you can set the level using the `EventBuilder.withLevel` message. Here are more usage examples: https://docs.sentry.io/clients/java/usage/

In the future, [please use the forum](https://forum.sentry.io/) for questions or other non-bug reports.
