### ISSUE TITLE
Unable to Resolve via Release when selected issues span multiple projects

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#56565]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When you try to click on the dropdown arrow next to the Resolve button while you have issues of multiple projects selected, you are shown the `Resolving is better with Releases` tool tip, regardless of whether the issues selected has a release value or not.

**Example of tooltip where all issues selected has a release**  [direct link to search in below screenshot](https://francisorg.sentry.io/issues/?query=release%3AtestMultiProjectResolve&referrer=issue-list&statsPeriod=14d) -
<img width="600" alt="Screenshot 2023-09-20 at 10 39 05 AM" src="https://github.com/getsentry/sentry/assets/96670625/41ef779f-c9c9-4836-9d4f-81250835223a">

**Release** - 

<img width="600" alt="Screenshot 2023-09-20 at 10 45 39 AM" src="https://github.com/getsentry/sentry/assets/96670625/acbd6747-bce6-4552-b1b7-9b4573ba21d0">

### Expected Result

Should be able see to at least see the normal dropdown menu when a release is detected in all the issues selected, or if they all share the same release value.

<img width="250" alt="Screenshot 2023-09-20 at 10 52 51 AM" src="https://github.com/getsentry/sentry/assets/96670625/71a5fad5-eba3-4eff-90a1-c9c19df99e12">

### Actual Result

<img width="250" alt="Screenshot 2023-09-20 at 10 53 51 AM" src="https://github.com/getsentry/sentry/assets/96670625/a79e34b4-de6d-46d1-886c-cdec9bbcfb2e">

### Product Area

Issues

**Comment by scttcper** [comment]
Thanks for reporting, we don't allow resolve in commit across projects but it shouldn't show the setup releases CTA
