### ISSUE TITLE
Codeowners `dateUpdated` not updating even though file syncs

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry#56624]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Go to the codeowners file in the codeowners page.
Click on the "Sync" button for a codeowners file.
Observe that the "Last Sync" time does not update as expected. 

Workaround:
Delete the codeowners file and then re-import it. 

### Expected Result

The "Last Sync" time should update immediately after clicking the "Sync" button, indicating that the codeowners file changes have been successfully synced.

### Actual Result

The "Last Sync" time remains unchanged, even after attempting to sync the codeowners file.

### Product Area

Settings

**Comment by malwilley** [comment]
@cdignam-segment when you sync, do the values update correctly? I'm trying to understand if this is just a bug with the "Last Sync" time, or with codeowner syncing in general.

**Comment by lobsterkatie** [comment]
@cdignam-segment Have you noticed, does the time eventually correct itself? Or is it stuck on a previous sync's time?

**Comment by lobsterkatie** [comment]
Thanks for the link.

I wonder if it has anything to do with this:
![image](https://github.com/getsentry/sentry/assets/14812505/390b0dea-72a9-468b-b0ba-3fee9424bf35)

Do you know when you first started getting those errors?

**Comment by lobsterkatie** [comment]
UPDATE: @cdignam-segment, never mind on my question about the errors. I spoke to a colleague who's worked on this feature and he said we just skip rules with problems and update the rest. He also pointed me to a related issue from earlier this month. Sounds like this is indeed a bug. I'll bring this to my PM's again and will update here once there's any news on when we might work on this.
