### ISSUE TITLE
Allow downloading attachments using the Sentry API

### ISSUE THREAD

**Issue by floriancuringa-evam** [getsentry/sentry#56643]
### Problem Statement

Hello,

We are using Sentry attachments to send files from our app using the Android SDK. 

These files include various logs from our application, and we would like to setup some script to periodically download them and analyze them.

However, it seems that the Sentry API does not allow the download of attachments. The only way is to use the Sentry UI.

### Solution Brainstorm

*Note: I am not familiar with the codebase so feel free to dismiss this.*

Using the Events and Issues API it is possible to retrieve the attachment download link (e.g. `/api/0/projects/{org}/{project-name}/events/{event-id}/attachments/{attachment-id}/?download=1`) but attempting the download using an access token results in an expected 403 error.

Maybe it would be possible to add this as a scope in the access token creation? 

### Product Area

APIs

**Comment by malwilley** [comment]
@floriancuringa-evam are you using an integration token to make this request? 

It looks like we check user roles on this endpoint, which means that tokens not associated with a user won't work. I'll have to look into why we made that decision to determine whether or not we can expand this to work with non-user tokens. But in the meantime as a workaround you can use a user token to make these requests successfully: https://docs.sentry.io/api/auth/#user-authentication-tokens

**Comment by floriancuringa-evam** [comment]
@malwilley Thanks a lot for the quick answer.

Yes, I am using an integration token. Sorry for not specifying it earlier.

I can try with a user token instead today and tell you how that went.

**Comment by floriancuringa-evam** [comment]
@malwilley  I confirm using a User token works as expected. 

Since it is OK for me to use a User token you may close this issue as far as I am concerned.

**Comment by malwilley** [comment]
Thanks for confirming! Glad this solution worked for you. Will close this issue but can reopen if we notice any others wanting to use integration tokens to do this.
