### ISSUE TITLE
Inconsistencies in pagination between the event details page and "Related Event" list.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#5668]
The ordering on the "Related Events" does not consistently mirror the ordering of the events when paging through "Older" and "Newer" events when using this control: 
![screenshot 2017-06-30 14 22 00](https://user-images.githubusercontent.com/65315/27754459-85a1c3f2-5d9f-11e7-9bf7-0ac3b00531ca.png)

There are also cases where hitting the "latest event" button (next to "Newer") doesn't actually bring you to the newest event, and you have to click "Newer" until you reach the newest event.

**Comment by benvinegar** [comment]
@tkaemming Can you add any detail to this? Like, is this something trivially fixed? (I'm guessing no, but dare to dream.)

**Comment by mattrobenolt** [comment]
#6156

**Comment by tkaemming** [comment]
https://github.com/getsentry/sentry/blob/c269e6cbb41bf4e22ad4c9fe633d01ea7cb8c549/src/sentry/api/endpoints/event_details.py#L50-L96

I'm not sure if there is a specific reason we didn't create an index on `(group_id, datetime, id)` (other than this is a big table), but I assume there is one otherwise we'd have already done it.

**Comment by benvinegar** [comment]
@mattrobenolt – in that ticket @dcramer suggested there's a way to "solve ordering" without adding this missing precision. Are there other solutions we're not thinking of?

**Comment by mattrobenolt** [comment]
I can't speak for him, but the only other way is with what ted suggested, and we'd have to create a new index on `sentry_message` that also contains the `id` so we can actually sort on it.

**Comment by dcramer** [comment]
I dont remember what I suggested other than what Ted shows above (collect more events, skip what you already know exists).

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
