### ISSUE TITLE
Renaming upload_file_minidump

### ISSUE THREAD

**Issue by DamGouz** [getsentry/sentry#56727]
### Problem Statement

When uploading a minidump, the attachment is always called upload_file_minidump 

### Solution Brainstorm

It would be great if we could somehow provide an alternative name for it 

### Product Area

Unknown

**Comment by jan-auer** [comment]
Hi @DamGouz. Could you please share precisely through which mechanism you're uploading the minidump? 

In multipart/form-data uploads, you can usually specify a file name in addition to the field name, the latter of which needs to be `upload_file_minidump`. When done with curl like in [these docs](https://docs.sentry.io/platforms/native/guides/minidumps/#minidump-integration), this should happen automatically. 

If you generate the multipart request manually, it should look something like this:

```http
--boundary
Content-Disposition: form-data; name="upload_file_minidump"; filename="myminidump.dmp"

MDMP<binary data...>
--boundary--
```

**Comment by DamGouz** [comment]
Thank you. We are uploading it through python using requests and the trick was to actually set:
```
flask.request.files['upload_file_minidump'].name = 'dump.dmp'
```

**Comment by lobsterkatie** [comment]
Great, glad you got it sorted, @DamGouz, and thanks for sharing your solution!
