### ISSUE TITLE
Onboarding Suggestion by Operating System

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#56720]
### Problem Statement

The onboarding today is not optimized to recognize if someone is setting up a project and they are working on Windows or Mac. Things like our android wizard which is available via BREW do not natively work on windows machines. 

`brew install getsentry/tools/sentry-wizard && sentry-wizard -i android`

### Solution Brainstorm

There should be a toggle view of different onboarding steps whether a user is on a windows or mac machine. Ideally Sentry should detect via the browser and display the best default, but always allow to switch should the user want.

Ideally there is a component available or some kind of model to follow and easily copy pasta over to other platforms which would also benefit from this model

Only need something that easy to re-use as a blue print in other platforms. Let's start with android where it is an almost 50/50 split of users coming from windows or mac.

related: https://github.com/getsentry/sentry/pull/56158

### Product Area

Projects - Project Creation
```[tasklist]
### Tasks
```

**Comment by ale-cota** [comment]
This somehow feels like more of an epic 😬 … it’s easy to determine the users OS and display different instructions based on that, but we’d actually need to produce the differentiated content with help from the SDK teams.

I’d suggest we maybe pick one platform where we know the workflow would be significantly different on MacOS vs. Windows for example and try this out. Can you maybe think of one large enough platform where this would make sense and add it to the issue?

**Comment by romtsn** [comment]
After #57155 is merged, we can default to Manual tab for Windows users

**Comment by romtsn** [comment]
I'd say this is closed by #57155 , we switch to Manual mode for Windows machines by default now.

**Comment by Jesse-Box** [comment]
Do we really care about Windows users who aren't using WSL? I believe it's a bad idea to systematically build out onboarding docs that factor OS
