### ISSUE TITLE
[Request] Make it clearer why a landing page widget is empty

### ISSUE THREAD

**Issue by brentc** [getsentry/sentry#56743]
### Problem Statement

It's unclear why a widget on the performance landing page isn't showing any data. E.g. 

<img width="1219" alt="image" src="https://github.com/getsentry/sentry/assets/466158/8ce37ec6-d600-49f6-953e-9dec6003f556">

This could be because,
1. You have no slow HTTP ops - Happy state! 🎉
2. You don't have any transactions that meet the widget's filters (e.g. tpm > 0.1 for the slow http ops widget above, or the time selector) - 🤷‍♂️ state
3. You're not sending us transactions - Unhappy state ☹️ - something may not be configured properly
4. (...Did I miss any other states?)

Users should be able to understand which of the above state their project is in without having to ask support for help

### Solution Brainstorm

Ideally, differentiate between,
 * we have data within our consideration criteria and "it's all good!" - celebration time!
 * we have data but it's all outside our consideration criteria (and maybe quantify with something like "0 of `nnn`k transactions meet the requirements for this widget (e.g. tpm > 0.1) for this")
 * we have no data now and we stopped seeing it on X date
 * we have no data and we've never seen any (in the last 90 days?)

### Product Area

Performance

**Comment by alexjillard** [comment]
Closing as stale - Empty states have been updated throughout performance to better indicate why the empty state is occuring.
