### ISSUE TITLE
Clicking Resolve on multiple items is triggering Ignore confirmation dialog

### ISSUE THREAD

**Issue by hkdobrev** [getsentry/sentry#5675]
When I click on the *Resolve button* to resolve things in bulk, I get the confirmation dialogue for the *Ignore* action

> Sentry version: 8.18.0.dev0 hosted on sentry.io

Exact steps to reproduce:
1. Search for unresolved issues and a query term. E.g. ["is:unresolved timeout"](https://sentry.io/org/project/?query=is%3Aunresolved+timeout).
2. Click the select all checkbox at the top to select all issues found.
3. Click the Resolve button.

Expected result: Resolve the selected issues or get a confirmation dialogue for resolving.

Actual result: Getting a confirmation dialogue for the ignore action.

Button clicked:
![image](https://user-images.githubusercontent.com/506129/27837642-4d00b4cc-60dd-11e7-961b-f75f687a618c.png)

Resulting modal:

![image](https://user-images.githubusercontent.com/506129/27837678-815e5b8e-60dd-11e7-8938-0fdf908e0ba1.png)

**Comment by mattrobenolt** [comment]
This was fixed yesterday with https://github.com/getsentry/sentry/pull/5672
