### ISSUE TITLE
[cleanup] Replace int enums with string enums

### ISSUE THREAD

**Issue by snigdhas** [getsentry/sentry#56801]
- [ ] Replace `NotificationSettingTypes` with `NotificationSettingEnum` 
    - Convert values as needed to allow Notification instances to accept `NotificationSettingEnum` 
- [ ] Replace `NotificationSettingOptionValues` with `NotificationSettingsOptionEnum`
- [ ] Partially replace `ExternalProviders` with `ExternalProviderEnum`
    - We should leave it as-is outside of notifications

**Comment by ryuusama09** [comment]
I would like to tackle this issue !
