### ISSUE TITLE
Bun Project Creation

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#56856]
### Problem Statement

For users setting up a Bun with Sentry there is no existing paltform to point users down the right path.

### Solution Brainstorm

For users setting up a Bun project with Sentry there should be a respective platform type, under browser?

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/pull/56913
- [ ] https://github.com/getsentry/sentry/pull/56928
```

### Product Area

Projects - Project Creation

**Comment by AbhiPrasad** [comment]
I can take a look at this - @matejminar are there any docs anywhere on the process involved to add a new platform w/ the news onboarding docs format?

**Comment by smeubank** [comment]
> I can take a look at this - @matejminar are there any docs anywhere on the process involved to add a new platform w/ the news onboarding docs format?

https://develop.sentry.dev/frontend/working-on-getting-started-docs/

**Comment by matejminar** [comment]
Yep, that's the one. @AbhiPrasad If something is out of date or not clear as you follow those instructions, please let me know so that we can improve it 🙏
