### ISSUE TITLE
Add weekly digest explanation to docs

### ISSUE THREAD

**Issue by ehfeng** [getsentry/sentry#5685]
Sentry [docs on notifications](https://docs.sentry.io/learn/notifications/) currently describe our error alert and workflow emails, but do not document the weekly digests.

Would be nice to add docs for weekly digest (it sends once a week on Monday, noon UTC).

**Comment by BYK** [comment]
You asked and we delivered: https://docs.sentry.io/product/alerts-notifications/alert-settings/#digests (yes took a while 😁 )
