### ISSUE TITLE
API to export performance data

### ISSUE THREAD

**Issue by gid-sentry** [getsentry/sentry#56869]
### Problem Statement

Many of our customers like using external visualization tools to look at data generated by Sentry - today we offer webhooks integration support as well as APIs to be able to retrieve error data. Parity for performance data would be helpful too

### Solution Brainstorm

https://getsentry.atlassian.net/browse/FEEDBACK-1945

### Product Area

APIs

**Comment by sentaur-athena** [comment]
We started working on expanding our stats APIs and performance data sounds like another similar usecase. Tagging @Dhrumil-Sentry to figure out prioritization in the backlog.

**Comment by Dhrumil-Sentry** [comment]
We have no plans to work on an API to export raw tracing data at this time
