### ISSUE TITLE
Add "raw" toggle to extra data (or any rich rendered field)

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#5689]
We need to be able to provide users an easy way to copy/paste values that appear in the `extra` interface (and other rich rendered fields). It might need to be per-field.

Example of when this is difficult:

![](http://i.imgur.com/1XYqRD3.png)

As commented on the forums: https://forum.sentry.io/t/extra-data-in-raw-format/1873

**Comment by sabrehagen** [comment]
Easy and quick to implement - very useful for users.
