### ISSUE TITLE
Update config.yml defaults and the documentation to match what is really supported

### ISSUE THREAD

**Issue by CGenie** [getsentry/sentry#5690]
Hello,
The newest sentry release (https://github.com/getsentry/sentry/releases/tag/8.18.0) has this line:

> Add a new option (`auth.allow-registration`) for determining whether registration
is allowed on an installation.

As I understand this is supported via `config.yml` file? Can the default `config.yml` file be updated to include all available settings:

https://github.com/getsentry/sentry/blob/8.18.0/src/sentry/data/config/config.yml.default

I can see that some others seem supported there as well:

https://github.com/getsentry/sentry/blob/ec22c7dfef5800c438ae69da628edb970686a076/src/sentry/static/sentry/app/views/adminSettings.jsx#L10-L18

This isn't mentioned in https://docs.sentry.io/server/config/ as well.

**Comment by dcramer** [comment]
@CGenie its not updated in docs, you're right, but you *can* configure it via the UI

**Comment by CGenie** [comment]
OK, it's just I prefer to have all settings done via `config.yml` actually because I want to manage Sentry via SaltStack completely. It's really helpful to have a default `config.yml` file with all options listed there :) Thanks for the quick response BTW.

**Comment by BYK** [comment]
You asked we delivered (years later): https://github.com/getsentry/onpremise/blob/master/sentry/config.example.yml
