### ISSUE TITLE
Delete event via sentry website

### ISSUE THREAD

**Issue by mgarbade** [getsentry/sentry#56917]
### Problem Statement

I use sentry to collect app feedback from my users. However, while setting up / debugging the functionality, I send some test messages / events. 

How can I manually delete these events via the sentry website, such that my data does not get messed up?

### Product Area

User Feedback

**Comment by JLuse** [comment]
@mgarbade you would need to delete the events associated issue in order to have it removed. Currently, it is not possible to delete individual events. Please reference our documentation for more information: https://docs.sentry.io/product/issues/states-triage/#delete
