### ISSUE TITLE
[BE][FE] Evaluate tag cardinality to guard grouping in widgets

### ISSUE THREAD

**Issue by jernejstrasner** [getsentry/sentry#56930]
We don't want people to group-by high-cardinality tags (eg. ids).

At widget creation time check how many tags exist in the past 10-14 days or so. If beyond a certain threshold we wouldn't allow creation (for new widgets at least).
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/57124
```

**Comment by armenzg** [comment]
The frontend portion of (https://github.com/orgs/getsentry/projects/156/views/2?pane=issue&itemId=43135418), we need to indicate that a widget has been blocked so the lack of data isn't alarming to AM1 users that have had their widgets blocked.

**Comment by ale-cota** [comment]
No longer relevant.
