### ISSUE TITLE
Unable to find a mri reverse mapping for 'c:transactions/count_per_root_project@none'.

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#56945]
https://sentry.sentry.io/api/0/organizations/sentry/metrics/data/?field=sum%28c%3Atransactions%2Fcount_per_root_project%40none%29&interval=5m&per_page=20&project=1&query=&statsPeriod=24h&useCase=transactions

**Comment by iambriccardo** [comment]
The solution is to add the query parameter `allowPrivate` set to `true`. This will allow querying metrics with the mri.
