### ISSUE TITLE
Switch license to Apache 2

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#5698]
Let's do it.

**Comment by dcramer** [comment]
Need to confirm the recent React concerns won't affect us.

**Comment by dcramer** [comment]
https://github.com/facebook/react/issues/10191

**Comment by dcramer** [comment]
So one concern, and I'm not sure if avoidable, we need to add license headers to files to be correct via Apache.

**Comment by dcramer** [comment]
https://github.com/projectcalico/felix/blob/master/git-hooks/pre-commit

https://github.com/NitorCreations/license-maintainer

**Comment by dcramer** [comment]
Aside once we fully resolve this, let's plan to transition all SDKs and open source work from Sentry to the same structure. I dont THINK there will be any concerns from upsteam users on those, but we will be confirming with legal advisor first, and might offer dual license options.

**Comment by janl** [comment]
Just curious, what’s the goal here? You’re using a standard 3-clause BSD license afaict, which is very permissive already and you don’t have the patents addition that Facebook added to react.

The react story thus is unrelated.

As for license headers, that’s not an ASL2 requirement, just ASF policy for its own projects. Were you too witch to ASL2, all you need is copying the license text into your `LICENSE` file.

**Comment by dcramer** [comment]
@janl good to know (re: LICENSE file). My concerns were more around we're not actually declaring who the copyright holder(s) are anywhere given the standard Apache text doesnt include anything.

Our goal is a more universally understood license with potential future protections. Given that Sentry's a growing business, it's possible we may want/need to take advantage of the patents protections Apache offers (down the road), as well as having access to the CLA (though we may never use it). Apache is also the most understand on the legal side, and its something we've more or less standardized on in newer projects for quite a while.

(Aside we had talked about the React bit internally, and that was the same conclusion we came to, as it was just a misunderstanding)

**Comment by janl** [comment]
@dcramer that’s all well thought out, keep going :) #asfmemberout

**Comment by EvanPurkhiser** [comment]
@BYK can we close this?

**Comment by BYK** [comment]
@EvanPurkhiser we haven't switched the license yet :)
