### ISSUE TITLE
Fingerprint rules not following Discover syntax

### ISSUE THREAD

**Issue by julianCast** [getsentry/sentry#57008]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Using this syntax in Discover works:
```tsx
(message:"insertBefore" OR message:"removeChild" OR message:"object can not be found") and tags[boundary_translation_error]:True 
```
<img width="998" alt="Screenshot 2023-09-27 at 10 59 15" src="https://github.com/getsentry/sentry/assets/559677/f8eda116-9a6c-4a40-a32e-3ae579263e04">

But I'm unable to use it as fingerprint rule:

<img width="1009" alt="Screenshot 2023-09-27 at 10 59 46" src="https://github.com/getsentry/sentry/assets/559677/934b4a8b-2c73-4676-98bf-98f17ab5488e">

According to the [Fingerprint Documentation](https://docs.sentry.io/product/data-management-settings/event-grouping/fingerprint-rules/) should be posible:

> The syntax follows the [syntax](https://docs.sentry.io/product/sentry-basics/search/#syntax) from Discover queries. If you want to negate the match, prefix the expression with an exclamation mark (!).

What am I doing wrong? Thank you!

### Expected Result

Not syntax rule errors.

### Actual Result

Syntax rule errors.

### Product Area

Settings - Projects

**Comment by scefali** [comment]
I'm having some folks take a look, at first glance says this might be hard or impossible to do

**Comment by julianCast** [comment]
> I'm having some folks take a look, at first glance says this might be hard or impossible to do

Thanks! The only way I've figured out how to do it is from my codebase (adding the fingerprint conditionally using Sentry library API). It's fine, I was just wondering if everything could be handled from the Sentry admin panel, but as you said, I don't think so.

So:
Basic ruling      => Sentry panel
Conditional ruling => Sentry lib API

**Comment by jjbayer** [comment]
Good catch, proposed to update the docs to clarify that the syntax is different: https://github.com/getsentry/sentry-docs/pull/8094

**Comment by lobsterkatie** [comment]
Closing this as the documentation has now been updated.
