### ISSUE TITLE
MS Teams Webhook: There was an internal error with the Plugin, Summary or Text is required

### ISSUE THREAD

**Issue by nfeltrin-dkb** [getsentry/sentry#57021]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a Webhook in an MS Teams channel
2. Configure an project to send alerts through it (legacy Webhooks plugin)
3. Send a test notification (or even a real one, most likely)

### Expected Result

 * A test notification appears in the MSTeams channel linked to the incoming Webhook

### Actual Result

* No notification appears in the MSTeams channel linked to the incoming webhook
* The Sentry interface shows the error "There was an internal error with the Plugin, Summary or Text is required."

This has already been reported in https://github.com/getsentry/sentry/issues/55752 and I understand that new integration is considered the way forward. Unfortunately this requires more permissions in MSTeams that my organization is comfortable granting at the moment, so having the fallback to "simple" webhooks would be great.

Could you consider re-evaluating your decision and investigate how to get webhooks notifications to work with MSTeams?

### Product Area

Alerts

**Comment by Dhrumil-Sentry** [comment]
@nfeltrin-dkb Have you looked at creating an [internal integration](https://docs.sentry.io/product/integrations/integration-platform/internal-integration?original_referrer=https%3A%2F%2Fwww.google.com%2F)?

 You can setup a webhook here and send alerts to that webhook, you would not need to use the MS Teams integrations either

**Comment by nfeltrin-dkb** [comment]
@Dhrumil-Sentry thanks for your reply. I have not tried that, because setting up internal integrations require org-wide permissions (which I do not have). I will definitely pass it forward to someone who does, and report here how it goes.

On the other hand, I think it would be generally desirable to provide a way for Team Admins to be able to configure notification methods for their teams without requiring the Owner role :)

**Comment by Dhrumil-Sentry** [comment]
> the webhook payload would follow the [issue alert](https://docs.sentry.io/product/integrations/integration-platform/webhooks/issue-alerts/) or [metrics alert](https://docs.sentry.io/product/integrations/integration-platform/webhooks/metric-alerts/) schema, and therefore needs to be sent to a third-party/self-hosted/in-house-built service to convert that to an MS Teams payload?

Your understanding is correct here. We don't have documented examples for this but several customers host their own webhooks server to listen to these webhooks and route them according to their custom needs

**Comment by iamrajjoshi** [comment]
Unfortunately, we don't support plugins, we recommend to use the new integration.
