### ISSUE TITLE
Org auth token can contain `url=null`

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry#57120]
In self-hosted or local Sentry the url is null because obvioulsly the instance can't be aware of it's own location.

Potential solutions:
- Show a warning on the org auth token page about this and provide steps to fix
- Adjust all of our clients (cli, bundler-plugins, ...) to properly handle this case.

---

In my (a bit more radical opinion), org auth tokens probably shouldn't contain anything that isn't contained within the Sentry instance itself. Everything that is not contained, like `url` can easily drift away from reality, for example when you move the domain under which you host sentry.

**Comment by vladistan** [comment]
Have the same problem,  didn't have it a year ago on an older sentry install

**Comment by lforst** [comment]
Fixed by https://github.com/getsentry/sentry/pull/57123
