### ISSUE TITLE
Update query for sessions

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#57121]
We query sum(sentry.sessions.session) to get the total session count, but that [maps to SessionMRI.SESSION](https://github.com/getsentry/sentry/blob/ebd28c8c3e37274ec3fe5207fcbbc939ceb8101f/src/sentry/snuba/metrics/naming_layer/mapping.py#L33), which is an internal metric that double-counts crashed sessions and should therefore not be used by the product. Instead, we should query session.all to get the correct number of total sessions.

Relates to: https://github.com/getsentry/sentry/issues/54703

**Comment by brentc** [comment]
We'll need to look into dashboards and see how this is working to figure out how complicated the fix might be
