### ISSUE TITLE
Update Project Details page to query metrics

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#57122]
**Problem**: there is difference between how these metrics are shown in the Project Details page vs. Dashboards, because the first one uses an old sessions API and a lot of calculations are done on the front-end, while the second actually uses the metrics API. To make sure they align perfectly, we’d need to update the Project Details page to use metrics as well. Related issue: https://github.com/getsentry/sentry/issues/54703

**Comment by ArthurKnaus** [comment]
@ale-cota I checked it together with @obostjancic. The only issues we found are differences in how we round the values. (see screenshot)
Let's discuss this issue again. Maybe we missed something.

![image](https://github.com/getsentry/sentry/assets/7033940/8021e69a-24f0-4bd9-bbbf-ba05a8bc4ca4)

**Comment by matejminar** [comment]
We still want to continue using sessions API where it makes sense. It's just a wrapper around metrics API with a few session-related niceties. Answers from those two APIs should be equal. What we'll do instead is change the project details page to not calculate the crash-free rate on the frontend but request that field from sessions API (it is now supported there).
This work will be tracked as part of this customer issue: https://github.com/getsentry/sentry/issues/58396
