### ISSUE TITLE
Dashboard: Actions on all selected events only apply to first 25 events

### ISSUE THREAD

**Issue by jeffrey-xiao** [getsentry/sentry#5713]
Reproduction steps:
1) Do a custom search on events
2) Click the checkbox at the top left corner and choose `Select all issues matching this search query.`
3) Do an action on all selected events (E.G. resolve).
4) The popup dialogue box shows `Are you sure you want to resolve 25 issues`.
5) Running the custom search again shows events that weren't resolved.

Using Sentry 8.19.0.dev0

**Comment by dcramer** [comment]
@jeffrey-xiao if this is onpremise, can you confirm the API payload thats sent to the server?

**Comment by jeffrey-xiao** [comment]
This is not on-premise.

**Comment by FdezRomero** [comment]
@dcramer I'm experiencing the same issue, using Sentry 8.18.0 on-premise.

The request being made is:

```
PUT https://sentry.mydomain.com/api/0/projects/myorganization/myproject/issues/?query=is%3Aunresolved
```

Request payload:
```
{status: "resolved"}
```

Response (200):
```
{"status": "resolved", "statusDetails": {}}
```

I'm not sure how many issues are actually being marked as resolved, but definitely not all of them. I hope it helps!

**Comment by dcramer** [comment]
There's a hard limit of 1,000 items that it will bulk apply to. I'm not sure there's a bug other than the user's expectation is it should "apply to all no matter how many that is", and we dont plan to implement that at this time.

**Comment by FdezRomero** [comment]
@dcramer Understood. Then I suggest correcting the message so it's clear that it will only apply to 1,000 items. Current the confirmation prompt says 25, regardless of selecting all from the query or not, which is misleading.

**Comment by dcramer** [comment]
https://github.com/getsentry/sentry/issues/5840
