### ISSUE TITLE
Modify issue and metric alert rule update methods so that only submitted fields are updated

### ISSUE THREAD

**Issue by isabellaenriquez** [getsentry/sentry#57156]
Now that `ProjectRuleDetailsEndpoint` and `OrganizationAlertRuleDetailsEndpoint` are public APIs, their PUT methods should be updated so that it only saves the fields that are submitted in the request body, rather than requiring the user to submitted the data from the original rule they want to keep.

The documentation for the endpoints should also be updated to clarify the change, and the required fields should be updated.

**Comment by isabellaenriquez** [comment]
It turns out the serializers used in both methods set `partial=True`. 

`OrganizationAlertRuleDetailsEndpoint` should work as expected and only updated modified fields. Thus, the docs for this endpoint need to be updated, with the required body params made not required.

`ProjectAlertRuleDetailsEndpoint` requires a little more tweaking. After the serializer is validated, `name`, `actionMatch`, and `frequency` are attained for `kwargs` in a way that assumes that those fields were updated. Thus, this results in key errors even if a user makes a valid PUT request. These should be changed to use `.get()`. Once that is done, the docs can be updated as well.

We should also add tests for testing that partial updates work and don't modify any fields that weren't passed in.

**Comment by mikejihbe** [comment]
These endpoints are going to be replaced soon. @saponifi3d FYI the new endpoints should fix this.
