### ISSUE TITLE
Raven test sends message but Sentry responds with API Error

### ISSUE THREAD

**Issue by junem-ingenuity** [getsentry/sentry#5716]
I installed raven==6.1.0 and tried sending a test event by running 

>python manage.py raven test -v 3

the result was
`Sending a test message... DEBUG 2017-07-13 13:20:44,882 base 31044 140177710491392 Sending message of length 3419 to http://sentry.ingenuity.ph/api/25/store/
Event ID was 'c2b339d7e7c44e3eaaee6b9a35761449'
ERROR 2017-07-13 13:20:46,016 base 31044 140177506739968 Sentry responded with an API error: APIError(No JSON data was found)
ERROR 2017-07-13 13:20:46,016 base 31044 140177506739968 [u'This is a test message generated using ``raven test``']`

my Sentry server version is 8.8.0

**Comment by dcramer** [comment]
I'm closing this out as Sentry 8.8 is ancient and not supported.

**Comment by saviour123** [comment]
@dcramer I am having same issue- my sentry 8.10. Do you think its the sentry version?/

**Comment by saytik** [comment]
sentry 9 
raven==6.9.0
Python 2.7.11

 python manage.py  raven  test  --traceback 
lib/python2.7/site-packages/sorl/thumbnail/helpers.py:5: DeprecationWarning: django.utils.simplejson is deprecated; use json instead.
  from django.utils import simplejson

Client configuration:
  base_url       : http://sentryall
  project        : 21
  public_key     : 52eb9f528d527901a6d52c
  secret_key     : f7544272da85db5a74b8b

Sending a test message... Event ID was '9be155397ae0df34b33'
ERROR 2018-09-19 17:43:52,070 Sentry responded with an API error: APIError(No JSON data was found)
ERROR 2018-09-19 17:43:52,070 [u'This is a test message generated using ``raven test``']

**Comment by saviour123** [comment]
For me, it happens to be sentry version error. After updating to the latest version(v9) it solve the problem. I tore down the old and  build a new one from scratch, its working well.
