### ISSUE TITLE
Dashboard fails to load some widgets due to 429 - throttling 15 req/sec.

### ISSUE THREAD

**Issue by realkosty** [getsentry/sentry#57173]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a new dashboard
2. Add 30 widgets of type Big Number and with `count()` as metric. Modify each widget by filtering it with any nonexistent tag and a unique value (to bust the cache), e.g. `mytag:1` 
3. [or alternatively open customer's dashboard from linked Jira ticket]
4. Reload dashboard. 

### Expected Result

All widgets load successfully and show some number (0, if using steps from [2])

### Actual Result

Some widgets fail to load (see screenshot)
<img width="539" alt="Screenshot 2023-09-28 at 2 50 17 PM" src="https://github.com/getsentry/sentry/assets/490201/12d7cac6-ec22-4fc5-8bae-44b532dcbf11">

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1951) by [Unito](https://www.unito.io)

**Comment by udameli** [comment]
Hi @realkosty,

We're looking into this issue and will try to resolve it soon!

**Comment by realkosty** [comment]
Excellent! Thanks for the update

**Comment by realkosty** [comment]
We just had another enterprise customer complain about this today

**Comment by udameli** [comment]
Hi @realkosty, I bumped up the rate limit so this issue should be less common

**Comment by realkosty** [comment]
@udameli thank you!!
