### ISSUE TITLE
Loader script for Browser JavaScript has mismatched quotation marks which makes copying and pasting difficult

### ISSUE THREAD

**Issue by whitep4nth3r** [getsentry/sentry#57198]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a new Browser JavaScript project
2. Go to Settings > Client Keys
3. Copy the loader script manually by selecting and using CMD/CTRL + C or using the copy button provided
4. Paste the code in a JavaScript file inside single quotes, and you need to change the singles quotes around the `src` attribute to double quotes in order for the code to be valid in some cases (e.g inside single or double quotes).

### Expected Result

Quotes in the loader script that users copy and paste using the button or manually should match.

E.g. the loader script should either be provided as:

```html
<script src="https://js.sentry-cdn.com/....min.js" crossorigin="anonymous"></script>
```
or
```html
<script src='https://js.sentry-cdn.com/....min.js' crossorigin='anonymous'></script>
```

Whilst this is a seemingly tiny issue, I believe it will be a huge quality of life improvement for developers.

### Actual Result

![image](https://github.com/getsentry/sentry/assets/52798353/d1933df0-2d6a-449a-8495-8c7696359498)

### Product Area

Settings

**Comment by AbhiPrasad** [comment]
Thanks for reporting @whitep4nth3r - I'll take a look!

Let's make it double quotes because this matches all of our docs like at https://docs.sentry.io/platforms/javascript/install/loader/
