### ISSUE TITLE
Setting Slack notification channel in spike protection in some cases accept channel id and in some must provide name and id

### ISSUE THREAD

**Issue by saban90** [getsentry/sentry#57194]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I didn't find a specific pattern.
In our case where we are trying to add Spike protection channels for over 500 projects, around 25 of them failed because I didn't provide channel name and id.

Note that I was using the API based on this Github discussion, but also manually I confirmed that it fails to set the notification channel if I don't provide both. It is even worse because in API I don't have option to send both in a POST request.
https://github.com/getsentry/sentry/discussions/44155#discussioncomment-6067158.

Thank you.

EDIT: It seems that when channels have enabled workflows and disabled freetext input, Sentry won't accept Slack channel id, but I must need to enter name and id to set notification channel. It not obvious if this will produce any message in Slack when Spike protection is triggered or Sentry will just fail quietly.
Also, there is no way to test Spike notifications when set up like we have test button when setting alerts in projects.

### Expected Result

Adding slack channel id OR channel name should create a valid notification action.

### Actual Result

For some projects it fails if I don't provide both.

### Product Area

Settings - Spike Protection

**Comment by Dhrumil-Sentry** [comment]
@saban90 We're actively working on publishing API docs for Spike Protection notification actions

> Slack notification channel in spike protection in some cases accept channel id and in some must provide name and id

They are both required and this will be called out in the documentation that will be published soon.

> there is no way to test Spike notifications when set up like we have test button when setting alerts in projects

This is a feature request that I will add to our backlog

**Comment by Dhrumil-Sentry** [comment]
We have clarified that both the channel name and id are required fields for these APIs: https://docs.sentry.io/api/notifications/create-a-spike-protection-notification-action/
