### ISSUE TITLE
Add popup on issue stream over archive button

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#57205]
Some users have mentioned the repositioning of the archive and resolve buttons on the issue stream was unexpected, and they've accidentally used archive when they intended to resolve.  We want to make sure the button placement is called out.

AC:
- Add the following popup to the issue stream, pointing to the archive button. 
![Image](https://github.com/getsentry/sentry/assets/1660873/3b92b03f-a6af-4284-aaf4-ab92ec3c6603)
![Screenshot 2023-09-29 at 8 26 39 AM](https://github.com/getsentry/sentry/assets/1660873/8b54fa19-13fb-474e-b098-57ff8822805d)
- There was a cookie implemented for similar popups for Escalating Issues which limited viewing the other popups to just one time. This popup should use the same cookie.
- The copy on the popup should be updated to reflect that it's being displayed on the stream versus the issue details page (where the screenshot was taken from)

**Comment by lizokm** [comment]
[Headline]
"Archive" is the new "Ignore"
or
Meet the new "Archive" button
[Subhead]
You can now "Archive" an issue instead of ignoring it.
