### ISSUE TITLE
Split Auto-Resolve tasks into separate queue

### ISSUE THREAD

**Issue by NisanthanNanthakumar** [getsentry/sentry#57250]
## Objective:

Auto Resolve tasks have a different instantiation pattern than the other auto-state-transition tasks. This makes it difficult for Ops to generate an auto-scaling strategy. We want to create a new queue and start sending the Auto Resolve tasks there.

This migration will need multiple PRs.

1. Create the new queue and duplicate the task on the new queue with a new name and start dispatching tasks to the new task
2. Switch production to the new queue and drain old one in a separate deployment

Best way to switch from old to new is with an option. When you turn the option on you stop publishing tasks to the old queue and start publishing to the new one. Then you just have to wait the workers for the old queue to have processed all the tasks they had in flight. When they are done the old queue is drained.

Since the queue name is hardcoded in the task code, you will have to create: a new queue, a new task and a new worker

**Comment by mikejihbe** [comment]
AFAIK, no one has thought about this since this ticket was opened. Closing it.
