### ISSUE TITLE
Have a way to programmatically trigger investigation bias without calling endpoint

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#57264]

**Comment by RaduW** [comment]
There is no need to change anything.
There is already a reasonable abstraction in the data model `CustomDynamicSamplingRule` that permits rule creation with relative ease,( basically call `CustomDynamicSamplingRule.updateOrCreate` the only tricky bit is creating the condition. See `sentry/api/endpoints/custom_rules.py` for an example on how to do it.

A notion document on how to do it already exists.

**Comment by RaduW** [comment]
There is no need to change anything.
There is already a reasonable abstraction in the data model CustomDynamicSamplingRule that permits rule creation with relative ease,( basically call CustomDynamicSamplingRule.updateOrCreate the only tricky bit is creating the condition. See sentry/api/endpoints/custom_rules.py for an example on how to do it.

A notion document on how to do it already exists.
