### ISSUE TITLE
Relocating Browser and OS tags

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#57270]
### Problem
The replay details header displays browser and OS information so that people can quickly parse this information without navigating to the Tags tab. However, it takes up a lot of space in the header which could otherwise be used by more actionable insights like dead or rage clicks.
### Acceptance Criteria
- Users can still see which browser and OS was used without navigating to another tab

### Design Solutions
Figma [here](https://www.figma.com/file/krnjQeErB2rU3Uu2UXiora/Specs%3A-Browser-%26-OS-Tags-Relocation?type=design&node-id=0%3A1&mode=design&t=8UPhpg0KzUQLbzK4-1)

#### Concept A

![Image](https://github.com/getsentry/sentry/assets/6508377/05ecfa09-7d8d-4780-ba36-68cb3fe70725)

#### Concept B

![Image](https://github.com/getsentry/sentry/assets/6508377/903324f3-9444-44b9-8915-379dbea8a56a)

**Comment by Jesse-Box** [comment]
Hey @michellewzhang I do think your recent change does solve the acceptance criteria, but I wonder why you didn't follow through with the visual direction specified in Concept A?

**Comment by michellewzhang** [comment]
addressed @Jesse-Box's comment with https://github.com/getsentry/sentry/pull/57572
