### ISSUE TITLE
Create a more flexible key-value row component

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#57272]
### Problem
The current tag component works well when placed in a narrow fixed width container (Sidebar as an example) because the key and value are close to each other. However, the component starts to breakdown visually when used in a main container window, where the container's width can grow indefinitely. 
### Acceptance Criteria    
- The component's default layout is optimised for sidebars
- Using a prop, the component's layout can change for cases when key value pairs are shown in a wide container
- use a prop, the component's font-size can switch from 12px (Default/XS) to 14px (SM)
### Designs
[Figma](https://www.figma.com/file/daVDovN8zTlenkGIz5aqzG/Specs%3A-Tags-component?type=design&node-id=0%3A1&mode=design&t=lbrMIsE90EHf90FX-1)

![Image](https://github.com/getsentry/sentry/assets/6508377/a45ab453-a450-4df0-ac6a-75183eb59560)

**Comment by ryan953** [comment]
this is stale, since then we've gotten new key/value components from the issue-details page and can use them all over the place as needed.
