### ISSUE TITLE
Filter alert queries by custom measurements

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#57274]
**Problem**: People can define custom measurements today and send them together with a transaction. They can see them on the transaction summary and query in Discover/Dashboards, but not use them in alerts today.

**Proposed solution:** Allow customers to filter metric alerts by adding query conditions based on custom measurements. E.g. Alerting on the throughput of transactions that have a custom measurement greater than X. 

Example: Sentry back-end has `measurements.query.num_projects`, [see discover here](https://sentry.sentry.io/discover/homepage/?field=title&field=event.type&field=project&field=timestamp&field=measurements.query.num_projects&id=17639&name=&project=-1&query=has%3Ameasurements.query.num_projects&sort=-timestamp&statsPeriod=7d&topEvents=5&yAxis=count%28%29).

https://github.com/getsentry/sentry/assets/26696515/1eed3fb0-2e5a-4ac9-8db9-5ecedb300a41

**_Note_**: There is a separate use case, where a customer could choose a custom measurement as the main metric to alert upon (potentially extending the existing dropdown), but this is not in the scope of this issue.

This relates to: https://github.com/getsentry/sentry/issues/55159
Rick already worked on a fix spec generation pipeline here: https://github.com/getsentry/sentry/issues/56837

**Comment by Antiinflamatory1** [comment]
yes we need to work it out

**Comment by ale-cota** [comment]
Duplicate
