### ISSUE TITLE
Specify release commits using git commit ranges

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#5728]
Some CI services provide environment variables that indicate a range of commits being deployed/tested/etc. Specifically, TravisCI provides `$TRAVIS_COMMIT_RANGE` (there's an [open issue](https://discuss.circleci.com/t/introspect-commit-range/9878) on CircleCI to provide the same).

It would be very helpful for TravisCI users if they could just pass this range to Sentry and we parsed it out, treated it as `commit`/`lastCommit`.

**Comment by dcramer** [comment]
I think we could provide a reasonable shorthand for it which would be nice.

e.g. ``repos={"name": "foo..bar"}``

**Comment by BYK** [comment]
I think we've addressed this recently.
