### ISSUE TITLE
User ID 1 displayed as sentry@example.com

### ISSUE THREAD

**Issue by cakeandmouse** [getsentry/sentry#5731]
Using sentry-raven 2.5.3.

In the web portal, when I view the Affected Users for a particular issue, a user with ID #1 (set via Raven.user_context(id: current_user.id)) displays as sentry@example.com.

**Comment by dcramer** [comment]
This is from the example JavaScript event that would have been created when you clicked on "view sample" in the installation phase.

**Comment by cakeandmouse** [comment]
I never clicked that. And I see it for both user 1 in development and
production.

**Comment by dcramer** [comment]
It looks like we actually still creating it automatically. It happens once per project. You can remove the sample event and tags will eventually reconcile, but it won't affect any of your other data.

**Comment by cakeandmouse** [comment]
Thanks for the quick response and direction. I'm still learning to navigate
the site, so will need to figure out how to view/delete events and tags.

**Comment by dcramer** [comment]
@cakeandmouse click the "X" on the search bar to clear any filters and there some be some example javascript event. From there you can select it, and under actions there is a "Delete Issues". Alternatively you can find that same action in the toolbar on the issue's details page.
