### ISSUE TITLE
Sort by status should include disabled

### ISSUE THREAD

**Issue by ceorourke** [getsentry/sentry#57339]
Users should be able to click "Status" on the alert rule detail page and sort the results by ones that are disabled. Currently needs designs.

**Comment by ArthurKnaus** [comment]
@ceorourke as the Epic was closed, I assume this can be closed as well?

**Comment by ceorourke** [comment]
@ArthurKnaus thanks for finding this, yeah it can be closed as we don't have disabled alerts.
