### ISSUE TITLE
Dashboard Widget - Percentage does not show on Y-axis when below 1.0%

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#57352]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Dashboard widgets that work with values lower than 1.0% like for instance 0.15 don't cause the Y-axis to rescale so it stays on 0%
![Screenshot 2023-10-03 at 14 21 02](https://github.com/getsentry/sentry/assets/25929053/0734bb78-a40a-4236-88ab-792d4975a7c0)

### Expected Result

I would expect the Y axis to scale automatically

### Actual Result

![Screenshot 2023-10-03 at 14 21 02](https://github.com/getsentry/sentry/assets/25929053/0734bb78-a40a-4236-88ab-792d4975a7c0)

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2069) by [Unito](https://www.unito.io)

**Comment by udameli** [comment]
Hi @Angelodaniel,

Thanks for reporting this. This is definitely a bug with how we're rendering the axis markings. I'll backlog this ticket so we can address this issue 👍
