### ISSUE TITLE
[SPIKE] Verify if there is the need to implement better abstractions around toggleable `errorMessages`

### ISSUE THREAD

**Issue by iambriccardo** [getsentry/sentry#57359]
The `errorMessages` inbound filter expects a list of patterns that are matched against errors to filter them out. Such system has been designed to allow our customers to specify their own error messages to filter out.

Since the introduction of React hydration and chunk load error filters, the system was slightly compromised. In the sense that now the configuration generation merges together the patterns from the user and the two new inbound filters that are defined in the UI.

Besides the fact that such filters have been implemented in a hacky way into the code, there is the need to more closely track outcomes by knowing which error messages belong to which inbound filter.

This ticket aims at researching all dependencies and complexities involved into extending the `errorMessages` filter by allowing sub-filters like:
```json
...
"errorMessages": {
    "default": [
       "patterns": [...]
    ],
    "react-hydration-error": [
       "patterns": [...]
    ],
    "chunk-load-error": [
       "patterns": [...]
    ]
}
...
```

**Comment by matejminar** [comment]
https://github.com/getsentry/sentry/issues/57799
