### ISSUE TITLE
OAuth seeks permissions on all repos with no way to select individually

### ISSUE THREAD

**Issue by phpguru** [getsentry/sentry#5736]
I was just invited to join my organization's Sentry hosted solution. It's in the OAuth flow page 2 where it shows me the repos in my account. I cannot de-select repos. Sentry only needs (and I only give) permission to 1 of my orgs, and I cannot change it, so I cannot OAuth.

![screen shot 2017-07-18 at 5 38 19 pm](https://user-images.githubusercontent.com/798500/28345659-a3d8ddde-6be0-11e7-9f82-d908e2cd880d.png)

**Comment by mattrobenolt** [comment]
This is strictly a limitation of the GitHub APIs. This page is entirely owned by GitHub and not under our control unfortunately. :(

**Comment by phpguru** [comment]
Dang, that seems like a bug on their end :-/

**Comment by joewadcan** [comment]
Hey @mattrobenolt @phpguru - just wanted to let you know GitHub's API now supports more granular scopes (in addition to specific repo selection). The integration needs to be built using the archetype we're calling [GitHub Apps](https://developer.github.com/apps/building-integrations/setting-up-a-new-integration/about-choosing-an-integration-type/#installation-processes-for-integrations) - which is now the preferred method to interact with GitHub's API.
