### ISSUE TITLE
Count discrepancies in the issues details page

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#57361]
For some time, an issue can have differing values for the count.

From my analysis, it seems that we're not updating `times_seen` for the group fully, thus, falling behind. There's prior art around [this](https://github.com/getsentry/sentry/pull/31624).

We should either grab times_seen_pending, fix the problem of the buffer, base the UI on the Snuba values rather than PG.

## Example 1 (issue younger than 90 days)
[This issue](https://sentry.sentry.io/issues/4504164958/?project=1&query=is%3Aunresolved+error.type%3AValueError&referrer=issue-stream&sort=new&statsPeriod=7d&stream_index=3) was created 8 days ago. The top right number shows 44 events, the last 30 days widget shows 48 events (figure 1) and Discover says 48 events with 2 unique users.

[The issues API](https://sentry.sentry.io/api/0/organizations/sentry/issues/4504164958/?collapse=release&collapse=tags&expand=inbox&expand=owners) returns the 44 count and the 24h/30d stats (figure 2).

This is the code that gets the 24h and 30d values.
https://github.com/getsentry/sentry/blob/1698ce0e80d81e274a913e6ca5b109238f45ddfd/src/sentry/api/endpoints/group_details.py#L131-L153

The global count and user count are calculated in this code https://github.com/getsentry/sentry/blob/1698ce0e80d81e274a913e6ca5b109238f45ddfd/src/sentry/api/serializers/models/group.py#L377-L378

From looking at the following code, I believe we use `times_seen` from the group:
https://github.com/getsentry/sentry/blob/1698ce0e80d81e274a913e6ca5b109238f45ddfd/src/sentry/api/serializers/models/group.py#L1146-L1170

I think the root of the problem may be coming from the buffer where we do not count every single event.

Figure 1:
<img width="272" alt="image" src="https://github.com/getsentry/sentry/assets/44410/d88b3ba5-2bd6-4f3e-a0fc-7916339284ef">

Figure 2:
<img width="226" alt="image" src="https://github.com/getsentry/sentry/assets/44410/1521929b-330c-42b7-a3fc-7a0da6c64be8">

## Example 2 (issue older than 90 days)
For instance, [this issue](https://sentry.sentry.io/issues/4205458780/events/?project=1&referrer=issue-stream&statsPeriod=7d&stream_index=2) was created 4 months ago (any events older than 90 days get deleted). The issue details page shows "3 events" (fig. A), and the "all events" tab shows 1 event (fig. B)

Figure A
<img width="133" alt="image" src="https://github.com/getsentry/sentry/assets/44410/27ba061b-752d-45f4-ad52-9a8c28aeb4c5">
Figure B
<img width="755" alt="image" src="https://github.com/getsentry/sentry/assets/44410/ddaf818c-4897-468c-a0a5-98664fafd068">

Evidence from Michi:
> This shows 6 events and 1 user
![image](https://github.com/getsentry/sentry/assets/44410/8d67afa8-8878-4dd3-9aba-7ad234bb9087)
> The details page shows 2 events and "all events" is empty
![image](https://github.com/getsentry/sentry/assets/44410/19111d08-710a-44e7-bd24-f31499ce38cc)

**Comment by jangjodi** [comment]
@wedamija I had the same thought process about the disadvantages of snuba and am currently fetching it from the buffers (`fetch_buffered_group_stats` and `group.times_seen_with_pending`)

**Comment by jangjodi** [comment]
Re-opening this issue, as using the buffer did not fix the count discrepancy.

**Comment by wedamija** [comment]
So it looks like we're failing to increment the count for some % of events. It could either be that we're failing to call buffers, or that buffers is dropping counts. Both are concerning
