### ISSUE TITLE
Ability to rename an issue

### ISSUE THREAD

**Issue by mangini** [getsentry/sentry#57362]
### Problem Statement

Issues sometimes have names that are not descriptive enough. We use several dashboards and custom searches for our oncall team, and it would be great if we have the ability to set an arbitrary name to an issue.

### Solution Brainstorm

A simple “rename” option to the issue title would be enough for our use cases.

### Product Area

Issues

**Comment by jangjodi** [comment]
Thank you for the request @mangini! I've added this to our backlog, but it may not be prioritized for the next quarter or two.

**Comment by therealarkin** [comment]
Thanks! It's not on our roadmap currently, however, this one, is related, so please feel free to vote / +1 that discussion
https://github.com/getsentry/sentry/issues/5572

**Comment by mangini** [comment]
Hey @roggenkemper , can you please link the PR where it was implemented, so we can see when it deploys? Thanks.

**Comment by roggenkemper** [comment]
@mangini sorry for the miscommunication, this was something that we chose not to pursue. if you're interested in a similar idea, feel free to leave your thoughts on the GitHub issue from above. ill correctly mark this as something we chose not to do, instead of complete.
