### ISSUE TITLE
Ability to jump to the issues page with a time filter when clicking on a crash spike in the Overview page

### ISSUE THREAD

**Issue by bsergean** [getsentry/sentry#5738]
At this point we don't have a good workflow when there is a spike in crashes. Those spikes usually relates to a new deploy/release, but sometime new code can trigger old bugs, so we don't really want to look at new crashes, but at all the crashes for that time period.

An idea to help here would be to let users click on one individual time period in the Overview view which already display a nice chart. Right now when we mouse over we can see counter values, but clicking on it (different UI maybe with an explicit action labeled) and jumping to a page would be super useful.

<img width="731" alt="overview page" src="https://user-images.githubusercontent.com/11857745/28379407-65354008-6c68-11e7-894e-85b522cd39ed.png">

**Comment by bsergean** [comment]
I forgot the syntax but the query/filter would be a combination of datetime__gte >= "6AM on July 19th" AND datetime_lower_than "7AM on July 19"

**Comment by bsergean** [comment]
Filter is something like that -> event.timestamp:>=2017-10-20T01:00:00 event.timestamp:<2017-10-20T10:01:00

Today we wished we had this feature once again ...

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
