### ISSUE TITLE
Archived issues still counting towards alert numbers

### ISSUE THREAD

**Issue by masinette** [getsentry/sentry#57397]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Set up an Alert to notify on Issues
2. Change an Issue's state to "Archived" 

### Expected Result

- Alerts should be paused for this Issue

### Actual Result

Alerts are being triggered and are notifying users for Archived Issues.

### Product Area

Issues

**Comment by roggenkemper** [comment]
Could you send an example alert that continues being triggered? Or a screenshot of the conditions of the alert?

**Comment by gileorn** [comment]
So, after discussing the case with support through email of a very basic feature that is not working (and worked previously), I need to keep track of this github issue too and provide all the context from the emails I sent previously? Can you sort all this out on your side without me being involved?
@roggenkemper @masinette

**Comment by ceorourke** [comment]
Our team is working on addressing this - follow [this issue](https://github.com/getsentry/sentry/issues/53110) for updates.
