### ISSUE TITLE
Ignore until occurs X times in Y interval not alerting once threshold is reached

### ISSUE THREAD

**Issue by MeredithAnya** [getsentry/sentry#5742]
Issue was set to be Ignored until it occurs 100 times in 24hrs but under 'Last 24hrs' they saw 238 events in one hour for the same issue and did not get notified/alerted

**Comment by dcramer** [comment]
I just hit an odd behavior when testing this as well:

![screenshot 2017-07-19 15 25 16](https://user-images.githubusercontent.com/23610/28392374-8294ac46-6c96-11e7-8ab6-44af620092a9.png)

**Comment by dcramer** [comment]
I do see a real bug now.

When GroupSnooze is cleared it doesnt actually unresolve the issue.

**Comment by dcramer** [comment]
#thisiswhywewritetests
