### ISSUE TITLE
Link to CRON job definition in Monitor failure issue

### ISSUE THREAD

**Issue by DanielNoord** [getsentry/sentry#57445]
### Problem Statement

Currently when a Monitor failure issue is created there is no easy way to get to the CRON job defintion. This is annoying as that is the only place where the actual issue causing the monitor failure is linked (see also https://github.com/getsentry/sentry/issues/43647 I think).

We can create a webhook based alert in our internal messaging platform for the Monitor failure issue but then there is no clear next step for the developer looking at that issue. We want to define 50+ crons so it would be quite hard for them to find the particular definition of the alert they were looking for.
Can we add a link to the definition in the issue? 

### Solution Brainstorm

It should be as simple as `$PROJECT_NAME/$MONITOR_SLUG`, although I'm probably missing edge cases :sweat_smile: 

### Product Area

Crons

**Comment by gaprl** [comment]
Hey @DanielNoord thank you for the feedback! We agree, having backlinks between issues and our monitors is valuable. We'll prioritize this on our end, and I'll reach back out here when we ship this.

**Comment by DanielNoord** [comment]
Thanks for picking this up so quickly. This was a blocker for us starting to use this feature so nice to see it resolved so quickly <3
