### ISSUE TITLE
Webpack ChunkLoadErrors Filtered out

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#57458]
### Problem Statement

ChunkLoadErrors are not new, but seem to be impacting NextJS devs working with AppDir disproportionately. This leads to a buggy page or just a white page, it seems.

The problem is these errors are not very actionable all the time, and can happen often which simply leads to consuming a lot of Sentry quota. 

As a fix there is now an inbound filter on by default, good for quota, bad for visibilty. Is there way we can ensure users are still alerted to this problem, without killing their quota?

![image](https://github.com/getsentry/sentry-javascript/assets/47563310/5505041c-bd72-4cdf-8dd7-1e3504c23907)

As seen in examples like [this](https://dev.to/ianwalter/fixing-chunkloaderror-3791), Sentry plays an important role in telling developers that this problem exists

### Solution Brainstorm

1. some kind of auto-refund
2. performance issue

### Background

Was surfaced on [twitter](https://twitter.com/viktorsarstrom/status/1707105377328804296) with link to error on NextjS 

https://github.com/vercel/next.js/issues/38507

**Comment by HazAT** [comment]
Besides what @smeubank proposed -

We could try to group all these errors together - explain to users that they should capture the error in their app and refresh the page.
While at the same time pointing them to the inbound filter where they can enable it then in case they don't care to do this.

But since it's a valid error, this approach might maintain trust in Sentry and our reporting.

**Comment by HazAT** [comment]
It could be a new Issue Type - where instead of us showing a Stacktrace, we explain what the error is:

"This error happens when your the users bundle isn't refreshed when you do a new deploy. To fix this capture this error in your application and prompt the user to refresh the page."

**Comment by scefali** [comment]
We also need a grouping rule to ensure that all ChunkLoadErrors get grouped together.

**Comment by scttcper** [comment]
Action items:
- Add a strict grouping rule for these errors
- Messaging with:
  - A description of the error
  - A link to the inbound filter setting for that project
