### ISSUE TITLE
Remove recommendation to lower 100% in prod for tx

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#57453]
**Opportunity**: With Performance at Scale we're encouraging customers to send up to 100% of their traffic also in production whenever possible/there isn't any overhead concern in our docs. This should be the case at least for front-end platforms.

**Proposed solution**: There are still code snippets in our onboarding guides that recommend lowering the sample rate in production. We should remove these to not have inconsistent instructions for the end users.

![Image](https://github.com/getsentry/sentry/assets/26696515/2f97ebac-fcbb-4efe-85eb-d0a10ae83c9a)

**Comment by smeubank** [comment]
https://github.com/search?q=repo%3Agetsentry%2Fsentry+%22reduce+in+production%21%22&type=code

@stephanie-anderson for us to consider changing in all the above locations

**Comment by lforst** [comment]
What is the desired copy here?
