### ISSUE TITLE
accessing repos

### ISSUE THREAD

**Issue by tpham12** [getsentry/sentry#5750]
the application sentry will not allow me to access my repositories

**Comment by DuncanFairley** [comment]
![image](https://user-images.githubusercontent.com/1350420/28631596-a3ae5b06-71e2-11e7-8ab7-cf3b703b162a.png)
When I try to add a repository, I just get a little white box. Is that what you're getting?

Sentry 8.18.0

**Comment by dcramer** [comment]
You need to install the latest sentry-plugins

**Comment by DuncanFairley** [comment]
Well that's helpful.
