### ISSUE TITLE
Code snippets incorrect in JS when using a source map

### ISSUE THREAD

**Issue by scottmessinger** [getsentry/sentry#5751]
The JS code snippets shown by sentry in the Full or App view don't match the method reported in the Raw view. For instance, if the raw view shows the error happened in the `insert` method on line 148, the App/Full view show an entirely different method in the same file. I just enabled source maps so that might be related to the problem. 

Example URL: https://sentry.io/commoncurriculum/v4-frontend/issues/314783758/ (obviously locked to the public, but any sentry support staff and more than welcome to take a look).

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
