### ISSUE TITLE
Rethink group id assignment when merging/unmerging?

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry#57533]
**Background**

In my attempts to reproduce https://github.com/getsentry/sentry/issues/56334, I ran into some pretty counterintuitive, if not outright buggy, behavior with respect to merging and unmerging. Consider the following scenario:

1. A user has a project named `Dogs` and has in their `Dogs` stream two issues, `A` and `B`, at short ids `DOGS-1` and `DOGS-2`, respectively.
2. The user merges these issues. Either `B` has more events than `A` or they have the same number of events, but either way, `A` merges "into" `B`, meaning its events become part of issue `DOGS-2`.
3. An event for `A` comes in, gets filed in the merged group, and that group changes its title to match `A`'s message.
4. The user decides to unmerge the issues. Because the issue is now titled with `A`'s message, it makes sense to them to pull `B` (rather than `A`) "out of" the merged issue. `B`'s events are thus moved to a new issue, with short id `DOGS-3`.

In this scenario, the user started out with two issues, `A` and `B`, and ended with two issues, `A` and `B`. All good, except that in the beginning, `DOGS-2` contained only `B` events, while at the end, `DOGS-2` contains only `A` events. 

Now, users mostly identify issues by their titles, so they might not even notice, or they might notice and be confused, but nothing will have broken. However, consider the scenario where all of the above happens, but in the meantime someone references `B` by using `DOGS-2` (in a PR description, for instance). If that reference doesn't get updated, it's now talking about the wrong issue entirely.

Activity* is another can of worms. When the first merge happens, `A`'s `Activity` records have their group id updated to match `B`'s group id. How then to keep track of which records originally belonged to each group, such that they can be redistributed to the right groups when the unmerge happens? And what of the entry which says "`A` was merged into this group"? If the unmerge happens as described above, that entry now implies that `A` merged into itself (since it's now sitting at short id `DOGS-2`). 

In fact, however unlikely, repeated merging and unmerging can lead to a totally nonsensical Activity tab, such as when `A` and `B`'s corresponding unmerging `Activity` entries ("`B` events split off from this group" and "this group was formed with events taken out of `A`") end up on the same group, even though they're from opposite perspectives. This of course all gets even worse when more than 2 issues are involved, possibly merging and unmerging in different combinations.

*This discussion assumes the activity phrasing has been updated to be clearer and more specific than it currently is, which, if it happens at all, is likely to happen before this issue gets tackled.

**Potential Solutions**

There are a number of things we could change to solve some of all of the above problems, and we'd have to game out the pros and cons of each and which ones would work in which cases, but here are a few off the top of my head:

- When two groups merge, both of their group ids are left behind, and a new group id is used. In other words, groups just _merge_, rather than one group merging "into" another.
- When two groups merge, the left-behind issue is only shadow-deleted, so that it can be shadow-undeleted if the two hashes ever get split back apart.
- `Activity` entries keep track of the hash(es) of the issue for which they were created, so that if necessary they can travel with unmerged hashes into the new group, updating their phrasing as necessary. We also figure out some way to reconcile competing entries when two groups are merged.
- On the issue details page, for events which used to be in `DOGS-1` but are now in `DOGS-2` (the `A` events from above), we list the short id as something like "`DOGS-2` (`DOGS-1` before merge)."

**Comment by mikejihbe** [comment]
2% of merges get unmerged, so I don't think we'll prioritize making this better in the near future. Closing for now
