### ISSUE TITLE
stats_v2 always returns results for the whole hour ignoring start and end parameters

### ISSUE THREAD

**Issue by vanchaxy** [getsentry/sentry#57536]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Make a request to the stats_v2 endpoint. Use an interval less than 1h (e.g. 1m) and specify the start/end time inside this hour. 

E.g:
interval: 1m
start: 2023-10-05T01:30:00
end: 2023-10-05T01:35:00

Link: https://maksym-ivanchenko.sentry.io/api/0/organizations/maksym-ivanchenko/stats_v2/?category=error&end=2023-10-05T01:35:00&field=sum(quantity)&interval=1m&project=4505520723984384&start=2023-10-05T01:30:00

### Expected Result

The endpoint should return 6 results:

2023-10-05T01:30:00
2023-10-05T01:31:00
2023-10-05T01:32:00
2023-10-05T01:33:00
2023-10-05T01:34:00
2023-10-05T01:35:00

### Actual Result

The endpoint returns results for the whole hour inside the specified period. (60 results if an hour is in the past or current minutes result if an hour is still going).

E.g. response from the link above: 
```
{
  "start": "2023-10-05T01:00:00Z",
  "end": "2023-10-05T01:37:00Z",
  "intervals": [
    "2023-10-05T01:00:00Z",
    "2023-10-05T01:01:00Z",
    "2023-10-05T01:02:00Z",
    "2023-10-05T01:03:00Z",
    "2023-10-05T01:04:00Z",
    "2023-10-05T01:05:00Z",
    "2023-10-05T01:06:00Z",
    "2023-10-05T01:07:00Z",
    "2023-10-05T01:08:00Z",
    "2023-10-05T01:09:00Z",
    "2023-10-05T01:10:00Z",
    "2023-10-05T01:11:00Z",
    "2023-10-05T01:12:00Z",
    "2023-10-05T01:13:00Z",
    "2023-10-05T01:14:00Z",
    "2023-10-05T01:15:00Z",
    "2023-10-05T01:16:00Z",
    "2023-10-05T01:17:00Z",
    "2023-10-05T01:18:00Z",
    "2023-10-05T01:19:00Z",
    "2023-10-05T01:20:00Z",
    "2023-10-05T01:21:00Z",
    "2023-10-05T01:22:00Z",
    "2023-10-05T01:23:00Z",
    "2023-10-05T01:24:00Z",
    "2023-10-05T01:25:00Z",
    "2023-10-05T01:26:00Z",
    "2023-10-05T01:27:00Z",
    "2023-10-05T01:28:00Z",
    "2023-10-05T01:29:00Z",
    "2023-10-05T01:30:00Z",
    "2023-10-05T01:31:00Z",
    "2023-10-05T01:32:00Z",
    "2023-10-05T01:33:00Z",
    "2023-10-05T01:34:00Z",
    "2023-10-05T01:35:00Z",
    "2023-10-05T01:36:00Z"
  ],
  "groups": [
    {
      "by": {},
      "totals": {
        "sum(quantity)": 0
      },
      "series": {
        "sum(quantity)": [
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0,
          0
        ]
      }
    }
  ]
}
```

### Product Area

APIs

### Link

https://maksym-ivanchenko.sentry.io/api/0/organizations/maksym-ivanchenko/stats_v2/?category=error&end=2023-10-05T01:35:00&field=sum(quantity)&interval=1m&project=4505520723984384&start=2023-10-05T01:30:00

**Comment by Dhrumil-Sentry** [comment]
@vanchaxy Thanks for raising this issue, we'll investigate this and update here

**Comment by vanchaxy** [comment]
@Dhrumil-Sentry any updates or estimates here?

**Comment by leedongwei** [comment]
We have a group of engineers that are reviewing our APIs for issues. I'll get this on their roadmap next Monday and we'll get back to you on timelines.

**Comment by vanchaxy** [comment]
Looks like this was fixed. The same request now returns 5 results instead of 60. Probably, 2 weeks ago in [this PR](https://github.com/getsentry/sentry/pull/60466).

**Comment by leedongwei** [comment]
Thanks for letting us know!
