### ISSUE TITLE
Alert on n% quota on errors exceeded

### ISSUE THREAD

**Issue by radekwarisch** [getsentry/sentry#57563]
### Problem Statement

Hey Team,
We'd like to setup notification/alert that will warn us if we are like to exceed our quota before month period ends. I have notice there is 80% auto notification: https://docs.sentry.io/product/alerts/notifications/?original_referrer=https%3A%2F%2Fwww.google.com%2F#quota-notifications but this is too late for us. Ideally we would like to be notified on exceeded quota usage weekly (e.g. after 1 week we have exceeded more than 25% therefore alert if hired).

Do we have a ready-to-use option to achieve this goal without custom solution that will communicate with Sentry API? If no, then please advise how to use Sentry API to implement such solution.

Thanks!

### Product Area

Settings - Spend Allocation

**Comment by hubertdeng123** [comment]
Thanks for bringing this up. Will route this to the appropriate team.

**Comment by Dhrumil-Sentry** [comment]
Thanks for this feedback, we'll add it to our backlog. cc @sentrypri

**Comment by brianthi** [comment]
We have built spend notifications that are configurable at 10% increments of usage for both reserved volumes and pay-as-you-go budgets. You can configure the thresholds [here](https://sentry.io/settings/billing/notifications/), and users can turn these on and off for themselves in their [personal notification settings](https://sentry.io/settings/account/notifications/).
