### ISSUE TITLE
Integrate getsentry-ldap-auth

### ISSUE THREAD

**Issue by floqqi** [getsentry/sentry#5757]
Currently I have two instances of Sentry installed at two (completely) different organizations. Both organizations use LDAP as their authentication source of truth. Is there a possibility to integrate [gesentry-ldap-auth](https://github.com/Banno/getsentry-ldap-auth) in the core (or in the [official Docker image](https://hub.docker.com/_/sentry/))? I don't like it to have an extra `Dockerfile` and build it on every update.

**Comment by dcramer** [comment]
I'd rather not do this as getsentry-ldap-auth only supports On-Premise, and bundling features that work for OnPrem and not SaaS (barring basic operations/setup) violates our core missions and increases maintenance burden.

Now, however, if an LDAP backend were to be built using our SSO routines, we'd happily support it. That may be something we do at this point, but its not planned right now.
