### ISSUE TITLE
performance_n_plus_one_db_queries stop being displayed after an indeterminate amount of time

### ISSUE THREAD

**Issue by davidjmemmett** [getsentry/sentry#57582]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

2.21.0

### Steps to Reproduce

1. `docker-compose up -d`
2. Wait a few days
3. No `performance_n_plus_one_db_queries` issues are shown until the Sentry instance is restarted

### Expected Result

`performance_n_plus_one_db_queries` are always available without having to restart Sentry

### Actual Result

I've not been able to determine what's dying/getting backed up. Any tips for where to look would be appreciated.

We've not noticed the issue until today, but as soon as I restart the Sentry instance, we will start receiving events again. 

[sentry_install_logs.txt](https://github.com/getsentry/self-hosted/files/12801611/sentry_install_logs.txt)

**Comment by brentc** [comment]
Let me check with the team to see if there's anything obvious that stands out.

**Comment by davidjmemmett** [comment]
Is there anything I can do to help debug this issue?

**Comment by ceorourke** [comment]
@rjo100 would you be able to help out here?

**Comment by rjo100** [comment]
The only thing I could think of would be maybe the consumer is dying//something else is off with Kafka? Haven't seen anything like this before.

**Comment by davidjmemmett** [comment]
What would I be best monitoring to find out?

**Comment by snigdhas** [comment]
Are there any errors in the internal sentry project? We'd want to make sure consumer is running [here](https://github.com/getsentry/sentry/blob/e4546202138130d9f4240d735357fc1c6e7682c3/src/sentry/runner/commands/run.py#L544)

**Comment by mrduncan** [comment]
I'm going to close this for now given it's age and our lack of ability to repro it - please re-open with additional details if it's still occurring.
