### ISSUE TITLE
Fix typing for `sentry.tasks.groupowner`

### ISSUE THREAD

**Issue by snigdhas** [getsentry/sentry#57599]
Many files related to post-process are skipping type checks. 
* Remove the file from [sentry/pyproject.toml](https://github.com/getsentry/sentry/blob/b7810a9dca4b57afd2858903a6a9ec7ab50cdead/pyproject.toml) 
* Run `mypy sentry.tasks.groupowner` and fix the typing errors

From #55193

**Comment by mrduncan** [comment]
Fixed in #69211
