### ISSUE TITLE
[Epic] Issue Stream Performance

### ISSUE THREAD

**Issue by roggenkemper** [getsentry/sentry#57625]
```[tasklist]
### Saved Search Improvement
- [ ] https://github.com/getsentry/sentry/issues/57853
- [ ] https://github.com/getsentry/sentry/issues/57854
```

```[tasklist]
### Unhandled Flag
- [ ] https://github.com/getsentry/sentry/issues/57844
- [ ] https://github.com/getsentry/sentry/issues/57846
- [ ] https://github.com/getsentry/sentry/issues/57847
- [ ] https://github.com/getsentry/sentry/issues/58389
- [ ] https://github.com/getsentry/sentry/issues/64289
```

```[tasklist]
### Caching Issue Stream
- [ ] https://github.com/getsentry/sentry/issues/57849
- [ ] https://github.com/getsentry/sentry/issues/57850
- [ ] https://github.com/getsentry/sentry/issues/64288
```

**Comment by kir2963** [comment]
- - - - - ![2048.cc-photo_2024-07-18_17-13-01.jpg](https://github.com/user-attachments/assets/c6859827-1084-498c-bca9-61f449e9d3d3)

- @![u[]() bUploading 2048.cc-photo_2024-07-18_17-13-01 (6).jpg …]()

[]()

**Comment by kir2963** [comment]
- - - .eyJyeyJhbGciOiJIUzUxMiJ9b bb2wiOiJST0xFX01FTUJFUiIsInN1YiI6ImtpcmRvYW4iLCJpYXQiOjE3MjE4NDY0MTIsImV4cCI6MTcyNDI2NTYxMn0.vzNxNa-jRBufo8VQWdOhT7GDLR67gsCFg7e1asi7cvMp2Za-lQyPQpupX-BGvEoXmHmM9QeypEkgjSMcULm1gA

**Comment by kir2963** [comment]
- - - -        - - - - - []()   -  .eyJyeyJhbGciOiJIUzUxMiJ9b bb2wiOiJST0xFX01FTUJFUiIsInN1YiI6ImtpcmRvYW4iLCJpYXQiOjE3MjE4NDY0MTIsImV4cCI6MTcyNDI2NTYxMn0.vzNxNa-jRBufo8VQWdOhT7GDLR67gsCFg7e1asi7cvMp2Za-lQyPQpupX-BGvEoXmHmM9QeypEkgjSMcULm1gA

**Comment by kir2963** [comment]
- - - - -  ![2048.cc-photo_2024-07-18_17-13-01 (6).jpg](https://github.com/user-attachments/assets/dcc52e9e-fa51-43bc-84c9-035fff5c0c81)

        - - - - - []()   -  .eyJyeyJhbGciOiJIUzUxMiJ9b bb2wiOiJST0xFX01FTUJFUiIsInN1YiI6ImtpcmRvYW4iLCJpYXQiOjE3MjE4NDY0MTIsIm- V4cCI6MTcyNDI2NTYxMnvzNxNa-jRBhRBufo8VQWdOhT7GDLR67gsCFg7e1asi7cvMp2Za-lQyPQpupX-BGvEoXmHmM9QeypEkgjSMcULm1gA

**Comment by kir2963** [comment]
- - - - -  ![2048.cc-photo_2024-07-18_17-13-01 (6).jpg](https://github.com/user-attachments/assets/dcc52e9e-fa51-43bc-84c9-035fff5c0c81)

        - - - - - []()   -  .eyJyeyJhbGciOiJIUzUxMiJ9b bb2wiOiJST0xFX01FTUJFUiIsInN1YiI6ImtpcmRvYW4iLCJpYXQiOjE3MjE4NDY0MTIsIm- - V4cCI6MTcyNDI2NTYxMnvzNxNa-jRBhRBufo8VQWdOhT7GDLR67gsCFg7e1asi7cvMp2Za-lQyPQpupX-BGvEoXmHmM9QeypEkgjSMcULm1gA
