### ISSUE TITLE
Issue Platform: Schema Validation does not align with Sentry event schema:

### ISSUE THREAD

**Issue by JoshFerge** [getsentry/sentry#57649]
This schema is incorrect/incomplete compared to ingest. I'm not sure what the source of it was, but there are fields missing, and also many fields are incorrect. e.g `name` is a valid property of `user`, but in this schema it is not.

https://github.com/getsentry/sentry/blob/129903f663585acb4c0107f8d8a41f11fac77e2a/src/sentry/issues/json_schemas.py#L3

I also do not understand why we tried to define our own event schema JSON, we already have one generated here:
https://github.com/getsentry/sentry-data-schemas/blob/main/relay/event.schema.json

**Comment by wedamija** [comment]
@JoshFerge Yeah we should probably move to the official schema. We weren't aware of that at the time/weren't sure how to access it.

We should be careful to make sure that this doesn't break any existing incoming data too. Probably need to shadow run it and see if the failure rate increases significantly.
