### ISSUE TITLE
Automatically link short IDs in issue comments.

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#5764]
It'd be nice if these were automatically linked:
 
![screenshot 2017-07-24 16 50 46](https://user-images.githubusercontent.com/65315/28549637-414262a8-7090-11e7-9c29-3b0b79a9b125.png)

Same goes for the comment notification email, but there's no formatting there at all right now. (I thought there might be a ticket for rendering Markdown for HTML emails, but I can't seem to find it?)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
