### ISSUE TITLE
Existing Discord integrations still enabled after org plan change

### ISSUE THREAD

**Issue by 17hogeju** [getsentry/sentry#57684]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Have a Slack and Discord integration enabled
2. Change to a free plan such that all third party integrations should be disabled
3. On the integrations page, Discord is missing a 'reinstall required' alert
4. On the Discord integration itself, It is missing the upgrade plan button and disabled notification dot

### Expected Result

![Image](https://github.com/getsentry/sentry/assets/22582037/a65fdfea-a35b-4c95-8ffd-ba114f5620c0)
![Image](https://github.com/getsentry/sentry/assets/22582037/e5908545-afb6-4228-bfa8-5f9c638183ed)

### Actual Result

![Image](https://github.com/getsentry/sentry/assets/22582037/057cbe47-5e5d-4ab1-a703-b1b38821cdad)
![Image](https://github.com/getsentry/sentry/assets/22582037/c664f184-179d-4b9a-a88c-74c343007992)

### Product Area

Settings - Integrations

**Comment by scttcper** [comment]
punting, there's a job that marks them disabled after a period
