### ISSUE TITLE
[Replay List] List columns overlap when the browser is at a narrow width

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#57682]
**Problem:**

![Image](https://github.com/getsentry/sentry/assets/187460/9ff2187c-2223-415a-b789-7bb0adb41a1c)

**Solution ideas:**
We've had this kind of thing pop up in the past, and back then we added a media query and started hiding columns when the table was too narrow. We could do that again

Alternatively, we could switch this table over to use GridEditable, which should scroll sideways when the table gets too small. also the resizable columns might be a nice addition as well.

**Comment by Jesse-Box** [comment]
We can probably get rid of the browser and OS columns since we only added them to make the replay table "more alive" 

Doesn't solve the problem but it will help a little
