### ISSUE TITLE
PivotalTracker ID search should include hash sign

### ISSUE THREAD

**Issue by sergous** [getsentry/sentry#57704]
### Problem Statement

the default for Pivotal id ref is #186138333 , so it should be searchable including the hash sign by my view point.

https://sentry.zendesk.com/hc/requests/186138333

### Solution Brainstorm

Just add the hash to the search regexp

### Product Area

APIs

**Comment by Kobby-Bawuah** [comment]
Adding a few images to add some context for the user
<img width="643" alt="Снимок экрана 2023-09-27 в 11 54 01 PM" src="https://github.com/getsentry/sentry/assets/89524511/1a4541a4-e2d2-4750-9686-590d7ad5b685">

<img width="633" alt="Снимок экрана 2023-09-27 в 11 54 10 PM" src="https://github.com/getsentry/sentry/assets/89524511/060e084d-f6ec-45a1-a02e-4240d01184a3">

**Comment by Christinarlong** [comment]
Hi, unfortunately we are not supporting plugins anymore. However, we currently provide an [Integration Platform](https://docs.sentry.io/organization/integrations/integration-platform/) to build new integrations on Sentry though and are always taking community contributions.
