### ISSUE TITLE
Malformed Navigation Links in certain Situations

### ISSUE THREAD

**Issue by eviscares** [getsentry/sentry#5774]
Sentry Version: 8.15.0-1
Environment: Debian Jessie, Kernel 3.16, VM on KVM

Behaviour:
Links behind navbar to are set as follows when in Project Settings:
`<a href="[sentry-hostname]/sentry/internal/">Issues</a>`

Links work correctly in other views.

Expected Behaviour:
Link should be given as:
`<a href="/sentry/internal/">Issues</a>`

**Comment by dcramer** [comment]
Its unclear to me what you're referencing, but some links will include the full sentry.url-prefix, while others are explicitly using the router's base (/). There shouldn't be an issues here, as this is the same behavior in sentry.io production.
