### ISSUE TITLE
New platform icons for GraphQL

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#57749]
Hey Team!

We would need some GraphQL related icons for docs. 

We would need the bigger (80) and smaller (20) versions so they can be used here: https://github.com/getsentry/platformicons

Thanks!

Those are the four original Logos:

![Image](https://github.com/getsentry/sentry/assets/202325/2a7af6e5-0a45-4c69-80d5-ed4799cabbc4)
![Image](https://github.com/getsentry/sentry/assets/202325/c44a2739-6568-4c94-af42-dfab1eb545bd)
![Image](https://github.com/getsentry/sentry/assets/202325/dc57e6bb-6567-4c35-932f-6df63c49b503)
![Image](https://github.com/getsentry/sentry/assets/202325/233cdccb-e991-47a2-89da-8a1792a03cd2)

**Comment by Jesse-Box** [comment]
Marking this as done

@antonpirker 
[graphQL.zip](https://github.com/getsentry/sentry/files/12914967/graphQL.zip)

@sentrivana
[python-huey.zip](https://github.com/getsentry/sentry/files/12914988/python-huey.zip)

**Comment by sentrivana** [comment]
@Jesse-Box Thanks for the icons! Looks like Ariadne is missing from the GraphQL bundle, could we get that one, too?

- https://user-images.githubusercontent.com/202325/271982180-c44a2739-6568-4c94-af42-dfab1eb545bd.png
- https://ariadnegraphql.org/

**Comment by Jesse-Box** [comment]
Ah ok, I thought it was apollo that he needed. Will re open the ticket

**Comment by sentrivana** [comment]
TY, looks good!
