### ISSUE TITLE
Show detailed release info on hover for artifact bundles

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#57754]
Show a popup with details about an associated release of an artifact bundles when hovering over it.

We could build a similar solution to what we have in the issue details:

![Image](https://github.com/getsentry/sentry/assets/7033940/a651f133-36a0-4540-89a7-b6845c802d4e)

Additionally, if a 404 error code is returned we should show a fallback, mentioning that the release does not exist in Sentry.
(similar to https://www.figma.com/file/Ieg9z8tLIHuI8viooNRA7c/Specs%3A-Source-Map-Project-Settings-v4?type=design&node-id=448-3500&mode=dev)

**Comment by obostjancic** [comment]
Won't do as support does not consider this as a priority
