### ISSUE TITLE
Update for some small platform icons

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#57750]
Hey Team!

We would need some upate to platform icons for our docs. 

We would need the smaller (20) versions so they can be used here: https://github.com/getsentry/platformicons (the bigger version of the icons are already there)

Thanks! 

Those are the six bigger icons from platformicons:

* `apache-airflow`:
![Image](https://github.com/getsentry/sentry/assets/202325/191b3c45-904a-4499-9449-69a527dd139f)

* `apache-beam`:
![Image](https://github.com/getsentry/sentry/assets/202325/8630f060-500c-4634-9350-342f7b8ad922)

* `apache-spark`: 
![Image](https://github.com/getsentry/sentry/assets/202325/b4553730-547e-444e-83bb-cb8a409f5d60)

* `falcon`:
![Image](https://github.com/getsentry/sentry/assets/202325/2f6bb4ab-90a6-4f5a-8c88-c18323b6b6a5)

* `flask`:
![Image](https://github.com/getsentry/sentry/assets/202325/15ba675b-a21c-4f69-a2b2-ce2bb07c1d72)

* `quart`:
![Image](https://github.com/getsentry/sentry/assets/202325/7b748c7a-9bb7-492c-a372-62edcb158496)

**Comment by Jesse-Box** [comment]
@antonpirker can you update both the 80 and 20 versions? Ive provided both in the zip
[platform icons.zip](https://github.com/getsentry/sentry/files/12917228/platform.icons.zip)

**Comment by antonpirker** [comment]
Will do! Thanks!
