### ISSUE TITLE
Feedback Inheriting Fonts

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#5776]
<img width="819" alt="screenshot 2017-07-26 10 03 49" src="https://user-images.githubusercontent.com/23610/28625294-c59a4bd8-71e9-11e7-809d-444457268fbf.png">

**Comment by sinanargun** [comment]
Hello, can you explain what we would like to solve here?

**Comment by BYK** [comment]
@dcramer is this the feedback form inheriting the fonts from the parent page?
