### ISSUE TITLE
[User Story] Alerting on reports crosses a threshold

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#57773]
## Problem
I can't be notified if a number of bug reports cross a threshold
## Acceptance Criteria
- I want to to be notified when a number of reports in a project and or environment crosses a threshold
- I want to be notified only if reports match one or more key:value pairs (All the smart search would afford)
- I want to set thresholds using: 
  - static values or
  - percentage changes
- I want to set individual thresholds for Critical, Warning and Resolved status
- I want to notify based on status, specifically;
  - Send emails to a team or member
  - Send slack message
  - Send Discord message
  - Send Pagerduty
- I want to name and assign ownership of Alert rule 

## Designs
[Figma](https://www.figma.com/file/ncZFVze3iDXrfAU9iPrn0M/Specs%3A-Alerts-Reports?type=design&node-id=1%3A2594&mode=design&t=chlmfRkNsvaWMjDC-1)
![Image](https://github.com/getsentry/sentry/assets/6508377/7b102117-a06b-4de3-a4a7-c8b1cbc5ac41)

**Comment by jas-kas** [comment]
@Jesse-Box I don't think this type of notification will be a requirement for the MVP/or public beta scheduled for November.

@JoshFerge would you agree?

**Comment by jas-kas** [comment]
Closing as not a product requirement atm
