### ISSUE TITLE
How to get all releases with label starting with string via cli or API?

### ISSUE THREAD

**Issue by filipatbnp** [getsentry/sentry#57801]
### Problem Statement

How to get all releases with label starting with string via cli or API?

### Solution Brainstorm

After reading this https://docs.sentry.io/api/releases/list-an-organizations-releases/ I was trying this
```
curl https://sentry.io/api/0/organizations/{organization_slug}/releases/ \
 -H 'Authorization: Bearer <auth_token>'
 -d '{"query":"X.YZ.*"}'
```
but no good, the response was cryptic:
```
{"version":["This field is required."],"projects":["This field is required."]}
```

### Product Area

APIs

**Comment by schew2381** [comment]
Hi, I believe that curl request has `query` as a body param instead of a query param. If you try this, I believe it should work
```Bash
curl https://sentry.io/api/0/organizations/{organization_slug}/releases/?query=X.YZ.* \
 -H 'Authorization: Bearer <auth_token>'
```

**Comment by filipatbnp** [comment]
almost! wildcard * does not work but without the wildcard and withinn quotes it works:
```
curl "https://sentry.io/api/0/organizations/{organization_slug}/releases/?query=X.YZ." \
 -H 'Authorization: Bearer <auth_token>'
```
