### ISSUE TITLE
Replay playback can lose fidelity (extra spacings, etc)

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#57820]
Example replay: https://sentry.sentry.io/replays/1bf88d854ff34f09a9d0a23ccafbff33/

Playing from the start without scrubbing back/forward works fine. Only when clicking back in time it renders differently:

<img width="1074" alt="image" src="https://github.com/getsentry/team-replay/assets/1633368/0403e3f3-f815-4ef5-bad6-95ecec4956f5">

Normal playback assigns the correct dimensions to svg, but it looks like the replayer is losing the svg dimensions when we scrub forward/backwards.

Closes https://github.com/getsentry/team-replay/issues/233

**Comment by billyvg** [comment]
This will be fixed when we publish [this fix](https://github.com/getsentry/rrweb/pull/117)
