### ISSUE TITLE
Span Waterfall: TTFB listed first and FID removed

### ISSUE THREAD

**Issue by nanoburd** [getsentry/sentry#57824]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Look at any span waterfall in the FE where TTFB, FCP, FP is all bunched up together. Common for serverside rendering like NodeJS. 

### Expected Result

TTFB should be listed first to better match the sequence of these metrics.

FID should also be removed from the span waterfall.

### Actual Result

The webvital pills are listed in alphabetical order.

### Product Area

Performance

**Comment by nanoburd** [comment]
@k-fish any other comments?

**Comment by Dhrumil-Sentry** [comment]
Closing this since it's likely fixed by the new trace view
