### ISSUE TITLE
Source code was not found

### ISSUE THREAD

**Issue by valeryq** [getsentry/sentry#5783]
Sentry doesn't found .map file, but it exists in artifacts for this release.

<img width="1266" alt="2017-07-27 15 27 12" src="https://user-images.githubusercontent.com/7645460/28670209-589e37d6-72e0-11e7-89f2-c547d47d2940.png">
<img width="1571" alt="2017-07-27 15 27 42" src="https://user-images.githubusercontent.com/7645460/28670208-589dff6e-72e0-11e7-846e-25e0ba6a4c36.png">

Sentry: 8.19.0.dev0

**Comment by dcramer** [comment]
Are you certain the release value is the same?

**Comment by valeryq** [comment]
@dcramer yes, of course.
http://dl4.joxi.net/drive/2017/07/27/0010/0315/708923/23/a2445e857d.png
http://dl4.joxi.net/drive/2017/07/27/0010/0315/708923/23/1b5946f41b.png

But it's strange. Right now I have new event from another phone and it's working right, but previous event is still the same `Source code was not found for /main.jsbundle.map`

**Comment by dcramer** [comment]
@valeryq we dont go back and mutate issues after they've been processed. If the sourcemap wasn't available when the event was seen, it's not going to re-apply. I unfortunately am not going to be able to identify any broken behavior here without a lot more details, and my guess this is just confusion in how things work vs an actual bug.

**Comment by valeryq** [comment]
okey, thanks, may be it works with some delay.
