### ISSUE TITLE
Sentry not ignoring 'in_app'=false stack frames when grouping

### ISSUE THREAD

**Issue by jiri-matejka** [getsentry/sentry#5784]
Hello, I have two exceptions (C#, Sentry 8.18 in Docker) that are not grouped but their stack frames differ only in frames with `in_app=false`. According to [this post](https://forum.sentry.io/t/exception-grouping-in-app-stackframe-attribute/2007) such frames should be ignored when grouping.

My assumptions:
- grouping is according to 'stacktrace' not 'raw_stacktrace'
- 'instruction_addr' is not taken into account

JSON for the exceptions:
[1.json.txt](https://github.com/getsentry/sentry/files/1180107/1.json.txt)
[2.json.txt](https://github.com/getsentry/sentry/files/1180106/2.json.txt)

**Comment by dcramer** [comment]
We don't actually ignore it. We create a hash that focuses on app frames but ONLY when app frames make up enough volume of the stacktrace. if e.g. you have one app frame and 100 system frames, the app hash gets discarded.

There might be something we can do to improve the grouping algo in your specific case, but unfortunately the in_app heuristics likely can't change.
