### ISSUE TITLE
@xliee: I still have "The organization you were looking for was not found." issue

### ISSUE THREAD

**Issue by hadifarnoud** [getsentry/sentry#57906]
@xliee A fix was merged:
* https://github.com/getsentry/sentry/pull/53451

Could you please update to the latest commit and let us know it solved the problem?

_Originally posted by @bruno-garcia in https://github.com/getsentry/sentry/issues/53431#issuecomment-1648691959_
            

I did update Sentry to 23.8.0.dev0 7f209c4 and still have the same issue on both new replays and old replays.

**Comment by bruno-garcia** [comment]
@hadifarnoud we had reports that the fix worked: 

https://github.com/getsentry/sentry/issues/53431#issuecomment-1648766410

Any chance this is related to something else? Or the version bump didn't really work out?
Could you update Sentry further to see if it helps, latest is: https://github.com/getsentry/self-hosted/releases/tag/23.9.1

**Comment by hadifarnoud** [comment]
I did update to latest commit and it was fixed. thanks
