### ISSUE TITLE
Issue Escalation overriding Archive status

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#57913]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Ensure Auto-Resolve is set to Off
2. Archive Issue > Until... > issue occurs 10k/day via UI
3. Wait for Issue to reoccur in a newer release

### Expected Result

Issue should remain archived unless 10k occurrences happen in a single day.

### Actual Result

Escalation occurs and overrides the Archived status, re-opening the issue and the linked JIRA ticket.

### Product Area

Issues

**Comment by malwilley** [comment]
After some discussion, this was a misunderstanding with the way archived issues work. When issues are resolved (either manually or through an integration), new events will cause the issue to regress. In other words, resolving an issue removes any escalation logic you have set when you originally archived the issue.
