### ISSUE TITLE
In react-native-sentry setUserContext requires user_id even though docs say email suffices

### ISSUE THREAD

**Issue by scottyantipa** [getsentry/sentry#5792]
The `setUserContext` method is said to only require one piece of identifying information in order for Sentry to properly identify the user.  However, when only passing email, and no user id, Sentry fails to recognize the user.  If both id and email are provided, then Sentry recognizes the user.  I can dm some links to the events in my project if necessary.

Here is where the docs say that only *one* is required: https://docs.sentry.io/learn/context/#capturing-the-user

- react-native-sentry @0.14.15
- Paying for hosted Sentry

**Comment by HazAT** [comment]
Please upgrade to `0.19.0` this has been fixed there.
