### ISSUE TITLE
performance settings not visbile

### ISSUE THREAD

**Issue by eriksobolt** [getsentry/sentry#57921]
### Self-Hosted Version

23.9.1

### CPU Architecture

x96-64

### Docker Version

20.10.17

### Docker Compose Version

20.10.17

### Steps to Reproduce

1. log in
2. navigate to project -> settings -> performance.

### Expected Result

something like this from the docs

![image](https://github.com/getsentry/self-hosted/assets/81301541/f6f140c3-80e5-44ba-a157-d8780cf444ea)

### Actual Result

![image](https://github.com/getsentry/self-hosted/assets/81301541/b138f0fb-536b-43b3-bd31-f9d590f81d9e)

**Comment by k-fish** [comment]
Hey @eriksobolt! We're just looking into that, hopefully we'll have a fix out for self-hosted soon (there is a PR already attached). We'll update once it's in.

**Comment by Abdkhan14** [comment]
Hey @eriksobolt, thank you for reaching out. The detector threshold setting should now be visible in **Project Settings > Performance**.

**Comment by eriksobolt** [comment]
Just want to confirm that it is visible now. I have just updated to 23.10.1 and can see the settings. Thanks a lot
