### ISSUE TITLE
8.18 IntegrityError: IntegrityError('null value in column "organization_id" violates not-null constraint\n

### ISSUE THREAD

**Issue by AlexeySetevoi** [getsentry/sentry#5793]
Name: sentry
Version: 8.18.0
Installation: Local, from pip.
After: Upgrading to 8.18 from 8.12

Visual effect: No issue details, just "There was an error loading data." message in "details" tab.

Jul 31 08:33:02 sentry sentry[169960]: IntegrityError: IntegrityError('null value in column "organization_id" violates not-null constraint\nDETAIL:  Failing row contains (97432, 11, dev, 2017-07-31 08:33:02.537434+00, null).\n',)
Jul 31 08:33:02 sentry sentry[169960]: SQL: INSERT INTO "sentry_environment" ("project_id", "name", "date_added") VALUES (%s, %s, %s) RETURNING "sentry_environment"."id"
Jul 31 08:33:02 sentry sentry[169960]: 08:33:02 [ERROR] celery.worker.job: Task sentry.tasks.store.save_event[4215cdf5-1350-4689-9f2e-1e389a9b7ec3] raised unexpected: IntegrityError('IntegrityError(\'null value in column "organization_id" violates not-null constraint\\nDETAIL:  Failing row contains (97432, 11, dev, 2017-07-31 08:33:02.537434+00, null).\\n\',)\nSQL: INSERT INTO "sentry_environment" ("project_id", "name", "date_added") VALUES (%s, %s, %s) RETURNING "sentry_environment"."id"',) (data={u'hostname': 'celery@sentry', u'name': 'sentry.tasks.store.save_event', u'args': '[]', u'internal': False, u'kwargs': "{'start_time': 1501489982.096902, 'cache_key': 'e:9c8d172961d74488b13100e4fdf8c6b0:11', 'data': None}", u'id': '4215cdf5-1350-4689-9f2e-1e389a9b7ec3'})

**Comment by dcramer** [comment]
You ran ``sentry upgrade`` without issues?

**Comment by AlexeySetevoi** [comment]
Yes, without issues.
And when i had seen this error 1-time, i re-run sentry upgrade - all running ok, no migration apply/no errors happend.
This is not random error for me, i have 2 not crossing sentry-instances - same scenario, same errors.
I can run any debug script, if you need this.

**Comment by mattrobenolt** [comment]
Hey @AlexeySetevoi, did you make sure to upgrade both the workers and web processes? It appears that the workers at least are running an old version of the code. It seems that the schema changes have applied that created the `organization_id` column, but the code isn't acknowledging this as you can tell by the `INSERT` query being generated.

So I'm not exactly sure how or why, but there is definitely a mismatch in code running somewhere.

**Comment by AlexeySetevoi** [comment]
@mattrobenolt, you 100% right.
I install sentry in virtualenv like https://docs.sentry.io/server/installation/ say.
And upgrade like https://docs.sentry.io/server/upgrading/ say.
But between these events a lot of time has passed and I forgot that the installation lives in virtualenv, not system-wide. If strictly follow upgrade doc, we will update the system-wide install, not virtualenv copy. 

As a result - new db schema, old version of code workers/web. Maybe you can add to upgrade doc memo about virtualenv? something like "Warning! If you using our install guide and virtualenv, don't forget enter in virtualenv by using source ../activate, before upgrade".

Thank for your help!
