### ISSUE TITLE
Allow for use of FIDO U2F Security Key 

### ISSUE THREAD

**Issue by kkirsche** [getsentry/sentry#5794]
While on the SaaS option FIDO U2F Security Keys is an allowed method of two-factor authentication, the community open source edition does not seem to support security keys. Would it be possible to expose this feature to on-premise users?

**Comment by tld** [comment]
Just configured a self-hosted version (I think from master), and there is working U2F-support! :-)

**Comment by billyvg** [comment]
U2F is supported for on-premise users. IIRC, it only works if you're using `https`.
