### ISSUE TITLE
sso error login

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#57959]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

https://getsentry.atlassian.net/browse/FEEDBACK-1955

"Currently I have to clear the session cookie to sign in, otherwise I get the error in the attached screenshot. Steps to reproduce:

I log in
My session expires
Then this happens.
"
see screenshot

### Expected Result

successfull login

### Actual Result

<img width="608" alt="image" src="https://github.com/getsentry/sentry/assets/8920574/aebbe6bf-7270-47b9-a1a6-d25f019c3e11">

### Product Area

Unknown

**Comment by Dhrumil-Sentry** [comment]
I am adding this to our backlog for investigation, cc @leedongwei @nhsiehgit

**Comment by leedongwei** [comment]
Closing because the bug is specific to a user's browser.
