### ISSUE TITLE
Consolidate project creation events

### ISSUE THREAD

**Issue by ArthurKnaus** [getsentry/sentry#57967]
- Check if we create project on new account onboarding

- Sent First event with minified stack trace for project vs Sent First Sourcemaps

- created project vs project create

**Comment by ArthurKnaus** [comment]
> Check if we create project on new account onboarding

We create the `Created Project` event in the BE.

> Sent First event with minified stack trace for project vs Sent First Sourcemaps

`Sent first event with minified stack trace for project`
Is sent once for each project if there is a minified stack trace:
```py
# Check if an event contains a minified stack trace (source maps for javascript)
def has_event_minified_stack_trace(event):
    exception_values = get_path(event.data, "exception", "values", filter=True)

    if exception_values:
        for exception_value in exception_values:
            if "stacktrace" in exception_value and "raw_stacktrace" in exception_value:
                return True

    return False
```

`Sent First Sourcemaps`
Is sent once for each organization if there is a sourcemap attached to an event.
```py
def has_sourcemap(event):
    if event.platform not in ("javascript", "node"):
        return False

    for exception in get_path(event.data, "exception", "values", filter=True, default=()):
        for frame in get_path(exception, "stacktrace", "frames", filter=True, default=()):
            if "sourcemap" in (frame.get("data") or ()):
                return True

    return False
```

@smeubank does this cover your needs?
Or do you need a `Send First Sourcemaps For Project` event?

> created project vs project create

`Created project` is always sent by the BE once a project was created.

`Project Create: Project Created` is sent by the FE after successful project creation in the project create flow.
(after click on Create project

![Image](https://github.com/getsentry/sentry/assets/7033940/456cab7f-8dec-49f5-9d36-176f604cf879)

**Comment by smeubank** [comment]
> Created project is always sent by the BE once a project was created.

this is good

> Or do you need a Send First Sourcemaps For Project event?

Yes I would need sent first source maps for project event, also ideally BE event to match the created project

these should also have event attributes to tell me what platform it is for
