### ISSUE TITLE
Deleted org leaves orphan projects

### ISSUE THREAD

**Issue by Meowbeast** [getsentry/sentry#5800]
8.17.0 via docker

I have someone who created an org and then deleted the org...but when I look in the project list, there is an orphan project that I can't access.  I've tried to delete the project via API but I get 403 (odd since I'm a super user and gave all perms to the token).

Any way to manually delete an orphan project?

**Comment by mattrobenolt** [comment]
What makes you think it’s orphaned? And if it is orphaned, how are you seeing it?

Also, it’s eorth noting that deleting an org via the API actually is a soft delete immediately, and follows up with a hard delete 24 hours later so it has the ability to be reverted.

**Comment by Meowbeast** [comment]
Because the org is deleted, so there is no way to access the project since the org slug is invalid, so I would considered that orphaned.

I can see the project via admin panel, but when I click to view, I cannot.  

This did happen less than 24h ago, so if there is a safety window, maybe it will get picked up?

**Comment by mattrobenolt** [comment]
Yeah, my assumption at this point is that it has just been scheduled for deletion.
