### ISSUE TITLE
Add time zone support to searching timestamps

### ISSUE THREAD

**Issue by mcsnolte** [getsentry/sentry#5801]
Currently time zones are not supported when parsing timestamps for searching.  (See https://github.com/getsentry/sentry/commit/188a2a3e8ab9fb213d78338c861413d78ad7c0cd#diff-712e897580b290560333dc7b4bb0dd88R81)

I'd like to offer two suggestions:

1. Allow specifying a time zone suffix
2. Default to the time zone that the user specified in their profile

**Comment by dcramer** [comment]
Probably should tackle this as part of https://github.com/getsentry/sentry/issues/5741

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
