### ISSUE TITLE
Internal integration - Unable to save org:admin permissions 

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#58020]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

**Description**
When attempting to create/save an internal integration with the Organization -> Admin permission, you encounter an "unknown Error"

Steps:
1. Create internal integration
2. Set Organization permissions to Admin
3. Save

### Expected Result

Successfully save integration with org:admin permission

### Actual Result

Encounter "unknown error" when saving integration

### Product Area

Settings - Integrations

**Comment by schew2381** [comment]
Waiting to confirm this fix works once it's deployed

**Comment by thomaswienecke** [comment]
I believe this ticket was created on behalf of my support request. I just tried it again, and although I'm not getting the error anymore and the request is going through, the setting is just not updating now

**Comment by schew2381** [comment]
> I believe this ticket was created on behalf of my support request. I just tried it again, and although I'm not getting the error anymore and the request is going through, the setting is just not updating now

Hey there! Sorry about that, there was another visual bug that I merged a fix for. I tested it and everything seems to be working now 👍
If anything else comes up however, feel free to reopen this issue and ping me
