### ISSUE TITLE
Move User column under 'Related Events'

### ISSUE THREAD

**Issue by MeredithAnya** [getsentry/sentry#5803]
In the case where there is user and the email is provided, you have to go all the way to bottom of the page in order to scroll since it is the last column and usually cutoff.

Might be worth changing where the user column is or easier to scroll.

**Comment by benvinegar** [comment]
Could you paste a screenshot? (Make sure any user data is fake/anonymized.)

**Comment by MeredithAnya** [comment]
had to scroll to the end to see `meredith@gmail.com`
![screen shot 2017-08-08 at 10 39 30 am](https://user-images.githubusercontent.com/15368179/29085990-e3b72b9a-7c25-11e7-907f-e675e75129e0.png)

**Comment by billyvg** [comment]
I think the table needs some love in general, not just the user column. Ideally, we should not have to scroll for any information.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
