### ISSUE TITLE
Support Multiple VictorOps Route Keys Per DSN

### ISSUE THREAD

**Issue by dkhenkin** [getsentry/sentry#58084]
### Problem Statement

Hello, 

Our company has multiple monoliths, with multiple teams contributing to them. We also use VictorOps as our paging platform. Currently, I can only configure a single VictorOps routing key for a project in Sentry, this means I have to route Sentry and VictorOps alerts manually when an issue occurs. 

### Solution Brainstorm

Allow specifying the VictorOps route key in the alert creation instead of it being hardcoded to the entire project

### Product Area

Unknown

**Comment by scttcper** [comment]
Thanks for the suggestion, I've added it to our backlog

**Comment by Christinarlong** [comment]
Hi, unfortunately the Ecosystem team is understaffed and we are not supporting plugins anymore. We currently provide an [Integration Platform](https://docs.sentry.io/organization/integrations/integration-platform/) to build new integrations on Sentry though and are always taking community contributions.
