### ISSUE TITLE
Help Hybrid cloud team test their new installation

### ISSUE THREAD

**Issue by RaduW** [getsentry/sentry#58082]
From Anton on #proj-dynamic-sampling 
Please check the original message for the actual links.

Hi Telemetry Experience team,
As you might’ve heard, the Hybrid Cloud (specifically, the DE region) launch is on the horizon. Soon we’ll be entering the validation phase, meaning that we have some infrastructure in place, but we’ll need to make sure that (ideally) all the Sentry features work as expected. For that, we’ll need some help from pretty much every team, including yours.

What to do

We’ve started [this page]to keep track of important features to validate in the new region(s).
In the first iteration, we’d like to ask you the following:
Add a few (3-4) Sentry features that are relevant to your team to [this section of the doc ]
(“Category: Ingestion” is used for simplicity for now, don’t focus too much on that). Example: “dynamic sampling works in scenario XXX”

Important: please add some instructions on HOW to validate this feature (in “How to check” field, or if the instructions are 
lengthy — in the corresponding feature page). Example: “click on button XXX in project YYY, send an event ZZZ to the project, expected result: XYZ”. The idea is that someone else outside your team should be able to repeat the validation steps at some point in the future. Some existing examples: ....
To reiterate, the idea is to have instructions to do a basic (manual for now) validation of the system, to make sure that everything is connected and configured correctly (like, Relay configuration, getsentry configuration, connectivity between different databases and clusters, etc.)
Thanks in advance, this will help the HC launch a lot! Let me know if something’s unclear and if you have questions :pray: (edited)

**Comment by obostjancic** [comment]
We updated the required notions page
