### ISSUE TITLE
Add option to have integration subscription state changes to Manager role

### ISSUE THREAD

**Issue by chmielsen** [getsentry/sentry#58144]
### Problem Statement

Currently, when integration is disabled, an email is being sent only to the Owner of the integration (see request case #104670).

See similar case:
https://github.com/getsentry/sentry/issues/57261

### Solution Brainstorm

Add an option in notification preferences to have the email about integration being disabled sent to the Managers (and potentially other roles) of the organization as well

### Product Area

Unknown

**Comment by Dhrumil-Sentry** [comment]
Hi @chmielsen Thanks for this feedback, We've added this item to the backlog as well- we'll keep this issue updated

**Comment by Christinarlong** [comment]
Hi currently, the integration disabling feature is disabled so this won't apply anymore.
