### ISSUE TITLE
Issue Tracking doesn't work

### ISSUE THREAD

**Issue by iremakcu** [getsentry/sentry#58145]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Click and see one of the issue
2. Go to Issue Tracking on the right bar
3. Click GitLab Issue button
4. Receive a warning

Warning Content:
Oops! Something went wrong
It looks like you've hit an issue in our client application. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

If you're daring, you may want to try the following:

Give it a few seconds and reload the page.
If all else fails, [contact us](https://github.com/getsentry/sentry/issues/new/choose) with more details.

5. Even if the page is refreshed the problem continue

### Expected Result

opening an issue on GitLab

### Actual Result

A warning appears and issue is not opened on GitLab

### Product Area

Issues

**Comment by ceorourke** [comment]
Hi @iremakcu can you open up the network tab before you click to create a Gitlab issue and provide us with the error id? That would allow us to look up the error in Sentry. From seeing similar issues in the past though, my guess is that you'll need to reinstall the integration to resolve this.

**Comment by trisamsul** [comment]
Hi, I'm having a similar issue when creating GitLab ticket on the issue

<img src="https://github.com/getsentry/sentry/assets/23292910/e647e2c0-afc9-4c8d-b811-6cf21872fa12" width="400px;">

This is the response that I get from Network
```
GET: https://us.sentry.io/api/0/organizations/<organization>/issues/<issue-id>/integrations/<integration-id>/?action=create

{"detail":"Internal Error","errorId":"090cae876b5c4f9da83b8489430af19d"}
```

**Comment by lobsterkatie** [comment]
This is the event in Sentry: https://sentry.sentry.io/issues/4581408189/events/090cae876b5c4f9da83b8489430af19d/

@schew2381 - Should https://github.com/getsentry/sentry/pull/59130 resolve this?

**Comment by schew2381** [comment]
> This is the event in Sentry: https://sentry.sentry.io/issues/4581408189/events/090cae876b5c4f9da83b8489430af19d/
> 
> @schew2381 - Should #59130 resolve this?

Whoops sorry for slow response, that PR looks like it did the trick
