### ISSUE TITLE
Invalid location in source map: (None, None)

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#5814]
![image](https://user-images.githubusercontent.com/2153/28955294-8a24654a-789a-11e7-8b52-12a81a460b85.png)

Seems to occur from an error that points to an HTML document (not a JS file), with no line or column information.

Error:

```json
{
    "errors": [
        {
            "column": null,
            "source": "https://example.com/html/",
            "type": "js_invalid_sourcemap_location",
            "row": null
        }
    ]
}
```

Input stacktrace – no column, line information:

```json
{
    "frames": [
        {
            "abs_path": "https://example.com/html/",
            "in_app": false,
            "module": "<unknown module>",
            "filename": "/html/"
        }
    ]
}
```

Likely triggered [here](https://github.com/getsentry/sentry/blob/master/src/sentry/lang/javascript/processor.py#L653), since there's even comments that suggest line/column information could be missing.

@getsentry/platform

**Comment by benvinegar** [comment]
@mitsuhiko – I took a stab at implementing a fix, but I got buried in the source map processors. It wasn't clear to me how to write an end-to-end test that didn't require mocking out a ton of components. Would really appreciate your help here.

**Comment by Tibingeo** [comment]
Is there any way so that we can suppress or hide these kind of errors ? I get this error `There were 3 errors encountered while processing this event`. But I want to hide these errors as it is working as expected for me.

**Comment by benvinegar** [comment]
@Tibingeo not yet
