### ISSUE TITLE
search string is cut by title

### ISSUE THREAD

**Issue by RomanMIzulin** [getsentry/sentry#58157]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. open all events
2. search by title

### Expected Result

full string under title

### Actual Result

![image](https://github.com/getsentry/sentry/assets/10415843/f48a4c24-a7f0-4080-bfb4-61c4a45dd0c7)

### Product Area

Issues

### Version

23.9.1

**Comment by ceorourke** [comment]
Thanks for the bug report - I've put it in our backlog to tackle.

**Comment by mrduncan** [comment]
@RomanMIzulin I'm going to close this issue given it's age - we recently revamped our search experience so please reopen if you're still seeing problems
