### ISSUE TITLE
Scrambled Senty documentation on hexdocs.pm

### ISSUE THREAD

**Issue by ijdickinson** [getsentry/sentry#58152]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Read the docs on the Sentry for Elixir package on [hexdocs](https://hexdocs.pm/sentry/readme.html#integrations), as linked to from your [GitHub package](https://github.com/getsentry/sentry-elixir)

### Expected Result

Correctly formatted HTML

### Actual Result

Looks like incorrectly transcoded Markdown

![image](https://github.com/getsentry/sentry/assets/63979/4fc30f30-9e81-45f3-b41a-0496f52a87e3)

### Product Area

Other

**Comment by hubertdeng123** [comment]
Thanks for reporting this. Looks like GitHub is giving me a permissioning issue when I try to transfer this issue to sentry-elixir, so I'm going to go ahead and close and open an issue in that repo for this.
