### ISSUE TITLE
Weekly Report Email Link Redirects to Incorrect Page

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry#58171]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

- Receive the weekly report email from Sentry.
- Click on the "View All Transactions" link within the email.
- Observe that the link redirects to the Issues page with an error message.

### Expected Result

When clicking on the "View All Transactions" link in the weekly report email, users should be directed to a page displaying all transactions, as indicated by the link's label.

### Actual Result

Clicking on the "View All Transactions" link in the email redirects users to the Issues page with an error message, even though there are transactions in the organization.

### Product Area

Other

**Comment by ceorourke** [comment]
I can't reproduce - I think I fixed this some time back. Feel free to reopen if there's still a problem.
