### ISSUE TITLE
Monitor schedule being reset

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#58183]
### Problem Statement

Customer reports: Monitor schedule is getting reset on new checkins. I set the schedule to "*/5 * * 5-10 *" and it saves correctly as "every five minutes, between May and October" and updates in the UI, but on the next checkin it resets to just every 5 minutes. The actual cron schedule changes back to "*/5 * * * *" without me doing anything.

### Solution Brainstorm

Customer request to set custom start and end conditions for cron monitors. E.g. they have a couple they only want to run between May 15 and October 15 ish, but using the regular cron syntax they can't do days inside the month, just the months themselves.

### Product Area

Crons

**Comment by bakerkretzmar** [comment]
Reporter here. If you don't support all cron expressions that's fine, but my issue is that `*/5 * * 5-10 *` is parsed correctly in the UI, saves successfully, and is displayed correctly too _until the next checkin_, at which point it's silently discarded and reset to just "every five minutes".

**Comment by davidenwang** [comment]
Sorry for the delayed reply here, and thank you for reporting this issue. How are you instrumenting crons? Are you using upsert functionality to pass in a configuration on each check-in or was this cron monitor manually created?

**Comment by bakerkretzmar** [comment]
Manually created and I just added the `->sentryMonitor()` call to hook them up to scheduled jobs in a Laravel app.

It looks like the default behaviour is to update the monitor based on the scheduled job's generated cron expression, I had no idea that was even possible until digging into the code yesterday but I see it's documented, so my bad I guess. I updated my cron expressions in my app to be exactly what I want in Sentry.

I'd still love to be able to set custom 'between' conditions to only run a check between specific dates or days of the year, but that's kind of a separate feature request. I think you can close this, the basic issue here is fixed. Thanks!

**Comment by evanpurkhiser** [comment]
Thanks for following up @bakerkretzmar

Pinging in @cleptric, the PHP SDK engineer who built out the integration :-)

@cleptric -- wondering if maybe we can show some kind of warning if they're using any of the conditional features of the [Laravel conditions](https://laravel.com/docs/10.x/scheduling#truth-test-constraints) (if that's even possible)

(I'm just assuming you might have been doing this here @bakerkretzmar, I might be wrong!)

---

Also, we're planning to make it clear that a monitor is being upserted and that some fields should not be edited in the UI https://github.com/getsentry/sentry/issues/49264
