### ISSUE TITLE
Don't report Win PDB symbols as "Missing" when loaded

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#58206]
### Problem Statement

User reports:
Issue Screen > Images Loaded > click "Show Details" to list all the modules/symbol files loaded.
Observe that even if you have the symbols loaded, it will report "missing"

When I click "view" it shows all the locations that it (un)successfully downloaded the symbols.
In my case, I can see it downloaded the compressed ".pd_" file and it failed to download the uncompressed ".pdb" version.
This is not an error, but by design since my PDBs are 1GB in size :(

### Solution Brainstorm

User requests that when we ARE able to download symbols for a file, we report it as downloaded and NOT as missing. This is causing confusion for their managers who think Sentry doesn't 

### Product Area

Issues

**Comment by ceorourke** [comment]
Hi @kerenkhatiwada which SDK is this for?

**Comment by JasonDeArte** [comment]
This is with the Unreal Engine.  

Smaller image is the "Images Loaded" view of the Issue view, showing 2 modules that were symbolized, but the one we compiled is "Missing"?
![image](https://github.com/getsentry/sentry/assets/18296201/277c3569-2980-4986-ba89-f5de216e63e3)

Larger image is the "View" (details), showing that it loaded the compressed PDB file (aka PD_) with a green "Ok"
![image](https://github.com/getsentry/sentry/assets/18296201/a0c93c29-810a-4de3-a12e-93037835e5a8)

**Comment by bruno-garcia** [comment]
Indeed looks confusing. But it seems like it's missing `unwind` info, could it be because of that?

![image](https://github.com/getsentry/sentry/assets/1633368/2bbe6c50-19cc-4e40-9a4e-9e911c7754c2)

![image](https://github.com/getsentry/sentry/assets/1633368/37f3aa76-1cd5-47c2-8699-7b380fae63db)

**Comment by MichaelSun48** [comment]
Going to close due to inactivity. Feel free to reopen if this is still an issue!
