### ISSUE TITLE
Tighten relase health rules to filter more specific paths

### ISSUE THREAD

**Issue by RaduW** [getsentry/sentry#58219]
Currently the health-check filter uses the following rules to filter transactions:

```python
HEALTH_CHECK_GLOBS = [
    "*healthcheck*",
    "*healthy*",
    "*live*",
    "*ready*",
    "*heartbeat*",
    "*/health",
    "*/healthz",
    "*/ping",
]
```

This is covers too many strings and transactions for paths like `service-delivery` are captured as health-check paths.

The more problematic patterns seem to be `*live*` and `*ready*` since there are may words that may contain them .

All other patterns will be kept as they are.
`*live*` and `*ready*` are replaced by:
`live`,  `live[z/-]*`, `*[/-]live` , `*[/-]live[z/-]*`
`ready`, `ready[z/-]*`, `*[/-]ready` , `*[/-]ready[z/-]*`

**Note:** these are blobs  there is no way I found to write the above in a more concise way ( there is no `or` and there is no optional character ).... `?` means any character one (and only one) time  and `*` means any char any number of times.

```python
HEALTH_CHECK_GLOBS = [
    "*healthcheck*",
    "*healthy*",
    "live",
    "live[z/-]*",
    "*[/-]live" ,
    "*[/-]live[z/-]*"
    "ready",
    "ready[z/-]*",
    "*[/-]ready" ,
    "*[/-]ready[z/-]*",
    "*heartbeat*",
    "*/health",
    "*/healthz",
    "*/ping",
]
```

**Comment by Lms24** [comment]
I'd argue that `healthy` probably also is problematic. Example: `/food/healthy/snacks` probably isn't an API health check either. Maybe we treat it equally to `/health`?

**Comment by RaduW** [comment]
`healthy` will not pass the current patterns only `/health` and `/healthz`
