### ISSUE TITLE
Often missed_checkin (cron monitoring) of internal project. 

### ISSUE THREAD

**Issue by justlucknb** [getsentry/sentry#58224]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Now we hosted sentry in k8s. Version - Sentry 23.6.1

I had a lot of errors in crons (internal project - sentry). Such as:
Monitor failure: send-ping,check-auth and other (missed_checkin)

How to debug this? Why i get missed_checkin errors?
Which components in sentry are responsible for this?
### Expected Result

No errors in internal crons.

### Actual Result

Now i got this (with ping and another)
![Screenshot_5](https://github.com/getsentry/sentry/assets/49238889/e9f920f7-53fc-4bed-b491-6d3211ad6e61)

### Product Area

Crons

**Comment by gaprl** [comment]
Hey @justlucknb, can you share which SDK version you are using, and share as snippet of the code on how you're instrumenting your job? Thank you

**Comment by justlucknb** [comment]
Hello, now i solved problem) It was a time difference between k8s and another components in sentry (pg,clickhouse).
