### ISSUE TITLE
Attachments from events deleted due to retention prevent new attachments in Issue

### ISSUE THREAD

**Issue by gid-sentry** [getsentry/sentry#58257]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Configure project to save up to X attachments per issue
2. Have events with attachments come in
3. Wait 90+ days

### Expected Result

Events over 90 days old will be removed together with their attachments, and new attachments will be able to be stored.

### Actual Result

Events over 90 days old are removed, however in the attachments tab for an issue their attachments are still present
<img width="763" alt="image" src="https://github.com/getsentry/sentry/assets/108364755/70dd56d8-4c22-4634-b228-a30997e37e90">

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1956) by [Unito](https://www.unito.io)

**Comment by ceorourke** [comment]
@getsentry/ingest team should handle this but there is no label for them

**Comment by iker-barriocanal** [comment]
I believe @getsentry/team-processing handles this part.

**Comment by Swatinem** [comment]
> Events over 90 days old are removed, however in the attachments tab for an issue their attachments are still present

We had a problem that the cleanup job for attachments (they have a retention time of 30 days btw) was not running correctly. We have since restarted that background cleanup task which is slowly working its way through those old attachments and deleting those that are past the retention period.

**Comment by Swatinem** [comment]
We have since caught up with deletion of old attachments, and also implemented improvements to attachment storage to prevent this in the future.
