### ISSUE TITLE
Alert message to assigned people of project

### ISSUE THREAD

**Issue by gzhappysky** [getsentry/sentry#5827]
Alert message to assigned people of project, for example:
Level=Fault alert to people A,B,C by SMS.
Level=Error alert to people E,F,G by WhatsApp.

We implement this feature in my fork repository. 
![dingding](https://user-images.githubusercontent.com/3305041/29012269-e483777c-7b6c-11e7-9d64-8fdc1a0b64e2.png)

If everyone needs this feature, I can submit a PR. 😄

**Comment by kristajg** [comment]
@gzhappysky This looks awesome. Is there currently any other way to alert only certain people based on custom rules (other than forking from your solution)? It doesn't seem to be a basic feature anywhere in Sentry at the moment, but would be very nice to have!

**Comment by kristajg** [comment]
I found a way to alert specific people via Slack by using alert rules + slack config

**Comment by dcramer** [comment]
We're implementing a larger fix for this concern called 'Owners', and that would eliminate the need for this kind of feature in its current form.

**Comment by dcramer** [comment]
(Aside it looks like we haven't publicized Owners yet, but I promise its coming. https://github.com/getsentry/sentry/issues/5741)

**Comment by kristajg** [comment]
Thanks for the update 👍
