### ISSUE TITLE
Session replay doesn't capture vanilla javascript .animate() method

### ISSUE THREAD

**Issue by stikler51** [getsentry/sentry#58317]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

We have successfully set up session replay for project. However, we have encountered a problem where the recorded sessions appear to be incomplete and inaccurate. Specifically, the recordings do not capture elements with dynamic height and animated content created using the animate() method in vanilla JavaScript.

Here is a minimal reproduction app: https://jsfiddle.net/Stikler51/jqsgaf2p/94/

Sentry config:

```
Sentry.init({
  dsn: "https://****.ingest.sentry.io/****",
  integrations: [
    new Sentry.Replay({
      networkCaptureBodies: true,
      maskAllText: false,
      maskAllInputs: false,
      blockAllMedia: false,
    }),
  ],
  replaysSessionSampleRate: 1,
});
```

### Expected Result

On session replay records animated elements must be visible

https://gyazo.com/0e10a0925a7eb6352a8a1e6c4124d157

### Actual Result

On session replay records animated elements are not visible

https://gyazo.com/9031018a2e1b4c3b6a1f3269a09475ab

### Product Area

Replays

**Comment by billyvg** [comment]
Thanks for the report and especially the minimal repro, we'll look into this.

cc @mydea is this similar to what you were seeing on Vanguard (iirc)?
