### ISSUE TITLE
Display filtered events due to Allowed Origins

### ISSUE THREAD

**Issue by JTCunning** [getsentry/sentry#5831]
Since [these events](https://github.com/getsentry/sentry/blob/master/src/sentry/api/base.py#L158-L163) do not count towards a quota, we should display them as Filtered so that orgs can get a full scope of their event volume.

**Comment by dcramer** [comment]
@kjlundsgaard could we make this change as part of the filters work?

**Comment by kjlundsgaard** [comment]
Do just mean log and display them in the inbound filters stats?

**Comment by dcramer** [comment]
Yeah. Right now we just discard but capturing the metric on these would be good. We can call the filter name "cors"

**Comment by kjlundsgaard** [comment]
Since inbound data filters are scoped to projects, is there a way to reliably know what project these events are filtered from? Or what's the best way to approach that?

**Comment by dcramer** [comment]
@kjlundsgaard yep this reads the project config to know what 'Allowed Domains' are, and if it doesnt match those, it drops the event. It'd simply be adding a tsdb.incr call (or appending to the list) when that happens.

**Comment by dcramer** [comment]
Specifically its in this check in ``web/api.py``:

```
                    if not is_valid_origin(origin, project):
                        raise APIForbidden('Missing required Origin or Referer header')
```

We could probably raise a new exception and catch it above (thus letting you batch the incrs).

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
