### ISSUE TITLE
Support Mixed Profiles

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry#58329]
React Native can send mixed profiles including Hermes JS and Cocoa frames.

- https://github.com/getsentry/sentry-react-native/pull/3349

At the moment the profile symbolication is based on the top level `platform` property. Which for RN is `javascript`.

The scope of the change should include the following functions:
https://github.com/getsentry/sentry/blob/9c487382d459203ebe4109f6b677507f03ca0891/src/sentry/profiles/task.py#L276
https://github.com/getsentry/sentry/blob/9c487382d459203ebe4109f6b677507f03ca0891/src/sentry/profiles/task.py#L347

We can either add `platform` field to the `frame` properties or similarly to the `is_valid_js_frame` we can detect native frames and symbolicate them. 

Example mixed profile:
https://sentry-sdks.sentry.io/profiling/profile/sentry-react-native/95829777fb0e4ee4a37f78a31727f218/flamegraph/

![Screenshot 2023-10-18 at 15 06 46](https://github.com/getsentry/sentry/assets/31292499/3a44967f-d67f-435e-ab94-cc0bb7f54527)

**Comment by viglia** [comment]
@krystofwoldrich as we discussed offline, let's use the frame-level `platform` field then. 
This way we'll get closer to what mixed-error does already.

**Comment by viglia** [comment]
Relay _"Add platform field to profile frames"_ [PR](https://github.com/getsentry/relay/pull/2629)
