### ISSUE TITLE
Make endpoint to get and update notification provider preferences for a team

### ISSUE THREAD

**Issue by jangjodi** [getsentry/sentry#58363]
- API design should be similar to the existing [UserNotificationSettingsProviderEndpoint](https://github.com/getsentry/sentry/blob/e59d23b3a55bb6dcd7ac6eca3c92140a817fb48e/src/sentry/api/endpoints/user_notification_settings_providers.py#L22)
- Endpoint should be private and behind the feature flag
- `/api/0/teams/{orgSlug}/{teamSlug}/notification-providers/`
    - `GET`: Returns a list of `NotificationSettingProvider` rows for that team
    - `POST`: Update/create the `NotificationSettingProvider` rows for that team

**Comment by mikejihbe** [comment]
Unlikely to work on this in the foreseeable future without customer demand. Closing.
