### ISSUE TITLE
Mobile Screenshot creates additional whitespace when there is a small number of tags

### ISSUE THREAD

**Issue by kahest** [getsentry/sentry#58388]
[Example issue](https://sentry-sdks.sentry.io/issues/2862440042/?project=5428559&project=5428557&project=5428562&project=5428561&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=1)

![Screenshot 2023-10-18 at 13 39 18](https://github.com/getsentry/sentry/assets/2005158/31511a0b-3090-4667-8467-ab28fe28aca2)

**Comment by 17hogeju** [comment]
@kahest I believe it is because of the screenshot. Is the placement of the screenshot something you would want to change?

**Comment by kahest** [comment]
@17hogeju ideally we'd not want to move it too much - we placed it rather on top of the page to make it prominent. Since this is more of an edge case, I'm looking for a way to (at least slightly) improve the layout for these cases without compromising for the "normal" use case.

E.g. currently we have a `Screenshot` header and a `View screenshot` + `...` buttons at the bottom, maybe there's a way to combine these? And we could reduce the default height of the thumbnail slightly, ideally depending on the height of the tags div?

**Comment by kahest** [comment]
this is outdated after the recent layout changes on the issue details
