### ISSUE TITLE
Indicate success upon email notification unsubscribe

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#58409]
https://github.com/getsentry/sentry/assets/1421724/853d4b5d-175d-4f57-b8d0-619da7f28179

Right now when you unsubscribe from email notifications there's no indication given that the unsubscribe was successful

### Proposed solution

here's the code responsible for this view. 

https://github.com/getsentry/sentry/blob/a3264a8cd0366f1df21c4a12023256bd31416428/src/sentry/web/frontend/accounts.py#L231-L257

1. **Approach 1:** Replace this view with a react view and implement the unsubscribe action as an API endpoint

2. **Approach 2**: Instead of redirecting return a new view that confirms the unsubscribe

**Comment by ceorourke** [comment]
This looks resolved as approach 1 by https://github.com/getsentry/sentry/pull/59172, https://github.com/getsentry/sentry/pull/59223, and https://github.com/getsentry/sentry/pull/59652
