### ISSUE TITLE
Note limitation of Bulk Actions

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#5840]
For a number of reasons, Sentry's "bulk action" behavior is limited to the first 1,000 matches. While ideally we'd apply to everything, we can't do that synchronously and we haven't implemented another mechanism.

As a stop-gap, let's update the UI to note it only applies to the first 1,000 matches.

**Comment by dcramer** [comment]
@getsentry/workflow

**Comment by billyvg** [comment]
@dcramer By "first" you mean the "most recent" right?

**Comment by dcramer** [comment]
@billyvg i think thats safe to say
