### ISSUE TITLE
Improve custom Loader Script init flow

### ISSUE THREAD

**Issue by mydea** [getsentry/sentry#58428]
Currently, when using the Loader Script, you have to configure it like this:

```html
<script src="... loader URL"></script>
<script>
Sentry.onLoad(function() {
  Sentry.init({ ... });
});
</script>
```

In order for this to work, we depend on very specific timing semantics - you have to call `Sentry.onLoad` _after_ you added the loader script, but _before_ the loader script fetched the CDN bundle. 

In order to streamline this, I propose to add a new way to do this:

```html
<script>
window.sentryOnLoad = function() {
  Sentry.init({ ... });
};
</script>
```

This could be configured either before or after the loader script tag, and we would pick it up in the loader, if configured, in addition to any `Sentry.onLoad()` callbacks.

Alternatively, we could also make it an array:

```html
<script>
window.sentryOnLoad = window.sentryOnLoad || [];
window.sentryOnLoad.push(function() {
  Sentry.init({ ... });
});
</script>
```

This has the benefit of allowing multiple calls, but makes the setup a bit more complicated. I would personally vote for the first option, for simplicity - if you need multiple callbacks, you can still use `Sentry.onLoad()`.

**Comment by lforst** [comment]
The google analytics is strong in this one :D

**Comment by mydea** [comment]
so the "old" way still has a purpose, as you can use it to guard usage of APIs. E.g. anything that is not handled by the loader, you can guard:

```js
// Safe to use, because this is handled by the loader
Sentry.captureException(); 

// This is NOT safe to use, because this may not be loaded/available yet
Sentry.startTransaction();

// Instead, you have to do:
Sentry.onLoad(function() {
  Sentry.startTransaction();
});
```

This new API is specifically desgined to streamline the custom init flow for the loader! `onLoad` is a bit more versatile and can be called multiple times.

**Comment by asottile-sentry** [comment]
I'm worried that this feels rushed -- especially when there's a correct way to do it already and that we would need to attach yet-another thing to `window`.  Is there a broader design document and agreement that this is the correct way forward?

**Comment by mydea** [comment]
The problem is that the current way is not necessarily _correct_ for what it is trying to achieve:

1. You need to guard for the existence of `Sentry.onLoad`, because it could be unexisting if e.g. the loader script failed to load.
2. We depend on fragile timing semantics to ensure that any init called inside of `Sentry.onLoad()` is actually applied correctly before other things. See e.g. https://github.com/getsentry/sentry-javascript/issues/9216

**Comment by asottile-sentry** [comment]
can you please put together a design / [rfc](https://github.com/getsentry/rfcs)

**Comment by mydea** [comment]
Sadly it seems the issue has not been fixed - it was also more of a bandaid, sadly, as the root cause is tricky. The actual solution is to define your custom init _before_ the loader script is loaded, then we can _ensure_ this is correct. See also the comment here: https://github.com/getsentry/sentry-javascript/issues/9216#issuecomment-1775673799 who basically asks for exactly this.

From a docs perspective, I would only recommend this going forward for custom initialization, but we would of course (as @HazAT pointed out) continue to support `Sentry.onLoad` indefinitely, and can document it as a way to guard custom API calling going forward.

**Comment by mydea** [comment]
Since we don't have another real fix for the timing issues, we're going to go ahead with this change in a backwards compatible way.
