### ISSUE TITLE
Mark as Fixed in Commit

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#5842]
Allow an issue to manually marked as fixed in a commit SHA. This would be primarily used in situations where you didn't tag the commit when you pushed it.

**Comment by riktimmondal** [comment]
Please can you elaborate in details as i am just starting to contribute.

**Comment by theharshitgarg** [comment]
please explain `llow an issue to manually marked as fixed in a commit SHA. `
It is known that github allows issue number along with certain keywords like `close, resolve, fix` to be used for auto-closing.
