### ISSUE TITLE
[Invitation Modal] UX For Inviting Users Needs Enhancements

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry#58473]
### Problem Statement

There are numerous nits/problems with the existing invitation flow, I am documenting them here for posterity as this is a compilation of several differing conversations both recently and in the past:

##### Failure Edge Cases

The modal does a poor job handling failure states - example:

<img width="852" alt="image" src="https://github.com/getsentry/sentry/assets/76002357/e6ac41c7-d650-4229-af1e-8ffe729f7dcb">

In this case I have sent no invites, but am presented with the following visual information:

- a green check mark
- the statement "**Sent 0 invites** , 1 failed to send"
- a call to "Send More Invites"

The check mark should in this case be something akin to an "X", in cases where ANY invite from a number of invites fails to send, we should show some kind of warning symbol, we do not:

<img width="852" alt="image" src="https://github.com/getsentry/sentry/assets/76002357/8d64bd0a-41e5-4d4b-b9d5-49319821aa85">

Additionally, the statement "**Sent 0 invites** , 1 failed to send" is both poorly laid out (with extra " " space) and grammatically incorrect. This should probably say "Attempted to send 1 invite, 1 failed to send" etc. 

Finally being prompted to "Send more invites" after sending 0 invites feels semantically incorrect, it's also misleading as to the purpose of the button, which resets the form. This button should probably just say "Reset" or something similar.

##### Secondary Email Non-Disclosure

When you attempt to send an invitation to an email that is a verified secondary email for a user that is already a member of the organization, we indicate that the user is already a member of the org. We do not disclose which member has this secondary email attached to it (this makes sense from a security perspective) however the message in this edge case is highly misleading and can lead to a large amount of wasted time on the part of the user attempting to send the invite.

##### Team Membership

_This feedback is captured in our (now deprecated)[ Feedback board in Jira](https://getsentry.atlassian.net/browse/FEEDBACK-473) - I am choosing to reiterate it here in light of a recent Twitter thread._

It is possible to invite a user to an organization without a team membership. This causes a poor UX as upon joining the org you have access to 0 projects.

For organizations without Open Membership (the ability to freely join a team) this causes a secondary step whereby the invited needs to ask for someone to add them to a team. There are probably valid edge cases for this however the move to deprecate the Admin role in favour of a Team Admin roles complicates the invitation flow. More on that in the next section.

This also causes a poor UX when a user is invited without a team, but with a role that has the ability to create projects (which must have teams). This results in "disappearing projects" as the user does not see those projects by default in the UI after creating them. Interestingly, the Admin Role or greater CAN view this page: https://some-org.sentry.io/settings/projects/ which has a full list of projects. Yet the UI forces you to view this message when attempting to land on any feature overview page without a team membership:

<img width="1138" alt="image" src="https://github.com/getsentry/sentry/assets/76002357/45ff7509-cc66-46c6-8439-a13056db6701">

This message is valid though as people should be joining a project if they are using Sentry. Folks without teams can visit URLs that are project based if there is Open Membership, but not the feature's default view.

##### Role

It is still possible to invite an Admin to a Sentry Organization. This role is deprecated. The correct role should be Team Admin. 

It is not possible invite a Team Admin to a Sentry Organization. A Team Admin would REQUIRE a Team, whereas an Admin would not require a team because this individual would have the permission to create a team.

<img width="851" alt="image" src="https://github.com/getsentry/sentry/assets/76002357/6e1b0a62-74c3-4852-84e2-4f2c4c524842">

The modal has no ability to assign a team role upon invite and should probably not list the option of Admin as this role is deprecated.

##### Email Validation & Repair

It is possible to lock in a string that is not an email: 

<img width="836" alt="image" src="https://github.com/getsentry/sentry/assets/76002357/cdbbca5a-9b7c-4da3-936c-31bcfbdb4d70">

Once this is locked you cannot edit it. Only remove it. 

<img width="833" alt="image" src="https://github.com/getsentry/sentry/assets/76002357/f3eeb145-b325-4833-8caf-8e9f57dcb562">

Upon submission the failure message validates that it is, in fact, not an email. The `x` icon next to this red non-email is not interactive. The only way to clear this is state is by using the Close or Send More Invites CTA (in this case  - again - we have not sent any invites).

### Solution Brainstorm

The user invitation flow needs some enhancements to streamline the invitation experience for both the invited and those sending the invitations.

### Product Area

Settings - Members

**Comment by Dhrumil-Sentry** [comment]
Thanks for opening this issue and the opinion is correct that we need to fix this, I'll use this issue to collect more problems with this flow

cc @leedongwei

**Comment by sentaur-athena** [comment]
We launched a lot of improvements to this modal recently which address these issues. Please feel free to open a new ticket if there are more feedbacks.
