### ISSUE TITLE
Localization of the showReportDialog

### ISSUE THREAD

**Issue by mpj** [getsentry/sentry#5847]
The showReportDialog is great, but is it localized? It's not clear by the docs.

**Comment by vhfmag** [comment]
It doesn't seem so, since sentry source code only receives eventId, dsn, name and email from the error-page endpoint (as shown [here](https://github.com/getsentry/sentry/blob/master/src/sentry/web/frontend/error_page_embed.py#L83)).

So, could that be done? I could work on pt-br and, maybe, fr-fr translations if there is enough demand.

**Comment by dcramer** [comment]
It would use our standard 'detect language' code. It could be done, and passed as an argument, and is something we'd like to support. We simply haven't yet. It's not an extremely complex thing, though I'm not sure how simple it is.

**Comment by chiefmc** [comment]
bump on this

**Comment by anantaramdas** [comment]
Any updates on making it more localized for non-native english speekers? Thanks!

**Comment by sombreroEnPuntas** [comment]
Is it on the road-map? :)

**Comment by dcramer** [comment]
https://docs.sentry.io/enriching-error-data/user-feedback/

**Comment by sombreroEnPuntas** [comment]
I tried earlier using `{ lang: 'de' }`, but it still has English text. Was this updated recently?

**Comment by dcramer** [comment]
@sombreroEnPuntas we might not actually have the localized strings completed but you can pass in your own which is what most people found more valuable

**Comment by monikakalt** [comment]
> @sombreroEnPuntas we might not actually have the localized strings completed but you can pass in your own which is what most people found more valuable

is there documentation on how to pass your own strings? 

seems like` IT LOOKS LIKE WE'RE HAVING ISSUES.` text is not localized (at least not for german lang)
