### ISSUE TITLE
Not able to see wave representation in Session Replays

### ISSUE THREAD

**Issue by Ajay-ML** [getsentry/sentry#58495]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Hi Team,

We have a functionality where users can view the wave representation of their recording in our app. The wave representation is shown properly to users, but it is being captured in the session replays. Can you let us know what is the issue?

Below is the screenshot from the app where wave representation is shown

<img width="199" alt="image" src="https://github.com/getsentry/sentry/assets/107402658/92690acf-b8c7-42f3-a8d3-7fbf57dee482">

### Expected Result

Wave representation also should be shown in session replays

### Actual Result

Wave representation is not shown in session replays

<img width="199" alt="image" src="https://github.com/getsentry/sentry/assets/107402658/4316a5f7-3335-4974-a8ac-c7319e3ed44c">

### Product Area

Replays

### Version

7.74.1

**Comment by bruno-garcia** [comment]
Any chance that wave is a web `canvas`? If so, we're not supporting canvas just yet. But we're planning on working on this soon: https://github.com/getsentry/sentry-javascript/issues/6519

**Comment by Ajay-ML** [comment]
Hi,

Yes we are using html canvas to display it. Thanks for letting me know on working on it. I will follow-up that thread for progress.

**Comment by billyvg** [comment]
Thanks for the report, I'm going to close this thread as it is canvas related. Please follow https://github.com/getsentry/sentry-javascript/issues/6519 for updates on canvas support.
