### ISSUE TITLE
Feature(discover): Be able to show the duration of the longest span

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry#58534]
### Problem Statement

Currently we have spams.db that is a nice measure, but may give high numbers if a given transaction has many queries.
Ideally max(spams.db) or another name would be able to return the value from the longest span from a given transaction, that would help to triage transactions that actually had a slow span.
<img width="169" alt="image" src="https://github.com/getsentry/sentry/assets/8229322/d1ce209c-30c6-43dc-ab4a-2b87491446b0">

### Solution Brainstorm

max(spans.db/http/...) could return this value and perhaps, min(spans.db) could also show the fastest  span.

### Product Area

Discover

**Comment by mjq-sentry** [comment]
Hi @lucas-zimerman, thanks for the issue!

The `max` and `min` aggregate functions [already exist](https://docs.sentry.io/product/discover-queries/query-builder/#stacking-functions) and have a particular meaning so we couldn't use those here, but maybe under another name. To understand your use case better, is the goal of finding these slow queries to then try to speed them up? Or did you have something else in mind?

For what it's worth we have two other ways to monitor for slow DB queries. Our new [Queries page](https://docs.sentry.io/product/performance/queries/) will show you all your queries across the app, and you can use that today to find ones that are slow across all of your transactions.

For a more proactive approach, Sentry's ["Slow DB Query" issue](https://docs.sentry.io/product/issues/issue-details/performance-issues/slow-db-queries/) will automatically trigger if a particular query is consistently slow. If you've got a cutoff in mind, you can set that as your minimum duration in Project Settings > Performance (more details in the [docs](https://docs.sentry.io/product/issues/issue-details/performance-issues/slow-db-queries/)).

**Comment by lucas-zimerman** [comment]
The Queries feature should do the trick, thanks!
