### ISSUE TITLE
Improve release health docs

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#58564]
Slack thread: https://sentry.slack.com/archives/C019637C760/p1695308814934139?thread_ts=1695297576.267089&cid=C019637C760

I've read the Release Health docs and I've seen the SDK specific docs for Release health too :sweat_smile: , Here are some of the gaps based on what I've seen from user interviews as well:
We say the following about crashes:
“A crash is when the application had an explicit unhandled error or hard crash.”
“crash free sessions number is the percentage of sessions in the specified time range not ended by a crash of the application.”
“crash free users number is the percentage of distinct users who did not experience a crash during the specified time period.”
Now here’s what users are trying to do:
They are seeing the total session count we show in page or the total User Count
Then they go search for unhandled issues or the all issues shown below this - They see that the unhandled errors is very low or high but crash free rates don’t match
[@matej](https://sentry.slack.com/team/UQY0N6J77)
 mentioned users can’t correlate errors and session data- but that is not mentioned anywhere :sweat_smile:
A lot of the sam problems likely apply to the project details page

![Image](https://github.com/getsentry/sentry/assets/26696515/adf165bd-1699-4987-b5aa-b744167aa1e0)

**Comment by ale-cota** [comment]
Fixed in https://github.com/getsentry/sentry-docs/pull/8406
