### ISSUE TITLE
replay-count request for IDs returns no results while Discover shows results

### ISSUE THREAD

**Issue by narsaynorath** [getsentry/sentry#58602]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. [This request](https://sentry.sentry.io/api/0/organizations/sentry/replay-count/?data_source=search_issues&end=2023-10-23T15%3A31%3A10.142Z&project=-1&query=event.type%3Atransaction%20transaction%3A%5B%22%2Fapi%2F0%2Fprojects%2F%22%5D%20transaction.duration%3A%3E%3D119.47812999999998ms&returnIds=true&start=2023-10-14T08%3A00%3A00.000Z) to replay-count returns no data
2. [This discover query with similar filters](https://sentry.sentry.io/discover/homepage/?end=2023-10-23T15%3A31%3A10.142&field=title&field=replayId&id=20890&name=&project=1&query=transaction%3A%5B%22%2Fapi%2F0%2Fprojects%2F%22%5D+event.type%3Atransaction+transaction.duration%3A%3E%3D119.47812999999998ms+has%3AreplayId&sort=-replayId&start=2023-10-14T08%3A00%3A00.000&topEvents=5&yAxis=count%28%29) shows there are transactions with replay IDs

### Expected Result

The request to the `replay-count` endpoint surfaces replay IDs that are found in the discover request

### Actual Result

The response is empty

### Product Area

Replays

**Comment by JoshFerge** [comment]
I see. the replay-count endpoint does not support _all_ query parameters from discover. it only takes in a list of Ids. can see how it is used elsewhere on the frontend. 

The replay count endpoint should simply take in 1 or more issue ids, transaction names, or replay_ids. No other fields are supported. can see usage here: https://github.com/getsentry/sentry/blob/985b12891c097f1b5a4097b3f4e80313b304cb4f/tests/sentry/replays/test_organization_replay_count.py#L279

what use case are you trying to accomplish? ideally, you'd get the list of replay_ids from your transactions with all of your discover criteria, and then feed those into the replay count endpoint.

**Comment by narsaynorath** [comment]
@JoshFerge Thanks for the follow up, it's too bad I missed this, I must've only checked with the transaction names before applying my other filters. The reason why we need to add these filters is because for statistical detectors, the other tabs (e.g. Sampled Events, Tags, etc) are filtered to events occurring after the breakpoint with an additional duration filter to show events similar to the new regression baseline.

As a follow up, I removed all of the filters except for the transaction name array filter and simplified my time range to 30 days, but I'm still unable to see results ([query here](https://sentry.sentry.io/api/0/organizations/sentry/replay-count/?data_source=search_issues&project=-1&query=transaction:[%22/api/0/projects/%22]&returnIds=true&statsPeriod=30d)). If I do the same in the discover query, I still see results. Is there an explanation for this?

**Comment by JoshFerge** [comment]
@narsaynorath please change the datasource to `discover` in your query like so: https://sentry.sentry.io/api/0/organizations/sentry/replay-count/?data_source=discover&project=-1&query=transaction:%5B%22/api/0/projects/%22%5D&returnIds=true&statsPeriod=30d
