### ISSUE TITLE
Spike Protection not synced between Org Settings and Project Settings

### ISSUE THREAD

**Issue by gid-sentry** [getsentry/sentry#58604]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Have Spike Protection enabled for a project in both the Organization Settings and the Project's settings
2. Disable Spike Protection via the Organization Settings view for a project
3. Spike Protection within that project's settings view will still appear "enabled"

### Expected Result

Spike Protection settings should be synced between the organization settings view and the project settings view

### Actual Result

<img width="1570" alt="image" src="https://github.com/getsentry/sentry/assets/108364755/4d0b31a6-dbca-4664-b335-c49bd3caf480">

Spike Protection appearing as enabled within the Project Settings view can lead users to believe they're safe in case of spikes, even though it's actually disabled.

### Product Area

Settings - Spike Protection

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1963) by [Unito](https://www.unito.io)

**Comment by Dhrumil-Sentry** [comment]
@cathteng @leedongwei can you please take a look at this one

**Comment by leedongwei** [comment]
Fixed by https://github.com/getsentry/sentry/pull/58651
