### ISSUE TITLE
Sentry Replay Player Autofills Log In Information from Browser

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#58653]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1.) View Replay that has a username and password log in screen
2.) Play replay and select log in box for username and password
3.) On newest version of Firefox 118.02 if 'autofill username and password' is selected in browser options the Sentry Replay Player will recognize the log in boxes in the replay and autofill from the user's browser.

You can reference ticket #105069 for a screen recording of this occurring along with a direct link

### Expected Result

No autofill to occur since the browsers username and password information are not related to the replay in any way and it can be bothersome to have this information show when trying to watch a replay.

### Actual Result

Autofill of browser stored log in information occurs when viewing the replay that includes a log in screen

### Product Area

Replays

**Comment by bruno-garcia** [comment]
@ReneGreen27 does the field have an attribute called `autocomplete`?
Is this a Firefox specific problem? Sentry Replay is rendering the website in the iframe so if the browser is setup to autocomplete something even without you focusing on the input, I understand it'll just do that. SO trying to better understand the triggers/environment so we can find a way to try to disable that within the replayer

**Comment by ryan953** [comment]
Closing because we should avoid messed with captured html
