### ISSUE TITLE
Queries feature not available, please fix this

### ISSUE THREAD

**Issue by titombagwu** [getsentry/sentry#58652]
### Problem Statement

Queries do not work when using the Golang SDK. Also when releasing a feature please release for all SDKs or provide a timeline when it will be available for that SDK.

### Product Area

Performance - Queries

**Comment by mjq-sentry** [comment]
Hi @titombagwu, thanks for the feedback. The currently supported list of SDKs is documented [here](https://docs.sentry.io/product/performance/queries/#recommended-sdk-versions), but indeed it looks like Go is not currently supported. I've followed up with the team working on this feature for guidance.

**Comment by titombagwu** [comment]
I would also update the documentation language, "recommended" != "unsupported"

**Comment by mjq-sentry** [comment]
Sentry's Go SDK doesn't currently support autoinstrumentation of database spans, which is why it isn't supported by Queries. Forwarding to the SDK team for triage, since that's going to be a prereq for getting `db` spans into Sentry.

**Comment by cleptric** [comment]
@titombagwu We'll soon start working on overhauling our performance capabilities in the Go SDK. If you want us to add support for some ORM, please comment on https://github.com/getsentry/sentry-go/issues/743.
