### ISSUE TITLE
Publish Bitbucket Integration on Atlassian Marketplace

### ISSUE THREAD

**Issue by norgeindian** [getsentry/sentry#58678]
### Problem Statement

Currently, the Bitbucket integration can only be used, if the development mode in Bitbucket is active, which is a potential security risk.
It would be awesome if the Sentry Connector could be an official Bitbucket integration, which can be added without development mode.

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
@norgeindian Thanks for this feedback. We don't have any plans to work on this in the next few quarters but I'll add this to our backlog to track this request

**Comment by cathteng** [comment]
Closing as duplicate of https://github.com/getsentry/sentry/issues/23232
