### ISSUE TITLE
Feature flag spring cleaning

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#58682]
Remove flags that are not used in the codebase or are GAd. We need to check both sentry, getsentry, and flagr.

48 organizations:mobile-app - no usages
63 organzations:metrics - enabled for all (no usages)
319 organizations:dynamic-sampling-transaction-name-priority - no usages
336 organizations:open-ai-suggestion - GA'd
341 organizations:onboarding-project-loader - enabled only for tele team (no usages)
349 organizations:artifact-bundles - enabled for EA + riccardo (no usages) (edited)

**Comment by cuevana8** [comment]
+1..[.](https://github.com/flslib/fl-studio-cracked)[@@@](https://github.com/getsentry/sentry/issues/58682#issue-1958878696)
