### ISSUE TITLE
ui: search bar re-renders and appends space to query term

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#5871]
Can be a bit awkward the first time you click into search bar and you can see it append a space. Also can lead to incorrect behavior as seen here: http://i.imgur.com/byAeMvZ.gifv

**Comment by alsuren** [comment]
Fixed in https://github.com/getsentry/sentry/pull/9143 by adding the space to props.query before saving it into state.query, and then removing it again when calling props.onSearch(). The onInputClick callback no longer has to do the crazy late update.
