### ISSUE TITLE
Subscribe to Commits

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#5872]
The ability to subscribe to commits would be useful when paired with deploy notifications. Would likely work very similar to issue subscriptions.

**Comment by dcramer** [comment]
Aside, adding comments to releases/commits would also be nice (we'd likely need to refactor those systems).

**Comment by dcramer** [comment]
I may toy around w/ the data schema changes needed ot make this more easily doable.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
