### ISSUE TITLE
Sentry.setUser not passing extra key pairs

### ISSUE THREAD

**Issue by shayani** [getsentry/sentry#58767]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which SDK are you using?

Sentry Browser CDN bundle

### SDK Version

7.73.0

### Framework Version

Vanilla JS inside Rails

### SDK Setup

```
Sentry.init({
      replaysSessionSampleRate: 1.0,
      replaysOnErrorSampleRate: 1.0,
      environment: "production",
      integrations: [
        new Sentry.Replay({
          maskAllText: false,
          blockAllMedia: false,
        }),
      ],
    });
```    

### Steps to Reproduce

Run through the webapp and record a replay. The replay is then sent to Sentry.io with user's IP, email and name, but any extra key pair is not being saved.

Follows snippet for `setUser`
```
Sentry.setUser(
      {
        username: 'My name',
        email: 'email@example.com',
        agency_name: 'My company name'
      }
    )
```

### Expected Result

I expect to receive the `agency_name` and this be recorded anywhere on Sentry Replay (probably under `TAGS`)

### Actual Result

`user.ip`, `user.email` and `user.username`  displays on TAGS tab on Replay. The `agency_name` doesn't show anywhere.

**Comment by AbhiPrasad** [comment]
For issues team folks - here's an example issue where [I sent segment in the payload](https://sentry-test.sentry.io/issues/4573897198).

This doesn't appear in the user context UI 

![image](https://github.com/getsentry/sentry/assets/18689448/1bcec919-62fa-4326-ab08-a32f1ef3e43d)

but is a part of the event JSON

https://sentry-test.sentry.io/api/0/projects/sentry-test/z-abhi-test-project/events/0229c40fd8484cbaaddf6d6795a8eab0/json/

![image](https://github.com/getsentry/sentry/assets/18689448/234988fd-a855-419c-bcc0-9da681138f65)

https://github.com/AbhiPrasad/GH-9229-sentry-setuser-extra-key-pairs/blob/main/src/index.js is a basic reproduction you can use.

**Comment by roggenkemper** [comment]
thanks for bringing this up, i'll add it to our teams backlog so we can take a look at it.

**Comment by cleptric** [comment]
`user.segment` is now considered deprecated and was removed from docs/develop.
All other user-provided keys should still be displayed, though.

**Comment by vctormb** [comment]
> Hey @shayani, thanks for writing in! For replay I think we only extract `id`, `username`, `email`, or `segment` as tags as per our [setUser docs](https://docs.sentry.io/platforms/javascript/enriching-events/identify-user/).
> 
> I'll let @bruno-garcia confirm this though.

So is it better to create another tag for extra data?

**Comment by mikejihbe** [comment]
It looks like we don't support arbitrary attributes on user in this fashion. Please open an SDK ticket if you want something like this to be added.
