### ISSUE TITLE
repository connection preserve input on auth

### ISSUE THREAD

**Issue by MaxBittker** [getsentry/sentry#5876]
When connecting a repository, if you try to connect a repo that you're not authorized for, you're redirected to a page where you associate an oauth identity. 
Afterwards, you're redirected back to the page but the repository name field has been cleared.
It would be nice to preserve it.

to reproduce: 
unassociated any relevent bitbucket or github identity
add a repository that requires auth
authorize sentry for repo provider
you will now be back at the /repos/ page with no repo name filled out

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
