### ISSUE TITLE
Owners are not able to view stats for teams that they are not a part of

### ISSUE THREAD

**Issue by serglom21** [getsentry/sentry#58774]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Go to the `stats/issues` page as an owner.

By looking at the [code](https://github.com/getsentry/sentry/blob/7bb213df90a03a982865916fcad1e0dbc18e2d35/static/app/views/organizationStats/teamInsights/controls.tsx#L133), it seems to me that we are just checking whether the user is either a super user or returning the teams that they are only a part of

### Expected Result

As an organization owner, I would expect to be able to select and see the stats for ALL the teams within my org, even if I am not part of that team

### Actual Result

As an owner, I am only able to select teams I am a part of in the dropdown

### Product Area

Issues

### Link

https://demo.sentry.io/stats/issues/

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1968) by [Unito](https://www.unito.io)

**Comment by Dhrumil-Sentry** [comment]
@leedongwei can you please take a look at this issue

**Comment by serglom21** [comment]
@leedongwei @Dhrumil-Sentry are there any updates on this issue?
Thanks

**Comment by leedongwei** [comment]
Sorry, it dropped off my plate. I'll have someone take a closer look.
