### ISSUE TITLE
[design] Purple-on-purple color scheme in the feedback list is problematic

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#58837]
When the checkbox is purple, and the selected item is purple, it's not great.
When the 'is unread' indicator is purple, and the selected item is purple, it's not great.
This needs something to happen, new colors？

| case | pic |
| --- | --- |
| Unselected, unread | ![Image](https://user-images.githubusercontent.com/187460/278195924-fb6530cf-6013-4e06-b28e-dce932cbc360.png) |
| selected, unread, not checked | ![Image](https://user-images.githubusercontent.com/187460/278195772-2bb69fbf-9a50-4b3c-bbe5-66a051236ca1.png) |
| selected, unread, checked | ![Image](https://user-images.githubusercontent.com/187460/278195802-5b8e113d-2a65-4f69-babb-cf7adbdcf888.png) |

**Comment by Jesse-Box** [comment]
Hey @ryan953 

So I covered the cases you highlight above [here](https://www.figma.com/file/ga57zyLonVCSJIH3kOWLVA/Specs%3A-User-Feedback-v1?type=design&node-id=3%3A11969&mode=design&t=m4jTSD2JsWfthaqz-1)

However, if we're looking for something less custom, I can certainly address the UI in a different way

**Comment by ryan953** [comment]
sending this to @michellewzhang. We've got to follow through and make the checkbox background white when things are checked.
