### ISSUE TITLE
CSP Improvements

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#5884]
- [ ] capture browser.name tag
- [ ] capture blocked-uri.domain tag (evaluate if others are useful)
- [x] pass values which may contain user input (e.g. urls) through scrubbers https://github.com/getsentry/sentry/pull/5886
- [ ] remove logger

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
