### ISSUE TITLE
Badges on the sidebar

### ISSUE THREAD

**Issue by WilliamDavidHarrison** [getsentry/sentry#58846]
### Problem Statement

I would like to see badges with numbers on the sidebar next to specific options.

Like for example, next to the issues button on the sidebar, show a badge with the amount of unresolved issues. (Maybe make this changeable in settings so people can change it to the amount of regressed issues, etc)
![image](https://github.com/getsentry/sentry/assets/87287585/350378c4-974b-43f5-9a10-faddc17d73d6)

### Solution Brainstorm

These are the following badges which I would be cool to see:
- Issues (stated above)
- Projects (number of projects in the organisation)
![image](https://github.com/getsentry/sentry/assets/87287585/c6cf91da-6785-4253-8858-2078dd7fa74f)

### Product Area

Other

**Comment by roggenkemper** [comment]
thanks for the idea! no promise that this is a project the team is going to take up , but something we will consider.

**Comment by WilliamDavidHarrison** [comment]
@scttcper Will this not be added?

**Comment by scttcper** [comment]
@WilliamDavidHarrison not planned for now
