### ISSUE TITLE
Monitor 'sync-options-control' has an interval of 10 seconds.

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/sentry#58854]
Hello i just install sentry on premise for the first  time - self-hosted-23.10.0   and my logs are full of:

docker/sentry-self-hosted_cron_1[861]: 15:59:39 [WARNING] sentry_sdk.errors: Intervals shorter than one minute are not supported by Sentry Crons. Monitor 'sync-options-control' has an interval of 10 seconds. Use the `exclude_beat_tasks` option in the celery integration to exclude it.

is there a doc to help me fix this ?

_Originally posted by @ydastous in https://github.com/getsentry/sentry/discussions/42283#discussioncomment-7371959_

**Comment by rjo100** [comment]
https://github.com/getsentry/sentry/pull/58856 This will fix it. 

We're working on better ownership for crons internally to prevent this sort of thing happening. 

For reference here's the docs on it:
https://docs.sentry.io/platforms/python/integrations/celery/crons/?original_referrer=https%3A%2F%2Fwww.google.com%2F#excluding-celery-beat-tasks-from-auto-discovery

**Comment by ydastous** [comment]
Thanks I have seen this doc, but since i am not a dev more a sysadmin guy who install the  self-hosts version, i have no ideas which config to changed/modif at the install level  ( config files) to achieve it...
