### ISSUE TITLE
How can I change the four featured tags at the top of each Sentry issue page?

### ISSUE THREAD

**Issue by edgariscoding** [getsentry/sentry#58858]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

On each individual Sentry issue page there's a section labeled "Tags" with four large pinned tags at the top and a list of all tags right below.

How can i change these pinned tags? 

For example, I don't really care about the runtime version for every issue... it'll always be the same in my case but currently it's prominently displayed with a large icon and large text at the top of the issue. I'd prefer to know the server_name up there because that's more relevant while troubleshooting.

I also don't need to know the OS version, I'd rather know the Release version.

Trying to find server_name, and release, and other more important tags in a list of dozens of tags is annoying.

### How are you getting stuck?

I can't find anything in the settings to change this behavior. I can see how to delete tags but nothing about changing which of the tags gets highlighted at the top of each issue page.

### Where in the product are you?

Issues

**Comment by 17hogeju** [comment]
Hey! Thanks for sending in this request - this sounds like a useful feature! I appreciate you taking the time to share your feedback. 😄 

I can't make any concrete promises yet, but I've passed this along to our product team. I'd expect we can prioritize working on this sometime in the next quarter or two.

**Comment by leeandher** [comment]
Hi @edgariscoding! We've just shipped a new feature called '[Event Highlights](https://docs.sentry.io/product/issues/issue-details/#event-highlights)' which aims to solve this issue. Those context summaries should no longer be appearing in Sentry, and you can customize the highlights you wish to see at the top of the page for every project, so long as you're a Project Admin.

Closing this out, but thank you for the feedback!
