### ISSUE TITLE
Invite Member on Team page opens up organization invite page rather than team invite

### ISSUE THREAD

**Issue by mikellykels** [getsentry/sentry#5889]
Clicking the **+ Invite Member** button from `https://sentry.io/organizations/{organization_slug}/teams/{team_slug}/members/` opens up the **Add Member to Organization** page `https://sentry.io/organizations/{organization_slug}/members/new/`.

Should be something like: `https://sentry.io/organizations/{organization_slug}/teams/{team_slug}/members/new/`
- As a dropdown that does a typeahead with the existing team names/emails

CC @getsentry/workflow @ehfeng @getsentry/cops

**Comment by danielwhatmuff** [comment]
Any news on this? I cant seem to add existing org members to a team. Just takes me to the add org member screen and then says they already exist.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
