### ISSUE TITLE
"Something went wrong" trying to create Jira issue from Sentry issue

### ISSUE THREAD

**Issue by bdworth** [getsentry/sentry#58906]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Navigate to https://benchling.sentry.io/issues/4577254609/ (need permissions, naturally)
2. Click the plus icon by "Jira Server Issue".
3. See the popup to choose between creating a new issue or linking to an old one _briefly_ (can't do anything)
4. See the popup change to this: 
<img width="610" alt="Screenshot 2023-10-26 at 5 48 21 PM" src="https://github.com/getsentry/sentry/assets/13633550/d89935a0-d353-4362-8579-34af051d8782">

### Expected Result

Being able to create a new Jira or link to an existing one

### Actual Result

see screenshot in "steps to reproduce"

### Product Area

Issues

### Link

https://benchling.sentry.io/issues/4577254609/

**Comment by Dhrumil-Sentry** [comment]
@schew2381 can you please take a look when you get a chance

**Comment by saifelse** [comment]
It's a 500 on this endpoint: https://us.sentry.io/api/0/organizations/benchling/issues/4577254609/integrations/145094/?action=create

Response:
```
{
  "detail": "Internal Error",
  "errorId": "ecac98715ac1405aa67a586016867600"
}
```

**Comment by saifelse** [comment]
On the other hand, https://us.sentry.io/api/0/organizations/benchling/issues/3793834696/integrations/145094/?action=create reliably 200s... so the crash seems issue-specific.

**Comment by schew2381** [comment]
@saifelse For more context, has this issue only started appearing recently?

**Comment by adamgsg** [comment]
This is affecting us as well.  I believe it started in the last week or two

**Comment by adamgsg** [comment]
In our JIRA logs, we see the sentry user making this request:
`/rest/api/2/project/24900/priorityscheme`

Which gets a 403 access denied error, as that endpoint is only allowed for Jira Project Admins.  (And we cannot make the Sentry user an admin in every project).

Why is this endpoint being requested?

**Comment by Dhrumil-Sentry** [comment]
Hi @adamgsg we're working on automatic ticket creation for Jira Server and some of our changes may be causing some bugs, @schew2381 is looking into fixing these soon
