### ISSUE TITLE
Sentry is loading complete organisation data at once.

### ISSUE THREAD

**Issue by Tibingeo** [getsentry/sentry#5893]
Sentry takes ~1 minute to load my organization, payload size is  `16.7 MB`
![screen shot 2017-08-16 at 9 58 43 pm](https://user-images.githubusercontent.com/16147643/29374260-63e037cc-82ce-11e7-827d-c3375b4f292c.png)

Sentry Version: 8.18.0

**Comment by mattrobenolt** [comment]
wtf

Can you share the response JSON?

**Comment by dcramer** [comment]
At the very least, whats the API endpoint its hitting? And are you logged in as a superuser or not (if this is sentry.io, you're not).

**Comment by mattrobenolt** [comment]
This also seems to be the same as the post here: https://forum.sentry.io/t/huge-api-responses/2161

If you can, could you add more information there?

**Comment by Tibingeo** [comment]
@mattrobenolt Thank You my issue is fixed here `https://forum.sentry.io/t/huge-api-responses/2161/9`
