### ISSUE TITLE
Slow React Mount Performance Issue

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry#58935]
### Problem Statement

As soon as we see a span with op `ui.react.mount` that takes longer than something like 500ms we can confidently say this is an absurd mount time (a few ms is probably reasonable at max) and notify the user.

### Solution Brainstorm

<img width="883" alt="image" src="https://github.com/getsentry/sentry/assets/18689448/3dad1d04-956d-4fdb-bf37-228ce88c7ff2">

### Product Area

Performance

**Comment by nanoburd** [comment]
I like this idea, just need to prioritize for impact for the most number of customers.

**Comment by AbhiPrasad** [comment]
We have `ui.X.mount` span via component tracking spans for other frameworks as well (vue, svelte, angular), and we can use the same logic for those too.

Hence this detector will work for react, vue, svelte, angular

**Comment by nanoburd** [comment]
Ok that's really good to know. I will consider this for future quarters, especially when we revisit our strategy and roadmap for Performance Issues in general. I don't think we can drop anything to work on this right now.

**Comment by AbhiPrasad** [comment]
Going to close this a won't do for now, we can always re-evaluate in the future.
