### ISSUE TITLE
Get transactions within certain timerange using Sentry API

### ISSUE THREAD

**Issue by adityasingh773** [getsentry/sentry#58932]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I am trying to access my transactions via Sentry API like so
`GET https://sentry.io/api/0/projects/{{org}}/{{project}}/events/`

I have two problems:

1. It only gives me events with errors and not "transactions" like network requests made from my app (I see the transaction on sentry).
2. How do I query such transactions for a given timerange? 

Note: I don't want to query transactions with id, rather get transactions within specific time range.

### How are you getting stuck?

Could not find out docs relating to above two points.

### Where in the product are you?

APIs

**Comment by Dhrumil-Sentry** [comment]
@adityasingh773 Thanks for this feedback, I don't think we have any API to do this today but I'll let the performance team chime in

**Comment by mjq-sentry** [comment]
As a workaround, it's currently possible to do this with multiple API calls, using the [Query Discover Events in Table Format endpoint](https://docs.sentry.io/api/discover/query-discover-events-in-table-format/) to get event IDs, and then calling the [Retrieve an Event for a Project endpoint](https://docs.sentry.io/api/events/retrieve-an-event-for-a-project/) to fetch the details of each event. (It's not likely to be a scalable solution if you want to query a lot of events though.)

**Comment by adityasingh773** [comment]
@mjq-sentry , I checked [Query Discover Events in Table Format endpoint](https://docs.sentry.io/api/discover/query-discover-events-in-table-format/), how do I fetch events of type "transactions" from the this endpoint: `https://sentry.io/api/0/organizations/{organization_slug}/events/`?
When I do make a curl request on that endpoint, i only see events of type "error" which my point 1 in the issue still

**Comment by mjq-sentry** [comment]
You can use the `query` value `event.type:transaction` to filter to just transactions. Here's an example that fetches the project ID, timestamp and transaction name for transactions in a time range (swapping in your own `{organization_slug}` and  `<auth_token>`).

```sh
curl https://sentry.io/api/0/organizations/{organization_slug}/events/ \
 -H 'Authorization: Bearer <auth_token>' \
 -G \
 -d "query=event.type:transaction" \
 -d "start=2023-10-24" \
 -d "end=2023-10-31" \
 -d "field=transaction" \
 -d "field=timestamp" \
 -d "field=project_id"
```

**Comment by adityasingh773** [comment]
@mjq-sentry , Now, I have to query each transaction individually, which would make it an expensive operation. Although, thanks for the input, it solves my problem partially. 🎉
