### ISSUE TITLE
Ignore issue doesn't let you specify time in SENTRY_DEFAULT_TIME_ZONE

### ISSUE THREAD

**Issue by davedash** [getsentry/sentry#5895]
- Sentry 8.19
- Non-docker instance

Steps to repro:

1. Find an issue
2. Choose Ignore
3. Choose custom time

Actual:
Time is to be specified in UTC

Expected
Enter time in SENTRY_DEFAULT_TIME_ZONE (in my case PDT).

**Comment by dcramer** [comment]
Ideally we'd respect the user's preference in the UI (and probably clarify that its in X timezone, or give you a selector between UTC and your chosen timezone).

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
