### ISSUE TITLE
Data Scrubbing tags

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#5896]
We should consider how to apply data scrubbing filters to tag keys/values. But this presents a couple challenges and considerations to the pipeline today.

## Problem

It's possibly send something like:

```json
"tags": {
  "credit-card-number": "4242424242424242"
}
```

And currently, tags are untouched by scrubbers.

## Solutions

So as a first pass, we could add another method into data scrubbers similar to the way we blast over `extra` as seen here: https://github.com/getsentry/sentry/blob/86c259da5843cbaeb426c0fb1dd8b14dfb18710f/src/sentry/utils/data_scrubber.py#L98-L99

But for tags, this is not quite enough. When a tag value actually fails a violation step, the tag value is shoved into `errors` instead and left out of tags. And this value has not been sanitized. This means we now take a sensitive value, that failed validation, and we just shoved the value into `errors` before and data scrubber would touch it. This happens here: https://github.com/getsentry/sentry/blob/86c259da5843cbaeb426c0fb1dd8b14dfb18710f/src/sentry/coreapi.py#L517-L610 And this happens _before_ data scrubbers have run.

In a real world example, there was a tag whose value was a url. This url has a credit card number within the querystring parameters within the value. None of our existing scrubbers would have caught this value. The url was something like: `http://example.com/?creditcard=4242424242...` . See the change applied in https://github.com/getsentry/sentry/pull/5886 to work around this.

So thinking of refactoring data scrubbers a bit so that we can do both validation and scrubbing of values within the same phase. This way we can also avoid sensitive information from appearing in errors. But we also need to expand some of our checks to be able to accommodate patterns like above. Not sure if the answer is to just change the regexp for credit card numbers to just work here magically, or we attempt to also detect urls within all inputs and try to handle querystring key/values out of that.

cc @getsentry/platform

**Comment by sksembhi** [comment]
:1st_place_medal:

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
