### ISSUE TITLE
New Story on Swift Symbols

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#5898]
Users keep running into various issues because we effectively require them to upload the swift dsyms themselves. In particular when bitcode is used it's a bit weird as our support for stripped symbols is not great (`__hidden`).

We might want to extend our symbol collection process to also collect libswift*.dylib from the sdks that are distributed with xcode.  This would also then solve the case laid out in https://github.com/getsentry/sentry-cli/pull/109

The only downside is that we need to collect more stuff.

**Comment by mitsuhiko** [comment]
A note: since swift is shipped within the framework folder the branching for app shipped vs system symbols would have to special case swift.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
