### ISSUE TITLE
[feature request] connect repositories via API

### ISSUE THREAD

**Issue by MaxBittker** [getsentry/sentry#5899]
Would enable people to do things like programmatically create a new repo, new sentry project, and register the webhook in a fell swoop.

**Comment by dcramer** [comment]
technically cant you do this already? assuming you have an account attached?

**Comment by kaplun** [comment]
@dcramer from the documentation I wasn't able to find a reference on how to add a repository via API. One can only retrieve a list of registered repositories.

**Comment by dcramer** [comment]
It’s not documented but you can take a look at what the UI does as you should be able to make the same calls.

**Comment by azakordonets** [comment]
And what if you could just update your documentation? I recently discovered by lucky chance that I can actually specify a platform in "Create Project" API Call. This was missing from documentation as well.

**Comment by BYK** [comment]
The [docs are also open source](https://github.com/getsentry/sentry-docs/) so feel free to submit a PR there for any improvements you see fit.

Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
