### ISSUE TITLE
Go project creation lacks some integrations

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry#59017]
![grafik](https://github.com/getsentry/sentry/assets/6617432/8dca5353-2ad3-4386-9e7b-87a87adcf7f4)

We should add

- https://docs.sentry.io/platforms/go/guides/gin/ (supports panic reporting & performance)
- https://docs.sentry.io/platforms/go/guides/echo/ (supports panic reporting)
- https://docs.sentry.io/platforms/go/guides/fasthttp/ (supports panic reporting)

**Comment by natikgadzhi** [comment]
Whoops, I thought I'd snag the issue and work on it, but alas I'm late to the party 🙃 Please excuse me for posting an unsolicited opinion, and feel very free to "well, actually" me, or tell me to shut up and never show up in this repo again.

Anyway, I _think_ the reason Go frameworks don't show up is in here: https://github.com/getsentry/sentry/blob/62bd12c50f2c9253dc897a2ee2a7fbe0b217936d/static/app/data/platformPickerCategories.tsx#L55 — they're just not on the list of `createablePlatforms`.

<div>
    <a href="https://www.loom.com/share/ed697055cff944dea0d268a6e0eecadd">
      <p>Poking Around Sentry Campaigns - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/ed697055cff944dea0d268a6e0eecadd">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/ed697055cff944dea0d268a6e0eecadd-with-play.gif">
    </a>
  </div>

Fixing it there will have a side effect of showing the _frameworks_ on the list of all available frameworks to create a project with here:
<img width="2660" alt="Screenshot 2023-10-31 at 2 19 54 PM" src="https://github.com/getsentry/sentry/assets/43633/78a2e7c9-137f-402b-a535-53667c027166">

I can put up a PR if @ArthurKnaus you don't mind, but, again, I don't even have Sentry fully running locally yet. I was just poking around ;)

**Comment by cleptric** [comment]
Our Vienne office has a day off tomorrow, so if you're fast, you can beat him 😆
