### ISSUE TITLE
Release Flutter Profiling on iOS/macOS - Alpha

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#59035]
- [x] Add support to SDK: https://github.com/getsentry/sentry-dart/pull/1611
- [x] Upload Flutter symbols: https://github.com/getsentry/sentry-dart/pull/1673
- [x] Make a release of the Flutter SDK 7.12.0
- [x] merge docs https://github.com/getsentry/sentry-docs/pull/8363/
- [x] Add in-product onboarding

**Comment by bruno-garcia** [comment]
No need to route, @vaind is driving this

**Comment by kahest** [comment]
@buenaflor just FYI

**Comment by bruno-garcia** [comment]
This is resolved, Flutter Profiling is available for iOS/macOS
