### ISSUE TITLE
Native stacktraces improvements

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry#59030]
<img width="459" alt="279160057-e574324e-ab9f-420a-8e55-e994a8169f14" src="https://github.com/getsentry/sentry/assets/6617432/5b89bd6a-3e58-40ed-84e1-bd1e30ef2d94">

Not having the format of `<file>:<line>` means that I can't paste it into a VSCode Quick Open dialog or anything like that.

Honestly I've said this all over the place, but it would just be really nice if I could map some file/package locations to GitHub URLs to at least link to the code. It's terribly frustrating to have literally nothing that can easily get me to the code to look at what's going wrong.

_Originally posted by @eric in https://github.com/getsentry/sentry-go/issues/740#issuecomment-1785831952_

**Comment by dcramer** [comment]
Would be great if we could get ahead of this problem and find a way to pull in source snippets from GitHub

**Comment by cleptric** [comment]
This was always a concern when it came to GitHub's API rate limits, we have this problem in Codecove all the time 🙁 
Allowing to link to GitHub even without source context would already go a long way, and I don't see any reason why we wouldn't be able to do so.

**Comment by eric** [comment]
I still don't understand why I don't have links to GitHub in my Objective-C project... If I could write a regular expression that created accurate GitHub links based on JSON, Sentry should be able to provide them.

That said, I do really want to see the inline snippets for my Go code as well, so some solution (grabbing from GitHub or uploading code) would make the Go integration actually useful for me.

**Comment by Dhrumil-Sentry** [comment]
@brianthi  our [docs](https://docs.sentry.io/product/integrations/source-code-mgmt/github/#stack-trace-linking) say that stack trace linking is supported for Go too, and Michi's example is for Go - any idea what's different here?

**Comment by cleptric** [comment]
It's only available if source context exists on the Sentry stack trace, but this is not always possible. But we still have all the required properties at hand, like filename and line number.

**Comment by rachrwang** [comment]
@cleptric - thanks for filing this ticket! We're going to be making a series of improvements to Issue Details in Q4, and will follow up later this week if we have any questions for you. We'll update this ticket once we've figured out sequencing & timelines. cc @malwilley

**Comment by jerbob92** [comment]
It's a bit unclear to me if anything happened related to this. Anyone has some insights?

> It's only available if source context exists on the Sentry stack trace, but this is not always possible. But we still have all the required properties at hand, like filename and line number.

I think it's almost never available? Why would anyone ship their source code with their binary?

**Comment by malwilley** [comment]
@jerbob92 since this issue was created, we now will provide links to your source code for native stack traces (provided you have a source code integration and [have it set up properly](https://docs.sentry.io/product/sentry-basics/integrate-frontend/configure-scms/)).

Viewing source code inline, however, has not changed. It looks like there is an [issue here](https://github.com/getsentry/sentry-cli/issues/1979) related to making that process easier.

**Comment by jerbob92** [comment]
@malwilley thanks, I did not find that issue myself, will start tracking that one!

**Comment by MichaelSun48** [comment]
Looks like the original issue was resolved, going to close this out. Feel free to reopen if I mis interpreted the conversation.
