### ISSUE TITLE
There's no way to select the path of a source file for Objective-C

### ISSUE THREAD

**Issue by eric** [getsentry/sentry#59058]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

https://github.com/getsentry/sentry/assets/470/9364544b-0548-4d02-b8ed-fe117087ef5e

### Expected Result

I expect to be able to select more than just the filename.

### Product Area

Issues

**Comment by lobsterkatie** [comment]
@eric , if you go to the `...` menu and choose Raw Stack Trace, does that solve your problem?

**Comment by eric** [comment]
I don’t see full file names there.

**Comment by lobsterkatie** [comment]
Can you please send a link to your event? Or, if you don't feel comfortable with that, can you please send the number after the word `issues` in the URL?

**Comment by eric** [comment]
@lobsterkatie 4274396182, 4329905530, 4600620753
