### ISSUE TITLE
Alerts filter by release > release:latestProduction

### ISSUE THREAD

**Issue by realkosty** [getsentry/sentry#59056]
### Problem Statement

A certain enterprise-size customer relies on Sentry to monitor their desktop and mobile apps.
Naturally, their release adoption cycle is relatively slow and they use semantic versioning. At any moment in time they have:

**(A)** 1 current production release available for all customers to update to
**(B)** multiple current alpha's and beta's (release candidates) actively worked on by the dev team.
**(C)** multiple past production releases and backports (customers are not forced to update)
**(D)** multiple past alpha's and beta's circulating internally on all of the company's 1000+ employees' devices as all employees are enrolled in beta-testing program. These can linger for awhile since updates are not forced. There also may be stale development branches based on old alphas/betas sending events as well.

They would like to be alerted whenever a new issue is introduced in **(B)** so that it can be assigned and fixed immediately (instead of having them pile into a long list that has to be triaged before cutting release). Using environment alone to filter is not an option because it will include errors from **(D)**, which are not relevant and can add a lot of noise.

---
### Solution Brainstorm

Implement `release:latestProduction` and make it possible to reference it using a comparison relation (<,<=,>,>=,==) in relation to `release` attribute in the following pages:
- Issue Alerts "If" section 
  - currently doesn't expose `release` property, only “The event is from the latest release”
  - `tags[release]` is empty by default + tags don't allow numeric operators
  - we need to either start allowing negation per each if-condition OR fix the [semantics of firstRelease](https://github.com/getsentry/sentry/issues/59056#issuecomment-1841640839) + expose it in Issue Alerts,  otherwise they won't be able to have more than 1 if-condition in their issue alerts (or maybe that's acceptable?)
- [optional?] Metric Alert filters in section "[2] Filter Events"
- [optional, for consistency] Issues stream filters, Dashboards, Discover. 
 
`release:latestProduction` is a "magic constant" (similar to `release:latest`) defined as:
release that is most recent release that has seen at least X events tagged with "production" environment.
- "most recent" (either SemVer OR dateReleased) is defined according to [ordering determined by release version format and used elsewhere in the product](https://www.notion.so/sentry/Release-Format-and-Ordering-887364c1e45c4d6c9b92cb9eb3e33991).
- X must be user-configurable in the Settings and is necessary to filter out app store running the app before actually releasing it to real users. It should have a reasonable default value.
- "production" defined as case-insensitive `*prod*` string match is acceptable but ideally is user-configurable.
  - potential design question when multiple production environments exist, whether actually (regions, whitelabels/customers, etc) or on paper (renamed 'prod' -> 'production' at one point).
  - could be solved with magic behavior around when combined with `environment` filter in alert

Above feature would allow this customer to set up 1 alert and have it "just work" instead of needing manually change the cut-off release in the alert every single time.

### Product Area

Alerts

[FEEDBACK-1458]: https://getsentry.atlassian.net/browse/FEEDBACK-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1969) by [Unito](https://www.unito.io)

**Comment by lobsterkatie** [comment]
This is an interesting idea! @Dhrumil-Sentry, have we considered something like this in our roadmap?

**Comment by Dhrumil-Sentry** [comment]
We've heard similar feedback from Mobile customers who have similar release scenarios -but we have not actively considered this

@realkosty we'll add this to the backlog but I don't think we'll be getting to this in the next 2 quarters.

>  Having such capability would allow this customer to set up 1 alert and have it "just work" in perpetuity instead of needing to build and maintain a CI step or cron job to update alert through API for every new production release.

This is likely the best solution for now

**Comment by realkosty** [comment]
Update:

1. Additional requirement: release should not be considered a "production release" unless it has seen > X (configurable threshold) of events.

2. @mikejihbe will be implementing something in product to address this using semver filtering with magic constants

**Comment by realkosty** [comment]
Simplified and reorganized description a bit to make it more clear

**Comment by realkosty** [comment]
Moving this out of description to avoid confusion:

### Not really a workaround but something available now that's related to this
The closest thing to a workaround that is currently available is to use the following filter in Issues stream:

```
!release.version:<(insert release immediately after latest prod release)
```

which eliminates all issues that have at least 1 event observed in latest prod release or any of the earlier releases. This is preferred over using `firstRelease` because of its semantics: ~the oldest release the error has been seen in~ the release that the first error of this type that Sentry saw was tagged with. Additionally, at the time of writing, it is not possible to use `*` globs or `<,>` on `firstRelease`.

This however is not a full workaround as it:
- **doesn't allow alerting**
- have to adjust the query as new production releases are shipped, can't be a saved query.

**Comment by scefali** [comment]
@wedamija is starting work on this soon

**Comment by serglom21** [comment]
@Dhrumil-Sentry Adding context from another customer with an Android use case where in production they get a lot of crashes that flood their notifications which is caused by dependency errors that happen as soon as a new version of the app is released - These crashes eventually get solved on their own as the users update their application;

Upon brainstorming, a functionality that would help ease this challenge would be to be able to filter alert conditions based on the latest release (as suggested in the context of this ticket) AS WELL as being able to use the "release stage" filter that is available in the releases page and some dashboards so that they can only get alerted once the release has been adopted or replaced

Is this additional filter (release stage) something that could also be implemented?

Thanks

**Comment by realkosty** [comment]
hey @serglom21, this has already been implemented (not rolled out to all customers yet, feature flag: `organizations:latest-adopted-release-filter` in flagr)
<img width="753" alt="Screenshot 2024-01-15 at 9 19 05 AM" src="https://github.com/getsentry/sentry/assets/490201/c3c11694-98f5-47c9-b962-b54c8e7a7f9d">

> AS WELL as being able to use the "release stage" filter that is available in the releases page and some dashboards so that they can only get alerted once the release has been adopted or replaced 

yes the new filter uses `release.stage:adopted` when determining "latest release in prod". Should really say "latest adopted release in prod"

See [this doc](https://www.notion.so/sentry/Issue-Release-Filter-6268c2feb03c48a4905392fdac9c178f) for final design that answers some open questions described in this issue.

**Comment by rachrwang** [comment]
This has now shipped to prod - let us know if there are any questionts!

**Comment by realkosty** [comment]
Internal design doc: https://www.notion.so/sentry/6268c2feb03c48a4905392fdac9
