### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [getsentry/sentry#5906]
I want to use this file to build docker image on arm64 architecture,but I am not sure that can be support arm64 architecture. So I want to konw this file whether or not support arm64 architecture https://github.com/getsentry/sentry/releases/download/8.19.0/sentry-8.19.0-py27-none-any.whl

**Comment by mattrobenolt** [comment]
It does not and we have no plans to support ARM.

**Comment by longquan7** [comment]
@mattrobenolt OK,thanks

**Comment by ctrahey** [comment]
@mattrobenolt  It's been a few years, and ARM is only gaining traction, including in enterprise cloud settings (c.f. Graviton). Perhaps we can consider re-opening this and exploring the work necessary?

**Comment by mattrobenolt** [comment]
I highly doubt we’ll invest any resources anytime soon into supporting ARM since we have no needs for it. If you’d like to do the exploratory work and see what things fail, that’d be helpful. The only issues I’d really anticipate are native dependencies that we don’t control.
