### ISSUE TITLE
8.19.0: No module librabbitmq

### ISSUE THREAD

**Issue by 0x4e3** [getsentry/sentry#5907]
Hi all! After switching broker from Redis to rabbitmq got this error. 
Was fixed with ```pip install librabbitmq```, but I wonder why does this package not mentioned in the installation requirements or why there is no information about it neither in the installation instructions nor in the "Asynchronous Workers" part of the documentation.

- The version of Sentry you're using: ```8.19.0```
- Whether you're using Docker or another installation method: ```No```
- Include a stacktrace or other logs when relevant:
```python
ImportError: No module named librabbitmq
  File "sentry/api/base.py", line 82, in handle_exception
    return super(Endpoint, self).handle_exception(exc)
  File "sentry/api/base.py", line 177, in dispatch
    response = handler(request, *args, **kwargs)
  File "sentry/api/endpoints/system_health.py", line 18, in get
    results = status_checks.check_all()
  File "sentry/status_checks/__init__.py", line 20, in check_all
    return {check: check.check() for check in checks}
  File "sentry/status_checks/__init__.py", line 20, in <dictcomp>
    return {check: check.check() for check in checks}
  File "sentry/status_checks/celery_alive.py", line 25, in check
    size = backend.get_size('default')
  File "sentry/monitoring/queues.py", line 72, in get_size
    with self.get_conn() as conn:
  File "sentry/monitoring/queues.py", line 50, in get_conn
    from librabbitmq import Connection
```

**Comment by dcramer** [comment]
Happy to accept PRs to improve the docs here, but Celery does describe deps needed for various backends.

**Comment by 0x4e3** [comment]
Thanks for your response! 
As you wrote, Celery requires ```librabbitmq```, but only as ```extras_require```, so it will never be installed until you mention it in Sentry's requirements according to [setuptools docs](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies).
Of course, I'll make a PR to improve the docs, but I wonder why you don't want to include one more dependency.
Or, if You don't like to have an optional package in deps, just handle an ```ImportError``` in your monitoring module.

Thanks, Alex.

**Comment by dcramer** [comment]
@0x4e3 if this is erroring outside of changing CELERY_BROKER to Rabbit we should definitely fix it. We dont include "every dependency possibly required" as lots of people run with different setups, and dependencies cause random failures.

**Comment by mattrobenolt** [comment]
This should only be triggered if you told celery to use rabbitmq: https://github.com/getsentry/sentry/blob/master/src/sentry/monitoring/queues.py#L50

This is already being guarded behind a check. So we don't need to check ImportError, nothing in your workers will work without this.

**Comment by 0x4e3** [comment]
@dcramer @mattrobenolt  yes, it happened only after I told celery to work with rabbitmq. 
Ok, I understood your arguments. Thanks for your time and wonderful software!
