### ISSUE TITLE
Can't create or link gitlab issues from event (previously working)

### ISSUE THREAD

**Issue by iqrow** [getsentry/sentry#59092]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open an Issue
2. Click the Issue Tracking - Gitlab Issue + button
3. See error modal saying something went wrong

### Expected Result

Issue creation dialog is shown

## Screenshot

![b31::093050](https://github.com/getsentry/sentry/assets/188648/73fbad50-d1a5-4d4a-8962-628b6169e1ba)

## Logs

https://us.sentry.io/api/0/organizations/{org}/issues/{id}/integrations/{id}/?action=create

```
GET - 500
{"detail":"Internal Error","errorId":"4f62da6dd71d44a2b860240ed9a5a933"}
```

### Product Area

Issues

**Comment by Dhrumil-Sentry** [comment]
@schew2381 can you please take a look?

**Comment by schew2381** [comment]
Hi there, this should be fixed now! Feel free to ping me and re-open this issue if anything else pops up 🤠

**Comment by schew2381** [comment]
@iqrow Hi there, this should be fixed now! Feel free to ping me and re-open this issue if anything else pops up 🤠

**Comment by iqrow** [comment]
Confirmed fix! Thanks so much for the very fast turnaround!
