### ISSUE TITLE
Increase Ownership Rules character limit

### ISSUE THREAD

**Issue by realkosty** [getsentry/sentry#59125]
### Problem Statement

An enterprise customer is quickly approaching to the [100k characters limit for the Ownership Rules](https://docs.sentry.io/product/issues/ownership-rules/#limitations).

They are using some optimization strategies to collapse records, but the structure of our codebase does not allow to collapse into a fixed set of records and the list is constantly growing as a result.

They are asking us to increase this limit.

### Solution Brainstorm

❌ Using CODEOWNERS which has a higher limit (3MB) for the `path` rules is not an option because it means that people would be added to reviews for all those files, and this is not something they want. “Want to review” and “want to receive errors” are not always the same.

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1971) by [Unito](https://www.unito.io)

**Comment by scttcper** [comment]
added to feature flag
