### ISSUE TITLE
Add abbility to specify http method, not only url, in network details configuration

### ISSUE THREAD

**Issue by sanjadev** [getsentry/sentry#59176]
### Problem Statement

We  have a use case where we have two different methods (GET and PUT) on  the same url, and we want to capture request/response information only  for PUT. When we add this URL in networkDetailAllowUrls list, Sentry  Replay starts capturing both GET and PUT. It would be nice to have a way to specify request method, if need, beside URL.

### Product Area

Replays

**Comment by billyvg** [comment]
You should be able to do this with [`beforeAddRecordingEvent`](https://docs.sentry.io/platforms/javascript/session-replay/privacy/#example-capturing-500-status-codes-only)

**Comment by sanjadev** [comment]
@billyvg I tried using [beforeAddRecordingEvent](https://docs.sentry.io/platforms/javascript/session-replay/privacy/#example-capturing-500-status-codes-only) as suggested, but if I am seeing it correctly, the end result is that this request is not captured/logged in Network, by Sentry Replay, like it was not triggered at all. My expectations are that it is listed in "Network" tab, so that we are aware it happened, just without details for Request and Response. PUT request details for same endpoint are captured, which is OK.

**Comment by billyvg** [comment]
@sanjadev The example you linked returns `null`, which means it won't be captured. However, you can mutation `event`, and return an event that does not contain the request/response body (e.g. `delete event.data.payload.data && return event` (this is not exactly what you want, you'll have to console.log(event) and debug it a bit for what you want to remove)).

**Comment by sanjadev** [comment]
Thanks for clarifying this! I managed to get desired behavior with mutating event.

**Comment by bruno-garcia** [comment]
That's great! THanks for letting us know.
