### ISSUE TITLE
Session Replays for elements with shadowRoot (closed)

### ISSUE THREAD

**Issue by farhan-ottu** [getsentry/sentry#59175]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I'm utilizing Sentry's session replay feature to troubleshoot any potential issues within my application.

### How are you getting stuck?

 I've encountered a challenge with a specific component that has a shadowRoot configured with a "closed" mode. This configuration prevents Sentry from capturing session replays for that particular element.

### Where in the product are you?

Replays

**Comment by farhan-ottu** [comment]
The issue I'm facing is replay is captured but the element with shadowRoot displays empty space because sentry is unable to access DOM elements inside shadowRoot, with shadowRoot mode *open* replays work as expected.
Is there a way I can capture replays without removing shadowRoot closed (as it is requirement of my project)

**Comment by billyvg** [comment]
I don't think there's much we can do with closed shadow roots, as that's the purpose of have it closed
