### ISSUE TITLE
Cron: Checkin OK sent but missed by sentry

### ISSUE THREAD

**Issue by tjerkw** [getsentry/sentry#59177]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Occasionally my cron fails due to a mised checking,
but when checking the job logs, everything went fine... 

Do i need to call `Sentry.flush()` to ensure the checkin is actually deliverd on the server?

Kotlin code:

```kotlin

 fun <T> trace(val monitorSlug: String, block: () -> T): T {
        val checkInId: SentryId = Sentry.captureCheckIn(
            CheckIn(
                monitorSlug,
                CheckInStatus.IN_PROGRESS,
            )
        )

        try {
            val returnValue = block()

            Sentry.captureCheckIn(
                CheckIn(
                    checkInId,
                    monitorSlug,
                    CheckInStatus.OK,
                ),
            )
            return returnValue

        } catch (e: Throwable) {
            Sentry.captureCheckIn(
                CheckIn(
                    checkInId,
                    monitorSlug,
                    CheckInStatus.ERROR,
                ),
            )
            throw e
        } finally {
            // IS THIS NEEDED? I dont have thsu currently
            Sentry.flush(5000)
        }
}

```

### Expected Result

Checking with CheckInStatus.OK was called, but sentry didnt register it. 

### Actual Result

Expect sentry to register it

### Product Area

Crons

### Link

https://tebi.sentry.io/crons/dev-tebi-tools-closeexpiredsubledgers/?cursor=10%3A0%3A1&project=4504837629607936&statsPeriod=14d

### Version

6.30.0 (java)

**Comment by gaprl** [comment]
Hey @tjerkw, we're sorry to hear you're having issues with your check-ins -- we are investigating on could be wrong here. It would be super helpful if you could send your logs with the times check-ins were sent from your end if possible. If you can please send them to crons-feedback@sentry.io. Thanks

**Comment by gaprl** [comment]
Issue seems to have been resolved after we improved how we handle our rate limits.
