### ISSUE TITLE
Search feature with event.timestamp and UserId filter not working as intended

### ISSUE THREAD

**Issue by tajchert** [getsentry/sentry#5918]
Sentry: 8.18.0, docker

I want to search for issue (and event for it) for particular UserId and inside dates (between).
However search(web dashboard or API) seems to be not reliable in case of using with UserId.

Ex.
Web dashboard search:
**userId:XYZ** **event.timestamp**:>=2017-08-16T10:00:00 **event.timestamp**:<2017-08-16T10:00:00

(or API -> /api/0/projects/sentry/project_xyz/issues/?query=userId:XYZ event.timestamp:>2017-08-16T10:00:00 event.timestamp:<2017-08-16T10:30:00

Results -> issue number 123

Using API I list all events for issue 123 with given user, ex.
/api/0/issues/123/events/?query=userId:XYZ

And all events for that user are outside of that time range, or in some cases I got no events for that user.

**Comment by tkaemming** [comment]
I'm guessing this is another manifestation of GH-5475.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
