### ISSUE TITLE
Add Flutter profiling to onboarding

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry#59198]
### Problem Statement

Based on https://github.com/getsentry/sentry/issues/54093, add Profiling to Flutter (currently in alpha and only available for iOS and macOS).

See:
* https://github.com/getsentry/sentry-dart/pull/1611
* https://github.com/getsentry/sentry-docs/pull/8363

### Product Area

Profiling

**Comment by bruno-garcia** [comment]
We just need the wizard in the docs repo, like this: https://github.com/getsentry/sentry-docs/tree/master/src/wizard/php/profiling-onboarding/laravel

I could get to this next week, if u don't have time @vaind 

@JonasBa offered to do the in-product changes.

**Comment by vaind** [comment]
> if we support raw Dart

we don't, it's using sentry-cocoa from the flutter package
