### ISSUE TITLE
Real-time updates not working with my project (can't see events coming in until manual browser refresh)

### ISSUE THREAD

**Issue by ndmanvar** [getsentry/sentry#5920]
Not working in this project
https://sentry.io/testorg-az/react-demo/

Works in other projects. e.g. https://sentry.io/testorg-az/testproject/

Repro case:
- make sure 'real-time' updates is enabled/toggled on
- send event
- look at Sentry UI / XHRs to see if event comes through and is shown (if it never shows up, verify that refresh will make it show up, which means 'real-time' updates not working as expected)

**Comment by ndmanvar** [comment]
Cramer mentioned this might have something to do with 'Last Seen' filter and cursor

**Comment by ndmanvar** [comment]
![screen shot 2017-08-18 at 3 56 37 pm](https://user-images.githubusercontent.com/314061/29480541-db247c34-842d-11e7-90cc-f3a10e336f5a.png)

**Comment by tkaemming** [comment]
Unassigned myself per our earlier conversation about sprint priorities.

**Comment by EvanPurkhiser** [comment]
@ndmanvar does this happen both when the issues list is empty *and* when there is at least one issue in the list already?

**Comment by soundsgoodsofar** [comment]
@EvanPurkhiser I don't think this is actually resolved, at least in production unless sentry.io hasn't pushed the fix yet.  I've just signed up and set things up there.  Was wondering why I never get count updates until I refresh the page.

I'm just using the defaults for a new project.  It's sorted by "last seen".  Never updates when the project is new and there are no events yet or when there are events and their counts should be increasing due to new calls.

I'd consider this a critical bug.

**Comment by string-areeb** [comment]
Same behaviour in Sentry 9.0.0

**Comment by himalr** [comment]
Can confirm. It has something to do with the 'cursor' parameter presented in the ajax request. Server returns and empty list if it present in the URL.

**Comment by dsudaez** [comment]
I want to integrate sentry to my project (Backbonejs). But I think I have de same issue.

Why doesnt catch any events from my application? Please help

**Comment by EvanPurkhiser** [comment]
Hi @dsudaez. If you still don't see errors show up even after refreshing then it sounds like the issue you're facing is unrelated. Check out or [support channels](https://sentry.io/contact/support/) for a quicker way to resolve your issue.

**Comment by wedamija** [comment]
@ndmanvar @soundsgoodsofar  We've resolved two issues with this: 
 - On a new project, the waiting for event screen never goes away when the first event for the project is received
 - Events wouldn't receive updates to counts in certain cases

This issue should now be resolved.
