### ISSUE TITLE
Add Content-Security-Policy header

### ISSUE THREAD

**Issue by VorontsovMaxim** [getsentry/sentry#5923]
To reduce XSS risks it will be great to add `Content-Security-Policy` header and nonce for all inline scripts

**Comment by oxdef** [comment]
There is a mechanism called Content Security Policy which web applications can use to mitigate a broad class of content injection vulnerabilities, such as cross-site scripting (XSS). Content Security Policy is a declarative policy that lets the authors (or server administrators) of a web application inform the client about the sources from which the application expects to load resources.


It will be great if Sentry web interface will support it out of the box and enforce by default. In the most cases implement CSP support into web applicaton consist of following steps:

1. Review HTML code and try to remove all inline code (JS and CSS) and eval() usage
2. If you can't remove inline code you should use nonces/hashes
3. Prepare CSP policy and switch it on in Report-Only mode for some time
4. Fix all the bugs from the CSP log
5. Switch CSP into block mode

Additional information:
* https://www.w3.org/TR/CSP2/
* http://githubengineering.com/githubs-csp-journey/
* http://www.html5rocks.com/en/tutorials/security/content-security-policy/
* https://developer.mozilla.org/en/docs/Web/Security/CSP/CSP_policy_directives
* https://oxdef.info/csp-tester/

**Comment by mattrobenolt** [comment]
We already implement CSP on sentry.io. It’d be a little hard to bundle a policy with Sentry core, but this is super easily configurable on your own by setting this header in nginx.
