### ISSUE TITLE
Issue with Adding Widgets to Dashboard

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry#59231]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

A user is encountering some unexpected behaviour when trying to add a widget to the dashboard.

- Go to any Alert.
- Click on "Open in Discover."
- Click on "Add to Dashboard."
- The Widget creator opens up.
- Click "Save Widget."

### Expected Result

The widget should be added to the Dashboard.

### Actual Result

Re-directed to dashboard but no widget exists.

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1973) by [Unito](https://www.unito.io)

**Comment by ale-cota** [comment]
hey, @Kobby-Bawuah! Sorry this issue got buried until now - do you know if this is still an issue? I've tried to reproduce this by following the steps you described, but the widget got added just fine to the dashboard. Thanks!

**Comment by bcoe** [comment]
Closing this as part of cleanup, @Kobby-Bawuah please reopen if this is still a problem for you 👍
