### ISSUE TITLE
Android Plugin fail with upload of proguard mapping - bad JSON EOF

### ISSUE THREAD

**Issue by tajchert** [getsentry/sentry#5924]
Sentry 8.18, Docker, Android plugin 1.5.0.

I'm trying to use auto upload of mapping.txt file, however I get:
```
Error:bad json: EOF while parsing a value at line 1 column 0
Error:Execution failed for task ':app:persistSentryProguardUuidsForDebug'.
> Process 'command '/var/folders/ft/pfd25wb91rzc761x93t0s3_r0000gn/T/.sentry-cli8590557722218880974.exe'' finished with non-zero exit value 1
```
I have defaults.project, defaults.org, defaults.url, auth.token in sentry.properties (change in any of them result in error specific for particular field so I assume this is set correctly).
I don't use printmapping file method, however I use DexGuard (8.0.07).

My mapping.txt is located in: "app/build/outputs/mapping/debug/mapping.txt"

Can you point me in right direction what this error is about and how to solve it? I would guess that EOF = file was empty (wrong path?) but I don't see how I can adjust my mapping.txt path in Android Sentry plugin.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
