### ISSUE TITLE
[Replay Details] New timeline, zoom indicators

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#59258]
The idea is simple, the final css/style is TBD, but what i'm thinking is that we need to indicate on the scrubber line what is the Timeline looking at?

A story in two images:
- first image is 1x zoom, the Timeline is looking at the whole replay (so is the scrubber below)
- second image is 2x zoom, the Timeline is looking at the first 50% of the replay. The green lines are there to match.

![Image](https://github.com/getsentry/sentry/assets/187460/4d37db0b-f3f7-4ffe-8356-87fc2f59c527)
![Image](https://github.com/getsentry/sentry/assets/187460/a835c4ba-ad01-41e7-90c9-489bcd1d6c4f)

The first part of this ticket is to do the math (Math! more of the same, but slightly different again!)
The second part of this ticket will be to apply whatever styles we get from the design team. ie: things like colors/height/zindex, etc. cc @Jesse-Box

**Comment by ryan953** [comment]
related to https://github.com/getsentry/team-replay/issues/199

**Comment by Jesse-Box** [comment]
Figma file [here](https://www.figma.com/file/3URUL8ZlVO0YM9ISWMonSP/Event-Timeline?type=design&node-id=0%3A1&mode=design&t=ybZjQgTJgMUNPd2M-1)

### Zoomable = False
![Zoomable=False](https://github.com/getsentry/sentry/assets/6508377/c9cfb947-b05c-46e3-8413-ba164c91bb9d)

### Zoomable = True, Zoom Magnification = 1
![Zoomable=True, Zoom Magnification_ 1](https://github.com/getsentry/sentry/assets/6508377/10bc2621-85a8-425e-a0ab-a8453a4d2049)

### Zoomable = True, Zoom Magnification = 2
![Zoomable=True, Zoom Magnification_ 2](https://github.com/getsentry/sentry/assets/6508377/b0e50ca3-850b-453f-b403-e8ca696e0068)
