### ISSUE TITLE
You cannot select dates that span across months

### ISSUE THREAD

**Issue by hubertjakubiak** [getsentry/sentry#59265]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Open the application and navigate to the section where date selection is required.
2. Click on the date picker control to initiate the date selection process.
3. Attempt to select a start date in one month (e.g., October 31st) and an end date in the following month (e.g., November 1st).
4. Observe that the date picker currently does not allow this selection and may display an error message or prevent the selection of November 1st.

### Expected Result

The date picker should allow users to select a start date in one month (e.g., October) and an end date in the following month (e.g., November) without any errors or restrictions. The selected date range should be valid and reflect the chosen date span.

### Actual Result

The date picker currently prevents the selection of November 1st when attempting to select it as the end date for a range that spans two months. An error message or restriction is encountered, preventing the desired date range selection.

### Product Area

Issues

### Version

23.10.1

**Comment by lobsterkatie** [comment]
You're right, that does seem like a bug! In the meantime, the best current workaround would be to pick the correct start date and the wrong end date, apply that to the stream, and then edit the end date in the URL. (This is far from ideal, I grant, but it does work.)

@scttcper or @malwilley, how hard or easy would this be to fix?

**Comment by scttcper** [comment]
You can currently select the next month but you need to navigate to the next month and not use the greyed out dates. We're using a date picking library here, not sure what it would take to fix.

**Comment by scttcper** [comment]
we might consider hiding days not belonging to the current month

```
/* Hide days not belonging to the current month */
.rdrDayPassive {
  visibility: hidden;
}
```

**Comment by lobsterkatie** [comment]
Yeah, I think that's a good idea, and would be an effective way to solve (half of) the confusion here. (The other half of the confusion, at least for me, was that you can click and drag over a number of days to set the date range, which means I never realized I could click the start date and separately click the end date, so I was trying to drag over the last few days of one month, change months, and then continue dragging over the first few days of the next month, which didn't work at all - and, in retrospect, shouldn't. But is there a way to disable the dragging option, so people are forced into the two-clicks method?)
