### ISSUE TITLE
Audit Log - Be able to see if a project has been unassigned/assigned from a team

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#59285]
### Problem Statement

Currently it's not possible to see in the audit log which teams got which projects assigned. 
But more importantly which projects are getting disconnected from a team.

The issue here is, if you have a big project count. And you remove one project-team connection by accident you don't know what to re-add again.

### Solution Brainstorm

Add the data to the audit log so they can find it back.

### Product Area

Settings

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1976) by [Unito](https://www.unito.io)

**Comment by Dhrumil-Sentry** [comment]
This is definitely something that should be in the audit log, Have added this to our backlog, we don't have a timeline yet but will try to get to this soon
