### ISSUE TITLE
Team Projects - There needs to be a "are you sure" when removing a project-team connection.

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#59286]
### Problem Statement

Currently it's possible to remove a project assignement from a team without any confirmation.

If you have a big set of projects you are not able to know which one has been removed if it was by accident.
The audit log doesn't show anything [yet](https://github.com/getsentry/sentry/issues/59285)

### Product Area

Settings - Teams

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1977) by [Unito](https://www.unito.io)

**Comment by Dhrumil-Sentry** [comment]
Adding this to the backlog, this action should be audited and we should have a confirmation modal
