### ISSUE TITLE
Sentry integration is unreliable

### ISSUE THREAD

**Issue by bww** [getsentry/sentry#5930]
I've configured the Slack integration for one of my projects. The configuration is correct and when I press the "test" button I get the test exception. However, actual exceptions are never sent to Slack, even though I still get emails about them, as I would expect.

## Requested details
- The version of Sentry you're using: Hosted version
- Whether you're using Docker or another installation method: n/a
- Include a stacktrace or other logs when relevant: n/a
- Include a redacted version of your configuration when relevant: n/a

**Comment by dcramer** [comment]
@bww alerts are generated based on the rules configured for a project, which is not always the same for when you get an email (alerts vs workflow emails).

https://docs.sentry.io/learn/notifications/

We're not aware of any issues with the system, and without more details this ticket is unfortunately not actionable.

**Comment by bww** [comment]
Would you like more details? You've closed this issue so I get the impression you're not interested.

In case you are: I have two projects configured identically; alert settings have not been changed from defaults beyond adding the Slack integration.

One gets Slack alerts as I would expect, one doesn't get any at all. I suspect it's due to the fact they are using the same Slack channel although I haven't attempted to verify this.

**Comment by dcramer** [comment]
@bww do you mind sharing the org/project slugs? you can email support@ as well with more details (just reference this ticket)

The primary reason I'm closing it is just to maintain a noise level on our issue feed. Often things are misunderstandings, and this is one of those historically. It's possible Slack is rate limiting or erroring, and we dont expose that outside of internal auditable logs/metrics. 

The main thing is just knowing that by default only "new issues" would send to Slack.
