### ISSUE TITLE
How can I view a complete list of all error events for a user?

### ISSUE THREAD

**Issue by dbruning** [getsentry/sentry#59317]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

A user reports he is having issues with the software.
I want to go into Sentry and type their email address somewhere, and see a full list of their errors, chronologically, not grouped.

### How are you getting stuck?

I go to Sentry and filter the "Issues" view by their email address; I can see a list of issues.
If I go into each issue, I can click on "All events" and look for (or filter for) their email address. 
That's very time-consuming. I don't want a per-issue All Events view; I want a global filterable All Events view.

### Where in the product are you?

Issues

**Comment by JoshFerge** [comment]
the Discover feature should allow you to do this! https://docs.sentry.io/product/explore/discover-queries/
