### ISSUE TITLE
Expand client outcomes on the stats page

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry#59320]
Today, we only expose three categories to our users.

<img width="360" alt="Screenshot 2023-11-02 at 22 39 38" src="https://github.com/getsentry/sentry/assets/6617432/b454d73e-b1ce-450d-8500-0a5866fdd7a2">

This makes debugging issues with the SDKs too cumbersome.
We should expose some stats we show on `_admin`.

<img width="549" alt="Screenshot 2023-11-02 at 22 41 05" src="https://github.com/getsentry/sentry/assets/6617432/df617d57-1fb5-420b-8a23-f56209bccfef">

**Comment by cleptric** [comment]
In https://github.com/getsentry/sentry/issues/67801, there was an ask to set up alerts on certain outcomes. We should consider this as well.

**Comment by matejminar** [comment]
Related: https://github.com/getsentry/sentry/issues/42940
