### ISSUE TITLE
Stability of APIs with Unknown Status

### ISSUE THREAD

**Issue by HYuanAi** [getsentry/sentry#59336]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

We are exploring using Sentry API to query about issues and events. One of the things we would like to do is to count events/issues filtered/grouped by tag values. 

### How are you getting stuck?

We found out that there quite a few endpoints with unknown status, but which may be useful for us. Are they considered stable and is it advisable to use them? 

### Where in the product are you?

APIs

### Version

23.8.0

**Comment by Dhrumil-Sentry** [comment]
@HYuanAi could you please share examples of APIs that you would like to use but find the status to be uncertain?

**Comment by sentaur-athena** [comment]
To add more context the unknown APIs needs to be reviewed to determine their stability and be published. Not all of them are stable or unstable. Specific examples can help.

**Comment by HYuanAi** [comment]
We are interested in enabling plugins with configurations at this endpoint: `/api/0/projects/{organization_slug}/{project_slug}/plugins/{plugin_id}/`, probably through PUT and POST.

**Comment by sentaur-athena** [comment]
@HYuanAi plugins in general are deprecated so this endpoint will not be maintained moving forward and I would not consider it stable. We don't have a timeline for full deprecation though so if you like you can test to ensure it's doing what you need and use it, but that may change any time.

**Comment by HYuanAi** [comment]
@sentaur-athena I want to enable data forwarding to SQS through some API, do you perhaps know the best way to do this? On the official documentation for APIs, the only way is to register a service hook (documentation for which I could not find anywhere else), and create a service to forward those events to SQS. But if data-forwarding to SQS is already implemented, I see no benefit of implementing this ourselves with a service hook.
