### ISSUE TITLE
Text for Subject + Body for custom rules notifications

### ISSUE THREAD

**Issue by RaduW** [getsentry/sentry#59356]
Provide final text for the content of the emails sent to the custom rule creators when enough samples are collected.

The following details are available (and can be used in the  body or the subject)

The CustomRule 
 - date added
 - start date
 - end date
 - projects (when not an org rule)
 - the org
 - the original query
 - num_samples to collect (hard coded to 100 at the moment)
 
The User information (from the custom rule)
- username
- name
- email

The number of the samples collected until now

Not 100% sure if we can provide a deep link to the query ( since it may come from either performance of discover), if that is desired it can be achieved relatively easily in the future by also storing information about where we created the rule at rule creation (maybe in a followup PR).

**Comment by RaduW** [comment]
Suggestion from @matejminar Add deep links to both performance and discover.

**Comment by Jesse-Box** [comment]
>Suggestion from @matejminar Add deep links to both performance and discover.
I also agree this functionality would close the loop on the user experience

@RaduW 

Do we need anything more than this?

```
Hello {name/email/null},

We've collected ${num_samples} samples for the following search query:

<code>${query}</code>

Click the link below to see samples
<a href="${deeplink}">See Samples</a>
```
