### ISSUE TITLE
Remove Secret Keys

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#5940]
Let's do it.

**Why do they exist?**

We originally went with a pattern of private/public keys so that we could more safely allow API requests to fully verified clients. The public key was introduced to allow JavaScript clients to authenticate without sacrificing the safety of private keys.

**Why remove them?**

Over time keys have evolved to serve only the purpose of SDK submissions. They allow you to do nothing other than submit event data. Given that's not going to change (for security reasons), there's no reason to maintain a private key. We can still prevent obvious/accidental embedded abuse on web clients when Origin's (or web client requests) are detected, but there's no need to confuse people with two different configurations.

**Agenda**

Just off the top of my head:

- Update SDKs to remove the required secret key component.
- Update ingestion to remove the required secret key component.
- Use public key/origin detection only based on headers (possibly Referer/Origin => use CORs checks?)

**Comment by BYK** [comment]
I think we've done this now?
