### ISSUE TITLE
Alert rule parsing not work as expected.

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#59417]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create and alert rule that triggers on any event.
2. Under IF add the following option:
The event's `excepton.value` value `does not contain` `OutOfTimeException`
3. Send an event with the above value as part of the exception's value. The exact use case is:
`error fetching <redacted> contract: error fetching balance, code > 0: class org.tron.core.vm.program.Program$OutOfTimeException : CPU timeout for 'PUSH20' operation executing`

### Expected Result

The alert rule is not triggered. 

### Actual Result

The alert rule is triggered. 

The workaround is to add the entire "substring" where the term value appears:
rg.tron.core.vm.program.Program$OutOfTimeException

### Product Area

Alerts

### Link

https://dev-curumas.sentry.io/alerts/rules/plain-python/11513181/details/

**Comment by malwilley** [comment]
I can verify that there's an issue here and it seems like this alert should never have been fired. Writing a test for this works as expected though, so I'm still digging into what might have gone wrong here.

**Comment by rachrwang** [comment]
@malwilley - are you still working on this issue? If not - would you be okay with Danny's team pick this up?

**Comment by ceorourke** [comment]
I looked into this a bit but could not reproduce the issue. I made a rule with this filter: "The event's exception.value value does not contain fine" (and the inverse) where my `exception.value` is "name 'test' is not defined" and it worked as expected. The code is [here](https://github.com/getsentry/sentry/blob/master/src/sentry/rules/conditions/event_attribute.py#L271-L281) where `value` is the string you set in the rule to match (or not match) on, and `values` is the `exception.values` as a list. 

@malwilley how did you verify that there's an issue?

**Comment by malwilley** [comment]
@ceorourke I had looked at the linked reproduction which was as described. It looks like the alert has been modified since though, so it's not there anymore. I wasn't able to reproduce it either. I suppose we could close this until we get more reports?

**Comment by rodolfoBee** [comment]
@malwilley  @ceorourke i adjusted the alert rule and trie to reproduce the issue again, and it is no longer reproducible. 

Marking as closed. In case anyone is runs in this issue again, please open a new issue.
