### ISSUE TITLE
Creating gitlab issue fails

### ISSUE THREAD

**Issue by sorvis** [getsentry/sentry#59425]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open an issue
2. Click the gitlab issue link
3. Click create an issue

### Expected Result

A gitlab issue would be created

### Actual Result

An error message

![image](https://github.com/getsentry/sentry/assets/1037467/dd32db94-f388-4fc9-9c6a-bfd0bfb45021)

### Product Area

Unknown

**Comment by schew2381** [comment]
Hi there, our support team will reach out to get your organization slug so we can investigate this further

**Comment by sorvis** [comment]
Seems to be resolved after I removed the integration then re-added it.
