### ISSUE TITLE
How to group issues have different (dynamic) URLs in stack-trace that are generated by third-party script?

### ISSUE THREAD

**Issue by meotimdihia** [getsentry/sentry#59420]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

I want to merge these issues
![image](https://github.com/getsentry/sentry/assets/300961/92324e75-ff51-4232-8fc4-52e6830a595d)

I read the documentation https://docs.sentry.io/product/data-management-settings/event-grouping/fingerprint-rules/?original_referrer=https%3A%2F%2Fsentry.io%2F .I am not sure about it but I feel it won't solve the problem.

https://docs.sentry.io/platforms/javascript/guides/nextjs/usage/sdk-fingerprinting/?original_referrer=https%3A%2F%2Fwww.google.com%2F
SDK fingerprint seems not to help to merge similar issues too.

This is an example of an exception (JSON):

```JSON
"exception": {
    "values": [
      {
        "type": "TypeError",
        "value": "null is not an object (evaluating 'document.querySelector(`#${id} div[id]`).shadowRoot')",
        "stacktrace": {
          "frames": [
            {
              "module": "comic/01-love-doesn-t-matter/qLm3U3nx-chapter-22-en",
              "filename": "app:///comic/01-love-doesn-t-matter/qLm3U3nx-chapter-22-en",
              "abs_path": "app:///comic/01-love-doesn-t-matter/qLm3U3nx-chapter-22-en",
              "lineno": 1,
              "colno": 291,
              "in_app": true
            }
          ]
        },
        "raw_stacktrace": {
          "frames": [
            {
              "filename": "app:///comic/01-love-doesn-t-matter/qLm3U3nx-chapter-22-en",
              "abs_path": "app:///comic/01-love-doesn-t-matter/qLm3U3nx-chapter-22-en",
              "lineno": 1,
              "colno": 291,
              "in_app": true
            }
          ]
        },
        "mechanism": {
          "type": "instrument",
          "handled": false,
          "data": {
            "function": "setInterval"
          }
        }
      }
    ]
  }
  ```
  
It looks like because the error was generated by a third-party script  => the sourcemaps doesn't work here.
Dynamic path in next.js can't be solved.

### How are you getting stuck?

I think we can merge these exceptions because they have the same value:

`null is not an object (evaluating 'document.querySelector(`#${id} div[id]`).shadowRoot')`

But it looks like Sentry merged them by stack trace.
Please guide me on how to merge them/solve this problem.

### Where in the product are you?

Issues

### Version

23.10.1

**Comment by scefali** [comment]
@meotimdihia Maybe you want to change your inbound filter rules to block these third party script errors? See: https://docs.sentry.io/product/data-management-settings/filtering/

**Comment by jangjodi** [comment]
Thank you for bringing this to our attention @meotimdihia. We're currently working on an initiative to improve grouping for Next.js [here](https://github.com/getsentry/sentry/issues/59564)

**Comment by lobsterkatie** [comment]
@meotimdihia, as long as you have a reliable way of recognizing such events, you can either

a) filter them - the way you're doing it is the correct way,
b) capture them but group them by setting the fingerprint in the SDK (also in `beforeSend`), or
c) capture them but group them by using stacktrace rules to exclude the bad frames from the grouping calculation (docs [here](https://docs.sentry.io/product/data-management-settings/event-grouping/stack-trace-rules)).

We don't automatically do any of these things because there's no way to consistently detect for everyone that either of those is the desired behavior (which indeed it might not be for some folks).

**Comment by jangjodi** [comment]
I'm going to close this issue, as the solution Katie mentioned seemed to have worked. Please re-open this ticket if more support is needed.
