### ISSUE TITLE
Releases filter in Dashboard doesn't show enough options

### ISSUE THREAD

**Issue by gid-sentry** [getsentry/sentry#59433]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open a Dashborad
2. Try to filter by Release with events within the time period selected

### Expected Result

All releases with events in the time period selected will be visible

### Actual Result

Only releases *created* within the time period selected will be visible

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1994) by [Unito](https://www.unito.io)

**Comment by narsaynorath** [comment]
^ Just a heads up, that PR removes the date filter so you should just be able to see all releases in the selector all the time. I'll update again once it's merged and deployed

**Comment by narsaynorath** [comment]
@gid-sentry this should be deployed now!
