### ISSUE TITLE
[Design] Replay: Allow watching a replay when it's embedded in an issue

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#59463]
Today when you open an issue in Sentry, you end up seeing something like this: 

![image](https://github.com/getsentry/sentry/assets/1633368/2a2f1aa9-6ef5-40d7-83a7-5d5d18b5be85)

As the button indicates, this will **Open** the replay, and it does so by redirecting you to the Replay Details page.

There are numerous reasons why the first iteration of Replay took this route, but feedback is constant: We'd like to watch the replay inline.

Things to consider:

1. Design needs to be clear that there's "more to it". Watching inline is going to unlock quick preview of the replay, but for new users in particular, we need to be clear that there is a whole debugging tool in the Replay Details page with Console, Network, Errors, Tracing, etc.
2. It shouldn't/doesn't need more than just the video. The goal is to not take a lot of space and to be a quick view. If users want more capabilities, a further 'click' should take them to the replay details page.

**Comment by Jesse-Box** [comment]
Relates to https://github.com/getsentry/sentry/issues/59280

**Comment by Jesse-Box** [comment]
@bruno-garcia, @jas-kas @ryan953 

The issue teams pretty good about the current state of the design, so assuming opinions won't change too much in the new year, im going to mark this ticket as done.

https://www.figma.com/file/nxwvYc8kZKHE8q8V2d1zqR/Specs%3A-Issue-Details-Replay-Section-v2?type=design&node-id=132%3A1666&mode=design&t=r5MT6ub2Rlz9jWRB-1
