### ISSUE TITLE
Allow longer custom tag names

### ISSUE THREAD

**Issue by yuval-sentry** [getsentry/sentry#59480]
### Problem Statement

Sentry allows users to create their own custom tags, but the max length for a tag name is currently 32 characters, if the tag name exceeds that the tag name won't show up, the user will se `<invalid>` instead.

### Solution Brainstorm

Can the tag/key name max length be increased?

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1982) by [Unito](https://www.unito.io)

**Comment by ceorourke** [comment]
This is more of a question/request for the @getsentry/ingest team

**Comment by olksdr** [comment]
@ceorourke 

I've checked the ingest part and we do allow the tags keys and tags values [to up to 200 chars in length](https://github.com/getsentry/relay/blob/1bc9fc9830dee70ca2033f80e5c7082ed4c007fb/relay-event-schema/src/processor/attrs.rs#L133-L134)

Also I'm not sure if that correct place, but on the sentry side we have limit set [also to 200](https://github.com/getsentry/sentry/blob/63b5963cee7e47eb5005d7345b19170c74e9719a/src/sentry/sentry_metrics/consumers/indexer/tags_validator.py#L11-L12) also [see here](https://github.com/getsentry/sentry/blob/63b5963cee7e47eb5005d7345b19170c74e9719a/src/sentry/sentry_metrics/configuration.py#L14)  
At least those are limits in the Sentry I could find. 

I'm not sure where are those 32 characters limit comes from.

**Comment by ceorourke** [comment]
I do see that the [docs](https://docs.sentry.io/platforms/python/enriching-events/tags) (not just Python, but that's one example) says the key limit is 32, but I tested locally and was able to create a tag value with more. I also tested `sc.mobile_foundation_dbapp_use_sentry_ios`, just long keys in general (longest was 56 chars), keys with underscores, keys with periods, keys with underscores and periods, etc. and I wasn't having an issue. Which SDK are you using @jboulter11 ? The only thing I can think of is it might be related to that - I was using the Python SDK.

**Comment by jboulter11** [comment]
I'm using the iOS SDK.

**Comment by jboulter11** [comment]
This is how it manifests in the UI

<img width="1240" alt="Screenshot 2023-11-14 at 11 49 02 AM" src="https://github.com/getsentry/sentry/assets/6633472/91348f1b-656a-4d73-945b-0c0e9db594d5">
<img width="143" alt="Screenshot 2023-11-14 at 11 49 10 AM" src="https://github.com/getsentry/sentry/assets/6633472/26090902-40e6-4905-86f3-7bef82f3e789">

**Comment by ceorourke** [comment]
Thanks - I pinged the SDK team internally to see if they have any ideas.

**Comment by armenzg** [comment]
I have tested that we can handle very large key lengths.
I've pinged the SDK team about this.

**Comment by armenzg** [comment]
I believe we have resolved this.

**Comment by jboulter11** [comment]
For context, in case some poor soul finds this issue and is trying to debug this issue for themselves, we simply had to update our Sentry Relay proxy to a version which had increased limits for tag key size to match the rest of the platform. 👍 

Thank you for your help here!
