### ISSUE TITLE
No way to unsubscribe - lost 2FA and unable to reset it, login and unsubscribe

### ISSUE THREAD

**Issue by Jess-Gibson** [getsentry/sentry#59483]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1.lose your 2FA
2.Get 1000s of emails from sentry
3.try to unsubscribe
4.try to login as thats the only way
5.try to reset
6.try to submit help ticket
7.need to login
8.write up here

### Expected Result

I can unsubscribe from emails

### Actual Result

No way to login to unsubscribe

### Product Area

Sign In

**Comment by JLuse** [comment]
@Jess-Gibson can you please submit a support ticket to support@getsentry.com with your organization slug and details on what you're facing? The team can further trouble shoot from a support thread.
