### ISSUE TITLE
Trigger an Alert when an Issue Changes Assignee

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#59507]
### Problem Statement

My use case is currently I have an alert rule to post to Slack when there's a new issue created/escalating, with a filter of "Assigned to my team".

However, when another team reassigns an issue to my team, I'm missing a notification on that and instead will only see it once I go into the Sentry dashboard.

### Solution Brainstorm

I would like for a notification when an issue isn't new, but has been newly assigned to my team.

### Product Area

Alerts

**Comment by scefali** [comment]
@ReneGreen27 we have workflow personal notifications, would that work? See [here](https://docs.sentry.io/product/alerts/notifications/#workflow-notifications).
