### ISSUE TITLE
Cannot create metric alerts for transactions through Discover

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#59513]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a query for your transactions on discover
![image](https://github.com/getsentry/sentry/assets/81985895/9c5fed90-2a9f-4b64-8b19-51e7e0a88033)

2. Click on "Create Alert"
3. On Step 1 "Define your Metric" choose either "Transaction Duration" or "Custom Metric" with "transaction.duration"
4. On Step 3 "Set thresholds" set any threshold for the Critical status (ie. 300)
5. Click on "Save Rule"
![image](https://github.com/getsentry/sentry/assets/81985895/a26f79f0-4134-4cc8-86f5-8f4e8d44d318)

### Expected Result

The new Metric Alert rule is saved.

### Actual Result

The following error is shown:
![image](https://github.com/getsentry/sentry/assets/81985895/e8ec388f-5b23-4414-bdbe-9ea009b58ee4)

Another thing to note is that when going to create this alert from Discover, the following message appears at the top of the page:
![image](https://github.com/getsentry/sentry/assets/81985895/adb27e9d-db96-41f1-94c0-a4dda0d3e3ac)

It looks like `event.type:error` is chosen for the creation of the metric alert by default. This will remain no matter what kind of alert we try to set up, and will therefore make the alert rule invalid if we try to monitor anything related to transactions.

### Product Area

Alerts

**Comment by malwilley** [comment]
Can confirm that this is a real bug for the reason you describe: The query uses the errors dataset by default, which does not work with the transaction duration metric alert.

@scttcper do you know if there is a simple way for us to select the correct dataset here? Maybe we should be doing that when you switch from "Number of Errors" to "Transaction Duration"?

**Comment by saponifi3d** [comment]
Hey @InterstellarStella - we recently released an update that should allow you to save this Alert.

You mentioned,
> On Step 1 "Define your Metric" choose either "Transaction Duration" or "Custom Metric" with "transaction.duration"

This is where the fix happened. If you select `Transaction Duration` or the custom metric with a transaction duration, it should correctly save the alert. We're also investigating a fix, so the dataset is correctly set when you load the alerts page.

Thanks so much for reporting this issue! Please let me know if you're still running into issues with this work-around.
