### ISSUE TITLE
Chained exception display issues

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#5954]
- the highest frame should be expanded by default, but right now the (first?, shown last) exception expands its frame
- app-only looks pretty bad when one exception has app frames and others dont http://i.cra.mr/3V462u0I2C1F
- the raw stacktrace generation is not correct, at least in python, as the exceptions are shown in the wrong order

**Comment by dcramer** [comment]
lets also make sure we get jest tests in place when we resolve these

**Comment by dcramer** [comment]
See also https://github.com/getsentry/sentry/issues/5565

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
