### ISSUE TITLE
An exception occurs when clicking Profiling

### ISSUE THREAD

**Issue by heaquan** [getsentry/sentry#59540]
### Self-Hosted Version

23.10.1

### CPU Architecture

X86_64

### Docker Version

23.0.4

### Docker Compose Version

v2.23.0

### Steps to Reproduce

After installation, open the web interface and click proiling. An error appears on the console as shown below.

![20231107142018](https://github.com/getsentry/self-hosted/assets/7976188/f1ba2455-fa99-4923-a871-609e1a3453e4)

### Expected Result

The page is normal and there are no errors in the console.

### Actual Result

![20231107142018](https://github.com/getsentry/self-hosted/assets/7976188/e05600e9-399f-4a66-a096-e42e6c5452f1)

**Comment by Zylphrex** [comment]
@heaquan are you able to get the backend error that's causing the 500 response? A stack trace will be ideal.

**Comment by heaquan** [comment]
> @heaquan are you able to get the backend error that's causing the 500 response? A stack trace will be ideal.

Where can I see the backend stack information?

**Comment by Zylphrex** [comment]
Are you able to check if there is a container running `vroom`? Additionally, is your self hosted instanced setup to report errors to itself? If so, can you check to see if there's any errors there?

**Comment by heaquan** [comment]
` vroom` is running normally

**Comment by Zylphrex** [comment]
Is your self hosted instance set up to report errors to itself? If so, can you check to see if there are any errors there? Without additional information, it's hard to say what's wrong here.

**Comment by cmanallen** [comment]
Closed due to inactivity.  Please re-open if the issue persists on the latest version of Sentry.
