### ISSUE TITLE
Create issue not utilizing correct raw stacktrace

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#5955]
This is at least true for Python + GitHub:

https://github.com/getsentry/zeus/issues/17

- The chained exception order is backwards (see also https://github.com/getsentry/sentry/issues/5954)
- the exception seems repeated
- theres some odd spacing

**Comment by mitsuhiko** [comment]
For iOS raw reports we moved the code to the server because we also have a text file download and wanted to reuse the code.  I feel like it would make sense to move the raw stuff in general to the server (and then dump it out with the event response) to make this consistent.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
