### ISSUE TITLE
Sentry depends on old version of botocore, causing some sentry-plugins to break

### ISSUE THREAD

**Issue by boboli** [getsentry/sentry#5959]
When upgrading to sentry 8.19.0 using pip, it installs botocore 1.5.70 as a dependency as defined by the [wheel](https://pypi.python.org/pypi/sentry):
```
Successfully installed botocore-1.5.70
```

However, when I try to run `sentry upgrade`, a bunch of sentry-plugins show these errors: 

```
ContextualVersionConflict: (botocore 1.5.70 (/home/robinhood/sentry_venv/lib/python2.7/site-packages), Requirement.parse('botocore<1.7.0,>=1.6.0'), set(['boto3']))
```

The exception seems to suggest that the plugins want a conflicting version of botocore. This seems to be causing the crashing plugins to no longer be active under all integrations (the one we use is Slack):

![image](https://user-images.githubusercontent.com/4108038/29601224-37fc22d6-878f-11e7-9c64-ce8b66090105.png)

We are using sentry-plugin==8.19.0. If this issue should be filed to the sentry-plugins repo, lemme know and I'll do that.

Install details:
- The version of Sentry you're using: 8.19.0
- Whether you're using Docker or another installation method: pip install in a virtualenv, no docker

**Comment by boboli** [comment]
Installing the latest `boto3` package (after installing sentry, since reinstalling sentry will revert `botocore`) and restarting everything seems to have fixed it. `boto3` pulls in a newer `botocore` (1.6.5) and the plugins show up correctly.

**Comment by mattrobenolt** [comment]
https://github.com/getsentry/sentry/commit/38d9f52c1667760deb1450254955270a4163cba0 :)

So looks like this hasn't been released yet, but boto3's minor release bumped them up to a non-minor release of botocore. So I'd just do `pip install boto3==1.4.5` to explicitly choose the highest version we can use. And moving forward, this will be fine.
