### ISSUE TITLE
Getting issue Exception is already source mapped and first resolved frame points to

### ISSUE THREAD

**Issue by aloksingh3112** [getsentry/sentry#59600]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I am trying to enable source map for my project followed every step in sentry doc but always giving me this error 
Exception is already source mapped and first resolved frame points to:

    fetchUrl,
    priority,
    label,
    statusCode,
  }) => {
>   Sentry.captureException(new Error(errMsg), {
      tags: { fetchUrl, priority, label, statusCode },
    });
  };

this is my webpack config 
![carbon](https://github.com/getsentry/sentry/assets/27079355/ad7a9499-1936-48f4-90ec-f07db1367f5a)

### How are you getting stuck?

I am not able to enable source map for my project 

### Where in the product are you?

Issues - Source Maps

**Comment by lforst** [comment]
Hi, what error are you getting? Can you share a link to the Sentry event? Thanks.
