### ISSUE TITLE
Issues - Issues overview shows empty because of Snuba 

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#59610]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

So the issue stream shows "empty" when I switch to 90 days.
But it works when I go to 14 days
30 days is also empty

This is likely caused by cross db join from Snuba since we only fetch so many pages of issues to pass over to snuba to validate, in some cases it ends up failing and returning no results

### Expected Result

the solution is putting those fields into snuba

### Actual Result

<img width="1160" alt="Screenshot 2023-11-08 at 13 39 44" src="https://github.com/getsentry/sentry/assets/25929053/f0cc9721-ca3f-4ca4-b5d0-daecbeba50c3">

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-1985) by [Unito](https://www.unito.io)

**Comment by ceorourke** [comment]
@Angelodaniel is this still an issue? I checked the org linked in the synced Jira ticket and it works fine for me.

**Comment by Angelodaniel** [comment]
I just checked it myself and it seems to be resolved indeed @ceorourke
