### ISSUE TITLE
Missin icons for Queries and WebVitals on mobile view

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry#59632]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. https://sentry-sdks.sentry.io/issues/
2. make the webpage too big to the point it uses the "mobile" layout ( `ctrl` + `+` )

### Expected Result

Some icon to describe what's the button about

### Actual Result

a dot as a icon for Query and Web Vitals
<img width="945" alt="image" src="https://github.com/getsentry/sentry/assets/8229322/c0fddce0-3e76-4333-ac61-70b955450aa2">

### Product Area

Unknown

### Link

https://sentry-sdks.sentry.io/issues/

**Comment by edwardgou-sentry** [comment]
Hey @lucas-zimerman , this design is actually intentional for now, but we're aware that the dot icons are ambiguous here.
These subitems aren't permanent and we will eventually move them to a more appropriate place in the future, so this will be indirectly resolved. Thanks!
