### ISSUE TITLE
Investigation bias 0 rows bug in discover

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#59677]
If you have 0 rows, discover returns back null for numSamples I believe, so 0 rows => no Get Samples button.

**Comment by RaduW** [comment]
This is not the case.
Probably what happened is that the user did not specify `event.type:transaction`. 
The need to specify the event type in Discover was mentioned repeatedly.

![Screenshot 2023-11-09 at 12 22 15](https://github.com/getsentry/sentry/assets/5281987/df1e262f-3385-4f08-b9c4-d59507669865)

**Comment by RaduW** [comment]
Works as designed
