### ISSUE TITLE
Stop users from creating more than 50 investigation rules per project

### ISSUE THREAD

**Issue by RaduW** [getsentry/sentry#59681]
Users should not be able to create more than 50 investigation rules that apply to a project.

Need to figure out the user experience for limiting this.

We could simply disable the rule creation if adding another rule would cause any project to go over the limit.
This would be quite confusing for users, they would see that there are no samples but at the same time they will not get the UI that offers them to create a rule.

We could also keep the button and generate an error when the user tries to create a rule ( with some feedback... projects X,Y,Z would get more that 50 active investigation rules and that's not allowed).
Second option would make it clearer for the user what's going on but would frustrate them by first inviting them to create a rule only to be told that they can't do it when they press the button.

Finally we could just check and if we don't have enough samples and we also have too many rules we could place a message (similar to the one that says "Collecting samples since ... ") saying something about not being able create investigation rules because there are already too many in progress.

A complete solution would also include a UI for managing existing investigation rules, currently they will persist as active for 2 days regardless if they have collected enough data from the user's point of view or not.

**Comment by matejminar** [comment]
Let's display the Get Samples button, and if they press it and would go over 50 rules per project, the frontend will display the red toast notification (bottom right) saying "We are already getting samples for maximum amount of concurrent queries". - wording in progress
