### ISSUE TITLE
Opsgenie Integration not working on EU

### ISSUE THREAD

**Issue by pfallasro** [getsentry/sentry#59688]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to `Settings` on main page
2. Click on `Integrations`
3. Search for `Opsgenie` and click on it
4. Click on `Add Installation`
5. Fill in the form as follows:
  - Base URL: `api.eu.opsgenie.com`
  - Account name: `your opsgenie account name`
  - Opsgenie Integration Key: `your opsgenie integration key`
6. Submit form

### Expected Result

Integration should be configured to point to Opsgenie EU API: `COMPANY_NAME.app.eu.opsgenie.com`.

### Actual Result

Integration default to API: `zenjob.app.opsgenie.com`.

Because of this, the API keys we generate on the EU site don't work on the american site.

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
@pfallasro Thanks for opening this bug report, we'll take a look and keep this issue updated

**Comment by Dhrumil-Sentry** [comment]
@pfallasro please let us know if the fix does not solve the problem

**Comment by pfallasro** [comment]
Thank you so much for the fast response, seems to be working now :)
