### ISSUE TITLE
Always scrub credit card-looking things

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#5969]
Right now this only happens if you keep our default scrubbers on. To protect ourselves and others, we should enforce that this is always true (and communicate that in the UI accordingly).

**Comment by dcramer** [comment]
Probably the same with PEMs. SSNs might not be accurate enough to enforce.

**Comment by mattrobenolt** [comment]
I assume with no explicit way to opt out of this? Just confirming, I don't really see any legit reason someone would want that.

**Comment by dcramer** [comment]
Right, no way to opt-out.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
