### ISSUE TITLE
Graph glitches when there are holes

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#59702]
https://github.com/getsentry/sentry/assets/26696515/a51cd17e-0ef2-4442-a969-b375efb6cde5

**Comment by ArthurKnaus** [comment]
@matejminar this is not connected to the holes in the data. The blue series simply gets focused when hovering over its "line".
I would suggest the same solution as for bar charts -> disabling the hover state as it feels like a glitch...

**Comment by obostjancic** [comment]
Fixed in the meantime, closing
