### ISSUE TITLE
Improve cursor for bar chart

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#59709]
Crosshair cursor type is not ideal for bar charts because bars are much wider than crosshair (ddog has its own cursor type that looks like a bar with the same width as bars or buckets). vertical cursor line should be as wide as a bar in bar charts

**Comment by matejminar** [comment]
We can't do a wide bar chart-like cursor easily because echarts has an issue opened about it. Instead, we enabled snapping, which improved the experience quite a lot.
