### ISSUE TITLE
Holes in the graphs when no metrics exist in timeframe

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#59701]
Maybe an option to prefill half-empty charts with zeros - or connect distant datapoints with line?

![image (30)](https://github.com/getsentry/sentry/assets/26696515/06a52c52-7256-469b-955c-e4523ecda293)

**Comment by ArthurKnaus** [comment]
@ale-cota Do you have a chart for which this happens? I tried to reproduce it but could never encounter null values. It seems as holes in the data are always 0. 🤔

**Comment by matejminar** [comment]
The new metrics layer now always prefills with 0. This is not ideal for some metric types but it essentially closes this issue. We might open a new one in the future to address some of the concerns (is this percentage really 0 or we just don't have data?).
