### ISSUE TITLE
Crons: Deleting a monitor removes the project selection

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#59723]
If you have a project selected, and go to your monitor details page and delete a monitor, the page is redirected back to the monitors list however the project selection is cleared.

Expected behavior: the project selection should not be cleared.

**Comment by Shubhdeep12** [comment]
Hi,
Is it open?
Can i try resolving this?

**Comment by gaprl** [comment]
Hey @Shubhdeep12, thanks for the interest! You are more than welcome to try and resolve it. Please make sure to read our [CONTRIBUTING.md](https://github.com/getsentry/sentry/blob/03d1c7f5e455a768b5047ce85613dbd45f4bdd2f/.github/CONTRIBUTING.md) before submitting your PR. Thank you!

**Comment by Shubhdeep12** [comment]
Sure @gaprl . Raised a PR

**Comment by davidenwang** [comment]
Currently working on getting @Shubhdeep12 's PR to pass CI and will merge in
