### ISSUE TITLE
Asp.Net using VB

### ISSUE THREAD

**Issue by designinsist** [getsentry/sentry#5975]
I am Asp.Net developer and use VB for backend. My concern is very simple, i just want to know that  "Sentry" support VB or not ?  I contacted Sentry support and they suggest me to create an issue on GITHUB. That is why i am here. 

Waiting for you guys response. 
Bundle of thanks in advance.

**Comment by mikellykels** [comment]
Closing, opened in [raven-csharp](https://github.com/getsentry/raven-csharp/issues/188)
