### ISSUE TITLE
Source maps not being utilized

### ISSUE THREAD

**Issue by micha5strings** [getsentry/sentry#59758]
### Self-Hosted Version

23.11.0.dev0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

v2.21.

### Steps to Reproduce

1. Setup angular app as stated here: https://docs.sentry.io/platforms/javascript/guides/angular/
`
Sentry.init({
        dsn: "[CENSORED]",
        release: packageJson.version,
        dist: "production",
        integrations: [
            new Sentry.BrowserTracing({
                routingInstrumentation: Sentry.routingInstrumentation,
            }),
            new Sentry.Replay()
        ],
        environment: environment.staging ? "staging" : "production",
        tracesSampleRate: 1.0,
        tracePropagationTargets: [CENSORED],
        replaysSessionSampleRate: 0.1,
        replaysOnErrorSampleRate: 1.0,
    });
    enableProdMode();
`
2. injected & uploaded source maps via sentry-cli source maps as stated here: https://docs.sentry.io/platforms/javascript/guides/angular/sourcemaps/uploading/cli/
3. deployed app
4. fired test event

### Expected Result

Event should show human readable code.

### Actual Result

Event shows minified output.

Additional infotmation:
- the artifacts are uploaded properly (it seems) and are tagged with the correct release string and debug id
- events report matching debug id and release string

![image](https://github.com/getsentry/self-hosted/assets/117353547/eec77657-2ae7-40be-bbdf-a54274a9986d)
![image](https://github.com/getsentry/self-hosted/assets/117353547/d4f46531-085a-42e3-b94c-412e592d4a01)
![image](https://github.com/getsentry/self-hosted/assets/117353547/4a4d4dbe-7dd7-433c-b76d-830da5aa1038)

![image](https://github.com/getsentry/self-hosted/assets/117353547/6e6d83c1-0840-48f6-88ed-9f55d6fc8699)
![image](https://github.com/getsentry/self-hosted/assets/117353547/cac7d40b-addb-454a-82f6-5283ff411eee)

**Comment by lforst** [comment]
If you click into one of the uploads, does it show the debug Ids?

**Comment by lforst** [comment]
Also, can you share a link to the event?

**Comment by micha5strings** [comment]
> If you click into one of the uploads, does it show the debug Ids?

Yes, the debug Ids match.

> Also, can you share a link to the event?

Sorry, I can't. Sentry is running on premise for internal use only. There is no way to access the events from outside.

**Comment by micha5strings** [comment]
The sorucemaps are uploaded during deployment and all subsequent events show the same behaviour.

**Comment by lforst** [comment]
Do the `abs_path` and the `code_file` fields match?

**Comment by micha5strings** [comment]
![image](https://github.com/getsentry/sentry/assets/117353547/d498762f-f118-422b-a65a-df5f94e84045)
![image](https://github.com/getsentry/sentry/assets/117353547/80abc98b-8014-47fe-8a94-9548c6346ca7)
![image](https://github.com/getsentry/sentry/assets/117353547/82b19277-cfdc-4132-8feb-a3ebf19596f2)

Looks good to me

**Comment by lforst** [comment]
Ok since all of the source mapping and debug ID stuff looks right, my last guess then is that the `symbolicator` instance/container you have running is either old or broken. Can you try to look at that?

**Comment by micha5strings** [comment]
That's it!
![image](https://github.com/getsentry/sentry/assets/117353547/192192b3-b4fd-4af8-8393-6b05d15415ba)

Any idea what the cause is?

**Comment by lforst** [comment]
@micha5strings no idea... I recommend looking at the logs. Maybe it panicked? But 137 would more likely point to an OOM issue.

**Comment by micha5strings** [comment]
This is wierd.
I re-run install.sh and docker compose and it seems to work just fine. Sourcemaps are being utilized.
I cannot count how many times I did this last week without any success.
Maybe there was an error in the nightly build. (just saw the default images are nightly)
Guess I'll switch to stable. Thanks for your help. You really got my sanity back on track.
