### ISSUE TITLE
[UI Tweak for User Feedback] Add an icon only for error-related feedbacks and remove error level icons from all feedbacks

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#59795]
Today, our Feedback List page looks like this:

The error level (blue icons in the photo) makes it appear as if the individual feedback is unread, but it's just the error level.

It also distracts from our actual "unread" indicator (purple dot). 

As a user, it's difficult for me to immediately recognize _which_  feedbacks are from the crash report modal and which are not on the List page.

![Image](https://github.com/getsentry/sentry/assets/77064737/ef4f11b1-7f56-4c6c-8e2f-c5d798a03794)

## Proposed Solution

- [x] Drop error level icons from all feedbacks
- [x] Use a unique icon for feedbacks from crash report modal that shows up on the feedback list page.
- [x] Incorporate error level icons on crash-report feedbacks in some fashion

**Comment by jas-kas** [comment]
cc/ @Jesse-Box

**Comment by Jesse-Box** [comment]
Here's what I'm thinking @jas-kas and @michellewzhang 

<img width="1151" alt="Screenshot 2023-11-16 at 11 45 03" src="https://github.com/getsentry/sentry/assets/6508377/b312a35f-6ed6-4eeb-a693-cdc2a90fa723">

Its my opinion, the solution needs to be pretty explicit and the solution proposed affords us to show a tooltip on hover, where we can explain the situation and potentially upsell people on the new UF product. All it will require is a bit of CSS massaging to consolidate the other UI pieces such as linked Issue, Replay and Issues

**Comment by jas-kas** [comment]
@Jesse-Box  I like the "After" with the small crash report flag and name! 

What do the other icons in the bottom-left represent (Specifically the folder and paperclip)? If the folder is demonstrating there's a linked issue, doesn't the Crash Report name already signify this?

**Comment by Jesse-Box** [comment]
> @Jesse-Box Thanks Jesse! I like the "After" with the small crash report flag and name!
> 
> What do the other icons in the bottom-left represent (Specifically the folder and paperclip)? If the folder is demonstrating there's a linked issue, doesn't the Crash Report name already signify this?

So like an email client, the paperclip icon aims to communicate that things are attached to this UF event. You are right though, the issues folder icon shouldn't exist for the crash report case, but we'll definitely need it for our new UF events.

**Comment by michellewzhang** [comment]
@Jesse-Box some questions:

- in what scenario would we show the issues folder icon (what does it indicate)? 
- to clarify, the tooltip would pop up when the user hovers over the '[flag icon] Crash Report' bit? and it would say something like 'this feedback came in from our crash report widget and has an associated issue linked'? is there more wording we want to add?

**Comment by Jesse-Box** [comment]
@michellewzhang 
> in what scenario would we show the issues folder icon (what does it indicate)?
So Im making the assumption that the new UF event can have an error event associated, but maybe thats wrong? Let me know if so. 
> to clarify, the tooltip would pop up when the user hovers over the '[flag icon] Crash Report' bit? and it would say something like 'this feedback came in from our crash report widget and has an associated issue linked'? is there more wording we want to add?
so I would imagine the tooltip would be trigged by the container that wraps both the icon and string. As for the wording, I haven't figured this out yet, but we can also say we add this tooltip later, as its more of a added bonus.

**Comment by michellewzhang** [comment]
@Jesse-Box i think only crash report feedbacks (coming in from the old widget) have error events associated!

**Comment by Jesse-Box** [comment]
> @Jesse-Box i think only crash report feedbacks (coming in from the old widget) have error events associated!

Ok if thats the case, then Id like some more time evaluate my solution. First thing tomorrow ;)

**Comment by michellewzhang** [comment]
fwiw this is what it could look like! mocked it up quickly
<img width="387" alt="SCR-20231116-jkrj" src="https://github.com/getsentry/sentry/assets/56095982/76768131-a882-40fb-be3c-ae97ee3f92e5">

**Comment by Jesse-Box** [comment]
@michellewzhang 

See the latest version of the list item component [here](https://www.figma.com/file/ga57zyLonVCSJIH3kOWLVA/Specs%3A-User-Feedback-v1?type=design&node-id=3%3A11969&mode=design&t=gSUaxIQcK424XKnG-1)

For what I'm calling the "attachment tag", I'm using the same tag variant used for regressed issues. As for the crash report tag, I assume theres a red variant we can use ;).

<img width="792" alt="List Item" src="https://github.com/getsentry/sentry/assets/6508377/6fba0de9-14ef-4f2f-8246-9e3d0c655d85">
