### ISSUE TITLE
Add Crons Outcomes

### ISSUE THREAD

**Issue by cleptric** [getsentry/sentry#59841]
It's currently impossible for us and our users to see an outcome of a Cron's Check-In anywhere in `_admin` or the UI.

We should add outcomes to both of these places.

![image (1)](https://github.com/getsentry/sentry/assets/6617432/7b0c2736-00ee-4d35-a0bb-b84ca4ea5c2e)

![image](https://github.com/getsentry/sentry/assets/6617432/88f0165a-5c3a-4d77-aed4-d8821159df16)

**Comment by gaprl** [comment]
Thank you @cleptric, we'll take a look into this.

**Comment by evanpurkhiser** [comment]
I believe this is completed after https://github.com/getsentry/sentry/pull/61534
