### ISSUE TITLE
Add alert option to notify when an issue is assigned

### ISSUE THREAD

**Issue by MaicolBen** [getsentry/sentry#59860]
### Problem Statement

Currently, the only option to get notified through an alert when assignment is if the issue was auto-assigned (through CODEOWNERS) or if it happened several times in a X period. It would be nice when a human assigns an issue to someone/some team, the team gets notified through Slack for example. 

Not sure is related to https://github.com/getsentry/sentry/issues/45085 but you cannot comment/vote there. 

### Product Area

Alerts

**Comment by ceorourke** [comment]
Hi @MaicolBen - is this because workflow notifications aren't granular enough to your liking? You can already get a Slack notification for issue assignment through them - see the docs here: https://docs.sentry.io/product/alerts/notifications/#workflow-notifications

**Comment by MaicolBen** [comment]
Yeah, but I meant in the Alerts feature, workflow notifications are sent to each slack user, so something you cannot achieve is: "Send a slack notifications to a team channel when an issue is assigned to the team", only when is automatically by CODEOWNERS.

**Comment by scttcper** [comment]
You can set that up for a team. Go to the notifications tab on the team you'd like to set that up for.
![image](https://github.com/getsentry/sentry/assets/1400464/3aaea70f-f6ab-4d7b-8eb2-54ce8ec3fc05)

**Comment by MaicolBen** [comment]
Oh great! I didn't know that, I tried it and it didn't work for me, so I will contact support
