### ISSUE TITLE
Sentry not allowing me to set an email as primary from an old deleted account

### ISSUE THREAD

**Issue by bellini666** [getsentry/sentry#59863]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I'm trying to set another email as my primary one.

That email was associated with another account that I created by mistake. I logged in that account and asked to close it. It was scheduled for deletion last week and the deletion already happened.

I'm now trying to set my main account's primary email with an email that was associated there, but the association should have been removed by now, but I'm getting the message `That email address is already associated with another account.`

### How are you getting stuck?

Not being able to set my primary email with the email that I want.

### Where in the product are you?

Settings - Auth

**Comment by nhsiehgit** [comment]
This sounds like a customer issue that will require communicating via a support ticket.

**Comment by nhsiehgit** [comment]
@bellini666 

can you email our support team at support@sentry.io ?
they can work with you to help resolve this issue
