### ISSUE TITLE
Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.

### ISSUE THREAD

**Issue by DavidWeiss2** [getsentry/sentry#59884]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Install sentry.
2. Host a website on site A
3. Host a website on site B with different host name
4. Host site A in iFrame from site B without permission to session storage
5. Create a bug in site A
6. An error will be thrown from the line: `return"sessionStorage"in er&&!!er.sessionStorage` 

### Expected Result

Sentry will check access to session storage

### Actual Result

global error is created

### Product Area

Issues

### Link

https://searslive.com/main.js#:~:text=return%22sessionStorage%22in%20er%26%26!!er.sessionStorage

**Comment by hubertdeng123** [comment]
Oof bot race condition

**Comment by scttcper** [comment]
@DavidWeiss2 is this an SDK question or about how sessions are used in sentry. I see PR #59886 but I'm not sure how its related to this two iframe question.

**Comment by DavidWeiss2** [comment]
Its related to the sdk we are consuming on site A via the angular/ivy sentry library

**Comment by scttcper** [comment]
@DavidWeiss2 that code lives over here https://github.com/getsentry/sentry-javascript Should we move this issue over to them? This repo has to do with sentry.io the website, i've gone ahead and closed the pr.

**Comment by DavidWeiss2** [comment]
You are right. I will open that there. Thank you
