### ISSUE TITLE
[User Feedback Search] Add additional search conditions: User Description content and User Email

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#59928]
## Search Improvements

1. Being able to search by user email

As a Sentry user, I would like to see all feedbacks from a specific user so that I can get a better understanding of challenges they're facing holistically.

2. Being able to search description content

As a Sentry user, I would like to search the end-user description content (i.e, the message the user inputted) of a feedback, so I can easily go back to a feedback I previously viewed.

As a Sentry user, I would like to understand if there is a theme in my feedbacks by searching all of them by a key word.

Note: I would expect the above to work similar to event title/messages on the Issues Stream search. [[Link](https://docs.sentry.io/product/reference/search/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2F#syntax)]

**Comment by jas-kas** [comment]
cc/ @JoshFerge

**Comment by bruno-garcia** [comment]
Email is likely going to be used pretty quickly so if we can land this for open beta that'd be helpful but not a blocker

**Comment by bruno-garcia** [comment]
We agreed to move this to the GA milestone since it's not super straight forward to get this done and Josh doesn't have the bandwidth until our open beta date.

**Comment by michellewzhang** [comment]
@bruno-garcia  searching for `user.email` works; we just can't search for the field `contact_email` cc @c298lee

**Comment by JoshFerge** [comment]
idea:

on ingestion, if we have feedback.contact_email, but not user.email, simply fill in user.email with contact_email. and we can point customers to use user.email for search

we can also add feedback.message to a field which is indexed on events, i'm not sure what this would be -- event.message maybe!

**Comment by bruno-garcia** [comment]
That makes sense.

We have `event.user.email` and `event.user.username`, the latter is less intuitive to map directly. Could we translate the query somewhere to and from `name` to `user.username`?
Similarly `feedback.contact_email` to `user.email` ?

**Comment by bruno-garcia** [comment]
When resolving this we need to update the searchable fields (in particular how we define email search): https://github.com/getsentry/sentry-docs/pull/8599/files#diff-3abe4c90e0b49860c7072d4bd94be91580ea4dd2b7ce5f3277e18b2dd405f68eR121
