### ISSUE TITLE
[Design Support] High Fidelity User Feedback Customization Diagram for SDK Documentation

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#59941]
High-fidelity version of the User Feedback Customization Diagram created by Billy:

[[Associated Slack msg to download diagram](https://sentry.slack.com/archives/C05J714QPRR/p1699999044287279)]

![Image](https://github.com/getsentry/sentry/assets/77064737/ca0d4c66-7619-4d46-aaf6-8e8c19f62b1f)

**Comment by jas-kas** [comment]
cc/ @billyvg

**Comment by Jesse-Box** [comment]
@jas-kas @billyvg see draft here

![Image](https://github.com/getsentry/sentry/assets/6508377/0c139ad9-ad18-4bec-9a65-1ea510828cb1)

**Comment by bruno-garcia** [comment]
@Jesse-Box this is looking good, is it the final version?

**Comment by Jesse-Box** [comment]
> @Jesse-Box this is looking good, is it the final version?

If everyone is happy, I would consider this done!
