### ISSUE TITLE
This was an issue with our configuration. Missing "/" at the end of `/extensions/slack/action/` endpoint in bot setup in Slack

### ISSUE THREAD

**Issue by balaG4046** [getsentry/sentry#59967]
This was an issue with our configuration. Missing "/" at the end of `/extensions/slack/action/` endpoint in bot setup in Slack

_Originally posted by @jmsg4 in https://github.com/getsentry/sentry/issues/24676#issuecomment-808368847_
            

Even though i have configured correctly but still issue is persisting couldn't able to update the sentry issue from slack.

**Comment by scttcper** [comment]
Is there anything we need to update here? The docs seem to have it listed correctly. All of our endpoints are strict with trailing slash as far as i know.

**Comment by iamrajjoshi** [comment]
The [documentation](https://develop.sentry.dev/integrations/slack/) mentions trailing slash.
