### ISSUE TITLE
Setup Profiling documentation in the UI not updating DSN when changing projects

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#59965]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Profiling 
2. Select a project that does not have profiles
3. Click Set up Profiling

A side menu will open with the steps to setup profiling, for me it defaulted to my asgi project (1st in alphabetical order).

4. Use the project selector at the top to change to another project using the same platform. In my case it is python, so I choose fastapi project. 

### Expected Result

The setup steps update to the selected project (including the DSN).

### Actual Result

The DSN in the setup remains the same. This can lead to errors when setting up profile and events might be sent to the wrong project. It only updates if I choose a project on another platform, in this case the DSN is also updated to reflect the new project.

Screenshots:
![Screenshot 2023-11-15 at 08 43 00](https://github.com/getsentry/sentry/assets/64906376/28e9d49f-761c-4736-ba7d-54842404f996)
![Screenshot 2023-11-15 at 08 43 12](https://github.com/getsentry/sentry/assets/64906376/c7e6149c-243b-42d5-a279-a40382a3dc5a)

### Product Area

Profiling

**Comment by Zylphrex** [comment]
Thanks for the report! We'll get this fixed soon.
