### ISSUE TITLE
Absolute date range selector should be set to false always when daterange selector commits the changes and closed.

### ISSUE THREAD

**Issue by Shubhdeep12** [getsentry/sentry#59964]
https://github.com/getsentry/sentry/blob/0da3a01c7350f583af73b0e138a27f2d41d3cdbf/static/app/components/timeRangeSelector/index.tsx#L246

this condition should not depend on showRelative

**Comment by scttcper** [comment]
closing in favor of your other ticket #59814

**Comment by Shubhdeep12** [comment]
Hey @scttcper, i got this concern while resolving the other issue. 

Can you please provide some light here? Any idea why we are retaning the state to true after closing/ committing the changes?

And should this be set to false always?
