### ISSUE TITLE
Investigation rule failing on release details

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#59979]
Failed investigation rule popup is showing up on the release details page. Example here:
https://sentry.sentry.io/releases/control%40f3ca145b482040e38449bcc6190f89e218c3e7a1/?project=1

That's an oversight likely because the discover/performance table is reused at the bottom of that page.

We either need to fix the reason why this is erroring out on this page or disable it on this page.

![Image](https://github.com/getsentry/sentry/assets/9060071/97494861-230a-4d2d-8477-373b6978bcb8)

**Comment by RaduW** [comment]
Will add a flag to be passed to the component from the table and enable the component explicitly, so anybody that uses the discover or performance table without explicitly specifying the flag for investigation rules will not get the investigation rules component.
