### ISSUE TITLE
UX for group by limitations

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#59971]
### Problem: 
In Dashboards, grouping by very high cardinality tags (more than X values) isn't really useful for customers and it's also not sustainable for our infrastructure. This wasn't an issue when using stored event data, therefore a number of customers [[link](https://redash.getsentry.net/queries/5378/source)] have pre-existing dashboard widgets that use such high cardinality tags, which cannot work with metrics.

### Proposed solution:
There are two scenarios that need to be handled:

**1. We identify a high cardinality tag during new widget creation**
In this case we should prevent the customer from creating such a widget. Once a tag is chosen that we can already identify as "high cardinality", we show an alert informing the customer that it's not possible to choose this tag and disable saving the widget.

**2. The widget was created with a tag that became high cardinality later, and the widget on-demand extraction had to be disabled** 
In this case we should offer a "degraded" experience, where we're potentially dropping metrics for the particular widget and inform the customer. We should mark the widget with a warning icon and explain why this is happening, encouraging them to take action to either limit the tag values on the client or use a different tag.

**Comment by Shubhdeep12** [comment]
Hey @ale-cota can you please add some description

**Comment by Shubhdeep12** [comment]
Hi @ale-cota if it is possible/allowed i would love to work on this.

**Comment by Shubhdeep12** [comment]
Ok thanks for the reply @k-fish

**Comment by ale-cota** [comment]
Question from @Jesse-Box: could we just pre-check all tags and now show high cardinality ones as options in the group-by?
Otherwise:
- yellow alert banner underneath the group by input field
- and leverage error message on chart
<img width="818" alt="Screenshot 2023-12-13 at 10 33 12" src="https://github.com/getsentry/sentry/assets/26696515/7f75c55b-fb28-4023-a7cf-2e31129f6e59">
