### ISSUE TITLE
Profiling empty screen looks is not aligned properly. 

### ISSUE THREAD

**Issue by Shubhdeep12** [getsentry/sentry#59972]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

![image](https://github.com/getsentry/sentry/assets/43654389/47ba295f-c047-47e2-9b04-389b9ddcabde)

### Expected Result

Empty state illustration is misaligned.

### Actual Result

It should be aligned properly.

### Product Area

Profiling

**Comment by Shubhdeep12** [comment]
Please confirm if this needs a fix. I'll raise a PR

**Comment by Zylphrex** [comment]
@Shubhdeep12 I'm unable to reproduce this behaviour. Are you always seeing this? Is it a specific browser? Or perhaps a certain screen size?

**Comment by Shubhdeep12** [comment]
No its is happening on every screen for me @Zylphrex

**Comment by Zylphrex** [comment]
Thanks, I'll take another look to see if I can figure out what's going on. If you have any additional information, that would be appreciated.

**Comment by Shubhdeep12** [comment]
@Zylphrex it looks misaligned locally. 

Local - 
![image](https://github.com/getsentry/sentry/assets/43654389/72991d13-0804-47fc-a8fe-2c5c79b55bcc)




Deployed Production
![image](https://github.com/getsentry/sentry/assets/43654389/1920c9e7-8335-4668-88ca-2f39cd3964ef)

**Comment by Zylphrex** [comment]
To be clear, is it aligned correctly now except in your local sentry instance?

**Comment by Shubhdeep12** [comment]
yes @Zylphrex

**Comment by JonasBa** [comment]
@Shubhdeep12 can you confirm that this doesn't work on sentry.io? We can't tell from your original screenshot if that is broken in production or in your local environment

**Comment by Shubhdeep12** [comment]
Hey @JonasBa this happens in a local environment for me, after running **yarn dev-ui**
