### ISSUE TITLE
group_tombstone_id does not exist

### ISSUE THREAD

**Issue by 0fork** [getsentry/sentry#5998]
I'm using Docker (official images) to run Sentry and I just noticed that I've been getting ~400k events an hour from Sentry Internal. So I check the logs and the error message is this:

`ProgrammingError: ProgrammingError('column sentry_grouphash.group_tombstone_id does not exist\nLINE 1: ...grouphash"."hash", "sentry_grouphash"."group_id", "sentry_gr...\n`.

We haven't had any problems with Sentry until this started yesterday after Docker logs caused server's harddrive to fill up 100% yesterday (resolved now). I suspect this might have caused Sentry to store only partial data and now it can't find the rest.

Any ideas how to fix this without reinstalling everything?

**Comment by mattrobenolt** [comment]
Sounds like somewhere, you forgot to run `sentry upgrade` after updating. You need to apply scheme migrations.

**Comment by cpoetter** [comment]
I'm having the same problem right now...
