### ISSUE TITLE
Show UI frames, CPU and Memory for RN/iOS Mixed Profiles

### ISSUE THREAD

**Issue by krystofwoldrich** [getsentry/sentry#59989]
Since https://github.com/getsentry/sentry-react-native/pull/3349 RN SDK sends profiles with UI frames, CPU and Memory.

https://sentry-sdks.sentry.io/profiling/profile/sentry-react-native/4f0be51bd1534274b5b0fc1874520fd8/flamegraph/

![Screenshot 2023-11-15 at 16 10 24](https://github.com/getsentry/sentry/assets/31292499/a38c4e5a-6658-4fb3-bcb1-5e32478b0fea)

The current UI doesn't display the measurements. 

Note not all RN profiles include the measurements.

**Comment by DeeVine** [comment]
Hi, is there an estimate on when CPU and Memory usage will be available for RN?

**Comment by JonasBa** [comment]
@krystofwoldrich I cant access that flamegraph you shared. Mind sending me one where measurements were sent? I'm going to look enabling this, iirc it's just a matter of adding the platform to a whitelist that determines if the charts should be rendered.

**Comment by JonasBa** [comment]
> @krystofwoldrich I cant access that flamegraph you shared. Mind sending me one where measurements were sent? I'm going to look enabling this, iirc it's just a matter of adding the platform to a whitelist that determines if the charts should be rendered.

Nevermind, I found it and I'm working on enabling this.
