### ISSUE TITLE
[User Feedback] Two-way sync between crash-report feedback Assign/Resolve statuses and the associated Issue

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#59994]
[Context in internal Slack thread](https://sentry.slack.com/archives/C05J714QPRR/p1699647913513919)

**Comment by jas-kas** [comment]
cc/ @JoshFerge

**Comment by ryan953** [comment]
I don't think that we should link together Feedback and Issues (either Sentry Crash Report issues, or linked Github/Jira/etc issues)

I think Issues of all types are resolved, generally speaking, by deploying code.
And Feedbacks are resolved by communicating to the author. 

These two activities happen at different times, and by auto-closing the feedback we make it so much harder to have any workflow that includes comms back to the feedback author. 

I recommend we close this ticket.

**Comment by jas-kas** [comment]
See above.
