### ISSUE TITLE
Ticket Auto Creation

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#600]
Some Issue plugins already provide "automatically create tickets for new events". The standard IssuePlugin currently doesnt do this (and wont by default), but we want to add this option.

For this to be added, we need to handle the case of "we authenticate each user, so there is no system user".

Proposal is something like:

[ ] Automatically create ticket for new events on behalf of <no user set>  (assign my user)
[x] Automatically create ticket for new events on behalf of <no user set> (assign my user)
[x] Automatically create ticket for new events on behalf of David Cramer (you are assigned)
[x] Automatically create ticket for new events on behalf of David Cramer (assign my user)

**Comment by ashwin31** [comment]
+1

**Comment by joshma** [comment]
Any plans for the new assign-user functionality (in the beta) to be generalized / integrated with issue tracking like Phabricator? Would be really sweet to see 1) if a task has been created and 2) who it's assigned to from the UI instead of having to click through. Totally understand if that's far out in the future; just curious.

**Comment by dcramer** [comment]
@joshma Our goal is to add an API on top of it that will allow issue plugins to tap into it. I dont know yet what it'll look like though.

**Comment by terion-name** [comment]
nothing here?

**Comment by ankuriitk** [comment]
+1 - Would love to get auto creation feature!

**Comment by maverick93** [comment]
what's the status on this?

**Comment by ehmo** [comment]
+1 - this would be a great help

**Comment by stepanbujnak** [comment]
+1

**Comment by hynek-jemelik** [comment]
:+1:

**Comment by sYnfo** [comment]
👍

**Comment by nfm** [comment]
:+1:

**Comment by mgiachetti** [comment]
👍

**Comment by rpereira** [comment]
👍

**Comment by pierresauvignon** [comment]
👍

**Comment by link82** [comment]
👍

**Comment by jeanCarloMachado** [comment]
:+1:

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
