### ISSUE TITLE
Replay Search: Typeahead doesn't filter down matching values as you type

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#60025]
Searching on Replays (e.g: https://sentry.sentry.io/replays/) 

![image](https://github.com/getsentry/sentry/assets/1633368/c4b8a2f9-303c-4193-8762-ba9e49beeca2)

The spinner comes up when you type, but values are not filtered. When compared to for example issues (https://sentry.sentry.io/issues/):

![image](https://github.com/getsentry/sentry/assets/1633368/f4cbf2fa-c48f-436f-b3ab-359227939eb0)

**Comment by Shubhdeep12** [comment]
Yeah, it seems like while fetching organization tag key values in the case of includeReplays.

**conditions** array consisting query is not passed while fetching values from DB at line 1326 in src/sentry/tagstore/snuba/backend.py

And query_replays_dataset_tagkey_values should also support conditions while executing query.


Am I going in the right direction?
