### ISSUE TITLE
Allow option to store Native crash reports based on data retention time

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#60027]
### Problem Statement

Under Project Settings > Security & Privacy > Store Native Crash Reports, allow client to specify a timeframe for how long the crash report is retained.

![Screenshot 2023-11-15 at 10 34 11 AM](https://github.com/getsentry/sentry/assets/103009467/97d9d610-4b45-453a-95c4-b3b2b9ab72ac)

### Product Area

Settings - Security & Privacy

**Comment by leedongwei** [comment]
@kpujjigit Hey! I'm not familiar with this feature. What's the expected timeframe? I'm assuming this follows the organization's data retention policies, so 30d/60d/90d depending on their contract with us.

**Comment by jernejstrasner** [comment]
I don't think this makes much sense to do since the retention is based on what @leedongwei said above. Is there a specific use case or need for this?
If so let's discuss but closing this for now.
