### ISSUE TITLE
Vercel integration configuration ugly

### ISSUE THREAD

**Issue by scttcper** [getsentry/sentry#60056]
### Problem

We want the vercel experience to be well designed and easy to use. There are some areas that could be improved.

![Image](https://github.com/getsentry/sentry/assets/1400464/2ebdd202-da3b-40bb-a230-99b243f2b962)

Hover state missing on the dropdown, padding is wrong/broken.

It doesn’t feel clear which column is which (vercel/sentry). The light colored placeholder doesn’t make it clear what you’re doing on this page.

Connect a repository… why?

![Image](https://github.com/getsentry/sentry/assets/1400464/ec5fcad1-6be1-49e7-b5f9-2247396e7b51)

Feels like a link to vercel might be nice up at the top

![Image](https://github.com/getsentry/sentry/assets/1400464/ed81d79b-70ae-4172-9a50-2847144e9b8e)

### ACs
- Fix padding and hover states on the integration config page #60021 
- Make the component a FC w/ useQuery instead of AsyncComponent (tech debt)
- Add a link to your vercel dashboard like we do for other integrations

**Comment by roggenkemper** [comment]
completed in https://github.com/getsentry/sentry/pull/60051
