### ISSUE TITLE
Showcase certain tags runtime (like client vs server)

### ISSUE THREAD

**Issue by scttcper** [getsentry/sentry#60066]
### Problem

Certain clues are more important to debugging nextjs. Projects use a single dsn between frontend and backend and it isn’t currently easy to filter or differentiate between frontend/backend errors.

![Image](https://github.com/getsentry/sentry/assets/1400464/c9bbf5ec-aa1d-41aa-ae1d-b9b91a60e4e7)

### Current Experience

The way tags are shown feels like it could be either a browser error or a server error.

In the below example, a server nextjs error on nodejs, the user is using windows/chrome to make the request and both sets of tags are shown together.

![Image](https://github.com/getsentry/sentry/assets/1400464/1799201c-7e0e-439c-bb63-2dce2120f6bd)

### Ideal Experience

We could show the high priority tags in the stacktrace hovercard. this could apply for all issues

Some sort of tag shown on the issues stream directly. Which SDK file is driving this error. client/server/edge?

![Image](https://github.com/getsentry/sentry/assets/1400464/f4cb9117-dd56-4fd1-aa27-11e650b3cf9c)

Can probably do this for all SSR frameworks like Remix. Can limit changes to just issue details.

**Comment by roggenkemper** [comment]
Current change is to hide the browser in the context section for Next.js, can add this to over SSR frameworks if we think it makes sense. Only made a change to issue details. https://github.com/getsentry/sentry/pull/62278
