### ISSUE TITLE
Implement the new design for samples table

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#60076]
### Problem
We currently have no UI pattern for conveniently displaying data  related to a specific widget

### Acceptance Criteria
- The tray component has its own feature flag
- The tray component sits above the flow of content (widgets)
- The ray can be collapsed
- The tray's height can be determined by dragging it
- The widget component needs a selection state

### Rewatch
https://sentry.rewatch.com/video/5zbje22juyl8l4p4-ddm-sample-insights-specs-feedback-round-2

### Design
https://www.figma.com/file/j5bl6JiFa4t1tGAvV9U0QG/Specs%3A-Insights-Tray-v1?type=design&node-id=70%3A6417&mode=design&t=c9Y2V9fUdFDbEQwO-1

**Comment by Shubhdeep12** [comment]
Hey @matejminar is this open for community? If yes, is anyone working on this?

If not, i would love to work on this. 
Thanks

**Comment by matejminar** [comment]
Hi @Shubhdeep12, thank you for your offer! We are still iterating and finalizing decisions so this is not yet ready to be worked on 🙏
