### ISSUE TITLE
Linear Ticket creation is janky due to dependent fields being auto populated

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#60097]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a Linear ticket from an issue
2. See that the Team is auto populated
3. But the dependent fields of Assignee, Label cannot be edited
4. Need to update the Team selection to make the dependent fields editable

### Expected Result

The dependent fields should be editable from the start

### Actual Result

<img width="765" alt="image" src="https://github.com/getsentry/sentry/assets/109983869/92a7f81b-4964-4954-b7b6-7452e83e9510">

### Product Area

Settings - Integrations

**Comment by skbogner** [comment]
@Dhrumil-Sentry notice that we only auto populate the team field if there's a single team. So bear that in mind for repro.

**Comment by natikgadzhi** [comment]
I'm happy to tinker with this if you need a pair of hands — I have time tomorrow. But, looks like Linear is not on the list of integrations available in local dev environment, and that does not seem to be the feature flag thing — I don't see the code for it at all. Is it in sentry closed-source for now?

**Comment by skbogner** [comment]
> I'm happy to tinker with this if you need a pair of hands — I have time tomorrow. But, looks like Linear is not on the list of integrations available in local dev environment, and that does not seem to be the feature flag thing — I don't see the code for it at all. Is it in sentry closed-source for now?

The Linear integration is owned by us (Linear), so probably not there no, but this should be easily reproducible without it. You just need a field which gets a default value and one that depends on it. The dependent field is not editable straight away.

**Comment by skbogner** [comment]
@Dhrumil-Sentry can we move this forward?

**Comment by Dhrumil-Sentry** [comment]
@skbogner I've asked the eng team to look into this issue, We'll comment here as we have any updates

**Comment by scefali** [comment]
@skbogner @Dhrumil-Sentry  Is this bug still happening? What determines if the team gets autopopulated? I am not able to replicate the auto-population of the team for the Linear integration. I also set up my own integration locally that populates a default value through the endpoint and the fields are unlocked correctly:




![Image](https://github.com/user-attachments/assets/91ac8493-7523-47c7-bb88-f1bbcc310bf2)

**Comment by skbogner** [comment]
Hi, it's still the case although it is behaving slightly differently. 

We only default the team when there's a single team, but if I just force default some team I repro the bug.

I'll send a video over email.
