### ISSUE TITLE
[User Feedback] Allow deletion of feedbacks

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#60113]
For compliance reasons, we need to allow a user to delete a feedback. In the event that the author of it requests it.

**Comment by JoshFerge** [comment]
where did this requirement come from? we don't allow people to delete the existing feedbacks

**Comment by michellewzhang** [comment]
Just a note: we discussed being able to delete feedbacks at the beginning of this project, but it's technically not feasible right now. PR for context: https://github.com/getsentry/sentry/pull/58422 (see dan's comment)

**Comment by bruno-garcia** [comment]
> where did this requirement come from? we don't allow people to delete the existing feedbacks

https://docs.google.com/document/d/1UzrIINc4v4V4jnuflNhyrtRXVwKkhvAb0x4VXsCSmjg/edit

**Comment by stoft** [comment]
GDPR includes the right to be forgotten, this includes deleting user feedback. A workaround could be anonymization, but anywhere you happen to have free text input, such as a feedback form, there's always a risk that users input GDPR sensitive data in free text. We started using the feature just a few days ago without being aware of this issue, and this has now happened to us.

**Comment by tusmenko** [comment]
Up on this. The default deletion time after 30\60 days covers most of the use cases, but
to be fully GDPR-compliant, we'll need the option to delete user request\data manually or via API ASAP.

**Comment by jord1e** [comment]
The whole feature is useless without this feature, pretty bizarre not to even mention it on the documentation page

**Comment by bruno-garcia** [comment]
The ability to delete feedbacks is being worked on. We'll update this issue once it's completed

**Comment by michellewzhang** [comment]
cc @c298lee in case you haven't seen this ticket!

**Comment by c298lee** [comment]
UI implemented in https://github.com/getsentry/sentry/pull/78677. Backend works for single deletion cases, batch deletion is wip
