### ISSUE TITLE
Crons: Cover more incident creation scenarions

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#60123]
Thread for context: https://github.com/getsentry/sentry/pull/59445/files#r1394889657

There are a number of cases for monitor incident creation we don't currently handle correctly. This ticket documents those cases. There are likely more but for now this is what we've considered:

Key for cases

```
X = failed
I = in-progress
O = OK
```

### Unhandled incident creation cases

1.  ```
	X X I X X
	```
	
	could very well turn into this
	
	```
	X X O X X
	```

    In this scenario we would want to NOT create an incident since even though there were 4 failures with an in-progress in the middle (That we're ignoring right now), this still ended up not being an incident since it resolved with OK.

2.  ```
	failure_threshold=4
	recovery_threshold=4
	
	X X I X X O O
	```

    In this scenario imagine the 3rd check-in becomes a failure, when this happens we would have met the recovery threshold. However, when determining incidents we only look at the 4 most recent check-ins, since that's the failure threshold, because of that the 2 OK check-ins would cause us NOT to see this as an incident.

**Comment by rjo100** [comment]
OK I think I have a solution here. When we mark a check-in as failed we query for the check-ins forwards and backward including in-progress check-ins and subject to the threshold limit. Then, we iterate through the list and check for an unbroken chain of failures that hit the threshold. If we hit the threshold, then create and incident and send occurrences.

Optionally, we can then go through any later check-ins and send occurrences//resolve the incident as necessary. It might make more sense to do this as a later step.

**Comment by rjo100** [comment]
Yeah let's do step 1 now and then step 2 later when we can more easily + confidently extract helper functions and pull out some of the internal `mark_failed` + `mark_ok` logic. Right now for a timeout we'll basically still "skip" the intermediate check-ins and only resolve + send occurrences for new instances of `mark_*`

**Comment by wedamija** [comment]
@evanpurkhiser I assume this is done, closing. Re-open if there's still work to do
