### ISSUE TITLE
Improvements to /filters/discarded-groups/ list view

### ISSUE THREAD

**Issue by pcsmchristine** [getsentry/sentry#60158]
### Problem Statement

We've used this 3 times recently, but had these requests to improve this feature:
Improve the information included in the list view title and description. The info displayed changes to more generic information that is different from the original so it's impossible to know/remember what that issue was without removing it from this discarded view. 

### Solution Brainstorm

Desire is to retain that original information (title, etc.)
 Include "Date added" information. There's no info about when it was discarded, so it also loses information. Would like this included in the list view.
Is it possible to retain 1 example issue so that we can click into the discarded issue and remember what it was about?

[nice to have] Ability to include a note when discarding an issue. Include that note in the list view for history when we discard the issue.

### Product Area

Issues

**Comment by roggenkemper** [comment]
thanks for the feedback. not sure retaining an event will be possible given how we delete events after a certain amount of time , but showing more information in addition to the generic information we show now is a good idea. will add it to our backlog.

**Comment by armenzg** [comment]
Thanks for filing and the suggested solution!

Unfortunately, this area of the product is not and has not been one of our priorities for a while. For now, I'm going to close this issue.

If a lot of interest comes up we can re-evaluate it at that point.
