### ISSUE TITLE
Fix `count_if` check in on demand

### ISSUE THREAD

**Issue by iambriccardo** [getsentry/sentry#60163]
The current implementation of `count_if` it's not checking correctly for on demand, since for example:
* `count_if(transaction.duration,equals,0)` has a field which we support in standard but we do not support it in the filter, since the conversion of that operation is equivalent to `count(transaction.duration)` and `transaction.duration:0`.

We have to check many variants of this and one test which fails is:
```python
(
      "count_if(transaction.duration,equals,0)",
      "release:a",
      False,
)
```

**Comment by armenzg** [comment]
Hi 👋 
What's the status of this?

**Comment by armenzg** [comment]
Is this affecting extraction?
