### ISSUE TITLE
Clearer labeling in the issue view for "our code" vs "SDK/3rd party" code

### ISSUE THREAD

**Issue by pcsmchristine** [getsentry/sentry#60160]
### Problem Statement

When browsing issues, it's sometimes hard to quickly identify if the problematic code is likely from our source code OR from code executed in a 3rd party SDK we're using. 

### Solution Brainstorm

Some ideas for improvement:
Clearer labeling in the issue screen like "likely from your source code" or "likely from a 3rd party SDK you're using"
I realize we can also use "stack.filepath:xyz to filter out issues and identify those that are likely from our source code. 
It might be nice to have tabs in the Issues page for these.
Speaking of which, it'd be nice to be able to add a few custom tabs kind of like saved queries in the Issues tab view.

### Product Area

Issues

**Comment by MichaelSun48** [comment]
Hey @pcsmchristine! Great question - we actually do try to do this automatically by marking certain stacktrace frames as in-app vs non in-app:

![Image](https://github.com/user-attachments/assets/db24f0e8-96aa-4de8-a721-7487700d5f37)

You can also manually adjust which frames are labeled as in-app via [stack-trace rules](https://docs.sentry.io/concepts/data-management/event-grouping/stack-trace-rules/), which I believe addresses your issue. Feel free to reopen this and let us know if that's not the case!
