### ISSUE TITLE
Linked errors in Sentry js browser sdk are given incorrect title in Sentry

### ISSUE THREAD

**Issue by johndoherty** [getsentry/sentry#60194]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Create a [linked error](https://docs.sentry.io/platforms/javascript/configuration/integrations/linkederrors/) in sentry in the browser:
```js
try {
  // ...
} catch (e) {
    const fetchError = new Error(`Failed to fetch`);
    fetchError.cause = e;
    Sentry.captureException(fetchError);
}
```

Previously the title of the error in sentry would be: `Failed to fetch`, but now the title is whatever is in `e.message`.

### Expected Result

Title of error in Sentry UI is the error thrown, not the message of the error in the `cause` field. In the example above it should be "Failed to fetch", instead of `e.message`.

### Actual Result

Unfortunately I can't share what we see in our sentry UI publicly, but the title of the error that we see is `e.message`

### Product Area

Issues

**Comment by lobsterkatie** [comment]
Hi, @johndoherty - thanks for reporting! This is actually the same issue as https://github.com/getsentry/sentry/issues/59679, so I'm going to close this in favor of that, since a bunch of conversation has already happened there. Feel free to comment if you have stuff to add.
