### ISSUE TITLE
To increase width of "FIlter Release" filter in mobile performance page

### ISSUE THREAD

**Issue by Shubhdeep12** [getsentry/sentry#60237]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

https://vimeo.com/886148363/ec826f856b?share=copy

### Expected Result

Loader should be visible

### Actual Result

Loader is not visible and width can be increase further.

### Product Area

Performance

**Comment by Shubhdeep12** [comment]
Its a very minor issue. Let me know if this should be fixed, I'll push a commit.
Thanks

**Comment by shruthilayaj** [comment]
Thanks for the report @Shubhdeep12. You're welcome to put up a PR for the fix and link it to this issue! Feel free to tag @getsentry/team-starfish for review.

**Comment by Shubhdeep12** [comment]
Thanks @shruthilayaj just pushed a fix for this. 
Seems like I cannot tag anyone for review.

**Comment by shruthilayaj** [comment]
Thanks for contributing @Shubhdeep12!
