### ISSUE TITLE
Change copy/illustration of custom metrics category

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#60249]
### Problem/Opportunity
Users should be able to create alerts based on custom metrics (DDM). The current alert creation UI already has something called "custom metrics" that allows customers to choose event type (errors - type error or default - or transactions) and based on that offers a few different options to create more customised performance/error alerts.

![image](https://github.com/getsentry/sentry/assets/9060071/f48054d6-07bb-4932-8e49-64281418e9ba)

### Proposed solution
- repurpose the existing Custom Metrics radio button for DDM metrics - this means we need to update the copy and illustration (maybe reuse something from [here](https://docs.google.com/presentation/d/1QLT576LRYfQVuAbar80HYfaed_TWYhqmz0brkpMThYk/edit#slide=id.g29813e81eee_0_2))
- the existing custom performance metrics should move under the Performance section and just be called "custom" > no more selector for event type needed
- a separate custom error metrics in the Errors section doesn't make sense, since you can already create the same customisation today by choosing "number of errors" / "users experiencing errors"

**Comment by ale-cota** [comment]
Copy proposal:
Alert on custom metrics that you have configured and are not related to errors, transactions or sessions.

// illustration

Examples:
When your number of sign-ups dropped by 10% compared to the previous week.
When the 75th percentile of your login flow is taking longer than 500 milliseconds.

**Comment by ale-cota** [comment]
@Jesse-Box for the illustration maybe we could use:
- an illustration that defines the login metric
- an illustration of the graph that shows the metric plotted

Something like these:
![Image](https://github.com/getsentry/sentry/assets/26696515/d237ccd7-fedd-4852-8218-e440a82c9209)
![Image](https://github.com/getsentry/sentry/assets/26696515/57ffa45e-66b3-488a-8f49-2c623aa5f980)

**Comment by Jesse-Box** [comment]
@matejminar @ale-cota @ArthurKnaus see below
![Image](https://github.com/getsentry/sentry/assets/6508377/ad545f86-c0c7-4356-8b65-4f4af5978b45)

**Comment by Jesse-Box** [comment]
Going to mark this as done
