### ISSUE TITLE
Add empty welcome screen (send your first custom metric)

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#60250]
I like what Replays have:
![image](https://github.com/getsentry/sentry/assets/9060071/f6cd00da-9012-4a1c-9e12-31eadccd4360)
or Crons:
![Image](https://github.com/getsentry/sentry/assets/9060071/76715a2b-cff5-431f-b139-12fb0df67c1b)

We should also aim to inform users if they land on a frontend project without metrics and its backend project has metrics.

**Comment by ArthurKnaus** [comment]
@Jesse-Box could you add the illustration here? 🙏

**Comment by Jesse-Box** [comment]
![illustration-empty-state-ddm](https://github.com/getsentry/sentry/assets/6508377/e2e5b38b-6714-4ea2-9294-b4066d1a5cc1)

In addition, heres the flow, illustrating the different states we need to account for
https://www.figma.com/file/ZCGI7KKuITeybjqzhaqU1A/Exploration%3A-Onboarding-v1?type=whiteboard&node-id=0%3A1&t=aEXm8ZJtVsjNV9nb-1
