### ISSUE TITLE
Unable to setup distributed tracing

### ISSUE THREAD

**Issue by niteshtarani** [getsentry/sentry#60254]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Trying to enable distributed tracing with automated instrumentation in Spring boot app

### How are you getting stuck?

Getting these errors in logs:

INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'sentryTransactionAdvice' of type [io.sentry.spring.tracing.SentryTransactionAdvice] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'io.sentry.spring.tracing.SentryTransactionPointcutConfiguration' of type [io.sentry.spring.tracing.SentryTransactionPointcutConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'sentrySpanAdvice' of type [io.sentry.spring.tracing.SentrySpanAdvice] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'io.sentry.spring.tracing.SentrySpanPointcutConfiguration' of type [io.sentry.spring.tracing.SentrySpanPointcutConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'io.sentry.spring.tracing.SentryAdviceConfiguration' of type [io.sentry.spring.tracing.SentryAdviceConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'sentryCaptureExceptionParameterAdvice' of type [io.sentry.spring.exception.SentryCaptureExceptionParameterAdvice] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'io.sentry.spring.exception.SentryCaptureExceptionParameterPointcutConfiguration' of type [io.sentry.spring.exception.SentryCaptureExceptionParameterPointcutConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'io.sentry.spring.exception.SentryExceptionParameterAdviceConfiguration' of type [io.sentry.spring.exception.SentryExceptionParameterAdviceConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'sentryCheckInAdvice' of type [io.sentry.spring.checkin.SentryCheckInAdvice] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'sentryOptionsConfiguration' of type [io.sentry.spring.boot.SentryAutoConfiguration$HubConfiguration$$Lambda$530/0x00007fbdb85a3410] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'sentry-io.sentry.spring.boot.SentryProperties' of type [io.sentry.spring.boot.SentryProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'io.sentry.spring.boot.SentryAutoConfiguration$HubConfiguration$ContextTagsEventProcessorConfiguration' of type [io.sentry.spring.boot.SentryAutoConfiguration$HubConfiguration$ContextTagsEventProcessorConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'io.sentry.spring.boot.SentryAutoConfiguration$HubConfiguration' of type [io.sentry.spring.boot.SentryAutoConfiguration$HubConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'io.sentry.spring.checkin.SentryCheckInPointcutConfiguration' of type [io.sentry.spring.checkin.SentryCheckInPointcutConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'io.sentry.spring.checkin.SentryCheckInAdviceConfiguration' of type [io.sentry.spring.checkin.SentryCheckInAdviceConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

### Where in the product are you?

Performance

### Version

22.11.0

**Comment by niteshtarani** [comment]
Using this dependency:
<dependency>
    <groupId>io.sentry</groupId>
    <artifactId>sentry-spring-boot-starter</artifactId>
    <version>6.33.1</version>
</dependency>

**Comment by k-fish** [comment]
Hey there 👋, it sounds like you might be having trouble with the java sdk, you'll probably want to make an issue over on https://github.com/getsentry/sentry-java

**Comment by niteshtarani** [comment]
It was dsn issue, closing this.
