### ISSUE TITLE
Add metrics summaries to spans

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#60252]

**Comment by mitsuhiko** [comment]
This is now implemented on a branch in the Python SDK: https://github.com/getsentry/sentry-python/pull/2522

The plan is to deploy it to S4S gated behind a variable sample rate to measure impact. https://github.com/getsentry/sentry/pull/60506

**Comment by jan-auer** [comment]
Closing this, as we're tracking the deploy separately.
