### ISSUE TITLE
sentry_logo_full.png not showing in email

### ISSUE THREAD

**Issue by kobymeir** [getsentry/sentry#6028]
My sentry installation is installed on-premise behind a VPN, so it's url isn't publicly available.
In the email sentry is sending it's referring to an image:
`http://<my server url>/_static/1504316425/sentry/images/email/sentry_logo_full.png`
It's quite obvious the image won't be available publicly and return a 404 when the email is being rendered.

My question is if there is anyway to customize the email template to remove the image/ or somehow embedded the image within the email?

**Comment by markstory** [comment]
You have the source code and can make changes to the templates as necessary to suit your deployment environment.
