### ISSUE TITLE
Crons: Improve monitor consumer parallelism

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#60292]
Currently, monitor ingestion happens with a single process (single thread) and check-ins are processed completely sequentially. This process is relatively IO-bound, since we're spending most of our time talking to postgres (and a bit talking to redis). [See the transaction summary in sentry here](https://sentry.sentry.io/performance/summary/aggregateWaterfall/?project=1&query=&statsPeriod=24h&transaction=monitors.monitor_consumer).

It's likely we can optimize parts of this by fanning out the work into threads. However, we will need to be careful that we continue to process our check-ins in the correct order **across monitor environments**. Since out-of-order processing can cause anomalies in monitors.

> [!NOTE]
> If an `ok` check-in happens before the opening `in_porgress` check-in, the `in_progress` will end up timing out. This only happens with `latest` check-ins, most SDK generated check-ins will generate a consistent UUID for the run and out-of-order check-ins can be correctly detected.

## Current world

As a reminder, the current execution lifecycle of the monitor check-in consumer is as follows:

1. trigger the clock-pulse check. This is responsible for moving our global consumer clock forward once all partitions have been processed up to a new minute. This is currently done for **every check-in**.

2. If the message was a synthetic clock-pulse, generated by the backup celery task that ensures the clock is driven even when no check-ins are present in the kafaka topic (low-volume environments), then there is nothing left to do. The cock will have been pulsed by step 1 already. 

3. We unmarshal the JSON payload of the check-in. This includes details such as the monitor slug, monitor environment, and check-in GUID.

4. Check-in processing - This is where a majority of the postgres work happens, this is the slowest part of the process.

5. Offset commit

## Ideas for multiprocessing

A key factor to consider is again **check-ins per monitor environment MUST happen in order**.

### Batching

Instead of processing each check-in one at a time, we can do the following

1. Batch check-ins using the [`BatchStep` strategy](https://getsentry.github.io/arroyo/strategies/batching.html). The goal here is to collect `n` check-ins to be procssed in paralell.

2. After batching, the `nextStep` is a processing function which takes our batch and decodes all internal messages and partitions check-ins by `{project_id}:{monitor_slug}:{env}` into `n` partitions. These partition'd check-in groups will be processed in parallel using a thread pool worker.

3. Once all thread execution is completed the `nextStep` will now be to trigger the clock-pulse check using the oldest message timestamp from all the processed messages.

4. Finally we can now commit our offset.

**Comment by mwarkentin** [comment]
@evanpurkhiser should this be closed now?

**Comment by evanpurkhiser** [comment]
Yes!
