### ISSUE TITLE
Show cardinality limits in UI

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#60309]
- show different notices per use case
- visible not only in DDM but everywhere we render metrics

Right now we don't have outcomes per metric, so a generic banner that there was some cardinality limiting happening during X timeframe has to be enough (probably in DDM,Dashboards, and Stats).

**Comment by jjbayer** [comment]
This would be particularly useful in stats views, so we can tell the user why their numbers are off. See https://github.com/getsentry/team-ingest/issues/134.

**Comment by Jesse-Box** [comment]
@matejminar @ale-cota 

I spoke with @jan-auer to learn about what cardinality limits are and the status of the project.

@jan-auer feel free to correct me, but there's definitely at least two stages to this experience.

The end goal, would be to know exactly which metrics are the culprit for a limit to trigger, informing the user accordingly. However, the tech isn't there yet, meaning if the priority high, we'll need a stop-gap solution which is more rudimentary. Essentially highlighting on the chart with some additional communicate explaining the state of things.

I'm happy to support the team to find a simple solution for now, but I think we should flesh this ticket some more to be more indicative of where the tech is currently at.

**Comment by iambriccardo** [comment]
All the work related to outcomes will be updated once we figured out how those outcomes are actually computed.
