### ISSUE TITLE
Add filters based on Issue Status for metrics alerts

### ISSUE THREAD

**Issue by Juanjacinto123** [getsentry/sentry#60327]
Hi, how can I receive alerts based on the issue status, such as Ongoing, New, Archived, etc.

I tried adding the "is:New" statement as a filter, but the system tells me that the "is:" filter is incompatible.

Alert configuration:

![rules1](https://github.com/getsentry/sentry/assets/84612635/9099f9a0-9f72-466a-a7b2-df0a40a5c6a0)

In this case, I am only interested in the issue with the Status "New"

![rules2](https://github.com/getsentry/sentry/assets/84612635/8cd539a6-37bd-47ca-a12a-07759c8d2658)

How can I configure it? Any idea? @scttcper @Dhrumil-Sentry @shruthilayaj 

I appreciate any help you can provide.

**Comment by scttcper** [comment]
This is currently in progress now! We have a ticket open here #53110

**Comment by scttcper** [comment]
You won't be able to filter on "new" but you will be able to filter on events from unresolved issues soon.
