### ISSUE TITLE
Event ingest blocked with invalid (?) stack trace rules

### ISSUE THREAD

**Issue by aswanfigma** [getsentry/sentry#60335]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I have a project that has had the following rule for ages:
```
stack.function:* max-frames=6
```

I recently tried to add a second rule to consider more frames for some specific errors:
```
error.value:"*something*" max-frames=12
```

I was able to add this second rule through the UI, but as soon as I did, accept incoming events immediately dropped to zero with no indication of any errors.  Disabling the new rule immediately fixed the problem and event ingest resumed at typical rates.

### Expected Result

Most important is that this new rule should not have completely prevented events from being ingested!

### Actual Result

(see above)

### Product Area

Other

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2008) by [Unito](https://www.unito.io)

**Comment by aswanfigma** [comment]
I should mention, I can shared more details with Sentry employees about our setup if that's helpful, but everything here appears to be world readable so I'm not inclined to add any detailed information here...

**Comment by roggenkemper** [comment]
hi! if you want to email me more information about the setup you have so it isn't public on Github, please send the information to richard.roggenkemper@sentry.io !

**Comment by yuval-sentry** [comment]
@roggenkemper I added you to our internal ticket

**Comment by jan-auer** [comment]
cc @armenzg , this is likely related to https://sentry.sentry.io/issues/4633368892/
