### ISSUE TITLE
"Invalid characters" error on alert page with invalid filter

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#60354]
https://sentry.sentry.io/alerts/rules/details/193044/

![image](https://github.com/getsentry/sentry/assets/9060071/e1e33155-3af8-4419-978d-d96bb275e500)

There might be a race condition because it does not happen all the time.

**Comment by ArthurKnaus** [comment]
@matejminar I think this is fixed by now. At least I fail to reproduce it 🤔

**Comment by matejminar** [comment]
@ArthurKnaus I just reproduced by going to the alerts page (by default sentry project is selected and average of breakdowns.span_ops.ops.db) and just added the `event_type:[default, transaction]` filter.

I guess the event_type tag does not exist on that metric, and that's why it fails. We should handle this more gracefully than throwing `Invalid characters...` error that's visible in the original screenshot.

<img width="1010" alt="image" src="https://github.com/getsentry/sentry/assets/9060071/6ba2ec21-b799-4235-be94-a2b320d142e1">
