### ISSUE TITLE
Sidebar should have tooltips when links are ellided

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#60364]
See the attached screen shot for an example where the button text is truncated with `...`. In this case we should have a tooltip available so people can read the full text.

Tooltips do appear when the nav bar is in different states: ie: closed on the left side & along the top. 

If the bar is along the top (narrow screen) it might behave different if it was originally closed or not. Need to check that.

![Image](https://github.com/getsentry/sentry/assets/187460/3058b096-dd19-4b87-af68-ef8ef75b2870)

**Comment by Shubhdeep12** [comment]
Hey @ryan953 , I'm interested in working on this bug. Is it open for community contributions, and if so, could it be assigned to me? 

Your reply would be highly appreciated. Thanks!

**Comment by Shubhdeep12** [comment]
ok thanks @bruno-garcia
