### ISSUE TITLE
[Feedback List] Item Color & Icon Updates

### ISSUE THREAD

**Issue by Jesse-Box** [getsentry/sentry#60367]
### Acceptance Criteria
- update footer signifiers
- signifiers have tooltips
- both themes have a consistent visual treatment

### Footer signifiers
|  State | Screenshot  | 
|---|---|
| Else | ![Image](https://github.com/getsentry/sentry/assets/6508377/00d638b5-5993-401d-b9d7-56069a238807) | 
| Linked Replay | ![Image](https://github.com/getsentry/sentry/assets/6508377/eb218305-b1e8-4a07-bb57-eeb4c3ac6856)  | 
| Linked Issue (Crash Reports) | ![Image](https://github.com/getsentry/sentry/assets/6508377/33e14d08-c155-4b02-b5df-9ccbeb520f8e) | 
| Linked Replay & Issue | ![Image](https://github.com/getsentry/sentry/assets/6508377/0e9bcaff-ab82-446d-bd08-136dcdf0c030) | 
| Linked Replay & Issue with 1 Issue Tracker Ticket Linked | ![Image](https://github.com/getsentry/sentry/assets/6508377/0e7298c1-fa48-443b-9a14-9d7a4c1a1d9e) | 
| Linked Replay & Issue with >1 Issue Tracker Ticket Linked | ![Image](https://github.com/getsentry/sentry/assets/6508377/864028ff-740e-4fec-8e73-320ee9d86652) | 
| Linked Replay & Issue with >1 Issue Tracker Ticket Linked plus assignment | ![Image](https://github.com/getsentry/sentry/assets/6508377/4124e564-e33d-423f-aaa9-b5a66d0991df) | 

#### Light
![Image](https://github.com/getsentry/sentry/assets/6508377/3c619456-6072-4b5f-bdda-6ad84ad119df)
#### Dark
<img width="792" alt="Dark Mode" src="https://github.com/getsentry/sentry/assets/6508377/88dd9db3-1531-4576-b96d-9f27b4b3c967">

**Comment by jas-kas** [comment]
Related to implement ticket - https://github.com/getsentry/sentry/issues/60371

**Comment by ryan953** [comment]
Implementation note about the white text on purple background:

```
import {darkTheme} from 'sentry/utils/theme';

const config = useLegacyStore(ConfigStore);

// I think hard-coding to dark-mode is the rigth way, but hard-coding to light might be the way. IDK. we do need to hard-code to a theme so color doesn't change.

  return (
    <ThemeProvider theme={darkTheme}>
       <... the selected row />
   </ThemeProvider>
  );
```

**Comment by ryan953** [comment]
closed with https://github.com/getsentry/sentry/pull/60430

**Comment by bruno-garcia** [comment]
Displaying linked issue affected by: https://github.com/getsentry/sentry/issues/60478

**Comment by michellewzhang** [comment]
> Displaying linked issue affected by:
> 
> * [[Feedback - bug] Linked issue not showing up in feedback details, even though associated_event_id exists and source is crash report modal #60478](https://github.com/getsentry/sentry/issues/60478)

@bruno-garcia I think this is a separate issue. The ticket you linked is saying that there was a crash report icon but no linked issue was shown in the details
