### ISSUE TITLE
User Feedback focus color for the infinite scrolling list needs fixing in dark-mode

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#60365]
This probably also applies to virtual lists around the app (like replay). We should check that too

But the problem is when you're using your keyboard to navigate the page, the focus color for that list isn't great. We should update the color

What it looks like now:

![Image](https://github.com/getsentry/sentry/assets/187460/5e80d3dc-accb-4493-acde-295d54b05b87)

The code that applies the color is actually coming from browser defaults. See `.ReactVirtualized__Grid .ReactVirtualized__List`  gets `.focus-visible` and `data-focus-visible-added` added, which sets UA styles: `outline: -webkit-focus-ring-color auto 1px;`

The list container could also use some rounded corners at the bottom to match the container/border.

![Image](https://github.com/getsentry/sentry/assets/187460/c01124de-90ed-4773-a508-5f9743464e85)

**Comment by lcsvcn** [comment]
Is any news when this will be available to all sentry users, not only superuser?

<img width="445" alt="Screenshot 2024-05-10 at 14 30 39" src="https://github.com/getsentry/sentry/assets/6011385/95118fcd-a4c0-41eb-b774-c4a4fd12c04f">


It has been "under development" for more than 3 years accordingly to this [reference](https://github.com/getsentry/sentry/issues/22887)

**Comment by hubertdeng123** [comment]
@lcsvcn could you file another issue for this?
