### ISSUE TITLE
[Design] Iconography to Represent Any External Tickets Linked To Feedback

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#60371]
## Solution

One ticket linked to a feedback: Display a GitHub/Jira/or other Relevant Icon on the List for Individual User Feedbacks when there is a ticket linked to a feedback.

Multiple tickets linked to a feedback: Display **N icon** on the List for Individual User Feedbacks when there are multiple tickets linked to a feedback. [ TBD on Design ]

See list item component designs here: https://www.figma.com/file/ga57zyLonVCSJIH3kOWLVA/Specs%3A-User-Feedback-v1?type=design&node-id=3%3A11969&mode=design&t=gSUaxIQcK424XKnG-1

**Comment by jas-kas** [comment]
cc/ @Jesse-Box @ryan953 @michellewzhang

**Comment by ryan953** [comment]
I think the design of this stuff is covered by https://github.com/getsentry/sentry/issues/60367 and looking good. Possible to close this up now!
