### ISSUE TITLE
Display issue short id in email alert

### ISSUE THREAD

**Issue by kjlundsgaard** [getsentry/sentry#6040]
I spoke with someone at RailsCamp who has started using the "Fixes SENTRY-" commit feature, but wanted a reference to the issue's short id in the email to make the workflow a bit smoother/less annoying.

**Comment by tkaemming** [comment]
This is a good idea — adding this to the subject line would also help with some cases where a bunch of distinct issues with a similar messages end up grouped into the same email thread by clients that don't respect the `References`/`In-Reply-To` headers and make skimming the thread history really confusing.

**Comment by billyvg** [comment]
Closed in https://github.com/getsentry/sentry/pull/6992
