### ISSUE TITLE
Determine way to detect if notifications are not being sent

### ISSUE THREAD

**Issue by jangjodi** [getsentry/sentry#60401]
- Determine way to track how many notifications should be sent and how many were sent
- Consider using anomaly detection

**Comment by mikejihbe** [comment]
@jangjodi did we decide not to do this? 

The way to do it in datadog would be to create 2 metrics: one for when deciding to send a notification and one when it's actually sent and subtract them. Then just maintain a threshold monitor.

**Comment by jangjodi** [comment]
@mikejihbe Thanks for finding this again, I think I lost track of this ticket. I'll work on completing it this week or early next week.

**Comment by ceorourke** [comment]
Closing as I have no context on this and it sounds like it was completed.
