### ISSUE TITLE
Alerts (metrics and issues) configured to be sent to a Slack channel do not arrive on some occasions.

### ISSUE THREAD

**Issue by velajos** [getsentry/sentry#60429]
Hi @scttcper 

I have several alerts configured for metrics and issues, simultaneously sent to an email and a Slack channel. But on some occasions, only the notification arrives in the email.

These alerts are triggered at least ten times daily, so I don't think it relates to saturation issues during sending.

Does the configuration below have anything to do with it?

![Captura de pantalla 2023-11-21 175651](https://github.com/getsentry/sentry/assets/84612635/bb3caeb3-b997-4e12-946b-0947e7a5794f)

What would be the ideal configuration for the Digests section?

I really appreciate any help you can provide.

**Comment by roggenkemper** [comment]
hi! digests shouldn't have anything to do with Slack not getting any notifications. How often do you not get the slack notifications for your alerts?

**Comment by velajos** [comment]
> hi! digests shouldn't have anything to do with Slack not getting any notifications. How often do you not get the slack notifications for your alerts?

Normally one or two alerts are generated per day. But they don't always arrive to Slack, but to the mail they always arrive. I don't know what the problem is.

**Comment by brianthi** [comment]
Hi, for us to more effectively help you, could you create a support ticket to include a URL to the Issue and Metric alert in question, and which issues you got notified for and which you didn't? https://help.sentry.io/. You may reference this GH issue in the support request as well.
