### ISSUE TITLE
Use icons instead of dots/blobs for warning/error/info indicators

### ISSUE THREAD

**Issue by Firesphere** [getsentry/sentry#60446]
### Problem Statement

The Colour coding is hard to distinguish for colour blind people. E.g. on Issues, the coloured rectangle on the left of the issue
Or when looking at an issue itself, the dot next to the error description (Fatal errors that are not handled do have an icon in the latter situation)

### Solution Brainstorm

Show an icon that clearly indicates error/warning/fatal/etc. instead of only a colour, so that people with colourblindness can also easily distinguish the different levels of recorded issues.

### Product Area

Issues

**Comment by roggenkemper** [comment]
Thanks for the feedback. That definitely seems like an area we can improve on. I'll add it as someone for the team to look at.

**Comment by scttcper** [comment]
Hello! Internally we tested using icons and icons + words and nothing worked quite a well for us as the colored level dots.

Can see some of the iterations here:
https://github.com/getsentry/sentry/pull/77117
https://github.com/getsentry/sentry/pull/79160
https://github.com/getsentry/sentry/pull/79152
