### ISSUE TITLE
Rate Limiting per Issue, Threshold for number of events per Hour

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#60453]
### Problem Statement

**Ask:** "I'd like to Rate LImit any new issue to 500 events max per hour, for that issue"

**Why:** "Because if Rate LImit is for all of the Projects' Issues, then when the Rate Limit becomes effective ,it starts muting out lower volume issues which are super important to us from a visibility perspective, so we'd rather only mute out the Issues that are exceeding the 500 events/hour threshold"

Not sure if cardinality or total number of unique issues makes this hard.

### Solution Brainstorm

Maybe a Project or Org Setting so you can specify a Rate Limit for the Issue.

### Product Area

Issues

**Comment by roggenkemper** [comment]
Just to clarify - instead of having a rate limit per project, you want one per issue, so that some issues you can limit while other (lower volume ones) can continue fully coming in?

**Comment by achernoprudov** [comment]
> Just to clarify - instead of having a rate limit per project, you want one per issue, so that some issues you can limit while other (lower volume ones) can continue fully coming in?

Yes, that's correct. Right now we completely ignore the issues but instead would be nice to have some control on the issues.

**Comment by scefali** [comment]
@thinkocapo Yea, I've had this idea as well. We probably can't efficiently rate limited by issue because we'd have to figure out the grouping which requires Sentry to consume it BUT we might be able to rate limit based on a specific message since Relay could do that. That being said, this isn't high on the issues's team list of priorities so I'm not sure when we'd do it.

**Comment by mikejihbe** [comment]
Consider our "archive until escalating" feature for issues like this. That should suppress noise from it until volume starts to increase.

Steve is right that we likely wont prioritize this anytime soon, so closing for now.
