### ISSUE TITLE
Can not log in after ugrade 23.6.0dev0 -> 23.6.2

### ISSUE THREAD

**Issue by E-lit** [getsentry/sentry#60476]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1) stop sentry 23.6.0dev0
2) download sentry-23.6.2
3) copy sentry-23.6.2 to previous sentry foler
4) run install.sh
5) run sentry with docker compose up -d
6) log in to Sentry web UI using existing account
7) create new super user account using docker-compose run --rm web createuser
8) log in as new superuser

### Expected Result

working Sentry UI

### Actual Result

No Organization Access

You do not have access to any organizations within Sentry.

If you were expecting otherwise, this may be due to a configuration change in the organization. Please check your email inbox for an invite link to rejoin the organization.

### Product Area

Unknown

### Version

23.6.2

**Comment by E-lit** [comment]
Find out that upgrade was 23.6.0 -> latest instead of 23.6.0 -> 23.6.2

**Comment by buffcode** [comment]
@E-lit may be this helps: https://github.com/getsentry/self-hosted/issues/2582#issuecomment-1824442106

**Comment by fabio-thoma** [comment]
https://github.com/getsentry/self-hosted/issues/2582#issuecomment-1824442106 works.
