### ISSUE TITLE
[Feedback - bug] Linked issue not showing up in feedback details, even though associated_event_id exists and source is crash report modal

### ISSUE THREAD

**Issue by michellewzhang** [getsentry/sentry#60478]
Seems like there is an error when the endpoint attempts to fetch the event from the `event_id`:
<img width="568" alt="SCR-20231122-jnwf" src="https://github.com/getsentry/getsentry/assets/56095982/fe1e68b5-823b-441a-98c2-cfe5e0ca8881">

_Note: The crash report also does not show up in the old user feedback UI._

**Comment by bruno-garcia** [comment]
Hey @JoshFerge is this something you have context/can help with

**Comment by JoshFerge** [comment]
@bruno-garcia please see slack thread. https://sentry.slack.com/archives/C05J714QPRR/p1700685529985819?thread_ts=1700666386.573759&cid=C05J714QPRR

**Comment by bruno-garcia** [comment]
> it’s likely the error was filtered. and old user feedbacks should exist in full
> we are populating the old feedbacks as they were. we haven’t changed anything about those
