### ISSUE TITLE
Add a way to include jira on the slack + sentry integration

### ISSUE THREAD

**Issue by FilipeCosta** [getsentry/sentry#60503]
### Problem Statement

Currently with the integration of Jira + Sentry (manual integration), we need to reach out every time to the sentry dashboard whenever we want to create a new issue. Making this, an extra unnecessary step if we have the slack + jira integration since we already have a vision of the error with the slack bot.

### Solution Brainstorm

It would be nice if we could include an extra button in the slack bot that allows us to create the Jira ticket directly from there.

### Product Area

Settings - Integrations

**Comment by brianthi** [comment]
Hi @FilipeCosta, I'm not quite clear what you mean by Jira + Sentry (manual integration), but with the installation of the Jira integration described [here](https://docs.sentry.io/product/integrations/issue-tracking/jira/), you can create an issue alert rule which has the condition to create a Jira ticket when your [conditions match](https://docs.sentry.io/product/integrations/issue-tracking/jira/).
