### ISSUE TITLE
How to Set the SENTRY_LOG_LEVEL to info or debug

### ISSUE THREAD

**Issue by balaG4046** [getsentry/sentry#60505]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Hi team,

How to set the SENTRY_LOG_LEVEL to info or debug? in sentry application.

As of now we are using cloud watch to capture the logs.

### How are you getting stuck?

Kindly navigate  me to set the logs in sentry. 

### Where in the product are you?

Alerts

### Version

23.11.0

**Comment by balaG4046** [comment]
Hi Team,

Any update here

**Comment by azaslavsky** [comment]
You'll need to set an env variable for it in either your `.env` file or the `docker-compose.yml` file for the `web` container. More info [here](https://docs.docker.com/compose/environment-variables/set-environment-variables/).
