### ISSUE TITLE
Render blocking dropdown on resource summary page is cut off in small viewports

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry#60552]
<img width="1279" alt="image" src="https://github.com/getsentry/sentry/assets/18689448/0c328e80-12c7-4a04-a2a3-b28fad0b8015">

https://sentry.sentry.io/performance/browser/resources/spans/span/fc99ca7985acec0d/?end=2023-11-21T14%3A00%3A00&project=11276&start=2023-11-20T20%3A38%3A24

**Comment by DominikB2014** [comment]
Resolved in #60297
