### ISSUE TITLE
Additional Organizational Email Settings

### ISSUE THREAD

**Issue by crespire** [getsentry/sentry#60562]
### Problem Statement

I would like to send notifications to a specific secondary email on my account for an organization.

### Solution Brainstorm

An organization level notification setting already exists, and it would be nice to be able to set a target email address there too.

### Product Area

Settings

**Comment by natikgadzhi** [comment]
To clarify, do you meen a behavior similar to Github, where you can route notifications from certain organizations to certain email addresses already registered on your account?

**Comment by crespire** [comment]
> To clarify, do you meen a behavior similar to Github, where you can route notifications from certain organizations to certain email addresses already registered on your account?

Yes! If this is already possible, I may have overlooked it in the docs, but I did look!

**Comment by 17hogeju** [comment]
Hi @crespire!

Under user settings > email addresses, I know you can add a secondary email. For any notification where the delivery method is by email, it will send it to both addresses. 

Is this what you are looking for? Thanks!

**Comment by 17hogeju** [comment]
Ah, so you would like to be able to specify which email rather than sending it to all emails registered to your account?

**Comment by snigdhas** [comment]
We do allow email routing by project. You can add another email like @17hogeju mentioned, and then set the desired email for projects in your various orgs via Settings > Account > Notifications > Email Routing
