### ISSUE TITLE
Add Crons onboarding options for Rails and Python

### ISSUE THREAD

**Issue by natikgadzhi** [getsentry/sentry#60566]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Here's the loom video overview!

<div>
    <a href="https://www.loom.com/share/ca825bd2b9644b9c81d822abc3eeffb0">
      <p>Issues — sentry — Sentry - 25 November 2023 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/ca825bd2b9644b9c81d822abc3eeffb0">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/ca825bd2b9644b9c81d822abc3eeffb0-with-play.gif">
    </a>
  </div>

- Click **Crons** on the sidebar nav in a project where you don't have any cron monitores setup yet
- Pick a platfrom from the platform grid (Rails or Python)
- No Upsert (programmatic) monitor onboarding :sadpanda:

### Expected Result

Both Ruby and Python SDKs have ways to programmatically make new crons monitors, so we should show those options to the users!

### Actual Result

No Upsert (programmatic) monitor onboarding :sadpanda:

### Product Area

Crons

### Version

23.12.0.dev0

**Comment by natikgadzhi** [comment]
To clarify, if you agree that we should indeed add those onboarding notes — I'm happy to push them up in a pull request.

**Comment by gaprl** [comment]
Hey there @natikgadzhi PR's are always welcome! Rails is indeed missing, however, Python doesn't currently support upsert (hence why Celery is in a different category in our in-app guides). It is in our roadmap, though.

**Comment by davidenwang** [comment]
Neel actually went ahead with this and added rails upsert options https://github.com/getsentry/sentry/pull/60600, so going to close this out
