### ISSUE TITLE
Blocking errors from certain OS version

### ISSUE THREAD

**Issue by KoderFPV** [getsentry/sentry#60606]
### Problem Statement

We cannot block certain OS version errors on sentry.
We would like to block all errors from Android < 9, and Chrome < 90. 
The only way is to block it by the user agent in the codebase. 

### Solution Brainstorm

Maybe something like a minimum OS version? Or the ability to add it to inbound filters?

Best regards

**Comment by MichaelSun48** [comment]
Hey @KoderFPV, this appears to be a very similar request to [this](https://github.com/getsentry/sentry/issues/79743) ticket, and I'll reiterate Matt's recommendation to use client side filtering with `beforeSend` as a workaround. This is a good feature request, though, and it feels like a natural extension of the pre-defined browser inbound filters we already have, so keep an eye out on that ticket for any updates. Going to close this ticket out in favor of that one for now.
