### ISSUE TITLE
User IDs do not display under "Tag Details"

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#60665]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

**Description**
When applying an ID for [identifying a user](https://docs.sentry.io/platforms/node/enriching-events/identify-user/), the ID is applied correctly, however you cannot view it on the tags breakdown.

Example of outcome behavior in my test org: https://j-org.sentry.io/issues/4675563863/events/9c15955322bb42f9a0e774ba231ea8ed/tags/user/?project=4503995763916800&statsPeriod=30d

### Expected Result

Affected users to display ID

### Actual Result

<img width="540" alt="Screenshot 2023-11-27 at 4 00 20 PM" src="https://github.com/getsentry/sentry/assets/8451987/7b415c62-924a-4ca5-826e-fd736a1b2794">

### Product Area

Issues

**Comment by snigdhas** [comment]
The [values](https://j-org.sentry.io/issues/4675563863/tags/?project=4503995763916800&query=is%3Aunresolved&referrer=issue-stream&stream_index=0) for the user tag don't appear to be user IDs. It looks like we convert the User IDs -> Users when viewing the tag values in `tags/user` and those values aren't able to be converted.

**Comment by bbjay** [comment]
@snigdhas so would a fallback to display user IDs, when the conversion is not possible, be a solution here?
I assume that's how the user tag overview in `tags/` currently works, as the user IDs are visible there:

<img width="397" alt="Bildschirmfoto 2024-04-05 um 12 20 16" src="https://github.com/getsentry/sentry/assets/324694/39f5946b-a748-43bf-a5e6-391695d82cfe">


It's just in tag details (`tags/user`) that the IDs are not displayed:

<img width="701" alt="Bildschirmfoto 2024-04-05 um 12 21 36" src="https://github.com/getsentry/sentry/assets/324694/151fb539-0be0-442c-b5fa-923c7f52a00d">

**Comment by roggenkemper** [comment]
@bbjay yeah, I think that's the best option. ill work on fixing this and keep you updated

**Comment by bbjay** [comment]
I see this is working again, so this issue can be closed. Thanks to whoever worked on a resolution!

**Comment by JoshFerge** [comment]
thank you @bbjay!
