### ISSUE TITLE
Is it possible to remove the `server_name` tag?

### ISSUE THREAD

**Issue by adamreisnz** [getsentry/sentry#6066]
We're using Sentry on Heroku, and the reported `server_name` is downright useless:

![image](https://user-images.githubusercontent.com/490562/30203407-239c7d0a-94d6-11e7-9cae-b6c03b046af1.png)

Is there a way to prevent this tag from showing up / suppress it?
Right now it gets in the way of fast visual grepping when scanning for useful information about the error.

**Comment by dcramer** [comment]
@adamreisnz it depends on the SDK, as thats whats collecting it. I'm not sure if they truly let you suppress them as there is still value even if its not a real server. Usually there's something like 'server_name' in the configuration that you can pass.

For example, if you see it happening only on one node, it could indicate some other kind of problem.

**Comment by adamreisnz** [comment]
For the node SDK. It's just that for us there is no value to it, as we only have one server/node running the app, and it only creates meaningless noise. Could I overwrite it or suppress it by passing say a null or undefined value?

**Comment by dcramer** [comment]
@adamreisnz good chance null might make it set a default but I didn't verify. It's def something we should make it so you can clear the default but I imagine we don't yet today and there's not a defined behavior. 

Are you on saas? Is it just about visual distraction?

**Comment by adamreisnz** [comment]
Yes, on Heroku, it's mostly a visual distraction at this point not a big deal though. 
I like using the tags for some other variables we report through Sentry, and I just noticed that I get distracted by the `server_name` when I'm looking for similar tags.

**Comment by oliviertassinari** [comment]
@adamreisnz You can use the `dataCallback` property of the node SDK:
```js
      dataCallback: data => {
        // https://github.com/getsentry/sentry/issues/6066
        // We already add a docker tag.
        // The `server_name` doesn't provide any useful information.
        // eslint-disable-next-line no-param-reassign
        delete data.server_name

        // https://github.com/getsentry/raven-node/issues/188
        // Remove the used packages from the payload sent to Sentry.
        // The dependencies are versioned and locked with yarn. It's pointless.
        // eslint-disable-next-line no-param-reassign
        delete data.modules
        return data
      },
```

**Comment by adamreisnz** [comment]
Brilliant, thanks @oliviertassinari
