### ISSUE TITLE
Link from profile frames in application code to specific line in Github

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry#60668]
### Problem Statement

When I mouse over a slow frame in my application source code, I want to be able to quickly see where the problem lies without having to switch to my IDE and look up the file. I don't care about system level frames.

Assume I have the Github(/Bitbucket/Gitlab) integration enabled.

<img width="1786" alt="Screenshot 2023-11-27 at 4 21 37 PM" src="https://github.com/getsentry/sentry/assets/12092849/3aa90918-099c-429f-bee3-1d307a6f169c">

### Solution Brainstorm

Sentry could provide a direct link to that line of application code in Github/Bitbucket/Gitlab. This was @ndmanvar 's idea and I think it would be a pretty smooth experience.

### Product Area

Profiling

**Comment by JonasBa** [comment]
@cstavitsky we only allow this for python right now, but let me enable it for javascript as well and we'll see how well it works
