### ISSUE TITLE
Get Vue application usage count by unique users

### ISSUE THREAD

**Issue by iserialize** [getsentry/sentry#60679]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Hi, we currently use sentry.io as a crash reporting service however, we also enrich the data via setUser to set the users name and email address. I was wondering if its possible to start tracking the application usage and running a report end of the month to find out how many unique users used the application. We are currently on the Teams plan so not sure if its something you can do in the more expensive plans.

### How are you getting stuck?

Cant find any documentation on use case.

### Where in the product are you?

Discover

**Comment by ishkebab** [comment]
@iserialize 
Hello, thanks for you question! 

So in the context of Sentry, you might try using the Discover page.  You could build a chart with `event type: error` and set the y-axis to `count_unique(user)` with the interval set to 30 days.  This would count the number of unique users sending events to Sentry per month.  Of course, this would only reflect Sentry errors data - it would count the number of unique users who sent errors in the last 30 days (not including those users who did NOT send any errors).  

If you are looking to understand the total number of monthly users as a product metric, you may want to consider something like Google analytics.  As you said, Sentry is intended as an error and performance monitoring platform, so it may not specifically work for this use case.  

Let me know if you have any further questions!

Ash
Product Manager
