### ISSUE TITLE
User Feedback Shortcodes

### ISSUE THREAD

**Issue by gggritso** [getsentry/sentry#60715]
### Problem Statement

I wish the new User Feedback feature supported shortcodes! It makes it much easier to reference them in my TODOs, and more importantly I'd love to comment with "Fixes SENT-XX" in my GitHub PRs to automatically close the feedback on merge.

### Solution Brainstorm

If User Feedback could have the same shortcode system as our Issues and supported incoming hooks from GitHub, that'd solve it for me!

### Product Area

User Feedback

**Comment by jas-kas** [comment]
Update: We do have User Feedback shortcodes _if_ you create a GitHub issue directly from the User Feedback Details view that _should_ function similar to how the Issues product works.

An incremental improvement we can make to the UI is to reflect the shortcode on the User Feedback Details view. 

cc/ @ryan953 @JoshFerge

**Comment by ryan953** [comment]
Fixed with https://github.com/getsentry/sentry/pull/61227

**Comment by gggritso** [comment]
Woo! Thanks!
