### ISSUE TITLE
Loader on Performance -> Web Vitals page is positioned correctly.

### ISSUE THREAD

**Issue by Shubhdeep12** [getsentry/sentry#60756]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Visit - https://***.sentry.io/performance/browser/pageloads/

### Expected Result

The loader should be positioned relative to the chart, not the whole page.

### Actual Result

https://vimeo.com/889394397/e0df979ea1?share=copy

### Product Area

Performance - Web Vitals

**Comment by Shubhdeep12** [comment]
Please confirm if it's a valid issue. 
It's a minor styling issue, I'll push a commit for this, after confirmation

**Comment by edwardgou-sentry** [comment]
Hey @Shubhdeep12 , yes this does look like a valid issue, thanks for raising!
Feel free to tag me if you're working on a pr to fix this.

**Comment by Shubhdeep12** [comment]
Hi @edwardgou-sentry 
Thanks for the confirmation.


Attached the PR for the same.

Thanks

**Comment by wmak** [comment]
Closed by https://github.com/getsentry/sentry/pull/61015
