### ISSUE TITLE
No Performance metrics are being collected

### ISSUE THREAD

**Issue by codingmoh** [getsentry/sentry#60779]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

sentry-sdk[fastapi]==1.37.1

### Steps to Reproduce

We're running a fastAPI and want to use performance tracking but unfortunately there are not transactions being collected at all - errors/issues however are being collected - I've tried figuring out what's been missing but couldn't pinpoint the problem - I saw in other discussions that initializing the fastAPI app first may be help resolve the issue - but it didn't, I've also tried using the fastApiIntegration (from sentry_sdk.integrations.fastapi import FastApiIntegration) - but it didn't resolve the problem either.

This what our code looks like right now:

What are we missing?

```
app = FastAPI()
app.include_router(atelier_router)
app.include_router(qr_code_router)

app.add_middleware(
  .....
  ....
)

sentry_sdk.init(
    dsn="https://xxxxxxx@xxxxxxxxxxxx.ingest.sentry.io/xxxxxxxxx",
    # Enable performance monitoring
    enable_tracing=True,
    traces_sample_rate=1.0,
    integrations=[FastApiIntegration()],
    profiles_sample_rate=1.0,
)
```

Thanks!

### Expected Result

Performance and transaction metrics are being collected

### Actual Result

![image](https://github.com/getsentry/sentry-python/assets/829818/f9d1b1a7-129d-4a86-b8d9-5ac91f528a1b)

**Comment by kerenkhatiwada** [comment]
Hey @codingmoh, this would require taking a look at your organization. If this issue is still occurring, please write in to support@sentry.io with your issue.
