### ISSUE TITLE
[User Feedback] Sometimes the replay attached to a feedback renders as a squished line

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#60800]
![Image](https://github.com/getsentry/sentry/assets/187460/c5ca6847-b765-419a-9b66-e8e70558d584)

This could be because the replay is really new, and still processing. We need to repro the issue first to confirm. If that's the case, then we should do something to avoid this rendered outcome; it's better to show nothing for example.

I can repro after refreshing it a few times:

https://sentry.sentry.io/feedback/?alert_rule_id=14726850&alert_type=issue&feedbackSlug=javascript%3A4703586643&notification_uuid=554b5560-bd30-4f2e-bee1-a1b5b71525a8&project=11276&project=5953206&referrer=slack&statsPeriod=14d

Replay of observing the repro:
https://sentry.sentry.io/replays/054f44192d96404b83d45f13fcd4a2da/?project=11276&project=5953206

**Comment by ryan953** [comment]
@billyvg looked into this, and it seems like these replays are missing the `meta` rrweb frame, which happens when we're in a buffered context. 

To improve the UI i'll set a min height, and look for that frame. If it's missing we can show an error for people.

**Comment by billyvg** [comment]
Fixed and released in sdk version `7.87.0` -- UI also display an Error when this happens
