### ISSUE TITLE
Support for tags, aggregate data in Issues dataset for Dashboard widgets

### ISSUE THREAD

**Issue by rpropst** [getsentry/sentry#60840]
### Problem Statement

The issues dataset is the only way users can get to issue state, but using it prevents including columns such as `count()` (aggregation) or event values like tags.

Additionally it doesn't support filtering on these values

This makes it impossible to create a widget we need such as: 
* Show a widget of all issues where `count_unique(user)` is > 1000
* Show a widget of issues with the associated custom tag value (such as feature flag)

### Product Area

Dashboards

**Comment by nanoburd** [comment]
Do we think this is necessary for dashboards or perhaps is a more general way to "prioritize" and filter issues in the issue feed?

cc/ @rachrwang

**Comment by alexjillard** [comment]
As progress is made on [EAP](https://github.com/getsentry/projects/issues/43) and the Issues data is exposed, features like this should become possible. @phacops feel free to reopen if isn't the case.
