### ISSUE TITLE
Hide metric

### ISSUE THREAD

**Issue by jan-auer** [getsentry/sentry#60860]
requirements:
- hide only for `custom` namespace
- as a v0, hide only the metric in the `metrics/meta` endpoint
- audit entry

technical implementation:
- store a block list in project option
- in meta endpoint: hide the hidden metrics
- in data endpoint: do not prevent querying (for now)

validation:
- check DDM UI
- check alerts
- check dashboards

**Comment by iambriccardo** [comment]
We agreed on making blocking + hiding as two operations that happen within the same action. This means that a user blocking a metric will result in the metric being hidden in the UI completely but the user WILL still be able to search for it (for now, but we might change this later down the road).
