### ISSUE TITLE
Unable to load Sentry app in Jira Cloud

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#60869]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Unable to configure Jira integration with Sentry or see Sentry linked issues in Jira.

1. In Jira go to Manage Apps -> Sentry -> Configure
Result: 
![Screenshot 2023-11-30 at 14 50 36](https://github.com/getsentry/sentry/assets/64906376/bc1d912d-50cb-4ceb-9d61-82ad8ed151f3)

1. Open any issue in Jira
2. Expand Sentry on the right side menu:
![Screenshot 2023-11-30 at 14 48 41](https://github.com/getsentry/sentry/assets/64906376/eae52b42-511c-41e8-a677-167ee7c186f2)

Re-installing the application does not resolve the issue.

### Expected Result

When navigating issues: to see sentry linked issues.

When configuring the integration: to open the modal to select which organisation you want to install the Jira integration. 

### Actual Result

See above

### Product Area

Settings - Integrations

**Comment by snigdhas** [comment]
This issue typically occurs if you have an ad blocker blocking the conversation between JIRA and Sentry during setup. See https://docs.sentry.io/product/integrations/issue-tracking/jira/#something-went-wrong-message-with-jira-on-saas-sentryio-install

**Comment by rodolfoBee** [comment]
@snigdhas I do not have ad-blockers enabled when testing.

**Comment by snigdhas** [comment]
Thanks for confirming. And just to double check, have you read through the [troubleshooting](https://docs.sentry.io/product/integrations/issue-tracking/jira/?utm_medium=text&utm_term=jira&utm_content=atlassian&utm_source=marketplace&utm_campaign=partner#troubleshooting) tips and confirmed the following:

```
- The provided installation URL is a fully qualified domain name (FQDN), which is resolvable on the internet.
- The IP addresses Sentry uses to make outbound requests are [allowed](https://docs.sentry.io/product/security/ip-ranges/?utm_campaign=partner&utm_content=atlassian&utm_medium=text&utm_source=marketplace&utm_term=jira).
- Sentry's access to your installation URL is not path restricted.
- Make sure your instance is routable (that is, our server can reach it!)
```

**Comment by malwilley** [comment]
Thanks for all the information - I've placed this on our backlog to fix.

**Comment by rodolfoBee** [comment]
@malwilley is there any ETA for when it will be resolved? At the moment it is not possible to install the integration in Sentry.

**Comment by malwilley** [comment]
Fix has been merged and I can confirm that it appears to be working now 🎉
