### ISSUE TITLE
New User Feedback interface does not show the correct environment when associated to an error

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#60871]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Enable the new user feeback interface from Organization Settings > General Settings > Early Adopter
2. Set up a basic JS application with the corresponding Sentry SDK that collects user feedback through the [Embeddable JavaScript Widget](https://docs.sentry.io/platforms/javascript/guides/react/enriching-events/user-feedback/#embeddable-javascript-widget)
3. In the Sentry init, set the environment option to "example"
4. Run the app and trigger a test error and send user feedback through the pop-up window
5. Head to the User Feedback tab in the Sentry Web UI

### Expected Result

The environment of the user feedback is "example".

### Actual Result

The environment from [this user feedback](https://dragonfruit-dev.sentry.io/feedback/?feedbackSlug=javascript-react%3A4684745097&referrer=feedback_list_page&statsPeriod=90d) always defaults to "production".
![ufview](https://github.com/getsentry/sentry/assets/81985895/1165ab72-e490-4030-b613-d9b9ff531341)

However, if we open [the event](https://dragonfruit-dev.sentry.io/issues/4680186801/events/e6a145dee9b74d23afae6e222abd77b7/?project=4504179109068800&referrer=compact-issue) the feedback originated from, the environment tag correctly shows the value "example".
![ufevent](https://github.com/getsentry/sentry/assets/81985895/e288beb0-f923-456d-9cac-5903d9f4808d)

Additionally, if we submit [user feedback](https://dragonfruit-dev.sentry.io/feedback/?feedbackSlug=javascript-react%3A4684708631&referrer=feedback_list_page&statsPeriod=90d) through the [@sentry-internal/feedback](https://www.npmjs.com/package/@sentry-internal/feedback) package, the environment is correctly set to "example".
![ufnew](https://github.com/getsentry/sentry/assets/81985895/5fe553f4-a2d7-49d2-967d-53a92e77ea7e)

### Product Area

User Feedback

**Comment by bruno-garcia** [comment]
Thanks for reporting this! It does look like a bug.

The SDK by default sends `production` so there might be something to do with applying scope data to the feedback. We'll figure out.

**Comment by bruno-garcia** [comment]
I can see in Sentry a different environment though (we use `prod` instead) so it might be something else.

**Comment by bruno-garcia** [comment]
![image](https://github.com/getsentry/sentry/assets/1633368/1a6269ad-775e-42c6-9f25-a7f78979b0fd)

Just tried and it worked for me. @billyvg was there a fix on 0.17 we should ask the customer to upgrade to?

**Comment by billyvg** [comment]
@bruno-garcia This is not an SDK issue - it seems like we are not properly copying the environment for the old crash reports? /cc @JoshFerge

**Comment by JoshFerge** [comment]
https://github.com/getsentry/sentry/pull/60953

**Comment by bruno-garcia** [comment]
:sanic:
