### ISSUE TITLE
New User Feedback interface does not link to the exact event the feedback originates from

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#60872]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Enable the new user feeback interface from Organization Settings > General Settings > Early Adopter
2. Set up a basic JS application with the corresponding Sentry SDK that collects user feedback through the [Embeddable JavaScript Widget](https://docs.sentry.io/platforms/javascript/guides/react/enriching-events/user-feedback/#embeddable-javascript-widget)
3. Run the app and trigger a test error and send user feedback through the pop-up window
4. Head to the User Feedback tab in the Sentry Web UI
5. Click on the issue name that shows up in [the user feedback](https://dragonfruit-dev.sentry.io/feedback/?feedbackSlug=javascript-react%3A4684745097&referrer=feedback_list_page&statsPeriod=90d) that we just submitted

### Expected Result

We are redirected to the exact event inside the issue that the feedback originates from.

### Actual Result

We are redirected to [the latest event](https://dragonfruit-dev.sentry.io/issues/4680186801/?referrer=event-or-group-header&statsPeriod=90d) of the associated issue.
![1](https://github.com/getsentry/sentry/assets/81985895/ee0e4b16-406c-4562-bf35-2c561851a2c9)
![2](https://github.com/getsentry/sentry/assets/81985895/a3be0980-baad-45b1-9d27-b0cb1d363338)

However, if we return to [the old User Feedback](https://dragonfruit-dev.sentry.io/user-feedback/?feedbackSlug=javascript-react%3A4684745097&referrer=feedback_list_page&statsPeriod=90d) interface and click on the associated issue, we are redirected to [the exact event](https://dragonfruit-dev.sentry.io/issues/4680186801/events/e6a145dee9b74d23afae6e222abd77b7/?project=4504179109068800&referrer=compact-issue) within the issue that the feedback originated from.
![3](https://github.com/getsentry/sentry/assets/81985895/0355707a-6033-42ac-84db-189ca705bd52)
![Screenshot 2023-11-30 at 15 57 44](https://github.com/getsentry/sentry/assets/81985895/11224d24-414e-48ba-929c-1975fd9a590a)

### Product Area

User Feedback

**Comment by michellewzhang** [comment]
Working on a fix here: https://github.com/getsentry/sentry/pull/60985
