### ISSUE TITLE
De-emphasize Codecov line indicators

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#60892]
In order to have introduce syntax highlighting to the stack trace (https://github.com/getsentry/sentry/issues/47598), the Codecov line indicators will need to be de-emphasized. In the current state, the colors are too bold and will conflict with the subtle colors of the highlighted code.

![Image](https://github.com/getsentry/sentry/assets/10888943/1b5368f8-3c74-4d67-9d73-680f58e28d62)

**Comment by mrduncan** [comment]
Closing for now as the high-contrast is actually beneficial for some folks
