### ISSUE TITLE
Editing alert in alert menu not working

### ISSUE THREAD

**Issue by erfantkerfan** [getsentry/sentry#60897]
### Self-Hosted Version

23.11.0

### CPU Architecture

x86_64

### Docker Version

24.0.6

### Docker Compose Version

v2.21.0

### Steps to Reproduce

1. install [23.10.0](https://github.com/getsentry/self-hosted/releases/tag/23.10.0)
2. updated to [23.11.0](https://github.com/getsentry/self-hosted/releases/tag/23.11.0)
3. after visiting this [url](https://sentry.company.com/organizations/MyOrgName/alerts/metric-rules/MyProject/44/) to edit an alert I'm getting an error
![image](https://github.com/getsentry/self-hosted/assets/37825504/ccf9f75b-e756-42e9-9b8d-3133327d3cc8)
after digging more I found out that error is comming from this [url](https://sentry.company.com/api/0/organizations/MyOrgName/alert-rules/available-actions/)
![image](https://github.com/getsentry/self-hosted/assets/37825504/09caadf6-0e08-432b-a59d-7d167e013e2f)
here us the log for container `web`:
![image](https://github.com/getsentry/self-hosted/assets/37825504/df8f8038-ddae-4119-8779-8615a5392df3)

### Expected Result

for this page to load properly (it used to work)

### Actual Result

I get a 500 error code

**Comment by snigdhas** [comment]
@azaslavsky I'm not sure how we cut releases for self-hosted but there was some [HC work](https://github.com/getsentry/sentry/pull/58185) in this space in early October (around the time of 23.10.0 was released). Could those be related?

**Comment by vladborovtsov** [comment]
Same thing still happening on self-hosted 23.11.2.

**Comment by erfantkerfan** [comment]
I migrated from 23.7.1 to 23.12.1 one more time and the problem is fixed now.
Thanks sentry team.
