### ISSUE TITLE
JSON Schema for API

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#6095]
Let's implement JSON schema!

## Overview

Utilizing JSON schema will let Sentry's backend (API) describe to the frontend how forms should function. You can imagine this as an extension of the stuff we built ourselves (``get_config()`` on plugins for example), but in a standardized format. This means that to render the "Project Settings", we could hit an endpoint which describes the settings and the UI could be completely agnostic of the ordering/grouping of components.

In the cases where that's not acceptable, at the very least the backend can clarify what types, validation, and general metadata form components should take on.

## Implementation

This is mostly straight forward. Though without digging into a full design spec, we're going to only focus on the option.

There's a some unanswered questions:

1. What should be used to describe the schema?
2. How is schema queried and returned?
3. What details will we need that JSON schema doesnt support? 

### Schema Descriptions

We could continue using the REST serializers for input and build an output parser for them. Alternatively we could use Marshmallow (framework agnostic, used by Zeus).

I would side with using Marshmallow at this point, as it seemingly could replace all of our serializer code as well if we really wanted to invest into it. It's plausible REST framework can as well, however it's unclear that it'd be worth refactoring (and/or upgrading the framework) just to continue to be locked into Django.

### Querying Schema

There's two clear options that I see:

1. Adding some kind of ``?schema=1`` to endpoints (or possibly use ``OPTIONS``?). This has complexity in that we're going to always return a lot of data and we may not want it. For example, Sentry has a ton of options per project, and we dont render them all on one page right now.
2. Add a special 'schema' endpoint. This could be something like `/:endpoint/:schema/`.

In addition, we likely will want to make it possible to select which top level attributes are returned for the schema, which ensures changing the UI can be extremely minimal.

### Extending Schema

Cloudflare extends JSON schema in simplistic ways, so any cases that aren't supported we should be able to do similar.

### Dynamic Fields

For fields which are dynamic -- based on data in the form -- we can use pass in parameters to the schema API to get the new values. Cloudflare does this via webhooks, but you could imagine we simply POST to ``/:endpoint/schema/`` with the current values, and it returns the new schema.

**Comment by dcramer** [comment]
I'll note, that I was inspired by Cloudflare's fairly seemless plugin implementation which is based on this.

**Comment by dcramer** [comment]
Another note, this doesn't include the ``/store/`` endpoint, which we describe as "ingestion", though there might be a point where we also choose to spec that out with JSON schema as well.

**Comment by dcramer** [comment]
Quick proposal:

First, add a dedicated 'schema' query endpiont where relevant, which would be a defined endpoint:

```python
urls('/:endpoint/_schema/', SchemaEndpoint(for=SchemaClass))
```

(``:endpoint`` above would be replaced with each 'object' that exposes a schema, such as project details, org details, etc)

Second, the schema endpoint supports a selection of fields using something like:

```
/.../_schema/?attr=X&attr=X&attr=X
```

By default it'd return the entire schema available to the given endpoint, but attrs would allow you to return only specific names, and it'd maintain the order of those.

Third, endpoints which expose schema could provide a header pointing to the location. This could be with something like X-Schema-URI or just an additional Link tag.

**Comment by dcramer** [comment]
Aside if we put schema under one giant endpoint, it would be easier to query 'find this setting'.

imagine /api/0/schema/ and you could pass some kind of description of what you wanted, e.g. project.* project.foo, project.bar, organization.*

**Comment by BYK** [comment]
We now have https://github.com/getsentry/sentry-data-schemas/
