### ISSUE TITLE
"Add integrations" link in Performance Page leads to nonexistent docs page

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#60966]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the Performance tab
2. Choose the Backend category
3. Choose a python project
4. On the "Slow HTTP Ops", if it is empty, you should see the message:

> No transactions with HTTP spans found, you may need to [add integrations](https://docs.sentry.io/platforms/python/configuration/integrations).

![image](https://github.com/getsentry/sentry/assets/81985895/6a8a5b94-2db3-4a79-8efe-ad5e23a86662)
5. Click on "add integrations"

### Expected Result

We are redirected to the integrations section of the python SDK docs.

### Actual Result

We are redirected to a Page Not Found docs page.
![image](https://github.com/getsentry/sentry/assets/81985895/a3a2f94f-ff29-4875-a56d-3f442fb4623d)

This is because the link leads to https://docs.sentry.io/platforms/python/configuration/integrations/ which does not exist anymore. Instead, it should lead to https://docs.sentry.io/platforms/python/integrations/

### Product Area

Other

**Comment by gggritso** [comment]
Yikes! Thanks for catching this! Unfortunately, different platforms have different URLs for this documentation 😞 I saw at least three just from clicking around:

- https://docs.sentry.io/platforms/ruby/configuration/integration_options/
- https://docs.sentry.io/platforms/dart/integrations/
- https://docs.sentry.io/platforms/javascript/configuration/integrations/

@vivianyentran would it be possible to standardize these URLs somehow, or set up redirects? What do you think?

**Comment by vivianyentran** [comment]
Thanks for bringing this up! @shanamatthews is the expert on our SDK docs, so I'll let her take the lead on this one.

**Comment by shanamatthews** [comment]
Hey @gggritso - let's set up redirects for now. What's the common URL format that the product uses for these links, is it https://docs.sentry.io/platforms/<platform>/configuration/integrations ?
