### ISSUE TITLE
GitHub validation failed when adding repository

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#6096]
GitHub is responding with an ``HTTP 422: Validation Failed`` in some cases.

**Comment by dcramer** [comment]
I haven't seen this before, hoping @getsentry/cops might have some idea.

I've confirmed the organization shows as "Approved".

**Comment by MeredithAnya** [comment]
@dcramer it came up once before when someone deleted the repo but at that point we didn't automatically delete the webhook from GitHub. So when they tried to re-add repo it failed. Removing the webhook fixed the issue.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
