### ISSUE TITLE
[User Feedback] Design - Add a segmented control to the top of the Feedback List to select between "Crash reports" and "All feedbacks" 

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#60978]
Or if we could make this type of thing more obvious from within the search box, that would be cool too.

-> Suggested searches anyone?

**Comment by c298lee** [comment]
If this is searchable, suggested searches is easy to implement!

**Comment by billyvg** [comment]
We can't do this because we can't search for crash reports atm.
