### ISSUE TITLE
The file was re-downloaded when the error was caught

### ISSUE THREAD

**Issue by MiRinZhang** [getsentry/sentry#6097]
###  The *JavaScript* file was re-downloaded when the error was caught.

I used the following packages

> `raven@3.17.0`

> The website loads Raven.js from CDN.
(`<script src="//hicn.mengxiaozhu.cn/raven/3.17.0/raven.min.js" crossorigin="anonymous"></script>`)

> `react@15.4.2`  `react-router@3.0.3`

> `webpack@2.3.2`

**Comment by mattrobenolt** [comment]
Can you explain what you mean?

**Comment by MiRinZhang** [comment]
@mattrobenolt 

> The server will download the`chunkFile` when an error was captured.

E.g

If `detail.c16e0.chunk.js` file capture error, the server will re-download `detail.c16e0.chunk.js` when report error.

**Comment by mattrobenolt** [comment]
Yes, this is working as intended. The server needs to download the file to construct a full stack trace. If you want to avoid this, you can upload release artifacts and use our Releases API and we'll download the files from our artifact store instead.

**Comment by MiRinZhang** [comment]
@mattrobenolt 

But always download the same chunkfile, which led to our CDN traffic is too large, the cost is relatively high~~~

Is there any way to solve this problem?

**Thanks**

**Comment by mattrobenolt** [comment]
> If you want to avoid this, you can upload release artifacts and use our Releases API and we'll download the files from our artifact store instead.
