### ISSUE TITLE
ignoreErrors not working

### ISSUE THREAD

**Issue by vcarel** [getsentry/sentry#6100]
I'm trying to make `ignoreErrors` work, and I can't figure how.
I'm using express with the following setup:

```javascript
import express from 'express'
import Raven from 'raven'

Raven.config('the dsn', { ignoreErrors: ['BOOM'] }).install()

const app = express()

app.use(Raven.requestHandler())

app.get('/boom', (req, res) => {
  throw new Error('BOOM')
})

app.use(Raven.errorHandler())
```

When I make a request to http://myserver/boom, Sentry captures the error.

I tried `/BOOM/` and `/.*BOOM.*/` for `ignoreErrors`. The error is always sent.
I'm on raven@2.1.2

**Comment by mattrobenolt** [comment]
@kamilogorek does raven-node even support this?

I’m going to close the ticket here at any rate since it’s on the wrong repository. See https://github.com/getsentry/raven-node

**Comment by kamilogorek** [comment]
@mattrobenolt it doesn't, `ignoreErrors` is available in `raven-js`, not `raven-node`. @vcarel please use `shouldSendCallback` method to filter unwanted errors.

**Comment by vcarel** [comment]
@mattrobenolt @kamilogorek My apologizes, I confused `raven-js` and `raven-node`.
BTW, shouldn't the APIs be consistant on this point ?

**Comment by kamilogorek** [comment]
@vcarel they will, we're working on it :)

**Comment by mhd999** [comment]
@kamilogorek Any update on this feature ?

**Comment by kamilogorek** [comment]
@mhd999 we're in the process of creating next major version of JS SDK – https://github.com/getsentry/raven-js/pull/1149
We'll definitely try to keep everyone updated as we go :)

**Comment by adamreisnz** [comment]
I've written a custom helper for this based on code found in raven-js, you can use it to support `ignoreErrors` while waiting for the SDK's to be unified.

Helper:

```js
/**
 * Join an array of string/regex patterns into a single regex (adapted from raven-js)
 */
function joinRegex(patterns) {

  //Initialize sources
  const sources = [];

  //Loop patterns
  for (const pattern of patterns) {

    //If it's a string, we need to escape it
    if (typeof pattern === 'string') {
      sources.push(pattern.replace(/([.*+?^=!:${}()|[\]/\\])/g, '\\$1'));
    }

    //If it's a regular expression already, we want to extract the source
    else if (pattern && pattern.source) {
      sources.push(pattern.source);
    }

    //Intentionally skip other cases
  }

  //Return combined regular expression
  return new RegExp(sources.join('|'), 'i');
}
```

Configuration converter:

```js
if (Array.isArray(cfg.ignoreErrors) && cfg.ignoreErrors.length > 0) {
  const ignoreErrors = joinRegex(cfg.ignoreErrors);
  cfg.shouldSendCallback = function(data) {
    if (data.message && typeof data.message.match === 'function') {
      return !data.message.match(ignoreErrors);
    }
    return true;
  };
}
```

This essentially defines a `shouldSendCallback` config property if you've passed `ignoreErrors` instead.
