### ISSUE TITLE
Sentry cloud in other regions?

### ISSUE THREAD

**Issue by zhou934381967** [getsentry/sentry#61019]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

no

### Expected Result

The data in China was reported normally

### Actual Result

China data cannot be reported

### Product Area

Stats

**Comment by leedongwei** [comment]
Hello, we will offer our SaaS product in other regions early next year. Please keep an eye out for the product announcement.

**Comment by zhou934381967** [comment]
When will the China region be released? Which region will it be released in early next year?

**Comment by leedongwei** [comment]
I don't have timelines. If you need it as soon as possible, you can set up a relay instance and forward the events to Sentry yourself: https://docs.sentry.io/product/relay/

**Comment by leedongwei** [comment]
If data residency is a concern for using Sentry, our SaaS service is available in EU: https://blog.sentry.io/sentrys-eu-data-region-now-in-early-access/

We're assessing demand for other geographical regions. Please reach out to support@sentry.io if your ideal region/country is not available.
