### ISSUE TITLE
Adding multiple projects in the Metric Alert Creation API endpoint creates invalid alerts

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#61031]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. User this endpoint to create a metric alert for more than one projects. I used the following:
POST https://sentry.io/api/0/organizations/dragonfruit-dev/alert-rules/
with body:
```
{
    "name": "test2",
    "timeWindow": 1,
    "projects": [
        "javascript-react",
        "javascript-nextjs"
    ],
    "query": "",
    "thresholdType": 0,
    "triggers": [
        {
            "label": "critical",
            "alertThreshold": 50,
            "actions": []
        },
        {
            "label": "warning",
            "alertThreshold": 25,
            "actions": []
        }
    ],
    "queryType": 1,
    "dataset": "generic_metrics",
    "aggregate": "avg(transaction.duration)"
}
```
2. Access the alert rule in the Sentry Web UI: https://dragonfruit-dev.sentry.io/alerts/rules/details/196063/

### Expected Result

Either 2 separate alerts with the exact same rule setup are created for the 2 projects or we get an error that the alert cannot be created.

### Actual Result

Upon creation, we get response 201 Created with response body:
```
{
    "id": "196063",
    "name": "test2",
    "organizationId": "1420511",
    "status": 0,
    "queryType": 1,
    "dataset": "generic_metrics",
    "query": "",
    "aggregate": "avg(transaction.duration)",
    "thresholdType": 0,
    "resolveThreshold": null,
    "timeWindow": 1.0,
    "environment": null,
    "resolution": 1.0,
    "thresholdPeriod": 1,
    "triggers": [
        {
            "id": "327482",
            "alertRuleId": "196063",
            "label": "critical",
            "thresholdType": 0,
            "alertThreshold": 50.0,
            "resolveThreshold": null,
            "dateCreated": "2023-12-04T13:26:36.398759Z",
            "actions": []
        },
        {
            "id": "327483",
            "alertRuleId": "196063",
            "label": "warning",
            "thresholdType": 0,
            "alertThreshold": 25.0,
            "resolveThreshold": null,
            "dateCreated": "2023-12-04T13:26:36.408845Z",
            "actions": []
        }
    ],
    "projects": [
        "javascript-nextjs",
        "javascript-react"
    ],
    "includeAllProjects": false,
    "owner": null,
    "originalAlertRuleId": null,
    "comparisonDelta": null,
    "dateModified": "2023-12-04T13:26:36.351585Z",
    "dateCreated": "2023-12-04T13:26:36.351593Z",
    "createdBy": {
        "id": 2377144,
        "name": "webhook-c99147-1eff691a-3eed-43e7-abbc-e6067df7e0c7",
        "email": ""
    }
}
```
In the Sentry Web UI, we can see the alert rule:
![image](https://github.com/getsentry/sentry/assets/81985895/23fe8757-27d7-45d6-9071-e96c9fe99172)

However, upon clicking on it, we get a 500 Internal Server Error with the message "An error occurred while fetching the alert rule."
![image](https://github.com/getsentry/sentry/assets/81985895/30a29501-b6f0-4380-8386-bd2a828bd431)

### Product Area

APIs

**Comment by schew2381** [comment]
I've confirmed with the issues team that metrics are currently restricted to a single project at a time. I've updated the [API docs](http://localhost:3000/api/alerts/create-a-metric-alert-rule-for-an-organization/) in the above PR to say the project should only contain a single project at a time, and @isabellaenriquez created a backlog issue to verify this in the POST.
