### ISSUE TITLE
Provide an ability to see triggered alerts from issues

### ISSUE THREAD

**Issue by Almad** [getsentry/sentry#61039]
### Problem Statement

I am trying to reduce incident noise for my teams, and it's hard to see which alert caused the incident with more complicated setups (50 alerts+). 

### Solution Brainstorm

- For IR system (PagerDuty in my case) in particular, it would be enough to add alert URL to the payload
- However, in general, I think it would be useful to have triggered alerts available on a timeline—possibly in the Incident's Activity tab?

### Product Area

Issues

**Comment by lobsterkatie** [comment]
Hi, @Almad. Thanks for the suggestions! 

Your first idea seems quite reasonable and likely wouldn't be that hard to implement. (In case you have any interest in giving it a shot, or for whoever picks this up: It seems like `send_incident_alert_notification` ([here](https://github.com/getsentry/sentry/blob/285473b5945468d48c43940a7a7b662f1e7a3cc7/src/sentry/integrations/pagerduty/utils.py#L59)) should be able to add the alert name to the payload via `action.alert_rule_trigger.alert_rule.name`, and the URL could probably be reconstructed fairly easily as well.) I've added it to our backlog.

The second idea is interesting, but would be a much bigger project, so I'm going to leave it as a feature request. If it's something we decide to pursue, we'll let you know!

**Comment by mikejihbe** [comment]
We plan to address this early next year with upcoming detector & workflow scope, so going to close this.
