### ISSUE TITLE
[Onboarding Sidebar] Update sidebar segmented controls and initial content

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#61069]
There's the existing project selector:
- [x]  Supported list should include backend projects now

Segmented control: I have JS Framework / I have HTML
- [x] Add the segmented control
- [x] Backend proj -> defaults to "I have HTML"
- [x] Frontend proj -> defaults to "I have JS framework"

**currently: the segmented control has memory though, so it won't reset after you pick another project**

<img width="472" alt="SCR-20231204-kdoz" src="https://github.com/getsentry/sentry/assets/56095982/d162eeef-84dd-480e-9d8e-1a48eed6f44b">

### Segmented Control 
**I have HTML**: Need to find/write Loader steps:
- [x] The "Step 1 - Install" loader snippet is the same snippet we show on the project settings page (the URL should be dynamic)
- [x] Step 1.5 -> Make sure that they have "Enable session replay" checked inside the project settings -> DSN -> Loader page (or bring the checkbox up here). (Further iteration https://github.com/getsentry/sentry/issues/62081)
- [x] The "Step 2 - Config" loader snippet includes "window.sentryOnLoad" and everything else from https://docs.sentry.io/platforms/javascript/install/loader/#custom-configuration

<img width="651" alt="SCR-20231204-kdbb" src="https://github.com/getsentry/sentry/assets/56095982/d415f87d-00b8-45bb-a25d-fd8b9826d12b">

**I have JS Framework**: The NPM steps are the same as what we show already (and are specific to the JS framework chosen)
- [x] The specific framework depends on the 2nd dropdown list. (2nd dropdown only shows up if it's a BE proj)
- [x] The 2nd dropdown list has the same list of frameworks as https://docs.sentry.io/platforms/javascript/session-replay/ on the right-sidebar

Followup: Checkboxes to configure the loader snippet (see figma): https://github.com/getsentry/sentry/issues/61071

**Comment by michellewzhang** [comment]
Backend proj -> defaults to "I have HTML"
Frontend proj -> defaults to "I have JS framework"

**Comment by michellewzhang** [comment]
The checkboxes (`maskAllText` etc) would apply to both loader and NPM. We'd have to write some extra code to perform the logic
