### ISSUE TITLE
Jira Integration is failing on "Get Started"

### ISSUE THREAD

**Issue by sjmcdowall** [getsentry/sentry#61062]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I just tried to install the Jira app for Sentry.io to our Jira Cloud instance.  The install itself appeared to go fine -- but anytime I try to "Get Started" or configure I get the following generic error message (not too helpful) ..

Tried to uninstall and re-install from within Jira .. same results .. 

This is reproducible for me .. 

![Screenshot 2023-12-04 at 12 30 05 PM](https://github.com/getsentry/sentry/assets/2034925/ded4f5c8-ae55-43fa-a76d-bedb7f2948de)

### Expected Result

Some sort of configuration screen is presented allowing me to link this to our Sentry.io account.

### Actual Result

![Screenshot 2023-12-04 at 12 30 05 PM](https://github.com/getsentry/sentry/assets/2034925/533a424c-70cf-4ae8-bb1b-7ac494c2c04a)

### Product Area

Settings

**Comment by kerenkhatiwada** [comment]
Also reported #61022

**Comment by sjmcdowall** [comment]
Not sure how helpful this is -- but here is a a dump of the console log from Chrome -- 
[truelook.atlassian.net-1701716770953.log](https://github.com/getsentry/sentry/files/13550367/truelook.atlassian.net-1701716770953.log)

**Comment by malwilley** [comment]
It appears that this is the same issue as https://github.com/getsentry/sentry/issues/60869 which was fixed in https://github.com/getsentry/sentry/pull/61128

@sjmcdowall if you try again it should be working now. Closing as fixed, but please respond if your problem is still ongoing.
