### ISSUE TITLE
[Replay Onboarding] Need a full list of all the platforms that we 'support'

### ISSUE THREAD

**Issue by michellewzhang** [getsentry/sentry#61070]
A full list of all the platforms that we 'support'. FE list based on `static/app/data/platformCategories.tsx`

Frontend/JS:
- capacitor
- electron
- javascript-angular
- javascript-angularjs **UNSUPPORTED (is this still true?)** 
  - angularjs requires the v6.x core SDK
- javascript-astro 
- javascript-backbone **no docs yet**
- javascript-capacitor
- javascript-electron
- javascript-ember
- javascript-gatsby
- javascript-nextjs
- javascript-react
- javascript-remix
- javascript-svelte
- javascript-sveltekit
- javascript-vue
- javascript

Backend: server side web apps
- Python - Django
- Python - Flask
- Java -Spring
- Java - Spring Boot
- .NET - ASP.NET
- .NET - ASP.NET Core
- PHP - Laravel
- PHP - Symfony
- PHP
- Go - Gin
- Go - FastHttp
- Go - Martini
- Go - Iris
- Go - Echo
- Node - Express
- Node
- Deno
- Bun
- Ruby - Ruby on Rails
- Elixir

**Comment by michellewzhang** [comment]
Closing for now since we have a comprehensive list as of today, but if there are edits/changes needed, update the description and comment for visibility

**Comment by bruno-garcia** [comment]
added complete list of Python frameworks
