### ISSUE TITLE
GitHub Code Mappings for .NET

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#61103]
These .NET based Sentry projects have code mapping issues:

https://sentry.sentry.io/issues/?project=5953206&project=1886021&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=1

For example this event doesn't have a _open on GitHub_:

![image](https://github.com/getsentry/sentry/assets/1633368/90ef090b-1472-4682-852d-a6cdcc991260)

```
{
"function": "async Task<IActionResult> SymbolsController.UploadSymbol(Guid batchId, CancellationToken token)",
"package": "SymbolCollector.Server, Version=1.13.0.0, Culture=neutral, PublicKeyToken=null",
"filename": "SymbolsController.cs",
"abs_path": /app/server/src/SymbolCollector.Server/SymbolsController.cs",
"lineno": 208,
"colno": 13,
"in_app": true,
"data": {
"symbolicator_status": "missing"
},
"instruction_addr": "0x1f6",
"addr_mode": "rel:3",
"function_id": "0x122"
},
```

File: https://github.com/getsentry/symbol-collector/blob/16facc91ffddce74918f452be19423b3b4fd105f/src/SymbolCollector.Server/SymbolsController.cs

Note that `filename` only has the file name without a path.
While `abs_path` has the complete path to the root which is based on how the image is built:
https://github.com/getsentry/symbol-collector/blob/16facc91ffddce74918f452be19423b3b4fd105f/Dockerfile#L4-L7

Code mapping used:
![image](https://github.com/getsentry/sentry/assets/1633368/7b70647b-5f1d-47bb-b77c-ef42b4b88bea)

On the Mobile app, an example:

![image](https://github.com/getsentry/sentry/assets/1633368/fc890e57-bb8b-4296-9d98-57838ccff000)

```
{
"function": "bool ObjectFileParser.TryElf(string file, out ObjectFileResult result)",
"package": "SymbolCollector.Core, Version=1.13.0.0, Culture=neutral, PublicKeyToken=null",
"filename": "ObjectFileParser.cs",
"abs_path": "/Users/runner/work/symbol-collector/symbol-collector/src/SymbolCollector.Core/ObjectFileParser.cs",
"lineno": 98,
"pre_context": [
"        }",
"        private bool TryElf(string file, out ObjectFileResult? result)",
"        {",
"            var parsed = false;",
"            result = null;"
],
"context_line": "            if (TryParseElfFile(file, out var elf) && elf is {})",
"post_context": [
"            {",
"                result = elf;",
"                parsed = true;",
"            }",
"            else if (_options.UseFallbackObjectFileParser)"
],
"in_app": true,
"data": {
"symbolicator_status": "symbolicated"
},
"instruction_addr": "0x5",
"addr_mode": "rel:1",
"function_id": "0xa6"
},
```

Same situation as the server frame above, `abs_path` has a path to the root (here it's the GitHub Actions built server path).
File is here: https://github.com/getsentry/symbol-collector/blob/16facc91ffddce74918f452be19423b3b4fd105f/src/SymbolCollector.Core/ObjectFileParser.cs#L23

Related to:
* https://github.com/getsentry/sentry/issues/43516

Special handling for some platforms: https://github.com/getsentry/sentry/blob/62ef714de2259a3c574a14b6c65da0a11dfc8053/src/sentry/utils/event_frames.py#L98-L115

**Comment by malwilley** [comment]
I can confirm that the values for `filename` in the csharp platform does not contain enough information for code mapping, so we will need to change our logic to use `abs_path` in some way.

Placing on the backlog.

**Comment by aronbierbaum** [comment]
What is the status of this fix, I'm running into a lot of issues with C# code linking.

**Comment by malwilley** [comment]
@aronbierbaum this particular issue has actually been fixed, so I'm closing.

I responded to the issue you opened, which is something unrelated to this particular problem.
