### ISSUE TITLE
Issues API response doesn't seem to match UI

### ISSUE THREAD

**Issue by yysfwls** [getsentry/sentry#61111]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Description

Why are the API query results different from the page query? Within 24 hours, the api query has a result, but firstSeen and lastSeen are both September, is that right?

![183e099fcd3e907388195fc1125775af](https://github.com/getsentry/sentry/assets/29426633/f882dc1e-9e4c-4b9c-9bf7-97865a60629b)
<img width="897" alt="6ac46bb5f51f7f763cd9c6b3f6729d61" src="https://github.com/getsentry/sentry/assets/29426633/923942c2-ec52-4ddb-8ce0-e56bfa3984d1">

**Comment by yysfwls** [comment]
Anyone see this question?

**Comment by yysfwls** [comment]
> 你好，@yysfwls- 只是澄清一下：您看到的不匹配是 UI 表示您在过去 24 小时内没有出现问题，但当您查询时，结果`count`是 2？如果不是这样，您能具体说明您认为哪些部分不匹配吗？

Yes Yes, there is an error in the interface query, but not in the page query

**Comment by yysfwls** [comment]
> 你好，@yysfwls- 只是澄清一下：您看到的不匹配是 UI 表示您在过去 24 小时内没有出现问题，但当您查询时，结果`count`是 2？如果不是这样，您能具体说明您认为哪些部分不匹配吗？

The query conditions are all the same

**Comment by jangjodi** [comment]
Hi, @yysfwls

The part of the query result that corresponds to 24h stats query is the `[stats][24h]` field. Here you can see that the count is 0 for every timestamp in the last 24h. This is why the Sentry issues page shows no issues in the last 24h.

The `count`, `firstSeen`, and `lastSeen` fields are just information about the issue, not relating to the 24h query. In this case it means that the issue has occurred 2 times in total in September. It does not mean that it has occurred in the last 24h.

**Comment by yysfwls** [comment]
> 你好，@yysfwls
> 
> 查询结果中与24小时统计查询对应的部分是`[stats][24h]`字段。在这里您可以看到过去 24 小时内每个时间戳的计数均为 0。这就是为什么 Sentry 问题页面在过去 24 小时内没有显示任何问题。
> 
> `count`、`firstSeen` 和 `lastSeen` 字段只是有关问题的信息，与 24 小时查询无关。在这种情况下，这意味着该问题在 9 月份总共发生了 2 次。这并不意味着它发生在过去24小时内。

ok got it thank u😬
