### ISSUE TITLE
[Issue Details] Add CTA banner with "set up replay"

### ISSUE THREAD

**Issue by michellewzhang** [getsentry/sentry#61141]
- Contextually aware based on platform of issue project

<img width="711" alt="288134836-f4605aaf-f9f1-4b7c-a3a8-e776c0d01185" src="https://github.com/getsentry/sentry/assets/187460/df3f10d2-e8f1-41fb-abb4-782e32822780">

**Comment by Jesse-Box** [comment]
@michellewzhang @ryan953 @jas-kas here is the last draft of the banner.
Figma link [here](https://www.figma.com/file/9s59JjqUucZBjDimaFccXI/Specs%3A-Banner-Setup-v2?type=design&node-id=1%3A1935&mode=design&t=xu5PipDOXKrutHHK-1)

![Image](https://github.com/getsentry/sentry/assets/6508377/0c56cea5-0629-4060-acb5-7d035c653224)

The design implies the following functionality
- The replay section can be collapsed (Hide Details)
- The banner has a button to trigger the sample replay modal
- The banner has a button to open up the onboarding tray
- The banner header copy roughly matches the SDK name.

Below is an updated Background SVG
![Image](https://github.com/getsentry/sentry/assets/6508377/73341c6a-65f3-4479-8896-64b9f9aefb83)

**Comment by jas-kas** [comment]
@Jesse-Box Awesome, thanks Jesse!
