### ISSUE TITLE
Scrubbed field list is also applied to values

### ISSUE THREAD

**Issue by ThiefMaster** [getsentry/sentry#6114]
https://github.com/getsentry/sentry/blob/master/src/sentry/utils/data_scrubber.py#L133-L134

For example, a log message containing "User authenticated" is scrubbed since "auth" is in `DEFAULT_SCRUBBED_FIELDS` - but looking at the values in that list those should clearly be applied only to (form/request/querystring/whatever) field names, and not to values.

Sentry version: entry 8.21.0.dev0 (sentry.io)

**Comment by dcramer** [comment]
This is intentional, and while it could probably be described more accurately, its unlikely we'd ever want to separate the two concerns.

**Comment by ThiefMaster** [comment]
Then the UI should probably mention this :) It also seems a bit overzealous to strip any string containing the word "auth", especially in breadcrumbs / log messages, which are unlikely to contain sensitive data in the first place.

**Comment by dcramer** [comment]
@ThiefMaster i agree, though the actual use case is something thats not decoded, for example, say you have this:

```{
    "request": <Request password=fizzbuzz>
}```

The ``request`` object isn't getting parsed into a field but is still contains highly sensitive information.

What I'd suggest, is if you have known attributes that are safe, you should be able to add them to the exclusion lists.

**Comment by ThiefMaster** [comment]
What would the "attribute name" be for a log message in a breadcrumb?

**Comment by dcramer** [comment]
Looks like the system keeps them agnostic so you cant filter on the field name.

If it seems reasonable, you could turn off the default filters, and just start an inclusion list of your own (id probably immediately stick password-like strings in there).
