### ISSUE TITLE
Regression Emails race condition with latest group details

### ISSUE THREAD

**Issue by MeredithAnya** [getsentry/sentry#6116]
It's possible that regression emails can end up with the 'older' `title`, `culprit`, `times seen`info because the group hasn't finished updating those details for new events that have come in since it has been resolved.

This can cause confusion over what has caused the regression (before going into sentry to view the event details).

cc @tkaemming

**Comment by MeredithAnya** [comment]
This still happens semi-regularly. It seems to be more likely when the regression is caused after a significant amount of time (a week or more).

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
