### ISSUE TITLE
script loader error

### ISSUE THREAD

**Issue by kongwm** [getsentry/sentry#61237]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. get script loader
2. request js -> http code 302 -> cross error

### Expected Result

script loader success

### Actual Result

![image](https://github.com/getsentry/sentry/assets/17430988/08c5340b-cd4f-43b6-9c08-4ae4d72249a5)

### Product Area

Unknown

**Comment by kerenkhatiwada** [comment]
Hey @kongwm, can you please provide more information on the issue? Currently, it's not clear to me how to reproduce this issue. For example, where is the script loader you are getting located? Also, what do you mean by request js?
