### ISSUE TITLE
Dedupe of Suggested Assignees removes Codeowners

### ISSUE THREAD

**Issue by sdzhong** [getsentry/sentry#61314]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Have a Sentry Issue with Suspect Commit on _userA_
2. Create CODEOWNERS file and configure it in Sentry such that the Sentry Issue also implicates _userA_ due to the CODEOWNERS rule
3. See that the CODEOWNERS match doesn't appear because it's been deduped

### Expected Result

Merge the Suggested Assignee messages for `userA` (`Suspect commit author` + `Owner of codeowners:…`) into one line instead of the current behavior (which removes the `Owner of codeowners:...` line)

### Actual Result

The Suggested Assignee messages for the user gets deduped and evidence of CODEOWNERS rule match is not available; you only see a line for `Suspect commit author`.

### Product Area

Issues

**Comment by lobsterkatie** [comment]
Yeah, that definitely seems like a bug. Thanks for pointing it out! I'll add it to our backlog.

**Comment by snigdhas** [comment]
This is actually working as intended - the suggested assignee implementation works through a hierarchy of ownership, with suspect committers taking precedence over codeowners. If we find a suggested assignee via suspect commits, we don't evaluate any further.
