### ISSUE TITLE
Unable to import GitHub CODEOWNERS file larger than 1MB

### ISSUE THREAD

**Issue by pushlean** [getsentry/sentry#61323]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Ownership Rules in project settings
2. Click "Import CODEOWNERS" button
3. Click "Add file" button

### Expected Result

CODEOWNERS file successfully imported and synced to the project.

### Actual Result

![image](https://github.com/getsentry/sentry/assets/5820138/0dc3cba3-967b-4164-86d2-b2418581f416)
This error message displays after trying to import the file.

Looking at the network traffic, the request to fetch the codeowners file at `https://us.sentry.io/api/0/organizations/dropbox/code-mappings/216746/codeowners/` shows an empty `raw` variable for the contents of the file in the response.

https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content
I was able to reproduce the issue by making a request to GitHub's API at this "get-repository-content" endpoint.
The documentation for the endpoint mentions the content string will be empty by default if the file is greater than 1 MB, which our CODEOWNERS file is.

After following the doc, I was able to fetch the file contents when I added this request header "Accept: application/vnd.github.raw" to override the default media type.

### Product Area

Settings - Projects

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2053) by [Unito](https://www.unito.io)

**Comment by lobsterkatie** [comment]
@NisanthanNanthakumar - How did you handle this case when you were upping the CODEOWNERS size limit?
