### ISSUE TITLE
Crons: Wrap text for long monitor names in timeline view

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#61320]
![Image](https://github.com/getsentry/sentry/assets/1308394/c3348eed-03fa-4313-87d3-5dd29092cc05)

Long monitor names doesn't wrap in Crons' timeline view

**Comment by evanpurkhiser** [comment]
Related to https://github.com/getsentry/sentry/issues/59657

we should solve in a similar manner

**Comment by evanpurkhiser** [comment]
Inadvertently fixed here https://github.com/getsentry/sentry/pull/62023/files#diff-a5297a1ad589af7137c4742d9f7c8a93a4f9f9b94f7dffe430a60d8da366cea7R205
