### ISSUE TITLE
Display Rate Calculations for Metrics in DDM

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#61344]
### Problem Statement

Customer has an assortment of metrics they call "business events", which they've previously tracked as DDRUM.Actions.
- user actions
- async processes (e.g. an async function for http request returning a reponse)
- user flow updates (e.g. an entire user journey beginning, changing, completing. like a status update)

They Problem is that they don't want to see only counts of each one. They want to know the percentage of the time that one happens relative to another. And, they want to Alert on it.

### Use Case
Take the example of a rate for a 'conversion' in the customer's funnel analysis in their eCommerce platform. We'll call it _Conversion Rate_.

metricA - number of shopping carts with products in them
metricB - number of completed Purchases

If you devide metricB / metricA then you get the Conversion Rate. Customer knows this is a constant number. If it suddenly drops to 0% in 10 minutes then they know there may be a problem with their app.

See the below screenshot which demonstrate this Conversion Rate.

### Workaround with Custom Transactions
The customer is recording a Custom Transaction for each business event.
Therefore, we can construct a Dashboard widget to calculate a rate. However this is not a fast out-of-the-box experience, nor can you alert on this Rate, because it is dynamically computed via a dashboard 'equation', therefore it is not an event/issue property for alerting. And it will become very expensive to pay for processing an entire Transaction Event when all they need is the count. They told us the breadcrumbs and tags are not significant to them and they realize "we are retrofitting your Transactions for our business event actions"
[demo dashboard link](https://demo.sentry.io/dashboard/54856/?project=5808623&statsPeriod=7d)
- note - my demo app doesn't reach a OrderComplete page because it errors on every purchase, therefore I'm using Cart-to-Checkout as my Conversion scenario that I'm tracking with a Rate)
- note - in the line-graph widget you have to uncheck the first two count_if's in order to make the y-axis for the equation be 0 to 1.0. PITA, non-obvious, and no way to persist this.
<img width="1379" alt="image" src="https://github.com/getsentry/sentry/assets/8920574/fe3aaa04-3eb1-497d-9c3f-1a4a6c4ab395">

<img width="935" alt="image" src="https://github.com/getsentry/sentry/assets/8920574/648c1946-2773-4039-ba31-d4a1aef30b73">

They don't want to see only counts of each one, but they want to understand how they _trend_ together. Rate's are one way to understand this.

### Solution Brainstorm

The ability to compare Metrics verse each other via rate.

Let's say the user's funnel, or any collection of Metrics which they've recorded, are such:

Metrics
A | B  | C | D

Solution: the ability to see a rate for...
A / B 
B / C
C / D
A / C
A / D
B / A

and so on...so example rates could be like...
A / B = 0.4
B / C = 0.1
C / D = 0.99
A / C = 1.2
A / D = 0.3
B / A = 1.01

Maybe they could select which ones they want in the numerator or denominator.

Lastly they should be able to Alert on something like, "If A/B drops below 0.4, then trigger an Alert"

### Product Area

DDM

**Comment by matejminar** [comment]
This is on our radar. We are working on formulas that would allow that.
No timeline for alerting on formulas yet.
