### ISSUE TITLE
JIRA integration broken - no projects to link

### ISSUE THREAD

**Issue by charlesmims** [getsentry/sentry#6140]
Using sentry.io and atlassian.net managed solutions.

Beginning today, attempts to create a new linked issue resulted in " "Error in JIRA configuration, no projects found for user <omitted>" 
I tried to edit the plugin values, but all fields were grayed out and not editable.  

I reset the plugin and the credentials for this sentry-dedicated user, and verified that I can log in to JIRA with the new credentials and manually create tickets in JIRA through the atlassian.net portal.

In Sentry,
Under Project Settings,
Integrations,
JIRA,
I'm able to specify JIRA Instance URL, Username, and password.
The next dialog asks for Linked Project, but provides no options. Typing in project names within my JIRA, it still says "No matches found".

**Comment by dcramer** [comment]
Will take a look today. I think it's an issue with response encoding not being handled in a specific case. 

https://github.com/getsentry/sentry-plugins/issues/239

**Comment by dcramer** [comment]
Getting some failures on Travis, but will have this deployed to sentry.io in the next couple of hours.
