### ISSUE TITLE
Replay pagination is broken

### ISSUE THREAD

**Issue by IanWoodard** [getsentry/sentry#61418]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Opened up replays
2. Scrolled to the bottom

### Expected Result

Have a second page that I can navigate to by clicking the right arrow in the pagination.

### Actual Result

The right arrow is disabled signaling that there is no second page. However, when I change the sorting by clicking on the activity section, the button becomes clickable and a second page is able to be navigated to.

### Product Area

Replays

### Link

https://sentry.sentry.io/replays/?project=4505800768618496&statsPeriod=7d

**Comment by ryan953** [comment]
Looks like the pagination Links in the api response are coming back with `results="false"` which is unexpected.

Here's an example api call: https://us.sentry.io/api/0/organizations/sentry/replays/?field=activity&field=browser&field=count_dead_clicks&field=count_errors&field=count_rage_clicks&field=duration&field=finished_at&field=id&field=is_archived&field=os&field=project_id&field=started_at&field=user&per_page=50&project=4505800768618496&query=&sort=-started_at&statsPeriod=90d&cursor=0:0:0

It's sorted by `-started_at`, cursor is set for the beginning of the data `0:0:0`, and `per_page=50`.

If we tweak these things the Link header can return the correct thing. Works with any one of these changes:
- `sort=-activity` 
- `per_page=47` (but not 48, 49 or 50)
