### ISSUE TITLE
Event Duration rounding issue on Performance section

### ISSUE THREAD

**Issue by dalton-oliveira** [getsentry/sentry#61425]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Performance
2. Selects any Transaction
3. Check Total Duration values on Sampled Events listing 

### Expected Result

Total Duration to have same decimal fractional as the Event Duration at Event Details 

### Actual Result

Total Duration always has `.00` as decimal fractional

### Product Area

Performance

### DSN

https://f372487ad5a8d2f18b10fc0a9331f6c9@o4506340046077952.ingest.sentry.io/4506340055842816

**Comment by wmak** [comment]
Hey unfortunately the data that powers Performance currently doesn't have that level of precision yet, but as a part of moving more of our data to be powered by span data (eg. the new Query view) we should start showing more precise data.
