### ISSUE TITLE
Issues - Time Range doesn't reflect selected timeframe correctly

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#61420]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

https://github.com/getsentry/sentry/assets/25929053/4ef468dd-458c-478e-93b1-741639c7881f

Added the video to show that the value in the issues stream is still on 1H when first navigating from releases to issues through the new issues number.

### Expected Result

I would the UI to show 1H timeframe which I override through the URL.

### Actual Result

Because my account first had 30days then through the url I set 1H I think the UI gets confused in way that it shows 30days but shows issues from the 1h time range.

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2031) by [Unito](https://www.unito.io)

**Comment by malwilley** [comment]
@Angelodaniel this is expected behavior. When you select the time range through the selector, your changes are saved across pages. However, if you are linked to a specific time range, that is not saved.
