### ISSUE TITLE
Convert issue notifications to use block kit

### ISSUE THREAD

**Issue by ceorourke** [getsentry/sentry#61460]
Convert the `IssueNotificationMessageBuilder` to use block kit (code [here](https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/slack/message_builder/notifications/issues.py)) - note that these are the notifications an individual user receives if an issue alert is set to notify a specific user, and it is different from the notification that goes to a channel in that it does not have any actions (buttons).

**Comment by rachrwang** [comment]
Hello!
