### ISSUE TITLE
Batch resolve claims 1000 but only resolves 100

### ISSUE THREAD

**Issue by ryanwilsonperkin** [getsentry/sentry#6148]
`Sentry 8.21.0.dev0`

When using the batch resolve function, it says "Select the first 1,000 issues that match this search query." however when I select it and then click resolve, it only resolves 100 issues. Possibly a typo in specifying 100 vs 1000?

I can provide a screencast if necessary.

Thanks!

**Comment by SimonSchick** [comment]
Same here.

**Comment by SimonSchick** [comment]
In fact it only seems to be deleting 99.

**Comment by MaxBittker** [comment]
closing in favor of #6099
