### ISSUE TITLE
Review Group endpoints to publish or make private

### ISSUE THREAD

**Issue by vartec** [getsentry/sentry#61487]
API endpoints to review:

- [x] GroupActivitiesEndpoint::GET
- [x] GroupAttachmentsEndpoint::GET
- [x] GroupCurrentReleaseEndpoint::GET
- [x] GroupDetailsEndpoint::DELETE
- [x] GroupDetailsEndpoint::GET
- [x] GroupDetailsEndpoint::PUT
- [x] GroupEventDetailsEndpoint::GET
- [x] GroupEventsEndpoint::GET
- [x] GroupExternalIssueDetailsEndpoint::DELETE
- [x] GroupExternalIssuesEndpoint::GET
- [x] GroupFirstLastReleaseEndpoint::GET
- [x] GroupHashesEndpoint::DELETE **private**
- [x] GroupHashesEndpoint::GET **private**
- [x] GroupHashesSplitEndpoint::DELETE **private**
- [x] GroupHashesSplitEndpoint::GET **private**
- [x] GroupHashesSplitEndpoint::PUT **private**
- [x] GroupIntegrationDetailsEndpoint::DELETE
- [x] GroupIntegrationDetailsEndpoint::GET
- [x] GroupIntegrationDetailsEndpoint::POST
- [x] GroupIntegrationDetailsEndpoint::PUT
- [x] GroupIntegrationsEndpoint::GET
- [x] GroupNotesDetailsEndpoint::DELETE **private**
- [x] GroupNotesDetailsEndpoint::PUT **private**
- [x] GroupNotesEndpoint::GET
- [x] GroupNotesEndpoint::POST
- [x] GroupParticipantsEndpoint::GET
- [x] GroupReprocessingEndpoint::POST **private**
- [x] GroupSimilarIssuesEndpoint::GET **private**
- [x] GroupStatsEndpoint::GET
- [x] GroupTagKeyDetailsEndpoint::GET
- [x] GroupTagKeyValuesEndpoint::GET
- [x] GroupTagsEndpoint::GET
- [x] GroupTombstoneDetailsEndpoint::DELETE **private**
- [x] GroupTombstoneEndpoint::GET **private**
- [x] GroupUserReportsEndpoint::GET
- [x] IssueGroupActionEndpoint::GET **private**
- [x] IssueGroupActionEndpoint::POST **private**

Documentation on determining if API should or shouldn't be public and how to publish: https://develop.sentry.dev/api/public/

If an endpoint is determined as a candidate to be published, create an issue and link it in this [placeholder epic](https://github.com/getsentry/sentry/issues/61479) 

Note: scope of **this ticket** is only to either create ticket for publishing, or marking private/experimental.

If endpoint is determined to be kept private or experimental, it should be marked as such with ApiPublishStatus. Example:

https://github.com/getsentry/sentry/blob/dc65f986f481a27b3a13db224b4a096f009e1a48/src/sentry/api/endpoints/user_notification_email.py#L19-L24

This a minimal change, so no point in creating a separate ticket.

**Comment by 17hogeju** [comment]
- [ ] GroupActivitiesEndpoint::GET
- [ ] GroupAttachmentsEndpoint::GET
- [ ] GroupCurrentReleaseEndpoint::GET
- [x] GroupDetailsEndpoint::DELETE
- [x] GroupDetailsEndpoint::GET
- [x] GroupDetailsEndpoint::PUT
- [ ] GroupEventDetailsEndpoint::GET
- [x] GroupEventsEndpoint::GET
- [x] GroupExternalIssueDetailsEndpoint::DELETE
- [x] GroupExternalIssuesEndpoint::GET
- [ ] GroupFirstLastReleaseEndpoint::GET
- [ ] GroupHashesEndpoint::DELETE
- [x] GroupHashesEndpoint::GET
- [ ] GroupHashesSplitEndpoint::DELETE
- [ ] GroupHashesSplitEndpoint::GET
- [ ] GroupHashesSplitEndpoint::PUT
- [ ] GroupIntegrationDetailsEndpoint::DELETE
- [ ] GroupIntegrationDetailsEndpoint::GET
- [ ] GroupIntegrationDetailsEndpoint::POST
- [ ] GroupIntegrationDetailsEndpoint::PUT
- [ ] GroupIntegrationsEndpoint::GET
- [x] GroupNotesDetailsEndpoint::DELETE **private**
- [x] GroupNotesDetailsEndpoint::PUT **private**
- [ ] GroupNotesEndpoint::GET
- [ ] GroupNotesEndpoint::POST
- [x] GroupParticipantsEndpoint::GET
- [x] GroupReprocessingEndpoint::POST **private**
- [ ] GroupSimilarIssuesEndpoint::GET
- [x] GroupStatsEndpoint::GET
- [x] GroupTagKeyDetailsEndpoint::GET
- [x] GroupTagKeyValuesEndpoint::GET
- [ ] GroupTagsEndpoint::GET
- [x] GroupTombstoneDetailsEndpoint::DELETE **private**
- [x] GroupTombstoneEndpoint::GET **private**
- [x] GroupUserReportsEndpoint::GET **private**
- [x] IssueGroupActionEndpoint::GET **private**
- [x] IssueGroupActionEndpoint::POST **private**

@vartec I was able to review the following endpoints. The rest I am unsure about.
