### ISSUE TITLE
Need custom sum column for dashboard table which will count session start rather end

### ISSUE THREAD

**Issue by saivivek1987** [getsentry/sentry#61512]
### Problem Statement

In dashboard under section Releases(Session, crash rates) we have different fields such as crash_free_rate(), sum()...Now sum() calculates only after end of session closed. Assuming its being calculated after sentry_close() is called in sentry-native. Something on similar lines looking start_sum() something like that which should be triggered the moment sentry_init event happens. Issue is we want metrics dashboard which tell like how many sessions started rather than end.
Also to add will need new crash_free_rate() function which will calculate with this new custom_sum...i.e custom_crash_rate = (crashes/custom_sum)*100  or custom_crash_free = (1 - (crashes/custom_sum)) * 100

### Solution Brainstorm

Can you add custom column to table that can capture session start. Hoping you will have data to capture that. DOnt want to disturb sum() functionality that also needed just need another column which captures session start. Something begins at sentry_init(options) call.
![Screenshot 2023-12-11 at 8 58 38 AM](https://github.com/getsentry/sentry/assets/51218020/005b6d23-8dc5-4d3c-bc1e-ba7f7b470031)

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2032) by [Unito](https://www.unito.io)

**Comment by rachrwang** [comment]
@Dhrumil-Sentry - do you mind taking a look at this one?

**Comment by Dhrumil-Sentry** [comment]
I'll let the dashboard team chime in too, but I don't think we have this data today and at the least is not available in Dashboards

@saivivek1987 can you please tell us why tracking how many sessions started is important to your workflow?

**Comment by nanoburd** [comment]
@Dhrumil-Sentry the dashboard team can only display data that's avaialble.

**Comment by ale-cota** [comment]
Hi @saivivek1987, 

Just checking in to see if this is still an issue. This type of metric is not available, so we have no way to display this in dashboards.
Can you please tell us why tracking how many sessions started is important to your workflow?

**Comment by saivivek1987** [comment]
We can close the issue. We wanted to track how many current active session ongoing because current session goes for longer time. But session count is getting ticked only when we call sentry_close. So wanted to track that. But its fine not a hard requirement for now so we can close this issue.

**Comment by ale-cota** [comment]
Great, thanks a lot for the quick response!
