### ISSUE TITLE
Permission denied to create extension "citext"

### ISSUE THREAD

**Issue by maxiko** [getsentry/sentry#6153]
I've upgraded to latest sentry 8.20 via pip. During upgrage I've catch an error:
 > sentry:0345_add_citext
>FATAL ERROR - The following SQL query failed: CREATE EXTENSION IF NOT EXISTS citext
>The error was: permission denied to create extension "citext"
>HINT:  Must be superuser to create this extension.
 
I tried to create an extension by myself, but no luck.

**Comment by mattrobenolt** [comment]
We’re you able to run it manually as a superuser?

**Comment by maxiko** [comment]
I create extension manually, restart upgrade and still get this error

**Comment by mattrobenolt** [comment]
What happens if you do:

```
$ sentry django migrate sentry 0344
$ sentry django migrate --fake sentry 0345
$ sentry upgrade
```

This should be safe to do if you’ve actually created the extension manually.

**Comment by DuncanFairley** [comment]
Can things like this please be mentioned in patch/upgrade notes? It failed for me as well and my sentry installation is as vanilla as they come.
