### ISSUE TITLE
Sourcemaps uploaded with Debug ID's are not being applied to events

### ISSUE THREAD

**Issue by masinette** [getsentry/sentry#61559]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Sourcemaps w/ debug id's are being uploaded via Sentry CLI
2. Corresponding Artifacts are uploaded (also including Debug ID's)

### Expected Result

The debug ID's match and are applied to the event

### Actual Result

There is no debug_meta on the event. The debug id is in the stacktrace, and the corresponding artifacts are uploaded, but they are not being applied to the event

### Product Area

Issues - Source Maps

### Version

" @Sentry /electron": "4.13.0", " @Sentry /react": "7.73.0", " @Sentry /cli": "2.21.2"

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2034) by [Unito](https://www.unito.io)

**Comment by lforst** [comment]
Ideally we get reproduction here because I can't figure out how this seems to happen nor can I reproduce myself.

**Comment by wlyu2001** [comment]
Hi @lforst, you don't need to reproduce it yourself, you can simply see the symptom here:

Here is an event where you can see `debugId` in the stack trace:

https://bending-spoons.sentry.io/issues/4723380359/?project=6370840&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h&stream_index=0

And here is the corresponding event json, where there is no `debug_meta`

https://bending-spoons.sentry.io/api/0/projects/bending-spoons/en-ion/events/961d8caf59a94e08a28d557f5adbe3f9/json/

**Comment by lforst** [comment]
@wlyu2001 Unfortunately I do need to reproduce this so I can fix the bug (if there is one).

**Comment by wlyu2001** [comment]
Hi @lforst, you mean this could be how the system works normally? I was told by the technical support otherwise. :)

Let me know how I can help you to reproduce it. 🙏

**Comment by lforst** [comment]
> you mean this could be how the system works normally? 

Generally no. Things should work.

> Let me know how I can help you to reproduce it. 🙏

Ideally you create a very small app with all the relevant build steps in order to replicate the behaviour you're seeing in your app and Sentry instance. Thanks!

**Comment by wlyu2001** [comment]
@lforst The situation as I understand is:

- We have some js code in production, it has debugId (**this means our CI processed the code correctly and uploaded the right bundle to production.**)
- Somewhere it crashes, and sentry sdk caught the crash. (**this means our sentry integration is correct.**)
- Sentry sdk send the event json to the server, but missing debub_meta. (**This part is where the problem lies, and we have no influence over this part.**)
- We can see the event in the console, but without source mapping.

 Is there something wrong with this understanding?

**Comment by lforst** [comment]
The process you describe seems pretty standard. This is why a simple reproduction app would be needed to find out where stuff is buggy.

> This part is where the problem lies, and we have no influence over this part
You _do_ have influence over this part. You choose what is sent to Sentry - either via SDK configuration or via additional code.

> We can see the event in the console, but without source mapping, as a consequence of missing debub_meta.
If you are referring to the browser console here, debug IDs will have no effect on browser dev tools source maps.

**Comment by wlyu2001** [comment]
> a simple reproduction app would be needed to find out where stuff is buggy.

Our project setup includes complex CI. I don't see a simple app can be much help here. What I am trying to do is to isolate the problem, e.g. the problem couldn't be at this part, because we can see the outcome of this part being correct.

> You do have influence over this part. You choose what is sent to Sentry - either via SDK configuration or via additional code.

What could we have done here to make the SDK not sending debug_meta? 

> If you are referring to the browser console here, debug IDs will have no effect on browser dev tools source maps. (yet at least)

I meant the Sentry console where you see the event :)

**Comment by lforst** [comment]
> I don't see a simple app can be much help here.

Unless we can replicate this issue it is almost infeasible for us to fix. A simple app that does so is the easiest path towards a fix. Unless we have this we are stuck here.

> What could we have done here to make the SDK not sending debug_meta?

Messing with JS stack traces. Having SDK versions in the bundle that are too old. Accidentally removing the debug_meta field off the event somehow. Rewriting the stack traces on the event somehow. There are a million things that can go wrong, which (to mention again) is why we need reproduction.

I get that "we need reproduction" from the perspective of a customer is annoying and I also don't want to necessarily have to fix a bug. However, sourcemaps are inherently very complex and I can't look at your code so we need to work together here.

**Comment by wlyu2001** [comment]
I can send you all Sentry related code later. The version of the SDK is already mentioned in the issue. I guess with these information, you can try reproduce it on your side?

**Comment by wlyu2001** [comment]
Noted. I will get back to you next week. 🙏

**Comment by wlyu2001** [comment]
@lforst I sent you an email with some code sample. Let me know when you need more info. 🙏

**Comment by lforst** [comment]
@wlyu2001 Thank you! I looked at your code and don't see anything wrong. Honestly, I am running out of ideas about what might be going wrong. When I throw manual events (with the browser console) on your website they are getting debug IDs applied. I can only assume that there is a race condition of some sort, even though it wouldn't make much sense considering that the debug ID injection snippets are in every case all the way at the top of the file.

The only thing left for me to suggest (and this sucks, I know), is for you to look at our code and make assumptions, based on your implementations and setup, why it may fail.

The location where we are reading debug IDs off the page is here:
https://github.com/getsentry/sentry-javascript/blob/89ca41db586fcd8e36a1c6b2f9d298fe8f051e4e/packages/core/src/utils/prepareEvent.ts#L169 called from here: https://github.com/getsentry/sentry-javascript/blob/89ca41db586fcd8e36a1c6b2f9d298fe8f051e4e/packages/core/src/utils/prepareEvent.ts#L64-L67

It's possible that there are issues when web workers are involved...

**Comment by wlyu2001** [comment]
@lforst Thanks for the answer.

If debugID doesn't work in our case, do you think we can fall back to using the legacy approach with matching paths?

The abs_path property of that event is https://web.desktop.evernote.com/builds/next_20240112135804/en-conduit-web-worker.09d39df7c7e3293ac9b5.js, containing dynamic part, so I assume we can use RewriteFrames described [here](https://docs.sentry.io/platforms/javascript/configuration/integrations/rewriteframes/?
original_referrer=https%3A%2F%2Fwww.google.com%2F)?

Thanks!

**Comment by wlyu2001** [comment]
@lforst  Cool! I will give rewriteFrames a try. There isn't much documentation about iteratee, maybe you can help us.

[Here](https://bending-spoons.sentry.io/issues/4880692533/?environment=production&project=6370840&referrer=issue-stream&statsPeriod=30d&stream_index=3) is the event.

The artifact is [here](https://bending-spoons.sentry.io/settings/projects/en-ion/source-maps/artifact-bundles/96a2df3c-9b7d-5df7-953a-6ef28aa7de22/?query=en-conduit-web-worker).

I guess it's just mapping
`/builds/next_20240116183719/en-conduit-web-worker.e62722fb635774d1c0be.js`

to
`~/en-conduit-web-worker.e62722fb635774d1c0be.js`

In the event json, we have

`"abs_path":"https://web.desktop.evernote.com/builds/next_20240116183719/en-conduit-web-worker.e62722fb635774d1c0be.js"`

Both `next_20240116183719` and `e62722fb635774d1c0be` are dynamic.

Could you show us how rewriteFrame's iteratee should be? 🙏 🙏 🙏

**Comment by lforst** [comment]
@wlyu2001 It should be something along the lines of

```ts
Sentry.init({
  integrations: [
    Sentry.rewriteFramesIntegration({
      iteratee(frame) {
        return {
          ...frame,
          filename: frame.filename?.replace(/^https:\/\/yourDomainOrAnyOtherMatchingMechanism\.com\/builds\/next_\d*\//, 'app:///'),
        };
      },
    }),
  ],
});
```

You could also use `new URL` to parse the filename in some way but that would require polyfilling to support IE11.

**Comment by wlyu2001** [comment]
@lforst 

I got some typing error in 

`  integrations: [new RewriteFrames()],`

```
Type 'Integration & { name: string; processEvent(originalEvent: Event): Event; } & { setupOnce: (addGlobalEventProcessor?: ((callback: EventProcessor) => void) | undefined, getCurrentHub?: (() => Hub) | undefined) => void; }' is not assignable to type 'Integration'.
  Types of property 'setupOnce' are incompatible.
    Type '((addGlobalEventProcessor: (callback: EventProcessor) => void, getCurrentHub: () => Hub) => void) & ((addGlobalEventProcessor?: ((callback: EventProcessor) => void) | undefined, getCurrentHub?: (() => Hub) | undefined) => void)' is not assignable to type '(addGlobalEventProcessor: (callback: EventProcessor) => void, getCurrentHub: () => Hub) => void'.
      Types of parameters 'addGlobalEventProcessor' and 'addGlobalEventProcessor' are incompatible.
        Types of parameters 'callback' and 'callback' are incompatible.
          Type 'import("/Users/lingyu/evernote/desktop/node_modules/@sentry/integrations/node_modules/@sentry/types/types/eventprocessor").EventProcessor' is not assignable to type 'import("/Users/lingyu/evernote/desktop/node_modules/@sentry/types/types/eventprocessor").EventProcessor'.
            Types of parameters 'event' and 'event' are incompatible.
              Type 'import("/Users/lingyu/evernote/desktop/node_modules/@sentry/types/types/event").Event' is not assignable to type 'import("/Users/lingyu/evernote/desktop/node_modules/@sentry/integrations/node_modules/@sentry/types/types/event").Event'.
                Types of property 'spans' are incompatible.
                  Type 'import("/Users/lingyu/evernote/desktop/node_modules/@sentry/types/types/span").Span[] | undefined' is not assignable to type 'import("/Users/lingyu/evernote/desktop/node_modules/@sentry/integrations/node_modules/@sentry/types/types/span").Span[] | undefined'.
                    Type 'import("/Users/lingyu/evernote/desktop/node_modules/@sentry/types/types/span").Span[]' is not assignable to type 'import("/Users/lingyu/evernote/desktop/node_modules/@sentry/integrations/node_modules/@sentry/types/types/span").Span[]'.
                      Type 'Span' is missing the following properties from type 'Span': attributes, spanContext, end, setAttribute, and 3 more.ts(2322)
```

Here are our library versions
```
    "@sentry/electron": "^4.13.0",
    "@sentry/integrations": "^7.73.0",
    "@sentry/react": "^7.73.0",
    "@sentry/types": "^7.73.0",
```

What could be the problem? 🙏

**Comment by lforst** [comment]
Yes, please use the latest Sentry SDK version and use `Sentry.rewriteFramesIntegration` like I outlined in my comment. Thank you! We are deprecating a bunch of things in preparation for the new major version.

**Comment by wlyu2001** [comment]
@lforst  After bumping to 

```
    "@sentry/electron": "^4.17.0",
    "@sentry/react": "^7.92.0",
    "@sentry/types": "^7.92.0",
```

There are several errors with the init function. You can try with the code sample I sent you.

And I still can't find `Sentry.rewriteFramesIntegration`. Is there any documentation about this API change?

**Comment by wlyu2001** [comment]
@lforst Hi, sorry for the late reply. I bumped sentry sdk to 7.102.1 and still can't find `Sentry.rewriteFramesIntegration`. Where should Sentry be imported from?

I have tried:

import * as Sentry from '@sentry/electron';
import * as Sentry from '@sentry/browser';
import * as Sentry from '@sentry/react';

Could you verify that `Sentry.rewriteFramesIntegration` indeed exist? Thanks!

**Comment by wlyu2001** [comment]
Hi @lforst, I found the integration after sdk bump. 

Question about the iteratee. In our case, the path for the stack frame is 

`app://evernote/boronConduitWorker/834-1e869c8c47b076b434cd.js`

and the file in the release's artifacts is

`~/renderer/boronConduitWorker/834-1e869c8c47b076b434cd.js`

I can use iteratee as follows:

```
      iteratee(frame) {
        return {
          ...frame,
          filename: frame.filename?.replace('app://evernote/boronConduitWorker', '~/renderer/boronConduitWorker'),
        };
      },
```

Is this correct? 🙏

**Comment by lforst** [comment]
If your stackframe is
`app://evernote/boronConduitWorker/834-1e869c8c47b076b434cd.js`, the only thing you need to do for it to match with the artifact `~/renderer/boronConduitWorker/834-1e869c8c47b076b434cd.js` is to transform the stacktrace so that it starts with `app:///` (note the triple slash). `~` is a wildcard for any protocol. Meaning if you match the `app://` part of the stack frame you currently get, by consuming the `~`, you're left with `evernote/boronConduitWorker/834-1e869c8c47b076b434cd.js` which does not match `/renderer/boronConduitWorker/834-1e869c8c47b076b434cd.js` because it is missing a `/`.

**Comment by wlyu2001** [comment]
It's not only the missing /, but the path also need to be transformed from /evernote/ to /renderer/, right?

I think i will use regex instead, to match any prefix with `boronConduitWorker/` in it. I guess since ~ is a wildcard, I can remove it from the path, something like this:

```
          filename: frame.filename?.replace(
            /^.+boronConduitWorker\//,
            '/renderer/boronConduitWorker/'
          ),
```

**Comment by wlyu2001** [comment]
BTW, the only frames we have problem with are those of `boronConduitWorker`, because during deployment we changed the path. So i would keep frames without `boronConduitWorker` untouched.

**Comment by lforst** [comment]
> It's not only the missing /, but the path also need to be transformed from /evernote/ to /renderer/, right?

Correct! Sorry, I missed that!

> BTW, the only frames we have problem with are those of boronConduitWorker, because during deployment we changed the path. So i would keep frames without boronConduitWorker untouched.

Sounds good.

> I can remove it from the path, something like this?

Looks fine! I hope you understand though, that I cannot verify every single change you intend to make. We assume you (and all Sentry users) are capable engineers who will find the right solution for their setup!
