### ISSUE TITLE
Cannot configure Issue Alerts to notify via MS Teams

### ISSUE THREAD

**Issue by masinette** [getsentry/sentry#61555]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Set up MS Teams integration
2. Select "Create Alert" on "Alerts" page
3. Choose "Issues" alert type, and select "Choose Conditions"
4. Try to set MS Teams as an option under the "THEN" filter

### Expected Result

MS Teams should appear as an option to notify on Alerts

### Actual Result

MS Teams is not available to choose for notifications on Issue Alerts.    (It works on Metric Alerts)

### Product Area

Alerts

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2033) by [Unito](https://www.unito.io)

**Comment by jangjodi** [comment]
Hi, [masinette](https://github.com/masinette)

I was unable to reproduce this issue. Could you please provide the name of the org in the ticket on Jira so I can investigate further?

**Comment by masinette** [comment]
@jangjodi added!

**Comment by jangjodi** [comment]
Thank you @masinette! I will add my investigation comments on Jira

**Comment by jcasner** [comment]
Hi @jangjodi! I'd be happy to show this to you live if that would be helpful! We're unable to set MS Teams as a notification target for users or Teams, so our alerts only go to email.

**Comment by scttcper** [comment]
@jcasner are you a microsoft teams tenant? Tenants are not currently able to setup issue alerts.

**Comment by jcasner** [comment]
> @jcasner are you a microsoft teams tenant? Tenants are not currently able to setup issue alerts.

I'm not sure what this means. We're using Microsoft Business Premium licenses through Office 365. @mzbarskybsis might be able to help. 

What I find odd is that I can setup alerts through some approaches, but not others. For example, if I setup an alert on Throughput, then I can choose MS Teams as a notification target. However, I can't do that with Issue Alerts. It seems very odd that notifications to Teams would only be partially supported like this. 

I also find it odd that you'll allow me to link my Sentry identity to Teams, but not set Teams as a notification target for my individual user.

**Comment by scttcper** [comment]
if you go into the integrations configure page it should tell you
![img](https://github.com/getsentry/sentry/assets/1400464/0b9222bb-60e9-4c4d-a2dc-ffc0d1857558)

**Comment by jcasner** [comment]
> if you go into the integrations configure page it should tell you ![img](https://private-user-images.githubusercontent.com/1400464/293086807-0b9222bb-60e9-4c4d-a2dc-ffc0d1857558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM3MDgxODksIm5iZiI6MTcwMzcwNzg4OSwicGF0aCI6Ii8xNDAwNDY0LzI5MzA4NjgwNy0wYjkyMjJiYi02MGU5LTRjNGQtYTJkYy1mZmMwZDE4NTc1NTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMjAxMTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWE3N2E5ZjljN2M2MWUxMzMxZThkYTk3NmY2MzhjZGYyOWMwOTU1NDIxNjdlYWRkZmM2MzY3OTcxZWQ2N2Q5YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.i-n8FIiglx65nSRFqT8kqu0YoO4zgTywT0Vi7LV-MeM)

Can we please get on a call? There's clearly some miscommunication here and a serious lack of documentation on the Sentry side.

**Comment by masinette** [comment]
Hi @jcasner , I reached out to you in our internal ticket.
