### ISSUE TITLE
Increase Ownership Rules character limit beyond the higher limit of 200k characters

### ISSUE THREAD

**Issue by michaelchai-sentry** [getsentry/sentry#61580]
### Problem Statement

One of our Enterprise customers is already on the higher limit of 200k characters for ownership rules. They recently made some changes to have more granular ownership of packages, and the ownership rules size grew to over 300k characters. They were wondering if it would be possible to increase the limit further?

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2035) by [Unito](https://www.unito.io)

**Comment by Dhrumil-Sentry** [comment]
Thanks for the feedback, We've added this to our backlog but we don't have timeline for making this change yet

**Comment by JoshFerge** [comment]
We now have experimental support for up to 750k characters. reach out to folks on the Sentry issues team to have an org be included in this limit as we continue to improve our CODEOWNERS feature. cc @mrduncan
