### ISSUE TITLE
[User Feedback] Bug: Issue widget didn't load

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#61587]
Replay: https://sentry.sentry.io/replays/910553a659d24e508d10c19b3b4e3020/?project=11276&query=&referrer=%2Freplays%2F&statsPeriod=14d&yAxis=count%28%29

At first it looked like this:
<img width="388" alt="image" src="https://github.com/getsentry/sentry/assets/1633368/a2749fff-e903-42d9-bb5d-1852abd2997b">

After reloading it showed correctly:
<img width="415" alt="image" src="https://github.com/getsentry/sentry/assets/1633368/9185a363-881c-45f9-aecc-5b6670874e51">

**Comment by ryan953** [comment]
Same root cause as https://github.com/getsentry/team-replay/issues/321 i think

> This is probably because loading the Issue Tracker info in the sidebar absolutely destroys the network. Each item in the list fires off two requests that line up and block each other.
I'm noticing that none of the assignment, issue-tracker, crash-id, or replay icons are appearing in the visible part of the list.

**Comment by ryan953** [comment]
depends on https://github.com/getsentry/sentry/issues/62594

**Comment by ryan953** [comment]
https://github.com/getsentry/sentry/issues/62594 is closed, issue loading is better now. Create a new ticket with a fresh example if things are broken
