### ISSUE TITLE
Issues around manually adding existing  tag?

### ISSUE THREAD

**Issue by peteruithoven** [getsentry/sentry#61595]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Have some kind of React (Javascript) project with Sentry
2. Manually add `http.status_code` as tag when capturing error: 
``` js
import {  captureException} from "@sentry/react";

captureException(new Error("test"), {
  tags: {
    "http.status_code": '404',
  }
});
```
3. In Sentry, search for `http.status_code:404`

### Expected Result

My errors show up.

### Actual Result

The errors don't show up. They only show up when using the `tags[]` syntax:
`tags[http.status_code]:404`

### Product Area

Issues

### Link

https://metabolic.sentry.io/issues/?project=4506200469405696&query=http.status_code%3A404&referrer=event-tags&statsPeriod=14d&stream_index=0

### DSN

https://90d5edb19719ee1275c82a6249b6e62e@o4506160608509952.ingest.sentry.io/4506200469405696

## Additional info
This is extra problematic because when looking at a specific issue with such a tag and clicking on the tag it will use the `http.status_code:404` syntax and find nothing. 
Example issue: https://metabolic.sentry.io/issues/4719165757/?project=4506200469405696&query=&referrer=issue-stream&statsPeriod=14d&stream_index=0

It seemed like a smart thing to do, to use an existing tag, since then it automatically shows up in the search auto suggest, but maybe this is not supported?

**Comment by jangjodi** [comment]
Hi, @peteruithoven
We do not recommend using reserved key words as tags, and using `tags[<tag>]` to search for the overwritten tag is the expected behavior. Please see our [docs](https://docs.sentry.io/product/reference/search/#explicit-tag-syntax) for more information.

**Comment by peteruithoven** [comment]
Alright, fair. 

It might be good to clarify this a bit more on the following page:
https://docs.sentry.io/platforms/javascript/enriching-events/tags/
Near the following part:
> Some tags are automatically set by Sentry. We strongly recommend against overwriting those tags. Instead, name your tags with your organization's nomenclature.

Maybe link to https://docs.sentry.io/product/reference/search/#explicit-tag-syntax ?
