### ISSUE TITLE
Organization-level Setting to Enable/Disable Project Creation by Members

### ISSUE THREAD

**Issue by leedongwei** [getsentry/sentry#61610]
### Problem Statement

We made some changes to allow users with "member" roles are allowed to create new sentry projects. 

This affects some organizations' access control policies.

### Solution Brainstorm

We'll have a organization-level setting for users with owners/managers roles to disable this.

### Product Area

Settings - Projects

**Comment by amoise-bd** [comment]
Seems like an unfortunately choice to let any member create project when you already had this done by managers, admins, owner, team admin ... 
And where is this defined in https://docs.sentry.io/product/accounts/membership/ ?

**Comment by Dhrumil-Sentry** [comment]
@amoise-bd thanks for your feedback. We've heard two different types of feedback from customers here

- One cohort has a centralized process to manage tools like Sentry and needs controls so that not everyone can take such actions
- Another cohort wants democratized access- and since we don't allow members to create projects they are forced to make everyone an Admin which has its own set of problems

We will update the docs for that- it's in progress already and apologies for that miss cc @leedongwei @sentaur-athena 

We understand that this creates problems for customers such as yours who are in the first cohort and we'll add a toggle to turn this off in the organization settings. We anticipate this will get done in the next few weeks

**Comment by amoise-bd** [comment]
From our opinion it is a totally unfortunately choice to release such a feature without the possibility to have it overwrite at a company level.

Q: Why don't you implement an option to allow users to configure their chosen mapping between "Actions" and "Roles"
- This way one could even give "project creation" permission to billing and why not, remove organization to members.
- And any other parties that need to have a clear structure, control, synchronisation, compliance between their project can give the "create project" role only to manager (for example)


P.S. It will be interesting to see Atlassian implement the option to allow any user create a new jira-project, confluence-page of bitbucket-project ...

**Comment by leedongwei** [comment]
@amoise-bd I'll add a organization-wide setting for this. ETA before Christmas holidays.

**Comment by leedongwei** [comment]
Unfortunately, I didn't get to this task earlier this week. It's implemented in these two PRs but I'll wait till folks return to office before we merge them.

- https://github.com/getsentry/sentry/pull/62277
- https://github.com/getsentry/sentry/pull/62294

**Comment by realkosty** [comment]
We have a major enterprise customer very interested in this in the context of quota management. Their Sentry admin team wants to lock down project creation so everyone has to go through them.

**Comment by Dhrumil-Sentry** [comment]
@realkosty Danny's change is meant to prevent Org members from creating projects- Thats a change we've made for business plans and Danny is building an opt out for those customers.

Does this customer want only owners to be able to create project?

**Comment by realkosty** [comment]
@Dhrumil-Sentry yes, they want only owners (or managers maybe too?) to be able to create projects. They would like to prevent ideally both Members and Team Admins from doing so. But members alone would be better than nothing.

**Comment by dalnoki** [comment]
Hi @Dhrumil-Sentry, a customer is interested in the ETA for this feature, is there any news that I can share with them?

**Comment by Dhrumil-Sentry** [comment]
@leedongwei can you please share more details about an ETA please

**Comment by jboeijenga** [comment]
@leedongwei: any update on this?

**Comment by leedongwei** [comment]
Updating this ticket. https://github.com/getsentry/sentry/pull/62603 and https://github.com/getsentry/sentry/pull/62294 were merged a while ago. We've added the feature into the organization's General Settings page. 

It is limited to organizations on Biz Plan.

![Image](https://github.com/user-attachments/assets/cc0c2e7a-304e-4720-8b4c-aaca5fd30678)
