### ISSUE TITLE
uwsgi behind a reverse proxy which is itself behind ssl terminating reverse proxy redirects to http (instead of https).

### ISSUE THREAD

**Issue by Rotwang** [getsentry/sentry#6161]
Hi,

I'm using sentry `8.20.0` on `kubernetes` on `AWS`. The proxy layout I'm using is as follows:

```
                        +----------------------+
                        |                      |
                        |        k8s pod       |
+------------+          |                      |
|            |          | +-------+ +--------+ |
| Ingress    |          | |       | |        | |
|            |          | | nginx | | sentry | |
| SSL        +----------> | uwsgi | | web    | |
| terminated |          | | proxy | |        | |
| here       |          | |       | +--------+ |
|            |          | +-------+            |
+------------+          |                      |
                        +----------------------+
```

I've tried to configure my nginx uwsgi proxy as stated [here](https://docs.sentry.io/server/performance/#web-server) however I'm getting redirected to http:

```
$ curl -I https://sentry.mycompany.io/
HTTP/1.1 302 FOUND
[...]
Location: http://sentry.mycompany.io/auth/login/
```

`uwsgi_param UWSGI_SCHEME https;` didn't help in my case (found in now closed #429).
I've tried to play around with uwsgi options in the nginx configuration to no avail.

I guess problem I'm facing is that the nginx doesn't terminate ssl (because it already speaks http with upstream) so it doesn't pass some of the options down to sentry.

Reverting back to `http_pass` as described in [here](https://docs.sentry.io/server/nginx/) works as expected and redirects me to https.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
