### ISSUE TITLE
Alignment bug for equations in table column headers

### ISSUE THREAD

**Issue by michaelchai-sentry** [getsentry/sentry#61630]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When you create a table widget in Dashboards, and you choose to use an equation as one of the headers, the text for the equation will be left-aligned whereas all the other text will be right-aligned. This makes it visually confusing and hard to read the table header and value. Example below, for `count() /100`:
<img width="1242" alt="Screenshot 2023-12-12 at 12 54 14 PM" src="https://github.com/getsentry/sentry/assets/98921471/1bfd8c99-a557-48a5-b6e8-7d32c17c50ba">

### Expected Result

Expect all headers to be right-aligned, even for equations

### Actual Result

Equation headers are left-aligned

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2037) by [Unito](https://www.unito.io)

**Comment by 0Calories** [comment]
Hey @michaelchai-sentry , thanks for reporting this. Working on a fix right now, will keep you posted.

**Comment by 0Calories** [comment]
Opened a PR for the fix: https://github.com/getsentry/sentry/pull/61713

**Comment by 0Calories** [comment]
Fix has been merged and deployed
