### ISSUE TITLE
Add User Feedback to more pages in Sentry

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#61659]
### Problem Statement

We should add the User Feedback modal for more pages that our team owns. 

- Stats
- Org Settings- General, Members, Teams, Integrations, Spike Protections
- Projects Tab page
- Integration Details Page- Jira, GitHub

### Product Area

Settings

**Comment by billyvg** [comment]
I don't think we have a GH team mapped as owners to the product areas outlined in the OP. Gonna close this up since it's a year old.
