### ISSUE TITLE
Add support for additional arbitrary String=>Value map in Exception objects

### ISSUE THREAD

**Issue by Qix-** [getsentry/sentry#61669]
### Problem Statement

We have some custom Error types (in our case, in Rust) where we convert to a sentry `Event` type. Everything works great and has a place, except that we have stacked error support (where an error has an optional "caused by" field, which can recurse downward as a sort of linked list).

These errors can have **error-specific context variables** added to them as they are more or less scoped to some increasingly granular part of a larger operation.

Right now we're converting them to `Exception` objects, but `Exception`s don't have any `BTreeMap` (in rust) for arbitrary values to be attached to specific stack traces, as opposed to the event overall.

### Solution Brainstorm

It'd be great to just have a table view between the error type/value lines and the stacktrace in the web UI when additional userdata values are populated on Exception objects.

Then it'd simply be adding an `extra: BTreeMap` field to the Exception class.

### Product Area

APIs

**Comment by jangjodi** [comment]
Thank you for submitting this feature request @Qix-! This does not align with our current initiatives, but I have put it in our backlog

**Comment by mrduncan** [comment]
Closing as this isn't something that is on our current roadmap, [context](https://docs.sentry.io/platforms/rust/enriching-events/context/) is another potential way to achieve this.
