### ISSUE TITLE
Discord Integration Problem

### ISSUE THREAD

**Issue by Alejodevturbo** [getsentry/sentry#61742]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When I install sentry in my discord server, sentry bot was installed but cannot link to sentry and I give this error
<img width="588" alt="image" src="https://github.com/getsentry/sentry/assets/129610701/ca09423b-dcb6-4fd5-b726-42f5a9411954">

### Expected Result

successfull discord integration

### Actual Result

bot was installed but cannot link to sentry

### Product Area

Settings - Integrations

### Link

https://turbotraffic.sentry.io/settings/integrations/discord/

**Comment by 17hogeju** [comment]
Hey @ReneGreen27,

Thanks for bringing this issue to our attention. I've discovered that a recent update introduced a bug affecting the Discord integration installation.

The great news is that we've already tackled the fix, and it's just wrapping up the final checks. You should be all set to install Discord in about an hour or so.

I really apologize for any inconvenience this has caused. Your patience in this is hugely appreciated. If there are any other questions or concerns, or anything else you need, feel free to reach out.

-Julia

**Comment by alejogonza** [comment]
Excellent thanks for the quick response they are the best 👌

**Comment by alejogonza** [comment]
Excellent thanks for the quick response they are the best 👌

**Comment by 17hogeju** [comment]
@Alejodevturbo Fix is out, should work now!
