### ISSUE TITLE
Traceback parts in exception list

### ISSUE THREAD

**Issue by andreif** [getsentry/sentry#6181]
I am getting traceback parts in exception list on sentry.io using Raven 6.1.0 with Django 1.6 and Celery 3.1. Where should I look to make them reported properly?

<img width="482" alt="sentry" src="https://user-images.githubusercontent.com/259691/30774547-9a0485d2-a084-11e7-9e98-2980f3690e61.png">

**Comment by dcramer** [comment]
If i had to guess, you're doing somethiung that is logging an exception line by line

**Comment by andreif** [comment]
I was hoping it's a some known issue. I'll try to dig it then.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
