### ISSUE TITLE
No longer able to expand distributed tracing in event details view

### ISSUE THREAD

**Issue by fribergr** [getsentry/sentry#61833]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Setup two applications, both with performance tracing enabled.
Send one request from application 1 to application 2 with a traced http client (that includes sentry-trace and baggage headers).

### Expected Result

When viewing details of the event in Sentry, we can see http.server and a span under it for http.client to the second application. We expect it to be possible to expand the http.client span to see the trace from application 2.

However, the plus-sign is no longer available (i.e the trace of application 2 can not be expanded in application 1 event details).

### Actual Result

When viewing the details of the event, we still see http.server and http.client, but there is no "plus"-sign for the http.client span, so we cannot expand the trace.
![bild](https://github.com/getsentry/sentry/assets/4725627/702f8156-e8a6-422d-a0ee-d26f8d25ca2c)

Checking "View Full Trace" shows that the trace is connected.
![bild](https://github.com/getsentry/sentry/assets/4725627/b6f9d9e2-217a-460d-8c3c-649c9c608774)

### Product Area

Performance

### Version

23.10.1 (also tested on 23.11.2)

**Comment by Abdkhan14** [comment]
Hey @fribergr thank you for reaching out! I've been working around this area of the product recently. Taking a look.

**Comment by fribergr** [comment]
Hi @Abdkhan14, I upgraded one of my installations to 23.12.0 yesterday and it seems to be fixed there. Unclear if this was an issue with my installations or an actualy error in the previous versions.

**Comment by Abdkhan14** [comment]
Thanks for the headsup @fribergr, I'll be closing this issue for now and reopen it if it's reproducible.
