### ISSUE TITLE
[OpenAI Subprocessor Acknowledgement] Provide the ability to revoke the acknowledgement

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry#61834]
### Problem Statement

Customers must review and accept the OpenAI Sub-processor Acknowledgement AND opt in to the AI Suggested Fix feature using a toggle in Organization settings before any data is sent to OpenAI.

Turning off the feature in Organization Settings is fine for some cases but certain other circumstances may require the users to also revoke the sub-processor acknowledgement.

Examples of why you may wish to revoke the acknowledgement:
- your role in Sentry gave you the ability to accept the acknowledgement, but you lacked the correct level for such a decision in your company
- you accidentally accepted the policy from the review step
- after trialing the feature you decide that your team will not use it and wish to ensure that even if the organization option is accidentally turned on, the feature will not work

### Solution Brainstorm

Give users the option to revoke this acknowledgement from the application.

### Product Area

Settings - General
```[tasklist]
### Tasks
```

**Comment by trillville** [comment]
Hey @souredoutlook - great suggestion, makes sense to me. Should be relatively straightforward to support this :)

**Comment by trillville** [comment]
this toggle is now available in the "legal and compliance" section of our settings page.
