### ISSUE TITLE
Integration not appearing in alert action

### ISSUE THREAD

**Issue by HerrDerb** [getsentry/sentry#61841]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I am trying to use the Microsoft team integration to send alert notification to a certain teams channel.
We are running on the Teams plan, which should includ this feature.

### How are you getting stuck?

I've installed the Microsoft Team integration, which seems to be actived as it should:
![image](https://github.com/getsentry/sentry/assets/7398256/a3fdb1a1-731e-444e-91ee-4c0c75d8216c)
With this state, I would expect the integration to appear as possible action for an alert rule, which it does not:
![image](https://github.com/getsentry/sentry/assets/7398256/22e2bd35-34eb-43c3-9319-ca10d73a3539)

### Where in the product are you?

Alerts

**Comment by ceorourke** [comment]
Hi @HerrDerb it should be there right below where the screenshot cuts off, under "notify integration" it'll say "Send a Microsoft Teams notification". Did you go through the setup completion via the message in MSTeams mentioned in the [docs](https://docs.sentry.io/product/integrations/notification-incidents/msteams/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2F#install)? Can you open a ticket with support so they can look into your organization? I've confirmed it shows up in a test organization we have here.

**Comment by nickittynack** [comment]
We are having this issue too. We cannot get Sentry and Teams connected as a first party integration and are falling back to webhooks. We have followed the step by step options and ensured "Add To Team" is selected.

<img width="957" alt="image" src="https://github.com/getsentry/sentry/assets/1596713/18b206a9-1a76-4c6c-af40-76db331d9294">


![image](https://github.com/getsentry/sentry/assets/1596713/85341114-6a82-4f43-a438-6d9a55ff5ed5)
![image](https://github.com/getsentry/sentry/assets/1596713/79e538db-cd85-47ea-96dc-8ce950c861e5)

**Comment by leedongwei** [comment]
Duplicated by https://github.com/getsentry/sentry/issues/66130. We'll have the team investigate.
