### ISSUE TITLE
Is there a way to get assignee data for a Sentry event via Data Fowarding (Amazon SQS Integration)? 

### ISSUE THREAD

**Issue by kennethtruong** [getsentry/sentry#61871]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I want to get the assignee data (i.e based off codeowner) to pipe into my DWH (which we're using Amazon SQS integration) 

### How are you getting stuck?

I don't see anyway to get that data. (There also isn't a way to build the dashboard to have a chart to show overview of bugs per team) 

### Where in the product are you?

APIs

**Comment by Dhrumil-Sentry** [comment]
@kennethtruong - This would not be supported in the SQS integration. The assignee information exists at the issue(group) level and not at the error event level.

You could use Sentry's Issue Webhooks: https://docs.sentry.io/api/events/retrieve-an-issue/ which does have an issue_id that you can use to correlate the issue back to the error webhook's payload
