### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by magicseth** [getsentry/sentry#61902]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I cannot link my organization with Sentry. My personal account seems to work, but I have tried my organization in github multiple times and it fails to allow me.

### Expected Result

I should be able to connect my github organization. It all looks good on githubs end, but not sentry's

### Actual Result

Sentry does not show me anything configured

### Product Area

Settings - Integrations

**Comment by scefali** [comment]
@magicseth Can you provide more details? Screenshots etc? Is it possible that it's already installed on your organization account on GitHub's side if you go to your installed apps in GitHub?

**Comment by magicseth** [comment]
I had to revoke permission for Century and all of my organizations, and
then go through the integration process again. That triggered it to work.
