### ISSUE TITLE
Metrics Alerts added logical 

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry#61928]
### Problem Statement

I want to create a metric alert based on the number of errors (throughput) but also the number of unique users impacted. 

>  only fire if the overall metric is X but it affects more than 1 user? I.e. overall Number of errors > threshold AND users experiencing errors > some other number?

For context, we get a lot of false positives from users with browser extensions or trying to scrape, which can lead to a big spike in errors but just for 1 user. We'd like to stop alerting on those if possible.

### Solution Brainstorm

Add the ability to combine multiple metrics into 1 metric alert. 

### Product Area

Alerts

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2045) by [Unito](https://www.unito.io)

**Comment by roggenkemper** [comment]
definitely an interesting proposal and something we might consider in the future, but I don't think there are any plans to do this in the near future.

**Comment by mifu67** [comment]
We are unlikely to address this feature request because it doesn’t seem general enough to apply across our user base. Closing it for now, but please leave a thumbs up on the original description and we can reopen the request if it gains some traction.
