### ISSUE TITLE
Inadequate Matching for ChunkLoadError Prefixes in Filter

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry#61944]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

A user recently enabled the "Filter out ChunkLoadError(s)" inbound filter, but unfortunately, the errors reported by the user are not being caught by the filter. Example of the user Error: 
![Screenshot 2023-12-15 at 11 27 15 AM](https://github.com/getsentry/sentry/assets/67604018/c14933c8-838f-47ae-9058-539d5d52218f)

Upon investigation, it was observed that the filter's pattern for matching ChunkLoadError(s) is not comprehensive. It does not match the chunkload pattern proposed: ChunkLoadError: Loading chunk * failed.\n(error: *) .

### Expected Result

The "Filter out ChunkLoadError(s)" inbound filter should accurately capture and handle ChunkLoadError(s) with various prefixes. The filter's pattern should be flexible enough to accommodate different formats of ChunkLoadError(s) while ensuring that legitimate errors are correctly identified and processed. After implementing the proposed solution, the user should no longer experience issues with the ChunkLoadError(s) being missed by the filter.

### Actual Result

Currently, the filter's pattern for matching ChunkLoadError(s) is too specific and does not cover all possible prefixes. As a result, the user reported that the filter was not capturing their errors and consuming their quota. 

### Product Area

Settings - Projects

**Comment by schew2381** [comment]
Hi there, the filter has been updated in the PR above to catch the missing prefix.
