### ISSUE TITLE
Discord Integration Problem -- is not snowflake

### ISSUE THREAD

**Issue by jamincollins** [getsentry/sentry#61965]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Open Organization Settings
2. Select Integrations
3. Select Discord
4. Click **Add Installation**

### Expected Result

The integration is installed.

### Actual Result

New window displayed with the following as contents:
```
{"client_id": ["Value \"\" is not snowflake."]}
```

### Product Area

Settings - Integrations

### Version

23.11.2

**Comment by scefali** [comment]
@jamincollins have you seen this? https://www.reddit.com/r/Discord_Bots/comments/rse7v8/client_id_value_is_not_snowflake/

**Comment by jamincollins** [comment]
> @jamincollins have you seen this? https://www.reddit.com/r/Discord_Bots/comments/rse7v8/client_id_value_is_not_snowflake/

I hadn't seen it, no.  But how would I make such a change for the Sentry installation of the Discord integration?  There doesn't appear to be any way to set a configuration before trying to add the installation.

**Comment by scefali** [comment]
@jamincollins Ah, that's because you need to make your own: https://develop.sentry.dev/integrations/discord/
