### ISSUE TITLE
Rate limiting exceptions at a project level

### ISSUE THREAD

**Issue by SurenNihalani** [getsentry/sentry#62012]
### Problem Statement

I would like to limit by budget spend per exception. Let's say that I'm interested in only 10 samples per hour and knowing the count of how often the exception occurs. I don't want to spend 180k errors on a single exception where it's not humanly possible to get value out of.

### Solution Brainstorm

Have budgetary limits on a fingerprinted exception

### Product Area

Unknown

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2052) by [Unito](https://www.unito.io)

**Comment by Dhrumil-Sentry** [comment]
@SurenNihalani  Have you considered filtering errors using client or server-side inbound filters?

**Comment by gavrilikhin-d** [comment]
> @SurenNihalani Have you considered filtering errors using client or server-side inbound filters?

While this is possible and fairly easy, it would be nice to have some kind of automatic errors limit per client.
In our case, we have a single user that sends 5000+ events for the same error. Would be nice to prevent such cases

**Comment by brianthi** [comment]
Hi @SurenNihalani, I spoke with a couple product teams about this feature request and this is not a feature we're going to prioritize. I'd suggest following the suggestion provided by @Dhrumil-Sentry for now.

**Comment by SurenNihalani** [comment]
I think we need to keep this open since the workaround doesn't solve this natively

**Comment by SurenNihalani** [comment]
We are currently rate limiting our errors via counting the errors in redis.

**Comment by SurenNihalani** [comment]
@brianthi , can you share why this won't be prioritized? Just want to ensure that I follow through all paths

**Comment by SurenNihalani** [comment]
Where can I see the prioritized issues?

**Comment by rachrwang** [comment]
@SurenNihalani - you can see what's being worked on in our public repos, and you can also see future areas of planned investments in these discussions: https://github.com/getsentry/sentry/discussions.
