### ISSUE TITLE
Raw json request bodies

### ISSUE THREAD

**Issue by kg-jcaron** [getsentry/sentry#62085]
### Problem Statement

I have an issue logged in my projects sentry for a post request with invalid json that failed to parse due to a missing quote. Sentry displays the request bodies but strips all the quotes out of it, so it's hard to track down if the json is actually invalid or if it's a bug in the json parsing library we're using.

Currently you can show the request body as "Formatted" which strips the quotes, or "curl" which strips the body entirely and just shows the headers. I would love a raw option that displays the body exactly as it was when it was logged.

### Product Area

Issues

**Comment by scttcper** [comment]
![image](https://github.com/getsentry/sentry/assets/1400464/9b3b69c4-7373-465f-8048-44366731b0fe)

view json might give you the information you're looking for

**Comment by kg-jcaron** [comment]
Thanks, that helped a lot!
