### ISSUE TITLE
Language upgrade breaking grouping

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry#62120]
As reported by @asottile-sentry, upgrading from Python 3.9 to Python 3.10 caused new groups to be made where none should have been. The culprit turns out to be that Python changed timeout errors from appearing as `timeout` to appearing as `TimeoutError`. (Apparently `socket.timeout` and `TimeoutError` are aliases, and which alias is getting used was changed.)

![image](https://github.com/getsentry/sentry/assets/14812505/13c61cea-8347-4c0f-a554-e31385c901ae)

Though this is the only report of this problem we've gotten so far, we should investigate if there are any other known examples, either from Python or anywhere else.

**Comment by armenzg** [comment]
As I mentioned on Slack, I believe this could be improved if we stopped paying attention to `type` and `value` for the in-app algorithm and only considered the frames.

**Comment by lobsterkatie** [comment]
> I believe this could be improved if we stopped paying attention to `type` and `value` for the in-app algorithm and only considered the frames.

When you say "for the in-app alogrithm," do you mean "when grouping based on in-app frames?"

Assuming yes, I feel like that could lead to a lot of over-grouping, since the same code path can throw a number of different errors, and I'd think we'd want to keep those separate. In this case they actually were the same, but they easily might not be.

**Comment by lobsterkatie** [comment]
Closing this, since most folks are likely well past the 3.9 -> 3.10 transition, and we haven't gotten any other reports of similar problems.
