### ISSUE TITLE
Usage Tracking

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#62167]
We need usage tracking in place during the alpha release stage, so the data can be used to inform the pricing proposal.

The information we need at this point is:
- which orgs are sending custom metrics
- which projects/platforms they are sending them from
- number of distinct custom metrics per org (last 28 days)
- avg/max no. of tags per metric (last 28 days)
- volume of submitted metrics per org (per sensible time unit)

Eventually this information needs to be accessible also in Looker ([Data Project Proposal](https://www.notion.so/sentry/Metrics-DDM-Product-Tracking-0824c9d87fce4c15bc95b410df6c2e56))

**Comment by iambriccardo** [comment]
We had a meeting with Ingest and Armin, and we figured out some possible ways of proceeding. Ingest team will take over the implementation on their side. Once that is done, we might want to query that data in `stats`.

**Comment by iambriccardo** [comment]
Work tracked by ingest here -> https://github.com/getsentry/relay/issues/3147

**Comment by iambriccardo** [comment]
We need to figure out how to show this data in admin

**Comment by iambriccardo** [comment]
#67678 is the ticket that will be followed up by @obostjancic
