### ISSUE TITLE
COGS estimations

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#62168]
In order to inform the pricing proposal, we need to provide COGS estimations.

So far, we've identified the following dimensions and need to understand how they impact cost:
- the inherent cost of a metric type (distributions are more expensive than counters)
- volume of metrics (number of submissions)
- number of dimensions attached to a metric (tags)

**Comment by jan-auer** [comment]
A reproducible script to run analysis is now in this repo:
https://github.com/getsentry/ddm-pricing-analysis

I'll discuss findings in the meeting today and then close this task.

**Comment by jan-auer** [comment]
Updated in the [**Pricing Notion Doc**](https://www.notion.so/sentry/Metric-Hour-Pricing-2817cfeb664b47418bc82b397638b75c). Now implementing.
