### ISSUE TITLE
Replay: count_errors greater than 0 shows a Replay with 0 error

### ISSUE THREAD

**Issue by rohitkataria-sentryio** [getsentry/sentry#62237]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

This is happening for a customer Org. Details in Slack. 

### Expected Result

We should only see Replays that have at least 1 error associated and not Replays that have 0 errors in them

### Actual Result

We are seeing a Replay event with 0 Errors in it. 
![Screenshot 2023-12-21 at 2 27 06 PM](https://github.com/getsentry/sentry/assets/66752128/0f57eb6d-042f-44a7-a776-ef166a2ee4f7)

### Product Area

Replays

**Comment by bruno-garcia** [comment]
Thanks for reporting. It'll require looking into it in more detail but @cmanallen mentioned:

> likely a disconnect with the display expression and the filter expression.  i'll review.  theres a PR related to error_ids open right now.  this could possibly be fixed already.  but not sure atm
> either way the root cause is the addition of the new error id fields (for tracking backend errors)

**Comment by bruno-garcia** [comment]
Update from @cmanallen 

> so its actually the opposite.  backend and frontend errors propagated by the post processor are being displayed but the error_ids column is being filtered (in addition to the new error columns).  so a dropped error was attached to the replay causing it to match the count_errors filter and be returned.  but not counted in the display output because we don't want to double count errors (count_errors + count_new_errors would double the error counts for everyone).
two solutions:
wait ~60 days.
or just drop querying against the deprecated error_ids column.
i dont have a preference.  both things will happen eventually.  we can just expedite step 2 (at the expense of missing older errors).
we could add the two error counts together (old and new) but i think thats a less than ideal solution.  you'll double count a lot of errors
