### ISSUE TITLE
isSideLoaded flag uses opposite colors (green/red)

### ISSUE THREAD

**Issue by valeriyo** [getsentry/sentry#62247]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

The `isSideLoaded` flag (from Android) is displayed `false` in RED and `true` in GREEN:

<img width="156" alt="image" src="https://github.com/getsentry/sentry/assets/7052801/372c3262-4be6-42c1-a013-a0ddd33c12e9">

<img width="148" alt="image" src="https://github.com/getsentry/sentry/assets/7052801/4b182cb9-f1a6-49ea-951b-18530bc53863">

which is confusing, because when app is side-loaded that's not good/normal so it should stand out in RED. So, `false` should be GREEN, and `true` should be RED -- the opposite of the current colors.

### Expected Result

`isSideLoaded`:
* `false` should be GREEN
* `true` should be RED

### Actual Result

`isSideLoaded`:
* `false` is RED
* `true` is GREEN

### Product Area

Issues

**Comment by malwilley** [comment]
Thank you for the feedback! I understand the problem, but we also want to to ensure that the UI is consistent. Right now we always display green for true values and red for false values. I think that reversing the colors in certain situations would be a step in the wrong direction.

However, we're currently in the planning stages for a tags cloud redesign, so we may be moving away from the red/green entirely. So this may no longer be an issue in the future. I'll close this ticket for now.
