### ISSUE TITLE
Replay rendering issue when skipping to certain points using timeline

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#62255]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Using the JS react SDK, create a sample app that is scrollable
2. Have a button that appears after you scroll down on the page, and throws an error on click
3. Go to the recorded replay event in Sentry and skip to just before the error is thrown

### Expected Result

The replay shows that we scrolled down to click the button that throws the error.

### Actual Result

The replay does not show that we scrolled down to click the button that throws the replay. Instead, it shows that we clicked somewhere without scrolling down, and then the error was thrown.

Public tracker for getsentry/team-replay#332

### Product Area

Replays

**Comment by billyvg** [comment]
This should be fixed in replay SDK version 8.0.0 and above (should be fixed by https://github.com/rrweb-io/rrweb/pull/1352)
