### ISSUE TITLE
Handle latest data missing in timeseries response

### ISSUE THREAD

**Issue by obostjancic** [getsentry/sentry#62253]
![Image](https://github.com/getsentry/sentry/assets/86684834/5550f9f7-66ec-4428-9faf-f5be30cdb233)

**Comment by obostjancic** [comment]
Will be resolved with #62363

**Comment by matejminar** [comment]
We increased the limits (10x) so the widgets in the screenshot work as expected. In parallel, we are working on an experience for when you hit those increased limits.
