### ISSUE TITLE
Consolidate Slack message builders for workflow notifications

### ISSUE THREAD

**Issue by isabellaenriquez** [getsentry/sentry#62283]
We currently have two message builders we use for Slack workflow notifications.

### [SlackNotificationsMessageBuilder](https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/slack/message_builder/notifications/base.py)
Covers escalations, comments, deploys, nudges, and event processing problem notifications.

### [IssueNotificationMessageBuilder](https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/slack/message_builder/notifications/issues.py)
Covers assignment, unassignment, resolve, unresolve, and regression notifications, as well as issue alerts configured to be sent directly to a certain user.

This builder inherits from `SlackNotificationsMessageBuilder` and uses `SlackIssuesMessageBuilder` (used for issue alerts) to actually build the notification. 

Since both SlackNotificationsMessageBuilder and IssueNotificationMessageBuilder, we should see if we can consolidate the two so SlackNotificationsMessageBuilder is used for all workflow notifications, which would help make the difference between message builder classes clearer and also clean up redundant code.

**Comment by iamrajjoshi** [comment]
closing this, but keeping this in mind for notification platform work
