### ISSUE TITLE
Aggregate Spans shorten Hostnames too much

### ISSUE THREAD

**Issue by jeengbe** [getsentry/sentry#62297]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Sample networks spans with a hostname longer than two segments (e.g. `service-a.internal.company.com`).
2. Go to "Aggregate Spans" on a transaction summary page

### Expected Result

The spans should display the same way they do on an individual transaction's page.

### Actual Result

![image](https://github.com/getsentry/sentry/assets/51749023/bb00f54c-88f3-4d9a-97ea-294e86d4ace5)

vs.

[can't show the actual spans, but image the above with full-length host+pathname]; https://prisjakt-ab.sentry.io/performance/bff:1119e0ae74834dc280fe34dc9f6537dd/?project=4503976714305536&query=http.method%3APOST&statsPeriod=24h&transaction=productPage

### Product Area

Performance

### Link

https://prisjakt-ab.sentry.io/performance/summary/aggregateWaterfall/?http.method=POST&project=4503976714305536&query=http.method%3APOST&statsPeriod=24h&transaction=productPage

**Comment by shruthilayaj** [comment]
Thank you for your feedback! We parametrize the hostnames this way to form meaningful groups when they are aggregated. Aggregating them based on the exact urls or even just the hostname as seen in a single transaction often leads to too many distinct url groups that make the aggregate spans feature less useful (common example: you might end up with a lot of ungrouped subdomains like `company1.example.com`, `company2.example.com` etc). 

That being said, we may be exploring better parametrization of http.client urls to include more of the host and path to make these aggregates more meaningful in the coming months.
