### ISSUE TITLE
Label User Auth Key

### ISSUE THREAD

**Issue by zhiyan114** [getsentry/sentry#62295]
### Problem Statement

Currently, I have multiple auth keys on my accounts and occasionally I'll come by and create a test key. Unfortunately, I won't always remember where each keys will be used, which caused me to delete one of the keys before and broke one of the services.

### Solution Brainstorm

If possible, you could add an option to name the keys and change them later if needed to (or to add names to existing keys that aren't named)

### Product Area

Other

**Comment by snigdhas** [comment]
Thanks for filing - I've added this to our team's backlog for prioritization.

**Comment by leedongwei** [comment]
Seems to be addressed.

![Screenshot 2024-06-30 at 6 31 46 PM](https://github.com/getsentry/sentry/assets/1748388/cb9e4720-b5f2-44c2-9f41-afa6d21ce738)

**Comment by leedongwei** [comment]
Added this extension: https://github.com/getsentry/sentry/issues/73556
