### ISSUE TITLE
Internal error when exporting date

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#62309]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Some users are receiving the message below after trying to export data from Discover. At the moment I an unable to reproduce on two of my organisations.

[Internal issue link](https://sentry.sentry.io/issues/4742527173)

### Expected Result

Data is exported correctly. 

### Actual Result

![Captura de tela de 2023-12-27 08-38-55](https://github.com/getsentry/sentry/assets/64906376/4a2abdcc-ea93-4003-bd6a-ff82365b6c00)

### Product Area

Issues

**Comment by wmak** [comment]
Fix identified in #62347, Thanks for raising this!
