### ISSUE TITLE
Sentry clien for Crystal Language

### ISSUE THREAD

**Issue by ansarizafar** [getsentry/sentry#6232]
Please provide a client for Crystal language http://crystal-lang.org

**Comment by dcramer** [comment]
The API is documented that you can send your own exceptions from unsupported languages:

https://docs.sentry.io/clientdev/ 

We have no plans for first party Crystal support at this time.

**Comment by HazAT** [comment]
There is a community created SDK
https://github.com/Sija/raven.cr
But we don't know in which shape it is.

**Comment by Sija** [comment]
@HazAT It has been documented, tested and running for months with no issues + there are integrations available for 2 of the most popular Crystal frameworks - [Kemal](https://github.com/kemalcr/kemal) & [Amber](https://github.com/amberframework/amber). It's on par with raven-ruby, from which it was initially ported.

**Comment by InstanceOfMichael** [comment]
Been using Sija/raven.cr for 6months now :+1:
