### ISSUE TITLE
Event timestamp accuracy

### ISSUE THREAD

**Issue by Renny49** [getsentry/sentry#62357]
### Problem Statement

Hi, Team Sentry,

We found event timestamp is only accurate to second and millisecond position is filled with zero value, like `2023-12-01T09:52:56+00:00`. How can we fetch the accurate millisecond timestamp?

The timestamp accuracy is important for us to track user detailed behavior.

### Product Area

Discover

**Comment by wmak** [comment]
Unfortunately we don't store the timestamps with that accuracy by default, I'd recommend using the custom performance metrics for your usecase here instead: https://docs.sentry.io/platforms/python/performance/instrumentation/performance-metrics/#custom-metrics
