### ISSUE TITLE
Spend Allocation per release version range

### ISSUE THREAD

**Issue by su-bob** [getsentry/sentry#62372]
### Problem Statement

I want to release a new version, but I've already exhausted the error collection.
I want to make quota for new release version. 

### Solution Brainstorm

I have no idea to how to user can input version range. 

### Product Area

Settings - Spend Allocation

**Comment by masinette** [comment]
Hi @su-bob. Can you write in to[ Support ](https://help.sentry.io/)for help? 
Alternatively, there is a info about changing quotas in our docs, here: https://docs.sentry.io/product/accounts/quotas/#how-to-manage-your-quota.

**Comment by su-bob** [comment]
Hi @masinette 
when I have plan for release the next version of my product, 
can I make old version doesn't run out of all the errors? 
I think the document does not have the feature.

**Comment by Dhrumil-Sentry** [comment]
There is no way to add spend allocation for a release version and we will not be working on this request

As @masinette suggested, I'd suggedt reading through our quota management docs to see other effective strategies to manager your quotas
