### ISSUE TITLE
control spend allocation using crontab.

### ISSUE THREAD

**Issue by su-bob** [getsentry/sentry#62370]
### Problem Statement

The reset of spend allocation capacity does not align with our product's deployment cycle.

### Solution Brainstorm

I would like to a feature users to control spend allocation using crontab. 

### Product Area

Crons

**Comment by Dhrumil-Sentry** [comment]
@su-bob Do you want to control the day on the month on which the spend allocation cycle begins for your org?

**Comment by su-bob** [comment]
I'm allocating all quota to the other project so that I prevent to run out of errors. 
I want to reduce the quota for the other project every day and get only a certain amount every day.

**Comment by Dhrumil-Sentry** [comment]
Spend Allocation is meant to be a tool to help guarantee a min volume of events to your critical projects today and its not meant to be used as ceiling-based quota management too.

We're unlikely to build this
