### ISSUE TITLE
Queries don't show in table but we do see activity in the charts

### ISSUE THREAD

**Issue by gotenxds** [getsentry/sentry#62408]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

View queries in the query window

### How are you getting stuck?

They dont show up in the table but do show up in the charts
![image](https://github.com/getsentry/sentry/assets/3519520/d368dbc9-8b98-408b-907e-02e8f938d544)

### Where in the product are you?

Performance - Queries

### Link

https://panorays.sentry.io/performance/database/?project=4504565220114432&statsPeriod=24h

**Comment by nanoburd** [comment]
@gggritso this is the issue I talked to you about

**Comment by gggritso** [comment]
@gotenxds thanks for raising this! There are two things going wrong at once:

1. The "Queries" feature doesn't support MongoDB queries, sorry! You can read more about eligible span in [the documentation](https://docs.sentry.io/product/performance/queries/)
2. There is a UI bug, in which the charts and the table disagree on how to filter for queries. I will fix this

@ishkebab another request for MongoDB support here, FYI

**Comment by gotenxds** [comment]
Thanks for the response @gggritso I know you dont support mongo yet, which is why I found it odd we have any data there at all, we do have some (not many) services that use postgress so I assumed that it might be that (even though I never configured it to work I taught it might be an automatic instrumentation)
