### ISSUE TITLE
Azure DevOps Integration Problem

### ISSUE THREAD

**Issue by mhsn79** [getsentry/sentry#62426]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Going to 
1. Organization Settings
2. Integrations
3. Azure DevOps

And selecting Add Installation option pops up another browser window, with this URL:
https://app.vssps.visualstudio.com/oauth2/authorize?client_id=&response_type=code&scope=vso.code+vso.graph+vso.serviceendpoint_manage+vso.work_write&state=81b1cbcedf0d55654dc5dcdd1c893d1f4e62f18dd2bdc091c61ca64366d31d2c&redirect_uri=https%3A%2F%2Fsentry.zdpdev.zones.com%2Fextensions%2Fvsts%2Fsetup%2F

AND it shows 400 Error page. 

How to proceed? 

Note that we have self-hosted sentry env. 

### Expected Result

Add Installation page. 

### Actual Result

400 Bad Request Error page. 
<img width="788" alt="image" src="https://github.com/getsentry/sentry/assets/5061955/7f16851e-28ad-45c0-8c86-5e55d5f5de86">

### Product Area

Settings - Integrations

### Version

23.11.2-2ffe51a

**Comment by malwilley** [comment]
@mhsn79 have you followed the steps here before setting up the integration? https://develop.sentry.dev/integrations/azuredevops/

**Comment by GabeVillalobos** [comment]
Unfortunately the team is understaffed and we can’t prioritize this fix, but we’re always open to community contributions.

**Comment by GabeVillalobos** [comment]
This actually looks like a similar problem in our self-hosted repository: https://github.com/getsentry/sentry/issues/70023

We'll track this issue there since we may have a possible fix in the works already.
