### ISSUE TITLE
Store, Browse and Search server LOG files

### ISSUE THREAD

**Issue by scottie** [getsentry/sentry#62528]
### Problem Statement

View, browse and search additional external server log files within the sentry dashboard.
Example: /var/log/app/debug.log or /var/log/apache2 and so on...

This feature is available in all the competition including but not limited to new relic, data dog, paper trail.

### Solution Brainstorm

So to clarify we would like to store our /var/log/apache2 logs and such logs /var/log/app/debug.log within sentry and have the ability to browse / monitor in real time.

### Product Area

Stats

**Comment by scottie** [comment]
Bump :)

**Comment by azaslavsky** [comment]
Are these the logs generated by your self-hosted instance, or logs sent to the running Sentry itself from an SDK?

**Comment by chadwhitacre** [comment]
I dropped a line internally. Logs are indeed a gap in our product line-up, but I don't know that we're going to get to this anytime soon (we're focused on Performance and Metrics right now). I'm not sure if we want this ticket open to track or not. We'll reopen if so.
