### ISSUE TITLE
slack alerts link

### ISSUE THREAD

**Issue by rotemkadoshvia** [getsentry/sentry#62531]
### Problem Statement

the slack alert link is directing to the issue and not to a specific event.
we are using the alerts in order to notify a user feedback is received, all of the user feedbacks has the same Exception type, so its always direct us to the same issue while we would want to see the specific event for the feedback

### Solution Brainstorm

the link should direct to the specific event that triggered the alert

### Product Area

Alerts

**Comment by malwilley** [comment]
Thanks for the feedback! Will close as a duplicate since we have a couple other issues about the same thing, but feel free to chime in there to help get it prioritized: https://github.com/getsentry/sentry/issues/21315, https://github.com/getsentry/sentry/issues/33678
