### ISSUE TITLE
User auth token list shows non-existing `sentrys_` token prefix

### ISSUE THREAD

**Issue by Lms24** [getsentry/sentry#62535]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Click sidebar profile -> "User auth tokens"
2. Create new token (scopes don't matter)
3. Observe new token value starting with the 64-char sequence (no `sentrys_` prefix)
4. Click Done
5. Observe new token in list starts with `sentrys_*********xyz`

### Expected Result

Token in user auth token list does _not_ start with the `sentrys_` prefix as this is only present in the new org auth tokens

![image](https://github.com/getsentry/sentry/assets/8420481/ce1cdd32-68a2-4038-a146-d790e39053fa)

### Actual Result

Token in user auth token list starts with `sentrys_*********xyz`

### Product Area

Settings

**Comment by Lms24** [comment]
cc @szokeasaurusrex

**Comment by szokeasaurusrex** [comment]
Seems to be fixed as of today when I tried
