### ISSUE TITLE
How can I improve the concurrency performance

### ISSUE THREAD

**Issue by XinXianChen** [getsentry/sentry#62602]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

How can I improve the concurrency performance, such as adjusting some configurations, which I deployed through helm

### How are you getting stuck?

When the amount of concurrent data is large, the service will crash

### Where in the product are you?

Unknown

### Version

20.9.3

**Comment by hubertdeng123** [comment]
Looks like you're using helm, which is unsupported here. You may have more luck asking in the third party helm charts repo
