### ISSUE TITLE
Replay count stuck loading when no records returned

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#62617]
From Scrott C:

> the replay count badge seems to get stuck loading when there's zero replays. 

![image](https://github.com/getsentry/sentry/assets/1633368/a87f4608-2584-43ea-9a2b-734bce24f077)

The API response format didn't change so might be related to changes on the frontend.

**Comment by bruno-garcia** [comment]
This PR hides the badge and can be a temp work around: https://github.com/getsentry/sentry/pull/62530

**Comment by onkardeshpande93** [comment]
Hey @ryan953 I had reported this a while ago and written the `return null` sort of patch to avoid the empty badge, and was surprised to see it again today.

So went and checked to see this reverted, 

<img width="1512" alt="Screenshot 2024-01-10 at 11 51 18 AM" src="https://github.com/getsentry/sentry/assets/136301926/ecefe40c-6919-4cd4-90db-2b430863f700">

Data from replays count api was empty, and FE element showed empty badge again.
