### ISSUE TITLE
Create new integration pop up 

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry#62619]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Org Settings 
2. Integrations 
3. Create a new Internal Integration 
4. Adjust one of the permissions 

### Expected Result

> You are going to increase privileges for this integration. Organization members who already had access to the Client Secret may gain extra permissions due to this change. If this is not what you are expecting, consider re-creating the integration.

Expecting this to only show up for existing integrations and not new ones.

### Actual Result

<img width="1531" alt="image" src="https://github.com/getsentry/sentry/assets/86369415/0717f3da-eb76-4799-aa9c-c4596ce6d883">

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
@schew2381 can you please take a look if this related to any of your changes?
