### ISSUE TITLE
Not able to save Organization Settings

### ISSUE THREAD

**Issue by gek0** [getsentry/sentry#6264]
I'm trying to enable "Open Membership" option on Organization Settings.
I'm unable to save settings, getting error `Unable to save your changes. Please ensure all fields are valid and try again.`

Field that is causing this problem is `Short name` with error `A unique ID used to identify this organization.
Invalid value.`
This value is the same since we started using Sentry. Tried changing the input field with something else or even leaving it blank but the same error occurs.

Also is there any variable for "Open membership" option that I can set in config file? Or what table holds this option in the database?

Sentry version - 8.20.0

**Comment by dcramer** [comment]
What value are you using? It’s possible we switched it to a reserved slug and that’s the problem.

**Comment by gek0** [comment]
It's `DreamImpl`, a short version of The organization name. Can't remember if it was auto-generated or I've selected it. Haven't tried changing any organizations settings for a while. But if I remember correctly, it workerd before in previous versions.

**Comment by dcramer** [comment]
That shouldn’t cause any issues. I will take a look when I get a few but if you’re able you could try changing it (maybe lowercase, ensure there’s no spaces or special characters, etc)

**Comment by gek0** [comment]
Ok, it seems to be working with the lowercase version...
Don't know why is that required but I did manage to save the settings and no link is broken since URL-s are case-insensitive anyway.

**Comment by dcramer** [comment]
This was likely triggered when we moved the settings page to our API, which enforces lowercase only. 

I'm a bit torn on if we should just coerce them to lowercase, or just change this to accept mixed case.

**Comment by mattcodez** [comment]
I also had to use lowercase just now, would be nice if the error stated why the value is invalid.

**Comment by TheBoroer** [comment]
I just ran into this issue too! Sentry version 9.0.0.
Would have been nice if the error was more descriptive though.

**Comment by lidashuang** [comment]
![image](https://user-images.githubusercontent.com/612381/46242588-44032880-c3fd-11e8-9fec-0e915b080c47.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
