### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by garinichsan** [getsentry/sentry#62669]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Setup self-hosted sentry
2. Create a GitHub app for integration based on https://develop.sentry.dev/integrations/github/
3. Add installation of the GitHub app in sentry based on https://docs.sentry.io/product/integrations/source-code-mgmt/github/

### Expected Result

The app successfully installed

### Actual Result

Our member can use the SSO, but sentry does not detect the GitHub app installation. When we hit the installation button, it only pops up the GitHub app page in a new window, and there is nothing we can do after that. It should be automatically detected and the status should be successfully installed.

![image](https://github.com/getsentry/sentry/assets/42213809/f44ebd35-1210-4410-aff5-2802df2f07ee)

### Product Area

Settings - Integrations

### Version

23.12.1

**Comment by scefali** [comment]
@garinichsan You might need to uninstall the app on GitHub's side first before trying a fresh install.

**Comment by garinichsan** [comment]
@scefali 
> You might need to uninstall the app on GitHub's side first before trying a fresh install.

We've done that, but that doesn't resolve the issue
![image](https://github.com/getsentry/sentry/assets/42213809/bd327b40-0df5-4226-8780-83e20bcc2c81)

**Comment by scefali** [comment]
@garinichsan I see the install button now, you're telling me if you press that it doesn't work?

**Comment by garinichsan** [comment]
@scefali yes, exactly
here is the recording video
![sentry-github-problem](https://github.com/getsentry/sentry/assets/42213809/aa989832-2a0f-4d25-9d03-da67a39b29b7)

**Comment by scefali** [comment]
@garinichsan I suspect something is messed up in your config as set up [here](https://develop.sentry.dev/integrations/github/). Not sure exactly what...hard to pinpoint what happened but it looks like at some point during installation it is redirecting out of the installation flow.

**Comment by garinichsan** [comment]
>  at some point during installation it is redirecting out of the installation flow.

Thanks for your insight @scefali, the problem has been fixed by unchecking the `Request user authorization (OAuth) during installation` configuration in the GitHub app.
![image](https://github.com/getsentry/sentry/assets/42213809/af88fdc4-8715-4d11-9774-bbf853aa96bf)
