### ISSUE TITLE
[Discover] "Export all" sends empty csv

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#62698]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

**Description:**
When attempting to export a Discover query that includes `dataset=issuePlatform` in the URL, the csv is sent however no data is associated.

**Steps to reproduce:**
1. Navigate to any issue from the issue stream
2. Click "open in discover" button
3.  From Discover page, try to export all

### Expected Result

CSV to have populated data

### Actual Result

Only column headers included in CSV

### Product Area

Discover

**Comment by wmak** [comment]
OK to unblock exports I've opened #62702 which will allow the CSV exports to happen again. But leaving this issue open until we can resolve the alternate problem which is that discover is implicitly allowing dataset selection in the URL and not in product in any clear way

**Comment by wmak** [comment]
Since the csv issue is fixed, closing this to monitor the implicit dataset selection with https://github.com/getsentry/sentry/issues/63212 instead
