### ISSUE TITLE
Bug: Crons "Retrieve Check-Ins for a Monitor" path parameters invalid

### ISSUE THREAD

**Issue by macmoritz** [getsentry/sentry#62717]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

The official API reference of crons (I know, it is in beta) for the endpoint "Retrieve Check-Ins for a Monitor" is not clear.  
There are three (3) parameters for the path required, but there are only to placeholders in the url.  

This also appears in the [openapi json spec](https://github.com/getsentry/sentry-api-schema/blob/main/openapi-derefed.json) (shortened):   
```json
    "/api/0/organizations/{organization_slug}/monitors/{monitor_slug}/checkins/": {
      "get": {
        "operationId": "Retrieve Check-Ins for a Monitor",
        "description": "Retrieve a list of check-ins for a monitor",
        "parameters": [
          {
            "in": "path",
            "name": "organization_slug",
            "schema": {
              "type": "string"
            },
            "description": "The slug of the organization the resource belongs to.",
            "required": true
          },
          {
            "in": "path",
            "name": "monitor_slug",
            "schema": {
              "type": "string"
            },
            "description": "The slug of the monitor.",
            "required": true
          },
          {
            "in": "path",
            "name": "checkin_id",
            "schema": {
              "type": "string",
              "format": "uuid"
            },
            "description": "The ID of the check-in.",
            "required": true
          }
        ],

```

In total view, this is an invalid openapi spec.

### Expected Result

Clear documentation and spec.  
Multiple solutions:  
1. Make the third parameter available in the URL
2. Make the third parameter not required (f.e. query parameter)

### Actual Result

/

### Product Area

APIs

### Version

23.12.1

**Comment by rjo100** [comment]
Thanks for surfacing this! We're cleaning up our docs as we speak, will let you know when this is updated & please let us know if there's any other issues you catch.
