### ISSUE TITLE
native stacktrace icon always apple

### ISSUE THREAD

**Issue by hsitter** [getsentry/sentry#62728]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. submit event with frames that have `"filename":"libc_start_call_main.h"`
2. view event in sentry

### Expected Result

stacktrace icon should be of the "correct" platform

### Actual Result

stacktrace icon is always `apple`

![Screenshot_20240108_100822](https://github.com/getsentry/sentry/assets/809987/303bcfac-1a5f-4d44-8bcd-85fbe8e4c2da)

In my particular case this ignores `event.platform` which surely knows better than the mapping table what platform the event is on :wink:

This happens because of the recent change https://github.com/getsentry/sentry/commit/dd5bd59fa177e9d271558ba6a506875104a2e574 which prefers file ending over any other platform data of the event in `getFramePlatform`, **and** the file mapping table maps `.h` to apple.

https://github.com/getsentry/sentry/blob/3fc84cfc7fe8bc0e20d274930f75159eecab7460/static/app/utils/fileExtension.tsx#L16

From just glancing at this problem I would think that the `.h` mapping needs to be removed because it is used by multiple platforms. Additionally the resolution order for the current platform probably should be shuffled around such that `frame.platform > event.platform > FILE_EXTENSION_TO_PLATFORM > project.platform`. My thinking here is that the SDK should know best what platform a frame is, and `frame.platform` should implicitly default to `event.platform` - if the SDK sets neither then we are back to guessing what platform it might be. With that in mind the original bug probably should be fixed by the SDK setting the correct frame.platform annotations.

### Product Area

Issues

### Link

https://foo-0k.sentry.io/issues/4832159873/

### DSN

https://c4f183f74466469d8c4ba72f26288f4d@o1295146.ingest.sentry.io/4505594311540736

**Comment by malwilley** [comment]
@hsitter thanks for the report! I agree that `.h` shouldn't be classified as apple as it is now. However, there is a reason that we check file extensions before the event platform, which is that we can display more specific icons than the event platform allows. If we see a react file, we can show a React icon instead of a JS icon. And Scala instead of Java, etc.

Will get this fixed soon!
