### ISSUE TITLE
The event frequency condition passes regardless of any other filtering conditions passing.

### ISSUE THREAD

**Issue by rsprabery** [getsentry/sentry#62748]
### Problem Statement

Same as https://github.com/getsentry/sentry/issues/4751

It would be great to have the event_frequency filter work on key=value pairs.

I'd like an alert based on X exceptions in Y interval for exceptions tagged with the same value.

Thanks!

(_EDIT by @lobsterkatie: See [below](https://github.com/getsentry/sentry/issues/62748#issuecomment-1883692526) for the specifics which inspired the original ticket. TL;DR, if X events - regardless of tag value - happen in Y interval, the next event in that interval with the matching tag will trigger the alert, even if it's the only one with the matching value. In other words, the tallying of events ignores the other conditions, which it shouldn't. See also [this comment](https://github.com/getsentry/sentry/issues/783#issuecomment-13419246) asking for the same thing, from back in 2013, when we were first implementing alerts._)

**Comment by lobsterkatie** [comment]
More info, from the ZD ticket behind the original GH issue:

_Question from customer in 2017:_

> Hello,
> 
> We set up an Alert Rule for warning level events but after inspecting our logs it looks like they are not triggering as expected. Note we have both staging and production environments hooked up to the same sentry project with an `environment` tag for each.
> 
> The Rule:
> 
> When all of these conditions are met:
> * An event's tags match environment equals production
> * An event is seen more than 5 times in 1m
> * An event's level is equal to warning
> 
> Take these actions at most once every 30 minutes for an issue:
> Send a notification (for all enabled services)
> 
> It looks like we are still receiving notifications for production even though only 2 events came in for production, but we saw another 3 or more events on staging (those didn't create notifications per the conditions we set above).
> 
> Any help would be appreciated.

_Response from Sentry engineer:_

> My initial reaction is that we've written those conditions in such a way that this is what's happening:
> - 4 events with the level equal to warning get grouped within one minute, all from the staging environment
> - the last event with the level equal to warning gets grouped with the same 4 events, but this one is from your production environment
> - all conditions are technically satisfied based on the literal interpretation of them, seeing as how 5 total events were seen in 1m, and an event in that total matched the tag
> 
> Obviously, you'd prefer the tag condition to act as a filter for the frequency condition.

**Comment by lobsterkatie** [comment]
@rsprabery - Thanks for writing in. I can see how the current behavior is counterintuitive! I'll check in with our PMs to see if this is something we've considered, and update here once I know something.

**Comment by rsprabery** [comment]
Thanks! I think maybe the correct way of doing things is to use a `before_send` action to set the `fingerprint` field to do any grouping prior to sending events to sentry and keep the alerting the same. 

That's working for us now, so happy to close this. I could see situations where you might want group-based pre-filters on interval based alerting, but maybe it's not common.
