### ISSUE TITLE
psycopg2 version specified in requirements.txt doesn't support postgresql 10.0

### ISSUE THREAD

**Issue by Deimos** [getsentry/sentry#6281]
[PostgreSQL 10 was released yesterday](https://www.postgresql.org/about/news/1786/), and currently trying to install Sentry with it will fail, due to psycopg2 being restricted to version 2.6.2, which isn't able to understand the new version-numbering format of "10.0" (with no third part).

[psycopg2 fixed this 3 years ago](https://github.com/psycopg/psycopg2/commit/91eabf5fcbf07a72b8b86f7d7da0d309db1af003), but that patch isn't included in the version that Sentry is using.

**Comment by mattrobenolt** [comment]
We don’t support Postgres 10 yet. And we likely won’t have the capacity to do so until we run it ourselves. I’d highly suggest sticking with 9.x.

**Comment by mattrobenolt** [comment]
Also, fwiw, I think I recall tried upgrading psycopg2 one a while back and it caused tests to fail. So I didn’t investigate further.

**Comment by Sija** [comment]
Any news regarding Postgres 10 support?

**Comment by mrPsycho** [comment]
still waiting)

**Comment by mattrobenolt** [comment]
This has been updated long ago on master, but isn't in any release yet. That'll come with Sentry 9.

**Comment by mrPsycho** [comment]
oh, cool!

**Comment by mrPsycho** [comment]
@mattrobenolt do you now any estimations?
