### ISSUE TITLE
How does Sentry calculate the performance score of a page?

### ISSUE THREAD

**Issue by coderyyx** [getsentry/sentry#62822]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

I would like to understand how Sentry calculates the performance score for each page, as well as the thresholds for each metric. I only found this in the documentation, but it wasn't clear.

![image](https://github.com/getsentry/sentry/assets/19465842/a2159870-747a-468e-a9ab-ba09b0ff620f)

[performance-score](https://docs.sentry.io/product/performance/web-vitals/#performance-score)

### How are you getting stuck?

How does Sentry calculate the performance score of a page? I want to know details.

### Where in the product are you?

Performance

**Comment by edwardgou-sentry** [comment]
Hi, thanks for the feedback! We're actively working on putting out more materials around this particular topic, including updating the docs you linked here to be more transparent. We should have some more content in the next couple of weeks, I'll post back when they're available.

**Comment by edwardgou-sentry** [comment]
Hi, recently released a blog post that discusses how scores are calculated:
https://sentry.engineering/blog/how-we-improved-performance-score-accuracy
