### ISSUE TITLE
In Replays, API details are unnecessarily made overflow scroll always

### ISSUE THREAD

**Issue by Shubhdeep12** [getsentry/sentry#62829]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

overflow property is set to scroll always

### Expected Result

overflow should be auto for general details of API

### Actual Result

![image](https://github.com/getsentry/sentry/assets/43654389/e7058b5b-281c-4299-b13d-2e21c9d81b73)

### Product Area

Replays

**Comment by Shubhdeep12** [comment]
Please confirm, then i'll push a fix for this.
Thanks

**Comment by bruno-garcia** [comment]
This looks like a bug, thanks for raising. What browser are you on? 
Or a link to a Replay if that's OK so we can peek?

**Comment by Shubhdeep12** [comment]
> This looks like a bug, thanks for raising. What browser are you on? Or a link to a Replay if that's OK so we can peek?

Hi @bruno-garcia 
browser is chrome

and here is the link - https://shubhdeep-chhabra.sentry.io/replays/03505e7518b64b709173d0e680368ec1/?environment=development&project=4506541821460480&query=&referrer=%2Freplays%2F&statsPeriod=24h&yAxis=count%28%29 
I hope this helps.

it would be a one-line change both for network and accessibility logs. let me know I'll push the fix.

**Comment by bruno-garcia** [comment]
Thanks for sharing. I can't reproduce. 

Thanks for offering to fix, it! I think we need help from an engineer to confirm that's what's needed, sicne I couldn't repro: @ryan953 is the fix proposed needed?

**Comment by michellewzhang** [comment]
@bruno-garcia ah I know what's happening, I remember adding this part of the code 
Fix is here https://github.com/getsentry/sentry/pull/62945

**Comment by Shubhdeep12** [comment]
Yes this will fix the issue.
