### ISSUE TITLE
Filtering out class proxies from stacktraces (in Java)

### ISSUE THREAD

**Issue by fprochazka** [getsentry/sentry#6283]
Hi,
I'm relatively new to Java, so I'm not sure how this really works, but Spring is using something (CGLIB?) to generate proxies and they're not really that interesting when it comes to stacktraces.

![image](https://user-images.githubusercontent.com/158625/31312664-9a08abee-abc9-11e7-8248-bbe5ca140e07.png)

It would be nice, if Sentry could automatically recognize that the line in stacktrace is from a proxy and mark it as "library code".

**Comment by mattrobenolt** [comment]
So we should be doing that already: https://github.com/getsentry/sentry/blob/master/src/sentry/interfaces/stacktrace.py#L38-L42

Well, not exactly that, but we should be stripping that bit out.

When testing this manually, it seems to do the right thing.

```
>>> _java_enhancer_re.sub(r'\1<auto>', 'foo$$FastClassBySprintCGLIB$$4ed8b6b')
'foo$$FastClassBySprintCGLIB$$<auto>'
```

Are you running a really old Sentry or something?

**Comment by tkaemming** [comment]
> we should be stripping that bit out

For clarification: the nondeterministic bits are stripped out for consideration in the grouping hash generation algorithm, but we still display it as part of the stacktrace in the UI.

**Comment by mattrobenolt** [comment]
Ohhh, TIL. I thought we removed it entirely from the stack itself.

**Comment by fprochazka** [comment]
Actually installed it few days ago based on the current `onpremise` repository in a docker container :)

![image](https://user-images.githubusercontent.com/158625/31363275-a7d0c9a6-ad5d-11e7-82af-fbb86f8d0c79.png)

**Comment by fprochazka** [comment]
I think it's usefull info in the stack - you want to know it was called from a proxy, but it should not be marked as party of my app, since it's generated.

**Comment by bretthoerner** [comment]
Hey @fprochazka, this sounds like a safe/fine change to me. It should probably happen on the SDK (`sentry-java`) side. We could have a list of special cases we check for and exclude from the app frames. In this case I assume frames containing `$$FastClassBySpringCGLIB$$` would be safe to exclude.

Do you mind opening an issue at `sentry-java`? I can try to get to this later this week.

**Comment by fprochazka** [comment]
@bretthoerner you want to not send them to sentry server at all, or just mark them somehow?

**Comment by bretthoerner** [comment]
Ya, I assume you're using the [stacktrace.app.packages](https://docs.sentry.io/clients/java/config/#in-application-stack-frames) config option?

So in the SDK we won't mark frames as "in app" if they match the blacklist of regexes.

**Comment by fprochazka** [comment]
@bretthoerner awesome :+1:

**Comment by bretthoerner** [comment]
Cool, closing in factor of that issue.
