### ISSUE TITLE
Jira Cloud Integration: Assignee, status and comments don't sync

### ISSUE THREAD

**Issue by astein24** [getsentry/sentry#62840]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.21.0

### Steps to Reproduce

1. Configured Jira Cloud in self-hosted Sentry as described in the documentation. Had to allow Jira Cloud IPs https://docs.sentry.io/product/integrations/issue-tracking/jira/
2. Had to allow X-Frame-Options as described in this article https://confluence.atlassian.com/jirakb/unable-to-install-use-the-sentry-on-prem-with-jira-cloud-via-the-atlassian-marketplace-addon-1272283752.html
3. Creating Jira tickets from Sentry issues now works

### Expected Result

Creating a comment, changing the status or assigne of an issue in Jira or Sentry syncs vice-versa.

### Actual Result

Changes made in Sentry or in Jira aren't synced to each other. Creating Jira Issues or linking existing issues works.

**Comment by lobsterkatie** [comment]
With on-prem installations you can turn on any feature you'd like. In your `sentry.conf.py`:

```Python
from sentry.conf.server import SENTRY_FEATURES, SENTRY_OPTIONS

SENTRY_FEATURES["some-feature-name"] = True
SENTRY_FEATURES["some-option-name"] = True
```

(A list of features with their defaults can be found in the `SENTRY_FEATURES` dictionary in `src/sentry/conf/server.py`, and a list of options with their defaults is in `src/sentry/options/defaults.py`.)

In this case, you want the feature called `organizations:integrations-issue-sync`. That said, it should in theory be on by default. Nonetheless, can you try forcing it on, to see if that helps?

**Comment by astein24** [comment]
Hi, feature was already activated by

`SENTRY_FEATURES.update(
    {
        feature: True
        for feature in (
            "organizations:discover",
            "organizations:events",
            "organizations:global-views",
            "organizations:incidents",
            "organizations:integrations-issue-basic",
            "organizations:integrations-issue-sync",
            "organizations:invite-members",
            "organizations:metric-alert-builder-aggregate",
            "organizations:sso-basic",
            "organizations:sso-rippling",
            "organizations:sso-saml2",
            "organizations:performance-view",
            "organizations:advanced-search",
            "organizations:session-replay",
            "organizations:issue-platform",
            "organizations:profiling",
            "organizations:dashboards-mep",
            "organizations:mep-rollout-flag",
            "organizations:dashboards-rh-widget",
            "organizations:metrics-extraction",
            "organizations:transaction-metrics-extraction",
            "projects:custom-inbound-filters",
            "projects:data-forwarding",
            "projects:discard-groups",
            "projects:plugins",
            "projects:rate-limits",
            "projects:servicehooks",
        )`

Activated it additionally nevertheless without success.

Could this be a network related issue? It would surprise me because creating and linking Jira tickets from Sentry work. Only syncing activites, status and assignees won't. I'm out of ideas.

**Comment by ceorourke** [comment]
Since you're running this self-hosted, could you check to see if you have any of the logs or errors from [here](https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/jira/integration.py#L898) and/or [here](https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/jira/integration.py#L952)? And just to be sure, have you toggled on the [sync settings](https://docs.sentry.io/product/integrations/issue-tracking/jira/?original_referrer=https%3A%2F%2Fdocs.sentry.io%2F#issue-sync)?

**Comment by astein24** [comment]
Hi! Sync settings are active. Found following logs

`sentry-self-hosted-worker-1                                        | 10:07:16 [INFO] sentry.integrations.jira: jira.assignee-not-found (integration_id=1 user_id=1 issue_key='TEST-11')`

`sentry-self-hosted-worker-1                                        | 16:18:17 [ERROR] celery.app.trace: Task sentry.tasks.integrations.jira.sync_metadata[b7cae554-2384-470a-b683-a3514df6e8c6] raised unexpected: AssertionError() (data={'hostname': '80a1ae79d6ad', 'id': 'b7cae554-2384-470a-b683-a3514df6e8c6', 'name': 'sentry.tasks.integrations.jira.sync_metadata', 'exc': 'AssertionError()', 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 306, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 115, in reraise\n    raise value\n  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 301, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 160, in override\n    return original_method(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 126, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/base.py", line 163, in wrapped\n    return func(*args, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/tasks/integrations/sync_metadata.py", line 17, in sync_metadata\n    installation = integration.get_installation(None)\n  File "/usr/local/lib/python3.8/site-packages/sentry/models/integrations/integration.py", line 77, in get_installation\n    return get_installation(instance=self, organization_id=organization_id, **kwargs)\n  File "/usr/local/lib/python3.8/site-packages/sentry/models/integrations/utils.py", line 25, in get_installation\n    installation = instance.get_provider().get_installation(\n  File "/usr/local/lib/python3.8/site-packages/sentry/integrations/base.py", line 211, in get_installation\n    assert isinstance(organization_id, int)\nAssertionError\n', 'args': '()', 'kwargs': "{'integration_id': 1}", 'description': 'raised unexpected', 'internal': False})`

Apparently the `access_email_addresses` scope is missing from the descriptor at /extensions/jira/descriptor/

`  
...
    },
    "name": "Sentry",
    "scopes": [
        "read",
        "write",
        "act_as_user"
    ],
    "vendor": {
        "name": "Sentry",
        "url": "https://sentry.io"
    }
}`

Also did some research and to me it seems like this issue is related https://github.com/getsentry/sentry/issues/24171

**Comment by ceorourke** [comment]
Thanks for finding that! I'll put this in our backlog to update the settings.

For whoever grabs this from the backlog, the latest comment on the other issue is what change needs to be made: https://github.com/getsentry/sentry/issues/24171#issuecomment-1001839969

**Comment by astein24** [comment]
Thank you! Do you have any idea how long this will take to be fixed?

**Comment by Dhrumil-Sentry** [comment]
@astein24 we don't have a timeline for the fix yet, We'll keep this issue updated once we know more

**Comment by pezig** [comment]
Hi @astein24! Could you explain in more detail how you added your site to the X-FRAME-OPTIONS as described in step 2 of your reproduction steps? My team and I have been working on this problem for a a few weeks on and off and we found the help article but still haven't been able to modify the atlassian-connect.json file because we can't find it. Your help would be greatly appreciated!

**Comment by GabeVillalobos** [comment]
Unfortunately the team is understaffed and we can’t prioritize this fix, but we’re always open to community contributions.
