### ISSUE TITLE
Apply SQL syntax highlighting to breadcrumbs that contain annotated/filtered text

### ISSUE THREAD

**Issue by 17hogeju** [getsentry/sentry#62843]
![Image](https://github.com/getsentry/sentry/assets/22582037/f98d7021-d447-4dd8-a008-83357d14b06f)

Also need to highlight search terms in these cases.

![Image](https://github.com/getsentry/sentry/assets/22582037/a6d39e51-4352-48b5-a166-8cda100d9b4b)

**Comment by snigdhas** [comment]
Closing this since we've completed the project to add syntax highlighting
