### ISSUE TITLE
publish versionized/tagged openapi schema

### ISSUE THREAD

**Issue by macmoritz** [getsentry/sentry#62854]
### Problem Statement

We have github releases and git tags of software releases. The corresponding openapi schema is mirrored to [getsentry/sentry-api-schema](https://github.com/getsentry/sentry-api-schema/), but this is not versionized or tagged.  

Also created an issue a few days back in [getsentry/sentry-api-schema#48](https://github.com/getsentry/sentry-api-schema/issues/48), but seems it wont be processes. (maybe disable issues or so). The code for publishing this schema is in here anyways.

### Solution Brainstorm

Would be great if we could have releases, which are identical to the sentry repo releases.
I do not see any downsites, because the main branch will still exist and therefor we would not have any breaking changes.
Also I do not think we need to have old versions in this repo, but would be icing on the cake (tbh should be easily doable from a automated task).

### Product Area

APIs

**Comment by leedongwei** [comment]
Thanks for the suggestion. What's the use case on your end for this?

**Comment by macmoritz** [comment]
We, as most companies do, don't update softwares directly after release. But if the sentry release includes breaking changes in the api the spec gets updated directly, but is not versionized/tagged. 
In this case we would have an invalid spec for our sentry installation. With versionized spec it would be easy to use a exact version of the spec.
In fact this affects most users, because noone updates their software instant after a release.

**Comment by leedongwei** [comment]
Gotcha. We have not made breaking changes to [our public APIs](https://docs.sentry.io/api/) (private APIs are treated different), hence the lack of versioning. It's on the cards for us but it's not a top priority at the moment.

**Comment by sentaur-athena** [comment]
Closing this issue since we don't make breaking changes in APIs. If we do we communicate and give notice so you're aware to upgrade.
