### ISSUE TITLE
weekly email punchcards stretched

### ISSUE THREAD

**Issue by MaxBittker** [getsentry/sentry#6289]
at certain resolutions, the middle punchcard month will display as rectangles and not squares.

<img width="657" alt="screenshot 2017-10-06 10 09 30" src="https://user-images.githubusercontent.com/5915546/31352500-d408f2b6-ace3-11e7-87e3-5513b7efc7ad.png">

**Comment by MaxBittker** [comment]
fixed in #6357

**Comment by Chrissy** [comment]
ok this is actually actually fixed now via #6357
