### ISSUE TITLE
Support session replay capture only when user feedback is submitted

### ISSUE THREAD

**Issue by timhwang21** [getsentry/sentry#62909]
### Problem Statement

I would like to NOT automatically sample session replays, but ALWAYS capture session replays when [user feedback](https://docs.sentry.io/platforms/javascript/user-feedback/) is submitted.

### Solution Brainstorm

It seems like the replay data are always collected, but only submitted based on the sampling rules.

If this behavior already exists, it's not clear from the documentation. 

### Product Area

User Feedback

**Comment by timhwang21** [comment]
I am reading https://docs.sentry.io/platforms/javascript/session-replay/understanding-sessions/. Is my understanding correct that I can build this myself by calling `replay.startBuffering()` on app load, and then call `replay.flush()` in the user feedback widget's `onClose()` callback? (Is there any way to tell if the feedback widget was closed due to successful submission vs. just exiting the widget?)

**Comment by billyvg** [comment]
@timhwang21 That's correct, that should work, note that the feedback widget automatically calls `replay.flush()` on submit so you should have a replay provided that replays is already sampling (which will be the case if `replaysOnErrorSampling > 0`)

**Comment by timhwang21** [comment]
Great thanks. Currently my sampling rate is set to zero because I ONLY want replays when a user submits feedback, and the code I posted above works well for this! Happy to close this since I found a solution, though I do think it’d be very helpful if the fact the feedback widget callled flush were better documented 😄
