### ISSUE TITLE
[Flaky CI]: Relay integration test - test_blob_only_attachment

### ISSUE THREAD

**Issue by iker-barriocanal** [getsentry/sentry#62927]
### Flakiness Type

Assertion failure

### Name of Job

backend test

### Name of Test

tests/relay_integration/test_integration.py::SentryRemoteTest::test_blob_only_attachment

### Link to Test Run

https://github.com/getsentry/sentry/actions/runs/7475745006/job/20344551823#step:4:996

**Comment by jjbayer** [comment]
Was already fixed: https://github.com/getsentry/sentry/pull/63011
