### ISSUE TITLE
Enhance color is similar to the default color for line chart

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#62932]
It would be nice to change it to something with a bit more contrast.

![Image](https://github.com/getsentry/sentry/assets/9060071/3af0c931-8c65-4df4-b0f2-5d7f149815ff)

**Comment by Jesse-Box** [comment]
@obostjancic @matejminar see below for my suggestion

What you're seeing are two things
1. The outer-bounds of the enhance frame has a 75% opacity of `surface400`, creating a vignette effect.
2. The enhance frame is `gray500`

<img width="1569" alt="mock-ddm-chart-signifiers-enhance" src="https://github.com/getsentry/sentry/assets/6508377/cc23ee58-7845-4249-b9a0-ca72d152291c">
