### ISSUE TITLE
Inconsistent project name field length between model and API

### ISSUE THREAD

**Issue by deejay1** [getsentry/sentry#6297]
Hi,

When adding a new project via API the limit for the NAME field is 64 characters (https://github.com/getsentry/sentry/blob/master/src/sentry/api/endpoints/team_project_index.py#L32) but the project model creates a 200 char length field (https://github.com/getsentry/sentry/blob/master/src/sentry/models/project.py#L90).

This seems like an inconsistency limiting the project name...

**Comment by dcramer** [comment]
@deejay1 we dont want 200 character names. We might increase it at some point from 64, but whatever the API enforces should be considered correct.
