### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by lctech-daniel-hung** [getsentry/sentry#62992]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

![image](https://github.com/getsentry/sentry/assets/126635042/b65a5404-9792-484d-8c02-f32081e36ec7)
![image](https://github.com/getsentry/sentry/assets/126635042/56648ad7-9f33-470e-8751-3d69a8f09916)
![image](https://github.com/getsentry/sentry/assets/126635042/8c30afea-10bd-4b63-9b18-4bd73bb0bf52)

### Expected Result

I wish to add the repository that I have currently selected. I've granted the necessary permissions, but the configurations still do not display the corresponding repository options.

### Actual Result

I've installed Sentry.io but I still can't select the corresponding repository. Can you tell me why this might be?

### Product Area

Unknown

**Comment by ceorourke** [comment]
Did you have the integration installed before, and somehow attempting to edit the repo permissions uninstalled it? Or have you not yet installed it at all? When you go through the installation flow you'll be able to select the repositories you want to grant access to.

**Comment by cathteng** [comment]
Closing this issue. Feel free to reopen if you're still experiencing this.
