### ISSUE TITLE
[User Feedback] Multi-line preview in the list

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#63070]
The original figma had multi-line previews, i think if we play with `line-height` and `height` and stuff we can get it working.

https://www.figma.com/file/ga57zyLonVCSJIH3kOWLVA/Specs%3A-User-Feedback-v1?node-id=348%3A12825&mode=dev

**Comment by michellewzhang** [comment]
closed by https://github.com/getsentry/sentry/pull/63078
