### ISSUE TITLE
Django project setup references Falcon integration information

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#63079]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a new Django project 
2. the Configure Django SDK docs reference the Falcon integration
![Screenshot 2024-01-11 at 17-51-07 Org2](https://github.com/getsentry/sentry/assets/99350819/efc9c3e0-5fcc-4689-94d3-1977938c4eb2)

### Expected Result

The Django project setup does not include a reference to the Falcon integration information.

### Actual Result

The Django project setup does include a reference to the Falcon integration information.

### Product Area

Projects - Project Creation

### Link

https://org2-w7.sentry.io/projects/todelete-r4/getting-started/?product=performance-monitoring&product=profiling

**Comment by ArthurKnaus** [comment]
@kerenkhatiwada thx for reporting! 🙌 
Fix is on the way 🙂
