### ISSUE TITLE
Loader Script throws error when adding any Integration setting in code config, without it enabled in project settings

### ISSUE THREAD

**Issue by Janus-thg** [getsentry/sentry#63085]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

My org is looking to test Session Replays, to get better insight into our complex issues. We only want to log Errors, not general sessions, or dead/rage clicks, as we have a fairly large userbase, and the 10% default logging rate, will eat our budget/quota within 10-15 minutes.
So what we want to do, is adjust the setup of Session Replays, and push the setup to production, before enabling them in the project settings. 
Unfortunately, adjusting the code config S, throws the error: `You are using new Replay() even though this bundle does not include replay.`. I think it should be possible to adjust the settings of an Integration in the Loader Script, without having the setting enabled, so that you can for a fact, deploy the settings to Production, before enabling the integration in the Projects settings.

Steps to reproduce: 
1. Add an Integration setting to the `Sentry.init()`, such as `replaysSessionSampleRate: 0` or the below code, while Session Replay is disabled in Project settings:
```js
integrations: [
  new Sentry.Replay({
    maskAllText: true,
  }),
],
```
2. Note that Sentry now throws the below error from `Replay.ts`
![image](https://github.com/getsentry/sentry/assets/120378187/c0644548-1768-46bf-8ecc-d4e5af20e640)

### Expected Result

Sentry throws no error, and allows adjustment of settings before enabling Session Replays as an Integration in the Project Settings.
This will also mean that the quote from the [docs](https://docs.sentry.io/platforms/javascript/#install), is slightly more accurate:
> The Loader Script allows you to configure some SDK features from the Sentry UI, without having to redeploy your application.
If we were able to change the settings directly from the Project Settings, this would make sense, but if we can't change the settings, before enabling the Integration, then we have to Deploy with the error active.

### Actual Result

Sentry throws the error `You are using new Replay() even though this bundle does not include replay.` when enabling any setting related to it, without it enabled in the Project Settings:
![image](https://github.com/getsentry/sentry/assets/120378187/97a792f7-a821-4036-94b1-8a9a66487387)
![image](https://github.com/getsentry/sentry/assets/120378187/d0f90edd-9cb7-4ab1-8a18-c2d1877fa9e2)
![image](https://github.com/getsentry/sentry/assets/120378187/c3328374-b72f-4d82-a06f-e6fd32db12da)

### Product Area

Replays

**Comment by bruno-garcia** [comment]
Thanks for raising. @mydea had some ideas of what might be going on here. @mydea could you please elaborate?

**Comment by mydea** [comment]
I think that's a reasonable idea! We'll adjust this to be a warning only 👍
