### ISSUE TITLE
Display samples in a chart

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#63105]
https://github.com/getsentry/sentry/assets/9060071/fa22a4f0-0658-4273-9f0f-b53457724117

We want to achieve a consistent experience. That means displaying samples in a chart (and having hover-highlight binding with the samples table).

Samples that can't be placed on yaxis (counters etc.) can be represented as lines.

**Comment by obostjancic** [comment]
Related PRs 
- #63424 
- #63425
