### ISSUE TITLE
Improved fog of war

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#63106]
Fog of war is a feature that makes the last few data points in a chart look different because those are not yet stabilized because metrics are still being processed, and the interval is still in progress. This is useful for counters and such as the chart usually shows a huge dip on the right side of the chart.

![Image](https://github.com/getsentry/sentry/assets/9060071/a649f204-108d-4d14-bd2c-044f715b1109)

Right now, it only takes a percentage of a chart from the right and makes it transparent.

It should be a bit more smart and based on time.

**Comment by ArthurKnaus** [comment]
Closed with https://github.com/getsentry/sentry/pull/64650
