### ISSUE TITLE
Connection refused when trying to load sentry

### ISSUE THREAD

**Issue by DayoAkinsola3** [getsentry/sentry#63236]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Sign in to my company's sentry organisation
2. Navigated to organisation's issues page
3. Page loads, but the issues table is stuck on a loading spinner
4. Sidebar renders with icons, but no text
5. Same loading issue when navigating to other pages via the sidebar

The bug is fixed temporarily (for around 5 -10 mins) when I clear my cookies.

### Expected Result

The pages finish loading and show content

### Actual Result

The issues table is permanently stuck in a loading state.
Get the following errors in the console:
![Screenshot 2024-01-16 at 12 01 40](https://github.com/getsentry/sentry/assets/107467591/57fb9bee-ad21-4278-bf03-b3e4df8a0e3d)

### Product Area

Issues

**Comment by roggenkemper** [comment]
Could you try signing in on a browser with no adblockers, and if that doesn't work, in incognito mode on a browser without any extensions? To clarify- when you clear cookies, it works, but then stops working after 5-10 minutes?

**Comment by DayoAkinsola3** [comment]
Tried this with no adblocker on chrome and still run into the issue. Worked fine at first in incognito mode, but the issue showed up after a few minutes. Yes, when I clear cookies it works, then stops working after around 5 - 10 minutes.

**Comment by DayoAkinsola3** [comment]
Hey. Not sure if anything changed, but the page loads fine now for me and the rest of my team now. Thank you both for the help
