### ISSUE TITLE
"Something went wrong" in Org UI

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#63233]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

**I'm not able to reproduce at this moment**
A user is trying to see issues and project information but this gives errors without any explanation.

Things checked:
- No use of Addblockers
- Re-assigned roles to user
- Cleared cookies and login in again
- Incognito without any extensions

See Jira for Customer information.

### Expected Result

I would expect this user to see and be able to use the UI correctly

### Actual Result

Console screenshot
![image (15)](https://github.com/getsentry/sentry/assets/25929053/6fa9e71f-66a7-4b5d-862d-b356c7cc1005)

Issues stream screen
<img width="1082" alt="Screenshot 2024-01-16 at 11 56 30" src="https://github.com/getsentry/sentry/assets/25929053/2e419e71-197a-4aa4-bfbf-01eec964c5a0">

Issues screen
<img width="925" alt="Screenshot 2024-01-16 at 11 56 47" src="https://github.com/getsentry/sentry/assets/25929053/d3375358-98a4-4568-bbd5-2d81e7e735ab">

Customer information in Jira

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2070) by [Unito](https://www.unito.io)

**Comment by isabellaenriquez** [comment]
@Angelodaniel I believe this is a JavaScript void 0 error. Could you ask the user to make sure JavaScript is enabled in their browser, and to try clearing the cache and reloading?

**Comment by mrduncan** [comment]
I'm going to close this issue for now given the age, please reopen if you are able to reproduce it.
