### ISSUE TITLE
Event's request body widget not expanding with content

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#63246]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Have a body with multiple objects
2. Try to expand each object

### Expected Result

The widget that shows the body in the UI expands with the its contents

### Actual Result

See video (on Chrome Browser):

https://github.com/getsentry/sentry/assets/64906376/d1da0222-f165-480c-bd8b-5690b4f4ca88

### Product Area

Issues

**Comment by roggenkemper** [comment]
following up to get more information about this bug

**Comment by rodolfoBee** [comment]
Issue is resolved.
