### ISSUE TITLE
Mobile Session Replay: SDK Recording parameters and API

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#63248]
This ticket defines some aspects of recording a mobile app and supporting data/context to send to Sentry:
It serves to track what parameters we will need and to align between iOS and Android.

# Recording parameters and Options

These parameters/options **might not be public**, but we'll use these to control or adjust video quality, size and recording overhead.

Let's not put this into SentryOptions directly, but create a new nested object SessionReplayOptions which contains all of these params. SentryOptions then holds a ref to this nested object (sentryOptions.setSessionReplayOptions(replayOptions)).

## Public options:
* `sessionReplay.sessionSampleRate: float` - sample rate
* `sessionReplay.onErrorSampleRate: float` - If the entire session is not sampled, use the sample rate to sample sessions when an error occurs.
* _`quality: high|medium|low` - for later, predefined quality options that change bitrate, resolution, maybe mimeType under the hood_

### Masking:

We'll redact all text input controls, WebView, labels, images (except when loaded from the bundle), custom controls by default. 

- [ ] Provide a way to pause/resume recording for certain screens (E.g. a PIN-code screen we cannot really redact properly). It should probably be a top-level API of the static class (`Sentry.resumeSessionReplay/Sentry.pauseSessionReplay`)
	- [ ] Let's bring this up with frontend/backend, because there will be gaps between replay segments. Maybe we could add new RREvent types or breadcrumbs indicating the replay was paused/resumed to surface this in the frontend.
- [x] Provide a way to redact views based on their class name. We should do that on SDK init - register a list of classes that you know are sensitive from the beginning. `sessionReplayOptions.addClassForMasking()`, name TBD 
- [x] Provide a way to redact specific view instances. Via an extension property/function on iOS and Kotlin Android, e.g. `sampleView.sentryBlock = true|false`
	- [x] On Android we could also use `view.setTag("sentry-block|unblock")`.
	- [x] In case of Java, extension property wouldn't work so we probably need to call to Sentry static class, maybe let's not do it in the first version

## Internal/Private Recording options:
* `frameRate: float`: Screenshot every N seconds, default is `1`, `0.5` is a valid option
* `bitRate: int`: The quality of the 'video', defaults to `20`.
* ~`mimeType: enum`: h264~ - let's always hardcode it to h264
* ~`height`: Used on Android. The height of the video. Width adjusts proportionally. Default `720`. This might depend on device it runs.~
* `scaling`: Used on iOS and Android. Default 1x that means,for an iPhone 15 Pro, the video is 320x840

**Comment by brustolin** [comment]
Update for iOS:

#Public options
- [x] sessionSampleRate: float
- [x] errorSampleRate: float
- [x] quality: high|medium|low 
- [x] redactAllText
- [x] redactAllImages

# Internal/Private Recording options
- [x] frameRate
- [x] bitRate
- [x] scaling

## and a few extra internal options to change behaviour
- [x] errorReplayDuration = 30s
- [x] sessionSegmentDuration = 5s
- [x] maximumDuration = 1h

**Comment by cmanallen** [comment]
@brustolin @bruno-garcia Closing as completed task.
