### ISSUE TITLE
Allow sub-minute configuration for monitoring

### ISSUE THREAD

**Issue by zhiyan114** [getsentry/sentry#63302]
### Problem Statement

1. For one of my cron jobs, I want it run every 15s or so. While the syntax parser recognizes it, the system restrict the input.
2. Some of the tasks are expected to be completed before 60s, but the grace period or max runtime can only detect tasks that exceeded over a minute.

### Solution Brainstorm

1. Increase the field input to 6 (or even 7 for yearly cron). Although this isn't the standard cron syntax, some libraries, like node-cron supports it.

2. The values in the margins (`Grace Period`/`Max Runtime`) should also allow sub-min values for task that'll execute fairly quickly.

### Product Area

Crons

**Comment by evanpurkhiser** [comment]
Unfortunately, the current system does not support sub-minute crons. We likely will not be adding this in the near future. Sorry!

**Comment by zhiyan114** [comment]
@evanpurkhiser May I know which limitation is preventing this?

Is it because the monitoring system internally uses unix cron, which doesn't have this support or is it because of the large influx of requests if sub-min is enabled?
