### ISSUE TITLE
413 Entity Too Large for Organization Release Artifacts

### ISSUE THREAD

**Issue by kjanoudi** [getsentry/sentry#6331]
## Reporting Bugs

When reporting bugs, include details about your configuration, such as:

- The version of Sentry you're using: Latest version of Raven
- Whether you're using Docker or another installation method: I am using the Raven JS plugin for React
- Include a stacktrace or other logs when relevant: No stacktrace

My issue is detailed here: https://github.com/40thieves/webpack-sentry-plugin/issues/50

When using https://docs.sentry.io/api/releases/post-organization-release-files/ , the request size limit seems to be lower than when using https://docs.sentry.io/api/releases/post-project-release-files/

 I believe this was recently upped to 40mb from 20mb a while back for the latter endpoint. However, the new organization based endpoint seems to return 413s when uploading more than 20mb.

**Comment by mitsuhiko** [comment]
@getsentry/ops This is a misconfiguration on the load balancer for sentry.io

**Comment by JTCunning** [comment]
Hey @kjanoudi, looks like a new artifact upload endpoint exists. We've gone ahead and increased that endpoint's size limit to 40MB.

In the future, please direct your questions about sentry.io to support. This issue tracker is for sentry the codebase, not the hosted SaaS.
