### ISSUE TITLE
API inconsistently returns 404

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#63337]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. send a GET request to [https://sentry.io/api/0/issues/{issue_id}/](https://sentry.io/api/0/issues/%7Bissue_id%7D/) - I tested it with https://sentry.io/api/0/issues/4298020691/
2. repeat the above step a few times
3. a 404 error is returned randomly

### Expected Result

all get requests should return a 200 response with a JSON

### Actual Result

inconsistently a 404 error is returned

### Product Area

APIs

**Comment by markstory** [comment]
This will be resolved later today once #63341 reaches sentry.io
