### ISSUE TITLE
Large gaps of time not being marked as "Missing Span Instrumentation" in waterfall span view

### ISSUE THREAD

**Issue by michaelchai-sentry** [getsentry/sentry#63369]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

A user of ours noted that in their waterfall span view for transactions, they see large gaps of time that are unaccounted for and don't show the "Missing Span Instrumentation" visual. The Sentry team believes that this is still missing instrumentation, but for some reason the frontend doesn't display this. We would love to find out why, and if it is indeed missing instrumentation, display it clearly for the user to take action.
<img width="535" alt="Screenshot 2024-01-17 at 1 38 23 PM" src="https://github.com/getsentry/sentry/assets/98921471/3575673d-5dc9-43d7-bec3-983630da1522">

### Expected Result

Large gaps of unaccounted time should show "Missing Span Instrumentation" visual if that is indeed the case

### Actual Result

No missing instrumentation visuals, as shown in the screenshot above

### Product Area

Performance

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2075) by [Unito](https://www.unito.io)

**Comment by gggritso** [comment]
@michaelchai-sentry thanks for filing this! This looks like a UI bug, I'm taking a look.

**Comment by gggritso** [comment]
This trace view has since been replaced with a brand new one, so this bug is probably not relevant anymore. @michaelchai-sentry let me know if that's not the case!
