### ISSUE TITLE
Using multiple Node SDK api paths causes 403 error conflicts.

### ISSUE THREAD

**Issue by jameszenartist** [getsentry/sentry#63416]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Set all Node fetch api calls as suggested in the Sentry documentation.
2. Set all necessary permissions as suggested in your custom integrations section in your Sentry Account.

### Expected Result

Greetings Everyone,

So currently in my Node app I have a cron job that uses the Node SDK to fetch all my issues data, then extracts all the data I want and writes it to a file.

After it confirms that the data was received, I then make another fetch to bulk remove all the issues/logs...but that's where I'm having trouble.

That path in the docs doesn't seem to be working.

This is the api path I'm referring to: https://docs.sentry.io/api/events/bulk-remove-a-list-of-issues/

The path in which to retrieve a list of all issues: https://docs.sentry.io/api/events/list-a-projects-issues/

is working fine; where I set the permissions to Read as suggested.

The path in which to Bulk remove all Issues is set to Admin, as suggested.

I've tried the path ending with "issues/" and "issues/?id=1&id=2" etc like suggested, but nothing seems to be working. I always end up getting a 403 error. 

All other paths in this api I've used seem to be working fine, except this one.

-James

### Actual Result

I can successfully retrieve a list of all issues/logs in my account, but the Bulk remove path always results in a 403.

For days I've been stumped, but just recently I noticed that if you set all permissions in your custom integration section to Admin, regardless of what the docs say, then all my sentry fetch api calls on my Node Server work just fine?

if your Node server is targeting multiple Sentry api paths, where each path requires a different permission setting, does it not seem to defeat the purpose of setting up all your permissions individually for each api fetch call?

Because sooner or later, something is going to conflict?

-James

### Product Area

APIs

**Comment by nhsiehgit** [comment]
Hey @jameszenartist 

Sounds like you've been able to unstick yourself?

The docs on the bulk delete endpoint seem to call out that an admin scope is needed as well.
If you set all your scopes to admin, then yes that will allow your token free range to perform actions on your behalf.
I would imagine we have the different scopes there as a precaution against any destructive actions (such as delete).

If you're still having issues please feel free to open this ticket back up!

**Comment by jameszenartist** [comment]
Hey @nhsiehgit ,

In a brute force manner, yes you could say so!

Earlier in my cron job, I first use the List all Issues path which requires the permission Event to be set to read.
I'd also like to add that it mentions scopes in the docs, which has nothing to do with this api path.
Once I add the Bulk Remove Issues path, that's where I would get the 403 error.

In this context, I would have to go back and change everything to Admin, despite what the docs say.

My point is that the documentation is inaccurate, misleading and ambiguous.

I recently spoke with Francis Wang @ Sentry, and he said that a ticket would be filed to correct what I've been pointing out.

I understand the need for individual protective permissions but again, if someone has multiple api paths on their Node server, I'd imagine that in the documentation it would be helpful if it mentioned that you would be better off setting everything to Admin. Otherwise if you set each permission individually according to the api path used; you'll get conflicts like I was getting.

In addition, I'd also like to point out that when it comes to the previous api paths that I have mentioned; scopes are irrelevant. Only the permissions are in the custom integration section.
