### ISSUE TITLE
Empty Web Vitals Tab for specific environment

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#63433]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

A user has reported that their Web Vitals tab is empty when choosing their production environment, when it didn't use to be like that a day ago.

### Expected Result

If their transactions in that environment have web vital measurements on that environment, the tab should be populated.

### Actual Result

When choosing the production environment specifically the Web Vitals tab is blank:
![1](https://github.com/getsentry/sentry/assets/81985895/a5b649f7-356f-44c1-8421-d9eed19d6cc0)

This is not the case when the other environments or all environments are selected. Upon looking at their discover page, they seem to be receiving some web vital measurements in their transactions for the production environment, so the Web Vitals tab should have been showing information.

More details and links in the shadow ticket. I was unable to reproduce this in another Sentry Organization.

### Product Area

Performance - Web Vitals

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2076) by [Unito](https://www.unito.io)

**Comment by edwardgou-sentry** [comment]
This is likely due to page load events being excluded from performance score calculations due to missing webvitals (ie `LCP` or `CLS`). We're investigating a fix for this. Will update when ready

**Comment by edwardgou-sentry** [comment]
Hi, starting from version [7.96.0](https://github.com/getsentry/sentry-javascript/releases/tag/7.96.0), the latest Sentry Javascript SDK now includes a fix to capture LCP and CLS more often. This will also result in more results and performance scores showing up in the Web Vitals module. Customers should update to the latest version of their SDK to receive the fix.
