### ISSUE TITLE
Bulk Remove a List of Issues doc page lists wrong auth token scope

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#63468]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

The doc page for [Bulk Remove a List of Issues](https://docs.sentry.io/api/events/bulk-remove-a-list-of-issues/) lists the required auth token scope of `project:admin` but that does not work for this endpoint.  The correct scope is `event:admin` created from setting the Issues & Event option to Admin.

**Token with project:admin scope** -
<img width="308" alt="Screenshot 2024-01-18 at 3 20 49 PM" src="https://github.com/getsentry/sentry/assets/96670625/b9ae55dc-8684-48f3-8e04-50afa4c3a991">

**Returns 403** - 

<img width="795" alt="Screenshot 2024-01-18 at 3 22 18 PM" src="https://github.com/getsentry/sentry/assets/96670625/fadb624b-37c5-4510-b7ef-f4a260c7ac5d">

**Comment by isabellaenriquez** [comment]
Thanks for catching this! We'll definitely make sure to update the documentation.

**Comment by jameszenartist** [comment]
@Fwang36 

Again, Francis thank you so much for taking the time to listen to my concerns about this issue and all of your help earlier.

-James
