### ISSUE TITLE
Bulk selecting issues to resolve evaluates action text to false

### ISSUE THREAD

**Issue by rd3m** [getsentry/sentry#63488]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to list of issues
2. Click bulk select checkbox to select all issues on the page
3. Click resolve

### Expected Result

Modal text should be -  "Are you sure you want to resolve these 25 issues?"

### Actual Result

![image](https://github.com/getsentry/sentry/assets/76932130/d57cb2af-290e-4f7b-ad13-d7ac7a230306)

### Product Area

Issues

**Comment by rd3m** [comment]
I think [this line](https://github.com/getsentry/sentry/blob/88850793e9c962dbba01d77d335b27ebf41fb224/static/app/views/issueList/actions/utils.tsx#L82) should be `const actionText = action === ConfirmAction.IGNORE ? t('archive') : action`

**Comment by isabellaenriquez** [comment]
Thanks for pointing this out! We'll definitely get that fixed.
