### ISSUE TITLE
inconsistent value of X-Sentry-Team email header

### ISSUE THREAD

**Issue by zelial** [getsentry/sentry#6349]
Sentry email notifications contains a custom header named X-Sentry-Team, which is useful for email filtering. Except the value sometimes is included as is and sometimes lowercased with spaces replaced by dashes.

Example headers:
on a new alert message: X-Sentry-Team: BaseOS CI
on a new comment message: X-Sentry-Team: baseos-ci 

Version: Sentry 8.15.0

**Comment by tkaemming** [comment]
Thanks for the heads up, this should be consistent with the second form mentioned above now, and also be considered for digest notifications (these were missing before.)
