### ISSUE TITLE
Alerting when events are being dropped

### ISSUE THREAD

**Issue by sophiekoonin** [getsentry/sentry#63506]
### Problem Statement

I'd like to be able to set an alert when we hit our rate limit and start dropping events. 

### Product Area

Alerts

**Comment by jangjodi** [comment]
Hi @sophiekoonin, if you are a team member with a manager, billing, or owner level permissions, you can set up event [spend allocation](https://docs.sentry.io/product/accounts/quotas/spend-allocation/) per project or organization. You will be notified by email when 80% and 100% of your spend allocation has been consumed.
