### ISSUE TITLE
Duplicate processing errors

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#6351]
In some cases events report processing errors. Those errors may also end up duplicated, and while the frontend de-dupes them, that should be done on the backend.

![screen shot 2017-10-17 at 12 30 23 pm](https://user-images.githubusercontent.com/23610/31685224-104a17d8-b337-11e7-8c25-65f2d238d3ad.png)

This example has 50+ of the exact same 'error' in the ``errors`` array.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
