### ISSUE TITLE
Slack Integration Problem

### ISSUE THREAD

**Issue by phwhite** [getsentry/sentry#63560]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I had to cancel adding the slack workspace the first time, due to reaching app limit.    After freeing up an app slot, now when I go back and try to add the slack workspace I am getting a "Whoops something went wrong" error and am no longer able to link to Slack.

### Expected Result

I'm expecting to link to slack.

### Actual Result

It's not linking to slack.

### Product Area

Settings - Integrations

**Comment by phwhite** [comment]
After trying again in a Chrome incognito window, it worked, so I no longer have the issue.   Seems it is some cookie problem.    Will let you decide to close this issue or not.    I would suggest that if user hits `Cancel` to adding the workspace integration in the second screen, that it clear this cookie.

**Comment by Dhrumil-Sentry** [comment]
Thanks for the bug report, We've added this to our backlog

**Comment by iamrajjoshi** [comment]
thanks for the update! looks like this might be a cookie issue in the browser, closing for now!
