### ISSUE TITLE
In-stream sparkline

### ISSUE THREAD

**Issue by ckj** [getsentry/sentry#6356]
In Sentry 9 we want to introduce spark lines in the stream to replace the css column based graphs we have in place currently.

<img width="355" alt="screen shot 2017-10-17 at 2 16 13 pm" src="https://user-images.githubusercontent.com/30713/31692541-00c91224-b34f-11e7-93f9-6007aad4296b.png">

The new graphs introduce color-based scale to help a user understand the amount represented as a point on a sparkline compared to some larger whole. Neutral gray/blue would represent an average or below level of events. The pink tones represent a higher than normal count of events.

On hover, each point would need to display a tooltip detailing the timeframe and event count: 

<img width="192" alt="screen shot 2017-10-17 at 2 25 24 pm" src="https://user-images.githubusercontent.com/30713/31692554-0df60506-b34f-11e7-912b-79381058b2ab.png">

In the future, clicking on a point will link to that time range in the stream (time range filtering is not currently supported).

**Comment by dcramer** [comment]
whats normal count?

**Comment by ckj** [comment]
> whats normal count?

@dcramer I think part of this project is figuring out that baseline. Normal could be relative to the issues in the filter, or across the project, etc. I think part of this project is figuring out that baseline.

**Comment by Chrissy** [comment]
Seen and noted! I'll have the think about the _what is normal_ thing. The constant danger with relative graphs is delivering two things that look similar but actually represent very different data.

We also don't _have_ to do a 1:1 coupling of y-value and color, which might make comparisons easier.

**Comment by ckj** [comment]
> The constant danger with relative graphs is delivering two things that look similar but actually represent very different data.

@Chrissy Yeah, that's what we're doing in the app today, and why I think that's why the color axis is necessary. The y-scale is currently per issue. When scanning the stream, the spikiest graphs are usually the lowest in volume (e.g. a spike from 0 to 1). Adding some red to those that aren't all that spikey, but are happening way more often than "normal" seems like a good way to signal relative impact at a glance. That's the theory at least.

**Comment by benvinegar** [comment]
6 months later, we've decided this is pretty low priority and we're going to put this on hold. Closing for now.
