### ISSUE TITLE
[Alpha] Update Amplitude for Metrics

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#63584]
Metrics:
- page view
- add query
- duplicate
- create alert
- add to dashboard
- code location
- sample table interaction

Dashboards:
- add widget + type

Alerts:
- select alert + type

**Comment by ArthurKnaus** [comment]
@matejminar @ale-cota 
For dashboards there is `Widget Builder: Field changed` with `field: dataSet` and `value: metrics`
For alerts there is `Alert Wizard: Option Selected` with `alert_type: custom_metrics`
I guess those should be sufficient?
