### ISSUE TITLE
Remove manual Hub clones

### ISSUE THREAD

**Issue by szokeasaurusrex** [getsentry/sentry#63591]
Manual Hub clones can cause scope leakage issues. Also, with the Hub & Scope changes (https://github.com/getsentry/sentry-python/issues/2533), the SDK will no longer have a concept of a Hub, so these clones likely won't do what they were intended to do anymore.

See also: https://www.notion.so/sentry/Sentry-SDK-Custom-Code-and-why-we-Should-fix-it-932c8493c29b4bb2bf18c2fc4b729ef1?pvs=4#966901ec61a140f1a18d8f63ba9c7719

Parent issue: #56248

**Comment by sl0thentr0py** [comment]
yes, for future reference, the others are all some kind of thread pool executor where you want task level isolation and not thread level (since the same thread will be reused for processing tasks), so we cannot really remove those unless we have first class thread pool integration support.
