### ISSUE TITLE
Sharing issue to VSTS errors due to bug template

### ISSUE THREAD

**Issue by Aidurber** [getsentry/sentry#6360]
We have template set up for a bugs in VSTS which has required fields. This prevents us from sharing issues from Sentry. 

> Error Communicating with Visual Studio Team Services (HTTP 400): TF401320: Rule Error for field Reported By Club. Error code: Required, InvalidEmpty. One additional error occurred during validation of the work item. Please correct all errors and try again.

I'm going to try and file an issue with the Visual Studio Team Services team to add an API endpoint to get a list of templates. 

When sharing a bug to VSTS then, it could be possible in Sentry to select templates when creating the issue. Alternatively, even passing a template ID in the VSTS configuration in Sentry. So we could create a "Sentry" template. It's a query string parameter called "templateId" with a GUID. 
[Use work item templates : VSTS Documentation](https://docs.microsoft.com/en-us/vsts/work/backlogs/work-item-template?tabs=browser)

Would this be possible?

We've been waiting for VSTS integration for a long time, I'm very excited about the support, by the way! 😄 
Thank you

**Comment by Aidurber** [comment]
Just had a thought, would it be more effective to report the issue here: https://github.com/boylec/sentry-vsts

**Comment by dcramer** [comment]
@Aidurber we actually pulled VSTS support into core (getsentry/sentry-plugins).

I think we could do templates in VSTS, though I'm not sure when it'll happen. We've gone down that path with Jira, and to be honest, its a huge pain in the ass. Right now we're still considering VSTS pretty early as it's not functioning for all instances perfectly.

**Comment by Aidurber** [comment]
That's fair enough. 
I've just seen the source for the VSTS plugin. I'm thinking about doing a PR for supporting an optional template ID. Would that be something you would consider pulling in if I can sort it?

**Comment by dcramer** [comment]
@Aidurber ideally, if possible, i think it'd do this:

- A type exists on the create issue form
- When the type is changed, it fetches the fields needed, and renders them
- A default type is set (could be configurable)
