### ISSUE TITLE
Slack Integration : Show context / attributes in notification message 

### ISSUE THREAD

**Issue by julienzakaib** [getsentry/sentry#63718]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Having successfully setup a Slack Integration, looking to improve the quality of the actual message that gets posted to Slack by including useful information that would otherwise only be available by clicking the issue link. Specifically, we have some custom context properties that were added to these issues, and I'd like for some of them to show up in the Slack message.

```
Sentry.withScope(scope => {
  scope.setContext('foo', {
    bar: 'some useful data'
  })
  Sentry.captureEvent()
})
```

![Screen Shot 2024-01-23 at 3 24 42 PM](https://github.com/getsentry/sentry/assets/1383603/6380286f-fd59-4a7b-a118-f082104b1d84)

### How are you getting stuck?

I am able to add tags that will show up in the Slack message, but not other properties of the issue.

### Where in the product are you?

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
Hi @julienzakaib Thanks for sharing this feedback. Currently we only support sending tags to Slack. 

We'll add your request to our backlog and keep this issue updated

**Comment by iamrajjoshi** [comment]
Hello, this seems to be similar to https://github.com/getsentry/sentry/issues/58921, closing this so we can track it there. Feel free to upvote the other issue, it will help us proritize!
