### ISSUE TITLE
Different slack messages for frequent occurances

### ISSUE THREAD

**Issue by chrisjensen** [getsentry/sentry#6372]
We're currently getting a lot of noise in our Slack channel as we work on ironing out bugs.

Currently it's really hard to distinguish an occasional glitch from a serious issue being faced by everyone.

We've configured different alerts for if an event is happening 100, 1000, 10,000 times in an interval, but the messages in slack are the same for these. So an error that occurs once a day looks the same as an error that occurs once ever minute.

It would be really helpful if the slack message could differentiate itself if an event is being triggered a lot.

**Comment by keithhalterman** [comment]
This would be super helpful for us too. We'd love to be able to include information from relevant tags on the issue (e.g. `Serivce: CRM`)

**Comment by benvinegar** [comment]
I believe this is solved by [Sentry's new Slack integration](https://blog.sentry.io/2018/04/02/sentry-plus-slack), launched earlier in 2018.
