### ISSUE TITLE
Improve Share Issue Flow

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#6378]
To deliver on the intent of the action of sharing, we should do the following:

- [x] When clicking share, if its not shared, automatically share it
- [ ] When the link becomes shared, automatically copy the shared link
- [ ] When a link is regenerated, automatically copy the shared link

**Comment by billyvg** [comment]
Instead of hijacking user's clipboard, the shared URL will be selected upon sharing an issue (or regenerating a new share URL).

We can revisit this again if we find the auto-select not sufficient.
