### ISSUE TITLE
How do I show manual breadcrumbs in a Replay?

### ISSUE THREAD

**Issue by csvan** [getsentry/sentry#63798]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

I am using the `addBreadcrumb` API to add custom breadcrumbs to an issue, as per the recommendation in https://github.com/getsentry/sentry-javascript/issues/8154#issuecomment-1554566653. I would like those breadcrumbs to show up in the associated Replay to help navigating to specific parts o it.

### How are you getting stuck?

These breadcrumbs show up fine in the issue itself, however, under the `Breadcrumbs` tab in the associated Replay, there is nothing apart from the Exception that triggered the issue.

### Where in the product are you?

Replays

### Version

21.12.1

**Comment by bruno-garcia** [comment]
@csvan are the breadcrumbs you recorded added within the time of the recording? It should show up then

**Comment by csvan** [comment]
@bruno-garcia yes they are, we've also tried running a manual flush() at the end to no avail. Do they have to belong to some specific category?

**Comment by billyvg** [comment]
@csvan Can you post your `addBreadcrumb` code?

**Comment by csvan** [comment]
@billyvg like so:

```
addBreadcrumb({
  type: 'info',
  level: 'info',
  category: 'cypress',
  message: `${name}: ${message}`,
});
```

**Comment by billyvg** [comment]
@csvan can you email me a link to an example replay where you'd expect the breadcrumb to show up? billy at sentry.io -- thanks

@ryan953 we don't filter custom breadcrumbs on the UI, correct?

**Comment by csvan** [comment]
@billyvg sadly our Sentry GUI is behind a VPN and I have no way to give you access, is there any way I can export it?

**Comment by billyvg** [comment]
@csvan if you open up a replay and browser dev tools, in the Network tab, there should be an API request for `recording-segments` -- if you could email me the result of that request, that would help.

**Comment by billyvg** [comment]
Manual breadcrumbs currently show up in the Console tab, but there seems to be a regression with displaying the message:



![Image](https://github.com/getsentry/sentry/assets/79684/a10aa14f-f0fe-4a2f-907b-cfe8d739981c)


This is the custom event:
```
{
    "tag": "breadcrumb",
    "payload": {
        "timestamp": 1712933337.593,
        "type": "info",
        "level": "info",
        "category": "cypress",
        "message": "billy testing breadcrumbs"
    }
}
```

[Replay for reference](https://sentry-emerging-tech.sentry.io/replays/b71d81fa3fb84ea1851ad1b189aacb56/?project=4504600711200768&query=&referrer=%2Freplays%2F&statsPeriod=14d&t_main=console&yAxis=count%28%29)
