### ISSUE TITLE
Feature Request: Have Error when adding Team to Crons Monitor Notifications not associated to Project 

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#63814]
### Problem Statement

Steps to Reproduce:

- Navigate to Crons Monitor and Edit
- Add to "Notifications" a Team that is not associated to Crons Monitor Project
- Save Changes 
- No error will pop up either when adding unassociated Team or when Saving Edited changes, however when navigating to the Crons Monitor settings again you will see that the unassociated Team(s) were not saved in the "Notifications" section

### Solution Brainstorm

It would be nice for either the unassociated Team(s) to be greyed out and not able to be selected, or an error message informing the customer that these unassociated Team(s) cannot be added either when initially trying to add the Team or when saving the changes

### Product Area

Crons

**Comment by gaprl** [comment]
Hey @ReneGreen27, thank you for the bug report. Our team is taking a look and I'll get back to you early next week.

**Comment by davidenwang** [comment]
Hi @ReneGreen27 thanks for alerting us on this behavior! Gonna work on it and keep progress updates here
