### ISSUE TITLE
Jira Integration Problem

### ISSUE THREAD

**Issue by holymp2006** [getsentry/sentry#63818]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Install Sentry for Jira
2. Click on "Finish Installation in Sentry" button
![Screenshot from 2024-01-25 12-14-48](https://github.com/getsentry/sentry/assets/13824510/29eab88b-522b-4aa7-9276-f361ce7da0df)

### Expected Result

Successfully finish installation.

### Actual Result

Error:  There was an error loading a component.
![Screenshot from 2024-01-25 12-15-21](https://github.com/getsentry/sentry/assets/13824510/eb8276fa-2538-4cc2-86d9-b8be43e8698a)

### Product Area

Settings - Integrations

**Comment by FredSoderberg** [comment]
+1

**Comment by tommy31** [comment]
+1

We are experiencing the same error with on prem sentry server.

https://github.com/getsentry/sentry/issues/63821

**Comment by hermzz** [comment]
+1

Same issue, on prem server. Getting 
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>403</status-code><message>ASAP token from issuer 'micros/edge-authenticator' failed authorization</message></status>
```
 back from Jira when trying to link a Sentry issue to a Jira through the Sentry API.

**Comment by leedongwei** [comment]
Gotcha, we'll prioritize this. Thanks for the report.
