### ISSUE TITLE
Overage notifications should be configurable

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#63819]
### Problem Statement

A customer wrote in, that currently not all engineering leaders can see overage messages from Sentry.

They can't give every leader "Owner" level access to Sentry.

### Solution Brainstorm

Managers should be able to receive overage notifications.  The customer also mentioned that it would be nice to have team-specific quota and rate-limiting setting.

### Product Area

Settings - Members

**Comment by mrduncan** [comment]
Thanks! We're working on some upcoming improvements around spend visibility, including around notifications. We'll keep this use case in mind as we think about designs.

**Comment by brianthi** [comment]
This is available now, with configurable thresholds through the Notifications tab on the Subscriptions page. Any user can get these notifications, they'll just need to enable them in their personal notification settings.
