### ISSUE TITLE
Adjust link to docs in metrics onboarding

### ISSUE THREAD

**Issue by ArthurKnaus** [getsentry/sentry#63832]
Let it point to the docs page instead of the GitHub discussion.

Let's fix in both here: 

![Image](https://github.com/getsentry/sentry/assets/9060071/1d372ca9-3d30-473d-ac04-32cfe29c3a1c)

and onboarding sidebar.

**Comment by ale-cota** [comment]
Main docs: https://docs.sentry.io/product/performance/  (PR [here](https://github.com/getsentry/sentry-docs/pull/8969))

SDK docs: platforms/*platform*/metrics/  (PHP PR [here](https://github.com/getsentry/sentry-docs/pull/8972), others coming)
