### ISSUE TITLE
Jira integration not working

### ISSUE THREAD

**Issue by mikebowbyes** [getsentry/sentry#63864]
### Environment

Self Hosted

### Steps to Reproduce

1. Existing Sentry Self Hosted to Jira integration
2. Starting earlier this week ~ 22/Jan/2024 noticed that we can no longer create Jira issues from Sentry
3. From a sentry issue, clicking the "Link Jira issue" button produces this error "Could not fetch project list from JiraEnsure that jira is available and your account is still active."

### Expected Result

Form would appear and allow us to start creating the jira issue.

### Actual Result

Error message: "Could not fetch project list from JiraEnsure that jira is available and your account is still active."

From sentry logs: (note have subbed our atlassian server with [our-host])

16:18:55 [INFO] sentry.integrations.client: integration.http_response (status_string='403' error='403 Client Error: Forbidden for url: https://[our-host].atlassian.net/rest/api/2/project?jwt=<token>' integration='jira' org_id=1 integration_id=3 org_integration_id=4)
16:18:55 [INFO] sentry.integrations.jira: jira.get-create-issue-config.no-projects (integration_id=3 organization_id=1 error='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><status><status-code>403</status-code><message>ASAP token from issuer \'micros/edge-authenticator\' failed authorization</message></status>')
16:18:55 [INFO] sentry.access.api: api.access (method='GET' view='sentry.api.endpoints.group_integration_details.GroupIntegrationDetailsEndpoint' response=400 user_id='72' is_app='None' token_type='None' is_frontend_request='True' organization_id='1' auth_id='None' path='/api/0/groups/9916/integrations/3/' caller_ip='69.11.56.234' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0' rate_limited='False' rate_limit_category='user' request_duration_seconds=0.9399609565734863)
16:18:55 [WARNING] django.request: Bad Request: /api/0/groups/9916/integrations/3/ (status_code=400 request=<WSGIRequest: GET '/api/0/groups/9916/integrations/3/?action=create'>)

### Product Area

Unknown

### Version

22.3.0

**Comment by sentaur-athena** [comment]
This is similar to https://github.com/getsentry/sentry/issues/63821.
This issue is fixed in https://github.com/getsentry/sentry/commit/d9f5e5fa9ceec614e6deedd2f8f7c484d8a99e0b and upgrade should help you get past it.
