### ISSUE TITLE
Registry for apps to extend cleanup, merging, deletions

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry#6389]
Would be great if models/apps had some sort of meta field where they could register themselves with cleanup, merging and deletions. Current examples (that should be moved into a registry system) follow:

Cleanup:
https://github.com/getsentry/sentry/blob/067fce166d44e3bdaedfedace213b68ade792da6/src/sentry/tagstore/legacy/backend.py#L64-L68

Merge:
https://github.com/getsentry/sentry/blob/067fce166d44e3bdaedfedace213b68ade792da6/src/sentry/tagstore/legacy/backend.py#L70-L73

Deletions:
https://github.com/getsentry/sentry/blob/067fce166d44e3bdaedfedace213b68ade792da6/src/sentry/tagstore/legacy/backend.py#L41-L62

Bonus: We could use a way to handle moving old model names:
https://github.com/getsentry/sentry/blob/067fce166d44e3bdaedfedace213b68ade792da6/src/sentry/utils/imports.py#L14-L20

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
