### ISSUE TITLE
Reduce unique styles in replay timeline

### ISSUE THREAD

**Issue by scttcper** [getsentry/sentry#63910]
Each column in the replay timeline adds a unique style (grid-col which might be slow if theres a lot of items. Can use inline styles to avoid this. 

![image](https://github.com/getsentry/sentry/assets/1400464/60f96b99-3841-47f6-a23d-6fef3d90826b)

https://github.com/getsentry/sentry/blob/master/static/app/components/replays/breadcrumbs/replayTimelineEvents.tsx#L61

**Comment by billyvg** [comment]
This looks fixed now ![Image](https://github.com/user-attachments/assets/d320255f-a330-49d7-89a3-bf62d1d1e28e)
