### ISSUE TITLE
Cryptic error message on user feedback when ad blocker installed

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/sentry#63921]
### Steps

1. Run Chrome w/ an ad blocker.
2. Try to submit user feedback on sentry.io.

### Expected 

Feedback submitted.

### Actual

Cryptic error message:

> There was a problem submitting feedback, please wait and try again.

### Notes

Can we at least sniff ad blockers and give better error messages? 

<img width="1355" alt="Screenshot 2024-01-25 at 7 35 09 PM" src="https://github.com/getsentry/sentry/assets/134455/86c7ad26-049d-455a-9f6d-86fbac7f767c">

**Comment by bruno-garcia** [comment]
@chadwhitacre what would you have expected in a situation like this? I'm thinking we could change the wording to suggest an ad-blocker is in place

**Comment by chadwhitacre** [comment]
> I'm thinking we could change the wording to suggest an ad-blocker is in place

Yes that would be much better. We should fork the ublock list together [with Plausible](https://github.com/plausible/analytics/discussions/610) and other like-minded companies and drive people to adopt ours instead. 🙃

**Comment by bruno-garcia** [comment]
If we get status code 0 we'll suggest: "Either offline or ad-blocker related"

**Comment by bruno-garcia** [comment]
@chadwhitacre we have the same issue reported here: 

* https://github.com/getsentry/sentry-javascript/issues/9371

Since change happens on the SDK we'll close this in favor of that
