### ISSUE TITLE
I want to be able to delete a metric (DDM)

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/sentry#63922]
### Problem Statement

I created a bunch of metrics in the course of testing and development. I only want one of them long-term.

<img width="530" alt="Screenshot 2024-01-25 at 7 41 16 PM" src="https://github.com/getsentry/sentry/assets/134455/db22bfdf-93c2-4b51-acf0-ed52b44291b5">

### Solution Brainstorm

Add a "Delete metric" button to the Metric Details page. I would expect it to be at the bottom with a red button.

<img width="571" alt="Screenshot 2024-01-25 at 7 42 36 PM" src="https://github.com/getsentry/sentry/assets/134455/0ef1c56c-c5f3-42ed-9677-06a6d5b09a39">

### Product Area

DDM

**Comment by samuelhwilliams** [comment]
Same here :)

**Comment by matejminar** [comment]
Hi, we don't have a delete metric functionality yet.
As a workaround, you can use "Block". It will hide the metric from UI and will also stop ingesting metrics with that name.
![CleanShot 2024-04-18 at 12 06 21](https://github.com/getsentry/sentry/assets/9060071/fe3bfeef-2695-4fd0-b893-f71a9a6f7924)

**Comment by wedamija** [comment]
https://github.com/getsentry/sentry/discussions/81239
