### ISSUE TITLE
Don't know how to use linked issue properties in issues search filter

### ISSUE THREAD

**Issue by richtluk** [getsentry/sentry#63945]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Filter issues (sentry.io/issues) by linked issues (from external issue tracker - Jira) properties. e.g. linked issue is in state "DONE" or "OPEN" etc.

### How are you getting stuck?

Didn't find it anywhere in documentation or on the internet. Maybe it is not a feature yet.

### Where in the product are you?

Issues

**Comment by scttcper** [comment]
Thanks for this feature request, i've added it to our backlog. I'm not sure that we currently store the state of the linked issues? Services like jira should already sync the status between sentry/jira.

**Comment by snigdhas** [comment]
Unfortunately, we don't store the state for linked issues in a way that is searchable in the issue stream. Instead, Sentry does a conversion of the state from JIRA to the states supported in Sentry (and vice versa). There's some configurability available for how that information sync ([docs](https://docs.sentry.io/organization/integrations/issue-tracking/jira/#issue-sync)). Based on the existing search architecture, I don't see us being able to support this sort of field. 

Please feel free to reopen if there's more we can help with!
