### ISSUE TITLE
Make Issue grouping better when URLs are present in stackframes

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#63955]
### Problem Statement

For some web frameworks like Next.js, the stackframes can have unique URLs for each error event. Sentry groups by stacktraces and this can lead to several duplicate issues getting created instead of 1 which adds to noise in the Issue Stream and Notifications

### Product Area

Issues

**Comment by mrduncan** [comment]
Closing this for now since [AI grouping](https://blog.sentry.io/cancel-the-issue-noise/) seems to mostly handle these.
