### ISSUE TITLE
Check-ins with fast executions sometimes cause missed or skipped check-ins

### ISSUE THREAD

**Issue by gaprl** [getsentry/sentry#63969]
We've noticed check-ins that happen extremely fast sometimes cause check-ins to fail, be missed, or skipped altogether. We're currently working on a fix.

**Comment by iris-baton** [comment]
Not sure if this is related, but I just filed https://github.com/getsentry/sentry/issues/64000. I've merged a revert to temporarily use the old endpoint until these issues are sorted out

**Comment by gaprl** [comment]
Hello all, as of yesterday, we've been able to solve this issue. If you still have problems, please make sure to update your SDKs to the latest version.
