### ISSUE TITLE
Support thread grouping if there is a single crashed thread

### ISSUE THREAD

**Issue by tsondergaard** [getsentry/sentry#6398]
#5245 introduced thread grouping if there is a single thread. This issue is about extending this to support thread grouping if there is a single crashed thread (out of multiple threads).

This is reasonable as the SDK otherwise has to include the stacktrace for the crashing thread twice in the event to achieve proper grouping. Also, if the event has both a separate stacktrace and threads with stacktraces the presentation in the UI shows the same stacetrace twice.

See also this thread: https://forum.sentry.io/t/grouping-by-stacktrace/2554

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
