### ISSUE TITLE
Python dictionaries render with lots of extra slashes in UI

### ISSUE THREAD

**Issue by dan-blanchard** [getsentry/sentry#6399]
I'm not sure if this is a client or server issue, but with `raven-python 6.1.0` I've noticed that lately we encounter instances where a dictionary will render incorrectly in the UI, which makes debugging much harder.

For example:

<img width="937" alt="screenshot 2017-10-23 11 34 41" src="https://user-images.githubusercontent.com/976345/31898199-852e4a5c-b7e6-11e7-98b4-b4df8c060c8b.png">

for a Python dictionary that is roughly:

```py
{'filter': {'bool': {'must': [{'term': {'page_type': 'post'}}, 
                              {'term': {'apikey': 'someapikey'}}],
                     'must_not': [{'term': {'recrawlable': False}]}
```

**Comment by MaxBittker** [comment]
😂 looks fine to me. (thanks for the issue dan, I think i've noticed this too.)

**Comment by alex-hofsteede** [comment]
@dan-blanchard I stumbled across a similar problem as well just now, and I think #6636 should fix it for your case too.

**Comment by dan-blanchard** [comment]
@alex-hofsteede so happy to see a fix is coming soon!

**Comment by alex-hofsteede** [comment]
This is merged. It won't go back and fix any past events that were serialized this way, but should prevent new data from having this problem.
