### ISSUE TITLE
Switching a new cron's checkins to the new endpoint caused an existing cron's checkins to be missed

### ISSUE THREAD

**Issue by iris-baton** [getsentry/sentry#64000]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Two frequent heartbeat cron monitors were working fine. We deployed a third cron monitor (overlapping, non-heartbeat) pointed at the new endpoint, and suddenly the first two had a lot of missed checkins

### Expected Result

Working monitors keep working

### Actual Result

Existing monitors stopped working (many missed checkins), and the new one was exhibiting the behavior described in https://github.com/getsentry/sentry/issues/63969 (fast runs being erroneously marked "timed out")

### Product Area

Crons

### DSN

https://o415829.ingest.sentry.io/api/4504301803077632

**Comment by iris-baton** [comment]
![Screenshot 2024-01-26 at 8 45 05 AM](https://github.com/getsentry/sentry/assets/148919389/e2e5836e-8330-4be9-8126-dab30456168f)
The deploy in question happened around 5:35 PM yesterday. Our heartbeats (and many other monitors) started experiencing issues within ~15 minutes and didn't come back until we reverted the deploy. The only monitors that kept working smoothly were still sending checkins to the old endpoint

**Comment by gaprl** [comment]
This issue should be resolved by #63969, if not, please feel free to reopen this issue. Thank you.
