### ISSUE TITLE
Numbers discrepency

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#64023]
Arpad: So I have this weird discrepancy between DDM and DD for a counter/sum metric that I capture with an explicit number. can someone explain to me why DD outputs a much higher number for the old tag than DDM? the difference is very significant, and I don’t know what I am doing wrong here?

https://app.datadoghq.com/notebook/7293216?cell_id=opagp2ub

https://sentry.sentry.io/ddm/?project=1&statsPeriod=7d&widgets=%5B%7B%22mri%22%3A%22c%3Acustom%2Fsentry.apple_symbol_availability%40none%22%2C%22op%22%3A%22sum%22%2C%22query%22%3A%22%22%2C%22groupBy%22%3A%5B%22availability%22%5D%2C%22displayType%22%3A%22area%22%2C%22showSummaryTable%22%3Atrue%2C%22sort%22%3A%7B%22order%22%3A%22asc%22%7D%7D%5D

**Comment by iambriccardo** [comment]
@Swatinem will increase the sample rate of the metric to 100%

**Comment by iambriccardo** [comment]
PR available here: https://github.com/getsentry/sentry/pull/64049#pullrequestreview-1848539167

**Comment by Swatinem** [comment]
hm, even with sampling rate forced to 100%, we still have this huge gap that I can’t explain.

**Comment by iambriccardo** [comment]
Both @untitaker and @Swatinem weren't able to figure out what is going on. Closing the ticket for now and will bring it back in case of further escalation.
