### ISSUE TITLE
Surface metrics in the outcomes API

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#64026]
Introduce a new metric category in stats_v2 endpoint so that we can query metric outcomes.
As an examples, rhis is how the query looks like for error outcomes:
https://sentry.io/api/0/organizations/sentry/stats_v2/?category=error&field=sum%28quantity%29&groupBy=outcome&groupBy=reason&interval=1d&project=1&statsPeriod=90d

The goal is to see when metrics are rate-limited. Relay already supports this with outcome rate_limited and reason cardinality_limited.

**Comment by iambriccardo** [comment]
The endpoint seems to support already a generic querying interface, thus we can query the category `metric_bucket` to access outcomes related to metrics. A proposal of how to query the endpoint has been written internally.
