### ISSUE TITLE
The event bubbles seem to be slightly misaligned (firefox)

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#64052]
![Image](https://github.com/getsentry/sentry/assets/9060071/0d99cc01-f41f-4672-98a4-e8781fa702e2)

**Comment by obostjancic** [comment]
Sampled events are currently positioned according to their absolute timestamp so they are not aligned with the actual interval buckets. The peaks in the chart on the other hand correlate to the interval buckets of the chart.

![Image](https://github.com/getsentry/sentry/assets/86684834/1d79f119-7388-48f0-9a18-564c556f32e1)
![Image](https://github.com/getsentry/sentry/assets/86684834/df886b2a-38f2-4cb7-8df5-4c90b87de6e0)

Closing this as Won't do. We can revisit this and coerce samples into time series buckets if necessary
