### ISSUE TITLE
JVM/Android issue title not derived from the most deeply nested error 

### ISSUE THREAD

**Issue by grandstaish** [getsentry/sentry#64074]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Try/Catch on the JVM allows you to catch an exception and throw a different one, listing the originally thrown exception as a `cause`:

```kotlin
try {
  potentiallyDangerousCode()
} catch (e: IOException) {
  throw AppException(e)
}
```

In this example, if `potentiallyDangerousCode` throws an `IOException`, then Sentry will make the title of the issue `AppException`. This is not useful because because in this imaginary example any number of `IOException`s could have occurred in `potentiallyDangerousCode`! It should be easy to use the issue title as a way to distinguish these issues. Therefore Sentry should do what Firebase does and use the most deeply nested `cause` for deriving the title. 

This is particularly problematic on Android, because `potentiallyDangerousCode` becomes your entire app! [Source](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/core/java/com/android/internal/os/RuntimeInit.java;l=551-563;drc=228276a74bc36e8c0f0fadbb4a15ef013ff6ce24). So in Android apps, unless your exception thrown is a `RuntimeException`, then Sentry will always title the issue as `RuntimeException — com.android.internal.os.RuntimeInit$MethodAndArgsCaller in run at line 562`. 

I listed this as a bug, but it could also be a feature request? Feel free to change it if it's intended. 

### Expected Result

Title of the issue should be derived from the most deeply nested exception cause, not from the topmost one. 

### Actual Result

Title of the issue is derived from the topmost exception. 

### Product Area

Issues

**Comment by scttcper** [comment]
Thanks for reporting, seems like something we should support better. I've added it to our backlog

**Comment by armenzg** [comment]
Has this been fixed after https://github.com/getsentry/sentry-java/pull/3212 got merged?
