### ISSUE TITLE
Port stacktrace inversion from hierarchical strategy

### ISSUE THREAD

**Issue by lobsterkatie** [getsentry/sentry#64087]
NOTE: This issue is really @armenzg 's. I just clicked "convert to issue" on the project board.

-----

@mitsuhiko and I were investigating Dropbox grouping issues and he brought up that some of the ANR (app hanging) issues should have their stack trace reversed.

This is a feature that was implemented for hierarchical grouping and we should look into porting it to our current grouping.

The error events that should be reversed are the ones that have `snapshot` set to `true` (threads/exception -> values -> stacktrace -> snapshot: true).

Some of the invertion logic can be found in here: https://github.com/getsentry/sentry/blob/c49c9ef2a3b150589bc147a1c4e5be27a9535065/src/sentry/grouping/strategies/newstyle.py#L557-L567 which was merged as part of [PR 24346](https://github.com/getsentry/sentry/pull/24346).

Here are some related notes and recording:
https://www.notion.so/sentry/Dropbox-iOS-issues-8a30aa01fbea4553b5befbbd0a4b9e1f?pvs=4#1a9e39bfcd754df0a76b37fd4921743e

**Comment by armenzg** [comment]
There was no interest in keeping this functionality.
