### ISSUE TITLE
Georgia Dept of Education:  Districts are reporting performance issues when viewing professional development courses

### ISSUE THREAD

**Issue by trobinsonllc** [getsentry/sentry#64089]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Steps to Reproduce:
1.  Users login through their Student Information System to the Performance Development Portal
2.  User launch the course and view modules which contain SCORM videos and other files
3.  Buffering and poor performance is not noticed immediately, but after a fairly short period of time

### Expected Result

The user should be able to view the course in its entirety without errors or performance issues.  

### Actual Result

Users are reporting significant buffering and fatal error notification on a select group of Georgia Department of Education performance development courses since Wednesday of last week.  District support admins have taken the following steps to troubleshoot:
 
- Checking bandwidth (our technology coordinator has verified this is not the issue)
- Comparing the course with other GALearns courses (the others play very well) 
- Comparing the performance of modules through the original provider Cox Campus (the videos have played without buffering or fatal errors from Cox Campus) 
- Accessing GALearns through home and school internet (the issue occurs on both)
- Collecting reports from multiple users across the system (the issue seems to be universally replicated)
- Using DevTools - the error in the following screenshot was noted: 
![image](https://github.com/getsentry/sentry/assets/111534127/d15d0169-9e91-4cc6-a4b7-fb7bbc42daef)
'Failed to load resource:  the server responded with a status of relay-iad.sentry.ins_ot.reach%2F7.81.0::1

### Product Area

Performance

**Comment by trobinsonllc** [comment]
Our course modules are using a URL that is pointed to sentry.io on your end.  Were there any server issues or performance issues on your side that may have contributed to the issues we are experiencing?

**Comment by trobinsonllc** [comment]
Thanks for your feedback.  I will pass along this information and look into whether the 503's are still occurring.

**Comment by k-fish** [comment]
Sounds good @trobinsonllc, I'm going to close this issue for now but if you find out feel free to leave a comment and we can check it out.
