### ISSUE TITLE
Sentry Bundle Analysis

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry#64090]
## New Version
For v0 of sentry bundle analysis, we will focus on tracking bundle size overtime. To do this, we'll be using the metrics product to push metrics on frontend application release.

```[tasklist]
### Backend
- [x] Add use case id for bundle analysis project
- [x] Create get endpoint to publish new metrics for a particular project, this should be tagged with JS/CSS/Fonts/Imgs
- [ ] Create endpoint to get the metrics as a time series for a given date range.
```

```[tasklist]
### Sentry Webpack Plugin (sentry-bundler-plugins)
- [x] update codecov-javascript-bundler-plugins to send sentry bundle stats metrics
- [ ] Uses codecov-javascript-bundler-plugins under the hood to generate stats
- [ ] add codecov-javascript-bundler-plugins to sentry-bundler-plugins
```

```[tasklist]
### Sentry UI
- [x] Add bundle size overtime stacked area graph.
- [ ] Ensure that if the bundle stats aren't there, a graph does not show and a message to setup bundle analysis appears.
- [ ] Hook up bundle size graph to real data
```

### Uploading to Sentry (Client-side)

Option 1: codecov-javascript-bundler-plugins + `SENTRY_AUTH_TOKEN`
Option 2: codecov bundler plugins emits stats file -> we upload stats file via sentry-cli
Option 3: sentry-bundler-plugins uses codecov-javascript-bundler-plugins under the hood

### Uploading to Sentry (Server-side)

- Chunked Uploads (stats file can be HUGE for big codebases) https://github.com/getsentry/sentry/blob/b3a3f9296def99881e45ef34484db01fc0444fc0/src/sentry/api/endpoints/chunk.py#L49

We need to decide what backend to select (postgres, direct to GCS via filestore, nodestore) TBD after talking with smart people.

### Querying

- backend endpoint(s) that can query storage backend for stats file/json equivalent
- dependent on what product features we want, per release workflows, per asset workflows, per parameterized asset workflows

 ### UI facing changes

- Align stats file asset path with resources module asset path (fix domain/path)
- Figure out where to render modules table
- STRETCH: deep link with codecov

**Comment by DominikB2014** [comment]
Moved this to `TODO` as we are pausing work on this!

**Comment by AbhiPrasad** [comment]
Going to close this as we have codecov bundle analysis now :)
