### ISSUE TITLE
Crash after relogon

### ISSUE THREAD

**Issue by skytaker** [getsentry/sentry#6415]
Hello! I use Sentry 8.21.0, Docker, for authentication use django-auth-ldap
sentry-ldap-auth. Description of the problem: I authorize using the AD’s credentials, everything works without problems, but as soon as I make an exit and try to relogin, the system falls. In error logs:

 UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 3: ordinal not in range(128)
[ERROR] django.request: Internal Server Error: / auth / login / sentry / ((status_code = 500 request = <WSGIRequest: POST u ‘/ auth / login / sentry /’>)

postgres_1 | ERROR: duplicate key value violates unique constraint "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
postgres_1 | DETAIL: Key (project_id, environment_id) = (1, 12) already exists.
postgres_1 | STATEMENT: INSERT INTO “sentry_environmentproject” (“project_id”, “environment_id”) VALUES (1, 12) RETURNING “sentry_environmentproject”. “Id”
Hope for your help!

**Comment by mattrobenolt** [comment]
Can you provide a full stacktrace? There isn’t enough information here to debug. But my guess is a bug in the LDAP plugin which isn’t from us. We’ve changed some stuff lately around authentication, and this plugin probably needs to be updated.

**Comment by skytaker** [comment]
|#033[0m 10.0.112.239 - - [24/Oct/2017:14:09:25 +0000] "GET /api/0/broadcasts/ HTTP/2.0" 200 261 "https://sentry.svet.ru/sentry/maximus-web-back-end/settings/install/php/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 14:09:27 [INFO] sentry.auth: user.auth.success (username=u'k.y.skytaker' organization_id=1L ip_address=u'10.0.112.250')
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:27 +0000] "POST /auth/login/sentry/ HTTP/2.0" 302 976 "https://sentry.svet.ru/auth/login/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:27 +0000] "GET /auth/login/ HTTP/2.0" 302 715 "https://sentry.svet.ru/auth/login/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:27 +0000] "GET /sentry/ HTTP/2.0" 200 4366 "https://sentry.svet.ru/auth/login/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:27 +0000] "GET /api/0/internal/health/ HTTP/2.0" 200 370 "https://sentry.svet.ru/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:27 +0000] "GET /api/0/organizations/?member=1 HTTP/2.0" 200 744 "https://sentry.svet.ru/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:27 +0000] "GET /api/0/organizations/?member=1 HTTP/2.0" 200 744 "https://sentry.svet.ru/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:27 +0000] "GET /api/0/organizations/sentry/ HTTP/2.0" 200 9164 "https://sentry.svet.ru/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:27 +0000] "GET /api/0/broadcasts/ HTTP/2.0" 200 261 "https://sentry.svet.ru/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:27 +0000] "GET /api/0/organizations/sentry/stats/?stat=received&since=1508767762&until=1508854162&resolution=1h HTTP/2.0" 200 744 "https://sentry.svet.ru/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:27 +0000] "GET /api/0/organizations/sentry/stats/?stat=rejected&since=1508767762&until=1508854162&resolution=1h HTTP/2.0" 200 731 "https://sentry.svet.ru/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:27 +0000] "GET /api/0/organizations/sentry/members/me/issues/assigned/?&cursor=&statsPeriod=24h&per_page=5&status=unresolved HTTP/2.0" 200 648 "https://sentry.svet.ru/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:27 +0000] "GET /api/0/organizations/sentry/stats/?stat=blacklisted&since=1508767762&until=1508854162&resolution=1h HTTP/2.0" 200 731 "https://sentry.svet.ru/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:27 +0000] "GET /api/0/organizations/sentry/activity/?cursor=&per_page=10 HTTP/2.0" 200 544 "https://sentry.svet.ru/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:27 +0000] "GET /api/0/organizations/sentry/issues/new/?cursor=&statsPeriod=24h&per_page=5&status=unresolved HTTP/2.0" 200 1873 "https://sentry.svet.ru/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:27 +0000] "GET /api/0/organizations/sentry/stats/?since=1508767762.62&stat=generated&group=project HTTP/2.0" 200 8964 "https://sentry.svet.ru/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:30 +0000] "GET /api/0/organizations/sentry/members/me/issues/assigned/?cursor=&status=unresolved&statsPeriod=24h&per_page=25 HTTP/2.0" 200 654 "https://sentry.svet.ru/organizations/sentry/issues/assigned/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.135 - - [24/Oct/2017:14:09:31 +0000] "GET /api/0/broadcasts/ HTTP/2.0" 200 261 "https://sentry.svet.ru/sentry/maximus-web-back-end/issues/2197/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"
 |#033[0m 10.0.21.16 - - [24/Oct/2017:14:09:31 +0000] "POST /api/6/store/ HTTP/1.1" 200 366 "-" "-"
 |#033[0m ERROR:  duplicate key value violates unique constraint "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
 |#033[0m DETAIL:  Key (project_id, environment_id)=(6, 1) already exists.
 |#033[0m STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id") VALUES (6, 1) RETURNING "sentry_environmentproject"."id"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:33 +0000] "GET /auth/logout/ HTTP/2.0" 302 497 "https://sentry.svet.ru/organizations/sentry/issues/assigned/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:33 +0000] "GET /auth/login/ HTTP/2.0" 302 580 "https://sentry.svet.ru/organizations/sentry/issues/assigned/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:33 +0000] "GET /auth/login/sentry/ HTTP/2.0" 200 10706 "https://sentry.svet.ru/organizations/sentry/issues/assigned/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m 1:M 24 Oct 14:09:35.055 * 10000 changes in 60 seconds. Saving...
 |#033[0m 1:M 24 Oct 14:09:35.056 * Background saving started by pid 249
 |#033[0m 249:C 24 Oct 14:09:35.082 * DB saved on disk
 |#033[0m 249:C 24 Oct 14:09:35.083 * RDB: 0 MB of memory used by copy-on-write
 |#033[0m 1:M 24 Oct 14:09:35.157 * Background saving terminated with success
 |#033[0m Traceback (most recent call last):
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
 |#033[0m     response = wrapped_callback(request, *callback_args, **callback_kwargs)
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
 |#033[0m     return self.dispatch(request, *args, **kwargs)
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
 |#033[0m     return view_func(*args, **kwargs)
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/base.py", line 194, in dispatch
 |#033[0m     return self.handle(request, *args, **kwargs)
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
 |#033[0m     response = view_func(request, *args, **kwargs)
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
 |#033[0m     return func(*args, **kwargs)
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_organization_login.py", line 130, in handle
 |#033[0m     response = self.handle_basic_auth(request, organization)
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/sentry/web/frontend/auth_organization_login.py", line 63, in handle_basic_auth
 |#033[0m     elif login_form.is_valid():
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 129, in is_valid
 |#033[0m     return self.is_bound and not bool(self.errors)
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 121, in errors
 |#033[0m     self.full_clean()
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 274, in full_clean
 |#033[0m     self._clean_form()
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 300, in _clean_form
 |#033[0m     self.cleaned_data = self.clean()
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/sentry/web/forms/accounts.py", line 151, in clean
 |#033[0m     self.user_cache = authenticate(username=username, password=password)
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 49, in authenticate
 |#033[0m     user = backend.authenticate(**credentials)
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 173, in authenticate
 |#033[0m     user = ldap_user.authenticate(password)
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 350, in authenticate
 |#033[0m     self._get_or_create_user()
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 577, in _get_or_create_user
 |#033[0m     self._user, created = self.backend.get_or_create_user(username, self)
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/sentry_ldap_auth/backend.py", line 38, in get_or_create_user
 |#033[0m     if 'mail' in ldap_user.attrs:
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 432, in _get_user_attrs
 |#033[0m     self._load_user_attrs()
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/backend.py", line 474, in _load_user_attrs
 |#033[0m     results = search.execute(self.connection)
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/config.py", line 178, in execute
 |#033[0m     return self._process_results(results)
 |#033[0m   File "/usr/local/lib/python2.7/site-packages/django_auth_ldap/config.py", line 252, in _process_results
 |#033[0m     "; ".join(result_dns)))
 |#033[0m UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 3: ordinal not in range(128)
 |#033[0m 14:09:35 [ERROR] django.request: Internal Server Error: /auth/login/sentry/ (status_code=500 request=<WSGIRequest: POST u'/auth/login/sentry/'>)
 |#033[0m ERROR:  duplicate key value violates unique constraint "sentry_eventuser_project_id_1a96e3b719e55f9a_uniq"
 |#033[0m DETAIL:  Key (project_id, hash)=(1, ed3492e13440bd9c12c1acc8b0b80b76) already exists.
 |#033[0m STATEMENT:  INSERT INTO "sentry_eventuser" ("project_id", "hash", "ident", "email", "username", "name", "ip_address", "date_added") VALUES (1, 'ed3492e13440bd9c12c1acc8b0b80b76', NULL, NULL, NULL, NULL, '10.0.112.250', '2017-10-24 14:09:36.006014+00:00') RETURNING "sentry_eventuser"."id"
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:35 +0000] "POST /auth/login/sentry/ HTTP/2.0" 500 9176 "https://sentry.svet.ru/auth/login/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"
 |#033[0m ERROR:  duplicate key value violates unique constraint "sentry_environmentproject_project_id_29250c1307d3722b_uniq"
 |#033[0m DETAIL:  Key (project_id, environment_id)=(1, 12) already exists.
 |#033[0m STATEMENT:  INSERT INTO "sentry_environmentproject" ("project_id", "environment_id") VALUES (1, 12) RETURNING "sentry_environmentproject"."id"
 |#033[0m ERROR:  duplicate key value violates unique constraint "sentry_featureadoption_organization_id_78451b8747a9e638_uniq"
 |#033[0m DETAIL:  Key (organization_id, feature_id)=(1, 0) already exists.
 |#033[0m STATEMENT:  INSERT INTO "sentry_featureadoption" ("organization_id", "feature_id", "date_completed", "complete", "applicable", "data") VALUES (1, 0, '2017-10-24 14:09:36.096005+00:00', true, true, '{}'), (1, 42, '2017-10-24 14:09:36.096156+00:00', true, true, '{}')
 |#033[0m 10.0.112.250 - - [24/Oct/2017:14:09:36 +0000] "GET /api/embed/error-page/?eventId=0435a06f454b403c876bb867d24bb101&dsn=https%3A%2F%2Fc22d69030cca4cb894c5f029a2c22b3e%40sentry.svet.ru%2F1 HTTP/2.0" 200 15087 "https://sentry.svet.ru/auth/login/sentry/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.62 Safari/537.36"

**Comment by mattrobenolt** [comment]
Yeah, this is 100% a bug with sentry-auth-ldap. The entire stacktrace is coming from that and `django-auth-ldap`.

There's nothing I or Sentry can do here to fix it. :(
