### ISSUE TITLE
[Bug] Replay Banner on Issue Details - the "Hide Details" button is not sticky

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#64175]
The "Hide/Show Details" button on the Replay Banner on Issue Details is not sticky (i.e., does not persist). This is problematic when we show the banner on a web BE project and it's not relevant for the org.

[Link to example](https://sentry.sentry.io/issues/4925850650/?environment=production&project=4505160011087872&query=&referrer=issue-stream&statsPeriod=14d&stream_index=2) [INTERNAL]

![Screenshot 2024-01-30 at 10 30 46 AM](https://github.com/getsentry/sentry/assets/77064737/307c3d73-65fc-4d1c-af62-dac176565832)

**Note: This is true for all Show/Hide Details buttons. We should make this behaviour consistent** (Pending discussion w Issues team)

**Comment by michellewzhang** [comment]
if this behavior is consistent across all show/hide buttons on issues then we should bring it up with the issues team to make sure they're okay with their section buttons being sticky as well

**Comment by jas-kas** [comment]
@michellewzhang agree - thanks for scheduling a meeting tmr!

**Comment by michellewzhang** [comment]
Instead of touching the show/hide functionality, we're updating the CTA in favor of this design: https://github.com/getsentry/sentry/issues/64311
