### ISSUE TITLE
Gitlab integration failure 

### ISSUE THREAD

**Issue by AndrewBurdyug** [getsentry/sentry#6422]
Hi! 

Gitlab integration does not work, when I click the button "Create GitLab Issue", I get error :(
And it is happend from version to version, I do not remember in which version of Sentry 
this feature worked...

> - The version of Sentry you're using

Gitlab instance - I use free plan of https://gitlab.com 
Sentry instance:  8.21.0 (latest, but this feature not really worked on previous versions too)

> - Whether you're using Docker or another installation method

manual install (all works fine, except Gitlab integration)

> - Include a stacktrace or other logs when relevant

here stack trace which gitlab instance email me:

```python 
AttributeError: 'Gitlab' object has no attribute 'Project'
(3 additional frame(s) were not displayed)
...
  File "sentry/web/frontend/base.py", line 194, in dispatch
    return self.handle(request, *args, **kwargs)
  File "sentry/web/frontend/group_plugin_action.py", line 25, in handle
    response = plugin.get_view_response(request, group)
  File "sentry/plugins/base/v1.py", line 315, in get_view_response
    response = self.view(request, group)
  File "sentry/plugins/bases/issue.py", line 242, in view
    request=request,
  File "sentry_gitlab/plugin.py", line 88, in create_issue
    proj = gl.Project(id=repo_url)
```

**Comment by dcramer** [comment]
> DEPRECATED: This project now lives in sentry-plugins

**Comment by AndrewBurdyug** [comment]
Thank you for hint, I missed it, my installation have had very old sentry-gitlab-0.2.0, 
so removing this one and installing the new addon (sentry-plugins) have fixed my problem!
