### ISSUE TITLE
'Save Changes' for deleting tags doesn't seem to work.

### ISSUE THREAD

**Issue by MeredithAnya** [getsentry/sentry#6428]
From support ticket: "Clicking the trash icon for each Tag fires a DELETE request with a 204 response, but the items remain in the list. When I click Save Changes (which sends a POST), there is a 405 METHOD NOT ALLOWED response and the page is blank."

I was able to eventually delete tags by repeating the process a couple times and refreshing the page but still not sure why it didn't work in the first place.

**Comment by bretthoerner** [comment]
So a few things are going on here (none of them are new/changed with tagstore):

1. The "Save Changes" button is pointless, by clicking the trash can you issue a delete, that's all that's needed. I assume "Save Changes" is leftover from when we had labels, it can be removed AFAIK.
2. We give no UI notification on the page that the tag is/was being deleted, like hiding the row (I can't really help here).
3. Even if you refresh (or use "Save Changes") the page is using a cached list of tag keys, and so the deleted (or in progress of deletion) tag is still shown.

I'll work on 1 and 3.

**Comment by bretthoerner** [comment]
@MeredithAnya I'm curious if the user would agree this was a caching issue. The cache should have been cleared after 60 seconds. Keeping in mind if they had new events coming in with the same tag that it would have been recreated...

**Comment by bretthoerner** [comment]
Sorry, it was caching *and* it would display the tag until the async deletion completed. #6431 has fix.
