### ISSUE TITLE
[Design] Iterate on Replay CTA on Issue Details

### ISSUE THREAD

**Issue by michellewzhang** [getsentry/sentry#64311]
Synced with @vuluongj20, @rachrwang, @jas-kas, @bruno-garcia and we agreed on the following criteria to update the Replay CTA (both frontend & web backend) on Issue Details:

Requirements:
- Standardize Frontend & Web Backend CTA design.

The frontend design looks like this: 
![screenshot_2024-01-31_at_2 18 10___pm_720](https://github.com/getsentry/sentry/assets/56095982/23675455-2c0f-4942-bff0-48c38d757545)

And the web backend looks like this:
<img width="944" alt="SCR-20240131-kekv" src="https://github.com/getsentry/sentry/assets/56095982/337430bb-4231-4730-bcef-114f9ff8aaeb">

We want to update the frontend design to look **more like the the new backend design.**

- Instead of show/hide details in the top right, the Replay CTA should be dismissible with an "X" in the top right corner 
  - Dismissing ("X") will stick around for user & project level 
- The current frontend CTA has ability to both "snooze" and "dismiss" -- we'd like to implement both these behaviors for the new design as well.
  - Perhaps show these options with less prominence vs. the "set up now" button
-  After dismissing/snoozing, the whole Session Replay section goes away.

**Comment by vuluongj20** [comment]
@Jesse-Box Let's make use of our new banner design, which already has an X in the top right corner ✨ We can discuss where to place the "Snooze" button.
<img width="798" alt="image" src="https://github.com/getsentry/sentry/assets/44172267/37161385-5224-4495-ba0c-ee318356ca45">

**Comment by Jesse-Box** [comment]
@michellewzhang 

Figma: https://www.figma.com/file/vRL5LvIUMqIiCndq9J4TpB/Specs%3A-Replay-Banner-v3?type=design&node-id=1%3A50&mode=design&t=HfgixDJZrlwWxCzb-1

Illustration
![onboarding-spots-update-03](https://github.com/getsentry/sentry/assets/6508377/f63e960a-ac65-4551-9296-c3cbe8908756)
