### ISSUE TITLE
C# Code Mapping Not Working

### ISSUE THREAD

**Issue by aronbierbaum** [getsentry/sentry#64342]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Add GitHub integration for an existing project.
2. Add a mapping with Stack Trace Root "Controllers/" and Source Code Root "NotificationsAPI/Controllers/"
3. Generate an error/exception
4. Custom code that translate the `Filename` and `AbsolutePath` to replace backslashes and remove long prefixes.
5. Resulting stack trace frames have the following "filename": "Controllers/HealthController.cs" and "abs_path": "Controllers/HealthController.cs"

Could be related to https://github.com/getsentry/sentry/issues/61103

### Expected Result

Expect to see source code inline when viewing the issue.

### Actual Result

![image](https://github.com/getsentry/sentry/assets/722775/427ed1c9-1c0f-4884-85e1-5ff1953a01ff)

### Product Area

Issues - Source Maps

### Version

N/A

**Comment by malwilley** [comment]
@aronbierbaum code mappings are used for suspect commits and stack trace linking. If you want to see source code in the stack trace, see this docs page: https://docs.sentry.io/platforms/dotnet/data-management/debug-files/source-context/#source-bundles

**Comment by aronbierbaum** [comment]
@malwilley What is the difference between stack trace linking and viewing code in the stack trace? Does it mean that I should be seeing a link in the issue's stack trace that will take me to the file and line in GitHub? If that is the case I'm not seeing the links either.

**Comment by malwilley** [comment]
@aronbierbaum currently, for stack trace links to show up, you also need source context (the viewable code in the stack trace). 

We will soon release an update that will make stack traces visible regardless of source context, but until then source context is necessary.

**Comment by aronbierbaum** [comment]
@malwilley That is great news, do you have a rough estimate of when the release will happen?

**Comment by malwilley** [comment]
@aronbierbaum in the next week we should be releasing to early access users (you can set that in your org settings!), and within a month will be released to everyone. Cheers!

**Comment by aronbierbaum** [comment]
@malwilley One last question, without modifying the stacktrace before sending each event the filename and abs_path contain Windows paths. `C:\\path\\to\\code\\Controller\\SomeController.cs`. Is this handled in the code mapping, and what path format should we use in the mapping configuration?

**Comment by malwilley** [comment]
@aronbierbaum unfortunately backslashes are a known issue with code mappings: https://github.com/getsentry/sentry/issues/56115

**Comment by bruno-garcia** [comment]
Thanks for raising @aronbierbaum, mapping was recently improved for C# but I tried it out and validated it worked on Mac and Linux so seems like Windows (90% of C# developers' dev and prod environment 🙈 ) was missed. Sorry about that.
