### ISSUE TITLE
Issues from different environments are grouped together

### ISSUE THREAD

**Issue by mlarcher** [getsentry/sentry#64354]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

trigger an error from "development" env and another one from "producion" env

### Expected Result

issues are not grouped, and most importantly, Slack notifications are separated.

### Actual Result

Issues are grouped, and the first environment in which the error occurs handles the Slack notification.

In our case, we noticed than errors coming from scheduled jobs trigger at the same time on development and production environment. The development instance gets it just a bit before the production env. So the issue is created and notified to the development-errors slack channel. The same error on production env being grouped with it, it is not considered as a new error, and the prod-errors Slack notification isn't triggered.
This is very annoying, as some production errors end up being hidden because of their development equivalent.

Issues from different environment should never be grouped together (at least it should be an option to do so).

### Product Area

Alerts

### DSN

https://647d260c481c4f99bc2608c034dcf94b@o1269250.ingest.sentry.io/6458945

**Comment by scttcper** [comment]
If they should never be grouped together you might consider using different projects entirely

**Comment by mlarcher** [comment]
> If they should never be grouped together you might consider using different projects entirely

What is the point in having an "environment" variable then ? 🤷‍♂️

**Comment by scttcper** [comment]
Depends on your workflow. For some teams, an issue in staging is identical to an error in production and splitting them up would only produce more noise

**Comment by scttcper** [comment]
You might also be interested in something more like #21612

**Comment by mlarcher** [comment]
Thanks for the idea, but that does not seem very convenient for our use case.

Perhaps "for some teams an issue in staging is identical to an issue in production and splitting them up would only produce more noise", but I'm enclined to believe that it would be a large minority and an edge case. 

Alerting *needs* to depend on the environment to be relevant.

Any chance this can be considered as a feature instead of placing the burden of splitting up environments into a separate project for each instance of each project ?

**Comment by scttcper** [comment]
Added as a feature request to our backlog

**Comment by lobsterkatie** [comment]
In the meantime, [this](https://docs.sentry.io/platforms/node/usage/sdk-fingerprinting/#group-errors-with-greater-granularity) ought to do what you want:

```js
Sentry.init({
  dsn: "...",
  beforeSend: (event, hint) => {
    event.fingerprint = event.environment
      ? ["{{ default }}", event.environment]
      : ["{{ default }}"];
    return event;
  },
});
```

**Comment by mlarcher** [comment]
looking good, thanks @lobsterkatie 🙏🏻

**Comment by lobsterkatie** [comment]
Nice!

NB: I'm leaving this open in order to track the feature request to add environment to the built-in list of things you can group by using custom fingerprint rules.

**Comment by mikejihbe** [comment]
Workarounds have been posted. Closing.
