### ISSUE TITLE
Outdated Trello integration setup flow

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#64362]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

The Trello plugin (legacy integration) setup steps are outdated: https://github.com/getsentry/sentry/blob/master/src/sentry_plugins/trello/Trello_Instructions.md

The authentication method utilised is legacy and no longer supported by Trello. 

### Expected Result

Open the setup steps and being able to follow it.

### Actual Result

Steps do no match the current Trello authentication flow. 

My Trello user (workspace admin) has legacy keys and I was able to set up the integration with the following steps:
1. Go to https://trello.com/app-key
2. Copy the key in "Personal Key" and paste it on the "Trello Api Key" field in Sentry.
3. Click on "Token" to go to the token generation page
4. On the new page, click on "Allow" 
5. Copy the token from the new page and paste it on the "Trello Api Token" field in Sentry.
6. Save the Settings in Sentry.
7. Choose a board and save it again.
8. Enable the integration.

Trello users (also with admin permissions) that do not have access to legacy keys are unable to set up the integration. You can see in the screenshot that the original setup and workaround steps are not available: 
![Screenshot 2024-02-01 at 14 10 42](https://github.com/getsentry/sentry/assets/64906376/cff4d220-69cf-4a1e-951a-22f963a7a892)

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
We're adding this to our backlog, we don't have concrete timelines as to when we'll fix this but I'll keep the issue updated as I know more

**Comment by oaugustynserif** [comment]
Just wanted to say that our team is also experiencing the same. Trying to use API keys provided by the new Trello integration flow results in the following message in the Sentry UI:
> Unauthorized: either your access token was invalid or you do not have access

**Comment by iamrajjoshi** [comment]
Hello, Sentry plugins are now deprecated in favor of [Integration Platform](https://docs.sentry.io/organization/integrations/integration-platform/).
We are always open to community contributions and actively publish integrations built by the community!
