### ISSUE TITLE
[Epic] Feedback Email Notifications

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#64386]
Figma: https://www.figma.com/file/nLS7ZsjVmuSoCmEkMG5nHn/Specs%3A-Alerting-Emails-for-Feedback-v1?type=design&node-id=0-1&mode=design&t=UrGNDqACUqTn1vTp-0

**Comment by JoshFerge** [comment]
related? https://github.com/getsentry/getsentry/pull/12795

**Comment by snigdhas** [comment]
probably missing some context here, but I think my PR isn't related to this? it's a script intended to send an email to our beta customers asking for feedback on a new alert type
