### ISSUE TITLE
[User Feedback/Issues] Show a spinner with the gradient background instead of a blank placeholder when loading replay previews in all places

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#64382]
This is how it currently looks:
![Image](https://github.com/getsentry/sentry/assets/187460/593c7b07-b43f-4042-8ee2-98ffbcb60f77)

**Comment by billyvg** [comment]
Can we add a subtle animation to the placeholder instead of a spinner? We have so many spinners already when loading a page 😭

**Comment by jas-kas** [comment]
@ryan953 this isn't UF specific, this is on our Issues page

**Comment by michellewzhang** [comment]
@billyvg how opposed to the spinner are you? we don't currently have anything else in the UI that resembles the placeholder with a subtle animation (at least to my knowledge)

**Comment by billyvg** [comment]
@michellewzhang I _hate_ them -- can you talk to @vuluongj20 maybe and see how he feels? I will defer to the design team and whatever their design approach is to this. I think we are inconsistent with the usage of placeholder vs spinner anyway

And TBH I don't agree that this is even that big of an issue.

**Comment by michellewzhang** [comment]
i'll dm @vuluongj20 - he's on vacation so may be a while before we get a response

**Comment by vuluongj20** [comment]
I also don't like the spinners. @ryan953 when you said "gradient background", do you mean an animated gradient, or a static one? If it's animated then we don't need the spinner. 

I agree with @billyvg about how we're already being inconsistent in using spinner vs placeholder. In the future I'd push us toward animated placeholders and limit the use of the spinners to very specific circumstances (e.g. when a whole page is loading, not just a single component).
