### ISSUE TITLE
Need UI feedback when a tag is deleted in project settings page

### ISSUE THREAD

**Issue by bretthoerner** [getsentry/sentry#6440]
Related to #6428

I am so utterly useless at JS/React/frontend. 😊 

On this page (for example): https://sentry.io/sentry/sentry/settings/tags/

When you click a trash can (_please don't do that in production_) it sends off an XHR request to do the delete, but the user gets no feedback that the tag was deleted unless they refresh the page. I guess we should hide the row or something? I have no idea what's normal in our UI for this type of thing.

Template: https://github.com/getsentry/sentry/blob/master/src/sentry/templates/sentry/projects/manage_tags.html#L40-L41

**Comment by bretthoerner** [comment]
Apparently this page may be redone in React soon anyway.

**Comment by macqueen** [comment]
this might be easy enough to fix that it's worth doing before the conversion to react
