### ISSUE TITLE
Sentry for Jira integration

### ISSUE THREAD

**Issue by mmoitatchiou** [getsentry/sentry#64418]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

I'm trying to integrate jira to sentry but always gettings redirect to sentry.io url. How can i setup jira to my custom url ? 
I'm trying this process:
https://docs.sentry.io/product/integrations/issue-tracking/jira/#install 

Getting redirect here when 
![Capture d’écran 2024-02-01 170557](https://github.com/getsentry/sentry/assets/147549997/c73da117-a6b7-4f8f-b34d-027c91a990ac)

### How are you getting stuck?

I'm trying to integrate jira to sentry but always gettings redirect to sentry.io url. How can i setup jira to my custom url or figure out ? 
I'm trying this process:
https://docs.sentry.io/product/integrations/issue-tracking/jira/#install 

### Where in the product are you?

Settings - Integrations

**Comment by malwilley** [comment]
@mmoitatchiou if you are on self-hosted, I believe you will need to create a Jira app that points to your custom URL: https://develop.sentry.dev/integrations/jira/

**Comment by mmoitatchiou** [comment]
@malwilley thanks for following app

The first installation worked but can't finished setup, in network seems to be issue
![Capture d’écran 2024-02-06 150004](https://github.com/getsentry/sentry/assets/147549997/0475a8d9-6f08-446a-b21c-f5dde9af57c9)

The when try to uninstall reinstall got this issue.
![Capture d’écran 2024-02-06 145709](https://github.com/getsentry/sentry/assets/147549997/fb58c755-3b48-454d-88bc-d0db3ab0374c)
