### ISSUE TITLE
Unfurl links into a chart

### ISSUE THREAD

**Issue by obostjancic** [getsentry/sentry#64456]
![Image](https://github.com/getsentry/sentry/assets/9060071/fa924ca1-b4eb-4db6-bc93-1aeb03d7afc7)

We'll have to investigate how to get this into chartcuterie.

**Comment by ArthurKnaus** [comment]
This requires a bit more work that we don't want to prioritize atm as some dependencies (e.g. metrics page query params) are not stable yet.

Required work:
- Add new slack URL handler on the BE 
(see https://github.com/getsentry/sentry/blob/master/src/sentry/integrations/slack/unfurl/discover.py)
-  Register a new chartcutery config in https://github.com/getsentry/sentry/blob/master/static/app/chartcuterie/config.tsx
    - This needs a bit of cleanup in the current metrics code base as the processing of time series is split over multiple components / functions atm.

**Comment by HazAT** [comment]
We decided to move this back since the effort is higher than expected, but we keep this in the back pocket of still todo
