### ISSUE TITLE
Custom impact numbers on issue page

### ISSUE THREAD

**Issue by jboulter11** [getsentry/sentry#64466]
### Problem Statement

On the issue details page, there's no good way to get a customized impact summary.  Here's what I mean...
https://dropbox.sentry.io/issues/4600153273/events/6813bb6ecdde4ffbb256f6e7168f06e3/

If you open up any issue and I ask of you, "How many users per week is this affecting right now?" there's not a good way to get that number without either going back to issues search and filtering to just this ticket, a very annoying multi-step process, or going into discover, via the View in Discover button at the top of the issue details page.  Then, from discover, I need to select options for time and what metric I want (event or distinct user count) and finally I can see the impact in the time window I need.  Another annoying multi-step process.

Now I'll add one more: "How many users per week is this affecting right now only on version 362?"
You have to go to Issues search and narrow it down to this, then figure out how to punch in a version filter too.  Either that or again go to Discover and figure out how to add a version column to the table there.

I do like that I can set a desired table as default in Discover, so it becomes fewer clicks if I always want to answer the same question, but it would be even nicer to not have to leave the page, and even nicer still if I didn't have to instruct ever engineer before they go on call how to assess impact, because it's very much not obvious.

On Bugsnag, answering both of these questions is extremely easy to do, directly on the issue detail page.  You click the time window down to 7d and then it just gives you the impact numbers right on top.  Here's a screenshot:
![Screenshot 2024-02-01 at 12 29 16 PM](https://github.com/getsentry/sentry/assets/6633472/1342bc50-53d1-4264-83c6-21e5c25c1ce7)

To answer the second question, you simply click the version in their version of Sentry's Tags view, or set it via a dropdown, and you're given the impact numbers for the issue on that specific version easily, without leaving the page or learning how to customize a table.
![Screenshot 2024-02-02 at 8 44 48 AM](https://github.com/getsentry/sentry/assets/6633472/c724eb44-5639-4664-9316-f35e06a8b33b)
![Screenshot 2024-02-02 at 8 45 48 AM](https://github.com/getsentry/sentry/assets/6633472/099b9008-95b8-42fc-97e9-3c6c85b425cc)

### Solution Brainstorm

The solution that comes to mind for me is to allow me to apply a time filter using the existing component on other Sentry pages:
![Screenshot 2024-02-01 at 3 34 09 PM](https://github.com/getsentry/sentry/assets/6633472/0bf9c7fe-4553-484b-80c2-1af3564c174f)

and to show impact numbers for count of events and count distinct users in that time window, rather than only showing events in 24hr and 30d as well as the total count for events and users at the top right, which is restrictive and unhelpful for my use case, where I need to answer how bad it is this past week.

If this component was on the top right of the Sentry issue detail page, it could adjust what I see on the page based on my specified time window.

For filtering by the tags, another option might be that clicking a tag segment might link you directly to discover with the existing page settings set and a table showing the already specified time window and any other filters pre-applied, to minimize the steps needed.  Right now, when clicked it opens the "All Events" view with a filter applied, which, to be honest, is basically useless to me if it doesn't have aggregate numbers there.

### Product Area

Issues

**Comment by malwilley** [comment]
This is great feedback @jboulter11! 

We have been discussing potential improvements to the issue details page and this is a great use case for us. There have been some similar ideas in this discussion: https://github.com/getsentry/sentry/discussions/43531

Will put this on our backlog for now and update when we have some work planned.

**Comment by jboulter11** [comment]
Hey @malwilley could we get an update on this one, I'm getting a lot of feedback about this internally, it's making triaging issues noticeably more complicated than it was before.

Even if it's not perfect, we'd appreciate some kind of stopgap here to be able to get a users/week impact number on the issue page.

**Comment by malwilley** [comment]
@jboulter11 we haven't yet started work towards adding a feature like this to the issue page, but here is way to get some sort of user impact info from an issue:

- Click the "Open in Discover" button at the top of the issue details page
- Add a column with the value `count_unique(user)`
- Adjust the y-axis of the chart to plot the user count and adjust the interval to 7 days (or whatever interval you'd like)

I understand that this isn't the simplest process, but the it does allow you to drill down into any other properties that might be interesting. 

I'll bring this up again internally to see if we can get this prioritized, but it isn't yet on our immediate list of projects.

**Comment by rachrwang** [comment]
@jboulter11 - I'm Rachel, PM working on the issues experience. Thank you for sharing this feedback with us; the details you've noted are super helpful. We are planning for a bigger revamp of the issues experience, and making it easier to explore/understand the events within an issue is a key use case.

I don't have full visibility into timelines at the moment, given that we're still planning/ discussing within the team. If you're open to chatting, I'd love to learn more about your experience with Sentry, and how we could improve the issues experience to meet your needs better. You can reach me at rachel.wang@sentry.io, and I'd be happy to set time up for us!

**Comment by jboulter11** [comment]
Thanks @rachrwang, I sent you an email.  You can also get ahold of me in the Dropbox+Sentry Slack channel.  Ask Jeff Van Earwage to add you, if you can't see it in Slack. :)
