### ISSUE TITLE
[User Feedback - Spam] Determine if we can use Vertex AI python library

### ISSUE THREAD

**Issue by michellewzhang** [getsentry/sentry#64488]

**Comment by JoshFerge** [comment]
info here: https://cloud.google.com/python/docs/reference/aiplatform/latest

may be able just just the `aiplatform` gcp library -- may not need to install vertex

**Comment by michellewzhang** [comment]
We don't need to install Vertex AI library. We can just directly make a HTTP request to the endpoint
