### ISSUE TITLE
Possibility to set cap per recognised issue to prevent unnecessary charges

### ISSUE THREAD

**Issue by r-dev-limited** [getsentry/sentry#64521]
### Problem Statement

Sentry correctly process error -> generate issue.
Then correctly for every other same issue, increases count of that issue.
Trouble is that after certain point it just doesnt make sense. 
For example, knowing that in past hour one issue happened over 1k times, from one env is more then enough to understand that this issue is serious, most likely infinite loop type of issue. And passing charge to sentry customer, using up all quota is not helpful.

### Solution Brainstorm

Add another module similar to inbound filters
Where you can per env specify max cap.
So if same issue happens more than selected cap, it will get ignored -> no more increasing count and processing, charging

### Product Area

Settings - Spike Protection

**Comment by Dhrumil-Sentry** [comment]
@r-dev-limited thanks for this feedback. You can implement a simple rate limiter for your top issues on the client side itself. But we have no plans to build this in the near to mid term.
