### ISSUE TITLE
Jira integration Date Time Picker custom field always throws "The <field name> must be a string"

### ISSUE THREAD

**Issue by vzarskus** [getsentry/sentry#64538]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

In Jira:
1. Create a custom field that is of type Date Time Picker.
2. Add the custom field to some project's issue type. Make it required.

In Sentry:
1. Got to an issue ant try to create a Jira card for it via Jira integration.
2. Fill in all the fields, including the Date Time one. For the Date Time field you may try setting the value from this Jira example page: https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#creating-an-issue-examples
6. Get an exception "The `your field name` must be a string".

### Expected Result

Jira issue gets created in the board.

### Actual Result

Here is the result of trying to create a Jira card via Sentry. The endpoint throws "The Bug start date must be a string". "Bug start date" is the name of our custom Date Time field.
![image](https://github.com/getsentry/sentry/assets/60877312/e41b7ef3-276f-47e5-a4c5-da634839ed9b)

### Product Area

Settings - Integrations

### Link

https://eldorado-tm.sentry.io/issues/4936726247/?environment=prod&project=1402798&query=is%3Aunresolved+is%3Aunlinked&referrer=issue-stream&statsPeriod=24h&stream_index=0

### DSN

https://d538900ebe0b4d888e0d64b4f58fd428@us.sentry.io/1402798

**Comment by Dhrumil-Sentry** [comment]
@vzarskus Sentry does not support custom required fields in our Jira integration: https://docs.sentry.io/product/integrations/issue-tracking/jira/#cant-create-issues-using-a-custom-required-field

From your screenshots it looks like the custom field you added is a required field

**Comment by vzarskus** [comment]
Got it, thank you.
Are there any plans to support custom required fields in the future?

**Comment by devatlantis** [comment]
@Dhrumil-Sentry but you do support custom required fields.

From the screenshot you can see that we have a custom required text field and a custom required dropdown which both work. The only issue seems to be with the date time picker.

**Comment by Dhrumil-Sentry** [comment]
@devatlantis If other custom required fields work as in your case, its a more a lucky coincidence rather than something we intentionally support. 

I'll add this request to our backlog but we're unlikely to get to this item in the next 2 quarters

**Comment by devatlantis** [comment]
Thanks for the info!

Any recommended workarounds in the meantime?

**Comment by GabeVillalobos** [comment]
Closing this at it has been addressed in the related issue: https://github.com/getsentry/sentry/issues/71911. This should now be fixed.
