### ISSUE TITLE
Design: Multi-series charts and formulas in Dashboards

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#64545]
**Problem**: Today we only support single series charts and no formulas, this is the major gap identified through dogfooding compared to Datadog.

**Solution**: Add support for multi-series charts (e.g. plot p50, p99) and formulas (e.g. A/B) in the Metrics Explorer and Dashboards.

![Image](https://github.com/getsentry/sentry/assets/26696515/1285945e-e63a-43ca-9bc1-b1b0316c8870)

**Dashboards**
- Exploration for Dashboards
  - verify if we can keep a basic inline widget creation/edit + modal for more complex actions like formulas and multi-series
  - modal always - opportunity to consolidate the different datasets back into one widget building experience

**Comment by Jesse-Box** [comment]
Writing some notes here @ale-cota 

Since we agreed that the inline editor can't support these features, we need to factor in some time to understand how the improved dashboard custom metric widget builder will function. Provided that the UI must be the same.
