### ISSUE TITLE
[Bug] Missing Replays on User Feedback Details

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#64573]
Examples in `sentry`:

- https://sentry.sentry.io/feedback/?feedbackSlug=javascript%3A4946279181&project=11276&referrer=feedback_list_page&statsPeriod=14d

- https://sentry.sentry.io/feedback/?feedbackSlug=javascript%3A4931610418&project=11276&referrer=feedback_list_page&statsPeriod=14d

**Comment by ryan953** [comment]
https://sentry.sentry.io/feedback/?feedbackSlug=javascript%3A4946279181&project=11276&referrer=feedback_list_page&statsPeriod=14d has a tag for this replay:
```
 "replay": {
            "replay_id": "08f65bc4d472417ebb4be0338085a859",
            "type": "default"
        },
```
when i go to load it, it doesn't load: https://sentry.sentry.io/replays/08f65bc4d472417ebb4be0338085a859/?project=11276&query=&referrer=%2Freplays%2F&statsPeriod=30d&yAxis=count%28%29

**Comment by ryan953** [comment]
The 2nd example: https://sentry.sentry.io/feedback/?feedbackSlug=javascript%3A4931610418&project=11276&referrer=feedback_list_page&statsPeriod=14d

is tagged with this replay:
```
        "replay": {
            "replay_id": "a7fcc2b504d34db296f2c7293bd47f28",
            "type": "default"
        },
```

Trying to view that directly also doesn't work: https://sentry.sentry.io/replays/a7fcc2b504d34db296f2c7293bd47f28/

**Comment by ryan953** [comment]
I'm thinking we should close this. It's possible for replays to not have been saved, i think this is the case here.
