### ISSUE TITLE
Sort by ascending or descending on the issue stream

### ISSUE THREAD

**Issue by polga** [getsentry/sentry#64572]
### Problem Statement

I'd love to be able to more easily see Issues that have just recently started.

### Solution Brainstorm

Sort by ascending or descending on the issue stream.

### Product Area

Issues

**Comment by scttcper** [comment]
The "For Review" tab is currently sorted by Date Added by default. This would be the order in which they arrive / became regressed / became escalating. It is limited to the issues from the last 7 days and marking things reviewed will remove them. [See this page for more](https://docs.sentry.io/product/issues/states-triage/)
