### ISSUE TITLE
Error in dependency psycopg2

### ISSUE THREAD

**Issue by dzubchik** [getsentry/sentry#6461]
When trying to install sentry through pip I get an error. It was [fixed](https://github.com/psycopg/psycopg2/issues/594) in 2.7 version, but sentry requires psycopg2<2.7
```
(env) sentry@vps452072:/usr/lib/sentry$ pip install sentry==8.20
Collecting sentry==8.20
  Downloading sentry-8.20.0-py27-none-any.whl (19.4MB)
    100% |████████████████████████████████| 19.4MB 54kB/s 
Collecting click<7.0,>=5.0 (from sentry==8.20)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting enum34<1.2.0,>=0.9.18 (from sentry==8.20)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting redis-py-cluster<1.4.0,>=1.3.4 (from sentry==8.20)
  Using cached redis_py_cluster-1.3.4-py2.py3-none-any.whl
Collecting setproctitle<1.2.0,>=1.1.7 (from sentry==8.20)
  Using cached setproctitle-1.1.10.tar.gz
Collecting celery<3.1.19,>=3.1.8 (from sentry==8.20)
  Using cached celery-3.1.18-py2.py3-none-any.whl
Collecting mmh3<2.4,>=2.3.1 (from sentry==8.20)
  Using cached mmh3-2.3.1.tar.gz
Collecting djangorestframework<2.5.0,>=2.4.8 (from sentry==8.20)
  Using cached djangorestframework-2.4.8-py2.py3-none-any.whl
Collecting pytest<3.2.0,>=3.1.2 (from sentry==8.20)
  Using cached pytest-3.1.3-py2.py3-none-any.whl
Collecting PyYAML<3.12,>=3.11 (from sentry==8.20)
  Using cached PyYAML-3.11.zip
Collecting sqlparse<0.2.0,>=0.1.16 (from sentry==8.20)
  Downloading sqlparse-0.1.19.tar.gz (58kB)
    100% |████████████████████████████████| 61kB 7.6MB/s 
Collecting rb<2.0.0,>=1.7.0 (from sentry==8.20)
  Using cached rb-1.7-py2-none-any.whl
Collecting psycopg2<2.7.0,>=2.6.0 (from sentry==8.20)
  Using cached psycopg2-2.6.2.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    Error: could not determine PostgreSQL version from '10.0'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vjvmMC/psycopg2/
```

**Comment by dcramer** [comment]
Sounds ike somethings wrong with your system, but its not a bug in Sentry.

**Comment by dcramer** [comment]
Actually I missed the first line. We might be able to bump the dep. @mattrobenolt  ?

**Comment by mattrobenolt** [comment]
> Error: could not determine PostgreSQL version from '10.0'

You're trying to compile against libpq for postgres 10. We definitely don't work with pg 10 and require postgres 9. I'm not sure what ramification this has on libpq though if the backing database is still 9.x.

But given that, I swore I tried an update to 2.7 and it caused test failures. I'd be willing to try again though.

For now, I'd just say you should compile against libpq 9.x instead of 10 since that's a whole other can of worms.

**Comment by dzubchik** [comment]
@mattrobenolt , thank you! Will try to fix this downgrading libpq

**Comment by dzubchik** [comment]
I leverage postgres packages and it is okay now.
```
- name: Install correct versions of postgres packages
  apt:
    name: "{{item}}=9.6.5-1.pgdg16.04+2"
    state: present
    force: true
  with_items:
    - libpq5:amd64
    - libpq-dev
```

**Comment by mattrobenolt** [comment]
Yeah, that's way better. Postgres 10 very unlikely wouldn't have worked anyways. :)

**Comment by ztane** [comment]
... and this should be reopened...

**Comment by mattrobenolt** [comment]
We're going to address this now because the base Travis CI image update is causing this to break for us now. Ugh.

https://github.com/getsentry/sentry/pull/6746

So we're going to try to upgrade psycopg2 to 2.7 tomorrow and see if the world burns down.

**Comment by jeromelefeuvre** [comment]
Always have problem with this with sentry 8.22.0 ? Anything ?

**Comment by dcramer** [comment]
You should pin the dependency for psycopg2. It doesn't require a change to Sentry to force this AFAIK. We'll likely support new psycopg2 in a future version (Q1), but we dont consider this a high priority for customers.

**Comment by mattrobenolt** [comment]
The problem is the libpq dependency on the host fwiw. So pinning back libpq to a 9.x version is what needs to be done.

**Comment by ztane** [comment]
it is impossible to pin back libpq as it is pulled to 10 if the host uses anything related to Pg10.

**Comment by dcramer** [comment]
@ztane then downgrade Postgres as 10 isn’t supported by us yet.

**Comment by tomelliff** [comment]
@dcramer There's a few issues asking about Postgres 10 support either directly/indirectly (all seem to be closed). Is there something on the road map for supporting Postgres 10 or will there be an announcement when it is supported? It sounds like it's theoretically possible now that psycopg2 has been updated but I'm wary of moving over to it with comments in issues saying it that it's basically untested right now.

Not sure it's worth creating a new issue/feature request for it if it's just that you guys will only be happy signing off on Postgres 10 when you move sentry.io over.

**Comment by mattrobenolt** [comment]
The latest release, Sentry 9.0 has newer psycopg2 so it’ll compile against libpq10.

We have no immediate plans to directly support running against Postgres 10, but in all likelihood it’ll work. We just haven’t tried and don’t run it ourselves. 

If you’d like to try it out, I don’t anticipate any real issues. We will probably never run pg10 ourselves in production. :)
