### ISSUE TITLE
Pivotal Tracker 400 bad request: Error communicating with Pivotal Tracker

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#64642]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Enabled the Pivotal Tracker for a project in Project Settings Legacy Integrations
2. Try to create a new issue from Sentry in Pivotal

### Expected Result

The pivotal issue is created 

### Actual Result

Get the following response:
```
400 bad request:
{
"error_type": "validation",
"errors": {
"__all__": "Error communicating with Pivotal Tracker"
}
}
```

As this issue is affecting a specific organisation more details are available in the [shadow ticket](https://getsentry.atlassian.net/browse/FEEDBACK-2092). 

### Product Area

Settings - Integrations

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2092) by [Unito](https://www.unito.io)

**Comment by leedongwei** [comment]
We can keep this open to see if anyone has the same issue. For now, it seems to be a likely to be a setup/config issue on the user's side.

**Comment by esetnik** [comment]
I am still experiencing this issue. I've tried re-setting up the integration several times.

**Comment by leedongwei** [comment]
@esetnik What's the error message that you're seeing?

**Comment by esetnik** [comment]
> @esetnik What's the error message that you're seeing?

Error communicating with Pivotal Tracker

However it's since gone away. I believe it actually may be related to outages happening on the PivotalTracker side https://status.vmware-services.io/incidents/ybgx3shq02kp

**Comment by esetnik** [comment]
> @esetnik What's the error message that you're seeing?

Error communicating with Pivotal Tracker

However it's since gone away. I believe it actually may be related to outages happening on the PivotalTracker side https://status.vmware-services.io/incidents/ybgx3shq02kp

**Comment by leedongwei** [comment]
Gotcha. Thanks for the update! 

I'll close this out for now. Feel free to reopen if it's a issue on Sentry's side.
