### ISSUE TITLE
[Slack integration] Alert that sends to slack no longer works and testing / saving the alert rules throws 500 err

### ISSUE THREAD

**Issue by mvannes** [getsentry/sentry#64652]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Configure an alert for a project with the slack integration that makes use of the following;
1.1  A WHEN that says "Send a notification to the {our-workspace} Slack workspace to {our-channel-name} (optionally, an ID: {our-id}) and show tags {environment,user} in notification
2. Send a TEST notification OR Save the alert rules. 
3. Get a notice that says "An error has occured". 
4. Inspect the network tab, and do it again to see that https://us.sentry.io/api/0/projects/donna-service-organisatie/tijd-weg-diagram/rule-actions/ has failed with a 500 status code. This gives an error code that says `{"detail":"Internal Error","errorId":"ccaba86d160d46728e0106764b9624fc"}`

OR;
1. have an existing alert that is configured with the above information
2. Trigger issues that match the alert condition
3. The alert fires (according to the graph at the alert info for that alert)
4. Nothing is shown in the slack channel that the alert was configured for.

 

### Expected Result

The alert is saved, and existing alerts send messages to slack when they trigger

### Actual Result

I am unable to edit and save existing/new alerts that make use of the slack integration due to 500 errors in the system, and existing alerts for multiple different channels appear to never reach slack. 

### Product Area

Alerts

**Comment by Dhrumil-Sentry** [comment]
@mvannes we think this issue was recently fixed, is it still happening for you?

**Comment by mvannes** [comment]
Sorry for the late response on my part, yes this seems to have been fixed the day you responded. Thank you so much for the fast response!
