### ISSUE TITLE
Add new SDK API for capturing User Feedback without event_id (new format) https://develop.sentry.dev/sdk/features/#user-feedback

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#64698]
Today if someone wanted to write a UF Widget on a new SDK (say: iOS or Android) they'd need to reverse engineer the JS SDK.

Please expand the develop docs with API/envelope format and any other significant details (tracing?) needed.

**Comment by aliu39** [comment]
This is live as `captureFeedback`: https://docs.sentry.io/platforms/javascript/user-feedback/#user-feedback-api
