### ISSUE TITLE
Daily / Weekly Reports

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#647]
We want to support interval-based daily digests. We would support both daily and weekly intervals. These would exist per-project.
### Summary of stats
- Resolved issues
- Unresolved issues
- Total events
- Users affected
- User reports
- Releases
### Frequency chart
- # of events combined with # users affected
### Top lists
- Most impactful events (ideally a formula of events + users affected, worst case just events)
- New events (sorted by impact/frequency)
## Potential Additions
- Tag breakdown (browser, server, release)
- Hot code paths

**Comment by afelle1** [comment]
@dcramer Yeah I think this would be really useful and imagine @josephmc5 will agree

**Comment by josephmc5** [comment]
Very interested. @dcramer is there anything in the works for this? It's something I may be interested in contributing if there isn't something already out there.

**Comment by rakanalh** [comment]
I am almost done with writing most of the code for this. I also created the HTML mail template. I still have to:
1) Create the bar graph using HTML & CSS
2) Pass data to the template for rendering

So... it's coming soon i hope.

**Comment by dcramer** [comment]
@rakanalh btw feel free to open a PR even if the code isn't done. It's useful to get early feedback and we can just keep it open until things are good

**Comment by rakanalh** [comment]
Will do, i just need to finish up the above 2 points to have something useable at the very least.

**Comment by josephmc5** [comment]
@rakanalh thank you for sharing! It looks really interesting.

**Comment by dcramer** [comment]
Updating this to latest thoughts.

Of note, ideally we can solve the top lists here and for the dashboard at the same time. Additionally being able to provide top lists for organizations would be valuable on getsentry.com

**Comment by j-fernandes** [comment]
Hello, any updates on this? Will this be put into an integration or part of the mainstream app soon

Cheers

**Comment by dcramer** [comment]
When it is done it'll be in Sentry's core. Right now its not an active project, but we've laid some groundwork w/ recent features.

**Comment by j-fernandes** [comment]
Awesome! Thanks for the update :)

**Comment by wesleyk** [comment]
@dcramer Any update or ETA on this feature? Thanks!

**Comment by sam-cook** [comment]
Any progress on this feature? This is a great idea, my team would really benefit from this.

**Comment by tkaemming** [comment]
We've been working on this and testing it for early adopters on [sentry.io](http://sentry.io). We'll likely release it there first and then have it enabled by default in the on-premise release within the next version or two.

**Comment by rosskmurphy** [comment]
@tkaemming Any possibility of getting access as an early adopter on sentry.io?

**Comment by tkaemming** [comment]
Early adopter features can be enabled by your organization administrators in the organization settings:

![screenshot 2016-09-06 11 37 41](https://cloud.githubusercontent.com/assets/65315/18286003/a5f91b14-7425-11e6-8739-08374f46cc8a.png)

**Comment by rosskmurphy** [comment]
Thank you, this is awesome. Will the report send automatically or is it configured?

**Comment by tkaemming** [comment]
These are sent automatically on Mondays at 12:00 UTC at the moment (not configurable.)

**Comment by tiny-dancer** [comment]
Updates on this feature?

**Comment by DanLirette** [comment]
This would be useful work our company. Would be a nice feature to have!

**Comment by MaxBittker** [comment]
@tiny-dancer @DanLirette these exist now, have you been getting them?

**Comment by estebanefi** [comment]
Any way of making this report be daily?

**Comment by caiolopes** [comment]
Any way of making this report be send to a slack channel too?
