### ISSUE TITLE
Cannot setup development environment

### ISSUE THREAD

**Issue by max-wittig** [getsentry/sentry#6474]
### I tried to setup the development environment for sentry, but I think there are some problems in the setup

* Clean clone from commit https://github.com/getsentry/sentry/commit/2adce3434847abb6435a5699f679e5dd68718a1f

* Setup development environment installation method https://docs.sentry.io/server/installation/python/#installing-from-source

* ``` python 2.7.13  ```

* ``` pip 9.0.1 ```

* Stacktrace
<pre>
creating /tmp/easy_install-JPXQef/symbolic-1.1.0/.eggs/pycparser-2.18-py2.7.egg
Extracting pycparser-2.18-py2.7.egg to /tmp/easy_install-JPXQef/symbolic-1.1.0/.eggs

Installed /tmp/easy_install-JPXQef/symbolic-1.1.0/.eggs/pycparser-2.18-py2.7.egg
error: Setup script exited with error: [Errno 2] No such file or directory
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/tmp/easy_install-JPXQef/symbolic-1.1.0/setup.py", line 59, in delete_scratchpad
  File "/usr/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/tmp/easy_install-JPXQef/symbolic-1.1.0/temp/tmpNG6VCM'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/tmp/easy_install-JPXQef/symbolic-1.1.0/setup.py", line 59, in delete_scratchpad
    __import__(m)
  File "/usr/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/tmp/easy_install-JPXQef/symbolic-1.1.0/temp/tmpNG6VCM'
</pre>

* This happens with and without the virtualenv

**Comment by mitsuhiko** [comment]
Are you on arch linux?

**Comment by max-wittig** [comment]
I'm using debian 9 stable

**Comment by max-wittig** [comment]
Any updates on this @mitsuhiko

**Comment by mitsuhiko** [comment]
Yes, we are catching down this error now down in symbolic 1.1.1. This means you should get a better error message. However I'm not sure why your server attempts to manually compile symbolic to begin with. We distribute wheels. Maybe your version of pip is too old?

**Comment by mitsuhiko** [comment]
(Normally only archlinux users should run into the issue that wheels are unavailable, or users with heavily outdated pip)

**Comment by mitsuhiko** [comment]
Oh also more importantly: do not run this: `python setup.py develop`

Instead run

`pip install --editable .`

**Comment by max-wittig** [comment]
So the development documentation would need to be updated, right?
https://docs.sentry.io/server/installation/python/

**Comment by BYK** [comment]
We now have an extensive guide for this: https://develop.sentry.dev/environment/
