### ISSUE TITLE
Vue onboarding docs encourage you to set up Source Maps 2x

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#64772]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which SDK are you using?

@sentry/vue

### SDK Version

latest

### Steps to Reproduce

This is a small issue, but I notice that during Vue onboarding, we ask the user to set up source maps even though the docs have already guided the user to upload source maps?

![image](https://github.com/getsentry/sentry-javascript/assets/2153/5202260e-d8e7-44f5-80d9-997109a761e6)

### Expected Result

Probably shouldn't occur 2x.

### Actual Result

Probably shouldn't occur 2x.

**Comment by ArthurKnaus** [comment]
Thx for the issue! Fix will be out soon 🙌
