### ISSUE TITLE
JIRA Issue Link Settings in Alerts don't save

### ISSUE THREAD

**Issue by gid-sentry** [getsentry/sentry#64784]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Click “issue Link Settings” in the “Then” section
2. Scroll down to “Labels” and paste “InsertLabel-Here”
3. Hit Apply Changes
4. Hit Save Rule at the bottom of the page
5. Refresh the page, and notice that “Labels” is still empty

### Expected Result

Labels field gets saved

### Actual Result

“Labels” is still empty

### Product Area

Alerts

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2094) by [Unito](https://www.unito.io)

**Comment by GabeVillalobos** [comment]
I believe this has been addressed via #79043, which fixes a bug with issue link settings not populating unless they were a choice or search/autofill field.
