### ISSUE TITLE
Unable to fetch commits: Error Communicating with GitHub (HTTP 503): unknown error

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#64854]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Install the Github Integration
2. Create a new release 
3. Try to associate commits to this new release.

### Expected Result

All commits are associated with release. 

### Actual Result

User gets the email with the message above and commits are not associated with release. 

Reports show user using different tools to associated commits: Sentry GHA and sentry-cli directly. 

[Linked to this issue.](https://sentry.sentry.io/issues/4277777414/events/latest/?project=1&referrer=latest-event)

### Product Area

Settings - Integrations

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2097) by [Unito](https://www.unito.io)

**Comment by leedongwei** [comment]
Seems to be a user-specific error because they've hit their API limits with Github.
