### ISSUE TITLE
Timestamp of a release should be per environment

### ISSUE THREAD

**Issue by oliworx** [getsentry/sentry#64865]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Using `sentry-laravel`, in order to inform Sentry about a new release on deployment, I built a deployment hook, that basically sends a message to Sentry:  
  `app('sentry')->captureMessage('New release deployment', Sentry\Severity::info());`
3. I deploy release XY at 1pm to the staging environment to test it
4. Then I deploy the same at 3pm to the production environment

### Expected Result

Time of a release should be per environment.

So for the production environment the release time should be 3pm

### Actual Result

The Sentry UI shows the release XY was deployed at 1pm, for both, the staging and the production environment.

![image](https://github.com/getsentry/sentry/assets/1712684/56b81c30-75ee-4a69-ade0-4eb6ddae7447)

![image](https://github.com/getsentry/sentry/assets/1712684/7b8c2569-bb3f-44ed-a82b-97236b99497e)

### Product Area

Releases

### Link

https://envivo.sentry.io/releases/768f81de/?environment=production&project=6004810

**Comment by lobsterkatie** [comment]
Hi, @oliworx.

I think what you're looking for is a [deploy](https://docs.sentry.io/product/releases/setup/#notify-sentry), which is the association of a release (which is just our record that that version of your code exists, regardless of environment) with an environment. (I get that the distinction can be a little confusing, given that you can filter session data about a release by environment, as you've done in the screenshots above. But deploys are where metadata about the release-environment combo lives.)

When you use deploys, that information is displayed at the top and bottom of the righthand sidebar on the release details page:

![image](https://github.com/getsentry/sentry/assets/14812505/740343d4-60ae-4754-8f42-040d81147ebf)

(In this example, both deploys are listed as having happened 6 hours ago, but if you hover over those timestamps you get more specific timestamps.)

**Comment by oliworx** [comment]
@lobsterkatie Thank you for the explanation. So I will try to setup releases for our projects.

**Comment by oliworx** [comment]
Got release deploys working now:
![image](https://github.com/getsentry/sentry/assets/1712684/3a3b9c34-a5c4-4da4-ab93-b503a9529e43)
