### ISSUE TITLE
Phabricator API Request Error

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#64867]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Add the Phabricator integration to your Sentry Organization
2. Pick an issue from the project you connected the integration for, and click on "Phabricator Issue"

### Expected Result

We should be able to create or link issues with Phabricator.

### Actual Result

Doing so creates a 500 status code in: <html><head></head><body>
GET | https://us.sentry.io/api/0/issues/4904317791/plugins/phabricator/autocomplete?autocomplete_field=tags&autocomplete_query=
-- | --
</body></html>

with response:<html><head></head><body>
error_type | "unknown"
-- | --
</body></html>

If we click on "Create issue", we get a 400 status code in:<html><head></head><body>
POST | https://us.sentry.io/api/0/issues/4904317791/plugins/phabricator/create/
-- | --
</body></html>

with response:<html><head></head><body>
error_type | "validation"
-- | --
errors | Object { __all__: "ERR-CONDUIT-CALL ERR-CONDUIT-CALL: Method 'maniphest.createtask' belongs to application 'Maniphest', which is not installed." }
__all__ | "ERR-CONDUIT-CALL ERR-CONDUIT-CALL: Method 'maniphest.createtask' belongs to application 'Maniphest', which is not installed."
</body></html>

This created [this replay in Sentry's Sentry](https://sentry.sentry.io/replays/437291f30678473eb616361758fa27e3/?project=-1&query=id%3A%22437291f30678473eb616361758fa27e3%22&referrer=%2Freplays%2F&statsPeriod=14d&t_main=errors&yAxis=count%28%29).

### Product Area

Settings - Integrations

**Comment by leedongwei** [comment]
We will likely deprecate Phabricator in the near future.
