### ISSUE TITLE
Allow configuring global defaults for crons

### ISSUE THREAD

**Issue by mikicz** [getsentry/sentry#64881]
### Problem Statement

We've just started using crons in Sentry at Xelix - and it's a great feature, but it's a bit noisy right now, and making not as noisy is a lot of manual work (especially since we have some dynamic cron jobs)

It is possible to set the `Grace Period` / `Max Runtime`, and `Failure Tolerance` / `Recovery Tolerance` per cron and it defaults to some values - I would love to change the default values, i.e. set the default grace period to five minutes on all my crons, instead of the current default one minute.

I've searched all the docs, and I have not found a way to do this within the UI. It's possible this is doable with some configuration on the server (we're on-premise), but it would be nice to set the defaults in the UI.

### Solution Brainstorm

I'd love a page in the settings (per project probably?) that sets the default values for `Grace Period` / `Max Runtime`, and `Failure Tolerance` / `Recovery Tolerance`

### Product Area

Crons

**Comment by gaprl** [comment]
Hey @mikicz, thank you for your feedback. I do recommend taking a look at our [upsert functionality](https://docs.sentry.io/product/crons/getting-started/http/#creating-or-updating-a-monitor-through-a-check-in-optional). Basically, it allows you to configure or update your monitor directly through a check-in payload. Most of our SDKs support this now.

**Comment by hillam** [comment]
The fact that max_runtime is _optional_ but has a non-configurable default is _quite_ misleading. I might even go so far as to call it a bug.
