### ISSUE TITLE
Organization stats page for metrics shows all zero

### ISSUE THREAD

**Issue by vartec** [getsentry/sentry#64917]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. go to Sentry for Sentry
2. click on _"Stats"_
3. choose _"Sentry"_ project
4. choose category _"Metrics"_ 

### Expected Result

Actual metric usage statistics

### Actual Result

All values are zero
![All zero metric stats](https://github.com/getsentry/sentry/assets/2284726/b5268c51-e9fa-4b3f-a3d3-5d5fb5deecec)

### Product Area

DDM

### Link

https://sentry.sentry.io/stats/?dataCategory=metric_buckets&project=1&statsPeriod=7d

### DSN

sentry4sentry

**Comment by iambriccardo** [comment]
For now, we are going to kill the page, until we know better which numbers we want to show.
