### ISSUE TITLE
Increase Replay max billing option beyond 1M

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#64929]
The system can ingest a lot more and [request for 1.5M came through Twitter](https://twitter.com/devgummibeer/status/1755763391526773118)

![image](https://github.com/getsentry/sentry/assets/1633368/41921fd7-fe05-47f0-b738-134ce319940e)

**Comment by jas-kas** [comment]
Update: working with Theresa to increase SS slider to 10M.

**Comment by bruno-garcia** [comment]
it's live: https://twitter.com/cleptric/status/1760477748844200192
