### ISSUE TITLE
Get onto React 16

### ISSUE THREAD

**Issue by MaxBittker** [getsentry/sentry#6495]
Upgrade sentry to React 16.

- [x] Move all components from DropdownLink to DropdownReact
- [x] move to react-dom standalone
- [ ]  create-react-class standalone + class codemod
- [ ] upgrade jest + enzyme 
- [ ] upgrade eslint
- [ ] upgrade or patch react router 2.8.1 (it relies on react internal proptypes)
- [ ] ???

**Comment by billyvg** [comment]
Do we need to move to DropdownReact? Wasn't the issue just project/assignee selector because it was doing weird stuff to try to have the bootstrap dropdown to be more controlled by parent?

**Comment by MaxBittker** [comment]
good point, we might not need to

**Comment by MaxBittker** [comment]
partial list of package.json  changes we need to make:
https://gist.github.com/MaxBittker/853c6fb0f2f502df3a34781569db2c3d

**Comment by MaxBittker** [comment]
:D
