### ISSUE TITLE
Modify chart granularity in Metrics Explorer

### ISSUE THREAD

**Issue by HazAT** [getsentry/sentry#64989]
## Problem ##

When zooming into counter data (sum operation) the y axis values change dramatically pho 

Multiple options:
1. the bucket granularity being available as a variable in formulas
2. a dedicated per_second aggregation function as a shortcut to dividing the metric by the bucket granularity

[Original thread - Markus](https://sentry.slack.com/archives/C05TB55ETN1/p1707126351415479)

I would like to see a "per-second" aggregation option so that when I zoom in and out of this graph, the y-axis does not change. Currently this graph, zoomed out to 24h, reads like "600k iterations per 5 minutes", and when further zoomed in like "100k iterations per 20 seconds", and I think that's too much math in my head. I want the "per N seconds" to always be the same N
https://sentry.sentry.io/dashboard/77810/?project=300688&statsPeriod=24h

![Image](https://github.com/getsentry/sentry/assets/26696515/6d295b6e-a8ff-4a91-85a3-b21e05c07bd6)
![Image](https://github.com/getsentry/sentry/assets/26696515/545c4dff-211a-4ec9-a933-4b0fc6703864)

## Proposed Solution ##

- Add a global selector that defines chart granularity in the Metrics explorer page.
- There is a minimum available granularity based on the time interval selected (our current defaults)

**Comment by ale-cota** [comment]
We have a few more customer inquiries about the possibility to customise this time interval and there is also an old issue

- https://www.notion.so/sentry/Control-over-x-axis-on-dashboards-and-discover-660fcfc9adc04371946caf6de0e8c1bd
in this case the customer would like the time interval to be 1 month (so they can see a trend month/month)
- https://github.com/getsentry/sentry/issues/36204 (more generic)

**Comment by ArthurKnaus** [comment]
closed in https://github.com/getsentry/sentry/pull/67775
