### ISSUE TITLE
Sentry dashboard not showing API tokens

### ISSUE THREAD

**Issue by dltacube** [getsentry/sentry#65030]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. log in to Sentry
2. Click "settings" in the sidebar
3. Under "developer settings" click "Auth Tokens"

I checked the audit log and there are no traces of any individual in my org deleting any tokens.

### Expected Result

To see a list of API tokens.

### Actual Result

"You haven't created any authentication tokens yet."

### Product Area

Settings - Developer Settings

**Comment by dltacube** [comment]
I guess this might be a duplicate of issue 1939

**Comment by sentaur-athena** [comment]
@dltacube the issue you mentioned as duplicate is fixed recently. Are you still experiencing this?

**Comment by dltacube** [comment]
> @dltacube the issue you mentioned as duplicate is fixed recently. Are you still experiencing this?

No, it looks like I'm able to see our tokens in the dashboard as well as use them. Thank you!
