### ISSUE TITLE
[Issues] Custom search, sort parameter not respected when opening URL directly

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#65047]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

**Description**
When you set up a custom search in the issue stream and then adjust the sorting criteria (such as Priority, Events, Users, etc.), if you open the URL in a new tab, the issues are not correctly sorted according to the chosen sort option. This seems to only happen when "searches" is included in the URL path.

**Steps to reproduce:**
1. Create a custom search (Users) -> https://sentry.sentry.io/issues/searches/5581065/?referrer=issue-list&sort=user&statsPeriod=7d
2. Change sort criteria -> https://sentry.sentry.io/issues/searches/5581065/?referrer=issue-list&sort=freq&statsPeriod=7d
<img width="387" alt="Screenshot 2024-02-12 at 4 06 46 PM" src="https://github.com/getsentry/sentry/assets/8451987/98a806b5-a0b9-44f8-989a-d28ff7e36d24">

3. Open same URL in a separate tab -> sort no longer applied

### Expected Result

Sorted events to be applied when opening in a new tab or window

### Actual Result

Sort is no longer respected

### Product Area

Issues

**Comment by roggenkemper** [comment]
Hmm, i can't seem to reproduce it. Just to make sure I'm doing the right thing - I have the issue stream open, i click sort by users,  then i sort by events, and then copy that URL into another tab? my url at that points has the right sort and the issue stream loads as expected.

**Comment by MichaelSun48** [comment]
Closing this due to >6 months with no response - feel free to reopen if this is still an issue.
