### ISSUE TITLE
Define Limits Per Project

### ISSUE THREAD

**Issue by Brandon0** [getsentry/sentry#65087]
### Problem Statement

We have had a project in the past introduce an error (or false escalation of an error) that can go on to consume the entire org's error quota. This leads to other projects being unable to log errors the rest of the billing cycle.

We had hoped Spend Allocation would allow this (upgraded our account specifically for this), but it only defines the minimum number of errors to _reserve_ for a project. This feature would be the reverse of that (define a maximum number of errors to allow for a project).

### Solution Brainstorm

Allow defining a limit (either as a number of a percentage of total) to the quantity of errors that can be logged, per project. This way out of control projects will become automatically filtered out, before the org's total quota is consumed, and thereby without affecting the other projects as much.

### Product Area

Settings - Spend Allocation

**Comment by Dhrumil-Sentry** [comment]
Thanks for sharing this feedback but we don't plan on introducing such controls at the project level.

**Comment by sdzhong** [comment]
Internal tracking https://www.notion.so/sentry/1ad8b10e4b5d80c18d46ee2c851964f5
