### ISSUE TITLE
How to disable sentry while debugging?

### ISSUE THREAD

**Issue by danieldelouya** [getsentry/sentry#6509]
While I test my React Native app in debug mode, get new issues while i test my app and occasional errors are thrown. How can i disable that and only allow it to track release builds?
Thanks

**Comment by dcramer** [comment]
If you set the DSN to an empty value it should disable any SDK.

**Comment by c100k** [comment]
Actually it does not work anymore with `react-native-sentry@^0.38.3`

```js
Sentry.config('').install();
```

==>

```js
Possible Unhandled Promise Rejection (id: 0):
Error: Project ID path component of DSN is missing
Error: Project ID path component of DSN is missing
```

Any way to do it ?

Thanks

**Comment by likern** [comment]
The correct way to do it:
```ts
if (!__DEV__) {
  Sentry.init({
    dsn:
      'PUT_VALID_DSN'
  });
}
```
Errors happen while debugging will not be sent to sentry.

**Comment by dcramer** [comment]
The correct way to disable Sentry is to pass a false-y DSN. If that doesn't work please open a new ticket so we can address it, as we'd consider it a bug.
