### ISSUE TITLE
[Feature Request] Custom Saved Search for Teams

### ISSUE THREAD

**Issue by michaelchai-sentry** [getsentry/sentry#65096]
### Problem Statement

Right now in Sentry, custom saved searches are either only visible to the individual user or to the entire organization. A customer of ours was requesting that we add a middle ground, perhaps a category of custom saved searches that are "visible to my team". The reasoning behind this ask is that searches available to the whole org seem to be too open, and they don't want a ton of searches for every team in the global namespace either.

### Solution Brainstorm

Custom saved searches that are available at the team level

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2102) by [Unito](https://www.unito.io)

**Comment by rachrwang** [comment]
@michaelchai-sentry - do we have any examples for what the saved search contains? Would love to see some examples if they're available

**Comment by michaelchai-sentry** [comment]
@rachrwang yup it's just a combination of different issue filters that is relevant to an individual, or in this case, team. i've provided an example from our demo org :) let me know if this wasn't what you were looking for
<img width="904" alt="Screenshot 2024-02-13 at 10 43 29 AM" src="https://github.com/getsentry/sentry/assets/98921471/3c61ae5a-6358-454f-88c3-b93c9f6a9a18">

**Comment by MichaelSun48** [comment]
Closing this out since custom searches is being deprecated in favor of [Issue Views](https://docs.sentry.io/product/issues/issue-views/).  We're currently considering how to make issue views more sharable, and will consider this feedback in our discussion.
