### ISSUE TITLE
Chart doesn't show on dashboard

### ISSUE THREAD

**Issue by discover59** [getsentry/sentry#65103]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Select project and go to issues page

### Expected Result

Before it showed bar charts on each error aggregated by hour.

### Actual Result

Now I cannot see previous chart(GRAPH section) anymore. It shows on my other sentry project.
![image](https://github.com/getsentry/sentry/assets/16558427/4dc43c66-ba01-4382-8a84-59db9087aa5f)

### Product Area

Issues

### Link

https://sentry.io/issues/

**Comment by malwilley** [comment]
Following up here - we reverted the change so now the chart is displayed at the same window size as it was before.
