### ISSUE TITLE
Trending issues count not updated when time duration changed in Overviews Tab

### ISSUE THREAD

**Issue by ndmanvar** [getsentry/sentry#6511]
Steps to reproduce:
- Go to 'Overview' tab of project
- change time period (1 hour, 1 day, 1 week)
- Expected result: Graph and Trending/New issues should be updated accordingly.
  Actual result: Only graph is updated

See GIF:
![overview-issuesnotupdate](https://user-images.githubusercontent.com/314061/32390522-f902685c-c08b-11e7-8eab-aadf1fce054f.gif)

**Comment by harshil562** [comment]
I am interested to pick this issue.
Can I start working on it ?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
