### ISSUE TITLE
Configured Gitlab project missing from Issue Creation Dropdown

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#65135]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Trying to enable a particular GitLab project to appear when generating a GitLab issue from the Issue Tracking panel of an issue.

### How are you getting stuck?

After configuring the relevant code mapping, the GitLab project does not appear. This might be a misconfiguration or a potential defect.

### Where in the product are you?

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2111) by [Unito](https://www.unito.io)

**Comment by kpujjigit** [comment]
"When we attempt to create a new Gitlab issue from an existing issue in a Sentry project that’s mapped to a given repo, the repo does not appear in the drop down of options."

What is needed to populate the list of available GitLab Projects?

**Comment by leedongwei** [comment]
Can you link the Zendesk ticket? I can't seem to find it.

**Comment by sdzhong** [comment]
> Can you link the Zendesk ticket? I can't seem to find it.

What Zendesk ticket are you looking for?

**Comment by Dhrumil-Sentry** [comment]
@sdzhong I think @leedongwei is referring to the jira ticket with the org's details and details about the issue and repo where the problem occurs

**Comment by sdzhong** [comment]
Understood. @leedongwei, I've added the `Sync: Jira` label to this GitHub Issue; you can find the Jira Improvement ticket associated.

**Comment by leedongwei** [comment]
Responded in Jira.
