### ISSUE TITLE
Server-Side Data Scrubbing picks up website domains

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#65142]
### Problem Statement

If we have a website or email that includes once of [these fields](https://docs.sentry.io/product/data-management-settings/scrubbing/server-side-scrubbing/) in its name, the Server-Side data scrubbing will pick it up and Filter it.

For example, if I set the following:
``` javascript
  Sentry.setUser({ email: "john.doe@mywebsiteauth.com", first_name: "John", last_name: "Doe" });
  Sentry.addBreadcrumb({
    category: "xhr",
    data: {
      "method": "GET",
      "status_code": 200,
      "url": "https://mywebsiteauth.com",
    },
    type: "http"
  });
```

The event will show up in Sentry like this:
<img width="853" alt="image" src="https://github.com/getsentry/sentry/assets/81985895/3cd0b9d5-f360-4186-8289-c5d04a106338">
<img width="296" alt="image" src="https://github.com/getsentry/sentry/assets/81985895/3df74593-4be1-41d0-be97-5a2a5f5ec045">

This can hide a lot of crucial information for customers who have these strings in their domain names.

### Solution Brainstorm

While it is possible to add these strings into the safe fields, or disable server-side data scrubbing completely, customers might not want this because it would disable filtering on actually sensitive information. It might be better to prevent this filtering if we detect the string is included inside a domain name.

### Product Area

Settings - Security & Privacy

**Comment by iker-barriocanal** [comment]
In this case, using the safe fields is the best choice.

Currently, we don't have a way to disable scrubbing for domain names, and adding heuristics for this feature in multiple places of the protocol could result in false positives and PII data ending up in storage. Feel free to reopen the issue or open a new one if there's something I'm missing.
