### ISSUE TITLE
More java generated proxy class patterns

### ISSUE THREAD

**Issue by jpsyri** [getsentry/sentry#6514]
This is somewhat related to the #6283. I have few additional generated/proxy class patterns that mess up with automated stack grouping:

1. Apache cfx generated webservice client ('rengashinnat' is the name of the proxied method)

    `   
     at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:138)
     at com.sun.proxy.$Proxy15555.rengashinnat
    `
2.  Weld proxy
    `
    at sun.reflect.GeneratedMethodAccessor2408.invoke
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    `

**Edit** On further look 2. seems to be already handled, but think 1 is still an issue.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
