### ISSUE TITLE
 Send alert notifications to custom emails

### ISSUE THREAD

**Issue by 2008mga** [getsentry/sentry#6515]
I’m trying to configure alerts for my project and I noticed that in action section I have only either
Send a notification (for all enabled services)
OR
Send a notification via Mail

What I’d like to have is to configure custom email addresses for different alert rules… But I can’t find such option. Is they a way to do so?

**Comment by dcramer** [comment]
Sentry doesn’t allow you to send alerts to arbitrary addresses. I don’t know that this will change in the near term as it’s intended to be a collaboration tool.

**Comment by idlesign** [comment]
Hi, @dcramer 

Correct me if I get it wrong: if one has a mailing list address to send alerts to, this very person needs to register this address as his own, or a separate account is required. If so, it seems strange.

**Comment by dcramer** [comment]
@idlesign it’s less strange when you disconnect sentry from what you know wa monitoring. We focus on a workflow and part of that is ownership. Historically alerts are a crucial part of telling an individual about an issue affecting their code.

**Comment by idlesign** [comment]
Got it, will tie that public list to my account. 
Thank you.

**Comment by havenchyk** [comment]
@dcramer and is it an expected behavior if sentry doesn't send a verification email to a "group of emails"?
