### ISSUE TITLE
Some Org Owners are receiving permissions error when trying to reset 2FA for their users

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#65155]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

This has been reported by multiple users but has not been reproducible by me using either my test org, or Superuser access.  I am attaching more information in [linked Jira ticket](https://getsentry.atlassian.net/browse/FEEDBACK-2104), with a screenshot that shows the issue.

In some situations, when an Owner goes to reset the 2FA of a user in their org, they receive a permissions error.  This makes the button unclickable and leaves the owner unable to reset a user's 2fa and leaves them locked out of Sentry.

**Error They See -**
<img width="336" alt="Screenshot 2024-02-14 at 9 43 47 AM" src="https://github.com/getsentry/sentry/assets/96670625/67530dc6-4fb0-4950-869b-3c4932fe4620">

The button seems to only be greyed out for certain users.  For the org I took a look at, it's possible that it's greyed out only for users with the Member role, while users with Admin role could still be reset.

### Expected Result

Owners do not see permissions error when attempting to remove 2FA

### Actual Result

Owners see that error in certain conditions.

### Product Area

Settings - Security & Privacy

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2104) by [Unito](https://www.unito.io)

**Comment by schew2381** [comment]
I checked the code where this is happening but couldn't find any recent changes or anything that stands out to me. Would you have any more example orgs where this is happening for debugging? I checked the org that reported this in the Jira ticket but it appears to have already been reset

**Comment by Danw33** [comment]
@schew2381 We're also seeing this on our org `gambit-nash` if it helps debug - My role is "Owner", this is whilst trying to reset 2FA of a user with "Member" role:

<img width="1188" alt="Screenshot 2024-02-15 at 11 22 35" src="https://github.com/getsentry/sentry/assets/5680603/3c678890-89d0-49b7-a7c5-db531d1a6696">

If at all relevant:
- `Settings > Security & Privacy`: `Require Two-Factor Authentication` is currently OFF
- `Settings > Auth` is configured for SSO via Google Workspace

**Comment by Fwang36** [comment]
hey @schew2381,

I updated the jira with a couple of other orgs that reported this issue within the past week.  I also added some extra information provided to me by the org that I reported originally.

@Danw33,
I am curious if Managers also see this issue.  Do you have access to a Manager role user account that you can test to see if they also see a permissions error?  Both Managers and Owners should be able to remove the 2FA.

**Comment by schew2381** [comment]
Hey everyone just wanted to leave a quick update on this issue. I've managed to reproduce the bug, but am still working toward the root cause of it. Will post more updates here as I go along

**Comment by schew2381** [comment]
@Danw33 @Fwang36
The bug should be fixed now, please let me know if there's any more issues with it!
