### ISSUE TITLE
Release marker tooltip on 'Overview' for projects don't make sense in the timeline. 

### ISSUE THREAD

**Issue by MeredithAnya** [getsentry/sentry#6517]
Example:

Tooltip for marker shows Oct. 30, 2017
![screen shot 2017-11-06 at 9 28 59 am](https://user-images.githubusercontent.com/15368179/32454741-f8c3c48a-c2d4-11e7-8b73-d445735c07b3.png)

Value right after marker:
![screen shot 2017-11-06 at 9 31 09 am](https://user-images.githubusercontent.com/15368179/32454847-4604695c-c2d5-11e7-98a9-0f0000c92bfe.png)

cc @getsentry/workflow

**Comment by MaxBittker** [comment]
this was partially fixed in https://github.com/getsentry/sentry/pull/6530 but still needs a filter to filter markers from before the start of the graph (currently works when time is set to one week i think)
