### ISSUE TITLE
Be able to get a users events - not just search for events affecting the user

### ISSUE THREAD

**Issue by tarjei** [getsentry/sentry#6519]
- The version of Sentry you're using
8.13
- Whether you're using Docker or another installation method
From python. 

I know I can search for user:someId, but when I do this, I want to be able to get links to the events registered on _that_ user so that I can see things like breadcrumbs and browser version for that users interaction. 

Now I just get 10 events with no indication wrt which of the events have happened for my specific user the last hour f.x..

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
