### ISSUE TITLE
[User Feedback] Prevent the Comments text area from taking focus when the Feedback Details page is rendered

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#65215]
Repro steps:
1. Visit `/feedback/` (no query params)
2. Notice that no feedback is loaded by default, "No feedback selected" on the right side
3. Click to load and render a feedback
4. Notice that the "Post Comment" text area has focus, the Feedback Details area is scrolled down. ❌ 
5. Click outside the text area, scroll up to the top of the Feedback details area
6. Click to load and render a 2nd feedback
7. Notice same as step 4 ❌ 
8. Repeat step 5 (click outside the textarea. scroll up)
9. Click to re-load the 1st feedback, from step 3
10. Notice how loading is quicker, the text area does not get focus. ✅ 

I believe steps 4 and 7 are taking focus because the text area is being rendered "new" after the feedback loading placeholder is removed. 
In the case of step 10 there is no loading placeholder, we read from the cache and switch which feedback is rendered, react re-uses the existing dom nodes.

**Comment by ryan953** [comment]
@michellewzhang I believe you fixed this, correct?

**Comment by michellewzhang** [comment]
https://github.com/getsentry/sentry/pull/66799 yup, this should've fixed it!
