### ISSUE TITLE
Transfer organization between users

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#6524]
It's possible to do this today – if your organization supports > 1 member. Just invite a new member with owner-level permissions, then remove your own membership.

But sentry.io free-tier organizations can't have more than 1 member, so pulling this off is tricky. It would be great to have a way to transfer an entire organization to a different user.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
