### ISSUE TITLE
Jira Integration Problem

### ISSUE THREAD

**Issue by mrede-rf** [getsentry/sentry#65242]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

The Jira side of the integration is failing.
I have installed the app in Jira.
I can link issues from Sentry to a ticket in Jira (or create a new one)
But I cannot see the linked issue on the Jira side which in fact just shows an error in the Sentry linked issue panel (after a few minutes of showing nothing but whitespace)

To recreate for me:
Install the Jira app as normal
Configure sentry when Jira prompts you to

Note: The Jira sentry app always prompts me to "Finish installation in sentry" (which I have tried multiple times)

 

### Expected Result

I should be able to see linked tickets in Jira and if I update the ticket in Jira it closes in sentry

### Actual Result

![2  Jira errors when showing linked ticket](https://github.com/getsentry/sentry/assets/137216176/cd975aef-e261-45ec-b3a8-e9703fc8a2c6)
<img width="388" alt="1   Ticket linked to Jira ok" src="https://github.com/getsentry/sentry/assets/137216176/15584035-1dfe-49bd-a3ab-8e039e590866">

### Product Area

Other

**Comment by leedongwei** [comment]
Thanks for the bug report! I'll have the team take a closer look.

**Comment by mrede-rf** [comment]
Hey, it turned out to be an overzealous ad blocker. Sorry should have
closed this off
