### ISSUE TITLE
Team names are currently truncated at 30 characters. Increase to 50.

### ISSUE THREAD

**Issue by khfayzullaev** [getsentry/sentry#65249]
### Problem Statement

It seems that I am facing an issue with the Sentry API Create Team where the team slug cannot exceed 30 characters in length. I am interested in exploring whether there is a way to override this limitation, as I need team slugs that are longer than 30 characters. It looks like the exact naming convention for the team slug isn't explicitly defined in the provided documentation.

### Solution Brainstorm

If it is possible, it would be nice to increase the limit, and document that at least in the API Reference. For example, https://learn.microsoft.com/en-us/azure/devops/organizations/settings/naming-restrictions?view=azure-devops has good examples. 

### Product Area

Settings - Teams

**Comment by Dhrumil-Sentry** [comment]
Thanks a lot for this feedback, we'll add this to our backlog and keep this issue updated

**Comment by RyanSkonnord** [comment]
Team slugs can now be up to 50 characters long.
