### ISSUE TITLE
Track Deletions

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#6527]
Right now the only tracking we have around deletions is via logging. This is fine for a lot of things, but we'd like to keep records in the database of every deleted organization, project, and user, and make those searchable.

**Comment by mattrobenolt** [comment]
In addition to the AuditLogEntry records?

**Comment by dcramer** [comment]
@mattrobenolt Do those not just instantly get deleted? But yes, in addition to those.

**Comment by mattrobenolt** [comment]
They should on Organization deletion, but we've hit this catch-22 before as well. We log org deletion into the AuditLogEntry, but then can't look at the AuditLogEntry record to get information about it.

Tangentially, I'd argue that we should expand on this AuditLogEntry behavior to support all of this, and decouple it from Organization deletion. We've also wanted to track AuditLogEntry records that aren't paired to an organization, like, individual events. Change password, etc, which doesn't fit in with current model.

**Comment by dcramer** [comment]
The audit log is intended for the organization only (nothing more). It serves the purpose well enough, and trying to reuse it for other things will likely over complicate it.

What we need is historical records of who/what/when was deleted for critical paths so customer support (or system operators) can identify when things happen without digging into logs.

**Comment by dcramer** [comment]
We want to track:

- User ID whom deleted the object
- Timestamp
- slug/identifying details based on the type (e.g. org.slug, org.id, project.slug, project.id)

We likely want to start with this for both Organization and Project.

**Comment by mattrobenolt** [comment]
> User ID whom deleted the object

I think we should track also the state of the User at the time, in case the User is deleted too? Maybe we just have a `data` JSON field to stuff in whatever arbitrary metadata to go with it like we do in AuditLogEntry?

**Comment by dcramer** [comment]
Maybe we should track DeletedUser as well? The concern is I **think** we can't hold email addresses forever, so the DeletedUser would have to be limited to the User ID anyways.

It's also important to note we are going to want to query this information, so JSON fields are not ideal here. I would stick to a rigid schema per model.

**Comment by dcramer** [comment]
Oh last bit, it might make sense to track a 'reason' on deletions.

e.g. account closure, user requested, something like that

**Comment by lauryndbrown** [comment]
So just to summarize: We want three tables  DeletedUser, DeletedProject, and DeletedOrganization with the intent to search the data. There is no general data field containing json; that's currently how auditlogs appear to be implemented.

**Comment by benvinegar** [comment]
Refs #6629
