### ISSUE TITLE
Subject emails show ${tag:..} when event triggering email doesn't have specified tag

### ISSUE THREAD

**Issue by MeredithAnya** [getsentry/sentry#6529]
Example:

<img width="678" alt="screen shot 2017-11-09 at 10 24 11 am" src="https://user-images.githubusercontent.com/15368179/32622592-32e9787a-c538-11e7-98fe-7c1786c3e79e.png">

Maybe we can make the default we omit tag values in the subject title that aren't present?

**Comment by krasnopolsky** [comment]
Hey all - curious if there are any plans to address this?

**Comment by tkaemming** [comment]
I'm a little hesitant to just omit them/replace them with an empty string since that could lead to confusing formatting (e.g. in this case `Meredith Ruby Integration v (development) - …`) but I don't really have any alternatives in mind at this point either.

**Comment by MeredithAnya** [comment]
@tkaemming what if we add to the description where you set the subject title an example of what it looks like when tag doesn't exist? Just to set expectations.

**Comment by tkaemming** [comment]
No real opinion one way or another. We could also replace the missing item with one that signifies the value is empty, but I haven't put much thought into what a good one would be.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
