### ISSUE TITLE
Can't specify "(Default Environment)" as the default environment

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#6531]
In project settings, if "Default Environment" is left blank, it seems not to actually default to "(Default Environment)" as it appears in the UI.

Blank value:

![image](https://user-images.githubusercontent.com/2153/32683657-ba2ac092-c631-11e7-9291-0361ee1409fe.png)

Defaults to "production":

![image](https://user-images.githubusercontent.com/2153/32683658-c4763252-c631-11e7-83be-c306f510a738.png)

**Comment by benvinegar** [comment]
@lynnagara – I'd probably look at this one last.

**Comment by roginator** [comment]
Just wondering if this is still on the radar?

**Comment by mnpenner** [comment]
Also, "Dev" is showing in there twice for us, and those barcharts don't seem to relate to the selected environment which is super confusing because the dropdown is immediately above them.

![image](https://user-images.githubusercontent.com/1112998/34747836-be920496-f54e-11e7-977d-cfd2e2a4f5ee.png)

**Comment by lynnagara** [comment]
Yeah, we're looking at doing a larger revamp of environments at the moment, including updating the charts and merging environments.

**Comment by lynnagara** [comment]
Environment names are currently case-sensitive - so it's possible you are sending 'dev' + 'Dev' for example in your data. It's not evident by looking at the dropdown though since the UI is title casing the names.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
