### ISSUE TITLE
Using an Object for 'exception.values[0].type' causes web page exceptions

### ISSUE THREAD

**Issue by iccir** [getsentry/sentry#6532]
I sent the following event to the official sentry.io server – notice that 'exception.values[0].type' is accidentally an `object` instead of a `string`.

```
{"dist":"net.musictheory.Site-2086","release":"Site-2086","platform":"javascript","extra":{"Original Input":"https://www.musictheory.net/vs/public/095095e46b3c4de2a52721b458a2f688/input.json"},"contexts":{"app":{"app_name":"Site","app_identifier":"net.musictheory.Site","app_version":"2086"}},"exception":{"values":[{"type":{"name":"-[TenutoBannerModalView dismiss]","filename":"TenutoBanner.oj","line":301,"path":"Web/UI/Base/TenutoBanner.oj"},"value":"NotFoundError: The object can not be found here.","stacktrace":{"frames":[{"function":"-[TenutoBannerModalView dismiss]","package":"TenutoBanner.oj","lineno":301}]}}]},"request":{"url":"http://www.musictheory.net/exercises/note","headers":{"User-Agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 (KHTML, like Gecko) Version/10.0 Mobile/14D27 Safari/602.1"}},"event_id":"095095e46b3c4de2a52721b458a2f688","sdk":{"name":"net.musictheory.veritas","version":"1"},"timestamp":0}
```

I received an e-mail alert from Sentry with the event. However, when I tried to view the event in my web browser ([link to the now-deleted event](https://sentry.io/musictheorynet/site/issues/402959488/)), the page wouldn't load. In addition, any page which listed this event failed to load.

It looks like exceptions where being throw in the Web Console (React errors?).

I had to manually delete the event via a `DELETE` request to `/api/0/issues/402959488/` in order to restore access to my organization's page.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
