### ISSUE TITLE
Inbound Filters not filtering TypeError Issue

### ISSUE THREAD

**Issue by DeadSuperHero** [getsentry/sentry#6534]
I have a Sentry.io project with __Inbound Filters__ set to filter out TypeError exceptions. The filter looks like this:

```
TypeError*
TypeError ("" + (new Date(...))).match(...) is null
TypeError: node.className.indexOf is not a function
QuotaExceededError: The quota has been exceeded.
```

However, the project I'm looking at has two recurring issues that keep coming in:

```
TypeError render in this
error("" + (new Date(...))).match(...) is null
```

and

```
QuotaExceededError [native code] in setItem
error The quota has been exceeded.
```

**Comment by tkaemming** [comment]
Neither of these issues have a `Message` interface.

As written, this filter test doesn't reject the message: https://github.com/getsentry/sentry/blob/13ab6682a4fbe2b14f1d33e9974c6eee9265e333/src/sentry/coreapi.py#L403-L407 https://github.com/getsentry/sentry/blob/13ab6682a4fbe2b14f1d33e9974c6eee9265e333/src/sentry/utils/data_filters.py#L97-L112

If we want to support this for the exception message (not just the literal `Message` interface), we'll need to update this to check those different attribute.

**Comment by tkaemming** [comment]
I'm going to make this more aggressive (include the exception type/value as part of the filterable content, etc.) because it's demonstrably confusing and may have been more appropriate to implement that way in the first place
