### ISSUE TITLE
Missing samples with when using sentry_sdk.metrics.timing()

### ISSUE THREAD

**Issue by danielkhan** [getsentry/sentry#65396]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

```python
with sentry_sdk.metrics.timing(key="api_call_duration"):
  response = requests.get(url)
```

### Expected Result

Samples are shown in the samples table in DDM.

### Actual Result

![Capto_Capture 2024-02-16_02-28-32_PM](https://github.com/getsentry/sentry/assets/2722161/ea9e064c-c959-4de0-a05b-33eec9ab6b1f)

### Product Area

DDM

### Link

https://sentry-test.sentry.io/ddm/?multiChartMode=0&project=4506755435397120&statsPeriod=7d&widgets=%5B%7B%22mri%22%3A%22d%3Acustom%2Fapi_call_duration%40second%22%2C%22op%22%3A%22sum%22%2C%22query%22%3A%22%22%2C%22displayType%22%3A%22line%22%2C%22powerUserMode%22%3Afalse%2C%22sort%22%3A%7B%22order%22%3A%22asc%22%7D%7D%5D

**Comment by HazAT** [comment]
https://sentry-test.sentry.io/performance/summary/spans/metric.timing:2fa9a18a1ee4d889/?project=4506755435397120&query=http.method%3AGET&statsPeriod=14d&transaction=index

**Comment by iambriccardo** [comment]
The problem is that sentry-test is on AM1 and we do not support span-level summaries there.
