### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by kapso** [getsentry/sentry#65399]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

It never works, I cannot get a repo to connect to Sentry??

### Expected Result

It should work

### Actual Result

nothing happens, after I go through the workflow of connecting GitHub auth

### Product Area

Dashboards

### Link

https://tradespace-io.sentry.io/

**Comment by leedongwei** [comment]
Can you share which page/step that the set up errors out?

**Comment by cathteng** [comment]
Closing this issue. Feel free to reopen if you're still experiencing this.
