### ISSUE TITLE
Timeseries with empty tag is being populated along with a tagged series

### ISSUE THREAD

**Issue by danielkhan** [getsentry/sentry#65395]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

```python
@app.route('/')
def index():
    global toggle
    choice = request.args.get('choice', '')
    url = f"http://localhost:{'3010' if toggle < 3 else '3020'}?choice={choice}"
    
    try:
        with sentry_sdk.metrics.timing(key="api_call_duration"):
            response = requests.get(url)
        # Increment or reset the toggle based on its current value
        toggle = toggle + 1 if toggle < 3 else 0
        
        // ******* Increments metric with a response status code
        metrics.incr("api_call", 1, tags={"response_code": response.status_code})
        if response.status_code > 299:
            # If there is an error with the request, respond with the error
            return jsonify(error='Something went wrong!'), response.status_code
        return response.json()
    except requests.exceptions.RequestException as e:
        # Handle connection errors
        // ******* Increments metric with a response status code = 500
        metrics.incr("api_call", 1, tags={"response_code": 500})
        return jsonify(error=str(e)), 500
```

### Expected Result

This should create N timeseries with one for each status code that is emitted.
In my example it is either 500 or 200.

### Actual Result

3 time-series are created: 

* `response_code = (none)`
* `response_code = 200`
* `response_code = 500`

where the values in `(none)` are identical to those in `200`.

![Capto_Capture 2024-02-16_05-38-37_PM](https://github.com/getsentry/sentry/assets/2722161/86d4132a-bc12-42f0-88ea-2e218192af37)

### Product Area

DDM

### Link

https://sentry-test.sentry.io/ddm/?multiChartMode=0&project=4506755435397120&statsPeriod=7d&widgets=%5B%7B%22mri%22%3A%22c%3Acustom%2Fapi_call%40none%22%2C%22op%22%3A%22sum%22%2C%22query%22%3A%22%22%2C%22groupBy%22%3A%5B%22response_code%22%5D%2C%22displayType%22%3A%22bar%22%2C%22powerUserMode%22%3Afalse%2C%22sort%22%3A%7B%22order%22%3A%22asc%22%7D%7D%5D

**Comment by iambriccardo** [comment]
I wasn't able to figure out the problem. Will bring this ticket up again in case more people encounter this error.

**Comment by obostjancic** [comment]
Tried to reproduce with the following simplified version of the snippet above
```python
app = Flask(__name__)

# randomly returns either 200 or 500 
def get_response():
  import random

  if random.randint(0, 1) == 0 :
    return {"status_code": 200}

  raise Exception("Internal Server Error")

@app.route('/')
def index():
    try:
        with sentry_sdk.metrics.timing(key="api_call_duration"):
            response = get_response()

        sentry_sdk.metrics.incr("api_call", 1, tags={"response_code": response['status_code']})
        if response['status_code'] > 299:
            # If there is an error with the request, respond with the error
            return jsonify(error='Something went wrong!'), response['status_code']
        return jsonify(response), 200
    except Exception as e:
        # Handle connection errors
        # ******* Increments metric with a response status code = 500
        sentry_sdk.metrics.incr("api_call", 1, tags={"response_code": 500})
        return jsonify(error=str(e)), 500
```

Got expected results, no empty tags and a rough 50/50 split between 200 and 500 status codes
![Image](https://github.com/getsentry/sentry/assets/86684834/7ff0afc3-b715-405f-9673-aa628c2b6e2e)
