### ISSUE TITLE
error: bad json: invalid type: map, expected a string at line 1 column 327

### ISSUE THREAD

**Issue by flightknight22** [getsentry/sentry#65402]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I'm trying to upload my source maps to Sentry on ubuntu but get an error and can't get more information with log-level=debug

Here's more of the log:

 ''' DEBUG   2024-02-19 22:22:40.559324031 -06:00 ignoring ./CHANGELOG.md: Ignore(IgnoreMatch(Types(Glob(UnmatchedIgnore))))  (from ignore)
  DEBUG   2024-02-19 22:22:40.559339042 -06:00 ignoring ./favicon.ico: Ignore(IgnoreMatch(Types(Glob(UnmatchedIgnore))))  (from ignore)
  DEBUG   2024-02-19 22:22:40.559353573 -06:00 ignoring ./package-lock.json: Ignore(IgnoreMatch(Types(Glob(UnmatchedIgnore))))  (from ignore)
  DEBUG   2024-02-19 22:22:40.559381771 -06:00 ignoring ./test/specs/test.e2e.ts: Ignore(IgnoreMatch(Types(Glob(UnmatchedIgnore))))  (from ignore)
  DEBUG   2024-02-19 22:22:40.559402108 -06:00 ignoring ./.gitignore: Ignore(IgnoreMatch(Types(Glob(UnmatchedIgnore))))  (from ignore)
> Found 77295 files
> Analyzing 77295 sources
> Analyzing completed in 9.804s
> Rewriting sources
error: bad json: invalid type: map, expected a string at line 1 column 327
  INFO    2024-02-19 22:22:58.492176583 -06:00 Skipping update nagger update check'''

### How are you getting stuck?

"sentry-cli sourcemaps inject --org revel-digital --log-level=debug --project universal-player ./ && sentry-cli sourcemaps upload --org revel-digital --project universal-player ./ --log-level=debug"

Causes the above error

### Where in the product are you?

Issues - Source Maps

**Comment by loewenheim** [comment]
Hi, thank you for your report. Can you upload the sourcemaps after injection or email them to me at sebastian.zivota@sentry.io?
