### ISSUE TITLE
Trace view "Limited to a view of 1 rows" instead of 100

### ISSUE THREAD

**Issue by codegain** [getsentry/sentry#65448]
### Self-Hosted Version

23.11.2

### CPU Architecture

x86_64

### Docker Version

23.0.1

### Docker Compose Version

2.16.0

### Steps to Reproduce

1. Use distributed tracing accross 2 projects
2. Ensure `sentry-trace` and `baggage` are sent via HTTP
3. Ensure other systems use `continueTrace`

### Expected Result

1. Link `View full trace` is shown on issue
2. Trace view lists all traces from all projects (access granted to both projects - issues are visible)

### Actual Result

Trace View shows only trace from project from which the issue was opened and limits view to "1 row":

![image](https://github.com/getsentry/self-hosted/assets/11192306/0559326a-507a-40dd-b063-01041e5eb1c7)

Full trace can be viewed in Discover, but I would like to increase this limit which should be 100 according to https://docs.sentry.io/product/sentry-basics/concepts/tracing/trace-view/#transaction-view

Is there any config value which needs to be changed?

**Comment by Abdkhan14** [comment]
Hey @codegain , thank you for reaching out. I will be taking a look at this and will be keeping you updated.

**Comment by codegain** [comment]
@Abdkhan14 This may got fixed in a newer version of sentry. I upgraded to 24.2.0 and now I see all rows.

**Comment by k-fish** [comment]
@codegain glad to hear it it's fixed! I'm going to close this with a recommendation for anyone else seeing this to upgrade to `24.2.0`+ 👍
