### ISSUE TITLE
UI Bug: Alert in Performance > Queries is in 1 cell of 6-column grid, when it should span the entire width size

### ISSUE THREAD

**Issue by DAcodedBEAT** [getsentry/sentry#65458]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create new sentry project
2. Visit `Performance > Queries`

### Expected Result

Alert should be readable and spread across the size of the div (is the CSS grid even necessary?)

### Actual Result

<img width="1483" alt="image" src="https://github.com/getsentry/sentry/assets/5031018/ce01d5a0-a313-4cee-b5cc-ea972109a4ed">

### Product Area

Performance - Queries

**Comment by gggritso** [comment]
@DAcodedBEAT thanks for raising this, fix is on the way!
