### ISSUE TITLE
Feature Request: Add “git blame” like prefix to each source code line

### ISSUE THREAD

**Issue by guettli** [getsentry/sentry#6547]
It would help the communication between the operators and the developers a lot if sentry could show "git blame" for each source code line of a stacktrace.

Up to now it takes some time for the operator (which uses sentry) to find the developer who could be responsible for this stacktrace.

If every source code line would have "changed on .. by ... in commit ..." prefix, this would help the operators a lot.

Can you understand this feature request? 

What do you think - or am I on the wrong track and there is an easier solution?

**Comment by dcramer** [comment]
We are working on something we're calling 'Owners', which aims to solve this problem. It's not what you're asking for, but it will point you to the commit/pull request/likely owners of an issue. We have an early version of it live already, but the rest will come as part of Sentry 9 (https://github.com/getsentry/sentry/issues/5741)
