### ISSUE TITLE
'Resolve' button should say 'Unresolve' when selected issues are resolved

### ISSUE THREAD

**Issue by saragilford** [getsentry/sentry#6553]
Usability issue around resolving/un-resolving issues in the Issues view. Currently, user can resolve multiple issues by clicking the resolve button. If the user then selects some of the resolved issues and clicks the 'Resolve' button again to undo the change, nothing happens. Rather, the option to unresolve is hidden within the ellipsis menu as 'Set status to: Unresolved'.

A solution would be to make the text on the 'Resolve' button read 'Unresolve' when only resolved issues are selected, and to set the corresponding status when clicked.

An additional note: when the user selects all issues in view and clicks 'Resolve', a pop-up modal alerts them that 'This action cannot be undone.' This is false -- either we should remove the modal or provide directions within the modal of how to unresolve issues.

Steps to repro:

1. Navigate to Issues view.
1. Select a few exceptions to resolve, then click the 'Resolve' button
1. Select the same exceptions to un-resolve, then click 'Resolve' again.

OR

1. Navigate to Issues view.
1. Search only resolved issues.
1. Select all resolved issues, then click Resolve.
1. Confirm 'Cannot be Undone' modal.
1. Select all resolved issues to unresolve, then click Resolve.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
