### ISSUE TITLE
[Replay Details] Update name for `sdk.errorSampleRate` in Replay Details > Tags to `sdk.onErrorSampleRate`

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#65618]
"onErrorSampleRate" is more specific than "errorSampleRate" (errorSampleRate can be conflated with what we use for Sentry errors)

**Comment by mydea** [comment]
Instead, let's change this in the SDK to name these `sdk.replay.XXX` instead - this is actually where this comes from, and internally the option is called `errorSampleRate`. And if this was called `sdk.replay.errorSampleRate`, it should also be clearer!

**Comment by jas-kas** [comment]
@c298lee @billyvg wdyt of francesco's suggestion?

**Comment by c298lee** [comment]
sounds good to me!

**Comment by billyvg** [comment]
Yeah that seems fine, I would say we should change this on the frontend instead so we don't have to deal with compatibility:

Current:

| Old | New |
| --- | --- |
| sdk.blockAllMedia | sdk.replay.blockAllMedia |
| sdk.errorSampleRate | sdk.replay.errorSampleRate |
| sdk.maskAllInputs | sdk.replay.maskAllInputs |
| sdk.maskAllText | sdk.replay.maskAllText |
| sdk.networkCaptureBodies | sdk.replay.networkCaptureBodies |
| sdk.networkDetailHasUrls | sdk.replay.networkDetailHasUrls |
| sdk.networkRequestHasHeaders | sdk.replay.networkRequestHasHeaders |
| sdk.networkResponseHasHeaders | sdk.replay.networkResponseHasHeaders |
| sdk.sessionSampleRate | sdk.replay.sessionSampleRate |
| sdk.shouldRecordCanvas | sdk.replay.shouldRecordCanvas |
| sdk.useCompression | sdk.replay.useCompression |
| sdk.useCompressionOption | sdk.replay.useCompressionOption |
| sdk.name | sdk.name |
| sdk.version | sdk.version |
