### ISSUE TITLE
There is no valid electron symbol debug file in self hosted sentry

### ISSUE THREAD

**Issue by theremoon-j** [getsentry/sentry#65668]
### Self-Hosted Version

23.12.1

### CPU Architecture

amd64

### Docker Version

25.0.2

### Docker Compose Version

2.24.5

### Steps to Reproduce

create a electron project in a new self hosted sentry, report a crash but cant find debug file. However the same case can find correct file by the same way in sentry.io.

### Expected Result

Same result like sentry.io
![image](https://github.com/getsentry/self-hosted/assets/39041796/9c6462ec-cf29-410a-bc96-cfc7d2b287df)
![image](https://github.com/getsentry/self-hosted/assets/39041796/d391b82f-2ddd-4f0d-bd73-4942adc8c269)

### Actual Result

Actually cant find the debug file.
![image](https://github.com/getsentry/self-hosted/assets/39041796/dd90ff83-1d5c-4562-88d4-03f40d3ee121)
![image](https://github.com/getsentry/self-hosted/assets/39041796/5e1c3c63-d761-4b3b-bc16-40068f90b2ce)
![image](https://github.com/getsentry/self-hosted/assets/39041796/95f84e68-8581-47b8-a8ff-9215710ffb6c)

**Comment by hubertdeng123** [comment]
Are there any logs in symbolicator that may indicate some errors? This looks like an issue during symbolication

**Comment by theremoon-j** [comment]
> Are there any logs in symbolicator that may indicate some errors? This looks like an issue during symbolication

where can i get the err logs for symbolicator?

**Comment by hubertdeng123** [comment]
You can try running the command `docker compose logs symbolicator`

**Comment by theremoon-j** [comment]
> You can try running the command `docker compose logs symbolicator`

I've manually upload sym file yet. thx
