### ISSUE TITLE
Inviting members for new org has error

### ISSUE THREAD

**Issue by ykamo001** [getsentry/sentry#65673]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create new org
2. Go to invite members
3. Add members
4. Click send emails

### Expected Result

1. Emails are sent
2. Trial automatically starts

OR

1. Error shows what is actually wrong

### Actual Result

Emails are not sent, and I do not know what the error/problem is. I had to click "learn more" button, then click on "start trial" to actually start the trial. After that, I was able to invite members by sending the emails. Looks like the trial doesn't actually start automatically, which prevents the emails from going?

![Screenshot 2024-02-22 at 3 03 41 PM](https://github.com/getsentry/sentry/assets/5581484/c7cea4ce-f340-4225-9509-0ea0e1c6c1a0)

### Product Area

Settings - Members

**Comment by Dhrumil-Sentry** [comment]
As a part of this improvement we should fix the following:

- Fix the trial based interaction described above
- Allow users to exit from error states of invalid emails
- Default the team selection where only 1 team is available

**Comment by leedongwei** [comment]
Link to [design file](https://www.figma.com/file/Qz08CT7RNoOkaUAatnke8Z/Github-Missing-Member-Sync?type=design&node-id=1784-24003&mode=design&t=FViTIM0DMRW80nxu-0)
