### ISSUE TITLE
[Inbound Filters] Block User-Agents

### ISSUE THREAD

**Issue by phihochzwei** [getsentry/sentry#65682]
### Problem Statement

We recently faced the problem, that a South-Korean Searchengine crawled our Website. Unfortunately, they use a rather obscure Browser which resulted in really weird errors. Even though we got spike protection enabled, we still received several thousand issues which nearly ate up our unit limit. And since we need to use Relay to anonymize IPs we could not block any IPs

### Solution Brainstorm

As a custom inbound filter, it would be really helpful to be able to block a specific user-agent by parts of the string. 

### Product Area

Settings - Projects

**Comment by jjbayer** [comment]
> And since we need to use Relay to anonymize IPs we could not block any IPs

@phihochzwei do you run Relay in static mode? In that case, you can filter out events by adding something like the following to your [project config](https://docs.sentry.io/product/relay/projects/):

```json
{
  "filterSettings": {
    "generic": {
      "version": 1,
      "filters": [
        {
          "id": "WeirdBrowser",
          "isEnabled": true,
          "condition": {
              "op":"eq",
              "name": "event.contexts.browser.name",
              "value": "weird-browser"
          }
        }
      ]
    }
  }
}
```

**Comment by jjbayer** [comment]
@phihochzwei let me know if the local solution I proposed works for you. If not, I will be happy to reopen this issue as a feature request.
