### ISSUE TITLE
[Inbound Filters] Extend the SSR-Hydration Filter to Angular

### ISSUE THREAD

**Issue by phihochzwei** [getsentry/sentry#65683]
### Problem Statement

Currently, this option states: 

"React falls back to do a full re-render on a page and these errors are often not actionable."

Well, since Angular 16/17 this also applies to Angular. 

### Solution Brainstorm

It would be really helpful to extend this Option to handle those errors for Angular as well

### Product Area

Unknown

**Comment by hubertdeng123** [comment]
@getsentry/team-web-sdk-frontend This seems like something that should belong to the web sdk frontend team. Should this go on the web sdk frontend project board?

**Comment by Lms24** [comment]
hey @phihochzwei thanks for writing in! I must admit I'm a bit out of the loop around SSR and Angular. Can you give us an example (some kind of documentation or a small GH repo/stackblitz) around what Angular hydration errors?

Full disclosure: The SDK team didn't build the inbound filter for react hydration errors but we can see what we can check what needs to be done to extend the filter to Angular. Can't give you a timeline on this though.

**Comment by phihochzwei** [comment]
hi @Lms24  

Sure, I will collect some of them over the next week and come back :)
