### ISSUE TITLE
Add Deno Icon Runtime Icon

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#65697]
### Problem Statement

When we have an issue occuring on a server with a Deno runtime, there is a question mark for the icon. While there is no question it is in fact on Deno, and we know it :D 

and there are nice icons we can show instead 🦖 

### Solution Brainstorm

Let's show the icon! 🦕 

we already have it here https://github.com/getsentry/platformicons/blob/master/svg/deno.svg

I don't know hwo it works with this paltform icons repo if this is also connected to use in runtime or that's something else

### Product Area

Issues

**Comment by smeubank** [comment]
fwiw the same is true for vercel edge and probably cloudflare and others, if is where the logic is to add these I would just try to work with design and we add them all

**Comment by sentaur-athena** [comment]
Does it mean for supported platforms we don't necessarily show the icon in issues although we have it during project creation and everywhere else? @smeubank I want to add this for Nintendo as well. Who would be the right person to reach out and see how to do it?

**Comment by scttcper** [comment]
deno was done by @smeubank in #69100
