### ISSUE TITLE
Control  Asana 

### ISSUE THREAD

**Issue by Bayramito** [getsentry/sentry#65735]
### Problem Statement

When I complete my task from Asana, I want my issue to be marked as Resolved automatically in Sentry  or if I mark my issue as resolved in Sentry, the task in the Asana also should be marked as completed.

### Product Area

User Feedback

**Comment by Dhrumil-Sentry** [comment]
This is a valid request and we'll add it to our backlog but we don't anticipate working on this for the next 2 quarters

**Comment by iamrajjoshi** [comment]
The team is understaffed, so we aren't able to actively supporting plugins at the moment, but we are always open for community contributions!
