### ISSUE TITLE
Searching by user.email produces incomplete results

### ISSUE THREAD

**Issue by jiri-matejka** [getsentry/sentry#6574]
We have desktop email client application where a single user can have the app running on multiple computers.
We log to Sentry a report with computer-specific user.username, but the same user.email for such a user.
In such case the issue search by email is incomplete, it returns only issues for one of the usernames. 
Our suspect is this routine: https://github.com/getsentry/sentry/blob/61359ba626a3d18274ad6494e2997283fbac23d5/src/sentry/search/utils.py#L36

Sentry 8.21.0 on Docker

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
