### ISSUE TITLE
Tag length limit - 200 characters, shows only first, not documented

### ISSUE THREAD

**Issue by tajchert** [getsentry/sentry#6576]
- Sentry 8.18.0
- Docker

I try to log event with Android SDK (1.4.0) with tag that is over 200 characters long. I get:
```
"Discarded invalid value for parameter 'tags' " 
{
  "name": "tags",
  "value": [
    "test_tag_three",
    "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  ]
}
```
Question is - shouldn't be max length of tag documented (also maybe client SDK should throw runtime exception/warning for such case)?
Bug - web dashboard shows only one such case for event (if event has more than one such tag it reports only first one).

**Comment by bretthoerner** [comment]
(Oops sorry about assign @mitsuhiko, ignore that.)

@tajchert We should document and warn about the tag length for sure. I don't understand your comment about the bug, though, can you provide more detail?

**Comment by tajchert** [comment]
Hi,
No problem, glad to help with pointing that out.

With bug I mean if you have 2+ more tags that are over 200 characters, only first one is displayed in web dashboard as wrongly parsed, fix would be to display all tags that are not correct/doesn't meet criteria. If this is still not clear let me know.

**Comment by bretthoerner** [comment]
Interesting, the JSON actually contains 2 errors, so I think this is a bug on the frontend.

![](https://i.imgur.com/jUgBzU8.png)

![](https://i.imgur.com/fiIC8S3.png)

**Comment by bretthoerner** [comment]
@macqueen this may be another easy ticket? Error data in the payload but for some reason we're only showing the user one error? My comment above shows an example -- I sent an event with 2 very large tag values.

**Comment by ethanmdavidson** [comment]
Just ran into this same issue. The error message in the web dashboard is descriptive enough that I was able to track it down easily, but it would've been nicer to have a heads up in the documentation.

**Comment by BYK** [comment]
Ping @markstory, @untitaker

**Comment by mitsuhiko** [comment]
@BYK the error message should be more descriptive now compared to when this issue was first made. I feel like this might be resolved?

**Comment by mitsuhiko** [comment]
Current error in the UI:

![image](https://user-images.githubusercontent.com/7396/67813104-04e05480-faa1-11e9-864c-2a1a5cf2546d.png)

Maybe still not ideal

**Comment by yuzefovich** [comment]
One easy improvement to error message could be saying exactly what the "maximum length" is, so the users could act accordingly.

**Comment by scttcper** [comment]
Docs on customizing tags specify the limits https://docs.sentry.io/platforms/node/enriching-events/tags/
