### ISSUE TITLE
[User Feedback] Listing a project's user feedback breaks if there a linked error has been deleted

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#65779]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Use the new User Feedback in your app, ie. in [the React SDK](https://docs.sentry.io/platforms/javascript/guides/react/user-feedback/)
2. Record a couple of user feedback entries
3. Use [this endpoint](https://docs.sentry.io/api/projects/list-a-projects-user-feedback/) to list your project's user feedback
4. Now go to one of your user feedback entries, click onto the linked error, and delete that issue
5. Use the endpoint from step 3 again.

### Expected Result

The recorded user feedback is returned both times

### Actual Result

The second time, after we have deleted the linked error from one of our user feedback entries, our request returns an empty array. It looks like having one or more deleted linked issues is breaking the endpoint.

### Product Area

User Feedback

**Comment by bruno-garcia** [comment]
Thanks for raising, we'll take a look

**Comment by tkhho** [comment]
Hi, is there a update on this topic? This currently causes, that we have to manually create tickets from User Feedback. Normally we automatically syncing it with this endpoint, but this is not working anymore.

**Comment by bruno-garcia** [comment]
No updates yet
@tkhho you can have Sentry create tickets automatically for you when the feedbacks arrive, have you considered that? What tool do you create the tickets on?

**Comment by tkhho** [comment]
We are using Zendesk for support. We automatically create a Zendesk ticket from a user feedback.

We previously used alerts and webhooks to create a ticket when a user feedback is created. But an alert is only triggered maximum every 5 minutes. So if two feedbacks has been created within 5 minutes, only one of them has been exported.

Now we are polling on regular basis the feedback endpoint to look for new user feedback. But this stopped working now, because of this bug.

unfortunately there is no integration with zendesk.

**Comment by bruno-garcia** [comment]
We track Zendesk integration here:
* https://github.com/getsentry/sentry/issues/50877

**Comment by souredoutlook** [comment]
@tkhho 👋 Manager of Technical Support for Sentry over here. We pipe User feedback into Zendesk 1 of 2 ways right now.

For our help center's user feedback form (we're using the most recent iteration of the feedback widget) we simply use Issue Alerts, for routing user feedback from our other web properties we use workflow notifications and secondary email routing.

It sounds like you're using the old report dialog which associates user feedback with specific error events on an issue. For this case you could consider using workflow notifications and a secondary email for routing on that project. 

You should be able to filter out workflow notifications that don't include a message of new user feedback being received on the Zendesk platform. Happy to hop on a call and have a look if you'd like just open a ticket and reference this comment.

**Comment by tkhho** [comment]
Thank you for your thoughts about how to sync zendesk with sentry, but we have a working solution for syncing feedbacks with zendesk. There is just this bug, which has to be resolved, then everything works for us again.

**Comment by bruno-garcia** [comment]
I'm sorry we broke your workflow which relies on this API. Unfortunately we don't have an alternative yet. I'll raise this with the team to see if there are anything we can do to unblock you or at least a plan to resolve this. cc @cmanallen might have ideas

**Comment by cmanallen** [comment]
@tkhho I've not been able to reproduce this issue.  Are you able to share your organization slug so I can investigate the error?

Alternatively, we expose a new API for querying user-feedback reports:
```
https://us.sentry.io/api/0/organizations/{ORG_ID}/issues/?project={PROJECT_ID}&start={START_DATE}&end={END_DATE}&limit=25&query=issue.category:feedback
```

Docs: https://docs.sentry.io/api/events/list-a-projects-issues/

**Comment by JoshFerge** [comment]
the above API should solve this issue
