### ISSUE TITLE
Can't receive slack alert from sentry

### ISSUE THREAD

**Issue by easyhappy** [getsentry/sentry#65777]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

sentry send alert message to slack

### How are you getting stuck?

after I create one alert rule, sentry show message list from  program, but it doesn't send message to slack.

<img width="1188" alt="截屏2024-02-26 20 23 55" src="https://github.com/getsentry/sentry/assets/733348/f8ba9cd2-30a4-4922-b490-a1e19e8a36bb">
<img width="969" alt="image" src="https://github.com/getsentry/sentry/assets/733348/b39ff2e1-2e36-4c80-9032-90a80b7ea958">

<img width="1476" alt="image" src="https://github.com/getsentry/sentry/assets/733348/6f48ec67-4fbb-494c-9de9-3307d20e864c">

project id: 4506804732952576

### Where in the product are you?

Issues

### DSN

o4504710408830976

**Comment by pablodz** [comment]
Same here

**Comment by Dhrumil-Sentry** [comment]
We're actively working on fixing this proble and will update this issue as we have more updates to share

**Comment by Juantamayo26** [comment]
Same problem 😢

**Comment by easyhappy** [comment]
thx, already receive now
