### ISSUE TITLE
Better error reporting for CORS failures

### ISSUE THREAD

**Issue by acdha** [getsentry/sentry#658]
If your hostname is specified incorrectly, Sentry loses live updating and the ability to resolve errors with no notice other than the console messages telling you that the hostnames are incorrect. It feels like this is easy enough to do that the AJAX handler should display some sort of error dialog for this class of failures, which will never resolve without a config change.

**Comment by mattrobenolt** [comment]
Going to assume this isn't a problem anymore. Also.... 4 years old.
