### ISSUE TITLE
Drop-down list for Custom Fields

### ISSUE THREAD

**Issue by t-huynh** [getsentry/sentry#65811]
### Problem Statement

Requesting to have custom fields which are selectable in Jira become drop-down fields in the Sentry UI for creating linked Jira issues.

Currently custom Jira fields show up as text boxes in the Sentry UI for creating linked Jira tickets. Typing "Maintenance" in a custom field "Account" for example, then pressing Create Issue results in the button being disabled but no ticket being created on the Jira side. I believe it has to do with the typed in value not matching with the index of select choices from Jira.

Error in inspector shows:
"{ "io.tempo.jira__account": [
  "Can not deserialize instance of java.lang.Long out of START_OBJECT token\n at [Source: N/A; line: -1, column: -1]"
]}"

### Solution Brainstorm

I'm not well versed in python, but poking through the source code, I see that there is already code to consume fields with selectable options like the Jira Project field. Perhaps the same functions or logic could be applied to other custom fields that are selectable.

### Product Area

Issues

**Comment by Dhrumil-Sentry** [comment]
This is a valid ask, I am adding this to our backlog and will keep the issue updated when we have timelines but I don't anticipate working on this in the next few months atleast

**Comment by GabeVillalobos** [comment]
Hi @t-huynh. Are you still experiencing this problem? We've overhauled some of our Jira field handling recently, so I'm not sure whether we've already fixed this particular issue.
