### ISSUE TITLE
Set Default Env on Issues Page

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#65854]
### Problem Statement

Currently we only have a Saved Search Settings that allows you to set a default saved search as you can [see in our documentation](https://docs.sentry.io/product/reference/search/saved-searches/), however this does not allow for you to save a default env at present. 

### Solution Brainstorm

Customer would like to be able to set a default env selection the same way you can save a search settings by selecting "Save as Default" in upper right
<img width="773" alt="Screenshot 2024-02-26 at 5 35 30 PM" src="https://github.com/getsentry/sentry/assets/100724053/9a26e293-e767-421e-bcc1-1d93ef19e55c">

### Product Area

Issues

**Comment by Joodith** [comment]
@ReneGreen27 I would like to take up this issue.As iam new to open source contribution,can you share me relevant materials regarding the issue?

**Comment by scefali** [comment]
@ReneGreen27 seems like a good suggestion! I'm going to add this to the backlog

**Comment by MichaelSun48** [comment]
Closing this since it appears that @lobsterkatie has provided a working solution and there has been >6 months of inactivity - feel free to reopen if this is not the case.
