### ISSUE TITLE
Use TTFD as Calculation Method

### ISSUE THREAD

**Issue by ohjunki** [getsentry/sentry#65856]
### Problem Statement

I saw a feature in [the document](https://docs.sentry.io/product/performance/metrics/#custom-thresholds) that allows for modification of the Calculation Method on a per-project basis, but the only options available for setting are Duration and LCP. In Android, we are recording TTFD instead of LCP; is it possible to use TTFD??

Link PR : #21468 

### Product Area

Performance

**Comment by k-fish** [comment]
@ohjunki hey, thanks for using the product. Those calculation methods are specifically for `Apdex` and `User Misery`, can you tell me more about your use case for mobile for these? It's likely we'll be focusing more on TTFD soon for a more mobile-specific view.

**Comment by alexjillard** [comment]
TTFD and TTID are the primary metrics that we use for calculations in Mobile Insights, so we can close this issue. @ohjunki if you have any input on how we've implemented this, or if it doesn't meet your needs, please let us know.
