### ISSUE TITLE
Release commits are not created

### ISSUE THREAD

**Issue by JuusoPalander** [getsentry/sentry#6586]
## Issue
Release commits are not created in the database and are not visible in the Sentry dashboard.

### Version and setup
Sentry: 8.21.0
Docker setup:
![rancher-stack](https://user-images.githubusercontent.com/1438515/32937432-2ef0d250-cb81-11e7-8a92-7a61b1879f81.png)

### Details
1. During deployment, we create a Sentry release using `curl`:
```bash
curl -f -s -X POST https://sentry.<url>/api/0/projects/<organization_slug>/<project_slug>/releases/ -H 'Content-Type: application/json' -H 'Authorization: Bearer <token>' -d '<json>'
```
2. The JSON looks like this:
![curl-json](https://user-images.githubusercontent.com/1438515/32937521-9ca1fc5c-cb81-11e7-8064-57aa05d809c1.png)

3. After deployment is done, the Sentry dashboard looks like this:
![sentry-dashboard-release-commits](https://user-images.githubusercontent.com/1438515/32937557-bf53cc94-cb81-11e7-97e6-8f6bb98c2508.png)

4. `sentry-cli releases info` looks like this:
![sentry-cli-release-info](https://user-images.githubusercontent.com/1438515/32937611-e87aa2d2-cb81-11e7-94ab-56cfafab9400.png)

5. Github webhook request:
![github-webhook-request](https://user-images.githubusercontent.com/1438515/32938521-1b14e22c-cb85-11e7-8e41-26337532297f.png)

6. Github webhook response:
![github-webhook-delivery-response](https://user-images.githubusercontent.com/1438515/32938527-22be30f0-cb85-11e7-8355-3913cf6f66ee.png)

All the responses are 204, and payload seems to be what it should be.

7. Postgres queries:
![postgres](https://user-images.githubusercontent.com/1438515/32937702-38381e6c-cb82-11e7-80d9-027015325d70.png)

We'd expect that there would be release commits in the database but there are none. Are we missing something?

**Comment by macqueen** [comment]
It looks like your payload isn't formatted correctly. `commit` should be part of `refs`. There is a curl example here if that's helpful: https://docs.sentry.io/learn/releases/#releases-are-better-with-commits

**Comment by markstory** [comment]
Closing as this issue has gone stale.
