### ISSUE TITLE
[Feature Request] Sentry webhook integration for issue alerts should return issue alert rule ID

### ISSUE THREAD

**Issue by saroshh24** [getsentry/sentry#65878]
### Problem Statement

The Sentry webhook integration for issue alerts returns key information on the event that was received for an issue in a project that matches an issue alert rule [[ref](https://docs.sentry.io/product/integrations/integration-platform/webhooks/issue-alerts/)]. Unfortunately, only the name (label) of the issue alert rule is returned which is not enough to uniquely identify the issue alert rule because many issue alert rules can share the same name. I'd like if the issue alert rule ID was also returned.

### Solution Brainstorm

The webhook integration for issue alerts already returns a json object with details for the `issue_alert` [[ref](https://docs.sentry.io/product/integrations/integration-platform/webhooks/issue-alerts/)]. Adding a field for the `id` on that object could make sens, e.g.

`    "issue_alert": {
      "title": "Very Important Alert Rule!",
      "id": 123456,
      "settings": [
        {
          "name": "channel",
          "value": "#general"
        }
      ]
    }`
  

### Product Area

APIs

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2116) by [Unito](https://www.unito.io)

**Comment by Dhrumil-Sentry** [comment]
Thanks for this feedback, This is a valid request and I'll add it to our backlog

**Comment by yuval-sentry** [comment]
This issue is closely related to this issue:
https://github.com/getsentry/sentry/issues/66622
Maybe we can work on these together.

**Comment by Christinarlong** [comment]
closing this per https://github.com/getsentry/sentry/issues/66622
