### ISSUE TITLE
Distinguish Metrics from Multiple Projects in Selector and Charts

### ISSUE THREAD

**Issue by danielkhan** [getsentry/sentry#65885]
### Problem Statement

I've encountered a challenge in monitoring metrics across the frontend and backend of my application. The core issues and suggestions for improvement are as follows:

* Identifying Metrics: When selecting metrics like transaction.duration from multiple projects, it’s difficult to distinguish their origins since they all appear identical in the metrics selector.

* Filtering Issues: Attempting to use project selection as a filter to identify metrics doesn't work as intended. Changing project selections alters existing queries, which isn't practical.

* Charts Lack Project Info: The generated charts for these metrics do not indicate the project source, leading to potential confusion during analysis.

![Capto_Capture 2024-02-27_04-59-13_PM](https://github.com/getsentry/sentry/assets/2722161/e275b3e7-f632-45c2-aa70-8fb9e4da093b)

### Solution Brainstorm

1. Visual Indicators for Projects: Adding visual tags or labels in the metrics selector and charts would make it easier to identify the source project for each metric.

3. Incorporate Project Selection in Queries: It's crucial that the project selection is explicitly part of each query to maintain clarity and relevance of the data being analyzed.

4. Project Information in Visualizations: Charts, timeseries, and legends (especially in the case of multiple timeseries on a single chart) should clearly display project information to avoid confusion and ensure accurate interpretation of data.

### Product Area

DDM

**Comment by matejminar** [comment]
Addressed in https://github.com/getsentry/sentry/issues/67863 and https://github.com/getsentry/sentry/issues/68409
