### ISSUE TITLE
Replays tab in Transaction Summary: `Could not parse value for 'id'`

### ISSUE THREAD

**Issue by nikolovlazar** [getsentry/sentry#65887]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When I access the `Replays` tab in the Transaction Summary page I get the following message:`Could not parse value for 'id'` in place of the replays list ([screenshot](https://github.com/getsentry/sentry/assets/5396211/a1697397-2d14-4093-b4c4-b7316e38d295)).

Here's the request URL:
```
https://us.sentry.io/api/0/organizations/sentry-devrel/replays/?field=activity&field=browser&field=count_dead_clicks&field=count_errors&field=count_rage_clicks&field=duration&field=finished_at&field=id&field=is_archived&field=os&field=project_id&field=started_at&field=user&per_page=50&query=id%3A%5B%5D&sort=-started_at&statsPeriod=14d
```

The dashboard URL:
```
https://sentry-devrel.sentry.io/performance/summary/replays/?project=4506696112799744&query=&statsPeriod=14d&transaction=%2F
```

The Replays tab does report that I have 13 replays associated with this transaction.

### Expected Result

I should see the 13 replays that are associated with this transaction.

### Actual Result

![Screenshot](https://github.com/getsentry/sentry/assets/5396211/a1697397-2d14-4093-b4c4-b7316e38d295)

### Product Area

Replays

### Link

https://us.sentry.io/api/0/organizations/sentry-devrel/replays/?field=activity&field=browser&field=count_dead_clicks&field=count_errors&field=count_rage_clicks&field=duration&field=finished_at&field=id&field=is_archived&field=os&field=project_id&field=started_at&field=user&per_page=50&query=id%3A%5B%5D&sort=-started_at&statsPeriod=14d

**Comment by billyvg** [comment]
@nikolovlazar can you link to the UI as well, not just the API request?

**Comment by nikolovlazar** [comment]
@billyvg I've updated the issue details
