### ISSUE TITLE
New installation: 0015 fails when trying to create in a schema that isn't public

### ISSUE THREAD

**Issue by sclerck** [getsentry/sentry#6588]
My issue is very similar to this one, in that I'm experiencing the same error message:
https://github.com/getsentry/sentry/issues/2916

I'm using sentry 8.22.0 and other software as per Python-based installation instructions. 

I've tried the following....

Using a super user role:
-          Created a database called sentrydb
-          Created a role called mqsentry
-          GRANT ALL PRIVILEGES ON DATABASE sentrydb TO mqsentry
-          In sentrydb, create schema called sentry
-          GRANT ALL PRIVILEGES ON SCHEMA sentry TO mqsentry
-          ALTER ROLE mqsentry SET search_path TO sentry
 
I then ran the upgrade command (with mqsentry as the login in sentry.conf.py) and see the same errors as before.
 
So, I changed mqsentry to be a superuser and set it to be the owner of the sentry schema….. Still didn’t work.
 
So, I dropped the database and had mqsentry create the database and the sentry schema…. Still didn’t work.
 
So, I changed the search_path of mqsentry to public….. And it worked!

Is it possible to install Sentry into a non-public schema? If so, what is required of the database and / or schema to achieve this? 

Thanks very much

**Comment by mattrobenolt** [comment]
Honestly, I'm not sure. As much as I've used Postgres in my life, I've never used anything other than a public schema, so I'm not sure if there's any suggestions I can give here.

**Comment by sclerck** [comment]
Ok thank you for confirming.

**Comment by lusor** [comment]
We got it to work by adding the parameter 'SCHEMA' to the database config:

```
DATABASES = {
    'default': {
        'ENGINE': 'sentry.db.postgres',
        'NAME': 'sentry',
        'SCHEMA': 'sentry',
        'USER': 'sentry',
        'PASSWORD': 'xxxxxxxxxx',
        'HOST': 'hostname.domain',
        'PORT': '5432',
        'AUTOCOMMIT': True,
        'ATOMIC_REQUESTS': False,
    }
}
```

**Comment by sclerck** [comment]
That seems to have done the job! Thanks very much
