### ISSUE TITLE
Show totals in metrics explorer

### ISSUE THREAD

**Issue by iambriccardo** [getsentry/sentry#65880]
Some users would like to see the totals of the aggregate they run on the metrics explorer (a good example of this is the `count_unique` across the entire timerange).

This ticket involves the work of figuring out and implementing a good way to show the totals.

**Comment by obostjancic** [comment]
Metrics explorer should definitely be able to do this, but as of now it requires adding a different viz type (pie chart or so) and we would also need to support it in the dashboards.
