### ISSUE TITLE
[Feature Request] Manual Issue Creation

### ISSUE THREAD

**Issue by danbopes** [getsentry/sentry#6589]
I've noticed sentry is phenomenal in reporting errors that come in via javascript, but if an end user notices something that isn't right (That does not trigger any javascript error), it would be nice to create a manual issue in sentry, and then log results/comments to keep it all in one place.

**Comment by aashudwivedi** [comment]
I think creating a separate app, which logs the manual issue using the sentry API would solve your problem.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by danbopes** [comment]
I still think you should work on this.

**Comment by BYK** [comment]
@danbopes it is very unlikely that a member from the team will pick this up. If you think this is important, I encourage you to submit a pull request with your best shot at it.

Moreover, you can already create custom issues using the API directly or `sentry-cli`: https://docs.sentry.io/product/cli/send-event/
