### ISSUE TITLE
Refreshing the UI is causing the DSN to change (periodically)

### ISSUE THREAD

**Issue by masinette** [getsentry/sentry#65924]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Refresh the page and view the DSN

### Expected Result

A valid DSN 

### Actual Result

A DSN that is not valid. Sometimes It is following this format:
"@us.sentry.io/project_id"

### Product Area

Ingestion and Filtering

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2115) by [Unito](https://www.unito.io)

**Comment by markstory** [comment]
I've made a change to our saas environment that fixes the missing subdomain (getsentry/sentry@04651514945cd540605aea4d4ea34299377c98ec). Previously the `o123.ingest` prefix would be missing some of the time. The inconsistent results are related to our operational changes to run in a multi-region environment and until that transition is complete, customers will be able to observe shifting DSN addresses. Some responses will contain domains like `o12345.ingest.sentry.io` and other responses will contain `o12345.ingest.us.sentry.io`. Both of these domains will work now and in the future.

**Comment by aelmekeev** [comment]
@markstory should we expect any other domains in the response? Or is it OK to just do:

```
"value" = replace(sentry_key.this.dsn_secret, "ingest.us.sentry.io", "ingest.sentry.io")
```

to remove this inconsistency while provisioning DSN for the services via terraform?
