### ISSUE TITLE
Automatically ingest Heroku platform errors

### ISSUE THREAD

**Issue by trevorturk** [getsentry/sentry#65927]
### Problem Statement

Currently AFAICT there's no support for Heroku's platform errors in Sentry: https://devcenter.heroku.com/articles/error-codes

### Solution Brainstorm

It appears that Honeybadger has support via Heroku's log drain feature: https://docs.honeybadger.io/guides/heroku/#heroku-platform-errors

### Product Area

Ingestion and Filtering

**Comment by Dhrumil-Sentry** [comment]
Thanks for this request, we'll add it to our backlog, but we don't anticipate working on this soon

**Comment by GabeVillalobos** [comment]
Combining this with another similar request: https://github.com/getsentry/sentry/issues/28270
