### ISSUE TITLE
Bulk resolving in New User Feedback fails for issues from same project when multi project stream feature is NOT enabled

### ISSUE THREAD

**Issue by DAcodedBEAT** [getsentry/sentry#65945]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Using account with multi project stream *_disabled_*

1. Submit multiple user feedbacks (going to the same DSN/project)
2. Attempt to batch-resolve multiple user feedback (sourced from the same DSN/project)

### Expected Result

Feedback is resolved and no longer in New User Feedback view.

### Screenshot in UI:

<img width="380" alt="image" src="https://github.com/getsentry/sentry/assets/5031018/dc9de071-bf04-4891-8f56-f76f236dab2e">

### Request:

URL: `PUT https://us.sentry.io/api/0/organizations/<organization>/issues/?id=<issue-id-1>&id=<issue-id-2>`

body:
```json
{status: "resolved"}
```

### Response:
http status: `400 Bad Request`

body:
```json
{"detail":"You do not have the multi project stream feature enabled"}
```

<details>
<summary>Stack trace</summary>
(anonymous) @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-1ce6af.12b13246b35888aa7e4e.js:349
request @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/app_components_emptyMessage_tsx-app_components_events_interfaces_utils_tsx-app_components_for-f7eef3.7d8c561a67239eb527da.js:1
(anonymous) @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/app_components_emptyMessage_tsx-app_components_events_interfaces_utils_tsx-app_components_for-f7eef3.7d8c561a67239eb527da.js:1
requestPromise @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/app_components_emptyMessage_tsx-app_components_events_interfaces_utils_tsx-app_components_for-f7eef3.7d8c561a67239eb527da.js:1
(anonymous) @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/app_actionCreators_guides_tsx-app_components_acl_access_tsx-app_components_events_styles_tsx--4a2c2c.327fabe81eff6042f12c.js:1
mutationFn @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/app_components_events_interfaces_crashContent_stackTrace_rawContent_tsx-app_views_feedback_fe-ac1193.8f71148ffa1c17aa6388.js:15
fn @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_tanstack_query-core_build_lib_index_mjs-node_modules_tanstack_react-quer-f1cb10.674ff662f541c6d0eb28.js:9
w @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_tanstack_query-core_build_lib_index_mjs-node_modules_tanstack_react-quer-f1cb10.674ff662f541c6d0eb28.js:9
l @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_tanstack_query-core_build_lib_index_mjs-node_modules_tanstack_react-quer-f1cb10.674ff662f541c6d0eb28.js:9
l @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_tanstack_query-core_build_lib_index_mjs-node_modules_tanstack_react-quer-f1cb10.674ff662f541c6d0eb28.js:9
execute @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_tanstack_query-core_build_lib_index_mjs-node_modules_tanstack_react-quer-f1cb10.674ff662f541c6d0eb28.js:9
mutate @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_tanstack_query-core_build_lib_index_mjs-node_modules_tanstack_react-quer-f1cb10.674ff662f541c6d0eb28.js:9
(anonymous) @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_tanstack_query-core_build_lib_index_mjs-node_modules_tanstack_react-quer-f1cb10.674ff662f541c6d0eb28.js:9
(anonymous) @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/app_components_events_interfaces_crashContent_stackTrace_rawContent_tsx-app_views_feedback_fe-ac1193.8f71148ffa1c17aa6388.js:15
onConfirm @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/app_components_events_interfaces_crashContent_stackTrace_rawContent_tsx-app_views_feedback_fe-ac1193.8f71148ffa1c17aa6388.js:15
handleConfirm @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/app_components_emptyMessage_tsx-app_components_events_interfaces_utils_tsx-app_components_for-f7eef3.7d8c561a67239eb527da.js:20
(anonymous) @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/app_actionCreators_redirectToProject_tsx-app_actionCreators_sudoModal_tsx-app_components_aler-51dd19.2b91bc995ede6d3242b7.js:1
Ta @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_focus-trap_dist_focus-trap_esm_js-node_modules_history_lib_createMemoryH-bac370.6dee86473f3a2cdbdc35.js:18
Ra @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_focus-trap_dist_focus-trap_esm_js-node_modules_history_lib_createMemoryH-bac370.6dee86473f3a2cdbdc35.js:18
Oa @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_focus-trap_dist_focus-trap_esm_js-node_modules_history_lib_createMemoryH-bac370.6dee86473f3a2cdbdc35.js:18
Go @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_focus-trap_dist_focus-trap_esm_js-node_modules_history_lib_createMemoryH-bac370.6dee86473f3a2cdbdc35.js:18
Jo @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_focus-trap_dist_focus-trap_esm_js-node_modules_history_lib_createMemoryH-bac370.6dee86473f3a2cdbdc35.js:18
(anonymous) @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_focus-trap_dist_focus-trap_esm_js-node_modules_history_lib_createMemoryH-bac370.6dee86473f3a2cdbdc35.js:18
uo @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_focus-trap_dist_focus-trap_esm_js-node_modules_history_lib_createMemoryH-bac370.6dee86473f3a2cdbdc35.js:22
xa @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_focus-trap_dist_focus-trap_esm_js-node_modules_history_lib_createMemoryH-bac370.6dee86473f3a2cdbdc35.js:18
nu @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_focus-trap_dist_focus-trap_esm_js-node_modules_history_lib_createMemoryH-bac370.6dee86473f3a2cdbdc35.js:18
Wl @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_focus-trap_dist_focus-trap_esm_js-node_modules_history_lib_createMemoryH-bac370.6dee86473f3a2cdbdc35.js:18
Hl @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_focus-trap_dist_focus-trap_esm_js-node_modules_history_lib_createMemoryH-bac370.6dee86473f3a2cdbdc35.js:18
U.unstable_runWithPriority @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-1ce6af.12b13246b35888aa7e4e.js:442
un @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_focus-trap_dist_focus-trap_esm_js-node_modules_history_lib_createMemoryH-bac370.6dee86473f3a2cdbdc35.js:18
oo @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_focus-trap_dist_focus-trap_esm_js-node_modules_history_lib_createMemoryH-bac370.6dee86473f3a2cdbdc35.js:22
Qa @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_focus-trap_dist_focus-trap_esm_js-node_modules_history_lib_createMemoryH-bac370.6dee86473f3a2cdbdc35.js:18
c @ https://s1.sentry-cdn.com/_static/dist/sentry/chunks/vendors-node_modules_emotion_is-prop-valid_dist_is-prop-valid_browser_esm_js-node_modules_emo-1ce6af.12b13246b35888aa7e4e.js:4
</details>

note: resolving these user feedbacks individually worked as expected

### Product Area

User Feedback

**Comment by bruno-garcia** [comment]
thanks for raising. we have a PR linked to it, team is on it.
