### ISSUE TITLE
Environment names have very lax validation requirements

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#6595]
The only requirement for environment names is that they are not too long, and are valid unicode: https://github.com/getsentry/sentry/blob/c3c3403088c8dd20200ed273119d945b8ae0c3e0/src/sentry/coreapi.py#L774-L784

These values are also considered case sensitive, so `production` and `PRODUCTION` are stored independently (but not always treated as independently, especially by the UI.)

This causes a few issues:

- We can't send emails with the environment as a header value because it can contain newlines: see GH-6567
- We receive a lot of junk, such as entries where the value was:
  - an incorrect interpolation, such as `$$environment$$`
  - an unexpected value, such as `<class config.ProductionConfig at 0x7f2fdf767808>`: this one is particularly bad because it can lead to a very high cardinality of environment records associated with an organization which can manifest itself in unexpected ways
  - assorted other oddities, such as `{u'environment': u'development'}`
- Inconsistencies in API handling of environments: see GH-6568
- Undefined behavior in the UI when the environment name is split over multiple lines for display

**Comment by Code0x58** [comment]
A simple option would be to use [`django.core.validators.slug_re`](https://github.com/django/django/blob/1.6.11/django/core/validators.py#L128), but that is quite limiting and may cause grief for non-English users.

I think it would be better to use something like [`slug_unicode_re`](https://github.com/django/django/blob/1.11.1/django/core/validators.py#L249) which appeared in Django 1.9:
```python
import re
import unicodedata

slug_unicode_re = re.compile("^[\w-]+$", re.UNICODE)
…
        if not slug_unicode_re.match(unicodedata.normalize("NFKC", data['environment'])):
            …
```
I went with only normalizing in the test so that the users are left to manage that themselves; without normalization things like *élő* would pass but *élő* wouldn't (the latter is [NFKD](https://en.wikipedia.org/wiki/Unicode_equivalence#Normal_forms)).

The slug format still feels too restrictive as white space is nice, allowing that would just require adding `\s` into the pattern.

**Comment by bretthoerner** [comment]
So if this were only in Postgres, I guess it'd be something like (I'm entirely riffing here):

1. Change all events going forward to write to `lowercase` environment names.
2. Downcase and unique-ify all environments as displayed to the user (including filters).
2. On read path... have a lowercase index on environment name and aggregate results.
3. In 90 days delete non-lowercase environments.

But I don't know how this plays out with TSDB? Also 3 may be much harder than it seems at a glance, I'd have to dig in more.

**Comment by tkaemming** [comment]
Good point about unicode normalization — thanks for bringing that up.

For context, here's the current validation for tag values: https://github.com/getsentry/sentry/blob/50f8aea7bd9c8518caf5919f570fc4f8a2a9ac92/src/sentry/tagstore/base.py#L89-L90

Now I think it's possible that right now we're accepting tag values with `\r` in them (I didn't validate that this can actually happen or that it's actually occurred, but it seems plausible) which would break when interpolated into email subject templates. 😞

**Comment by tkaemming** [comment]
I've also confirmed that we've written back some `environment` tag values with newlines (explicitly considered invalid by the above validation method), likely due to this block: https://github.com/getsentry/sentry/blob/9f848bd82c619485862433446e33b5b729790039/src/sentry/event_manager.py#L473-L474

**Comment by tkaemming** [comment]
Environment names that include slash `/` characters also can't be handled correctly in URLs due to a [a `wontfix` bug in Django](https://code.djangoproject.com/ticket/15718). For example:

https://github.com/getsentry/sentry/blob/b8d6aa1d97ba43310dfddc2695fbe74fe9e10a47/src/sentry/api/urls.py#L710-L714

Releases, implement similarly, prevents this with a character blacklist (defined twice?): https://github.com/getsentry/sentry/blob/b8d6aa1d97ba43310dfddc2695fbe74fe9e10a47/src/sentry/api/endpoints/project_releases.py#L17

https://github.com/getsentry/sentry/blob/b8d6aa1d97ba43310dfddc2695fbe74fe9e10a47/src/sentry/models/release.py#L35

**Comment by markstory** [comment]
Closing as #9815 disallowed `/` and newlines from environment names. Stricter validation was explored but would impact too many current users.
