### ISSUE TITLE
Aggregation count for Users and Events are not changed based on the filter

### ISSUE THREAD

**Issue by ddehghan** [getsentry/sentry#6596]
When using a filter criteria for release, os or any other criteria the list events is updated however the aggregation count for Users and Events stays the same.

My example filter criteria:
https://sentry.io/xx/dev-angular/?query=release%3A3.290.64+os.name%3A%22Windows+7%22
https://sentry.io/xx/dev-angular/?query=release%3A3.290.64+os.name%3A%22Windows+10%22

![image](https://user-images.githubusercontent.com/717686/32983249-69da8526-cc46-11e7-9f2d-cbc309556247.png)

This makes is rally hard to figure out if the new release has addressed a bug or not. If I filter the events by release or OS i just want get the count of how many times that exception has occurred for that specific criteria. 

This seems  really basic features. I could not find any discussion about this issues in the forum or previous issue in github. 

Thanks

**Comment by dcramer** [comment]
Counts are total for the issue and not reflective of the search results. 

This is likely something that will change in the future but it’s very complex to implement and scale.
