### ISSUE TITLE
S3 Filesystem PutObject fails due to authorization mechanism

### ISSUE THREAD

**Issue by sreeram-boyapati** [getsentry/sentry#6598]
**Error**

> An error occurred (InvalidRequest) when calling the PutObject operation: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

Sentry Version: 8.21
Docker: Yes
Traceback: https://gist.github.com/sreeram-boyapati/433b0aca69faa9398887a459982b9c7e
AWS Region: Mumbai, India. ap-south-1 (S3 supports version 4 signatures only in this region).

**Comment by sreeram-boyapati** [comment]
Edit: Solved this problem by specifying the signature_version 's3v4' in sentry options for filestore. 

To sentry team,
This should be default, all major regions support s3v4 now and new regions only support v4 signatures.

**Comment by mattrobenolt** [comment]
Well most likely just do this when we stop using S3 ourselves, which should be soonish. We have a problem using v4 signatures ourselves, which prevented us from upgrading boto and botocore. :(

**Comment by kangguru** [comment]
@sreeram-boyapati can you give me an example of your configuration? i'm having a similar problem with a bucket in frankfurt.

```python
    SENTRY_OPTIONS['filestore.options'] = {
        'access_key': env('SENTRY_S3_ACCESS_KEY'),
        'secret_key': env('SENTRY_S3_SECRET_KEY'),
        'bucket_name': env('SENTRY_S3_BUCKET'),
        'region_name': 'eu-central-1',
        'signature_version': 's3v4',
    }
```

doesn't seem to help.

**Comment by kimxogus** [comment]
I'm using on premise sentry 9.0 and having same problem with `s3v4` signature_version.

**Comment by kimxogus** [comment]
setting should be in `config.yml`

```yaml
filestore.backend: 's3'
filestore.options:
  bucket_name: YOUR_BUCKET
  region_name: YOUR_REGION
  signature_version: 's3v4'
```

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
