### ISSUE TITLE
[Dashboards] Sort by release does not display versions higher than 99.x

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#66027]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

**Description:**
A customer has reported that when they create a dashboard and attempt to sort by the release field, they are only seeing release up to version 99.x. However, the organization has release versions that exceed 99.x (i.e 100.1.x)

**Steps to reproduce:**
1. Customer instance and dashboard example - https://sentry.zendesk.com/agent/tickets/114418
2. In the dashboard, add release for step 6:
<img width="784" alt="Screenshot 2024-02-28 at 3 44 10 PM" src="https://github.com/getsentry/sentry/assets/8451987/f56c0406-7758-418d-8eda-ca5b0f33ff57">

3. In step 7, sort by release:
<img width="782" alt="Screenshot 2024-02-28 at 3 46 03 PM" src="https://github.com/getsentry/sentry/assets/8451987/bcbd3672-69b7-41ec-ac8f-94e17f9170bc">

4. Navigate to visualizer -> releases version only up to 99.x

### Expected Result

Sort by releases highest releases that exceed version 99.x

### Actual Result

Only can sort by release verisons 99.x

### Product Area

Dashboards

**Comment by k-fish** [comment]
@JLuse have you been able to repro this with our releases in a dashboard? I suspect it _might_ have something to do with the ordering of the release tag value; we could check by trying to limit to only show two releases in the filter by adding `release:[99.x,100.1.x]` (exactly matching a working and a missing release). If it's actually a sorting issue then `100.1.x` is likely there but not sorted properly, limiting it to only 2 releases should make sure it always shows up in the list.

**Comment by ale-cota** [comment]
@JLuse just checking back in on this one - I've checked the linked dashboard and the problem seems to be resolved now. Can you please verify, so we can close the issue? Thanks!
