### ISSUE TITLE
Deriving tag values from other attributes can result in invalid tag values being saved

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#6606]
Discovered this while looking into GH-6595.

Tag values are supposed to be validated to not contain newlines: https://github.com/getsentry/sentry/blob/50f8aea7bd9c8518caf5919f570fc4f8a2a9ac92/src/sentry/tagstore/base.py#L89-L90

This is correctly applied to values that are provided as tag values as part of the original event payload. However, there are several places that attributes of other interfaces are used to derive tag values that are used for search indexes, and many of these are not subject to the same constraints as tag values.

I think all of the examples that I observed were likely added in these two locations: https://github.com/getsentry/sentry/blob/3b4d153e398342a144047534c291d48eb95fc843/src/sentry/event_manager.py#L463-L512 and 
https://github.com/getsentry/sentry/blob/3b4d153e398342a144047534c291d48eb95fc843/src/sentry/event_manager.py#L523-L524

**Comment by mattrobenolt** [comment]
@lauryndbrown I don't think we should entirely close this. I think there are other issues, not just related to field length that would need to be addressed.

**Comment by mattrobenolt** [comment]
Or at least I think we should make sure all the fields behave as we expect. I don't remember all the context here, so maybe @tkaemming can shed some light.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
