### ISSUE TITLE
Flakey Infinite Retry During Setup for OAuth and SAML

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#66083]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Auth settings of org.
2. Click Configure next to Google SSO
3. Enter email and click Next
4. Observe the next page never loads and lots of errors in browser console.

[Direct link to my test org where you can test it](https://testing-yt.sentry.io/settings/auth/).

### Expected Result

Google SSO is enabled for the org.

### Actual Result

<img width="799" alt="Screenshot 2024-02-29 at 12 27 29 PM" src="https://github.com/getsentry/sentry/assets/96670625/a06cebb0-eb38-4441-a1fb-d3e09199f413">

### Product Area

Sign In

**Comment by leedongwei** [comment]
I can replicate it but it's kind of flakey. Sometimes it works, sometimes it doesn't. We'll investigate.

**Comment by kerenkhatiwada** [comment]
Hey @leedongwei, Users are having issues with other SSO providers as well. I experienced a similar problem during the setup of GitHub Auth in my own org. There is also a user [here](https://sentry.zendesk.com/agent/tickets/114885), who is facing a 404 error while configuring Okta SSO.

**Comment by leedongwei** [comment]
Gotcha. We'll prioritize this.

**Comment by leedongwei** [comment]
https://github.com/getsentry/sentry/pull/66291

**Comment by kerenkhatiwada** [comment]
Hey @leedongwei, it looks like setting up OAuth is fixed now by https://github.com/getsentry/sentry/pull/66291, but setting up SAML is still broken.

**Comment by leedongwei** [comment]
Yea, we're investigating for SAML.

**Comment by thalesvon** [comment]
I am also experiencing a similar issue while configuring Custom SAML2.

There are no errors on the console, but I am redirected to setry.io homepage after inputting the Metadata URL.
On the top of the page, there is a banner that says "Authentication error: Something unexpected happened during authentication."

Support request: 115545

**Comment by seansalmassiviz** [comment]
We are also facing a SAML issues when trying to se up the SSO.

Tried a couple of times in the past days and got authentication error

**Comment by dylancarruthers** [comment]
We are facing the same, unable to set up SAML to AAD. No errors in the console apart from complaints about amplitude.com and stripe.network being blocked.

**Comment by uk-rj** [comment]
We're trying to setup Azure Active Directory and are experiencing an error:
"Authentication error: Something unexpected happened during authentication."

I don't see others mentioning Azure AD, so just wanted to make sure it's on the radar to be investigated.

**Comment by valentyntymku** [comment]
We have a similar SAML issue with Okta and Google, which is urgent for us.
Please prioritize if possible.
Thanks.

**Comment by leedongwei** [comment]
Hi folks. I've identified the problematic area of code that affects SAML setup. It's only happening on production and not in the dev environment, so it's been a small headache to debug. I will update again when I have more clarity.

**Comment by barmicwt00** [comment]
> We have a similar SAML issue with Okta and Google, which is urgent for us. Please prioritize if possible. Thanks.

> Hi folks. I've identified the problematic area of code that affects SAML setup. It's only happening on production and not in the dev environment, so it's been a small headache to replicate. I will update again when I have more clarity.

Hello, can you share estimated time when we can expect solution to this problem with SAML? Thank you

**Comment by leedongwei** [comment]
@barmicwt00 There's some weird cache stuff going on, so I can't promise timelines but it's my main priority and I want to resolve it as soon as possible. Hopefully, by Wed if not earlier.

**Comment by Sagi-Hill** [comment]
Hi All, any news about the issue? 
all the SSO method are not working for us (Tried Okta SSO, Azure SSO & SAML)

**Comment by leedongwei** [comment]
Hi folks, we have engineers from 2 teams investigating at the moment. We narrowed down the issue to our production-only API Gateway service dropping some headers in the request from Okta. A fix is underway.

**Comment by BenjaminJohannes** [comment]
> We're trying to setup Azure Active Directory and are experiencing an error: "Authentication error: Something unexpected happened during authentication."
> 
> I don't see others mentioning Azure AD, so just wanted to make sure it's on the radar to be investigated.

We're experiencing the same trying to set up SSO via Azure AD.

**Comment by leedongwei** [comment]
We've identified the root cause and made some progress towards a fix:
- https://github.com/getsentry/sentry/pull/67452
- https://github.com/getsentry/sentry/pull/67468

**Comment by rajanram** [comment]
> > We're trying to setup Azure Active Directory and are experiencing an error: "Authentication error: Something unexpected happened during authentication."
> > I don't see others mentioning Azure AD, so just wanted to make sure it's on the radar to be investigated.
> 
> We're experiencing the same trying to set up SSO via Azure AD.

We are experiencing the same issue when setting up SSO using Azure AD

**Comment by leedongwei** [comment]
Hi folks. Fix is merged and deployed at 12pm PST. This was a tricky one. Apologies for taking a while to resolve it.

Please reopen this issue if SAML/OAuth setup is still not working for your organization.

**Comment by BenjaminJohannes** [comment]
Hi, I'm afraid this is still not working for us for Azure AD SSO. 

The metadata URL step now goes through but it fails here: 
<img width="652" alt="image" src="https://github.com/getsentry/sentry/assets/37473903/09a1f923-3beb-4f47-a330-d9756553d7ac">
 
After adding the claim names from Azure AD
<img width="632" alt="image" src="https://github.com/getsentry/sentry/assets/37473903/17228b95-7529-432a-a597-97ab6aa62aac">

We get this error: 
<img width="492" alt="image" src="https://github.com/getsentry/sentry/assets/37473903/af7e030a-6b74-4259-958e-29baed730280">

<img width="492" alt="image" src="https://github.com/getsentry/sentry/assets/37473903/ebc1a9d3-712a-4654-8e62-37a0a6224b1e">

**Comment by btpnlsl** [comment]
We are also seeing the same error when trying to set up Custom SAML2 SSO via Google. 
We are able to get the dialog to Map Identity Provider Attributes. We select "Save Attributes" and then are prompted for a Google account to use for Signin.
Then we see either one of these two errors:
- The organization does not exist or does not have SAML SSO enabled
- Authentication error: SAML SSO failed signature validation failed: SAML response rejected

Sorry, no screenshots.

**Comment by uk-rj** [comment]
Same issue with Azure AD..

![image](https://github.com/getsentry/sentry/assets/18295942/ca9125c8-0668-4375-b4f1-8d157d634e2a)

**Comment by Sagi-Hill** [comment]
Same for SAML or Okta SSO (tried both)
![Uploading Screenshot 2024-03-26 at 14.28.53.png…]()

In addition, I'm getting this error : 
"Authentication error: Failed to map SAML attributes. Assertion returned the following attribute keys: 'First Name', 'Idp user ID', 'Last Name', 'User Email'"

**Comment by Sagi-Hill** [comment]
Same for SAML or Okta SSO (tried both)

In addition, I'm getting this error : 
"Authentication error: Failed to map SAML attributes. Assertion returned the following attribute keys: 'First Name', 'Idp user ID', 'Last Name', 'User Email'"

**Comment by leedongwei** [comment]
Thanks for the reports. I'm so sorry for this. We are debugging and we'll update as soon as we have a fix.

**Comment by Dhrumil-Sentry** [comment]
Hi All, We're unable to re-product this error for any of these SAML options

Can you please write to support@sentry.io with the details of all values you add in this Step 9:

![image](https://github.com/getsentry/sentry/assets/109983869/72023d57-b6b5-406e-8db1-7cc2303c3aba)

**Comment by c4xp** [comment]
Same here. But now at least I get a new error:
Authentication error: Failed to map SAML attributes. Assertion returned the following attribute keys: 'http://schemas.microsoft.com/claims/authnmethodsreferences', 'http://schemas.microsoft.com/identity/claims/displayname', 'http://schemas.microsoft.com/identity/claims/identityprovider', 'http://schemas.microsoft.com/identity/claims/objectidentifier', 'http://schemas.microsoft.com/identity/claims/tenantid', 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress', 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname', 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name', 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname'

**Comment by leedongwei** [comment]
@c4xp What attribute keys are you putting in Sentry? That error is usually due to the wrong keys being submitted from your end.

**Comment by c4xp** [comment]
> @c4xp What attribute keys are you putting in Sentry? That error is usually due to the wrong keys being submitted from your end.

Yes, in my case, the problem were the keys. I was about to write here that he input placeholder hints are missleading
When I used the values from:
https://docs.sentry.io/product/accounts/sso/azure-sso/

eg. http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress
it started working..
Maybe amending the hints will be nice

**Comment by uk-rj** [comment]
We are getting this issue:
![image](https://github.com/getsentry/sentry/assets/18295942/6e9299e2-d7c4-41b3-98c9-3e2e965ebf85)



Reproduction step:
https://<slug>.sentry.io/settings/auth/
Active Directory -> Configure

Paste the App Federation Metadata Url from the EnterpriseApp into the Metadata URL.
Complete the four map entries using the values in here: https://docs.sentry.io/product/accounts/sso/azure-sso/ (IDP Username, email, first name, last name) and save.

It returns to the project screen with the above error message at the top.

**Comment by leedongwei** [comment]
@uk-rj Can you reach out to support@sentry.io? I can't debug this without knowing which organization that you're in.

**Comment by leedongwei** [comment]
Closing this issue because the original problem has been resolved.

**Comment by Sagi-Hill** [comment]
I'm still having issues with connecting SSO (tried SAML & OKTA options) this the error message I got: 
CSRF Verification Failed

A required security token was not found or was invalid.

If you're continually seeing this issue, try the following:

Clear cookies (at least for Sentry's domain). - **Did that (And tried Incognito)**
Reload the page you're trying to submit (don't re-submit data). - **Did that**
Re-enter the information, and submit the form again. - **Did that**
Ensure the URL does not contain an extra "/" anywhere (eg: https://foo//saml -> https://foo/saml).
Read more about [CSRF on Wikipedia](https://en.wikipedia.org/wiki/Cross-site_request_forgery).
