### ISSUE TITLE
Able to filter out archived errors for metric alert

### ISSUE THREAD

**Issue by siggi-livekindred** [getsentry/sentry#66175]
### Problem Statement

We have a "noisy issue" in production that is proving elusive to fix. The app recovers from the error and it does impact the user experience, so a decision was made to live with it, hopefully for a short while.

Archiving the issue, temporarily for a set time, seemed like the perfect solution here.

> Archive an issue to move it out of the issue stream and pause alerts on it until the issue gets worse. Archiving makes sense for noisy issues that are less pressing or not applicable to you or your team. Archiving changes the issue status to Archived and moves the issue from "Unresolved" into the "Archived" tab.

https://docs.sentry.io/product/issues/states-triage/#archive

We quickly found out that this kept tripping our alerts, despite being archived. 
Later found out (with help from support) that this is documented in "Metrics Alerts"

> Metric alerts aren’t affected by archived issues, so events from those issues are counted if they match the filters of your metric alert rule.

https://docs.sentry.io/product/alerts/alert-types/#metric-alerts

Currently adding an `is:archived` filter results in an error: `"is:" queries are not supported in this search.`

Would it be possible to add support for an `is:archived` filter on Metric Alerts?
Are there other solutions to filter "noisy issues" from metric alerts?

### Solution Brainstorm

Adding a `is:unresolved` filter appears to work as a workaround. Assume it's broader so may not be ideal.

### Product Area

Alerts

**Comment by rachrwang** [comment]
@scttcper - can you work with @vivianyentran to make sure the docs are updated accordingly for this change? Thanks!

**Comment by siggi-livekindred** [comment]
Thanks for clarifying @scttcper! 
I will continue using `is:unresolved`, the `!issue.id:<issue_id>` filtering is a good trick to know about as well.

+1 on adding to the referenced docs but otherwise feel free to close this request
