### ISSUE TITLE
[Product Category Trials] Show ♾️ as the reserved quota during a product category trial

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry#66188]
### Problem Statement

Customers are occasionally confused that the UI shows the reserved quota amount (which is already part of the their subscription) while also showing that the data category has x days remaining on trial. 

Uninitiated users will believe that this data category is somehow not available by default.

### Solution Brainstorm

Show  ♾️ during the product trial for that specific reserved quota type to indicate that the trial is modifying the reserved amount from the platform/base amount.

Here's an example screenshot prepared by @vbro :

![image](https://github.com/getsentry/sentry/assets/76002357/415df3eb-7b3d-484e-bccf-4731ee4992be)

For reference the current UI looks like this:

![image](https://github.com/getsentry/sentry/assets/76002357/a7b5d940-365c-4c2e-a078-52856795436c)

This feedback was surfaced as part of triaging and resolving the following Zendesk ticket https://sentry.zendesk.com/agent/tickets/114973

### Product Area

Settings - Subscription

**Comment by brianthi** [comment]
Implemented with https://github.com/getsentry/getsentry/pull/13104
