### ISSUE TITLE
Config name conflict with /rydurham/Sentinel/

### ISSUE THREAD

**Issue by warmwhisky** [getsentry/sentry#6618]
I am having issues with installation to Laravel 5.2. I am currently using github.com/rydurham/Sentinel/ for authentication which has the same config name as your package and also I believe you use the same facade name, but I have not got that far to find out if the below issue was fixed? https://github.com/getsentry/sentry-laravel/issues/24

**Comment by MeredithAnya** [comment]
Closing this and putting it here https://github.com/getsentry/sentry-laravel/issues/112
