### ISSUE TITLE
Feedbacks sent via User Feedback API not applying environment from Scope

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#66214]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Reported by a user using Android sdk, I reproduced using latest NextJs sdk.

User feedback events sent via the user feedback api do not have the correct environment tag applied, even though the event the feedback is attached to has the correct environment tag.

**1. Follow docs on setting up [User Feedback Api](https://docs.sentry.io/platforms/javascript/user-feedback/#user-feedback-api)**

<img width="450" alt="Screenshot 2024-03-01 at 10 57 47 AM" src="https://github.com/getsentry/sentry/assets/96670625/3d90fbb5-d0bb-49a8-aa84-68fee1d1d715">

**2. Set Env tag in init.** 

<img width="300" alt="Screenshot 2024-03-01 at 10 56 16 AM" src="https://github.com/getsentry/sentry/assets/96670625/7da6ca2d-e216-4641-bce7-1ae7ac453ab4">

**3. Send event with user feedback**

**4. See that event in Sentry has correct env tag set, but user feedback has default "production" env tag set.**

--------------------------------------

**Event has correct env tag -**
<img width="600" alt="Screenshot 2024-03-01 at 10 59 33 AM" src="https://github.com/getsentry/sentry/assets/96670625/3f4a585d-1b97-4d75-9efa-ee4a740aece2">

**Feedback has production env tag -**
<img width="600" alt="Screenshot 2024-03-01 at 10 59 25 AM" src="https://github.com/getsentry/sentry/assets/96670625/871fd4eb-0c5a-42e7-be3f-ae25ac6887c0">

[Link to my org where I tested all three feedbacks to check the env tags](https://francisorg.sentry.io/feedback/?project=4504089864830976&statsPeriod=14d).

### Expected Result

Feedback should have the same environment tag as the event. 

### Actual Result

Feedback does not have the same environment tag.

The tags do get set properly when using the new User feedback widget, or the Crash Report Modal.  Only the API seems to exhibit this behavior.

**Comment by billyvg** [comment]
Just to clarify here, I don't think this is SDK related at all, it seems to be a problem with our feedback backend/ui not using the correct env value.

**Comment by jas-kas** [comment]
cc/ @JoshFerge @ryan953

**Comment by BranislavJenci1** [comment]
Hi, i have the same issue. Is there any hack/ quick fix that i can use until you fix the issue? Thanks.

**Comment by bruno-garcia** [comment]
I don't believe there's a work around just yet. We'll need to change the sdk to attach the environment I believe. Or pull it from the DSC of the envelope header I guess. Let's see what the engineers suggest

**Comment by JoshFerge** [comment]
Fixed with https://github.com/getsentry/sentry/pull/68317
