### ISSUE TITLE
[Design] Replay for Mobile Alpha: UI changes from Web

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#66223]
This issue lists key differences between our current Replay product, tailored for Web. And what data/details Mobile replay will have.

Note we don't plan on releasing Dead/Rage click support on the first alpha. But when we do, the term 'Click' feels off on mobile. 
Would we call it 'dead taps' instead?

# Replay Index

### Empty state

The global selector can have 1 mobile project, 1 web project, or a combination of the two. 

1. Today, it includes **FAQ** with 3 entries, all of which are Web specific
2. In addition, the _Selectors_ tab, is Web specific
3. _Read Docs_ links to `/platforms/javascript/` docs
4. Blue banner saying _Replay isn't available for project Xyz_ is based on projects other than Web
5. View Sample shows a Web project
6. Copy _See a video-like reproduction_ is not accurate on Mobile, where we have an actual video. Though due to redacting, maybe _video-like is accurate enough_

![image](https://github.com/getsentry/sentry/assets/1633368/6c16a617-694c-4936-97c2-d32a1edc085d)

### When a Mobile project is selected

1. Dead and Rage click cards at first won't be available on Mobile. But when we do they won't be based on 'selectors'
  - This is shown in the cards and also on the table itself
2. _Browser_ won't be available for Mobile. _OS_ is still relevant. For Android and iOS native it'll always be the same one, but Flutter/React Native/MAUI/etc it'll vary. 

![image](https://github.com/getsentry/sentry/assets/1633368/2bead029-a80c-44e8-a69d-15578e231771)

# Replay Details

1. URL is not applicable. Screen name might be a good replacement.
2. _Console_, _Accessibility_, _Memory_ are not applicable
3. _Network_ feels like Browser DevTools but its data comes from breadcrumbs. We can keep that, removing the related crumbs from the _Breadcrumbs_ list. Request/Reponse payload are not available (at least at first).
4. Rage and dead click counts at the top will not be applicable at first.

![image](https://github.com/getsentry/sentry/assets/1633368/4689a34c-4666-4d01-a86e-4282eda99b22)

**Comment by jas-kas** [comment]
@bruno-garcia Some follow up questions:

> URL is not applicable. Screen name might be a good replacement.
How do we identify the screen name? :o

Should we also add that masking on Mobile for Replay Details looks like blocks instead of *****? :D

**Comment by bruno-garcia** [comment]
> How do we identify the screen name? :o

The SDK will send it, I believe we might be using the URL field even right now @romtsn @brustolin ?

**Comment by romtsn** [comment]
yes, https://github.com/getsentry/relay/blob/1a780e2831c1e6e8b3cfda97e7345c3e3279c367/relay-event-schema/src/protocol/replay.rs#L19

but also, we'll have to send breadcrumbs for navigation to indicate that the screen has changed

**Comment by Jesse-Box** [comment]
@bruno-garcia @jas-kas I'm going to close this ticket because it feels most future actionable items will be addressed in a separate ticket.
