### ISSUE TITLE
Make eventId optional for user feedback?

### ISSUE THREAD

**Issue by Addvilz** [getsentry/sentry#6624]
Currently, User Feedback requires an event id from sentry to submit any feedback. It would be quite useful to make this optional (thus making having an event optional), to be able to accept generic user feedback as well. Otherwise you almost need to throw an exception yourself to capture user feedback.

**Comment by dcramer** [comment]
That bleeds far too close to a support system and I don’t think it’s somwthing we’re ever going to want to really do.

**Comment by Addvilz** [comment]
For me it's either this or god awful JIRA collector. The nice part about user feedback is that it depends on Sentry alone, and does not need any backend support, in case the backend is what's broken. Hence the idea.
