### ISSUE TITLE
Make it easier to see long span names in the context of performance waterfall graph

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry#66260]
### Problem Statement

Sometimes span names are long and can't be easily seen in the waterfall graph. For example:

![Screenshot 2024-03-04 at 2 00 42 PM](https://github.com/getsentry/sentry/assets/12092849/0c26f414-090e-42f4-9d7b-f7553beaa3b2)

Even if I drag the column wider, the problem may not go away:
![Screenshot 2024-03-04 at 2 02 56 PM](https://github.com/getsentry/sentry/assets/12092849/5f23cf79-ea04-41a7-9402-690803c699fc)

### Existing way product solves this

You can click to expand to see a lot of other metadata:

![Screenshot 2024-03-04 at 2 04 11 PM](https://github.com/getsentry/sentry/assets/12092849/52374114-1d45-43ef-ad21-bc97f2a54eec)

However, this takes me away from the experience of viewing this span in the context of the waterfall graph, and provides too much info -- I just want to know what the span is!

### Solution Brainstorm

Hovering over the span name shows a tooltip containing the full extended span name, as in the mockup below (maybe up til a certain character length)

![Screenshot 2024-03-04 at 2 05 29 PM](https://github.com/getsentry/sentry/assets/12092849/6bb092b3-53b1-4a72-85cb-7009dcb380a0)

### Product Area

Performance

**Comment by k-fish** [comment]
Hey @cstavitsky, yeah the long horizontal rows especially for http has been a bit of a pain point. At the moment we are actually in the midst of rebuilding some of the transaction and trace view. This UI should be changing, I don't know that anything is finalized, I'll mention this to design for that project.
