### ISSUE TITLE
Manage user details page: Own username shown instead of selected user's

### ISSUE THREAD

**Issue by benebun** [getsentry/sentry#6627]
Using Sentry version 8.13.0:
When managing users, on their detail page it shows my own username instead of the selected user next to the "User Details" headline:

See screenshot below: I'm editing spam users exampleuser20@examplie.com but next to the headline at the top it shows my own user.

URL: `/manage/users/1/`

Screenshot:
![screenshot-2017-11-27 change user admin sentry](https://user-images.githubusercontent.com/1321740/33273138-b4453834-d38c-11e7-87cd-3a9b5ba95e8b.png)

**Comment by billyvg** [comment]
You're using an outdated version of sentry, our current release is 8.22.0, where this bug isn't present.
