### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by Jesperpaulsen** [getsentry/sentry#66307]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Clicking add integration
2. Clicking configure at github.com
3. Choosing repositories

### Expected Result

The plugin is installed in Sentry

### Actual Result

The plugin is not installed, and no errors are shown. After being redirected from Github this is all that is shown:
<img width="1054" alt="Screenshot 2024-03-05 at 14 34 13" src="https://github.com/getsentry/sentry/assets/37295027/8e8b9756-47b9-4fdd-9d15-7db6de0cf9ff">

### Product Area

Settings - Integrations

### Link

atlas-hq

**Comment by leedongwei** [comment]
Thanks for the bug report! We'll prioritize the investigation for this.

**Comment by squpshift** [comment]
How's this going?

**Comment by cathteng** [comment]
Is it possible that there exists another org with a Github integration for this same repo? We would need some information about your org slug and repo to investigate further.

**Comment by Jesperpaulsen** [comment]
No, that can't be possible. First time adding Sentry. But one thing that can be related is that I changed the org slug for the organization in Sentry after creating it. What information do you need?

**Comment by cathteng** [comment]
Could you please submit a support ticket through Sentry with a video of the behavior so we can better investigate this?

**Comment by Fwang36** [comment]
Hey guys,

The user here has written into support and we were able to get the integration installed properly for them.

If any other SaaS users stumble upon this while trying to set up their Github integration and has these symptoms  -

 - Sentry shows integration as uninstalled.
 - Clicking Add Installation opens a Github window where the button says "Configure"
 
 Please open a support ticket through the widget in your org, and we will take a look.
