### ISSUE TITLE
Add a expand to fullscreen button to the breadcrumb section of an issue

### ISSUE THREAD

**Issue by ccerinojr** [getsentry/sentry#66310]
### Problem Statement

When investigating issues, I often would like to focus on the historical context of the app leading up to the issue in the breadcrumbs. In general, the limited space provided makes it hard to navigate a long history of breadcrumbs and it becomes even more difficult if the breadcrumbs have a lot of metadata associated with them. I also find myself fighting with which scrollable area gets the scrolling focus. The focus will often switch between the page and the breadcrumb section.

### Solution Brainstorm

Add an option to the breadcrumbs sections to expand or pop out that section to become the full page. Providing an option to focus completely on the breadcrumbs will provide more screen real estate for investigating and limit the number of scrollable surfaces to one.

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2118) by [Unito](https://www.unito.io)

**Comment by leeandher** [comment]
New expanded UI is available for all customers! More info in the changelog -> https://changelog.sentry.dev/changelog/improved-breadcrumbs-on-issues/
