### ISSUE TITLE
Roku SDK

### ISSUE THREAD

**Issue by prashantchothani** [getsentry/sentry#66399]
### Problem Statement

As the apps being developed for the CTV and Smart TV devices increase, developers are building apps more than ever for these ecosystems. One of them is Roku which uses Brightscript. Currently errors can be logged using an HTTP API of other solutions like Bugsnag, but Sentry does not have an HTTP API as well.

### Solution Brainstorm

Ideally a Roku Brightscript SDK would make much more sense than just a HTTP API as that would not only enable Error Reporting, but also give other metrics including performance and tracing. 

### Product Area

Other

**Comment by prashantchothani** [comment]
Any update on this please ?

**Comment by leedongwei** [comment]
We have an API for ingesting errors. Let me check with the team.

**Comment by leedongwei** [comment]
The documentation for the API to send errors to Sentry is here: https://develop.sentry.dev/sdk/envelopes/

At this moment, Roku BrightScript is too limited in reach for us so it's unlikely that we'll prioritize a SDK for it.

We have a guide for the open-source community to implement SDKs (https://develop.sentry.dev/sdk/) and a Discord channel (https://discord.com/invite/sentry) with our in-house SDK folks to answer questions and help you build the SDKs.

Leaving this issue open for folks to :+1: on the top post so we can get some sense of the demand for it.

**Comment by stephanie-anderson** [comment]
Closing this issue for now - we won't be shipping a Roku SDK any time soon
