### ISSUE TITLE
Hide / show query design

### ISSUE THREAD

**Issue by ArthurKnaus** [getsentry/sentry#66403]
Problems:
* The current solution is not easily discoverable by the user
* We have 3 different states (hidden, visible, selected)

![Image](https://github.com/getsentry/sentry/assets/7033940/2db4c7a4-939f-4e60-9426-6895ee838014)

Also repordet in JAVASCRIPT-2S3E

**Comment by Jesse-Box** [comment]
Figma Designs [here](https://www.figma.com/file/WYkmVTTDjdyNKdd2eerc6s/Specs%3A-Multi-queries-%26-Formula's-v2?type=design&node-id=1%3A9812&mode=design&t=vS2ymroziVswFGzW-1)

Based on the feedback in slack, I'm confident the design is ready
