### ISSUE TITLE
Sentry incorrectly parses a microsoft link from a .NET Exception message

### ISSUE THREAD

**Issue by Baffour** [getsentry/sentry#66428]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. In a .NET Project with Sentry included, trigger an exception that has a microsoft link in the URL.
2. View the issue in the Sentry App
3. Click the link to view the microsoft documentation
![image](https://github.com/getsentry/sentry/assets/3619447/1735a9e0-645e-4d2d-aada-7908bb0c36e3)

### Expected Result

The Microsoft Documentation page loads successfully

### Actual Result

The page fails to load and Bing opens instead (This is because the URL it tries to use includes the period at the end of the sentence, and Microsoft redirects invalid short links to Bing)

### Product Area

Issues

**Comment by scefali** [comment]
@Baffour I will try to fix this by the end of the week

**Comment by Baffour** [comment]
@scefali went back to the issue and can see the fix is live, thank you!
