### ISSUE TITLE
Add more detailed error message for failed SSO set up

### ISSUE THREAD

**Issue by bfpepper87sentry** [getsentry/sentry#66443]
### Problem Statement

Right now users in Developer and Team tier level plans do not have access to SSO. When trying to set up SSO they are presented with a generic error message "Authentication error: Something unexpected happened during authentication." Requesting that the error message prompts them to contact sales to upgrade plan or informs them of current plan limitations. 

### Product Area

Unknown

**Comment by Dhrumil-Sentry** [comment]
This is a fair ask, Adding this to our backlog

**Comment by leedongwei** [comment]
This is related to https://github.com/getsentry/sentry/issues/66083
