### ISSUE TITLE
[Design] More padding between AI Solutions character and Performance Issue's "Resources and Maybe Solutions"

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry#66446]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. trigger an Uncompressed Asset performance issue
2. view the performance issue's 'resources and maybe solutions' section
3. the character art is at risk of overlapping important text

### Expected Result

No risk of overlapping the resources/solutions text with the character art.

### Actual Result

[Reference perf issue
](https://demo.sentry.io/issues/4522215778/?alert_rule_id=14346326&alert_type=issue&notification_uuid=9cf8b1ae-220e-495c-b717-339ce09d1ffa&project=5808623&referrer=slack)

![Screenshot 2024-03-06 at 11 59 49 AM](https://github.com/getsentry/sentry/assets/12092849/04e4c6e7-e099-4d15-bbc5-1a95a34ec4ed)

Note that this does not occur on [some other](https://demo.sentry.io/issues/4328601416/?project=5808623&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=3) perf [issues](https://demo.sentry.io/issues/3952653497/?project=5808623&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=30d&stream_index=7)

### Product Area

Issues

### Link

https://demo.sentry.io/issues/4522215778/?alert_rule_id=14346326&alert_type=issue&notification_uuid=9cf8b1ae-220e-495c-b717-339ce09d1ffa&project=5808623&referrer=slack

**Comment by lobsterkatie** [comment]
@scttcper, is this an easy fix?

**Comment by scttcper** [comment]
@malwilley is doing stuff in this area right now and i think working on the v2

**Comment by MichaelSun48** [comment]
Closing this since that Issue Details view is now outdated, and the new Issue Details does not have this same issue
