### ISSUE TITLE
Broken autocomplete/ unable to use event properties for metric alert creation

### ISSUE THREAD

**Issue by rachrwang** [getsentry/sentry#66480]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Search does not auto-complete/ show to the user that event properties can be used:
![image](https://github.com/getsentry/sentry/assets/82916311/e42e742b-b3d4-4d4f-b1ef-41b7ef667302)

### Expected Result

Querying/ auto-complete should work similar to Discover:
<img width="999" alt="Screenshot 2024-03-06 at 2 59 31 PM" src="https://github.com/getsentry/sentry/assets/82916311/0ac509ec-58f8-4790-ab3a-95a3b9aedd6a">

### Actual Result

Ability to create metric alert queries using event properties

### Product Area

Alerts

**Comment by InterstellarStella** [comment]
We have another case where when trying to add `error.unhandled:true`, we see a message indicating it is not supported. However, this event property does exist within our searchable properties.
![image](https://github.com/getsentry/sentry/assets/81985895/46eea922-8b27-4863-bc0b-1f9140009cec)
The metric alert rule will still save successfully.

Another thing that's happening is, if we use `is:unresolved` and `error.unhandled:true`, the alert rule fails to save with message "Internal error. Your query failed to run.". Saving the rule with only either one of the two succeeds.

Trace and resulting error in Sentry's Sentry [here](https://sentry.sentry.io/performance/trace/193101bd928e44c1843f75700e0ed8a0/?field=title&field=event.type&field=project&field=user.display&field=timestamp&homepage=true&id=17492&name=&node=error%3Ab9c4af98ebf24e7f99bd43d5f22b9748&project=-1&query=id%3A%22044e4cabca414ce7b51fb6d9ced10e1a%22&sort=-timestamp&statsPeriod=24h&timestamp=1711111830.668&topEvents=5&yAxis=count%28%29).

**Comment by fredyalexander** [comment]
Hello,

I have the same error described from @InterstellarStella 
![image](https://github.com/getsentry/sentry/assets/58709061/e311df4c-2786-4b18-8331-c74dd7eccf59)
