### ISSUE TITLE
[Replay] Investigate `canvas` performance issue

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#66519]
When a replay is long or the canvas images are large, the playback experience is degraded.

Examples: https://github.com/getsentry/team-replay/issues/399

A solution was proposed here: 
* https://github.com/getsentry/sentry/issues/66472

But includes some assumptions. So before we can go ahead with a specific solution we need to further analyze the issue.

**Comment by billyvg** [comment]
Dupe of https://github.com/getsentry/sentry/issues/65792
