### ISSUE TITLE
Sentry requesting unknown symbols

### ISSUE THREAD

**Issue by AfterThunk** [getsentry/sentry#66543]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

# Our Setup
- Sentry Self Hosted running on Docker.

- An additional Symbolicator instance running in Docker that acts as our Symbol Server.

- An NGINX proxy that sits in front of Symbolicator, and also statically serves the symbol files. A host volume is mounted to a local path that contains the symbols.

All of these are running on the same machine.

As a part of our CI/CD, we use Symsorter to generate the symbols, and these are then copied over to the path that is mounted in the Docker container running NGINX.

Our project is Unreal Engine based, and we're using 0.15.1 Sentry Unreal Plugin.

This works _most of the time_

# The Problem
Occasionally, Sentry will start requesting files that don't exist. When this happens, it causes Symbolicator to block our local Symbol Proxy / Cache, and then legitimate crashes fail to Symbolicate with errors like this:

![image](https://github.com/getsentry/sentry/assets/26654843/507c1b6f-5a9c-49d6-85c0-d85adda66307)

`2024-03-06T21:28:44.296783833Z  INFO stackwalk_minidump:fetch_object_file:fetch_file: symbolicator_service::download: Blocking host due to too many download failures host=REDACTED block_time=1day file_id=HTTP source 'e026b4be-65c9-4e31-b473-898c714801ae' location '4d/43cab87cb573b14b1f37ffeaf274731/debuginf_' file_id=HTTP source 'e026b4be-65c9-4e31-b473-898c714801ae' location '4d/43cab87cb573b14b1f37ffeaf274731/debuginf_'`

It looks like at least some of these files are redundant requests that Sentry makes, where it'll request something like `executabl_` and then immediately request `executable`.

I don't think that's the main issue, however. My assumption is that when engineers are testing builds they've made locally, if those builds happen to cause issues that get reported to sentry, that causes problems. In this case, symbols never would have been uploaded (we have automatic symbol uploading disabled).

### How are you getting stuck?

I think one of the following would help us, if my assumptions above are correct:

- A way to block Sentry from sending reports for local builds. I think this is something I can work out on my end, because our CI/CD system is already injecting some additional version information into the builds, and I can check for the existence of that.

- A way to tell Sentry or Symbolicator never to block a particular server. I'd rather have it always query and fail.

As far as confirming my assumptions, it would be nice if there was an easy way to trace back what Symbolication request ultimately triggered the requests that caused the server to get blocked. Maybe this is already possible in the logs, and I just haven't pieced it together yet.

### Where in the product are you?

Issues

### Version

24.2.0

**Comment by scefali** [comment]
I am going to have the processing team take a look at this on Monday

**Comment by loewenheim** [comment]
I opened https://github.com/getsentry/symbolicator/pull/1407 in the Symbolicator repo that might address your problem in the immediate term:
1. It lets you switch off the denylist entirely by setting `deny_list_enable` to `false`.
2. If you still want to use the denylist and just don't want it to block your own symbol server, you can add the URL to `deny_list_never_block_hosts`.

**Comment by Swatinem** [comment]
> Maybe this is already possible in the logs, and I just haven't pieced it together yet.

I believe we are already capturing those errors. In general such requests would have to fail repeatedly for it to be blocked.

**Comment by AfterThunk** [comment]
Somewhat related, is there a way to request Sentry try to re-symbolicate a given crash? I.E., if I get these issues fixed, and assuming all of the symbols are still around, it would be nice to go back to some of these reports and ask Sentry to try again.

**Comment by loewenheim** [comment]
That would work via [reprocessing](https://docs.sentry.io/product/issues/reprocessing/), although I'm not sure how that works on self-hosted.
