### ISSUE TITLE
Ability to send alerts to multiple slack channels

### ISSUE THREAD

**Issue by keithhalterman** [getsentry/sentry#6654]
Currently each project in sentry can only send slack alerts to one channel. This isn't very helpful for triaging the severity of the issue or routing it to the correct place.  We would like to be able to set up rules that send alerts to varying channels.

*Send a notification via slack **to #RedSquad***

**Context:**
Our #Tech911 channel was drowning in noise, so now we only send high priority issues, but we would like to be able to send non-critical issues as alerts to other channels.

**The ideal:**
#Tech911 - Issues that impact many users
#RedSquad - Issues with tag `squad:red`
#BlueSquad - Issues with tag `squad:blue`

![alert rules](https://user-images.githubusercontent.com/6403394/33397073-b974868a-d507-11e7-84df-cee7b7548c14.png)

**Comment by LyleScott** [comment]
I am in the same boat. I want to filter certain environments to different slack channels.

**Comment by 0xdiba** [comment]
Is this issue planned for implementation any time soon ?

**Comment by EvanPurkhiser** [comment]
This is implemented in the [new slack integration!](https://blog.sentry.io/2018/04/02/sentry-plus-slack)

**Comment by keithhalterman** [comment]
@EvanPurkhiser Looks like the New Slack Integration is in Sentry 8.23.0, which hasn't been released yet. We're self hosted, so we don't have this feature yet. Do you have an estimate for when 8.23.0 will be released? (Sentry was releasing monthly but hasn't since November).  https://github.com/getsentry/sentry/releases

**Comment by Kolyunya** [comment]
@EvanPurkhiser @dcramer I've just tested this new Slack integration and it's just awesome.

But it's not applicable for business notifications. I'll explain what I mean. I want to use `info` level logs of some business events and send them to slack via sentry.

This would not work in a current design since each and every `info` log must be delivered to slack, but sentry would allow to send the same event at most once in 5 minutes.

Any chances that the rule system will allow to send each and every particular event to slack?

**Comment by dcramer** [comment]
@Kolyunya it is unlikely we'll ever allow "every event" to go to Slack. There's only a few cases where you'd want that, and there's many cases where you'd shoot yourself in the foot (and more importantly, anger the Slack Gods). There is a world where you could do this yourself through upcoming service hooks, but we haven't yet decided how we're going to support those for customers (e.g. will it be free for everyone? a paid upgrade? etc etc)

**Comment by Kolyunya** [comment]
@dcramer thanks for a quick response. I got it. Regarding the `few cases where you'd want that` I can name a dozen of cases in which I'd use that. I'd like many `info` events to be routed to different slack destinations via the standard logging system. And of'course I'd pay for that convenience opposed to implementing a custom slack application. Looking forward for this feature!

**Comment by JJBocanegra** [comment]
This feature isn't released yet? When will it be done?

**Comment by dcramer** [comment]
This ya been supported for quite a long time now.
