### ISSUE TITLE
Can't parse localhost IPv6 address for user

### ISSUE THREAD

**Issue by TheDevMinerTV** [getsentry/sentry#66549]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Initialize Sentry SDK
2. Create Hub
3. Configure scope with a new user with the IP address `[::1]:59427
`.
4. Capture a message in that scope

### Expected Result

`user.ip_address` to not get discarded and just show the IPv6 address.

### Actual Result

![image](https://github.com/getsentry/sentry/assets/29845135/19fc2a8e-2f06-42f1-8372-9f5d7d626c20)
![image](https://github.com/getsentry/sentry/assets/29845135/6bb04bd7-6bf7-4bc0-ba76-09d220093182)

### Product Area

Other

### Version

24.2.0

**Comment by vartec** [comment]
@TheDevMinerTV this is expecting an IP address not a socket address, thus `"::1"` without a port works fine.
