### ISSUE TITLE
User feedback not working - API returns HTTP 400

### ISSUE THREAD

**Issue by verglor** [getsentry/sentry#6657]
The request to https://`host`/api/embed/error-page/?eventId=`eventId`&dsn=`publicDsn` returns HTTP 400
in Sentry 8.22.0 causing user feedback not working.
`host`, `eventId` and `publicDsn` are correct - double checked.
No error or warning is logged anywhere.

**Comment by mattrobenolt** [comment]
Did this work for you in 8.21?

**Comment by verglor** [comment]
I didn't try another version

**Comment by dcramer** [comment]
Closing as old, and #8997 returns several error messages.
