### ISSUE TITLE
Remove /activity/ page

### ISSUE THREAD

**Issue by mrduncan** [getsentry/sentry#66598]
The https://sentry.sentry.io/activity/ page hasn't been linked to from anywhere for a long time and has a lot of missing data even when it's loaded. We should clean things up by removing it.
```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/67887
- [ ] https://github.com/getsentry/sentry/issues/67888
```

**Comment by vartec** [comment]
This page/endpoint are still being used, [423 calls from 16 organizations in last two weeks](https://console.cloud.google.com/logs/query;query=jsonPayload.view%3D%22sentry.issues.endpoints.organization_activity.OrganizationActivityEndpoint%22%0A%0A), including one organization very actively using it (325 calls in last two weeks). 

I'll follow up with API team for a plan to properly deprecate.
