### ISSUE TITLE
Monitor task dispatch minute skipped

### ISSUE THREAD

**Issue by IvanovOleg** [getsentry/sentry#66592]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Changing helm chart values doesn't introduce issue. 

### How are you getting stuck?

I have a sentry deployed to the openshift cluster using the helm chart as an ArgoCD application. On each app sync execution, helm chart runs a set of jobs and restarts worker and web. If there is no sync events after the very first deployment, there is no issues in the internal projects. After the sync, one issue appears there and doesn't want to go away. "Monitor task dispatch minute skipped". Could you please tell me how I can fix it and what component is responsible for this?

### Where in the product are you?

Issues

### Version

24.1.2

**Comment by leeandher** [comment]
I'm not the most familiar with how much your infrastructure may be affecting the issue, but [it appears as though Sentry](
https://github.com/getsentry/sentry/blob/master/src/sentry/monitors/tasks.py#L171-L177) is capturing this message internally to track skipped monitor polls. Do you know of any reason why Sentry may be unable to schedule these task runs every minute?
