### ISSUE TITLE
CircleCI workflow `releases set-commits` fails with object not found

### ISSUE THREAD

**Issue by toote** [getsentry/sentry#66600]
### Environment

Running in CircleCI image cimg/python:3.8 using latest CLI (verified with 2.28.6 and 2.30.0):

### Steps to Reproduce

* Create a the steps for releases as described in the official documentation to do so from CircleCI https://docs.sentry.io/product/releases/setup/release-automation/circleci/
* Run the CircleCI workflow

### Expected Result

Release is created as normal

### Actual Result

When running `sentry-cli releases set-commits $VERSION --auto --ignore-missing` the following error occurs:

```
error: object not found - cannot read header for (<SHA that is not the commit ID>); class=Odb (9); code=NotFound (-3)
```

The job had been working without issues and no changes 10 days ago.

### Logs

[sentry.log](https://github.com/getsentry/sentry-cli/files/14529334/sentry.log)

**Comment by toote** [comment]
Working on this with support it looks like the issue is a change done on CircleCI's side to speed up checkout steps: https://discuss.circleci.com/t/product-update-speeding-up-code-checkout/50317

The error is probably the internal implementation trying to read information out of the git repository assuming it has a _normal_  repository. While this is obviously an issue on CircleCI's side, it may be a good idea to have this as an enhancement to the sentry-cli tool so that the error reported is not so cryptic

**Comment by alimony** [comment]
I don't use CircleCI and have not changed anything about my workflows, so would love any other hints on what the issue might be.

**Comment by schew2381** [comment]
Closing as this appears to be rolled back on CircleCI's side
