### ISSUE TITLE
Do not change the alert ID if it gets saved

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#66622]
When someone edits a metric alert while there is an active incident it will trigger the "resolved" action and it may be why the webhook sends the "wrong" ID. Every time an alert is edited it will get a new id.

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2123) by [Unito](https://www.unito.io)

**Comment by Dhrumil-Sentry** [comment]
Thanks for this bug report, We'll work on this, We expect to fix this in the next 2-3 weeks

**Comment by yuval-sentry** [comment]
This issue could be implemented together with this request:
https://github.com/getsentry/sentry/issues/65878

**Comment by ceorourke** [comment]
This is due to the snapshotting behavior we have currently. ACI will change this such that instead of there being active incidents for a metric alert rule there will simply be a metric issue instead and we don't have the snapshotting.

**Comment by yuval-sentry** [comment]
@armenzg @ceorourke The customer brought this up again, is there any chance that the alert id will remain the same?

**Comment by ceorourke** [comment]
If they don't edit active metric alert rules the id will not change. After the project we're working on now this will no longer be the case but it will be some months until it's done.
