### ISSUE TITLE
the default size and location of the Feedback button conflicts with the WebXR Immersive/AR button placement in all browsers

### ISSUE THREAD

**Issue by matthargett** [getsentry/sentry#66636]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. add the FeedbackIntegration to your Sentry-enabled WebXR application
```js
Sentry.init({
	dsn: '<redacted>',
	maxBreadcrumbs: 50,
	attachStacktrace: true,
	enabled: environment.production,
	environment: environment.production ? 'production' : 'development',
	integrations: [
		// profiling requires setting `Document-Policy: js-profiling` in response header, which GitHub Pages doesn't support
		// Sentry.browserProfilingIntegration(),
		Sentry.browserTracingIntegration(),
		Sentry.feedbackIntegration({
			colorScheme: 'system',
			isEmailRequired: false,
			isNameRequired: false,
		}),
	],
});
```

2. load your application in an XR headset with gaze-based focus management, like the Apple Vision Pro or Pico 4 Enterprise (this is also visible in controller-focused XR headsets, but only a showstopper with gaze)

### Expected Result

Ideally, the feedbackIntegration would detect ﻿the existing button and it's Z-index, and position itself so as to not conflict with an existing interactive element on the screen.
<img width="452" alt="image" src="https://github.com/getsentry/sentry/assets/1550766/db5bbee6-6431-47ed-8262-48dc75dafa0e">

Alternately, a configuration prop for the feedbackIntegration for adjusting the size, inset from the edge of the browser window/surface, or something like that, so that I could manually adjust it would be nice.

### Actual Result

The `Report a Bug` button overlaps the Enter Immersive button in such a way that gaze-based headsets like Apple Vision Pro and Pico 4 Enterprise almost always accidentally trigger the Report a Bug button. This is also annoying on controller-based headsets, but is a showstopper on gaze-based headsets.
![image](https://github.com/getsentry/sentry/assets/1550766/70c8c8fa-0df0-4cfc-8e4e-182ad2cd9aae)

### Product Area

User Feedback

**Comment by bruno-garcia** [comment]
Our solution to this problem today is the API we provide so you can have your own button that triggers the widget.
https://docs.sentry.io/platforms/javascript/user-feedback/configuration/#bring-your-own-widget

You can also align the widget on a separate part of the UI: https://docs.sentry.io/platforms/javascript/user-feedback/configuration/#additional-ui-customization

**Comment by c298lee** [comment]
@matthargett with SDK version 8.0.0, you can now configure the inset of the button by setting the CSS variable `--inset`: https://docs.sentry.io/platforms/javascript/user-feedback/configuration/#css-customization

**Comment by bruno-garcia** [comment]
Sounds like @c298lee's message addressed this, so we're closing. Let us know if that's not the case by reopening it.
