### ISSUE TITLE
Dashboard - Increase Line Chart Granularity to 1min

### ISSUE THREAD

**Issue by Prithvirajkumar** [getsentry/sentry#66645]
### Problem Statement

Currently, when creating a line chart widget in Sentry Dashboards to display transaction durations, the granularity of the chart is set to 5 minutes when the time range is 1 hour as seen below:
![Screenshot 2024-03-08 at 7 43 48 PM](https://github.com/getsentry/sentry/assets/56081556/cd7fae11-dfa3-44bd-bafb-87a43e9ccca6)

![Screenshot 2024-03-08 at 7 43 58 PM](https://github.com/getsentry/sentry/assets/56081556/77775b96-2bc5-4867-94ea-5a37b55d6481)

This means that each data point on the chart represents an interval of 5 minutes, which might not provide the desired level of detail for monitoring transaction performance, especially in scenarios where more granular insights are required. 

That being said, within Discover, with the same conditions, the granularity is 1 minute as seen below:
![Screenshot 2024-03-08 at 7 44 19 PM](https://github.com/getsentry/sentry/assets/56081556/b7a7a242-328e-4a77-b126-915af69e4d4c)

![Screenshot 2024-03-08 at 7 44 28 PM](https://github.com/getsentry/sentry/assets/56081556/86affc4c-15eb-420d-8f59-8d9c93db1879)

### Solution Brainstorm

To enhance the usability and effectiveness of the transaction durations widget, the proposal is to increase the granularity of the line chart to 1 minute when the time range is set to 1 hour within Dashboards. This adjustment will allow users to visualize transaction performance with finer detail, enabling them to identify and analyze performance trends more accurately.

This is particularly useful for users that would use Dashboards as the primary view when using Sentry.

### Product Area

Dashboards

**Comment by narsaynorath** [comment]
Hey @Prithvirajkumar, just updating you to know that we're looking at changing this for the 1hr time range. Agreed that at 1hr the interval look a bit too coarse to get good insights.

**Comment by narsaynorath** [comment]
@Prithvirajkumar this is deployed now! Users should be able to see 1m granularity for 1hr time range
