### ISSUE TITLE
Distribution percentile performance

### ISSUE THREAD

**Issue by obostjancic** [getsentry/sentry#66665]
Originally reported in JAVASCRIPT-2S0J 

Reproduced with [p90(transaction.duration)](https://sentry.sentry.io/ddm/?project=1&statsPeriod=7d&widgets=%5B%7B%22mri%22%3A%22d%3Atransactions%2Fduration%40millisecond%22%2C%22op%22%3A%22p90%22%2C%22query%22%3A%22%22%2C%22groupBy%22%3A%5B%5D%2C%22powerUserMode%22%3Afalse%2C%22type%22%3A1%2C%22id%22%3A0%2C%22displayType%22%3A%22line%22%2C%22focusedSeries%22%3A%5B%5D%2C%22sort%22%3A%7B%22order%22%3A%22asc%22%7D%2C%22isHidden%22%3Afalse%7D%5D) that took 40s to load. Full trace available [here](https://sentry.sentry.io/performance/trace/a13928c236aa41d6b4d05132d2ef2d2e/?limit=100&pageEnd=2024-03-11T06%3A35%3A11.053&pageStart=2024-03-10T06%3A34%3A41.048)

**Comment by iambriccardo** [comment]
This ticket might address the performance: https://github.com/getsentry/snuba/pull/5610

**Comment by mitsuhiko** [comment]
Can reproduce this, still happens. Can't tell what the query is, but this comes back really slow from running the query in clickhouse.

**Comment by jernejstrasner** [comment]
Just repro'd this. Percentiles are slow and error out eventually.

**Comment by iambriccardo** [comment]
We will discuss this ticket in an internal meeting with sns team.

**Comment by HazAT** [comment]
Closing this for now, we'll create follow up items if needed
