### ISSUE TITLE
Get internal Server Error

### ISSUE THREAD

**Issue by orosi** [getsentry/sentry#6667]
Hi ,
We get an internal Server Error when we assign Issues to users
status=500 body={'detail': 'Internal Error', 'errorId': '09247249f7024aed9fd0a39e138ad0b8'}
when page was reloaded the issue was assigned succesfully.
Also Stats Graphs are empty.
We upgraded from Sentry 8.18.0 to fix this issues but it dosent help
"sentry upgrade" run without errors
we run on postgres 
REINDEX SYSTEM sentry;
REINDEX DATABASE sentry;     
VACUUM (FULL, ANALYZE);    
All without fixing this issues
many thanks for help
oliver

Software:
Ubuntu-16.04
Sentry 8.20.0
postgresql-9.5
Redis server v=4.0.2

**Comment by mattrobenolt** [comment]
Can you share the full error? By itself, there’s nothing I can do here.

**Comment by orosi** [comment]
Do need more infos?
thanks for the quick answer 

[sentry-web.log](https://github.com/getsentry/sentry/files/1522090/sentry-web.log)
![error_assign](https://user-images.githubusercontent.com/8320771/33490431-6ae3f724-d6b7-11e7-820c-570e5af9ce00.png)

raven.js:1061 PUT https://sentry.pool4tool.com/api/0/issues/14401/ 500 (INTERNAL SERVER ERROR)
(anonymous) @ raven.js:1061
send @ jquery.js:8630
ajax @ jquery.js:8166
value @ api.jsx:95
value @ api.jsx:130
value @ api.jsx:212
assignTo @ assigneeSelector.jsx:133
handleClick @ menuItem.jsx:27
o @ ReactErrorUtils.js:26
a @ EventPluginUtils.js:89
c @ EventPluginUtils.js:112
p @ EventPluginHub.js:44
d @ EventPluginHub.js:55
o @ forEachAccumulated.js:25
processEventQueue @ EventPluginHub.js:231
o @ ReactEventEmitterMixin.js:18
handleTopLevel @ ReactEventEmitterMixin.js:29
i @ ReactEventListener.js:73
perform @ Transaction.js:138
batchedUpdates @ ReactDefaultBatchingStrategy.js:63
i @ ReactUpdates.js:98
dispatchEvent @ ReactEventListener.js:150
o @ raven.js:321

**Comment by mattrobenolt** [comment]
I need the server logs for the 500 error. The JS error doesn’t tell me anything.

**Comment by orosi** [comment]
Add Serverlogs from the last start
11:38:00 [ERROR] django.request: Internal Server Error: /avatar/d9e94e6e46164449980c9a10c42c1729/ (status_code=500 request=<WSGIRequest: GET u'/avatar/d9e94e6e46164449980c9a10c42c1729/?s=48'>)
this was copied from attached logfile
[sentry-web.log](https://github.com/getsentry/sentry/files/1526891/sentry-web.log)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
