### ISSUE TITLE
Improve distributed tracing for hybrid cloud RPC calls

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry#66701]
### Problem Statement

https://getsentry.atlassian.net/browse/INC-667

https://www.notion.so/sentry/INC-667-Sourcemap-uploading-does-not-work-b3b5ad07a7e240d185de03a5a0b4f48b

We had an incident regarding sourcemaps uploading where we found it hard to have visibility due to lack of distributed tracing in RPC calls.

Here's an example transaction where we don't see traces propagated properly: https://sentry.sentry.io/performance/sentry:70e7ae1b98304100888eca2d0775685d/?project=1&query=transaction.duration%3A%3E5000+title%3A%2Fapi%2F0%2Forganizations%2F%7Borganization_slug%7D%2Fprojects%2F+event.type%3Atransaction&statsPeriod=24h&transaction=%2Fapi%2F0%2Forganizations%2F%7Borganization_slug%7D%2Fprojects%2F#span-82e4e774024e00b3

In this case there is no transaction that represents `POST http://sentry-rpc-prod-control.us.sentry.internal:8999/api/0/internal/rpc/user/get_many/`

<img width="924" alt="image" src="https://github.com/getsentry/sentry/assets/18689448/19ffd5e5-1c3e-4e57-968f-fd81b9b0e726">

### Solution Brainstorm

Understand why it doesn't work for some scenarios and make a comprehensive fix.

### Product Area

Other

**Comment by AbhiPrasad** [comment]
Here's an example of HC RPC call that should get a distributed trace attached to it https://sentry.sentry.io/performance/sentry:d11f9ab194ad47e894384b78008e815b/?project=1&query=http.method%3APOST&referrer=performance-transaction-summary&statsPeriod=24h&transaction=%2Fapi%2F0%2Finternal%2Frpc%2F%7Bservice_name%7D%2F%7Bmethod_name%7D%2F&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29

<img width="734" alt="image" src="https://github.com/getsentry/sentry/assets/18689448/b9f152f2-97f1-4e65-a0ac-5c187b577443">

Ideally we also improve the transaction name to ensure that we are more specific (remove paramaterization to include `service_name` and `method_name` directly)

**Comment by AbhiPrasad** [comment]
Relevant links:

https://github.com/getsentry/sentry/blob/bdf51dcb1dc868daeac2a8f815664c9682c12a65/src/sentry/hybridcloud/apigateway/proxy.py#L147-L174

https://github.com/getsentry/sentry/blob/bdf51dcb1dc868daeac2a8f815664c9682c12a65/src/sentry/silo/util.py#L18

**Comment by sl0thentr0py** [comment]
preliminary investigation of above linked transaction (internal/rpc):

we're getting two `sentry-trace` headers joined with a comma incomin
```
sentry-trace: 6a5871d13d8441818ccc593c6c3b07c8-b252c3821bdbaceb-1, 6a5871d13d8441818ccc593c6c3b07c8-88529d2712c386fd-1
```

which causes the extract function to fail silently while parsing and start a new trace

```python
>>> from sentry_sdk.tracing_utils import extract_sentrytrace_data as extract
>>> header1 = "6a5871d13d8441818ccc593c6c3b07c8-b252c3821bdbaceb-1"
>>> header2="6a5871d13d8441818ccc593c6c3b07c8-b252c3821bdbaceb-1, 6a5871d13d8441818ccc593c6c3b07c8-88529d2712c386fd-1"
>>> extract(header1)
{'trace_id': '6a5871d13d8441818ccc593c6c3b07c8', 'parent_span_id': 'b252c3821bdbaceb', 'parent_sampled': True}
>>> extract(header2)
>>> 
```

todos

* investigate why we're getting two headers
* improve SDK handling
  *  guard against this on incoming - if we get two sentry-trace headers like this, we should just pick the first one (same with baggage, also duplicated but might need to process that smartly)
  * guard against this on outgoing - if sentry-trace already exists, don't inject further sentry-trace/baggage on that request

**Comment by sl0thentr0py** [comment]
double adding headers in the rpc request has been removed 
https://github.com/getsentry/sentry/pull/66789

**Comment by AbhiPrasad** [comment]
Okay so with the above change we seem to be getting RPC calls correctly traced.

but there is def some scope/trace ID leakage now: https://sentry.sentry.io/performance/trace/0247865c290144a8bd63ddfda017c0fc/?limit=100&pageEnd=2024-03-14T04%3A50%3A41.175&pageStart=2024-03-13T04%3A50%3A41.161

**Comment by sl0thentr0py** [comment]
this trace leakage keeps showing up since twp fwiw

**Comment by AbhiPrasad** [comment]
Closing because RPC tracing seems to be working on. We can investigate the scope/trace leaks with another investigation/issue.
