### ISSUE TITLE
Settings Auth Tokens says 'never used' for org tokens that get used

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#66703]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. create auth tokens
2. use them for uploading ios android debug symbols and js sourcemaps
3. wait a bit, check Org Settings > Auth tokens.
see link for exact org slug and so forth
https://www.notion.so/sentry/Org-Auth-Tokens-Reported-as-never-used-6405889a98ad461c8a4c9bd1bfd3762f?pvs=4

### Expected Result

it should say it was used

### Actual Result

it says it was not used

### Product Area

Settings - Auth

### Link

https://monzo.sentry.io/settings/auth-tokens/

**Comment by leeandher** [comment]
Thanks for the report, this is definitely a bug and I'll be working on fix for this soon.

**Comment by thinkocapo** [comment]
related to https://github.com/getsentry/sentry/issues/67038 and fixed by https://github.com/getsentry/sentry/pull/67147
