### ISSUE TITLE
Does sentry will support one month stats?

### ISSUE THREAD

**Issue by istommao** [getsentry/sentry#6675]
sentry: 8.10.0

![image](https://user-images.githubusercontent.com/5070879/33534042-01b0a2c2-d8e0-11e7-9942-175c696e0ec9.png)

Does sentry will support one month stats?
now it's only support 1 hour 1 day 1 week statistical

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
