### ISSUE TITLE
Cron monitor timezones not using daylight saving time adjustment

### ISSUE THREAD

**Issue by DaveHasteSpringer** [getsentry/sentry#66763]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. During non-DST (i.e. before 10th March 2024), configure a cron monitor on a schedule specified in the `America/New_York` timezone
2. Observe the monitor running at the correct schedule for that timezone (i.e. EST)
3. Wait until DST comes into effect (i.e. 10th March 2024)
4. Observe that the monitor runs at an incorrect time: one hour early in EDT (which is now the correct timezone for `America/New_York`)

### Expected Result

I would expect the cron monitor to continue run at the configured time, taking Daylight Saving Time adjustments into account.

### Actual Result

In February I set up a monitor to run daily at 07:00 in the `America/New_York` timezone (which was EST at the time). It ran on schedule, as expected.

A few days ago, New York moved into DST (Daylight Saving Time), so the local time became EDT (i.e. no longer EST). Unexpectedly, the monitor doesn't seem to take the move to DST into account, so it now runs at 06:00 EDT, which is incorrect.

The attached screenshots from the Sentry web UI show that the configuration is specified correctly, but that an issue was raised one hour too early.

**Config (correct):**
<img width="337" alt="Screenshot 2024-03-12 at 10 44 09" src="https://github.com/getsentry/sentry/assets/8331190/d378d2b7-8aa8-4b55-9cc1-13fe9cb4bc37">

**Issue raised (incorrect):**
<img width="551" alt="Screenshot 2024-03-12 at 10 44 32" src="https://github.com/getsentry/sentry/assets/8331190/b3bd30c5-82e1-4f0f-8631-394908f59be4">

### Product Area

Crons

### Link

https://springernature.sentry.io/crons/eus-weeknight-startup/

**Comment by evanpurkhiser** [comment]
Hi @DaveHasteSpringer -- Is it continually reporting these since the timezone change on March 10th? I assume yes since in your screenshot I see it was reported this morning.

**Comment by evanpurkhiser** [comment]
Oh, I see, your schedule declares that today would have been the first day after the timezone change.

Let me investigate further. I suspect the computation for the next check-in may be failing to fully consider timezones.

**Comment by DaveHasteSpringer** [comment]
@evanpurkhiser It seems that this problem manifested itself for two consecutive days (from 10th March onwards), for all of the cron monitors we have set up in the New York timezone.

However, as of last night, I can see that _some_ of the cron monitors that we have in that timezone have started running at the correct time.

**Comment by evanpurkhiser** [comment]
Unfortunately looks like there's a bug in the library we're using to compute schedules :(

https://github.com/taichino/croniter/issues/147

I would have expected it to resolve itself after the first time it marks the monitor as missed, however. When you say it manifested for two days in a row, are you talking about monitors with a different schedule than the example you have in your original report? In the original report, the schedule is `0 7 * * 2-5` which means when the last check-in occurred on Friday it would compute the next expected check-in for this past Tuesday (the 10th was a Sunday). So after Tuesday (once the miss happened) it should have correctly computed the next check-in time as Wednesday at 7am EDT.

I'm going to spin this out into a more detailed ticket where we can figure this out, we'll likely have to spend some time contributing to the upstream library to get this fixed (though it's [looking complicated](https://github.com/kiorky/croniter-fork/pull/34))

**Comment by evanpurkhiser** [comment]
Closing in favor of https://github.com/getsentry/sentry/issues/66868

**Comment by DaveHasteSpringer** [comment]
> I would have expected it to resolve itself after the first time it marks the monitor as missed, however. When you say it manifested for two days in a row, are you talking about monitors with a different schedule than the example you have in your original report?

Sorry, yes I should have been more specific. We have several cron monitors in the New York timezone (as well as many more in other timezones), and I can see that each of them ran once at the wrong time (across a total time span of a couple of days), but each has since resumed running at the correct time.

So that behaviour does indeed seem to align with your expectation that it resolves itself after the first miss.
