### ISSUE TITLE
Opening User feedback should take me to the Quote first

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#66786]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Open an user feedback.

### Expected Result

I see the quote first

### Actual Result

See Tags instead 

### Product Area

User Feedback

**Comment by jas-kas** [comment]
FYI @ryan953 @michellewzhang

**Comment by jas-kas** [comment]
Replay of this happening for me: https://sentry.sentry.io/replays/673287b7df3d42458f0a5c027be0e827/?project=11276&query=user.email%3Ajasmin.kassas%40sentry.io&referrer=%2Freplays%2F%3AreplaySlug%2F&statsPeriod=90d&yAxis=count%28%29&t=67
