### ISSUE TITLE
limit commit message length in suggested owners tooltip

### ISSUE THREAD

**Issue by macqueen** [getsentry/sentry#6687]
otherwise it can bleed off the page

**Comment by mattrobenolt** [comment]
It also doesn't preserve any whitespace formatting from the message itself. So maybe if this is being addressed, that'd be nice too. 👍

**Comment by benvinegar** [comment]
I think we need a whole new custom component for this.

Can we get a screenshot, btw?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
