### ISSUE TITLE
Allow OpenAI model to be customized

### ISSUE THREAD

**Issue by max-wittig** [getsentry/sentry#66884]
### Problem Statement

We've noticed that Sentry now has support for AI suggestions inside issues.

We can now already configure our in-house OpenAI endpoint via the `OPENAI_BASE_URL` environment variable, but sadly we cannot configure the model that is used. In our case: `mistral-7b-instruct`. 

See: https://github.com/getsentry/sentry/blob/05e6601a823fb35b21ef8ba79a07da68bf67cb08/src/sentry/api/endpoints/event_ai_suggested_fix.py#L264

Is this something that you would consider adding as a setting?

### Solution Brainstorm

add setting to sentry.conf.py to allow the configuration of the model used.

### Product Area

Issues

**Comment by vartec** [comment]
Seems like a reasonable ask. @max-wittig thank you for your suggestion.

**Comment by vartec** [comment]
@max-wittig in #66990 I've added `SENTRY_AI_SUGGESTED_FIX_MODEL` to configured by environment
variable or directly as a Django setting.
