### ISSUE TITLE
Custom dashboards with ability to change time frame 

### ISSUE THREAD

**Issue by bfpepper87sentry** [getsentry/sentry#66891]
### Problem Statement

Right now default visualizations within the Sentry UI have the ability to change the timeframe a user is viewing. The dashboards a user creates do not have this functionality. Can we look into what it would take to be able to change the timeframe in custom dashboards. 

### Product Area

Unknown

**Comment by gggritso** [comment]
@bfpepper87sentry thanks for raising this! What do you mean by "timeframe"? Dashboards have a time selector at the top where you can choose the start and end date for the data, do you need other time controls?

<img width="591" alt="Screenshot 2024-03-15 at 3 54 11 PM" src="https://github.com/getsentry/sentry/assets/989898/d942733a-fe32-4232-a3ba-1cbcda3da7b0">

**Comment by DominikB2014** [comment]
hey @bfpepper87sentry 
It looks the functionality you described is already supported by dashboards, if you think we misunderstood that, feel free to open a new issue!
