### ISSUE TITLE
Geolocation filter for session replays

### ISSUE THREAD

**Issue by nthgol** [getsentry/sentry#66890]
### Problem Statement

Like Full Story, would like to be able to search for session replays by region, like "USA". 

### Solution Brainstorm

Use geolocation services

### Product Area

Replays

**Comment by jas-kas** [comment]
Hey @nthgol 👋 

Thanks for your feature request! I've documented it in [this ticket.](https://github.com/getsentry/sentry/issues/67001)

Could you share a little more on your use-case for searching by geolocation? When would this be especially important to you?

**Comment by jas-kas** [comment]
@nthgol Closing this for now - please add any follow ups to https://github.com/getsentry/sentry/issues/67001 :)
