### ISSUE TITLE
Crons using log_error_if_queue_has_items broken with AMQPS

### ISSUE THREAD

**Issue by maths22** [getsentry/sentry#66917]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Configure BROKER_URL to use the amqps:// protocol
2. See AssertionError: queues monitoring is not enabled logged from both crons that use log_error_if_queue_has_items

It would appear that https://github.com/getsentry/sentry/blob/master/src/sentry/monitoring/queues.py needs to be updated to handle amqps urls correctly.  (We are running into this because we are using AWS-hosted managed RabbitMQ, which requires TLS connections.)

### Expected Result

Those crons should not break: log_error_if_queue_has_items should handle AMQPS urls

### Actual Result

<img width="1223" alt="image" src="https://github.com/getsentry/sentry/assets/3067361/de8bdfb3-4a88-481e-93d9-8f98338694ea">

### Product Area

Unknown

### Version

24.1.2

**Comment by gaprl** [comment]
Redirecting to issues team, they'd be the owners here.

https://github.com/getsentry/sentry/blob/51cbe95d93915e4111486997e8c71c9274dfbaa5/src/sentry/tasks/auto_ongoing_issues.py#L37

https://github.com/getsentry/sentry/blob/51cbe95d93915e4111486997e8c71c9274dfbaa5/src/sentry/tasks/auto_ongoing_issues.py#L101
