### ISSUE TITLE
KeyError: 'sentry:latest_version'

### ISSUE THREAD

**Issue by HackToday** [getsentry/sentry#6693]
## General Support

If you're looking for general support, please utilize our [community forum](https://forum.sentry.io/) rather than GitHub Issues.

## Reporting Bugs

When reporting bugs, include details about your configuration, such as:

- The version of Sentry you're using
  8.21-onbuild
- Whether you're using Docker or another installation method
 Docker
- Include a stacktrace or other logs when relevant
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/options/manager.py", line 101, in lookup_key
    return self.registry[key]
KeyError: 'sentry:latest_version'
05:59:24 [DEBUG] sentry: Using legacy key: sentry:latest_version
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/options/manager.py", line 101, in lookup_key
    return self.registry[key]
KeyError: 'sentry:latest_version'

```
- Include a redacted version of your configuration when relevant

 Dockerfile as below:
```
FROM sentry:8.21-onbuild
RUN apt-get update \
  && apt-get install -y \ 
    libldap-2.4.2 \
    libldap2-dev \
    libsasl2-dev \
  && pip install git+https://github.com/Banno/getsentry-ldap-auth.git
```

Then try login with LDAP user and password, it would have such error log about `KeyError`

**Comment by mattrobenolt** [comment]
This isn't a bug. If you notice, it's just a DEBUG level log, and there's nothing wrong here.

**Comment by HackToday** [comment]
The issue is that @mattrobenolt  the LDAP can not work with that exception logs, I did not find other errors in log
