### ISSUE TITLE
Scrub Event.spans.description by default (as part of `**`)

### ISSUE THREAD

**Issue by realkosty** [getsentry/sentry#66932]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Set up an Advanced Scrubbing Rule with a regex that replaces certain kinds of URLs with placeholder text (exact regex doesn't matter as long as it matches some transactions).
2. Set "Source" to `**`
3. Examine a sample transaction to see if rule has applied.

### Expected Result

Every field that commonly contains PII, including `$span.description`, is scrubbed.

### Actual Result

Event.spans.description is NOT scrubbed.
That is consistent with our docs [Event PII Fields doc](https://docs.sentry.io/product/data-management-settings/scrubbing/server-side-scrubbing/event-pii-fields/) but is bad user experience as span description which for auto-instrumented HTTP spans in most SDKs contains `<HTTP_METHOD> <URL>` can easily contain PII. 
Related: https://github.com/getsentry/sentry-docs/pull/9431
<img width="967" alt="Screenshot_2024-03-13_at_3_35_54 PM" src="https://github.com/getsentry/sentry/assets/490201/faa8c0a7-25d7-4388-abf3-f3dda71c09d2">

### Product Area

Settings - Security & Privacy

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2125) by [Unito](https://www.unito.io)

**Comment by iker-barriocanal** [comment]
Resolved on https://github.com/getsentry/sentry-docs/pull/9431.
