### ISSUE TITLE
Custom Slack notification content for Metric Alerts - Add tags like Issue Alerts

### ISSUE THREAD

**Issue by barakgr-cyera** [getsentry/sentry#66937]
### Problem Statement

Bring me the custom summary that I'm interested in of the issue to Slack, instead of having to log into the platform and do initial research myself, just to decide whether I want to deal with the issue now or not.

### Solution Brainstorm

You already support it for issue alerts: 
<img width="949" alt="image" src="https://github.com/getsentry/sentry/assets/97047211/8bcca71a-f1a0-4614-b060-d51939bb5f1d">

Just have the same for Metric alerts instead of this:
<img width="1114" alt="image" src="https://github.com/getsentry/sentry/assets/97047211/f9139cf7-0b63-474b-ba0b-b272bccbece1">

### Product Area

Alerts

**Comment by rachrwang** [comment]
@barakgr-cyera  - can you share more about what you mean re: "custom summary"? And in particular for metric alerts, what would be the information you'd need to understand whether it's something to address now vs. later?

**Comment by barakgr-cyera** [comment]
@rachrwang 
I would like the customer id, and endpoint. Our product is B2C, so there is a wide range of tenant's env' size. 
So for some combinations of endpoint and tenant, we already know we have a performance issue, and we just need to get to it. But if I see a new endpoint having issues, or the same endpoint but with more tenants - I may treat it more urgently.

**Comment by rachrwang** [comment]
Got it, that makes sense! @barakgr-cyera - do you mind linking one of the alert rules you have in mind, so I can take a closer look at the query that's being configured? You can also email a screenshot of the alert config to my email - rachel.wang@sentry.io. Thanks!

**Comment by iamrajjoshi** [comment]
Thanks for this report! This is similar to https://github.com/getsentry/sentry/issues/58921, so closing this. Feel free to upvote the other issue - it helps us prioritize what to do next!
