### ISSUE TITLE
Frontend: Breadcrumbs code cutoff

### ISSUE THREAD

**Issue by benebun** [getsentry/sentry#6694]
On selfhosted Sentry 8.13.0, Firefox 57:
Long breadcrumbs code is cutoff when it wraps, seems to be related to padding on `<td>`:
`ul.crumbs li .table.key-value td.value`

See screenshot gif:
![sentry_code_cutoff](https://user-images.githubusercontent.com/1321740/33599834-a7249a5c-d9a7-11e7-9e12-ab80e7240275.gif)

HTH

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
