### ISSUE TITLE
Uncollapsed object is not scrollable in stacktrace

### ISSUE THREAD

**Issue by darklow** [getsentry/sentry#66954]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When object in stacktrace is uncollapsed, the list with parameters is not scrollable on Mac/Chrome (haven't tested other browsers)
<img width="578" alt="image" src="https://github.com/getsentry/sentry/assets/445304/b1009c3b-341c-4353-ab96-a06c49d6e3e3">

### Expected Result

List with parameters should be scrollable

### Actual Result

Not scrollable

### Product Area

Issues

**Comment by leeandher** [comment]
Thanks for writing in @darklow!

Is this a persistent issue you're facing across the app? I wasn't able to reproduce this and I'm wondering if it may be related to accessing an older version of our frontend. 

The section cut off in the screenshot shouldn't be clipped or render a scroll bar, but instead push down the rest of the page contents to accommodate it.

If you are still having trouble with this, do you mind sharing an Issue ID or link for us to continue to debug this?
