### ISSUE TITLE
Sentry issue page refreshes continuosly

### ISSUE THREAD

**Issue by rpaw053** [getsentry/sentry#6697]
We are using sentry version 8.22.0 docker container, our sentry page refreshes continuously

We found that it is possibly due to getting 401 error while accessing any issue on issue page (e.g: 'https://{hostname}/api/0/projects/sentry/flask/issues/?id=11').

Please let us know your comments on this one.

Note: Our sentry is backed by ssl proxy

**Comment by SachinJanani** [comment]
Even I am also facing same issue @mattrobenolt can you please help
