### ISSUE TITLE
Environment variable not being properly used in UI

### ISSUE THREAD

**Issue by fabiopedrosa** [getsentry/sentry#6699]
We set the environment variable to `testing` and `production`, but the UI doesn't really switch between them here:

![image](https://user-images.githubusercontent.com/88341/33632964-2818b968-da07-11e7-887a-8a0bbc209068.png)

![image](https://user-images.githubusercontent.com/88341/33632943-1a694486-da07-11e7-98d3-f93ca29643e7.png)

You can see I chose different environments using the drop-down, but both the chart and the event is always from productions.

**Comment by YevheniiKravchenko** [comment]
So, looks like UTC time is correct, but relative time is used from latest event within all environments

**Comment by Grannath** [comment]
Same issue here. Running 9.0.0 on-premise.

How is there no update on this? A large part of the UI is fundamentally broken and gives wrong information.

**Comment by Grannath** [comment]
Still no comment? Seriously? This is a major defect. It gives wrong information in one of the most used screens.

**Comment by markstory** [comment]
@Grannath Changing environments appears to be working fine on sentry.io. You will likely have to upgrade to 9.1.0, 9.1.1, or 9.1.2 (when it is ready) to get the fixes for this problem.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
