### ISSUE TITLE
Metrics Graphs Axes / Overlays Lost Their Units

### ISSUE THREAD

**Issue by seanabraham** [getsentry/sentry#67017]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Look at any graph of a metric with a unit such as milliseconds

### Expected Result

I would expect to see the axes and overlay properly labeled according to the unit and bucketing to happen (e.g. see 2s instead of a value of 2000 for a graph with unit milliseconds).

Here's an old screenshot from before where this did work:
![image](https://github.com/getsentry/sentry/assets/1400053/07700cfc-c1f7-45a5-8a86-2dccd1edd66e)

### Actual Result

<img width="1358" alt="image" src="https://github.com/getsentry/sentry/assets/1400053/5481b5cb-0833-4caf-b1f6-c58bdb5c36e3">

### Product Area

DDM

**Comment by iambriccardo** [comment]
We enabled the unit system we developed for all of the customers, the issue should now be fixed. @seanabraham let me know!

**Comment by seanabraham** [comment]
This does indeed look fixed now, thank you!
