### ISSUE TITLE
transactions are bundled togeter in an issue with no apparent reason

### ISSUE THREAD

**Issue by gotenxds** [getsentry/sentry#67124]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Have multiple exception on multiple pages in the UI

The result is that a lot of exceptions that dont seem connected (different pages, different status code, different request) end up all in the same issue

### Expected Result

Get a single issue for every page and error, not one large issue with everything

### Actual Result

![image](https://github.com/getsentry/sentry/assets/3519520/2f7f2b5d-e787-4df7-9d73-ce3e3c323a74)

### Product Area

Issues

### Link

https://panorays.sentry.io/issues/3540341677/events/ae73b68d209947ca8a2595b657edc2c4/?project=5496420&referrer=replay-errors

**Comment by masinette** [comment]
Hello @gotenxds. This looks like a problem with [issue grouping](https://docs.sentry.io/product/data-management-settings/event-grouping/).
Can you reach out to the Support team to open up a ticket, here: [https://help.sentry.io/](https://help.sentry.io/)

**Comment by gotenxds** [comment]
@masinette Thanks for the response, the reason this looks like a bug is because the grouping logic is "in app exception"
But we can see that the exceptions are different,
![image](https://github.com/getsentry/sentry/assets/3519520/11e1694b-8e73-4947-8b2c-4f8006090fd4)

![image](https://github.com/getsentry/sentry/assets/3519520/0ea8110a-9762-436c-a4e3-be87d3a185ed)


Do you still think this is an issue with the way issue grouping is configured?
