### ISSUE TITLE
Add a small filter and select checkbox to the Environments list under Settings

### ISSUE THREAD

**Issue by mvaled** [getsentry/sentry#67141]
### Problem Statement

I would like to quickly, select and hide many obsolete environments in a project.  Currently you must clink on the Hide button of each environment separately.

The screenshot shows the first page of the environments I had to hide one by one.

![Screenshot from 2024-03-18 15-24-18](https://github.com/getsentry/sentry/assets/270825/534405e0-8b16-45a9-be16-61ce2c87025d)

### Solution Brainstorm

Add a checkbox to each line, a filter at the top and a button to Hide/Show the current selection.

### Product Area

Settings - Projects

**Comment by leedongwei** [comment]
Definitely agree that the UX on this page is lacking when an organization has more than just dev/staging/prod. I don't have timelines but we'll schedule this for our rotational crew to take it on.

**Comment by roggenkemper** [comment]
we have another GitHub issue tracking the same request - https://github.com/getsentry/sentry/issues/59270 , will close this issue and use the other one instead
