### ISSUE TITLE
Alert rules quantity limits monitoring

### ISSUE THREAD

**Issue by pavlo-by-MA** [getsentry/sentry#67195]
### Problem Statement

As I've got information from support - Sentry has limit for 1000 alert rules for 1 organization. 

Due to this limit our team would like to know the way of monitoring quantity of alerts for 1 organization slug. Performing such monitoring makes possible to know exact time when number of alerts reaching limit.

### Solution Brainstorm

Add alerts quantity to any API endpoint that will allow parse exact field and create alert rules quantity monitoring. A little similar example described [here](https://docs.sentry.io/api/alerts/create-an-issue-alert-rule-for-a-project/), but there are no alert rules quantity at all.

### Product Area

Alerts

**Comment by leedongwei** [comment]
Make sense. We should surface this in the product UI too.

**Comment by saponifi3d** [comment]
We updated the API to include the `X-Sentry-Alert-Rule-Limit` header when making GET requests for alert rules to include the limit for alert rules. To help make it a little easier to do pagination, we also added the number of alert rules that exist as well: `X-Sentry-Alert-Rule-Hits`.
