### ISSUE TITLE
When inviting users to through the onboarding modal, Billing members should not be added to teams

### ISSUE THREAD

**Issue by ykamo001** [getsentry/sentry#67202]
User feedback:

> It seems one cannot create a billing user by invitation. It just bugs out. I was able to get around it by creating a normal user, then switching it to billing, at which point I received an error "Billing users may not be in any team" or some such. I'm going to guess this is why one cannot invite a billing user.
In the UI there is "Add to team", which has the only team by default. I suppose if I remove this, it'd work. Anyhow, there is no error text in this UI. It just fails and some elements turn red

Update the flow such that if a user tries to invite a Billing member we should remove the default team

**Comment by souredoutlook** [comment]
I ran into this on https://sentry.zendesk.com/agent/tickets/129541

**Comment by brianthi** [comment]
I was not able to reproduce this issue on my personal org. If this issue is still present, please reopen.
