### ISSUE TITLE
Getting Started with Session Replay --> Link to project settings

### ISSUE THREAD

**Issue by JeremiaAu** [getsentry/sentry#67207]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

25.0.4

### Docker Compose Version

2.24.7

### Steps to Reproduce

1. Create ASP.NET project
2. Create an issue (through SDK)
3. Navigate to an issue in said project
4. Under "Session Replay" klick on "Set Up Now"
5. Klick on link to project settings: "Make sure that Session Replay is enabled in your [project settings]"

### Expected Result

It takes me to the relevant project settings
https://sentry.example.com/settings/**[org-slug]**/projects/[project-slug]/loader-script/

### Actual Result

"Page Not Found"
The organization slug is missing from the URL:
https://sentry.example.com/settings/projects/[project-slug]/loader-script/

**Comment by bruno-garcia** [comment]
@michellewzhang any ideas why we might be missing the org on the URL? Maybe related to subdomains?

**Comment by michellewzhang** [comment]
> @michellewzhang any ideas why we might be missing the org on the URL? Maybe related to subdomains?

Yup, I know what the bug is -- putting out a fix now
