### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by Booboo213** [getsentry/sentry#67216]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. foo 2. bar 3. baz

### Expected Result

Solve problem 

### Actual Result

Solve problem

### Product Area

Other

**Comment by masinette** [comment]
Hello @Booboo213. Please feel free to open up a [support ticket](https://help.sentry.io/) with any questions you may have.
