### ISSUE TITLE
Crons: HTTP setup does not work for timezone

### ISSUE THREAD

**Issue by stumbaumr** [getsentry/sentry#67299]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. We run Cron Jobs in Nomad and use a container in a prestart and poststop task to notify Sentry Cron Monitor about start, stop and fail.
2. We recently changed the timezone for most jobs from UTC to Europe/Berlin - works for Nomad, but Sentry Cron Monitors are not updated with the new timezone from UTC to Europe/Berlin using the HTTP setup up.

### Expected Result

The HTTP call in the prestart task should update the existing cron monitor using the HTTP call with the correct timezone.
HTTP request:
```
curl --silent --show-error -X POST "${SENTRY_CRONS}" \
  --header 'Content-Type: application/json' \
  --data-raw '{"monitor_config":{"schedule":{"type":"crontab","value":"'"${CRON}"'","timezone":"'"${TIMEZONE}"'"}},"failure_issue_threshold":1,"recovery_threshold":1,"environment":"'"${APP_ENV}"'","check_in_id":"'"${CHECK_IN_ID}"'","status":"in_progress"}'
```

With ${TIMEZONE} = "Europe/Berlin".

For the container see: 
(https://github.com/godmodelabs/sentry-cron-nomad)
Script used in the container is:
(https://github.com/godmodelabs/sentry-cron-nomad/blob/main/sentry-cron-prestart.sh)

### Actual Result

The Cron Monitors in Sentry all stay UTC.

### Product Area

Crons

### Version

24.2.0

**Comment by evanpurkhiser** [comment]
Hi @stumbaumr 

`timezone` is not a sub-key of `schedule`, it should be in the `monitor_config` object. So should `failure_issue_threshold`, and `recovery_threshold` (Though looking closer at this, I believe we may have a bug and will not accept these values)

I believe your request should look like this

```
curl --silent --show-error -X POST "${SENTRY_CRONS}" \
  --header 'Content-Type: application/json' \
  --data-raw '{"monitor_config":{"schedule":{"type":"crontab","value":"'"${CRON}"'"},"timezone":"'"${TIMEZONE}"'","failure_issue_threshold":1,"recovery_threshold":1},"environment":"'"${APP_ENV}"'","check_in_id":"'"${CHECK_IN_ID}"'","status":"in_progress"}'
```

Let me know if that helps!

**Comment by stumbaumr** [comment]
Thanks @evanpurkhiser !
I adjusted the curl command and now it just works!
