### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by mukkumayc** [getsentry/sentry#67412]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Go to User Feedback page. But actually it happens only with my user.

### Expected Result

It loads

### Actual Result

![image](https://github.com/getsentry/sentry/assets/32779796/db17100a-13b8-4ffe-95cd-13282f73c103)

### Product Area

User Feedback

### Version

24.3.0

**Comment by ryan953** [comment]
The url in the screen shot is funny, it's got a subdomain and also `/organizations/:orgSlug`, but they don't match.

But more generally it looks like we're not checking for invalid responses from the issues & events endpoints.

**Comment by MattPurland** [comment]
I'm having the same issue, but the error on the frontend is slightly different:

`TypeError: Cannot read properties of undefined (reading 'feedback')`

The 400 (Bad Request) response is:

`{"detail":"Invalid statsPeriod: ''"}`

I'm not sure how else I can help, but please let me know if I can provide any more info

**Comment by billyvg** [comment]
@MattPurland Are you on self hosted or saas? Can you paste the URL path + params? (omitting any project/org id/slugs)

**Comment by MattPurland** [comment]
> @MattPurland Are you on self hosted or saas? Can you paste the URL path + params? (omitting any project/org id/slugs)

I'm on self-hosted, here's the URL:

http://sentry.domain.com/api/0/organizations/star/issues-count/?end=&query=issue.category%3Afeedback%20is%3Aunassigned%20is%3Aunresolved%20&query=issue.category%3Afeedback%20is%3Aunassigned%20is%3Aresolved%20&query=issue.category%3Afeedback%20is%3Aunassigned%20is%3Aignored%20&queryReferrer=feedback_list_page&start=&statsPeriod=&utc=

```
end: 
query: issue.category%3Afeedback%20is%3Aunassigned%20is%3Aunresolved%20
query: issue.category%3Afeedback%20is%3Aunassigned%20is%3Aresolved%20
query: issue.category%3Afeedback%20is%3Aunassigned%20is%3Aignored%20
queryReferrer: feedback_list_page
start: 
statsPeriod: 
utc: 
```

**Comment by MattPurland** [comment]
Not sure if it helps to compare the payload to that of saas, but:

```
end: 
query: issue.category:feedback is:unassigned is:unresolved 
query: issue.category:feedback is:unassigned is:resolved 
query: issue.category:feedback is:unassigned is:ignored 
queryReferrer: feedback_list_page
start: 
statsPeriod: 
utc: 
```

**Comment by MattPurland** [comment]
Comparing this to saas I'm not sure what to make of it, but it also has the same problem initially - but manages to continue to make multiple requests to the same API endpoint and works as intended:

The first one fails, just like the self-hosted:
```
end: 
query: issue.category%3Afeedback%20is%3Aunassigned%20is%3Aunresolved%20
query: issue.category%3Afeedback%20is%3Aunassigned%20is%3Aresolved%20
query: issue.category%3Afeedback%20is%3Aunassigned%20is%3Aignored%20
queryReferrer: feedback_list_page
start: 
statsPeriod: 
utc: 
```

But continues with the following, which seems to work fine:
```
end: 
project: 4505958713786368
query: issue.category%3Afeedback%20is%3Aunassigned%20is%3Aunresolved%20
query: issue.category%3Afeedback%20is%3Aunassigned%20is%3Aresolved%20
query: issue.category%3Afeedback%20is%3Aunassigned%20is%3Aignored%20
queryReferrer: feedback_list_page
start: 
statsPeriod: 14d
utc: 
```
Followed by variations of the above, which all return successfully

This is way beyond me, but hopefully can help

**Comment by bruno-garcia** [comment]
> The url in the screen shot is funny, it's got a subdomain and also `/organizations/:orgSlug`, but they don't match.
> 
> But more generally it looks like we're not checking for invalid responses from the issues & events endpoints.

Is it the lack of `statsPeriod` the problem @ryan953 ?

**Comment by billyvg** [comment]
Seems like #73748 and #73802 should address this?
