### ISSUE TITLE
3rd party integration name needs to change

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#67429]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Feedback from a partner

> I see that our integration still shows as "clubhouse" (instead of "Shortcut") on the Sentry activity page. Is this something we control, or would Sentry have to make that change?

![image](https://github.com/getsentry/sentry/assets/109983869/e1d6724a-6daf-48b6-8cfd-d8963c73d009)

### Expected Result

.

### Actual Result

.

### Product Area

Settings - Integrations

**Comment by iamrajjoshi** [comment]
Could we get the `org_id`, `project_id`, `issue_id` for what issue this comment was posted for so we can debug?

**Comment by iamrajjoshi** [comment]
There is an auth user with clubhouse as username that's causing it to show up in the activity tab.

https://sentry.io/_admin/users/410021/
https://sentry.io/_admin/sentry-apps/shortcut/

**Comment by iamrajjoshi** [comment]
After investigating, it seems that the integration uses a user with the name "clubhouse" to make comments in the Activity page. The partnet needs to update their integration to create/use a new user with the correct name. Because the orgs that already have the integration installed will not use the correct user, we will need to file an ops ticket to update the user.

**Comment by tobias** [comment]
@iamrajjoshi Thanks for looking in to this (I'm the original reporter via other channels). 

In our config for the integration, I don't see a place to define a user, nor do I see a user in our account named "clubhouse". Do you have any docs or guidance about where this user account lives?

**Comment by leedongwei** [comment]
Fixed + added logo. Configuration for integration name is on Sentry's side.

![Screenshot 2024-05-15 at 5 13 32 PM](https://github.com/getsentry/sentry/assets/1748388/154084c1-7cda-4272-b943-5470f3203fdc)
