### ISSUE TITLE
Unable to invite new user as Billing when a team is selected

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#67427]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Organisation Settings -> Members
2. Try to invite a new user with Billing role and add this new user to a team (sometimes auto populated)

### Expected Result

The UI clearly displays why the invite cannot be sent:
```
The user with a 'billing' role cannot have team-level permissions.
```

### Actual Result

The invite fails with an error with no details on the same.

### Product Area

Settings - Members

**Comment by leedongwei** [comment]
I can replicate. We'll address this bug in an upcoming rotational.
