### ISSUE TITLE
CODEOWNERSHIP based issue routing doesnt follow github's logic

### ISSUE THREAD

**Issue by prasad-apollo** [getsentry/sentry#67459]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Create a react based FE project with 2 files foo.js and bar.js and upload the project to github
Add Sentry
In codeowners have 2 rules, 1 permissive rule like *.js pointing to team A and another specific rule making foo.js owned by team B
Add CODEOWNERSHIP based routing added to the project in Sentry
Ensure rule 1 is first and rule 2 is 2nd in the file
Have an error thrown by foo.js

### Expected Result

In github, if you navigate to foo.js it will show team B as the owner for the file since the last rule to match it was the for team B

### Actual Result

Sentry routes the error to Team A instead of team B since it takes ownership based on the first matching rule for Team A

### Product Area

Issues - Source Maps

**Comment by jangjodi** [comment]
Hi @prasad-apollo,
Thank you for bringing this to our attention. This is not intended behavior, as we should also be assigning ownership based on the last matching rule. 
Unfortunately I was unable to replicate this issue. Could you please share the link to the particular issue by opening a support ticket here: https://help.sentry.io/ so we can investigate this further?

**Comment by prasad-apollo** [comment]
I am unable to open the portal to contact support. Is this the correct link: https://sentry.zendesk.com/hc/en-us/requests/new

Also I tried to create a support ticket through the in-page support desk modal but it keeps hanging and erroring out.
I dont want to post pictures and links of the details here since its sensetive information.

**Comment by prasad-apollo** [comment]
I was able to access your portal and submit a ticket. I received a confirmation email that my request was submitted but I didnt mention a ticket id of any sort for me. The ticket was logged with my email address prasad(d o t )prabhu( a t )apollo.io

**Comment by prasad-apollo** [comment]
This issue is resolved. The problem was that there was a missing team mapping in Sentry configuration for the project.
