### ISSUE TITLE
Adjust thresholds causing webhooks to be auto-disabled

### ISSUE THREAD

**Issue by gid-sentry** [getsentry/sentry#67467]
### Problem Statement

A customer has a webhook they use to forward error events to longer-term data storage and it turns off semi-regularly because they breach the number of timeouts.

We’ve tried a couple ways to reduce the amount of timeouts on their webhook, (e.g. most recently they’ve implemented it such that as soon as they get the request from Sentry they return a 200 response before they perform any actions with the data)

Unfortunately they still run into periods where they get more than 1000 timeouts in a 24 hour period. Is there any way we could modify the thresholds on when the webhook would shut off automatically for their case? Either modifying timeout thresholds (which I guess would be less optimal), or allowing for more timeouts to occur before shutting off the webhook?

### Product Area

APIs

**Comment by ceorourke** [comment]
What have they tried to respond to the webhooks on time? Why can't they respond within 1 second? This threshold is in place to prevent incidents, otherwise a single integration can back up the queue and prevent webhooks working for others.

**Comment by gid-sentry** [comment]
They've modified their webhook to instantly respond back with a 200 response before performing any actions on the event, so it is strange that timeouts still happen ---- With that said though I'm not sure what other actions they could take to reduce the number of timeouts since the response time should be near immediate/bottlenecked by the network as things are setup..

**Comment by ceorourke** [comment]
Was using one of our [data forwarding integrations](https://docs.sentry.io/product/integrations/#data--visualization) considered before essentially writing their own? Is there a reason they can't use one of them?

**Comment by sentaur-athena** [comment]
Closing this issue since it seems more like a question that is answered. Feel free to re-open if this is still an ongoing concern.
