### ISSUE TITLE
Is it possible to turn a Single Org installation to non single org?

### ISSUE THREAD

**Issue by chauffer** [getsentry/sentry#6750]
Due to https://github.com/getsentry/sentry/issues/4633, we cannot mix SSO & non-SSO users in Sentry.

From https://github.com/getsentry/sentry/issues/3856 it seems like we can achieve this if we disable the single organization setting of Sentry.

Is this something we can easily switch? Does it take more than just changing the settings?

Thanks!

**Comment by dcramer** [comment]
We're going to look at addressing this via #4633

**Comment by chauffer** [comment]
@dcramer I'm afraid this doesn't answer the question, is it possible to switch back and forth easily to bypass this while this is being developed? 

As that issue was opened over 1y ago, we're fine with working around it in the meantime.

Happy holidays!

**Comment by dcramer** [comment]
Sorry, yes you can turn off single org mode at any time, and turn it back on. It will just make any orgs besides the default unavailable (without some explicit url mangling).
