### ISSUE TITLE
$ SENTRY_UI_DEV_ONLY=1 SENTRY_WEBPACK_PROXY_PORT=7999 yarn webpack serve 'SENTRY_UI_DEV_ONLY'  Not an internal or external command, nor a runnable program

### ISSUE THREAD

**Issue by shiduan** [getsentry/sentry#67508]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I run this project in my windows, why tip that 'SENTRY_UI_DEV_ONLY'  Not an internal or external command, nor a runnable program
![image](https://github.com/getsentry/sentry/assets/14343580/00b30945-780e-4459-a63b-f1a54149bd5c)

$ SENTRY_UI_DEV_ONLY=1 SENTRY_WEBPACK_PROXY_PORT=7999 yarn webpack serve
'SENTRY_UI_DEV_ONLY'  Not an internal or external command, nor a runnable program

### Expected Result

$ SENTRY_UI_DEV_ONLY=1 SENTRY_WEBPACK_PROXY_PORT=7999 yarn webpack serve
'SENTRY_UI_DEV_ONLY'  Not an internal or external command, nor a runnable program

### Actual Result

project run success

### Product Area

Unknown

**Comment by azaslavsky** [comment]
Seems like you are running across this problem: https://stackoverflow.com/questions/13979209/environment-variable-errors-not-recognized-as-an-internal-or-external-command

**Comment by azaslavsky** [comment]
Since this does not seem to be a Sentry issue, but rather a problem with your shell setup, I will close this issue.

**Comment by shiduan** [comment]
"dev-ui": "cross-env SENTRY_UI_DEV_ONLY=1 SENTRY_WEBPACK_PROXY_PORT=7999 yarn webpack serve"
In my windows；I use cross-env can run success
