### ISSUE TITLE
[UI] Tag Details display broken

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#67583]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Find an error event and click on "View Full Event Details". [Example here](https://dragonfruit-dev.sentry.io/discover/javascript-react:2b8d5383908e4a53894f2d6f5d7b21b1/).

### Expected Result

The side bar where tags and their values are displayed is shown normally.

### Actual Result

The tags' values are misaligned and hidden out of view. This can lead to some tag values not being visible at all. It is not possible to do a horizontal scroll to view the full tag value.
![image](https://github.com/getsentry/sentry/assets/81985895/2d8782a8-2cf3-4032-9ad4-983c5687836f)

### Product Area

Other

**Comment by gggritso** [comment]
Caused by https://github.com/getsentry/sentry/pull/67497, unfortunately
