### ISSUE TITLE
Search Result not linking to correct Entry on Multi-Entry Issues

### ISSUE THREAD

**Issue by futureweb** [getsentry/sentry#67581]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Hello,
I have about 10,000 entries in my Sentry for a specific issue, all from different clients with differing IP addresses.
Now, I need to find the entry for a specific IP. The search function does find the issue under this IP, but the link directs to the latest entry for this issue and not the right entry with the searched IP. 
How can I directly navigate to the entry with the correct IP? Manually searching through 10,000 entries is not a feasible solution. 
Search: https://sentry/organizations/myorg/issues/?query=+user%3A%22ip%3A83.219.000.000%22&referrer=issue-list&statsPeriod=14d&stream_index=0 <-- showing correct issue
Link to issue: https://sentry/organizations/myorg/issues/7740/?_allp=1&query=+user%3A%22ip%3A83.219.000.000%22&referrer=issue-stream&statsPeriod=14d&stream_index=0 <-- loading latest entry within this issue and not the needed one

### How are you getting stuck?

Link not going to the right Entry within the issue

### Where in the product are you?

Issues

### Version

23.7.2

**Comment by scttcper** [comment]
Hello! Yes we've heard this a few times before, what might fit your use case is searching events on discover or within the issue's events tab.
