### ISSUE TITLE
Sentry should consider environment when suggesting the 'next release'

### ISSUE THREAD

**Issue by sandstrom** [getsentry/sentry#67582]
### Problem Statement

![CleanShot 2024-03-25 at 11 06 32](https://github.com/getsentry/sentry/assets/122287/75287667-bc98-4618-9101-a925411fae1c)

### Product Area

Releases

**Comment by scttcper** [comment]
I've added this to our backlog as a feature request. I know right now those are per project and do not take into account any of the query information

**Comment by mikejihbe** [comment]
I disagree with the premise of this request. Releases in our system are treated as essentially builds -- deployable artifact identifiers. We don't currently model releases as belonging to a single environment and I am not sure it would be generally correct to do so. I doubt we will pick this up anytime in the near future. Closing for now.

**Comment by sandstrom** [comment]
@mikejihbe Thanks for looking at this Mike! 😄 

I agree with your disagreement :) But I also think you may already have the needed building blocks in the form of deploys. See my reasoning below.

## Assumption that a release doesn't belong to an environment

> We don't currently model releases as belonging to a single environment and I am not sure it would be generally correct to do so.

I totally agree with this, a release doesn't belong to an environment. Rather, a release may be deployed into one or multiple environments (often in steps over time, for rollouts etc).

## Deploy primitive

Another primitive you have are deploys. I see them as basically the tuple of {release, environment, deploy-time}, i.e. the act of putting a certain release into a certain environment.

## Suggestion

Maybe there is a way for you to utilize the existing deploy models (when a customer is sending them to you) to figure out what the 'current release' is per environment? 

Perhaps there isn't a lot of extra work. Just see if deploys exist, and if so use them to figure out the current release, and if none exist, then fall back to current behavior which is just looking at the most recent release (regardless of which environment it's been seen in).


[1] https://docs.sentry.io/product/releases/usage/sorting-filtering/
