### ISSUE TITLE
Feature parity with Gitlab for CodeCov

### ISSUE THREAD

**Issue by bfpepper87sentry** [getsentry/sentry#67608]
### Problem Statement

From CodeCov Docs the Sentry <> CodeCov <> GitHub integration is the only one currently that is full feature. It looks like 25% of Sentry customers using integrations use Gitlab. Is it possible to have feature parity of this integration for Gitlab? 

### Product Area

Unknown

**Comment by cathteng** [comment]
@bfpepper87sentry We'll track this within the Ecosystem team

**Comment by sentaur-athena** [comment]
This is the same as https://github.com/getsentry/sentry/issues/65326
So closing and tracking there.
