### ISSUE TITLE
User-creation should not fail, when the account already exists

### ISSUE THREAD

**Issue by UnitedMarsupials** [getsentry/sentry#6763]
I'm creating an Ansible role for installing sentry on our network. The software is installed via `pip` -- version 8.22.0, which seems to be the latest as of today. Not using Docker -- just a dedicated VM.

One of the tasks is to create a Sentry-admin:
```
sentry createuser --superuser --no-input --password=FOO --email=sentry@example.com
```
Unfortunately, the above command only works _the first time_. Trying to run it again fails:
```
django.db.utils.IntegrityError: IntegrityError('duplicate key value violates unique constraint \"auth_user_username_key\"
DETAIL:  Key (username)=(sentry@example.com) already exists
```
I understand, why the same account can not be created again. But it should not be an _error_ -- simply update the existing record if necessary. Or, if it must be an error, there should be a specific exit-code for this case, which would allow systems like Ansible to move on. Currently, `sentry` exits with the same code 1 for all errors...

At the very least, there needs to be a way to check, whether the account exists already... Ansible would then be able to perform the query before attempting to add the user.

**Comment by jpic** [comment]
That's the same issue with standard createsuperuser command, a solution I use for now is failed_when: false. But a better solution would be to register the task and then use the stdout attribute of the register variable to improve the failed_when check.

```
  - name: Create super users
    failed_when: false
    with_items: '{{ active_users }}'
    tags: users
    expect:
      timeout: 30
      command: docker exec -it {{ django_instance }} su uwsgi -c bash -c "django-admin createsuperuser"
      responses:
        'Username': ["{{ item['name'] }}"]
        'Email': ["{{ item['email'] }}"]
        'Password': ["{{ admin_passwords[item['name']] }}", "{{ admin_passwords[item['name']] }}"]
```

I think we should just contribute to make a better createsuperuser command in Django.

**Comment by mattrobenolt** [comment]
We already implement our own command entirely: https://github.com/getsentry/sentry/blob/master/src/sentry/runner/commands/createuser.py

**Comment by jpic** [comment]
I recon it really shouldn't fail, because it will log the error:

![2018-01-15-045002_1139x852_scrot](https://user-images.githubusercontent.com/94636/34926433-bfbb671c-f9af-11e7-808c-fbc9108811e5.png)

Note that I'm using createuser now, thanks for the heads up !

```
  - name: Create super users
    failed_when: false
    with_items: '{{ active_users }}'
    tags: users
    command:
      docker run
      -t
      --rm
      --network sentry
      --env SENTRY_DB_PASSWORD={{ sentry_postgresql_password }}
      --env SENTRY_DB_USER=sentry
      --env SENTRY_POSTGRES_HOST=sentry-postgres
      --env SENTRY_REDIS_HOST=sentry-redis
      --env SENTRY_SECRET_KEY={{ sentry_secret_key }}
      sentry sentry createuser --no-input
      --superuser
      --email {{ item['email'] }}
      --password {{ admin_passwords[item['name']] }}
```
