### ISSUE TITLE
[Invitation Email] "Home" CTA Unclear

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry#67684]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Send an invitation email, they look like this: 
<img width="766" alt="image" src="https://github.com/getsentry/sentry/assets/76002357/358936d5-479a-4829-8ece-f017e7ecfda1">

### Expected Result

Links to sentry.io/welcome use the full path which will always take any user to the /welcome site

### Actual Result

They use sentry.io -> this can result in redirection to /auth/login under certain circumstances

Furthermore, it's unclear what the "HOME" CTA in the footer is meant to suggest. It feels like it was put there by accident as it's simply another link to sentry.io 

### Product Area

Settings - Members

**Comment by cathteng** [comment]
We can change the Sentry website link to sentry.io/welcome.

If it makes sense to remove the Home, we can do that too.

**Comment by leedongwei** [comment]
Might be a good small task for @JLuse
