### ISSUE TITLE
Why is the marking of the symbol table in the red box unusual?

### ISSUE THREAD

**Issue by WeiLingQiang** [getsentry/sentry#67724]
Why is the marking of the symbol table in the red box unusual?

![企业微信截图_17108397122565](https://github.com/getsentry/sentry-unity/assets/103353466/fc5a3161-1abc-4322-be6b-a3bf4507b27e)

_Originally posted by @WeiLingQiang in https://github.com/getsentry/sentry-unity/issues/1526#issuecomment-2006455914_

**Comment by WeiLingQiang** [comment]
> Hey @WeiLingQiang, what is it that is not working? Could you provide me a link to the issue on Sentry?

https://sausage-client-sentry.sausage.xd.com/share/issue/3e6e8303b32b4cff9a5e7e8c7335df35/

Can you access this link?

**Comment by Swatinem** [comment]
Yes, I can access this link, but it does not show the full details of the loaded library.

I also don’t fully understand what the concern is? Would you like to see a green checkmark there instead of an empty circle?

**Comment by WeiLingQiang** [comment]
Yes, I compared the normal situation. There is this green check mark, but it is okay to use the command line to analyze the stack.

`xcrun atos -o UnityFramework.framework.dSYM/Contents/Resources/DWARF/UnityFramework -arch arm64 -l 0x00000001d2dbd198 0x00000001d2db6000`

**Comment by WeiLingQiang** [comment]
Excuse me, have you found a solution?

**Comment by bitsandfoxes** [comment]
I think the interface has been updated.
