### ISSUE TITLE
Clarification about scrubbing rules pulled from Relay in managed mode

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry#67755]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Original question, on behalf of a customer:

> “I’m looking through the docs to see how the Relay can be setup and for the relay scrubbing, the doc seem to suggest that the scrubbing is defined per project. (Docs say: ‘After iterating on the config, paste it back into the project config located at .relay/projects/<PROJECT_ID>.json’)
> Is it possible to create some global rules that apply everywhere or does it have to be duplicated in all projects? ”

### How are you getting stuck?

My understanding is that Relay’s [managed mode](https://docs.sentry.io/product/relay/modes/#managed-mode) will obtain settings from Sentry and apply them to events that pass through the Relay instance. But which settings get obtained from Sentry?

- If a user has server-side scrubbing rules set in Sentry.io (for example [Advanced Data Scrubbing](https://docs.sentry.io/product/data-management-settings/scrubbing/advanced-datascrubbing/) or [Server-Side Scrubbing](https://docs.sentry.io/product/data-management-settings/scrubbing/server-side-scrubbing/)), will these scrubbing rules be pulled by a managed-mode Relay and applied to all events that pass through the Relay? 
- Or, does scrubbing have to be defined inside the Relay instance itself on a per-project basis, as in the original question’s docs link example?

(Note: I did attempt to answer this with a local Relay and an [Advanced Scrubbing Rule](https://cstavitsky.sentry.io/settings/security-and-privacy/) — I successfully sent a [test event](https://docs.sentry.io/product/relay/getting-started/#sending-a-test-event) whose message [was hashed](https://cstavitsky.sentry.io/issues/5103134163/?project=4505484140019712&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=90d&stream_index=0) per my rule. However, I wasn’t able to actually tell whether this scrubbing happened in the Relay or on Sentry.io. When I attempted to add logging statements to check the event details within Relay, killed the local Relay, restarted it, then sent events, none of my logs showed up even though the events did eventually make their way to Sentry 🤔 )

### Where in the product are you?

Settings - Relay

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2131) by [Unito](https://www.unito.io)

**Comment by jjbayer** [comment]
> If a user has server-side scrubbing rules set in Sentry.io (for example [Advanced Data Scrubbing](https://docs.sentry.io/product/data-management-settings/scrubbing/advanced-datascrubbing/) or [Server-Side Scrubbing](https://docs.sentry.io/product/data-management-settings/scrubbing/server-side-scrubbing/)), will these scrubbing rules be pulled by a managed-mode Relay and applied to all events that pass through the Relay?

Yes.

> Or, does scrubbing have to be defined inside the Relay instance itself on a per-project basis, as in the original question’s docs link example?

This is only for Relays running in static mode: In static mode, a per-project JSON file replaces the config that managed Relays would obtain from Sentry.

@cstavitsky Is there a specific part of the documentation that you think needs clarification on this, apart from https://docs.sentry.io/product/relay/modes/?

**Comment by cstavitsky** [comment]
> @cstavitsky Is there a specific part of the documentation that you think needs clarification on this, apart from https://docs.sentry.io/product/relay/modes/?

@jjbayer thanks for the reply and confirmation of Relay behavior!

Since scrubbing seems to be one of the most common use cases for customers to use Relay, consider updating the docs to be explicit about the 'statement version' of the question I asked:

> <put under "managed mode" section?>
> Server-side scrubbing rules set in Sentry.io (for example [Advanced Data Scrubbing](https://docs.sentry.io/product/data-management-settings/scrubbing/advanced-datascrubbing/) or [Server-Side Scrubbing](https://docs.sentry.io/product/data-management-settings/scrubbing/server-side-scrubbing/)) will be pulled by a managed-mode Relay and applied to all events that pass through the Relay.

In general, it could be helpful to know which relevant Sentry.io project settings and configs will get pulled by a managed-mode relay, and how they would act upon events passing through the relay.

Hope that helps explain my thinking, let me know if you need any more clarification, and thanks again ✌️
