### ISSUE TITLE
Performance Issue When Scrubbing Replay in Replay Details

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#67760]
Reported by our customer:

> My biggest issue is when I'm trying to pinpoint errors in a given replay, but the replay is like 30 minutes long. I can see where the error is on the timeline and scrub to it, but the reply is so large that Sentry has to buffer the replay contents (I'm assuming) and I just get a white screen for what feels like forever. I usually just give up at this point, which is a bummer.

Private ticket: https://github.com/getsentry/team-replay/issues/411

**Comment by billyvg** [comment]
Closed by https://github.com/getsentry/rrweb/pull/213
