### ISSUE TITLE
Report failure to submit transactions

### ISSUE THREAD

**Issue by Atleago** [getsentry/sentry#67801]
### Problem Statement

Sentry does not allow introspection of the messages that don't reach sentry. There exist several such scenarios, for example: envelope exceeds size limit. Contrary to the documentation, these do not receive a `413 Content Too Large` but instead receive a `400 Bad Request`. The only visibility provided by the python sdk is through the debug logging. Parsing errors out of logs is expensive and not fit for purpose when automated, clearer signals exist for this purpose.

### Solution Brainstorm

Proposal to self-instrument the sdk using the beta metrics to submit a gauge/rate of failures. It is understood that these may also be rejected by the server however, as metrics are normally not dependent on a stacktrace, it's locals and attachments, the size of this is predictable and much more normalized.

### Product Area

Ingestion and Filtering

**Comment by scttcper** [comment]
@Atleago this might be an sdk specific problem. What SDK are you referring to?

**Comment by Atleago** [comment]
@scttcper I was directed here from sentry's support. We're using the python-sdk and I believe the self-instrumentation should be considered in there: the python sdk. Feel free to move this to the appropriate place, this is likely something that can/should be done for all sdk's, granted they have the ability to participate in the Metrics beta as an ideal implementation.

Separately, the observed 400 response code instead of the a 413 response code could perhaps be triaged here but is of significantly less importance than the visibility granted by self-instrumentation first paragraph of this comment.

---

Perhaps good to add is some of the attempts to address this with sentry's support (115042):

After being unable to find a production issue in Sentry we hunt down a recent change that included new local variables in scope of the issue. Deep within the logs only visible when running in debug, we observe: `[sentry] ERROR: Unexpected status code: 400 (body: b'{"detail":"envelope exceeded size limits for type \'event\' (https://develop.sentry.dev/sdk/envelopes/#size-limits)"}')`. We engage further with support as there was no indication in the control UI on sentry that this was happening. According to support, this is impossible as the request doesn't reach sentry (`but these events never actually reach Sentry, since it's rejected before it could be counted as dropped`).

We want to hook into these failures, be able to categorize them and provide visibility to it, somewhere, anywhere; logs are not a quality signal for this.

We then get some further replies from support:
1.	If you enable the debug logs and an error gets dropped on the client side (due to beforeSend or sample rate or other event processors), a relevant debug log will be outputted in your terminal
2.	If you go to your Project's settings > Client Keys (DSN) > find the DSN you are using > Configure, you will see a graph at the top of the page detailing whether errors were accepted or dropped
3.	If you got to your Project's settings > Inbound Filters, you will see a graph at the top of the page detailing whether errors are being dropped and by which [inbound filter](https://docs.sentry.io/product/data-management-settings/filtering/).

Which are not relevant to us:
1. it's not dropped client side, see the 400 response code.
2. Graph is flat.
3. No inbound filters are in place.

We then submit a motivation for this visibility to be available through self-instrumentation (possibly using the new Metrics beta) of the sdk and get directed to create this request for public triage.

**Comment by iker-barriocanal** [comment]
Thanks for reporting, @Atleago!

We record data when we drop envelopes on the server, including errors for too large envelopes (see [relay code](https://github.com/getsentry/relay/blob/33aa45c2f99e81559d72291b07eb8804ad02bde6/relay-server/src/endpoints/common.rs#L371-L372)). In the org stats, these should be grouped in "dropped" (see [docs](https://docs.sentry.io/product/stats/#usage-stats)). There's a [feature request](https://github.com/getsentry/sentry/issues/59320) open to expand the stats and make them more granular, would that solve your concerns?

**Comment by Atleago** [comment]
Being able to alert on the increased granularity would resolve my concern after experiencing issues in production. However, the increased visibility would already be much appreciated.

Also, it seems we can improve the documentation somewhere, as there are some places where these dropped events are shown (the org stats), and in others they are not shown (stats on key usage).

---

I image each organization (and even project) has different patterns to their dropped events, for some it may be very normal to have these. For us, it is not. Just like with spike protection deciding to enable and protect our wallet and your systems, we get an e-mail. When you protect your system from an issue in ours, we similarly want to know, quickly, via a notification of sorts.

**Comment by iker-barriocanal** [comment]
> alert on the increased granularity

I'm not sure how useful that'd be as it can result in plenty of noise. We're working on a [metrics product](https://docs.sentry.io/product/metrics) that supports alerts, does this unblock you?

**Comment by Atleago** [comment]
Having the sdk, and/or the server itself, self-instrument through the metrics product, would be great. That is exactly the initial ask in this request.

**Comment by iker-barriocanal** [comment]
@getsentry/team-web-sdk-backend could we triage this feature request?
