### ISSUE TITLE
Add Distribution Chart visualization to Dashboards

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry#67817]
### Problem Statement

It would be helpful to see Web Vital distribution charts in a dashboard rather than the performance page.

<img width="1769" alt="image" src="https://github.com/getsentry/sentry/assets/86369415/1cfab461-b838-4ede-b549-0bf78677509f">

### Product Area

Dashboards

**Comment by k-fish** [comment]
Hey there @dachakra, we're currently evaluating potentially changing these vital pages, and may change dashboard visualizations in the future but I don't have a timeline for you. I'll let our product team know so they can factor that into their roadmap. Thanks for the feedback!
