### ISSUE TITLE
Support release for fingerprint rules

### ISSUE THREAD

**Issue by jboulter11** [getsentry/sentry#67836]
## Context
Sentry's App Hangs collected for iOS Widgets extensions do not accurately reflect whether the extension code is hanging.

## Problem
I have disabled app hang collection in widgets in new clients, but old clients will continue to log them, and, under some circumstances, new clients may log some too.

App Hangs from widgets may be in their own group or share a group with real app hangs reflected in the main application or other app extensions, they just seem to happen a lot more in the cases they share a group with the main app or extensions.

I want to entirely stop collecting these app hangs for old clients, so it does not disrupt my team's ability to triage and resolve real app hangs.  If I cannot do this, my team is likely to have app hangs re-open as regressed even though they are not, and there's also likely to be a lot of noise both on alerts and also when browsing app hangs.  It will be very difficult to understand what's real and what isn't, as well as whether the issue is actually impacting users and at what level.

## My Solution
I went to Fingerprint Rules with the intent to group together all the app hangs coming from widgets releases so that they could be discarded and deleted.

Here's the fingerprint rule I tried:
```
tags.mechanism:"AppHang" tags.release:"com.getdropbox.Dropbox.Widgets*" -> widget_app_hangs title="Widget App Hang"
```

But it does not seem that `tags.release` exists?  The rule seems to do nothing.

### Solution Brainstorm

My intended solution would work, I think, if I could access release in some way inside a fingerprint rule.

I'm super open to other solutions for my problem.

Something else I tried that doesn't work entirely:
I can use inbound filters to drop all things from widgets, but the issue is that I still want things from widgets, I just don't want app hangs from widgets.  So that does not help solve the whole issue, only most of it.  I can drop those older versions entirely, at the expense of losing all their error reports, but some newer versions will have a (bad) cached value for the feature gate used to control whether we collect app hangs on widgets, that may live for a very long time.

### Product Area

Ingestion and Filtering

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2132) by [Unito](https://www.unito.io)

**Comment by realkosty** [comment]
Tested this independently and confirming described behavior with `tags.release`.
Matching semver without package name doesn't work either.
`release` is not allowed by validation 
<img width="153" alt="Screenshot 2024-03-27 at 5 12 24 PM" src="https://github.com/getsentry/sentry/assets/490201/93b25e07-c3d6-4abd-9b3f-700ef41b7e9e">

**Comment by armenzg** [comment]
Hi @jboulter11 
I tend to use Discover to help me create fingerprint rules.

You should be using this:
`error.mechanism:AppHang  release:com.getdropbox.Dropbox.Widgets*`

The mechanism is part of the `error` field rather than a tag. Also the `release` is a field rather than a tag.

Please let me know if this works for you.

**Comment by jboulter11** [comment]
Unfortunately that does not work:
![Screenshot by Dropbox Capture](https://github.com/getsentry/sentry/assets/6633472/2a5456e6-5ddb-4234-88be-d06a829f7ab7)

I also used discover to help write this. :'(

**Comment by armenzg** [comment]
huh! Let me fix that.

**Comment by jboulter11** [comment]
Thank you!  Let me know when I can expect this to ship? 🙏

**Comment by armenzg** [comment]
Hi Jim, my apologies as I went to the Easter weekend here in Canada.
This fix was deployed. Let me know if it doesn't work.

**Comment by armenzg** [comment]
The system now allows us to use the `release` field, however, thanks to @realkosty it seems that it's not quite working. I will ask the team and see what I may have missed.

He used this rule [here](https://demo.sentry.io/settings/projects/react/issue-grouping/).
`error.value:"500 - Internal Server Error" release:"application.monitoring.javascript@*" -> react-flagship-500 title="Error 500"`

The issues are still separate [here](https://demo.sentry.io/discover/homepage/?field=issue&field=title&field=count%28%29&field=release&name=All+Events&project=5808623&query=error.value%3A%22500+-+Internal+Server+Error%22+release%3A%22application.monitoring.javascript%40%2A%22&sort=-count&statsPeriod=2h&yAxis=count%28%29):
<img width="656" alt="image" src="https://github.com/getsentry/sentry/assets/44410/42d0f55a-5853-4e9f-8434-c7add42faecd">

**Comment by jboulter11** [comment]
Confirmed it does not appear to be working in our project either.
```
tags.mechanism:"AppHang" release:"com.getdropbox.Dropbox.Widgets*" -> widget_app_hangs title="Widget App Hang"
```
