### ISSUE TITLE
Replay videos API endpoint needs to support `Range` header (for Safari)

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#67900]
Safari browsers will only play videos if the server serving the video supports the [`Range` http header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) to fetch a certain range of bytes for the video. (The idea is to only stream video data as requested so as to conserve mobile data usage if the user does not watch the entire video).

Safari will send an initial request to check that the server supports the header:

`Range: bytes=0-1`

If it succeeds, it will continue to request the rest of the video as needed.

I would follow [the spec outlined by MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range)

The endpoint in question is `/api/0/projects/<orgSlug>/<projectSlug>/replays/<replayId>/videos/<segmentId>/`

Ref https://github.com/getsentry/sentry/issues/64379

**Comment by bruno-garcia** [comment]
did #68121 resolve this?

**Comment by billyvg** [comment]
Yes
