### ISSUE TITLE
Allow users to exclude archived issues from alert rules that notify for issues with more than x errors

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#67920]
### Problem Statement

Feedback from a customer:

> I want to be alerted for issues that have more than x errors in a given period but I don't want to be alerted for archived issues

### Product Area

Alerts

**Comment by travisbloom-cb** [comment]
This would be a huge win!

**Comment by ceorourke** [comment]
Customers can use the `is:unresolved` filter on metric alerts to achieve this.
