### ISSUE TITLE
[Feature Request] PrometheusMetricsBackend

### ISSUE THREAD

**Issue by freeseacher** [getsentry/sentry#6795]
Please add PrometheusMetricsBackend to export internal metrics to Prometheus. Along with StatsdMetricsBackend.

Currently Prometheus is pretty good monitoring solution.

**Comment by mattrobenolt** [comment]
I'd happily review a PR for this, but right now, we don't have any capacity to add this ourselves since we don't use Prometheus and have very little context personally.

**Comment by saady** [comment]
Since it is not yet supported, I come up with something like this.
https://github.com/saady/sentry-prometheus

**Comment by snakecharmer** [comment]
I've only exposed the project metrics (error received) with this prometheus exporter https://github.com/snakecharmer/sentry_exporter

**Comment by Smashmint** [comment]
Plus one for this.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by pecigonzalo** [comment]
I would find this really useful.

**Comment by BYK** [comment]
@pecigonzalo I think so too but it is clearly out of scope for our teams and there seems to be some open-source tools that may help with this. Since we don't plan to work on this, I closed the issue. PRs welcome but I think this would be a separate project anyway.

**Comment by pecigonzalo** [comment]
@BYK Could elaborate on why its out of scope of this project? I think it would be far better to have those in it given you already have collectors set for `statsd`.
Your first message indicated that this was being closed due to staleness, and to comment if felt this was useful, there are also 69 other 👍 (assuming all ❤️[ are repeats) from people that would also find this useful, you current reply seems to indicate the opposite.

**Comment by mattrobenolt** [comment]
It's out of scope for us because we don't use Prometheus. I mentioned I'd be open to reviewing a PR for a backend.

**Comment by BYK** [comment]
@pecigonzalo I did close it due to staleness as nobody from the team picked this up and it is because we don't use Prometheus as @mattrobenolt mentioned above.

It is still possible to get this, just not from the Sentry team itself.

**Comment by pecigonzalo** [comment]
Got it 👍 I thought was a call out to users not internally.
