### ISSUE TITLE
Jira Server Integration does not save labels

### ISSUE THREAD

**Issue by jboulter11** [getsentry/sentry#68010]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

0. Have a jira server integration
1. Create an alert with an action to create a jira ticket and enter configuration.
2. Set a label to be added in the Labels field.
3. Save
4. Re-open Jira Ticket Config.

### Expected Result

Labels which were supposedly saved are shown in Labels box.

### Actual Result

Labels are seemingly not saved, as no text is shown in the labels box.

Screencast can be found in our shared Slack channel.  I don't wanna post this one publicly since it contains some configs I'd rather not have out there.

### Product Area

Alerts

### Link

https://dropbox.sentry.io/alerts/rules/dropbox-android/14935892/

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2133) by [Unito](https://www.unito.io)

**Comment by realkosty** [comment]
Added screen recording to linked internal Jira ticket

**Comment by Dhrumil-Sentry** [comment]
Thanks for this bug report, We will comment on this issue with details once we start investigating this problem

**Comment by jboulter11** [comment]
Something to note, the labels are being saved and used to make Jira Tickets.  They just don't show up at all in the settings.

**Comment by jboulter11** [comment]
The saved labels are also in the response from `https://us.sentry.io/api/0/projects/dropbox/dropbox-ios/rules/15065595/` so I'm guessing they're just not being read into the form or something.

**Comment by GabeVillalobos** [comment]
This has been addressed via https://github.com/getsentry/sentry/pull/79043, which fixes the fill bug. Closing for now but please let us know if this continues to be a problem.
