### ISSUE TITLE
Add options to disable Performance Issues and/or filter them

### ISSUE THREAD

**Issue by mcheng-brilliant** [getsentry/sentry#68045]
### Problem Statement

What is stated in these two closed issues:
- https://github.com/getsentry/sentry/issues/47010
- https://github.com/getsentry/sentry-react-native/issues/3072

For my specific use case, it is around the `Large HTTP Payload` detector. We expect specific dynamic routes to be pulling down large JSON bundles. We know the route patterns that will be doing this and want to ignore this Performance Issue on those routes because it is just noise.

### Solution Brainstorm

Each Performance Detector should have the option to be:
1. Turned on/off
2. Filterable based on a condition

For the `Large HTTP Payload`, the triggering criteria already excludes Next.js specific routes by filtering out `_next`. This is necessary due to Next.js's SSR architecture where soft navigations result in queries for just the JSON payload returned from `getServerSideProps`. Seeing as how such a route filter already exists, I think it should be possible to make this filtering criteria configurable by users.

**Other Considerations**
- Why changing the threshold doesn't work - There's no guarantee that these JSON bundles will fall below the 10MB cap on the threshold at the moment. Increasing that cap would also impact all other routes which means that this detector effectively becomes useless everywhere else.
- Why archiving issues doesn't work - These routes are dynamic and are based on content we create. Every new route published means that another new issue will pop-up in our Dashboard. This results in having to play a game of endless whack-a-mole.

### Product Area

Performance

**Comment by gggritso** [comment]
@mcheng-brilliant thanks for raising this! I want to ask more about this:

> Why archiving issues doesn't work - These routes are dynamic and are based on content we create

Are the content routes parameterized? e.g., if your routes look like `/content/kinematics`, `/content/calculus`, does Sentry capture them as separate pages, or as `/content/:contentType`? If it was the latter, the grouping would work better and you'd be able to ignore the issue just once

**Comment by mcheng-brilliant** [comment]
> @mcheng-brilliant thanks for raising this! I want to ask more about this:
> 
> > Why archiving issues doesn't work - These routes are dynamic and are based on content we create
> 
> Are the content routes parameterized? e.g., if your routes look like `/content/kinematics`, `/content/calculus`, does Sentry capture them as separate pages, or as `/content/:contentType`? If it was the latter, the grouping would work better and you'd be able to ignore the issue just once

Sentry is capturing them as separate routes so we get thousands of separate issues in our Dashboard.

**Comment by gggritso** [comment]
@mcheng-brilliant understood! The ability to configure issue detection per-route is an interesting idea, so I will add this to our project backlog.

For now, my recommendation is to capture the URLs as one route. This will fix grouping of performance issues. Our docs have [more information on filtering the transaction names](https://docs.sentry.io/platforms/javascript/guides/react/data-management/sensitive-data/#scrubbing-data), but it's something like this:

```js
Sentry.init({
  dsn: "<your-dsn>",

  beforeSendTransaction(event) {
    // Replace the event's `transaction` property with a scrubbed URL. e.g., replace `"/content/calculus"` with `"/content/:contentType"`
    return event;
  },
});
```

This will improve how Sentry behaves in other places, too.
