### ISSUE TITLE
Replay tab is empty but transaction summery has a replay attached

### ISSUE THREAD

**Issue by gotenxds** [getsentry/sentry#68057]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Have only 1 replay for a transaction

### Expected Result

Should be both in the replay tab and transaction summery

### Actual Result

<img width="1476" alt="image" src="https://github.com/getsentry/sentry/assets/3519520/1ccaa133-7db4-4eb7-a114-9577e0ea7420">

### Product Area

Issues

### Link

https://panorays.sentry.io/issues/4957066908/?end=2024-03-28T23%3A59%3A59&project=5496420&query=issue%3ASURFACE-UI-5TR&referrer=issue-stream&start=2023-12-31T00%3A00%3A00&stream_index=0&utc=true

**Comment by jas-kas** [comment]
cc/ @JoshFerge @ryan953 @cmanallen

**Comment by jas-kas** [comment]
Hey @gotenxds 👋 

Thanks for reporting this bug. Just to confirm the Replay tab displaying '0' (despite showing a replay on the event-specific view) is happening on your Issue Details page (rather than Transaction Summary)? This is what your screenshot and link indicates. :)

**Comment by gotenxds** [comment]
Hya @jas-kas yes this happens in the issue details page, I have provided a link to the sample issue (this happens in a lot of issues)

**Comment by jas-kas** [comment]
@gotenxds Got it. So, the source of this discrepancy between the Replays tab count and the fact that you see replays inside the individual event details pages, is because we do hard-code the Replays tab to be looking at the last **14d** worth of data.

@ryan953 on our team is looking into a fix/how to improve the UX here!

**Comment by gotenxds** [comment]
Cool, thanks for letting me know
