### ISSUE TITLE
Trace timeline not showing up correctly for issues

### ISSUE THREAD

**Issue by rachrwang** [getsentry/sentry#68071]
Expected for certain issues to show a trace timeline inline in the issue, but they aren't being displayed.

Example issues noted in [this slack thread](https://sentry.slack.com/archives/C04KZQBNQ2U/p1712029015959769).

From Matt: "It looks like we might be missing a project filter on the queries in static/app/views/issueDetails/traceTimeline/useTraceTimelineEvents.tsx - they're both returning You cannot view events from multiple projects. errors."

**Comment by mrduncan** [comment]
Closing this as Slack retention is gone, likely would have been resolved with trace connected issues cleanup.
