### ISSUE TITLE
[User Feedback] Replay Player Does Not Always Show the Right Context Leading up To Feedback Submission

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#68100]
## Problem Statement

The 'replay player' inside User Feedback Details shows ~20s before a feedback is submitted. However, it sometimes takes the end-user 30s-1m to write the feedback report, resulting in the replay player not showing the context of what was the user was doing before opening up the feedback form (instead it shows the user typing in the form).

![Image](https://github.com/getsentry/sentry/assets/77064737/70e6c095-29b9-4a91-8c92-84de959c4c5e)

**Comment by jas-kas** [comment]
cc/ @billyvg @ryan953

**Comment by michellewzhang** [comment]
@jas-kas is this resolved with our newest SDK update?

**Comment by jas-kas** [comment]
@michellewzhang I don't know 🤷  @billyvg to confirm

**Comment by ryan953** [comment]
seems like a replay sdk/buffering thing

**Comment by billyvg** [comment]
The issue here is that the user feedback details player is using the feedback submitted breadcrumb to determine the replay window to display.

**Comment by michellewzhang** [comment]
@billyvg @jas-kas @ryan953 this looks to be resolved? all the replays i'm seeing in the latest UF gives about 19s of content before the feedback submission

**Comment by jas-kas** [comment]
@michellewzhang I see this as well :) I will close this ticket for now and re-open if I notice lack of context leading up to submission inside the replay snippet.
