### ISSUE TITLE
Begin ingesting cache spans

### ISSUE THREAD

**Issue by DominikB2014** [getsentry/sentry#68118]
Ingest general cache spans (i.e spans with op of `cache.*`)

Create metrics for db.redis spans with tags

- [x]  Environment
- [x]  Span op (cache.get_item, cache.save, etc)
- [x]  Transaction name
- [x]  Duration
- [x]  Cache hit or miss

The following tags will need to be added as well, but do not have data collect this data in the SDK yet.

- [ ]  Domain/table ( or some identifier to which cache it is, db vs nodestore cache in your example)

**Comment by gioshi3007** [comment]
const Prometheus = require('prom-client');

// Definir el histograma para la duración de las operaciones de caché
const cacheOperationDuration = new Prometheus.Histogram({
  name: 'cache_operation_duration_seconds',
  help: 'Duration of cache operations',
  labelNames: ['transaction_name', 'action', 'environment', 'cache_result', 'domain_table'],
  buckets: [0.1, 0.5, 1, 2, 5] // Definir los intervalos de duración
});

// Función para registrar una operación de caché
function recordCacheOperation(transactionName, action, environment, cacheResult, domainTable, duration) {
  cacheOperationDuration.labels(transactionName, action, environment, cacheResult, domainTable).observe(duration);
}

// Ejemplo de registro de una operación de caché
recordCacheOperation('example_transaction', 'get', 'production', 'hit', 'user_data', 0.05);
