### ISSUE TITLE
Audit log - Log the deletion of Sentry Issues by User X

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#68162]
### Problem Statement

Currently when issues are deleted by accident or by mistake causes others to be confused about the data gone in dashboards, alert charts or general discover queries.

By pointing out if and who has deleted it, it can prevent a lot of confusion.

### Solution Brainstorm

I believe logs are already available in the GCP logs, we just don't have them in the Sentry logs. 

### Product Area

Settings

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2135) by [Unito](https://www.unito.io)

**Comment by souredoutlook** [comment]
💯 @Angelodaniel this would be a nice QOL feature

**Comment by JoshFerge** [comment]
Thank you for the issue. Adressing in https://github.com/getsentry/sentry/pull/68198

**Comment by JoshFerge** [comment]
Going forward issue deletions should have audit logs. Deployed this afternoon:
<img width="1188" alt="Screenshot 2024-04-03 at 5 04 45 PM" src="https://github.com/getsentry/sentry/assets/1976777/de125e10-80ed-4186-a87e-1a14331d6ca4">
