### ISSUE TITLE
Cron REST API registers two check-ins for in progress and ok statuses

### ISSUE THREAD

**Issue by rokcarl** [getsentry/sentry#68161]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Send a REST API request with `status=in_progress`.
2. In 20s, send another one with `status=ok`.

### Expected Result

There's one check-in in Sentry.

### Actual Result

There's two.

<img width="900" alt="Screenshot 2024-04-03 at 09 45 14" src="https://github.com/getsentry/sentry/assets/42874/56b0a99f-03b5-4f24-b77f-4576bddfaef5">

<img width="900" alt="Screenshot 2024-04-03 at 09 50 43" src="https://github.com/getsentry/sentry/assets/42874/4d29c3b4-7007-4870-bedc-c8c536c57ba9">

Here's my [test Python app](https://gist.github.com/rokcarl/1cebb15a4629a312e9034eda88a53e6d). Also note that [my crontab](https://gist.github.com/rokcarl/160047c2bacafa83d00e2950abba453e) is `*/5 * * * *`, so it might be some interaction there as well.

I would use the Python SDK, but it currently doesn't support upserting the monitor. I've followed [this documentation](https://docs.sentry.io/product/crons/getting-started/http/#check-ins-recommended) to get my app. I've set the status in the query param and the post body, just in case. The docs aren't clear about that. Project ID is 4505074364317696.

### Product Area

Crons

### Link

https://{company-slug}.sentry.io/crons/{project-slug}/test-rok/?project=4505074364317696&statsPeriod=1h

**Comment by wedamija** [comment]
Hi @rokcarl 

You have configured this monitor with a schedule of `"*/2 * * * *"`, but your actual crontab is `*/5 * * * *`. Could you make these line up and see whether the problems here still persist?

**Comment by rokcarl** [comment]
Same problem, it's just that the 2 check-ins are now closer together:

<img width="1106" alt="Screenshot 2024-04-04 at 10 00 24" src="https://github.com/getsentry/sentry/assets/42874/5c818074-1492-4832-b825-2a9c7baeaeef">
<img width="1105" alt="Screenshot 2024-04-04 at 10 00 31" src="https://github.com/getsentry/sentry/assets/42874/48200cd8-1005-40ed-b299-4a5e1939e856">

So it looks like we might be dealing with two separate issues, i.e. the 2 check-ins problem and the one where the cadence is not the same but Sentry doesn't figure this out.

**Comment by wedamija** [comment]
Hi @rokcarl 

I haven't been able to reproduce this using your script. I have it running on a cron as well, and it never produces these duplicates. I have a few thoughts around this:
 - Is it possible you are running this script twice somehow? I could imagine all kinds of weird results if you had duplicate checkins being sent.
 - Could you try changing your monitor slug and see if this issue keeps happening on a new monitor?
 - Another useful way to diagnose this is to use checkin ids for your checkins. You can follow this guide to add them in https://docs.sentry.io/product/crons/getting-started/http/#overlapping-jobs-optional. If you do this, log the checkins/times for each of your checks and paste them here, it will be helpful to help me diagnose.

**Comment by rokcarl** [comment]
After debugging, for some reason, my cron job was firing twice, so I refactored [the code](https://gist.github.com/rokcarl/c485fc1c7a465bfd99fb619a810e2b7c) a bit.

Seems to work fine now, if the app works fine. But if it breaks (simulated with random fails), I get empty spaces in Sentry and no alerts. As if it's working fine. But it's not. I should get an alert?

<img width="1284" alt="Screenshot 2024-04-08 at 11 32 26" src="https://github.com/getsentry/sentry/assets/42874/ad80c9af-1bdb-44b8-8037-dc821ff420eb">
<img width="1288" alt="Screenshot 2024-04-08 at 11 32 33" src="https://github.com/getsentry/sentry/assets/42874/bf67e04f-cd4f-4ef8-883d-d86d80d67e5c">

Here's the log from the app:

```
Cron started at: Mon Apr  8 09:10:02 UTC 2024
09:10:03 App start
09:10:03 Starting actual work.
09:10:23 Done the work.
Cron started at: Mon Apr  8 09:12:01 UTC 2024
09:12:02 App start
09:12:02 Starting actual work.
09:12:02 Random fail of the job
Cron started at: Mon Apr  8 09:14:01 UTC 2024
09:14:02 App start
09:14:03 Starting actual work.
09:14:23 Done the work.
Cron started at: Mon Apr  8 09:16:01 UTC 2024
09:16:02 App start
09:16:03 Starting actual work.
09:16:23 Done the work.
Cron started at: Mon Apr  8 09:18:01 UTC 2024
09:18:02 App start
09:18:02 Starting actual work.
09:18:22 Done the work.
Cron started at: Mon Apr  8 09:20:01 UTC 2024
09:20:02 App start
09:20:02 Starting actual work.
09:20:22 Done the work.
Cron started at: Mon Apr  8 09:22:01 UTC 2024
09:22:02 App start
09:22:02 Starting actual work.
09:22:22 Done the work.
Cron started at: Mon Apr  8 09:24:01 UTC 2024
09:24:02 App start
09:24:03 Starting actual work.
09:24:23 Done the work.
Cron started at: Mon Apr  8 09:26:01 UTC 2024
09:26:02 App start
09:26:03 Starting actual work.
09:26:23 Done the work.
Cron started at: Mon Apr  8 09:28:01 UTC 2024
09:28:02 App start
09:28:03 Starting actual work.
09:28:23 Done the work.
```

☝️ you can see the random fails, the gaps in Sentry, but nothing that would indicate that Sentry thinks crons have been missed.

**Comment by rokcarl** [comment]
And even when I turn off my app, Sentry does see that the crons went missing, but I don't get notified, even though I'm configured.

<img width="1284" alt="Screenshot 2024-04-08 at 12 06 31" src="https://github.com/getsentry/sentry/assets/42874/6c2d5ca8-fe81-41f9-87b3-749426181308">
<img width="400" alt="Screenshot 2024-04-08 at 12 06 04" src="https://github.com/getsentry/sentry/assets/42874/15a3bfbc-3dd0-4ece-9a5e-8bab3e10aab2">

**Comment by wedamija** [comment]
Hi @rokcarl 

This is because your max runtime is set to 30 ![Screenshot 2024-04-08 at 9 49 40 AM](https://github.com/getsentry/sentry/assets/6288560/a1f03812-da83-4ec4-a1a4-c0b80ca59c09)

Since you aren't using checkin_ids, you still have an active checkin open, and so your jobs end up overlapping. You have two options here:
- https://docs.sentry.io/product/crons/getting-started/http/#overlapping-jobs-optional use checkin ids, so that you can have jobs open in parallel
- Lower your max runtime so that your job will fail before the next job starts

**Comment by wedamija** [comment]
I'm not sure why you're not receiving notifications, could you check your notification settings are enabled for this project? https://docs.sentry.io/product/alerts/notifications/notification-settings/

**Comment by rokcarl** [comment]
Modifying the max runtime helped, also configuring the notification settings. Thank you.
