### ISSUE TITLE
Allow using equation in "Big number" view in dashboard

### ISSUE THREAD

**Issue by gotenxds** [getsentry/sentry#68167]
### Problem Statement

Hi, I would like to create a "big number" that is a percentage of two data points, today we can only use single datapoints or preconfigured functions

### Solution Brainstorm

I would like to have the ability to create two queries like I have in other views, then based on these two create a calculation

for example
query one: [tag]: true
query two: [tag]: false

big number: percentage(count(query one), count(query two))

### Product Area

Dashboards

**Comment by gggritso** [comment]
This request makes sense, thanks for raising this! I'll add it to our backlog, but I can't give you an estimate on when we'll work on this, sorry 🙏🏻
