### ISSUE TITLE
Add quota limit notifications for 50% usage

### ISSUE THREAD

**Issue by stijndecubber** [getsentry/sentry#68164]
### Problem Statement

It would be nice to set quota limit notifications for 50% usage, next to 80% and 100% which are currently supported.

### Product Area

Alerts

**Comment by brianthi** [comment]
We're actively working on this exact feature! We plan to allow users to define and set notifications thresholds for both your reserved event volumes and on-demand volumes. We'll provide an update on this issue once it's shipped.

**Comment by brianthi** [comment]
This feature has been rolled out and you can set thresholds in 10% increments for your reserved volume and pay-as-you-go in your organization settings here: https://sentry.io/settings/billing/notifications/
