### ISSUE TITLE
User Feedback UI: Shows incorrect environment

### ISSUE THREAD

**Issue by kaushik546** [getsentry/sentry#68179]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Login sentry
2. Go to User Feedback (New User Feedback UI) from left menu
3. Click an issue
4. Shows wrong environment

### Expected Result

We need to show correct environment in both new and old view

### Actual Result

On the new User Feedback UI, it shows the wrong environment. See the screenshot below:
![image](https://github.com/getsentry/sentry/assets/11855976/6850d7c3-f7a3-42cb-8f1d-18fe8ee30995)

But the old User Feedback UI shows the correct environment. See below screenshot:
![image](https://github.com/getsentry/sentry/assets/11855976/a3aeb25f-b737-478e-b8d2-65a0259be345)

### Product Area

User Feedback

**Comment by bruno-garcia** [comment]
Unfortunately reports from the crash report modal don't have a way to specify the `environment` in its current form. We plan to resolves this though by using a new envelope format for user feedback which we've recently built to enable the Widget used for user-initiated feedback.

**Comment by JoshFerge** [comment]
Fixed with https://github.com/getsentry/sentry/pull/68317
