### ISSUE TITLE
UX Problems with Member Invite Modal

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#68181]
The member invite modal is giving me mixed messages

[Slack Message](https://sentry.slack.com/archives/CQDHVRS2W/p1712159017205319?thread_ts=1712159017.205319&cid=CQDHVRS2W)

![image](https://github.com/getsentry/sentry/assets/109983869/5aa18f10-c82b-4224-b5af-167780120ec8)
![image](https://github.com/getsentry/sentry/assets/109983869/aa4b2d64-818f-4fa5-a6c7-292889ddcd3d)

**Comment by evanpurkhiser** [comment]
Guessing we'll be able to close this @ameliahsu with the new modal

**Comment by ameliahsu** [comment]
Closed by https://github.com/getsentry/sentry/pull/77528
