### ISSUE TITLE
Inbound Filters for Attributes

### ISSUE THREAD

**Issue by kwiesmueller** [getsentry/sentry#6819]
We are using sentry in command-line and other tools we supply our admins with.
These tools are mainly developed in java and golang and directly executed from our infrastructure git repo.

We now saw, that many issues being sent to sentry are from our devs building these tools and mails and bots sending events are too spammy as only a small amount of events is really relevant.

As we are all working in the same subnet with partially dynamic ip's, we can not use ip-filters to exclude dev machines from sentry. Therefor it would be helpful to filter events based on attributes like server_name.

We are on the hosted version of sentry and switched from open source some while ago, so doing it ourselves is not really an option.
Any plans on doing this as a feature?

**Comment by BYK** [comment]
I think this should be done at the SDK level using a `before_send` hook. I'll be closing this issue due to staleness but feel free to comment here if you think we should be working on this.
