### ISSUE TITLE
Duplicate spike protection messages in Slack

### ISSUE THREAD

**Issue by archon810** [getsentry/sentry#68222]
### Problem Statement

Hi,

Every time a spike protection gets activated or deactivated, I get a message in Slack in the respective channel as well as an email, which is great. But Sentry also direct messages me in Slack with the same notification, creating a duplicate notification in Slack that I have to then dismiss.

Is it possible to stop getting these direct messages?

Thank you.

### Solution Brainstorm

There's a setting in spike protection notification settings, and I have both email and slack selected as they're both desired. IMO this delivery method dropdown should have Slack split into 2 options: Slack DMs and Slack channel messages. Or it could be some setting for the Sentry slack bot.

### Product Area

Settings - Spike Protection

**Comment by souredoutlook** [comment]
Hi @archon810 I'm going to forward this to Engineering just in case there is something I missed but you should be able to disable personal notifications to Slack for this specific category of alert here: https://sentry.io/settings/account/notifications/spike-protection/

**Comment by ceorourke** [comment]
Without knowing your organization / who you are in Sentry I can only guess, but do you possibly have both your personal notifications enabled (as @souredoutlook noted) _and_ a spike protection Slack channel set up (https://sentry.io/settings/{org_slug}/spike-protection/)? That would account for the duplicate Slack notifications.

**Comment by archon810** [comment]
Aha, now we're getting somewhere, I think you nailed it @ceorourke.

Under spike protection settings for the org https://sentry.io/settings/%7Borg_slug%7D/spike-protection/, for this project, we have this:
![image](https://github.com/getsentry/sentry/assets/469543/b96af75b-8d0a-4156-a476-93c1cf922860)

But separately under https://sentry.io/settings/account/notifications/spike-protection/, I have this:
![image](https://github.com/getsentry/sentry/assets/469543/a0d22ca5-b6f0-463b-9646-3798a55c88ca)

So to be clear, the personal account settings delivery method "Slack" - what is that? A direct message? This is the confusing part - it's not clear what "Slack" will do there - I was under the impression that it means both a DM and a message to the channel. This page also has a section called "Settings for organization" with a list of projects and values ("on" or "off"). I think I understand now that this allows customizing pings per project but once again only for my account (so only slack DM, not slack channel pings).

And finally, there's no link or mention of https://sentry.io/settings/%7Borg_slug%7D/spike-protection/ on the https://sentry.io/settings/account/notifications/spike-protection/ page - this omission made me not realize there are 2 pages that handle spike protection notifications in a different way. Room for improvement.

**Comment by ceorourke** [comment]
Hi @archon810 - to answer your questions:

> personal account settings delivery method "Slack" - what is that? A direct message?

Yes, since it's your user level setting this entire settings section refers to notifications that will go directly to you, the user, be it email, Slack (in which case it's a DM to you the user), etc. 

> a section called "Settings for organization" with a list of projects and values

Yep, this is whether or not you want to be notified via the selected delivery methods for notifications in a particular organization's projects. 

To your last point, I'm making a ticket for us to make the connection between the two pages more obvious. I'm not entirely sure how we can clarify the Slack DM vs. channel confusion in the personal settings page, but I'm bringing this up as well. 

Thanks for your feedback and I hope you're getting the desired amount of spike protection notifications now!
