### ISSUE TITLE
Cron Onboarding: Wrong "Root URL"

### ISSUE THREAD

**Issue by JeremiaAu** [getsentry/sentry#68237]
### Self-Hosted Version

24.3.0

### CPU Architecture

x86_64

### Docker Version

26.0.0

### Docker Compose Version

2.25.0

### Steps to Reproduce

1. Add New Cron Monitor
2. On page titled "Instrument your monitor"
3. Select "cURL" from the dropdown

### Expected Result

Displaying the configured "Root Url" in code Snippet e.g.:
`SENTRY_INGEST="https://sentry.example.com"`

### Actual Result

`SENTRY_INGEST="https://o1.ingest.sentry.io"`

**Comment by evanpurkhiser** [comment]
Ah good catch! Will get this fixced
