### ISSUE TITLE
Enable database query insights feature for self-hosted

### ISSUE THREAD

**Issue by begemotik** [getsentry/sentry#68238]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

2.24.7

### Steps to Reproduce

1. Add the following configuration block to sentry.conf.py:
```
##############################
# Database view feature flag #
##############################
SENTRY_FEATURES["organizations:performance-database-view"] = True
SENTRY_FEATURES["organizations:performance-database-view-percentiles"] = True
```

### Expected Result

Expected [the feature](https://blog.sentry.io/find-slow-database-queries-with-query-insights/) added and "Queries Insight" available for the projects. Apart from that there is a message which leads me to the thinking that there should be something else to enable the feature.

### Actual Result

The endpoint `organizations/<org-name>/performance/database` becomes visible, but there is no any metric there.
<img width="1461" alt="Screenshot 2024-04-02 at 11 35 05" src="https://github.com/getsentry/self-hosted/assets/35958211/739a7556-3ae5-4a2c-b09d-0ec90ff2a9bc">

**Comment by gggritso** [comment]
@begemotik thanks for raising this! In order to use the Queries feature, you'll also need a few more features. Sentry 24.3.0 (just one ahead of yours) has those features enabled by default. Could you give that a try?

**Comment by begemotik** [comment]
@gggritso, thank you for the response.

It would take some time to upgrade the current installation. I will get back to you, for sure, with the result when we've updated it. I hope it's ok to leave the issue open until then.

**Comment by begemotik** [comment]
Hello @gggritso,

I can confirm that it works with the latest version. Thank you
