### ISSUE TITLE
"I would like to inquire in detail about whether the profiling in Sentry includes all the metrics measurable in Chrome DevTools Performance, such as scripting, rendering, and painting. Could you please provide information on this matter?"

### ISSUE THREAD

**Issue by miridih-jujang** [getsentry/sentry#68271]
### Problem Statement

"I would like to inquire in detail about whether the profiling in Sentry includes all the metrics measurable in Chrome DevTools Performance, such as scripting, rendering, and painting. Could you please provide information on this matter?"

### Solution Brainstorm

I don't know

**Comment by JonasBa** [comment]
@miridih-jujang it currently does not. This is currently a spec limitation with a proposed [markers](https://github.com/WICG/js-self-profiling/pull/72) extension which would solve this by providing the information you are asking about as stack markers. I would encourage you to contribute to that issue and explain why you'd find it useful, that way it would help us push the spec forward!
