### ISSUE TITLE
Unable to create monitor through the Getting Started with Celery manual page

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#68272]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to crons page.
2. Select Project with no crons monitors
3. Select Celery
4. Select Manual
5. Try to create a monitor and see errors listed in below screenshot

[Link to Crons in my org for testing](https://francisorg.sentry.io/crons/?guide=manual&platform=python-celery&project=4506588713254912&statsPeriod=7d)

<img width="500" alt="Screenshot 2024-04-04 at 12 58 52 PM" src="https://github.com/getsentry/sentry/assets/96670625/0353c389-61e8-4477-b60c-a7678ad24db3">

### Expected Result

Monitor is created

### Actual Result

Monitor is not created

### Product Area

Crons

**Comment by gaprl** [comment]
Thank you for the report @Fwang36, we have been able to reproduce the issue and will send out a fix asap.
