### ISSUE TITLE
Dashboard filters not saving properly, changes made to one filter affect the filters on other dashboards

### ISSUE THREAD

**Issue by birdaw** [getsentry/sentry#68282]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open Sentry in Safari (not tested on other browsers)
2. Create multiple dashboards
3. Set different environment, project, and timeframe filters for each dashboard
4. Save your settings
5. Click out of and into each dashboard at random and note how the filters change/revert

### Expected Result

Each dashboard filter should only affect that specific dashboard. Dashboard filters should not auto-revert to other settings when leaving and returning to the dashboard. The "Save" button should save that dashboard filter, for that dashboard, until user manually changes the filter _in that dashboard_.

### Actual Result

The filters revert themselves unpredictably and seemingly at random, but commonly gravitate to one specific project/env/time setup.

No one else on the team is touching the dashboards, which makes me think that:
1) either Sentry's saving mechanism is broken, or
2) there is a caching issue happening where someone has the dashboard open in a passive browser tab on their machine and unbeknownst to them, has a saved configuration different than mine.

If this is a known issue where some other user has the dashboard open passively on their machine, and the filters are universal and NOT per-user, and there is some caching issue between the way the other user has the dashboard saved and the way the user observing the problem has the dashboard saved, _then please put this in the docs._ 

Unable to provide screen recording for privacy reasons.

Thanks all.

### Product Area

Dashboards

**Comment by k-fish** [comment]
Hey @birdaw, can you remove all the query params from the url and try again? The order that your filters get applied is roughly _Query Params_ -> _Saved Dashboard Filters_ -> _Global Settings_ in terms of precedence. URLs take precedence so all immediate views are shareable. 

eg. I might have a url like `https://***.sentry.io/dashboard/777/?project=123&statsPeriod=14d` which overrides the dashboard filter for project. 

If that's still not working, if you can share the dashboard id in question and I can take a look.

**Comment by birdaw** [comment]
I removed the params but found they got appended again when I went into Sentry > Dashboards > [any board], and somehow cross-pollinating each other (params meant for one board ID would show up when I clicked on the other board, etc)

The only thing that worked was clearing all cached data from Sentry and logging back into the site.

**Comment by k-fish** [comment]
If you've removed all the query params appends the incorrect params, that's unexpected. Whatever your saved filters are should be returned from the dashboard api call (check in the network tab, should be eg. `.../region/us/api/0/organizations/<your-org-name>/dashboards/<your-dashboard-id>/`).

Can you check the response from the api call and share it (minus any email / personal info)?
![Screenshot 2024-04-16 at 1 27 48 PM](https://github.com/getsentry/sentry/assets/6111995/9c3f627a-536e-4a5a-9f4b-86438cfe3519)

The values here are what should be setting your dashboard filters, it's the first thing a dashboard detail view does (for reference, [the codes does it here](https://github.com/getsentry/sentry/blob/49b5b7b97b608b7c4e5b4847bde02f8741b61e53/static/app/views/dashboards/orgDashboards.tsx#L113-L124))

**Comment by birdaw** [comment]
results are as they should be, nothing wrong here
since clearing the cache resolved the issue I'm assuming my browser decided to play games of its own volition.
I'm no longer able to replicate the behavior in either chrome or safari

<img width="1009" alt="Screenshot 2024-04-16 at 11 21 21 AM" src="https://github.com/getsentry/sentry/assets/90013375/0c953134-511e-46cc-9b71-dbd5dece89d3">

**Comment by ale-cota** [comment]
Since the issue seems to have been resolved with the cache clearing, I will close this issue.
