### ISSUE TITLE
Don't show model if undefined

### ISSUE THREAD

**Issue by kirkins** [getsentry/sentry#6830]
I made a PR https://github.com/getsentry/sentry/pull/6742 that stopped the value "n/a" from showing for device.family when it was empty.

It was supposed to work for model too but it's showing as undefined. Maybe it's being set to the string "undefined" instead being empty like family?

![untitled](https://user-images.githubusercontent.com/9503662/34281381-54ba0e0e-e68c-11e7-86db-ef993c474b07.png)

**Comment by priscilawebdev** [comment]
@kirkins Thank you for reporting this.

I just checked the UI and I can say that we no longer display` n/a` and `undefined` when the value is `undefined`, but if the value is an "undefined" string, it will be displayed. Could you please paste here the response you are receiving? the request should look like `api/0/issues/${groupId}/events/latest/` 😉

**Comment by priscilawebdev** [comment]
Since this already fixed in the product, I am closing this for now
