### ISSUE TITLE
Subscription page is showing "Cron Monitors Trial" when there is no trial enabled 

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#68376]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Navigate to Subscription page
2. Observe the quota usage is showing "Cron Monitors Trial" even when there is no trial enable for the organization 
<img width="495" alt="Screenshot 2024-04-05 at 1 40 15 PM" src="https://github.com/getsentry/sentry/assets/99350819/21a404d7-3d5b-43af-99c5-6edf5e2583bb">

### Expected Result

If the organization is not on a trial, the Crons quota should show "Cron Monitors"

### Actual Result

The organization is not on a trial and the Crons quota shows "Cron Monitors Trial"

### Product Area

Settings - Subscription

### Link

https://org2-w7.sentry.io/settings/billing/overview/

**Comment by isabellaenriquez** [comment]
thanks for bringing this to our attention! i've identified the issue and will put up a PR sometime today to remedy this 🙌🏽
