### ISSUE TITLE
How to connect elasticsearch and sentry

### ISSUE THREAD

**Issue by gr-jialeiwang** [getsentry/sentry#6837]
## General Support
I am using [getsentry/onpremise](https://github.com/getsentry/onpremise) version 8.22.0.
I used docker to install sentry on my local MacBook.
And i installed elasticsearch by docker on my local MacBook too.
Elasticsearch's image is docker.elastic.co/elasticsearch/elasticsearch:5.4.1.

Now, i want to connect elasticsearch to sentry, the thing i want to do is,
When elasticsearch receive an error data, then automatically push this data to Sentry.

I do not know how to setting elasticsearch,
Is there someone can tell me how to do this?

**Comment by sreeram-boyapati** [comment]
pipe all errors from elasticsearch to some forwarder script which uses sentry api to register it in sentry.
