### ISSUE TITLE
Events not be updated even i choose 24H

### ISSUE THREAD

**Issue by gr-jialeiwang** [getsentry/sentry#6838]
I am using sentry-UI now, there are 24H and 14D on the event list.
When i clicked 24H, the list be freshed, but the event number seems still 14D's count.
I only want to know how many events happened on 24H.

Please refer to the image, 15 is 14D's count, i want 24H's count, and 24H's count is 7,
What should i do to make 24H's count be shown?

<img width="1339" alt="screen shot 2017-12-25 at 15 10 38" src="https://user-images.githubusercontent.com/12379440/34334015-cd001b1e-e985-11e7-8d97-bf8295e8ad37.png">

**Comment by MaxBittker** [comment]
is this fixed now @gr-jialeiwang ?
