### ISSUE TITLE
SAML2 integration failing for XML & IdP data with various error messages

### ISSUE THREAD

**Issue by Prithvirajkumar** [getsentry/sentry#68380]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Setting up SAML2 results in different errors being thrown for various attempts with no clear indication of what the issue is.

This user tested setting up SAML2 using XML & IdP options and failed. 

### Expected Result

Integration should work and if it does not, more information about why it failed needs to be presented on the UI 

More details in [customer case](https://www.notion.so/sentry/JPMorgan-Chase-SAML2-Authentication-error-9a2dd786562042c0b7a3c650329c2b7f?pvs=4)

### Actual Result

The following error messages are being displayed:
- The organization does not exist or does not have SAML SSO enabled.
- Authentication error: Failed to map SAML attributes. Assertion returned the following attribute keys: 'Email'
- Authentication error: Failed to map SAML attributes. Assertion returned the following attribute keys: 'Email', 'Firstname', 'Surname'

### Product Area

Settings - Auth

**Comment by nhsiehgit** [comment]
Unfortunately this issue may just be a result of SAML/Auth logic being complicated and difficult to understand/set up.

the SSO flow (either auth or saml) requires a handshake between the service (us) and the identity provider (eg. okta, google, etc.)
If a user has set up their credentials incorrectly, or has mapped the incorrect values - there's no way for us to know what the IdP is expecting, so we can only surface the errors they kick back to us.

we could potentially alleviate this painpoint by providing better documentation - however every IdP is going to be different, and we are not an auth company like okta is :/ 

I'm inclined to close this issue out as a won't do, but let me know what you think here

**Comment by leedongwei** [comment]
- Authentication error: Failed to map SAML attributes. Assertion returned the following attribute keys: 'Email'
- Authentication error: Failed to map SAML attributes. Assertion returned the following attribute keys: 'Email', 'Firstname', 'Surname'

This means that the person setting up the SSO config on Sentry's webapp need to use the `Email`, `Firstname` or `Lastname` in the key mapping.

**Comment by nhsiehgit** [comment]
Spoke with Prithvi directly and suggested providing the customer with a link to our [AzureAD SAML SSO documentation](https://docs.sentry.io/product/accounts/sso/azure-sso/)

@Prithvirajkumar let us know if this resolves their issue.
I'm going to close this ticket out for now. If they're still having trouble please feel free to reopen
