### ISSUE TITLE
Linear Integration does not seem to be working for some instances

### ISSUE THREAD

**Issue by Prithvirajkumar** [getsentry/sentry#68392]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Linear Integration does not seem to be working for some instances

### Expected Result

Once the Linear integration is set up, Sentry users should be able to create a Linear issue from Sentry as shown in the example:
![Screenshot 2024-04-05 at 5 43 30 PM](https://github.com/getsentry/sentry/assets/56081556/815fa9cf-4930-4b6b-9f9c-f4ac3b089785)
![Screenshot 2024-04-05 at 5 43 40 PM](https://github.com/getsentry/sentry/assets/56081556/ee6b9e79-56d3-4ddd-9a5a-61b3a3ccd316)

### Actual Result

Even though the integration is set up, the option is greyed out as seen in the example below:
<img width="283" alt="Screenshot 2024-04-05 at 7 41 24 PM" src="https://github.com/getsentry/sentry/assets/56081556/7e3da6de-f86a-4f7a-b8cd-7c5f528514ae">

### Product Area

Settings - Integrations

### Link

More details in case [here](https://www.notion.so/sentry/Monzo-Linear-Integration-does-not-seem-to-be-working-for-some-instances-021306177c1147e4ba16c5f09b5598cd)

**Comment by Dhrumil-Sentry** [comment]
Feedback from Eng:

The link is disabled on the Issues page if the integration's   webhook returns errors

https://github.com/getsentry/sentry/blob/master/static/app/components/group/sentryAppExternalIssueActions.tsx#L151
https://github.com/getsentry/sentry/pull/37454

@Prithvirajkumar in case this helps the investigation

**Comment by miriambudayr** [comment]
I am having the same issue right now as well. 

<img width="276" alt="image" src="https://github.com/getsentry/sentry/assets/35577323/574e41e9-8e50-42a4-a67d-a52455e703c7">

**Comment by Dhrumil-Sentry** [comment]
@Prithvirajkumar We're getting a bunch of 400s from Linear which is likely causing the problem and the customer may have to check with Linear

**Comment by sentaur-athena** [comment]
I'm closing the issue since some time has past with no communication. Please feel free to create a new one if the issue persists.
