### ISSUE TITLE
Install plugin takes forever

### ISSUE THREAD

**Issue by matanbanin** [getsentry/sentry#68399]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Install Sentry Jira plugin

### Expected Result

will install

### Actual Result

![image](https://github.com/getsentry/sentry/assets/14214701/d487c083-135f-45dd-a8e7-da83364729c7)

### Product Area

Unknown

**Comment by cathteng** [comment]
Have you tried disabling ad blocker? https://docs.sentry.io/product/integrations/issue-tracking/jira/#something-went-wrong-message-with-jira-on-saas-sentryio-install
