### ISSUE TITLE
Editing monitors consume cron quota.

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#68405]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a new monitor, the Crons quota is increased by one
2. Rename the existing monitor

### Expected Result

The used Crons quota is not affected. 

### Actual Result

The used Crons quota is increased by one. 

### Product Area

Crons

**Comment by isabellaenriquez** [comment]
To be clear, this occurs when the _slug_ is changed, not just the name.

**Comment by rodolfoBee** [comment]
@isabellaenriquez Is it intended behaviour?

**Comment by gaprl** [comment]
> @isabellaenriquez Is it intended behaviour?

No, we're fixing it.

**Comment by evanpurkhiser** [comment]
I believe @wedamija fixed this here https://github.com/getsentry/sentry/pull/68491
