### ISSUE TITLE
how do I unlink sentry

### ISSUE THREAD

**Issue by kdong007** [getsentry/sentry#6841]
it keeps asking for organization slug/project slug/DSN/Auth token. All the hint urls like `It can be found here: ****` are all broken and all leads to dashborad.

I simply get it removed and do a fresh install. but its blocking me from doing anything

**Comment by mattrobenolt** [comment]
Hey @kdong007, what do you mean by "unlink sentry"?

**Comment by kdong007** [comment]
@mattrobenolt sorry wrong repo.
