### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by FanPower** [getsentry/sentry#68523]
### Problem Statement

use Auth token request Sentry APIs, return {'detail': 'Invalid token'}. Auth token was just created and full authority.

### Product Area

Issues

**Comment by mdtro** [comment]
@FanPower I'll see if I can help you on this issue, but I may need some more details.

- Are you referring to a user auth token or an org auth token?
- How much time had passed between the time you created the token and attempted to use it for authentication?
- Were you eventually able to authenticate with the token?

**Comment by mdtro** [comment]
Hi @FanPower -- I'm going to close out this issue. If you run into this again, please let me know with the additional details included and we can reopen it.
