### ISSUE TITLE
[Replay] Bug: Trace timeline misaligned

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#68529]
[Replay](https://sentry.sentry.io/replays/d08ccc72928c44e0a695e1fb38039f99/?referrer=%2Fperformance%2Ftrace%2F%3AtraceSlug%2F&t=0&t_main=trace)

As seen below, the calls to the backend on the trace tab happen a lot after they actually did as seen in the timeline
![image](https://github.com/getsentry/sentry/assets/1633368/4d5be011-6ade-4fe7-b1ef-50d653ca7f76)

**Comment by ryan953** [comment]
This is fixed with the new trace timeline which is being rolled out!

**Comment by ryan953** [comment]
This is fixed with the new trace timeline which is being rolled out!
