### ISSUE TITLE
iPhone model can not show properly

### ISSUE THREAD

**Issue by SpaceGrey** [getsentry/sentry#68608]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Upload a message with the iPhone 15 series or newer.

### Expected Result

Show the iPhone model name.

### Actual Result

It displays the iPhone‘s internal device code instead of the model name.
<img width="537" alt="Screenshot 2024-04-10 at 8 32 45 PM" src="https://github.com/getsentry/sentry/assets/78807862/2d7458c6-aa19-4de0-950d-29149198267c">

### Product Area

Unknown

**Comment by MichaelSun48** [comment]
Hey there @SpaceGrey! 👋 

I've just put up the PR above to fix this in the next deployment 👍 Thanks for surfacing this and helping us make Sentry better!
