### ISSUE TITLE
cURL instructions for crons setup show `crons` instead of `cron`

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#68622]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create new monitor.
2. Look at setup instructions for cURL
3. `SENTRY_CRONS` lists `crons` instead of `cron`

[Link to a new Cron monitor in my org](https://francisorg.sentry.io/crons/2cordova/test/?project=4505902853062656) Click the dropdown and change to cURL at the bottom

<img width="700" alt="Screenshot 2024-04-10 at 12 13 30 PM" src="https://github.com/getsentry/sentry/assets/96670625/080c8998-ee90-4edf-8fe3-2617b0a0c1eb">

### Expected Result

Should say `cron`

### Actual Result

`crons` leads to a 404

### Product Area

Crons

**Comment by evanpurkhiser** [comment]
Ah! Thank you for catching this! https://github.com/getsentry/sentry/pull/68702

This regressed while I was fixing https://github.com/getsentry/sentry/issues/68237
