### ISSUE TITLE
Unable to change performance settings of transferred projects

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#68678]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Transfer a project from one organization to another
2. Go to the project's settings > performance
3. Change the "Response Time Threshold (ms)" field from 300 to something else, ie. 2500

### Expected Result

The change saves successfully.

### Actual Result

We get a 500 Internal Error. The error in Sentry's Sentry can be found [here](https://sentry.sentry.io/issues/5174975071/events/2dcdcf5678154e74aa1e6f5796f987f9/?project=11276&referrer=issue-list&statsPeriod=7d).

The transfer was made from and to orgs from the US data region, and this was tested by transferring to both a paid and a free org.

### Product Area

Settings - Projects

**Comment by shruthilayaj** [comment]
Thanks for reporting, will get this fixed soon!

**Comment by K-AYU-SHHH** [comment]
@shruthilayaj  @cathteng @InterstellarStella Can you please give me more context about the changes ? Please allow me to take this change as i am very new to open-source contribution and looking forward to join the community.

**Comment by shruthilayaj** [comment]
@K-AYU-SHHH Apologies! I already put up a fix - essentially, the try/except pattern was causing a race condition so the fix was to do an update_or_create
