### ISSUE TITLE
Issue Search Discovery: Which search terms are used most often

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#68754]
If possible, answer this question with existing analytics on Amplitude or Redash. If not possible, add frontend analytics to enable this.

At the very least, we want to know the frequency of search keys such as `is`, `user.email`, etc. If possible, we would also like to know the frequency of pairing which have a hardcoded set such as `is:unresolved`, `priority:low`, etc.

**Comment by MichaelSun48** [comment]
[Redash query](https://redash.getsentry.net/queries/3140/source) courtesy of Dhrumil. (Note that the count is the total number of _paid_ and _active_ orgs that have used that query in the last day, NOT the number of times that query was used) 

[Here's](https://redash.getsentry.net/queries/new) another query that measures the number of times we see the query across all orgs in the last day.

Some insights from these queries:
* Queries are not case-normalized (`is:unresolved typeerror` and `is:unresolved TypeError`)
* 4 of the top 25 queries are clearly looking for http response status codes, but they don't use the `http.status_code` parameter and instead just search for the code as a raw string.  Perhaps we should increase the visibility of this parameter?
