### ISSUE TITLE
Issue Search Discovery: How frequently is the `is:for_review` term used?

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#68758]
If possible, answer this question with existing analytics on Amplitude or Redash. If not possible, add frontend analytics to enable this.

**Comment by MichaelSun48** [comment]
[Amplitude chart](https://app.amplitude.com/analytics/share/cdb3382c4f04418ca96f05b0c4d7bbf7) comparing number of total searches and number of searches containing `is:for_review`.

Redash query showing the queries themselves and what other tokens are called with it. 

Insights: 
* `is:for_review` is rarely used - 2 orders of magnitude less than the total number of searches. 
* `is:for_review` is never the only token in the query
