### ISSUE TITLE
Issue Search Discovery: Which type of queries take the longest?

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#68755]
If possible, answer this question with existing analytics on Amplitude or Redash. If not possible, add frontend/backend analytics or metrics to enable this.

**Comment by MichaelSun48** [comment]
[Sentry Performance](https://sentry.sentry.io/performance/summary/events/?breakdown=none&project=1&query=http.method:GET&showTransactions=p100&sort=-transaction.duration&statsPeriod=7d&transaction=/api/0/organizations/%7Borganization_slug%7D/issues/) 🙌  view of requests that took a long time. 

I dug into the queries behind these requests, and they all seem very regular. Weirdly (and perhaps worryingly), most of them are just `is:unresolved`. I'll dig deeper to see if there is stronger evidence of a specific type of query taking longer than others, but this view is a start.
