### ISSUE TITLE
GitLab Integration Problem: Other sentry users can see private GitLab repositories when creating an GitLab Issue from within Sentry

### ISSUE THREAD

**Issue by lennartdohmann** [getsentry/sentry#68800]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Self-hosted sentry v24.3.0
2. Self-hosted GitLab Enterprise Edition [v16.10.1-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v16.10.1-ee)
3. Sentry - GitLab Integration with whole GitLab instance connected
4. In the right-hand bar on any Issue on _Issue Tracking_ click on _GitLab Issue +_
5. In the _GitLab Project_ drop down menu, any user is able to see any repository inside the GitLab instance (private user repositories, private repositories of any groups, etc.), even that not explicitly added in the integrations settings

### Expected Result

Of course, by linking an entire GitLab instance of an admin user, Sentry has API access to all groups, repositories and projects, but I would expect that this would not allow other Sentry users to see what repositories etc. are in the entire GitLab instance, especially if they are private or from private groups. 

I would have expected that the selection of projects in which you can create a GitLab issue from a Sentry issue are either the GitLab projects that you have mapped to the Sentry projects in the integration settings, or you can set which GitLab projects can be selected by which Sentry team/user. Especially because there is already a project selection and also a mapping of GitLab projects to Sentry projects in the integration settings.

Maybe I just overlooked some setting, did something wrong with the integration or didn't think of any meaningful reason for it. I am grateful for any help to create a little more privacy towards the GitLab instance at this point.

### Actual Result

The following drop down menu in the project selection of creating a GitLab-Issue from within a Sentry Issue shows all repositories inside the GitLab instance, not only those that have been added to Sentry in the integration settings, and not only the GitLab projects that have been mapped to Sentry projects in the integration settings.

![2024-04-10_16-57](https://github.com/getsentry/sentry/assets/99874374/f79c764c-f7b0-4235-9147-8159a0e3e52a)

### Product Area

Issues

### Version

24.3.0

**Comment by sentaur-athena** [comment]
@lennartdohmann to clarify, when adding repos to sentry, you setup sentry for all the repos but on gitlab some of your org members don't have access to some of the repos, and you want to keep it that way in Sentry. Can you confirm this?

**Comment by lennartdohmann** [comment]
> @lennartdohmann to clarify, when adding repos to sentry, you setup sentry for all the repos but on gitlab some of your org members don't have access to some of the repos, and you want to keep it that way in Sentry. Can you confirm this?

Yes, I can confirm this. The members in Sentry can see everything in GitLab in the drop-down menu, instead of just the projects selected for them.

**Comment by sentaur-athena** [comment]
Looking back at this, if a repo is added as an integration to Sentry it has to be accessible for many reasons for the members of that org. If you want the repo not to show up in the drop down for issue creation, it's better to remove it from the integration.
