### ISSUE TITLE
[Replay Index] Update Unsupported Banner Message for Android, iOS and React Native projects to link out to Waitlist

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#68816]
### Update Unsupported Banner Message for Android, iOS and React Native projects

Change message from screenshot to "Session Replay isn't available for [PROJECT] at the moment. To join our waitlist for mobile, click [here](https://sentry.io/lp/mobile-replay-beta/). To learn more about which SDKs we support today, please visit our [DOCS]."

![Image](https://github.com/getsentry/sentry/assets/77064737/ac3a80b7-bc6d-4137-ae52-dde932b60695)

**Comment by bruno-garcia** [comment]
I suggest also adding to:

**Comment by jas-kas** [comment]
@bruno-garcia did you finish your sentence?

**Comment by bruno-garcia** [comment]
Also, how about:

> Session Replay isn't available for [PROJECT] at the moment. Web is currently supported, and Mobile is being developed right now, [join our waitlist here](https://sentry.io/lp/mobile-replay-beta/)."

**Comment by bruno-garcia** [comment]
done: https://github.com/getsentry/sentry/pull/68836
