### ISSUE TITLE
Unable to search by transaction.duration in Discover

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#68858]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Make sure you have sent some transactions to Sentry
2. Go to Discover
3. Enter the query `transaction.duration:>=0`

### Expected Result

All transaction sent to Sentry should show up.

### Actual Result

The graph seems populated but the table below it is void of any entries. This doesn't happen with other queries like `event.type:transaction`.

In the browser's console we can see some CORS errors.
![Untitled](https://github.com/getsentry/sentry/assets/81985895/2a2cfbcb-70d4-4c1e-a1db-9edbab50f497)

And in Sentry's Sentry we are getting an [Unsupported search query](https://sentry.sentry.io/issues/4629808805/events/58f542608b884f6e9df0554e45eab55f/) error.

This is affecting some Organizations that have started the [Metrics beta](https://sentry.io/lp/metrics/). Other queries work normally in the affected orgs. More details [in the shadow ticket](https://getsentry.atlassian.net/browse/FEEDBACK-2145).

### Product Area

Discover

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2145) by [Unito](https://www.unito.io)

**Comment by k-fish** [comment]
Brought up already in internal channels, should be fixed by https://github.com/getsentry/sentry/pull/68952

**Comment by Zylphrex** [comment]
This should be fixed now.
