### ISSUE TITLE
Rename "Add Query" button?

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#68878]
None of the 11 customers we spoke to were looking at multiple queries at once. One in particular I probed on the topic recognised he didn't really understand what it's for.

Anyone familiar with DataDog and maybe other metrics tools will know this - what about the rest?

Rename to Add Metric and Remove Metric.

**Comment by K-AYU-SHHH** [comment]
@matejminar Can you please give me more context about the changes ? Please allow me to take this change as i am very new to open-source contribution and looking forward to join the community.
