### ISSUE TITLE
Dashboard - Query timeout in all different timeframes

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#68887]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Issue seems to primarily occur into 1 specific dashboard of a customer - I've shared it into internal ticket

### Expected Result

Data should show up in any timeframe

### Actual Result

![Screenshot 2024-04-15 at 14 08 04](https://github.com/getsentry/sentry/assets/25929053/3c1fe244-e7ce-4a49-b1dd-7286f0454762)

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2147) by [Unito](https://www.unito.io)

**Comment by k-fish** [comment]
Should be fixed by https://github.com/getsentry/sentry/pull/68952

**Comment by ale-cota** [comment]
This has since been resolved.
