### ISSUE TITLE
Transactions not showing by default on Discover list

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#68883]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Sent a few transactions to a project
2. Go to Discover page

### Expected Result

The transactions are shown on the table.

### Actual Result

No transaction is show on table. In the screenshot below you can see event count is 4, but only 2 events are listed:

![Screenshot 2024-04-15 at 13 14 56](https://github.com/getsentry/sentry/assets/64906376/70af251a-40d8-41a0-bcda-a4e8242680bc)

When adding the search `event.type:transaction` i can see the two missing events:
![Screenshot 2024-04-15 at 13 15 52](https://github.com/getsentry/sentry/assets/64906376/593444b5-9f15-4843-b152-502866ee3e0b)

### Product Area

Discover

### Link

https://dev-curumas.sentry.io/discover/homepage/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=5242419&query=event.type%3Atransaction&sort=-timestamp&statsPeriod=24h&yAxis=count%28%29

**Comment by flyingsilverfin** [comment]
We see the same - would be nice to get the old default behaviour back!

**Comment by k-fish** [comment]
Brought up already in internal channels, should be fixed by https://github.com/getsentry/sentry/pull/68952

**Comment by Zylphrex** [comment]
This should be fixed now.
