### ISSUE TITLE
Getting Started page for Elixir has wrong line of code shown

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#68895]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create New Project in Elixir
2. Be presented with Getting Started page for Elixir
3. See under Configure SDK the option `root_source_code_paths: File.cwd!()`

That should be `root_source_code_paths: [File.cwd!()]`.  Our docs on Elixir show the option correctly with the brackets [already here.](https://docs.sentry.io/platforms/elixir/#configure)

### Expected Result

<img width="400" alt="Screenshot 2024-04-15 at 9 48 02 AM" src="https://github.com/getsentry/sentry/assets/96670625/6d3d39f7-8fca-42ec-8083-a6cdf57fee4f">

### Actual Result

<img width="400" alt="Screenshot 2024-04-15 at 9 48 37 AM" src="https://github.com/getsentry/sentry/assets/96670625/bcb4d7b8-5828-404a-b539-5b6396dfa97f">

### Product Area

Projects - Project Creation

**Comment by ArthurKnaus** [comment]
@Fwang36 thx for reporting. Fix will go out soon 🙌
