### ISSUE TITLE
Select2 dropdown container width doesn’t resize properly

### ISSUE THREAD

**Issue by PerStirpes** [getsentry/sentry#6889]
- The version of Sentry you're using
lastest
- Include a redacted version of your configuration when relevant
does it on all major browsers

![resize](https://user-images.githubusercontent.com/19398470/34597409-432f84ec-f19b-11e7-92c3-0b617c56e4e2.gif)

**Comment by BYK** [comment]
Seems like this was fixed via #6890 but not auto closed.
