### ISSUE TITLE
Create relay server

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#689]
We should create a simple Python relay server that can be installed locally to queue events to the sentry remove

e.g.

```
pip install sentry-relay
sentry-relay start [options]
```

Clients could then have an option like relay='localhost' (hostname:port) as a shortcut for specifying this should proxy first.

The server would handle queueing events, accepting them immediately, and could potentially optimize things like sending things in bulk (e.g. if its happened 10 times before its sent).

**Comment by untitaker** [comment]
This now exists as https://github.com/getsentry/relay but is not fully usable yet.
