### ISSUE TITLE
[User Feedback] Add an 'activity' note to issues when a attachments are deleted

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#68907]
The proposal is:

When an attachment is deleted, save a note to the Activity log. Record who did the deletion, and when.

Something like this:
![Image](https://github.com/getsentry/sentry/assets/187460/a5ceb715-4f26-4759-b376-891cdb25a75b)

Some psuedocode is here: https://github.com/getsentry/sentry/pull/68468/files (this code does not 100% work, and needs tests!)

---

Spinning this off from https://github.com/getsentry/sentry/issues/67707

The original request was to show something like this in the UI (we should do something else though):
![Image](https://github.com/getsentry/sentry/assets/187460/478a1698-d7b2-442b-8cf4-ab18d16c2302)

But I think that's not practical for a few reasons:
- We're re-using the Issues backend here, which just fully deletes images. So changes to the backend preservation model could be complex
- We'd need to update other places in the ui (/issues page) to detect and support when an attachment exists/doesn't exist and update render to match
- It'll look weird if there were many attachments to start, and they're all deleted now

Instead my proposal is simpler, and while it would affect Issues as well, I think it's a beneficial change without the potential for downstream problems.

**Comment by cmanallen** [comment]
@aliu3ntry Can you look into this?
