### ISSUE TITLE
Profiles do not display when org is created in EU data center

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#68902]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create org and select EU as data center
2. send a transaction with a profile attached
3. Open transaction event, and click on View Profile in the upper right -

<img width="300" alt="Screenshot 2024-04-15 at 11 40 24 AM" src="https://github.com/getsentry/sentry/assets/96670625/f4200c30-e080-4200-b496-5830c39f2c0d">

4. Be brought to Profile page but with an error -

<img width="600" alt="Screenshot 2024-04-15 at 11 41 13 AM" src="https://github.com/getsentry/sentry/assets/96670625/8ae39407-29d9-4abd-800b-0948c6a5946c">

5. [See on Stats page that they show as Accepted](https://francisorgeu.sentry.io/stats/?dataCategory=profiles&project=4507091242319952&statsPeriod=14d)

[Direct Link to transaction in my org with a profile](https://francisorgeu.sentry.io/performance/python-fastapi-eu:1e7d7a88a3144fdba6a2acd3b0ef5611/?project=4507091242319952&query=http.method%3AGET&referrer=performance-transaction-summary&statsPeriod=14d&transaction=%2Ffunction&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)

I tested in node and python fastapi sdks.

Debug logging shows the profiles are being sent -

<img width="569" alt="Screenshot 2024-04-15 at 11 44 52 AM" src="https://github.com/getsentry/sentry/assets/96670625/31adc8af-baac-45b3-ba27-8126d1f46279">

### Expected Result

Profiles should show

### Actual Result

Profiles do not show even when sent properly

### Product Area

Profiling

### DSN
DSNs I used are -

`https://fc114ebe52a773a74dfc05be85ae461d@o4507091241009152.ingest.de.sentry.io/4507091242319952` 
`https://c459dffba139d37965593867ad28c4c4@o4507091241009152.ingest.de.sentry.io/4507091287146576`

**Comment by cleptric** [comment]
We're taking a look, thank you!

**Comment by cleptric** [comment]
This is now fixed!
