### ISSUE TITLE
Replace existing json usages with `orjson`

### ISSUE THREAD

**Issue by anonrig** [getsentry/sentry#68903]
We currently use `rapidjson` and default `json` library to parse/stringify JSON. The alternative library `orjson` is 6 times faster than `json` and 2-3 times faster than `rapidjson`.

We (me and @fpacifici) validated that simply replacing `rapidjson` with `orjson` results in 25% improvement (from 12ms to 9ms) on a particular task.

For example, here's graph to visualize the difference between `orjson` and `rapidjson`:

![Screenshot 2024-04-15 at 9 14 58 AM](https://github.com/getsentry/sentry/assets/1935246/b1e9d7d3-b734-4c99-a861-a81c418b6a1e)

## The drill

The drill is always this:
1. Pick up a consumer or a component or a class
2. Change the json implementation - surround it with a feature flag
3. Test - enabled feature flags
4. Rollout - usage without feature flags
5. Cleanup - removal of feature flags
6. Done

## Todos

- [ ] Removing all json and rapidjson usages
- [ ] Refactor [`sentry/utils/json.py`](https://github.com/getsentry/sentry/blob/5b88c7e9387903330a15ac5392c61f0e9c512ce9/src/sentry/utils/json.py#L4)

## Task list

| Component | Status | Author | Pull Request | Notes |
| --------- | ------ | ------ | ------------ | ----- |
| [Relay](https://github.com/getsentry/relay/blob/1d06dfbedee08528f0615f6264c01028f3c7c978/py/sentry_relay/processing.py#L206) | 4 | @anonrig | https://github.com/getsentry/sentry/pull/69613 | - |
| Indexer consumer | 6 | @anonrig | https://github.com/getsentry/sentry/pull/68802 | 20-25% overall reduction |
| Ingest processor | 6 | @anonrig | https://github.com/getsentry/sentry/pull/68811 | - |
| Snuba | 6 | @anonrig | https://github.com/getsentry/sentry/pull/68938 | - |
| Slack integration| 4 | @loewenheim | https://github.com/getsentry/sentry/pull/69409 | - |
| reconstruct messages | 4 | @ayirr7 | https://github.com/getsentry/sentry/pull/69378 | 50% reduction in JSON serialization and 25% reduction in average in all indexer payloads |
| outcomes_consumer | 2 | @vbro | https://github.com/getsentry/getsentry/pull/13779 | - |
| event_manager | 4 | @loewenheim | https://github.com/getsentry/sentry/pull/69653 | - |
| eventstore | 4 | @loewenheim | https://github.com/getsentry/sentry/pull/69653 | - |
| auth | 4 | @loewenheim | https://github.com/getsentry/sentry/pull/69653 | - |
| integrations | 4 | @loewenheim | https://github.com/getsentry/sentry/pull/69653 | - |
| backup | 4 | @loewenheim | https://github.com/getsentry/sentry/pull/69653 | - |

**Comment by JoshFerge** [comment]
is JSON parsing a significant cause of latency in our consumers or endpoints?

**Comment by anonrig** [comment]
> is JSON parsing a significant cause of latency in our consumers or endpoints? and would check sentry as you roll out, as with replays we noticed a bunch of errors associated with switching json implementations

@JoshFerge JSON parsing is a bottleneck in couple of places, and I think it has more impact than we assume it should have. Here's an example: https://sentry-st.sentry.io/performance/summary/?display=trend&end=2024-04-16T03%3A59%3A59&project=1513938&query=&referrer=performance-transaction-summary&start=2024-04-10T04%3A00%3A00&transaction=ingest_consumer.process_event&trendFunction=p95&unselectedSeries=p100%28%29%2Cavg%28%29

The only change done caused this improvement was due to rapidjson to orjson change.

<img width="907" alt="Screenshot 2024-04-15 at 8 29 50 PM" src="https://github.com/getsentry/sentry/assets/1935246/5b88c791-0407-4165-b397-17bf2eb87b26">

**Comment by ayirr7** [comment]
Here's an example of how this improved the time spent in one of the processing phases of the indexer: 

![](https://files.slack.com/files-pri/T024ZCV9U-F06VACF5230/screenshot_2024-04-22_at_11.51.24___am.png)

This is the phase where JSON deserialization is done.

**Comment by loewenheim** [comment]
One difference between `json` and `orjson` is that `orjson` dumps to `bytes`, not `str`. Decoding that back to a `str` might cost us some performance, let's see how it shakes out.

**Comment by anonrig** [comment]
> One difference between `json` and `orjson` is that `orjson` dumps to `bytes`, not `str`. Decoding that back to a `str` might cost us some performance, let's see how it shakes out.

@loewenheim Some functions such as Snuba ones take both bytes and str as parameters. We might not need to encode/decode in some places.

**Comment by TkTech** [comment]
In all of the cases where this change is being made, is the JSON fully parsed? If there are cases where the JSON is only parsed for a routing key for example, this can be sped up typically by another order of magnitude.

There are quite a few differences between how rapidjson and orjson parse JSON. This doesn't mean either is _wrong_, just that they might differ and introduce behaviour changes. A good place to start is to compare the two is:

- https://github.com/TkTech/json_benchmark/blob/main/minefield_reports/orjson.md
- https://github.com/TkTech/json_benchmark/blob/main/minefield_reports/rapidjson.md

Specifically, if you're depending on very-accurate float or integer parsing/serialization there will be quirks. For example with rapidjson you would have been ingesting Nan and +/-Infinity as valid numbers, but with orjson you no longer do.

**Comment by Narretz** [comment]
Why is the title of this issue "replace orjson with existing json usages"? It's the other way around, isn't it?

In the description it's fine"... simply replacing rapidjson with orjson results  ..."

**Comment by loewenheim** [comment]
Changed the title.

**Comment by anonrig** [comment]
Max duration of `reconstruct_messages.build_new_payload.json_step` has been impacted by this changes as well.

<img width="1333" alt="Screenshot 2024-05-07 at 9 38 36 AM" src="https://github.com/getsentry/sentry/assets/1935246/ebaf0c64-c10c-4ff4-8886-f3f27b21d848">

**Comment by anonrig** [comment]
After replacing middlewares and integrations to use `orjson`, here's the changes:

<img width="641" alt="Screenshot 2024-05-09 at 10 16 20 AM" src="https://github.com/getsentry/sentry/assets/1935246/02927bc8-cd2c-49a1-a165-d57664625b14">
