### ISSUE TITLE
don't showing transactions in discover menu

### ISSUE THREAD

**Issue by skelectlink** [getsentry/sentry#68957]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I can't see transactions in discover menu. I can't search transactions by tags.

### Expected Result

search transaction list in discover

### Actual Result

no transactions list in discover

### Product Area

Discover

### Link

https://electric-charger.sentry.io/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=6249858&query=&sort=-timestamp&statsPeriod=30d&yAxis=count%28%29

**Comment by k-fish** [comment]
Hey @skelectlink, we recently fixed a bug with the transactions list in discover, can you try again and confirm if it's still not working?

**Comment by skelectlink** [comment]
now working. thanks
