### ISSUE TITLE
Linear integration no working on EU 

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#68970]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a Sentry organisation in EU
2. Install the Linear integration 
3. Try to create an issue in Linear from any existing Sentry issue

Detail: the integration must be uninstalled from any US organisation before setting it up in the EU.

### Expected Result

The issue is created in Linear

### Actual Result

Internal server error: 
"error": "Error communicating with Sentry App service" 

([event link](https://sentry.sentry.io/performance/javascript:96c8b4d5ce4a4ae78919708f01469198/?legacy=1&node=error-96c8b4d5ce4a4ae78919708f01469198&statsPeriod=24h&timestamp=1713259863))

### Product Area

Settings - Integrations

### Link

https://ent-curumas.sentry.io/settings/sentry-apps/linear/

**Comment by Dhrumil-Sentry** [comment]
The team is investigating this and will update here

**Comment by Dhrumil-Sentry** [comment]
The Linear integration was built by the Linear team so we've reached out to them for help in debugging the problem, Apologies for the delay on this but we will get this resolved

**Comment by Dhrumil-Sentry** [comment]
The Linear team has confirmed they've made the changes needed to support our EU region. If this issue is still occurring after a couple of hours please let us know 🙏

**Comment by rodolfoBee** [comment]
It is working in my EU organisation. 
@mfn let us know if it continues for you.
