### ISSUE TITLE
Not receiving User Feedback in EU region

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#68980]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a Sentry org in the EU data region
2. Set up an app with the latest Sentry JS SDK (or JS framework)
3. Set up User Feedback either through [the widget](https://docs.sentry.io/platforms/javascript/guides/react/user-feedback/#user-feedback-widget) or through [the API](https://docs.sentry.io/platforms/javascript/guides/react/user-feedback/#user-feedback-api)
4. Run the app and send user feedback

### Expected Result

User feedback is received normally.

### Actual Result

User feedback is not received from either methods. If we switch to a DSN from an org in the US data region, it is received normally.

### Product Area

User Feedback

**Comment by bruno-garcia** [comment]
Thanks for letting us know! We're excited EU region is out but might have missed something to get User Feedback Beta available on it. it's timely since we plan to GA User Feedback this soon

**Comment by bruno-garcia** [comment]
Oh seems related to feature flags:
* https://github.com/getsentry/sentry-options-automator/pull/1140

**Comment by JoshFerge** [comment]
I've just confirmed that EU feedbacks now work on an EU org i just created. thank you for reporting this!
