### ISSUE TITLE
[User Feedback] bug: Internal Activity doesn't refresh after adding a message

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#68986]
Tried on this link: https://sentry.sentry.io/feedback/?feedbackSlug=javascript%3A5199287120%2F&project=1&statsPeriod=24h

The toast shows up:
> [Green check] Commented Posted 

But the message doesn't. Not until the page is reloaded.

**Comment by michellewzhang** [comment]
looking into this. it looks like optimistic updates aren't happening when the feedback isn't selected on the list. if you try with a selected feedback item the updates work without refresh

**Comment by bruno-garcia** [comment]
Seems to be working fine.

1. Tried when opening from the list. Worked
2. selected a different project (so list was empty). Still update worked
3. Hard refresh, still worked

![image](https://github.com/getsentry/sentry/assets/1633368/19315e07-e70c-4dbb-9a6b-b15a0c1dde9e)
