### ISSUE TITLE
400 Error When Using Absolute Date Filter on Replays Page 

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#69017]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1.) Navigate to Replays page https://yourorg.sentry.io/replays/ 
2.) Filter for an absolute date
3.) 400 Error occurs "Sorry, the list of replays could not be loaded. This could be due to invalid search parameters or an internal systems error."

<img width="548" alt="Screenshot 2024-04-16 at 11 26 32 AM" src="https://github.com/getsentry/sentry/assets/100724053/14e606fb-9972-4400-9d91-2ba1314ef06d">
<img width="795" alt="Screenshot 2024-04-16 at 11 26 45 AM" src="https://github.com/getsentry/sentry/assets/100724053/1b715459-f504-44f3-9f8a-80e6bbb3a7a9">
<img width="795" alt="Screenshot 2024-04-16 at 11 26 50 AM" src="https://github.com/getsentry/sentry/assets/100724053/7a58b5a2-25a1-45c1-8c33-d7bb9e84dce3">

I checked 4 different accounts to confirm that this is a consistent issue. 

### Expected Result

To successfully filter for an absolute date

### Actual Result

400 error occurs

### Product Area

Replays

**Comment by jas-kas** [comment]
Hey @ReneGreen27 👋 Thanks for reporting. Would you be able to share the org slug or exact repro steps?

I've filtered for absolute date on `sentry` org without any errors. Thank you!
