### ISSUE TITLE
Unify Email Subjects

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#6902]
With the introduction of the User Feedback emails, we now have 2 (3?) subjects in emails. Historically we kept an oddly generated alert subject template and had never gotten around to changing it, but at this point there's better solutions we could do from an experience POV.

Let's use this opportunity to overhaul subjects for the following:

- Alerts
- Workflow
- Digests

The subject we're using in feedback emails is:

```
{SHORT_ID} - {TITLE}
```

Where ``SHORT_ID`` is ZEUS-F1, and ``TITLE`` is 'New Feedback from USER'

See also https://github.com/getsentry/sentry/pull/6230

**Comment by lauryndbrown** [comment]
@dcramer for the sake of clarity, you are wanting emails for alerts, workflow, and digests to follow the same/similar pattern of the user feedback emails, correct?

**Comment by dcramer** [comment]
@lauryndbrown yep thats correct! Alerts probably still would be template based, but they should be based on the SHORT_ID pattern.

**Comment by lauryndbrown** [comment]
@dcramer I notice a common pattern in the subjects with events and groups emails is that the level tag is included in the format of level: title. I've kept that in there so far. Such that examples from test look like 'BAR-1 - ERROR: Foo bar' or 'BAR-1 - info: Foo bar'. Is that what you were looking for?

Also I noticed that some are based on templates. I don't yet know where to find those templates to change them to use the short_id. Do you know where those are stored, by chance? If not, I'll ask around.

**Comment by dcramer** [comment]
@lauryndbrown IMO I'd kill level as its less and less relevant.

The templates @tkaemming can probably help with as he's done some work there. I forget exactly where it's at, and where the default is, but we probably in that case should just 1) modify the default, 2) ensure SHORT_ID is available in the params
