### ISSUE TITLE
Enabling or disabling Reprocessing fails with "Unable to save your changes"

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry#6903]
Using sentry hosted on sentry.io

On the **Processing Issues** page:
`https://sentry.io/org/project/settings/processing-issues/`

Attempting to enable or disable Reprocessing results in the standard error:
`Unable to save your changes. Please ensure all fields are valid and try again.`

Looking in dev tools I can see:
`PUT https://sentry.io/api/0/projects/org/project/ 400 (BAD REQUEST)`

The response from the server is slightly more helpful:
```
{"detail": ["You do not have that feature enabled"]}
```

**Comment by mitsuhiko** [comment]
I think this might be because we do not have reprocessing enabled in sentry by default. Need to check that.

**Comment by dcramer** [comment]
@billyvg maybe you could look at this as part of the settings overhaul?

**Comment by mitsuhiko** [comment]
Should probably have updated this issue but this is a regression from recent changes. Will fix this.

**Comment by timfish** [comment]
Any update on this? 

I would like to disable re-processing as I don't have all the required symbols available but don't have that option.

**Comment by timfish** [comment]
Ah, it actually appears to have saved my setting change even though it displays the error.

**Comment by timfish** [comment]
This is now fixed

**Comment by kzlsk86** [comment]
I have the same bug< how can i fix it< i didn't saw a solution how it fixed?

**Comment by dcramer** [comment]
If this is happening on sentry.io please contact support. If its happening on a self-install you will need to identify the error and determine if its an issue in Sentry or an issue in your configuration.
