### ISSUE TITLE
Update issue assignee selector to use new components

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#69054]
The current assignee selector uses old components which are not consistent with the rest of the UI. This component should be rewritten to use `<CompactSelect />`.

The following behaviors should still work after the re-write:

- Should be able to search for and assign a user or team from the list
- Suggested assignees should be shown at the top of the list (codeowners and suspect commits)
- Suggested assignees should be shown as grayed out and dotted
- Can unassign an issue
- Can invite a new team member

This component should be rolled out with a new, short-lived feature flag.

Current:

![CleanShot 2024-04-16 at 14 54 12](https://github.com/getsentry/sentry/assets/10888943/97661929-f307-40ca-a63a-12dd2ed7e98e)

New:

![CleanShot 2024-04-16 at 14 51 56@2x](https://github.com/getsentry/sentry/assets/10888943/3c712902-5d19-4860-abfe-3fb9dd2fc083)

**Comment by MichaelSun48** [comment]
Issues Stream was updated with new design in #69639
I will close this task once Issue Details is also updated.
