### ISSUE TITLE
Bug in the filters and search in the "Issues" view

### ISSUE THREAD

**Issue by nirelbaz** [getsentry/sentry#69088]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to `https://equitybee.sentry.io/issues`
2. Filter by project, environment, time or use the search bar

### Expected Result

Result in table reload with the issues corresponding with the filter/search params (without requiring a complete window refresh)  

### Actual Result

Result in table reload with the issues that are **not** corresponding with the filter/search params and requiring a complete window refresh to see the correct result

https://github.com/getsentry/sentry/assets/9353959/708c7679-bc3e-4c79-9385-4c52af1a98d8

### Product Area

Issues

### Link

https://equitybee.sentry.io/issues

### DSN

https://acf5989337ae4195ad95aaeb59af2b3f@o204270.ingest.us.sentry.io/5353704

**Comment by lobsterkatie** [comment]
Hmmm... @nirelbaz, can you please try the same search, but without the `assigned_or_suggested` criterion? Since I am not you, that's one I can't test perfectly, but when I do the search without that, everything I get seems correct:

![image](https://github.com/getsentry/sentry/assets/14812505/3ee93941-324b-421a-a5ad-a76f049df9f0)

(There are only three issues in that screenshot, but I checked and all 160 issues are correct.)

They're all unassigned, so I can add in `is:unassigned` (which should be equivalent to the `none` part of `[me, my teams, none]`), and the same issues are retrieved:

![image](https://github.com/getsentry/sentry/assets/14812505/094b1067-6b80-47e6-9d3c-b564d0ed28aa)

If you're still seeing the wrong issues, can you please open up the network tab and let me know what we're sending in the request to `https://us.sentry.io/api/0/organizations/equitybee/issues/` which happens when you click 'enter' to submit a new search?

**Comment by nirelbaz** [comment]
I take it back, there is definitely something wrong with the `is:for_review` in combination with other filters/search query.
For example:
#### Any search for a `string` + `is:for_review` will require a refresh in order to see only the issue that have the `string` in their title

```
// Before refresh query to organizations/equitybee/issues/:
collapse: stats
collapse: unhandled
environment: production
expand: owners
expand: inbox
limit: 25
query: is%3Afor_review%20no%20privileges
savedSearch: 1
shortIdLookup: 1
sort: freq
statsPeriod: 7d
utc: true

- table footer shows: 1-50 of 160

// After refresh:
collapse: stats
collapse: unhandled
environment: production
expand: owners
expand: inbox
limit: 25
query: %20is%3Afor_review%20no%20privileges
savedSearch: 0
shortIdLookup: 1
sort: freq
statsPeriod: 7d
utc: true

- table footer shows: 1-25 of 160
```

#### Any env/project/timerange filter change will require refresh in order to influence the result if `is:for_review` is used

```
// Before refresh query to organizations/equitybee/issues/:
collapse: stats
collapse: unhandled
expand: owners
expand: inbox
limit: 25
project: 5353697
query: %20is%3Afor_review
savedSearch: 1
shortIdLookup: 1
statsPeriod: 7d
utc: true

- table footer shows: 1-26 of 2

// After refresh:
collapse: stats
collapse: unhandled
expand: owners
expand: inbox
limit: 25
project: 5353697
query: %20is%3Afor_review
savedSearch: 0
shortIdLookup: 1
statsPeriod: 7d
utc: true

- table footer shows: 1-2 of 2
```

**Comment by scefali** [comment]
@nirelbaz It seems like the only difference between the two queries is the `savedSearch` parameter, I think that might be related. Do you have a pinned search? If so, what is it?

**Comment by nirelbaz** [comment]
> @nirelbaz It seems like the only difference between the two queries is the `savedSearch` parameter, I think that might be related. Do you have a pinned search? If so, what is it?

@scefali thanks for the reply, I thought so too, but as you can see we have `savedSearch: 1` also in the query without the `is:for_review` filter and there it works as expected.

I cleared my saved search and tried again with same result:

```
// before refresh:
collapse: stats
collapse: unhandled
environment: production
expand: owners
expand: inbox
limit: 25
query: is%3Aunresolved%20is%3Afor_review%20required
savedSearch: 1
shortIdLookup: 1
statsPeriod: 90d
utc: true

- table footer: 1-25 of 1

// after:
collapse: stats
collapse: unhandled
environment: production
expand: owners
expand: inbox
limit: 25
query: is%3Aunresolved%20is%3Afor_review%20required
savedSearch: 0
shortIdLookup: 1
statsPeriod: 90d
utc: true

- table footer: 1-1 of 1
```

Before:
![equitybee sentry io_issues__environment=production query=is%3Aunresolved+is%3Afor_review+required referrer=issue-list statsPeriod=90d utc=true](https://github.com/getsentry/sentry/assets/9353959/399d9577-cf92-42dd-aad0-eb69bf8add55)

After:
![equitybee sentry io_issues__environment=production query=is%3Aunresolved+is%3Afor_review+required referrer=issue-list statsPeriod=90d utc=true (1)](https://github.com/getsentry/sentry/assets/9353959/98c9d4e4-517c-411e-92b1-9508389f6526)

**Comment by nirelbaz** [comment]
> @nirelbaz It seems like the only difference between the two queries is the `savedSearch` parameter, I think that might be related. Do you have a pinned search? If so, what is it?

@scefali thanks for the reply, I thought so too, but as you can see we have `savedSearch: 1` also in the query without the `is:for_review` filter and there it works as expected.

I cleared my saved search and tried again with same result:

```
// before refresh:
collapse: stats
collapse: unhandled
environment: production
expand: owners
expand: inbox
limit: 25
query: is%3Aunresolved%20is%3Afor_review%20required
savedSearch: 1
shortIdLookup: 1
statsPeriod: 90d
utc: true

- table footer: 1-25 of 1

// after:
collapse: stats
collapse: unhandled
environment: production
expand: owners
expand: inbox
limit: 25
query: is%3Aunresolved%20is%3Afor_review%20required
savedSearch: 0
shortIdLookup: 1
statsPeriod: 90d
utc: true

- table footer: 1-1 of 1
```

Before:
![equitybee sentry io_issues__environment](https://github.com/getsentry/sentry/assets/9353959/42447a6d-892e-4f18-ada6-9b127c6c1546)

After:
![equitybee sentry io_issues__environment=production query=is%3Aunresolved+is%3Afor_review+required referrer=issue-list statsPeriod=90d utc=true (1)](https://github.com/getsentry/sentry/assets/9353959/98c9d4e4-517c-411e-92b1-9508389f6526)

**Comment by scefali** [comment]
@nirelbaz Does that mean the same request is producing different results at different times? Because it seems to be the case if all the query parameters are the same. That is very strange. What happens when you go directly to the URLs in the browser?

**Comment by nirelbaz** [comment]
> @nirelbaz Does that mean the same request is producing different results at different times? Because it seems to be the case if all the query parameters are the same. That is very strange. What happens when you go directly to the URLs in the browser?

Going straight to the URL is the same as refresh the page. The difference is between using the UI dropdowns/search bar which don't produce the right result and refreshing the page/browsing to the URL which does

**Comment by jangjodi** [comment]
Hi @nirelbaz, I have tried to replicate this issue and unfortunately I am currently unable to.

Could you please:
1. View the network tab
2. Type your query in the search bar
3. Press enter in the search bar
  a. Confirm that the `https://us.sentry.io/api/0/organizations/equitybee/issues/` endpoint appears in the network tab with the expected query

I am curious to know what query is being sent to the endpoint.

**Comment by nirelbaz** [comment]
Hi @jangjodi,

From what I can see, the bug only appears when using the `is:for_review` filter. 
In the network tab I can see that `https://us.sentry.io/api/0/organizations/equitybee/issues/` is been called with the  expected query and even return the expected payload, but the table in the UI still show the previous results.

![Screenshot 2024-04-24 at 08 28 59](https://github.com/getsentry/sentry/assets/9353959/4a0d35d2-6fa6-4370-885f-be2e66015a9c)
![Screenshot 2024-04-24 at 08 28 10](https://github.com/getsentry/sentry/assets/9353959/31da7669-aedc-4117-972f-1a88605fc965)

**Comment by leeandher** [comment]
@nirelbaz Okay, so I was able to reproduce it! Thanks for the quick responses and being so helpful. 

It looks like there is an issue with the UI reflecting the query results on search when you have 'Real-time Updates' enabled. This feature hasn't been revisited in a quite some time, so it's likely something has become outdated. I will add this issue to our backlog to address, but for now I'd suggest pausing real-time updates to fix your search experience.

<img width="315" alt="image" src="https://github.com/getsentry/sentry/assets/35509934/cf1ec73f-0b3b-4343-8dd4-71908dee1b1f">

**Comment by nirelbaz** [comment]
@JLuse @scefali @leeandher confirming this is resolved. Thank you for all the help 🙏🏻
