### ISSUE TITLE
The Web Vitals subpanel in the Performance panel has no data

### ISSUE THREAD

**Issue by SouthLink** [getsentry/sentry#69082]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

I am using sentry self-hosted for web performance data and would like to use them for INP performance metrics:

Here is the version of the framework I am using:
next.js 14.0.0
react 18.0.0
"@sentry/nextjs":"^7.109.0",
"@sentry/react":"^7.109.0",
"@sentry/tracing": "^7.109.0",

sentry hosting platform : 24.3.0

I am using the above SDK to analyze the web performance data but found that the Web Vitals panel in the Performance panel has no data but the Performance panel is accepting the data just fine

Also, my SDK version was updated to 7.109.0, but no data was collected for INP metrics.

Here is my sentry configuration
```
// sentry.client.config

import * as Sentry from "@sentry/nextjs";

if (process.env.NODE_ENV === "production" || process.env.NEXT_PUBLIC_SERVER_ENV === "test") {
  Sentry.init({
    dsn: "https://xxxx@sentry.xxx.com/xxx",
    sampleRate: 0.2,
    tracesSampleRate: 0.1,
    profilesSampleRate: 0.3,
    environment: process.env.NODE_ENV,
    replaysSessionSampleRate: 0,
    replaysOnErrorSampleRate: 0.1,
    integrations: [
      // new Sentry.Replay(),
      new Sentry.browserTracingIntegration({
        beforeNavigate: (context) => {
          return {
            ...context,
            name: location.pathname
              .replace(/id=\d+/, "id=id")
              .replace(/\/\d+/g, "/:id")
              .replace(/\/tag\/.*/, "/tag/:id"),
          };
        },
        enableInp: true,
      }),
      new Sentry.Replay({
        maskAllText: false,
        maskAllInputs: false,
      }),
    ],
    initialScope: {
      tags: {
        upload_tag: "sentry-client",
      },
    },
  });
}

```

### Expected Result

The data in the Web Vitals panel can be displayed normally

### Actual Result

![image](https://github.com/getsentry/sentry/assets/17569488/7f7b4393-f912-458c-92c2-f545423faca1)
performance panel

![image](https://github.com/getsentry/sentry/assets/17569488/7d94626e-e6b2-457a-9fe5-2d4139b0a665)
Web Vitals panel

### Product Area

Performance - Web Vitals

### Version

24.3.0

**Comment by SouthLink** [comment]
Does anyone know how to solve this problem

**Comment by edwardgou-sentry** [comment]
Hi, can you try updating to the [7.114.0](https://github.com/getsentry/sentry-javascript/releases/tag/7.114.0) version of the sdk? There are some fixes in the newer versions that may help with capturing webvitals.

Also, can you check to see if any of the following webvitals are missing from your events?
`measurements.cls`
`measurements.lcp`
`measurements.fcp`
`measurements.ttfb`
The webvitals module may not show data if a combination of these webvitals are missing.

You should be able to check this in discover:
![image](https://github.com/getsentry/sentry/assets/83961295/7402064c-8b50-4ded-b36d-96eb194b8a49)

Let me know if you need further details, thanks!

**Comment by SouthLink** [comment]
> Hi @SouthLink , can you try updating to the [7.114.0](https://github.com/getsentry/sentry-javascript/releases/tag/7.114.0) version of the sdk? There are some fixes in the newer versions that may help with capturing webvitals.
> 
> Also, can you check to see if any of the following webvitals are missing from your events? `measurements.cls` `measurements.lcp` `measurements.fcp` `measurements.ttfb` The webvitals module may not show data if a combination of these webvitals are missing.
> 
> You should be able to check this in discover: ![image](https://private-user-images.githubusercontent.com/83961295/329628260-7402064c-8b50-4ded-b36d-96eb194b8a49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NTI3OTQsIm5iZiI6MTcxNTY1MjQ5NCwicGF0aCI6Ii84Mzk2MTI5NS8zMjk2MjgyNjAtNzQwMjA2NGMtOGI1MC00ZGVkLWIzNmQtOTZlYjE5NGI4YTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDAyMDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0M2MyN2E2MGM1OWZjOWUxMDEzMjVlNzFkZTM2N2IzNDIyYWE3YmFlNWQwYThiZDYyNGJiZTdlYmYzNmNhZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bGH3-YjU_g1F0SD82vDCNi3tR5CPApo0HA_9qPbKovk)
> 
> Let me know if you need further details, thanks!


Thank you for your reply. I have updated the SDK to the latest 7.114.0, but I am confused that I still don't know how to check the INP data, and the data of LCP and CLS is also very small, but the number of logs is very large.

![image](https://github.com/getsentry/sentry/assets/17569488/b4cb1076-39ac-42c3-83eb-950321cee375)

And I don't know how to view similar FCP and LCP data in performace panel, they seem to have a certain amount of logs.
![image](https://github.com/getsentry/sentry/assets/17569488/f7cf6a49-8cbb-4004-b5f3-8f95e3043c8c)

I tried a method to view performance metrics by selecting items from the Dashboards panel, and it seemed fine, but the performance and web vitals panel data showed very little performance data, so I was confused
![image](https://github.com/getsentry/sentry/assets/17569488/14fc98be-6ef0-4c99-b173-03be3812c2c0)

**Comment by edwardgou-sentry** [comment]
Hi @SouthLink , I don't see anything wrong with the sentry configuration you posted and seems like you've updated to a 
more recent version of the sdk. 

There's a couple of factors I can think of that might be causing you to not receive INP and other webvitals data:
- INPs only get triggered on `pagehide` events (ie when the user changes tabs). If your users don't trigger `pagehides`, this might affect the amount of INPs you're seeing.  
- Your `tracesSampleRate` is set to `0.1`. Not an issue by itself, but `tracesSampleRate` impacts the volume of INPs your website sends.
- Your webpage may not have any interactive elements and only navigations

A combination of these factors might be causing to not see any INPs.

If your site is publicly hosted, would you be able to send me a link to your webpage with Sentry instrumented so that I may do some further investigation on the cause?

**Comment by SouthLink** [comment]
> 你好@SouthLink，我没有发现您发布的哨兵配置有任何问题，并且似乎您已经更新到了 最新版本的 sdk。
> 
> 我认为有几个因素可能会导致您无法收到 INP 和其他 webvitals 数据：
> 
> * INP 仅在事件发生时触发`pagehide`（即当用户更改选项卡时）。如果您的用户不触发`pagehides`，这可能会影响您看到的 INP 数量。
> * 您的`tracesSampleRate`设置为`0.1`.本身不是问题，但`tracesSampleRate`会影响您网站发送的 INP 数量。
> * 您的网页可能没有任何交互元素，只有导航
> 
> 这些因素的结合可能会导致看不到任何 INP。
> 
> 如果您的网站是公开托管的，您能否向我发送一个带有 Sentry 检测的网页链接，以便我可以进一步调查原因？

Thank you for keeping an eye on my problems.

This is the [URL](https://c.8891.com.tw/m/) of our website. It can be confirmed that there are many interactive elements on the webpage. sentry is added to the code base, and web-vitals is also quoted to collect inp data on the page and report it to the self-built statistical program through onINP. I wonder if there is a conflict between the referenced web-vitals and sentry, whether this is possible.

**Comment by edwardgou-sentry** [comment]
Hi @SouthLink , thanks for sharing your webpage.

I viewed your page on a desktop browser and was able to trigger some INP events by clicking around, so I don't believe there is any configuration issue. 

I noticed your webpage is for mobile, which we do not fully support for all web vitals yet. If most your traffic is from mobile users, this would explain why you're not seeing any/limited INP data.

We have plans to add better mobile support in future updates

**Comment by SouthLink** [comment]
> 你好@SouthLink，感谢您分享您的网页。
> 
> 我在桌面浏览器上查看了您的页面，并且能够通过单击来触发一些 INP 事件，因此我不认为存在任何配置问题。
> 
> 我注意到您的网页适用于移动设备，但我们尚未完全支持所有 Web Vitals。如果您的大部分流量来自移动用户，这可以解释为什么您看不到任何/有限的 INP 数据。
> 
> 我们计划在未来的更新中添加更好的移动支持

Thank you and I will keep up with your updates
