### ISSUE TITLE
Unable to update issue priority for orgs on a dev and team plan

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#69120]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Navigate to an issue in an organization that is on a developer or team plan
2. attempt to change the issue's priority
3. observe the error "Unable to update issue priority" in the UI, and the browser's network tab on the endpoint that fails shows the error:
"You do not have the multi project stream feature enabled"
<img width="305" alt="Screenshot 2024-04-17 at 10 37 41 AM" src="https://github.com/getsentry/sentry/assets/99350819/03f61a3b-8566-4a37-82d2-3479dfd804f7">
<img width="1506" alt="Screenshot 2024-04-17 at 10 38 09 AM" src="https://github.com/getsentry/sentry/assets/99350819/371fb4cb-9d50-467e-8003-6e19b9c4412e">
<img width="1511" alt="Screenshot 2024-04-17 at 10 38 19 AM" src="https://github.com/getsentry/sentry/assets/99350819/34b922c3-5e3d-4188-95c9-a467259f8fb8">
<img width="1512" alt="Screenshot 2024-04-17 at 10 38 28 AM" src="https://github.com/getsentry/sentry/assets/99350819/be96b6dc-912c-48c2-9d67-4829c66ab821">

### Expected Result

Ability to change issue priority

### Actual Result

unable to update issue priority for orgs on a dev and team plan

### Product Area

Issues

### Link

https://test-org-7n.sentry.io/issues/5045468437/?project=4506870802415616&query=&referrer=issue-stream&statsPeriod=30d&stream_index=0

**Comment by malwilley** [comment]
Thanks for the report! This should be fixed now.
