### ISSUE TITLE
Alerts delayed for EU organisation. 

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#69178]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Crete an alert in an EU organisation
2. Trigger the alert.

### Expected Result

The alert message to be triggered within 1 or 2 minutes after the event. 

### Actual Result

Alert is triggered with a significant delay. On my local tests the delays were 13 and 7 minutes. Another user is reporting 2h up to 7th delays. More information on that in the linked Jira ticket (for PII reasons).

From my latest test, it is affecting the trigger "When a new issue is created", alerting on every event has no delay. 

### Product Area

Alerts

### Link

https://ent-curumas.sentry.io/alerts/rules/python/2384/details/

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2150) by [Unito](https://www.unito.io)

**Comment by leedongwei** [comment]
@mfn Thanks for the update! Please let us know if it regresses.
