### ISSUE TITLE
<unlabeled event> on all new issues

### ISSUE THREAD

**Issue by nirelbaz** [getsentry/sentry#69183]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Trigger an error

### Expected Result

New/existing Issue in Sentry will be label with a relevant name

### Actual Result

New/existing Issue in Sentry are labeled with "\<unlabeled event\>"

### Product Area

Issues

### Link

https://equitybee.sentry.io/issues

### DSN

https://acf5989337ae4195ad95aaeb59af2b3f@o204270.ingest.us.sentry.io/5353704

**Comment by liamjones** [comment]
Ditto here, happening for new events on existing issues too:

![image](https://github.com/getsentry/sentry/assets/521341/3fdc1db8-3c0e-41a1-9202-d525fe8cc637)

**Comment by liamjones** [comment]
They've also all started coming through in discover as 'default' events rather than errors (transactions seem unaffected)

![image](https://github.com/getsentry/sentry/assets/521341/b3f54998-0662-487b-b528-ddd567c3ea51)

**Comment by liamjones** [comment]
Incident exists for this now: https://status.sentry.io/incidents/2mdl8zwhp3by

**Comment by nirelbaz** [comment]
Seems like it was solve, thanks.
