### ISSUE TITLE
[Replay] Video seems to buffer until you move your mouse

### ISSUE THREAD

**Issue by c298lee** [getsentry/sentry#69203]
If you use the timeline to jump ahead to a part of the replay that requires buffering, the replay doesn't stop buffering until you move away from the timeline.

https://github.com/getsentry/sentry/assets/55311782/b3d490f9-41b4-4106-8dc8-2db6c6970b6f

**Comment by michellewzhang** [comment]
looks like the buffering message goes away as soon as you move your mouse, doesn't have to be away from the timeline

**Comment by c298lee** [comment]
seems fixed now!
