### ISSUE TITLE
Replay Clip Play/Pause Does Not Work as Expected (Scrubber doesn't move)

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#69209]
**Reported by Ryan:**

play/pause state for replay clips seemed messed up.

I’m looking at this one: <https://sentry-test.sentry.io/issues/5184646950/events/1b8522aefd4c418d9f6d7f5ea4307cd1/?project=4506072436572160>

When i click play inside issue-details the scrubber doesn’t move, the play/pause button reverts back to ‘play’ but i can see the mouse shooting around and the video does ‘work’

if i click into the scrubber it’s all working better, but the default experience of clicking the play button look broken 

[Slack Message](https://sentry.slack.com/archives/C04RDSY3ML1/p1713394381761069?thread_ts=1713394381.761069&cid=C04RDSY3ML1)

**Comment by ryan953** [comment]
This is related to the viewed-by replay project
- https://github.com/getsentry/team-replay/issues/19
- https://github.com/getsentry/sentry/issues/64924
