### ISSUE TITLE
[Replay Details - Breadcrumbs] Introduce new category `system` for mobile (orientation change, batter status change, etc.)

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry#69226]
- Title could be `System`
- Description:
  - We could either take it from `message` (where the SDKs would concatenate details about the breadcrumb into a string)
  - **Or we could take the json component from the breadcrumbs component and display the entire `data` field:**
 
![image](https://github.com/getsentry/sentry/assets/4999776/10cba6a6-267a-42d4-be58-f11650266c50)
 

---
We could also reuse the icon we have in the breadcrumbs component
![image](https://github.com/getsentry/sentry/assets/4999776/ff4f7e90-4440-4c33-9d20-466dd8af10dc)

**Comment by romtsn** [comment]
Let's send everything for now, and enable the Console tab for mobile (only internally), all "other" breadcrumbs will show up there. As we develop, we can decide which breadcrumb types are important enough to support properly in the Breadcrumbs tab (e.g. orientation change, battery status, etc.)

**Comment by michellewzhang** [comment]
@romtsn  let's go with this option: Or we could take the json component from the breadcrumbs component and display the entire data field:

**Comment by michellewzhang** [comment]
might want to add a property `is_mobile_native` to differentiate from web
