### ISSUE TITLE
[Replay Details - Breadcrumbs] Display `default` mobile breadcrumbs in the breadcrumbs tab if no console tab

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry#69230]
As of now the `default` breadcrumbs go into the Console tab (shown to internal only). 

We should decide later if we want to get rid of the console tab completely. If that's the case, the `default` breadcrumbs should go to the Breadcrumb tab instead.

there's no way for the SDKs to send breadcrumbs that are not falling under the known categories, e.g. logcat/timber messages, or manually captured breadcrumbs.

- Title could be `Default` or `Generic`
- Description should be taken from the `message` field
- Icon could be the same as for `Replay start`:
![image](https://github.com/getsentry/sentry/assets/4999776/450e19b3-0688-45a6-9789-8551adfafbf5)

**Comment by romtsn** [comment]
Let's send them, and enable the Console tab for mobile for now, the "other" breadcrumbs will show up there

**Comment by jas-kas** [comment]
Related to  https://github.com/getsentry/sentry/issues/71504
