### ISSUE TITLE
Display contexts with correct formatting 

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#69233]
Events from the .NET SDK (like [this](https://sentry.sentry.io/issues/5041230607/?project=1886021&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=7d&stream_index=5)) have some data being sent as bytes in integer format:

![image](https://github.com/getsentry/sentry/assets/1633368/1c9d3d49-ca6a-4078-acbd-b90c62a4b5f5)

In other parts of the protocol we're able to display it as 'KB, MB, GB etc".

What needs to be done on the SDK to get the data shown properly? 

That's happening here in the SDK:

https://github.com/getsentry/sentry-dotnet/blob/717aa7356a1f4bebf4b9379243c05f760b92d613/src/Sentry/Internal/MemoryInfo.cs#L8

https://github.com/getsentry/sentry-dotnet/blob/717aa7356a1f4bebf4b9379243c05f760b92d613/src/Sentry/Internal/MainSentryEventProcessor.cs#L165-L193

**Comment by bruno-garcia** [comment]
cc @rachrwang, a few years ago @matejminar added some formatting, IIRC we have something for other parts of the `context` part of the protocol like `Device.Memory`. So I'm hoping this could be an easy fix. 

I find it impossible to parse the data the way it looks right now.

**Comment by leeandher** [comment]
Fixed in https://github.com/getsentry/sentry/pull/80623, wrapped the values in `formatMemory`!

**Comment by bruno-garcia** [comment]
![Image](https://github.com/user-attachments/assets/787d2634-fc26-488a-a40c-f2ea35c6db39)

So nice to read! thank you @leeandher
