### ISSUE TITLE
[Replay Details - UI] Reflect pause/resume for mobile playback

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry#69249]
Because we pause/resume replay when an app goes foreground/background, we should reflect this somehow on the playback (e.g. gray out the video view and also the replay timeline part of it). We could do that based off of the breadcrumb that the SDKs send.

Currently these breadcrumbs have:
- `category`: `navigation`
- `data["state"]`: `foreground|background`

Open question: is this breadcrumb data sufficient or should we introduce a new category/type or add more data?

**Comment by michellewzhang** [comment]
- `ui.blur` & `ui.focus` exist for web replays but we don't display them. we could reuse these for mobile, they correlate to background & foreground
- would be helpful to show, visually, where there are "gaps" (which likely result from switching from foreground/background)
  - would require a large amount of refactoring wrt the scrubber (e.g. we'd probably want to disable clicking into a gap)
