### ISSUE TITLE
Fix Issue update flow to prevent redoing actions

### ISSUE THREAD

**Issue by ykamo001** [getsentry/sentry#69250]
When Issues are attempted to be updated, we should do a no-op if the action does not actually change anything. Look into [update_group](https://github.com/getsentry/sentry/blob/24.3.0/src/sentry/integrations/slack/webhooks/action.py#L96-L115) function and entry path where we call `update_groups` from sentry.api.helpers.group_index. This function currently allows a resolved issue to be resolved again, or an archived issue to be archived again, resulting in multiple of the same activity to be created in the activity model.

![Screenshot 2024-04-09 at 11 39 51 AM](https://github.com/getsentry/sentry/assets/5581484/1d0c31b6-54c8-4fa1-be91-a6b815be8699)

**Comment by mrduncan** [comment]
Added to the Core Product rotational backlog, we'll look into potentially resolving this as a part of upcoming work to the issue stream since it also seems to be one of the places allowing duplicate resolutions.

**Comment by ykamo001** [comment]
Related to: https://github.com/getsentry/sentry/issues/69252
