### ISSUE TITLE
[Replay Details - Breadcrumbs] Introduce new category `ui.lifecycle` for mobile

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry#69256]
**This is rather a discussion point.**

If we're sending all lifecycle events with the `navigation` category, it looks something like this (which is not pretty):
![image](https://github.com/getsentry/sentry/assets/4999776/3de8df4f-ba18-44a8-a14f-e569a685eacf)

There are multiple potential solutions to this:
- Only have one breadcrumb per screen (i.e. no lifecycle events, just one `navigation` breadcrumb when a screen is interactable/visible, meaning `Activity.onResume` or `ViewController.viewDidAppear`)
- OR introduce new category `ui.lifecycle` which will have lifecycle crumbs in addition to navigation crumbs. Perhaps we could make them collapsible under a parent `navigation` breadcrumb for a screen
- OR keep it as-is, as shown on the screenshot above

I'm personally leaning towards the first option here, meaning there's no work on the frontend side and we can just backlog it, and re-iterate after customers' feedback. The SDKs will do the filtering, and only send one `navigation` breadcrumb per screen navigation event.

**Comment by michellewzhang** [comment]
thoughts:
- we could have only one nav breadcrumb per screen
- potentially another `lifecycle` category, we like this idea: "Perhaps we could make them collapsible under a parent navigation breadcrumb for a screen"

**Comment by romtsn** [comment]
We've decided to drop excessive breadcrumbs and only report one navigation crumb per screen, so closing this for now, until we get feedback that this is not enough.
