### ISSUE TITLE
`Cannot read properties of undefined (reading 'id')` when switching to User Feedback from nav bar

### ISSUE THREAD

**Issue by jwjoel** [getsentry/sentry#69258]
### Self-Hosted Version

24.3.0

### CPU Architecture

x86_64

### Docker Version

25.0.5

### Docker Compose Version

3.8.0

### Steps to Reproduce

Switch user feedback to the left-side navigation. However, if I refresh the page, it's able to load normally, which seems to be due to no startPeriod being passed to the request

![Screenshot from 2024-04-17 09-23-13](https://github.com/getsentry/self-hosted/assets/25562443/d3b8ed24-8954-4f1b-b4b2-1477ba82994c)

### Expected Result

Show user feedback

### Actual Result

Got error: `Cannot read properties of undefined (reading 'id')`

![FireShot Capture 005 - TypeError — Discover — hyperhuman — internal — Sentry - sentry deemos dev](https://github.com/getsentry/self-hosted/assets/25562443/78c0ddae-6848-4807-b442-682afb5d96a7)

### Event ID

1d5a4d93b97f48e1bf1d72df495e2f90

**Comment by jas-kas** [comment]
Reported before here https://github.com/getsentry/sentry/issues/67412
