### ISSUE TITLE
Add ability to set up github enterprise integration over sentry API

### ISSUE THREAD

**Issue by nickmartin-factset** [getsentry/sentry#69309]
### Problem Statement

We have multiple organization on our github enterprise instance, and adding sentry integration on each organization is a manual process which involves a sentry-org owner needing to be temporarily added as an owner of their github organization and stepping through  the process documented at https://docs.sentry.io/product/integrations/source-code-mgmt/github/#install-your-github-app . It would be preferable if we could perform the registration action over the sentry API - we would then build an app which would empower our teams to self-service the sentry integration in their own organizations.

### Product Area

APIs

**Comment by Dhrumil-Sentry** [comment]
This is a valid ask, Adding this to our backlog. We will comment here once we have more details

**Comment by sentaur-athena** [comment]
Installations are multiple step pipelines requiring back and forth between github and sentry, there's no single API for this so I'll go ahead and close this.
Also user would still need the right permissions ob both sentry and github to be able to install so I don't think this actually makes the process easier.
