### ISSUE TITLE
Sentry.io fails to load queries

### ISSUE THREAD

**Issue by yashsway** [getsentry/sentry#69360]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Login and see any issues or do anything.

### How are you getting stuck?

![image](https://github.com/getsentry/sentry/assets/5233993/a9b82e8c-f662-4351-9702-be4ad57b22d5)

### Where in the product are you?

Issues

### Link

https://validere.sentry.io/

**Comment by jangjodi** [comment]
Hi [yashsway](https://github.com/yashsway), are you still experiencing this issue? It may have been related to a brief [outage](https://status.sentry.io/uptime) on 04/19/2024, as I cannot replicate this issue.

**Comment by yashsway** [comment]
@jangjodi not experiencing it anymore! It last a few hours the day I reported it and it was fine the next day.
