### ISSUE TITLE
GitHub Actions for Django migrations + Releases management

### ISSUE THREAD

**Issue by Prithvirajkumar** [getsentry/sentry#69361]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

A customer is looking guidance on the following:
1. [[actions/action-migrations](https://github.com/marketplace/actions/action-migrations)](https://github.com/marketplace/actions/action-migrations): is this action something they could leverage for their Django migrations as well? If so, could the Sentry team provide some examples of where this should run in CI?

2. [[actions/sentry-release](https://github.com/marketplace/actions/sentry-release)](https://github.com/marketplace/actions/sentry-release): The documentation suggested that it is best practice to notify the sentry of an upcoming release. Could the Sentry team clarify the usage of this action in the use case of a complete end-to-end CICD, deploying up the chain from `main` -> `release` ->`production` Currently, they run the following jobs in their deployment workflow once per environment.

Further details available on the corresponding case document. 

### How are you getting stuck?

Looking for guidance.

### Where in the product are you?

Settings - Integrations

**Comment by markstory** [comment]
> is this action something they could leverage for their Django migrations as well? If so, could the Sentry team provide some examples of where this should run in CI?

If they really want to. This github action is a component of how we build sentry though and isn't intended for customer consumption. As for an example of its usage, our [CI configuration](https://github.com/getsentry/sentry/blob/master/.github/workflows/migrations.yml) is the one and only example.
