### ISSUE TITLE
keeping the 'url' field visible after issue is assigned/archived via slack

### ISSUE THREAD

**Issue by sayag11** [getsentry/sentry#69373]
### Problem Statement

Hi,
We configured the slack integration with sentry to show the 'url' field so we can know which environment the error was thrown from. but when an issue is archived/assigned it's removed.

We want to show the 'url' field always, even after the issue is assigned/archived. can this be added?

attached relevant screenshots

Thanks, Yehonatan

### Solution Brainstorm

![url_hidden](https://github.com/getsentry/sentry/assets/13763174/3137bbe6-1e0a-4d44-a772-76c81e50e04e)

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
Thanks a lot for this very valid feedback. The tags should show up even after you take action on the issue. We will comment on this issue once this is available
