### ISSUE TITLE
Prevent suffix wildcard search as long as feature is not implemented

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#69387]
As described in https://github.com/getsentry/sentry/issues/65875, the Metrics API currently cannot deal with suffix wildcards (e.g. environment:prod-*). This leads to some weird graphs, because other APIs do support this:

![Image](https://github.com/getsentry/sentry/assets/6788060/ad2fac4e-4753-4a30-bf0f-dd34f5869666)

**Comment by ArthurKnaus** [comment]
As there will not be support for wildcard search in the short term, we decided to disable it on the FE.
