### ISSUE TITLE
Internal error when searching discover 

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#69380]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Discover
2. Search for events with a particular release

### Expected Result

Table and graph shows events for that release

### Actual Result

internal server error

[Link Internal issue. ](https://sentry.sentry.io/issues/5038883259/events/11ec51e487824294a0f07860ee421ab9/?project=11276&referrer=issue-list&statsPeriod=7d)

### Product Area

Discover

### Link

https://dev-curumas.sentry.io/discover/homepage/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=5499004&query=release%3Aelectron-sentry%401.0.0&sort=-timestamp&statsPeriod=30d&yAxis=count%28%29

**Comment by adamgsg** [comment]
We have started seeing this error as well when querying Discover.   A query that worked for us last week is no longer working this morning.  This query:

```
(environment:prod OR environment:prod2 OR environment:prod3) 
```
Now gives this error:

![image](https://github.com/getsentry/sentry/assets/23393447/7289b35b-a834-4c92-b5fa-93d3ede63077)

**Comment by charlesmchen-bc** [comment]
Same for us, we're seeing this on a number of dashboards.

**Comment by rodolfoBee** [comment]
The issue should be fixed now. Could no longer reproduce on Discord neither on Dashboards.
