### ISSUE TITLE
It looks like you've hit an issue in our client application. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

### ISSUE THREAD

**Issue by mshaermerx** [getsentry/sentry#69403]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

View issues

### How are you getting stuck?

It looks like you've hit an issue in our client application. Don't worry though! We use Sentry to monitor Sentry and it's likely we're already looking into this!

### Where in the product are you?

Issues

**Comment by dalnoki** [comment]
Hi @mshaermerx, thanks for reaching out, would you mind sharing a bit more detail on what you experienced, which URL you tried to visit and where exactly did you receive this message? Is the issue still ongoing? Thanks in advance for letting me know!
