### ISSUE TITLE
You can merge a single issue.

### ISSUE THREAD

**Issue by metaa** [getsentry/sentry#6949]
I'm on Sentry 8.22.0 (self hosted, Docker container).
I noticed I can merge one single issue with ... I don't know, itself?
![image](https://user-images.githubusercontent.com/5056880/34818669-c8cfbcbe-f6bb-11e7-9150-fe4d98e969a8.png)

It then disappears from the list and is visible again after a refresh of the page.

**Comment by lynnagara** [comment]
Hmm, thanks for pointing that out @metaa! I guess we should just disable the action in that case.
