### ISSUE TITLE
Slack Integration Problem

### ISSUE THREAD

**Issue by jhamer8** [getsentry/sentry#69576]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Trying to add slack workspace

### Expected Result

I'd imagine there should be an option to connect to slack.

### Actual Result

<img width="1158" alt="image" src="https://github.com/getsentry/sentry/assets/124536741/f8939ae4-882e-4d0b-96cd-8a3dbc8b98d6">

### Product Area

Alerts

**Comment by cathteng** [comment]
Just asking our support team to help get the org slug for us to investigate

**Comment by WuBruno** [comment]
Hey I am also getting the same issue

**Comment by dalnoki** [comment]
Hi @jhamer8 @WuBruno thanks for reaching out and we're honestly sorry that you are experiencing this! Would you mind sending your org slug to support@sentry.io so we can better assist here? Thanks in advance!
