### ISSUE TITLE
Simplified Filtering for Development Environments in Sentry

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry#69609]
### Problem Statement

Current filtering options in Sentry require manual configuration to effectively ignore error reports from development environments such as "localhost". A unified setting in the project setting UI to filter out all events originating from development setups would simplify this process significantly.

### Solution Brainstorm

filter out all events from common development addresses and environments.

### Product Area

Settings - Projects

**Comment by 0x33dm** [comment]
> ### Solution Brainstorm
> filter out all events from common development addresses and environments.


In our case if the environemnt is `development` we simply set Sentry's enabled flag, other environments are set to true.

I tempted to say this should be the default settings on Sentry, but then it would likely break backwards compatibility with other projects that might use it in development.

**Comment by Dhrumil-Sentry** [comment]
We already have inbound filters under Project settings, I don't understand how this would be any different ?

**Comment by MichaelSun48** [comment]
Closing this out due to >6 months of inactivity. Feel free to reopen if anyone has a similar issue and @Dhrumil-Sentry's suggestion doesn't work for you.
