### ISSUE TITLE
[Replay Canvas] Replay details & replay clip playback are wrong

### ISSUE THREAD

**Issue by michellewzhang** [getsentry/sentry#69634]
When you replay the clip, it's not the same as the intial playback:

https://github.com/getsentry/sentry/assets/56095982/d859ebbb-90cc-4a46-929f-233de4c4b99e

This also happens in the full replay details as well.

- Replay in the recording above is linked to [this issue](https://sentry.sentry.io/share/issue/bc178b5095354118ace5672364056f8a/)
- Seems to be a canvas issue? cc @billyvg

**Comment by billyvg** [comment]
So I checked a bunch of recent replays and it looks like it's playing fine. I then took a look at the linked issue and it's actually an exception being captured from the flamegraph code, so this could be correct and is what users are seeing.
