### ISSUE TITLE
Errors in metrics dashboards

### ISSUE THREAD

**Issue by obostjancic** [getsentry/sentry#69665]
Sometimes when I open this [dashboard](https://sentry.sentry.io/dashboard/77974/?project=1&statsPeriod=1h&utc=true) most of the widgets error out. Then I refresh and everything works. Can't reproduce right now, but wondering if anyone know what that's about.

**Comment by obostjancic** [comment]
I also encountered this multiple times, but have no good explanation for it.

**Comment by matejminar** [comment]
![Image](https://github.com/getsentry/sentry/assets/9060071/c977fa08-7995-485f-870b-0100d45cf522)
`429 Too Many Requests`
`"You are attempting to use this endpoint too frequently. Limit is 200 requests in 5 seconds"`
This page fired 44 requests - let's see how the 200 limit is configured.
