### ISSUE TITLE
Fast-forward inactivity checkbox does not work

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#69660]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to replay with periods of inactivity.
2. Play until there is a period of inactivity

<img width="300" alt="Screenshot 2024-04-25 at 9 15 36 AM" src="https://github.com/getsentry/sentry/assets/96670625/e84da16c-02db-47f0-951c-358398eba31d">

3. Click on the gear and uncheck `Fast-forward inactivity`
<img width="302" alt="Screenshot 2024-04-25 at 9 16 51 AM" src="https://github.com/getsentry/sentry/assets/96670625/5dbc0d4f-752a-4510-91d4-e60b45e2aad8">

4. See that the banner for "Fast forwarding through inactivity" is removed and the replay has stopped fast forwarding and seems to have worked.
5. Restart the replay, or go to next point of replay where there is inactivity
6. Banner comes back and replay starts fast forwarding again even though box is unchecked.

[Direct link to Replay in my org from the screenshots](https://francisorg.sentry.io/replays/289e60dd82c148e68d73f1ca3d01d28d/?project=-1&query=&referrer=%2Freplays%2F&statsPeriod=90d&yAxis=count%28%29)  (replay starts with inactivity)
 

### Expected Result

Checkbox should work permanently.

### Actual Result

Checkbox only works for the section when it is checked, and then behavior reverts to Fast forward.
<img width="1000" alt="Screenshot 2024-04-25 at 9 18 44 AM" src="https://github.com/getsentry/sentry/assets/96670625/0adf2a0f-b9d8-4b15-beec-aab6f112383c">

### Product Area

Replays

### Version

React 7.110

**Comment by bruno-garcia** [comment]
Thanks for letting us know, seems like the settings isn't persisting

**Comment by michellewzhang** [comment]
@bruno-garcia i was able to repro -- it happens when we seek in the timeline after unchecking 'fast forward'. looking into it now

**Comment by michellewzhang** [comment]
https://github.com/getsentry/sentry/pull/69713 this should hopefully fix it. thanks for reporting @Fwang36 !
