### ISSUE TITLE
How to group golang errors better

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#69678]
### Problem Statement

Feedback from a customer on [Discord](https://discord.com/channels/621778831602221064/1233087800291623015/1233087800291623015):

> Hello, Sentry folks. We use Sentry in a Go application, so nominal error types and stack traces are relatively rare. For instance, the errors coming from AWS calls are all of type *awserr.baseError and have no stack trace, grouping together lots of different kinds of errors. I have thought about creating an integration that will unpack the content from the errors. In the example of AWS errors, the "error code" string corresponds relatively well to error type, so I'd like to make it so that Sentry uses that for issue grouping. I could use that information to add a fingerprint the event in the go-sentry SDK client, which would be pretty straightforward. The problem is this: If there is an error chain (multiple "exception" values in the event) or a stack trace, I'd like to continue to use those for grouping, but also use the information from within the AWS error.
> 
> Is there a pattern for adding additional grouping information like this other than fingerprinting? Or is it possible to use both fingerprint and stack trace to group issues?
> 
> An approach that I had considered was rewriting the "type" of the error from *awserr.baseError to something like AWS Error (<code>), which I think would work, but seems like an abuse.

### Product Area

Issues

**Comment by Dhrumil-Sentry** [comment]
Chatted with the team about this, this is not possible to do today, We're adding this to our backlog in the event we work on making this more flexible

**Comment by j3h** [comment]
Is there a recommended workaround?

**Comment by lobsterkatie** [comment]
With all due respect, @Dhrumil-Sentry , if I'm understanding the question correctly, I don't think that's true. You can use the special `{{ default }}` value as part of your fingerprint (as shown [here](https://docs.sentry.io/platforms/go/usage/sdk-fingerprinting/#group-errors-with-greater-granularity)) and it will take into account both the stuff it would automatically and whatever else you give it.

**Comment by j3h** [comment]
@lobsterkatie Thank you!  That's exactly what I want, and I managed to miss that in the documentation!

Knowing that (a) the default grouping mechanism works by generating a fingerprint and (b) you can decide whether or not to include that fingerprint gives me a very clean way to accomplish what I want.

**Comment by lobsterkatie** [comment]
Great, glad we were able to get things sorted!

Cheers!
