### ISSUE TITLE
[Alerts] "Issue is more than x times in y minutes" WHEN condition does not maintain value in UI

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#69692]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Description:
If you create an alert using the WHEN "issue is more than X times in Y minutes" then save, by the next time you revisit that alert the UI does not have the value saved. This appears to be strictly a UI issues when editing the alert.

Steps to reproduce:
1. Create issue alert -> add WHEN "issue is more than 0 in 5 minutes":
![Screenshot 2024-04-25 at 12 00 51 PM](https://github.com/getsentry/sentry/assets/8451987/f1e2a342-93d1-42e0-b5fe-5b402adde4f1)
2. Save the alert
3. Edit alert -> view WHEN condition:
![Screenshot 2024-04-25 at 12 02 00 PM](https://github.com/getsentry/sentry/assets/8451987/a9c45778-cbdc-4857-ba22-c48f0fab68e3)

### Expected Result

Issue quantity value to remain the same

### Actual Result

Issue defaults to 100 in edit mode

### Product Area

Alerts

**Comment by ceorourke** [comment]
I was able to reproduce this - thanks

**Comment by ceorourke** [comment]
I can no longer reproduce this - I believe @mifu67 fixed it recently.
