### ISSUE TITLE
Issues Stream: Update assignee selector to use new design

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#69827]
After the work in https://github.com/getsentry/sentry/issues/69054 we will have a new assignee selector that looks similar to the old one but with a new dropdown component.

The next step will be to update the trigger to match the new pill design, as pictured below. The component should receive a prop that will either display the trigger with or without text. For the first iteration, we will not display the assignee text on the issue stream.

![CleanShot 2024-04-26 at 15 59 36](https://github.com/getsentry/sentry/assets/10888943/0f310c3a-9549-4086-a50e-3cefa647de06)

**Comment by MichaelSun48** [comment]
Completed in #70991
