### ISSUE TITLE
Mohammed albanna

### ISSUE THREAD

**Issue by rockmaster6** [getsentry/sentry#69838]
import Sentry

SentrySDK.start { options in
    options.dsn = "https://1ccc79572a2c4c99a6caec6cf4dc8576@o4504052354711552.ingest.us.sentry.io/4504052364279810"

    // Example uniform sample rate: capture 100% of transactions
    // In Production you will probably want a smaller number such as 0.5 for 50%
    options.tracesSampleRate = 1.0

    // OR if you prefer, determine traces sample rate based on the
    // sampling context
    options.tracesSampler = { context in
         // Don't miss any transactions for VIP users
        if context?["vip"] as? Bool == true {
            return 1.0
        } else {
            return 0.25 // 25% for everything else
        }
    }
}

**Comment by ReneGreen27** [comment]
Hello @rockmaster6! Thanks for opening a Github issue with us; can you please provide further context as to what behavior is occurring that is unexpected, what you would expect and in what part of our product so I can best direct your request for review?
