### ISSUE TITLE
Issues Stream: Backfill cron ID in the metadata for existing cron issues

### ISSUE THREAD

**Issue by malwilley** [getsentry/sentry#69835]
After we start recording the cron ID in the issue metadata (https://github.com/getsentry/sentry/issues/69826), we will need to add migration which backfills them into the existing set of issues.

**Comment by wedamija** [comment]
@malwilley Is this still planned?

**Comment by malwilley** [comment]
We never ended up executing on this project, good to close and can reopen if we get to this at some point
