### ISSUE TITLE
GitHub Integration installation failed when name contains `'` (single quote)

### ISSUE THREAD

**Issue by aldy505** [getsentry/sentry#69837]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Create a GitHub App named `Something's New`, then install it.

### Expected Result

Installation successful, we're redirected to `https://github.com/apps/something-s-new`

### Actual Result

Instead, we're redirected into `https://github.com/apps/somethings-new`

The app in question: https://github.com/apps/teknologi-umum-s-sentry

### Product Area

Settings - Integrations

### Version

24.4.1

**Comment by aldy505** [comment]
The code for the URL slug creation is here:

https://github.com/getsentry/sentry/blob/163b8b81f2cce24fa023ed4453f8c3b521ea6ff3/src/sentry/integrations/github/integration.py#L444-L445

I suppose we have 2 options moving forward:
- Let the users provide their own github app url
- Repair the `slugify()` function to generate correct url

**Comment by scefali** [comment]
@aldy505 I guess you're saying Github uses a slightly different slugify implementation than us. We use the built in Django one but we could potentially add a wrapper around it for Github for this special case. That being said, it seems like there is a workaround of just renaming the app to get rid of the `'` in the name, no?

**Comment by aldy505** [comment]
> @aldy505 I guess you're saying Github uses a slightly different slugify implementation than us. We use the built in Django one but we could potentially add a wrapper around it for Github for this special case.

Yes. 

> That being said, it seems like there is a workaround of just renaming the app to get rid of the `'` in the name, no?

No, I don't think that's a viable solution for everyone. Perhaps the easiest solution would be specifying our own Github App URL. If the Github App URL doesn't exists, we'll use the slugify function.

**Comment by scefali** [comment]
@aldy505 what if you changed the name in your `github-app.name` option to the actual slug you expect? I am pretty sure that would work.

**Comment by aldy505** [comment]
Maybe that will work, since only found 3 occurrences of `github-app.name` on the repo. We still need to add this to the docs though.

**Comment by aldy505** [comment]
Hey @scefali, can you take a look over this one please? https://github.com/getsentry/develop/pull/1268
