### ISSUE TITLE
Integration issues with Self-Hosted GitLab on Sentry EU servers

### ISSUE THREAD

**Issue by Kuppit** [getsentry/sentry#69858]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Navigate to the Sentry integration settings and start the process to integrate a self-hosted GitLab instance.
2. Complete the authentication and setup process in GitLab, which redirects back to Sentry.
3. Notice the prolonged time taken for the redirection from GitLab to Sentry.
4. Attempt to add repositories in Sentry by accessing the list of repositories through the API endpoint.

### Expected Result

- The integration setup should complete swiftly without prolonged delays.
- Once authenticated and set up, the list of GitLab repositories should be retrieved successfully without errors.
- Users should be able to add repositories smoothly, similar to the experience on Sentry's US servers.

### Actual Result

- The redirection from GitLab to Sentry is significantly delayed.
- The API call to retrieve the list of repositories (URL: https://sentry.io/api/0/organizations/quarks-eu/integrations/231940/repos/) results in an "upstream request timeout" error.
- Unlike the previous experience on Sentry's US servers, repositories cannot be added due to the error.

### Additional Information:

- This issue is occurring on the Sentry EU servers.
- Previously configured on Sentry US servers without these issues.
- GitLab version: 16.11

### Product Area

Settings - Integrations

### Link

https://quarks-eu.sentry.io/settings/integrations/gitlab/231940/

### DSN

https://o4507055433842688.ingest.de.sentry.io/

**Comment by leedongwei** [comment]
Thanks for the report! We'll get the team to take a look.

**Comment by maikelvl** [comment]
We, as paying customer, also have this issue.

It seems related to #71080. We also use Sentry EU, but connecting to GitLab.com.

/cc @Kobby-Bawuah

**Comment by sentaur-athena** [comment]
The add repository button is trying to fetch all the repos. We changed that to fetch only the ones you query with so this issue should be resolved now.

**Comment by maikelvl** [comment]
It's fixed. Thanks for the quick response!
