### ISSUE TITLE
New user Feedback UI is both extremely slow and inconsistent    

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry#70003]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Create a feedback using the [user feedback API](https://docs.sentry.io/platforms/javascript/user-feedback/#user-feedback-api)](https://docs.sentry.io/platforms/javascript/user-feedback/#user-feedback-api)

If you look in the new sentry UI window, the feedback comes in extremely slow and also if you throw multiple Feedback issues, only 1 seems to comes in.  

### Expected Result

All feedbacks comes in and Fast

### Actual Result

See Steps to Reproduce above

### Product Area

User Feedback

**Comment by bruno-garcia** [comment]
> If you look in the new sentry UI window, the feedback comes in extremely slow and also if you throw multiple Feedback issues, only 1 seems to comes in.

This is referring only to ingestion? Like from the moment the feedback is sent by the client to the point it shows up in the UI?

I have questions:
1. Could you please expand by what slow means? Is it 30 seconds? 1 minute? 10 minutes?
2. What SDK version is being used?
3. Are you using the [Widget](https://docs.sentry.io/platforms/javascript/user-feedback/#user-feedback-widget), the [Crash Report Modal](https://docs.sentry.io/platforms/javascript/user-feedback/#crash-report-modal), or the [API in the SDK `captureUserFeedback`](https://docs.sentry.io/platforms/javascript/user-feedback/#user-feedback-api)?
4. Is it using screenshots? (only available in our v8 beta at this time)
5. When you say multiple, how is that being tested? Clicking on the widget many times in a row on the same device? different devices? How many were sent in what time frame?

Note we don't expect the same person to send many feedbacks quickly, if that's happening it's probably spam. That said we're not actively rate limiting until it's a relatively high volume (@aliu3ntry do you know the exact amount?)

**Comment by aliu3ntry** [comment]
@bruno-garcia Unless we're doing it for the current/old infra, we are not rate limiting as far as I know.

**Comment by aliu3ntry** [comment]
I think by "user feedback API", Kobby means he's using `captureUserFeedback`, right? This is ingested differently from widget/crash report.. relates to what Josh is working on https://github.com/getsentry/sentry/pull/70117

**Comment by bruno-garcia** [comment]
> I think by "user feedback API", Kobby means he's using captureUserFeedback, right? This is ingested differently from widget/crash report, and relates to what Josh is working on https://github.com/getsentry/sentry/pull/70117

@Kobby-Bawuah could you please clarify?
