### ISSUE TITLE
issue.complexity to gauge how difficult an issue would be to fix/address

### ISSUE THREAD

**Issue by ndmanvar** [getsentry/sentry#70002]
### Problem Statement

I want to understand which issues may be easy to fix / less complex.

Goal: if (`issue.priority`===high and `issue.complexity`===low), then let's have a jr-dev fix it (as its "low-hanging-fruit")

### Product Area

Issues

**Comment by JoshFerge** [comment]
We've made a lot of progress with AI root cause analysis / autofix, which more or less satisfies the underlying requirement (help me understand if this issue is easy to fix).

Feel free to comment/reopen if you think the approach we've taken is still lacking!
