### ISSUE TITLE
User feedback issue integration tooltip triggers too often

### ISSUE THREAD

**Issue by c298lee** [getsentry/sentry#70016]
Once you trigger an integration tooltip once, the tooltip triggers again any time you hover where the **tooltip** was instead of the integration. This makes it impossible to click on anything behind where the tooltip once was and can make it impossible to assign or close an issue integration. The tooltip animation makes the tooltip almost transparent while it's animating out, which makes it seem like the tooltip is gone when it isn't, and hovering over will bring the tooltip back again.

Note: this issue is tooltip related, not user feedback specific. This behavior happens across other tooltips on the product too. The user can trigger it too fast because the animation hasn’t finished and it’s still animating out.

https://github.com/getsentry/sentry/assets/55311782/06fd4643-6303-44ad-9347-7b6e14be64ed

<img width="880" alt="image" src="https://github.com/getsentry/sentry/assets/55311782/5cb073eb-8625-4805-8ef0-e0bfd1665f16">

**Comment by michellewzhang** [comment]
updated the description to note that the issue is tooltip-specific rather than uf-specific, but we can keep the ticket in case we want to make a workaround for uf

**Comment by evanpurkhiser** [comment]
Fix was here https://github.com/getsentry/sentry/pull/71057
