### ISSUE TITLE
Shortcut to _Early Adopter_ takes me to the wrong page in settings

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#70043]
Using CMD+K and _Early Adopter_ I see the option. 
![image](https://github.com/getsentry/sentry/assets/1633368/3e4e346f-9d4a-4f0d-bdd7-47ab9b9d7ab3)

Selecting it though takes me to: `https://bruno-test.sentry.io/settings/#isEarlyAdopter`

Which is the wrong place:
![image](https://github.com/getsentry/sentry/assets/1633368/90036fd0-0a40-4b48-8ba3-ab3690493a75)

**Comment by michellewzhang** [comment]
this doesn't seem to be specific to the `Early Adopter` shortcut. happens for many other shortcuts & search results in settings as well
