### ISSUE TITLE
[User Feedback]: Alert not triggered for "crash report" Feedback API using an SDK

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#70041]
I was validating this user report: https://github.com/getsentry/sentry/issues/5055#issuecomment-2082085673 by [turning on alerting](https://bruno-test.sentry.io/settings/projects/dotnet-aspnet/user-feedback/#sentry%3Afeedback_user_report_notifications) on this test org and firing a new issue and feedback

![image](https://github.com/getsentry/sentry/assets/1633368/0e261ae0-dbbd-4de5-b9ab-c309e357b5c7)

```
var id = SentrySdk.CaptureMessage("test 4");
SentrySdk.CaptureUserFeedback(id, "test 4","test 4");
```

I confirm new issue alert is working, and I received an email for that:
![image](https://github.com/getsentry/sentry/assets/1633368/1d63bb08-f2e9-47b3-9af3-85a7051d3251)

I also enabled EA for this org, since UF is Beta I wasn't sure we gated any feature by EA-orgs only.

**Comment by jas-kas** [comment]
cc/ @JoshFerge @rodolfoBee

**Comment by bruno-garcia** [comment]
Oh, could it be the EA flag is cached on Relay and only updates after 1 hour? And I didn't wait long enough?

Just a thought here to help folks debugging ^

**Comment by bruno-garcia** [comment]
Fixes are live, I tested and validated it! 🚀

**Comment by rodolfoBee** [comment]
Is it already live? My organisation has EA enabled but I do not see the option: https://dev-curumas.sentry.io/settings/projects/notjava/user-feedback-processing/

**Comment by rodolfoBee** [comment]
Why there is two user feedback options in the menu?

**Comment by jas-kas** [comment]
@rodolfoBee Let me speak to the team -- we will try to consolidate. I think they're separate at the moment bc some represent Processing and the others are part of SDK Set Up :/ It makes for a worse UX though

https://sentry.slack.com/archives/C05J714QPRR/p1715181664051439

**Comment by jas-kas** [comment]
@rodolfoBee We're fixing it -- https://github.com/getsentry/sentry/issues/70663 tracking here
