### ISSUE TITLE
Replace our usage of `react-inspector` in Replay with component used in Issue Details

### ISSUE THREAD

**Issue by billyvg** [getsentry/sentry#70042]
When we first worked on Replay, we did not have a component to do pretty rendering of objects for our Console and Breadcrumbs. However, it looks like we now have one available that is currently in use in our Issue Breadcrumbs:

![Image](https://github.com/getsentry/sentry/assets/79684/73c07d24-3810-4bc8-a33c-9ad0d24ae24d)

Let's look into using this so that we have one less dependency!

**Comment by ryan953** [comment]
Replay currently uses `<ObjectInspector>`

Issues has https://sentry.sentry.io/stories/?name=app/components/structuredEventData/index.stories.tsx

You can see them both side-by-side (with the same data even!) here https://sentry.sentry.io/stories/?name=app/utils/useOrganization.stories.tsx

**Comment by michellewzhang** [comment]
note: i finished one half of this ticket. other half requires some non-trivial refactoring work with remembering expansion state, which the current `StructuredEventData` component does not have, so i'll leave it open for the future, for anyone who wants to tackle it.

DONE:
- [x] replace component in network panel

TODO:
- [ ] replace component in breadcrumbs panel
- [ ] replace component in console panel

https://github.com/getsentry/sentry/pull/74238 is a half-working PR that might give some inspiration about how to implement the expansion state functionality -- basically we need to do something similar to `ObjectInspector` which passes in `onExpand` and `expandPaths`, which give the component information about how to re-calculate row height when the component is expanded/collapsed, and info that helps remember the expansion state when re-rendered.

**Comment by michellewzhang** [comment]
@c298lee are the instances fully replaced within the breadcrumbs tab? :D

**Comment by c298lee** [comment]
@michellewzhang yes! just the console panel left
