### ISSUE TITLE
UI support for security reports.

### ISSUE THREAD

**Issue by alex-hofsteede** [getsentry/sentry#7005]
Per #5133 there is now a new API endpoint which can be the `report-uri` for all security report types.

 ```/api/$project_id/security/```

This accepts `CSP`, `Expect-CT`, and `Expect-Staple` security violation reports. (HPKP was removed).  `/api/$project_id/csp/` still works but should be deprecated eventually.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expect-CT and https://github.com/ScottHelme/draft-helme-expect-staple/blob/master/draft-helme-expect-staple.md describe the setting of report-uri for these reports.

We also need to define the display of these new interfaces similar to https://github.com/getsentry/sentry/blob/master/src/sentry/static/sentry/app/components/events/interfaces/csp.jsx

**Comment by dcramer** [comment]
@getsentry/workflow hi frendz does someone want to volunteer to help overhaul the "CSP Settings" to expand it to talk about how to send these other security reports?

**Comment by dcramer** [comment]
tbh i may build this this weekend/after i finish other things if no one grabs it
