### ISSUE TITLE
[User Feedback] Feedback only showing on the old Feedback page (org is EA)

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#70050]
Feedback captured via the SDK `CaptureUserFeedback` API passing `event_id`
Org is set [to EA](https://bruno-test.sentry.io/settings/organization/) and some of the feedbacks were sent while it was EA (but not all).

But still, [no feedback shows on the new UI](https://bruno-test.sentry.io/feedback/?project=4505865338617856&statsPeriod=7d):
![image](https://github.com/getsentry/sentry/assets/1633368/34d3acf9-7931-4687-a18b-e6513ecc4a25)

They all [show on the old UI](https://bruno-test.sentry.io/user-feedback/?project=4505865338617856&statsPeriod=7d)
![image](https://github.com/getsentry/sentry/assets/1633368/5d3ef112-7b8a-4e2c-8af8-cd7111289df9)

**Comment by jas-kas** [comment]
cc/ @JoshFerge

**Comment by hamedfoodready** [comment]
I have the same issue.

**Comment by bruno-garcia** [comment]
Sorry about that @hamedfoodready , we're working on a fix!

**Comment by bruno-garcia** [comment]
![image](https://github.com/getsentry/sentry/assets/1633368/daa8e9d3-13a1-4e0f-970f-4c3332d4416b)

Resolved! thanks @JoshFerge
