### ISSUE TITLE
Document SCRIPT_NAME usage

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#701]
Its pretty common to host an install at foo.com/sentry, though we recommend a subdomain. let's document how to do this

**Comment by grjones** [comment]
+1

**Comment by alesdotio** [comment]
+1

**Comment by mattrobenolt** [comment]
This is sorta documented at https://docs.getsentry.com/on-premise/server/nginx/#hosting-sentry-at-a-subpath but pretty sure it doesn't fully work, and we don't support this method. We expect a full domain/subdomain.

If this changes in the future, we'll document it better.
