### ISSUE TITLE
Ephemeral Messages for Link Prompts in Discord

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#70112]
Feedback from customers:

unrelated: can you pass this along to whoever works on the discord bot, it would be nice if the messages were marked [ephemeral](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-interaction-callback-data-structure) so that they only appear to the current user, instead of sharing to all users. probably can be applied to every message in response to a user action.

![image](https://github.com/getsentry/sentry/assets/109983869/47b2b514-a400-49df-a16b-c8d3015d1275)

**Comment by paperdave** [comment]
<img width="947" alt="image" src="https://github.com/getsentry/sentry/assets/24465214/ac3bc433-9a79-4c37-858f-58867a3f2384">

in my opinion, all of the above messages should be marked ephemeral

**Comment by iamrajjoshi** [comment]
This issue was fixed in https://github.com/getsentry/sentry/pull/76197
