### ISSUE TITLE
Winden scope for Hydration Error Inbound Filter

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#70119]
### Problem Statement

Currently our hydration error inbound filter looks for the following ([source](https://github.com/getsentry/sentry/blob/8ac74352694af33add65799bb481a99a287ef10d/src/sentry/relay/config/__init__.py#L152)):
```python
error_messages += [
            "*https://reactjs.org/docs/error-decoder.html?invariant={418,419,422,423,425}*"
]
```
This does not account for messages such as the following:

> Minified React error #425; visit https://react.dev/errors/425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

### Solution Brainstorm

We should widen the scope of the filter to take into account cases such as the one described above.

### Product Area

Unknown

**Comment by roggenkemper** [comment]
thanks for the feature request, i've added this to our backlog to take a look at
