### ISSUE TITLE
Incorrect time zone for Kazakhstan

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#70126]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

- Go to user settings (https://sentry.io/settings/account/details/)
- Click "Select Timezone" input
- Search for Almaty
- <img width="488" alt="Screenshot 2024-05-02 at 13 17 24" src="https://github.com/getsentry/sentry/assets/25980868/f146984d-71e8-4292-937a-bef73d168c46">

### Expected Result

Almaty is now in the UTC + 5 time zone

https://www.timeanddate.com/news/time/kazakhstan-single-time-zone.html

### Actual Result

Almaty is still in the UTC + 6 time zone

### Product Area

Unknown

**Comment by roggenkemper** [comment]
Thanks for writing this in! I think these timezones are controlled by moment, but we can follow up to see if it has been updated and make sure ours are up to date
