### ISSUE TITLE
Multiple Issue Alerts in a single Slack Alert Thread

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#70135]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Set up Slack Integration
Construct Issue Alert with routing to a Slack Channel
Trigger an Issue Alert multiple times to send multiple alerts per a single issue

### Expected Result

New events that are grouped with an existing issue are being posted into a slack thread rather than to the main slack channel, resulting in poor visibility for recurring issues.

### Actual Result

It appears the logic of this change ([Slack Threads for Metric Alerts](https://sentry.io/changelog/slack-threads-for-metric-alerts/)) is applying to Issue Alerts unintentionally.

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
Thanks for this report - This was a feature released to Early Access customers only for feedback and we will update this so that the issue alerts always go to the channel

**Comment by ykamo001** [comment]
Fix is released
