### ISSUE TITLE
User Feedback from Unreal Crash Reporter through `CrashContext.runtime-xml` stopped working

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#70138]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I've seen several reports from users that about 14 days ago, User Feedbacks for events sent via the Unreal Crash Reporter has stopped appearing on their issues and their User Feedback page.  All reports so far have reported April 18th as the last day they have received the feedbacks.

As far as I can tell, we used to take the `UserDescription` field in the `CrashContext.runtime-xml` file sent to us and attach it as user feedback to the Sentry event.  The file still contains that field so I don't think it's an sdk issue.

Also the feedbacks received prior April 18th, are not visible in the New Feedback View.  They are only visible in the Old Feedback View.

### Expected Result

User Feedbacks using the Unreal Crash Reporter continue to work.

### Actual Result

They have stopped working.

### Product Area

User Feedback

**Comment by bruno-garcia** [comment]
> Also the feedbacks received prior April 18th, are not visible in the New Feedback View. They are only visible in the Old Feedback View.

This seems related to:
* https://github.com/getsentry/sentry/issues/70050

> As far as I can tell, we used to take the UserDescription field in the CrashContext.runtime-xml file sent to us and attach it as user feedback to the Sentry event. The file still contains that field so I don't think it's an sdk issue.

Seems like a dupe of:
* https://github.com/getsentry/sentry/issues/70041

During the EA of the new feedback feature, which GA's next week, we made some changes to the ingestion of feedbacks in order to bridge them from the old format to the new. This allows feedbacks to be alerted on:
* https://github.com/getsentry/sentry/issues/57772

@JoshFerge is doing some work to address this, linking some for reference:
* https://github.com/getsentry/sentry/pull/70200
* https://github.com/getsentry/sentry/pull/70198
* https://github.com/getsentry/sentry/pull/70197

**Comment by bruno-garcia** [comment]
Could you please try again? This related issue was resolved, I believe they are the same:

* https://github.com/getsentry/sentry/issues/70050

**Comment by Darkere** [comment]
Does not appear to be fixed. Though I'm not sure if this question was only for EA Repo's.

**Comment by MTSchuby** [comment]
Our company is experiencing the same issue.  The last feedback we can visibly see is as of April 17th.  The CrashContext.runtime-xml files list the feedback correctly under `<UserDescription>`, but they no longer appear in any of our events after the date mentioned above.

**Comment by JoshFerge** [comment]
Hello! is Feedback sent after ~Friday still missing?

**Comment by JoshFerge** [comment]
and if it is, could you please pass along your sentry org slug? (if you don't want to put it publicly on github, can email me at josh.ferge@sentry.io

**Comment by Darkere** [comment]
Still missing. New Feedback page is empty, and newest entry in old feedback is 19 days old. Slug: tml-edition-gmbh

**Comment by Fwang36** [comment]
I think the issue here might be a little different from the 2 other linked issues.

Yes, the existing user feedbacks only showed on the old user feedback view, but new ones are no longer created at all, whether we are looking at the new view or the old view.

I'm also not sure if these are handled differently on ingest, but I don't believe we are referring to the [User Feedback Api method](https://docs.sentry.io/platforms/unreal/user-feedback/#user-feedback-api) but are referring to the [Unreal Crash Reporter.](https://docs.sentry.io/platforms/unreal/configuration/setup-crashreporter/#ue-crash-reporter).  I don't think this Unreal specific method for user feedbacks via the crash reporter is documented in our docs, but I think it's [this section in Relay ](https://github.com/getsentry/relay/blob/0a7037e7c05f673d85bc7e8d44ca318fca33e61d/relay-server/src/utils/unreal.rs#L157)

**Comment by Darkere** [comment]
Seems to be fixed. Feedback is appearing in the Old Feedback page again.

**Comment by jas-kas** [comment]
@Fwang36 Do you think we can close out this ticket? LMK!

**Comment by Fwang36** [comment]
Yes, I think we can close this now.  If anyone else is having issues with this please write in to support@sentry.io and we'll take a look directly.

**Comment by MTSchuby** [comment]
@Fwang36 Email sent to support, thanks.
