### ISSUE TITLE
Set Loader Script Configuration Defaults

### ISSUE THREAD

**Issue by serglom21** [getsentry/sentry#70226]
### Problem Statement

Currently, it seems that new projects in Sentry automatically inherit the settings enabled for Performance Monitoring and Session Replay in the Loader Script options for a DSN. This might result in new projects inadvertently sending data that they might not want
 

### Solution Brainstorm

Be able to set Loader Script defaults for new projects (i.e Enable/Disable certain features by default upon project creation).

### Product Area

Projects - Project Creation

**Comment by matejminar** [comment]
Hey @serglom21, you can untick Replay or Performance when creating a new project with loader script:
![CleanShot 2024-05-06 at 12 54 05](https://github.com/getsentry/sentry/assets/9060071/41b49b05-99b7-45a4-901c-5832ff539c14)
Or did you have something else in mind?
