### ISSUE TITLE
[Milestone] Quality of Samples & Connection to Trace

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#70220]
### Problem ###
The current trace correlation experience brings up samples that are somewhat "random" or at least not the most useful. We have an opportunity to improve on:
- the quality/relevance of the samples we show
- the way they are visualised in the chart
- the way they are displayed in the table
- the connection of samples to different time-series (multiple queries or group by)

### Potential solutions ###
**Chart**:
- Have a good distribution of samples around the line, to have good coverage
- Display less samples (maximum 10-15, TBD), but ensure they are useful
  - Always cover the spike/dip case
  - if there’s an arrow, in span card  show +100% or x times bigger than average (to show how much of outlier it is)
- Have samples also for count and sum (just an even spread of samples), to ensure consistency
- Connect sample on chart with table on hover
- [strechy] Lo-fi preview trace

**Samples table:**
- Give users the ability to filter samples that are shown to them, keeping the same date range and bounds. Also give the possibility to choose the ordering in a user friendly way (e.g., slowest, fastest)
- Revise table columns or make them configurable
- Make hover cards the same on chart and samples table
- When you do max and min, sort also the table by default
- Samples roll-up to the trace or root-span 
- Improve the empty state of the samples table - CTA to enable tracing or troubleshoot
- Highlight specific samples (for example when coming from trace view)

**Trace view:**
- Have icon to span with metrics when you’re coming from metrics page

```[tasklist]
### Tasks
- [ ] https://github.com/getsentry/sentry/issues/71488
- [ ] https://github.com/getsentry/sentry/issues/71516
```

**Comment by ale-cota** [comment]
Jesse's analysis: https://www.notion.so/sentry/UX-Correlating-Samples-to-Metrics-a5e9b1ccba5f4c3983f19fde9cd5b19a
