### ISSUE TITLE
Integration with Redmine broken

### ISSUE THREAD

**Issue by valipod** [getsentry/sentry#7023]
On https://sentry.io it is not possible to add a Redmine integration, the configuration page has **Project**, **Tracker** and **Default Priority** as mandatory fields, but they are empty selects since the Host and API key have not been saved yet (or no AJAX call is performed to asynchronously fetch the data for these three selects).

This also applies to an already configured integration (end of November 2017 this was still working), **Project**, **Tracker** and **Default Priority** that were previously set are empty (the following screenshot is from such a configured integration)

![required](https://user-images.githubusercontent.com/1492705/35230899-fe7abcdc-ff9f-11e7-81fa-354ed5453a81.png)

**Comment by larrylampco** [comment]
Can confirm that this is still a problem. Tried integrating with Redmine 3.2.3. Saw the same erros.

**Comment by jorgemfm** [comment]
Having the same problem.

Thank you.

**Comment by blacksmith77** [comment]
Same problem here... redmine 3.4.4

**Comment by scaule** [comment]
+1

**Comment by lost4815162342** [comment]
Same problem

**Comment by rakshazi** [comment]
Same here, any updates?

**Comment by scaule** [comment]
Wow , thanks for this workaround. 
I gonna try that today :)

**Comment by MiniKeb** [comment]
This workaround works for configuring the plugin but you still can't use the redmine plugin.
When you try to update this configuration, or if you try to create a redmine issue from an error, it won't work.

**Comment by hugoseabra** [comment]
Is that a perspective of correting the integration with Redmine 3.4?

**Comment by atvirasvilnius** [comment]
For me also the same problem :(

**Comment by mstroeve** [comment]
Same problem hete with on premise version

**Comment by viciu** [comment]
Same problem here - Sentry 9.0.0, Redmine 3.3.8

**Comment by viciu** [comment]
@scefali could you please give a hint? I've seen you've been working on the plugin recently here #15894
