### ISSUE TITLE
[Issue Stream] Filter Issue Stream by count.

### ISSUE THREAD

**Issue by gid-sentry** [getsentry/sentry#70273]
### Problem Statement

1.  I want to ignore any issues that have happened fewer than let’s say 10 times. they’re just noise to me.

### Solution Brainstorm

Add a `count:>10` filter option in the issue stream.

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2167) by [Unito](https://www.unito.io)

**Comment by vartec** [comment]
@gid-sentry we do have `count` as `timesSeen`, however we don't have a way to do a _less than_ or _more than_ comparison right now. Not sure if we'd go route of supporting that or rather route of something like `countAtLeast` and `countAtMost`.

**Comment by gid-sentry** [comment]
Ah! Looks like `timesSeen:<500` does actually work in the issue stream, so maybe that's ok and we could close this issue?

**Comment by armenzg** [comment]
Sounds good! 👍🏻
