### ISSUE TITLE
[Design] Proactively Show Customers How They Can Change their Replay Identifier from IP Address

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#70276]
Today, many projects collect IP addresses and those are used to identify replay sessions unless `Sentry.setUser` is specified.

We want a way to indicate to customers how they can use a more friendly user-specific identification such as email, user name or user ID instead: https://docs.sentry.io/platforms/javascript/session-replay/configuration/#identifying-users

**Comment by Jesse-Box** [comment]
A simple solution would be to add another item to the "Configure Replay" dropdown
