### ISSUE TITLE
User Feedback: Replay shows 404 but linked error has replay

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#70308]
https://nugettrends.sentry.io/feedback/?feedbackSlug=spa%3A5308233113&notification_uuid=2d218c8b-8a09-4608-b87d-46eaf7b38e92&project=1266321&statsPeriod=14d

<img width="796" alt="image" src="https://github.com/getsentry/sentry/assets/1633368/1ee90a8f-4d22-4e8f-ba90-7f8829d207af">

But the error linked actually has a replay:

<img width="919" alt="image" src="https://github.com/getsentry/sentry/assets/1633368/bfc782ad-0579-41f3-a466-8807676c6fd5">

**Comment by bruno-garcia** [comment]
@michellewzhang I believe this is related to a change done last week?
Or perhaps @JoshFerge might know

**Comment by michellewzhang** [comment]
@bruno-garcia i believe this ticket is a duplicate of https://github.com/getsentry/sentry/issues/70206

**Comment by bruno-garcia** [comment]
Ah my bad, I knew it was familiar. Sorry about the noise
