### ISSUE TITLE
Slack alerts in threads: add option to enable or disable it

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#70316]
### Problem Statement

With the addition of Slack threads for metric alerts, when the same issue triggers an alert multiple times all messages are in the same thread. 

[Some users like this behaviour](https://sentry.zendesk.com/agent/tickets/120760), some want to [see all messages in the channel ](https://github.com/getsentry/sentry/issues/70135). 

[A recent change made ](https://github.com/getsentry/sentry/pull/70108)all messages to also be posted in the channel, not only in the thread. 

### Solution Brainstorm

Make this behaviour customisable:
By default send only to thread with the option to also send to channel, or vice-versa. 

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
This is a fair request and we're currently working on providing options so users can turn off any use of threads for issue or metric alerts
