### ISSUE TITLE
[User Feedback] Feedback widget is no longer collecting name or email

### ISSUE THREAD

**Issue by michellewzhang** [getsentry/sentry#70347]
Can see that all of the labels say "anonymous" (which means on the frontend we don't have access to a name or email to display):

<img width="837" alt="328232263-8b0ec5f6-b400-4c76-bc31-86f4c78bd1cf" src="https://github.com/getsentry/sentry/assets/187460/ab7f18ee-ddd1-461b-8ee4-aa2fcd30b402">

**Comment by c298lee** [comment]
This is happening because `getCurrentScope().getUser()` isn't returning anything. Waiting on Francesco for how to best access the scope to fix this.

**Comment by c298lee** [comment]
fixed with https://github.com/getsentry/sentry-javascript/pull/11928
