### ISSUE TITLE
Commits do not match the count

### ISSUE THREAD

**Issue by anapier70** [getsentry/sentry#70411]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

On the releases page the count on the commits tab does not match the number of commits actually shown on the commits tab. The same applied to the files tab, count in the tab header does not match how many files get shown.

This is counting using all available pages so we have went to the next page, but for example on our latest release we have a count of 61 files and only 27 listed out individually

### Expected Result

number of commits should match the number of commits shown

### Actual Result

![image](https://github.com/getsentry/sentry/assets/164612005/31487c99-9adb-4dc2-a90f-81fb4335f39d)

### Product Area

Releases

### Link

https://innovid-xp.sentry.io/releases/jobqueue%40measrelease.20240506/commits/?environment=prod&environment=produsa&project=4506575222800384

### DSN

https://innovid-xp.sentry.io/projects/jobqueue/?project=4506575222800384

**Comment by schew2381** [comment]
Hi thanks for the bug report, I'm looking into this and it appears the problem lies with how we display the commits rather than the commit count.

I'll post future updates on this ticket as I keep exploring

**Comment by schew2381** [comment]
@anapier70 Hi there, the issue should be fixed now. Please feel free to ping me on this issue again if it pops up again!
