### ISSUE TITLE
Invalid `user.id` length for passkeys handlers

### ISSUE THREAD

**Issue by LeoColomb** [getsentry/sentry#70412]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Having a passkeys manager running (e.g: a password manager)
2. Being authenticated on Sentry
3. Go to the U2F page https://sentry.io/settings/account/security/mfa/u2f/enroll/

### Expected Result

All the enrollment to run without issues and the key challenge to be accepted.
The `user.id` standard to be respected
* https://w3c.github.io/webauthn/#dom-publickeycredentialuserentity-id
* https://developer.mozilla.org/en-US/docs/Web/API/CredentialsContainer/create#id_5

### Actual Result

The interface shows an error.
![image](https://github.com/getsentry/sentry/assets/846943/3f2df084-153d-4481-8e25-b2f7408e5937)

The passkeys manager receives an incorrect `user.id` length.

![image](https://github.com/getsentry/sentry/assets/846943/d7613384-47d7-4e5d-9db6-eb4d2bf7f3b4)

The password manager logs an error.

```
[Fido2Client] Invalid 'user.id' length: oWlwdWJsaWNLZXmmYnJwomJpZGlzZW50c[truncated] (589)
```

Ref: https://github.com/bitwarden/clients/issues/8756

I tried to dig in where the wrong length was created, but it seems to be generated to correct way:

https://github.com/getsentry/sentry/blob/9d2044811ebac0d3412a57cb755c79d650fd8668/src/sentry/auth/authenticators/u2f.py#L111

Some ideas:
* Fido2 Server is re-processing the `user.id`
* There is a mismatch in the encoding/decoding somewhere, possibly while the data transited on the frontend React page. 

### Product Area

Settings - Auth

### Link

https://sentry.io/settings/account/security/mfa/u2f/enroll/

**Comment by leedongwei** [comment]
We're looking into this. Thanks for the detailed bug report!

**Comment by mdtro** [comment]
@LeoColomb

I'm able to recreate this using the Bitwarden Browser Extension 2024.4.2 and Chrome 124.0.6367.156. I don't receive a prompt from Bitwarden to setup a passkey. Is this what you're experiencing? Could you share your extension and browser versions?

Interestingly, I cannot recreate this using 1Password. It successfully prompts to create a new passkey and registers it fine.

**Comment by LeoColomb** [comment]
@mdtro Good to know!.
I don't think the version numbers are going to explain anything: I've tried with 3 different browsers (Chrome, Firefox, Brave), with different versions (I'm facing this issue for half a year at least).
Same for Bitwarden.
In any case, latest versions are affected.

The prompt is not shown because of the error reported by Bitwarden's background script.

**Comment by LeoColomb** [comment]
@mdtro After further investigation, it appears that the `user.id` provided is actually the challenge data encoded with CBOR+base64.
The `user.id` inside that data is the valid one.

![image](https://github.com/getsentry/sentry/assets/846943/d3e8b4dd-fa24-4350-8b5a-7528a32ca184)

**Comment by mdtro** [comment]
@LeoColomb Good catch! Our backend API returns this in a JSON response to a GET on `/api/0/users/me/authenticators/u2f/enroll/`.

```json
{
    ...
    "challenge": {
        "webAuthnRegisterData": "<encoded data>"
    }
}
```

@leedongwei I'm not great with the frontend code. Is it possible we are decoding this incorrectly and putting the wrong values in `user.id`? Or is this an issue with the BitWarden client/extension?

**Comment by LeoColomb** [comment]
@mdtro @leedongwei If I may, is there any other data/info I can provide to help?

**Comment by leedongwei** [comment]
We need to schedule the work but there are competing priorities. I'll try my best to get someone to address it this month.

**Comment by LeoColomb** [comment]
Closing as an issue on Bitwarden side.
