### ISSUE TITLE
Sentry 8.22 Github auth backend is unclear

### ISSUE THREAD

**Issue by mmclanerh** [getsentry/sentry#7042]
I'm trying to get github sso auth options to enable and there doesn't seem to be a clear way to enable it. 

- Adding GITHUB_APP_ID, didn't automagically enable the github sso option
- There's django? Should I be hand crafting the social auth config options? If so, which are exposed?
- There's a stand-along pip install of github auth -- is this current? How does this relate to the sentry-plugins package?
- There's also the sentry-plugins package..  which has no documentation but seems ike it might expose some SENTRY_OPTIONS related to github auth..?

What's the correct way to enable github auth in Sentry 8.22?

Thanks.

**Comment by EvanPurkhiser** [comment]
You've installed the [auth Github plugin](https://github.com/getsentry/sentry-auth-github) correct?

**Comment by mmclanerh** [comment]
I'm using the official Docker image  [1]-- which has [2]  deployed inside of it, which itself seems to have the github plugin contained within it [3]?  

[1] https://github.com/getsentry/docker-sentry/blob/b7d55c572e0b23c5c537432211823a8677727e1c/8.22/Dockerfile#L63-L64
[2] https://github.com/getsentry/sentry-plugins

[3] https://github.com/getsentry/sentry-plugins/tree/master/src/sentry_plugins/github

```
# sentry plugins list
jira: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
bitbucket: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
github: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
amazon_sqs: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
slack: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
pushover: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
gitlab: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
jira_ac: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
hipchat_ac: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
victorops: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
sessionstack: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
heroku: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
asana: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
pivotal: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
pagerduty: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
vsts: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
segment: sentry-plugins 8.22.0 (/usr/lib/python2.7/site-packages)
```

**Comment by mmclanerh** [comment]
Also, saw this is included in the sentry core:  
https://github.com/getsentry/sentry/blob/releases/8.22.x/src/social_auth/backends/github.py

If the solution here is simply adding the py code -- then, okay. :)  I'll probably ship up a PR to get that (and maybe the other SSO plugins, ex: google) into the official docker images.  It'd be great if that came pre-bundled.

**Comment by EvanPurkhiser** [comment]
> which itself seems to have the GitHub plugin contained within it.

This is a little confusing right now, but the GitHub _plugin_ and GitHub _authentication provider_ (sentry-auth-github) actually do different things. The GitHub plugin adds features like opening GH issues from a Sentry issue, where as the auth provider is used for SSO.

We plan to merge the `sentry-auth-*` plugins into the `sentry-plugins` package soon, since right now they are unversioned, leading us to having not included them in the docker image. We'll get them in their soon though.

For now, following the instructions in the GitHub auth providers readme should get you going! https://github.com/getsentry/sentry-auth-github

**Comment by mmclanerh** [comment]
That makes sense.   Thank you very much for the insight there.  For what it's worth, I'm creating some container images that will include 8.22.0 with the Google/Github plugins baked in (though, I had to use not-the-latest Google code, with 8.22.0).  

Would it be helpful for me to ship a PR for 8.22.0 Docker images (ex: sentry-sso:8.22) that bundle the SSO code?  If those are getting merged into sentry-plugins "soon", I guess, that might be moot.   Let me know!  I'm happy to share.

**Comment by EvanPurkhiser** [comment]
> Would it be helpful for me to ship a PR for 8.22.0 Docker images (ex: sentry-sso:8.22) that bundle the SSO code? If those are getting merged into sentry-plugins "soon", I guess, that might be moot. Let me know! I'm happy to share.

@mattrobenolt ^

**Comment by mmclanerh** [comment]
btw, I am fine with closing this issue.  I can submit a PR as described, and we can discuss in the PR comments it makes sense to include/tweak/reject there.

Thanks again for the responses (and of course, for all the work on Sentry) -- greatly appreciate it!

**Comment by EvanPurkhiser** [comment]
Sounds good, @mmclanerh

**Comment by riker09** [comment]
@mmclanerh @EvanPurkhiser There is no reference of a PR here and no further status updates. So, my question, what's the status on this? 🙂
