### ISSUE TITLE
Alerts are not being triggered for User Feedback

### ISSUE THREAD

**Issue by yuval-sentry** [getsentry/sentry#70440]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Create an alert rule and add a filter category = Feedback (
![Screenshot 2024-05-07 at 11 05 50 AM](https://github.com/getsentry/sentry/assets/89414234/d65cf781-eaa2-4bfe-94ea-8123c2c83cb8)

Submit a User Feeback and see that alert is not triggering

### Expected Result

Alert should trigger when user is sending a feedback.

### Actual Result

Not alert is being sent.

Workaround for now, adding a filter that says if the event type does not contain error does work.

See the attached.

![Screenshot 2024-05-07 at 11 06 42 AM](https://github.com/getsentry/sentry/assets/89414234/e2ce8e4b-1946-466f-b709-2cd4c7b51ea9)

### Product Area

Alerts

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2171) by [Unito](https://www.unito.io)

**Comment by dalnoki** [comment]
Hi @yuval-sentry could you please check if you enabled the Crash Report Notifications" in Settings > Projects > [Project Name] > User Feedback? If yes, and it's still not working, would you mind sharing the alert rule so I can take a closer look at it? If you're not comfortable sharing it here, please open a ticket [here](https://sentry.zendesk.com/hc/en-us/requests/new)
