### ISSUE TITLE
The number of transactions is zero in all projects after upgraded

### ISSUE THREAD

**Issue by trongquan1297** [getsentry/sentry#70473]
### Self-Hosted Version

24.4.0

### CPU Architecture

x64_86

### Docker Version

20.10.21

### Docker Compose Version

v2.12.2

### Steps to Reproduce

1. Upgrading from 21.11.0 -> 23.6.2 -> 24.4.0
2. The number of transactions is zero in all projects
![image](https://github.com/getsentry/self-hosted/assets/44629299/66772f0d-3420-4265-907f-4172f137b9b9)

### Expected Result

The number of transactions is equal to the number of transactions in the Performance tab.

### Actual Result

n/a

**Comment by k-fish** [comment]
Hey there @trongquan1297 can you take a screenshot of your **Discover** tab searching for that project with a filter of `project:<project_name> event.type:transaction` and a `count()` column (see screenshot below).

![Screenshot 2024-05-09 at 2 16 26 PM](https://github.com/getsentry/sentry/assets/6111995/c431ff17-7413-48dd-bbe7-069a994eb820)

**Comment by trongquan1297** [comment]
> project:<project_name> event.type:transaction

Yes. transaction still come
![image](https://github.com/getsentry/sentry/assets/44629299/f0e5044d-b365-43a3-9819-ada4168d6826)

**Comment by gggritso** [comment]
@trongquan1297 thanks! We're taking a look, and will try to get back to you early next week when the folks who were helping you are back from being away

**Comment by ivacom** [comment]
Hello, we encountered the same problem. Help is needed.

**Comment by gggritso** [comment]
@ivacom are you using a self-hosted instance? If yes, what version of self-hosted are you running, and what was your previous version before the upgrade?

**Comment by gggritso** [comment]
@trongquan1297 are you still experiencing this problem?

**Comment by SCjona** [comment]
this is still happening for me with Sentry 24.6.0

**Comment by ivacom** [comment]
yes, I use self-hosted, updated from version 23.3.1 > 23.6.2 > 24.3.0 > 24.6.0.
It seems the problem appeared after updating to version 23.6.2.
`<your.sentry.version> -> 23.6.2 -> latest`
https://develop.sentry.dev/self-hosted/releases/

**Comment by gggritso** [comment]
@ivacom @SCjona thanks for clarifying! I need a little more info from you to help debug this, bear with me. Here's what I need:

1. Go to your Sentry's "Projects" page
2. Open the browser's Developer Tools
3. Refresh
4. In Developer Tools, in the "Network" panel find an outgoing HTTP GET request to a URL that looks like this: `https://<your-sentry-url>/api/0/organizations/<your-organization>/projects/?dataset=<something>&query=id:<some-project-id> id:<some-project-id> &sessionStats=1...more URL parameters`
5. Paste the URL here. You can omit your organization and project IDs from the request.

**Comment by ivacom** [comment]
@gggritso 

https://sentry/api/0/organizations/sentry/projects/?dataset=metricsEnhanced&query=id%3A15%20id%3A23%20id%3A22%20id%3A27&sessionStats=1&statsPeriod=24h&transactionStats=1

**Comment by gggritso** [comment]
@ivacom thanks! That part looks correct. Next, can you check the contents of the response? It should be an array that looks like this:

```json
[
  {
    id: 15,
    name: ...
    team: ...etc
    transactionStats
```

Can you paste the contents of `transactionStats`?

**Comment by ivacom** [comment]
@gggritso , Yes, 
"transactionStats": [
      [1721336400, 21191],
      [1721340000, 19083],
      [1721343600, 19162],
      [1721347200, 24648],
      [1721350800, 35906],
      [1721354400, 55665],
      [1721358000, 83597],
      [1721361600, 108304],
      [1721365200, 133168],
      [1721368800, 166180],
      [1721372400, 196108],
      [1721376000, 194613],
      [1721379600, 197770],
      [1721383200, 191335],
      [1721386800, 180598],
      [1721390400, 174520],
      [1721394000, 169829],
      [1721397600, 159714],
      [1721401200, 151055],
      [1721404800, 134266],
      [1721408400, 117220],
      [1721412000, 97107],
      [1721415600, 74891],
      [1721419200, 9442]
    ],

**Comment by SCjona** [comment]
@gggritso 

`https://sentry.hostname.tld/api/0/organizations/<org-name>/projects/?dataset=metricsEnhanced&query=id%3A7%20id%3A5%20id%3A4%20id%3A1%20id%3A6%20id%3A3%20id%3A2&sessionStats=1&statsPeriod=24h&transactionStats=1`

Response transactionStats:
<details>

```json
{
	"transactionStats": [
		[
			1721340000,
			0
		],
		[
			1721343600,
			0
		],
		[
			1721347200,
			0
		],
		[
			1721350800,
			0
		],
		[
			1721354400,
			0
		],
		[
			1721358000,
			0
		],
		[
			1721361600,
			0
		],
		[
			1721365200,
			0
		],
		[
			1721368800,
			0
		],
		[
			1721372400,
			0
		],
		[
			1721376000,
			0
		],
		[
			1721379600,
			0
		],
		[
			1721383200,
			0
		],
		[
			1721386800,
			0
		],
		[
			1721390400,
			0
		],
		[
			1721394000,
			0
		],
		[
			1721397600,
			0
		],
		[
			1721401200,
			0
		],
		[
			1721404800,
			0
		],
		[
			1721408400,
			0
		],
		[
			1721412000,
			0
		],
		[
			1721415600,
			0
		],
		[
			1721419200,
			0
		],
		[
			1721422800,
			0
		]
	]
}
```

</details>

**Comment by gggritso** [comment]
Got it! I'll continue looking at this on Monday. Thank you!

**Comment by ivacom** [comment]
Hi! @gggritso 
Let's continue?

**Comment by ivacom** [comment]
thanks @gggritso , yes, I most likely have a problem with displaying @SCjona no transactions.


> [@gggritso](https://github.com/gggritso)
> 
> `https://sentry.hostname.tld/api/0/organizations/<org-name>/projects/?dataset=metricsEnhanced&query=id%3A7%20id%3A5%20id%3A4%20id%3A1%20id%3A6%20id%3A3%20id%3A2&sessionStats=1&statsPeriod=24h&transactionStats=1`
> 
> [
			1721340000,
			**0**
		],
		[
			1721343600,
			**0**
		],

@SCjona This part of the request contains the project code query=id%3A**7**%20id%3A**5**%20id%3A**4**%20id%3A**1**%20id%3A**6**%20id%3A**3**%20id%3A**2**

Perhaps in transactionStats there are project data where there are no transactions
[1721408400, **117220**],
[1721412000, **97107**],
[1721415600, **74891**],

**Comment by SCjona** [comment]
no we have transactions, this is just broken in the project overview/details, works fine in the performance tab

![Image](https://github.com/user-attachments/assets/0e3ffe5e-405e-4a8a-b0cd-eb965f634311)

`GET https://sentry.hostname.tld/api/0/organizations/<org>/events-meta/?dataset=metricsEnhanced&environment=master&project=3&query=event.type:transaction&statsPeriod=14d`
returns count 0 (triggered in project overview)

`GET https://sentry.hostname.tld/api/0/organizations/<org>/events-stats/?environment=master&interval=1h&partial=1&project=3&query=event.type:transaction&referrer=api.performance.generic-widget-chart.apdex-area&statsPeriod=28d&yAxis=apdex()&yAxis=tpm()&yAxis=failure_rate()`
returns correct? data (triggered in performance view)

Interestingly `GET https://sentry.hostname.tld/api/0/organizations/<org>/events-meta/?environment=master&project=3&query=event.type:transaction&statsPeriod=14d&utc=true` returns count > 0 (triggered in discover)

If i remove the `utc=true` parameter i still get count > 0, but if I add `dataset=metricsEnhanced` I get count = 0.

**Comment by gggritso** [comment]
@SCjona this is interesting!

Could you check whether these features are enabled in your Sentry config?

- `'organizations:metrics-extraction'`
- `'organizations:transaction-metrics-extraction'`
- `'organizations:mep-rollout-flag'`

If those features are not enabled, please turn them on. This will turn on metrics extraction from transactions, which will start collecting transaction metrics and start populating the charts. You should start getting data from that point.

Let me know if that works! In the meantime, I will talk to the team about doing a frontend fallback (which the Performance tab does automatically).

@ivacom do you mind checking those features on your instance, too?

**Comment by ivacom** [comment]
yes, included

![Image](https://github.com/user-attachments/assets/dc87b82a-34c5-4b2a-bdd1-ffd456ecd28b)

**Comment by SCjona** [comment]
@gggritso Those features were missing from my `sentry.conf.py`. I hadn't updated that one in a while, just did `cp sentry.conf.example.py sentry.conf.py`. I now get transactions in the project overview as new data is coming in. Thank you!

**Comment by gggritso** [comment]
@SCjona glad to hear it! Sounds like the issue is resolve for you, yes?

@ivacom if can try a version between 23.6.2 and 23.12.1 that would help narrow down the issue! There are 4-5 releases in that range you could try. If you can specify which _exact_ release first breaks the feature, that would help a lot

**Comment by ivacom** [comment]
@gggritso 
updated 23.6.2-> 23.10.1 there is a problem.
updated 23.6.2-> 23.8.0 no problem.
It remains to check 23.6.2-> 23.9.1.

**Comment by ivacom** [comment]
@gggritso Hi!
Updated 23.6.2 -> 23.8.0 -> 23.9.1 no problem.
Updated 23.9.1->23.10.1 there is a problem. It turns out that after 23.9.1 it will not be possible to update.

**Comment by gggritso** [comment]
@ivacom thanks for narrowing it down! I'm going to see if I can figure out what broke between those versions

**Comment by gggritso** [comment]
@ivacom I took a look at the diff between those versions, but didn't spot anything obvious. Unfortunately, I'm running out of ways to help you! Without access to your environment, there's not much else I can do. Once of the downsides of self-hosted over SAAS.

At this point I need more information. If you're able to take a lead on debugging, that would help move this forward. Sentry's front end code has source maps, so you should be able to step through the browser's debugger and check a few points:

- the `render` method of `ProjectCard` is in charge of [calculating the total transaction count](https://github.com/getsentry/sentry/blob/23.9.1/static/app/views/projectsDashboard/projectCard.tsx#L131). If you can add a breakpoint there, it should be possible to see if `transactionStats` has any non-zero data points in it at any point
- the `_debouncedLoadStats` method is in charge of fetching the data from the endpoint. If you [add a breakpoint there](https://github.com/getsentry/sentry/blob/fc893afc4be0cbd544533dcf6801eb313595f987/static/app/actionCreators/projects.tsx#L109), you should be able to confirm/deny whether it's able to successfully fetch the results for your projects

Also overall, watch out for any errors in the Network pane (maybe CORS or CSRF errors, 500s, or anything similar) or in the browser console (errors parsing responses, errors with `undefined` values, or anything similar)

**Comment by ivacom** [comment]
@gggritso hi!
In general, we partially figured out the problem, but we found a problem point.
The problem point is Relay.
We have Relay in static mode, only redis and kafka are connected.
On sentry version 23.3.1 everything works fine, starting with version 23.9.1 relay in static mode does not transfer data for display in projects or the main stack does not process this data. If relay is in managed mode with upstream: web:9000 specified, everything works and is displayed in projects.

Relay is in a closed network and it cannot be connected to upstream: web:9000, so relay is in static mode with kafka and redis connection.
Kafka and redis use the same

please help.

**Comment by jjbayer** [comment]
@ivacom could you please check whether you have the feature flag for transaction metrics extraction enabled, as it is in the linked example?

https://github.com/getsentry/self-hosted/blob/3d120727d5118e6d9ec6932f88756de4d3cbaaba/sentry/sentry.conf.example.py#L288

**Comment by ivacom** [comment]
yes, it is enabled as you can see from the message above
https://github.com/getsentry/sentry/issues/70473#issuecomment-2244319673




as I said above, the problem is in static mode, in managed mode there is no problem with displaying the number of transactions in projects

**Comment by jjbayer** [comment]
@ivacom sorry, I had not read the entire conversation. What you're describing does sound like a Relay bug: static mode should forward all data unless configured differently. Would you be able to share your local `.relay/config.yml` (feel free to redact any fields you don't want to share) ?

**Comment by ivacom** [comment]
Sure!
![Image](https://github.com/user-attachments/assets/433e68f1-8e37-4387-82fd-9ab95d0ee798)

**Comment by jjbayer** [comment]
@ivacom thanks! `mode: static` and `processing.enabled: true` are actually mutually exclusive (think of `managed+processing` as a fourth relay mode). We added an explicit validation step for proxy mode, but apparently forgot about static mode: https://github.com/getsentry/relay/pull/3146.

> Relay is in a closed network and it cannot be connected to upstream: web:9000, so relay is in static mode with kafka and redis connection.

Would it be possible for you to switch to Managed mode? If Relay can connect to Kafka and Redis, why not allow it to the upstream as well?

**Comment by ivacom** [comment]
Unfortunately, this is not possible, Kafka and redis are located in the same place as relay.
Sentry can connect to kafka and redis, but reverse connection from a closed network from Relay to Sentry is not possible for security reasons.
What config should I use for testing?

**Comment by jjbayer** [comment]
> Let me remind you that on version 23.3.1 everything works without problems.

I'm surprised this even worked. What you could try to restore previous behavior is adding `{"config": {"transactionMetrics": {"version": 6}}}` to your project config(s) in `.relay/projects/*.json`.

I will discuss with the team whether we want to support processing in static mode in the future.

**Comment by ivacom** [comment]
Added your config, the result is the same, zero transactions in Projects
![Image](https://github.com/user-attachments/assets/8dcc683a-d98e-4473-a034-ed798cfdef03)


Here is the full config
![Image](https://github.com/user-attachments/assets/359cc98b-3586-47f7-8877-d625727b14c4)

**Comment by ivacom** [comment]
Hi!
Is there any solution?

And by the way, transactions in projects do not work in proxy mode either.

We really need your help, we cannot update.

**Comment by jjbayer** [comment]
@ivacom your use case is tricky because it's a setup we do not recommend. Essentially you need to create a project config to resemble closely a a project config that would get sent from sentry. I'm looking at this code in particular: https://github.com/getsentry/relay/blob/a1713f11ff1840023e81b15145166eada08c3b14/relay-server/src/services/processor.rs#L1376-L1384

You might also need to add  a `{"metricExtraction": {"version": 4}}` to your config. Do the relay logs contain anything that might point you to the problem?

**Comment by ivacom** [comment]
@jjbayer 
added to the config, it did not give a result, previously in the projects there are zero transactions. 
there are no errors in the log. 

maybe something needs to be added to the relay source code so that it works in our complex configuration?

**Comment by SuperTommy007** [comment]
Every time I run it for a while (about 1 or 2 days) the transactions in the projects page goes to 0, then I use docker-compose down and docker-compose up -d and the transactions value goes back to normal, then after a while it goes back to 0 again.![Image](https://github.com/user-attachments/assets/598bd7d5-a1ff-4ccc-8bbb-a78fdd560a8a)

**Comment by SuperTommy007** [comment]
> Every time I run it for a while (about 1 or 2 days) the transactions in the projects page goes to 0, then I use docker-compose down and docker-compose up -d and the transactions value goes back to normal, then after a while it goes back to 0 again.![Image](https://github.com/user-attachments/assets/598bd7d5-a1ff-4ccc-8bbb-a78fdd560a8a)

![Image](https://github.com/user-attachments/assets/4ffdbb63-ef3a-4705-ba1d-e558d3840dd7)
![Image](https://github.com/user-attachments/assets/0dd43d53-0ef3-43ba-9362-61be9520f521)

**Comment by jjbayer** [comment]
@ivacom I discussed the matter with the team, we are going to explicitly forbid combining static mode + processing enabled because we cannot support it and it will become even harder to maintain in the future. May I ask why the HTTP connection in your case is a security concern, but the redis & kafka connections are not?

**Comment by jjbayer** [comment]
@SuperTommy007 what you are describing sounds like a [dynamic sampling](https://develop.sentry.dev/application/dynamic-sampling/) issue, is the transaction count actually zero or just a very low number?

**Comment by ivacom** [comment]
@jjbayer Hi!
where we have kafka and relay, this is a closed cloud server from which there is no access to the main sentry server, but there is access from the main sentry server to the cloud server.   The restrictions are determined by the information and financial security service, and we cannot bypass them. we accept more than 1M transactions per hour, we really need the function of static mode + enabled processing, help us build a relay version at least up to 24.4.x with the required function, and then we will try to solve the issue with access from the cloud server.
We really need to update

**Comment by SuperTommy007** [comment]
> [@SuperTommy007](https://github.com/SuperTommy007) what you are describing sounds like a [dynamic sampling](https://develop.sentry.dev/application/dynamic-sampling/) issue, is the transaction count actually zero or just a very low number?

it's just zero...

**Comment by SuperTommy007** [comment]
> > [@SuperTommy007](https://github.com/SuperTommy007) what you are describing sounds like a [dynamic sampling](https://develop.sentry.dev/application/dynamic-sampling/) issue, is the transaction count actually zero or just a very low number?
> 
> it's just zero...

I think this is a memory problem, it was 16G before, now I have no problem with 32G

**Comment by jjbayer** [comment]
@ivacom I'm sorry, we cannot support this use case. Your best options IMO is allowing relay to make HTTP requests to your sentry instance, or forking relay to make it behave in the way you want it to.

@SuperTommy007 thanks for the update, I'm glad you got it to work!

**Comment by ivacom** [comment]
@jjbayer 
`or forking relay to make it behave in the way you want it to.`

Can you be more detailed?

**Comment by jjbayer** [comment]
> > or forking relay to make it behave in the way you want it to.
> 
> Can you be more detailed?

@ivacom You would have to identify the section of Relay that drops the events, and then rewrite the code to prevent that from happening. This in turn might introduce new inconsistencies though, so allowing relay to make HTTP requests to your sentry instance and switching to Managed mode is definitely the easier path.
