### ISSUE TITLE
Project lost after transfering

### ISSUE THREAD

**Issue by saif-alj** [getsentry/sentry#70494]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Issue with project

### How are you getting stuck?

I transferred a project from an org to another, having my email address being the owner of both. The project doesn't exist in the newly created org.

from organization: Blank Space
project: noodlebox-app
requested by: [hello@blankspaceinc.ca](mailto:hello@blankspaceinc.ca)
requested at: [May 8, 2024, 4:46 a.m.](https://github.com/getsentry/sentry/issues/2024-05-08%2004:46:00%20EDT)

### Where in the product are you?

Settings - Projects

**Comment by rodolfoBee** [comment]
Check if the project is in Organisation Settings -> Projects ( https://idh-vn.sentry.io/settings/projects/ ).

You need to add a team to the project to view it -> https://docs.sentry.io/organization/membership/#transfer-a-project

> When transferring a project to a new organisation, we recommend also adding a new team to the project for better visibility.
