### ISSUE TITLE
Clicking unmerge dialogue box buttons not making dialogue disappear

### ISSUE THREAD

**Issue by lauryndbrown** [getsentry/sentry#7052]
On sentry.io when attempting to unmerge issues, I ran into a bug where clicking the buttons on the dialogue box does not make the box go away. Clicking anywhere else on the dialogue box does however, make it disappear. 
<img width="1680" alt="screen shot 2018-01-24 at 11 44 47 am" src="https://user-images.githubusercontent.com/12959365/35353540-53ed72ce-00fc-11e8-8c5c-98e6d7deb9b7.png">

**Comment by lynnagara** [comment]
I think this might be happening on all our Confirmation modals
