### ISSUE TITLE
[Ui] Enable JavaScript source fetching option not greyed out for Member role

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#70604]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

In Project Settings - General Settings

Member role can't make changes to the settings on this page.  Most of them are greyed out as expected but the Enable Javascript Source Fetching option is still clickable.  If a member clicks it, it toggles off but the settings do not persist if you refresh.  Here is a screen recording -

https://github.com/getsentry/sentry/assets/96670625/a7035644-2c09-4856-9fc8-02c14c18d18d

### Expected Result

Option should not be clickable at all.

### Actual Result

Option can be clicked.

### Product Area

Settings - Projects

**Comment by leedongwei** [comment]
Seems like a UI bug from the recording. I'll schedule it for someone to fix.
