### ISSUE TITLE
Suspect Commit discrepancies

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#70615]
The root of the problem is that somehow the Slack notifications and the UI are fetching the data differently.

The UI gets the list of committers from this API: https://us.sentry.io/api/0/projects/sentry/sentry/events/d6d5d807c0d9449d827e004623246900/committers/

@malwilley was one of the last people touching this area.

We would have to determine how the Slack alert gets the suspect commit.

### Which suspect commit would have been the better pick?

If we load [this issue](https://sentry.sentry.io/issues/5326921843) we will see this suspect commit (https://github.com/getsentry/sentry/pull/69211 to PR):
<img width="426" alt="image" src="https://github.com/getsentry/sentry/assets/44410/3f972cb5-a9d0-477a-b95e-872981efe9cf">

If we look at the alert we received in Slack we will see this suspect commit ([link to PR](https://github.com/getsentry/sentry/pull/70574)):
![image](https://github.com/getsentry/sentry/assets/44410/4e972d46-592f-435b-bac3-de0ab364c828)

The stack trace is this:
<img width="725" alt="image" src="https://github.com/getsentry/sentry/assets/44410/67877d8e-3ae7-4335-9ddb-84574f1a2376">

Yagiz's change is the suspect commit because [base.py was recently changed](https://github.com/getsentry/sentry/blob/6c6900cbe0cdd569c5978e39f088da5d11330890/src/sentry/api/base.py#L439) from the stack trace, however, the change was from `load_json_body` rather than `dispatch` (which is part of the stack trace), thus, it should not have been considered a suspect commit:

From Yagiz's change:
<img width="512" alt="image" src="https://github.com/getsentry/sentry/assets/44410/b7736705-a68d-44da-b6d8-f0185023b2c2">
This shows that the function `dispatch` is part of the stack trace:
<img width="489" alt="image" src="https://github.com/getsentry/sentry/assets/44410/0a4068f6-c0af-4112-ba57-0e06d4c332fe">

Snigdha's change does touch the `put` function from `organization_group_index.py`, thus, it makes more sense to blame it:
<img width="676" alt="image" src="https://github.com/getsentry/sentry/assets/44410/a4bb96fc-f302-4dec-8deb-847fb18197af">
<img width="604" alt="image" src="https://github.com/getsentry/sentry/assets/44410/df11e352-d27f-4ba7-be45-37c566ea8f2c">

**Comment by ceorourke** [comment]
Cathy's working on this in https://github.com/getsentry/sentry/pull/70634

**Comment by cathteng** [comment]
The suspect commit is processed async so it's not guaranteed to exist by the time the Slack notification is sent. I added logic to fetch it via GroupOwner if it exists

**Comment by snigdhas** [comment]
Sounds like this was fixed in #70634
