### ISSUE TITLE
sentry replay not found 

### ISSUE THREAD

**Issue by lmcccy** [getsentry/sentry#70638]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1、Main.js file is configated.
2、Sentry@vue version and sentry@replay version are newliest.
3、But interface is show 'Replay Not Found'.

### Expected Result

Replay Not Found

### Actual Result

Replay Not Found

### Product Area

Replays

**Comment by bruno-garcia** [comment]
Which version of self hosted? Not a lot of details to help us debug ur set up, could u elaborate further please?

**Comment by lmcccy** [comment]
> Which version of self hosted? Not a lot of details to help us debug ur set up, could u elaborate further please?

my sentry version is "@sentry/cli": "^2.31.2",

**Comment by billyvg** [comment]
Can you post your `Sentry.init` (without DSN) and a link to a replay?

**Comment by billyvg** [comment]
Closing due to lack of reproduction steps.
