### ISSUE TITLE
User heat map generation

### ISSUE THREAD

**Issue by tellisnz** [getsentry/sentry#70642]
### Problem Statement

We're using replays to great effect we ended up discontinuing our hotjar account. A big thing we obviously lose from that is the site heatmaps.

### Solution Brainstorm

I was wondering given that we have replays if it would be possible to aggregate them to produce a heat map of sorts?

### Product Area

Replays

**Comment by jas-kas** [comment]
Hey @tellisnz 👋 

Thanks for your feature request. We don't have plans at the moment to build a heatmap functionality but will keep this in mind for future feature development.

To understand your request better, what type of insights are you hoping to gain from a heatmap visualization?

**Comment by vctormb** [comment]
> User behavior insights, possibly pairing with dead/rage clicks. Basically what we lost from switching from dropping hotjar for further expanding our sentry account.

Same here! I'd love to have this feature available too!

**Comment by vctormb** [comment]
> @vctormb could u give some examples about how you'd use this? curious about use cases as we're aiming to add features focused on debuggability use cases

Our UX designers used to use this feature in other platforms to understand the user's engagement and interactions with the elements and click attempts on the screen

**Comment by bruno-garcia** [comment]
We're looking for use cases for developers only though, so although it's quite useful for designers and PMs, we haven't seen a big use case for devs for this feature. I'll close the issue since we don't intend on adding this anytime soon

**Comment by bruno-garcia** [comment]
We're considering adding this. Not in the plan right now but it's definitely something we could add in Q4 perhaps.

**Comment by weixing02** [comment]
> We're considering adding this. Not in the plan right now but it's definitely something we could add in Q4 perhaps.

I'd love to have this feature available too! our ux / pm always wanted this. looking forward to it.
