### ISSUE TITLE
[Mobile Replay - Bug] Video player plays wrong clip

### ISSUE THREAD

**Issue by michellewzhang** [getsentry/sentry#70687]
See comments below for relevant examples

**Comment by michellewzhang** [comment]
Looked into this a bit. Seems to be a weird replay because in `loadSegmentAtTime`, `segmentIndex` is always undefined, which seems to relate to a gap: cc @billyvg 

https://github.com/getsentry/sentry/assets/56095982/7e7bbc84-eea5-4d8c-ad57-c5f0fbf6b7ad

https://github.com/getsentry/sentry/blob/1491155c67bec5eb0c4a9f89de282cbbe2316cf9/static/app/components/replays/videoReplayer.tsx#L555-L560

**Comment by michellewzhang** [comment]
example replay: https://sentry-sdks.sentry.io/replays/e63c8004ce07468a9e461d75d4d5944b/?project=5428557&query=&referrer=%2Freplays%2F&statsPeriod=90d&yAxis=count%28%29

this one & the example above may be due to the fact that the ios sdk is sending `video.duration` in seconds (rather than milliseconds). need to validate when the SDKs are sending the duration in ms

**Comment by michellewzhang** [comment]
additional example with android SDK (which is not related to the seconds/ms problem): https://sentry-sdks.sentry.io/replays/f7797884538f49288eccf9497def2634/?project=5428559&query=&referrer=%2Freplays%2F&statsPeriod=14d&yAxis=count%28%29

if you play/pause around 5, 10, 15, and ~19 seconds, you'll notice some flickering as well. i believe that this is related to this chunk of code: https://github.com/getsentry/sentry/blob/0298eef00139c5bb6838e382064aaacd6177926e/static/app/components/replays/videoReplayer.tsx#L321-L323

**Comment by c298lee** [comment]
> additional example with android SDK (which is not related to the seconds/ms problem): https://sentry-sdks.sentry.io/replays/f7797884538f49288eccf9497def2634/?project=5428559&query=&referrer=%2Freplays%2F&statsPeriod=14d&yAxis=count%28%29
> 
> if you play/pause around 5, 10, 15, and ~19 seconds, you'll notice some flickering as well. i believe that this is related to this chunk of code - maybe something to do with the fact that our segment is ending early and we've accidentally clicked into this gap:
> 
> https://github.com/getsentry/sentry/blob/0298eef00139c5bb6838e382064aaacd6177926e/static/app/components/replays/videoReplayer.tsx#L321-L323

In this example, the replay also flickers when playing between video segments when you replay it (eg. 5, 10, and 15 seconds). There is no flickering on first play through
