### ISSUE TITLE
Getting started sidebar skip button looks broken

### ISSUE THREAD

**Issue by Chrissy** [getsentry/sentry#7068]
It might be intentionally this way, but it still looks not great and we (I) should fix it

![image](https://user-images.githubusercontent.com/435981/35413526-95de57ce-01d4-11e8-9007-b574c05345a0.png)

**Comment by Chrissy** [comment]
discovered by @lynnagara, dunno if she has anything to add

**Comment by lynnagara** [comment]
Thanks for creating this! The giant grey circles on the left could use some work imo :)

**Comment by Chrissy** [comment]
lol nawwwwww

**Comment by BYK** [comment]
This thing has been reworked multiple times at this point so closing the issue.
