### ISSUE TITLE
Slack Integration not working as expecting after upgrading to paid plan

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#70715]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

A customer wrote in with this complaint:

> We recently tried out sentry, and as part of that had slack integrations working. When the trial ended, slack was disabled. We then upgraded to the plan which includes slack integrations, but i can't get it working again. When i try to test notifications to Slack, i just get an internal error message.
> 
> I poked around the web developer console when trying to test an alert in the browser, and shows a 500 on the api call to sentry, with internal error and no details.
>

Please reach out @Dhrumil-Sentry for more details about the org slug and error message

### Expected Result

Test Notifications to Slack should work as expected

### Actual Result

.

### Product Area

Settings - Integrations

**Comment by cathteng** [comment]
We are investigating this and will update when we have more details.

**Comment by cathteng** [comment]
It looks like this org is hitting `message_limit_exceeded` from Slack's side. It's possible this org has a free Slack workspace https://slack.com/help/articles/115002422943-Usage-limits-for-free-workspaces

The image below is from https://api.slack.com/methods/chat.postMessage#errors
<img width="1010" alt="Screenshot 2024-05-15 at 12 08 08" src="https://github.com/getsentry/sentry/assets/70817427/a28530d2-16c4-4009-9a75-591b2296a36c">

**Comment by iamrajjoshi** [comment]
Closing this for now, if you are still experiencing this, please feel to reopen!
