### ISSUE TITLE
Cannot edit alert rule

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#70730]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open Alerts page
2. Click on the three dots next to the alert rule
3. The edit view for the alert does not load, there's one cancelled request and the metric endpoint returns a 400

### Expected Result

the user should be able to edit the alert rule

### Actual Result

it is not currently possible to edit the alert rule

### Product Area

Alerts

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2173) by [Unito](https://www.unito.io)

**Comment by ceorourke** [comment]
I can't reproduce the issue outside of the specific rule linked - has this happened to any other orgs? If this customer deletes the rule and makes another, does the same thing happen?

**Comment by bmulholland** [comment]
Okay, I've gone ahead and recreated the alert, deleting the old one. I can view/edit the new one -- though I don't know if I set the same options, since I couldn't view or edit the bugged alert.

**Comment by ceorourke** [comment]
This has been resolved, thanks for your patience! I've verified the rules that didn't load before the fix now load. This was only affecting metric alert rules with Linear actions, so it was a bit hard to track down.
