### ISSUE TITLE
Please allow for a dashboard or notification feature when an issue with a specific tag hasn't been seen in x amount of time.

### ISSUE THREAD

**Issue by configureng** [getsentry/sentry#70740]
### Problem Statement

Hello, I was told to make this feature request via Sentry support.  It would be very useful to be able to have a notification (email, etc) sent if an issue with a specific tag has not been seen in x amount of time (some customer settable number). Even better would be some sort of visual dashboard or screen on Sentry in addition that showed these types of things. 

Use case:
I have a script that runs every hour that sends an issue to sentry when completed or when there is an error thrown.  However periodically it can hang up due to a number of circumstances and never complete.  It would be nice to be able to see "hey I haven't gotten this issue with this tag in x amount of time I should go check on it and see why it's not working".  Right now I have to have a separate process entirely to check this via the output of a file and whether that exists or not.  It would be nice if I could just use sentry as the one place for this and get rid of the second process entirely.  

Thanks.

### Product Area

User Feedback

**Comment by ceorourke** [comment]
Hi @configureng - it sounds like maybe you want to use our cron monitoring product: https://docs.sentry.io/product/crons/#example-cron-monitoring-use-cases once set up it'll alert you if your task fails to have checkins.

**Comment by ceorourke** [comment]
Great! I'm going to close this issue, but feel free to re-open if it turns out that wasn't what you were looking for.
