### ISSUE TITLE
backup projects/user only

### ISSUE THREAD

**Issue by dcharbonnier** [getsentry/sentry#7083]
Doing a full backup/restore of an instance could take time with a lot of events.
There is some situations where the events are not so important and being able to just backup/restore the data that would not force a clients/ users change would be useful.
Storing a backup of that would be fast, inexpensive, would not create any load on the infrastructure and be a useful tool for disaster recovery.
The projects need to keep the same DSN, the users should be restored, optionally all settings (plugins, integrations, alerts should be included)
An export with an exclude could do the job but it's hard to know what to exclude.

Related to #2698

**Comment by sammerry** [comment]
There is a `sentry export` and `sentry import` command-line tool but there are known issues with importing the export file.

https://github.com/getsentry/sentry/issues/2836

**Comment by turbo124** [comment]
Came here for this, Backup and Restore of the Projects DSNs via the UI would be a very appreciated feature request.

This would help us get back on our feet and start processing events without having to reupdate clients with new DSNs etc.

**Comment by BYK** [comment]
I don't think we'll ever invest into a UI-based import/export solution but we will be making sure our `import` and `export` commands work. I'll close this issue in favor of #2836 as this one is more of a question.
