### ISSUE TITLE
Inbound filter for localhost does not ignore *subdomain.localhost reports

### ISSUE THREAD

**Issue by josias-r** [getsentry/sentry#70841]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Cause sentry issues from "anysubdomain.localhost:1234" with the inbound filter for localhost enabled

### Expected Result

Errors should not appear in sentry

### Actual Result

Errors are still being reported

### Product Area

Settings - Projects

**Comment by Dav1dde** [comment]
👍 Went ahead and implemented that in [Relay](https://github.com/getsentry/relay/pull/3608).
