### ISSUE TITLE
CORS error when Assigning and Resolving issues.

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#70859]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Some users have reported receiving a CORS error when clicking the resolve or assign buttons of an issue.  I am unable to reproduce, but the users consistently reproduce the issue.

Information shared from the user will be attached to linked [JIRA ticket](https://getsentry.atlassian.net/browse/FEEDBACK-2175).

### Product Area

Issues

**Comment by markstory** [comment]
Closing this as I've not heard of more problems related to this in a long time.
