### ISSUE TITLE
Source maps don't seem to be cached

### ISSUE THREAD

**Issue by marcoow** [getsentry/sentry#7085]
It looks like Sentry is downloading our source maps for every single error we track which results in several GBs of traffic per month in our case. I think Sentry should respect the caching headers when downloading the source maps for the first time. I understand the recommended way of providing source maps to Sentry is uploading them but I still think downloading them over and over otherwise is wrong?

Some details about our setup:

* we don't upload sourcemaps but reference them in our JS files, e.g. `//# sourceMappingURL=https://assets.trainline.eu/mweb/assets/mweb-f6189952b548425c98acd900d5bd50d9.map`
* the files are fingerprinted and have proper caching headers:
```
cache-control: public
cache-control: max-age=315360000
```
* we are running Sentry 8.18.0

**Comment by mattrobenolt** [comment]
You are right in that we don’t respect the Cache Control header. We have an internal note that we should. I don’t think we’d want to 100% respect it, so we’ll have to get some middle ground that works for us. 

For example:

* we still need to cache for a fixed period of time, even if marked as private or explicitly max-age=0, etc. this is very critical to our performance and processing. 
* we need to cap a max duration for caching on our side. If your cache control says 1 year duration, we can’t cache for 1 year. We should cap our side to a few hours at most.

But I agree I’m that we should do this.

**Comment by mattrobenolt** [comment]
@marcoow Also, tangentially, I just realized that you said "for every single error", and that shouldn't be true if you have caching configured. So it sounds like on your end, you don't have this, so no caching we add or improve upon will help you out without configuring this. :)

Right now, this is a hard coded cache for 60 seconds: https://github.com/getsentry/sentry/blob/master/src/sentry/lang/javascript/processor.py#L334

**Comment by lauryndbrown** [comment]
Hi @marcoow we just released this feature! If you set your cache-control's max-age to any value 60s to 7200s it should now respect that request. Please let me know if you have any questions. ^ . ^

**Comment by marcoow** [comment]
Awesome, thanks for the prompt fix!

**Comment by marcoow** [comment]
I realized I have a few follow-up questions :)

> Also, tangentially, I just realized that you said "for every single error", and that shouldn't be true if you have caching configured. So it sounds like on your end, you don't have this, so no caching we add or improve upon will help you out without configuring this. :)

Tbh, I didn't actually check that - we just observed a lot of data being transferred to Sentry so it's probably not actually every single error but every x minutes or so.

> * we still need to cache for a fixed period of time, even if marked as private or explicitly max-age=0, etc. this is very critical to our performance and processing.

Sure, that makes sense

> * we need to cap a max duration for caching on our side. If your cache control says 1 year duration, we can’t cache for 1 year. We should cap our side to a few hours at most.

I don't really understand why that is tbh. All of our assets are fingerprinted and thus are guaranteed to never become stale. Once there is a new version released the source map URL in the JS files would change and point to a different `*.map` file so that should be safe.

> Hi @marcoow we just released this feature! If you set your cache-control's max-age to any value 60s to 7200s it should now respect that request. Please let me know if you have any questions. ^ . ^

So does that mean our header `cache-control: max-age=315360000` would not actually have an effect?

**Comment by mattrobenolt** [comment]
> I don't really understand why that is tbh.

We don’t have infinite storage, and after this time, 1 request per 2 hours should be plenty sufficient. It’s diminishing returns beyond that. 

> So does that mean our header cache-control: max-age=315360000 would not actually have an effect?

It’s just capped to 7200 internally for us. So you’ll get benefits of it caching now more than 60s, but it won’t cache for 315360000s.
