### ISSUE TITLE
[User Feedback Onboarding] Add linkout about async

### ISSUE THREAD

**Issue by michellewzhang** [getsentry/sentry#70862]
Splitting the "async" part of https://github.com/getsentry/sentry/issues/69683 into a different issue since I don't think we have async-related docs for UF yet

cc @c298lee to add more details!

**Comment by ryan953** [comment]
Idk if we need a linkout, but is a PR about async loading... so if we link to something, that'll be where: https://github.com/getsentry/sentry-docs/pull/10108

**Comment by michellewzhang** [comment]
synced with @c298lee - we decided not to link in onboarding, it's fine to just have the documentation!
