### ISSUE TITLE
Feedback widget submission can result in duplicate feedback

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#70860]
[Feedback 1](https://sentry.sentry.io/feedback/?feedbackSlug=javascript%3A5348084909&project=4506155486085120&statsPeriod=90d)
[Feedback 2](https://sentry.sentry.io/feedback/?feedbackSlug=javascript%3A5348085037&project=4506155486085120&statsPeriod=90d)

Watching the [full replay makes](https://sentry.sentry.io/replays/412f724e31f54481a0170ffc0c73d8a0/?f_b_type=feedback&referrer=%2Ffeedback%2F&t=11.871400000035763&t_main=breadcrumbs) it easier to see that the widget showed some error message (text although redacted shows at the top) as opposed to changing to the toast. And user re-submitts. Resulting in dupliated feedback.

Reported on Slack by @gggritso

**Comment by billyvg** [comment]
@c298lee I think you've made some improvements to error handling. Do you know if this is still an issue? 

It sounds like we were catching an exception that occurs outside of feedback request and so despite successfully sending feedback, we display an error message and keep the feedback text.

**Comment by billyvg** [comment]
This should be fixed in 8.45.1
