### ISSUE TITLE
Template not updating

### ISSUE THREAD

**Issue by JohnMH** [getsentry/sentry#7086]
On my installation of Sentry, I've altered templates/sentry/layout.html, but nothing has changed. Is Django caching these templates? If so, how would I invalidate the cache?

**Comment by mattrobenolt** [comment]
It is cached, but it shouldn’t across process restarts. So just restart, and it should pick up whatever changes you make.

**Comment by JohnMH** [comment]
@mattrobenolt Thanks for the quick response, but I've already tried that with no result.

**Comment by mattrobenolt** [comment]
I'm not sure what you're trying to change then, but you might just not be changing anything that's used. Most of `layout.html` gets overridden by `templates/sentry/bases/react.html` which clobbers all of `<body>` and our main React app is loaded.

**Comment by JohnMH** [comment]
Alright, implemented a workaround anyway. Thanks!
