### ISSUE TITLE
Frontend runtime error when navigating to new User Feedback page

### ISSUE THREAD

**Issue by joshacheson** [getsentry/sentry#70887]
### Self-Hosted Version

24.2.0

### CPU Architecture

n/a (client issue)

### Docker Version

n/a (client issue)

### Docker Compose Version

n/a (client issue)

### Steps to Reproduce

1. Navigate to organizations/{org}/feedback

### Expected Result

See a list of submitted User Feedback

### Actual Result

Get this instead:

![image](https://github.com/getsentry/self-hosted/assets/1906888/cc3a7a2b-22e7-409b-86fb-8962e8fe83ce)

Stack trace from console:

![image](https://github.com/getsentry/self-hosted/assets/1906888/be42d230-7f84-4ad2-acec-9e45cc88e639)

Line 31 from FeedbackItem:

![image](https://github.com/getsentry/self-hosted/assets/1906888/79846850-1502-4a6a-9a68-276f58ffdec4)

**Comment by michellewzhang** [comment]
thank you for reporting @joshacheson! looks like we're trying to access a property on`tags` when it doesn't exist. hopefully this null check should fix the issue: https://github.com/getsentry/sentry/pull/71003

**Comment by billyvg** [comment]
Sounds like this is fixed by https://github.com/getsentry/sentry/pull/71003 -- please open a new ticket if you're still encountering this issue.
