### ISSUE TITLE
Cannot create ClickUp issue with the integration

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#70925]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Install the ClickUp integration
2. Open an issue
3. Click on the plus sign next to ClickUp issue under "Issue tracking"
4. Click on Save changes

### Expected Result

A ClickUp issue should be successfully created

### Actual Result

<img width="307" alt="Screenshot 2024-05-15 at 11 36 21" src="https://github.com/getsentry/sentry/assets/25980868/8ac5dcf0-5da0-4b44-86ad-1a774d82f72d">

<img width="824" alt="Screenshot 2024-05-15 at 11 36 52" src="https://github.com/getsentry/sentry/assets/25980868/9bfd38c4-527c-45c9-9934-4dd13b852832">

<img width="802" alt="Screenshot 2024-05-15 at 11 37 17" src="https://github.com/getsentry/sentry/assets/25980868/39294637-38df-4467-bec2-e5815a91cd32">

the issue is never created

### Product Area

Settings - Integrations

**Comment by scefali** [comment]
I can confirm from the integration dashboard of ClickUp that we are getting a 500 error on the request for that organization. That customer would need to reach out to ClickUp support to resolve this.
