### ISSUE TITLE
Alert for Metric won't load

### ISSUE THREAD

**Issue by bmulholland** [getsentry/sentry#70930]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

We created an alert for a metric a while ago, and now we can't view or change it.

To repro, just open https://recital.sentry.io/alerts/metric-rules/recital-backend/237346/#

### Expected Result

Page loads

### Actual Result

Infinite spinner

### Product Area

Alerts

### Link

https://recital.sentry.io/alerts/metric-rules/recital-backend/237346/#

### DSN

https://dcb648f7653e49c4b47e2eb60946c479@o419267.ingest.us.sentry.io/5495041

**Comment by ceorourke** [comment]
This is a duplicate of https://github.com/getsentry/sentry/issues/70730 so I'm going to close this, but we are looking into it!
