### ISSUE TITLE
Table sentry_email doesn't exist

### ISSUE THREAD

**Issue by cmmata** [getsentry/sentry#7096]
Hello,

I'm using Sentry 8.22.0 installed with the old python + virtualenv method. I have been using it for almost two years without problems. But today I wanted to add a second user to the Sentry organization and when the user gets the invite email and tries to register, he gets an error saying table "sentry_email" doesn't exist.

Like in #6587, looks like a database migration didn't work well. But looking at the database table `south_migrationhistory` I see the migrations added as if they worked.

id | app_name | migration | applied
-- | -------------- | ----------- | ---------- 
357 | "sentry" | "0342_projectplatform" | "2017-09-13 09:58:36.412536+02"
358 | "sentry" | "0343_auto__add_index_groupcommitresolution_commit_id" | "2017-09-13 09:58:36.837098+02"
359 | "sentry" | "0344_add_index_ProjectPlatform_last_seen" | "2017-09-13 09:58:37.425025+02"
360 | "sentry" | "0345_add_citext" | "2017-09-13 10:05:01.797217+02"
361 | "sentry" | "0346_auto__del_field_tagkey_project__add_field_tagkey_project_id__del_uniqu" | "2017-09-13 10:05:02.163942+02"
362 | "sentry" | "0347_auto__add_index_grouptagvalue_project_id__add_index_grouptagvalue_grou" | "2017-09-13 10:05:02.523747+02"
363 | "sentry" | "0348_fix_project_key_rate_limit_window_unit" | "2017-09-13 10:05:02.8735+02"
364 | "sentry" | "0349_drop_constraints_filterkey_filtervalue_grouptagkey" | "2017-09-13 10:05:03.419896+02"
365 | "sentry" | "0350_auto__add_email" | "2017-09-13 10:05:03.902622+02"
366 | "sentry" | "0351_backfillemail" | "2017-09-13 10:05:04.27675+02"

I have `sentry_projectplatform_last_seen` index of table `sentry_projectplatform` for example, from migration 0344. But don't have `sentry_email` table from 350.

So what do you recommend me to do?

**Comment by cmmata** [comment]
I have never developed in Python. Could please anyone tell me how to execute again failed migrations?

**Comment by cmmata** [comment]
Okay, found it. In case anybody is in the same situation, I ended up:
- deleting those entries in south_migrationhistory with `sentry django migrate sentry 0342`
- executing `sentry upgrade` again
- fixing errors like deleting tables / columns if the upgrade process says that already exists

The problem in my case was that 0345_add_citext failed because I didn't install postgresql-contrib library in the database server, so the `create table` with a `citext` column was failing and the first time I didn't notice. As `south_migrationhistory` had all the migrations, I didn't know they failed.

With the new upgrade process, I can add new members to the organization.

**Comment by daimon99** [comment]
I use this script to create the missing sentry_email table:
```
--
-- PostgreSQL database dump
--


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: sentry_email; Type: TABLE; Schema: public; Owner: sentry
--

CREATE TABLE public.sentry_email(
    id bigint NOT NULL,
    email character varying(75) NOT NULL,
    date_added timestamp with time zone NOT NULL
);


ALTER TABLE public.sentry_email OWNER TO sentry;

--
-- Name: sentry_email_id_seq; Type: SEQUENCE; Schema: public; Owner: sentry
--

CREATE SEQUENCE public.sentry_email_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sentry_email_id_seq OWNER TO sentry;

--
-- Name: sentry_email_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: sentry
--

ALTER SEQUENCE public.sentry_email_id_seq OWNED BY public.sentry_email.id;


--
-- Name: sentry_email id; Type: DEFAULT; Schema: public; Owner: sentry
--

ALTER TABLE ONLY public.sentry_email ALTER COLUMN id SET DEFAULT nextval('public.sentry_email_id_seq'::regclass);


--
-- Name: sentry_email sentry_email_pkey; Type: CONSTRAINT; Schema: public; Owner: sentry
--

ALTER TABLE ONLY public.sentry_email
    ADD CONSTRAINT sentry_email_pkey PRIMARY KEY (id);


-- PostgreSQL database dump complete
```
