### ISSUE TITLE
App Start - Change - Wrong foreground color

### ISSUE THREAD

**Issue by michaelmairegger** [getsentry/sentry#70970]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Within App Starts the CHANGE column shows wrong coloring. As you can see in the screenshot the Appstart reduces from 4.02s to 1.84s which is shown as -54.3% but the foreground color is red.

### Expected Result

Change foreground color: green

### Actual Result

![image](https://github.com/getsentry/sentry/assets/4341039/21d39045-0328-4367-98b1-a848bf3cc04e)

### Product Area

Performance

### Version

24.4.2

**Comment by narsaynorath** [comment]
Hi @michaelmairegger, this was fixed but it didn't make it into the most recent self-hosted version you're running. The next version should have the proper colour for the text. I'm going to close this issue, but if you still see that it hasn't propagated after an upgrade, please feel free to re-open this.

Thanks for your report!

**Comment by michaelmairegger** [comment]
@narsaynorath I can confirm that with 24.5.0 this issue is fixed.

Thank you!
