### ISSUE TITLE
Long emails on event details header are hard to copy

### ISSUE THREAD

**Issue by MaxBittker** [getsentry/sentry#7101]
it ellipsizes weirdly on click. 

example:
<img width="796" alt="screenshot 2018-01-29 13 48 41" src="https://user-images.githubusercontent.com/5915546/35536253-339c2f76-04fb-11e8-9bca-f6a6180d68f8.png">

it would be nice if the font was smaller or it made affordances for copy/paste

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
