### ISSUE TITLE
Message column missing in Events table

### ISSUE THREAD

**Issue by vektor330** [getsentry/sentry#7106]
We are using Sentry 8.22.0, installed directly on the server (no Docker).

When I open some issue and click the Events tab I see a table with columns like _ID_, _User_, _Browser_ etc. However, I can't see the _Message_ column - why is that? The search box even says "search event message or tags", so I'd assume the _Message_ column should be there.

The Message of my events is definitely being recorded correctly as I can see it in the issue detail.
<img width="1310" alt="screen shot 2018-01-30 at 13 22 11" src="https://user-images.githubusercontent.com/377878/35566328-476247fe-05c1-11e8-8088-b5ab1a3aeba6.png">
<img width="1309" alt="screen shot 2018-01-30 at 13 22 01" src="https://user-images.githubusercontent.com/377878/35566329-47c72836-05c1-11e8-813d-b6ac20bfef51.png">

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
