### ISSUE TITLE
can't undiscard

### ISSUE THREAD

**Issue by jongjunpark** [getsentry/sentry#71097]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. discard some issue (at 14-day free trial period)
2. 14-day later
3. hidden UI "Discarded Issues"
4. can't undiscard

### Expected Result

I want undiscard all issue.

### Actual Result

hidden "Discarded Issues" tab UI

### Product Area

Settings - Projects

### Link

https://imweb-ad-fe.sentry.io/settings/projects/javascript-nextjs/filters/data-filters

**Comment by JLuse** [comment]
@jongjunpark this is actually expected behavior, as delete & discard is only available for the Business plan and during trial periods. If you need a trial extension, please write into support@sentry.io for us to assist.
