### ISSUE TITLE
The tooltip in Sentry 24.5.0.dev0 is annoying

### ISSUE THREAD

**Issue by huyphams** [getsentry/sentry#71114]
### Self-Hosted Version

24.5.0.dev0

### CPU Architecture

x86_64

### Docker Version

25.0.4

### Docker Compose Version

v2.24.7

### Steps to Reproduce

Here are the corrected versions:

1. Click on the "Projects" link in the navigation bar.
2. Click on a project and look to the right in the latest releases section.
3. Hover the mouse over the newest release, and the tooltip will appear.
From now on, if you move the mouse out of the section to click the icon at the top to view all releases, the tooltip will still be there. Even though it is hidden, it still intercepts mouse clicks.

<img width="142" alt="Screenshot 2024-05-16 at 10 52 44 AM" src="https://github.com/getsentry/self-hosted/assets/3654622/2b811d13-34c7-4e5e-b392-2ff214389544">

Could not click the icon to see all releases even the tooltip is hidden.

<img width="364" alt="Screenshot 2024-05-16 at 10 52 54 AM" src="https://github.com/getsentry/self-hosted/assets/3654622/775586eb-4b1a-41eb-9988-722a2f547204">

### Expected Result

Can click the link when tooltip is closed.

### Actual Result

It show copied

### Event ID

N/A

**Comment by evanpurkhiser** [comment]
Fixed in https://github.com/getsentry/sentry/pull/71057
