### ISSUE TITLE
Alert Github PR author of suspect commit

### ISSUE THREAD

**Issue by chodges15** [getsentry/sentry#71127]
### Problem Statement

Assume a Sentry user merges a Github PR which gets pushed out to production and Sentry reports a new issue with a suspect commit. It is unlikely that the author will notice the suspect commit comment from the Sentry bot. 

Relying on auto-assignment of the Sentry issue for the notification is a little risky due to the [possibility](https://docs.sentry.io/product/issues/suspect-commits/#limitations) for Github API rate limits getting hit. Also, auto-assignment of Sentry issues may go to a team instead of an individual, and at the team level the alerts could be noisy causing the original PR author to miss the notification.

If suspect commits are missed and the issue isn't severe enough to trigger an alert, those going unnoticed will lead to stale issues indefinitely accumulating creating unnecessary noise.

### Solution Brainstorm

Given the high value of the information Sentry is surfacing here, it would be helpful to enable a targeted alert to the PR author when a suspect commit is identified. This would have the benefit of that author not having to manually look for new issues when their change rolls to production saving them time and making them more efficient.

A direct Slack message is orders of magnitude more likely to be seen and acted upon than a Github PR comment, and targeting it to the PR author ensures the person with the most context is brought in as soon as possible.

### Product Area

Alerts

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2177) by [Unito](https://www.unito.io)

**Comment by rachrwang** [comment]
One possible solution is a new workflow notification type to send notifications to the author of suspect commits

**Comment by chodges15** [comment]
@rachrwang In response to the question about suggested assignees, we think it would be most actionable if the original author was notified, versus a team that was auto-assigned the issue.

As we've thought about it, it would be even more helpful if there was some sort of threshold for this alert, so that PR authors aren't getting pinged for one-off errors in prod.

We believe this type of alert could drastically reduce time-to-detect for certain types of incidents.

**Comment by rachrwang** [comment]
Makes sense, thanks for sharing that context @chodges15 . We won't be able to get to this in the near term, though we'll update you as we have updates.

**Comment by chodges15** [comment]
We ended up putting together some Slack automation to ping the PR author. Closing since we have a workaround, but I would love to see better notifications for suspect commits in the future.
