### ISSUE TITLE
‘internal server error’ when uploading debug files

### ISSUE THREAD

**Issue by hak-ioki** [getsentry/sentry#71121]
### CLI Version

2.31.2

### Operating System and Architecture

- [X] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [ ] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)

### Operating System Version

macOS 14.4.1

### CLI Command

sentry-cli upload-dif "$DWARF_DSYM_FOLDER_PATH" 2>&1 >/dev/null --log-level=debug

### Exact Reproduction Steps

When I build the Xcode project, it can't upload the symbols. Here is the summary of the logs:

```
> Found 123 debug information files
> Prepared debug information files for upload
> File processing complete:

    ERROR Common
        internal server error
    ERROR CommonAirship
        internal server error
    ERROR DBFFM
        internal server error

Error: some symbols did not process correctly
error: sentry-cli exit with 1

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
```

### Expected Results

Should upload debug files successfully.  I saw two[[1](https://github.com/getsentry/sentry-cli/issues/1745), [2](https://github.com/getsentry/sentry-cli/issues/1742)] different issues that are related to our [issue](https://github.com/getsentry/sentry-cli/pull/1749), and I uploaded sentry-cli after I saw this fix, but it didn't work again.

### Actual Results

It couldn't upload debug files.

### Logs

[detailed-logs.zip](https://github.com/getsentry/sentry-cli/files/15352683/detailed-logs.zip)

**Comment by szokeasaurusrex** [comment]
More details are provided on https://github.com/getsentry/sentry-cli/issues/2068, which was closed in favor of this issue

**Comment by hak-ioki** [comment]
@szokeasaurusrex, my last try was successful and I'm not sure why, maybe it was a temporary issue, but for the last 10 minutes, it worked :)  I appreciate your help. The last error disappeared on the website, sorry for the confusion. So, I'm closing the issue.
