### ISSUE TITLE
Issue Stream's Header Row confused when rapid selecting an issue

### ISSUE THREAD

**Issue by MichaelSun48** [getsentry/sentry#71134]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Double click an issue in rapid succession 
2. Observe the items in the header get wonky. Column labels disappear when nothing is selected, and reappear when an issue is selected. 

### Expected Result

Column labels should always be visible when nothing is selected, and bulk modification drop downs (Resolve, Archive, Set Priority) should always be visible when 1 or more issues are selected, regardless of how rapidly the issue is clicked. 

### Actual Result

Header row is just empty when nothing is selected: (Expected behavior is for column labels to be visible) 
<img width="2030" alt="image" src="https://github.com/getsentry/sentry/assets/55160142/2f56b380-ae39-4cf5-803c-c734b31f7ca7">

Column labels appearing when issue is selected: (Expected behavior is for bulk modification drop downs to be visible)
<img width="2032" alt="image" src="https://github.com/getsentry/sentry/assets/55160142/41afeea8-e031-43d7-9166-8aac571e502c">

### Product Area

Issues

**Comment by jangjodi** [comment]
I was able to replicate this issue, but only in the Sentry org and not my personal org. This may be related to some feature in LA
