### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by mqklin** [getsentry/sentry#71171]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

![image](https://github.com/getsentry/sentry/assets/9456433/3c284a70-d422-4f41-9777-2663ea14c154)

Hello. Our organisation is https://sanr.sentry.io/. We installed Github integration (check the screenshot above), but Sentry still doesn't consider it as installed:
![image](https://github.com/getsentry/sentry/assets/9456433/9baa8809-e0c5-430e-86e1-badb15307da3)

### Expected Result

Github integrated

### Actual Result

Github is not integrated

### Product Area

Settings - Integrations

**Comment by dalnoki** [comment]
Hi @mqklin Thanks for reaching out! I'd recommend removing Sentry from GitHub's side at https://github.com/settings/installations and start the whole installation process from Sentry's side again as explained in [this](https://docs.sentry.io/product/integrations/source-code-mgmt/github/) document. Let me know if that helps!
