### ISSUE TITLE
Create alerts with breadcrumbs filtering

### ISSUE THREAD

**Issue by gabrielgarciagava** [getsentry/sentry#71215]
### Problem Statement

I would like to be able to create alerts that filter recent occurrence of specific breadcrumbs.

Example:
Define your metric -> Number of errors
Filter -> Contains breadcrumb X in the last 10 breadcrumbs
Threshold -> Critical above 300
Set action -> Send email

### Product Area

Alerts

**Comment by Dhrumil-Sentry** [comment]
Thanks for this feature request, We currently have no plans to build this. Querying on breadcrumbs to support alerting is a massive effort for and we're unlikely to take this on
