### ISSUE TITLE
HTTPS url behind a proxy are reported as HTTP url

### ISSUE THREAD

**Issue by sylfabre** [getsentry/sentry#7122]
I'm using `sentry/sentry` version 1.8.2 on PHP and `sentry/sentry-symfony` version 2.0

This issue https://sentry.io/assoconnect/php/issues/445316669/ reports a bug on http://www.assoconnect.com/demo-initiactive-95/master/abonnements/nouveau/37128 but the user was on https://www.assoconnect.com/demo-initiactive-95/master/abonnements/nouveau/37128 (notice http vs https)

My webserver is behind a proxy and according headers are sent:
![image](https://user-images.githubusercontent.com/3177556/35621169-b7499db6-0683-11e8-94d2-d14f45cf9496.png)

Sentry should report the url with https instead of http.

I've noticed this issue while searching for the sentry report using the https url provided by the user

![image](https://user-images.githubusercontent.com/3177556/35621221-e9c35e9e-0683-11e8-8726-e4f33d815f35.png)

![image](https://user-images.githubusercontent.com/3177556/35621229-f495e8dc-0683-11e8-8f21-a7af2e7c75d6.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by sylfabre** [comment]
@BYK This is still an issue for us

**Comment by BYK** [comment]
@sylfabre - do you have the following settings in your config:

https://github.com/getsentry/onpremise/blob/e9cff2e28867eda078b3d3b103aae68252e19d91/sentry/sentry.conf.example.py#L217-L229

Also you haven't mentioned which version of Sentry you are using.

**Comment by sylfabre** [comment]
@BYK Thank you for your answer.

I'm using PHP with:
* sentry/sdk: 2.2.0
* sentry/sentry: 2.5.0
* sentry/sentry-symfony: 3.5.2

The Sentry server is the online one at sentry.io
As I'm not using on-premise Sentry, I'm not sure that the link you have provided is relevant to my use-case, or I don't understand what I should do

**Comment by BYK** [comment]
>As I'm not using on-premise Sentry, I'm not sure that the link you have provided is relevant to my use-case, or I don't understand what I should do

If you are not using self-hosted Sentry, that link is irrelevant. If you are using sentry.io on a paid plan, I urge you to contact our support to get faster and dedicated support: https://sentry.io/contact/support/

If you are not on a paid plan, I'll try to look into this when I have time.

**Comment by sylfabre** [comment]
@BYK Ok thank you, I'll contact the support
