### ISSUE TITLE
Missing user data from issue event

### ISSUE THREAD

**Issue by lucas-zimerman** [getsentry/sentry#71246]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Set a custom user data, the data is sent and also stored on Sentry (as  you can see on the actual result ) but the user interface hides the custom data.

### Expected Result

the user context to show the additional user data set by the user.

### Actual Result

https://[us.sentry.io/api/0/projects/sentry-sdks/sentry-capacitor/events/c15bc11c29a842488d8891b37416a211/json/](https://us.sentry.io/api/0/projects/sentry-sdks/sentry-capacitor/events/c15bc11c29a842488d8891b37416a211/json/)
![image](https://github.com/getsentry/sentry/assets/8229322/fba368d1-beb8-4534-b5c6-fd496f0e4e42)

https://sentry-sdks.sentry.io/issues/5061824231/events/351f306ce50c401694c2bb040b80546f/?project=5522756
![image](https://github.com/getsentry/sentry/assets/8229322/7fb6e892-5083-4b30-977b-b9e96de91985)

### Product Area

Issues

**Comment by leeandher** [comment]
Thanks for reporting this! I've found the issue and will be working on a fix to roll out within the week.
