### ISSUE TITLE
Metrics with unit names exceeding length limit (15 chars) don't appear in Sentry

### ISSUE THREAD

**Issue by philipphofmann** [getsentry/sentry#71323]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

This problem initially appeared on the Cocoa SDK (https://github.com/getsentry/sentry-cocoa/issues/3999), but while investigating, I realized it also happens for the Python SDK, so my assumption is that it's not SDK-related.

Capture the following metrics with the Python SDK or the Cocoa SDK:
```Python
# Does NOT end up in Sentry
sentry_sdk.metrics.incr(
    key="inc_with_custom_unit_underscores",
    value=1,
    unit="custom_unit_underscores",
)

# Ends up in Sentry
sentry_sdk.metrics.incr(
    key="inc_with_custom_unit_without_underscores",
    value=1,
    unit="myCustomUnit",
)

# Does NOT end up in Sentry
sentry_sdk.metrics.set(
    key="set_with_custom_unit_underscores",
    value="3",
    unit="custom_unit_underscores",
)

# Ends up in Sentry
sentry_sdk.metrics.set(
    key="set_with_custom_unit_without_underscores",
    value="3",
    unit="myCustomUnit",
)
```

It's worth noting that the `_` is allowed for units; see [develop docs](https://develop.sentry.dev/sdk/metrics/#normalization). 

### Expected Result

All metrics show up in Sentry.

### Actual Result

Only metrics without using the `_` custom unit appear in Sentry.

### Product Area

Other

**Comment by kahest** [comment]
The root cause of this is that unit names are restricted to a maximum length of 15 chars, see docs: https://develop.sentry.dev/sdk/metrics/#maximum-lengths

Currently, measurements exceeding this limit are dropped. We plan to change this to automatically truncate unit names instead.

**Comment by philipphofmann** [comment]
> We plan to change this to automatically truncate unit names instead.

Truncate them where, @kahest?

**Comment by kahest** [comment]
> > We plan to change this to automatically truncate unit names instead.
> 
> Truncate them where, @kahest?

I think in Relay, as per @Dav1dde's suggestion
