### ISSUE TITLE
Google Cloud Function / Express : raven@2.4.0 alert: failed to send exception to sentry: socket hang up

### ISSUE THREAD

**Issue by pvdyck** [getsentry/sentry#7139]
-  Versions : "raven": "2.4.0", "raven-js": "3.22.1",
- Express /  NodeJS
- Google cloud function environment

Hi, I am getting socket timeouts on a very simple function : 

const app1 = express();

raven.config('https://****',{}).install();

app1.use(raven.requestHandler());
app1.use(raven.errorHandler());
app1.get('/', function (req, res) {
    throw new Error();
});

Do you confirm that Sentry works on Google Cloud / Firebase engine ?

Thanks

**Comment by bjornbjorn** [comment]
I'm getting this one as well - did you resolve it @pvdyck ?

I get some exceptions from cloud functions logged to Sentry, but if I check my cloud functions log I see it's full of "raven@2.6.3 alert: failed to send exception to sentry: socket hang up" errors.

**Comment by andreas-** [comment]
Firebase Cloud Functions are not able to call external links when running on Spark Plan (free). Please verify that you are using a paid plan Flame or Blaze.

I hope this helps.

**Comment by markstory** [comment]
If you're having socket timeout issues that sounds like hosting issue and not something specific to the raven client. You should verify that your cloud function can do external HTTP requests like @andreas- suggested.
