### ISSUE TITLE
[Hydration Errors] Add setting to "create hydration errors from replays"

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#71396]
similar to `sentry:replay_rage_click_issues`

When the user goes to a page like https://sentry.sentry.io/settings/projects/javascript/replays/ they should see a new checkbox that says something like "Toggles whether or not to create Session Replay Hydration Issues"

![Image](https://github.com/getsentry/sentry/assets/187460/a5750ccf-5c99-4870-841a-519568d5dcef)

**Comment by aliu3ntry** [comment]
Need to add to UI
