### ISSUE TITLE
Remember selected exception displaying mode between errors

### ISSUE THREAD

**Issue by szpak** [getsentry/sentry#7140]
It is possible to switch between "App Only", "Full" and "Raw" exception presentation modes in UI. However, that information is not persisted (in the browser/session) and willing to see "raw" exceptions every time is it required see switch to it in every error.

It would be useful to stick with selected mode (e.g. "raw") across all browsed errors.

Tested with Sentry 8.22.0.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by szpak** [comment]
I still think it is an useful feature for people usually using the raw mode on a daily basis.

**Comment by BYK** [comment]
@szpak I don't think anyone from the team would take this on any time soon. Would you like to try submitting a PR for this?

**Comment by szpak** [comment]
Unfortunately, I'm not a frontend developer and it would be hard for me to implement it :-(.

**Comment by BYK** [comment]
@taylangocmen I've seen you working on the new Inbox interface. Is this something relevant there?
