### ISSUE TITLE
Organization name doesn't change on project page / emails /slack alerts

### ISSUE THREAD

**Issue by rdeavila** [getsentry/sentry#7142]
On sentry.io, when I change the organization name (not the short name) in the settings page, this name is not reflected on any other place, like project page, slack alerts, email alerts, etc. 

- The version of Sentry you're using: The current version available on https://sentry.io

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by BYK** [comment]
I _think_ this is fixed by the way.
