### ISSUE TITLE
`<< unparameterized >>` page in web vitals that only has INP

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/sentry#71435]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

https://sentry.sentry.io/performance/browser/pageloads/overview/?project=-1&statsPeriod=24h&transaction=%3C%3C+unparameterized+%3E%3E

### Expected Result

This page does not exist

### Actual Result

![image](https://github.com/getsentry/sentry/assets/18689448/ef2c2f9d-71cb-480c-bb40-97e64ee4351d)

I assume this is because of some ingest problems with metrics extraction.

### Product Area

Performance

### Link

https://sentry.sentry.io/performance/browser/pageloads/overview/?project=-1&statsPeriod=24h&transaction=%3C%3C+unparameterized+%3E%3E

**Comment by jjbayer** [comment]
@AbhiPrasad the `<< unparametrized >>` only showed up in metrics, right? Or did you also find an indexed span that had it?

Can you point me to the place in the SDK where the interaction span is emitted so we can build a repro case?

**Comment by AbhiPrasad** [comment]
Here is where the span is constructed: https://github.com/getsentry/sentry-javascript/blob/0ac519aa8c583268ae613d41c30106cd832968c8/packages/browser-utils/src/metrics/inp.ts#L98-L117

and here is an example of the payload: https://github.com/getsentry/sentry-javascript/blob/0ac519aa8c583268ae613d41c30106cd832968c8/dev-packages/browser-integration-tests/suites/tracing/metrics/web-vitals-inp/test.ts#L72-L96

**Comment by AbhiPrasad** [comment]
@edwardgou-sentry should we only send INP if there is a valid transaction name on the span?

**Comment by AbhiPrasad** [comment]
For now can we just drop these in Relay, or hide them in the product somehow? This is just bad product experience, and users will run into it with older sdk versions even if we patch the SDK.

**Comment by jjbayer** [comment]
> For now can we just drop these in Relay

We could, yes, but a filter in the product might make more sense (more flexible).

**Comment by edwardgou-sentry** [comment]
We merged in the product change to filter out any `<< unparameterized >>` transaction names from surfacing in the web vitals UI.

I also have a PR for the JS sdk that mitigates this issue further. There was a bug with how we were picking up transaction names, which often lead to `undefined` values. The PR will reduce the odds of that happening:
https://github.com/getsentry/sentry-javascript/pull/12358
