### ISSUE TITLE
Installation grant code is not provided during oAuth

### ISSUE THREAD

**Issue by leesh22** [getsentry/sentry#71440]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Auth via API 

### Expected Result

We get a grantcode 

### Actual Result

We are not getting the grant code back in the payload when we are requesting auth via oAuth. Payload does exist with `installation_id=.` but for some reason sentry hasn't included the code here (which is nullable). 

### Product Area

APIs

**Comment by JoshFerge** [comment]
thanks for reporting @leesh22 -- this should be fixed now. let us know you run into any other issues.
