### ISSUE TITLE
Slack integration auth issue

### ISSUE THREAD

**Issue by rohitdhas** [getsentry/sentry#71448]
### Self-Hosted Version

24.1.0

### CPU Architecture

x86_64

### Docker Version

26.1.1

### Docker Compose Version

v2.27.0

### Steps to Reproduce

Click `Settings > Integrations > Slack > Add Workspace`

I encountered an error stating that the redirect URI didn't match any configured URIs. Passed URI: `http://<server_ip_addr>:9000/auth/slack.callback.`

I have added the Redirect URL in Slack, which is now `https://<server_ip_addr>:9000/auth/slack.callback.` because Slack only supports HTTPS. However, I'm still facing the issue.

### Expected Result

redirect uri should have `https` instead of `http`.
Found similar issue - https://github.com/chsasank/outline-wiki-docker-compose/issues/34

### Actual Result

<img width="717" alt="Screenshot 2024-05-16 at 1 26 36 PM" src="https://github.com/getsentry/self-hosted/assets/53969450/1d5ab6a7-121d-48b7-8b3c-ab95d0e564ed">

**Comment by Dhrumil-Sentry** [comment]
Thanks for this report, we're adding this to our backlog and we'll comment here as we have any updates

**Comment by iamrajjoshi** [comment]
Unfortunately the team is understaffed and we can’t prioritize this fix but we’re always open to community contributions.
