### ISSUE TITLE
"Change status to unresolved" text bubble doesn't go away after unignoring

### ISSUE THREAD

**Issue by LewisJEllis** [getsentry/sentry#7145]
On Sentry.io, when viewing an ignored issue, hovering over the "unignore" button causes a "Change status to unresolved" text bubble. If I then click the button, that text bubble sticks around even as I move my mouse elsewhere, and even through navigation to other views. I am able to reproduce this consistently.

Here is a screenshot of the bubble persisting after I return to the issue list view:
<img width="369" alt="screen shot 2018-02-01 at 11 45 28 am" src="https://user-images.githubusercontent.com/1445984/35701175-0ab582aa-074a-11e8-9cf7-2ad05b69e42e.png">

**Comment by mattrobenolt** [comment]
:wave:

**Comment by sksembhi** [comment]
hi lewlew
