### ISSUE TITLE
[Crons] Ui error banner with no context and nothing in the dropdown

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#71499]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Send crons event with something invalid like an invalid monitor slug
2. Go to Crons page in org.
3. See this error banner - 
<img width="1262" alt="Screenshot 2024-05-24 at 1 09 13 PM" src="https://github.com/getsentry/sentry/assets/96670625/f8c3f7fe-8286-416b-869d-a07526988cfa">

4. Hit Dropdown and see no extra details -
<img width="1266" alt="Screenshot 2024-05-24 at 1 08 34 PM" src="https://github.com/getsentry/sentry/assets/96670625/75a7ae29-e4bd-4e50-895b-67b623444f93">

[Link to where banner can be seen in my org.](https://francisorg.sentry.io/crons/?project=4504039154974720&statsPeriod=14d)

### Expected Result

Errors on ingest should display properly

### Actual Result

Nothing is displayed when dropped down. I have both rate limit errors and invalid monitor errors in my org.  [Link to my stats page showing dropped check in events](https://francisorg.sentry.io/stats/?dataCategory=monitor+check-ins&project=4504039154974720&statsPeriod=14d).

I looked at several orgs, and It only seems to work properly in our main Sentry org.

### Product Area

Crons

**Comment by davidenwang** [comment]
Thanks @Fwang36 for pointing this one out. This was an oversight on my end, and I have the fix here: https://github.com/getsentry/sentry/pull/71566, once that is merged in this behavior should be fixed!
