### ISSUE TITLE
Sentry User feedback button Disappears after rendering in next.js

### ISSUE THREAD

**Issue by GrowWidTalha** [getsentry/sentry#71506]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. clone this repo https://github.com/GrowWidTalha/portfolio
2. run the development server
3. open localhost:3000

### Expected Result

The user feedback button should appear in the bottom right corner

### Actual Result

The user feedback button appears for a second but then gets dissappear. 

### Product Area

User Feedback

**Comment by bruno-garcia** [comment]
Thanks for the repro - we'll take a look at this

**Comment by bruno-garcia** [comment]
I peeked at ur demo but couldn't find the init block for the backend and frontend. Could u share a link to those please?

**Comment by GrowWidTalha** [comment]
I fixed it. I just set the auto inject to false and injected it using use
effect and it worked

**Comment by bruno-garcia** [comment]
Good to hear! thanks for letting us know
