### ISSUE TITLE
Hi hi, wondering if you could help me out. I have an on premise instance of Sentry on my amazon server (it runs Centos 7). It looks fine, I have cron and worker running and the background worker warning isn't showing up. I can create projects and post errors, but for some reason, I cannot change the settings of the projects or remove the project at all. Whenever I press Save Changes or Remove Projects it just loads, times out, and says it didn't send any data. Please help!

### ISSUE THREAD

**Issue by mattrix27** [getsentry/sentry#7150]
## General Support

If you're looking for general support, please utilize our [community forum](https://forum.sentry.io/) rather than GitHub Issues.

## Reporting Bugs

When reporting bugs, include details about your configuration, such as:

- The version of Sentry you're using
- Whether you're using Docker or another installation method
- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration when relevant

**Comment by mattrix27** [comment]
Oh by the way, I installed Sentry through a python environment and I have a HTTPS proxy set up

**Comment by MaxBittker** [comment]
hi @mattrix27, this sounds like a configuration problem, so unless you can give us a stacktrace or something minimal and reproducible, the correct place to get help would be the forum: https://forum.sentry.io/
Hope you can get everything working!

**Comment by MaxBittker** [comment]
one place to start would be viewing the content and response code of the xhr request in your network tab
