### ISSUE TITLE
Instructions for self-hosted metrics?

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#71517]
On self-hosted, it is not immediately clear how to enable metrics. Should we provide instructions on how to do this in some area of the docs or make sure that it works out of the box? (maybe this is planned for GA)

**Comment by aldy505** [comment]
It's here already: https://github.com/getsentry/self-hosted/issues/2698

On self-hosted, anything that's an upcoming feature should be tracked on issues. It's even described on the docs https://develop.sentry.dev/self-hosted/#enabling-preview-features
