### ISSUE TITLE
Style - z-index in div element

### ISSUE THREAD

**Issue by gmalca-sperant** [getsentry/sentry#71542]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

<img width="1179" alt="image" src="https://github.com/getsentry/sentry/assets/98062282/90ab96f1-670d-46e7-9953-c2d746f6320a">

<img width="1170" alt="image" src="https://github.com/getsentry/sentry/assets/98062282/b1eaee47-e3e1-4df2-873a-3001e6605766">

### Expected Result

The style of the element should allow the element to be hidden when it passes through the StickyActions

### Actual Result

The style of the element is not allowing the element to be hidden when it passes through the StickyActions

### Product Area

Issues

**Comment by MichaelSun48** [comment]
Thanks for the callout @gmalca-sperant! I just put up a fix for this, so you should see it reflected soon!
