### ISSUE TITLE
Stats are not showing up

### ISSUE THREAD

**Issue by nickheiner-usds** [getsentry/sentry#7155]
I am running Sentry `8.14` via https://github.com/getsentry/onpremise at 699d2ef2a0dd1081dc81cdb08ac7069b493a4948. I'm using Docker. I have a steady stream of events that I can see, but stats don't appear to be showing up: 

![image](https://user-images.githubusercontent.com/25331532/35748701-e8d54854-081c-11e8-9ad9-c7c1cf5ba89e.png)

![image](https://user-images.githubusercontent.com/25331532/35748708-ef7f38cc-081c-11e8-9b51-472bfb041ad3.png)

Here are some events:

![image](https://user-images.githubusercontent.com/25331532/35748730-016db8b0-081d-11e8-8d9a-9fa7566e2ee1.png)

I didn't see anything in `docker logs` that seemed immediately troubling.

If you let me know what specific parts of my config would be useful to post, I can provide them.

If I hit https://sentry.ds.va.gov/api/0/projects/{slug}/events/, I see `100` events on the first and second pages.

If I hit https://sentry.ds.va.gov/api/0/organizations/department-of-veterans-affairs/stats/?stat=received&since=1517509913&until=1517596313&resolution=1h, I see a mostly empty response:

```json
[[1517508000.0, 0], [1517511600.0, 0], [1517515200.0, 0], [1517518800.0, 0], [1517522400.0, 0], [1517526000.0, 0], [1517529600.0, 0], [1517533200.0, 0], [1517536800.0, 0], [1517540400.0, 0], [1517544000.0, 0], [1517547600.0, 0], [1517551200.0, 0], [1517554800.0, 0], [1517558400.0, 0], [1517562000.0, 0], [1517565600.0, 0], [1517569200.0, 0], [1517572800.0, 0], [1517576400.0, 0], [1517580000.0, 0], [1517583600.0, 0], [1517587200.0, 0], [1517590800.0, 3], [1517594400.0, 1]]
```

What could be going on here? How can I troubleshoot this issue? Would upgrading to `8.22` help? I didn't see much in the changelog that seemed relevant.

**Comment by BYK** [comment]
Closing due to staleness and 8.14 is not even a thing anymore. Feel free creating a new issue if you still have this with more recent versions.
