### ISSUE TITLE
Incorrect Exception raised

### ISSUE THREAD

**Issue by dimoschi** [getsentry/sentry#71561]
As the `get_blended_sample_rate` can return either `float | None` raising an Exception on None is misleading and creates confusion. The None case of `get_blended_sample_rate` could be handled using a default value.

https://github.com/getsentry/sentry/blob/41a2e0a3dd8048c41d551d7301709ea0600d1c59/src/sentry/dynamic_sampling/rules/base.py#L51

**Comment by jjbayer** [comment]
@matejminar could you please have a look at this? Thanks!
