### ISSUE TITLE
Add request tracking

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#716]
For events, we should record the following in frameworks where it's easy:
- generate a request id (uuid)
- record time since request start

This will let us say "this error happened 300ms into the request, and is linked with these 3 other events from the same request".

**Comment by TheSavior** [comment]
This would be amazing. We have access to the request id for a given request from our backend services, web server, all the way to our client JavaScript. It would be great if we could send the request id along with our errors and be able to see all errors for a given request across our entire stack.

**Comment by bjeanes** [comment]
The dream here would be able to pull the Request-ID from the HTTP response in JS errors too, so that we could show X backend error likely caused Y frontend error.

**Comment by ramsrib** [comment]
It would be nice if the framework provides straight-forward way to track the requests (by generating and setting the request id in the event metadata) and providing support to search/filter it in UI.

Or if we've to do it manually, then the sentry UI should support search by tags or other metadata (extra) across projects. Right now, sentry lacks this most important feature: `Global search` (or Search across projects). Also sentry doesn't support searching using `extra` data.

**Comment by BYK** [comment]
This is now available under https://docs.sentry.io/product/performance/
