### ISSUE TITLE
user reporting dialog: name color invisible

### ISSUE THREAD

**Issue by michaeldrob** [getsentry/sentry#7162]
using JS sentry reporting. basic setup. I wanted to play around with user reporting dialog and when I bring it up, I notice when I type into the name field, it's blank. Other fields are fine. Seems the color property is not defined in the CSS. Selecting the field with the mouse reveals the text (see screenshots)

<img width="683" alt="screen shot 2018-02-03 at 11 40 23 am" src="https://user-images.githubusercontent.com/16999036/35769556-fa187cb2-08da-11e8-8e02-7e0d1035881b.png">
<img width="684" alt="screen shot 2018-02-03 at 11 40 33 am" src="https://user-images.githubusercontent.com/16999036/35769557-fa20919a-08da-11e8-9cfc-5c0ca17adad3.png">

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

This should be fixed anyway.
