### ISSUE TITLE
Use the format "<function> at <filename>:<linenumber>" for stacktrace lines

### ISSUE THREAD

**Issue by tsondergaard** [getsentry/sentry#7164]
The stacktrace formatting would be much better (imho) if the function was listed first followed by filename and line number information. Just as gdb and many other debuggers do. The function name carries much more information that the source filename, which is why it should be first. Also for brevity just use <filename>:<linenumber> instead of " at line <linenumber>". Stacktraces contains lots of information so best to eliminate unnecessary text.

**Comment by billyvg** [comment]
Good idea, I would go further and say there should be a customizable template, since everyone has opinions.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
