### ISSUE TITLE
Include Timestamp on Issue Public Share page

### ISSUE THREAD

**Issue by keithbrink** [getsentry/sentry#71642]
### Problem Statement

When I share an event with a public link, there is no timestamp, which makes it a lot less useful. Could you add the event timestamp to the public share page?

### Product Area

Issues

**Comment by mrduncan** [comment]
Hi @keithbrink, since issues often have multiple events are you referring to the timestamp of the latest event?

**Comment by keithbrink** [comment]
That would be fine, or the timestamp of the event that I click the share button on.

**Comment by mrduncan** [comment]
Thanks! I've added this to our backlog - for transparency this isn't a super commonly used feature so it's not high on the priority list but it's likely a relatively quick add when we have a chance since we already have the last event timestamp available in the API response.
