### ISSUE TITLE
Improve thread navigation

### ISSUE THREAD

**Issue by tsondergaard** [getsentry/sentry#7165]
Thread navigation in sentry is a little difficult. The following would be great improvements

* Highlight the currently displayed thread in the combobox
* Provide next/previous thread buttons for navigating through threads
* Provide keyboard shortcuts for the thread next/previous buttons

**Comment by alexanderkaraivanov-at-karoshealth-com** [comment]
Currently, it is not so easy visually which thread crashed. It might be better just to put it on top.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by tsondergaard** [comment]
Please reconsider this issue. It is an easy fix and would help a lot!

**Comment by BYK** [comment]
@priscilawebdev generously offered to take this on!

**Comment by MichaelSun48** [comment]
I can't tell if/how this was resolved, but I'm going to close this due to >3 years of inactivity. Feel free to reopen if this is still an issue.

**Comment by tsondergaard** [comment]
It was fixed very recently. Thanks!
