### ISSUE TITLE
Crons: Support February 29th schedules

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#71663]
Croniter doesn't support iterating backward to February 29th.

We've validated against schedules like this now since https://github.com/getsentry/sentry/pull/71661

But really this should be supported. We'll need to either wait for an upstream fix, or implement a patch and get it upstreamed ourselves. 

See https://github.com/taichino/croniter/issues/55

This is similar to #66868

**Comment by wedamija** [comment]
Closing this since we no longer use croniter, @evanpurkhiser lmk if we should reopen
