### ISSUE TITLE
Autocomplete for Replay Index Search does not work as expected

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#71662]
## Problem

The autocomplete suggestions in the search box are not filtered based on what is being typed. For example, for `user.email`, if I type `user.email:j`, I still see results without `j`.

**Comment by michellewzhang** [comment]
duplicate of [Replay Search: Typeahead doesn't filter down matching values as you type](https://github.com/getsentry/sentry/issues/60025)
