### ISSUE TITLE
I wish I could link the Replay content to other UI test libraries like playwright.

### ISSUE THREAD

**Issue by bkkoli** [getsentry/sentry#71738]
### Problem Statement

There is no way to connect Replay contents with  other UI test libraries

### Solution Brainstorm

I think we need an export button to Playwright or Puppeteer at the top of the replay.

### Product Area

Replays

**Comment by bruno-garcia** [comment]
Thanks for raising this! We considered this in past brainstorming sessions but never opened a ticket.

@ryan953 had some idea how we could achieve this

> 1. read list of click & keyboard breadcrumbs
> 2. reformat it into a string of playwright code
> 3. download button, or copy+paste that string in the UI… done!

Is that something you'd like to contribute a PR for @bkkoli ?

**Comment by billyvg** [comment]
This is a pretty neat idea but it's a bit outside of our product scope. I could see this being a feature down the line if we added support for exporting replays (e.g. as movie, json, etc). But as of right now this is not something we're intending to implement.
