### ISSUE TITLE
GitLab Integration Problem

### ISSUE THREAD

**Issue by acoyfellow** [getsentry/sentry#71739]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Trying to add a Gitlab.com account, getting "Unexpected Error"

### Expected Result

Connecting my Repo to my gitlab private account

### Actual Result

<img width="1049" alt="image" src="https://github.com/getsentry/sentry/assets/1666099/de3a6486-82e4-495d-a38b-9f03dab29580">

### Product Area

Issues

### Link

https://sentry.io/extensions/gitlab/setup/?completed_installation_guide

### DSN

https://243f520be2cfb839a848aa5aab698838@o4507340186124288.ingest.us.sentry.io/4507340232261632

**Comment by sentaur-athena** [comment]
@acoyfellow gitlab integration is only available to repositories under group account: https://docs.sentry.io/organization/integrations/source-code-mgmt/gitlab/
