### ISSUE TITLE
"Some of your projects have been omitted from query performance analysis" banner erroneously appears on every project with transactions

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#71742]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to a project with transactions
2. See banner implying that queries are disabled for the project.

Example and ([link](https://francisorg.sentry.io/performance/database/?project=-1&statsPeriod=90d)) from my org showing all my projects have been disabled - 
<img width="1253" alt="Screenshot 2024-05-30 at 9 43 12 AM" src="https://github.com/getsentry/sentry/assets/96670625/351b0b3a-5a58-48d7-a385-0e3564cc9d78">

I don't see the behavior in Sentry org, but I've seen it in every other org I've checked so far.

### Expected Result

Banner should not be there

### Actual Result

Banner is there

### Product Area

Performance

**Comment by gggritso** [comment]
@Fwang36 all good now! Sorry for the disruption

**Comment by gggritso** [comment]
Fixed in https://github.com/getsentry/getsentry/pull/14148
