### ISSUE TITLE
Send events from relay-server to proxy and then to Sentry

### ISSUE THREAD

**Issue by revathyrams** [getsentry/sentry#71812]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I have a sentry instrumented PHP service that sends events to the sentry-relay server. I need to setup a proxy server in between relay and Sentry. The proxy server exists because it needs needs to transform Sentry traces to open telemetry and send to otel collector. So the proxy will forward the request as it is to Sentry, but transform to otel and send to otel collector.

<img width="1098" alt="relay-proxy-design" src="https://github.com/getsentry/sentry/assets/12392774/6c13e645-e4f1-4152-a2ea-f657ae109871">

### How are you getting stuck?

When I forward the request from the proxy server to Sentry, it fails with a 500
```
{"detail":"bad envelope authentication header","causes":["expected value at line 1 column 1"]}
```
I think this is happening because the `dsn` in the envelope points to the proxy-server's address and not `sentry.io`, since the upstream route of relay-server is the proxy-server  `"http://<redacted>:@localhost:3000/<redacted>"`

This would mean that I have to decode the event, replace the dsn, and then encode and make an http request. 
Is there an easier method to achieve this? Is there a drop-in replacement instead of modifying the header/payload? 

### Where in the product are you?

Settings - Relay

**Comment by jjbayer** [comment]
@revathyrams thanks for the report! This response is emitted when there's a parsing error. Do you have an example payload of what your proxy sends to Sentry?

https://github.com/getsentry/relay/blob/38a79bddeab0d9e653cf28292007fab5e0b6511e/relay-server/src/endpoints/envelope.rs#L103

**Comment by revathyrams** [comment]
Hi @jjbayer! It was a malformed payload, thank you. We got past that now. But I do have another question.

In my new proxy-server, is it sufficient to expose the endpoints listed here - https://docs.sentry.io/product/relay/operating-guidelines/#request-routing
Are there any endpoints not listed here or were added recently? I'm asking because we're seeing some "dropped envelope" errors.

**Comment by Dav1dde** [comment]
The list is a bit outdated for what routes Relay does serve and accepts data from. But it should be enough for your setup, Relay itself only forwards data using a smaller set of routes which are all included in the list.

Best if you run Relay with trace logs and post them here, also your configuration is of interest, managed Relays behave different from static/proxy and do require different configurations.

**Comment by jjbayer** [comment]
@revathyrams I updated the list (https://github.com/getsentry/sentry-docs/pull/10349).

> also your configuration is of interest, managed Relays behave different from static/proxy and do require different configuration

In your case, _if_ you are running a managed Relay you might also need to expose the private endpoints Relay uses for inter-relay communication listed [here](https://github.com/getsentry/relay/blob/d19b1b1e2cadd68de8b4fc24d21fd7a38acb5abf/relay-server/src/endpoints/mod.rs#L66-L74). Those are not necessary in static or proxy mode.

**Comment by revathyrams** [comment]
thanks for updating the docs. I'm running in `proxy` mode.

**Comment by revathyrams** [comment]
Seeing several buffer capacity exceeded issue after introducing the proxy
```
relay_server::endpoints::common: error handling request error=failed to queue envelope error.sources=[envelope buffer capacity exceeded]
```
Right now I have default buffer size. Not sure why introducing the proxy should cause this issue.

**Comment by Dav1dde** [comment]
That error means Relay cannot forward data at all or fast enough and the internal buffer is full.

I can't help you here without having Relay logs and the config you're using. Also if you know it works without the Proxy, you can also debug the Proxy and see which requests get rejected when they shouldn't.

**Comment by revathyrams** [comment]
this is what I see in the relay logs and it's set up in proxy mode
`ERROR relay_server::utils::managed_envelope: dropped envelope: internal error tags.project_key="redacted" tags.has_attachments=false tags.has_sessions=false tags.has_profiles=false tags.has_transactions=false tags.has_replays=false tags.has_checkins=false tags.event_category=Some(Error) cached_summary=EnvelopeSummary { event_category: Some(Error), attachment_quantity: 0, session_quantity: 0, profile_quantity: 0, replay_quantity: 0, checkin_quantity: 0, secondary_transaction_quantity: 0, has_plain_attachments: false, event_metrics_extracted: false, payload_size: 15982 } recomputed_summary=EnvelopeSummary { event_category: None, attachment_quantity: 0, session_quantity: 0, profile_quantity: 0, replay_quantity: 0, checkin_quantity: 0, secondary_transaction_quantity: 0, has_plain_attachments: false, event_metrics_extracted: false, payload_size: 0 }`

ERROR relay_server::endpoints::common: error handling request error=failed to queue envelope error.sources=[envelope buffer capacity exceeded]

**Comment by Dav1dde** [comment]
I am not sure how we can help here, from what you're describing the error is coming from the Proxy you introduced.

I'll close this for now, feel free to re-open if you have more information including the full Relay logs.
