### ISSUE TITLE
Weekly Summaries are being sent multiple times per user

### ISSUE THREAD

**Issue by leedongwei** [getsentry/sentry#71855]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

-

### Expected Result

-

### Actual Result

-

### Product Area

Alerts

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2249) by [Unito](https://www.unito.io)

**Comment by ceorourke** [comment]
Josh's investigation notes from last week: https://www.notion.so/sentry/Weekly-Reports-Investigation-f9c57bbb73114a13ba4d31f440f6477c

Logs PR: https://github.com/getsentry/sentry/pull/71629

So far empty data: https://sentry.sentry.io/performance/traces/?end=2024-05-20T06%3A59%3A59&project=1&query=span.op%3Aweekly_reports.deliver_reports&start=2024-05-17T07%3A00%3A00

Transactions data: https://sentry.sentry.io/performance/summary/?project=1&statsPeriod=14d&transaction=sentry.tasks.summaries.weekly_reports.prepare_organization_report

**Comment by ceorourke** [comment]
Request to update the time frame title in weekly reports: https://github.com/getsentry/sentry/issues/71458

**Comment by kevinrenskers** [comment]
Same problem here. I was getting a duplicate report for many weeks, but today I got 3 reports sent to me. Two of them one hour apart, and then another one 6 hours later.

![Image](https://github.com/user-attachments/assets/6785f9c3-2bb2-4b26-a324-44dcb35c5dda)

This is all the same project sent to the same person.

**Comment by kevinrenskers** [comment]
Same happened with a different project just now.

![Image](https://github.com/user-attachments/assets/560ac2e1-03b6-4cd4-88dc-29ad3992e8b5)

**Comment by souredoutlook** [comment]
Hi @leedongwei we are see many reports of this since July 27th:

https://sentry.zendesk.com/agent/tickets/127929
https://sentry.zendesk.com/agent/tickets/127934
https://sentry.zendesk.com/agent/tickets/127977
https://sentry.zendesk.com/agent/tickets/128054
https://sentry.zendesk.com/agent/tickets/128054

**Comment by ReneGreen27** [comment]
I have an additional example of this here: 
[https://sentry.zendesk.com/agent/tickets/128169](https://sentry.zendesk.com/agent/tickets/128169)

**Comment by JoshFerge** [comment]
https://github.com/getsentry/sentry/pull/76031 addresses. closing for now.
