### ISSUE TITLE
Unable to apply publicly-hosted sourcemaps

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#71888]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Attempting to host sourcemaps publicly on a local server, to apply to events in Sentry. This is due to artifacts being too large for sentry to accept upload.

### How are you getting stuck?

I have verified Sentry's infrastructure can see the local server hosting the source artifacts, but events are not deobfuscating. I am seeing the below message. Perhaps I am missing a step: 

![image](https://github.com/getsentry/sentry/assets/103009467/98b7d499-3b18-42e7-9640-23e723c1c272)

### Where in the product are you?

Issues - Source Maps

**Comment by smeubank** [comment]
@lforst noticing from this issue, that the modal might not work that well if you are trying to public host an issue
