### ISSUE TITLE
Sentry alert pagerduty event missing client

### ISSUE THREAD

**Issue by keidarcy** [getsentry/sentry#71896]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

An alert is triggered in sentry, sends en event to pagerduty, pagerduty sends a slack message.

Compare this to DataDog sentry not sending client and client_url which ends up with lacking of one handy link to sentry in a slack message.

I had PR(https://github.com/getsentry/sentry/pull/71548) to fix it already

### Expected Result

An event from datadog
![Screenshot 2024-06-03 at 16 40 52](https://github.com/getsentry/sentry/assets/48758247/aaea472e-a2c0-4997-8768-2970cdc75452)

### Actual Result

An event from sentry
![Screenshot 2024-06-03 at 16 40 43](https://github.com/getsentry/sentry/assets/48758247/2e0dd5cc-3f3b-4c4c-be3d-c7ed7c3ee77a)

### Product Area

Alerts

**Comment by schew2381** [comment]
@keidarcy Hi there, thanks for making the PR fix! I'll have the right team review it to move things along

**Comment by keidarcy** [comment]
Hi, there is a sentry link from paperduty slack message now. Thank you!
![Screenshot 2024-06-13 at 16 26 45](https://github.com/getsentry/sentry/assets/48758247/986d4369-af8a-421d-92c4-6c2194f868eb)
