### ISSUE TITLE
Monorepo with two projects, source Maps uploading two different keys. Github onBuild actions accept a single key.

### ISSUE THREAD

**Issue by lveillard** [getsentry/sentry#71905]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

We have a monorepo with two nextjs apps. 

We installed sentry in both apps, and asigned them to two different projects.

We just want the sourcemap to be uploaded during build time, all apps are build at once, or individually depending on the needs

### How are you getting stuck?

We want to split each app in a single project, but then we get 2 different auth keys for the sourcemap upload.

The problem is that in the github actions we can set up a single one, so we should unify the sourcemap upload, while having two different projects in the same monorepo.

ORG ID: `blitz-no-code`

### Where in the product are you?

Issues - Source Maps

**Comment by lforst** [comment]
Hi, you can absolutely just use the same key for both of the projects when uploading.

**Comment by lveillard** [comment]
Oh perfect. Thanks! For UX I guess it would make sense to don't generate one key on every setup for the same account, similar as how highligh.io does it

Also the auto patcher is really cool, but it does not check if the code is already there, so if you run it twice to change some configs, it actually duplicates most of the code (at least for the nextjs one)

Closing this, will reopen if i find any issue by using the same key for different projects.

Thanks!
