### ISSUE TITLE
[Jira Integration] Non required custom date field lists "The <field name> must be a string"

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#71911]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

This is very similar to [64538](https://github.com/getsentry/sentry/issues/64538), but in that issue they are discussing required fields, where it looks like the error shows even without the field being marked as Required.

1. Create date field in Jira with Required Unchecked -

<img width="600" alt="Screenshot 2024-06-03 at 12 18 02 PM" src="https://github.com/getsentry/sentry/assets/96670625/e7a068f3-07c3-47aa-81e4-40e8c357a4cb">

2. Try to fill in field on Sentry side and see error -

<img width="677" alt="Screenshot 2024-06-03 at 12 19 31 PM" src="https://github.com/getsentry/sentry/assets/96670625/16e61e44-6634-4862-81a6-0340ecd33b3b">

[Link to a testable error in my org](https://francisorg.sentry.io/issues/4293933925/?project=-1&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=1)

### Expected Result

The Form should save

### Actual Result

Form does not save

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
Thanks for this bug report, we'll add it to the backlog and investigate

**Comment by GabeVillalobos** [comment]
This has been addressed by https://github.com/getsentry/sentry/pull/76962, which now allows you to specify a date in the `YYYY-MM-DD` format. Closing this for now, but please comment if you encounter more issues with this field type.
