### ISSUE TITLE
Project Transfer Issue

### ISSUE THREAD

**Issue by usmanthesuper** [getsentry/sentry#71943]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. transfer project
2. accept request
3. I transfered project to my other account but when I accepted it it leads to an error now project is not showing up in my account neither on the account which I transfered project to

### Expected Result

<img width="1385" alt="Screenshot 2024-06-04 at 1 24 59 AM" src="https://github.com/getsentry/sentry/assets/64627750/4587e174-1ae2-4ed6-ae76-21ba087c9666">

### Actual Result

The project should show up on account from which accepted from

### Product Area

Projects - Project Details

**Comment by dalnoki** [comment]
Hi @usmanthesuper thanks for reaching out! Would you mind sharing the slug of the origin and the target organization and the name of the project? if you don't feel comfortable sharing this information here, please write to support [here](https://sentry.zendesk.com/hc/en-us/requests/new). Thanks in advance!

**Comment by mrduncan** [comment]
I'm going to close this for now since we're not able to repro - please reopen with more details if you're still seeing this.
