### ISSUE TITLE
Slack alert shows up as thread after disabling the thread option

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#71967]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. have a Slack integration, with enabled Slack threads on Issue Alerts
2. Send in the same error twice, the second will appear as a thread
3. Go to integration settings and disable Slack threads for Issue Alerts
4. Send in the same error again, it will still appear as a thread in Slack

### Expected Result

after disabling the feature, it the notification should not appear as a thread in Slack

### Actual Result

it still appears in a thread

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
@dalnoki can you please share the ZD ticket with the org details so we can investigate
