### ISSUE TITLE
SAML2 incorrectly depends on 'organizations:sso-rippling' feature

### ISSUE THREAD

**Issue by reedloden** [getsentry/sentry#7197]
I was migrating our Sentry instance from Google to SAML, and I couldn't get the SAML options to show on the auth provider page. After much gnashing of teeth, I figured out that this was because I hadn't set `SENTRY_FEATURES['organizations:sso-rippling']` to True, even though I wasn't using Rippling at all.

https://github.com/getsentry/sentry/blob/master/docs/sso.rst#enabling-sso talks about both
```
SENTRY_FEATURES['organizations:sso-saml2'] = True
SENTRY_FEATURES['organizations:sso-rippling'] = True
```

but it doesn't make it clear that both are required (and seems odd that the latter would hold precedent). This seems like a bug to me.

**Comment by EvanPurkhiser** [comment]
Thanks @reedloden, I’ll be able to take a look at this on Tuesday. You’re right, this sounds like a bug!

**Comment by EvanPurkhiser** [comment]
Are you sure @reedloden? I'm not able to reproduce this. Perhaps you did not restart your server after enabling the `organizations:sso-saml2` feature?
