### ISSUE TITLE
Wrong UA parsing for Waterfox/basilisk

### ISSUE THREAD

**Issue by dhoko** [getsentry/sentry#7198]
version: Sentry 8.22.0

Hey, 

I tested to report issues with: 
```
Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.2.2 Waterfox/55.2.2
Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Goanna/4.0 Firefox/55.0 Basilisk/20171113
```

But I get this. 
![waterfox](https://user-images.githubusercontent.com/713283/35978590-7968a352-0ce6-11e8-88a1-16929666b15d.png)

Which lib are you using to parse the UA ? Is it https://github.com/ua-parser/uap-core cf https://github.com/getsentry/sentry/issues/3911 ?

Thx.

**Comment by kaplun** [comment]
@dhoko I've sent a PR to the core relevant project `uap-core` that would make the above user-agents to be recognized.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
