### ISSUE TITLE
Adding multiple filters to the message field breaks the issue stream

### ISSUE THREAD

**Issue by jfranmora** [getsentry/sentry#71981]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

In the issue tab, add a couple of search terms to filter issues by message
- In our case, we were testing with something like `message:*HTTP/1.1* !message:"*QoS*" ` **(second search term is negative!)**

### Expected Result

When searching for the same field multiple times, the query doesn't break and return results.

### Actual Result

In the issue section, this query doesn't work, while the alert and discovery section works.

### Product Area

Issues

### DSN

https://9cf6d358681e4018a823d56659a44ff2@o3642.ingest.us.sentry.io/4503970242822144

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2191) by [Unito](https://www.unito.io)

**Comment by mrduncan** [comment]
Hi @jfranmora, this appears to be resolved now, can you verify and re-open this issue if you're still seeing the problem?
