### ISSUE TITLE
Issue unexpectedly marked as "resolved due to inactivity" after escalating

### ISSUE THREAD

**Issue by nbrustein** [getsentry/sentry#71998]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I don't know how to reproduce this issue. Looking at the activity tab for [this issue](https://pedago.sentry.io/issues/5392087181/activity/?alert_rule_id=751720&alert_type=issue&environment=Production+-+Client&notification_uuid=2ad4c6ca-5c14-4938-bf93-4cabbb31fed2&project=1491374&referrer=slack), I see

 * May 23, 1:44pm: Nate Brustein archived this issue until it happens 1 time(s)
 * June 3, 3:27pm: Sentry flagged this issue as escalating because 1 event happened
 * June 3, 3:27pm: Sentry updated the priority value of this issue to be high after it escalated
 * **June 3, 3:30pm: Sentry marked this issue as resolved due to inactivity**

### Expected Result

The issue should not be marked as "resolved due to inactivity minutes after escalating.

### Actual Result

The issue was marked as "resolved due to inactivity minutes after escalating.

https://pedago.sentry.io/issues/5392087181/activity/?alert_rule_id=751720&alert_type=issue&environment=Production+-+Client&notification_uuid=2ad4c6ca-5c14-4938-bf93-4cabbb31fed2&project=1491374&referrer=slack

### Product Area

Issues

### Link

https://pedago.sentry.io/issues/5392087181/activity/?alert_rule_id=751720&alert_type=issue&environment=Production+-+Client&notification_uuid=2ad4c6ca-5c14-4938-bf93-4cabbb31fed2&project=1491374&referrer=slack

**Comment by snigdhas** [comment]
Hey @nbrustein thanks for reporting this! It's definitely a bug in our auto-resolution logic and seems to be hitting a race condition with the issue auto-transitioning to `escalating`. I've brought this to our team's attention and will keep the ticket updated as we work towards a fix.

**Comment by snigdhas** [comment]
Closing this as it should have been fixed in #72269 - please reopen if you notice this happen again!
