### ISSUE TITLE
Business Trial Okta not Working

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#72030]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

![image](https://github.com/getsentry/sentry/assets/8920574/43c31b79-ac8d-4b48-affe-1b463cc06753)
and
![image](https://github.com/getsentry/sentry/assets/8920574/8fb8d8c1-bf3d-4ec1-b018-897f257f76cf)

### Expected Result

not expecting a pop-up that says Business Plan is not available while Business Trial is turned on

### Actual Result

see screenshot

### Product Area

Settings - Integrations

**Comment by leedongwei** [comment]
Product decision to not allow people to setup SSO through a Business Plan trial.
