### ISSUE TITLE
Unable to get error report when SQL query has %

### ISSUE THREAD

**Issue by caiola** [getsentry/sentry#7208]
require_once './includes/config/loader.php';

$sql = "SELECT DATE_FORMAT('2018-02-09','%d/%m/%Y %H:%i') AS_ data";
$bd = new bd();
$results = $bd->query($sql);
var_dump($results);

Sentry will report error with title "False", fails on vsprintf sentry client lib.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
