### ISSUE TITLE
Mapping environment specific schedules inside one Cron Monitor

### ISSUE THREAD

**Issue by romanefimchik** [getsentry/sentry#72101]
### Problem Statement

Preconditions:
Java project, using Sentry SDK

Here said

_"...shared schedule to send check-ins for multiple environments to one monitor"_

https://docs.sentry.io/product/crons/job-monitoring/#multiple-environments

That means I have a possibility to map defferent environments for one Monitor.

But I don't have a possibility to map environment-specific schedules for one Monitor at the moment.
One monitor means one schedule but for multiple environments.

**Example:**

Input:

One monitor, different environments:

env: "dev" schedule: `0 * * * * #hourly`

env: "qa" schedule: `*/15 6-21 * * 1-5 #every 15 min in working day and in working days`

**Current sate:**

On every execution scheduled Job rewrites Monitor configuration and I see in Sentry Cron UI 
either `0 * * * *` 
OR
`*/15 6-21 * * 1-5`
and this value is not mapped to environment.

In case I select environment on Sentry UI - no Monitor schedule is changed.

**Wish state:**
On every execution scheduled Job setup (in Java source code) environment and environment-specific schedule.
This schedule is used for particular environment and does not affect schedule for other environments.
On Sentry UI environment-specific schedule is taken into account and on selecting ENV - avalable to browse.

### Product Area

Crons

**Comment by gaprl** [comment]
Hey @romanefimchik, thank you for the feedback. Currently, we have no plans on modifying this behavior, but we'll definitely consider for the future. For now, I recommend creating one monitor for each of your environments that have different schedules.

I'll close this issue for now, but we'll reopen if we ever reconsider. Thank you.
