### ISSUE TITLE
[Replay Settings] Fix "Read More" link at the top of the page

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#72124]
The "Read More" link goes to a rage-click specific place, seems incorrect.

https://sentry.sentry.io/settings/projects/docs/replays/

Related to https://github.com/getsentry/sentry-docs/issues/10277

**Comment by michellewzhang** [comment]
could probably link to https://docs.sentry.io/product/issues/issue-details/replay-issues/ once we add something about hydration issues (right now that page only talks about rage click issues). right now the button is linking to https://docs.sentry.io/product/explore/session-replay/replay-page-and-filters/ which is just a generic replay docs page
