### ISSUE TITLE
[Replay Settings] Add a note, for getsentry users, about how Replay Issues do not consume Error quota

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#72123]
On a page like https://sentry.sentry.io/settings/projects/docs/replays/ we can see this:

<img width="823" alt="SCR-20240605-igup" src="https://github.com/getsentry/sentry/assets/187460/fc816536-ceb4-446b-a080-9b027fe5920f">

I'm thinking we should add a note directly to the page so people know these things are free and do not consume quota.

**Comment by bruno-garcia** [comment]
That's great catch. Worth considering calling it out as 'errors quota'
