### ISSUE TITLE
Replays

### ISSUE THREAD

**Issue by petertimperman** [getsentry/sentry#72162]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I am tyring to get Replays to work. 

### How are you getting stuck?

I got replays to work once in dev environment but have been unable to replicate 

### Where in the product are you?

Replays

### DSN

https://d249d1452b0e4486889e9f06f232206d@o106833.ingest.us.sentry.io/235089

**Comment by InterstellarStella** [comment]
Hi @petertimperman, could you provide some more information on your setup? Specifically your Sentry.init, SDK package name and version, and whether you are capturing anything manually. If you have any PII, please feel free to open a support ticket [here](https://sentry.zendesk.com/hc/en-us/requests/new).

**Comment by petertimperman** [comment]
Okay thanks i will open a ticket instead

**Comment by InterstellarStella** [comment]
Got it, I will be closing this issue then. Thanks!
