### ISSUE TITLE
Edit Alert Rule: section "IF [all/any] of these filters match" become more flexible

### ISSUE THREAD

**Issue by romanefimchik** [getsentry/sentry#72209]
### Problem Statement

I created an ENV-specific Alerts to have possibility to send Notification in different Slack channels.
I would like to setup next rule:
```
dev* + "uat-features-uk" -> sent Slack notification to channel #sentry-alerts-dev
```

Now I can't perform such rule in one ALERT issue and have to create (and further support) two ALERTs:
Please take a look on image
![sentry_if_statement](https://github.com/getsentry/sentry/assets/60354106/3cba8ef5-8d98-4833-bdd1-55562c6ad1ae)

Two last conditions clashes.

**Suggestion:**
Apply kind of Query constructor.
Add a possibility of Filter "much condition" on EVERY sub-rule in [IF] Alert section.
I mean:

The event's tags match "monitor.slug" "is set"
**AND**
(
The event's tags match "environment" "contains" "dev"
**OR**
The event's tags match "environment" "equals" "uat-features-uk"
)

### Product Area

Alerts

**Comment by schew2381** [comment]
Hi there thanks for this feature request. We currently don't support mixing [all/any] conditions in filters, although I'll post any updates in this issue if anything changes.

**Comment by AshRing** [comment]
This would help clean up a bunch of my team's alerts. We currently need to make separate alerts for each page, for example. If we had this feature we could make 1 alert to hit many areas.

**Comment by nhsiehgit** [comment]
Hi @AshRing 

See our latest [changelog update here](https://docs.sentry.io/changelog/sentry-issue-alerts-now-support-in-and-not-in-conditions-for-tags-and-attributes/)
We've just released a new change to our Issue alerts to enable specifying explicit tags to group alerts together.
Hopefully this can solve your issue!

**Comment by nhsiehgit** [comment]
Hi @romanefimchik 

See our latest [changelog update here](https://docs.sentry.io/changelog/sentry-issue-alerts-now-support-in-and-not-in-conditions-for-tags-and-attributes/)

This isn't quite exactly what you were asking for - but i think this can address the annoyance you were having.
Now - instead of 2 different alerts, you could set a filter for
```
any:
- event.tag monitor.slug IS SET
- event.environment IS IN [dev-1, dev-2, dev-3, uat-features-uk]
```

Let us know if this helps resolve your issue!
