### ISSUE TITLE
OpsGenie Webhook missing attached tags

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry#72220]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Create issue alert 
Attach the environment tag to opsgenie webhook

### Expected Result

Expected to see the environment tag in the opsgenie alert

### Actual Result

- Environment tag not attached
- Similar alerts from a different team are seeing their environment attached correctly 

### Product Area

Alerts

**Comment by cathteng** [comment]
Webhook event data is generated here https://github.com/getsentry/sentry/blob/fdbcd3a5f92edea5c1d60a7b96f5e32723786def/src/sentry/tasks/sentry_apps.py#L60-L83

We call `event.as_dict()` to get the event information https://github.com/getsentry/sentry/blob/fdbcd3a5f92edea5c1d60a7b96f5e32723786def/src/sentry/eventstore/models.py#L541-L568, which includes all of the tags.

This fetches tags from Snuba with a fallback on Nodestore https://github.com/getsentry/sentry/blob/fdbcd3a5f92edea5c1d60a7b96f5e32723786def/src/sentry/eventstore/models.py#L130-L157

If tags are not appearing in the webhook data, that would appear to be some problem with Snuba or Nodestore as the integration does not manipulate (remove) the tags in any way besides formatting them.

**Comment by dachakra** [comment]
Confirmed that the event payload is missing the tag.

**Comment by cathteng** [comment]
I would follow up with the team that is responsible for storing and fetching tags, we don't manipulate any of the tags in Python when populating the webhook

**Comment by sentaur-athena** [comment]
I'll close this since it seems like this is not an issue with the integration but the fact that tags were missing.
