### ISSUE TITLE
Limit the discord bot interactions to certain users

### ISSUE THREAD

**Issue by shtlrs** [getsentry/sentry#72305]
### Problem Statement

We have a community server that harvests a couple of open source projects.

Along with that, we have rules related to who can assign issues, etc.

The discord integration, if activated, will enable everyone to click on those buttons to create issues and or resolve them, which isn't ideal.

Ideally, we could add a list of user ids who can interact with the bot.

### Solution Brainstorm

This could be a plain text input boxes, just like for the alert rules, to add ids of users that can interact with the bot.
Then a check against those ids will be made upon integration, and determine whether to execute the button's callback.

### Product Area

Settings - Integrations

**Comment by Dhrumil-Sentry** [comment]
Thanks for this feedback, we're not planning to work on the Discord integration in the near future but we will add this feedback to our backlog

**Comment by cathteng** [comment]
Unfortunately the team is understaffed and we can’t prioritize this fix, but we’re always open to community contributions
