### ISSUE TITLE
[Crons] Monitor quota depletes even though the monitor was not used during the billing cycle

### ISSUE THREAD

**Issue by serglom21** [getsentry/sentry#72311]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. I create a monitor - Which depletes my 1 monitor per billing cycle quota
2. I don't generate any check-ins (I don't use this monitor at all)
3. I delete the monitor because it is not what I want anymore (different config, different project)
4. I create a new monitor with the config I want

### Expected Result

I would expect the new monitor that I created to be able to accept check-ins (Since I did not use the previous monitor at all)

### Actual Result

I am not able to send check-ins to the new monitor. I get the error `You don't have enough on-demand available to create a new monitor`

### Product Area

Crons

**Comment by wedamija** [comment]
Hi @serglom21 

Sorry about this - it's a current shortcoming of our billing process that we're looking to correct. If you contact support they can give you additional quota to work around this issue.
