### ISSUE TITLE
Display full function signature on hover for stack traces

### ISSUE THREAD

**Issue by Steelskin** [getsentry/sentry#72336]
### Problem Statement

Stack traces display a truncated user-friendly string for the function used in a stack. While this trims down on the display, it can be really confusing to see which function is actually in use. This is especially true for closures or lambdas, which get truncated to "closure" or "lambda".

It would be very helpful to have the full original function name with arguments and closure/lambda reference on hover in the UI.

### Solution Brainstorm

The trimming is done in `trim_function_name` in `src/sentry/stacktraces/functions.py`. I am unclear on how this connects to the UI for stack traces, though. Anyway, this is presumably where we "lose" the full function name.

### Product Area

Dashboards

**Comment by malwilley** [comment]
@Steelskin thanks for the feedback! To help us fully understand the issue, could you include some additional info?

- Which SDK are you using?
- What is your original function name, and what is shown in the UI?
- Is there a "better" trimmed value we could use in your example that would be more helpful?

**Comment by Steelskin** [comment]
I am not sure what you mean by SDK.

You can see examples in this [PR](https://github.com/getsentry/sentry/pull/72335) where I am fixing a couple of issues with the current trimming function:
* `closure #1 @Swift.MainActor () -> () in static Foo.CallFunction(args: [Swift.String]) -> ()` becomes `#1` in the UI. I am fixing it to display `closure in Foo.CallFunction` instead.
* `static Namespace.ThrowingFunction() throws -> Namespace.ExitValue?` becomes `throws` in the UI. I am fixing it to display `Namespace.ThrowingFunction` instead.

Since we can't think of all possible ways the names are going to be mangled, this bug is about having the full original prototype on hover. This serves 2 purposes:
* Workaround for any future bug in trimming the function value.
* Have full diagnostic information related to closures. This is very handy when trying to diagnose a crash and figuring out which path was taken.

Does that answer your questions?

**Comment by leeandher** [comment]
@Steelskin First of all, thank you for the PR! When we get the opportunity we'll give that a review and get that moving along.

> I am not sure what you mean by SDK.

By SDK, we just mean which platform your project is using. From your description/PR, I'm assuming it is [iOS SDK](https://docs.sentry.io/platforms/apple/guides/ios/).

> It would be very helpful to have the full original function name with arguments and closure/lambda reference on hover in the UI.

This sounds like a reasonable feature request if we already have access to this data. I wouldn't be able to provide a timeline on when this could be added, but I'll pass it along to the team. 

In the meantime, would it be possible be able to share a link to a Sentry Issue, or a Project ID / Issue ID to reproduce the issue with truncated frames?

**Comment by Steelskin** [comment]
> By SDK, we just mean which platform your project is using. From your description/PR, I'm assuming it is [iOS SDK](https://docs.sentry.io/platforms/apple/guides/ios/).

We use macOS, iOS and Windows. Specifically, this issue arose with Swift on Windows, but the truncated display for Swift in general is not as helpful as it could be.

> In the meantime, would it be possible be able to share a link to a Sentry Issue, or a Project ID / Issue ID to reproduce the issue with truncated frames?

You can check Sentry Issue ID 5408770401 for Project ID 4505954005876736 for a sample stack trace where some of the trimmed symbols are not very helpful.

**Comment by leeandher** [comment]
Thanks for the context, I put together a PR for it. The formatting is a bit challenging since the raw function can have extreme variations in length, but hopefully having it accessible in the UI helps with debugging!

**Comment by Steelskin** [comment]
Thanks for the quick turnaround, I appreciate it!
