### ISSUE TITLE
Integrate gitlab 

### ISSUE THREAD

**Issue by Alex-stack-cell** [getsentry/sentry#72395]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Connect my Sentry organization to an organization in my GitLab instance or gitlab.com

### How are you getting stuck?

After following the steps I got the following error : 

Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.

### Where in the product are you?

Settings - Integrations

### DSN

https://4d001fe566bd239f7b692e6aec3850f3@o4507391070699520.ingest.de.sentry.io/4507391080464464

**Comment by cathteng** [comment]
This is an error message from GitLab, I'm not sure how you're authenticating but some other people have received this message as well
- https://gitlab.com/gitlab-org/cli/-/issues/7306
- https://gitlab.com/gitlab-org/cli/-/issues/1338
- https://gitlab.com/gitlab-org/gitlab-mattermost/-/issues/34
