### ISSUE TITLE
Disconnect Fly.io from Sentry Org

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#72446]
### Problem Statement

Customer reported: I know it's not possible to disconnect your Fly OAuth from Sentry today. But please make sure this ticket is prioritized. What a pain for getting new users into the platform. If we knew this would be an issue, we would never have done this.

### Product Area

Settings - Integrations

**Comment by leedongwei** [comment]
Responded in DMs. 

For folks reading this, using Fly.io SSO is part of Sentry's partnership terms with Fly.io. It will affect user provisioning through other identity providers. We can remove it from your Sentry organization but it'll remove the free subscription plan. You can sign up for an equivalent plan at $26/month.
