### ISSUE TITLE
Solid-js Platform in Sentry

### ISSUE THREAD

**Issue by smeubank** [getsentry/sentry#72497]
### Problem Statement

Solid-js is a JavaScript browser framework which will be supported by an official Sentry JavaScript SDK

https://github.com/getsentry/sentry-javascript/tree/develop/packages/solid

There is no platform in Sentry

### Solution Brainstorm

Add a platform in Sentry

### Product Area

Projects - Project Creation

**Comment by smeubank** [comment]
https://github.com/getsentry/sentry/pull/70647/files

example needed changes

**Comment by andreiborza** [comment]
The [solid package readme](https://github.com/getsentry/sentry-javascript/tree/develop/packages/solid) currently has two code samples, one for performance instrumentation via the router and another one for the error boundary component. Consider combining these.
