### ISSUE TITLE
Replay - Need ability too zoom in on the player

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#72492]
### Problem Statement

I have a webview on mobile which is very long, so I can't see the content very easily as it's put into full display on the replay details screen

I can zoom in on browser but that means I cannot check the other tabs as it's zoomed in on the browser itself

I'll include a Screenshot in the internal jira ticket 

### Product Area

Replays

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2197) by [Unito](https://www.unito.io)

**Comment by michellewzhang** [comment]
so i also have this mobile-specific ticket: https://github.com/getsentry/sentry/issues/70058#event-13269955029

which we agreed on designs/concept for (no zoom choice, just auto-zoom) but this ticket is web-replay specific. i'm not sure we fully decided on a design/concept for this

**Comment by jas-kas** [comment]
cc/ @Jesse-Box on above ^

**Comment by michellewzhang** [comment]
Slack thread: https://sentry.slack.com/archives/C03USURCFBJ/p1718013821403969
