### ISSUE TITLE
Sourcemaps not working (Angula/JS project)

### ISSUE THREAD

**Issue by cswan-log** [getsentry/sentry#72569]
### Self-Hosted Version

24.5.1

### CPU Architecture

x86_64

### Docker Version

26.1.4

### Docker Compose Version

2.27.1

### Steps to Reproduce

1. Create angular/js project
2. Add release and sourcemaps to project
3. produce an error

### Expected Result

The error stacktrace should be unminified and the problematic code path should be readable.

### Actual Result

The code is still minified and sentry is unable to unminify the code.

The "help popup" shows this:

![image](https://github.com/getsentry/self-hosted/assets/63999494/2265d7a4-6050-4eca-ba34-f22194ad58de)

and this 

![image](https://github.com/getsentry/self-hosted/assets/63999494/74e3c9c2-eef4-4616-9624-947175ac314e)

The "new" way of tagging the artifact bundles seems to work but the tagged release might interfere with this?

The corresponding chunk is definitely in the bundle: 

![image](https://github.com/getsentry/self-hosted/assets/63999494/17f5e6d3-5d3b-492b-bbe3-db95ffc4d79e)

The  `.map` files are removed from the deployed production build.

As you can see the project is hosted in an subfolder "handheld". Thus the sourcemaps are uploaded with the corresponding command parameters: `--strip-common-prefix --url-prefix '~/handheld' --release "$VERSION"`

I already tried various things (changed prefix, re-uploaded, with or without release) but it seems sentry is not able to properly find the sourcemaps.

**Comment by hubertdeng123** [comment]
I've transferred this over to sentry since I don't have quite the context to help out here.

**Comment by loewenheim** [comment]
Hi, is this on SaaS? Can you link me to a concrete event where this fails?

**Comment by cswan-log** [comment]
Hi, not on SaaS. The original ticket was created in the self-hosted repository.

**Comment by loewenheim** [comment]
In that case, can you mail the event.json file to me at sebastian.zivota@sentry.io? Maybe I can glean something from that.

**Comment by cswan-log** [comment]
Seems like a problem with the self-hosted setup. With the help of @loewenheim I could narrow it down to a non-working API communication between symbolicator and sentry. Somehow, the access is denied when fetching the artifact to generating the correct stacktrace.

Even with a freshly generated token, using the `symbolicatorcli` manually, a 401 error is given from the API.

Follow up here: https://github.com/getsentry/self-hosted/issues/3134
