### ISSUE TITLE
Slack: "/sentry link" gives a 404 URL

### ISSUE THREAD

**Issue by eusouoviana** [getsentry/sentry#72597]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. I open the 'conversation' with the Sentry app on Slack.
2. Dispatch the command /sentry link
3. A message "Link your Slack identity to your Sentry account to receive notifications. You'll also be able to perform actions in Sentry through Slack." appears
4. I click on link "Link your Slack identity"
5. A "Page Not Found | Sentry" page is displayed.

![image](https://github.com/getsentry/sentry/assets/86630477/e5782ca3-a57c-4bfe-aa86-32423d329935)

![image](https://github.com/getsentry/sentry/assets/86630477/4cd0d08e-19a8-4043-ac0b-04dd24a52907)

### Expected Result

Connect my Slack account to my Sentry account

### Actual Result

404 Page Not Found

### Product Area

Settings - Integrations

**Comment by cathteng** [comment]
Hi, we have logic in the endpoint to 404 if we don't have all of the information we need to link the identity https://github.com/getsentry/sentry/blob/4e033bbbf47822da1d39477b95ab13024364a6f5/src/sentry/integrations/utils/identities.py#L16-L60

We need more information to help you with your particular case. Could you share your organization slug here or open a support ticket in Zendesk with this information?

**Comment by iamrajjoshi** [comment]
It seems to be working, so closing this issue for now. Feel free to open this issue if you are still having problems!
