### ISSUE TITLE
On-Demand Budget Help link leads to 404

### ISSUE THREAD

**Issue by klemmchr** [getsentry/sentry#72592]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Settings > Subscription 
2. Click on the help link for On-Demand Budgets

### Expected Result

Redirect to docs page

### Actual Result

![image](https://github.com/getsentry/sentry/assets/6552521/1880ad4d-21cb-4c34-80fa-d941d8002458)
![image](https://github.com/getsentry/sentry/assets/6552521/5f4b0abf-c20b-4ea9-b784-b56a1c72a2be)

### Product Area

Settings - Subscription

**Comment by brianthi** [comment]
Thanks for sharing! We'll get this fixed.
