### ISSUE TITLE
The Diff button inside the Similar Issues tab should show grouping information, not just error message

### ISSUE THREAD

**Issue by jboulter11** [getsentry/sentry#72607]
### Problem Statement

When looking at the differences between groups, I am trying to understand whether they can be grouped together, in other words, why did Sentry group them differently in the first place?

Right now the Diff button, when pressed, shows only error messages.  For us, they're almost always identical.

This is the button I'm talking about:
![Screenshot by Dropbox Capture](https://github.com/getsentry/sentry/assets/6633472/47c2d14a-f79a-4890-820d-96ecb0d17050)
This is what I see when I click it.  Very unhelpful.
![Screenshot by Dropbox Capture](https://github.com/getsentry/sentry/assets/6633472/2fafb94a-cabf-4890-abce-9013a0499951)

### Solution Brainstorm

I'd instead like to see the reason for the grouping diffed so it actually tells me why they're not the same.

In most cases that will mean the stack trace and exception type, but whatever is in the grouping details should ideally be supported.  I'll take just stack trace and exception type as an incremental improvement, though.

### Product Area

Issues

**Comment by malwilley** [comment]
Thanks for the report! We are looking into this and will get back to you with an update soon.
