### ISSUE TITLE
Dead End Link from App to Docs

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry#72669]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

> When I click the link "learn more" next to "Your orgs data storage location" in Legal & Compliance in our account, it's a dead end.

### Expected Result

It resolves to this docs page instead https://docs.sentry.io/organization/data-storage-location/

### Actual Result

It leads to a 404 page

### Product Area

Settings - Security & Privacy

**Comment by leedongwei** [comment]
Create PR with fix.
