### ISSUE TITLE
User Doesn't Appear at Top

### ISSUE THREAD

**Issue by scefali** [getsentry/sentry#72684]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I am trying to set the user for an API route Next.js for an application. Following the instructions [here](https://docs.sentry.io/platforms/javascript/guides/node/enriching-events/identify-user/).

Here is my code:

```
import { getAuth as clerkGetAuth } from "@clerk/nextjs/server";
import * as Sentry from "@sentry/nextjs";

export function getAuth(req, options) {
  const auth = clerkGetAuth(req, options);
  if (auth) {
    Sentry.setUser({
      userId: auth.userId,
      orgSlug: auth.orgSlug,
      orgRole: auth.orgRole,
      orgId: auth.orgId
    });
  }
  return auth;
}
```

### Expected Result

User information should show up in event highlights.

### Actual Result

User information shows up in context instead:

![Screenshot 2024-06-13 at 10 00 01 PM](https://github.com/getsentry/sentry/assets/8533851/6ae9c02c-339e-4588-9937-a4e591fc0db3)
![Screenshot 2024-06-13 at 10 00 09 PM](https://github.com/getsentry/sentry/assets/8533851/0c7196c1-1170-480b-aebd-bde3156abe3a)

### Product Area

Issues

### Link

https://builtrightco.sentry.io/issues/5486316096/?project=4507410872139776

**Comment by leeandher** [comment]
Hey @scefali! (miss you on the team 🫶)

The event highlights get pre-populated with some defaults based on the project (like `User.Email`) but other properties you added won't be highlighted dynamically. Anything in 'Tags' or 'Contexts' can be highlighted.

You'll need to manually add them by using the 'Edit' button just above the highlights. Going forward, those should appear at the top of every issue for the project! 👍

**Comment by scefali** [comment]
@leeandher miss you guys as well!


The only thing that's a bit annoying is that I don't think it registers these contexts as user tags because I have 0 users:
![Screenshot 2024-06-18 at 4 51 10 AM](https://github.com/getsentry/sentry/assets/8533851/946c63e7-3d5c-488f-8057-743ec0835b80)

Does setting the user in Node behave differently than on the backend? Or is it because I set `id` instead of `userId`? Editing the event highlights made it appear a the top at least, nifty feature! Nice work on that btw

**Comment by malwilley** [comment]
@scefali nice to see you here! Yeah I think it's because you need to want `Sentry.setUser({ id: auth.userId, ... })` instead of setting `userId`. According to the docs, it needs one of `id`, `username`, `email`, or `ip_address` to work the way you'd expect.

**Comment by scefali** [comment]
@malwilley @leeandher Thanks guys! I'm sure I'll be posting issues here and there these days :D
