### ISSUE TITLE
Can not use "Removing Archived Issues from Metric Alerts" / "is:unresolved" filter in selfhosted Sentry 24.5.1

### ISSUE THREAD

**Issue by NB13** [getsentry/sentry#72683]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

I try to use this feature https://sentry.io/changelog/removing-archived-issues-from-metric-alerts/ , i.e. 
1. Create "Number of Errors" alert
2. Add "is:unresolved" to the "Filter events" section
3. Save this alert

### How are you getting stuck?

I get error "Unable to save alert: Invalid Query or Metric: "is:" queries are not supported in this search."

### Where in the product are you?

Alerts

### Version

24.5.1

**Comment by ceorourke** [comment]
Hello @NB13 this is enabled in saas but just flip this flag: https://github.com/getsentry/sentry/blob/master/src/sentry/features/temporary.py#L161 (add `default=True`) - I'm working on removing it so self hosted won't have to manually do this though.

**Comment by ceorourke** [comment]
I removed the flag (in https://github.com/getsentry/sentry/pull/72832 and https://github.com/getsentry/sentry/pull/72833) so this should be in the next self hosted version.
