### ISSUE TITLE
Support CSP-directive frame-src after un-deprecation

### ISSUE THREAD

**Issue by jonathanrohland** [getsentry/sentry#7271]
Can you enable support for submitting CSP-reports violating the 'frame-src' directive?

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy#frame-src the 'child-src'-directive has been deprecated while the 'frame-src'-directive is now un-deprecated again.

Since the state of these directives has been quite unstable recently, use both 'child-src' and 'frame-src' in our project to support as many browsers as possible. We would appreciate it if Sentry allowed us to just submit both as valid directives. We are now getting HTTP-400-responses for our CSP-reports (possibly since https://github.com/getsentry/sentry/pull/6718 has been merged, but maybe even before that).
As far as I can tell the code would be as simple as uncommenting the `# 'frame-src',` line in interfaces/schemas.py, but I do not have a running test setup to verify this. If you prefer I can also open a pull request for this.

**Comment by dcramer** [comment]
@getsentry/platform can we do this?
