### ISSUE TITLE
Crash in Web Vitals

### ISSUE THREAD

**Issue by nikolovlazar** [getsentry/sentry#72715]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open the Web Vitals module
2. Zoom in a specific date range
3. Web Vitals crash

### Expected Result

The data table should be filtered based on the selected date range

### Actual Result

The page crashes

![image](https://github.com/getsentry/sentry/assets/5396211/55af68bc-274f-45d6-ace2-f1a15f93aa48)

### Product Area

Insights

### Link

https://sentry-devrel.sentry.io/insights/browser/pageloads/?end=2024-06-12T23%3A48%3A05&start=2024-06-11T17%3A21%3A07

### DSN

https://940ee53488f15eb17932f14e7acf764b@o4506044970565632.ingest.us.sentry.io/4507369592717312

**Comment by AbhiPrasad** [comment]
sentry error: https://sentry.sentry.io/issues/5486939449/events/a7b1e21627fd4522b3c86d96625d02f4/

**Comment by AbhiPrasad** [comment]
This has been fixed by https://github.com/getsentry/sentry/pull/72773
