### ISSUE TITLE
Clickup Integration can not be installed.

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#72727]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

*I'm not sure if this is a clickup issue or a Sentry issue, because the error seems to hang on Clickup's page when I attempt the install.

1. Attempt to install the Click up integration from either Click up or Sentry's Side.
2. See an infinite spinner on Clickup's side, and on Sentry's side integration just shows Pending.

I made a screen recording to show the behavior here.

https://github.com/getsentry/sentry/assets/96670625/e1986a97-41f4-43ad-b033-2877f7668dc1

### Expected Result

Successful install

### Actual Result

Infinite spinner

### Product Area

Unknown

**Comment by ceorourke** [comment]
I was able to reproduce this if I wasn't logged into my Clickup account when I started the installation from Sentry. After I logged in I re-initiated the installation from Sentry (you may have to click "uninstall" if it's gotten into a "pending" state and start again) and was able to complete the installation. The UX on the Clickup side is a little strange and doesn't feel like you've completed it, but if you go back to Sentry to check it's installed and I was able to create a Clickup issue from my Sentry issue.

**Comment by mindaugasbarysas** [comment]
We have the same issue. Tried different browsers, inspected browser traffic, etc. This seems to be an issue on clickup side.
