### ISSUE TITLE
GitLab Integration Problem

### ISSUE THREAD

**Issue by fejan-malek** [getsentry/sentry#72765]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a project in the group in GitLab
2. The project will be private type not public.
3. Follow the setup wizard from the add installation button from sentry to integrate GitLab

### Expected Result

Gitlab will be configured with sentry.

### Actual Result

<img width="971" alt="Screenshot 2024-06-14 at 4 14 05 PM" src="https://github.com/getsentry/sentry/assets/63099555/3e786ff3-2c80-4fa8-8f4d-7f6206431791">

### Product Area

Other

### DSN

https://ukvi-compliance.sentry.io/

**Comment by cathteng** [comment]
Could you please share your organization slug and GitLab project slug? You're welcome to open a support ticket if necessary. I see logs where an error is happening during the last step of the installation pipeline but we need more information to debug.

**Comment by fejan92** [comment]
Sure.

Organization slug.
https://ukvi-compliance.sentry.io/

Gitlab Repo slug.
https://gitlab.com/ukvi-stable/ukvi-website-portal

**Comment by cathteng** [comment]
I see the error on our side as `The requested GitLab group ukvi-stable/ukvi-website-portal could not be found.` which is coming from GitLab. Is the group path `ukvi-stable` or `ukvi-stable/ukvi-website-portal`? The documentation asks for the group path (step 4 in https://docs.sentry.io/organization/integrations/source-code-mgmt/gitlab/)

**Comment by fejan92** [comment]
This is my group with url

https://gitlab.com/ukvi-stable

Here is the repo URL which needs to integrate with sentry
https://gitlab.com/ukvi-stable/ukvi-website-portal

**Comment by cathteng** [comment]
The docs are asking for the group URL

From step 2:
> Find the GitLab Group Path in your group’s GitLab page. Groups might contain subgroups and projects. You should not specify the URL to any specific project, just to a group or subgroup.

**Comment by cathteng** [comment]
It should be the group path, please take a look at step 4 of the integration setup instructions.

> For example, if your group can be found at https://gitlab.com/my-group/my-subgroup, enter `my-group/my-subgroup`.

https://docs.sentry.io/organization/integrations/source-code-mgmt/gitlab/
