### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by kevinm416** [getsentry/sentry#72782]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I added the github sentry integration, but on the Sentry side it says it's not installed. I do see it on the github side.

<img width="956" alt="Screenshot 2024-06-14 at 9 44 46 AM" src="https://github.com/getsentry/sentry/assets/526698/09cd8c01-84eb-4e91-8af1-8f8a77125ffe">
<img width="921" alt="Screenshot 2024-06-14 at 9 45 13 AM" src="https://github.com/getsentry/sentry/assets/526698/efc92cc7-242f-45ae-8bd3-5a0eb2c202ab">

### Expected Result

I expect to see that the github integration is installed in Sentry after I finish configuring it.

### Actual Result

The github integration is not active in Sentry.
<img width="399" alt="Screenshot 2024-06-14 at 9 46 04 AM" src="https://github.com/getsentry/sentry/assets/526698/87737a5b-390b-44fb-94b5-8bc5dc8c6a80">

### Product Area

Settings - Integrations

**Comment by cathteng** [comment]
Have you tried removing the app and reinstalling? Did you see the page where you could add your repositories?

**Comment by malcium** [comment]
We are also running into the same issue.

**Comment by cathteng** [comment]
We also currently do not support linking a single GitHub organization / user to multiple Sentry organizations, please check if this may be the case. If you are seeing the "Configure" button when installing the integration it means the GitHub org or user already has the Sentry Github app installed.

**Comment by malcium** [comment]
> We also currently do not support linking a single GitHub organization / user to multiple Sentry organizations, please check if this may be the case. If you are seeing the "Configure" button when installing the integration it means the GitHub org or user already has the Sentry Github app installed.

Yes, it was already allowed for certain repositories within the same organization and sentry account. Those repositories also don't appear to be integrated fully.

**Comment by cathteng** [comment]
@malcium Could you please submit a support ticket with your org slug? We'd need to look at the specific configuration to debug more

**Comment by cathteng** [comment]
Closing this issue. If you're still experience this, feel free to reopen.
