### ISSUE TITLE
 Stack frame path doesn't match a source file artifact name - Release

### ISSUE THREAD

**Issue by jpabara** [getsentry/sentry#72836]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I can't seem to make work the sourcemaps in sentry for react native, for android builds. Code is still minified, and I tried different solutions from similar issues.

The message from Sentry issues page with the unminify button:
![image](https://github.com/getsentry/sentry/assets/124057872/964b20fa-b26d-45b1-aeb2-d35acd0b2321)

![image](https://github.com/getsentry/sentry/assets/124057872/021b0a50-c7b9-4d19-91ea-874eb3514d65)

The last source map uploaded, the dist value and release value matches the one above.
![image](https://github.com/getsentry/sentry/assets/124057872/3205ff63-f311-4cfd-9d3f-342cdd8f333f)

We can see the files uploaded match each other. They don't have a debugId because I'm using the "Releases" method.
![image](https://github.com/getsentry/sentry/assets/124057872/dd1779ed-2179-4a02-8f2a-33810a85314e)

The release, for some reason says it has 0 artifacts, I wonder if this is the problem.
![image](https://github.com/getsentry/sentry/assets/124057872/85fcca96-193a-47ba-b526-817b0549072c)

Relevant Versions:
    "@sentry/cli": "^2.32.1",
    "@sentry/react-native": "^5.23.1",
    "react-native": "0.74.2",
    
 Sentry init:
```
        if (!__DEV__) {
            Sentry.init({
                dsn: 'https://951816ca725c42dfaaebf74b424e441e@o1175091.ingest.sentry.io/6271698',
                // Set tracesSampleRate to 1.0 to capture 100% of transactions for performance monitoring.
                // We recommend adjusting this value in production.
                tracesSampleRate: 0.3,
                dist: '132',
                integrations: [
                    new Sentry.ReactNativeTracing({
                        // Pass instrumentation to be used as `routingInstrumentation`
                        routingInstrumentation,
                    }),
                ],
            })
        }
```

Using create react app, I used the wizard provided `npx @sentry/wizard@latest -i sourcemaps`, and tested many configurations, especially tested different paths for the artifacts location, the one with the most promising result was inside this folder:

`./android/app/build/generated`
    
This config as well as the commands that the wizard generates in package json: (I included the hardcoded release and dist flags for testing purposes) 

`sentry-cli sourcemaps inject --org onstageobra --project onstageobra --release com.onstageobra@20.0+132 ./android/app/build/generated && sentry-cli sourcemaps upload --org onstageobra --project onstageobra --release com.onstageobra@20.0+132 --dist 132 ./android/app/build/generated
`

Gave me the following result:

![image](https://github.com/getsentry/sentry/assets/124057872/e16a7e07-d72c-4ac7-90d0-dd3b2e640433)

I'm doing an assembleRelease command in order to be able to log production errors, and added a test button inside the app:

`<Button title="TRYYYY 2" onPress={() => { Sentry.captureException(new Error('TEST error')) }}></Button>`

### How are you getting stuck?

The error is being logged in the sentry issues page, but the code is still minified. I would appreciate any guidance, help or anything to make this work. 

Thank you!

### Where in the product are you?

Issues - Source Maps

### Link

https://onstageobra.sentry.io/issues/5495445605/?project=6271698&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0

**Comment by loewenheim** [comment]
Hi, thank you for the report, I will have a look.

**Comment by loewenheim** [comment]
The issue link you posted doesn't work for me, do you have another one?

**Comment by jpabara** [comment]
Yes sorry, here is a[ valid error](https://onstageobra.sentry.io/issues/5500247028/?project=6271698&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+dist%3A132&referrer=issue-stream&statsPeriod=7d&stream_index=1)

For now, only code lines from node_modules are being mapped correctly.

![image](https://github.com/getsentry/sentry/assets/124057872/568b3a3a-5adb-4108-b092-bc31e8827750)

Thank you for your help!

**Comment by jpabara** [comment]
Hey @loewenheim, are there any news with this issue? would really appreciate any help

**Comment by loewenheim** [comment]
Closing this for now, please let us know if we can help you further.
