### ISSUE TITLE
Stream Play/Pause button tooltip is wrong

### ISSUE THREAD

**Issue by satyanash** [getsentry/sentry#7284]
The Stream Play/Pause button has an invalid tooltip. 

Sentry: Sentry.io
Versions from **View Source**:
    sentry_version: 42bc969aa038d934cc80dd011b115af1ff412482
    release: 6706682de49171476d340027279c91d4debb4787

Browser: Chromium 63.0.3239.132 (Developer Build) (64-bit)
OS: ArchLinux 4.14.13-1-ARCH x86_64 GNU/Linux

![2018-02-16-131029_532x402_scrot](https://user-images.githubusercontent.com/1559596/36298070-2d3baa24-131c-11e8-8bf5-729601cf5b9b.png)

**Comment by MaxBittker** [comment]
thanks for the issue @satyanash
