### ISSUE TITLE
Session Replay tab for tracking a Metric across the session replay

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#72927]
### Problem Statement

User has a Custom Measurement for batterylevel on their spans+transactions in Android. They want to know batter at the start and end of each screen and be able to see if the battery level drops over a session replay, because the device is a payment terminal for swiping credit cards (in Android OS) and often is not plugged into a wall charger. They'd also like to see it release.

[Slack discussion](https://sentry.slack.com/archives/CDXAKMGTU/p1718706388918139)

**Attempted Workarounds**
Can't plot the screens (transactions)'s average battery levels from left-to-right in order that the screen occurs, in Dashboard Widgets, because the x-axis is not configurable like that. X-axis always represents linear time too.

Performance dashboard shows the screens, but stacked vertically and not in order in which the screens occur. It's also a Table, but a visual will be nicer.

### Solution Brainstorm

![image](https://github.com/getsentry/sentry/assets/8920574/85e784bb-4379-44e8-8aba-05d5b011786d)

### Product Area

Unknown

**Comment by ryan953** [comment]
Metrics are going away :(

**Comment by thinkocapo** [comment]
and now they're coming back @ryan953
