### ISSUE TITLE
Dynamic Remote Config

### ISSUE THREAD

**Issue by bfpepper87sentry** [getsentry/sentry#72932]
### Problem Statement

Right now there are very few options for inbound filters in the UI. Would like a way to set inbound filters that could do sampling as well. This would be primarily for Mobile use case as there is no way to update dynamically change sample rates in older version of a mobile app. 

### Product Area

Releases

**Comment by MichaelSun48** [comment]
Hey there @bfpepper87sentry, thanks for the feedback on our new Inbound Filters feature! Filter options for older mobile apps seems pretty analogous to the inbound filters we have for old browsers, so this is a reasonable ask. I'll flag this GH issue as a feature request for now and relay it to the right person internally to see how we can get this prioritized!

**Comment by bruno-garcia** [comment]
@bfpepper87sentry Could you expand on the use cases where you decide to ignore some devices?
Is that like a specific Android version is too old? Or releases of your app that are too old?

**Comment by cmanallen** [comment]
You can use custom inbound filters: https://docs.sentry.io/concepts/data-management/filtering/#how-custom-filtering-works.  AFAIK sampling events is unsupported within the inbound-filters feature.
