### ISSUE TITLE
Mobile replay tap events - shows multiple at the same time

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry#72959]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

assuming a replay with multiple tap events
1. click on the last event
2. click on the previous one
3. etc

### Expected Result

only the currently selected tap is rendered (as before)

### Actual Result

all taps stay rendered

![image](https://github.com/getsentry/sentry/assets/6349682/cc8c115b-9fb1-4d02-b82e-80cbac9814e8)

### Product Area

Replays

### Link

https://sentry-sdks.sentry.io/replays/698dbb072c734a76bc78cbd2bfaed07c/?project=5428561&query=&referrer=%2Freplays%2F&statsPeriod=7d&yAxis=count%28%29

**Comment by michellewzhang** [comment]
https://github.com/getsentry/sentry/assets/56095982/576af346-f9e8-4364-9c06-b3a647852e02

i'm seeing this, not what's in the screenshot

**Comment by vaind** [comment]
https://github.com/getsentry/sentry/assets/6349682/344e13c8-d40b-4145-99af-e92ff602f115

**Comment by michellewzhang** [comment]
ah sorry, missed the repro steps, i'll look into it
