### ISSUE TITLE
[Jira Integration] Alternating auto assignment

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#72999]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create an Issue in Jira
2. Pick an Issue in Sentry and link it to the Jira Issue
3. Assign this Sentry issue to a user
4. Pick another Issue in Sentry and link it to the same Jira Issue
5. Assign this Sentry issue to a different user

### Expected Result

All Sentry issues keep their original assignees

### Actual Result

The first Sentry issue gets reassigned to the second user.

Having multiple Sentry issues linked to the same Jira issue seems to be influencing issue ownership. Whenever one of them changes owner, the others will automatically change to the new owner too.
![Untitled](https://github.com/getsentry/sentry/assets/81985895/da7866fe-8b5f-44fa-9112-b84ead5c20f2)

### Product Area

Settings - Integrations

**Comment by cathteng** [comment]
Hi, this feature is currently unmaintained, but we will keep track of this issue.

**Comment by GabeVillalobos** [comment]
This should have been addressed via https://github.com/getsentry/sentry/pull/77754, closing this issue as it should no longer be a problem.
