### ISSUE TITLE
Wizard "return to terminal" page should not show "view issues" and "see docs" button

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry#72993]
![Screenshot 2024-06-19 at 11 00 09](https://github.com/getsentry/sentry/assets/8118419/c72424eb-2128-4a52-bcd2-cc18a6ed3d9b)

It's just distracting. Padding is off too.

**Comment by benvinegar** [comment]
I think the padding needs adjustment, and for future, the whole design needs some love.
