### ISSUE TITLE
Sentry dashboard enhancement - Add Event Stats Dataset

### ISSUE THREAD

**Issue by sp1rs** [getsentry/sentry#73006]
### Problem Statement

Enhance the sentry dashboard by looking into the error/txn quotas for projects. This can be done if we have information like billing periods and quotas in the dashboard datasets.

### Solution Brainstorm

I would like to see the following feature in the sentry dashboard.
1. Have a new option in the datetime filter in the dashboard where we can select billing periods.
2. Spend allocation datasets used in the dashboard.

### Product Area

Dashboards

**Comment by Dhrumil-Sentry** [comment]
@sp1rs Does the existing Stats page not meet your requirements for tracking usage across projects?

**Comment by sp1rs** [comment]
@Dhrumil-Sentry It can be used but it is very difficult to go through when you have 100s of projects. Also, everything in one dashboard will make it much easier to monitor and navigate.

**Comment by alexjillard** [comment]
@sp1rs Thanks for the feedback, unfortunately this is not something we're looking to support in Dashboards at this time, however I'll pass your feedback along and we can consider some updates to the Stats page to make it more suitable for the use case you're describing.
