### ISSUE TITLE
Filtering in performance view, for async jobs

### ISSUE THREAD

**Issue by sandstrom** [getsentry/sentry#73000]
### Problem Statement

Right now, it's split into frontend, backend and mobile.

![CleanShot 2024-06-19 at 14 26 33](https://github.com/getsentry/sentry/assets/122287/7eacfadc-3570-4132-88e0-acf4cdbfb6fc)

The backend category will contain both our HTTP endpoints and async jobs.

It would be nice if we could quickly separate http endpoints from async jobs, since the performance requirements are somewhat different from these groups (700ms is slow for an endpoint, but generally okay for an async job).

### Solution Brainstorm

Maybe a group for 'async' or worker (in our case it's Sidekiq / ActiveJob, but might be other type of async work in other systems).

Or, if we could filter the list somehow, to only show HTTP endpoints, or only show async jobs.

### Product Area

Performance

**Comment by Dhrumil-Sentry** [comment]
Thanks a lot for this feedback, Adding it to our backlog

**Comment by DominikB2014** [comment]
Hey @sandstrom, this issue will be resolved by https://github.com/getsentry/sentry/issues/79197
In this ticket, we are suggesting a free formed search bar in the performance overview pages allowing you to search by transaction attributes. This means you could do a query like `transaction.op:async-job-op` on the performance overview page, and see a list of async jobs.

I'm going to close this in favour of that issue!

**Comment by sandstrom** [comment]
> This means you could do a query like transaction.op:async-job-op on the performance overview page, and see a list of async jobs.

Great! 🎉
