### ISSUE TITLE
CODOWNERS evaluation flow was not followed - last matching rule did not define assignment

### ISSUE THREAD

**Issue by serglom21** [getsentry/sentry#73021]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I have a CODEOWNERS file linked to Sentry with the following rule `codeowners:/app/processing_unit.rb #processing-team` on line **1237** and a rule `codeowners:*payment* #payments` on line **759**. I have the following stacktrace:

File "/app/payment_service.rb", line 13, in block in call
File "/app/processing_unit.rb", line 63, in charge!
File "/app/processing_unit.rb", line 174, in call!
  
[Customer Case](https://www.notion.so/sentry/CODEOWNERS-evaluation-flow-not-respected-d1666ac8767e4b96b263184890338e62?pvs=4)

### Expected Result

I would expect that based on the [evaluation flow](https://docs.sentry.io/product/issues/ownership-rules/#evaluation-flow), the `#processing-team` would have been assigned to the issue since this rule is lower than the `#payments` rule

### Actual Result

The issue was assigned to the `#payments` team

### Product Area

Issues

**Comment by mrduncan** [comment]
Thanks, we plan on investigating in the next couple of weeks and will follow up again then.

**Comment by mattthaber** [comment]
Have seen similar issues on our end with code owners in which a codeowners setup like....

```
codeowners:* #team-one
codeowners:/some/path/ #team-two
```

is always assigning to the first matched wildcard, and not respecting our codeowner matches that match on folders.

**Comment by mrduncan** [comment]
Sorry for the lack of follow up here folks, this is still on our roadmap but we have not had a chance to investigate yet. For transparency, we are allocating additional resources in the next few months to resolve a number of codeowners related issues.
