### ISSUE TITLE
Project slug length limit

### ISSUE THREAD

**Issue by beloniki-flant** [getsentry/sentry#73032]
### Problem Statement

Hey 👋 
Is there any opportunity to change max size of project's slug field?
This request is based on UX, 50 chars is not quite enough.
By project convention, used in our company, some project's names can be longer than 50 chars, so we face char limit in "slug" field.

Thanks

### Product Area

Settings - Projects

**Comment by markstory** [comment]
> By project convention, used in our company, some project's names can be longer than 50 chars, so we face char limit in "slug" field.

How long do project names get?

**Comment by beloniki-flant** [comment]
> How long do project names get?

It seems that a length of 100 characters will cover all of our needs

**Comment by beloniki-flant** [comment]
Hi
Any news?

**Comment by leedongwei** [comment]
@beloniki-flant I've scheduled it but there are competing priorities at the moment.

**Comment by schew2381** [comment]
@beloniki-flant Hi there, sorry for the delay but I've finally updated the project slug character limit. I've confirmed that it allows up to 100 characters now.

Let me know if you run into any other issues!
