### ISSUE TITLE
Order of context sections in TraceView should be same as in an Issue View for a unified experience

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#73042]
### Problem Statement
The sections tags context sessionreplay breadcrumbs are in very separate orders between these 2 views. Feels strange when trying to find what you're looking for in one verse the other, feels like too much of a hunt, because it's not consistent between the two UI's (TraceView vs Issue). It feels a bit like, “I wonder what section will displays next as I keep scrolling downward”

The 4 sections that **both** Views share are Tags Context SessionReplay Breadcrumbs

**TraceView sections in vertical order, moving downwards:**
Context (General, TraceData, SDK)
_Tags
Context
SessionReplay
Breadcrumbs_

**Issue View sections in vertical order, moving downward**
EventHighlights
Stacktrace
_SessionReplay
Breadcrumbs
Tags
Context_

TraceView
<img width="1745" alt="image" src="https://github.com/getsentry/sentry/assets/8920574/7a7437a6-ec2f-45c2-89e6-7ac6e31718e3">

IssueView
<img width="1765" alt="image" src="https://github.com/getsentry/sentry/assets/8920574/2b50707a-b3d2-41fe-9225-4c917dbb081e">

### Solution Brainstorm

The 4 sections that both Views share are:
Tags
Context
SessionReplay
Breadcrumbs

Maybe put them in same order? Optional. To think about

### Product Area

Issues

**Comment by Dhrumil-Sentry** [comment]
Thanks for this feedback, we're going to audit this and try bringing more consistency but we don't have a timeline yet

**Comment by alexjillard** [comment]
Closing this for now, the ordering and grouping of these sections has changed, and will likely continue to change as we move towards Otel compatibility. We may not aim for total alignment between the two product areas, but rather try to prioritize the most relevant information.
