### ISSUE TITLE
[User Feedback] spam detection should filter messages uniformly without taking into account capitalization

### ISSUE THREAD

**Issue by michellewzhang** [getsentry/sentry#73066]

**Comment by ryan953** [comment]
Original Message that was marked as spam: https://demo.sentry.io/feedback/?feedbackSlug=react%3A5513579551&mailbox=ignored&project=5808623&referrer=feedback_list_page&statsPeriod=90d
Username: `Angry`
Message: `THis was slow and then I cant buy`

Another message, not marked as spam: https://demo.sentry.io/feedback/?feedbackSlug=react%3A5513619151&mailbox=unresolved&project=5808623&referrer=feedback_list_page&statsPeriod=90d
Username: `Ryan`
Message: `This was slow and then I cant buy`


We think that the mixed casing "THis" vs "This" messed up the filter. Both messages should not be marked as spam

**Comment by drguthals** [comment]
I don't know how the model works , but similar potential things to explore if we are looking at adjusting this:
- Common mis-spellings (isn't automatically spam)
- Apps that want to leverage UF for other spoken languages

**Comment by aliu39** [comment]
> We do not take into account the name for spam detection
I think it makes sense for name/email to not be taken into account, since it could confuse the model. Since we allow anonymity/empty values for these 2 fields, we don't do any validation on them

**Comment by aliu39** [comment]
There's 2 approaches for solving this:
1. lower case the whole feedback message before passing it to the LLM. Surefire fix.
2. Include verbal instructions to "ignore casing and make a best guess at misspellings" in the prompt. Could be more robust.

Both should have no problem solving the casing issue. I'll try out different instructions for the misspellings. Something to think about is how badly a word can be misspelled before being interpreted as junk
