### ISSUE TITLE
Add 1h timeframe to issue details page

### ISSUE THREAD

**Issue by DeeVine** [getsentry/sentry#73076]
### Problem Statement

The 1h timeframe in the issues tab is helpful to see the immediate trend of issues as they are escalating and triaged. Can the the 1hr timeframe also be made available on the issue details page for devs to view there? 

Issues tab with 24h and 1h:
<img width="233" alt="image" src="https://github.com/getsentry/sentry/assets/4958063/bc92dc7d-5b9b-40ef-b451-f2913792da01">

Issue details with only last 24 Hours:
<img width="344" alt="image" src="https://github.com/getsentry/sentry/assets/4958063/4232fbbb-d881-4151-99d2-c8ed40186c90">

### Solution Brainstorm

Perhaps have an option to toggle on the 1hr time frame in the issue details page, like how the issues tab has a 24h and 1h toggle.

### Product Area

Issues

**Comment by malwilley** [comment]
Thanks for the request! This is very similar to https://github.com/getsentry/sentry/issues/64466 so I'll close this one in favor of the other.

We are in the process of designing a new experience where you will be able to customize the time range of all the information shown in issue details. Stay tuned!
