### ISSUE TITLE
Changes to table(s)

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#73156]
We should only have one table for the configured metrics. We have a temporary state where some customers might have the "old custom metrics" for a period of time as well as configure new metrics from span attributes. 
- The second table is only visible if there are old custom metrics. New customers only see the new table.
- The new table lists the configured metrics with the columns: Span Attribute, Filters, Cardinality and Actions
   - the attribute is clickable and leads the customer to the Metrics explorer with the attribute selected
   - the edit action opens the configuration panel 

Figjam [link](https://www.figma.com/board/hQp48I2NH6s7m1JwJh3508/Exploration%3A-Metric-Extraction-Page-v2?node-id=0-1&t=AtOR0cHARy1fhrJA-0).

**Comment by ArthurKnaus** [comment]
To query the cardinality, I need the MRIs that are generated by the extraction rule.
@shellmayr could we include the MRIs in the response of the extraction rules endpoint?
