### ISSUE TITLE
Better support for many feature flags.

### ISSUE THREAD

**Issue by bfpepper87sentry** [getsentry/sentry#73187]
### Problem Statement

We have ~300 feature flags in some sessions and are currently sending them as tags which is Sentry's recommendation. However, this makes the interface VERY noisy and you have to scroll a lot to find the info you need.

### Solution Brainstorm

How Bugsnag handles this: Bugsnag has a separate tab for Feature Flags so they don't pollute the UI. Sentry's Feature flag system is overall better, but their visualization as part of "tags" makes them create a lot of clutter and hide other important information.
What we'd want: Ideally a separate tab for "Flags" or something similar to bble to view all of them. The side menu should put feature flags at the bottom so that they do not hide the other more important tags.
How we can mitigate: Not much we can do. One option is prefixing all the feature flags with a character that makes them always be ordered last and easy to identify. Although this is not great and probably Sentry's biggest flaw, we believe the other benefits still make it worth it.

### Product Area

Other

**Comment by roggenkemper** [comment]
thanks for the feedback! just to clarify one point you made - you mentioned that "Sentry's feature flag system is overall better". is this referring to how we represent the feature flags as tags right now? if i'm understanding correctly, you like how we present the information but because it is sent as a tag, it's too cluttered, so having a separate tab, with a similar presentation of the info, would help.

**Comment by jas-kas** [comment]
@bfpepper87sentry 

> What we'd want: Ideally a separate tab for "Flags" or something similar to bble to view all of them. The side menu should put feature flags at the bottom so that they do not hide the other more important tags.

Can you elaborate on the problem you're trying to solve by showing Feature Flags all in one place (say, a separate tab). What is the utility of this?

**Comment by bfpepper87sentry** [comment]
responded to the above question internally.

**Comment by cmanallen** [comment]
We've recently released support for feature flags.  You can learn more here: https://docs.sentry.io/product/explore/feature-flags/

We'll be adding support for more providers in the coming months.
