### ISSUE TITLE
npm ERR! Could not install from "@sentry/cordova@~0.6.0" as it does not contain a package.json file.

### ISSUE THREAD

**Issue by schumannd** [getsentry/sentry#7320]
I have reproduced this error twice now in my cordova project.

When running `cordova plugin add @sentry/cordova` everything seems to install fine.

I however can't then require the model in code

Upon trying to uninstall using `cordova plugin remove sentry-cordova`, I get the following error:

```
Uninstalling sentry-cordova from ios
Removing "sentry-cordova"
Error: npm: Command failed with exit code 1 Error output:
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@sentry/cordova@~0.6.0" as it does not contain a package.json file.
```

cordova: 7.1.0
cordova-android: "^6.3.0"
cordova-ios: "^4.5.4"

plugins:
com.telerik.plugins.nativepagetransitions 0.6.5 "Native Page Transitions"
cordova-plugin-badge 0.8.1 "Badges"
cordova-plugin-compat 1.1.0 "Compat"
cordova-plugin-customurlscheme 4.3.0 "Custom URL scheme"
cordova-plugin-device 1.1.6 "Device"
cordova-plugin-dialogs 1.3.3 "Notification"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-file-transfer 1.6.3 "File Transfer"
cordova-plugin-media 3.0.1 "Media"
cordova-plugin-nowplaying 1.0.0 "NowPlaying"
cordova-plugin-remotecommand 1.0.0 "RemoteCommand"
cordova-plugin-statusbar 2.2.3 "StatusBar"
cordova-plugin-whitelist 1.3.2 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
phonegap-plugin-push 1.10.5 "PushPlugin"
skwas-cordova-plugin-datetimepicker 1.0.0 "DateTime picker"

listed in my package.json under dependencies:
```
"@sentry/cordova": "^0.6.0",
...
"sentry-cordova": "@sentry/cordova@~0.6.0",
...
```

Is this a sentry wizard bug?

**Comment by SpellChucker** [comment]
I found that removing the `sentry-cordova` line in `package.json` fixes the issue. I think the `cordova plugin add @sentry/cordova` command inserts this entry?

**Comment by schumannd** [comment]
Yes, it inserts this entry. So I should remove it after it was inserted?

Does it fix the whole package not working in the first place, or does it just fix the removal command?

**Comment by SpellChucker** [comment]
I believe it just fixes the adding/removal command. I had those entries in my `package.json`, then I did a `rm -r node_modules` and tried an `npm i` but it failed with the same error. So I had to remove it from my `package.json`. I don't think this is ideal, because the cordova plugin uses it. I need to do more testing to see if this actually breaks the package or not.

**Comment by HazAT** [comment]
Thx @schumannd for creating this, I moved it to https://github.com/getsentry/sentry-cordova/issues/19
Also ty @SpellChucker for responding 👍
