### ISSUE TITLE
Outgoing Email - `Heads Up  - your Tracing trial ends soon` lists incorrect URL

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#73209]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

The outgoing email sent by Sentry when the Tracing trial is ending has a line that goes - 

"Explore Traces" The url for that line is `<orgslug>.sentry.io/spans/`.   This link goes nowhere and redirects to the main page.  Should the url be `<orgslug>.sentry.io/traces/` instead?

### Expected Result

Link leads you to somewhere under the Explore tab

### Actual Result

Link redirects to the issues page.

### Product Area

Performance

**Comment by Dhrumil-Sentry** [comment]
@brianthi is looking into this
