### ISSUE TITLE
Profiling with ts-node / express

### ISSUE THREAD

**Issue by anuraagy** [getsentry/sentry#73234]
### Problem Statement

We have an express/node/typescript backend and we set up Sentry profiler. However, most of the functions are showing up in the profiler with name "fulfilled" or "__awaiter". Any idea why that might be happening? 

We use ts-node to run our application!

### Product Area

Profiling

**Comment by anuraagy** [comment]
HI @JonasBa , thank you for the response. Is there any way around this? At this point the profiler isn't super useful because we don't have the function level insights anymore.

**Comment by JonasBa** [comment]
@anuraagy I need to take some time and see what might be some possible workarounds. Would you mind sharing how these frames look like in the profiling product?
