### ISSUE TITLE
Can not delete users using internal integrations token and API

### ISSUE THREAD

**Issue by RedShiba** [getsentry/sentry#73249]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

25.0.0

### Docker Compose Version

2.24.1

### Steps to Reproduce

1. Create internal integration (Settings -> Custom Integrations -> Create New integration -> Internal Integration)
2. Provide the following permissions to your integration: member:admin, member:read, member:write. 
3. Get token.
4. Try to delete member from sentry using sentry API. (https://docs.sentry.io/api/organizations/delete-an-organization-member/)

Maybe I do smth wrong and this custom integration is not intended for this purpose?

### Expected Result

User is deleted.

### Actual Result

Some users can not be deleted via API. I'm getting an error like:  400 Bad Request "{"detail":"You cannot remove a member who has more access than you."}".

But I can successfully delete users from UI using my own account(I'm owner).

**Comment by Dhrumil-Sentry** [comment]
We're not going to support destructive actions like deleting users via an API.
