### ISSUE TITLE
User Feedback route returns HTTP 400 Invalid Origin despite configuration to allow all origins

### ISSUE THREAD

**Issue by Gudahtt** [getsentry/sentry#7324]
The route used to POST user feedback consistently returns HTTP 400 with the message `Invalid origin: [origin]`.

I have configured Sentry to accept all origins by adding the line `SENTRY_ACCEPT_ORIGIN = '*'` to `sentry.conf.py`. So in theory, I should never be getting that message, as it should accept requests from any origin.

- Sentry version: 8.22
- Docker method used, following steps here: https://github.com/getsentry/onpremise

The only change made to `sentry.conf.py` was the line mentioned above.

**Comment by dcramer** [comment]
You likely need to configure this within project settings, as it uses the Allowed Domains from an individual project.

**Comment by Gudahtt** [comment]
We have the `Allowed Domains` setting for each project set to `*`, which I understand to mean that all domains are allowed.

**Comment by heartbeatLV** [comment]
same

**Comment by bkiss-crey** [comment]
same issue, allowed all domains and it works for error reporting but not working for the user feedback API :/
