### ISSUE TITLE
Link to doc on archived issue is broken

### ISSUE THREAD

**Issue by fwolfst** [getsentry/sentry#73260]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When an issue has been archived, a banner informs the user about it. The banner includes a link that should go to the docs but lands on 404. (Link is `read the docs` => https://docs.sentry.io/product/accounts/early-adopter-features/issue-archiving/)
![image](https://github.com/getsentry/sentry/assets/219373/32893c1b-743b-404e-8e2d-c0f475bab36e)

### Expected Result

Link should point somewhere helpful.

### Actual Result

The banner includes a link that should go to the docs but lands on 404.
![image](https://github.com/getsentry/sentry/assets/219373/32893c1b-743b-404e-8e2d-c0f475bab36e)

### Product Area

Issues

**Comment by fwolfst** [comment]
Will provide a PR

**Comment by MichaelSun48** [comment]
Hey @fwolfst, thanks for catching and surfacing this! I've put up a PR (#73307) to fix the link, you should see the changes reflected today.

**Comment by fwolfst** [comment]
> Hey @fwolfst, thanks for catching and surfacing this! I've put up a PR (#73307) to fix the link, you should see the changes reflected today.

@MichaelSun48 ? Like announced, I did set up a PR already https://github.com/getsentry/sentry/pull/73261 and also outlined another possible improvement in it .

**Comment by fwolfst** [comment]
But thanks.

**Comment by MichaelSun48** [comment]
@fwolfst 🤦 I totally missed your PR in the issue description, so sorry about that. 

About your suggested changes - I also agree that this banner would be a great place to surface our docs on how we define an "escalation". Let me relay your suggested copy internally and see what the best way to improve it is.
