### ISSUE TITLE
Broken Performance URLs after upgrading from 24.3.0 to 24.6.0

### ISSUE THREAD

**Issue by flottes** [getsentry/sentry#73270]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

I updated my instance from 24.3.0 to 24.6.0.
I have the Problem, that all Sub-Menu Entries from Performance (Queries, Requests, Caches, Web Vitals, Queues, Screen Loads, App Starts, Assets) are Broken. I get the Messages "The organization you were looking for was not found." OR "Page Not Found".

I noticed that the URL seems missing the "/organizations/org-slug/" part. For Queries its now sentry.example.com/insights/database/ but it should be sentry.example.com/organizations/org-slug/insights/database/. When I add the /organizations/org-slug/ part, it works for Queries, Requests, Web Vitals, Screen Loads, App Starts and Assets

For "Caches", "Queues" and "LLM Monitoring" I get the response "You don't have access to this feature". These menu entries are new after the update to 24.6.0

### Expected Result

I expect the menu-entries to work.

### Actual Result

"The organization you were looking for was not found.":
![CleanShot 2024-06-25 at 11 51 49@2x](https://github.com/getsentry/sentry/assets/26257324/daf8a1c7-f5a0-4ff9-8d0b-131a083efba3)

"Page Not Found":
![CleanShot 2024-06-25 at 11 52 59@2x](https://github.com/getsentry/sentry/assets/26257324/5f8c8f28-0566-440d-9379-dcc91134a142)

### Product Area

Performance

### Version

24.6.0

**Comment by baubie** [comment]
I am seeing this behaviour on a completely fresh install of 24.6.0

**Comment by gggritso** [comment]
@flottes thanks for raising this, sorry about the linking confusion! This issue will be fixed by https://github.com/getsentry/self-hosted/pull/3152 which hopefully will make it into the next release 🙌🏻 

In the meantime, you can fix this issue for your own install by adding a few feature flags to your config. See https://github.com/getsentry/self-hosted/issues/3145 for details

**Comment by flottes** [comment]
This solves the problems for me. Thank you for your efforts and for making such a great product!

**Comment by gggritso** [comment]
@flottes great! Sorry again, and thank you for your patience. Closing!
