### ISSUE TITLE
Compressed minidump does not upload

### ISSUE THREAD

**Issue by xenomeno** [getsentry/sentry#73288]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Hello,

I am trying to upload compressed minidump with compressed with 7-zip:

```
curl -X POST \
  'https://o0.ingest.sentry.io/api/0/minidump/?sentry_key=examplePublicKey' \
  -F upload_file_minidump=@default.dmp.gz
```

But the file does not appear next to the other issues. I've tried both with -H "content-encoding: gzip" and without it but no luck in both cases. When the minidump is not zipped it appears straight away as a new crash. Executing curl finishes with:

```
{"detail":"invalid minidump"}
```

What am I missing?

Thank you

### Expected Result

compressed minidump to upload as a regular one

### Actual Result

The compressed minidump is not uploaded.

### Product Area

Unknown

**Comment by jjbayer** [comment]
> However I want also to upload a text file default.log along with the minidump in the same event.

@xenomeno you have two options:

1. Instead of putting a gzipped dump in multipart data, put the raw minidump there and encode the entire request instead. Unfortunately cURL does not support this out of the box.
2. Attach the log file to the event with an additional request. The minidump endpoint returns the event ID in plain text, and you can send additional attachments to `/api/:project_id/events/:event_id/attachments/`.

The third option would be not compressing anything.

**Comment by xenomeno** [comment]
Hello, 

Thank you for your reply. I've tried separating into two curl commands. Using the event_id returned by the first one with the compressed minidump(which gets registered in the senty website) and executing the second one I get this:

```curl --globoff -X POST "https://o313068.ingest.sentry.io/api/5844244/events/e1cbecb4d1b2479dbbffd4f94947062d/attachments/" -H "Authorization: Bearer MY_PUBLIC_KEY"  -F upload_file_minidump=@"default.txt" -v
Note: Unnecessary use of -X or --request, POST is already inferred.
* Host o313068.ingest.sentry.io:443 was resolved.
* IPv6: (none)
* IPv4: 34.120.195.249
*   Trying 34.120.195.249:443...
* Connected to o313068.ingest.sentry.io (34.120.195.249) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.x
> POST /api/5844244/events/e1cbecb4d1b2479dbbffd4f94947062d/attachments/ HTTP/1.1
> Host: o313068.ingest.sentry.io
> User-Agent: curl/8.7.1
> Accept: */*
> Authorization: Bearer MY_PUBLIC_KEY
> Content-Length: 108105
> Content-Type: multipart/form-data; boundary=------------------------KtKxX84TZS2PFzuxwHdqmW
>
* upload completely sent off: 108105 bytes
* schannel: remote party requests renegotiation
* schannel: renegotiating SSL/TLS connection
* schannel: SSL/TLS connection renegotiated
< HTTP/1.1 401 Unauthorized
< Server: nginx
< Date: Thu, 27 Jun 2024 11:29:56 GMT
< Content-Type: application/json
< Content-Length: 46
< access-control-allow-origin: *
< vary: origin,access-control-request-method,access-control-request-headers
< access-control-expose-headers: x-sentry-error,x-sentry-rate-limits,retry-after
< cross-origin-resource-policy: cross-origin
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
< Via: 1.1 google
< Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
<
{"detail":"missing authorization information"}* Connection #0 to host o313068.ingest.sentry.io left intact
```

Is this something about token access rights?

**Comment by xenomeno** [comment]
@jjbayer The second one worked just fine, thank you!

**Comment by jjbayer** [comment]
Great to hear!
