### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by skavish** [getsentry/sentry#73299]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I configured sentry github app, I see the app on my github account having access to selected repos, but sentry page says the app is not installed

### Expected Result

I expect the app to be installed

### Actual Result

it is not installed

### Product Area

Settings - Integrations

**Comment by cathteng** [comment]
Hello, could you please write into support with your org slug? We'd need more information to debug this.

**Comment by skavish** [comment]
it's `wavevideo`

**Comment by cathteng** [comment]
Closing this issue, if you're still experiencing this feel free to reopen.
