### ISSUE TITLE
In alert email, all links not work

### ISSUE THREAD

**Issue by evanushechkin** [getsentry/sentry#7334]
In the alert message sent, all links are relative, not added to system.url-prefix :. In the web interface, I see that the variable from the config file was picked up.

**Comment by evanushechkin** [comment]
version 8.22

**Comment by herman7** [comment]
I have same issues with sending user invite email

**Comment by SniperCZE** [comment]
Same problem here, self hosting sentry version 9.1.1. I have root url set in my config.yml but emails are still comming with wrong links like `<a href="/vshosting-devel/zerops/issues/25/?environment=local&amp;referrer=alert_email">`

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
