### ISSUE TITLE
Not able to view Query Summary

### ISSUE THREAD

**Issue by Shubhdeep12** [getsentry/sentry#73370]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

From trace detail -> view query summary

### Expected Result

Query summary

### Actual Result

Not sure, if this is removed for Free Tier, but right now getting this not found page

![image](https://github.com/getsentry/sentry/assets/43654389/a4088848-5461-4beb-8a66-f494a65c387d)

[Screencast from 06-26-2024 06:56:12 PM.webm](https://github.com/getsentry/sentry/assets/43654389/4b69fcda-9ef3-46f8-acc5-ff72b3143ed1)

### Product Area

Unknown

**Comment by gggritso** [comment]
@Shubhdeep12 thanks for raising this, sorry about the interruption! Your plan still has access to Query Summary, the "View Query Summary" button is linking to the wrong URL. This will be fixed in https://github.com/getsentry/sentry/pull/73539
