### ISSUE TITLE
Show session replay timestamp instead of duration in the timeline

### ISSUE THREAD

**Issue by rodrigopavan** [getsentry/sentry#73404]
### Problem Statement

The video timeline on Session Replay shows the video duration only. We're replacing our current monitoring tool to use Sentry and our company operation asked us that it's quite important to them to see the time that the event occurred in the timeline, instead of the duration. It's quite important during debug sessions. 

<img width="1482" alt="Screenshot 2024-06-26 at 18 28 31" src="https://github.com/getsentry/sentry/assets/11966529/f0885ba6-db8d-4b52-a8d4-a2e4d85c91c6">

### Solution Brainstorm

An idea would be to add an option where the user could set to consider the timestamp of the event. And it would show something like this:

<img width="1482" alt="Screenshot 2024-06-26 at 18 28 31" src="https://github.com/getsentry/sentry/assets/11966529/eaf43e1e-25f3-4996-904a-49e0ccb94984">

### Product Area

Replays

**Comment by jas-kas** [comment]
Hey @rodrigopavan 👋 

Thanks for your feature request. We show the timestamp when you hover over the replay duration in the Breadcrumbs, Console and Network tabs. The Breadcrumbs represent any key user interactions. Is there a particular reason why this would be helpful for the timeline? Appreciate your input.

**Comment by rodrigopavan** [comment]
Hi @jas-kas ! Our support operation currently makes use of LogRocket and they rely completely in the time-event once they receive a support for our internal users. It's simple for them to identify a problem once the user just say: `It was at 4:39 PM`

**Comment by rodrigopavan** [comment]
We're migrating to Sentry, and this was a point that they comply that could help them.

**Comment by jas-kas** [comment]
Hey @rodrigopavan, completely understand! 


[1] Within the replay, **you can see the actual time and day on hover, like shown in the screenshot. "8:33:20 AM"** in our Breadcrumbs tab.
![Screenshot 2024-07-02 at 8 34 41 AM](https://github.com/getsentry/sentry/assets/77064737/492682ae-e21a-458c-a069-d50af74603b0)

[2] Sentry also offers a way to narrow down the specific timeframe immediately from the Replay landing page, as well as the ability to search for specific user emails. This can be incredibly helpful when trying to find a user session that lines up with a specific support inquiry. 

![Screenshot 2024-07-02 at 8 33 35 AM](https://github.com/getsentry/sentry/assets/77064737/c47157f0-94a3-45fb-8b7a-8612c5cba323)

Will this meet your Support team's needs? Or is there something else that can be beneficial and why? Lmk!

**Comment by rodrigopavan** [comment]
It's not a straightforward process for our support team. 

Take a look at how LogRocket works:
![image](https://github.com/getsentry/sentry/assets/11966529/4f7115bf-3808-4c71-875c-3b4e5de0282f)

Our support navigate on the timeline using the event timestamp. Usually, our support mention that a problem occurs at 4:30PM for instance, the support team move the timeline bar close to the timestamp, it's easy for them to achieve this.  Sentry provide ways to accomplish that (by look at each event timestamp), but it's a more 'manually' process.

**Comment by jas-kas** [comment]
Makes sense, I will take this feature request back to the team and see the feasibility of implementing the timestamp into the timeline. :)

**Comment by marisahelena** [comment]
Hi @jas-kas, I hope you are well :) 
Are there any updates on this? If it's possible, could you please provide an estimation?

Given our support process, having the timeline for session replay would be really helpful (and I'd say necessary on time-sensitive issues) for our team.

Thanks in advance!

**Comment by bruno-garcia** [comment]
This is a very fair request and I personally also needed a timestamp before.
We've got this also here: 
* https://github.com/getsentry/sentry/issues/52682

At this stage we're talking about different UX/designs, no timeline yet to when it'll be live but we're making progress

**Comment by bruno-garcia** [comment]
We got designs shared on the other ticket. we'll close this as dupe. 

please follow https://github.com/getsentry/sentry/issues/52682
