### ISSUE TITLE
The engine "yarn" is incompatible with this module. Expected version ">=1.0.2".

### ISSUE THREAD

**Issue by AlmogRnD** [getsentry/sentry#7340]
Hi,
I updated my node version, npm version and now I'm getting the following error 

My project is react-native and using the provided react-native sdk with the wizard 

error @sentry/wizard@0.8.2: The engine "yarn" is incompatible with this module. Expected version ">=1.0.2".
error Found incompatible module

Thanks,
Almog

**Comment by AlmogRnD** [comment]
Closing this was able to fix this using nvm and setting the new node version

**Comment by baaart** [comment]
Is there any workaround if i would like to stay with yarn?

**Comment by yaneq** [comment]
@baaart `npm i -g yarn` fixed it for me

**Comment by rahul-desai3** [comment]
`npm i -g yarn` did not work for me
Node v11.0.0
Yarn v1.13.0
