### ISSUE TITLE
I want to be able to create alert for User Feedback created through API

### ISSUE THREAD

**Issue by barp** [getsentry/sentry#73415]
### Problem Statement

Support told me it's currently not supported.

I want to have it in order to have notifications about recieving feedback in our slack channel.

### Product Area

Alerts

**Comment by ceorourke** [comment]
Hello, we have a new-ish implementation of User Feedback that support alerts through Slack - the documentation can be found here https://docs.sentry.io/product/user-feedback/#getting-user-feedback-alerts for alerting and here https://docs.sentry.io/product/user-feedback/ more generally for user feedback issues.

**Comment by barp** [comment]
Hi, this is Wyatt we tried to use but customer support said it didn't work
if we use user feedback through the API and add the said it doesn't work...

**Comment by aliu39** [comment]
Alerts should be supported for all creation sources and configured the same way. @barp are alerts not working for your team?

**Comment by barp** [comment]
No and support specifically said it doesn't work when created through the
API

**Comment by aliu39** [comment]
Got an update. Can you check if the project option "Enable Crash Report Notifications" is turned on? At sentry.io/settings/projects/feedback/
<img width="942" alt="Screenshot 2024-06-27 at 2 22 37 PM" src="https://github.com/getsentry/sentry/assets/159852527/6fde07d8-6de8-4e14-ac6e-6fdef1ec1623">

**Comment by barp** [comment]
After enabling it works.
