### ISSUE TITLE
Onboarding Updates for Span-based Metrics

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#73420]
**Problem**: The current empty state of the Metrics explorer page is still focused around setting up the "old" custom metrics. We need to update it to reflect the new way of configuring metrics from span attributes.

**Solution**:

**(1) If they’re already using performance and don't have old custom metrics**
- Show the explorer page
- Remove the banner to set up custom metrics
- In the query 3 dot menu - Update “Metric Settings” so it’s not disabled for the out-of-the-box metrics (e.g. span.duration), but leads to the “Configure Metrics” screen with the attribute pre-selected
- Show button "Add New Metric" on top right that leads the customers to the Metrics Settings page.

![Image](https://github.com/getsentry/sentry/assets/26696515/4143a936-f876-4497-b907-c81607c51673)

![Image](https://github.com/getsentry/sentry/assets/26696515/73fb7b33-4594-45f9-8f27-51f9300e669c)

**(2)  If they’re not using performance and don't have old custom metrics**
- Update Description
  - Track and solve what matters
  - “Query and plot metrics extracted from your span data, to visualise trends and identify anomalies. To get started, you need to enable tracing (https://docs.sentry.io/concepts/key-terms/tracing/).”
- Update CTA button
  - “Set Up Tracing” links to Tracing setup docs (https://docs.sentry.io/product/performance/getting-started/)

**(3) First visit to the Metrics page**
- Remove Modal with beta disclaimer (we would need to update it, it does not feel worth it at this point since there is a warning on the page already about the upcoming API changes)

![Image](https://github.com/getsentry/sentry/assets/26696515/9d4b94d1-691d-4dde-bbce-dc02d1c5e617)

**(4) If they have old custom metrics**
- Display red banner telling them that this old method is deprecated
   - Description: "We've released a new API to submit metrics. Metrics using with the old API will stop being ingested on XX/YY. Learn more [link to docs or help article will be provided later]."
- CTA on top right is renamed from "Add Custom Metric" to "Add New Metric" and instead of opening the setup instructions panel, it leads the customers to the Metrics Settings page.
- The rest continues to work the same
  - Clicking on Metrics Settings brings them to the Metric Details page as-is

![Image](https://github.com/getsentry/sentry/assets/26696515/59cfcfd4-3efa-4247-a0f8-2cc57f4031e4)

**Comment by priscilawebdev** [comment]
First of all, thank you for explaining the issue so thoroughly 🙏 🚀

Here is my feedback:

**(1) If they’re already using performance**
The Metrics button in the 3 dots menu seems too hidden. How can we make customers more aware of the metrics settings?

**(3) First visit to the Metrics page**

- In my brand-new organization, I was surprised to be immediately presented with a modal upon visiting the metrics page. I don't know why we chose this option, but wouldn't improving the displayed banner behind it be sufficient? - Although it seems we now want to remove it as you mentioned in item 3.

**Comment by priscilawebdev** [comment]
@ale-cota shall we also say "Set Up Trace" instead of "Set Up Performance Monitoring" here?

![image](https://github.com/getsentry/sentry/assets/29228205/9b89d85c-7ac3-43e9-82c1-f8430fc0d615)
