### ISSUE TITLE
403 error on website

### ISSUE THREAD

**Issue by night-fury-web** [getsentry/sentry#73459]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

When I open error link on website, it shows 
```
Error: Forbidden
our client does not have permission to get URL /issues/abcdef/ from this server.
```

### How are you getting stuck?

I couldn't see error content.
I think it's because of proxy I use. Does sentry block some IP addresses?

### Where in the product are you?

Issues

**Comment by mrduncan** [comment]
Hi @night-fury-web, are you able to reproduce this in another browser? If so, our support team is better equipped to assist - you can open a ticket over at https://help.sentry.io/.
