### ISSUE TITLE
Unable to get Source Maps working with Debug ID

### ISSUE THREAD

**Issue by baubie** [getsentry/sentry#73511]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Trying to get source maps to work with an internal Vue app with self-hosted Sentry. We are on the latest version of Sentry, Webpack Plugin, and Vue Sentry SDK as of this morning (June 28).

### How are you getting stuck?

We are using the `sentryWebpackPlugin` to upload source maps.  Debug IDs are set, they are being sent with errors, source artifacts are uploaded, but nothing is working. 

![image](https://github.com/getsentry/sentry/assets/292411/e4cbbb8f-70e0-472d-a26c-88ad29d8d823)

Clicking on **Unminify Code** it tells us everything looks good:
![image](https://github.com/getsentry/sentry/assets/292411/e6bef480-6f74-40f7-b12a-22d9514f9709)

Looking at the raw event JSON we see the `debug_meta` field:
```
"debug_meta":{"images":[{"code_file":"http://localhost/static/js/app.43e39073ab510c561674.js","debug_id":"1b48b47e-183c-4028-b5e5-d1bef3ec7bed","type":"sourcemap"}]},"environment":"production","errors":[{"type":"js_no_source","symbolicator_type":"missing_source","url":"http://localhost/static/js/app.43e39073ab510c561674.js"}
```

Uploading the source map says it was fine:
![image](https://github.com/getsentry/sentry/assets/292411/9e221e66-1b42-413d-b56a-a4e244b3f9ca)
![image](https://github.com/getsentry/sentry/assets/292411/6d2c190c-86f4-4b52-8fe1-72410d2e1dbc)

In out WebPack config we have:
```
  devtool: 'source-map' ,
  output: {
    path: config.build.assetsRoot,
    filename: utils.assetsPath('js/[name].[chunkhash].js'),
    chunkFilename: utils.assetsPath('js/[id].[chunkhash].js'),
    sourceMapFilename: '[file].map',
  },
```

The debug ID of 1b48b47e... seems to match up to the source/maps being uploaded.

### Where in the product are you?

Issues - Source Maps

### Version

24.6.0

**Comment by baubie** [comment]
Thanks @lforst - that button appears on every error after the source is uploaded via the webpack plugin.  It looks like the `symbolicator` service is just full of:

`symbolicator_service::download::sentry: Sentry API returned status code 401 Unauthorized`

This is on a brand new fresh install of 24.6.0 using docker compose.  Possibly similar to this bug? https://github.com/getsentry/sentry/issues/73135

**Comment by lforst** [comment]
@loewenheim what was the issue in #73135?

**Comment by baubie** [comment]
Found the issue!  With the 401 errors I took a look at my config and saw that the internal-url-prefix in sentry/config.yml was commented out - I believe was during debugging getting the external URL working behind a load balancer.  Uncommenting that back to the default web:9000 and source maps are working!
