### ISSUE TITLE
Trying to accept project transfer

### ISSUE THREAD

**Issue by chanko** [getsentry/sentry#73538]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I want to transfer a project from one org to another. I had the owner of the original project initiate the transfer, but when I click accept I hit an error page saying to wait and reload after a bit, but still nothing.

Additional details are that my email is tied to both the original org and the new org I'm trying to transfer the project to.

And the original org and project were created via Heroku.

We're getting off Heroku, so I want to have the project live in an org that isn't tied to it.

### How are you getting stuck?

I can't accept the project transfer for an unknown reason

### Where in the product are you?

Projects - Project Details

### Link

https://mosaicvoice.sentry.io/accept-transfer/?data=eyJhY3Rvcl9pZCI6Mjk2NTMxNiwiZnJvbV9vcmdhbml6YXRpb25faWQiOjQ1MDYyMzIwODc3MDc2NDgsInByb2plY3RfaWQiOjQ1MDY5ODQ4NTUzNzE3NzYsInVzZXJfaWQiOjMwMjEwOTcsInRyYW5zYWN0aW9uX2lkIjoiZmExZTZmOWIzNmM4NGJiZmJkM2ZjY2RjYzA0NmZlZTUifToxc0x0YXY6Y1dfNzdkWWwtM1RRWVNCV0ExT3pXV1F0NVRsYWdONHEzVlVVY2gxNnhZVQ

### DSN

https://4741983ab977b2170e310b992b2ffe4a@o4506232087707648.ingest.us.sentry.io/4506984855371776

**Comment by nhsiehgit** [comment]
Hi @chanko 

Can you see if these docs help your situation at all?
https://sentry.zendesk.com/hc/en-us/articles/23572020203419-How-can-I-migrate-projects-between-Sentry-organizations

If not, you can open a ticket with our support team and they'll be able to better support you
