### ISSUE TITLE
Support Internal/Public integrations with OAuth authentication for security purpose.

### ISSUE THREAD

**Issue by palemmahesh** [getsentry/sentry#73621]
### Problem Statement

Internal Integrations we can give url with username and password to send events to another url. But it will be good to provide oAuth 2.0 setup for external/internal integrations for security purpose not to give clear text password in the url.

### Solution Brainstorm

OAuth 2.0 support for internal integrations

### Product Area

Settings - Auth

**Comment by Christinarlong** [comment]
Closing as we have this, please make a follow up if this isn't the case.
