### ISSUE TITLE
Sentry does not show the request body was truncated

### ISSUE THREAD

**Issue by cedric-spinergie** [getsentry/sentry#73629]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

See [this issue](https://github.com/getsentry/sentry-python/issues/3209) for my initial report.

When using a SDK related to an API, send a POST request with a big request body and make it so the endpoint throws an exception. (Mine was 40kB when testing)  
Configure the SDK so it automatically picks up the exception and its context (including the request body) and sends the data to Sentry.

### Expected Result

I expected the body to be available on Sentry without truncation **OR** with clearly stated truncation.

### Actual Result

Sentry has truncated the test JSON in such a way that the body field is perfectly valid and correct JSON. This is a problem because users don't know whether the data is right or wrong and they might end up debugging a non-existent problem.

In my specific tests, Sentry truncated a json array from 5XXX elements to 13XX elements. This was done silently and the resulting body field looks like perfectly valid json which is very confusing for users.

### Product Area

Issues

**Comment by roggenkemper** [comment]
Thanks for the feedback! We have similar feedback that is already on our backlog (https://github.com/getsentry/sentry/issues/68426) about being showing an indicator when the data is truncated, but having more info about people encountering this is useful. not sure when the team will work on this, but ill add this to our backlog as well

**Comment by scttcper** [comment]
closing in favor of https://github.com/getsentry/sentry/issues/68426
