### ISSUE TITLE
Stride (HipChat replacement) intergration

### ISSUE THREAD

**Issue by violuke** [getsentry/sentry#7365]
We were forcibly upgraded from HipChat to Stride over the weekend and this has unfortunately broken all our integrations, the most important of which is Sentry.

Please can a native Stride integration be developed ASAP?

This might be of help https://developer.atlassian.com/cloud/stride/learning/hipchat-to-stride/

Thank you

**Comment by dcramer** [comment]
Just so everyone who might be watching is aware, we're going to look into Stride, but to be perfectly honest its (right now) at the bottom of some of our other concerns. We're intending to launch many overhauled integrations on top of our new platform in the next few months, but Jira, GitHub, and Slack (to name a few) are the priorities right now. Hopefully with the new scaffolding the time needed to build (and maintain) these will be drastically reduced, as historically it's been quite complex for things like HipChat.

**Comment by azhard4int** [comment]
Any update on Stride?

**Comment by oriolarcas** [comment]
Our company migrated from Slack to Stride, but the lack of integration with Sentry is really annoying. It would be nice if there was some update on this, even if it was a minimal integration.

**Comment by dcramer** [comment]
Everyone needs to realize that Sentry has a lot of important things to build, and integrations with every new product aren’t high on that list. We’re in the middle of overhauling the rest of the ecosystem and will be evaluating Stride when that is done. Bumping a GitHub thread isn’t going to make that happen any faster.

**Comment by violuke** [comment]
Thanks @dcramer we understand that, the only thing is that Stride is not really just a part of "every new product". Everyone using HipChat is being migrated from HipChat to Stride against their will by Atlassian. This means that it's not just some new product that may or may not become popular, but will gradually become approximately as popular as HipChat is (but probably more as frankly it's better)... and your current HipChat integration will become defunct.

I totally get that we don't get to dictate the roadmap for Stride and that the work your doing overhauling the ecosystem makes sense to come first, but I'd hope that once that framework is in place you give this some level of priority as at the moment you're making all your happily HipChat-integrated customers unhappy (although we get that it's more Atlassian's fault than Stride's).

I hope that the above makes sense and that Sentry realise that Stride is not just some random new team chat product, but what all HipChat users will be using soon. And 👎 to Atlassian for not making it backwards compatible with HipChat notifications, yet still forcing us to migrate - that was really irritating.

**Comment by dcramer** [comment]
@violuke yeah we realize that its not really a choice for some people, and it is something we want to solve soon. It's just lower on our list of priorities purely on the customer demand side. I'm hoping we'll be able to resolve it in 60-90 days, but thats assuming timelines work out on other projects which often slip in engineering 🤦‍♂️

**Comment by sandys** [comment]
+1 - we are in the same boat. We are being force-migrated from Hipchat and we will lose notifications for sentry. is there a way we can wire up using something else ?

**Comment by mkdeddens** [comment]
I look forward to native integration. In the meantime I feel this helps:

- Create an incoming webhook with [Unified Webhooks](https://marketplace.atlassian.com/apps/1218774/unified-webhooks-for-stride?hosting=cloud&tab=overview) Stride app

- Configure that webhook on Sentry > Project > Settings > Integrations > Slack > Webhook URL

**Comment by robertobarreda** [comment]
Never mind :( https://www.atlassian.com/partnerships/slack
