### ISSUE TITLE
Cannot create a JIRA issue when there is a "team" field that is required

### ISSUE THREAD

**Issue by mjburghoffer** [getsentry/sentry#73671]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I want to use the JIRA integration to create and link a ticket based off of a Sentry issue.  I fill in the form and hit submit, but there is no valid value I can put in the "Team" field.

- Blank - rejected by the API because it is required.
- Display Name - rejected with error message `Team Id 'JsonData{data={id=My Team Name}}' is not valid`
- UUID - rejected with the error message `Team Id 'JsonData{data={id=c219d0ca-6bdd-42af-94b6-bbe748ddb9a4}}' is not valid`

It doesn't present the team as a dropdown either, so I needed to manually enter the exact name/id (though neither worked anyway).

### Expected Result

I would expect the name or id to work, or for there to be a search/dropdown list of teams.

### Actual Result

<img width="669" alt="Screenshot 2024-07-02 at 11 16 10 AM" src="https://github.com/getsentry/sentry/assets/2665798/1ed51bed-1f1a-4641-969a-e122e19138ac">

### Product Area

Unknown

**Comment by mattste** [comment]
Ran into this issue today.

**Comment by GabeVillalobos** [comment]
@mjburghoffer @mattste This has been addressed via #76091, which fixes the format of the Team field we pass to Jira.

You should now be able to specify a Team UUID when creating a new Jira issue from an existing Sentry issue. I've also validated that this fixes a related issue with automatic issue creation via alert rules.

If you encounter any other problems surrounding team linking, please let me know and I can reopen this issue.
