### ISSUE TITLE
Actual usage is ~10x less than estimated in Usage & Billing

### ISSUE THREAD

**Issue by yinghaochan** [getsentry/sentry#7370]
We have a large plan which allows dropping events through filtering. 

![image](https://user-images.githubusercontent.com/7133601/36702871-ce6bce80-1b0d-11e8-9ae7-977e32c0ffb2.png)

We filter >95% of events, since most of them are `[object Object]` https://github.com/getsentry/raven-js/issues/1176#issuecomment-353032034

Here's the Usage & Billing page:
![image](https://user-images.githubusercontent.com/7133601/36702860-c08ffcf0-1b0d-11e8-94c6-7f006f7baddd.png)

projected events show ~700k estimated events per day, which adds up to ~20mil for the month...
while history shows only ~10k events per day, or ~300k per month.

![feb-26-2018 16-12-34](https://user-images.githubusercontent.com/7133601/36703299-e58bb592-1b0f-11e8-9c4c-4de73f584662.gif)

**Comment by benvinegar** [comment]
Hey @yinghaochan – issues here are reserved strictly for issues/bugs with the getsentry/sentry codebase. Issues with [sentry.io](https://sentry.io) (the hosted service), should be raised to our [support team](https://sentry.io/support) or on our [forums](https://forum.sentry.io).

---

But, to quickly help you with your question: you can configure Raven.js to filter client-side (see: `shouldSendCallback`) which does not affect your account quota.

@kamilogorek – we should talk about introducing getsentry/raven-node#416 to raven-js.

**Comment by yinghaochan** [comment]
@benvinegar  thanks-- will open support ticket.

**Comment by kamilogorek** [comment]
@benvinegar we will definitely port this to v4. We'll try to estimate whether it's worth it to do ASAP or wait for the new release.
