### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by KrawczowaKris** [getsentry/sentry#73809]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### What are you trying to accomplish?

Hi everyone,

The [documentation](https://docs.sentry.io/product/issues/) shows that performance issues are listed in the general list on the "Unresolved" tab. Also we can find performance issues by searching `issue.category:performance`.

### How are you getting stuck?

Performance issues are only displayed in the "For review" tab.

![image](https://github.com/getsentry/sentry/assets/72573143/934c37a9-a6c5-4002-bf1f-6e8ed5239fda)

Also the filter `issue.category:performance` doesn't output anything:

![image](https://github.com/getsentry/sentry/assets/72573143/03c53ae7-0c3b-48ff-af1f-594cf9f7e6fc)

Is it possible to change this somehow?

### Where in the product are you?

Issues

### Version

24.5.1

**Comment by vartec** [comment]
Hi @KrawczowaKris, 

I have hard time reproducing this. 
Could you add more detailed steps to reproduce?
Thank you!
