### ISSUE TITLE
SPIKE Figure out how to connect rules to dashboards and alerts so that we can warn users on edit/delete

### ISSUE THREAD

**Issue by ArthurKnaus** [getsentry/sentry#73875]
When a user removes an existing metrics extraction query, they loose the data that was generated by it.
We should warn them of doing so.

**Comment by obostjancic** [comment]
Proposals outlined in https://www.notion.so/sentry/Rule-extraction-delete-update-4e29d2817f9446f1a2c9706cf7663bcf?pvs=4
