### ISSUE TITLE
Unable to transfer ownership of a project to another organisation I own

### ISSUE THREAD

**Issue by njbmartin** [getsentry/sentry#73899]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create two or more organisations
2. Create a new project
3. Go to project settings
4. Transfer project, using the same owner email
5. Click on approve transfer in the email

### Expected Result

I should be able to transfer a project to another organisation owned by myself.

### Actual Result

After clicking approve transfer, the only organisation I can transfer the project to is the _current_ organisation it already belongs to.

### Product Area

Settings - Projects

**Comment by njbmartin** [comment]
I had a response from Support on this:

> Transferring projects between organizations in different data storage locations is not supported.

It seems I may have missed this line when trying to transfer, and didn't realise my other organisations were in the US (legacy):
![image](https://github.com/getsentry/sentry/assets/5699471/c597f350-0bb6-4a70-bd25-644745d5736c)

**Comment by leedongwei** [comment]
Gotcha, thanks for the update. 

Unfortunately, we cannot move data between regions and hence, project transfer across regions is not allowed.
