### ISSUE TITLE
ReacnTive-mx

### ISSUE THREAD

**Issue by MarcoAntoniodesp** [getsentry/sentry#73900]
### Problem Statement

Reac para los mexicanos 

### Product Area

Projects - Project Creation

**Comment by matejminar** [comment]
Hi, can you please specify what this issue is about?

**Comment by MarcoAntoniodesp** [comment]
Disculpe soy nuevo aquí aún no entiendo la plataforma

**Comment by MichaelSun48** [comment]
Closing since there is no issue being described in this ticket. If you have an issue, feel free to open a new one and we'll respond accordingly.
