### ISSUE TITLE
[Replay] Replace references to ContextIcon imports with equivalent PlatformIcon

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#73945]
Check the replay list page, as well as replay details page.

Specific files to look at:
https://github.com/getsentry/sentry/blob/master/static/app/components/replays/contextIcon.tsx#L20
https://github.com/getsentry/sentry/blob/master/static/app/views/replays/replayTable/tableCell.tsx#L10
https://github.com/getsentry/sentry/blob/master/static/app/views/replays/detail/browserOSIcons.tsx#L4

**Comment by michellewzhang** [comment]
the code blobs give me 404 btw @ryan953

**Comment by ryan953** [comment]
> the code blobs give me 404 btw @ryan953

fixed! i pointed them them to the master branch instead of whatever commit that was.

**Comment by aliu39** [comment]
@ryan953 Is the idea to get rid of the `replays/contextIcon` component, or swap out the import for `LazyContextIcon`? Is `events/interfaces/crashContent/stackTrace/platformIcon` the right file for this?

Asking cause it seems like the replay component has an extra dropdown feature Michelle added in https://github.com/getsentry/sentry/pull/54897

**Comment by ryan953** [comment]
@aliu39 the end-goal is to get rid of the `sentry/components/events/contexts/contextIcon` component, which https://github.com/getsentry/sentry/blob/master/static/app/components/replays/contextIcon.tsx#L20 brings into replay land. 

Normally for icons we just import them, but i guess that `LazyContextIcon` is there because these logo icons can be larger (multiple colors, intricate logo shapes, etc) than regular icons. So we could change `replays/contextIcon.tsx` itself, which the other two files depend on, or if we don't need the lazy loading quick updates to all three files should be good. I'm not sure!

**Comment by aliu39** [comment]
Right now we're importing https://sentry.sentry.io/stories/?name=app/components/events/contexts/contextIcon.stories.tsx

We want to move to the more up-to-date PlatformIcons from https://sentry.sentry.io/stories/?name=app/icons/icons.stories.tsx
