### ISSUE TITLE
Upload libc.so.6 and ld-linux-x86-64.so.2 in PostBuild symbol uploads when cross compiling

### ISSUE THREAD

**Issue by narthur157** [getsentry/sentry#73950]
### Problem Statement

![image](https://github.com/getsentry/sentry/assets/2042752/e7a54499-914f-4de0-a2fd-55c7980aaca0)
You get this error when emitting events from a linux server
It's a bit unclear how best to go about uploading these debug files, particularly when cross compiling

### Solution Brainstorm

I tried uploading all the debug symbols available from the linux toolchain, however this didn't solve my issue as neither of the libc.so.6 files uploaded matched the debug id

### Product Area

Unknown

**Comment by lforst** [comment]
@Swatinem @loewenheim mind taking a look at this?

**Comment by loewenheim** [comment]
Hm, are those files we would expect the user to upload? Or should they be on a public symbol server @Swatinem ?

**Comment by Swatinem** [comment]
The only Linux distribution which we have a builtin symbol server for is Ubuntu at the moment. And we have already seen that Ubuntu happily removes outdated debug files from their server.

So even in that case, its quite possible that no debug symbols can be found.

I would recommend to either figure out if the distribution offers a *stable* symbol server and configure that, or to just upload those debug files manually.
As more and more distributions have decided to move towards enabling frame pointers by default by now, it might not even be necessary to have unwind info in those cases, and the stack trace is "correct" even though it might not be particularly readable.

See https://github.com/getsentry/sentry/blob/56f790693e03db86c1074c419e48bd50470c6f3f/src/sentry/conf/server.py#L2763-L2786 for some other example symbol servers.
