### ISSUE TITLE
sentry.celery in apply_async

### ISSUE THREAD

**Issue by dingshiwei** [getsentry/sentry#7399]
details: Couldn't apply scheduled task flush-buffers: Cannot route message for exchange 'counters': Table empty or key no longer exists. Probably the key ('_kombu.binding.counters') has been removed from the Redis database

when I use celery 3.1 to sending a task with a queue, the error occurred. On celery Issue ,it is be repair  in 4.0, but sentry still use 3.1 by default package

**Comment by mattrobenolt** [comment]
This sounds like your Redis ran out of memory and started evicting keys. I would recommend preventing this from happening, using RabbitMQ, or configure redis in a way that doesn’t evict keys forcefully.

**Comment by dingshiwei** [comment]
I'm confirmed that my redis is not out of memory , only celery 3.1 version have this problem, look at this https://github.com/celery/kombu/issues/236, hope you can upgrade install package!

**Comment by fabb** [comment]
We experience the same issue. After a few weeks, parts of Sentry stop working because of this (e.g. the Issue Tags do not update anymore, which breaks Filtering). Seems like celery is still on 3.1: https://github.com/getsentry/sentry/blob/master/requirements-base.txt#L4
