### ISSUE TITLE
IE Mobile 10 is not filtering with enabled IE 10 filter

### ISSUE THREAD

**Issue by AlexWayfer** [getsentry/sentry#7400]
- The version of Sentry you're using

`8.15.0`

- Whether you're using Docker or another installation method

Docker.

- Include a stacktrace or other logs when relevant

![image](https://user-images.githubusercontent.com/6510020/36780306-aa0616a0-1c83-11e8-8ddc-0672f0ef7d03.png)
![image](https://user-images.githubusercontent.com/6510020/36780326-b2e58ac6-1c83-11e8-8f7b-aa83399d9b5b.png)

**Comment by kamilogorek** [comment]
@AlexWayfer can you provide event's JSON data from your Sentry instance?

It should be available in the header of event's page.

<img width="565" alt="screen shot 2018-03-02 at 13 25 14" src="https://user-images.githubusercontent.com/1523305/36898925-301f9032-1e1d-11e8-8651-7964fdde92b3.png">

I want to see how IE Mobile is stored there.
Thanks!

**Comment by AlexWayfer** [comment]
@kamilogorek I don't want to publish the whole file, so there are parts about device:

```json
"tags": [
    ["device", "Lumia 520"],
    ["device.family", "Lumia 520"],
    ["os", "Windows Phone 8.0"],
    ["os.name", "Windows Phone"],
    ["browser", "IE Mobile 10.0"],
    ["browser.name", "IE Mobile"]
  ],
  "contexts": {
    "device": {
      "model": "Lumia 520",
      "brand": "Nokia",
      "family": "Lumia 520"
    },
    "os": {
      "version": "8.0",
      "name": "Windows Phone"
    },
    "browser": {
      "version": "10.0",
      "name": "IE Mobile"
    }
  },
  "sentry.interfaces.Http": {
    "headers": [
      ["User-Agent", "Mozilla/5.0 (compatible; MSIE 10.0; Windows Phone 8.0; Trident/6.0; IEMobile/10.0; ARM; Touch; NOKIA; Lumia 520)"]
    ],
  },
```

**Comment by kamilogorek** [comment]
Fixed in https://github.com/getsentry/sentry/pull/7521

**Comment by AlexWayfer** [comment]
Thank you!
