### ISSUE TITLE
remove sourcemap doesn't work

### ISSUE THREAD

**Issue by DophinL** [getsentry/sentry#7401]
sentry version:1.30.1

I uploaded a sourcemap for a js file.
It works.
Then I delete the sourcemap with`sentry-cli releases files version delete --all`,but it still show sourcemap:
![image](https://user-images.githubusercontent.com/8707316/36787850-8da3c0a0-1cc6-11e8-9564-bf4433b99a1b.png)

So how to really remove sourcemap?

**Comment by benvinegar** [comment]
Was this event generated _before_ or _after_ the source map was removed?

Event data is immutable once its been processed. So if a source map was applied, deleting that source map won't impact any events that have already been processed.

**Comment by DophinL** [comment]
Thanks for reply!

My actual demand is upload new source map to override previous source map, but it seems doesn't work unless I change the release.

my step is:
1. write a file named a.ts which has a exception on it
2. generate source map and upload to sentry
3. trigger the exception
4. change a.ts and repeat step 2 & 3 again
5. watch issue on sentry but seems source map isn't the newest one.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
