### ISSUE TITLE
Allow 3rd party apps to subscribe to webhooks that they already have permission scopes for

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#74029]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Linear wants to subscribe to the Issue webhooks - They already have Read and Write access to the Issues and Events resource and are allowed to subscribe the Issue webhooks but the UX is not letting them do that

![image](https://github.com/getsentry/sentry/assets/109983869/ad349dad-4f42-455a-8865-713228b8f63b)

![image](https://github.com/getsentry/sentry/assets/109983869/843d32b6-33b9-468f-b9c4-26f6f8150193)

### Expected Result

3rd party apps should be able to subscribe to webhooks they already have permission for

### Actual Result

.

### Product Area

Settings - Integrations

**Comment by iamrajjoshi** [comment]
@skbogner, thank you for your patience as we investigated the issue. We believe we have a fix in which should allow you to now subscribe to the webhook. Could you please try again?

**Comment by skbogner** [comment]
Thanks! It worked :)

**Comment by iamrajjoshi** [comment]
Thank you for confirming.
