### ISSUE TITLE
can't finish re-authenticate for superuser.

### ISSUE THREAD

**Issue by xuweixi10** [getsentry/sentry#74046]
### Self-Hosted Version

24.6.0

### CPU Architecture

x86_64

### Docker Version

24.0.7

### Docker Compose Version

2.23.3

### Steps to Reproduce

1. first use sentry as superuser
2. select options
3. enter password
<img width="714" alt="截屏2024-06-27 16 51 29" src="https://github.com/getsentry/self-hosted/assets/40662756/6e85f149-a05c-4532-ad17-16b0563b9e81">

### Expected Result

enter sentry home page

### Actual Result

nothing happed, and the button is disabled
<img width="640" alt="截屏2024-06-27 16 50 52" src="https://github.com/getsentry/self-hosted/assets/40662756/43b8886f-8dc2-44dc-943d-3847ce1e5ea9">

**Comment by schew2381** [comment]
Those lines for setting the expiration and idle time have not changed at all. My best guess is the problem is somehow related to how we're verifying the superuser session.

@xuweixi10 could you possibly take a look at where we're validating the session expiration time below, and check what the value is when using the existing code vs your fix?
https://github.com/getsentry/sentry/blob/ba3a4de019399cfaf1707bb2ea73bec690d56bf2/src/sentry/auth/superuser.py#L310-L325

**Comment by xuweixi10** [comment]
after i add log blow, 
```
        logger.info(
            "superuser.logged-in",
            extra={
                "exp": self.expires.strftime("%s"),
                "idl": (current_datetime + IDLE_MAX_AGE).strftime("%s"),
            },
        )
        self.request.session[SESSION_KEY] = {
            "exp": self.expires.strftime("%s"),
            "idl": (current_datetime + IDLE_MAX_AGE).strftime("%s"),
            "tok": self.token,
            # XXX(dcramer): do we really need the uid safety mechanism
            "uid": self.uid,
        }
```
when i login as superuser
```
09:57:51 [INFO] sentry.superuser: superuser.needs-validation (DISABLE_SU_FORM_U2F_CHECK_FOR_LOCAL=False self_hosted=True)
09:57:51 [INFO] sentry.superuser: superuser.logged-in (exp='1722059871' idl='1722046371')
09:57:51 [INFO] sentry.superuser: superuser.logged-in (ip_address='157.10.105.33' user_id=1)
09:57:51 [INFO] sentry.access.api: api.access (method='PUT' view='sentry.api.endpoints.auth_index.AuthIndexEndpoint' response=200 user_id='1' is_app='None' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/api/0/auth/' caller_ip='157.10.105.33' user_agent='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.2741873264312744 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
09:57:51 [INFO] sentry.superuser: superuser.session-expired (ip_address='157.10.105.33' user_id=1)
09:57:51 [INFO] sentry.superuser: superuser.session-expired (ip_address='157.10.105.33' user_id=1)
09:57:51 [INFO] sentry.superuser: superuser.session-expired (ip_address='157.10.105.33' user_id=1)
09:57:51 [WARNING] django.request: Forbidden: /api/0/internal/stats/ (status_code=403 request=<WSGIRequest: GET '/api/0/internal/stats/?key=events.total&resolution=1h&since=1721469471.309'>)
09:57:51 [INFO] sentry.superuser: superuser.session-expired (ip_address='157.10.105.33' user_id=1)
09:57:51 [INFO] sentry.superuser: superuser.session-expired (ip_address='157.10.105.33' user_id=1)
```
I login as super user then immediately expired i think maybe the timezone problem, i can see some places still use non-UTC time

**Comment by xuweixi10** [comment]
Fine, the reason is my docker timezone is not UTC.after i change to UTC everything is ok
