### ISSUE TITLE
Tags are not showing in "All Events" view of an issue

### ISSUE THREAD

**Issue by maxp1256** [getsentry/sentry#74045]
### Self-Hosted Version

24.2.0

### CPU Architecture

x86_64

### Docker Version

24.0.7-0ubuntu2~22.04.1

### Docker Compose Version

2.28.1

### Steps to Reproduce

Open an Issue
Open "All Events" tab
reading the listview

### Expected Result

Before the recent upgrades (from 22.x / 23.x) to 24.2 it was possible to show all our custom tags in the "All Events" view of an issue. After upgrading we're missing all of our custom tags in this listview. Previously it was not the best solution because the list was very  wide but we had all the needed information there.
There were some use-cases (e.g. to find similarities) where it was fine to can sort and filter all our tags for an event. Now we're still able to filter our tags, but we need to do it blindly because we cannot see the tag values.

### Actual Result

Only system defined tags are showing up

**Comment by vartec** [comment]
I've added this to our board.

**Comment by jangjodi** [comment]
I'm closing this as we now have an "Event Tags" dropdown in the "All Events" tab that shows all event tags, including custom ones. Please re-open this ticket if this does not fix your use case.
