### ISSUE TITLE
Custom sampling frequency for profiling

### ISSUE THREAD

**Issue by aleksanb** [getsentry/sentry#74069]
### Problem Statement

Today, the sampling frequency for performance tracing is capped at 100hz.
We'd like to set this to something custom, perhaps 200hz to get more accurate flamegraphs.

### Product Area

Performance

**Comment by Dhrumil-Sentry** [comment]
Thank you for this feedback. The sampling frequency for profiles is fixed at 101hz and is not user configurable. One of the main reasons being higher frequencies will cause additional load.

We will keep this in our backlog but we don't anticipate working on this in the near-mid term

**Comment by aleksanb** [comment]
I'm aware of the increased performance impact, and willing to take the hit for more fine grained profiling on our app servers. Being able to self configure this would only make things slower for my own organization.

Is it a data cost question on sentry's side? 200hz would shovel twice the data amount through your servers. If so i see why making the flag user configurable could takr more time, if it had to increase the profile cost to 1.4 or more for instance.

**Comment by DaveRosenthalSentry** [comment]
I'm closing this and marking it as won't-do for now. We appreciate the feedback but this configurability is not planned at this point (and brings up lots of work in terms of setting reasonable limits for different platforms, increased server costs, etc.) 100hz we feel is a good tradeoff for capturing fine-grained profiling data with limited overhead. There is also the simple workaround of looking at multiple samples of a process to get more samples.

Thanks, Dave
