### ISSUE TITLE
Android Replays have platform=javascript 

### ISSUE THREAD

**Issue by romtsn** [getsentry/sentry#74074]
This seems to be overwritten by backend, because the SDK always sends `java`. here's an example video which shows that the tag changes from `java` to `javascript` after refreshing the page:

https://github.com/getsentry/sentry/assets/4999776/e2642c15-d547-4432-bdd3-9fbc1874833f

**Comment by romtsn** [comment]
i think this is fixed now @cmanallen ?

**Comment by bruno-garcia** [comment]
Resolved through: https://github.com/getsentry/snuba/pull/6098
