### ISSUE TITLE
Custom tag value is shown as (empty string) in Discover overview

### ISSUE THREAD

**Issue by shafy** [getsentry/sentry#74122]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I want to display the values for a custom tag in Discover in one of the columns.

### How are you getting stuck?

I can display a list of my events and add a new column for my custom tag. However, the value in the overview table always shows as (empty string). If I go into the event detail view, I can see that the value for the custom tag is correcly set.

Discover overview: No value for my custom tag `store_id`
![CleanShot 2024-07-11 at 10 17 21@2x](https://github.com/getsentry/sentry/assets/1881676/d96818c6-5415-4f54-9afe-7497f0038fd4)

Clicking on the event ID, I see see correct value for my custom tag `store_id` in the event detail view.
![CleanShot 2024-07-11 at 10 17 52@2x](https://github.com/getsentry/sentry/assets/1881676/c5030552-cb0f-4539-a218-3f35a08999c9)

### Where in the product are you?

Discover

**Comment by gggritso** [comment]
@shafy thanks for raising this! Did you reach out to [Sentry Support](https://sentry.zendesk.com/hc/en-us/requests/new)? That might be a better approach since they'll be able to help you directly. It's hard to triage this without more information

**Comment by shafy** [comment]
Hi @gggritso not yet, but I will do now!

**Comment by gggritso** [comment]
@shafy were you able to resolve this?

**Comment by gggritso** [comment]
Closing as stale! @shafy let us know if you're still having trouble

**Comment by shafy** [comment]
Hey @gggritso sorry missed your initial message. Yes, this was resolved. The issue was that I was not passing the `store_id` as a tag but as "additional data". So it was still visible in the event details, but not possible to use as a filter in Discover. Maybe helpful if anybody else his this issue in the future.
