### ISSUE TITLE
Export data of a tag of a metric

### ISSUE THREAD

**Issue by GiannisGl** [getsentry/sentry#74121]
### Problem Statement

We want to use a metric to collect some data and we would like to export the data related to a tag, e.g. to csv, for further processing if needed. There is such a way for a tag of an issue (the "export all to csv" button) but there is not one for metrics.

### Solution Brainstorm

Add functionality to export data of a tag of a metric similar to that of a tag of an issue.
Either in UI or with an API to be able to export the data programmatically
Thank you for your consideration

### Product Area

Other

**Comment by Dhrumil-Sentry** [comment]
Thanks for this feedback. We will add this to our backlog but we don't anticipate supporting this in the near to mid term
