### ISSUE TITLE
[Design] Unclear when setup is complete

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#74128]
**Problem**: Early testers keep getting stuck on "my metrics are not appearing". The sequence of tasks to complete isn't clear and an easy way to verify. The "mistakes" people make are:
- they first implement the custom attribute and then go to the metrics page expecting it to appear - it won't until they also complete the configuration
- after they complete the configuration they expect the metric to appear - it doesn't because it won't apply to historical data, so they need to send more spans to start seeing it; typically they manually generate some spans to test this

**Solution:** Offer in-product guidance that helps the user complete the tasks and verify the metric is appearing.

There are 2 scenarios:
(1) defining a span metric from a new custom attribute
(2) defining a span metric from an existing span attribute (e.g. span.duration, browser.name, etc)

For a new custom attribute (1), the sequence should be:
1. create the custom attribute you want to measure in code and send some test spans
2. go into the UI and "add new metric"
   - when span indexing is done and the autocomplete works, they will be able to see their new attribute
   - until we have span indexing, the user just has to type in the name (and make sure not to have typos)
3. fill in the form and save the metric
4. send more spans from their application and start seeing metrics appear

For scenario (2), the sequence is the same, but without the first step. Their application might also be steadily sending spans with those attributes already, so no need to send them manually.

**Comment by ale-cota** [comment]
- the "add metric" button needs to be more visible/contextual, because any old user is used to that just opening up setup instructions
- "forgot your password?" type of interaction for "not seeing your attribute?"/"forgot how to add a custom metric?"
- maybe the subtext goes into a tooltip instead 
- "add metric" and "add new metric" are very similar CTAs which is confusing
- after you save the new metric on the chart we need to tell you that now you either have to wait for metrics to come in or send more spans manually to start seeing metrics
- "Metric extraction rule created" - needs rewording, doesn't mean anything

**Comment by ale-cota** [comment]
- https://www.figma.com/design/ezIcRHotnCVWTdYh60uRtp/Specs%3A-Create%2FEdit-Metric-Modal?node-id=2-349&t=ZU4iwIVnRn0pJMpl-0
- maybe add an alert on the page as v0
- maybe add the CTA to create new metric in the metric selection dropdown

**Comment by Jesse-Box** [comment]
Marking this as done

Figma designs below
1. [Create/Edit Modal](https://www.figma.com/design/ezIcRHotnCVWTdYh60uRtp/Specs%3A-Create%2FEdit-Metric-Modal?node-id=30-104&t=OpbjyJUd1gRj7wsq-1)
2. [Metric Combo Box](https://www.figma.com/design/gTSzrls85h2wW0Gfct9gM3/Specs%3A-Search-Experience-v3?node-id=2001-570&t=XemN2eF15akdYXFy-1)
