### ISSUE TITLE
Cache insights failing to load events

### ISSUE THREAD

**Issue by stayallive** [getsentry/sentry#74130]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Access cache insights with data from the Laravel SDK.

### Expected Result

Cache Insights loads correctly.

### Actual Result

![afbeelding](https://github.com/getsentry/sentry/assets/1090754/0de65fac-68d5-4cbe-9e28-f8803f54f8eb)

Request is made to:

> https://us.sentry.io/api/0/organizations/devalex/events/?dataset=spansMetrics&field=project&field=project.id&field=transaction&field=spm()&field=cache_miss_rate()&field=sum(span.self_time)&field=time_spent_percentage()&field=avg(cache.item_size)&per_page=20&query=span.op:[cache.get_item,cache.get]&referrer=api.performance.cache.landing-cache-transaction-list&sort=-time_spent_percentage()&statsPeriod=1h

400 response is thrown with:

> Metric: cache.item_size could not be resolved

### Product Area

Insights

### Link

https://devalex.sentry.io/insights/caches/?statsPeriod=1h

**Comment by DominikB2014** [comment]
hey @stayallive! Thanks for pointing this issue out.
I put up a [PR](https://github.com/getsentry/sentry/pull/74275) to solve this failing query, I will also need to double check that the UI handles this well (which i believe it should), will keep you posted when everything is deployed and resolved.

**Comment by stayallive** [comment]
Seems to be working! Thanks 👍
