### ISSUE TITLE
Your Web browser doesn't appear to have cookies enabled. Cookies are required for logging in.

### ISSUE THREAD

**Issue by kjxbyz** [getsentry/sentry#74189]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

https://sentry.io/auth/login/

### Expected Result

Log in to sentry.io normally

### Actual Result

Your Web browser doesn't appear to have cookies enabled. Cookies are required for logging in.

### Product Area

Sign In

**Comment by kjxbyz** [comment]
I can log in normally after reopening the browser. I don't know why!

**Comment by dalnoki** [comment]
Hi @kjxbyz I'm glad to hear you were able to log in. If you experience anything out of ordinary with logging in in the future, please drop us a line [here](https://sentry.zendesk.com/hc/en-us/requests/new).
