### ISSUE TITLE
More details on the issues on django

### ISSUE THREAD

**Issue by ashwanthbalakrishnan5** [getsentry/sentry#74188]
### Problem Statement

When a new issues is create I like the see the request and response which cause the issues. Something the data in the request we will helpful in debugging. 
Request - uri, headers, data
Response -status code, headers, data

### Product Area

Issues

**Comment by mrduncan** [comment]
Hi @ashwanthbalakrishnan5 sending this information is covered in our docs: https://docs.sentry.io/platforms/python/data-management/data-collected/. You can also manually enrich events with other information: https://docs.sentry.io/platforms/python/enriching-events/
