### ISSUE TITLE
Jira Integration Problem in Jira

### ISSUE THREAD

**Issue by rafau71** [getsentry/sentry#74249]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Install sentry app in Jira
2. Open Get started page

### Expected Result

Get started page shows to configure

### Actual Result

Nothing shows, cannot configure Jira integration with Sentry

Error returned:

_Something's gone wrong
Our team has been notified. If the problem persists, please contact Atlassian Support._

### Product Area

Settings - Integrations

**Comment by leedongwei** [comment]
Can you share a project DSN from your Sentry org?

**Comment by rafau71** [comment]
@leedongwei I found the root cause now. You may want to close this ticket or use it to solve the issue. 

The sentry settings didn't load up due to the [Ghostery](https://www.ghostery.com/) extension in my web browser
