### ISSUE TITLE
"Cold start" issue with span metrics

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#74253]
**Problem:** When customers first configure a new metric and send spans with the new attribute, they are likely to just do a manual test and send a few spans. It seems like in some cases ([example project](https://team-se.sentry.io/metrics/?interval=5m&project=4506079262212096&statsPeriod=3d&widgets=%5B%7B%22type%22%3A1%2C%22id%22%3A0%2C%22mri%22%3A%22v%3Acustom%2Fuser_view%7C4506079262212096%40none%22%2C%22aggregation%22%3A%22count%22%2C%22condition%22%3A16%2C%22query%22%3A%22%22%2C%22sort%22%3A%7B%22order%22%3A%22asc%22%7D%2C%22displayType%22%3A%22line%22%2C%22isHidden%22%3Afalse%2C%22overlays%22%3A%5B%22samples%22%5D%7D%5D)) metrics don't appear on the chart even after 24h, despite the spans with the attributes being correctly received.  This makes the setup process feel "broken" and leaves the user confused.

When sending a batch or a constant "stream" of spans it starts to work, but it's unclear what the conditions are. This is a big hurdle for onboarding, many users are likely to drop off.

**Comment by olksdr** [comment]
@matejminar  for us to look into it  could someone, please, write detailed reproducible scenarios to confirm exactly what you mentioned in the problem? 

You mentioned: 
> It seems like in some case [...] metrics don't appear on the chart

How these cases can be isolated and reproduced? 

cc @jjbayer @Dav1dde

**Comment by obostjancic** [comment]
Closing this as it is not reproducible anymore. We have encountered #74720 and $74721 and will continue there
