### ISSUE TITLE
Broken link on the pricing page

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#74252]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the [Pricing page](https://sentry.io/pricing/)
<img width="1245" alt="Screenshot 2024-07-15 at 10 15 12" src="https://github.com/user-attachments/assets/b63a8d92-5d5b-4949-b592-8942e80a517f">

2. Scroll down to the feature comparison page

3. Click on _Discover: build queries_
4. It brings users to [this](https://docs.sentry.io/product/discover-queries/query-builder/) page instead of [this](https://docs.sentry.io/product/explore/discover-queries/query-builder/)

### Expected Result

The link should point to the correct page in the docs

### Actual Result

The link points to a 404 page

### Product Area

Other

**Comment by joshuarli** [comment]
Closing; issue's fixed.
