### ISSUE TITLE
Broken link in the UI

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#74251]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the https://{org-slug}.sentry.io/settings/projects/{project-name}/filters/data-filters/ page, and click on common naming patterns
<img width="621" alt="Screenshot 2024-07-15 at 10 03 16" src="https://github.com/user-attachments/assets/54848abe-f386-4319-9394-d80172f844b7">

It brings the user [here](https://docs.sentry.io/product/data-management-settings/filtering/#transactions-coming-from-health-check) instead of [here](https://docs.sentry.io/concepts/data-management/filtering/#transactions-coming-from-health-check)

### Expected Result

The link should point to the correct page in the docs

### Actual Result

The link points to a 404 page

### Product Area

Settings - Projects

**Comment by roggenkemper** [comment]
Will put a PR up to fix this!
