### ISSUE TITLE
OpsGenie Integration - close alerts instead of acknowledging

### ISSUE THREAD

**Issue by clemblanco** [getsentry/sentry#74256]
### Problem Statement

It looks like Sentry is trying to acknowledge alerts on OpsGenie when the integration is enabled and a Sentry issue is marked as "resolved" on Sentry.

### Solution Brainstorm

Even though, I'm currently struggling to see this working (see issue [#74230](https://github.com/getsentry/sentry/issues/74230)) it seems like according to OpsGenie documentation, the acknowledgment of an alert is not matching the resolution of an issue on Sentry.

For OpsGenie, an alert can be acknowledged when someone being on-call is starting to investigate an issue so other responders don't get alerted and the team knows someone is starting to look at an issue. See more information [here](https://support.atlassian.com/opsgenie/docs/acknowledge-and-unacknowledge-an-alert/).

From a Sentry point of view, resolving an issue means we no longer expect the same issue to occur again.

These two don't seem to match and therefore, closing an alert on OpsGenie feels like would be more appropriate instead.

### Product Area

Settings - Integrations

**Comment by leedongwei** [comment]
This is useful product feedback. I'll get the team to review it. Thanks!

**Comment by sentaur-athena** [comment]
This is fixed now.
