### ISSUE TITLE
No way to filter performance Alerts to exclude API like upload a file

### ISSUE THREAD

**Issue by bitsal** [getsentry/sentry#74265]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

We try to configure performance alerts by transaction duration and want to filter them by custom tags, e.g. we want to exclude transactions that are related to file upload. We have added a custom tag "request.content-type" and want to filter by it using "Filter events" search box.

### Expected Result

Custom tags are allowed to filter transactions OR any other way to filter transactions like upload file w/o setting exact API path.

### Actual Result

It says that it is not possible to filter by this custom tag and any custom tag we have.

### Product Area

Alerts

### DSN

https://fdde445821194c7787f7c883b52b8c37@o1044699.ingest.sentry.io/6501848

**Comment by rachrwang** [comment]
Thank you for filing this request - this is something we're planning to support in the future cc @bcoe, @Dhrumil-Sentry
