### ISSUE TITLE
[Mobile Replay SDK - iOS & RN] Video duration should be sent in MS

### ISSUE THREAD

**Issue by michellewzhang** [getsentry/sentry#74289]
There are inconsistencies in the units for the `video.duration` the SDK is sending. Android SDK sends them in MS, while looks like iOS and React Native have been sending them in seconds (ex. Android gives me `5000`, iOS gives me `5`). 

Our player code has been under the assumption that the duration is in MS, which is why we're seeing some bugs in the playback when playing/pausing, as well as bugs in the timeline when you try to zoom in. 

We should align these units, and change this data to be in MS instead.

**Comment by bruno-garcia** [comment]
This PR: https://github.com/getsentry/sentry-cocoa/pull/4163 should address it on both iOS and RN, since RN isn't dealing with the duration directly, it's all native.
