### ISSUE TITLE
Alert wizard copy and illustration for span based metrics

### ISSUE THREAD

**Issue by ArthurKnaus** [getsentry/sentry#74333]
Custom Metrics should have `(deprecated)` next to them if you have rules feature flag enabled.

![Image](https://github.com/user-attachments/assets/a6bd58a9-8b2f-4fc0-b17f-51c4fb572b15)

**Comment by Jesse-Box** [comment]
Here's the revised svg
![Image](https://github.com/user-attachments/assets/5107ca78-cc3a-4ea8-8339-ae986470afcd)
