### ISSUE TITLE
Cleanup manually sampled transactions

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/sentry#74340]
We need to cleanup sampling in sentry for manual transactions.

example:
https://github.com/getsentry/sentry/blob/2b4cd05450b5f5602d80f3758a5c42ee374656fa/src/sentry/ingest/consumer/processors.py#L44-L47

All such cases are overriding sdk sampling so the DSC sample rates are inaccurate.
Move the sampling logic to a rate that's passed to the sdk via `traces_sampler`.

CAUTION: Ingest consumers are very critical and overloaded so make sure SDK overhead is low when we make this change and rollout carefully with monitoring.

**Comment by antonpirker** [comment]
A quick code search for the linked `SENTRY_INGEST_CONSUMER_APM_SAMPLING` above shows that is is only something other than `0` in the tests. So the sampling rate for ingest consumsers is always `0`? (or is this settingoverwritten somewhere)

I also was unable to find transactions with a name of for example `"ingest_consumer.process_event"`.

**Comment by jan-auer** [comment]
The setting is set to `0.02` [in getsentry](https://github.com/getsentry/getsentry/blob/12b7a3aede21d041e612b30129a18904ea04370c/getsentry/conf/settings/defaults.py#L1146).
