### ISSUE TITLE
unresolve issue tooltip does not clear

### ISSUE THREAD

**Issue by MaxBittker** [getsentry/sentry#7435]
after clicking 'unresolve' on the issue details page, the tooltip moves but does not go away.

should be converted to use the `<Tooltip/>` component. 

![image](https://user-images.githubusercontent.com/5915546/36883014-18514252-1d8c-11e8-8dce-b4517dca3912.png)

**Comment by MaxBittker** [comment]
( cc @adhiraj )

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
