### ISSUE TITLE
Mobile Safari 5.1.1 is not filtering with enabled Safari 5 filter

### ISSUE THREAD

**Issue by AlexWayfer** [getsentry/sentry#7436]
I'm not sure if it should filter `5.1` or not. But I think that `5.0` should filter `≤ 5.0`, and `5` should filter `< 6`.

- The version of Sentry you're using

`8.15.0`

- Whether you're using Docker or another installation method

Docker.

- Include a stacktrace or other logs when relevant

![image](https://user-images.githubusercontent.com/6510020/36780306-aa0616a0-1c83-11e8-8ddc-0672f0ef7d03.png)
![image](https://user-images.githubusercontent.com/6510020/36899823-d5406028-1e31-11e8-9655-72008ccce869.png)

From JSON files:

```json
  "tags": [
    ["device", "iPad"],
    ["device.family", "iPad"],
    ["os", "iOS 5.1.1"],
    ["os.name", "iOS"],
    ["browser", "Mobile Safari 5.1"],
    ["browser.name", "Mobile Safari"]
  ],
  "contexts": {
    "device": {
      "model": "iPad",
      "brand": "Apple",
      "family": "iPad"
    },
    "os": {
      "version": "5.1.1",
      "name": "iOS"
    },
    "browser": {
      "version": "5.1",
      "name": "Mobile Safari"
    }
  },
  "sentry.interfaces.Http": {
    "headers": [
      ["User-Agent", "Mozilla/5.0 (iPad; CPU OS 5_1_1 like Mac OS X) AppleWebKit/534.46 (KHTML, like Gecko) Version/5.1 Mobile/9B206 Safari/7534.48.3"]
    ],
  },
```

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
