### ISSUE TITLE
Implement an image-diff tool where two images are diff'd with each other, different pixels are highlighted in pink (for example) in the resulting image. AKA the "pink image diff" tool.

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#74361]
The goal is to endup with an image like this:

![textcompare-image-diff](https://github.com/user-attachments/assets/28f35912-e153-412c-979b-ab24ae4f314f)

**Comment by billyvg** [comment]
This would be an awesome feature, but this ticket lacks some details on how it would be done. We'd most likely need to do this server side which would involve some costly infra. Given this + the new mutations tab, this probably isn't something we'll do sometime soon.
