### ISSUE TITLE
Clearer visual difference between "Resolve" and "Resolved" buttons

### ISSUE THREAD

**Issue by olagjo** [getsentry/sentry#74409]
### Problem Statement

When looking at an issue in the web-UI, the visual state of the "Resolve"-button is not particularly different between a resolved issue and an open issue:
<pre align="center"><img width="800" alt src="https://github.com/user-attachments/assets/bf3f78b3-5be6-45a1-9544-f008cf477d10" /></pre>
<pre align="center"><img width="800" alt src="https://github.com/user-attachments/assets/05c8d44a-c01f-45fb-8fc8-58ea96d3c3e7" /></pre>

An experienced user who is looking for it would notice that the "Archive"-button is missing, and that there is no dropdown for actions once an issue is resolved.
However, if you are just jumping on to an issue from a link, it's easy to think that the purple button, styled like a primary call to action, and saying "Resolved" is the button you should click when you have verified that the issue is resolved. 
(Based on the creation of this issue, it might not come as a surprise that I myself regularly accidentally unresolve resolved issues by clicking this button 😎)

### Solution Brainstorm

- Make the "Resolved"-status-badge less clickable by giving it secondary styling and maybe a checkmark?
- Move the word "Resolved" to a non-interactive badge where the "Archive"-button would be on an unresolved issue, and then make the call to action "Unresolve" on the button that unresolves?
- Add a little "Issue is resolved"-text above the unresolve-button and change the text on the button to be "Unresolve"?
- Make the hover-styling on the button red or in some other way indicate that a click will make an unsatisfying/"bad" change to the status of the issue, instead of a satisfying/"good" change?

### Product Area

Issues

**Comment by mrduncan** [comment]
@olagjo agreed! We don't have anything ready to show yet but we're currently in the process of making some changes to the issue details page which will address this in the next few of months.

**Comment by mrduncan** [comment]
Going to consolidate this with #50193. We have some changes here we're excited to show off very soon!
