### ISSUE TITLE
Offer Support for User Feedback

### ISSUE THREAD

**Issue by CristianOnisor** [getsentry/sentry#74411]
### Problem Statement

For each User Feedback you have the option to add comments for internal team usage currently in Sentry but not to send directly messages to each user to offer support on their concerns. 

### Solution Brainstorm

You can add a switch in the User Feedback section, to switch from internal comments to User Support and then to be able to write support messages and send them to the users directly via email. In this manner you can offer support to the users within Sentry app since the users emails are stored.

### Product Area

User Feedback

**Comment by CristianOnisor** [comment]
![shot_240715_154514 (1)](https://github.com/user-attachments/assets/bbff1722-2f9f-49b9-94c3-1f077e3d20a0)
Added also a screenshot to show the section where we can have the switch to support directly to users

**Comment by jas-kas** [comment]
Hi @CristianOnisor 👋 

Thanks for sharing this feature request!

>  ....to User Support and then to be able to write support messages and send them to the users directly via email. 

Do you just want to send a one-off email to the user (as in, Sentry would not display any reply to the email or any part of the remaining email thread), **or** rather be able to have a dialogue with the user from within the Sentry UI?

With the latter solution, there's a lot of complexities. That would effectively mean we have an email client in Sentry. We're not looking to build something that advanced right now, as we want to keep the product simple, which does mean a few additional manual steps for our users.

**Comment by CristianOnisor** [comment]
Hi Jasmin,

Ideally to have a dialogue thread with the users for the cases when they
are not using properly the system functionality and the support would cover
their feedback/needs.

Best,

*Cristian ONIŞOR <https://www.linkedin.com/in/onisorcristian/>*
Mobile: +40 757 19 84 85 <+40+757+19+84+85>
Skype: cristian.onisor

This communication contains information which is confidential and may also
be privileged. It is for the exclusive use of the intended recipient(s). If
you are not the intended recipient(s), please note that any distribution,
copying or use of this communication or the information within is strictly
prohibited. If you have received this communication in error, please notify
the sender immediately and then destroy any copies of it. All rights
reserved.

**Comment by billyvg** [comment]
This feature is a great idea and makes sense given what User Feedback currently offers. At the moment, we're going to focus on making User Feedback more of a debugging tool rather than support.
