### ISSUE TITLE
Android Source Context integration doesn't support most Android repositories

### ISSUE THREAD

**Issue by zsperske** [getsentry/sentry#74435]
### Problem Statement

The "[known limitations](https://docs.sentry.io/platforms/android/enhance-errors/source-context/#known-limitations)" of the Source Context feature on Android mentions `Package declaration and file tree must match for source lookup to work`. **Most Android repositories cannot meet this requirement**. A basic Android project with only one Gradle module would have a file hierarchy that looks like this:

```
repoRoot/
    app/
         src/main/java
              com/company/app
                    MainActivity.kt
    build.gradle.kts
```

The package name of `MainActivity.kt` will be `com.company.app`. The limitations say that the file must live in the `com/company/app` directory relative to the project root when in fact it will live in `app/src/main/java/com/company/app`.

Package names only match file hierarchy relative to the `java` (or `kotlin`) directories within their respective Gradle module. Any amount of directories can exist above that point.

One "easy" fix would be to allow specifying a root directory to start looking from (`app/src/main/java` in this example), however this could easily break if the project is refactored and would also not support multi module projects which is most mature Android projects. Here's an example file hierarchy of a multi-module project:

```
repoRoot/
    build.gradle.kts
    app/
         build.gradle.kts
         src/main/java
              com/company/app
                    MainActivity.kt
     features/
         feature1/
              build.gradle.kts
              src/main/java
                  com/company/feature1
                      SomeClass.kt
    libraries/
         networking/
             build.gradle.kts
             src/main/java
                  com/company/networking
                      SomeOtherClass.kt
```

There are multiple Gradle modules, with varying numbers of layers of directories above them. Again the "easy" solution might be to allow specifying multiple source directories to search in but this would quickly become a maintenance nightmare. Real world Android projects have hundreds or even thousands of Gradle modules.

For a real example here is a Github project: https://github.com/vmadalin/android-modular-architecture

### Solution Brainstorm

The `settings.gradle` file in a Gradle project could be used to find the path to each Gradle module in the project. Another option is looking for `build.gradle` and `build.gradle.kts` files as they appear in the root directory of a given Gradle module.

However, I wouldn't be surprised if there are lots of edge cases that wouldn't be covered by these.

### Product Area

Issues - Source Maps

**Comment by mrduncan** [comment]
Really appreciate the detail here, thank you! For full transparency, we don't have any planned work in this area at the moment but we will review and follow up when that changes.

**Comment by kahest** [comment]
There is a related issue on the SAGP repo about supporting source context for multi-module setups: https://github.com/getsentry/sentry-android-gradle-plugin/issues/685

**Comment by realkosty** [comment]
@kahest @mrduncan Is there any workaround we can think of? I'm wondering if there's a way to add a simple script as a step before Sentry gradle plugin runs that copies all source code into the root directory, then cleans up after?

**Comment by markushi** [comment]
As this is mainly a topic for our Sentry Android Gradle plugin, let's close this in favor of https://github.com/getsentry/sentry-android-gradle-plugin/issues/685
