### ISSUE TITLE
Regression version comparison incorrectly identified issue as regressed, when version was older than resolved-in version

### ISSUE THREAD

**Issue by jboulter11** [getsentry/sentry#74448]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

See:
https://dropbox.sentry.io/issues/5597803787/activity/?project=4505546600087552

I do not know why this happened.

### Expected Result

Sentry should have compared the version numbers 388.0.6 vs 388.0.8 and concluded there was no regression.

### Actual Result

Sentry compared 388.0.6 and 388.0.8 and determined 388.0.6 to be equal to or greater than 388.0.8, which is incorrect.

### Product Area

Issues

### Link

https://dropbox.sentry.io/issues/5597803787/activity/?project=4505546600087552

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2226) by [Unito](https://www.unito.io)

**Comment by armenzg** [comment]
Hey @jboulter11 👋 
Thanks for reporting. I will have a look.

**Comment by armenzg** [comment]
I have placed the issue into the backlog after attempting a fix.

These are my notes from today:
* The developer had marked the issue to be resolved in [388.0 (388.0.8)](https://dropbox.sentry.io/releases/com.getdropbox.Dropbox%40388.0%2B388.0.8/?project=4505546600087552)
  * I have noticed that the releases differ in the name of the release `com.getdropbox.Dropbox` vs `com.getdropbox.DropboxTest`
![Image](https://github.com/user-attachments/assets/5b33f98a-112e-4452-b289-c8c91be123d5)
* The event that caused the regression was on release [388.0 (388.0.6)](https://dropbox.sentry.io/releases/com.dropbox.DropboxTest%40388.0%2B388.0.6/) at 2:24pm
![Image](https://github.com/user-attachments/assets/c7c9b437-8b26-445c-9ad8-a3be2de8929e)
  * Noticed that the patch version is 6 which is less than 8
* I have attempted to create a test case in #74526 
  * More time is needed to determine if the test case was written properly as it does not reproduce the reported issue

**Comment by armenzg** [comment]
For anyone who ends up picking this up, this PR tries to reproduce this issue:
https://github.com/getsentry/sentry/pull/74526/files

**Comment by jboulter11** [comment]
This happened again but this time with versions using `release date` instead of semver: https://dropbox.sentry.io/issues/5918496859/activity/?project=4505546831036416

`44d3cb5` is older than `28a9559` but it is being treated as newer and reopening the ticket here.

**Comment by lobsterkatie** [comment]
Huh - you're right, that does seem quite backwards.

![Image](https://github.com/user-attachments/assets/f65b7706-5685-4d99-ae95-7d9f72b726eb)
![Image](https://github.com/user-attachments/assets/854b2d1e-4687-489c-9038-8315df7d4f77)
![Image](https://github.com/user-attachments/assets/4441f294-72b4-4c02-b1d7-493fa5b60cdc)

When your colleague marked it as resolved shortly before it got marked as having regressed, do you happen to know which resolve option he used? (It shouldn't matter - they should all work - but I'm trying to narrow down my search for the problem. The[ code in question](https://github.com/getsentry/sentry/blob/6b87ddf79ef6388fc678bb395626921b7da9cc07/src/sentry/models/groupresolution.py#L64) is relatively straightforward, and nothing is jumping out at me.)
 ![Image](https://github.com/user-attachments/assets/d3a6dceb-6293-4708-ae28-aaa17ebdc40e)

**Comment by jboulter11** [comment]
I unfortunately do not know and due to yesterday's layoffs, I cannot ask them.  I'd guess they either picked next version or they picked a specific commit/current release.  I can't be sure, unfortunately.

**Comment by lobsterkatie** [comment]
Oof. Bad timing, sorry. 😓 

Okay, I'll keep investigating, thanks.

**Comment by armenzg** [comment]
There's a chance that this bug may also be fixed by #80737

**Comment by armenzg** [comment]
I just noticed you also reported sha-based releases. I will look at it this afternoon.

> This happened again but this time with versions using `release date` instead of semver: https://dropbox.sentry.io/issues/5918496859/activity/?project=4505546831036416
> 
> `44d3cb5` is older than `28a9559` but it is being treated as newer and reopening the ticket here.
