### ISSUE TITLE
[Hydration Errors] Add amplitude analytics to hydration error tools

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#74456]
I want to be able to have charts like:
- [x] ~~when the issue stream items are fetched, how many hydration errors does the list contain?~~ Can redash query for num issues per proj, org, etc. No need to track how many per issues stream.
- [x] when the issue details page is rendered, is it for a hydration error?
- [x] Log an event for each interaction (debounced) with the slider-diff-tool
- [x] Log an event each time the hydration diff modal is opened, include what page did the button click happen on
- [x] Log an event each time the hydration diff modal tabs are changed, include which tab was picked.

Also:
- [ ] Clone the rage click issue dashboard in Redash: https://redash.getsentry.net/dashboards/227-rage-click-issues

**Comment by aliu39** [comment]
Looks like there's already an analytics event for #4: https://github.com/getsentry/sentry/pull/61888. Might not track the page though.

**Comment by aliu39** [comment]
> Log an event for each interaction (debounced) with the slider-diff-tool
An approach would be to track _only the first time_ the user clicks or drags the slider, since they last visited the page
