### ISSUE TITLE
[Hydration Errors] Improve UI labels inside the slider-diff-tool

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#74458]
Add "Before" and "After" labels to the top left & right corders of the slider-diff tool. This should help people understand it slightly better.

![Image](https://github.com/user-attachments/assets/efb7c2e5-f0c8-42a6-a703-8ae0acaf7cda)

**Comment by bruno-garcia** [comment]
Could a 'tooltip' be an educational opportunity? Or does everything understand what before/after mean?
