### ISSUE TITLE
Session replay not rendering correctly.

### ISSUE THREAD

**Issue by Ulset** [getsentry/sentry#74495]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Set up sentry session replay as according to the sentry for remix documentation.
2. Use the app
3. Watch replay. Observe that the rendering of the page is not updating correctly

### Expected Result

This is the page on the app:
<img width="1003" alt="bilde" src="https://github.com/user-attachments/assets/dafad22b-54ed-455c-8226-d341a2f3bcc0">

This is whats rendered on sentry.io:
<img width="774" alt="bilde" src="https://github.com/user-attachments/assets/54ae35dc-3db8-46fe-b2d3-a58f5af59b7c">

As you can see it seems like sentry doesnt recognize that this was a new page render, and renders the new page at the bottom of the old one 

### Actual Result

<img width="753" alt="bilde" src="https://github.com/user-attachments/assets/474ed008-257f-474f-8723-a2f41d3a8c0b">

### Product Area

Replays

### DSN

https://edab7551bfaf9f75bb0d6ffb648fe960@o4507489363165184.ingest.de.sentry.io/4507489365721168

**Comment by c298lee** [comment]
Hi @Ulset, thanks for reporting this. Can you share a link to the replay where you're experiencing this? Also is there a public link to your app that you could share? Thank you!

**Comment by bruno-garcia** [comment]
Could you also share the sdk version you're on?

**Comment by bruno-garcia** [comment]
Please reopen if it persists
