### ISSUE TITLE
[Hydration Errors] Create a redash dashboard so we can have some observability over hydration errors

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#74501]
Basically we're talking about cloning this one, but changing the data to be related to hydration errors instead: https://redash.getsentry.net/dashboards/227-rage-click-issues

**Comment by ryan953** [comment]
the other analytics ticket is https://github.com/getsentry/sentry/issues/74456

**Comment by aliu39** [comment]
Added at https://redash.getsentry.net/dashboards/272-hydration-errors
