### ISSUE TITLE
Sentry C# RavenClient receiving 403 in webRequest.GetResponse()

### ISSUE THREAD

**Issue by AaronFixer** [getsentry/sentry#7451]
Using sentry-onpremise docker image (latest). 

I have made no changes to the Sentry configuration file, and I am tunneling the web API through Docker and access the port through an SSH tunnel. 

When attempting to make a Capture event on the RavenClient the Raven server is returning a 403 (OK).

Here's the client code `catch`: 

```
            catch (RabbitMQ.Client.Exceptions.BrokerUnreachableException e)
            {
                var ravenClient = new RavenClient("http://<SentrySecret>@localhost:9000/sentry//3");

                ravenClient.Capture(new SentryEvent(e.Message)); 

                Console.WriteLine("Successfully sent error to Sentry: ", e.Message);
                Console.ReadLine();
            }
```

Point at which 403 is being returned in the `Receiver.cs` (line 178) of the RavenClient: 

``` 
            using (var wr = (HttpWebResponse)this.webRequest.GetResponse())
```

Server-side is only returning the following from the Django logs: 

```
172.17.0.1 - - [05/Mar/2018:03:34:29 +0000] "POST /sentry//api/3/store/ HTTP/1.1" 403 8034 "-" "SharpRaven/0.0.0.0"
```

My assumption is this is because the django configuration hasn't been built to support localhost connections but normally this results in a 400. 

I can't really track down where this problem originates.

The Sentry web UI is working perfectly. I haven't enabled any special configuration, I have just set up a user, team and project.

**Comment by AaronFixer** [comment]
This is definitely a problem with Sentry and handling tunneling. If I change from `localhost:9000` to a public DNS and update the root URL, this works perfectly. 

I can understand if this isn't an important issue, but to those of us trialing Sentry its good to be able to use a local tunnel for testing the product.

**Comment by bruno-garcia** [comment]
It's a bit tricky to reproduce your issue.
I have tested the `onpremise` container with SharpRaven and it worked fine. I haven't setup the whole SSH tunneling though. 

Perhaps you can create a repro of the issue so we can pull and run a script for example?

I can confirm that I connect through localhost and it works fine so maybe it's an issue with your tunneling as suggested.

**Comment by h1ac0k** [comment]
same problem

**Comment by bruno-garcia** [comment]
Could you please try it again with [our new .NET SDK](https://github.com/getsentry/sentry-dotnet)?
Please feel free to reopen the issue if it still persists.
