### ISSUE TITLE
Breadcrumbs overflow

### ISSUE THREAD

**Issue by terrdus** [getsentry/sentry#7452]
Breadcrumbs are overflowing from element when no spaced report is inside.

Found solution:  change `break-word: keep-all` to `break-word: break-all` on `pre` element 

![image](https://user-images.githubusercontent.com/5702843/36973620-f91273f8-2073-11e8-8410-e9f2bad349cd.png)
![image](https://user-images.githubusercontent.com/5702843/36973644-0f4be230-2074-11e8-8cc2-c9855f4d1dae.png)

**Comment by billyvg** [comment]
Closed by #8993
