### ISSUE TITLE
Cannot load Caches page

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#74554]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. the customer tries to open the Caches page in production
2. the endpoint gives the following error: 

```
{
"detail": "Invalid quote at '[\"BackOfficeClient': quotes must enclose text or be escaped."
}
```
3. the page does not load properly

### Expected Result

the customer should be able to load the page

### Actual Result

the page is not loading

### Product Area

Insights

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2227) by [Unito](https://www.unito.io)

**Comment by DominikB2014** [comment]
hey @dalnoki !

Thanks for reporting this. I've confirmed this issue, the problem lies on our end. We didn't correctly handle quotation marks being in the transaction name within the cache module. I put up a PR to resolve this issue, fix should be up shortly! https://github.com/getsentry/sentry/pull/74667

**Comment by mthenw** [comment]
Hey, I'm the person that reported that issue to support team. It kind of fixed the original issue but the page still doesn't load. It shows loader in the transactions sections and the `https://us.sentry.io/api/0/organizations/xxxxx/events/?dataset=` endpoint returns 500.

**Comment by dalnoki** [comment]
hey @DominikB2014 thanks a lot for putting up a PR! I checked, and I can confirm that @mthenw shared here - should we open a new issue, or can you take a look here as well? Thanks in advance for letting me know!

**Comment by DominikB2014** [comment]
hey @dalnoki !
A new issue would be preferred here, as it sounds like it a seperate (but related) issue to the one originally posted
