### ISSUE TITLE
LLM Monitoring Pipeline tokens not showing

### ISSUE THREAD

**Issue by lambopancake** [getsentry/sentry#74638]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I want the "Total tokens used" to display on the columns and graph of the individual trace. 

![Image](https://github.com/user-attachments/assets/c5bf0a1e-8cf3-411d-bf58-37a148d61090)

### How are you getting stuck?

"Total tokens used" displays on the LLM Monitoring tab. But the total tokens does not display on the individual pipeline. I'm currently using nodeJS. The initial trace starts with a transaction `op: "ai.pipeline"`, then a child span `op:"ai.chat_completions.create.openai"`. The tokens are then displayed using `span.setData("ai.total_tokens.used",response.usage.total_tokens);`, but only shows in the LLM Monitoring tab.

![Image](https://github.com/user-attachments/assets/1bfee0a6-f2aa-4899-93a1-ed73d4bb9701)

### Where in the product are you?

Performance

### Version

sentry/node: 7.118.0

**Comment by colin-sentry** [comment]
The child span needs `ai.pipeline.name` set to `External.openai.prompt` in this case - that's how the token usage is linked back.

**Comment by gggritso** [comment]
Closing as stale! @lambopancake feel free to reopen if you're still having trouble.
