### ISSUE TITLE
500 error when trying to create alert for Sessions Dataset

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#74639]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

**1. Open up the Create Alert window with Sessions Dataset Selected**

![Image](https://github.com/user-attachments/assets/8671076c-ba1b-441f-9d73-8337cd488400)

**2. Click Save and see error banner**

![Image](https://github.com/user-attachments/assets/f2ad99dc-9d55-4209-9d5b-4daa544c9c8f)

[Link to the error we are seeing in Sentry](https://sentry.sentry.io/issues/5248385193/events/4eb0a3592a2e44c0a1975db42ad02435/?project=1)

### Expected Result

Alert should be created

### Actual Result

Alert is not created

### Product Area

Alerts

### Link

https://francisorg.sentry.io/alerts/rules/?statsPeriod=7d

**Comment by rachrwang** [comment]
Thank you for filing! Will try to get this on an upcoming rotational cycle

**Comment by mifu67** [comment]
Should be resolved now.
