### ISSUE TITLE
Unable to save Crash Free Session rate alert

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#74716]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the Alerts page
2. Create new Crash free session rate alert
3. Add dummy data
4. Try saving the rule - it will return an internal error

Example error: id: 064a31d78deb46978f5938fa094a47ec

### Expected Result

it should be possible to create a Crash Free Session rate alert

### Actual Result

it is not currently possible to create the alert

### Product Area

Alerts

**Comment by mgaldo** [comment]
Worth to mention that this is happening when trying to send the alert through a slack channel (public) (we have sent other types of alerts on that channel), I don't know if it also happens when setting an email alert but we don't want to send emails.

**Comment by mgaldo** [comment]
Hi @saponifi3d and @dalnoki the issue still persists when trying to create a crash free alert see attached screenshot

![Image](https://github.com/user-attachments/assets/1acbe5cd-f2d3-4c5c-b817-48db01116223)
