### ISSUE TITLE
We do not have samples on the metrics page for set metrics

### ISSUE THREAD

**Issue by obostjancic** [getsentry/sentry#74720]

**Comment by shellmayr** [comment]
Kafka schema is changed in: https://github.com/getsentry/sentry-kafka-schemas/pull/322/files
Snuba processor is changed in: https://github.com/getsentry/snuba/pull/6140

**Comment by shellmayr** [comment]
Additional relay change removing validation: https://github.com/getsentry/relay/pull/3864
