### ISSUE TITLE
[userFeedback] attachments that are not screenshots are very hard for support to download

### ISSUE THREAD

**Issue by joranbeasley** [getsentry/sentry#74731]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

add non image attachments such as csv/text to feedback

also see related issue i opened in the wrong subproject
https://github.com/getsentry/sentry-javascript/issues/13009#issuecomment-2244497464

### Expected Result

- display images inline, offer download for non-image files
- **or** offer one big zip for download
- **or** offer download links for each item including images

### Actual Result

![Image](https://github.com/user-attachments/assets/15825ba1-e5d7-4adc-8a40-c6cb8d892e21)

it tries to create an image preview of a file that is not an image 

### Product Area

User Feedback

### Link

https://zentra.sentry.io/feedback/?feedbackSlug=zentra-frontend%3A5633115988&project=4505371415216128&referrer=feedback_list_page&statsPeriod=30d

**Comment by bruno-garcia** [comment]
That's fair. if the mime type isnt' of something we can preview, we could offer a download button similar to the current attachments experience on issues.

Curious, would you share a bit about the use case you have? Could be useful for us to better describe on the docs for other users that would like to use attachments for their own app/use cases.

**Comment by michellewzhang** [comment]
https://github.com/getsentry/sentry/pull/74802 this PR should add support to allow downloading the non-image files

**Comment by joranbeasley** [comment]
uploading logfiles or other supporting evidence  .... typically raw smallish text logfiles or binary files that are simply struct packed values with a header, and csv files
