### ISSUE TITLE
[Mobile Replay] Issue Detail Tab: Incorrect number of Users

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#74751]
The different users here are defined by the `user.id`, and there are 2 different users, but the app says 5:

![Image](https://github.com/user-attachments/assets/fa04f272-ffa5-4eee-997f-d060da562da4)

Example: https://sentry-sdks.sentry.io/issues/5607602092/replays/?project=4507596011798528&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&selected_replay_index=0&statsPeriod=30d&stream_index=0

Relates to:
* https://github.com/getsentry/sentry/issues/74747

**Comment by c298lee** [comment]
@bruno-garcia the underlying code is actually only counting the number of replays, not the users. Do we want to modify the message to say the "number of replays", or do we want to add a new hook that actually counts the number of users?

**Comment by jas-kas** [comment]
@c298lee users if possible, depending on complexity. i think that's more of an interesting insight than pure replay count

**Comment by c298lee** [comment]
@jas-kas implementing a user count would be a little complex since we will need backend support to write a new query. Our replay count endpoint currently only returns the count and no user info so it would need to be modified for this case. I think we should just modify the text for this case, wdyt?

**Comment by c298lee** [comment]
We decided to modify the text to accurately represent that a replay count is being shown due to complexity of getting a user count. We will follow up and create a hook that gets the user count in https://github.com/getsentry/sentry/issues/75103
