### ISSUE TITLE
Unable to send email: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by lxcid** [getsentry/sentry#7475]
I keep getting this error

```
[Errno 99] Cannot assign requested address
```

My configuration is as follow…

```
SENTRY_SERVER_EMAIL=sentry@example.com
SENTRY_EMAIL_HOST=smtp.gmail.com
SENTRY_EMAIL_USER=sentry@example.com
SENTRY_EMAIL_PASSWORD=********
SENTRY_EMAIL_PORT=587
SENTRY_EMAIL_USE_TLS=True
```

I'm using docker setup and I have ensured that my email is working…

![screenshot 2018-03-06 13 25 27](https://user-images.githubusercontent.com/297156/37015436-1a9c8bde-2142-11e8-9db9-f2372658f558.png)

**Comment by Sovetnikov** [comment]
It's a outgoing connection problem. Check that smtp.gmail.com:587 is open to connection from your docker container.

**Comment by markstory** [comment]
Closing as this is a configuration issue in your environment and not something we can fix.

**Comment by ChrisHumphry** [comment]
I am getting this same error and I've tried curl telnet://smtp.sendgrid.net:587 from the container which works perfectly well. So it is not an problem with environment configuration
