### ISSUE TITLE
Platform choices should be sorted alphabetically

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#74781]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a new project
2. Observe any platform list (it doesn't matter whether you choose "Popular", "Browser", etc.)

![Image](https://github.com/user-attachments/assets/ca99a831-d147-4455-8b2c-419cb7a3969a)

### Expected Result

The platforms should be sorted alphabetically.

### Actual Result

They are seemingly randomly sorted (e.g. why is Dart first)?

### Product Area

Projects - Project Creation

**Comment by priscilawebdev** [comment]
Thanks for reporting this, @benvinegar ! the issue was moved to our triage queue and we will check it out soon
