### ISSUE TITLE
Copy Feedback URL does not work

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#74834]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open any feedback on the User Feedback tab
2. Click on the dropdown menu next to the feedback ID
3. Select "Copy feedback URL"

![Image](https://github.com/user-attachments/assets/d7f56886-6e98-4ee5-a6c9-1582fd1d8998)

### Expected Result

Get a link to the feedback, for example:
https://dev-curumas.sentry.io/feedback/?feedbackSlug=notjava%3A5634839372&mailbox=resolved

### Actual Result

The followed is copied:
`https://dev-curumas.sentry.io[object Object]`

Workaround: copy the URL directly from the browser.

**Comment by jas-kas** [comment]
Fixed in https://github.com/getsentry/sentry/pull/74874
