### ISSUE TITLE
Queries, requests page access issue

### ISSUE THREAD

**Issue by RajeshVE22** [getsentry/sentry#74917]
### Self-Hosted Version

24.6.0

### CPU Architecture

64-bit x86

### Docker Version

27.0.3

### Docker Compose Version

1.29.2

### Steps to Reproduce

I deployed latest version of sentry on self hosted server. Every thing working fine but there are some page in side performance menu. I am not able to access that file. When I clicked its redirect me to dashboard page or throw message:  _**The organization you were looking for was not found.**_ 

![Image](https://github.com/user-attachments/assets/df007e58-8e37-4c7e-9637-bd8e368d0fcf)

### Expected Result

I deployed latest version of sentry on self hosted server. Every thing working fine but there are some page in side performance menu. I am not able to access that file. When I clicked its redirect me to dashboard page or throw message:  _**The organization you were looking for was not found.**_ 

### Actual Result

I deployed latest version of sentry on self hosted server. Every thing working fine but there are some page in side performance menu. I am not able to access that file. When I clicked its redirect me to dashboard page or throw message:  _**The organization you were looking for was not found.**_

**Comment by aldy505** [comment]
Please refer to this issue, there's a fix there: https://github.com/getsentry/self-hosted/issues/3145

Or just simply upgrade to 24.7.1 or so, make sure the feature flags on your `sentry.conf.py` matches the ones defined on the repository!

**Comment by gggritso** [comment]
@RajeshVE22 I'm going to close this, since we haven't heard back from you for a while! Please re-open if you're still having trouble
