### ISSUE TITLE
[User Feedback] Offer a way to turn off spam detection from the Feedback Index page

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#74940]
## Problem

A customer may want to be alerted on all feedbacks they received if they either have a low volume of them , for testing purposes, or because the possibility of spam is low since all submitters are authenticated users.

The first few feedbacks an org may receive could go directly to the spam folder and it's not apparent that you can turn off spam detection in project settings unless you go to docs.

[User feedback on this](https://github.com/getsentry/sentry-javascript/issues/13001#issuecomment-2247904329)
![Image](https://github.com/user-attachments/assets/67b0650c-b338-4b39-84a0-526e81617364)

## Solution Brainstorm

Surfacing the ability to turn this off:
- Add a banner on top of feedbacks in the spam folder that deep link to the relevant project settings page
- Add it in the hover message over "Spam" tab
- Add it in the Internal Activity notes

![Image](https://github.com/user-attachments/assets/f6bfea2c-d545-4b05-8723-8500a045ab51)

Surfacing the ability to turn this on
- Add a banner on top of feedbacks in the spam folder that deep link to the relevant project settings page
- Add it in the hover message over "Spam" tab

**Comment by bruno-garcia** [comment]
> The first few feedbacks an org may receive could go directly to the spam folder and it's not apparent that you can turn off spam detection in project settings unless you go to docs.

A feedback should end up in spam if it's rated as spam, and the volume shouldn't play a role here. Is the user saying our detection logic is creating too many false positives?

**Comment by jas-kas** [comment]
@bruno-garcia well there test feedbacks went straight to spam, so yes there were false positives

**Comment by bruno-garcia** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/1633368?s=64&amp;u=856a9e52d4cdc92eac2ff9e1f97900df39ae5e4d&amp;v=4">@bruno-garcia](https://github.com/bruno-garcia) well there test feedbacks went straight to spam, so yes there were false positives

We should track this! One ideas to improve the spam detection algo is by adding “Don’t mark as spam if it seems like a test feedback”

**Comment by aliu39** [comment]
> > [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/1633368?s=64&amp;u=856a9e52d4cdc92eac2ff9e1f97900df39ae5e4d&amp;v=4">@bruno-garcia](https://github.com/bruno-garcia) well there test feedbacks went straight to spam, so yes there were false positives
> 
> We should track this! One idea to improve the spam detection algo is by adding “Don’t mark as spam if it seems like a test feedback”

I'm worried those instructions would be too generic and weaken the detection. Right now that could refer to a lot of things, do you have ideas about specific qualities of test feedback?

It might be simple + effective to mark any feedback with the word "test" in it as not spam. I think it's common to use that word in test messages.

**Comment by aliu39** [comment]
On a different note, I was thinking it could be nice to have a log/analytic/metric for whenever a user marks a feedback as spam/not-spam. We can add to a tooltip or something, encouraging users to mark falsely classified feedback. This way we can build out a pool of real examples
