### ISSUE TITLE
Latest Alerts (via Project Details) inaccurate, not syncing with actual Alert Status

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#74970]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Configure Metric Alert
2. Add an alert rule Action (to notify PagerDuty, in this case) 
3. Remove alert rule Action (after 1hr, in this case)
4. Allow Metric Alert to fire

### Expected Result

Alert Status, List of Recent Alerts, Latest Alerts should appear in-sync

### Actual Result

I'm seeing an issue where some alerts seem to be stuck as triggered on the Project Details page. When you click into the alerts the Alert Status is Resolved. 

![Image](https://github.com/user-attachments/assets/623969d8-8c72-462d-aac9-c3b80c45f526)

![Image](https://github.com/user-attachments/assets/504cb357-b6f6-49a7-bd76-53c63cebde74)

### Product Area

Projects - Project Details

**Comment by ceorourke** [comment]
Is this only reproducible in alerts that recently had an action removed? Was it the only action on the rule? Are there 3 different alert rules here that are titled beginning with "Percent threshold change in n.."? Which one was clicked on? The screenshot shows it isn't resolved, so I'm confused.

**Comment by kpujjigit** [comment]
> Is this only reproducible in alerts that recently had an action removed? Was it the only action on the rule? Are there 3 different alert rules here that are titled beginning with "Percent threshold change in n.."? Which one was clicked on? The screenshot shows it isn't resolved, so I'm confused.

Hi @ceorourke - internally I couldn't seem to reproduce this. There was only a single PagerDuty action added that was promptly removed. There is only one Alert with the name in-question.

**Comment by ceorourke** [comment]
If it's not reproducible can the user just delete and re-create the rule, or is there a consistent problem with it?

**Comment by ceorourke** [comment]
I'm going to close this as it's been some months without a response. If this is still occurring, feel free to reopen.
