### ISSUE TITLE
Issue - Alert not identifying Regressions

### ISSUE THREAD

**Issue by mariana-espana** [getsentry/sentry#74980]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Hello

I know this issue was solved in this ticket here: https://github.com/getsentry/sentry/issues/52849

I started having this issue, is not all the time but it just happened for me.

### Expected Result

I expected my regression events to be triggered and send the issue in one of my integrations as well as my other issues that are not regressions.

### Actual Result

I have an issue regressed that doesn't trigger the data alert anymore. 

### Product Area

Alerts

**Comment by schew2381** [comment]
Hi there could you please file a support ticket in order to have all the information needed for debugging, thanks!
