### ISSUE TITLE
cannot upload js files

### ISSUE THREAD

**Issue by DophinL** [getsentry/sentry#7499]
sentry version:1.30.1

I can not upload js files suddenly,I used to uploaded for some times already.
![image](https://user-images.githubusercontent.com/8707316/37095239-42494528-2250-11e8-938d-4ccdfbebe6ab.png)

But I can upload map file.
![image](https://user-images.githubusercontent.com/8707316/37095267-5484f6a6-2250-11e8-9b3f-7968fe183110.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
