### ISSUE TITLE
source map name not equal to source file name

### ISSUE THREAD

**Issue by DophinL** [getsentry/sentry#7500]
My source file are named as FILE_VERSION,but source map are named just FILE.
So if I upload these files, source map feature won't work.
Does sentry offer any way to match them?
![image](https://user-images.githubusercontent.com/8707316/37095499-1450eaf8-2251-11e8-8973-772d8a49f3dd.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
