### ISSUE TITLE
Convert SmartSearchBar to SearchQueryBuilder in DDM

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#75044]
Malachi:
Hello!
I come with good news - the new search bar should now be feature-complete enough to be used in other parts of the app. Which includes the metrics page!
What I need from your team is help converting the old <SmartSearchBar /> component to use <SearchQueryBuilder /> instead. This work shouldn’t too much of your time, and I’m very happy to help with any issues, questions, or code reviews!
Some resources to help you get started:
See [here for the documentation](https://sentry.sentry.io/stories/?name=app/components/searchQueryBuilder/index.stories.tsx) which should help you understand how to use the component and how the old props map to the new one.
I’ve created a feature flag for your convenience which is enabled for internal orgs. [See here for the full list](https://github.com/getsentry/sentry-options-automator/pull/2018/files) - use the one that matches the product area.
GitHub issue to track this work (and which has all this info): https://github.com/getsentry/sentry/issues/75004
Thank you!

**Comment by priscilawebdev** [comment]
There was an issue with the `onChange` being fired more frequently than we expected, so we are waiting for the [PR](https://github.com/getsentry/sentry/pull/75082) to be merged
