### ISSUE TITLE
transaction is not a tag on span.duration

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#75136]
Tagging rule for transaction on span.duration can be found here: 
https://github.com/getsentry/relay/blob/152335119ad6acf10ac69ab853da3f8d27bd47b4/relay-dynamic-config/src/defaults.rs

Should be tagged, but is not selectable - investigate at which point this breaks

**Comment by shellmayr** [comment]
The problem does not seem to be in the Metrics API - when the tag is present on the metric, it is returned as confirmed via tests - continuing to investigate earlier in the pipeline.

**Comment by shellmayr** [comment]
The tag is in the data in clickhouse, it's returned by the API, and later filtered by the frontend. Are there any side-effects in other parts of the application if we stop filtering it out?
