### ISSUE TITLE
Plotting built-in span.duration let’s me filter on “span.description”, which only seems to work on the samples table and the line on the chart disappears

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#75134]

**Comment by shellmayr** [comment]
Preliminary investigation of this: it seems to be connected to https://github.com/getsentry/sentry/issues/75135 - when selecting a full (i.e. not truncated) span.description, the samples work. When selecting a truncated span.description in the filter, the samples disappear and the line basically also disappears except for a few examples.

**Comment by shellmayr** [comment]
Waiting with further investigation until there is sufficient evidence of this being a separate issue or the underlying truncation issue is solved.

**Comment by shellmayr** [comment]
Relay extracts certain tags like span.description only for very specific inputs to prevent high cardinality. One example for this is database queries, all others are not attached to the metric as a tag. This means that the tag is present on the sample span, but not on the metric, leading to the situation where we have samples, but no data returned from metrics query.

**Comment by shellmayr** [comment]
Was introduced by a refactor of the frontend and fixed in https://github.com/getsentry/sentry/pull/75715
