### ISSUE TITLE
Sentry request body hides empty dictionary keys

### ISSUE THREAD

**Issue by klemmchr** [getsentry/sentry#75146]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Send a request with this body

```json
{
    "displayName": {
        "": "foo",
        "de-DE": "bar",
        "en-US": "fooBar"
    }
}
```

### Expected Result

Sentry displays the body as-is.

### Actual Result

Sentry hides the empty dictionary key when displaying the body

![Image](https://github.com/user-attachments/assets/71268582-a5c5-49d3-9a94-71c551e20750)

The curl view shows the correct request body.

### Product Area

Issues

**Comment by jangjodi** [comment]
Hi [klemmchr](https://github.com/klemmchr), thanks for bringing this to our attention! I agree that this should be fixed and have added it to our backlog.
