### ISSUE TITLE
[Metrics] Mutually exclusive tag filters  break equations

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#75142]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to metrics and add the same metric twice (`a` and `b`)
2. Filter both of them by the same tag key but with different values
3. Add an equation of `a+b`

### Expected Result

The equation `f1` should show up as the sum of the two samples of the metric

### Actual Result

The graph with the equation appears empty. Note that the result is normally populated in the following cases:
- We add a tag filter in only one of the two metrics
- We add the same tag filter in both metrics
- We add different tag filter keys between the two metrics

### Product Area

DDM

**Comment by enochtangg** [comment]
https://github.com/getsentry/snuba/pull/6155
