### ISSUE TITLE
Cannot Page Through Projects Debug Files

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#75208]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1.) Navigate to Project Settings -> Processing -> Debug Files 
2.) Attempt to navigate to second page of debug info files
[

![Image](https://github.com/user-attachments/assets/41ed9e92-eaec-4e20-816e-3419c6aa7cb3)

](url)
3.) Nothing happens, received **POST https://reload.getsentry.net/metric/ net::ERR_FAILED 400 (Bad Request)** in dev console logs

![Image](https://github.com/user-attachments/assets/8cafe86d-60c5-42f1-9fe7-b4295ad1a6de)

Was able to recreate this issue in multiple organizations, both in firefox and google chrome most recent versions

### Expected Result

To have Sentry UI navigate to the second page of the debug info files

### Actual Result

Nothing happens

### Product Area

Processing

**Comment by vartec** [comment]
I'm seeing

```
Access to XMLHttpRequest at 'https://reload.getsentry.net/metric/' from origin 'https://sentry.sentry.io' 
has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
```

**Comment by kunal-511** [comment]
@ReneGreen27  Please assign this issue to me.
