### ISSUE TITLE
Sentry issues endpoint is returning incorrect value for annotations field

### ISSUE THREAD

**Issue by csureshfigma** [getsentry/sentry#75203]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Visit https://sentry.io/api/0/issues/4706902130/
2. Note that the field `annotations` returns an array object instead of an array of strings

### Expected Result

As per the sentry api documentation, it should be an array of strings. (ref: https://docs.sentry.io/api/events/retrieve-an-issue/)
```
    "annotations": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
```

### Actual Result

Array of objects 
`[{"url":"https://app.asana.com/0/[redacted id]/[redacted id]","displayName":"Figma Bugs#[redacted id]"}]`

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2235) by [Unito](https://www.unito.io)

**Comment by mrduncan** [comment]
Hi @csureshfigma, good find! That documentation is incorrect, `annotations` will be an array of objects with [`displayName` and `url` fields](https://github.com/getsentry/sentry/blob/master/src/sentry/api/serializers/models/group.py#L75-L77). We'll get that updated shortly to reflect the actual responses.

**Comment by csureshfigma** [comment]
@mrduncan Thanks! I wonder if this is a recent change? Since things only started breaking for us recently

**Comment by mrduncan** [comment]
Yes, it looks like it was, as a part of response to https://github.com/getsentry/sentry/security/advisories/GHSA-fm88-hc3v-3www.
