### ISSUE TITLE
Performance unit exceeded warning link returns 404

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#75213]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Customer reported receiving the following warning: "You have exceeded your [performance unit](https://sentry-docs-git-move-quota-to-billing.sentry.dev/pricing/quotas/manage-transaction-quota/) and [replay](https://docs.sentry.io/product/session-replay/) limit."

"performance unit" links to the following URL: https://sentry-docs-git-move-quota-to-billing.sentry.dev/pricing/quotas/manage-transaction-quota/

Which leads to a 404 page (probably because it's a development page, going by the .dev domain.)

![Image](https://github.com/user-attachments/assets/687196f0-4e22-441f-b015-ef72081d7a01)
![Image](https://github.com/user-attachments/assets/3eed1727-b461-42e5-8283-371071c62f93)

### Expected Result

"performance unit" should link to the URL: https://docs.sentry.io/pricing/quotas/manage-transaction-quota/

### Actual Result

"performance unit" currently links to the URL: https://sentry-docs-git-move-quota-to-billing.sentry.dev/pricing/quotas/manage-transaction-quota/

### Product Area

Other

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2233) by [Unito](https://www.unito.io)

**Comment by brianthi** [comment]
Can you confirm when this email was sent? We have since made changes to remove over quota emails linking to that temporary docs page.

**Comment by kerenkhatiwada** [comment]
hey @brianthi, sorry if it wasn't clear, this is in the Sentry UI. You can see the same in the org [here](https://getsentry.atlassian.net/browse/FEEDBACK-2233). 

![Image](https://github.com/user-attachments/assets/348b612b-baea-4f40-9b58-50ec5546a52c)

**Comment by brianthi** [comment]
This is resolved now.
