### ISSUE TITLE
Spend allocation not being saved due to ExclusionViolation

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#75220]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Specific to 1  customer org, could not reproduce it in my demo org.
1. Open up Spend allocations
2. Create a Transaction spend allocation for Project mentioned in Jira ticket of 24881 transactions
3. Internal error

![Image](https://github.com/user-attachments/assets/5d756c39-d273-4bb6-b4e1-e40b81c3f391)

### Expected Result

Should be able to save as the quota has been there and there is no duplicate record

### Actual Result

[Sentry Issue link](https://sentry.sentry.io/issues/5140934098/events/0bbfccc1efc44a868002c9ac78591032/?project=1)

### Product Area

Settings - Spend Allocation

### Link

See linked Jira issue

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2234) by [Unito](https://www.unito.io)

**Comment by brianthi** [comment]
Thanks for reporting this issue. Will add it to our backlog for now, and will respond here when we have an update.

**Comment by brianthi** [comment]
No ETA as of right now, but we'll update here when we do.

**Comment by keradus** [comment]
I face the same error also for `errors` spend limit (not only `transactions`)

**Comment by isabellaenriquez** [comment]
This issue has been resolved alongside https://github.com/getsentry/sentry/issues/76043.
