### ISSUE TITLE
[Feature Request]: Dynamic Breadcrumbs size

### ISSUE THREAD

**Issue by pranshuchittora** [getsentry/sentry#75336]
### Problem Statement

Currently sentry has some limits around various types of entities. https://develop.sentry.dev/sdk/envelopes/#size-limits
Speaking of the error events, it has been capped at 1MB. The default breadcrumbs size on the web and mobile sdks (maybe all) is 100. But this is sometimes not enough to debug things. Hence we increased this to 1K and found that events are getting dropped because the size exceeds 1MB.

Instead of statically defining this size, it would be great if there's a way to include as many breadcrumbs as possible upto 1MB so that none gets dropped. 

### Product Area

Unknown

**Comment by jangjodi** [comment]
I believe this truncation is occurring at the SDK level, @getsentry/sdks do you have context on this?

**Comment by mrduncan** [comment]
@pranshuchittora I'm going to close this for now as it's not something we can achieve in-product. If you can share which SDK you're hitting this on I can reopen and transfer over to that repo.
