### ISSUE TITLE
Create a high priority or medium priority condition for alert rules

### ISSUE THREAD

**Issue by Gekko0114** [getsentry/sentry#75413]
### Problem Statement

I would like to set alerts when high or medium items are triggered.

Seems that this feature was introduced before, but I can't choose that setting.
https://github.com/getsentry/sentry/issues/59872
https://github.com/getsentry/sentry/pull/61186

![Image](https://github.com/user-attachments/assets/6409c266-ed81-423a-b67d-69da57458f47)

Is this feature enabled now?
If not, I want this feature.

### Product Area

Unknown

**Comment by snigdhas** [comment]
Hi @Gekko0114, we're working on rolling this feature out to a wider audience - the feature should be available to all users in the coming weeks. I'll update this issue when the feature is GA. 

In the meantime, does your organization have the `early-adopters` setting enabled? Enabling this will grant you access to the feature while we're rolling it out.

**Comment by Gekko0114** [comment]
Sure, I am looking forward this feature, thanks :)

**Comment by ceorourke** [comment]
The high priority condition has been released!
