### ISSUE TITLE
Merge Similar treacherous to click

### ISSUE THREAD

**Issue by MaxBittker** [getsentry/sentry#7542]
on the similar issues tab, clicking the red error tab or the text of the issue will navigate you away to the issue details page. 
this makes it treacherous to select a group 

![image](https://user-images.githubusercontent.com/5915546/37194054-46bba584-2321-11e8-8fbb-d5d1b4ba7b3d.png)

**Comment by EvanPurkhiser** [comment]
I think the best bet is to probably just remove the link on the little error tag.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
