### ISSUE TITLE
Remove sensitive information prior to login

### ISSUE THREAD

**Issue by tuctboh** [getsentry/sentry#7547]
Hi,

We recently had a report via HackerOne that exposed information that we don't feel should be. In

https://github.com/getsentry/sentry/blob/master/src/sentry/templates/sentry/layout.html#L57
which calls
https://github.com/getsentry/sentry/blob/master/src/sentry/templatetags/sentry_react.py#L82

You're exposing the current version, as well as the administrators name. That can be used to know what holes are available in that version, as well as a potentially valid username to brute force.

Is there something that can be done to reduce the exposure?

Tnx, Tuc

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
