### ISSUE TITLE
Add a preview of scopes being applied to Auth Token permissions page.

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#75527]
### Problem Statement

Currently the auth token generation page below (ie. found in Settings > User Settings > User Auth Tokens > Create New Token)  uses 5 dropdowns to select which scopes to apply to the auth token.  It would be helpful to also include a preview of the actual scope being applied.  

![Image](https://github.com/user-attachments/assets/e52978be-b5b7-496d-bcca-7566a63aec84)

### Solution Brainstorm

For example if you select admin for Project and Organization Read/Write. There can be some sort of messaging letting you know that the Token you are generating will have `project:read project:write project:admin org:read org:write` scopes.  This helps avoid ambiguity on what the token will be able to do and also line up with our api docs which list the needed scope and not which option to select in the dropdown.

### Product Area

Settings

**Comment by michellewzhang** [comment]
hi @Fwang36, i've opened a PR to address this issue here: https://github.com/getsentry/sentry/pull/82070. thanks for your feedback, and let us know if you have any more feedback you'd like to share!
