### ISSUE TITLE
Metrics - 414 Request-URI Too Large

### ISSUE THREAD

**Issue by Ronniie** [getsentry/sentry#75632]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When you have multiple metrics, with group by options saved as default; Refreshing/Creating a duplicate tab returns 414 Request-URI Too Large, by nginx. Loading the page fresh, from the navigation bar works just fine.

1. Add 20 metrics (lol.)
2. Group by something
3. Save as Default
4. Try refreshing the page, or creating a duplicate tab.

Additionally, filtering by tags might cause this, too. Haven't played with that. I'm using Firefox 128.0.3 Windows 10 if that makes a difference.

### Expected Result

![Image](https://github.com/user-attachments/assets/3e0619b2-d54f-4e0b-9b2c-d7e3536ef6b8)

Expected Result would be not a 414 Request-URI Too Large error.

### Actual Result

![Image](https://github.com/user-attachments/assets/ed1327a8-d1e4-47b4-af22-9f7910ac565d)

### Product Area

Other

### Link

https://x.sentry.io/metrics

### DSN

https://5a8537c7edc2ef1609c84c1e24eb88ba@o4507646104567808.ingest.us.sentry.io/4507646108368896

**Comment by ale-cota** [comment]
hey, @Ronniie! 
Thanks for reporting this. May I ask what you were trying to do when you ran into this issue? Why were you refreshing/creating a duplicate tab?

**Comment by Ronniie** [comment]
Hey @ale-cota!

I was refreshing to see updated metrics (I'm not sure if it auto-updates), but I noticed the duplicating tabs portion when trying to take screenshots for this issue. 

This issue also happens when you bookmark, say you want to have a bookmark for 7 days, 30 days, or just different filters; It'll error depending on how lengthy the URL is.

**Comment by matejminar** [comment]
After careful consideration, we are ending the beta program and will retire the current Metrics solution on October 7th. Stay tuned for updates and [read the FAQs](https://sentry.zendesk.com/hc/en-us/articles/26369339769883-Metrics-Beta-Coming-to-an-End) for more details.
