### ISSUE TITLE
Dashboard - Widget with INP on Y-Axis shows incorrect units

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#75660]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Create a Widget with p75(measurement.inp)

### Expected Result

Same as LCP

![Image](https://github.com/user-attachments/assets/99487e12-a316-4222-a485-b462b57db22d)

### Actual Result

Looks like there is no Unit specified on the Widget

![Image](https://github.com/user-attachments/assets/f25ffc29-9837-4c64-a0e3-d25d3f0f1759)
![Image](https://github.com/user-attachments/assets/88ab566d-dc99-40a3-8aeb-b5ad83ce0aed)

### Product Area

Dashboards

### Link

https://demo.sentry.io/dashboard/76835/?dataset=events&project=5808623&statsPeriod=14d

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2242) by [Unito](https://www.unito.io)

**Comment by edwardgou-sentry** [comment]
Should be fixed once I get this merged:
https://github.com/getsentry/sentry/pull/75672

**Comment by edwardgou-sentry** [comment]
Fix is merged! The unit should be showing up properly now

![Image](https://github.com/user-attachments/assets/98b97ae5-55c8-493f-b7ce-dde3a7dae95a)
