### ISSUE TITLE
Alert rule "when" condition UI shows misleading placeholder

### ISSUE THREAD

**Issue by jonstaryuk** [getsentry/sentry#75700]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

We have an alert rule with a condition of the form "The issue is seen more than X times..." where the threshold is 0 (on purpose).

The number input UI shows a placeholder of 100, but in reality the rule is using a value of 0. This placeholder looks very similar to an actual 100 value — just a slightly different shade of purple.

This caused some confusion when our team was debugging alert rules.

![Image](https://github.com/user-attachments/assets/a2f68ec9-5252-409d-b554-7131aac73124)

![Image](https://github.com/user-attachments/assets/cbbc4305-d0fe-45c2-9742-904657e8e804)

![Image](https://github.com/user-attachments/assets/6bf5c07f-6c74-4041-ad81-f1fd69dab238)

### Expected Result

Since the alert rule backend uses a default value of 0, the input box should also use a placeholder value of 0.

### Actual Result

The input box shows a placeholder value of 100.

### Product Area

Alerts

**Comment by ceorourke** [comment]
Hello, we've already got this in our backlog to address, we'll update this ticket when it's fixed.

**Comment by mifu67** [comment]
Hi @jonstaryuk,

We just put out a fix that should address this. Let me know if the issue persists.
