### ISSUE TITLE
Issue's user list not showing user IDs

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#75713]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Send events with user ID, for example:
```
Sentry.setUser({ 
    id: 1031,
});

Sentry.captureException( new TypeError("UserID test"))
```
2. Go to Issues details -> Tags -> Users

### Expected Result

In the list with user values I expect to see the user ID. 

### Actual Result

In Sentry the user information has to have one of the following to count as a user: id, username, ip_address or email, but only the last 3 are displayed on the list. Users with only ID are not displayed correctly:

![Image](https://github.com/user-attachments/assets/48c5d070-71f1-46d2-b7d7-314fcff755d3)

### Product Area

Issues

### Link

 https://dev-curumas.sentry.io/issues/5686141479/events/d36665f37a2f4999bee6725d1fd043d3/tags/user/

**Comment by jangjodi** [comment]
Thanks for bringing this to our attention! I've put up some PRs that will fix the issue
