### ISSUE TITLE
Big number visualization doesn't scale with widget width

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#75730]
**Problem**: We have an issue with big number visualisations - by default they are cutoff and resizing them takes up an unnecessary amount of space on the dashboard. They should resize to fit the size of the widget.

![Image](https://github.com/user-attachments/assets/96b62a9c-e2de-476b-a386-8670919c1b8f)
![Image](https://github.com/user-attachments/assets/a1a50b2f-4732-458c-b4a4-19dddfa09e98)

- https://github.com/getsentry/sentry/pull/76209
- https://github.com/getsentry/sentry/pull/76669
- https://github.com/getsentry/sentry/pull/76955
- https://github.com/getsentry/sentry/pull/76995
- https://github.com/getsentry/sentry/pull/77097

**Comment by gggritso** [comment]
Re-opening this for tracking! It's still not in GA and I'm doing performance tests.

**Comment by gggritso** [comment]
👍🏻
