### ISSUE TITLE
UI discrepancy when fetching replays vs. showing number of replays with Env filtering

### ISSUE THREAD

**Issue by ajay-sentry** [getsentry/sentry#75754]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to issues page and filter on numerous environments
2. Open up an issue
3. Look at the number next to "replays" header
4. Click on replays tab
5. Confirm that number of replays !== number of replays shown when clicking tab

![Image](https://github.com/user-attachments/assets/45db5b84-da88-45e1-b12d-8623d00932b7)
![Image](https://github.com/user-attachments/assets/28a5ae48-1300-497c-954d-6a2afe053802)

### Expected Result

Filtering when calling this endpoint should contain the environment filters as a query parameter for both endpoint calls.

### Actual Result

Filtering only occurs for one of the endpoint calls (I'm not sure which)

### Product Area

Replays

### Link

https://codecov.sentry.io/issues/5334449981/replays/?environment=epic&environment=dd&environment=enova&environment=mailchimp&environment=production&environment=roblox&environment=snowflake&environment=prodvana&project=5514400&project=5215654&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=7d&stream_index=4

**Comment by michellewzhang** [comment]
example video of bad behavior:

https://github.com/user-attachments/assets/038351ba-6561-48e6-8217-21528384c706

**Comment by billyvg** [comment]
I checked this behavior against the new issue details UI and it no longer applies. Given that this will be fixed with the new UI, we will not address it in the current UI.
