### ISSUE TITLE
Github Integration Broken

### ISSUE THREAD

**Issue by geofferyj** [getsentry/sentry#75788]
### Self-Hosted Version

24.5.1

### CPU Architecture

x86_64

### Docker Version

 26.1.3

### Docker Compose Version

2.27.0

### Steps to Reproduce

follow the instructions to add github integration from [here](https://develop.sentry.dev/integrations/github/)

### Expected Result

after following the instructions, I expect that on the integrations page, when I click on add integration it should begin the integration flow

### Actual Result

after setting all the configurations, 
re-running ./install.sh

in the integrations page, when Add Installation button is clicked, it just redirects me to the home page of my self hosted sentry. and I can't login again as the login page is missing.

https://github.com/getsentry/self-hosted/assets/15072297/93c3ec15-f6de-4324-83a8-3b4029723e06

https://github.com/getsentry/self-hosted/assets/15072297/e842a330-4408-451d-a501-03e072a87b02

Please take a look at the videos above.

**Comment by cathteng** [comment]
When I set up GitHub locally for development, I have it configured like this:

![Image](https://github.com/user-attachments/assets/cf2a706d-1543-481a-9b6e-e1ebe3542c26)

--- 

From the docs (https://develop.sentry.dev/integrations/github/):

![Image](https://github.com/user-attachments/assets/b580ba72-900e-43d9-8269-ecb1704f3068)

**Comment by noma4i** [comment]
Any updates on that?

**Comment by leedongwei** [comment]
Small update that @cathteng is investigating this issue.

**Comment by cathteng** [comment]
@noma4i This seems unrelated to https://github.com/getsentry/sentry/issues/76018

Can you try it with the config I posted above? Without the extra callback URL?

**Comment by leshik** [comment]
> [@leshik](https://github.com/leshik) do you have the extra post-setup URL? I think you commented on the issue linked to this one, which is unrelated to this issue.

I tried all the options. Without the setup callback URL, clicking the button opens a window with the same Sentry page instead of Github app.

**Comment by cathteng** [comment]
I reconfigured my GitHub app for local development. I have the following settings and was not able to reproduce the error.

![Image](https://github.com/user-attachments/assets/6fe5c0fb-7401-4af5-bd04-08822d6454d7)

If you are able to share more details about what you are attempting that might help. e.g. what flow do you see when you click `Add Installation`? If you are seeing the screen with "Configure" then the app should already be installed -- please check the "Configurations" tab on the GitHub integration page. You may need to uninstall the app and then reinstall.

**Comment by leshik** [comment]
@cathteng more details are [here](https://github.com/getsentry/self-hosted/issues/3247) with the video, and the setup is exact same as yours.

**Comment by cathteng** [comment]
@leshik if you see the screen with "Configure" it means the app is already installed, possibly on another organization. We don't support connecting multiple sentry instances with a single Github organization. Can you please try uninstalling the GIthub app and retrying the installation process from Sentry?

**Comment by leshik** [comment]
@cathteng It's the same organization. We tried this setup at least 3 times from the beginning, with different GitHub accounts. The result is 100% reproducible and is described in the ticket with the video I mentioned.

**Comment by cathteng** [comment]
I am able to reproduce the issue when the GItHub app is already installed on the GitHub organization / user. If I remove the GitHub app from the organization / user, then I am able to see the `Install` button. Do you still see "Configure" even if you completely uninstall the GitHub app in GitHub?


https://github.com/user-attachments/assets/c28c1b20-fa98-4550-8ff4-fbe54c8b8bdb

**Comment by leshik** [comment]
> I am able to reproduce the issue when the GItHub app is already installed on the GitHub organization / user. If I remove the GitHub app from the organization / user, then I am able to see the `Install` button.

Yeah, that helped. After uninstalling and then installing again it seems working. Weird, because that same process was already done previously from that same GitHub integration page. Thanks.
