### ISSUE TITLE
Unassigned filter not working

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#75811]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to issues page
2. Search for `is:unassigned`

### Expected Result

The issues page will return unassigned issues

### Actual Result

The search return no results.

[This project](https://helpandprovid.sentry.io/issues/?project=5722597&query=&referrer=issue-list&statsPeriod=30d) has one unassigned issue as you can see in the screenshot:

![Image](https://github.com/user-attachments/assets/7b34a6f1-95fe-45fa-b099-f467774d12e7)

When I search for [unassigned issues](https://helpandprovid.sentry.io/issues/?project=5722597&query=is%3Aunassigned&referrer=issue-list&statsPeriod=30d), nothing is returned. 

![Image](https://github.com/user-attachments/assets/699a8817-28f4-4c36-899c-d5e29cd7555a)

### Product Area

Issues

**Comment by snigdhas** [comment]
Turned off the feature that was responsible for this bug - searching for `is:unassigned` works now. Thanks for filing the issue @rodolfoBee
