### ISSUE TITLE
Disabling Escalating Issues Algorithm for certain environments

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#75882]
### Problem Statement

For projects that have multiple environments, such as staging and production, users encounter issues when experimenting in the staging environment. This can generate numerous errors, which causes archived errors to be moved to the “Escalating” status, creating unnecessary noise. User is requesting the ability to disable the “Escalating” feature for specific environments. 

### Product Area

Issues

**Comment by scttcper** [comment]
feels really similar to https://github.com/getsentry/sentry/issues/57446 i'll add this to the backlog as well

**Comment by rachrwang** [comment]
Closing as we don't have plans to make this type of change anytime soon
