### ISSUE TITLE
Custom Integration token with Admin Permissions cannot change the roles of Organization Members

### ISSUE THREAD

**Issue by Macarthur501** [getsentry/sentry#75974]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Manage Organization Members using Terraform with a Custom Integration token with Admin permissions. Specifically I am trying to change the below roles:
- manager -> member
- owner -> billing 

I haven't seen any docs that state that this shouldn't be possible using a custom integration auth token with Admin permissions.

### How are you getting stuck?

When applying the terraform changes I am receiving 400 responses from the below API (I have omitted the values for the org slug and member id):
`Error: PUT https://sentry.io/api/0/organizations/{org-slug}/members/{member-id}/: 400 map[role:[You do not have permission to set that org-level role]]` 

The permissions set for the Custom Integration being used are:
![Image](https://github.com/user-attachments/assets/e7a17022-bbd4-46aa-8ed4-116f04688457)

### Where in the product are you?

Other

**Comment by schew2381** [comment]
@Macarthur501
Hey there, I did some double-checking and unfortunately for security reasons we don't allow internal integration tokens to change member roles.

This API is restricted to user tokens, b/c we need to know who is changing the role in order to validate against role escalation.
I'll make sure to change the docs to reflect this.

**Comment by Macarthur501** [comment]
@schew2381 Thank you for the reply, and updating the docs to reflect the behaviour. Are there any future plans around allowing this for integration tokens? Managing user roles with Terraform would be the optimal way for us, following an IaC approach.
