### ISSUE TITLE
Remove `Group.score` column

### ISSUE THREAD

**Issue by wedamija** [getsentry/sentry#76002]
The `group.score` column is likely no longer used. Audit the codebase to be sure we're only writing to it, and remove the code that does so and then [drop the column](https://develop.sentry.dev/development/database-migrations/#deleting-columns).

This will help us avoid any overflows in the future, and for customers that are experience this already, like in https://github.com/getsentry/sentry/pull/75625

**Comment by mrduncan** [comment]
Added to our core product rotational backlog, tentatively aiming to knock this out this quarter.
