### ISSUE TITLE
Add docs links to event processing errors

### ISSUE THREAD

**Issue by roggenkemper** [getsentry/sentry#76014]
UI shows a red indicator, that scrolls to the bottom of the page where more details exist.
But it's not actionable.

[Example event](https://sentry-sdks.sentry.io/issues/6033342930/events/latest/?project=6253052&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=latest-event&sort=date&statsPeriod=30d&stream_index=0)
![Image](https://github.com/user-attachments/assets/7c18eb02-1cdb-47d8-a708-d445402ab570)

![Image](https://github.com/user-attachments/assets/e8d71ca1-7165-437e-9ec0-a0ee96e91576)

**Comment by mrduncan** [comment]
I'm going to close this out in favor of #67028 which is an older version of the same problem.
