### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by tk-servicemax** [getsentry/sentry#76018]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Sentry Setting -> Setting -> Integration
2. Github -> Configuration -> Add Installation.
3. On the popup, I signed into Github and select the corresponding Github repo.
4. Admin team has approved the request.Screenshot to show Github has installed Sentry successfully.

![Image](https://github.com/user-attachments/assets/8c009750-70d5-4ad9-a3bd-f63f5e3e1489)

We have following this self help: https://sentry.zendesk.com/hc/en-us/articles/23148998617883-Github-integration-installation-out-of-sync

### Expected Result

Integration successful.

### Actual Result

Integration unsuccessful.

![Image](https://github.com/user-attachments/assets/cedad97b-5bac-460e-a55a-d147b26e1fa1)

In the Github Integration page, I still see Add Installation.

### Product Area

Settings - Integrations

### DSN

https://zincit.sentry.io/settings/integrations/github/

**Comment by tk-servicemax** [comment]
@getsentry-bot Any updates?

**Comment by noma4i** [comment]
Related to https://github.com/getsentry/sentry/issues/75788

**Comment by noma4i** [comment]
@aldy505 Hey! We have now a handful amount of the reports for the Github integration.

**Comment by tk-servicemax** [comment]
Thanks for linking.  What is the next step for this?  Is there an ETA on the resolution?

**Comment by noma4i** [comment]
@tk-servicemax I'm in the same boat. Waiting for the fix since June.

**Comment by aldy505** [comment]
> [@aldy505](https://github.com/aldy505) Hey! We have now a handful amount of the reports for the Github integration.

@noma4i I'm just a fellow contributor for self-hosted, and I only installed GitHub integration once on April 2024 (see [this commit](https://github.com/teknologi-umum/sentry/commit/483eab300bcf99ee83d2e4eb3fcb8f5afc3bd7be)). The best option is to wait for Sentry devs that handles third party integrations.

**Comment by tk-servicemax** [comment]
@noma4i @aldy505 Thanks for your reply.  We have recently onboarded Sentry.io and learning the ropes of Sentry.io support.  For an instance, I thought both of you were on the Sentry team.  

Can someone from Sentry team post here on the next step and ETA for this?

**Comment by leedongwei** [comment]
Hey, I'm going to get the team to investigate/replicate this next week.

**Comment by cathteng** [comment]
My initial hunch is that we require the person who installs the GitHub app to be the person who sets up the Sentry integration. Is that the case here?

**Comment by leshik** [comment]
@cathteng omitting the setup callback URL results in showing the Sentry page in the pop-up windows instead of the GitHub app page. Yes, the person who installed the GitHub app is also the person who set up Sentry integration.

**Comment by noma4i** [comment]
@tk-servicemax we were able to do the setup. @leshik can assist if you need. While the Sentry documentation may be somewhat misleading, it gets the job done.

**Comment by leedongwei** [comment]
@noma4i Can you share the wrong parts in our documentation so the team can update it?

**Comment by leshik** [comment]
@leedongwei the documentation should be clear that the GitHub app must be installed from within the Sentry interface, and that if it doesn't work with some weird symptoms, it should be uninstalled and then reinstalled within that same interface.

**Comment by tk-servicemax** [comment]
Resolved, thanks.
