### ISSUE TITLE
Spend Allocation - Root allocation is removed from start of new cycle and cannot create new one

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#76043]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Reproducable in 1 specific org - Link shared in Jira ticket

1. Go to spend allocations
2. Open up Transactions category - This is empty without audit log removal
3. Create Org-level allocation

### Expected Result

Spend allocation to be there as no-one deleted it and if it's gone: be able to create a new one which is impossible.

### Actual Result

As you can see someone change the root allocation for transactions on 13th of august
![Image](https://github.com/user-attachments/assets/b04da471-afaf-4f36-a0be-5b420ed50e1f)

And here is the proof that no-one has removed it after the 13th
![Image](https://github.com/user-attachments/assets/af1039f7-100e-4bf8-965c-16a37974c971)

But as you can see there is no allocation and creating a new one is also not possible
![Image](https://github.com/user-attachments/assets/ca4cdf68-d237-4390-90c1-a6a1a8b5dd03)

### Product Area

Settings - Spend Allocation

### Link

Link in Jira ticket

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2250) by [Unito](https://www.unito.io)

**Comment by isabellaenriquez** [comment]
Thanks for reporting this! This is a UI bug which our team is prioritizing a fix for. I'll update here when the bug has been fixed 🙏  Thank you for your patience!

**Comment by keradus** [comment]
I was raising this issue originally to @Angelodaniel .

After this ticket got closed, I got empty UI and 400 error on `https://us.sentry.io/api/0/organizations/XXX/spend-allocations/?billing_metric=transaction&cursor=&periods=1&target_type=Project&timestamp=1723675135.79`



![Image](https://github.com/user-attachments/assets/0d87016a-6aa4-4ce0-babd-f900027e3d7c)

**Comment by isabellaenriquez** [comment]
@keradus the ticket was closed when the fix was merged but at the time you commented it had not yet been deployed 😁 If you're still facing issues with this, definitely update here, otherwise, thanks again for raising the original issue! 🙌

**Comment by keradus** [comment]
now I see the issue fixed indeed, big thanks for that !

> the ticket was closed when the fix was merged but at the time you commented it had not yet been deployed 😁

haha, I would recommend to manage expectations and either close the ticket _after_ fix is deployed, or put a memo like (closing, planned for release in upcoming x hours)
