### ISSUE TITLE
Performance page showing same information on Frontend and Backend tabs

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#76044]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a project and set up any SDK to send performance data
2. Navigate to the performance page
3. Switch between the Frontend and Backend tabs 

### Expected Result

Each tab shows relevant information: frontend showing pageload and navigation transaction, and backend showing http.server and DB transactions. 

### Actual Result

The same information is shown on both. 

This is not an issue on most projects as SDKs instrument only frontend or only backed, but it is an issue on SDKs that instrument both (such as NextJS) or there are multiple projects selected. 

### Product Area

Performance

**Comment by bcoe** [comment]
Hello @rodolfoBee this is behaving as intended, the information that varies between the _Frontend_ and _Backend_ tab is the charts that we display, i.e., Web Vitals for Frontend, Query Information for Backend.

We understand this is a bit confusing, and have discussed moving away from a list of "Transactions" in the future, to a list of "Pages" for frontend applications, "Endpoints" for backend applications.

**Comment by bcoe** [comment]
@rodolfoBee we're chatting internally, and we'd like to change the intended behaviour, so that "Frontend" only shows frontend transactions, "Backend" only shows backend transactions.

I reopened so we can track.

**Comment by bcoe** [comment]
We now filter transactions to appropriate type in `Insights > Frontend`, `Insights > Backend`. We will be removing the old "Performance" tab in the near future.
