### ISSUE TITLE
[object Object] instead of DSN when creating a Node.js project

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#76052]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a new Node.js project
2. Visit the configure Node.js SDK page e.g: https://kismeow.sentry.io/projects/node-ah/getting-started/?product=performance-monitoring&product=profiling
3. Instead of the DSN of the project, [object Object] is visible:

![Image](https://github.com/user-attachments/assets/6fe50484-1c69-4aa5-8b16-1d37356c6bc8)

### Expected Result

the tutorial should show the actual dsn

### Actual Result

instead of the DSN it shows [object Object]

### Product Area

Settings - Projects

**Comment by CosmoAbdon** [comment]
Indeed, running last version of :nightly and the issue is also ocurring.
I can go to the project settings and get the dsn from there, but the snippet isnt working.

**Comment by CosmoAbdon** [comment]
Found and fixed the issue.

More details at the PR: #76153
