### ISSUE TITLE
Setting "Event Highlights" across all projects?

### ISSUE THREAD

**Issue by linsomniac** [getsentry/sentry#76075]
### Problem Statement

In an Issue, "Event Highlights", is it possible to set the defaults across projects?  It's possible to click "Edit" and modify it, or go down to Tags and click next to the tag to "Add to events highlights".  In the "Edit" view there's a "Use Defaults", so a way to specify the defaults across projects would be nice.

We used to use "host_name" and "server_name", which appeared at the top, but now would need to go in and modify 30 projects independently, which I'm going to go ahead and do.  But are we missing something?

### Solution Brainstorm

A way to speciffy the "default event highlights"?

### Product Area

Issues

**Comment by leeandher** [comment]
Hi there, thanks for writing in! Unfortunately at this time there is no way to set a default for the highlights for all of your projects. We do have different defaults depending on the platform (e.g. Mobile projects will have different presets than Web), but it is not user configurable.

The highlights are also editable from settings which might make it easier to make sweeping changes like this if you navigate to **Project Settings > Tags & Context** for each project. 

![Image](https://github.com/user-attachments/assets/7f600d75-f881-4ee7-bb45-5feea3cc0eaf)

At this time, we don't have plans to work on any changes to highlights like this, so I'm going to close this issue out. That said, the API being invoked is [documented here](https://docs.sentry.io/api/projects/update-a-project/), if you would like to put a script together to make bulk changes yourself. I'm working on [adding the fields to the public documentation](https://github.com/getsentry/sentry/pull/76184) to make things a bit easier.
