### ISSUE TITLE
Issue lists are not working

### ISSUE THREAD

**Issue by jkytomak** [getsentry/sentry#76162]
### Environment

EU SaaS (https://sentry.io/)

### Steps to Reproduce

Go to issues
No issues are visible even though tab tells (and I know) that there are 2 open:

![Image](https://github.com/user-attachments/assets/b3e536fa-b22f-4694-a2e5-c15b171ee84c)

If I then go to archived I can see some issues, but number drops from 51 to 37 after opening the tab:

![Image](https://github.com/user-attachments/assets/bde6a234-2106-4666-80b2-55bd5e07a58b)

This worked still yesterday.

### Expected Result

List shows issues according to filters

### Actual Result

Only some (old issues?) are visible

### Product Area

Issues

**Comment by jkytomak** [comment]
Works now again

**Comment by JoshFerge** [comment]
thank you for reporting! we were able to replicate we've rolled back our recent changes and @snigdhas is working on a fix.
