### ISSUE TITLE
Member cannot login with organization credentials

### ISSUE THREAD

**Issue by JoseanMeonez** [getsentry/sentry#76173]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

This problem happens in both login auth site:
https://sentry.io/auth/login/
https://grupo-platino.sentry.io/auth/login/grupo-platino/
 
1. After get invited to an organization, login with google and an organization mail example: "example@mycompany.com"
![Image](https://github.com/user-attachments/assets/e21bb1dc-da08-4742-ba2c-238341e6159c)

2. After select the account sentry returns the following error

![Image](https://github.com/user-attachments/assets/55cbe617-0f63-4967-b67c-5f103d63f96c)

### Expected Result

It must redirect to the following sentry issues page:

![Image](https://github.com/user-attachments/assets/63a9e3db-b7b5-4d3b-83e9-a92a1c6bdbe2)

 

### Actual Result

Sentry redirect too many times and crash after a few seconds:

![Image](https://github.com/user-attachments/assets/459258a3-80c2-4d60-88f9-ef684a963804)

### Product Area

Unknown

### Link

 https://grupo-platino.sentry.io/auth/login/grupo-platino/

### DSN

https://grupo-platino.sentry.io

**Comment by leedongwei** [comment]
Can you clear your cookies and see if the problem persists?

**Comment by JoseanMeonez** [comment]
Good afternoon I've already tried cleaning the cookies and the problem
persists.

**Comment by leedongwei** [comment]
Hi, I'm not able to replicate your issue. When accepting the invite, which options did you choose here: 



![Image](https://github.com/user-attachments/assets/b7d07229-97a5-4624-b8e4-6fac9ce43fe0)

**Comment by JoseanMeonez** [comment]
I accept the invitation.

I'd to say that the account already had an organization created before
received the invitation.

**Comment by leedongwei** [comment]
@JoseanMeonez Did you click "Create a new account" or "login using an existing account"?

**Comment by JoseanMeonez** [comment]
> [@JoseanMeonez](https://github.com/JoseanMeonez) Did you click "Create a new account" or "login using an existing account"?

I click in "login using an existing account"

**Comment by leedongwei** [comment]
Can you try this sequence:

1. Sign out of Sentry
2. Go to your email inbox and click the link to accept the invite
3. Select "Login using an existing account" and go through the login flow

**Comment by JoseanMeonez** [comment]
> Can you try this sequence:
> 
> 1. Sign out of Sentry
> 2. Go to your email inbox and click the link to accept the invite
> 3. Select "Login using an existing account" and go through the login flow

The problem is that when my teammate tries to send me the invitation now it doesn't leave him do it, It says i'm currently in the organization

**Comment by leedongwei** [comment]
I've looked into your account. Your email `j*****z@grupoplatino.**` is added as a secondary email in 2 other accounts: 

1. `d**@grupoplatino.**` which is the owner of the `grupo-platino` organization
2. `jc****@grupoplatino.**` which is an account that's already disabled.

> it doesn't leave him do it, It says i'm already in the organization

You need to remove your email from the owner account in (1) for it to work.
