### ISSUE TITLE
Alert Conditions Sidebar breaks when switching between Static and Percent thresholds if Alert was created with a Static threshold

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#76199]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create alert with Static Threshold 

![Image](https://github.com/user-attachments/assets/8f25c447-bfba-44ba-8991-bb58ba7b45d1)

2. Save Alert

3. Edit Alert to use Percent Change instead and save

![Image](https://github.com/user-attachments/assets/2872f5d6-5f52-4c0b-9b33-b068c5630d3c)

4. See sidebar is updated incorrectly

![Image](https://github.com/user-attachments/assets/3a159725-a0a4-4a43-be48-5eb805887a56)

[Link To Alert in screenshots in my org](https://francisorg.sentry.io/alerts/rules/details/270721/)

Creating an alert and saving it with a percent threshold initially works as expected.  You can switch back and forth between the two thresholds.

### Expected Result

Sidebar should show something similar to this when using percent thresholds -

![Image](https://github.com/user-attachments/assets/b2591847-4dad-45bf-82a6-162fb9931df6)

### Actual Result

Looks like it gets the inputted percentage added to a static threshold of 100 instead.

### Product Area

Alerts

**Comment by rachrwang** [comment]
Adding it to our backlog - thanks for flagging!

**Comment by mifu67** [comment]
Hi @Fwang36:

We've put out a change that fixes the bug. Let me know if the error still persists.
