### ISSUE TITLE
UF Backend: Limit feedback message size

### ISSUE THREAD

**Issue by aliu39** [getsentry/sentry#76298]
We discovered in [SENTRY-3B86](https://sentry.sentry.io/issues/5552524761/) feedback msgs above a certain size causes errors in the backend. This issue is in spam detection, but looking at a [sample trace](https://sentry.sentry.io/performance/trace/485ee9dcd75a4ec2a6c30ca85a016ac7/?project=1&source=performance_transaction_summary&stream_index=6&tab=events&timestamp=1723743503): this also causes errors writing to Kafka and Postgres (post process job).

**Brainstorm:**
A good start for what the limit should be is text-bison's max input token limit of **8192**. (AI model we're using for spam) https://ai.google.dev/palm_docs/palm#model-metadata.
We need to check the size limits for kafka (think it's ~10kb) and postgres too.

We'd prefer to set limits upstream. There are multiple creation sources (see https://develop.sentry.dev/application/feedback-architecture/), so let's define an option for this msg size limit.

The places to truncate msgs are:
- Relay: user_report and user_report_v2 envelopes (use `#annotated` on fields)
- Sentry backend: user report endpoint and crash report embed form

**Comment by billyvg** [comment]
We should make sure that front end displays a reasonable error msg as well

**Comment by aliu39** [comment]
We can also set max_length for the comments field of [userreport.py](https://github.com/getsentry/sentry/blob/65f94afa7b7d860bc54a3b703484d8b286a66722/src/sentry/models/userreport.py#L18-L18)
But not sure how this would affect the current data, if we need a migration, etc

**Comment by aliu39** [comment]
Relates to [SENTRY-3B86](https://sentry.sentry.io/issues/5552524761/)
