### ISSUE TITLE
Arbitrary grouping instructions

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#763]
We should add the ability for some kind of arbitrary grouping rules.

e.g. "Group all events of X together"

This could be like "Where the [select item] is [input]"

Item might be like "Exception Type", and potentially input could be a regular expression.

**Comment by mattrobenolt** [comment]
@dcramer was this superseded by fingerprinting? Or was this something different? Sounds like you wanted to expose something in the UI to do this.

**Comment by dcramer** [comment]
This is about rules on the server but no promises we actually do it so closing
