### ISSUE TITLE
Time series graphs no longer show in the user's selected timezone

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#7630]
Graphs are showing the timestamps in the tooltip on the system timezone, rather than the user's configured timezone (in my case, graphs are displaying in PDT rather than UTC.)

**Comment by MaxBittker** [comment]
https://github.com/getsentry/sentry/issues/2032

**Comment by tkaemming** [comment]
Here too:

![screenshot 2018-03-14 16 41 14](https://user-images.githubusercontent.com/65315/37436719-8978a014-27a6-11e8-9cb0-00cd739f9918.png)
