### ISSUE TITLE
Ability add custom filters to dashboards

### ISSUE THREAD

**Issue by mortargrind** [getsentry/sentry#76317]
### Problem Statement

At the moment there are 4 built-in filters in Dashboards:
- Project name
- Environment
- Date
- Releases

This is pretty limited for us since we have highly configurable applications that is deployed to under different configurations (such as countries or regions etc). 

We would like to be able to create custom filters based on existing built-in or custom data (tags or contextual data) for dashboards so instead of duplicating the same dashboard for multiple different breakpoint combinations (ie. Finland - iOS users etc.), a user can just set certain filter values to get an overview of things quickly.

### Solution Brainstorm

Having the ability to add custom filters to dashboards also mean we should be able to refer each filters' value in our widgets in the dashboard (Imagine having a query like `event.type: error AND geo.country_code:$country_filter.value`). There might be some widgets where some filter values do not get applied because of the nature of those widgets' query and it most probably would be up to developer to decide how exactly the value of the filter would be incorporated into a widget.

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2353) by [Unito](https://www.unito.io)

**Comment by ale-cota** [comment]
Hi @mortargrind,

Thanks for submitting this feedback. We already have a separate [issue](https://github.com/getsentry/sentry/issues/55036) for adding custom tags as filters for dashboards. This feature is currently on our backlog, but we might be able to look into this over the next few weeks. Could you please subscribe to the other issue, as we'll be posting updates there? Thanks again.

**Comment by wmak** [comment]
https://github.com/getsentry/sentry/issues/55036 is tracking this issue, closing this in favour of that
