### ISSUE TITLE
Error when grouping metrics by tag with dashes "-".

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#76319]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Submit a metric with a tag that includes a dash in the key value (name). For example:
```
Sentry.metrics.increment("websiteTest", 1, {
  tags: {"tag-name": "dashedTag"},
});
```

### Expected Result

Being able to group results using this tag. 

From the [documentation](https://docs.sentry.io/product/explore/metrics/#supported-characters), the supported characters are:
> Metric Tag Key: All word characters including _, -, ., /. Any unsupported characters will be removed from the tag key.

### Actual Result

Error in the UI:

![Image](https://github.com/user-attachments/assets/c4457e18-75f5-4a95-8b0f-5ae64420160f)

### Product Area

DDM

### Link

https://helpandprovid.sentry.io/metrics/?interval=1h&project=5722597&statsPeriod=7d&widgets=%5B%7B%22mri%22%3A%22c%3Acustom%2FwebsiteTest%40none%22%2C%22aggregation%22%3A%22sum%22%2C%22query%22%3A%22%22%2C%22groupBy%22%3A%5B%22tag-name%22%5D%2C%22powerUserMode%22%3Afalse%2C%22type%22%3A1%2C%22id%22%3A0%2C%22displayType%22%3A%22line%22%2C%22sort%22%3A%7B%22order%22%3A%22asc%22%7D%2C%22isHidden%22%3Afalse%2C%22overlays%22%3A%5B%22samples%22%5D%7D%5D

**Comment by matejminar** [comment]
After careful consideration, we are ending the beta program and will retire the current Metrics solution on October 7th. Stay tuned for updates and [read the FAQs](https://sentry.zendesk.com/hc/en-us/articles/26369339769883-Metrics-Beta-Coming-to-an-End) for more details.
