### ISSUE TITLE
Give the ability to turn off Missing instrumentation spans since there is nothing to instrument in many cases

### ISSUE THREAD

**Issue by aellett** [getsentry/sentry#76368]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I've got a scoped transaction that I started manually. While that transaction is running, I start a span every time 1) there is a network request and 2) the user navigates to a different feature within the app.

As a visualization of this, you could imagine that I've got one long session. At any point within that session, some given feature should be running, which means that a span should be running underneath that session.

Also at any point during that session, a network request might be made, which would result in a span for that request. These request spans would be unevenly spaced out throughout a session. 

### Expected Result

Because the user navigates from one feature to another, I would expect my "feature" spans to end up exactly next to each other and not really leave any gaps for missing instrumentation.

The only time a feature span ends is when either 1) the session ends or 2) the user navigates to a different feature (which starts a new span).

### Actual Result

When I look at a trace of a session where a user has moved between a couple features, I see large blocks of spans labeled "Missing instrumentation." It feels like instrumentation is not missing, since I've got both a transaction (for the session) and a span (for the feature) running at that point.

In the attached screenshot, the session transaction starts, then a feature span starts, and while both of those are active, I see two blocks for "Missing instrumentation."

![Image](https://github.com/user-attachments/assets/d34b9c48-14fb-4988-bad5-b5595f6f01d2)

It's not such a huge problem in this situation, but I've seen situations where the user stays in one feature and makes many network requests, and in that case I get an explosion of quite a lot of "Missing instrumentation" blocks, which makes it harder to view the waterfall and track what I'm looking at.

### Product Area

Performance

**Comment by Dhrumil-Sentry** [comment]
@aellett - Currently we show missing instrumentation spans if there are gaps of over 100ms between span waterfall. There is no way for a user to turn this default behavior off.

But we'll take this feedback under active consideration 🙏
