### ISSUE TITLE
Sourcemap not linking to events even though matched via debug ID

### ISSUE THREAD

**Issue by MattPurland** [getsentry/sentry#76376]
### Self-Hosted Version

24.6.0

### CPU Architecture

x86_64

### Docker Version

26.1.2

### Docker Compose Version

2.27.0

### Steps to Reproduce

Note: deploying to sentry.io works as expected.

Events are unable to display unminified code using an uploaded sourcemap via either the Debug ID or Release method, although the event says there's a successfully uploaded sourcemap when using the Debug ID, but it's still unable to show the original javascript source in the stack trace.

Example:
![Image](https://github.com/user-attachments/assets/b90749bd-214f-4b43-89c8-8571668f4b86)

Debug ID
![Image](https://github.com/user-attachments/assets/8628621b-7c29-4a79-81af-77e2c8fb76a2)

Release (I can see there's a path issue here, but I'm unsure how to fix it)
![Image](https://github.com/user-attachments/assets/95db00a5-08c4-4674-8f90-34e78e905713)

JS and Map in the release artefacts:
![Image](https://github.com/user-attachments/assets/b1b2ef86-dc3d-4b5d-a28d-7667ba864382)

There are no errors in the internal project and I'm unsure where to go from here.

Any ideas?

### Expected Result

The event's stack trace should display the original javascript source via a sourcemap in the release artefacts

### Actual Result

Displays the error as if there is no uploaded sourcemap

**Comment by MattPurland** [comment]
> Sorry for the delayed response. Those two paths that you scribbled over with blue, they're the same? Also wondering if that dist value thing is relevant or not.

The scribbled out bit is just the domain, and yes they're the same. Having the dist value or not makes no difference

**Comment by loewenheim** [comment]
Hi, would you mind running `symbolicli` on your event? It's a CLI utility that runs the same symbolication steps that would happen on the server. You use it like this:
```
symbolicli --url <YOUR_SENTRY_URL> -o <ORG_SLUG> -p <PROJECT_SLUG> --auth-token <AUTH_TOKEN> --log-level trace <EVENT_ID>
```
And post the logs, or email them to me at sebastian.zivota@sentry.io? A binary can be found at https://github.com/getsentry/symbolicator/releases.

**Comment by MattPurland** [comment]
> Hi, would you mind running `symbolicli` on your event? It's a CLI utility that runs the same symbolication steps that would happen on the server. You use it like this:
> 
> ```
> symbolicli --url <YOUR_SENTRY_URL> -o <ORG_SLUG> -p <PROJECT_SLUG> --auth-token <AUTH_TOKEN> --log-level trace <EVENT_ID>
> ```
> 
> And post the logs, or email them to me at [sebastian.zivota@sentry.io](mailto:sebastian.zivota@sentry.io)? A binary can be found at https://github.com/getsentry/symbolicator/releases.

Thanks for your help with this.

I'm probably doing something wrong, but I'm getting "Error: Response from server: Forbidden". The auth token is definitely being used against the server as the "last accessed" is being updated.

The URL format looks identical to the API calls in the Sentry dashboard. Any ideas?

**Comment by loewenheim** [comment]
Does it work if you `curl` to the server (`curl -H "Authorization: Bearer <AUTH_TOKEN>" <YOUR_SENTRY_URL>`)?

**Comment by MattPurland** [comment]
> Does it work if you `curl` to the server (`curl -H "Authorization: Bearer <AUTH_TOKEN>" <YOUR_SENTRY_URL>`)?

**Comment by loewenheim** [comment]
You mean you run `symbolicli` on the server? You should run it from your local machine, I don't know if that would cause the permission issue you're encountering though.

**Comment by MattPurland** [comment]
> You mean you run `symbolicli` on the server? You should run it from your local machine, I don't know if that would cause the permission issue you're encountering though.

I'm unable to run it from my local machine as I'm in a local authority environment (restricted). But I just tried another machine (where I can run it) and I get the same response

**Comment by loewenheim** [comment]
Does downloading the file work with `curl`?

**Comment by MattPurland** [comment]
> Does downloading the file work with `curl`?

Unfortunately not

{"detail":"You do not have permission to perform this action."}

**Comment by MattPurland** [comment]
I've fixed it!

My problem was I'd set the system.internal-url-prefix to that of system.url-prefix. So it *should* be:

```
# The URL prefix in which Sentry is accessible
system.url-prefix: 'https://sentry.my-domain.com'
system.internal-url-prefix: 'http://web:9000' # This is where I went wrong, I'd set it to match the above url-prefix
```

Not sure why I checked, but I had a feeling I'd done something wrong in the config.yml

Hopefully that helps others out

**Comment by loewenheim** [comment]
Glad to hear your problem is resolved!
