### ISSUE TITLE
Preview for .txt crash reports

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#76381]
### Problem Statement

Currently, .txt crash report attachments don't have a preview, it would be nice to preview them without having to download them.

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2259) by [Unito](https://www.unito.io)

**Comment by mrduncan** [comment]
We do support previews if the mime type is `text/plain`: [static/app/components/events/eventAttachments.tsx](https://github.com/getsentry/sentry/blob/master/static/app/components/events/eventAttachments.tsx#L41) however we don't show that anywhere in the UI to users.

Adding a few more in #76391 and will follow up in the Jira ticket for more specific advice for this user.

**Comment by mrduncan** [comment]
Going to close this given it's age and the resolution now present in https://github.com/getsentry/sentry-native/issues/1031.
