### ISSUE TITLE
Project selection doesn't immediately apply to errors

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#76387]
Came up through [zendesk](https://sentry.zendesk.com/agent/tickets/129984):

> The past few months, Sentry seems to have a lot of weird caching issues, where I click on “errors” in a particular project, and then in the list view, its showing errors from other projects, then when I hit Enter again on the search criteria, it shows the right lists. Seems to be more of this happening all around the app and it didn’t used to happen before. Just seems like what used to work flawlessly is a little buggy now...

It also came up on Twitter recently: https://x.com/949630562091917312/status/1824872929622122809

> Please this to the roadmap:
> Fix faulty caching of issue list when switching between projects. 
> It’s annoying as hell. You gotta reload the entire site to get the correct issues for the project switched to.

**Comment by Fwang36** [comment]
[Link to my org where you can test](https://francisorg.sentry.io/projects/)

Steps to Repro - 

1 . Start from the projects view and click into Errors below Project Name


![Image](https://github.com/user-attachments/assets/e94790d9-3f43-44bd-ba32-625f561b0601)


2. Hit Back in browser.

3. Click into Errors for another project.

![Image](https://github.com/user-attachments/assets/1ac7a2f8-f86b-4577-a98a-e2dce7b629dd)

4. Be brought into issues page where the issues from the last project are stacked on top the new one even though the project selector only has 1 project selected.

![Image](https://github.com/user-attachments/assets/82edbfd2-7275-4b6f-8b4a-e082df177613)

**Comment by mrduncan** [comment]
Thanks for the repro! We'll take a look at this next week.

**Comment by scttcper** [comment]
This should be fixed with the rollout of the new Issue Views https://sentry-docs-14uoi4943.sentry.dev/product/issues/issue-views/ Please let me know if that is not the case
