### ISSUE TITLE
GitHub Education Pack Can't Be Claimed: redirect_uri is not associated with the application

### ISSUE THREAD

**Issue by souredoutlook** [getsentry/sentry#76399]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Tracking public request here:

https://x.com/jaywyawhare/status/1825598013496242652

Internal escalation first started tracking available at request

### Expected Result

GitHub education pack linking works as expected

### Actual Result

redirect_uri is not configured correctly

### Product Area

Unknown

**Comment by leedongwei** [comment]
We've schedule an engineer to investigate on Aug 26.

**Comment by milumine** [comment]
> We've schedule an engineer to investigate on Aug 26.

Hello, what's the status of the fix? I've been waiting for 4 days now 🙂

**Comment by durvs** [comment]
I'm having same problem.

**Comment by dashed** [comment]
@durvs This should be fixed now. Can you please try again?

**Comment by jaywyawhare** [comment]
Hey i havn't heard back after sending the screenshot, please help me to fix it as its a blocker for me now.

**Comment by rudolfgrauberger** [comment]
> [@durvs](https://github.com/durvs) This should be fixed now. Can you please try again?

It works. Thank you very much
