### ISSUE TITLE
Microsoft Teams Integration Problem

### ISSUE THREAD

**Issue by laalamrajesh** [getsentry/sentry#76409]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Not receiving notifications to team from Aug 19, 12 PM IST time. 

### Expected Result

We should receive sentry issue details in microsoft teams

### Actual Result

Not receiving sentry message to teams

### Product Area

Unknown

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2260) by [Unito](https://www.unito.io)

**Comment by dalnoki** [comment]
Hi Team, I have another customer who reported that they don't receive messages in Teams since Friday, I added the details to the Jira ticket.

**Comment by gbaldera** [comment]
Same for us, Notifications stopped working this week

**Comment by youssef-tec** [comment]
Same for us. We re-installing the teams integration app but that seems to be broken as well as we no longer receive the welcome message.

**Comment by nickittynack** [comment]
This is impacting our organisation too, no alerts being sent through into teams

**Comment by laalamrajesh** [comment]
@getsantry

MS Teams retired office 365 connectors. Issue might be due to that. I have attached ref below. please check and resolve this issue.

https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/

**Comment by nickittynack** [comment]
That was my suspicion too but they already kicked out their timeline (the edit top of the link, quote below). Our Jira connectors to teams are also having problems so your hypothesis may be true. 

> All existing connectors within all clouds will continue to work until December 2025, however using connectors beyond December 31, 2024 will require additional action.
> Starting August 15th, 2024 all new creations should be created using the Workflows app in Microsoft Teams

**Comment by klavdijS** [comment]
We are also having the same problems, notifications stopped working 1 daya ago

**Comment by iamrajjoshi** [comment]
Hello everyone! We believe we have a fix in, could you please go ahead and try again?

**Comment by natenatters** [comment]
> Hello everyone - Thank you for raising this issue and your patience. We believe we have a fix in, could you please go ahead and try again?

Yes @iamrajjoshi , this is working for us.

To confirm:
* We are getting alerts sent to our Teams channel
* We can create new alerts
* We can update alerts

Thanks for the update!

**Comment by gbaldera** [comment]
> Hello everyone - Thank you for raising this issue and your patience. We believe we have a fix in, could you please go ahead and try again?

Thanks! I have sent a test notification and now it is working.

Thanks again for the quick remediation.

**Comment by nickittynack** [comment]
Confirmed working again for us too. Appreciate you!

**Comment by leedongwei** [comment]
Sorry for the service interruption, I'm glad that it's working now. 

Thank you for bringing this to our attention and bring patient while @iamrajjoshi was investigating it.
