### ISSUE TITLE
AMQP import error

### ISSUE THREAD

**Issue by DamianLion** [getsentry/sentry#7643]
ref: https://github.com/getsentry/docker-sentry/issues/125

## Reporting Bugs

Current setup issues. Can someone assist? Did somebody else ran into this issue

When reporting bugs, include details about your configuration, such as:

- The version of Sentry you're using
onbuild (8.22)
- Whether you're using Docker or another installation method
Docker
- Include a stacktrace or other logs when relevant
see https://github.com/getsentry/docker-sentry/issues/125

**Comment by dcramer** [comment]
https://sentry.io/support/
