### ISSUE TITLE
No event id or timestamp on the header of a trace

### ISSUE THREAD

**Issue by Dhrumil-Sentry** [getsentry/sentry#76457]
Please see more details [here](https://www.notion.so/sentry/No-event-id-or-timestamp-on-the-header-of-a-trace-c37681ebdd2d473e9a17250e70e417dc?pvs=4)

We need to include the timestamp of the trace, span count and the id in the header. We should get Vasudha's help for this

**Comment by alexjillard** [comment]
This has been resolved with recent design changes.
