### ISSUE TITLE
Single Developer Slack integration

### ISSUE THREAD

**Issue by talnmizrachi** [getsentry/sentry#76487]
### Problem Statement

I would love having the paid option to have a 3rd party integration for a single user (instead of paying for a seat on the team plan)

### Product Area

Unknown

**Comment by leedongwei** [comment]
Hi @talnmizrachi. Our billing plans are usage-based, not seat-based. When you upgrade to a Team plan, you get more errors/spans/attachments/etc

**Comment by brianthi** [comment]
Hi @talnmizrachi, sorry to say but I don't see us adding the ability to configure third party integrations on our free tier any time soon. Closing this issue.
