### ISSUE TITLE
Cannot load Subscription page

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#76526]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

please see the details in the attached Jira ticket for more details

### Expected Result

the subscription page should load

### Actual Result

![Image](https://github.com/user-attachments/assets/c70cd15e-037e-4de2-a7ca-099383b5cd49)

### Product Area

Settings - Subscription

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2266) by [Unito](https://www.unito.io)

**Comment by isabellaenriquez** [comment]
Thanks for reporting, I'm currently looking into this bug, will update here when I find the cause!

**Comment by isabellaenriquez** [comment]
@dalnoki I've identified and fixed the issue, let me know if you're still seeing this! Long story short, there was some missing data in the API response for this specific subset of customers.
