### ISSUE TITLE
Improvements to Jira issue creation

### ISSUE THREAD

**Issue by pupeno** [getsentry/sentry#7664]
Hello guys,

I love creating Jira issues from Sentry and I'm doing it a lot. There's a few improvements that would help make my workflow, and probably others, smoother. This issue should probably be broken down into several different ones as you see fit.

When creating a new issue, it would be great if you try to identify the report, as the current Sentry user, and auto-fill it. Maybe from previous reports or from the email/name of the user.

Also, it'd be great if you improved the management of versions. You know in which version an exception happened, so, you could try to match it to the appropriate set of versions provided by Jira. Another very useful feature would be to clearly delineate released from to-be-released versions, similarly to how Jira does it. Auto-populating the fixed version with the last one used might be a good idea to.

On the link to Jira issue, it would be nice if you listed, as a sort of short cut, other Sentry exceptions and the issues they were linked to. I find that something almost every time I'm linking to an issue is to one that I just created minutes ago from Sentry for another exception (in cases in which the exceptions look different so Sentry doesn't group them).

**Comment by benvinegar** [comment]
Hey @pupeno – thanks for the feedback, sorry it took us so long to reply.

We're working on a couple of Jira enhancements now. I'd encourage you to check back after they're live (might be a month or two).

**Comment by pupeno** [comment]
Awesome! Looking forward to that.

**Comment by nesl247** [comment]
Is there any update regarding the auto-fill of the reporter?

**Comment by aleksandrmetik** [comment]
Any updates? Thanks

**Comment by BYK** [comment]
The auto-fill issue should be resolved via https://github.com/getsentry/sentry/pull/21580.

For the rest, I don't think we'll be working on them any time soon so closing the issue due to staleness.

**Comment by saifelse** [comment]
> Is there any update regarding the auto-fill of the reporter?

@nesl247 : I filed an issue tracking the reporter auto-fill here #21588 and put up a PR for it: #21589
