### ISSUE TITLE
Issue Details won't Load

### ISSUE THREAD

**Issue by scefali** [getsentry/sentry#76651]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open incognito window
2. Login
3. Visit https://pioneer-dev-ai.sentry.io/issues/5468083795/
4. Notice spinner is stuck

### Expected Result

Should see issue details load

### Actual Result

Issue details not loading. I don't even see a request being made to the issues endpoint. I think something with `useQuery` is messed up because when I was developing locally, I had a similar problem. It seems like `queryFn` which is an input to `useQuery` isn't ever getting called so it never fetches the data from the sever.

### Product Area

Issues

### Link

https://pioneer-dev-ai.sentry.io/issues/5468083795/

**Comment by scefali** [comment]
@malwilley tagging you because you're the king of `useQuery` haha

**Comment by leeandher** [comment]
Hey @scefali! Using the link you provided, I didn't have any loading problems with the issue, could this be related to some incorrect state in your browser? Is the problem just with this one issue, or are you finding it across the product? 

I'm not able to find anything in Sentry about the loading times increasing or anything for your organization.

**Comment by scttcper** [comment]
@scefali you could try enabling the react query debug tools and see what it's saying https://github.com/getsentry/sentry/blob/master/static/app/main.tsx#L58-L60

**Comment by scefali** [comment]
@scttcper @leeandher Havne't tried messing with the debug setting locally but I tried in Safari and it works fine, so there does seem to be some browser interaction going on here.

**Comment by scefali** [comment]
@scttcper This is what I see, data is `null` for the endpoint loading the issue

![Image](https://github.com/user-attachments/assets/39088fbb-2fb3-414c-9c8f-3981e142b180)

**Comment by leeandher** [comment]
Is that a local issue, its not just happening on SaaS? I'm just guessing because the `group_id` in the screenshot is `14`. If so I'm guessing it could be a browser extension, or maybe some add-on to the browser causing this issue? 

I don't think there are any failure states that result in no data being sent back to the requestor. If we handle the failure, it's a `{detail: ...}` blob, and if we don't it's still an `InternalError` payload.

**Comment by scefali** [comment]
@leeandher All of the sudden, issues started to load for me in prod. Hopefully it will work for me locally, but I can just use Safari locally if it continues to happen. Closing the issue now.
