### ISSUE TITLE
Keep environment filters when switching between projects

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#76663]
### Problem Statement

Customer request: When filtering on environment for a given backend (let's say to see only production alerts for Python which is a typical usecase across all your clients I guess), and then switching to another project (so see frontend issues or PHP backend ones), the filter on environment is lost, which is annoying. Would really appreciate if there was some kind of persistence when changing projects.

### Product Area

Issues

**Comment by leeandher** [comment]
Thanks for the feedback, unfortunately this is not something we'll likely build out. Environments are uniquely created for each project. For different projects, the 'production' environment is representing different items in Sentry, they simply share a matching name. The name string is too tenuous a connection to persist across projects and will likely cause issues if projects don't standardize (e.g. `prod` vs `production`).

An alternative which could be investigated, and that I'll share with the team is to persist the last selected environment state when switching between projects. Example:

- Select Project 1 -> Change 'All Envs' to 'production'
- Select Project 2 -> Change 'All Envs' to 'prod'
- Back to Project 1 -> Current Environment is 'production'
- Back to Project 2 -> Current Environment is 'prod' 

We'd have to figure out the behaviour around selecting multiple project, but it could help with this issue. This is just a proposal I'll share with the team, but this likely won't be prioritized immediately.
