### ISSUE TITLE
Unable To Filter Custom breadcrumbs in Replay's Console Tab

### ISSUE THREAD

**Issue by FocussedFlyer3** [getsentry/sentry#76717]
### Environment
SaaS (https://sentry.io/)

### Steps to Reproduce
1. Set up some custom breadcrumbs in the SDK
2. Create an issue with an associated Replay
3. Check out the breadcrumbs on reply in console tab
4. Unable to filter and view only custom breadcrumbs, changing Log Level filtering, doesn't show the custom breadcrumbs

### Expected Result
The breadcrumbs in the console tab should be allowed to be filtered using the Log Level dropdown for easy filtering through all the logs in the console

### Actual Result
Aside from searching, there is no other way to filter, changing Log Level filtering, doesn't show the custom breadcrumbs either

![Image](https://github.com/user-attachments/assets/91379984-31f1-4061-9be2-a6094470cfc2)

### Product Area

Replays

**Comment by bruno-garcia** [comment]
This is related to a plan we have in adding Sentry custom breadcrumbs (calls to `Sentry.addBreadcrumb`) under the `Breadcrumbs` tab in Replay as opposed to `Console`.

* https://github.com/getsentry/sentry/issues/71504
* https://github.com/getsentry/sentry/issues/69230

**Comment by c298lee** [comment]
Custom breadcrumbs have now moved from the Console tab to the Breadcrumbs tab with https://github.com/getsentry/sentry/pull/77962. You can now filter for custom breadcrumbs in the breadcrumbs dropdown with `Custom`
