### ISSUE TITLE
User report endpoint is not creating feedback

### ISSUE THREAD

**Issue by aliu39** [getsentry/sentry#76730]
Resolution: endpoint is working as expected, customer was associating missing events to the reports.

____

Bug report and steps to repro here: https://github.com/getsentry/sentry/discussions/60134#discussioncomment-10392232
Reporter @JanMikes

Needed info:
- how old is the associated event? Finding a link to it would be best. 
    - ~~**Feedback won't be created if the event is older than 1mo** (and going forward, 1 day older than the report).~~
    - **Feedback won't be created if the event doesn't exist in the same project, or is older than 30min from time of submission**
- were reports previously created in the project with the same event ID? Project+Event is unique in our DB model, so **you can only create 1 report from each event**
    - this requirement is not enforced for 5min after the first submission

**Comment by aliu39** [comment]
cc @bruno-garcia

**Comment by JanMikes** [comment]
> were reports previously created in the project with the same event ID? Project+Event is unique in our DB model, so you can only create 1 report from each event

No, but the eventId is random and if the event is not created via this call, then there will be no event with this id at all.

I understand this might not be the correct way to create feedbacks, but it worked in the past and stopped working while API keeps responding with 200 status code - if the response was at least 400 or 404 all would be okay.

This way i am afraid we lost few months of feedback responses.

**Comment by aliu39** [comment]
> This way i am afraid we lost few months of feedback responses.

We still store the user's submitted comments, email, etc and you should be able to access them with GETs on the same endpoint. Unfortunately if the error events don't exist, these won't show up in the UI.

**Comment by JanMikes** [comment]
I will adapt the integration, that is no problem. 

Though i am unable to retrieve the missed feedbacks via API either:
```
curl --location 'https://sentry.io/api/0/projects/speedpuzzling/web/user-feedback/' \
--header 'Authorization: Bearer <token>' \
--data ''
```

Response 200 OK: `[]`

**Comment by aliu39** [comment]
Looks like this is a filter in the endpoint -- reports without an existing event are not returned. https://github.com/getsentry/sentry/blob/5522b80a4dba11703425ba400b04abab8cbbd18d/src/sentry/api/endpoints/project_user_reports.py#L64-L64

On tuesday I can check with the team to see if we can get this data for you.

**Comment by JanMikes** [comment]
That would be very nice, thank you.

**Comment by bruno-garcia** [comment]
> Looks like this is a filter in the endpoint -- reports without an existing event are not returned.

This was also the original behavior. If the event didn't make it in, the feedbacks don't show up anywhere

**Comment by aliu39** [comment]
@JanMikes unfortunately engineering teams don't have the authorization to access your data. Could you try reaching out to a support team and/or filing a new ticket?

**Comment by JanMikes** [comment]
Sure thing. Thank you very much!
