### ISSUE TITLE
Dashboard - ID column link stops working when opening Widget in Full screen mode

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#76731]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

- Create widget
- Select Column "Id" 
- Save widget
- Open widget in full mode
- See that Id column is not clickable

### Expected Result

Id column needs to be clickable

### Actual Result

You can see that in the background the columns are clickable, but in full screen mode not.

![Image](https://github.com/user-attachments/assets/4e4eb98b-1871-4bed-8d6b-a9cdb211cd6c)

### Product Area

Dashboards

### Link

https://demo.sentry.io/dashboard/104975/widget/720694/?project=5808623&query=%5Bobject+Object%5D&statsPeriod=30d

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2269) by [Unito](https://www.unito.io)

**Comment by gggritso** [comment]
Thanks for raising this! Adding to our backlog!
