### ISSUE TITLE
Organization-level Setting to Create/Edit Project inbound filters

### ISSUE THREAD

**Issue by byboscobarros** [getsentry/sentry#76736]
### Problem Statement

We need that users with "members" role be able to create or edit inbound filters to your projects, today only "Team Admin" is able to do it.

### Solution Brainstorm

We'll have a organization-level setting for users with owners/managers roles to enable or disable the posibility of users with role "members" create or edit inbound filters.

### Product Area

Settings - Projects

**Comment by leedongwei** [comment]
Can you promote those members to Team Admin? I'm very hesitant to provide members with more write-access on configurations because it'll complicate the product as a whole.

**Comment by mrduncan** [comment]
I'm going to close this as I don't anticipate this being prioritized in the current state but please add additional details if we're missing something here.
