### ISSUE TITLE
Event deduplication occurs after group aggregate details are created/updated

### ISSUE THREAD

**Issue by tkaemming** [getsentry/sentry#7677]
`_save_aggregate` is called:

https://github.com/getsentry/sentry/blob/2213aa200f2cb2a164d2296753966cbe19ae1670/src/sentry/event_manager.py#L673-L675

… prior to unique constraint enforcement on `(project_id, event_id)` (event deduplication):

https://github.com/getsentry/sentry/blob/2213aa200f2cb2a164d2296753966cbe19ae1670/src/sentry/event_manager.py#L701-L739

This causes the group aggregates to get updated with consideration to the duplicate event ID, erroneously incrementing counters or modifying first and last seen aggregate data. If the duplicate event IDs are also sent with different fingerprints or different event details that cause differentiating hashes, this can lead to a group being created that contains no events or additional aggregate data (tags, TSDB, etc) beyond the data that is updated in `_save_aggregate`.

**Comment by mattrobenolt** [comment]
As a tangential note: we have no way to even report this as an error to the customer to say "Hey, you're sending dupe IDs." We just log to ourselves.

**Comment by BYK** [comment]
I think this can be closed as #7682 addressed this sufficiently. I'm guessing the race condition mentioned is captured in #5085 but feel free to correct me @tkaemming
