### ISSUE TITLE
Brainstorming how to link stats docs to chart reasons

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry#76791]
On the stats page, the UI displays the reason why an event was not accepted by Sentry. To understand a reason, users can refer to the stats document, which provides a list of all reasons and their explanations.

We want to brainstorm ways to link the stats docs directly to the chart reasons, allowing users to click on a link from the stats page and go straight to the specific reason. Ideally, it would be even better to integrate the documentation and display the explanation directly in the UI, though that may be more complex.

**Comment by Jesse-Box** [comment]
![Image](https://github.com/user-attachments/assets/bc9f18e2-0935-4faf-9c1f-7242e038e4fe)

Is the assumption that these tooltips aren't fulfilling the needs of the user?

**Comment by Jesse-Box** [comment]
@matejminar @priscilawebdev 

### Solution

- Place a (?) tooltip next to the chart title “Project Stats”, with the following text; “You can find more information about each category in our [docs](https://docs.sentry.io/product/stats/).
- Make sure the “Project Stats” title is persistent no matter the time range
- For the tooltips visible for each category card, we can append the tooltip text with the following; “… For more information, read our [docs](https://docs.sentry.io/product/stats/).
