### ISSUE TITLE
Uptime monitoring breaks alert sorting

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#76798]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Have the Early Adopters option toggled on
2. Have an automatically created uptime alert rule
3. Go to that project's alert rules and sort the list my title

### Expected Result

The alerts are sorted alphabetically by title.

### Actual Result

We get the error message "There was an error loading alerts", and a 500 error in the network tab.

Additionally, the following AssertionError is created in Sentry's Sentry: https://sentry.sentry.io/issues/5719365046/events/cba34a2892fd40c288d54bd6aaa0cf41/?project=1 

As a temporary workaround, disabling the Early Adopters option fixes the issue but disables the feature.

### Product Area

Alerts

**Comment by leedongwei** [comment]
Getting the Uptime team to take a closer look

**Comment by allanlewis** [comment]
Hi - I reported this bug and @InterstellarStella raised this issue in response. Thanks for the quick fix, much appreciated!
