### ISSUE TITLE
Stack frame doesn't have Debug IDs

### ISSUE THREAD

**Issue by richhapal** [getsentry/sentry#76810]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Hi sentry Team, I'm facing issue **Stack frame doesn't have Debug IDs**. 

When I running ` sentry-cli sourcemaps inject --org myOrg --project projectName ./build && sentry-cli sourcemaps upload --org myOrg --project projectName ./build` , it working fine for `Source Map Debug ID Injection Report` but you can see in images, it not generating Release and dist automatically.

![Image](https://github.com/user-attachments/assets/49b10c5b-a909-49e4-b56b-0d53ac1412b3)

The debugId injecting perfectly.

On sentry dashboard 
**Associated Releases -> No releases associated with this bundle**

![Image](https://github.com/user-attachments/assets/9cec9290-22dd-41fd-8270-f6071b04f404)

Source code is uploading perfectly.

![Image](https://github.com/user-attachments/assets/aa524464-088a-4b34-8744-f6175f90fe9e)

### How are you getting stuck?

I'm not able to see error code.

### Where in the product are you?

Issues - Source Maps

### DSN

https://63ed691b2737c6fd97c017c3c79b4dc7@o1243174.ingest.us.sentry.io/4506735425290240

**Comment by loewenheim** [comment]
Hi, do you have an example of an event that doesn't get unminified correctly?

**Comment by richhapal** [comment]
Hi @loewenheim I have this event id `db17a4a4afb7400c985a237c53a0fe7a` which show **Unminify Code** button

**Comment by richhapal** [comment]
Hi @loewenheim Please check this one 
![Image](https://github.com/user-attachments/assets/f1568d82-b85d-4424-a3e9-b2a9eb78cc25)

**Comment by lforst** [comment]
@richhapal I am gonna take this over. Looks like that issue is from localhost. Can you do a production build and test it there? Also it seems like it worked for this event https://physics-wallah-nn.sentry.io/issues/5787367611/events/eadedaccf9c64da2854712403079b246/ Did you figure it out?

**Comment by richhapal** [comment]
Hi @lforst it's working fine on staging and production build.
Thanks @lforst .

**Comment by ibrahim-ytl** [comment]
Hi @lforst I am facing same issues as well. However I haven't deploy my application to prod or stage yet. Does this issue only occur when in localhost?

**Comment by lforst** [comment]
We are not optimizing sourcemaps for dev servers. Please try a production build (can be local).

**Comment by ibrahim-ytl** [comment]
> We are not optimizing sourcemaps for dev servers. Please try a production build (can be local).

Tried production build and run it on local as well. Still could not see the unminified code. 😢

**Comment by lforst** [comment]
@ibrahim-ytl we need more info! Please open a new issue with concrete reproduction steps!
