### ISSUE TITLE
[SaaS] Migrate legacy student plan w/o "downgrading"

### ISSUE THREAD

**Issue by zhiyan114** [getsentry/sentry#76821]
### Problem Statement

Some students, like me, are on the legacy edu plan. Because it's a legacy plan, some features are broken (i.e. Insights stuff). If we were to migrate to the latest plan, we would lose out the benefit of the legacy plan (i.e. no expiration and high quota).

### Solution Brainstorm

I'd be awesome if Sentry could either update the legacy subscription to reflect on the latest change on the subscription system or create one additional subscription type that matches what the legacy plan was offering.

### Product Area

Settings - Subscription

**Comment by brianthi** [comment]
Hi @zhiyan114, thanks for raising this concern. We don't have plans at the moment to update or create a new Github student plan to get access to the latest plan features. With most plan changes, this is something we consider but sorry to say that as of today there's no plan to do so.

**Comment by zhiyan114** [comment]
> Hi [@zhiyan114](https://github.com/zhiyan114), thanks for raising this concern. We don't have plans at the moment to update or create a new Github student plan to get access to the latest plan features. With most plan changes, this is something we consider but sorry to say that as of today there's no plan to do so.

Thank you for the response! If plan implementation isn't being considered, Will it be possible for the support team to migrate the plan and adjust the quota/expiration manually?

**Comment by brianthi** [comment]
@zhiyan114 yes, support can help you upgrade from your existing plan to a paid plan that has the features you'd like. You can create a support issue by filing one here: https://help.sentry.io/
