### ISSUE TITLE
Sentry user feedback button disappears after split seconds of rendering in next.js

### ISSUE THREAD

**Issue by abhidiwakar** [getsentry/sentry#76825]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Add sentry in next.js app
2. Add Feedback integration in the integrations section of `sentry.client.config.ts`
```jsx
Sentry.init({
    // other config options
    integrations: [
        // other integrations
        Sentry.feedbackIntegration({
             // Additional SDK configuration goes in here, for example:
             colorScheme: "system",
             isNameRequired: true,
        }),
    ]
})
```

### Expected Result

The user feedback button should render on the screen when the next.js application loads in the browser.

### Actual Result

The user feedback button does load initially but disappears instantly after the next.js application completely loads in the browser.

### Product Area

User Feedback

### DSN

https://eb8a50e6f65186a37049cd4bd9191dff@o4505021758898176.ingest.us.sentry.io/4507048956854272

**Comment by bruno-garcia** [comment]
Is it possible it's related to hydration error?

Could you share a repro so the team can debug?

**Comment by abhidiwakar** [comment]
Hi @bruno-garcia 
It was indeed a hydration error. I have this code in my project that was causing a hydration error.
```js
<small className="text-slate-300">
    It&apos;s{" "}
          {dayjs
            .tz(currentDate, "Asia/Kolkata")
            .format("ddd, MMM D, YYYY - h:mm A")}{" "}
          here.
</small>
```


Dates often cause hydration errors because the server and client exist in different timezones or the relative time has changed since the server rendered the page. To fix the issue, i just suppressed the hydration warning using the `suppressHydrationWarning`.
https://nextjs.org/docs/messages/react-hydration-error#solution-3-using-suppresshydrationwarning
```js
<small className="text-slate-300" suppressHydrationWarning>
    It&apos;s{" "}
          {dayjs
            .tz(currentDate, "Asia/Kolkata")
            .format("ddd, MMM D, YYYY - h:mm A")}{" "}
          here.
</small>
```
