### ISSUE TITLE
[Laravel] Take me to Session Replay doesn't make sense in Laravel

### ISSUE THREAD

**Issue by vgrozdanic** [getsentry/sentry#76829]
https://sentry.rewatch.com/video/1drizqrsrxqmuewe-laravel-11-livewire-sentry-onboarding?t=1661

**Comment by vgrozdanic** [comment]
https://github.com/getsentry/sentry/blob/d836df040b66bc9439c32c3958353acde2687957/static/app/data/platformCategories.tsx#L410

**Comment by matejminar** [comment]
Duplicate of https://github.com/getsentry/sentry/issues/77138
