### ISSUE TITLE
N+1-queries - threshold number of spans

### ISSUE THREAD

**Issue by peterHakio** [getsentry/sentry#76835]
### Problem Statement

I have a multi tenant setup, where I need to query across all tenants. This is generally done with one query per tenant. So I would love to be able to adjust the setting threshold number of queries in the admin panel

![Image](https://github.com/user-attachments/assets/efa123c2-b06c-416e-ad27-1113f9cd498c)

![Image](https://github.com/user-attachments/assets/2b70f0aa-bcb4-446c-a607-8ecc8b731a60)

### Product Area

Settings

**Comment by Dhrumil-Sentry** [comment]
@peterHakio Are you basically asking to be able to query the number of N+1 span per tenant (which I assume is a tag on your spans?)

**Comment by peterHakio** [comment]
> [@peterHakio](https://github.com/peterHakio) Are you basically asking to be able to query the number of N+1 span per tenant (which I assume is a tag on your spans?)

We send one query peer tenant, which is the bascialy the same query. Just performed with a different Postgres search_path. When we have 10 tenants this will show up as 10 identical queries each with there own span. Here is our setup for JS.Kysely 
```

export async function invokeForAllCompanies<T extends Record<string, any>>(
  transactionLogic: (trx: Transaction<DB>) => Promise<T[]>,
  schemaNames?: string[],
) {
  const schemaNamesToQuery = schemaNames ?? (await getAllSchemaNames())
  return (
    await Promise.all(
      schemaNamesToQuery.map(async (schemaName) => {
        const kyselyDb = await getGenericDb()
          .transaction()
          .setIsolationLevel("serializable")
          .execute(async (trx) => {
            await sql`
              SET
                search_path = ${sql.raw(schemaName)};
            `.execute(trx)

            return trx
          })
        return transactionLogic(kyselyDb)
      }),
    )
  )
    .map((a, index) => a.map((b) => ({ ...b, orgId: schemaNamesToQuery[index] ?? "" })))
    .flat()
}
```

I know it is not something everyone is facing, so I though it would make sense to be able to adjust the threshold maching the number of companies we are having. (later we might need another solution). And it seemed meaningful to be able to adjust this threshold since 5 could seem alittle arbitrary and somebody could set it even lover in order to detect N + 1 in testing. Which is in many cases done on smaller problems.

**Comment by Dhrumil-Sentry** [comment]
Thanks a lot for this feedback, We'll add it to our backlog but we don't have concrete timelines as of now cc @bcoe

**Comment by mjq** [comment]
@peterHakio Thanks for your suggestion! This has been rolled out and you can now configure the count threshold under your project performance settings (Settings -> Projects -> (your project) -> Performance).

**Comment by peterHakio** [comment]
> [@peterHakio](https://github.com/peterHakio) Thanks for your suggestion! This has been rolled out and you can now configure the count threshold under your project performance settings (Settings -> Projects -> (your project) -> Performance -> N+1 Query -> Minimum Query Count).

You guys are awesome. I have applied it and it works thanks
