### ISSUE TITLE
web-vitals indicators will always change

### ISSUE THREAD

**Issue by windole** [getsentry/sentry#76840]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

After entering the Web Vitals tab, select a fixed absolute date and refresh the page. You will find that the LCP value is different from the last time.

### Expected Result

At a fixed absolute date, the LCP value is the same as the previous one

### Actual Result

![Image](https://github.com/user-attachments/assets/a2b4c068-3e4a-40d9-a4f9-0faca312170c)

![Image](https://github.com/user-attachments/assets/46e41809-2392-4076-b513-1498c1ab16c5)

### Product Area

Performance

**Comment by edwardgou-sentry** [comment]
Hi @windole can you show us how you are changing the date range on the page filters?

**Comment by alexjillard** [comment]
We're unable to reproduce this, but @windole if you're able to help us out here, we can re-open and continue to investigate.
