### ISSUE TITLE
Latest release filters do not exclude archived releases when using semantic versioning

### ISSUE THREAD

**Issue by ericemmrich** [getsentry/sentry#76841]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Trigger a Sentry error from a semantic version release, e.g. `myapp@10.0.0`.  
2. Archive the release in Sentry.
3. Trigger another Sentry error from a semantic version release, using a lower version, e.g. `myapp@5.0.0`.

### Expected Result

The Sentry filters `release:latest`, `firstRelease:latest` + "latest release" alerts will contain all issues related to the latest non-archived release `myapp@5.0.0`.

### Actual Result

The Sentry filters do not show any results + alerts do not get triggered. 

They only do once the semantic version is higher than the one of the archived release, e.g. for any new errors coming from `myapp@12.0.0`.

As this is working as expected for time-based versioning (i.e. when not using semantic versions), I would deem this as a bug. For more info, see Sentry support request #130192.

### Product Area

Issues

**Comment by malwilley** [comment]
From my testing, it looks like, as far as the issue list search is concerned, `release:latest` will search for the latest release regardless of whether or not it is archived. I've opened a PR that would skip archived releases, but before merging that I need to check with teammates to see if that is the desired behavior.

**Comment by ericemmrich** [comment]
> From my testing, it looks like, as far as the issue list search is concerned, `release:latest` will search for the latest release regardless of whether or not it is archived. I've opened a PR that would skip archived releases, but before merging that I need to check with teammates to see if that is the desired behavior.

Awesome - thank you so much! 🙏 Will your change also fix the `firstRelease:latest` filter then?

**Comment by malwilley** [comment]
@ericemmrich yes, this should fix the `latest` alias for all release filters!

I've confirmed that this is the correct approach, so it should be merged in sometime today.

**Comment by malwilley** [comment]
@ericemmrich the fix has been deployed - let us know if it's working for you!

**Comment by ericemmrich** [comment]
> [@ericemmrich](https://github.com/ericemmrich) the fix has been deployed - let us know if it's working for you!

@malwilley Thank you so much for tackling this so quickly! It works like a charm and even fixed our alerts with this condition as well:

![Image](https://github.com/user-attachments/assets/febecaac-cb4d-4024-944a-b282a9b27ca8)

Love you guys - keep up the great work ❤
