### ISSUE TITLE
Cannot resolve issue with current release from Issues overview

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#76845]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the Issues page
https://kismeow.sentry.io/issues/?query=&referrer=issue-list&statsPeriod=14d

2. Try resolving an issue with the current release:

![Image](https://github.com/user-attachments/assets/5595c0ae-8523-412a-8752-bf29adce8e1f)

the issues/{{issue_id}} endpoint returns a 400 (Bad request) and the following response:

{
    "statusDetails": {
        "inRelease": [
            "Unable to find a release with the given version."
        ]
    }
}

### Expected Result

I should be able to perform this action since the release exists: https://kismeow.sentry.io/releases/dalnoki-papp.zsofia.WeSplit%401.0%2B1/?project=4507301797363712

### Actual Result

I can only resolve the issue from here:

https://kismeow.sentry.io/issues/5747534325/?query=&referrer=issue-stream&statsPeriod=14d&stream_index=0

### Product Area

Issues

**Comment by malwilley** [comment]
It looks like this bug is occurring when "My projects" is selected and not a single project. We should be sending a project ID in both cases, but are not. I will create a PR to fix shortly!
