### ISSUE TITLE
Source code was not found for app:///main.ios.jsbundle in React Native

### ISSUE THREAD

**Issue by xutm** [getsentry/sentry#7687]
- react-native 0.50.4
- react-native-sentry 0.32.1
- sentry 8.19.0
- while testing on a real IOS device in Debug config (prebundled source on the device)
- sourcemaps are uploaded correctly since they appear as "~/main.ios.jsbundle.map" on -
 release/artifacts page for the correct dist number
- the error is: **"Source code was not found for app:///main.ios.jsbundle"**

### init sentry
`Sentry.config(ops.dsn).install()`
`Sentry.setRelease('0.0.32')`
![sentry](https://user-images.githubusercontent.com/11706751/37592995-78a929b2-2bab-11e8-92ca-d8e2c51b516a.jpeg)

### sourcemap
```
node node_modules/react-native/local-cli/cli.js bundle --platform ios --entry-file ./src/index.js --bundle-output ./output_ios/main.ios.jsbundle --sourcemap-output ./output_ios/main.ios.jsbundle.map --assets-dest ./output_ios --dev true
```
![sourcemap](https://user-images.githubusercontent.com/11706751/37592282-2c276e2a-2ba9-11e8-853c-cf514768d444.jpeg)
### upload bundle and sourcemap
```
./node_modules/.bin/sentry-cli --auth-token <auth-tocken> --url https://fse.devops.xiaohongshu.com/ releases -o sentry -p mall-home files 0.0.32 upload-sourcemaps --rewrite --validate /Users/xutianming/red/mall-home/output_ios/main.ios.jsbundle /Users/xutianming/red/mall-home/output_ios/main.ios.jsbundle.map --strip-prefix /Users/xutianming/red/mall-home/output_ios/
```
![sourcemap](https://user-images.githubusercontent.com/11706751/37592357-614ae988-2ba9-11e8-9c85-8f402e1901ea.jpeg)
### project => releases => artifacts
![artifacts](https://user-images.githubusercontent.com/11706751/37592483-c0b4a68e-2ba9-11e8-9902-fb31486b60a4.jpeg)
### error
![error](https://user-images.githubusercontent.com/11706751/37592525-e6d048d2-2ba9-11e8-86c9-5edf514e3098.jpeg)

I don't know where is the problem，how to solve the problem?

**Comment by sauravy** [comment]
+1

**Comment by HazAT** [comment]
Please create an issue on https://github.com/getsentry/react-native-sentry
This error is probably caused by release / dist do not match the event tags.
Also please provide an url to your sentry.io issue so we are able the check whats going on.

**Comment by hsparihar-systango** [comment]
Getting same issues on "react-native-sentry": "^0.40.3" version.
Tried to configure on the free account then got the debug file but on deployed version getting the error  
Source code was not found for app:///main.jsbundle Expand
Not getting the error stack trace 
![screen shot 2019-02-26 at 2 49 01 pm](https://user-images.githubusercontent.com/29117670/53401552-08818000-39d6-11e9-80a7-6ab230dbea75.png)
