### ISSUE TITLE
Missing "Code" Field in Sentry Payload for Split Integration

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry#76903]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

A representative from split noticed that the Split <> Sentry integration is not functioning as expected for some of their customers. Specifically, the payload coming from Sentry during the installation process is missing the "code" field, which is necessary for completing the initial grant code exchange.

Example payload:
```
{
"action":"created",
"installation":{
"uuid":"XXXXX"
},
"data":{
"installation":{
"app":{
"uuid":"XXXXX",
"slug":"split"
},
"organization":{
"slug":"example"
},
"uuid":"XXXXX",
"status":"pending"
}
},
"actor":{
"type":"user",
"id":XXXXX,
"name":"Guido Pochettino"
}
}

```

Is this something we could fix or should we advise them to handle auth differently? 

### Expected Result

According to our integration documentation ([Public Integration](https://docs.sentry.io/organization/integrations/integration-platform/public-integration/)), the payload should include the "code" field to allow for proper token exchange and finalizing the integration setup.

### Actual Result

The payload sent from Sentry during the Split integration installation process does not contain the required "code" field. As a result, Split is unable to complete the initial grant code exchange, preventing the integration from functioning properly for new installations.

### Product Area

Settings - Integrations

**Comment by gpochettino** [comment]
To repro this issue I went to Settings -> Integrations -> Split. 

If I try to install a new installation. I get the installation UUID. 

![Image](https://github.com/user-attachments/assets/fbfb7d24-84f6-4958-8317-83c5a37a6722)

The Split application is receiving the installation message, however is missing the code field. 

Actual message: 
```json
{
   "action":"created",
   "installation":{
      "uuid":"XXXXX"
   },
   "data":{
      "installation":{
         "app":{
            "uuid":"XXXXX",
            "slug":"split"
         },
         "organization":{
            "slug":"example"
         },
         "uuid":"XXXXX",
         "status":"pending"
      }
   },
   "actor":{
      "type":"user",
      "id":"XXXXX",
      "name":"Guido Pochettino"
   }
}
```

Expected message: 
```json
{
   "action":"created",
   "installation":{
      "uuid":"XXXXX"
   },
   "data":{
      "installation":{
         "app":{
            "uuid":"XXXXX",
            "slug":"split"
         },
         "organization":{
            "slug":"example"
         },
         "uuid":"XXXXX",
         "code": "XXXXXXXXXXXXX",
         "status":"pending"
      }
   },
   "actor":{
      "type":"user",
      "id":"XXXXX",
      "name":"Guido Pochettino"
   }
}
```

This is causing our Backend to not be able to do the token exchange, so we cannot get authenticated for retrieving the project id.

**Comment by leedongwei** [comment]
Hello. Thanks for the report.

Unfortunately, the integration team is understaffed right now and we will not be able to look into this in a timely manner. Apologies for this. If you'd like to unblock yourself, you can try to open a PR to fix the issue and ping us here to review it.

**Comment by animcdowell** [comment]
@leedongwei Can you point us to the file(s) so we can take a look and see if it is possible for us to open the PR? Thanks

**Comment by gpochettino** [comment]
@sentaur-athena I saw that a PR was merged, when is this supposed to reach production so we can test from our side?

**Comment by sentaur-athena** [comment]
It's deployed now.
