### ISSUE TITLE
Add timestamps to replays based on local time

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#76933]
### Problem Statement

Problem Statement
I've a feature request that should be fairly simple but its valuable for replay investigations and maybe relevant for other companies as well.
(Let me know if this is not the right place for it. )

Problem: We have a customer complain that on on 14:17 PM on 1st of January he had a certain issues, or we see under the discover tab a specific error that happen during this timestamp (the view includes timestamp).

It would be really useful for the Replay view to include the full timestamp as well to be able to easily correlate (instead of showing the text happen "X days ago" and require us to hover over each X days ago text to see the full timestamp (in some cases we can't filter by absolute date and need to go over daily range of recordings, which makes it really difficult and require us to over each tooltip one by one and check the full timestamp)

Solution Brainstorm
During the replay itself, to know go for the specific timestamp (14:17) I need to check the tooltip on the screen for the start of the replay e.g 14:09 PM, then manually calculate the time between the error and move the time by 8 minutes to discover the relevant time of issue I want to look for.

It would be really helpful if there was a UTC timestamp view on the recoding screen on top + instead of timer for the start of the recording to have a timestamp timer.

![Image](https://github.com/user-attachments/assets/3447a893-adee-44cd-83ca-00eee06834ef)

![Image](https://github.com/user-attachments/assets/196c8dd4-80f4-4578-9d63-a9fdaee36b45)

![Image](https://github.com/user-attachments/assets/04f334c5-6266-4235-a72c-0cbdb4bb4fe9)

### Solution Brainstorm

Originally posted in JS SDK repo -> https://github.com/getsentry/sentry-javascript/issues/13446

Migrated to getSentry as this is more of a UI improvement than SDK. 

### Product Area

Replays

**Comment by c298lee** [comment]
Hi @kpujjigit, thanks for writing in! We will be adding a setting to view the UTC timestamp instead of the replay duration in the timeline of the Replay Details page, feel free to follow this ticket for updates: https://github.com/getsentry/sentry/issues/52682

**Comment by jas-kas** [comment]
Hey @kpujjigit, the changes Catherine described have been shipped: https://github.com/getsentry/sentry/pull/77251

Please see the setting below:

![Image](https://github.com/user-attachments/assets/d1aad2e3-553a-4bfb-8f33-ebb85130ee09)

Does this resolve the issue for you? The Replay Details header (time you see on the top) does not update to absolute time because it is what is carried over from the Replay landing page. However, the entire timeline updates to display absolute time.

**Comment by kpujjigit** [comment]
> Hey [@kpujjigit](https://github.com/kpujjigit), the changes Catherine described have been shipped: [#77251](https://github.com/getsentry/sentry/pull/77251)
> 
> Please see the setting below:
> 
> ![Image](https://github.com/user-attachments/assets/d1aad2e3-553a-4bfb-8f33-ebb85130ee09)
> 
> Does this resolve the issue for you? The Replay Details header (time you see on the top) does not update to absolute time because it is what is carried over from the Replay landing page. However, the entire timeline updates to display absolute time.

This is precisely what I had envisioned. Thank you kindly 😁
