### ISSUE TITLE
Replay UI: clicking on a network item results in an error

### ISSUE THREAD

**Issue by vaind** [getsentry/sentry#77001]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Pick a replay with network activity
2. go to the network tab
3. click any of the items

### Expected Result

unknown

### Actual Result

error message "There was a problem rendering this component"

https://github.com/user-attachments/assets/d9576fd3-f6dd-483c-92b4-0178633c496f

### Product Area

Replays

### Link

https://sentry-sdks.sentry.io/replays/7a8dbe489317419babe7cc92e312d6cb/?query=&referrer=%2Freplays%2F7a8dbe489317419babe7cc92e312d6cb%2F&statsPeriod=24h&t_main=network&yAxis=count%28%29&t=0

**Comment by ryan953** [comment]
the error in the console is `Cannot include a '?' character in a manually specified `to.pathname` field` 
this is coming from our upgrade to react-router v6, the feature flag for that upgrade is only enabled on internal orgs, so the issue isn't widespread.

**Comment by michellewzhang** [comment]
is this issue still occuring? @vaind

**Comment by vaind** [comment]
fixed now
