### ISSUE TITLE
Ability to customize the email address Sentry uses to send notifications

### ISSUE THREAD

**Issue by sentryadam0000345** [getsentry/sentry#77053]
### Problem Statement

Currently, the email that Sentry uses to send things like weekly reports are locked to the following email address: `"noreply@md.getsentry.com"`.  

It would be great if this could be changed to using a custom email address. The reason being is that it allows for IT teams to be able to filter messages more easily and standardize the way for 3rd party vendors send emails to employees at a firm.  

### Solution Brainstorm

An ability to add a custom email within the Org settings would be ideal.  

![Image](https://github.com/user-attachments/assets/a2a8d74a-fbbd-473f-bb19-39ebcf2b472f)

### Product Area

Settings

**Comment by leedongwei** [comment]
> It would be great if this could be changed to using a custom email address.

How would this work? Does the user provide Sentry with a Mailgun/Sendgrid API key and we send it through their email service account? I didn't do any research, but it doesn't pass the smell test for Sentry to spoof "from: email@acme-company.com" field on our transactional emails.
