### ISSUE TITLE
Cannot create Issue alerts

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#77063]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to https://org_slug.sentry.io/alerts/new/issue/?project=ai-inquiry-doctor&referrer=alert_stream
2. The page doesn't load, the https://us.sentry.io/api/0/projects/org_slug/project_name/rules/preview/?cursor&per_page=5 endpoint returns the following response: ["Invalid input."]

Additional details in the Jira ticket.

### Expected Result

The page should load, it should be possible to create issue alerts for the org

### Actual Result

The page does not load, it is not currently possible to create issue alerts for the org

### Product Area

Alerts

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2280) by [Unito](https://www.unito.io)

**Comment by kpujjigit** [comment]
Additional Context:

Checking the browser's network console when creating an alert, we can see a '400 Bad Request'

For at least one organization, this 400 results in the creation wizard remains greyed out and cannot be interacted with, per below screenshot.

![Image](https://github.com/user-attachments/assets/1f19bec8-39cc-4c5f-97e6-36afaf27cc87)

**Comment by schew2381** [comment]
Thanks for the report, @snigdhas is currently putting together a fix for this

**Comment by ceorourke** [comment]
This issue should now be resolved
