### ISSUE TITLE
Asana integration is broken

### ISSUE THREAD

**Issue by peterklipfel** [getsentry/sentry#77111]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Settings -> Integrations -> Asana (found by searching for "Asana" in the search bar
2. Click "Associate Identity"

### Expected Result

An oauth flow allowing me to authenticate with Asana

### Actual Result

```
Error

invalid_request: The `redirect_uri` parameter does not match a valid url for the application.
```

![Image](https://github.com/user-attachments/assets/b4a2b144-c155-4aa1-bb9f-9f881bd08060)

Alternatives tested:
1. Associate identity after enabling the plugin (same error)
2. Associate identity after clicking "reset configuration"

Notes:

I have also received 500s on other requests associated with this plugin including the "reset configuration" button which 500s at this url:

https://us.sentry.io/api/0/projects/[our project]/php/plugins/asana/

### Product Area

Settings - Integrations

### Link

https://[our org].sentry.io/settings/projects/php/plugins/asana/

**Comment by jonaswebdev** [comment]
It's happening for me too

**Comment by anna-alda** [comment]
Also happening to me

**Comment by leedongwei** [comment]
Thanks for the report. We'll have the team investigate this.

**Comment by GabeVillalobos** [comment]
It appears we changed our redirect URI within Sentry at some point, but didn't update it on the Asana app. We're testing the fix and updating the URI on Asana's side, but this may take a bit of time as published Asana apps cannot be updated without manual approval from their support team. We'll let you know when we have more updates on this.

**Comment by sentaur-athena** [comment]
Thank for reporting this issue, and thanks @GabeVillalobos for creating a ticket for Asana.
Unfortunately Asana is built as a plugin which is deprecated Sentry platform for integrations. Our team doesn't maintain plugins anymore and instead we encourage 3rd party integration creators to use our docs to integration with sentry: https://docs.sentry.io/organization/integrations/integration-platform/public-integration/

I recommend reaching out to Asana.
