### ISSUE TITLE
custom fields

### ISSUE THREAD

**Issue by mrzbn** [getsentry/sentry#77128]
### Problem Statement

I want to send some field (e.g. api response time) to sentry and apply functions on it in dashboard like p99 or avg. is there already a way for that? cause I see only some defined fields can be used with these functions.

### Product Area

Dashboards

**Comment by ale-cota** [comment]
hi @mrzbn,
You can send custom fields to sentry by either using [custom tags](https://docs.sentry.io/platforms/javascript/enriching-events/tags/) or [custom measurements](https://docs.sentry.io/product/performance/metrics/#custom-performance-measurements) if you're looking only at numerical values.

However, for the use case you mentioned - measuring something like api response time and plotting the avg or p99 - you can use the `transaction.duration` field which serves exactly this purpose. You can then for example group it by `transaction` then to see the values per specific endpoint. Please try that out and let us know if you have other questions.
