### ISSUE TITLE
Request for Transition Plan for Metrics Beta Users with Ongoing Observability Needs

### ISSUE THREAD

**Issue by kiran-esper** [getsentry/sentry#77130]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Using the Sentry Metrics Beta, we are trying to maintain observability on a critical feature. Given the upcoming end of the Metrics Beta, **we are seeking a solution that allows us to continue using the metrics functionality without significantly disrupting our workflow or incurring the operational overhead** of switching to a temporary alternative tool.

### How are you getting stuck?

With the Metrics Beta ending on October 7th, we face a tight timeline to explore and migrate to another tool. This is particularly challenging as implementing a new solution requires significant effort.

If Sentry were to release the new metrics feature after, transitioning back would not be ideal, no matter how robust the solution, as it would involve multiple engineering efforts and shifting priorities. At the same time, companies focus on their business logic.

The absence of a clear transition plan leaves us uncertain about maintaining critical observability during this interim period. An ideal solution would be to offer customers sufficient time to transition or, even better, extend support until the new product is released, ensuring that customers remain within the Sentry ecosystem.

### Where in the product are you?

DDM

**Comment by ale-cota** [comment]
Hi Kiran,

Thank you for sharing your feedback and we really appreciate you participating in the beta program. It’s clear that it's become an important part of your workflow, and I understand the challenges its retirement creates.

The decision to retire Metrics beta on October 7th was made after careful evaluation and, unfortunately, extending it until a new product is released won't be possible. We’re committed to delivering a more fitting solution in the near future, but it will look very different from the current version. With no clear transition path, we also want to make sure you don't invest further time in a product that will not be supported long-term.

We know this isn’t ideal - we also would have preferred to have the alternative available right away. However, we recognise that it will take some time and want to get it right before we make this available to customers again.

Thank you for understanding.

**Comment by kiran-esper** [comment]
I've never seen an open beta where the product was stopped before it became generally available (GA), and most people would expect the same. If there was a chance of Metrics being discontinued, it should have been done as a closed alpha instead. After all, the whole point of an open beta is to move toward a GA release.

Extending this for an additional two months would give people enough time to find alternatives and respond to this!

**Comment by ale-cota** [comment]
hi @jvineet,
Our new metrics solution will not support sending standalone custom metrics like the current metrics beta. It will instead derive aggregations directly from span data.

**Comment by jvineet** [comment]
@ale-cota FWIW, we thought the custom metrics feature was a pretty great "push metrics" solution, especially w.r.t the ease with which we could send metrics over from internal svcs as well as browser apps. It also helped with consolidation of some of the observability stack. I hope your team would reconsider supporting custom metrics in some fashion or another in the near future.

**Comment by Dhrumil-Sentry** [comment]
Closing this issue

We've started rolling out our span powered metrics solution. Please see this discussion: https://github.com/getsentry/sentry/discussions/81239
