### ISSUE TITLE
Changing status to reprocessing through API doesn't currently work

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#77132]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the docs: https://docs.sentry.io/api/events/update-an-issue/
2. There it is mentioned that the current valid values are "resolved", "reprocessing", "unresolved", and "ignored".
![Image](https://github.com/user-attachments/assets/d5896243-aecc-4386-abfd-4c80b3e0641c)
3. Send a request with status:reprocessing and a 400, bad request is returned:

```{"status":["\"reprocessing\" is not a valid choice."]}```

### Expected Result

status: reprocessing should work, or if it's not a valid value, we shouldn't mention it in the docs

### Actual Result

this option is not currently working

### Product Area

APIs

**Comment by a-samir97** [comment]
@leedongwei Is there any update about this issue ? if not, i can pick it up to work on.

**Comment by sentaur-athena** [comment]
Issues team would be the right to update these docs. I believe they're working on some doc updates next week so this might be already on their radar.
