### ISSUE TITLE
Friction when finalizing project creation

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#77138]
Having to choose between going to  issues / performance / replays is potential friction for the user.
We should be more opinionated here and just forward them to what makes sense.

Important: Do not forward to performance / replays if the verify step did not create any data for it.

https://app.amplitude.com/analytics/sentry/chart/new/sgnhne1u?source=copy+url

**Comment by ale-cota** [comment]
Concluded that we can remove the secondary CTAs and just leave "Take me to Issues"
