### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by n-galochkin** [getsentry/sentry#77137]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. github install
2. request to project on github
3. close window
4. after aprove on github nothing happens
5. open again install and now we see configurate button only
6. close window github not installed as result

### Expected Result

github integration status - ok

### Actual Result

github integration status - not installed 

### Product Area

Settings - Integrations

**Comment by n-galochkin** [comment]
I cant update status in github configure page bcz im not owner of github organization

**Comment by leedongwei** [comment]
I'm not able to replicate the issue. Can you share a project DSN from your organization?

**Comment by n-galochkin** [comment]
https://b2e1379186749bdb55dc75623523047d@o4507010249392128.ingest.us.sentry.io/4507010261778432

**Comment by n-galochkin** [comment]
We just removed github integration, and integrated with him by github owner

**Comment by sentaur-athena** [comment]
@n-galochkin are you still experiencing the issue? I just didn't quite understand your last comment.

**Comment by cathteng** [comment]
Closing this issue. If you're still experiencing this, feel free to reopen.
