### ISSUE TITLE
Truncated error message

### ISSUE THREAD

**Issue by nirmaljingar** [getsentry/sentry#7715]
Sentry showing truncated exceptions and I cannot see the full response.

GuzzleHttp\Exception\ServerException
Server error: `POST https://example.com/ccu/v2/queues/default` resulted in a `503 Service Unavailable` response:
<HTML><HEAD><TITLE>Error</TITLE></HEAD><BODY>
An error occurred while processing your request.<p>
Reference&#32;&#35;30& (truncated...)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
