### ISSUE TITLE
[Hydration Errors] Update Modal so all references to "Before" and "After" are bold, red&green, not say "Before Hydration"

### ISSUE THREAD

**Issue by ryan953** [getsentry/sentry#77208]

**Comment by wedamija** [comment]
@ryan953 I assume this is replays related, feel free to assign elsewhere

**Comment by billyvg** [comment]
From what I can tell, this is done ![Image](https://github.com/user-attachments/assets/7cd5ccda-c048-445d-867f-72d2e992f3ba)
