### ISSUE TITLE
Cannot edit alert rule

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#77238]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the alert rule edit page
2. The page currently doesn't load so the alert rule cannot be edited

please see details in the attached Jira issue

### Expected Result

the page should load, the customer should be able to edit the rule

### Actual Result

the page doesn't load, the customer is not currently able to edit the rule

### Product Area

Alerts

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2285) by [Unito](https://www.unito.io)

**Comment by mifu67** [comment]
We're looking into this.

**Comment by schew2381** [comment]
Heads up this is caused by the same bug in https://github.com/getsentry/sentry/issues/77063

**Comment by schew2381** [comment]
This should now be resolved, feel free to ping me on this issue again if it pops up!
