### ISSUE TITLE
Issue Trackers missing from Issue Details (Linear, Incident.io)

### ISSUE THREAD

**Issue by kpujjigit** [getsentry/sentry#77258]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Observe Issue in Org that has Linear integration installed.

### Expected Result

Options should be available to create Linear ticket right from issue details

![Image](https://github.com/user-attachments/assets/da345b70-c332-46d8-8be6-9a79750f00d6)

### Actual Result

Clients are no longer seeing Linear for our Issue tracking, even though the integration is enabled. Same for Incident.io

![Image](https://github.com/user-attachments/assets/169177cd-1055-48ab-bf37-70b16c6a9ce3)

![Image](https://github.com/user-attachments/assets/320941a7-153e-4bca-a0c7-c54dd302eeee)

![Image](https://github.com/user-attachments/assets/83d3b4e3-bee0-4c82-bcf4-2d25b6f4338e)

### Product Area

Settings - Integrations

**Comment by sentaur-athena** [comment]
We're looking at this. Will post an update soon.

**Comment by sentaur-athena** [comment]
This issue should have resolved now. More details here: https://github.com/getsentry/sentry/issues/77402
