### ISSUE TITLE
Incident.io Not receiving installation webhook

### ISSUE THREAD

**Issue by phroggyy** [getsentry/sentry#77308]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When installing our incident.io integration in Sentry, we do not receive a webhook from Sentry. Therefore, we cannot call the `verify_installation` endpoint, meaning a customer is left with a pending installation.

### Expected Result

We receive the webhook.

### Actual Result

We see no installation webhook.

### Product Area

Settings - Integrations

**Comment by sentaur-athena** [comment]
Please check the way the installation is set up: https://docs.sentry.io/organization/integrations/integration-platform/webhooks/installation/

**Comment by phroggyy** [comment]
Hi @sentaur-athena, per the ticket, we're not seeing that webhook arrive for one of our customers. Would appreciate some support looking into this. More specifics (like the installation ID) are in our shared Slack channel with you.

**Comment by sentaur-athena** [comment]
@phroggyy this seems like related to the current incident where requests to incident.io fail with connection timeout. Let's monitor and see if this issue is still remaining after that one got fixed.

**Comment by Christinarlong** [comment]
Was this fixed as part of the incident?
