### ISSUE TITLE
Dashboards - Have "infinite scroll" on the table widget

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#77306]
### Problem Statement

At this moment the widgets only are limited to X amount of records when you have them all in the dashboard
This means the user needs to make multiple extra clicks to get to the second page of the table
- Open up full display
- click on next page
- etc
See: https://demo.sentry.io/dashboard/104975/?project=5808623&statsPeriod=30d
![Image](https://github.com/user-attachments/assets/6556b6e5-24cc-44aa-b197-dd8d6f21ea0a)

### Solution Brainstorm

Infinite scroll could load up a next page and add it to the table so customers don't need to wonder where the rest of the data is.

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2286) by [Unito](https://www.unito.io)

**Comment by ale-cota** [comment]
Hi Angelo,
Thanks for reporting - I agree that there's something suboptimal about the current way we display these table widgets with many rows. I'm not sure infinite scroll would be the solution, but we'll definitely look into this.

**Comment by alexjillard** [comment]
Angelo, I'm going to close this for now because we're not likely to add infinite scroll as @ale-cota pointed out. If you've got other ideas on how to fix this, let us know.
