### ISSUE TITLE
[Feature Request]  use generative AI on the side panel to diagnoise issue and find a fix or even generate a PR

### ISSUE THREAD

**Issue by sourceful-karlson** [getsentry/sentry#77311]
### Problem Statement

Sentry error, especially for python, have all the information to diagnoise an issue and create a fix, so sentry GPT should be able to create a pull request to address the fix

### Solution Brainstorm

use a Vision GPT or Claude, put that in and generate a pull request and suggest a fix and open a pull request in the customer repository in github

### Product Area

Unknown

**Comment by MichaelSun48** [comment]
Hey there @sourceful-karlson 👋  Thanks for writing in and for the suggestion! Personally, I would also love to see this feature request become a reality – No promises, but I will definitely forward your request to our AI/ML team internally and see if this is feasible.

**Comment by Dhrumil-Sentry** [comment]
The AI/ML team has autofix enabled for EA customers. Please try that feature: https://sentry.io/changelog/sentry-ai-now-available-for-early-adopters/
