### ISSUE TITLE
[Alerts Configuration] Condition to show multiple tags does not work as expected

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#77333]
## Problem 

For a User Feedback Alert (Backed on Issues Platform), I have set up a Slack alert to render both 'url' and 'user.email' tags.
Both of these tags exist on feedback events. However, only 'url' shows up. I have noticed that the `user.email` tag does not show up in the Tags list on User Feedback Details despite being indexed/searchable. This could be part of the reason why it does not render on the Slack alert. 

[Specific Alerts Configuration Page](https://sentry.sentry.io/alerts/rules/javascript/14756941/)

**Comment by aliu39** [comment]
Summary of what I found with @michellewzhang : for some reason we dont send this tag in the sdk event, but, we can fill it in on the backend before sending to Issue Platform.
