### ISSUE TITLE
add `release.stage:adopted` to sentry alerts

### ISSUE THREAD

**Issue by ethanneff** [getsentry/sentry#77356]
### Problem Statement

Add `release.stage:adopted` to sentry alerts.

I only want to be alerted to the latest release. This is helpful for mobile releases where older versions still exist in the wild. This is currently not supported. ![Image](https://github.com/user-attachments/assets/59c53f4d-f635-4d67-b85f-60b66f8a2e25)

### Product Area

Alerts

**Comment by mifu67** [comment]
Thanks for bringing this to our attention! We'll add it to the backlog.

**Comment by ceorourke** [comment]
This is a duplicate of https://github.com/getsentry/sentry/issues/75568#issuecomment-2289619544 so I'm going to close it, please follow along there
