### ISSUE TITLE
Conflicts at alert rule filtering

### ISSUE THREAD

**Issue by hermitdemschoenenleben** [getsentry/sentry#77384]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I'm trying to edit an alert rule which has been running without problems for a few years now. However, the "Save rule" button is disabled due to a "conflict", even though the alert rule works:

![Image](https://github.com/user-attachments/assets/035c77b4-733a-4bb7-ac54-123d71f427fc)

### Expected Result

I should be able to edit and save the alert rule

### Actual Result

"Save rule" button is disabled

### Product Area

Alerts

**Comment by mifu67** [comment]
Hi @hermitdemschoenenleben,

It is my understanding that this rule will never fire. Alerting when the new issue is created means that the issue has never been seen before, which is at odds with the condition that the alert be seen at least ten times. It's likely that we added these checks recently and the alert was not working properly before.

If you want to alert when an issue has been seen at least ten times, you can do it like so:
![Image](https://github.com/user-attachments/assets/0136843a-12ea-4de1-a850-676c1617fd67)

Let me know if you have further questions.

**Comment by hermitdemschoenenleben** [comment]
Hi, thanks for the quick reply! For some reason, the rule did work though and continues to work. But I'll switch to the solution that you mentioned then if this is the correct way of doing things :)
