### ISSUE TITLE
Set up source maps for Nitro project

### ISSUE THREAD

**Issue by mjdNjhNJ** [getsentry/sentry#77429]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I'm trying to unmify the code in stack trace for my [Nitro](https://nitro.unjs.io/) project. I haven't found any info about which building tool they use thus the configuration is made through `@sentry/cli`.

### How are you getting stuck?

After building the project I get many errors in a format of:
`- warning: could not determine a source map reference (Could not auto-detect referenced sourcemap for {path})
    {path} (no sourcemap ref, debug id {id})`

When I try to unmify anyway I get to the second step:
<img src="https://github.com/user-attachments/assets/e62377fa-1f0a-467a-9b30-b1cc3ac12b90" width="400"></img>

### Where in the product are you?

Issues - Source Maps

**Comment by chargome** [comment]
Hi @mjdNjhNJ, which SDK are you using?

**Comment by mjdNjhNJ** [comment]
@chargome Hey @chargome, thank you for the reply. I'm not quite sure what do you mean. I'm trying to set it up using `npx @sentry/wizard@latest -i sourcemaps`.

**Comment by mjdNjhNJ** [comment]
@chargome Ah, got it! I use `@sentry/node` SDK.

**Comment by chargome** [comment]
@mjdNjhNJ 
Are you using a bundler for your project?

**Comment by mjdNjhNJ** [comment]
@chargome I'm not aware of using a bundler. I guess Nitro has its own.

**Comment by mjdNjhNJ** [comment]
@chargome Looks like Nitro uses [Rollup](https://github.com/unjs/nitro/blob/e28a02f7675e21b3aaa100d4f41f50ef1e4cb6a7/package.json#L103-L110).

**Comment by mydea** [comment]
Cc @andreiborza or @s1gr1d touched on nitro in their work on the nuxt and solid start SDKs, maybe they have an idea how to get this working!

**Comment by andreiborza** [comment]
hi @mjdNjhNJ, could you please provide a reproduction repo or stackblitz?

**Comment by s1gr1d** [comment]
This is how source maps are set up for nitro in the Nuxt SDK: https://github.com/getsentry/sentry-javascript/blob/afa79b68640caf7ea3f3bc91c584e92225a49bc8/packages/nuxt/src/vite/sourceMaps.ts#L28
Maybe this helps you as well.

**Comment by mjdNjhNJ** [comment]
@andreiborza Hey, thanks for your time! Here is a repl repository with Nitro project: https://github.com/mjdNjhNJ/nitro-sentry-source-maps-repl

I have chosen to use Rollup plugin and tried to match it with the `nitro.config.ts` as you can see in the repository. When running `pnpm build` I get stuck at `Invalid path: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object] `.

**Comment by andreiborza** [comment]
@mjdNjhNJ thanks for providing the reproduction.

In your config, `plugins` should be under `rollupConfig`, then it all works!

```js
import { sentryRollupPlugin } from "@sentry/rollup-plugin";

//https://nitro.unjs.io/config
export default defineNitroConfig({
  sourceMap: true,
  srcDir: "server",
  rollupConfig: {
    plugins: [
      sentryRollupPlugin({
        authToken: process.env.SENTRY_AUTH_TOKEN,
        org: "REDACTED",
        project: "REDACTED",
      }),
    ],
  }
});
```

I'm going to close this, but feel free to reply here if it didn't work and we can take it from there.

**Comment by mjdNjhNJ** [comment]
@andreiborza Thank you! That was it, now the source maps are uploaded successfully.

However, I'm getting this error when opening an issue:
<img src="https://github.com/user-attachments/assets/91fd7be8-246c-4ba9-8ad6-4f9b9b620885" width="600"></img>

Is it related to configuration?

**Comment by andreiborza** [comment]
@mjdNjhNJ do you have a link to some event where I could have a look?

**Comment by mjdNjhNJ** [comment]
@andreiborza Sure, please provide your business email and somebody from us will get in touch with you.

**Comment by andreiborza** [comment]
@mjdNjhNJ you can link the event here, only sentry staff can access them, but email is also fine. It's my github firstname.lastname and sentry.io.
