### ISSUE TITLE
Linear integration customers don't see create issue button

### ISSUE THREAD

**Issue by sentaur-athena** [getsentry/sentry#77477]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Here's an email we received from Linear:

We've gotten a report from a user that the button to link a Sentry issue to Linear doesn't show up. They've apparently tried your support and were sent our way.

I've tried debugging and looking into this on our end and I'm at a loss currently. Here's my findings:

When you visit an issue in Sentry there's a call to `sentry-app-components/`. Which I believe calls out to us at `sentry/hooks/issues/teams` (along with other integrations). This will include information on the UI button to link issue. Normally a response would include something like:
```
{
  error: false,
  sentryApp: {
    name: 'Linear',
    ...
  },
  ...
}
```

If I force an error on the endpoint `sentry/hooks/issues/teams` the response on `sentry-app-components/` instead will just be `error: true`.

The customer instead is seeing the call to `sentry-app-components/` timeout after 2 minutes  with a 504. See screenshot: 
image.png [not attached for privacy of customer]

I've combed our logs and although we do sporadically get a 500 or 502 on the endpoint (network issues I believe) there's nothing aligning with the user. I also fail to see how a 500 or 502 response would translate to you timing out after 2 minutes with 504.

So I currently believe that the error is either on your end or maybe another integration that's also called out to as part of `sentry-app-components/`?

If you could provide the `RayID` from some of the requests that timed out, we can double check our logs to see if there is something hiding there, but it really doesn't seem like it. And if it's not on our end then can you help the customer figure out if it's you or another integration maybe?

The customer in question is hitting this consistently at https://sentry.io/api/0/organizations/invert/sentry-app-components/?projectId=6242406.

### Expected Result

Button shows up

### Actual Result

Button doesn't show up

### Product Area

Settings - Integrations

**Comment by cathteng** [comment]
All the URLs that are timing out are precisely `https://api.linear.app/hooks/sentry`. We're seeing a `ReadTimeout` error on our side, which looks like the API is taking too long to respond to us. Our default timeout is 30.

**Comment by sentaur-athena** [comment]
Sebastian, this particular customer also is using incident.io and the issue they're experiencing is very similar with that incident which is resolved. Can you please ask them to try again?

Are they the only customer experiencing this isssue?

**Comment by skbogner** [comment]
Sorry only seeing this now. The customer has reported that it works for them after you resolved your incident, so that should be the end of it 👍
