### ISSUE TITLE
Copy button for additional data fields

### ISSUE THREAD

**Issue by BnayaZil** [getsentry/sentry#7749]
In my work, I'm using your service and we assist a lot in additional data for debugging and understanding the context or errors, very often I'm sending an object as extra data and afterward I want to copy the data and it takes some time because I can only copy the pretty structure you have as a text and I need it as a JSON.

### Spec
Adding a small icon button in the top-right corner of every additional data field, the icon will present only if a user is floating (hover) above the field with his cursor, click on the icon will copy the field content to your clipboard as a JSON.

I can open the PR by my self if my suggestion is welcome and my spec approves.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
