### ISSUE TITLE
Broken link: Organization-wide integrations

### ISSUE THREAD

**Issue by seddonym** [getsentry/sentry#7752]
I'm on hosted Sentry, with Early Adopter features turned on.

Steps to reproduce:

1. Visit home page (https://sentry.io/settings/organization/<my_organization>/)
2. In the sidebar, click on the Integrations link (which links to https://sentry.io/settings/organization/<my_organization>/integrations/)

I get a 404.

**Comment by billyvg** [comment]
Thanks, this was removed in https://github.com/getsentry/sentry/pull/7716 but there does seem to be a reference to it from the Organization Dashboard.
