### ISSUE TITLE
Sentry doesn't capture errors in FastAPI from local environemt

### ISSUE THREAD

**Issue by csmsln** [getsentry/sentry#77534]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I use FastAPI on my local machine inside a docker container.

So:
1- FastAPI is inside a docker container.
2- The docker container is in my local machine

### How are you getting stuck?

I completely copied the Sentry initialization code from the dashboard and pasted it into my FastAPI main.py file. but it doesn't capture errors and I don't see any errors in my sentry dashboard.

Following is my main.py file:
```
from fastapi import FastAPI
import sentry_sdk

sentry_sdk.init(
    dsn="https://dc36d711bef4e72095a3f6bf21d0680e@o4507949202210816.ingest.de.sentry.io/4507949226721360",
    traces_sample_rate=1.0,
    profiles_sample_rate=1.0,
)

app = FastAPI()

@app.get("/sentry-debug")
async def trigger_error():
    division_by_zero = 1 / 0
```

When I trigger the "/sentry-debug" in the browser, the browser and the FastAPI running terminal show me the Internal Error.
But I cannot see the error in the Sentry dashboard.

### Where in the product are you?

Unknown

### Link

https://local-dev-3t.sentry.io/

### DSN

https://dc36d711bef4e72095a3f6bf21d0680e@o4507949202210816.ingest.de.sentry.io/4507949226721360

**Comment by sentaur-athena** [comment]
@ReneGreen27 I don't see any integrations being used. Sending back to triage.

**Comment by snigdhas** [comment]
Hi @csmsln - could you provide your organization id? I can take a look if there's any errors we're seeing for your org.

**Comment by snigdhas** [comment]
Actually, I was able to look it up from the DSN and I'm not seeing any errors on our end. @ReneGreen27 can the support team help out here? There's not much more the issues team can do to debug this further.
