### ISSUE TITLE
Ability to manage product trials

### ISSUE THREAD

**Issue by brianthi** [getsentry/sentry#77557]
### Problem Statement

Today, there is no way to manage a product trial in-app. Customers who want to make changes to their product trials (cancel, additional trial, extend) have no way to manage it themselves. Those customers end up writing in to support to get help doing so. 

This issue tracks the request to build internal tooling to allow our support team to manage product trials. 

### Product Area

Settings - Subscription

**Comment by shellyvo** [comment]
Another request for replay trials: https://sentry.zendesk.com/agent/tickets/132669

**Comment by shellyvo** [comment]
Another ticket here: https://sentry.zendesk.com/agent/tickets/137187
When will this be available?
