### ISSUE TITLE
Replays Are No Longer Scrollable

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#77608]
### Problem Statement

 Previously when navigating to an individual Replay screen and pressing play, you could mouse over the replay videos and scroll up and down the page as if you are the user. 

Now when attempting to do this the browser page moves, not the replay video, you can reference internal ticket #132252 for a video reproduction.

I was able to reproduce this behavior in latest version of Chrome and Firefox, video reproduction demonstrates this occurring in Edge.

### Solution Brainstorm

Customer would like for this feature to be restored as this was very helpful for them in debugging with replays. 

### Product Area

Replays

**Comment by bruno-garcia** [comment]
I'm sure what scrollable experience they meant, we didn't reallly change anything in that regard.
Our aim is to have a reproduction of the site/user session so if the user scrolls on a page, the replay should reflect that. So the replay shows what the user saw already.

**Comment by billyvg** [comment]
rrweb by default has a css property on the iframe to ignore all mouse events inside of it. However, we wanted to let users be able to inspect elements within their replay (i.e. inside of the iframe), so we disabled this CSS property. A consequence of that is that users are able to interact with the replay in any way they wish (including scrolling).

This regressed, but we're fixing it.

**Comment by ryan953** [comment]
What I've done is make all the replay views "inspectable" by allowing pointer-events as @billyvg described. So links can be clicked inside the replay... but also doing "Right-Click -> Inspect Element" works great again.

The attribute scrolling="no" is set on the iframe though, and as far as i can tell I don't know how it could've become unset at any point. So i'm not sure how or when that behavior changed. Currently in my testing scrolling is not possible, but Right-click To Inspect is working better now (as the deploy finishes up)

**Comment by billyvg** [comment]
I think with `scrolling="no"`, scrolling is still possible as long as it's not the iframe scrolling (e.g. you have child divs that have overflow, those should still scroll).
