### ISSUE TITLE
Feedback Regarding Performance Page Display

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#77610]
### Problem Statement

Per customer feedback these are the following points made:

- On Performance page they'd expect us not to mix http.server operations with navigation and pageload operations as well as be able to filter these. Why are they on the same page?
- They should be able to search for http.server operations on the Performance page, instead of having to complete this search on the Discover page (Specific example is searching for http.server operations by P95)
- I used to be able to just see a list of the transactions, now there are 20 menu items for unneeded features 
- Menu item for "Requests" doesn't show incoming requests, it shows outgoing requests.
- Sentry is slower than it used to be

Internal reference ticket #131733 if needed

### Product Area

Performance

**Comment by bcoe** [comment]
The majority of this feedback should be addressed by the introduction of [domain specific insights](https://sentry.io/changelog/performance-and-insights-are-merging/) which:

* Reduces menu items significantly.
* Filters operations to the specific domain, e.g., frontend-like transactions in the frontend view.

There is a separate tracking ticket for being able to filter results without going to a discover page: https://github.com/getsentry/sentry/issues/79197
