### ISSUE TITLE
Cannot link Asana identity

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#77688]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Integrations
2. Search for the Asana integration, click on Add to Project
3. Click on Associate Identity here:
![Image](https://github.com/user-attachments/assets/bbca0ca5-31aa-49c1-9778-99e44d34e0e3)
4. The following error is shown:
![Image](https://github.com/user-attachments/assets/de5cb4ad-9669-41ed-8b28-f7f014390a5d)

### Expected Result

users should be able to associate the identity
the https://app.asana.com/-/oauth_authorize?client_id=211064917007597&redirect_uri=https%3A%2F%2Fsentry.io%2Fauth%2Fsso%2Faccount%2Fsettings%2Fsocial%2Fassociate%2Fcomplete%2Fasana%2F&state=1lzS6zzIdCQyZrlBip2nm6l1jiZVZx2T&response_type=code&next=%2Fsettings%2Fprojects%2F{{project_name}}%2Fplugins%2Fasana%2F endpoint throws a 400 - bad request

### Actual Result

it is not currently possible to associate the identity

### Product Area

Settings - Integrations

**Comment by sentaur-athena** [comment]
@dalnoki Asana is built on our deprecated integration platform called plugin. We don't provide support for plugins anymore. We did reach out to Asana to fix this specific issue though and ask customers to reach out to Asana to get help or encourage them to create a 3rd party integration: https://docs.sentry.io/organization/integrations/integration-platform/public-integration/

**Comment by dalnoki** [comment]
@sentaur-athena thanks a lot for taking a look & letting me know!
