### ISSUE TITLE
Releases - "Something went wrong" when opening up Releases overview

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#77690]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Customer URL is in Jira ticket
1. open up releases view
2. go to any timeframe
3. Error message will show up ( https://sentry.sentry.io/issues/5719481000/events/9100dae8673e40c3a5898df71f233fcc/?project=1 )

### Expected Result

Releases to load like it would normally

### Actual Result

https://sentry.sentry.io/issues/5719481000/events/9100dae8673e40c3a5898df71f233fcc/?project=1

![Image](https://github.com/user-attachments/assets/f72a84e7-633d-4fad-8ef0-9a2f189d359c)

### Product Area

Releases

### Link

See linked jira issue

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2297) by [Unito](https://www.unito.io)

**Comment by ceorourke** [comment]
I've pinged the team who added release health stuff and am waiting for a response.

**Comment by jangjodi** [comment]
It looks like this error last occurred on September 30, so I'm going to close this for now. Please reopen this ticket if this occurs again.
