### ISSUE TITLE
Profiling, no frames marked as Application Frames

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#77691]
## Problem
Why is the whole flamegraph grey when you select sortBy ApplicationFrame?
There is no distinction of application functions versus system functions. The system frames and application frames are all mixed together and grey.

## How to Reproduce
Sort By...

By System vs Application Frame -> everything in red
By Package -> works fine
By System Frame -> works fine
By Application Frame -> everything in grey. bad

## Expected Behavior
If customer name is 'toy' then customer wants all frames with `com.toy.*` to be marked as in-app, to start.

From some of the flamegraphs it looks like up to 50% start with `com.toy.*` while the other 50% are system because they start with things like `android.view.*` `androidx.*` `android.os`

## Workaround Attempt
Stacktrace Rules only apply to frames in stacktraces but not frames in the entire Profile flamegraph. It's possible the Profile flamegraph doesn't have any erroring code producing a stacktrace.
https://docs.sentry.io/concepts/data-management/event-grouping/stack-trace-rules/

### Solution Brainstorm

Can stacktrace Rules also be applied to a Profile's frames somehow?
Or could this be indicated from the sdk side instead of ProjectSettings.IssueGrouping.Stacktrace rules?

Or should SentrySDK and Sentry.io already be able to identify which are the application frames? Is there a bug going on here?

**Comment by phacops** [comment]
Profiling use the `app_identifier` property from the application context in transactions to identify application frames. If a package name starts with the `app_identifier`, it is marked as an application frame, otherwise a system frame.

We do not plan to support stack trace rules.
