### ISSUE TITLE
WorkerLostError: Only one event being logged per project

### ISSUE THREAD

**Issue by vladimircores** [getsentry/sentry#7779]
Running SEntry on a local machine - Mac
Installed with instructions from: https://docs.sentry.io/internal/environment/

"POST /api/2/store/?sentry_version=7&sentry_client=raven-js%2F3.23.3&sentry_key=f81616ce85af468480f7a8e990da2d09 HTTP/1.1" 200 643

11:10:12 worker  | objc[14357]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
11:10:12 worker  | objc[14357]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
11:10:17 worker  | 11:10:17 [ERROR] multiprocessing: Process 'Worker-9' pid:14357 exited with 'signal 6 (SIGIOT)'
11:10:17 worker  | Traceback (most recent call last):
11:10:17 worker  |   File "/Users/vladimir.minkin/.virtualenvs/sentry/lib/python2.7/site-packages/billiard/pool.py", line 1175, in mark_as_worker_lost
11:10:17 worker  |     human_status(exitcode)),
11:10:17 worker  | WorkerLostError: Worker exited prematurely: signal 6 (SIGIOT).
11:10:17 worker  | 11:10:17 [ERROR] celery.worker.job: Task sentry.tasks.store.save_event[8c25a5ef-9a34-4eef-b95f-83b6cbc3e298] raised unexpected: WorkerLostError('Worker exited prematurely: signal 6 (SIGIOT).',) (data={u'hostname': 'celery@MPB-Prague-08.local', u'name': 'sentry.tasks.store.save_event', u'args': '[]', u'internal': False, u'kwargs': "{'event_id': u'0f19c573a00e448493641862d157ce7b', 'cache_key': 'e:0f19c573a00e448493641862d157ce7b:2', 'start_time': 1522062612.005279, 'project_id': 2, 'data': None}", u'id': '8c25a5ef-9a34-4eef-b95f-83b6cbc3e298'})
11:10:59 server  | 11:10:59 [INFO] sentry.superuser: superuser.request (user_id=4 url=u'http://localhost:8000/api/0/broadcasts/' method=u'GET' ip_address=u'127.0.0.1')

**Comment by virtuman** [comment]
were you ever able to find the solution to the problem?

**Comment by HackerWilson** [comment]
related to https://github.com/celery/billiard/issues/278

**Comment by BYK** [comment]
We're now on `billiard==3.6.3`: https://github.com/getsentry/sentry/blob/2760a62145fbdfcb6d794480a965b41aff0d0530/requirements-base.txt#L91
