### ISSUE TITLE
Clarity integration

### ISSUE THREAD

**Issue by johnwc** [getsentry/sentry#77814]
### Problem Statement

Can we get integration with Microsoft Clarity added? It already does the replay recording. If we can just correlate the events in Sentry to a clarity session, we can go to clarity to view the session replay.

### Product Area

Issues

**Comment by sentaur-athena** [comment]
Thanks for submitting the request @johnwc. We don't have bandwidth to create a Clarity integration right now but we always welcome community contributions. New integrations can be build using our integration platform: https://docs.sentry.io/organization/integrations/integration-platform/public-integration/

**Comment by johnwc** [comment]
@sentaur-athena I am not really sure I follow, how would creating a custom integration sitting between sentry and Clarity work? Do I have the ability to add to senty's UI, for example like a url to Clarity's replay?


Does sentry SDK have a session ID for each user, that I can send to Clarity so I can easily filter and find it in Clarity?

**Comment by sentaur-athena** [comment]
oh sorry for the confusion, I read too fast 🤦 . You're right it can't be done with integration platform and it rerouted to our team by mistake probably because of the "integration" in it 😅  

I missed that this in fact might need support in sdk 🤔 Let me loop in the correct people. Maybe someone from Replay is more helpful.

**Comment by jas-kas** [comment]
Hey @johnwc 👋 

You can set custom context (https://docs.sentry.io/platforms/javascript/enriching-events/context/) to add a clarity session ID to your error events. Then, you can just look up the relevant session inside the Clarity platform. LMK if you have any questions!

**Comment by fdx-matias** [comment]
> clarity session ID t

Hello @jas-kas, how can I get the clarity session ID? I'm using the npm package, and I'm not finding any method to do that. Would you happen to have any clue? My idea is to initialize clarity and set the sentry context with that, but clarity documentation could be better.

**Comment by bruno-garcia** [comment]
> > clarity session ID t
> 
> Hello [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/77064737?s=64&amp;u=05777d3f0155f4152a5935733f05e070b4030994&amp;v=4">@jas-kas](https://github.com/jas-kas), how can I get the clarity session ID? I'm using the npm package, and I'm not finding any method to do that. Would you happen to have any clue? My idea is to initialize clarity and set the sentry context with that, but clarity documentation could be better.

We don't really support Clarity on this issue tracker. This is about Sentry, and we have a built-in Session Replay product.
That said as Jasmin indicated we have documented API for you to set context in Sentry issues. Now how to get stuff from a different vendor, you'll need to check with them how that part works.

**Comment by johnwc** [comment]
@bruno-garcia do I have the ability to create a plugin for sentry UI, that adds an area in the UI that I can put content in? In this example, a button that opens the session in clarity, if the sentry session was associated with a Clarity session.
