### ISSUE TITLE
Ability able to filter events based off conditional logic around releases

### ISSUE THREAD

**Issue by sentryadam0000345** [getsentry/sentry#77831]
### Problem Statement

Based off existing Github issues, listed here:
https://github.com/getsentry/sentry/issues/72932, https://github.com/getsentry/sentry/issues/71901, https://github.com/getsentry/sentry/issues/63132

Wanted to add one more feature request regarding our Inbound Filters.

Is there a way to set up an inbound filter than will drop errors events for releases below a certain number? Right now it looks like I can filter via glob matching but I'd like to be able to say something like "drop error events for all releases below x.x.x", ideally being able to filter out error events more than x releases behind current

### Solution Brainstorm

Since this doesn't seem possible could we allow this functionality via an API? Even if it is more of an unsupported internal API, being able to set this functionality programmatically would be great.  

### Product Area

Settings - Projects

**Comment by jjbayer** [comment]
This should be relatively straight forward with [Generic Inbound Filters](https://github.com/getsentry/sentry/issues/57799) if we extend the `Getter` impl of `Event` to support string access to "virtual" fields `"release.version.major"`, etc.

**Comment by cmanallen** [comment]
Refer to the docs here: https://docs.sentry.io/concepts/data-management/filtering/#releases

**Comment by zsperske** [comment]
I don't think this should have been closed? What in those docs solves the problem I described?
