### ISSUE TITLE
Bulk delete environments from monitors

### ISSUE THREAD

**Issue by nijel** [getsentry/sentry#77843]
### Problem Statement

We are heavily using environments and cron monitors. But once we remove one environment from production, all cron monitors are failing. There is option to remove environment from each cron monitor, but doing that for two pages of cron monitors is a tedious task. I can also hide environment in project settings, but that doesn't affect cron monitors and new errors are popping up.

### Solution Brainstorm

Manage Environments could add a button to remove the environment from all monitors.

### Product Area

Crons

**Comment by gaprl** [comment]
Hi @nijel thank you for the feedback. We have this issue tracked at https://github.com/getsentry/sentry/issues/71919, so I'll close as a duplicate and I recommend watching and 👍 the other issue.
