### ISSUE TITLE
Clean-up widget actions

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#77898]
**Problem/Opportunity**: Currently action buttons and descriptions are always displayed on dashboard widgets, which uses up quite a bit of the surface. The data/charts should be clearly visible and benefit from as much space as possible within the widget.

**Proposed Solution:** 
Maximizes the space available for displaying the data, by displaying icons on hover and moving the description behind an (i) icon.

![Image](https://github.com/user-attachments/assets/ce4eb73a-7f14-49d4-977e-85d421160320)
[Hover Interaction](https://github.com/user-attachments/assets/95950214-f3c4-49e5-883b-708d933b2942)

**Comment by edwardgou-sentry** [comment]
Resolved:
https://github.com/getsentry/sentry/pull/78231
https://github.com/getsentry/sentry/pull/78379
