### ISSUE TITLE
Spike Protection Per Environment

### ISSUE THREAD

**Issue by jamesreprise** [getsentry/sentry#77900]
### Problem Statement

Spike protection is useful! But right now, it's per project rather than per environment. That means when developers break the *development* environment, the spike protection for the project may cause *production* errors to be dropped. 

It should not be the case that something happening in the development environment can affect the production environment.

### Solution Brainstorm

It would be ideal if we could configure spike protection to be per environment rather than per project. I'd go even further and say that per environment should be the default, because per project is dangerous for the above reason.

### Product Area

Settings - Spike Protection

**Comment by gauthamcs** [comment]
@jamesreprise : Thanks for surfacing this! Environment-specific spike protection has come up earlier (see https://github.com/getsentry/sentry/issues/56078) and is on our backlog. We don't have an ETA at this point - we'll update this issue with timeline.

**Comment by brianthi** [comment]
Closing as this is a duplicate the ticket Gautham mentioned in previous comment
