### ISSUE TITLE
Broadcasts: Does Browser Javascript not target all frameworks?

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#77902]
A new broadcast was created with a Javascript targeting group, but I don't see it in my org with a SvelteKit project. SvelteKit definitely contains Javascript, so why is the flag not set?

**Comment by shellmayr** [comment]
Answer: Browser Javascript is a platform of its own that is the catchall for non-framework code, but does not include frameworks. Discussed solution makes this more obvious to users: https://github.com/orgs/getsentry/projects/79?pane=issue&itemId=80866434
