### ISSUE TITLE
Wizard: Sourcemaps SvelteKit - Unused auth token from .sentryclirc

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#77920]
Repo: https://github.com/obostjancic/silver-robot

got Warning: No auth token provided. Will not upload source maps. Please set the authToken option. You can find information on how to generate a Sentry auth token here: https://docs.sentry.io/api/auth/
but my .sentryclirc contains a token :/

**Comment by matejminar** [comment]
This seems to be fixed now, just validate the fix.

**Comment by shellmayr** [comment]
Works like a charm.

**Comment by shellmayr** [comment]
Ok the above was a blunder - verified in a new project that the auth now works, and source maps are uploaded automatically on `npm run build`.
