### ISSUE TITLE
Breadcrumb timestamps don't display timezone information correctly

### ISSUE THREAD

**Issue by alexgokhale** [getsentry/sentry#77937]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Access an event on the Sentry dashboard with a timestamp in the afternoon.
2. Observe the timestamp at the top of the page next to the Event ID.
3. Scroll to the breadcrumbs of this event.
4. Observe that the timestamps appear to be in 24-hour format, and don't include an `AM/PM`.

### Expected Result

Time formats should be consistent across both the event summary and breadcrumbs.

### Actual Result

Timestamp next to event ID, showing a PM timestamp:
![Image](https://github.com/user-attachments/assets/c2f8d61f-51b5-48b3-9f6a-e0606f13d29d)

Timestamps on the breadcrumbs (note that these state 03:40:XX.XXX, when I'd expect them to be 15:40:XX.XXX:
![Image](https://github.com/user-attachments/assets/efb1a650-778a-4090-a973-cf88f0fe7a07)

### Product Area

Issues

**Comment by scttcper** [comment]
@alexgokhale thanks for opening an issue.

@leeandher i took a look but it seems like we decided against showing am/pm for breadcrumbs to show seconds/milliseconds. I'll let you decide https://github.com/getsentry/sentry/blob/master/static/app/components/events/breadcrumbs/breadcrumbsTimeline.tsx#L80-L96
