### ISSUE TITLE
Issue approving a transfer

### ISSUE THREAD

**Issue by juliew210** [getsentry/sentry#77933]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Clicked on link in email ![Image](https://github.com/user-attachments/assets/a7da4c1a-5624-4f54-b0fc-ce41064f39e0)
2. Entered login info and then it gave me this message ![Image](https://github.com/user-attachments/assets/d62b8743-0eb3-4292-a778-3c683d61fc98)
3. I tried to reload the page and got nothing. 
4. I can log into my account normally as you see here ![Image](https://github.com/user-attachments/assets/452d6e05-4422-4efd-a520-03f6bd532e98)

### Expected Result

I would like to accept the transfer by clicking the button in the email, or I would like to accept the transfer directly in the account once logged in. 

### Actual Result

See in the steps to reproduce section

### Product Area

Projects - Project Details

### Link

https://wevolv2.sentry.io/accept-transfer/?data=eyJhY3Rvcl9pZCI6MzMxNDE4OCwiZnJvbV9vcmdhbml6YXRpb25faWQiOjY4ODk0NiwicHJvamVjdF9pZCI6NDUwNzY0Njc5ODY1OTU4NCwidXNlcl9pZCI6MzM5MTIzNSwidHJhbnNhY3Rpb25faWQiOiI0MWI5OWJmZDY2OGM0Y2JmYjhhNDBhNTM3OWQ4OTg0MCJ9OjFzcjFPQzpxdy05akZETzFBRF9JWnlGUzFCOUNKc1F4dW9GVzZfcC1qT0RTbTJQNzUw

**Comment by InterstellarStella** [comment]
Hi @juliew210, please write to Sentry Support through [here](https://sentry.zendesk.com/hc/en-us/requests/new) about this issue and we will be happy to help you resolve it!
