### ISSUE TITLE
Settings Members - The list of pending members doesn't get updated if the member is in the team

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#77945]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I could not reproduce it locally as I was not able to replicate the exact org setup (they have SSO enabled)
So I've provided org urls in the Jira ticket
1. Open up Org - teams page
2. See list of members to still approve
3. Check member profile + teams

### Expected Result

That once a member is part of the team it should clean up the approval list

### Actual Result

See jira for actual result but the approval row doesn't get cleared in their org

### Product Area

Settings - Members

### Link

See jira

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2300) by [Unito](https://www.unito.io)

**Comment by leedongwei** [comment]
Likely to be a small fix. I've scheduled it for the next rotational crew.
