### ISSUE TITLE
Add Search Functionality to User Feedback API

### ISSUE THREAD

**Issue by nurkilcadir** [getsentry/sentry#77941]
### Problem Statement

The current User Feedback API does not provide search capabilities, making it challenging to filter feedback based on specific attributes such as timestamp, user ID, feedback type, or message content. This limitation hinders the usability of the data in cases where we need to locate specific feedback entries quickly or perform targeted analysis.

### Solution Brainstorm

**Proposed Solution**
I propose adding a search endpoint or extending the existing User Feedback API with search parameters. Key functionalities could include the ability to:

Search feedback by user ID or email.
Filter feedback by date range.
Search feedback content for specific keywords or phrases.
Filter feedback based on error context or metadata.
Sort results by relevance, date, or status (e.g., resolved/unresolved).

**Use Case**
This feature would greatly improve the efficiency of dashboards or systems that integrate Sentry’s User Feedback API by allowing us to pinpoint specific feedback entries and perform more detailed analysis. This would benefit both product teams and support engineers who need quick access to relevant feedback.

**Impact**
Enhancing the API with search capabilities will increase its flexibility, providing a more robust solution for organizations that rely on user feedback for decision-making and troubleshooting. It will save time and improve overall productivity by making feedback data more accessible.

**Alternatives Considered**
Currently, the workaround is to retrieve all feedback entries and filter them manually on our side. However, this is inefficient, especially as the volume of feedback grows.

**Additional Information**
Please feel free to reach out if additional clarification is needed regarding this feature request. We believe that adding search functionality to the User Feedback API will significantly enhance its utility for all Sentry users.

Thank you for considering this request.

### Product Area

User Feedback

**Comment by ryan953** [comment]
related to https://github.com/getsentry/sentry/issues/74113

**Comment by c298lee** [comment]
Hi @nurkilcadir, thanks for writing in! User feedback is actually implemented as an issue, so you would use the [issue search API](https://docs.sentry.io/api/events/list-a-projects-issues/) and filter for feedbacks. You can do that using `issue.category:feedback`, so your API call would look something like `https://sentry.io/api/0/projects/{organization_id_or_slug}/{project_id_or_slug}/issues/?query=issue.category:feedback`. We will add this info to our API documentation

**Comment by nurkilcadir** [comment]
Hello Catherine,

Thank you for your response :)
