### ISSUE TITLE
Navigate among adjacent issues faster (without loading each one individually)

### ISSUE THREAD

**Issue by cstavitsky** [getsentry/sentry#77982]
### Problem Statement

Opening this on behalf of a trialing customer.

Currently, navigating from one event to another within an issue requires each individual event to be loaded (purple spinner in video). Crashlytics, for example, has no lag when navigating among events.

https://github.com/user-attachments/assets/7b11e522-3e4d-42e9-a37c-f14a3c9ebcfe

### Solution Brainstorm

If possible, increase the speed at which individual events are loaded, without the delay.

### Product Area

Issues

**Comment by scttcper** [comment]
Added to our backlog

**Comment by roggenkemper** [comment]
This has been added! To try it out, turn on the EA flag in organization settings and opt into the new issue details experience (beaker in the top right corner of the issues page)
