### ISSUE TITLE
User defined timezone is not reflected in Organization views

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#78017]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to user settings and set your timezone to anything but UTC
2. Navigate through your organization's dashboard

### Expected Result

All timestamps show up in the selected timezone.

### Actual Result

All timestamps remain in UTC. Using an incognito window shows the timezone correctly, but clearing the browser cookies does not help.

It turns out the time zone is held in the local storage key `global-selection:ORG_SLUG`. Deleting it fixed the issue, but customers should not have to go through this process.

### Product Area

Settings

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2341) by [Unito](https://www.unito.io)

**Comment by InterstellarStella** [comment]
Hi @scttcper I was also not able to replicate the issue on my side but it happens to customers sometimes. The settings I am referring to are [here](https://sentry.io/settings/account/details/).
The issue always boils down to the browser cache not being updated.

**Comment by scttcper** [comment]
@InterstellarStella we would need to know which page since the timezone handling is done on the frontend, some of them may not be responsive to user settings changes.

**Comment by InterstellarStella** [comment]
@scttcper added more info in the [shadow ticket](https://getsentry.atlassian.net/browse/FEEDBACK-2341).

**Comment by leeandher** [comment]
The user likely has the UTC box checked in the date filiter. ![Image](https://github.com/user-attachments/assets/ba76ffbd-fec4-4b26-8018-c6bf053912bd) Many areas of the app pull date ranges from the settings configured here, so if that is checked, that might be why they are seeing UTC times, even if they don't have 'custom date range' selected. Areas in the app that don't pull dates from here should be respecting the users timezone preferences, so if that is the not the case please let us know.

**Comment by InterstellarStella** [comment]
Thanks for that @leeandher, I updated the customer but have not received a response for a few weeks now so we can close the issue for now.
