### ISSUE TITLE
Dashboards overlay toggle spillover to other widgets

### ISSUE THREAD

**Issue by realkosty** [getsentry/sentry#78072]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to https://demo.sentry.io/dashboard/108650/?end=2024-09-24T18%3A00%3A28&project=4504708328325120&start=2024-09-24T13%3A00%3A28
2. Scroll down to `[flask] /products -> /cart | Conversion` widget on the left
3. try to toggle/untoggle overlays to get this widget and the one right below it (`[flask] /cart -> /checkout | Conversion`) **to ONLY display the yellow line** (equation in the form of `count_if(...) / count_if(...)`

### Expected Result

same overlays in different widgets are toggled independently of each other

### Actual Result

a game of whack-a-mole

![Image](https://github.com/user-attachments/assets/f0717e86-5d0b-4df2-8f43-2b099cdb8b0a)

### Product Area

Dashboards

### Link

 https://demo.sentry.io/dashboard/108650/?end=2024-09-24T18%3A00%3A28&project=4504708328325120&start=2024-09-24T13%3A00%3A28

### Version

-

**Comment by realkosty** [comment]
a workaround that may be usable in some of the cases: put double quotes in one of the expression or something that makes it syntactically different yet return the same data.

**Comment by ale-cota** [comment]
Thanks for flagging, Kosty! Added to our backlog, we'll try to get this fixed soon.

**Comment by ale-cota** [comment]
hey, @nikkikapadia! Could you please verify that this issue is also fixed once you merge https://github.com/getsentry/sentry/pull/78675?
Thanks 🙏

**Comment by nikkikapadia** [comment]
Hey! yes this issue will be fixed when this gets merged :)
