### ISSUE TITLE
Linking Sentry issues to Pivotal returns a 500 Internal Server Error

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#78083]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Customer reported when they attempt to link a Sentry issue and a Pivotal Tracker issue, they run into error:
"There was an error linking the issue."
![Image](https://github.com/user-attachments/assets/1e2c4018-6a07-464d-a81a-0967ffe5e959)
and see the response: 500 (Internal Server Error). [This looks like the associated error](https://sentry.sentry.io/issues/5653926855/?project=1&query=user.email%3Asergous%40gmail.com&referrer=issue-stream&sort=date&statsPeriod=30d&stream_index=0) in Sentry. 

User is able to create a new Pivotal Tracker issue but unable to link an issue. 

I was unable to reproduce because I can't sign up for a Pivotal account, as it will [reach end of life April 30, 2025](https://www.pivotaltracker.com/blog/2024-09-18-end-of-life). 

### Expected Result

User is able to link a Sentry issue to a pivotal issue. 

### Actual Result

User is unable to link a Sentry issue to a pivotal issue. 

### Product Area

Settings - Integrations

**Comment by sentaur-athena** [comment]
Hi @kerenkhatiwada,
Pivotal is built on our old integrations platform which is deprecated (plugins). Unfortunately we don't provide support for plugins anymore. We recommend asking Pivotal to build a 3rd party integration using our [integration platform](https://docs.sentry.io/organization/integrations/integration-platform/) and we also welcome community contributions.
