### ISSUE TITLE
Sourcemaps Issue Grouping

### ISSUE THREAD

**Issue by priscilawebdev** [getsentry/sentry#78109]
- The same issue from dev and prod are not grouped together? For a new version, the same exception creates a new issue - why are they not grouped?

**Comment by priscilawebdev** [comment]
I was able to reproduce the issue using next.js. @armenzg  will check with his team to investigate why the 2x events aren't being grouped, despite using the updated version of the grouping algorithms.

For context, the event from the dev environment does not have source maps, while the one from the production environment includes them.

**Comment by lobsterkatie** [comment]
@priscilawebdev I think we solved this on Slack? If not, please feel free to re-open the issue.
