### ISSUE TITLE
Modifying uptime monitoring alert fails to save on first click

### ISSUE THREAD

**Issue by zhiyan114** [getsentry/sentry#78185]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create an uptime alert
2. Refresh inside the Alerts (not sure if it's necessary, but the issue arise after I left and came back to modify it)
3. Go to the alert that just created and click "Edit Rule"
4. Modify any parameters and click "Save Rule"

### Expected Result

The new modified parameter should be saved on first click.

### Actual Result

Observe the network request inside dev tool as the first request are made to `https://us.sentry.io/api/0`, causing CORS (as provided by the console `Access to fetch at 'https://us.sentry.io/api/0' from origin 'https://[OrgSlug].sentry.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.`)

Clicking on "Save Rule" again will now properly post the change under `https://us.sentry.io/api/0/projects/[OrgSlug]/[ProjectName]/uptime/[EventID]/`

### Product Area

Alerts

**Comment by rachrwang** [comment]
@gaprl - can you help take a look at this & assign to the right person? Thanks!

**Comment by gaprl** [comment]
Hi @zhiyan114 this issue has been resolved.
