### ISSUE TITLE
UI resets project selection causing "You do not have the multi project stream feature enabled" error

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#78207]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Open issues page
2. Select a project
3. Click on the issues page again

### Expected Result

no error

### Actual Result

The project selector resets and selects multiple projects, this feature is not available on a team plan causing the error message
More details (affected org and recordings) are in the shadow ticket due to PII

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2303) by [Unito](https://www.unito.io)

**Comment by scttcper** [comment]
I believe this should be working with the new issue views which will be in EA shortly. I'll pass this to the team and see if we can do anything until then.

**Comment by rodolfoBee** [comment]
@scttcper we had another organisation affected by this issue. The quicker we can have an update the better.

**Comment by roggenkemper** [comment]
We won't be releasing the updated issue views super quickly as they just hit EA, but I will look to see if I fix can be made for all other organizations.

**Comment by adnweedon** [comment]
I was just wondering if there were any updates on this; it's pretty irritating to keep getting the error! 🙂

**Comment by armenzg** [comment]
Michael may have a fix for this during this week.

**Comment by armenzg** [comment]
We're looking into it. Thank you for reporting!
