### ISSUE TITLE
Provide the option to opt out of uptime monitoring

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#78208]
### Problem Statement

Now that uptime monitoring is in open beta, customers can delete auto generated uptime alerts or block Sentry via `robots.txt`. It is currently not possible to completely turn off the feature.

### Solution Brainstorm

Create a toggle in the org or project settings that allows customers to opt out of uptime monitoring. This feature request is made on behalf of a customer.

### Product Area

Crons

**Comment by gaprl** [comment]
Hey @InterstellarStella, this is something we've considered (adding a global toggle to turn off uptime), however given that deleting the existing auto detected uptime alert effectively does the same thing, we've decided to not move forward with its implementation.
