### ISSUE TITLE
Performance "Best Page Opportunities" Links Broken (400)

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#78219]
### Problem Statement

![Image](https://github.com/user-attachments/assets/32a06b4b-bcee-4296-ab28-250193f95ca1)

When navigating to the Performance Page -> Select "Front End" and navigate to the "Best Page Opportunities" Widget, if you select any link contained within the widget you receive a 400 Page Not Found error and the following screen:

![Image](https://github.com/user-attachments/assets/91afd051-b815-4780-99b9-34220686ccb6)

The Browser Console Logs:

![Image](https://github.com/user-attachments/assets/2c67848b-f1bb-4db9-ac04-74bb088ce447)

If you select "View All" the url redirect is  https://organizationname.sentry.io/performance/undefined/browser/pageloads/

Selecting a Page the url redirect is  https://organizationname.sentry.io/performance/undefined/browser/pageloads/overview/?environment=production&project=numberhere&statsPeriod=24h&transaction=%Fpage%2Fhere

### Solution Brainstorm

Have the redirect function properly

### Product Area

Performance

**Comment by ReneGreen27** [comment]
To note, this was repeatable behavior tested on three different orgs

**Comment by ReneGreen27** [comment]
Also both on Firefox and Chrome

**Comment by DominikB2014** [comment]
@ReneGreen27 Hey! Thanks for pointing this out. I noticed an issue on our end that caused this bug, i confirmed and merged a changed that should resolve the issue. Let us know if you come across this again!
