### ISSUE TITLE
Team Admin - Debug Symbols cannot be download from project

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#78229]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Log in as a team admin
2. Go to project with debug symbols uploaded
3. Try to download one of the symbols

### Expected Result

I would expect to download the debug symbols because of the team admin role my user has like mentioned in the banner on the top of the first screenshot

### Actual Result

Looking into the issue about deleting this https://github.com/getsentry/sentry/issues/53919

I don't think the same goes for downloaded.

### Product Area

Settings - Members

### Link

Customer Link in Jira

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2304) by [Unito](https://www.unito.io)

**Comment by schew2381** [comment]
PR Fix is here: https://github.com/getsentry/sentry/pull/78279
