### ISSUE TITLE
How do you handle DSN key rotation?

### ISSUE THREAD

**Issue by primostasis123** [getsentry/sentry#78245]
Does Sentry only initialize once? I store my DSN key in AWS Secrets Manager and fetch the key in sentry.server.config in my Next JS. But what happens if my DSN is no longer valid because we change it? How do we reinitialize it when we encounter a log error or something similar?

**Comment by InterstellarStella** [comment]
Hi @primostasis123, the DSN should not become invalid unless you disable it through your project settings in the Sentry Web UI. In any case, if the Sentry SDK closes at any point for any reason, it can be reinitialized by calling `Sentry.init()`.
