### ISSUE TITLE
Limit Accces to Github integration repositories on Project level

### ISSUE THREAD

**Issue by mnordst5** [getsentry/sentry#78246]
### Problem Statement

When integrating GitHub with Sentry, there's currently no way to restrict each project's access to specific repositories. This means that all projects can create issues in any repository, which poses a significant challenge when dealing with large organizations. 
Ideally, there should be a solution that allows for project-level repository permissions or a similar mechanism.

### Product Area

Settings - Integrations

**Comment by cathteng** [comment]
Closing as a duplicate

**Comment by cathteng** [comment]
Unfortunately the team is understaffed and we can’t prioritize this fix
