### ISSUE TITLE
Timeout on issues endpoint when using `is:linked` filter

### ISSUE THREAD

**Issue by narsaynorath** [getsentry/sentry#78258]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Navigate to the Issues page
2. Add the `is:linked` filter (you may need to tweak your page filters)

### Expected Result

The query completes and returns issues.

### Actual Result

The query times out. The relevant issue and query can be found in this [Sentry issue](https://sentry.sentry.io/issues/5225260997/events/fc7a9101560549289461df2d940c26b3/?node=txn-57dfe4003ffb4b019e12bbeb2215d450&project=1)

This does seem like it depends on the amount of data being queried. e.g. by selecting a single project and scoping the date range to a lower amount (<7d) seems to work in most cases

### Product Area

Issues

**Comment by scttcper** [comment]
Looked into this a bit [the filter happens here](https://github.com/getsentry/sentry/blob/7e956e419c13cf96005e639c5a7beb39827092c1/src/sentry/search/snuba/backend.py#L102-L136) the main issue is always going to be that is:linked forces a postgres query. We have indexes on everything in the subquery except for sentry_grouplink.relationship but looking at this org with 80 sentry_grouplink's total shouldn't matter. [redash query](https://redash.getsentry.net/queries/7509/source)
