### ISSUE TITLE
Inconsistent session replay search results

### ISSUE THREAD

**Issue by masinette** [getsentry/sentry#78286]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. navigate to Session Replay main page
2. search `user.email is not "" `
3. compare results of this search to the unfiltered results

### Expected Result

All of the replays with a user email appear on the list for the `user.email is not "" ` search

![Image](https://github.com/user-attachments/assets/649a6c10-f994-4325-a6ed-891d567d50e4)

### Actual Result

Some results that appeared in the unfiltered search (and had a user email) do not appear in the filtered search

Unfiltered search:
![Image](https://github.com/user-attachments/assets/d96f1dd7-8a41-4bc5-b883-f6a38fdc9847)

Filtered search:
![Image](https://github.com/user-attachments/assets/f6b620bb-4144-4fdd-b626-7ec5a7227d84)

### Product Area

Replays

**Comment by jas-kas** [comment]
Hey @masinette 👋 

Thanks for raising this.

The inconsistent search results for the "`user.email is not ""`" search is indeed odd. I've been able to repro this on my laptop.

What is the use-case/rationale for someone searching for this?

**Comment by staticshock** [comment]
Filtering out users who are not signed in

**Comment by staticshock** [comment]
I also tried `user.ip is ""` and `user.ip is None`, since the list displays IPs when an email is not available, but both of those queries crashed. After that I ran out of steam looking for ways to get the output I was looking for.

**Comment by staticshock** [comment]
Also, it's not just the `is not` operator. `user.email is ""` returns weird results, too. In my project, that returns at least some rows where users clearly have an email.

**Comment by aliu39** [comment]
IP bug relates to https://github.com/getsentry/sentry/pull/69326/files

We're looking into both of these issues, thanks for reporting! @staticshock @masinette

**Comment by aliu39** [comment]
@staticshock the IP bug you discovered should be fixed by https://github.com/getsentry/sentry/pull/78642

**Comment by staticshock** [comment]
Thank you, after this release the issue appears fixed in production :)
