### ISSUE TITLE
Email Conditions

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry#783]
When should Sentry allow you to be notified?

- A new event (or regression)
  - Only new events which match tag=value (e.g. level=error)
- An event when it reaches a threshold of N times seen
  - Or when it reaches number of unique tags (e.g. 13 servers)
  - Or when it reaches number of values for a tag (e.g. 1000 times of level=error)
- Number of times seen increases by N in interval
- Global number of events increases by N in interval
- Global number of new events increases by N in interval

Right now it's easy to do 60 seconds as the interval, do we need more options than that? Should it be an average over a few minutes? If we need to compare w/ some kind of historical value things will be complicated. We also cant notify within seconds, only after 60 seconds of something happening.

Reply with a comment if you have any opinion.

Implementation notes:

- Add Plugin.should_notify, which will pass in the event and some metadata

**Comment by markushausammann** [comment]
Was this closed because it was implemented?

**Comment by dcramer** [comment]
Rules have been implemented for quite a while, yeah. It doesnt do all of these conditions, but it effectively solves this problem.

**Comment by markushausammann** [comment]
Ok, thanks.

**Comment by djmaze** [comment]
One thing I'd like to see is repeated notifications when exceptions occur again. E.g Errbit sends out notifications on the first occurrence, and then again on 10th, 100th and so on (independent of the time between occurrences).  This can not exactly be modeled with the current rules implementation, but I find it very useful.

A quick way to make this possible would be to allow setting a larger interval in the condition  "an event is seen more than {value} times in {interval}" - i.e. days, weeks, months. One would be able to create multiple rules for the different thresholds then, using e.g. a 1 week interval.
