### ISSUE TITLE
When there are no issues that match the filter, onboarding screen is shown, although project already has ingested a lot of events

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#78324]
E.g. with this filters: https://sentry.sentry.io/issues/?environment=00634c51eef2&project=-1&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&sort=date&statsPeriod=1m&viewId=55599

![Image](https://github.com/user-attachments/assets/dc281f84-d659-43b4-a5e7-b3e46e57056d)

**Comment by jangjodi** [comment]
I cannot replicate this issue, as when I click on the provided link I see the page saying we couldn't find any issues that match the filter. I'm going to close this for now, but please re-open it if it's still occurring
