### ISSUE TITLE
Opsgenie Integration API Key Invalid Error

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry#78441]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Steps to Reproduce:

Set up integration with Opsgenie using the provided API key from the Opsgenie/Jira Service Management (JSM) UI.
Follow the integration steps provided by both Sentry and Atlassian.
Attempt to send a test notification to Opsgenie through Sentry.

### Expected Result

The notification should successfully send to Opsgenie without error.

### Actual Result

Receiving the error: The provided API key is invalid. Please make sure that the Opsgenie API key is an integration key of type "Sentry" that has configuration access.

Please see internal Jira Issue for more information on the user case. 

### Product Area

Settings - Integrations

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2306) by [Unito](https://www.unito.io)

**Comment by sentaur-athena** [comment]
Looking at the Zendesk ticket looks like the customer found a workaround and this is not blocking them anymore. So adding it to backlog for investiagation.
