### ISSUE TITLE
Ignore spans, traces, everything for health checks

### ISSUE THREAD

**Issue by black-snow** [getsentry/sentry#78457]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I can't quite figure out if there's a way / what's the "canonical" way to filter out everything regarding health checks (or any other action you wan't to be silent). I don't need any APM on my health checks - they can go fully blind.

So far I've seen denyUrls, beforeSend, and server-side filtering, but I'm not sure *what* exactly they'll filter or if, for example, `/health` as a denyUrl would even work.

### How are you getting stuck?

Not quite sure what to use and to me this seems to be worth a small section in the docs as it should be a rather common case.

### Where in the product are you?

Performance

**Comment by dalnoki** [comment]
hey @black-snow thanks for reaching out! In general, I'd recommend enabling the _Filter out health check transactions_ within your project's Inbound Settings. [Here](https://docs.sentry.io/concepts/data-management/filtering/#transactions-coming-from-health-check) you can find information on what we consider to be a health check. Please note that this setting setting will only filter out transactions and not errors. Let me know if you have any additional questions on this!

**Comment by black-snow** [comment]
@dalnoki thanks for your reply!

I'd rather like to not collect and send stuff on this route in the first place. Sure, I could just `sentry.init` after the routing happens and do it within each rout but this is clearly not quite ideal. Isn't there a way to tell the SDK to ignore some routes, URLs, or to kida `sentry.stop()`? Not sure if it worked to just `del sentry` in my `/health` route.

**Comment by black-snow** [comment]
That's pretty much what my initial search yielded. [Filtering](https://docs.sentry.io/platforms/python/configuration/filtering/#filtering-transaction-events) will probably work, but it's some I have to do in the code and I also need to (re-) implement the sampling rate then. That's quite cumbersome - I have to go into every project and copypaste that in.

Would be nice to have some config option for this that I can configure from the outside - something like `SENTRY_IGNORED_PATHS=/a/b/c,/health` and Sentry would then automatically discard everything for these paths.

**Comment by black-snow** [comment]
imho this should get a label:"Type: Feature Request" - unless both of us are missing some detail here.

**Comment by black-snow** [comment]
Just found https://docs.sentry.io/concepts/data-management/filtering/#transactions-coming-from-health-check - seems to be exactly what I was looking for.

**Comment by black-snow** [comment]
Actually, it's not. What I'd like to do is not sending any data for, e.g., `/health` in the first place (so I don't have to pay for traffic that I'm sentry.io is going to trash then anyway).

So, feature request still valid.

**Comment by black-snow** [comment]
I'm surprised this ain't seem to be a more highly sought after feature request.
