### ISSUE TITLE
Assert that --queues argument(s) actually exist in codebase before starting celeryd.

### ISSUE THREAD

**Issue by JTCunning** [getsentry/sentry#7856]
Currently, if someone runs a celery worker with the argument:`--queues no-way-this-queue-actually-exists-yet`  RabbitMQ will create a queue with the default options, which will cause any future production to the queue to error if there is a configuration mismatch.

**Comment by BYK** [comment]
Not sure this is still important for prod but I think it can also help self-hosted so taking on.

**Comment by JTCunning** [comment]
It's still a "gotcha" for saas but we haven't been "got" in quite some time now. 🤞
