### ISSUE TITLE
Pagination should go to the first page when we update filters

### ISSUE THREAD

**Issue by Sereinity** [getsentry/sentry#786]
What I have done:

1. I open a project with a few (0) bookmarks
2. I browsed issues to bookmark some of them (using pagination)
3. From the last page (p=8 in the URL) I switched to bookmarked filter
4. Sentry display no issues and pagination is still on 8th page (p=8 in the page query)
5. I change the p=8 to p=1 in the URL → It now display my two issues

What it should do:

* Reset page number to the first one when updating filters

**Comment by benvinegar** [comment]
This is true as of Sentry 8.
