### ISSUE TITLE
[New Azure DevOps] Link UI not returning issues created after integration reauthorization

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#78628]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Reported by a user, and I am unable to reproduce with the old integration so it might be only affecting the new integration.

Azure tickets created by Sentry after the integration is updated no longer getting returned when trying to Link and search for them.

   1.  From a Sentry issue create an Azure DevOps issue by clicking on the plus symbol under the issue tracking section on the right side and the Create tab

 2. Go to another unlinked Sentry issue and click on the plus symbol.

 3. This time click on the Link tab, and try to search for the previously created issue.

### Expected Result

Should be able to find newly created issues and link them

### Actual Result

Link returns no results

### Product Area

Unknown

**Comment by Fwang36** [comment]
Routing to @getsentry/product-owners-settings-integrations for [triage](https://develop.sentry.dev/processing-tickets/#3-triage)

**Comment by sentaur-athena** [comment]
@Fwang36 Can you also please link to a Jira or zendesk issue where we can get the customer information to debug?

**Comment by Fwang36** [comment]
hey @sentaur-athena, here is the [Zendesk link](https://sentry.zendesk.com/agent/tickets/134140)

I did try to install the new integration but I wasn't able to sign in with my personal account upon clicking "Add Installation" and wasn't sure how to get past it.

**Comment by sentaur-athena** [comment]
Thanks for linking. Looks like they had the issue before the installation of the new integration as well. I'll comment on the zendesk ticket.

**Comment by Fwang36** [comment]
@rodissanayaka9 I've sent you a response in the ticket.

I'm closing this ticket as a duplicate of #77307 which was reported before the new integration was released

**Comment by rodissanayaka9** [comment]
Hi Francis,

The old ticket created no longer with us. Can you please continue this ticket. Still, I haven’t got any positive feedback for this ticket. I believe I can’t do anything from me to resolve this type of issue. If there any, please let me know.

Roshan


[cid:ignored-in-diff-32373043-CA19-4E9B-A694-73BABFB6D10E]
Roshan Dissanayaka​​​​
Senior Cloud Administrator ‑ Azure
[cid:ignored-in-diff-2AE76BD1-2D43-4B34-A0EF-81EAF5CA7525]
(+94) 770 325 771<tel:(+94)%20770%20325%20771>

[cid:ignored-in-diff-5A50E8ED-755E-4E1B-A040-500480D3C9A4]
***@***.******@***.***>

The content of this email is intended for the person or entity to which it is addressed only. This email may contain confidential information and we do not waive any confidentiality, privilege of copyright associated with it. If you are not the person to whom this message is addressed, be aware that any use, reproduction, or distribution of this message is strictly prohibited. If you received this in error, please contact the sender and immediately delete this email and any attachments.

________________________________
