### ISSUE TITLE
"Invalid Minidump" error on valid minidumps

### ISSUE THREAD

**Issue by masinette** [getsentry/sentry#78624]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

The Issue has events that are  marked <.unknown>: invalid minidump
They are valid and resymbolicate locally without issue. 

### Expected Result

valid minidumps are not marked as invalid

### Actual Result

valid minidumps are marked as invalid

### Product Area

Other

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2310) by [Unito](https://www.unito.io)

**Comment by loewenheim** [comment]
This has been rectified in the UI, see https://github.com/getsentry/sentry/issues/78766.
