### ISSUE TITLE
Delete release artifact modal does not support keyboard interaction

### ISSUE THREAD

**Issue by cameronmcefee** [getsentry/sentry#7864]
On the release artifacts page, click the trash can button to delete an artifact. A confirmation modal appears.

Expected: Hit enter to accept
Actual: Nothing

**Comment by dev-drprasad** [comment]
I am new to sentry. but i know React. I am interested to take this issue. I need some help. How to navigate to that modal ?? I am unable to find in UI exactly where it is located. In code it should be `sentry/static/app/views/releaseArtifacts.jsx` (correct me if am wrong)

**Comment by dev-drprasad** [comment]
I think i found the solution. adding `autoFocus` to primary button makes enter to perform action. Since  release artifacts page using reusable `Confirm` component, Making a change to `Confirm` component affect all other components. is that okay ??

**Comment by billyvg** [comment]
I believe a lot of `Confirm` modals are for destructive actions - do we want default action to "confirm" vs "cancel"?

If that's the case we would probably want `tabindex` = `1` for cancel and `2` for confirm. Thoughts @cameronmcefee ?

**Comment by cameronmcefee** [comment]
¯\_(ツ)_/¯ I could argue it either way. My instinct to hit enter to confirm is what brought me here, but I can definitely see the argument for making the default to cancel. I guess if we have an existing paradigm we ought to stick with it.

**Comment by dev-drprasad** [comment]
@cameronmcefee @billyvg  In my opinion, if user press `enter`, his intention will be to perform primary action (can be destructive action/ create action). Mostly people use `esc`  to cancel action. I think we can use primary action as default. correct if i am wrong

**Comment by billyvg** [comment]
Yeah that sounds good

**Comment by dev-drprasad** [comment]
@billyvg Can I raise pull request for this ?

**Comment by billyvg** [comment]
Yes, please do!

**Comment by dev-drprasad** [comment]
@billyvg i raised pull request. its very small change
