### ISSUE TITLE
Query for Matching Events Returns No Results

### ISSUE THREAD

**Issue by Kobby-Bawuah** [getsentry/sentry#78659]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

- Go to the issue stream in Sentry.
- Add the search term "internal" or any other term in the search bar.
- Click on the "matching events" option under the affected users section for one of the events.
- Observe that it shows "No results found for your query" in the subsequent window.

### Expected Result

The list of events that matched the filter should display properly.

### Actual Result

No results are returned despite showing X matching events initially.

![Image](https://github.com/user-attachments/assets/35d2eb31-9b89-42ba-ad00-c1f0ec85fa6b)

![Image](https://github.com/user-attachments/assets/09be2194-a1c8-488b-bc10-2a3a34f4847e)

### Product Area

Issues

**Comment by scttcper** [comment]
Discover can't use `issue.priority` at the moment, we should probably remove it or inform the user

**Comment by Kobby-Bawuah** [comment]
Hey @scttcper, 

We have a user who is difficult to work with. Do you mind elaborating on how `issue.priority` factors into the number being wrong?

**Comment by scttcper** [comment]
@Kobby-Bawuah discover uses a different dataset that is only aware of certain values that appear at the event level. We should remove issue.priority for you when clicking the link since filtering since all event within a single issue have the same priority.

**Comment by Kobby-Bawuah** [comment]
@scttcper Oh okay. Thanks for clarifying. We will be on stand-by for the fix.
