### ISSUE TITLE
GitHub Integration Problem - Github issue not linked to sentry issue

### ISSUE THREAD

**Issue by fendtinger** [getsentry/sentry#78667]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. create test issue
2. let sentry create a github issue automatically (via alert)
3. issue is created but sentry issue is not linked to the issue.

### Expected Result

Sentry issue should be linked to the created issue

### Actual Result

![Image](https://github.com/user-attachments/assets/9b67b61d-5d61-49ca-af7e-803937db5744)
![Image](https://github.com/user-attachments/assets/3834ddd5-6328-498b-bc55-4de060e67df8)
![Image](https://github.com/user-attachments/assets/c792901e-2d1d-4fe6-b69b-6e7431223147)

### Product Area

Unknown

### Link

https://lifeguardmedia.sentry.io/alerts/rules/equicert-dev/14663437/

**Comment by sentaur-athena** [comment]
Thanks for reporting. We're looking at this and provide an update soon.
