### ISSUE TITLE
Discover tab Filters do not match URL

### ISSUE THREAD

**Issue by qualityjohn-sc** [getsentry/sentry#78676]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a discover view that uses the environment filter to show only issues from a single env (e.g. Production)
2. Select "Save as default"
3. Change the filter to a new environment (e.g. Staging)
4. Navigate away from the discover page (e.g. open the Profiles page)
5. Return to the discover page

### Expected Result

The page loads the filter that was saved as default and the filter settings are reflected in the UI

### Actual Result

The saved filter results are loaded with the Production data, but the UI shows the selected filter as Staging

### Product Area

Discover

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2313) by [Unito](https://www.unito.io)

**Comment by Dhrumil-Sentry** [comment]
Thanks for the bug report, we'll add this to the backlog

**Comment by shruthilayaj** [comment]
fixed in https://github.com/getsentry/sentry/pull/81361
