### ISSUE TITLE
[Issues Search] 'Hydration' search shows no results despite hydration errors being in the project

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#78729]
Search condition applied: https://sentry.sentry.io/issues/?project=1267915&query=hydration&referrer=issue-list&sort=date&statsPeriod=90d&viewId=default0

Existing hydration error issue in Sentry: https://sentry.sentry.io/issues/5459161744/?project=1267915

**Comment by jas-kas** [comment]
cc/ @roggenkemper @snigdhas

**Comment by percyhanna** [comment]
What is the bug you are seeing? I wonder if it's similar to a bug/regression I've seen recently, where links to search results lose their `query` params and reset to a default search. Possibly related to https://github.com/getsentry/sentry/pull/78762.

**Comment by mrduncan** [comment]
I'm no longer able to repro this - going to close it for now but please reopen if you're still seeing it.
