### ISSUE TITLE
Slack Integration: 

### ISSUE THREAD

**Issue by lukemoore** [getsentry/sentry#7873]
Hi, I'm having trouble setting up the new Slack integration to work with private channels.
- With the legacy integration we had Sentry sending messages into private channels.
- When authorizing the Slack app I selected "Specific channels" and entered the names of the private channels, as well as "slackbot, which is private to you"..
- The authorization appeared to succeed.  After authorizing I saw a message `Sentry APP [2:39 PM]
was added to this conversation by Luke Moore.` in those channels.
- When editing the alert rule I've set the "take these actions" to send a notification to the private workspace but I see the error: 'The slack resource "website-private" does not exist or has not been granted access in the SideFX Slack workspace.'  I've tried with and without a leading "#".

Am I doing something wrong?
![image](https://user-images.githubusercontent.com/6863550/38211023-2492766c-3687-11e8-9a6f-2715dd542580.png)
![image](https://user-images.githubusercontent.com/6863550/38210995-0cdbf4da-3687-11e8-9504-6c66a44feb04.png)

**Comment by Otienoh** [comment]
You have to invite Slack bot in your channel

> /invite @Sentry
