### ISSUE TITLE
Enhancement: investigate use of sentry.utils.http functions

### ISSUE THREAD

**Issue by aliu39** [getsentry/sentry#78801]
https://github.com/getsentry/sentry/blob/0fea05bea3b7fcc2d0c79e36d63e0604525548e5/src/sentry/utils/http.py#L1

Seems like these functions could simplify our allowed origins check, and be consistent with the way the rest of Sentry does it. They might have extra considerations we haven't thought about.

Mainly:
`origin_from_request`
`is_valid_origin`

**Comment by billyvg** [comment]
@aliu39 Another quick investigation task to look into/close this week
