### ISSUE TITLE
Issue Page Error "You do not have the multi project stream feature enabled"

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#78807]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

- Select Issues in the lefthand column
- Intermittently Error "You do not have the multi project stream feature enabled" will occur, selecting "Retry" never results in the error going away
- You can see that no projects are selected, manual selection of the project, refreshing the page multiple times, or reselecting "Issues" all will successfully load the page
- This occurs on team plans
- Reproducible in most recent Chrome browser version

This is identical to what is being described in this previous Github Issue https://github.com/getsentry/sentry/issues/58961

![Image](https://github.com/user-attachments/assets/5eef8b9e-4a3d-4373-9116-649539f4c2ec)

### Expected Result

Default project to be selected automatically  since "All Projects" shouldn't be possible on Free Dev or Team plans so no error occurs. 

Can find org example in internal ticket #134646

### Actual Result

error message intermittently since "all projects" selection is not possible on Team plan

### Product Area

Issues

**Comment by MichaelSun48** [comment]
Hey @ReneGreen27, this is a [known issue](https://github.com/getsentry/sentry/issues/78207). I'll be taking a look at this today or tomorrow and will try to provide a fix.

**Comment by Skyppid** [comment]
Experiencing the same issue on Firefox as of today...

**Comment by armenzg** [comment]
We will be using the other issue to track this.
