### ISSUE TITLE
Almost impossible to debug auto resolving.

### ISSUE THREAD

**Issue by skbogner** [getsentry/sentry#78822]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Hi,

As we're developing our integration at Linear we've seen some issues around auto resolving. If an issue auto resolves in Sentry it appears to not resolve in Linear as it should. There's no way to reliably debug this at the moment. The current theory is that we are not receiving a webhook when Sentry auto resolves an issue (maybe only sometimes?), but this feels almost impossible to verify.

### How are you getting stuck?

Currently you have to set up a separate project (because you can only install the development integration in our organization as it's developed there) and feed issues into it somehow. Then you have to set auto resolving to 1 hour (lowest bound). And then you have to wait and hope. There's no way to tell in the Sentry UI if anything recently autoresolved other than clicking through individual issues to find one that did and then trying to line that up.

This makes it incredible hard to correlate auto-resolutions with possibly missing webhooks.

A few things that could make this easier:
- Allow setting a super low auto resolution (behind some development setting maybe?) (1min)
- Allow creating fake issues in a project directly from the UI. This would make setting up projects to test against much faster.

### Where in the product are you?

Unknown

**Comment by skbogner** [comment]
cc @sentaur-athena @gauthamcs

**Comment by sentaur-athena** [comment]
@skbogner thanks for the feedback. The team is prioritizing building better debugging instrumentation for 3rd party apps in Q1, so I add this ask to the backlog and we get back to it later this year during planning.

>The current theory is that we are not receiving a webhook when Sentry auto resolves an issue (maybe only sometimes?)
If this is a fact, it's a bug we should look into.

**Comment by sentaur-athena** [comment]
@skbogner we looked at it and verified the bug. Auto resolve does not trigger a webhook now. We will work on a fix soon and post an update.

**Comment by sentaur-athena** [comment]
@skbogner the fix is launched 2 days ago. Auto-resolve is now triggering the webhook the same way as resolve does.
