### ISSUE TITLE
Slack Integration: authorization failure

### ISSUE THREAD

**Issue by markwoon** [getsentry/sentry#7886]
Tried to configure the new Slack integration but failed when attempting to connect Sentry to Slack workspace.  Error message:

```
Invalid permissions requested
Invalid scope: users:readchat:write
```

If it makes a difference, my workspace is on a Slack Enterprise Grid.  I am the admin of my workspace and have configured other integrations before.

**Comment by EvanPurkhiser** [comment]
Thanks

Issue was introduced here https://github.com/getsentry/sentry/commit/28f63dbf1c570868d1a845e932075636cc28f5ff and is fixed in https://github.com/getsentry/sentry/commit/18ae4993bc0a55ecfb9b50b094bbe1c2a2aafc4c which is going out right now :)
