### ISSUE TITLE
Href broken for Alert in project settings (sentry web)

### ISSUE THREAD

**Issue by surculus12** [getsentry/sentry#7898]
Sentry version 8.22.0

Sentry et al. is running in docker.

This is a fresh setup and newly created project.

Href for `/sentry/<project>/settings/alerts/` is missing a `/` in the prefix in (as far as I can tell) all `/sentry/<project>/settings/*` sites, resulting in 404.

That is, the anchor elements looks like `<a href="sentry/<project>/settings/alerts/">Alerts</a>` resulting in a redirect to `/sentry/<project>/settings/sentry/<project>/settings/alerts/`.

**Comment by billyvg** [comment]
Thanks, this is fixed on `master` but we have not tagged a new release since 8.22.0 with the applied fixes

**Comment by billyvg** [comment]
Track https://github.com/getsentry/sentry/issues/5741 for the next release
