### ISSUE TITLE
App installation verification breaks OAuth token refreshes on EU instances

### ISSUE THREAD

**Issue by guillaumelachaud** [getsentry/sentry#78989]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

- Initiate an app installation in a EU Sentry instance
- Exchange the installation code against an access/refresh token pair
- Notice how the token is valid, can be refreshed several times and can be used to make successful API calls
- Validate the installation with `PUT https://sentry.io/api/0/sentry-app-installations/<installation_id>` and body `{"status": "installed"}`
- Notice how the token still works
- Refresh the token as usual: a new access/refresh pair is issued successfully
- Any calls with this access token fails with a 401 `{"detail":"Invalid token"}`
- Subsequent refreshes are still successful but the token issued remain invalid.

### Expected Result

- Validating the installation should not break token refreshes
- Token refreshes should not return a successful 200 if the provided token is actually invalid

### Actual Result

After refreshing the token, all subsequent calls will fail with 401 `{"detail":"Invalid token"}`.

I can reproduce this behavior using curl commands or with a REST client on Sentry **EU** instances only. Doing the same flow ona Sentry US workspace works flawlessly.

### Product Area

Settings - Integrations

**Comment by guillaumelachaud** [comment]
cc @sentaur-athena We have stumbled upon this problem when working on the Linear integration but I can reproduce with a newly created integration for repro purposes.

**Comment by sentaur-athena** [comment]
Thanks for detailed repro steps. We will look into it.

**Comment by ameliahsu** [comment]
@guillaumelachaud Just to get more details, what specific URLs are you calling with the access token?

**Comment by guillaumelachaud** [comment]
> Thanks for detailed repro steps. We will look into it.


`POST https://sentry.io/api/0/sentry-app-installations/<installation_id>/authorizations/` to get the tokens
`PUT https://sentry.io/api/0/sentry-app-installations/<installation_id>/authorizations/` to verify the installation
`GET https://sentry.io/api/0/issues/<issue_id>/` to get an issue

**Comment by ameliahsu** [comment]
I was able to reproduce this issue with the issues endpoint that you specified. This endpoint only works for querying issues within our US region. We now recommend using `GET https://sentry.io/api/0/organization/<org_id_or_slug>/issues/<issue_id>/`, which queries both our US and EU regions.

We are working on updating our documentation to provide support for our region-specific endpoints. Sorry for the confusion!

**Comment by ameliahsu** [comment]
@guillaumelachaud I was able to reproduce this issue with the issues endpoint that you specified. This endpoint only works for querying issues within our US region. We now recommend using `GET https://sentry.io/api/0/organization/<org_id_or_slug>/issues/<issue_id>/`, which queries both our US and EU regions.

We are working on updating our documentation to provide support for our region-specific endpoints. Sorry for the confusion!

**Comment by guillaumelachaud** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/2076017?s=64&amp;u=67e0367f706ef05242ce7c242fa45ccd1926c42e&amp;v=4">@guillaumelachaud](https://github.com/guillaumelachaud) I was able to reproduce this issue with the issues endpoint that you specified. This endpoint only works for querying issues within our US region. We now recommend using `GET https://sentry.io/api/0/organization/<org_id_or_slug>/issues/<issue_id>/`, which queries both our US and EU regions.
> 
> We are working on updating our documentation to provide support for our region-specific endpoints. Sorry for the confusion!

Does this apply to all endpoints, including `/sentry-app-installations` ?

**Comment by ameliahsu** [comment]
> POST https://sentry.io/api/0/sentry-app-installations/<installation_id>/authorizations/ to get the tokens
PUT https://sentry.io/api/0/sentry-app-installations/<installation_id>/authorizations/ to verify the installation
GET https://sentry.io/api/0/issues/<issue_id>/ to get an issue

@guillaumelachaud Of the endpoints you mentioned, only the`/issues` endpoint needs to be updated

**Comment by guillaumelachaud** [comment]
> > POST [sentry.io/api/0/sentry-app-installations](https://sentry.io/api/0/sentry-app-installations/)<installation_id>/authorizations/ to get the tokens
> > PUT [sentry.io/api/0/sentry-app-installations](https://sentry.io/api/0/sentry-app-installations/)<installation_id>/authorizations/ to verify the installation
> > GET [sentry.io/api/0/issues](https://sentry.io/api/0/issues/)<issue_id>/ to get an issue
> 
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/2076017?s=64&amp;u=67e0367f706ef05242ce7c242fa45ccd1926c42e&amp;v=4">@guillaumelachaud](https://github.com/guillaumelachaud) Of the endpoints you mentioned, only the`/issues` endpoint needs to be updated

Are you planning to add an `organizationId` field in the verify response payload? This would allow us to capture the `organizationId` as part of the OAuth flow. Currently, it only returns the slug. We can use the slug to construct the new URLs, but the slug is mutable by the end user so we'd rather rely on the organization ID instead of handling these changes.

**Comment by sentaur-athena** [comment]
Yes, ideally all the endpoints returning slug should also return ID. Unfortunately. some of the endpoints are old and don't follow this standard though. You mean the oauth/token/ endpoint?

**Comment by ameliahsu** [comment]
@guillaumelachaud I just added `id` to the response payload under `organization`. Returning to the original issue, did using the updated endpoint fix the 401 you were receiving?

**Comment by guillaumelachaud** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/2076017?s=64&amp;u=67e0367f706ef05242ce7c242fa45ccd1926c42e&amp;v=4">@guillaumelachaud](https://github.com/guillaumelachaud) I just added `id` to the response payload under `organization`. Returning to the original issue, did using the updated endpoint fix the 401 you were receiving?

We have completed the rollout of the fix on our end. We have seen a sharp drop in 401 errors so I think we can close this issue here.
