### ISSUE TITLE
Dashboard - Using custom tag in filter in Big Number Widget of custom measurement shows no results

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#78991]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Have a Big number widget based on Transaction data
2. p90 of custom measurement send in
3. using 1 default tag like os.name and 1 custom tag for example CustomerType

The table shows empty
Customer example in the linked Jira issue

### Expected Result

Data to be shown
This already works when I remove the custom tag from the filter
Also when you go into Discover you can see that there is definitely data.

### Actual Result

Number stays on 0.00ms even though Discover has data 

### Product Area

Dashboards

### Link

See jira issue

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2319) by [Unito](https://www.unito.io)

**Comment by narsaynorath** [comment]
Thanks @Angelodaniel, I think this is a possible bug with on-demand. I'm going to add it to the Dashboards project board so we have visibility. YYZ is off on Monday so I'm going to raise this in our weekly meeting on Tuesday. I'll look today and see if this is something that can be quickly fixed before then, otherwise we'll triage it and have a better estimate of the fix for this.

**Comment by Angelodaniel** [comment]
@narsaynorath - Thank you 🙏 I think we might have a wider issue than just the big number:
We’re not getting any data for some of our measurements and throughputs when on the dashboard, but on discovery we’re getting the data. I’ve added a workaround by forcing the data to be sorted by a field (environment) and now it’s able to get the data.
Here’s one of the dashboards (Link in Jira issue) that have this issue. You can see all the way to the bottom there are 2 Widgets Web Vitals and Web Vitals (no workaround), they’re supposed to have the same data, but the no workaround one doesn’t get any data. The throughput widget we have here also is working right now because I also applied the same workaround, but if I remove the workaround it would also not be able to get the transactions data.

**Comment by narsaynorath** [comment]
I'm going to close this off because we identified that this issue was related to our discover split work, which was fixed, but the reporting organization was reaching on-demand widget limits with this. Please re-open if this isn't the case.
