### ISSUE TITLE
Issues API Returns 404

### ISSUE THREAD

**Issue by kylannjohnson** [getsentry/sentry#79032]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. run `curl -I -H "Authorization: Bearer <token>" https://sentry.io/api/0/organizations/<org-slug>/<project-slug>/issues/` 

if you exclude the project-slug, the API returns issues

### Expected Result

I'm expecting a response in the shape specified in this API doc: https://docs.sentry.io/api/events/list-a-projects-issues/

### Actual Result

The curl command above returns a 200 on the connection establishment and a 404 on the api request.  Removing project-slug returns correct json.

### Product Area

APIs

**Comment by jangjodi** [comment]
Hi @kylannjohnson, I believe the url should be `https://sentry.io/api/0/projects/{organization_id_or_slug}/{project_id_or_slug}/issues/`, instead of `https://sentry.io/api/0/organizations/<org-slug>/<project-slug>/issues/` (replace `organizations` with `projects`). Please let me know if this helps!
