### ISSUE TITLE
[EPIC] Quick Start Guide Improvements

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#79079]

**Comment by priscilawebdev** [comment]
closing this as we are now using the EPD projects board instead: [https://github.com/orgs/getsentry/projects/266/views/20?sliceBy%5Bvalue%5D=Telemet[…]nce&pane=issue&itemId=83051870&issue=getsentry%7Cprojects%7C225](https://github.com/orgs/getsentry/projects/266/views/20?sliceBy%5Bvalue%5D=Telemetry+Experience&pane=issue&itemId=83051870&issue=getsentry%7Cprojects%7C225)
