### ISSUE TITLE
Search puts cursor on the left side of logical operator after 'enter' is pressed

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#79078]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

![Image](https://github.com/user-attachments/assets/7e56b1c9-22e8-4c93-8faa-c2423a68e5c3)

I'm creating a dashboard and adding a series of search filters. They are all `or`. Every I write `or` and press 'enter'. The cursor goes to the left of the `or` operator. So if I continue to type, it ends up with a broken query

1![Image](https://github.com/user-attachments/assets/66040292-f507-4f90-a02e-712164ae0ce7)
2![Image](https://github.com/user-attachments/assets/c52e6f68-bd8c-4f61-8c34-549a15b5783d)
3![Image](https://github.com/user-attachments/assets/ecbd4df2-1e8a-47dd-ad27-e4b495059d31)

### Expected Result

When I hit 'enter' the `or` operator is added, and the cursor is added to the write of it so I can continue to type my quary

### Actual Result

as described above

### Product Area

Dashboards

**Comment by ale-cota** [comment]
This issue is in the search component and reproducible in other parts of the product, not just dashboards.
