### ISSUE TITLE
Event detail -> Screenshots - show a carousel so we can quickly cycle through the screenshots

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#79076]
### Problem Statement

When trying to understand how the UI connects to the issue, through looking at screenshots. It would be ideal to be able to quickly cycle through the screenshots.

In the current beta experience, screenshots (which require URL hacking since clicking on Attachments open Tags) show a list.
And one needs to hit `Preview` one by one as the images stack on top of each other.

![Image](https://github.com/user-attachments/assets/d936d55c-ced5-434f-a304-aeebea93617d)

Link to example: https://sentry.sentry.io/issues/5987813063/attachments/?attachmentFilter=screenshot&node=error-cfa4cebfdec847f4910ba5dde06201fd&project=5905698&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=1h&stream_index=0

### Solution Brainstorm

Relates to:
* https://github.com/getsentry/sentry-unity/issues/1827#issuecomment-2408787640

### Product Area

Unknown

**Comment by jangjodi** [comment]
Thanks for suggestion! I will add this to our backlog

**Comment by UrbanNuke** [comment]
Any news? Out self-hosted sentry a little bit shocked by it

**Comment by jangjodi** [comment]
Hi [UrbanNuke](https://github.com/UrbanNuke), unfortunately we have no updates on this

**Comment by bruno-garcia** [comment]
Looks like we gate the preview by `isMobile`:

https://github.com/getsentry/sentry/blob/ec05e95588181966ded878090b1241e3b3fb2775/static/app/views/issueDetails/groupEventAttachments/groupEventAttachmentsFilter.tsx#L51C15-L51C31

We have other platforms that are not mobile, such as Unity (can be desktop, web, console) as well as Nintendo which can have screenshots.

Could we always show this, or only show it if we see an attachment with name containing `screenshot`? 
Screenshots are convention based, if name is screenshot.(jpg|png) we show the preview in the issue details.

**Comment by bruno-garcia** [comment]
This is used by: https://github.com/getsentry/sentry/blob/master/static/app/utils/platform.tsx#L8C21-L8C39

And defined on:
https://github.com/getsentry/sentry/blob/cd955ea612a79eaeabc59ff2b6180cdeb6eabb89/src/sentry/utils/platform_categories.py#L53
https://github.com/getsentry/sentry/blob/master/static/app/data/platformCategories.tsx#L37

This approach is not ideal because the outcome of saying something "is mobile" isn't super clear. We'll add Nintendo Switch there to get the screenshots, but this could have negative side effects.

We should instead have a `has_screenshot` support list.

**Comment by bruno-garcia** [comment]
Talked to @scttcper on Slack about this, the idea is to remove this filter to simplify things and have the "screenshot" filter show up on all platforms.

**Comment by bruno-garcia** [comment]
Resolved here:
* https://github.com/getsentry/sentry/pull/82046
