### ISSUE TITLE
Transaction duration is shorter than its child spans total duration

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#79081]
### How do you use Sentry?

Sentry Saas (sentry.io)

### Version

 2.16.0

### Steps to Reproduce

Run the following script:
```
import sentry_sdk
import time

def short_duration():
    time.sleep(1)
    return

def long_duration():
    time.sleep(2)
    with sentry_sdk.start_span(name="Short"):
        short_duration()
    with sentry_sdk.start_span(name="Short"):
        short_duration()
    with sentry_sdk.start_span(name="Short"):
        short_duration()
    with sentry_sdk.start_span(name="Short"):
        short_duration()
    return

sentry_sdk.init(
    dsn="...",
    traces_sample_rate = 1.0,
    debug=True
)

with sentry_sdk.start_transaction(op="task", name="Long duration"):
    long_duration()

sentry_sdk.flush()
```

### Expected Result

The Transaction "long duration" to be 6 seconds long (2+4x1) 

### Actual Result

The full trace is 6 seconds as I expect, but the transaction is only 1 second long. [Link to event on my test organisation.](https://dev-curumas.sentry.io/performance/trace/a865410b43524368ba6f360301e7a24e/?fov=0%2C6019&node=txn-1bb317c31f4d4b33ad018bbaaa615219&project=5225844&query=&referrer=performance-transaction-summary&showTransactions=recent&source=performance_transaction_summary&statsPeriod=7d&timestamp=1728885406&transaction=Long%20duration&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29)

This also affects a user on v1.40.6 of the SDK. Link to the event + screenshots can be found on this [internal ticket](https://sentry.zendesk.com/agent/tickets/134925).

**Comment by Dav1dde** [comment]
From the Relay side everything looks to be in order 👍

**Comment by shruthilayaj** [comment]
@rodolfoBee Looks like the issue has been fixed, I haven't able to reproduce it (@JonasBa or @Abdkhan14 probably fixed it sometime this past week)
 ![Image](https://github.com/user-attachments/assets/1246c7f9-37ae-44f7-b64d-e95fb9cffa4d)
