### ISSUE TITLE
Apply minimal number of users in Crash Free Session Rate Alert

### ISSUE THREAD

**Issue by JankoLancer** [getsentry/sentry#79082]
### Problem Statement

We use the Crash Free Session Rate Alert to trigger Pager incidents when the rate falls below a certain threshold. While this works well overall, we receive alerts during times when there are only a few users on the platform. In these instances, even a single user experiencing a crash can trigger an alert.

We would like to request an option to set a minimum number of users affected by crashes within a specified interval before an alert is triggered. This would help prevent unnecessary alerts during periods of low user activity.

### Product Area

Alerts

**Comment by ceorourke** [comment]
Hey @JankoLancer - have you tried the "crash free user rate" option? When you're creating an alert you can select it from the sidebar like this:

![Image](https://github.com/user-attachments/assets/2ab55f5a-7ddd-482a-b664-d61859e4fb83)

or if you're editing an existing alert, you can select it from the dropdown like this:
![Image](https://github.com/user-attachments/assets/ffd08433-5f25-4786-851e-665bfd300471)

Or is there a reason this doesn't meet your needs?

**Comment by ceorourke** [comment]
Closing as we have this feature and there hasn't been a response.
