### ISSUE TITLE
Replays tab on Transaction summary doesn't load the count

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#79086]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

[Slack thread](https://sentry.slack.com/archives/C03USURCFBJ/p1728914108645249)

Looking at errors on this endpoint, no huge amount of events. Searching by the user who reported I found no events.

https://sentry.sentry.io/issues/?project=1&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20transaction%3A%2Fapi%2F0%2Forganizations%2F%7Borganization_id_or_slug%7D%2Freplay-count%2F&referrer=issue-list&sort=date&statsPeriod=14d&viewId=default0

### Expected Result

Count loads

### Actual Result

![Image](https://github.com/user-attachments/assets/b7489e36-13a3-4aa2-b208-fb65fb8a3ebe)

### Product Area

Replays

### Link

https://sentry-sdks.sentry.io/performance/summary/replays/?project=5572016&statsPeriod=90d&transaction=GET%20https%3A%2F%2Fapp.test%2Fhome%2Fhttp

**Comment by bruno-garcia** [comment]
Happens also with this other Project (.NET): https://sentry-sdks.sentry.io/performance/summary/replays/?project=6601807&query=http.method%3APATCH&statsPeriod=90d&transaction=PATCH%20%2Fassessment%2Finstance%2F%7BinstanceId%7D

Seems like we have some type of filter that's not applied for mobile projects?

**Comment by michellewzhang** [comment]
seems like this is a problem in general, not specific to one project or due to not filtering mobile projects. we're not filtering by project properly in general, e.g. here where we display `javascript` replays for our jest project:
 https://sentry.sentry.io/performance/summary/replays/?project=4857230&query=&statsPeriod=3d&transaction=Profile%20%3E%20Empty%20profile%20duration%20is%20not%20infinity

**Comment by michellewzhang** [comment]
seems like the replay count badge is buggy in general: here it shows 0 replays but the list is not 0.
![Image](https://github.com/user-attachments/assets/b85f05b3-9ba8-4564-b5be-4ff3338ea3d2)

**Comment by michellewzhang** [comment]
turns out it's a problem with our query. fixing this in https://github.com/getsentry/sentry/pull/79140
