### ISSUE TITLE
Showing absolute time on viewing multiple session replays

### ISSUE THREAD

**Issue by joshnice** [getsentry/sentry#79176]
### Problem Statement

When I am looking through multiple user session replays on the session replay dashboard I want to be able to see the exact time the session replay was. 

### Solution Brainstorm

You already have this information as when you hover over the "2 months ago" it shows the exact time! Being able to see this without having to hover over the time would be really helpful and improve the efficiency I can navigate that dashboard. 

![Image](https://github.com/user-attachments/assets/49c1524d-df97-410a-8f51-aa35843c820e)

### Product Area

Replays

**Comment by billyvg** [comment]
Thanks for the report, I can see the usefulness, but this is not likely something we'll change as we want to maintain UI consistency throughout our app. I'm going to close this but we can revisit if see more interest down the road.
