### ISSUE TITLE
Improve GraphQL Request Grouping by Extracting Query Endpoints in Request Insights

### ISSUE THREAD

**Issue by serglom21** [getsentry/sentry#79216]
### Problem Statement

Currently, Sentry's request insights module groups all GraphQL requests together under a single /graphql endpoint, even though these requests contain different query endpoints. This grouping makes it difficult to quickly identify latency or performance issues for specific GraphQL queries, requiring users to open the group and manually inspect each trace. This hampers efficiency in debugging and monitoring application performance.
![Image](https://github.com/user-attachments/assets/2be6abee-3a81-4b2b-89ba-f349d9541852)

### Solution Brainstorm

Extract and display the specific query endpoints from the available request data in the traces. Instead of grouping all GraphQL requests under a single /graphql group, list each unique query endpoint separately in the request insights view. This will allow users to quickly identify performance issues related to specific GraphQL queries, improving the speed and accuracy of debugging and performance monitoring.

### Product Area

Insights

**Comment by bcoe** [comment]
@mjq this should be addressed by using `integrations: [Sentry.graphqlIntegration({ useOperationNameForRootSpan: true })]`, which would split their GraphQL transactions up by operation name?

What if we keep this ticket open until we add documentation [here](https://docs.sentry.io/platforms/javascript/guides/node/tracing/instrumentation/custom-instrumentation/requests-module/).
