### ISSUE TITLE
Slack Integration: I can't resolve issues from Slack

### ISSUE THREAD

**Issue by garecinos4** [getsentry/sentry#7922]
## Reporting Bugs

- I'm integrating Sentry with Slack, when Sentry send the notification, I can't resolve the issue from Slack

![captura de pantalla 2018-04-04 a la s 12 28 34](https://user-images.githubusercontent.com/10041845/38323759-d72966dc-3803-11e8-8c7a-b536e9c8a466.png)

If I select the user for solved the issue, I can't take any action after
![captura de pantalla 2018-04-04 a la s 12 30 17](https://user-images.githubusercontent.com/10041845/38323852-15f00fa6-3804-11e8-87fe-70ad95c8699a.png)

![captura de pantalla 2018-04-04 a la s 12 30 27](https://user-images.githubusercontent.com/10041845/38323880-2ce5c8e0-3804-11e8-93a7-5de088d5ba8a.png)

In any case I can't resolve issues, only I can ignore issues

![export 7](https://user-images.githubusercontent.com/10041845/38325072-99f84a04-3807-11e8-8088-2d24a2f74b46.png)

Thanks for the feedback

**Comment by EvanPurkhiser** [comment]
Do you get the dialog window at all, or does it just hang with the buttons greyed out?

**Comment by garecinos4** [comment]
@EvanPurkhiser The buttons are blocked for a moment and it does't do anything, it does't open any window.

**Comment by booleanbetrayal** [comment]
I've seen this as well. It has happened on all of the (limited / testing) events on our staging environment, but the one error that has come through since on our production environment works fine. In case it helps debugging:

Working: https://sentry.io/pedago/front-royal/issues/514347654/?referrer=slack

Not-working: https://sentry.io/pedago/staging-rails/issues/514554265/?referrer=slack

Both are using the same Slack "Workspace" and notification options, so not sure what else it could be environmentally.

**Comment by EvanPurkhiser** [comment]
```
["[ERROR] The field `title` cannot be longer than 24 characters"]
```

Here's the issue, project names are too long :) Fix here https://github.com/getsentry/sentry/pull/7949

**Comment by garecinos4** [comment]
you mean the name of my project, plus the ID that Sentry set, plus the word "resolve" ?

 example:  "resolve STATUS-SERVICE-9B"

I think the best solution has to be change the title in the integration and send only "resolve" and add a label with the name of the project

**Comment by EvanPurkhiser** [comment]
> add a label with the name of the project

Unfortunately slack also limits the labels to 24 characters

> Label displayed to user. Required. 24 character maximum.

**Comment by pkuczynski** [comment]
@EvanPurkhiser how did you debug the issue? I am having similar. Buttons are active and whenever I click them, become gray for a moment and then come back white. I can't resolve either ignore or assign the issue from slack. Very annoying :(

**Comment by EvanPurkhiser** [comment]
@pkaminski  Is this on sentry.io?

**Comment by pkaminski** [comment]
I think you meant to mention @pkuczynski.  :)

**Comment by pkuczynski** [comment]
Yeah, on sentry.io
