### ISSUE TITLE
Dashboards - Being able to surface the App score (from Web vitals) into a table per release

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#79266]
### Problem Statement

Currently to measure the impact the App score can be seen as a overal metric.
But this metric cannot be used in dashboards to show you the app score for each release which might be the first indicator to start looking.

### Solution Brainstorm

You can create a widget showing releases and all web vitals but no App score.

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2322) by [Unito](https://www.unito.io)

**Comment by gggritso** [comment]
This makes sense, thanks for raising! I'll throw this on our backlog 👍🏻

**Comment by ruud** [comment]
Great addition 👍
