### ISSUE TITLE
Give options to reduce the recording time

### ISSUE THREAD

**Issue by cristianonisor007** [getsentry/sentry#79260]
### Problem Statement

Currently the recordings default time is 60 min per session. 

Give more options to record 30 min, 15 min, etc. 

In many cases the recordings of 60 min are not too relevant or efficient and eating resources. Having lower timeframes would fit better other users needs and save resources. 

### Product Area

Replays

**Comment by bruno-garcia** [comment]
The resources you are referring to are the client device?

One consideration is that if the session ends sooner, it'll probably be sampled again sooner potentially increasing your quota usage. 

It seems reasonable to have such option although I'm not sure about the complexity involved to add it. I'll defer this to @billyvg

**Comment by cristianonisor007** [comment]
I was thinking in general about the resources(storage), I'm not sure if it impacts the end client device resources.

**Comment by billyvg** [comment]
This actually exists, but is not documented: https://github.com/getsentry/sentry-javascript/blob/develop/packages/replay-internal/src/integration.ts#L86

**Comment by billyvg** [comment]
Please re-open if this doesn't resolve the issue
