### ISSUE TITLE
Flask tracing does not work out of the box

### ISSUE THREAD

**Issue by obostjancic** [getsentry/sentry#79270]
Having a nested function call like 
```python 
@app.route("/")
def hello_world():
    generate_fibonacci(random.randint(1, 10))
    return "<p>Hello, World!</p>"

def generate_fibonacci(n: int) -> int:
    if n <= 0:
        return 0
    elif n == 1:
        return 1
    else:
        return generate_fibonacci(n-1) + generate_fibonacci(n-2)
```
resulted in [traces](https://telex-sandbox.sentry.io/traces/?project=4508138030497872&statsPeriod=90d) with only one span 

after adding `@sentry_sdk.trace`  decorator i got a [full trace](https://telex-sandbox.sentry.io/performance/trace/8d27649b558140da95e639a6fa913094/?dataset=transactions&field=title&field=project&field=user.display&field=timestamp&name=All%20Errors&node=txn-113d2647e7ae40e098f3b716daad4dc1&project=4508138030497872&query=&queryDataset=transaction-like&sort=-timestamp&source=discover&statsPeriod=1h&timestamp=1729167851&yAxis=count%28%29)

**Comment by szokeasaurusrex** [comment]
@obostjancic, as I stated in Slack, the SDK should only create spans for the `generate_fibonacci` function if it is decorated with `@sentry_sdk.trace`. As this is expected behavior, I am closing the issue.
