### ISSUE TITLE
Cant filter tag with space

### ISSUE THREAD

**Issue by askfor** [getsentry/sentry#793]
In stream page the url is:
http://127.0.0.1:9000/test/test/?test**+**tag=a

but the polling url is:
http://127.0.0.1:9000/api/test/test/poll/?test**%2B**tag=a&cursor=1361161709

so the request.GET is different:
<QueryDict: {u'test tag': [u'long']}>
<QueryDict: {u'cursor': [u'1361161709'], u'test+tag': [u'long']}>

then in Filter.get_value will try to use request.GET['test tag'] to get tag value. There is no 'test tag' in api.poll requets but only 'test+tag', so api.poll won't filter this tag.

now i change Filter.get_value like this,it works:

    def get_value(self):
        ret = self.request.GET.get(self.get_query_param(), self.default)
        if not ret:
            ret = self.request.GET.get(urllib.quote_plus(self.get_query_param()), self.default)
        return ret or ''

but i think it's better to fix this in javascript.

**Comment by mattrobenolt** [comment]
Pretty sure this is not an issue anymore, but please reopen if I'm mistaken.
