### ISSUE TITLE
Crons: Detect ingestion outages during clock ticks

### ISSUE THREAD

**Issue by evanpurkhiser** [getsentry/sentry#79328]
There is a failure scenario that can be very disruptive for our customers. 

If we have an outage in our ingestion of cron check-ins, specifically where we are **dropping check-ins**, then we may incorrectly mark customers cron monitors as having missed check-ins. This only happens if we drop check-ins, if we are delayed with check-ins, the clock ticks which drive missed and time-out detections will slow down to match the consumption of check-ins in our topic.

This is highly problematic as it means customers are unable to trust that cron alerts are accurate. This is, however, a difficult problem, since if check-ins never make it into the check-ins topic, how can we differentiate between a customers job failing and not sending a check-in, and us failing to ingest their check-in?

In most of our ingestion failure scenarios **we have had a significant drop in check ins**. That typically looks something like this:

![Image](https://github.com/user-attachments/assets/97cd197b-3fc8-40a1-a2ff-84a7e6a4a18c)

## Improved behavior

If we were able to detect this extreme drop in volume, we could create clock ticks that are marked as being `unknown` ticks. meaning we are moving the clock forward, but we have a high certainty that we may have lost many check-ins. When this happens instead of creating `missed` and `timed-out` check-ins that trigger alerts, we can create missed check-ins that have a "unknown" status and mark in-progress check-ins that are past their latest check-in time as "unknown", again not alerting customers. Once we are certain that we have recovered from our incident, the clock will resume producing ticks that are regular, and not marked as unknown.

## Detecting ingestion volume drops

The tricky part here is deciding if we are in an incident state. Ideally we are not relying on an external service telling us that we may be in an incident, since that service itself may be part of the incident (eg, if we had relay report that it was having problems, there's no guarantee that when it's having problems it will just fail to report to us).

My proposed detection solution is rather simple. As we consume check-ins, we keep a bucket for each minute worth of check-ins, that bucket is a counter of how many check-ins were consumed for that minute. We will keep these buckets for 7 days worth of data, that's 10080 buckets.

Each time the clock ticks across a minute, we will look at the last 7 days of that particular minute we ticked over, take some type of average of those 7 counts, and compare that with the count of the minute we just ticked past. If we find that the count here is some percentage different from the previous 7 days of that minute, we will produce our clock tick with a "unknown" marker, meaning we are unsure if we collected enough data for this minute and are likely in an incident. In which case we will create misses and time-outs as "unknown".

### Ignoring previous incidents

When a minute was detected as having a abnormally low volume we should reset it's count to some sentinel value like `-1` so that when we pick up this minute the next 7 days, we know to ignore the data, since it will not be an accurate representation of typical volume.

### Not enough data

> [!WARNING]
> What should we do if we don't have enough data to determine if the past minute is within the expected volume?

## Implementation

We should start by implementing this as a simple metric that we track, so we can understand what our typical difference looks like each day. It's possible some days may have many more check-ins, such as Monday's ad midnight. So maybe we will need a different way to evaluate anomalies.

> [!WARNING]
> The implementation described above has changed. See the [comment later in this issue](https://github.com/getsentry/sentry/issues/79328#issuecomment-2463477046) for a description of the new approach

## Implementation

```[tasklist]
### PRs needed for both approaches
- [ ] https://github.com/getsentry/sentry/pull/79448
- [ ] https://github.com/getsentry/sentry/pull/79574
- [ ] https://github.com/getsentry/sentry/pull/80348
- [ ] https://github.com/getsentry/sentry-kafka-schemas/pull/340
- [ ] https://github.com/getsentry/sentry/pull/79735
- [ ] https://github.com/getsentry/sentry/pull/79785
- [ ] https://github.com/getsentry/sentry/pull/79783
```

```[tasklist]
### Outdated PRs for previous approach
- [ ] https://github.com/getsentry/sentry-kafka-schemas/pull/339
- [ ] https://github.com/getsentry/sentry-kafka-schemas/pull/341
- [ ] https://github.com/getsentry/sentry/pull/79729
- [ ] https://github.com/getsentry/sentry/pull/80347
- [ ] https://github.com/getsentry/sentry/pull/80355
```

```[tasklist]
### PRs needed for new approach
- [ ] https://github.com/getsentry/sentry-kafka-schemas/pull/348
- [ ] https://github.com/getsentry/sentry/pull/80527
- [ ] https://github.com/getsentry/sentry/pull/80528
- [ ] https://github.com/getsentry/sentry/pull/80605
- [ ] https://github.com/getsentry/sentry/pull/80640
- [ ] https://github.com/getsentry/sentry/pull/80703
- [ ] https://github.com/getsentry/getsentry/pull/15718
- [ ] https://github.com/getsentry/ops/pull/12854
- [ ] https://github.com/getsentry/sentry/pull/80773
- [ ] https://github.com/getsentry/sentry/pull/80842
- [ ] https://github.com/getsentry/sentry/pull/80844
- [ ] https://github.com/getsentry/sentry/pull/80845
- [ ] https://github.com/getsentry/sentry/pull/80911
- [ ] https://github.com/getsentry/sentry/pull/80930
- [ ] https://github.com/getsentry/sentry/pull/80864
- [ ] https://github.com/getsentry/sentry/pull/80916
- [ ] https://github.com/getsentry/sentry/pull/80949
- [ ] https://github.com/getsentry/sentry/pull/80955
- [ ] https://github.com/getsentry/sentry/pull/80985
- [ ] https://github.com/getsentry/sentry/pull/80954
- [ ] https://github.com/getsentry/sentry-options-automator/pull/2691
- [ ] https://github.com/getsentry/sentry-options-automator/pull/2692
- [ ] https://github.com/getsentry/sentry-options-automator/pull/2698
- [ ] https://github.com/getsentry/sentry-options-automator/pull/2699
- [ ] https://github.com/getsentry/sentry/pull/81012
- [ ] https://github.com/getsentry/sentry/pull/81016
- [ ] https://github.com/getsentry/sentry/pull/81018
- [x] Killswitch documentation / runbook / systems diagram
- [x] Alert in slack when entering incident
- [x] Cleanup old changes no longer required (old anomaly things)
```

**Comment by evanpurkhiser** [comment]
We've realized there is a problem with the approach described in this issue.

As it turns out, it's unlikely we're able to just determine an incident from just looking at volume of a specific clock tick in comparison to volume from the previous clock tick. We did have an incident while building this feature after we've already started collecting metrics for our historic volume, looking at the % deviation from mean during that incident we have the following graph (The second graph being the number of check-ins we processed.

![Image](https://github.com/user-attachments/assets/56421770-b44b-4461-8fba-631594cbd1bf)

Note that there's a uptick in % mean deviation, followed by a small downtick in % deviation. This downtick is not visible in the actual check ins processed graph and is likely just due to the nature of how the check-in volume variates from minute to minute. So while we did consumer less check-ins at that minute, the deviation is not as great compared to the previous minutes deviation. **This does not mean the incident stopped during that downtick**, if we were to just use some percentage cut off to determine if a tick is abnormal, we would have processed this tick and likely lost data and create missed check-ins.

**This is something we need to account for when determining if we're in an incident state**

Given what we've implemented so far, where we make a decision during a tick and will create unknown check-ins instead of missed, and will mark in-progress as unknown. You might intuitively think we can simply delay the click tick and look at future volume deviations during the delayed clock tick, and use that to determine if we are definitely in an incident state, and make the decision for that tick to create misses as unknown etc. But there is a problem with this.

https://github.com/getsentry/sentry/issues/63166 describes a problem where during a single partition backlog monitors may fail to correctly mark missed check-ins due to to the fact that the clock is delayed, but we are still consuming check-ins from relay. During a clock delay like this, it's possible an OK check-in will come in before we're able to mark missed check-ins for a monitor. By inducing a clock delay for the purpose of detecting incidents, we'll also be inducing this behavior causing real misses to be lost.

Ideally we would just fix this problem, but unfortunately we can't do that. In fact, we are not able to introduce _any_ kind of clock delay without introducing this problem. Even if we were to "fix" this using the proposed solution in that ticket of back-filling missed check-ins, it does not work. Doing this would mean during an incident when we are trying to avoid creating misses and instead create them as unknown, we would still create misses using this backfill. There's no way for them to be backfilled as unknowns since the fact that the clock is delayed (causing this problem in the first place) is _because we do not know if we're in an incident yet_. So really we would need to delay creating those mises, but that would mean _delay processing the OK check in_, which we cannot do.

**So if we're unable to delay the clock what-so-ever, what can we do?**

The problem we're trying to solve for is two fold here

1. Do NOT notify customers of missed and timed-out check-ins during an ingestion incident at sentry. This is THE most important thing, we do not want to wake up customers at 1am when their job ran fine, but we had an ingestion incident.
2. Correctly communicate in our check-in history UI that a missed or timed-out check-in's were created during an incident, and likely do not reflect what their monitor was actually reporting.
3. Be very accurate for when an incident started and when an incident resolved itself by using volume history.

Notifications are the component that needs to be delayed. Once we are sure we are an incident we can mark misses and time-outs as unknown. To delay notifications **TBD**





#### Notes

- Misses are going to show as miseed in the UI
- Timeouts get marked during an incident, how are we able to go back and mark those time-outs as unknowns
  - If we go back and clean up

**Comment by swanson** [comment]
Hi! We're using the crons product and this issue is really the one negative we have.

I did want to share from our perspective if it is helpful:

- Reducing, without completely eliminating, would be a meaningful improvement. Getting pinged for false positives is annoying, but the bigger issue is the erosion of trust (our team has already started assuming that failures are due to "Sentry ingest issues" and is now the first thing they check, instead of our own service)
- We don't really care at all about the history of the check-ins, rather the notifications as you mention. So backfilling "unknown" status would be nice but honestly, we rarely look at the history during normal operations
- We've already turned our notification settings to wait for 2 consecutive failures as a result (not great, but does help with random blips)
- We would love to be able to opt-in on a new monitor basis to more "lax alerting" -- we have some recurring processes that are critical and we can accept false positives, others where we don't care as much

I am certainly not anything approaching an expert on the topic, but one technique we had used before setting up cron monitoring was to run a "tracer" job through our actual infrastructure. Maybe something similar could work for the Sentry cron ingest itself? If some internal ingest workload that you all are managing is not getting processes, that could be an early indication that ingest is degraded and then you could trigger some flag to change notification behavior.

Great to see this is being worked on and will be following along!

**Comment by gaprl** [comment]
Hey @swanson thank you for the feedback! That's our goal, to complete eliminate these misleading alerts and regain your trust in our product.

I wanted to follow up on this bullet point:
> We would love to be able to opt-in on a per-monitor basis to more "lax alerting" -- we have some recurring processes that are critical and we can accept false positives, others where we don't care as much

Today you are able to configure the alerting thresholds on a per-monitor basis. Can you clarify if these consecutive failures/successes would be enough for your use case, or if you're referring to something else?

**Comment by swanson** [comment]
> Today you are able to configure the alerting thresholds on a per-monitor basis. Can you clarify if these consecutive failures/successes would be enough for your use case, or if you're referring to something else?

I was imagining something like a toggle field per-monitor for "Don't alert on unknown status" that would allow us to let some monitors opt-in to behavior changes related to service degradation. The current consecutive failures helps, but is not sufficient and is not that legible (we would want it to alert immediately, just that service degradation is so often the cause that we have it as a workaround)

**Comment by evanpurkhiser** [comment]
Hey thanks for the comments on this @swanson!

> run a "tracer" job through our actual infrastructure

This is an approach we considered, but this also has it's drawbacks since it means that system needs to be highly fault resistant itself, otherwise we risk a false positive of that trace not coming through causing true misses / time-out's not to be sent out. The new approach we have that delays sending notifications when the system detects an anomaly in check-in volume should work in a similar way, but will have the ability to self correct based on 

> We don't really care at all about the history of the check-ins, rather the notifications as you mention. So backfilling "unknown" status would be nice but honestly, we rarely look at the history during normal operations

This is super helpful feedback since I was trying to weight the added complexity of trying to mark check-ins as unknown once we "think" we're in an incident, and then if we aren't go back and correctly mark them as missed / timeout status. I think we probably won't do that, but we **will** mark incorrectly generated misses / timeouts as unknown once we **know** we are in an incident.

Thanks again for the feedback!

**Comment by evanpurkhiser** [comment]
> Don't alert on unknown status

By default we won't alert if there is a system incident. We considered an option that still sends notifications in the case that we think we're producing false positive misses (for example, if you have a job that is so critical that you want to know if we think it could be down). But I think the need for this is going to be pretty rare, so we're probably not going to build this (at least not right away).

**Comment by evanpurkhiser** [comment]
I spent some time writing a description for the final bit of how this system works. It's in an internal notion Run Book document, but I'll duplicate it here for posterity.

[[Internal runbook document]](https://www.notion.so/sentry/Crons-Runbooks-53bf37215b634b02adbb719ca99cc528?pvs=4#1438b10e4b5d8085affacf428c573f3c)

---

# Configuring the System Incident detections

The crons system is resilient to upstream outages (such as partial relay outages) that would typically cause erroneously created `MISSED` or `TIMEOUT` check-ins. It does this by monitoring the volume of check-ins it consumes each minute. If the volume drops below the average for the last 30 days during that minute, the system will delay sending “incident occurrences” (which produce issue occurrences). We delay until we can determine if we are truly experiencing an outage, once the system determines there is an outage, it will drop those incident occurrences and any future occurrences until we recover, as well as mark affected check-ins as `UNKNOWN`.

To understand this system let’s look at the DataDog dashboard we have configured. [[Internal DataDog dashboard]](https://app.datadoghq.com/dashboard/eru-qsp-mst/cron-metrics?fromUser=true&refresh_mode=paused&tpl_var_sentry_region%5B0%5D=us&from_ts=1732011833989&to_ts=1732012964263&live=false&tile_focus=2957428177242310)

The “Mean Deviation %” graph shows us the deviation percentage that each clock tick deviates from the average volume history for that particular minute over the last 30 days.

![Image](https://github.com/user-attachments/assets/3775abeb-a779-4085-95ec-d28541e49a16)

This data is used to generate “tick decisions” for each tick. Decisions can be observed in the “Tick Decisions” graph

![Image](https://github.com/user-attachments/assets/6ec893d3-19be-4165-854c-d6051fb5f60d)

## Decision transitions

In the previous graph we see all decisions made for each clock tick are `NORMAL`. However, if the system detects a deviation into the `ABNORMAL` range the tick will be decided as `ABNORMAL`. All future ticks will be abnormal until we see 5 ticks that are below the abnormal threshold in a row, in which case the decisions will transition back to `NORMAL`.

When `ABNORMAL` transitions back to `NORMAL` all abnormal decisions are backfilled to `NORMAL`. This is to say that `ABNORMAL` is a intermediate state.

Should the metric deviate into the `INCIDENT` threshold, the system will mark those ticks as `INCIDENT`. Similar to `ABNORMAL` once a tick is detected below the abnormality threshold the system will begin making `RECOVERING` decisions. There must be 5 recovering decisions in a row below the abnormality threshold, at which point the system will begin making `NORMAL` decisions again and the `RECOVERING` decisions will be backfilled as `NORMAL`.

The “Tick Transitions” graph gives us insight into the transition events

![Image](https://github.com/user-attachments/assets/137e015b-cf37-417e-9329-0243c4505425)

The architecture overview includes some examples of how this works: [Internal architecture diagram](https://www.figma.com/file/cXyqavGR77wfQrqXkZDuEz/Crons-Architecture?type=whiteboard&node-id=0-1&t=vQvNFsrB5W5MwSmf-0)

## Delayed Incident Occurrences (delaying alerts)

Miss and Time-out failures cause the `mark_failed` logic to dispatch “incident occurrences” into a queue. These occurrences will check the Tick Decision made for the clock tick that dispatched these check-in failures.

- **`NORMAL` Ticks** - The consumer will immediately dispatch an issue occurrences to notify customers of their cron failure.
- **`ABNORMAL` and `RECOVERING`** - The consumer **will not process the occurrence** and will wait for the tick decision to resolve. **During this time it is expected that this consumer will backlog**, as we are waiting to determine if we have entered an incident, recovered from an abnormality, or recovered from an incident.
- **`INCIDENT` Ticks** - The consumer will **drop occurrences** (they will never be sent). In this scenario these occurrences may be false negatives. The check-ins will be marked as `UNKNOWN`

Again we **expect this consumer to backlog** which may look something like this. Once the tick decision has resolved the consumer will burn down it’s queue of occurrences.

![Image](https://github.com/user-attachments/assets/afd737c4-852f-4e3b-b5cb-bf1a54b2bb5a)

## Decision option configuration

There are a number of options that control this system

- `crons.system_incidents.collect_metrics: boolean`
Enables recording volume and metrics. Without this enabled the decision detection system will do nothing.
- `crons.system_incidents.use_decisions: boolean`
Enables using tick decisions to delay / drop incident occurrences (intents to create issue occurrences). Also enables marking in-progress as unknown during incidents. **This may be disabled should we incorrectly detect an abnormality or incident.**
- `crons.system_incidents.pct_deviation_anomaly_threshold: int`
The threshold the metric must deviate for a tick to be considered an anomaly. The closer we can get this to the typical metric the better, since this means we will catch incidents earlier. This value is also used to determine when we have recovered. **Should be adjusted if we get stuck in long running anomaly states.**
- `crons.system_incidents.pct_deviation_incident_threshold: int`
Similar to the anomaly threshold, this is the % deviation that we must surpass to consider a tick having entered an incident. **Should be adjusted if we fail to detect an incident with too low of a volume drop-off.**
- `crons.system_incidents.tick_decision_window: int`
The number of ticks that we will look back at when recovering from an abnormality or incident. This may be adjusted if we recover too soon / too late from incidents or abnormalities.

**Comment by evanpurkhiser** [comment]
Closing this issue. This is now deployed and operating as expected.

Customers should no longer receive false positive notifications.
