### ISSUE TITLE
Do not process frames marked as in-app by in_app_include rules

### ISSUE THREAD

**Issue by armenzg** [getsentry/sentry#79357]
This work depends on [this SDK](https://github.com/getsentry/sentry-python/issues/3671) issue resolving.

If the customer uses `in_app_include` to set some frames as in-app we should not later destroy it with one of our enhancement rules.

For instance, the customer installed their code under their virtual env which ends up under `site-packages` which we then mark as **not an in-app frame**. (https://github.com/getsentry/sentry/blob/e56c063b7c55de625354f07114896a3fdb308d65/src/sentry/grouping/enhancer/enhancement-configs/newstyle%402023-01-11.txt#L377)

Once the SDK issue is fixed we can then determine which frames should not be tried for enhancement.

**Comment by armenzg** [comment]
Instead of this, we're going to work on #79482.

**Comment by lobsterkatie** [comment]
Superseded by https://github.com/getsentry/sentry/issues/83603
