### ISSUE TITLE
Trace duration appears to be rounded to nearest millisecond, despite displaying decimal places

### ISSUE THREAD

**Issue by szokeasaurusrex** [getsentry/sentry#79406]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Consider [this trace](https://sentry-sdks.sentry.io/performance/trace/dcdb453cc51f45ebb4c0e002605b6ab2/?fov=0%2C4&node=trace-root&project=4505239425777664&query=http.method%3AGET&referrer=performance-transaction-summary&showTransactions=recent&source=performance_transaction_summary&statsPeriod=1h&timestamp=1729516257&transaction=hello_world&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29), whose duration is displayed as `4.00ms`.

![Image](https://github.com/user-attachments/assets/ddf60c01-bac6-4cc1-a78a-f2b92408e024)

### Expected Result

The trace includes only one transaction (the `http.server` `hello_world` transaction). So, the trace duration should be equal to the transaction's duration. The transaction's duration (in seconds) is given by the difference between the (end) `timestamp` and `start_timestamp` properties of the transaction's JSON.

### Actual Result

If we view the [transaction's JSON](https://sentry-sdks.sentry.io/api/0/projects/sentry-sdks/python/events/579e7d363cb44401910134e209683f6f/json/), we see the start and end timestamps (in seconds) for the transaction:

```json
  "start_timestamp": 1729516257.802911,
  "timestamp": 1729516257.806465,
```

By taking the difference of the two timestamps, and multiplying by 1000ms/s, we see that the transaction's duration is actually `3.55ms`, not `4.00ms` as we would expect (~~note that the UI also displays the transaction's duration incorrectly, but this is a separate issue~~ edit: looks like this was already fixed).

I have several other transaction's whose trace duration also appears to have been rounded to a whole number of milliseconds, so maybe we are rounding somewhere. I think we should display the exact value, rather than the rounded value, if possible.

But, if we need to round, then we should not display any digits after the decimal point. In other words, we should display `4ms` rather than `4.00ms` in the UI. Displaying two zeroes after the decimal point on a rounded value falsely suggests to users that the value is accurate to that many decimal places, even though it is not.

### Product Area

Performance

### Link

https://sentry-sdks.sentry.io/performance/trace/dcdb453cc51f45ebb4c0e002605b6ab2/?fov=0%2C4&node=trace-root&project=4505239425777664&query=http.method%3AGET&referrer=performance-transaction-summary&showTransactions=recent&source=performance_transaction_summary&statsPeriod=1h&timestamp=1729516257&transaction=hello_world&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29

**Comment by DaveRosenthalSentry** [comment]
Good catch. Seems like an easy one. Marking as low effort.

**Comment by szokeasaurusrex** [comment]
This should have been fixed in https://github.com/getsentry/sentry/pull/79823, but that PR only appears to have fixed part of the problem. 

Looking again at [the trace](https://sentry-sdks.sentry.io/performance/trace/dcdb453cc51f45ebb4c0e002605b6ab2/?fov=0%2C4&node=trace-root&project=4505239425777664&query=http.method%3AGET&referrer=performance-transaction-summary&showTransactions=recent&source=performance_transaction_summary&statsPeriod=1h&timestamp=1729516257&transaction=hello_world&unselectedSeries=p100%28%29&unselectedSeries=avg%28%29) I linked in the original issue description, we see that the transaction now has its duration correctly displayed as 4ms, but the trace duration still incorrectly is displayed as 4.00ms when it should also be 4ms:

<img width="922" alt="trace duration 4.00ms and transaction 4ms screenshot" src="https://github.com/user-attachments/assets/afde9af1-9b61-48dc-8296-3614b5a45b1d" />

@JonasBa pinging you since you made the [original PR](https://github.com/getsentry/sentry/pull/79823)

**Comment by JonasBa** [comment]
@szokeasaurusrex we wont be displaying the trace duration anymore as a bar (if you look at some traces on sentry org, I believe the bar should no longer be rendered).
