### ISSUE TITLE
show more information about code mapping in Add Code Owner File modal

### ISSUE THREAD

**Issue by cdignam-segment** [getsentry/sentry#79410]
### Problem Statement

The "Add Code Owner File" modal only lists the repository name for the code mapping. So when there are multiple code mappings, it's not possible to know which one to pick.

![Image](https://github.com/user-attachments/assets/9a8f2136-e80a-4817-a561-d4408b02e7d5)

### Solution Brainstorm

The modal should show a snippet of the source root or stack trace root from the code mapping. In addition to the repository name.

### Product Area

Issues

**Comment by jangjodi** [comment]
Thanks for bringing this to our attention @cdignam-segment! I will add this to our backlog to fix
