### ISSUE TITLE
[Search] Multiple release.version searches casues invalid operation

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#79428]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Reported by a customer, searching for multiple release.versions in the issue stream results in `Invalid operation 'IN' for semantic version filter.` error.

Repro in Sentry instance:
1. Navigate to [issue stream](https://sentry.sentry.io/issues/?project=1&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=sidebar&sort=date&statsPeriod=14d&viewId=default0) 
2. [Search by](https://sentry.sentry.io/issues/?project=1&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D%20release.version%3A%5B23.2.0%2C23.3.0%2C22.11.0%5D&referrer=issue-list&sort=date&statsPeriod=14d&viewId=default0) multiple `release.version` values
3. "Invalid operation 'IN' for semantic version filter." error

### Expected Result

Issues returned from release.version's

### Actual Result

Invalid operation 'IN' for semantic version filter error occurs

### Product Area

Issues

**Comment by JoshFerge** [comment]
thank you for reporting! will be prioritizing a fix https://github.com/getsentry/sentry/pull/76313/files

**Comment by roggenkemper** [comment]
Will close this issue since we have an older one tracking the same issue - https://github.com/getsentry/sentry/issues/76286
