### ISSUE TITLE
Feature Request: Ability to Set Sample Rates via Sentry UI

### ISSUE THREAD

**Issue by georg78sf** [getsentry/sentry#79437]
### Problem Statement

Currently, there is no option to configure sample rates for different event types, including replays, directly within the Sentry UI. Instead, these settings for error and performance tracking must be specified in the JavaScript code.

This approach presents challenges, especially when needing to adjust sample rates based on changing traffic volumes or scaling needs. In my opinion, such changes should not require code deployments, as they are more operational than developmental in nature.

Furthermore, depending on how a project is structured, updating Sentry initialization code across multiple HTML pages can add unnecessary complexity, especially for teams working with larger or distributed codebases.

Another issue I’ve encountered is browser compatibility when implementing these settings in code. Despite various attempts, I’ve had difficulty preventing errors such as "duplicate initialization" in certain browsers, which complicates deployment.

Here’s an example of the code I'm using:

```
Sentry.init({
    integrations: [
      Sentry.replayIntegration(),
    ],
    replaysSessionSampleRate: 0.1, // 10% sampling
    replaysOnErrorSampleRate: 1.0,  // 100% sampling when an error occurs
});

```

It would be highly beneficial to have the ability to manage these settings dynamically from the Sentry UI, without the need to modify and redeploy code. This would significantly streamline the process, especially for teams managing multiple environments or dealing with fluctuating traffic.

### Product Area

Performance

**Comment by cmanallen** [comment]
Hi @georg78sf we currently do not have any plans to support remotely configuring the Sentry SDK from the Sentry UI.  However, you can accomplish this by using a feature provider (such as LaunchDarkly, Statsig, Unleash, or Split.io) to seed the SDK with remotely configured values.

Alternatively, if this is a a back end service, you can use environment variables to dynamically change sample rates without a code change.  Just be sure to restart the server after making the change (this is done automatically on platforms such as Amazon's EBS).

**Comment by georg78sf** [comment]
@cmanallen  Ah ok that's too bad. I want to not have another dependency on a feature provider. And this is also not a backend service.

**Comment by michellewzhang** [comment]
closing as not planned
