### ISSUE TITLE
Adding of CPU and RAM monitoring

### ISSUE THREAD

**Issue by mihalt** [getsentry/sentry#79434]
### Problem Statement

I want to monitor how much of CPU and RAM of a host machine is each of my app docker containers with Sentry used. And I would like to see it in history of course. Specially for me are containers with django now. 

### Product Area

Performance

**Comment by Dhrumil-Sentry** [comment]
This use case is very relevant to infra monitoring. That is not a direction we want to pursue for several quarters at the least. I am closing this as a won't do

**Comment by mihalt** [comment]
> This use case is very relevant to infra monitoring. That is not a direction we want to pursue for several quarters at the least. I am closing this as a won't do

Can you recommend any instruments for infra monitoring that will be successfully living with sentry?
