### ISSUE TITLE
GitHub Integration Problem

### ISSUE THREAD

**Issue by chinleung** [getsentry/sentry#79444]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Add a new integration for the first Sentry organization
2. Switch to another Sentry organization
3. Add a new integration for the second Sentry organization using the same GitHub organization

### Expected Result

I expected that I should be able to add a new integration using the same GitHub organization.

### Actual Result

I'm stuck in my existing GitHub integration that has been added for my first Sentry organization.

### Product Area

Settings - Integrations

### DSN

https://99ee604da173597af407c3ab166f063f@o4505824404832256.ingest.us.sentry.io/4505828674764800

**Comment by sentaur-athena** [comment]
Thanks for providing feedback. We got this before and will be tracking it on https://github.com/getsentry/sentry/issues/79401

**Comment by cathteng** [comment]
Closing as a duplicate
