### ISSUE TITLE
Can't open configuration for Jira Integration

### ISSUE THREAD

**Issue by niklasHack2810** [getsentry/sentry#79474]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. Open Jira configuration

### Expected Result

It works

### Actual Result

![Image](https://github.com/user-attachments/assets/76a2e098-ba31-4a72-a925-c8844031974e)

![Image](https://github.com/user-attachments/assets/f284ab2e-5080-4eec-9c41-43e6cc0ff2ad)

### Product Area

Settings - Integrations

### Version

24.10.0

**Comment by sentaur-athena** [comment]
Thanks for reporting. We will look into this.

**Comment by GabeVillalobos** [comment]
@niklasHack2810 We reverted a recent change yesterday that caused this to occur for a small number of organizations. Are you able to access Jira configuration settings now? If so, I'll be closing this ticket out.

**Comment by niklasHack2810** [comment]
@GabeVillalobos will there be an update for this? The latest version I see is 24.10.0 which has the broken jira configuration :/

**Comment by niklasHack2810** [comment]
I upgrade to 24.11.0 and this issue is now resolved. Thank you :)
