### ISSUE TITLE
Verify how you can get releases

### ISSUE THREAD

**Issue by ale-cota** [getsentry/sentry#79479]
We currently have various tasks in the QuickStart that _might_ result in you setting up releases (e.g. setting up source maps or SCM integrations like Github, Gitlab, etc.) as well as a standalone one to track releases. It would be good to figure out if and how reliably completing the other tasks helps you set up releases as well, so we can decide how to prioritise the tasks.

**Comment by priscilawebdev** [comment]
Findings so far:

**Sending Sourcemaps**

- Using the Sentry wizard command `npx @sentry/wizard@latest -i sourcemaps` automatically creates a release in my Sentry organization.
- I was unable to manually set up sourcemaps following [this guide](https://docs.sentry.io/platforms/javascript/guides/react/sourcemaps/uploading/create-react-app/#manual-setup). It’s unclear if a release is created automatically through this method (likely not).

**Adding Integrations**

- Even after integrating GitLab and GitHub and manually creating releases, nothing appeared in Sentry. It seems you still need to set up a release management tool like GitHub Actions or manually trigger a release using Sentry CLI. Just adding an integration alone doesn't automatically show releases in Sentry.

**Comment by lforst** [comment]
> It’s unclear if a release is created automatically through this method (likely not). @lforst can you please confirm this?

Whether or not a release is created by following this guide is an implementation detail. The guide is for uploading sourcemaps, not setting up releases. Sourcemaps don't have to be coupled to releases anymore - they can - but they don't have to.

**Comment by priscilawebdev** [comment]
According to the integrations team,  releases are mostly driven by telemetry sent with release annotations or explicit creation from CLI and not by creating SCM integrations.
