### ISSUE TITLE
Must Click Image name twice for auto-scroll to Images Loaded

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#79480]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. generate a unsymbolicated crash
2. click image address +0x5a2a8
![Image](https://github.com/user-attachments/assets/e0cf71d8-7079-4040-9a27-8e11217aa4de)

4. click image address +0x5a2a8 (second time)
5. it scrolls down to:![Image](https://github.com/user-attachments/assets/ecab1d93-b725-436f-a079-bca1338c4b0c)

happens on my computer and a colleague's

[](https://github.com/user-attachments/assets/3716a3ef-70b9-4969-b992-30b979fc7499)

see screen recording attached

### Expected Result

should only have to click once

### Actual Result

doesn't scroll after clicking once.
scrolls after clicking twice.

### Product Area

Issues

**Comment by roggenkemper** [comment]
tried it on the same issue/event and was also unable to reproduce - will close for now. feel free to re-open if this pops up again
