### ISSUE TITLE
Missing Margin around Issue Details Stack Trace for Native Projects?

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#79526]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

When navigating to an Issue Details page, I can see that there is a missing margin surrounding the stack trace. I was able to replicate this for two different projects for two different orgs in both the latest version of Firefox and Google Chrome. Was able to replicate for Native projects, not sure if this is occurring for any other project type. 

See screenshot

![Image](https://github.com/user-attachments/assets/b20300fc-575d-47c9-9806-aa4e9f5ac085)

### Expected Result

For there to be a clear margin around the stack trace and left/right columns

### Actual Result

No margin for Native project stack trace issues 

### Product Area

Issues

**Comment by leeandher** [comment]
This was a regression introduced by some new designs, I'll take a look at this ASAP and link a PR for a fix.
