### ISSUE TITLE
[Alerts] Metric alerts cannot save

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#79563]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Summary:
When creating or duplicating a metric alert and saving, you get the following error despite there being an action:
![Image](https://github.com/user-attachments/assets/4b05a0b3-e384-40e7-afdb-de01976d5821)

Also tested trying to delete and re add the action but still running into same error

Steps:
1. Navigate to a metric alert - https://jluse-free-org.sentry.io/alerts/rules/details/239654/
2. Duplicate
3. Attempt to save

### Expected Result

Ability to duplicate metric alert

### Actual Result

Error regarding action when saving

### Product Area

Alerts

**Comment by mifu67** [comment]
Hi @JLuse,

Thanks for bringing this to our attention, we'll work on a fix.

**Comment by mifu67** [comment]
Each trigger now requires an associated action (the action is the "fire an alert" part of the alert rule). If both warning and critical thresholds are set, then they must both have actions associated with them, otherwise the alert rule won't save.

**Comment by MelodicsPavol** [comment]
Thanks, this solved the problem.
