### ISSUE TITLE
Getting error "The organization you were looking for was not found." when trying to click in Quick Start section

### ISSUE THREAD

**Issue by gagell** [getsentry/sentry#79583]
**Environment**
self-hosted (https://develop.sentry.dev/self-hosted/)

Similar: https://github.com/getsentry/sentry/issues/53431

**Steps to Reproduce**
When you click on "Quick Start" on left bar and next  click in "Capture your first error" on start button. After choose project it redirects you to
https://example.com//getting-started/{project}/?referrer=onboarding_task
![Image](https://github.com/user-attachments/assets/b5ee7652-48e1-4d09-811e-4b85e5191593)
![Image](https://github.com/user-attachments/assets/62ab379a-0398-4384-9d10-7eafc30f93b7)

The correct url should indeed be:
[https://example.com/organizations/{organization_slug}/projects/{project}/getting-started/?product=performance-monitoring&referrer=onboarding_task
![Image](https://github.com/user-attachments/assets/03a94c89-a9c7-4c7b-b8e0-91e62d44e845)

**Comment by priscilawebdev** [comment]
@gagell thanks for reporting this issue 🙏 it will be fixed in the [PR](https://github.com/getsentry/sentry/pull/79964) 😉
