### ISSUE TITLE
Duplicate issue creation surfaces 500s for 3rd Party Integrations

### ISSUE THREAD

**Issue by sentaur-athena** [getsentry/sentry#79610]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

This should not be specific to 1 3rd party developer, but a partner reported getting 500s from /sentry-app-installations/$installationId/external-issues/. The full error shows that Sentry is trying to create external issue multiple times for the same Sentry issue. This is a unique relation in Sentry database so we throw 500.

### Expected Result

Issue gets created with no error

### Actual Result

Issue gets created with no problem but also 500 shows that a duplicate issue is being created as well.

### Product Area

Settings - Integrations

**Comment by Christinarlong** [comment]
completed see above PR
