### ISSUE TITLE
Tried moving from a heroku based account to a separate standalone one, keep getting an error when i click on the approve transfer email link.

### ISSUE THREAD

**Issue by RoohbirSingh** [getsentry/sentry#79658]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Clicked on approve transfer link
2. Shows error page

### Expected Result

To not see an error page but have the account move from heroku to the new one

### Actual Result

Seeing error page

![Image](https://github.com/user-attachments/assets/01ebe357-9fea-4e65-acf4-790312d7f31a)

### Product Area

Unknown

**Comment by leedongwei** [comment]
> have the account move from heroku to the new one

Are you trying to transfer a project from a Heroku-provisioned organization to a new organization?

**Comment by brianthi** [comment]
Closing issue as we haven't heard back. If this issue persists please reopen the ticket or create a support ticket and we can better help you there.
