### ISSUE TITLE
Setting commits for a release without using sha as release name

### ISSUE THREAD

**Issue by jlongster** [getsentry/sentry#7967]
Is it possible to use the git integration feature while still using versions like 0.0.50, instead of using the sha for release name?

Everything I've read seems to indicate so, and the API separate them. It's not clear why the release has to be the sha, and is only useful for people doing continuous integration.

However, I can't get it to work. You can see in this screenshot that commits were pulled in when I used the sha as the release name, but not when I created a release with a different name:

<img width="1182" alt="screen shot 2018-04-07 at 2 38 51 pm" src="https://user-images.githubusercontent.com/17031/38459100-99c155b2-3a73-11e8-80b4-a5e3df02b707.png">

**Comment by MaxBittker** [comment]
Hey @jlongster - conceptually, this should work (afaik, the name isn't used for any special logic).

I'd be happy to help you get this sorted out - Are you creating releases and associating commits using the CLI, a webpack plugin, or http requests? Could you share whatever your config or script is?

**Comment by jlongster** [comment]
I using sentry-cli, but dropped it to use the straight API to make sure it didn't have any bugs. Regardless, I figured it out. What was confusing was that nothing was showing up on the initial call to set the commits. None of the releases showed anything, and then I tried using the sha as the name, but just happened to push a new commit. The one new commit showed up, and I thought it was because I used the sha as the name.

I tried a new release without the sha as the name, and I *thought* I pushed a new commit, but I only made it locally and forgot to push. So nothing showed up.

Anyway, the key is that nothing shows up on the first release that'd been tagged. Only new commits will show up in future releases. Things seems to be working now.

The documentation makes it seem like you need to use the sha as the release name. I recommend adding a note somewhere in the docs that that's just convention for products using continuous delivery, and the name can be anything. It's good to hear that it's not used for any special logic.

Thanks for responding anyway :)
