### ISSUE TITLE
Access request for multi-team slack channel link

### ISSUE THREAD

**Issue by cdignam-segment** [getsentry/sentry#79728]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

I want to link multiple Sentry teams to a single Slack channel. It seems like this is feature flagged, so it would be great if this could be enabled for my org, segment.sentry.io.

https://github.com/getsentry/sentry/blob/3a2036cd495718e4f7d5a351657a605c15ac119e/src/sentry/integrations/slack/webhooks/command.py#L106-L109

### How are you getting stuck?

I get an error when attempting to link a second team to a Slack channel.

> This channel already has a team linked to it.

![Image](https://github.com/user-attachments/assets/d8a0e817-d2fe-411e-ac94-2cb3782f207f)

### Where in the product are you?

Issues

### Link

https://segment.sentry.io

### DSN

https://{tag}@o19879.ingest.us.sentry.io/{project_id}

**Comment by sentaur-athena** [comment]
This feature is in Alpha mode. We can definitely add you but if you experience any issue please let us know.

**Comment by cdignam-segment** [comment]
Thanks so much @sentaur-athena, this is very helpful for our organization!
