### ISSUE TITLE
[Wizard] CORS error after auth redirect

### ISSUE THREAD

**Issue by ArthurKnaus** [getsentry/sentry#79807]
After going through the auth redirect the user can end up on the wizard page of a non control silo region, resulting in a CORS error on form submit.

Reproduction: 
1. Log out of Sentry
2. Run wizard locally
3. Login to Sentry through wizard
4. Try to submit the project selector form
-> Causes CORS error from https://[slug].sentry.io/account/settings/wizard/[id] to https://sentry.io/account/settings/wizard/[id]
-> When user is logged in, the wizard navigates to sentry.io, but after auth, the wizard is navigated to [slug].sentry.io - which explains why it works when the user is already logged in.

**Comment by alvesvin** [comment]
Error persists

**Comment by alvesvin** [comment]
Out of a sudden it worked

**Comment by dule-vikki** [comment]
same issue

**Comment by shellmayr** [comment]
Fix in https://github.com/getsentry/sentry/pull/80305 does not seem to have fixed the issue - exploring further solutions

**Comment by shellmayr** [comment]
Closing - issue was fixed by https://github.com/getsentry/sentry/pull/80442
