### ISSUE TITLE
"required debug debug information file is missing" while the right PDB is there

### ISSUE THREAD

**Issue by mkdotcom** [getsentry/sentry#79803]
Originally discussed [on Discord](https://discordapp.com/channels/621778831602221064/1298931711467327518/1298931711467327518)

### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Hello!
I get "a required debug debug information file is missing" while the right pdb was uploaded ? I'm using the latest sentry-native. 
Thanks

### How are you getting stuck?

Hello!
I get "a required debug debug information file is missing" while the right pdb was uploaded ? I'm using the latest sentry-native. 
Thanks

### Where in the product are you?

Unknown

### Link

https://mkdc-tech.sentry.io/issues/10305818/?project=4507373010223184&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=30d&stream_index=1

**Comment by mkdotcom** [comment]
![Image](https://github.com/user-attachments/assets/59d1fbbb-c85a-49e8-94c9-20356f144889)
![Image](https://github.com/user-attachments/assets/caf623c1-a794-4562-93e6-663dc3ec9be5)
![Image](https://github.com/user-attachments/assets/021813c2-0652-4a5e-8309-4d3bd62b012f)

**Comment by mkdotcom** [comment]
the issue in sentry:

https://mkdc-tech.sentry.io/issues/10305818/?project=4507373010223184&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=30d&stream_index=1

**Comment by bruno-garcia** [comment]
@olksdr maybe you or your team have ideas what's going on?

**Comment by loewenheim** [comment]
Hi, sorry, I looked into it but couldn't reproduce it.

**Comment by mkdotcom** [comment]
Hi, can't you directly check the issue on my sentry.io account?

**Comment by loewenheim** [comment]
That issue only has the one event.

**Comment by mkdotcom** [comment]
Isuue not showing up on new crash reports, I guess we could closed this ticket.

**Comment by loewenheim** [comment]
Please let us know if it happens again!
