### ISSUE TITLE
Proposal: Make DSN suffix non-sequential

### ISSUE THREAD

**Issue by SeMeKh** [getsentry/sentry#7989]
Currently, the project id is shown in DSN, which makes it leak a bit of information about the number of projects hosted on an instance. It's not a serious issue, but could be considered undesirable in specific environments.

I'd like to see if you're willing to merge a PR fixing the issue, and if so, what your preferred approach is.

**Comment by mitsuhiko** [comment]
For self hosted instances you can just bump up the project ID by increasing the postgres sequence.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
