### ISSUE TITLE
Duplication of dashboards is broken

### ISSUE THREAD

**Issue by fabriciolemos** [getsentry/sentry#79969]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the Dashboard page in https://sentry.io/dashboards
2. Click on the kebab menu (three dots) at the bottom right of any dashboard
3. It opens the chosen dashboard page, without duplicating it https://sentry.io/dashboard/DASH_ID

![Image](https://github.com/user-attachments/assets/705deee0-1bd0-4abb-9775-0687d4ee0c00)

### Expected Result

It should duplicate the dashboard when we click "Duplicate"

### Actual Result

It is just opening the Dashboard page without duplicating it.

### Product Area

Dashboards

### Link

https://sentry.io/dashboards

**Comment by ale-cota** [comment]
Additional details from Discord conversation:
> It functions well in Safari. However, in Chrome, I logged out and cleared the cache, yet the issue persists.
> And in Chrome, it does not even create the copy sometimes. I was able to replicate it again, but it's not consistent.

We'll get back to you once we manage to find something. Thanks again!

**Comment by gggritso** [comment]
@fabriciolemos thanks for raising this! Could you open the URL `chrome://version` and paste the version string? Should look something like "130.0.6723.92 (Official Build) (arm64)"

**Comment by gggritso** [comment]
@fabriciolemos this is a tricky one! We couldn't reproduce this bug, but we have a hypothesis for why it's happening. The fix is in production, give it a try 👍🏻

**Comment by fabriciolemos** [comment]
> [@fabriciolemos](https://github.com/fabriciolemos) this is a tricky one! We couldn't reproduce this bug, but we have a hypothesis for why it's happening. The fix is in production, give it a try 👍🏻

It's working now, thank you! Sorry I missed the msg above.
