### ISSUE TITLE
Add Plugin Types

### ISSUE THREAD

**Issue by texdc** [getsentry/sentry#8003]
Please add typings for the plugins.

- The version of Sentry you're using
`"raven-js": "^3.24.1"`
- Whether you're using Docker or another installation method
yarn
- Include a stacktrace or other logs when relevant
N/A
- Include a redacted version of your configuration when relevant
```ts
import RavenVue from 'raven-js/plugins/vue' // no typing available
```
In order to remove compilation warnings about implicit 'any', I need to disable strict checking to import the Vue plugin.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
