### ISSUE TITLE
Unable to Edit Alert Rule - Changes Not Saved

### ISSUE THREAD

**Issue by dalnoki** [getsentry/sentry#80049]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Navigate to the alert rules page.
2. Select an alert rule to edit.
3. Add a new filter to the rule.
4. Click "Save" to confirm the changes.
5. Reopen the alert rule by clicking "Edit" again.

for more information please see the internal jira ticket.

### Expected Result

 The newly added filter should persist after saving and be visible when editing the alert rule again.

### Actual Result

The newly added filter does not appear upon re-editing, suggesting the changes are not saved.

### Product Area

Alerts

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2332) by [Unito](https://www.unito.io)

**Comment by ceorourke** [comment]
This should be resolve now, let me know if you still have any problems.
