### ISSUE TITLE
Add tracing headers to task activations

### ISSUE THREAD

**Issue by markstory** [getsentry/sentry#80054]
As task namespaces create messages for tasks, they should append the current tracing context (trace_id, baggage) as headers to task messages.

**Comment by evanh** [comment]
Talked to Anton P. about this, and he suggested adding a Kafka integration to the SDK as a way to do this. His suggestion:

About the kafka support. If you could create a very simple pyrhon file that puts a message into kafka and another script that processes that message this could get us started to add kafka support.
