### ISSUE TITLE
Metric Alert Filter events section can not be saved or edited.

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#80057]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a new or open an old Metric Alert.
2. For section 2 either add a filter rule, or attempt to edit the existing ones
3. Save the alert.
4. See a successful PUT request to `alert-rules`
5. reopen the alert and see that the conditions did not change.

Here is a quick video I made in a test org ([Link to alert](https://francisorg.sentry.io/alerts/rules/details/216635/))-

https://github.com/user-attachments/assets/8d8feba5-7b08-4d03-99d1-564846f5b40b

### Expected Result

Filters should change.

### Actual Result

Filters do not change, and it looks like we are making the PUT request with the query from before the filter change.

### Product Area

Alerts

**Comment by ceorourke** [comment]
This should be resolve now, let me know if you still have any problems.
