### ISSUE TITLE
Empty Discover export when filtering data based on custom measurement.

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/sentry#80068]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Add custom measurements to transactions
2. Create a discover search to see the information
3. filter based in a value for that measurements
4. create an export
5. Download the csv export.

Code and affected user organisation are available on [this link ](https://sentry.zendesk.com/agent/tickets/136714)

### Expected Result

The csv has the information in the discover table

### Actual Result

The number of samples on the page is 0 but the graph and table are populated with data. The downloaded CSV has no information. 

I was not able to [reproduce on my organisation.](https://dev-curumas.sentry.io/discover/homepage/?dataset=transactions&field=title&field=project&field=measurements.my.critical.measure&field=timestamp&name=All%20Errors&project=5242419&query=has%3Ameasurements.my.critical.measure%20measurements.my.critical.measure%3A%3E%3D300&queryDataset=transaction-like&sort=-timestamp&statsPeriod=14d&yAxis=count%28%29).

![Image](https://github.com/user-attachments/assets/27f94d7b-d0b0-4bf5-b30d-06c86e3cbb3c)

### Product Area

Discover

**Comment by shruthilayaj** [comment]
Thanks for the report, I'll look into this soon!

**Comment by shruthilayaj** [comment]
@rodolfoBee this happened because of custom units attached to the measurement which wasn't handled as expected in two of our endpoints. Fix was merged yesterday, this should work as expected now, please let me know if that's still not the case
