### ISSUE TITLE
Duration values in dashboards non-deterministic

### ISSUE THREAD

**Issue by landenai** [getsentry/sentry#80067]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a new dashboard in sentry.io
2. Add a new widget
3. Set visualization to bar chart
4. Select Transactions as dataset 
5. In step 4, select p50 and p75 of `transaction.duration` 
6. save widget
7. Observe p75 from a date in the past on the bar chart, refreshing several times and noting the value

### Expected Result

Since we're observing data from the past, it is expected that the same p75 value is observed with each refresh 

### Actual Result

The p75 value varies each time the widget is refresehed.

### Product Area

Dashboards

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2369) by [Unito](https://www.unito.io)

**Comment by wmak** [comment]
Closing in favour of https://github.com/getsentry/snuba/issues/6661

But to address the issue, percentiles are non-deterministic for performance reasons. They should still be _roughly_ accurate, but between refreshes there is no guarantee you will get the same exact value.
