### ISSUE TITLE
Resending invite to members removes them from the teams they've been assigned

### ISSUE THREAD

**Issue by crivetechie** [getsentry/sentry#80063]
Our SaaS Organization is using Google Auth with SCIM disabled; we are managing Sentry members, teams and team membership using terraform.

We've observed an issue that we believe isn't working as expected: resending an invite to a member via the Sentry UI is removing the member from all teams the member has been assigned to.
We think resending invite shouldn't change the team membership of the member.

Can you confirm is this is how it resending invite is intended to work? If not, can the issue be addressed?

Also, since we have Google Auth enabled: is there any need to invite members? Maybe the button could be disabled?

**Comment by leedongwei** [comment]
@crivetechie You can use JIT provisioning for your members, since you have Google OAuth on your organization. An account will be created for them, and they'll be added into your org upon login. The downside is that they'll not be assigned to teams.

I'll get the team to review the invitation flow. You should keep your team assignment even after resending invites.

**Comment by crivetechie** [comment]
Thanks for the feedback @leedongwei 
JIT provisioning is working but we are creating members and teams using an automation, this works fine. The only issue is with sending the invitation: we don't need this but if we accidentally resend the invite (manually, via UI) the team assignment gets reset.
It would be great if the resend invitation flow wouldn't reset the team assignment or if the button to resend the invites was hidden/disabled if JIT is enabled.

We can of course instruct admins to avoid sending the invite again in the meantime.

**Comment by ameliahsu** [comment]
@crivetechie We've fixed this problem in our invitation flow, members should no longer lose their team assignments after resending invites now. Thanks for catching this!
