### ISSUE TITLE
Using Modals in Vue causes Session Replay viewing difference between browsers

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#80116]
### Problem Statement

Using the latest version of Vue SDK and updated dependencies

With using Modals, viewing the same session replay in the UI in Chrome the overlay causes a grey background, so you're still able to view the background. In Firefox the overlay causes a black background resulting in it being unviewable for the same replay. This is a repeatable behavior; I can confirm there are no ad blockers or extensions resulting in this issue. 

Latest version of both browsers 

Example replay links as well as a screen recording can be found in internal ticket #135567

### Product Area

Replays

**Comment by bruno-garcia** [comment]
Thanks for raising this. We didn't have a chance to debug this yet but I'll reply here as soon as we do

**Comment by billyvg** [comment]
This should be fixed by https://github.com/getsentry/sentry/pull/81199
