### ISSUE TITLE
Issues - Ownership rules send through API - Char limit of 100000 prevents from further adopting this feature

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#80125]
### Problem Statement

One of our developer is uploading a codeowners file using sentry api. This file is used to map issues in Sentry with the appropriate feature tea,.
While doing this api request, he gets an error "Raw needs to be < 100000 chars" (PFA screenshot). This is the api that he is using - https://sentry.io/api/0/projects/ing/one-web/ownership/. 

Do you know if there is anyway to bump these characters length? Because the features file will increase in future with more new features coming in.

### Product Area

Issues

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2334) by [Unito](https://www.unito.io)

**Comment by Angelodaniel** [comment]
Seems to be discussed here: https://github.com/getsentry/sentry/issues/80125
but no solution has been provided

**Comment by mrduncan** [comment]
> Seems to be discussed here: [#80125](https://github.com/getsentry/sentry/issues/80125) but no solution has been provided

That links back to this ticket, is there a different ticket you're referencing?

> Do you know if there is anyway to bump these characters length? Because the features file will increase in future with more new features coming in.

I'm going to close this for now as 100K is our default limit but will open an internal thread as we have options to raise it in some situations.
