### ISSUE TITLE
[Hydration Errors] No visual difference or HTML difference in HE Issue

### ISSUE THREAD

**Issue by jas-kas** [getsentry/sentry#80153]
More details in this [specific user feedback report](https://sentry.sentry.io/feedback/?feedbackSlug=javascript%3A6035536852&project=11276).

**Comment by jas-kas** [comment]
cc/ @ryan953 @billyvg Can either of you look into the visual difference? I'm unaware of this being an existing issue

**Comment by billyvg** [comment]
I haven't looked at it yet, but I think it's possible that we're unable to capture the hydration error because Replay is loaded too late (e.g. after hydration occurs).

**Comment by jas-kas** [comment]
Closing as stale
