### ISSUE TITLE
Add export functionality to issues, or allow issue related filtering in "Discover"

### ISSUE THREAD

**Issue by gadileshem** [getsentry/sentry#80160]
### Problem Statement

In discover it is useful to export the filtered content to allow further analysis externally. 
It is impossible however to filter by "assigned" for example.

In "Issues" one can filter by Assigned, but can't export. 

Some fields can be used in both displays... but not Assigned. 
We would like to export entries based on "Assigned" filtering 

### Product Area

Unknown

**Comment by leeandher** [comment]
Hi there, thanks for writing in.

Unfortunately the datasets queried by Discover are used for aggregating event and span data across projects/issues and do not currently have access to the all the properties of the issues themselves, such as `assignee`. This may change in the future, but there are no plans to do so at the moment.

The export feature was custom built for Discover and Issue Event Data, so would need to be extended for Issue Data, which is not something the team currently has the bandwidth to take on.

I'll be closing out this issue as it's not something the team will be able to prioritize, but here are some alternative solutions:

1. Use the stats page for team level insights into issue related data - https://sentry.io/stats/issues/
2. Use our public API for aggregating the data directly - https://docs.sentry.io/api/events/list-a-projects-issues/
