### ISSUE TITLE
There has been no data since connecting to Sentry

### ISSUE THREAD

**Issue by long1012** [getsentry/sentry#80174]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

![Image](https://github.com/user-attachments/assets/b50ba3bd-1f34-4756-b3e6-f1ec649b3841)

### Expected Result

Can display data normally

### Actual Result

![Image](https://github.com/user-attachments/assets/6616508f-7eff-452a-90d3-1efe984f2660)

### Product Area

Unknown

**Comment by long1012** [comment]
> 你好[@long1012](https://github.com/long1012)您能否创建[一张支持票](https://sentry.zendesk.com/hc/en-us/requests/new)以便我们直接帮助您？



> Hi [@long1012](https://github.com/long1012) could you please create [a support ticket](https://sentry.zendesk.com/hc/en-us/requests/new) so we can help you directly?

I don't understand, what do I need to do?

**Comment by long1012** [comment]
> Hi [@long1012](https://github.com/long1012) could you please create [a support ticket](https://sentry.zendesk.com/hc/en-us/requests/new) so we can help you directly?

I don't understand, what do I need to do?

**Comment by hubertdeng123** [comment]
You should create a support ticket in zendesk so our support team can help. Filing issues here are mostly for product related issues. Going to go ahead and close this.
