### ISSUE TITLE
Since a few weeks ago, pressing "AI Solution" says "There was an error loading data."

### ISSUE THREAD

**Issue by melyux** [getsentry/sentry#80171]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to any error
2. Press "AI Solution"
3. It says: "There was an error loading data."

### Expected Result

Expected the AI Solution.

### Actual Result

"There was an error loading data."

I'd show a screenshot, but GitHub image uploading is broken.

### Product Area

Issues - Suggested Fix

**Comment by jennmueng** [comment]
Hey @melyux, is the "AI Suggestion Solution" toggle enabled in your organization settings? Regardless, we are actually going to be fully sunsetting the feature in the coming weeks for the much more powerful [Autofix](https://techcrunch.com/2024/03/20/sentrys-ai-powered-autofix-helps-developers-quickly-debug-and-fix-their-production-code/?guccounter=1).

![Image](https://github.com/user-attachments/assets/7bd03b3f-c6e3-4257-a4d5-616cde827da7)

**Comment by melyux** [comment]
@jennmueng Yep it's on. ![image](https://github.com/user-attachments/assets/ad071ed3-5b1c-4eb5-a63d-293b95dd9158)

And that's great but hoped to use the AI feature these few weeks, which are critical for us, since it's pretty helpful sometimes.

**Comment by melyux** [comment]
Sure, that'd be great

**Comment by jennmueng** [comment]
Sorry for the late reply, missed the notification, mind shooting me your organization slug at jenn@sentry.io?
