### ISSUE TITLE
Visualize issues with charts

### ISSUE THREAD

**Issue by kevinschaich** [getsentry/sentry#80170]
### Problem Statement

I can't chart issues like events or transactions. I get `This dataset is restricted to tabular visualization` if I try to visualize issues on a bar chart.

This is really useful to map over time to see how we're doing in terms of resolution.

![Image](https://github.com/user-attachments/assets/168f78a2-bbdb-4cbd-91b2-ab58c977f605)

### Solution Brainstorm

Make issues have the same visualization options as events and transactions

### Product Area

Dashboards

**Comment by ale-cota** [comment]
Hi, @kevinschaich! Thanks for submitting the request. We already have an issue on our backlog for this enhancement, so please follow that one: https://github.com/getsentry/sentry/issues/68166 

We're planning to do some enhancements on the Issues dataset, including more visualisation options, but this will only be sometime next year.
