### ISSUE TITLE
How to download attachments in Event?

### ISSUE THREAD

**Issue by end-former-LAH** [getsentry/sentry#80232]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

How to download attachments in Event?

### How are you getting stuck?

I want to download file in the attachments of Event

### Where in the product are you?

Unknown

**Comment by InterstellarStella** [comment]
Hi @end-former-LAH if you are looking to download minidumps from the events, you need change the `Store Native Crash Reports` option under `Security and Privacy` settings from `disabled` to any other option depending on how many reports you want to keep. This can be done either at the organisation level or at the project level.

For other attachments, you can go to the `Attachments` tab when looking at an issue's details, and download them one-by-one.

If you are still having trouble with downloading attachments, please feel free to open a support ticket [here](https://sentry.zendesk.com/hc/en-us/requests/new) so we can assist you directly.
