### ISSUE TITLE
Dead click false positive on "select a file" input field

### ISSUE THREAD

**Issue by THdeCamargoJ** [getsentry/sentry#80275]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Hi,

I'm having some trouble trying to understand dead click alerts in one of the apps I'm working on.

### How are you getting stuck?

There is a drop file field with a “choose a file” button which is identified as a dead click by Sentry whenever clicked. However, when I check the replay, there are no issues with its functionality. It seems to me that this is one of the false positives mentioned in issues #48259 and #60826, such as the downloaded file event example. I just wanted to make sure that this is the case and that this type of issue can be ignored.

Thank you for your time.

### Where in the product are you?

Replays

**Comment by billyvg** [comment]
@THdeCamargoJ Looks like we should be ignoring these input fields already -- can you link to the replay where this is happening?

**Comment by THdeCamargoJ** [comment]
> [@THdeCamargoJ](https://github.com/THdeCamargoJ) Looks like we should be ignoring these input fields already -- can you link to the replay where this is happening?

I'll ask my superiors for permission!

**Comment by billyvg** [comment]
@THdeCamargoJ feel free to email directly to me: billy at sentry.io

**Comment by THdeCamargoJ** [comment]
@billyvg, thank you for your help!

For anyone facing the same issue: it seems that the opening of a file upload dialog cannot be detected by Sentry, thus generating the false positive. The proposed solution is to manually ignore these warnings.
