### ISSUE TITLE
Send emails to users via Sentry

### ISSUE THREAD

**Issue by matt-weiner-s** [getsentry/sentry#80279]
### Problem Statement

It would be very nice if there was a ability to message/email people from Sentry or send a message to all Sentry users, or to certain teams.

As in this email is coming from Sentry, not "me".

Additional things I have found helpful are banners for announcements, things like that.

### Product Area

Unknown

**Comment by rachrwang** [comment]
@matt-weiner-s - are you referring to the weekly report? That email is currently sent to all users, not just admins

**Comment by matt-weiner-s** [comment]
Well like I get additional emails when we are nearing our quota, hit our quota, etc. those would just be a nice to have if I we could have it sent to all users.  Last time that happened I think I checked with some users and they didn’t receive those emails (I could be wrong).

Thanks,

Matthew Weiner
Product Owner & Software Engineer - DevOps

[A close up of a logo  Description automatically generated]
Symetra® is a registered service mark of Symetra Life Insurance Company. www.symetra.com<http://www.symetra.com/>

***@***.***?anonymous&ep=signature>Book time to meet with ***@***.***?anonymous&ep=signature>

From: Rachel Wang ***@***.***>
Date: Monday, November 11, 2024 at 4:03 PM
To: getsentry/sentry ***@***.***>
Cc: Matt Weiner ***@***.***>, Mention ***@***.***>
Subject: Re: [getsentry/sentry] Send emails to users via Sentry (Issue #80279)
This message originated from outside Symetra. Be cautious of unfamiliar links and attachments.


@matt-weiner-s<https://github.com/matt-weiner-s> - are you referring to the weekly report? That email is currently sent to all users, not just admins

**Comment by rachrwang** [comment]
Got it, thanks! cc @brianthi - an idea for expanding the audience for billing notifications

**Comment by brianthi** [comment]
Hi @matt-weiner-s, those notifications you're referring to are our spend notifications which have the capability to send to all users on both email and Slack. There are two settings which control this, an org wide setting in sentry.io/settings/billing/notifications/, which controls the thresholds at which these notifications get sent, and a per user setting accessible only while logged into that users account at sentry.io/settings/account/notifications/quota/. I believe users in your org have turned off spend notifications so you'll just need to let them know to turn them back on. Here are some docs which reference the notification settings I'm referring to.

**Comment by matt-weiner-s** [comment]
Hello, ok that is great to know, thanks!

Matthew Weiner
Product Owner & Software Engineer - DevOps

[A close up of a logo  Description automatically generated]
Symetra® is a registered service mark of Symetra Life Insurance Company. www.symetra.com<http://www.symetra.com/>

***@***.***?anonymous&ep=signature>Book time to meet with ***@***.***?anonymous&ep=signature>

From: Brian Thi ***@***.***>
Date: Tuesday, November 12, 2024 at 10:42 AM
To: getsentry/sentry ***@***.***>
Cc: Matt Weiner ***@***.***>, Mention ***@***.***>
Subject: Re: [getsentry/sentry] Send emails to users via Sentry (Issue #80279)
This message originated from outside Symetra. Be cautious of unfamiliar links and attachments.


Hi @matt-weiner-s<https://github.com/matt-weiner-s>, those notifications you're referring to are our spend notifications which have the capability to send to all users on both email and Slack. There are two settings which control this, an org wide setting in sentry.io/settings/billing/notifications/, which controls the thresholds at which these notifications get sent, and a per user setting accessible only while logged into that users account at sentry.io/settings/account/notifications/quota/. I believe users in your org have turned off spend notifications so you'll just need to let them know to turn them back on. Here are some docs which reference the notification settings I'm referring to.

**Comment by mifu67** [comment]
Closing as this seems to be resolved.
