### ISSUE TITLE
`OS` distribution not showing up nicely in the UI

### ISSUE THREAD

**Issue by pontello** [getsentry/sentry#80313]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Send the os distribution as described in [this doc](https://develop.sentry.dev/sdk/data-model/event-payloads/contexts/#example-os-context).

### Expected Result

OS distribution fields not displayed as JSON on the UI.

### Actual Result

![Image](https://github.com/user-attachments/assets/8971d704-43b9-4eda-bd61-d67ceef2dac4)

### Product Area

Issues

**Comment by leeandher** [comment]
@pontello Thanks for surfacing this! If we've documented it as expected, it should definitely _look_ like it's expected. I'll take a look at this. There are likely other fields that are getting incorrectly rendered as JSON in these context cards as well.
