### ISSUE TITLE
Absolute date picker removes number of releases from project

### ISSUE THREAD

**Issue by JLuse** [getsentry/sentry#80415]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Navigate to a project - https://sentry.sentry.io/projects/sentry/?project=1&statsPeriod=14d
2. Change date to any "Absolute Date" range - https://sentry.sentry.io/projects/sentry/?end=2024-11-08T07%3A59%3A59&project=1&start=2024-10-24T07%3A00%3A00

### Expected Result

Release section to be populated:
![Image](https://github.com/user-attachments/assets/8313aef2-70d9-4dd6-b4aa-d9608f408254)

### Actual Result

![Image](https://github.com/user-attachments/assets/5e18ffbb-fc50-4c5a-9eb4-f953b0fded4f)

### Product Area

Projects - Project Details

**Comment by leeandher** [comment]
Addressing in #80482! Thanks for the report
