### ISSUE TITLE
Postman/Raw HTTP client POST to envelope returns 200 but not displayed in dashboard

### ISSUE THREAD

**Issue by Hussain-f** [getsentry/sentry#80434]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Following on from support query 136895, I am unable to send HTTP requests directly to Sentry envelope API. I appreciate I can use the Sentry SDK as your colleague Tony pointed at numerously, however I would prefer to get this working via postman, and subsequently via a raw HTTP client within a Kotlin codebase.

I have attached multiple screen recordings to the support query which you can hopefully access. In the latest reply from your support colleague, I was given an example payload to try, which I did from both Postman and the Sentry provided Postman collection. Neither worked, with the response being a bad request.

I am able to get a successful 200 response when sending a POST to https://ffxxx@oxxxxx.ingest.us.sentry.io/api/{project_id}/envelope/
The JSON body within the POST request is as below

`{
    "event_id": "9ec79c33ec9942ab8353589fcb2e09cd",
    "sent_at": "2024-10-02T17:41:36Z",
    "dsn": "https://ffxx@oxxxxx.ingest.us.sentry.io/{project_id}",
        "type": "issue",
    "platform": "kotlin",
    "level": "fatal",
    "check_in_id": "83a7c03ed0a04e1b97e2e3b18d38f244",
    "monitor_slug": "my-monitor",
    "status": "in_progress",
    "duration": 10.0,
    "release": "1.0.0",
      "errors": [
    {
      "type": "unknown_error",
      "path": "/var/logs/errors.log.1",
      "details": "Failed to read attachment"
    }
  ]
}`

However the event is not displayed on the dashboard.

I have experimented with sending an event from sentry-cli and copying the JSON of the event directly from Sentry dashboard. I have then used this exact same JSON (with the event_id) changed, and I get a 200 response but nothing showing on the dashboard.

### Expected Result

Sentry event showing on the dashboard, which is sent from Postman and raw HTTP client

### Actual Result

Receiving 200 response in postman but event not showing on dashboard

[sentry proof - 01.zip](https://github.com/user-attachments/files/17670859/sentry.proof.-.01.zip)
[sentry_proof.zip](https://github.com/user-attachments/files/17670858/sentry_proof.zip)
[sentry-cli-copy.zip](https://github.com/user-attachments/files/17670860/sentry-cli-copy.zip)

### Product Area

APIs

**Comment by InterstellarStella** [comment]
Original ticket [here](https://sentry.zendesk.com/agent/tickets/136895).

**Comment by sentaur-athena** [comment]
This particular API is not maintained by our team so rerouting to ingest.

**Comment by Hussain-f** [comment]
I'm presuming all your SDK integrations use a raw HTTP client under the hood, which send payloads containing errors, traces, breadcrumbs etc to the same API '/envelope'?

**Comment by Dav1dde** [comment]
The Endpoint does not include the secret key in the URL: `https://o{org_id}.ingest.{region}.sentry.io/api/{project_id}/envelope/`, on a successful submit you will get a the event id returned as JSON.

For example:
```sh
ORG_ID=1
PROJECT_ID=12345
SECRET_KEY=abcdef

curl "https://o${ORG_ID}.ingest.us.sentry.io/api/${PROJECT_ID}/envelope/?sentry_key=${SECRET_KEY}" \
    --data-raw $'{}\n{"type":"event"}\n{"message":"Hello, World!"}\n'
```

Looking at your video, it seems like:
- The URL is wrong, you're using the DSN as the base, which is not the ingestion endpoint (no `@` should be in the URL)
- The URL does not contain `/api/`
- The payload you're sending is not an [envelope](https://develop.sentry.dev/sdk/data-model/envelopes/), just the event.

**Comment by pokepoke81** [comment]
I am experiencing the same issue. I am sending a post to  https://o4508241690558464.ingest.us.sentry.io/api/4508247239557120/envelope with my security key in the header as X-Sentry-Auth. 

My payload is:
`{"extra":[{"key":"repeats","value":null}],"event_id":"df2cd9a3-6453-4d20-8bcd-43b263b0f9a0","timestamp":"2024-11-06T13:17:30.461-08:00","platform":"Other","level":"Error","transaction":"j-APXnFWLD-XF6kL3","server_name":"[https://app.workato.com/recipes/55624345/job/j-APXnFWLD-XF6kL3","errors":[{"details":"","value":null,"type":"fatal"}],"tags":[{"value":"TT.1.1](https://app.workato.com/recipes/55624345/job/j-APXnFWLD-XF6kL3%22,%22errors%22:[%7B%22details%22:%22%22,%22value%22:null,%22type%22:%22fatal%22%7D],%22tags%22:[%7B%22value%22:%22TT.1.1) Process Monthly Invoices","key":"Recipe"}],"fingerprint":[{"value":"j-APXnFWLD-XF6kL3"},{"value":"55624345"}],"type":"event”}`

I receive a 200 reply and was given the event ID df2cd9a364534d208bcd43b263b0f9a0 back in the response, which is the same event_id that I passed in the request.

**Comment by Dav1dde** [comment]
The payload is missing the envelope header and event header.

**Comment by pokepoke81** [comment]
Thank you. I was very confused by the documentation, but I see what you mean by headers now and importance of newlines. I was assuming that headers meant HTTP headers. I've been able to get this working now. I would recommend making a graphic that calls out the format more clearly:

Envelope header -> {"event_id":"9ec79c33ec9942ab8353589fcb2e04dc","dsn":"https://e12d836b15bb49d7bbf99e64295d995b:@sentry.io/42"}\n
Item header -> {"type":"attachment","length":10,"content_type":"text/plain","filename":"hello.txt"}\n
Item payload -> \xef\xbb\xbfHello\r\n\n
Item header -> {"type":"event","length":41,"content_type":"application/json","filename":"application.log"}\n
Item payload -> {"message":"hello world","level":"error"}\n

**Comment by Hussain-f** [comment]
Ive also got it working but I second what @pokepoke81 said. The documentation isn't too clear IMO. What through me off was sending a JSON payload when the body doesn't adhere to JSON syntax.

Also, i've noticed an empty envelope header works fine too. That is, no DSN or event_id provided. So I guess a blank envelope header works fine.
