### ISSUE TITLE
remove sentry from a specific Jira Project

### ISSUE THREAD

**Issue by marco-lendbuzz** [getsentry/sentry#80450]
### Environment

SaaS (https://sentry.io/)

### What are you trying to accomplish?

Hello, I want to remove Sentry plug-in from my specific project in (Jira Service Management) without uninstalling and affecting other projects.

### How are you getting stuck?

I don't see the option to remove, only see an option to uninstall. 

### Where in the product are you?

Other

**Comment by sentaur-athena** [comment]
It's not clear to me what integration you're talking about. Is it called `Jira (Legacy)` in your integration settings on Sentry? If so plugins are deprecated and we don't provide support for them moving forward. We highly encourage uninstalling it and using the Jira integration.

**Comment by sentaur-athena** [comment]
@marco-lendbuzz what is your organization slug? (If you don't want to share it in a public ticket, please feel free to file a support ticket)

**Comment by marco-lendbuzz** [comment]
https://lendbuzz.atlassian.net/

**Comment by marco-lendbuzz** [comment]
> [@marco-lendbuzz](https://github.com/marco-lendbuzz) what is your organization slug? (If you don't want to share it in a public ticket, please feel free to file a support ticket)

https://lendbuzz.atlassian.net/

**Comment by sentaur-athena** [comment]
I just checked and your integration is our first party Jira integration. The integration doesn't support project by project access but it's a reasonable feature. Adding it to backlog to get back to it.

**Comment by GabeVillalobos** [comment]
This feature request looks like a duplicate of https://github.com/getsentry/sentry/issues/80532. Closing this for now.
