### ISSUE TITLE
Transparency in Uploaded Avatar reveals letter avatar underneath

### ISSUE THREAD

**Issue by MaxBittker** [getsentry/sentry#8047]
when an uploaded or gravatar based avatar included transparent pixels, the way avatars render stacked means that the letter leaks out from underneath. it should probably be white underneath.

**Comment by coportian-harshit** [comment]
I would like to contribute to solving this issue. @MaxBittker please help by explaining in detail.

**Comment by theharshitgarg** [comment]
I am interested in taking this issue. please help explain me in detail.
