### ISSUE TITLE
normalize double slash in SENTRY_DSN to avoid 403 CSRF error

### ISSUE THREAD

**Issue by lambdaq** [getsentry/sentry#8049]
I am using the latest on-premise docker image of sentry

in [sentry/models/projectkey.py](https://github.com/getsentry/sentry/blob/master/src/sentry/models/projectkey.py#L165)

the `return '%s%s?sentry_key=%s'` syntax has a serious potential bug.

If in `/manage/settings` -> General -> Root URL we have an ending tail slash, then at the page

`XXX/XXX_proj/settings/keys/`  the DSN, CSP endpoint would have duplicate double slash

Others have reported the bug ealier https://forum.sentry.io/t/csrf-verification-failed/2901

We should normalize the DSN URL.

Beside, on [403-csrf-falure.html](src/sentry/templates/sentry/403-csrf-failure.html) we should add extra notes for this behavior.

**Comment by yellowiscool** [comment]
I think this could be a very good improvement, as I just lost time thanks to a stupid tail slash.

**Comment by disappear89** [comment]
Please merge :D

**Comment by ensirius** [comment]
Bump

**Comment by BYK** [comment]
I think this is from the same root cause by #8657. Closing in favor of that.
