### ISSUE TITLE
Stats page 30-Day view broken for Errors & Spans

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#80515]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

**StepsToReproduce**
1. https://demo.sentry.io/stats/?project=5808623&statsPeriod=30d for errors or https://demo.sentry.io/stats/?dataCategory=spans&project=5808623&statsPeriod=30d for Spans
2. or start on a different page then click Stats, same problem

1HR and 90D views works fine

**Tried**
- selecting 1 project, vs. unselecting it for All Projects. same problem
- empty cache and hard reload
- Chrome, then Safari, same problem
- logging out of sentry org and back in.
- seeing nothing notable in Chrome.Console dev tools for errors.
- AbsoluteDate for a 30Day selection also doesn't work

slack convo with real orgs I encounter this problem in too
https://sentry.slack.com/archives/CGE1QHNSH/p1731317384484769?thread_ts=1730737391.662429&cid=CGE1QHNSH

### Expected Result

should not be a blank graph with 0 events

### Actual Result

Stats graph chart is blank
![Image](https://github.com/user-attachments/assets/65def934-4056-4535-af7e-ede05f9c74f5)

### Product Area

Stats

### Link

https://demo.sentry.io/stats/?project=-1&statsPeriod=30d

**Comment by brianthi** [comment]
Closing this as it was confirmed to not be reproducible by @thinkocapo
