### ISSUE TITLE
Dashboards - Widget shows different times when opened full screen with fixed date selection

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#80525]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to last 7 days
2. Click on table widget full screen mode
3. See difference in numbers due to refetching of query

https://demo.sentry.io/dashboard/54232/widget/8/?project=6249899&statsPeriod=30d

When using fixed timeframe instead of Last X days it stays the same 

### Expected Result

Numbers to be the same and not re-fetched somehow

### Actual Result

Different numbers
![Image](https://github.com/user-attachments/assets/81c14b9a-91cd-4fb8-8fdb-748e3289be69)

### Product Area

Dashboards

### Link

https://demo.sentry.io/dashboard/54232/widget/8/?project=6249899&statsPeriod=30d

**Comment by gggritso** [comment]
@Angelodaniel thanks for raising this! As you pointed out there are a few overlapping bugs here. The main one is re-fetching of the data, which we'll fix first. I'll post an update as we make progress, this is somewhat complicated.
