### ISSUE TITLE
The network in the web console uploaded data a month ago, but the Session Replay has no data。

### ISSUE THREAD

**Issue by zhuoyu1994** [getsentry/sentry#80545]
### Self-Hosted Version

23.6.2

### CPU Architecture

unknown

### Docker Version

unknown

### Docker Compose Version

unknown

### Steps to Reproduce

![Image](https://github.com/user-attachments/assets/0de9c1b8-7448-4e8b-afbf-bf72dcb99d72)
![Image](https://github.com/user-attachments/assets/d4e6adb8-1b19-4fc9-83ec-5f08ec04289a)

### Expected Result

Normal display data。

### Actual Result

![Image](https://github.com/user-attachments/assets/c0cf42b4-12df-4eed-94c5-e26f2119e1a3)

**Comment by bruno-garcia** [comment]
I'm not sure how to start diagnosing this issue.
Do you see any logs from Relay? In the Stats page, do you see data being dropped?

Data was uploaded a month ago, meaning you saw it in Sentry a month a go? What's ur data retention?

**Comment by zhuoyu1994** [comment]
> I'm not sure how to start diagnosing this issue. Do you see any logs from Relay? In the Stats page, do you see data being dropped?
> 
> Data was uploaded a month ago, meaning you saw it in Sentry a month a go? What's ur data retention?

There is no data on the Relay page. Stats page has data.
![Image](https://github.com/user-attachments/assets/264a7eb4-0a0f-4395-8ad0-e6c4fbf93b80)

**Comment by bruno-garcia** [comment]
> > I'm not sure how to start diagnosing this issue. Do you see any logs from Relay? In the Stats page, do you see data being dropped?
> > 
> > Data was uploaded a month ago, meaning you saw it in Sentry a month a go? What's ur data retention?
> 
> There is no data on the Relay page. Stats page has data.
> ![Image](https://github.com/user-attachments/assets/264a7eb4-0a0f-4395-8ad0-e6c4fbf93b80)
> 

that's showing errors. you can chance the data type in the selector, to Replays.

**Comment by zhuoyu1994** [comment]
> > > I'm not sure how to start diagnosing this issue. Do you see any logs from Relay? In the Stats page, do you see data being dropped?
> > > Data was uploaded a month ago, meaning you saw it in Sentry a month a go? What's ur data retention?
> > 
> > 
> > There is no data on the Relay page. Stats page has data.
> > ![Image](https://github.com/user-attachments/assets/264a7eb4-0a0f-4395-8ad0-e6c4fbf93b80)
> 
> that's showing errors. you can chance the data type in the selector, to Replays.

![Image](https://github.com/user-attachments/assets/3afb9cc8-6367-4624-a883-5859c30d5c59)
It's empty. I've been setting it up for months. The details of the issues have been mentioned.

**Comment by bruno-garcia** [comment]
Please reply to my question: _that's showing errors. you can chance the data type in the selector, to Replays._

You showed us stats for Errors:
![Image](https://github.com/user-attachments/assets/2f4a1050-9e9d-491e-b621-f3364fdd07b8)

**Comment by zhuoyu1994** [comment]
> Please reply to my question: _that's showing errors. you can chance the data type in the selector, to Replays._
> 
> You showed us stats for Errors: ![Image](https://github.com/user-attachments/assets/2f4a1050-9e9d-491e-b621-f3364fdd07b8)

Sorry. There is no replay option.
![Image](https://github.com/user-attachments/assets/7c5dfcdf-d5cb-4af0-b642-99e8c8bf35e2)

**Comment by bruno-garcia** [comment]
> Self-Hosted Version
> 23.6.2


Please update your Sentry server to the latest version.
