### ISSUE TITLE
Sentry sending email aggregates with issues not assigned to our team

### ISSUE THREAD

**Issue by Soniaroxana** [getsentry/sentry#8056]
We are receiving aggregate emails with issues that are assigned to other teams. Individual issue emails are sent to the appropriate teams as expected.

**Comment by dcramer** [comment]
@Soniaroxana are you perhaps confusing alerts with workflow emails? "Alerts" will go to every "Owner" (project members by default), unrelated to how they're assigned.

**Comment by Soniaroxana** [comment]
@dcramer we are using the Early access routing feature. Our understanding was that would only send the aggregate alerts to the teams in the individual routes. See our config below: 
![image](https://user-images.githubusercontent.com/8528395/38831233-53f309aa-4184-11e8-9f80-91cad755c83b.png)

New issue alerts are being sent to the individual teams just fine, but aggregate issue alerts are not.

**Comment by tkaemming** [comment]
This is in progress here: #7924

**Comment by ceorcham** [comment]
@Soniaroxana do you know if this issue was solved by #7924 ?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
