### ISSUE TITLE
[User Feedback API] Add Time to Query Parameters

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry#80663]
### Problem Statement

Using [List a Project User Feedback API](https://docs.sentry.io/api/projects/list-a-projects-user-feedback/), I want to provide a time period to retrieve user feedback.

### Solution Brainstorm

Add time period to query parameters.

### Product Area

User Feedback

**Comment by ryan953** [comment]
@dachakra I think you should look at using the issue API with a search term of `?query=issue.category:feedback` included. This will be more robust to search against than the feedback specific API

https://docs.sentry.io/api/events/list-a-projects-issues/

**Context**
The user-feedback system has two parts:
1. There is an older 'crash-reports' dialog and related API that required an error event as part of the payload. This has it's own set of api's which are missing the usual powerful filters like being able to request a specific date/time range.
2. There is a newer 'user feedback' widget, which is built on top of our issues api, which allows users to submit feedback with or without an associated error event.

The important bit is that data from the first, older, system is also sent into the issue platform, so you can query either kind of feedback!

So checkout that [issues api](https://docs.sentry.io/api/events/list-a-projects-issues/) and start with a query like this and see how it works for your use-case:

```bash
curl https://sentry.io/api/0/projects/{organization_id_or_slug}/{project_id_or_slug}/issues/?query=issue.category:feedback& statsPeriod=14d \
 -H 'Authorization: Bearer <auth_token>'
```
