### ISSUE TITLE
[User Feedback API] Extract More Properties from User Feedback API

### ISSUE THREAD

**Issue by dachakra** [getsentry/sentry#80662]
### Problem Statement

Using the [List a Project User Feedback](https://docs.sentry.io/api/projects/list-a-projects-user-feedback/ ) API, I want to extract properties such as: 

* Feedback Marked as Spam 
* Feedback Marked as Seen

### Solution Brainstorm

Add the above properties to the response payload: https://docs.sentry.io/api/projects/list-a-projects-user-feedback/ 

### Product Area

User Feedback

**Comment by aliu39** [comment]
Hi @dachakra , this endpoint is deprecated in favor of the [issue platform API](https://docs.sentry.io/api/events/list-a-projects-issues/). See the paragraph "User feedback items from the User Feedback Widget..". This endpoint will return a `hasSeen` field.

You can also get is_spam from this endpoint through the `status` field. To mark feedbacks as spam, we set `status` as `"ignored"`.
