### ISSUE TITLE
TypeError in Replays SDK - Cannot read properties of null (reading 'addEventListener')

### ISSUE THREAD

**Issue by gil-gross-glbe** [getsentry/sentry#80683]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

We're observing a significant number of errors in our production environment related to the Replays SDK. The error is in High volume reaching approximately 3.5M occurrences in a week.
![Image](https://github.com/user-attachments/assets/cca3395e-ebd1-43e2-9805-f654e30ef903)

Error occurs in the Sentry Replays bundle:
https://browser.sentry-cdn.com/7.119.2/bundle.tracing.replay.debug.min.js:2:209910

### Expected Result

The Replays SDK should properly handle element initialization and verify object existence before attempting to add event listeners.

### Actual Result

The SDK attempts to call addEventListener on a null object

### Product Area

Unknown

**Comment by billyvg** [comment]
@gil-gross-glbe thanks we'll take a look into this. I'm assuming this is happening in a normal browser environment? does this still occur if you turn off replays sampling?

can you email me with your org slug? billy at sentry.io -- I'd like to take a look into your account and make sure these errors get credited back to your account, as this shouldn't happen.

**Comment by chargome** [comment]
Hi @gil-gross-glbe!

So in this case the error does not actually occur in the SDK itself but rather in your application code on `<anonymous>:1:1182` – which is just wrapped by our SDK. Could you check if you can find this part of your bundle?

**Comment by AbhiPrasad** [comment]
Closing this for cleanup. If this issue still applies please re-open the issue! Thanks.
