### ISSUE TITLE
Ability to add Docker Container name that is visible on Issues Page

### ISSUE THREAD

**Issue by ReneGreen27** [getsentry/sentry#80721]
### Problem Statement

Customer would like the ability to add the Docker container name associated to an issue, that is visible on the Issues Page in the same way that the project and age of the issue show. While a tag is searchable, adding the container name with a tag would not be visible on the Issues Page, on Issue Details page. 

### Product Area

Issues

**Comment by mrduncan** [comment]
I'm going to close this in favor of #5572 which is a bit more general.
