### ISSUE TITLE
Issue without a squad.

### ISSUE THREAD

**Issue by NatashaZettler** [getsentry/sentry#80782]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

If you search on sentry assigned:none, we can the issue without a squad.

### Expected Result

When we search with this assigned:none query, the goal is no result show.

### Actual Result

![Image](https://github.com/user-attachments/assets/a047bf3b-a2ff-468d-a274-b3e569e16594)

### Product Area

Issues

### Version

sentry_flutter 8.9.0

**Comment by jangjodi** [comment]
Hi @NatashaZettler, the `assigned:none` query is meant to show issues where no one is assigned to it. Thus, this is the intended result.
