### ISSUE TITLE
No new releases since 8.22.0

### ISSUE THREAD

**Issue by MaggotMouth** [getsentry/sentry#8082]
Is there a release coming any time soon?
There hasn't been anything since Nov 17th, and afaik the docker images rely solely on versioning and not master branch for latest (as per https://github.com/getsentry/docker-sentry/blob/b7d55c572e0b23c5c537432211823a8677727e1c/8.22/Dockerfile#L56)

**Comment by mattrobenolt** [comment]
The next tagged release will be 9.0.0. A bunch of stuff is in flight lately as we prepare for this, so would rather not ship something half broken that's changing too rapidly. :)

**Comment by allixsenos** [comment]
https://forum.sentry.io/t/sentry-9-release/3850 says "by June 18th"
