### ISSUE TITLE
[Plugin] which version of Sentry correspond to description of new slack plugin

### ISSUE THREAD

**Issue by moooofly** [getsentry/sentry#8083]
## ENV

- The version of Sentry: 8.22.0
- installation: Docker

-----

after slack plugin being enabled, I get

![my](https://user-images.githubusercontent.com/7439290/38927380-285ccbea-4338-11e8-96c2-0c08d628a76b.png)

is different from 

![slack-global-integration-project-settings-add-workspace](https://docs.sentry.io/_images/slack-global-integration-project-settings-add-workspace.png)

But, I get no idea about the exact version being used above.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by BYK** [comment]
Btw you can check our new and improved guide for Slack if you are still interested: https://develop.sentry.dev/integrations/slack/
