### ISSUE TITLE
How to replays are stored for self-hosted?

### ISSUE THREAD

**Issue by Huskywannafly0** [getsentry/sentry#80881]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

I am trying to understand how to archive replays in a self-hosted environment.
While I find replays to be a very useful feature, I have concerns about how to archive them.

I have reviewed the documentation, but I couldn’t find much information specific to storage in self-hosted setups. 
Could you please clarify or direct me to any documentation related to self-hosted replay storage?

Thank you for your help.

### Expected Result

.

### Actual Result

.

### Product Area

Replays

### Version

24.1.0

**Comment by bruno-garcia** [comment]
On SaaS we use GCS. Not sure what's the self hosted version of that, file system somehow? @hubertdeng123 might know

**Comment by Huskywannafly0** [comment]
Hi @bruno-garcia, 

Thanks for you information. 
Could you please describe or direct me to any documentation related to workflow replay storage?

**Comment by cmanallen** [comment]
If you haven't configured a storage location Sentry will store files using the local filesystem.  Archiving a replay will delete related files from the filesystem.
