### ISSUE TITLE
New UI for Issues has very short space for Package names

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#80883]
This UI probably works well for Python and JS packages that tend to have a short name.
But for languages with namespaces or reverse domains, it'll word wrap almost all entries.

[Example event](https://sentry-sdks.sentry.io/issues/6069735749/?project=5428537&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=30d&stream_index=0)

![Image](https://github.com/user-attachments/assets/37aecbe6-5ba2-4d10-bc00-bcb8ecd98fa6)

### Solution brainstorm

Could the table adapt based on the content? E.g: Render 2 rows instead of 3 if X% of entries are longer than the width of the table?

I see it's responsive to a wider layout, adding a 4th row:

![Image](https://github.com/user-attachments/assets/d2005f08-983b-4f53-a526-4e1bb84f4cc5)

**Comment by jangjodi** [comment]
I'm closing this issue, as it looks like the new issue details changes fixed it <img width="562" alt="Image" src="https://github.com/user-attachments/assets/ad957c33-7034-4f5b-925a-0cb695869864" />
