### ISSUE TITLE
Stats > Rate Limited Errors total is incorrect and inconsistent

### ISSUE THREAD

**Issue by jehhynes** [getsentry/sentry#80894]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Navigate to Stats
2. Note the value in "Rate Limited Errors" appears inflated and inconsistent with the graph. 
3. Refresh by either reloading the page or switching to Category: Transactions and then back to Category: Errors
4. Note that the value in "Rate Limited Errors" has changed (and still appears incorrect/inconsistent)
5. Repeating the above steps will produce many different numbers.

![Image](https://github.com/user-attachments/assets/0bd52d0a-5635-4dab-864e-328a56b1413b)![Image](https://github.com/user-attachments/assets/d2dd74f2-2770-4b1c-97f5-545ebf0c992e)
![Image](https://github.com/user-attachments/assets/bfa09e6f-81c1-4529-a990-0e0711498552)
![Image](https://github.com/user-attachments/assets/4bca80fa-0dd8-45c8-9ce0-091f003b19a9)

### Expected Result

The number should not change when refreshed and should match the graph.

### Actual Result

The number changes when refreshed and does not match the graph.

### Product Area

Stats

### Link

https://datarg.sentry.io/stats/?dataCategory=errors&project=4506393986269184&statsPeriod=30d

### DSN

https://4e99e8d8b75bcba97873e5552769d190@o4506393976111104.ingest.us.sentry.io/4506393986269184

**Comment by brianthi** [comment]
Hi @jehhynes, this issue should be resolved now. I went through the reproduction steps and was not able to see the reported issue. Thanks for surfacing!
