### ISSUE TITLE
Automatically enable built-in repos

### ISSUE THREAD

**Issue by matejminar** [getsentry/sentry#80891]
Whenever a new Electron project gets created, we should automatically enable iOS, Microsoft, and Electron debug symbol built-in repos.

Usually, these settings can be found here: https://sentry.sentry.io/settings/projects/javascript/debug-symbols/

[Slack](https://sentry.slack.com/archives/C052LNFMLV6/p1731924960158639).

**Comment by jan-auer** [comment]
Regardless of the current epoch's default, the option `sentry:builtin_symbol_sources` should be set to `["ios", "microsoft", "electron"]`.

The actual defaults are here and include symbol servers that need not be enabled for an electron project: 
https://github.com/getsentry/sentry/blob/aaa1fa61bb217e8e9a6777228c9026c7608f8496/src/sentry/projectoptions/defaults.py#L59-L70
