### ISSUE TITLE
Sentry occasionally fails to symbolicate errors even though the required debug symbols are uploaded

### ISSUE THREAD

**Issue by jboulter11** [getsentry/sentry#80927]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

The ingestion pipeline clearly will miss occasional errors and they result in a single issue full of events with unsymbolicated traces.  While this does not happen super often considering our scale of errors being ingested, it is nonetheless very annoying.

If you look at the provided link, you can see the last event has debug info with a debug id that is listed in the list of uploaded debug info files in Sentry as uploaded 2mo ago.

### Expected Result

All traces with uploaded debug files are symbolicated, with none missing symbolication

### Actual Result

Some events do not get symbolicated and it results in reopening a ticket every time it happens on a new version.

### Product Area

Ingestion and Filtering

### Link

https://dropbox.sentry.io/issues/5425338141/

**Comment by loewenheim** [comment]
Hi, thank you for the report. In the linked issue the symbolication problem was caused by a 503 service unavailable error when trying to download a debug file from Sentry on Nov. 18. This is probably related to an outage we had that day.

**Comment by jboulter11** [comment]
That's what we figured.  These should not come through as unsymbolicated, reopening this ticket.  They should wait to be ingested until they can be.  An outage should be absolute: either ingestion works properly or it does not and those events should not be half-ingested, polluting the data.  What would it take to make that happen?

**Comment by loewenheim** [comment]
We're in the early stages of designing improvements to the pipeline, we will definitely keep this issue in mind for that.

**Comment by Dav1dde** [comment]
There is a big improvement of our ingestion and symbolication pipeline in the works, this should address these issues.
