### ISSUE TITLE
“Unable to load merged events” error when on Merge Issues tab of Issue Detail page

### ISSUE THREAD

**Issue by gywright** [getsentry/sentry#80961]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to Issue Detail Page
2. Go to Merged Issues tab

### Expected Result

Should present a list of possible issues to merge

### Actual Result

Unable to load merged events, please try again later <-- that error message is displayed in UI, inside a red box where the list of issues should be
![Image](https://github.com/user-attachments/assets/7664d9e7-1d1f-4cc0-923f-76bd71780565)

### Product Area

Issues

**Comment by snigdhas** [comment]
Thanks for filing the ticket @gywright - this will be worked on during the current core product rotation!

**Comment by snigdhas** [comment]
@gywright can we follow up with the customer later today (once this change is released to prod) and see if this fixes their issue?
