### ISSUE TITLE
alert rule not triggered but preview does

### ISSUE THREAD

**Issue by StandardStudent** [getsentry/sentry#80980]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

1. check alert rule preview
![Image](https://github.com/user-attachments/assets/348be72b-2e35-4f2e-9d0a-c417b13dd424)
2. check alert triggered
![Image](https://github.com/user-attachments/assets/152c0fe3-9b52-47da-b4c7-19394f500a57)

### Expected Result

1. alert triggered as preview

### Actual Result

1. alert not triggered

### Product Area

Alerts

### Version

24.7.1

**Comment by ceorourke** [comment]
The preview shows what issues would trigger the alert in the future based on the conditions and filters chosen. Have you had a new issue come into the project the alert is for that didn't trigger the alert?
