### ISSUE TITLE
Issues from projects I did not select are listed

### ISSUE THREAD

**Issue by mutant277** [getsentry/sentry#81027]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Select a specific project from the issue screen
2. Click real time update on the top right of the screen.

### Expected Result

Only issues related to the selected project should be shown.

### Actual Result

![Image](https://github.com/user-attachments/assets/4399d16b-db46-4c24-841e-175287a1a472)

### Product Area

Unknown

**Comment by snigdhas** [comment]
Hi @mutant277 - I was able to repro this if I had both projects open with real time updates in different tabs. Can you confirm if that's the case for you or if you're seeing this with just a single Sentry tab for the selected project?

**Comment by MichaelSun48** [comment]
Closing this ticket since #75876 appears to be a duplicate
