### ISSUE TITLE
Sentry 8.22 email config not work

### ISSUE THREAD

**Issue by moxun33** [getsentry/sentry#8109]
Here is my email config in ``config.yml``

```js
 mail.backend: 'smtp'  # Use dummy if you want to disable email entirely
 mail.host: 'smtp.sina.com'
 mail.port: 25
 mail.username: 'my username'
 mail.password: 'my password'
 mail.use-tls: false
# The email address to send on behalf of
 mail.from: 'myname@sina.com'

```

but on web page still show the default setting

![](https://ws4.sinaimg.cn/large/006tKfTcgy1fqi6xzcuhtj30hv0gjt8s.jpg)

what do I miss? Thank you!

**Comment by matt-block** [comment]
@moxun33 This might come very late but I had the same issue.

It seems that the running instance of Sentry does not pick up the email changes in `config.yml` until you restart it.

Once I restarted my host machine, Sentry picked up the changes and all works as expected.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
