### ISSUE TITLE
Issue Filter Throws When Filtering by Multiple Revisions

### ISSUE THREAD

**Issue by sb-chericks** [getsentry/sentry#81210]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to the main issues page for your domain: [https://my_domain.sentry.io/issues](https://my_domain.sentry.io/issues)
2. in the issue filter, create a filter for `release.version` (not simply `release`, that one appears to work correctly).
3. click on the revision filter tag to open the mofication popover, and select a second revision
4. execute the issue search

### Expected Result

The results are returned that match the specified release versions.

### Actual Result

the results table responds with the message: `Invalid operation 'IN' for semantic version filter.`

![Image](https://github.com/user-attachments/assets/264fe0be-d89e-4157-9e54-cc092c745373)

### Product Area

Unknown

**Comment by roggenkemper** [comment]
Thanks for posting, we have an open GitHub Issue (https://github.com/getsentry/sentry/issues/79428) that is tracking this bug and a PR up to fix it. I'll close this issue so we don't have a duplicate, so please reference the other issue for any updates
