### ISSUE TITLE
Linear integration - assignee not changing when assigning on sentry

### ISSUE THREAD

**Issue by yogevyuval** [getsentry/sentry#81224]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Sentry issue is linked to a Linear ticket with a working integration
2. When changing the assignee on linear, the asignee on sentry changes successfully.
3. When changing the assignee on sentry, the linear ticket is not updated, the previous asignee is still the selected one.

### Expected Result

The assignee on linear should change when changing it on sentry (based on the same email)

### Actual Result

The assignee on linear does not change

### Product Area

Settings - Integrations

**Comment by sentaur-athena** [comment]
Can you please provide link to the issue? Feel free to file a support ticket if you don't want the information to be available publicly.

**Comment by yogevyuval** [comment]
> Can you please provide link to the issue? Feel free to file a support ticket if you don't want the information to be available publicly.

@sentaur-athena It's not a specific issue, and issues are getting opened / close all the time so can't really share one specific issue, opening a support ticket as well.

**Comment by sentaur-athena** [comment]
Got it. Have you tried reporting this to Linear? We provide a webhook for issue:assigned that calls Linear APIs on every issue assigned. It seems to me that the issue might be an internal error on Linear side.
