### ISSUE TITLE
Upload a New File API endpoint does not work in EU orgs

### ISSUE THREAD

**Issue by InterstellarStella** [getsentry/sentry#81232]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Follow [these docs](https://docs.sentry.io/api/projects/upload-a-new-file/) to upload a .zip file to a Sentry org in the EU data center.

### Expected Result

The file is uploaded.

### Actual Result

We get the error:
```
{"detail":"The requested resource does not exist"}% 
```
Using the same command but for a US org works normally.

### Product Area

APIs

**Comment by sentaur-athena** [comment]
This API is owned by the ingest team. Re-routing

**Comment by InterstellarStella** [comment]
@jjbayer I do get a list when I use this link in my US org, but I'll have to work on getting some debug files uploaded to my EU org too.

**Comment by jjbayer** [comment]
>  I do get a list when I use this link in my US org, but I'll have to work on getting some debug files uploaded to my EU org too.

@InterstellarStella You can also just verify that you get an empty list in your EU org, that's what I did.

**Comment by InterstellarStella** [comment]
@jjbayer Yes, I do get an empty list.

**Comment by jjbayer** [comment]
I can confirm that for a US org, I get a different result than for a EU org:

```shell
# US returns a 500, that's an unrelated bug in the endpoint because I'm not uploading a valid ZIP:
$ curl  https://{MY_US_ORG}.sentry.io/api/0/projects/{MY_US_ORG}/python/files/dsyms/ -H 'Authorization: Bearer {MY_US_TOKEN}' -F file=/tmp/test-file
{"detail":"Internal Error","errorId":"f1b9e82ca740491b93473a850c00833f"}%

# EU returns a 401
$ curl  https://{MY_EU_ORG}.sentry.io/api/0/projects/{MY_EU_ORG}/python/files/dsyms/ -H 'Authorization: Bearer {MY_EU_TOKEN}' -F file=/tmp/test-file
{"detail":"Invalid org token"}%
```

The exception seems to be coming from https://github.com/getsentry/sentry/blob/ad2b920ec9e704bd1ea1905a1a43644a1569198f/src/sentry/api/authentication.py#L483. @corps any idea what could be wrong here?

**Comment by jjbayer** [comment]
@InterstellarStella due to the particularities of our regional setup, requests to the `/dsyms/` endpoint must go to `https://{region}.sentry.io` instead of `https://{org}.sentry.io`. @markstory is working on improving the docs around this.

I can confirm that I can successfully upload zip archives to my EU test org if I replace `{MY_EU_ORG}` with `de`:

```shell
curl  https://de.sentry.io/api/0/projects/{MY_EU_ORG}/python/files/dsyms/ \
-H 'Authorization: Bearer {MY_EU_TOKEN}' \
-F file=@crash.dsym.zip
```

As input I zipped the file we use in tests: https://github.com/getsentry/sentry/blob/master/tests/sentry/models/fixtures/crash.dsym

Feel free to reopen if you encounter more issues.
