### ISSUE TITLE
Advanced Data Scrubbing Rules Not Working

### ISSUE THREAD

**Issue by zsperske** [getsentry/sentry#81253]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

We have set up a data-scrubbing rule with the following regex `[A-Z0-9-]{9,16}` in order to replace UUIDS in error messages, a particular tag and error.value but it isn't working.

There might be some relationship with the fact that the issue we are trying to scrub is fired from the [SentryOkHttpInterceptor](https://github.com/getsentry/sentry-java/blob/main/sentry-okhttp/src/main/java/io/sentry/okhttp/SentryOkHttpInterceptor.kt) which seems to use a different method than usual for reporting events to Sentry.

We also tried Sentry's built in UUID scrubbing rule and several variations of our regex.

### Expected Result

We should see UUIDS replaced with a string of our choosing.

### Actual Result

Can share privately.

### Product Area

Ingestion and Filtering

**Comment by jjbayer** [comment]
@zsperske unfortunately the `url` tag is populated from the `request.url` field after PII scrubbing: https://github.com/getsentry/sentry/blob/a6126669cd93cf72f041942a4e4eca3e8dd80326/src/sentry/plugins/sentry_urls/models.py#L6-L9

Apply the rule to `$request.url` should work.

**Comment by yuval-sentry** [comment]
The suggested solution by @zsperske is working.
Thank you!!

**Comment by zsperske** [comment]
+1, thank you!
