### ISSUE TITLE
Web Vitals UX improvements for new users

### ISSUE THREAD

**Issue by bcoe** [getsentry/sentry#81303]
### Problem Statement

Until you've read the documentation it can be difficult to know the meaning of LCP, FCP, CLS, etc., see user feedback:

> You don't have tooltips for any of your acronyms. I'm a new user. What is LCP, FCP, INP, etc??? Please add tooltips so I know what these things mean!

## Improvements to Insights

**1. hover tips**

When you hover over the vitals cards or the table headings, it would be good to show the meaning of the acronym:

![Image](https://github.com/user-attachments/assets/0a6a3f09-8fd1-488b-a238-e9e430c6281d)

![Image](https://github.com/user-attachments/assets/970492ab-3761-41c1-b1de-cc6e2b1064b0)

**2. link to tutorials**

We are starting to write tutorials for each web vitals, we should link to these either from the hover pop-up or the summary you see when clicking through.

## Improvements to Trace View

**1. hover tips and click for details on trace view*

The trend lines on Trace View don't provide a hover tip or allow you to click for details, we should support one or both:

![Image](https://github.com/user-attachments/assets/086f0553-8f1e-40a3-9d23-96164ff371a9)

### Product Area

Insights

**Comment by 0Calories** [comment]
Everything in here will be resolved once https://github.com/getsentry/sentry/pull/81997 is merged and deployed!

As for the trace view, in the new design that will be shipped later, we will include the web vitals in the bottom context drawer. The same short tooltips will be displayed when you hover over these: ![Image](https://github.com/user-attachments/assets/3b899326-844f-4ca5-8b95-439ae50a39aa)
