### ISSUE TITLE
sentry not playing nice with react-native-git-upgrade?

### ISSUE THREAD

**Issue by uriva** [getsentry/sentry#8130]
I'm not 100% sure this is Sentry's fault, but when I run `react-native-git-upgrade` it hangs right after sentry prints this:

> 
> Running Sentry Wizard...
> version: 0.9.5 | sentry-cli version: 1.30.4
> Sentry Wizard will you help to configure your project
> Thank you for using Sentry :)
> 
> 
> Please open
> https://sentry.io/account/settings/wizard/MY_ID/
> in your browser (if it's not open already)
> 
> 
> Successfully set up android for react-native
> Successfully set up ios for react-native
> 

At the past there were some problems with sentry and this command due to sentry running the wizard without user being aware input is needed (nor could they give that input), but in latest version this was fixed.

This however might be a new issue.

**Comment by HazAT** [comment]
I will check why it's stuck there.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
