### ISSUE TITLE
User management - Prevent users with role Members from freely creating teams so they can still create projects

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#81310]
### Problem Statement

As discussed in https://github.com/getsentry/sentry/issues/80978 users are able to freely create teams and also create projects in that regards.
In order to prevent that, there should be an option to prevent users with member roles to create new teams as it should go through SCIM or Org Admins/Owners/Managers, higher role than regular Members. 

### Product Area

Settings - Members

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2364) by [Unito](https://www.unito.io)

**Comment by sentaur-athena** [comment]
You can disable project creation for members in org settings and that way members cannot create teams.

**Comment by sentaur-athena** [comment]
As discussed in https://github.com/getsentry/sentry/issues/80978 they cannot freely create teams. They only can create 1 team and that's if they try to create a project. So disabling project creation setting will stop them from creating any teams.

**Comment by Angelodaniel** [comment]
@sentaur-athena - I think the nuance here is that it would disable also for the Team Admins of the teams. Which is not the goal.
Org admins (deprecated) are now Team Admins. When they disable the members can create projects it also disables project creation for Team Admins. 
Apologies for the namings here
The next in line who can create projects are managers but that seems to be too high of a role

**Comment by sentaur-athena** [comment]
No that would not disable it for team admins. It would only disabled for team contributor org members.

**Comment by Angelodaniel** [comment]
@sentaur-athena ok then there is a bug in the Team admin role: https://github.com/getsentry/sentry/issues/82127
