### ISSUE TITLE
When copying DSNs out of textboxes, they paste wrapped with newlines

### ISSUE THREAD

**Issue by gricey432** [getsentry/sentry#8131]
In the project settings page (where there is also a copy button) and on the getting started page (where there isn't); if you copy out a DSN by highlighting and hitting ctrl c and paste it into a text editor, it comes out wrapped in newlines
```

<DSN>

```
Pretty minor but annoying when I'm setting up dozens of them. It doesn't occur when using the "copy" button on the settings page.

Sentry SAAS. Chrome 65 on linux pasting into Slack, Mousepad, and Pycharm.

**Comment by stayallive** [comment]
I have the same issue, almost every copyable field does this (api auth key & dsn private key fields also does this).
