### ISSUE TITLE
Notifications in Slack

### ISSUE THREAD

**Issue by bruun** [getsentry/sentry#8134]
We find the Release and Deploy tracking to be a very useful feature, and recently started receiving email alerts about deploys. It would be fantastic if we could have a Slack integration for release tracking as well.

**Comment by BYK** [comment]
This is now in!

**Comment by bruun** [comment]
Hi @BYK, very glad to hear this has been implemented. I can't seem to find any mention of Slack notiifications in the documentation for Releases, nor in any other documentation. I also tried looking through the settings in both our organization and projects. Is this not yet released for everyone, or am I looking in the wrong place?

**Comment by BYK** [comment]
Hi @bruun, sorry for the very late response, the notification email got buried in my inbox. I think I didn't fully understand what you mean by release tracking in Slack when I first closed the issue. We do have deploy notifications as you mentioned and then we have a release health tracking feature where you can create metric alerts from: https://docs.sentry.io/product/alerts-notifications/metric-alerts/

These alerts will notify you in Slack too. Is this close to what you are after?

**Comment by bruun** [comment]
Hi @BYK, no worries. In the feature request I was refering to deploy notifications, which were limited to an email. It's my understanding from the documentation that this is still the case?

**Comment by BYK** [comment]
Ah, right. You are correct, checking our docs and recalling from my experience, turns out our "notifications" are limited to e-mails. I'll reopen this and ping the team to see if we can have more integration between the notification system and the more flexible alerts system as it should allow all integrations to get these notifications.

**Comment by robsonsobral** [comment]
Hi!

We're using GoogleChat and to have all members of the team notified about new releases would be sooooo useful!

(Maybe this issue needs to be renamed)

**Comment by aurbano** [comment]
@BYK any updates on this?

**Comment by BYK** [comment]
@aurbano I'm no longer working at Sentry that said I'm almost certain that I've used Slack notifications for deploy recently. Have you checked your settings?

Maybe @chadwhitacre can provide a definitive answer and then close this issue if it's already resolved.

**Comment by brianthi** [comment]
Hello! We do support Slack and MSTeams notifications for deploys and releases. You can find the per user based settings here: https://<orgSlug>.sentry.io/settings/account/notifications/deploy/. Docs related to this notifications settings page is [here](https://docs.sentry.io/product/alerts/notifications/notification-settings/). 

To @robsonsobral , we don't support Gchat at the moment. If that is still something you're looking for, please open a new feature request ticket.
