### ISSUE TITLE
Track Sentry Issue Merges in Activity Tab

### ISSUE THREAD

**Issue by gid-sentry** [getsentry/sentry#81352]
### Problem Statement

Sometimes Sentry will merge issues or at least mark issues as merged in the Merged Issues tab, without user interaction. In those cases, it can be hard to find out why the issues were merged and there's no entry in the activity tab about how the fingerprints ended up being merged.

### Solution Brainstorm

If there is a heuristic for Sentry to auto-merge issues, make sure it is tracked in the activity tab to be able to track and understand what happened.

### Product Area

Issues

**Comment by gid-sentry** [comment]
Customer Case https://www.notion.so/sentry/Issues-were-merged-unclear-why-how-they-were-merged-1378b10e4b5d801ab863d7d50101834a?d=1428b10e4b5d805f8881001cfc85b8d6

**Comment by Dhrumil-Sentry** [comment]
Thanks a lot for sharing this feedback, the team has added this to our backlog

**Comment by armenzg** [comment]
After my analysis on Slack, I found that this is not applicable.

I will follow up in #proj-grouping on how to prevent this from happening.

**Comment by armenzg** [comment]
For the customer, I added this rule: `error.type:NSGenericException -> {{ default }}, {{ message }}` which was exactly what they needed.

To help all customers from getting into the same state we need to fix these two issues:
* https://github.com/getsentry/sentry/issues/72294
* https://github.com/getsentry/sentry/issues/82079
