### ISSUE TITLE
Get 500 Internal Server error when adding GitHub Integration

### ISSUE THREAD

**Issue by justinyu-vyond** [getsentry/sentry#81357]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I am trying to add GitHub integrations from the Sentry page. I used the `Add Installation` button in sentry page  to set up the integration.

I followed the instructions and selected the repositories that I want to add to the Sentry integration. Then I clicked the `Install` button and tried to continue.

But it returns a 500 Internal Error Page when requesting https://sentry.io/extensions/github/setup/?installation_id=57668763&setup_action=install

### Expected Result

Expected to continue the setup

### Actual Result

![Image](https://github.com/user-attachments/assets/65588aba-d528-4410-88ce-61f91dcaa465)

![Image](https://github.com/user-attachments/assets/2226a04b-01d9-4973-a3b0-f8da6f3de34f)

### Product Area

Settings - Integrations

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2375) by [Unito](https://www.unito.io)

**Comment by sentaur-athena** [comment]
The next step in the installation here is to show you all the organizations you're member of and ask you to see which one you want to install. My guess is something failed there. Can you please share your user id or email to look? Note that this is a public issue so if you need to send it in private please file a support ticket and link this issue in it.

**Comment by justinyu-vyond** [comment]
I'm afraid that is not the case. I thought I had already passed that selection. As you can see in the first picture I uploaded.
I am able to select my organizations and repos that I want to include, as well as the repos I want to install.

**Comment by sentaur-athena** [comment]
@justinyu-vyond I'm talking about your sentry organization and not your github organization.

**Comment by rodolfoBee** [comment]
@sentaur-athena the user reached via Zendesk, I added the information on the affected organisation to the Shadow Jira ticket. You and your team can find the information there.

**Comment by sentaur-athena** [comment]
Responded on the internal ticket. @rodolfoBee please feel free to close the ticket if it resolves the issue.
