### ISSUE TITLE
Feature suggestion: display or remove JS console.log formatting in breadcrumbs

### ISSUE THREAD

**Issue by jrencz** [getsentry/sentry#8139]
In JS console in browsers there's output formatting feature

https://developer.mozilla.org/en-US/docs/Web/API/Console#Styling_console_output

If one uses `autoBreadcrumbs.console: true` (which is default for raven-js) then console calls are capturing breadcrumbs.
Sentry does not take formatting into consideration which makes breadcrumbs less readable than they could be.

E.g.
In one of the modules of my app I have colored "tags" at the beginning of the message:

```js
const debug = (...messages) => console.debug('%c[My Tag Name]', 'color:red;font-weight:bold', ...messages);
```

Which makes console output a bit more eye-pleasing but in Sentry issue I see the `%c` and css used for formatting.

I wonder if it could be either processed out (presumably: on the server side not prevent making raven-js even bigger than it is now) or just applied as inline style so instead of this:

<img width="761" alt="screen shot 2018-04-23 at 09 40 55" src="https://user-images.githubusercontent.com/948356/39113036-9eaff920-46da-11e8-9c14-1bb172ad4a46.png">

one would see this:

<img width="759" alt="screen shot 2018-04-23 at 09 41 41" src="https://user-images.githubusercontent.com/948356/39113029-9adde41a-46da-11e8-9bf1-4033358fa2d6.png">

I see that the breadcrumb from console call is sent in concatenated way: 

https://github.com/getsentry/raven-js/blob/26fcb595ca46b6323717349087a9415c813b0ac8/src/console.js#L16

```js
var msg = utils.safeJoin(args, ' ');
```

but if some non-space delimiter was used then sentry could figure out that if the first part of the message starts with `%c` then use the 2nd argument as value for `style` attribute wrapping the first one (more or less like the browsers console does)

**Comment by MaxBittker** [comment]
Oh hey, cool! I've actually implemented rendering these strings as html before: 
https://github.com/MaxBittker/regl-shader-error-overlay/blob/master/overlay.js#L61

there's probably a more idiomatic way, but my point is that this isn't super hard.

How common is this? not sure what timeframe on which this is worth prioritizing. I'm glad you opened the issue though, this could be bothering a larger set of people than I assumed.

I think that it would be safer to strip these styles out than to actually apply them.

**Comment by aguynamedben** [comment]
+1, these are super annoying and I have to implement a bunch of hacks using `beforeBreadcrumb` to remove/modify them. Mine come from [redux-logger](https://github.com/LogRocket/redux-logger). I want to log redux-actions, but by default they look like this:

![image](https://user-images.githubusercontent.com/107841/61414531-0e073600-a8a3-11e9-9558-e4e15f7b24b4.png)

The state changed logged by redux-logger are even crazier... the `extra` field in the breadcrumbs is very large. To clean this up in `beforeBreadcrumb` I have this logic...

```js
        // Keep breadcrumbs from redux-logger console logs, but clean it's
        // messages up before sending to Sentry.
        if (breadcrumb.data && breadcrumb.data.extra && breadcrumb.data.extra.arguments && breadcrumb.data.extra.arguments[2] && breadcrumb.data.extra.arguments[2].type) {
          const reduxAction = breadcrumb.data.extra.arguments[2].type;
          breadcrumb.message = reduxAction;
          breadcrumb.data = {};
        } else if (breadcrumb.message.includes('state color')) {
          // This is a trash message for solely for changing the color of the
          // console, drop it.
          return null;
        }
```

**Comment by aguynamedben** [comment]
bump

**Comment by priscilawebdev** [comment]
just added this issue to my backlog 😉

**Comment by priscilawebdev** [comment]
This task will be part of this week's sprint. Sorry for taking so long

**Comment by jrencz** [comment]
Which way you decided to go?

**Comment by priscilawebdev** [comment]
We talked about it internally and decided that we won't do anything, but read below for a more extensive conclusion.

It's too hard to decide what to drop and what not. Especially that there are multiple other console markers that can be used. 

Ex: `console.log("this value %cwill be read and will print number %i but this will be %cblue", "color: red", 1, "color:blue")`

It's impossible to tell which values to drop without parsing everything and applying some awful logic to it.

If you want to discard the formatting, we recommend using `beforeBreadcrumb` to do this, as you may know where the tags are used.

ex: 

```
init({
  beforeBreadcrumb(breadcrumb) {
    if (breadcrumb.category === 'console') {
      breadcrumb.message = someLogicToFixMessage(breadcrumb.message);
      // or
      breadcrumb.message = buildMessageFromRawArguments(breadcrumb.data.arguments);
    }
    return breadcrumb;
  }
})

```

**Comment by loilo** [comment]
For anyone interested, this is the function I built to serialize the arguments of a `console.log()` call into a simple string. This could be used in @priscilawebdev's `beforeBreadcrumb` example:

```js
function serializeConsoleLog(...args) {
  let result = []

  // Format if first argument is a string
  if (typeof args[0] === 'string') {
    let formattedMessage = args.shift().replace(/%[csdifoO]/g, (match) => {
      // Keep raw token if no substitution args left
      if (args.length === 0) return match

      switch (match) {
        // Formatting (omitted)
        case '%c':
          args.shift()
          return ''

        // String
        case '%s':
          return String(args.shift())

        // Integer
        case '%d':
        case '%i':
          return parseInt(args.shift())

        // Float
        case '%f':
          return parseFloat(args.shift())

        // Object
        case '%o':
        case '%O':
          return JSON.stringify(args.shift())
      }

      // Keep raw token if not replaced
      return match
    })

    if (formattedMessage.length > 0) {
      result.push(formattedMessage)
    }
  }

  // Format 
  let formattedArgs = args.map((arg) =>
    typeof arg === 'string' ? arg : JSON.stringify(arg)
  )
  result.push(...formattedArgs)

  return result.join(' ')
}
```
