### ISSUE TITLE
No results found in discover tab for query despite relevant transactions

### ISSUE THREAD

**Issue by NicolasGiaco** [getsentry/sentry#81418]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

- Go to Discoverand click on the `Tansactions` tab 
- Use the query `http.status_code is 404`to filter transactions.
- Execute the query within a time range where transactions with status code 404 are expected.

### Expected Result

Transactions with http.status_code equal to 401 should appear in the results, as verified by existing logs or individual transaction details.

### Actual Result

No results are returned, even though transactions with http.status_code = 404 exist (confirmed by inspecting specific transaction details in the UI).

### Product Area

Discover

### Link

https://legitbee-c9.sentry.io/discover/homepage

**Comment by NicolasGiaco** [comment]
Here are a few screenshots with my transaction and query 

![Image](https://github.com/user-attachments/assets/8e19c428-3718-4417-b003-73ab96fc1792)
![Image](https://github.com/user-attachments/assets/04451c89-e6c9-4de0-a6fe-1698c1e990e0)

**Comment by Dhrumil-Sentry** [comment]
Thank you for the bug report, the team will investigate this

**Comment by shruthilayaj** [comment]
Seems like this is happening because we're not attaching the [response context](https://develop.sentry.dev/sdk/data-model/event-payloads/contexts/#response-context) to the events. We aggregate http_status codes from `response.status_code`. I'm going to follow up with the SDK teams about this!
