### ISSUE TITLE
NullPointerException on Bitmap.isRecycled() on replay code

### ISSUE THREAD

**Issue by kukadiajayesh** [getsentry/sentry#81430]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

I have a picture capture activity where user can pick image or select from gallery. When user try to capture image in some devices got crash on this activity and on the trace, it shows ScreenshotRecorder class. I thought it might be a bug on sentry as the whole trace is out of My Application package. 

In some devices it throws error while capturing screen shot.

Here is the public link of sentry issue: https://mikashboks.sentry.io/share/issue/21b7a8dce08f40de82c27951d7c490ba/

Till now, I'm unable to find pattern or any common mistake to reproduce this issue.

### Expected Result

As a normal activity it should not crash application.

### Actual Result

Application is crash totally unpredictable.

### Product Area

Replays

**Comment by romtsn** [comment]
hey, this issue was fixed in a recent version, please update to the latest one (7.18.1 as of now)

**Comment by kukadiajayesh** [comment]
Thanks @romtsn , this helps a lots !!!
