### ISSUE TITLE
Alert Unsubscribe Link should take me to Alert Settings

### ISSUE THREAD

**Issue by thinkocapo** [getsentry/sentry#81450]
### Problem Statement

Alert Unsubscribe Link should take me to Alert Settings and not a Documentation Loop

## Problem
Really hard how to figure out how to unsubscribe and this leads to alert fatigue.

## Steps to Reproduce
1. this
![Image](https://github.com/user-attachments/assets/241b2fca-df49-45ed-bebc-67357b5cab05)

2. and this only unsubscribes for `this issue` but not all issues
![Image](https://github.com/user-attachments/assets/917ec9e5-5bc3-4e2b-ac5a-dbf760d493e1)

3. so click link ^ for [workflow notifications](https://docs.sentry.io/product/alerts/notifications/#workflow-notifications)
4. Still not clear how this Alert was configured and why it's emailing me. Not clear where I need to go fix it in Sentry UI. Would rather not read this entire page. Why not link the user directly to their [UserSettings.NotificationSettings](https://demo.sentry.io/settings/account/notifications/) by now? or [UserSettings.NotificationSettings.IssueWorkflowSettings](https://demo.sentry.io/settings/account/notifications/workflow/)
![Image](https://github.com/user-attachments/assets/930b584a-711f-47f8-98fe-7d16017ba998)

5. I check my [Alerts for the React Project](https://demo.sentry.io/alerts/rules/?project=5808623&statsPeriod=14d) and none were triggered in 48hrs, so it must not be one of those alerts.
6. I find UserSettings.NotificationSettings.IssueWorkflowSettings to disable it. Because I noticed in docs `You can manage these notifications in User Settings > Notifications.` but still the pop-up in step#3 should offer a link to UserSettings directly.

### Solution Brainstorm

Step 3 should also include a link for going to settings that would fix this. This screenshot needs a link to user settings or else the end user gets thrown into the documentation ocean:
![Image](https://github.com/user-attachments/assets/dcf7bbf7-ee52-42c4-9619-c212bde26b25)

### Product Area

Alerts

**Comment by ceorourke** [comment]
Clicking "Notification Settings" at the bottom of the email brings you to https://sentry.io/settings/account/notifications/ as suggested in step 4

![Image](https://github.com/user-attachments/assets/e1b46362-e8a4-4cd1-b0ed-7a9954fc5945)
