### ISSUE TITLE
Stats -> Issues tab - Inconsistency with the graphs on specific team with no issues assigned

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#81483]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Seems to be specific to Customers org/ team structure
They have a team that is triaging issues with the end goal to not have any issues assigned to it which reflects in the issues stream.
1. Go to Stats - Issues dashboard
2. Select Team provided in Jira ticket
3. See number of unresolved issues
4. Open up issues stream
5. Select same team
6. No results on issues

Another issue is that I have 2 screenshots where the number of issues is first 500 and the next one is 400 but these screenshots are 1 day apart and there is no decrease seen in the history of the graph.

### Expected Result

Issue counts to reflect the actual state of Team X
Graph to be consistent

### Actual Result

1st problem: 
![Image](https://github.com/user-attachments/assets/0fe33f48-9edd-4b07-b2ea-b9d9cae41f28)
![Image](https://github.com/user-attachments/assets/5031bab8-2805-4de4-bc2a-f8a4390847f8)

2nd problem:
![Image](https://github.com/user-attachments/assets/9a4dc891-7c38-4e01-806f-18ad7a9cd5a4)
![Image](https://github.com/user-attachments/assets/332fbcb0-9328-4fbe-9383-608dd336d597)

### Product Area

Issues

### Link

Links in Jira issue

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2370) by [Unito](https://www.unito.io)

**Comment by scttcper** [comment]
New and returning issues are counting the total number of times an issue was assigned to your team and was new/regressed/etc over the currently selected time period. If the issue has been reassigned since then it would not appear in the issues stream.

Unresolved issues include the members of the team in the count, not just the team.

**Comment by Angelodaniel** [comment]
Aah so the initial linking adds a +1 to the total count @scttcper.

> Unresolved issues include the members of the team in the count, not just the team.
So that would mean if I'm in Team A and Team B and Team A has 5 issues but Team B 0, I'd still get 5 issues shown? 
That all makes sense.

The last thing about this is that the Data dropped magically from 500 to 400 and there is no change over the periods which is confusing ![Image](https://github.com/user-attachments/assets/7e4d8018-f300-4d7b-8dbb-359ef8429128)

**Comment by scttcper** [comment]
@Angelodaniel could the team have been removed from a project? I'm not sure

**Comment by scttcper** [comment]
Going to close this out unless we have something new to investigate. Feel free to reopen.
