### ISSUE TITLE
Large .webpack_cache size in docker

### ISSUE THREAD

**Issue by madest92** [getsentry/sentry#81487]
Maybe it's worth clearing?

```
root@sentry# docker run --rm getsentry/sentry:24.8.0 du -sh .webpack_cache
2.2G    .webpack_cache
```

Or are there reasons why the cache is needed after the build?

**Comment by aldy505** [comment]
Can confirmed, it's fixed on nightly. Thanks @BYK!

![Image](https://github.com/user-attachments/assets/e5a77a7e-93e7-4a5f-a834-21defcdce69d)
