### ISSUE TITLE
Additional Data fields sent via setExtra is displaying as an array with a value of the key name in the Transaction Trace View screen

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#81586]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Reported by a user using the dotnet sdk, and I reproduced using the node sdk.

1. Add some data to scope via an sdk's setExtra()
2. Send a transaction
3. Open up the transaction event in the Trace View, and see that the Additional Data section shows the values as arrarys.

Link to a[ transaction](https://francisorg.sentry.io/performance/trace/dfbca595af3be0a8efed233e7f7ca67f/?dataset=transactions&field=title&field=project&field=user.display&field=timestamp&name=All%20Errors&node=txn-08645c48d04a466b8a4faf41039639a1&project=-1&query=&queryDataset=transaction-like&sort=-timestamp&source=discover&statsPeriod=14d&timestamp=1733243283&yAxis=count%28%29) with an [error](https://francisorg.sentry.io/issues/6076144292/?project=4504039154974720&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=1), both with the same scope data.

broken Transaction event-

<img src="https://github.com/user-attachments/assets/eb23cf75-2acf-4636-8132-b109ae8ece29" width="300" />

transaction raw -

<img src="https://github.com/user-attachments/assets/67bc43ea-d993-48be-a59c-49a59ad0c1cb" width="300" />

Working properly Error event - 

<img src="https://github.com/user-attachments/assets/555c2fae-a678-4755-b88b-2fe65a87a9cf" width="300" />

error event raw -

<img src="https://github.com/user-attachments/assets/e4a2f488-00f6-4f9a-99d4-6cb39d94b466" width="300" />

### Expected Result

The transaction should display the same as the error event.

### Actual Result

The transaction displays an array of the just the key name.

### Product Area

Performance

**Comment by k-fish** [comment]
Closing in favour of https://github.com/getsentry/sentry/issues/81417 since these appear to be the same issue
