### ISSUE TITLE
Metrics alerts not firing even with threshold breach

### ISSUE THREAD

**Issue by saagar-cognite** [getsentry/sentry#81724]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Hello team.

We're experiencing issues with metrics alerts not firing since 18th Nov 2024.
There was no modifications to the rules but they suddenly stopped.
We can't see them either in sentry UI nor we are getting them in slack anymore.
We still see the high priority alerts which are getting triggered for the error event showing up in mail.

We were redirected to post this here from [discord message](https://discord.com/channels/621778831602221064/1314022687978291251/1314062948913647716)

### Expected Result

Metrics alerts should fire like they were given in [history](https://cognite-eu.sentry.io/alerts/?environment=production&project=4508143373320272&statsPeriod=10m).
[Link to last triggered alert](https://cognite-eu.sentry.io/alerts/rules/details/4578/?alert=649).

We would like to be like this last triggered alert.
![Image](https://github.com/user-attachments/assets/26b8bde6-a225-46a1-91ca-a873a32be311)

### Actual Result

![Image](https://github.com/user-attachments/assets/0462d8b5-1fac-4083-bf6a-ce17329ddedf)

### Product Area

Alerts

### Link

https://cognite-eu.sentry.io/alerts/rules/details/4578/?environment=production

### DSN

https://a502cc0e8e16f5316044b5c34c045d30@o4508040730968064.ingest.de.sentry.io/4508143373320272

**Comment by ceorourke** [comment]
Hello, we're currently looking into this but don't have much to share at the moment - I'll update when we do.

**Comment by ceorourke** [comment]
We've identified the problem and have issued a fix - I'm going to close this but feel free to reopen if you continue to have problems.

**Comment by saagar-cognite** [comment]
Thank you so much @ceorourke !
We can confirm that the issue seems to be fixed. 👍

**Comment by ngerstle-cognite** [comment]
Can you provide any background on what the problem was/what triggered it in our setup @ceorourke ?
