### ISSUE TITLE
Linear integration - Multiple labels

### ISSUE THREAD

**Issue by brdtheo** [getsentry/sentry#81737]
### Problem Statement

When Sentry automatically creates a new Linear issue, providing only 1 label feels a bit limited

The end purpose is (but not limited to) being able to dispatch more efficiently Linear issue to the different teams

That is why selecting more than 1 label for Sentry alerts + Linear would be awesome

![Image](https://github.com/user-attachments/assets/e0efad46-8677-4de8-a496-e2e6b58a5f5f)

### Solution Brainstorm

In the alert rule edit page `alerts/rules/:project/:id/` make the field "Label" a multiple choice field instead of a single one. That way, linear API can receive properly the several IDs we selected from front end.

The Sentry API would need to transform the `labelId` field from a simple `string` into an array of `string` that matches the logic of "one or more"

The `POST` request made to `/api/0/projects/:org/:project/rules/:id/` would need an updated payload such as

```json
{
    "actions": [
        {
            "settings": [
                {
                    "name": "labelId",
                    "value": ["602f4101-48c1-42bb-916c-00c6eeaaec2a", "9f777662-846f-42fe-b011-f3fc744647ac"]
                },
            ],
        }
    ]
}
```

## Linear API example

```graphql
mutation IssueCreate($issueCreateInput: IssueCreateInput!) { issueCreate(input: $issueCreateInput) { lastSyncId } }
```

```js
{
  "issueCreateInput": {
    "title": "Issue from Sentry",
    "teamId": "2ceb065c-f91a-4b92-a40b-8225ee594c07",
    "priority": 0,
    "subscriberIds": [],
    "stateId": "337402a2-fce0-4af4-be26-6909db6fb675",
    "sortOrder": -6194.35,
    "prioritySortOrder": -6194.35,
    /** provide 1+ label(s) for Linear issue. those labels needs to exist in Linear project  */
    "labelIds": [
      "602f4101-48c1-42bb-916c-00c6eeaaec2a",
      "9f777662-846f-42fe-b011-f3fc744647ac"
    ],
    "preserveSortOrderOnCreate": false
  }
}
```

### Product Area

Alerts

**Comment by sentaur-athena** [comment]
@brdtheo can you please confirm this if the issue is created by a customer or the integrator? (Linear)

**Comment by sentaur-athena** [comment]
My question was if this is ask by Linear or Linear customer. Just because the way we triage those tickets are different.

But never mind, just figured this is already in our backlog. Please track here: https://github.com/getsentry/sentry/issues/66255
