### ISSUE TITLE
Dashboards - Make it possible to add a binominal distribution for custom metrics

### ISSUE THREAD

**Issue by michellangeveld** [getsentry/sentry#81794]
### Problem Statement

For web vitals there exist the following graph as representation:
![Image](https://github.com/user-attachments/assets/0e232536-f19b-46ff-91a8-f4876d666015)

Would be awesome if custom metrics can be represented in the same way.
Now custom metrics can be plotted in a dashboard.
But not in this type of a graph.
This graphs give good insight and is use full to trouble shoot performance issues or configure correct values for timeouts in the application.

### Product Area

Unknown

┆Issue is synchronized with this [Jira Improvement](https://getsentry.atlassian.net/browse/FEEDBACK-2376) by [Unito](https://www.unito.io)

**Comment by ale-cota** [comment]
Hi there,
Thanks for adding the feature request. We already have another issue tracking this (https://github.com/getsentry/sentry/issues/80524), so I will close this one to avoid duplication. Could you please follow the other issue instead?
It's currently on our backlog and requires non-trivial effort, but we're hoping to tackle this at some point next year.
Thanks again.
