### ISSUE TITLE
Metric Alerts are not triggering for EU orgs

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#81818]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Create a Metric Alert in an EU org
2. Attempt to trigger it.
3. See that the alert stays at the green Resolved state even though it passes the configured thresholds.

I created 2 EU metric alerts[ here](https://francisorgeu.sentry.io/alerts/rules/details/5467/?period=6h) and [here](https://francisorgeu.sentry.io/alerts/rules/details/5468/?period=6h).

I crossed their threshold in multiple occasions but the alerts do not trigger.

I created 2 US metric alerts with the same rules [here](https://francisorg.sentry.io/alerts/rules/details/301039/), and [here](https://francisorg.sentry.io/alerts/rules/details/301040/).

They trigger when the threshold is crossed and the status changes.

### Expected Result

Metric alerts to move from Resolved to another Status

### Actual Result

EU metric alerts do not change status -

<img src="https://github.com/user-attachments/assets/823056f9-999a-4b18-8859-e4fe662e07f9" width="800" />

### Product Area

Alerts

**Comment by ceorourke** [comment]
This issue should be resolved now, I'm going to close this but feel free to reopen if the issue persists.
