### ISSUE TITLE
Postgres port is inconsistent in init procedures

### ISSUE THREAD

**Issue by ermik** [getsentry/sentry#8181]
## Bug

- The version of Sentry you're using
8.22
- Whether you're using Docker or another installation method
Kubernetes
- Include a stacktrace or other logs when relevant
sentry-createuser-job | Apr 24, 2018, 11:58:54 PM | Is the server running on host "init-cloudsql.sentry.svc.cluster.local" (10.11.249.154) and accepting TCP/IP connections on port 3306?

- Include a redacted version of your configuration when relevant
The configuration, which is done as a combination of k8s Secret and ConfigMap resources, includes the env value for Postgres Port — 3306. This config was a byproduct of existing postgresql instance.

I previously had a problem connecting to the instance — the migrations script was connecting to port 5432 ignoring the setting. I didn't realize that and instead changed by postgres instance to serve on the default 5432 port. And now, the createuser command, that apparently uses the environment variable correctly, is failing.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by ermik** [comment]
Haven't used Sentry OSS distribution recently. Whenever I do again I'll report any issues that may arise.

**Comment by BYK** [comment]
>Whenever I do again I'll report any issues that may arise.

I recommend posting any issues related to self-hosted versions to [getsentry/onpremise](https://github.com/getsentry/onpremise) as it is more closely monitored for these issues.
