### ISSUE TITLE
Crash Report is not getting update for iOS App

### ISSUE THREAD

**Issue by abhaysingh007** [getsentry/sentry#8184]
Hi Guys,

I have created an iOS project (**Objective - C**) and integrated with Sentry for crashanalytics.

The crash reports are not getting uploaded to Sentry console immediately even though in the  log I'm able to see **1 crash report sent** .

All crash reports are getting uploaded only after the app is  launched successfully without any crash in the further attempts.

However, the crash reports are getting uploaded immediately to Sentry console incase of Android application.
Is there any thing that have to be done in the iOS Objective C app side to get our crash logs uploaded immediately?.

Thanks All.

**Comment by HazAT** [comment]
I suppose you are using `sentry-cocoa` right?
So not sure what the problem is, in case of a crash on the next app start we are sending the last crash to Sentry.
We do this because there might be not enough time to send it during the crash.

Does this answer your question?

**Comment by abhaysingh007** [comment]
Thank you HazAT, You'er right app was not getting enough time to send the crash report.
