### ISSUE TITLE
Minidump stack walking does not use CFI data from debug symbols

### ISSUE THREAD

**Issue by cpfair** [getsentry/sentry#8193]
Minidumps are parsed at upload time, including extraction of the stack traces - however, this stack walking [does not use any CFI records](https://github.com/getsentry/sentry/blob/a1604c64c434095c701305e2391d1f9e39b0f8c7/src/sentry/web/api.py#L572) that may be present in the modules' previously uploaded symbol files. This causes problems on platforms like x86, where breakpad's naive stack-walking routine tries its best but ultimately falls short, producing inaccurate stack traces.

This appears to be a known issue, with a suggestion that [minidumps could be reprocessed later, once CFI data was available](https://github.com/getsentry/sentry/blob/a2268bcdb8471e9af412a12851047c69f2c47cd2/src/sentry/lang/native/utils.py#L197). But, this isn't currently feasible given that the minidump is thrown away as soon as possible. It seems like the next best option would be to opportunistically check for any uploaded symbols w/ CFI at minidump upload time, using them if present, but otherwise continuing without.

**Comment by asgoel** [comment]
@jan-auer any update on this?

**Comment by jan-auer** [comment]
@asgoel We’ve recently started working on using CFI and expect to deliver this feature soon. I will update this GH issue once it is available.

**Comment by rrueth** [comment]
@jan-auer now that all of the changes for this issue have been merged, when should we expect the changes to be deployed to sentry.io?

**Comment by jan-auer** [comment]
They are deploying at the moment. We will be updating documentation around CFI in the upcoming days.
