### ISSUE TITLE
"Retrieve activations for a Metric Alert Rule API" not returning any data

### ISSUE THREAD

**Issue by Fwang36** [getsentry/sentry#81970]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

The API [at this page titled Retrieve activations for a Metric Alert Rule API](https://docs.sentry.io/api/alerts/retrieve-activations-for-a-metric-alert-rule/) is returning an empty list.

1. Have a metric alert with activations. ( [I have one here](https://francisorg.sentry.io/alerts/rules/details/301039/), last activation today)
2. Call the API.  For my alert I called `https://sentry.io/api/0/organizations/francisorg/alert-rules/301039/activations/`
3. check 200 response with just an empty array.

### Expected Result

Should return  list of activations for a metric alert rule

### Actual Result

Returns empty array

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/78c997d6-e811-460a-a73c-4c6a6c1da21d" />

### Product Area

Alerts

**Comment by ceorourke** [comment]
@Fwang36 activated alerts is a mostly unreleased feature, I'm not sure why that endpoint is even published but we'll be removing it entirely soon. Are you trying to see how many times a metric alert has been triggered?

**Comment by Fwang36** [comment]
Hey, thanks for explaining that to me.  Yes, the user that wrote in to support was looking for a way to see how many times a metric alert was triggered, and we thought that's what "activated" meant.

I was able to provide a workaround for the user, so this issue can be closed now.  Thanks!

**Comment by iain8** [comment]
just to add as the hapless user in question: was indeed trying to get a count of alerts for a short period after a deploy, and i was lured in by the prospect of the Ideal Endpoint For That. but Francis provided an option that works just as well (albeit in a kinda prescribed off-label way)
