### ISSUE TITLE
Error 500 if a team's name only contains non-latin characters

### ISSUE THREAD

**Issue by boris-chervenkov** [getsentry/sentry#820]
When I created a team named "Едно" (cyrillic characters only), I lost all access to Sentry - all it was displaying was "Internal server error".

I deleted the team from the database by hand, and Sentry was working again.

Some error information from Sentry's own error messages:
```
NoReverseMatch: Reverse for 'sentry' with arguments '(u'',)' and keyword arguments '{}' not found.

File "sentry/header.html", line 29

{% for t in TEAM_LIST %}
       <li><a href="{% url 'sentry' t.slug %}">{{ t.name }}</a></li>
{% endfor %}
```

Looks like the slug is empty if only non-latin chars are used in the team's name.

sentry	5.4.3

**Comment by mattrobenolt** [comment]
plz reopen if this is still an issue, but haven't heard anything new in the past 3 years. :)
