### ISSUE TITLE
Project Created Auto Generate error DSN cause 403.

### ISSUE THREAD

**Issue by KISSMonX** [getsentry/sentry#8207]
## Reporting Bugs

- The version of Sentry you're using

**v8.22.0**

- Whether you're using Docker or another installation method

**Docker**

- Include a stacktrace or other logs when relevant

![image](https://user-images.githubusercontent.com/2876745/39281949-dd73a54c-4939-11e8-9a3c-ccea76b733c0.png)

- Include a redacted version of your configuration when relevant
None

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
