### ISSUE TITLE
Add option to view raw request body

### ISSUE THREAD

**Issue by hoanghun** [getsentry/sentry#82122]
### Problem Statement

The rationale is that sometimes body parsing fails and I don't know if the client sent body encoded as `JSON` or `URLEncoded`, in the issue detail I only see parsed `body`.

### Product Area

Issues

**Comment by armenzg** [comment]
@hoanghun thanks for filling this.
Can you please add more details? It's unclear what part of the product you're referring to.

**Comment by hoanghun** [comment]
> [@hoanghun](https://github.com/hoanghun) thanks for filling this. Can you please add more details? It's unclear what part of the product you're referring to.

The product area is issues, issues detail. Here is the screen of the UI.
<img width="908" alt="Image" src="https://github.com/user-attachments/assets/60d72bcd-cf12-4520-9042-942d7c4bceac" />

**Comment by scttcper** [comment]
i don't believe we have the url encoded version, but the next version of issue details that you can opt into by being an early access member [more details here](https://github.com/getsentry/sentry/discussions/80801) displays the body as json

![Image](https://github.com/user-attachments/assets/ac0322a8-437d-4ba3-a87a-4b952c39bd56)
