### ISSUE TITLE
API for Performance Trace List

### ISSUE THREAD

**Issue by ostk0069** [getsentry/sentry#82123]
## What I want to achive

get performance trace data for each trace event by API to visualize in other tools.  eg grafana.

## What I used for now

By using this api bellow, I could get in table format.

https://docs.sentry.io/api/discover/query-discover-events-in-table-format/

 This is nice to have. However, List API would be way better.

### Product Area

APIs

**Comment by Dhrumil-Sentry** [comment]
Hi - We're unlikely to support APIs to export raw event data like this so I am closing this issue 

 We're happy to improve our visualization capabilities if you have any feedback
