### ISSUE TITLE
Stack frames layout issue

### ISSUE THREAD

**Issue by lbarnes4** [getsentry/sentry#82124]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

Steps to reproduce would be to open any issue and look at its stack trace. It looks like a recent change made the text spans in the stack trace frames be laid out horizontally instead of wrapping. I believe this is due to there being a `display: flex` where there should not be.

### Expected Result

![Image](https://github.com/user-attachments/assets/a86acad7-f0cf-4a13-a7a6-49092a76975b)

### Actual Result

![Image](https://github.com/user-attachments/assets/eb533927-215a-4197-8532-160692ceac6c)

### Product Area

Issues

### Link

https://flowsavvy.sentry.io/issues/6017947209/events/9b3e1d40c84146fcacc00016674e6b20/?project=4504584489074688

**Comment by armenzg** [comment]
Thanks @lbarnes4 for reporting! We're reverting a chance and the issue should be fixed in the next hour or so.
