### ISSUE TITLE
Update pip requirements

### ISSUE THREAD

**Issue by djadk84** [getsentry/sentry#8215]
I'm trying to install Sentry on Freebsd 11.1 server using python 2.7 and Clang compiler and rustc 1.25.0.
Look like to me when I tried to install sentry via pip it's breaking due to symbolic version in requirements.
pip install sentry trying to install symbolic-1.1.5.zip and the working version with rustc it 1.25.0
https://github.com/getsentry/symbolic/issues/71#issuecomment-384553477

**Comment by mitsuhiko** [comment]
@mattrobenolt this is because the release version of sentry is ancient. Fixed on master.
