### ISSUE TITLE
Setting for OTP issuer

### ISSUE THREAD

**Issue by kkrimpmann** [getsentry/sentry#8230]
When having multiple instances of Sentry and want to enable 2FA for all of them via Google Authenticator there is a problem that the entry in Google Authenticator is always replaced by the latest sentry-instance added.
I guess that the issuer parameter in the QR-code is responsible for that.

Drilling down in the code i see that always the default-value "Sentry" is taken as value as seen [here](https://github.com/getsentry/sentry/search?utf8=%E2%9C%93&q=get_provision_qrcode&type=).

I would suggest to add a setting for this to override the default.

**Comment by BYK** [comment]
I'm guessing this is still an issue, right @kkrimpmann?
