### ISSUE TITLE
Pop-up for closing widget builder with unsaved changes

### ISSUE THREAD

**Issue by nikkikapadia** [getsentry/sentry#82328]
when widget builder is being closed
1. check if the widget has been changed / unsubmitted
2. display an "are you sure?" pop-up

**Comment by nipunh** [comment]
@nikkikapadia Can i work on this?

**Comment by nikkikapadia** [comment]
Hey @nipunh, thanks for your interest! Unfortunately, this task is for an unreleased, internal feature, so it's not something we can open up for external work.
