### ISSUE TITLE
Add support for copying tag values to clipboard from the Tags tab

### ISSUE THREAD

**Issue by kerenkhatiwada** [getsentry/sentry#82381]
### Problem Statement

Currently, tag values in the Tags tab are displayed as hyperlinks, making it difficult for users to copy the full value. While the option to copy tag values exists in the issue page, it is not available in the All Tags sidebar or the Tags tab.

<img width="836" alt="Image" src="https://github.com/user-attachments/assets/2540135d-c43e-469b-9700-13ba11091c33" />

User Feedback:
I was looking at the tags in the “All tags” sidebar, and the Tags tab. That option is not available in either of those. If possible, I think it would be very useful to have that option available on the Tags tab

### Solution Brainstorm

Adding the option to copy tag values directly from the Tags tab and the “All tags” sidebar

### Product Area

Issues

**Comment by armenzg** [comment]
This is not an issue anymore with the upcoming new UI.
<img width="374" alt="Image" src="https://github.com/user-attachments/assets/ca5bcb92-e74e-477c-82ca-5fb2f97d2a1d" />
<img width="345" alt="Image" src="https://github.com/user-attachments/assets/7bf34d59-5c79-469f-82b1-851919747beb" />
