### ISSUE TITLE
ElasticSearch Database backend

### ISSUE THREAD

**Issue by kalw** [getsentry/sentry#824]
Hi there,

Is there any plan to make an ElasticSearch db backend and/or search backend ?
Seems there's support for on haystack for it (http://toastdriven/django-haystack#180#issuecomment-3342777)

Regards,

-- 
Regis A. Despres

**Comment by hatt** [comment]
This would be pretty great. There's also https://github.com/aparo/django-elasticsearch but looks like it needs some updating to run with latest Sentry/Django. My team already uses ES to distribute our log/event data, keeping traces and all the rest from Sentry in it would be great.

**Comment by dcramer** [comment]
Closing this out as we're going to rebuilding the storage/search infra

**Comment by ebuildy** [comment]
Yes this really makes sense, since a few years elasticsearch is a very good solution for logs management (via ELK stack). It supports bulk indexing, aggregation, scales horizontally, has Hadoop connector and full text search ...
