### ISSUE TITLE
Alerts - Have possibility to alert on Issue.status=new

### ISSUE THREAD

**Issue by Angelodaniel** [getsentry/sentry#82462]
### Problem Statement

As of today our Issue alert has an option for the IF clause to look for "A new issue is created" but this is looking at if the Issue.event.count() = 1 basically and is not looking into IF Issue.status="New".

This becomes a problem when I want to alert on Issue.status=New & impacted X users or X events.
(Sentry will give an error because the config is trying to do: IF Issue.events.count() = 1 & Issue.events.count() >= 100 in 1H) 
![Image](https://github.com/user-attachments/assets/d2499ab1-d611-4504-8f6b-d5d509da4d8b)

### Solution Brainstorm

Be able to alert on the actual Issue.status like we can search on in Issues stream as is:new 

### Product Area

Alerts

**Comment by ceorourke** [comment]
<img width="921" alt="Image" src="https://github.com/user-attachments/assets/03b7c1e3-6098-4453-a05d-bcb938788720" />

Can you do something like this since `is:new` is created in the last 7 days?

**Comment by Angelodaniel** [comment]
I missed that option! @ceorourke yes that would be considered as the "new" issues. Thanks!
