### ISSUE TITLE
Account Notification Settings Input Issues (UI only)

### ISSUE THREAD

**Issue by cobyeastwood183** [getsentry/sentry#82508]
### Environment

SaaS (https://sentry.io/)

### Steps to Reproduce

1. Go to account notification settings
2. Selecting "Off" on **My Own Activity** or **Resolve and Auto-Assign**

From https://sentry.zendesk.com/agent/tickets/141005. Seems to only be related to the UI. Does not affect HTTP requests to backend.

### Expected Result

1. Input is "Off" when Off
2. Input stays "On" or "Off" after page reload

### Actual Result

1. Input is "--" when Off
2. Input is "--" and value is "None selected" after page reload

### Product Area

Settings

### Link

https://sentry.io/settings/account/notifications/

**Comment by nipunh** [comment]
Hi, I would like to work on this bug.
