### ISSUE TITLE
Send email only when error occured more than X times

### ISSUE THREAD

**Issue by tomwys** [getsentry/sentry#829]
I have configured client side Javascript tracking. It is helpful in some situations but generates lots of errors. Most of the errors are related to user extensions or external services and are not my concern. I don't want to recive emails about those errors.

The simplest approach to reduce number of emails I have come up with is to sent email only if error has ocurred multiple times in single day (where multiple should be configurable).

**Comment by MaxBittker** [comment]
this is part of the alert rules engine now.
