### ISSUE TITLE
Multi Line Action Buttons lack Padding

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry#8313]
If the UI rewraps the buttons because it runs out of space on the event page it does not insert padding between the lines.

<img width="515" alt="screen shot 2018-05-04 at 14 47 14" src="https://user-images.githubusercontent.com/7396/39628673-1498dd32-4faa-11e8-95ca-fcc1dc7b5e81.png">

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
