### ISSUE TITLE
Search by lack of Jira issue

### ISSUE THREAD

**Issue by pupeno** [getsentry/sentry#8338]
I'm guessing this applies to all external issue trackers, not Jira. My triaging process is creating an issue connected to the Sentry exception (or finding and connecting to an existing one), so, it would be good to have a way to find those without any assigned yet. Those would be the issues that need triaging for me.

**Comment by benvinegar** [comment]
cc @macqueen

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by pupeno** [comment]
Yes, I still think this would be a good feature to help me triage the exceptions that haven't been triaged yet.

**Comment by BYK** [comment]
@pupeno asking around in our dedicated search and storage team and will respond here if this is something that can be done fairly easily or not.

**Comment by pupeno** [comment]
Thank you :)

**Comment by BYK** [comment]
Turns out this is non-trivial as I suspected but we have a larger project going on that may make it easier in the future. That future is no sooner than 2021 though.

Will reopen as I've seen a few more similar requests but do not expect progress soon.
