### ISSUE TITLE
Issue stream real-time update is not working.

### ISSUE THREAD

**Issue by bruno-garcia** [getsentry/sentry#8355]
A user has raised concern on [StackOverflow](https://stackoverflow.com/questions/50212213/sentry-logs-tracker-doesnt-worked-as-real-time) about the _real-time update_ feature not working properly.

I successfully reproduced on _sentry.io_:

1. Cleared issues.
2. Turned on real-time update
3. Raised a few errors
4. Nothing showed up
5. Open another tab and the issues are displayed

Minutes later I checked and there were still no issues listed.

- Sentry.io version: 8.23.0.dev0

Related issues:
https://github.com/getsentry/sentry/pull/4976
https://github.com/getsentry/sentry/issues/4689

EDIT:
I've tried again now and it seems to be working again although it seems flaky,
Seems to align with #4689 where some events just don't show up unless I refresh.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
