### ISSUE TITLE
Increase the limit in nginx for longer URLs

### ISSUE THREAD

**Issue by mattrobenolt** [getsentry/sentry#837]
(For Raven-js)

I'm pretty sure you need to bump this: http://wiki.nginx.org/NginxHttpCoreModule#large_client_header_buffers

It's for handling when a request URL is longer than 4096 characters. If this is what you need to increase, I'll add it to my documentation.

See: https://github.com/getsentry/raven-js/issues/88

**Comment by robinwassen** [comment]
I agree with @mattrobenolt, we just noticed that nginx rejects requests with a *414 Request-URI Too Large* due to their size.

We use a stack trace of 10 frames with 3 lines of pre- and post context, just that stack trace is sometimes enough for exceeding the 4KB GET request size limit.

**Comment by mattrobenolt** [comment]
@robinwassen In 1.2, the plan is to get rid of the ability to fetch context from raven-js. In Sentry now, there is an API that allows you to upload sources.

In normal scenarios (like a publicly accessible website), this is not a concern and you shouldn't need to send along context. The Sentry server will fetch them and fill in the gaps.

In private scenarios where we can't access the source (maybe a mobile application or browser plugin), we'll mitigate this by having users upload source to us directly.

Either way, the concept of raven-js fetching sources and doing these insanely long GET requests is going to go away with 1.2. 1.2 will also support sending the data via POST on modern browsers which will avoid the problem entirely.

**Comment by mattrobenolt** [comment]
I dunno, we've been doing this for a long time.
