### ISSUE TITLE
Add support for Bitbucket server

### ISSUE THREAD

**Issue by pierredup** [getsentry/sentry#8372]
Currently, Sentry only supports bitbucket cloud (bitbucket.org) to link commits to a project.
We have an instance of Bitbucket server which is hosted on-site, and it would be nice to be able to integrate our commits with Sentry.

**Comment by nilson-aguiar** [comment]
I'd like to use with the server version too

**Comment by ArcticSnowman** [comment]
Same request as #9148

**Comment by pauldraper** [comment]
Also same as https://github.com/getsentry/sentry-plugins/issues/197 and https://github.com/getsentry/sentry-plugins/issues/383

(But no comment from Sentry team on those either.)

**Comment by ErnestStaug** [comment]
Any updates? The only reason who is holding me from purchasing plan...

**Comment by JuniorSilva5150** [comment]
Any response sentry team? Feature request since 2017.. https://github.com/getsentry/sentry-plugins/issues/197

**Comment by scuben** [comment]
Trying to onboard but missing a bitbucket server integration is kind of a show-stopper :(
Any plans on this topic?

**Comment by julianuphoff** [comment]
Because my company uses bitbucket server for all of our project, we can't use senty's maximum potential. We would upgrade our account if we could connect to bitbucket server.

**Comment by markstory** [comment]
There aren't any current plans to build a bitbucket server integration. I'll forward this feedback up to the product folks though.

**Comment by pierredup** [comment]
An implementation for Bitbucket server is added in #15221

**Comment by LouisMilesRH** [comment]
We would still really really like this... is there any plans to merge @pierredup fixes? Looks like @scefali was reviewing it... 👀
