### ISSUE TITLE
Project named "Billing" interferes with billing and usage page

### ISSUE THREAD

**Issue by MaggotMouth** [getsentry/sentry#8373]
Hi,

I'm using the hosted instance of Sentry.

I have created a new project for the organization called "billing".  I am trying to access the project's settings, but get redirected to `/settings/organization/billing/overview` which is the Usage & Billing page, not the project's settings.

The usage & billing page's url needs to be altered, or "billing" needs to become a reserved word or something so that other people dont run into the same problem as me.

I've reached out to sentry support via mail to rectify my current situation.

**Comment by billyvg** [comment]
Thanks @MaggotMouth, I'll add the `billing` slug (as well as others) to the reserved project name list. I'm assuming you've contacted support to have the project renamed?
