### ISSUE TITLE
Broken DSN keys link

### ISSUE THREAD

**Issue by dmyerscough** [getsentry/sentry#8377]
When running Sentry locally on my machine I noticed that the DSN link was broken, everytime I tried to access the `DSN Keys` page it was redirected to:-

http://127.0.0.1:9000/sentry/django/settings/example.com/sentry/django/settings/keys/

However, this should have been direct to the correct page of

http://127.0.0.1:9000/sentry/django/settings/keys/

## Reporting Bugs

When reporting bugs, include details about your configuration, such as:

- The version of Sentry you're using

sentry-onpremise latest

- Whether you're using Docker or another installation method

Docker installation

- Include a stacktrace or other logs when relevant

No Stacktrace occured, just an incorrect link is generated

```
172.18.0.1 - - [09/May/2018:18:11:02 +0000] "GET /sentry/django/settings/example.com/sentry/django/settings/keys/example.com/_static/1525888003/sentry/images/icons/apple-touch-icon.png/ HTTP/1.1" 200 4122 "http://127.0.0.1:9000/sentry/django/settings/example.com/sentry/django/settings/keys/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36"
```

- Include a redacted version of your configuration when relevant

I followed the sentry-onpremise documentation.

**Comment by pquerner** [comment]
Make sure you have a correct Root URL set.

**Comment by markstory** [comment]
I tried to reproduce this locally and couldn't. Closing.
