### ISSUE TITLE
Slack Integration: Bug alerts not coming through for Global Integration

### ISSUE THREAD

**Issue by jbbae** [getsentry/sentry#8396]
Hi,

I upgraded the Slack integration to the new "Global Integrations" one, and I suddenly stopped getting bug alerts altogether (something which worked just fine in the old integration I had set up...) I have tried fiddling with the settings as well with no luck... Any idea what could be wrong?

**Comment by channprj** [comment]
Me too. All alerts stopped. How can I fix it?

**Comment by EvanPurkhiser** [comment]
Did you configure alerts for the integration? See https://forum.sentry.io/t/slack-integration-feedback/3146

**Comment by channprj** [comment]
@EvanPurkhiser I already set up alerts rules, but it doesn't work.

**Comment by EvanPurkhiser** [comment]
What does your alert rule look like?

**Comment by channprj** [comment]
<img width="921" alt="2018-05-15 14 30 30" src="https://user-images.githubusercontent.com/1831308/40038369-bef37b16-584c-11e8-87cf-5640640e2011.png">

Is it right?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
