### ISSUE TITLE
CI tests for Django 1.8 are installing 1.6 and thus misleadingly passing

### ISSUE THREAD

**Issue by JoshuaRLi** [getsentry/sentry#8406]
The [latest successful CI test with `DJANGO_VERSION` set to `1.8.x`](https://travis-ci.org/getsentry/sentry/jobs/377471508) at the time of writing are actually using a virtual environment with `1.6.x` (see line 750 of Travis job log).

I'm currently working on a `Makefile` + `.travis.yml` revamp which, among many fixes and changes, correctly installs the correct `DJANGO_VERSION`. And no, our tests don't pass on 1.8 - so I will be moving that matrix job to `allow_failures`.

**Comment by MaxBittker** [comment]
: O

**Comment by JoshuaRLi** [comment]
Fixed in #8419.
