### ISSUE TITLE
[BUG] "Create a New Release for an Organization" API endpoint says {"projects"=>["This field is required."]} even with an array is provided

### ISSUE THREAD

**Issue by joeyparis** [getsentry/sentry#8418]
When attempting to `POST https://sentry.io/api/0/organizations/{organization-slug}/releases/` with the following payload:

```
{
	projects: [<project-slug>],
	url: "https://bitbucket.org/<commit-url>",
	version: <commit_sha>,
}
```

However, when making that request I am returned a 400 error with this body:

```
{
	"projects": ["This field is required."]
}
```

I'm positive I have the variables in the right place because if I remove the `version` attribute that attribute is added to the error message about required fields. If I replace `[<project-slug>]` with a string (e.g. `projects: "hear-is-a-slug"`) the error I get back is:

```
{
	"projects": ["Incorrect type. Expected a list, but got unicode"]
}
```

So it's clear the API is able to see that attribute but is falsely reporting it as being missing when it's not.

I'm using the current version of the API and making my request with Ruby's `RestClient` tool.

**Comment by tivervac** [comment]
I have the same issue just using the a regular curl post to `https://sentry.io/api/0/organizations/{slug}/releases/`. The projects array is most certainly there

**Comment by BYK** [comment]
Are you able to share a full request log? We are okay with some redaction but try to keep the types the same (such as `["<redacted-project-slug>"]` above, instead of `[<project-slug>]`) to ensure everything is right.
