### ISSUE TITLE
Better grouping of events based on stacktraces

### ISSUE THREAD

**Issue by tsondergaard** [getsentry/sentry#8430]
sentry.io would benefit hugely from improved algorithms for grouping events based on stack traces. I good first step would be to introduce a stack trace similarity metric so stacktraces don't have to be (virtually?) identical to be grouped.

Some existing work within this domain: 
* ReBucket algorithm: https://www.microsoft.com/en-us/research/wp-content/uploads/2016/07/rebucket-icse2012.pdf
* Experimental implementations: https://github.com/skmry/rebucket and https://github.com/dgryski/go-rebucket

Something less advanced might also do the job, ie some basic filtering of the stacktrace and then some adaptation of the levenshtein edit distance algorithm could be used. Refinements that put extra relevance on the top stack frames would be an improvement.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by BYK** [comment]
Actually, I find this very interesting. Will keep open for self-interest 😀

**Comment by MichaelSun48** [comment]
Closing this out since this is now being done as part of our [AI Grouping](https://www.youtube.com/watch?v=J5svAaPNCkc) feature.
