### ISSUE TITLE
`sentry.lint.engine` should not require pycodestyle when linting JS

### ISSUE THREAD

**Issue by JoshuaRLi** [getsentry/sentry#8451]
See 3dae137, where `pycodestyle` had to be added as a dependency to pass the js Travis CI test suite. This should be fixed.

**Comment by billyvg** [comment]
Would be nice to eventually remove python deps completely from the js job.

**Comment by mattrobenolt** [comment]
That's the goal, the only other dependency is `click`.

**Comment by JoshuaRLi** [comment]
Fixed in #9044.
