### ISSUE TITLE
Do issues get deleted after certain period of time?

### ISSUE THREAD

**Issue by s-nizamani** [getsentry/sentry#8479]
We had some old issues in our php project that are now completely gone. They are not in resolved, or unresolved. Do sentry delete issues after a certain time period? Oldest php issue we have after searching for is:resolved and is:unresolved is 6 days old

**Comment by MRZMUH001** [comment]
Likewise. We think data got reset after the recent upgrade? Even the project names are different.

**Comment by zachd** [comment]
Hi, we are also experiencing this problem. Our recent issues were wiped.

**Comment by mattrobenolt** [comment]
Are you all on sentry.io? We haven't deleted any data, but if you are an "early adopter", you got opted into our new environments feature that has a limited set of historical data. The "All Environments" environment though in this case should still contain all of your data.

**Comment by benvinegar** [comment]
> Even the project names are different.

So, previously every project had a non-unique name (e.g. "MyProject") and unique slug (`my-project`). The slug was usually derived by the name automatically, but it could always be edited.

In the latest version, in the interest of having unique projects names, we started surfacing the project slug instead. Take a look and see if this is the case.

**Comment by dcramer** [comment]
Also if this is on our SaaS service, there are various retention periods. If you're on our free plan that retention period is 7 days. Historically this has been soft-enforced (in that we didn't guarantee the 7 days of retention, but we didn't always delete the data). More recently we've enforced that visibility and will begin enforcing it in the data processing pipeline at some point in the future.

If the above doesnt sound like it's the problem you're experiencing please let us know.
