### ISSUE TITLE
Search Bar resets itself periodically when playing last seen issues 

### ISSUE THREAD

**Issue by alsuren** [getsentry/sentry#8503]
When receiving real-time updates, the contents of the search box is reset. This often happens when you are in the middle of typing a query.

Steps to reproduce:

- Sort by Last Seen (it happens in other modes, but the list-refresh is easier to notice in this mode)
- Click `Enable real-time updates` (the play button)
- Type something in the search bar (after is:unresolved)
- Wait (or keep typing)
- Notice that the thing you typed goes away whenever the issue list refreshes.

This can happen when you're in the middle of typing something (at which point it strips the space after is:unresolved, resulting in garbage in the search bar if you're not paying attention).

Work-around:

- Click pause
- Type your search query
- Click play again.

The version of Sentry you're using
  - The hosted version on sentry.io

This seems related to the outstanding point on https://github.com/getsentry/sentry/issues/2526 (changing filters in the right-hand sidebar clears the search) and https://github.com/getsentry/sentry/issues/5871 (lazily adding space to search box causes a re-render). All three should probably be considered when changing how the search box's state is managed.

**Comment by alsuren** [comment]
The fix for this turned out to be a one-liner ( #8711 ) and doesn't affect either of the other two bugs I linked to above. 

It looks like it was just a simple error in c4d4cbdb557c03655003a4ae86b822b472e6d0e1 (right at the very end of https://github.com/getsentry/sentry/pull/2056 ). The intention was to make the `setState({query: nextProps.query})` call trigger whenever the `query` prop changes from outside, but in practice it triggers whenever `props.query` is different from `state.query`, which can happen even when `props.query` hasn't changed from its previous value. My fix compares `nextProps.query` against `this.props.query`, so the `setState()` call is edge-triggered only when `props.query` is changed from its previous value.

I'll be around until June 15th (Friday) to address any review comments, then I'm on holiday for a week.

**Comment by billyvg** [comment]
Thanks for the PR @alsuren! I'll review your PR this week, enjoy your holiday!
