### ISSUE TITLE
Error when requesting to join teams

### ISSUE THREAD

**Issue by ayesha-omarali** [getsentry/sentry#8512]
"Request to join" button toggles randomly between a clickable "..." button and "request to join" -- after refreshing it shows "request pending".
Possibly add "cancel request" button and fix refreshing so the buttons don't get weird. 

<img width="1097" alt="screen shot 2018-05-21 at 4 21 49 pm" src="https://user-images.githubusercontent.com/10991288/40334583-7776ec0c-5d13-11e8-91f9-6880e46c6d6e.png">
@lynnagara

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
