### ISSUE TITLE
Filter for 'release:all'

### ISSUE THREAD

**Issue by yeleleo** [getsentry/sentry#8529]
## Feature request

Now in the filters you can see only issues for the current release and even in filter you can see only one release a time - so it would be great to have `release:all ` filter to see all the reports as there is no releases at all

**Comment by dcramer** [comment]
@yeleleo for clarify, you want to see "all issues which have a release associated with them" ?

We could probably do something like ``has:release``.

**Comment by yeleleo** [comment]
@dcramer I want to see all issues in total, regardless to release

**Comment by dcramer** [comment]
Then simply remove any filter you've applied. Maybe you're talking about environment? We absolutely do not filter on any release (let alone current) by default.

**Comment by yeleleo** [comment]
In my case I see only 5 issues in the report but in my email inbox I see at least 46 issues (via name Performance %@ - %@-46) which are still open (if you go there by direct link).

Also I see that old issues which is not in the list has id $PROJECT$-46 - new ones $PROJECT$-3Z

e.g. I don't see in the list issue: issues/550024974

also file of the release attached
![2018-06-22 13-46-35 release c61ab0447c2dadff4af339196b31e3c0d816b385 tb-back-end](https://user-images.githubusercontent.com/1327411/41775135-f782f170-7622-11e8-9fd0-beb8a71e6122.png)

**Comment by yeleleo** [comment]
Here is another sample of the wrong filtering

![2018-07-02_22-20-48](https://user-images.githubusercontent.com/1327411/42182267-5120ceb6-7e46-11e8-9513-7cfb7b01dc83.png)

**Comment by dcramer** [comment]
@yeleleo its possible something is not being saved or its been deleted (but still indexed)

If this is SaaS its easy for us to confirm this, if its localhost I'd guess its an issue with your installation (so id check worker logs).

**Comment by yeleleo** [comment]
@dcramer hi, it is saas,

Please check the case:
- Project ID: 1186562

I see no issues 
![2018-07-04_22-25-00](https://user-images.githubusercontent.com/1327411/42292152-1f8fe050-7fd9-11e8-8f25-60d89dae5180.png)

But I still can go to the issues directly:
- issues/550024974 (unresolved)
- issues/567590815 (unresolved)
- issues/553158596 (resolved)
- issues/543220403 (unresolved)

and many others.
Please tell me if it will be better to email you the full links.

**Comment by dcramer** [comment]
@yeleleo are you on the free plan? if so the stream will be limited to the last 7 days of data (which is the retention plan applied to the account). We dont enforce it everywhere yet, and dont always hard delete at 7 days.

(The age:-100d is also useless in that query as we never store events after 90 days on sentry.io)

**Comment by dcramer** [comment]
@yeleleo we wont display them in the list, but we will likely fix it so they become inaccessible. We'll also be improving how things show up, but its not always easy to convey "oh you're not seeing results because you only see 7 days of data". Its really any different than 90 days. We might say "Theres no results available in the [retention period]".
