### ISSUE TITLE
Releases in project card not correct and/or up-to-date

### ISSUE THREAD

**Issue by stayallive** [getsentry/sentry#8541]
On Sentry.io the releases in the project card seem te be incorrect.

This is what it is showing for a project for me:

![image](https://user-images.githubusercontent.com/1090754/40489364-32d68672-5f69-11e8-8ad5-a667b95d11d3.png)

And this is in the releases tab of that project:

![image](https://user-images.githubusercontent.com/1090754/40489485-85a316a4-5f69-11e8-966b-43ba6e5771fd.png)

So the releases or not up-to-date and I would expect (and hope) the staging release to also shows up there.

**Comment by stayallive** [comment]
Yes this fixed it, just needs a bit shorter "a few seconds ago" string 😄 

![image](https://user-images.githubusercontent.com/1090754/40575125-feeeb380-60de-11e8-908c-f714efbc885c.png)

**Comment by benvinegar** [comment]
Great!
