### ISSUE TITLE
Issue tracker not linked on all errors

### ISSUE THREAD

**Issue by adityar7** [getsentry/sentry#8574]
We are using the Phabricator integration. Some errors on Sentry have a “Create Maniphest Task” button as expected, but others show “Link Issue Tracker” button.

Refreshing the page doesn’t help i.e. it’s not a transient error. Refreshing shows the same button the page had before the refresh.

On pages that have a “Create Maniphest Task” button the integration works fine, so it’s not an issue with the integration either.

Certainly seems like a bug.

**Comment by dcramer** [comment]
@adityar7 its very possible somethings problematic with our Phabricator integration. We haven't updated it in quite some time and have done an enormous amount of work on the overarching system. It's something we'll dig into (if no one beats us to it), once we get past the new revisions of Jira, GitHub, and Bitbucket.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
