### ISSUE TITLE
Unable to track 404 errors using angular sentry.io with raven.js

### ISSUE THREAD

**Issue by thiruopti** [getsentry/sentry#8575]
Hi,

      I can't able to track 404 (Page not found/file missing errors) using sentry.io in an angular application.
      Sample error 
         jquery.js:5800 GET http://localhost:22400/styles/fonts/Segoe-ui/SEGOEUI.woff2 404 (Not Found)
Thanks,
Thirupathi Raj.V

**Comment by dcramer** [comment]
This qualifies as general support or a usage question, rather than bug with the Sentry server, so I'm closing this ticket.

https://sentry.io/support/
