### ISSUE TITLE
Can't pay using card

### ISSUE THREAD

**Issue by easle-green** [getsentry/sentry#8578]
![2018-05-29 22 07 41](https://user-images.githubusercontent.com/85288/40679848-fef68bcc-638c-11e8-897c-328920f3dcac.png)

![2018-05-29 22 12 22](https://user-images.githubusercontent.com/85288/40679998-69b13106-638d-11e8-87e5-45c264c7114a.png)

I think this is not normal that i can't pay using card.
Any another service accept my card.

How can i get paid plan?

**Comment by MaxBittker** [comment]
(this has moved over to support)
