### ISSUE TITLE
Fetch as google produces error 

### ISSUE THREAD

**Issue by jimmykane** [getsentry/sentry#8629]
Hi I am not sure if this fits here but I ll take my chances. 

I am using the latest Sentry with a Angular 6. 

When on the google webmaster tools I try to use fetch as google the page does not get fetched due to a sentry error as seen below

<img width="1101" alt="screen shot 2018-06-01 at 14 49 56" src="https://user-images.githubusercontent.com/1268723/40841608-5a53f034-65ab-11e8-8c1b-82c3985fd95e.png">

Any tips or info 

Sorry if I post on the wrong place, I found a similar issue at the forum but none had replied

**Comment by mattrobenolt** [comment]
What’s the issue? There’s nothing at this endpoint for Google to fetch. This is the API endpoint for ingesting error data, so there’s nothing to scrape here, and would need a valid error payload.

**Comment by jimmykane** [comment]
@mattrobenolt the problem is since the resource cannot be fetched the render of Google is partial/broken 

Here is what my about page looks like for a normal visitor 

<img width="1416" alt="screen shot 2018-06-01 at 15 15 21" src="https://user-images.githubusercontent.com/1268723/40842584-9ffb8694-65ae-11e8-9300-700ef4328b13.png">

However when the google bot fetches it: 

<img width="1134" alt="screen shot 2018-06-01 at 15 16 14" src="https://user-images.githubusercontent.com/1268723/40842618-bfe25078-65ae-11e8-82ca-0c97a23bacc7.png">


Not a 100% sure but then the Google bot wont parse any text data (since the JS is broken) thus the website is not correclty scraped ending in a very low ranking (that is not my big problem actually)

Because I am new to Sentry I might be doing something wrong so thanks for your time to teach me

**Comment by mattrobenolt** [comment]
So it’s hard for me to say, since I also don’t really know much about what Google is doing here, but it seems more like your website is triggering an exception when Google is scraping it, causing the exception to attempt to be logged. And the exception is why the page is failing to render. 

I’m open to being completely wrong here, but this is what seems to be wrong logically. There’s no other way that Google would even be getting that url unless it did something to trigger an error, since that URL is assembled in raven-js when an error is being sent.

@benvinegar @kamilogorek do you maybe have any other ideas?

**Comment by jimmykane** [comment]
@mattrobenolt  that is what I am starting to suspect as well. 

I ll take a look into it and get back and update the issue status. 

Thanks so much for the effort.

**Comment by jimmykane** [comment]
@kamilogorek yup that must be it. 

Sorry for the alert and great news guys about Sentry 9

But just for the reference here is what happened

- I could not fetch as Google and that pointed me to here a google looked like they could not fetch the sentry or something similar (not very familiar with the Sentry internals)
- I removed crawlers from the inbound filters and got the error which I think relates to Angular 6 (there we go again) 

I think I can close this, for now, guys and thanks a TON for the magnificent engagement and turning my neck to the right direction.
