### ISSUE TITLE
Minidump: add a way to download the minidump

### ISSUE THREAD

**Issue by supercairos** [getsentry/sentry#8665]
I used mini-dump before with this simple server ([simple-breakpad-server](https://github.com/acrisci/simple-breakpad-server)). 
It's just a super simple server that does stackwalking report and minidump hosting.
But one of the feature that iSentry's minidump implementation is lacking is a way to download the minidump file. 

Please, if possible, add a download button of the minidump files :)

Thanks 💯

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

/cc @jan-auer in case we already have this (or planning to add)

**Comment by supercairos** [comment]
This is indeed done on your end :)
