### ISSUE TITLE
Left panel gets shifted over when dialogs are open

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry#8719]
In current sentry.io:

![dialog-bug](https://user-images.githubusercontent.com/1150298/41302210-329b47dc-6e6a-11e8-85b0-547b3bd841ce.gif)

**Comment by billyvg** [comment]
Looks like this is a bug in firefox.

**Comment by timfish** [comment]
I haven't tested Firefox but the above GIF was recorded in Chrome 68...

**Comment by billyvg** [comment]
From one of the issues, it sounded like Firefox was conforming to spec while Chrome wasn't, so it's possible the behavior was changed in Chrome68 to spec (have not tested in 68).

**Comment by timfish** [comment]
I'll have a look into this, but it looks like caused entirely by the filter!
It's exactly the same in Firefox 61.0.1 and Chrome 68.0.3440.68.

![filter-ui-shift](https://user-images.githubusercontent.com/1150298/43268344-a9c989f6-90f0-11e8-9edf-c60253c86c7b.gif)
