### ISSUE TITLE
Global environment filtering includes events which have zero occurrences 

### ISSUE THREAD

**Issue by timfish** [getsentry/sentry#8720]
In current sentry.io.

Global environment filtering does not exclude events which have zero occurrences in the currently selected environment. 

Take the example below. This event has only been seen once in development but displays for production but with zero occurrences:

![sentry-filtering](https://user-images.githubusercontent.com/1150298/41302684-65dbf35c-6e6b-11e8-9d6c-5393f91c84c9.gif)

**Comment by infoeon** [comment]
Even worse, the "Environment" option seems to have disappeared since yesterday. Did they possibly do a rollback?

**Comment by timfish** [comment]
@infoeon this feature should only be available to those with early adopters:

> The environments feature is only available for early adopters. You can enable early adopter features by navigating to your organization settings

You'll need to be an org admin to enable early adopter features

**Comment by untitaker** [comment]
@timfish what's the resolution status on this from your pov?

**Comment by timfish** [comment]
This environments feature was in preview and parts of it leaked through when you didn't have "early adopter" enabled.

As far as I can tell, this feature is now available to all so this bug is no longer relevant!
