### ISSUE TITLE
There was an error loading data -- v8.22

### ISSUE THREAD

**Issue by leniserodrigues** [getsentry/sentry#8727]
Hi there!

I use my own setup of servers to run sentry -- 13 vms, including web, workers and queue. Also a postgres db and redis pool for cache.

For some events, i get this error "There was an error loading data".

The console log:
request /api/0/issues/{issue_id}/ -- it's a GET(obviously)
response 504 Gateway Time-out

Can someone help pls?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
