### ISSUE TITLE
Send more than one event at once through the API

### ISSUE THREAD

**Issue by ColinHebert** [getsentry/sentry#873]
It could be useful to be able to send more than one event at once through the API.

For example if HTTP is used HTTP (to avoid UDP and ensure that the data will be received), instead of sending the events as soon as they are generated, it could be possible to open only one connection and send a batch.

This would reduce the HTTP overhead while keeping the advantages of HTTP (yay handshakes).

**Comment by dcramer** [comment]
Addressing in GH-1092
