### ISSUE TITLE
Strange localization issue in user feedback dialog

### ISSUE THREAD

**Issue by FredyC** [getsentry/sentry#8760]
This is concerning Czech localization, but I suspect others might have the same issue.

https://github.com/getsentry/sentry/blob/5a1da65a100a9033dbc7b93e4082570cdc477940/src/sentry/locale/cs/LC_MESSAGES/django.po#L954
![image](https://user-images.githubusercontent.com/1096340/41508359-d87ab688-7243-11e8-9d14-61078110ba98.png)

The translation text is correct here and yet for some reason when the dialog is shown to the user, it looks like this. For some reason, only first half is translated, but a second part contained within `span` is kept original and even cut off.

Is this some known issue in the translation software you are using? It would probably help to strip down that `span` element there as it causing issues obviously.

**Comment by FredyC** [comment]
@dcramer I realize this is not a top priority issue, but at least some reaction would be nice. Or ping someone who can respond to this, please.

**Comment by dcramer** [comment]
@FredyC so we dont actually have the cs localization upstream. Is this a modified version of Sentry?

**Comment by dcramer** [comment]
Disregard last comment

**Comment by dcramer** [comment]
k repro'd locally

**Comment by FredyC** [comment]
Oh nice, wasn't expecting such a quick fix. I assume it still needs to be fixed in locale files itself? I will create PR for czech language soon then.

**Comment by dcramer** [comment]
It’ll need fixed in the locale but we do all of that through transifex. If you sign up and request access to the project for Czech I can approve

**Comment by FredyC** [comment]
Ok, I've request access, username is `klenicak`.

**Comment by dcramer** [comment]
Aside if you only need it in Czech for your site, you could also override the labels now:

https://docs.sentry.io/learn/user-feedback/#customizing-the-widget
