### ISSUE TITLE
Team selector on new project being cut of by the footer

### ISSUE THREAD

**Issue by stayallive** [getsentry/sentry#8762]
This is on sentry.io as of the time of submitting this issue.

![image](https://user-images.githubusercontent.com/1090754/41523236-7dd045fe-72d9-11e8-9362-4e1d2869eeb9.png)

This is when creating a new project and selecting an team, the #overwatch team is not selectable right now since the logo image is capturing all scroll/click events.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
