### ISSUE TITLE
Webhook's `Test plugin` always returns success

### ISSUE THREAD

**Issue by note** [getsentry/sentry#8788]
Sentry 8.22.0

I am running sentry locally using onpremise exactly as it's described here: https://github.com/getsentry/onpremise

I am on this page trying to set webhook: http://localhost:9000/sentry/MyProject/settings/alerts/. It does not matter what I type in into `Callback URLs` field; after clicking `Test plugin` I am always getting successful response (namely `"No errors returned"`). Also, it does not matter if I click `save changes` before testing or not.

With that issue test functionality is not very useful.

**Comment by note** [comment]
Another observation, I received in `internal` project an issue:

```
HTTPConnectionPool(host='anything', port=7655): Max retries exceeded with url: /anything (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4bc47c3290>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

So seems like the request is actually failing but the UI does not reflect that

**Comment by BYK** [comment]
Closing due to staleness and 8.22 is not even a thing anymore. Feel free creating a new issue if you still have this with more recent versions.
