### ISSUE TITLE
Source code was not found for app:///index.android.bundle

### ISSUE THREAD

**Issue by ZhuZeus** [getsentry/sentry#8817]
Hi, i'm using v0.38.0

the question is ,the error said that it can't find the source when i'm totally follow the [step](https://docs.sentry.io/clients/react-native/) and i can't figure out what happened to my project.

I can see the error of the report，but there was 1 error encountered while processing this event

**Comment by bruno-garcia** [comment]
Closing this as stale. If this issue affects you please use the latest version of the RN SDK:

https://github.com/getsentry/sentry-react-native
