### ISSUE TITLE
Add Webflow crawler to list of known web crawlers

### ISSUE THREAD

**Issue by SAGV** [getsentry/sentry#8821]
Webflow uses `Webflow 1.0 (Site Screenshot)` crawler to take screenshots and display in their admin interface. However, this crawler doesn't seem to support JS well and sometimes gives errors.

Would be a good idea to add it to the list of known web crawlers to filter out those errors automatically.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
