### ISSUE TITLE
[BUG] Project Named "auth" share URL with sentry settings

### ISSUE THREAD

**Issue by mrtarunjain** [getsentry/sentry#8848]
I have a project name 'auth'.

When I go to project settings I am navigated to Sentry settings. (url: https://sentry.io/settings/cuemathcom/auth/)

I can't change the project name as it can be changed from project settings page. But i am not able to open it.

Please fix this.

However, I am able to access it using https://sentry.io/settings/cuemathcom/auth/alerts/

But not able to access General Settings.

**Comment by billyvg** [comment]
@mrtarunjain `auth` is a disallowed slug name, what would you like me to change it to?

**Comment by mrtarunjain** [comment]
authservice

**Comment by mrtarunjain** [comment]
Can you please help me with https://forum.sentry.io/t/bitbucket-only-one-configuration-missing/4000

**Comment by billyvg** [comment]
@mrtarunjain I've renamed it to `authservice` for you.
