### ISSUE TITLE
UDP settings not being considered

### ISSUE THREAD

**Issue by maraujop** [getsentry/sentry#886]
Hi there,

Following docs, I set these variables in my sentry settings file:

```python
SENTRY_UDP_HOST = '0.0.0.0'
SENTRY_UDP_PORT = 9201
```

However, I finally found out they were not being used, instead I need to start udp server like this:

```bash
sentry start udp 0.0.0.0:9201
```

I'm guessing this is not the intended behavior, otherwise I understood something wrong from the docs.

Thanks, cheers
Miguel

**Comment by master-lincoln** [comment]
Since UDP support is now dropped with 78ce382f31c1176687ef324b921990daa677baff this can probably be closed.
