### ISSUE TITLE
Slack Integration - self hosted sentry with docker

### ISSUE THREAD

**Issue by AlexanderBabel** [getsentry/sentry#8861]
Hello there,

I updated to the newest sentry version (0.9) and can not enable the new global slack integration because of a missing client_id. I tried to copy the client_id of official slack plugin, but the redirect urls wich are allowed point to sentry.io.

Error message:
<img width="636" alt="picture 1" src="https://user-images.githubusercontent.com/13570439/41966716-239a8a58-7a00-11e8-9375-68407508859a.png">

Request url:
<img width="997" alt="picture 2" src="https://user-images.githubusercontent.com/13570439/41966869-8a61c1ac-7a00-11e8-8e6c-2bd25dbb15f0.png">

Redirect url error when trying to use client_id of official plugin:
<img width="561" alt="picture 3" src="https://user-images.githubusercontent.com/13570439/41967271-88413e1a-7a01-11e8-9a10-5ab1ff5effc3.png">

**sentry version**: 0.9.0
**Install method**: docker (docker-compose file)

**Comment by EvanPurkhiser** [comment]
Hi @AlexanderBabel, check out the [on-prem instructions here](https://forum.sentry.io/t/how-to-configure-slack-in-your-on-prem-sentry/3463/5)

**Comment by AlexanderBabel** [comment]
Hello there my problem still exists. This time if I use "sentry config get slack.client-id" to see if it set correctly the console prints: "Unknown config option found: 'slack'"

**Comment by EvanPurkhiser** [comment]
Alex are you're sure you're typing `sentry config get slack.client-id` exactly? If that key didn't exist the error message should look like

```
evan $ sentry config get slack.client-id
Error: unknown option: slack.client-id
```

For example if I run

```
evan $ sentry config get slack.client-id-bad-key
Error: unknown option: slack.client-id-bad-key
```

(Working output should look something like this)

```
sentry on evanp-work › sentry config get slack.client-id
        type: STRING
 from config: 2169437334.330998002166
     current: 2169437334.330998002166
```

Is your app not working at all?

> I tried to copy the client_id of official slack plugin

How did you set the client id initially?

Also, in the future please ask support questions like this on the [sentry support forum](http://forum.sentry.io/) :)
