### ISSUE TITLE
TypeErrorapp/components/onboardingWizard/todos in ? after upgrading to version 9.0.0

### ISSUE THREAD

**Issue by cpoetter** [getsentry/sentry#8888]
Hi, 

I just upgraded to version 9.0.0. I am running sentry in the official sentry docker image. I see the following bug report in the internal sentry project page once I visited the new settings page `https:/[...]settings/`:

```
TypeErrorapp/components/onboardingWizard/todos in ?
errorundefined is not an object (evaluating 'e.onboardingTasks')
```

![4](https://user-images.githubusercontent.com/9142522/42083849-555ab012-7b8c-11e8-8079-23f4e8a6c0b5.png)

## Steps to reproduce the error:
1. Visit the settings page
![1](https://user-images.githubusercontent.com/9142522/42083891-7aed7ee0-7b8c-11e8-8d14-9d7304decc4f.png)
2. Click on the **Server admin**
![2](https://user-images.githubusercontent.com/9142522/42083927-902c132a-7b8c-11e8-9c64-242ea0f3530c.png)
3. Click on **Getting started with Sentry: 0/7 tasks completed**
![3](https://user-images.githubusercontent.com/9142522/42083967-a6fbf462-7b8c-11e8-8bb8-a5dee6296c75.png)
4. See the error **There was an error loading a component.**

## Additional error report:
When I want to see the *old* settings page and click on the link in `You can temporarily visit the old settings page if necessary.`, nothing happens.

**Comment by ttionya** [comment]
The same problem as you.

 But I can back to old settings page in "My Account".

![image](https://user-images.githubusercontent.com/22736919/42418266-04792800-82cf-11e8-8e41-6d2884462ef6.png)

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
