### ISSUE TITLE
Slack Integration - chat:write Scope

### ISSUE THREAD

**Issue by ocordeiro** [getsentry/sentry#8897]
- Using latest version of Sentry On-Premise;
- slack.client-id, slack.client-secret, slack.verification-token configured correctly;

On click on "+Add workspace" in Slack integration, I received this error:

**"Invalid permission request: User tokens do not support scope chat:write"**

![invalid](https://user-images.githubusercontent.com/1471463/42138111-c7455954-7d3d-11e8-939c-c5914cbc292a.jpg)

Slack OAuth, don't have chat:write scope. Only: chat:write:bot  and chat:write:user

![captura de tela 2018-07-01 as 14 34 04](https://user-images.githubusercontent.com/1471463/42138067-ec6d3720-7d3c-11e8-834e-f65b84e62145.png)

Then i changed /usr/local/lib/python2.7/site-packages/sentry/integrations/slack/integration.py
and update chat:write to chat:write:bot
Solved this bug and show "Authorization Screen" 

![authorize](https://user-images.githubusercontent.com/1471463/42138125-f9b00470-7d3d-11e8-9946-2db1e0673313.jpg)

But on click "Authorize" I receive this error: "Failed to retrieve token from the upstream service"

![failt_upstreem](https://user-images.githubusercontent.com/1471463/42138129-0d4b5944-7d3e-11e8-952b-9f9ad7425643.jpg)

**Comment by ocordeiro** [comment]
Solved, Sentry needs Workspace Apps https://api.slack.com/workspace-apps-preview

**Comment by amihura** [comment]
Hi @ocordeiro , workspace app is already configured, but having same issues, what exactly have you done? Thanks
