### ISSUE TITLE
Deploy hook URL

### ISSUE THREAD

**Issue by wernight** [getsentry/sentry#8898]
Sentry 9.0 RC1 (Docker onbuild)

![image](https://user-images.githubusercontent.com/145667/42153686-2999cae4-7de4-11e8-8f79-7b882d06e1b5.png)

I see the [blog post](https://docs.sentry.io/learn/releases/) telling about using authentication token but that doesn't seem to match this **deploy token**. To me it looks like there should be an example of a curl request using the deploy token url. I didn't find any documentation talking about this token.

Here is what I found:

 - https://docs.sentry.io/learn/releases/#tell-sentry-about-deploys says `https://sentry.io/api/0/organizations/:organization_slug/releases/:release_version/deploys/` which should be at least `https://sentry.io/api/0/organizations/{organization_slug}/releases/{release_version}/deploys/`
 - https://docs.sentry.io/api/releases/post-release-deploys/ says `/api/0/organizations/{organization_slug}/releases/{version}/deploys/`
 - https://blog.sentry.io/2017/05/09/release-deploys says `https://sentry.io/api/0/organizations/$ORGANIZATION_SLUG/releases/$RELEASE_VERSION/deploys/`

However the web hook for releases is more like: `https://sentry.io/api/hooks/release/builtin/0/$TOKEN`

**Comment by wernight** [comment]
I found a possibly related commit: https://github.com/getsentry/sentry/commit/09fe5ebeeae761dae6721b8310c19c98deba11ab but looks like nothing registered that hook URL https://github.com/getsentry/sentry/blob/master/src/sentry/api/urls.py#L710. That page should be renderer at https://github.com/getsentry/sentry/blob/94db6b06ed7b556ba1788a3ffe44fe3a05d946cb/src/sentry/static/sentry/app/views/settings/project/projectReleaseTracking.jsx#L50

**Comment by wernight** [comment]
Anyone can clarify what that deploy hook url should be?

**Comment by wernight** [comment]
Also posted on https://forum.sentry.io/t/deployment-hook-url/4133.

**Comment by ssx** [comment]
This stumped me for a while today as well, it looks as though a deploy has to be logged against a release, so this one looks the best bet:

https://sentry.io/api/0/organizations/{organization_slug}/releases/{release_version}/deploys/

**Comment by wernight** [comment]
Yes if you log in that works but that's with login through the API, not a web hook.

**Comment by sebastiaanluca** [comment]
Any update on this? No idea how to tag a release via the hook or the API. As part of the deployment process, we can't even use the API since we can't create the required OAuth bearer token.

**Comment by amanfredi** [comment]
The documentation for this is really unclear. You still have to specify the auth token in the header for the webhook url to work. In any case you also need github integration set up with the user whose auth token creates the release for commit pulling to work. I just created a bot user, configured github permissions for that user, and then created a user api key for the bot and used that in our deploy script.

**Comment by doomietrue** [comment]
Also interested if it's possible to deploy a release with a webhook ? For what deploy token is used then for ?

**Comment by BYK** [comment]
I think this is no longer an option and the docs are clearer: https://docs.sentry.io/product/releases/#create-release

Ping us back here if you think we still can improve these docs or the flow.
