### ISSUE TITLE
Multiple values for an HTTP Header

### ISSUE THREAD

**Issue by ColinHebert** [getsentry/sentry#891]
HTTP supports the repetition of a header, allowing to set multiple values for one specific header. (cf. http://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable)

Currently the `raven-java` client tries to send the value of each header as an array (my bad...), mostly because Java supports retrieving each value for the header separately.

Some would argue that it's a bit low level and HTTP specifies that those values can be concatenated with comas (cf. http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2).

So my question is, which one is right? Should the values be concatenated as it's what the server will use, or should it be kept separated as it's what was send by the user?

Obviously it would be easy to carry on with what we currently have (as single string meaning everything should be concatenated), but it would be better if it was a conscious choice between interpreting headers as "what the server understand" and "what the user sent".

Related to kencochrane/raven-java#56

**Comment by dcramer** [comment]
Closing this out and going to just say it'll be fixed as part of GH-1092 instead of the current protocol.
