### ISSUE TITLE
Issue Owner: can we use more advanced globbing?

### ISSUE THREAD

**Issue by richard-lopes** [getsentry/sentry#8947]
Hello,

When settings issue owners we either can choose a path to a source file or an URL. 
In our case we can only rely on URL.
We have teams owning sections of the product and URLs looks like like so:
- https://domain.com/tasks/blabla
- https://domain.com/<guid>/tasks/blabla
To attribute to the team owning the `/tasks` the errors happening in its section, with URLs like those, could we use something like `URL: **/tasks/*` ?

**Comment by mattrobenolt** [comment]
You could do `url:*/tasks/*` we don't support a `**` since `*` just means _anything_.

Our syntax directly maps to the syntax in Python's [`fmnatch`](https://docs.python.org/2/library/fnmatch.html)

So `*/tasks/*` translates into the regular expression `.*/tasks/.*`

**Comment by richard-lopes** [comment]
Excellent. In the documentation all the examples use absolute URLs with the domain prefixing the search.
Thanks. I will try.
