### ISSUE TITLE
Upgrading from 8.22.0 > 9 - sequences / increments on a few tables missing

### ISSUE THREAD

**Issue by vincentbriglia** [getsentry/sentry#8954]
Hi, 

we tried upgrading Sentry from 8.22.0 > 9 using the onbuild Docker images (we're running sentry in rancher)

we bumped into a few issues that all tracked back to fixing the many problems in exactly the same way

issues encountered: we couldn't run the migrations, we couldn't revert migrations, we couldn't add users, we couldn't add teams, we couldn't assign members to teams. 

we identified the problem, which was a strange one for us: the auto increment sequence on the migration id for the django south migration system table was missing, therefore it HAD run the migrations, but had been unable to insert the migration id's

at this point the database had 121 autoincrement indexes

once we figured that out, we added the sequence manually, then we rolled-back to a specific migration, and then re-ran the migrations. 

then we couldn't add new teams, or new members to the team, so we needed to add a sequence because of this error: 
```
7/6/2018 10:30:51 AMIntegrityError: IntegrityError('null value in column "id" violates not-null constraint\nDETAIL:  Failing row contains (null, 11, 8, t).\n',)
7/6/2018 10:30:51 AMSQL: INSERT INTO "sentry_organizationmember_teams" ("team_id", "organizationmember_id", "is_active") VALUES (%s, %s, %s) RETURNING "sentry_organizationmember_teams"."id"
```

at this point the database has 123 autoincrement indexes, it is difficult to know whether this is the right amount of sequence indexes, but perhaps someone could shed a light on whether this is the right amount.

while we fixed this manually, it is a strange bug, specifically that the sequence on the system migration table was missing. 

We can't reproduce this

**Comment by pablolibo** [comment]
the same error, thanks for reporting

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
