### ISSUE TITLE
Getting the error 'RavenConfigError: Missing eventId' with user feedback and whitelistUrls

### ISSUE THREAD

**Issue by nicholasgriffinVF** [getsentry/sentry#8975]
Hey,

I'm testing a configuration with user feedback, however, I have come across an error while doing this, which appears as:

'RavenConfigError: Missing eventId'

The strange thing is that if I remove the whitelistUrls section from my config (I have also tried removing the urls that I have in these settings around), I no longer get this error.

I'm using version 3.26.2 in a JavaScript configuration with the following:

`Raven.config('<DSN>', {
                whitelistUrls: [
                    '127.0.0.1',
                    'localhost',
                    'domain.co.uk',
                    'domain2.co.uk',
                    '<anonymous>'
                ],
                environment: environmentName,
                release: releaseName,
                tags: {
                    company_name: mainCompanyName,
                    company_id: mainCompanyAPI
                }
            }).install(function (err) {
                console.error(err);
                process.exit(1);
            });`

I'm posting the error with the following:

`var handleSFError = function handleSFError(error, showSentryDialog) {
    console.error(error);

    Raven.captureException(error);

    if (showSentryDialog) {
        if (typeof jQuery !== 'undefined') {
            jQuery('#reportErrorModal').modal('show');
        } else {
            Raven.showReportDialog()
        }
    }
};`

If jQuery is enabled then it will show a modal with a button that does the 'Raven.showReportDialog()' onclick.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
