### ISSUE TITLE
Releases api is using a case sensitive check on the repo name

### ISSUE THREAD

**Issue by xt0rted** [getsentry/sentry#8976]
I'm using the hosted version at sentry.io and added my repository called `myorg/project`.

I'm now deploying from AppVeyor and grabbing the repo name that they have configured to create my release (`myorg/Project` which is the same casing as on GitHub).

The issue I'm running into is the api is returning a 400 error saying
>Invalid repository names: myorg/Project

If I try to add a new repo on the site named `myorg/Project` it fails saying a repo with that name already exists since it's doing a case insensitive check. It seems like a bug that the releases api is doing a case sensitive check on this value.

I'm going to try deleting the repo and re-adding it with the correct casing. It's queued for deletion so once that's done I can resume testing this.

**Comment by xt0rted** [comment]
Once the repo was deleted I was able to re-add it using the same casing that AppVeyor is using and the create release calls started succeeding.

**Comment by brendanlong** [comment]
I ran into this too, and hit an additional problem: I renamed the repo in GitHub but deleting the repo from Sentry so I can re-add it takes forever. I've already been waiting half an hour for this to finish..

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
