### ISSUE TITLE
Feature Request: Team Defaults

### ISSUE THREAD

**Issue by itscharlieb** [getsentry/sentry#8984]
Would love a feature to have team-wide defaults so that I don't need to configure the same settings for every project my team owns. We own 20-30 projects. I want to be able to set team defaults for basically all project-settings - auto-resolve duration, integration urls, etc. In the current state of things, I manually set the same settings across all 30 projects which is tedious and error prone.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
