### ISSUE TITLE
Documentation fixes: use --config rather than CONF

### ISSUE THREAD

**Issue by gforcada** [getsentry/sentry#9067]
Hi,

while installing sentry 9 following these instructions: https://docs.sentry.io/server/installation/python/ I was getting an error that the configuration was wrong because I was running the first upgrade as said on the configuration:

```
CONF=config/ sentry upgrade
```

While it finally worked when I changed it to:

```
sentry --conf config/ upgrade
```

Is the ``CONF`` environment variable completely deprecated? :thinking: it should be updated across the documentation then.

**Comment by BYK** [comment]
We don't even offer this method now and I think `SENTRY_ENVIRONMENT` is what you were looking for: https://develop.sentry.dev/config/#general
