### ISSUE TITLE
Problem with custom UA clients 

### ISSUE THREAD

**Issue by alexey-ku77** [getsentry/sentry#9068]
Currently sentry specify unknown browsers with common word "Other".
Which group together different kind of issues.
And makes it not possible to find errors made by Android app which uses custom version of UA string. Or when bots or crawlers requesting some old page or page with obsolete parameters.

Sentry is missing for an toggleable option to use original `User-Agent` value instead of common word "Other".

- The version of Sentry you're using
`Sentry 8.22.0`

- Whether you're using Docker or another installation method
`Plain installation(No docker) with virtualenv`

- Include a stacktrace or other logs when relevant
`No stacktrace available`

- Include a redacted version of your configuration when relevant
`Not relevant`

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
