### ISSUE TITLE
Default environment not used as default filter

### ISSUE THREAD

**Issue by kanadaj** [getsentry/sentry#9089]
Using Sentry 9.0.0 on Docker, I'm experiencing an issue with the default environment setting where the default is set but its value is not actually used as the default filter.

![image](https://user-images.githubusercontent.com/3247357/42878899-9741effa-8a86-11e8-85f8-aef1f8cb89fc.png)

![image](https://user-images.githubusercontent.com/3247357/42878905-9bb59c3a-8a86-11e8-840f-1f2a8b8a1973.png)

The default issue list shows all errors, even the ones from Development.

**Comment by JakeHedman** [comment]
Same here, the environment dropdown is not even showing.

**Comment by lynnagara** [comment]
Is this still happening? The dropdown was recently turned on for all users (not just early adopters)

**Comment by longtengfei2016** [comment]
the environment dropdown is still not showing when use on-premise

**Comment by markstory** [comment]
@longtengfei2016 did you update to the latest master inside your container? Doing so is necessary to get the fixed that have shipped to sentry.io.

**Comment by d-luk** [comment]
Any progress on this? I still have this problem. It shows "All environments" by default, even though Production is set to be the default in the project settings.

**Comment by kanadaj** [comment]
This works for me now when building sentry from git instead of the release version

**Comment by markstory** [comment]
@kanadaj Thanks for verifying that. Going to close this then as the fix will be part of the next major release.
