### ISSUE TITLE
Feature Request: Ability to add runbooks

### ISSUE THREAD

**Issue by ThomasWunderlich** [getsentry/sentry#9122]
## Feature Request: Support adding external runbooks to an issue

###User Story
I would like to be able to add a link to either a runbook or a dashboard so that anyone investigating an alert knows what they should be doing to resolve the error.

### Future State
Plugins for alerting systems such as Pagerduty should include the runbook link if they can support it

### Work involved
* DB table/field
* Front-end workflow to add a runbook link
* backend CRUD code for runbook link

I'm willing to do the actual coding. I would probably need some help from the product and/or ui teams if accepted.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
