### ISSUE TITLE
After changing my team and project ID most of the issues are gone from the issue overview

### ISSUE THREAD

**Issue by belidzs** [getsentry/sentry#9142]
I'm using the SaaS version of sentry.io. 

After I have changed the team- and the project ID, most of the previously reported issues are gone from the issue overview.

I have digged out some notification e-mails from the past to make sure I can still use the permalinks to open the old issues and sure enough, they are there.

These issues shouldn't be filtered out by the default `Unresolved issues` view since they were never marked resolved.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by belidzs** [comment]
That's some top notch issue management there

**Comment by BYK** [comment]
@belidzs if you are still having this issue and using sentry.io I recommend reaching out to [our support](https://sentry.io/contact/support/).

We are working on improving the issues view too but no promises on when these improvements will be available.
