### ISSUE TITLE
JIRA/BitBucket Server Support

### ISSUE THREAD

**Issue by l0nax** [getsentry/sentry#9148]
Hey,
Is there any possibility to use the Sentry JIRA and BitBucket Plugin with the Self-Hosted Instances?

How can I change/ configure the URL's and how do I install the Plugins to the JIRA and BitBucket servers?

**Comment by levisbakalinsky** [comment]
Not possible without altering code.

**Comment by l0nax** [comment]
And at witch place of the Code can I edit the Base URLs of JIRA and
BitBucket?

Levis Bakalinsky <notifications@github.com> schrieb am Di., 24. Juli 2018,
20:51:

**Comment by mehcode** [comment]
Are there any plans to support self-hosted BitBucket and Jira? Sentry is an otherwise awesome platform and I'd love to use it to its full extent.

**Comment by garron** [comment]
The legacy JIRA plugin works with self-hosted JIRA. Please don't remove support for it there!

**Comment by markstory** [comment]
@garron Building a new organization-wide JIRA server integration is something we would do before removing the old JIRA-server plugin.

**Comment by markstory** [comment]
A new integration for jira-server has been released. The [docs can be found here](https://docs.sentry.io/workflow/integrations/global-integrations/jira-server/).

**Comment by ArcticSnowman** [comment]
Totally think this is a must have for serious use in any enterprise setup..

**Comment by markstory** [comment]
@ArcticSnowman Are you referring to bitbucket server? As the Jira-server integration is done.

**Comment by l0nax** [comment]
@markstory I think @ArcticSnowman means the BitBucket Server

**Comment by markstory** [comment]
Closing as this issue covers two integrations (one of which is done). Future discussion on bitbucket server can take place on #8372
