### ISSUE TITLE
Can't configure Slack integration on project level

### ISSUE THREAD

**Issue by leukanos** [getsentry/sentry#9151]
When I try to edit Slack integration configuration on project level I can see only information `No Integrations Enabled` even if this integration is enabled on Organisation level (see screenshots)
![screen shot 2018-07-23 at 16 57 53](https://user-images.githubusercontent.com/5787083/43084816-b4b50510-8e99-11e8-85ba-cdc20d81e655.png)

![screen shot 2018-07-23 at 16 57 30](https://user-images.githubusercontent.com/5787083/43084717-86e4dfb6-8e99-11e8-97ec-770d6f645a9a.png)

Also not that I can see only the `Install` button on already installed Slack integration.
This integration has been installed and configured before and currently, it is working ok. The only issue is that I cannot change anything related to Slack integration.

**Comment by holms** [comment]
I've installed slack workspace too, and I don't get anything from projects to that channel at all.

**Comment by leukanos** [comment]
Solved. Integration is working as expected. To configure your alerts go to `Alerts` -> `Rules` in project settings.
