### ISSUE TITLE
Client ip is not show in sentry 9

### ISSUE THREAD

**Issue by JinmingHao** [getsentry/sentry#9172]
I'm using sentry on-premise version，raven version is 6.2.1 and sentry version is 9.0.0， with new sentry，client ip is gone，I don't know why。

![image](https://user-images.githubusercontent.com/38746443/43116004-3e4d55ea-8f38-11e8-9a81-2eb85f9f6cbd.png)

and in old version：

![image](https://user-images.githubusercontent.com/38746443/43116144-dcf944ec-8f38-11e8-8cd4-ee125b551076.png)

and config is

![image](https://user-images.githubusercontent.com/38746443/43117405-33a3c212-8f3f-11e8-928a-5636b6f286d6.png)

**Comment by jaylinski** [comment]
Did you check global and project settings?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
