### ISSUE TITLE
Link from email address verification does not work - page does not exist

### ISSUE THREAD

**Issue by ProxiBlue** [getsentry/sentry#9204]
- The version of Sentry you're using
9.0.0
- Whether you're using Docker or another installation method
Official self hosted docker

When using link in email verification, the result is that page does not exist:

![selection_501](https://user-images.githubusercontent.com/4994260/43238669-bc312baa-90c1-11e8-86b3-1e0eab69dce9.png)

results in:

![selection_502](https://user-images.githubusercontent.com/4994260/43238681-cac8e4dc-90c1-11e8-81e8-4043ebcb9e76.png)

Actual link:

/sentry/account/confirm-email/1/Bjs9zdhmsIWRFFkZVmQqRQ0O3qqmFYUd/

**Comment by ProxiBlue** [comment]
Ok, seems this is a setup issue. Removing the preceding /sentry/ from the link fixes the url.

**Comment by ProxiBlue** [comment]
Yes, this was a configuration issue. I had placed an nginx proxy in front of setup to allow https with ssl cert. This then internally loads the /sentry/ url, so in sentry admin, I remove dthe /sentry/ path from base url, which then fixed the issue.

**Comment by rangercyh** [comment]
how do you solve the problem? I meet the same question. @ProxiBlue

**Comment by ProxiBlue** [comment]
Sorry, I don't know.
