### ISSUE TITLE
Alerts should support Google Chat WebHooks

### ISSUE THREAD

**Issue by innovia** [getsentry/sentry#9206]
## General Support
google chat supports incoming webhooks that need a specific formatting

the minimum for a plain text message is ```json {"text": "message here"}```

https://developers.google.com/hangouts/chat/reference/message-formats/cards

please provide this support - or at least allow customizing the body of a message to be sent via webhooks.

If you're looking for general support, please utilize our [community forum](https://forum.sentry.io/) rather than GitHub Issues.

## Reporting Bugs

When reporting bugs, include details about your configuration, such as:

- The version of Sentry you're using
- Whether you're using Docker or another installation method
- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration when relevant

**Comment by serafimpinto** [comment]
Hi guys

When this will be added? Really struggling with this 😕

**Comment by innovia** [comment]
@serafimpinto  i don't think they will implement it, i ended up (and no longer have the code access) running my own webhook that enable this support

**Comment by jweslley** [comment]
Hi guys, I created this plugin https://github.com/jweslley/sentry-googlechat

It was tested with Sentry 10.

**Comment by Evilbits** [comment]
Any updates on a native implementation of this?

**Comment by grecstar** [comment]
+1

**Comment by BYK** [comment]
@Evilbits we support generic webhooks for alerts now: https://docs.sentry.io/product/integrations/integration-platform/webhooks/

Would that suffice?

**Comment by defigor** [comment]
> Hi guys, I created this plugin https://github.com/jweslley/sentry-googlechat
> 
> It was tested with Sentry 10.

@jweslley : by any change does your plugin works for the cloud Sentry instance? How to install it without a server?

**Comment by defigor** [comment]
> @Evilbits we support generic webhooks for alerts now: https://docs.sentry.io/product/integrations/integration-platform/webhooks/
> 
> Would that suffice?

@BYK : we did setup a webhook (internal integration) with google chat, however every message which is being sent to this webhook URL ends with 400 HTTP status error code and we don't have any visibility what the error message it to troubleshoot.
So it doesn't really work out of the box. Any assistance on how to setup it up would be super useful, thanks in advance.

**Comment by jweslley** [comment]
> > Hi guys, I created this plugin https://github.com/jweslley/sentry-googlechat
> > It was tested with Sentry 10.
> 
> @jweslley : by any change does your plugin works for the cloud Sentry instance? How to install it without a server?

@defigor You need a sentry instance/server to install this plugin. This is the way!

**Comment by BYK** [comment]
>@BYK : we did setup a webhook (internal integration) with google chat, however every message which is being sent to this webhook URL ends with 400 HTTP status error code and we don't have any visibility what the error message it to troubleshoot.
So it doesn't really work out of the box. Any assistance on how to setup it up would be super useful, thanks in advance.

@defigor sorry I missed your message earlier. Without seeing more details from the webhook, it is very hard to suggest anything. Also for these kind of inquiries, you'd have more luck using [the forum](https://forum.sentry.io).

**Comment by defigor** [comment]
@BYK : I'm happy to provide an example, would it help?
The same question was already asked on the forum: https://forum.sentry.io/t/google-chat-webhooks-support/8037 but no response from the Sentry team... It seems that this one is monitored much better than the forum.

**Comment by BYK** [comment]
>The same question was already asked on the forum: forum.sentry.io/t/google-chat-webhooks-support/8037 but no response from the Sentry team...

It's been 2 years since that question was asked 🙂 We monitor both channels.

>@BYK : I'm happy to provide an example, would it help?

I'm not looking for an example. When you get a `400` response from your Sentry instance, it should produce more detailed logs on the console (or wherever you are logging into). Looking at those logs would help us (you and us here 🙂) to diagnose the issue.

**Comment by hatiboy** [comment]
Hello guys. Anybody help us ?

**Comment by BYK** [comment]
Sending back to @getsentry/ecosystem for a real triage. @manuzope feel free to close this if we don't plan to get to this at all.

**Comment by manuzope** [comment]
@jonesphillip can you take a look?

**Comment by webmozart** [comment]
We would love to move to Google Chat but this is unfortunately holding us back. Any updates?

**Comment by ericnewcomer** [comment]
Seems the team should at least give some closure here. We also recently switched to Google spaces, but were surprised to find no support for it here (or some way to manipulate a generic payload for a webhook alert).

**Comment by ceorourke** [comment]
Hey everyone, we don't have any plans to build a Google Chat integration. The way forward as BYK suggested earlier is to build an [internal integration](https://docs.sentry.io/product/integrations/integration-platform/). We now have a fully fleshed out example app here you can clone or fork https://github.com/getsentry/integration-platform-example to get started.
