### ISSUE TITLE
Sentry 9.0 . Send event from sentry java logback client is being redirected to the login.

### ISSUE THREAD

**Issue by onebuckrule** [getsentry/sentry#9210]
127.0.0.1 - - [26/Jul/2018:16:20:15 +0000] "POST /sentry//api/6/store/ HTTP/1.0" 302 476 "https://test.localapp.com/" "sentry-java/1.7.5-dccb1"
127.0.0.1 - - [26/Jul/2018:16:20:15 +0000] "POST /sentry//api/6/store/ HTTP/1.0" 302 476 "https://test.localapp.com/" "sentry-java/1.7.5-dccb1"
127.0.0.1 - - [26/Jul/2018:16:20:16 +0000] "GET /auth/login/ HTTP/1.0" 200 9088 "https://test.localapp.com/" "Java/1.8.0_102"
127.0.0.1 - - [26/Jul/2018:16:20:16 +0000] "GET /auth/login/ HTTP/1.0" 200 9088 "https://test.localapp.com/" "Java/1.8.0_102"

**Comment by mattrobenolt** [comment]
It looks like your DSN is misconfigured or something. It's POSTing to the wrong endpoint.

You have `/sentry//api/6/store/` in your logs. This should be `/api/6/store/`.
