### ISSUE TITLE
Unable to create a SubTask within Jira integration (Parent field not shown)

### ISSUE THREAD

**Issue by schinckel** [getsentry/sentry#9227]
This is using the hosted version of Sentry.

We have an integration with our Jira instance. 

When you attempt to create a SubTask from a Sentry event, it requires a Parent, but this field is not shown in the dialog.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

**Comment by flache** [comment]
I ran into the same issue, it would be nice if that can be resolved by adding an extra field for the parent issue id of the subtask
