### ISSUE TITLE
Project settings page url overlaps with organisation settings url

### ISSUE THREAD

**Issue by execmd** [getsentry/sentry#9229]
- **Sentry 9.0.0**
- **Docker**

Hello,
I have a project named **auth** and when I want to open project settings page I hit organisation authorization settings page.
Organisation name: **_A_**
Project name: **_C_**

At now URL looks like:
Project url **http://xxx/A/C/**
Project settings url **http://xxx/settings/A/C/**
So when **C** (project name) is one of 
- projects
- teams
- members
- auth
- audit-Log
- rate-limits
- repositories

we hit incorrect page.

Maybe sentry organisation auth settings page url can be changed to smth not widely used in names?

**Comment by billyvg** [comment]
@execmd These slugs should be reserved now, see: https://github.com/getsentry/sentry/blob/eaf0ba1403da26ddfd77f8cad40de46ef70a2b21/src/sentry/constants.py#L94

Sorry for any issues you've had, please contact support@sentry.io if you're still having issues.
