### ISSUE TITLE
Installation error(Interrupted for some reason)

### ISSUE THREAD

**Issue by psjwohoo** [getsentry/sentry#9252]
![qqq](https://user-images.githubusercontent.com/31725045/43449823-ffc1997e-94e3-11e8-9508-1e15cac0de77.png)

I didn't create a super user for some reason, so what should I do? I want to know how to uninstall (Linux platform).

**Comment by psjwohoo** [comment]
Or Make up for the way

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
