### ISSUE TITLE
Stack Trace => Source Map mapping incorrect

### ISSUE THREAD

**Issue by alekbarszczewski** [getsentry/sentry#9283]
Generally source map feature works for me on sentry.io, however stack trace is not mapped correctly. For example on chrome I see this:

![airchitect](https://user-images.githubusercontent.com/2742373/43586877-15673d8e-9669-11e8-8c36-c56016010b7d.png)

And when I click that error code in vue component is highlighted correctly which means that chrome parses source map correctly:

<img width="1232" alt="menubar_and_airchitect" src="https://user-images.githubusercontent.com/2742373/43586894-2198e8dc-9669-11e8-95a7-4e4f5c5d5bc5.png">

On sentry however I see this: (as you can see it does not refer to TestErrors.vue component code but instead to some "file" ./src/pages/TestErrors.vue?06aa

![typeerror__cannot_set_property__xyz__of_undefined](https://user-images.githubusercontent.com/2742373/43587031-86410e36-9669-11e8-9469-31f1ba7f4bfc.png)

And here is what sentry shows when "minified" is clicked:

![typeerror__cannot_set_property__xyz__of_undefined](https://user-images.githubusercontent.com/2742373/43586967-559283b4-9669-11e8-825c-ae9345baf1ed.png)

I checked with some sourcemap visualization tool and here is how it looks like:

![source-map-visualization](https://user-images.githubusercontent.com/2742373/43586990-64cc880c-9669-11e8-8187-b94500c65307.png)

Why sentry is loading TestErrors.vue?06aa instead of TestErrors.vue? What is exactly TestErrors.vue?06aa? Why it works in chrome and not with sentry?

 I use source maps hosted next to their original files, I also ensured that the map file downloaded by sentry matches original file.

**Comment by alekbarszczewski** [comment]
Guys any idea what might be wrong? I would like to use Sentry in prod but there is no point if I am not able to track errors correctly...

**Comment by billyvg** [comment]
@alekbarszczewski Do you have a reproduction repo handy that I can take a look at?

**Comment by benvinegar** [comment]
I'm confused. Your visualization tool appears to have output the same result for the stack frame with `TestErrors.vue?06aa`. Ours just snips the context because we can't store the entire lines, which is thousands of characters.

Re: `TestErrors.vue?06aa` – in your screenshot at the top, Chrome generates that same value, so again this is not the case that Sentry is generating that value.

Ah – I see it looks like some frames are "missing" to you. Did you click "Full" frames to make sure we haven't attributed some of these to Vue? We suppress library frames by default:

![image](https://user-images.githubusercontent.com/2153/46264385-15ef1880-c4d1-11e8-89fe-f23e05f94d98.png)

**Comment by alekbarszczewski** [comment]
Hmm, you are right, after clicking on "full" and expanding first stack entry I see correct code that caused the error:

<img width="1085" alt="typeerror__cannot_set_property__xyz__of_undefined" src="https://user-images.githubusercontent.com/2742373/46273372-88094100-c555-11e8-9624-c7ac3d8d3df9.png">

Strange,  I could have sworn that before there wasn't such entry there... Anyway, thanks, it works as expected now :)

**Comment by benvinegar** [comment]
^I'm a little concerned that we tagged that as `in_app=False` (meaning, not your application code). That might be something worth exploring.

cc @kamilogorek

**Comment by kamilogorek** [comment]
@benvinegar @alekbarszczewski this is a very odd issue, which seems to be broken on the webpack/vue side.

When you investigate stack trace of the error, you can see that first two frames, despite coming from the same file, have different absolute paths:

first: `webpack:///src/TestErrors.vue'`
second: '`webpack:///./src/TestErrors.vue?da2d'`

In addition to this, when you dig into source maps, it appears that `TestErrors` file is mapped multiple times, where it definitely shouldn't.

```json
"sources": [
  "webpack:///webpack/bootstrap",
  "webpack:///./src/TestErrors.vue?6f0c",
  "webpack:///src/TestErrors.vue",
  "webpack:///./src/TestErrors.vue",
  "webpack:///./src/TestErrors.vue?da2d",
  "webpack:///./src/App.vue",
  "webpack:///./src/App.vue?d096",
  "webpack:///./src/app.js"
]
```

We cannot easily fix this, as `webpack:///<anything other than . or ~>` is a reserved pattern, which we use to detect internal webpack frames, see: https://github.com/getsentry/sentry/blob/1976f480c9fbe46515f2c3a61558fdc691bfc5f3/src/sentry/lang/javascript/processor.py#L667-L712

**Comment by benvinegar** [comment]
Thanks for investigating @kamilogorek.
