### ISSUE TITLE
Feature: support ReportingObserver to report used deprecated APIs

### ISSUE THREAD

**Issue by laukstein** [getsentry/sentry#9285]
Chrome 69 will land ReportingObserver support that can be used to report used deprecated APIs.
Announcement https://developers.google.com/web/updates/2018/07/reportingobserver
Spec https://w3c.github.io/reporting/#observers

Allow to turn on/off this feature in Sentry settings.

**Comment by renchap** [comment]
Related ticket for Raven JS: https://github.com/getsentry/sentry-javascript/issues/1450

**Comment by renchap** [comment]
And it has been merged in https://github.com/getsentry/sentry-javascript/pull/1525 (ping @kamilogorek) 🎉

**Comment by laukstein** [comment]
@renchap, will this be enabled by default?

**Comment by HazAT** [comment]
@laukstein yes, currently it's on by default.

**Comment by kamilogorek** [comment]
With an ability to specify which types of reports you want to send of course :)

**Comment by laukstein** [comment]
@kamilogorek, any documentation for it?

**Comment by kamilogorek** [comment]
We're working on docs as we speak. It'll be:

```js
import * as Sentry from '@sentry/browser';

Sentry.init({
  dsn: '___PUBLIC_DSN___',
  integrations (defaultIntegrations) {
    // remove default ReportingObserver integration
    const customIntegrations = defaultIntegrations.filter((integration) => integration.name !== 'ReportingObserver');

    // Add new one with custom configuration
    return [...customIntegrations, new Sentry.Integrations.ReportingObserver({
      type: ['deprecation']
    )]
  }
});
```

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
