### ISSUE TITLE
Filter sensitive data in exception message

### ISSUE THREAD

**Issue by tarzan** [getsentry/sentry#9309]
I got sensitive data as part of the stacktrace in my app that is not being redacted.

This is a duplicate of #4666 which got closed without any further info of how to manage/fix this. Are you fixing this or have a better solution?

We're running sentry-elixir 6.4.1 on our elixir 1.6.3 app.

**Comment by BYK** [comment]
I think this might be useful: https://docs.sentry.io/platforms/elixir/data-management/sensitive-data/

Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
