### ISSUE TITLE
Migration from 8.22 o 9.0 is erroring

### ISSUE THREAD

**Issue by ys** [getsentry/sentry#9326]
What I am seeing is that the index suffix when running migration is different at every run.
Unsure how it is calculated.

but I get

```
FATAL ERROR - The following SQL query failed: DROP INDEX sentry_eventtag_project_id_6b8795b99476f883
```

but I have it under `sentry_eventtag_project_id_642fc074ff498345`

Unsure what I need to do.

Is it me doing something wrong?

I am running `sentry upgrade` on Heroku

**Comment by stayallive** [comment]
Not sure what is the recommended way but I commented out the migration step to drop the index (the file is in the error stacktrace) and dropped the matching index myself after which the migration can continue. 

However in my case I was coming from MySQL which caused the incorrect index names, but that is a way to move forward with the migrations... not sure if there is a better fix :)

**Comment by dcherman** [comment]
https://github.com/getsentry/sentry/issues/5229#issuecomment-377364078

The names of indexes are non-deterministic unless you've set `PYTHONHASHSHEED` to a constant value from the get-go.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
