### ISSUE TITLE
Node sourcemaps are incorrect if error occurs on line 1

### ISSUE THREAD

**Issue by aaronjensen** [getsentry/sentry#9329]
See: https://github.com/evanw/node-source-map-support/issues/36

It seems that node injects some code into the beginning of line one. If you have minified node code, chances are very good the error occurs on line 1 which makes the sourcemaps incorrect.

Any idea where this could be fixed?

Thanks!

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
