### ISSUE TITLE
Cannot read property '_avast_submit' of undefined

### ISSUE THREAD

**Issue by aniruddhashevle** [getsentry/sentry#9331]
We're are using Sentry for our React App and faced this issue. Don't know where exactly this issue is coming from? This variable '_avast_submit' (or related named variable) is not at all used in either frontend or backend. In the screenshot it's mentioned anonymous.

This issue had occurred for the user's who had used our React App, are from Mac and Windows OS specifically using Chrome browser.

![screen shot 2018-08-07 at 12 22 46 pm](https://user-images.githubusercontent.com/20954198/43760200-08260fb8-9a3f-11e8-91f1-7e363cfb09f8.png)

**Comment by stayallive** [comment]
Highly likely related to the Avast (antivirus) browser extension.

Unfortunately when tracking (all) JS errors, also errors originating from browser extensions could reported to Sentry.

**Comment by billyvg** [comment]
@stayallive is correct, this is due to an Avast extension.

**Comment by NNSTH** [comment]
We've faced this issue using NewRelic, it's not related to React.
