### ISSUE TITLE
CSP-Report causes Cross-Origin Read Blocking (CORB)

### ISSUE THREAD

**Issue by svewag** [getsentry/sentry#9336]
Hi folks,

we are using a Sentry v9.0.0. on premise. As with the newly released Chrome 68 we are facing some minor issue that the response of the CSP-Reports includes the HTTP-Header `Content-Type: text/html`.

```
HTTP/1.1 201 CREATED
Content-Length: 0
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Content-Language: en
Expires: Wed, 08 Aug 2018 15:09:41 GMT
Vary: Accept-Language, Cookie
Last-Modified: Wed, 08 Aug 2018 15:09:41 GMT
Cache-Control: max-age=0
X-Frame-Options: deny
Content-Type: text/html; charset=utf-8
```

See [here](https://www.chromium.org/Home/chromium-security/corb-for-developers) for the announcement of the Chromium team towards CORB.

As we are not evaluating the actually empty response response, this is not a problem at the moment.

**Comment by mattrobenolt** [comment]
What should we actually be returning here then? There is no body at all. I guess omitting Content-Type entirely?

**Comment by svewag** [comment]
If I understand it correctly there are multiple options.

1. set `Content-Type: application/javascript`
1. remove the `X-Content-Type-Options: nosniff`
1. set `Access-Control-Allow-Origin: *`

It sound like that the first option is the one that makes sense. As long as the body is empty, returning `Content-Type: application/javascript` might be another solution.

Here is a good explanation: https://youtu.be/dBuykrdhK-A?t=23m11s

**Comment by svewag** [comment]
Here is another video talking about CORB

https://youtu.be/_5rX6pt0A_k

**Comment by reedloden** [comment]
How about #9661 then?

**Comment by svewag** [comment]
👍 looking forward to test it with the next release. Thank you very much.
