### ISSUE TITLE
Source code was not found for foo.js

### ISSUE THREAD

**Issue by adamreisnz** [getsentry/sentry#9343]
We are using Sentry in our Node application without any minified javascript or sourcemaps, yet I get the following warning in Sentry:

![image](https://user-images.githubusercontent.com/490562/44006358-6d9a581c-9ed7-11e8-8a55-740b7c5b437e.png)

This doesn't make sense, as we don't use sourcemaps nor minified code. The file exists on the file system and is fine.

Using Raven ^2.6.2.

**Comment by benvinegar** [comment]
Sentry doesn't have access to your local filesystem. But it will try to see if the file exists as an uploaded artifact. If it can't find it, it won't be able to show source code context, and complains.

It's questionable whether this should be an "error" and not a "warning", but Sentry doesn't have a concept of that today.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
