### ISSUE TITLE
Emails have very little contrast and very tiny print.

### ISSUE THREAD

**Issue by mark0978** [getsentry/sentry#9372]
## Reporting Bugs

We've just upgraded our sentry installation and gone from usable, easy to read emails to emails with tiny, tiny text.

![image](https://user-images.githubusercontent.com/106150/44121356-4cb37a20-9fe5-11e8-95fa-f60b78a3a26b.png)

Is there some reason the message has to be shrunk to use a tiny portion of the screen and written in a font that is soo faint and so hard to read?

This is what they messages used to look like, where the text was larger, and much further away from the background color.  

![image](https://user-images.githubusercontent.com/106150/44121501-eac66d80-9fe5-11e8-9154-b7edc3dd54be.png)

Maybe it is more stylish, but it is a lot less usable with this color scheme.

**Comment by benvinegar** [comment]
cc @ckj

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
