### ISSUE TITLE
Feature Request: Allow more detailed/accurate stream filtering

### ISSUE THREAD

**Issue by bmconklin** [getsentry/sentry#938]
Being able to filter the stream would be helpful in identifying what you want to see.

For instance, setting the date ("Since Month Day") to a week ago and an hour ago display the same amount of alerts as long as there is at least one alert in both time frames. It would be preferable to see only the alerts that occurred within the set time frame, even when an event with the same tags occurred outside the set time frame.

Also, an option to not display resolved issues even after a regression occurs would be helpful. So if I resolve a tag containing a number of alerts, then another alert comes up with the same tag, I would like to see just the new one, not the total amount. As the system works now, it seems like I have to remove the event data to get this effect.

**Comment by joranbeasley** [comment]
I agree maybe even just a does not contain type keyword for search

**Comment by andybak** [comment]
@joranbeasley has it - it's seems like it should be a common use case to filter by "anything except spiders" or "any user agent except bing" (especially as bing seems to love hitting non-existent urls)

**Comment by dbpfindexp** [comment]
Not sure if this is along the same lines or if I'm missing the feature but would be great to add inbound filters to drop or just keep a simple counter of certain things in sentry you are not interested in via regex matches.  We have some exceptions we want to keep in our logs but don't want sentry to track them because they are just to noisy.

**Comment by dcramer** [comment]
I'm going to close this out as the ticket isn't overly accurate anymore.

@dbpfindexp agreed on expanding inbound filters. I doubt we'll do regex (its very expensive), but at least allowing you to do rule-like conditions (similar to our alerts) is our goal.
