### ISSUE TITLE
Feature Request: Faceted search

### ISSUE THREAD

**Issue by gregmac** [getsentry/sentry#942]
We have a few issues where there are hundreds of occurrences (especially in our "generic error" handler that includes several access denied errors that we don't actually want to see). On the right sidebar, it shows all the tags with the number of occurrences: right now, clicking on the tag takes you to all events with those tags. 

Much more useful would be if this acted as a faceted search, showing you only the occurrences of the event you're looking at with the selected tag. 

In our case, this would allow us to narrow down only issues against a specific version or host -- the usefulness to others obviously depends on the tags added.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
