### ISSUE TITLE
Generic Icon being displayed instead of project icon

### ISSUE THREAD

**Issue by iamareebjamal** [getsentry/sentry#9422]
## Reporting Bugs

React is now using `project.platforms` instead of `project.platform` which is either empty for many old and new projects( e.g. Java projects have `platform` property set but not `platforms`) or is very generic ( e.g. Django projects have `python-django` as platform but `python` as platforms) which results in either wrong icon being displayed or generic icon being displayed. This bug was probably added in #8852 and #8864 

Either the backend should include correct platform in `platforms` array or it should be prepended in the array before being passed into props

### To reproduce:

- Create a new Project on 9.1.0dev version or open any older one

### Screenshot

![screenshot from 2018-08-18 02-47-08](https://user-images.githubusercontent.com/3874064/44289329-4c5e3480-a291-11e8-9565-d7ed5ca2bdab.png)

### Info
- The version of Sentry you're using: 9.1.0dev
- Whether you're using Docker or another installation method: From source
- Include a stacktrace or other logs when relevant: N/A
- Include a redacted version of your configuration when relevant

**Comment by billyvg** [comment]
This is now a setting inside of projects
![image](https://user-images.githubusercontent.com/79684/66156781-34ea2400-e5d7-11e9-8e38-abc191667110.png)
