### ISSUE TITLE
Feature: Display tags for each issue in the issue list

### ISSUE THREAD

**Issue by arnemart** [getsentry/sentry#9428]
Showing more info with each issue in the issues list could be very useful in order to more quickly distinguish the issues when browsing the list. Specifically, I would like to be able to select one or more tags to show up in the list next to each issue.

The use case for this in my case is for an application that runs as a collection of medium-sized microservices, where I would like to distinguish in which service an issue appeared, without having to click on it first.

Here is a mockup of how something like this could look:
![screen shot 2018-08-20 at 14 30 00](https://user-images.githubusercontent.com/662021/44340612-a7f11380-a485-11e8-8c68-0c64d36c5aba.png)

I am prepared to implement this myself and submit a PR, but I thought that I should post this issue before starting the work to try and gauge whether this feature is desired and whether the PR would be accepted.

**Comment by mattrobenolt** [comment]
My immediate concern with this is that it’s not abnormal to have hundreds or even thousands of tags. So I’m not sure how any of the UI would cater to that.

**Comment by mattrobenolt** [comment]
And also, issue groups themselves don’t have tags. Individual events have tags. So I don’t even know what values you’d show here that would make sense. Each event within a group might have a different tag value.

**Comment by arnemart** [comment]
The UI would have to be different to handle a large number of tags, but I'm certain that can be solved.

Would showing the tag value for the most recent event, or would it make more sense to show a <multiple values>-thing if the values are different?

Also, I might be going about my problem in the wrong way -- as I mentioned, my goal is to have a single dashboard for multiple small applications, and to be able to see at a glance which application caused the issue. Could there be a better way to do this?

**Comment by iamzjk** [comment]
I would love to see this feature in sentry

**Comment by benvinegar** [comment]
So, the mockup is cool, but there can be multiple tag values within an issue for a single tag name.

I understand how this works when you have a tag like "appname", which is probably distinct per issue, but it seems less useful when you have a "browser" tag.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
