### ISSUE TITLE
Source code not found despite source map files having been uploaded and linked to release

### ISSUE THREAD

**Issue by adamreisnz** [getsentry/sentry#9450]
Possibly related to #9343, but this happened in a web environment, not Node JS.

I'm getting errors that the source code was not found for my version, e.g.

```
Source code was not found for https://foo.com/bundles/lib-251b8f5.min.js 
```

However, under the release these files are present:

![image](https://user-images.githubusercontent.com/490562/44380669-c24bef80-a560-11e8-9355-e2202813495f.png)

Why is Sentry no longer detecting/finding the source code for the minified file? This used to work fine until a few weeks or months ago.

The source mapping url is `//# sourceMappingURL=lib-251b8f5.min.js.map`

Does the domain name the file is served from matter at all? We serve the same code from multiple subdomains, and I wouldn't want to have to upload the same file for each one of them.

**Comment by adamreisnz** [comment]
I ended up having to change our sentry-cli command to now include the `--url-prefix '~/bundles'` explicitly.

**Comment by au-phiware** [comment]
I am experiencing the same issue, I shall try your solution, but it's seems more of a work around broken behaviour than a solution. I think you should keep this issue open!
