### ISSUE TITLE
Slack integration OAuth Error redirect_uri mismatch

### ISSUE THREAD

**Issue by seik** [getsentry/sentry#9451]
Sentry: 9.0.0
Installation method: Docker

When trying to add slack to a workplace the OAuth process fails because the protocol gets replaced with the domain, and then the urls do not mach.

For the slack app configuration this guide was used: https://forum.sentry.io/t/how-to-configure-slack-in-your-on-prem-sentry/3463

Example:
![image](https://user-images.githubusercontent.com/9640279/44389886-52237680-a52c-11e8-96d8-a1b899e95bb8.png)

**Comment by mattrobenolt** [comment]
Sounds to me like you have `system.url-prefix` either configured incorrectly or not at all. 

Check with `$ sentry config get system.url-prefix`

In this case, you want it to be `https://sentry.dekaside.com`

**Comment by seik** [comment]
@mattrobenolt that was it, thanks!
