### ISSUE TITLE
Source code was not found

### ISSUE THREAD

**Issue by jackmatrix** [getsentry/sentry#9468]
When i receive an error report in sentry, i still cannot debug because the js code is uglyfied. Yet, i configured source mapping in my `exp.json` in order to get the code as it is in dev.

    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "xxxxxx",
            "project": "xxxxxxxx",
            "authToken": "xxxxxxxxxx"
          }
        }
      ]
    }

Without source mapping, my app is really hard (impossible) to debug in production. 

My sentry dashboard display these two following errors 

`Discarded invalid parameter 'type'`

    Source code was not found for app:///crna-entry.delta? 
    platform=ios&dev=true&minify=false`

Any solution ?

**Comment by jackmatrix** [comment]
edit: my sentry dashboard display these two following error 


`Discarded invalid parameter 'type'`

    Source code was not found for app:///crna-entry.delta? 
    platform=ios&dev=true&minify=false`

**Comment by benvinegar** [comment]
Hi there. The [sentry-expo](https://github.com/expo/sentry-expo) project is maintained by Expo, not us. I recommend opening this issue over there or asking them for feedback. (We're not familiar with the configuration or how it works.)

You could also check out Sentry's [Source Maps docs](https://docs.sentry.io/clients/javascript/sourcemaps/) to see if that helps.
