### ISSUE TITLE
SAML2 SSO KeyError: 'attribute_mapping'

### ISSUE THREAD

**Issue by alternativc** [getsentry/sentry#9483]
A keyerror is thrown when doing SAML2 sso:
sentry/auth/providers/saml2.py in build_identity at line 284
`def build_identity(self, state):
        raw_attributes = state['auth_attributes']
        attributes = {}
        # map configured provider attributes
        for key, provider_key in iteritems(self.config['attribute_mapping']):
            attributes[key] = raw_attributes.get(provider_key, [''])[0]`

However the necessary attributes exist as follows:
`state	
{
	'attribute_mapping': {
		'first_name': u'', 
		'identifier': 'NameID', 
		'last_name': u'', 
		'user_email': 'email'
	}, 
	'auth_attributes': {
		'mail': [
			'<omitted>'
		], 
		'userid': [
			'<omitted>'
		]
	}, 
	'idp': {
		'entity_id': '<omitted>', 
		'slo_url': None, 
		'sso_url': '<omitted>', 
		'x509cert': '<omitted>'
	}
}`

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
