### ISSUE TITLE
Slack Integration: OAuth Error: Invalid client_id parameter

### ISSUE THREAD

**Issue by s2h** [getsentry/sentry#9484]
## Reporting Bug

When I try to integrate with slack, it shows me "OAuth Error: Invalid client_id parameter"

- The version of Sentry you're using: Sentry 9.0.0

**Comment by halida** [comment]
same issue.

**Comment by chrisdrackett** [comment]
I'm running into this using our own install of sentry. Looking at the URL nothing is being sent for `client_id` in the query

**Comment by chrisdrackett** [comment]
found a solution here: https://github.com/getsentry/sentry/issues/9004#issuecomment-405396652

**Comment by halida** [comment]
@chrisdrackett Not working for me, raise another permission issue, bot.write.

**Comment by markstory** [comment]
Closing as #9004 covers a similar/same issue.
