### ISSUE TITLE
IP Addresses Filters

### ISSUE THREAD

**Issue by NBajanca** [getsentry/sentry#9518]
I'm using Sentry as a Service (sentry.io).

I have two IPs I want to be filtered out. I've added them in ``https://sentry.io/settings/***/***/filters/data-filters/``, but I just received 500 issues due to requests originating from one of those IPs.

I've four projects, all with the same configurations regarding IP Addresses filters, and only one is not working so there must be something more to it. 

If you guide me through configs that may be related to this issue, I'll let you know what I have in each field.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
