### ISSUE TITLE
JSON post data broken in curl snippet

### ISSUE THREAD

**Issue by peterbe** [getsentry/sentry#9519]
An error happened on my server when someone did a HTTP POST with JSON data to it. Fair enough. To reproduce it I wanted to take the `curl` command snippet and perhaps adjust the URL so as to send it to `localhost:8000` instead of the production server. 
<img width="1178" alt="screen shot 2018-08-27 at 10 08 48 am" src="https://user-images.githubusercontent.com/26739/44664423-3cf19080-a9e1-11e8-85d4-599050f67cdc.png">

But when I copy-n-paste that snippet of JSON and run it, the JSON is not valid so my local dev server throws it out because the request is invalid. 

Also, I can't use the formatted version of the JSON because it looks like this:
<img width="1389" alt="screen shot 2018-08-27 at 10 12 21 am" src="https://user-images.githubusercontent.com/26739/44664611-bb4e3280-a9e1-11e8-9b3c-4da18f10b92d.png">
That list goes on for 2-3 pages. (I manually expanded the first 3 before taking the screen shot)

I can't click to expand every single little "+" sign. 

Ideally, I'd like to have a "Copy to clipboard" button that copies the whole raw JSON into my clipboard. 

> - The version of Sentry you're using
0.8.22

**Comment by benvinegar** [comment]
I think just having a "Raw" JSON view would be sufficient, right?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
