### ISSUE TITLE
Slack Integration:  login page not showing in slack

### ISSUE THREAD

**Issue by theoscat** [getsentry/sentry#9537]
- The version of Sentry you're using => **9.0.0**
- Whether you're using Docker or another installation method => Docker

Hello,

I'm trying to setup the slack integration.
After the workspace setup and the rule setup i can see my new event going into the good slack channel:
![image](https://user-images.githubusercontent.com/18569964/44728559-1ca6fc00-aadd-11e8-93d0-1f5c83a0e9ec.png)

As soon as i click the resolve, ignore button or even the drop down list i get the following html code instead of good looking integration: 

![image](https://user-images.githubusercontent.com/18569964/44730222-bde38180-aae0-11e8-8c30-3ac54f64ebe2.png)

What am i missing ?
It seems to be a login page. Can it be a side effect of the google authentification integration in sentry ?

[EDIT]:

following this [steps](https://forum.sentry.io/t/how-to-configure-slack-in-your-on-prem-sentry/3463) i'm not seeing the html code but instead i got this:

![image](https://user-images.githubusercontent.com/18569964/44731991-b02ffb00-aae4-11e8-80d5-ce1d1abd5382.png)

If anyone can help it would be really kind.

Thanks,

Theo

**Comment by EvanPurkhiser** [comment]
Hi @theoscat, could you share anything from your sentry logs, there may be a stacktrace

**Comment by theoscat** [comment]
Hi @EvanPurkhiser,

`81.250.141.104 - - [03/Sep/2018:07:51:28 +0000] "GET /api/0/broadcasts/ HTTP/1.1" 200 501 "http://host:9000/mpg/dev/issues/18/?referrer=slack" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"`

It seems that the request got a 501.

I may be missing something in my conf ?

Theo

**Comment by mattrobenolt** [comment]
That response is a 200. The 501 was the content length.

**Comment by theoscat** [comment]
My bad. Its the only thing showing in my logs so i was desperately searching for something.

It may helps you to know that i'm using docker but with multiple container.
There's a worker, a cron and  the web on different container.

**Comment by EvanPurkhiser** [comment]
@theoscat are you still stuck on this?
