### ISSUE TITLE
Wrong links in menu

### ISSUE THREAD

**Issue by vaisov** [getsentry/sentry#9599]
Version 9.00 on Docker

steps to reproduce:
1. go to Admin Settings 
![image](https://user-images.githubusercontent.com/3081137/45016593-c7637100-b02d-11e8-9f48-bd9e28eaee0b.png)
(in Manage section there's Relays)
2. click on Warnings and see that `Relays` change to `Agents`
![image](https://user-images.githubusercontent.com/3081137/45016631-df3af500-b02d-11e8-824f-3ed1caf56b8a.png)
3. Click `Agents` and get error:
![image](https://user-images.githubusercontent.com/3081137/45016646-eb26b700-b02d-11e8-9447-e4ed80b24bbf.png)

**Comment by markstory** [comment]
Looks this issue was fixed in cc3bcf54f9
