### ISSUE TITLE
Django query strings truncated even with string_max_length set well in excess

### ISSUE THREAD

**Issue by Strum355** [getsentry/sentry#9604]
- The version of Sentry you're using: 9.0.0
- Whether you're using Docker or another installation method: Docker
- Include a stacktrace or other logs when relevant
- Include a redacted version of your configuration when relevant:
```py
SENTRY_MAX_LENGTH_STRING = 100000

RAVEN_CONFIG = {
	...
    'string_max_length': 100000,
    ...
}
```
The character count of the query string ends at around 1030 characters, I've tried with `SENTRY_MAX_LENGTH_STRING` set and not set, with no difference

<details>

![image](https://user-images.githubusercontent.com/18282288/45044915-55108200-b069-11e8-8f3a-6ebd7a1785e4.png)

</details>

Note: the entire query that got printed is just the selected columns

**Comment by nbhuy89** [comment]
Any one working on this? I also face with this issue

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
