### ISSUE TITLE
Can't create new project

### ISSUE THREAD

**Issue by DomLip94** [getsentry/sentry#9695]
Hi, I can't create a new project and receive the error 'A project with this slug already exists.'.

This issue doesn't appear to be related to #8889. Have tried multiple names in different formats, and have made sure the slug doesn't exist.

We installed sentry with Docker.

Initially on DigitalOcean running ubuntu +docker but moved the exported json file over to AWS' EC2 running AMI + Docker.

System for the most part works fine, except this

Sentry Version 9.0.0

Could it be AMI?

**Comment by christophlehmann** [comment]
Same here

**Comment by scaccogatto** [comment]
Happens to me too

**Comment by bilenkis** [comment]
+1

**Comment by ahti** [comment]
I had the same behaviour. The issue for me was that importing the backup of my old instance into my new Docker instance did not set up the postgres sequences used for the primary keys correctly.

The error message is shown for any integrity error (https://github.com/getsentry/sentry/blob/896a2011f0e6d57e897603c854db762b3e88ab30/src/sentry/api/endpoints/team_projects.py#L144-L150) which was a little confusing, but the postgres container logs showed the full errors.

I fixed the sequences as described [on the Postgres wiki](https://wiki.postgresql.org/wiki/Fixing_Sequences), after which Sentry worked fine.

**Comment by ricardoapaes** [comment]
> I had the same behaviour. The issue for me was that importing the backup of my old instance into my new Docker instance did not set up the postgres sequences used for the primary keys correctly.
> 
> The error message is shown for any integrity error (
> 
> https://github.com/getsentry/sentry/blob/896a2011f0e6d57e897603c854db762b3e88ab30/src/sentry/api/endpoints/team_projects.py#L144-L150
> 
> ) which was a little confusing, but the postgres container logs showed the full errors.
> I fixed the sequences as described [on the Postgres wiki](https://wiki.postgresql.org/wiki/Fixing_Sequences), after which Sentry worked fine.

I just did it and it worked. Thanks

**Comment by BYK** [comment]
Closing this as the original issue and other comments seem out of sync and first post is referring to v9 which is quite old at this point. If you are having issues with the latest version please try the [forums](https://forum.sentry.io) first and then file an issue if you are sure this is a bug.
