### ISSUE TITLE
Maybe Gravatar cause `Mixed Content`

### ISSUE THREAD

**Issue by Cospotato** [getsentry/sentry#9713]
## General Support

If you're looking for general support, please utilize our [community forum](https://forum.sentry.io/) rather than GitHub Issues.

## Reporting Bugs

When reporting bugs, include details about your configuration, such as:

- The version of Sentry you're using
`9.0.0`
- Whether you're using Docker or another installation method
`Docker`
- Include a stacktrace or other logs when relevant
`None`
- Include a redacted version of your configuration when relevant
`None`

We Have an user **without** setting `using gravatar` in his own profile. But from the frontend, the api `https://sentry.own.instance/api/0/teams/demo-org/demo-team/members/` has returned the user info with this `avatarUrl`: `https://secure.gravatar.com/avatar/fc2bfe82b0f9dc4f3467da7435530fad?s=32&d=mm`. Request this url will be redirected to `http://i1.wp.com/undefined` which caused the `Mixed Content`.

Best regards,
CosPotato

**Comment by mattrobenolt** [comment]
Fairly confident this PR fixed that as well. 
https://github.com/getsentry/sentry/pull/8865 I know it’s not an issue on current master.
