### ISSUE TITLE
can't report errors from application running on the same machine of on-premise installation

### ISSUE THREAD

**Issue by daton89** [getsentry/sentry#9715]
## On-Premise install

i have a problem with sentry on premise installed with docker and an express application...
when i generate errors in localhost, the errors are correctly reported,
instead when i deploy the express application in production with docker on the same machine,
the application generates:

```
0|pm2   | raven@2.6.3 alert: failed to send exception to sentry: Connection timed out on request to sentry.mydomain.it
0|pm2   | raven@2.6.3 alert: failed to send exception to sentry: socket hang up
```
these containers are behind traefik proxy that manage the requests,
if i try to ping sentry.mydomain.it form the nodejs application container it resolve correctly the domain,
i don't understand why from the node js application it go in timeout, i've tried to improve the timeout window but nothing changed,

anyone can help me to figure out how can i communicate from the node js application to sentry running in docker containers on the same machine?
i guess this is the problem cause from localhost the errors are reported to sentry

- sentry version | 8.22.0
- On-Premise installed with docker behind traefik proxy
- com.docker.compose.version | 1.18.0
-  Docker Version | 17.12.0-ce

**Comment by dmourainatel** [comment]
Hi Daton, i have the same problem.
I'm use literally the same technologies.
Did you resolve it?

**Comment by daton89** [comment]
Hi Diego, no I didn't find a solution for this problem yet. 

The only workaround I found was install sentry on premise on another machine!

**Comment by BYK** [comment]
Hi there! Please use [our forums](http://forum.sentry.io/) for questions like these as the issue board is only for the core Sentry code-related issues.
