### ISSUE TITLE
UTF-8 non-english symbols in message lead to hidden event

### ISSUE THREAD

**Issue by nokitakaze** [getsentry/sentry#9735]
- Sentry/9.0.0
- Python installation via `pip`. New installation, not upgrading from previous version

Non-english symbols in message title have been tested in Sentry/9.0.0? Because **I might think they are not**. I can not send events with russian titles, so I used this script to check it. In version Sentry/8.2+ I had some russian titles.

## Sample
```php
#!/usr/bin/env php
<?php
    $key = 'cb000000000000000000000000000000'; // Zeroed
    $url = "https://{$key}@example.com/api/1/store/";

    $ch = curl_init($url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);// @todo Let's encrypt INCORRECT workaround
    $message_object =
        json_decode('{"event_id":"43339bba1fcf45dbabd6785fb522b1c5","timestamp":"2018-09-12T09:50:20.4159441+00:00","message":"Test Test","platform":"csharp","level":"debug","server_name":"XXXXXX","environment":"Development"}');

    $i = 0;
    $d = gmdate('Y-m-d H:i:s');
    $event_id_midfix = dechex(mt_rand(1 << 23, (1 << 24) - 1));
    foreach ([
                 'English',
                 'Русский', // Russian
                 '日本語', // Japanese
                 'variété de la langue d’oïl', // French
                 'اللغة العربية‎', // Arabic
             ] as $text) {
        $message = "Test #{$i}: {$text} -- {$d}";
        $i++;

        $event_id = dechex(mt_rand(1 << 23, (1 << 24) - 1));
        $message_object->event_id = '43339bba1fcf45dbabd6'.$event_id_midfix.$event_id;
        $message_object->message = $message;
        curl_setopt($ch, CURLOPT_HTTPHEADER, [
            'X-Sentry-Auth: Sentry sentry_version=7,sentry_client=Sentry.NET,sentry_key='.$key.',sentry_timestamp='.time(),
            'Content-Type: text/plain; charset=utf-8',
            'Accept: application/json',
        ]);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($message_object));

        $json = json_decode(curl_exec($ch));
        echo "{$text}\t".(($message_object->event_id == $json->id) ? 'success' : 'error')."\t".json_encode($text)."\n";
    }

    echo "done\n";
?>
```
Accepted events count in `/organizations/sentry/stats/` increases, but only english and french titles appeared.
![01](https://user-images.githubusercontent.com/9131758/45422662-89072b00-b699-11e8-9d30-89a85b7a6d98.PNG)
![02](https://user-images.githubusercontent.com/9131758/45422663-899fc180-b699-11e8-8eb9-501cdbb08e33.PNG)
![03](https://user-images.githubusercontent.com/9131758/45424405-1305c280-b69f-11e8-8604-54aa1a7fae5a.PNG)

**Comment by markstory** [comment]
Do you know if those events are in the API response?

**Comment by nokitakaze** [comment]
No, I didn't check it. I can check it in few hours

**Comment by nokitakaze** [comment]
![default](https://user-images.githubusercontent.com/9131758/45435276-e5c60e00-b6b8-11e8-903c-2bc4654dca02.PNG)

Only two "issues" appeared. With english & french titles. Unfortunately I can't see in my database in issues or events tables

**Comment by nokitakaze** [comment]
Guys, I don't want to complain, but now I have to [transliterate](https://en.wikipedia.org/wiki/Transliteration) exception's message, losing stacktrace. And I think this is critical error because some events just don't appears, while Sentry's user expect appearing if something breaks.

**Comment by markstory** [comment]
I wasn't able to reproduce this problem locally. I am able to send events with Cyrllic characters from the Javascript SDK and view them fine locally.

<img width="822" alt="screen shot 2018-10-01 at 2 15 16 pm" src="https://user-images.githubusercontent.com/24086/46307318-1c9b8f80-c5a6-11e8-9fc4-5000a1c76231.png">

How can someone reproduce this issue?

**Comment by nokitakaze** [comment]
It is... interesting...
I will check DDLs (charset in the first place) of my tables tomorrow. And then I will check logs of Sentry's services. There is some way to enable debug level messages to logs like `-vvv` does in `ssh`?

**Comment by nokitakaze** [comment]
https://pastebin.com/RB5dCyVU
Okay, this is fix for this trouble.

**Comment by markstory** [comment]
> So Sentry's DDLs doesn't have character set?

No we rely on you creating the database with the correct default encoding an character set. Closing as you've found a way to fix your database. For future readers, ensure you use `createdb -U postgres -E utf-8 sentry` to create your postgres database.
