### ISSUE TITLE
CACHES config default to DummyCache causing performance regressions

### ISSUE THREAD

**Issue by 0xdiba** [getsentry/sentry#9738]
Sentry version 9.0.0

By default, Sentry [sets the default django cache to DummyCache ](https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py#L938-L942).

This is not documented and it is not on par with the default behavior of django which uses `LocalMemCache` as a default.
Since `CACHES` is not a mandatory setting and the default behavior is not documented, this causes performance regressions ( over 10ms per request for project options that could have been cached ) if someone decides to set only the `SENTRY_CACHE` option.

The decision to default to `DummyCache` should definitely be documented.
A production default to `LocalMemCache` would make things easier ( although it is not as robust as Memcached or Redis )

**Comment by mattrobenolt** [comment]
Using LocalMemCache would be a bad default since it'd easily cause you to OOM. You should not do this and use memcached if you need caching. I know the two settings are confusing though, but not something that can easily be changed. :/

**Comment by 0xdiba** [comment]
:+1:  on the defaults part.

Nevertheless I think a documentation update mentioning that not setting a django cache effectively means no caching would help, since the 2 cache options ( django cache vs sentry cache ) can get a bit confusing.
