### ISSUE TITLE
Unable to create organizations on a fresh install

### ISSUE THREAD

**Issue by acdha** [getsentry/sentry#9757]
With a fresh Docker install, I ran into two problems:

1. /organizations/new/ fails as the superuser: “Organizations are not allowed to be created by this user”
2. The error message is visible for only a fraction of a second as the page reloads. I used the developer tools to see it but obviously that's not a great answer.

**Comment by ArcticSnowman** [comment]
Ah..  found this in the forums..
https://forum.sentry.io/t/error-create-new-organization/4118

**Comment by ArcticSnowman** [comment]
Given that this is a config setting to restrict to one org, the 'Create Org' UI should not be visible..

**Comment by apptilaus-agent** [comment]
Guys, can anyone share empty db dump with built-in admin of 9.0.0?

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
