### ISSUE TITLE
Regression logic going by release date_added instead of date_released

### ISSUE THREAD

**Issue by lukasgraf** [getsentry/sentry#9771]
**Sentry Version**: 9.1.0.dev0 (current `master` at 913ca9c2)
**OS**: macOS 10.13.5

*Edit: I thoroughly searched the issue tracker for similar issues, but didn't think to do so for the community forum. The behavior described here actually could be related:* https://forum.sentry.io/t/issues-incorrectly-re-opened-as-regressed/3795

### Expected behavior

This issue happens when creating releases out-of-order, as is often the case with **backport releases**. Say we've released `8.0` and `8.1` in the past. `8.0.x` is our LTS branch, and we've now fixed a bug that got backported to `8.0.x`. We therefore would release a version `8.0.1` *after* `8.1` has already been released.

These releases, chronologically speaking, will have been created in the order
- `8.0`
- `8.1`
- `8.0.1`

I would have expected that using the `sentry-cli release finalize` command (or the REST API to set `dateReleased`) would allow me to tell Sentry about the correct ordering of those releases.

But this doesn't work: Even after bringing the releases into the correct order (according to `dateReleased`, via `sentry-cli`), regression detection gets it wrong: If I resolve an issue that occured in `8.0` as fixed in `8.1`, it will flag it as a regression if it happens again in `8.0.1`.

### Actual behavior

The logic for detecting a regression ignores `date_released`, and instead uses `date_added` (which it seems can't be changed via the `sentry-cli` or the REST API). This leads to issues being flagged as regression that actually aren't.

The bug (IMHO) happens in [`GroupResolution.has_resolution()`](https://github.com/getsentry/sentry/blob/913ca9c2255eae8cafd553ff23840e4e1f0b6e2d/src/sentry/models/groupresolution.py#L45-L80) - that method compares the event's release's `date_added` against the group resolution's releases' `date_added`, when in fact it should be `date_released`.

### Steps to reproduce

*(--url and --auth-token parameters omitted for readability)*

- Create three releases in a non-linear order:
    ```bash
    $ sentry-cli [...] releases -o sentry new -p example 8.0
    Created release 8.0.
    $ sentry-cli [...] releases -o sentry new -p example 8.1
    Created release 8.1.
    $ sentry-cli [...] releases -o sentry new -p example 8.0.1
    Created release 8.0.1.
    ```
So while 8.1 is a **higher** release than 8.0.1, it has chronologically been created **before**.

- Finalize the releases in their proper order, therefore updating their `dateReleased`:

```
$ sentry-cli [...] releases -o sentry finalize 8.0
Finalized release 8.0.
$ sentry-cli [...] releases -o sentry finalize 8.0.1
Finalized release 8.0.1.
$ sentry-cli [...] releases -o sentry finalize 8.1
Finalized release 8.1.
$ sentry-cli [...] releases -o sentry list

+----------------+---------------+------------+----------------+
| Released       | Version       | New Events | Last Event     |
+----------------+---------------+------------+----------------+
| 28 seconds ago | 8.1           | 0          | -              |
| 40 seconds ago | 8.0.1         | 0          | -              |
| 55 seconds ago | 8.0           | 0          | -              |
+----------------+---------------+------------+----------------+
```

So according to `releasedDate`, 8.1 now comes after 8.0.1, as reflected in the listing.

- Send an event to Sentry with its release tagged to `8.0`
- Mark that issue as resolved in `8.1` in Sentry
- Send another event with the same fingerprint tagged with release `8.0.1`

=> The issue is flagged as a regression, even though according to ordering by `dateReleased`, `8.1` should be considered a higher version than `8.0.1`.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.

/cc @mitsuhiko in case somebody is working on this.
