### ISSUE TITLE
Add spaces in issue header

### ISSUE THREAD

**Issue by AlexWayfer** [getsentry/sentry#9785]
- Sentry 9.0.0
- Docker installation method

Please, add spaces between `span.error-level`, `span.message` and `span.event-annotation`: I can't normally copy text from `.message` by double click — content of neighboring elements also copied.

Example of copy-pasted words from message in comment field, and selected `message` word by double click:

![image](https://user-images.githubusercontent.com/6510020/45639109-c879b100-bab7-11e8-964b-da22e7862825.png)

Just space between `</span> <span>` helps.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
