### ISSUE TITLE
Improve Search documentation

### ISSUE THREAD

**Issue by ramsrib** [getsentry/sentry#9790]
Search Bar says:
<img width="499" alt="screen shot 2018-09-17 at 2 56 38 pm" src="https://user-images.githubusercontent.com/1449806/45652812-b897a800-ba8a-11e8-8b4c-c968f9488c9d.png">

But using `#` with event-id doesn't work. And the sentry [documentation](https://docs.sentry.io/learn/search/) doesn't have any information about search using `#`.

#### Improvements:
- An example in the documentation will help
- Also the search bar placeholder can be improved (i.e above image).

**Comment by benvinegar** [comment]
I think `#` there is just a filler icon so that it matches the other examples, but I agree it's confusing.

**Comment by BYK** [comment]
Closing this issue due to staleness. Feel free to comment here if you think we should still work on this.
