### ISSUE TITLE
File content are not uploaded even though the database says the file exists

### ISSUE THREAD

**Issue by geekyme** [getsentry/sentry#9810]
- The version of Sentry you're using: **9.0.0**
- Whether you're using Docker or another installation method: **docker**
- Include a stacktrace or other logs when relevant: See **https://forum.sentry.io/t/cannot-find-source-maps-for-on-premise-sentry-9-0-0/4699**

Same issue as https://github.com/getsentry/sentry-cli/issues/141, why are the files not there?

**Comment by geekyme** [comment]
I reinstalled sentry in my kubernetes cluster. It works now. Might have been some silent errors on the volume mounting. https://github.com/geekyme/typescript-app-sentry

**Comment by gregwym** [comment]
This happened to us today after we lost our local files. When trying to upload a file that has existed before, Sentry would not store them onto the file system. We solved it by flush all file related tables in db.
