### ISSUE TITLE
Notification option to automatically re-trigger notifications of unresolved events

### ISSUE THREAD

**Issue by simonpercivall** [getsentry/sentry#987]
A feature to track when last notifications were triggered for a group, and if a set period of time has passed, trigger notifications again.

This would be a nice way to deal with transient errors, errors that aren't "resolved", and you don't want to mark them as such, but you'd like a notification if they happen again.

**Comment by BYK** [comment]
After years of waiting, this is now (well, by 2015) available: https://blog.sentry.io/2015/11/19/snoozing-issues 😀
