### ISSUE TITLE
pypi page looks strange

### ISSUE THREAD

**Issue by guettli** [getsentry/sentry#9877]
## General Support
Please have a look at this page:

https://pypi.org/project/sentry/

I guess it should not look like this:

```
Project description
.. raw:: html

<p align="center">
<p align="center">
<img src="https://sentry-brand.storage.googleapis.com/sentry-logo-black.png" alt="Sentry" height="72"
</p>
<p align="center">
Users and logs provide clues. Sentry provides answers.
</p>
</p>
```

**Comment by mattrobenolt** [comment]
Yeah, this will be fixed on next release. You can't update it for an existing release because they are immutable.
