### ISSUE TITLE
GitHub Integration not installing after authorization

### ISSUE THREAD

**Issue by prescottprue** [getsentry/sentry#9936]
Integration is installed on Github's side, but Sentry.io still says it is not installed:

![image](https://user-images.githubusercontent.com/2992224/46228278-771ebc80-c316-11e8-938c-bd14ee7d4dc7.png)

Have attempted install multiple times - each time a request it generated on github's side and approved, but nothing changes in Sentry. Also tried logging in and out of Sentry multiple times.

**Comment by benvinegar** [comment]
I've recreated this on our end. We're investigating.

Thanks @prescottprue.

**Comment by mkg20001** [comment]
Still happening. Any fix?

**Comment by willyyang** [comment]
@mkg20001 how long does it take to sync up ?

**Comment by willyyang** [comment]
which button? It's been 3 hours now and sentry still doesn't see the installed GitHub integration

**Comment by mkg20001** [comment]
The connect button that opens the github prompt. Just repeatedly press and pray

**Comment by willyyang** [comment]
@benvinegar How's the investigation going ? This seems like a critical issue ...

**Comment by MeredithAnya** [comment]
There are two ways (that I can think of) in which you could end up in the scenario where GH shows the install and Sentry doesn't:
1. You go through the installation flow (redirected from Sentry to GH to choose your GH organization and selected repositories) and something failed in the authorization step after you clicked 'install' button on the choose your repositories page. The GH installation is already created but something went wrong on our end and we failed to connect the install to your organization. If this is the case, you'd need to uninstall from GH's end before retrying. If this still fails repeatedly, you'll need to contact support@sentry.io so we can debug your specific organization and see what's failing.

2. You go through the installation flow and see 'Configure' for the GH organization you're attempting to install Sentry on.
![screen shot 2018-11-28 at 10 37 46 am](https://user-images.githubusercontent.com/15368179/49174631-a5f7e580-f2fb-11e8-832d-4cab5484f736.png)
 If you haven't tried to set up the integration on the current Sentry organization you are in but you see this, it means it's already installed on another Sentry organization. GH only allows for a 1:1 relationship between a GH app installation and organization, meaning that if you have multiple Sentry organizations, only one of them can be linked with a specific GH app. 

@mkg20001 It definitely should have been pretty instantaneous so I'm not exactly sure how things worked in your case - @willyyang if you are still having issues and haven't written into support@sentry.io yet (and nothing above helps explain what you're experiencing) you should contact support so we can get the specifics.

**Comment by mrlubos** [comment]
Same issue here, I have requested access to a repository for Sentry, it's been approved, shows as installed in the Github popup, but Sentry shows nothing.

**Comment by bill-pairaktaridis** [comment]
This is still very much an issue. In my case, I'm the sole user on Sentry but the GH org is owned by someone else, even though I'm the admin of the repo I want access to. Request gets approved but never shows up on Sentry. Have tried a dozen times so far.

**Comment by mrlubos** [comment]
I have now tried granting Sentry access to all repositories, still the same result, nothing changed in Sentry even though access has been granted. @benvinegar @MeredithAnya

**Comment by dhhagan** [comment]
Did this ever actually get solved? I've tried uninstalling and re-installing the integration several times (and i'm the admin on the GitHub team account) and still...nothing :(

**Comment by wallynm** [comment]
Having the same issue, tried to uninstall but didn't worked

**Comment by bill-pairaktaridis** [comment]
On my end, Sentry support confirmed that I have to be the **owner** of the repo, which is ridiculous for organizations. We have a dozen or so repos that are, of course, not owned by the individual developers but our head manager. The solution seems to be to upgrade from the Free plan and add the owner to your Sentry team and then it all gets sorted.

**Comment by cinnamennen** [comment]
I am an owner of the organization I am trying to integrate with, but still facing this same issue. Are there any known workarounds/fixes?

**Comment by mrlubos** [comment]
👻

**Comment by Rom1-J** [comment]
Same issue today...
