### ISSUE TITLE
Members are asked to create a team when they don't have permission

### ISSUE THREAD

**Issue by benvinegar** [getsentry/sentry#9943]
![image](https://user-images.githubusercontent.com/2153/46260556-60a26d80-c49c-11e8-9808-c8f23876c9aa.png)

Note the "Create Project" button in the top-right is correctly greyed out, but we still invite them to click "Create a project", which opens the following modal:

Which
![image](https://user-images.githubusercontent.com/2153/46260565-86c80d80-c49c-11e8-8242-32b2bf8dcde7.png)

_Aside: The copy here is very confusing_

If you attempt to create a project from this modal, you are still blocked at the API-level, and you get the following obtuse error in the toast popup:

![image](https://user-images.githubusercontent.com/2153/46260572-9c3d3780-c49c-11e8-901a-9e1f986cc4ed.png)

**Comment by rpanczer** [comment]
Hi @benvinegar, I'd like to take care of this one

**Comment by rpanczer** [comment]
Ok cool  - I'll work on this today after work but if someone beats me, no problem

**Comment by billyvg** [comment]
This has been fixed 
![image](https://user-images.githubusercontent.com/79684/66157451-abd3ec80-e5d8-11e9-9a85-42e3212d08f1.png)
