### ISSUE TITLE
[DOC] 'Retrieve a Project' and 'Update a Project' quotes: 'the slug of the project to delete.'

### ISSUE THREAD

**Issue by retomerz** [getsentry/sentry#9948]
Both pages 'Retrieve a Project' [1] and 'Update a Project' [2] quotes this

> Parameters:     project_slug (string) — the slug of the project to delete. 

![image](https://user-images.githubusercontent.com/9657405/46286383-47262200-c57f-11e8-8057-a97f8eedb890.png)

Seems to be a Copy&Paste error from the 'Delete a Project' page.

[1] https://docs.sentry.io/api/projects/get-project-details/
[2] https://docs.sentry.io/api/projects/put-project-details/

**Comment by untitaker** [comment]
Hi, could you refile this against getsentry/sentry-docs? Thanks!

**Comment by markstory** [comment]
This issue was moved to getsentry/sentry-docs#412
