### ISSUE TITLE
Different issues automatically merged

### ISSUE THREAD

**Issue by AlexWayfer** [getsentry/sentry#9970]
## Important Details

How are you running Sentry?

* [x] On-Premise docker [Version 9.0.0]
* [ ] Saas (sentry.io)
* [ ] Other [briefly describe your environment]

## Description

Absolutely different issues were automatically merged.

## Steps to Reproduce

I don't know, it's accident automatically.

![image](https://user-images.githubusercontent.com/6510020/46345757-65a71e80-c64e-11e8-8a00-7b8aed917cdc.png)

There is no messages "somebody merged 1 issue into this" (because nobody merged something):

![image](https://user-images.githubusercontent.com/6510020/46345782-7b1c4880-c64e-11e8-8f04-23adfb928aa5.png)

We also already have a normal issue about `gCrWeb`:

![image](https://user-images.githubusercontent.com/6510020/46345866-cb93a600-c64e-11e8-9fd9-b54893051265.png)

### What you expected to happen

These issues from IE11 and Chrome on iOS with different messages should not be merged.

### Possible Solution

Don't merge issues if their messages are different.

**Comment by markstory** [comment]
Do the issues have similar stack traces? Sentry uses stack frame information to calculate similarity and group events together.

**Comment by AlexWayfer** [comment]
> Do the issues have similar stack traces?

Raw from IE:

```
TypeError: Object doesn't support property or method 'assign'
  at Anonymous function(/d6safundjenk6af/21670/042f041304250446044f0c3e04220bd20c45.js:1:31401)
  at a1256157352(/d6safundjenk6af/21670/c/6765747472616e73706f72742e636f6d_0.js:1:7310)
  at wrapped(raven.js:412:9)
```

From iOS:

```
TypeError: null is not an object (evaluating '__gCrWeb.form.wasEditedByUser.set')
  at wrapped(raven.js:412:21)
```

**Comment by markstory** [comment]
The iOS stack frame is pretty small which is likely why it is getting grouped in a way you aren't expecting.

**Comment by markstory** [comment]
Unfortunately changing how issues are grouped is a fairly fundamental change and not something we're likely to do as it would effect a significant number of users/customers.

Given that sentry is doing what its supposed to (group issues based on stacktrace fingerprints) I'm going to close this.
