### ISSUE TITLE
GitHub Integration: Can not add a repo

### ISSUE THREAD

**Issue by ChrisThompsonTLDR** [getsentry/sentry#9972]
![github sentry](https://user-images.githubusercontent.com/348801/46347819-ddf3ec80-c61a-11e8-9f14-99e246a3cd27.png)

GitHub + Sentry integration completed successfully, but we are unable to add a repo to Sentry.

**Comment by ChrisThompsonTLDR** [comment]
sentry.io.  There was a link on the setup/integration page that said something like "report an issue" and it brought me here.

**Comment by markstory** [comment]
Does your user role have the `org:write` permission? That is required to make the drop down not disabled. https://github.com/getsentry/sentry/blob/edb92c6c20cb6f8309742fceb043ac4f64722e57/src/sentry/static/sentry/app/views/organizationIntegrations/integrationRepos.jsx#L175-L185

**Comment by ChrisThompsonTLDR** [comment]
User role on what?  I'm an admin on sentry.io and a org owner on github.

**Comment by ChrisThompsonTLDR** [comment]
@markstory we received a random email today from Sentry.io, requesting new GitHub permissions.  We accepted and can now add repos.
